### ISSUE TITLE
array of primitives field support

### ISSUE THREAD

**Issue by Kml55** [realm/realm-java#1002]
Is there a plan for arrays of primitives support in modal classes. I faced with a case that json returns from ws has a field of array of ints not objects. I can not put a field like that **private int[] categoryIds;**
in my realm modal class. Support for this will be great for us.

**Comment by emanuelez** [comment]
This is already tracked in this issue: #575 
Please refer to that for progress.
In the mean time you can use wrapper classes for the primitive types.
