### ISSUE TITLE
io.realm.exceptions.RealmException: Primary key constraint broken. Value already exists:

### ISSUE THREAD

**Issue by jofor** [realm/realm-java#1003]
I'm trying to store a single unique object that should hold settings for the application.

The unique object in question, has the

@PrimaryKey
private String name = "UsageMode";

annotation declared to tell that only one object with this name should be allowed to exist.

the class looks like this: https://gist.github.com/jofor/164ed4c7e3c32554c6b9

When I try to run:
UsageMode usageMode = new UsageMode(input);
mRealm.beginTransaction();
mRealm.copyToRealmOrUpdate(usageMode);
mRealm.commitTransaction();
mRealm.close();

i get: Caused by: io.realm.exceptions.RealmException: Primary key constraint broken. Value already exists:

(this after I have created the object once)

This would not be the functionality i'd be after. I'd want it do update the new mode-attribute and not fail because the object already exists. Maybe this was not how PrimaryKey was meant to be used, but I think the need to store unique single objects that we can update attributes on, does exists for the users of realm :)

The version i'm using is 0.80.0

**Comment by cmelchior** [comment]
Hi @jofor 
From a quick glance it looks like you are getting hit by this bug here: https://github.com/realm/realm-java/issues/993

We just merged a fix for this, so can you try again with our SNAPSHOT release to see if you still have this problem?

```
repositories {
        jcenter()
        maven {
            url 'http://oss.jfrog.org/artifactory/oss-snapshot-local'
        }
    }

    compile 'io.realm:realm-android:0.80.1-SNAPSHOT'
```

**Comment by cmelchior** [comment]
I assume the above fixed your issue, otherwise please reopen this.
