### ISSUE TITLE
copyToRealm() tries to copy nested objects even if they are already in the Realm

### ISSUE THREAD

**Issue by RobertoArtiles** [realm/realm-java#1006]
Hey guys,

This piece of code leads to the exception ```Caused by: io.realm.exceptions.RealmException: Primary key constraint broken. Value already exists: brother```
```java
        realm.beginTransaction();
        UserRealm brother = realm.createObject(UserRealm.class);
        brother.setToken("brother");

        UserRealm user = new UserRealm();
        user.setToken("token");
        user.setBrother(brother);
        realm.copyToRealm(user);
        realm.commitTransaction();
        }
```

Changing ```copyToRealm``` to ```copyToRealmOrUpdate``` solves it. Using ```UserRealm user = realm.createObject(UserRealm.class)``` also solves it. It looks like even though ```brother``` is an object from the DB, Realm anyway treats it as a new object during the ```copyToRealm()```. It's either a bug, or a confusing design.

**Comment by cmelchior** [comment]
It is actually the intended design. ```copyToRealm()``` always create a new copy, while ```copyToRealmOrUpdate``` updates if possible. I can see why the interaction with ```@PrimaryKey``` might be a bit subtle and the functionality of ```copyToRealmOrUpdate``` is probably the one that people are going to want the most, but being able to create new copies is also a use case we cannot ignore.

While we could detect if the model has a primary key and switch to copyOrUpdate for those models even if copyToRealm is used, I think that behaviour would confuse people as well.

It might be a matter of either clarifying the behaviour in the JavaDoc or finding some better method names?

**Comment by RobertoArtiles** [comment]
Hey Christian,

Thanks for the explanation. Just to explain what was in my head when I called ```user.setBrother(brother);```. I thought that I'd linked this new user to another one in the DB. Of course, when you start thinking about it, you can rationalise why it works in a different way. But I think it might be a sign that there is something wrong with this method. Documentation could partially solve this issue, but ideally to have it as self explanatory as possible. Naming might something you want to consider.
In general, I think stuffs' default behaviour should be as obvious and natural as it could be, and all this advanced features should require some explicit extra work in order to achieve some rarely used behaviour.

**Comment by cmelchior** [comment]
Thanks for the feedback, it is the only way we can improve the API :)

That said, looking at this with fresh eyes and from you description, I might be inclined to file this as a bug instead. As you said, the brother object already exists in the database (which we very easily can detect), and if you do copyToRealm with ```brother`` as you top level object, it actually does nothing because this is checked for the top level object, but not nested objects. So the current behaviour is not consistent.

**Comment by RobertoArtiles** [comment]
Cool, thanks!
