### ISSUE TITLE
SerializedName & SerializedDateFormat not working

### ISSUE THREAD

**Issue by StephenMilone** [realm/realm-java#1009]
Having two issues with turning my models in RealmObjects.

Currently the json object my server is giving includes a property with the key "default" and a boolean value. 

`private boolean default;`
Will not compile with an expected error so I've tried the following:

`@SerializedName("default")
private boolean cardDefault;`

The values are always false regardless of json object value passed.

Secondly, I'm also trying to use the following on a Date variable
`@SerializedDateFormat("yyyy-MM-dd'T'HH:mm:ssZ")` 
and it won't compile cause it can't resolve symbol. 

My project uses Realm 0.80 and has Gson 2.3 added as well. please advise. thank you

**Comment by cmelchior** [comment]
Hi @StephenMilone 

Do you have an some example JSON and how you determine that ```cardDefault``` is false?

```@SerializedDateFormat``` is not something we have implemented yet, which is why it cannot resolve. I guess you read it here: https://github.com/realm/realm-java/issues/546. It is just a proposal for a future API, so might be subject to change as well.

You can see how to configure GSON dates here: http://stackoverflow.com/questions/6873020/gson-date-format

**Comment by StephenMilone** [comment]
Thanks for the response.  Here is an example object

{
    "default": true,
    "updatedAt": "2015-04-03T22:21:00Z"
}

**Comment by cmelchior** [comment]
If you have configured the GSON date parser properly there as in the above link there shouldn't be any problems importing that JSON structure. Can you show how your data gets imported into Realm and how your model class looks like?

**Comment by StephenMilone** [comment]
The server gives me a json array, which I then do the following:

        realm.beginTransaction();
        realm.createOrUpdateAllFromJson(realmClass.class, serverResponse.toString());
        realm.commitTransaction();

My model class is nothing special. Just used android studio generated getters/setters. nothing else to it, and everything else works wonderfully except this one variable, as its the only one i need to use serialized name for.

I'm more concerned about the getting 'default' to work, the date I should be able to get under control now that i know its dateformat is not implemented. thanks!

**Comment by cmelchior** [comment]
Hi @StephenMilone 
Sorry for the late response.

If you want to use the ```@SerializedName``` annotation you have to use GSON as it is a GSON annotation, not a Realm one.

The method ```Realm.createOrUpdateAllFromJson()``` only supports importing JSON that matches the model class 1:1. In your case you need to use ```Realm.copyToRealmOrUpdate()``` with a object created by a GSON parser. You can see more here: http://realm.io/docs/java/#gson 

```
Gson gson = new GsonBuilder()
        .setExclusionStrategies(new ExclusionStrategy() {
            @Override
            public boolean shouldSkipField(FieldAttributes f) {
                return f.getDeclaringClass().equals(RealmObject.class);
            }

            @Override
            public boolean shouldSkipClass(Class<?> clazz) {
                return false;
            }
        })
        .create();

List<RealmClass> objects = gson.fromJson(RealmClass.class, serverResponse.toString());
realm.beginTransaction();
realm.copyToRealmOrUpdate(objects);
realm.commitTransaction();

**Comment by StephenMilone** [comment]
worked! thank you so much. here is the code I used, as I'm actually getting an array of these from the server. 

        Gson gson = new GsonBuilder()
                .setExclusionStrategies(new ExclusionStrategy() {
                    @Override
                    public boolean shouldSkipField(FieldAttributes f) {
                        return f.getDeclaringClass().equals(RealmObject.class);
                    }

                    @Override
                    public boolean shouldSkipClass(Class<?> clazz) {
                        return false;
                    }
                })
                .create();

        RealmClass[] objects = gson.fromJson(serverResponse, RealmClass[].class);
        realm.beginTransaction();
        realm.copyToRealmOrUpdate(Arrays.asList(objects));
        realm.commitTransaction();
