### ISSUE TITLE
arm64-v8a library not present in the eclipse folder from the zip distribution

### ISSUE THREAD

**Issue by eboudrant** [realm/realm-java#1012]
Hi, looks like it is only present in the realm-0.xx.0.jar. 
ps : I was trying the apk split using gradle and your doc mention to use the eclipse folder (http://realm.io/news/reducing-apk-size-native-libraries/).
Thanks

**Comment by emanuelez** [comment]
Thanks for pointing that out! We will fix that ASAP. In the mean time you can extract such folder from the jar file itself.
