### ISSUE TITLE
Cant perform min() on a foreign field

### ISSUE THREAD

**Issue by degill** [realm/realm-java#1016]
It seems that I cant perform a min() (and possibly other operations like max()) for a foreign field like the following:

```
mAllFriends.min("name.length").intValue()
```

Executing that results in java.lang.ArrayIndexOutOfBoundsException: columnIndex is less than 0.

I looked a bit in the issues here on GitHub and found that it correlates to this issue https://github.com/realm/realm-java/issues/709

Can someone confirm this?

Thank you :)

Ps.: Same applys to `RealmQuery.findAllSorted()` (I am mentioning this also because the error messages are different. In the case of `findAllSorted` the message is `Field name 'xxx' does not exist.`)

**Comment by cmelchior** [comment]
Hi @gillde 

No, you are right. Currently we don't support those methods across links, although the error message could be a lot better and we should fix that. 

But I am not sure I understand your use case. Keep in mind that Realm is an object store not a relational database, so the way data is queried will be a a bit different from SQL in some cases.

Can you elaborate on what exactly you are querying and what you expect the result to be?

**Comment by gillde** [comment]
I am trying to query a table which acts a little like a linking table (m:n relation). And I am trying to get those elements, sorted by a field of an object that exists in that row.

```
class A {
    String name;
}

class B {
    int score;
}

class C {
    A a;
    B b;
}

So I am querying C with some constraints for ```a``` and ```b``` but sorted by ```score```.

I figured out how to do that with our model.

**Comment by valls** [comment]
Same feature required here. We are trying to sum() values of linked object.
We have to use the following approach (workaround):

```java
RealmResults<TripDB> result = realm.where(TripDB.class).between("fromDate", dateFrom, dateTo).findAll();
if(result != null && result.size() > 0) {
    RealmQuery<TripContextualScoreDB> query = realm.where(TripContextualScoreDB.class);
    query.equalTo("type", type);
    query.beginGroup();
    for(int i=0; i< result.size(); i++) {
        if(i > 0) {
            query.or();
        }
        query.equalTo("tripId", result.get(i).getTripId());
    }
    query.endGroup();
    distance = (double) query.findAll().sum("contextualDistance");
}
```

Ideally, with this feature we could change code above by this:

```java
RealmResults<TripDB> result = realm.where(TripDB.class).between("fromDate", dateFrom, dateTo)
.equalTo("tripContextualScore.type", type).findAll()
.sum("tripContextualScore.contextualDistance");
```
We have to use same workaround for avg() soon.

**Comment by cmelchior** [comment]
Folding this issue into #1598
