### ISSUE TITLE
Realm migration

### ISSUE THREAD

**Issue by guichico** [realm/realm-java#1019]
I am doing migration with realm, but have some things that are not clear for me.
Can you answer me some questions?

First of all, I am running migration in a try, catch in getInstance of realm, like...

```
Realm realm = null;
        try {
            realm = Realm.getInstance(this);
        } catch (RealmMigrationNeededException ex) {
            String path = String.format("%s/default.realm", getFilesDir().getPath());
            if (new File(path).exists()) {
                Realm.migrateRealmAtPath(path, new Migration());
            }
        }
```

It is correct? Because I continue receiving the RealmMigrationNeededException. It is possible that the migration is not being executed?

I get the exception in another part of code when I try to getInstance again. Is the migration executed in any thread?

**Comment by Bruno-Furtado** [comment]
+1.
I have the same problem.

**Comment by cmelchior** [comment]
```Realm.migrateRealmAtPath()``` is a blocking call that won't return until the migration is complete, so you got the right pattern. It just looks like you need to fix the path.

Try this instead:
```
Realm realm = null;
try {
    realm = Realm.getInstance(this);
} catch (RealmMigrationNeededException ex) {
    File realmFile = new File(getFilesDir(), "default.realm");
    Realm.migrateRealmAtPath(realmFile.getAbsolutePath(), new Migration());
}
```

**Comment by guichico** [comment]
Ok, thank you for the answer.
Let me do another question, when a new object is create that is the correct code to create a table in the realm?

```
        if (version == 2) {
            Table photoTable = realm.getTable(PhotoUri.class);
            long columnIndex = photoTable.getColumnIndex("uri");

            if (columnIndex == -1) {
                photoTable.addColumn(ColumnType.STRING, "uri");
            }

            version++;
        }
```
Because sometimes I still getting the error RealmMigrationNeededException: Field 'uri' not found for type 'PhotoUri'.

**Comment by cmelchior** [comment]
Hi @guichico 
The path might differ from device to device (which is the reason we are using Context.getFilesDir()), but it should be the same on the device. So if you are getting such an error it is because you are running your Migration code on another Realm than the one you are opening. If you have multiple Realm files you need to migrate all of the them. 

You would see the above error if you ran your first version of your code.

**Comment by cmelchior** [comment]
I assume the above answered you question. Please reopen if that is not the case.
