### ISSUE TITLE
Crash with most recent WebView

### ISSUE THREAD

**Issue by softkot** [realm/realm-java#1023]
I found very unusual combination of crypted Realm and most recent WebView component from google.
The crash happening almost instantly even try to open simple about:blank url insife WebUrl and having Realm crypted database opened. If try to use non crypted backend or old WebVew components the crash does not happens.

Log cat shows folluwing details:

> E/chromium( 6573): ### WebView Version 40 (1832189-arm) (code 424501)
> F/libc    ( 6573): Fatal signal 11 (SIGSEGV), code -6, fault addr 0x19ad in tid 6624 (Thread-16916)
> I/DEBUG   (  186): *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
> I/DEBUG   (  186): Build fingerprint: 'google/hammerhead/hammerhead:5.1/LMY47D/1743759:user/release-keys'
> I/DEBUG   (  186): Revision: '11'
> I/DEBUG   (  186): ABI: 'arm'
> I/DEBUG   (  186): pid: 6573, tid: 6624, name: Thread-16916  
> I/DEBUG   (  186): signal 11 (SIGSEGV), code -6 (SI_TKILL), fault addr 0xa152e000
> I/DEBUG   (  186):     r0 aef1e1c0  r1 aef1e1d9  r2 a152e000  r3 00000000
> I/DEBUG   (  186):     r4 00000019  r5 00000000  r6 aec6511c  r7 00000000
> I/DEBUG   (  186):     r8 aec650c0  r9 9fdbb040  sl aec65110  fp a2104904
> I/DEBUG   (  186):     ip b6de47dc  sp a21048f8  lr a2f5dee9  pc a2f31fcc  cpsr 800f0030
> I/DEBUG   (  186):
> I/DEBUG   (  186): backtrace:
> I/DEBUG   (  186):     #00 pc 0005dfcc  lib/arm/libtightdb-jni.so
> I/DEBUG   (  186):     #01 pc 0005e043  lib/arm/libtightdb-jni.so
> I/DEBUG   (  186):     #02 pc 0005fb03  lib/arm/libtightdb-jni.so
> I/DEBUG   (  186):     #03 pc 00068e93  lib/arm/libtightdb-jni.so (Java_io_realm_internal_SharedGroup_nativeCommitAndContinueAsRead+42)
> I/DEBUG   (  186):     #04 pc 0014bb8f  @base.apk@classes.dex
> I/DEBUG   (  186):
> I/DEBUG   (  186): Tombstone written to: /data/tombstones/tombstone_05

Thus i am running non rooted device it seems i can't get tombstone_05 file if it has some useful data.

**Comment by cmelchior** [comment]
Hi @softkot 
It sounds like the exact same error that is happening here #1008 . Here it just gets triggered by accessing the CookieManager from Chromium manually when running multiple background threads.

If you are able to reproduce this without using multiple threads we would be very very interested in a reproducible test case.

**Comment by softkot** [comment]
Ok here you are https://github.com/softkot/realm-issue1023

**Comment by cmelchior** [comment]
Thank you very much for the project. I altered you code a bit to make it simpler (removed the handler) and it still crashes with the same error. I have moved the code into #1008 as it very much look like the same error. You can follow the progress there instead and I will close this as an duplicate.
