### ISSUE TITLE
Could not find io.realm.RealmJsonImpl

### ISSUE THREAD

**Issue by emreaktrk** [realm/realm-java#1024]
You can check the problem by pulling bug/realm branch.

Good luck there.

https://github.com/emreaktrk/EdgeContact/tree/bug/realm

**Comment by emreaktrk** [comment]
I have changed all structure all the way down, and same issue.
Am i missing something or it should be really horrible bug?

**Comment by cmelchior** [comment]
Try changing your model class to:

```
final class Contact extends RealmObject {

    private CharSequence mName;

    public CharSequence getmName() {
        return mName;
    }

    public void setmName(CharSequence mName) {
        this.mName = mName;
    }
}
```
Right now we have pretty strict requirements for the getter and setter names compared to the field variabel in order to validate the model class. It is something we hope to relax soon though.

**Comment by emreaktrk** [comment]
I just figured out the problem.
As you said, there is a problem with Hungarian notation.
Btw, i also cannot use mName as property name, required default empty args constructor and public class modifier.

PS for others : Just avoid Hungarian notation and trust Android Studio's refactoring to create getter and setters. Do not modify them!

Anyway, thanks for your help.
