### ISSUE TITLE
Subclass a subclass of RealmObject

### ISSUE THREAD

**Issue by jinthagerman** [realm/realm-java#1025]
I'm relatively new to Realm, Java and Android and I was wondering whether you can subclass a subclass of RealmObject and if that subclass would then work as expected.

**Comment by cmelchior** [comment]
Hi @jinthagerman 
Unfortunately not yet. However it is something we have on our TODO and want to fix: https://github.com/realm/realm-java/issues/761

For now you will have to duplicate fields between model classes, sorry.

**Comment by donaldking** [comment]
Any update on this? when will this feature be available?

**Comment by Zhuinden** [comment]
[Considering it's "blocked on core" and "idea backlog" for Realm-Cocoa](https://github.com/realm/realm-cocoa/issues/1109) which is far ahead in terms of features (they have Results integration and fine-grained notifications too, for example), you should probably resolve this problem in a different way. For example, interfaces.
