### ISSUE TITLE
UnsatisfiedLinkError running Android tests on x86 and ARM Emulator

### ISSUE THREAD

**Issue by n0k** [realm/realm-java#1034]
Hi,

I'm encountering an issue getting Realm tests to run on the emulator in Android Studio. I've defined some tests like:

public class RealmManagerTest extends AndroidTestCase {
    private Realm mRealm;

    public void setUp() throws Exception {
        mRealm = Realm.getInstance(getContext());
    }

    public void tearDown() throws Exception {
        mRealmManager.close();
    }

    public void test1() {
    	// ...
    }
    
    public void test2 {
    	// ...
    }
}

when I've executed the tests I get a link error relates to libtightdb-jni.so:

Running tests
Test running started
java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/system/framework/android.test.runner.jar", zip file "/data/app/com.myprojects.nikhil.myapp.test-2/base.apk", zip file "/data/app/com.myprojects.nikhil.myapp.test-2/base.apk"],nativeLibraryDirectories=[/vendor/lib, /system/lib]]] couldn't find "libtightdb-jni.so"
at java.lang.Runtime.loadLibrary(Runtime.java:366)
at java.lang.System.loadLibrary(System.java:989)
at io.realm.internal.TightDB.loadLibrary(TightDB.java:144)
at io.realm.internal.SharedGroup.<clinit>(SharedGroup.java:34)
at io.realm.Realm.<init>(Realm.java:204)
at io.realm.Realm.createAndValidate(Realm.java:522)
at io.realm.Realm.create(Realm.java:486)
at io.realm.Realm.getInstance(Realm.java:404)
at io.realm.Realm.getInstance(Realm.java:366)
at io.realm.Realm.getInstance(Realm.java:347)

I'm using realm-0.80.0.jar and have tried gradlew clean assemble to no effect. My app is using Android 5.0.1 API 21 for both ARM and x86.

**Comment by cmelchior** [comment]
Hi @n0k 
That code looks fine. How are you executing your tests? Are you by any chance using Robolectric?

**Comment by n0k** [comment]
Hi Christian,

No, I'm not using Robolectric with the tests. I created an Android test case configuration in Android Studio and am running the tests with that in an emulator I've defined with AVD. I'm wondering if something is wrong in my gradle file. The tests are defined in a library that is used by the main app module. I've reproduced the library gradle file below. I also checked the Realm wiki to determine if I'm missing anything but nothing is jumping out at me. I'm getting the same link error when I try and run my app in the emulator.

apply plugin: 'com.android.library'

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.1.0'
    }
}

allprojects {
    repositories {
        jcenter()
    }
}

android {
    compileSdkVersion 21
    buildToolsVersion '21.1.2'
    defaultConfig {
        minSdkVersion 15
        targetSdkVersion 21
        versionCode 1
        versionName '1.0'
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    sourceSets {
        androidTest.setRoot('src/test')
    }
    lintOptions {
        abortOnError false
        disable 'InvalidPackage'
    }
    productFlavors {
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:support-v4:21.0.3'
    compile 'com.android.support:appcompat-v7:21.0.3'
    compile files('libs/realm-0.80.0.jar')
}

**Comment by kneth** [comment]
Instead of the line `compile files('libs/realm-0.80.0.jar')`, you could try with `compile 'io.realm:realm-android:0.80.1'`. Gradle will then download Realm for you.

**Comment by n0k** [comment]
Thanks Kenneth, I tried that and am not seeing the original error any longer however I'm seeing a new one:

UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Lio/realm/BuildConfig;
	at com.android.dx.merge.DexMerger.readSortableTypes(DexMerger.java:596)
	at com.android.dx.merge.DexMerger.getSortedTypes(DexMerger.java:554)
	at com.android.dx.merge.DexMerger.mergeClassDefs(DexMerger.java:535)
	at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:171)
	at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
	at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
	at com.android.dx.command.dexer.Main.runMonoDex(Main.java:303)
	at com.android.dx.command.dexer.Main.run(Main.java:246)
	at com.android.dx.command.dexer.Main.main(Main.java:215)
	at com.android.dx.command.Main.main(Main.java:106)
Error:Execution failed for task ':GitbookExplorer:dexDebug'.
> com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.7.0_21\bin\java.exe'' 

Looks like the dex method limit is being exceeded. Would you know how to resolve this?

**Comment by kneth** [comment]
Did you remember to remove the old Realm jar files before your rebuild?

**Comment by n0k** [comment]
That was the problem. Thanks for your help.
