### ISSUE TITLE
Remove RealmObject class? Decide.

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#1036]
Having to extend RealmObject seem to irk some people (me among them) as annotations are seen as being more natural for this kind of thing. Due to support for RealmModules incoming ( #938 ) and that we only have 2 methods on RealmObject, the only real use a more strict API has is that it catches more errors on compile time. However due to RealmModules allowing custom Schemas pr. Realm, this type check will only be partial anyway.

There is no technical limitation that prevents us from removing this, except that a lot of API methods will now require Object instead of RealmObject. This is not ideal and is more error prone, but the upside is that Entity classes are now more clean.

This would change the current API to this:
```
@RealmClass
public class Foo {
  ....
}

Realm realm = Realm.getInstance(getContext());
Foo foo = realm.createObject(Foo.class):
realm.isValid(foo);
realm.removeFromRealm(foo);
```

Note this still doesn't allow subclassing which is a different issue : #761

**Comment by cmelchior** [comment]
Copying this comment from #440 (as it really belongs here):

One possible solution for achieving the best of both worlds could perhaps be to to develop a custom Realm IntelliJ plugin that did static analysis. This would obviously only work inside IntelliJ, but Google are doing the same with their support annotations: http://tools.android.com/tech-docs/support-annotations and they even managed to get it to work with the Gradle plugin.

Something like this:

```
// 1. We remove the RealmObject class
// 2. annotate all methods that require an RealmObject like so
public <E> E createObject(@RealmClass Class<E> class) {
 // ...
}

// 3. When calling this method we do static analysis and let IntelliJ mark it as an error
realm.createObject(MyRealmObject.class); // This would work
realm.createObject(NonRealmObject.class); // This would be marked as an error
```

**Comment by cmelchior** [comment]
Some further thoughts on this. We will probably soon introduce a lot of features where having a base class will make the API much nicer:

* KVO 
* ChangeListeners
* Freeze

With a base class it could look like this:
```
Foo foo = realm.where(Foo.class).findFirst();

// KVO
foo.addFieldChangeListener("bar", new RealmChangeListener() {
  public void onChange() {
    // Field bar changed
  }
}

// ChangeListener
foo.addChangeListener(new RealmChangeListener() {
  public void onChange() {
    // Object was updated
  }
}

// RxJava
Observable<Foo> fooObservable = foo.observe();

// Immutability
Foo frozenFoo = foo.freeze(); // Creates an immutable copy
```

Without all methods would have to be on Realm instead

```
Foo foo = realm.where(Foo.class).findFirst();

Realm.addChangeListener(foo, new RealmChangeListener() { ... });
Realm.observe(foo);
Realm.freeze(foo);
```

**Comment by cmelchior** [comment]
Moved to P1 as we need to have a decision before reaching 1.0

**Comment by cmelchior** [comment]
After some internal discussion we are settling on keeping RealmObject as we think the benefits far outweigh the downsides.

### +
Type-safety baked into the API
Base-class prevents people from inheriting from classes incompatible with Realm.
Having a base class makes it easier to add the methods described above, something that would otherwise degrade the API on the `Realm` class itself.

### -
Methods on `RealmObject` might conflict with names on the model class itself.
Model objects become less "pure".
Model class will be incompatible with Google's Databinding library: https://developer.android.com/reference/android/databinding/BaseObservable.html

------
Some counter arguments:

* *Conflicting method names is a concern:* Care has to be taken to keep number of methods on `RealmObject` small and have names that makes it clear they are "Realm" methods. Currently we have `isValid` that could cause concern. `setOnChangeListener`, `removeChangeListener`, `observe` and `freeze` all have meaning that is specific to Realm and have a low chance of causing conflict.

* *Annotations are normally used for enhancing model classes*: It is true that on Android annotations are virtually used everywhere, however we feel that just having an annotation doesn't give us enough API flexibility as documented above. In our minds adding an annotation or extending a baseclass still means that a model class must be aware of a 3rd party framework and will have to be edited if it is removed.

* *Google's databinding library* also supports interfaces, which means we are still compatible although people are required to write more code to make it work.

Do you have any objections @timanglade @bmunkholm @realm/java ? Otherwise I will close this as a won't fix.

**Comment by timanglade** [comment]
I think @tebica had some feedback about this? I think we’ve heard from a lot of Java developers that get really stuck on the requirement to inherit from RealmObject, maybe he can add some details about why it can be so paralyzing.

**Comment by kboyarshinov** [comment]
I have few thoughts on how to make API more clear and provide additional extensibility to Realm classes.
- Remove current `RealmObject` and stick with `@RealmClass` annotation. As stated above this will provide basic functions to create/remove objects from database. 
```java
@RealmClass
public class Foo {
  ....
}

Realm realm = Realm.getInstance(getContext());
Foo foo = realm.createObject(Foo.class):
realm.removeFromRealm(foo);
```

- Further features like Immutability, ChangeListeners and RxJava support can be applied via extension interfaces:
```java
interface RealmImmutable<T> {
  T freeze();
} 

interface RealmObservable<T> {
  Observable<T> observe()
}

// can be split into two
interface RealmListenable {
  addChangeListener(RealmChangeListener listener)
  addFieldChangeListener(String field, RealmChangeListener listener)
  removeChangeListener(RealmChangeListener listener)
  removeFieldChangeListener(String field, RealmChangeListener listener)
}

```
Interface implementations is generated with annotation processing. Therefore user gets features he actually need. 

Probably there can be some issues in generating valid code if somebody wants to create so named `SuperRealmInterface` to have all features available:
```java
interface SuperRealmInterface<T> extends RealmImmutable<T>, RealmObservable<T>, RealmListenable {
}
```

Thus we will get type safety in Realm classes, but other API will require Objects. I like the idea of static analysis though.
> Base-class prevents people from inheriting from classes incompatible with Realm.

This case can be checked compile time and build error. 

> Having a base class makes it easier to add the methods described above, something that would otherwise degrade the API on the Realm class itself.

Extension interfaces will make it even easier to add new methods with the ability keep Realm objects pure without any method. Probably even work better with Data Binding, can't tell for sure.

**Comment by kboyarshinov** [comment]
One more thing about extension interfaces. All of them can extend some empty interface e.g. `RealmObjectExtension` to add type safety to them too. In future this may allow to create plugin libraries with additional extensions and mechanism to generate their implementation. BTW Realm core itself can have less size with additional APIs available as plugin libraries.

**Comment by cmelchior** [comment]
Thank you @kboyarshinov. I really like the idea of an extensible API and we are considering it for things like RxJava and extended JSON support. However there are some tricky corner cases with extension interfaces for RealmObjects as currently you are allowed to instantiate standalone copies of your objects, i.e objects not backed by Realm. This means that we cannot just let our Proxy classes implement the interfaces, the Model class has to do it which makes a bit cumbersome and awkward:

```
@RealmClass
public class Foo implements RealmOberservable<Foo> {

   private String str;

   public void setStr(String str) {
     this.str = str;
   }
   
   public String getStr() {
     return str;
   }

   public void addRealmChangeListener(RealmChangeListener listener) {
     // Empty, overridden by the Proxy class 
   }

   // All other interface methods must have a no-op implementation as well.
}
```

It could be solved by making `Foo` abstract, but that would completely remove the ability to create stand-alone objects, so it would be a big trade-off.

**Comment by kboyarshinov** [comment]
Yeah, I see why this is limitation. But probably absence of implementation will be expected. Because there will be no sense to use ChangeListeners or Observable<T> in an object actually not attached to Realm instance. 

Making `Foo` abstract actually may work with few additions. Instances of `Foo` may only be created with either existing `realm.createObject` (creates object attached to Realm) or with new static factory method `Realm.createObject` (creates object not attached to any Realm). However, this will not prevent user from making its own implementation of abstract `Foo`. Similar API works nice in AutoValue.

**Comment by cmelchior** [comment]
One crazy idea could also be to  do what the Googles Databinding library is doing, which is providing both an interface and a base class. Then people who don't like to extend a base class can implement a marker interface instead. It would mean we have to copy all current methods in RealmObject though and put them somewhere else, with the `Realm` class probably being the most likely candidate unless we want to create a `RealmObjectUtil` class or something.

**Comment by cmelchior** [comment]
Another thing for Removing RealmObject is that when we implement #575, it most likely means that `RealmList<RealmObject>` turns into `RealmList<Object>` which further removes the need for a base class.

**Comment by cmelchior** [comment]
Following discussion in #2296 we have decided to add a new marker interface which can be used instead of extending RealmObject, this is now being tracked in #2347.
