### ISSUE TITLE
Add support for indexing integer and Date fields

### ISSUE THREAD

**Issue by kneth** [realm/realm-java#1039]
Realm Core supports search index on boolean, integer, and Date fields. Adding support for these types could improve the performance for primary keys.

**Comment by cmelchior** [comment]
So this issue is two steps?

1) Add support for boolean, integer and Date index in general (remove restrictions in annotation processor + update doc)

2) Add implicit index to int primary keys the same way as strings currently.

**Comment by kneth** [comment]
@cmelchior You are right. Two different PRs will make it easier to review.

**Comment by cmelchior** [comment]
This should also be enabled for byte as that is also saved as an INTEGER?

**Comment by beeender** [comment]
Oh yes. The PR is on the way.

**Comment by beeender** [comment]
#1262 has been merged. Close this one.
