### ISSUE TITLE
expecting absolutePath.hashCode() not to collide each other

### ISSUE THREAD

**Issue by zaki50** [realm/realm-java#1040]
'absolutePath.hashCode()' is used as key of some HashMaps(realmsCache, referenceCount, etc.).

https://github.com/realm/realm-java/blob/746083df06e9a7a581fb3e769960f30a96b4ff01/realm/src/main/java/io/realm/Realm.java#L495

If hash code of absolutePath collides with each other, wrong Realm instance is returned on Realm.getInstance().

**Comment by kneth** [comment]
Worth a read: http://stackoverflow.com/questions/9406775/why-does-string-hashcode-in-java-have-many-conflicts

**Comment by cmelchior** [comment]
Example of collision:
```
Realm r1 = Realm.getInstance(this, "Ea");
Realm r2 = Realm.getInstance(this, "FB");
r1.getId() == r2.getId();
```
