### ISSUE TITLE
Skip needless migration issue

### ISSUE THREAD

**Issue by akocjl** [realm/realm-java#1042]
Hi,

Is there a way to persist the schema version inside the realm? 

This issue is related to https://github.com/realm/realm-java/issues/886
The suggested solution was to use a no-op migration to set the current schema version, but this should only be done once when the database is initiallized.

**Comment by cmelchior** [comment]
Hi @akocjl
The schema version is persisted inside the Realm. The current problem is that the version number is only incremented during a migration, which is why a no-op migration is needed. Are you running into problems using this approach? Also, this will be a lot easier when we introduce the new migration API.

**Comment by akocjl** [comment]
My issue with the no-op migration is that it should only be done once, and I can't think of where I should call it.

**Comment by akocjl** [comment]
I'm currently just using the default realm. What I'm looking for is where should I use the no-op migration to set the version once, only when the database is initiallized.

**Comment by cmelchior** [comment]
I agree it is not very nice atm. A approach you can do is having a helper class that handles this for you. Something like this:

```
// Pseudo code
public class RealmHelper() {
  
  private static SharedPreferences prefs; 

  public static Realm getInstance() {
    if (!prefs.getBool("realmUpgraded", false)) {
      // Do migration
      prefs.setBool("realmUpgraded", true)
   }

   return Realm.getInstance()
  }
}
```

**Comment by akocjl** [comment]
This looks good, hopefully you can release the migration API soon :)

Thanks!

**Comment by cmelchior** [comment]
Yes, that is the plan :)
