### ISSUE TITLE
App size does not change after deleting objects (v0.80.1)

### ISSUE THREAD

**Issue by le0nidas** [realm/realm-java#1043]
Here is my class (all RealmObject* classes are RealmObject descendants):
```java
RealmObject1 {
  @PrimaryKey int id;
  RealmObject2 obj2;
  RealmList<RealmObject3> listOfObj3;
}
```

When i want to delete an instance of RealmObject1 i execute the following transaction:
```java
final RealmObject1 obj1= realmInstance.where(RealmObject1.class)
                        .equalTo("id", id)
                        .findFirst();
realmInstance.executeTransaction(new Realm.Transaction() {
  execute() {
    obj1.obj2.removeFromRealm();
    for(int idx=obj1.listOfObj3.size()-1; idx>=0; idx--) obj1.listOfObj3.get(idx).removeFromRealm();
    obj1.removeFromRealm();
  }
});
```

I check both the application's size (Settings->Apps->*my app*->Data) and the realm file:
```java
File f = new File(path); // path = the path to the realm file
f.length;
```
and nothing changes after deleting an instance.

To make matters worse, if i add and delete the same object a few more times i see that both the file and app size have increased.

I guess i'm doing something wrong while deleting but i just can't see it.

Thank you in advance for your answers.

**Comment by emanuelez** [comment]
Realm doesn't automatically reclaim space after deletion operations.
To manually do it we provide the `compactRealmFile` method described here: http://realm.io/docs/java/api/io/realm/Realm.html#compactRealmFile-android.content.Context-

**Comment by le0nidas** [comment]
Yeap, that did the trick!
Thank you very much for your quick answer!

**Comment by crysan** [comment]
compactRealmFile is deprecated?

**Comment by beeender** [comment]
We introduced [`RealmConfiguration`](https://realm.io/docs/java/latest/api/io/realm/RealmConfiguration.html) in 0.81.
Please use [`compactRealm(RealmConfiguration configuration)`](https://realm.io/docs/java/latest/api/io/realm/Realm.html#compactRealm-io.realm.RealmConfiguration-) instead.

**Comment by crysan** [comment]
All clear. But I would like to ask how long the function will work compactRealmFile?

**Comment by beeender** [comment]
I cannot predict when would we delete the deprecated interfaces. But I don't think we will delete them recently since there are many users are still using them.

But we really suggest you to migrate to the new interface if you can. It is quite easy!
