### ISSUE TITLE
Detection of database upgrade

### ISSUE THREAD

**Issue by zhaozeyx** [realm/realm-java#1048]
we can detect whether database need to upgrade by using sqlite on android. But i don't find the same function in Realm. Should I write our code to achieve the function?

**Comment by cmelchior** [comment]
Hi @zhaozeyx 
As far as I know the only way you can do that with SQLiteOpenHelper is by overriding the ```onUpgrade()``` method, right?

Right now in Realm we throw an RealmMigrationNeededException instead if your database needs to be upgraded, which you then can handle. This is not as nice as it could be, so our new migration API will allow you to provide a Migration when opening the Realm so this is done automatically for you.

But for now I would recommend doing something like the below where you access the Realm instance through a Helper class. This allows you to transparently upgrade if needed:

```
public class RealmHelper {
	public static Realm getRealm(Context context) {
	    Realm realm = null;
	    try {
	        realm = Realm.getInstance(context);
	    } catch (RealmMigrationNeededException e) {
	    	Realm.migrateRealmAtPath(new File(context.getFilesDir(), "default.realm", new CustomMigration());
	    	realm = Realm.getInstance(context);
	    }
	    return realm;
	}
}
```

**Comment by cmelchior** [comment]
Hi @zhaozeyx 
I assume the above answered your question, otherwise please reopen this issue.
