### ISSUE TITLE
copyToRealmOrUpdate SIGSEGV

### ISSUE THREAD

**Issue by tmeunier** [realm/realm-java#1051]
Hi,

Following an update in my code, I randomly found a native crash (SIGSEGV 0x00000008) when using
`copyToRealmOrUpdate` and an object with a declared `@PrimaryKey` which was not set before copy.
Using `Realm 0.80.1`

To reproduce with a testCase:

```java
public class PrimaryKeyTest extends RealmObject {

    @PrimaryKey
    private String key;

    public String getKey() {
        return key;
    }

    public void setKey(String key) {
        this.key = key;
    }
}
```
```java
public void testPrimKeyMissing() {
        testRealm.beginTransaction();
        try {
            testRealm.copyToRealmOrUpdate(new PrimaryKeyTest());
            testRealm.commitTransaction();
        } catch (Exception e) {
            // OK
            testRealm.cancelTransaction();
        }
}
```

==> 'Instrumentation run failed due to 'Native crash''

**Comment by crysan** [comment]
Most likely if you do not specify copyToRealmOrUpdate PrimaryKey

**Comment by cmelchior** [comment]
Hi @tmeunier 
Thank you for the bug report, I am able to reproduce it. As @crysan points out it crashes because the primary key is null, but it shouldn't crash from native code. It should crash with an exception instead.
