### ISSUE TITLE
Unexpected Migration Exception

### ISSUE THREAD

**Issue by aaalaniz** [realm/realm-java#1053]
I am receiving an unexpected [RealmMigrationNeededException](https://github.com/realm/realm-java/blob/335ce1846caf80952766e30dd5955333647987ba/realm/src/main/java/io/realm/exceptions/RealmMigrationNeededException.java) when dealing with two object across two realms. Here is the scenario.

I released version of application with one object in one realm called "realm_one.realm"

```java

public class RealmObjectOne extends RealmObject {
    @PrimaryKey private String stringFieldOne;
    private long longField;

    // Getters and setters...
}

```

I then begin working on some additional functionality and added another object to only be stored in another realm called "realm_two.realm"

```java

public class RealmObjectTwo extends RealmObject {
    @PrimaryKey private String stringFieldTwo;
    private byte[] byteArrayField;

    // Getters and setters...
}

```

I have no instances of RealmObjectTwo in either realm and only intend to read/write that object to "realm_two.realm" yet, I receive a migration exception [RealmMigrationNeededException](https://github.com/realm/realm-java/blob/335ce1846caf80952766e30dd5955333647987ba/realm/src/main/java/io/realm/exceptions/RealmMigrationNeededException.java) for missing fields related to RealmObjectTwo when trying to query for RealmObjectOne in "realm_one.realm". Is this expected or am I doing something wrong here?

If this expected is there a notion of "scoped realm objects" where new objects to be maintained only in new realms don't conflict (ie. don't cause [RealmMigrationNeededException](https://github.com/realm/realm-java/blob/335ce1846caf80952766e30dd5955333647987ba/realm/src/main/java/io/realm/exceptions/RealmMigrationNeededException.java)) with existing realms?

**Comment by aaalaniz** [comment]
Realm version 0.80.0

**Comment by cmelchior** [comment]
Hi @aaalaniz 
Yes that is currently the expected behaviour. Right now Realm only has the notion of one global schema which all Realms must have. This means that you must migrate all Realms even though they contain no objects of given type type.

However we understand that people sometimes want to have different types of objects in different Realms, which is why we are going to add the concept of Realm Modules which does exactly that. You can follow progress on that here #938 .
