### ISSUE TITLE
Size of the default.realm file changes due to calls to Realm.close()

### ISSUE THREAD

**Issue by gillde** [realm/realm-java#1058]
Hey there, 

first of: this is not an issue (I guess) but I dont know where I should ask questions like these if not here, so please excuse my question, if there is a better place please let me know and I will ask my next question over there :)

I realized that the size of my actual realm file (pulled from device via adb pull) depends (at least it seems to do so) heavily on open Realm instances. This came as a surprise to me at first, but then I thought about the possible implementations you guys do to make Realm really fast and I thought that there is mirroring going on or so.

Can somebody shed some light on why the file size increases/decreased with open/closed realm instances?

**Comment by bmunkholm** [comment]
Hi @gillde ,
The file is memory mapped, and the OS will adjust the size of the file when it's being closed.
If you have more specific observations that are causing any issues, please let us know.

Cheers

**Comment by gillde** [comment]
Thank you for your answer.
As I said this is not really an issue, it was one before I knew what was happening.

**Comment by bmunkholm** [comment]
Great. Let us know if you have any other issues. BTW. We normally use this for real bugs or feature requests and https://groups.google.com/forum/#!forum/realm-java for general questions.
