### ISSUE TITLE
RealmMigrationNeededException should have getAbsolutePath()

### ISSUE THREAD

**Issue by zaki50** [realm/realm-java#1060]
I'd like to write schema check code as follows.

        try {
            Realm.getInstance(context, "foo.realm").close();
        } catch (RealmMigrationNeededException e) {
            Realm.migrateRealmAtPath(e.getAbsolutePath(), new MyRealmMigration());
        }

due to lacking of RealmMigrationNeededException#getAbsolutePath(), we must write 

    Realm.migrateRealmAtPath(new File(context.getFilesDir(), "foo.realm").getAbsolutePath(),
                             new MyRealmMigration());

**Comment by cmelchior** [comment]
Good idea. We are simplifying how Migrations are going to work, but RealmMigrationNeededExceptions will still be around, and adding this will make it easier to reference the correct Realm.
