### ISSUE TITLE
copyToRealmOrUpdate fails silently

### ISSUE THREAD

**Issue by vickychijwani** [realm/realm-java#1068]
I have the following `RealmObject` defined:

```java
@RealmClass
public class AuthToken extends RealmObject {
    @PrimaryKey   // intentional; there should only ever be one auth token
    private String tokenType = "Bearer";
    private String accessToken;
    private String refreshToken;
    private int expiresIn;
    private long createdAt;
    // standard getters and setters follow ...
}
```

I generate a valid `AuthToken` object, try to save it to the default Realm and get back the saved `RealmObject`, like so:

```java
private AuthToken saveAuthToken(AuthToken authToken) {
    realm.beginTransaction();
    AuthToken savedAuthToken = realm.copyToRealmOrUpdate(authToken);
    realm.commitTransaction();
    return savedAuthToken;
}
```

But when I check the value of `savedAuthToken`, it seems to be only default-initialized, i.e.,

```js
// = is equality, not assignment
savedAuthToken = {
    tokenType: "Bearer",
    accessToken: null,
    refreshToken: null,
    expiresIn: 0,
    createdAt: 0
}
```

Realm throws no errors. Additionally, I started with a completely empty Realm, so it's not a primary key clash. As far as I can see, this is a fairly simple use-case, with the only mildly unusual thing being my usage of `@PrimaryKey` (which according to the docs is entirely valid usage). What could be the issue?

**Comment by cmelchior** [comment]
How are you checking the value? The object returned is a Proxy object, where all fields are just default values. So if you don't use the getters but inspect it using the debugger you will see the wrong data.

**Comment by vickychijwani** [comment]
Oh, silly me, I wasn't using the getters and setters to check. There was something else going wrong that led me to infer (incorrectly) Realm wasn't saving the object properly.

By the way, I really love Realm so far! It's orders of magnitude easier to work with than Android's `ContentProvider`s and `Loader`s. I'm waiting for 1.0 to bring better tooling (especially since the database format is opaque), documentation, migration support, etc, then Realm will really shine. My thanks to the Realm team!

**Comment by bmunkholm** [comment]
Thanks a lot for the nice words!
Migration support is on it's way. With regards to documentation, please open a new issue and let us know what you would like to have better documented - that will be very helpful!
Thanks!
