### ISSUE TITLE
[DOC] RealmQuery.CASE_INSENSITIVE is not insensitive for special character

### ISSUE THREAD

**Issue by bbergshaven** [realm/realm-java#1069]
When using the query below on the following text:
JØSANG SJØMAT

it does not get hits on jøs or Jøs , but hits on JØS and jØs

contains("name", searchEditText.getText().toString(), RealmQuery.CASE_INSENSITIVE)

Seems that it does not support non-english characters.

**Comment by cmelchior** [comment]
Hi @bbergshaven 
Yes, that is a current limitation of Realm at the moment.: https://github.com/realm/realm-java/issues/581, but it is not documented very well. This is an unfortunate oversight we should fix, as solving the underlying problem will take some more research ( #1031).

ie. 
[ ] Update Website current limitations
[ ] Update RealmQuery.contains() with info on non-ascii chars
