### ISSUE TITLE
Crash after update from 0.79.0 to 0.80.0

### ISSUE THREAD

**Issue by eboudrant** [realm/realm-java#1070]
Hi,

I have a native crash when the app update from 0.80.0 from 0.79.0. I built a sample app and sent it to help@realm.io few days ago. I cannot update to 0.80.x until this is fixed.

Let me know if you received it. If not I can resend it.

Thanks

**Comment by bmunkholm** [comment]
Sorry for the delay - yes I responded to email, so I will close this issue.

**Comment by eboudrant** [comment]
thanks for re-opening #982.
