### ISSUE TITLE
Realm query returns null for equalTo

### ISSUE THREAD

**Issue by bobanda87** [realm/realm-java#1071]
Hi, I am using `RealmQuery` with `equalTo` and `findFirst` and I can see that the object exists, but somehow attributes of that object are `null`

This is the code that I am using
```
RealmQuery<NotificationColor> query = realm.where(NotificationColor.class);
NotificationColor result = query.equalTo("code", code).findFirst();
return result;
```

This is what is see in debugger. I can tell that object is found (as it should be), but attribute values are `null`.

![debugger image]
(http://i.imgur.com/Tq8dNOL.png)

Can you look into this? Or maybe advice if I am doing something wrong.

**Comment by cmelchior** [comment]
Hi @bobanda87 
It is because RealmObjects are just proxy objects. All the data is stored in the C++ core. This means that what you see in the debugger are just the Java default values, but if you call the getters you will get the actual values. So it is by design.

**Comment by bobanda87** [comment]
So, this is not the correct way of using queries in Realm? Can you advice how can I get NotificationColor object filtered by code?

Btw, I am checking my db with RealmBrowser and I can see that before this query, the data is there, so this should return one object.

Thanks!

**Comment by cmelchior** [comment]
It is the correct way, I am just saying you cannot trust what the debugger tells you. If you call ```result.getLabel()``` you should see you data?

**Comment by bobanda87** [comment]
You are right, I get the correct values! Thanks!

But then I am bit confused how it works, since I have the following situation.

I populated NotificationColor table with default data.
Then I am adding new Notifications that has attribute NotificationColor as one of it attributes, using the following code:

```realm.beginTransaction();
Collection<Notification> realmNotifications = realm.copyToRealm(notificationList);
realm.commitTransaction();```

notificationList is some array list with Notification objects.
`ArrayList<Notification> notificationList = new ArrayList<Notification>();`

So, whenever I save notifications, it automatically populates NotificationColor table - with values that already exists in that table.

Is this normal behaviour? It looks like I am having some structural problem. 

Thanks!

**Comment by cmelchior** [comment]
Yes, ```copyToRealm()``` copies standalone objects without regard to any existing objects, but if they reference objects that are already in the Realm, they shouldn't be duplicated, but without some more context of what you are doing it is hard to tell.

**Comment by bobanda87** [comment]
Thanks a lot for clarification! I will look into it!
