### ISSUE TITLE
Proper errorhandling missing when adding standalone objects to RealmList

### ISSUE THREAD

**Issue by dmytrodanylyk** [realm/realm-java#1076]
Reproduced on versions: `0.80.0`, `0.80.1`

I have following data objects:

``` java
public class RealmString extends RealmObject {
    private String value;

    public RealmString() {
    }
    public RealmString(String value) {
        this.value = value;
    }
    public String getValue() {
        return value;
    }
    public void setValue(String value) {
        this.value = value;
    }
}

public class Person extends RealmObject {
    private RealmList<RealmString> emailList;

    // getter and setter
}
```

I want to get `Person` object from realm and update `emailList`

``` java
Realm realm = ...
realm.beginTransaction();
Person person = realm.where(Person.class).findFirst();
person.getEmailList().add(new RealmString("jondoe@gmail.com")); // this line crash with NPE
realm.commitTransaction();
```

Crash log:

```
Caused by: java.lang.NullPointerException
            at io.realm.RealmList.add(RealmList.java:120)
```

I think `person.getEmailList()` return null, so I tried `person.setEmailList(newList)` which cause the same crash.

**Comment by cmelchior** [comment]
Hi @dmytrodanylyk 
It doesn't work because you are trying to put a standalone into a managed object. Standalone objects are objects created using the new keyword, ie. ```new RealmString()```, while managed objects are created using ```realm.createObject```.

So in your case it should be: 
```
Realm realm = ...
realm.beginTransaction();
Person person = realm.where(Person.class).findFirst();
RealmString str = realm.createObject(RealmString.class);
str.setValue("jondoe@gmail.com");
person.getEmailList().add(str);
realm.commitTransaction();
```

That said, we are clearly missing an error check, because we would normally throw an exception if you a trying to do something like that.

**Comment by dmytrodanylyk** [comment]
@cmelchior thanks, I missed this!

**Comment by kneth** [comment]
@dmytrodanylyk As far as I understand you, you got your issue solved. We will add a better error message later (we have currently more urgent issues).

**Comment by dmytrodanylyk** [comment]
@kneth sure, this is low priority I guess.

**Comment by kneth** [comment]
@dmytrodanylyk You are welcome to submit a patch ;-)

**Comment by markini** [comment]
Hello, just to get some things right.
This behavior changed didn't it?

I can do something like this just fine:

```java
Realm realm = Realm.getDefaultInstance();

Dog dog = new Dog();
dog.setRace("A funny one");

realm.beginTransaction();
dog = realm.copyToRealm(dog);
realm.commitTransaction();

RealmList<RealmString> names = new RealmList<>();
names.add(new RealmString("Wolfi"));
names.add(new RealmString("Wauwau"));

realm.beginTransaction();
dog.getNames().addAll(names);
realm.commitTransaction();

Dog dog2 = realm.allObjects(Dog.class).first();
for(RealmString name : dog2.getNames()){
    Timber.e("Dogname: " + name.getVal());
}
```

Why am I allowed to add non realm objects? I can't however set a `RealmString` directly like this:
```java
realm.beginTransaction();
dog.setRealmStringValue(new RealmString("some value"));
realm.commitTransaction();
```

**Comment by kneth** [comment]
When `dog` is copied to your Realm using `copyToRealm()` it becomes a managed object. The `names` list is a unmanaged list, but when you add it to the managed object `dog` in `dog.getNames().addAll()` (I assume you meant `dog.getNames().add()`), the objects in `names` are becoming managed objects (by calling `copyToRealm()`).

In the other example, you call the setter which will not copy an object to your Realm.

**Comment by markini** [comment]
Ok perfect, so it is safe to add unmanaged objects to a realm list of a managed object (inside a transaction of course).

I was just unsure if I should do this because in the first post of this issue, @dmytrodanylyk encountered a NPE when doing this:
```java
person.getEmailList().add(new RealmString("jondoe@gmail.com")); // this line crash with NPE
```

**Comment by kneth** [comment]
We should definitely document it better.

**Comment by beeender** [comment]
We support adding an unmanaged `RealmObject` to `RealmList` now. close this issue.

**Comment by Zhuinden** [comment]
@beeender you do? Previously it said "all values in a RealmList must be a valid proxy" or something like that.

**Comment by kneth** [comment]
@Zhuinden https://github.com/realm/realm-java/blob/master/realm/realm-library/src/main/java/io/realm/RealmList.java#L155

**Comment by Zhuinden** [comment]
@kneth thanks 😄 All I remembered was https://github.com/realm/realm-java/issues/1749
