### ISSUE TITLE
How to populate app with prepared data?

### ISSUE THREAD

**Issue by peternguyen88** [realm/realm-java#1078]
What is the best way to populate app with some prepared data when the app is installed? In SQLite I can using some desktop application to create the database, add some data and then import it to Android app upon installation. How can I do it with Realm? Thanks, I'm new to this.

**Comment by cmelchior** [comment]
Hi @peternguyen88  

Currently you have two options:

1) Create a sample app that creates the database and it's data, then copy it from the phone so you can bundle it with your "real" app: http://stackoverflow.com/questions/28478987/how-to-view-my-realm-file-in-the-realm-browser/28486297#28486297

2) If you are familiar with Cocoa, you can use Realm-Cocoa in a Mac OSX application, then you can create the database on a developer machine or a build server instead.

We don't have a pure Java API yet as we are focusing on the Android API first, but it will be coming down the road.

**Comment by eskimoapps** [comment]
A pure Java API would definitely be nice, is there another issue to track this with? Also, maybe this library should be called realm-android.
