### ISSUE TITLE
Realm with a SyncAdapter

### ISSUE THREAD

**Issue by lawloretienne** [realm/realm-java#1082]
Is there a way to make Realm
http://realm.io/docs/java/latest/
and Syncadapters
https://developer.android.com/training/sync-adapters/creating-sync-adapter.html
play nicely together?

I created a stub ContentProvider so that I could persist data with Realm. The problem is I don't know how to communicate changes from the SyncAdapter back to my Fragment that kicks off the whole sync adapter process.  

From the onPerformSync() method in the SyncAdapter I tried using an event bus like Otto to communicate these changes, however event buses do not work across multiple threads.

Realm provides an OnChangeListener which detects any changes to the DB.  This works well inside the Fragment but not across multiple threads.

The alternative is to do away with Realm and just use a ContentProvider.  But Realm is very simple to use and I would prefer a solution that includes Realm.

**Comment by cmelchior** [comment]
Hi @lawloretienne 
I tried adding Realm to the BasicSyncAdapter example provided from Android Studio. In here the RealmChangeListener works as expected. You can try to play around with it here and see where your code might differ: https://github.com/realm/realm-java/tree/cm-example-syncadapter

**Comment by epool** [comment]
What happened with the example link?

**Comment by deanezra** [comment]
@cmelchior, please can you reupload the example sync adapter as your link is now 404?

**Comment by cmelchior** [comment]
@deanezra I pushed the branch again

**Comment by deanezra** [comment]
@cmelchior thanks.

**Comment by veonua** [comment]
@cmelchior sorry but your sync adapter does nothing, it still uses SQLite DB to store data.
there is only "Foo foo = realm.createObject(Foo.class);" which is useless.

**Comment by veonua** [comment]
ok, as soon as realm does not support multiprocess - there is no sense to make syncadapter of it

**Comment by cmelchior** [comment]
@veonua That branch is just a exploratory branch, it was never intended to be a full blown working example. Regarding communication from the SyncAdapter you should just use the RealmChangeListeners as they will be triggered when any data written in the SyncAdapter is available.

**Comment by veonua** [comment]
the problem with RealmChangeListeners is that they will not work in multi-process environment. Most of SyncAdapter implementations has `android:process=":sync"` in the manifest.
so it supposed to be started independently from UI process.

**Comment by cmelchior** [comment]
Yes, that will be fixed with #1300, until then you need to run any SyncAdapter in the same process.

**Comment by jplazcano87** [comment]
is this example available somewhere? , i can't find it in the repo or any commit

**Comment by cmelchior** [comment]
The branch is here: https://github.com/realm/realm-java/tree/cm-example-syncadapter, it is quite old at this point though, so I doubt it it even compiles at this point.

**Comment by jplazcano87** [comment]
i just want an idea, is under the experimental folder, i was looking for the example in the examples folder.  thanks for the reply

**Comment by Zhuinden** [comment]
@jplazcano87 although nowadays Realm supports multi-process locking so technically in sync adapter you'd just need to use it like you normally would on any background thread

**Comment by jplazcano87** [comment]
thanks, i'm fully aware of the multi-process feature! thank for the advice, i've been using realm for a couple of years
