### ISSUE TITLE
Multiple Realm instances simultaneously

### ISSUE THREAD

**Issue by fnk0** [realm/realm-java#1084]
So my problem is the following... 

My app needs to do some fairly  large video uploads 15~20 MB. I run those uploads in a service and the data to be sent is cached by a realm database 

However while the data is being uploaded the user can still use the app which views other data that is cached in the server.

My problem is that while the service is running and I have a realm instance open I can not query or open any other instances of realm.  (i.e. my list appears empty until the upload is finished, when the upload is finished I can refresh the fragment and the data is loaded)

Any suggestions?

**Comment by emanuelez** [comment]
Are you storing such big files in Realm? If so please be aware that there is a 16 MB limit on data blobs.
That being said we tend to suggest not to store binary blobs in Realm since the benefits of doing so are much lower compared to storing other kind of data.

In regards to your particular problem my suggestion is to try to keep your transaction as short as possible since they are blocking one another. Another suggestion is to create a worker thread for writes to which you send tasks to be performed. You can see this pattern being used in some of the examples in our repo.

**Comment by fnk0** [comment]
Oh no! The files are not stored in a folder and just the file to the file is stored in the RealmObject. Hmm isn't the service already a worker thread?

**Comment by emanuelez** [comment]
Not always. Actually in most cases Android Services work on the UI thread. My suggestion would be to create a background Looper/Handler thread.

**Comment by fnk0** [comment]
I tried using a Handler inside the service with: new Handler().post(new Runnable() {....}));
But the realm object inside the activity still cannot access the data layer. 

And sorry for the confusion.. I'm using a IntentService which based on Android docs uses a worker thread by default: http://developer.android.com/reference/android/app/IntentService.html

**Comment by emanuelez** [comment]
Can you measure how long your transactions take to complete on average?

**Comment by fnk0** [comment]
It really depends on network. Using 4G LTE around 10-15s for a video and about 1-2s for a image. When using WIFI it varies much more. 

Let me try clarify how it is handled:

I have a List of RealmObjects with fairly small entries, basically a model with some integers and strings representing a piece of data.
One of the pieces of data is either a path to a image or a video. 
For each object in the list I will upload the data to a server. When I do so I read the path from the object and them upload the image. If the upload is successful (i.e. no timedOut, or other exception happened I will remove the data from the realm, otherwise I keep that object in the realm to retry it later.)

```java
Realm realm = Realm.getInstance(this);
realm.beginTransaction();
RealmResults<MyData> results = realm.allObjects(MyData.class);
realm.commitTransaction();
RestAdapter restAdapter = MyClient.getAdapterWithToken(this);
MyClient.MyData postData = restAdapter.create(MyClient.MyData.class);
for (int i = 0; i < results.size(); i++) { 
    realm.beginTransaction();
    MyData mD = results.get(i);
   // perform upload of the data...
   mD.removeFromRealm();
   realm.commitTransaction();
 }
// Finished all the uploads
realm.close();
// Service will be destroyed

**Comment by emanuelez** [comment]
How about something like this:

```java
Realm realm = Realm.getInstance(this);
RealmResults<MyData> results = realm.allObjects(MyData.class); // no need for a transaction to query
RestAdapter restAdapter = MyClient.getAdapterWithToken(this);
MyClient.MyData postData = restAdapter.create(MyClient.MyData.class);
for (int i = results.size(); i >= 0; i--) { // Iterate backwards. See https://github.com/realm/realm-java/issues/789 
    MyData mD = results.get(i);
    // perform upload of the data...
    realm.beginTransaction();
    mD.removeFromRealm();
    realm.commitTransaction();
 }
// Finished all the uploads
realm.close();
// Service will be destroyed 
```

**Comment by fnk0** [comment]
That worked great! Thanks! Just 1 detail. In your answer for backwards you should change results.size() to results.size() -1. 

Anyways, thanks for your help and for an amazing library! I really love realm and how fast it is! :+1:

**Comment by emanuelez** [comment]
Good catch! I edited my previews comment so that if anybody else runs into your problem will find a working snippet of code :)

Happy coding!
