### ISSUE TITLE
RealmBaseAdapter with null RealmResults

### ISSUE THREAD

**Issue by yolapop** [realm/realm-java#1086]
Can you please handle null `realmResults` within `RealmBaseAdapter`? If the adapter has no content at all, and `RealmQuery` possibly returns `null` too, it doesn't make sense for `RealmBaseAdapter` to not accepting `null`.

Example:

    RealmResults<MyObject> results = realm.where("...").find(); // it's possible the result is null
    MyRealmAdapter adapter = new MyRealmAdapter(context, results); // if results is null, you get exception
    // if I catch the exception, then adapter is null
    // I couldn't do this
    spinner.setAdapter(adapter);
    // or
    adapter.updateRealmResults(notNullRealmResults);

**Comment by cmelchior** [comment]
Hi @yolapop 
```findAll()``` should never return null, but a empty list if there is no query results (which is also one of the reasons that we crash on null). Do you have a case where you are getting null?

**Comment by yolapop** [comment]
Yes, I noticed that I never got null `realmResults`..

However, I usually go with this initialization pattern

    private Adapter adapter;

    public View onCreateView() {
        // initiate adapter with null
        // for some reason the adapter contents is dependent to user action, like AutoCompleteTextView
        adapter = new Adapter(mContext, null);

        // populate views
        spinner.setAdapter(adapter);
    }

    public void updateAdapter() {
        // user do some action and update the adapter
        adapter.updateRealmResults(results);
    }

Note, I could pass `findAll()` results on adapter initialization but it's not right. This is just inconvenience problem. Also, what happened when the `realmResults` passed in constructor is in a different `Realm` than the one that's passed in `updateRealmResults()`? Maybe there should be a check in the constructor and `updateRealmResults()`.

Thank you. If my understanding is wrong please point it out.

**Comment by cmelchior** [comment]
Hi @yolapop 
Yes, I can see why that could be useful. I'll add it to our backlog, but if you want to add it yourself we also accept Pull Requests :)

**Comment by yolapop** [comment]
I think I'll be able to create PR. So is it okay to pass `realmResult` that
belong to different realm than one that is already exist in the adapter?

**Comment by cmelchior** [comment]
Currently we doesn't handle that situation very well. We install a change listener for the Realm backing the original RealmResults but ```updateRealmResults()``` doesn't check which Realm is backing the new RealmResults, which can lead to the adapter not refreshing itself. I think the semantics would be more clear if that was not allowed, ie. you need to create a new RealmBaseAdapter if you want to update the RealmBaseAdapter with data from another Realm.

**Comment by yolapop** [comment]
Hi @cmelchior, I apologize, I don't think I'm gonna make the PR, it's a lot to prepare to build for just a little changes (I run Windows). I'm sure it'll be quicker if you guys do this. Thanks a lot for doing this!

**Comment by cmelchior** [comment]
Hi @yolapop 
No problem :)

**Comment by zaki50** [comment]
@cmelchior I made PR for this issue. please review it.
