### ISSUE TITLE
Is Realm.copyFromRealm() method available like  Realm.copyToRealm() ?

### ISSUE THREAD

**Issue by somghosh** [realm/realm-java#1088]
I have a method, that on network service failure populates the in memory data from realm and then this in memory data is used at several places to display data on screen

However, since I invoke the close() method at the end of this, it says that when it tries to display the data in an activity, the Realm instance is closed. Is there a good way of copying it 'out of realm' instance and still use the same RealmObject (i.e. not creating another class that does not extend RealmObject but still has exactly the same fields)?

                    @Override
                    public void failure(RetrofitError error) {

                        // failed for some reason, so populate from DB

                        Realm realm = Realm.getInstance(App.this, ME_DATA_DB);
                        RealmResults<MePageInfo> mePageInfoDBTableRowRes = realm.where(MePageInfo.class).findAll();
                        
                        if (mePageInfoDBTableRowRes.size()>0 ){
                            MePageInfo dbMePageInfoDBTableRow = mePageInfoDBTableRowRes.first();
                            appData.getMePageInfoList().add(dbMePageInfoDBTableRow);

                            appData.setUserMePageInfo(dbMePageInfoDBTableRow);
                            notifyUserDataChangeListeners(dbMePageInfoDBTableRow);

                        } else{
                            if (BuildConfig.DEBUG){
                                Toast.makeText(App.getInstance(),"DEBUG: Server failure but no AccountData in DB as well", Toast.LENGTH_SHORT).show();
                            }
                        }
                        realm.close();
                        

                        if (callingView!=null) {
                            callingView.onPostNetworkRequest();
                        }
                    }
                });

**Comment by cmelchior** [comment]
Hi @somghosh 
Currently no. We have considered adding such an option, but hasn't decided on anything final yet. You can see the discussion here: #931. I'll close this as a duplicate.
