### ISSUE TITLE
Date field gets reset to default value on createOrUpdateAllFromJson

### ISSUE THREAD

**Issue by hertill** [realm/realm-java#1095]
Unlike suggested by the changelog ("0.80.1 Realm.createOrUpdateWithJson() no longer resets fields to their default value if they are not found in the JSON input") createOrUpdateAllFromJson resets Date fields to 0 (beginning of time) when the corresponding value is missing in the input JSON

**Comment by cmelchior** [comment]
Yes, you a correct. Date is not behaving as it should. This will be fixed asap.

**Comment by hertill** [comment]
Great, thanks a lot!
