### ISSUE TITLE
Add reset method to RealmQuery

### ISSUE THREAD

**Issue by beeender** [realm/realm-java#1100]
Here is my use case:

I need to grab a list of json data from the server, and create/update them in my local realm.
When the list is huge, it really takes some time.

```
    if (obj.has("ID") && obj.get("ID").isJsonPrimitive()) {
        String code = obj.get("ID").getAsString();
        user = realm.where(User.class).equalTo("code", code).findFirst();
        if (user == null) {
            user = realm.createObject(User.class);
            user.setCode(code);
        }
    } else {
        Debug.stopMethodTracing();
        return null;
    }
  .... //Update others
```

Well, there is a reason that why i am not using convenient realm's JSON method to create/update my object.

Any way, here is the profiling result. The realm.where call does cost some time. In my case, it cost 20% single loop time.

Would it be good to have a reset method for the RealmQuery to reset the  TableQuery query to the initialized state to make it reusable again in the next create/update loop? At least in my case it will save 1ms for every single loop.

![screenshot from 2015-05-08 16-44-11](https://cloud.githubusercontent.com/assets/449296/7533215/29206898-f5a2-11e4-87ad-f6bc56fd3e6f.png)

**Comment by emanuelez** [comment]
You raise a valid point.
My first reaction was to check the `RealmQuery` constructors and look for some opportunity for optimizations but I didn't find anything major. So yes, I agree that having a `Realmquery.reset()` method would be a nice speedup for your use-case.

**Comment by beeender** [comment]
This is actually fixed when we integrate the Object Store `Results`
```c++
Results::Results(SharedRealm r, Query q, SortDescriptor s, SortDescriptor d)
```
The `Query` will be copied when creating the `Results` which means the original `Query` object can still be reused.
