### ISSUE TITLE
Create 32-bit and 64-bit realm gradle targets

### ISSUE THREAD

**Issue by roms** [realm/realm-java#1103]
We currently use
compile 'io.realm:realm-android:0.80.1'
in our gradle build to get the latest Realm (which has a 64 bit support) library into our app, but as

https://github.com/realm/realm-java/issues/1092

indicates, since Lollipop, Android is not smart enough to automatically choose the lowest common denominator and also run Realm in 32 bit mode.

So we have had to use the individual jar and .so files as suggested in http://realm.io/news/reducing-apk-size-native-libraries/ to exclude the 64 bit native library from our app build. However, we'd much rather use gradle than resort to including the various jar/.so files.

**Comment by cmelchior** [comment]
Which other libraries do you use that only supply 32-bit binaries? All newer high end android devices will be 64 bit, so the various libraries out there should really upgrade as fast as possible.

**Comment by roms** [comment]
We use the Adobe Creative SDK for image annotation and the Jumio SDK for credit card recognition. 

While I completely agree that the various libraries should upgrade as fast possible, most of them are not as responsive as the Realm developers. And I'm willing to bet there are developers out there using third party libraries with native components that may never get upgraded who would still love to use Realm. 

This is definitely an Android problem, but as more and more 64 bit phones make it into the wild, more and more developers using Realm are going to run into this problem.

**Comment by cmelchior** [comment]
Hi @roms 
Yes, it is a problem. The best approach would probably be Gradle plugin that could inspect all dependencies and remove arm64 binaries if needed, alternative we will look into distributing a arm32 only version.1

**Comment by yekretsam** [comment]
FYI: i tried to find a workaround for excluding the arm64 support the whole day so the solution might help someone else too:

packagingOptions {
        exclude 'lib/arm64-v8a/libtightdb-jni.so'
}

i would have loved to just exclude the whole folder instead of single *.so files, but i didn't get that to work.

**Comment by beeender** [comment]
Doc updated here https://realm.io/docs/java/latest/#couldnt-load-librealm-jniso
