### ISSUE TITLE
Possibility of a memory leak due to a combination of `RealmChangeListener` and `automaticUpdate`

### ISSUE THREAD

**Issue by kishikawakatsumi** [realm/realm-java#1109]
Reported by @zaki50 

`RealmChangeListener` is added to `Realm` when `automaticUpdate` is true. Then the listener instance was not released until the `Realm` instance is released because the `RealmChangeListener` is never deleted.

Since a listener instance is an anonymous inner class of `RealmBaseAdapter`, it holds a reference to the `RealmBaseAdapter` as an enclosing instance. `RealmBaseAdapter` usually holds a reference to the `Activity` that uses it as `Context`. So these instances will not be released until the `Realm` instance is released.

If you use `Realm` in only one Activity, there is no problem because `Realm#close()` is called when the `Activity`  is destroyed. (Strictly speaking, adapters may be accumulated if re-create a `RealmBaseAdapter` while the Activity is alive.)

On the other hand, if you use two activities, there are main activity and another activity that has `ListView`, each activity uses `Realm`, the `Realm` instance is held in cache until `onDestroy` of main activity is called. For example if you transition between the two Activities as follows, Main -> List-> back -> List -> back -> List... I think the `RealmChangeListener` may be accumulated in the `Realm`.

What do you think? @cmelchior @emanuelez

**Comment by cmelchior** [comment]
Hmm, I think you are right. This could be a very serious memory leak. 

Finding the solutions is a bit tricky though. I can come up with a few ideas but none seem ideal:

1) Add explicit unregister/close method to adapter. Similar to how people has to close a CursorAdapters cursor. 

2) Use WeakReferences to manage listeners.

**Comment by zaki50** [comment]
3) Clear listeners on each Realm.close() regardless of reference count. To do this, listeners list must be created against each Realm.getInstance().

current workaround: call `RealmBaseAdapter#updateRealmResults(RealmResults)` with `null` which unregisters RealmChangeListener from Realm instance.

**Comment by emanuelez** [comment]
I think this is actually the perfect use-case for `WeakReferences`.

Here is a nice explanation for it: https://www.youtube.com/watch?feature=player_detailpage&v=KTC0g14ImPc#t=1613
