### ISSUE TITLE
Possible to call RealmList.clear() outside a write transaction

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#1112]
It looks like it is possible to call RealmList.clear() outside a write transaction which can cause core to crash in some cases. Unit test exposing the issue is here: https://github.com/realm/realm-java/tree/cm-bug-clear.

There should be unit tests for all functions that modify Realm

**Comment by cmelchior** [comment]
Changelog 
* RealmList methods that requires a write transaction now correctly throws an exception if called outside one.

**Comment by emanuelez** [comment]
My proposal:
 * Fixed a bug occurring when accessing some methods of RealmList. They now throw the proper exception if they are called outside a transaction.
