### ISSUE TITLE
Publish Dash docset

### ISSUE THREAD

**Issue by kishikawakatsumi** [realm/realm-java#1118]
https://kapeli.com/docsets#javadoc

**Comment by 4goodapp** [comment]
This would be awesome.

**Comment by blivme84** [comment]
How to add realm java doc on dash

1. Download all realm java doc from web

```shell
wget --no-parent --recursive --level=inf --page-requisites --wait=1 https://realm.io/docs/java/latest/api/
```

2. Generate docset

```shell
javadocset Realm-Java realm/realm.io/docs/java/latest/api
```

3. Add generated `Realm-Java.docset` file to dash

**Comment by blivme84** [comment]
Check 

Preference > Downloads > User Contributed > search Realm Java

**Comment by cmelchior** [comment]
Outdated and user workaround provided. Closing
