### ISSUE TITLE
Link Queries example mistake

### ISSUE THREAD

**Issue by RobertoArtiles** [realm/realm-java#1119]
Hi guys,

I think I've found a mistake in the example provided under http://realm.io/docs/java/0.80.0/#link-queries

```java
RealmResults<Contact> contacts = realm.where(Contact.class).equalTo("email.active", true).findAll();
```

Taking in account this:
```java
public class Contact extends RealmObject {
    private RealmList<Email> emails;
    // Other fields…
}
```
The query should be:
_equalTo("**emails**.active", true)_.

**Comment by kneth** [comment]
@RobertoArtiles Thank you!

**Comment by kneth** [comment]
You will be able to see the change at next release (when we update the documentation).
