### ISSUE TITLE
Adding to Realm database changes a boolean from True to False

### ISSUE THREAD

**Issue by alin-rosu** [realm/realm-java#1120]
I have an Object Model that I use with Realm. I create a list of those objects, I set a Boolean to True inside those objects, I then try to add them to the database, and after that, I take the RealmList and try to go through it, the variale will be FALSE.
This is my stackoverflow quesion, where you have my code, and model:
http://stackoverflow.com/questions/30219968/adding-items-to-realm-database-changes-some-variables

**Comment by zaki50** [comment]
`SearchData` class has both `getIs_favorite()` and `is_favorite()`.

In that case, Realm annotation processor overrides only is_favorite().
That's why `getIs_favorite()` returns always `false`.

**Comment by cmelchior** [comment]
Hi @alin-rosu 
What @zaki50 says is true which is an unfortunate side effect of us allowing multiple naming schemes for boolean getters and setters. I have created a bug report on this here: https://github.com/realm/realm-java/issues/1130
