### ISSUE TITLE
Streamline SDK level across modules and documentation

### ISSUE THREAD

**Issue by zaki50** [realm/realm-java#1126]
README.md says API 19 and API 20 is required to build realm-java.

In addition to these API Levels,  realm-annotations-processor requires android.jar of API 21.

realm-annotations-processor/build.gradle:

```
    dependencies {
        ...
        testCompile files(new File(project.ext["sdk.dir"], '/platforms/android-21/android.jar'))
    }
```

It seems that we can use android-20/android.jar in realm-annotations-processor.
Is android.jar of API 21 really required?

**Comment by emanuelez** [comment]
You are right. I'm pretty sure we can use version 19 everywhere.

**Comment by cmelchior** [comment]
It looks like we have updated to API 24 across the board. Closing
