### ISSUE TITLE
mapping a json into a realmObject

### ISSUE THREAD

**Issue by cmonfortep** [realm/realm-java#1133]
Is there any solution to map a json where the name of the elements in a json are different from the name of the fields in my realmObject class?

something like ```@ SerializedName``` in GSON?

**Comment by cmelchior** [comment]
Realm currently doesn't offer any functionality like that natively. Is there any reason you don't want to use GSON?

**Comment by cmelchior** [comment]
I assume the above answered your question. Please reopen if that was not the case.
