### ISSUE TITLE
IllegalArgumentException with encrypted Realm after upgrading from 0.80.1 to 0.80.2 

### ISSUE THREAD

**Issue by benjaminburzan** [realm/realm-java#1137]
Hi,

I am encountering following Exception when updating from 0.80.1 to 0.80.2 and using the same realm file. 
```
The provided key is invalid. It should either be null or be 64 bytes long.
```
The key has not changed though. With 0.80.1 I was able to update my App properly when it was using 0.80.1. I could also migrate from 0.78 to 0.80.1 without any trouble.
But after I updated to 0.80.2 and then update the App, I get the IllegalArgumentException.

Can you help me with this issue?
Thanks
Ben

**Comment by emanuelez** [comment]
The code producing that exception is extremely simple:

```java
if (key != null && key.length != 64) {
   throw new IllegalArgumentException(INVALID_KEY_MESSAGE);
}
```

Are you absolutely sure the key you are passing is correct?

**Comment by benjaminburzan** [comment]
Thank you @emanuelez I found the error. It had something to do with our encryption algorithm. Sorry for bothering you we were on the wrong debugging way yesterday :)
Thanks for your support!

**Comment by emanuelez** [comment]
I'm glad I could help! :) Happy coding!
