### ISSUE TITLE
I try to createOrUpdate a realm object from json. the json is in the object but all fields are null

### ISSUE THREAD

**Issue by dangalg** [realm/realm-java#1139]
My code:

AppCFG appCFG = new AppCFG();

    if(jsonToParse != null) {

        Realm realm = Realm.getInstance(AppController.getInstance());

        appCFG.setOid(ParserJsonMethods.getOid(jsonToParse));

        appCFG.setBaseResourceUrl(jsonToParse.optString(AppCFGContract.BASE_RESOURCE_URL));
        appCFG.setClientName(jsonToParse.optString(AppCFGContract.CLIENT_NAME));
        appCFG.setBucketName(jsonToParse.optString(AppCFGContract.BUCKET_NAME));
        appCFG.setConfigUpdatedOn(StringConvertions.stringDateToMillis(jsonToParse.optString(AppCFGContract.CONFIGURATION_UPDATED_ON)));
        appCFG.setDefaultOutputVideoMaxFps(jsonToParse.optInt(AppCFGContract.DEFAULT_OUTPUT_VIDEO_MAX_FPS));
        appCFG.setLatestPackagePublishedOn(StringConvertions.stringDateToMillis(jsonToParse.optString(AppCFGContract.LATEST_PACKAGE_PUBLISHED_ON)));
        appCFG.setOnboardingPassed(jsonToParse.optBoolean(AppCFGContract.ONBOARDING_PASSED));
        appCFG.setOnboardingUsingPackage(jsonToParse.optString(AppCFGContract.ONBOARDING_USING_PACKAGE));
        appCFG.setPrefferedFootageOID(jsonToParse.optString(AppCFGContract.PREFFERED_FOOTAGE_OID));
        appCFG.setTweaks(jsonToParse.optString(AppCFGContract.TWEAKS));
        appCFG.setUploadUserContent(jsonToParse.optString(AppCFGContract.UPLOAD_USER_CONTENT));
        appCFG = parseMixedScreen(appCFG, jsonToParse);

        realm.beginTransaction();

        realm.copyToRealmOrUpdate(appCFG);

        realm.commitTransaction();
The result of pulling all results: All fields empty json attached
![screen shot 2015-05-20 at 10 24 00 am](https://cloud.githubusercontent.com/assets/5820649/7723975/d3a0f34e-fef5-11e4-9716-fbd033f0663e.png)

All fields are empty.. but somehow the json is attached to the object.. What am I doing wrong??

P.S. When I do result.getBaseResourceUrl() after pulling all results and opening this result (the result from the image), for instance, I get back a good answer which is:http://blah.blah. but when I try to get results from realm based on baseResourceUrl = "http://blah.blah" I get back nothing...

SO question here: http://stackoverflow.com/questions/30342946/i-try-to-createorupdate-a-realm-object-from-json-the-json-is-in-the-object-but/30345848?noredirect=1

**Comment by cmelchior** [comment]
Hi @dangalg 
Can you provide a sample project displaying this behavior?
Also to be 100% clear, are you saying that this returns null:

```
AppCFG result = realm.where(AppCFG.class).equalTo("baseResourceUrl","http://blah.blah").findFirst();
```

**Comment by emanuelez** [comment]
@dangalg The fields in the objects are always set to the default value for all RealmObjects and that's because we proxy the class and override getters and setters in order to perform zero-copy operations.
We also override `toString()` and that's why it looks correct in the popup window in your debugger

**Comment by JackWink** [comment]
@emanuelez that's a blocker for us, but with a slightly different case. Because the private fields are all null after querying the DB, we can't use GSON to serialize the realm object (since it uses reflection and not the getters).

**Comment by cmelchior** [comment]
You can still use GSON, but you have to write your own serializer. See this issue here for details on how to do that: https://github.com/realm/realm-java/issues/1127

**Comment by JackWink** [comment]
Ah, we've been using a copy-constructor with our RealmObject classes to get around it... I guess we were wishing there was a way to backfill the private variables after they're retrieved rather than manually specifying which ones to copy since we're already using GSON's @Expose(serialize / deserialize) annotations.

**Comment by cmelchior** [comment]
Sorry, but that isn't possible as that goes against the zero copy architecture of Realm.

We have been contemplating adding an option of getting a copy of your data from Realm. See this issue: https://github.com/realm/realm-java/issues/931 which is effectively what you do already. The only other option is writing your own GSON serializer.

**Comment by JackWink** [comment]
Yeah, I think I described it poorly, but #931 is exactly along the lines of what we were thinking, thanks

**Comment by kneth** [comment]
I'll close the issue. Please open a new or comment on #931 if you have questions.
