### ISSUE TITLE
RealmList.add() throws misleading exception for standalone objects

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#1140]
From this SO question: http://stackoverflow.com/questions/30340752/cant-add-new-object-to-realmlist-due-to-null-object-reference

The following will fail with a NullPointer exception:
```
RealmList<Bar> list = realm.where(Foo.class).findFirst().getBarList();
list.add(new Bar()); 
// throws NullPointerException: Attempt to invoke virtual method 'long io.realm.internal.Row.getIndex()' on a null object reference
```

As a minimum we should check if the object added is a managed RealmObject, but even better might be to do a ```copyToRealm()``` or ```copyToRealmOrUpdate``` inside the RealmList if it is a standalone object.

The later is needed for the following corner case:
```
RealmResult<Foo> result;
RealmList<BarWithPrimaryKey> list1 = result.get(0).getBarList();
RealmList<BarWithPrimaryKey> list2 = result.get(1).getBarList();

BarWithPrimaryKey newBar = new BarWithPrimaryKey();
list1.add(newBar);
list2.add(newBar);
```

which would fail if just using ```copyToRealm```.

What do you think @emanuelez @kneth

**Comment by kneth** [comment]
If we can avoid null pointer exceptions, I'm in! It is fine to throw an exception if we can detect an error condition, and a proper error message will help the user to correct her code.
