### ISSUE TITLE
Readonly Realms

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#1147]
Cocoa support opening Realms in ReadOnly mode. We should do the same.

**Comment by kneth** [comment]
Should it be read-only globally or by instance? The later is "easy" to implement by adding a flag and throw an exception when `beginTransaction()` is called.

**Comment by bmunkholm** [comment]
Also has to open the file in readonly mode.

**Comment by cmelchior** [comment]
I think it would make most sense given the new RealmConfiguration that this is done on pr. configuration basis, ie. it is possible to open the same file in both Readonly mode and write mode.

**Comment by beeender** [comment]
Since nobody really asked for this, put it into backlog.

**Comment by beeender** [comment]
Comments from Tim:
> The primary use-case was bundling data with your app on the app-store, and circumventing the need to move said data from the write-protected app bundle, to a writeable user folder
> Since this isn’t a thing on Android, I believe we agreed to backlog that feature on Android for now

**Comment by ahmedre** [comment]
that's not the only use case - another use case is having more than 1 realm database, in which case you need to mirror the schema of both databases in each one, even if they are both readonly (whereas on iOS, this isn't a problem). to me, this is the bigger reason i want this (not so much the dealing with `/data`, though it definitely would be nice if we didn't have to bother).

**Comment by joelteply** [comment]
We need to reopen this. It is causing us a big problem for the exact reason @ahmedre mentioned here. We ship a shared database of assets and also use another database for user specified things like favorites and their projects. More than the issue of it creating needless objects that don't belong in one schema, it's crashing saying there's a need to migrate a database, when it hasn't changed.

**Comment by cmelchior** [comment]
@joelteply If one Realm only contains a subset of classes, you should specify a RealmModule instead for that Realm. `readonly()` is not really connected to that. You can see more here: https://realm.io/docs/java/latest/#schemas

**Comment by cmelchior** [comment]
Bumping priority on this. It is a requirement for e.g. exposing Realm Mobile Platform permissions from users.

**Comment by cmelchior** [comment]
API:

```
RealmConfiguration config = new RealmConfiguration.Builder() 
  .assetFile("my.realm")
  .readOnly()
  .build();

SyncConfiguration config = new SyncConfiguration.Builder(user, server) 
  .readOnly()
  .waitForServerChanges()
  .build();
```

One observation is that it should be impossible to start a transaction against a read-only Realm. This also means that the schema cannot be written to the file, so any configuration using this option should either a) depend on `assetFile()` to provide it or b) use `waitForServerChanges()` #4270.

Note that we cannot prevent one process from creating a readonly Realm while another process has a mutable Realm. This is acceptable.

- [ ] It is unclear if the Object Store supports this, if not, it should be added there. Otherwise just expose the option.
- [ ] Expose `readOnly()` on the RealmConfiguration/SyncConfiguration.
- [ ] Add checks to the configuration that will make it throw if assetFile/waitForServerChanges are not used in combination with this.
- [ ] Unit tests
