### ISSUE TITLE
Change listener not called. Refresh stops to work

### ISSUE THREAD

**Issue by FaisalAbid** [realm/realm-java#1149]
After upgrading from 0.80.1 to 0.80.3, refresh() and the change listeners stop working. They work once or twice, but then stop refreshing or getting new changes.

**Comment by cmelchior** [comment]
Hi @FaisalAbid 
We made a change in 0.80.3 so that ChangeListeners are weak references inside Realm. This was due to fix other potential memory leaks, but it also means that if you do something like this:

```
realm.addChangeListener(new RealmChangeListener() {
 ...
});
```

your ChangeListener risk getting garbage collected which would give the error you see. If you save the listener in field variable it should work:

```
public class MyActivity extends Activity {

  private RealmChangeListener listener = new RealmChangeListener() {
    ..
  };

  protected onCreate() {
    Realm realm = Realm.getInstance(this);
    realm.addChangeListener(listener);
  }
 
  ...
}
```

We could probably have documented that change better.

**Comment by FaisalAbid** [comment]
Cool thanks, this works once made into a field

**Comment by sryze** [comment]
You might want to mention this somewhere in the documentation on [this page](https://realm.io/docs/java/latest/). I had the same problem with object change listener and for the life of me couldn't figure out what I was doing wrong until I found this issue.

**Comment by paulpv** [comment]
Ditto on mentioning this in the documentation. I too wasted a day trying to get this to work, and even tried the trick mentioned here, when finally I realized that I was closing the last reference to the realm instance which prevented the change listener from ever being called.

**Comment by kneth** [comment]
The example in the documentation (https://realm.io/docs/java/latest/#notifications) does it as outlined above. But we could add a short note in the text about weak references.

**Comment by iman2420** [comment]
With this code my app worked easily. But since listening to the socket in the `IntentService `and updating the database there, the `RealmChangeListener` sometimes works and sometimes not... why?

**Comment by Zhuinden** [comment]
You keep to keep a strong reference to the RealmResults. ¯\\_(ツ)_/¯

**Comment by cmelchior** [comment]
We recently updated https://realm.io/docs/java/latest/#notifications with a few examples that hopefully make this more clear
