### ISSUE TITLE
"Method does not override or implement a method from a supertype" (in the <classname>proxy file).

### ISSUE THREAD

**Issue by Murtaza42** [realm/realm-java#1151]
Here's my model class- 

    public class BasicSavedInfoImpl extends RealmObject implements BasicSavedInfo {

    private String iD;
    private String message;
    private long duration;
    private boolean bool;

    @Override
    public String getID() {
        return iD;
    }

    @Override
    public void setID(String ID) {
        this.iD= ID;
    }

    @Override
    public String getMessage() {
        return message;
    }

    @Override
    public void setMessage(String message) {
        this.message = message;
    }

    @Override
    public void setDuration(long duration) {

        this.duration = duration;
    }

    @Override
    public long getDuration() {
        return duration;
    }

    @Override
    public void setBool(boolean bool) {

        this.bool = bool;
    }

    @Override
    public boolean getBool() {
        return bool;
    }
    }

the proxy file i.e BasicSavedInfoImplProxy has `isbool()` instead of `getBool()`. Why is that happening? 

This is causing : `method does not override or implement a method from a supertype`

Thank you for reading.

**Comment by Murtaza42** [comment]
I came across a similar issue that opened earlier, and like mentioned there, none of my fields start with an `is`

**Comment by emanuelez** [comment]
Yeah, that seems to be a bug. I'm looking into it.

**Comment by emanuelez** [comment]
In the mean time, does renaming your boolean getter to use is instead fix your issue?

**Comment by Murtaza42** [comment]
Unfortunately, no. I'm now using an `int` and having it act as a makeshift boolean.

**Comment by emanuelez** [comment]
I tried replicating your issue here: #1160 
But it seems to be working fine. Am I missing something from your use-case?

**Comment by Murtaza42** [comment]
No, that's all my model class contains. I'll give it a go again and report back.

**Comment by kneth** [comment]
@Murtaza42 Do you still having this issue?

**Comment by Murtaza42** [comment]
@kneth , yes, I have this issue when I try to use a boolean. I've started using Integers as makeshift booleans instead, which works great.

**Comment by emanuelez** [comment]
Would it possible for you to share your project (or another one that reproduces the issue) with us?

**Comment by Murtaza42** [comment]
Sure, [here's the link to the project](https://github.com/Murtaza42/Android-Architecture-Playground), and [here's the link to the file in context](https://github.com/Murtaza42/Android-Architecture-Playground/blob/master/app/src/main/java/com/reddev/missedcallmanager/model/BasicSavedInfoImpl.java).

Note that I've changed boolean to integer.

**Comment by emanuelez** [comment]
Your project won't compile because it's missing all the view xml files. Also, you are using an ancient version of Realm. Please try the latest version.

**Comment by Murtaza42** [comment]
About that; I understand that Realm can't pass instances across threads. Why is it possible to do so in the older versions? I actually use the newest version now, and this project is quite old.

Yes, I haven't uploaded the layout files.

**Comment by emanuelez** [comment]
It was possible in older versions because of a mistake on our side. You should really not be using such an old version of Realm. We are working on a proper solution to be able to pass RealmObject and RealmResults among threads.

**Comment by Murtaza42** [comment]
This project is actually quite old, and I just took a look at it a few days back, and started to tinker a few days back. I do use the newest version in my latest projects. You may close this issue, since it's a remark of a deprecated version of Realm.

**Comment by emanuelez** [comment]
:+1:  :)
