### ISSUE TITLE
Link queries and contain

### ISSUE THREAD

**Issue by manuelwenner** [realm/realm-java#1155]
Hi Folks,

is it somehow possible to use "contains" in case of a link query? I want to query all Contacts where the field "address" in linked table "Email" contains gmail for example.

Thanks in advance,
Manuel

**Comment by cmelchior** [comment]
Hi @manuelwenner 

Yes that should be possible.

```
realm.where(Contacts.class).contains("email.address", "gmail").findAll();
``

should work?

**Comment by manuelwenner** [comment]
Hi @cmelchior 

I tried this too but in this case i get an error "java.lang.IllegalArgumentException: 'contains' is not supported for link queries"

**Comment by cmelchior** [comment]
Which version of Realm are you using? It should be supported in the current version (0.80.3)?

**Comment by manuelwenner** [comment]
Same idea in the same moment :) I used 0.70.5. After updating to the current version it's working. Thanks a lot man. And after using .beginsWith everything is perfect :+1:

**Comment by cmelchior** [comment]
No problem. Happy coding :)

**Comment by manuelwenner** [comment]
Thanks :) With support like this it makes much more fun :) Love to see the development of realm. Keep on going!
