### ISSUE TITLE
Function not implemented in io_realm_internal_SharedGroup.cpp line 100

### ISSUE THREAD

**Issue by bhbfhfb** [realm/realm-java#1157]
Error occurs in the BlackBerry.

- Version
 - io.realm:realm-android:0.80.2

- Tested Devices
 - BlackBerry Q10
 - BlackBerry Classic

- Error Log
 1. java.lang.RuntimeException: Unspecified exception. mremap(): failed: Function not implemented in io_realm_internal_SharedGroup.cpp line 100	
 2. at io.realm.internal.SharedGroup.createNativeWithImplicitTransactions(Native Method)	
 3. at io.realm.internal.SharedGroup.<init>	(SourceFile:58)
 4. at io.realm.Realm.<init>	(SourceFile:201)
 5. at io.realm.Realm.createAndValidate	(SourceFile:509)
 6. at io.realm.Realm.create	(SourceFile:482)
 7. at io.realm.Realm.getInstance	(SourceFile:400)
 8. at io.realm.Realm.getInstance	(SourceFile:362)

**Comment by emanuelez** [comment]
Unfortunately that is a problem with Blackberry, which did not implement that function in their version of the C library. You can see more about it following this issue: #619
