### ISSUE TITLE
some question about use

### ISSUE THREAD

**Issue by Samsu7609** [realm/realm-java#1159]
Foo extends RealmObject
protected String id
getter and setter..

A extends Foo
private String phone;
getter and setter

B extends Foo
private String school;
getter and setter

when compiler got error 
error: A RealmClass annotated object must be derived from RealmObject

Sorry for my english ... 
and Someone plz tell how to use realm in My Case 

Thanks

**Comment by emanuelez** [comment]
Hello!

Right now we don't have support for inheritance (not polymorphism). 
We have an open issue for it already (https://github.com/realm/realm-java/issues/761) so you can follow the progress there.
In the mean time you can use composition instead of inheritance:

```java
class Foo extends RealmObject {
   private String id;
   // getters and setters
}

class A extends RealmObject {
   private String phone;
   private Foo foo;
   // getters and setters
}

class B extends RealmObject {
   private String school;
   private Foo foo;
   // getters and setters
}
```

I hope this helps!

**Comment by Samsu7609** [comment]
@emanuelez  thanks your answer !

**Comment by emanuelez** [comment]
I'm glad I could help! Happy coding! :)

**Comment by wpx121314** [comment]
+q wait for
