### ISSUE TITLE
Some Question about use

### ISSUE THREAD

**Issue by Samsu7609** [realm/realm-java#1162]
I have two class A and B then both extends RealmObject
A and B do not hava any relationship

realm.beginTransaction();
A a = realm.createObject(A.class)
do something ...
realm.commitTransaction();

B a = realm.createObject(B.class)
do something ...
realm.commitTransaction();

but i got  FATAL EXCEPTION about  
RealmMigrationNeededException: The Foo class is missing from the schema for this Realm.

So can i use realm like a  "A shareprefence" and "B shareprefence" 

Sorry for my poor English ...

**Comment by emanuelez** [comment]
That is expected behavior. You are changing the model classes but the Realm file you have installed comes from the previous version of your model.
During development `Realm.deleteRealmFile()` is very handy if you don't need to save any data from your previous runs.

**Comment by Samsu7609** [comment]
@emanuelez  thanks again 
but i want save A class data also B class data 
don't want to delet file ...
Realm does't support  this case ?

**Comment by kneth** [comment]
You probably have to write a migration step to update your Realm file when you upgrade your app. Please take a look at https://realm.io/docs/java/latest/#migrations

**Comment by kneth** [comment]
@Samsu7609 I will close the issue. Feel free to open a new issue if you have any questions.
