### ISSUE TITLE
Add x86_64 Support

### ISSUE THREAD

**Issue by aaalaniz** [realm/realm-java#1167]
I know there isn't a ton of devices out there that have this arch yet but there are x86_64 emulators available. Is there a timeline for this to be supported?

Thanks!

**Comment by emanuelez** [comment]
No timeline is available yet, but considering how popular the Asus Zenfone2 is getting it looks like we will add this soon :)

**Comment by elikohen** [comment]
+1
We at Ztory are using realm as our mobile data-base on iOS and Android. Our product is Tablet based and enabling the x86_64 support will be great for us. I know that Realm is free and that i cannot push you to do it. But you did and are doing a really great job and i just wanted to give you another small reason to add this support :P

**Comment by cmelchior** [comment]
@elikohen x86_64 support has been merged to master and should be part of the next release.
