### ISSUE TITLE
Unchecked cast warnings

### ISSUE THREAD

**Issue by joey-harward** [realm/realm-java#1169]
I am getting the unchecked cast warning for the proxy class that gets generated for all my realm objects.

Here is an example of the warning generated when processing my simple User class:

required: E
  found:    UserRealmProxy
  where E is a type-variable:
    E extends RealmObject declared in method <E>newInstance(Class<E>)
[[directory to my build]]/intermediates/classes/release/io/realm/DefaultRealmModuleMediator.java:186: warning: [unchecked] unchecked cast
        Class<E> clazz = (Class<E>) ((obj instanceof RealmObjectProxy) ? obj.getClass().getSuperclass() : obj.getClass());

I like to run a **no** warning environment, so this makes things really difficult ;)

**Comment by cmelchior** [comment]
Yes. Warnings should be a no go, and this should definitely be fixed.
