### ISSUE TITLE
Database migration process went harder when creating new model classes

### ISSUE THREAD

**Issue by tmeunier** [realm/realm-java#1173]
Hi,
I've ran into an problem after updating from Realm 0.80.1 to 0.80.3.

### 1. The goal is to migrate my database with new model entities
I have to add model entities in my app within each iteration of my app. These entities have many columns (5 to 15).
I **cannot** simple break my databases (they contain hundreds of records).

### 2. The migration was working...
My migration process was simple: when adding a new class, the table and columns were created when calling ```realm.createObject( clazz )```

### 3. ...until upgrade
After updating Realm my code throws ```java.lang.ArrayIndexOutOfBoundsException: Table has no columns: class_xxx```

### 4. I've find out why
The code that was initialising the table scheme is not executed, instead a simple getTable which creates an EMPTY table
```java

public <E extends RealmObject> E createObject(Class<E> clazz) {
  Table table = getTable(clazz);
  long rowIndex = table.addEmptyRow(); <==== crash is here, because the is no column in the table!
  return get(clazz, rowIndex);
}
```

The only createTable ever executed is in ```initializeRealm```, but it's only executed when there is no version on the database... which causes me trouble (as my database version is 2 in the present case)
```java
// Create and validate table
if (version == UNVERSIONED) {
     proxyMediator.createTable(modelClass, realm.transaction);
}
```

### So my solutions are:
- use java.reflect to call this "createTable" directly (that will break if you change a thing)
- add every column of every new class (~100 columns)  :/

I know you are not working on migration process, but in my opinion this is a regression. A simple "createTableIfNonExistent" method would do the trick until a new migration system is up.
I'd be happy with any suggestion, feedback.

**Comment by cmelchior** [comment]
Hi @tmeunier 
It is not really a regression as the logic for calling createTable() has not changed. That said I can understand why you find it cumbersome to add many new classes with many fields.

Unfortunately there is no easy answer for you as providing a function like ```Realm.createTableIfNotExisting(Foo.class)``` would be very dangerous and not future safe, .e.g. let say you in version 2 did call such a method but then in version 3 decided to rename one field inside ```Foo```. 
Handling that logic would be non-trivial and very error prone as your version 2 migration code would no longer work as expected.

You have a number of options though:

1) Write the necessary migration code. Yes, it is cumbersome, but only has to be written once, and it will make maintaining that code easier in the future.

2) Delete the database and recreate it (doesn't like an option in your case)

3) As a hack you can call ```FooRealmProxy.initTable(realm.transaction)``` without using reflection, but that would require you migration code to be in the io.realm package name to access the package protected variable. This is actually just what that code you referred to are doing. So you might just want to skip the reflection step.

We are currently working on a new migration API, so I will take that as input and see if maybe we can come up with something that can make a use case such as yours easier to handle.

**Comment by tmeunier** [comment]
@cmelchior 
Thanks for your answer.
I mostly created this issue to help others that may be in this case ;)

Yes, I understand the limitations/problems of a method like this. It was just a suggestion.

As for your options:
1) Yes, I think this is the "best" solution. I'll make the changes when I have time.
2) Never an option when managing user data ^^
3) I did not think about that, I'll take a look.

I have a very intensive use of your library, so I may have a few ideas if you want them :)

**Comment by cmelchior** [comment]
We would love any and all comments about the API, so please share them :)
You can send them to help@realm.io if you don't want to post them here.

**Comment by yaming116** [comment]
did you say this, https://github.com/realm/realm-java/blob/master/examples/migrationExample/src/main/java/io/realm/examples/realmmigrationexample/model/Migration.java

**Comment by kneth** [comment]
@tmeunier I'll close the issue and will look forward to your ideas in our mail box.
