### ISSUE TITLE
Include the Kotlin example in the distribution package

### ISSUE THREAD

**Issue by emanuelez** [realm/realm-java#1175]

**Comment by yoavst** [comment]
I think the kotlin example should be changed to looks like:
```kotlin
public RealmClass open class History(
        public open PrimaryKey var time: Long = -1,
        public open Index var song: Song? = null,
        public open var listeningDuration: Int = -1) : RealmObject()
```

**Comment by cmelchior** [comment]
This should not be part of the distribution package.

**Comment by cmelchior** [comment]
@ez this can be closed now, right?

**Comment by cmelchior** [comment]
@emanuelez This can be closed now, right?

**Comment by emanuelez** [comment]
Yes it can

**Comment by cmelchior** [comment]
With the new build system merged to master, all example projects will be distributed automatically. Closing this.
