### ISSUE TITLE
System.exit(0) doesn't work appropriately when working with Realm. 

### ISSUE THREAD

**Issue by grub-** [realm/realm-java#1181]
Today I noticed issue that when I added realm to cache level.
Restarting application with:
```java
//doing anything with Realm
Realm.getInstance(context).close();
System.exit(0) ;
```
freezing application. I would like to know why is happening so? Any workarounds?

**Comment by cmelchior** [comment]
Hi @grub- 
Using ```System.exit``` is in general a very bad idea: http://stackoverflow.com/questions/16480867/system-exit0-doesnt-close-all-my-activities

That said, I cannot reproduce the described behaviour. When you say freeze, what do you mean exactly? That you eventually get ANR errors or something else?

**Comment by grub-** [comment]
Thanks for point me out. You are very responsive!

I just added 
```
 @Override public boolean onCreateOptionsMenu(Menu menu) {
        menu.add(1, 1, 1, "exit");
        return true;
    }

    @Override public boolean onMenuItemSelected(int featureId, MenuItem item) {
        if (item.getItemId() == 1) {
            System.exit(0);
        }
        return super.onMenuItemSelected(featureId, item);
    }
```
to IntroExample and I see the same(eventually getting ANR and dialog with closing app), btw I'm using Android 5.1. 
With closing Activity with 'finish()' as mentioned in that link or  'killProcess(myPid())' everything works fine.
