### ISSUE TITLE
Document build.gradle config for Kotlin on website

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#1184]
Adding Kotlin to a Realm project require some additional setup that we should document under "Other libraries" on Realm.io. We already had a few users run into problems (even though it is only in SNAPSHOT).

https://github.com/realm/realm-java/pull/1171#issuecomment-108295753

See the Kotlin example for other things:
- Classes must be open.
- kapt must be defined in build.gradle.

**Comment by cmelchior** [comment]
With #909 merged. This task is mostly about documenting the restrictions since kapt is added by the plugin

**Comment by cbush** [comment]
We are revamping the Realm docs. We're not ignoring this issue -- we've read through every one of them, and we'll be sure to address this as part of our updates. We're closing the GitHub issues and creating new JIRA tickets to track the work at a high level.
