### ISSUE TITLE
Query API flawed?

### ISSUE THREAD

**Issue by teddis** [realm/realm-java#1185]
I'm sorry, I just started using Realm and like it a lot, and haven't had time to check if this has been brought up, so please forgive me and close this out otherwise. It seems as though the API to provide a String fieldname is flawed since it is not checked at compile time, so changing a field name in the model requires a huge effort to modify everywhere. I suppose one way is to just create a public constant in each model class, but this just feels wrong. You could use some kind of reflection, or you could make the fields public in the model, but that would seem to defeat the requirement of using getters/setters. Just curious why this wasn't thought through more.

**Comment by cmelchior** [comment]
Hi @teddis 
Thank you for taking the time to comment on this.

You are right that it would make the API a lot easier to use if those constants where auto generated for you, however this is not as easy as it sounds.

Auto generated code is not available until the annotation processor has run the first time. This means you have to know to press compile before using any constants. You see this problem with e.g. AutoValue/AutoParcel and it is not a particular good workflow.

Other libraries like e.g. GreenDAO does it a bit differently by requiring you to put all our model classes in separate project. This automatically make sure they are compiled before use, but also makes setup a bit more cumbersome.

So to address your issue: This is actually something we have considered a lot (and are still debating), but right now we feel the current approach is the best comprise between ease of use and type safety. That said we are still considering different options, and we haven't ruled out making a type safe query language as an advanced feature.

We always welcome feedback such as yours as it helps us guide our design decisions, so please don't hold back if you have any ideas on how to improve this or other parts of the API.
