### ISSUE TITLE
Realm instance unexpected close

### ISSUE THREAD

**Issue by sideris** [realm/realm-java#1188]
Hello.
I got the following message `....Realm instance has already been closed`

My code was like this
```java
.....
Account account = createAccount(....);
User user = createUser(account,......);

public Account createAccount(....){
  try(Realm realm = Realm.getInstance(context)){
   .....
  }catch(){
    ......
  }
}

public User createUser(Account account, .....){
  try(Realm realm = Realm.getInstance(context)){
   .....
  }catch(){
    ......
  }
}
```

I tried to see if the same happens when being outside of `try`
```java
Account account = <some explicit query>
Realm realm = Realm.getInstance(this);
realm.close();
Log.e("This should fail according to the previous", account.getNumber() + "");
```
But it works as it should. I removed all the try and just did `Realm realm = Realm.getInstance(context)` and it worked, but somehow does not feel right not closing the connection. 

I, also, have to note that I got the error when I was trying to access a property of account inside the `createUser`.

Now I don't know if it is a bug or I am just doing something stupid, so feel free to comment and/or close it directly. 

Thanks and keep up the good work.

**Comment by cmelchior** [comment]
Hi @sideris 
Your RealmObjects are only available as long as your Realm instance is open as RealmObjects lazy load their data. The reason for this is that Realm uses a zero-copy architecture which means we only load data you actually use, but it also require the Realm instance being open for the lifetime of the object.

This is also why we recommend you follow the Android lifecycle when managing your Realm instances, eg. opening during onCreate() and closing during onDestroy().

Eg. the following will give you the error you are seeing:

```
Realm realm = Realm.getInstance(this);
Foo foo = realm.where(Foo.class).findFirst();
realm.close();
foo.getBar(); // Will throw an exception
```

**Comment by sideris** [comment]
Okay, great. 

Thanks for the response!
