### ISSUE TITLE
Building source on Ubuntu/NDK r10e fails

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#1196]
Copy from here: https://groups.google.com/forum/#!topic/realm-java/FAKK0OzBaPs

---
I forgot to mention so I am using:
android-ndk-r10e
GNU Make 3.81
javac 1.7.0_80
----
Hi,

In order to use the latest source for which there is no snapshot yet I have decided to build realm from source. I have followed the instructions from the github page:
https://github.com/realm/realm-java#using-snapshots

Here are some debug logs of the error but I have no idea how to solve it.

14:33:17.329 [QUIET] [system.out] make: Entering directory `/home/valeria/src/realm-java/realm-jni/src'
14:33:17.329 [QUIET] [system.out] aarch64-linux-android-g++ -shared -Os -pthread columntypeutil-arm64.pic.o io_realm_internal_Group-arm64.pic.o io_realm_internal_LinkView-arm64.pic.o io_realm_internal_Row-arm64.pic.o io_realm_internal_SharedGroup-arm64.pic.o io_realm_internal_SubtableSchema-arm64.pic.o io_realm_internal_table-arm64.pic.o io_realm_internal_TableQuery-arm64.pic.o io_realm_internal_tableview-arm64.pic.o io_realm_internal_Util-arm64.pic.o io_realm_internal_Version-arm64.pic.o java_lang_List_Util-arm64.pic.o mem_usage-arm64.pic.o mixedutil-arm64.pic.o TableSpecUtil-arm64.pic.o util-arm64.pic.o -lrealm-android-arm64 -lstdc++ -lsupc++ -llog -L/home/valeria/src/realm-java/realm-jni/../core-0.89.2 -Wl,--gc-sections -flto -std=c++11 -ffunction-sections -fdata-sections -flto -o librealm-jni-arm64.so
14:33:20.075 [ERROR] [system.err] In member function 'prealloc_if_supported':
14:33:20.075 [ERROR] [system.err] lto1: internal compiler error: bytecode stream: expected tag block instead of LTO_type_ref
14:33:20.075 [ERROR] [system.err] Please submit a full bug report,
14:33:20.075 [QUIET] [system.out] make: Leaving directory `/home/valeria/src/realm-java/realm-jni/src'
14:33:20.075 [ERROR] [system.err] with preprocessed source if appropriate.
14:33:20.076 [ERROR] [system.err] See <http://source.android.com/source/report-bugs.html>; for instructions.
14:33:20.077 [ERROR] [system.err] lto-wrapper: aarch64-linux-android-g++ returned 1 exit status
14:33:20.077 [ERROR] [system.err] /home/valeria/src/realm-java/realm-jni/build/standalone-toolchains/arm64/bin/../lib/gcc/aarch64-linux-android/4.9/../../../../aarch64-linux-android/bin/ld: lto-wrapper failed
14:33:20.077 [ERROR] [system.err] collect2: error: ld returned 1 exit status
14:33:20.078 [ERROR] [system.err] make: *** [librealm-jni-arm64.so] Error 1
14:33:20.078 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Changing state to: FAILED
14:33:20.078 [DEBUG] [org.gradle.process.internal.DefaultExecHandle] Process 'command 'make'' finished with exit value 2 (state: FAILED)
14:33:20.079 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':buildAndroidJniArm64'
14:33:20.080 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :realm-jni:buildAndroidJniArm64 FAILED
14:33:20.080 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :buildAndroidJniArm64 (Thread[main,5,main]) completed. Took 2.778 secs.
14:33:20.080 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[main,5,main]] finished, busy: 3.367 secs, idle: 0.003 secs
14:33:20.084 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on buildscript class cache for build file '/home/valeria/src/realm-java/realm-jni/build.gradle' (/home/valeria/.gradle/caches/2.4/scripts/build_32o2kq7ioc55bn2yi2hbmsz4n/ProjectScript/buildscript).
14:33:20.085 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on no_buildscript class cache for build file '/home/valeria/src/realm-java/realm-jni/build.gradle' (/home/valeria/.gradle/caches/2.4/scripts/build_32o2kq7ioc55bn2yi2hbmsz4n/ProjectScript/no_buildscript).
14:33:20.086 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Closing cache fileSnapshots.bin (/home/valeria/src/realm-java/realm-jni/.gradle/2.4/taskArtifacts/fileSnapshots.bin)
14:33:20.087 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Closing cache taskArtifacts.bin (/home/valeria/src/realm-java/realm-jni/.gradle/2.4/taskArtifacts/taskArtifacts.bin)
14:33:20.087 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Closing cache outputFileStates.bin (/home/valeria/src/realm-java/realm-jni/.gradle/2.4/taskArtifacts/outputFileStates.bin)
14:33:20.088 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Closing cache fileHashes.bin (/home/valeria/src/realm-java/realm-jni/.gradle/2.4/taskArtifacts/fileHashes.bin)
14:33:20.088 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on task history cache (/home/valeria/src/realm-java/realm-jni/.gradle/2.4/taskArtifacts).
14:33:20.090 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.memcache.InMemoryCachedRepositoryFactory] In-memory dependency metadata cache closed. Repos cached: 1, cache instances: 1, modules served from cache: 0, artifacts: 0
14:33:20.091 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.CachedStoreFactory] Resolution result cache closed. Cache reads: 0, disk reads: 0 (avg: 0.0 secs, total: 0.0 secs)
14:33:20.091 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.CachedStoreFactory] Resolved configuration cache closed. Cache reads: 0, disk reads: 0 (avg: 0.0 secs, total: 0.0 secs)
14:33:20.092 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.ResolutionResultsStoreFactory] Deleted 2 resolution results binary files in 0.002 secs
14:33:20.093 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':realm:compileJni'
14:33:20.094 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :realm:compileJni FAILED
14:33:20.097 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :realm:compileJni (Thread[main,5,main]) completed. Took 3.631 secs.
14:33:20.097 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[main,5,main]] finished, busy: 5.196 secs, idle: 0.003 secs
14:33:20.101 [ERROR] [org.gradle.BuildExceptionReporter]
14:33:20.101 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
14:33:20.101 [ERROR] [org.gradle.BuildExceptionReporter]
14:33:20.102 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
14:33:20.102 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':buildAndroidJniArm64'.
14:33:20.102 [ERROR] [org.gradle.BuildExceptionReporter] > Process 'command 'make'' finished with non-zero exit value 2
14:33:20.102 [ERROR] [org.gradle.BuildExceptionReporter]
14:33:20.102 [ERROR] [org.gradle.BuildExceptionReporter] * Try:
14:33:20.102 [ERROR] [org.gradle.BuildExceptionReporter] Run with --stacktrace option to get the stack trace.
14:33:20.103 [LIFECYCLE] [org.gradle.BuildResultLogger]
14:33:20.103 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED
14:33:20.103 [LIFECYCLE] [org.gradle.BuildResultLogger]
14:33:20.103 [LIFECYCLE] [org.gradle.BuildResultLogger] Total time: 19.415 secs

**Comment by emanuelez** [comment]
Realm core and JNI need to be compiled with the same version of the NDK in order to avoid these LTO issues. We should probably document the suggested version of the NDK to use.

**Comment by valllllll2000** [comment]
So which version of NDK should I use? is it r10d ?

**Comment by emanuelez** [comment]
Yes, that's what we're currently using.

**Comment by emanuelez** [comment]
It'd also stated in our Readme so I will close this one

**Comment by stevyhacker** [comment]
I tried building it on ubuntu 14.04 with r10d version of NDK and I get this error as well.

**Comment by beeender** [comment]
@stevyhacker After you change ndk version, you have to clean the project. And I'm sorry that `./gradlew clean` will leave something behind...

Try with `git clean -ndX` find all those files and delete them. build again.

**Comment by stevyhacker** [comment]
Thank you @beeender , It worked after deleting the files manually and building again.
