### ISSUE TITLE
Question: How to recover from unclosed realms

### ISSUE THREAD

**Issue by richardlay** [realm/realm-java#1197]
Even though I've carefully ensured I'm closing my realm using try/catch/finally blocks, sometimes we experience unclosed realms - possibly due to a crash elsewhere in the app.

The issue is once this happens the unclosed realm instance seems to linger until I force kill the app or I uninstall the app.

How do I recover from this without having the user to force kill the app?

**Comment by cmelchior** [comment]
@richardlay 
Currently we don't have anything like ```realm.closeAll()``` or similar, so I am afraid we don't have any good solutions for you.

Instead of using try/catch to control realm instance lifecycle, have you tried using the normal activity/fragment lifecycle instead or alternative create a wrapper around Realm so you can implement your own instance counter to better manage the lifecycle of the Realm instance?

**Comment by richardlay** [comment]
We're using realm in a library project so using the activity lifecycle isn't an ideal solution.

Unclosed realms is actually quite problematic for us so hopefully this part of Realm will improve in the future.

Thanks.

**Comment by kneth** [comment]
@richardlay You mention than the app is crashing/failing elsewhere. Do you have an idea of what the failure is? Is it related to Realm?

**Comment by richardlay** [comment]
Not related to realm. It was just an example. My point was that if we
somehow get into a state where there is an unclosed realm it is not easy to
recover.

On Fri, Jun 12, 2015 at 4:50 PM, Kenneth Geisshirt <notifications@github.com

**Comment by cmelchior** [comment]
Hi @richardlay 
I agree that in the case where it is unclear how many Realm instances are open. Getting back to a stable state can be problematic. We already have a task for documenting best practice for handling the Realm lifecycle, so we should definitely also document strategies for avoiding cases such as yours: https://github.com/realm/realm-java/issues/874

That said we are still looking into how to simplify the Realm lifecycle with the hope of getting rid of the ```close()``` completely, but for now I'll be merging this issue into #874
