### ISSUE TITLE
Multi schema support

### ISSUE THREAD

**Issue by richardlay** [realm/realm-java#1198]
Is there support for multiple schemas? My app has two database files, and each requires it's own schema.

However I have found that if I change the model for one database, I get a RealmMigrationNeededException for both databases.

**Comment by cmelchior** [comment]
Hi @richardlay 
Right now all Realms are required to have the same schema, so you would have to perform a migration on both Realms. 

That said, we just merged  two concepts called RealmModules and RealmConfiguration to master which would allow you to do exactly what you need. We are still working on the samples/documentation, but you can see how it will work here: https://github.com/realm/realm-java/tree/cm-realm-module-example/examples/realmModuleAppExample

**Comment by richardlay** [comment]
Great! I'll wait for the proper release.

Thanks.

**Comment by kneth** [comment]
@richardlay I'll close the issue. When the `RealmModule` feature is realised, you're welcome to open a new issue it doesn't work for you.
