### ISSUE TITLE
How to create in-memory copy of an realm object in order to modify the object outside transactions?

### ISSUE THREAD

**Issue by risayew** [realm/realm-java#1202]
I have a need to load the realm object from the database, then modify its different fields in memory, afterwords store the modified object on some "save" button click.
One solution, which i see at the moment, is to create a new object and initialize its fields(fileld-wise) from the loaded realm object. At the end call mRealm.copyToRealmOrUpdate();

**Comment by risayew** [comment]
close, because of repeating  in #931

**Comment by TheImShrey** [comment]
As of now, Dec 2020, there is not proper solution of this issue. We have many workarounds though.

Here is the one I have been using, and one with less limitations in my opinion.

 1. Make your Realm Model Object classes conform to codable
```
class Dog: Object, Codable{
    @objc dynamic var breed:String = "JustAnyDog"
}
```
 2. Create this helper class

```
class RealmHelper {
    //Used to expose generic 
    static func DetachedCopy<T:Codable>(of object:T) -> T?{
       do{
           let json = try JSONEncoder().encode(object)
           return try JSONDecoder().decode(T.self, from: json)
       }
       catch let error{
           print(error)
           return nil
       }
    }
}
```

 3. Call this method whenever you need **detached / true deep copy** of your Realm Object, like this: 

```
 //Suppose your Realm managed object: let dog:Dog = RealmDBService.shared.getFirstDog()
 guard let detachedDog = RealmHelper.DetachedCopy(of: dog) else{
    print("Could not detach Note")
    return
 }
//Change/mutate object properties as you want
 detachedDog.breed = "rottweiler"
```


As you can see we are piggy backing on Swift's JSONEncoder and JSONDecoder, using power of Codable, making true deep copy no matter how many nested objects are there under our realm object. Just make sure all your Realm Model Classes conform to Codable.

Though its **NOT** an ideal solution, but its one of the most effective workaround.
