### ISSUE TITLE
[Q] get sorted list of objects based on count of fields

### ISSUE THREAD

**Issue by yoavst** [realm/realm-java#1204]
I'm having an History object. History object has time and Song object which contains id. (they contain more field but for my explanation it is enough).
So I want to do a top 10 of the last week for example.
So first I fetch all the history objects where time >= (time before week).
```kotlin
val histories = App.realm.where(javaClass<History>()).findAll()
val before = System.currentTimeMillis()
val map = HashMap<Song, Int>()
for (history in histories) {
      if (history.song in map)
          map[history.song]++
      else map.put(history.song, 1)
}
val songs = map.entrySet() sortDescendingBy { it.getValue() } map { it.getKey() }
e("TIme: " + (System.currentTimeMillis() - before).toString())
``` 
with 10,000 objects (with same song) it takes 2.5 seconds for creating the `map`.
Is there a way to do it with the library's api?

**Comment by kneth** [comment]
It is an interesting case. You could really use a pivot/group-by method or just a distinct method. We haven't yet implement such functionality (see #960 for some of the discussion). I believe that your app could benefit from using Realm but you might need to do the data modelling a bit different.

First, let's have two model classes (I have left out the getters and setters):

    class Song extends RealmObject {
        private long id
        private RealmList<History> histories;
    }
    
    class History extends RealmObject {
        private Date played;
    }

Now, each song has a list of timestamp for when it was played. You can now build up your top 10 like this:

    map = HashMap<Long, Long>();
    Date before = ...; // the timestamp you wish to go back to
    RealmResults<Song> songs = realm.allObjects(Song.class);
    for (Song song : songs) {
        long nPlayed = song.where().greaterThan("histories.played", before).count();
        map.put(song.id, nPlayed);
    }
    // sort map and display the first 10

**Comment by yoavst** [comment]
Is there a big difference between `realm.allObjects()` and `realm.where().findAll()`?

**Comment by kneth** [comment]
`realm.allObjects()` is short for `realm.where().findAll()`.

My best guess is that sorting of `map` is going to be the bottleneck. The `song.where().greaterThan("histories.played", before).count()` is a fast way of getting the numbers out. As you can see, you don't get a `RealmResults` back in the loop (no `findAll()` calls), and the `count()` call is pretty fast.

**Comment by yoavst** [comment]
Will it be overwhelm on a song object?
I got a fragment that show the history in recyclerView. Currently, for each history item it gets the song object and show its data. Now, it will have to load also all the histories belongs to the song.

**Comment by kneth** [comment]
In that case, backlinks (or reverse lookups) are required. We have an open issue (#607) on that. The current work-around is to manually keep track of them. That is, your model classes could be:

    class Song extends RealmObject {
        private long id
        private RealmList<History> histories;
    }
    
    class History extends RealmObject {
        private Date played;
        private song Song;
    }

**Comment by yoavst** [comment]
What would be less load on the system, a `Song` with `RealmList<History>` or with `RealmList<Pair<Int,Long>>` where the int is `History`'s id and the long is time stamp.
There is only one specific case I need list of histories for a specific song, most of the time I'm showing song's info from history (for example, history page)

**Comment by kneth** [comment]
Storing integers as strings sound expensive. If the history is your primary data, then two classes as

    class Song extends RealmObject {
        private long id
        // and other stuff about a song    
   }
    
    class History extends RealmObject {
        private Date played;
        private song Song;
    }

If you know the ID of a song, you can easily get its history:

    RealmResults<History> h = realm.where(History.class).equalsTo("song.id", id).findAll();

and if you need the history sorted, just use `findAllSorted("played")` instead of `findAll()`.

**Comment by yoavst** [comment]
Will this be faster than what I offered for top 10 by song?
If you save RealmList<X> as array of int than it is more expensive, but if not, why is that so expensive?
Example string is: "1434126908;1434126408;1433126908`

**Comment by kneth** [comment]
If you have an array of integers stored as a string, you will need to parse the string to get the integers back. In your case, you will have to split by semicolon (scales linearly with the number of characters), and then convert the individual substrings to numbers. Using Realm, the numbers are in memory when you wish to access them.

The `RealmList` is implemented as a list of references, and accessing elements of a `RealmList` is pretty fast.

**Comment by yoavst** [comment]
`History` class have `time` as primary key. So if I'll go on all the histories in the `RealmList` and get the time, will it be faster then parsing the string?

**Comment by kneth** [comment]
It's hard to guarantee but I would think that a `RealmList` will be faster than parsing strings.

**Comment by yoavst** [comment]
Ok thanks, I'll switch to `RealmList`
