### ISSUE TITLE
Database Query in Documentations

### ISSUE THREAD

**Issue by teddywest32** [realm/realm-java#1210]
I am trying to get a full column from the database, but couldnot figure out what is the query to do so.

Can you please update the Documentations with all of the possible queries. I am stuck in the queries.

**Comment by kneth** [comment]
I'm a little uncertain what you mean by "get a full column". Can you explain it? In SQL, you often do a projection (only returning a few columns) as part of your `SELECT` statement. With Realm, you don't need that as we don't copy data from the database to memory. So, when you do `RealmResults<Foo> foos = realm.allObjects(Foo.class)`, you have access to all objects on the type `Foo`.

**Comment by kneth** [comment]
@teddywest32 In https://github.com/realm/realm-java/blob/master/examples/introExample/src/main/java/io/realm/examples/intro/IntroExampleActivity.java you can see a few different queries.

**Comment by teddywest32** [comment]
@kneth Thanks for the examples. I was searching for same items.  Is there some possibility for using Joins Features in realm? Thanks for it. You can update some more queries for further more details. Thanks again.

**Comment by kneth** [comment]
@teddywest32 Realm isn't a relational database so it's a "join free database". Instead, you link your classes together (see https://realm.io/docs/java/latest/#relationships), and simply follow the references. In that way, Realm is closer to object-oriented programming than other databases. You can even query these links/relationships (https://realm.io/docs/java/latest/#link-queries).
