### ISSUE TITLE
.db file from asset folder to Realm

### ISSUE THREAD

**Issue by josias1991** [realm/realm-java#1212]
Is there a way to convert a preloaded database from the assets folder (a .db file) to a Realm database?

**Comment by wrparrish** [comment]
I've often wondered the same thing.  Is there an accepted pattern  /  best practice for converting from an exsiting SQL Db  to Realm?

**Comment by cmelchior** [comment]
Hi @josias1991 
I assume you mean a SQLite database? In that case no, we have not written a guide for converting yet (although we should). However, if you convert each of your tables to a RealmClass and convert primary key/foreign key pairs to links you should be well on your way. In general ```1:1``` mappings should be modelled using a simple object reference and ```1:m``` should be modelled using RealmList.

**Comment by kneth** [comment]
@wrparrish I close the issue but feel free to open a new issue if you have further questions.

**Comment by OmkarAmberkar** [comment]
I have the same issue where I need to convert .db in my assets into realm database. Is there a proper way to do this?

**Comment by kneth** [comment]
@OmkarAmberkar I can only repeat @cmelchior's comment above. Converting a relational data model isn't trivial as it may sound. If you are a OS X user, https://github.com/realm/realm-cocoa-converter has a few utilities to help you (converting your `.db` file to a Realm file and put the Realm file in your asset).

**Comment by Zhuinden** [comment]
I think it makes sense for the user to create their own realm models and the mapping.

**Comment by kneth** [comment]
@Zhuinden I tend to agree but a brief guide could be useful for many.
