### ISSUE TITLE
Add JSON support for ISO8601

### ISSUE THREAD

**Issue by rafa0809** [realm/realm-java#1213]
Is there a way to Realm.createObjectFromJson() with date attributes in format ISO8601? This is the current code that decodes date from JSON for the Android Version:

```
public static Date stringToDate(String date) {
        if (date == null || date.length() == 0) return null;
        Matcher matcher = jsonDate.matcher(date);
        if (matcher.matches()) {
            return new Date(Long.parseLong(matcher.group(1)));
        } else {
            return new Date(Long.parseLong(date));
       }
}
```

An strategy consist of use regex with the ISO 8601 format and perform the conversion. Is it possible?

**Comment by cmelchior** [comment]
Hi @rafa0809 
Currently the inbuilt JSON methods doesn't support ISO8601. However, instead you can use GSON to configure a date formatter: http://stackoverflow.com/questions/6873020/gson-date-format and then copy the objects using ```Realm.copyToRealmOrUpdate(objects)```

**Comment by rafa0809** [comment]
Yes @cmelchior , I'm doing it! It was a request. ISO8601 is a very handled format. 

Thanks you :+1:

**Comment by heikomaass** [comment]
+1 :)

**Comment by renannery** [comment]
+1

**Comment by caroth92** [comment]
+1

**Comment by bassrock** [comment]
+1 For this, as I can't use GSON, because I need to ignore fields that do not have keys from the json as described in the documentation: 
```
JSON doesn’t have the field:
Leave the value unchanged for both required and not-required fields.
```
