### ISSUE TITLE
Failed to open . Permission denied. open() failed: Read-only file system

### ISSUE THREAD

**Issue by theCodingWizard** [realm/realm-java#1215]
When I try to migrate the database in android, it throws this error: Failed to open . Permission denied. open() failed: Read-only file system.

My code:
```java
Realm.migrateRealmAtPath("realm_db", new RealmMigration() {
    @Override
    public long execute(Realm realm, long version) {
       ...
       return version;
    }
});
```

**Comment by theCodingWizard** [comment]
Never mind. Instead of "realm_db", I changed it to `context.getFileStreamPath("database.realm").getPath()`

**Comment by cmelchior** [comment]
@theCodingWizard 
Yes, the path must be the complete path. This part of the API isn't documented that well, but it will soon change to be better.
