### ISSUE TITLE
RealmConfiguration missing on Android

### ISSUE THREAD

**Issue by iamMehedi** [realm/realm-java#1217]
I have just added realm to an Android project. I have tried using the jar and also using maven but either way the RealmConfiguration class seems to be missing and so is the method Realm.getDefaultInstance().

**Comment by cmelchior** [comment]
Hi @iamMehedi 
Neither has been properly released, so they are only still available as your SNAPSHOT release. You can see how to include that here: https://github.com/realm/realm-java#using-snapshots

**Comment by iamMehedi** [comment]
As those are not part of release, would it be a good idea to use them in a professional project? or should I use some workaround for the time being?

**Comment by cmelchior** [comment]
The features should be stable, and we plan to release them within the next week or so, so it should be safe to use them.

**Comment by iamMehedi** [comment]
Awesome! Thanks.
