### ISSUE TITLE
Proof-read JavaDoc

### ISSUE THREAD

**Issue by kneth** [realm/realm-java#1219]
The JavaDoc should benefit from a proof-reading.

There is an inconsistency in the methods' documentation. Some methods are documented in 3rd person singular (e.g., "Returns") while others are not (e.g. "Get"). But we might have others.

**Comment by morqon** [comment]
Something for the flight home :)

**Comment by Arrs** [comment]
Unless this is preventing builders or discouraging people from using Realm, please close or reassign. 
We're conserving alll marketing bandwith on activities that directly bring visitors or builders for now.

**Comment by cmelchior** [comment]
This is outside the scope of Realm-Java as such, will be tracked elsewhere if it is something we want to pursue.
