### ISSUE TITLE
Sum and Group a field by Date

### ISSUE THREAD

**Issue by ghiyatshanif** [realm/realm-java#1220]
Hi, Thanks for the awesome library you made, i've been using it on several projects of mine. i'm wondering if i can do something like http://stackoverflow.com/questions/937652/mysql-select-sum-group-by-date using Realm. if so how do I approach it? thanks in advance!

**Comment by beeender** [comment]
You can use RealmQuery's [between](https://realm.io/docs/java/latest/api/io/realm/RealmQuery.html#between-java.lang.String-java.util.Date-java.util.Date-) function to get results between a certain date range, and use [sumInt](https://realm.io/docs/java/latest/api/io/realm/RealmQuery.html#sumInt-java.lang.String-) to get the sum value.
eg.:
```java
long sum = testRealm.where(DataObject.class).between("date", startDateOfMonth, endDateOfMonth).sumInt("total");
```

And then create your own data structure to hold the results.

Is this good enough for you? Or you need a more convenient way to group the results like "GROUP BY" in sql?

**Comment by ghiyatshanif** [comment]
it will give me a result of summed value from the selected field between startDate and endDate, am i right?
actually i've approached it by doing this:
//get a list of Dates between startDate and endDate 

for (String date : dates){
            RealmResults<ResultModel> rm = realm.where(ResultModel.class).equalTo("date", date).findAll();
            if (rm != null) {
                sum = rm.sum("value").intValue();

                Log.d("summed value", date + " " + sum);
                results.add(new ResultModel(date, sum));
            }
            else {
                results.add(new ResultModel(date, 0));
                Log.d("summed value", date + " " + 0);
            }
        }

**Comment by beeender** [comment]
Yes, that's right. sumInt will caculate the summed value of the selected field based on your query, in this case, they are results fitting the given date range.

**Comment by ghiyatshanif** [comment]
well perhaps i can close this issue now, as i've figured out how to approached it, but hopefully Realm will provide this feature on its next release. anyway thanks beender!

**Comment by Pedramrn** [comment]
Hi, I really interested in "GROUP BY" like the sql, how to achieve that with realm?

**Comment by bmunkholm** [comment]
You still have to do that manually.

**Comment by engr-erum** [comment]
Hi groupBy available now ? or will i stiill handle it manually ?

**Comment by SumalathaBareddi** [comment]
Hi team, is there any update regarding groupBy?
