### ISSUE TITLE
Auto Compute Fields in Realm Models

### ISSUE THREAD

**Issue by stripathi669** [realm/realm-java#1221]
First let me begin by saying that this library is awesome. I am huge fan of this work.

I have a  model called Post, and each post has no. of votes, no. of comments and time of creation as fields. Now what I want to do is calculate 'popularity score' for each post that takes into account each of the above fields, sort results based on this score and set it on a realm list view adapter. As you can see, due to time decay nature of popularity score, that value needs to be updated once in a while (say 12hrs). 

I am wondering which one of below is optimal way of doing things:

1. Make a field called popularity, update it on a periodic basis (via a service).
2. Make a field called popularity, update it when app is launched in a runnable or Async Task.
3. Fetch a list of pk's from server, query those posts from realm db, and set to list view.

I am wondering what is most optimal way in terms of best practice, clarity and usage of realm.

I understand that this issue is neither a bug nor a feature request, hence would be grateful for any advice you can give.

**Comment by bmunkholm** [comment]
Hi,
Usage questions like this is properly better managed on StackOverflow where more people are able to help but even more importantly more people will see the response in the future. So if you don't mind copying this into SO, that would be great and we will have a go at it there.

Thanks!
