### ISSUE TITLE
Link queries

### ISSUE THREAD

**Issue by petersnoopy** [realm/realm-java#1222]
Hi,

i have question to example about link queries.  

    public class Contact extends RealmObject {
      private RealmList<Email> emails;
      // Other fields…
    }

      public class Email extends RealmObject {
        private String address;
        private boolean active;
        // ... setters and getters left out
      }

      RealmResults<Contact> contacts = realm.where(Contact.class).equalTo("emails.active", true).findAll();

"The query above should be read give me all contacts with at least one active email address." 

Is it possible to get only contacts with all email addresses activated?

**Comment by emanuelez** [comment]
This is not possible right now but it is in the pipeline already. You can follow the progress here: #841 
I will close this issue as a duplicate but please keep the feedback coming!! :)
