### ISSUE TITLE
error when trying to update un object

### ISSUE THREAD

**Issue by mahermeg17** [realm/realm-java#1225]
Hi,

I want to update an object that already saved, but it bugs and close the app

    Realm realm = Realm.getInstance(context);
		RealmResults<MyObject> result = realm
				.where(MyObject.class).equalTo("name", name).findAll();
		if (result.size() == 1) {
			result.get(0).setName("ABCD");
		}
		realm.commitTransaction();

here the error message
     FATAL EXCEPTION: main
 java.lang.IllegalStateException: Mutable method call during read transaction.
 	at io.realm.internal.Table.throwImmutable(Table.java:1639)
 	at io.realm.internal.Table.checkImmutable(Table.java:1245)
 	at io.realm.internal.Row.setString(Row.java:215)

**Comment by nhachicha** [comment]
Hi @mahermeg17 
any modifications should happen within a [transaction](https://realm.io/docs/java/latest/#writes)

you can refactor your code to open one

```java
Realm realm = Realm.getInstance(context);
    realm.beginTransaction();
    RealmResults<MyObject> result = realm
            .where(MyObject.class).equalTo("name", name).findAll();
    if (result.size() == 1) {
        result.get(0).setName("ABCD");
    }
    realm.commitTransaction();
```
or 
```java
    Realm realm = Realm.getInstance(context);
    RealmResults<MyObject> result = realm
            .where(MyObject.class).equalTo("name", name).findAll();
    if (result.size() == 1) {
        realm.executeTransaction(new Realm.Transaction() {
                      @Override
                      public void execute(Realm realm) {
                        result.get(0).setName("ABCD");
                      }
           });
    }
    realm.commitTransaction();
```

**Comment by mahermeg17** [comment]
thank you @nhachicha 
I miss this point!
