### ISSUE TITLE
Please provide a 0.81.0 build JAR

### ISSUE THREAD

**Issue by athalay** [realm/realm-java#1226]
Because it is impossible to build this project on Windows, and Realm-migration-related classes are not available in 0.80.3 :(

**Comment by cmelchior** [comment]
Hi @athalay 
I'm not sure exactly what you mean by Realm-Migration related classes, but the 0.81.0 build can be downloaded here: https://static.realm.io/downloads/java/realm-java-0.81.0.zip

**Comment by athalay** [comment]
RealmConfiguration class is not present in version 0.80.3 (officially downloadable on the website), so it's quite hard to implement migration scenarios.

Thanks for the package!

**Comment by kneth** [comment]
`RealmConfiguration` was introduced by version 0.81.0. You can open a Realm file saved by version 0.80.3 using version 0.81.0.

**Comment by athalay** [comment]
Exactly, this what I mentioned in my original post, thanks a lot for the replies! I see on the main page there's already a newer version!
