### ISSUE TITLE
Question: what happen if 2 transactions try to modify the same object?

### ISSUE THREAD

**Issue by dmytrodanylyk** [realm/realm-java#1231]
Let's say I have 2 transactions in different thread (`Thread1` and `Thread2) which are modifying the same object at the same time.

E.g.

```java
beginTransaction();
try {
    User user = realm.where(User.class)
                            .equalTo("id", user.getId())
                            .findFirst();
    if(user != null) {
        user.setName("Updated name");
    }
    transaction.execute(this);
    commitTransaction();
} catch (RuntimeException e) {
    cancelTransaction();
    throw new RealmException("Error during transaction.", e);
} catch (Error e) {
    cancelTransaction();
    throw e;
}
```

What will happen?
1. `Thread1` will update user, then `Thread2` update user. (Transactions are placed on queue and are executed one after another)
2. `Thread1` will update user, while `Thread2` will raise exception.

**Comment by cmelchior** [comment]
Hi @dmytrodanylyk 
You can't. Realm transactions are blocking so as soon as you call `beginTransaction()` all other threads will block if you call `beginTransaction()` on them.  So that would mean option 1.

**Comment by dmytrodanylyk** [comment]
@cmelchior thanks.
