### ISSUE TITLE
Using realm with groovy domain class

### ISSUE THREAD

**Issue by OlegDokuka** [realm/realm-java#1234]
Hi guys, today I have worked around my new project and found that realm compiler produce error like above

```
Error:Test must contain at least 1 persistable field
Error:error: Getter getMetaClass is not associated to any field
public  groovy.lang.MetaClass getMetaClass() { return (groovy.lang.MetaClass)null;}
```
and domain class (entity)

``` groovy
class Test extends RealmObject {
    @PrimaryKey
    long id

    String name

    String getName() {
        return name
    }

    void setName(String name) {
        this.name = name
    }

    Long getId() {
        return id
    }

    void setId(Long id) {
        this.id = id
    }
}
```

everything is looking good, but as I understand realm compiler find some field that called metaClass - this field provided by GroovyObject by default way.
Of course, I can create simple java domain class, and I will do that for the first time, but I think it would be cool to create some plugin for groovy language and make happy groovy users.

Thanks a lot for great realm!

**Comment by emanuelez** [comment]
You are correct, GroovyObject adds several methods which we don't support at the moment. We are working on bytecode manipulation techniques that will solve the problem radically, but in the mean time your only option is to use the java domain for model classes.
