### ISSUE TITLE
Between usage with link query relations

### ISSUE THREAD

**Issue by berkayturanci** [realm/realm-java#1237]
Hi there,

We are trying to use link query with relations. In our case, classes are looked like;

    public class Root extends RealmObject {
        @PrimaryKey
        private String uuid;
        private RealmList<Level> levels;
        // Getter, Setters
    }

    public class Level extends RealmObject {
        private int zoomLevel;
        private RealmList<Point> points;
        // Getter, Setters
    }

    public class Point extends RealmObject {
        private int X;
        private int Y;
        // Getter, Setters
    }

So our query is look like;

    int MinX = 17435;
    int MaxX = 18500;
    int MinY = 14000;
    int MaxY = 15000;
    int zoomLevel = 15;
    RealmQuery<Root> query = realm.where(Root.class).equalTo("levels.zoomLevel", zoomLevel).between("levels.points.X", MinX,MaxX).between("levels.points.Y", MinY, MaxY);

There are my root objects that contains levels which contains points. 
I try to find root objects which contains the zoomLevel level with in the range of min and max points.

The problem is that, altough equalTo works fine, between gives the root objects that are not in the range of given X's and Y's.

Such example is that Root that contains this object  " [Level] zoomLevel = 15, points = <{17000, 13000}>  ", is also returned from query.

Thanks for any help

**Comment by kneth** [comment]
Querying relations can be a bit confusion. The fact is that such a query will return the objects (`Root` in your case) where at least one of the linked objects fulfil the conditions. But the objects are still linked to all the child objects (`Level` and `Point` in your case). Reverse lookups could in your case be what you need. We have an open issue on that (see #607).

One way you can do your query is to query the individual relationships - something like:

    RealmResults<Root> roos = realm.where(Root.class). equalTo("levels.zoomLevel", zoomLevel).findAll();
    for (Root root : roots) {
        for (Level level : root.getLevel()) {
            RealmResults<Point> points = level.getPoint().where(Points.class)..between("levels.points.X", MinX,MaxX).between("levels.points.Y", MinY, MaxY).findAll();
            // do something with your points
        }
    }

**Comment by berkayturanci** [comment]
Hi @kneth, 

Thanks for reply. 

Its a little bit confusing, I am trying to make an `and` query, so isn't that all of the conditions should be satisfied? 

The thing is that, in my one of the Root object there are 4 levels, such as;

1 -  "[Level] zoomLevel = 15, points = <{17000, 13000}> "
2-   "[Level] zoomLevel = 16, points = <{19200, 19500}> "
3-   "[Level] zoomLevel = 17, points = <{22000, 25000}> "
4-   "[Level] zoomLevel = 18, points = <{27000, 30000}> "

So, according to my query only first object should be satisfied by only one condition which is zoomLevel condition, not with other conditions, `betweens`. But query returns that first object although it does not satisfies the all `and` conditions.

Do I miss anything? 

Thanks

**Comment by kneth** [comment]
I fully understand the confusion. 

Your query will return the `Root` objects that fulfil the condition. That means that if one of the linked objects fulfil the condition, the `Root`object does. The fields of the `Root` object are all there. The value of the linked object (`levels` in your case) is a list and has four elements. Some of these elements might not fulfil the condition but you should see it from the `Root` object's perspective.

**Comment by berkayturanci** [comment]
Hi @kneth,

Thanks again,

We done lots of experiments on this but we could not be able to understand the problem that we make.

Let me revisit my query again,

    RealmQuery<Root> query = realm.where(Root.class).equalTo("levels.zoomLevel", 15).between("levels.points.X", 17435,18500).between("levels.points.Y", 14000, 15000);

And my levels are;

1- "[Level] zoomLevel = 15, points = <{17000, 13000}> "
2- "[Level] zoomLevel = 16, points = <{19200, 19500}> "
3- "[Level] zoomLevel = 17, points = <{22000, 25000}> "
4- "[Level] zoomLevel = 18, points = <{27000, 30000}> "

I just have one Root object and 4 Levels (upper) in that Root object.

So according to my query zoomLevel (15) matches with the first level element ("[Level] zoomLevel = 15, points = <{17000, 13000}> "), but point list for that zoomLevel does not satisfies the between query (X:17000 is not between 17435, 18500 and Y:13000 is not between 14000, 15000). So in this query result should be 0 but it returns my root object as well (please see the example ).

I make a small application which follows;

```
public class Points extends RealmObject {

    private int X;
    private int Y;

    public int getX() {
        return X;
    }

    public void setX(int x) {
        X = x;
    }

    public int getY() {
        return Y;
    }

    public void setY(int y) {
        Y = y;
    }
}

public class Levels extends RealmObject{

    private int zoomLevel;
    private RealmList<Points> points;

    public int getZoomLevel() {
        return zoomLevel;
    }

    public void setZoomLevel(int zoomLevel) {
        this.zoomLevel = zoomLevel;
    }

    public RealmList<Points> getPoints() {
        return points;
    }

    public void setPoints(RealmList<Points> points) {
        this.points = points;
    }
}

public class Root extends RealmObject {

    @PrimaryKey
    private String uuid;
    private RealmList<Levels> levels;

    public String getUuid() {
        return uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    public RealmList<Levels> getLevels() {
        return levels;
    }

    public void setLevels(RealmList<Levels> levels) {
        this.levels = levels;
    }
}

public class MainActivity extends ActionBarActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        init();

        query();
    }

    public void init()
    {
        Realm realm = Realm.getInstance(this);
        realm.beginTransaction();

        Points points1 = realm.createObject(Points.class);
        points1.setX(17000);
        points1.setY(13000);
        realm.copyToRealm(points1);

        Points points2 = realm.createObject(Points.class);
        points2.setX(19200);
        points2.setY(19500);
        realm.copyToRealm(points2);

        Points points3 = realm.createObject(Points.class);
        points3.setX(22000);
        points3.setY(25000);
        realm.copyToRealm(points3);

        Points points4 = realm.createObject(Points.class);
        points4.setX(27000);
        points4.setY(30000);
        realm.copyToRealm(points4);

        Levels levels1 = realm.createObject(Levels.class);
        levels1.setZoomLevel(15);
        levels1.getPoints().add(points1);
        realm.copyToRealm(levels1);

        Levels levels2 = realm.createObject(Levels.class);
        levels2.setZoomLevel(16);
        levels2.getPoints().add(points2);
        realm.copyToRealm(levels2);

        Levels levels3 = realm.createObject(Levels.class);
        levels3.setZoomLevel(17);
        levels3.getPoints().add(points3);
        realm.copyToRealm(levels3);

        Levels levels4 = realm.createObject(Levels.class);
        levels4.setZoomLevel(18);
        levels4.getPoints().add(points4);
        realm.copyToRealm(levels4);

        Root root = new Root();
        root.setUuid("1");
        root.setLevels(new RealmList<Levels>());
        root.getLevels().add(levels1);
        root.getLevels().add(levels2);
        root.getLevels().add(levels3);
        root.getLevels().add(levels4);
        realm.copyToRealmOrUpdate(root);

        realm.commitTransaction();
        realm.close();

    }

    public void query()
    {
        int MinX = 17435;
        int MaxX = 18500;
        int MinY = 14000;
        int MaxY = 15000;
        int zoomLevel = 15;
        Realm realm = Realm.getInstance(this);
        RealmResults<Root> results = realm.where(Root.class).equalTo("levels.zoomLevel", zoomLevel).between("levels.points.X", MinX, MaxX).between("levels.points.Y", MinY, MaxY).findAll();

/// There are one root element here where there should be zero
        Log.v("asd","asd");
    }
}

```

The confusing thing is that when we just set our min and max values to small values (nothing changes with root object and childs) it does not return any object too (case if just zoomLevel is enough for query).

```
  public void query()
    {
        int MinX = 0;
        int MaxX = 1;
        int MinY = 10;
        int MaxY = 20;
        int zoomLevel = 15;
        Realm realm = Realm.getInstance(this);
        RealmResults<Root> results = realm.where(Root.class).equalTo("levels.zoomLevel", zoomLevel).between("levels.points.X", MinX, MaxX).between("levels.points.Y", MinY, MaxY).findAll();

/// results is null as expected !
        Log.v("asd","asd");
    }

```

Thanks

**Comment by kneth** [comment]
I get the same results as you describe. It looks like a bug, and I will investigate.

**Comment by kneth** [comment]
After consultation with the Realm Core team, it is not regarded as a bug. You query has five subqueries (the two `between` conditions are rewritten internally as `>=` and `<=`). Each subquery is independent, and your single `Root` object will fulfil all five individually, and thereby the `RealmResults` will contain it.

In order to do what you ask for, you will have to do something like the code snippet below.

        RealmResults<Root> roots = testRealm.allObjects(Root.class);
        for (Root myroot : roots) {
            RealmResults<Levels> levels = myroot.getLevels().where().equalTo("zoomLevel", zoomLevel).findAll();
            for (Levels level : levels) {
                RealmResults<Points> pointses = level.getPoints().where().between("X", MinX, MaxX).between("Y", MinY, MaxY).findAll();
                // process the points founds
            }
        }

**Comment by berkayturanci** [comment]
Again, thanks for your attention.

I agree all you said. However, in the above examples, Root object cannot fulfill the all subqueries.

In first example non of the between queries are satisfied, only level is satisfied but Root object returns.(Unexpected result).

In the second example again non of the between queries are satisfied, only level is satisfied but non of the Root object returns (Expected result).

So, is there a logical mistake to combining different link queries (Combining queries with child objects conditions)? 

By the way, we need Root objects as a result in our query, thats why we cannot use what you suggested.

**Comment by berkayturanci** [comment]
After a lots of testing again; The problem occurs when we have more than one Level child, The simplest error occurs when;

```

public class Root extends RealmObject {

    @PrimaryKey
    private String uuid;
    private RealmList<Levels> levels;

    public String getUuid() {
        return uuid;
    }

    public void setUuid(String uuid) {
        this.uuid = uuid;
    }

    public RealmList<Levels> getLevels() {
        return levels;
    }

    public void setLevels(RealmList<Levels> levels) {
        this.levels = levels;
    }
}

public class Levels extends RealmObject {

    private RealmList<Points> points;


    public RealmList<Points> getPoints() {
        return points;
    }

    public void setPoints(RealmList<Points> points) {
        this.points = points;
    }
}

public class Points extends RealmObject {

    private int X;

    public int getX() {
        return X;
    }

    public void setX(int x) {
        X = x;
    }
}

public class MainActivity extends ActionBarActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        init();

        query();
    }

    public void init()
    {
        Realm realm = Realm.getInstance(this);
        realm.beginTransaction();

        Points points1 = realm.createObject(Points.class);
        points1.setX(10);
        realm.copyToRealm(points1);

        Points points2 = realm.createObject(Points.class);
        points2.setX(20000);
        realm.copyToRealm(points2);

        Levels levels1 = realm.createObject(Levels.class);
        levels1.getPoints().add(points1);
        realm.copyToRealm(levels1);

        Levels levels2 = realm.createObject(Levels.class);
        levels2.getPoints().add(points2);
        realm.copyToRealm(levels2);


        Root root = new Root();
        root.setUuid("1");
        root.setLevels(new RealmList<Levels>());
        root.getLevels().add(levels1);
        root.getLevels().add(levels2);
        realm.copyToRealmOrUpdate(root);

        realm.commitTransaction();
        realm.close();

    }

    public void query()
    {
        int MinX = 10000;
        int MaxX = 10500;
        Realm realm = Realm.getInstance(this);
        RealmResults<Root> results = realm.where(Root.class).between("levels.points.X", MinX, MaxX).findAll();

/// There are one root element here where there should be zero
        Log.v("asd", "asd");
    }
}

```

So one Level's X is 10 and other one is 20000, there are not between 10000 and 10500, but query returns a Root object anyway.

This looks like an obvious error to me.

**Comment by kneth** [comment]
The reason for the unexpected number of objects is due to our documentation isn't clear enough. I have attached a drawing to explain it (yeah, I know, I'm not an artist).

![scan2](https://cloud.githubusercontent.com/assets/1225363/8456651/182b44dc-200d-11e5-9b90-86266a7db229.jpg)

The same `Root` object fulfil the condition given by the two subqueries in the example. And since the combined query is an intersection of the two subqueries, you will end up with one object and not zero objects.

This is how link queries are designed at the moment. We are aware that many things are hard to expressed elegantly, and we will visit the design of the query engine in the future to make it more expressive.

**Comment by berkayturanci** [comment]
![untitled](https://cloud.githubusercontent.com/assets/4395053/8458113/df8e2462-201d-11e5-8eeb-5b29fd3af20e.png)

Thanks again your all support. I don't want to be a boring people. But upper case stil returns Root object.

This is the drawing of my last example. There is simple one between query for X. 

Code query : ` realm.where(Root.class).between("levels.points.X", 10000, 10500).findAll(); `

But it returns my Root object where as you can see there is no X point that should satisfy the query. 

First Level:
![image](https://cloud.githubusercontent.com/assets/4395053/8458254/c4e84d6c-201e-11e5-8a6a-8fdaebb7ef12.png)

Second Level:
![image](https://cloud.githubusercontent.com/assets/4395053/8458261/d0adbbd2-201e-11e5-847a-9c31811c8b34.png)

I Don't Have Any More Levels:
![image](https://cloud.githubusercontent.com/assets/4395053/8458266/db1fcc5e-201e-11e5-85df-acfc535b6246.png)

**Comment by kneth** [comment]
Thanks for a much better drawing. `between(field, min, max)` is for link queries implemented as `greaterThanOrEqual(field, min).lessThanOrEqual(field, max)`. In order words, we have two conditions.

In your example, the first condition is true for `x = 10`, and second condition is true for `x = 20000`. This is not what you expect (and I fully understand that).

**Comment by berkayturanci** [comment]
Hi again,

For `x = 10` ;

```
greaterThanOrEqual part -> false;
lessThanOrEqual part -> true;
```

shouldn't be `(false).(true) == false `  so  `greaterThanOrEqual(10, 10000).lessThanOrEqual(10, 10500) == false` in your case? `.` is represented as an `and` condition in your documents.

Anyway is there a way to get what I need then? 

Thanks

**Comment by kneth** [comment]
I have updated the [documentation](https://realm.io/docs/java/latest/#relationships) as I can see that link queries were not explained well. The link queries should be seen as existential [quantifier](https://en.wikipedia.org/wiki/Quantifier_(logic).

As I outlined earlier, I think you will have to iterate through the objects.

**Comment by berkayturanci** [comment]
Thanks for your all support.
