### ISSUE TITLE
What is the best way to synchronising realms between several android devices through p2p?

### ISSUE THREAD

**Issue by gpulido** [realm/realm-java#1238]
I'm developing an app that would share data between several devices and users, think about multiplayer gaming or a collaborative todo list.
I'm thinking on using the wifi p2p api (http://developer.android.com/training/connect-devices-wirelessly/wifi-direct.html), and once I have the "peers" connected, use a socket or a rest service to "move" realmobject (probably using json ).
My realmObjects all have a "uuid" as index, and I could add a "last changed" date field to check for the latest changes and comparations. But this would be cumbersome and error prone (basically I would need to implement an entire synchronization system between two copies of the same realm), so I wonder if there is a better approach for the problem.
Any suggestions, ideas or libraries that could help me on this task?
Thank you

**Comment by bmunkholm** [comment]
Hi @gpulido,
I guess this is more of a general problem than a specific Realm related question. Therefore I think it would be most valuable for you (and for the community at large) if you would post this on StackOverflow. That way you would get many more people suggesting solutions - including us :-)

Thanks!
