### ISSUE TITLE
Data Base crashe.

### ISSUE THREAD

**Issue by AntonLunegovPerm** [realm/realm-java#1244]
Hello! Please, help me. I have a specific problem. My app broke with this error: 

"E/dalvikvm﹕ Failed adding to JNI pinned array ref table (1024 entries). "

I have many appeal to db, because i'm writing my plane's track in db and geting db objects at once. Can the problem be in this part?
Code example: 

realmDB = Realm.getInstance(getApplicationContext());
try{
              realmDB.beginTransaction();
              MapflyTrack mapflyTrack = realmDB.createObject(MapflyTrack.class);
  }catch (Exception e){
                Log.e("Realm Error ", +e);
} finally {
             realmDB.commitTransaction();
}
...
realmDB.where(MapflyTrack.class).equalTo("_flightNumber", _flightNumber).findAll().get(realmDB.where(MapflyTrack.class).equalTo("_flightNumber", _flightNumber).findAll().size() - 1).getMapflyLat()
realmDB.where(MapflyTrack.class).equalTo("_flightNumber", _flightNumber).findAll().get(realmDB.where(MapflyTrack.class).equalTo("_flightNumber", _flightNumber).findAll().size() - 1).getMapflyLong();

Thus, more than 60 iterations

**Comment by kneth** [comment]
@AntonLunegovPerm It sounds like a memory leak in the C++ code of Realm. We will have to investigate it.

Two - unrelated to the error you see - observations: It would be a good idea to add a `realmDB.cancelTransaction()` to the `catch` block. And you don't need to do `get(realmDB.where(MapflyTrack.class).equalTo("_flightNumber", _flightNumber).findAll().size() - 1`. Instead the `last()` method can be used.

**Comment by AntonLunegovPerm** [comment]
Thank you! I tried old version) When i have included 0.81 version, the app works)

**Comment by kneth** [comment]
We fixed a bug in version 0.73.0 (November 2014). Did you use that old version?

**Comment by AntonLunegovPerm** [comment]
I was using 0.72.

**Comment by kneth** [comment]
I will close the issue as we have fixed the bug in 0.73.0.
