### ISSUE TITLE
NPE in close() in Realm.java:243 on 0.81.1

### ISSUE THREAD

**Issue by ahmedre** [realm/realm-java#1247]
hi,
i haven't been able to repro this myself, but i am getting many reports in Crashlytics about this on various 4.x and 5.x devices (Samsung and others).

the code at that line looks to be:

```java
            AtomicInteger counter = globalOpenInstanceCounter.get(canonicalPath);
            if (counter.decrementAndGet() == 0) {
                globalOpenInstanceCounter.remove(canonicalPath);
            }
```

here's an example stack trace:

```
java.lang.RuntimeException: An error occured while executing doInBackground()
       at android.os.AsyncTask$3.done(AsyncTask.java:300)
       at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
       at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
       at java.util.concurrent.FutureTask.run(FutureTask.java:242)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'int java.util.concurrent.atomic.AtomicInteger.decrementAndGet()' on a null object reference
       at io.realm.Realm.close(SourceFile:243)
       at com.ayah.util.Utils.closeSilently(SourceFile:11)
       at com.ayah.task.PageVersesTask.doInBackground$3a73acfa(SourceFile:37)
       at com.ayah.task.PageVersesTask.doInBackground(SourceFile:14)
       at android.os.AsyncTask$2.call(AsyncTask.java:288)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)
```

the code using this is doing nothing fancy - `PageVersesTask` is an `AsyncTask` that does a simple `Realm` query and then closes the database:

```java
  @Override
  protected PageDAO doInBackground(Void... params) {
    Realm realm = null;
    PageDAO result;
    try {
      realm = RealmUtils.getDatabase(mContext);
      final Page page = realm.where(Page.class)
          .equalTo("index", mPage - 1)
          .findFirst();
      result = PageDAO.from(page);
    } finally {
      Utils.closeSilently(realm);
    }
    return result;
  }
```

`closeSilently` in this case just takes a `Closeable`, checks for null, and if not null, then closes while catching `IOException`.

note that this same stacktrace happens in some of the other places i use a similar pattern for accessing data from an `AsyncTask`.

thanks!

**Comment by ahmedre** [comment]
sorry, duplicate of #1241.

**Comment by beeender** [comment]
Can you please share source code of  `RealmUtils.getDatabase(mContext)` and `Utils.closeSilently(realm)`? 
I guess PageDAO is not not a subclass of RealmObject and it has nothing to do with Realm, right?

Thanks!

**Comment by ahmedre** [comment]
sure - `PageDAO` is a pojo and i basically "copy" the data from the realm object into this pojo so i can pass it across threads (since the `RealmObject` (`Page` in this case) cannot be passed across threads). i used `try`/`finally` in case an exception is thrown somewhere (`RealmUtils.getDatabase`, or the realm query), that i ensure that i close the realm instance.

```
  public static void closeSilently(Closeable closeable) {
    if (closeable != null) {
      try {
        closeable.close();
      } catch (IOException ioe) {
        // fail silently
      }
    }
  }
````

RealmUtils.java
```java
  private static final String REALM_DB_NAME = "ayah.realm";

  private static final Object sLock = new Object();
  private static volatile boolean sIsInitialized;

  public static Realm getDatabase(Context context) {
    if (!sIsInitialized) {
      synchronized (sLock) {
        final File path = new File(context.getFilesDir(), REALM_DB_NAME);
        if (path.exists()) {
          sIsInitialized = true;
        } else {
          final InputStream inputStream =
              context.getResources().openRawResource(R.raw.ayahrealm);
          if (copyDatabase(inputStream, path)) {
            sIsInitialized = true;
          }
        }
      }
    }

    return Realm.getInstance(
        new RealmConfiguration.Builder(context)
            .name(REALM_DB_NAME)
            .schemaVersion(1)
            .build());
  }
```

**Comment by beeender** [comment]
Is it possible to share your project with us privately? To help@realm.io :smile: 
Although it is not reproducible, it still helps.

**Comment by ahmedre** [comment]
Unfortunately I can't :(

The common factor between all these crashes is that they happen in an AsyncTask or an AsyncTaskLoader.

I'll look at the Crashlytics logs and see if there is anything useful I can tell you (ex if it's just happening on a certain set of devices, os versions, etc). 

I personally never saw it, but crashes are frequent enough that it's a real problem.

**Comment by ahmedre** [comment]
Most are Samsung, most on 4.x (all throughout), some on 5.x. Happens also on the previous version of realm, but happens more on the newer version. Most of these devices with crashes are not rooted.

**Comment by beeender** [comment]
#1245 has been merged, would you please help to verify if it can fix your problem?
If it doens't, feel free to reopen this issue.
Thanks!

**Comment by ahmedre** [comment]
sounds good, i'll push a new version friday and let you know if i still run into crashes. thanks!

**Comment by ahmedre** [comment]
looks good to me after ~1 week in prod using snapshot - thanks!
