### ISSUE TITLE
mremap() on wrapped fd not supported

### ISSUE THREAD

**Issue by osayilgan** [realm/realm-java#1249]
Hi,

I'm using Realm.io in my Android App and we are currently supporting some of the MDM Providers. Lately, I came across this issue in MobileIron wrapped version of our Android Application. They do not support mremap().

I didn't try the Other MDM Providers yet, but this might be an issue for others as well.

is there any solution or suggestion on that ? Am I going go to end up replacing Realm with another database ?

Thanks.

**Comment by kneth** [comment]
I don't know MobileIron's products, so I can't give you a definite answer. If `mmap()`, `munmap()`, and `mremap()` are disabled, Realm will not work. #1163 is a similar issue using another MDM provider, and the user was able to get it to work. The trick was to disable encryption (then `mmap()` worked) and use Realm's encryption instead.

**Comment by osayilgan** [comment]
I've contacted to MobileIron team referring this ticket to see if disabling encryption could be an option for them. I will update the ticket once I have any news.

**Comment by osayilgan** [comment]
No solution for now until they support  `mremap()`. I will probably fork the project and create the ORMLite version for the MDMs only.

But if that would be possible to disable `mremap()` in Realm, even though it will decrease the performance, it can be a faster solution for my case.

**Comment by kneth** [comment]
Realm uses `mremap()` and its siblings heavily, and it not easy to disable it. If MobileIron cannot give you access to memory mapping, I suggest you use a MDM provider that does. As indicated in #1163, XenMobile might be a better solution for you.

**Comment by tgoyne** [comment]
If it's getting to a `mremap()` call then that means that `mmap()` worked. As long as it's property reporting `ENOTSUP` I think falling back to the non-`mremap()` codepath when it returns would be fairly straightforward.

**Comment by osayilgan** [comment]
@kneth Thanks for the details. We are supporting majority of MDM providers, so MobileIron is not the only one. I will fork my project and make ORMLite ,or another one, version just for those MDM providers which does not support memory mapping, but I will keep main release with Realm. That would probably be the fastest solution for my case.

@tgoyne According to their report, `mmap()` and `munmap()` are not supported as well but they may support `mremap()` later on.
