### ISSUE TITLE
java.lang.IllegalArgumentException: Realm on disc is newer than the one specified: v9 vs. v0

### ISSUE THREAD

**Issue by hanhailong** [realm/realm-java#1259]
java.lang.IllegalArgumentException: Realm on disc is newer than the one specified: v9 vs. v0
07-01 11:09:57.638    7654-7654/com.jikexueyuan.geekacademy.debug W/System.err﹕ at io.realm.Realm.createAndValidate(Realm.java:609)
07-01 11:09:57.638    7654-7654/com.jikexueyuan.geekacademy.debug W/System.err﹕ at io.realm.Realm.create(Realm.java:549)
07-01 11:09:57.638    7654-7654/com.jikexueyuan.geekacademy.debug W/System.err﹕ at io.realm.Realm.getInstance(Realm.java:396)
07-01 11:09:57.638    7654-7654/com.jikexueyuan.geekacademy.debug W/System.err﹕ at io.realm.Realm.getInstance(Realm.java:353)
07-01 11:09:57.638    7654-7654/com.jikexueyuan.geekacademy.debug W/System.err﹕ at io.realm.Realm.getInstance(Realm.java:334)
07-01 11:09:57.638    7654-7654/com.jikexueyuan.geekacademy.debug W/System.err﹕ at com.jikexueyuan.geekacademy.controller.command.persist.PersistUserInfoCommand.execute(PersistUserInfoCommand.java:36)
07-01 11:09:57.638    7654-7654/com.jikexueyuan.geekacademy.debug W/System.err﹕ at com.jikexueyuan.geekacademy.controller.core.GreekController.execute(GreekController.java:80)
07-01 11:09:57.638    7654-7654/com.jikexueyuan.geekacademy.debug W/System.err﹕ at com.jikexueyuan.geekacademy.model.core.ModelFacade.initUserInfo(ModelFacade.java:111)
07-01 11:09:57.638    7654-7654/com.jikexueyuan.geekacademy.debug W/System.err﹕ at com.jikexueyuan.geekacademy.model.core.ModelFacade.initModelFacade(ModelFacade.java:67)
07-01 11:09:57.638    7654-7654/com.jikexueyuan.geekacademy.debug W/System.err﹕ at com.jikexueyuan.geekacademy.model.core.ModelFacade.attachContext(ModelFacade.java:61)
07-01 11:09:57.638    7654-7654/com.jikexueyuan.geekacademy.debug W/System.err﹕ at com.jikexueyuan.geekacademy.GreekApplication.onCreate(GreekApplication.java:54)
07-01 11:09:57.642    7654-7654/com.jikexueyuan.geekacademy.debug W/System.err﹕ at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
07-01 11:09:57.642    7654-7654/com.jikexueyuan.geekacademy.debug W/System.err﹕ at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4344)
07-01 11:09:57.642    7654-7654/com.jikexueyuan.geekacademy.debug W/System.err﹕ at android.app.ActivityThread.access$1500(ActivityThread.java:135)
07-01 11:09:57.642    7654-7654/com.jikexueyuan.geekacademy.debug W/System.err﹕ at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)
07-01 11:09:57.642    7654-7654/com.jikexueyuan.geekacademy.debug W/System.err﹕ at android.os.Handler.dispatchMessage(Handler.java:102)
07-01 11:09:57.642    7654-7654/com.jikexueyuan.geekacademy.debug W/System.err﹕ at android.os.Looper.loop(Looper.java:136)
07-01 11:09:57.642    7654-7654/com.jikexueyuan.geekacademy.debug W/System.err﹕ at android.app.ActivityThread.main(ActivityThread.java:5017)
07-01 11:09:57.642    7654-7654/com.jikexueyuan.geekacademy.debug W/System.err﹕ at java.lang.reflect.Method.invokeNative(Native Method)
07-01 11:09:57.642    7654-7654/com.jikexueyuan.geekacademy.debug W/System.err﹕ at java.lang.reflect.Method.invoke(Method.java:515)
07-01 11:09:57.642    7654-7654/com.jikexueyuan.geekacademy.debug W/System.err﹕ at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
07-01 11:09:57.642    7654-7654/com.jikexueyuan.geekacademy.debug W/System.err﹕ at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
07-01 11:09:57.642    7654-7654/com.jikexueyuan.geekacademy.debug W/System.err﹕ at dalvik.system.NativeStart.main(Native Method)

When I put the realm to upgrade to the latest version from the old version to upgrade the app to the error，zhe latest version is 0.81.1

**Comment by cmelchior** [comment]
Hi @hanhailong 
This is happening because the Realm file in the app you are trying to access already has been migrated a few times.

You can solve this by making by adding ```schemaVersion``` to your RealmConfiguration like so:

```
RealmConfiguration config = new RealmConfiguration.Builder(context)
  .schemaVersion(9)
  .build();
```

**Comment by beeender** [comment]
@ hanhailong I am closing this issue now.
[stackoverflow  with realm tag](http://stackoverflow.com/questions/tagged/realm)  would be a better place for questions. Feel free to report issues here.

Thanks for your feedback!
