### ISSUE TITLE
Crashed after adding encryption key

### ISSUE THREAD

**Issue by KynoYang** [realm/realm-java#1267]
Hi, because of some reason I need to add the encryption key. However, it will cause a crash exception. 

Is there a formal way to deal with situation? 

```
E/AndroidRuntime(13423): java.lang.IllegalArgumentException: Illegal Argument: Invalid format of Realm file.
E/AndroidRuntime(13423):        at io.realm.internal.SharedGroup.createNativeWithImplicitTransactions(Native Method)
E/AndroidRuntime(13423):        at io.realm.internal.SharedGroup.<init>(SharedGroup.java:60)
E/AndroidRuntime(13423):        at io.realm.Realm.<init>(Realm.java:207)
E/AndroidRuntime(13423):        at io.realm.Realm.createAndValidate(Realm.java:586)
E/AndroidRuntime(13423):        at io.realm.Realm.create(Realm.java:549)
E/AndroidRuntime(13423):        at io.realm.Realm.getInstance(Realm.java:522)
```

**Comment by emanuelez** [comment]
If I understand correctly you are converting a non-encrypted Realm to an encrypted one.
To do this you need to copy the Ream file adding the new encryption key to it. This is done with the [`Realm.writeEncryptedCopyTo()`](https://realm.io/docs/java/latest/api/io/realm/Realm.html#writeEncryptedCopyTo-java.io.File-byte:A-) method.

Does this answer your question?

**Comment by KynoYang** [comment]
@emanuelez Yes. thank you very much !
