### ISSUE TITLE
Check if a relationship has any objects

### ISSUE THREAD

**Issue by koesie10** [realm/realm-java#1270]
I have basically got the following objects:
```
public class A extends RealmObject {
    private RealmList<B> items;
}

public class B extends RealmObject {
}
```

I now want to check whether `A` has any associated objects. Is there a way to check if the count of `items` is larger than `0`, i.e. if `A` has any related objects?

**Comment by beeender** [comment]
Try this [`RealmQuery.isNotNull`](https://realm.io/docs/java/latest/api/io/realm/RealmQuery.html#isNotNull-java.lang.String-)

```
RealmResults<A> results = realm.where(A.class).isNotNull("items").findAll();
```

**Comment by koesie10** [comment]
Thanks, that works!
