### ISSUE TITLE
More than one unique field

### ISSUE THREAD

**Issue by h777arsh** [realm/realm-java#1271]
Hello,
First thanx for the awesome library. 
My question is How we can define more than one unique field in realm?

**Comment by beeender** [comment]
Hi!
Unfortunately unique filed is only supported for the primary key right now.
May I ask what is your use case for this? What do you expect if the unique field (non-primary-key) is changed to a duplicated value? Throw an exception and cancel the transaction?

**Comment by h777arsh** [comment]
Thanx for the quick reply.
I think you should give options when duplicate records found likes you want to replace or cancel the transaction or even throw an exception.

**Comment by beeender** [comment]
#967 We have an issue to track this already. And it is in our plan. For easier bug tracking, I am duplicating this issue to #967 now. If you have any more thoughts/suggestions on this topic, feel free to comment there.

Thanks a lot for you feedback!

**Comment by h777arsh** [comment]
ok thanks.

**Comment by dtmandroid** [comment]
I want to make field 'itemName' of Table Item to be unique in Android Realm. It means 'itemName' should not contain duplicate values. Is there any other way to achieve this except Primary key.. Thanks..
