### ISSUE TITLE
Retrofit-Gson-Realm deserialize and insert  with input stream(or something similar)

### ISSUE THREAD

**Issue by aercanozcan** [realm/realm-java#1274]
Hello, 

I am working with some huge data like >300k rows of data.
Is there a way to insert those data without holding it in a collection, for example: inserting as soon an item is serialized.

To be clear :
Retrofit returns any object I declare as result and uses my Deserializer(Gson) like RealmList<Data>. but my response is too large for memory and I am not using them at all at same time. 

is there  a way to insert each RealmList item without adding to a collection?

**Comment by beeender** [comment]
Hello!

It seems your problem is about handling huge data with GSON.
Maybe this GSON Streaming API could help with your case? https://sites.google.com/site/gson/streaming
An example from that link:
```
public List<Message> readJsonStream(InputStream in) throws IOException {
    JsonReader reader = new JsonReader(new InputStreamReader(in, "UTF-8"));
    List<Message> messages = new ArrayList<Message>();
    reader.beginArray();
    while (reader.hasNext()) {
        Message message = gson.fromJson(reader, Message.class);
        messages.add(message);
        //May be you can write the Realm here?
    }
    reader.endArray();
    reader.close();
    return messages;
}
```

**Comment by aercanozcan** [comment]
Thank you for your response. I guess I asked the question to wrong repository. It looks like this is up to deserialization part. And also your example is accurate. cheers.

**Comment by beeender** [comment]
Happy to see it helps!
I am closing this issue now. Thanks a lot for your feedback!
