### ISSUE TITLE
RealmSet ?

### ISSUE THREAD

**Issue by nicolasgoutaland** [realm/realm-java#1275]
Hi there,

I just integrate your lib in my project, and it seems great, but I have one question, why did you choose to implement relationships as List instead of Set ?
Using a Set when needed could help to suppress a lot of boilerplate code.
Are you planning to add something like a RealmSet ? Are you eventually opened to a PR for this ?

Regards

**Comment by kneth** [comment]
We have talked about maps and sets. Said that, we haven't prioritised it, and not even added an issue for it. I can't put a date on when or if we will do something like RealmSet.

**Comment by cmelchior** [comment]
This is already covered by https://github.com/realm/realm-java/issues/759, so closing this as a duplicate.
