### ISSUE TITLE
java: Type java.util.List<java.lang.String> of field course_key is not supported

### ISSUE THREAD

**Issue by mjliu** [realm/realm-java#1279]
@RealmClass
public class CourseModel extends RealmObject implements Serializable {

    @PrimaryKey
    private int id;
    private int category_id;
    private List<String> course_key;
.......get，sets........
}
 
how to deal with this problem.

**Comment by emanuelez** [comment]
You should use `RealmList` instead of `List`.

**Comment by mjliu** [comment]
thank you for your answer @emanuelez .  RealmList<E extends RealmObject> , but String does not extend RealmObject.

**Comment by beeender** [comment]
You can create a RealmObject which has only a String field
```
class StringObject extends RealmObject {
    @PrimaryKey
    private String string;
    //...getter & setter
}
```

**Comment by beeender** [comment]
Hi @mjliu , I am closing this issue now. 
stackovlerflow.com would be a better place for questions.
Thanks a lot for your feedback!
