### ISSUE TITLE
IN operator similar to NSPredicate's "fieldName IN %@"

### ISSUE THREAD

**Issue by virl** [realm/realm-java#1280]
Greetings.
I need to retrieve objects from realm whose field doesn't have any of the values presented in code-supplied List.

In Realm for iOS I do that like this: `[SLLocation objectsInRealm:realm where:@"date > %@ AND NOT (signalId IN %@)", fromDate, signalIds]`

How to do that in Realm for Java?

**Comment by kneth** [comment]
Yes, an `IN` like operator in queries can be useful. It is fairly simple workaround:

    RealmQuery<SLLocation> query = realm.where(SLLocation.class);
    for (int id : signalIds) {
        query = query.equalsTo("signalId", id);
    }

Your request is similar to #841.

**Comment by virl** [comment]
Thanks.

**Comment by virl** [comment]
Thanks. Will it work when signalIds array is pretty large (2-3 thousands of items)?

**Comment by kneth** [comment]
Yes, it should work (we have a unit test with 1024 conditions).

**Comment by virl** [comment]
Thanks.

**Comment by tgoyne** [comment]
The IN operator in iOS currently just does the same thing of looping over the array and building up a chained OR/equalsTo, so you should see identical performance.
