### ISSUE TITLE
Is it possible to sort RealmResults?

### ISSUE THREAD

**Issue by schermannj** [realm/realm-java#1286]
I have dao method which returns RealmResults<MyModel> and I want to **sort** this list by some Date field. 
I know about realm ability to get sorted result, but for me it doesn't work, beacause I'm getting next exceptions:
`IllegalArgumentException: Field name "myModel.someNestedModel.field" does not exists`
or
`Sorting using child object properties is not supported: someNestedModel.field`

How I understand It's because I want to get ordered result using field from nested model e.g.
```
MyModel {
     SomeNestedModel model
}

SomeNestedModel {
     Date field
}
```
Now I try to sort this result via `Collections.sort(result, new MyComparator())` but I'm getting next exception:
`io.realm.exceptions.RealmException: Replacing elements not supported.`

Thanks!

**Comment by kneth** [comment]
Realm doesn't support sorting by link. There is an open issue (#672) for that.

**Comment by emanuelez** [comment]
Closing this one since #672 is covering it already
