### ISSUE TITLE
how to use RealmList<RealmInt>

### ISSUE THREAD

**Issue by mjliu** [realm/realm-java#1288]
@beeender 
when I use RealmList<RealmInt> , I find this error.
java.lang.IllegalArgumentException
            at com.google.gson.internal.$Gson$Preconditions.checkArgument($Gson$Preconditions.java:42)
            at com.google.gson.GsonBuilder.registerTypeAdapter(GsonBuilder.java:499)
            at com.google.gson.GsonBuilder.registerTypeAdapter(GsonBuilder.java:495)
            at com.kaikeba.u.student.model.MyDemoModel.example(MyDemoModel.java:74)
            at com.kaikeba.u.student.model.MyDemoModel.access$000(MyDemoModel.java:29)
            at com.kaikeba.u.student.model.MyDemoModel$1$1.run(MyDemoModel.java:47)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5014)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:806)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:622)
            at dalvik.system.NativeStart.main(Native Method)

my code is here.
final String jsonStr = "[{\"name\": \"jack18\",\"age\": \"26\",\"realmints\" : [1, 2, 3]},{\"name\": \"jack16\",\"age\": \"12\"},\"realmints\" : [1, 2]]";

                    Type token = new TypeToken<RealmList<RealmInt>>(){}.getType();
                    Gson gson = new GsonBuilder()
                            .setExclusionStrategies(new ExclusionStrategy() {
                                @Override
                                public boolean shouldSkipField(FieldAttributes f) {
                                    return f.getDeclaringClass().equals(RealmObject.class);
                                }

                                @Override
                                public boolean shouldSkipClass(Class<?> clazz) {
                                    return false;
                                }
                            })
                            .registerTypeAdapter(token, new TypeAdapter<RealmList<RealmInt>>() {

                                @Override
                                public void write(JsonWriter out, RealmList<RealmInt> value) throws IOException {
                                    // Ignore
                                }

                                @Override
                                public RealmList<RealmInt> read(JsonReader in) throws IOException {
                                    RealmList<RealmInt> list = new RealmList<RealmInt>();
                                    in.beginArray();
                                    while (in.hasNext()) {
                                        list.add(new RealmInt(in.nextInt()));
                                    }
                                    in.endArray();
                                    return list;
                                }

                            })
                            .create();

// Convert JSON to objects as normal
                    List<Person> objects = gson.fromJson(jsonStr, new TypeToken<List<Person>>(){}.getType());

                    realm.beginTransaction();
//                    realm.createOrUpdateAllFromJson(Person.class,arr);
                    realm.copyToRealmOrUpdate(objects);
                    realm.commitTransaction();

data is here 
@RealmClass
public class Person extends RealmObject implements Serializable{

    @PrimaryKey
    private String name;
    private String age;
//    private RealmList<Animal> animals;
    private RealmList<RealmInt> realmints;

//    public RealmList<Animal> getAnimals() {
//        return animals;
//    }
//
//    public void setAnimals(RealmList<Animal> animals) {
//        this.animals = animals;
//    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAge() {
        return age;
    }

    public void setAge(String age) {
        this.age = age;
    }

    public RealmList<RealmInt> getRealmints() {
        return realmints;
    }

    public void setRealmints(RealmList<RealmInt> realmints) {
        this.realmints = realmints;
    }
}

@RealmClass
public class RealmInt extends RealmObject implements Serializable {
    private int var;

    public RealmInt(){

    }

    public RealmInt(int i) {
        this.var = i;
    }

    public int getVar() {
        return var;
    }

    public void setVar(int var) {
        this.var = var;
    }

}

**Comment by mjliu** [comment]
@beeender 有时间帮忙看一下

**Comment by beeender** [comment]
This is quite difficult to read. Which line is the `at com.kaikeba.u.student.model.MyDemoModel.example(MyDemoModel.java:74)` ?

**Comment by beeender** [comment]
Hi, the GSON version (2.0) you are using is a bit old (4 years ago :P), it works with the latest GSON (tried with 2.3.1).

Thanks for the feedback!
