### ISSUE TITLE
ArrayIndexOutOfBounds Exception on Android

### ISSUE THREAD

**Issue by vijaemanlapaz** [realm/realm-java#1289]
im trying to delete all rows for a certain table.

        realm.beginTransaction();
        RealmQuery<?> transctionQuery = realm.where(clazz);
        RealmResults<?> transactionResults = transctionQuery.findAll();

        int size = transactionResults.size();
        for(int x = 0; x < size; x++) {
            RealmObject realmObject = transactionResults.get(x); // ArrayIndexOutOfBound happens here.
            Log.e(TAG, "Deleting " + x + " of " + size);
            realmObject.removeFromRealm();
        }
        realm.commitTransaction();

My logs returns
                   E/AndroidRuntime﹕ FATAL EXCEPTION: main java.lang.ArrayIndexOutOfBoundsException: rowIndex > available rows: 155 > 155
it only gets 155 row but the total rows for my table before i delete it is 350 why is that?.

**Comment by emanuelez** [comment]
1) To delete all rows from a table you should use the `clear` method. It's going to be way faster.

2) You can try iterating backwards and reading through this issue to see why: https://github.com/realm/realm-java/issues/789

I hope this helps!

**Comment by vijaemanlapaz** [comment]
Thanks @emanuelez it worked i used the clear method
