### ISSUE TITLE
Terrible GC sweeps while getting RealmList relation

### ISSUE THREAD

**Issue by fuwaneko** [realm/realm-java#1291]
So I have these two models.
```Java
// simplified models
public class User extends RealmObject {
  // stuff, including related models, RealmLists, etc. WITH circular relations to itself
}

public class Dialog extends RealmObject {
  private RealmList<User> participants;
  // other stuff w/o circular relations, getters, setters
}
```

I fetch dialogs from server via retrofit, put objects into Realm in background thread and listen to changes. In my Adapter I bind Dialog to RecyclerView item (ViewHolder) and fetch participants (actually, I use participants.where() to filter, but it also happens if I just iterate over them using standart Java constructs). On that step I see UI freezing and this in console:
```
07-13 19:44:44.085  23312-23312/tk.tewi.kitoss I/REALM﹕ Dataset changed for adapter DialogListAdapter
07-13 19:44:44.147  23312-23312/tk.tewi.kitoss W/﹕ Unable to open '/system/framework/qcom.fmradio.jar': No such file or directory
07-13 19:44:44.148  23312-23312/tk.tewi.kitoss W/art﹕ Failed to open zip archive '/system/framework/qcom.fmradio.jar': I/O Error
07-13 19:44:45.368  23312-23327/tk.tewi.kitoss I/art﹕ Background partial concurrent mark sweep GC freed 77206(3MB) AllocSpace objects, 3(6MB) LOS objects, 23% free, 52MB/68MB, paused 2.061ms total 139.784ms
07-13 19:44:46.399  23312-23327/tk.tewi.kitoss I/art﹕ Background sticky concurrent mark sweep GC freed 136944(4MB) AllocSpace objects, 2(3MB) LOS objects, 6% free, 64MB/68MB, paused 902us total 127.253ms
07-13 19:44:46.812  23312-23327/tk.tewi.kitoss I/art﹕ Background partial concurrent mark sweep GC freed 63624(2MB) AllocSpace objects, 0(0B) LOS objects, 18% free, 68MB/84MB, paused 1.693ms total 197.238ms
07-13 19:44:47.814  23312-23327/tk.tewi.kitoss I/art﹕ Background sticky concurrent mark sweep GC freed 142294(5MB) AllocSpace objects, 0(0B) LOS objects, 5% free, 79MB/84MB, paused 2.679ms total 102.751ms
07-13 19:44:47.917  23312-23312/tk.tewi.kitoss W/﹕ Unable to open '/system/framework/qcom.fmradio.jar': No such file or directory
07-13 19:44:47.917  23312-23312/tk.tewi.kitoss W/art﹕ Failed to open zip archive '/system/framework/qcom.fmradio.jar': I/O Error
07-13 19:44:47.954  23312-23312/tk.tewi.kitoss I/Choreographer﹕ Skipped 230 frames!  The application may be doing too much work on its main thread.
```

Please, advise.

Realm: 0.81.1
Device: Xperia Z1 with 5.0.2
IDE: IntelliJ IDEA 14.1.4
Compile SDK version: 22
Target version: 22
Min version: 16

**Comment by emanuelez** [comment]
Interesting. How many objects are you iterating through?

**Comment by fuwaneko** [comment]
Participants is actually only two items long.
13 июля 2015 г. 20:05 пользователь "Emanuele Zattin" <
notifications@github.com> написал:

**Comment by emanuelez** [comment]
That sounds weird. I would expect such a behavior while iterating through thousands of results, creating many short-lived realm objects. Are you able to share your code or produce a sample project to reproduce the issue?

**Comment by fuwaneko** [comment]
Yeah, I'll post sample project soon.
13 июля 2015 г. 20:14 пользователь "Emanuele Zattin" <
notifications@github.com> написал:

**Comment by emanuelez** [comment]
Perfect! Thanks!

On Mon, Jul 13, 2015 at 2:45 PM, Dmitry Gorbunov <notifications@github.com>
wrote:

> Yeah, I'll post sample project soon.
> 13 июля 2015 г. 20:14 пользователь "Emanuele Zattin" <
> notifications@github.com> написал:
>
> > That sounds weird. I would expect such a behavior while iterating through
> > thousands of results, creating many short-lived realm objects. Are you
> able
> > to share your code or produce a sample project to reproduce the issue?
> >
> > —
> > Reply to this email directly or view it on GitHub
> > <https://github.com/realm/realm-java/issues/1291#issuecomment-120906270
> >.
>
> >
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/realm/realm-java/issues/1291#issuecomment-120916714>.
>



-- 
*Emanuele Zattin* (@emanuelez <https://twitter.com/emanuelez>)
SW Engineer & CI Specialist

**Comment by fuwaneko** [comment]
@emanuelez after some time spent digging it and running emulator with very limited RAM (instead of 2G on actual device) I managed to produce OutOfMemory exception with good stacktrace and it turned out that Realm.io was not the culprit. Problem was with joda-time library (precisely, DateTimeZone routines). After replacing generic version with android-specific one I see no more GC sweeps. Sorry, my fault.
