### ISSUE TITLE
Migration script when changing model name

### ISSUE THREAD

**Issue by Ralphilius** [realm/realm-java#1293]
Hello,

In the migration examples, I can see that we have "add new table", "add new column" and "adjust a column", but there's no example to demonstrate if we want to change the model name.

What would be appropriate way to achieve this?

Thank you very much,

**Comment by kneth** [comment]
The migration API isn't well-documented, and it is likely to change (to the better) in the near future. Please take a look at #1265, #1253, and #1239.

When you open a Realm in an app, a model class are created in the Realm file if it doesn't exist. You don't have to do anything. If you rename a class, a new representation of the class is created automatically. But the objects are not copied, and you will have to add a migration step for that. If the model class `Person` is renamed to `Employee`, the step could be:

    Table person = realm.getTable(Person.class);
    Table employee = realm.getTable(Employee.class);
    for (int i = 0; i < person.size(); i++) {
        employee.addEmptyRow();
        employee.setString(0, i, person.getString(0, i)); // if the first field is a string
        // copy all fields
    }

**Comment by Ralphilius** [comment]
Thanks @kneth,

So I need to copy all the fields from old table to the new table, right?

**Comment by kneth** [comment]
Yes, you have to copy the data. In Realm's underlying storage engine, model classes are represented as `io.realm.internal.Table`. If you wish to use the object interface, the migration step could be:

    for (Person person : realm.allObjects(Person.class)) {
        Employee employee = new Employee();
        employee.setName(person.getName()); // and all the other fields
        realm.copyToRealm(employee);
    }

After copying, you should remove all the old objects using `realm.clear(Person.class)` so they don't take up space.

**Comment by cmelchior** [comment]
@Ralphilius I assume the above answered your question, so closing this for now.

Note that the new Migration API will have an explicit method for renaming classes, which will be a lot more performant than copying the data around. https://github.com/realm/realm-java/pull/1239

**Comment by spectrumIG** [comment]
Actually, I just want to point out that that code wouldn't had worked at all. If you rename a class, and try to access the old named one, the compiler will obviously complains making the app impossible to build and install. I'm saying that because I'm forced now to update my old version of realm just because I renamed a class.

**Comment by Zhuinden** [comment]
@spectrumIG although the Table-based migration was outdated since 0.86.0, but yes, considering class names determine the Realm model, the only way in my opinion to fix this via public Api would have been `deleteIfMigrationNeeded`.
