### ISSUE TITLE
java.lang.IllegalArgumentException:  c is not part of the schema for this Realm (ProGuard enabled)

### ISSUE THREAD

**Issue by Ralphilius** [realm/realm-java#1294]
Hello,

I got this issue while using Proguard with following configuration:

```
-keep @io.realm.annotations.RealmModule class *
-dontwarn javax.**
-dontwarn io.realm.**
```

Error message:
```
java.lang.IllegalArgumentException: c is not part of the schema for this Realm
       at io.realm.internal.modules.CompositeMediator.getMediator(CompositeMediator.java:118)
       at io.realm.internal.modules.CompositeMediator.getTableName(CompositeMediator.java:71)
       at io.realm.Realm.getTable(Realm.java:312)
       at io.realm.RealmQuery.(RealmQuery.java:75)
       at io.realm.Realm.where(Realm.java:1198)
....
```

 - I am using Realm version: 0.81.1
 - The model is extends RealmObject and has @RealmClass annotation 
 - When ProGuard is disabled, the application worked fine

**Comment by beeender** [comment]
Hi!
Try this in your proguard configuration.

**-keep class io.realm.annotations.RealmModule**
-keep @io.realm.annotations.RealmModule class *
-dontwarn javax.**
-dontwarn io.realm.**

**Comment by beeender** [comment]
Same problem with #1283 . @Ralphilius Do you mind we close this one and use #1283 to track?

**Comment by Ralphilius** [comment]
Thanks @beeender 
It's working. You can close this and reference to #1283 for easy tracking.

Cheers,
