### ISSUE TITLE
why i am "valid":false when extends myclass with RealmObject and parsed with objectmapper

### ISSUE THREAD

**Issue by vazeer** [realm/realm-java#1296]

**Comment by emanuelez** [comment]
Can you please elaborate your question? We would love to help but it does not describe the issue with enough detail. Some code sample would help as well if possible.

**Comment by cmelchior** [comment]
Closing due to no response. @vazeer Please see for https://github.com/realm/realm-java/blob/master/CONTRIBUTING.md#filing-issues for filling issues with the information we need to help you.
