### ISSUE TITLE
Realm proguard issue with @RealmModule

### ISSUE THREAD

**Issue by vvictor10** [realm/realm-java#1301]
I have a project with a single RealmModule annotated with @RealmModule. Build goes thru fine, however during run time, I get this following error:

Caused by: java.lang.IllegalArgumentException: java.lang.Class is not a RealmModule. Add @RealmModule to the class definition.
            at io.realm.RealmConfiguration$Builder.checkModule(RealmConfiguration.java:397)
            at io.realm.RealmConfiguration$Builder.addModule(RealmConfiguration.java:360)
            at io.realm.RealmConfiguration$Builder.setModules(RealmConfiguration.java:348)

Has anyone seen this?

I have the following in my proguard config file.

# keep realm classes
-keepnames public class * extends io.realm.RealmObject
-keepattributes *Annotation*
-keep @io.realm.annotations.RealmModule class *
-dontwarn javax.**
-dontwarn io.realm.**

Thanks in advance. This issue is driving me nuts. I am getting this same error on another project and am almost 100% sure that this is something to do with proguard, which seems to remove the annotation from the class.

**Comment by beeender** [comment]
[Doc for proguard](https://realm.io/docs/java/latest/#proguard) updated 
Try this to see if it helps:
```
-keep class io.realm.annotations.RealmModule
-keep @io.realm.annotations.RealmModule class *
-dontwarn javax.**
-dontwarn io.realm.**
```

BTW, Does it run fine without proguard?

**Comment by vvictor10** [comment]
I am a little confused now. The debug build works fine. However, the release build fails at runtime. I disabled proguard(minifyEnabled false) and ran the clean build and deployed again. No change, same message. This is my module class.

package com.customername.android.database.realm.module;

@io.realm.annotations.RealmModule(allClasses = true)
public class ExampleRealmModule {
}

And my prog config has the following:

# keep realm classes
-keepnames public class * extends io.realm.RealmObject
-keep @io.realm.annotations.RealmModule class *
-keepattributes *Annotation*
-dontwarn javax.**
-dontwarn io.realm.**

-keep class io.realm.annotations.RealmModule

**Comment by beeender** [comment]
Can you compare the build output directory for release and debug? Take a look on the difference between java files there, those are generated by Realm.  

And from the log:
`Caused by: java.lang.IllegalArgumentException: java.lang.Class is not a RealmModule.`
It seems your ExampleRealmModule is optimized out by something.
Are you using android studio?

**Comment by vvictor10** [comment]
yep, studio is what i use.

On Thu, Jul 16, 2015 at 10:23 PM, Chen Mulong <notifications@github.com>
wrote:

> Can you compare the build output directory for release and debug? Take a
> look on the difference between java files there, those are generated by
> Realm.
>
> And from the log:
> Caused by: java.lang.IllegalArgumentException: java.lang.Class is not a
> RealmModule.
> It seems your ExampleRealmModule is optimized out by something.
> Are you using android studio?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/realm/realm-java/issues/1301#issuecomment-122158724>.
>



-- 

Thanks & Regards,

Vicson.


*P* Think Green- please do not print this email unless necessary.

**Comment by vvictor10** [comment]
@cmelchior @bmunkholm I have a situation where I have a lib gradle module where I have all my RealmObject classes and the RealmModule defined as well. And there are 3 app gradle modules which depend on this lib module. So when creating the RealmModule in the lib module, do I need to declare that it is a library and prevent the DefaultRealmModule creation?

**Comment by vvictor10** [comment]
To throw some more light on my setup. have a 'lib' module which has the realm objects and module declared and the RealmConfiguration is also setup there. I use Dagger to wire up stuff. I have another module which is a slim bootstrapping module on top of Realm. That is where I have my base factory which produces realm instances. I have an abstract method to set the modules on the configuration. And that method is implemented by a class which extends this base factory. This class resides in the 'lib' module. And then I have the app modules, which depend on the lib module. I am unable to get this setup working. I have not set the library =true on the realm module declared in the the lib module as I do want the default module to be generated.

**Comment by cmelchior** [comment]
@vvictor10 
Why do you need the default module?

Doing the below in the library projects will automatically pick up any RealmObject classes in your library and would function as your "default" module (you would still have to set it manually though).
```
@RealmModule(library = true, allClasses = true) 
public class DefaultLibraryModule {
}
```

**Comment by vvictor10** [comment]
If I dont do that, I get this error.

     Caused by: java.lang.IllegalArgumentException: java.lang.Class is not a RealmModule. Add @RealmModule to the class definition.
            at io.realm.RealmConfiguration$Builder.checkModule(RealmConfiguration.java:397)
            at io.realm.RealmConfiguration$Builder.addModule(RealmConfiguration.java:360)
            at io.realm.RealmConfiguration$Builder.setModules(RealmConfiguration.java:348)

lib module contains the *Module class

@io.realm.annotations.RealmModule(allClasses = true)
public class IkinoRealmModule {
}

lib also contains the IkinoRealmInstanceFactory class(which extends a factory class(which lives in another common realm module, which is application agnostic) which has the meat of things), which sets the module. 

    @Override
    public void setRealmModules(RealmConfiguration.Builder builder) {
        builder.setModules(Realm.getDefaultModule());
    }

**Comment by beeender** [comment]
@vvictor10 Have you solved your issue? Is it possible to share your project with us? Or a simple project which can reproduce this issue would be good enough. to help@realm.io .

Thanks!

**Comment by ralphgabrielle** [comment]
was this solved ?

**Comment by Zhuinden** [comment]
I've never seen this since. We used Realm with RealmModule and it worked. Although we did have some proguard rules for it just in case.

**Comment by ralphgabrielle** [comment]
For some reason, I save more than 2000 data to realm and its working on debug flavor, but in release, it only give me 1 data.

**Comment by Zhuinden** [comment]
If you reuse your Realm Models as JSON responses, then you probably don't have @SerializedName annotation. Meaning all your data is parsed wrong. And primary key for your single object is `null`

**Comment by ralphgabrielle** [comment]
No, its actually working on debug mode with same code, release mode just
have  minifyEnabled true

**Comment by Zhuinden** [comment]
@ralphgabrielle yes that is exactly the case I am talking about in case you are parsing JSON with GSON but without @SerializedName

**Comment by kongsonida** [comment]
I got the same problem when I enabled progaurd 

com.xbx.debug.dao.realm.MySchemaModule is not a RealmModule. Add @RealmModule to the class definition.

Any one solved this problem?

Thanks,

**Comment by frANTicBee666** [comment]
@kongsonida 
seems that problem solved here:
https://github.com/realm/realm-java/issues/1301#issuecomment-466480217

**Comment by mayurik18** [comment]
I solved it by adding below Realm rules for proguard

-keep @interface io.realm.annotations.RealmModule { *; }
-keep class io.realm.annotations.RealmModule { *; }
-keep class io.realm.annotations.RealmModule
-keep @io.realm.annotations.RealmModule class *
-keep class io.realm.internal.Keep
-keep @io.realm.internal.Keep class *
-dontwarn javax.**
-dontwarn io.realm.**

# Additionally you need to keep your Realm Model classes as well
# For example:
# -keep class com.yourcompany.realm.** { *; }

**Comment by mayurik18** [comment]
I solved it by adding below Realm rules in proguard

-keep @interface io.realm.annotations.RealmModule { *; }
-keep class io.realm.annotations.RealmModule { *; }
-keep class io.realm.annotations.RealmModule
-keep @io.realm.annotations.RealmModule class *
-keep class io.realm.internal.Keep
-keep @io.realm.internal.Keep class *
-dontwarn javax.**
-dontwarn io.realm.**

# Additionally you need to keep your Realm Model classes as well
# For example:
# -keep class com.yourcompany.realm.** { *; }

**Comment by PGMacDesign** [comment]
The comment above did not work for me as it was missing a line and the semi-colons require an asterisk before them. Here is what I have set in my Proguard file and it is working with Minification set to true:

```
-keep @interface io.realm.annotations.RealmModule { *; }
-keep class io.realm.annotations.RealmModule { *; }
-keep class io.realm.annotations.RealmModule
-keep @io.realm.annotations.RealmModule class *
-keep class io.realm.internal.Keep
-keep @io.realm.internal.Keep class *
-dontwarn javax.
-dontwarn io.realm.**
-keepnames public class * extends io.realm.RealmObject
-keep class * extends io.realm.RealmObject
```

**Comment by Zhuinden** [comment]
(That explains why suddenly the text in that comment turned italic)

**Comment by Kolyall** [comment]
This works:
```
-keep class io.realm.annotations.RealmModule { *; }
-keep @interface io.realm.annotations.RealmModule { *; }
-keep @io.realm.annotations.RealmModule class *
-keep class io.realm.internal.Keep
-keep @io.realm.internal.Keep class *
-dontwarn javax.**
-dontwarn io.realm.**

-keepnames public class * extends io.realm.RealmObject
-keep class * extends io.realm.RealmObject
```
