### ISSUE TITLE
crash while processing large data

### ISSUE THREAD

**Issue by xingxp** [realm/realm-java#1307]
about 30000 lines of data
07-21 09:16:46.862      185-185/? I/DEBUG﹕ *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
07-21 09:16:46.862      185-185/? I/DEBUG﹕ Build fingerprint: 'google/hammerhead/hammerhead:5.1.1/LMY48B/1863243:user/release-keys'
07-21 09:16:46.862      185-185/? I/DEBUG﹕ Revision: '11'
07-21 09:16:46.862      185-185/? I/DEBUG﹕ ABI: 'arm'
07-21 09:16:46.862      185-185/? I/DEBUG﹕ pid: 18707, tid: 19188, name: pool-4-thread-4  >>> com.zbiti.yuntu <<<
07-21 09:16:46.863      185-185/? I/DEBUG﹕ signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
07-21 09:16:46.883      185-185/? I/DEBUG﹕ r0 00000000  r1 00004af4  r2 00000006  r3 00000000
07-21 09:16:46.883      185-185/? I/DEBUG﹕ r4 9e68fdb8  r5 00000006  r6 0000000b  r7 0000010c
07-21 09:16:46.883      185-185/? I/DEBUG﹕ r8 000000a6  r9 b48473c4  sl b48473cc  fp 75adf420
07-21 09:16:46.883      185-185/? I/DEBUG﹕ ip 00004af4  sp 9e68f5e0  lr b6db53c5  pc b6dd8c78  cpsr 600f0010
07-21 09:16:46.884      185-185/? I/DEBUG﹕ backtrace:
07-21 09:16:46.884      185-185/? I/DEBUG﹕ #00 pc 0003ac78  /system/lib/libc.so (tgkill+12)
07-21 09:16:46.884      185-185/? I/DEBUG﹕ #01 pc 000173c1  /system/lib/libc.so (pthread_kill+52)
07-21 09:16:46.884      185-185/? I/DEBUG﹕ #02 pc 00017fd3  /system/lib/libc.so (raise+10)
07-21 09:16:46.884      185-185/? I/DEBUG﹕ #03 pc 00014795  /system/lib/libc.so (__libc_android_abort+36)
07-21 09:16:46.884      185-185/? I/DEBUG﹕ #04 pc 00012f44  /system/lib/libc.so (abort+4)
07-21 09:16:46.884      185-185/? I/DEBUG﹕ #05 pc 00042e01  /data/app/com.zbiti.yuntu-2/lib/arm/librealm-jni.so
07-21 09:16:46.884      185-185/? I/DEBUG﹕ #06 pc 0004373f  /data/app/com.zbiti.yuntu-2/lib/arm/librealm-jni.so
07-21 09:16:46.884      185-185/? I/DEBUG﹕ #07 pc 00051b19  /data/app/com.zbiti.yuntu-2/lib/arm/librealm-jni.so
07-21 09:16:46.884      185-185/? I/DEBUG﹕ #08 pc 0006f7e9  /data/app/com.zbiti.yuntu-2/lib/arm/librealm-jni.so

**Comment by beeender** [comment]
@xingxp Could you please give us more details about this crash?
1. Does it happen to all devices? Which Realm version are you using?
2. When this problem happen, what is the Android version of the device?
3. Are you using WebView in your app? If yes, What is the WebView version?
4. Does it happen to the encrypted Realm only?
5. Would it be the same problem with #1008 ？ 
6. If it is not related with #1008, would you please share your project privately with us to help@realm.io or give us a sample project which can reproduce this error?

Thanks!

**Comment by xingxp** [comment]
hi beeender
my problem not occurs every time.
i am using Nexus 5 with realm latest version:0.81.1
i am not using webview or crosswalk as well,so not the same with #1008
and the data file is not encrypted.

**Comment by beeender** [comment]
@xingxp Can you please paste more information from logcat here? Some minutes before the crash and some minutes after. I suspect this would be the same problem with #1311

**Comment by beeender** [comment]
@xingxp We merged a PR #1313 which should fix this problem. If you can help to verify you case with that PR, it would be really appreciated!

Thanks!

**Comment by xingxp** [comment]
thanks, i tried , the problem solved now!
