### ISSUE TITLE
Nested realm list shrinks by 1 element.

### ISSUE THREAD

**Issue by alekseichuk** [realm/realm-java#1310]
When you have nested RealmList and trying to get it's item returned number of items less than expected by 1 item.

I suppose the issue is valid for managed lists and comes from LinkView implementation. In my case generated proxy object has method which fails to return all items.

```
@Override
    public RealmList<ProductSubOption> getSuboptions() {
        return new RealmList<ProductSubOption>(ProductSubOption.class, row.getLinkList(INDEX_SUBOPTIONS), realm);
    }
```

Issue pretty much described here: https://gist.github.com/alekseichuk/36d5ac0c34d3e315a0ca

**Comment by emanuelez** [comment]
I did a quick test and I can't seem to be able to reproduce the error. Are you able to provide a sample project showing the issue?

**Comment by alekseichuk** [comment]
Hi @emanuelez thanks for quick response. So here sample project https://drive.google.com/open?id=0B5qAhSiAwsNBdjJsUEpBSjB0dmM. See my TODOs. Cheers!

**Comment by emanuelez** [comment]
I asked for the permission to download the file

**Comment by alekseichuk** [comment]
Sorry, check it now.

**Comment by emanuelez** [comment]
It looks like the way you populate your Realm is a bit off.
I cleaned it up a bit like this:

```java
    private void fillRealm() {
        Realm realm = Realm.getInstance(this);
        realm.beginTransaction();

        realm.clear(ProductSubOption.class);
        realm.clear(ProductOption.class);
        realm.clear(Product.class);

        for (int i = 0; i < 2; i++) {
            Product p = new Product();
            p.setId(i);
            p.setName("Product " + i);
            p.setOptions(new RealmList<ProductOption>());

            //Adding three [0,1,2] options to each product
            for (int j = 0; j < 3; j++) {
                ProductOption po = new ProductOption();
                po.setId(j);
                po.setUniqueId("option_" + i + "." + j);
                po.setTitle("Option " + i + "." + j);
                po.setProduct(p);
                po.setSuboptions(new RealmList<ProductSubOption>());
                p.getOptions().add(po);

                //Adding four [0,1,2,3] sub-options to each options
                for (int k = 0; k < 4; k++) {
                    ProductSubOption pso = new ProductSubOption();
                    pso.setId(k);
                    pso.setUniqueId("suboption_" + i + "." + j + "." + k);
                    pso.setName("Suboption " + i + "." + j + "." + k);
                    pso.setOption(po);
                    po.getSuboptions().add(pso);
                }
            }

            realm.copyToRealm(p);
        }
        realm.commitTransaction();
    }
```

Now it's working as expected if I understand your specifications correctly.
It's a bit late in the night here so I cannot investigate what went wrong in your data population, but there were many unnecessary calls to `copyToRealmOrUpdate()` creating a hybrid object, partly managed by Realm and partly only living in memory.

If you want me to investigate further just let me know and I'll take a look tomorrow morning.

**Comment by alekseichuk** [comment]
Hi @emanuelez, yep seems your approach works as expected. I misconcluded that each object has to be added to Realm manually but seems even without this action it handles dependencies quite well. Cheers!

P.S. Offtopic: But please take a look into issue with overriding toString(), hashCode(), equals() 'cos it annoying.

**Comment by emanuelez** [comment]
We are working on that very actively :)
