### ISSUE TITLE
Link queries

### ISSUE THREAD

**Issue by yaming116** [realm/realm-java#1317]
Hello, given the following structure:
```java
class Parent extends RealmObject {
  int key;  
  String name;
  String address;

  ...
}
class Child extends RealmObject{
   int key;
   int parentKey;
   String name;
   String examTime;
   int score;
  
  ...
}
```
I already have a Parent data, I'll get a lot of information Child exam. Now I need to query a group associated with the Parent Child of information, how can I do

**Comment by beeender** [comment]
Hi, I don't really get your question. You want to query on Child with given score and also return its parent, right?

**Comment by yaming116** [comment]
yes, I will get to the Parent data before Child, but I need to show a group of Child data

**Comment by beeender** [comment]
The parent can contain a Child or a list of Child, like:
```
class Parent extends RealmObject {
    private int key;  
    private String name;
    private String address;
    private Child child;
    private RealmList<Child> children;
    //...
}
```
See [doc](https://realm.io/docs/java/latest/#relationships) and [Chinese version](https://realm.io/cn/docs/java/latest/#section-23) if you like :smile:

**Comment by beeender** [comment]
Hi, I am closing this issue now. If you have further problems with this, feel free to reopen it.
Thanks for your feedback!
