### ISSUE TITLE
RealmMigrationNeededException error

### ISSUE THREAD

**Issue by chonamdoo** [realm/realm-java#1318]
i want add another RealmObject class file 
public class Migration implements RealmMigration{
    @Override
    public long execute(Realm realm, long version) {
      
        return version;
    }
}

how  Add the above custom realmobject class file  to the table

**Comment by beeender** [comment]
Hello!
Please take a look at this simple file https://github.com/realm/realm-java/blob/master/examples/migrationExample/src/main/java/io/realm/examples/realmmigrationexample/model/Migration.java

**Comment by fuwaneko** [comment]
@beeender He asks how to add new table in migration. I believe there's nothing to do in that case, just increase version.

**Comment by beeender** [comment]
@fuwaneko Ha, OK. Then simply call:
```
Table table = realm.getTable(YouModel.class);
```
This will create a new Table or return the existing one.

**Comment by beeender** [comment]
Hi, I am closing this issue now. If you have further problems with this, feel free to reopen it.
Thanks for your feedback!
