### ISSUE TITLE
Can i hava a database file on sdcard ?

### ISSUE THREAD

**Issue by Yellup** [realm/realm-java#1320]
seems I don't find any API to change the path of the database file or Realm do not support sdcard database?  A little answer will help me so much.

**Comment by beeender** [comment]
Hi,

First, to use Realm on the SD card,
You can create a RealmConfiguration with a path to the SD card. See [`RealmConfiguration.Builder()`](https://realm.io/docs/java/latest/api/io/realm/RealmConfiguration.Builder.html#Builder-java.io.File-)

Then you have some choices to copy the Realm db file.
1. Use [`Realm.writeCopyTo()`](https://realm.io/docs/java/latest/api/io/realm/Realm.html#writeCopyTo-java.io.File-)
2. Get the Realm db file path by [`Realm.getPath()`](https://realm.io/docs/java/latest/api/io/realm/Realm.html#getPath--) then close the realm and copy it to the path you want by normal File APIs.

**Comment by Yellup** [comment]
Thank you for your reply so fast, the API Hidden so deep that i totally didn't see that..
