### ISSUE TITLE
Error: method does not override or implement a method from a supertype

### ISSUE THREAD

**Issue by dominicthomas** [realm/realm-java#1321]
I am trying to use realm in my project alongside RetroFit and GSON and have been working through converting my GSON object into a RealmObject. When compiling failed initially, along with other unsupported types, I was informed that realm doesn't support Integer types. I have replaced the other types and have changed the Integer field to a primitive int type in my model. 

The compiler now fails with the /...../EntryRealmProxy.java
Error:(448, 5) error: method does not override or implement a method from a supertype

Here is simplified version of my model just showing the field that seems to be break the build...
``` java
public class Entry extends RealmObject {
	@SerializedName("rating_count")
	@Expose
	private int ratingCount;
	public int getRatingCount() {
		return ratingCount;
	}
	public void setRatingCount(Integer ratingCount) {
		this.ratingCount = ratingCount;
	}
} 
```

the line that is failing the realm proxy file is...
``` java
    @Override <<<<<<<<< failing
    public void setRatingCount(int value) {
        realm.checkIfValid();
        row.setLong(INDEX_RATINGCOUNT, (long) value);
    }
```

Is there something I am doing wrong or a workaround available for Integer types?

**Comment by emanuelez** [comment]
Your setter need to accept `int` as well as opposed to `Integer`.
We are adding support for boxed types in these weeks so all this will soon become more natural.

**Comment by dominicthomas** [comment]
Thanks. Missed that one when replacing unsupported types; good to hear support for boxed types is on the way.
