### ISSUE TITLE
the @Ignore annotation not keep value in parent RealmObject  after#1313 merge

### ISSUE THREAD

**Issue by xingxp** [realm/realm-java#1322]
here is my model:
public class RMUser extends RealmObject {
    private long                  id;
    private String                name;
    @Ignore
    private boolean fav = false;
    
    ...getter and setter
}

public class RMDepartmentUser extends RealmObject{
    private long id;
    private RMUser user;

    ...getter and setter
}

and in the main code:
RMDepartmentUser user = Realm.getInstance(this).where(RMDepartmentUser.class).equalTo("id", someId).findFirst();
user.getUser.setFav(true);
Log.D(TAG,user.getUser.isFav);
//got false

but if i declare a new Object of RMUser from it's parent object, i will get true;
RMDepartmentUser user = Realm.getInstance(this).where(RMDepartmentUser.class).equalTo("id", someId).findFirst();
RMUser realUser=user.getUser();
realUser.setFav(true);
Log.D(TAG,realUser.isFav);
//got true

**Comment by beeender** [comment]
What is the definition of `RMDepartmentUser.getUser` ?

**Comment by xingxp** [comment]
auto generated getter and setter
public RMUser getUser() {
        return user;
    }

    public void setUser(RMUser user) {
        this.user = user;
    }

**Comment by beeender** [comment]
Realm is using proxy for you classes, which means all the field declared in your model class is not touched by Realm. Instead, Realm exchange data with your program through overriding getters and setters.

In this case, when every time you call `user.getUser`, a new RMUserProxy instance will be created and returned. In normal case, all the data is persisted by Realm, and the new instance will have the latest data stored in Realm. But when you put `@Ignore` annotation there, Realm will just ignore them. And they are still using the original getters and setters.
So, here, `user.getUser` will always return a RMUserProxy instance with `fav` untouched (the default value false).

So, if you need this, Keep the reference to user.getUser and set and use `fav` through that reference.

**Comment by beeender** [comment]
Hi, I am closing this issue now. If you have further problems with this, feel free to reopen it.
Thanks for your feedback!
