### ISSUE TITLE
Deep copy of a realm object to populate fields

### ISSUE THREAD

**Issue by kanishktripathi** [realm/realm-java#1324]
Supporting copy of a realm object from database such that the fields of the returned object are populated. This can be useful for serialization using libraries like GSON. Currently we have to write a custom serializer for every realm class which means lots of boilerplate code. It also means difficulty in maintenance.

**Comment by cmelchior** [comment]
Hi @kanishktripathi 
We agree, and there is already an issue tracking this here: https://github.com/realm/realm-java/issues/931
So I'll close this as a duplicate.
