### ISSUE TITLE
io.realm.exceptions.RealmMigrationNeededException: Index not defined for field 'id'

### ISSUE THREAD

**Issue by amozoss** [realm/realm-java#1330]
Upgrading from 0.81.1 to 0.82.0 causes `io.realm.exceptions.RealmMigrationNeededException: Index not defined for field 'id'`. I am able to migrate my realm using `RealmConfiguration` with the `.migration` in version 0.81.1, but I get the exception in 0.82.0. 

I've tried it a few times and it has crashed with two different `RealmObjects` on different attempts. Seems to be coming from the `io.realm.ReminderRealmProxy.validateTable(ReminderRealmProxy.java:241)` method. The `id` field is defined in both classes as:

         @PrimaryKey
         private int id;

Any ideas what may be causing this issue?

**Comment by beeender** [comment]
Hello! 
Please check this https://realm.io/news/realm-java-0.82.0/
The bottom, breaking change part. And the java doc will be updated soon!

**Comment by amozoss** [comment]
Ok I'll check it out. Yeah I think a think a link like you just provided would be helpful if it was near the top of the docs (thats where I tried to find it), especially for breaking changes.

**Comment by amozoss** [comment]
I was able to resolve the issue by adding every use of `@PrimaryKey` as a searchIndex. My `@PrimaryKey`'s were defined as `int`s and `long`s. I had to add my `long` primary keys as well, which is a little unclear by the breaking change document. I had 3 classes with primary keys, this is how I resolved the issue in my `Migration` class. 

        if (version == 2) {
            // Update for PrimaryKey breaking change
            Table table = realm.getTable(Reminder.class);
            long keyIndex = table.getColumnIndex("id"); // id defined as int
            table.addSearchIndex(keyIndex);

            table = realm.getTable(Goal.class);
            keyIndex = table.getColumnIndex("id"); // id defined as int
            table.addSearchIndex(keyIndex);
            
            // id defined as a long, migration did not work until longs were added as well. 
            table = realm.getTable(HabitualGoal.class);
            keyIndex = table.getColumnIndex("id");
            table.addSearchIndex(keyIndex);
            version++;

        }
