### ISSUE TITLE
Question/Clarification - Realm and Threads

### ISSUE THREAD

**Issue by m00sey** [realm/realm-java#1335]
Hi,

I've used Realm on an iOS project, and didn't really run into this issue, I'm guessing the short version was I must have done my realm work on the UI thread.

However on Android, even with small amounts of data we got Choreographer warnings 'the application may be doing too much work on the UI thread'. (Low end hardware)

We are using RxJava/Retrofit and as a result we attempted to do our writes on various background/io threads. 

I presumed once an object was written to realm and the realm 'closed' I could query it from a different thread. This is not proving to be the case. I've read the other issues here, but I just can't believe that once a realm object is created on a particular thread, it can *never* be accessed from a different one?

     Profile creation on Thread[RxCachedThreadScheduler-2,5,main]
     Notebook creation on Thread[RxCachedThreadScheduler-1,5,main]

We then reference the profile when creating a notebook.

     Failed to replace notebooks io.realm.exceptions.RealmException: Error during transaction.
     Realm access from incorrect thread. Realm objects can only be accessed on the thread they were created.

**Comment by cmelchior** [comment]
You can always query for an object on the other thread, but you can't access the original object, which it sounds like what you are doing by looking at your log?

e.g.
```
Thread1: profile = createProfile()

Thread2: notebook = createNotebook()
noteBook.setProfile(profile) // this will crash
noteBook.setProfile(realm.query(Profile).where().equalTo("id", profileId").findFirst()) // will work
```

We are aware that this is not optimal of course, so it is something we are actively working on making better.

**Comment by m00sey** [comment]
Thanks for the quick response, that's not really what we're doing though

We're querying for the profile/studentId, then using that when we create the note books.

Here's the full implementation
```
        val realm = realmProvider.getWriteRealm()
        val studentId = profileProvider!!.getProfile().getStudentId()
        val notebooks = realm.where(clazz).findAll()
        try {
            realm.executeTransaction {
                notebooks.clear()
                for (notebook in entities) {
                    notebook.setMySharedSort(notebook.getStudentId() == studentId)
                    realm.copyToRealmOrUpdate(notebook)
                }
            }
        } catch (e: Exception) {
            Log.e(TAG, "Failed to replace notebooks ${e}")
        } finally {
            realm.close()
        }
```

     profileService.getProfile()

is implemented as

    return realm.where(clazz).findFirst()

**Comment by cmelchior** [comment]
You are using two different Realm instances. One from `realmProvider` and one used in `profileProvider`, are they the same on the same thread? If you use a debugger they should have the same identifier as we use a thread local cache.

If that is the case, then it is a bit strange. It looks like you are using Kotlin lamda though for the write transaction. Maybe something is going wrong in the conversion to Java?

**Comment by m00sey** [comment]
Hm, so no they are not the same realm instance, but they are on the same thread, at least when we go to query.

The profile provider is injected, and so ends up with a realm reference from a different thread, which occurs when this notebook service is initialized (also injected).

The short version is, changing the implementation to:

```
val realm = realmProvider.getWriteRealm()
val studentId = realm.where(javaClass<Profile>()).findFirst().getStudentId()
val notebooks = realm.where(clazz).findAll()
```

works.

**Comment by cmelchior** [comment]
Ok. Great you found a solution.

Note that Realms are cached internally as well. So calling 
```
Realm.getInstance()
//or
Realm.getDefaultInstance()
``

is really cheap as it is just a cache lookup.
