### ISSUE TITLE
[FEATURE_REQUEST] Smaller lib size

### ISSUE THREAD

**Issue by cotfas** [realm/realm-java#1337]
Is there any chance to have less than 2.5 MB of the actual library size?

I`m asking because right now my app has 7MB which is huge and I`m thinking to optimize / reduce the apk size (I already use proguard)

Thank you.

**Comment by emanuelez** [comment]
You can use the split APK functionality. You can see this article we wrote about the subject a few months back: https://realm.io/news/reducing-apk-size-native-libraries/
