### ISSUE TITLE
Can I keep Realm instance opened for main thread?

### ISSUE THREAD

**Issue by virl** [realm/realm-java#1338]
Greetings.

Can I keep Realm instance opened for main thread? Or should I close it after each use and reopen next time I need something for it?

In other words, is it safe to keep references to Realm instance and its objects for long periods of time?
And what happens with objects on main thread if they're deleted from Realm on background thread?

**Comment by NAYOSO** [comment]
I think it's quite risky because it will increase a potential of native memory leak. Is there any specific reason why do you want to keep it open for long periods of time?

**Comment by cmelchior** [comment]
Hi @virl 
There is nothing inherently wrong with keeping the Realm on the UI thread open and not closing it.

However you should keep the following in mind:

- Realm can handle the process getting killed just fine, which means that forgetting to close Realm is not dangerous to your data.

- Not closing Realm when the app goes in the background means you will be more likely to get killed by the system if it gets low on resources.


Regarding objects getting deleted: If a background thread is deleted you have two options:

1) Register a RealmChangeListener and query for the object again: https://realm.io/docs/java/latest/api/io/realm/Realm.html#addChangeListener(io.realm.RealmChangeListener)

2) Use the `isValid()` method on the RaelmObject before trying to access any data. If it was deleted that method will return false.

**Comment by virl** [comment]
Thanks.
