### ISSUE TITLE
Cascade Deletes or Deleting RealmList Items from RealmObject

### ISSUE THREAD

**Issue by maarek** [realm/realm-java#1339]
I have a case where I'm calling a copyToRealmOrUpdate(List<MyObject>) and I have noticed that the RealmList that is a property on MyObject gets updated to the new list for MyObject but old objects get orphaned and not deleted. My guess is that there is no support for cascading deletes. Since they don't have primary keys, I have no identifiable way to query them and remove them after the fact. 

What would be the best possible solution for this? Would MyObject's property need to also have MyObject's primary key in order to query and delete those old orphaned objects? I could try some sort of app processing to remove them before the copyToRealmOrUpdate but it seems really heavy and only grows as the number of MyObjects grows. 

Get a List<MyObject>
For each MyObject, query for the stored Realm MyObject.
Get RealmList from stored Realm MyObject
Loop through RealmList object and removeFromRealm

Thoughts?

**Comment by cmelchior** [comment]
Hi @maarek Sorry for the late response.
Yeah, unfortunately cascading deletes are not supported yet. You can follow progress on that here https://github.com/realm/realm-java/issues/1104

Right now your only option is something like what you outlined.

**Comment by aercanozcan** [comment]
Are you planning to support cascade delete? If so what is the priority?

**Comment by emanuelez** [comment]
Yes, we are planning to support cascading deletes. It is currently under study in the core team.

**Comment by azizj1** [comment]
+1

**Comment by maarek** [comment]
Was there a verdict on this? Saw that it got closed without any update on the support of cascading deletes? :)

**Comment by kneth** [comment]
@maarek I closed it as #1104 is the issue to follow instead.

**Comment by petaren** [comment]
+1 On this issue

**Comment by heyzooi** [comment]
+1 please

**Comment by heyzooi** [comment]
+1 please

**Comment by badjano** [comment]
bump

**Comment by Zhuinden** [comment]
@badjano  this is duplicate of https://github.com/realm/realm-java/issues/1104

**Comment by genie137** [comment]
+1

**Comment by alvaroroyo** [comment]
Good job Realm Team. I think it's a great db.
Obviously needs more work to some features like cascade deletions but we can develop some object methods for that.
Thanks
+1

**Comment by naser-shaikh** [comment]
Any update on cascade delete?

**Comment by Zhuinden** [comment]
Sync doesn't support it so ObjectStore doesn't implement it so Java is stuck in limbo.

https://github.com/realm/realm-java/pull/5678

**Comment by programaths** [comment]
Well, isn't that dangerous ? Realm is a graph database and links between objects can quickly get out of hand and it would be easy to CASCADE DELETE all the graph by the sole "spaghetti effect".

**Comment by i-schuetz** [comment]
Please reopen, this was never solved.

**Comment by cmelchior** [comment]
It is a duplicate of #1104

**Comment by asymptotik** [comment]
5 years later?

**Comment by programaths** [comment]
@asymptotik They are quite quick 🤣
