### ISSUE TITLE
How to solve "error: cannot find symbol class MyObjectRealmProxy"

### ISSUE THREAD

**Issue by Frasprite** [realm/realm-java#1346]
Hi,
i'm trying to use Realm on Android with Parceler (my object are using RealmList too).
I followed your example and i get the error in the title.
I tried to add @RealmClass annotation, but it is not working too. I'm using Android Studio 1.3 and this is the .gradle file.

apply plugin: 'com.android.library'

android {
    compileSdkVersion 22
    buildToolsVersion "22.0.1"

    defaultConfig {
        minSdkVersion 19
        targetSdkVersion 22
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:22.2.1'
    compile 'com.loopj.android:android-async-http:1.4.8'
    compile files('libs/realm-0.81.1.jar')
    compile 'org.parceler:parceler-api:1.0.3'
    compile project(':logger')
}

And this is my code:
@Parcel(implementations = { ActivityModelRealmProxy.class },
        value = Parcel.Serialization.BEAN,
        analyze = { ActivityModel.class })
public class ActivityModel extends RealmObject {
...
@ParcelPropertyConverter(ModelKeyListParcelConverter.class)
    public void setModelKeyList(RealmList<ModelKey> modelKeyList) {
        this.modelKeyList = modelKeyList;
    }
...
}

public class ModelKeyListParcelConverter extends RealmListParcelConverter {
    @Override
    public void itemToParcel(Object input, Parcel parcel) {
        parcel.writeParcelable(Parcels.wrap(input), 0);
    }

    @Override
    public Object itemFromParcel(Parcel parcel) {
        return Parcels.unwrap(parcel.readParcelable(ModelKey.class.getClassLoader()));
    }
}

public abstract class RealmListParcelConverter<T extends RealmObject> extends CollectionParcelConverter<T, RealmList<T>> {
    @Override
    public RealmList<T> createCollection() {
        return new RealmList<>();
    }
}

What am i doing wrong?

**Comment by beeender** [comment]
Comment out `@Parcel(implementations = { ActivityModelRealmProxy.class },` block and build one since `ActivityModelRealmProxy` is generated by Realm based on `ActivityModel`. Then enable the block and compile again.

It is documented here [in the comments](https://realm.io/docs/java/latest/#parceler) .

And it can be compiled with AS 1.3, but AS is still complaining about the missing class `ActivityModelRealmProxy` . We will investigate on it.

**Comment by Frasprite** [comment]
After several unsuccessful tests, i've decided not use Parceler.
Thanks for your patience.

**Comment by AleksandarIlic** [comment]
Hi @beeender, any update on missing class with AS 1.3+? Thanks.

**Comment by beeender** [comment]
@AleksandarIlic Hi, I just tried to setup and use Parceler with Realm with AS 1.3, they are actually working fine together by following our instructions [here](https://realm.io/docs/java/latest/#parceler)

What is your problem? You need to compile project once without `@Parcel` annotation to make sure the ProxyClass is generated  then add them.

**Comment by AleksandarIlic** [comment]
@beeender I have just figure out the problem. I have a `common` Android library project in which I have added Realm and Parceler to build.gradle as follows:

    apply plugin: 'com.android.library'
    apply plugin: 'com.neenbedankt.android-apt'

    ...

    repositories {
        maven {url 'http://oss.jfrog.org/artifactory/oss-snapshot-local'} // Realm repo
    }

    dependencies {
        compile 'io.realm:realm-android:0.82.0'
        compile 'org.parceler:parceler-api:1.0.3'
        apt 'org.parceler:parceler:1.0.3'
        // other dependencies
    }

In my `app` Android project I'm including the `common` library project as follows: 

    apply plugin: 'com.android.application'

    repositories {
        maven {url 'http://oss.jfrog.org/artifactory/oss-snapshot-local'} // Realm repo
    }

    dependencies {
        compile project(':common')
        // other dependencies
    }


AS does not find `ProxyClasses` for my custom `RealmObjects` created in `app` project, but it does find them for `RealmObjects` created in `common` library. But if there are `RealmObjects` in `common` library I'm not able to build the `app` project due following build error:

    Error:Execution failed for task ':app:dexDebug'.
    > com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command '/Library/Java/JavaVirtualMachines/jdk1.7.0_65.jdk/Contents/Home/bin/java'' finished with non-zero exit value 2

**Comment by beeender** [comment]
@AleksandarIlic If you can share your new empty project with us, i think it can be solved quickly! help@realm.io 

Or share it though any other way you want :)

**Comment by AleksandarIlic** [comment]
@beeender Sent via e-mail. Let me know if you need anything else.

**Comment by beeender** [comment]
@AleksandarIlic Try to add `apply plugin: 'com.neenbedankt.android-apt'` and `apt 'org.parceler:parceler:1.0.3'` to your app's gradle file as well. At least it fixed problem on my computer :smile:

**Comment by AleksandarIlic** [comment]
@beeender It works. Thanks for the help!
