### ISSUE TITLE
A realm object can not be used for reading after Realm instance has been closed in 0.82.0

### ISSUE THREAD

**Issue by risayew** [realm/realm-java#1348]
Hello!
I have the following exception:

    java.lang.IllegalStateException: This Realm instance has already been closed, making it unusable.
            at io.realm.Realm.checkIfValid(Realm.java:186)
            at io.realm.UserPoiRealmProxy.getId(UserPoiRealmProxy.java:61) ... .

This happens, probably, because we try to use the realm object after the Realm instance has been closed. However the same code worked without any problem with version 0.80.1. Can anybody help me, please?

**Comment by beeender** [comment]
@risayew We solved a problem with PR #1245 which might cause your Realm instance is not closed properly before. I suggest you to check if you have been trying to close Realm instances across threads.

**Comment by risayew** [comment]
The exception happens because in the UserPoiRealmProxy in the getter method realm.checkIfValid() will be called.

    @Override
    public String getId() {
        realm.checkIfValid();
        return (java.lang.String) row.getString(INDEX_ID);
    }
Yes, you are right. i'm closing the Realm instance and then try to read (not write) from the realm object as it would be a standalone object.

**Comment by beeender** [comment]
Could delay the `Realm.close()` solve your problem?

**Comment by risayew** [comment]
Yes, if i close the Realm instance after i read from the realm object, the problem will be solved. But i don't like this solution.

**Comment by beeender** [comment]
Yeah, totally understand that.
You can subscribe to this issue #931 , it is tracking the feature to de-attach the object from Realm which might be the solution you would like :)

**Comment by risayew** [comment]
I was already subscribed ) !
So, i think for the moment i roll-back to the old realm 0.80.1. Because it was working). With 0.82.0 i break my app.

**Comment by risayew** [comment]
Thank you so much for your support!
