### ISSUE TITLE
Support RoboVM

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#1349]
Figure how how much will be required to support RoboVM: http://robovm.com/

**Comment by lucamtudor** [comment]
I did not believe I would say this, but it would be really great if you guys could support roboVM :+1: .

**Comment by kenticus** [comment]
@lucamtudor +1

**Comment by andreiverdes** [comment]
+1

**Comment by lucamtudor** [comment]
Maybe you could also take a look at Intel's Multi-OS Engine (new kid on the block): https://software.intel.com/en-us/multi-os-engine

**Comment by erneestoc** [comment]
+1

**Comment by cmelchior** [comment]
RoboVM is shutting down: https://robovm.com/robovm-winding-down/

**Comment by lucamtudor** [comment]
@cmelchior any plans to support Intel's Multi-OS Engine? LibGDX has moved towards that in the light of robovm's faith.

**Comment by cmelchior** [comment]
@lucamtudor Currently no, also in the light that it isn't a stable product yet.
