### ISSUE TITLE
Server response sometimes contains object, sometimes contain just primary key, how to handle?

### ISSUE THREAD

**Issue by StephenMilone** [realm/realm-java#1362]
Hi all, moving my project to using Realm and come across an odd situation.  So there are some instances where my server will respond with an entire object with an id (int) i set as a primary key.  other times it will send just that id.

full object:
>[{"target_object": {"object_value1": 212, "object_value2": "Manhattan", "id": 1}, "value1": "NY", "value2": "us" }]

just id:
>[{"target_object": 1, "value1": "NY", "value2": "us" }]

I have code in that if all I get is the id, I can query for the object or fetch it individually if it's not readily available. But I'm unsure how to handle this when using Realm, I seem to be a culprit for getting type mismatch exceptions all the time since I can't add any if/else in my RealmObject classes where "target_object" could be a json object or just a integer.  hope that made sense. please advise and thanks so much!

to give a better idea, currently (without realm) I had code like this in my constructors:
```
        if(jsonObject.get("target_object").isJsonObject()) {
            this.target = new TargetObject(jsonObject.get("target_object").getAsJsonObject());
            this.targetId = this.target.getId();
        } else {
            this.targetId = jsonObject.get("target_object").getAsInt();
        }
```

**Comment by beeender** [comment]
To be honest, I don't think it is a ideal Json response. The major problem is not only the `target_object`, but also the fields names are different (`value1` -> `old_value1` , `value2` -> `old_value2`).

The best way is changing the Json response to the ideal one :)

Or try this:

```java

public class Target extends RealmObject {
   // Make a differnt field name, so it can be parsed manually
   private int targetId;
   private String value1;
   private String value2;

   // setters and getters
}

// In Json response handler
realm.beginTransaction();
Target newTarget = realm.createObjectFromJson(Target.class, jsonObject);
Object targetObj = jsonObject.get("target_object");
if(targetObj instanceof Integer) {
   newTarget.setTargetId(targetObj);
} else if (targetObj instanceof JSONObject) {
   newTarget.setTargetId(((JSONObject)targetObj).getInt("id"));
} else {
   // Something is wrong
}
realm.commitTransaction();
```

Still, this kind of Json response always needs extra work to parse...

**Comment by StephenMilone** [comment]
Ok thanks @beeender 

I'll give it ago, what you said makes perfect sense.

**Comment by beeender** [comment]
Great! I am closing this issue now. Thanks a lot for you feedback!
