### ISSUE TITLE
RealmCollection interface

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#1363]
We need a `RealmCollection` to be able to parse different lists into UI components.

- [ ] Figure out exactly which methods should be in the interface 
- [ ] Make `RealmResults` and `RealmList` implement the interface
- [ ] Document the interface on the website (#2258).

v1 Needs to support `RealmResults` and `RealmList` /cc #972  
v2 Support for RealmSet when it becomes available #759 
v3 Support for RealmMap. Will most likely require its own interface. #759

**Comment by bmunkholm** [comment]
Align with Cocoa on this.

**Comment by cmelchior** [comment]
I think we could split this into possible 2 interfaces. The reason being that our observer pattern is being reused across all our primary classes.

```
public interface Observable {
  void addChangeListener(ChangeListener listener);
  void removeChangeListener(ChangeListener listener);
  void removeAllChangeListeners();
}

public interface RealmCollection<E> extends List<E> {
  boolean isLoaded();
  E load();
}
```

What do you think? @realm/java

**Comment by dalinaum** [comment]
I am worry about little confusing between RxJava's `Observable` and proposed `Observable`.

**Comment by Saketme** [comment]
I so need this for an adapter that is capable for handling both `RealmList` and `RealmResults` :D

**Comment by cmelchior** [comment]
@dalinaum True, `Observable` was just my initial suggestion. `RealmObservable` could probably also work. I updated the proposal

**Comment by cmelchior** [comment]
Looking at RLMCollection: https://realm.io/docs/objc/latest/api/Protocols/RLMCollection.html, it seems our `RealmCollection` interface should be the following:

```
// All collections are Lists. This won't work with Sets, problem?
public interface RealmCollection<E> extends List<E>, RealmObservable {
  E first()
  E last() // we don't have this currently
  RealmQuery<E> where()

  // Async methods
  boolean isLoaded();
  E load();

  // These are kinda new. Didn't we remove those for some reason?
  sort(String field, Sort sortOrder)
  sort(String field1, Sort sortOrder1, String field2, Sort sortOrder2)
  sort(String[] fields, Sort[] sortOrders)
}

**Comment by cmelchior** [comment]
@kneth / @emanuelez Didn't we remove `RealmResults.sort()` for some reason?

**Comment by jpsim** [comment]
This is an area where the Swift API has gotten a little further ahead than the ObjC one: https://realm.io/docs/swift/latest/api/Protocols/RealmCollectionType.html

We expose aggregate operations on all `RealmCollectionType`s: min, max, sum, average.

Otherwise, judging by what you inherit when you extend `List`, it seems to cover everything.

**Comment by beeender** [comment]
And maybe try to align the behaviour of `clear` and `removeFromRealm` in the interface

**Comment by cmelchior** [comment]
Yes, having a unified RealmCollection interface means we have to find the same semantics for all methods as `realmCollection.clear()` should work the same way regardless if it a `RealmResults` or a `RealmList`.
