### ISSUE TITLE
Don't process model classes that hasn't changed

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#1366]
Currently the annotation processor will analyse and create proxy classes/modules for all model classes each time it is run. This will slow down builds for larger projects.

Instead we should detect if a file has changed since last it was analysed and if it hasn't skip the analysis and creation of the proxy class.

**Comment by nhachicha** [comment]
This could be tricky, this is even subtle than incremental build in gradle, we need to watch for concurrent process trying to build the project, keep a persistent map of hashes of the previously proceed files (URI)

Maybe move this to backlog, it's not a P1 ..._yet_

**Comment by cmelchior** [comment]
Agreeded. It is not that important yet. It is still something we want to look at at some point IMO.

**Comment by cmelchior** [comment]
Merging this into #5906
