### ISSUE TITLE
Link query with isNull/isNotNull

### ISSUE THREAD

**Issue by michael-mohemian** [realm/realm-java#1367]
Unfortunately link queries with isNull or isNotNull are not yet supported:

```
realm.where( Contact.class ).isNotNull( "emails.address" ).findAll( );
```

Raises the exception:
java.lang.IllegalArgumentException: Checking for null in nested objects is not supported.

**Comment by beeender** [comment]
Yes, it is a known restriction. And our core team is working on that.

Thanks for reporting this!

**Comment by cmelchior** [comment]
This should have been fixed by https://github.com/realm/realm-core/pull/1020 . We just need to test and modify the binding accordingly.

**Comment by cmelchior** [comment]
Actually this is already supported, see https://github.com/realm/realm-java/blob/master/realm/realm-library/src/androidTest/java/io/realm/RealmQueryTests.java#L2001

Closing
