### ISSUE TITLE
Object is not part of the schema for this Realm

### ISSUE THREAD

**Issue by samkazmi** [realm/realm-java#1368]
Trying to run one of your example.. AdapterExample and getting this error 
i tried it in my project also still getting this error..

08-07 16:26:24.806: E/AndroidRuntime(7711): Process: io.realm.examples.realmadapters, PID: 7711
08-07 16:26:24.806: E/AndroidRuntime(7711): java.lang.RuntimeException: Unable to start activity ComponentInfo{io.realm.examples.realmadapters/io.realm.examples.realmadapters.AdapterExampleActivity}: java.lang.IllegalArgumentException: TimeStamp is not part of the schema for this Realm
08-07 16:26:24.806: E/AndroidRuntime(7711): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2693)
08-07 16:26:24.806: E/AndroidRuntime(7711): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2758)
08-07 16:26:24.806: E/AndroidRuntime(7711): 	at android.app.ActivityThread.access$900(ActivityThread.java:177)
08-07 16:26:24.806: E/AndroidRuntime(7711): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1448)
08-07 16:26:24.806: E/AndroidRuntime(7711): 	at android.os.Handler.dispatchMessage(Handler.java:102)
08-07 16:26:24.806: E/AndroidRuntime(7711): 	at android.os.Looper.loop(Looper.java:145)
08-07 16:26:24.806: E/AndroidRuntime(7711): 	at android.app.ActivityThread.main(ActivityThread.java:5942)
08-07 16:26:24.806: E/AndroidRuntime(7711): 	at java.lang.reflect.Method.invoke(Native Method)
08-07 16:26:24.806: E/AndroidRuntime(7711): 	at java.lang.reflect.Method.invoke(Method.java:372)
08-07 16:26:24.806: E/AndroidRuntime(7711): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
08-07 16:26:24.806: E/AndroidRuntime(7711): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)
08-07 16:26:24.806: E/AndroidRuntime(7711): Caused by: java.lang.IllegalArgumentException: TimeStamp is not part of the schema for this Realm
08-07 16:26:24.806: E/AndroidRuntime(7711): 	at io.realm.internal.modules.CompositeMediator.getMediator(CompositeMediator.java:118)
08-07 16:26:24.806: E/AndroidRuntime(7711): 	at io.realm.internal.modules.CompositeMediator.getTableName(CompositeMediator.java:71)
08-07 16:26:24.806: E/AndroidRuntime(7711): 	at io.realm.Realm.getTable(Realm.java:317)
08-07 16:26:24.806: E/AndroidRuntime(7711): 	at io.realm.RealmQuery.<init>(RealmQuery.java:75)
08-07 16:26:24.806: E/AndroidRuntime(7711): 	at io.realm.Realm.where(Realm.java:1205)
08-07 16:26:24.806: E/AndroidRuntime(7711): 	at io.realm.examples.realmadapters.AdapterExampleActivity.onCreate(AdapterExampleActivity.java:48)
08-07 16:26:24.806: E/AndroidRuntime(7711): 	at android.app.Activity.performCreate(Activity.java:6289)
08-07 16:26:24.806: E/AndroidRuntime(7711): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1119)
08-07 16:26:24.806: E/AndroidRuntime(7711): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2646)
08-07 16:26:24.806: E/AndroidRuntime(7711): 	... 10 more

**Comment by cmelchior** [comment]
Hi @samkazmi 
I tried to run it on my machine where it was working fine. Can you give some more details about your setup? Are you using Eclipse or Android Studio?

**Comment by samkazmi** [comment]
i'm using Eclipse and i followed the instructions.

**Comment by cmelchior** [comment]
Note that Eclipse doesn't support inherited annotations so the `TimeStamp` class should look like this:

```
@RealmClass
public class TimeStamp extends RealmObject {
 //...
}
```

**Comment by samkazmi** [comment]
Thanks man... It worked...
But in my application it is still giving me error....

08-07 17:13:59.546: E/AndroidRuntime(25979): Process: com.pantera.picksha, PID: 25979
08-07 17:13:59.546: E/AndroidRuntime(25979): io.realm.exceptions.RealmException: class com.pantera.data.album is not part of the schema for this Realm.
08-07 17:13:59.546: E/AndroidRuntime(25979): 	at io.realm.internal.RealmProxyMediator.getMissingProxyClassException(RealmProxyMediator.java:154)
08-07 17:13:59.546: E/AndroidRuntime(25979): 	at io.realm.DefaultRealmModuleMediator.getTableName(DefaultRealmModuleMediator.java:52)
08-07 17:13:59.546: E/AndroidRuntime(25979): 	at io.realm.Realm.getTable(Realm.java:317)
08-07 17:13:59.546: E/AndroidRuntime(25979): 	at io.realm.Realm.createObject(Realm.java:1077)
08-07 17:13:59.546: E/AndroidRuntime(25979): 	at com.pantera.fragments.PublicAlbumFragment.onCreateView(PublicAlbumFragment.java:41)
08-07 17:13:59.546: E/AndroidRuntime(25979): 	at android.support.v4.app.Fragment.performCreateView(Fragment.java:1789)
08-07 17:13:59.546: E/AndroidRuntime(25979): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:955)
08-07 17:13:59.546: E/AndroidRuntime(25979): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1138)
08-07 17:13:59.546: E/AndroidRuntime(25979): 	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:740)
08-07 17:13:59.546: E/AndroidRuntime(25979): 	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1501)
08-07 17:13:59.546: E/AndroidRuntime(25979): 	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:458)
08-07 17:13:59.546: E/AndroidRuntime(25979): 	at android.os.Handler.handleCallback(Handler.java:739)
08-07 17:13:59.546: E/AndroidRuntime(25979): 	at android.os.Handler.dispatchMessage(Handler.java:95)
08-07 17:13:59.546: E/AndroidRuntime(25979): 	at android.os.Looper.loop(Looper.java:145)
08-07 17:13:59.546: E/AndroidRuntime(25979): 	at android.app.ActivityThread.main(ActivityThread.java:5942)
08-07 17:13:59.546: E/AndroidRuntime(25979): 	at java.lang.reflect.Method.invoke(Native Method)
08-07 17:13:59.546: E/AndroidRuntime(25979): 	at java.lang.reflect.Method.invoke(Method.java:372)
08-07 17:13:59.546: E/AndroidRuntime(25979): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1400)
08-07 17:13:59.546: E/AndroidRuntime(25979): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1195)

on realm.createObject(album.class);

**Comment by cmelchior** [comment]
That error still indicate that the annotation processor isn't running in your project. I would try cleaning and rebuilding your project. You can also delete the folder `.apt_generated` manually which hold all the files generated by the annotation processor.

**Comment by samkazmi** [comment]
Thanks...

**Comment by danielgchap** [comment]
[RealmTester.zip](https://github.com/realm/realm-java/files/90611/RealmTester.zip)

**Comment by qingsong-xu** [comment]
Hi,I`m also has the issue,help :

Process: com.iboxpay.cashbox.sdk.plug, PID: 22261
                                                                              java.lang.IllegalArgumentException: OffLineTradingModel is not part of the schema for this Realm
                                                                                  at io.realm.internal.modules.CompositeMediator.getMediator(CompositeMediator.java:157)
                                                                                  at io.realm.internal.modules.CompositeMediator.copyOrUpdate(CompositeMediator.java:97)
                                                                                  at io.realm.Realm.copyOrUpdate(Realm.java:1302)
                                                                                  at io.realm.Realm.copyToRealm(Realm.java:726)
                                                                                  at com.iboxpay.openplatform.box.sm.BaseStateMachine.tradingOffLine(BaseStateMachine.java:1066)
                                                                                  at com.iboxpay.openplatform.box.sm.P60XBoxStateMachine$RegistedState.processMessage(P60XBoxStateMachine.java:1005)
                                                                                  at com.iboxpay.openplatform.box.sm.StateMachine$SmHandler.processMsg(StateMachine.java:955)
                                                                                  at com.iboxpay.openplatform.box.sm.StateMachine$SmHandler.handleMessage(StateMachine.java:775)
                                                                                  at android.os.Handler.dispatchMessage(Handler.java:111)
                                                                                  at android.os.Looper.loop(Looper.java:194)
                                                                                  at android.os.HandlerThread.run(HandlerThread.java:61)



My model code :
/**
 * Created by Jack on 16/8/11.
 */
public class OffLineTradingModel extends RealmObject {
    @PrimaryKey
    private String outTradeNo;
    private String iboxMchtNo;
    ........

    public String getOutTradeNo() {
        return outTradeNo;
    }

    public void setOutTradeNo(String outTradeNo) {
        this.outTradeNo = outTradeNo;
    }
}

---------------------------------------
and I use the mode :
Realm realm = OffLineTradeHelper.getRealm(mCashBoxContext.getContext());
        if (OffLineTradingModel.class.getSuperclass().equals(RealmObject.class))
        {
            Log.e("is right!!!!!!");//is ok.
        }
        realm.beginTransaction();
        OffLineTradingModel offLineTradingModel = realm.createObject(OffLineTradingModel.class);
        offLineTradingModel.setOutTradeNo(mTradingData.getOutTradeOrderNo());
        offLineTradingModel.setAppCode(mBaseUserModel.getAppCode());
        offLineTradingModel.setAlreadySuc(false);
        realm.commitTransaction();

but the line code is error: OffLineTradingModel offLineTradingModel = realm.createObject(OffLineTradingModel.class);

I don`t know how to resolve the issue.Please help me.

**Comment by GaborPeto** [comment]
qingsong-xu:

Did you add apply plugin: 'realm-android' to your app build.gradle file (or the module you use realm in)?

**Comment by vishsinghal** [comment]
Hello friends,
am also getting this type of issue

java.lang.IllegalArgumentException: CallSmsHistory is not part of the schema for this Realm

CallSmsHistory  is my model calss this exception . i cann't understand reason

my model class code is 


import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;

public class CallSmsHistory extends RealmObject {

    @PrimaryKey
    private String time;
    private int id;
    private String address;
    private String msg;
    private String date;
    private String folderName;
    private String readState;
    private String TypeStatus;
    private String Number;
    private String Subject;
    private String to;
    private String cc;
    private String GroupType;
    private String GroupName;
    private String ImageUrl;

}

Please help me regarding this problem

**Comment by GaborPeto** [comment]
@vishsinghal how does your app's build.gradle look like?

**Comment by vishsinghal** [comment]
android {
    compileSdkVersion 24
    buildToolsVersion "24.0.2"

    defaultConfig {
        applicationId "com.spine.spinesfa"
        minSdkVersion 15
        targetSdkVersion 24
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}
    repositories {
        jcenter()
    }
    dependencies {
        apply plugin: 'announce'
        compile fileTree(dir: 'libs', include: ['*.jar'])
        compile files('libs/glide-3.4.0.jar')
        compile 'com.android.support:appcompat-v7:24.2.0'
        compile 'com.android.support:appcompat-v7:24.2.0'
        compile 'com.android.support:design:24.2.0'
        compile 'com.android.support:multidex:1.0.1'
        compile 'com.android.support:cardview-v7:24.2.0'
        compile 'com.android.support:recyclerview-v7:24.2.0'
        compile 'com.github.wrdlbrnft:sorted-list-adapter:0.1.0.5'
        compile 'com.google.android.gms:play-services:9.4.0'
        compile 'com.google.android.gms:play-services-auth:9.4.0'
        compile 'com.google.android.gms:play-services-gcm:9.4.0'
        compile 'io.realm:android-adapters:1.3.0'
        compile 'com.squareup.retrofit:retrofit:1.9.0'
        compile 'com.squareup:otto:1.3.8'
    }

**Comment by vishsinghal** [comment]
@GaborPeto  above mention is my build.gradle please check what is my mistake

**Comment by vishsinghal** [comment]
@GaborPeto  
when i use this method 
 int size = realm.where(CallSmsHistory.class).findAll().size();

Then show below mention Exception:

Method threw 'java.lang.IllegalArgumentException' exception.

**Comment by GaborPeto** [comment]
@vishsinghal Add `apply plugin: 'realm-android'` to the top of your build.gradle. Rebuild and try again

**Comment by vishsinghal** [comment]
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.1.2'

        plugin: 'realm-android'
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

@GaborPeto  
i am add plugin hear but same Exception show

**Comment by Zhuinden** [comment]
@vishsinghal dude, just follow the installation section of the docs   https://realm.io/docs/java/latest/#installation

**Comment by GaborPeto** [comment]
:) 
@vishsinghal you added `apply plugin: 'realm-android'` to your root project's build.gradle.
You should add this to app/build.gradle

**Comment by vishsinghal** [comment]
![project build gridle](https://cloud.githubusercontent.com/assets/14270003/18825052/0962d640-83e4-11e6-92d0-d34f3af52782.png)

@GaborPeto 

I have already add in Project build.gradle 
Screen shot attached

Please check

**Comment by Zhuinden** [comment]
You are adding it to the wrong build.gradle and you also didn't add the classpath dependency to this file 

As I said, read the documentation and add the corresponding items as defined in the documentation 

https://realm.io/docs/java/latest/#installation <--- this link tells you what to do

**Comment by GaborPeto** [comment]
Look like you don't know the difference between project and app build.gradle. as @Zhuinden suggests: follow the installation instructions ^

**Comment by vishsinghal** [comment]
Thanks  i have solve my problem
