### ISSUE TITLE
Javascript SDK or JSON?

### ISSUE THREAD

**Issue by thecodingwizard** [realm/realm-java#1370]
When will there (if ever) be a Javascript SDK for realm?

It would be ideal if the Javascript SDK accepts a realm file and you can use normal API calls.

Or will there ever be a realm-to-JSON feature?

I guess my issue is that I want to create an android app using Realm, but I want to be able to edit my data online (with a bigger keyboard). Currently I'm just manually converting my data to and from JSON, but that's not easy... Any suggestions?

**Comment by kneth** [comment]
Just being curious: what should a JavaScript SDK support? I mean, JavaScript is used in many contexts (node.js, PhoneGap, etc.).

Currently, your best way to covert to JSON is to do it manually.
