### ISSUE TITLE
Backup and Restore: realm.writeCopyTo

### ISSUE THREAD

**Issue by thecodingwizard** [realm/realm-java#1372]
After I backup the realm file by using realm.writeCopyTo is there a specific API call that I need to call next, or do I simply manually replace the realm file (default.realm)?

**Comment by beeender** [comment]
Hi!

I am not quite sure what do you want. Do you just want to restore the realm from backup files?

Then do:
1. Close all the instances to the current realm
2. Replace the `default.realm` by `File` APIs.
3. Reopen the realm instance
4. Done :smile:

**Comment by beeender** [comment]
@thecodingwizard I hope it solved your problem :) I am closing this issue now, if the problem still exists, feel free to reopen this. 

Thanks!

**Comment by thecodingwizard** [comment]
Hi @beeender,

Thank you for all your help! That is exactly what I wanted. Sorry for the late response: I thought it would notify me by email, but I guess it never did.... :(
