### ISSUE TITLE
Validating Realm schema should only be done once

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#1373]
**Problem**:
1) Background thread opens Realm and begins a long living write transaction.
2) UI thread calls `Realm.getInstance()` for the first time.
3) Result: UI thread is locked until background thread completes because `initializeRealm` requires a write transaction.

**Reason**:
Our Realm cache is thread local and doesn't take into account that a Realm on another thread might have validated the schema already.

**Solution**:
We should cache the result of `mediator.validateTable(modelClass, realm.sharedGroup.getTransaction());`. Doing so will not only prevent unnecessary locking of the UI thread, but it will also speed up opening Realms considerable when doing so for the first time on new threads.

**Comment by beeender** [comment]
http://stackoverflow.com/questions/31521421/realm-causing-lots-of-anr This might be caused by this.
