### ISSUE TITLE
Parsing Object containing multiple arrays 

### ISSUE THREAD

**Issue by samkazmi** [realm/realm-java#1375]
Hi, I'm using eclipse. 
Having a problem parsing my object 

this is my main object
```java
@RealmClass
public class AlbumDetail extends RealmObject {

	private RealmList<gallery_details> gallery_details;
	private RealmList<AlbumDetailData> Data;
//...
}
```

```java
@RealmClass
public class gallery_details extends RealmObject{
	@PrimaryKey
	private String gallery_id;
	private String imageCount;
```

```java
@RealmClass
public class AlbumDetailData extends RealmObject {

        @PrimaryKey        
        private String imageId;	
        private String imageUrl;
	private String likesCount;
	private String commentCount;
	private String userId;
	private String like;
	private String like_id;
	private String delete;
//...
}
```

```java
	realm.createOrUpdateAllFromJson(AlbumDetail.class, jsonString);
```

getting error of shema

```
io.realm.exceptions.RealmException: class com.pantera.data.AlbumDetail is not part of the schema for this Realm.
```

**Comment by beeender** [comment]
hi, what is the error message?

**Comment by samkazmi** [comment]
io.realm.exceptions.RealmException: class com.pantera.data.AlbumDetail is not part of the schema for this Realm.

**Comment by beeender** [comment]
It feels like the same problem with #1368 ... Try to clean and rebuild...

One suggestion, it would be much less headache if you can switch to Android Studio...

**Comment by samkazmi** [comment]
It's not that error it's something else...
I tried to clean and rebuild... it doesn't work..

And android studio is very slow and it doesn't import eclipse projects correctly...

**Comment by beeender** [comment]
Do you have `AlbumDetailRealmProxy` generated in your build director?

And did you do following steps from https://realm.io/docs/java/latest/#installation
```
Right click on the realm jar file from libs folder, and go to “Build Path” -> “Add to Build path”.
Right click your project and select “Properties”, go to “Java Compiler” -> “Annotation Processing”, check “Enable project specific settings” and then click “Apply
```

**Comment by samkazmi** [comment]
Yes I've  followed the steps infact I'm using Realm someplace in my project. it's working just fine

No I don't see any file named AlbumDetailRealmProxy 

I have  gallery_detailsRealmProxy

**Comment by beeender** [comment]
Are you using proguard?

Can you share your project with us? to help@realm.io

**Comment by samkazmi** [comment]
I'm not using proguard.

yes sure... i will mention ```Parsing Object containing multiple arrays #1375``` as subject to the mail

**Comment by samkazmi** [comment]
Mail is not sent 

Delivery to the following recipients failed.
help@realm.io

Is the email address you wrote is correct?

**Comment by beeender** [comment]
it is correct... or can you upload it some where so i can get it? If it is not a confidential project...

**Comment by samkazmi** [comment]
Okay Give me a mint

**Comment by samkazmi** [comment]
Here is a link to my Project
![MyProject](https://onedrive.live.com/redir?resid=4EBCCF914F0F4FEE!6706&authkey=!AB3-Yv-1SSKX6Yc&ithint=folder%2cpng)

**Comment by beeender** [comment]
Hi

The problem is your class `AlbumDetail_GalleryData` , `AlbumDetailData`, `AlbumDetailLike` have declared a customized constructor, and no default constructor declared. That would cause a compiling error:

```
Error:A default public constructor with no argument must be declared if a custom constructor is declared.
```

Please check you compiling log carefully. And since they are not compiled at all, Realm cannot do anything with it.

**Comment by samkazmi** [comment]
Finally... it is working.. thanks .. and please mention the `<declaring default constructor>` in its doc
Thanks Man you rock.....

**Comment by beeender** [comment]
@samkazmi It is mentioned in the doc... https://realm.io/docs/java/latest/#creating-objects

**Comment by samkazmi** [comment]
Sorry my bad....

one more thing how can i delete a realm object?
is there a way to remove the object or something from the object like `realm.where(myObj.class).equalTo.(something).delete()`?

**Comment by samkazmi** [comment]
Never mind i got it..
thanks...

**Comment by Punpuf** [comment]
Hi, 
I'm having the same issue. How did you solve your problem ?
Thanks

**Comment by beeender** [comment]
@Punpuf You need to "declar default constructor" if you have custom constructors.

**Comment by Punpuf** [comment]
So for example if I have a Reminder class, I would do:

    
    class Reminder extends RealmObject{
    
        //The default constructor?
        Reminder(){}

        Reminder(int id, String (...)){
            this.id = id;
        }
    }

Is this correct ?
Thank you

**Comment by cmelchior** [comment]
Yes, but it needs to be public soclass Reminder extends RealmObject{

```
class Reminder extends RealmObject{

    //The default constructor?
    public Reminder(){}

    Reminder(int id, String (...)){
        this.id = id;
    }
}
```

**Comment by Punpuf** [comment]
Thank you so much, it's now working !
