### ISSUE TITLE
Improve RealmChangeListener to allow process changed data in Realm

### ISSUE THREAD

**Issue by mshusek** [realm/realm-java#1378]
When we use RecyclerView or we want reload view under certain conditions default onChange is not sufficient. Now, in RecyclerView we have to reload visible rows so it is not a optimal solution. Moreover, we can not use animation when item is delete or insert to our model.
 
I think better sollution will be implementing something like that:
 ContentObserver.ModelChangeListener() 
{

            @Override
            public void onModelChanged() { 
            } 

           @Override
            public void onModelUpdated(Object obj) {
            }

            @Override
            public void onModelDeleted(Object obj) {
            }

            @Override
            public void onModelInserted(Object obj) {

            }

        };

**Comment by beeender** [comment]
Hi! The fine grained notifications are very high on our priority list. There is a issue #989 tracking it.
I will update you comments there for easy tracking, and close this issue now. You can subscribe that one to see progress.

Thanks a lot for you feedback!
