### ISSUE TITLE
Realm column indexes issue. How to reorder? 

### ISSUE THREAD

**Issue by svasquezm** [realm/realm-java#1384]
I've used Realm Since 6 months ago and never have to use Migrations, until now.
In order to represent the issue, I'll explain the issue with generic classes.

Before the Migration (version 0), I have the following class

```
public class AModel extends RealmObject {
 private String field_a;
 private String field_b;
 private String field_c;

 // Getters and setters
}
```

After the migration, the modified version of **AModel** class is (version 1)
```
public class AModel extends RealmObject {
 private String field_a;
 private String field_d; // The new field
 private String field_b;
 private String field_c;

 // Getters and setters
}
```

So, after apply the migration, when do some *getField_d()* or *setField_d()* I get a **Fatal signal 11 (SIGSEGV), code 1** error causing App crashes.

After doing some test, I've realize that reording the fields like this
```
public class AModel extends RealmObject {
 private String field_a;
 private String field_b;
 private String field_c;
 private String field_d; // The new field

 // Getters and setters
}
```
The app doesn't crashes on *getField_d()* or *setField_d()* calls.

Right now the app runs ok, but I would like to know if there is a way to **reorder column indexes** of the fields (to put field_d after field_a, not at the end of fields declaration).

Thank you very much.

**Comment by beeender** [comment]
Can you please share your code of migration ?

**Comment by svasquezm** [comment]
Sure.

```
public class Migrations implements RealmMigration {

    @Override
    public long execute(Realm realm, long version) {
        // Version 0 code 
        if(version == 1){
            Table aTable = realm.getTable(AModel.class);
            aTable.addColumn(ColumnType.STRING, "field_d");
            version++;
        }
  }
}
```

**Comment by beeender** [comment]
How did you handle version 0 -> version 1?

**Comment by svasquezm** [comment]
Actually in version 0, I don't touch AModel table. The only block which manipule AModel table is the if(version == 1){}.

**Comment by beeender** [comment]
Did you set `schemaVersion` before? if you didn't, for the old app, the schemaVersion should be 0. And the version in `execute(Realm realm, long version)` is 0 as well... Which means your block in `version == 1` is not executed... Can you help to confirm this?

**Comment by svasquezm** [comment]
Yes, schemaVersion() was called in the previous app version (with 0),
 I put *version++* in  block marked by **// Version 0 code** comment..

**Comment by beeender** [comment]
Then the `version == 1` is not actually executed. version here means the realm version before migration. on the phone with previous version of the app installed, when running the new version of app the first time before migration, version should be 0.

**Comment by beeender** [comment]
@svasquezm Have you solved your problem? Anymore help needed?

**Comment by svasquezm** [comment]
I've solved the my problem changing the order of the fields, as question shows.
