### ISSUE TITLE
can't use on API 8

### ISSUE THREAD

**Issue by skyhigh123** [realm/realm-java#1386]
You shouldn't use isEmpty() to check String object, because isEmpty() added from API 9
http://developer.android.com/reference/java/lang/String.html#isEmpty()

**Comment by cmelchior** [comment]
Realm currently support back to API 9, which is also stated in our documentation: https://realm.io/docs/java/latest/#prerequisites

While we ideally would want to support as far back as possible we also has to weigh that against code complexity and maintainability. Right now Froyo has 0.3% of the market: https://developer.android.com/about/dashboards/index.html

Do you have a use case where supporting this is needed?

**Comment by cmelchior** [comment]
I hope the above answers your question. Otherwise feel free to reopen.
