### ISSUE TITLE
Snapshot releases have stopped updating

### ISSUE THREAD

**Issue by diegomontoya** [realm/realm-java#1392]
http://oss.jfrog.org/oss-snapshot-local/io/realm/realm-android/0.83.0-SNAPSHOT/

Last snapshot is on 8/11.

**Comment by cmelchior** [comment]
Hi @diegomontoya Thank you for notifying us. We had some problems with our CI system. Will look into getting it fixed ASAP

**Comment by cmelchior** [comment]
SNAPSHOT releases should now work again.
