### ISSUE TITLE
isValid() doesn't behave as expected

### ISSUE THREAD

**Issue by markini** [realm/realm-java#1393]
I'm using `realm-android:0.83.0-SNAPSHOT`.

When I run this simple code:
``` java
Realm realm = Realm.getInstance(this);
realm.beginTransaction();
Dog myDog = realm.createObject(Dog.class);
myDog.setDogName("myDog");
realm.commitTransaction();

realm.beginTransaction();
myDog.removeFromRealm();
realm.commitTransaction();

Timber.e("myDog still valid: " + myDog.isValid());
```

`myDog.isValid()` throws an `IllegalStateException`

```java
     Caused by: java.lang.IllegalStateException: Object is no longer managed by Realm. Has it been deleted?
            at io.realm.internal.InvalidRow.getStubException(InvalidRow.java:180)
            at io.realm.internal.InvalidRow.isAttached(InvalidRow.java:171)
            at io.realm.RealmObject.isValid(RealmObject.java:107)
```

How can I check if an object was removed from realm?
Or does my little example not work because I'm calling this function from the same thread? However, I don't think that `isValid()` should ever throw such an exception.

**Comment by kneth** [comment]
@markini Thanks for catching this bug. I have created a bug fix for it.

**Comment by kneth** [comment]
The fix gas been merged. You can try it using our snapshot releases (see `README.md` for details).
