### ISSUE TITLE
missing field type getter of DynamicRealmObject

### ISSUE THREAD

**Issue by zaki50** [realm/realm-java#1394]
In order to access model object by generic way, we have to know the type of each field.

I'd like to write as follows.
```
DynamicRealmObject obj = ...;
for (String fieldName : obj.getFieldNames()) {
    switch(obj.getFieldType(fieldName)) { // getFieldType(String) is missing
        case BOOLEAN:
            boolean b = obj.getBoolean(fieldName);
            // do something
            break;
        case STRING:
            String str = obj.getString(fieldName);
            // do something
            break;
        ...
    }
}
```

**Comment by cmelchior** [comment]
Yes, that is a problem. It does however mean we need to expose the underlying Realm types in the binding which was something we hoped to avoid.

We have been discussing adding a generic `get()` method as well:

```
Object value = obj.get(field);
```

Would this also solve your use case?

**Comment by cmelchior** [comment]
In any case it is a use case we should have a solution for when #1200 is implemented

**Comment by zaki50** [comment]
generic get() method is acceptable for my use case.

I'm writing a code to export all models into CSV file.

**Comment by cmelchior** [comment]
I am merging this issue into #1369. Closing this now.
