### ISSUE TITLE
I get Fatal signal 11 error when i call  recursive delete from my fragment.

### ISSUE THREAD

**Issue by aercanozcan** [realm/realm-java#1397]
```
deleteForm(formObject,getActivity);
```

Fatal signal 11 (SIGSEGV) at 0x00000094 (code=1), thread 6200 (om.infoline.ats)

the strange thing is : it does not  cause that error when i call this from an onClick inside of a listview item with
RealmBaseAdapter.getItem(position).

Method TLDR: it  deletes the FormObjects with cascade using for loop and recursion. It marks all forms as deleted then deletes all marked forms.

```
public static void deleteForm(FormObject formObject,Context context){
        Realm realm = Realm.getInstance(context);
        realm.beginTransaction();
        recursiveFormDelete(realm, formObject);
        setDeletedSingleForm(realm, formObject);
        realm.where(FormObject.class).equalTo("deleted",true).findAll().clear();
        realm.commitTransaction();
        realm.close();
    }

    /**
     * deletes all children forms as a tree.
     * @param realm
     * @param formObject
     */
    public static void recursiveFormDelete(Realm realm,FormObject formObject){
        RealmResults<FormObject> results=realm.where(FormObject.class).equalTo("firstVisitFormId",formObject.getFormId()).findAll();
        int size= results.size();

        for(int i =0 ; i< size;i++){
            FormObject item = results.get(i);
            if(realm.where(FormObject.class).equalTo("firstVisitFormId",formObject.getFormId()).count()>0){
                recursiveFormDelete(realm,item);
            }
            setDeletedSingleForm(realm,item);
        }
    }

    /**
     * Removes options questions and formpages of this form. and marks the form as deleted.
     * @param realm
     * @param formObject
     */
    public static void setDeletedSingleForm(Realm realm, FormObject formObject){
        String id=formObject.getFormId();
        realm.where(Question.class).equalTo("formId",id).findAll().clear();
        realm.where(Option.class).equalTo("formId",id).findAll().clear();
        realm.where(Answer.class).equalTo("formId",id).findAll().clear();
        realm.where(Answer.class).equalTo("parentFormId",id).findAll().clear();
        formObject.getFormPages().clear();
        formObject.setDeleted(true);
    }
```

**Comment by kneth** [comment]
@aercanozcan Do you use links between the classes?

**Comment by aercanozcan** [comment]
I didn't quite get what you mean by links between classes.

In case you are asking about object relations, I both use RealmLists and some id fields(like foreign key) for easy query purposes.

**Comment by kneth** [comment]
@aercanozcan Yes, I was asking about relationships. We have been investigating a similar issue (removing a single object) where relationships were involved too.

**Comment by aercanozcan** [comment]
just to be more clear: I get this error when i call this method just before removing a fragment (by delegating Activitiys onBackPressed() ). I achieved to avoid it ( or decreased the occurrence) by calling method handler by postDelayed. Maybe it can be related to "sharing realm with threads"  issues. 
thank you for response.

**Comment by kneth** [comment]
Can you share your code (if only privately, send an email to help@realm.io)? We try to give a proper error message if you try to access Realm object on another thread, and we would like to see if you have found a corner case where our logical isn't sufficient.
