### ISSUE TITLE
Realm.addChangeListener doesn't work on background threads

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#1401]
If you do 

```
new Thread(new Runnable() {
  public void run() {
    Realm realm = Realm.getDefaultInstance();
    realm.addChangeListener(listener)
    // ...
  }

}).start();
```

on a non-looper thread. That change listener will never be called unless you execute a transaction on that thread.

That behaviour seems a bit strange. The problem is that we are triggering onChange after updating the the Realm on looper-threads. That isn't possible on non-looper threads as there is no point in time updating the Realm behind users back would make sense.

We should consider doing one of the following:

1) Prevent people from adding change listeners on a non-looper thread (throw exception). People would have to notify these threads in some other way.

2) Document the behaviour better. 

3) Call onChange on non-looper threads, but without updating the Realm on that thread first.

4) Something else.... ?

**Comment by beeender** [comment]
1) :+1: 

3) Is there a way to do that? If the transaction happened in other threads.

**Comment by cmelchior** [comment]
I think so yes. Currently we keep track of handlers from other threads. That should be easily extendable to handle threads as well (I think)

**Comment by emanuelez** [comment]
a combination of 1) and 2) :+1:

**Comment by cmelchior** [comment]
Solution after discussion:
1) Calling `refresh()` should trigger listeners. It currently doesn't.
2) Update documentation for `addChangeListener` to document behaviour on Looper/non-looper threads.
3) Don't throw

**Comment by nhachicha** [comment]
:+1:  for a combination of 1) & 2) 
not throwing seems like failing silently, we shouldn't add a listener if we can't honour the contract. _fail fast_

another possibility is to use event bus, but generally we should avoid global state...
