### ISSUE TITLE
rxJava and Realm. 

### ISSUE THREAD

**Issue by TheRishka** [realm/realm-java#1402]
Hi! I'm using realm 0.82.1 and I was following this blogpost: https://realm.io/news/using-realm-with-rxjava/
Everything was quite well, until this part of code:
```Java
    @Override
    public void call(final Subscriber<? super T> subscriber) {
        final Realm realm = fileName != null ? Realm.getInstance(context, fileName) : Realm.getInstance(context);
        subscriber.add(Subscriptions.create(new Action0() {
            @Override
            public void call() {
                try {
                    realm.close();
                } catch (RealmException ex) {
                    subscriber.onError(ex);
                }
            }
        }));
```

Here i'm catching `Realm instances can only be closed on the same thread they were created` error!

I've googled quite much and didn't find any help for this. As I see in patchlogs, in 0.82.0 was added such thing: ` * Closing realm on another thread different from where it was created now throws an exception.` 

Is there any fix for this or I will have to stay on 0.81 forever? :(

**Comment by kboyarshinov** [comment]
@TheRishka On what thread do you observe events?

**Comment by TheRishka** [comment]
@kboyarshinov 
Observable is creating in this part of code:
```Java
public static <T extends RealmObject> Observable<T> object(Context context, final Func1<Realm, T> function) {
        return Observable.create(new OnSubscribeRealm<T>(context) {
            @Override
            public T get(Realm realm) {
                return function.call(realm);
            }
        });
    }
```
Just like in blogpost. I've tried to add `.subscribeOn(Schedulers.newThread()).observeOn(AndroidSchedulers.mainThread()` but it didn't work. The same error appeared.

**Comment by andrewCleverUA** [comment]
try to remove observeon() and try again

**Comment by kboyarshinov** [comment]
@TheRishka if you request and observe events in the same thread it should not be a problem. Since realm has one restriction - realm objects can not be passed across threads, you cannot use `subscribeOn` and `observeOn` operators directly. One option is to convert realm object to your own thread-safe POJO object - this is what blog post suggests to do. Check if you follow these rules.

Anyway these types of questions are better to be posted on StackOverflow than here. Follow RxJava native support in #865.

**Comment by kneth** [comment]
I'm closing the issue. As @kboyarshinov mention, StackOverflow might be a better place to discuss and we have an open issue to follow.
