### ISSUE TITLE
Support for join query 

### ISSUE THREAD

**Issue by lenguyenthanh** [realm/realm-java#1404]
I have a Person object and it has a RealmList of phone numbers. How can I search a person by a phone number? I'm using Realm for my Android project.

**Comment by beeender** [comment]
Try this:
```
RealmResults<Person> results = realm.where(Person.class).equalTo("phoneNumbers.number", "1234567").findAll();
```

**Comment by lenguyenthanh** [comment]
Thanks @beeender! You've made my day
