### ISSUE TITLE
Realm cant not working with NewRelic SDK under the AndroidVersion 5.0

### ISSUE THREAD

**Issue by wonTonx** [realm/realm-java#1413]
When I try to bulit in the NewRelic SDK into my project, it will have the error which is can't find the proxyclass of my own RealmObject when the Android version is below 5.0, I can't not find which part is wrong

and I'v try to use the different of the NewRelic SDK, and the newset version of realm but it didn't help

**Comment by beeender** [comment]
@wonTonx Are you using android studio? Any errors happened during the gradle build?

Can you please share your `build.gradle` here?

**Comment by kneth** [comment]
I'm closing the issue. @wonTonx please reopen if still relevant.
