### ISSUE TITLE
Handling unique (PrimaryKey) constraint violations

### ISSUE THREAD

**Issue by dantman** [realm/realm-java#1416]
Right now Realm throws a generic `io.realm.exceptions.RealmException` with the message "Primary key constraint broken. Value already exists: ..." when you try and insert an object that already exists.

The typical ACID way to handle this (and display an "Already exists" message, etc...) is to catch an exception specific to unique constraint violations.

So unless Realm has another optimum pattern for handling constraint violations I think the exception thrown on constraint violation should be replaced with one more specific.

**Comment by cmelchior** [comment]
Currently the only reason for not having a specific `PrimaryKeyConstraintException` was to keep the number of classes as low as possible, but I can see why being able to detect it better could be useful.

**Comment by xbroak** [comment]
+1 Please include this ASAP, i'm not sure how else we are supposed to handle such a situation?
