### ISSUE TITLE
Support accents at queries

### ISSUE THREAD

**Issue by ppamorim** [realm/realm-java#1418]
Hi!
I need the support of queries with accents in Strings, but I think:
We would remove the accents of the filter(the text searched) and filter this text at Realm.
But the columns can have accents in the text and I can't filter. It's look like the caseSensitive, look like AccentSensitive...
Any help?

I have implemented this workaround:

    ArrayList<Object> objects = QueryObject.getAllObjects(context); //Returns 1200 items.

    ArrayList<Object> filteredObjects = new ArrayList<>();
      for(Object object : objects) {
         f(stringUtils.removeAccents(object.getTitle()).toLowerCase().contains(filtered) ||
            stringUtils.removeAccents(object.getCity()).toLowerCase().contains(filtered) ||
            stringUtils.removeAccents(object.getState()).toLowerCase().contains(filtered)) {
          filteredObjects.add(object);
        }
      }

But this takes 2-3 seconds! :D Unbelievable!

**Comment by emanuelez** [comment]
If I understand correctly you have something like "perché" stored in your Realm and you want to be able to retrieve the object even when looking for "perche" (without the accent). This is called a diacritic search and it can be solved storing a normalized version of the string in your Realm.

For more informations you can refer to this SO question: http://stackoverflow.com/questions/28294809/get-diacritic-insensitive-results-from-realm-database-query
