### ISSUE TITLE
Realm Find Queries Result in Empty Objects

### ISSUE THREAD

**Issue by dkpalmer** [realm/realm-java#1423]
When doing find queries for objects I'm getting "empty" objects (non-null, but not populated). However, in the debugger I can see the data for the object in the object description (see below). I've also verified the data is there using the Realm Browser. I've tried different find queries, querying with filter criteria, using the same Realm object for inserts/queries, using different Realm objects for inserts/queries, refreshing the Realm, etc.

I have sample code and a screenshot up at http://stackoverflow.com/questions/32215733/realm-find-queries-result-in-empty-objects

**Comment by beeender** [comment]
Hi!
We just answered it on SO!
I am closing this issue now, let's discuss it there.
Thanks!
