### ISSUE TITLE
Support to FlatBuffers

### ISSUE THREAD

**Issue by ppamorim** [realm/realm-java#1426]
It will be amazing to implements the support to FlatBuffers, it can be possible?

ByteBuffer -> RealmObject

**Comment by bmunkholm** [comment]
Thanks for the input!
Could you be a bit more specific as to your use case?

**Comment by ppamorim** [comment]
@bmunkholm It's look like the Json Mapper, but without mappers! FlatBuffers deserialize byte[] to Java Object. If you want understand more, read this: https://google.github.io/flatbuffers/md__white_paper.html

**Comment by ppamorim** [comment]
@beeender ( ͡° ͜ʖ ͡°)

**Comment by kneth** [comment]
I'll label it as an enhancement but I can't when we will implement it.

**Comment by bmunkholm** [comment]
@ppamorim : I'm aware of FlatBuffers. I'm just asking how you would like it integrated with Realm? If you would just like to be able to store a FlatBuffer in Realm, then you can already do that in a byte[]. Would appreciate if you would elaborate the integration, maybe API and use cases you envision.

**Comment by cmelchior** [comment]
Closing as we already support `byte[]` and it is unclear what other kind of support is envisioned
