### ISSUE TITLE
Realm when app in background

### ISSUE THREAD

**Issue by bangarharshit** [realm/realm-java#1427]
Hi,
  We are working on a chat app where we insert our incomng chat messages in realm and the UI is rendered from realmbaseadapter. In chat app we still continue with our singleton listener if our app is in background.  What can be a good pattern to use it? Currently I am closing the realm in ondestroy and if the app goes in background it's pause will be called but chances are there if the activity will be destroyed. Should I use a started service or application context for realm?
Let me know if you want to see code sample for the pattern.
Thanks,
Harshit

**Comment by kneth** [comment]
We would be happy to see a code sample to gain insight to the pattern.

**Comment by bangarharshit** [comment]
public class ChatConnectionService {

    private WeakReference<XMPPReceiver> xmppReceiver;

**Comment by bangarharshit** [comment]
Here is the pattern:
public class XMPPService extends Service implements INetworkReceiver {
private XMPPConnection mXmppConnection;
private XMPPMethods xmpp;
private DatabaseHandler db;
private UserDetails user;
private SmackAndroid smack;
private Registrations registrations;
private static final String TAG="XMPPService";

@Override
public IBinder onBind(final Intent intent) {
    return new LocalBinder<XMPPService>(this);
}

@Override
public void onCreate() {
    super.onCreate();
    registrations=new Registrations(getApplicationContext());
    xmpp=XMPPMethodsImpl.getInstance(getApplicationContext());
    db=DatabaseHandler.getInstance(getApplicationContext());
    if(db!=null){
        user=db.getUserDetails();
    }
    createConnection();     
}

public void createConnection()
{
    ConnectionConfiguration connConfig = new ConnectionConfiguration(
            AppConstants.HOST, AppConstants.PORT);
    connConfig.setSASLAuthenticationEnabled(false);
    connConfig.setDebuggerEnabled(true);
    connConfig.setReconnectionAllowed(true);
    connConfig.setSecurityMode(SecurityMode.disabled);
    mXmppConnection = new XMPPConnection(connConfig);


    Thread thread=new Thread(new Runnable() {
        private Handler handler=new Handler();
        @Override
        public void run() {

            try {
                if(mXmppConnection!=null && !mXmppConnection.isConnected()){
                    mXmppConnection.connect();
                    Log.i("XMPPServiceAsync",
                            "Connected to " + mXmppConnection.getHost());
                    xmpp.setConnection(mXmppConnection);
                }
            } catch (XMPPException e) {
                e.printStackTrace();
            }

            //mXmppConnection.addConnectionListener(new XmppConnectionListener());

            handler.post(new Runnable() {

                @Override
                public void run() {
                    try {
                        if(db!=null && user!=null && mXmppConnection!=null && !mXmppConnection.isAuthenticated()){
                            if(user.getUserName()!=null && !user.getUserName().isEmpty()){
                                mXmppConnection.login(user.getUserName(), "Tp@!");
                                xmpp.setPresence(2, mXmppConnection);
                                xmpp.setConnection(mXmppConnection);
                                Log.i("XMPPServiceAsync",
                                        "Logged in as " + mXmppConnection.getUser());

                            }
                        }
                    }catch (IllegalStateException e) {
                        e.printStackTrace();
                    } catch (XMPPException ex) {
                        ex.printStackTrace();
                    }


                    if(mXmppConnection.isConnected()){
                        xmpp.rejoinGroups();
                        registrations.registerMessageListener(mXmppConnection);
                        registrations.registerPacketListener(mXmppConnection);
                        registrations.registerMultiUserInvitationListener(mXmppConnection, db, user);
                        registrations.registerPingListener(mXmppConnection);
                    }

                }
            });
        }
    });

    if (thread.getState() == Thread.State.NEW )
    { 
        Log.i(TAG,"Thread State: "+ thread.getState()+"");
        thread.start(); 
    } 
}

@Override
public int onStartCommand(final Intent intent, final int flags,
        final int startId) {
    //rejoining rooms
    try{
        Log.v("XMPP Connection before rejoining",mXmppConnection+"");
        if(mXmppConnection.isConnected()){
            registrations.registerMessageListener(new MessageListener(){
           
                   void onReceiveMessage() {
                          // 1. Should we use service or application context. Clearly activity may or may not be alive?
                          Realm realm = Realm.getInstance(Application.getApplicationContext)
                          // Updating the db and our UI is updated through it.
                   }
           });
            registrations.registerPacketListener(mXmppConnection);
            registrations.registerMultiUserInvitationListener(mXmppConnection, db, user);
            registrations.registerPingListener(mXmppConnection);
        }
    }catch(Exception e){
        e.printStackTrace();
    }

    return Service.START_STICKY;
}


@Override
public boolean onUnbind(final Intent intent) {
    return super.onUnbind(intent);

}


@Override
public void onDestroy() {
    super.onDestroy();

}

@Override
public void reEstablishConnection() {
    createConnection();
}

**Comment by bangarharshit** [comment]
Also since most of the networks calls ideally should be from service - https://www.youtube.com/watch?v=xHXn3Kg2IQE and not from activity do you also have recommendation on how to make it talk to webservice REST? In all your examples you have a realm directly into activity which is great for updating UI but things are not clear about the realm which is supposed to be updated from the realm  (you do have an example with async task but that is definitely not a great pattern for realm). It will be great if you can recommend a similar pattern for realm for Rest.

**Comment by kneth** [comment]
Is your service running as a separate process? Accessing a Realm from multiple processes isn't yet support but we are working on it (see #1300).

**Comment by bangarharshit** [comment]
Thanks. I was using a different process with  aidl. Since it was not a requirement moved it to the same process. Just one final question in long running service (foreground or sticky) is it okay to keep the connection alive for a long time. For activity in oncreate and ondestroy we open and close the connection. For service I am doing the same. I have two services one foreground and one sticky. Or you recommend opening a new realm every time I receive a message, insert and close it.

**Comment by kneth** [comment]
Realms are using native resources, and closing Realms will free allocated resources. When to close a Realm depends on the use case. You can get more insight to the topic in the (documentation)[https://realm.io/docs/java/latest/#realms] (see "Closing Realm Instances").

**Comment by kneth** [comment]
I'm closing the issue. Don't hesitate to open a new issue if you have questions.
