### ISSUE TITLE
Realm query equalTo() returns all sometimes

### ISSUE THREAD

**Issue by phiphuc89** [realm/realm-java#1428]
I have 2 cyclerviews, channels and playlists. When I select a channel, I want to get playlists of selected channel only.
```java
realmResults = realm.where(Playlist.class).equalTo("channelId", channel.getId()).findAll();
```
but sometimes, it returned all playlists in Realm. When I pressed back, and select that channel again, it returned right results.

Can you help me? Thank.

**Comment by beeender** [comment]
@phiphuc89 Is `channelId` the `@PrimaryKey` in your `Channel` model? Would you please set a breakpoint to see what are in the `realmResults` when the problem happens?

**Comment by phiphuc89** [comment]
Oh, it's my stupid mistake, when playlists of selected channel not available, I'll get it from server and copy to realm, after that, get realm results by 

```java
realmResults = realm.where(Playlist.class).findAll();
```
instead of 

```java
realmResults = realm.where(Playlist.class).equalTo("channelId", channel.getId()).findAll();
```

**Comment by beeender** [comment]
:beers: Problem solved
