### ISSUE TITLE
Realm isClosed method

### ISSUE THREAD

**Issue by mshusek** [realm/realm-java#1431]
Hi, i noticed there is no method to check my Realm instance is still open/valid. There is no problem when i have RealmObject somewhere because it have "isValid" method so i can call that. But if i have RealmResults or RealmList this validation is not available.
Possible associate with
https://github.com/realm/realm-java/issues/697

**Comment by kneth** [comment]
We can add `isValid` to `RealmResults` and `RealmList` as it sounds like what you really need. But `isClosed` on a `Realm` is definitely doable too.

**Comment by mshusek** [comment]
Now i can see is method checkIfValid is in Realm object but is checked as "protected" so i can create custom Realm object with method isValid. I think issue can be closed.
Lazy snippet:
public MyRealm extend Realm {
...
public boolean isValid(){
try{
checkIfValid();
}catch(IllegalStateException e)
{
return false;
} 
return true;
}
}

**Comment by cmelchior** [comment]
We should definitely add ```RealmResults.isValid``` and ```RealmList.isValid```. 

```Realm.isClosed``` might make sense, but I am not entirely certain what use cases people are after, because even though one instance is closed other threads might still keep the file reference open. ```Realm.isValid``` probably fit the semantics of the other ones better. ```Realm.isClosed``` could then be used to detect if the realm file is actually fully closed.

**Comment by mshusek** [comment]
Yes, i think this is great idea for isClosed(), when we want to delete realm file all instance should be closed and if developer don't create counter he get exception. Maybe this is good point to create method closeRealmInstances with cancel all pending transaction and close realms?

**Comment by cmelchior** [comment]
I would be really hesitant to add something like `forceClose()`, mostly because it will with almost certainty also break something else in your app.

**Comment by mshusek** [comment]
Generally little that is not related to the issue, but method deleteRealmFile for me should have boolean closeCurrentRealmInstances (default value = false), but this is only my opinion.
I tottaly agree with you, forceClose should't be public and can cause a lot of bugs inside application and devs can misused this method.

**Comment by cmelchior** [comment]
This task is the following:

- add `isClosed` to Realm
- add `isValid()` to RealmResults and RealmList

**Comment by dalinaum** [comment]
@zaki50 Why is it reopend? Did #1550 close this issue?

**Comment by zaki50** [comment]
@dalinaum Because this issue requires 2 tasks listed in last @cmelchior 's comment.
I've done only 1st item.

**Comment by zaki50** [comment]
@cmelchior how about RealmQuery?

**Comment by cmelchior** [comment]
Technically yes. It would be a really strange use case, which why probably why I forgot it.
