### ISSUE TITLE
Empty DB after application restart

### ISSUE THREAD

**Issue by HellAvalor** [realm/realm-java#1432]
Hi everyone.
I've ununderstandable problem with storing.

1. I`m getting instance of realm in application onCreate
like realm = Realm.getInstance(this);
2. in Activities getting link to that realm from application reading and writing. Everything going fine and realm has data.
3. Closing application from processes, start it again and trying to get any data from realm - but it`s empty.

I`m not deleting realm, not clearing it, not clearing cache. So what is it could be?
realm version io.realm:realm-android:0.82.1

**Comment by bmunkholm** [comment]
Sorry to hear that! Could you possibly share your project? maybe privately if needed to help@realm.io. That would make it super simple to help you. Alternatively try to share all relevant Realm code here.
Thanks

**Comment by HellAvalor** [comment]
Sorry but application is under NDA and very big...

but i`ll try

in CustomApplication 
```java
    private Realm realmDB;
    public void onCreate() {
        super.onCreate();
        realmDB = Realm.getInstance(this);
    }

    public Realm getRealmDB() {
        return realmDB;
    }
```
in first activivty
```java
       Realm realm = ((CustomApplication) getApplication()).getRealmDB();
        realm.beginTransaction();
        realm.copyToRealm(theme);
        realm.commitTransaction();
```
theme is not null class

in other place 
```java
realm = ((CustomApplication) getApplication()).getRealmDB();
realm.where(CustomizeTheme.class).findFirst()
```

**Comment by cmelchior** [comment]
Given the code you have provided it should work, so most likely you are deleting the object in some other  piece of the code. 

Have you tried putting a test directly into your custom application to check? Something like:

```
public class MyApplication extends Application {
 private Realm realmDB;
    public void onCreate() {
        super.onCreate();
        realmDB = Realm.getInstance(this);
        CustomizeTheme ct = realm.where(CustomizeTheme.class).findFirst();
        if (ct == null) {
          Log.i("Test", "No theme");
        } else {
          Log.i("Test", "Found theme");
        }
    }

    public Realm getRealmDB() {
        return realmDB;
    }
}
```

**Comment by HellAvalor** [comment]
I'll test it on Monday

**Comment by HellAvalor** [comment]
3152-3152/? I/Test﹕ No theme

**Comment by cmelchior** [comment]
Hi @HellAvalor 

Some places to look

```RealmObject.removeFromRealm()```
```RealmList.remove()```
```RealmResults.remove()```
```Realm.clear()```
```Realm.deleteRealm()````

Also if you have some code that is interacting with your apps files. Realm will save the file in ```data/data/<packagename>/files/default.realm```.

**Comment by HellAvalor** [comment]
I found problem... I`m clearing files from data/data/<packagename>/files/ directory after init of realm and RealmDB is working from memory but not storing anything to disk because of no file there.

So it was hard to find problem, because that is not directly connected to RealmDB. 

it was like 

```java
public class MyApplication extends Application {
 private Realm realmDB;
    public void onCreate() {
        super.onCreate();
        realmDB = Realm.getInstance(this);
       
        String sdcard = getFilesDir().getPath();

        File fileList = new File(sdcard);

        // so we can list all files
        File[] filenames = fileList.listFiles();

        // loop through each file and delete
        for (File tmpf : filenames)
            tmpf.delete();
    }
}
```

Thanks.

**Comment by cmelchior** [comment]
Ok, great you found it. 

A few notes about your code. `getFilesDir()` is actually not on the SDCard but a private folder only available to your app. Also there is a `getCacheDir()` ( http://developer.android.com/reference/android/content/Context.html#getCacheDir() ) if you want to store some temporary files.

**Comment by cmelchior** [comment]
@HellAvalor I'll close this issue now. Feel free to open another use if you run into any other problems with Realm.

**Comment by kayanalmeida** [comment]
Hi guys, I'm having the same issue, but in my case, after a new app session I can see three files:
The difference is that I'm restoring a database (Created from another app, with some States and cities from my country) from a raw file, following the migration example.
In the first session, everything works fine, I use all objects from my database but when a new application session is created, nothing is there anymore. 
Could somebody help me and tell what am I doing wrong??
Thank you very much
Also noticed that my states and cities are persisted, but everything else isn't! And I'm pretty sure I don't substitute the `default.realm` file again!
Files inside App dir:
```
.Fabric
default.realm
default.realm.lock
```

Here's my Application class
```
public class MyApplication extends Application {

    private static String AUTH_TOKEN = "";

    @Override
    public void onCreate() {
        super.onCreate();
        MyDB.init(this);
        String appPath = getFilesDir().getPath();

        File fileList = new File(appPath);

        // so we can list all files
        File[] filenames = fileList.listFiles();
        System.out.println(Arrays.toString(filenames));
        initUser();
        checkFirstAppOpen();
    }

    private void checkFirstAppOpen() {
        SharedPreferences preferences = getSharedPreferences(PreferencesHandler.APP_PREFERENCES, 0);
        boolean firstTime = preferences.getBoolean(PreferencesHandler.FIRST_TIME, true);
        if (firstTime) {
            SharedPreferences.Editor editor = preferences.edit();
            editor.putBoolean(PreferencesHandler.FIRST_TIME, false);
            editor.apply();
            copyBundledRealmFile(this.getResources().openRawResource(R.raw.defaultdb), "default.realm");
        }
    }

    private String copyBundledRealmFile(InputStream inputStream, String outFileName) {
        try {
            File file = new File(this.getFilesDir(), outFileName);
            FileOutputStream outputStream = new FileOutputStream(file);
            byte[] buf = new byte[1024];
            int bytesRead;
            while ((bytesRead = inputStream.read(buf)) > 0) {
                outputStream.write(buf, 0, bytesRead);
            }
            outputStream.close();
            return file.getAbsolutePath();
        } catch (IOException e) {
            e.printStackTrace();
        }
        return null;
    }
}
```
