### ISSUE TITLE
Realm.io IllegalStateException

### ISSUE THREAD

**Issue by slidenerd** [realm/realm-java#1436]
hi, first of all awesome work with your library. I saw this issue by 2 other people and it didn't help me much knowing what was going wrong there
![snap 2015-08-29 at 05 26 43](https://cloud.githubusercontent.com/assets/5139030/9559302/c4c4a2ea-4e0e-11e5-909e-5aec8fb0d5c9.png)
Here's an error I get
The code basically uses Realm to add items to a RecyclerView.Adapter instance and delete items on swipe, the super class like this
![snap 2015-08-29 at 05 29 48](https://cloud.githubusercontent.com/assets/5139030/9559314/004e55a4-4e0f-11e5-90a5-a0b0fd3b8b1c.png)
The superclass maintains a realm instance which I have not closed anywhere since I am not sure about closing Realm instance, they give me an exception if I try doing it, will research more on it.

The subclass looks like this
![snap 2015-08-29 at 05 31 00](https://cloud.githubusercontent.com/assets/5139030/9559332/28b940da-4e0f-11e5-8b98-6cdb46bce64b.png)

The delete method above is automatically called whenever the user swipes the item from left to right on the screen

![snap 2015-08-29 at 05 31 53](https://cloud.githubusercontent.com/assets/5139030/9559335/482abfb6-4e0f-11e5-92e5-6c8563b7450e.png)
The add is called when the person enters some data inside the editText, the exception is not triggered if I only add items

![testgif](https://cloud.githubusercontent.com/assets/5139030/9559344/7e04d61c-4e0f-11e5-9b41-f18726e1c2a9.gif)

The exception is triggered when I only remove items
![testgif](https://cloud.githubusercontent.com/assets/5139030/9559354/c384ed58-4e0f-11e5-94b9-8d3df94d14fa.gif)

I am not using threads, asynctask, handlers, runnables anywhere, so any hint is highly appreciated and as you notice, it is not triggered on every delete

[UPDATE 1] I saw this https://github.com/realm/realm-java/blob/master/examples/adapterExample/src/main/java/io/realm/examples/realmadapters/AdapterExampleActivity.java and am trying out the long click technique done here currently

[UPDATE 2] I just want to display a set of results loaded with RealmResults but be able to modify them by adding an item of type T or removing an item of type T and call the appropriate notifyXXX methods of the Recycler Adapter, if it isn't too much to ask, I am sure a lot of people are facing this issue from what I read in your issues list, would it be possible for you to add a gist with an abstract adapter that has the additions, removals handled with Realm for a RecyclerAdapter, the implementors can simply override the onCreateViewHolder and onBindViewHolder and get their work done while the parent manages all the hard stuff.

Thanks in advance

**Comment by beeender** [comment]
@slidenerd Beautifully formatted issue!!! 

I saw you are calling `notififyItemRemoved(position)`, how does that function look like? And are you using `RealmResults` as the data source for adapter? Is it possible to show your source code of the adapter?

**Comment by slidenerd** [comment]
Thank you very much, since people post issues on my lib, I know how much I hate to read unformatted code.



The onSwipe is triggered with the ItemTouchHelper attached to the recyclerview , all i have to do is implement the OnSwipeListener and when i swipe an item, it automatically calls the onSwipe method in my parent adapter, Coming to the point, here is the adapter I am using
this as the parent abstract adapter class http://pastebin.com/SpU2jS33
this as the child adapter http://pastebin.com/GTSwzdhh
I would highly appreciate if you can make a gist with an abstract adapter for a recyclerview that lets people add and delete items as well with realmresults, my current code is bad because of the arraylist and realmresults being used at the same time, however due to shortage of time, there wasnt much i could do, thanks in advance for your response

**Comment by beeender** [comment]
@slidenerd The biggest reason we don't supply a adapter for the `RecyclerView` right is because of this missing finegrained notification. See https://github.com/realm/realm-java/issues/989 . Since we based on current Realm's notification system, it is hard to know which index of the `RealmResults` is changing.

I checked your code, my guessing is something is not right in:

```
@Override
public final void onSwipe(int position) {
    delete(mRealm, mListData.get(position - getHeaderCount()), position);
}
```

Can you please debug this function a bit to see if the object and index matches when they are passed to `delete`?

**Comment by slidenerd** [comment]
Hi, I have fixed the issue myself, I made an abstract adapter and a concrete adapter that does the job, in case anyone encounters a similar issue in the future , feel free to refer them to this thread
1) here is my abstract adapter http://pastebin.com/QycnN2WK
2) here is my concrete adapter that lets you add and delete items on swipe from recyclerview with realm http://pastebin.com/PBwAd5Tv
3) here is my code for swipe to dismiss implementation on recyclerview http://pastebin.com/NHNmuHPJ and this would be OnSwipeListener interface

public interface OnSwipeListener {
    //Called when the user swipes an item from the RecyclerView at the given position
    void onSwipe(int position);
}

here is everything in action for adding items
![testgif](https://cloud.githubusercontent.com/assets/5139030/9698325/94d9bdf2-53ce-11e5-843a-8026de029771.gif)
here is everything in action for deleting items
![testgif](https://cloud.githubusercontent.com/assets/5139030/9698327/acb2e714-53ce-11e5-9538-58bdc689b8c3.gif)
Thank you for your assistance and time :+1:

**Comment by jjhesk** [comment]
```java

    @Override
    public RealmResults<SpamPhrase> getResults() {
        Realm realm = getRealm();
        return realm.where(SpamPhrase.class).findAllSorted("spamPhrase");
    }
 
    private void add(EditText mInputPhrase) {
        if (mInputPhrase != null
                && mInputPhrase.getText() != null
                && mInputPhrase.getText().toString().trim() != null) {
            String text = mInputPhrase.getText().toString().toLowerCase().trim();
            Realm realm = getRealm();
            SpamPhrase phrase = new SpamPhrase(text);
            phrase.setAdded(System.currentTimeMillis());
            mInputPhrase.setText("");
            realm.beginTransaction();
            SpamPhrase phraseToWrite = realm.copyToRealmOrUpdate(phrase);
            realm.commitTransaction();
            notifyItemRangeChanged(0, getItemCount());
        }
    }
 
    @Override
    public void onSwipe(int position) {
        if (!isHeader(position) && !isFooter(position)) {
            int itemPosition = position - getHeaderCount();
            Realm realm = getRealm();
            RealmResults<SpamPhrase> results = getResults();
            if (results != null && !results.isEmpty()) {
                realm.beginTransaction();
                SpamPhrase phraseToRemove = results.get(itemPosition);
                phraseToRemove.removeFromRealm();
                realm.commitTransaction();
                notifyItemRemoved(position);
            }
        }
    }
 
```
so if i need to remove the row from the realm in the adapter i had to remove the data from the realm first?

**Comment by beeender** [comment]
@jjhesk Is above the same problem with what you said in  #2401 ? If it is, we'd better to keep the discussion in one thread. Separated comments are really difficult for us to track issues.
