### ISSUE TITLE
Unrecoverable error. mremap(): failed

### ISSUE THREAD

**Issue by mistercz** [realm/realm-java#1439]
Hi,
One of our customer has BlackBerry Z30...We are using realm.io  0.82.1....

Getting instance of Realm causes fatal error:
Caused by: io.realm.exceptions.RealmError: Unrecoverable error. mremap(): failed: Function not implemented in io_realm_internal_SharedGroup.cpp line 115
       at io.realm.internal.SharedGroup.createNativeWithImplicitTransactions(ProGuard)
       at io.realm.internal.SharedGroup.(ProGuard:60)

Is there any way how to fix it ?

**Comment by beeender** [comment]
@mistercz We made a fix in Realm’s underlying storage engine which we think could solve this problem. But currently we don't have a bb device to verify. We can make a deskbuild lib includes this fix for you if you can help us to verify on BB device. Would this be OK for you if it won't trouble you too much?

**Comment by mistercz** [comment]
I would like to help with testing, but I don't have access to this device. I found this error log in Fabric reports.

**Comment by beeender** [comment]
@mistercz Thanks, then we will try to verify our fix and keep this issue opened for tracking.

**Comment by cmelchior** [comment]
Closing this now as we just released 0.84.0 with a fix for `mremap()` missing on BlackBerry.
