### ISSUE TITLE
Migrate to ObjectStore

### ISSUE THREAD

**Issue by bmunkholm** [realm/realm-java#1445]
* [ ] `Realm`
* [x] `RealmConfiguration` - see #2372 
* [ ] `RealmResults`
* [ ] `RealmObject`

**Comment by cmelchior** [comment]
Note: Remember new implementation of Primary key API's.

**Comment by kneth** [comment]
The integration of object store can be done in two major steps: a) JNI wrapping of the classes in the object store; b) refactor our Java classes to use the wrapped classes. We will have to wrapped the following classes: `Realm`/`SharedRealm`, `Results`, `List`, `Schema`, `ObjectSchema`, `Property` `ObjectStore`, `Object`.

**Comment by kneth** [comment]
Replaced by #3148
