### ISSUE TITLE
Doc: APT required for Parceler interop

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#1450]
Add a note about the APT plugin being required for Parceler to be able to work with Realm: https://bitbucket.org/hvisser/android-apt

**Comment by johncarl81** [comment]
If you're highlighting the gradle configuration, please make sure to show the different import scopes of the annotation process and api libraries:
```groovy
compile "org.parceler:parceler-api:1.0.3"
apt "org.parceler:parceler:1.0.3"
```
From: http://parceler.org/#getting_parceler

**Comment by kneth** [comment]
@johncarl81 Thanks for pointing us in that direction.
