### ISSUE TITLE
Realm Access From Incorrect Thread

### ISSUE THREAD

**Issue by slidenerd** [realm/realm-java#1456]
Hi, I have read your documentation about using different Realm instances in different threads and how the objects realmlist and realmresults cannot be shared between threads, this is a completely different issue...
![snap 2015-09-08 at 18 47 50](https://cloud.githubusercontent.com/assets/5139030/9735739/9e0e4a62-565a-11e5-9cb5-054c20e0f9f4.png)

I have a class called FBGroup which basically extends RealmObject and looks like this
![snap 2015-09-08 at 18 52 39](https://cloud.githubusercontent.com/assets/5139030/9735767/d1555bb8-565a-11e5-9984-69ccafbbb44c.png)

I am first loading it from the internet in the background thread and then storing it to Realm in the main thread, loading takes place with the help of Gson, my bg task doInBackground looks like this
![snap 2015-09-08 at 18 54 09](https://cloud.githubusercontent.com/assets/5139030/9735789/04f9506e-565b-11e5-8ae3-887dcc364462.png)
It just has one line of code to load straight from JSON and the FBUtil method call looks like this
The highlighted line 111 is giving me the error that says Realm cannot be used in the bg thread, i am simply storing json data into the FBGroup object
![snap 2015-09-08 at 18 55 22](https://cloud.githubusercontent.com/assets/5139030/9735852/44e03f26-565b-11e5-9072-8c3f7f7f6963.png)
There is no sign of Realm.getInstance or anything of that sort anywhere, so what is going on? Thanks for your suggestions and time in advance, does this have something to do with the fact that ID is a primary key and Realm is actually trying to read the key or something? I have added the default constructor to the FBGroup class, its not pasted here though

UPDATE 1
The debugger says this...for the single line inside the AsyncTask
![snap 2015-09-08 at 19 07 15](https://cloud.githubusercontent.com/assets/5139030/9736095/db04587e-565c-11e5-802a-f098f0847232.png)

UPDATE 2

I fixed the error by doing this, I made a copy of the object FBGroup and passed the copy to the AsyncTask and it works perfectly
![snap 2015-09-08 at 20 27 23](https://cloud.githubusercontent.com/assets/5139030/9738195/09f075f4-5668-11e5-8d5a-239a0b1ca4dd.png)
Though I ll be honest , I dont understand the reason behind this line fixing the error, the object FBGroup comes from an ArrayList that is loaded like this
![snap 2015-09-08 at 20 28 21](https://cloud.githubusercontent.com/assets/5139030/9738221/2b2be1ea-5668-11e5-943f-a0689f8ceff3.png)

The method in consideration loads a list of Group objects from Realm database like this
![snap 2015-09-08 at 20 29 28](https://cloud.githubusercontent.com/assets/5139030/9738263/53c2af30-5668-11e5-94e7-935c3e5f6af7.png)

It seems there is a problem here, I want to load a number of objects from Realm into an ArrayList, I think I have made some mistake here, your clarification would solve the issue, thanks in advance, in the meantime, let me try searching some solutions on realm to arraylist :)

UPDATE 3
This other technique worked as well where I directly duplicate stuff from the RealmResults to ArrayList, is there no way to go Realmresults to ArrayList in a more optimal way, I read your issues and saw a guy asking the reverse from List<T> to RealmResults<T> thanks, for your suggestions in advance
![snap 2015-09-08 at 20 46 19](https://cloud.githubusercontent.com/assets/5139030/9738773/adbed32c-566a-11e5-9163-4ec70b712210.png)

**Comment by emanuelez** [comment]
What is `mGroup` in your third image and where does it come from?

**Comment by slidenerd** [comment]
![snap 2015-09-09 at 15 04 28](https://cloud.githubusercontent.com/assets/5139030/9758417/17a31232-5704-11e5-8697-d1025b7b78a1.png)
Oops , sorry for not posting that line, mGroup is an object of FBGroup passed to the AsyncTask as shown above

**Comment by kneth** [comment]
Be careful not to pass an object between threads. Is `mGroup` the result of a query? Can you do the query on your AsyncTask?

**Comment by asbadve** [comment]
```
moviesAPI.getPageAndIndex(1)
                .subscribeOn(Schedulers.io()).observeOn(AndroidSchedulers
                .mainThread())
                .subscribe(new Subscriber<Movie>() {
                    @Override
                    public void onNext(Movie newPosts) {
                        Log.d(TAG, "onNext: new post" + newPosts);

                        final Movie newPostsFinal = newPosts;
//                        resultsListAdapter.addResults(newPosts.getResults());

                        realm.executeTransactionAsync(new Realm.Transaction() {
                            @Override
                            public void execute(Realm bgRealm) {
                                List<Result> resultList = newPostsFinal.getResults();
                                int size = resultList.size();
                                for (int i = 0; i < size; i++) {
                                    Result result = resultList.get(i);
                                    realm.beginTransaction();
                                    Result realmUser = realm.copyToRealmOrUpdate(result);
                                    realm.commitTransaction();

                                }
                            }
                        }, new Realm.Transaction.OnSuccess() {
                            @Override
                            public void onSuccess() {
                                // Transaction was a success.
                                Log.d(TAG, "onSuccess: executeTransactionAsync ");
                            }
                        }, new Realm.Transaction.OnError() {
                            @Override
                            public void onError(Throwable error) {
                                // Transaction failed and was automatically canceled.
                                Log.d(TAG, "onError: executeTransactionAsync ", error.getCause());
                            }
                        });


                    }

                    @Override
                    public void onCompleted() {
                        Log.d(TAG, "onCompleted: ");

                    }

                    @Override
                    public void onError(Throwable e) {
                        Log.e(TAG, "onError:  ", e);
                    }

                });
```
and error is 
`java.lang.IllegalStateException: Realm access from incorrect thread. Realm objects can only be accessed on the thread they were created.`

**Comment by beeender** [comment]
@asbadve the `Realm.Transaction.execute()` will run in a background thread. `realm` which is created in the caller thread cannot be used there. You should use `bgRealm` instead.

**Comment by Zhuinden** [comment]
The original question by @slidenerd was that `mGroup` belonged to the UI thread's Realm. He should have sent in only the ID to the AsyncTask, and requeried the `mGroup` by its ID with a Realm instance opened on that given background thread.

@asbadve you should use `bgRealm`, and you shouldn't be creating nested transactions.
