### ISSUE TITLE
Caused by: java.lang.IllegalStateException: Realm access from incorrect thread. Realm objects can only be accessed on the thread they were created.     

### ISSUE THREAD

**Issue by Rexota** [realm/realm-java#1458]
I'm trying to update a GridView adapter from DB using AsyncTask. Isn't it allowed?

**Comment by SundeepK** [comment]
Looks like each thread must have thier own instance of Realm object:

https://github.com/realm/realm-java/blob/master/examples/introExample/src/main/java/io/realm/examples/intro/IntroExampleActivity.java#L140

**Comment by slidenerd** [comment]
I had a similar issue and I found a fix, if interested @Rexota check this https://github.com/realm/realm-java/issues/1456

**Comment by kneth** [comment]
@Rexota Did you solve your issues using the advices in the previous comments?

**Comment by Rexota** [comment]
I was using a realm instance in AsyncTask, I deleted it and it works.
