### ISSUE TITLE
Realm object does not update, after adding objects in it

### ISSUE THREAD

**Issue by alin-rosu** [realm/realm-java#1460]
This is my code:
     http://pastebin.com/amasLYDK
This is my log:

update step pitstop 1 BEFORE TEST FOR ACTIVE -> ACTIVE0
update step pitstop 1 BEFORE TEST FOR ACTIVE -> ACTIVE2:1
update step pitstop 1 BEFORE TEST FOR ACTIVE -> ACTIVE3 + index is:0
update step pitstop 1 BEFORE TEST FOR ACTIVE -> ACTIVE4
update step pitstop 1 BEFORE TEST FOR ACTIVE -> ACTIVE5 tripsteps not in pstrip:1
update step pitstop 1 BEFORE TEST FOR ACTIVE -> ACTIVE5 tripsteps not in pstrip before:1
update step pitstop 1 BEFORE TEST FOR ACTIVE -> ACTIVE5 tripsteps not in pstrip AFTER CLEAR:0
update step pitstop 1 BEFORE TEST FOR ACTIVE -> ACTIVE6 tripstep size:0

Now this makes no sense. It clearly states that my realmlist has 1 object, I add it to my pstrip realmobject, inside the realmlist. and after that, It has 0 instead of 1. What am I doing wrong here?

**Comment by kneth** [comment]
The `tripsteps` is a managed list (a `RealmList`), and it is automatically updated when the underlying Realm is changed (see the class description for `RealmList` at https://realm.io/docs/java/latest/api/). When you do `psTrip.getTripSteps().clear()`, the objects in `tripsteps` are erased.

**Comment by alin-rosu** [comment]
Thanks a lot, I fixed it using this:
  public static List<TripStep> cloneList(RealmList<TripStep> list) {
        List<TripStep> clone = new ArrayList<TripStep>(list.size());
        for(TripStep item: list) clone.add(new TripStep(item));
        return clone;
    }
Cloning my realmlist inside a list, and then working with that.
