### ISSUE TITLE
Updating realm in Service

### ISSUE THREAD

**Issue by surbhi24** [realm/realm-java#1464]
I am trying to update realm in a background service by sending request to my server of some particular query. ( this service get the query and hit server in 1 minute)
So my database get filled with basic objects in another fragment and remaining field of it are update by sending query to server in the background service.

Problem i am facing is when i define my query and make a list of those query, it doesn't have those new object which are updated into the fragment. 
But if my app gets killed and is invoked again , background service start getting the new objects too.

Can you please help me sorting it out asap.

**Comment by kneth** [comment]
Can you share some of your code with us? That will be it easier for us to answer.

**Comment by surbhi24** [comment]
I solved it I have to refresh my realm to get database properly updated.

**Comment by kneth** [comment]
Great to hear!
