### ISSUE TITLE
columnIndices are not populated causing NPE

### ISSUE THREAD

**Issue by nhachicha** [realm/realm-java#1466]
https://github.com/realm/realm-java/pull/1434 introduced an optimisation to avoid validating a Realm more than once (if opened with the same configuration from another thread for example).
this cause  `createAndValidate` to be called once, still this is problematic as the second Realm will not populate `columnIndices` attribute which is used to lookup columns, causing a NPE

**Comment by nhachicha** [comment]
pr #1468

**Comment by nhachicha** [comment]
fix merged to master

**Comment by lucamtudor** [comment]
I'm running on `0.83.0-SNAPSHOT` and I get the same error even after this has been merged into `master`. Yesterday everything was fine...

> Caused by: java.lang.NullPointerException: Attempt to invoke interface method 'java.lang.Object java.util.Map.get(java.lang.Object)' on a null object reference
at io.realm.RealmQuery.getColumnIndices(RealmQuery.java:160)
at io.realm.RealmQuery.contains(RealmQuery.java:865)
at io.realm.RealmQuery.contains(RealmQuery.java:850)

**Comment by cmelchior** [comment]
@lucamtudor Yes, sorry about that. We accidentally introduced a bug to master. A fix is pending here #1497
