### ISSUE TITLE
Is it possible to save a Bitmap in Realm?

### ISSUE THREAD

**Issue by Rexota** [realm/realm-java#1472]
If I convert a bitmap to byte[] and then a string, that would be a bad solution? Bitmaps are just small website favicons.

Thanks.

**Comment by mshusek** [comment]
I am recommend to get around convert Bitmap to String, instead of this save array of byte into realm.

**Comment by kneth** [comment]
Realm has a data type for binary so using `byte[]` is just fine.

**Comment by vishwangundu** [comment]
can anyone  put code.... how to store image in a realm db in android.
