### ISSUE TITLE
Library  'libdvm houdini.so' not found

### ISSUE THREAD

**Issue by abbasfisal** [realm/realm-java#1473]
Hi 

where is my problem?:(

when i use these command :
***************************
RealmConfiguration config = new RealmConfiguration
.Builder(getApplicationContext())
.name("my.realm")
.build();

Realm realm = Realm.getInstance(getApplicationContext());
***************************
the log cat  show these message :shown in image

![1](https://cloud.githubusercontent.com/assets/10767713/9858488/3fe88746-5b36-11e5-9859-1d6320602177.png)

**Comment by kneth** [comment]
Which device are you using? Is your setup similar to #1398?

**Comment by kneth** [comment]
Have you seen http://www.teknoids.net/content/using-arm-emulation-other-android-x86-distributions?
