### ISSUE TITLE
Closing realm instance in the origin thread if it was interrupted

### ISSUE THREAD

**Issue by kboyarshinov** [realm/realm-java#1474]
I have an [issue](https://github.com/kboyarshinov/realm-rxjava-example/issues/1) in my *realm-rxjava-example* project with updated Realm to 0.82 when realm instances should be closed in the same thread they were created.

Assuming that Realm is doing some blocking IO work internally and the running thread can be interrupted, this situation needs to be properly handled with closing Realm instance. 

I see that Realm methods like `copyToRealm` or any generated setters do not throw `InterruptedException`. Does it mean that Realm catches interrupted exception internally and swallows it? Or does it call `Thread.currentThread().interrupt()` in case of caught interruption? I'm asking this cause I could not find these lines in source code.

If interruption is swallowed then the following code will wait while realm work is done and then exits the loop:
```java
Thread thread = new Thread() {
  @Override
  public void run() {
    Realm realm = Realm.getDefaultIntstance();
    while (!Thread.currentThread().isInterrupted()) {
      // do some work in realm
    }
    realm.close();
  }
};

thread.start();
thread.interrupt();
```
The code is basically existing [threading example](https://github.com/realm/realm-java/blob/master/examples/threadExample/src/main/java/io/realm/examples/threads/ThreadFragment.java). And it works like I described in my tests.

Does it mean that Realm IO process can not be interrupted?

Please correct me if my assumptions are wrong. I solved my issue with handling thread interruption manually but I need to be sure that realm is working as I think it works.
Thanks in advance.

**Comment by cmelchior** [comment]
Realm doesn't use any Java IO. Everything IO related is in the native layer. So this means you should never see an `InterruptedException` from Realm as we don't use the Java IO classes. So from a Java perspective, it means that the IO cannot be interrupted. I hope that answers your question?

**Comment by kboyarshinov** [comment]
Yes, thanks. It means that I should handle java thread interruption myself and safely close Realm instance. 

Btw do you have any plans on implementing native Realm IO interruption mechanism?

**Comment by cmelchior** [comment]
Not currently no. Interrupting normal database operations could potentially result in corrupted files, so that is probably a no-go, but for auxiliary methods like ```writeCopy`` it might make sense, but it would probably be very low priority.

**Comment by kboyarshinov** [comment]
Good to know that. Thanks.
