### ISSUE TITLE
object files in realm-jni remain when invoking clean task

### ISSUE THREAD

**Issue by zaki50** [realm/realm-java#1481]
There are two problems.

One is that clean task in realm-jni is not called from root project.
Other is that clean task in realm-jni uses file globbing but it does not work.

I sent two PRs that fixes these problems.

#1479, #1480

**Comment by kneth** [comment]
@zaki50 Thanks. Having object files in the same directory as the source file is also a bad habit.

**Comment by zaki50** [comment]
fixed by #1479 and #1488
