### ISSUE TITLE
Was it deleted by another thead?

### ISSUE THREAD

**Issue by slidenerd** [realm/realm-java#1482]
Hello guys, before making this post, I referred to  #1047 #1206 but did not find it helpful

I have a JSON feed that looks like this

![snap 2015-09-19 at 14 47 48](https://cloud.githubusercontent.com/assets/5139030/9975557/72b9e854-5edd-11e5-9253-ef78e153c2ac.png)

My model classes to fetch and store data from JSON with RealmObject look like this
Admin.java
![snap 2015-09-19 at 14 50 35](https://cloud.githubusercontent.com/assets/5139030/9975595/c94bb764-5ede-11e5-8e71-2e7326b5d79a.png)

Picture.java
![snap 2015-09-19 at 14 51 30](https://cloud.githubusercontent.com/assets/5139030/9975572/f9bc22cc-5edd-11e5-979b-8b9e36f5f050.png)

PictureData.java
![snap 2015-09-19 at 14 52 33](https://cloud.githubusercontent.com/assets/5139030/9975574/154b8d84-5ede-11e5-933a-0ffd7416a059.png)

the first time my activity runs, I load it from JSON and store it in Realm, after rotation I try to get data from a Parcelable with the Parceler library but a subsequent time I am getting a crash that looks like this
![testgif](https://cloud.githubusercontent.com/assets/5139030/9975591/85ca121a-5ede-11e5-849f-c3573e3e48b2.gif)

I am not deleting anything any part of the admin data anywhere, however I get an exception stating null in my debug as shown above. Am I missing something? Thanks for your response in advance, I ll work in the meanwhile on my end to see if I can fix this

This is all the code I am using to store my JSON object that looks exactly like what you see in the 1st screenshot
public static void storeAdmin(Context context, Realm realm, JSONObject jsonObject) {
        realm.beginTransaction();
        realm.createOrUpdateObjectFromJson(Admin.class, jsonObject);
        realm.commitTransaction();
    }

and this is how I load it from Realm
![snap 2015-09-19 at 15 01 25](https://cloud.githubusercontent.com/assets/5139030/9975608/5b6bf17c-5edf-11e5-9989-2edf2c7a48d2.png)

I do see the data after exporting the file to RealmBrowser
![testgif](https://cloud.githubusercontent.com/assets/5139030/9975629/194d4452-5ee0-11e5-9e7d-5ae37c2dfe32.gif)

UPDATE 1
The problem seems to be with the Picture class and its data, I commented out the whole part of having a picture, and there were no issues whatsoever

UPDATE 2
I think I have narrowed down the problem, parceler seems to load an invalid object, does this have something to do with Realm?
Picture object is invalid when loading from Parceler, am I missing something?
![snap 2015-09-19 at 21 02 28](https://cloud.githubusercontent.com/assets/5139030/9976920/d5b4c3f0-5f11-11e5-9403-b0befbd5617a.png)

This is how I save things prior to rotation
![snap 2015-09-19 at 21 07 21](https://cloud.githubusercontent.com/assets/5139030/9976932/7963c79e-5f12-11e5-8350-45d9ed98e562.png)

**Comment by slidenerd** [comment]
![snap 2015-09-20 at 15 29 00](https://cloud.githubusercontent.com/assets/5139030/9980190/88d2e90e-5fac-11e5-8732-36449a104458.png)
I fixed the issue by writing this code, it seems Realm doesnt care about fetching the Picture and the PictureData from the database, I had to first get the PictureData using Realm, duplicate it to prevent this exception
![snap 2015-09-20 at 15 31 59](https://cloud.githubusercontent.com/assets/5139030/9980194/c17b294c-5fac-11e5-81c6-28d4768d5dd0.png)

realm closing exception, get the Picture once again from realm, duplicate it, and then set the picture data on the picture and the picture on the admin, if an admin contains picture which in turn contains picture data, doesn't realm read everything in 1 shot? is there a better way to do what i did?

**Comment by cmelchior** [comment]
Hi @slidenerd 
It seems you are mixing standalone data and data managed by Realm by creating the object hierarchy that is already present in Realm, and that probably makes the `implementations` parameter for Parcel do something wrong. If you added the `@Parcel` annotation to all your model classes I would assume that just doing:

```
public static Admin loadAdmin(Realm realm) {
  return realm.where(Admin.class).findFirst(); 
}
```

should work?

**Comment by slidenerd** [comment]
the reason I am duplicate the Admin object is because it keeps throwing an illegal state exception once I close Realm in the onDestroy method, it says Realm instance already closed, I am loading an object only when savedInstanceState==null and closing the Realm in onDestroy, when the Activity or Fragment rotates, i try to use the same realm object which throws an exception because of realm closing

**Comment by cmelchior** [comment]
Hi @slidenerd 
I tried reproducing your example in this branch https://github.com/realm/realm-java/tree/cm-bug-parceler. I added it to our intro example here: https://github.com/realm/realm-java/tree/cm-bug-parceler/examples/introExample/src/main/java/io/realm/examples/intro/model

And you are right, something doesn't look right. From what I can tell Parceler doesn't seem to respect the `value = Parcel.Serialization.BEAN` it is given, which should cause it to use getters and setters. Instead it seems to serialize the underlying data structure in the Proxy class. This is a bit unexpected given the documentation so I am not sure what is up. Either it is a bug in Parceler 1.0.3 or something with our setup. Perhaps @johncarl81 has some input to that?

In any case, for now it seems duplicating the data manually is the proper work-around.

**Comment by slidenerd** [comment]
![testgif](https://cloud.githubusercontent.com/assets/5139030/10012584/e8439b88-6126-11e5-99f7-7c4b47a95551.gif)
First of all, thanks for taking the effort to setup a model and trying to check if this was a bug. I stopped loading the nested objects temporarily and tried to prevent duplication for loading the Admin object from Ream, i still get this exception which s shown below when I rotate my screen.
![testgif](https://cloud.githubusercontent.com/assets/5139030/10012643/5516b326-6127-11e5-9881-c7668ff48d09.gif)
Even if we dont consider the nested objects PictureData and Picture from my case, and simply have the Admin object without any duplication, i open a realm instance inside my fragment s oncreate and close it inside my ondestroy, if saved instance state is null, i load admin object from my data store else i load it from parcelable, i still get the crash which you see above which says Realm object is closed. The way i Understand is when I rotate the screen, onDestroy gets called where realm is closed and inside my onCreate i open an instance of realm, shouldnt the previously loaded Admin object be able to work with this new Realm instance?

**Comment by johncarl81** [comment]
Hmmm, I may need a little direction here, but I took a look at the introExample @cmelchior mentioned.  Here's a sample of the generated Parcelable focusing on the Dog class referecned by the Person:

```java

public class Person$$Parcelable
    implements Parcelable, ParcelWrapper<io.realm.examples.intro.model.Person> {

    private io.realm.examples.intro.model.Person person$$0;
    //...
    private io.realm.examples.intro.model.Person readio_realm_examples_intro_model_Person(android.os.Parcel parcel$$2) {
        io.realm.examples.intro.model.Person person$$1;
        person$$1 = new io.realm.examples.intro.model.Person();
        //...
            dog$$1 = readio_realm_examples_intro_model_Dog(parcel$$2);
        person$$1 .setDog(dog$$1);
        //...
        return person$$1;
    }

    private io.realm.examples.intro.model.Dog readio_realm_examples_intro_model_Dog(android.os.Parcel parcel$$3) {
        io.realm.examples.intro.model.Dog dog$$0;
        dog$$0 = new io.realm.examples.intro.model.Dog();
        dog$$0 .setName(parcel$$3 .readString());
        return dog$$0;
    }

    private void writeio_realm_examples_intro_model_Person(io.realm.examples.intro.model.Person person$$3, android.os.Parcel parcel$$4, int flags$$0) {
        //...
        writeio_realm_examples_intro_model_Dog(person$$3 .getDog(), parcel$$4, flags$$0);
    }

    private void writeio_realm_examples_intro_model_Dog(io.realm.examples.intro.model.Dog dog$$2, android.os.Parcel parcel$$5, int flags$$1) {
        parcel$$5 .writeString(dog$$2 .getName());
    }
//...
}

```

So, from what I can see Parceler is not serializing the fields found in the RealmBase class or the Proxy.  Am I missing something?

**Comment by slidenerd** [comment]
With the ongoing Parceler or Realm issue, as I mentioned previously I was duplicating stuff but I have ran into an issue, in my case I have the following structure which is causing problems while duplicating
class A extends RealmObject{
@PrimaryKey
int key;
RealmList<B> data;
}
class B {
//there is no primary key here
String data;
}

i add a new entry of class A and it has N entries of B associated with each row of A. I want to createAllOrUpdateFromJson which obviously doesnt work if there is no primary key, if I follow the duplication process then first I need to find all B, correcT?
realm.where(B.class).findAll() //how do I find only those B objects here that are associated with a particular entry of A?

**Comment by cmelchior** [comment]
@johncarl81 Thanks for looking into it. I should have thought of looking into the generated Parceler file. It looks correct though as it does use getters/setters and doesn't try to use the Proxy classes.

**Comment by cmelchior** [comment]
@johncarl81 @slidenerd Actually something came to mind from some previous testing. I think I can recall that the object isn't actually parcelled unless needed, e.g. it will be serialised if you put it into an intent, but if you just do `Parcels.unwrap(Parcels.wrap(obj)` it doesn't really parcel the object but just return some internal reference to it. Do you know anything about that?

E.g the following code does trigger the log statement:

```
Person p1 = realm.where(Person.class).findFirst();
Person p2 = Parcels.unwrap(Parcels.wrap(Person.class, p1));
if (p1 == p2) {
  Log.e("RealmTest", "Same object");
}
```

**Comment by cmelchior** [comment]
@slidenerd Looking through the source code for `Bundle`, it is indeed just as HashMap, in which case your error makes perfect sense as the original Realm is closed. 

So in your case I think you have to consider the following choices:

1) Copy all data out of Realm into stand-alone objects
2) Add a primary key to your Admin object you can save instead and then requery the object on the other side. 
3) Manually create the Parcel from the Parceler wrapper using something like http://stackoverflow.com/questions/18000093/how-to-marshall-and-unmarshall-a-parcelable-to-a-byte-array-with-help-of-parcel and then transfer it as an byte array.

@johncarl81 It doesn't look like a problem in Parceler, it behaves as expected.

**Comment by johncarl81** [comment]
@cmelchior you are correct, Parcelable objects aren't officially "Parceled" until they are marshaled through a Parcel / Bundle.  The Parcelable wrapper just sets up the methods to perform this marshaling when necessary.

Great.  Let me know if you need anything else.

**Comment by johncarl81** [comment]
@cmelchior, I may not understand this issue or Realm well enough... is this calling for a converter (like the [RealmList converter](https://gist.github.com/cmelchior/72c35fcb55cec33a71e1#file-realmlistparcelconverter-java)) to handle objects in a relationship... in this case a Many-to-one Picture ->  PictureData relationship?

Maybe I'm concerned that Parceler is a valid solution for the variety of Realm use cases.

**Comment by cmelchior** [comment]
I don't think this is something that Parceler can fix. If all classes are annotated correctly Parceler is able to serialize the entire object graph just fine. The problem here is that even though the Bundle takes an Parcelable as argument, it doesn't actually turn it into a Parcel (Doing that will do a copy of all data from Realm, effectively creating a stand-alone copy). If that doesn't happen, the wrapper provided by Parceler still just reference the original object, which is scoped by the lifetime of the Realm instance. 

So really it is a "problem" with the Bundle not turning the input into a Parcel. That is however totally understandable from a performance standpoint, when you think about it.

In any case, this is really a Realm problem and we need to provide better support for using Parcelable in general.

**Comment by slidenerd** [comment]
Thanks for the detailed insight @johncarl81 and @cmelchior , so given your 3 solutions 1) duplicate 2)add a primary key 3) custom marshalling, 
    I have a doubt with respect to the issue I posted earlier about the class A and class C thing where I have a primary key only on top level objects and no keys on nested ones and I would like to createOrUpdateAllFromJSON , what would be the best way to approach this situation? 
    Also if I make an Adapter for a RecyclerView with RealmResults as the primary data source, and if I want to use Loaders to load RealmResults from a background thread, I believe the documentation on realm clearly states RealmResults cannot be passed from one thread to the other, what is the best way to approach this situation? If I use an ArrayList instead of RealmResults, I would be able to load RealmResults in the background, convert that to an ArrayList and then set this ArrayList on the adapter, this however complicates inserts and deletes. 

   Last but not the least, if I load the data from Realm database everytime instead of using Parcelables in any form, that would get rid of a lot of issues which obviously is the worst solution possible, but what do you recommend?

**Comment by cmelchior** [comment]
1) in order to use `createOrUpdateAllFromJSON` you need primary keys on all your models you need updated, otherwise it will just create a new copy. So a primary key on the top-level object alone is not enough to avoid duplicated model data. We plan to implement cascading deletes which will make this use case easier, but those are not implemented yet: https://github.com/realm/realm-java/issues/1104

2) Currently you cannot parse RealmResults/Objects between threads, so just copying to an ArrayList is not enough unless you copy out all the data inside each object as well. We are just in the last review process of Async queries which will make it possible to query on a background thread though: #896
However queries in Realm are usually really fast, so in most cases you shouldn't have any problems querying on the main thread.

3) Just parsing a primary key around and querying for that single object is actually really fast, and in most cases shouldn't pose any problems. It also has the advantage that you will get the latest available data always. Using Parceler will copy the data out of Realm, which means they pr. definition are "out of date" and will take up more memory as Realm data is normally lazy loaded. It does have the advantage though that you then don't need a open Realm to actually read the data. What is better is probably up to your specific use case.

**Comment by slidenerd** [comment]
Thanks for the detailed answer @cmelchior I was testing a demo implementation of Realm with an ArrayList as base data source here https://github.com/slidenerd/SpamWordList and here is what I conclude 1)An adapter can have a RealmResults or ArrayList as data source, if RealmResults are used, then we can easily add and remove items with transactions on the main thread but loading a large number of entries using a loader is not possible since RealmResults cannot be shared between different threads, however you mentioned the Async queries so will wait for them :+1:  2) if the adapter uses ArrayList, it can easily load entries from a Loader but inserts and deletes become complicated since the ArrayList has to be updated properly and the position changes have to be notified, besides it goes against the whole point of having a RealmResult that already does this :+1:  so I ll use a RealmResults base object for now and wait for the async parts to be done. Thank you very much for your awesome library, I ll be making a video series on how to use realm :) and hopefully that ll help you in some way.

**Comment by cmelchior** [comment]
Cool, will look forward to seeing that :)
I'll close this issue now then. Feel free to either reopen or create a new one if you run into any other problems.
