### ISSUE TITLE
feature request: add createAllFromJson() and createOrUpdateAllFromJson() which accept java.io.Reader

### ISSUE THREAD

**Issue by zaki50** [realm/realm-java#1485]
InputStream version of createAllFromJson() and createOrUpdateAllFromJson() expects that data from InputStream is encoded in UTF-8.

It is reasonable in most cases, but not always.

If Realm class has Reader version of createAllFromJson() and createOrUpdateAllFromJson(),
user can use these methods for InputStream which contains data encoded other than in UTF-8.

**Comment by cmelchior** [comment]
Good idea. We will probably split JSON support into its own library though as it will make it easier to better support 3rd party JSON libraries like GSON/Jackson/Moshi as well as use cases like this without having an explosion of methods in the standard API.

**Comment by cmelchior** [comment]
Folding this into https://github.com/realm/realm-java/pull/3758
