### ISSUE TITLE
boolean as primary key

### ISSUE THREAD

**Issue by beeender** [realm/realm-java#1486]
Allow user to use boolean as the type of primary key.

**Comment by Saketme** [comment]
Primary keys are supposed to be unique. Why would you want booleans as primary keys?

**Comment by cmelchior** [comment]
If you only have 2 elements, and it makes it possible to use methods like `copyToRealmOrUpdate` or `createOrUpdateObjectFromJson` which only work on models with primary keys.

**Comment by beeender** [comment]
I don't think we are going to get `set_boolean_unqiue` support from core. So close this.
