### ISSUE TITLE
Documentation's instructions generate Exception: "io.realm.exceptions.RealmException: Removing is not supported."

### ISSUE THREAD

**Issue by MobileOak** [realm/realm-java#1487]
I just started playing around with Realm on a small project I have. I want to be able to delete objects from the database. Your [documentation](https://realm.io/docs/java/latest/#deletion) states I should do the following:

```java
// remove a single object
Dog dog = result.get(5);
dog.removeFromRealm();
```

This throws an exception instead of working:
```java
    io.realm.exceptions.RealmException: Removing is not supported.
    at io.realm.RealmResults$RealmResultsIterator.remove(RealmResults.java:552)
    at java.util.AbstractCollection.remove(AbstractCollection.java:229)
```

And it is because the code always throws an exception at that point:
https://github.com/realm/realm-java/blob/71e94e1ab8688bfb796e9f0e401462060428cd40/realm/src/main/java/io/realm/RealmResults.java#L552

What is the workaround here? Why hasn't the documentation been updated?

**Comment by emanuelez** [comment]
You are talking about two different ways to delete objects.

 1) from the object itself. This is supported and works fine
 2) from an iterator. This is not currently supported but will soon.

I suppose you code tries to delete objects using the iterator method.

**Comment by MobileOak** [comment]
I have tried again to get this working, to no avail.

I load from the database players for my app:

```java
mPlayers = realm.where(Player.class).findAll();
```
This array is then passed to an ArrayAdapter class to be shown in a listview, with a button for deleting the player. 

```java
        mViewHolder.delete.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                if (mListener != null) {
                    mListener.deletePlayer(player);
                }
            }
        });
```

This calls delete player on the original Activity. Originally I had this code:

```java
public void deletePlayer(final Player player) {
    mPlayers.remove(player);
    mAdapter.notifyDataSetChanged();
    player.removeFromRealm();
```
I thought this would work as per the example in your documentation, but it doesn't, it calls the "Removing is not supported" function and crashes my app.

So based on your suggestion, I thought I needed to do a new `get()` call on the original RealmResults and remove it that way, so I changed the code:

```java
public void deletePlayer(final Player player) {
    mPlayers.remove(player);
    mAdapter.notifyDataSetChanged();

    for (int i = 0; i < mPlayers.size(); i++) {
      if (player == mPlayers.get(i)) {
        mPlayers.get(i).removeFromRealm();
      }
    }
```

This as well causes the Exception to be thrown.


This is your documentation:
```java
// remove a single object
Dog dog = result.get(5);
dog.removeFromRealm();
```

There is no context here at all for me to figure out what result is, or how it was acquired. How is my code any different from what's in your documentation? There's no warning that the iterator version of the the removeFromRealm method will always throw an exception, nor how to avoid that. This is so far some of the worst documentation I've run into for an Android library, and if you expect people to use your product you should have better examples and documentation.

**Comment by kneth** [comment]
The variable `mPlayers` is a `RealmResults`, and it looks like you wish to remove all the objects in it. The method `clear()` is a better options as removing while iterating isn't supported.

Moreover, `mPlayers` is updated so `deletePlayer` could be simplified to:

    public void deletePlayer(final Player player) {
        player.removeFromRealm();

**Comment by kneth** [comment]
I'm closing the issue. Please free to reopen if issue still persists.

**Comment by MobileOak** [comment]
No, I'm not trying to remove all of the players, I'm trying to remove a single one.

**Comment by zaki50** [comment]
@MobileOak Did you call `Realm.beginTransaction()` or `Realm.executeTransaction()`?

**Comment by MobileOak** [comment]
I don't have the code anymore, but I'm 90% certain I was doing a `Realm.beginTransaction()` call.

The exception happened on the delete before the execute could be called.

**Comment by MobileOak** [comment]
If I recall correctly, I played around with several different ways, trying to get it to work, but it always somehow called the version of remove that threw that exception, rather than any other version of remove.

**Comment by kneth** [comment]
I have created a documentation issue so we can get better examples: #1763.

**Comment by sureshvaavel** [comment]
@MobileOak  did you fix this ? I am having the same problem

**Comment by multivoltage** [comment]
I tried some times, but I arrive at the same exception:
I have a a list of TravelsRealms object:

`for(TravelRealm t : travelRealms){
                        if(t.createdWhen == travel_key){
                            int index = travelRealms.indexOf(t);
                            realm.beginTransaction();
                            travelRealms.remove(index);
                            realm.commitTransaction();
                            homePagerAdapter.notifyDataSetChanged();
                            break;
                        }
                    }`

I user "for" to search inside this list. when objcet is correct, I delete it with a simple remove. I tried with other method like remove(Object), or call t.deleteFromReam().
I have the same error every time
