### ISSUE TITLE
Format JNI source code

### ISSUE THREAD

**Issue by beeender** [realm/realm-java#1489]
Some rules below:
1) JNI headers should be generated with gradle
2) JNI cpp files name should be like `io_realm_internal_ClassName.cpp`
3) Vars should be in forms of `underscore_case`
4) Use terms `RealmObject` and `RealmList` instead of `link` and `link list`. In general avoid using words like column/table/link/linklist if the error will reach users. All these concepts are core concepts and not exposed to end users.
5) `catch` and `CATCH_STD` should be in the new line.
6) Lines should never exceed **118** characters (https://github.com/realm/realm-core/blob/master/doc/development/coding_style_guide.cpp#L6)
7) JNI function definition:

``` c++
JNIEXPORT jlong JNICALL // This 3 things at the first line
Java_io_realm_internal_LinkView_nativeGetFinalizer(JNIEnv *, jclass)
{
    TR_ENTER()
    return static_cast<jlong>(reinterpret_cast<uintptr_t>(&finalize_link_view));
}
```

8) Others follow core's style guide https://github.com/realm/realm-core/blob/master/doc/development/coding_style_guide.cpp
9) return NULL instead of 0 for invalid pointer
10) Define a const value for -1 to return for invalid index/version

**Comment by nhachicha** [comment]
as commented [here](https://github.com/realm/realm-java/pull/1214#discussion_r40843188)
find a consistent way of using `TR_ENTER` & it's variants

**Comment by cmelchior** [comment]
Also, 
- comments for methods
- general code style like e.g. bracers

**Comment by nhachicha** [comment]
`return NULL` instead of 0 or -1 for pointer (in case of error) 
-1 should only be used for invalid indexes

**Comment by kneth** [comment]
We are now using `clang-format` and header files are always generated by CMake/Gradle.
