### ISSUE TITLE
Two configurations with different schemas are trying to open the same Realm file.

### ISSUE THREAD

**Issue by InfinityApps** [realm/realm-java#1490]
Hi!

I'm running into a random issue with captioned error when I use two Realms with different configurations (without overlapping modules for each configuration). Any idea for the cause of the error?

This error is not always reproducible and it has appeared under some random occasions on Android 4.3 and 5.1 with 0.82.2.

Thanks for your help!

**Comment by beeender** [comment]
@InfinityApps Do you have any more information about the issue? Like any exceptions, back trace and so on?

**Comment by InfinityApps** [comment]
@beeender Trying to reproduce the error. Please stay tuned.

**Comment by InfinityApps** [comment]
**Stack trace**

```
java.lang.IllegalArgumentException: Two configurations with different schemas are trying to open the same Realm file. Their schema must be the same: /data/data/com.example.app/files/info.realm
            at io.realm.Realm.validateAgainstExistingConfigurations(Realm.java:670)
            at io.realm.Realm.createAndValidate(Realm.java:596)
            at io.realm.Realm.create(Realm.java:567)
            at io.realm.Realm.getInstance(Realm.java:540)
            at com.example.app.util.RealmUtils.getInfoRealm(RealmUtils.java:35)
            at com.example.app.util.LocationInfoUtils.getDefaultLocationId(LocationInfoUtils.java:65)
            ...
```

**RealmUtils.java**
*Note: The two Realms (the other named DataRealm) have different schemaVersion*
```java
public static Realm getInfoRealm(Context context) {
    return Realm.getInstance(getInfoRealmConfig(context)); // Line 35
}

...

public static RealmConfiguration getInfoRealmConfig(Context context) {
    return new RealmConfiguration.Builder(context)
            .name(INFO_REALM_FILENAME) // info.realm
            .schemaVersion(1)
            .setModules(new InfoModule(), new RatingModule())
            .build();
}
```

**LocationInfoUtils.java**
```java
public static int getDefaultLocationId(Context context) {
    int id = -1;
    Realm dataRealm = RealmUtils.getDataRealm(context);
    // Logic to assign "id" if the required Location ID is available in DataRealm
    dataRealm.close();

    if (id == -1) {
        Realm infoRealm = RealmUtils.getInfoRealm(context); // Line 65
        Location result = infoRealm.where(Location.class).findAllSorted("id").first();
        id = result.getId();
        infoRealm.close();
    }

    return id;
}
```

Would it be an issue associated with the way I manipulated the two Realms in `LocationInfoUtils.class`? Thank you for your help!

**Comment by cmelchior** [comment]
The `name(INFO_REALM_FILENAME)` is what is used as the filename on disk, so if both your configurations use the same name you will get that error. Is that the case?

**Comment by InfinityApps** [comment]
@cmelchior Of course the two configurations have different file names.

**Comment by cmelchior** [comment]
The LocationInfoUtils class shouldn't have any impact. 

Realm should only throw that error if it was given 2 configurations it thought where different (by calling RealmConfiguration.equals() on them. The same mechanism is used by our internal cache. I am a bit surprised that this is only happening occasionally though. Are there any chance you are opening a Realm without using any of these two factory methods?

**Comment by InfinityApps** [comment]
@cmelchior Just checked that all Realm opening operations are completed with the factory methods. The issue really comes randomly even on the same device or VM.

**Comment by cmelchior** [comment]
Can you reproduce it (maybe not consistently, but from time to time)? 

One thing to test would be to cache the RealmConfiguration instead of creating a new instance each time.

Something like this:

```
public class MyApplication extends Application {
  public void onCreate() {
    super.onCreate();
    RealmUtils.initialize(this);
  }
}

public class RealmUtils {
  private static RealmConfiguration infoConfig;
  private static RealmConfiguration dataConfig;

  public static void initialize(Context context) {
    infoConfig = new RealmConfiguration.Builder(context)......build();
    dataConfig = new RealmConfiguration.Builder(context)......build();
  }

  public static Realm getInfoRealm() {
    return Realm.getInstance(infoConfig);
  } 

  public static Realm getDataRealm() {
    return Realm.getInstance(dataConfig);
  } 
}
```

**Comment by InfinityApps** [comment]
@cmelchior I'll try it. Thanks!

**Comment by kneth** [comment]
@InfinityApps Did you have success with suggestion by @cmelchior?

**Comment by InfinityApps** [comment]
@kneth Seems @cmelchior's solution solves the problem. I'll continue to test and report if the issue appears again. Thanks all for your help!

**Comment by cmelchior** [comment]
If it does indeed solve it it means one of our `equals()` functions has a problem. So it is probably something we need to dig deeper into.
