### ISSUE TITLE
createOrUpdate behaviour with respect to model

### ISSUE THREAD

**Issue by slidenerd** [realm/realm-java#1500]
Hello guys, I tried searching your issue base for any queries on createOrUpdate and didnt find much except a bunch of enhancement requests on the same. My issue is as follows-

I have a model that looks like this
class Feed extends RealmObject{
@PrimaryKey
String groupId;

RealmList<Post> posts;
}

class Post extends RealmObject{
@PrimaryKey
String postId;
...
String message;
}

I load the JSON object which contains an array of posts and looks like this http://pastebin.com/eWS95hf1

![snap 2015-09-26 at 20 15 54](https://cloud.githubusercontent.com/assets/5139030/10118072/95316368-648b-11e5-863f-ebd6e463814c.png)

As per the above image, when I loaded the feed yesterday, it gave me 15 posts, today when I do createOrUpdate(feed) it overwrites on top of those 15 items, in other words you ll see common elements but its clearly evident comparing both tables that an additional 2 posts were made, i was expecting the number of rows to be 17 instead of 15. 

My code that does the storing part creates a Feed object, loads a RealmList of posts from JSON, calls feed.setPosts(posts) and returns that feed object which I store by saying
realm.createTransaction();
realm.copyToRealmOrUpdate(feed);
realm.commitTransaction();

If I change the model from the one I posted above to say, this

class Feed extends RealmObject{
@PrimaryKey
String groupId;
}

class Post extends RealmObject{
@PrimaryKey
String postId;
...
String message;
}

and call createOrUpdate separately for Feed and separately for a single Post object, will it exhibit the behaviour in the screenshot or will it simply keep adding new post objects separately independent of the Feed object. I would love to know how it would behave if I decouple the relationship between the model classes. 

In simple words, if I do createOrUpdate(feed) before deleting and item from facebook and after deleting, it automatically removes the deleted item from the database as well. if I do a createOrUpdate(post) it ll update the fields if it already exists, it will create the object in the realm database if it doesnt exist, but what does it do if the object is not there in the json feed but present in the realm database, does it delete it? Thanks for your time in advance

UPDATE 1

I like trying things myself, its a Saturday and pretty sure you are AFK :+1:  so here is what I experimented
I had my class Feed separate from Post

and this is the result before and after making a few new posts
![snap 2015-09-26 at 20 45 32](https://cloud.githubusercontent.com/assets/5139030/10118173/b8654c24-648f-11e5-8b63-8e2476571645.png)

I would like to store a for each group Id, wonder if there is a way to tell Realm about such a thing, also i am not sure what happens if I go back and delete a post from facebook, and whether realm will reflect it, enjoy your weekend , I ll try something for the same here

UPDATE 2

I tested the delete and it brought my fears exactly, the old structure with Feed and Post having a relationship between them worked perfectly but replaced every thing each time the JSON feed was loaded instead of appending stuff, the new structure without any relationship between Feed and RealmList<Post> stores the posts but doesnt reflect what is deleted already, the createOrUpdate works differently according to the relationship between the models, is there a way I can maintain a relationship between Feed and Post and still tell Realm to append the RealmList post objects each time instead of replacing them?

**Comment by cmelchior** [comment]
Hi @slidenerd 
Right now we don't delete any existing objects if you replace a `RealmList` with new data using `copyOrUpdate`. So as you observed, you can risk having "free-floating" Post objects that aren't connected to any Feed. 

To better understand your use case can you verify my understanding of your problem:

- Your Posts should be updated correctly corresponding according to the postId (which is marked as a PrimaryKey)
- Feed should never loose references to Posts, i.e. If at v1 you get post `[1,2,3]` and at v2 you get `[2,3,4]` the end result should be `[1,2,3,4]`?

**Comment by slidenerd** [comment]
yes 1) posts should be updated correctly corresponding to postId
 2) yes you are correct

**Comment by cmelchior** [comment]
This is probably not a scenario we can support with a generic `copyOrUpdate` as it breaks the semantics you would normally have in such a case, but I can see at least one solution you can use. 

----
Remove the reference from `Feed -> Post` and let it go the other way.

```
public class Feed extends RealmObject {
  private Feed feed;
  private String postId;
  // ...
}
```

This will allow you to have "append" only mode for Posts, but will make your queries slightly more complicated as you need to query on the explicit Id instead of just following a reference:

```
Feed feed = realm.where(Feed.class).findFirst(); // Find some feed
RealmResults<Post> posts = realm.where(Post.class).equalTo("feed.groupId", feed.getGroupId()).findAll(); // Get all posts with that feedId;
```

**Comment by slidenerd** [comment]
Thanks for the suggestion but with all due respect, is there a mistake here
public class Feed extends RealmObject {
  private Feed feed;
  private String postId;
  // ...
}
You are suggesting to add a postId inside Feed, just clarifying because the structure you proposed looks different than the query you wrote

**Comment by cmelchior** [comment]
Yes, sorry. My example code was for the `Post` class class

**Comment by slidenerd** [comment]
Thanks I am closing the issue for now , will try this, if anything goes off will let you know
