### ISSUE TITLE
Document Android Framework class behavior

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#1503]
We should document how certain Android framework classes behave in the context of Realm:

* IntentService: `onHandleIntent` is running in a separate Thread. Disable autoRefresh.
* AsyncTask: `doInBackground` is running in a separate Thread. 
* Others?

**Comment by slidenerd** [comment]
IntentService, AsyncTask, JobSchedulerService, BroadcastReceiver [both local and remote]

**Comment by kneth** [comment]
Thanks for the suggestions.

**Comment by donnfelker** [comment]
@cmelchior chan this be closed? See the merge above.

**Comment by cmelchior** [comment]
Yup. Thanks
