### ISSUE TITLE
Realm Browser not displaying correct or full data

### ISSUE THREAD

**Issue by slidenerd** [realm/realm-java#1505]
Hi, I am loading a feed from the database, it shows me only 15 entries in the realm browser but as you can see in the GIF below, there are way more entries than 15, am I missing something?
<iframe src="//giphy.com/embed/3o85xEsVyTwlCWEyLS" width="480" height="273" frameBorder="0" class="giphy-embed" allowFullScreen></iframe><p><a href="http://giphy.com/gifs/realm-browser-vs-actual-data-3o85xEsVyTwlCWEyLS">via GIPHY</a></p>

I have a 
class Feed exten....{
@PrimaryKey
String groupId;
RealmList<Post> posts;
}

class Post exten...{
@PrimaryKey
String postId;
String message;
}

the Feed table shows 15 entries for a group id whereas the post table has 19 entries under that group while my android emulator is actually load 49 posts
here is my realm file http://www.4shared.com/folder/RcVOJCMR/_online.html

UPDATE 1
I ll clear the app's database, load a feed with some posts on it, make 10 new test posts and export the database before making the new posts and after making the new posts to compare the contents...will let you know if realm browser and app list is truly different

UPDATE 2
I ran a test, loaded 15 posts, exported the database, loaded 10 more and again exported the database, my realm browser for Feed table shows 15 posts in both the realm files
![snap 2015-09-28 at 20 30 40](https://cloud.githubusercontent.com/assets/5139030/10139297/d0012f9c-661f-11e5-8559-b1cbaa398102.png)

My post table however has 15 entries in the first table and 25 in the next
![snap 2015-09-28 at 20 31 47](https://cloud.githubusercontent.com/assets/5139030/10139322/f7059718-661f-11e5-9ac3-655258738803.png)

Am I missing something? This by the way also fixes #1500 I did not change the model in any way

My feed still looks like this
public class Feed extends RealmObject {
    @PrimaryKey
    private String groupId;
    private long timestamp;
    private RealmList<Post> listPosts = new RealmList<>();
    private String previous;
    private String next;
}

and my Post looks like this
public class Post extends RealmObject {

    @PrimaryKey
    private String postId;

    private String userId;

    private String userName;

    private String message;

    ...
}

I wonder how everything is being appended now suddenly. For querying the posts, I have a break in the form of the API itself. Each postId in the Post class starts with the value of the same groupId from the feed class and thus my query is mRealm.where(Post.class).beginsWith("postId", selectedGroup.getId()).findAll();

Sample groupId in my case is 1501186293533510 and some postIds are like 1501186293533510_1501187516866721, 1501186293533510_1501187493533390 etc

**Comment by kneth** [comment]
@slidenerd Can you share the code which does the update?

**Comment by slidenerd** [comment]
hi, i just formatted/cleared my data again and its working good, I am closing this issue, if any problem arises, I ll let you know, thank you very much for your time
