### ISSUE TITLE
Date query doesn't work with date greater than 2038-01-19

### ISSUE THREAD

**Issue by nartex** [realm/realm-java#1507]
All date queries (lessThan, lessThanOrEqual, between,...) doesn't work with date greater than Tue Jan 19 2038 04:14:07 GMT+0100 (CET) (Timestamp : 2147483647000).

Many "/1000" in TableQuery causing Integer cast.

I will make a pull request in few time.

**Comment by zaki50** [comment]
If `long / int` in Java code, `int` is promoted to `long`.

It seems that this problem comes from `static_cast<time_t>(value)` in jni code.

**Comment by kneth** [comment]
Good old `time_t` :-( As `time_t` is a typedef of `long`, it will be a 32 bit integer on 32 bit architectures, and 64 bit integer on a 64 bit architecture. Realm's underlying storage engine is using `time_t` in its constructor of date objects, and we are force to use only 32 bit values in order to have cross-architecture compatibility.

**Comment by kneth** [comment]
By the way, the limitation is documented in https://realm.io/docs/java/latest/#general (item 3).

**Comment by bmunkholm** [comment]
We also expect to provide a better datetime format with enhanced range and accuracy.

**Comment by zaki50** [comment]
@kneth @bmunkholm  That limitation is not described in cocoa/swift document.
Is that limitation really from underlying storage engine?

**Comment by nartex** [comment]
@zaki50 Thank you, I have always believed the opposite...
@kneth My bad, I deserve to fully read the doc, again :-).

**Comment by zaki50** [comment]
In https://github.com/realm/realm-cocoa/issues/2292#issuecomment-124780244
@segiddins showed that NSDate.distantPast() and NSDate.distantFuture() can be stored into Realm cocoa.

**Comment by kneth** [comment]
We are able to expand the date range - see #1510 to track progress.

**Comment by zaki50** [comment]
great news!

**Comment by zaki50** [comment]
I made PR #1511

**Comment by cmelchior** [comment]
As the issue is being tracked in #1510 and solved in #1511I will close this ticket here.
