### ISSUE TITLE
Overview of Realm Classes

### ISSUE THREAD

**Issue by timanglade** [realm/realm-java#1512]
Per this comment in https://github.com/realm/realm-java/pull/1265#issuecomment-144560453

**Comment by cmelchior** [comment]
Good idea, this could also be expanded with something like a Glossary on the most common Realm concepts. Something like https://github.com/google/caliper/wiki/Glossary

**Comment by donnfelker** [comment]
@timanglade @cmelchior Can I get some deeper context on what is required here so I can write it up during the holidays when others are out?

**Comment by cmelchior** [comment]
The idea is to have a section that should serve as a introduction to the Realm API which describe the purpose of the most common classes. The Reference to the Caliper Wiki is just an example of how it could be structured.

We should describe the following classes:
```
Realm
RealmConfiguration
RealmObject
RealmList
RealmQuery
RealmResults
```

We could consider the following as well:
```
DynamicRealm
DynamicRealmObject
RealmMigration
RealmSchema
RealmObjectSchema
```

But somehow they feel 2nd tier to me, and would just bloat a section which should give a primer to the API, so IMO we should leave them out.

**Comment by timanglade** [comment]
What @cmelchior said. On top of that, I pictured some sort of diagram of how the classes relate to each other (not in an OO sense but in a data sense) like a `Realm` contains `RealmObjects`, and so so `RealmResults` and `RealmLists`; `DynamicRealm` is an alternative to `Realm` that shows the same data, etc. Just a visual representation of that for people who are visually inclined.

I pictured this being at the root of the API docs rather than in the guide, but you could make the case for it to be the other way around (or in both).

**Comment by donnfelker** [comment]
The API docs, IMO, are usually some of the last places a developer will look for help. Some will, but most won't go there right away. They'll look online, using Google. If we want this to be easily found I advise we put this into the guide/doc.

**Comment by donnfelker** [comment]
Got this started in the https://github.com/realm/realm.io/issues/1706 repo

**Comment by timanglade** [comment]
To expand on the rationale of putting this in the API docs:
- I think a diagram like this is most helpful in the API index because right now our API index just assault you with a list of names that don’t make any sense to you unless you really know Realm. My intent wasn’t to better the guide; just to better the API reference :)
- the guide is purposefully organized by concept (model, queries, writes, etc.) not classes so it’s a little bit jarring to put the glossary there. 

That said, I could see a way this could be more organically added to our guide instead of the API reference. Just wanted to explain my thinking a bit more.

**Comment by cmelchior** [comment]
There is nothing wrong with the rationale, but:

a) It is extremely difficult to change how the Javadoc is generated, so it is much easier to have this outside the scope of the Javadoc.

b) I tried to play around with a few diagrams, and I couldn't come up with anything meaningful. If you have any drafts I am all ears, but I would rather leave it out than have a confusing diagram.

**Comment by donnfelker** [comment]
I agree with @cmelchior's comments about the Javadoc issue. Making that look nice is not that easy.

**Comment by timanglade** [comment]
Regarding (b) see my proposal here: https://github.com/realm/realm.io/pull/1717#issuecomment-181517149 

Regarding (a) if customizing Javadoc is impossible, it would be relatively trivial for us to inject HTML into the index.html file via CI every time the docs are updated. Should be easy to automate via simple shell script.

Would that address both of your concerns?
