### ISSUE TITLE
Help: I Want to change the encryptionKey without lossing any data.. the below code gives me IllegalStateException

### ISSUE THREAD

**Issue by riyase** [realm/realm-java#1514]
//because there is no option to change encryption key, i am copying all objects

        //old Configuration
        RealmConfiguration config0 = new RealmConfiguration.Builder(this)
                .name("riyas.realm")
                .schemaVersion(0)
                .encryptionKey(key.getBytes())  //old key
                .build();

        Realm realm = Realm.getInstance(config0);

        RealmResults<Contact> contacts = realm.allObjects(Contact.class);

        //doing a backup. so that i can use after "realm.close()"
        Contact[] contactsArray = contacts.toArray(new Contact[contacts.size()]);

        realm.close();
        
        //new configuration
        RealmConfiguration config1 = new RealmConfiguration.Builder(this)
                .name("riyas.realm2")
                .schemaVersion(0)
                .encryptionKey(key2.getBytes())  //new key
                .build();
        Realm realm2 = Realm.getInstance(config1);

        realm2.beginTransaction();
        realm2.copyToRealm(Arrays.asList(contactsArray));
        realm2.commitTransaction();

        realm2.close();
        //deleting old config
        Realm.deleteRealm(config0);

        Realm.setDefaultConfiguration(config1);

this whole code making an Exception 
java.lang.IllegalStateException: Illegal State: Table is no longer valid to operate on.

**Comment by emanuelez** [comment]
It is actually a supported use case, with this method: https://realm.io/docs/java/latest/api/io/realm/Realm.html#writeEncryptedCopyTo(java.io.File,%20byte[])

Happy coding! :)

**Comment by riyase** [comment]
@emanuelez Thanks.. so I can store realm file anywhere (internal/external memory)..
how can i access the stored realm file.. and start using it..?  RealmConfiguration has a name(String fileName) method.. is that a fileName or a complete filePath ?

**Comment by cmelchior** [comment]
@riyase It is the file name. The complete path is determined by the parameter to the Builder constructor. If you use `Context` it will be in `data/data/<packageName>/files/<name>` . The `File` parameter is the full path to the directory you want to save it in (e.g. SDCard)

**Comment by riyase** [comment]
i successfully copied realmFile with new key to sdCard. and read it from there..
but the same code not working when writing to app's databases folder ("/data/data/MY_PACKAGE/databases/")

here is my code

        RealmConfiguration config0 = new RealmConfiguration.Builder(this)
                .name("riyas.realm")
                .schemaVersion(0)
                .encryptionKey(key.getBytes())
                .build();
        Realm realm = Realm.getInstance(config0);

        String newDBFileName = "riyas.realm2";
        File newDBFile = getDatabasePath(newDBFileName);
        
        //File newDBFile = getSDCardFolder(newDBFileName);         //this file works fine

        try {
            realm.writeEncryptedCopyTo(newDBFile, key2.getBytes()); //this line makes the exception
        } catch (IOException e) {
            e.printStackTrace();
        }
        realm.close();

        RealmConfiguration config1 = new RealmConfiguration.Builder(newDBFile.getParentFile())
                .name(newDBFileName)
                .schemaVersion(0)
                .encryptionKey(key2.getBytes())
                .build();

        Realm.deleteRealm(config0);
        Realm.setDefaultConfiguration(config1);


this gives an exception
A/art: art/runtime/check_jni.cc:65] JNI DETECTED ERROR IN APPLICATION: input is not valid Modified UTF-8: illegal start byte 0xa0
A/art: art/runtime/check_jni.cc:65]     string: 'File not found: /data/data/com.riyase.realm/databases/riyas.real�.'


i did't gave the symbol '�' in file name

**Comment by kneth** [comment]
What device do you use? Can you share your Realm file?

**Comment by riyase** [comment]
sorry..my mistake. i was testing with a non rooted device..
i tested with a rooted device and the problem was..there was no folder named 'databases' in '/data/data/my_package'

so i created the folder just before writeEncryptedCopyTo() and now every thing is working fine. thanks for your support... :)

code:

        RealmConfiguration config0 = new RealmConfiguration.Builder(this)
                .name("riyas.realm")
                .schemaVersion(0)
                .encryptionKey(key.getBytes())
                .build();

        Realm realm = Realm.getInstance(config0);

        String newDBFileName = "riyas.realm2";
        File newDBFile = getDatabasePath(newDBFileName);
        if (!newDBFile.getParentFile().exists()) {
            newDBFile.getParentFile().mkdirs();
        }

        try {
            realm.writeEncryptedCopyTo(newDBFile, key2.getBytes());
        } catch (IOException e) {
            e.printStackTrace();
        }
        realm.close();

        RealmConfiguration config1 = new RealmConfiguration.Builder(newDBFile.getParentFile())
                .name(newDBFileName)
                .schemaVersion(0)
                .encryptionKey(key2.getBytes())
                .build();

        Realm.deleteRealm(config0);
        Realm.setDefaultConfiguration(config1);
