### ISSUE TITLE
Realm Model cannot compileReleaseWithJavac in android studio 1.4

### ISSUE THREAD

**Issue by povphearom** [realm/realm-java#1516]

**Comment by emanuelez** [comment]
Android Studio is not in charge of building your project: Gradle is.
Which version of the Android Gradle plugin are you using?

**Comment by cmelchior** [comment]
Hi @povphearom 
Please see https://github.com/realm/realm-java/blob/master/CONTRIBUTING.md#filling-issues when reporting an issue.

**Comment by cmelchior** [comment]
Closing due to no response
