### ISSUE TITLE
Relationship and strange behaviour of copyToRealmOrUpdate

### ISSUE THREAD

**Issue by StErMi** [realm/realm-java#1520]
I've a 2 classes

Category.java

```java
public class Category extends RealmObject {

    @PrimaryKey
    @SerializedName("id")
    private long id = -1;

    @SerializedName("name")
    private String name;

    @SerializedName("items")
    private RealmList<Item> items;

    //constructor, getters and setters

}
```

Item.java

```java
public class Item extends RealmObject {

    @PrimaryKey
    @SerializedName("id")
    private long id = -1;

    @SerializedName("name")
    private String name;

    @SerializedName("category")
    private Category category;

    //constructor, getters and setters

}
```

I use retrofit to get those first Categories and than Items and when I get the list of them I save into Realm like this

When I get categories from API they have not items initalized (it's an empty array)

```java
        Realm realm = Realm.getInstance(context);
        realm.beginTransaction();
        List<Category> categories = realm.copyToRealmOrUpdate(categories);
        realm.commitTransaction();
        realm.close();
```

When I get Items I have the category relationship inizialed (from json)
```java
        Realm realm = Realm.getInstance(context);
        realm.beginTransaction();
        List<Item> items = realm.copyToRealmOrUpdate(items);
        realm.commitTransaction();
        realm.close();
```

When I try to get the list of items of a category I get an empty list but if I try to get the category from an Item it's not null.

Why it's not correctly related?

**Comment by beeender** [comment]
@StErMi I don't really get what is your problem. When you call `realm.copyToRealmOrUpdate()`, what are the input there? Are `categories` and `items` empty list?

**Comment by StErMi** [comment]
@beeender in the first API call category.getItems() is empty because that API is giving me only the category detail without all the items list.

The second call instead is giving me details about the Item so item.getCategory() has a correct Category.

What I don't get is why Realm is not creating the relationship category.getItems() when I save the item (that has the relationship with the category and item.getCategory() has a corret value).

When after those API calls I query categories and I try to access category.getItems() it should correctly lazyloading all items I associated with the category right? Instead I get an empty list.

**Comment by beeender** [comment]
@StErMi I am sorry but I still don't get you question. What does you JSON response look like?

When you get items, `Item.category` cannot be automatically mapped to the categories you created before since there is no primary key for `Category`. If you want to do that, you could: Use primary key for `Category` or call `Item.setCategory` to set it to one category which is created in Realm before.

**Comment by StErMi** [comment]
@beeender sorry, I've updated right now the first post with a detailed Class description. 

The first API will return a list of Categories with Category.items empty. It will save the category inside realm.

```json
[
    {
        "id": 98,
        "name": "Shoes"
    }
]
```

The second API will return a list of Items with a valid Item.category. I will save it to realm and I can correctly access to item.category from realm.

```json
[
    {
        "id": 1354,
        "name": "AC80047A5",
        "category": {
            "id": 98,
            "name": "Shoes"
        }
    }
]
```

The issue is that as far as I can see item.category.items() is empty. Am I doing something wrong or am I using realm in the wrong way?

**Comment by beeender** [comment]
@StErMi It is quite normal that `category.items` is empty. Since no body actually adds item into `RealmList` items .

When the `Category` created in Realm, only `id` and `name` are saved. When the item created, Realm will try to create or update the `Category` based on the `id` which is the primary key of `Category` and save it to the `category` field of `Item`. However, at this point, Realm won't update the corresponding `Category`'s items since there is no way for Realm to know that should be updated as well.

For your case, i suggest after you created the item in Realm from JSON, do following to update the corresponding `Category` as well:

```
for (Item item : items) {
    RealmList<Item> itemList = item.getCategory().getItems();
    itemList.add(item);
}
```

**NOTE**: Above code **won't** check the duplicated items in the `Category`'s item list.

**Comment by StErMi** [comment]
@beeender Ok I thought that Ralm would create the relation from Category and Item when the Item (with the Category) is saved inside Realm.

Is there a way to specify that category.items should be a set and not an array in order to avoid duplicates? Which is the best way to handle it?

**Comment by beeender** [comment]
@StErMi Unfortunately set is not supported now. And the `contains` method doesn't have a optimized performance yet... see https://github.com/realm/realm-java/issues/897 .

**Comment by StErMi** [comment]
So there's not a real solution for this issue (at the moment)?

I think that how I'm trying to use Realm.io is a really common case
(offline usage of an app).

On Tue, Oct 6, 2015 at 9:14 AM, Chen Mulong <notifications@github.com>
wrote:

> @StErMi <https://github.com/StErMi> Unfortunately set is not supported
> now. And the contains method doesn't have a optimized performance yet...
> see #897 <https://github.com/realm/realm-java/issues/897> .
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/realm/realm-java/issues/1520#issuecomment-145765239>.
>



-- 

Founder e CEO di SurveyLab <https://surveylab.me/>

Skype: e.ricci.designfuture
Twitter: @StErMi <https://twitter.com/stermi>
Linkedin: https://www.linkedin.com/in/emanuelericci
Google+: https://plus.google.com/u/0/+EmanueleRicci/posts
Hangout: stermi@gmail.com

**Comment by beeender** [comment]
If you don't have too many items under category, add the item after checking by `contains` would just work with an acceptable performance. Or, you could just clear the item list before you add item (if it fit your use case well.).

**Comment by cmelchior** [comment]
Hi @StErMi 
Adding Set as a supported is tracked in this feature request as well https://github.com/realm/realm-java/issues/759. Until then then work-around given by @beeender would be the way to go about this.
