### ISSUE TITLE
0.83.0-SNAPSHOT annotation package missing

### ISSUE THREAD

**Issue by Kistamushken** [realm/realm-java#1521]
Hey, guys, I've been running 0.83.0-SNAPSHOT for 2 weeks now, but all of a sudden I've started getting errors during the build of the project. Btw, I've checkouted to the earlier commits of my project and I keep getting these errors:

  1) class file for io.realm.annotations.RealmClass not found
  2)  error: package io.realm.annotations does not exist

It seems like annotations class disappeared for some reason.

PS.
Everything is fine on 0.82.2

**Comment by emanuelez** [comment]
That is because we're experimenting with an alternative way to distribute Realm. I performed some tests in the morning so that's why you see such behavior. I will run a normal build soon so the SNAPSHOT should go back to normal.

**Comment by Kistamushken** [comment]
Okay, thanks for the reply.

**Comment by emanuelez** [comment]
A new version of the Jar should be uploaded now. Can you please confirm?

**Comment by kenticus** [comment]
I still get this error on my build machine. Maybe @Kistamushken can confirm

**Comment by kenticus** [comment]
Fixed.

**Comment by cmelchior** [comment]
You probably have to refresh the dependencies as SNAPSHOTs are normally cached for 24 hours:

```
./gradlew clean assemble --refresh-dependencies
```

But looks like you got it working anyway. So that is great.
