### ISSUE TITLE
Realm, relations and Parceler -> ERR: stack=java.lang.StackOverflowError: stack size 8MB

### ISSUE THREAD

**Issue by StErMi** [realm/realm-java#1522]
I've a 2 classes

Category.java

```java
public class Category extends RealmObject {

    @PrimaryKey
    @SerializedName("id")
    private long id = -1;

    @SerializedName("name")
    private String name;

    @SerializedName("items")
    private RealmList<Item> items;

    //constructor, getters and setters

}
```

Item.java

```java
public class Item extends RealmObject {

    @PrimaryKey
    @SerializedName("id")
    private long id = -1;

    @SerializedName("name")
    private String name;

    @SerializedName("category")
    private Category category;

    //constructor, getters and setters

}
```

When I query to get a category and use Parcles to pass the parcellable object from an Activity to another I got a 

```
ERR: stack=java.lang.StackOverflowError: stack size 8MB
```

because category has items and each of them has a category that has items and so on. This brings us to the StackOverflowError.

Is there a way to tell realm don't load from the database an attribute of the class (instead of SELECT * FROM category just SELECT name FROM category)?
Or is there a way to tell Parceler to just stop to the first or second level of recursivity?

**Comment by beeender** [comment]
@StErMi Try `Transient` annotation from parceler. See https://github.com/johncarl81/parceler/blob/master/parceler-api/src/main/java/org/parceler/Transient.java 

The stackoverflow is probably triggered by a infinite loop while building parcel object. `Item` has a `Category` whose list contains the same item. And that makes parceler into an infinite loop.

**Comment by StErMi** [comment]
@beeender yes, that's the case for sure, do you think that I've to find a solution from the Parceler side?

**Comment by beeender** [comment]
@StErMi As I mentioned. Maybe try `Transient` annotation from parceler on getters and setters to see if it helps?

**Comment by johncarl81** [comment]
@beeender is the `Item` `category` a reference to the `Category` parent?  In other words, is `category` and `items` different ends of a bi-directional relationship?

**Comment by StErMi** [comment]
@johncarl81 updated the first post with more detail on the Classes

**Comment by johncarl81** [comment]
Ok, it looks like the bi-directional relationship is the case and probably the reason why you're seeing this `StackOverflowError` exception.  As you pointed out, this is an open issue in Parceler, I'd like to treat an object graph more like Java serialization, but this complicates things, specifically object creation with constructors and factories.  In the end, this would look a lot like a dependency injection engine.

In short, @beeender is correct, you can use `@Transient` or the `transient` keyword to stop Parceler from running into an infinite loop while seralizing a bi-directional relationship:

```java
public class Item extends RealmObject {

    @PrimaryKey
    @SerializedName("id")
    private long id = -1;

    @SerializedName("name")
    private String name;

    @SerializedName("category")
    private Category category;

    //I assume you're using BEAN serialization technique, so you will need to annotate the getter:
    @Transient
    public Category getCategory(){...}
}
```

Keep in mind that post-marshaling `category` will be null.  If you want the parent `category` to be set you will need to do some post processing to reset this field.

**Comment by beeender** [comment]
@johncarl81 Thanks a lot for clarifying!
@StErMi Please let me know if it solved your issue.

**Comment by cmelchior** [comment]
@StErMi I'll assume the above answered your question. Please reopen if that is not the case.
