### ISSUE TITLE
java.lang.IllegalStateException: Changing Realm data can only be done from inside a transaction.

### ISSUE THREAD

**Issue by mubarak1361** [realm/realm-java#1528]
```
10-05 03:44:32.511    1402-1402/? E/AndroidRuntime﹕ FATAL EXCEPTION: main
    Process: com.test.materialup, PID: 1402
    java.lang.IllegalStateException: Changing Realm data can only be done from inside a transaction.
            at io.realm.internal.Table.throwImmutable(Table.java:1474)
            at io.realm.internal.Table.checkImmutable(Table.java:1074)
            at io.realm.internal.UncheckedRow.setString(UncheckedRow.java:207)
            at io.realm.PostRealmProxy.setBody(PostRealmProxy.java:92)
            at com.test.materialup.ui.PostActivity.onClick(PostActivity.java:107)
            at com.test.materialup.adapter.PostRecyclerAdapter$PostViewHolder$1.onClick(PostRecyclerAdapter.java:71)
            at android.view.View.performClick(View.java:4438)
            at android.view.View$PerformClick.run(View.java:18422)
            at android.os.Handler.handleCallback(Handler.java:733)
            at android.os.Handler.dispatchMessage(Handler.java:95)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5017)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:779)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:595)
            at dalvik.system.NativeStart.main(Native Method)
```

While changing a Post object value it gets crashing

```
 @Override
    public void onClick(int position) {
        Post post = postRecyclerAdapter.getPost(position);
        post.setBody("Hello Wolrd");
    }
```

**Comment by emanuelez** [comment]
A stacktrace is not the best way to issue a bug. Please take a look at https://github.com/realm/realm-java#getting-help

That being said it looks like you are trying to modify a Realm object outside of a transaction, which is not allowed.

**Comment by mubarak1361** [comment]
@emanuelez ya, am changing a realm object to update the adapter items.then how to fix this issue?

**Comment by dalinaum** [comment]
@mubarak1361 How about adding `beginTransaction()` before `post.setBody("Hello Wolrd")`? Do you still get IllegalStateException?

**Comment by mubarak1361** [comment]
@dalinaum ya got it thank you :)

**Comment by dalinaum** [comment]
@mubarak1361 Invoking `commitTransaction()` after modifying a Realm object might be needed too.

**Comment by dalinaum** [comment]
Did you solve your problem well, @mubarak1361 ?

**Comment by mubarak1361** [comment]
@dalinaum issue solved

**Comment by dalinaum** [comment]
Great. Please feel free to reopen if you encouter futher problems with this.

**Comment by killmario** [comment]
Thanks. So helped.

**Comment by MenilV** [comment]
This has become an issue with the Android's two way data binding. If I can't change the model directly I might as well ditch the way binding, or create a temp model to store data and then push it with commit to realm. Any workarounds with this?

**Comment by cmelchior** [comment]
You need to write Realm data inside an transaction, no way around that to ensure ACID.
What you can do is using `copyFromRealm` to copy the object to memory, attach it to two-way databinding and then do `copyToRealm` when done.

**Comment by MenilV** [comment]
Is it smart to open a transaction sometimes on the start of my activity's lifecycle like onCreate/onResume and simply close it on onPause/onDestroy? This way I can use the same model and use the full benefits of two way binding.

**Comment by cmelchior** [comment]
It would work yes, but transactions are blocking across all threads. So if you have a background thread doing a write when you start you suddenly ANR'ed your app.

**Comment by MenilV** [comment]
Good to know. Thanks

**Comment by Zhuinden** [comment]
@MenilV I'd opt against two-way databinding because synchronous writes on the UI thread can be blocking, but [one-way databinding isn't that difficult](https://github.com/realm/realm-java/issues/2716#issuecomment-244613866)

**Comment by sirvon** [comment]
@MenilV you might wanna check out this

[realm-1-2-0-android-data-binding](https://medium.com/@Zhuinden/realm-1-2-0-android-data-binding-1dc06822287f#.aa5s308ti)

**Comment by MenilV** [comment]
@sirvon yeah, actually an Observable is probably the way to go here. Didn't think of it right away.
btw @Zhuinden this article is great.

**Comment by iGhost1** [comment]
for every change of  data  from a object instance of a RealmObject class, for example in your case : 
     post.setBody("Hello Wolrd");
the Realm requires you to do it within a transaction, then use : 
     realm.beginTransaction();
     post.setBody("Hello Wolrd");
     realm.closeTransaction();
this will work.

**Comment by ebbnormal** [comment]
@cmelchior I get this error when I edit a object retrieved from Realm outside of a transaction. 

Currently in my system, for a given activity we do three things involving realm. 

1) everytime we make a service call for a list of Object, List<Cats> we persist the list received in realm from a function-scope-lived realm instance in our data manager
2) When a service call fails we grab a list of Cats from another function-scope-lived realm instance in our data manager
3) When we press a button in the activity we temporarily change the color of a cat (this is what throws the error if we are using a Realm persisted list of cats in the case of 2). 

I would like to freely allow any sequence of 1) 2) 3) but in a safe way. How can I do that. Do I just keep one realm instance in my data manager class and then update to that one so that I don't ANR the app?

**Comment by Zhuinden** [comment]
>  I get this error when I edit a object retrieved from Realm outside of a transaction.

well yes, you can only modify a RealmObject inside a transaction

> we temporarily change the color of a cat

from the perspective of Realm, there is no "temporarily" - you modify the object, it will have that property, such change can only be transactional and you must commit said transaction in order for the change to take place

**Comment by ebbnormal** [comment]
@Zhuinden that makes sense! thank you. But what about safely intermingling 1) 2) and 2) without conflict between the realm instances?

**Comment by ebbnormal** [comment]
will a opening of a asynchronous java realm transaction block all other realm instance transactions / insertions?

**Comment by Zhuinden** [comment]
Yes, there can only be 1 transaction open at a time to a given Realm file, on any thread and in any process

**Comment by pollux-** [comment]
If I do this
 ```
@Override
        public void bind(Choice object) {
            mCheckBox.setTag(object);
            mCheckBox.setText(object.getChoice());
            mCheckBox.setChecked(object.isSelected());
            mCheckBox.setOnCheckedChangeListener(new CompoundButton.OnCheckedChangeListener() {
                @Override
                public void onCheckedChanged(CompoundButton buttonView, final boolean isChecked) {
                    final Choice choice = (Choice) buttonView.getTag();
                    choice.setSelected(isChecked);
                    Realm dbInstance = DbManager.getInstance().getDBInstance();
                    dbInstance.executeTransaction(new Realm.Transaction() {
                        @Override
                        public void execute(Realm realm) {
                            choice.setSelected(isChecked);
                        }
                    });

                }
            });
        }
```

I'm getting below exception

**va.lang.IllegalStateException: Changing Realm data can only be done from inside a transaction.
07-13 21:30:34.596 23081 23081 E AndroidRuntime:        at io.realm.internal.Table.throwImmutable(Table.java:1138)
07-13 21:30:34.596 23081 23081 E AndroidRuntime:        at io.realm.internal.Table.checkImmutable(Table.java:924)
07-13 21:30:34.596 23081 23081 E AndroidRuntime:        at io.realm.internal.UncheckedRow.setBoolean(UncheckedRow.java:202)
07-13 21:30:34.596 23081 23081 E AndroidRuntime:        at io.realm.ChoiceRealmProxy.realmSet$isSelected(ChoiceRealmProxy.java:142)
07-13 21:30:34.596 23081 23081 E AndroidRuntime:        at com.chefd.tech.features.filter.model.Choice.setSelected(Choice.java:42)
07-13 21:30:34.596 23081 23081 E AndroidRuntime:        at com.chefd.tech.features.filter.adapter.FilterAdapter$ChoiceChild$1.onCheckedChanged(FilterAdapter.java:125)
07-13 21:30:34.596 23081 23081 E AndroidRuntime:        at android.widget.CompoundButton.setChecked(CompoundButton.java:156)
07-13 21:30:34.596 23081 23081 E AndroidRuntime:        at android.widget.CompoundButton.toggle(CompoundButton.java:115)
07-13 21:30:34.596 23081 23081 E AndroidRuntime:        at android.widget.CompoundButton.performClick(CompoundButton.java:120)
07-13 21:30:34.596 23081 23081 E AndroidRuntime:        at android.view.View$PerformClick.run(View.java:22429)
07-13 21:30:34.596 23081 23081 E AndroidRuntime:        at android.os.Handler.handleCallback(Handler.java:751)
07-13 21:30:34.596 23081 23081 E AndroidRuntime:        at android.os.Handler.dispatchMessage(Handler.java:95)
07-13 21:30:34.596 23081 23081 E AndroidRuntime:        at android.os.Looper.loop(Looper.java:154)
07-13 21:30:34.596 23081 23081 E AndroidRuntime:        at android.app.ActivityThread.main(ActivityThread.java:6119)
07-13 21:30:34.596 23081 23081 E AndroidRuntime:        at java.lang.reflect.Method.invoke(Native Method)
07-13 21:30:34.596 23081 23081 E AndroidRuntime:        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:886)
07-13 21:30:34.596 23081 23081 E AndroidRuntime:        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:776)**

executeTransaction actually wrap the begin and end transaction, then why I'm getting the exception ??
