### ISSUE TITLE
how to create datetime fields

### ISSUE THREAD

**Issue by ahhmarr** [realm/realm-java#1536]
How can i store datetime values ??

**Comment by cmelchior** [comment]
Normal Java `Date` objects are supported. Only restriction currently is that we truncate it to the nearest second. See #833 

Does this not cover your use case?

**Comment by ahhmarr** [comment]
so can i store something like 2015-10-10 01:32:59
and also perform sorting on it ?

**Comment by cmelchior** [comment]
Yes

**Comment by ahhmarr** [comment]
thnx a ton

**Comment by diskzzokejs** [comment]
*ahhmarr commented on Oct 6*
That realm can work with date-time. But I don`t see any example in realm.io
I tried "2015-11-25 23:25:00" and unix timestamp but realm returns NULL
Can someone provide me example, how to store and use *realm* with date-time: "2015-11-25 23:25:00"
