### ISSUE TITLE
Not enough precision when querying coordinates stored as double

### ISSUE THREAD

**Issue by shvelo** [realm/realm-java#1538]
I'm trying to obtain the set of objects that should be currently visible on the map, by using `between` to query for latitude and longitude inside a map's bounding box. The objects are located inside a small city, and I usually only need a single block. When querying the Realm, it returns the objects in the whole city, almost 1000 of them, adding them to the map causes huge system load. The app is written in Kotlin.

Query: 

```kotlin
val query = realm.where(BusStop::class.java)
      .between("lat", boundingBox.latSouth, boundingBox.latNorth)
      .between("lon", boundingBox.lonWest, boundingBox.lonEast)
```

[Class using the query](https://github.com/shvelo/tbilisi-bus/blob/rewrite-kotlin-full/app/src/main/kotlin/com/tbilisi/bus/util/MarkerHelper.kt)

BusStop model:

```kotlin
@RealmClass
public open class BusStop(): RealmObject() {
    @PrimaryKey
    public open var id = 0
    public open var name = ""
    public open var name_en = ""
    public open var lat = 0.0
    public open var lon = 0.0
}
```

[Model class](https://github.com/shvelo/tbilisi-bus/blob/rewrite-kotlin-full/app/src/main/kotlin/com/tbilisi/bus/data/BusStop.kt)

[Repository](https://github.com/shvelo/tbilisi-bus/tree/rewrite-kotlin-full)

**Comment by bmunkholm** [comment]
Hi @shvelo 
Could you try logging the values you put in the queries?
I'm just curious to see if the values are ordered correctly. `between(fieldName, from, to)` actually results in `(field => from and field <= to)`. It does look like it's done correctly from you naming. Just want to ensure.
It would also be helpful if you could print out some of the values for the matching objects and let us know if there is anything not correctly filtered in the query.
It's hard without more information to see what's wrong.

**Comment by shvelo** [comment]
Oh wait, I think it's my fault. The initial query happens before the map is zoomed into user location, and I forgot to limit minimum zoom for displaying the objects.

**Comment by bmunkholm** [comment]
Cool. Happy you got it fixed!
