### ISSUE TITLE
Document file related exceptions in Javadoc.

### ISSUE THREAD

**Issue by bmunkholm** [realm/realm-java#1541]

**Comment by cmelchior** [comment]
@bmunkholm Can you elaborate on this one?

**Comment by donnfelker** [comment]
+1

**Comment by bmunkholm** [comment]
The methods that can through file related exceptions (even the standard once), should have those exceptions documented in the Javadoc. We translate some of them from core to Java specific exceptions, but havn't documented that. Likely opening a Realm? Commiting?

**Comment by cmelchior** [comment]
Only the various `getInstance()` methods should be affected by this. A quick review shows that e.g `getInstance(context)` has a proper IO exception described, most other `getInstance`/`getDefaultInstance` seems to be missing this description.

**Comment by cmelchior** [comment]
Fixed by https://github.com/realm/realm-java/pull/1959
