### ISSUE TITLE
Add support for field type `char` and `Char`

### ISSUE THREAD

**Issue by beeender** [realm/realm-java#1542]

**Comment by beeender** [comment]
Cocoa binding won't support char since "we can't because BOOL is a char typedef"

**Comment by cmelchior** [comment]
That just put char in the same bucket as other platform specialized types as `URL`, `DateTime` and others IMO, so it shouldn't rule out us supporting it at some point. We just need to define the rules for platform specialised types.

**Comment by zaki50** [comment]
Is there any real use case for single char?
To support any single unicode character, we need at least 2 chars for surrogate pair.

**Comment by cmelchior** [comment]
The main reason is to have support for all primitive java types, which fits the idea of an object store. That said we haven't heard from anybody missing it yet.

**Comment by zaki50** [comment]
@cmelchior thanks. That's acceptable reason for me.

**Comment by beeender** [comment]
Close since it doesn't seem to be useful + will add lots of methods.

**Comment by cmelchior** [comment]
The completionist in me cries a little, but the pragmatic me says 👍
