### ISSUE TITLE
java.util.zip.ZipException: duplicate entry: io/realm/DefaultRealmModule.class

### ISSUE THREAD

**Issue by leisim** [realm/realm-java#1545]
While building my app the following error occurs:

:myapp:packageAllDebugClassesForMultiDex FAILED

FAILURE: Build failed with an exception.

\* What went wrong:
Execution failed for task ':myapp:packageAllDebugClassesForMultiDex'.
\> `java.util.zip.ZipException: duplicate entry: io/realm/DefaultRealmModule.class`

**Comment by cmelchior** [comment]
Are you using library projects that include Realm as well? Then there are some things to be aware of as described here: https://realm.io/docs/java/latest/#sharing-schemas

**Comment by leisim** [comment]
Thank you! That was the mistake...

**Comment by dalinaum** [comment]
Good. I'll close this issue. @leisim If the problem still persist, please feel free to reopen thi issue or open a new issue.

**Comment by riyase** [comment]
im having the same issue.. is there any way to find which library is internally using Realm.. i have more than 20 libs.

**Comment by cmelchior** [comment]
If you do `./gradlew dependencies` in your project it will output all your dependencies and their transitive dependencies as well.

**Comment by riyase** [comment]
the output was: 
:dependencies

------------------------------------------------------------
Root project
------------------------------------------------------------

No configurations

BUILD SUCCESSFUL

**Comment by cmelchior** [comment]
You have to do it in the project you need dependencies for, so if your app is in the `app` folder, it has to be something like:

```
./gradlew app:dependencies
```

**Comment by riyase** [comment]
thank you :+1:

**Comment by Junkeren44** [comment]
Remember to clean project after implementing the exposed library module.

**Comment by gustavomc** [comment]
how can i achieve this, im new to android, where do i put ```@RealmModule(library = true, allClasses = true)
public class MyLibraryModule {
}```

**Comment by mhdtouban** [comment]
@cmelchior even with module set, there's this issue happening  when you use android support library version 25.3.1 while it's working fine with 25.0.0.

**Comment by bhavyavklabs** [comment]
Hi ,

Even I am getting the same when I am using external library projects. 

https://forums.realm.io/t/realm-build-error-while-adding-an-external-sdk-duplicate-entry-io-realm-defaultrealmmodule-class/193

**Comment by vamshikhoslalabs** [comment]
Even i'm facing the same issue can some one look into this..
