### ISSUE TITLE
minimumDate query returns 1.1.1970 if table is empty

### ISSUE THREAD

**Issue by Kelt** [realm/realm-java#1546]
Not sure if bug or feature, but query for minimumDate on empty table returns 1.1.1970 Date object ... Which is 0 epoch  time ... the other option, which would maybe? make more sense would be to return null? 

Documentation doesnt cover/explain this case

https://realm.io/docs/java/latest/api/io/realm/RealmQuery.html#minimumDate(java.lang.String)

**Comment by dalinaum** [comment]
Hi @Kelt. We just merged Nullable support to master. #1543 It should be part of the next release.

**Comment by cmelchior** [comment]
Yes. This should be fixed in master now so it will return `null` and should be part of 0.83.0. So closing this issue now.
