### ISSUE TITLE
Breaking change in Realm Version 0.83 - Database file format

### ISSUE THREAD

**Issue by svasquezm** [realm/realm-java#1553]
Hi guys, 

Currently I have My app using Realm version 0.82.2. In version 0.83 changelog I've seen 

```
 * BREAKING CHANGE: Database file format update. The Realm file created by this version cannot be used by previous versions of Realm.
```

So, what do you recommend to migrate my current users data to use Realm 0.83?

**Comment by emanuelez** [comment]
Hello!

Did you read our blog post about it? https://realm.io/news/realm-java-0.83.0/

**Comment by svasquezm** [comment]
Thanks a lot!

```
Your Realm files will automatically be migrated to new file format
```
I will be more aware about Realm's news. I've just read the changelog file :P

**Comment by emanuelez** [comment]
Happy coding! :)
