### ISSUE TITLE
how to remove Items 

### ISSUE THREAD

**Issue by mjliu** [realm/realm-java#1557]
@beeender 
when I use realm ,I want to delete some data.I find clear() and remove(). but I want to remove some Items,what should I do?
example : removeAll(items)

**Comment by beeender** [comment]
@mjliu 
If the `items` you talked about is a `RealmResults`, you can simply use `RealmResults.clear()` to delete all of them.

If the `items` is a `RealmList`, it requires more manual steps. `RealmList.clear()` won't delete relevant RealmObject, but just remove them from the list.

For now, you can try something like following:
```
for(RealmChapter chapter: realmUnit.getChapters) {
    chapter.removeFromRealm()
}
```
This will also remove the objects from corresponding `RealmList` as well.

**Comment by mjliu** [comment]
@beeender 
ok I know. if I want to remove some Items from list, it just use 
for(RealmChapter chapter: realmUnit.getChapters) {
    chapter.removeFromRealm()
}

it hasn't any functions like Arraylist.removeAll(items) ?

**Comment by beeender** [comment]
No, there isn't :(

But this should be, we have `delete(RealmList)` function call in Realm Objective C & Swift.
I created an issue https://github.com/realm/realm-java/issues/1560 to track this problem.
