### ISSUE TITLE
Better exception message for setObject(standaloneObject)

### ISSUE THREAD

**Issue by beeender** [realm/realm-java#1558]
Currently a `NullPointerException` will be thrown since `value.row` is null.
We should have a better exception message for it.

**Comment by beeender** [comment]
See http://stackoverflow.com/questions/33010688/setting-a-realmobject-to-another-realmobject-after-retrieving-it-from-realm/33029428#33029428 for the confusion from user.

**Comment by cmelchior** [comment]
Should we instead do a `copyToRealm/copyToRealmOrUpdate` behind the users back if needed? This is e.g. what `RealmList.add()` does.

**Comment by cmelchior** [comment]
This is now being supported, we do a `copToRealm/copyToRealmOrUpdate` if a unmanaged object is being added to a managed one.
