### ISSUE TITLE
Raw Queries / Text Based Query Language

### ISSUE THREAD

**Issue by ahhmarr** [realm/realm-java#1573]
is there any method to pass raw query 
ex:
realm.where(User.class)
        .rawQuery("id>12 and deleted_at is not null")
        .findAll();

**Comment by zaki50** [comment]
@ahhmarr Realm Java does not support raw query for now.

**Comment by tgoyne** [comment]
Note that the query builder functionality is not building up a query string which is then parsed by a different layer. String-based queries would actually be built on top of the current query functionality, which is a fairly thin wrapper around the low-level query engine.

**Comment by cmelchior** [comment]
Yes, that was my impression as well. This issue would require the Java side being able to create some kind of AST  that corresponds to the the current query methods available in core.  I assume that ObjC piggybacks on NSPredicate to do the actual parsing so there is no real code we can copy from there?

**Comment by tgoyne** [comment]
Yes, NSPredicate gives us an AST which we convert to core query nodes.

**Comment by dalinaum** [comment]
@tgoyne Does [realm-cocoa](https://github.com/realm/realm-cocoa) use `NSPredicate` for the query builder now?

**Comment by Zhuinden** [comment]
Just the other day I thought this could actually be nice in order to have the query language used in `realm-js`: https://realm.io/docs/javascript/latest/#filtering

**Comment by Zhuinden** [comment]
This is becoming more relevant now with that core Query parser thing you have in the core thing

**Comment by cmelchior** [comment]
https://github.com/realm/realm-java/pull/6116 merged support for String-based query predicates. This will be part of 10.4.0.
