### ISSUE TITLE
Best way to get an empty realmresults object

### ISSUE THREAD

**Issue by slidenerd** [realm/realm-java#1575]
Hi guys,

I load data from json into realm but my adapter needs a realm results object in its constructor. I could replace the adapter each time but I would like to swap the data instead of the whole adapter. As of now I get an empty RealmResults object by querying a value that doesn't exist in the database, what would be the recommended or best way to get an empty realmresults object that be used as a dummy till real data is available?

Thanks for your answers in advance

**Comment by zaki50** [comment]
@slidenerd Currently we don't have a method that always returns empty RealmResults.

**Comment by slidenerd** [comment]
Thank you for the answer @zaki50 so if I need to construct an adapter which has no data initially, then querying for something that doesnt exist is the best way to get an empty realm results object in terms of performance and functionality?

**Comment by beeender** [comment]
@slidenerd Are you using `RealmBaseAdapter`? You can create the adapter by passing a `null` as the `RealmResults` and call `updateRealmResults` to pass the real `RealResults` later when the data is available.

**Comment by slidenerd** [comment]
thanks @beeender  i am closing this issue now

**Comment by dalinaum** [comment]
Is it enhancement? Is there any plan to add this feature?

**Comment by cmelchior** [comment]
Not really. You can easily work around it in your own adapter, just like our RealmBaseAdapter with an update method. Also #896 actually introduces the "empty" RealmResults.

**Comment by dalinaum** [comment]
OK. I will change it from `enhancement` to `help`.
