### ISSUE TITLE
please update README.md to add 'how to install android-ndk r10d'

### ISSUE THREAD

**Issue by ZeroBrain** [realm/realm-java#1576]
android-ndk-r10d was deprecated in home-brew.

so it had to install from Public Android Page.
(https://developer.android.com/ndk/downloads/index.html)

but it didn't include r10d.

so I downloaded manually android-ndk r10d.

### Mac
> http://dl.google.com/android/ndk/android-ndk-r10d-darwin-x86_64.bin

### Windows 64bit
> https://dl.google.com/android/ndk/android-ndk-r10d-windows-x86_64.exe

if @realm-java don't update to support r10e soon, then please update README.md.

**Comment by ZeroBrain** [comment]
or how about does it add to wiki

**Comment by dalinaum** [comment]
Although I made a homebrew/versions tap, it cannot be passed their test. It uses deprecated system OpenSSL.
https://github.com/Homebrew/homebrew-versions/pull/989

We will update r10e. It requires that our core uses r10e too and takes time. So I should update README.md for r10d now.

**Comment by ZeroBrain** [comment]
@dalinaum thanks for your reply.
