### ISSUE TITLE
Attempt to invoke virtual method 'long java.lang.Long.longValue()' on a null object reference

### ISSUE THREAD

**Issue by chonamdoo** [realm/realm-java#1580]
RealmQuery<CallStickerMenuDB> menuquery = realm.where(CallStickerMenuDB.class);
                        menuquery.equalTo("prid",mPrid);
                        long seq = menuquery.maximumInt("menuSeq");
                        int menuSeq = (int)(seq+1);

**Comment by beeender** [comment]
Hi @chonamdoo ,

By introducing the null support, the aggregate interface changed a bit.
1. `maximumInt` is deprecated. If max related function is called on an empty results query or query's results are all null values, `maximumInt` will throw an exception.
2. Please use `RealmQuery.max` instead. See doc [here](https://realm.io/docs/java/latest/api/io/realm/RealmQuery.html#max-java.lang.String-).  
> if no objects exist or they all have null as the value for the given field, null will be returned. Otherwise the maximum value is returned. When determining the maximum value, objects with null values are ignored.

**Comment by cmelchior** [comment]
Hi @chonamdoo I assume the above answered your question, so i'll close this now. Please reopen if that is not the case.
