### ISSUE TITLE
how to add tables during migration?

### ISSUE THREAD

**Issue by chandana1212** [realm/realm-java#1582]
Hi,
I have few new tables in the new schema. How can I achieve this through migration ? After the schema change I need to access the data from the old realm file too. Is there any way to achieve that ?

When I add new tables directly without migration call I am getting Realm migration exception. I don't know how to do migration for new tables . Can you plz help me.

Following is the exception which I got after the adding new tables.

java.lang.RuntimeException: Unable to create application com.rapidbizapps.dbs.common.CommonApplication: io.realm.exceptions.RealmMigrationNeededException: RealmMigration must be provided
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4412)
at android.app.ActivityThread.access$1500(ActivityThread.java:139)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1270)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:136)
at android.app.ActivityThread.main(ActivityThread.java:5086)
at java.lang.reflect.Method.invokeNative(Native Method)
at java.lang.reflect.Method.invoke(Method.java:515)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
at dalvik.system.NativeStart.main(Native Method)
Caused by: io.realm.exceptions.RealmMigrationNeededException: RealmMigration must be provided
at io.realm.Realm.migrateRealm(Realm.java:1655)
at io.realm.Realm.migrateRealm(Realm.java:1640)
at io.realm.Realm.create(Realm.java:572)
at io.realm.Realm.getInstance(Realm.java:413)
at io.realm.Realm.getInstance(Realm.java:370)
at io.realm.Realm.getInstance(Realm.java:351)
at com.rapidbizapps.dbs.queuing.QueuingApplication.onCreate(QueuingApplication.java:20)
at com.rapidbizapps.dbs.common.CommonApplication.onCreate(CommonApplication.java:66)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1030)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4409)
            at android.app.ActivityThread.access$1500(ActivityThread.java:139)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1270)
            at android.os.Handler.dispatchMessage(Handler.java:102)
            at android.os.Looper.loop(Looper.java:136)
            at android.app.ActivityThread.main(ActivityThread.java:5086)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:515)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:785)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:601)
            at dalvik.system.NativeStart.main(Native Method)

**Comment by zaki50** [comment]
Hi @chandana1212
Did you check migration example project?

// how to provide Migration instance.
https://github.com/realm/realm-java/blob/v0.83.0/examples/migrationExample/src/main/java/io/realm/examples/realmmigrationexample/MigrationExampleActivity.java#L60-L85

// implementation of Migration logic
https://github.com/realm/realm-java/blob/v0.83.0/examples/migrationExample/src/main/java/io/realm/examples/realmmigrationexample/model/Migration.java#L34

I think this migrationExample project will help.

**Comment by chandana1212** [comment]
I tried that migration logic but still I am getting migration error. Below is my code

Version 0 :
public class Person extends RealmObject {
    private int age;

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }
}

// Application class
Realm.migrateRealm(configuringRealm());
mRealm = Realm.getInstance(configuringRealm());

 public RealmConfiguration configuringRealm() {
        RealmConfiguration config = new RealmConfiguration.Builder(getApplicationContext())
                .schemaVersion(0)
                .migration(new Migration())
                .build();

        return config;
    }

// Version 1
public class Location extends RealmObject {
    private String name;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}
public class Person extends RealmObject {
    private int age;

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }
}

//Application class
Realm.migrateRealm(configuringRealm());
mRealm = Realm.getInstance(configuringRealm());

public RealmConfiguration configuringRealm() {
        RealmConfiguration config = new RealmConfiguration.Builder(getApplicationContext())
                .schemaVersion(1)
                .migration(new Migration())
                .build();

        return config;
    }
//Migration
public class Migration implements RealmMigration {
    @Override
    public long execute(Realm realm, long version) {
        if(version == 1){
            Table table = realm.getTable(Location.class);
            table.addColumn(ColumnType.STRING,"name");
        }
        return version++;
    }
}

**Comment by zaki50** [comment]
@chandana1212 your migration logic should check `if (version == 0)` instead of `if(version == 1)`
since you migrate the database version `0`. And should return `1` which is your latest schema version.


```
//Migration
public class Migration implements RealmMigration {
    @Override
    public long execute(Realm realm, long version) {
        if(version == 0){
            Table table = realm.getTable(Location.class);
            table.addColumn(ColumnType.STRING,"name");
            version++;
        }
        return version;
    }
}
```

**Comment by chandana1212** [comment]
I modified the migration logic as you said but still I am getting Migration Exception.

Version 0 :

public class Person extends RealmObject {
    private int age;

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }
}
// Application class
Realm.migrateRealm(configuringRealm());
mRealm = Realm.getInstance(configuringRealm());

 public RealmConfiguration configuringRealm() {
        RealmConfiguration config = new RealmConfiguration.Builder(getApplicationContext())
                .schemaVersion(0)
                .migration(new Migration())
                .build();

        return config;
}
Version 1:

// this Location table is not present in the version 0. 
public class Location extends RealmObject {
    private String name;

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}

public class Person extends RealmObject {
    private int age;

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }
}
//Application class
Realm.migrateRealm(configuringRealm());
mRealm = Realm.getInstance(configuringRealm());

public RealmConfiguration configuringRealm() {
        RealmConfiguration config = new RealmConfiguration.Builder(getApplicationContext())
                .schemaVersion(1)
                .migration(new Migration())
                .build();

        return config;
    }
//Migration
public class Migration implements RealmMigration {
    @Override
    public long execute(Realm realm, long version) {
        if(version == 0){
            Table table = realm.getTable(Location.class);
            table.addColumn(ColumnType.STRING,"name");
        }
        return version++;
    }
}

**Comment by zaki50** [comment]
@chandana1212 please reopen or post new issue if you'll have further question.

**Comment by chandana1212** [comment]
Okay Thank you.

**Comment by mayanksrivastavvs** [comment]
if (oldVersion == 1) {
            schema.get("Person")
                    .addField("email", String.class)
                    .transform(new RealmObjectSchema.Function() {
                        @Override
                        public void apply(DynamicRealmObject obj) {
                            if (obj.get("fullName").equals("fgg"))
                            {
                                obj.set("email","fgg@123");
                            }
                            if (obj.get("fullName").equals("fhjAge"))
                            {
                                obj.set("email","fhj@123");
                            }
                        }
                    });
            oldVersion++;
        }

i don't understand why it gives null object reference at   schema.get("Person")...pls help me

**Comment by zaki50** [comment]
Hi @mayanksrivastavvs 
Please create a new issue for different question.
Thanks

**Comment by mayanksrivastavvs** [comment]
java.lang.NullPointerException: Attempt to invoke virtual method 'io.realm.RealmObjectSchema io.realm.RealmObjectSchema.addField(java.lang.String, java.lang.Class, io.realm.FieldAttribute[])' on a null object reference

**Comment by mayanksrivastavvs** [comment]
if (oldVersion == 1) {
schema.get("Person")
.addField("email", String.class)
.transform(new RealmObjectSchema.Function() {
@Override <https://github.com/Override>
public void apply(DynamicRealmObject obj) {
if (obj.get("fullName").equals("fgg"))
{
obj.set("email","fgg@123");
}
if (obj.get("fullName").equals("fhjAge"))
{
obj.set("email","fhj@123");
}
}
});
oldVersion++;
}

i want to add field email in person table during migration this is my code.

**Comment by bmunkholm** [comment]
Hi @mayanksrivastavvs 
We would love to help you, but please do create a new issue. We are normally not tracking already closed issues, and it becomes quite messy since the title is no longer reflective of the issue, and hence other people can't find solutions to similar issues.
Thanks.
