### ISSUE TITLE
RealmResults(Realm realm, Class<E> classSpec) is unused and broken.

### ISSUE THREAD

**Issue by zaki50** [realm/realm-java#1583]
This constructor sets `table` field to `null` and that leads to returning `Table` instance from `getTable()` method. Most codes in `RealmResults` expect `TableView` instance instead of `Table` and do not work properly.

I propose simply to remove this constructor.

**Comment by beeender** [comment]
It might be for creating `RealmResults` directly on `Tables`. But it is not called by outside at all.

@emanuelez might know why do we have that.

**Comment by cmelchior** [comment]
I it's removed in my Dynamic API branch.

**Comment by zaki50** [comment]
@cmelchior nice. I close this issue.
