### ISSUE TITLE
Support Eclipse/ant with the new build system?

### ISSUE THREAD

**Issue by nhachicha** [realm/realm-java#1591]
As we're moving towards a build system based on a Gradle plugin + AAR archive. We may have problems supporting Eclipse/Maven/Ant, build system, especially after we introduce our byte code manipulation. This issue tries to get a feeling/necessity of this plugin from the community.

when :+1: please provide your use case/arguments as well as why you still using Eclipse despite Google stopping the official support & moving to AS

**Comment by cmelchior** [comment]
Since there doesn't seem to be any interest in this, I'm closing the issue.
