### ISSUE TITLE
Documentation/Motivation behind the new build system

### ISSUE THREAD

**Issue by nhachicha** [realm/realm-java#1592]
There is a breaking change with the upcoming build system based on a Gradle plugin + AAR archive, we need to document whey we're moving towards this approach (we need to announce the breaking change for the 0.94.0) so the community have the time to adapt & test the new distribution model

**Comment by cmelchior** [comment]
This is solved when we publish https://github.com/realm/realm.io/pull/1278/files
We should update the website documentation when releasing #909

**Comment by cmelchior** [comment]
A blog post describing this change has been posted.
