### ISSUE TITLE
Tracking the changes of the new distribution model AAR + plugin

### ISSUE THREAD

**Issue by nhachicha** [realm/realm-java#1593]
- [ ] documentation explaining the motivation behind this change #1592
- [ ] up/down-vote a UC to have a plugin for ant/eclipse #1591

**Comment by donnfelker** [comment]
Is Realm going to support Eclipse/Ant even though Android has said they're no longer supporting ADT anymore? https://twitter.com/AndroidDev/status/669314468518621184

**Comment by cmelchior** [comment]
@donnfelker Probably not but that mostly depends on community interest, which will be tracked in #1591

**Comment by cmelchior** [comment]
I'll close this issue now as #1592 and #1591 should be sufficient to track this.
