### ISSUE TITLE
 java.io.NotSerializableException RealmList

### ISSUE THREAD

**Issue by yuwu** [realm/realm-java#1595]
java.io.NotSerializableException RealmList

**Comment by cmelchior** [comment]
Hi @yuwu 
It is intentional that a RealmList isn't serialisable as the data is already stored in Realm. What is your use case?

**Comment by yuwu** [comment]
thanks.

**Comment by redblood666** [comment]
and if that RealmList is null? i can serialize the object?

**Comment by zaki50** [comment]
No

**Comment by Zhuinden** [comment]
http://stackoverflow.com/a/43621950/2413303
