### ISSUE TITLE
Collection aggregate queries

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#1598]
It should be possible to query on aggregates from RealmLists in a model.

```
public class Foo extends RealmObject {
  private RealmList<Bar> bars;
  // ...
}
```

API will probably be a bit tricky as we don't have NSPredicate to piggyback on:

```
1) realm.where(Foo.class).equalTo("bars.count()", 10).findAll()
2) realm.where(Foo.class).equalTo("bars@min()", 0).findAll()
3) realm.where(Foo.class).maxEqualTo("bars", 0).findAll()
```

Good ideas are welcome that fits well in a fluent interface, some discussion can be found here: https://github.com/realm/realm-java/issues/975#issuecomment-147443908

Cocoa issue here: https://github.com/realm/realm-cocoa/pull/2476/files

**Comment by astigsen** [comment]
I prefer `realm.where(Foo.class).equalTo("bars.count()", 10).findAll()`. It is also more flexible in the way that you can add arguments, like `realm.where(Foo.class).equalTo("bars.sum(bas)", 10).findAll()`.

But you might want to consider adding a specific method for testing if the list is empty since that is such a common request: realm.where(Foo.class).isEmpty("bars").findAll()

**Comment by kneth** [comment]
With `realm.where(Foo.class).equalTo("bars.count()", 10).findAll()` it is a strange mixture of a fluent interface and a query language. I think `realm.where(Foo.class).count("bars").equalTo(10).findAll()` is better.

**Comment by cmelchior** [comment]
I agree adding methods inside strings is a bit dangerous, and very hidden if you don't know it exists. However doing `count("bars").equalTo(10)` just moves ambiguity to the object level, e.g. 

`count("bars").equalTo(10)` is legal, but `count("bars").beginGroup()` would not be. It is not unsolvable but will also introduce other headaches....

**Comment by beeender** [comment]
I believe we can restrict `count("bars").equalTo(10)` by using builder pattern? Or simply `count("bar", 10)`?

**Comment by cmelchior** [comment]
The problem with the builder pattern is that you need "close" methods to exit the inner scope. It will be possible but you would have code that looks like this:

`
realm.where(Foo.class)
  .count("bars")
     .equalTo("10")
  .done() // exit()/end()/whatever to exit scope
  .equalTo("name", "bar").
  .findAll();
```

 
 



Regarding `count("bars",10)`. We have many more methods than equalTo: min/max/average + lessThan/greaterThan, so

**Comment by beeender** [comment]
uh, not really. `count("bar")` could return something like `CountQuery` (Not a good name though)
and to get the count `CountQuery.value()`
or build up the next query `RealmQuery CountQuery.equalTo()`
Since you won't chain other things after that, `done()` is kind of redundant.

**Comment by cmelchior** [comment]
Yes, you would would need something like `CountQuery` to "scope" your fluent interface, but I don't see how you can avoid a "endScope" method unless you force it to the last in the chain. Can you give an example?

**Comment by beeender** [comment]
```
// This would just fail compiling since equalTo(String, String) is a method of RealmQuery, But here is CountQuery
realm.where(Foo.class)
  .count("bars")
  .equalTo("name", "bar").
  .findAll();
```
```
realm.where(Foo.class)
  .count("bars")
    .equalTo(10) // This would pass compiling since it returns RealmQuery here. Maybe change equalTo to another function name to avoid confusion?
  .equalTo("name", "bar").
  .findAll();
```

**Comment by cmelchior** [comment]
Thanks. I get what you mean now. Yes it would work. It would require coming up with new names for `equalTo`, `lessThan`, `greaterThan`, `lessOrEqualThan`, `greaterOrEqualThan` though, which would be pretty nightmarish. On the upside it would be type safe.

**Comment by Flydiverny** [comment]
For coming up with alternative names I guess theres a few alternatives, but none of them sound as good as the original ones: (my prefered alternative of the suggestions first)
- `equalTo` -> `exactly`, `sameAs`, `same`
- `lessThan` -> `max`, `fewerThan`
- `greaterThan` -> `min`, `moreThan`
- `lessOrEqualThan` -> `atLeast`
- `greaterOrEqualThan` -> `atMost`, `moreThanOrExactly` `atMostOrExactly`

etc
or one could simply remove `To` and `Than` from the method names we have and for `count(x)` use `equal`, `less`, `greater`, `lessOrEqual`, `greaterOrEqual`, though that might still be confusing

**Comment by nhachicha** [comment]
@cmelchior have you checked the builder pattern we use for async
https://github.com/realm/realm-java/blob/nh-async-query/realm/src/main/java/io/realm/internal/async/QueryUpdateTask.java
could be a nice way to force a close

**Comment by cmelchior** [comment]
Yes, that is the same approach @beeender is talking about. For it to work we would have to map out a [BNF](https://en.wikipedia.org/wiki/Backus%E2%80%93Naur_Form) of our query language and create an interface for each level I think.

@Flydiverny Thanks for the suggestions, the more proposals the better.

**Comment by rimeissner** [comment]
Is there an ETA when this feature is coming to Java? as it is already available for cocoa.

**Comment by kneth** [comment]
@rimeissner We can't give you an estimate but it is somewhat in the future.

**Comment by rimeissner** [comment]
Thanks for the feedback, looking forward to it.

**Comment by niiamon** [comment]
@kneth any movement on this?

**Comment by kneth** [comment]
@niiamon No, sorry. Aligning with the other Realm products and integrating with Realm Mobile Platform have had priority.

**Comment by cmelchior** [comment]
Core support was added here: https://github.com/realm/realm-core/pull/1029

**Comment by Zhuinden** [comment]
@cmelchior that core support seems to have been merged earlier than this post was made 😕

**Comment by cmelchior** [comment]
@Zhuinden Yes, which was probably what caused the issue to be created in the first place? Note it isn't marked as "Blocked".

**Comment by Zhuinden** [comment]
Fair enough 👍

**Comment by Zhuinden** [comment]
@cmelchior actually I'm not sure what I was talking about because https://github.com/realm/realm-core/pull/2504 this pull request is even closer

**Comment by marchy** [comment]
I'm pretty sure this is what you guys are discussing, but want to make sure you will support expressions / compound predicates in the subqueries to achieve same functionality that predicates have in Realm Cocoa:

For example, in Realm Cocoa we have:
``` Swift
Realm().objects( Plan.self )
    // show only ongoing plans
    .filter( "SUBQUERY(members, $member, $member.id == '\(User.currentUser.id)' && $member.attendance == 'Unknown').@count > 0" )
    // don't show plans which the user was not interested in
    .filter( "SUBQUERY(members, $member, $member.id == '\(User.currentUser.id)' && $member.interest != 'Uninterested').@count > 0" )
```

NOTE that not only can there be multiple 'filters' applied but in each one multiple conditions can be performed.



As for the API/syntax, why not just use accept a callback interface which Realm can call passing in the RealmQuery to be applied on the sub-objects?

For example:
``` Kotlin
// PROPOSED
plans = Realm.getDefaultInstance().where( Plan::class.java )
    .subquery( "members ", RealmSubquery<Member> { query:RealmQuery<Member> -> query
        // consider only users' membership
        .equalTo( "memberID", User.currentUser.id )
        // show only ongoing plans
        .equalTo( "attendance", Attendance.Unknown.toString() )
        // don't show plans which the user was uninterested in
        .notEqualTo( "interest", Interest.Uninterested.toString() )
    })
.findAll()
```

The suq-query would be a trivial callback interface:
``` Kotlin
// PROPOSED
public interface RealmSuqbuery<T extends RealmModel> {
   void query( query:RealmQuery<T> )
}

```

Seems like that wouldn't require the definition of new query operations nor have any context ambiguity with the parent query.

**Comment by Zhuinden** [comment]
`Realm.getDefaultInstance().where(` please don't do that, you'll have local instances that you cannot close

**Comment by kneth** [comment]
@marchy Thanks for the suggestion. I wonder how we can translate your proposed `.subquery` into efficient queries - calling Java from C++ is not going to speed up the query :-(

**Comment by marchy** [comment]
@kneth heh yes indeed, I was imagining you guys already translate these calls into the underlying provider invocations / internal QL (if there is a such thing), but the internal implementation would surely have to be specific to subqueries. I do think re-leveraging the API to generate these invocations for sub-queries would be ideal as it's cognitively easier to adopt/consume instead of requiring a separate API for semantically equivalent operations.

**Comment by cmelchior** [comment]
I have been thinking about this for the last couple of days after a support question. I would like to propose an API I think is a good alternative:

```
public class Aggregate {
    public static Aggregate count(String fieldName) { ... }
    public static Aggregate min(String fieldName) { ... }
    public static Aggregate avg(String fieldName) { ... }
    public static Aggregate max(String fieldName) { ... }
    public static Aggregate sum(String fieldName) { ... }
}

// Find all persons with more than 2 children
realm.where(Person.class).greaterThan(Aggreate.count("children"), 2).findAll();

// Find all persons with youngest child being 5
realm.where(Person.class).equalTo(Aggregate.min("children.age"), 5).findAll();

// With static import
realm.where(Person.class).greaterThan(count("children"), 2).findAll();
realm.where(Person.class).equalTo(min("children.age"), 5).findAll();

// We could easily extend the Aggregate class to return the textual representation we want to
// use at some point, like
// Aggregate.count("children").toString() -> "children.@count"
// Aggregate.min("children.age").toString() -> "children.@min.age"
```

**Comment by zaki50** [comment]
@cmelchior What the `Aggregate.count("children.children")` mean in your API? The sum of the count of children's children?

If so, we don't allow to write a query like `Person objects where the smallest count of its children's children is 3`, right?

E.g. `realm.where(Person.class).equalTo(min(count("children.children")), 3).findAll();` is not allowed.



That looks great.

We don't allow to write a query like

**Comment by cmelchior** [comment]
I don't think I have "children.children" anywhere?
The smallest count of the list doesn't really make sense, since a count is just a count, but perhaps you are thinking of something else?

**Comment by zaki50** [comment]
Ah, you didn't write `Aggregate.count("children.children")`, but do we allow for users to write `Aggregate.count("children.children")`?

I'm supposing to have Person defined like:
```
public class Person extends RealmObject {
    public String name;
    public RealmList<Person> children;
}
```

**Comment by cmelchior** [comment]
`children.children` would be a list-of-lists or your grand-children in this case. I don't think Core has support for that, but I would need to check. 

From a grammar point of view, it looks like something we should support, but if not, I would just document it as a current limitation and it can be added later.

**Comment by Zhuinden** [comment]
https://speakerdeck.com/jakewharton/the-resurgence-of-sql-droidcon-nyc-2017 slide 34 points out the lack of support for collection aggregate query.

**Comment by cmelchior** [comment]
Yes, we noticed :)

**Comment by beit46** [comment]
Hey guys, we are using your solution and ended up having this exact problem. We have childs of an object we need to count and we discover this limitation, we have a working solution on swift but for Android we find this problem. I see there have been a lot of movement on this direction, do you feel we are going to see a solution for this any time soon? Thanks a lot

**Comment by Zhuinden** [comment]
I just had a field that contained the count of elements and was updating that along with the list...

**Comment by beit46** [comment]
Yes ok there is a bazillion ways of doing that, I get it, but this is not the point :) I would love to understand if what Is discussed in this ticket is going to see an implementation soon or late.

Il 26 set 2017, 13:14 +0200, Gabor Varadi <notifications@github.com>, ha scritto:

**Comment by mgohin** [comment]
Any updates ? ;)

**Comment by Zhuinden** [comment]
The query parser is *huge* but it'd be needed to easily support any string-based predicates including aggregate collection queries: https://github.com/realm/realm-java/issues/5730

That is all I know

**Comment by Zhuinden** [comment]
I vote for `realm.where(Person.class).equalTo("dogs.@count", 2).findAll()`

**Comment by cmelchior** [comment]
Interesting, thanks. I think my biggest concern with that approach is where to strike the balance between type safety and "strings". I mean, we clearly do not a fully typesafe query system right now, but this seems to move it further out. I don't know if you have any thoughts on where that line is?

This was why I suggested something like 
```
// Without static imports
realm.where(Person.class).equalTo(Aggregate.count("dogs"), 2).findAll();

// With static imports
realm.where(Person.class).equalTo(count("dogs", 2), 5).findAll();
```

But maybe we should just support both, so `Aggregate.count()` just output what ends up being the string based representation.

**Comment by cmelchior** [comment]
@pvtai This is just suggestions so far. It hasn't been implemented yet.

**Comment by BosAtWork** [comment]
+ 1 for this issue. Today I am porting an iOS app to Android and couldn't transfer some queries as @count is not supported in Android.

In iOS it is using Keypath Collection Queries (@count, @min, @max, @sum, @avg) so not sure why that could not be supported in Android.

**Comment by Zhuinden** [comment]
The proposed APIs weren't that great so I think we're waiting for https://github.com/realm/realm-java/pull/6116 and hoping for the best (i am not a Realm member i do not know)

**Comment by anggrayudi** [comment]
@cmelchior I really hope that this feature will be added this year ASAP.

**Comment by Zhuinden** [comment]
I don't know why https://github.com/realm/realm-java/pull/6116 never happened.

**Comment by kneth** [comment]
@Zhuinden The `.so` will grow quite a lot.

**Comment by walid-ashik** [comment]
It's 2019, I still hope at some point of my development career, I'd like to see this issue would be closed! :(

**Comment by cmelchior** [comment]
https://github.com/realm/realm-java/pull/6116 merged support for String-based query predicates, which should support this. This will be part of 10.4.0.
