### ISSUE TITLE
NPE at BaseRealm.java:591

### ISSUE THREAD

**Issue by andrewthecoder** [realm/realm-java#1608]
Today I upgraded our app to Realm 0.83.1 from my previous patched build of 0.83.0

Unfortunately I've seen the "Cannot send message to Handler on a dead thread" error @cmelchior  and I were battling a couple of weeks ago, although I don't have much data to help track that down yet.

Also, there's a new NPE bug in BaseRealm.java which should be reasonably easy to figure out - here's the stack trace:

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void io.realm.internal.SharedGroupManager.advanceRead()' on a null object reference
at io.realm.BaseRealm$RealmCallback.handleMessage(BaseRealm.java:591)
at android.os.Handler.dispatchMessage(Handler.java:98)
at android.os.Looper.loop(Looper.java:135)
at android.app.ActivityThread.main(ActivityThread.java:5430)
at java.lang.reflect.Method.invoke(Native Method)
at java.lang.reflect.Method.invoke(Method.java:372)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:913)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:706)
```

I'm happy to help debug this with a custom build of realm-java with additional debug code next week, so let me know if there's anything in particular I should do to help. 
Obviously trying to narrow it down to a simple test case would be ideal but I won't be able to spend significant time doing anything like that until later next week.

Cheers,
Andrew

**Comment by cmelchior** [comment]
Getting an epiphany:

```
    protected void removeHandler() {
        handler.removeCallbacksAndMessages(null); // This does not not, in fact, remove the configured Handler.Callback  
        // Another thread can can get in here and post to the Handler because it is still in the Handler map. 
        handlers.remove(handler); // Now other threads are prevented from posting
        this.handler = null; // Handler is not GC'ed yet, so in theory the Callback is still "alive"
    }
```

The right solution:

```
    protected void removeHandler() {
        handlers.remove(handler); 
        handler.removeCallbacksAndMessages(null); 
        this.handler = null; // Handler is not GC'ed yet, so in theory the Callback is still "alive"
    }
```

@andrewthecoder It still need to test this hypothesis (not sure how), but it should be relatively easy to patch into your own branch if you want to test it.
