### ISSUE TITLE
[Feature] onChange get triggered for specific class's changes

### ISSUE THREAD

**Issue by eneim** [realm/realm-java#1612]
For now, I think Realm will notify change on Every transaction. So if I catch that event to update my UI, it's kinds of wasting resource. It will be nice if I can just take care of the Update from specific classes. Thanks.

**Comment by cmelchior** [comment]
Yes, right now it is triggered on every change. We are already tracking the feature here: #989, but we plan to do much more than just listening to class changes, e.g. we plan to add support for listening for changes to query results, individual objects and lists as well.

I'll close this as a duplicate.
