### ISSUE TITLE
Add support for multi-field comparisons

### ISSUE THREAD

**Issue by ghost** [realm/realm-java#1615]
How to compare two fields in android realm.io ?

**Comment by emanuelez** [comment]
We currently we don't support multi-column comparisons in the Java API, mostly because it's hard to make a nice API for it. We are thinking about some possible options.

**Comment by cmelchior** [comment]
Just adding `equalToField` would probably be easy, but the list is also a bit bigger which complicates it:

- notEqualTo
- Calculations on integer fields, eg. `2 * field1 > field2`
- does contains/startsWith/endsWith work on multiple fields?

**Comment by brozot** [comment]
+1

Hello I need to use this solution to make this comparison  : updateDate > than syncDate (these two dates are in the database). I want to fetch only the updated entities or there is another solution for this?

**Comment by Saketme** [comment]
Please consider adding support for this. I've been running `equalTo` and other operators in a loop :(

**Comment by eyalfein** [comment]
Came here looking for solution to this problem (now missing feature) too.
Looks like there is significant demand for it.
I am hoping it will be in the form of:
.equalTo(string, string), notEqualTo(string, string), etc - to compare compare two properties of the same entity.

**Comment by papagno** [comment]
No workaround at the moment? I can't select comparing two columns in any way?

**Comment by bmunkholm** [comment]
One workaround is to add a third boolean which is the result of the comparison you wan to make. You would then need to update that whenever the properties you compare changes.

The Core does support this, so anyone with time can make a PR. The first task is to propose a proper API, then it is trivial to implement (I'll be happy to provide pointers to the core API).

**Comment by nachogarrone** [comment]
I would like to have this feature too!

I want to filter my RealmResults in my adapter when the user types in a search text view. I want to filter by all the fields in RealmResults.

Example:
firstName -- lastName
John -- Johnnes

`constraint = "John J"
mRealmObjectList.where().contains("firstName", String.valueOf(constraint), Case.INSENSITIVE).or().contains("lastName", String.valueOf(constraint), Case.INSENSITIVE) `

This wouldn't receive any record. 

My workaround is to get all the fields in a temporal string and do the contains() in there. But i wonder how much it will cost if my table has a lot of rows...

**Comment by bdpham** [comment]
@bmunkholm I'd like some pointers on the core API please. When referring to the core API, are you talking about the cpp files that provide JNI functions?

**Comment by letronje** [comment]
+1 for this

**Comment by acib708** [comment]
+1 for calculations on integer fields, eg. `(qty / dailyAvg) < 3`

**Comment by vostreltsov** [comment]
+1

**Comment by NebirosFeR** [comment]
+1

**Comment by samvanderhyden** [comment]
+1 on this - it is possible in realm cocoa, seems like it should be here to!

**Comment by cmelchior** [comment]
The most common cases could probably be solved by adding the following methods

```
equalToField(field1, field2);
greaterThanField(field1, field2);
greaterThanOrEqualToField(field1, field2);
lessThanField(field1, field2);
lessThanOrEqualToField(field1, field2);
notEqualToField(field1, field2);
```

**Comment by Zhuinden** [comment]
I'm not sure how common this actually is. A possible workaround of course is to store the actual `boolean` for the fields you are interested in.

This feels like one of those things that would be better solved by exposing the query language that is already processed by partial sync: https://github.com/realm/realm-java/issues/1573#issuecomment-292805550

**Comment by trr-amsiq** [comment]
+1

**Comment by abou7mied** [comment]
+1
Any updates?

**Comment by diegomontoya** [comment]
Bump this. This is not just implementation issue but a performance issue. Currently users are relagated to do this to simluate the effect (kotlin). f1 and f2 are numeric.

r.where(table).filter { row.f1 < row.f2 }

The above looks simple enough but performance-wise we are doing filtering (with lots of native calls plus allocations) in jvm runtime rather than c++. With lots of rows this becomes a huge issue. 

The current accepted work-around is the "additional field computed" comparison but this method is not sustainable in a normal dev env where logic change all the time. Imagine changing schema and/or adding migration every time this logic changes. Yikes.

**Comment by inri** [comment]
Even worse if one of the values is updated by `copyToRealmOrUpdate()` with a JSON, so the setter for the Boolean-field won't be called and updated properly. Or am I wrong?

A big +1 from me too.

**Comment by ios4vn** [comment]
+1

**Comment by funct7** [comment]
Still? 😞

**Comment by Zhuinden** [comment]
Still hoping for optional support of https://github.com/realm/realm-java/issues/5730

**Comment by cmelchior** [comment]
https://github.com/realm/realm-java/pull/6116 merged support for String-based query predicates, which should support this. This will be part of 10.4.0.
