### ISSUE TITLE
Example using split APK

### ISSUE THREAD

**Issue by nhachicha** [realm/realm-java#1618]
#1585 introduce AAR format, it would be nice to add an example that showcase how we can use [split APK](http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits) to help reduce APK size

**Comment by emanuelez** [comment]
We could just convert one of the existing examples to use the feature

**Comment by nhachicha** [comment]
good idea

**Comment by dalinaum** [comment]
#1834 resolved this. I'll close this.
