### ISSUE TITLE
Migration ColumnType change error

### ISSUE THREAD

**Issue by hackerpex** [realm/realm-java#1620]
Hi.
I am trying to  change a value from int to String on migration process. 
I execute migration but after complete i lost a column of table and structure become corrupted.

this is my migration code, anyone  know if i am doing something wrong?

//old object

    private long id;
    private int codCna;
    private int codEmp;
    private int codTsa;
    private String codTst;
    private String sigUfs;
    private String sitReg;

//new object

    private long id;
    private String codCna;
    private int codEmp;
    private String codTsa;
    private String codTst;
    private String sigUfs;
    private String sitReg;

//migration

     if (version == 0 ) {

            //ajuste dos campos codCna e codTsa de int para string
            Table cnaest;
            cnaest = realm.getTable(CnaeStEntity.class);
            long oldcodCna = cnaest.getColumnIndex("codCna");
            long oldcodTsa = cnaest.getColumnIndex("codTsa");

            long newcodCna = cnaest.addColumn(ColumnType.STRING, "codCna");
            long newcodTsa = cnaest.addColumn(ColumnType.STRING, "codTsa");

           // ColumnType tmptype = cnaest.getColumnType(codCna);
            for (int i = 0; i < cnaest.size(); i++) {
                cnaest.setString(newcodCna, i, cnaest.getLong(oldcodCna, i) + "");
                cnaest.setString(newcodTsa, i, cnaest.getLong(oldcodTsa, i) + "");
            }
            cnaest.removeColumn(oldcodCna);
            cnaest.removeColumn(oldcodTsa);

            version++;
        }

**Comment by hackerpex** [comment]
thank you @dalinaum  but does not helped.

**Comment by cmelchior** [comment]
Hi @hackerpex 
You are creating the new new columns with the same name as the old ones. Which makes it undefined which column you get back when asking for it.

Instead create temporary columns you fill with data, delete the old ones and then rename your temporary columns. Something like:

```
        //ajuste dos campos codCna e codTsa de int para string
        Table cnaest;
        cnaest = realm.getTable(CnaeStEntity.class);
        long oldcodCna = cnaest.getColumnIndex("codCna");
        long oldcodTsa = cnaest.getColumnIndex("codTsa");

        long newcodCna = cnaest.addColumn(ColumnType.STRING, "codCnaTmp");
        long newcodTsa = cnaest.addColumn(ColumnType.STRING, "codTsaTmp");

       // ColumnType tmptype = cnaest.getColumnType(codCna);
        for (int i = 0; i < cnaest.size(); i++) {
            cnaest.setString(newcodCna, i, cnaest.getLong(oldcodCna, i) + "");
            cnaest.setString(newcodTsa, i, cnaest.getLong(oldcodTsa, i) + "");
        }
        cnaest.removeColumn(oldcodCna);
        cnaest.removeColumn(oldcodTsa);
        cnaest.renameColumn(cnaest.getColumnIndex("codCnaTmp"), "codCna");
        cnaest.renameColumn(cnaest.getColumnIndex("codTsaTmp"), "codTsa");
        version++;
```

**Comment by hackerpex** [comment]
i tryed it too @cmelchior . but had the same problem.
my usage  is just the same as found in example migration code here in git sources.
i just update realm lib and i am trying another approach. now i am adjusting for Require annotations.
i will return with results.

**Comment by hackerpex** [comment]
i finish migration with sucsses but had a issue when tryed to retrieve data.

this is error 
java.lang.IllegalArgumentException: Field 'codTsa2': type mismatch. Was INTEGER, expected STRING


and this is my new migration code

 if (version == 0 ) {

            //ajuste dos campos codCna e codTsa de int para string
            Table cnaest;
            cnaest = realm.getTable(CnaeStEntity.class);
            long oldcodTsa = cnaest.getColumnIndex("codTsa");

            long newcodTsa = cnaest.addColumn(ColumnType.STRING, "codTsa2");

           // ColumnType tmptype = cnaest.getColumnType(codCna);
            for (int i = 0; i < cnaest.size(); i++) {
                cnaest.setString(newcodTsa, i, String.valueOf(cnaest.getLong(oldcodTsa, i)) + "");
            }

            cnaest.removeColumn(oldcodTsa);


            version++;
        }

**Comment by hackerpex** [comment]
solved.
this is the final code:

 if (version == 0 ) {

            //ajuste do codTsa de int para string
            Table cnaest;
            cnaest = realm.getTable(CnaeStEntity.class);
            long oldcodTsa = cnaest.getColumnIndex("codTsa");

            long newcodTsa = cnaest.addColumn(ColumnType.STRING, "codTsa2");

           // ColumnType tmptype = cnaest.getColumnType(codCna);
            for (int i = 0; i < cnaest.size(); i++) {
                cnaest.setString(newcodTsa, i, String.valueOf(cnaest.getLong(oldcodTsa, i)) + "");
            }

            cnaest.removeColumn(oldcodTsa);
            cnaest.renameColumn(cnaest.getColumnIndex("codTsa2"), "codTsa");

      //just to check
        //    for (int i = 0; i < cnaest.getColumnCount(); i++) {
         //       String colName = cnaest.getColumnName(i);
         //       ColumnType colType = cnaest.getColumnType(i);
        //       colName = colName+" ";
       //     }

            version++;
        }
