### ISSUE TITLE
sharedgroup error

### ISSUE THREAD

**Issue by hackerpex** [realm/realm-java#1639]
Hi.
I am runing 0.83.1 and this error is showed in random situations when i try to retrieve Realm instance.
we work in a comercial app and aparently this error happens after some instances.

10-21 23:41:47.673 3543-3543/com.morphy.blukit W/dalvikvm: threadid=1: thread exiting with uncaught exception (group=0x4304b160)
10-21 23:41:47.693 3543-3543/com.morphy.blukit E/AndroidRuntime: FATAL EXCEPTION: main
10-21 23:41:47.693 3543-3543/com.morphy.blukit E/AndroidRuntime: Process: com.morphy.blukit, PID: 3543
10-21 23:41:47.693 3543-3543/com.morphy.blukit E/AndroidRuntime: io.realm.exceptions.RealmError: Unrecoverable error. mmap() failed: Out of memory in io_realm_internal_SharedGroup.cpp line 179
10-21 23:41:47.693 3543-3543/com.morphy.blukit E/AndroidRuntime:     at io.realm.internal.SharedGroup.nativeCommitAndContinueAsRead(Native Method)
10-21 23:41:47.693 3543-3543/com.morphy.blukit E/AndroidRuntime:     at io.realm.internal.SharedGroup.commitAndContinueAsRead(SharedGroup.java:94)
10-21 23:41:47.693 3543-3543/com.morphy.blukit E/AndroidRuntime:     at io.realm.internal.ImplicitTransaction.commitAndContinueAsRead(ImplicitTransaction.java:45)
10-21 23:41:47.693 3543-3543/com.morphy.blukit E/AndroidRuntime:     at io.realm.internal.SharedGroupManager.commitAndContinueAsRead(SharedGroupManager.java:103)
10-21 23:41:47.693 3543-3543/com.morphy.blukit E/AndroidRuntime:     at io.realm.BaseRealm.commitTransaction(BaseRealm.java:290)
10-21 23:41:47.693 3543-3543/com.morphy.blukit E/AndroidRuntime:     at io.realm.Realm.commitTransaction(Realm.java:112)
10-21 23:41:47.693 3543-3543/com.morphy.blukit E/AndroidRuntime:     at com.morphy.blukit.persistence_impl.localstorage.base.AbstractGatewayLocalStorage$4.executar(AbstractGatewayLocalStorage.java:232)
10-21 23:41:47.693 3543-3543/com.morphy.blukit E/AndroidRuntime:     at com.morphy.blukit.persistence_impl.localstorage.base.AbstractGatewayLocalStorage$4.executar(AbstractGatewayLocalStorage.java:216)
10-21 23:41:47.693 3543-3543/com.morphy.blukit E/AndroidRuntime:     at com.morphy.blukit.persistence_impl.data_manager.DataBaseManager.executarLoop(DataBaseManager.java:374)
10-21 23:41:47.693 3543-3543/com.morphy.blukit E/AndroidRuntime:     at com.morphy.blukit.persistence_impl.data_manager.DataBaseManager.executar(DataBaseManager.java:356)
10-21 23:41:47.693 3543-3543/com.morphy.blukit E/AndroidRuntime:     at com.morphy.blukit.persistence_impl.localstorage.base.AbstractGatewayLocalStorage.save(AbstractGatewayLocalStorage.java:216)
10-21 23:41:47.693 3543-3543/com.morphy.blukit E/AndroidRuntime:     at com.morphy.blukit.use_cases.orders.PedidoManagerUseCase.salvarPedido(PedidoManagerUseCase.java:362)
10-21 23:41:47.693 3543-3543/com.morphy.blukit E/AndroidRuntime:     at com.morphy.blukit.telas.orders.order.new_order.presenter.Presenter_Pedido.salvarPedidos(Presenter_Pedido.java:689)
10-21 23:41:47.693 3543-3543/com.morphy.blukit E/AndroidRuntime:     at com.morphy.blukit.telas.orders.order.new_order.presenter.Presenter_Pedido.criarPedidos(Presenter_Pedido.java:150)
10-21 23:41:47.693 3543-3543/com.morphy.blukit E/AndroidRuntime:     at com.morphy.blukit.telas.orders.order.new_order.presenter.Presenter_Pedido.onClickAddItems(Presenter_Pedido.java:299)
10-21 23:41:47.693 3543-3543/com.morphy.blukit E/AndroidRuntime:     at com.morphy.blukit.telas.orders.order.base.view.fragments.Fragment_Pedido_State.onClickAddItems(Fragment_Pedido_State.java:270)
10-21 23:41:47.693 3543-3543/com.morphy.blukit E/AndroidRuntime:     at com.morphy.blukit.telas.orders.order.base.view.fragments.Fragment_Pedido.onClickAddItems(Fragment_Pedido.java:464)
10-21 23:41:47.693 3543-3543/com.morphy.blukit E/AndroidRuntime:     at com.morphy.blukit.telas.orders.order.base.view.fragments.Fragment_Pedido.onClick(Fragment_Pedido.java:383)
10-21 23:41:47.693 3543-3543/com.morphy.blukit E/AndroidRuntime:     at android.view.View.performClick(View.java:4438)
10-21 23:41:47.693 3543-3543/com.morphy.blukit E/AndroidRuntime:     at android.view.View$PerformClick.run(View.java:18431)
10-21 23:41:47.693 3543-3543/com.morphy.blukit E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:733)
10-21 23:41:47.693 3543-3543/com.morphy.blukit E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:95)
10-21 23:41:47.693 3543-3543/com.morphy.blukit E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:149)
10-21 23:41:47.693 3543-3543/com.morphy.blukit E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5061)
10-21 23:41:47.693 3543-3543/com.morphy.blukit E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method)
10-21 23:41:47.693 3543-3543/com.morphy.blukit E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:515)
10-21 23:41:47.693 3543-3543/com.morphy.blukit E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:787)
10-21 23:41:47.693 3543-3543/com.morphy.blukit E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:603)
10-21 23:41:47.693 3543-3543/com.morphy.blukit E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)

**Comment by kneth** [comment]
Realm's underlying storage engine is using the system call `mmap()` to read and write data. When your app runs out of memory or disk space, `mmap()` will fail, and a `RealmError` will be thrown (your stack trace indicates this as the error message is `Unrecoverable error. mmap() failed: Out of memory`).

You can read more about memory issues in the [FAQ](https://realm.io/docs/java/latest/#faq). In particular *What to do about out-of-memory exceptions?* and *Large Realm file size*.

**Comment by hackerpex** [comment]
Solved.
The problem happens because we forgotten ream instances opened,
then database size increases exponentially. when we close every instance the problem was solved. 
i think its can be improved by realm team, because we can't revert it after error.
Tankyou for your help @kneth .
