### ISSUE TITLE
Realm object does not get updated on the background thread

### ISSUE THREAD

**Issue by Wattos** [realm/realm-java#1642]
I am trying to use realm for our application. I am currently running into an issue which is most likely a bug in realm.

*Setup*:
1) In a service I have a background thread
2) The background thread I have a realm object (which was created on the background thread)
3) On the main thread I add objects to realm
4) Query the realm on the background thread

*Expected*:
I should be able to see the newly inserted objects in realm when querying for them

*Observed*:
I do not see the newly inserted objects in realm when querying on the background thread. They are fine when I am querying them in the foreground thread.

I want to query realm in the background thread because it contains the messages I want to send asynchronously

*Work around*:
I need to open and close the realm before querying

**Comment by beeender** [comment]
@Wattos 
1. Is the service in a separate process? If yes, then the behaviour is not defined yet. We haven't finished the multi-processes support yet.
2. Does the background thread have a looper? If no, then you need to call `Realm.refresh` manually since our notification system relies on Looper and hanlders.

**Comment by Wattos** [comment]
@beeender Hey, thanks for the quick response. No, It is within the same process. My thread did not have a looper. Thanks for letting me know about refresh. It might probably be a good idea to add this information to the documentation. Currently it says:


*The only rule to using Realm across threads is to remember that Realm, RealmObject or RealmResults instances cannot be passed across threads. When you want to access the same data from a different thread, you should simply obtain a new Realm instance (i.e. Realm.getInstance(Context context) or its cousins) and get your objects through a query. The objects will map to the same data on disk, and will be readable & writeable from any thread*

**Comment by beeender** [comment]
@Wattos Actually we have documented that :P 

https://realm.io/docs/java/latest/#auto-refresh
