### ISSUE TITLE
Add @SuppressWarnings("cast") to generated getters

### ISSUE THREAD

**Issue by bryanjswift** [realm/realm-java#1644]
I'm currently working on a project which used the following in the project wide build.gradle:

    allprojects {
        gradle.projectsEvaluated {
            tasks.withType(JavaCompile) {
                options.compilerArgs << '-Xlint:all'
                options.compilerArgs << '-Werror'
            }
        }
    }

This caused errors when compiling the generated generated proxy classes. After a little research I believe adding the `@SuppressWarnings('cast')` annotation for the getters and setters (https://github.com/realm/realm-java/blob/f7147ee6bcc451d612babd54832f891d56ea7f35/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.java#L217 and https://github.com/realm/realm-java/blob/f7147ee6bcc451d612babd54832f891d56ea7f35/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.java#L243) would eliminate almost all of the linting errors.

**Comment by zaki50** [comment]
@bryanjswift Can you send the warning message?

**Comment by zaki50** [comment]
@bryanjswift I could reproduce that. Other than `cast` warnings, we unfortunately introduced new warnings `rawtypes` in 0.84.0.

We should fix both warnings.

**Comment by dalinaum** [comment]
Hi, @bryanjswift #1654 is merged into master. 0.84.1 will solve both warnings. I closed this issue. If you encounter further problem, please feel free to reopen this or create another issue.

**Comment by bryanjswift** [comment]
Glad to hear it. Thanks for the quick attention to this issue.
