### ISSUE TITLE
Kotlin @Required annotation not being detected?

### ISSUE THREAD

**Issue by corbt** [realm/realm-java#1647]
I have a Realm database I'm updating from 0.81-SNAPSHOT to 0.84. I use Kotlin.

When I open the database, I get the following error:

```
java.lang.RuntimeException: Unable to create application com.emberall.kiosk.TheApp: io.realm.exceptions.RealmMigrationNeededException: Field 'updatedAt' is required. Either set @Required to field 'updatedAt' or migrate using io.realm.internal.Table.convertColumnToNullable().
...
```

My model is as follows:

```kotlin
public open @RealmClass class Recording(
    @PrimaryKey
    @Expose public open var id: String = UUID.randomUUID().toString(),
    @Expose @Required public open var createdAt: Date = Date(),
    @Expose @Required public open var updatedAt: Date = Date(),

    @Expose @Required public open var name: String = "",
    @Expose @Required public open var videoFileStatus: String = "none", // "none", "device", "uploaded", "queued", "processed"
    @Expose public open var videoFileSize: Long? = null
) : RealmObject()
```

So, it looks like Realm isn't recognizing my `@Required` annotation -- any idea why?

**Comment by zaki50** [comment]
@corbt are you importing `io.realm.annotations.Required` correctly?

**Comment by cmelchior** [comment]
Hi @corbt Do you get that error when upgrading an old database or starting from a fresh one as well?

**Comment by corbt** [comment]
@zaki50 yes, I think I'm importing the annotations correctly

```kotlin
import io.realm.annotations.PrimaryKey
import io.realm.annotations.RealmClass
import io.realm.annotations.Required
```

@cmelchior the error appears when upgrading an old database. A fresh one appears to be working fine, although I don't know whether the field is really @Required or not -- I suspect it's still ignoring that annotation (the .realm file isn't opening in the Realm Browser on my computer for some reason, it claims it's in a format that can't be read).

**Comment by cmelchior** [comment]
Yes, sorry our Realm browser is not updated yet to support the new Null values. We are getting a new version improved by Apple currently, but you can download it from here: https://github.com/realm/realm-browser-osx/releases

**Comment by corbt** [comment]
Thanks for the info @cmelchior. I don't think that the issue is related to the realm browser incompatibility at all though -- would it still be helpful for me to download that version and check the database file generated by realm-java 0.84 (which works fine on the device) to see whether the field is listed as `@Required` or not? Actually it appears the database viewer doesn't even show that information, so opening the file probably won't give us any new information.

**Comment by zaki50** [comment]
@corbt please try `@field:Required` instead of `@Required`.

Realm Java requires field to be annotated.

please see https://kotlinlang.org/docs/reference/annotations.html#annotation-use-site-targets for more details.

**Comment by dalinaum** [comment]
@corbt Did you use `0.81-SNAPSHOT`? Although we actually highly appreciate developers using our SNAPSHOT releases, we recommend to use official releases for your app releases.

**Comment by corbt** [comment]
@zaki50 adding `@field:` was the ticket! Thanks everyone for your help. I've opened a PR to add the necessary annotations to `@Required` to bring it in line with other Realm field annotations, so hopefully once that's merged this will no longer be necessary.
