### ISSUE TITLE
missing ProGuard configuration for classes referred from jni code

### ISSUE THREAD

**Issue by zaki50** [realm/realm-java#1658]
from #1656

We should add following lines to ProGuard configuration in our documentation.

```
-keep class io.realm.exceptions.* { *; }
-keep class io.realm.internal.async.BadVersionException { *; }
-keep class io.realm.internal.OutOfMemoryError { *; }
-keep class io.realm.internal.TableSpec { *; }
-keep class io.realm.internal.Mixed { *; }
-keep class io.realm.internal.ColumnType { *; }
```

**Comment by zaki50** [comment]
Is there other classes to add?

**Comment by diegomontoya** [comment]
Following from latest dexguard-common.pro config.

```
-keep class * extends io.realm.RealmObject {
    void set*(***);
    *** get*();
}

-keep class **RealmProxy extends io.realm.RealmObject {
    public static <methods>;
}
```

**Comment by zaki50** [comment]
@diegomontoya We currently documented following proguard configuration.

https://realm.io/docs/java/latest/#proguard

```
-keep class io.realm.annotations.RealmModule
-keep @io.realm.annotations.RealmModule class *
-dontwarn javax.**
-dontwarn io.realm.**
```

And we don't need to configure `-keep` against model class or proxy class since we do not access such class by reflection after 0.81.1.

**Comment by zaki50** [comment]
We should consider introducing something like `Keep` annotation.

**Comment by kneth** [comment]
Currently, `io.realm.internal.Mixed` is not used in the object store API.

**Comment by zaki50** [comment]
@kneth I removed `-keep class io.realm.internal.Mixed { *; }` from PR.

**Comment by kneth** [comment]
@zaki50 Thanks. Maybe it is time to remove the `Mixed` class?

**Comment by cmelchior** [comment]
Wasn't there talk about it being potentially useful for Set/Map implementations?

**Comment by kneth** [comment]
@cmelchior Oh yes, we shouldn't removed it. When we need it again, we can add it to the ProGuard configuration.

**Comment by zaki50** [comment]
@cmelchior @kneth What do you think #1673 ?

**Comment by cmelchior** [comment]
I like the idea :+1:  It makes it easy to keep the ProGuard configuration up to date.

**Comment by kneth** [comment]
Smart - me like :+1:

**Comment by zaki50** [comment]
@cmelchior @kneth Can I merge this PR?

**Comment by zaki50** [comment]
@cmelchior @kneth Sorry, this not a PR.

**Comment by kneth** [comment]
@zaki50 #1673 is almost ready to be merged. And then this can be closed, right?

**Comment by zaki50** [comment]
@kneth yes, I think so.
