### ISSUE TITLE
RealmObjectProxy Genearated update() Method Can Skip PrimaryKey Field

### ISSUE THREAD

**Issue by diegomontoya** [realm/realm-java#1659]
Sample of a realmObjectProxy code

```java
    static RealmReview update(Realm realm, RealmMyClass realmObject, RealmMyClass newObject, Map<RealmObject, RealmObjectProxy> cache) {
        realmObject.setA(newObject.getA());
        realmObject.setB(newObject.getB());
        realmObject.setC(newObject.getC());
        realmObject.setD(newObject.getD());
        return realmObject;
    }
```

If field A is a designated Primary Key, there is no need to update the field with the same value and the entire .setX() call can be skipped.

**Comment by zaki50** [comment]
@diegomontoya Thank you for your suggestion.

Yes and we already skip the primary key.

https://github.com/realm/realm-java/blob/master/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.java#L740-L742

I found one more thing we can do about `update()`.
If the model class does not have any primary key, we do not need to generate `update()` method.

**Comment by zaki50** [comment]
I've created an issue #1660 for removing `update()` method.

I'll close this issue.
If I have overlooked something, feel free to reopen.

thanks.
