### ISSUE TITLE
Guidelines for keeping Realm opened forever

### ISSUE THREAD

**Issue by Saketme** [realm/realm-java#1665]
Ahoy!

So I made the decision of revamping my app and integrating Realm with it. However, I feel I've encountered a critical issue — keeping Realm instances open forever. For example, during the lifecycle of an Activity.

Here's a use case: I have a list in my Activity, backed by an `Adapter` that uses `RealmResults` as its dataset. Now, I cannot close the Realm or else the dataset will become inaccessible. So, the Realm instance is kept opened forever, until the Activity gets destroyed.

This part of opening and closing Realm is handled inside my "BaseActivity". It's initialized lazily — only when the `getRealm()` method is called and later closed inside `onDestroy()`.

Now, is this safe? I fear I'll run into memory issues.

**Comment by dalinaum** [comment]
Hello, @Saketme How many do you open Realm instances? If you have a single or a few instanes and close it or them later,  this would not be a problem.

**Comment by Saketme** [comment]
Well, I've got base classes for `Activity`, `Service` and `BroadcastReceiver`s. They all keep Realm opened forever once accessed. One instance per class.

Considering that Services and receivers usually perform their jobs quickly and exit, it shouldn't be a problem.

However, it's the base Activity that class I'm worried about. I do remember seeing one `StackOverflow` exception due to low memory.

**Comment by cmelchior** [comment]
Realm uses a thread local cache internally, so you can call `Realm.getInstance` as many times you want on the UI thread and still only have 1 underlying resource open. It can be problematic if you open the Realm on background threads and don't close those. It is in those cases you might risk running out of memory.

**Comment by Saketme** [comment]
Thanks for answering. I'm ensuring that all Realm instances only get accessed from the UI thread. Is it okay to keep it open during the lifetime?

**Comment by cmelchior** [comment]
Yes that is perfectly fine.

**Comment by Saketme** [comment]
Cool, thanks!
