### ISSUE TITLE
Glibberish message on every project build

### ISSUE THREAD

**Issue by Saketme** [realm/realm-java#1666]
So Realm has suddenly started showing me this message everytime I run my project:

![Realm gibberish message](http://i.imgur.com/CYWywhU.png)

Update: Removing annotations like `@Nullable`, `@NonNull` from my RealmObject getters fixes the issue. But this is weird considering I'm already on the latest version (assuming the message is an update-notification for the developer)

**Comment by zaki50** [comment]
@Saketme It seems you are in the separate network and our latest version check is not working correctly.

I made a PR to check if obtained version string comes from expected server or net.

**Comment by Saketme** [comment]
Cool, thanks :)
