### ISSUE TITLE
"No outside changes to a Realm is allowed while iterating a RealmResults. Use iterators methods instead."

### ISSUE THREAD

**Issue by Saketme** [realm/realm-java#1667]
Sorry if this is a noob question, but I'm having difficulty understanding the exception message. Which iterators method am I supposed to use?

**Comment by Flydiverny** [comment]
```
RealmResult<RealmObject> objects = realm.query(RealmObject.class).findAll();
for(int i = 0; i < objects.size(); i++) {
    RealmObject obj = objects.get(i);
}
```
Generally works best in my experience :)
In case you are trying to remove objects from Realm while iterating over them keep in mind that the RealmResult will change, or if you are updating them they might not be included in your query anymore.

None of the iterators seems to work for removing, I usually opt for:
```
while(objects.size() > 0)
    objects.get(0).removeFromRealm();
```

**Comment by zaki50** [comment]
Hi @Saketme

Current implementation of the  `RealmResults`'s `Iterator` has a problem described in #640

So current solution is not to use the  `Iterator` if you need to modify anything in the Realm while iteration.

Please try the code in @Flydiverny  's comment.

**Comment by zaki50** [comment]
@Saketme I'll close this issue. If you have further questions, feel free to reopen this or create new issue.

**Comment by Saketme** [comment]
@Flydiverny Good idea. I was creating a backup collection of ReamObjects to later iterate through them, considering Iterators are slightly faster than fori loops (*in case of Collection of objects*).
