### ISSUE TITLE
Can not load other `.so` under other platforms 

### ISSUE THREAD

**Issue by Davion8948** [realm/realm-java#1670]
Hi,

  Originally, I had two platforms, `armeabi` and `armeabi-v7a`. Each folder has multiple `.so` files under it, including `libtpnsSecurity.so`, as shown in the following screenshot
![realm_1](https://cloud.githubusercontent.com/assets/4756476/10723836/fb1979ba-7bf9-11e5-881f-f7d75bf53e7c.png)

  After adding realm to the project, it had generated new platform folders, but some platforms did not generate the `libtpnsSecurity.so` file (with other `.so` files). This causes the following error in my project:

```
dlopen failed: library "libtpnsSecurity.so" not found
```

![ream_2](https://cloud.githubusercontent.com/assets/4756476/10723907/c5159366-7bfa-11e5-9545-376ae41d1be0.png)

How can I fix this error?  any help would be appreciated.

**Comment by cmelchior** [comment]
Most likely your other projects does not provide binary files for ARM 64 bit devices. As you can see the `.so` file from Realm is there but the rest is missing. I would suggest reaching out to where you got the other `.so` files from and ask them to provide binaries for 64 bit (both ARM and x86).

**Comment by Davion8948** [comment]
I see, is it possible to compile for the `armeabi` and `armeabi-v7a` platforms only? I'm using Android Studio

**Comment by beeender** [comment]
@Davion8948 Yes, check comments here https://github.com/realm/realm-java/issues/1640#issuecomment-150114493

**Comment by cmelchior** [comment]
There is also a guide here if you want to use APK split instead: https://realm.io/news/reducing-apk-size-native-libraries/ (at the bottom)

**Comment by Davion8948** [comment]
@cmelchior @beeender  Can you provide me with a realm.jar file that only contains the build version of `armeabi` and `armeabi-v7a`? It's rather difficult for me to go through the processes that needs to take to compile the files, so it would be great if you can compile one and provide me with a download link or an attachment (my email is xiaochen200642@gmail.com). Thanks.


I'm having problem with compiling the  I think it's  Some other `.so` files don't have 64 bit and I have difficult in  building realm with only `armeabi` and `armeabi-v7a`, can you support me one?

**Comment by bmunkholm** [comment]
That won't be sustainable for new releases. But it's very easy for you to do. the .jar file is a zip file so you can unzip it, delete the files you don't want and zip it again.

**Comment by Davion8948** [comment]
@bmunkholm Thanks.
