### ISSUE TITLE
How to inherit the RealmObject set to modify the values in the do

### ISSUE THREAD

**Issue by cwangkkb** [realm/realm-java#1671]
How to inherit the RealmObject set to modify the values in the do?

for example,
private boolean isSelected;

    public boolean isSelected() {
        return isSelected;
    }

    public void setIsSelected(boolean isSelected) {
        this.isSelected = isSelected;
    }

how to  Call set?

I only needs to modify memory without the need to save to the database.

**Comment by kneth** [comment]
If you never need to save the field to the Realm file, the `@Ignore` annotation is just what you need.

**Comment by cwangkkb** [comment]
@kneth  ok,tsk!

**Comment by kneth** [comment]
I'm closing the issue as it sounds like `@Ignore` was the solution.
