### ISSUE TITLE
Use with ios real

### ISSUE THREAD

**Issue by yaming116** [realm/realm-java#1679]
I found the new version of the realm database file format change, I now have two questions.
1. The new version of how to read the old version of the data?
2.ios need which version can read the new Android version of the database file.

Thank you

**Comment by dalinaum** [comment]
Hello, @yaming116. 

1. Your Realm files will automatically be converted to new file format when you open the Realm file for the first time.
2. Realm Objective-C & Swift 0.96 adds support for null values.

**Comment by hlllmr1314** [comment]
Hi @dalinaum.

When I use the new version realm to open old version database, app crash!
FATAL EXCEPTION: ExamDownloadManager
    io.realm.exceptions.RealmMigrationNeededException: Index not defined for field 'ex_id' in existing Realm file. Either set @Index or migrate using io.realm.internal.Table.removeSearchIndex().
            at io.realm.ZtyExpandHomeWorkContentRealmProxy.validateTable(ZtyExpandHomeWorkContentRealmProxy.java:215)
            at io.realm.ZtyExamBookLibraryModleMediator.validateTable(ZtyExamBookLibraryModleMediator.java:56)
            at io.realm.Realm.initializeRealm(Realm.java:339)
            at io.realm.Realm.createAndValidate(Realm.java:307)
            at io.realm.Realm.create(Realm.java:256)
            at io.realm.Realm.getInstance(Realm.java:219)

If i delete realm database file, the app run successfully！

**Comment by dalinaum** [comment]
I think your model and Realm file doesn't match correctly. You can set `@Index` for field `ex_id` or make a migration using `removeSearchIndex()`.

**Comment by hlllmr1314** [comment]
Hi @dalinaum. 
 Thank you, The problem has been resolved。

**Comment by dalinaum** [comment]
@hlllmr1314 Great. If you enter further problem, please feel free to create a new issue.
