### ISSUE TITLE
Unrecoverable error. mmap() failed

### ISSUE THREAD

**Issue by crysan** [realm/realm-java#1680]
Hi!
Realm 0.84.0. Device Highscreen Zera S rev.S

<code>
Caused by: io.realm.exceptions.RealmError: Unrecoverable error. mmap() failed: Out of memory in io_realm_internal_SharedGroup.cpp line 188
at io.realm.internal.SharedGroup.nativeCommitAndContinueAsRead(Native Method)
at io.realm.internal.SharedGroup.commitAndContinueAsRead(SharedGroup.java:99)
at io.realm.internal.ImplicitTransaction.commitAndContinueAsRead(ImplicitTransaction.java:59)
at io.realm.internal.SharedGroupManager.commitAndContinueAsRead(SharedGroupManager.java:118)
at io.realm.BaseRealm.commitTransaction(BaseRealm.java:309)
at io.realm.Realm.commitTransaction(Realm.java:113)
</code>

What could it be?

**Comment by dalinaum** [comment]
Hello, @crysan. When your app runs out of memory or disk space, `mmap()` will fail. You can read more about memory issues in the [FAQ](https://realm.io/docs/java/latest/#faq). [What to do about out-of-memory exceptions?](https://realm.io/docs/java/latest/#what-to-do-about-out-of-memory-exceptions) and [Large Realm file size](https://realm.io/docs/java/latest/#large-realm-file-size).

**Comment by crysan** [comment]
"When your app runs out of memory or disk space" - Is there other options?

**Comment by dalinaum** [comment]
`mmap` thorws out of memory error if your app runs out of memory. Did you open multiple Realm instances in multiple threads without closing instances? In this case, you can encounter this problem. Otherwise, please read memory issues in the FAQ.

**Comment by crysan** [comment]
Thank you for the detailed answer!

**Comment by dalinaum** [comment]
@crysan Did you solve your problem?

**Comment by crysan** [comment]
Yes. Hand Large Realm file size.
Ty!

**Comment by dalinaum** [comment]
@crysan Great. It seems related to #1462 
I'll close this issue, if you enter further problems, please feel free to create a new issue.

**Comment by giusecapo** [comment]
Hi, I'm facing this issue with Realm 3.0.

How did you solve it?

**Comment by Zhuinden** [comment]
I've mostly seen this happen if the user doesn't close his background thread local Realm instances.

**Comment by giusecapo** [comment]
@Zhuinden Thanks for you reply, but I do not think. I explain better: in my application I use a lot of bitmap data and this causes some memory issues (application goes out of memory). Now, on my tablet if app crashes because of memory, I just re-open it and everything works fine (at least until I re-load a lot of bitmaps). But on my client tablet, when app crashes due to memory, she can't re-open the app again and I read on the console this realm error `Unrecoverable error. mmap() failed: Out of memory size... ` Why do you think this happens?

**Comment by Zhuinden** [comment]
@giusecapo if you have bitmap memory issues, you should probably use an image loader library, like Glide.

**Comment by giusecapo** [comment]
@Zhuinden how would you integrate realm with Glide? Cause I read that Glide allows you to cache images with url but I need to create an offline-first app (that's why I'm storing bytes array of bitmap w/ realm).

**Comment by Zhuinden** [comment]
@giusecapo i'd just store the image URLs in Realm, and `Glide.with(context).load(url).into(imageView)`

**Comment by giusecapo** [comment]
@Zhuinden thanks for your answer. 
But that glide method will work only under connection. Instead I need a way to download all the images in one moment so that the user can use the app offline after the download ends. How would you do that? I really appreciate your help.

**Comment by Zhuinden** [comment]
I'm not sure, i've never done that. While you *can* download files, you still shouldn't store them in Realm, maybe a path is sufficient.

**Comment by giusecapo** [comment]
I store them on local storage (in a path) but still, it is very large for my app. How could I use some image cacher like glide to improve performance and still have my offline-first app? @Zhuinden
