### ISSUE TITLE
Bulk insert

### ISSUE THREAD

**Issue by beeender** [realm/realm-java#1684]
This is feature requested by http://stackoverflow.com/questions/33358880/realm-java-fastest-bulk-write-methodology

Most SQL database support "batch insert" like `INSERT INTO tbl (col1, col2) VALUES ('val1', 'val2'), ('val3', 'val4'), ...`

Our current bottle neck would be when inserting lots of data, lots of duplicated checking are made, and lots or jni calls are made. We should find a way to pass a batch of different types of data to JNI and insert them through one JNI call.

**Comment by cmelchior** [comment]
One of the huge performance penalties is also the time spend by the Garbage collector, because we allocate a lot of temporary objects. Some sort of object-pool pattern where users could "give back" an object would go a long way and could easily be added to our current API::

```
Foo foo = realm.createObject(Foo.class);
foo.setBar("bar");
for (int i = 1; i < 100000; i++ ) {
  foo = realm.createObject(Foo.class, foo); // Reuse object -> Manual cleanup of row-accessor, reuse all Java objects
  foo.setBar("newBar");
}
```

**Comment by beeender** [comment]
+1 from http://stackoverflow.com/questions/33358880/realm-java-fastest-bulk-write-methodology?noredirect=1#comment54535556_33358880

**Comment by cmelchior** [comment]
Another suggestion: Our 3 primary performance hogs are: GC, Thread-check and JNI boundary.

I think that we can address the first 2 relatively easy without big API changes, while the later is a lot more tricky as it means we should parse multiple arguments in one call.

If we could define a scope where within we disabled the thread-checks for RealmObject accessors we would also gain a lot:

```
// V1: Boolean in begin transaction / or maybe just as part of beginTransaction()?
realm.beginTransaction(boolean iPromiseOnly1Thread)
// do stuff
realm.commitTransaction()
```

**Comment by beeender** [comment]
I do prefer the idea before that we offer user a API to disable the thread checking globally, not only inside the transaction. As long as users know what they are doing, thread checking is not necessary in the release build.

**Comment by cmelchior** [comment]
If we can find find a nice way to do it, then that might work as well. I just think that the use cases where reading so much data are very small compared to the write-use cases.

It would actually be fairly easy to add these optimisations to our current `copyToRealm(collection)/bulk JSON` methods as we have a very well-defined scope there.

**Comment by cmelchior** [comment]
Copy from #987 

----

Creating a new object in a Realm is often done like:

realm.beginTransaction();
Person person = realm.createObject(Person.class);
person.setName("Arthur");
person.setAge(42);
realm.commit();
It turns out that the calls to the setters are checking if the person object accessed from the correct thread (calling Realm.checkIfValid()). And this checking takes up 40-50 % of the time spend in the setters. Typically, creating object and setting the fields' values are always done together, and a simple method could be useful:

realm.beginTransaction();
Person person = realm.createObjectWithValues(Person.class, "Arthur", 42);
realm.commit();
Besides a simpler API for creating objects with values, the method will also increase performance as only one call to Realm.checkIfValue()) is done.

See also http://stackoverflow.com/questions/29214236/how-to-add-1-milion-items-in-realm-correctly/29216133#29216133

**Comment by MinceMan** [comment]
I myself am having performance issues because of all the GCing while saving to realm. Should that issue be broken out from here for better tracking?

**Comment by cmelchior** [comment]
Hi @MinceMan Sorry for the late reply. Yes please create a separate issue for that.

**Comment by TSG9876** [comment]
Hi,
realm.beginTransaction();
Person person = realm.createObjectWithValues(Person.class, "Arthur", 42);
realm.commit();

The  realm.createObjectWithValues(Person.class, "Arthur", 42); may not be the best approach if I understand correctly that the calling Realm.checkIfValid() is done on the setter and getter as described.

Bulk insert methodology is something similar to 

data1,data2, data3..... Non-Stop Feed in  ---------> O B J E C T BRIDGE OPEN LINK  ---->Continuously  Push Write to ====> Persistent database.             


Instantiate the class  object first where   Person person =new Person(Name , Age)  , Name={A,B,C ...} , Age={21,25,35....}  and  then write on the fly  
realm.beginTransaction();
  realm.createObjectWithValues(person) 
realm.commit ();

**Comment by cmelchior** [comment]
Additional idea: Creating an `insert` method in proxy classes that uses the Table API. That way we can skip _all_ safety checks:

```
    public static void insert(AllJavaTypes obj, Table t) {
        long l = t.addEmptyRow();
        t.setBoolean(0, l, obj.isFieldBoolean());
        // ...
    }
```

Headaches are:
- Primary Keys
- Links
- LinkLists

**Comment by beeender** [comment]
google's flatbuffer is perfect for passing bunch of data between java and JNI which might be very useful for this.

**Comment by Zhuinden** [comment]
I do admit, an API that allows to create Realm rows using only `1` re-used Realm instance, without creating a new Realm object for each inserted element - that's pretty useful.
