### ISSUE TITLE
App crashing with Fatal signal 11(SIGSEGV)

### ISSUE THREAD

**Issue by skptl** [realm/realm-java#1685]
Multiple complaints received from users on Android 4.4* after adding realm, I am not able to reproduce it on my end. I am receiving about 40-50 complaints a day after the launch last week. We have multiple users in India and almost all of them experiencing crashes are on a dual sim phone and Android 4.4.* if it helps.

I am not receiving any logs as the app is not starting at all, by remote debugging I have the following information.

http://pastebin.com/YQPQVBb9

**Comment by zaki50** [comment]
@skptl Thank you for reporting.

What version of Realm are you using?

**Comment by skptl** [comment]
It's 0.83.1, thanks!

**Comment by kneth** [comment]
@skptl We have recently seen issues with encryption. Do you encrypt the Realm?

**Comment by skptl** [comment]
@kneth Yes I do encrypt the Realm. Any workaround?

**Comment by kneth** [comment]
@skptl No real workaround yet. We are working on a new encryption implementation (the encrypted Realm file is the same). If you can provide us with an overview of which devices you see these crashes, it can be useful for us.

**Comment by skptl** [comment]
@kneth I can send you a few devices, I would update the comment with device list.

**Comment by skptl** [comment]
@kneth I have commented with a few devices that experience crashes.

**Comment by dalinaum** [comment]
Thaks for the list of devices @skptl. We are investigating issues with encryption.

**Comment by beeender** [comment]
We have a similar problem before https://github.com/realm/realm-java/issues/1388
The device randomly doesn't route the signal to our signal handler instead it just crashed with (SIGSEGV) at 0x00000004 (code=1)

I believe the new encryption implementation we are working will solve this problem.,

**Comment by beeender** [comment]
Realm java 0.85.0 released which has a new implementation of encryption. 
https://realm.io/news/realm-java-0.85.0/

This problem should be solved! :tada:
