### ISSUE TITLE
App crashing with encryption turned on

### ISSUE THREAD

**Issue by anotherdev** [realm/realm-java#1689]
I'm getting error: A/art: art/runtime/fault_handler.cc:117] Check failed: !initialized_
When using realm encryption on Android 6.0.

**Comment by beeender** [comment]
@anotherdev 
1. Which device?
2. Can you please post a full log here?

**Comment by anotherdev** [comment]
1. Nexus 5, OTA Android 6.0
2. Unfortunately that's was the only line of the log. :(

**Comment by beeender** [comment]
@anotherdev It crashes when the Realm opened? Could it be easily reproduced? How?

**Comment by anotherdev** [comment]
It crash about 0.5-2 seconds after Realm opened. There are no stack trace or SIGSEGV type of error message at all.

I tested with HTC M8, Android 5. No errors.

**Comment by beeender** [comment]
We are working on new implementation of encryption right now, which should solve this problem as well. I will update this issue when that is done.

**Comment by crosswall** [comment]
I have the same problem,when using realm encryption on Android M.And device not print error log on Logcat

https://play.google.com/store/apps/details?id=com.airilyapp.board
test account: 283706885@qq.com  password: qqqqqq

**Comment by dalinaum** [comment]
Hello @crosswall. We are working on new implementaion yet. I think it already fixes this problem. But we need more testing and optimization to release this. We will update this soon.

**Comment by LiuDeng** [comment]
have this been fixed?

**Comment by beeender** [comment]
@LiuDeng We are optimizing and testing the new encryption implementation now. And it will be released recently.

**Comment by seinen** [comment]
We are having the same issue. Also on a Nexus 5.0 with Android 6.0 installed.
What is the status of this issue?

**Comment by beeender** [comment]
Realm java 0.85.0 released which has a new implementation of encryption. 
https://realm.io/news/realm-java-0.85.0/

I believe this problem should be fixed in the new release. @anotherdev If you still can reproduce the issue, feel free to reopen this issue.

Thanks everybody!
