### ISSUE TITLE
App crashing with Realm error

### ISSUE THREAD

**Issue by deepak2510** [realm/realm-java#1691]
My app suddenly crashed with this error : 
java.util.concurrent.TimeoutException: io.realm.internal.TableView.finalize() timed out after 10 seconds : at io.realm.internal.TableView.finalize(TableView.java:123)

Anything I must be doing wrong ? 

Thanks !

**Comment by yaming116** [comment]
same with #1599

**Comment by dalinaum** [comment]
@deepak2510 Thank you for reporting. What version of Realm are you using? If you can provide us with an overview of which devices you see the these crashe, it can be useful to us.

**Comment by deepak2510** [comment]
@dalinaum I am using 0.82.0. I saw this crash on my Nexus 6. I can't say for sure, but I think it might have to do with a lot of table opening and closing calls happening quickly in succession, although I might be wrong. Thank you for taking a lot at this :+1:

**Comment by kneth** [comment]
@deepak2510 We fixed a bug in 0.82.2. The bug could cause a timeout in finalisers. Please consider to upgrade to a newer version of Realm.

**Comment by deepak2510** [comment]
Thanks Kenneth. I tried updating the version in build.gradle but I get DEX
errors on compile. Am I missing something ?



On Fri, Oct 30, 2015 at 3:39 AM, Kenneth Geisshirt <notifications@github.com

**Comment by deepak2510** [comment]
When I try updating to version 0.84.2 I get this error : 
Error:Execution failed for task ':app:dexDebug'.
> com.android.ide.common.internal.LoggedErrorException: Failed to run command:
  	/Applications/adt-bundle-mac-x86_64-20140702/sdk/build-tools/21.1.1/dx --dex --no-optimize --output /Users/ubhagde/AndroidStudioProjects/Krsna/app/build/intermediates/dex/debug --input-list=/Users/ubhagde/AndroidStudioProjects/Krsna/app/build/intermediates/tmp/dex/debug/inputList.txt
  Error Code:
  	2
  Output:
  	UNEXPECTED TOP-LEVEL EXCEPTION:
  	com.android.dex.DexIndexOverflowException: method ID not in [0, 0xffff]: 65536
  		at com.android.dx.merge.DexMerger$6.updateIndex(DexMerger.java:502)
  		at com.android.dx.merge.DexMerger$IdMerger.mergeSorted(DexMerger.java:277)
  		at com.android.dx.merge.DexMerger.mergeMethodIds(DexMerger.java:491)
  		at com.android.dx.merge.DexMerger.mergeDexes(DexMerger.java:168)
  		at com.android.dx.merge.DexMerger.merge(DexMerger.java:189)
  		at com.android.dx.command.dexer.Main.mergeLibraryDexBuffers(Main.java:454)
  		at com.android.dx.command.dexer.Main.runMonoDex(Main.java:302)
  		at com.android.dx.command.dexer.Main.run(Main.java:245)
  		at com.android.dx.command.dexer.Main.main(Main.java:214)
  		at com.android.dx.command.Main.main(Main.java:106)

**Comment by dalinaum** [comment]
Hello @deepak2510. The number of your methods reaches 65536.

You can use [Multidex](http://developer.android.com/tools/building/multidex.html) to resolve this.

**Comment by deepak2510** [comment]
Thanks a lot !

**Comment by dalinaum** [comment]
@deepak2510 Good. I'll close this issue. If you encounter further problems, please feel free to reopen this or create a new issue.
