### ISSUE TITLE
nested Link Object isNull condition crashed

### ISSUE THREAD

**Issue by chouex** [realm/realm-java#1693]
Getting a crash reports when i try nested Linked isNull condition.

```
io.realm.exceptions.RealmError: Unrecoverable error. Combining link() and is_null() is currently not supported in io_realm_internal_TableQuery.cpp line 1497
    at io.realm.internal.TableQuery.nativeIsNull(Native Method)
    at io.realm.internal.TableQuery.isNull(TableQuery.java:677)
    at io.realm.RealmQuery.isNull(RealmQuery.java:249)
    at ***(SomeClass.java:80)
```

```
RealmQuery<ComplexSightseeing> query = realm.where(Level0.class);
query.isNotNull("Level1");
query.isNull("Level1.Level2");  //line 80
```

where Level0,Level1,Level2 class is

```
class Level0 extends RealmObject{
    @PrimaryKey
    private int id;


    private Level1 Level1;
...
}


class Level1 extends RealmObject{
    @PrimaryKey
    private int id;

    private Level2 Level2;
...
}


class Level2 extends RealmObject{
    @PrimaryKey
    private int id;

...
}
```

```
compile 'io.realm:realm-android:0.84.1' 
```

android 4.4.4

**Comment by zaki50** [comment]
Hi @chouex 
Thank you for reporting.

I'll check that.

**Comment by zaki50** [comment]
I confirmed this issue.
And it's a limitation of current underlying storage engine.

So, we should document this behavior as a current limitation.

**Comment by chouex** [comment]
temporary solution is to create another column define wether link is null

**Comment by cmelchior** [comment]
`isNull` for linked fields are now working, see https://github.com/realm/realm-java/issues/1367

**Comment by andriy-svirskyy** [comment]
> `isNull` for linked fields are now working, see #1367

Still getting exception `Illegal Argument: isNotNull() by nested query for link field is not supported.`

Realm-android 10.5.0
