### ISSUE TITLE
How to identify the host of RealmChangeListener?

### ISSUE THREAD

**Issue by HsiangLeekwok** [realm/realm-java#1697]
How to identify the host of RealmChangeListener?

this listener only has onChange() callback, but we don't know who fired this callback, Realm or RealmResult<E>

**Comment by cmelchior** [comment]
The idea is that it should only trigger when the RealmResults changed. However that is currently not the case as we are still working on #989. So currently it will trigger for all changes to the Realm. It will automatically be "upgraded" to work as expected once we add #989 though. 

So right now adding the RealmChangeListener to RealmResults is just a local version of adding it to Realm instead.

**Comment by HsiangLeekwok** [comment]
Thanks!!! @cmelchior
