### ISSUE TITLE
IllegalArgumentException: Realm on disc is newer than the one specified: v2 vs. v0

### ISSUE THREAD

**Issue by Ralphilius** [realm/realm-java#1709]
This issue is driving me crazy since I have followed everything in the examples and the answers to similar questions I found on Google.

**Specs:**
 - Current Realm version: 0.82.2. I am having database change for this build, so I avoid upgrading to newer version of Realm to deal with breaking changes later.
 - RealmConfiguration in Application class:

```
RealmConfiguration config = new RealmConfiguration.Builder(getApplicationContext())
                    .schemaVersion(2)
                    .migration(new DBMigration())
                    .build();
Realm.setDefaultConfiguration(config);
```
 - DBMigration class:
```
       if (version == 0) {
            Table tableDrawer = realm.getTable(NavDrawerItem.class);
            tableDrawer.setPrimaryKey("objectId");
            version++;
        }

        if(version == 1){
            Table favouriteTable = realm.getTable(Favourites.class);
            Table navTable = realm.getTable(NavDrawerItem.class);
            Table gameTable = realm.getTable(RealmGame.class);
            long favPrimaryIndex = favouriteTable.getColumnIndex("objectId");
            long navPrimaryIndex = navTable.getColumnIndex("objectId");
            long gamePrimaryIndex = gameTable.addColumn(ColumnType.STRING, "objectId");
            gameTable.addColumn(ColumnType.STRING, "gameName");
            //other addColumn....
            gameTable.addColumn(ColumnType.BOOLEAN, "isActive");
            gameTable.setPrimaryKey("objectId");
            favouriteTable.addSearchIndex(favPrimaryIndex);
            navTable.addSearchIndex(navPrimaryIndex);
            gameTable.addSearchIndex(gamePrimaryIndex);
            version++;
        }

        return version;
```

**Changes from schemaVersion 1 o 2:**
 - Added a new class

**Comment by zaki50** [comment]
Hi @Ralphilius 

How did you get the Realm instance when `IllegalArgumentException` was thrown?

**Comment by Ralphilius** [comment]
Hi @zaki50,

It's thrown in my Splash activity in which there is a query to retrieve objects.

**Comment by zaki50** [comment]
Are you using `Realm.getDefaultInstance()` to obtain the Realm instance in the splash activity?

**Comment by Ralphilius** [comment]
@zaki50 No, I'm using Realm.getInstance(context) to get Realm instance

**Comment by zaki50** [comment]
@Ralphilius 

That's the cause of this `IllegalArgumentException `.

`Realm.getInstance(context)` does not use the default configuration.
Instead, that method creates new RealmConfiguration with default name and schema version `0` and uses it.

You should use `Realm.getDefaultConfiguration()` in Splash activity and that solve the problem.

**Comment by Ralphilius** [comment]
OK.. Calling `Realm.getDefaultInstance()` will get another realm file if I update the app, right? What can I do with previously using `getInstance` to get a Realm instance?

**Comment by zaki50** [comment]
No, the database file is the same because you didn't provide database name to default configuration.

**Comment by Ralphilius** [comment]
OK. Thank you for quick response :+1: . I can resolve the issue now. Closing this  :)

**Comment by zaki50** [comment]
@Ralphilius :+1:
