### ISSUE TITLE
RealmObject and toString(), equals()

### ISSUE THREAD

**Issue by Saketme** [realm/realm-java#1714]
There's one flaw of RealmObjects that I'm having to deal with lately. 

The auto-generated equals() and toString() aren't available for use for non-live RealmObjects. Since Realm generates its own equals() & toString() methods that aren't allowed to be overridden, I'm unable to think of a workaround. 

Again, this will get solved once custom methods become allowed.

**Comment by kneth** [comment]
Yes, `equals()` and `toString()` are both generated by the annotation processor and can not ve overriden.

**Comment by Saketme** [comment]
There's one more thing. Will it be possible to exclude certain fields from `equals()` in the future?

**Comment by cmelchior** [comment]
We will probably not give that option, but once we allow you to create your own equals method, it should be relatively easy.

**Comment by Saketme** [comment]
Cool, thanks.
