### ISSUE TITLE
java.lang.IllegalStateException: Changing Realm data can only be done from inside a transaction.

### ISSUE THREAD

**Issue by mjliu** [realm/realm-java#1715]
@beeender 

when I update a RealmObject  I use realm.beginTransaction(). but I change realmList
for example:
realmList.addAll(list).
it also crash with that error. I don't know why?

**Comment by beeender** [comment]
Do you mean `RealmList.add` https://realm.io/docs/java/latest/api/io/realm/RealmList.html#add-E- ?
(There is no method called `addAll` for `RealmList` )

When you call `RealmList.add()` and that list is in non-managed mode, you don't have to start the transaction. "In non-managed mode" means the list is created by `new RealmList()` and it is not being managed by Realm yet.

But if the `RealmList` is in managed mode, like when you call your model's `getXXXList` method, the `RealmList` is actually connected with a Realm instance. the `add` call to it will actually change the Realm db, that is the reason that should happen in a transaction block.

**Comment by mjliu** [comment]
@beeender 
I want to use realmList to addAll what should I do.
for example:
 when I scroll up to load more and update my listview.

**Comment by mjliu** [comment]
![11111](https://cloud.githubusercontent.com/assets/8022517/10880211/6aae5990-8194-11e5-8b28-8cc2f2ec73db.jpg)

**Comment by beeender** [comment]
Sorry, just checked the source code, we don't override the `addAll` so it's the default behavior which will call the `add` method to add them all. And that will throw the same `IllegalStateException`.

Is the `this.cardEntities` a `RealmList` pointed to the same object's field as well? If it is, i think you just need to call `notifyDataSetChange()` in the change listener or after you commit the transaction. That `this.cardEntities` should be updated automatically in the next UI loop (Or after transaction committed in the UI thread.).

**Comment by mjliu** [comment]
@beeender 

RealmList<VideoGatherEntity> cardEntities = new RealmList<>();  VideoGatherEntity is RealmObject.

I don't know what you mean!  what should I do to resolve this problem.  
I have a idea : convert RealmList to ArrayList. but I think this is not a good idea. 
can you have any resolve ideas?  listview load more data is very common, after all.

**Comment by mjliu** [comment]
@beeender 
![image](https://cloud.githubusercontent.com/assets/8022517/10900080/586c2848-8216-11e5-89b7-d736356c3d9b.png)

Yes . RealmList pointed to the same object's field .  this cardEntities is a new RealmList.  setaData(RealmList)   this RealmList is passed from Activity.

**Comment by beeender** [comment]
@mjliu Normally you don't have to convert it to an `ArrayList` . Can you please post your model classes here?
