### ISSUE TITLE
NullPointerException: Attempt to invoke virtual method ColumnIndices.getColumnInfo(java.lang.Class)' on a null object reference

### ISSUE THREAD

**Issue by Saketme** [realm/realm-java#1719]
We're seeing NPEs at two places in our app. Here's the stacktraces:

https://gist.githubusercontent.com/Saketme/179ceeda5464683ea790/raw/bd2bcfb3a03663f3b79f6d0eaa845222326ad644/gistfile1.txt

https://gist.githubusercontent.com/Saketme/de9b88737fcec6bdfc26/raw/debd24336362a3f2649d8f6698c8c84660672eec/gistfile1.txt

Can anyone please help me understand what's going on here and what could be the solution?

**Comment by zaki50** [comment]
@Saketme What version of Realm are you using?

If you are using `0.84.0`, please update to `0.84.1` which includes the fix of #1646.

**Comment by Saketme** [comment]
Ah, I overlooked #1646. Upgraded to 0.84.1. Will re-open this issue if the issue still exists. Thanks :)
