### ISSUE TITLE
Read in asyncTransaction stills slows down ui-thread

### ISSUE THREAD

**Issue by jofor** [realm/realm-java#1723]
Hi! Thanks for a wonderful library and service. Been using realm for some while now, and it has been working great, but when I read Migration had been added I had to upgrade and I am now seeing weird problems that I didnt have before.

The version of realm i'm using is: 0.84.1

First of, I got a lot of these:

```I/art: Explicit concurrent mark sweep GC freed 478(18KB) AllocSpace objects, 0(0B) LOS objects, 37% free, 26MB/42MB, paused 1.516ms total 21.675ms
I/art: Explicit concurrent mark sweep GC freed 193(7KB) AllocSpace objects, 0(0B) LOS objects, 37% free, 26MB/42MB, paused 1.086ms total 19.254ms
I/art: Explicit concurrent mark sweep GC freed 407(14KB) AllocSpace objects, 0(0B) LOS objects, 37% free, 26MB/42MB, paused 1.239ms total 18.819ms
I/art: Explicit concurrent mark sweep GC freed 244(8KB) AllocSpace objects, 0(0B) LOS objects, 37% free, 26MB/42MB, paused 1.563ms total 19.136ms
I/art: Explicit concurrent mark sweep GC freed 24(1152B) AllocSpace objects, 0(0B) LOS objects, 37% free, 26MB/42MB, paused 1.188ms total 18.896ms
I/art: Explicit concurrent mark sweep GC freed 20(1024B) AllocSpace objects, 0(0B) LOS objects, 37% free, 26MB/42MB, paused 1.262ms total 18.877ms
I/art: Explicit concurrent mark sweep GC freed 20(1024B) AllocSpace objects, 0(0B) LOS objects, 37% free, 26MB/42MB, paused 1.364ms total 18.765ms
I/art: Explicit concurrent mark sweep GC freed 20(1024B) AllocSpace objects, 0(0B) LOS objects, 37% free, 26MB/42MB, paused 1.336ms total 19.045ms
I/art: Explicit concurrent mark sweep GC freed 20(1024B) AllocSpace objects, 0(0B) LOS objects, 37% free, 26MB/42MB, paused 1.449ms total 19.343ms
I/art: Explicit concurrent mark sweep GC freed 20(1024B) AllocSpace objects, 0(0B) LOS objects, 37% free, 26MB/42MB, paused 1.219ms total 18.741ms
I/art: Explicit concurrent mark sweep GC freed 20(1024B) AllocSpace objects, 0(0B) LOS objects, 37% free, 26MB/42MB, paused 1.489ms total 19.840ms
I/art: Explicit concurrent mark sweep GC freed 20(1024B) AllocSpace objects, 0(0B) LOS objects, 37% free, 26MB/42MB, paused 1.313ms total 18.993ms
I/art: Explicit concurrent mark sweep GC freed 20(1024B) AllocSpace objects, 0(0B) LOS objects, 37% free, 26MB/42MB, paused 1.417ms total 20.869ms
I/art: Explicit concurrent mark sweep GC freed 20(1024B) AllocSpace objects, 0(0B) LOS objects, 37% free, 26MB/42MB, paused 1.275ms total 19.161ms
I/art: Explicit concurrent mark sweep GC freed 20(1024B) AllocSpace objects, 0(0B) LOS objects, 37% free, 26MB/42MB, paused 1.301ms total 19.214ms
I/art: Explicit concurrent mark sweep GC freed 20(1024B) AllocSpace objects, 0(0B) LOS objects, 37% free, 26MB/42MB, paused 1.703ms total 25.882ms
I/art: Explicit concurrent mark sweep GC freed 20(1024B) AllocSpace objects, 0(0B) LOS objects, 37% free, 26MB/42MB, paused 1.305ms total 19.896ms
I/art: Explicit concurrent mark sweep GC freed 20(1024B) AllocSpace objects, 0(0B) LOS objects, 37% free, 26MB/42MB, paused 1.895ms total 26.911ms
I/art: Explicit concurrent mark sweep GC freed 22(1072B) AllocSpace objects, 0(0B) LOS objects, 37% free, 26MB/42MB, paused 1.406ms total 22.478ms
I/art: Explicit concurrent mark sweep GC freed 20(1024B) AllocSpace objects, 0(0B) LOS objects, 37% free, 26MB/42MB, paused 1.344ms total 21.171ms
I/Choreographer: Skipped 74 frames!  The application may be doing too much work on its main thread.```

And the code I'm running:

```
public void readPreviousDevice(final String id, final ReadAddedDeviceSuccess readAddedDeviceSuccess) {

        asyncTransaction = mRealm.executeTransaction(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {
                RealmQuery<PreviousDevice> query = realm.where(PreviousDevice.class);
                PreviousDevice deviceFound = query.equalTo("id", id).findFirst();
                readPreviousDevice = new PreviousDevice(deviceFound);
            }
        }, new Realm.Transaction.Callback() {
            @Override
            public void onSuccess() {
                readAddedDeviceSuccess.successFullReadCallback(readPreviousDevice);
            }

            @Override
            public void onError(Exception e) {
                e.printStackTrace();
                readAddedDeviceSuccess.errorFullReadCallback();
            }
        });
    }
```

The issue here is that each time I call the readPreviousDevice it seems to call the mark sweep more and more times and the Choreographer skips more and more frames. This seems somewhat odd to me.

The callback should update text on mainThread once the asyncTransaction has done its job, but it still seems to block. Could anyone shed any light on this?

(**Worth to mention is that PreviousDevice has a copy constructor to create a deep clone**)

**Comment by nhachicha** [comment]
Hi @jofor 
AFAICT you're not doing any write inside the transaction?
The current code will create a new commit each time which will trigger a `REALM_CHANGED` so other thread can advance their Realm, it also do cleanup (by calling the GC) in order to remove weakly reachable async queries (to avoid refreshing them in the future, which cause an overhead).

if you're calling often `readPreviousDevice` I suggest you replace it with an async query then register a listener to be notified when `PreviousDevice` changed
```java
PreviousDevice deviceFound = realm.where(PreviousDevice.class).findFirstAsync();
deviceFound.addChangeListener(new RealmChangeListener() {
                        @Override
                        public void onChange() {
                            //update text
                        }
                    });
```
Cheers,

**Comment by jofor** [comment]
Ah yes you are correct, Title was supposted to be "Read in asyncTransaction stills slows down ui-thread"

I tried your change:

```
  public void readAddedDevice(final String id, final ReadAddedDeviceSuccess readAddedDeviceSuccess) {
        RealmQuery< PreviousDevice > query = mRealm.where(PreviousDevice.class);
        final PreviousDevice previousDevice = query.equalTo("id", id).findFirstAsync();
        previousDevice.addChangeListener(new RealmChangeListener() {
            @Override
            public void onChange() {
                readAddedDeviceSuccess.successFullReadCallback(previousDevice);
            }
        });
    }
```

But it seems to have the same effect. Which is still, that the UI thread for each visit, gets a higher amount of reported:
Explicit concurrent mark sweep GC freed and the skipped frames amount increases:
I/Choreographer: Skipped 74 frames! The application may be doing too much work on its main thread

I tried to apply your suggested change throughout the application, where I use realm. And it does make things better, but the thing i noticed above still happens :/

**Comment by nhachicha** [comment]
@jofor actually you're registering a change listener for each call to `readAddedDevice`, so if you have *n* call to `readAddedDevice` this will register *n* listeners that we need to call each time the query is refreshed.

what you can do to improve performance is to have the following code run once (inside a callback for example), you'll end up having 1 callback registered & the callback will be notified each time `PreviousDevice` change
example:
```java
PreviousDevice previousDevice;
public void onResume () {
        RealmQuery<PreviousDevice> previousDevice = mRealm.where(PreviousDevice.class)
                              .equalTo("id", id).findFirstAsync();
        previousDevice.addChangeListener(new RealmChangeListener() {
            @Override
            public void onChange() {
                readAddedDeviceSuccess.successFullReadCallback(previousDevice);
            }
        });
}

public void onPause () {
     if (previousDevice != null) previousDevice.removeChangeListeners();
}
```

**Comment by kneth** [comment]
@jofor Did you have a chance to try out the suggestions by @nhachicha?

**Comment by jofor** [comment]
I did, I did'nt notice that much of an impact. In the end just limiting how many writes i made was the solution. Compared to the older versions of realm, something feels of here when writing data, even in a async thread things become slow if you need to constantly update values, even with the above mentioned remove listener.

This was working well with the older versions of realm, atleast for me :/

**Comment by nhachicha** [comment]
Hi @jofor 
can you provide a debug APK so we can run `systrace` & `traceview`, this might help detecting why you're skipping frames help@realm.io
it could be nice if you can send both APKs (before & after migration to async)

Cheers,

**Comment by jofor** [comment]
Hi @nhachicha the specific app apk is still behind NDA. However, the last one (the older apk) was based upon 0.80.2 of realm and used an event bus (in async) to do all the writes with realm. Which seemed to work at the time just fine. 

With 0.84.2 we noticed a change, and started looking into using the async methods of realm instead
to handle the issues. At first we were just pretty much using the old code to do the writes, but as said we noticed frame skipping, so started to look into the asyncFindFirst and similar. When we added that, not much was done to the impact of the frame skips, and more so, as discussed above, the more we called a specific read to realm, seemed to increase the amount of garbage calls. What we did was to follow the suggestion to remove all the listeners we created, but directly after we had a '''readAddedDeviceSuccess.successFullReadCallback(previousDevice);'''

Maybe this is the issue?

**Comment by nhachicha** [comment]
@jofor 
> At first we were just pretty much using the old code to do the writes, but as said we noticed frame skipping

If I understand correctly, even if you don't use any new async call, and you keep the same architecture (with the event bus) you still have drops in frames just by switching `0.80.2` with `0.84.2`?

**Comment by jofor** [comment]
Did did not see the same performance impact on 0.80.2, we kind of had to upgrade when you guys added migration support :) But what I meant was, the code(the non async reads) we had in 0.80.2 worked great with 0.80.2 but did not work as great on 0.84.1 and 0.84.1

**Comment by nhachicha** [comment]
So this is more related to the `0.84.x` release, not the fact that you're using async reads/writes (since even without using this feature you still experiencing a perf impact)

If you can reduce/extrapolate your use case into a unit test, we can investigate.

Cheers,

**Comment by markini** [comment]
Hello I wanted to add:
I too see a lot of garbage collector messages like `Explicit concurrent mark sweep GC free` and `GC_EXPLICIT freed 1K` recently. 
I have been on version 0.82.2 for some time and never experienced something like that. 
I went back and tested some versions. The garbage collector spam starts at `0.84.0`. No issues on `0.83.1`.
When does it happen: every time I save/read a lot to the realm. Basically everywhere in the app. I couldn't figure out a specific occurrence.

I have some methods which are calculating a lot of state data, which perform a lot of separated transactions in a very short time. 

I didn't experience any crashes though but it is hard to look at the output.

**Comment by nhachicha** [comment]
Hi @markini 
We use a [ReferenceQueue](http://developer.android.com/reference/java/lang/ref/ReferenceQueue.html) to clear the [WeakReference](http://developer.android.com/reference/java/lang/ref/WeakReference.html) used to do all the book keeping necessary to update async queries.

We hint to the GC to put any _weakly reachable_ reference inside the queue (to clear it) every time we receive a `REALM_CHANGE` message in the Looper (usually after a commit from another thread). 

Cheers,
