### ISSUE TITLE
Property RealmObject removal

### ISSUE THREAD

**Issue by changxiangzhong** [realm/realm-java#1731]
Hi,
Thank you so much for this amazing project you have made. Here's my question. Let's say the following are the JSON and their corresponding Java class definition.
 
    [
      {
        "id": 1111,
        "text": Some text.",
        "media": 
          {
            "id": 1,
            "url": "http://...",
         }
      },
      {
        "id": 2222,
        "text": Some text.",
        "media": 
          {
            "id": 1,
            "url": "http://...",
         }
    ]

    public class OuterClass {
      @PrimaryKey
      private int id;
      Media media;
      ...
    }
  
    public class Media {
      @PrimaryKey
      private int id;
      String url;
      ...
    }
We haven an OuterClass, which has a Media object. My questions are about realm behavior with Media object with same Primary key but in different OuterClass.
  * If I save the two objects (represented by JSON) using copyToRealmOrUpdate, how many instances of Media there will be in the database. Are they two instances, or just one instances?

**Comment by beeender** [comment]
If the `id` is the primary key of the `Media` object, then only one media will be stored in the Realm.

Depends on the order of them in the JSON, the last with with the same primary key will overwrite (with the exsiting fields in the JSON) former one if there is.

**Comment by changxiangzhong** [comment]
Related topic http://stackoverflow.com/questions/30258351/android-realm-copytorealmorupdate-creates-duplicates-of-nested-objects

@beeender Thanks for your reply. That's kinda deviate from our requirements. We hope to have two independent instance. But I could figure a few work arounds. To persist the Media JSON string, not the object. Or to re-generate the Media::id at the client side. Do you have any better suggestions?

**Comment by beeender** [comment]
Well, if the `id` is the primary key, more than on instances would be hard for any databases ...
If you want, you can just NOT set the `id` as the primary key in Realm, then two `Media` record will be stored in Realm.

**Comment by changxiangzhong** [comment]
Wow, thanks for your quick response. But then if a Media get saved twice, how can I recycle the old one? 

There will be no way to refer the old one at all.

**Comment by beeender** [comment]
If it is always linked and only linked to one `OuterClass` i think you can clean it up when cleaning the `OuterClass`.
```
outerClass.getMedia().removeFromRealm();
outerClass.removeFromRealm();
```

**Comment by changxiangzhong** [comment]
One more interesting thing is, what if `outerClass1` and `outerClass2` point to the same `Media` object. And the following get executed

    outerClass1.getMedia().removeFromRealm()
Will the `outerClass2.getMedia()` get a null pointer?

**Comment by beeender** [comment]
Yes, i think so.

**Comment by changxiangzhong** [comment]
Thanks a lot.
