### ISSUE TITLE
copyToRealm(Iterable<E> objects) not ignoring pre-existing records

### ISSUE THREAD

**Issue by TimOfTheYear** [realm/realm-java#1733]
Hello!

I'm using copyToRealm with a list that contains a mix of existing realm objects and new realm objects. However, while the documentation says the existing realm objects are ignored, instead of being ignored a RealmPrimaryKeyConstraintException is being thrown for the duplicate primary key.

From what I can tell in the API, this is the only version of the copyToRealm function that throws an exception instead of ignoring pre-existing records. 

The exception is _also_ documented though, so based on the contradictory documentation I can't tell if this is intended or indeed a bug. For my sake, I hope it is a bug :P 

It's pretty straight forward, but here is my code anyway:

              

                try {
                    realm = Realm.getDefaultInstance();
                    realm.beginTransaction();
                    realm.copyToRealm(messages);
                    realm.commitTransaction();
                } catch (Exception ex) {
                    Crashlytics.logException(ex);
                } finally {
                    if(realm != null) {
                        realm.close();
                    }
                }

**Comment by zaki50** [comment]
Hi @TimOfTheYear 

Realm's document says that `Objects already in this Realm will be ignored.`.

`Objects already in this Realm` means that an Object is not a standalone object and the corresponding Realm file of the object is the same as the one in the receiver(Realm instance).

You can use `copyToRealmOrUpdate` if you don't want to get a `RealmPrimaryKeyConstraintException`.

**Comment by kneth** [comment]
@TimOfTheYear Did @zaki50's suggestion help you?
