### ISSUE TITLE
How can I find the position where a new item was added in RealmResults

### ISSUE THREAD

**Issue by slidenerd** [realm/realm-java#1734]
![snap 2015-11-06 at 13 46 26](https://cloud.githubusercontent.com/assets/5139030/10992547/d3b17ed6-848c-11e5-92e2-6df1aa6bc7c5.png)

When I remove items on swipe, i know the exact position to call notifyItemRemoved, when I add items, how can I best determine the position within RealmResults where the item was added.

I have read your other fine grained notification threads such as this https://github.com/realm/realm-java/issues/989 and I know you are working on a fix, but is there any way for the time being to know the position where an item was inserted within RealmResults.

Also when I call setResults, can I call notifyItemRangeChanged(0, mResults.size()) or notifyItemRangeInserted(0,mResults.size()) I will be calling setResults only the very first time I load data inside a Fragment, after that I just want to call add or swipe to delete

Thanks for your answers in advance

**Comment by beeender** [comment]
Well, if you want a predictable position of an item in the list, i think it has to be ordered by something.

Maybe you can have a `Date` field to remember the modified date and sort the `RealmResults` by date?

**Comment by slidenerd** [comment]
The data item I am using are simple text strings, I am sorting them by name

**Comment by beeender** [comment]
Then i agree... Fine grained notification would be the best thing to solve it...

**Comment by cmelchior** [comment]
@slidenerd I assume the above answered your question for now. You can also follow #989 and #972 which will provide the solutions for this. Closing.
