### ISSUE TITLE
IllegalStateException caused by adapter getItemCount 

### ISSUE THREAD

**Issue by emanuelet** [realm/realm-java#1737]
I recently updated to the 0.84.1 version of the library and I'm now getting the following error:
``` java
 java.lang.IllegalStateException: Realm access from incorrect thread. Realm objects can only be accessed on the thread they were created.
```
That happens in a fragment where I have a recyclerview attached to a RealmResults query (containing messages) and the sequence of events is pretty much the following:
 - fragment, adapter and query gets initialized and instantiated correctly
 - while still inside the fragment I receive an event for a new message
 - I write this new message to realm
 - a ***.size()*** of the RealmResults gets triggered (with the notifyDatasetchanged method)
 - the exception gets thrown with the stacktrace that ends up inside the ***checkIfValid*** in ***BaseRealm.java*** for incorrect thread

Am I doing something wrong? Is it possible that the ***threadId*** field in ***BaseRealm*** gets changed somehow?

Appreciate any kind of help.

**Comment by dalinaum** [comment]
Hello @emanuelet Do you use Thread, AsyncTask, Handler or Loader in your fragment or adapter? It looks to me like that you used a Realm instance that was created by other thread.

**Comment by emanuelet** [comment]
None of that. I just create the RealmResults query in the fragment and then pass it to the adapter. 
About the realm instance in theory is the same, also because the error occurs independently by the fact that I move the .size call in the fragment or in the adapter.
My doubt here is: does a transaction (that I use to write to realm the new message) happens in the other thread?

**Comment by emanuelet** [comment]
Ok, I've digged deeper into it, attaching a Log of the current thread on every command and apparently the issue was generated by the library that I use to receive real-time messages (socket.io) that is working on the Event Thread.

Solved forcing the method on the ui thread:
```
new Handler(Looper.getMainLooper()).post(new Runnable() {
   @Override
    public void run() {
         onTyping(sender);
     }
});
```

Beware of threading, kids!

**Comment by dalinaum** [comment]
@emanuelet Great. I didn't think about Event Thread. I will add `help` tag then. If you encounter further problems, please feel free to create a new issue too.
