### ISSUE TITLE
Realm Beginswith search for multiple words

### ISSUE THREAD

**Issue by bangarharshit** [realm/realm-java#1738]
Hi Guys, I want to know if there is a way to do beginswith search when there are multiple words (and that too it works for each word). I know contains is one such thing but it is not good enough.

I can think of workaround for keyword search abc:
1. Check beginswith("abc").or.contains(" abc"). See the space that means it search only for new word beginning. I will test this and see how good it will perform. Is there any better pattern than this.

**Comment by zaki50** [comment]
Just an idea.

```
public class Entity extends RealmObject {
    private String phrase;
    private RealmList<Word> words;
    // setters and getters here
}
```

```
public class Word extends RealmObject {
    @Index
    private String word;
    // setters and getters here
}
```

And split the phrase into list of `Word` object.

Then you can build a query like:
```
realm.where(Entity.class).beginsWith("words.word", "abc")
```

**Comment by bangarharshit** [comment]
Nice.  It's much neater than what I  proposed. The only overhead is to do split into words and then commit objects for the same. For something like chat it might blow out of the portions. Do you think?

**Comment by kneth** [comment]
Once #1377 is implemented, I think it will be much easier to do the queries as you are doing. Currently, I think @zaki50's suggestion is your best option if you don't wish to do `beginswith("abc").or.contains(" abc")`.

**Comment by kneth** [comment]
I'm closing the issue as I believe that @zaki50's suggestion is the best solution for the time being.
