### ISSUE TITLE
error: cannot find symbol method realmGetRow() in generated file

### ISSUE THREAD

**Issue by foghina** [realm/realm-java#1739]
Using kotlin, my model class is simply:

```java
public open class Article : RealmObject() {
    @PrimaryKey public open var url : String? = null
    public open var title : String? = null
    public open var excerpt : String? = null
    public open var content : String? = null
    public open var imageUrl : String? = null
}
```

In my `build.gradle` I have:

```
compile "io.realm:realm-android:0.84.1"
kapt "io.realm:realm-annotations-processor:0.69.0"
```

I tried to add the annotations dependency as well, but it looks like it's not on jcenter (anymore)? Anyway I can successfully import annotations, so I guess they're part of `realm-android` now. I also cant find the gradle plugin on jcenter, not sure if that's required?

Not sure what's wrong with my setup. I've tried adding `@RealmClass` to my model but I get the same error.

Here's what the generated proxy class looks like:

![ArticleRealmProxy.java](https://cloud.githubusercontent.com/assets/412054/11019049/7bb3b82a-859a-11e5-8f64-468dc337dcb7.png)

**Comment by foghina** [comment]
Update: building from the console I also get these couple of warnings:

```
warning: Supported source version 'RELEASE_6' from annotation processor '__gen.AnnotationProcessorWrapper_debug_io_realm_processor_RealmProcessor' less than -source '1.7'
warning: The following options were not recognized by any processor: '[kapt.kotlin.generated]'
```

**Comment by zaki50** [comment]
Hi @foghina 

"io.realm:realm-android:0.84.1" includes annotation processor.

So you can write dependencies in your `build.gradle` as follows.
```
compile "io.realm:realm-android:0.84.1"
kapt "io.realm:realm-android:0.84.1"
```

We will introduce separate annotation processor jar and gradle plugin in (maybe) the next release of realm(those are already merged in master branch).

After those are introduced, you need to update dependencies in the `build.gradle`.
See https://github.com/realm/realm-java/blob/master/examples/kotlinExample/build.gradle

**Comment by foghina** [comment]
@zaki50 that's the example I was following, but I guess it only works with SNAPSHOT versions. Changing the `kapt` dependency to `realm-android` seems to have fixed my issue, thanks!

**Comment by zaki50** [comment]
@foghina You can see the example project for `0.84.1` from https://github.com/realm/realm-java/blob/v0.84.1/examples/kotlinExample/build.gradle
