### ISSUE TITLE
I'm getting Out of memory on a 235368-byte allocation

### ISSUE THREAD

**Issue by fernandodev** [realm/realm-java#1740]
Hi,

I'm populating tables with many entries and after some time I get an Out of Memory error.
`at io.realm.Realm.copyToRealmOrUpdate(Realm.java:811)`

I'm using Realm 0.84.1 and line 811 is:
```java
        ArrayList<E> realmObjects = new ArrayList<E>();
        for (E object : objects) {
            realmObjects.add(copyToRealmOrUpdate(object)); //THIS
        }
```

After populating 15 tables in the 16 (by 25 entries) app crashes
Is there anything I can do to around it?

**Comment by zaki50** [comment]
@fernandodev If you can't release any objects in some reasons, the only way is large heap by adding `android:largeHeap="true"`attribute in `application` element in `AndroidManifest.xml`.

**Comment by beeender** [comment]
@fernandodev I saw you are trying to add `RealmObject` into a normal `ArrayList`, may I ask why do you want to do that?

From memory usage perspective, it would be more efficient that you just copy them to Realm, then use query to get a `RealmResults` later.

**Comment by fernandodev** [comment]
@zaki50 Yes, I used it to avoid error. Thanx :+1: 
@beeender Unfortunately there is just one way to copyOrUpdate an object or a list of objects :(

Below my snippet code from my project. It's a callback result and I get a list of objects as return.

```java
public void result(T data) {
    super.result(data);
    if (data.isEmpty()) return;

    Realm threadRealm = Realm.getInstance(realmConfiguration);

    threadRealm.beginTransaction();
    threadRealm.copyToRealmOrUpdate(data); //Here is what I said. Is there another way to copy or update a list of objects?
    threadRealm.commitTransaction();

    threadRealm.close();
  }
```

**Comment by kneth** [comment]
To me, it sounds like the advice by @zaki50 helped you.
