### ISSUE TITLE
Hope improve stability of native code

### ISSUE THREAD

**Issue by LiuDeng** [realm/realm-java#1742]
Hope improve stability of native code:
If exception happen in native can throw the exception to java while not crash.
Thank you for your great job.

**Comment by kneth** [comment]
@LiuDeng In general, we try to catch all C++ exceptions and convert them to Java exceptions. Of course, we might have missed a few C++ exceptions, and if you experience one, we will be happy if you can send us the log.

**Comment by LiuDeng** [comment]
@kneth Thank you for reply~ I use version 0.84.1 once get a long convert to String UTF-8 Error when after createAllFromJson and then commit， but i clear it 。
If i meet aging i will new a issue。
Best Wishes~
