### ISSUE TITLE
Support listening to changes on Non-looper threads

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#1743]
All our change listeners depend on the UI thread to function. This means it can be tricky to tell background threads when to update the realm instances to the latest version. Also right now we don't warn people if they register an listener on a non-looper thread. 

This means there are a number of choices we can make

a) Throw exception when using listener on non-looper threads. ?
b) Allow listeners and find some other way of triggering them?

Would a pattern like the below make sense? It would effectively let people create their own event queue just for Realm events:

```
Realm realm = Realm.getDefaultInstance();
// Blocking method that doesn't return until Realm is changed and refreshed
// It would also automatically call all listeners
while(realm.waitForChange()) {  // return true if changed, return false if aborted
  // Work
}
realm.close();
```

**Comment by stk1m1** [comment]
Just out of curiosity. What would be Realm's standpoint when it comes to an area where Realm leads people to step in an uncharted territory? 

If it is to follow Android way (if there ever is such a thing), I'd imagine a case like above should just throw an exception saying 'there isn't a legitimate looper so put one on'. It might be very itching but for those ones who are accustomed to Android way would get a very consistent message and eventually appreciate it. I mean you can basically expect what's going to happen.

On the other hand, if an automatic situational detector kicks in and provides a pattern like above, it would be very soothing, and deliver a contrast message, 'we've got your back'. 

I am not saying which one is right or wrong. I'm just saying small thing like that could be a good indicator to show the idea. (If my comment is totally irrelevant, you can erase.)

**Comment by firasalmanna** [comment]
+1

**Comment by cmelchior** [comment]
We added `Realm.waitForChange()` and `Realm.stopWaitForChange()` a long time ago, which should solve this use case.
