### ISSUE TITLE
NullPointerException: Attempt to invoke interface method 'long io.realm.internal.Row.getIndex()' on a null object reference

### ISSUE THREAD

**Issue by Saketme** [realm/realm-java#1745]
Hello, I'm encountering another NPE and am unable to get around this.

Here's the code: https://gist.github.com/Saketme/fa769dd5dc8a580ba16f
Exception stacktrace: https://gist.github.com/Saketme/2820de307017402d98c3

Any help? :)

**Comment by zaki50** [comment]
How did you create/obtain `conversation` instance?

**Comment by Saketme** [comment]
From a Realm query. This is the flow:

Query Realm -> Pass `RealmResults` to `RecyclerView`adapter.
Next, long press conversation -> select mute -> Crash!

**Comment by zaki50** [comment]
@Saketme The setter of managed object only accepts managed object.

```
final MuteSettingItem muteSetting = new MuteSettingItem(uniqueKey, true);
realm.copyToRealmOrUpdate(muteSetting);
```

Above code, `muteSetting` is still standalone object.
Reassigning `copyToRealmOrUpdate`'s return value which is a managed object to `muteSetting` will solve the problem.

```
MuteSettingItem muteSetting = new MuteSettingItem(uniqueKey, true);
muteSetting = realm.copyToRealmOrUpdate(muteSetting);
```

**Comment by zaki50** [comment]
We should throw reasonable exception for this situation.

**Comment by zaki50** [comment]
@Saketme I made an issue to add a check if the value is valid or not.

I'll close this issue. Feel free to reopen this if you have further questions.

**Comment by Saketme** [comment]
Ah, how on earth did I forget to receive the returned object. Thanks a lot for helping me out. And yes, more helpful exceptions would be incredibly useful.
