### ISSUE TITLE
Add gotcha to doc: Never loop over RealmResults and update its items

### ISSUE THREAD

**Issue by Saketme** [realm/realm-java#1753]
So I spent quite some time wondering why some items weren't getting updated while looping over a `RealmResults`. 

The code is something similar to this:

    // Find all unread messages (where "read" flag is false)
    RealmResults<MessageItem> messagesToUpdate = messagesQuery.findAll();

    // And mark them as read
    for (int i = 0; i < messagesToUpdate.size(); i++) {
        messagesToUpdate.get(i).setRead(true);
    }

On first look, this code looks perfectly fine. However, I was just unable to understand why some items were getting skipped. And I soon realized why — because `RealmResults` is a live list! 

Damn. Updating items in the results was causing the `RealmResults` to auto-update its content. The indices were not consistent!

Looping using an interator results in an exception being thrown, which makes sense. But this code will never raise any exception and the dev. might never understand what and why is it going wrong.

Maybe you can mention this that it should never be updated while looping, even when using a fori loop. :sweat_smile:

**Comment by Saketme** [comment]
This brings me to a feature request — There should be an easier way to update an entire `RealmResults`. I'm currently copying the objects to a new list and then iterating over it. Is that the present correct way of doing it?

**Comment by kneth** [comment]
@Saketme It sounds like our documentation isn't clear on the auto-refresh feature of Realm (https://realm.io/docs/java/latest/#auto-refresh).

I'm not quite sure what you mean by "update an entire `RealmResults`. Can you share a code snippet so we can see your use case?

**Comment by Saketme** [comment]
In SQLite and other ORMs, you can quickly update a table by performing an operation like:

    Select.from(Table.class).update(COLUMN_NAME, newValue).commit();

Or something similar. It's easier to write and requires less lines of codes. In Realm, we first have to obtain the search results (`RealmResults`) and then update it. Please correct me if I'm wrong.

**Comment by kneth** [comment]
Realm doesn't have such a feature yet, and it sounds like #762 is what you're asking about.

**Comment by Saketme** [comment]
Ah yes. That feature would cut down a lot of code lines :)
