### ISSUE TITLE
Index not defined for String field

### ISSUE THREAD

**Issue by v-singhal** [realm/realm-java#1762]
Hi there

I am trying to use RealmMigration in order to add tables with primary keys (String) into the DB.
The migration is executing successfully however when accessing the Realm Db in app, I am getting the below error.

Caused by: io.realm.exceptions.RealmMigrationNeededException: Index not defined for field 

This is for a field that's of type String.
I am currently working of Realm v0.82.2

**Comment by kneth** [comment]
Did you update the model class by adding the `@PrimaryKey` annotation?

**Comment by v-singhal** [comment]
Yes, I did.
It's actually a new table that I am trying to add.

**Comment by kneth** [comment]
Can you share the model class and your migration step?

**Comment by v-singhal** [comment]
Sure..

Model Class:
`

@PrimaryKey
    private String orderIdForDelivery;
    private String riderIdForOrder;
    private String deliveryTimeForOrder;
    private String deliveryLatitudeForOrder;
    private String deliveryLongitudeForOrder;

    public String getOrderIdForDelivery() {
        return orderIdForDelivery;
    }

    public void setOrderIdForDelivery(String orderIdForDelivery) {
        this.orderIdForDelivery = orderIdForDelivery;
    }

    public String getRiderIdForOrder() {
        return riderIdForOrder;
    }

    public void setRiderIdForOrder(String riderIdForOrder) {
        this.riderIdForOrder = riderIdForOrder;
    }

    public String getDeliveryTimeForOrder() {
        return deliveryTimeForOrder;
    }

    public void setDeliveryTimeForOrder(String deliveryTimeForOrder) {
        this.deliveryTimeForOrder = deliveryTimeForOrder;
    }

    public String getDeliveryLatitudeForOrder() {
        return deliveryLatitudeForOrder;
    }

    public void setDeliveryLatitudeForOrder(String deliveryLatitudeForOrder) {
        this.deliveryLatitudeForOrder = deliveryLatitudeForOrder;
    }

    public String getDeliveryLongitudeForOrder() {
        return deliveryLongitudeForOrder;
    }

    public void setDeliveryLongitudeForOrder(String deliveryLongitudeForOrder) {
        this.deliveryLongitudeForOrder = deliveryLongitudeForOrder;
    }
`
Migration Step:
`
Table riderOrderDeliveryDataTable = realm.getTable(RiderOrderDeliveryDataTable.class);
        riderOrderDeliveryDataTable.addColumn(ColumnType.STRING, RiderOrderDeliveryDataTable.ORDER_ID);
        riderOrderDeliveryDataTable.addColumn(ColumnType.STRING, RiderOrderDeliveryDataTable.RIDER_ID_FOR_ORDER);
        riderOrderDeliveryDataTable.addColumn(ColumnType.STRING, RiderOrderDeliveryDataTable.DELIVERY_TIME_FOR_ORDER);
        riderOrderDeliveryDataTable.addColumn(ColumnType.STRING, RiderOrderDeliveryDataTable.DELIVERY_LATITUDE_FOR_ORDER);
        riderOrderDeliveryDataTable.addColumn(ColumnType.STRING, RiderOrderDeliveryDataTable.DELIVERY_LONGITUDE_FOR_ORDER);
        riderOrderDeliveryDataTable.setPrimaryKey(RiderOrderDeliveryDataTable.ORDER_ID);
        Log.i(TAG, "RiderOrderDeliveryDataTable HAS PRIMARY KEY: " + riderOrderDeliveryDataTable.hasPrimaryKey());
`

**Comment by kneth** [comment]
You need to call `addSearchIndex()` too (the annotation does that, the method doesn't). In the upcoming migration API, setting a field to primary key will also add the index.

**Comment by v-singhal** [comment]
Thanks a lot. Looks like it is working now :)

**Comment by kneth** [comment]
Great. I close the issue. Never hesitate to open a new issue if the issue occur again.
