### ISSUE TITLE
Examples should be self-contained

### ISSUE THREAD

**Issue by kneth** [realm/realm-java#1763]
Our examples of requires that you read the previous examples to get the context. For instance, one example is:

    for (User u : result) {
        // ... do something with the object ...
    }

but neither `User` or `result` in defined. A better code snippet is:

    RealmResults<User> result = realm.where(User.class).findAll();
    for (User u : result) {
        // ... do something with the object ...
    }

**Comment by cmelchior** [comment]
Fixed by https://github.com/realm/realm.io/pull/1470

**Comment by martygeek** [comment]
that link is no longer available
