### ISSUE TITLE
lessThan with negative id's not working as expected

### ISSUE THREAD

**Issue by seinen** [realm/realm-java#1773]
I am working with RealmObjects where i use negative id's (as long as they are not synced to the server).
So, when i synchronize with the server, i can get all negative id's, synchronize those objects and when synchronized, update the id.

But, when i perform a lessThan query on a RealmResult, there are less objects returned than expected.
When i use between (with f.e. values -10000, 0), it is working and i am getting all the objects returned that i expect.

So it looks like the behaviour of lessThan with negative number is not working the way i would expect it to be, Is this a bug or is there a good explanation for this?

I created a small android studio project, with a TestApplication where this test is setup, which fails (only 2 of the 10 objects are retreived). Project is on github: https://github.com/Sein-IT/RealmLessThan.

I am testing with a Samsung Galaxy S6, Android version 5.1.1

**Comment by zaki50** [comment]
@seinen Thank you for your report.

I confirmed that `lessThan` returns 2 instead of 10.

**Comment by zaki50** [comment]
```
    public void testLessThan() {
        testRealm.beginTransaction();
        long id = -1;
        for (int i = 0; i < 10; i++) {
            LessThan lt = new LessThan();
            lt.setId(id--);
            testRealm.copyToRealm(lt);
        }
        testRealm.commitTransaction();

        assertEquals(10, testRealm.where(LessThan.class).between("id", -10, -1).findAll().size());
        assertEquals(10, testRealm.where(LessThan.class).greaterThan("id", -11).findAll().size());
        assertEquals(10, testRealm.where(LessThan.class).greaterThanOrEqualTo("id", -10).findAll().size());
        assertEquals(10, testRealm.where(LessThan.class).lessThan("id", 128).findAll().size());
        assertEquals(10, testRealm.where(LessThan.class).lessThan("id", 127).findAll().size());
        assertEquals(10, testRealm.where(LessThan.class).lessThanOrEqualTo("id", -1).findAll().size());
        assertEquals(10, testRealm.where(LessThan.class).lessThan("id", 0).findAll().size());
    }
```

Last 3 assertions fail with actual value `2`.

**Comment by kneth** [comment]
I have been able to reproduce the issue in C++ using Realm's storage/query engine only. The bug is probably the same as https://github.com/realm/realm-cocoa/compare/mr-wrong-int-query-result, and we are currently investigating it.

**Comment by kneth** [comment]
Just a quick update: we have identified a bug in our underlying storage/query engine,  It only affects ARM. It will be fixed in the coming days.

**Comment by kneth** [comment]
Sorry for not updating the status. The bug has been fixed and a release was made. I have added a unit test (basically the example by @zaki50 as can be found above).
