### ISSUE TITLE
What would be the best way to impose an upper limit on the number of rows stored in Realm?

### ISSUE THREAD

**Issue by slidenerd** [realm/realm-java#1776]
I am using Realm database to cache json feeds for processing in the app. The json data is time based and I keep fetching new entries with time. Is there a mechanism in Realm by which I can store, say only the newest 100 rows and get rid of the old ones as soon as I start storing more? I read the documentation extensively and did not come across a feature like that. Thanks for your time in advance

**Comment by Saketme** [comment]
You are requesting a very niche feature that can easily be implemented on your own. There are far more important things to solve for the Realm team :)

**Comment by cmelchior** [comment]
Hi @slidenerd You are looking for a Circular Buffer (https://en.wikipedia.org/wiki/Circular_buffer) It is not something that Realm supports natively, but it should be relatively easy to create your own implementation in either pure java (with Realm backing the list) or by using a custom RealmObject with a RealmList and start/end pointers. The later will probably not work as well though until we implement #909

**Comment by slidenerd** [comment]
The truth be told, I am not requesting anything from the realm tealm @Saketme I am merely trying to see if the manual option of storing all the entries first and then removing the extra entries is the best possible solution which is what I am doing currently, and thanks for the answer @cmelchior

**Comment by Saketme** [comment]
Ah, sorry, I misunderstood your question @slidenerd
