### ISSUE TITLE
ANR upon executing equalTo() hundreds of times inside a loop

### ISSUE THREAD

**Issue by Saketme** [realm/realm-java#1778]
Hello team, I'm noticing a strange behavior with Realm when calling `equalTo()` on a `RealmQuery` inside a loop where the app stops responding.

There's no stacktrace to debug this. I guess the crash is happening somewhere when `findAll()` is called on the query.

I can email the sample project if you want.

**Comment by cmelchior** [comment]
Chances are it is not crashing, but that the query is taking more than 5 seconds. 5 seconds is a very long time though, but calling `equalTo()` hundreds of times also sound pretty extreme. What is the use since you need to call it that many times?

Note, you can use our new `findAllAsync` to prevent running the query on the UI thread, which should stop the ANR.

**Comment by Saketme** [comment]
It takes around 15-20ms to execute all the `equalTo()` methods. The app stops responding as soon as `findAll()` is called.

And, I need to exclude a lot of IDs when searching the DB. Since Realm does not support specifying multiple parameters in `equalTo()`, doing it in a loop is the only available option.

Possible for you to quickly view the code and let check if it's a Realm issue or not?

**Comment by cmelchior** [comment]
Sure, but it is most likely is a Realm issue. We don't actually run the query until you call `findAll()`, until then it is just building up internal data structures for the actual query.

So running it on a background thread using `findAllAsync()` is the best choice, because with that many clauses it will be slow even if we implemented `IN` or similar.

I am curious about how much data you are querying though? and with how many `equalTo` comparisons?

**Comment by Saketme** [comment]
In the sample app, I'm querying some 500 items. And some ~100 `equalTo` comparisons.

**Comment by kneth** [comment]
We have a unit test with 2516  items and 2516 `equalTo` comparisons (added to hunt down a memory leak in C++) - see `RealmResultsTest.testManyConditions()`.

**Comment by cmelchior** [comment]
Hi @Saketme I just tried to do some benchmarks, and even with many more `equalTo` comparisons it is nowhere near the long query time you are experiencing. If you can email your sample project to help@realm.io that would be very helpful.

**Comment by Saketme** [comment]
Sent from email saket@saket.me. Thank you!

**Comment by Saketme** [comment]
As discussed with Christian Melchior, this seems to be a device specific bug. It's running fine on his phone, running Android M. The same code stops responding on my Moto G3 (Android L).

However, I'm closing this issue as the code (where ANR was happening) is no longer required.

A more proper solution would be the support of multiple parameters in `equalTo` method. Looking forward to it.

**Comment by Saketme** [comment]
Update: So this just happened in another part of my app. Tried to delete a lot of items at once using the same method described above and the app stopped responding. 

Is there any way to send you some log?

**Comment by kneth** [comment]
@Saketme You can send the log to help@realm.io.

**Comment by Saketme** [comment]
Hold on, does Realm generate any type of log? Because no Stacktrace report gets generated whenever this happens.

**Comment by kneth** [comment]
I imagine that ANR will show up in your log. But you can trace all calls to C++ by calling `io.realm.internal.Util.setDebugLevel(5)`.

**Comment by kneth** [comment]
@Saketme Did you progress on this one? Can you reproduce the issue in a short test?

**Comment by Saketme** [comment]
No I did not :( I finally had to include one more column for quickly updating them, which surprisingly works well when I'm in fact using the same loop way of adding multiple parameters. I'm waiting for Sunday to come (tomorrow) so that I can send you a stripped down version of my project where maybe you can debug the issue.

Oh and I somehow overlooked your previous comment of enabling debugging. Will try it out, thank.

**Comment by kneth** [comment]
@Saketme Can we close the issue?

**Comment by Saketme** [comment]
Yes, closing it for now. Will re-open if I run into this problem again.
