### ISSUE TITLE
realm.copyToRealmOrUpdate(...) and Many-To-Many/RealmList update in same transaction?

### ISSUE THREAD

**Issue by seventyone-ben** [realm/realm-java#1785]
Hi,

I want to sync via REST-API and I'm getting a List of unmanaged Realm-Objects, which I update with

```
List<Entity> unmanaged = <from API>;

realm.beginTransaction();

for (Entity entity : unmanaged) {
    realm.copyToRealmOrUpdate(entity);

    List<OtherEntity> otherEntities = <loaded from Realm>;
    entity.getRelationships().addAll(otherEntities);
}
realm.commitTransaction();

```

and it ends in a `NullPointerException` on `.getRelationships()`, which is a `RealmList<OtherEntity>`.

As far as I tested it seems that the underlying `LinkList`/`LinkView` is `null` until the transaction is committed. If I add the relationships in another transaction it works, but is this really necessary? It would be great to only iterate once over all my objects to update them.

Best regards,
Ben

**Comment by kneth** [comment]
You should do `Entity entityInReam = realm.copyToRealmOrUpdate(entity);` and use `entityInRealm` instead of `entity`. The reason is that `entity` isn't backed by your Realm (still unmanaged) while `entityInRealm` is a Realm object.

**Comment by seventyone-ben** [comment]
Feeling really stupid not seeing/trying that... Thx for the explanation!
