### ISSUE TITLE
Best practice: Always do writes off the UI thread

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#1787]
Add a section to *Best practices* documenting that writes should always be done outside the UI thread to prevent accidentally blocking it.

**Comment by cmelchior** [comment]
Fixed by https://github.com/realm/realm.io/pull/1466

**Comment by Saketme** [comment]
Not having the option to pass RealmObjects across threads is a botteneck here since I mostly query data on the UI thread. How do you recommend updating them in the background then?
