### ISSUE TITLE
mips64 not support

### ISSUE THREAD

**Issue by hamberluo** [realm/realm-java#1788]

**Comment by beeender** [comment]
Thanks a lot for your feedback! We definitely should support mips64.
May I know if there is any special reason you want mips64 support? Since AFAIK there is not too many users are using mips64 Android device.

Also, can you suggest a mips64 device that we can use as a testing device if you have relevant information?

**Comment by hamberluo** [comment]
The only reason I want mips64 support is that I use other libs support mips64.
So it will cause crash in those mips64 devices since we don't have ream jni lib on those devices.
Sorry for that I cannot suggest any mips64 device. Hope your team resolve it.
Many thanks!

**Comment by beeender** [comment]
@hamberluo Got it! The workaround right now is you can exclude the other lib's mips64 version (Realm 's arm64 `so` is excluded by some projects because of the same reason :( )

```
android {
    //...
    packagingOptions {
        exclude "lib/mips64/libxxxxx-jni.so"
    }
    //...
}
```

We will try to release with mips64 support soon :)

**Comment by beeender** [comment]
@hamberluo May I know what kind of mips64 device did you meet the problem? We really want to get a mips64 device for testing, but cannot find any in the market.

**Comment by hamberluo** [comment]
@beeender Maybe one of those device
- BBK VIVO E3
- XIAOMI 2014011
- NOKIA N1

**Comment by beeender** [comment]
@hamberluo Are those devices from your crash report? Then it might not be related with mips64, or some really strange issues related with `loadLibrary` in those devices.

* BBK VIVO E3 -- MediaTek MT6575A (arm)
* XIAOMI 2014011 -- ARM MT6582
* NOKIA N1 -- Intel Atom Z3580 (x86_64)

Is there any information in the crash log leads you to think it might be related with mips64 (not arm64)?

**Comment by hamberluo** [comment]
@beeender yes, they are from my crash report and lead me to add this issue.

**Comment by beeender** [comment]
@hamberluo Remove the mips64 from other library might not solve the issue, since the mips64 so should not be installed to those devices at all. I suggest you examine other so of your apk as well. maybe there are some libraries don't have arm64 which caused this issue.

**Comment by beeender** [comment]
After two years, there are still no mips64 device in the market. Close this issue.
