### ISSUE TITLE
Migration, from one object (old) to another object (new)

### ISSUE THREAD

**Issue by jofor** [realm/realm-java#1789]
Hi again. Thanks once again for the awesome work you are doing on this ORM. I have yet another question. When using the new migration scheme. How would I correctly copy data from an old object (Old.java) to another Object (New.java) Correctly? The two classes shares many of the same attributes but in this case a simple upgrade of more fields to Old.java was not enough.

```
        // Migrate from version 0 to version 1
        if (version == 0) {
            Table old = realm.getTable(old.class);
            long nameIndex = getIndexForProperty(old, "name");
            for (int i = 0; i < old.size(); i++) {
            String name = oldDevices.getString(nameIndex, i);
  //create new.java table or add new.java to realm and copy values from old.java, how todo correctly?
            }
            version++;
        }
        return version;

private long getIndexForProperty(Table table, String name) {
        for (int i = 0; i < table.getColumnCount(); i++) {
            if (table.getColumnName(i).equals(name)) {
                return i;
            }
        }
        return -1;
    }
```

**Comment by kneth** [comment]
If you are modified a model class by adding a new field or renaming an existing field, you don't have to copy the old objects. In cases of such "trivial" changes to your model class, your migration step only requires that you add or rename the underlying column.

**Comment by jofor** [comment]
hi @kneth Sadfully that is not the case, the old.java class is still in use, but more functionality in code has required our code to support both old.java and a new.java class and depending on the situation. Data from old.java must be moved into a new.java. New.java shares a few fields from old.java but has a lot more.

For this specific purpose adding more fields to the old.java is not enough. Copying certain fields to an entire new object and adding is what i'd need help with :)

My current solution is something like: 

```
if (version == 0) {
            Table old = realm.getTable(Device.class);

            long unitIndex = getIndexForProperty(old, "unit");
            long addressIndex = getIndexForProperty(old, "address");
            long nameIndex = getIndexForProperty(old, "name");
            long deviceNameIndex = getIndexForProperty(old, "deviceName");


            for (int i = 0; i < old.size(); i++) {
                String unit = old.getString(unitIndex, i);
                String address = old.getString(addressIndex, i);
                String name = old.getString(nameIndex, i);
                String deviceName = old.getString(deviceNameIndex, i);

                NewData newData = new Newdata();
                newData.setUnitType(Integer.parseInt(unit));
                newData.setId(address);
                newData.setAddress(address);
                newData.setName(name);
                newData.setDisplayName(deviceName);

                realm.beginTransaction();
                realm.copyToRealmOrUpdate(newData);
                realm.commitTransaction();

            }
            version++;
        }
        return version;
```
However I'm having issues with it atm

**Comment by kneth** [comment]
Besides the calls to `beginTransaction()` and `commitTransaction()` it looks fine to me. The `getIndexForProperty()` could be change to `old.getColumnIndex()` but that's more a optimisation. What kind of issues do you see?

**Comment by jofor** [comment]
@kneth I ended up doing something similar to your first suggestion. It worked out great even tho there were a few bumps and bruises on the way :)
