### ISSUE TITLE
Any thoughts how to use realm with j2objc ?

### ISSUE THREAD

**Issue by aminelaadhari** [realm/realm-java#1791]
The fact that realm exists for both android and ios is really a game changer for mobile databases.
Combined with tools like j2objc would make realm choice number one for small teams trageting both android and ios.

Any thoughts what is the best way to implement this kind of approach especially with the fact model classes in java extend RealmObject and it is not the case for Swift model ?

**Comment by kneth** [comment]
We certainly agree that Realm will be a game changer :-) The cross-platform compatibility is very important for us. I don't know if you know but the Realm Browser can generate model classes for the same Realm file for both Objective C and Java?

The limitation that you have to extend `RealmObject` is something we are considering removing, see e.g. #1036.
