### ISSUE TITLE
Move class that defines a table

### ISSUE THREAD

**Issue by rimeissner** [realm/realm-java#1793]
Currently moving a class to a different package will cause a loss of all data of this class, as it is regarded as a new table that doesn't exist in the Realm yet.

Is it possible to rename the table, so that the data can still be used? Are there any other best practises for this case? Will it be possible with the new migration API?

Cheers
Richard

**Comment by cmelchior** [comment]
Just moving a class should be fine as the underlying storage engine doesn't save information about the package names. Renaming classes is however currently a big pain as it requires you creating the new class and moving everything manually.

This will change with the next Migration API where it will be a one-liner:
```
realm.getSchema().rename("Old", "New");
```
We are wrapping it up now as you can see here: https://github.com/realm/realm-java/pull/1496, and current plan is to release it next week.

**Comment by rimeissner** [comment]
Sounds awesome :)

Thanks for the help

One follow up question, when no information about the package names is used, does this mean I would get conflict when I create 2 classes with the same name in different packages?

**Comment by cmelchior** [comment]
Yes, that doesn't work currently. We have an issue tracking it here https://github.com/realm/realm-java/issues/1616

**Comment by rimeissner** [comment]
Thanks for the clarification. I am looking forward to the new migration system and dynamic realms ;)

**Comment by cmelchior** [comment]
Plan is to release it next week. So hopefully you don't have to wait long :)
I'll close this now, but feel free to reopen if any other issues pop up.
