### ISSUE TITLE
Force clear Realm file

### ISSUE THREAD

**Issue by Saketme** [realm/realm-java#1796]
In our app, we're clearing our Realm file when the user chooses to sign out of the account. Now, in the present format, Realm does not allow clearing of the file until all Realms instances are closed.

This has become a problem for us because there are several classes which are maintaining their own Realm instances (all on the UI thread). 

Is there a way to force clear everything in Realm?

**Comment by cmelchior** [comment]
Begin a transaction and clear all the tables should work? A transaction is a lock that prevents other people from touching the data while doing so.

**Comment by cmelchior** [comment]
```
realm.beginTransaction();
realm.clear(Foo.class);
realm.clear(Bar.class);
realm.commitTransaction();
```

**Comment by Saketme** [comment]
That's what we're using, but this requires you to remember all RealmObjects you have in your project. Everytime you create a RealmObject, you must remember adding it to this list.

**Comment by cmelchior** [comment]
Yes, currently there is that or `Realm.deleteFile()`, the later requires that no-one has opened the file. Adding a `realm.clearAll()` is basically the same as `Realm.deleteFile()`, so I am not sure we would want to add that. Exposing something like `RealmConfiguration.getClasses()` might have more use cases though and you could iterate over that to clear them.

EDIT: It seems we by mistake have `getSchemaMediator()` public on RealmConfiguration. This means you can do this instead:

```
Set<Class<? extends RealmObject>> modelClasses = configuration.getSchemaMediator().getModelClasses();

realm.beginTransaction();
for (Class realmClass : modelClasses) {
  realm.clear(realmClass);
}
realm.commitTransaction();
```

**Comment by Saketme** [comment]
That looks like the good solution, even though it was not intended to be ever visible :P

**Comment by cmelchior** [comment]
Yes, I created #1797 to fix that and add a proper API for it. So use at your own discretion :)

**Comment by Saketme** [comment]
Off-topic, How on earth is @bmunkholm able to remove labels as soon as an issue is closed? An auto-script?

**Comment by cmelchior** [comment]
Yes, we use Waffle.io to better manage GitHub issues. It has some automated workflows.

**Comment by Saketme** [comment]
Ah. :+1:
