### ISSUE TITLE
RealmConfiguration.getSchemaMediator is public 

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#1797]
It seems we by mistake left `RealmConfiguration.getSchemaMediator` public.
We should revert that to package private.

That said, there might still be use-cases where people want to know the classes part of the RealmConfiguration, so we should expose something like

```
// Not sure what is best?
RealmConfiguration.getClasses()
RealmConfiguration.getSchemaClasses()
RealmConfiguration.getRealmClasses()
```

One example of use case here: 
https://github.com/realm/realm-java/issues/1796

**Comment by Saketme** [comment]
+1 for `RealmConfiguration.getRealmClasses()`

**Comment by cmelchior** [comment]
Yes, I am probably leaning towards that one as well
