### ISSUE TITLE
Unexpected adapter view refresh after onPause()

### ISSUE THREAD

**Issue by changxiangzhong** [realm/realm-java#1801]
Hi all,
I'm getting this exception 
```java.lang.IllegalStateException: Illegal State: Object is no longer valid to operate on Was it deleted by another thread?"```. The exception is thrown from a ```Adapter::getGroupCount()``` method. Which doesn't make sense to me is fragment's ```onPause()``` method has already been invoked.

The whole sequence is as following: There are 5 steps as following. What's worthy mentioning is in step 2, a server request is made, and in step 4 the server replies a response, and we save the data into the Realm DB, which cause the exception. Again, what I don't understand, is the TaskSentDetailFragment is already in "onPause" state. Which its adapter is still being invoked. Is there some way to bypass this 

    ===>: TaskSentDetailFragment::onPause()
    ===>: TaskSentListFragment::onActivityCreated() //Will trigger the communication to Server
    ===>: TaskSentListFragment::onResume()
    ===>: onGetSentTasks // Server has replied, update the Realm DB
    ===>:java.lang.IllegalStateException: Illegal State: Object is no longer valid to operate on. Was it deleted by another thread?

**Comment by zaki50** [comment]
Hi @changxiangzhong 

Are you using RealmChangeListener to invoke `notifyDatasetChanged()` in `TaskSentDetailFragment `?

**Comment by changxiangzhong** [comment]
Absolutely. @zaki50 

Maybe it's just as simple as onPause() doesn't guarantee the Adapter is not being invoked.

**Comment by zaki50** [comment]
Are you using RealmBaseAdapter?

**Comment by changxiangzhong** [comment]
Not really

**Comment by zaki50** [comment]
In order to bypass invoking some methods while the Fragment is not resumed state, you can use `Fragment.isResumed()`.

Will it help?

**Comment by changxiangzhong** [comment]
A hackish way could be just flip the ListView visibility in ```onResume``` and ```onPause```. But then we will have a ** white screen** during fragment page animation. But anyway, that works.
