### ISSUE TITLE
Realm Migration for Column type long not working

### ISSUE THREAD

**Issue by mihirjoshi21** [realm/realm-java#1806]
I have an existing realm file in which I want to add a column -
```
Table wordTable = realm.getTable(WordModel.class);
wordTable.addColumn(ColumnType.INTEGER, "timestringLong");
```
and this is the field I added in my ```WordModel``` class 
```private long timestringLong;```

This is the exception - 
```
JNI DETECTED ERROR IN APPLICATION: input is not valid Modified UTF-8: illegal continuation byte 0x2e
11-20 11:55:40.019 17835-17952/com.my.app A/art: art/runtime/check_jni.cc:65]     string: 'Unrecoverable error. Failure when converting long string to UTF-16 error_code = 2; retcode = 0; StringData.size = 8188713; StringData.data =
```

**Comment by kneth** [comment]
This is indeed a strange error. The exception indicates that you are passing a string of 8188713 characters from Java to C++, and "timestringLong" is a much shorter. Can you see more in the log file? And it is possible to send you the Realm file (you can send it to help@realm.io)?

**Comment by mihirjoshi21** [comment]
That is all in the android logcat. I have sent you the realm file.

**Comment by kneth** [comment]
Communication is currently done by direct emails to resolved the issue.

**Comment by bmunkholm** [comment]
@kneth Any updates on this?

**Comment by mihirjoshi21** [comment]
You can close the issue as I am not able to reproduce the bug and cannot share the orignal database.
