### ISSUE TITLE
I have some error ZipException.

### ISSUE THREAD

**Issue by jompon** [realm/realm-java#1807]
I have setup realm then have error.
I have download realm-java-0.85.0.zip
then copy realm-java-0.85.0.jar to libs folder
and setup build.gradle
compile files('libs/realm-android-0.85.0.jar')
compile 'io.realm:realm-android:0.85.0'

For Run have some error.
>Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'. > com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: io/realm/BaseRealm$MigrationCallback.class

**Comment by zaki50** [comment]
Hi @jompon 

You don't need to add `compile files('libs/realm-android-0.85.0.jar')` to your dependencies.
Just adding `compile 'io.realm:realm-android:0.85.0'` is enough.

See https://realm.io/docs/java/latest/#installation

**Comment by jompon** [comment]
Remove it and can run program.

then next error.
>java.lang.NoClassDefFoundError: io.realm.internal.SharedGroup$Durability
>RealmConfiguration config = new RealmConfiguration.Builder(this).build();

**Comment by zaki50** [comment]
Are you using multidex?

**Comment by jompon** [comment]
Yes

**Comment by zaki50** [comment]
Can you try to disable multidex?

**Comment by jompon** [comment]
I have remove it
This is the error result.

>Error:Execution failed for task ':app:transformClassesWithDexForDebug'. > com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_31\bin\java.exe'' finished with non-zero exit value 2

**Comment by zaki50** [comment]
I can't see the reason of that error. Maybe methods count exceeds 64k limit?

**Comment by jompon** [comment]
Yeah

**Comment by zaki50** [comment]
Can you decrease the method count by removing unused libraries?

**Comment by jompon** [comment]
I can't

**Comment by zaki50** [comment]
Hmm..

enable multidex again, and adding some reference to Durability class to `onCreate()` of your application class solves might be solve your problem.

```
public void onCreate() {
    super.onCreate();

    ...

    SharedGroup.Durability durability = SharedGroup.Durability.FULL; // add this line
}
```

**Comment by jompon** [comment]
How? Like this?

    public class MyApplication extends Application{

        @Override
        public void onCreate() {
            super.onCreate();

            SharedGroup.Durability durability = SharedGroup.Durability.FULL;
            RealmConfiguration config = new RealmConfiguration.Builder(this).build();
            Realm.setDefaultConfiguration(config);
        }
    }

**Comment by zaki50** [comment]
yes.

Does it work?

**Comment by jompon** [comment]
No 'durability' is never used.

**Comment by zaki50** [comment]
still error is thrown for the same class?
or for other clases?


> java.lang.NoClassDefFoundError: io.realm.internal.SharedGroup$Durability

**Comment by jompon** [comment]
same class same this new error.

```java
11-22 19:30:08.778 10295-10331/com.filmsmithsbkk.tourdio E/GMPM: getGoogleAppId failed with status: 10
11-22 19:30:08.780 10295-10295/com.filmsmithsbkk.tourdio E/dalvikvm: Could not find class 'io.realm.internal.modules.FilterableMediator', referenced from method io.realm.RealmConfiguration.createSchemaMediator
11-22 19:30:08.780 10295-10331/com.filmsmithsbkk.tourdio E/GMPM: Uploading is not possible. App measurement disabled
11-22 19:30:08.780 10295-10295/com.filmsmithsbkk.tourdio E/dalvikvm: Could not find class 'io.realm.internal.modules.CompositeMediator', referenced from method io.realm.RealmConfiguration.createSchemaMediator
11-22 19:30:08.781 10295-10295/com.filmsmithsbkk.tourdio E/dalvikvm: Could not find class 'io.realm.internal.RealmProxyMediator', referenced from method io.realm.RealmConfiguration.getModuleMediator
11-22 19:30:08.782 10295-10295/com.filmsmithsbkk.tourdio E/dalvikvm: Could not find class 'io.realm.exceptions.RealmException', referenced from method io.realm.RealmConfiguration.getModuleMediator
11-22 19:30:08.783 10295-10295/com.filmsmithsbkk.tourdio E/dalvikvm: Could not find class 'io.realm.exceptions.RealmException', referenced from method io.realm.RealmConfiguration.getModuleMediator
11-22 19:30:08.783 10295-10295/com.filmsmithsbkk.tourdio E/dalvikvm: Could not find class 'io.realm.exceptions.RealmException', referenced from method io.realm.RealmConfiguration.getModuleMediator
11-22 19:30:08.784 10295-10295/com.filmsmithsbkk.tourdio E/dalvikvm: Could not find class 'io.realm.exceptions.RealmException', referenced from method io.realm.RealmConfiguration.getModuleMediator
11-22 19:30:08.791 10295-10295/com.filmsmithsbkk.tourdio E/dalvikvm: Could not find class 'io.realm.Realm$1', referenced from method io.realm.Realm.<clinit>
11-22 19:30:08.954 10295-10295/com.filmsmithsbkk.tourdio E/AndroidRuntime: FATAL EXCEPTION: main
                                                                           Process: *****, PID: *****
                                                                           java.lang.VerifyError: io/realm/Realm
```
>RealmConfiguration config = new RealmConfiguration.Builder(this).build();

**Comment by zaki50** [comment]
It seems to be solved `java.lang.NoClassDefFoundError: io.realm.internal.SharedGroup$Durability`.

That means multidex wrongly put classes those are needed by your Application class into secondary dex file.
That causes the class not found.
You can check required classes is put into primary dex file by showing the content of `build/intermediates/multi-dex/debug/maindexlist.txt`.

To solve next class not found problem, adding the references to those classes from Application class will help.

We should have the documentation for multidex configuration.
I file that as #1815

**Comment by zaki50** [comment]
@jompon What version of android gradle plugin are you using?

Can you try 1.5.0?

```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.5.0'

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}
```

**Comment by jompon** [comment]
Yeah it is gradle:1.5.0

**Comment by kneth** [comment]
I will close the issue and track the issue through #1815.
