### ISSUE TITLE
Add description for Retrofit 2 to Retrofit docs

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#1808]
API has changed slightly for Retrofit 2, add that to the docs as well

**Comment by AKiniyalocts** [comment]
I can knock this out pretty quick. Am I able to do a PR for the docs? I can't seem to find them in the repo.

**Comment by cmelchior** [comment]
@AKiniyalocts Any help will be greatly appreciated. The docs are not in a public repo unfortunately, but if you want you can make a pull request towards this repo, and I can make sure it gets moved to the correct repo.

Our documents are written in markdown, so if you just create a standalone markdown document that will work fine.

**Comment by AKiniyalocts** [comment]
@cmelchior awesome, just wrote this up. Any special branch you want me to PR to?

**Comment by cmelchior** [comment]
`master` is fine

**Comment by cmelchior** [comment]
Closed by https://github.com/realm/realm-java/pull/2210
