### ISSUE TITLE
Big file size

### ISSUE THREAD

**Issue by crysan** [realm/realm-java#1810]
Hi!

Yes, I've read https://realm.io/docs/java/latest/#faq Large Realm file size
But the fact is that if the entries in the database in the program there was an error and the program is closed, the file size of the database grows.

In this case, the command compactRealmFile not reduce the file size.
It seems that in the database are phantom records.

What to do?

**Comment by kneth** [comment]
If you can share the Realm file with us, it would be very helpful. You can send it to help@realm.io.

**Comment by crysan** [comment]
Ok. Send email.

**Comment by kneth** [comment]
I have tried to compact your Realm file. Before compaction, file size was 300 MB, and after it is 2 MB. Indeed a lot of free space exists in the file.

To be far, I compacted it using a utility in C++ (using the underlaying the storage directly as you cannot do). 

Just a remark, free space in Realm files will be reused when adding new objects. But more than 280 MB is far too much free space to carry.

Can you elaborate a bit on how the error occurred?

**Comment by crysan** [comment]
An error has occurred in the following way:
Using AsyncTask<String, String, String>
The loop gain html page, parse it and the data entered into the database:
<code>

                                                Books issetbook2 = realm_.where(Books.class).equalTo("url_base", url_author + bk[0].trim()).findFirst();

                                                //func.showLog("issetbook2: " + url_author + bk[0].trim());
                                                try{
                                                    realm_.beginTransaction();
                                                    Books book;
                                                    if (issetbook2 == null) {
                                                        book = new Books();
                                                        book.setUrl_base(url_author + bk[0].trim());
                                                        book.setUrl_base_md5(func.MD5(url_author + bk[0].trim()));
                                                    } else {
                                                        book = issetbook2;
                                                    }

                                                    if (!bk[2].equals(" "))
                                                        book.setBook_name(bk[2].trim());
                                                    if (!bk[3].equals(" "))
                                                        book.setBook_type(bk[3].trim());
                                                    if (!bk[4].equals(" "))
                                                        book.setBook_kb_size(Integer.valueOf(bk[4].trim()));
                                                    if (!bk[5].equals(" "))
                                                        book.setBook_date_update(func.strToDate(bk[5].trim()));
                                                    if (!bk[6].equals(" "))
                                                        book.setBook_rating(Double.valueOf(bk[6].trim()));
                                                    if (!bk[7].equals(" "))
                                                        book.setBook_rating_people(Integer.valueOf(bk[7].trim()));
                                                    if (bk.length>8 && !bk[8].equals(" "))
                                                        book.setBook_desc(bk[8].trim());

                                                    book.setBook_razdel(razdel_name);
                                                    book.setAuthor(issetauthor2);

                                                    realm_.copyToRealmOrUpdate(book);
                                                    realm_.commitTransaction();
                                                } catch (Exception e) {
                                                    new DebugLog(getActivity(), "SettingsFragment", "importBooksFile Book1", Log.getStackTraceString(e));
                                                    realm_.cancelTransaction();
                                                }
</code>

If for some reason the program crashes, it is a growth of the database file.

**Comment by kneth** [comment]
I was going to ask you if you have multiple threads but you already provided the answer that you do ;-)

When a Realm file is opened on multiple threads, the concurrent versioning implies that the Realm is at different versions. That explains why Realm files might be larger than the actual objects. When a version is not needed any more, the space isn't reclaimed but reserved to later use (cleaning up unused space and later allocating new space isn't good for performance).

It sounds like your AsyncTask can time a while (waiting for the network?), which means that the rest of the app's threads can build up many versions and leave use with a large file.

Said that, compacting your Realm file when the app is starting up is a good idea. And I will investigate why it doesn't compact it as much as you expect.

**Comment by crysan** [comment]
Good.  I am waiting for your decision on the seal of the database file.

**Comment by kneth** [comment]
I did create a small app with your Realm file as a raw resource. The app only does:

    copyBundledRealmFile(this.getResources().openRawResource(R.raw.samlibreaderlike), "default0.realm");
    RealmConfiguration realmConfiguration = new RealmConfiguration.Builder(getApplicationContext()).migration(new RealmMigration() {
            @Override
            public long execute(Realm realm, long version) {
                return 0;
            }
        }).name("default0.realm").build();
    Realm.compactRealm(realmConfiguration);
    Log.d("REALM", "size = " + new File(realmConfiguration.getPath()).length());

The line in the log file is:

    D/REALM: size = 1966080

that is, about 2 MB which is the same result I got when I did my test directly in C++.

Yes, compacting Realm files is important when you run with many threads. This is an issue, we are aware of, and we plan to improve the memory management of Realm's underlying storage engine.

**Comment by crysan** [comment]
I tried your code.  Yes, the file size has decreased.  Thank you for your support!

**Comment by kneth** [comment]
You're welcome!

**Comment by erudonja1** [comment]
Hey guys,

check my solution here. It works :)

http://stackoverflow.com/questions/34217476/android-realm-large-file-size/42959238#42959238

**Comment by Zhuinden** [comment]
@erudonja1 technically `compactRealm()` doesn't actually compact (and returns false) if you have random open Realm instance somewhere that is unclosed, you can use `Realm.getGlobalInstanceCount()` to verify this

**Comment by erudonja1** [comment]
@Zhuinden yes, that's correct, but this solution doesn't depend on those situations. Try it :)
