### ISSUE TITLE
UTF16 cpp read from realm  crash

### ISSUE THREAD

**Issue by diegomontoya** [realm/realm-java#1811]
Fatal Exception: io.realm.exceptions.RealmError: Unrecoverable error. Failure when converting long string to UTF-16 error_code 

The actual string value and crash info is sent to help@realm.io.

Expectation: If set/save string to realm is valid, then retrieve should be valid in reverse direction.

Maybe related to https://github.com/realm/realm-java/issues/1756

**Comment by kneth** [comment]
Got it! Thanks! I'll dive into it and see under what conditions it can be reproduced.

**Comment by kneth** [comment]
Discussion move to emails.

**Comment by beeender** [comment]
thread on helpscout https://secure.helpscout.net/conversation/141509249/2321/?folderId=366144

**Comment by diegomontoya** [comment]
1.0.0 crash on a SM-G7102 device (4.4.2)

```
Fatal Exception: io.realm.exceptions.RealmError: Unrecoverable error. Failure when computing UTF-16 size error_code = 1; retcode = 300; StringData.size = 131586; StringData.data = 
 in io_realm_internal_UncheckedRow.cpp line 138
       at io.realm.internal.UncheckedRow.nativeGetString(Unknown Source)
       at io.realm.internal.UncheckedRow.getString(Unknown Source:153)
```

Based on the fact that the String field that caused this error in our code can only contain a maximum of 255 UTF-8 chars based on our own data spec for that field, I can only guess that the "131586 bytes" size reported by the engine signals a db corruption and not related to any real string decoding.

**Comment by diegomontoya** [comment]
0.91.9 crash on Trio AXS 4G (4.2.2)

Same as above the column in question, although in a different realm, has our own size restriction of 255 utf8/utf16 chars so it is not possible we stored more than this amount into the db vs the StringData.size reported 11.9MB below.

```java
Fatal Exception: io.realm.exceptions.RealmError: Unrecoverable error. Failure when computing UTF-16 size error_code = 1; retcode = 128; StringData.size = 11957358; StringData.data =  in io_realm_internal_UncheckedRow.cpp line 138
       at io.realm.internal.UncheckedRow.nativeGetString(Unknown Source)
       at io.realm.internal.UncheckedRow.getString(Unknown Source:153)
```

**Comment by kneth** [comment]
@diegomontoya Thanks for the update. Do you have the possibility to shared the Realm files?

**Comment by diegomontoya** [comment]
@kneth Have not see this crash with 1.20 realm with our last few versions of our app which took extra care of protecting 2 processes of same app writing to realm.
