### ISSUE TITLE
Add a section of multidex configuration to our documentation

### ISSUE THREAD

**Issue by zaki50** [realm/realm-java#1815]
from #1807

**Comment by cmelchior** [comment]
Good idea.
Do we have any concrete advice we know that works? We have seen a few bugs that might hint to Multidex being the problem, but nothing specific, right?

**Comment by zaki50** [comment]
Unfortunately we don't have any concrete advice for now.

**Comment by kkooff114** [comment]
I have done all the following steps and solved #1087


1. Add this dependencies to my app `build.gradle`
```java
dependencies {
  ...
  compile 'com.android.support:multidex:1.0.1'
} 
```
2.Have my Application class extend MultiDexApplication class
```java
public class MyApplication extends MultiDexApplication { .. }
```
3.Call `MultiDex.install`
```java
public class MyApplication {
    protected void attachBaseContext(Context base) {
        super.attachBaseContext(base);
        MultiDex.install(this);
        ....
    }
    ....
}
```

[See this answer](http://stackoverflow.com/questions/15209831/unable-to-execute-dex-method-id-not-in-0-0xffff-65536/26196397#26196397)

**Comment by krunal-panchal** [comment]
Yes, that worked.

**Comment by GreaseMonk** [comment]
I was able to fix the problem just with steps 2 and 3 from kkooff114's answer.
Was looking for a solution to [#2837](https://github.com/realm/realm-java/issues/2837)

**Comment by heinhtetaung92** [comment]
That worked, thanks

**Comment by cbush** [comment]
We are revamping the Realm docs. We're not ignoring this issue -- we've read through every one of them, and we'll be sure to address this as part of our updates. We're closing the GitHub issues and creating new JIRA tickets to track the work at a high level.
