### ISSUE TITLE
New Gson 2.5.0: Do we still need to `setExclusionStrategies`?

### ISSUE THREAD

**Issue by Gryzor** [realm/realm-java#1821]
Hi I have noticed that Gson has moved from 2.3.1 to 2.4.x and now 2.5. I was wondering if we still need to do the GsonBuilder().setExclusionStrategies() thing?

Thanks!

**Comment by cmelchior** [comment]
Hi @Gryzor 
I just tested with GSON 2.5 and you still need to set the exclusion strategy. I updated our example to reflect his as well.

**Comment by Gryzor** [comment]
Thanks!
