### ISSUE TITLE
realm-0.85.1.jar is missing

### ISSUE THREAD

**Issue by skyisle** [realm/realm-java#1822]
Jar file for eclipse installation is missing from 0.85.1 release.

https://static.realm.io/downloads/java/realm-java-0.85.1.zip

![image](https://cloud.githubusercontent.com/assets/71561/11389076/ae86e194-937f-11e5-9082-f49a78021a2b.png)

**Comment by emanuelez** [comment]
Thank you for reporting this! It should now be fixed. Please contact us for any further issue!
