### ISSUE TITLE
Implements Interface in Model

### ISSUE THREAD

**Issue by thanhtranduc** [realm/realm-java#1835]
How to Realm support implement intecface in model, When I using interface build with gradle, Realm model only support setter getter
How to create interface for realm model android?

**Comment by emanuelez** [comment]
Thank you for reporting! This is already being tracked as issue #909 so I will close this issue and let you refer to that issue instead.

**Comment by thanhtranduc** [comment]
In my case:
I have class Car extends RealmObject implements A
{
@orverride
public A a1()
{
//do something
}
}

interface A
{
public A a1();
}
my issue is can not using interface for object that extends realm.
Please tell me detail, I can not see solution in #909

**Comment by emanuelez** [comment]
The fact is that RealmObjects classes cannot include custom methods, which is what you need to implement any non-marker interface. We are working on the issue so right now the only workaround is to use a utility class with static methods

**Comment by thanhtranduc** [comment]
Realm team will supporting impletment interface for Model in the future?
Why team don't support interface for model?

**Comment by emanuelez** [comment]
It's a limitation of the current system, that we are working on overcoming.

**Comment by thanhtranduc** [comment]
My issue base on large project working long time, I want to change from SQLite to realm then facing big changing in code structure database :( thank you so much :+1:
