### ISSUE TITLE
Native RecyclerView addition

### ISSUE THREAD

**Issue by alessandroceron** [realm/realm-java#1837]
I wonder if it will be added a Adapter for android.support.v7.widget.RecyclerView.

Thanks for attention

**Comment by cmelchior** [comment]
Yes, it is definitely something we want to add, but we are waiting for fine-grained notifications #989 to be completed before we can add the proper functionality. It is also being tracked here #972 , so i'll close this as an duplicate.

You might also want to take a look at https://github.com/thorbenprimke/realm-recyclerview
