### ISSUE TITLE
Cant use Migration for Schema Version 2

### ISSUE THREAD

**Issue by defaultbr** [realm/realm-java#1843]
i already did a Migration, now trying to add another field to another table 

PS: if i unistall and run the application install again, it jump the migration and work perfectly the problem is the migration =/

```
if (version == 0) {

            Table categoryT = realm.getTable(Category.class);
            long c1 = categoryT.addColumn(ColumnType.INTEGER, "position");
           

            version++;
        }

        if(version == 1) {
            Table editT = realm.getTable(Edit.class);
            long e1 = editT.addColumn(ColumnType.INTEGER, "position");

            version++;
        }
```

always returns:
 ```Caused by: io.realm.exceptions.RealmMigrationNeededException: Field count does not match - expected 6 but was 7```
                                                 

and my new EditClass(for V2):

from: 
```
private String id;
    private int id;
    private String title;
   ....
```
TO:

```
private String id;
    private int id;
    private String title;
    private int position; //NEW FIELD
```

what can be? 

i saw that next version will probably have a new Migration system and seems to be great

**Comment by defaultbr** [comment]
deleted everything and did a ctrl c + ctrl v from here, change the private int position to the top of the class and it started to work -_-

**Comment by beeender** [comment]
@defaultbr I guess it might be a build problem? Shall we close this issue now?

**Comment by defaultbr** [comment]
yep, can close, thank you ;)
