### ISSUE TITLE
Add new table

### ISSUE THREAD

**Issue by yaming116** [realm/realm-java#1846]
I have a database, now you need to add a new table, how do?

**Comment by zaki50** [comment]
Hi @yaming116 

1. define model classes that extends `RealmObject`.
2. add the classes defined in step 1 to module. If you are using default module, skip this step.
3. configure RealmConfiguration with `deleteRealmIfMigrationNeeded()` if you can remove old database or `migration(RealmMigration)` if you need to migrate old database. If the latter, you also need to define your migration logic. Please see the example migration code https://github.com/realm/realm-java/blob/v0.85.1/examples/migrationExample/src/main/java/io/realm/examples/realmmigrationexample/model/Migration.java#L32 for the detail.

FYI: We will update migration API in the next release. PR is already merged into master https://github.com/realm/realm-java/pull/1496 . If you can wait the next release, I recommend to wait next release.

migration code example for new migration API: https://github.com/realm/realm-java/blob/master/examples/migrationExample/src/main/java/io/realm/examples/realmmigrationexample/model/Migration.java#L32

**Comment by yaming116** [comment]
thx
