### ISSUE TITLE
Cannot compile the examples(jsonexample) in your zip file

### ISSUE THREAD

**Issue by kentcheung2000** [realm/realm-java#1852]
I am new to android studio.  I have got android-sdk-manager and android-command plugin not found.  I tried various solution and couldn't get it work.  Can you update your files?  Thanks.

Kent

**Comment by kneth** [comment]
Please take a look at http://stackoverflow.com/questions/33861009/realm-android-sdk-manager-not-found

**Comment by zaki50** [comment]
Hi @kentcheung2000 

Please remove `examples/local.properties` and try build again?
That file is mistakenly included in the archive.

**Comment by kneth** [comment]
@kentcheung2000 Did the suggestion by @zaki50 solves your problem?

**Comment by kentcheung2000** [comment]
Yes. Thank you very much.  I am able to compile the examples.   
cheers,
Kent 


    On Monday, December 7, 2015 4:31 AM, Kenneth Geisshirt <notifications@github.com> wrote:
 

 @kentcheung2000 Did the suggestion by @zaki50 solves your problem?—
