### ISSUE TITLE
Null Values on Partial Writes

### ISSUE THREAD

**Issue by TheShapGuy** [realm/realm-java#1853]
Updating a RealmObject with PrimaryKey makes all values that have not been rewritten null. 

For Example, lets say I have this Object

```
[{username:shaggy},{userId:null},{linkKarma:240},{commentKarma:37},{gold:false},{inboxCount:0},{accessToken:23372282},{tokenExpiry:3600},{refreshToken:23372282},{subredditObjects:RealmList<SubredditObject>[0]},{multiRedditObjects:RealmList<MultiRedditObject>[0]},{selectedAccount:true}]
```

I want to update the `subredditObjects`.

First of all, I cannot do 

`object.subredditObjects = SomeRealmList()`

throws an exception.

So whats the point of having primary keys if I have to update all the values when writing an object? Just uniqueness? and no data handing? 

Finally, how should I update an Object without having to read, copy all those values into a new realmObject and then update the database? Doesn't this seem cumbersome? If I don't do this right now, it makes all my non updated values `null`?

**Comment by beeender** [comment]
If I understand correctly, you want to update one/some fields only of an RealmObject from JSON?

For example, `username` is your primary key, and you only want to update `userId`, then you can use a JSON lik:

`{{username:shaggy},{userId:123}}` and call `Realm.createOrUpdateObjectFromJson()`. It will ignore those fields which are not in your JSON string and update the `userId` only.

**Comment by TheShapGuy** [comment]
Why is this not the default feature? and `copyToRealmOrUpdate` makes all the other values or not updated values `null`, however `createOrUpdateObjectFromJson` doesn't?

**Comment by beeender** [comment]
These two APIs are different. `createOrUpdateObjectFromJson` takes JSON string/stream as input, which could only have the fields you want to update defined. `copyToRealmOrUpdate` takes a RealmObject or a standalone object as input which you cannot say "although MyModel.name = null, i don't want to update its value to null". Since `null` is also a valid value for Realm.

**Comment by TheShapGuy** [comment]
Would it be great if there is just an `update` method rather than having to be doing this using JSON using the `createOrUpdateObjectFromJson`? Basically right now, updating data is tedious in Realm.

**Comment by beeender** [comment]
@TheShapGuy Why do you thing updating data is `tedious` in Realm? It is actually the simplest part of Realm, just: 
```
realm.beginTransaction();
yourObject.setSomeString("abc");
realm.commitTransaction();
```

**Comment by TheShapGuy** [comment]
Doesn't this make all the non updated values null... this the tedious part.

**Comment by beeender** [comment]
no, it won't. The precondition is `yourObject` here is managed by Realm, not the standalone object.
```
// Here the object is managed by Realm. Not like the object you created by new YourObject();
YourObject yourObject = Realm.where(YouObject.class).equalTo("PK", 1).findFirst();
realm.beginTransaction();
yourObject.setSomeString("abc");
realm.commitTransaction();
```
