### ISSUE TITLE
Realm is so fast, it's breaking my code!

### ISSUE THREAD

**Issue by Saketme** [realm/realm-java#1855]
So there are two components in my app: A conversation list page (Activity) and a conversation page (Fragment). The conversation page is kept hidden initially and only when a conversation is tapped, the messages are fetched and the conversation fragment is shown to the user.

Additionally, if the conversation page is fully hidden, any updates detected in the DB are ignored. No point in showing new messages to the user if the conversation isn't open right?

This system was working perfectly with SQLite. The delay between the call-to-fetch-messages and messages-fetched events used to be so long that the conversation fragment was always ~halfway down its open animation.**

Now, after migrating to Realm, I noticed that the messages weren't being shown. Why? Because it's so freakin' fast that the messages load before the animation is even able to start (1-2ms max). At this point, the conversation thinks it's hidden and so ignores updating the message list :D

(** This also used to create another issue: Updating the UI with new messages used to interfere with the opening animation of the conversation, producing ugly lags. I had to add delays et al to make it look smooth. This is also gone with Realm :D)

Sorry for creating an issue, but this had to be told! But I have a code-boner right now seeing everything happen so fast. Thank you!

**Comment by bmunkholm** [comment]
LOL - that's about the best issue for a long long time if not ever :-) Thx!

**Comment by Saketme** [comment]
Haha :D
