### ISSUE TITLE
Realm will crash ViewPager adapter

### ISSUE THREAD

**Issue by SeanOceanHu** [realm/realm-java#1864]
Hi guys, I'm using realm as the back end data source of a ViewPager, here's the source code of the RealmViewPagerAdapter:

```
public abstract class RealmViewPagerAdapter<T extends RealmObject> extends ViewPagerAdapter {
    protected Context context;
    private RealmResults<T> realmResults;

    public RealmViewPagerAdapter(Context context, RealmResults<T> realmResults) {
        this.context = context;
        this.realmResults = realmResults;

        realmResults.addChangeListener(new RealmChangeListener() {
            @Override
            public void onChange() {
                notifyDataSetChanged();
            }
        });
    }

    @Override
    public int getCount() {
        return realmResults != null ? realmResults.size() : 0;
    }

    public T getItem(int pos) {
        return realmResults.get(pos);
    }

}

```

However when doing Realm transactions in the background threads, ViewPager will throw an exception indicating an error that the adapter's data was changed without calling ```notifyDataSetChanged```. However when working with RecyclerView.Adapter like such things worked well no matter Realm transactions happened in the background threads or the main thread.

Can you guys help resolve this issue ? Is there a better way to bind RealmResults to ViewPager adapter ?

Thanks ~

**Comment by zaki50** [comment]
`RealmResults` holds `RealmChangeListener` as weak reference for now.
That means your `RealmChangeListener` can be gc'ed if your `RealmViewPagerAdapter` does not have strong reference to it.

This behavior will be changed in next release (#1725).

**Comment by SeanOceanHu** [comment]
Hi @zaki50 , thanks~ I'll close this issue now.

**Comment by SeanOceanHu** [comment]
Hi guys,
This problem still exists event if I store a reference to the realmChangeListener in the adapter class, so I'll reopen this issue : )

**Comment by nhachicha** [comment]
Hi @SeanOceanHu 
Could you please try with the latest version, we fixed a bunch of bugs related to `RealmChangeListener`
Cheers

**Comment by SeanOceanHu** [comment]
Hi @nhachicha ,
Just tried with the latest version(0.86.1), Realm works really well with PagerAdapter now : )  

Really awesome work :smile: , thanks ~
