### ISSUE TITLE
How to add collection to the model.

### ISSUE THREAD

**Issue by Dandewine** [realm/realm-java#1865]
I wont to add N items to collection to my model, that already has N items. But when I trying to add, I see my existing collection is null, but RealmProxyClass has data.

I have Runs models which can contain list of Orders.
More details: I have one activity, which has instance of my Run model, it already has N items, then I open new Fragment and display data in adapter, then I open new one Fragment and add how much item I wont to add, press OK, I wont to get from Realm my Run with N Orders, add to it new Orders and save, return to the previous fragment (OnCreateView) get Run instance from Realm with N+N orders.

As I said, when I try to add new items, real my models has nulls and zeros.

In activity I get it from Realm

```
 @Override
    public Run get(long id) {
       return realm.where(Run.class).equalTo("id",id).findFirst();
    }
```
Save Run 
```
 @Override
    public void add(Run run) {
        realm.beginTransaction();
        run.setOrders(run.getOrders());
        realm.copyToRealmOrUpdate(run);
        realm.commitTransaction();
   }
```
Try to add new Orders 
```
private void saveRun(){
        long id = ((PendingRunActivity) getActivity()).getCurrentRun().getId();
        Repository repository = ((BaseRunActivity) getActivity()).getRepository();
        Run run = (Run) repository.get(id);
        repository.addOrdersToRun(run,orderList);
    }


    @Override
    public void addOrdersToRun(Run run, List<Order> list) {
        realm.beginTransaction();
        run.setOrders(list);
        realm.copyToRealmOrUpdate(run);
        realm.commitTransaction();
        add(run);
    }
```
My model Run has two methods setOrders
```
 public void setOrders(RealmList<Order> orders) {
        this.orders = orders;
    }
//Here always I see Log
    public void setOrders(List<Order> newOrders){
        if(orders != null)
            orders.addAll(newOrders);
        else Log.e("myTag", "Orders was null, orders wasn't add");
    }
```
So when I close my AddFragment and return to AdapterFragment I see empty adapter.

**Comment by cmelchior** [comment]
When looking at objects persisted in Realm you cannot trust the IntelliJ debugger as it will show you the values of the fields in the Java heap. Realm is a zero-copy database that saves all its data in native memory instead. This means you will only see the real data if you call the getters on your object.

It is a bit unclear how your program flow is but if you do the following:
```
Run run = new Run();
run.getOrders(); // This would return null

realm.beginTransaction();
Run realmRun = realm.copyToRealm(run);
realm.commitTransaction();
realmRun.getOrders(); // != null
```

As long as you are working on your normal standalone objects (i.e. objects created by you), then we don't do anything, but as soon as you do `copyToRealm` we will return a managed RealmObject where all the data is stored in Realm, this includes `getOrders()` which are now guaranteed to be not-null. This is not the case before you called `copyToRealm`

**Comment by Dandewine** [comment]
Thanks for reply! Yes, I understand it, if I do following:
```
Run run = new Run();

RealmList<Order> list = new RealmList<>();
Order o = new Order();
Order o2 = new Order()
list.add(o);
list.add(o2);
run.setOrders(list);

realm.beginTransaction();
realm.copyToRealmOrUpdate(run);
realm.commitTransaction();
```
I expect Realm save my Run with Orders, and when I write 
```
Run run  = realm.where(Run.class).findFirst();
run.setOrders(getNewOrders()) // on this step I expect for previous 2 orders will be added new 2 orders, but
  in my case orders in model null;
```

```
private List<Order> getNewOrders(){
  Order o1 = new Order();
  Order o2 = new Order();
  return Arrays.asList(o1,o2);
}
```
Maybe I should use ``` run.getOrders().addAll(getNewOrders())  ```instead?

**Comment by kneth** [comment]
The `run.setOrders()` will override the existing list, so `RealmList<Order> list = run.getOrders(); list.add(o1); list.add(o2);` is better to add new objects to the list.

**Comment by Dandewine** [comment]
@kneth Thanks) I mean the same, as I said above I have two setOrders():

```
 public void setOrders(RealmList<Order> orders) {
        this.orders = orders;
    }
//Here always I see Log
    public void setOrders(List<Order> newOrders){
        if(orders != null)
            orders.addAll(newOrders);
        else Log.e("myTag", "Orders was null, orders wasn't add");
    }
```
But it does not matter

**Comment by kneth** [comment]
Maybe you can try `if (getOrders().size() > 0))` instead of `if (orders != null)`. You cannot really use the fields directly - only through setters and getters.
