### ISSUE TITLE
Does it support 23+?

### ISSUE THREAD

**Issue by alin-rosu** [realm/realm-java#1871]
In api 23+ for OS6 you need to put the permission in each activity. I did that, but I use the Realm database everywhere, and was still getting errors that the file that realm is using is not "nullable".
Is this from my part of from your library?

**Comment by kneth** [comment]
Can you post the actually log entry? Using Realm doesn't require any particular permissions.

**Comment by alin-rosu** [comment]
It was from my part. was not giving runtime permissions correctly. my bad
