### ISSUE TITLE
duplicate primary key

### ISSUE THREAD

**Issue by Marchuck** [realm/realm-java#1873]
Hello, I was using realm in Android app, for generating unique primary keys, I am using UUID.randomUUID().toString(). However, I have found duplicate keys!

retrofit.RetrofitError: Primary key constraint broken. Value already exists:

FYI its not a bug, I only want to show that this danger not only exists in theory.

**Comment by kneth** [comment]
The probability of collision is very low, and it is surprising that you see collisions (see https://docs.oracle.com/javase/7/docs/api/java/util/UUID.html#randomUUID()). Is it possible to change the code where you create the objects with primary keys?

**Comment by Marchuck** [comment]
yes, I've fixed the code, now I try{}  to insert  new record to table while (random)UUID keeps the same. Thx for link.
