### ISSUE TITLE
Use a consistent pattern for test involving Handler

### ISSUE THREAD

**Issue by nhachicha** [realm/realm-java#1874]
as discussed here 
https://github.com/realm/realm-java/pull/1809#discussion_r46361970

**Comment by cmelchior** [comment]
@nhachicha Hasn't this been resolved with the introduction of `@RunTestInLooperThread` and `TestRealmConfigurationFactory` ? Unit tests are being converted as we reach them, but I don't think we need a issue to track it?

**Comment by cmelchior** [comment]
With the introduction of `@RunTestInLooperThread`, `TestRealmConfigurationFactory` and `ExceptionHolder`, we should have the tools for making much more readable unit tests involving the Handler.

Closing this.
