### ISSUE TITLE
UnsupportedOperationException in RealmBaseAdapter

### ISSUE THREAD

**Issue by roughboy** [realm/realm-java#1875]
I get such exception after I guess last change regarding notifications (0.86.0-SNAPSHOT):

`Caused by: java.lang.UnsupportedOperationException`
`		at java.util.concurrent.CopyOnWriteArrayList$CowIterator.remove(CopyOnWriteArrayList.java:744)`
`		at io.realm.HandlerController.addChangeListenerAsWeakReference(HandlerController.java:145)`
`		at io.realm.RealmBaseAdapter.<init>(RealmBaseAdapter.java:56)`
`		at com.borg.forza.adapters.RealmModelAdapter.<init>(RealmModelAdapter.java:0)`

Seems like CopyOnWriteArrayList iterator does not support remove operation.

**Comment by cmelchior** [comment]
Thanks for reporting this. We are working on a fix now.
