### ISSUE TITLE
Table getInt(long columnIndex, long rowIndex) function

### ISSUE THREAD

**Issue by NikoYuwono** [realm/realm-java#1876]
I checked Table class and I can't found getInt(long columnIndex, long rowIndex), is there any other way to get value with ColumnType INTEGER from Table class?

Thanks

**Comment by beeender** [comment]
byte, short, int, long are all stored as `long` in the Realm's underlying engine.
So, just use `Table.getLong()`

BTW, I suggest you to use our Dynamic API instead which will be released very soon.
Direct access to `Table` will be deprecated later.

**Comment by NikoYuwono** [comment]
Hmmm that's what I thought before. I tried Table.getLong() but it throw me exception

```
D/REALM: Expected columnType 0, but got 2.
D/REALM: jni: ThrowingException 3, ColumnType invalid., .
D/REALM: Exception has been throw: Illegal Argument: ColumnType invalid.
```

Thanks for the suggestion! Any reference for starting point?

**Comment by beeender** [comment]
`columnType` 2 is `String`, please check the column index you passed in.

The Dynamic API has been merged into the master, you can start with the SNAPSHOT now. The doc will be released when the `0.86.0` gets released. Maybe just following our tweet/news to be notified when the release happens?

**Comment by NikoYuwono** [comment]
Currently reading [this](https://github.com/realm/realm-java/pull/1265). While waiting for the release I'll use that as temporary reference. Thanks for the help @beeender !

**Comment by beeender** [comment]
@NikoYuwono Reminder service from Realm Robot beeender, the 0.86.0 is released with Dynamic API support. See the blog post https://realm.io/news/realm-java-0.86.0/ and the document update https://realm.io/docs/java/latest/#dynamic-realms . Also the Japanese blog post is available as well : https://realm.io/jp/news/realm-java-0.86.0/ .

Have fun!

**Comment by NikoYuwono** [comment]
Thank you! Will try to change the table with dynamic realms then!
