### ISSUE TITLE
ChangeListener not triggered on newly created RealmObject

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#1884]
```
realm.beginTransaction();
Person p = realm.createObject(Person.class);
realm.commitTransaction();

p.addChangeListener(() -> { Log.i("Debug", "Hello") });

realm.beginTransaction();
p.setAge(50);
realm.commitTransaction(); // Doesn't trigger change listener.
```

ChangeListeners are correctly triggered on objects created using `RealmQuery.findFirst()` but not when using `Realm.createObject()`

RealmQuery has the following code:
```
if (realm.handlerController != null) { // non Looper Thread doesn't have a handlerController
    WeakReference<RealmObject> realmObjectWeakReference
            = new WeakReference<RealmObject>(realmObject, realm.handlerController.referenceQueueRealmObject);
    realm.handlerController.realmObjects.put(realmObjectWeakReference, this);
}
```

Which is not present in `addChangeListener` for `RealmObject`

**Comment by nhachicha** [comment]
I suppose we need to add 
* `copyOrUpdate`
* `createAllFromJson`
* `createObjectFromJson`
* `createOrUpdateAllFromJson`
* `createOrUpdateObjectFromJson`

as well

**Comment by cmelchior** [comment]
Fixed by https://github.com/realm/realm-java/pull/1892
