### ISSUE TITLE
Crash: Fatal Signal 11 after running same query on a large database

### ISSUE THREAD

**Issue by vikas-fueled** [realm/realm-java#1887]
I started getting sporadic crashes at times in realm when i changed from small test database to large production database. I could narrow it down to calling same async query 2-3 times. My scenario is I have a ViewPager with different fragments showing data from same table with different conditions(sorting order).

So to reproduce it I did following
```
Realm defaultRealm = Realm.getDefaultInstance();
RealmResults<Content> realmResults = defaultRealm .where(Content.class).equalTo("contentParts.active", true).greaterThan("bestOf", 0).findAllSortedAsync("bestOf", false);
realmResults.addChangeListener(iistenerA);

Realm duplicateRealm= Realm.getDefaultInstance();
RealmResults<Content> realmResults2 = duplicateRealm.where(Content.class).equalTo("contentParts.active", true).greaterThan("bestOf", 0).findAllSortedAsync("bestOf", false);
realmResults2.addChangeListener(iistenerB);
```

My realm file is around 2.5MB,
tested on  v 0.84.1 and 0.85.1
device for logs: Nexus 5 running M Preview 3(tested on other devices as well)

[crash log 1.txt](https://github.com/realm/realm-java/files/51725/crash.log.1.txt)
[crash log 2.txt](https://github.com/realm/realm-java/files/51726/crash.log.2.txt)

This issue might be realted to these two issues
https://github.com/realm/realm-java/issues/1851
and https://github.com/realm/realm-java/issues/1645

**Comment by kneth** [comment]
@vikas-fueled From your description, it sounds very much like #1851.

**Comment by beeender** [comment]
@vikas-fueled I think this issue should be fixed in 0.86.1. Have you met this issue recently with the latest Realm release?

**Comment by bmunkholm** [comment]
@vikas-fueled : Could you please verify if this has been fixed?

**Comment by vikas-fueled** [comment]
@bmunkholm @beeender yes this is now fixed. Sorry for late reply.

**Comment by beeender** [comment]
@vikas-fueled Thanks a lot for the reply. Now we can close this issue :)
