### ISSUE TITLE
Getting quite a lot of IllegalStateExceptions (Illegal State: Object is no longer valid to operate on)

### ISSUE THREAD

**Issue by Saketme** [realm/realm-java#1890]
We're getting a few reports of this exception everyday:

    FATAL EXCEPTION: main
                  Process: in.cleartax.taxcloud.dev, PID: 32716
                  java.lang.IllegalStateException: Illegal State: Object is no longer valid to operate on. Was it deleted by another thread?
                      at io.realm.internal.UncheckedRow.nativeGetLong(Native Method)
                      at io.realm.internal.UncheckedRow.getLong(UncheckedRow.java:122)
                      at io.realm.EntityItemRealmProxy.getEntityId(EntityItemRealmProxy.java:108)
                      at in.cleartax.ui.Dashboard.EntityProfileFragment.loadContent(EntityProfileFragment.java:297)
                      at in.cleartax.ui.Dashboard.DashboardActivity$1.onExpandableItemClick(DashboardActivity.java:253)

I'm unable to understand this because I'm already checking `RealmObject.isValid` before showing a new page with its details.

The only hint I have is that this happens while the app is syncing data with the server and the list of RealmObjects might be getting updated right when the user is clicking the item.

How does this auto-update functionality of `RealmResults` internally work? Are you clearing existing Objects and replacing them with new ones? That might be error prone.

**Comment by Saketme** [comment]
Update: The problem might be somewhere else. Here's the `EntityProfileFragment.loadContent` part where this crash is occurring: 

    void loadContent(@NonNull EntityItem newEntity) {

        // Avoid doing extra work if it's the same entity
        if (mOldEntityDetails != null && mOldEntityDetails.getEntityId() == newEntity.getEntityId()) {

            ....
            return;

        }

        ....

    }

So I'm not sure if the crash happened on an existing cached RealmObject, `mOldEntityDetails` or the newly received `newEntity`. Does the old invalid RealmObject become invalid for a short duration when the DB gets updated?

**Comment by cmelchior** [comment]
No, RealmObjects only become invalid if you closed the Realm or the object was deleted. If you are not actively deleting objects, it sounds like you are closing your Realm instance to early?

As all Realm data is lazy-loaded the Realm has to be open for as long as you want to access data in the RealmObjects.

**Comment by Saketme** [comment]
I'm only closing Realm in `onDestroy` of my Activity, so that doesn't make sense. And I'm nowhere deleting items in this project either.

**Comment by cmelchior** [comment]
Our update doesn't really delete anything. We only refresh RealmObjects with a Looper event, so that shouldn't be the problem.

Are you perhaps accessing a object that came from a background thread. If the Realm on the background thread was closed you would see the error you are getting instead of our standard Thread exception

**Comment by Saketme** [comment]
> Are you perhaps accessing a object that came from a background thread

Wouldn't that instead throw a different error that I cannot use RealmObjects across threads?

**Comment by cmelchior** [comment]
It would, but not if the Realm on the other thread was closed first. We check for that before checking for the correct thread

**Comment by zaki50** [comment]
@Saketme Are you using async query?

**Comment by Saketme** [comment]
Okay, let me explain the setup. There are 3 components here:

1. List of items (`RecyclerView` with a Realm based adapter)
2. Item details page.
3. Sync service (Downloads new items from the server and stores them locally)

All these access Realm on the main thread and none of them were using `executeAsync` (which I just found out and fixed because writing on the UI thread would block other stuff)

The Sync service requests delta updates from the server, compares them with the local data and stores new items to DB.

The item list's adapter gets notified and calls `notifyDataSetChanged`. That's it.

Any ideas?

**Comment by cmelchior** [comment]
`mOldEntityDetails.getEntityId() == newEntity.getEntityId()`

What is the old and new? I assume the newEntity hasn't be saved in Realm yet, but the old has?

**Comment by Saketme** [comment]
No, in this context, the old `Entity` is the one whose details are currently visible in the fragment and new `Entity` is the newly selected item from the entity list. In this line, I'm ignoring load requests if the user chose the same entity again.

Imagine a list of `Entity` items and a fragment that displays the details of an `Entity`.

**Comment by cmelchior** [comment]
Ok, that sounds like it should work. Where is mOldEntityDetails stored and how is it refreshed? I can a possible bug with it:

1) If it is stored in a class field
2) App is put in the background -> All activities have `onDestroyed` called, but Activity is not GC'ed
3) App is reopened, see that `mOldEntityDetails` still contain data and doesn't reload it.
4) Reading from `mOldEntityDetails` will now crash.

**Comment by Saketme** [comment]
Yes, it's stored as a class field. Losing data once the Activity gets destroyed does sound like a probable bug. What's the best way to solve this? Reload the data if becomes invalid in `onResume()`?

**Comment by cmelchior** [comment]
Yes, you need to reload the data in either `onCreate` or `onResume`.

**Comment by Saketme** [comment]
Will try this, thanks. Closing this issue until then.

**Comment by dinhthaidaica** [comment]
Hi @cmelchior , could you help to verify this issue again? I'm facing this issue and I don't know why.
Below is my implementation:
`Realm realm = getMyRealm();
            currentDb = hash + ".realm";
            RDatabase results = realm.where(RDatabase.class)
                    .equalTo("fileName", currentDb)
                    .findFirst();
            if (results == null || !results.isValid()) {
                return;
            }
            
            realm.beginTransaction();
            results.setLastLogin(System.currentTimeMillis());
            String basicString = new Gson().toJson(bi);
            results.setBasicInfoString(basicString);
            realm.copyToRealmOrUpdate(results);
            realm.commitTransaction();
            realm.close();`

And sometimes I got exception 

> java.lang.IllegalStateException: Illegal State: Object is no longer valid to operate on. Was it deleted by another thread?
                                                                              at io.realm.internal.UncheckedRow.nativeGetIndex(Native Method)
                                                                              at io.realm.internal.UncheckedRow.getIndex(UncheckedRow.java:123)
                                                                              at io.realm.internal.UncheckedRow.setLong(UncheckedRow.java:192)

Log pointed that exception occur in line `results.setLastLogin(System.currentTimeMillis());`

**Comment by shahid650** [comment]
Answer: 
I got these errors , and While the solution was simple.
1- java.lang.IllegalStateException: Object is no longer managed by Realm. Has it been deleted?
2-  ThrowingException 8, Object is no longer valid to operate on. Was it deleted by another thread?, .
11-19 00:19:02.146 21759-21932/zeroturnaround.org.jrebel4androidgettingstarted E/REALM_JNI: Exception has been throw: Object is no longer valid to operate on. Was it deleted by another thread?

The Bad Code:
  if (subServiceId != null && !subServiceId.isEmpty()) {
                    mSubServiceModelDelete.setDeleted(true);
                    realm.copyToRealmOrUpdate(mSubServiceModelDelete);
                } else {

                    mSubServiceModelDelete.deleteFromRealm();
                    Log.d("TAG", "Service is Deleted from database.." + mSubServiceModelDelete.getSubservicesSubservicename());
                }

The Good and Error Free Code: 
  if (subServiceId != null && !subServiceId.isEmpty()) {
                    mSubServiceModelDelete.setDeleted(true);
                    realm.copyToRealmOrUpdate(mSubServiceModelDelete);
                } else {
                    Log.d("TAG", "Service is Deleted from database.." + mSubServiceModelDelete.getSubservicesSubservicename());
                    mSubServiceModelDelete.deleteFromRealm();
                }



So that was the Solution For This Error, This Was Error, as i was accessing deleted object after deleting it. LOL
Happy Coding :) :)
