### ISSUE TITLE
java.lang.IllegalStateException: Realm access from incorrect thread. Realm objects can only be accessed on the thread they were created.

### ISSUE THREAD

**Issue by hunain-liaquat** [realm/realm-java#1891]
Hi,

I am using realm for offline storage when there is no internet connectivity.
I am loading data from local database in case of no internet access only. but when there is internet access available I am requesting a service call to get data from server.

I am getting an exception when I am requesting data from server through a service call and parsing json through **GSON**  . and when calling ```  task.getTaskType(); ``` in list adapter, my application is crashing and below is the exception.

**java.lang.IllegalStateException: Realm access from incorrect thread. Realm objects can only be accessed on the thread they were created.**

I have a model Task in my application which extends RealmObject and it have following field TaskType type which is also a RealmObject.
```
@SerializedName("event_type")
    @Expose
    private TaskType type;
```

Even I have observed that Task Objects are not TaskRealmPrxoy objects when getting data from server and parsing using gson then why this exception is occuring.

**Comment by Saketme** [comment]
You need to do exactly what the stacktrace suggests, do not pass the Realm objects across threads, until this becomes supported :)

**Comment by hunain-liaquat** [comment]
But its not a realm object as I have parsed service response using GSON and passed the list to adapter and also to save in local database

**Comment by cmelchior** [comment]
@hunain-liaquat Can you show us the code where you are using Realm/GSON. From your description it is hard to tell where you are accessing Realm from the wrong thread?

**Comment by hunain-liaquat** [comment]
I have figured out what was the issue, I was passing the parsed list to adapter and also to realm to save in local database. and there I was getting local task type object and setting to task before saving list and it was changing parsed taskType object with realm taskType object :)

**Comment by kneth** [comment]
Great to hear!
