### ISSUE TITLE
Your Realm is opened from a thread without a Looper. Async queries need a Handler to send results of your query

### ISSUE THREAD

**Issue by diskzzokejs** [realm/realm-java#1896]
Hi, again. I'm new at android coding and realm also. I can't find really simple and good explanation, how to avoid this error message ```  Your Realm is opened from a thread without a Looper. Async queries need a Handler to send results of your query ```

Can someone please, provide me simple code example or explanation?

**Comment by beeender** [comment]
Check http://developer.android.com/reference/android/os/Handler.html and http://developer.android.com/reference/android/os/Looper.html .

Basically Realm need a way to communicate with your thread when doing asyc query, on Android, naturally Looper and Handler is the way to go.

Check this for more sample code.
https://github.com/realm/realm-java/tree/master/examples/threadExample

**Comment by cmelchior** [comment]
Also, if you are on a thread without a looper it means you are on a background thread, in which case you don't get much benefit out of doing asynchronous queries or writes.

**Comment by diskzzokejs** [comment]
@cmelchior, so I should not use asynchronous queries or writes in AsyncTask? 

@beeender I will try to explain my situation. While I'm doing realm query, application have black screen while processing data. So, I'm trying to avoid it. 

1. I have two realm objects. One for Channels and other for Channel events.
2. I have two queries, first to find all Channels in Channels DB object and other query is for Channel events. (see ``` class Task ``` at the bottom) 

Things I tried:

- [x] 1. I tried to run realm queries in background task, but I got message: ``` Your Realm is opened from a thread without a Looper. Async queries need a Handler to send results of your query ```
- [x] 2.1 I tied to use ``` RealmChangeListener  ``` It didn't help me to avoid black screen on application launch.
- [x] 3.1 Last thing is  ```Runnable``` (see below)


Code Example:

```    
 private RealmResults<TvObject> tvChannels;
 private RealmResults<ProgramObject> tvGuide;


@Override
protected void onCreate(Bundle savedInstanceState) {

 super.onCreate(savedInstanceState);
 setContentView(R.layout.activity_main);

new Thread(new Task()).start();

 private void updateEPG() {

        HashMap<EPGChannel, List<EPGEvent>> first = Maps.newLinkedHashMap();

        for(TvObject item : tvChannels) {
            EPGChannel epgChannel = new EPGChannel(RLinks.APP_DOMAIN + item.getLogo(),
                    "Kanāls " + item.getXprs_id(), item.getXprs_id() + "");

            first.put(epgChannel, createEvents(item.getXprs_id()));

        }

        epg = (EPG) findViewById(R.id.epg);
        epg.setEPGClickListener(new EPGClickListener() {
            @Override
            public void onChannelClicked(int channelPosition, EPGChannel epgChannel) {
                Toast.makeText(MainActivity.this, epgChannel.getName() + "", Toast.LENGTH_SHORT).show();
            }

            @Override
            public void onEventClicked(int channelPosition, int programPosition, EPGEvent epgEvent) {
                Toast.makeText(MainActivity.this, epgEvent.getTitle() + "", Toast.LENGTH_SHORT).show();
            }

            @Override
            public void onResetButtonClicked() {
                epg.recalculateAndRedraw(true);
            }
        });

        if (first != null) {
                 EPGData epgData = new EPGDataImpl(first);
                 epg.setEPGData(epgData);
                 epg.recalculateAndRedraw(false);
        }

    }


private List<EPGEvent> createEvents(int channelNumber) {

        RealmResults<ProgramObject> tvp = tvGuide.where().equalTo("channel_id", channelNumber).findAll();
        List<EPGEvent> result = Lists.newArrayList();

        for(ProgramObject item : tvp) {
            long epgStart = item.getTime_start_unix() * 1000L;
            long epgEnd = item.getTime_stop_unix() * 1000L;
            long epgDuration = epgEnd - epgStart;
            long currentTime = epgStart;

            if (currentTime <= epgEnd) {

                long eventEnd = getEventEnd(currentTime, epgDuration);
                EPGEvent epgEvent = new EPGEvent(currentTime, epgEnd, item.getTitle(), getEventTimeFromTo(item.getTime_start(), item.getTime_stop()));
                result.add(epgEvent);
                currentTime = eventEnd;
            }
        }

        return result;
    }

```

EPGChannel and EPGEvent classes:

```
public class EPGChannel {

    private final String channelID;
    private final String name;
    private final String imageURL;

    public EPGChannel(String imageURL, String name, String channelID) {
        this.imageURL = imageURL;
        this.name = name;
        this.channelID = channelID;
    }

    public String getChannelID() {
        return channelID;
    }

    public String getName() {
        return name;
    }

    public String getImageURL() {
        return imageURL;
    }
}

```
```
public class EPGEvent {

    private final long start;
    private final long end;
    private final String title;
    private final String timeFromTo;

    public EPGEvent(long start, long end, String title, String timeFromTo) {
        this.start = start;
        this.end = end;
        this.title = title;
        this.timeFromTo = timeFromTo;
    }

    public long getStart() {
        return start;
    }
    public String getTimeFromTo() {
        return timeFromTo;
    }

    public long getEnd() {
        return end;
    }

    public String getTitle() {
        return title;
    }

    public boolean isFuture() {
        long now = System.currentTimeMillis();
        return now <= start && now <= end;
    }

    public boolean isPast() {
        long now = System.currentTimeMillis();
        return now >= start && now >= end;
    }

    public boolean isCurrent() {
        long now = System.currentTimeMillis();
        return now >= start && now <= end;
    }
}

```

Task Class:

```
class Task implements Runnable {
        @Override
        public void run() {

            handler.post(new Runnable() {
                @Override
                public void run() {
                    // EPG -->

                    tvChannels = app.getDatabase().where(TvObject.class).findAll(); //.equalTo("id", 101)
                    Log.e("runn", tvChannels+"");
                    if (tvChannels.size() > 0) {
                        tvGuide = app.getDatabase().where(ProgramObject.class).findAll();
                        Log.e("runn", tvGuide+"");
                        if (tvGuide.size() > 0) {
                            updateEPG();

                            }
                        }
                    }
                });
            }
        }

```

**Comment by diskzzokejs** [comment]
Basically I need help to avoid black screen, while working with big amount of data.

**Comment by beeender** [comment]
@diskzzokejs You just need:
```
RealmChangeListener listener = new RealmChangeListener() {
     // Do your UI updates here. The query will be running in another thread, but this function will be running int the caller thread, in your case, the UI thread.
};
final RealmResults<AllTypes> realmResults1 = realm.where(AllTypes.class)
                            .findAllAsync();
realmResults1.addChangeListener(listener);
```

PS. Normally Realm query is super fast, i doubt you might have some other thing is blocking the UI thread.

**Comment by cmelchior** [comment]
@diskzzokejs You should not be using a worker thread like your Task class. Instead as @beeender suggest, using `findAllAsync` as it will automatically do the query outside the UI thread for you . 

In your current Task class you also use `handler.post` what will execute everything inside that handler on the UI thread.

Something like this should work instead

```

tvChannels = app.getDatabase().where(TvObject.class).findAll(); //.equalTo("id", 101)
tvChannels.addChangeListener(new RealmChangeListener() {
  public void onChange() {
	Log.e("runn", tvChannels+"");
	if (tvChannels.size() > 0) {
	    tvGuide = app.getDatabase().where(ProgramObject.class).findAllAsync();
	    tvGuide.addChangeListener(new RealmChangeListener() {
	    	public void onChange() {
			    Log.e("runn", tvGuide+"");
			    if (tvGuide.size() > 0) {
	        		updateEPG();
	        	}	
		    }    	
	    });
	}
  }	
});
```

**Comment by diskzzokejs** [comment]
@beeender maybe problem is in:

First method: updateEPG()
```
HashMap<EPGChannel, List<EPGEvent>> first = Maps.newLinkedHashMap();
 for(TvObject item : tvChannels) {
EPGChannel epgChannel = new EPGChannel(RLinks.APP_DOMAIN + item.getLogo(),
                    "Channel " + item.getXprs_id(), item.getXprs_id() + "");

first.put(epgChannel, createEvents(item.getXprs_id()));
result.add(epgEvent);
}
```

Second method: private List<EPGEvent> createEvents(int channelNumber)
```
for(ProgramObject item : tvp) {
List<EPGEvent> result = Lists.newArrayList();
EPGEvent epgEvent = new EPGEvent(currentTime, epgEnd, item.getTitle(), getEventTimeFromTo(item.getTime_start(), item.getTime_stop()));
                result.add(epgEvent);
}
```
I'm creating linked HashMaps, to link results together. Maybe this process causes black screen?

**Comment by diskzzokejs** [comment]
@cmelchior I will try Your suggestion.

**Comment by diskzzokejs** [comment]
@cmelchior Your suggestion worked fine, byt: 

1. ``` tvChannels = app.getDatabase().where(TvObject.class).findAllAsync(); ``` works instantly but other query: ``` tvGuide = app.getDatabase().where(ProgramObject.class).findAllAsync(); ``` takes ~ 5 sec. Okey, there is at least 10K + records. 

And displaying results set, takes ~ 7 seconds. 

So, I think problem maybe is in ``` newLinkedHashMap() ``` Read post I mentioned before, to @beeender 

Is there any way I can link realm results together without using/creating linked HashMap?

**Comment by beeender** [comment]
@diskzzokejs As i can see from your source code, everything in the hashmap can be computed based on the `TvObject`, why do you even need it?
You can just compute the values when you want to display them.

**Comment by diskzzokejs** [comment]
@beeender problem is, that I dont know how to do it with realm. :D 
I have data implementation class, who works with HashMap
```
public class EPGDataImpl implements EPGData {

    private List<EPGChannel> channels = Lists.newArrayList();
    private List<List<EPGEvent>> events = Lists.newArrayList();

    public EPGDataImpl(Map<EPGChannel, List<EPGEvent>> data) {
        channels = Lists.newArrayList(data.keySet());
        events = Lists.newArrayList(data.values());
    }

    public EPGChannel getChannel(int position) {
        return channels.get(position);
    }

    public List<EPGEvent> getEvents(int channelPosition) {
        return events.get(channelPosition);
    }

    public EPGEvent getEvent(int channelPosition, int programPosition) {
        return events.get(channelPosition).get(programPosition);
    }

    public int getChannelCount() {
        return channels.size();
    }

    @Override
    public boolean hasData() {
        return !channels.isEmpty();
    }
}
```
But thank You guys for helping me out with black screen problem. 
How to avoid ```HashMap```, I will try, to figure it out by myself :)

**Comment by kneth** [comment]
@diskzzokejs Sounds like it ok to close the issue. Don't hesitate to reopen or create a few issue if you still experience the issue.

**Comment by diskzzokejs** [comment]
@kneth thank You :)

**Comment by jemshit** [comment]
What if i have to call `realm.executeTransactionAsync()` in background thread, because my function needs to be in background thread, and this realm query code also exists in that function

**Comment by Zhuinden** [comment]
You could just use `realm.executeTransaction()` on background thread?

**Comment by jemshit** [comment]
@Zhuinden It will be blocking right? I mean next line will be called after this `realm.executeTransaction()` is executed even it takes few seconds?

**Comment by Zhuinden** [comment]
Yes, it is blocking on the **background thread**, but that doesn't seem like a problem on a background thread?

Otherwise you'll need to [create a looper thread](https://realm.io/docs/java/latest/#closing-realm-instances).

**Comment by jemshit** [comment]
yeah, i want realm query to be executed, then next line to be executed

**Comment by Zhuinden** [comment]
In that case, look into how to use a [HandlerThread](https://developer.android.com/reference/android/os/HandlerThread.html)

**Comment by xuie0000** [comment]
new Handler(Looper.getMainLooper()).post(() ->  Realm.getDefaultInstance....

**Comment by Zhuinden** [comment]
@xuie0000 typically if you follow [https://realm.io/docs/java/latest/#controlling-the-lifecycle-of-realm-instances](https://realm.io/docs/java/latest/#controlling-the-lifecycle-of-realm-instances) then you typically don't need to do a thread-jump to the main thread in order to execute an operation.

Use the synchronous methods on background threads.

**Comment by Sottti** [comment]
I don't understand what @cmelchior meant here:

> Also, if you are on a thread without a looper it means you are on a background thread, in which case you don't get much benefit out of doing asynchronous queries or writes.

The main benefit from async queries is not blocking the calling thread, **whatever that is**. Obviously not blocking the main thread is essential in an Android app, but it doesn't mean that whenever in a background thread there are not reasons for not wanting to block it.

```
getUser() {
    getUserFromRealm();
    getUserFromAPI();
}
```

Now, I'm debugging an example where a query to Realm takes a few seconds in an old device (Galaxy S3). I don't want that query to be blocking because the chances are my API query is faster (!!) so having both async queries running at the same time makes sense.

All of this code runs in the data layer inside a Repository (pattern) so all of it happens on background threads, and indeed that's the reason it's not convenient.

**Comment by Zhuinden** [comment]
Nah, the intended usage is that if you have the data in the local storage, you retrieve it from the local storage, and if you also end up updating said data then it should "immediately" reflect once new data is downloaded and the data is updated (written to disk).

Realm won't be able to do a callback to your current thread if it doesn't have a Looper, so async query is nice except a normal background thread can die by the time it's done, and there is no way to send callback to it.
