### ISSUE TITLE
RealmObject is not part of the schema for this Realm

### ISSUE THREAD

**Issue by StefanoGR** [realm/realm-java#1899]
Hello,
My team has been using REALM on my apps from 1 year and it works really really well. We are satisfied on all levels.

From yesterday, one of our apps crashes after a project clean. A realmobject is not found anymore in the schema and we don't know why. I have tried to clean, rebuild, delete bin-gen files, but is not working. We actually working on 0.8.2 and for now we have no plans to update to the latest version. Is this a bug of 0.8.2 or what?

Thank you for the support, here the changelog:

> 12-07 10:12:08.724: E/AndroidRuntime(3920): java.lang.IllegalArgumentException: UserModel is not part of the schema for this Realm
12-07 10:12:08.724: E/AndroidRuntime(3920): 	at io.realm.internal.modules.CompositeMediator.getMediator(CompositeMediator.java:118)
12-07 10:12:08.724: E/AndroidRuntime(3920): 	at io.realm.internal.modules.CompositeMediator.getTableName(CompositeMediator.java:71)
12-07 10:12:08.724: E/AndroidRuntime(3920): 	at io.realm.Realm.getTable(Realm.java:317)
12-07 10:12:08.724: E/AndroidRuntime(3920): 	at io.realm.Realm.checkHasPrimaryKey(Realm.java:1589)
12-07 10:12:08.724: E/AndroidRuntime(3920): 	at io.realm.Realm.copyToRealmOrUpdate(Realm.java:1139)

**Comment by kneth** [comment]
We did fix a bug in `copyToRealmOrUpdate()` in version 0.80.3.

**Comment by StefanoGR** [comment]
I have double checked, the version the app is running is realm-0.82.0.jar
The strange thing is that 2 days ago the project was working 100% we only cleaned it.

**Comment by kneth** [comment]
Sorry, I misunderstood which version, you are using.

Did you add the class `UserModel` recently? And can you share how you set up your `RealmModule` and `RealmConfiguration`?

**Comment by StefanoGR** [comment]
Hi Kneth, the problem was with a conflicted copy created by the svn tool. The file was "DefaultRealmModuleMediator.java". With two copies we had that error. I have removed the file and now everything works. My bad, but maybe it's a specific case that you have never encountered.

**Comment by kneth** [comment]
@StefanoGR I happy to hear that you solved the issue.

**Comment by cmelchior** [comment]
Hi @StefanoGR You only get two `DefaultRealmModuleMediator` classes if a library you depended on isn't configured properly. You can read more about it in our documentation: https://realm.io/docs/java/latest/#sharing-schemas

**Comment by alin-rosu** [comment]
@StefanoGR I get the same issue on my UserRecord class. And this was working perfectly until 2 days. Where did you find the conflicting file?

**Comment by kneth** [comment]
Try to do `find . -name DefaultRealmModuleMediator.java` in the root of your app.
