### ISSUE TITLE
setObject and getObject not working as expected in Migration

### ISSUE THREAD

**Issue by rimeissner** [realm/realm-java#1912]
In my migration I create a new field (which has the same field as an old field, therefore with the "_tmp" field) and I want to put in set on the new object a field that was before on the old object.

I think some example code is clearer:

``` 
schema.get("Test")
    .addRealmObjectField("field_tmp", newSchema)
    .transform(new RealmObjectSchema.Function() {
        @Override
        public void apply(DynamicRealmObject object) {
            DynamicRealmObject newInstance = realm.createObject("NewObject");
            newInstance.setObject("user", object.getObject("user"));
            object.setObject("field_tmp", newInstance);
        }
    })
    .removeField("user")
    .removeField("field")
    .renameField("field_tmp", "field");
```

When I try to execute that in my migration I get the following error:
```
java.lang.IllegalArgumentException: Type of object is wrong. Was class_Test, expected class_NewObject
```

Can you help me with that?

**Comment by cmelchior** [comment]
Can you post the RealmObject class for NewObject?

**Comment by rimeissner** [comment]
The NewObject class looks like this:
```
public class NewObject extends RealmObject 
    @Required
    private String id;
    private long createdAt;
    private User user;

 /* Getter & Setter */
}
```

The User class looks like this:
````
public class User extends RealmObject {
    @Required
    private String lastName;
    @Required
    private String firstName;
}
```

When I debug the migration and execute `object.getObject("user")` and use `hasField("lastName")` it returns false, but when I try `hasField("field")` it returns true.

Also when I check the type of the DynamicRealmObject that I retrieved with `getObject("user")` with `getType()` it doesn't return `User`, but `Test`

**Comment by cmelchior** [comment]
Hmm, that sounds like a bug. I'll look into it.

**Comment by rimeissner** [comment]
thanks

**Comment by rimeissner** [comment]
Thank you for fixing the problem this fast :D 

Do you think that you release 0.86.1 public until tomorrow? or can I grab it from the snapshot server?

**Comment by cmelchior** [comment]
Right now we plan to release 0.86.1 either today or tomorrow. I just merged the fix to master as well, so in 15 minutes-ish, it should be available in our `0.87.0-SNAPSHOT` as well

**Comment by benjamincombes** [comment]
Thanks for this bug fix, I have the problem too, and for your great work on Realm! Do you still plan to release 0.86.1 today?

**Comment by cmelchior** [comment]
@benjamincombes Sorry for the delay. 0.86.1 should be released now.

**Comment by benjamincombes** [comment]
Thanks a lot for your feedback & the release (and for your great work with Realm!), I just saw that, I'll update my app right now!
