### ISSUE TITLE
isValid tricky naming

### ISSUE THREAD

**Issue by Marchuck** [realm/realm-java#1921]
Hello, I've recently noticed that inside RealmObject class exists boolean field isValid! Thats tricky for new developers with limited naming, because isValid is in common use:

private boolean isValid;

produces:

@Override public boolean isValid(){...}

Refactor this variable would be appreciated :)

**Comment by kneth** [comment]
#909 (custom objects and own methods) is being worked on. With that, you can easily choose your own method names. For the time being, we don't see the urge of refactoring.
