### ISSUE TITLE
How to Import and Export RelationShip as JSON?

### ISSUE THREAD

**Issue by defaultbr** [realm/realm-java#1924]
i mean:

if i have a Product Object that has a Field Called Owner and its a relationship in Realm database, how can i export this to a external mysql database as backup and/or import something that has a relationship at the Mysql database(get it as json) and load?

im stuck at this, is this possible or i need another solution?

Other solution i thougth if i need to share the database from employee 1 to  other employee

copy default.realm from source and than load at the destination (manually or using some kind of web host for sincronization, but copying all the database not exporting as json)

**Comment by kneth** [comment]
The `toString()` will not recursively follow relationships (with cyclic data structure will end up in an infinite loop). Best option is to write a method to export your data:

    StringBuilder out = new StringBuilder("[");
    for (Product product : realm.allObjects(Product.class)) {
        out.append("{");
        out.append("[");
        for (Owner owner : product.getOwners()) {
           out.append("{name: ");
           out.append(owner.getName());
           out.append("},");
       }
       out.append("]");
       out.append("}");
    }

**Comment by defaultbr** [comment]
@kneth  but i cant import it again, how can i load from a external json
i mean, if i use this kind of json to export and than reentrive it, it will "automagilly" create the owner and make the relationship? im kind of lost

if you have some relationship based on ID, if you have something like owner: IDxxxx, for everyplace you load this data, the relationship will be know by the db..

in Realm how this works? Realm is kind of NOSQL?

if yes, so probably it will "duplicate" data

OWNER: O1

PET A
  -> owner: o1
  -> and will add all the information of the owner o1 again here (making some kind of duplicate data)

thats the Realm behaviour??

**Comment by defaultbr** [comment]
forget i got it, now i understand, based in the answer here -> http://stackoverflow.com/questions/31628574/implementing-a-form-of-join-query-on-a-realm-db-without-having-a-predefined-rela

YES, Realm = NoSQL, so it will "duplicate" the data (if you dont create some kind of ID and use your own class to make the second query), so this make sense for me now!!

Can close ;) 

thank you @kneth  now i understand, to export the json i must create some method, thank you so much =)

if i export it to a MySql database is like trying to suicide since this will make the world harder =P, i will search for NoSQL as a backup/export system

**Comment by dalinaum** [comment]
I'm happy to hear this issue can be close. If you encounter further problems, please reopen this or create the new issue. Thanks.
