### ISSUE TITLE
NoClassDefFoundError  io/realm/internal/SharedGroup

### ISSUE THREAD

**Issue by amelize** [realm/realm-java#1929]
We have several crashes on android 4.0.x - 4.1.2 with this stack:

Fatal Exception: java.lang.NoClassDefFoundError: io/realm/internal/SharedGroup
       at io.realm.internal.SharedGroupManager.<init>(SharedGroupManager.java:43)
       at io.realm.BaseRealm.<init>(BaseRealm.java:73)
       at io.realm.Realm.<init>(Realm.java:128)
       at io.realm.Realm.createAndValidate(Realm.java:240)
       at io.realm.Realm.createInstance(Realm.java:225)
       at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:114)
       at io.realm.Realm.getInstance(Realm.java:191)
       ...

SharedGroup is there, but can not be loaded. Realm version is 0.86.0

**Comment by amelize** [comment]
I got more information for now. There is no 'lib' directory after client's application update.  My colleague found following article https://medium.com/keepsafe-engineering/the-perils-of-loading-native-libraries-on-android-befa49dce2db#.totnm9p46.

**Comment by cmelchior** [comment]
Interesting, in that case, those errors should only happen while upgrading your app. Can you verify it is not hitting the same users repeatedly?

That said, we are currently looking into implementing the advice from that blog post: https://github.com/realm/realm-java/pull/1771

**Comment by amelize** [comment]
Yes, it stated after update when we added realm. It affects the group users repeatedly (the did not reinstall application yet).

**Comment by diegomontoya** [comment]
We have 1 single user, Samsung S975L Android 4.3, not sure whether from upgrade to clean install, crash 22 times repeatedly due to this issue. If ReLinker lib fixes this, it would be great.

**Comment by kneth** [comment]
@amelize Have you seen that we have merged #1772? It is possible to try it out as a snapshot release. Or you can wait a little longer to it be released.

**Comment by cmelchior** [comment]
Closing due to no response.
