### ISSUE TITLE
Getting error in Realm proxy on Samsung S3(Jelli Bean)

### ISSUE THREAD

**Issue by sekardec29** [realm/realm-java#1933]
E/dalvikvm: Could not find class 'io.realm.MediaRealmBeanRealmProxy', referenced from method io.realm.DefaultRealmModuleMediator.newInstance
12-12 13:03:44.394 4217-4217/? E/dalvikvm: Could not find class 'io.realm.CategoryRealmBeanRealmProxy', referenced from method io.realm.DefaultRealmModuleMediator.newInstance
12-12 13:03:44.394 4217-4217/? E/dalvikvm: Could not find class 'io.realm.FormsRealmBeanRealmProxy', referenced from method io.realm.DefaultRealmModuleMediator.newInstance
12-12 13:03:44.398 4217-4217/? E/dalvikvm: Could not find class 'io.realm.AdsRealmBeanRealmProxy', referenced from method io.realm.DefaultRealmModuleMediator.newInstance
12-12 13:03:44.398 4217-4217/? E/dalvikvm: Could not find class 'io.realm.SponsorInfoRealmBeanRealmProxy', referenced from method io.realm.DefaultRealmModuleMediator.newInstance
12-12 13:03:44.398 4217-4217/? E/dalvikvm: Could not find class 'io.realm.EventRealmBeanRealmProxy', referenced from method io.realm.DefaultRealmModuleMediator.newInstance
12-12 13:03:44.398 4217-4217/? E/dalvikvm: Could not find class 'io.realm.FormFilledDetailsRealmBeanRealmProxy', referenced from method io.realm.DefaultRealmModuleMediator.newInstance
12-12 13:03:44.398 4217-4217/? E/dalvikvm: Could not find class 'io.realm.PostRealmBeanRealmProxy', referenced from method io.realm.DefaultRealmModuleMediator.newInstance
12-12 13:03:44.398 4217-4217/? E/dalvikvm: Could not find class 'io.realm.AppRealmBeanRealmProxy', referenced from method io.realm.DefaultRealmModuleMediator.newInstance
12-12 13:03:45.534 4217-4217/com.nomadeducation.annalesprepabac E/AndroidRuntime: FATAL EXCEPTION: main
12-12 13:03:45.534 4217-4217/com.nomadeducation.annalesprepabac E/AndroidRuntime: java.lang.NoClassDefFoundError: io.realm.PostRealmBeanRealmProxy
12-12 13:03:45.534 4217-4217/com.nomadeducation.annalesprepabac E/AndroidRuntime:     at io.realm.DefaultRealmModuleMediator.validateTable(DefaultRealmModuleMediator.java:92)
12-12 13:03:45.534 4217-4217/com.nomadeducation.annalesprepabac E/AndroidRuntime:     at io.realm.Realm.initializeRealm(Realm.java:342)
12-12 13:03:45.534 4217-4217/com.nomadeducation.annalesprepabac E/AndroidRuntime:     at io.realm.Realm.createAndValidate(Realm.java:310)
12-12 13:03:45.534 4217-4217/com.nomadeducation.annalesprepabac E/AndroidRuntime:     at io.realm.Realm.create(Realm.java:246)
12-12 13:03:45.534 4217-4217/com.nomadeducation.annalesprepabac E/AndroidRuntime:     at io.realm.Realm.getInstance(Realm.java:219)
12-12 13:03:45.534 4217-4217/com.nomadeducation.annalesprepabac E/AndroidRuntime:     at io.realm.Realm.getInstance(Realm.java:182)
12-12 13:03:45.534 4217-4217/com.nomadeducation.annalesprepabac E/AndroidRuntime:     at fr.appsolute.prepahec.activities.SplashActivity.onCreate(SplashActivity.java:82)
12-12 13:03:45.534 4217-4217/com.nomadeducation.annalesprepabac E/AndroidRuntime:     at android.app.Activity.performCreate(Activity.java:5008)
12-12 13:03:45.534 4217-4217/com.nomadeducation.annalesprepabac E/AndroidRuntime:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1079)
12-12 13:03:45.534 4217-4217/com.nomadeducation.annalesprepabac E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2023)
12-12 13:03:45.534 4217-4217/com.nomadeducation.annalesprepabac E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2084)
12-12 13:03:45.534 4217-4217/com.nomadeducation.annalesprepabac E/AndroidRuntime:     at android.app.ActivityThread.access$600(ActivityThread.java:130)
12-12 13:03:45.534 4217-4217/com.nomadeducation.annalesprepabac E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1195)
12-12 13:03:45.534 4217-4217/com.nomadeducation.annalesprepabac E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:99)
12-12 13:03:45.534 4217-4217/com.nomadeducation.annalesprepabac E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:137)
12-12 13:03:45.534 4217-4217/com.nomadeducation.annalesprepabac E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:4745)
12-12 13:03:45.534 4217-4217/com.nomadeducation.annalesprepabac E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method)
12-12 13:03:45.534 4217-4217/com.nomadeducation.annalesprepabac E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:511)
12-12 13:03:45.534 4217-4217/com.nomadeducation.annalesprepabac E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:786)
12-12 13:03:45.534 4217-4217/com.nomadeducation.annalesprepabac E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
12-12 13:03:45.534 4217-4217/com.nomadeducation.annalesprepabac E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)

is anyone solved this issues before?????

**Comment by cmelchior** [comment]
For some reason your proxy classes are not part of the APK. Have you tried doing a clean build? Otherwise we need more information about your setup, e.g. are you using MultiDex? Does it only happen on the S3?

**Comment by sekardec29** [comment]
Yes, I used MultiDex in my gradle.

I get the same error after clean and rebuild the project and how to resolve it?

these my dependencies  

 compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.0.1'
    compile 'com.android.support:design:23.0.1'
    compile 'com.android.support:recyclerview-v7:23.0.1'
    compile 'com.android.support:cardview-v7:23.0.1'
    compile 'com.android.support:support-v4:+'
    compile 'com.facebook.android:facebook-android-sdk:4.8.2'
    compile 'com.google.android.gms:play-services:8.3.0'
    compile 'com.google.android.gms:play-services-analytics:8.3.0'
    compile 'com.mcxiaoke.volley:library-aar:1.0.0'
    compile 'io.realm:realm-android:0.84.1'
    compile('com.crashlytics.sdk.android:crashlytics:2.5.5@aar') {
        transitive = true;
    }

**Comment by kneth** [comment]
Please try to disable multidex. We haven't any advice for multidex - see #1815.

**Comment by sekardec29** [comment]
Okay Thank You...:-)@Kneth

**Comment by kneth** [comment]
@sekardec29 I'll close the issue and ask you to track #1815.
