### ISSUE TITLE
XXX is not part of the schema for this Realm

### ISSUE THREAD

**Issue by telenewbie** [realm/realm-java#1938]
12-14 16:44:29.775: E/CrashCommonHandler(6776): java.lang.IllegalArgumentException: SongInfo is not part of the schema for this Realm
12-14 16:44:29.775: E/CrashCommonHandler(6776): 	at io.realm.internal.modules.CompositeMediator.getMediator(CompositeMediator.java:116)
12-14 16:44:29.775: E/CrashCommonHandler(6776): 	at io.realm.internal.modules.CompositeMediator.getTableName(CompositeMediator.java:79)
12-14 16:44:29.775: E/CrashCommonHandler(6776): 	at io.realm.Realm.getTable(Realm.java:1146)
12-14 16:44:29.775: E/CrashCommonHandler(6776): 	at io.realm.Realm.checkHasPrimaryKey(Realm.java:1068)
12-14 16:44:29.775: E/CrashCommonHandler(6776): 	at io.realm.Realm.copyToRealmOrUpdate(Realm.java:707)
12-14 16:44:29.775: E/CrashCommonHandler(6776): 	at com.txznet.music.db.DbHandler$1.execute(DbHandler.java:182)
12-14 16:44:29.775: E/CrashCommonHandler(6776): 	at io.realm.Realm.executeTransaction(Realm.java:947)
12-14 16:44:29.775: E/CrashCommonHandler(6776): 	at com.txznet.music.db.DbHandler.add(DbHandler.java:179)
12-14 16:44:29.775: E/CrashCommonHandler(6776): 	at com.txznet.music.db.DbHandler.addAll(DbHandler.java:198)
12-14 16:44:29.775: E/CrashCommonHandler(6776): 	at com.txznet.music.engine.SongListFragmentEngine.getLocalMusic(SongListFragmentEngine.java:77)
12-14 16:44:29.775: E/CrashCommonHandler(6776): 	at com.txznet.music.fragment.SongListFragment.initData(SongListFragment.java:116)
12-14 16:44:29.775: E/CrashCommonHandler(6776): 	at com.txznet.music.fragment.base.BaseFragment.onActivityCreated(BaseFragment.java:32)
12-14 16:44:29.775: E/CrashCommonHandler(6776): 	at android.support.v4.app.Fragment.performActivityCreated(Fragment.java:1512)
12-14 16:44:29.775: E/CrashCommonHandler(6776): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:962)
12-14 16:44:29.775: E/CrashCommonHandler(6776): 	at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1121)
12-14 16:44:29.775: E/CrashCommonHandler(6776): 	at android.support.v4.app.BackStackRecord.run(BackStackRecord.java:682)
12-14 16:44:29.775: E/CrashCommonHandler(6776): 	at android.support.v4.app.FragmentManagerImpl.execPendingActions(FragmentManager.java:1484)
12-14 16:44:29.775: E/CrashCommonHandler(6776): 	at android.support.v4.app.FragmentManagerImpl$1.run(FragmentManager.java:450)
12-14 16:44:29.775: E/CrashCommonHandler(6776): 	at android.os.Handler.handleCallback(Handler.java:725)
12-14 16:44:29.775: E/CrashCommonHandler(6776): 	at android.os.Handler.dispatchMessage(Handler.java:92)
12-14 16:44:29.775: E/CrashCommonHandler(6776): 	at android.os.Looper.loop(Looper.java:137)
12-14 16:44:29.775: E/CrashCommonHandler(6776): 	at android.app.ActivityThread.main(ActivityThread.java:5045)
12-14 16:44:29.775: E/CrashCommonHandler(6776): 	at java.lang.reflect.Method.invokeNative(Native Method)
12-14 16:44:29.775: E/CrashCommonHandler(6776): 	at java.lang.reflect.Method.invoke(Method.java:511)
12-14 16:44:29.775: E/CrashCommonHandler(6776): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:818)
12-14 16:44:29.775: E/CrashCommonHandler(6776): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
12-14 16:44:29.775: E/CrashCommonHandler(6776): 	at dalvik.system.NativeStart.main(Native Method)

this is my code below
```
// Define you model class by extending the RealmObject
	public class SongInfo extends RealmObject {
		private String name;
		private int age;

		public String getName() {
			return name;
		}

		public void setName(String name) {
			this.name = name;
		}

		public int getAge() {
			return age;
		}

		public void setAge(int age) {
			this.age = age;
		}

		// ... Generated getters and setters ...
	}
```

**Comment by kneth** [comment]
Do you define a `RealmModule`? If so, did you include `SongInfo`?

Did you add `SongInfo` to your app as part of an upgrade? If so, did you add a migration step? See https://realm.io/docs/java/latest/#migrations

**Comment by telenewbie** [comment]
We have several crashes  with this stack with the  help of your :

12-14 20:00:34.385: E/AndroidRuntime(23765): java.lang.NoClassDefFoundError: io.realm.RealmConfiguration$Builder
12-14 20:00:34.385: E/AndroidRuntime(23765): 	at com.example.teletest.BaseApplication.onCreate(BaseApplication.java:41)
12-14 20:00:34.385: E/AndroidRuntime(23765): 	at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1000)
12-14 20:00:34.385: E/AndroidRuntime(23765): 	at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4391)
12-14 20:00:34.385: E/AndroidRuntime(23765): 	at android.app.ActivityThread.access$1300(ActivityThread.java:141)
12-14 20:00:34.385: E/AndroidRuntime(23765): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1294)
12-14 20:00:34.385: E/AndroidRuntime(23765): 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-14 20:00:34.385: E/AndroidRuntime(23765): 	at android.os.Looper.loop(Looper.java:137)
12-14 20:00:34.385: E/AndroidRuntime(23765): 	at android.app.ActivityThread.main(ActivityThread.java:5045)
12-14 20:00:34.385: E/AndroidRuntime(23765): 	at java.lang.reflect.Method.invokeNative(Native Method)
12-14 20:00:34.385: E/AndroidRuntime(23765): 	at java.lang.reflect.Method.invoke(Method.java:511)
12-14 20:00:34.385: E/AndroidRuntime(23765): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:818)
12-14 20:00:34.385: E/AndroidRuntime(23765): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
12-14 20:00:34.385: E/AndroidRuntime(23765): 	at dalvik.system.NativeStart.main(Native Method)

how to deal with it?thanks you.

**Comment by kneth** [comment]
@telenewbie Is it possible for you to share the code which constructs the `RealmConfiguration`?

**Comment by telenewbie** [comment]
public class MainActivity extends Activity {
	private final static String TAG = "MainActivity";
	private static final int REQUEST_ENABLE = 0;
	private RealmMigration migration;

	@Override
	protected void onCreate(Bundle savedInstanceState) {
		super.onCreate(savedInstanceState);
		setContentView(R.layout.activity_main);

		migration = new RealmMigration() {
			@Override
			public void migrate(DynamicRealm realm, long oldVersion,
					long newVersion) {

				// DynamicRealm exposes an editable schema
				RealmSchema schema = realm.getSchema();
				// Migrate to version 1: Add a new class
				if (newVersion == 0) {
					schema.create("SongInfo").addField("name", String.class)
							.addField("age", int.class);
					oldVersion++;
				}
			}
		};

		// Use them like regular java objects
		SongInfo songInfo = new SongInfo();
		songInfo.setName("Rex");
		// Open the Realm with encryption enabled
		RealmConfiguration realmConfiguration = new RealmConfiguration.Builder(
				this).migration(migration).schemaVersion(0).build();

		// Start with a clean slate every time
		Realm.deleteRealm(realmConfiguration);

		// Open the Realm with encryption enabled
		Realm realm = Realm.getInstance(realmConfiguration);
		// Persist your data easily
		realm.beginTransaction();
		realm.copyToRealm(songInfo);
		realm.commitTransaction();
	}
}

this is my code and problem.
12-14 20:45:14.115: E/AndroidRuntime(7967): java.lang.NoClassDefFoundError: com.example.teletest.MainActivity$1
12-14 20:45:14.115: E/AndroidRuntime(7967): 	at com.example.teletest.MainActivity.onCreate(MainActivity.java:26)
12-14 20:45:14.115: E/AndroidRuntime(7967): 	at android.app.Activity.performCreate(Activity.java:5104)
12-14 20:45:14.115: E/AndroidRuntime(7967): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1080)
12-14 20:45:14.115: E/AndroidRuntime(7967): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2144)
12-14 20:45:14.115: E/AndroidRuntime(7967): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2230)
12-14 20:45:14.115: E/AndroidRuntime(7967): 	at android.app.ActivityThread.access$600(ActivityThread.java:141)
12-14 20:45:14.115: E/AndroidRuntime(7967): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1234)
12-14 20:45:14.115: E/AndroidRuntime(7967): 	at android.os.Handler.dispatchMessage(Handler.java:99)
12-14 20:45:14.115: E/AndroidRuntime(7967): 	at android.os.Looper.loop(Looper.java:137)
12-14 20:45:14.115: E/AndroidRuntime(7967): 	at android.app.ActivityThread.main(ActivityThread.java:5045)
12-14 20:45:14.115: E/AndroidRuntime(7967): 	at java.lang.reflect.Method.invokeNative(Native Method)
12-14 20:45:14.115: E/AndroidRuntime(7967): 	at java.lang.reflect.Method.invoke(Method.java:511)
12-14 20:45:14.115: E/AndroidRuntime(7967): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:818)
12-14 20:45:14.115: E/AndroidRuntime(7967): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:584)
12-14 20:45:14.115: E/AndroidRuntime(7967): 	at dalvik.system.NativeStart.main(Native Method)

**Comment by kneth** [comment]
I have tried to create a small app with the activity and model class as outlined above, and I haven't been able to reproduce the error.

**Comment by beeender** [comment]
@telenewbie Have you solved your problem? For easier issue management, we are closing this issue now. Feel free to reopen it if you still have problem with it.

Thanks a lot for your feedback!

**Comment by telenewbie** [comment]
sorry, i forget to close this problem.thanks your help.
