### ISSUE TITLE
Possible problem with the reference count

### ISSUE THREAD

**Issue by douglasjunior** [realm/realm-java#1942]
I am creating an option to delete the database in my app, and found a possible problem in the reference count. I am using **0.87.0-SNAPSHOT** to help in testing and also because I need the `Realm.copyFromRealm()`.

When I try to delete the database, the Realm check the reference count for opened instances. But the increase is happening several times to the same instance. Throwing error `IllegalStateException`.

If I do:
```java
        RealmConfiguration config = new RealmConfiguration.Builder(getContext())
                    .name("database.realm")
                    .deleteRealmIfMigrationNeeded()
                    .schemaVersion(1)
                    .build();

        Realm.setDefaultConfiguration(config);
        Realm realm = Realm.getDefaultInstance();
        realm.close();
        Realm.deleteRealm(config);
```
Everything works fine.

But, if i do:
```java
        Realm.setDefaultConfiguration(config);
        Realm realm = Realm.getDefaultInstance();
        Log.v("InitRealm", "Realm1: " + realm.hashCode());
        realm = Realm.getDefaultInstance();
        Log.v("InitRealm", "Realm2: " + realm.hashCode());
        realm.close();
        Realm.deleteRealm(config);
```

Out:
```log
Realm1: 1094523336
Realm2: 1094523336
java.lang.IllegalStateException: It's not allowed to delete the file associated with an open Realm. Remember to close() all the instances of the Realm before deleting its file.
        at io.realm.BaseRealm$1.onResult(BaseRealm.java:520)
        at io.realm.RealmCache.invokeWithGlobalRefCount(RealmCache.java:249)
        at io.realm.BaseRealm.deleteRealm(BaseRealm.java:516)
        at io.realm.Realm.deleteRealm(Realm.java:1225)
...
```
I believe this should not happen, because I recovered twice the same reference.

**Comment by kneth** [comment]
The number of `realm.close()` should match the the number of `Realm.getDefaultInstance()`. I can see where your confusion comes from in the second code snippet above: you think the reference count is stored within `realm` which is overwritten. But the reference count is a global state.

**Comment by douglasjunior** [comment]
I understand, but when I do a `getDefaultInstance()` within the same thread, 
I do not have a new reference.. It's always the same reference. 

It makes no sense to have to call `close()` to each `getDefaultInstance()`.

I can call several times `getDefaultInstance()` in the same thread, and end call only once the `close()` without problems.

This can occur due to many `Fragments` within an `Activity`. 

Because I make sure there is no open instance, I am deleting the file manually, like this:

```java
        String path = realm.getPath();
        realm.close();
        File file = new File(path);
        file.delete();
```

**Comment by kneth** [comment]
As `getDefaultInstance()` (and `getInstance()`) is a static method, Realm cannot detect that you override an existing object. If you did

    Realm realm1 = Realm.getDefaultInstance();
    Realm realm2 = Realm.getDefaultInstance();
    realm1 = realm2;

it is virtually impossible to detect that only one instance is open. As [`finalize()`](http://developer.android.com/reference/java/lang/Object.html#finalize%28%29) is never a good idea, you have to close Realms manually.

The method `Realm.isClosed()` might be useful in your case.

**Comment by douglasjunior** [comment]
My question is related to the cache instances. For the Realm always returns the same instance already open to the same thread.

Thinking about it, I thought the increased counter should only occur when a new instance is created.
That is, when it just return a cached instance, the counter would not be incremented.

See the code below: [RealmCache.java](https://github.com/realm/realm-java/blob/master/realm/realm-library/src/main/java/io/realm/RealmCache.java)

```java
    static synchronized <E extends BaseRealm> E createRealmOrGetFromCache(RealmConfiguration configuration,
                                                        Class<E> realmClass) {
        boolean isCacheInMap = true;
        RealmCache cache = cachesMap.get(configuration.getPath());
        if (cache == null) {
            // Create a new cache
            cache = new RealmCache(configuration);
            // The new cache should be added to the map later.
            isCacheInMap = false;
        } else {
            // Throw the exception if validation failed.
            cache.validateConfiguration(configuration);
        }

        RefAndCount refAndCount = cache.refAndCountMap.get(RealmCacheType.valueOf(realmClass));

        if (refAndCount.localRealm.get() == null) {
            // Create a new local Realm instance
            BaseRealm realm;

            if (realmClass == Realm.class) {
                // RealmMigrationNeededException might be thrown here.
                realm = Realm.createInstance(configuration, cache.typedColumnIndices);
            } else if (realmClass == DynamicRealm.class) {
                realm = DynamicRealm.createInstance(configuration);
            } else {
                throw new IllegalArgumentException(WRONG_REALM_CLASS_MESSAGE);
            }

            // The Realm instance has been created without exceptions. Cache and reference count can be updated now.

            // The cache is not in the map yet. Add it to the map after the Realm instance created successfully.
            if (!isCacheInMap) {
                cachesMap.put(configuration.getPath(), cache);
            }
            refAndCount.localRealm.set(realm);
            refAndCount.localCount.set(0);
        }

        Integer refCount = refAndCount.localCount.get();
        if (refCount == 0) {
            if (realmClass == Realm.class && refAndCount.globalCount == 0) {
                cache.typedColumnIndices = refAndCount.localRealm.get().schema.columnIndices;
            }
            // This is the first instance in current thread, increase the global count.
            refAndCount.globalCount++;
        }
        refAndCount.localCount.set(refCount + 1);

        @SuppressWarnings("unchecked")
        E realm = (E) refAndCount.localRealm.get();
        return realm;
    }
```
On line [108](https://github.com/realm/realm-java/blob/master/realm/realm-library/src/main/java/io/realm/RealmCache.java#L108) it checks if there is already an instance for this Thared in the cache, if it exists it does not create a new instance, it will only return the same.

However, in line [139](https://github.com/realm/realm-java/blob/master/realm/realm-library/src/main/java/io/realm/RealmCache.java#L139), the counter is always incremented. My logic says that the counter was incremented only if a new instance was created.

Sorry if I did not understand his explanation. But if a new instance is not created, why the counter should be increased?

**Comment by zaki50** [comment]
That is an intended behavior.
Realm expects that `close()` is called with the same rate of `getInstance()`.

On each thread, `getInstance()` increments the counter, and `close()` decrements the counter.
And if the counter becomes `0`, then Realm execute cleanup task and dispose itself.

Simple rule. you must call `close()` against each `getInstance()`.

**Comment by douglasjunior** [comment]
I understand, but I was not convinced.

If the developer call `getInstance()` twice in the same thread, all is lost, it can never make the counter back to `0`.

This can occur because a Activity has several fragments working in the same thread.

I have to work another way to keep the singletons.

Thank you for your attention.

**Comment by zaki50** [comment]
If you call `getInstance()` twice in the same thread, calling `close()` twice maks the counter back to 0.

**Comment by douglasjunior** [comment]
But I'll call `close()`" twice in the same instance (same object reference). This will not fail?

**Comment by zaki50** [comment]
will not fail.
