### ISSUE TITLE
Detect invalid RealmResults

### ISSUE THREAD

**Issue by kneth** [realm/realm-java#1945]
The following code might lead to a native crash:

    realm.beginTransaction();
    RealmResults<Owner> owners = realm.allObjects(Owner.class);
    RealmResults<Dog> dogs = owners.first().where().equalTo("dogs.name", "Fido").findAll();
    owners.clear();
    long nDogs = dogs.size(); // crash here
    realm.commitTransaction();

The reason is that Realm's storage engine doesn't invalidate `dogs` after `owners.clear()`. Once it does, an exception should be thrown at `dogs.size()`.

See also https://github.com/realm/realm-core/issues/1413

**Comment by beeender** [comment]
#2133 fixed this.
