### ISSUE TITLE
Port deleteAllObjects to realm-java

### ISSUE THREAD

**Issue by rgrinberg** [realm/realm-java#1947]
realm-swift has this useful method for clearing a realm database:

https://realm.io/docs/objc/latest/api/Classes/RLMRealm.html#/c:objc(cs)RLMRealm(im)deleteAllObjects

Would be nice to have in java too

**Comment by cmelchior** [comment]
Hi @rgrinberg 
Thanks for the suggestion. We already have an issue tracking missing `delete*` methods, but it seems we forgot this one. I'll add it to the list here: https://github.com/realm/realm-java/issues/1560

I'll close this as an duplicate, but you can follow the progress in #1560
