### ISSUE TITLE
How to pass model object in RealmResult from fragment to another fragment?

### ISSUE THREAD

**Issue by csnu17** [realm/realm-java#1948]
I use first fragment to load data from Realm and show the ListView. Then when I click at the item it should pass the object at the specific index to the second fragment. However when the first fragment is already replaced the realm.close() will be call inside onStop() method. Then when I use the object in the second fragment, app will crash with java.lang.IllegalStateException: This Realm instance has already been closed, making it unusable. I try to call Realm.getDefaultInstance(); in the onStart() method in the second fragment but also don't work. Thank you for your helping.

**Comment by cmelchior** [comment]
Realm objects are scoped by how long the Realm instance is alive, and as you point out. onStart/onStop in fragments might not overlap.

We have some suggestions to work around this in the docs here: https://realm.io/docs/java/latest/#controlling-the-lifecycle-of-realm-instances 

But the basic idea is that you should keep the Realm instance open, e.g. by using the Activity lifecycle instead.

**Comment by csnu17** [comment]
You mean I should delete all of Realm objects in any fragments and use only once public static Realm instance from Activity that hold the fragments? Or you mean I should implement Realm instance open/close both activity and fragments life cycle?

**Comment by csnu17** [comment]
Now Realm for Android 0.87.0 already has copyFromRealm() that solves the issue. Thank you very much.
