### ISSUE TITLE
RealmResults isn't updated in onChange

### ISSUE THREAD

**Issue by RobertoArtiles** [realm/realm-java#1950]
Hi team,

I have a chained query which I execute on Main Thread, and RealmResults of which I store in the field in the custom view. The custom view is provided to the Realm as RealmChangeListener. When I change something in the Realm from the Activity (also on the Main Thread), onChange() gets triggered, but if I put a breakpoint inside onChange() and check the field with RealmResults, it has the same set of results (although, with updated values). But if I execute the same query in debug mode while standing on that breakpoint, it will return the correct set of results.

The chained query looks like this:
```java
query = realm.where(Model.class)
                    .isNotNull("x")
                    .isNotNull("y")
                    .isNotNull("z");

...

query.where()
     .equalTo("z", z)
     .findAll();
```

Realm version: 0.86.1

**Comment by cmelchior** [comment]
Can you also post your OnChangeListener and which object it is registered on? It is a bit hard to tell from your description.

Also is it something you just see when debugging? or does it work correctly when running the code?

**Comment by RobertoArtiles** [comment]
>Also is it something you just see when debugging? or does it work correctly when running the code?

It also doesn't work when the code is running.

>an you also post your OnChangeListener and which object it is registered on? It is a bit hard to tell from your description.

It all happens inside the custom view. The view implements the RealmChangeListener. The only thing I do in the onChangeListener() is grab one of the items from the RealmResults and do some UI updates based on it. It looks something like this:

```java
public class CustomView extends View {
	
	private RealmResults<Model> realmResults;

	public CustomView(Context context) {
		super(context);
		Realm.getDefaultInstace();
		realmResults = realm.where(Model.class)
                    		.isNotNull("x")
                    		.isNotNull("y")
                    		.isNotNull("z")
                    		.where()
                    		.equalTo("z", z)
     						.findAll(); // 


		realm.addChangeListener(this);
	}
	
	...
	
	@Override
	public void onChange() {
		Integer x = realmResults.first().getX();
		
		// do something with x
	}

}
```

The problem is that `realmResults` has a stale set of results (in this specific case it has on one more item than it should). So, if I execute exactly the same query right in the onChange() it will return the correct set of values.

**Comment by kneth** [comment]
@RobertoArtiles Is your issue related to #1894?

**Comment by RobertoArtiles** [comment]
@kneth Seems like it's fixed.

**Comment by dalinaum** [comment]
@RobertoArtiles Great. I'll close this issue. Don't hesitate to create an issue if you have questions.
