### ISSUE TITLE
Realm Query:  In Realm how to select all rows where two columns/fields are equal to one an other.

### ISSUE THREAD

**Issue by AamirAbro** [realm/realm-java#1954]
In Realm how to select all rows where two columns/fields are equal to one an other.
I would like to query all records where first field is equal to second field like {"first" : "x" , "second":"x"}.
One way I have  found is to query all records and filer it in code. But this seems very odd to me. And what would be its performance and memory costs?

**Comment by cmelchior** [comment]
Comparing two fields is currently not supported in Realm Java. We have an issue tracking it here: https://github.com/realm/realm-java/issues/1615

Right now your only option is doing the filter manually in code. It would not really have a memory cost as Realm objects are really cheap in terms of memory, but you will most likely experience some memory churn as it will create and destroy a lot of short-lived objects.

**Comment by bmunkholm** [comment]
An additional detail: It is supported by the core engine, but not exposed yet in the Java binding.

**Comment by AamirAbro** [comment]
Thanks and would be awesome to have this feature.

**Comment by cmelchior** [comment]
We think so too :)
I'll close this issue as an duplicate. You can track progress in #1615
