### ISSUE TITLE
Could not find class 'io.realm.rx.RealmObservableFactory$1'

### ISSUE THREAD

**Issue by atouchsimo** [realm/realm-java#1967]
E/dalvikvm: Could not find class 'io.realm.rx.RealmObservableFactory$1', referenced from method io.realm.rx.RealmObservableFactory.from

version 87.0

**Comment by cmelchior** [comment]
Please see https://github.com/realm/realm-java/blob/master/CONTRIBUTING.md#filing-issues when creating issues.

**Comment by cmelchior** [comment]
This seems to be the same issue as https://github.com/realm/realm-java/issues/2023, i'll close this one as a duplicate. Please provide any information in #2023
