### ISSUE TITLE
Migration sometimes not executed

### ISSUE THREAD

**Issue by rimeissner** [realm/realm-java#1968]
With the new version of our app we use the new version of the migration system. Therefore we had to rewrite all our migrations and in all our local tests everything seems to work perfectly.

Now we rolled out the new version and have some users where we get errors that tables are missing or that the column count is different.

We have a user that started the app twice within an our. First time we got the error that a table was missing, the second time we got the error that expected column count was 13 but only 10 were in the table. 

As this prevents some of our users to start the app I wanted to ask if you can recommend a way how to handle this situation. And if there is any way that you can help us out.

I understand that this is an issue that you might not be able to help us with since we cannot provide much information.

**Comment by cmelchior** [comment]
Without more information it is hard to speculate what could be wrong. One thing you can do is try to accessing the schema using the Dynamic API in case of errors and print all field names for the classes that are wrong. Hopefully that can provide more insight into which fields are missing:

```
try {
  Realm realm = Realm.getInstance(config);
} catch (RealmMigrationNeededException e) {
  DynamicRealm dynamicRealm = DynamicRealm.getInstance(config); // This doesn't fail if the schema is wrong
  dynamicRealm.getSchema().get("Foo").getFieldNames(); // Returns the list of field
}
```

**Comment by rimeissner** [comment]
Right now I am using that approach to save some data, then I trash the Realm file and put the data back in. 

When we have more information I will let you know :confused: Thankfully the DynamicRealm is still able to access the data. 

This ticket can be closed. Just wanted to check if you have some idea what could cause this. Thanks :)
