### ISSUE TITLE
Issue importing jsonexample in Android Studio

### ISSUE THREAD

**Issue by jkblgithub** [realm/realm-java#1969]
I am running Adroid Studio 1.5.1 . When I try to import jsonexample as a project, I get the following error:
`Error:Could not find io.realm:realm-gradle-plugin:0.88.0-SNAPSHOT.`

Any ideas how I can get it imported please?

**Comment by cmelchior** [comment]
There is a chance our 0.88.0-SNAPSHOT hasn't been deployed yet. You can install it yourself locally by running `./gradlew installRealmJava` from the root folder

**Comment by beeender** [comment]
@jkblgithub I hope you solved this issue. I am closing this issue now, feel free to reopen it if you still have problems. Thanks a lot for your feedback!
