### ISSUE TITLE
ConcurrentModificationException while making notification

### ISSUE THREAD

**Issue by roughboy** [realm/realm-java#1970]
Hi,
i'm geting exception when running below code:
<pre><code>public static void makeMutableWorkoutCopy(Realm realm, final long workoutId) {
        realm.beginTransaction();
            Workout workout = realm.where(Workout.class).equalTo("id", workoutId).findFirst();

            Workout copyWorkout = realm.copyFromRealm(workout);
            copyWorkout.setId(IdentifierGenerator.getInstance().generateUniqueId(realm, Workout.class));
            copyWorkout.setName(copyWorkout.getName() + "*");
            copyWorkout.setSections(new RealmList<Section>());
            copyWorkout.setImmutableWorkout(workout);

            workout.setMutableWorkout(realm.copyToRealmOrUpdate(copyWorkout));
        realm.commitTransaction();
    }</code></pre>
Exception:
<pre><code>java.util.ConcurrentModificationException
at java.util.IdentityHashMap$IdentityHashMapIterator.checkConcurrentMod(IdentityHashMap.java:164)
at java.util.IdentityHashMap$IdentityHashMapIterator.next(IdentityHashMap.java:169)
at io.realm.HandlerController.notifyRealmObjectCallbacks(HandlerController.java:254)
at io.realm.HandlerController.notifyTypeBasedListeners(HandlerController.java:207)
at io.realm.BaseRealm.commitTransaction(BaseRealm.java:294)
at io.realm.Realm.commitTransaction(Realm.java:108)
at com.borg.forza.model.RealmUtils.makeMutableWorkoutCopy(RealmUtils.java:289)
</code></pre>

The model of Workout.class looks like below:
<pre><code>public class Workout extends RealmObject {

    @Index      private long                    id;
                private long                    backendId;
                private int                     sync;

    @PrimaryKey private String                  name;
                private String                  description;
    @Index      private String                  type;
                private long                    duration;
                private RealmList<Section>      sections;
                private int                     access;
                private Workout                 mutableWorkout;
                private Workout                 immutableWorkout;
    }</code></pre>
I am using 0.87.0-SNAPSHOT.
Thanks!

**Comment by cmelchior** [comment]
Hi @roughboy We released 0.87.0 yesterday. Can you verify if the problem still happens there?

**Comment by roughboy** [comment]
@cmelchior problem still exists in 0.87.0.

**Comment by cmelchior** [comment]
Thanks, we will look into it.

**Comment by cmelchior** [comment]
Hi @roughboy 
I am having a bit of trouble reproducing this. It looks like you have registered a `RealmChangeListener` on a single object, most likely a Workout object. Are you doing something special inside that listener like removing/adding listeners or similar?

If you can post a working sample project that demonstrate the failure it would be even better.

**Comment by roughboy** [comment]
Indeed, it was hard to reproduce it, but i managed to do it. I put zip package here:
https://drive.google.com/file/d/0B_iAqFNIegRpY1lKNC03b1RLMVE/view?usp=sharing

In order to reproduce the issue after app is installed hit FAB button several times. Next close the app (by swapping it out) and open app again. Now hit FAB again and the exception should be thrown.

**Comment by kneth** [comment]
@roughboy Thank you for the app. It is quite easy to reproduce the exception. We'll look into it.

**Comment by beeender** [comment]
`addToRealmObjects` in object getter called in the listener triggered the crash. Working on a fix.
