### ISSUE TITLE
Snapshots: Source Packaging

### ISSUE THREAD

**Issue by diegomontoya** [realm/realm-java#1971]
Since Oct 29 v0.84.2 snapshot release, the source package is no longer part of the snapshot release process. It would be great if this condition can be reverted if not actually intended.

**Comment by cmelchior** [comment]
From what I can tell, it looks like the sources are still deployed as part of 0.87.0-SNAPSHOT, but not 0.88.0-SNAPSHOT?

In any case, it is a mistake they are not there. We will look into it.

**Comment by cmelchior** [comment]
0.87.2 has been released with proper sources and javadocs.

**Comment by Zhuinden** [comment]
3.7.2 is latest and best release atm but it should work
