### ISSUE TITLE
Delay in propagation of changes across Realms

### ISSUE THREAD

**Issue by Saketme** [realm/realm-java#1972]
I'm using a custom solution for listening to Realm updates using an EventBus and manually emitting "update" events which contains info about the changed `RealmObject`. It's working quite nicely and until Realm supports fine-grained notifications, this is the only way I can determine which update to process and which to discard.

One side-effect of this that I'm facing is that when a Realm is updated in a background thread, there's a small delay for that update to appear in another Realm in another thread (say, main thread).

Is this expected?

**Comment by cmelchior** [comment]
Yes. Realm uses the Handler to propagate changelisteners, so there will be a slight delay until the thread can process the handler message. Unless there is a lot of event processing happening, the delay should be really short however.

**Comment by zaki50** [comment]
@Saketme If you'd like to see the changes as soon as possible, you can use `Realm.refresh()`.

**Comment by Saketme** [comment]
@zaki50 Got it, thanks!
