### ISSUE TITLE
parsing json arrays which may have null objects

### ISSUE THREAD

**Issue by ihajat** [realm/realm-java#1979]
Hi,

I am using createOrUpdateAllFromJson, using primary string key, and when I have duplicates I am getting RealmPrimaryKeyConstraintException?

regards

**Comment by cmelchior** [comment]
Hi @ihajat Please see https://github.com/realm/realm-java/blob/master/CONTRIBUTING.md#contributing when creating issues. That way we can help you more effectively.

**Comment by ihajat** [comment]
Hi,

1. Goals: To seek an alternative to sqlite
2. Expected results: I have a work order, the wororderId is the primary key. when I add a new workorder, it inserts it, and when I add the same workorder, it updates it.
3. Actual results: getting RealmPrimaryKeyConstraintException.
4. Steps to reproduce: I would think, any code will be able to reproduce it. I will email you whole project.
5. Version of Realm (0.87.0) / Android Studio (1.5) / OS ( Mac 10.10.5)

kind regards

**Comment by ihajat** [comment]
Hi Christian,

I have found the issue, it was my fault, not your library. The issue was , I was using xx = realm.createObject(XX.class)

sorry

**Comment by cmelchior** [comment]
No problem. I'll close this issue then. Feel free to create another if you run into any other issues.

**Comment by ihajat** [comment]
Thank you. You're most kind.

regards
