### ISSUE TITLE
Statement "IN" like SQL

### ISSUE THREAD

**Issue by danieltigse** [realm/realm-java#1981]
I didn't find a way to implement this:

```sql
SELECT * FROM TABLE WHERE ID IN (id1, id2, ..., idn)
```

**Comment by NikoYuwono** [comment]
Currently realm does not support IN statement but you can build it manually 

```
RealmResults<banned_user_ids> ids = realm.allObjects(banned_user_ids.class);
RealmQuery q = users.where();
for (banned_user_ids id : ids) {
    q = q.equalsTo("id", id.id);
}
RealmResults<users> users = q.findAll();
```

Actually this been talked for a while in https://github.com/realm/realm-java/issues/841 you should take a look at that thread too.

**Comment by cmelchior** [comment]
Hi @danieltigse 
As @NikoYuwono said, we don't currently support something like `IN` and you have to build it manually, like the above code. You can follow #841 for progress on a solution for this.

In the meantime i'll close this as an duplicate.

**Comment by danieltigse** [comment]
OK thank you for the information
