### ISSUE TITLE
native crash while deleting obj from realm.

### ISSUE THREAD

**Issue by RobertBorg** [realm/realm-java#1983]
Possible duplicate of #1982 
While committing an transaction that deletes an Obj1 from realm i get a native crash.
A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x288 in tid 26921 (app)

I'm using 'io.realm:realm-android:0.87.0' from "http://dl.bintray.com/realm/maven"

while deleting the obj1 there is an active subscription to a subquery of obj1. Something like this:
guithread;
obj1.getObj2List().where().equalTo("someField", "asd").findAll().asObservable().subscribe(/*code that only calls size on RealmResults*/)

later in other thread:
r.beginTransaction();
obj1.getObj2List().where().equalTo("someField", "asd").findAll().clear();
r.commitTransaction();
if(obj1.getObj2List().size() == 0) {
r.beginTransaction();
obj1.removeFromRealm();
r.commitTransaction(); // crash
}

not subscribing in guithread prevents the problem from happening

I'm using Android Studio 2.0 built on nov 21 and i think i'm on latest LTS release of ubuntu

If this is not enough to pinpoint the problem i'll probably be able to create isolated example.

**Comment by RobertBorg** [comment]
for anyone facing similar issues i ended up subscribing to obj1 and if obj1.getObj2List().size() == 0 i'd unsubscribe from all subscribsions concerning obj1. A more generic workaround(?) would be using obj1.getPendingDeletion().

**Comment by cmelchior** [comment]
Hi @RobertBorg 
It sounds like you might be experiencing this bug here: https://github.com/realm/realm-java/issues/1945
