### ISSUE TITLE
Unrecoverable error. Unsupported version in io_realm_internal_SharedGroup.cpp line 113

### ISSUE THREAD

**Issue by KynoYang** [realm/realm-java#1984]
```
Fatal Exception: io.realm.exceptions.RealmError: Unrecoverable error. Unsupported version in io_realm_internal_SharedGroup.cpp line 113
       at io.realm.internal.SharedGroup.createNativeWithImplicitTransactions(SharedGroup.java)
       at io.realm.internal.SharedGroup.<init>(SharedGroup.java:67)
       at io.realm.internal.SharedGroupManager.<init>(SharedGroupManager.java:48)
       at io.realm.BaseRealm.<init>(BaseRealm.java:90)
       at io.realm.Realm.<init>(Realm.java:151)
       at io.realm.Realm.createAndValidate(Realm.java:277)
       at io.realm.Realm.create(Realm.java:241)
       at io.realm.Realm.getInstance(Realm.java:214)
```

Above is a piece of crash log that I noticed recently.  I don't know how to reproduce it and what the meaning of this log. The realm version is 0.8.5.1

The devices that report this crash log include Mi 4C, H60-L0, MX5, Che1-CL20. 

I guess maybe I did something wrong when using realm, but I need to know what does the log mean to check my code.

**Comment by cmelchior** [comment]
Hi @KynoYang 
The error seems to happen when you try to open a Realm. A couple of questions:

1) Are you shipping a pre-created Realm file with your app?
2) Are you accessing any Realm files from multiple processes?

**Comment by KynoYang** [comment]
@cmelchior Thanks for replying.
1) Not sure what you mean. @beeender help :cry: 
2) No multiple processes.

**Comment by KynoYang** [comment]
@cmelchior I never use pre-created Realm files with my app.

**Comment by beeender** [comment]
Checked with @KynoYang , it happens even to a fresh installed apk.

It happens when another thread open the Realm instance and there is already a Realm instance opened by the other thread.

Reproduce steps are not clear yet.

**Comment by beeender** [comment]
This issue has not been seen for a week in user's crash report server. And i still cannot reproduce this. Let's keep monitor it for some more weeks.

**Comment by beeender** [comment]
This issue hasn't be reproduced for weeks. Just close for now.

**Comment by beeender** [comment]
https://github.com/realm/realm-core/pull/1369 https://github.com/realm/realm-core/pull/1364 might be relevant to this issue. According to user's report, after release with 0.86.1, this issue hasn't been seen yet.
