### ISSUE TITLE
Info message from art: Rejecting re-init

### ISSUE THREAD

**Issue by rimeissner** [realm/realm-java#1990]
Just as an information, when I start the app with the most current version of Realm I get the following log messages:

```
        I/art: Rejecting re-init on previously-failed class java.lang.Class<io.realm.rx.RealmObservableFactory$4>
        I/art: Rejecting re-init on previously-failed class java.lang.Class<io.realm.rx.RealmObservableFactory$4>
        I/art: Rejecting re-init on previously-failed class java.lang.Class<io.realm.rx.RealmObservableFactory$3>
        I/art: Rejecting re-init on previously-failed class java.lang.Class<io.realm.rx.RealmObservableFactory$3>
        I/art: Rejecting re-init on previously-failed class java.lang.Class<io.realm.rx.RealmObservableFactory$2>
        I/art: Rejecting re-init on previously-failed class java.lang.Class<io.realm.rx.RealmObservableFactory$2>
        I/art: Rejecting re-init on previously-failed class java.lang.Class<io.realm.rx.RealmObservableFactory$1>
        I/art: Rejecting re-init on previously-failed class java.lang.Class<io.realm.rx.RealmObservableFactory$1>
```

We are currently not using the new `rx`feature, but just wanted to see if this is something to be concerned about.

The device was a Nexus 5 running Android 6.

**Comment by cmelchior** [comment]
Thanks for reporting this. I doubt it is something to be concerned about since it is only logged as `I`, but I  must confess I am not entirely sure why it is complaining. I'll look into it.

**Comment by kneth** [comment]
Is it similar to https://code.google.com/p/android/issues/detail?id=186012

**Comment by b12kab** [comment]
The same thing happens to me. I, like the original poster, am not using the rx feature either. This is happened on a One + 1 - both with KitKat and Lollipop. 

01-09 14:02:13.004 22131-22237/? I/art: Rejecting re-init on previously-failed class java.lang.Class<io.realm.rx.RealmObservableFactory$4>
01-09 14:02:13.004 22131-22237/? I/art: Rejecting re-init on previously-failed class java.lang.Class<io.realm.rx.RealmObservableFactory$4>
01-09 14:02:13.005 22131-22237/? I/art: Rejecting re-init on previously-failed class java.lang.Class<io.realm.rx.RealmObservableFactory$3>
01-09 14:02:13.005 22131-22237/? I/art: Rejecting re-init on previously-failed class java.lang.Class<io.realm.rx.RealmObservableFactory$3>
01-09 14:02:13.006 22131-22237/? I/art: Rejecting re-init on previously-failed class java.lang.Class<io.realm.rx.RealmObservableFactory$2>
01-09 14:02:13.006 22131-22237/? I/art: Rejecting re-init on previously-failed class java.lang.Class<io.realm.rx.RealmObservableFactory$2>
01-09 14:02:13.010 22131-22237/? I/art: Rejecting re-init on previously-failed class java.lang.Class<io.realm.rx.RealmObservableFactory$1>
01-09 14:02:13.011 22131-22237/? I/art: Rejecting re-init on previously-failed class java.lang.Class<io.realm.rx.RealmObservableFactory$1>

**Comment by cmelchior** [comment]
While we are investigating this, a work-around would probably be to create a dummy class as explained here: https://realm.io/docs/java/latest/#jackson-databind

**Comment by b12kab** [comment]
I tried that both as package rx as well as package io.realm.rx, neither stopped the error message.

**Comment by kneth** [comment]
@b12kab Thanks for checking.

**Comment by Gnzlt** [comment]
Same problem here on Marshmallow. I also tried with RealmObservableFactory dummy class but the error is still there

**Comment by cmelchior** [comment]
Internal note: This issue is more about understanding the root cause for this message and if possible fix it. It it is "unfixable" we should at least add an entry in our FAQ about it.

**Comment by beeender** [comment]
Some findings, log is printed here
https://android-review.googlesource.com/#/c/147986/1/runtime/class_linker.cc

But it seems a exception should be thrown after that. No clue why it behaves different, maybe the exception is caught by art?

More thinking:
We are adding more and more APIs, things like rxjava support should not be in the base realm-java. Or maybe we could remove rxjava related API during byte code manipulation if the user doesn't need it?

**Comment by cmelchior** [comment]
Ideally I would have loved to have RxJava in its own package, but that is impossible if we want a fluent API. With Kotlin we could have used extension methods, but alas :(

Removing the code completely if not used sounds like an interesting idea though. I am not entirely sure why this didn't work: https://github.com/realm/realm-java/issues/1990#issuecomment-171106611
