### ISSUE TITLE
Missing javaDocs

### ISSUE THREAD

**Issue by ar-g** [realm/realm-java#1996]
Since upgrade to new version 87 no docs and AndroidStudion could not fetch it. Also no separate files here https://bintray.com/realm/maven/realm-android/0.87.1/view#files/io/realm/realm-android/0.87.1

**Comment by kneth** [comment]
@ar-g Sorry for the inconvenience. You'll have to look JavaDoc up at https://realm.io/docs/java/latest/api/ and we'll add it later on.

**Comment by cmelchior** [comment]
This is already being tracked here: https://github.com/realm/realm-java/issues/1971, so any progress on this issue can be tracked there instead. I'll close this as an duplicate.,
