### ISSUE TITLE
`addFiled` with `PRIMARY_KEY` doesn't apply `REQUIRED` modifier implicitly  (Original title - How to migrate a field's type the right way?)

### ISSUE THREAD

**Issue by Saketme** [realm/realm-java#2001]
Hey guys. I'm receiving an exception while trying to change a field's type.

Stacktrace: https://gist.github.com/Saketme/4b8f6274a0103165c79d
RealmObject: https://gist.github.com/Saketme/37894ccc5a1051cd8111
Migration: https://gist.github.com/Saketme/9ff0591dfdc45018e90b

In brief, I wanted to change a field's type from `long` to `String`. Retaining old values was not an option so the whole table had to be dropped. I however could not find a way to clear all items while migrating. Am I supposed to use `Realm.clear()` here?

**Comment by zaki50** [comment]
Hi

how about `dynamicRealm.where(ClearTaxMember.TABLE_NAME).findAll().clear();`?

**Comment by Saketme** [comment]
That seemed to work, but I received a new exception:

`Caused by: io.realm.exceptions.RealmMigrationNeededException: Field 'id' does support null values in the existing Realm file. Remove @Required or @PrimaryKey from field 'id' or migrate using io.realm.internal.Table.convertColumnToNotNullable().`

The id field was previously a `long` field that cannot store null. Does Realm internally store primitive types as Objects?

**Comment by beeender** [comment]
Is the `long` typed `id` removed in the migration? Does the migration block execute?

**Comment by Saketme** [comment]
No, it's still there. I simply changed its type from `long` to `String`. You can see the migration code here: https://gist.github.com/Saketme/9ff0591dfdc45018e90b

**Comment by beeender** [comment]
We might have a bug with `memberSchema.addField(ClearTaxMember.COLUMN_ID, String.class, FieldAttribute.PRIMARY_KEY);` 
You can try this workaround:
```
memberSchema.addField(ClearTaxMember.COLUMN_ID, String.class, FieldAttribute.PRIMARY_KEY, FieldAttribute.REQUIRED);
```

**Comment by beeender** [comment]
@Saketme I made a fix of the `REQUIRED` problem. Before it merged, you can just use `memberSchema.addField(ClearTaxMember.COLUMN_ID, String.class, FieldAttribute.PRIMARY_KEY, FieldAttribute.REQUIRED);` as a workaround. It won't have side effect even the fix gets released.

**Comment by Saketme** [comment]
That worked, thanks!

**Comment by Saketme** [comment]
Oh there's a small typo in this issue's new title: `addFiled`. Should be `addField`.
