### ISSUE TITLE
Build failed with ClassCastException. I was researched this issue then have not idea :( Pls help me

### ISSUE THREAD

**Issue by thanhtranduc** [realm/realm-java#2002]
Error:Execution failed for task ':main:compileServerDevDebugJava'.
> java.lang.ClassCastException: com.sun.tools.javac.code.Symbol$MethodSymbol cannot be cast to javax.lang.model.element.TypeElement
le's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
<a href="syncProject">Re-download dependencies and sync project (requires network)</a></li><li>The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
<a href="stopGradleDaemons">Stop Gradle build processes (requires restart)</a></li><li>Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.</li></ul>In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes.

**Comment by beeender** [comment]
Hi! From the log, it doesn't seem to be a problem related with Realm.
Can you provide more information?

**Comment by thanhtranduc** [comment]
affter remerging code I resolved this issue, so I can't find what's reasion :(
Pls close this issue for me

**Comment by beeender** [comment]
Good the hear the issue is solved! Happy coding then!
