### ISSUE TITLE
Android Realm Permission

### ISSUE THREAD

**Issue by crysan** [realm/realm-java#2005]
Hi!
I use Realm

<code>compile 'io.realm:realm-android:0.87.1'</code>

The configuration database is defined in the class

<code>MyApplication extends Application</code>

And the database file is stored on the SD card.

    myConfig = new RealmConfiguration.Builder(Environment.getExternalStorageDirectory().toString() + "/MyApp/Db/")
            .name(getResources().getString(R.string.app_name_db) + ".realm")
            .schemaVersion(6)
            .migration(migration)
            .build();
    Realm.setDefaultConfiguration(myConfig);

Run on Android 6.0 gives an error that does not have permissions to read / write the SD card. On the Internet there are many examples to address this issue in the class Activity. But what if I need to get permission in a class MyApplication which set the parameters of the database?

**Comment by dalinaum** [comment]
Hello @crysan 

What target SDK version do you use? Is there`<uses-permission android:name="android.permission.WRITE_EXTERNAL_STORAGE" />` in your `AndroidManifest.xml`?

**Comment by crysan** [comment]
API Level 23

**Comment by crysan** [comment]
WRITE_EXTERNAL_STORAGE permission is dangerous and its use should allow the user.

**Comment by kneth** [comment]
You can check if `WRITE_EXTERNAL_STORAGE` is granted at runtime using [`PackageManager.checkPermission()`](http://developer.android.com/reference/android/content/pm/PackageManager.html#checkPermission(java.lang.String, java.lang.String)).

**Comment by beeender** [comment]
Instead of using `Environment.getExternalStorageDirectory()`, use [`Context.getExternalFilesDir()`](http://developer.android.com/reference/android/content/Context.html#getExternalFilesDir%28java.lang.String%29) instead. 

The reason is from Android M, the external SD card can be formatted as an internal storage if use choose to. See http://androidcommunity.com/android-6-0-marshmallow-turns-external-sd-card-to-internal-storage-20151021/ for more information.

You could try:

```java
File file = getExternalFilesDir("/MyApp/Db/"); // The whole path would be something similar to "/storage/emulated/0/Android/data/apptest.realm.io.androidmtest/files/MyApp/Db"
myConfig = new RealmConfiguration.Builder(file)
                    .name("test" + ".realm")
                    .build();
```

Please check the [Doc of `Context.getExternalFilesDir()`](http://developer.android.com/reference/android/content/Context.html#getExternalFilesDir%28java.lang.String%29) for more details.

**Comment by beeender** [comment]
Same question on SO http://stackoverflow.com/questions/34459860/android-realm-permission

**Comment by crysan** [comment]
http://stackoverflow.com/questions/34459860/android-realm-permission
The question I asked.  The answer to it is not.

**Comment by beeender** [comment]
@crysan Does `Context.getExternalFilesDir()` solve your problem?

**Comment by crysan** [comment]
As I described above the problem is not getting the way to the SD card and obtain permission to write to the SD card in Android API 23.

**Comment by beeender** [comment]
@crysan See https://gist.github.com/beeender/3172b31a30b1a67cb095 for the full demo code.

**Comment by crysan** [comment]
Хороший пример. НО это все верно для активности.
А у меня MyApplication extends Application

**Comment by crysan** [comment]
Sorry reopen the issue.

**Comment by crysan** [comment]
Good example.  But it's all right for the activity.
And I MyApplication extends Application

**Comment by crysan** [comment]
And as described on page Realm
<code>
The RealmConfiguration can be saved as a default configuration. Setting a default configuration in your custom Application class, will ensure that it is available in the rest of your code.

public class MyApplication extends Application {
  @Override
  public void onCreate() {
    super.onCreate();
    RealmConfiguration config = new RealmConfiguration.Builder(context).build();
    Realm.setDefaultConfiguration(config);
  }
}
</code>

**Comment by beeender** [comment]
Put the default RealmConfiguration settings in the application is an example for a typical use case, for your use case, i think it is still fine to put it there but with some additional settings:

1. Check the `Context.getExternalFilesDir` return value in the application, and save it somewhere (eg.: `defaultSet = true`)
2. In you first activity, check if defaultSet is false, then start permission request
3. Handle  the result for permission request result, set the `defaultSet = true` if the result is granted.
4. Error handling for granting permission fails.

**Comment by crysan** [comment]
All right but how to deal with
<code>
    @Override
    public void onRequestPermissionsResult(int requestCode, String[] permissions, int[] grantResults) {
</code>
This procedure is not maintained in the Application. Only Activity.

**Comment by beeender** [comment]
That really depends on your App's structure.

I would prefer to have it in my first activity. And make sure the first activity is shown whenever the permission needs to be granted.

Or you can have a universal super activity to have the `onRequestPermissionsResult` defined there and others inherit from that. But I don't suggest that.

You can also use Fragment's `requestPermission` , see answers here http://stackoverflow.com/questions/32714787/android-m-permissions-onrequestpermissionsresult-not-being-called

**Comment by beeender** [comment]
And also, the `getExternalFilesDir` could return `null` if the sd card is not existing. So you also need some logic to check that.

**Comment by crysan** [comment]
Good.  I'll try to fragment.  On the results were reported later.  Thank you!

**Comment by crysan** [comment]
See what happened (drop while checking the SD card - we believe that it is):


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);
        checkRealm();
    }



    public void checkRealm(){
        boolean hasPermission = (ContextCompat.checkSelfPermission(this, Manifest.permission.WRITE_EXTERNAL_STORAGE) == PackageManager.PERMISSION_GRANTED);
        if (!hasPermission) {
            ActivityCompat.requestPermissions(this, new String[]{Manifest.permission.WRITE_EXTERNAL_STORAGE}, REQUEST_WRITE_STORAGE);
        } else {
            configRealm();
        }
    }



    @Override
    public void onRequestPermissionsResult(int requestCode, String[] permissions, int[] grantResults) {
        switch (requestCode) {
            case REQUEST_WRITE_STORAGE:
                // If request is cancelled, the result arrays are empty.
                if (grantResults.length > 0 && grantResults[0] == PackageManager.PERMISSION_GRANTED) {
                    configRealm();
                } else {
                    Toast toast = Toast.makeText(this, "Write permission to the external storage is needed for this app", Toast.LENGTH_LONG);
                    toast.show();
                    finish();
                }
                return;
            default:
                break;
        }
    }



    public void configRealm(){
        createFolders();

        RealmMigration migration = new RealmMigration() {
            @Override
            public void migrate(DynamicRealm realm, long oldVersion, long newVersion) {

                // DynamicRealm exposes an editable schema
                RealmSchema schema = realm.getSchema();

                if (oldVersion == 0) {
                    oldVersion++;
                }

                if (oldVersion == 1) {
                    oldVersion++;
                }

                if (oldVersion == 2) {
                    oldVersion++;
                }

                if (oldVersion == 3) {
                    oldVersion++;
                }

                if (oldVersion == 4) {
                    oldVersion++;
                }

                if (oldVersion == 5) {
                    oldVersion++;
                }

                if (oldVersion == 6) {
                    schema.get("News")
                            .addField("author_err", boolean.class);
                    oldVersion++;
                }
            }
        };

        if (myConfig == null) {
            myConfig = new RealmConfiguration.Builder(new File(func.getFolder("db")))
                    .name(getResources().getString(R.string.app_name_db) + ".realm")
                    .schemaVersion(7)
                    .migration(migration)
                    .build();
            Realm.setDefaultConfiguration(myConfig);
        }

        File fl = new File(func.getFolder("db") + "/" + getResources().getString(R.string.app_name_db) + ".realm");
        if ((int) ((fl.length()/1024)/1024) > 70) Realm.compactRealm(myConfig);

        realm = Realm.getDefaultInstance();
        db_count_all_author = realm.where(Authors.class).findAll().size();

        getFragmentManager().beginTransaction().replace(R.id.lContainer, new AuthorsFragment(), "AuthorsFragment").commit();
        getFragmentManager().executePendingTransactions();}


That's what happens.  When you first start the program all right.  When it zpkrytii and restarting an error


java.lang.RuntimeException: Unable to start activity 
java.lang.IllegalArgumentException: Configurations cannot be different if used to open the same file. 
                                                                                     Cached configuration: 
                                                                                     realmFolder: /storage/sdcard0/lala/Db
                                                                                     realmFileName : samlibreaderlike.realm
                                                                                     canonicalPath: /storage/sdcard0/lala/Db/lala.realm
                                                                                     key: [length: 0]
                                                                                     schemaVersion: 7
                                                                                     migration: MainActivity$2@41d40f10
                                                                                     deleteRealmIfMigrationNeeded: false
                                                                                     durability: FULL
                                                                                     schemaMediator: io.realm.DefaultRealmModuleMediator@751e370

**Comment by beeender** [comment]
Can you post the full log here? The log should print both configuration which are mismatched.

**Comment by crysan** [comment]
please email

**Comment by beeender** [comment]
To help@realm.io

**Comment by crysan** [comment]
send

**Comment by crysan** [comment]
316 line:
realm = Realm.getDefaultInstance();

**Comment by beeender** [comment]
From the log, the migration block you passed to the configuration is not the same. Please make the migration static and always use the same migration to create the `RealmConfiguration`

**Comment by crysan** [comment]
mmm... example please

**Comment by beeender** [comment]
```
static RealmMigration migration = new RealmMigration() { ... }
myConfig = new RealmConfiguration.Builder(new File(func.getFolder("db")))
                .name(getResources().getString(R.string.app_name_db) + ".realm")
                .schemaVersion(7)
                .migration(migration)
                .build();
```

**Comment by crysan** [comment]
YES!!!!!
Everything worked out!
Thank you!

**Comment by dalinaum** [comment]
@crysan Great. I'll close this issue. If you encounter further problems, please feel free to reopen or create a new issue. Thanks.
