### ISSUE TITLE
realm rx subscribe -> onComplete never call !!! 

### ISSUE THREAD

**Issue by rimidalv** [realm/realm-java#2010]
realm version - 0.87.1

        RealmResults<RealmPlace> realmPlaces = realm.where(RealmPlace.class).findAllAsync();
        realmPlaces.<RealmPlace>asObservable()
           
                .subscribe(result -> {
                               <some code> //call 2 times: the first with result.size() == 0; and the second with good size
                        },
                        Throwable::printStackTrace,
                        () -> {
                            Log.d("TAG", "onComplete"); //Never call !!!
                        }
                );

**Comment by cmelchior** [comment]
That is by design as the observable will emit a new RealmResult each time the query result is updated due to you writing changes to Realm. If you want a `onComplete` event you can do something like:

```
realmPlaces.asObservable()
  .filter(results -> results.isLoaded())
  .first()
  .subscribe(...)
```
That will give you the first loaded result from Realm and then call `onComplete`

**Comment by rimidalv** [comment]
It is work! like a charm, but it is MAGIC! I can understand .filter(...), but why first?

**Comment by cmelchior** [comment]
Because it converts a never-ending stream of Observables to one that only emit 1 item and then call `onComplete`. You can see the description here: http://reactivex.io/documentation/operators/first.html

**Comment by rimidalv** [comment]
Thank you!
