### ISSUE TITLE
Support for RealmQuery.isNotEmpty()

### ISSUE THREAD

**Issue by roughboy** [realm/realm-java#2014]
Current implementation only support RealmQuery.isEmpty(). In order to be consistent i.e. with  RealmQuery.isNull() and RealmQuery.isNotNull(), RealmQuery.isNotEmpty() should also be added.

**Comment by kneth** [comment]
@roughboy Nice catch

**Comment by dalinaum** [comment]
#2025 and #2028 resolved this. I'll close this issue.
