### ISSUE TITLE
Performance in removing objects

### ISSUE THREAD

**Issue by douglasjunior** [realm/realm-java#2015]
I'm having performance problems with Realm, and I wonder if I'm doing something wrong.

I'm removing about 6,000 objects using the `RealmResults.clear()`. My query is performed by a `@Index` property.

Entity:
```java
public class Foo extends RealmObject {
      @PrimaryKey
      private long id;
  
      @Index
      private long bar;
      // getters and setters
}
```
My code to remove:
```java
RealmResults<Foo> result = realm.where(Foo.class).equalTo("bar", barId).findAll();
result.clear();
```
When the `Foo` table has 7,000 records in total, the removal happens almost instantly. However, if the total is 300,000 records, it takes about 50 seconds to call the `clear()`.

The same problem I have to make "update" on several objects.

```java
RealmResults<Foo> result = realm.where(Foo.class).equalTo("bar", barId).findAll();
for (Foo foo : result) {
   foo.setValue(newValue);
}
```

I can do something to fix it?

*I'm using the Realm 0.87.1 with Android 4.2.2 on a Galaxy Tab 3 Lite.*

**Comment by beeender** [comment]
We might can accelerate `RealmResults.clear` much faster by calling clear with  `RemoveMode::unordered`. Let's see what can be done in Realm side

**Comment by douglasjunior** [comment]
Thanks for answering.

I would love to be able to contribute to the Realm, if there's anything I can do. I consider libraries and framework as part of my application and responsibility.

**Comment by rrrlasse** [comment]
@beeender I'm optimizing this now

**Comment by rrrlasse** [comment]
I've created https://github.com/realm/realm-core/pull/1428 for the core part of this

**Comment by dalinaum** [comment]
@beeender @rrrlasse Does it need to update `RealmResults.clear`? Otherwise, I think we can close this issue.

**Comment by beeender** [comment]
@dalinaum Let's close this when new core merged.

**Comment by dalinaum** [comment]
Sorry for several repoens.

**Comment by kneth** [comment]
Core 0.95.8 has been released and integrated for upcoming 0.87.3 release.

**Comment by douglasjunior** [comment]
Already available in 0.88.0-SNAPSHOT?

**Comment by kneth** [comment]
We will merged the changes from 0.87 to master (and releasing 0.88-SNAPSHOT) once 0.87.3. is released.

**Comment by douglasjunior** [comment]
I tested the version 0.87.3 and 0.88.0.

I performed the same procedure as before, and the speed of `realmResult.clear()` decreased from 50 to 40 seconds'.

Correct?

**Comment by cmelchior** [comment]
It sounds a bit from the measurements we had. @kneth  / @rrrlasse thoughts?

**Comment by rrrlasse** [comment]
From the Core side such a delete (with the given tables, columns and rows) it takes just a couple of seconds since core 0.95.8. So it's strange...

**Comment by douglasjunior** [comment]
Just remember that I'm excluding 6,000 records of a total of 300,000.

If I try to delete 6,000 of a total of 7,000 occurs instantly.

**Comment by kneth** [comment]
I'll reassign the issue to me, and I'll do a bit of measuring during the next days.

**Comment by douglasjunior** [comment]
OK thank you.

Let me know if you need help.

**Comment by douglasjunior** [comment]
I ran the same test (removing 6,000 of 300,000) on a smartphone Motorola Moto X2. I obtained the following results:

v0.87.2 -> 15 seconds
v0.87.3 -> 10 seconds

This smartphone has a quad-core 2.2GHz processor. While the Samsung Galaxy Tab 3 Lite has dual-core 1.2GHz.

**Comment by kneth** [comment]
@douglasjunior Thanks for the numbers. Removing one object takes 1.66 ms - hmmm. Even though Realms are unordered, objects are stored somewhere, and objects can be more or less scattered in memory. Can you tell us how you create the objects in the first place?

**Comment by douglasjunior** [comment]
My app creates a lot of data as it is a history of a seed planting process in agricultural machinery.

I'm creating fictitious data for the test, so I create data using a loop.

My model:
```java
public class Planting extends RealmObject {
     @PrimaryKey
     private long id;
     @Index
     private long plantingParentId;
     private RealmList<Line> lines;
     // others properties...
     // getters and setters
}
```
```java
public class Line extends RealmObject {
     @PrimaryKey
     private long id;
     @Index
     private long lineParentId;
     // others properties...
     // getters and setters
}
```
Creating fictitious data:
```java
            realm.beginTransaction();

            Planting planting = realm.createObject(Planting.class);
            // set properties on planting

            for (int i = 1; i <= 48; i++) {
                Line line = realm.createObject(Line.class);
                // set properties on line
                planting.getLines().add(line);
            }

            // It creates 6000 historical records for planting and each of the 48 lines.
            for (int i = 0; i < 6000; i++) { 
                // It does commit every 200 historical to free up memory
                if (i % 200 == 0) {
                    realm.commitTransaction();
                    realm.beginTransaction();
                }
                Planting plantingHistory = realm.copyFromRealm(planting, 0);
                plantingHistory.setPlantingParentId(planting.getId());
                // change some properties of plantingHistory
                realm.copyToRealm(plantingHistory);
                for (Line line : planting.getLines()) {
                    Line lineHistory = realm.copyFromRealm(line, 0);
                    lineHistory.setLineParentId(line.getId());
                    // change some properties of lineHistory
                    realm.copyToRealm(lineHistory);
                }
            }

            realm.commitTransaction();
```
And for removing:
```java
   RealmResult<Line> history = realm.where(Line.class).equalTo("lineParentId", line.getId());
   history.clear();
```

**Comment by kneth** [comment]
@douglasjunior Thanks, I'll use your code above to create a small benchmark.

**Comment by douglasjunior** [comment]
Sorry, I just add the code that removes planting history.

Thank you very much for your time.

**Comment by kneth** [comment]
Just for my understanding: you have 48 `Line` objects and 6000 `Planting` objects? And every `Planting` object is linked to all `Line` objects?

**Comment by douglasjunior** [comment]
My `Planting` has 48 `Lines` directly related. Both the `Planting` as the `Lines` I created history records.

Historical objects are clones of originals without relationships. Historical do not have relationships.

So I my test, I created 6,000 historical records of planting, and also 6,000 historical records of each of the 48 lines.

In the `realm.copyFromRealm(planting, 0);` is set `0`. In other words, relationships are not cloned.

If history do not have relationships, how do I know who owns the history?
History records only have the parent ID in "plantingParentId" and "lineParentId".

**Comment by kneth** [comment]
@douglasjunior We have translated your test into C++ in order to see where in the storage/query engine we might have bottlenecks.

**Comment by douglasjunior** [comment]
You are awesome. The attention the team pays is rare. Thank you so much.

I did more tests on another device. Samsung Galaxy Tab E with processor quad-core 1.2GHz.

v0.87.2 -> 32 seconds
v0.87.4 -> 15 seconds

**Comment by kneth** [comment]
In version 0.87.3 we did try to improve the performance of delete objects.

**Comment by douglasjunior** [comment]
Yes, I'm watching, so always do test in version 0.87.2 and current, to compare. :smile:

**Comment by kneth** [comment]
If you only wish to remove the historical objects (`Planting` objects with relationship to any `Line` objects - and `Line` objects to referenced by any `Planting` object), there is no elegant way to express it. You can manually track a historical objects by adding a boolean field.

By the way, deleting objects which are referenced (`Line` object referenced by `Planting` objects) does require updating the "parent" objects which - of course - will slow down the process.

**Comment by douglasjunior** [comment]
I need to control who the father is. Because I can have several registered `Planting`. Every working day the user starts a new `Planting`. Then each will have its historical `Planting`, and the `Lines` of this `Planting` will also have their histories.

So when the user wants to remove a `Planting` is also necessary to remove its `Lines` and historical.

**Comment by kneth** [comment]
Just curious, if you remove the `@Index` annotations, is the performance changed?

**Comment by douglasjunior** [comment]
I did the tests without `@Index` with my first equipment. Galaxy Tab 3 Lite dual-core 1.2 GHz.

Without `@Index`:

v0.87.2 -> 40 seconds
v0.87.4 -> 40 seconds

With `@Index`:

v0.87.2 -> 50 seconds
v0.87.4 -> 42 seconds

**Comment by beeender** [comment]
@douglasjunior We did some more optimization in `0.87.5`

According to my testing on a Sumsung GTS 7572 (Dual-core 1.2 GHz)
0.87.4 -> 1200 ms
0.87.5 -> 420 ms

Testing code: 

```java
public class Foo extends RealmObject {
    @Index
    private long bar;

    public void setBar(long bar) {
        this.bar = bar;
    }

    public long getBar() {
        return bar;
    }
}
```

```java
final Thread thread = new Thread(new Runnable() {
    @Override
    public void run() {
        long total = 0;
        long count = 0;
        while (true) {
            Realm realm = Realm.getInstance(MainActivity.this);
            realm.beginTransaction();
            realm.clear(Foo.class);
            for (int i = 0; i < 6000; i++) {
                Foo foo = new Foo();
                foo.setBar(1);
                realm.copyToRealm(foo);
            }
            for (int i = 0; i < 6000; i++) {
                Foo foo = new Foo();
                foo.setBar(0);
                realm.copyToRealm(foo);
            }
            realm.commitTransaction();
            RealmResults<Foo> results = realm.where(Foo.class).equalTo("bar", 1).findAll();
            System.gc();

            long start = System.nanoTime();
            realm.beginTransaction();
            results.clear();
            realm.commitTransaction();
            long end = System.nanoTime();
            long time = (end - start) / 1000 / 1000;
            total += time;
            count++;
            Log.e("TTT", "Elapsed time: " + total/count + "ms");
            realm.close();
        }
    }
});
thread.start();
```

I am closing this issue now, thanks a lot for the feedback!
