### ISSUE TITLE
 E/dalvikvm(29335): Could not find class 'io.realm.rx.RealmObservableFactory$1', referenced from method io.realm.rx.RealmObservableFactory.from

### ISSUE THREAD

**Issue by MADHUSUDAN-PARASHAR-SOJAT** [realm/realm-java#2017]

**Comment by dalinaum** [comment]
Hello, @MADHUSUDAN-PARASHAR-SOJAT. Could you post the full log here?

**Comment by MADHUSUDAN-PARASHAR-SOJAT** [comment]
import io.realm.RealmObject;
import io.realm.annotations.Ignore;
import io.realm.annotations.PrimaryKey;
import io.realm.annotations.RealmClass;
@RealmClass
public class TransactionRealm extends RealmObject{
	@PrimaryKey
	 private Integer             age;
	
   

  
    // Standard getters & setters generated by your IDE…
 
    public int    getAge() { return age; }
    public void   setAge(int age) { this.age = age; }
  
  
	

}

public class RegisterForm extends Activity implements OnClickListener{ 
	@Override
		protected void onCreate(Bundle savedInstanceState) {
			super.onCreate(savedInstanceState);
Realm realm = Realm.getInstance(this);
	   
		    realm.beginTransaction();
		    TransactionRealm transaction=realm.createObject(TransactionRealm.class);
		    transaction.setAge(11);
	       
	        realm.copyToRealm(transaction);
		    realm.commitTransaction();
		  
}
}

**Comment by dalinaum** [comment]
Can you share your project? To lk@realm.io ?

**Comment by cmelchior** [comment]
This seems to be the same issue as #2023, i'll close this one as a duplicate. Please provide any information in #2023
