### ISSUE TITLE
Dynamic type of RealmResults.

### ISSUE THREAD

**Issue by csnu17** [realm/realm-java#2019]
I want to get RealmResults that type of its depend on my condition. For example,

``` java
RealmResults result;
if (condition1) {
   result = realm.where(Item1.class).findAll();
} else {
   result = realm.where(Item2.class).findAll();
}
```

How can I achieve this?

**Comment by dalinaum** [comment]
Hello, @csnu17. How about the following code?

```
if (condition1) {
   RealmResults<Item1> result = realm.where(Item1.class).findAll();
   ...
} else {
   RealmResults<Item2> result = realm.where(Item2.class).findAll();
   ...
}
```

**Comment by csnu17** [comment]
But the code in each block maybe similar and I dont want to copy paste same code in other block condition. How can I achieve this?

**Comment by beeender** [comment]
@csnu17 You could consider to use java generic method for your same code.
https://docs.oracle.com/javase/tutorial/extra/generics/methods.html

**Comment by cmelchior** [comment]
@csnu17 Like @beeender said. This is not really Realm specific and you can use generics to accomplish what you want, e.g. using this method:

```
public <E extends RealmObject> RealmResults<E> query(Class<E> clazz) {
  return realm.where(clazz).findAll();
}
``

**Comment by csnu17** [comment]
Thank you.
