### ISSUE TITLE
Update realm

### ISSUE THREAD

**Issue by yaming116** [realm/realm-java#2022]
last version was 0.84.1,now i update to 0.87.1.
I have a error  `Invalid format of Realm file`,i need help, thx

`
java.lang.IllegalArgumentException:Illegal Argument: Invalid format of Realm file.
io.realm.internal.SharedGroup.createNativeWithImplicitTransactions(Native Method)
io.realm.internal.SharedGroup.<init>(SharedGroup.java:67)
io.realm.internal.SharedGroupManager.<init>(SharedGroupManager.java:47)
io.realm.BaseRealm.<init>(BaseRealm.java:76)
io.realm.Realm.<init>(Realm.java:126)
io.realm.Realm.createAndValidate(Realm.java:246)
io.realm.Realm.createInstance(Realm.java:231)
io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:114)
io.realm.Realm.getInstance(Realm.java:197)
com.xuehai.xhenglistbrush.db.user.UserDB.create_aroundBody0(UserDB.java:49)
com.xuehai.xhenglistbrush.db.user.UserDB$AjcClosure1.run(UserDB.java:1)
org.aspectj.runtime.reflect.JoinPointImpl.proceed(JoinPointImpl.java:149)
hugo.weaving.internal.Hugo.logAndExecute(Hugo.java:39)
`

**Comment by beeender** [comment]
Are you using encryption?

Can you please send your realm file to help@realm.io ?

**Comment by yaming116** [comment]
@beeender No use has been sent to your mailbox

**Comment by beeender** [comment]
@yaming116 Really sorry for the delay, we tried your Realm file, but cannot reproduce it... is it possible to share your project as well? Let me know if you cannot share the project, we can figure out other ways to solve it.

**Comment by yaming116** [comment]
Sorry, I may have committed a serious error, no update .so file.Thank you for your help.

**Comment by beeender** [comment]
Happy to hear it is not a problem!
