### ISSUE TITLE
public class RegisterForm extends Activity implements OnClickListener{   		@Override 		protected void onCreate(Bundle savedInstanceState) { 			super.onCreate(savedInstanceState);                         setContentView(R.layout.activity_register_form);  		   Realm realm = Realm.getInstance(this); 	    		    realm.beginTransaction(); 		    TransactionRealm transaction=realm.createObject(TransactionRealm.class); 		    transaction.setAge(11); 	        	        realm.copyToRealm(transaction); 		    realm.commitTransaction();                       realm.close(); } }   import io.realm.RealmObject; import io.realm.annotations.Ignore; import io.realm.annotations.PrimaryKey; import io.realm.annotations.RealmClass; @RealmClass public class TransactionRealm extends RealmObject{ 	@PrimaryKey 	 private Integer             age; 	             // Standard getters & setters generated by your IDE…       public int    getAge() { return age; }     public void   setAge(int age) { this.age = age; }       	  }

### ISSUE THREAD

**Issue by MADHUSUDAN-PARASHAR-SOJAT** [realm/realm-java#2024]

**Comment by MADHUSUDAN-PARASHAR-SOJAT** [comment]
public class RegisterForm extends Activity implements OnClickListener{ 

		@Override
		protected void onCreate(Bundle savedInstanceState) {
			super.onCreate(savedInstanceState);
                        setContentView(R.layout.activity_register_form);

		   Realm realm = Realm.getInstance(this);
	   
		    realm.beginTransaction();
		    TransactionRealm transaction=realm.createObject(TransactionRealm.class);
		    transaction.setAge(11);
	       
	        realm.copyToRealm(transaction);
		    realm.commitTransaction();
                      realm.close();
}
}


import io.realm.RealmObject;
import io.realm.annotations.Ignore;
import io.realm.annotations.PrimaryKey;
import io.realm.annotations.RealmClass;
@RealmClass
public class TransactionRealm extends RealmObject{
	@PrimaryKey
	 private Integer             age;
	
   

  
    // Standard getters & setters generated by your IDE…
 
    public int    getAge() { return age; }
    public void   setAge(int age) { this.age = age; }
  
  
	

}


01-04 06:00:38.189: E/AndroidRuntime(1226): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.letsgodutch/com.example.letsgodutch.RegisterForm}: java.lang.IllegalArgumentException: TransactionRealm is not part of the schema for this Realm

**Comment by dalinaum** [comment]
Since it seems duplicated to #2017, I'll close this issues.
