### ISSUE TITLE
Realm causes GC events when saving objects.

### ISSUE THREAD

**Issue by MinceMan** [realm/realm-java#2029]
A large performance problem that I'm running into is that when saving data in the background realm is causing memory churn creating a bunch of small GC events. This often interferes with scrolling causing the app to drop frames for no apparent reason to the user. In #1684 it was suggested that Realm could easily be updated to use an object pool there by mitigating the GC events.

Another possibly related issue is #1925

**Comment by beeender** [comment]
#2004 shoud fix this.

**Comment by cmelchior** [comment]
@MinceMan This is indeed related to https://github.com/realm/realm-java/issues/1925, i'll close this as an duplicate for now, but you can follow progress in #1925.
