### ISSUE TITLE
Reorganize/Rewrite Live Queries / Live Objects (Auto Refresh)

### ISSUE THREAD

**Issue by donnfelker** [realm/realm-java#2038]
Documentation on realm.io should mention RealmResults<E> and RealmObjects are live in a more prominent fashion. This is major value add that should be showcased more as it helps developers grok the understanding of what Realm does and how the threading works. Currently it is buried at the bottom of the documentation in the Best Practices. It is very easy to miss and needs more attention. 

Meaning that if an item is added to the Realm that satisfies the query then the RealmResults will now also contain that item (or deletion,etc). Same for RealmObject, if the item is updated/etc then it will be updated in real time on the UI thread. 

Of course, mention the Looper requirement.

**Comment by cmelchior** [comment]
Yes, that is very much needed.

**Comment by donnfelker** [comment]
Documentation updated from objc in order to reduce documentation churn for the time being.
