### ISSUE TITLE
javassist.NotFoundException: rx.Observable encountered when mocking Realm with Mockito and PowerMock

### ISSUE THREAD

**Issue by ephread** [realm/realm-java#2040]
I've been more or less following the [Unit Test example](https://github.com/realm/realm-java/tree/master/examples/unitTestExample) to unit test certain objects relying on Realm in my project. I have encountered an issue, when trying to mock the Realm objects using Mockito and PowerMock.

The tests crash, because the mocking engines can't find the “optional” Reactive Extensions, thus, the tests can't pass. :) I'm not sure it's entirely Realm's fault, but given that using PowerMock seems to be the recommended option, the crash probably shouldn't happen.

I've set up a quick and dirty sample, extracted from my project, to showcase the issue, you can find it [here](https://github.com/ephread/RealmRxCrash).

#### Steps to reproduce the issue
Fire up the project in Android Studio, make sure the Test Artifact is set to `Unit Test`, right click on the `ephread.com.realmrxcrash (tests)` package and run the JUnit tests.

The tests will crash with the following stack trace: https://gist.github.com/ephread/7baad3ad8e50b340d871

The crash can be resolved by adding the Reactive Extension dependency (`testCompile 'io.reactivex:rxjava:1.0.16'`) or reverting to Realm 0.86, but neither of those solutions seem very nice.

#### Environment

- Android Studio 1.4.1
- Realm 0.87.1
- OS X 10.11.2

**Comment by cmelchior** [comment]
Hi @ephread 
Thanks for the report. I suspect it is happening because RxJava is an optional dependency and JavaAssist (used by PowerMock) doesn't handle that very well.

If you do no want to add RxJava as a `testCompile` dependency, you can add a dummy class as described here instead: https://realm.io/docs/java/latest/#jackson-databind

**Comment by ephread** [comment]
Thanks for the tip @cmelchior!

I totally missed that part of the documentation, and a dummy class is probably the best option in my case. Since this issue has been reported to Jackson-databind, should we report the issue to javassist/PowerMock as well?

**Comment by cmelchior** [comment]
That is probably a good idea.

**Comment by cmelchior** [comment]
I created this issue on JavaAssist https://github.com/jboss-javassist/javassist/issues/70. In any case this is a problem outside the control of Realm unless we change the behaviour from optional dependency to required dependency, which at this point is unlikely.

Another work-around would be to only add `RxJava` to test configurations:

```
testCompile 'io.reactivex:rxjava:1.1.0'
androidTestCompile 'io.reactivex:rxjava:1.1.0'
```
