### ISSUE TITLE
RealmList and Collections.sort / Collections.swap operations

### ISSUE THREAD

**Issue by roughboy** [realm/realm-java#2041]
Is it allowed to make Collections operations on RealmList? I.e Collection.swap(realmList, fromIdx, toIdx) or Collections.sort(realmList, someCustomComparator) ?

**Comment by cmelchior** [comment]
Hi @roughboy 
Yes, that should work fine as collections just use the normal List interface (which RealmList supports). Only requirement is that it happens inside a transaction as you are modifying data.

```
realm.beginTransaction();
Collections.sort(realmList);
realm.commitTransaction();
```

**Comment by roughboy** [comment]
Thanks a lot!

**Comment by cmelchior** [comment]
No problem. Have fun
