### ISSUE TITLE
RealmList.set(int location, E object) returns current object instead of previous.

### ISSUE THREAD

**Issue by roughboy** [realm/realm-java#2044]
Implementation of List interface requires from `set(int location, E object)` operation to return object that was previously set at given index. 
https://docs.oracle.com/javase/7/docs/api/java/util/List.html#set(int,%20E)

The implementation of `RealmList.set(int location, E object)` has a bug - it returns current object, instead of the previous one. 
It can be easily observed by runing `Collections.swap(list, index1, index2);` (it uses set operation internally). Instead of objects being swapped, the same object is at index1 and index2 .

**Comment by cmelchior** [comment]
Ups, that is embarrassing. I just checked the source code and you are right.

**Comment by cmelchior** [comment]
Hi @roughboy 
A fix has been merged to master, so it should be available in a `-SNAPSHOT` release shortly.

**Comment by roughboy** [comment]
Nice, very fast fix - thank you!
