### ISSUE TITLE
RxJava isLoaded call needs to be clarified on documentation

### ISSUE THREAD

**Issue by jcarty** [realm/realm-java#2050]
Hey guys,

Great library!

Just a suggestion:

For RxJava, the documentation doesn't mention that you need to .filter() the observable returned from .asObservable() for isLoaded() to ensure the results/object have actually loaded.

It's shown in the example but not stated anywhere else.

Thanks!

**Comment by cmelchior** [comment]
Good idea. It could probably be better described.

**Comment by jcarty** [comment]
With that, would it make more sense to add the filter inside of asObservable to simplify things or would you rather the user know and handle that?

**Comment by cmelchior** [comment]
I would rather let the user handle that as there are use cases where you want RealmResults immediately even if they are not done loadng. You can create your own `RxObservableFactory` if you want to modify all Observables and add it through `RealmConfiguration.rxFactory()`

**Comment by jcarty** [comment]
That makes sense. Thanks.

**Comment by cmelchior** [comment]
The website documentation have been updated with this information.
