### ISSUE TITLE
No notifications triggered after sequence of disabling and enabling auto-refresh

### ISSUE THREAD

**Issue by roughboy** [realm/realm-java#2051]
I have following scenario: I create some realm results by runing a query
`mRealmItems = mRealm.where(RealmItem.class).findAll();`
and then add to it listener
`mRealmItems.addChangeListener(this);`
Listener makes notification when new item is added. After adding some items i disable auto-refresh:
`mRealm.setAutoRefresh(false)` and do some stuff that I dont want to be notified about.
Next i enable auto-notifications again:
`mRealm.setAutoRefresh(true);`, however after adding new item no notifications are triggered.

My assumption was that as long as I did not removed listener and auto-refresh is enabled the notifications will be trigerred. Unfortunately in this use case they are not. 

Is it intended behavior? It seems like bug to me.

**Comment by cmelchior** [comment]
It tend to agree. It looks like we create a new instance of our controller class when re-enabling auto-refresh, which will cause it to forgot all previous registered changelisteners. What do you think @nhachicha ?

**Comment by nhachicha** [comment]
Good catch @roughboy  we can improve the behaviour of `setAutoRefresh` by having a boolean per LocalThread to toggle the `HandlerController` (responsible to notifying the listeners)

**Comment by cmelchior** [comment]
@nhachicha I need this to fix #640 / #602 so I'll start looking into implementing this as part of the fix for them.

**Comment by cmelchior** [comment]
Fixed in 0.89
