### ISSUE TITLE
Realm Gradle plugin

### ISSUE THREAD

**Issue by csnu17** [realm/realm-java#2052]
I read https://realm.io/news/android-installation-change/ and want to install Realm by gradle plugin. I want to know that the build.gradle is Module.app or Project. Thank you.

**Comment by cmelchior** [comment]
You can see how it is used in our example projects:
Project gradle file: https://github.com/realm/realm-java/blob/master/examples/build.gradle
Module gradle file: https://github.com/realm/realm-java/blob/master/examples/introExample/build.gradle

**Comment by csnu17** [comment]
Thank you for your helping.

**Comment by Saketme** [comment]
Correct me if I'm wrong, but the gradle plugin dependency link mentioned in your [recent blog post](https://realm.io/news/android-installation-change/) is:

    classpath "io.realm:gradle-plugin:<version>"

and in your example build.gradle file, 

    classpath "io.realm:realm-gradle-plugin:<version>"

Which one of these two is the recommended one?

**Comment by wuwu2000** [comment]
Hey and sorry if this is the wrong "issue" to ask.
First at all: great job so far, loving realm :-)

I just want to know if it will be stil possible (easily) to build with maven without gradle?
Thanks for answer :+1:

**Comment by cmelchior** [comment]
We don't support Maven right now, since we didn't have any requests for it. We have talked about it though, but haven't really prioritised it. I just noticed we are actually lacking an issue for tracking interest for it, so i'll create one.
