### ISSUE TITLE
createObject io.realm.exceptions.RealmPrimaryKeyConstraintException: Value already exists: 0

### ISSUE THREAD

**Issue by LiuDeng** [realm/realm-java#2053]
DateJokeHeader header = diskRealm.createObject(DateJokeHeader.class);

01-10 01:27:00.768 22291-22291/com.qiuduanribao.joke W/System.err: io.realm.exceptions.RealmPrimaryKeyConstraintException: Value already exists: 0
01-10 01:27:00.768 22291-22291/com.qiuduanribao.joke W/System.err:     at io.realm.internal.Table.throwDuplicatePrimaryKeyException(Table.java:636)
01-10 01:27:00.768 22291-22291/com.qiuduanribao.joke W/System.err:     at io.realm.internal.Table.addEmptyRow(Table.java:365)
01-10 01:27:00.768 22291-22291/com.qiuduanribao.joke W/System.err:     at io.realm.Realm.createObject(Realm.java:661)

**Comment by dalinaum** [comment]
Hello. @LiuDeng 

When calling Realm.createObject(), it will return a new object with all fields set to the default value. In this case, there might be a conflict with an existing object whose primary key field is the default value.

You should create a standalone object, set values of the fields, and then copy it to Realm by copyToRealm() method.

```
DateJokeHeader header = new DateJokeHeader();
// set values of the fields
realm.beginTransaction();
realm.copyToRealmOrUpdate(header);
realm.commitTransaction();
```

See also https://realm.io/docs/java/latest/#primary-keys

**Comment by LiuDeng** [comment]
@dalinaum I found you have a private createObject function with primary_key as params it should be public

**Comment by cmelchior** [comment]
@LiuDeng That method is internal because it might change if we introduce composite primary keys. Is there any reason you cannot use the method suggested by @dalinaum ?

**Comment by LiuDeng** [comment]
@cmelchior  copyToRealmOrUpdate is okay and i saw the method and just ask why not make it  public
Thank you @cmelchior @dalinaum
