### ISSUE TITLE
Document how to enable NDK crashreporting

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#2056]
Point to one or more services that offers this, and link to blogposts/docs with instructions. Should be part of the getting started steps.

**Comment by donnfelker** [comment]
@cmelchior Can you point me to a couple of them? I can help write it up.

**Comment by cmelchior** [comment]
The only one I know of is Crashlytics: https://docs.fabric.io/android/crashlytics/ndk.html
That is probably also the best known though.

**Comment by donnfelker** [comment]
Isn't there an internal wiki thatbhas this info? I think MP mentioned it
one time. Is that correct?

**Comment by cmelchior** [comment]
We have a wiki, but i'm afraid it doesn't have that information :(

**Comment by donnfelker** [comment]
Lets sync up on this to see how I can help get this one done.

**Comment by donnfelker** [comment]
Document implemented here: https://github.com/realm/realm.io/pull/1662 Please provide feedback. I need to know the two values for `androidNdkOut` and `androidNdkLibsOut` which is mentioned in the Fabric guide: https://fabric.io/downloads/gradle/ndk & more detail: https://crashlytics.com/blog/the-wait-is-over-launching-crashlytics-for-android-ndk

**Comment by cmelchior** [comment]
Fixed by https://github.com/realm/realm.io/pull/1662
