### ISSUE TITLE
DynamicRealmObject.setObject should thrown meaningfull exception when columnIndex = -1

### ISSUE THREAD

**Issue by beeender** [realm/realm-java#2057]
Currently it will just crash in native code.

**Comment by beeender** [comment]
we could throw an exception in the `table.getColumnIndex`. But probably better to solve this in the object store since there quite a lot places need to be changed.

**Comment by cmelchior** [comment]
Closing as this fixed when we moved all schema logic to the Object Store. An `IllegalArgumentException` is being thrown now.
