### ISSUE TITLE
Contains function doesn't do case insensitive operation if contains special characters

### ISSUE THREAD

**Issue by tajchert** [realm/realm-java#2062]
Performing such search (case sensitive is set as false):
```realm.where(Employee.class).contains("name", searchQuery, false)```
with searchQuery containing special characters (tested on Polish "ę", "ą", "ł"...) does case sensitive search instead of case insensitive as requested (and working fine for Latin alphabet).

Example:
So for example I have Employee with name equal to "BRZĘCZYSZCZYKIEWICZ" and search with contains "brzę" wouldn't work even if case sensitivity is set to false, I need to search "BRZĘ" to make it work.

**Comment by cmelchior** [comment]
Yes, it is unfortunately one of our limitations currently. You can read more about it here: https://realm.io/docs/java/latest/#case-insensitive-queries

We are tracking this in https://github.com/realm/realm-java/issues/581 and https://github.com/realm/realm-java/issues/1031 already, so I'll close this as an duplicate. But please raise your voice in either of the two other issues so we can prioritise it accordingly.

A work-around can be to normalize your fields to latin-only characters and then do the query on those fields instead.

**Comment by Zhuinden** [comment]
A simple way to normalize such input :  http://stackoverflow.com/a/32717923/2413303
