### ISSUE TITLE
Add support for IN operator

### ISSUE THREAD

**Issue by mauriciogior** [realm/realm-java#2063]
I could not find a way to use the IN operator with realm. I was expecting a method with a signature similar to:

```java
public RealmQuery<RealmObject> in(String fieldName, Object[] values)
```

The only way I figured out how to simulate this operator is to iterate over the `contains` and `or` methods (it probably generates something like `WHERE x = ? OR y = ? OR z = ? ...`)

**Comment by donnfelker** [comment]
The `in' operator can be very useful. This question was raised before as well - please see @kneth's comments here: https://github.com/realm/realm-java/issues/1280

**Comment by cmelchior** [comment]
Yes, we agree that this could be a useful feature. We are already tracking it here https://github.com/realm/realm-java/issues/841, so i'll close this as an duplicate.
