### ISSUE TITLE
Realm sort by date behaved differenly on different phones

### ISSUE THREAD

**Issue by ChrisOHu** [realm/realm-java#2071]
HI guys,
When sorting RealmResorts by Date, the sorted order is opposite on different phones.

My test phones:
• Mi3                        Android 4.X
• Samsung Note 1   Android 4.X
• Nexus 5                 Android 6.0

Mi3 & Samsung Note has the same order, while Nexus 5 has a different opposite order.

Thanks~

**Comment by beeender** [comment]
First can you please confirm this? It sounds very very strange if it has this issue.

Can you please share more details? What is the data set? What does your sort call look like? What are the orders on Mi3 / Samsung / Nexus 5?

**Comment by SeanOceanHu** [comment]
If you could not duplicate this issue, please close this.

**Comment by beeender** [comment]
Close this for now since. @ChrisOHu If you have more details please let us know, we can reopen this issue :)
