### ISSUE TITLE
Illegal State: Object is no longer valid to operate on. Was it deleted by another thread?

### ISSUE THREAD

**Issue by liangzhitao** [realm/realm-java#2073]
After I delete an item from RealmResults, the last item stay in the first position,and I continued to delete, the app crashed. The issue is "Illegal State: Object is no longer valid to operate on. Was it deleted by another thread?" 

The following is my code : 
```Java
int position = viewHolder.getAdapterPosition();
List<User> usersInDb = realm.where(User.class).findAll();
for (User user : usersInDb) {
    Log.i(TAG, user.getAvatarUrl());
}
Log.i(TAG, "=====================");
userList.remove(position);
userAdapter.notifyItemRemoved(position);
userAdapter.notifyItemRangeChanged(position, userAdapter.getItemCount());
realm.executeTransaction(realm1 -> usersInDb.remove(position));
List<User> usersInDbAfterRemove = realm.where(User.class).findAll();
for (User user : usersInDbAfterRemove) {
    Log.i(TAG, user.getAvatarUrl());
}
Log.i(TAG, "=====================");
```

Thank you.

**Comment by beeender** [comment]
Where did the exception throw?

**Comment by liangzhitao** [comment]
When I excute `usersInDb.remove(position)` ，it throw this exception

**Comment by beeender** [comment]
When `RealmResults.remove` called, the elements order in the storage won't be maintained to make the operation faster. But in your case  `usersInDb` should be updated with that element removed and remaining elements keep the original level. `usersInDbAfterRemove` is a new query without any sorting method, which means it might have a different order from `usersInDb`.

You could sort two results to make them have the same order. See https://realm.io/docs/java/latest/#sorting

In your case, I don't really think you should be build a `userList` by yourself, instead, you can just use `RealmResults` as the data source of the adapter which is much easier to do.

**Comment by liangzhitao** [comment]
@beeender OK, Thank you for your reply. via your description, I have realized I made a mistake .
And I corrected my code to the following, and it worked correctly.

1. realm **dynamic changed**, I use RealmResults as data source, I don't need to deal with data source, when data source changes, I `notifyDataSetChanged` directly.

```Java
realm = Realm.getDefaultInstance();
realmResults = realm.where(User.class).findAll();
Log.i(TAG, String.valueOf(realmResults.size()));//size is 0 
userAdapter = new UserAdapter(realmResults, this);
......
Observable.merge(getObservables(users))
.subscribe(users2 -> {
    circularProgressBar.setVisibility(View.GONE);
    userAdapter.notifyDataSetChanged();//don't need to deal with data source, notifyDataSetChanged directly
}, Throwable::printStackTrace);

```

2. The same reason , when I delete an item, dealing with `RealmResult` is equal to deal with `List` and `SQLite` before.
```Java
int position = viewHolder.getAdapterPosition();
realm.executeTransaction(realm1 -> realmResults.remove(position));
userAdapter.notifyItemRemoved(position);
userAdapter.notifyItemRangeChanged(position, userAdapter.getItemCount());
```

Thank you very much!

**Comment by kneth** [comment]
I'm happy to hear that you get it working. I'm closing the issue.

**Comment by shahid650** [comment]
Answer: 
I got these errors , and While the solution was simple.
1- java.lang.IllegalStateException: Object is no longer managed by Realm. Has it been deleted?
2-  ThrowingException 8, Object is no longer valid to operate on. Was it deleted by another thread?, .
11-19 00:19:02.146 21759-21932/zeroturnaround.org.jrebel4androidgettingstarted E/REALM_JNI: Exception has been throw: Object is no longer valid to operate on. Was it deleted by another thread?

The Bad Code:
  if (subServiceId != null && !subServiceId.isEmpty()) {
                    mSubServiceModelDelete.setDeleted(true);
                    realm.copyToRealmOrUpdate(mSubServiceModelDelete);
                } else {

                    mSubServiceModelDelete.deleteFromRealm();
                    Log.d("TAG", "Service is Deleted from database.." + mSubServiceModelDelete.getSubservicesSubservicename());
                }

The Good and Error Free Code: 
  if (subServiceId != null && !subServiceId.isEmpty()) {
                    mSubServiceModelDelete.setDeleted(true);
                    realm.copyToRealmOrUpdate(mSubServiceModelDelete);
                } else {
                    Log.d("TAG", "Service is Deleted from database.." + mSubServiceModelDelete.getSubservicesSubservicename());
                    mSubServiceModelDelete.deleteFromRealm();
                }



So that was the Solution For This Error, This Was Error, as i was accessing deleted object after deleting it. LOL
Happy Coding :) :)

**Comment by lbx2015** [comment]
If we had not using the RealmResults directly in adapter, we need to mannualy update the adapter's data set after changed. This fix my issue.

**Comment by shaunty21** [comment]
I had the Same issue but when i deleting the last item row of recyclerAdapter it throws error like:
Object is no longer valid to operate on. Was it deleted by another thread?

Can Anyone tell me the Solution?

these my delete function:

 public void removeItem(String date, String id, int position) {
        DatabaseManager.getInstance().deleteSymptomDatebyId(date, id);
        symptomsDbModels.remove(position);
        notifyDataSetChanged();

        if (symptomsDbModels.size() == 0) {
            hidefab.hideFab();
        }
    }

**Comment by shaunty21** [comment]
i'm using RealmRecyclerAdapter but at the time of deletetion it gets me same error obj is no longer valid..

public class SymptomDataAdapter extends RealmRecyclerViewAdapter<SymptomsDbModel, SymptomDataAdapter.ViewHolder> {
    Context context;
    ArrayList<SymptomsDbModel> symptomsDbModels;
    Gson gson;
    Hidefab hidefab;
    StringBuilder stringBuilder;

    public SymptomDataAdapter(Context context, @Nullable OrderedRealmCollection<SymptomsDbModel> data) {
        super(context, data, true);
        this.context = context;
//        this.symptomsDbModels = symptomsDbModels;
        gson = new Gson();
        hidefab = (Hidefab) context;
    }

**Comment by Zhuinden** [comment]
That's because you have a `symptomsDbModels` instead of using `getData()`

**Comment by shaunty21** [comment]
@Zhuinden I'm Using RealmRecyclerAdapter but it also gives me error like Object is no longer Valid. Was it deleted bt it's another thread?

didn't get the Proper Solution? Can u plz help him out?

**Comment by Zhuinden** [comment]
As I said, there shouldn't be a `ArrayList symptomsDbModels`  inside RealmRecyclerViewAdapter.

You should be using `getData()` instead of wherever you use `symtomsDbModels`.

**Comment by shaunty21** [comment]
@Zhuinden I'm Using model= getItem(position) in onBindViewHolder to delete data on Realm but it also gives me error same as Above.
//Activity
 mCustomCalendar.setCalendarListener(new CalendarListener() {
            @Override
            public void onDateSelected(Date date) {
                if (!CalendarUtils.isPastDay(date)) {
                    SimpleDateFormat mdf1 = new SimpleDateFormat("dd-MMM-yyyy");
                    selectedDate = mdf1.format(date);

                    symptomList1 = DatabaseManager.getInstance().getSymptoms(selectedDate);
                    LoggerGeneral.info("SelectDate==>" + selectedDate + "---" + symptomList1.size());

                    if (symptomList1 != null && symptomList1.size() != 0) {
                        dialog = new Dialog(context);
                        dialog.requestWindowFeature(Window.FEATURE_NO_TITLE);
                        dialog.setContentView(R.layout.symptoms_dialog);

                        dialog.getWindow().setBackgroundDrawable(new ColorDrawable(Color.TRANSPARENT));
                        dialog.setCancelable(false);
                        Window window = dialog.getWindow();
                        WindowManager.LayoutParams wlp = window.getAttributes();

                        wlp.gravity = Gravity.CENTER;
                        wlp.flags &= ~WindowManager.LayoutParams.FLAG_BLUR_BEHIND;
                        window.setAttributes(wlp);
                        dialog.getWindow().setLayout(ViewGroup.LayoutParams.MATCH_PARENT, ViewGroup.LayoutParams.MATCH_PARENT);
                        dialog.getWindow().getAttributes().windowAnimations = R.style.CustomDialogTheme;

                        recyclerView = (RecyclerView) dialog.findViewById(R.id.recyclerview1);
                        recyclerView.setHasFixedSize(true);
                        recyclerView.setLayoutManager(new LinearLayoutManager(context, LinearLayoutManager.VERTICAL, false));

                        adapter = new SymptomDataAdapter(context, symptomList1);
                        adapter.setCallbackClickListener(Symptom_Logbook_Home.this);
                        recyclerView.setAdapter(adapter);
                        TextView tv_name = (TextView) dialog.findViewById(R.id.tv_name);
                        TextView tv_date = (TextView) dialog.findViewById(R.id.tv_date);

                        tv_name.setText("Symptoms");
                        tv_name.setTextColor(getResources().getColor(R.color.app_black));
                        tv_date.setText(selectedDate.toString());

                        iv_cancel = (ImageView) dialog.findViewById(R.id.iv_cancel);
                        iv_cancel.setOnClickListener(new View.OnClickListener() {
                            @Override
                            public void onClick(View v) {
                                dialog.dismiss();
                            }
                        });

                        dialog.show();
                    }

//Adapter Constructor
 public class SymptomDataAdapter extends RealmRecyclerViewAdapter<SymptomsDbModel, SymptomDataAdapter.ViewHolder> {
    Context context;
    RealmResults<SymptomsDbModel> symptomsDbModels;
    private final ViewBinderHelper binderHelper = new ViewBinderHelper();
    StringBuilder stringBuilder;
    Gson gson;
    private Callback callback;

    public SymptomDataAdapter(Context context, RealmResults<SymptomsDbModel> symptomsDbModels) {
        super(symptomsDbModels, true);

        this.context = context;
        this.symptomsDbModels = symptomsDbModels;  
    }

//onBindViewHolder
  @Override
    public void onBindViewHolder(@NonNull ViewHolder holder, int position) {
        final SymptomsDbModel symptomsDbModel = getItem(position);
        holder.textData.setText(symptomsDbModel.getTitle());

//Delete Functionality
holder.btn_delete.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {
                DatabaseManager.getInstance().deleteSymptomDatebyId(getData().get(position).getDatevalue(), getData().get(position).getId());
                LoggerGeneral.info("DataSize==>" + symptomsDbModels.size());
                if (symptomsDbModels.size() == 0) {
                    if (callback != null) {
                        callback.checkData();
                    }
                }
            }
        });

**Comment by shaunty21** [comment]
As per my assumption, the main problem is that recyclerAdapter get Perform accurate operation, but behind activity doesn't get refreshed when click on any dates on Calendar error occurs like:- Object is no longer valid.Was it deleted by another Thread?
Is that wr8 or wrng doesn't know, but it gets happen wr8 now So is there a solution to that?
