### ISSUE TITLE
Why dataBase can't store to local????like store mem. 

### ISSUE THREAD

**Issue by zhoumingliang** [realm/realm-java#2075]

**Comment by cmelchior** [comment]
Please see https://github.com/realm/realm-java/blob/master/CONTRIBUTING.md#filing-issues when creating issues. That way it is easier to help you.

**Comment by beeender** [comment]
@zhoumingliang Did you get your issue solved? Or can you please supply more details about your issue? thanks!

**Comment by cmelchior** [comment]
Closing this issue due to no response.
