### ISSUE TITLE
Stetho/chrome database viewer

### ISSUE THREAD

**Issue by danielgomezrico** [realm/realm-java#2078]
I am not able to see the database though chrome with https://github.com/facebook/stetho.
With works for sql ones, will be cool to have it here.

**Comment by cmelchior** [comment]
Have you tried https://github.com/uPhyca/stetho-realm by @zaki50 ?

**Comment by kokeroulis** [comment]
@danielgomezrico Be sure that you are using the com.uphyca:stetho_realm:0.8.0 version. There was an issue with the 0.7.2 stetho and realm 0.8.6. The inspector was crashing because the api has changed and the code related to the reflaction was wrong...

https://github.com/uPhyca/stetho-realm/issues/9

**Comment by danielgomezrico** [comment]
Yeah but it is not working, tried `0.8.0` and stetho `1.2.0` and realm `0.87.2`

**Comment by zaki50** [comment]
`stetho-realm 0.8.0` and `stetho 1.2.0` and `Realm Java 0.87.2` is working on my phone.

As I commented https://github.com/uPhyca/stetho-realm/issues/8#issuecomment-172022163 , can you try https://github.com/zaki50/realm_file_viewer_by_stetho ?

**Comment by zaki50** [comment]
Hi @danielgomezrico

not yet working?
Can you share the code with us help? Please send the project to @realm.io if possible.

**Comment by andreinass** [comment]
Hello.

This is not working for me as well.

I don't know if this have something to do with realm config. I'm setting my own config for realm and setting this as default. 

I have a database called "[filename].realm" and configuring Stetho like documentacion said:

  Stetho.initialize(
                    Stetho.newInitializerBuilder(this)
                            .enableDumpapp(Stetho.defaultDumperPluginsProvider(this))
                            .enableWebKitInspector(RealmInspectorModulesProvider.builder(this)
                                    .withFolder(getCacheDir())
                                    .withMetaTables()
                                    .withDescendingOrder()
                                    .build())
                            .build());

            OkHttpClient client = new OkHttpClient();
            client.networkInterceptors().add(new StethoInterceptor());


If someone has any news regarding this please share.

**Comment by zaki50** [comment]
@andreinass can you share the project with us?

**Comment by cmelchior** [comment]
Closing due to no response

**Comment by morder** [comment]
Didn't work with stetho 1.4.1, stetho_realm:2.0.0, realm 2.2.0
Shows empty tables and same tables in all databases
https://gyazo.com/3cdec1e76ab56a9f1d91c903b0883c44

**Comment by Zhuinden** [comment]
Paging @zaki50 although you could report this issue on Stetho-Realm instead
