### ISSUE TITLE
Combined primary key，How to do？

### ISSUE THREAD

**Issue by yuwu** [realm/realm-java#2088]
Combined primary key，How to do？

**Comment by beeender** [comment]
We don't support it right now, to see the progress of this issue #1129 

But one workaround is you can use a `String` field as the `PrimaryKey` and combine multi keys together into a string.

**Comment by cmelchior** [comment]
Closing this issue as it is an duplicate of #1129. Follow #1129 for updates on this issue.

**Comment by vipulpurohit** [comment]
How can I combine multi keys if my object is creating through webservice?
Gson creating realm object automatically.
