### ISSUE TITLE
Switch from a Synchronous Transaction to an Asynchronous Transaction

### ISSUE THREAD

**Issue by rhonyabdullah** [realm/realm-java#2097]
According to [this](https://realm.io/docs/java/0.87.2/#preventing-application-not-responding-errors-anrs) realm doc.section, realm are advise to perform all "Realm write" operations on a background thread (not Android’s main thread), is that safe if i change directly to Asynchronous in entirely transaction ? which mean i will never use the synchronous transaction during the development.

**Comment by kneth** [comment]
I'm not sure what you mean by safe.

A write transaction is a blocking operations i.e., only one write operation can execute at a time and others  will wait. Moreover, write transactions involve I/O activity, so we recommend that you perform most transactions not on the main thread.

Of course, async transactions might be a bit more complex to use, but to simplify your code, you can use [`executeTransaction()`](https://realm.io/docs/java/latest/#asynchronous-transactions).

**Comment by SarthakM9** [comment]
Hello Realm Team,

I have a similar question:

Suppose I declare a method containing some database operation.
What's the better approach: declaring an asynchronous transaction in the method or declaring a synchronous transaction.
I personally feel that the latter provides more flexibility, since now I have the option to run it in the same thread as well as another thread!
what do you guys suggest?
Thanks!

**Comment by Zhuinden** [comment]
Generally I make a "realm repository" which does not manage transactions at all, just the writes. The writes are managed by whatever thread is trying to write that way, although I prefer to do these things with synchronous transaction on background thread.

**Comment by SarthakM9** [comment]
@Zhuinden thanks for your time! :)
I also follow a similar pattern and strategy. :)

**Comment by rhonyabdullah** [comment]
Just as reminder [Closing Realm Instance](https://realm.io/docs/java/latest/#closing-realm-instances) @SarthakM9

**Comment by android-bash** [comment]
> ```java
> repository
> ```



> Generally I make a "realm repository" which does not manage transactions at all, just the writes. The writes are managed by whatever thread is trying to write that way, although I prefer to do these things with synchronous transaction on background thread.
> 
> ```java
>      try(Realm r = Realm.getDefaultInstance()) {
>          r.executeTransaction(realm -> {
>              // do many writes
>              repository.insertOrUpdate(realm, blah);
>              otherRepository.insertOrUpdate(realm, bleh);
>          });
>      }
> ```

Yeah a good one. Can you post some more info on having a separate repository and running this on background thread please?

**Comment by Zhuinden** [comment]
See https://github.com/Zhuinden/simple-stack/blob/f28fcae66287dbb92faefdc905cd2901dd3e7e8d/simple-stack-example-mvp-fragments/src/main/java/com/zhuinden/simplestackdemoexamplefragments/data/repository/TaskRepository.kt
