### ISSUE TITLE
createOrUpdateObjectFromJson throw RealmPrimaryKeyConstraintException: Value already exists: 

### ISSUE THREAD

**Issue by Ralphilius** [realm/realm-java#2098]
I've tried with `createOrUpdateObjectFromJson` using `String json` on 2nd parameter and got this error:

	io.realm.exceptions.RealmPrimaryKeyConstraintException: Value already exists: 
	at io.realm.internal.Table.throwDuplicatePrimaryKeyException(Table.java:636)
	at io.realm.internal.Table.addEmptyRow(Table.java:360)
	at io.realm.Realm.createObject(Realm.java:661)
	at io.realm.RealmFavouriteRealmProxy.createOrUpdateUsingJsonObject(RealmFavouriteRealmProxy.java:352)
	at io.realm.DefaultRealmModuleMediator.createOrUpdateUsingJsonObject(DefaultRealmModuleMediator.java:110)
	at io.realm.Realm.createOrUpdateObjectFromJson(Realm.java:506)
	at io.realm.Realm.createOrUpdateObjectFromJson(Realm.java:565)

Isn't it supposed to update rather than `createObject`? My RealmObject has a `PrimaryKey` which also exists in json string.

Anything related to https://github.com/realm/realm-java/issues/993?

I am using `0.87.2` version.

**Comment by cmelchior** [comment]
Hmm, that does sounds strange. Can you post the JSON string + your Realm class?

**Comment by Ralphilius** [comment]
@cmelchior I think I got the issue. I use Gson with JSONObject which added `nameValuePairs` to the json string. But the thing is it should not even add the json into database, right?

	public class RealmFavourite extends RealmObject {

		@PrimaryKey
		private String objectId;

		private String locationName;
		private String preview;
		private long favouritedAt;
		private long createdAt;
		private long updatedAt;
		private long dateTaken;
		private int widthOriginal;
		private int heightOriginal;
    //Setters & getters...
    }

JSON String:

    {"nameValuePairs":{"favouritedAt":1452946480417,"updatedAt":1451138188995,"dateTaken":1444608000000,"preview":"http://files.parsetfss.com/6fa3fa17-ac46-4a14-841d-2ff06def20ad/tfss-71bd1108-d32b-4232-b984-15d8cde8993e-21600321693_3f186a57c2_o.jpg","createdAt":1449754749621,"objectId":"GSuDXBUaNh","widthOriginal":1600,"locationName":"Australia","heightOriginal":1067}}

**Comment by beeender** [comment]
Yes, you should pass the `JSONString.get("nameValuePairs")` to the `createOrUpdateObjectFromJson`

**Comment by beeender** [comment]
@Ralphilius I hope your issue is solved. I am closing this now. Feel free to reopen it if necessary :)
