### ISSUE TITLE
0.88.0-SNAPSHOT not found

### ISSUE THREAD

**Issue by cmonfortep** [realm/realm-java#2099]
Trying to execute the examples, I'm getting an error related with the version 0.88.0-SNAPSHOT.

I've checked jcenter website and I don't see this version: https://bintray.com/realm/maven/realm-gradle-plugin/view

**Comment by dalinaum** [comment]
Hello @cmonfortep. Please run `./gradlew installRealmJava` on your project root folder.

**Comment by cmelchior** [comment]
@cmonfortep 
The `-SNAPSHOT` versions are not on JCenter but on OJO. If you cloned our repository, you need to either call `installRealmJava` or add the following to the `examples/build.gradle`

```
    repositories {
       mavenLocal()
       jCenter()
       maven {
            url 'http://oss.jfrog.org/artifactory/oss-snapshot-local'
        }
   }
```

**Comment by cmonfortep** [comment]
Thanks!

I added the maven repo to the build.gradle and it's working.
