### ISSUE TITLE
Apparent memory leak with query on background Looper thread

### ISSUE THREAD

**Issue by whoney** [realm/realm-java#2100]
When a query is executed on a background thread with associated Looper, in a usual way like:

```java
RealmResults<> results = realm.where (Something.class).....findAll ();
```

Realm will retain a reference to every RealmObject in the result set, in the order to (possibly) update the object when a change happens to the underlying realm - which is correct behavior.

However, there is no such method as RealmResults.close or anything similar. If we reuse the same Realm instance and run the query again, producing new RealmResults and dropping the reference to the old one, strong references to the RealmObjects seem to be retained and the heap grows uncontrollably, eventually leading to OOM - in my specific case, with a dataset of about 30k objects, it is enough to rerun the query only about 10-20 times before hitting OOM (Realm 0.87.2, on Android emulator API 23).

I've tried both asynchronous queries with listeners (detaching them of course) and synchronous, with the same OOM result. So far the only way to avoid OOM in my specific case is to create a new Realm instance before running the query and closing it after retrieving the results. It works acceptably but comes with a performance impact due to creating and closing Realm instance; also, it is not possible to use Realm's auto-update feature with such workaround.

How to reproduce:

1. Create a reasonably large dataset (30k simple objects were enough in my case, no relationships etc);
2. Create a background thread with an associated Looper;
3. Create Realm instance in the background thread;
4. Periodically (e.g. on a button press) run a query against this dataset in the background thread (passing a message to the thread via Handler to initiate the query);
5. Feed the results to the UI thread by using Realm.copyFromRealm on the RealmResults, but don't close the Realm instance;
6. Wait for OOM.

There seems to be no difference whether the query is synchronous or asynchronous. Just before OOM, heap dump shows an excessive amount of RealmObjects being referred to by HandlerCallback associated with the background thread as described above. At the same time, there are no stale instances of RealmResults (other than the "last" one), indicating that they're properly collected by GC, while RealmObjects are not.

Am I missing something obvious or is this indeed a bug/unexpected behavior?

**Comment by beeender** [comment]
Hi, how did you use those `RealmObject`s in the results? Any references to them not freed? Can you share the project with us?

**Comment by whoney** [comment]
I was copying the objects from RealmResults by using Realm.copyFromRealm (whatever returned from the query) and discarding the reference (nullifying, just to be safe) to the original RealmResults afterwards. Result of the copy was being passed on to the UI thread for display by means of a Handler; it worked correctly, and the only issue was an OOM after a few iterations. Let me stress it again that creating a new, fresh Realm instance for each iteration and closing it after the query made the problem go away.

For the sake of completeness, I've also tried to place the objects returned by Realm.copyFromRealm into Guava's ImmutableList and discard the original list; this seemed to make no difference. 

I can't share the project as it is, but I'll try to prepare a minimal working example for reproducing the issue. Of course, it's always a possibility that there's a memory leak somewhere in my code, or I might be missing something obvious.

**Comment by diegomontoya** [comment]
@whoney. Are you actually copying all 30K rows of RealmObject via copyFromRealm into java memory on each iteration of your query execution and then passing it to the UI thread for rendering? Have you tried avoiding this huge memory waste and just executing the query on UI thread and let you render/list/ui item use the RealmResult directly?

**Comment by whoney** [comment]
@diegomontoya My original intent was to process the query results before handing them over to the UI thread, filtering and sorting them for geolocation, as Realm cannot perform geospatial queries yet. I am aware of various geohashing algorithms; however, my naive approach seemed to work well enough, and the heap usage stays typically under 20 Mb for the entire app after applying the workaround described above. There is probably a better way of doing it (always!); however, I'm a little bit worried that I may have accidentally stumbled upon a usage pattern where RealmObjects aren't properly collected by GC. The same approach on iOS works apparently nice, without any obvious memory leaks detected.

**Comment by beeender** [comment]
@whoney How is your minimal example going on? Or is it possible that just share some code piece for below:

> Periodically (e.g. on a button press) run a query against this dataset in the background thread (passing a message to the thread via Handler to initiate the query);
> Feed the results to the UI thread by using Realm.copyFromRealm on the RealmResults, but don't close the Realm instance;

The data structure of your model object doesn't matter. I want to have a look at the logic of "query", "usage of RealmResults".

**Comment by cmelchior** [comment]
Closing due to no response.
