### ISSUE TITLE
Combine data from two table into new table

### ISSUE THREAD

**Issue by rshah** [realm/realm-java#2101]
I'm creating a new class to combine two tables into one table.
For example i have UserTable and DomainTable, i want to combine into AccountTable.
```Java
class AccountTable extends RealmObject {
     UserTable user;
     DomainTable domain;
}
```
I can create the new table, but i don't understand how to populate the data into AccountTable using new migration API.
Any clue how to do this?
the 'transform' seems only operate on one table.

**Comment by rshah** [comment]
Not sure if this is the best method.
But i managed to populate the data into AccountTable by using something like
```Java
        RealmResults<DynamicRealmObject> userResults = realm.allObjects("UserTable");
        if (userResults.size() > 0) {
            for (DynamicRealmObject user : userResults) {
                DynamicRealmObject account = realm.createObject("AccountTable");
                ...
                account.set("user", user);
            }
        }
```

**Comment by cmelchior** [comment]
Hi @rshah 
Yes, the `transform` method does not work across multiple classes, so just using a normal query and populate the new objects yourself as you are doing would be the way to go.
