### ISSUE TITLE
0.88-snapshot-2016-01-13: "does support null values" for a primitive "int" field?

### ISSUE THREAD

**Issue by diegomontoya** [realm/realm-java#2105]
dStatus is an "indexed" "integer" field. We are migration from 0.84.2 realm lib to realm-android-0.88.0-20160113.060756-31 snapshot and got the following crash from one of our users.

Non-fatal Exception: io.realm.exceptions.RealmMigrationNeededException: Field 'dStatus' does support null values in the existing Realm file. Use corresponding boxed type for field 'dStatus' or migrate using io.realm.internal.Table.convertColumnToNotNullable().
       at io.realm.MyRealmProxy.validateTable(MyRealmProxy.java:1146)
       at io.realm.MyRealmMediator.validateTable(MyRealmMediator.java:47)
       at io.realm.Realm.initializeRealm(Realm.java:297)
       at io.realm.Realm.createAndValidate(Realm.java:265)
       at io.realm.Realm.createInstance(Realm.java:244)
       at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:114)
       at io.realm.Realm.getInstance(Realm.java:200)

We have another captured crash with exact same type of message but for a different realm db/table. Both tables in this and previous comment went through migration adding an int field.

Both "int" fields happens to the the last column in each table if that is relevant.

**Comment by diegomontoya** [comment]
This is a bug caused by migration code using .addField() where you are adding a Integer.class field but not adding a FieldAttribute.Required attribute.

This should be implicit and not required for PRIMITIVE types. But the bug is that if you don't pass in FieldAttribute.Required for table.addField(), it will set the field as "nullable" even if type is PRIMITIVE.

**Comment by diegomontoya** [comment]
@cmelchior I accidentally closed the first issue. Check my comment above for bug source.

**Comment by beeender** [comment]
@diegomontoya If you want to add a `int` field, you should call `addField(int.class)` instead of `addField(Integer.class). then the field won't be nullable.

**Comment by diegomontoya** [comment]
@beeender You're right. Ahhh. My bad.

**Comment by beeender** [comment]
@diegomontoya I am closing this issue now. Let me know if there is further questions! :beers:
