### ISSUE TITLE
Nested transactions are not allowed. Use commitTransaction() after each beginTransaction().

### ISSUE THREAD

**Issue by thanhtranduc** [realm/realm-java#2111]
In my case, I want to do 2 task parallel, the first task is doing so the second task is beginning with beginTransaction. How to access database separetly??
having more question, pls tell me, How to see change log version realm?

**Comment by beeender** [comment]
What do you mean "access database separately" ? Access db in different threads?

And what does `change log version realm` mean? You mean https://github.com/realm/realm-java/blob/master/changelog.txt this ?

**Comment by thanhtranduc** [comment]
thank you for share change log :) the first issue I mean access db in many different background thread :)

**Comment by beeender** [comment]
For using Realm across threads, it really depends on what do you want to do.

The most common case is that you want to offload some db operations from UI thread, and the best choice would be using Realm's async query and async transaction. You can see docs https://realm.io/docs/java/latest/#asynchronous-queries and https://realm.io/docs/java/latest/#asynchronous-transactions .

If you just want to use Realm in another thread, just open a Realm instance in that thread, and close it when done. Just like using it in the UI thread. Some more docs worth to read: https://realm.io/docs/java/latest/#using-a-realm-across-threads .

**Comment by khangpv202** [comment]
in my case, i have two parallel threads, thread1: beginTransaction(), then delay 30 second ->commitTransaction, after thread1 call beginTransaction, thread2 call beginTransaction and the error message is "Nested transactions are not allowed. Use commitTransaction() after each beginTransaction().".

**Comment by cmelchior** [comment]
You are only getting that error if you are starting two transactions on the same thread. Are you sure that thread1 and thread2 are not the same? You can e.g. check it with `Thread.currentThread().getName()`

**Comment by thanhtranduc** [comment]
We create the first job using AsynTask and another job using thread pool. As you know I check it with 
Thread.currentThread().getName() and Thread.currentThread().getId(). the result is two thread not the same :) (In my project using to threadFactory create threadPool support for sync up data and Using asynTask to get data from local database to view)

**Comment by thanhtranduc** [comment]
Hi my friend maybe that is not issue from Realm, I found the bug in my code without Realm issue :)
