### ISSUE TITLE
Replace RealmList content

### ISSUE THREAD

**Issue by rshah** [realm/realm-java#2117]
How to properly replace the content of books?
```Java
class User extends RealmObject {
    private RealmList<Book> books;
}
```
I'm trying to sync the books content from server.
So i did something like below(in Kotlin)
```Kotlin
realm.beginTransaction()
for (i in user.books.indices) {
    user.books[i].removeFromRealm() // Got exception java.lang.ArrayIndexOutOfBoundsException
}

for (book in newBooksFromServer) {
    val bookRealm = realm.createObject(Book::class.java)
    bookRealm.name = book.name
    bookRealm.bookId = book.bookId
    user.books.add(bookRealm)
}
realm.commitTransaction()
```

But i got java.lang.ArrayIndexOutOfBoundsException when doing removeFromRealm.
I'm using 0.87.2 version of Realm.

**Comment by zaki50** [comment]
Hi @rshah 

What is `space.projects.indices`?

**Comment by rshah** [comment]
Ah sorry, i edited the codes it should be user.books.indices.

**Comment by zaki50** [comment]
When you call `user.books[i].removeFromRealm()`, the `user.books` is also updated and the length reduces.

One solution is always removing the first object like:
```
while (!user.books.isEmpty()) {
    user.books[0].removeFromRealm()
}
```

**Comment by rshah** [comment]
Thank you for the pointer.
I can remove and replace the contents now
```Kotlin
while (user.books.isNotEmpty()) {
   user.books[0].removeFromRealm()
}
```

**Comment by zaki50** [comment]
@rshah another simple code.

```
user.books.where().findAll().clear()
```

**Comment by rshah** [comment]
@zaki50 Thank you
