### ISSUE TITLE
Realm support for Cordova

### ISSUE THREAD

**Issue by batista-mihai** [realm/realm-java#2125]
Hello,

I have an issue in a Cordova plugin with a dependency that uses Realm. 

The exception that is being raised is the following:
<code>
2-08 16:51:52.770 2138-2138/io.cordova.hellocordova:onyxsdk E/AndroidRuntime: java.lang.AbstractMethodError: abstract method "java.util.Set io.realm.internal.RealmProxyMediator.getModelClasses()"
12-08 16:51:52.770 2138-2138/io.cordova.hellocordova:onyxsdk E/AndroidRuntime:     at io.realm.Realm.initializeRealm(Realm.java:279)
12-08 16:51:52.770 2138-2138/io.cordova.hellocordova:onyxsdk E/AndroidRuntime:     at io.realm.Realm.createAndValidate(Realm.java:255)
12-08 16:51:52.770 2138-2138/io.cordova.hellocordova:onyxsdk E/AndroidRuntime:     at io.realm.Realm.createInstance(Realm.java:225)
12-08 16:51:52.770 2138-2138/io.cordova.hellocordova:onyxsdk E/AndroidRuntime:     at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:114)
12-08 16:51:52.770 2138-2138/io.cordova.hellocordova:onyxsdk E/AndroidRuntime:     at io.realm.Realm.getInstance(Realm.java:191)
12-08 16:51:52.770 2138-2138/io.cordova.hellocordova:onyxsdk E/AndroidRuntime:     at com.onyxbeacon.service.ContentManager.<init>(ContentManager.java:149)
</code>

The Gradle used: 1.3.0 and 1.5.0
Realm version: 0.86.0

Does Realm offer support for Cordova? Any help is appreciated. 

Thank you,
Mihai Batista

**Comment by cmelchior** [comment]
We don't support Cordova directly, but as far as I know, it is possible to create Java modules in it which definitely should be possible. This sounds like perhaps the annotation processor isn't running. Can you check the Gradle log? There should be lines that reads something like `Note: Processing XXX`

**Comment by beeender** [comment]
@batista-mihai I hope your issue is solved. I am closing this issue now. Please fell free to reopen it if you need more help on this topic.
