### ISSUE TITLE
Realm not refresh data when commit done

### ISSUE THREAD

**Issue by thanhtranduc** [realm/realm-java#2127]
I have a question for team's realm, so I have two thread, the firstly changing data then commit successfully data to local database, after that the secondly fetch all data after previous thread done but not data change in here. What's reason in show case?

**Comment by cmelchior** [comment]
If you make a write transaction on one thread, all other Looper threads gets notified using a Handler message. If you want to be notified when that happens you can register a `RealmChangeListener` as described here: https://realm.io/docs/java/latest/#notifications

Not that Handler messages enter a queue of messages, so there will be a small delay between one thread writing and other threads being notified about it. You can manually force an update using `Realm.refresh()` if you want.

**Comment by beeender** [comment]
@thanhtranduc I guess you solved you issue~~ I am closing this now. Feel free to let us know if you need more help.
