### ISSUE TITLE
Annotation processing not running with Android annotations

### ISSUE THREAD

**Issue by vitorprado** [realm/realm-java#2132]
I has a headache with annotation processing and realm wasn't looking into my project to find objects.
I said in stackoverflow that some libraries (like Android Annotations) has an `apt` or `provided` in gradle dependencies. Using `apt` solved my problem, but it's not documented. Maybe this could be useful to another people:

```
    apt 'io.realm:realm-android:0.87.1'
    compile 'io.realm:realm-android:0.87.1'
```

I made this, like AA use.. and know the compile task force Realm annotation process to run.

**Comment by kneth** [comment]
Thanks for the suggestion.

Did you use the same Proguard configuration as outlined in the documentation: https://realm.io/docs/java/latest/#proguard

**Comment by vitorprado** [comment]
Yes, I follow the instructions correctly.
I read about the process here: http://stackoverflow.com/a/34613104

**Comment by cmelchior** [comment]
Note that if you are using our new Gradle plugin as described here: https://realm.io/news/android-installation-change/ it should automatically be added to APT

**Comment by vitorprado** [comment]
Nice! But this is not described in documentation. I think adding this information there will help a lot.

**Comment by tuochi** [comment]
it's not working for me!?

here my gradle file: http://pastebin.com/sD74zX5U

I get the error: Error:The generated at.hochi.android.R class cannot be found

If i remoe the annotation @EActivity(R.layout.activity_main) form my Activity it compile! and after adding onCreat it run!

Can someone give me a working example? thx

**Comment by zaki50** [comment]
@tuochi did you get any other errors from annotation processor of AA?

**Comment by cbush** [comment]
We are revamping the Realm docs. We're not ignoring this issue -- we've read through every one of them, and we'll be sure to address this as part of our updates. We're closing the GitHub issues and creating new JIRA tickets to track the work at a high level.
