### ISSUE TITLE
Link queries 

### ISSUE THREAD

**Issue by atouchsimo** [realm/realm-java#2136]
```java
realm.where(Users.class).contains("data.friends.name", query, Case.INSENSITIVE).findAll();
```
it does not return any result,

**Realm version:** *0.87.2*
**Android Studio:** *1.5.1*
**OS:** *OS X 10.11.2*

**Comment by cmelchior** [comment]
What kind of data are you querying? Note that `Case.INSENSITIVE` only works for the Latin alphabet as described here: https://realm.io/docs/java/latest/#case-insensitive-queries

**Comment by atouchsimo** [comment]
yes it's latin alphabet
i didnt understand wht do u mean by (wht kind of data)
here's my objects
***Users***
```java
public class Users extends RealmObject {

    @PrimaryKey
    private String _id;

    private String type;

    private UserData data;
  
    ...
}
```
***UserData***
```java
public class UserData extends RealmObject {
    ...    
    private RealmList<Friends> friends;
    ...
}
```
***Friends***
```java
public class Friends extends RealmObject {

    @PrimaryKey
    private String _id;

    private String name;
  
    ...
}
```

**Comment by kneth** [comment]
Just to get a better  understanding of your data, how many objects are returned if you do the following queries:

* `realm.where(UserData.class).contains("friends.name", query, Case.INSENSITIVE).findAll();`
* `realm.where(Friends.class).contains("name", query, Case.INSENSITIVE).findAll(); `

**Comment by atouchsimo** [comment]
`realm.where(Friends.class).contains("name", query, Case.INSENSITIVE).findAll();`
returns some result

but the following doesn't
`realm.where(UserData.class).contains("friends.name", query, Case.INSENSITIVE).findAll();`

**i used realm browser i noticed that when saving UserData the the linked friends saved too, but they are not linked to UserData object ???**

**Comment by kneth** [comment]
I assume that linking `UserData` and `Friends` objects is done somewhere in your app, right? In the Realm browser you are able to follow links.

**Comment by atouchsimo** [comment]
i save **Users** object directly which has **UserData** which has a list of **Friends** objects

in realm browser i have ability to follow links but it shows (0) count...

**Comment by kneth** [comment]
It does sound like the links/lists are not properly set up. Can you show how to add the list of `Friends` to `UserData` and `Users`?

**Comment by atouchsimo** [comment]
**i save the object returned from the api directly  here's the api result....**
```
{
   "_id": "40ccf",
   "type":"normal"
    "data": [
      {
        ...
        "friends": [{
                   ...
                   "name": "kira"
                   ...
                   },
                 {
                   ...
                   "name": "kira"
                   ...
                }
      ]
}
```

**Comment by kneth** [comment]
In the JSON above, I notice that `data` is an array of `friends`, and `friends` is also an array. Your classes suggest that `data` should be an object.

**Comment by atouchsimo** [comment]
yes it's i just forgot to add realmlist to `Users` class,
data it does not contain only `friends` field it has more fields

**Comment by kneth** [comment]
How do you parse the JSON? And how do you add the objects to your Realm?

**Comment by cmelchior** [comment]
@atouchsimo Are you still seeing this problem?

**Comment by atouchsimo** [comment]
i removed primarykey from friends object, and it worked fine,

**Comment by cmelchior** [comment]
Great, i'll close the issue then.
