### ISSUE TITLE
Realm Can decode Good 

### ISSUE THREAD

**Issue by SaeedDarvish** [realm/realm-java#2142]
Hi 
I have a class named Store that extends from `RealmObject`. When I save it into realm, it work's fine. But when retriving it from Realm it doesn't work and the fields are not populated.

![2016-01-24](https://cloud.githubusercontent.com/assets/5301170/12536383/3d8b95d0-c2b8-11e5-985d-569aa57f2bc8.png)

**Comment by cmelchior** [comment]
Note that the debugger doesn't show the real values. You can read more about it here: https://realm.io/docs/java/latest/#debugging
