### ISSUE TITLE
getDefaultRealm missing constructor

### ISSUE THREAD

**Issue by Waterstar2012** [realm/realm-java#2145]
I call getDefaultRealm on my fragment onstart, it throws missing constructor exception...
How can I fix it？

here is my log

java.lang.RuntimeException
re-throw on exception class missing constructor
io.realm.internal.SharedGroup.long createNativeWithImplicitTransactions(long,int,byte[])(Native Method)
io.realm.internal.SharedGroup.void <init>(java.lang.String,boolean,io.realm.internal.SharedGroup$Durability,byte[])(Unknown Source)
io.realm.internal.SharedGroupManager.void <init>(io.realm.RealmConfiguration)(Unknown Source)
io.realm.BaseRealm.void <init>(io.realm.RealmConfiguration,boolean)(Unknown Source)
io.realm.Realm.void <init>(io.realm.RealmConfiguration,boolean)(Unknown Source)
io.realm.Realm.io.realm.Realm getInstance(io.realm.RealmConfiguration)(Unknown Source)
               io.realm.Realm createAndValidate(io.realm.RealmConfiguration,io.realm.internal.ColumnIndices)
               io.realm.RealmObject copyToRealmOrUpdate(io.realm.RealmObject)
               io.realm.RealmQuery where(java.lang.Class)
io.realm.Realm.io.realm.Realm createInstance(io.realm.RealmConfiguration,io.realm.internal.ColumnIndices)(Unknown Source)
               void initializeRealm(io.realm.Realm)
               io.realm.RealmObject createObject(java.lang.Class)
               io.realm.RealmObject createObject(java.lang.Class,java.lang.Object)
               io.realm.RealmObject copyToRealm(io.realm.RealmObject)
               java.util.List copyToRealmOrUpdate(java.lang.Iterable)
               void executeTransaction(io.realm.Realm$Transaction)
               io.realm.RealmObject copyOrUpdate(io.realm.RealmObject,boolean)
               void migrateRealm(io.realm.RealmConfiguration,io.realm.RealmMigration)
               java.lang.String getCanonicalPath(java.io.File)
               boolean isInTransaction()
               void setAutoRefresh(boolean)
io.realm.RealmCache.io.realm.BaseRealm createRealmOrGetFromCache(io.realm.RealmConfiguration,java.lang.Class)(Unknown Source)
                    void release(io.realm.BaseRealm)
                    void validateConfiguration(io.realm.RealmConfiguration)
                    void invokeWithGlobalRefCount(io.realm.RealmConfiguration,io.realm.RealmCache$Callback)
io.realm.Realm.io.realm.Realm getDefaultInstance()(Unknown Source)
cn.jaxus.course.control.realm.RealmManager.io.realm.Realm getDefaultRealm()(Unknown Source)
cn.jaxus.course.control.homepage.hot.HotFragment.void openRealm()(Unknown Source)
cn.jaxus.course.control.homepage.hot.HotFragment.void onStart()(Unknown Source)

**Comment by beeender** [comment]
Is there anything like below in your adb log?
`jni: ThrowingException `

**Comment by Waterstar2012** [comment]
No I don't see any 'jni: ThrowingException'

**Comment by Waterstar2012** [comment]
The problem has cause a lot of crash..

**Comment by beeender** [comment]
Which Realm version are you using? Can you please share your code of the setting the default realm configuration?

**Comment by Waterstar2012** [comment]
my realm version is 0.87.0

And here is my code 

I create RealmManger  to help me manager realm which is below.
In TestFragment onStart I call 
 if (null == mRealm) {
      mRealm = RealmManager.getInstance().getDefaultRealm();
  }


·public class RealmManager {

    private static final String TAG = "RealmManager";

    private static final int VERSION = 1;  
    private static final int VERSION_COURSE_RECOMMEND = 0;  

    private static RealmManager mInstance;

    private static RealmConfiguration.Builder mDefaultBuilder;
    private static RealmConfiguration.Builder mCourseRecommendBuilder;

    public static RealmManager getInstance() {
        if (mInstance == null) {
            synchronized (RealmManager.class) {
                if (mInstance == null) {
                    mInstance = new RealmManager();
                }
            }
        }
        return mInstance;
    }

    public static void init(Context context) {
        String cacheDir = StoragePathUtil.getRealmCacheDir(context);
        File cacheFile = new File(cacheDir);
        if (!cacheFile.exists()) {
            if (!cacheFile.mkdirs()) {
                KLog.e(TAG, " create realm cache dir failed ");
            }
        }

        mDefaultBuilder = new RealmConfiguration.Builder(cacheFile)
                .schemaVersion(VERSION)
                .migration(new RealmMigration() {
                    @Override
                    public void migrate(DynamicRealm dynamicRealm, long oldVersion, long newVersion) {
                        KLog.i(TAG, "default oldVersion:" + oldVersion + "   newVersion:" + newVersion);
                        // DynamicRealm exposes an editable schema
                        RealmSchema schema = dynamicRealm.getSchema();

                        // Migrate to version 1
                        if (0 == oldVersion) {
                            // 2.0.2增加HotCategory表
                            schema.create("HotCategory")
                                    .addField("id", String.class, FieldAttribute.PRIMARY_KEY, FieldAttribute.REQUIRED)
                                    .addField("title", String.class);

                            RealmObjectSchema realmObjectSchema = schema.get("RealmSubject");
                            realmObjectSchema.addField("linkUrl", String.class);
                            realmObjectSchema.addField("sType", int.class);

                            // 2.0.2 RealmCourseItem增加order字段
                            RealmObjectSchema courseItem = schema.get("RealmCourseItem");
                            courseItem.addField("order", int.class);

                            oldVersion++;
                        }

                        // Migrate to version 2
                    }
                });
        Realm.setDefaultConfiguration(mDefaultBuilder.build());

        mCourseRecommendBuilder = new RealmConfiguration.Builder(cacheFile)
                .schemaVersion(VERSION_COURSE_RECOMMEND)
                .migration(new RealmMigration() {
                    @Override
                    public void migrate(DynamicRealm dynamicRealm, long oldVersion, long newVersion) {
                        KLog.i(TAG, "course recommend oldVersion:" + oldVersion + "   newVersion:" + newVersion);
                        // DynamicRealm exposes an editable schema
                        RealmSchema schema = dynamicRealm.getSchema();

                        // Migrate to version 1
                        if (0 == oldVersion) {

                            oldVersion++;
                        }

                        // Migrate to version 2
                    }
                });
    }


    public Realm getDefaultRealm() {
        if (mDefaultBuilder == null) {
            return null;
        }
        return Realm.getDefaultInstance();
    }

 

}
·

**Comment by Waterstar2012** [comment]
It seem that it happen only on some machine, and my code works well on my phone..

**Comment by beeender** [comment]
Can you please share a list of the problematic devices?

**Comment by Waterstar2012** [comment]
HM NOTE 1TD(Xiaomi) 
vivo x5sl
r831s
huawei c8817l

**Comment by beeender** [comment]
What is the return value  of `getRealmCacheDir` ? On some devices, if the directory contains special characters, error might occur.

**Comment by Waterstar2012** [comment]
getRealmCacheDir return /storage/emulated/0/Android/data/cn.jaxus.course/CacheData/realmCache/

**Comment by Waterstar2012** [comment]
beside some times NoSuchMethodError happen

java.lang.NoSuchMethodError
no non-static method "Lio/realm/exceptions/RealmError;.<init>(Ljava/lang/String;)V"
io.realm.internal.SharedGroup.long createNativeWithImplicitTransactions(long,int,byte[])(Native Method)
io.realm.internal.SharedGroup.void <init>(java.lang.String,boolean,io.realm.internal.SharedGroup$Durability,byte[])(Unknown Source)
io.realm.internal.SharedGroupManager.void <init>(io.realm.RealmConfiguration)(Unknown Source)
io.realm.BaseRealm.void <init>(io.realm.RealmConfiguration,boolean)(Unknown Source)
io.realm.Realm.void <init>(io.realm.RealmConfiguration,boolean)(Unknown Source)
io.realm.Realm.io.realm.Realm getInstance(io.realm.RealmConfiguration)(Unknown Source)
               io.realm.Realm createAndValidate(io.realm.RealmConfiguration,io.realm.internal.ColumnIndices)
               io.realm.RealmObject copyToRealmOrUpdate(io.realm.RealmObject)
               io.realm.RealmQuery where(java.lang.Class)
io.realm.Realm.io.realm.Realm createInstance(io.realm.RealmConfiguration,io.realm.internal.ColumnIndices)(Unknown Source)

**Comment by beeender** [comment]
Is it hard coded `/storage/emulated/0` ? Or it is created by `context.getCacheDir() + "realmCache"`?

**Comment by beeender** [comment]
can you please share your code of `getRealmCacheDir` as well?

**Comment by Waterstar2012** [comment]
the call stack of my StoragePathUtil.getRealmCacheDir is

public static String getRealmCacheDir(Context context) {
        return getCacheRootDir(context) + "realmCache" + File.separator;
    }

public static String getCacheRootDir(Context context) {
        return getRootDirPath(context) + "CacheData" + File.separator;
    }

public static String getRootDirPath(Context context) {
        if (mRootPath == null) {
            mRootPath = StorageUtil.getInternalSdcardPath() + File.separator + getPackagePath(context) + File.separator;
        }
        return mRootPath;
    }

public static String getInternalSdcardPath() {
		return Environment.getExternalStorageDirectory().getPath();
	}

**Comment by beeender** [comment]
And the code for `getPackagePath` please?

**Comment by Waterstar2012** [comment]
```
//有的情况下, 默认的包名的文件夹创建不成功, 只好随机生成一个来代替
    private static String getPackagePath(Context context) {

        String settedPath = context.getSharedPreferences(SP_NAME, Context.MODE_PRIVATE).getString(KEY_PACKAGE_NAME_PATH, null);
        if (settedPath == null) {
            return getDefaultPackagePath(context);
        }
        return settedPath;
    }

    private static String getDefaultPackagePath(Context context) {
        String path = "Android" + File.separator + "data" + File.separator + context.getPackageName();
        return path;
    }

//如果缓存文件夹被文件占用,果断删除先,如果删除不了,则随机生成一个,并且写入preferences
    private void initRootDir() {
        KLog.d(TAG, " init cacheDir ");
        File rootDir = new File(StoragePathUtil.getRootDirPath(this));

        if (rootDir.exists() && !rootDir.isDirectory()) {
            KLog.i(TAG, " file exist  and cacheDir is file");
            if (!rootDir.delete()) {
                StoragePathUtil.setRandomPackagePath(this);
                rootDir = new File(StoragePathUtil.getRootDirPath(this));
                KLog.i(TAG, "create a random package dir for this app " + rootDir.getPath());
            } else {
                KLog.d(TAG, " cacheDir is file and deleted");
            }
        } else {
            KLog.d(TAG, "cacheDir exist " + rootDir.exists() + " cacheDir is file " + rootDir.isFile() + "cacheDir is Dir" + rootDir.isDirectory());
        }
        if (!rootDir.exists()) {
            if (!rootDir.mkdirs()) {
                StoragePathUtil.setRandomPackagePath(this);
                rootDir = new File(StoragePathUtil.getRootDirPath(this));
                KLog.i(TAG, " make a random dir for this app " + rootDir.getPath());

                rootDir.mkdirs();
            } else {
                KLog.d(TAG, " cache dir mkdirs true ");
            }
        } else {
            KLog.d(TAG, " cache dir exist");
        }
    }

  //设置packagePath,有时默认的文件夹会创建不成功
    public static void setRandomPackagePath(Context context) {
        String originPackagePath = context.getPackageName();

        SharedPreferences sp = context.getSharedPreferences(SP_NAME, Context.MODE_PRIVATE);
        Editor et = sp.edit();
        et.putString(KEY_PACKAGE_NAME_PATH, originPackagePath);
        et.apply();
        KLog.i(TAG, " set random package path ");
    }
```

**Comment by beeender** [comment]
Do you have below in your proguard config?
```
-keep class io.realm.internal.Keep
-keep @io.realm.internal.Keep class * { *; }
```

**Comment by beeender** [comment]
BTW, I saw `public static void init(Context context)` is not private and it is not synchronized. Any chance you `mkdir` in on thread and delete it in other thread?

**Comment by Waterstar2012** [comment]
my proguard-project.txt is

-keep class io.realm.annotations.RealmModule
-keep @io.realm.annotations.RealmModule class *
-keep class io.realm.internal.Keep
-keep @io.realm.internal.Keep class *
-dontwarn javax.**
-dontwarn io.realm.**

and I quite sure that no other code delete the folder...

**Comment by beeender** [comment]
when `cn.jaxus.course.control.homepage.hot.HotFragment.void onStart` this called, is it the first time the App getting a Realm instance?

**Comment by Waterstar2012** [comment]
yeah

**Comment by beeender** [comment]
@Waterstar2012 When i tried to run your app on emulator, it gives me error message below

```
java.lang.RuntimeException: Unable to create application cn.jaxus.course.MainApplication: java.lang.IllegalArgumentException: An existing folder must be provided. Yours was /sdcard/cn.jaxus.course/CacheData/realmCache
```

Is this a known issue to you?

**Comment by Waterstar2012** [comment]
does it happen to you every time?

**Comment by beeender** [comment]
on my emulator yes. `Nexus 6P API 23`

**Comment by Waterstar2012** [comment]
our app does not support android 6.0 yet..

**Comment by beeender** [comment]
I cannot figure out what is wrong with those devices... Maybe those have a bug with accessing external storage? Maybe easy fix would be that you just save the Realm files on the internal storage, then you won't risk exceptions like user removes the sd card.

I will continue investigate why the exception message is not completed if the proguard settings are correct...

**Comment by Waterstar2012** [comment]
Thanks a lot!

**Comment by beeender** [comment]
BTW, nice APP!

**Comment by beeender** [comment]
```
java.lang.NoSuchMethodError
no non-static method "Lio/realm/exceptions/RealmError;.(Ljava/lang/String;)V"
```
This is caused by optimized byte code....
```
package io.realm.exceptions;

import io.realm.internal.Keep;

@Keep
public class RealmError extends Error {
}
```

The constructor has bee optimized out, then the JNI cannot find it anymore.

**Comment by Waterstar2012** [comment]
Ok, I will try it!

**Comment by beeender** [comment]
@Waterstar2012 for your proguard setting:
`-keep @io.realm.internal.Keep class *` should be `-keep @io.realm.internal.Keep class * {*;}`

**Comment by Waterstar2012** [comment]
Is that the problem cause my crash..?

**Comment by beeender** [comment]
No. It is to fix the incomplete exception message ---- it is the same root cause with #1904 
After you fix it in the proguard setting, you are supposed to have more information about the error.

However, I think change it to use internal storage would be the ideal fix for you right now... The root cause of you crash needs more information to analysis.

**Comment by cmelchior** [comment]
@Waterstar2012 Are you still seeing this problem?

**Comment by Waterstar2012** [comment]
No. I don't see any ‘missing constructor’ crash any more! Thank you!
