### ISSUE TITLE
Realm overwrites persisted objects

### ISSUE THREAD

**Issue by mhgk** [realm/realm-java#2149]
Hey guys.

I have a class (NewsEntity .class) that extends RealmObject, which have a field (MediaContentEntity.class) consitsting of an object also extending RealmObject.

Every time i create a new NewsEntity object with a mediaEntity object, is seems like the mediaEntity object is overwritten (like it would if it had the same primary key).
Cant figure out why, am i using realm wrongly or?

```
public class NewsEntity extends RealmObject {

    @PrimaryKey
    private int entityId;
    private int channelId;
    private String title;
    private String body;
    private int authorId;
    private String authorName;
    private String authorPictureUrl;
    private Date created;
    private RealmList<CommentEntity> commentsList;
    private RealmList<LikeByIdEntity> likedByUserIds;
    private Date serviceAnnouncementEnd;
    private Date serviceAnnouncementStart;
    private boolean likedByMe;
    private boolean commentedByMe;
    private MediaContentEntity mediaContentEntity;  <----

...........  getters and setter and empty constructor

}
```

```
public class MediaContentEntity extends RealmObject {

    @PrimaryKey
    private int id;
    private int ownedById;
    private String contentUrl;
    private String thumbnailUrl;
    private String mimeType;
    private int width;
    private int height;

...........  getters and setter and empty constructor

}
```

```
  private void persistMediaContent(NewsEntity newsEntity, News news, Realm localTransAction) {

        localTransAction.beginTransaction();
        newsEntity.setMediaContentEntity(mediaContentEntity);
        localTransAction.commitTransaction();
    }
```

shouldnt this be the correct way to add  the mediaContentEntity to realm, or?  I also tried commiting the  mediaContentEntity  to realm first, and then set it in the NewsEntity object

**Comment by zaki50** [comment]
Hi @mhgk 

How do you create `mediaContentEntity` object?

**Comment by mhgk** [comment]
Hello  Zaki, thx for reply.
MediaContentEntity mediaContentEntity = new  mediaContentEntity(); 

I tried both creating the mediaContent and persist it in Realm before setting it in the newsEntiti(),

 localTransAction.beginTransaction();
        MediaContentEntity mediaContentEntity = localTransAction.copyToRealmOrUpdate(createMediaContentEntity(news.getMediaContent()));
        localTransAction.commitTransaction();

        localTransAction.beginTransaction();
        newsEntity.setMediaContentEntity(mediaContentEntity);
        localTransAction.commitTransaction();

I alo tried just:

 localTransAction.beginTransaction();
        newsEntity.setMediaContentEntity(createMediaContentEntity(news.getMediaContent()));
        localTransAction.commitTransaction();

**Comment by mhgk** [comment]
I use the db viewer tool by stetho (chrome tool), and i see no objects i the MediaContentEntity table, exept 1.

**Comment by kneth** [comment]
You need to be aware that `copyToRealmOrUpdate()` is using the primary key to either create or update an object. Does `createMediaContentEntity()` set the primary key?

**Comment by mhgk** [comment]
Yes it does. I figured it out though. thx
