### ISSUE TITLE
Realm migrations + background thread context question

### ISSUE THREAD

**Issue by shawnwall** [realm/realm-java#2155]
I have a realm migration set up in my Application subclass as so:

        RealmConfiguration config = new RealmConfiguration.Builder(this)
                .schemaVersion(REALM_VERSION)
                .migration(new Migration())
                .build();
        Realm.setDefaultConfiguration(config);
        Realm realm = Realm.getInstance(config); // Automatically run migration if needed
        realm.close();

This was my first migration to the existing codebase. In my original codebase in some background threads I used the following as originally instructed:

`Realm.getInstance(getActivity())`

...within fragments, for example. Upon running the new codebase with the migration, places where I used `getInstance(Context)` began to fail. After some research I discovered `getInstance(Context)` does not use the default configuration and thus the model version becomes zero, resulting in problems. My question is: *How are we supposed to mix realm migrations and background thread operations?*

Note I am still using an older version at the moment: 0.81.0

**Comment by cmelchior** [comment]
If you set the default configuration in your Application class, you can use `Realm.getDefaultInstance()` everywhere. You can see an example of it here: https://realm.io/docs/java/latest/#controlling-the-lifecycle-of-realm-instances

**Comment by shawnwall** [comment]
Thank you. That is what I am currently doing, but wasn't aware that it would be thread-safe given the documentation states to use `Realm.getInstance(Context)` in relation to threading. I've been observing some odd behavior since making the change, for example in nested network call callbacks.

**Comment by cmelchior** [comment]
Using `Realm.getInstance(context)` is just a shorthand for `Realm.getInstance(RealmConfiguration)` and you should ideally use `Realm.getDefaultInstance()` or `Realm.getInstance(RealmConfiguration)` instead, but all should work. The main principle is just to call it on the thread you want to use Realm on.

Can you elaborate on the behaviours you are seeing regarding callbacks?

**Comment by shawnwall** [comment]
If I call a static class method Object.getCurrentSomething() inside a callback, make another network call, and in its callback call that same method again, etc... but internal to the implementation I use Realm.getDefaultInstance() and find the first of that objects type, sometimes the object is not found, even though the same implementation is running. I've resolved it by simply fetching the object prior to all of the calls and using it's id as a final int for now and things are looking good.

**Comment by kohiyadav** [comment]
Hi, I have want to add one field in my model class, so i used Realm-0.87.5 for realm migration, but while running the app it displays realmmigration must be provided exception at  realm = Realm.getInstance(context); point.

But when i change it to realm = Realm.getInstance(config); it runs but return exception Configurations cannot be different if used to open the same file. 

Please provide suggesstion.
