### ISSUE TITLE
Thread synchronization error between IntentService and AsyncTaskLoader

### ISSUE THREAD

**Issue by leo-one** [realm/realm-java#2161]
Hi,

The code below is leading to unpredictable behaviour and inconsistent results.

In the IntentService:
```java
    // >>>>>> In the IntentService, delete existing local data and insert new downloaded data
    Realm realm = Realm.getInstance(getApplicationContext());
    realm.beginTransaction();
    RealmQuery<DogRealm> query = realm.where(DogRealm.class);
    query = (filter == null) ? query.isNull("filter") : query.equalTo("filter", filter);
    query.findAll().clear();

    for (Dog dog : dogsFromWeb) {
        DogRealm dogRealm = new DogRealm();
        dogRealm.setName(dog.getName());
        // set other properties
        realm.copyToRealm(dogRealm);
     }
     realm.commitTransaction();

    // Use EventBus to notify the Frag,ment to update UI
     EventBus.getDefault().post(new DogsUpdated());
```
In the Fragment:
```java
     // >>>>>>  In the fragment, reload the AsyncTaskLoader
     public void onEventMainThread(CacheIntentService.DogsUpdated e){
        getLoaderManager().getLoader(0).onContentChanged();
    }

    // this is the code of AsyncTaskLoader
        @Override
        public List<Dog> loadInBackground() {
                List<Dog> dogList = new ArrayList<>();

                // The error is here. It often return an empty result.
                RealmResults<DogRealm> realmResults =  Realm.getInstance(getContext()).where(DogRealm.class)
                    .equalTo("filter", mFilter).findAllSorted("createdAt", Sort.DESCENDING);

            for(DogRealm dogRealm: realmResults) {
                dogList .add(new Dog(dogRealm));
            }

            return dogList ;
        }
```
The result of the query is often empty in AsyncTaskLoader.
But if I execute the same query in IntentService, after the commit, the result is the expected one.

It looks a thread synchronization error between IntentService and AsyncTaskLoader. Although both are executed in background, the AsyncTaskLoader is called only after the commit then the result should be consistent.

What would it be the correct approach in this case ?

Regards,

**Comment by beeender** [comment]
Are `IntentService` and `AsyncTaskLoader` in the different processes?
And one more thing, try to call `Realm.refresh()` before query in the `AsyncTaskLoader`.

**Comment by beeender** [comment]
I think the major problem is, you didn't close the Realm instance in `loadInBackground`. Realm tries to maintain a reference counter for each thread, and the auto-updating mechanism is based on looper. That is said, if the thread doesn't have a looper, and you opened a Realm instance before without closing it, the next time when you open it, the Realm will reuse the same instance and the db version stays at the last time you opened it.
Just modified it to:

```java
@Override
public List<Dog> loadInBackground() {
    List<Dog> dogList = new ArrayList<>();
    
    Realm realm = Realm.getInstance(getContext());
    RealmResults<DogRealm> realmResults =  realm.where(DogRealm.class)
        .equalTo("filter", mFilter).findAllSorted("createdAt", Sort.DESCENDING);

        for(DogRealm dogRealm: realmResults) {
            dogList .add(Realm.copyFromRealm(dogRealm));
        }

        return dogList ;
}
```

Why don't you just use the Realm's async query? That would be much easier and no need to do `copyFromRealm`.

**Comment by leo-one** [comment]
Thanks, beeender.
It looks that call Realm.refresh() before query in the AsyncTaskLoader solved the issue.
But I need to do more tests to confirm it.

The AsyncTaskLoader is already background thread and the method loadInBackground() needs to return the result, so the async query does not look applicable in this case. I changed to copyFromRealm() to avoid retaining reference.

Regards,

**Comment by beeender** [comment]
Please also have a look at my comment https://github.com/realm/realm-java/issues/2161#issuecomment-175001853 . 1. Please make sure the Realm instance is closed. 2. If you are opening a new instance every time, no need to call refresh anymore.

**Comment by kneth** [comment]
@leo-one Have you been able to solve your issue and can we close it?

**Comment by leo-one** [comment]
Yes. The issue was solved by closing the instance.
Thanks @beeender and @kneth

**Comment by kneth** [comment]
@leo-one Thanks for the update.
