### ISSUE TITLE
cause mine so files java.lang.UnsatisfiedLinkError

### ISSUE THREAD

**Issue by lgengsy** [realm/realm-java#2163]
when i  put  realm_0873.jar to my Android studio  project  libs dir  ,then myself  .so files  can't load . I spent a whole day to troubleshoot the problem. but  I give up。

**Comment by beeender** [comment]
@lgengsy Realm lib contains so for lots of ARCHs. Most common issue is if you own so doesn't have arm_64 version, then on some phones, it choose to load the arm_64 version realm so, then fails to find your own so with arm64 version. See https://realm.io/docs/java/latest/#couldnt-load-librealm-jniso

**Comment by beeender** [comment]
@lgengsy I guess you solved you issue~~ I am closing this now. Feel free to let us know if you need more help.
