### ISSUE TITLE
Realm access from incorrect thread.(Help)

### ISSUE THREAD

**Issue by Sutirth** [realm/realm-java#2170]
I have setup Realm configuration in application file. Used getDefaultInstanceI() to open realm in Intent Service. However I need RealmResults query for updating me 2 tables and putting/updating new values in other 2 tables. Its failing any help on this front??

**Comment by beeender** [comment]
failing with what exception? and would you please share some related source code? it is really hard for us to help with limited information ...

**Comment by Sutirth** [comment]
RealmConfiguration realmConfiguration = new RealmConfiguration.Builder(this).build();
        Realm.deleteRealm(realmConfiguration); // Clean slate
        Realm.setDefaultConfiguration(realmConfiguration);
//In application class
This is what I am trying to do inside IntentService with
private void postSweatPoints(){
       // mContext = context;
        SharedPreferences sharedPrefUser = getApplicationContext().getSharedPreferences("UserProfile", Context.MODE_PRIVATE);
        userTeam = sharedPrefUser.getString("USER_TEAM", null);

        SharedPreferences sharedPrefLogin = getApplicationContext().getApplicationContext()
                .getSharedPreferences("UserProfile", Context.MODE_PRIVATE);
        userId = sharedPrefLogin.getInt("USER_ID", 0);

        dateFormat = new SimpleDateFormat("yyyy-MM-dd HH:mm:ss");
        //dateFormat.setTimeZone(TimeZone.getTimeZone("UTC"));
        currentTimeStamp = dateFormat.format(new Date());
        SharedPreferences sharedPref = getApplicationContext().getSharedPreferences("UserAccessToken", Context.MODE_PRIVATE);
        ACCESS_TOKEN = sharedPref.getString("AccessToken", null);
        Log.i(TAG, "Current time in post service:  " + currentTimeStamp);
        ArrayList<Activities> activitiesPost = new ArrayList<Activities>();
        ArrayList<Extra> extras = new ArrayList<Extra>();
        final Realm realm = Realm.getDefaultInstance();
        RealmResults<FitnessDB> fitnessDBRealmResults = realm.allObjects(FitnessDB.class);
        for (int i = 0; i < fitnessDBRealmResults.size(); i++) {
            if (fitnessDBRealmResults.size() != 0) {


                int stepCount =Integer.valueOf(fitnessDBRealmResults.get(i).getStepCount());
                int Calories = (int) Math.floor(fitnessDBRealmResults.get(i).getCaloriesExpeneded());

                if(stepCount == 0){
                    stepCount = 0;
                    Calories = 0;
                }


                Activities activities = new Activities(fitnessDBRealmResults.get(i).getActivityStartTime()
                        , fitnessDBRealmResults.get(i).getActivityEndTime()
                        , stepCount
                        , Calories,
                        0, 1, 0, extras);

                activitiesPost.add(activities);

            } else {

            }
        }

        try {

            if (activitiesPost.size() != 0) {


                Log.i(TAG,"Activites post:  "+activitiesPost);

                FitnessModel fitnessModel = new FitnessModel(currentTimeStamp, activitiesPost);
                apiModule = createApiModule();
                Call<FitnessModel> fitnessModelCall = apiModule.postFitnessModel(fitnessModel);
                fitnessModelCall.enqueue(new Callback<FitnessModel>() {
                    @Override
                    public void onResponse(Response<FitnessModel> response, Retrofit retrofit) {
                        RealmResults<FitnessDB> fitnessDBRealmResults =
                                realm.where(FitnessDB.class).findAll();
                        Log.i(TAG, "Fitness post body:  " + response.body());
                        modelFitness = response.body();
                        if (response.isSuccess()) {
                            Log.i(TAG, "Inside on Success");
                            if (modelFitness.getAppStatusCode() == WorkoutCashConstants.SUCCESS_API) {

                                for (int i = 0; i < fitnessDBRealmResults.size(); i++) {
                                    if (fitnessDBRealmResults.size() != 0) {
                                        Log.i(TAG, "Fitness data posts is success inside post sweatpoints");

                                        realm.beginTransaction();
                                        FitnessDB fitnessDB = new FitnessDB();
                                        fitnessDB.setActivityStartTime(fitnessDBRealmResults.get(i).getActivityStartTime());
                                        fitnessDB.setActivityEndTime(fitnessDBRealmResults.get(i).getActivityEndTime());
                                        fitnessDB.setCaloriesExpeneded(fitnessDBRealmResults.get(i).getCaloriesExpeneded());
                                        fitnessDB.setStepCount(fitnessDBRealmResults.get(i).getStepCount());
                                        fitnessDB.setIsSynced(1);
                                        realm.copyToRealmOrUpdate(fitnessDB);
                                        realm.commitTransaction();

                                        realm.beginTransaction();

                                        TestFitnessDB testFitnessDB = new TestFitnessDB();
                                        testFitnessDB.setActivityStartTime(fitnessDBRealmResults.get(i).getActivityStartTime());
                                        testFitnessDB.setActivityEndTime(fitnessDBRealmResults.get(i).getActivityEndTime());
                                        testFitnessDB.setCaloriesExpeneded(fitnessDBRealmResults.get(i).getCaloriesExpeneded());
                                        testFitnessDB.setStepCount(fitnessDBRealmResults.get(i).getStepCount());
                                        testFitnessDB.setIsSynced(1);
                                        testFitnessDB.setSendTime(currentTimeStamp);
                                        testFitnessDB.setSendCodePost(200);
                                        realm.copyToRealmOrUpdate(testFitnessDB);
                                        realm.commitTransaction();

                                        Calendar currentTime = Calendar.getInstance();
                                        currentTime.add(Calendar.MONTH, 0);
                                        currentMonthNo = format.format(currentTime.getTime()).toString();
                                        currentMonth = nameFormat.format(currentTime.getTime()).toString();

                                        for(int z = 0 ; z < modelFitness.getData().getDailyFitnessData().size() ; z ++){
                                            realm.beginTransaction();
                                            SweatPointFitnessDB sweatPointFitnessDB = new SweatPointFitnessDB();
                                            sweatPointFitnessDB.setForday(modelFitness.getData().getDailyFitnessData().get(z).getForDay());
                                            sweatPointFitnessDB.setUserid(modelFitness.getData().getDailyFitnessData().get(z).getUserId());
                                            sweatPointFitnessDB.setCalories(modelFitness.getData().getDailyFitnessData().get(z).getCalories());
                                            sweatPointFitnessDB.setStepCount(modelFitness.getData().getDailyFitnessData().get(z).getStepCount());
                                            sweatPointFitnessDB.setSweatpoints(modelFitness.getData().getDailyFitnessData().get(z).getSweatPoints());
                                            sweatPointFitnessDB.setDistance(Integer.toString(modelFitness.getData().getDailyFitnessData().get(z).getDistance()));
                                            sweatPointFitnessDB.setCurrentMonth(currentMonth);
                                            sweatPointFitnessDB.setCurrentMonthNo(currentMonthNo);
                                            realm.copyToRealmOrUpdate(sweatPointFitnessDB);
                                            realm.commitTransaction();
                                        }



                                        RealmResults<UserInfoDB> userInfoResults
                                                = realm.where(UserInfoDB.class)
                                                .equalTo(WorkoutCashConstants.COLUMN_USER_ID,userId)
                                                .findAll();


                                        for(int j  = 0 ; j < userInfoResults.size() ; j++){
                                            realm.beginTransaction();
                                            UserInfoDB userInfoData =  new UserInfoDB();
                                            userInfoData.setUserId(userInfoResults.get(j).getUserId());
                                            userInfoData.setEmail(userInfoResults.get(j).getEmail());
                                            userInfoData.setDisplayName(userInfoResults.get(j).getDisplayName());
                                            userInfoData.setTeamId(userInfoResults.get(j).getTeamId());
                                            userInfoData.setTeamName(userInfoResults.get(j).getTeamName());
                                            userInfoData.setRoleId(userInfoResults.get(j).getRoleId());
                                            userInfoData.setRoleName(userInfoResults.get(j).getRoleName());
                                            userInfoData.setSweatPoints(modelFitness.getData().getSweatPoints());
                                            realm.copyToRealmOrUpdate(userInfoData);
                                            realm.commitTransaction();
                                        }


                                        //    ((DrawerActivity) mContext.getApplicationContext()).setUpToolbarTitle();


                                    }
                                }
                                realm.close();
                            }

                        } else if (response.code() == WorkoutCashConstants.USER_NOT_AUTHENTICATED) {
                            // logoutUser();
                            for (int i = 0; i < fitnessDBRealmResults.size(); i++) {
                                if (fitnessDBRealmResults.size() != 0) {
                                    realm.beginTransaction();

                                    TestFitnessDB testFitnessDB = new TestFitnessDB();
                                    testFitnessDB.setActivityStartTime(fitnessDBRealmResults.get(i).getActivityStartTime());
                                    testFitnessDB.setActivityEndTime(fitnessDBRealmResults.get(i).getActivityEndTime());
                                    testFitnessDB.setCaloriesExpeneded(fitnessDBRealmResults.get(i).getCaloriesExpeneded());
                                    testFitnessDB.setStepCount(fitnessDBRealmResults.get(i).getStepCount());
                                    testFitnessDB.setIsSynced(1);
                                    testFitnessDB.setSendTime(currentTimeStamp);
                                    testFitnessDB.setSendCodePost(400);
                                    realm.copyToRealmOrUpdate(testFitnessDB);
                                    realm.commitTransaction();
                                }
                            }
                        } else {
                            Log.i(TAG, "Fitness post body:  " + response.message());
                            for (int i = 0; i < fitnessDBRealmResults.size(); i++) {
                                if (fitnessDBRealmResults.size() != 0) {
                                    realm.beginTransaction();

                                    TestFitnessDB testFitnessDB = new TestFitnessDB();
                                    testFitnessDB.setActivityStartTime(fitnessDBRealmResults.get(i).getActivityStartTime());
                                    testFitnessDB.setActivityEndTime(fitnessDBRealmResults.get(i).getActivityEndTime());
                                    testFitnessDB.setCaloriesExpeneded(fitnessDBRealmResults.get(i).getCaloriesExpeneded());
                                    testFitnessDB.setStepCount(fitnessDBRealmResults.get(i).getStepCount());
                                    testFitnessDB.setIsSynced(1);
                                    testFitnessDB.setSendTime(currentTimeStamp);
                                    testFitnessDB.setSendCodePost(400);
                                    realm.copyToRealmOrUpdate(testFitnessDB);
                                    realm.commitTransaction();
                                }
                            }

                            Converter<ResponseBody, Error> errorConverter =
                                    retrofit.responseConverter(Error.class, new Annotation[0]);
                            try {
                                Error error = errorConverter.convert(response.errorBody());
                                if (error.appStatusCode == WorkoutCashConstants.USER_NOT_AUTHENTICATED) {
                                    //   logoutUser();
                                }
                            } catch (Exception e) {
                            }
                        }
                    }

                    @Override
                    public void onFailure(Throwable t) {
                        Log.i(TAG, "Inside on Failure");


                    }
                });
            }
        }catch (Exception e){
            Log.i(TAG, "Inside on Crashed");
        }
    }

**Comment by beeender** [comment]
And what is the exception?

**Comment by Sutirth** [comment]
01-27 22:47:29.821 463-463/com.workoutguru.workoutcash E/AndroidRuntime: FATAL EXCEPTION: main
01-27 22:47:29.821 463-463/com.workoutguru.workoutcash E/AndroidRuntime: Process: com.workoutguru.workoutcash, PID: 463
01-27 22:47:29.821 463-463/com.workoutguru.workoutcash E/AndroidRuntime: java.lang.IllegalStateException: Realm access from incorrect thread. Realm objects can only be accessed on the thread they were created.
01-27 22:47:29.821 463-463/com.workoutguru.workoutcash E/AndroidRuntime:     at io.realm.BaseRealm.checkIfValid(BaseRealm.java:330)
01-27 22:47:29.821 463-463/com.workoutguru.workoutcash E/AndroidRuntime:     at io.realm.Realm.where(Realm.java:759)
01-27 22:47:29.821 463-463/com.workoutguru.workoutcash E/AndroidRuntime:     at com.workoutguru.workoutcash.Service.SweatPointService$1.onResponse(SweatPointService.java:136)
01-27 22:47:29.821 463-463/com.workoutguru.workoutcash E/AndroidRuntime:     at retrofit.ExecutorCallAdapterFactory$ExecutorCallback$1.run(ExecutorCallAdapterFactory.java:86)
01-27 22:47:29.821 463-463/com.workoutguru.workoutcash E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:733)
01-27 22:47:29.821 463-463/com.workoutguru.workoutcash E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:95)
01-27 22:47:29.821 463-463/com.workoutguru.workoutcash E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:146)
01-27 22:47:29.821 463-463/com.workoutguru.workoutcash E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5602)
01-27 22:47:29.821 463-463/com.workoutguru.workoutcash E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method)
01-27 22:47:29.821 463-463/com.workoutguru.workoutcash E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:515)
01-27 22:47:29.821 463-463/com.workoutguru.workoutcash E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
01-27 22:47:29.821 463-463/com.workoutguru.workoutcash E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
01-27 22:47:29.821 463-463/com.workoutguru.workoutcash E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)

**Comment by beeender** [comment]
Realm instacne/RealmObject/RealmResults cannot be used across thread, please take a look at doc here https://realm.io/docs/java/latest/#using-a-realm-across-threads . Basically you need a Realm instance for every thread.

For sending RealmObject through intent check this doc https://realm.io/docs/java/latest/#intents

**Comment by Sutirth** [comment]
Okay had a look understood but then how should I update my different database tables.

**Comment by beeender** [comment]
What do you mean "different database table"?

**Comment by Sutirth** [comment]
Apologies I meant to said  different Realm Pojo classes which I am updating in background like there list of it

**Comment by beeender** [comment]
But you are already doing that, aren't you? I saw you are updating TestFitnessDB/userInfoData/fitnessDB etc.. 

Please take a look at our examples https://github.com/realm/realm-java/tree/master/examples
Especially the json examples which might help you https://github.com/realm/realm-java/tree/master/examples/jsonExample

**Comment by Sutirth** [comment]
I am unable to do that in intent service because  RealmResults<FitnessDB> fitnessDBRealmResults =
                                realm.where(FitnessDB.class).findAll(); is failing for me due the exception

**Comment by beeender** [comment]
That is what i said, `onResponse` is running in a different thread, and your realm was created in the other one. Please take a look of our document about the threading part. https://realm.io/docs/java/latest/#using-a-realm-across-threads 

Easiest way is just create a new Realm instance in the `onResponse` and use that on instead.

**Comment by Sutirth** [comment]
I resolved it . Was stupid mistake from my side. Thanks a ton :+1:
