### ISSUE TITLE
Realm duplicated row items in the RecyclerView

### ISSUE THREAD

**Issue by vlonjatg** [realm/realm-java#2171]
So I'm using Realm and DataBinding in RecyclerView but I'm having some issues. 

When I update the model, the recyclerView duplicates the items in the recyclerView which you can see in the image below:

![](http://i.imgur.com/alDyLav.gif)

Here is my code when I do the update when the switch is changed

```
 public void checkedListener(CompoundButton buttonView, boolean isChecked) {
        Timber.d("The active switch result is: " + isChecked);
        if (isActive() != isChecked) {
            //Update realm only if value has changed
            realm.beginTransaction();
            setActive(isChecked);
            realm.commitTransaction();

            Timber.d("Active switch updated");
        }
    }
```

I have tested by removing the realm specific code and and only leaving the ```checkedListener()``` listener empty and it works fine without any row item duplication. But as soon as I put the realm code, the rows duplicate. 

Any idea what's the issue about?

**Comment by beeender** [comment]
Is it possible to share your adapter code of recycle view with us?

**Comment by vlonjatg** [comment]
@beeender, yep first thing tomorrow.

**Comment by vlonjatg** [comment]
Here it's the current adapter that I'm using:

```
public class RemindersAdapter extends RecyclerView.Adapter<RemindersAdapter.ViewHolder> {

    Context context;
    List<ReminderViewModel> reminderViewModels = new ArrayList<>();

    public RemindersAdapter(Context context,  List<ReminderViewModel> reminderViewModels) {
        this.context = context;
        this.reminderViewModels = reminderViewModels;
    }

    @Override
    public ViewHolder onCreateViewHolder(ViewGroup viewGroup, int i) {
        LayoutInflater inflater = LayoutInflater.from(viewGroup.getContext());

        RowReminderItemBinding binding =
                RowReminderItemBinding.inflate(inflater, viewGroup, false);

        return new ReminderViewHolder(binding.getRoot());
    }

    @Override
    public void onBindViewHolder(ViewHolder viewHolder, int i) {
        ReminderViewHolder reminderViewHolder = (ReminderViewHolder) viewHolder;
        reminderViewHolder.binding.setReminderViewModel(reminderViewModels.get(i));
    }

    @Override
        public int getItemCount() {
        return (null != reminderViewModels ? reminderViewModels.size() : 0);
    }

    public void setItems(List<ReminderViewModel> exerciseViewModels) {
        this.reminderViewModels = exerciseViewModels;
        notifyDataSetChanged();
    }

    public void removeItem(ReminderViewModel reminderViewModel) {
        notifyItemRemoved(reminderViewModels.indexOf(reminderViewModel));
        reminderViewModels.remove(reminderViewModel);
    }

    public class ViewHolder extends RecyclerView.ViewHolder {
        public ViewHolder(View itemView) {
            super(itemView);
        }
    }

    class ReminderViewHolder extends ViewHolder {
        RowReminderItemBinding binding;

        public ReminderViewHolder(View view) {
            super(view);

            binding = DataBindingUtil.bind(view);
        }
    }
```

**Comment by beeender** [comment]
Did you pass a `RealmResults` to `RemindersAdapter` constructor? When transaction committed, you need to call `notifyDataSetChanged` because of the `RealmResults` changes.
Easy way is just use add a change listener to `RealmResults` you are using, and trigger the `notifyDataSetChanged` in the listener.

You can spend a few minutes to look at our `RealmBaseAdapter`, https://github.com/realm/realm-java/blob/master/realm/realm-library/src/main/java/io/realm/RealmBaseAdapter.java. it shows how to use `RealmResults` as the data source. You don't have to inherit the `RealmBaseAdapter` if you are using the RecyclerView, but make something similar is quite easy.

Let me know if there is still more questions about this ~

**Comment by kneth** [comment]
@vlonjatg Did you have a chance to look at the `RealmBaseAdapter`? Did it solve you issue?

**Comment by cmelchior** [comment]
Closing due to no response. Feel free to reopen if there is still problems with this.

**Comment by kyodgorbek** [comment]
Guys I am having the same issue my recyclerview item also duplicating what is your suggestions

**Comment by kyodgorbek** [comment]
below my code 
public class IntroductionItem extends AppCompatActivity {
    public RealmList<Introduction> introductionList;

    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.introduction);

        RecyclerView recyclerView = findViewById(R.id.recyclerView);
        recyclerView.setLayoutManager(new LinearLayoutManager(getApplicationContext()));

        //TODO move this initialization to App extends Application
        Realm.init(IntroductionItem.this);
        RealmConfiguration realmConfiguration = new RealmConfiguration.Builder().build();

        final Realm realm = Realm.getInstance(realmConfiguration);

        KitabInterface kitabInterface = ApiClient.getApiService();
        Call<KitabSawti> call = kitabInterface.getIntroduction();
        call.enqueue(new Callback<KitabSawti>() {
            @Override
            public void onResponse(Call<KitabSawti> call, Response<KitabSawti> response) {

                introductionList = response.body().getIntroduction();
                recyclerView.setAdapter(new IntroductionAdapter(IntroductionItem.this, introductionList));


                realm.beginTransaction();
                for (int i = 0; i < introductionList.size(); i++) {

                    Introduction introduction = realm.createObject(Introduction.class);
                    introduction.setImage(introductionList.get(0).getImage());
                    introduction.setIntroduction(introductionList.get(0).getIntroduction());

                }
                realm.commitTransaction();

            }

            @Override
            public void onFailure(Call<KitabSawti> call, Throwable t) {

                List<Introduction> list = realm.where(Introduction.class).findAll();
                if (list != null) {

                    recyclerView.setAdapter(new IntroductionAdapter(IntroductionItem.this, list));

                }

            }

        });


    }
}

**Comment by Zhuinden** [comment]
You don't have primary keys that you seem to assume that you do have.

**Comment by kyodgorbek** [comment]
https://gist.github.com/kyodgorbek/3bcd877832f127fbf8b750b49c2b2a47 this my gist can you check it

**Comment by Zhuinden** [comment]
Introduction does not have primary key.
