### ISSUE TITLE
RealmQuery beginsWith always returns zero results

### ISSUE THREAD

**Issue by kevinvanmierlo** [realm/realm-java#2172]
When I try to use `realm.where(Test.class).beginsWith("name", "A", Case.INSENSITIVE).findAll();` it always returns zero results, even when there are a lot of results. I'm using Realm 0.87.3

**Comment by beeender** [comment]
Can you share you realm db file with us?

**Comment by kevinvanmierlo** [comment]
Thanks for the very quick response! Here is the realm db file. I'm using this exact query: `RealmResults<Town> realmResults = realm.where(Town.class).beginsWith("name", "A", Case.INSENSITIVE).findAll();`
[default.realm.zip](https://github.com/realm/realm-java/files/107009/default.realm.zip)

**Comment by beeender** [comment]
@kevinvanmierlo I tried it, but your db looks fine and I cannot reproduce the problem?
Can you please help to confirm this? By checking the result with:
1) `RealmResults<Town> realmResults = realm.where(Town.class).beginsWith("name", "A").findAll();`
2) `RealmResults<Town> realmResults = realm.where(Town.class)..findAll();`

**Comment by kevinvanmierlo** [comment]
Okay, let me first give you some more info. I'm using Android Studio 2.0 Preview 7. Using gradle 2.10 with `classpath 'com.android.tools.build:gradle:2.0.0-alpha7'`.

I used your code and logged the results:
```
D/test: begin tests
D/test: first results size: 0
D/test: second results size: 133
D/test: end tests
```

**Comment by beeender** [comment]
@kevinvanmierlo Uh... i found a naughty space before `A` in your Realm db ....
` Aalburg`
try `RealmResults<Town> realmResults = realm.where(Town.class).beginsWith("name", " A", Case.INSENSITIVE).findAll();` :sob:

**Comment by kevinvanmierlo** [comment]
@beeender Damn, I wouldn't have found that, ever! Thank you so much! My bad! :sweat_smile: Thanks for the help and quick responses! Now I can continue on my project :smile: . By the way, I just wanted to let you know this is the best database there is!!

**Comment by beeender** [comment]
Yeah! :beers:
