### ISSUE TITLE
Wrong warning if using higher version 

### ISSUE THREAD

**Issue by dawidhyzy** [realm/realm-java#2175]
Getting warning during build process:
Note: Version 0.87.0 of Realm is now available: http://static.realm.io/downloads/java/latest
but Version 0.87.3 is used.

**Comment by cmelchior** [comment]
@dawidhyzy. Thank you for reporting it. It is a known bug we are tracking here: #1966, so i'll close this as an duplicate, but you can follow #1966 for updates on this.
