### ISSUE TITLE
Partial updates with copyToRealmOrUpdate() (or other method)

### ISSUE THREAD

**Issue by guillermomuntaner** [realm/realm-java#2179]
### Feature request:
**Partial updates**

### How?
Related to issue #1853 
I agree that only updating not-null values is not a correct approach, since null can be sometimes a desired value and also because of not nullable primitive types with default values.

But, what about a call to specify a list of the fields that one want to overwrite (or preserve)?
`copyToRealmOrUpdateOverwritingFields("field1","field2")`
`copyToRealmOrUpdatePreservingFields("field1","field2")`
`copyToRealmOrUpdate(obj).preserve("field1","field2")`

In case the object does not exist in realm, the "fields to be preserved" can be initialized with default values, which i think is quite solid from a design pov.

Thoughts on this?

### My issue scenario:
Im doing a cache with Realm where objects from one class can be updated online or locally based on user interaction. This is a problem, because every single online update using copyToRealmOrUpdate() will overwrite all the local updates which i would like to keep. The option to use json would work for me, but since im dealing with complex json and doing custom deserialization plus other manipulations in order to get the POJO i am storing, having to serialize to Json just to update feels a bit excessive. 

As reference found also other related issue with a scenario like mine #1540

**Comment by beeender** [comment]
@guillermomuntaner May I know how did you create the object and pass it to `copyToRealmOrUpdate`?

Is it something like:
```
MyObject obj = new MyObject();
obj.setId(id);
obj.setString("aaa") // the field needs to be update
// then update the realm
realm.beginTransaction();
realm.copyToRealmOrUpdate(obj);
realm.commitTransaction();
```

If the above is the case, i am thinking the other interface requested by other user might be more suitable for you, see https://github.com/realm/realm-java/issues/2166
With that interface, you can use something like below:

```
realm.beginTransaction();
MyObject obj = realm.getOrCreate(id);
obj.setString("aaa") // the field needs to be update
realm.commitTransaction();
```

Wouldn't it be simpler and easier for your case?

**Comment by guillermomuntaner** [comment]
@beeender Indeed im using the first approach, because my object instances come from Retrofit GSON deserialization. Then i am using the copyToRealmOrUpdate(List<E>) to persist batches of objects into realm in a single elegant call.

Your proposed solution with getOrCreate() can be a solution to my issue, so thanks!
Thought, it requires to iterate over all the objects and copy each of the fields from the non-realm object to the realm object obj.setField(retrofitObj.getField()). Not elegant at all, but works.

I still think that being able to partialy update objets and collections of objects with a simpler interface would be a nice feature in case you are interested. Also i guess some performance improvements could be achieved when updating batches of objects together.

Thanks!

**Comment by beeender** [comment]
Yes, it does make sense to me. Let's see what can we improve from Realm side. :)

**Comment by cmelchior** [comment]
Merging this issue into #2288. Closing.

**Comment by sashatinkoff** [comment]
have you tried to use json string?

String json = "[{\"name\":\"name\",\"ts\":0}]";
realm.createOrUpdateAllFromJson(SampleAccount.class, json);

It seems like it works as expected
