### ISSUE TITLE
Array Index out of bound exception in Recycler View.(Help)

### ISSUE THREAD

**Issue by Sutirth** [realm/realm-java#2184]
I am using remove method in recycler view
  public void removeItem(int position){
            realm.beginTransaction();
            allGoalsResults.remove(position);
            notifyItemRemoved(position);
            realm.commitTransaction();
        }

and getting exception:
01-28 22:05:13.766 9508-9508/com.workoutguru.workoutcash E/AndroidRuntime: FATAL EXCEPTION: main
01-28 22:05:13.766 9508-9508/com.workoutguru.workoutcash E/AndroidRuntime: Process: com.workoutguru.workoutcash, PID: 9508
01-28 22:05:13.766 9508-9508/com.workoutguru.workoutcash E/AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: rowIndex > available rows: 6 > 5
01-28 22:05:13.766 9508-9508/com.workoutguru.workoutcash E/AndroidRuntime:     at io.realm.internal.TableView.nativeRemoveRow(Native Method)
01-28 22:05:13.766 9508-9508/com.workoutguru.workoutcash E/AndroidRuntime:     at io.realm.internal.TableView.remove(TableView.java:549)
01-28 22:05:13.766 9508-9508/com.workoutguru.workoutcash E/AndroidRuntime:     at io.realm.RealmResults.remove(RealmResults.java:542)
01-28 22:05:13.766 9508-9508/com.workoutguru.workoutcash E/AndroidRuntime:     at com.workoutguru.workoutcash.CompanyGoals_TODOGoals_Fragment$TODOGoalsAdapter.removeItem(CompanyGoals_TODOGoals_Fragment.java:590)
01-28 22:05:13.766 9508-9508/com.workoutguru.workoutcash E/AndroidRuntime:     at com.workoutguru.workoutcash.CompanyGoals_TODOGoals_Fragment$TODOGoalsAdapter$2$1.onResponse(CompanyGoals_TODOGoals_Fragment.java:522)
01-28 22:05:13.766 9508-9508/com.workoutguru.workoutcash E/AndroidRuntime:     at retrofit.ExecutorCallAdapterFactory$ExecutorCallback$1.run(ExecutorCallAdapterFactory.java:86)
01-28 22:05:13.766 9508-9508/com.workoutguru.workoutcash E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:733)
01-28 22:05:13.766 9508-9508/com.workoutguru.workoutcash E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:95)
01-28 22:05:13.766 9508-9508/com.workoutguru.workoutcash E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:146)
01-28 22:05:13.766 9508-9508/com.workoutguru.workoutcash E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5602)
01-28 22:05:13.766 9508-9508/com.workoutguru.workoutcash E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method)
01-28 22:05:13.766 9508-9508/com.workoutguru.workoutcash E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:515)
01-28 22:05:13.766 9508-9508/com.workoutguru.workoutcash E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
01-28 22:05:13.766 9508-9508/com.workoutguru.workoutcash E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
01-28 22:05:13.766 9508-9508/com.workoutguru.workoutcash E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)

**Comment by Sutirth** [comment]
Any help with this issue??

**Comment by kneth** [comment]
The error message is `rowIndex > available rows: 6 > 5` so it sounds like you are trying to remove a non-existing object.

**Comment by Sutirth** [comment]
But technically I have everything in realmDb which I am showing on recyclerView. So if I try to remove an object from the list like without following a particular order i.e say top to bottom or vice-versa I end up gettting this exception and app crashes

**Comment by beeender** [comment]
try call `notifyItemRemoved` after `commitTransaction`.

**Comment by Sutirth** [comment]
It resolves the issue of not crashing but then some data is not removed from the list it remains stale lying there

**Comment by Sutirth** [comment]
Still getting the same error.

1/com.workoutguru.workoutcash E/AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: rowIndex > available rows: 4 > 4

**Comment by beeender** [comment]
Please share you source code of adapter.

**Comment by Sutirth** [comment]
java.lang.IllegalStateException: Illegal State: Object is no longer valid to operate on. Was it deleted by another thread?

**Comment by Sutirth** [comment]
Should I share the whole recycler View code. Or just the remove item code??

**Comment by Sutirth** [comment]
[AdapterSourceCode.docx](https://github.com/realm/realm-java/files/111933/AdapterSourceCode.docx)

**Comment by Sutirth** [comment]
Is there any personal Email id where I can share ??

**Comment by cmelchior** [comment]
You can send it to help@realm.io

**Comment by beeender** [comment]
Would you please share the code in text fortmat? The source code in doc format is impossible to read...

**Comment by Sutirth** [comment]
I had sent an email to help@realm.io got a reply from Christian as well working towards resolving it

**Comment by Sutirth** [comment]
Folks I am closing issue atm not receiving any crashes due to realm

**Comment by donnguyen** [comment]
@Sutirth can you please share the root of the issue and the solution here? Thanks
