### ISSUE TITLE
Problem migraton realm 0.80.0 to 0.87.0

### ISSUE THREAD

**Issue by gildassamuel** [realm/realm-java#2188]

**Comment by cmelchior** [comment]
Please see https://github.com/realm/realm-java/blob/master/CONTRIBUTING.md#filing-issues when creating issues. That way we can easier help you.

**Comment by beeender** [comment]
@gildassamuel Since we don't have enough information to help you solve the issue, I am closing this now. Feel free to let us know if you need any help in the future with more information :)
