### ISSUE TITLE
Best practices on migration ?

### ISSUE THREAD

**Issue by kuno** [realm/realm-java#2192]
Hi all:

I am new to realm, I want to use realm in my android app, but I am bit of concerning the migration.

So where to find the docs/resources on the best practice for do migration on realm ?

Or even  is trying to avoid migration totally is a good idea ? For example:

In the first place, I have a mode called `ModelV1.java`, and if we need to update the schema later on , it just required to create another model `ModelV2.java`. In the start up time of the, the new will copy all the data in `ModelV1` on device to `ModelV2`, then delete all `ModelV1` object.

Is this doable or just a stupid idea ?

**Comment by beeender** [comment]
I won't say it is stupid, but you don't have to do it:)
You an just make changes in your `ModelV1` and create migration block for it which is not difficult at all.
see https://realm.io/docs/java/latest/#migrations for the general doc
and examples: https://github.com/realm/realm-java/tree/master/examples/migrationExample

**Comment by kuno** [comment]
thanks for the warm reply

Especially the "Not stupid" part : >

**Comment by beeender** [comment]
You are welcome!
Do you have rough idea about how migration works? Shall we close this issue?

**Comment by kuno** [comment]
I am reading the doc you given.

Please let me close this issue, once I got confidence.

**Comment by beeender** [comment]
No problem, take your time :smile:

**Comment by beeender** [comment]
Hello @kuno ! How is it going on? Are we safe to close this issue now? You can always have a chance to ask a question on stackoverflow or create another github issue here :smile:
