### ISSUE TITLE
JavaCV and Realm cause UnsatisfiedLinkError

### ISSUE THREAD

**Issue by Rakatan** [realm/realm-java#2195]
Hello,

I am writing here fully aware of issue #1640. 
I am experiencing a similar issue, using the JavaCV libraries however.

Both Realm and JavaCV work fine independently, however when put together JavaCV's _FFmpegFrameGrabber_ class crashes upon calling the _start()_ method. And it is most likely not the only case.

I have included both of these libraries in a new project like so:

```
compile group: 'org.bytedeco', name: 'javacv', version: '1.1'
compile group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.0.0-1.1', classifier: 'android-arm'
compile group: 'org.bytedeco.javacpp-presets', name: 'opencv', version: '3.0.0-1.1', classifier: 'android-x86'
compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '2.8.1-1.1', classifier: 'android-arm'
compile group: 'org.bytedeco.javacpp-presets', name: 'ffmpeg', version: '2.8.1-1.1', classifier: 'android-x86'
       
compile 'io.realm:realm-android:0.87.2'
```

And i have added these packaging options:

```
packagingOptions {
        exclude 'lib/arm64-v8a/librealm-jni.so'

        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/maven/org.bytedeco.javacpp-presets/ffmpeg/pom.properties'
        exclude 'META-INF/maven/org.bytedeco.javacpp-presets/ffmpeg/pom.xml'
        exclude 'META-INF/maven/org.bytedeco.javacpp-presets/opencv/pom.properties'
        exclude 'META-INF/maven/org.bytedeco.javacpp-presets/opencv/pom.xml'
    }
```

The error i'm receiving is:

```
FATAL EXCEPTION: main
Process: com.hypersensesoftware.javacvtest, PID: 6570
java.lang.UnsatisfiedLinkError: org.bytedeco.javacpp.avutil
  at java.lang.Class.classForName(Native Method)
  at java.lang.Class.forName(Class.java:324)
  at org.bytedeco.javacpp.Loader.load(Loader.java:413)
  at org.bytedeco.javacpp.Loader.load(Loader.java:381)
  at org.bytedeco.javacpp.avformat$AVFormatContext.<clinit>(avformat.java:2597)
  at org.bytedeco.javacv.FFmpegFrameGrabber.startUnsafe(FFmpegFrameGrabber.java:386)
  at org.bytedeco.javacv.FFmpegFrameGrabber.start(FFmpegFrameGrabber.java:380)
```

The behaviour is the same on both a Nexus 5X (64 bit) and Samsung Galaxy S4 (32bit).

I will post any necessary additional information if requested.

Any help is greatly appreciated.

**Comment by cmelchior** [comment]
Have you tried open the resulting dex file and see which `.so` files is shipped with your app. I'm guessing that some library are still bundling the wrong native files with your app?

**Comment by Rakatan** [comment]
I have decompiled the apk using dex2jar as described [here](http://stackoverflow.com/questions/1249973/decompiling-dex-into-java-sourcecode). I am not sure what to look for. I can only see the compiled .class files.

**Comment by Rakatan** [comment]
The issue has been cracked. You can find the answer [here](http://stackoverflow.com/questions/35066470/using-javacv-and-realm-together-causes-java-lang-unsatisfiedlinkerror/35088655#35088655)

Thank you @cmelchior for your help!
