### ISSUE TITLE
 Unrecoverable error. mremap(): failed: Out of memory in io_realm_internal_SharedGroup.cpp line 188

### ISSUE THREAD

**Issue by stefencanning** [realm/realm-java#2197]
i am having an issue with memory usage on an android  app while downloading, i believed it was due to the data being saved being too big as the app was using 70mb of memory during sync when it crashed with the above exception, scaling down the images on the server reduced the memory down to only 20mb however it still crashed, thinking i was doing too much in one transaction i began transaction and committed it once per record instead of once per 500, however the issue still occurs, i then changed it to opening and closing the realm for each record instead of just beginning and committing the transaction and the issue still occurs, 
the exception is:
io.realm.exceptions.RealmError: Unrecoverable error. mremap(): failed: Out of memory in io_realm_internal_SharedGroup.cpp line 188
at io.realm.internal.SharedGroup.nativeCommitAndContinueAsRead(Native Method)
at io.realm.internal.SharedGroup.commitAndContinueAsRead(SharedGroup.java:99)
at io.realm.internal.ImplicitTransaction.commitAndContinueAsRead(ImplicitTransaction.java:60)
at io.realm.internal.SharedGroupManager.commitAndContinueAsRead(SharedGroupManager.java:116)
at io.realm.BaseRealm.commitTransaction(BaseRealm.java:292)
at io.realm.Realm.commitTransaction(Realm.java:108)

the sync happens in a background thread with no other threads running and the realm is closed after opening and the device is a Galaxy Tab S, model SM-T800 running android version 5.0.2, the realm version im using is 0.87.1
i was wondering if there was anything else i could try to solve this issue

**Comment by cmelchior** [comment]
Hi @stefencanning 

That error can happen in a number of scenarios, the most likely being:

1) You a trying to commit a too large transaction
2) You are not closing your Realms on background threads, and keep making new threads.
3) You have too many open Realms across threads that doesn't auto update, hence are "different" versions.

We really need more information to give an informed answer, but 2) is probably the most likely. I would start by making sure that your Realm is fully closed on all background threads.

**Comment by stefencanning** [comment]
thank you for the reply, after much trial and error the issue seems to have been fixed by saving that particular record in its own realm data file
