### ISSUE TITLE
IllegalStateException: Changing Realm data can only be done from inside a transaction

### ISSUE THREAD

**Issue by Durai123** [realm/realm-java#2199]

**Comment by cmelchior** [comment]
Please see https://github.com/realm/realm-java/blob/master/CONTRIBUTING.md#filing-issues when creating issues. That way we can easier help you.

**Comment by beeender** [comment]
Take a look at https://realm.io/docs/java/latest/#writes :)

@Durai123 Since we don't have enough information to help you solve the issue, I am closing this now. Feel free to let us know if you need any help in the future with more information :)
