### ISSUE TITLE
findFirstAsync() asObservable doesn't always return when items are not found

### ISSUE THREAD

**Issue by grahamsmith** [realm/realm-java#2200]
### Goals + Expected Results

To load a single object from the database as an observable by querying it's ID, while returning null (or error) when an item with a specified ID is not found, as specified in the JavaDocs.

### Actual results

Loading a single valid item by its ID is fine, the first item emitted is not loaded so the filter returns false. When the RealmObject is loaded then the filter returns true on the seconds pass and the object is passed along.

When an empty ID is passed to the query, it executes and the same process begins where a non loaded item is filtered out but then nothing is ever returned. According to the docs, it should yield a null object.

Even if this is expected behaviour, it means it becomes impossible to detect if an item wasn't found or if a query is just taking an extremely long time.

### Steps + Sample

Call `getFooById()` with an empty String.

    getFooById("").observeOn(AndroidSchedulers.mainThread()).subscribe(new FooSubscriber());

    public Observable<Foo> getFooById(String id) {

        return realm.where(Foo.class)
                .equalTo("id", id)
                .findFirstAsync()
                .asObservable()
                .filter(this::filterResults);
    }

    private boolean filterResults(Foo result) {
        return result.isLoaded();
    }

    private class FooSubscriber extends Subscriber<Foo> {

        @Override
        public void onCompleted() {
            doCompletedThing();
        }

        @Override
        public void onError(Throwable error) {
            //handle errors
        }

        @Override
        public void onNext(Foo foo) {
            //do something with foo
            onCompleted();
        }
    }

### Versions

Android Studio 1.5.1
RxJava 1.0.17
Realm 0.87.2

**Comment by cmelchior** [comment]
Hi @grahamsmith 
Thanks for a detailed report and sorry for the late response. Due to `findFirstAsync` always returning a placeholder object, the expected behaviour should be that your should receive a object where `obj.isLoaded() == true && obj.isValid() == false`. This doesn't seem to be happening though. I'll look closer into it.

**Comment by dalinaum** [comment]
Does #2240 resolve this?

**Comment by cmelchior** [comment]
Yes

**Comment by unidaysgraham** [comment]
@cmelchior thanks for looking at this :) When is the release with this in scheduled?

**Comment by MohamadAtieh** [comment]
I am currently experiencing the same issue as OP: Retrieving the RealmObject onNext() but onCompleted is never fired. 

Realm 0.87.5

Is this fixed in the newer releases?

**Comment by Zhuinden** [comment]
@MohamadAtieh 0.88.0
> RealmChangeListeners did not triggering correctly if findFirstAsync() didn't find any object. findFirstAsync() Observables now also correctly call onNext when the query completes in that case (#2200).

**Comment by unosmiles** [comment]
I'm still able to replicate this issue, where realmObject.isLoaded() returns false from a rxJava filter and never is set to true, meaning nothing is ever emitted.

**Comment by Zhuinden** [comment]
@unosmiles I'd assume the object doesn't exist because it gets deleted over time, no?

@MohamadAtieh I didn't even notice, but `onCompleted()` is not even meant to be called. Realm uses `Observable` to send the notifications from `RealmChangeListener` until you unsubscribe, it doesn't magically stop emitting and therefore nor does it ever truly "complete".

**Comment by unosmiles** [comment]
@Zhuinden In this case, the object does not even exist in the database. I would expect Realm to notify me of such.

**Comment by Zhuinden** [comment]
@unosmiles yes I re-read what you said and realized that's what you'd like to achieve, and edited my response out.

You're right. Please note I'm not an official Realm member. Your issue sounds the same as https://github.com/realm/realm-java/issues/3138 . I'm surprised that never got fixed, but my workaround is also in that thread.

**Comment by MohamadAtieh** [comment]
@Zhuinden Why would it expect someone to unsubscribe? I understand the idea that's asynchronous but it's better to have a built-in mechanism that stops emitting if no data is retrieved and call `onCompleted()` on its own.

**Comment by Zhuinden** [comment]
@MohamahAtieh I'm not entirely sure for the case of RealmObject change listeners, but RealmResults is auto-updated whenever the underlying table is written to. 

But if the default behavior for RealmObject Observables doesn't suit your case, then you can supply your own `RxObserableFactory`

**Comment by cmelchior** [comment]
What @Zhuinden said. That is the entire purpose of the `RxObservableFactory`. If you want to make it easier on yourself you just extend `RealmObservableFactory` and make the modifications there. Register it through `RealmConfiguration.rxFactory()`
