### ISSUE TITLE
Support `RealmResults.indexOf`

### ISSUE THREAD

**Issue by beeender** [realm/realm-java#2203]
Although this is not support by core, we can support it either in java or JNI layer.

**Comment by cmelchior** [comment]
This might be a bit tricky especially considering #1363 as well. As part of #602 the plan is to make RealmResults more stable, but we still need to investigate the differences between RealmList and RealmResults as currently the semantics are different.

**Comment by cmelchior** [comment]
Support for this is added as part of  #2345
