### ISSUE TITLE
We Sync too!

### ISSUE THREAD

**Issue by sahal2080** [realm/realm-java#2207]
From realm/realm-cocoa#913
@blwinters:

> In light of Parse's announcement to shut down in a year, now might be a good time to share some details regarding your plans for sync. There are a lot of developers treading water in the sync market and it could benefit Realm adoption greatly if you made a public statement.

We on the Android side, though admittedly not as privileged as our iOS counterparts, still have the same aspirations of one day being able to sync without constantly worrying about failure.

You may say I'm a dreamer, but I'm not the only one. ;-)

**Comment by timanglade** [comment]
Hi @sahal2080 for now let’s please keep all the feedback on sync in Realm, whether it’s for iOS, Android or others on realm/realm-cocoa#913. It started on the Cocoa repo for historical reasons but that issue is the right one to discuss Sync for Android as well — no need for a separate issue.
