### ISSUE TITLE
Kotlin: Realm mediators do not get generated across modules

### ISSUE THREAD

**Issue by asarazan** [realm/realm-java#2208]
Repro:
* Create an android project with multiple library modules.
* Define a `RealmObject` subclass in each module (along with `@RealmClass` annotation)
  * `Realm.getInstance(context)` fails with "this class is not part of the schema"
  * Explicit declaration of modules fails with "no mediator"

Problem is solved by writing `@RealmModule` declarations in java and in their own modules.

**Comment by kneth** [comment]
Thanks. As you can see I have added it to our high priority backlog so we don't forget to document it.

**Comment by cmelchior** [comment]
I wonder if this is related to #2356. @zaki50 are you testing this scenario as well?

**Comment by zaki50** [comment]
@cmelchior Not yet, but I'll test multi-module project in #2356

**Comment by zaki50** [comment]
It seems to be working with multiple library modules.

[realm-library-test_issue2208.zip](https://github.com/realm/realm-java/files/165149/realm-library-test_issue2208.zip)

**Comment by cmelchior** [comment]
Verified that this works with #2358, so closing this.
It will be released as part of 0.88
