### ISSUE TITLE
Out of memory in io_realm_internal_SharedGroup.cpp

### ISSUE THREAD

**Issue by douglasjunior** [realm/realm-java#2209]
I'm trying to figure out the reason for getting these exceptions, but so far only have suspicions.

Is throwing an exception when running `realm.commitTransaction()`:

```java
FATAL EXCEPTION: pool-10-thread-1
  Process: com.myApplication, PID: 18378
  io.realm.exceptions.RealmError: Unrecoverable error. mremap(): failed: Out of memory in io_realm_internal_SharedGroup.cpp line 188
      at io.realm.internal.SharedGroup.nativeCommitAndContinueAsRead(Native Method)
      at io.realm.internal.SharedGroup.commitAndContinueAsRead(SharedGroup.java:99)
      at io.realm.internal.ImplicitTransaction.commitAndContinueAsRead(ImplicitTransaction.java:60)
      at io.realm.internal.SharedGroupManager.commitAndContinueAsRead(SharedGroupManager.java:116)
      at io.realm.BaseRealm.commitTransaction(BaseRealm.java:292)
      at io.realm.Realm.commitTransaction(Realm.java:108)
      at com.myApplication.activity.PlantingActivity$UpdateData.run(PlantioActivity.java:777)
      at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
      at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
      at java.lang.Thread.run(Thread.java:841)
```

## Scenario:

In this "Activity" has 3 Threads running constantly, asynchronous, every 1 to 3 seconds.

In each Thread I open and close a instance.
```java
Realm realm = Realm.getDefaultInstance();
try {
    // code here
} finally {
   realm.close();
}
```
Sometime it can happen concurrent readings, but never occurs concurrent writes. In no time I have removed, only insert and update.

I saw that this problem occurred in #1639, but I have no choice, I have to keep all the threads. And at some time there may be 3 instances opened at the same time.

## Suspicion:

The problem only began to occur after some time of use, so I believe that the database size can be a problem. It is around 25MB. (My application generates a lot of data, as we are discussing here #2015)

If call `Realm.compactRealm(config)`, everything works for a while, then starts the problem occurs again.

I am working the wrong way? It would be a limitation of the Realm?

Thank you

*Sorry to open some issues. My application is still in development, so I am evaluating whether the Realm will fulfill the requirements.*

**Comment by beeender** [comment]
25MB should not be a big Realm file.

1. If you are using Realm in thread without a looper, that is very important to close the Realm or calling `Realm.refresh` to release the reference to old data.  Realm is a MVCC database (Multiversion concurrency control), which means that multiple versions of the data might exist at the same time, and will cost more memory than expected. Especially if you have more Realm instances in the non-looper threads, and writing data continuously, the db will grow quickly.
2. If you did a `Realm.setAutoRefresh(false)` in a looper thread, then it would have the same problem with 1).
2. If you have very big transaction, consider to separate it into a smaller one.

**Comment by beeender** [comment]
If non of above is your problem, would you please share you project with us privately? to help@realm.io.

**Comment by zsavely** [comment]
Hi!
My scenario is much simplier. I emailed a link to a repository which also gets `Out of memory` to help@realm.io.

**Comment by beeender** [comment]
Got it! I am checking now...

**Comment by douglasjunior** [comment]
Thanks for answering @beeender.

Two of the thread has loop, one that updates the Views and another that sends HTTP requests. Both are just reading the Realm. They run every 2 or 3 seconds.
Implementation:
```java
private Thread thread1 = new Thread(){
     private run(){
         Realm realm = Realm.getDefaultInstance();
         try {
             while(...){
                  realm.refresh();
                  // read data
                  Thread.sleep(2000);
             }
         } finally {
           realm.close();
         }
     }
};
```
Executing:
```java
private ThreadPoolExecutor threadExecutor = (ThreadPoolExecutor) Executors.newCachedThreadPool();
...
 threadExecutorGeral.execute(thread1);
 threadExecutorGeral.execute(thread2);
```
I do not write in concurrent transactions. Only one thread is writing the Realm. And has not loop. This thread is executed when reading Bluetooth information, every 1 second. Each time is updated approximately 20-50 objects, and can eventually create more 20-50.
```java
new Thread(){
    private run(){
      Realm realm = Realm.getDefaultInstance();
      try {
        // parse bluetooth data and update objects
      } finally {
        realm.close();
      }
    }
}.start();
```
To test, I'm changing the way the reading Threads work, I'm doing this:
```java
private Thread thread1 = new Thread(){
     private run(){
          while(...){
             Realm realm = Realm.getDefaultInstance();
             try {
                  // read data
                  Thread.sleep(2000);
             } finally {
                 realm.close();
             }
         }
     }
};
```
You recommends setting `ream.setAutoRefresh(true)` in all instances?

**Comment by beeender** [comment]
@douglasjunior By default, for looper thraed, auto refresh is enabled. You don't have to call it.

In your first `thread1` example, it relies on GC to free some native resource, like the RealmObject read from the Realm instance. And the `refresh` at the beginning of the loop might create overhead for refeshing all the RealmObjects created in previous loop if they haven't been GCed yet.

In the 2nd `thread1` example, it would be much better. Since all the native resources created in the loop can be freed by calling `realm.close()`

Does it still have problem with the changes in the 2nd `thread1`?

**Comment by douglasjunior** [comment]
I'm testing right now.

The memory does not exceed 8MB Debug. I have been running the app for 15 minutes.

![captura de tela 2016-02-02 as 09 26 41](https://cloud.githubusercontent.com/assets/1512341/12748159/a83fc576-c98f-11e5-8b7e-032d4f2df59d.png)

**Comment by kneth** [comment]
@douglasjunior Did you reach a conclusion? The screenshot indicated a memory consumption which fluctuates around 8 MB.

**Comment by douglasjunior** [comment]
*My God, your comment appears while I was writing this one. hahahahahaha*

---------------

Apparently the problem is resolved. Now I'm opening and closing instances each loop.

Previously I was open an instance when start the thread, each loop I did refresh before reading the data, and in the end closed the instance.

Yes, the memory is around 8 MB, even before the changes. But I think the memory used by C ++ is not displayed on the Debug, is not it?

I will continue with the tests, if it happens again I go back to report.

**Comment by kneth** [comment]
Yes, the memory used by C++ is not really reported. Estimating memory consumption is a black art in Android.

**Comment by kneth** [comment]
@douglasjunior I have closed the issue but never hesitate to either reopen or create a new issue.

**Comment by douglasjunior** [comment]
Ok, thanks!
