### ISSUE TITLE
Relational接口

### ISSUE THREAD

**Issue by badboyhb** [realm/realm-java#2212]
Realm提供了Object接口，软件可以以Object方式访问数据。

我们希望Realm也同时能提供Relational接口，软件可以以Table、Row、Column、Cursor的方式访问数据。特别是在使用Android ContentProvider时，我们希望Realm与ContentProvider无缝连接。

**Comment by badboyhb** [comment]
Realm provides Object interface, software can access data by the Object interface.

We hope Realm also provides Relational interfaces, software can access data by Table, Row, Column, Cursor . Especially when using Android ContentProvider, we hope Realm and ContentProvider seamlessly.

**Comment by badboyhb** [comment]
Realm provides Object interface, software can access data by the Object interface.

We hope Realm also provides Relational interfaces, software can access data by Table, Row, Column, Cursor . Especially when using Android ContentProvider, we hope Realm and ContentProvider interact seamlessly.

**Comment by beeender** [comment]
已经有 #438 在追踪这个问题啦。为了方便期间，我把这个问题关了，咱们可以在 #438 里讨论。

多谢您的反馈！
