### ISSUE TITLE
RealmResult query again

### ISSUE THREAD

**Issue by XhinLiang** [realm/realm-java#2215]
I use Realm for my Android Project. In the MainActivity users can choose different group of Contact,the query RealmResult will be show in RecyclerView.When users choose another group ,it means that I have to query the 'Contact' again and reset the Adapter. In my opinion, RealmResult can be query again (NOT IN THIS QUERY RESULT BUT IN THIS REALMOBJECT), and the RealmResult will be more ReactiveX.

**Comment by cmelchior** [comment]
Hi @XhinLiang 

I am not entirely sure what you mean? The Adapter would not know what to do with completely new data anyway and would have to reset all it's state.

If you want you can just add a method like `replaceResults(RealmResults results)` to your adapter that does something like:

```
public void replaceResults(RealmResults results) {
  this.data = results;
  notifyDataSetChanged();
}
```

Then you don't have to create a whole new Adapter class.

**Comment by beeender** [comment]
@cm I think what @XhinLiang means is if we can have an interface like `RealmQuery RealmResults.resetQuery()`
then it can be done like:
```
results.resetQuery().where(MyModle.class).equalTo("name", newCondition);
```
Then the original RealmResults is just updated according to the new query. So the adapter doesn't have to be changed at all.

The problem is I am not quite sure this fit the TableView well, and when is the good timing to trigger the listener.

**Comment by XhinLiang** [comment]
`RealmResult` will be update when Realm is updated.
If there is an interface like `RealmResults.resetQuery()` the `Adapter` can update without I call `replaceResults(RealmResults results)`.

**Comment by cmelchior** [comment]
That would go against the design goal for RealmResults, which is to encapsulate the results of 1 query. The only benefit you are gaining is to avoid creating a new RealmResults object. The RecyclerView would still have to redraw everything from scratch.

**Comment by XhinLiang** [comment]
@cmelchior 
The way you provided is just I coded.

**Comment by XhinLiang** [comment]
@cmelchior 
Thanks for your help.
Actually I just wanted to make the code more elegant and more 'Reactive'.
Thanks again.

**Comment by cmelchior** [comment]
Hi @XhinLiang 
No problem, we welcome any suggestions. In this case we just feel that extending RealmResults in that direction would go against our goals for the class, but I'm glad you could use the alternative solution.

**Comment by hardysim** [comment]
Hey, I've just came across this issue. I'm using android's `LiveData` and the `LiveRealmData`-class from https://academy.realm.io/posts/android-architecture-components-and-realm. This all works fine as long as the query does not change.

In my case, my android-fragment is subscribed to the `RealmResult` (which is now a `LiveData`, actually updated by a `RealmChangeListener` in it) so when the data in the result changes, my fragment is notified. All fine here.

---

Now, I need to **update the query** of the **existing `RealmResult`** my fragment is subscribed to (e.g. change the sorting). So basically just the idea of `resetQuery()` above (re-use the existing `RealmResult` with a whole new query).

This is not seem possible, right? But if I need to create a new `RealmResult`, I'd need to unsubscribe from the old one, create a new one and subscribe to it. It would be far easier to just re-use the existing result (even if this is kind of a hack).

Any chance to get this added to Realm?

**Comment by cmelchior** [comment]
Yes, creating a new "query" for the same `RealmResults` is probably not something we want to support as it breaks the encapsulation we have at that layer, namely that each `RealmResults` matches one query.

In your case, I would just extend your LiveData class with that capability, it should be fairly trivial and downstream consumers don't have to know about that, but it isn't something that Realm needs to provide?

**Comment by Zhuinden** [comment]
@hardysim that is completely expected and you'd have the same problem when using `Flowable<List<T>>` or even `Flowable<PagedList<T>>` from AAC/Room or even SQLBrite or your own reactive database wrapper where you need a new query to observe.

Refer to https://stackoverflow.com/questions/49192540/paging-library-filter-search/49193372#49193372

**Comment by hardysim** [comment]
Cool, https://stackoverflow.com/questions/49192540/paging-library-filter-search/49193372#49193372 seems to do the trick. Thank you very much.
