### ISSUE TITLE
StackOverflowError with transaction inside RxJava map()

### ISSUE THREAD

**Issue by Minkfan** [realm/realm-java#2216]
While getting my objects from realm, I want to iterate and change some of them.
So thats what I'm doing:

``` java

private RealmResults<FeedItem> setHeaderDateInFeedList(RealmResults<FeedItem> feedList) {
   if (feedList == null || feedList.size() < 1) {
       return feedList;
   }
   realm.beginTransaction();
   for (int i = feedList.size() - 1; i >= 0; i--) {
       feedList.get(i).setShowDate(true);
   }
   realm.commitTransaction();
       
   return feedList;
}
```
than using it with my `Observable`:
``` java
realm.where(FeedItem.class)
                .findAllSortedAsync("date", Sort.DESCENDING)
                .asObservable()
                .map(this::setHeaderDateInFeedList)
                .map(feedItems -> feedItems.subList(0, feedItems.size()))
                .subscribe(subscriber);
```

So, without `.map(this::setHeaderDateInFeedList)` all goes fine and I can populate my adapter with List<FeedItem>. But the map operator causes recursive call of itself (when there is a realm transaction inside) till I get StackOverflowError. I just can't beleive my eyes, but i've seen this in debug.
So, what can it be and how to avoid it?

**Comment by cmelchior** [comment]
Hi @Minkfan
RealmResults are live results (see  https://realm.io/docs/java/latest/#auto-updating-results). This means that when you commit changes to RealmObjects it will trigger `onNext` for relevant queries. In this example it is being re triggered as you are changing FeedItem object. Our change-detection is not yet intelligent enough to detect that you are actually not changing the number of results in your `findAll` query, so it will update the RealmResult and emit a `onNext` event which is why you get the loop.

This will be fixed once we introduce fine-grained notifications here: #989 

In the meantime, If you want to break the loop you can do something like only accepting the first results being sent:

```
realm.where(FeedItem.class)
                .findAllSortedAsync("date", Sort.DESCENDING)
                .asObservable()
                .filter(this::isLoaded)
                .first()
                .map(this::setHeaderDateInFeedList)
                .map(feedItems -> feedItems.subList(0, feedItems.size()))
                .subscribe(subscriber);
```

**Comment by Minkfan** [comment]
Thank you for the quick reply, @cmelchior !
Do you mean I must manually trigger some flag and return it in `isLoaded` method?
When I use only `first()` operator, the list always returns with 0 elements, actually without it, realm observable's `onNext` called twice, first with 0 than with 7 elements

**Comment by cmelchior** [comment]
Hi @Minkfan 
Sorry for the late reply.

`isLoaded()` is a method on the `RealmResults` class. It will be true if the results are actually available, e.g. when the async query is done. This is also why you see two `onNext` emissions. One with the empty result set (which can be used to prepopulate lists) and then one when the query completes. If you don't care about the initial empty RealmResults, you filter it by using `results.isLoaded()` as in my example above.

**Comment by Minkfan** [comment]
Hello again, @cmelchior !
Was a bit confused by `.filter(this::isLoaded)` operator, done `.filter(results -> results.isLoaded)`, now works like a charm!
One last question before closing the issue, why so strange behavior: empty emission? Where I can read about it (maybe part of the source code)?

**Comment by cmelchior** [comment]
Some UI components benefit from having empty results straight away. If you want to change that behaviour you can create your own `RxObservableFactory` that overrides the behaviour. You can see how here: https://realm.io/docs/java/latest/#rxjava

The factory being used as the default is this one: https://github.com/realm/realm-java/blob/master/realm/realm-library/src/main/java/io/realm/rx/RealmObservableFactory.java

**Comment by Minkfan** [comment]
Thanks a lot for your great work!
