### ISSUE TITLE
Add Wire to Other Libraries section

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#2228]
We should add Wire to the Other Libraries section on the website.

See http://stackoverflow.com/questions/34818971/convert-protobuff-class-as-model-and-store-its-value-using-realm/34819639#34819639

and https://github.com/square/wire

**Comment by cbush** [comment]
We are revamping the Realm docs. We're not ignoring this issue -- we've read through every one of them, and we'll be sure to address this as part of our updates. We're closing the GitHub issues and creating new JIRA tickets to track the work at a high level.
