### ISSUE TITLE
Use "Realm" instance in multi-thread environment.

### ISSUE THREAD

**Issue by badboyhb** [realm/realm-java#2229]
Realm.getInstance() takes long time. So I do the following. Is it OK?

public class RealmFactory {
    final static String LOG_TAG = "RealmFactory";

    static private class RealmWrapper {
        final private Realm mRealm;

        private RealmWrapper(Realm realm) {
            mRealm = realm;
        }

        @Override
        protected void finalize() throws Throwable {
            if (mRealm != null && !mRealm.isClosed()) {
                Log.v(LOG_TAG, "Close Realm " + mRealm);
                mRealm.close();
            }
            super.finalize();
        }
    }

    private static final ThreadLocal<RealmWrapper> threadRealm = new ThreadLocal<RealmWrapper>();

    public static Realm getRealm(RealmConfiguration config) {
        RealmWrapper r = threadRealm.get();
        if (r == null) {
            r = new RealmWrapper(Realm.getInstance(config));
            threadRealm.set(r);
            Log.v(LOG_TAG, "Create Realm " + Thread.currentThread().getId());
        }
        return r.mRealm;
    }

}

**Comment by cmelchior** [comment]
Hi @badboyhb 
Realm actually has it's own internal caching that looks more or less exactly like what you have there, so adding your own caching on top will not give you any performance improvements.

The first time you open a Realm instance it validates that the file matches your data model classes. This is not cheap, but we cache the result, so any subsequent access should be much faster.

You can see this if you measure two `getInstance()` calls right after each other.

**Comment by beeender** [comment]
And also, Realm instance needs to be created and closed in the **same** thread. In you example, the close will happen in the finalize daemon thread, an `IllegalStateException` will be thrown there, and the underlying resource won't be released in this way.

**Comment by badboyhb** [comment]
@cmelchior @beeender thanks

But  getInstance() does take 20ms every time.

**Comment by cmelchior** [comment]
That sounds very strange. Are you closing your Realm in between calling getInstance?

**Comment by badboyhb** [comment]
Yes, I close it every time

**Comment by cmelchior** [comment]
That is the problem. If a Realm file gets fully closed we have to validate the schema when you open it again. You can try keeping an instance alive for the duration of your app by following this guide here: https://realm.io/docs/java/latest/#controlling-the-lifecycle-of-realm-instances

**Comment by badboyhb** [comment]
I cannot keep an instance alive , because I dont know which thread will call the method.
The thread was created by Android Binder.

**Comment by cmelchior** [comment]
It is fine to keep an instance alive on the UI thread even if you use it primarily on a binder thread as we cache the validation across all threads. The important thing is that if you at any time close _all_ access to the Realm file we have to validate it again when you reopen it as there is no guarantee that it might have been changed in the meantime.

**Comment by badboyhb** [comment]
I see.
@cmelchior, Thanks very much
