### ISSUE TITLE
Support `equalsIn` for queries 

### ISSUE THREAD

**Issue by beeender** [realm/realm-java#2230]
Question from SO
http://stackoverflow.com/questions/35174919/in-operation-in-realm/35191927?noredirect=1#comment58102206_35191927

It would be good if we support `RealmQuery.equalsIn(String fieldName, List values)` to achieve `IN` feature in SQL like below:

```
 select * from Products where productId IN ('P101','P102');
```

Currently user has to chain a long list of `or` to do that.

**Comment by cmelchior** [comment]
This is already being tracked here: #841 
Closing this as a duplicate.
