### ISSUE TITLE
Working on all Java platforms outside of Android (OS X, Linux, Windows)

### ISSUE THREAD

**Issue by virl** [realm/realm-java#2241]
Realm-java needs to be able to work on desktop OSes outside of Android.
The main use case for that is tooling for database pre-seed: when you use Realm in Windows/Linux console app to pre-seed database with static data and the use that database during mobile application build for iOS/Android.

**Comment by kneth** [comment]
Thanks for the suggestion. Currently, Realm has a few Android specific dependencies.

**Comment by grahamsmith** [comment]
I would like to +1 this too. Maybe some enhancements to the Realm data browser would be an easy way forward, such as Class creation and importing from CSV etc?

**Comment by kneth** [comment]
@grahamsmith The Realm Browser is able to generate classes based on a Realm file. But please create issues at https://github.com/realm/realm-browser-osx (I'm thinking of the CSV importer suggestion).

**Comment by grahamsmith** [comment]
Sorry didn't mean to cross pollinate issues. Will raise the ticket.

**Comment by dusiema** [comment]
I have the exact same requirement (pre-seed DB outside of mobile world, i.e. in a java RCP Client) and then use the DB in an Android and iPhone app. Too bad it's not yet supported outside of Android. I would love to give Realm a try instead of SQLite (and core data).

As the site says that this might get supported in the future what would be the best way to follow this? This issue? Mailing list?

**Comment by astigsen** [comment]
> I have the exact same requirement (pre-seed DB outside of mobile world, i.e. in a java RCP Client) and then use the DB in an Android and iPhone app

Could you use the node.js version of Realm for this (https://realm.io/news/first-object-database-realm-node-js-server/)?

**Comment by jirungaray** [comment]
> Could you use the node.js version of Realm for this (https://realm.io/news/first-object-database-realm-node-js-server/)?

I'm the same situation as this guys, I have a Java backend and desperately need to update realm files, without this i can´t have a fully automated process ( I need a helper app to create BD files!).

Adding a second backend in a different language just to pre populate the BD seems like overkill.
Being able to create realm files in Java is a MUST for me if I am to present this a a viable production ready alternative.

**Comment by cmelchior** [comment]
Folding this into #2339
