### ISSUE TITLE
"Configuring a Realm" example a bit confusing

### ISSUE THREAD

**Issue by cbotman** [realm/realm-java#2250]
Hi there,

This is only a small thing, but I made a mistake so thought I'd mention it. In the current documentation for configuring a Realm <ttps://realm.io/docs/java/0.87.4/#configuring-a-realm>, this is the code for the first example:

```
// The RealmConfiguration is created using the builder pattern.
RealmConfiguration config = new RealmConfiguration.Builder(context)
  .name("myrealm.realm")
  .encryptionKey(getKey())
  .schemaVersion(42)
  .setModules(new MySchemaModule())
  .migration(new MyMigration())
  .build();

// These two are equivalent
Realm realm = Realm.getInstance(context);
Realm realm = Realm.getInstance(new RealmConfiguration.Builder(context).build());
```

Reading that example, I assumed the configuration object would be applied automatically when I called Realm.getInstance.

After some more tinkering (and of course, reading the next part of the documentation), I realised I need to either use `Realm.setDefaultConfiguration(config);` or `Realm.getInstance(config)`.

I think it would be clearer up front if that first code example made use of the config object it created. The lines after "These two are equivalent" are almost illustrating a different point--that a default config object is created when you only pass in the context. 

Perhaps the first example should be:

```
// The RealmConfiguration is created using the builder pattern.
RealmConfiguration config = new RealmConfiguration.Builder(context)
  .name("myrealm.realm")
  .encryptionKey(getKey())
  .schemaVersion(42)
  .setModules(new MySchemaModule())
  .migration(new MyMigration())
  .build();
// Use the config
Realm realm = Realm.getInstance(config);

// Note these two are equivalent
Realm realm = Realm.getInstance(context);
Realm realm = Realm.getInstance(new RealmConfiguration.Builder(context).build());
```

Thanks and keep up the good work. :)

Regards,
Chris

**Comment by kneth** [comment]
Thanks for the suggestions. If you find it confusing, it is safe to assume that many others find it confusing.

**Comment by cbotman** [comment]
Thanks, kneth.

**Comment by cmelchior** [comment]
Fixed by https://github.com/realm/realm.io/pull/1784
