### ISSUE TITLE
createOrUpdate method should have listeners 

### ISSUE THREAD

**Issue by mahmoudgalal2015** [realm/realm-java#2251]
i'm facing a problem in my requirement to push a notification to the user that show how many records have been updated and how many records did created. but i can't see any direct method that notify me  what did happened to the record. any help ?

**Comment by cmelchior** [comment]
Hi @mahmoudgalal2015 
That is inherently impossible to do in the generic case, as you might be updating different classes in an object graph, which means it will be very difficult to give you any meaningful results back.

If you have such a requirement, it is easier to implement the update logic yourself, so you can keep track of what is required by your use case. You can look in our generated `*RealmProxy` classes for inspiration on how to do that.
