### ISSUE TITLE
Support creating an initial dataset for a Realm

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#2254]
From this question: http://stackoverflow.com/questions/35304125/how-can-i-create-a-realm-database-with-initial-data-for-my-android-app

It would make sense to allow people to specify a closure for creating a initial dataset when a Realm file is created for the first time.

Proposal for API:

```
RealmConfiguration config = new RealmConfiguration.Builder(context)
  .initialData(new RealmTransaction() {
     @Override
      public void excute(Realm realm) {
        // Just reuse our existing transaction concept.
        // Right now users have to keep track of this in SharedPreferences or similar, which is something
        // that Realm could track just as easily.
      }
  })
  .build();

// The first time the file is created or reset due to a RealmMigrationNeeded, it will execute the initialData transaction.
Realm realm = Realm.getInstance(config);
```

Thoughts @realm/java ?

**Comment by kneth** [comment]
It's not a bad idea. We should extend `initialData()` with a method which takes a file name as argument. It can then copy a Realm from the assets to the file name set by the `Builder()`.
