### ISSUE TITLE
Naming restriction of attributes in RealmObjects

### ISSUE THREAD

**Issue by wickermoon** [realm/realm-java#2255]
Goal: create a RealmObject class with an attribute named "realm".
Expected results: No compilation errors
Actual results: "Error: realm has private accessor" compiler error, due to internal realm.io variable also called "realm", thus the whole proxy class is getting confused as to which realm to use for the proxy functions.
Steps to reproduce: Create a class extending RealmObject, add an attribute named realm, compile

Realm Version: 0.87.0

Well, the problem is pretty obvious. The proxy class is extending the actual class, tries to override the attribute named realm, because apparently you use a variable called "realm" for the proxy implementation. The proxy class then finds that this variable has a private accessor and throws an exception. Either disallow attributes with the name "realm" (bad idea) or rename the internal attribute to "proxyRealm" or something like that.

**Comment by emanuelez** [comment]
Well spotted! I think we should rename the realm field in `RealmObject`

**Comment by cmelchior** [comment]
The problem with renaming it is that you can never remove the risk of a name conflict, but it should be relatively easy to rename it to something with less chance of a conflict. `$realm` , `obj$realm` perhaps as that is usually reserved for generated code.

**Comment by wickermoon** [comment]
You could also explicitly state the class like "((RealmObject)this).realm" to make perfectly clear that you're using the attribute defined in RealmObject. Of course, this is an arduous way of calling the RealmObject.realm attribute, but it is conflict-safe, as attribute names of RealmObject children won't matter.

**Comment by zaki50** [comment]
@wickermoon thank you for your suggestion. Perhaps we'll fix this after merging `feature/better-objects` branch since that branch contains many changes to proxy classes.

**Comment by zaki50** [comment]
@wickermoon made a fix (a63c9e1)

I will create a PR after #2196 merged.

**Comment by zaki50** [comment]
@wickermoon this issue has been fixed in the `master` branch. It's available in SNAPSHOT release and of cource will be available in next `0.88`.

Thanks.
