### ISSUE TITLE
Realm is closed unexpectedly

### ISSUE THREAD

**Issue by AOrobator** [realm/realm-java#2261]
In the docs it says to open the realm in `onStart()` for fragments, and then `onStop()` to close it. I'm doing this and using a `RealmResults<T>` to back an adapter. The `getCount()` method just returns the size of the `RealmResults<T>`. The issue is as follows: After leaving and coming back to the fragment several times, usually it takes 2 leaves, I get a crash saying the `This Realm instance has already been closed, making it unusable.` Any thoughts?

I've "fixed" the issue by just checking to see if the realm is closed and instantiating a new one via `Realm.getDefaultInstance()` and exposing a `closeRealm()` method on the adapter so the realm doesn't leak in `onStop()` . Although this solution works, it's far from ideal.

The `RealmResults<T>` are initialized right after I initialize the realm in `onStart()`.

I have no reason to believe `getItemCount()` would run after `onStop()` as this is when the `Fragment` is no longer visible to the user, so it has no need to run. However, I'm ready to be proven wrong, as I haven't done much digging into this.

I removed the adapter in `onStop()` by `recyclerView.setAdapter(null);` but this doesn't seem to work either. A full conversation discussing this bug is [here](https://www.reddit.com/r/androiddev/comments/44c9ec/fragmented_podcast_27_realm_realm_realm_your_boat/czqdloc).

I'm testing on a Nexus 6P running Marshmallow 6.0.1, but [/u/Zhuinden also reports seeing issues on L devices](https://www.reddit.com/r/androiddev/comments/44c9ec/fragmented_podcast_27_realm_realm_realm_your_boat/czqv8dl).

#### GenreRecyclerAdapter.java
```
public class GenreRecyclerAdapter extends RecyclerView.Adapter<GenreRecyclerAdapter.ViewHolder> {

    private final RealmResults<Genre> genres;

    public GenreRecyclerAdapter(RealmResults<Genre> genres) {
        this.genres = genres;
    }

    @Override
    public ViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        LayoutInflater inflater = LayoutInflater.from(parent.getContext());
        View itemView = inflater.inflate(R.layout.list_item_genre, parent, false);
        return new ViewHolder(itemView);
    }

    @Override
    public void onBindViewHolder(ViewHolder holder, int position) {
        holder.bind(position);
    }

    @Override
    public int getItemCount() {
        return genres.size(); // Realm is closed here
    }

    class ViewHolder extends RecyclerView.ViewHolder {
        TextView genreTextView;
        TextView genreIconTextView;
        ImageButton addToQueueImageButton;

        public ViewHolder(View itemView) {
            super(itemView);

            genreTextView = (TextView) itemView.findViewById(R.id.genre_TextView);
            genreIconTextView = (TextView) itemView.findViewById(R.id.genre_icon_TextView);
            addToQueueImageButton = (ImageButton) itemView.findViewById(R.id.add_to_queue_ImageButton);
        }

        public void bind(int position) {
            // View setup
        }
    }
}
```

#### GenresFragment.java

```
public class GenresFragment extends MusicCollectionFragment {
    public static final String TAG = "GenresFragment";
    public static final String KEY_FOR_GENRE = "com.orobator.auracle.genreKey";
    private SimpleFastScrollRecyclerView genreRecyclerView;
    private Realm realm;

    @Override
    public void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setRetainInstance(true);
    }

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup parent, Bundle savedInstanceState) {
        View view = inflater.inflate(R.layout.list_view_genres, parent, false);

        genreRecyclerView = (SimpleFastScrollRecyclerView) view.findViewById(R.id.genres_RecyclerView);
        genreRecyclerView.setLayoutManager(new LinearLayoutManager(getActivity()));
        genreRecyclerView.addItemDecoration(new DividerItemDecoration(getActivity()));
        genreRecyclerView.addOnScrollListener(new FabMiniplayerRecyclerScrollListener());

        return view;
    }

    @Override
    public void onStart() {
        super.onStart();

        if (realm.isClosed()) {
             realm = Realm.getDefaultInstance();
        }
 
        RealmResults<Genre> genres = Database.getAllGenres(realm);
        if (genres.isEmpty()) {
            showEmptyView(); // Defined in parent class
            return;
        }

        genreRecyclerView.setAdapter(new GenreRecyclerAdapter(genres));
    }

   @Override
    public void onStop() {
        super.onStop();
        realm.close();
    }

}

```

**Comment by cmelchior** [comment]
Hmm, strange because the code looks alright. So you are saying you tried:

```
   @Override
    public void onStop() {
        super.onStop();
        recyclerView.setAdapter(null);
        realm.close();
    }
```

Life cycle things are notoriously difficult to debug. Is it possible for you to create a small sample project that showcase this error?

**Comment by AOrobator** [comment]
Yes, that's what I did and it didn't work. I'll see if I can whip up a sample project.

**Comment by xbroak** [comment]
Is this related to my issue also? Sudden "closure" of realm seems to be happening very frequently lately... https://github.com/realm/realm-java/issues/2246

**Comment by cmelchior** [comment]
Hi @xbroak, No this issue is about Fragment lifecycles while yours was about Activity lifecycles.

The easiest way to debug something like this is to add `Log` statements into the lifecycle methods. That way it is a lot easier to reason about what is happing from the log output.

**Comment by Zhuinden** [comment]
The realm objects become invalidated by `getItemCount()` method.

My current workaround is to check the validity of the RealmObjects in `getItemCount()`.

    public static <T extends RealmObject> boolean isValid(RealmResults<T> realmResults) {
        if(realmResults == null) {
            return false;
        }
        try {
            realmResults.isEmpty();
            return true;
        } catch(IllegalStateException e) {
            return false;
        }
    }

But it's far from ideal. This started happening only on L and above, so it must be an ART thing.

**Comment by cmelchior** [comment]
Hi @AOrobator 
Any luck with the sample project?

**Comment by beeender** [comment]
Close due to no response.
