### ISSUE TITLE
How to search to-many tables in one filter.

### ISSUE THREAD

**Issue by mrsaif** [realm/realm-java#2262]
Ok I am new to realm. In realm I think full-text search is not supported. I wan to search text in 2 tables. I have following tables. 
Member(firstName, lastName, location, contacts:List<Contact>)
Contact(type, name, value)
I am using following query to search members. 

realmObj.objects(Member).filter("firstName BEGINWITH[c] '\(txtSearch.text!)' OR lastName BEGINWITH[c] '\(txtSearch.text!)' OR location BEGINWITH[c] '\(txtSearch.text!)'")

above query is working and returning results. I also want to search the same text in Contact  table in and get all the members where name, and value begins with the search text.  one way is to have member object in contact table and perform separate filter to get matching members.. and also I have to combine both results so that member records do not repeat. 

Is there a way to perform search in one filter/query? I need to do it because my member and contact data might grow to 10000 records.

**Comment by cmelchior** [comment]
That looks like Realm Swift? This repository is for Realm Android. So it would be better if you created the issue here instead: https://github.com/realm/realm-cocoa

**Comment by mrsaif** [comment]
thanks
