### ISSUE TITLE
Adding RealmNotificationListener on RealmObjects from a RealmResult using get() Method

### ISSUE THREAD

**Issue by joseffilzmaier** [realm/realm-java#2264]
Hello there!

My Goal is to implement a RecyclerView using Realm. I would like to update the View's in the RecyclerView granularly. So i'm holding a RealmResults<RealmObject> realmResults in my RecyclerView.Adapter. I'm putting RealmObjects in my ViewHolder using realmObjects.get(position), and then adding a RealmNotificationListener to those RealmObjects. 

So far this is working nicely. However, there is a Problem: If i change the data of **one** of my RealmObjects, the RealmNotificationListener::onChange() method gets called on **all** RealmObjects of this RealmResults.

I would have expected it to only fire the listener on the RealmObject for which i changed the underlying data.

Is this the expected behaviour? If yes, do i have to open a new RealmQuery for each Object to get a granular onChange?

**Sample Code: Adapter**
```
public class MyAdapter extends extends RecyclerView.Adapter<RecyclerView.ViewHolder>{

private  RealmResults<RealmObject> realmresults;
...
    @Override
    public void onBindViewHolder(final MyViewHolder holder, final int i) {
        super.onBindViewHolder(holder, i);
        holder.setMovementTrackingDevice(realmResults.get(i));
        }
    }
...
}
```

**Sample Code: ViewHolder:**
```
public class MyViewHolder extends RecyclerView.ViewHolder {

    private RealmObject object;
    private RecyclerView.Adapter adapter;
    private RealmChangeListener movementChangeListener = new RealmChangeListener() {
        @Override
        public void onChange() {
            adapter.notifyItemChanged(getAdapterPosition());
        }
    };

    public ShutterViewHolder(BaseInteractionView view, RecyclerView.Adapter adapter) {
        super(view);
        this.adapter = adapter;
    }

    public void setMovementTrackingDevice(RealmObject object){
        if (this.object != null)
            this.object.removeChangeListener(movementChangeListener);
        this.object = object;
        this.object.addChangeListener(movementChangeListener);
    }

}
```

Using 
Android Studio 1.5.1
Realm Java 0.87.4
Android 5.1

Thanks in advance.

**Comment by nhachicha** [comment]
Hi @joseffilzmaier 
I think what you're looking for is fine grained notification https://github.com/realm/realm-java/issues/989

For now we have a heuristic that does a best effort to reduce the number of notifications by using a meta attribute `version` associated with the _table_ that stores your data. So if another operation update the table holding your RealmObjects, we need to notify the listeners, since the aforementioned operation might influence the result for the `RealmObjects` using the same _table_

Cheers,

**Comment by joseffilzmaier** [comment]
Hi @nhachicha 
This is exactly what i need. I guess i didn't scroll down far enough in the issue pool to see this ticket though :) I already have a workaround in place but would love to switch to such a solution. Maybe you could add a hint about this in the documentation.

Thanks for your fast response!

**Comment by cuihujun** [comment]
@joseffilzmaier, hello, is it possible to share how you did the workaround?

**Comment by Zhuinden** [comment]
@cuihujun `OrderedRealmCollectionChangeSet` was added in Realm 3.0.0 and is reliable since 3.1.0.

Objects also can be observed for field changes using `RealmObjectChangeListener`.
