### ISSUE TITLE
Realm access in non-Activity class

### ISSUE THREAD

**Issue by luzianscherrer** [realm/realm-java#2267]
I understand that Realm objects can only be accessed on the thread they were created. But what I don't understand is this: let's say I have a network class that handles all communication and runs in a separate thread. Now I need to access Realm objects on the UI thread as well as in this network classes thread. But since the network class is not an Activity, there is no Context. How can I get a Realm instance in the network class without having a Context?

One solution I guess might be to pass the Context to the network class, but I would not like to run its Realm operations on the UI thread.

I think this question could be turned around in a more general way: Can Realm be used at all outside of Android, I mean in plain Java where there is no Context?

Is there a solution for that or am I missing something?

**Comment by cmelchior** [comment]
You don't need the Context as such. We only use it to get a reference to the `getFilesDir` which is done automatically in our RealmConfiguration.

You can just create the a default configuration in your Application subclass and then call `Realm.getDefaultInstance()` from any thread you want.

You can see an example of it here: https://realm.io/docs/java/latest/#controlling-the-lifecycle-of-realm-instances

**Comment by luzianscherrer** [comment]
Ah, got it! Took me some refactoring because I just have one storage singleton which encapsulates all the Realm stuff for me using setters and getters. That singleton kept one single Realm object. I'm now passing in the Realm object to be used in as an addition argument to each method. Works fine.

Thank you very much!

**Comment by cmelchior** [comment]
No problem. Good luck with your project :)
