### ISSUE TITLE
Multiple call to RealmMigration's migrate

### ISSUE THREAD

**Issue by rshah** [realm/realm-java#2268]
I have problem with migration, it always complaining about multiple value in primary key.
I tried adding some logcat when migrating. It turned out that migrate() function is called many times.
Some are from same thread, some are from different thread.
Any way to avoid this problem?
Should i just try and catch the migration block?

Thank you.

**Comment by cmelchior** [comment]
Hi @rshah 
A RealmMigration is a blocking operation across all threads, so it shouldn't be called more than once. Is it something you can reproduce in some code you can show?

**Comment by rshah** [comment]
Thank you, i'm sorry, it's not possible to show the code as is.
I will try to create small project. Hopefully i can reproduce it easily.

**Comment by rshah** [comment]
I have looked again the debug output.
Seems my data has problem, i will close this. Sorry for the noise.
