### ISSUE TITLE
Query to a nested object without including nested elements

### ISSUE THREAD

**Issue by lectricas** [realm/realm-java#2269]
Hi. 
Suppose we have many-to-many relationship.
class Foo extends RealmObject{
    private String aaa;
    //getters...
}

class Bar extends RealmObject{
    private String bbb;
    private RealmList<Foo> foos;
    //getters...
}

I want to query all bars without foos included

**Comment by cmelchior** [comment]
Not sure I understand your problem. Can you try to show an example of what you want to accomplish?

**Comment by lectricas** [comment]
Ok. Assume we have a realm with decent amount of Foo and Bars in it.
If we query like like that: 
Bar bar = realm.where(Bar.class).equalTo('some_value", true).findFirst();
bar.getFoos(); // not null, right?;
But I want bar.getFoos(); to be null 
so no nested objects would be queried. 
I'm trying to implement a system where you don't need all the objects in some Activities because sometimes bar.getFoos().size() would be equal 10000 and I'm worried that this would cause lags in my app.

**Comment by cmelchior** [comment]
Realm lazy-load all its data, so you can safely query your Bar class without worrying about loading all the Foos. They will only be loaded if you actually access them.

```
Bar bar = realm.where(Bar.class).equalTo('some_value", true).findFirst();
bar.getFoos(); // We only load foos if you call the getter.
```

**Comment by lectricas** [comment]
Thanks - it's awesome.

**Comment by lectricas** [comment]
Also can I get rid of notifyDatachanged adapter method when implementing RealmAdapter?
I want to refresh my ListView as soon as data was changed.
What is the simplest way to do that with Realm?

**Comment by lectricas** [comment]
opened another issue
