### ISSUE TITLE
refresh listView when implementing adapter

### ISSUE THREAD

**Issue by lectricas** [realm/realm-java#2270]
Can I get rid of notifyDatachanged adapter method when implementing RealmAdapter?
I want to refresh my ListView as soon as data was changed.
What is the simplest way to do that with Realm?

**Comment by cmelchior** [comment]
If you use the RealmBaseAdapter it will automatically refresh if change the data that is being shown. Right now it is a bit coarse grained so it might trigger a `notifyDataChanged` for more than what is being shown, but we are working on full fine-grained support : #989

**Comment by lectricas** [comment]
thanks
