### ISSUE TITLE
Write child object without calling parent

### ISSUE THREAD

**Issue by lectricas** [realm/realm-java#2271]
Hi again. Sorry for so many q, there is no docs about some features.

I want to update my foos.
```java
class Bar extends RealmObject{
    RealmList<Foo> foos;
    //getters
}
```

And I can do it like that:

```java
Bar bar = realm.where(Bar.class).findFirst();
List<Foo> foos;
Override
onStatusChanged(Foo foo){
    realm.beginTransaction()
    foos = bar.getFoos();
    foos.add(bar);
    bar.addFoos(foos);
    realm.copyToRealmOrUpdate(bar);
    realm.commitTransaction();
}
```

Is there an easy way to do that?
Btw, how to make this issue T:help?

**Comment by emanuelez** [comment]
It's a bit hard to figure out what you are trying to achieve with the code above. Can you describe it a bit more?

Also, are you handling backlinks manually? (Foo to Bar and Bar to Foo)

Anyway, the call `copyToRealmOrUpgrade()` seem unnecessary since `bar` come from Realm already.

**Comment by lectricas** [comment]
Hi. I'm trying to make a (db)realm record(write) of an Foo item of RealmList, while this RealmList is a field of Bar object

**Comment by cmelchior** [comment]
Hi @lectricas 

If you want to create a new `Foo` object and add it to your `foos`, the easiest way is this:

```
List<Foo> newFoos = getFoos();
Bar bar = realm.where(Bar.class).findFirst();
realm.beginTransaction();
bar.getFoos().clear();
bar.getFoos().addAll(newFoos); // This will automatically copyToRealm your new objects.
realm.commitTransaction();
```

**Comment by lectricas** [comment]
Hi. Did you miss the line with adding new Foo object?
I didn't get your code, can you explain it a little bit more?
I have a bar, right:
Bar bar = realm.where(Bar.class).findFirst();
and I have a foo:
Foo foo = new Foo("someString");
I want to make that kind of record in DB:
bar.getFoos().add(foo),
in other words, add new foo to existing one.

**Comment by cmelchior** [comment]
I misunderstood your original explanation then. In that case you can just do:

```
Bar bar = realm.where(Bar.class).findFirst();
realm.beginTransaction();
bar.getFoos().add(new Foo("someString")); // This will automatically copyToRealm your new object.
realm.commitTransaction();
```

**Comment by lectricas** [comment]
Thanks. Realm makes the things pretty simple. However, I'm a little bit confused by writing and querying lifecycle. In other words when transactions are occure and what if I haven't invoked commitTranaction();
Is there any place where I can study this info?

**Comment by cmelchior** [comment]
You can take a look in our examples: https://github.com/realm/realm-java/tree/master/examples
A good place to start is our IntroExample: https://github.com/realm/realm-java/tree/master/examples/introExample

**Comment by cmelchior** [comment]
Hi @lectricas I assume the above answered your question. Feel free to reopen if that is not the case.

**Comment by lectricas** [comment]
ok. What if bar.getFoos()=null because it was initiated at the first time?

**Comment by lectricas** [comment]
ah, I got it. dumb me.
