### ISSUE TITLE
Make Asynchronous Writes compatible with RxJava via Completable or Single

### ISSUE THREAD

**Issue by grahamsmith** [realm/realm-java#2272]
### Background 

The first class support for RxJava in Realm is great, however that said I couldn't find a way to make writes work with the current API. As a result using callbacks rather than reactive seemed to be the sensible choice with the current setup.

### Proposal

The `Completion` or `Single` APIs of RxJava map well to the `Callback` object created as part of the asynchronous write transaction. Could the callback be abstracted or replace with one of the aforementioned types of `Observable`?

The Single API defines the same methods as the Callback. This is documented here http://reactivex.io/documentation/single.html

The process would only emit one item therefore the use of Single seems like a logical fit.

**Comment by cmelchior** [comment]
Yes, we fully agree and are already tracking it here: https://github.com/realm/realm-java/issues/2126

I am not entirely sure that we want to support `Completable` right away though as it require everyone to upgrade to the latest version of RxJava which might be problematic, but exposing it as an Observable is definitely something we want to do and then for people that uses 1.1.1 they can use `Observable.toCompletable()`   https://github.com/ReactiveX/RxJava/releases/tag/v1.1.1.

I'll copy your writeup to #2126 and close this as an duplicate
