### ISSUE TITLE
Removing duplicate data in transform() during migration

### ISSUE THREAD

**Issue by rshah** [realm/realm-java#2275]
I need to remove duplicate data before adding primary key.
Right now, i'm using hashmap to check if certain data exist or not and add temporary duplicateFlag field to mark if the row is duplicate or not.
Then query against this field then remove all.

RealmObjectSchema.transform might be good idea to do the clean up operation.
Is it possible to remove DynamicRealmObject passed inside apply() function?

Thank you.

**Comment by cmelchior** [comment]
Hi @rshah 

the `transform` method currently doesn't support removing objects, but you can do it outside that method as well.

The `DynamicRealm` gives you access to all normal query methods, so you can just do something like this instead:

```
RealmMigration migration = new RealmMigration() {
  @Override
  public void migrate(DynamicRealm realm, long oldVersion, long newVersion) {
    realm.where("Foo").equalTo("duplicatedFlag", true).findAll().clear();
  }
}
```

**Comment by rshah** [comment]
Your solution is nice.
Thank you for the feedback.
