### ISSUE TITLE
realm.createOrUpdateObjectFromJson duplicate primary key - fatal error

### ISSUE THREAD

**Issue by miguelmartin75** [realm/realm-java#2276]
Here's a stack trace:

```
 FATAL EXCEPTION: EventThread
Process: myapp, PID: 32290
io.realm.exceptions.RealmPrimaryKeyConstraintException: Value already exists: 
    at io.realm.internal.Table.throwDuplicatePrimaryKeyException(Table.java:636)
    at io.realm.internal.Table.addEmptyRow(Table.java:360)
    at io.realm.Realm.createObject(Realm.java:661)
    at io.realm.OrderRealmProxy.createOrUpdateUsingJsonObject(OrderRealmProxy.java:741)
    at io.realm.DefaultRealmModuleMediator.createOrUpdateUsingJsonObject(DefaultRealmModuleMediator.java:210)
    at io.realm.Realm.createOrUpdateObjectFromJson(Realm.java:506)
    at myapp.model.Order.updateOrder(Order.java:50)
    at myapp.instances.Server$7.call(Server.java:195)
    at io.socket.emitter.Emitter.emit(Emitter.java:117)
    at io.socket.client.Socket.onevent(Socket.java:317)
    at io.socket.client.Socket.onpacket(Socket.java:280)
    at io.socket.client.Socket.access$100(Socket.java:18)
at io.socket.client.Socket$2$2.call(Socket.java:101)
```

Here is my situation:
1. I have an object that I have received from my server previously and I store it in Realm.
2. Once the object is 'updated' outside of my application, I receive an event from my server that it has.
3. The code for handling this 'object updated' event is essentially: 

```java
Realm realm = Realm.getDefaultInstance();
try {
    realm.beginTransaction();
    realm.createOrUpdateObjectFromJson(Order.class, json);
    realm.commitTransaction();
} finally {
    realm.close();
}
```

Note: this is called on a separate network thread handled by Socket I/O. Am I doing something wrong, or is this a bug?

**Comment by cmelchior** [comment]
It is a bug. This `io.realm.internal.Table.addEmptyRow(Table.java:360)` creates an empty Object with all default values, but if you already have an object with that value it will throw the error. The `createOrUpdateObjectFromJson` method should have detected that.

**Comment by miguelmartin75** [comment]
>Note that having objects with default primary keys like 0 or "", can cause problems in other API methods as well like Realm.createObject, so avoiding that would be a good idea.

I have my Primary Key set to nothing by default (null).

Is there any known work-arounds for this? Having this implemented is a fundamental feature of the application I'm working on.

**Comment by cmelchior** [comment]
using `copyToRealmOrUpdate` should not have this bug. It require you to convert your JSON to an Java object first though, but since your json matches your model classes it should be straight forward. You can see how there: https://realm.io/docs/java/latest/#gson

**Comment by ivanove** [comment]
Hi,
This is what I did but I test it only in the version 0.80, I don't know for other versions.

`public class ApplicationBean extends RealmObject {


    @PrimaryKey
    private int id;

    private Application application;

    public int getId() {
        return id;
    }


    public void setId(int id) {
        this.id = id;
    }
    public Application getApplication() {
        return application;
    }
    public void setApplication(Application application) {

     id = Increment.Primary_AppBean(application);
        this.application = application;
    }

    public ApplicationBean() {
    }


    public ApplicationBean(Application application) {
        this.application = application;
    }
}
`

The static function to Increment ID :

`
int AppBean = 0;
 public static int Primary_AppBean(Application application){
        if(application !=null) {
            id_AppBean++;
        }
        return id_AppBean;
    }`

**Comment by stk1m1** [comment]
@ivanove Thank you very much for your feedback. We will look into it and come back to you soon.

**Comment by stk1m1** [comment]
@miguelmartin75 Could you provide us your object class? We're trying to reproduce the crash and it could really helpful to have an insight. Bare object code like [this](https://github.com/realm/realm-java/issues/2324#issuecomment-188131946) should suffice.

**Comment by miguelmartin75** [comment]
I actually think this was my mistake. I'm fairly sure the mistake was the fact that I was passing the method a JSON object that was not related to the object (the JSON object contained the actual object tagged as "order", i.e. `{ "order": { /* json I wanted to convert */  } }`. 

So I think what the problem was: the fact that I was giving it the wrong json object, so it default constructed my Order object with the default primary key (`null`).

Seems to work fine now though.
