### ISSUE TITLE
Delete Relationship Objects

### ISSUE THREAD

**Issue by AlokBansal8** [realm/realm-java#2277]
I have a RealmObject `Conversation` which have other RealmObject `Message` as RealmList. I want to delete all `Message` in that `Conversation` without deleting `Conversation` and I want that when my `Conversation` is deleted all `Message` in the list are also deleted.

**Comment by beeender** [comment]
For "delete all Message in that Conversation without deleting Conversation" 

You can use [`RealmList.removeAllFromRealm`](https://github.com/realm/realm-java/blob/master/realm/realm-library/src/main/java/io/realm/RealmList.java#L313). **Please note that this method is not released yet. But you can use snapshot version to get it before release.**

For "hen my Conversation is deleted all Message in the list are also deleted."
This is not supported yet, see the #1339 for more details.

**Comment by AlokBansal8** [comment]
@beeender thanks. I see that latter of my request is being handled in #1104 
I will be waiting for a proper release to use RealmList.removeAllFromRealm. Hope that it will be included in the next release.
