### ISSUE TITLE
How can i update a child?

### ISSUE THREAD

**Issue by AalenChan** [realm/realm-java#2281]
```
class Parent extends RealmObject {
      RealmList<Child> child;
}
```

how can i update one of these child upon child's some param?

**Comment by beeender** [comment]
Just query for the child you want to update then simply change it inside the transaction.

```
realm.beginTransaction();
Child child = child.where().equalTo("name", "the name").findFirst();
child.setName("abc");
realm.commitTransaction();
```

See doc https://realm.io/docs/java/latest/#queries https://realm.io/docs/java/latest/#writes
