### ISSUE TITLE
Terminal distinct() invalidates all previous distinct(), resulting in unexpected values.

### ISSUE THREAD

**Issue by stk1m1** [realm/realm-java#2282]
When more than one `distinct()` are called in query chain, e.g. `distinct().equalTo().distinct()`, the last `distinct()` will discard all the effects of previous `distinct()` as it is designed.

This behavior results in unexpected values in terms of the final objects set.

**Comment by beeender** [comment]
`distinct` will always create a new `RealmResults` and won't change the original one since `v3.0.0`.
