### ISSUE TITLE
Realm Main thread vs background thread

### ISSUE THREAD

**Issue by Sutirth** [realm/realm-java#2286]
Are there are any major pitfalls using realm in main thread for operations rather than using background thread?

**Comment by cmelchior** [comment]
The only major pitfall is that writes are blocking across all threads. So if you have _any_ background thread doing writes, you might accidentally risk block the UI thread for an extended period of time.

**Comment by Sutirth** [comment]
So say I am doing something in a service and updating UI simultaneously  it might block the UI right?? .

**Comment by zaki50** [comment]
Writes does not block any reads. Writes only blocks writes in all other threads.

That means writing on UI thread can be blocked by writes on other background thread.

**Comment by cmelchior** [comment]
@Sutirth Yes, if you do writes in both a Service thread and on the UI, they might block each other.

**Comment by yshrsmz** [comment]
So we need to manually make sure that only a single write is going on at the same time across the all threads?

**Comment by beeender** [comment]
@yshrsmz No, you don't have to do that. Writing in thread A will block writing in thread B automatically. Just use async transactions in **UI thread** when it is possible, async transaction won't be blocked in the caller thread.

**Comment by yshrsmz** [comment]
Ah, got it.
Sorry for the stupid question, just realized what "blocking" means ;)
thanks!

**Comment by Sutirth** [comment]
Thanks a bunch guys clears all the confusion :)

**Comment by lightai** [comment]
what is the
