### ISSUE TITLE
why is realm.classToTable count  0 when I get instance of realm object in Android

### ISSUE THREAD

**Issue by sDurgam** [realm/realm-java#2287]
I have created my own realm db and I set configuration to  new RealmConfiguration.Builder(this).name("mydb.realm").build();
realm = Realm.getInstance(realmConfiguration);

The classToTable count is 0 and count of rows in the table is also 0. Can someone let me know what am I missing. Thanks.

**Comment by cmelchior** [comment]
Realm automatically detects any classes you have that extend `RealmObject`. They are the "schema" for the Realm file. If you don't have any such classes, the `classToTable` map is empty.

Note you can also use `Realm.getSchema()` which provide a more safe API for investing how the schema for a Realm file is. E.g. `realm.getSchema().getAll()` should return a list of all known model classes.

**Comment by sDurgam** [comment]
realm.getSchema().getAll() is listing 9 objects. realm.getSchema().getSchemaForClass(MyClass.class) is also showing column indices. But realm.getSchema().getAll() is giving 'unable to evaluate the expression Method threw 'java.lang.UnsupportedOperationException' exception. Also findAll() query on my table is giving no results.

**Comment by cmelchior** [comment]
@sDurgam Can you create a small sample project that showcase this behaviour? That will make debugging a lot easier.

**Comment by sDurgam** [comment]
@cmelchior Thank you. I am working to just two realm objects instead of 9. Though classtoTable is still 0 the count of rows from findAll on these classes is not zero.

**Comment by cmelchior** [comment]
@sDurgam I am not entirely sure what you mean by that. If you could create a sample project it would make it a lot easier to look into.

**Comment by sDurgam** [comment]
@cmelchior I am right now defined just two tables (classes that extend RealmObject) instead of 9. I also removed deleleconfiguration from my application code. Though classToTable count is still zero I am able to fetch data from these tables.

**Comment by cmelchior** [comment]
OK. Just a note that `classToTable` is really an internal data structure and not one you should depend on in order to tell what is going on. Using the RealmSchema is much safer and more accurate.

**Comment by sDurgam** [comment]
@cmelchior Thank you. Will keep that in mind.

**Comment by cmelchior** [comment]
It sounds like you found a solution, so I am closing this issue. Feel free to reopen if that is not the case.
