### ISSUE TITLE
asObservable() don't call onCompleted() callback

### ISSUE THREAD

**Issue by w9xhc** [realm/realm-java#2289]
```java
userRealmQuery.findAllAsync().asObservable()
.filter(users.isLoaded)
.flatMap(users -> Observable.from(users))
.subscribe(new Subscriber<User>() {
                    @Override
                    public void onCompleted() {
                      
                    }

                    @Override
                    public void onError(Throwable e) {

                    }

                    @Override
                    public void onNext(User user) {
                    }
                });
```
    
like this.  `onCompleted()` is not called  when query finish.

**Comment by cmelchior** [comment]
Realm Observables never complete as they emit every time your data changes. We have recently update the Javadoc to be clear about that. There is also hints to how you can get `onCompleted` events: https://github.com/realm/realm-java/blob/master/realm/realm-library/src/main/java/io/realm/RealmResults.java#L902-Lundefined

**Comment by IHNEL** [comment]
@cmelchior 
I face the same case. onCompleted never get called, and when I insert new data item in another thread, it wasn't emit into subscriber as you said.

**Comment by Zhuinden** [comment]
`onCompleted` is never called because a RealmChangeListener never completes, it always listens until you unsubscribe. You receive it in `onNext`.
