### ISSUE TITLE
Realm does not generate model proxy class

### ISSUE THREAD

**Issue by muraterd** [realm/realm-java#2290]
I have model class:

public class WEpisode extends RealmObject {

private WImages images;

public WImages getImages() {
        return images;
    }

    public void setImages(WImages images) {
        this.images = images;
    }
}

But build failed,
Error:(64, 20) error: Getter getImages is not associated to any field
Note: Creating DefaultRealmModule
Warning:File for type 'io.realm.DefaultRealmModule' created in the last round will not be subject to annotation processing.
Warning:File for type 'io.realm.DefaultRealmModuleMediator' created in the last round will not be subject to annotation processing.

I'm using Windows 10, Android Studio 2.0 Beta 4 and Realm 0.87.4

Also when i try to build the same code in OSX it just successfully bulds.

**Comment by beeender** [comment]
`WImages` is not a supported type by Realm. But you can use `@Ignore` annotation to let Realm annotation processor ignore it.
Like this:

```java
public class WEpisode extends RealmObject {
@Ignore
    private WImages images;

    public WImages getImages() {
        return images;
    }

    public void setImages(WImages images) {
        this.images = images;
    }
}
```

**Comment by muraterd** [comment]
I tried the @Ignore annotation but keep getting the same error. I'm soorry but i still didn't understand how the same code works in OSX and doesn't work on windows. By the way i'm using windows in Turkish language. Can the problem be related to it?

**Comment by beeender** [comment]
What version of AS on OSX are you using? Can you please try with disable the AS2.0 's Instant Run and try again?

**Comment by muraterd** [comment]
The problem was in my language settings. I changed the language to en-US and the problem is gone. Anyway thank you for your support. And I'm using the same version on OSX. AS 2.0 Beta 4
