### ISSUE TITLE
Android instant run problem

### ISSUE THREAD

**Issue by rimidalv** [realm/realm-java#2293]
The app crashes after reinstall with instant run. 

 java.lang.IllegalAccessError: Illegal class access ('io.realm.RealmOrdersRealmProxy' attempting to access 'io.realm.BaseRealm') in attempt to invoke virtual method void io.realm.BaseRealm.checkIfValid() (declaration of 'io.realm.RealmOrdersRealmProxy' appears in /data/data/ru.avangard.selo/files/instant-run/dex/slice-slice_6_0aa5d3d0f8ecaffbc1b1e59784e31a3963000341-classes.dex)
                                                                    at io.realm.RealmOrdersRealmProxy.getId(RealmOrdersRealmProxy.java:70)
                                                                    at ru.avangard.selo.ui.MainActivity.checkOrders(MainActivity.java:194)

**Comment by cmelchior** [comment]
Hi @rimidalv 

Instant Run is still in beta and still have issues with libraries such as Realm. You can read more here https://github.com/realm/realm-java/issues/2139 + a there is a link to the Google bug tracker with an open issue about this.

**Comment by rimidalv** [comment]
Thank you!
