### ISSUE TITLE
Updating realm version to new migration API

### ISSUE THREAD

**Issue by chadwilken** [realm/realm-java#2297]
We are in the process of updating realm from 0.82.0 to 0.87.4 and are having migration issues. We have been unable to find any documentation about how to convert old migration files to the new format or if it is even necessary. We keep getting errors about primary keys, indexes and the like. Any guidance on how to update would be appreciated.

**Comment by cmelchior** [comment]
Hi @chadwilken 

We don't have any guide as such, but the below file was upgraded to the new API which should give some ideas:

New:
https://github.com/realm/realm-java/blob/master/examples/migrationExample/src/main/java/io/realm/examples/realmmigrationexample/model/Migration.java

Old version:
https://github.com/realm/realm-java/blob/e28faeaea18aecffe9f8ecd7fed9c2849f7c69c1/examples/migrationExample/src/main/java/io/realm/examples/realmmigrationexample/model/Migration.java

Note that we introduced Null support in 0.83 which also require some changes: https://realm.io/news/realm-java-0.83.0/ (the new api method is called `setNullable()` 

If you run into specific problems, you can also post your migration code + model class so we can give you some pointers.

**Comment by chadwilken** [comment]
@cmelchior Well what is confusing is that you move from `Table`'s to `Schema`'s but don't really specify how to move all the old migration code that is using tables over to using the schema. We got a pretty good idea of what to do but when we do it we get errors that are vague and don't help with any sort of guidance. Our main error is about needing to add `@Index or call removeSearchIndex`.

**Comment by cmelchior** [comment]
Yes, sorry about that. 

Primary keys was changed to all be automatically indexed in 0.82. This was only true for Strings before 0.82 and is described here https://realm.io/news/realm-java-0.82.0/. The new method is called `addIndex(field)`.

**Comment by beeender** [comment]
@chadwilken I hope your problem is solved. I am closing this issue now, feel free to reopen it if necessary. Thanks!
