### ISSUE TITLE
Can't query child child objects during their write in another thread.

### ISSUE THREAD

**Issue by lectricas** [realm/realm-java#2301]
Hi. Suppose I have a service:

public MyService extends Service {

    @Override
    public void onCreate {
        realm = Realm.getDefaultInstance();
        currentTrack = new Track(new RealmList<>()); // empty list, right?
        realm.beginTransaction();
        realm.copyToRealmOrUpdate(currentTrack);
        realm.commitTransaction();
        currentTrack =  realm.where(Track.class).findFirst();
    }

    @Override
    public void onLocationChanged(Location l) {  //  THIS IS THE "A" place, executes every 5 seconds 
        Point p = new Point("someString");
        realm.beginTransaction();
        currentTrack.getPoints().add(p);
        realm.commitTransaction();
    }    
}

it constantly make records inside Realm.
And I have an Activity which queries from realm:

public Activity extends Activity{

    @Override
    public void onCreate {
        realm = Realm.getDefaultInstance();
    }
    @Override
    public void onResume {
        currentTrack =  realm.where(Track.class).findFirst(); // not null, everything is fine, but -->>
        currentTrack.getPoints().size(); // ALWAYS gives 0 if the "A" place is in execution,
    }

}

So, when service is working and I'm constantly making database writings, I can't query them. As soon as recording is completed, I can query them easily. 
How to fix that?

**Comment by beeender** [comment]
` currentTrack.getPoints().size();` always return 0 or only return 0 when onLocationChanged is running? means during the 5s interval, does it return the right value?

If you don't make any mistake, it sounds like we have a bug... Let me try if i can reproduce it.

**Comment by beeender** [comment]
@lectricas I think it is not Realm's problem.
```
    @Test
    @RunTestInLooperThread
    public void list_add_in_other_thread() {
        looperThread.realm.beginTransaction();
        Owner owner = looperThread.realm.createObject(Owner.class);
        looperThread.realm.commitTransaction();

        new Thread(new Runnable() {
            @Override
            public void run() {
                Realm realm1 = Realm.getInstance(looperThread.realmConfiguration);
                Owner owner1 = realm1.where(Owner.class).findFirst();

                while (true) {
                    Dog dog = new Dog();
                    realm1.beginTransaction();
                    owner1.getDogs().add(dog);
                    realm1.commitTransaction();
                    try {
                        Thread.sleep(100);
                    } catch (InterruptedException e) {
                        e.printStackTrace();
                    }
                }
            }
        }).start();

        final Runnable runnable = new Runnable() {
            @Override
            public void run() {
                Owner owner2 = looperThread.realm.where(Owner.class).findFirst();
                Log.e("OOO", "Dogs list size is " + owner2.getDogs().size());
                try {
                    Thread.sleep(1000);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }

                looperThread.postRunnable(this);
            }
        };

        looperThread.postRunnable(runnable);
    }
```

You need to check:
if the `currentTrack` is the same one created in the service. You didn't sort the results when `findFirst`, there is no guarantee that they are the same.

**Comment by lectricas** [comment]
I do use findfirst() actually. Also, In my example I'm using Realm.getDefaultInstance() every time I come to onCreate method. I'll double check it to find any mistakes.

**Comment by lectricas** [comment]
I've double checked the code and seems like everything is fine. Do you want me to show the code?

**Comment by beeender** [comment]
@lectricas Yes, please! If you want to share it privately, you can send it to help@realm.io

**Comment by lectricas** [comment]
don't care about privacy now. Here, take a look. 
Service (where recording is done):
https://github.com/lectricas/fixedrec2/blob/master/app/src/main/java/com/pythonanywhere/fixedrec/services/LocationService.java

Place where query is done:
https://github.com/lectricas/fixedrec2/blob/master/app/src/main/java/com/pythonanywhere/fixedrec/ViewActivity.java

Application class is called App.

**Comment by beeender** [comment]
In your `LocationService.startNewTrack`, to create the new track, you have:
```
currentTrack = new Track(calendar.getTime(), "user1");
```
And this created a standalone object which is not managed by Realm. Any further changes to this object won't be saved to Realm. To solve this:
```
currentTrack = realm.copyToRealm(currentTrack);
```
The return value of `copyToRealm` is the managed `RealmObject`.

And after changing this, you will get exception in ``stopNewTrack`. That is because of the setters to change the managed RealmObject is not inside a transaction. fix it by:
```
realm.beginTransaction();
currentTrack.setDateClosed(Convert.getCTine());
currentTrack.setDateUpdated(Convert.getCTine());
currentTrack.setRunning(false);
realm.commitTransaction();
```

**Comment by beeender** [comment]
@lectricas Is your problem solved? Thanks!

**Comment by lectricas** [comment]
yes, thank you.
