### ISSUE TITLE
Android Studio 2.0 preview with gradle error

### ISSUE THREAD

**Issue by shern91** [realm/realm-java#2302]
Hi everyone , i using android studio to develop my project, i using kinvey as my backend service, so i paste all the .jar file and .arr file in \lib folder. when i try to compile my project, i always get one error which is "Gradle build finished with 1 error (s)"

Error:Execution failed for task ':app:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: com/kinvey/java/AbstractClient$Builder$Option.class

and this is my build.gradle setting

apply plugin: 'com.android.application'

repositories {
    jcenter()

    flatDir {
        dirs 'libs'
    }
    mavenCentral()

}

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.2"

    defaultConfig {
        applicationId "com.example.lenovo.busttracker"
        minSdkVersion 14
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
        multiDexEnabled true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }

    dexOptions {
        preDexLibraries = false
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.0.1'
    compile 'com.android.support:design:23.1.1'
    compile(name:'kinvey-android-2.10.5', ext:'aar')
}

which part i have did wrong? thank in advance!

**Comment by cmelchior** [comment]
Hi @shern91 
It doesn't looks like your project is using Realm?

**Comment by shern91** [comment]
ya, didn't using Realm, actually i am move from Eclipse to AS, not very understand what is Realm.

**Comment by cmelchior** [comment]
This is a repository for the mobile database Realm: https://realm.io/

I am sorry, but we cannot really help you with Kinvey. I suggest contacting their support instead https://support.kinvey.com/support/home

**Comment by shern91** [comment]
ok, thank for ur reply and help.
