### ISSUE TITLE
`./gradlew test` is not running on CI, and mockito cannot mock final Realm class

### ISSUE THREAD

**Issue by beeender** [realm/realm-java#2303]
Two issues:

1) `./gradlew test` will fail `unitTestExample` because of
```
when(Realm.getInstance(any(RealmConfiguration.class))).thenReturn(mockRealm);
```
   will fail. Realm is an static class which cannot be mocked by Mockito. We might have to use PowerMock instead

2) Enable `./gradlew test` on CI.

**Comment by cmelchior** [comment]
We should also make all examples work when running `gw check`. This also include fixing lint warnings or ignore them

**Comment by beeender** [comment]
@emanuelez #2320 has been merged. Can you please help to enable the `./gradlew test` for `examples/unitTestExample/src/test` on CI and close this issue? Thanks!

**Comment by emanuelez** [comment]
This is now done both for PRs and normal builds
