### ISSUE TITLE
Relationship between two RealmObject - Out of memory error

### ISSUE THREAD

**Issue by heitorpr** [realm/realm-java#2306]
Hello guys, I have a very complex RealmObject that has many dependencies, also having complex RealmObjects. Follow the example (just showing the relationships):

RealmTask
```
    private RealmTaskDescription description;
    private RealmUser responsible;
    private RealmUser owner;
    private RealmTaskType taskType;
    private RealmProject project;
    private RealmWorkflow workflow;
    private RealmRepetitionRule repetitionRule;
    private RealmCheckList checkList;
    private RealmTaskState taskState;
    private RealmTeam team;
    private RealmList<RealmUser> followers;
    private RealmList<RealmAttachment> documents;
    private RealmList<RealmTaskEstimate> estimates;
    private RealmList<RealmTaskPrerequisite> prerequisites;
```

RealmUser
```
    private RealmUserSummary summary;
    private RealmUserStatistics statistics;
    private RealmList<RealmUserShift> shifts;
    private RealmList<RealmUser> partners;
    private RealmList<RealmUser> demanders;
```

RealmUserSummary
```
    private RealmTask task;
```

When I have this configuration, and I fetch the data filling in the objects. When I fill the fields of "RealmUserSummary" and try to use it in a new activity, I have in the memory managment on Android Studio displaying something like:  using 10 mb to 110 mb in seconds. And then I have an out of memory error.

If I try to acess the RealmTask in a new activity, I also get an out of memory error after the error before. The strange thing is when I open my app I has a Task list that uses the RealmTask, but the out of memory just occurs when opening a new Activity.

My guess:

RealmTask has RealmUser that has RealmUserSummary that has RealmTask ...

Somene can help me? =).  Today i'm solving my problem using a task_id in RealmUserSummary, and giving a find on Task (on main thread) when it is in need.

Thank you very much!

**Comment by beeender** [comment]
First, how big is your Realm file right now?
Did you often create Realm instances in different threads without closing them?

**Comment by heitorpr** [comment]
My realm file has : 1.12 mb. (default.realm)

I always follow this pattern on asynctasks:

```
Realm realm = null;
try {
	realm = Realm.getDefaultInstance();
	
	//Do something
	
} catch (Exception ex) {
	Log.e("error", ex.toString());
} finally {
	if (realm != null) {
		realm.close();
	}
}
```

And if i need to change an object i always follow this pattern

```
Realm realm = null;
try {
	realm = Realm.getDefaultInstance();
	realm.beginTransaction();
	
	//Do something
	
	realm.commitTransaction();
} catch (Exception ex) {
	Log.e("error", ex.toString());
} finally {
	if (realm != null) {
		realm.close();
	}
}
```

**Comment by beeender** [comment]
@heitorpr It seems everything is OK... Could you please check if you have any memory leaks? The RealmObject won't be loaded to the memory until you access them, so even lots of relationships of `RealmObjects` defined, the memory usage won't be huge. If there is no leak in your side, would you please share the project with us? to help@realm.io if you want to share it privately.

**Comment by heitorpr** [comment]
I will need some time to check if Im not having a leak, and I will check with my manager if I can share the project. Give me sometime. Thanks :)

**Comment by cmelchior** [comment]
Hi @heitorpr Any update on this?

**Comment by heitorpr** [comment]
@cmelchior not yet. I will need some time because my manager didnt allowed me to share the project. So I'm doing another project.

**Comment by demo-Ashif** [comment]
@heitorpr  hello - sorry to bother you. I also have this kind of complex object with many dependencies. I need to convert mother object to json with all data. Used serialize method but not getting data properly. Have you faced these type of issues?

**Comment by heitorpr** [comment]
@demo-Ashif, hello! Dont worry. About this, actually my complex object is composed just with raw data, Strings, Integers, etc. All that dependencies that I have, actually I do on client side (Android side). For example, I have an endpoint in my api that has users, and my task object just has the "user_id" key. So I don't need to serialize everything in just one shot. Well, if that helps, i didn't have any problem using this combination:

GSON + Retrofit2 + Okhttp3

**Comment by beeender** [comment]
@heitorpr Did you solve your problem? Can we close this issue now? You can always reopen it or create a new one if further help needed :)

**Comment by heitorpr** [comment]
Yes! For now I solved my problem using a different solution. Will study
this later and reopen if needed. Thx!
Em 16 de mar de 2016 12:06 AM, "Chen Mulong" <notifications@github.com>
escreveu:
