### ISSUE TITLE
copyToRealmOrUpdate does not save all fields

### ISSUE THREAD

**Issue by MGaetan89** [realm/realm-java#2311]
I am using Realm to save and display the data I received from a server (using Retrofit). But it seems that some fields are not persisted, resulting in `null` values in the table. This is how I use Realm:

In the `onCreate(Bundle)` of my `Fragment` I get a list of `Category` from the database (Realm is initialized using `Realm.getDefaultInstance()`):

```java
this.categories = this.realm.where(Category.class).findAllSortedAsync("name");
this.categories.addChangeListener(this.categoriesListener);

this.categoriesAdapter = new CategoriesAdapter(this.getContext(), this.categories);
```

The listener is as follow:

```java
private final RealmChangeListener categoriesListener = new RealmChangeListener() {
	@Override
	public void onChange() {
		if (categoriesAdapter != null) {
			categoriesAdapter.notifyDataSetChanged();
		}
	}
};
```

And my `onResponse(Call<List<Category>> call, Response<List<Category>> response)` (from Retrofit):

```java
@Override
public void onResponse(Call<TradingThemes> call, Response<TradingThemes> response) {
	if (response.isSuccess()) {
		return;
	}

	final List<Category> categories = response.body();

	this.realm.executeTransaction(new Realm.Transaction() {
		@Override
		public void execute(Realm realm) {
			realm.copyToRealmOrUpdate(categories);
		}
	}, null);
}
```

This way, the listener is called when the data are read from the database (I used an asynchronous query) and after the server response is saved in the database. The listener is indeed called twice, as expected, but some fields are `null`. However, this does not happen for every entry, and the server actually some data where I have some `null` values.

```java
// This is a simplified version of the model
// The missing fields are primitives, Date or String
public class Category extends RealmObject {
	@PrimaryKey
	private String id;
	private String name;
	private RealmList<Category> relatedCategories;

	// Getters and setters
}
```

Is there something wrong in my usage of Realm? Or is it a bug in the library?
Thanks for your help.

**Comment by MGaetan89** [comment]
I just noticed that the server returns a subset of the data in the `relatedCategories` field. So the existing values are replaced with the default one. What would be the best approach to prevent that?

**Comment by cmelchior** [comment]
Unfortunately `copyToRealm` is not really designed to handle the case. You are not the first to run into this issue though, and we already have an issue tracking it + discussing possible solutions: https://github.com/realm/realm-java/issues/2288

Right now the only work-around is unfortunately to manually do the update. Alternatively you can use `createOrUpdateFromJson` which will only override the fields actually set (but it require that your JSON matches the model class).

**Comment by MGaetan89** [comment]
Thanks for your response and the link. I'll follow its progress.

About the `createOrUpdateFromJson` solution, it means that a field annotated with `@SerializedName` (from the Gson library, like `@SerializedName("foo") private String bar;`) won't work, right?

**Comment by cmelchior** [comment]
Yes, that is unfortunately correct.

**Comment by MGaetan89** [comment]
Ok, thank you for your help. I should be able to make it work now.
I'll close this issue so the focus can be on the other dedicated issue.

Keep the good work with the library :)

**Comment by rameshcool** [comment]
I'm using realm for a printing application. when i select duplex printing and send in history page page count won't show. first it should be saved in to database.its null.once swipe refresh value displayed and it saved in database.whta's the problem.used realmlivedata, for saving copyToRealmOrUpdate and RealmRecyclerViewAdapter.what changes i need to do to display printcount in Ui.
