### ISSUE TITLE
Custom sorting of RealmResults

### ISSUE THREAD

**Issue by dkuida** [realm/realm-java#2313]
I wonder if there is such an option as to sort by custom predicate/calculation?
if for example I have a latitude/longitude and I want to sort by distance ( lat^2+lon^2)^0.5 so is it doable ? and if not I will be glad to fork and implement it myself if you could give me some head start 

I plan in general anyway to add geographic capabilities to realm so that is something to start with

**Comment by beeender** [comment]
Unfortunately it is not supported by our underlying storage engine (which is not open-sourced yet) right now :(

**Comment by cmelchior** [comment]
Also note that we have geospatial queries on the roadmap as well: #1772

**Comment by dkuida** [comment]
So I guess that the closes thing to actually making some kind of distance base calculation ( assuming we use planar approximation and not a real geographic CS) would something like this ?
`  double lat = currentLocation.getLatitude();
        double lon = currentLocation.getLongitude();
        RealmResults<Business> allInBox = Realm.getDefaultInstance().where(Business.class)
                .between("lat", lat - ROUGHT_ONE_METER * 100, lat + ROUGHT_ONE_METER * 100)
                .between("lon", lon - ROUGHT_ONE_METER * 100, lat + ROUGHT_ONE_METER * 100)
                .findAll();
        List<Business> addsInLocation = Stream.of(allInBox).sortBy(x -> dist(x)).collect(Collectors.toList());`

Anyway would be glad to contribute to that effort

**Comment by dkuida** [comment]
And another Q.
If I have Person and it has a property of RealmList<Dog> so would it be possible to make a link query such as realm.where(Person.class).equalTo("Person.Dogs.count",1) ?
I mean to get properties that has linked property with more than one element
seem like using linked props with aggregate wouldn't work

**Comment by Zhuinden** [comment]
https://github.com/realm/realm-java/issues/3669

**Comment by Zhuinden** [comment]
@dkuida that is tracked in https://github.com/realm/realm-java/issues/1598
