### ISSUE TITLE
Add a check if database file exists when Realm.migrateRealm() is called.

### ISSUE THREAD

**Issue by zaki50** [realm/realm-java#2316]
if `Realm.migrateRealm()` is called when Realm file does not exist, it may create wrong Realm file(no schema contained) or may cause the exception in Migration code.

This issue is reported by @tiro105 on slack chat. Thanks!

We have 2 choices in the case of missing Realm file.

* throw exception if Realm file does not exist
* create Realm file and execute normal initialization of schema instead of executing migration

What do you think? @realm/java

**Comment by cmelchior** [comment]
I would prefer throwing an exception since people might expect the migration to do some work (like adding new objects). Trying to migrate a non-existing DB sounds like a logical error to me.

**Comment by zaki50** [comment]
@cmelchior I agree with that.

**Comment by dalinaum** [comment]
I prefer to throw an exception. I don't like silent behaviours. It sometimes causes the debugging problem.
