### ISSUE TITLE
HashCode not working correctly

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#2323]
Right now we use the following for `hashCode`: 

```
        String realmName = realm.getPath();
        String tableName = row.getTable().getName();
        long rowIndex = row.getIndex();

        int result = 17;
        result = 31 * result + ((realmName != null) ? realmName.hashCode() : 0);
        result = 31 * result + ((tableName != null) ? tableName.hashCode() : 0);
        result = 31 * result + (int) (rowIndex ^ (rowIndex >>> 32));
        return result;
```

The problem is `rowIndex` might suddenly change through the use of `moveLastOver`. This will change the hashCode unexpectedly and break things like Set: https://docs.oracle.com/javase/7/docs/api/java/util/Set.html

Cocoa currently uses the PrimaryKey value (which is not allowed to change) if possible, otherwise fallback to the default hashcode implementation. This has the downside that `result.get(0).equals(result.get(0)) == false`.

Without persistent identifiers we have to accept one of the short-comings :cry: 

I would be tempted to say that our current approach is OK and we should just document that `hashCode` is not stable and can change. With #2196 soon ready, people have more tools to work around it anyway.

What do you think @realm/java ?

**Comment by beeender** [comment]
Why don't just use row's raw pointer to compute the hashcode? then we don't even need to has the realm name and table name.

**Comment by cmelchior** [comment]
The raw pointer can also change between TableViews as far as I know:
```
realm.allObjects(Foo.class).get(0).equals(realm.allObjects(Foo.class).get(0)) == false
```

**Comment by beeender** [comment]
Then we should use the `TableView::get_source_ndx()` which is the index in the table

**Comment by cmelchior** [comment]
Yes, but the source index changes with `moveLastOver`, which is why the current proposal is problematic.

**Comment by cmelchior** [comment]
@stk1m1 I think the fix for this is to just document the behaviour in both Javadoc for RealmObject and on the website.

**Comment by stk1m1** [comment]
Until we have an immutable `RealmObject` identifier, the behavior should remain documented. The issue is closed for now.
