### ISSUE TITLE
java.lang.IllegalArgumentException: Primary key value must not be null

### ISSUE THREAD

**Issue by DanteAndroid** [realm/realm-java#2326]
When I set "minifyEnabled true" in my gradle, I got such error and the app crashes. When I disable it, app runs fine.
Here is error detail:
`                                                                       Process: com.dante.knowledge.debug, PID: 860
                                                                       java.lang.IllegalArgumentException: Primary key value must not be null.
                                                                           at io.realm.am.a(Unknown Source)
                                                                           at io.realm.DefaultRealmModuleMediator.a(Unknown Source)
                                                                           at io.realm.r.a(Unknown Source)
                                                                           at io.realm.r.b(Unknown Source)
                                                                           at com.dante.knowledge.a.b.a(Unknown Source)
                                                                           at com.dante.knowledge.mvp.b.l$1.a(Unknown Source)
                                                                           at com.dante.knowledge.mvp.b.l$1.a(Unknown Source)
                                                                           at com.d.a.a.a$4.run(Unknown Source)
                                                                           at android.os.Handler.handleCallback(Handler.java:739)
                                                                           at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                           at android.os.Looper.loop(Looper.java:135)
                                                                           at android.app.ActivityThread.main(ActivityThread.java:5254)
                                                                           at java.lang.reflect.Method.invoke(Native Method)
                                                                           at java.lang.reflect.Method.invoke(Method.java:372)
                                                                           at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
                                                                           at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)`

and here is my proguard-rules.pro:

`-keep class butterknife.** { *; }
-dontwarn butterknife.internal.**
-keep class **$$ViewBinder { *; }
-keepclasseswithmembernames class * {
    @butterknife.* <fields>;
}
-keepclasseswithmembernames class * {
    @butterknife.* <methods>;
}

-keepattributes Signature
-keepattributes *Annotation*
-keep class sun.misc.Unsafe { *; }
-keep class com.google.gson.examples.android.model.** { *; }

-keepattributes *Annotation*,EnclosingMethod,Signature
-keepnames class com.fasterxml.jackson.** { *; }
-keep class org.codehaus.** { *; }
-keepclassmembers public final enum org.codehaus.jackson.annotate.JsonAutoDetect$Visibility {
 public static final org.codehaus.jackson.annotate.JsonAutoDetect$Visibility *; }
-keep public class your.class.** {
  public void set*(***);
  public *** get*();
}

-keep class io.realm.annotations.RealmModule
-keep @io.realm.annotations.RealmModule class *
-keep class io.realm.internal.Keep
-keep @io.realm.internal.Keep class * { *; }
-dontwarn javax.**
-dontwarn io.realm.**

-dontwarn butterknife.internal.**
-dontwarn okio.**
-dontwarn com.squareup.okhttp.**
-dontwarn com.fasterxml.jackson.databind.**

-keep class org.eclipse.mat.** { *; }
-keep class com.squareup.leakcanary.** { *; }
-keep class com.squareup.haha.** { *; }
-dontwarn com.squareup.haha.guava.**
-dontwarn com.squareup.haha.perflib.**
-dontwarn com.squareup.haha.trove.**
-dontwarn com.squareup.leakcanary.**`

Furthermore, you can just check out my code : [Here](https://github.com/DanteAndroid/Knowledge).
I love Realm and appreciate if you guys could help me.

**Comment by cmelchior** [comment]
That sounds strange. That error should have nothing to do with obfuscation. Does it only happen when you enable ProGuard?

**Comment by DanteAndroid** [comment]
Sadly the answer is Yes. Although it appeared once, but I fixed it. (Cuz Primary key value is null, obviously). My repository is not so big, so maybe you can check it out :)

**Comment by beeender** [comment]
@DanteAndroid Something is wrong after proguard processing your source. Check `ZhihuModel.java` line 49, after ``Json.parseZhihuNews`, the date is `null`. And since it is the `PrimaryKey`, it cannot be `null`.

**Comment by DanteAndroid** [comment]
@beeender Reeeeeeaaaaaaaally appreciate you point out source of the problem, I simply put a `-keep class com.dante.knowledge.mvp.model.** { *; }` in my proguard-rules.pro just to solve it. I wonder whether I have to keep my model classes in every application. Is that kinda a bug? I don't see any instruction about keeping the model classes in Gson page. Thanks again for you and @cmelchior 's patience. (BTW, could you tell me how do you locate the error?)

**Comment by DanteAndroid** [comment]
@beeender I find out that there's several lines in Gson's proguard code: `# Gson uses generic type information stored in a class file when working with fields. Proguard
# removes such information by default, so configure it to keep all of it.`
So maybe this error is my fault :( I just ignored those sentences.

**Comment by DanteAndroid** [comment]
@beeender May I ask you one more question (since you already see my code)?  I use `results.sort("date", Sort.DESCENDING);` to sort "ZhihuJson" to let the latest story items on top, (surely 'String date' is Primary key). But only get story items added at bottom.
To be clear, ZhihuJson is like this: `    /**
     * date : 20160129
     * stories : [{"images":["http://pic1.zhimg.com/aef18b16a9a6dcb445d5c235784c25a8.jpg"],"type":0,"id":7813824,"ga_prefix":"012915","title":"运气好的话，说不定 3 万年就把木星挪过来"},{"images":["http://pic2.zhimg.com/3ade66b9adc39db01656baa25ed38775.jpg"],"type":0,"id":7782299,"ga_prefix":"012914","title":"讲真，请不要用眼镜布擦眼镜"},{"images":["http://pic3.zhimg.com/541662b02a6a99a860f7f1b80cd9880e.jpg"],"type":0,"id":7813351,"ga_prefix":"012913","title":"好酱配好面，意面的酱怎么做才好吃？"},{"title":"这俩兄弟自制令人惊叹的玩具，谢耳朵估计也会拜服","ga_prefix":"012912","images":["http://pic3.zhimg.com/129c39a0a941648724dc90ce24e792be.jpg"],"multipic":true,"type":0,"id":7812687},{"images":["http://pic2.zhimg.com/fbf9f9907b48739dcccd6b6a94188d8d.jpg"],"type":0,"id":7812703,"ga_prefix":"012911","title":"一份非常详细的过年囤货指北"},{"images":["http://pic1.zhimg.com/a28113f36de3e7b2e5a2d83b6b385304.jpg"],"type":0,"id":7811123,"ga_prefix":"012910","title":"看完这篇攻略，你也能拍出小王子的小行星"},{"title":"我是一位孕期坚持健身的孕妇，目前我和宝宝都很健康","ga_prefix":"012909","images":["http://pic4.zhimg.com/4a3e3c49433d77ba525a02a5fdb1496f.jpg"],"multipic":true,"type":0,"id":7810014},{"images":["http://pic3.zhimg.com/adb17dd5357b5c4f7e2b83b5ef3b729a.jpg"],"type":0,"id":7805494,"ga_prefix":"012908","title":"海星不止会卖萌，这种凶起来真是「魔鬼杀手」"},{"images":["http://pic1.zhimg.com/d95e4a92692c4b31f57256ce7fb1db5c.jpg"],"type":0,"id":7811235,"ga_prefix":"012907","title":"总觉得感冒是小事，很多大型疫情往往又是流感引起"},{"images":["http://pic1.zhimg.com/660c6c4f33faf14f448263c980ae8e40.jpg"],"type":0,"id":7811643,"ga_prefix":"012907","title":"这些奇葩的电影，光是念出片名来都很羞耻"},{"images":["http://pic3.zhimg.com/a37a9eddf88159cbf461d37e63095fd6.jpg"],"type":0,"id":7809891,"ga_prefix":"012907","title":"味同嚼臭袜子的奶酪，歪果仁民还特别喜欢"},{"images":["http://pic1.zhimg.com/c366908a775629e3eedf0976816e24fc.jpg"],"type":0,"id":7806632,"ga_prefix":"012906","title":"瞎扯 · 如何正确地吐槽"}]
     * top_stories : [{"image":"http://pic2.zhimg.com/9c8804770cef7efe1b464eb394f73a19.jpg","type":0,"id":7782299,"ga_prefix":"012914","title":"讲真，请不要用眼镜布擦眼镜"},{"image":"http://pic4.zhimg.com/e1d9a422616aceb7ec4525c02e934c43.jpg","type":0,"id":7811643,"ga_prefix":"012907","title":"这些奇葩的电影，光是念出片名来都很羞耻"},{"image":"http://pic3.zhimg.com/6b5d5533831ac8ccfb63948a8b9eb876.jpg","type":0,"id":7812703,"ga_prefix":"012911","title":"一份非常详细的过年囤货指北"},{"image":"http://pic1.zhimg.com/68e424b56afa5117cf425bed6903f52c.jpg","type":0,"id":7809940,"ga_prefix":"012821","title":"20 岁看，几乎什么也不懂；30 岁再看，想哭"},{"image":"http://pic4.zhimg.com/bb6689ab114fde9b75d260728577b95b.jpg","type":0,"id":7810014,"ga_prefix":"012909","title":"我是一位孕期坚持健身的孕妇，目前我和宝宝都很健康"}]
     */`

Besides, when I want to show the stories, I did not findAll for ZhihuJson, but find all ZhihuStories(which is the field of ZhihuJson). I don't know whether it matters. Thanks for helping, Realm is really cool.

**Comment by beeender** [comment]
Q: How do I add latest data to top of the database quickly?
A: You won't be able choose the order where the data stored when you add something to the Realm. You just sort the `RealmResults` as what you want.

Q: Could Realm sort date String like "20160225" ? How?
A: The string sorting is based on the character's order in the ASCII table. I am not quite sure why the results is not what you expected. Maybe you could list all the date string and try to do some testing. But it is strange that you are using `String` for date and use it as a primary key. It seems very likely it would be duplicated in the JSON response. For storing date, using `Date` field might be a better option IMO.

Q: Is there any order difference between search the parent model then get its field and just search the field class?
I don't quite get the question ... Could you please explain the question?

**Comment by DanteAndroid** [comment]
@beeender well, I got a Json response like: 
```
     * date : 20160129
     * stories : [{story one, story two, ....}]
```so, I create a whole model object for this response , call it ZhihuJson.class, then I create one story object for the story content, call it ZhihuStory.class. When I want to get stories, I may search for ZhihuJson, then use get method to get the stories list, or, just search for ZhihuStory.class immediately get the stories list. So, in another words, when I sort the parent class,  is the field class sorted as well.
I ask this because if answer is no, then I won't get my expected results; If yes, I could do further test like you said. (If you don't get it, just ignore it.)
As to why I use date as primary:
- we get different response with every date
- If the date is duplicate, the new response will just override the old. Isn't that what copyToRealmOrUpdate do?
- How do I let Gson pass date String to Date?

If my questions are dumb, forgive me : D

**Comment by DanteAndroid** [comment]
You should really help me, sorting date drives me crazy T_T

**Comment by DanteAndroid** [comment]
@beeender And I just do a test to find that sort the main model class actually doesn't sort its field class, that is to say, I sorted the ZhihuJson with date, actually doesn't sort the ZhihuStory class, so when I search for ZhihuStories, I still get the order when I added them (the latest data is at bottom).
I think you guys could improve it, cause in most conditions, I sort some class, its field class should be sorted as well, don't you think?
Thanks again for your great work.

**Comment by DanteAndroid** [comment]
Here's my code for test:
##Before:
`
    private List<ZhihuStory> zhihuStories
DB.findAllDateSorted(ZhihuJson.class);//this method sort the zhihuJson with date
 zhihuStories = DB.findAll(ZhihuStory.class);`//    field RealmList<ZhihuStory> stories is in zhihuJson, so it should be sorted as well


##After
`        RealmResults<ZhihuJson> list = DB.findAllDateSorted(ZhihuJson.class);
        for (ZhihuJson json : list) {
            zhihuStories.addAll(json.getStories());//I add the stories got by zhihuJson directly, and the order is right(that means zhihuJson was sorted).
        }`

Conclusion:
Sort method works, but not influence its field class.

**Comment by beeender** [comment]
sort on `ZhihuJson` won't impact on `ZhihuStory` (`ZhihuStory` doesn't even have a `date` field, how could be sorted?). One suggestion is you can save a `date` field for `ZhihuStory` as well. Then you can just use `Realm.where(ZhihuStory.class).findAll().sort("date")`

**Comment by DanteAndroid** [comment]
@beeender You are right, ZhihuStory doesn't have a date, but isn't it logical if I sort some class, and its field be sorted as well? I consider save a date for it, but it would be quite complex.

**Comment by beeender** [comment]
The API `RealmResults.sort()` means it will sort the given `RealmResults` based on the given field. The `RealmResults` is a collection of given `RealmObject`.  https://realm.io/docs/java/latest/api/io/realm/RealmResults.html#sort-java.lang.String-

If you want to sort the field `RealmList`, you need to call `realmList.where().findAllSorted()`. https://realm.io/docs/java/latest/api/io/realm/RealmList.html#where--

**Comment by DanteAndroid** [comment]
You are right, but I still think it is great if there's such method can sort one class and its field. Thanks a lot whatsover

**Comment by beeender** [comment]
You can do that, as what i said, `RealmResults<ZhihuStory> results = zhihuJson.stories.where().findAllSorted(`title`)` (sorting by `title` for example).

**Comment by DanteAndroid** [comment]
@beeender Of course I know how to sort... Apparently that doesn't meet my demand, because title doesn't have an order. And adding date isn't realistic, coz even every ZhihuStory has a date, in one day we have many stories, and with the same date, how will this punch of stories be sorted? That won't be expected.

**Comment by DanteAndroid** [comment]
By "such method can sort one class and its field", I mean "sort one class and its field **class**"

**Comment by beeender** [comment]
Since the original issue is solved, i am closing this issue now. Feel free to create a new issue if you have further issues/suggestions. Thanks for the feedback!
