### ISSUE TITLE
This Realm instance has already been closed, making it unusable

### ISSUE THREAD

**Issue by DanteAndroid** [realm/realm-java#2346]
When I perform a compatibility test in about 50 devices, I got such error in several devices (5%-10%), here's my code about realm: 
     
    public class DB {

    public static Realm realm;

    public static void saveOrUpdate(RealmObject realmObject) {
        realm.beginTransaction();
        realm.copyToRealmOrUpdate(realmObject);
        realm.commitTransaction();
    }
    ......
    //other methods
    } 
In every activity's onCreate:

       DB.realm = Realm.getDefaultInstance();
 
In every activity's onDestroy:
 
        super.onDestroy();
        DB.realm.close();

**Comment by DanteAndroid** [comment]
BTW, could I just not close the Realm? Or how could I just get one static instance, and close it when app exits?I got several errors since I close them.

**Comment by beeender** [comment]
What is the error message? closing realm in a wrong thread?

**Comment by DanteAndroid** [comment]
`reason: java.lang.IllegalStateException: This Realm instance has already been closed, making it unusable.
#16797	02-24 18:14:30.130	13021	E	TestinAgent	 ----------------------------------------
#16798	02-24 18:14:30.130	13021	E	TestinAgent	 stacktrace:
#16799	02-24 18:14:30.130	13021	E	TestinAgent	
#16800	02-24 18:14:30.130	13021	E	TestinAgent	         at io.realm.BaseRealm.checkIfValid(BaseRealm.java:344)
#16801	02-24 18:14:30.130	13021	E	TestinAgent	         at io.realm.RealmResults.isLoaded(RealmResults.java:758)
#16802	02-24 18:14:30.130	13021	E	TestinAgent	         at io.realm.RealmResults.size(RealmResults.java:389)
#16803	02-24 18:14:30.130	13021	E	TestinAgent	         at com.bigkoo.convenientbanner.adapter.CBPageAdapter.getRealCount(CBPageAdapter.java:39)
#16804	02-24 18:14:30.130	13021	E	TestinAgent	         at com.bigkoo.convenientbanner.adapter.CBPageAdapter.getCount(CBPageAdapter.java:35)
#16805	02-24 18:14:30.130	13021	E	TestinAgent	         at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:518)
#16806	02-24 18:14:30.130	13021	E	TestinAgent	         at android.support.v4.view.ViewPager.setCurrentItemInternal(ViewPager.java:514)
#16807	02-24 18:14:30.130	13021	E	TestinAgent	         at android.support.v4.view.ViewPager.setCurrentItem(ViewPager.java:495)
#16808	02-24 18:14:30.130	13021	E	TestinAgent	         at com.bigkoo.convenientbanner.ConvenientBanner$AdSwitchTask.run(ConvenientBanner.java:110)
#16809	02-24 18:14:30.130	13021	E	TestinAgent	         at android.os.Handler.handleCallback(Handler.java:615)
#16810	02-24 18:14:30.130	13021	E	TestinAgent	         at android.os.Handler.dispatchMessage(Handler.java:92)
#16811	02-24 18:14:30.130	13021	E	TestinAgent	         at android.os.Looper.loop(Looper.java:153)
#16812	02-24 18:14:30.130	13021	E	TestinAgent	         at android.app.ActivityThread.main(ActivityThread.java:5014)
#16813	02-24 18:14:30.130	13021	E	TestinAgent	         at java.lang.reflect.Method.invokeNative(Native Method)
#16814	02-24 18:14:30.130	13021	E	TestinAgent	         at java.lang.reflect.Method.invoke(Method.java:511)
#16815	02-24 18:14:30.130	13021	E	TestinAgent	         at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:837)
#16816	02-24 18:14:30.130	13021	E	TestinAgent	         at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
#16817	02-24 18:14:30.130	13021	E	TestinAgent	         at dalvik.system.NativeStart.main(Native Method)`

I only close it at onDestroy, no other places.

**Comment by beeender** [comment]
But your `CBPageAdapter` is still using it, that is the problem. `RealmObject` `RealmResults` and `RealmList` will be valid only if their corresponding Realm instance is still opened.

See https://realm.io/docs/java/latest/#controlling-the-lifecycle-of-realm-instances

**Comment by DanteAndroid** [comment]
@beeender  sounds like a bug in CBPageAdapter, which is a class of a library I use for show banner. [FYI](https://github.com/saiwu-bigkoo/Android-ConvenientBanner). What confuses me is that this error just appear randomly, cause I commit a test a few moments before, and the result contains no that error any more. 
I don't know, maybe Realm can improve its stability, and make closing Realm easier or better automatically :)

**Comment by xbroak** [comment]
Also seeing this across even the most simple deployments of Realm, closing is extremely painful and barely works at the best of times

**Comment by beeender** [comment]
The major concern from us to do GC for Realm instance is we have to introduce lock to ensure thread safety which might slow down other thread (especially UI thread) randomly (GC will start kind of randomly). Let's see if we can find a better way to easy the Realm instance life control in the future.
