### ISSUE TITLE
Invalid format of Realm file only with signed apk in Nexus Android v6.0.1

### ISSUE THREAD

**Issue by chandana1212** [realm/realm-java#2350]
Hi I am not getting any issues when I installed debug apk. When I installed the signed apk in 6.0.1v  I am getting the below error.
**Caused by: java.lang.IllegalArgumentException: Illegal Argument: Invalid format of Realm file.** at Realm.getInstance(this). I placed this in the application class.

I tried un installing and installing the same apk but still exists.

Can you please help e in fixing this issue.

**Comment by cmelchior** [comment]
Hi @chandana1212. We need more information in order to help you. Are you using an encrypted Realm or copying the Realm file from your assets or similar?

**Comment by chandana1212** [comment]
In my app I placed the realm 0.82.2 jar file in the libs folder and and wrote Realm.getInstance(this) in my application class. I am not using encrypted realm and I am not copying the realm file.

**Comment by cmelchior** [comment]
Did you overwrite an existing app that might had a Realm file? Have you tried uninstalling the app and installing it again?

**Comment by chandana1212** [comment]
I am not overwriting anything. I tried uninstalling and installing but
issue still exists.

*Chandana Dara*

**Comment by cmelchior** [comment]
Is this happening on multiple devices or only a single one? Also if you can reproduce it, can you send the APK to help@realm.io ?

**Comment by cmelchior** [comment]
Closing due to no response, and we cannot reproduce this. Please reopen if you are still seeing this.
