### ISSUE TITLE
java.lang.ClassCastException when trying to realm.copyToRealmOrUpdate()

### ISSUE THREAD

**Issue by aalt0** [realm/realm-java#2353]
After the Realm lib was updated today I started getting this exception thrown in the app:

java.lang.ClassCastException: com.hubchat.Hubchat.data.model.user.User cannot be cast to io.realm.UserRealmProxyInterface
at io.realm.UserRealmProxy.copy(UserRealmProxy.java:816)
at io.realm.UserRealmProxy.copyOrUpdate(UserRealmProxy.java:811)
at io.realm.DefaultRealmModuleMediator.copyOrUpdate(DefaultRealmModuleMediator.java:426)
at io.realm.Realm.copyOrUpdate(Realm.java:1395)
at io.realm.Realm.copyToRealm(Realm.java:746)
at com.hubchat.Hubchat.data.realm.UserDetailsProvider.insertUser(UserDetailsProvider.java:143)

etc.

And the actual code doing the copying to realm code which still worked earlier today:

```
    public static void insertUser(final User user, final String service) {
        final Realm realm = Realm.getDefaultInstance();
        try {
            user.setSignedInVia(service);
            realm.beginTransaction();
            realm.copyToRealmOrUpdate(user);
            realm.commitTransaction();
        } catch (Exception e) {
            Timber.d("inserting user failed");
            realm.cancelTransaction();
            e.printStackTrace();
        } finally {
            realm.close();
        }
    }
```

The User class looks like this

```
@RealmClass
public class User extends RealmObject {

    @PrimaryKey private String id;
    private String givenName;
    private String familyName;
    private String displayName;
    private String username;
    private String email;
    private boolean active;
    private boolean verified;
    private long timestamp;

    private Date updatedAt;
    private Date createdAt;
    private Image avatar;

    private String signedInVia;

// getters and setters...
}
```

The User object is received via Retrofit, which deserializes the JSON to standalone User object. This is also happening to other classes that I'm trying to persist in Realm and all of this has been working just fine earlier. I'm using the SNAPSHOT version, so I have a feeling that I've just missed something relating to the latest changes. Any ideas?

**Comment by cmelchior** [comment]
Hi @aalt0 
We just merged our byte code weaver into master, and it sounds like it isn't being triggered in your case. Note that from 0.88.0-SNAPSHOT you have to use our Gradle plugin: https://realm.io/news/android-installation-change/

**Comment by aalt0** [comment]
Yep, I had missed the news about the plugin. Thanks for the quick reply!
