### ISSUE TITLE
Generated RealmProxy classes cause "unchecked" warnings

### ISSUE THREAD

**Issue by bryanjswift** [realm/realm-java#2354]
I'm working on a project (using Realm 0.87.5) which used the following in
the project wide build.gradle:

    allprojects {
        gradle.projectsEvaluated {
            tasks.withType(JavaCompile) {
                options.compilerArgs << '-Xlint:all'
                options.compilerArgs << '-Werror'
            }
        }
    }

This causes errors when compiling the generated generated proxy classes.

    /Users/user/Documents/code/build/intermediates/classes/debug/io/realm/PersistableActivityIntervalRealmProxy.java:648: warning: [unchecked] unchecked conversion
            CacheData<PersistableActivityInterval> cachedObject = (CacheData) cache.get(realmObject);
                                                                  ^
      required: CacheData<PersistableActivityInterval>
      found:    CacheData
    error: warnings found and -Werror specified
    /Users/user/Documents/code/build/intermediates/classes/debug/io/realm/PersistableJsonModelRealmProxy.java:391: warning: [unchecked] unchecked conversion
            CacheData<PersistableJsonModel> cachedObject = (CacheData) cache.get(realmObject);
                                                           ^
      required: CacheData<PersistableJsonModel>
      found:    CacheData
    /Users/user/Documents/code/build/intermediates/classes/debug/io/realm/PersistableProfileRealmProxy.java:447: warning: [unchecked] unchecked conversion
            CacheData<PersistableProfile> cachedObject = (CacheData) cache.get(realmObject);
                                                         ^
      required: CacheData<PersistableProfile>
      found:    CacheData
    /Users/user/Documents/code/build/intermediates/classes/debug/io/realm/PersistableSyncStatusRealmProxy.java:365: warning: [unchecked] unchecked conversion
            CacheData<PersistableSyncStatus> cachedObject = (CacheData) cache.get(realmObject);
                                                            ^
      required: CacheData<PersistableSyncStatus>
      found:    CacheData
    1 error
    4 warnings
    :code:compileDebugJavaWithJavac FAILED

I believe this may be fixed by including the type parameter in the
[generated cast statement][1], but I'm not certain.

[1]: https://github.com/realm/realm-java/blob/master/realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.java#L702

**Comment by cmelchior** [comment]
Thanks for reporting this. I agree that should be fixed.
