### ISSUE TITLE
Realm doesn't always load my data.

### ISSUE THREAD

**Issue by voider1** [realm/realm-java#2359]
I'm writing an Android app for timetables at my school, and I decided to go with Realm.
I want to give people the functionality to download your own timetable to your device, and I'd like to store it in a DB. 
I went testing, so this is the code:

```
RealmQuery dbLessonss = realm.where(Timetables.class).equalTo("identity", GridsView.timetableName);

        if (dbLessonss.count() > 0) {
            List<Timetables> lessonss = dbLessonss.findAll();
            for (Timetables lesson : lessonss) {
                try {
                    int year = lesson.getYear();
                    int month = lesson.getMonth();
                    int day = lesson.getDay();

                    if (checkDay(year, month, day) == position + Calendar.MONDAY)
                        offLessons.add(lesson);
                } catch (ParseException e) {
                    e.printStackTrace();
                }
            }
        } 
```

It should load those from the DB. 
And it sometimes does, but sometimes it doesn't.
```

	@Override
	protected String[] doInBackground(Integer... params) {
		final int position = params[0];
		String timetableName = GridFragment.grids[pos].get(position);
		Realm realm = Realm.getInstance(context);
		long timetablesAvailableOffCount = realm.where(Timetables.class).equalTo("identity",
				timetableName).count();

		if (timetablesAvailableOffCount > 0) return new String[] {timetableName};

		if (Utility.hasActiveInternetConnection(context)) {
			String timetable = Utility.url + Utility.timetablesUrlPostfix + "%s";

			switch (pos) {
				case 0:
					timetable = String.format(timetable, Utility.timetablesClassnames + "%s");
					break;
				case 1:
					timetable = String.format(timetable, Utility.timetablesTeachers + "%s");
					break;
				case 2:
					timetable = String.format(timetable, Utility.timetablesClassrooms + "%s");
					break;
			}

			timetable = Utility.getHTTPData(String.format(timetable, GridFragment.grids[pos].get(position)));
			return new String[] {timetableName, timetable};
		}

		return null;
	}

	@Override
	protected void onPostExecute(String[] extras) {
		super.onPostExecute(extras);

		if (extras == null) {
			Utility.makeToast("Je moet netwerkverbinding hebben om rooster data op te halen!", context);
			return;
		}

		Intent toGrids = new Intent(context, GridsView.class);

		toGrids.putExtra("timetableName", extras[0]);
		if (extras.length == 2) toGrids.putExtra("timetable", extras[1]);
		context.startActivity(toGrids);
	}
```

In the onPostExecute, you see that if extras equals null, it should give me this toast, which means: "You gotta have network access to get timetable data."
When I get put the data in the DB, and I turn my wifi + datanetwork off, it sometimes loads it from the DB, and sometimes it just gives me this toast, so say, I click 5 times. 2 out of 5 it'll load, and 3 out of 5 it'll say I need internet connection.
Someone knows what kind of Voodo this is?

**Comment by beeender** [comment]
It doesn't sound like a Realm issue.
You could:
1 . Set a breakpoint on `long timetablesAvailableOffCount = realm.where(Timetables.class).equalTo("identity", timetableName).count();` to check if  `timetableName` is the correct input.
2. Set a breakpoint on where you write `Timetables` data to see if the data written to Realm is correct.
3. Maybe there is a timing issue, so keep the both both breakpoints enabled and check the running sequence.

**Comment by wuwu2000** [comment]
Hey voider1,
I had this issue too at some point. So I wrapped my call into another thread and I always got my disired result. Of course I was really unhappy about this.

But some weeks later I recognized I wasn't commiting transactions correctly. Please beware of start/stop transaction and open/close realm very carefully.

Especially because you pointed out this is a timing problem of your async tasks.

Too bad I didn't find out a way to properly track locked Realm yet, good luck :-)

**Comment by Zhuinden** [comment]
You're opening a random Realm instance in your `AsyncTask` that you're not closing.

If you do that, you'll eventually create inconsistency.

Same thing happens if you begin transactions that you don't cancel in case you don't commit them.

**Comment by beeender** [comment]
@voider1 I hope your issue is solved. I am closing this issue now, feel free to reopen this if needed. Thanks for your feedback!
