### ISSUE TITLE
Stored procedures

### ISSUE THREAD

**Issue by MiguelFale** [realm/realm-java#2360]
Hello!

Does realm support stored procedures? If so, how can one make use of them?

Thanks!

**Comment by zaki50** [comment]
Hi @MiguelFale 

Realm currently does not have Stored procedures.
You might be able to use `ChangeListener`  instead.

https://realm.io/docs/java/latest/api/io/realm/RealmResults.html#addChangeListener-io.realm.RealmChangeListener-

**Comment by MiguelFale** [comment]
Alright. Thanks!
