### ISSUE TITLE
Realm's Library size is 4 MB, any solution?

### ISSUE THREAD

**Issue by Shajeel-Afzal** [realm/realm-java#2363]
Hi

I see that Realm's size is 4 Mb, is there any suggestion to handle that? or an plan to decrease it in future? I am using 0.87.5 version of the library. 

Using Proguard decreased 1 MB however

```java
-keep class io.realm.annotations.RealmModule
-keep @io.realm.annotations.RealmModule class *
-keep class io.realm.internal.Keep
-keep @io.realm.internal.Keep class * { *; }
-dontwarn javax.**
-dontwarn io.realm.**

```

Thanks.

**Comment by cmelchior** [comment]
You can use our AAR instead of the JAR, which makes it easier to use ABI split to reduce the size: https://realm.io/news/android-installation-change/

**Comment by Shajeel-Afzal** [comment]
Thanks @cmelchior, can you please tell me latest version of `io.realm:realm-gradle-plugin`?

**Comment by Shajeel-Afzal** [comment]
Also it says: 

```java
Error:(16, 0) Plugin with id 'realm-android' not found.
Open File
```

**Comment by Shajeel-Afzal** [comment]
With Gradle plugin, i see that the size of the app is still 5.1 Mb with Proguard enabled, I think I need to research about ABI splits now.

**Comment by cmelchior** [comment]
Hi @Shajeel-Afzal 
You can see how to use it in our examples: https://github.com/realm/realm-java/blob/master/examples/gridViewExample/build.gradle

**Comment by cmelchior** [comment]
The above should hopefully guide you in the right direction. Please reopen if that is not the case.

**Comment by amitkumarsingh1991** [comment]
splits {
        // Split apks on build target ABI, view all options for the splits here:
        // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
        abi {
            enable true
            reset()
            include 'armeabi', 'armeabi-v7a', 'arm64-v8a', 'mips', 'x86', 'x86_64'
        }
    }

 please add this code inside app Gradle and run the appliation

**Comment by adiget** [comment]
armeabi is not supported anymore on 2.0.0
https://github.com/realm/realm-java/blob/master/CHANGELOG.md
