### ISSUE TITLE
Realm Result Null pointer exception

### ISSUE THREAD

**Issue by Sutirth** [realm/realm-java#2370]
I am trying to make my application to work offline. My database has row already inserted into it. When there is internet connection it works perfectly fine but when I try to make database call offline it crashes giving me null pointer exception.
 RealmResults<LeaderBoardDb> leaderBoardResults =
                realm.where(LeaderBoardDb.class)
                        .notEqualTo(WorkoutCashConstants.COLUMN_LEADERBOARD_RANK,"-1")
                        .findAll();
            leaderBoardResults.sort("rank");

**Comment by cmelchior** [comment]
Hi @Sutirth 
Can you post the exact exception message + the code in that region?

**Comment by Sutirth** [comment]
@cmelchior 
this is the exact exception message I get.

 FATAL EXCEPTION: main
 E/AndroidRuntime:  PID: 21586
 E/AndroidRuntime: java.lang.RuntimeException: Unable to start activity ComponentInfo{.LeaderBoards_Fragment}: java.lang.NullPointerException
 E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2413)
 E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2471)
 E/AndroidRuntime:     at android.app.ActivityThread.access$900(ActivityThread.java:175)
E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308)
E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:146)
 E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5602)
 E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method)
E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:515)
 E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1283)
 E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1099)
 E/AndroidRuntime:     at dalvik.system.NativeStart.main(Native Method)
/AndroidRuntime:  Caused by: java.lang.NullPointerException
03-01 11:53:00.251 21586-21586/ E/AndroidRuntime:     at .LeaderBoards_Fragment.setLeaderBoardAdapter(LeaderBoards_Fragment.java:294)
 E/AndroidRuntime:     at .LeaderBoards_Fragment.onCreate(LeaderBoards_Fragment.java:129)
 E/AndroidRuntime:     at android.app.Activity.performCreate(Activity.java:5451)
 E/AndroidRuntime:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1093)
 E/AndroidRuntime:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2377)
 E/AndroidRuntime:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2471) 
E/AndroidRuntime:     at android.app.ActivityThread.access$900(ActivityThread.java:175) 
E/AndroidRuntime:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1308) 
 E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:102) 
E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:146) 
 E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5602) 
 E/AndroidRuntime:     at java.lang.reflect.Method.invokeNative(Native Method) 
E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:515)

**Comment by cmelchior** [comment]
> .LeaderBoards_Fragment.setLeaderBoardAdapter(LeaderBoards_Fragment.java:294)

What code is running here. That is the origin of your NullPointerException

**Comment by Sutirth** [comment]
I am setting this in the adapter

RealmResults leaderBoardResults =
realm.where(LeaderBoardDb.class)
.notEqualTo(WorkoutCashConstants.COLUMN_LEADERBOARD_RANK,"-1")
.findAll();
leaderBoardResults.sort("rank");

**Comment by cmelchior** [comment]
That is two lines of code. I doubt both are line 294?
In any case the only likely NullPointer there is your `realm` variable. Have you verified it isn't null?

**Comment by Sutirth** [comment]
@cmelchior  I know its doubtful but when I apply debugger it crashes at realm results. Secondly this is inside fragment so 

    @Override
    public void onStart(){
        super.onStart();
        realm = Realm.getInstance(this);
    }


    @Override
    public void onStop(){
        super.onStop();
        realm.close();

    }

I write this acc to docs

**Comment by cmelchior** [comment]
Have you tried doing this instead then? 
```
if (realm == null) {
  throw new NullPointerException("Realm is null");
}
RealmResults leaderBoardResults =
realm.where(LeaderBoardDb.class)
.notEqualTo(WorkoutCashConstants.COLUMN_LEADERBOARD_RANK,"-1")
.findAll();
leaderBoardResults.sort("rank");
```

**Comment by Sutirth** [comment]
Will try and let you know

**Comment by Sutirth** [comment]
@cmelchior Any insight what should I do more

**Comment by cmelchior** [comment]
Try to split each method invocation into its own test. Just so you are 100% where the error is ocuring, something like:

```
failIfNull(realm);
RealmQuery query = realm.where(LeaderBoardDb.class);
failIfNull(query);
RealmQuery query = realm.where(LeaderBoardDb.class);
failIfNull(query);
query = query.notEqualTo(WorkoutCashConstants.COLUMN_LEADERBOARD_RANK,"-1");
failIfNull(query);
RealmResults leaderBoardResults = query.findAll();
failIfNull(leaderBoardResults);
leaderBoardResults.sort("rank");
failIf(leaderBoardResults);
```

**Comment by Sutirth** [comment]
@cmelchior  So I have debugged the issue in my scenario realm is null because it not getting initialize. But however I fail to understand how is it possible since I am doing this in fragment lifecycle

 @Override
    public void onStart(){
        super.onStart();
        realm = Realm.getDefaultInstance();
    }
 
 @Override
    public void onStop(){
        super.onStop();
        realm.close();
    }

**Comment by cmelchior** [comment]
@Sutirth 
Your method is being called during `onCreate` 

```
E/AndroidRuntime: at .LeaderBoards_Fragment.onCreate(LeaderBoards_Fragment.java:129)
E/AndroidRuntime: at android.app.Activity.performCreate(Activity.java:5451)
```

Which is before `onStart`: https://github.com/xxv/android-lifecycle

**Comment by Sutirth** [comment]
Arrghh foolish mistake from my side. @cmelchior  thnx a ton!!!
