### ISSUE TITLE
RxJava .distinct() doesnt work

### ISSUE THREAD

**Issue by atouchsimo** [realm/realm-java#2378]
## Goals
> REMOVE duplicate items

## Expected Results

> i have a list of data has duplicate items and want to remove them

## Actual Results

> it returns the same result the returned items doesnt get effect with distinct

## Version of Realm and Tooling

> 0.87.5

**Comment by cmelchior** [comment]
Hi @atouchsimo 
That use case is actually covered by our RxJava example here: https://github.com/realm/realm-java/blob/master/examples/rxJavaExample/src/main/java/io/realm/examples/rxjava/gotchas/GotchasActivity.java#L162-Lundefined

The reason it doesn't work like you would suspect currently is that our objects are live objects. We have an issue here: #1208 that will provide the tools for making this work a lot better, but until then you should use the work-arounds described in the example above.
