### ISSUE TITLE
`DynamicRealm` transaction doesn't advance read `Realm` instance in the same thread

### ISSUE THREAD

**Issue by beeender** [realm/realm-java#2382]
1) See below test case, `DynamicRealm` and `Realm` doesn't share the same `SharedGroup`, so below test will fail. It's doesn't give user a right feeling.

``` java
    @Test
    public void dynmicRealmDoesntAdvanceRealm() {
        Realm realm = Realm.getInstance(realmConfig);
        DynamicRealm dynamicRealm = DynamicRealm.getInstance(realm.configuration);

        dynamicRealm.beginTransaction();
        DynamicRealmObject allTypes = dynamicRealm.createObject(AllTypes.CLASS_NAME);
        dynamicRealm.commitTransaction();

        // Without realm.refresh, below test will fail.
        assertEquals(1, realm.allObjects(AllTypes.class).size());
    }
```

2) We do allow create `DynamicRealmObject` from a normal `RealmObject`.  `public DynamicRealmObject(RealmObject obj)`. This allows a `DynamicRealmObject` hold a normal `Realm` instance as the source. It will introduce `SharedGroup` version mismatch problem when trying to write it to a `DynamicRealm`.

The 1) might not be severe issue, it is just not easy to make user understand this behaviour. But 2) is surely a critical issue. It might cause inconsistency data.

**Comment by cmelchior** [comment]
Regarding 2) I don't think that is possible, since the only way you currently can create objects in DynamicRealm is through `createObject`, or am I missing something?

**Comment by cmelchior** [comment]
I can see why we the DynamicRealm and Realm being on different versions might look funny. Not sure I have a sane use-case for it happening though.

I tend to agree that they should have the same version though, but we need to careful with changelisteners still being triggered correctly when we fix it.

**Comment by beeender** [comment]
We have a constructor like this, it will set the Realm and row... this is a bad constructor i think.

```java
    public DynamicRealmObject(RealmObject obj) {
        if (obj == null) {
            throw new IllegalArgumentException("A non-null object must be provided.");
        }
        if (obj instanceof DynamicRealmObject) {
            throw new IllegalArgumentException("The object is already a DynamicRealmObject: " + obj);
        }

        Row row = obj.row;
        if (!obj.isValid()) {
            throw new IllegalArgumentException("An object managed by Realm must be provided. This " +
                    "is a standalone object or it was deleted.");
        }
        this.realm = obj.realm;
        this.row = ((UncheckedRow) row).convertToChecked();
    }
```

**Comment by beeender** [comment]
Maybe we should just disallow people from having DynamicRealm and Ream at the same time. I cannot really figure out the real case to have them both.

**Comment by cmelchior** [comment]
Migrations

**Comment by cmelchior** [comment]
But it also seems like a bit arbitrary restriction to have? Especially if there is a use-case we haven't anticipated? Perhaps just de-prioritise this to P2?

**Comment by beeender** [comment]
The major error case is like below

```java
Realm realm = Realm.getInstance(realmConfig);
AllJavaTypes allJavaTypes = realm.where(AllJavaTypes.class).findFirst();
DynamicRealmObject dynAllTypes = new DynamicRealmObject(allJavaTypes);
realm.beginTransaction();
// Do something could change the row index of dynAllTypes 
realm.commitTransaction();
​
DynamicRealm dynamicRealm = DynamicRealm.getInstance(realm.configuration);
dynamicRealm.beginTransaction();
// dynAllTypes's row index might not exist here
dynamicRealm.where(AllJavaTypes.CLASS_NAME).findFirst().setObject(AllJavaTypes.FIELD_OBJECT, dynAllTypes);
dynamicRealm.commitTransaction();
```

We need to check the equality of Realm instance in dynamic related setters.

**Comment by beeender** [comment]
#2380 will fix the severe issue 2). 1) is relatively minor issue. Downgrade this to P2.
