### ISSUE TITLE
java.lang.IllegalStateException: It's not allowed to delete the file associated with an open Realm

### ISSUE THREAD

**Issue by kinzirva** [realm/realm-java#2383]
Remember to close() all the instances of the Realm before deleting its file。
why activity oncreate() run this （ Realm.deleteRealm(realmConfiguration);）？

**Comment by cmelchior** [comment]
Hi @kinzirva 
Your question is unclear. Please see https://github.com/realm/realm-java/blob/master/CONTRIBUTING.md#filing-issues when creating issues. That way we can easier help you.

**Comment by kinzirva** [comment]
In this Activity，run this onCreate(),throw Exception :java.lang.IllegalStateException: It's not allowed to delete the file associated with an open Realm.Remember to close() all the instances of the Realm before deleting its file.
This is a problem with this method there is a line of code （ Realm.deleteRealm(realmConfiguration);）. 

public class GridViewActivity extends Activity implements AdapterView.OnItemClickListener {

    private GridView mGridView;
    private CountryAdapter mAdapter;

    private Realm realm;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_realm_example);

        RealmConfiguration realmConfiguration = new RealmConfiguration.Builder(this).build();

        // Clear the realm from last time
        Realm.deleteRealm(realmConfiguration);
        // Create a new empty instance of Realm
        realm = Realm.getInstance(realmConfiguration);
    }

    @Override
    public void onResume() {
        super.onResume();

        // Load from file "cities.json" first time
        if (mAdapter == null) {
            List<Country> cities = loadCities();

            //This is the GridView adapter
            mAdapter = new CountryAdapter(this);
            mAdapter.setData(cities);

            //This is the GridView which will display the list of cities
            mGridView = (GridView) findViewById(R.id.cities_list);
            mGridView.setAdapter(mAdapter);
            mGridView.setOnItemClickListener(this);
            mAdapter.notifyDataSetChanged();
            mGridView.invalidate();
        }
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        realm.close(); // Remember to close Realm when done.
    }

    private List<Country> loadCities() {
        // In this case we're loading from local assets.
        // NOTE: could alternatively easily load from network
        InputStream stream;
        try {
            stream = this.getAssets().open("country.json");
        } catch (IOException e) {
            return null;
        }

        // GSON can parse the data.
        // Note there is a bug in GSON 2.5 that can cause it to StackOverflow when working with RealmObjects.
        // To work around this, use the ExclusionStrategy below or downgrade to 1.7.1
        // See more here: https://code.google.com/p/google-gson/issues/detail?id=440
        Gson gson = new GsonBuilder()
                .setExclusionStrategies(new ExclusionStrategy() {
                    @Override
                    public boolean shouldSkipField(FieldAttributes f) {
                        return f.getDeclaringClass().equals(RealmObject.class);
                    }

                    @Override
                    public boolean shouldSkipClass(Class<?> clazz) {
                        return false;
                    }
                })
                .create();

        JsonElement json = new JsonParser().parse(new InputStreamReader(stream));
        List<Country> _countries = gson.fromJson(json, new TypeToken<List<Country>>() {
        }.getType());

        // Open a transaction to store items into the realm
        // Use copyToRealm() to convert the objects into proper RealmObjects managed by Realm.
        realm.beginTransaction();
        List<Country> realmCities = realm.copyToRealm(_countries);
        realm.commitTransaction();

        return new ArrayList<Country>(realmCities);
    }

    RealmResults<Country> _countries;

    public void updateCities() {
        // Pull all the cities from the realm
        _countries = realm.where(Country.class).findAll();
        // Put these items in the Adapter
        mAdapter.setData(_countries);
        mAdapter.notifyDataSetChanged();
        mGridView.invalidate();
    }

    @Override
    public void onItemClick(AdapterView<?> parent, View view, int position, long id) {
        Country modifiedCountry = (Country) mAdapter.getItem(position);

        // Acquire the RealmObject matching the name of the clicked Country.
        Country _country = realm.where(Country.class).equalTo("name", modifiedCountry.getName()).findFirst();

        // Create a transaction to increment the vote count for the selected Country in the realm
        realm.beginTransaction();
        _country.setVotes(_country.getVotes() + 1);
        realm.commitTransaction();

        updateCities();
    }
}


this is the exact exception message I get.
java.lang.IllegalStateException: It's not allowed to delete the file associated with an open Realm. Remember to close() all the instances of the Realm before deleting its file.
 at io.realm.BaseRealm$1.onResult(BaseRealm.java:532)
at io.realm.RealmCache.invokeWithGlobalRefCount(RealmCache.java:249)
at io.realm.Realm.deleteRealm(Realm.java:1234)

 at com.example.love.realm_java.GridViewActivity.onCreate(GridViewActivity.java:49)

 at android.app.Activity.performCreate(Activity.java:6038)
 at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1116) 
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:809)

**Comment by beeender** [comment]
Close due to unclear question

**Comment by jcj52436999** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  jcjacksonengineering@gmail.com
    Domain joe-jackson.net has exceeded the max emails per hour (106/100 (106%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext6.iad.github.net ([192.30.252.197]:60891 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by rs5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1aflj4-001fcG-33
	for jcjackson@joe-jackson.net; Tue, 15 Mar 2016 05:57:18 -0400
Date: Sun, 13 Mar 2016 19:21:27 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1457922087;
	bh=7qfyjecMq9Rs5VfWMRhQu3gb0eV/wDaUEjbXjSgmGts=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=qzynj8ryRXHaqxuIsS3QDLNqFapBWJBrfbgpBTq/DSfMMU0nE1Saw0aVD1SBA8CVo
	 kaIlCCEPGgK1y49NfRGcIyVaKKnBK+M0GtylYgUxmr8l4z/wNl42KE52ldSOZaMus9
	 Y748h9nDFU2hoRJkxfWBr9c4EkK3Wrjc53AgK8Yg=
