### ISSUE TITLE
ViewPager for Screen Slide using Realm Result

### ISSUE THREAD

**Issue by kentcheung2000** [realm/realm-java#2389]
I like to use ViewPager for ScreenSlide to displays data  from realm result.   However, in my main activity, I need to extend fragmentActivity; and in my adapter , it needs to extends Fragment.

As a result, how I could extends RealmBaseAdapter so I can get the data from the RealmResult to display the strings in screen slide?

Many Thanks.

**Comment by beeender** [comment]
Please spend a few minutes to take a look at the source code of `RealmBaseAdapter`.
https://github.com/realm/realm-java/blob/master/realm/realm-library/src/main/java/io/realm/RealmBaseAdapter.java

It is a very simple adapter, you don't have to extends it to fit your needs. You can just use `RealmResults` as the data source for your adapter and use the convenient `RealmChangeListener` to trigger the adapter updates.

Let us know if you have more detailed questions to this. thanks! :)

**Comment by kentcheung2000** [comment]
I am trying to pass the students object and the selected student position to the screen slide activity.

My question is can I pass my student list and the student position and use in the view pager  activity?  Thanks.


The following is my models:

public class School extends RealmObject {

    @Required
    private String SchoolID;
    private String SchoolName;
    private String SchoolChineseName;
    private RealmList<Student> Students;

getters/setters...

}

public class Student extends RealmObject {

    @Required
    private String StudentID;
    private String StudentName;
    private String StudentChineseName;
    private Boolean StudentFavourite;

}

The following is my Screen Slide Activity:

public class ScreenSlideActivity extends FragmentActivity {

    Realm realm;
    private static final int NUM_PAGES = //Student object size;
    private ViewPager mPager;
    PagerAdapter mPagerAdapter;


    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_screen_slide);

        realm = Realm.getDefaultInstance();

    }

    @Override
    public void onResume() {

        super.onResume();

        Bundle extras = getIntent().getExtras();

        if (extras != null) {
            String cStudentID = extras.getString("chosenStudentID");
            
            //The selected student position
            Integer cStudentPosition = extras.getInt("positionStudent");

            // The student object with the list of student in its school
            Student cStudents = realm.where(Student.class).equalTo("StudentID", cStudentID).findFirst();

            mPager = (ViewPager) findViewById(R.id.pager);
            mPagerAdapter = new ScreenSlidePagerAdapter(getSupportFragmentManager(), cStudents, cStudentPosition);
            mPager.setAdapter(mPagerAdapter);

        }

    }

    @Override
    public void onBackPressed() {
        if (mPager.getCurrentItem() == 0) {

            super.onBackPressed();
        } else {
            // Otherwise, select the previous step.
            mPager.setCurrentItem(mPager.getCurrentItem() - 1);
        }
    }

    private class ScreenSlidePagerAdapter <T extends RealmObject> extends FragmentStatePagerAdapter {

           // The following RealmResult<T> is giving me an error.
           private  RealmResult<T> realmResult;
        public ScreenSlidePagerAdapter(FragmentManager fm, Student cStudents, Integer cStudentPosition) {
            super(fm);
        }

        @Override
        public Fragment getItem(int position) {
            return new ScreenSlidePageFragment();
        }

        @Override
        public int getCount() {
            return NUM_PAGES;
        }
    }

}

The following is my Screen Slide Fragment:

**Comment by beeender** [comment]
Check this doc to see how to pass `RealmObject` through intent.
https://realm.io/docs/java/latest/#intents

**Comment by kentcheung2000** [comment]
Thank you for your reply.   I have one more question.  For my adapters, they all need to extends RealmBaseAdapter<Student>, for my screen slide activity, it already needs to  extend FragmentStatePagerAdapter.

In the code I showed you, it tried to use <T extends RealmObject>, but it is giving me error. Is there anything I have done wrong?  Thanks.

KC

**Comment by beeender** [comment]
What error does it give you?

> And and after I get the realm result from intent, how can I use it dynamically and use it as fragment. 
You don't get `RealmResults` from intent, we suggest you to pass a primary key through the intent. And when receive it in the fragment, get a new Realm instance in the fragment, query by the primary key to get a object instance in the fragment.

**Comment by beeender** [comment]
@kentcheung2000 Did you manage to solve this problem? Can we close this issue now?

**Comment by kentcheung2000** [comment]
I run into other problem.   You can close it for now.  Thanks.

**Comment by jcj52436999** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  jcjacksonengineering@gmail.com
    Domain joe-jackson.net has exceeded the max emails per hour (111/100 (111%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext6.iad.github.net ([192.30.252.197]:33905 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by rs5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1afljF-001fgz-A7
	for jcjackson@joe-jackson.net; Tue, 15 Mar 2016 05:57:29 -0400
Date: Sun, 13 Mar 2016 19:22:08 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1457922128;
	bh=f7ByWl8EqhABpgfULKSCpNzYBWAmnQeByL2QoMP6XYo=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=KOXZDfGjLsnFXk4Gycyu9Ah3aVU/vOW0AYCn3OwnM7ZtjIU1e1yc0DV/IuBgl9k+Y
	 gyXx87fUFZU+WoVxm/wyeeYe99DppMkD32/7gChGanH90ShYY1d9HMnMxWic9AqErL
	 yirWsWS6boLeBQCtcEcf4S8M303vUh7h2no0I7+I=
