### ISSUE TITLE
Updating bulk child relation duplicates RealmList records

### ISSUE THREAD

**Issue by huibvv** [realm/realm-java#2393]
## Goal :
Adding and/or updating the records of a relation

## Expected Results
Updated records within the child RealmList

## Actual Results (e.g. full stack trace with exception)
While the record are being updated correctly (Within the Realm, all records only exist once), the child RealmList contains duplicate records. The records are simply being added, instead of being updated.

### Code Sample

Realm object
```java
public class AlarmObject extends RealmObject {
 private RealmList<LogLine> LogLines;

public RealmList<LogLine> getLogLines() {
        return LogLines;
    }

    public void setLogLines(RealmList<LogLine> logLines) {
        LogLines = logLines;
    }
}
```
Child object
```java
public class LogLine extends RealmObject {
    @PrimaryKey
    private long Id;
    private String LogText;

public long getId() {
        return Id;
    }

    public void setId(long id) {
        Id = id;
    }

    public String getLogText() {
        return LogText;
    }

    public void setLogText(String logText) {
        LogText = logText;
    }
}
```
Update logic
```java
 Realm realm = Realm.getDefaultInstance();
        realm.beginTransaction();

        List<LogLine> loglines = realm.copyToRealmOrUpdate(response);
        AlarmObject object = Authenticator.getCurrentClientObject(realm, getBaseContext());

        //object.getLogLines().clear();
        object.getLogLines().addAll(response);
        realm.commitTransaction();
        realm.close();
```
Example Json object

{
    "Id": "123456",
    "LogText": "Test text",
  }

## Version of Realm and tooling
Realm version(s): 0.87.5

Android Studio version: 1.5.1

Android version(s) on device/simulator: API 21

**Comment by cmelchior** [comment]
The reason you are seeing duplicated objects is because RealmList just works like a normal List (which can contain duplicates).

In your code:

```
 Realm realm = Realm.getDefaultInstance();
realm.beginTransaction();

// This will correctly create or update any existing LogLine objects
List<LogLine> loglines = realm.copyToRealmOrUpdate(response);
AlarmObject object = Authenticator.getCurrentClientObject(realm, getBaseContext());

// This will just add all items to the end of the list, potentially duplicating them in the List
object.getLogLines().addAll(response); 

// This leaves you with two options:
// 1) If you didn't create any new objects, you don't have to do anything. `object` is now automatically up to date.
// 2) You need to replace the list because new items where added:
object.getLogLines().clear(); // clear the old list
object.getLogLines().addAll(response); // add the new list

realm.commitTransaction();
realm.close();
```

**Comment by huibvv** [comment]
Thank you for the quick response. I was in the understanding that clearing a RealmList is the same as removing the records from the realm (as the documentation suggests). 

```JAVA
// obtain the results of a query
RealmResults<Dog> results = realm.where(Dog.class).findAll();

// All changes to data must happen in a transaction
realm.beginTransaction();

// remove single match
results.remove(0);
results.removeLast();

// remove a single object
Dog dog = results.get(5);
dog.removeFromRealm();

// Delete all matches
results.clear();

realm.commitTransaction()
```

**Comment by cmelchior** [comment]
Hi @huibvv 
Right now RealmResults and RealmList have different behaviors in that regard. `RealmList.clear()` just removes it from the list, but not the Realm. `RealmResults.clear()` will delete them from the Realm as well. It is confusing as you point out, so we are also in the process of making it more consistent here: #2345

**Comment by Zhuinden** [comment]
@HayTran94 if you don't want duplicate objects then use a `@PrimaryKey` that is unique to the object instance that you are identifying

Just like in SQLite
