### ISSUE TITLE
Nested objects without PrimaryKey - contained references

### ISSUE THREAD

**Issue by baloghz** [realm/realm-java#2396]
Hi,

lets have the following simplified data model:
``` java
public class User {
    @PrimaryKey
    private int id;
    private Location location;  // Contained
    private User friend;        // Non-contained
    //...
}

public class Location {
    private double lon;
    private double lat;
    //...
}
```
I want to update a ```User``` object using ```createOrUpdateObjectFromJson(User.class, userJson)``` method. For example with the following json:
``` json
{
  "id": "1",
  "location": {
    "lon": 0,
    "lat": 0
  },
  "friend":{
    "id": "2"
  }
}
```

My problem is that every time I tried to update a user, an additional ```Location``` object will be created.

In the ```User``` there are two types of references:
 - _Contained_: The referenced object has meaning only inside the user object. Therefore for example ```RealmQuery<Location> queryLoctaions = realm.where(Location.class)``` may return with empty array. We're not interested in these objects only within some context.
 - _Non-Contained_: The referenced object is standalone object, lives independently.

Do you have any future plans to support these kind of _Contained_ references? For example with an annotation ```@Contained```.

Can you give me some workaround to handle these cases with the current realm implementation (0.87.5)?

Similar issue:
http://stackoverflow.com/questions/30258351/android-realm-copytorealmorupdate-creates-duplicates-of-nested-objects

**Comment by cmelchior** [comment]
Hi @baloghz 
Yes, it is on our roadmap. The concept you are looking for is called Cascading deletes: https://github.com/realm/realm-java/pull/2386

**Comment by baloghz** [comment]
Hi @cmelchior,

thanks for the advise and it's good to hear that this feature is in your roadmap (I missed that issue).
Keep up the good work!

**Comment by cmelchior** [comment]
Thanks. Good luck with the project.

**Comment by baloghz** [comment]
Hi @cmelchior,

I've found another problem with the above case.

Let's have the same data model again:
``` java
public class User {
    @PrimaryKey
    private int id;
    private Location location;  // Contained
    private User friend;        // Non-contained
    //...
}

public class Location {
    private Double lon;
    private Double lat;
    //...
}
```

and again let's create a ```User``` object using ```createOrUpdateObjectFromJson(User.class, userJson)``` method with the following json:
``` json
{
  "id": "1",
  "location": {
    "lon": 10,
    "lat": 10
  },
  "friend":{
    "id": "2"
  }
}
```

After that let's update only the longitude of the location using again ```createOrUpdateObjectFromJson(User.class, userJson)``` method with the following json:
``` json
{
  "id": "1",
  "location": {
    "lon": 100
  }
}
```

I would expect the user model after the update:
``` json
{
  "id": "1",
  "location": {
    "lon": 100,
    "lat": 10
  },
  "friend":{
    "id": "2"
  }
}
```

but unfortunately the new user is:
``` json
{
  "id": "1",
  "location": {
    "lon": 100
  },
  "friend":{
    "id": "2"
  }
}
```

The latitude is missing. I assume it's because the update logic doesn't get the actual location of the user, but simply createOrUpdate the location in separate way and then set to the user. Again if the location would have an id, it would not happen.

Will the above mentioned cascade delete (and related stuff) solve this issue as well? If not, do you have something else on the roadmap related to this?

P.s.: I've tried to set an ```id``` for the location in ```user.setLocation()``` to ```<user.id>_location``` (it could be a more generic solution as well).  It works if I'am the one who creates the Location object and call ```user.setLocation```, but doesn't work if I use ```createOrUpdateObjectFromJson(User.class, userJson)``` for example. It that case the user.setLocation simply won't be called.

To put the id into the location explicitly is also not an option as it is come from a webservice.
