### ISSUE TITLE
ChangeListener called after removeChangeListener

### ISSUE THREAD

**Issue by huibvv** [realm/realm-java#2401]
## Goal (what do you want to achieve?)
Notify on change

## Expected Results

Not being notified when removing the listener

## Actual Results (e.g. full stack trace with exception)

Notification fires after the listener has been removed

## Steps & Code to Reproduce (Or describe your current debugging efforts)

The activity containing the views depends on multiple records. I want these views to be updated in real time, so i've put a listener to the child list. After removing the listener (and after the activity has been destroyed), the listener is still being called.

```java

 @Override
    public void onPause() {
        if(mHardware != null){
            mHardware.getValues().where().findAll().removeChangeListener(mListener);
        }
        super.onPause();
    }

    @Override
    public void onResume() {
        redraw();
        if(mHardware != null){
            mHardware.getValues().where().findAll().addChangeListener(mListener);
        }
        super.onResume();
    }

    private RealmChangeListener mListener = new RealmChangeListener() {
        @Override
        public void onChange() {
            redraw();
        }
    };

    @Override
    public void onDestroyView() {
        super.onDestroyView();
        mRealm.close();
    }

```

## Version of Realm and tooling
Realm version(s): 0.87.5

Android Studio version: 1.5.1

Android version(s) on device/simulator: 21

**Comment by beeender** [comment]
```java
mHardware.getValues().where().findAll().removeChangeListener(mListener);
```

this line equals to 

```java
RealmResults newResults = mHardware.getValues().where().findAll();
newResults.removeChangbeListener(mListener);
```

It creates a new `RealmResults` which is different from the one created in `onResume`, and remove the listener on that one, because of there is no listener registered on it, `removeChangeListener` just does nothing.

To fix this: 

```java
private RealmResults results;

@Override
public void onResume() {
    redraw();
    if(mHardware != null) {
        // You might also want to check if the results is null here, no need to rebuild a Results if it exists.
        results = mHardware.getValues().where().findAll();
        results.addChangeListener(mListener);
    }
    super.onResume();
}

@Override
public void onPause() {
    if(mHardware != null){
        results.removeChangeListener(mListener);
    }
    super.onPause();
}
```

**Comment by jjhesk** [comment]
what do i need to do in the adapter? 
I got 
`mutable call during read transaction io.realm adapter` on the recyclerview when it removes the item from the list.

**Comment by jjhesk** [comment]
finally this is my solution
```java

public final void removeInternalRealmSupport(int position) {
        if (hasHeaderView() && position == 0) return;
        if (enableLoadMore() && position == getItemCount() - 1) return;
        if (source.size() > 0) {
            synchronized (mLock) {
                Realm realm = Realm.getInstance(RealmUtil.realmCfg(ctm));
                realm.beginTransaction();
                source.remove(hasHeaderView() ? position - 1 : position);
                realm.commitTransaction();
            }
            notifyItemRemoved(position);
        }
    }

```

add this above code in the adapter to get all the remove issue resolve.

**Comment by beeender** [comment]
You can just use `Realm realm = source.getRealm()` to get the Realm instance which is used to create the RealmResults.

**Comment by beeender** [comment]
Please just ignored what i said above. `RealmResults.getRealm()` will return a `BaseRealm` which is not public, and cannot be used outside. What you did in https://github.com/realm/realm-java/issues/2401#issuecomment-194147697 is OK.

**Comment by jjhesk** [comment]
I have tried `getRealm` and it did not get the thing because it was private or protected.

**Comment by jjhesk** [comment]
@beeender  i think it is still not the perfect solution as i have recall the realm from the initiation. Are there any options that i can call directly from the `source` object and get the instance of the Realm?

**Comment by cmelchior** [comment]
@jjhesk Why not just add the Realm instance as an extra parameter in the constructor?

**Comment by beeender** [comment]
@huibvv @jjhesk I hope your issues have been solved. I am closing this now, feel free to reopen it if needed.
