### ISSUE TITLE
ArrayIndexOutOfBoundsException: rowIndex is less than 0

### ISSUE THREAD

**Issue by Sutirth** [realm/realm-java#2408]
## Goal (what do you want to achieve?)

I am changing status of a field in realm table continuously  

## Expected Results

The status should change in the database

## Actual Results (e.g. full stack trace with exception)

```
03-10 17:27:50.122 28586-28586/com.workoutguru.workoutcash E/AndroidRuntime: FATAL EXCEPTION: main
03-10 17:27:50.122 28586-28586/com.workoutguru.workoutcash E/AndroidRuntime: Process: com.workoutguru.workoutcash, PID: 28586
03-10 17:27:50.122 28586-28586/com.workoutguru.workoutcash E/AndroidRuntime: java.lang.ArrayIndexOutOfBoundsException: rowIndex is less than 0.
03-10 17:27:50.122 28586-28586/com.workoutguru.workoutcash E/AndroidRuntime:     at io.realm.internal.TableView.nativeGetSourceRowIndex(Native Method)
03-10 17:27:50.122 28586-28586/com.workoutguru.workoutcash E/AndroidRuntime:     at io.realm.internal.TableView.getSourceRowIndex(TableView.java:158)
03-10 17:27:50.122 28586-28586/com.workoutguru.workoutcash E/AndroidRuntime:     at io.realm.RealmResults.get(RealmResults.java:174)
03-10 17:27:50.122 28586-28586/com.workoutguru.workoutcash E/AndroidRuntime:     at com.workoutguru.workoutcash.CompanyGoals_AllGoals_Fragment$CompanyAllGoalsAdapter$CompanyAllGoalsAdapterViewHolder$1$1.onResponse(CompanyGoals_AllGoals_Fragment.java:668)
03-10 17:27:50.122 28586-28586/com.workoutguru.workoutcash E/AndroidRuntime:     at retrofit.ExecutorCallAdapterFactory$ExecutorCallback$1.run(ExecutorCallAdapterFactory.java:86)
03-10 17:27:50.122 28586-28586/com.workoutguru.workoutcash E/AndroidRuntime:     at android.os.Handler.handleCallback(Handler.java:739)
03-10 17:27:50.122 28586-28586/com.workoutguru.workoutcash E/AndroidRuntime:     at android.os.Handler.dispatchMessage(Handler.java:95)
03-10 17:27:50.122 28586-28586/com.workoutguru.workoutcash E/AndroidRuntime:     at android.os.Looper.loop(Looper.java:135)
03-10 17:27:50.122 28586-28586/com.workoutguru.workoutcash E/AndroidRuntime:     at android.app.ActivityThread.main(ActivityThread.java:5343)
03-10 17:27:50.122 28586-28586/com.workoutguru.workoutcash E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Native Method)
03-10 17:27:50.122 28586-28586/com.workoutguru.workoutcash E/AndroidRuntime:     at java.lang.reflect.Method.invoke(Method.java:372)
03-10 17:27:50.122 28586-28586/com.workoutguru.workoutcash E/AndroidRuntime:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:905)
03-10 17:27:50.122 28586-28586/com.workoutguru.workoutcash E/AndroidRuntime:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:700)
```

## Version of Realm and tooling
Realm version(s): compile 'io.realm:realm-android:0.87.5'

Android Studio version:  android 1.4

Android version(s) on device/simulator: Device version 5.1,API:22

**Comment by kneth** [comment]
It looks like you are trying to change the value of a non-existing object. The object you are changing is found in a `RealmResults`, right?  Do you execute the query (`findAll()`) outside the transaction? Is your Realm updated in another thread?

**Comment by Sutirth** [comment]
I am executing query findfirst() in async transaction and calling notifyDataSetChanged in recyclerView

**Comment by jjhesk** [comment]
+1

**Comment by beeender** [comment]
@Sutirth Can you set a breakpoint at `CompanyGoals_AllGoals_Fragment.java:668` to see what is the index when crash happens?

**Comment by Sutirth** [comment]
@beeender  It happens sometime or the other not a frequent breakdown. Though I have debugged this issue for long hours and after doing everything it crashes here 
AllGoalsDB unsubscribeGoalResult = realm.where(AllGoalsDB.class)
                                            .equalTo(WorkoutCashConstants.COLUMN_GOALID, allGoalsResults.get(getAdapterPosition()).getGoalID())
                                            .findFirst();

So I have made few observation and this would be according to my theory please correct me if I am wrong. Suppose I say a user is on 2g network and for example he click subscribe(This is the time when I hit my api call and onSuccess I change the status in my realm database). And suppose there is a brief lag period and I click on subscribe again it crashes  because its status is already changed in the database and hence I get row Index as 0. 

Would request you to keep this issue open Because I am debugging this issue continuously

P.S I live in India and hence we do a rigorous testing on spectrum.

**Comment by beeender** [comment]
The changes in another thread will reflect to the current thread's Realm instance in the "next" event loop. So if you are tracking soma Realm data status, like the `RealmResults`'s size by your own var, it is very important to refresh them when Realm changes. The suggestion is make your data in each thread's data stateless, whatever the data changes, just read the Realm, get the latest data.

**Comment by Sutirth** [comment]
@beeender  Exactly I am doing the same thing say for e.g if I am doing some changes in Recycler view I notify the adapter when its successful but this still I am end getting error.

**Comment by jcj52436999** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  jcjacksonengineering@gmail.com
    Domain joe-jackson.net has exceeded the max emails per hour (105/100 (105%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext1.iad.github.net ([192.30.252.192]:33757 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by rs5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1aflgV-001eOS-2C
	for jcjackson@joe-jackson.net; Tue, 15 Mar 2016 05:54:39 -0400
Date: Tue, 15 Mar 2016 01:35:21 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1458030922;
	bh=sAwDGuX908kUPsYgxQRKfIk4BAkAHRYjFrwNJQGsCXg=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=ML9SEOnA/8Y8+9kl4c9KdfOsXuJC0ui1QhSFUOxvE9exnqhfk6PJnzVyn1P2bUY7k
	 0CquBlg0SY5oz4VPkitN4huf2lmHML2m44n7SEgUJ1GbuvHQGXVFnngU81Ne5/odQh
	 3RqfPP8jj8BHYvVkl27odMxCvRO2YE8aFgr3LyRM=

**Comment by jcj52436999** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  jcjacksonengineering@gmail.com
    Domain joe-jackson.net has exceeded the max emails per hour (119/100 (119%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:54208 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by rs5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1afmNf-001xyx-5M
	for jcjackson@joe-jackson.net; Tue, 15 Mar 2016 06:39:15 -0400
Date: Tue, 15 Mar 2016 01:12:07 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1458029527;
	bh=UnvM7IFCn2BCCOruFbpOplBcbYO4IB7ieNxYpNzT1Fw=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=2CV8ZcQWKXTU7Ls8bT5SAKOrws8pb06gDd/St5N/QkqCU8JWeQyFzIqmm09NWUWI2
	 7typFj0q6mHg632I5BVaxzRPfsKq3cjEebHkFDQX/Uye3L6YftxiwIRS7xEVFQ2pqO
	 VSQ2OQiAuz+dSTaPWTTNy7p628BmbE9jQhjUkYwk=

**Comment by dalinaum** [comment]
This issue is reported by VCNC too. See its CrashLytics too: http://crashes.to/s/957c6014d94

**Comment by Sutirth** [comment]
@beeender  Closed Already without solution?? :(

**Comment by beeender** [comment]
Oppos, I thought this is solved. Since we cannot reproduce this from our side can you please reproduce this issue will a minimal Android Studio project and share with us so we can do some investigation on it? to help@realm.io
Thanks!

**Comment by atouchsimo** [comment]
has the same issue occurred some times, when the the adapter being updated and the user click before or while the adapter is being updated, 
i use the following solution when the user clicks on an item
```java
try {
     list.get(getAdapterPosition());
} catch (Exception ignored) {
     return;
}
```

**Comment by KynoYang** [comment]
I have the  same issue, but it may be because I remove data from Realm in another thread. Do all the transactions in the same thread is not possible for me. Any suggestion?

**Comment by beeender** [comment]
@KynoYang Can you share some related code with us? to help@realm.io if you want to share it privately.

**Comment by KynoYang** [comment]
Sure. I'll try to make a demo to reproduce it.

**Comment by beeender** [comment]
@KynoYang A demo project to reproduce it would be the best!!! Thanks a lot!

**Comment by KynoYang** [comment]
@beeender Unfortunately, I failed to reproduce it in the demo. It seems no relation with multiple threads. But I indeed received several crash reports from users. I'll add some log in my app to figure out what's the problem. BTW, one of my users sent me a video about this bug. I guess it's because the change listener in RealmExpandableListAdapter (not sure RealmBaseAdapter has the same problem) doesn't work at that time in some unknown reason.

**Comment by beeender** [comment]
Reopen this issue. I am checking with @KynoYang about this.

**Comment by cmelchior** [comment]
@beeender Did you have a chance to look into this?

**Comment by beeender** [comment]
Yes, but we have no luck to reproduce it :(

**Comment by beeender** [comment]
#2753 is reporting the similar issue, i will try to reproduce it with clues from there.

**Comment by b12kab** [comment]
I have this particular issue now. I've seen this was solved earlier this month. The build number doesn’t seem to have increased release wise (1.1.0).

I’ve got to get the current build with the fix so I can move on. Are there instructions on how to pull down the source https://github.com/realm/realm-java and build it locally? If so, could someone point me to how to do this and then incorporate it into my project from the local build?

**Comment by kneth** [comment]
@Mohsin92 can you provide a bit of background info (Realm version, etc.) and context (when do you see exception, Realm configuration, etc.).

**Comment by Zhuinden** [comment]
@Mohsin92 execute your query inside the Realm transaction

**Comment by Mohsin92** [comment]
@kneth : Realm 2.3.0 
Context:
When I tried to update in database its shows me errors.

` try { // I could use try-with-resources here
                        realm = Realm.getDefaultInstance();
                        realm.executeTransaction(new Realm.Transaction() {
                            @Override
                            public void execute(Realm realm) {

                                RealmResults<Favourite_List_DB> favourite_list_dbs = realm.where(Favourite_List_DB.class).findAll();
                                if (favourite_list_dbs.size() < 1) {
                                    Log.e("Databae is empty: ", "Empty DB");
                                } else {
                                    Log.e("DB List Before size: ", String.valueOf(favourite_list_dbs.size()));
                                    for (int i = 0; i < favourite_listing_subs.size(); i++) {
                                        for (int j = 0; j < favourite_listing_subs.get(i).getResult().getListing().size(); j++) {
                                            if (favourite_listing_subs.get(i).getResult().getListing().get(j).getListingKey().equalsIgnoreCase(favourite_list_dbs.get(i).getListing_key())) {
                                                if (!favourite_listing_subs.get(i).getResult().getListing().isManaged()) {
                                                    for (Favourite_listing_sub favourite_list_db : favourite_listing_subs) {
                                                        if (favourite_list_db.getResult().getListing().isManaged()) {
                                                            managedImageList.add(favourite_list_db);
                                                            Log.e("Favourite: ", "Now it manage.");
                                                        } else {
                                                            managedImageList.add(realm.copyToRealm(favourite_list_db));
                                                        }
                                                    }
                                                    //  favourite_listing_subs.addAll(managedImageList);
                                                    favourite_list_dbs.get(j).setListing(managedImageList.get(i).getResult().getListing().get(j));
                                                    favourite_list_dbs.get(j).setListing_key(managedImageList.get(i).getResult().getListing().get(j).getListingKey());
                                                    favourite_list_dbs.get(j).setUpdate_date(retdate());
                                                    favourite_list_dbs.get(j).setCreate_date(retdate());
                                                    realm.copyToRealmOrUpdate(favourite_list_dbs);
                                                    Log.e("DB List after size: ", String.valueOf(favourite_list_dbs.size()));
                                                } else {
                                                    favourite_list_dbs.get(j).setListing(managedImageList.get(i).getResult().getListing().get(j));
                                                    favourite_list_dbs.get(j).setListing_key(managedImageList.get(i).getResult().getListing().get(j).getListingKey());
                                                    favourite_list_dbs.get(j).setUpdate_date(retdate());
                                                    favourite_list_dbs.get(j).setCreate_date(retdate());
                                                    realm.copyToRealmOrUpdate(favourite_list_dbs);
                                                }
                                            } else {
                                                if (!favourite_listing_subs.get(i).getResult().getListing().isManaged()) {
                                                    for (Favourite_listing_sub favourite_list_db : favourite_listing_subs) {
                                                        if (favourite_list_db.getResult().getListing().isManaged()) {
                                                            managedImageList.add(favourite_list_db);
                                                            Log.e("Favourite: ", "Now it manage.");
                                                        } else {
                                                            managedImageList.add(realm.copyToRealm(favourite_list_db));
                                                        }
                                                    }
                                                    //   favourite_listing_subs.addAll(managedImageList);
                                                    //  favourite_listing_subs.addAll(managedImageList);

                                                    favourite_list_dbs.get(j).setListing(managedImageList.get(j).getResult().getListing().get(j));
                                                    // favourite_list_dbs.get(i).setListing_key(managedImageList.get(j).getResult().getListing().get(j).getListingKey());
                                                    favourite_list_dbs.get(j).setUpdate_date(retdate());
                                                    favourite_list_dbs.get(j).setCreate_date(retdate());
                                                    realm.insert(favourite_list_dbs);
                                                    Log.e("DB List after size: ", String.valueOf(favourite_list_dbs.size()));
                                                } else {
                                                    favourite_list_dbs.get(j).setListing(managedImageList.get(j).getResult().getListing().get(j));
                                                    //  favourite_list_dbs.get(j).setListing_key(managedImageList.get(j).getResult().getListing().get(j).getListingKey());
                                                    favourite_list_dbs.get(j).setUpdate_date(retdate());
                                                    favourite_list_dbs.get(j).setCreate_date(retdate());
                                                    realm.insert(favourite_list_dbs);
                                                }
                                            }
                                        }
                                    }
                                    realm.insertOrUpdate(favourite_listing_subs);
                                }
                            }
                        });
                    } finally {
                        if (realm != null) {
                            realm.close();
                        }
                    }`

**Comment by Mohsin92** [comment]
@Zhuinden : yes I tried same you can find in above code.

**Comment by Zhuinden** [comment]
@Mohsin92 

`for (int j = 0; j < favourite_listing_subs.get(i).getResult().getListing().size(); j++) {`

apparently `favourite_listing_subs.get(i).getResult().getListing().size()` != `favourite_list_dbs.size()`
