### ISSUE TITLE
0.88.0 download doesn't contain library

### ISSUE THREAD

**Issue by kassim** [realm/realm-java#2411]
The download here just has examples and documentation - no libs
https://static.realm.io/downloads/java/realm-java-0.88.0.zip

**Comment by cmelchior** [comment]
Hi @kassim 
From 0.88.0 We no longer ship a JAR file as described here: https://realm.io/news/android-installation-change/

**Comment by kassim** [comment]
Oh right. I just read the build message that a new version was available and provided the link.
I've seen its still on the Java Docs page https://realm.io/docs/java/latest/ on the "Download Realm for Android" button. 

Thanks for the help.
