### ISSUE TITLE
std::exception in io_realm_internal_TableQuery.cpp line 1682 when calling RealmResults.load() with multiple Realm instances

### ISSUE THREAD

**Issue by dmarcato** [realm/realm-java#2417]
#### Steps to reproduce

- Obtain an instance of `Realm`
- Execute an async transaction on it
- Obtain a second instance of `Realm` with same configuration and on the same thread (it will return the same instance as the first `Realm`)
- Execute an async query
- Call `load()` to synchronously wait for the query to execute 

#### Issue

The `load()` method throws a native exception: `std::exception in io_realm_internal_TableQuery.cpp line 1682`. this exception is swallowed on the Java side, but I managed to debug it and I discovered it's actually a `BadVersionException`.
After some investigation I think the issue is in the invocation of `Realm.getInstance()` after submitting the first transaction. If that happens before (or if I reuse the same `Realm` variable) everything works correctly.
I already discussed with @cmelchior on Slack about the issue.

#### Code Sample
(in Kotlin :stuck_out_tongue: )
```kotlin
val realm = Realm.getInstance(realmConfiguration)
realm.executeTransactionAsync {
    it.deleteAll()
}
val realm2 = Realm.getInstance(realmConfiguration)
realm2.where(RealmDocument::class.java).findAllAsync().load()
```

#### Version of Realm and tooling
Realm version(s): 0.88.0

Android Studio version: 2.0

Which Android version and device: Emulator with 6.0

**Comment by dmarcato** [comment]
Yes, the test run as `@UiThreadTest` and it's the only one in the class.

I played around with your Java version and I found something really funny: you are right, your test pass, but if you modify it like the following it will fail :confused:

```java
    @Test
    @UiThreadTest
    public void badVersion() {
        RealmConfiguration config = configFactory.createConfiguration();
        Realm realm = Realm.getInstance(config);
        realm.executeTransactionAsync(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {
                realm.deleteAll();
            }
        });
        Realm realm2 = Realm.getInstance(config);
        boolean result = realm2.where(AllTypes.class).findAllAsync().load()
        assertTrue(result);
        realm.close();
        realm2.close();
    }
```

Something really weird is going on here... :no_mouth:

**Comment by cmelchior** [comment]
It still doesn't fail for me. What exact hardware and device/emulator are you testing on?

**Comment by dmarcato** [comment]
I'm using a MacBook Pro with OS X 10.11.3 - the test run in a emulated Nexus 5X with Android 6.0.

Can you try change your `RealmConfiguration` into something like this:
```java
RealmConfiguration config = new RealmConfiguration.Builder(InstrumentationRegistry.getContext()).deleteRealmIfMigrationNeeded().build();
```
It seems like by using your `TestRealmConfigurationFactory` the problem doesn't show up, instead the combination of creating a `RealmConfiguration` from a `Context` and setting `deleteRealmIfMigrationNeeded()` somehow triggers it :confused:

**Comment by cmelchior** [comment]
Thank you. I can reproduce it on a 5X ARM emulator running API 23.

My unit test needs the below to fail though, but it just confirms my suspicion it is timing related:
```
    @Test
    @UiThreadTest
    public void badVersion() {
        RealmConfiguration config = new RealmConfiguration.Builder(InstrumentationRegistry.getContext()).deleteRealmIfMigrationNeeded().build();
        Realm realm = Realm.getInstance(config);
        realm.executeTransactionAsync(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {
                realm.deleteAll();
            }
        });
        realm.executeTransactionAsync(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {
                realm.deleteAll();
            }
        });
        realm.executeTransactionAsync(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {
                realm.deleteAll();
            }
        });
        Realm realm2 = Realm.getInstance(config);
        boolean result = realm2.where(AllTypes.class).findAllAsync().load();
        assertTrue(result);
        realm.close();
        realm2.close();
    }
```

**Comment by dmarcato** [comment]
Funny that it doesn't fail for me... Oh well, glad you are able to reproduce it :smile:

**Comment by cmelchior** [comment]
@dmarcato 0.88.2 has been released with a fix for this.

**Comment by dmarcato** [comment]
@cmelchior great, thanks! I just re-run my test and they seems to be working correctly! :smile:
