### ISSUE TITLE
Does Realm support manually migration after MigrationException throwed

### ISSUE THREAD

**Issue by avenwu** [realm/realm-java#2418]
#### Goal

> What do you want to achieve?
I would like to deal with MigrationException manually,not just delete the old default.realm db 

#### Expected Results

```
try{
    Realm.getInstance()
} catch(MigrationException e) {
    //step 1. read realm file manually
    //step 2. extract necessary information in the existing old db
    //step 3. delete the old db file
    //step 4. create new db and set the information we've got from step 2;
}
```
#### Actual Results
Currently I can only delete the realm file when MigrationException throwed which means any user sensitive information in the dirty db will be lost;

**Comment by beeender** [comment]
Actually you can do those things you listed in the catch block.
But before that, I suggest you to take a look of our migration examples https://github.com/realm/realm-java/tree/master/examples/migrationExample
Especially https://github.com/realm/realm-java/blob/master/examples/migrationExample/src/main/java/io/realm/examples/realmmigrationexample/model/Migration.java#L60 . It shows how to convert two fields in the old objects in one.
I do believe the migration API should full fill your requirement, but it if doesn't please let us know.

The more free way is you can use our dynamic APIs, it gives you opportunity to open the Realm without checking schema and defining any Object. See https://realm.io/docs/java/latest/api/io/realm/DynamicRealm.html

**Comment by avenwu** [comment]
@beeender Thanks so much!
We integrated Ream since 0.7x and has upgraded it for once to 0.81.1. This version does not contain the  DynamicRealm class, so in which release was DynamicRealm included?

I've double check the Migration example, the standard migration should suit for nearly all normal cases, but for my situation I'd like handle the unexpected exception which may be introduced by developer not deal with migration properly.

And we did get several migration exception while shipping new release.  The best way would be focus on the the standard migration but not rely on it only.

As your suggestion mentioned, I think the DynamicRealm may provide developer new access to the db file;
```
try{
    Realm.getInstance()
} catch(MigrationException e) {
    //step 1. read realm file manually
    DynamicRealm.getInstance(RealmConfiguration configuration);
    //step 2. extract necessary information in the existing old db
    //step 3. delete the old db file
    //step 4. create new db and set the information we've got from step 2;
}
```
Can I use DynamicRealm.getInstance when MigrationException throwed?
If not, can you show me any relative docs?
Thanks again @beeender

**Comment by beeender** [comment]
Always suggest you to use the latest version, `0.88.0` is current latest version. But if you are not comfortable with the build system changes, you can use `0.87.5`. Be noticed that we won't update the `0.87.5` any more. 

> Can I use DynamicRealm.getInstance when MigrationException throwed?
Yes, you can. But i don't suggest you to do that since the `Migration` block should take care of it.

Why do you want to do `step 2` in the catch block? Cannot you do that in `Migration` like described here https://github.com/realm/realm-java/blob/master/examples/migrationExample/src/main/java/io/realm/examples/realmmigrationexample/model/Migration.java#L60 ?

**Comment by avenwu** [comment]
The reason why I was trying to do step2:

    We don't want our users to lost the stored information, such as user profile, in-app data

So I need take care of any potential risks to roll back the db;  We are doing stuff in the Migration, but with sanity check is better

**Comment by beeender** [comment]
If you just need some kind of backup, you could just copy the Realm file before open it i think? Which is much easier to do. use `RealmConfiguration.getPath()` to get the path then copy the file by normal java file API maybe?

**Comment by avenwu** [comment]
Will try later:)

**Comment by jjhesk** [comment]
i got this message when i use the [instruction](https://realm.io/news/android-installation-change/) from the mentioned above. 
`com.github.KeepSafe:ReLinker:1.1` .

**Comment by cmelchior** [comment]
Hi @jjhesk See this issue: https://github.com/realm/realm-java/issues/2415

**Comment by beeender** [comment]
@avenwu Have you solved it? Can we close this issue now?

**Comment by avenwu** [comment]
Closed, thanks for your help
