### ISSUE TITLE
Upgrade NDK

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#2423]
A new version of the NDK was released: 
We should upgrade our NDK version to r11 and move away from GCC 4.9 to Clang: http://developer.android.com/ndk/downloads/index.html

**Comment by emanuelez** [comment]
I think #2095 is a pre-requisite of this, since it would allow us to  measure the impact of the change

**Comment by cmelchior** [comment]
I agree it would be nice to be able to measure any performance regressions, but since GCC is now deprecated we have to move eventually.

**Comment by emanuelez** [comment]
If the performance loss is considerable we don't need to use the latest NDK

**Comment by cmelchior** [comment]
Well, if GCC is deprecated we have to move eventually, but you are right, we don't have to migrate _now_.

**Comment by cmelchior** [comment]
Some interesting info about the differences between GCC and Clang: https://github.com/android-ndk/ndk/issues/26#issuecomment-198067100

It definitely sounds like we need to get some metrics in place (size / performance) before switching.

**Comment by cmelchior** [comment]
Folding this into #3506
