### ISSUE TITLE
Received an error in Jni: Failure when converting long string to UTF-16

### ISSUE THREAD

**Issue by Saketme** [realm/realm-java#2429]
```java
JNI DETECTED ERROR IN APPLICATION: input is not valid Modified UTF-8: illegal continuation byte 0x2e
03-12 00:19:49.679 8033-10913/com.tattva.app A/art: art/runtime/java_vm_ext.cc:410]     string: 'Unrecoverable error. Failure when converting long string to UTF-16 error_code = 8; retcode = 0; StringData.size = 116289; StringData.data = ...
```

I've emailed the entire stacktrace to your email `(help@realm.io)`, from my email `saket@saket.me`. Could not post it here publicly since it contains data I do not wish to make public.

#### Goal

Nothing. I was debugging my app and this happened out of nowhere.

#### Steps & Code to Reproduce

No idea. Couldn't reproduce. 

#### Version of Realm and tooling
Realm version(s): 0.87

Android Studio version: 2.1

Which Android version and device: Android 5.1, Moto G3

**Comment by cmelchior** [comment]
The IntelliJ debugger is calling methods on objects in order to show their data. In particular `toString()`. It looks it was doing something like that here:

```
10913/com.tattva.sup A/art: art/runtime/runtime.cc:399]   at io.realm.internal.Table.nativeToString(Native method)
03-12 00:19:50.712 8033-10913/com.tattva.sup A/art: art/runtime/runtime.cc:399]   at io.realm.internal.Table.toString(Table.java:1313)
03-12 00:19:50.712 8033-
```
If we are somehow cutting a String in half for that toString method, it could potentially result in something invalid. At least that is my theory. We will look closer into it.

**Comment by Saketme** [comment]
Sounds like a bug I shouldn't be bothered with then. Cool, thanks!

**Comment by cmelchior** [comment]
Yes, you should never see this in app code as `Table.toString()` is not used for anything there

**Comment by beeender** [comment]
More log on helpscout: https://secure.helpscout.net/conversation/180596095/3357/?folderId=366141

**Comment by beeender** [comment]
https://github.com/realm/realm-core/issues/1831 core bug reported. If it is crashed in `Table.nativeToString()`, that is the root cause.
