### ISSUE TITLE
This Realm instance has already been closed, making it unusable.

### ISSUE THREAD

**Issue by DanteAndroid** [realm/realm-java#2430]
While I encounter this problem, and try many ways but failed to solve, so I decide not to close it. Could I not do that?
Need I close Realm when I quit app?

If you would like to solve my problem, check out [my repository](https://github.com/DanteAndroid/Knowledge), I just closed realm in `BaseActivity`, and the error appears after `MainActivity` was recreated.

Thanks!

**Comment by MGaetan89** [comment]
According to [the doc](https://realm.io/docs/java/latest/#closing-realm-instances), it is important to close your realm when you are done: 

> Realm implements Closeable in order to take care of native memory deallocation and file descriptors so it is important to remember to close your Realm instances when you are done with them.

In your `BaseActivity`, you are calling `Realm.getDefaultInstance()` twice, but closing it only once.

**Comment by DanteAndroid** [comment]
It's not about whether I close them all, problem is as soon as I close Ream, I encounter `unusable` error, I close it just in `BaseActivity's onDestroy`, it should be okay, isn't it?

**Comment by zaki50** [comment]
Hi @DanteAndroid 
Closing Realm in `Activity.onDestroy()` is very normal.

Your code is overriding `initViews()` in `SettingsActivity` but does not call `super.initViews()` in it.
So, when you start and then finish `SettingsActivity`, `Realm.close()` is called without `Realm.getInstance()`.

https://github.com/DanteAndroid/Knowledge/blob/master/app/src/main/java/com/dante/knowledge/ui/SettingsActivity.java#L14

**Comment by DanteAndroid** [comment]
@zaki50 That helps me a lot, thank you!
