### ISSUE TITLE
Realm group by date 

### ISSUE THREAD

**Issue by MahmoudAlnouno** [realm/realm-java#2437]
```
public class ChequeOutGoing{
  private date entryDate;
  private double amount;
}
```
data in this table like this

```
entryDate ...................amount
1/1/2016   *************** 50
15/1/2016 *************** 100
20/1/2016 *************** 50
1/2/2016  *****************100
4/2/2016   ******************150
19/2/2016 *****************50.5
```

I need select sum of amount group by date 
for example 
month is 1 amount is 200.0
month is 2 amount is 300.5

**Comment by beeender** [comment]
Take a look at `RealmQuery.distinct()` https://realm.io/docs/java/latest/api/io/realm/RealmQuery.html#distinct-java.lang.String-

Try something like this:

```java
RealmResults<ChequeOutGoing> distintResults = realm.where(ChequeOutGoing.class).distinct("entryDate");
for (ChequeOutGoing cog : distinctResults) {
    int sum = realm.where(ChequeOutGoing.class).equalTo("entryDate", cog.getEntryDate()).sum("amount");
}
```

**Comment by jcj52436999** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  jcjacksonengineering@gmail.com
    Domain joe-jackson.net has exceeded the max emails per hour (109/100 (109%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext6.iad.github.net ([192.30.252.197]:46169 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by rs5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1afmMI-001xOY-HN
	for jcjackson@joe-jackson.net; Tue, 15 Mar 2016 06:37:50 -0400
Date: Sun, 13 Mar 2016 19:59:45 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1457924386;
	bh=PmVbLQ3hrXq/vwZA/8bA7mcpCybIKknOJfrcZuHQ1dE=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=eZ6YxiXUr+rNwiZEmWSm2Q4eq182zxm0JHEHWSCUHLufHE1PNwayW05lJW0o+D5Xg
	 juk2tYUYXM8Mwl4AkgdEEeBttpBy9i4VqsETzhnyUSCG7pU0Ooo0ew9ZChWoNsrfxU
	 Ixt0gvq9kjFwnoMdlFpszYsOKnltZozoV0t+8gOE=

**Comment by beeender** [comment]
@MahmoudAlnouno Any updates on this? Does above comment help?

**Comment by beeender** [comment]
Close due to no response.
