### ISSUE TITLE
Version realm 

### ISSUE THREAD

**Issue by MahmoudAlnouno** [realm/realm-java#2438]
## ** When i use 
`'io.realm:realm-android:0.87.5'
`
I have this error

`'value' belongs to a different Realm.ChequeOutGoingRealmProxy.setBank(ChequeOutGoingRealmProxy.java:164)`

but if I change version .

`  compile 'io.realm:realm-android:0.84.1'
`work fine 
so ,, how do I use it

```

public class ChequeOutGoing extends RealmObject implements Cheque {
    @PrimaryKey
    private Long id;
    private Bank bank;
  }


```
```
public class Bank extends RealmObject {
    @PrimaryKey
    private Long id;
    private String name;
}
```

this is classes 
On button click 
```
ChequeOutGoing chequeOutGoing = new ChequeOutGoing();
chequeOutGoing.setId(DBPresenter.getDbPresenter().getNextId(ChequeOutGoing.class));
chequeOutGoing.setBank((Bank) DBPresenter.getDbPresenter().executeSelectByName(Bank.class, "name", spnBankName.getSelectedItem().toString()));

```
DBPresenter .class 
 

```
@Override
public RealmObject executeSelectByName(Class aClass, String filedName, String value) {
return realm.where(aClass).equalTo(filedName, value).findFirst();
}
```
after it I save data using this function
 ```
realm.executeTransaction(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {
                realm.copyToRealm(passedObject);
            }
        }, new Realm.Transaction.Callback() {
            @Override
            public void onSuccess() {
                dbOnSaveHandler.onSuccess();
                super.onSuccess();
            }

            @Override
            public void onError(Exception e) {
                dbOnSaveHandler.onException(e);
                e.printStackTrace();
                super.onError(e);
            }
        });
```

**Comment by beeender** [comment]
That exception means you are using a RealmObject across thread.

Please check our doc about threading for more details https://realm.io/docs/java/latest/#threading

When you using the async transaction, `public void execute(Realm realm)` realm here is a different Realm instance which is created in background thread. but the `passedObject` is managed by the Realm which is created in you UI thread (I guess.). One solution is you can use `RealmObject.copyFromRealm()` to create a standalone object (not managed by Realm anymore) and pass it to the async transaction.

**Comment by jcj52436999** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  jcjacksonengineering@gmail.com
    Domain joe-jackson.net has exceeded the max emails per hour (100/100 (100%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193]:45070 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by rs5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1afmIb-001vsD-Jg
	for jcjackson@joe-jackson.net; Tue, 15 Mar 2016 06:34:01 -0400
Date: Sun, 13 Mar 2016 19:54:00 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1457924040;
	bh=/mq+1cAvMFWpc5H7IH3SJQ1rI46qh01Ic60mBPxjEv0=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=Rpa9ORDvUFhzErlNGKmm5NEOiPB7Q+3jQA1G/92QNbL2MzkTjz0CHNwdsCBByvnm+
	 PysDy/seArhPT1iTfaaLxsraBjO+lDBK3TI945e1cddNzkP5AMfjGTNcq3ilnYP1T3
	 r7bsHu4z4lEywfL5hxYUuhoICC9FPV4XFFF2qO1c=

**Comment by beeender** [comment]
@MahmoudAlnouno Any updates on this? Does above comment help?

**Comment by beeender** [comment]
Close due to no response.
