### ISSUE TITLE
DynamicRealmObject.toString() does not honor null values

### ISSUE THREAD

**Issue by zaki50** [realm/realm-java#2439]
#### Goal

* `DynamicRealmObject.toString()` shows null value as "null".
* Remove "class_" prefix from type name in that String.
* Align the format to the String from typed `RealmObject`.

#### Expected Results

```
Nullables = [{str:null},{bool:null},{num:null},{time:null},{bytes:null}]
```

#### Actual Results

```
class_Nullables = [{str: null}, {bool: false}, {num: 0}, {time: Thu Jan 01 09:00:00 GMT+09:00 1970}, {bytes: null}]
```

#### Code Sample

```java
public class Nullables extends RealmObject {

    private String str;
    private Boolean bool;
    private Integer num;
    private Date time;
    private byte[] bytes;

    // getters and setters
}
```

```java
Realm realm = Realm.getInstance(new RealmConfiguration.Builder(this).deleteRealmIfMigrationNeeded().build());
try {
    final Nullables nullables = new Nullables();
    realm.executeTransaction(new Realm.Transaction() {
        @Override
        public void execute(Realm realm) {
            realm.deleteAll();
            realm.copyToRealm(nullables);
        }
    });
} finally {
    realm.close();
}

final DynamicRealm dynamicRealmBefore = DynamicRealm.getInstance(new RealmConfiguration.Builder(this).build());
try {
    System.out.println(dynamicRealmBefore.allObjects("Nullables").first().toString());
} finally {
    dynamicRealmBefore.close();
}
```

#### Version of Realm and tooling
Realm version(s): 0.88.0

Android Studio version: 2.1 Preview1

Which Android version and device: N preview1

**Comment by stk1m1** [comment]
I am with you for removing class prefix. However, I think that `[{str: null}, {bool: false}, {num: 0}, {time: Thu Jan 01 09:00:00 GMT+09:00 1970}, {bytes: null}]` is more aligned with Java behavior than `[{str:null},{bool:null},{num:null},{time:null},{bytes:null}]`. 

I might not actually grasp the idea right. Please correct me in that case.

**Comment by zaki50** [comment]
@stk1m1 Realm supports `null` as field value by using `Integer` instead of `int`.

I think `toString()` displays `null if type of the field is `Integer`(not `int) and the value is `null`.
