### ISSUE TITLE
Add `isPrimaryKey` and `getPrimaryKey` to `RealmObjectSchema`

### ISSUE THREAD

**Issue by beeender** [realm/realm-java#2440]
We used to have `Table.getPrimaryKey()` to return the PK row. But this cannot be achieved by the new Dynamic API anymore.

Propose to add two more methods to `RealmObjectSchema`

* `void RealmObjectSchema.isPrimaryKey(String fieldName)`
* `String RealmObjectSchema.getPrimaryKey()`

Requested from SO http://stackoverflow.com/questions/35978812/realm-io-v0-88-get-primary-key-column-name

**Comment by beeender** [comment]
#2445 adds `isPrimaryKey` which should be good enough for current use case. For the purpose to minimize the API methods numbers, no need to add `RealmObjectSchema.getPrimaryKey()`

**Comment by jcj52436999** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  jcjacksonengineering@gmail.com
    Domain joe-jackson.net has exceeded the max emails per hour (122/100 (122%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext7.iad.github.net ([192.30.252.198]:60966 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by rs5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1aflkR-001gHu-QJ
	for jcjackson@joe-jackson.net; Tue, 15 Mar 2016 05:58:43 -0400
Date: Tue, 15 Mar 2016 00:30:38 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1458027038;
	bh=HfUsSKHEvtBHm09MNOq3uP1b77TG+x0LwUOhoeWGF0Q=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=2N9ttLJe3tH3XA+wG3YbhdUqVPSKuNL6h6tACF2ZyTrbAh4XiT1dqBF86EzCi5uSN
	 qZekketskPK5U4gMJRE2tdPeFXlGO+nKwqDlDgqPsv8JbhgGBgHeAO0zHTDx6112hD
	 7s/vp0iGJW2wbVUCuNUe3QTzs2oqRt3IY08MBaKw=

**Comment by jcj52436999** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  jcjacksonengineering@gmail.com
    Domain joe-jackson.net has exceeded the max emails per hour (108/100 (108%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext6.iad.github.net ([192.30.252.197]:46146 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by rs5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1afmMI-001xOL-6l
	for jcjackson@joe-jackson.net; Tue, 15 Mar 2016 06:37:50 -0400
Date: Mon, 14 Mar 2016 03:02:30 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1457949750;
	bh=XDNaAes1ETB8Rw/IonZQrhRjdLc4INYYlmbh1LvGNxE=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=1gTEPv+gxmLCiPkx5j0B7Gdx9CzmvMPin/k+1s6DcTLIY+Kzcy/V1k2tQZBGsnR6Z
	 1bN9TJXWERYh4VRBLBfSS8Le6UkI//ABiiETcs6lzrwqFj6khw2q2QZhKt+HqPxBuD
	 IjcZAM4ajK0ydPuhhYssKVxEeEzEUIRqqyAN0+lE=
