### ISSUE TITLE
RealmConfiguration NullPointerException

### ISSUE THREAD

**Issue by swjjxyxty** [realm/realm-java#2442]
#### Goal

> What do you want to achieve?
get a realm instance.

#### Expected Results

> Realm instance

#### Actual Results

> `03-14 16:30:56.439: E/AndroidRuntime(20628): Caused by: java.lang.NullPointerException
03-14 16:30:56.439: E/AndroidRuntime(20628): 	at io.realm.RealmConfiguration.equals(RealmConfiguration.java:186)
03-14 16:30:56.439: E/AndroidRuntime(20628): 	at io.realm.RealmCache.validateConfiguration(RealmCache.java:217)
03-14 16:30:56.439: E/AndroidRuntime(20628): 	at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:103)
03-14 16:30:56.439: E/AndroidRuntime(20628): 	at io.realm.Realm.getInstance(Realm.java:213)
03-14 16:30:56.439: E/AndroidRuntime(20628): 	at io.realm.Realm.getInstance(Realm.java:176)
03-14 16:30:56.439: E/AndroidRuntime(20628): 	at com.xty.ecowa.ui.activities.NewEventActivity.onActivityResult(NewEventActivity.java:256)
03-14 16:30:56.439: E/AndroidRuntime(20628): 	at android.app.Activity.dispatchActivityResult(Activity.java:5804)
03-14 16:30:56.439: E/AndroidRuntime(20628): 	at android.app.ActivityThread.deliverResults(ActivityThread.java:3831)
03-14 16:30:56.439: E/AndroidRuntime(20628): 	... 11 more`

#### Steps & Code to Reproduce

> update version 0.83 to 0.88.

#### Code Sample

```java

Realm instance = Realm.getInstance(this);

```

#### Version of Realm and tooling
Realm version(s): 0.88

Android Studio version: 2.0 beta6

Which Android version and device: 4.4.4-Samsung-SM-E7000 ,SM-G7509

**Comment by lourenci** [comment]
Hi, 
I already opened something like that. I think that is already closed and it will released at 0.88.1 version. #2416

**Comment by zaki50** [comment]
@swjjxyxty thank you for reporting.
As @lourenci said, it was fixed in #2416 and `0.88.1` which includes #2416 has been released.

Please try `0.88.1`.

**Comment by swjjxyxty** [comment]
Thanks.

**Comment by jcj52436999** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  jcjacksonengineering@gmail.com
    Domain joe-jackson.net has exceeded the max emails per hour (107/100 (107%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193]:32838 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by rs5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1aflj4-001fcY-Ry
	for jcjackson@joe-jackson.net; Tue, 15 Mar 2016 05:57:18 -0400
Date: Mon, 14 Mar 2016 09:20:54 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1457972454;
	bh=rNNA4oGP2MWXsjq47bbSjRg7QLIGTtgiMA/MxGVvPR4=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=GIgqawamJLZ1pGBEruTyeFds8LzBf82qHn+fdmMHrPA3T0sv5++rWp1rGTEhtaXVl
	 yRSgX2jptKc+VYDMIrtRclAK83v6duVI7iV+evJh+swdc+cCcR7KmNOoPF1jLQmtv5
	 Z5GOf5i4BJcrWtTFDNONbyQi8yy/Ru+xioN8x8UQ=
