### ISSUE TITLE
Build-error if using @JsonIgnore from LoganSquare

### ISSUE THREAD

**Issue by nasuellia** [realm/realm-java#2452]
In the past few days I've been working with Realm and LoganSquare, and consequently I'm having lots of fun making them work together.

Good results with v0.88, now that I can put custom methods in my POJOs, awesome.

But there's still one thing I can't figure out and I'm starting to think it's a problem on the Realm code-base side of things, or alternatively, I might be a moron! =)

if I use the @JsonIgnore annotation on any field in my POJOs, I get the following build-error when I issue the <run> command (Android Studio 2.1 Preview 1):

Error:Execution failed for task ':<mymodule>:transformClassesWithRealmTransformerForDebug'.
> com/bluelinelabs/logansquare/annotation/JsonIgnore$IgnorePolicy

(oddly, Gradle build completes just fine issuing Rebuild Project or Make Project).

**Comment by zaki50** [comment]
Hi @nasuellia 
Thank you for reporting.

It seems to be the same issue with #2413.
#2413 has been fixed in `0.88.1` release. Please try it.

**Comment by nasuellia** [comment]
Hi @zaki50 

I didn't notice the previous report, I looked for LoganSquare and found nothing, I should have though that it's based on Jackson. =)

I just tried v88,1 and it now works like a charm with @JsonIgnore annotations.

Thanks a bunch!

**Comment by zaki50** [comment]
@nasuellia no problem.
I updated the title of #2413 to be easier to find.

**Comment by jcj52436999** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  jcjacksonengineering@gmail.com
    Domain joe-jackson.net has exceeded the max emails per hour (114/100 (113%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext7.iad.github.net ([192.30.252.198]:58240 helo=github-smtp2a-ext-cp1-prd.iad.github.net)
	by rs5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1afljv-001g2i-7w
	for jcjackson@joe-jackson.net; Tue, 15 Mar 2016 05:58:11 -0400
Date: Mon, 14 Mar 2016 11:33:08 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1457980388;
	bh=LhSrPKodSJZvI/aupELrYsDJqoqC0LycpK/Aaqp10HE=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=LWekPf91+NO2EKC5dSgTavreINre0TOQNCtyUePdQcDUdSQajMGV6T3aepqtpftNi
	 tt2mTxltAFYaHce/KtrHzRfrvqB1sTeiyzPcLkYN+eyEEVeZXCSRh1QahMK65MfiDB
	 aQRjEj6VBtzEdaNEb5nw4Vtq9BGCzRiJafHaaWHM=

**Comment by jcj52436999** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  jcjacksonengineering@gmail.com
    Domain joe-jackson.net has exceeded the max emails per hour (115/100 (114%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext3.iad.github.net ([192.30.252.194]:49506 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by rs5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1afmMo-001xc7-8M
	for jcjackson@joe-jackson.net; Tue, 15 Mar 2016 06:38:22 -0400
Date: Mon, 14 Mar 2016 11:12:10 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1457979130;
	bh=hHr9fGvKFv+tJ64qhKGuuue0HGBOedF7KKi+Gm70WEA=;
	h=From:Reply-To:To:In-Reply-To:References:Subject:List-ID:
	 List-Archive:List-Post:List-Unsubscribe:From;
	b=tGZOaV0bBSHPcYYIdZseADg8YeWWLTKz/iuO4M2TrtpKg35BnMINgDYkJxJ+AX00h
	 Mbu4lsn4nZiJ2lo1G7oP1qeK1NyoJtvCunM+HoNcSairt0fRTVRqSfN5Po9Tzpmhph
	 wAnjYEnFUmapDs4GdFQTcbsz/rg+A2Li5njq0sng=
