### ISSUE TITLE
Realm just update half of search result

### ISSUE THREAD

**Issue by steven274** [realm/realm-java#2457]
```
Realm realm = Realm.getDefaultInstance();
RealmResults<Message> messages = realm.where(Message.class).equalTo("read", false).findAll();
realm.beginTransaction();
Log.i("Total", messages.size() + "");
for (int i=0; i<messages.size(); i++) {
    messages.get(i).setRead(true);
}
realm.commitTransaction();
messages = realm.where(Message.class).equalTo("read", false).findAll();
Log.i("Total", messages.size() + "");
realm.close();
```

Console:
I/Total: 42
I/Total: 21

**Comment by cmelchior** [comment]
Hi @steven274 
This is due to our RealmResults are always up-to-date and that you actually change the property your searched for. We are aware that this can come as a slight surprise in cases such as yours and are working on fixing it here: #2124 

In the meantime you can use the work-around described here: https://github.com/realm/realm-java/issues/640#issuecomment-103798064

**Comment by jcj52436999** [comment]
This message was created automatically by mail delivery software.

A message that you sent could not be delivered to one or more of its
recipients. This is a temporary error. The following address(es) deferred:

  jcjacksonengineering@gmail.com
    Domain joe-jackson.net has exceeded the max emails per hour (107/100 (107%)) allowed.  Message will be reattempted later

------- This is a copy of the message, including all the headers. ------
Received: from github-smtp2-ext2.iad.github.net ([192.30.252.193]:43825 helo=github-smtp2b-ext-cp1-prd.iad.github.net)
	by rs5.websitehostserver.net with esmtps (TLSv1.2:ECDHE-RSA-AES256-GCM-SHA384:256)
	(Exim 4.86_1)
	(envelope-from <noreply@github.com>)
	id 1afmLr-001xDu-OG
	for jcjackson@joe-jackson.net; Tue, 15 Mar 2016 06:37:23 -0400
Date: Mon, 14 Mar 2016 13:28:18 -0700
DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=github.com;
	s=pf2014; t=1457987298;
	bh=vYNhwzWYPVJ3T7SGMG1mYgAxOBnrkklLuB/aH8tGW04=;
	h=From:Reply-To:To:Subject:List-ID:List-Archive:List-Post:
	 List-Unsubscribe:From;
	b=TCKzRhBXIfrhaSFLvyFzoXWXl8KZE6p0V/o1cm5LtBMR97rxlhT2PsI63kMEQnFyu
	 MfJOhA8DKFJoVOGKZZc+LhIrGb4C/BoXzG6UD4EO7VZuPutGALlX742nI12COw+1tU
	 lSTltNkSp/TgLlU/i0OfcKyZfQWLUmM8VAiP9RUQ=
