### ISSUE TITLE
Realm access from incorrect thread.

### ISSUE THREAD

**Issue by mithrann** [realm/realm-java#2460]
Hi,
I have a dataHandler library which takes care fetching data from server and local db.
Now i fetch list<clients> from realm and then pass it to app. where i process the data(adding section) in another thread(AsyncTask) and display them in list. I know this issue is already reported and work in progress. But i couldn't find any work around for this. Since i have already migrated 50% of code to Realm. Now i cant go back as well. It will be great if someone can point me in right direction.

Thanks in advance.

**Comment by beeender** [comment]
Hi!
Please take a look at our document https://realm.io/docs/java/latest/#threading
and https://realm.io/docs/java/latest/#strategies-when-dealing-with-android-framework-threads

Please let us know if you have further questions, thanks!

**Comment by mithrann** [comment]
@beeender I have looked at those docs. But my case here is different.
For example. When i need to display List of clients. I have function in my datahandler library that will first fetch data from local db the send that in the Eventbus to my app where i process those data in AsyncTask.

Now using Realm i couldn't do that because of this incorrect thread issue. 
Is there is any way to pass that List<Client> to asyncTask(Where Client extends RealmObject).

Now as a work around i am converting the Client to another object which does not extend from RealmObject and using that. Wonder if there is any easier way to do this.

**Comment by cmelchior** [comment]
@mithran
You can use `realm.copyFromRealm()` to get a standalone copy you can transfer between threads, but you will also loose the benefits of auto-updating and lazy-loading if you do.

**Comment by mithrann** [comment]
@cmelchior Thanks a lot!. That works :+1:
