### ISSUE TITLE
`typedColumnIndices` can be kept until next time opened Realm version changes

### ISSUE THREAD

**Issue by beeender** [realm/realm-java#2465]
Currently `typedColumnIndices` will be cleared when all of the Realm instances closed. This slows down the opening the Realm with the same schema version at the next time.

In this situation, we could keep the `typedColumnIndices` until next time the Realm schema version changes.

Issue reported by https://github.com/realm/realm-java/issues/2414

**Comment by cmelchior** [comment]
I think we already discussed this previously. I think the idea we came up with then was to cache the validated schema, save the latest realm version when closing the last instance and then check that version when reopening. That would be safer than checking against last modified on the filesystem.

I cannot find the issue though...

**Comment by cmelchior** [comment]
Moving to P2 ... would be nice to have included but not strictly necessary for a 1.0 release.

**Comment by cmelchior** [comment]
Folding this into https://github.com/realm/realm-java/issues/2231
