### ISSUE TITLE
Link to changelog from the website doc

### ISSUE THREAD

**Issue by Marcel50506** [realm/realm-java#2466]
#### Goal

Know what is different between realm versions to know if it is useful to update.

#### Expected Results

See some "Release notes" or "Change log" when a new (major/minor) version comes out

#### Actual Results

There seems to be none (to find at least)

**Comment by cmelchior** [comment]
Perhaps you are looking for https://github.com/realm/realm-java/blob/master/CHANGELOG.md ?

**Comment by Marcel50506** [comment]
Exactly what I was looking for, thank you :+1: Was looking in the wrong place I guess. Might it be an idea to link to this page from the realm.io documentation? This is my fist go-to to see if there is a new release.

**Comment by cmelchior** [comment]
Yes, linking to the changelog from the website is probably a good idea.
