### ISSUE TITLE
Rename BadVersionException

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#2468]
We should rename BadVersionException to something more appropriate and less "dangerous" sounding. Perhaps "VersionUnreachableException"

**Comment by cmelchior** [comment]
This exception is being cast from JNI, having the same name in both Java/JNI seems more important  than this rename. Besides we had no feedback on this either way. Closing.

**Comment by Zhuinden** [comment]
`BadVersionException` already makes sense, it just means that you got a result set from the async query that belongs to an older version of the Realm instance, right?

**Comment by cmelchior** [comment]
Yes
