### ISSUE TITLE
We can reduce the chance of `BadVersionException` in some cases

### ISSUE THREAD

**Issue by zaki50** [realm/realm-java#2470]
https://github.com/realm/realm-java/blob/5444c96b8bec2a6537f30401cca3b452aab1a42a/realm/realm-jni/src/io_realm_internal_TableQuery.cpp#L1055

https://github.com/realm/realm-java/blob/5444c96b8bec2a6537f30401cca3b452aab1a42a/realm/realm-jni/src/io_realm_internal_TableQuery.cpp#L1166

```
    } else if (sg->get_version_of_current_transaction() != handoverQuery->version) {
        sg->end_read();
        sg->begin_read(handoverQuery->version);
    }
```

The code above can be:

```
    } else if (sg->get_version_of_current_transaction() < handoverQuery->version) {
        sg->advance_read(handoverQuery->version);
    } else if (handoverQuery->version < sg->get_version_of_current_transaction()) {
        sg->end_read();
        sg->begin_read(handoverQuery->version);
    }
```

By avoiding to call `end_read()`, we can reduce the chance of `BadVersionException`.

**Comment by cmelchior** [comment]
This will be handled by the Object Store when #3834  is merged. So closing this.
