### ISSUE TITLE
Distribution package should be selfcontained

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#2472]
After the move to the Gradle plugin the JAR file is no longer being distributed as part of our Distribution package that can be downloaded from the website.

We should make that package self-contained.

One option would be to include a maven repository inside the zip file and modify all the examples to use that when building.

**Comment by beeender** [comment]
And also, maybe this message should be changed
"Note: Version 0.88.2 of Realm is now available: http://static.realm.io/downloads/java/latest"
And suggestion by @n0mer from https://github.com/realm/realm-java/issues/944#issuecomment-197680249 , we could also add a link to the change log when show the new version note.

**Comment by cmelchior** [comment]
Outdated. Folding into https://github.com/realm/realm-java/issues/6613
