### ISSUE TITLE
Async transactions only call onChange once when called in same thread

### ISSUE THREAD

**Issue by lujop** [realm/realm-java#2474]
I expect that async transactions notify changed listeners whatever was it's calling thread.
Because I think that it's a common pattern in android for example to have:

* Activity makes a query and listen on it's changes.
* A Service (not IntentService) is started and it modifies data affected by the query. The service it's asynchronous by nature but it listen and coordinate it's state from the main thread that receives event results from async sources (for example a websocket, location provider, ...).
When the service receives a result in main thread and does an async transaction I expected to be notified to the activity.

But it gives me a strange behaviour. Sometimes the handler it's called and sometimes not.

Here is some sample code to see that change handler is only called once:

        realm = Realm.getDefaultInstance();

        user = Realm.getDefaultInstance().where(UserRealm.class).equalTo("uid","uid").findFirst();
        user.addChangeListener(new RealmChangeListener() {
            @Override
            public void onChange() {
                Timber.i("user changed handler1. Name is %s",user.getName());
            }
        });

        doUpdateAsync("1");
        doUpdateAsync("2");

        Handler handler = new Handler() {
            @Override
            public void handleMessage(Message msg) {
                iterate();
            }
        };

        new Timer().scheduleAtFixedRate(new TimerTask() {
            @Override
            public void run() {
                handler.sendMessage(handler.obtainMessage());
            }
        },0,4000);

    }

    private void iterate() {
        if(user!=null)
            user.removeChangeListeners();

        Timber.i("Start iteration");

        doUpdateAsync("iter");
    }

    private void doUpdateAsync(String name) {
        Realm r = Realm.getDefaultInstance();
        r.executeTransaction(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {
                UserRealm obj = realm.where(UserRealm.class).equalTo("uid","uid").findFirst();
                obj.setName(name);
                Timber.i("Changed %s",name);
            }
        });
        r.close();
    }

_[EDIT: Added output]_
Output: Crossed lines are the ones expected but not printed

  Changed 1
  ~~user changed handler1. Name is 1~~
  Changed 2
  user changed handler1. Name is 2 
  Start iteration
  Changed iter
  ~~user changed handler1. Name is iter~~
  Start iteration
  Changed iter
  ~~user changed handler1. Name is iter~~
  ...

In resume the changed handler is only executed once and only the **user changed handler1. Name is 2** is printed.
I can understand, althought is not deriable, that the first changed handler is not fired becase it's very close in time with the second. But I really expect the __iter__ ones to be fired.

**Comment by beeender** [comment]
What is the expected output? like:

```
user changed handler1. Name is xxx
user changed handler1. Name is 1
user changed handler1. Name is 2
```

What is the current output from your observation?

**Comment by lujop** [comment]
@beeender I've just updated the issue including output

**Comment by beeender** [comment]
@lujop OK, this is actually expected. Let me try to explain this:

Realm is using `Handler` to notify other threads that the db has been change. When other thread gets the event in the handler loop, it will seek to the latest Realm version, please notice it just seek to the latest db version not the specific version. So if you continuously changing the data in the background, it is guaranteed that the **latest data can be seen in other threads**, but it **won't** be guaranteed that every change will be reflected to other threads.

For most use cases, this will remove lots of overhead since mostly program cares about the latest data. 

Can I ask why do you need it behaves like what you described?

**Comment by lujop** [comment]
@beeender I can understand that some events are lost due to performance, that is not a big problem for me.  But in my example that is only the case for the first lost (~~user changed handler1. Name is 1~~). 
The other updates are executed indefinitely every 4 seconds. And *none of them* get the changed event (~~user changed handler1. Name is iter~~).

My use case is: 

1. An activity makes a query to show content and puts a handler on that query to receive updates
2. There is a service that manages a websocket that receives data from a server that update db and can modifiy data from the activity query. 
Websocket operates asynchronously but reports messages in Main thread. And is in main thread that the service does async transactions to update db from websocket data.
3. I expect that the transactions done in *2* ar seen in *1*

**Comment by beeender** [comment]
@lujop about this "An activity makes a query to show content", can I challenge that by if the changes happen too fast, then it is pointless to show the changes to user? Just the latest result would be good enough?

**Comment by lujop** [comment]
@beeender Yes it's completely razonable what you say.
But it's not the case I illustrated here. There's an infinite iteration that runs every 4 seconds indefinitely and change handler is only called first time and never is called again although you let 100 iterations.

The problem I suspect is that asyncTransactions run on same thread of change handler aren't notified at all, only the first time or there are some subtle hidden logic here.

**Comment by beeender** [comment]
@lujop 
I did check your source code again, i found the change listener is removed in the `iterate()` by 

``` java
if(user!=null)
    user.removeChangeListeners();
```

I think that is the reason you didn't get `user changed handler1. Name is iter`

**Comment by lujop** [comment]
@beeender You are right. What a stupid mistake on my part.
I played with several tests to reproduce and then when I reduced code I didn't remove the subscriber.

I will recheck my real case. What I understood by this conversation is that some updates can be lost only if there are very concurrent but in that cas always the **last** will be notified. It's correct?

**Comment by beeender** [comment]
yep, you shouldbe guaranteed to  always get the **last** update if the listener is not removed (:P).
