### ISSUE TITLE
@Required is invalid for field item with the type Something

### ISSUE THREAD

**Issue by yolapop** [realm/realm-java#2477]
Hi Realm team, I can't build with current realm setting.

    public class MyClass extends RealmObject {
        @Required private Something something;
        // setter getter
    }

    public class Something extends RealmObject {
        private int id;
        // setter getter
    }

This error is shown when building my code

> @Required is invalid for field item with the type Something

Realm version(s): 0.88.2

Android Studio version: 1.5.1

Thank you.

**Comment by beeender** [comment]
Please refer to the java doc https://realm.io/docs/java/latest/api/io/realm/annotations/Required.html

> Only Boolean, Byte, Short, Integer, Long, Float, Double, String, byte[], Date can be annotated with Required. Compiling will fail when fields with other types have Required annotation. Fields with primitive types and the RealmList type are required implicitly. **Fields with RealmObject type are always nullable.**

**Comment by yolapop** [comment]
Thanks for clarifying. That wasn't in the latest doc, though.

> **Required fields and null values**
In some cases, null is not an appropriate value of a field. The @Required annotation can be used to tell Realm to enforce checks to disallow null values. You don’t have to add @Required to fields of primitive types as these cannot be null.

**Comment by beeender** [comment]
Yep, we will update the dac, thanks!
