### ISSUE TITLE
@Ignore'd members of certain types in RealmObject produce errors

### ISSUE THREAD

**Issue by beeender** [realm/realm-java#2478]
Error reported on SO http://stackoverflow.com/questions/36011077/ignored-members-of-certain-types-in-realmobject-produce-errors

Consider the following code:

```java
    // ...
    import org.json.JSONObject;
    import android.graphics.Bitmap;
    // ...
    
    public class someObject extends RealmObject
    {
    	@PrimaryKey
    	private String token;
    	private byte[] data;
    	private long updated;
    
    	@Ignore
    	private jsonBuilder jbRoot;
    
    //	@Ignore
    //	private JSONObject JSON; // causes compiling error once uncommented
    //  @Ignore
    //  private Bitmap bmp; // also causes the error
```

Prior to 0.88.0 the code above compiled perfectly. It would not compile on both 0.88.0 & 0.88.1 if I uncommented the ignored JSONObject and/or Bitmap:

```
    Error:Execution failed for task     ':<package>:transformClassesWithRealmTransformerForDebug'.
    > javassist.CannotCompileException: cannot find org.json.JSONObject
```

and

```
    Error:Execution failed for task     ':<package>:transformClassesWithRealmTransformerForDebug'.
    > javassist.CannotCompileException: cannot find android.graphics.Bitmap
```

respectively.

But it accepts the ignored private member of one of my own types as shown with the `jsonBuilder` object.

Build script in case anyone needs it:

```
        buildscript {
            repositories {
                jcenter()
            }
            dependencies {
                classpath "io.realm:realm-gradle-plugin:0.88.1" // tried 0.88.0 as well
            }
        }
        apply plugin: 'realm-android'
```

Thank you. The error above is not actually a blocker but Im just curious why that happens. But I like the 0.88.x changes. :)

**Comment by lectricas** [comment]
I'm getting this error, by ignoring Drawable field in my RealmObject inherited class. What should I do to avoid this?

**Comment by cmelchior** [comment]
What version of Realm are you using?

**Comment by lectricas** [comment]
Hi. I used 0.88 version but then I've updeted it up to 90 and seems like everything started to work fine. Thanks!
