### ISSUE TITLE
Async createAllFromJson

### ISSUE THREAD

**Issue by PsyGik** [realm/realm-java#2481]
### Goals:
Current implementation of `createAllFromJson()` runs on the UI thread. It'd be nice to have a `createAllFromJsonAsync()` which will delegate it to a background thread.

**Comment by cmelchior** [comment]
Hi @PsyGik 
I assume you load the JSON on a background thread as well? What prevents you from saving the data there?

**Comment by PsyGik** [comment]
@cmelchior, No. In my use case I'm loading the JSON from a file. I'm feeding it to realm using an InputStream. I was not able to find a solution for bundling a realm database with the app. So, I am storing the JSON in assets and loading it at first launch.

**Comment by cmelchior** [comment]
Doing it an an async transaction should also work then:

```
InputStream stream = loadJson();
realm.executeTransactionAsync(new Transaction() {
  public void execute(Realm realm) {
    realm.createOrUpdateAllFromJson(json);
  }
}, new OnSuccess() {
  public void onSuccess() {
    stream.close();  
  }
 });
```
Although it would be a lot safer to do everything on the same thread.

**Comment by PsyGik** [comment]
@cmelchior, that works. 

> Although it would be a lot safer to do everything on the same thread.

Could you elaborate on this?

**Comment by cmelchior** [comment]
By opening the InputStream on one thread and using it on another, you introduced the chance of race conditions, e.g. if you by accident start using the input stream on the UI thread you will get exceptions.

This pattern would be safer:

```
realm.executeTransactionAsync(new Transaction() {
  public void execute(Realm realm) {
    InputStream stream = loadJson();
    try {
      realm.createOrUpdateAllFromJson(json);
    } finally {
      stream.close();
    }
  }
});
```

**Comment by PsyGik** [comment]
I see. 
Well, we can use Async Transaction for JSON. That's good to know. Feel free to close the issue.

Thanks for the assist @cmelchior. Have a good one!

**Comment by cmelchior** [comment]
You to. Good luck with the project.
