### ISSUE TITLE
build execution fails on Windows after update to 88.2

### ISSUE THREAD

**Issue by bakua** [realm/realm-java#2484]
#### Goal
Build the app successfully after update to 88.2

#### Expected Results
I am able to build

#### Actual Results
Error:Execution failed for task ':app:transformClassesWithRealmTransformerForStagingDebug'.
cannot find io/realm/MyClassRealmProxy: io.realm.MyClassRealmProxy found in io/realm/MyClassRealmProxy.class

#### Steps & Code to Reproduce
I am seeing this error after update to 88.2. When I downgrade back to 87.2 the project builds OK.

#### Version of Realm and tooling
Realm version(s): 87.2, 88.2

Android Studio version: 1.5.1
OS Version: Windows 10

**Comment by cmelchior** [comment]
Hi @bakua 

Are you using the Gradle plugin as described in https://realm.io/news/realm-java-0.88.0/ ?

**Comment by bakua** [comment]
Hi, yes I am. Actually I am able to build this project on a different workstations. The only difference among them is OS - Windows x Linux. Other than that it is the same Android Studio version. Really don't know what is happening. Also my guyess is that it is not specific error to MyClass.java because when I go to generated apt code directory, that class is first file in it.

**Comment by Damnum** [comment]
I'm having the same issue. Realm Gradle Plugin 0.88.2, Android Studio 1.5.1, Gradle 2.12, Windows 10.

Exception happens in task: transformClassesWithRealmTransformerForDebug

Downgrade to 0.87.5 fixes the exception.

**Comment by cmelchior** [comment]
Thanks for the info. We will look into it.

**Comment by gpulido** [comment]
Hello,
Same problem here.
Realm Gradle Plugin 0.88.2, Android Studio2.1 Preview 4, Android Plugin Gradle2.1.0-alpha4, Gradle version 2.10
It is working in linux ubuntu, not working on WIndows 10

**Comment by beeender** [comment]
@bakua @Damnum @gpulido I tried to create a sample project on Windows 10 AS 1.51, but it works fine. Would you please share a sample project which cannot be built on Windows 10 so I can reproduce the issue?

**Comment by bakua** [comment]
@beeender I found a little time today to look at it. 

I have project with two modules - **app**, **api**. In **api** module I have model classes that extend the Realm. in **app** module I use them.

The issue was caused that build.gradle files of both modules contained `apply plugin: 'realm-android'`. As soon as I've removed it from **app** module, I was able to build with 88.2 once again.

My question now is whether using Realm plugin in multiple modules is correct thing to do from development perspective in the first place, or if this behaviour is a bug.

Thanks :)

**Comment by Damnum** [comment]
I have exactly the same structure as you @bakua

**Comment by beeender** [comment]
I can reproduce this issue now, it seems to be a bug for javaassit on windows. checking now.

**Comment by CarlosMChica** [comment]
Same issue here.

@beeender thanks for taking care of it

**Comment by GaborPeto** [comment]
@beeender I see you updated 0.88.2 so that it replaces both "\" and "/" with "."
I just ran the task `transformClassesWithRealmTransformerForDebug `and I'm still getting the same  `cannot find io/realm/PersistableXXXRealmProxy` exception
