### ISSUE TITLE
From 0.88.0 ,Realm must to be add in application?

### ISSUE THREAD

**Issue by JarvanMo** [realm/realm-java#2487]
I used to use realm-java 0.87.5, it worked well. And I upgrade realm from 0.87.5 to 0.88.2 today. At first I just add the following part in my library's build gradle:
```
apply plugin: 'realm-android'
buildscript {


    repositories {
        jcenter()
    }


    dependencies {
        classpath "io.realm:realm-gradle-plugin:0.88.2"
    }
}
```

However , realm throws an exception that *XX is not part of the schema for this Realm**!. I tried a lot, finally I add those words above in my application's  build.gradle . Yes , it works!Here's the problem,  I have to add those words everywhere ! I just want to ask , can realm be easier?

**Comment by zaki50** [comment]
Hi @JarvanMo 

Are you using multi module gradle project which means that the project has multiple `build.gradle`?

If so, you must add `apply plugin: 'realm-android'` to all projects which uses Realm. And application project must contain `apply plugin: 'realm-android'` even if it does not directly use Realm.

**Comment by JarvanMo** [comment]
THX

**Comment by zaki50** [comment]
@JarvanMo I'll close this issue. If you have further questions, please feel free to reopen it.
