### ISSUE TITLE
UnsatisfiedLinkError exception on ReLinker

### ISSUE THREAD

**Issue by dalinaum** [realm/realm-java#2495]
#### Expected Results

No exception

#### Actual Results

http://crashes.to/s/0a06f902ba4 (from VCNC's Crashlytics)

```
Fatal Exception: java.lang.UnsatisfiedLinkError
dlopen failed: library "/data/data/kr.co.vcnc.android.couple/app_lib/librealm-jni.so" not found
```

#### Steps & Code to Reproduce

This exception is only reported by Crashlytics.

#### Version of Realm and tooling
Realm version(s): 0.88.2

Which Android version and device: Kitkat and JellyBean: Android 4.4.2 (72%), 4.2.2 (16%), 4.4.4 (10%)

**Comment by cmelchior** [comment]
Line 75 in Relinker is the line that loads the native code _after_ the work-around was attempted. Perhaps there are corner cases where the work-around doesn't work as we expect.

**Comment by cmelchior** [comment]
ReLinker is now on JCenter. We should use that instead of including the dependency ourselves.
