### ISSUE TITLE
Package Realm does not exist

### ISSUE THREAD

**Issue by mithrann** [realm/realm-java#2497]
`error: package Realm does not exist` this error comes when gradle sync. Earlier it was working fine!

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath "io.realm:realm-gradle-plugin:0.88.2"
    }
}

apply plugin: 'realm-android'

**Comment by cmelchior** [comment]
Hi @mithrann 
Have you tried cleaning your project? Under `Build > Clean Project`

**Comment by mithrann** [comment]
Yeah cleaned. Still not working. Went back to `compile 'io.realm:realm-android:0.87.5'`

**Comment by cmelchior** [comment]
Have you looked at our examples? They should be working, so perhaps you can spot the difference compared to your project:
https://github.com/realm/realm-java/blob/master/examples/build.gradle
https://github.com/realm/realm-java/blob/master/examples/introExample/build.gradle

**Comment by mithrann** [comment]
Now it works. Once i removed and 0.87.5 went back to 0.88.2. Cleaning project issue

**Comment by ChrisOHu** [comment]
Hi also had this issue, rebuilding the project would solve it, though I think this might be better noted in the doc.

Wishes : )

**Comment by ajithamp** [comment]
hi i did the above u said but i got two more errors

Error:(11, 22) error: package io.realm.react does not exist
Error:(27, 19) error: cannot find symbol class RealmReactPackage
