### ISSUE TITLE
Realm Migration

### ISSUE THREAD

**Issue by DevikaSrinivasan** [realm/realm-java#2498]
Hi,

My Previous released version has the following migration code,

First Version:
**Migration.Class**
```
public class Migration implements RealmMigration {

    public void migrate(final DynamicRealm realm, long oldVersion, long newVersion) {
        RealmSchema schema = realm.getSchema();
        if (oldVersion == 0) {
            schema.get("MesRecherchesBean")
                    .addField("trouver_unbien_type", String.class)
                    .addField("trouver_unbien_uuid", String.class)
                    .addField("trouver_unbien_name", String.class)
                    .addField("trouver_unbien_nb", String.class)
                    .addField("trouver_unbien_newnb", String.class);
            schema.get("RecentSearchBean")
                    .addField("trouver_unbien_type", String.class);
            oldVersion++;
        }
    }
}
```

**Application.Class:**
```
RealmConfiguration config1 = new RealmConfiguration.Builder(this)
                .schemaVersion(0)
                .migration(new Migration())
                .build();

        realm = Realm.getInstance(config1); // Automatically run migration if needed
        realm.close();
```

Second Version:
```
public class Migration implements RealmMigration {

    public void migrate(final DynamicRealm realm, long oldVersion, long newVersion) {
        RealmSchema schema = realm.getSchema();
        if (oldVersion == 0) {
            schema.get("MesRecherchesBean")
                    .addField("trouver_unbien_type", String.class)
                    .addField("trouver_unbien_uuid", String.class)
                    .addField("trouver_unbien_name", String.class)
                    .addField("trouver_unbien_nb", String.class)
                    .addField("trouver_unbien_newnb", String.class);
            schema.get("RecentSearchBean")
                    .addField("trouver_unbien_type", String.class);
            oldVersion++;
        }
        if (oldVersion == 1) {
            schema.get("MesNotificationBean")
                    .addField("notificationUuid",String.class);
            schema.get("AppartmentOpacityBean")
                    .addField("appartmentOpacityId", String.class);
            oldVersion++;
        }
    }
}
```
**Application.Class:**
```
RealmConfiguration config1 = new RealmConfiguration.Builder(this)
                .schemaVersion(0)
                .migration(new Migration())
                .build();

        realm = Realm.getInstance(config1); // Automatically run migration if needed
        realm.close();
```

********************************************

Downloaded playstore version and added few data to the database. Then I created new apk and then installed to my device. So it creates null pointer exception in the Migration.class in this line  schema.get("MesNotificationBean")

**Comment by DevikaSrinivasan** [comment]
Hi @cmelchior ,

Can you please help me with this

**Comment by dadino** [comment]
You didn't change schema version in the second version:
Change

    .schemaVersion(0)

to

    .schemaVersion(1)

**Comment by DevikaSrinivasan** [comment]
Hi,

But if I put schema version to .schemaVersion(1).  Fresh users can't access the oldversion == 0. It willl directly reach to oldversion == 1. Is it correct?

**Comment by DevikaSrinivasan** [comment]
Hi,

How to add new table to the migration class

**Comment by DevikaSrinivasan** [comment]
"MesNotificationBean" is the new table so when I migrate to the new version the class shows null pointer exception. How to add a new table to the migration and its fields?

**Comment by callmepeanut** [comment]
@DevikaSrinivasan I think fresh users would not do the migration, they just create new db file, so schemaVersion() should always be the newest.

**Comment by DevikaSrinivasan** [comment]
@callmepeanut : Ya this following code executes only when migration is needed. So fresh db wont enter into this code,

RealmConfiguration config1 = new RealmConfiguration.Builder(this)
                .schemaVersion(0)
                .migration(new Migration())
                .build();

        realm = Realm.getInstance(config1); // Automatically run migration if needed
        realm.close();

**Comment by callmepeanut** [comment]
@DevikaSrinivasan In your Application.Class:
```
RealmConfiguration config = new RealmConfiguration.Builder(this)
.schemaVersion(2)
.migration(new Migration())
.build();
Realm.setDefaultConfiguration(config);  // Automatically run migration if needed
```
then, you can use```mRealm = Realm.getDefaultInstance();```in your other Classes.
The migration will be processed is needed, fresh user start from version 2, so no need to do migration.

**Comment by emanuelez** [comment]
@DevikaSrinivasan: @callmepeanut is correct. We will wait a bit for your answer before closing this issue.

**Comment by DevikaSrinivasan** [comment]
Okay!!! Thanks to all

**Comment by DevikaSrinivasan** [comment]
Actually the oldversion ever starts from 0. If the current user wants only the oldversion == 1 how will it reach there. It shows the error already field "trouver_unbien_type" is there

**Comment by emanuelez** [comment]
The user should not be able to choose which version of the schema he/she should be using. That's your decision as a developer. If you push an update of your app that uses schema version 2, then people upgrading from schema version 0 and 1 will be upgraded to version 2 with the migration you defined.
Basically you need one migration block for every schema version bump. So from 0 to 1 and from 1 to 2.
Does this make sense?

**Comment by DevikaSrinivasan** [comment]
Initially if I'm making the migration. How the code must be?

Is the following correct?

**Migration.class:**

if(olversion==0){
oldversion++;
}

**Application.Class:**

RealmConfiguration config1 = new RealmConfiguration.Builder(this)
                .schemaVersion(0)
                .migration(new Migration())
                .build();

        realm = Realm.getInstance(config1); // Automatically run migration if needed
        realm.close();

**Comment by DevikaSrinivasan** [comment]
if I'm making the second migration

Is the following correct for second migration?

**Migration.class:**

if(olversion==0){
oldversion++;
}

if(olversion==1){
oldversion++;
}

**Application.Class:**

RealmConfiguration config1 = new RealmConfiguration.Builder(this)
.schemaVersion(1)
.migration(new Migration())
.build();

    realm = Realm.getInstance(config1); // Automatically run migration if needed
    realm.close();

**Comment by emanuelez** [comment]
In our migration example (https://github.com/realm/realm-java/tree/master/examples/migrationExample) you can see how we setup migrations from version 0 all the way to version 3 (https://github.com/realm/realm-java/blob/master/examples/migrationExample/src/main/java/io/realm/examples/realmmigrationexample/model/Migration.java)

**Comment by DevikaSrinivasan** [comment]
Thanks again

**Comment by callmepeanut** [comment]
@DevikaSrinivasan As @emanuelez says, only one version in one apk.
If you want the user to choose the version, you may had to package several versions of apks,  for example:
app_V1.0.apk - db_v0
app_V2.0.apk - db_v1 (migration 0-1)
app_V3.0.apk - db_v2 (for app_V1, migration 0-2; for app_V2, migration 1-2 )
Is this clear to you?

**Comment by DevikaSrinivasan** [comment]
Ya got it

**Comment by emanuelez** [comment]
I will now close this issue. Please feel free to open a new one if you run into more issues.
