### ISSUE TITLE
RealmProxyMediator not found during travis build

### ISSUE THREAD

**Issue by grigoryfedorov** [realm/realm-java#2501]
Hi! After updating to 0.88 I've got following build problems. 

#### Goal

Correct build by travis 
`./gradlew build connectedCheck`

#### Expected Results

successful build

#### Actual Results
General assembleDebug or assembleRelease tasks are successful! But connectedCheck task used by travis fails:
[![Build Status](https://travis-ci.org/redsolution/xabber-android.svg?branch=develop)](https://travis-ci.org/redsolution/xabber-android)
> FAILURE: Build failed with an exception.
> 
> * What went wrong:
> Execution failed for task ':xabber:transformClassesWithRealmTransformerForBetaDebugAndroidTest'.
> > javassist.NotFoundException: io.realm.internal.RealmProxyMediator

You can see full travis log [here](https://travis-ci.org/redsolution/xabber-android/builds/117382757)

#### Steps & Code to Reproduce
[build.gradle](
https://github.com/redsolution/xabber-android/blob/develop/xabber/build.gradle)
[.travis.yml](https://github.com/redsolution/xabber-android/blob/develop/.travis.yml)
[Project](https://github.com/redsolution/xabber-android/tree/develop)

#### Version of Realm and tooling
Realm version(s): 0.88.0 - 0.88.2 (was OK before)
gradle: 1.5.0
BuildTools: build-tools-23.0.2
SDK version: android-23

**Comment by emanuelez** [comment]
I was able to reproduce the issue and I'm looking into it.

On the other hand I can't seem to find any instrumentation unit test in your project so running `connectedCheck` seems useless. Am I missing something?

**Comment by grigoryfedorov** [comment]
@emanuelez thanks! I've removed `connectedCheck`, and it's ok now. Should I close an issue?

**Comment by emanuelez** [comment]
I will close this issue and create a new one for the issue I found while investigating this one :)
