### ISSUE TITLE
Running `connectedCheck` on a project without instrumentation tests makes the Realm transformer fail

### ISSUE THREAD

**Issue by emanuelez** [realm/realm-java#2502]
The failure is:

```
javassist.NotFoundException: io.realm.internal.RealmProxyMediator
```

and it's caused by the fact that, since the test app is empty, the Javassist pool doesn't contain any reference to Realm classes, hence failing at line 89:

```groovy
def baseProxyMediator = classPool.get('io.realm.internal.RealmProxyMediator')
```

**Comment by rimeissner** [comment]
We are experiencing the this error sometimes when we build, but when we retrigger the build it seems too work. We have connected test in place. It fails with the following error:

```
Execution failed for task ':app:transformClassesWithRealmTransformerForAndroidTest'.
javassist.NotFoundException: io.realm.internal.RealmProxyMediator
```

We use the 0.88.2 gradle plugin.

**Comment by bmunkholm** [comment]
.

**Comment by beeender** [comment]
Something wrong with android gradle plugin when compiling `androidTest`, the classes under `exploded-aar` won't be passed to transformer. But when run it 2nd time, it works as normal...

Updating the `com.android.tools.build:gradle:` to `2.1.0` solves this issue.

**Comment by cmelchior** [comment]
Best way to solve issues. Let others do it for you 😀
