### ISSUE TITLE
Unity5 incompatible with v0.88.2

### ISSUE THREAD

**Issue by kenticus** [realm/realm-java#2503]
I have a native android application where I launch a Unity scene using the UnityPlayerActivity.java class.
Using Realm v0.88.2, I get a error back from Unity saying "Failure to initialize! Your hardware does not support this application, sorry!"

In my build.gradle file, I placed the below code to reproduce the Unity error:

```
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath "io.realm:realm-gradle-plugin:0.88.2"
    }
}
apply plugin: 'realm-android'
```
If i turn off all things Realm, unity loads up fine.

Android Studio version: 2.0 Beta-7

**Comment by beeender** [comment]
Does Unity have `.so` files for all platforms? If not, see https://realm.io/docs/java/latest/#couldnt-load-librealm-jniso . You might need to disable some of the Realm `.so` to make all of the native libs be loaded.

**Comment by kenticus** [comment]
It provides x86 and ARM7 architectures. 
<img width="262" alt="screen shot 2016-03-21 at 10 47 18 pm" src="https://cloud.githubusercontent.com/assets/4250025/13942341/f5025ba6-efb6-11e5-9abe-cb00c2856c0d.png">

I currently have everything running perfectly, but thats only the case when i remove Realm. Do the libs collide somehow? I'm not very knowledgeable in how .so files work.

**Comment by beeender** [comment]
Put below lines into your app's gradle.
```
android {
    //...
    packagingOptions {
        exclude "lib/x86_64/librealm-jni.so"
        exclude "lib/mips/librealm-jni.so"
        exclude "lib/armeabi/librealm-jni.so"
        exclude "lib/arm64-v8a/librealm-jni.so"
    }
    //...
}
```

**Comment by kenticus** [comment]
That seems to of fixed the problem. 
Though, I'm not sure I understand why. Could you explain? 
Could this adversely effect me somehow in the future?

**Comment by beeender** [comment]
Basically it is not Realm's fault, but Unity's or Android's.
There is a priority for loading `.so` lib, for example, on a arm-64 device, the system will try to find the arm-64 first, if it doesn't exist, then try with armeabi-v7a, then armeabi. The thing is, 64-bit and 32-bit so cannot be loaded together. If the system loads Realm's arm-64 so first, then it will complain there is no arm-64 so for Unity.

Excluding those doesn't seem to be a problem, just a little bit performance penalty IMO.
