### ISSUE TITLE
Realm a date formats

### ISSUE THREAD

**Issue by hareshsandeep** [realm/realm-java#2506]
Hey Realm team -

I have researched few thing  about the issue that I am facing but was not able to find anything that can resolve it and so I am asking you guys if you could help me out.

I am receiving data from the server which contains dates with the format `EEE, dd MMM yyyy hh:mm:ss Z` and this date format is something that I can't change on the server. 

Moreover, I have 2 issues, to store this date format and to retrieve data back from Realm using greaterThan api of Realm.

Firstly, I am not able to store this date format in the database as it exception and crashes with the below exception : 
`Caused by: io.realm.exceptions.RealmException: Failed to parse date ["Thu, 10 Mar 2016 01:07:10 +0000']: Invalid number: Thu, (at offset 0)`

Secondly, I want to fetch data from Realm using greaterThan for this dates but again, I have read somewhere in SO that Realm supports only specific date format while using greaterThan API.

Could please guide me to address this issues in my app.

Thanks alot.

**Comment by beeender** [comment]
For the Date parsing: Unfortunately Realm doesn't support to use customized parser when calling `createOrUpdateUsingJsonObject`. So you need to parse it set it by yourself.

For the Date `greaterThan`, can you share a example about your problem? `RealmQuery.greaterThan(String fieldName, Date value)` is taking a `java.util.Date` as the input param. I am not sure what do you mean that "Realm supports only specific date format" .

**Comment by hareshsandeep** [comment]
Hey @beeender I followed your suggestion and its resolved now. What I did was I parsed the date and converted them into milliseconds(i.e long datatype) and then i performed greaterThan APi on this long and now its working like a charm. Thanks for your suggestion. :+1: :100:

**Comment by beeender** [comment]
I did help too much :stuck_out_tongue_winking_eye: , you basically solved it by your self. :tada: 
Thanks a lot for your feedback!! Please let us know if you have further questions!
