### ISSUE TITLE
Can you add a detailed example for using query in realm?

### ISSUE THREAD

**Issue by hegdekar** [realm/realm-java#2510]
Please add detailed example of illustrating query in realm. I'm using realm in one of the applications I'm building where I want to search the data based on user's input. 
#### Goal

> Understand as to how the query works in realm. and make use of the same efficiently.

**Comment by beeender** [comment]
Hi, does https://realm.io/docs/java/latest/#queries and https://realm.io/docs/java/latest/api/io/realm/RealmQuery.html help?

Would you please let us know what specific thing you are looking for in the doc?

**Comment by hegdekar** [comment]
Hi, I did check both of these and proceeded with implementation of search it didn't suffice my needs,so had to ask.
Here is what I tried
`results = realm.where(EmployeeShortProfile.class)
                        .contains("name", query)
                        .or()
                        .contains("id", query)
                        .findAllSorted("name",Sort.ASCENDING);`

 I have  an entry in DB with name : **"Deena Sahay"** 
Entering a query: **"Deen"** does return a result, when query changes to **"Deena"** results.isEmpty() returns true which I guess it should not. So trying to know where I'm making a mistake.

**Comment by beeender** [comment]
If you don't have any typo in query/db, or extra space which is not quite visible, or any other mistakes, then it sounds like a bug.
Maybe you can check with some debug/printf first. If everything is correct in your side would you please make a simple testing project and share it with us? share it anywhere, or to help@realm.io if you prefer to share it privately.

**Comment by hegdekar** [comment]
I don't seem to have made any typo though, Im rechecking things closely again.

**Comment by emanuelez** [comment]
Can you please post your class definition for `Profile`? That would allow us to try and replicate the issue.

**Comment by hegdekar** [comment]
`public class EmployeeShortProfile extends RealmObject {

    @PrimaryKey
    private String id;
    @Required
    private String name;
    private String firstName;
    private String lastName;
    private String emailId;
    private String mobileNumber;
    private String location;


    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getFirstName() {
        return firstName;
    }

    public void setFirstName(String firstName) {
        this.firstName = firstName;
    }

    public String getLastName() {
        return lastName;
    }

    public void setLastName(String lastName) {
        this.lastName = lastName;
    }

    public String getEmailId() {
        return emailId;
    }

    public void setEmailId(String emailId) {
        this.emailId = emailId;
    }

    public String getMobileNumber() {
        return mobileNumber;
    }

    public void setMobileNumber(String mobileNumber) {
        this.mobileNumber = mobileNumber;
    }

    public String getLocation() {
        return location;
    }

    public void setLocation(String location) {
        this.location = location;
    }
`

**Comment by hegdekar** [comment]
And here is the code I'm using for querying

`@Override
            public void afterTextChanged(Editable s) {
                trimmedQuery=s.toString().trim();

                if(!trimmedQuery.isEmpty()){
            
                results = realm.where(Profile.class)
                        .contains("name", trimmedQuery)
                        .or()
                        .contains("id", trimmedQuery)
                        .findAllSorted("name",Sort.ASCENDING);
        }
}`

as mentioned earlier the results returns empty even though there are matching entries for the query. I tried even without using the trim for **trimmedQuery**.

**Comment by beeender** [comment]
Can you please add
```
results = realm.where(Profile.class).findAll();
```
before `if(!trimmedQuery.isEmpty()){` and debug it a bit? If it still has problem, please share the values of `results = realm.where(Profile.class).findAll();` and `trimmedQuery` here.

Or you can share your project with us to help@realm.io and let us know how to reproduce it.

**Comment by hegdekar** [comment]
You mean to say try querying without **.contains()** before the **if(!trimmedQuery.isEmpty())**?

**Comment by beeender** [comment]
yep, just want to know what elements are stored there.

**Comment by hegdekar** [comment]
Its giving me whole database content since entering query string isn't performing any filtering on results. With the change in query string **afterTextChange{ }** gets called and with every call to it
`results = realm.where(Profile.class).findAll( )`
is being executed. With this change though app tends to give a heavy load on memory loosing its responsiveness to user input.

**Comment by beeender** [comment]
can you share your realm file with us plus the the query string? so we can take a look. To help@realm.io if you want to share it privately.

**Comment by hegdekar** [comment]
Since data in the database is confidential, I'm not allowed to share it.

**Comment by beeender** [comment]
```
public void afterTextChanged(Editable s) {
    trimmedQuery=s.toString().trim();

    if(!trimmedQuery.isEmpty()){

        RealmResults<Profile> profiles = realm.where(Profile.class).findAll();
        for (Profile profile : profiles) {
            if (profile.getName().contains(trimmedQuery) || profile.getId().contains(trimmedQuery)) {
                Log.e(TAG, "Expected profile " + profile);
            }
        }

        results = realm.where(Profile.class)
            .contains("name", trimmedQuery)
            .or()
            .contains("id", trimmedQuery)
    }
}

```

Please try above code, does it print the expected message in the logcat? What are the printed profiles?

**Comment by hegdekar** [comment]
search by id: entered query **0301**:
**Logcat message:**
E/SeachActivity: Expected profile Profile = [{id:0301},{name:Naveenkumar Hegdekar},{firstName:Naveenkumar},{lastName:Hegdekar},{emailId:hegdekar@xyz.com},{mobileNumber:1234567890},{location:abcd}]
E/SeachActivity: Expected profile Profile = [{id:0301},{name:Naveenkumar Hegdekar},{firstName:Naveenkumar},{lastName:Hegdekar},{emailId:hegdekar@xyz.com},{mobileNumber:1234567890},{location:abcd}]
E/SeachActivity: Expected profile Profile = [{id:0301},{name:Naveenkumar Hegdekar},{firstName:Naveenkumar},{lastName:Hegdekar},{emailId:hegdekar@xyz.com},{mobileNumber:1234567890},{location:abcd}]
E/SeachActivity: Expected profile Profile = [{id:0301},{name:Naveenkumar Hegdekar},{firstName:Naveenkumar},{lastName:Hegdekar},{emailId:hegdekar@xyz.com},{mobileNumber:1234567890},{location:abcd}]

Here its clear that for every digit of query entered, logcat has a message.

But whereas for name search i.e query **naveenkumar hegdekar**
**Logcat message:**
E/SeachActivity: Expected profile Profile = [{id:0301},{name:Naveenkumar Hegdekar},{firstName:Naveenkumar},{lastName:Hegdekar},{emailId:hegdekar@xyz.com},{mobileNumber:1234567890},{location:abcd}]


That pretty much gets us to the old point where results where displayed initially but with the change in query results doesn't seem to refresh. Correct me if I'm wrong about it.

**Comment by beeender** [comment]
@hegdekar Do you mean when you enter every character of "naveenkumar hegdekar", the logcat only shows the last result??? That seems very strange, can you please confirm that `afterTextChanged()` will be called that many times?

**Comment by hegdekar** [comment]
Sorry I was wrong about it . I had a filter enabled in logcat but then actual case is like until I type **nav** logcat seems to get refreshed. That gives me all the profile entries with **nav** as a substring in them. but after that if I clear logcat and continue typing in query logcat remains empty. That clearly means there are filtering being applied on the initial dataset.

**Comment by beeender** [comment]
Would you please setup a breakpoint on `if (profile.getName().contains(trimmedQuery) || profile.getId().contains(trimmedQuery)) ` to see what happened there? If you don't write anything to Realm during typing, nothing will be changed there. And `RealmResults<Profile> profiles = realm.where(Profile.class).findAll();` will always give you the same results.

**Comment by hegdekar** [comment]
Once the DB is created that's all I'm never writing any data back to it again. Just querying to fetch the data already present in it.
And what I'm expecting is if DB contains
-Nathan
-Nivia
-Naveen
-Naveenkumar
-Naveenkumar H
-Naveenkumar Hegdekar

With just **n** in the query all of the above should be present in the results. As the query changes to **na** the results should not contain **Nivia** anymore since it doesn't contain the entered substring. continuing the same when **Naveenkumar He** is the query results must contain only entry corresponding to **Naveenkumar Hegdekar**.

**Comment by beeender** [comment]
> Would you please setup a breakpoint on if (profile.getName().contains(trimmedQuery) || profile.getId().contains(trimmedQuery)) to see what happened there? 

Have you tried above? what is the result?

**Comment by hegdekar** [comment]
That just gets me the profile for first iteration of for and nothing else.

**Comment by beeender** [comment]
I have no idea then.
Although you cannot share your project, if you can simulate this problem with a minimal sample project and share it with us, we'd love to help further.

**Comment by hegdekar** [comment]
I'll try figure out if I can.
But meanwhile do check about this.
Query: ''nav"
no results (actually it should get me around 15 )

Query : "nave"
15 results

But both the times afterTextChanged gets called.

**Comment by kneth** [comment]
@hegdekar Do you query case insensitive? And can you log the value of `trimmedQuery`?

By the way, which locale do your app use?

**Comment by beeender** [comment]
@hegdekar I am closing this issue now. Feel free to reopen it if you can give us more details about the problem (like a sample project to reproduce the isse :smile: ).

Thanks a lot for the feedback!
