### ISSUE TITLE
Selecting the path of the realm file so that i can write/read to it

### ISSUE THREAD

**Issue by iballan** [realm/realm-java#2512]
Realm my support selecting create path and place it there. so that we can write/read to realm file on sdcard..

**Comment by emanuelez** [comment]
The behaviour you mentioned is already supported. `RealmConfiguration.Builder` comes with a constructor that accepts a `File`. See the docs here: https://realm.io/docs/java/latest/api/io/realm/RealmConfiguration.Builder.html#Builder-java.io.File-

**Comment by emanuelez** [comment]
I'll close this issue now. Please feel free to open a new one for any other enquiry.

**Comment by iballan** [comment]
Thank you so much @emanuelez that's exactly what i was trying to find out :)
