### ISSUE TITLE
Unity3d as Subview and Realm conflict with each other

### ISSUE THREAD

**Issue by vlonjatg** [realm/realm-java#2518]
#### Goal

We are implementing Unity3D inside a native Android app as sub-view to add some interactive 3D features to the app and using  Realm as local database.

#### Expected Results

The expected result is for the Unity3D view to load inside a regual Android view and show the 3D interactive content.

#### Actual Results

While it is working great on devices that we have tested (Samsung S3, S4, HTC M8, Nexus 5), we are encountering issues in devices Samsung S6 and S6 Edge. In these two devices (there might be more devices, we tested in these two), Unity is showing an error dialog "Failed to initialize!, Your hardware does not support this application, sorry!".

We just created a new Android Project and imported the Unity3D library fresh and build the app. The Unity view loaded correctly and working as expected in Samsung S6 Edge. But as soon as I added the realm dependency to gradle file of the project, Unity fails to load again. 

So we are 100% sure that Realm and Unity are conflicting with each other somehow. And our best guess is that is has to do something with system libraries but we don't have any idea what.

#### Steps & Code to Reproduce

- Create a new Android Project
- Export a Unity3D project as Google Android Project"
- Import the created project from Unity as module on the created project in the first step
- Add the realm dependency inside the gradle.
- Build the app in Samsung S6 or S6 Edge.
- Your should receive the error dialog: "Failure to initialize!"

#### Code Sample

Here is the sample project which if you build in Samsung S6 & S6 Edge should reproduce the error

[Test Project in Dropbox](https://www.dropbox.com/s/awex7sjrg12dgzl/UnityTesting.zip?dl=0)

#### Version of Realm and tooling
Realm version(s): Tested in 0.87.3 and 0.88.2

Android Studio version: 1.5.1

Which Android version and device: 5.1.1, Samsung S6 & S6 Edge

**Comment by beeender** [comment]
I guess it is the same issue with https://github.com/realm/realm-java/issues/2503 :smile: 
@vlonjatg Let me know if it is not :grinning:

**Comment by vlonjatg** [comment]
Yep, it seems like so. Adding :

```
android {
    //...
    packagingOptions {
        exclude "lib/x86_64/librealm-jni.so"
        exclude "lib/mips/librealm-jni.so"
        exclude "lib/armeabi/librealm-jni.so"
        exclude "lib/arm64-v8a/librealm-jni.so"
    }
    //...
}
```
to the ```app``` and also ```unity``` build gradle files, fixed the issues.

**Comment by beeender** [comment]
:beers:
