### ISSUE TITLE
Realm Browser crashed in Mac OS Mavericks

### ISSUE THREAD

**Issue by kentcheung2000** [realm/realm-java#2520]
My realm browser crashed when open a realm file in Mac OS Mavericks.   It has no problem when opened in EI Capitan.

Thanks for helping.

Process:         Realm Browser [477]
Path:            /Applications/Realm Browser.app/Contents/MacOS/Realm Browser
Identifier:      io.realm.realmbrowser
Version:         0.98.5 (66)
App Item ID:     1007457278
App External ID: 816743972
Code Type:       X86-64 (Native)
Parent Process:  launchd [311]
Responsible:     Realm Browser [477]
User ID:         501

Date/Time:       2016-03-26 11:08:17.834 -0700
OS Version:      Mac OS X 10.9.4 (13E28)
Report Version:  11
Anonymous UUID:  DF0CE8C9-9858-60D8-4BFE-78A6A5673AF1

Crashed Thread:  0  Dispatch queue: com.apple.main-thread

Exception Type:  EXC_CRASH (SIGABRT)
Exception Codes: 0x0000000000000000, 0x0000000000000000

Application Specific Information:
*** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSTextField setUsesSingleLineMode:]: unrecognized selector sent to instance 0x7fe4725694f0'
terminating with uncaught exception of type NSException
abort() called

Application Specific Backtrace 1:
0   CoreFoundation                      0x00007fff893da25c __exceptionPreprocess + 172
1   libobjc.A.dylib                     0x00007fff930f1e75 objc_exception_throw + 43
2   CoreFoundation                      0x00007fff893dd12d -[NSObject(NSObject) doesNotRecognizeSelector:] + 205
3   CoreFoundation                      0x00007fff89338272 ___forwarding___ + 1010
4   CoreFoundation                      0x00007fff89337df8 _CF_forwarding_prep_0 + 120
5   Realm Browser                       0x00000001061fd999 Realm Browser + 14745
6   AppKit                              0x00007fff87c774f1 -[NSCustomView nibInstantiateWithObjectInstantiator:] + 672
7   AppKit                              0x00007fff87c544f3 -[NSIBObjectData instantiateObject:] + 264
8   AppKit                              0x00007fff87c53815 -[NSIBObjectData nibInstantiateWithOwner:topLevelObjects:] + 413
9   AppKit                              0x00007fff87c485ce loadNib + 327
10  AppKit                              0x00007fff87c47b6c +[NSBundle(NSNibLoading) _loadNibFile:nameTable:withZone:ownerBundle:] + 288
11  AppKit                              0x00007fff87edc4d2 +[NSBundle(NSNibLoading) loadNibFile:externalNameTable:withZone:] + 140
12  AppKit                              0x00007fff87edc2ca -[NSWindowController loadWindow] + 196
13  AppKit                              0x00007fff87ee0f88 -[NSWindowController window] + 80
14  AppKit                              0x00007fff87ee20f0 -[NSWindowController showWindow:] + 36
15  Realm Browser                       0x0000000106205630 Realm Browser + 46640
16  AppKit                              0x00007fff87fae5f5 -[NSDocument showWindows] + 100
17  AppKit                              0x00007fff8811482d __80-[NSDocumentController openDocumentWithContentsOfURL:display:completionHandler:]_block_invoke855 + 198
18  AppKit                              0x00007fff88114517 __80-[NSDocumentController openDocumentWithContentsOfURL:display:completionHandler:]_block_invoke_3841 + 24
19  libdispatch.dylib                   0x00007fff8ebda1bb _dispatch_call_block_and_release + 12
20  libdispatch.dylib                   0x00007fff8ebd728d _dispatch_client_callout + 8
21  libdispatch.dylib                   0x00007fff8ebdeef0 _dispatch_main_queue_callback_4CF + 333
22  CoreFoundation                      0x00007fff893414f9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
23  CoreFoundation                      0x00007fff892fc714 __CFRunLoopRun + 1636
24  CoreFoundation                      0x00007fff892fbe75 CFRunLoopRunSpecific + 309
25  HIToolbox                           0x00007fff8bab1a0d RunCurrentEventLoopInMode + 226
26  HIToolbox                           0x00007fff8bab17b7 ReceiveNextEventCommon + 479
27  HIToolbox                           0x00007fff8bab15bc _BlockUntilNextEventMatchingListInModeWithFilter + 65
28  AppKit                              0x00007fff87c6524e _DPSNextEvent + 1434
29  AppKit                              0x00007fff87c6489b -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 122
30  AppKit                              0x00007fff87c5899c -[NSApplication run] + 553
31  AppKit                              0x00007fff87c43783 NSApplicationMain + 940
32  libdyld.dylib                       0x00007fff8d96d5fd start + 1

Thread 0 Crashed:: Dispatch queue: com.apple.main-thread
0   libsystem_kernel.dylib        	0x00007fff88f86866 __pthread_kill + 10
1   libsystem_pthread.dylib       	0x00007fff877c035c pthread_kill + 92
2   libsystem_c.dylib             	0x00007fff8d7e9b1a abort + 125
3   libc++abi.dylib               	0x00007fff8da0cf31 abort_message + 257
4   libc++abi.dylib               	0x00007fff8da32952 default_terminate_handler() + 264
5   libobjc.A.dylib               	0x00007fff930f230d _objc_terminate() + 103
6   libc++abi.dylib               	0x00007fff8da301d1 std::__terminate(void (*)()) + 8
7   libc++abi.dylib               	0x00007fff8da30246 std::terminate() + 54
8   libobjc.A.dylib               	0x00007fff930f20b0 objc_terminate + 9
9   libdispatch.dylib             	0x00007fff8ebd72a1 _dispatch_client_callout + 28
10  libdispatch.dylib             	0x00007fff8ebdeef0 _dispatch_main_queue_callback_4CF + 333
11  com.apple.CoreFoundation      	0x00007fff893414f9 __CFRUNLOOP_IS_SERVICING_THE_MAIN_DISPATCH_QUEUE__ + 9
12  com.apple.CoreFoundation      	0x00007fff892fc714 __CFRunLoopRun + 1636
13  com.apple.CoreFoundation      	0x00007fff892fbe75 CFRunLoopRunSpecific + 309
14  com.apple.HIToolbox           	0x00007fff8bab1a0d RunCurrentEventLoopInMode + 226
15  com.apple.HIToolbox           	0x00007fff8bab17b7 ReceiveNextEventCommon + 479
16  com.apple.HIToolbox           	0x00007fff8bab15bc _BlockUntilNextEventMatchingListInModeWithFilter + 65
17  com.apple.AppKit              	0x00007fff87c6524e _DPSNextEvent + 1434
18  com.apple.AppKit              	0x00007fff87c6489b -[NSApplication nextEventMatchingMask:untilDate:inMode:dequeue:] + 122
19  com.apple.AppKit              	0x00007fff87c5899c -[NSApplication run] + 553
20  com.apple.AppKit              	0x00007fff87c43783 NSApplicationMain + 940
21  libdyld.dylib                 	0x00007fff8d96d5fd start + 1

Thread 1:
0   libsystem_kernel.dylib        	0x00007fff88f86e6a __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff877c0f08 _pthread_wqthread + 330
2   libsystem_pthread.dylib       	0x00007fff877c3fb9 start_wqthread + 13

Thread 2:: Dispatch queue: com.apple.libdispatch-manager
0   libsystem_kernel.dylib        	0x00007fff88f87662 kevent64 + 10
1   libdispatch.dylib             	0x00007fff8ebd9421 _dispatch_mgr_invoke + 239
2   libdispatch.dylib             	0x00007fff8ebd9136 _dispatch_mgr_thread + 52

Thread 3:
0   libsystem_kernel.dylib        	0x00007fff88f86e6a __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff877c0f08 _pthread_wqthread + 330
2   libsystem_pthread.dylib       	0x00007fff877c3fb9 start_wqthread + 13

Thread 4:
0   libsystem_kernel.dylib        	0x00007fff88f86e6a __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff877c0f08 _pthread_wqthread + 330
2   libsystem_pthread.dylib       	0x00007fff877c3fb9 start_wqthread + 13

Thread 5:
0   libsystem_kernel.dylib        	0x00007fff88f86e6a __workq_kernreturn + 10
1   libsystem_pthread.dylib       	0x00007fff877c0f08 _pthread_wqthread + 330
2   libsystem_pthread.dylib       	0x00007fff877c3fb9 start_wqthread + 13

Thread 6:
0   libsystem_kernel.dylib        	0x00007fff88f82a1a mach_msg_trap + 10
1   libsystem_kernel.dylib        	0x00007fff88f81d18 mach_msg + 64
2   com.apple.CoreFoundation      	0x00007fff892fcf15 __CFRunLoopServiceMachPort + 181
3   com.apple.CoreFoundation      	0x00007fff892fc539 __CFRunLoopRun + 1161
4   com.apple.CoreFoundation      	0x00007fff892fbe75 CFRunLoopRunSpecific + 309
5   com.apple.AppKit              	0x00007fff87e0505e _NSEventThread + 144
6   libsystem_pthread.dylib       	0x00007fff877bf899 _pthread_body + 138
7   libsystem_pthread.dylib       	0x00007fff877bf72a _pthread_start + 137
8   libsystem_pthread.dylib       	0x00007fff877c3fc9 thread_start + 13

Thread 7:: RLMRealm notification listener
0   libsystem_kernel.dylib        	0x00007fff88f8764a kevent + 10
1   org.cocoapods.Realm           	0x000000010626513d realm::_impl::ExternalCommitHelper::listen() + 189
2   org.cocoapods.Realm           	0x000000010626534c std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0>::operator()() + 18
3   org.cocoapods.Realm           	0x00000001062652d8 std::__1::__async_assoc_state<void, std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >::__execute() + 26
4   org.cocoapods.Realm           	0x0000000106265481 std::__1::__thread_proxy<std::__1::tuple<void (std::__1::__async_assoc_state<void, std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >::*)(), std::__1::__async_assoc_state<void, std::__1::__async_func<realm::_impl::ExternalCommitHelper::ExternalCommitHelper(realm::_impl::RealmCoordinator&)::$_0> >*> >(void*, void*) + 78
5   libsystem_pthread.dylib       	0x00007fff877bf899 _pthread_body + 138
6   libsystem_pthread.dylib       	0x00007fff877bf72a _pthread_start + 137
7   libsystem_pthread.dylib       	0x00007fff877c3fc9 thread_start + 13

Thread 0 crashed with X86 Thread State (64-bit):
  rax: 0x0000000000000000  rbx: 0x00007fff76265310  rcx: 0x00007fff59a03e78  rdx: 0x0000000000000000
  rdi: 0x0000000000000707  rsi: 0x0000000000000006  rbp: 0x00007fff59a03ea0  rsp: 0x00007fff59a03e78
   r8: 0x00007fff8da33959   r9: 0x00007fff8d8118d0  r10: 0x0000000008000000  r11: 0x0000000000000206
  r12: 0x00007fff59a04000  r13: 0x00007fff59a044d0  r14: 0x0000000000000006  r15: 0x00007fff59a03ee0
  rip: 0x00007fff88f86866  rfl: 0x0000000000000206  cr2: 0x

**Comment by bdash** [comment]
Thanks for reporting this crash. Realm Browser development is tracked in the [realm/realm-browser-osx](/realm/realm-browser-osx) repository. Would you be so kind as to [re-file this issue against that repository](/realm/realm-browser-osx/issues/new) so that the people that work on the Browser see it?

**Comment by beeender** [comment]
https://github.com/realm/realm-browser-osx/issues/146 realm-browser issue created. close this one.
