### ISSUE TITLE
Are .lock/.log files created by realm safe to be removed manually on app startup?

### ISSUE THREAD

**Issue by diegomontoya** [realm/realm-java#2521]
We would like to implement a manual copy/backup of realm db files within an app either on app startup, before any realm operations, or after ensuring all existing realms have been closed. We want to a non-realm dependent copy/duplicate mechanism since our goal is to auto-recover in case of realm corruption. 

Realm generate .log and .lock alongside db files.  Our question is 

1) Are the .lock files safe to be removed on app startup?
2) Are the .log files safe to be removed on app startup?

Thanks.

**Comment by beeender** [comment]
1) Yes!
2) Yes!

Just make sure to do these before opening any Realm instances, then it will be totally safe.

**Comment by diegomontoya** [comment]
Great!
