### ISSUE TITLE
SharedGroup crash when init realm file.

### ISSUE THREAD

**Issue by rfrost77** [realm/realm-java#2524]
I said once before about this crash, but I still can't reproduce it.

I share crash log below
http://crashes.to/s/6f786c3c97c

The problem line is
```
mRealm = Realm.getDefaultInstance();
```

I hope you solve asap, cause it is most crash now for us, and it gives very bad experience to our users.

**Comment by beeender** [comment]
Is there any chance for you to get a corrupted Realm file for us to analyse?

**Comment by beeender** [comment]
1. Where do you store the Realm file? Internal storage or SD card?
2. Does it happen after you update Realm lib? If yes, from which version to which version?
3. Do you use `Realm.compactRealm()`
4. Which version of Realm are you using now?
5. 
For the other thread, i saw"
```
public static void initialize() {
    if (AppUtil.isDebugMode()) mRealmBuilder.deleteRealmIfMigrationNeeded();
    Realm.setDefaultConfiguration(mRealmBuilder.build());
}
```
Does `AppUtil.isDebugMode()` return true even in the release version of your app?

**Comment by rfrost77** [comment]
1. I did not set file path. Where is your default path? I put Application context to builder.
2. Yes. It happen twice. 0.87.1 -> 0.87.5 and 0.87.5 -> 0.88.2. Now, we use 0.88.2
3. no.
4. 0.88.2
5. Never.

**Comment by beeender** [comment]
@rfrost77 according to https://github.com/realm/realm-java/issues/2402#issuecomment-1943851

You don't have a migration block, then Realm won't be deleted in the release version, right?
So what changes between schema version 1 and schema version 2? And still, how did you handle `MigrationNeededException`?

**Comment by rfrost77** [comment]
At schema 2, I update whole of realm, so I used deleteRealmIfMigrationNeeded() on by BaseApplication class that extends Application, which starts with app launch. Of course, I checked app version, so deleteRealmIfMigrationNeeded() is used only first launch after app version update.

Anyway, I found below crash log in my device while update test, even if this update doesn't change any realm settings than before...

java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/kr.co.rememberapp/app_lib/librealm-jni.so" is 32-bit instead of 64-bit
The line of fire is
```
public static RealmConfiguration.Builder mRealmBuilder = new RealmConfiguration.Builder(BaseApplication.get())
            .name(Realm.DEFAULT_REALM_NAME)
            .schemaVersion(SCHEMA_VERSION)
            .migration(new MigrationRealmUtil());
```

**Comment by beeender** [comment]
> java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/kr.co.rememberapp/app_lib/librealm-jni.so"

Do you have other native libs which has 64bit so and you exclude 64bit realm so from gradle?

===================================================

Can you share you code related with calling `deleteRealmIfMigrationNeeded()`  in the `BaseApplication` class?

**Comment by rfrost77** [comment]
This is my gradle options. I did not set 32bit or 64bit for any other lib.
```
packagingOptions {
        exclude 'META-INF/services/javax.annotation.processing.Processor'
        exclude 'lib/arm64-v8a/librealm-jni.so'
        exclude 'lib/x86_64/librealm-jni.so'

        exclude 'META-INF/NOTICE'
        exclude 'META-INF/NOTICE.txt'
        exclude 'META-INF/LICENSE'
        exclude 'META-INF/LICENSE.txt'
        exclude 'META-INF/DEPENDENCIES'
        exclude 'META-INF/DEPENDENCIES.txt'

        exclude 'NOTICE'
        exclude 'NOTICE.txt'
        exclude 'LICENSE'
        exclude 'LICENSE.txt'
        exclude 'DEPENDENCIES'
        exclude 'DEPENDENCIES.txt'
    }
```

BaseApplication code is below
```
private void migrate() {
    int oldVersion = SessionWrapper.PROPERTY_APP_VERSION_CODE();
    int newVersion = AppUtil.getAppVersionCode();
    if (oldVersion < newVersion) {
        if (oldVersion <= 77) {
            MigrationAppUtil.migrate73TO74();
        }
    }
}

// It is in MigrationAppUtil
private static void migrate73TO74() {
  RealmUtil.mRealmBuilder.deleteRealmIfMigrationNeeded();
}
```

**Comment by beeender** [comment]
You excluded realm's 64bit so by `exclude 'lib/arm64-v8a/librealm-jni.so'` . So if you have any other libs which has 64 bit '.so` file, that exception will be thrown. Since the 64 bit so and 32 bit so cannot be loaded together, and 64 bit so will have a higher priority on 64 bit system. Please check other 3rd party libs if they have any 64 bit so.

==============================================================
It is hard to assemble code pieces into one big picture ... Is it OK for you to share the `BaseApplication.java` and `BaseActivity.java` with us privately? To help@realm.io

**Comment by rfrost77** [comment]
@beeender Sorry for late. I sent mail. I hope you can resolve with our code.

**Comment by beeender** [comment]
Note for easy tracking: https://secure.helpscout.net/conversation/191249881/3766/?folderId=539748

**Comment by rfrost77** [comment]
@beeender I cannot login the site. Which account do I need to login?

**Comment by beeender** [comment]
@rfrost77 Never mind about that. The website is just for us tracking some private information related to the issue. I put it there just to make it easier for us to collect all related information.

**Comment by beeender** [comment]
Some updates: We have been trying to reproduce this crash for many days in all kind of ways, but still no luck :( . Any clue about this would be appreciated.

**Comment by flawyte** [comment]
I have the same problem and it looks like the number of crashes consistently increases every time I upgrade my domain model objects.

The thing is that my app's data comes from an API, so whenever I upgrade my model "schema" objects, I don't provide any migration but I rely on `builder.deleteRealmIfMigrationNeeded();` so app isn't supposed to crash for legacy users but just start from "blank", like if user had removed the app's stored data by himself (at least, that's how I understand it).

So maybe it has something to do with schema changes? BTW, here's the crash log : http://crashes.to/s/15b88716693

**Comment by cmelchior** [comment]
Folding this issue into #3064
