### ISSUE TITLE
Suggested doc clarification on chaining queries

### ISSUE THREAD

**Issue by mikemee** [realm/realm-java#2528]
#### Doc Suggestion:

In the docs section https://realm.io/docs/java/latest/#chaining-queries, just before the end line:

> Read more about link queries.

Add a new paragraph, something like:

> Note that query chains are built on `RealmResults`, not `RealmQuery`. If you add more conditions to an existing `RealmQuery`, then you're modifying that query, not chaining.

#### Goal

I had a "base" query and wanted to chain some others. Reading the docs, because I just wanted counts, I thought I could do this:
```
        RealmQuery<PuzzleState> completedQuery = mRealm
                .where(PuzzleState.class)
                .equalTo(PuzzleState.COMPLETED, true)
                .equalTo(PuzzleState.VOLUME_ID, volumeId);

        int trophyCount = (int) completedQuery.equalTo(PuzzleState.GOT_TROPHY, true).count();
        int noTrophyCount = (int) completedQuery.count() - trophyCount;            
        int unResolvedCount = puzzles.size() - (int) completedQuery.count();

```
#### Expected Results

I thought the above code would give me counts with trophies and counts without.  

#### Actual Results

As I learned, until I "instantiate" (?) the query, subsequent criteria will just add to it. This makes sense, in hindsight. If I hadn't just wanted counts, then I likely would have done a `findAll()` and it all would have worked as expected first time.

I think adding a quick explanation in the docs would make a difference and save others some pain.

Adding a `findAll()` to the query and modifying the return type, got me what I expected, i.e.:

```
            RealmResults<PuzzleState> completedQuery = RealmHelper.getPuzzleStateRealm()
                    .where(PuzzleState.class)
                    .equalTo(StateField.completed, true)
                    .equalTo(StateField.volumeId, volumeItem.getVolume().getId())
                    .findAll();

            int trophyCount = (int) completedQuery.where().equalTo(StateField.fastTime, true).count();
            int noTrophyCount = (int) completedQuery.where().count() - trophyCount;
            int unResolvedCount = puzzles.size() - (int) completedQuery.size();
```

#### Version of Realm and tooling

Realm version(s): 0.88.2

**Comment by beeender** [comment]
Definitely we should doc this. I was confused before as well.

**Comment by derekstavis** [comment]
I got here because I saw lots of examples where people have been replacing the original instance everytime they call methods on `RealmQuery`. As far as I have found, there's no need to do this, so we should definitely make clear it's not needed :+1:

**Comment by stk1m1** [comment]
@mikemee  

Thanks for letting us know. Your point is fully applied on [realm.io](https://realm.io/docs/java/latest/). It will soon be available. 💯
