### ISSUE TITLE
Inconsistent Realm file

### ISSUE THREAD

**Issue by yolapop** [realm/realm-java#2532]
Hi there, I don't know why but my realm file is having inconsistent values.

How to see the realm:
1) Navigate to table `SubCategory` -> (`ProductItem`) `items` and see each of those item attributes.
2) Navigate to table `ProductItem` and see that these have slightly different attributes than the items above. The list here should be the same with `SubCategory`.`items`.

I put the file to dropbox and as soon as you download it, I'm gonna delete it. Please confirm.
https://www.dropbox.com/s/jb6dwog3y6n4lh5/default5.realm?dl=0

Realm version(s): 0.88.2

Android Studio version: 1.5.1

Which Android version and device: Genymotion API 16

**Comment by yolapop** [comment]
I'm sorry, I just checked and they're **consistent**! I can't believe. Maybe my eyes tricked me or it's just some glitch.
I'll confirm once I see further problems.

**Comment by cmelchior** [comment]
Hi @yolapop 
Happy to hear it wasn't a bug after all, please reopen this if you discover something was wrong after all.
