### ISSUE TITLE
Realm.createObject() doesn't respect field values set in default constructor or field declaration

### ISSUE THREAD

**Issue by jonasrottmann** [realm/realm-java#2535]
#### Expected Results

Adding an object to a realm using `Realm.createObject()` should respect the field values set in the default constructor or the value the field is initialized with in the field declaration.

#### Actual Results

Using `Realm.createObject()` adds an object with all fields set to `null`, `0`or `false`.

#### Code Sample

[Code Sample](https://gist.github.com/jonasrottmann/93d632131a0223c95478ea2fdf6aa877)

#### Version of Realm and tooling
Realm version(s): 0.88.2

Android Studio version: 2.1 Preview 4

Which Android version and device: 6.0.1 (MHC19J) on Nexus 5X

**Comment by cmelchior** [comment]
Hi @jonasrottmann 
This sounds very much like the concept of DefaultValues we are tracking here: #777 
I tend to agree that what you are describing here would be a much more natural behaviour, and of the top of my head I cannot see any reason for why we couldn't make it work.

For the sake of brevity I'll fold this issue into #777, so you can follow any progress there.
