### ISSUE TITLE
Calling setter method in no argument constructor results in NPE

### ISSUE THREAD

**Issue by jonasrottmann** [realm/realm-java#2536]
#### Goal

Be able to use setter methods in the no arguments constructor.

#### Expected Results

No NPE and field set to the given value.

#### Actual Results

```
Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'void io.realm.BaseRealm.checkIfValid()' on a null object reference
                                                                                at io.realm.ModelRealmProxy.realmSet$string(ModelRealmProxy.java:62)
                                                                                at de.jonasrottmann.realmtest.Model.setString(Model.java:13)
                                                                                at de.jonasrottmann.realmtest.Model.<init>(Model.java:19)
                                                                                at io.realm.ModelRealmProxy.<init>(ModelRealmProxy.java:51)
                                                                                at io.realm.DefaultRealmModuleMediator.newInstance(DefaultRealmModuleMediator.java:80)
                                                                                at io.realm.BaseRealm.get(BaseRealm.java:521)
                                                                                at io.realm.Realm.createObject(Realm.java:709)
```

#### Code Sample

```java

public class Model extends RealmObject {
    public String string;



    public void setString(String string) {
        this.string = string;
    }



    public Model() {
        setString("Success!");
    }
}

```

#### Version of Realm and tooling
Realm version(s): 0.88.2

Android Studio version: 2.1 Preview 4

Which Android version and device: 6.0.1 (MHC19J) on Nexus 5X

**Comment by cmelchior** [comment]
Hi @jonasrottmann 

I just tried the following which didn't fail:

```
public class DefaultValues extends RealmObject {
    private int age = 42;
    private String name;
    private String address;

    // Default constructor
    public DefaultValues() {
        this.name = "Foo";
        setAddress("Bar");
    }

    public int getAge() {
        return age;
    }

    public void setAge(int age) {
        this.age = age;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getAddress() {
        return address;
    }

    public void setAddress(String address) {
        this.address = address;
    }
}

    @Test
    public void defaultConstructor_standAlone() {
        DefaultValues obj = new DefaultValues();
        assertEquals(42, obj.getAge());
        assertEquals("Foo", obj.getName());
        assertEquals("Bar", obj.getAddress());
    }
```

**Comment by zaki50** [comment]
no...

**Comment by beeender** [comment]
Shall we inject a dummy constructor to the original object during transformer?

**Comment by cmelchior** [comment]
I am playing around with the following idea:

```
Private API:
// New proxy constructor for objects we _known_ will point to native objects
// Perhaps expose this as `createProxyObject` internally. All Proxy classes should use this instead.
public FooProxy(Realm realm, Row row) {
  this.realm = realm;
  this.row = row;
}

// Public API:
// Realm.createObject will be replaced with
Foo obj = mediator.createStandaloneInstance(Foo.class); // To avoid reflection, although mediator is not free either. Should be benchmarked.
return realm.copyToRealm(obj);
```

It will make `createObject` slower since it will now always create a garbage object that is only used to make sure we get all the default values, but it will work I think.

**Comment by beeender** [comment]
but `public FooProxy(Realm realm, Row row)` by default will call `super()`, which potentially calls some setters in the `super()` again, right?

**Comment by cmelchior** [comment]
If you have  a named constructor in a subclass i don't think it calls the default constructor in the super class. I might be wrong though.

**Comment by cmelchior** [comment]
> "Effective Java 2nd Edition, Item 17: Design and document for inheritance, or else prohibit it: Constructors must not invoke overridable methods, directly or indirectly."

Not that it is going to help us though :unamused:

**Comment by beeender** [comment]
Well, that is not an real excuse :disappointed:  by doing `this.name = "abc"` will generate the same issue.

**Comment by cmelchior** [comment]
Looking at bit further into this. It appears that trying to remove the `super()` call in the byte code will cause the JVM to throw errors as well, so this is getting a bit tricky.

A potential solution could be to just wrap all getters/setters in:

```
if (realm != null) {
  // Default impl
}
```

It would be slightly annoying, but I am not sure if the impact would be measurable at all. It would still have to be combined with the above approach as we need to separate between proxy instances and standalone instances.

Another approach might be to inject a dummy constructor through the RealmTransformer in the standalone class, but then we would have to modify the Proxy classes as well to actually use that constructor
```
public class Foo extends RealmObject  implements FooRealmProxyInterface<Foo> {

  // Dummy constructor created by JavaAssist. Need to create a constructor that doesn't class with anything a user might create, Generics are removed at compile time, so it will be tricky :(
  public Foo(Class<FooRealmProxy> ignore) {
  }

FooRealmProxy
// All calls to new Foo() should be replaced with:
new Foo(this)
```

**Comment by cmelchior** [comment]
Another crazy idea: 

Okay, crazy idea:

1) Extend the autogenerated class with 3 extra methods:

```
setColumnInfo$realmSet(info);
setProxyState$realmSet(state);
init$realm();
```

2) Let JavaAssist create a new constructor in the model class

```
public DefaultValues(ColumnInfo info, ProxyState state) {
    setColumnInfo$realmSet(info);
    setProxyState$realmSet(state);
    init$realm();
}
```

3) Let JavaAssist implement the `init()` method by copying all the constructor logic from the default constructor.
According to http://stackoverflow.com/questions/14805547/are-fields-initialized-before-constructor-code-is-run-in-java, this
will also include all fields initializers.

The complexity of this is unknown.

```
public class DefaultValues() {
	String foo = "foo";
	int bar = getBar(42);

	// Default constructor
	public DefaultValues() {
		doFunnyStuff();
	}
}

public void init$realm() {
	setFoo$realmSet("foo");	// Set field directly. Replaced by other transform logic
	setBar$realmSet(getBar(42)); // Standard method calls
	doFunnyStuff(); // Method called from default constructor.
}
```


4) Let JavaAssist manipulate the constructor of the DefaultValuesRealmProxy class, so it now calls the generated one:

````
// Current
public DefaultValuesRealmProxy(ColumnInfo info) {
	this.info = info;
	this.proxyState = new ProxyState(DefaultValues.class, this);
}

// New visible one
public DefaultValuesRealmProxy(ColumnInfo info) {
	// This will be replaced with super(info, new ProxyState(DefaultValues.class, this));
}

// Constructor after transform has run
public DefaultValuesRealmProxy(ColumnInfo info) {
	super(info, new ProxyState(DefaultValues.class, this));
}

// Also implement thise methods
public void setColumnInfo$realmSet(info) {
	this.info = info;
};

public void setProxyState$realmSet(state) {
	this.proxyState = state;
};
```

Advantages
- Would allow standard behaviour for defining default values for fields (Big Win!).
- Default values would not be baked into the Schema. This is not the case for Realm Swift/Objective C either currently.

Disadvantages:
- Still not sure how easy it is to copy method content.
- Hard to debug
- The level of black magic is .... concerning.
- Yet more generated methods.

This will not be possible for 0.91.0 though, so de-prioritizing this for now. We should document it instead for now.

**Comment by Zhuinden** [comment]
Can't you just add an annotation similar to `@PostConstruct` in Spring which would be called from the proxy constructor if the annotation exists?

**Comment by cmelchior** [comment]
Yes, that would also be an option, but if possible we would like to stay as close to a normal Java object as possible.

**Comment by Zhuinden** [comment]
Actually, that wouldn't even work with the vanilla `Something something = new Something();` unless you transform this call everywhere AND when it's created via reflection for the proxies
