### ISSUE TITLE
Support android experimental plugin

### ISSUE THREAD

**Issue by beeender** [realm/realm-java#2539]
Question from SO: http://stackoverflow.com/questions/36341822/run-realm-with-android-experimental-plugin

What could be fixed in our side:
in 'gradle-plugin/Realm.groovy` check through the plugin name instead of the class.

```
def isAndroidApp = project.plugins.hasPlugin("com.android.application") ||
                project.plugins.hasPlugin("com.android.model.application") // Android experimental plugin
def isAndroidLib = project.plugins.hasPlugin("com.android.library") ||
                project.plugins.hasPlugin("com.android.model.library") // Android experimental plugin
```

However, it will still fail because of the `AndroidAptPlugin` doesn't support Android experimental plugin yet, see issue https://bitbucket.org/hvisser/android-apt/issues/46/support-for-experimental-plugin

**Comment by cmelchior** [comment]
Perhaps we should document this under Current limitations on the website until we get this fixed?

**Comment by masterjefferson** [comment]
Heads up, I have been using [this plugin](https://bitbucket.org/pvoid/android-apt-experemental/overview) as a replacement for apt when using the android experimental plugin, and it does work. I have only used it in conjunction with butterknife so far though. 

I'd really like to see this fixed, as our build includes a *lot* of C/C++ code and the experimental plugin is a must have.

**Comment by beeender** [comment]
@masterjefferson Just curious, what is the special reason you want to use the experimental plugin? For NDK project? There are other choices now like the the ndk with cmake which doesn't require the experimental plugin https://github.com/googlesamples/android-ndk/tree/master-cmake/hello-jni .

And we tried it, it works great! https://github.com/realm/realm-java/pull/2960

**Comment by masterjefferson** [comment]
@beeender Thanks for the heads up on that! I must have missed that update somehow. I'll update our build and give it shot.

**Comment by Zhuinden** [comment]
@beeender wait, how would you make the `realm-android` Gradle plugin run with `cmake`?

**Comment by beeender** [comment]
@Zhuinden check this branch https://github.com/googlesamples/android-ndk/tree/master-cmake , lots of fun

**Comment by Zhuinden** [comment]
@beeender yeah I've just figured it out that that's there too :smile: 

This seems to be a way better alternative than the "experimental plugin" which breaks every Gradle version update and doesn't work with anything.

Thanks for the info :+1:

**Comment by cmelchior** [comment]
Probably not as relevant with CMake now being officially supported, but keeping it open just in case.

**Comment by cmelchior** [comment]
I think we can safely close this. For all intents and purposes, the experimental plugin seems dead: http://tools.android.com/tech-docs/new-build-system/gradle-experimental

**Comment by josmad** [comment]
It still receives fairly regular updates:

https://bintray.com/android/android-tools/com.android.tools.build.gradle-experimental/view

They were always terrible at keeping the wiki up-to-date

**Comment by Zhuinden** [comment]
@josmad well how do they expect people to use it if they don't update their docs?

I haven't seen anything that would support the experimental plugin, CMake is better and officially supported.
