### ISSUE TITLE
toString

### ISSUE THREAD

**Issue by alfaro28** [realm/realm-java#2545]
#### Goal

override toString

#### Expected Results

toString to return my custom string

#### Actual Results

my custom method is not being called and the default realm toString implementation is shown

#### Steps & Code to Reproduce

create custom object, override toString

#### Version of Realm and tooling
Realm version(s): 0.88.2

Android Studio version: 1.5.1

Which Android version and device: Icecream,  Samsung S3

**Comment by fobid** [comment]
I resolved this issue with custom method. But it's bothering me to create custom, it has too many fields..

**Comment by dalinaum** [comment]
Hello @alfaro28 and @fobid. I just reproduced this issue. It is a bug. We will investigate this issue.

**Comment by alfaro28** [comment]
@fobid I'm using my object in an ArrayAdapter so I can't use that workaround, @dalinaum thanks

**Comment by dalinaum** [comment]
I just made a simple patch #2554. It will resolve this issue.

**Comment by dalinaum** [comment]
#2554 just merged into 0.88.3 and it will be released soon.
