### ISSUE TITLE
RealmSchema.remove() doesn't clear primary key metadata

### ISSUE THREAD

**Issue by kkmike999** [realm/realm-java#2555]
There is `User` table in APP version 1.0: 
```
@Table(name="User1")
public class User extends RealmObject {

    @PrimaryKey
    public int    uid;

    @Required
    public String name;
}
```

In APP version 2.0, add a field `age`:
```
@Table(name="User2")
public class User extends RealmObject {

    @PrimaryKey
    public int    uid;

    @Required
    public String name;

    public int    age;
}
```

I usually **change** `User` **table name** in version 2.0 by changing **annotation**. i don't want to call `addField` or `removeField`. If the requirement changes every version，i have to write code in Migration every time i change User<br/>

So, i run such code:
```
RealmConfiguration config = new RealmConfiguration.Builder(getApplicationContext()).build();

Realm realm = Realm.getInstance(config);

realm.beginTransaction();
realm.getSchema().remove("User");
realm.commitTransaction();

realm.beginTransaction();
realm.copyToRealmOrUpdate(user);
```

And then, throws exception:
```
E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.example.realm, PID: 26909
java.lang.IllegalArgumentException: A RealmObject with no @PrimaryKey cannot be updated: class com.example.realm.bean.User
at io.realm.Realm.checkHasPrimaryKey(Realm.java:1411)
at io.realm.Realm.copyToRealmOrUpdate(Realm.java:764)
at com.example.realm.MainActivity.testTable(MainActivity.java:72)
```

**Comment by cmelchior** [comment]
You can use `RealmSchema.rename()`: https://realm.io/docs/java/latest/api/io/realm/RealmSchema.html#rename-java.lang.String-java.lang.String-

**Comment by cmelchior** [comment]
Also note that Realm doesn't support the `@Table` annotation

**Comment by kkmike999** [comment]
First run,`schemaVersion(0)` and `realm.copyToRealmOrUpdate(user);`.
Next time run such code:
```
RealmConfiguration config = new RealmConfiguration.Builder(getApplicationContext()).schemaVersion(1)
		                                                                   .migration(new UserMigration())
		                                                                   .build();

Realm realm = Realm.getInstance(config);
```

```
private class UserMigration implements RealmMigration {
	@Override
	public void migrate(DynamicRealm realm, long oldVersion, long newVersion) {
		RealmSchema schema = realm.getSchema();

		if (newVersion > oldVersion) {
			if (schema.contains("User")) {
				schema.rename("User", "User_" + System.currentTimeMillis());

				if (!schema.contains("User")) {
					RealmObjectSchema userSchema = schema.create("User");

					userSchema.addField("uid", Integer.class);
					userSchema.addField("name", String.class);
				}
			}
		}
	}
}
```

when calling `migrate` every thing is fine. After that, throws 
```
Process: com.example.realm, PID: 25862
io.realm.exceptions.RealmMigrationNeededException: Field 'uid' does support null values in the existing Realm file. Use corresponding boxed type for field 'uid' or migrate using io.realm.internal.Table.convertColumnToNotNullable().
    at io.realm.UserRealmProxy.validateTable(UserRealmProxy.java:117)
    at io.realm.DefaultRealmModuleMediator.validateTable(DefaultRealmModuleMediator.java:57)
    at io.realm.Realm.initializeRealm(Realm.java:315)
    at io.realm.Realm.createAndValidate(Realm.java:283)
    at io.realm.Realm.createInstance(Realm.java:262)
    at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:114)
    at io.realm.Realm.getInstance(Realm.java:213)
    at com.example.realm.MainActivity.testTable(MainActivity.java:66)
    ...
```

**Comment by beeender** [comment]
@kkmike999 I think there is a misunderstanding of this.

First, `@Table` won't has any impact there since Realm doesn't support that annotation. Second, the schema name of the Object in the storage is decided by the `RealmObject`'s class name. eg.: For `public class User extends RealmObject`, Realm expects a schema named `User` in the storage. if the db file doesn't exist, Realm will create a schema named `User` otherwise it will throw a `MigrationNeededException` if the schema doesn't exist.

So in your migration block, `schema.rename("User", "User_" + System.currentTimeMillis());` is kind of strange since you won't have a model class named like `User_current_time_in_millis`.

For you user case, you need to first change the class name `User` to something like `UserV2`, then create a migration block for it. But, be honest, I don't see any necessity to do that. That also means you need to change the class everywhere when accessing the `User` Object.

**Comment by kkmike999** [comment]
@beeender i just want a simple case: `Drop table` when `schemaVersion` upgrade, and `Create` it again. i write 'rename' code to satisfy this case. i don't really want to change table name.

**Comment by cmelchior** [comment]
Hi @kkmike999 
Dropping and creating a table again is just equivalent to clearing it. In that case you can just do `realm.clear("User")/realm.delete("User")` depending on what version of Realm you are using

**Comment by kkmike999** [comment]
@cmelchior 1.there is no `realm.delete("User")` API;  2.`realm.clear("User") ` is smilier to sql `DELETE FROM table_name`, but not 'Drop table'. After `realm.clear ` `User v1`'s fields still in schema, so calling `realm.copyToRealmOrUpdate(User v2)` still has problem.

**Comment by cmelchior** [comment]
@kkmike999 It would help if you explained _why_ you want remove the UserV1 data?

Note that if it is because you don't want to write any migration code you can just use `RealmConfiguration.deleteRealmIfMigrationRequired()`. That way all your tables are DROP'ed and CREATE'ed again if a migration was needed.

**Comment by kkmike999** [comment]
@cmelchior If `User` table change every version in my APP , so that i should write `addField` `removeField` every time in `Migration`.  If i `Drop User` and `Create User`, i wirte much less code. 

i try to call `remove(User)` ,but after calling 
```
RealmObjectSchema userSchema = schema.create("User");

userSchema.addField("uid", Integer.class);
userSchema.addField("name", String.class);
```
throws 
```
io.realm.exceptions.RealmMigrationNeededException: Field 'uid' does support null values in the existing Realm file. Use corresponding boxed type for field 'uid' or migrate using io.realm.internal.Table.convertColumnToNotNullable().
    at io.realm.UserRealmProxy.validateTable(UserRealmProxy.java:117)
    at io.realm.DefaultRealmModuleMediator.validateTable(DefaultRealmModuleMediator.java:57)
    at io.realm.Realm.initializeRealm(Realm.java:315)
    at io.realm.Realm.createAndValidate(Realm.java:283)
    at io.realm.Realm.createInstance(Realm.java:262)
    at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:114)
    at io.realm.Realm.getInstance(Realm.java:213)
    at com.example.realm.MainActivity.testTable(MainActivity.java:66)
```

**Comment by cmelchior** [comment]
I don't see why you end up writing less code that way. You still need to manually specify all the fields for the the new User class.

The reason you are getting the error is because there is a difference between `Integer` and `int`. Your migration should be this:

```
RealmObjectSchema userSchema = schema.create("User");
userSchema.addField("uid", int.class, FieldAttribute.PRIMARY_KEY);
userSchema.addField("name", String.class);
userSchema.addField("age", int.class);
```

**Comment by kkmike999** [comment]
@cmelchior 
If i use `remove` and `create`, i just need to add all fields in current version, no need to know what field in last version and call `remove` field or check field is exist then not to add.

---
```
if (schema.contains("User")) {
	schema.remove("User");

	if (!schema.contains("User")) {
		RealmObjectSchema userSchema = schema.create("User");

		Set<String> set = userSchema.getFieldNames();

		userSchema.addField("uid", int.class, FieldAttribute.PRIMARY_KEY);
		userSchema.addField("name", String.class, FieldAttribute.REQUIRED);

	}
}
```
`set` size is `0`, when calling `userSchema.addField("uid", int.class, FieldAttribute.PRIMARY_KEY);` throws 
```
java.lang.IllegalStateException: A primary key is already defined
at io.realm.RealmObjectSchema.addPrimaryKey(RealmObjectSchema.java:303)
at io.realm.RealmObjectSchema.addModifiers(RealmObjectSchema.java:455)
at io.realm.RealmObjectSchema.addField(RealmObjectSchema.java:151)
```
T_T

**Comment by cmelchior** [comment]
Hmm, I think that is a bug from our side. It looks like calling `remove("User")` doesn't clear the primary key definition.

Try 
```
schema.get("User").removePrimaryKey();
schema.remove("User");
RealmObjectSchema userSchema = schema.create("User");
userSchema.addField("uid", int.class, FieldAttribute.PRIMARY_KEY);
userSchema.addField("name", String.class);
userSchema.addField("age", int.class);

```

**Comment by kkmike999** [comment]
@cmelchior i'll try tomorrow. it's 1:14am in China @_@. Thank you for patiently answering my question .

**Comment by kneth** [comment]
@kkmike999 Did you have a chance to try what @cmelchior suggest?
