### ISSUE TITLE
Use `RealmResults.addChangeListener()` in RealmBaseAdapter

### ISSUE THREAD

**Issue by beeender** [realm/realm-java#2560]
1. Make a way to add WeakRef of change listeners to `RealmResults`, and generalize it as a public API. User might need it as well for their own public Api.
2. Subscribe to `RealmResults` instead of `Realm` to avoid false positive notifications in the `RealmBaseAdapter`
3. Check if we can do the same to `RealmList`.

**Comment by cmelchior** [comment]
Ideally we probably want to add it to the OrderedRealmCollection API, but right now no ChangeListeners are supported for RealmList. Maybe we should just fold this into #989 ?

**Comment by beeender** [comment]
yep
