### ISSUE TITLE
ReamChangeListener not fired between Activity Transitions

### ISSUE THREAD

**Issue by WanClem** [realm/realm-java#2571]
Respect to the Realm Engineers,your framework is powerful....I replaced my entire sqlite based app with realm and the query speed is what baffles me....blazing fast!!! However,am having issues with the RealmChangeListener....I have two activities,Activity A and B....Activity A contains a username textview that is updated via a username textfield in Activity B.When I enter a new username in the username field in Activity B and return to Activity A,realm change listener is not fired,hence my Username TextView even after calling invalidate doesnt get the new value of the updated RealmObject via the edittext in Activity B....Any work around please??? Thanks......

**Comment by cmelchior** [comment]
Hi @WanClem 
Can you please post the code of your activities?

**Comment by kneth** [comment]
@WanClem Did you solve the issue? Or can you post the activities? [StackOverflow](http://stackoverflow.com/questions/tagged/realm) might be a better place to post this question.
