### ISSUE TITLE
Date field is not saved correctly

### ISSUE THREAD

**Issue by GaborPeto** [realm/realm-java#2572]
From documentation :

> Realm supports the following field types: boolean, byte, short, ìnt, long, float, double, String, Date  and byte[]

Given a class that has a Date field and extends RealmObject when saving an instance than retrieving it produces different date instances.

I have written a project to demonstrate this with test. You can have a look at: https://github.com/GaborPeto/realm-date-field-test

The test in the project fails with the following error
java.lang.AssertionError: expected:<1460205711757> but was:<1460205711000>

**Comment by cmelchior** [comment]
As described here: https://realm.io/docs/java/latest/#current-limitations, Realm currently only support dates with a precision of seconds. We are currently implementing proper millisecond precision though and progress can be tracked here: #833
