### ISSUE TITLE
Make Realm Schemaless like Good Old Parse(RIP)...

### ISSUE THREAD

**Issue by WanClem** [realm/realm-java#2573]
Nice Work Realm Engineering Team,Realm is indeed cool..However,we need a Schemaless database...Keeping track of schemeVersions is too hardwired(AKA RealmMigration)...To be a true variance from the likes of Sqlite and Core Data means not doing what they're doing....Realm WOULD definitely be the future of mobile database from its speed and ease of use which is cool.But would be far more cooler without keeping track of schemeVersions...I know u guys can do this....Thanks and Thumbs up for the good work...

**Comment by cmelchior** [comment]
Hi @WanClem 
Realm is not a schemaless database at its core, and that isn't going to change. For arguments why schemaless is generally a bad idea, see http://martinfowler.com/articles/schemaless/

If you don't want to tackle migrations you have the option of using `RealmConfiguration.deleteRealmIfMigrationRequired()`. Of course the downside is that all data will be deleted. So depending on your use case that might not be acceptable.
