### ISSUE TITLE
createQueryFromList io.realm.internal.TableQuery io.realm.internal.LinkView.where()' on a null object reference

### ISSUE THREAD

**Issue by hay12396** [realm/realm-java#2574]
Hello,

When im trying to run the following code:

```
Realm realm = Realm.getDefaultInstance();
        RealmList<RealmItem> list = new RealmList<>();

        RealmResults<RealmWish> myWishes = realm.where(RealmWish.class).equalTo(Constants.WISHER_ID, id).findAll();


        for (RealmWish w : myWishes) {
            RealmItem item = realm.where(RealmItem.class).equalTo(Constants.ID_COLUMN, w.getItemId()).findFirst();
            if(item!= null)
                list.add(item);
        }


        RealmResults<RealmItem> results = RealmQuery.createQueryFromList(list).findAll();
        realm.close();
        return results;
```

I'm receiving this error:

> java.lang.NullPointerException: Attempt to invoke virtual method 'io.realm.internal.TableQuery io.realm.internal.LinkView.where()' on a null object reference
                                                                    at io.realm.RealmQuery.<init>(RealmQuery.java:178)
                                                                    at io.realm.RealmQuery.createQueryFromList(RealmQuery.java:128)

I'm sorry if the problem is just me not using realm as i should, but i can't seem to find what the problem is..

The "createQueryFromList" line is what throw this exception.

With regards,
Hay.

**Comment by cmelchior** [comment]
You cannot create a query from an un-managed RealmList, but the error message could be a bit clearer about that.

Any particular reason you are trying to convert a RealmList to a RealmResults?

**Comment by hay12396** [comment]
I needed to do something like this:http://stackoverflow.com/questions/36535030/realmresults-to-realmlist

But i managed to get a walkaround by creating a realmquery and add an ”equalTo” rule to the query on each iteration.

This issue can be closed as i didn`t know that the realmlist had to be managed.

With regards,
Hay.

**Comment by beeender** [comment]
@hay12396 We added something called `RealmCollection` in the next major release. You can see this PR for more details https://github.com/realm/realm-java/pull/2345 It might be helpful for your case.

I am closing this issue now. Thanks for the feedback!
