### ISSUE TITLE
Realm transactions times.

### ISSUE THREAD

**Issue by HectorFGarcia** [realm/realm-java#2576]
I'm testing Realm on a old device. It's a **Honeywell E70 (1Ghz singlecore, 512Mb, Android 4.0.3)** and the results surprised me a little bit.

Saving _20.186_ objects:

**Regular transaction**
 ```
   realm.beginTransaction();
   // Unicorns and other stuff
   realm.commitTransaction();
```

_~12 seconds_

**Transaction block**
```
realm.executeTransaction(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {
                // More unicorns and stuff
            }
        });
```

_~9 seconds_

**Async transaction block**
```
realm.executeTransactionAsync(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {
                // Happy puppies and stuff
            }
        });
```

_~15 seconds_

------------------------

So the obvious question is... how can be the async transaction the slowest? What I'm missing? It's related to the singlecore device or the 4.0.3 Android version?

**Comment by cmelchior** [comment]
The regular transaction and transaction block is essentially the same underlying code. You should definitely not see 25% difference between the two. 

The async transaction is running on a background thread, so the reason it is slower is probably just the thread scheduler, but it might also just be your variance being that high.

**Comment by HectorFGarcia** [comment]
I'll run more tests then to be sure that those times are not a 'one day thing'.

Any suggestion about what can I do is welcome.

**Comment by cmelchior** [comment]
Batch insert benchmarks are inherently very prone to interference from the GC, so they can be really unpredictable. For those cases it is really important running the tests many times and picking the median value.

**Comment by stk1m1** [comment]
@HectorFGarcia  
Any progress on your end?

**Comment by HectorFGarcia** [comment]
@stk1m1 no, sorry, I couldn't test it yet. I'm working on another project wich needs to be done in the next weeks, so I'll need to wait until May to run tests on this.

**Comment by stk1m1** [comment]
Hi @HectorFGarcia,

Would you mind reopening this case then? Although we can sit down and speculate various aspects of codebase for performance measurements, it would be much nice to take a look at the cases with a tangible project.

**Comment by HectorFGarcia** [comment]
Sure, no problem. Closed until then.

**Comment by GokhanArik** [comment]
I am having the same issue. I am parsing 1MB JSON Array that has 425 elements and adding them to Realm using copyToRealmOrUpdate method. My for loop is inside the Transaction so Realm is using only one thread. I don't have exact numbers but when I use async transaction it takes 2-3 minutes. Using the old method, it takes 30 seconds or so.

My assumption is that the thread executeTransactionAsync is somehow slower than main thread.
