### ISSUE TITLE
添加了realm，运行的时候出现错误了

### ISSUE THREAD

**Issue by gogooing** [realm/realm-java#2577]
/Users/apple/三秋的思想/sanqiu/sanqiu/app/build/intermediates/exploded-aar/com.wnafee/vector-compat/1.0.5/res/drawable/ic_stop_vector.xml
Error:Error: error in parsing "g/"
:app:mergeDebugResources FAILED
Error:Execution failed for task ':app:mergeDebugResources'.
> /Users/apple/三秋的思想/sanqiu/sanqiu/app/build/intermediates/exploded-aar/com.wnafee/vector-compat/1.0.5/res/drawable/ic_stop_vector.xml: Error: error in parsing "g/"

出现上面的这个错误。

**Comment by beeender** [comment]
看起来好像 `ic_stop_vector.xml` 里有个语法错误。不过错误看起来跟 Realm 没什么关系？

**Comment by gogooing** [comment]
好像是的，具体是Not recognizing known sRGB profile that has been edited 造成的，但是不明白为什么在没有添加realm的时候允许不会出错。

**Comment by beeender** [comment]
问题解决了吧？那我先关哈。如果仍然觉得跟 Realm 有关你可以重新打开这个问题。
谢谢！
