### ISSUE TITLE
Complex query

### ISSUE THREAD

**Issue by Litun** [realm/realm-java#2582]
#### Query

I want to use sort in this way:
`chat.sort("messages.findFist.createDate");`,
where `messages` is `List`.

#### How it have to work

- make string representation of the query like `messages.findFist.createDate`
- make `sort(RealmQuery)` 

#### Participation

I'm ready to participate in implementation with the mentoring of realm developer.

**Comment by cmelchior** [comment]
Hi @Litun 
I think the feature you are looking for is already being tracked here #672 
Unfortunately it require changes to the underlying core database, so it isn't as easy as it looks.

I'll close this as an duplicate, but you can follow progress in #672
