### ISSUE TITLE
RealmChangeListener, pop up the changed realmobject?

### ISSUE THREAD

**Issue by hay12396** [realm/realm-java#2592]
Hello,

So im holding list of items (as realmresults) in my recyclerview.
when the user enters the app, the application pull items from the server, that might change the existing items.

as a result, when setting "addchangelistener" to the realmresults, im getting unwanted behavior where all of the items keep getting refreshed few times each second untill all of the data has been downloaded and saved locally. 
(it causes the item preview image to be reloaded and reloaded my users notice that)

It would be very nice if i could get the item that was changed via the realmchangelistener so i would update a specific view inside the recyclerview instead of updating all of the views everytime.

With regards,
Hay.

**Comment by cmelchior** [comment]
@hay12396 Yes, we fully agree and that feature is already being tracked here #989. I'll close this as an duplicate, but you can follow progress in #989
