### ISSUE TITLE
Realm causing issues with other .so files. 

### ISSUE THREAD

**Issue by pingothedoer** [realm/realm-java#2600]
I have implemented PJSUA2 in my application which has an `.so` file in *jniLibs\armeabi\* folder. If I remove the realm installation from project build.gradle and module build.gradle files, then the `.so` file loads perfectly but if I use realm, I am getting the following error. 

`
java.lang.UnsatisfiedLinkError: com.android.tools.fd.runtime.IncrementalClassLoader$DelegateClassLoader[DexPathList[[dex file "/data/data/com.xxxx.xxxx/files/instant-run/dex/slice-support-annotations-23.2.1_362111e3327434c6a1cad3858b3c82a684410db2-classes.dex", dex file "/data/data/com.xxxx.xxxx/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/com.xxxx.xxxx/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/com.xxxx.xxxx/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/com.xxxx.xxxx/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/com.xxxx.xxxx/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/com.xxxx.xxxx/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/com.xxxx.xxxx/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/com.xxxx.xxxx/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/com.xxxx.xxxx/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/com.xxxx.xxxx/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/com.xxxx.xxxx/files/instant-run/dex/slice-realm-annotations-0.88.3_545d7c1189cc453f198d46641b50ade627318538-classes.dex", dex file "/data/data/com.xxxx.xxxx/files/instant-run/dex/slice-mail_358cb6d2e2bfe3abb9a56b5e09839ea13f9c903d-classes.dex", dex file "/data/data/com.xxxx.xxxx/files/instant-run/dex/slice-libphonenumber-7.2.7_b2ce6bdb896ce0e7511afbaff89828225e4a4ed4-classes.dex", dex file "/data/data/com.xxxx.xxxx/files/instant-run/dex/slice-junit-4.12_8bd64565bc4948ad5ca2045e84501ee91a0d32de-classes.dex", dex file "/data/data/com.xxxx.xxxx/files/instant-run/dex/slice-io.realm-realm-android-library-0.88.3_623f32694e5c6f64f853ef8cb913325f9b782439-classes.dex", dex file "/data/data/com.xxxx.xxxx/files/instant-run/dex/slice-internal_impl-23.2.1_281e45eeb9447eef33d0dc71a6b3ca744c8ba7e7-classes.dex", dex file "/data/data/com.xxxx.xxxx/files/instant-run/dex/slice-httpmime-4.2.1_e0f5d97b226bbf3cada0db702c445a4d67ccd1b2-classes.dex", dex file "/data/data/com.xxxx.xxxx/files/instant-run/dex/slice-hamcrest-core-1.3_437627c9702de8eeb7e17b08299a3fedaca2badc-classes.dex", dex file "/data/data/com.xxxx.xxxx/files/instant-run/dex/slice-gson-2.3.1_8571fe5640caaf50855921f71c8043a747e0bc01-classes.dex", dex file "/data/data/com.xxxx.xxxx/files/instant-run/dex/slice-gson-2.2.4_6a63f46ee0c13d997619df937672fb2920f03708-classes.dex", dex file "/data/data/com.xxxx.xxxx/files/instant-run/dex/slice-crashlytics_e49e8a95cdbdbd9bebdb9b1357aff352536864ba-classes.dex", dex file "/data/data/com.xxxx.xxxx/files/instant-run/dex/slice-commons-io-2.4_e224d30efb8880a0541f9756db3ab0f9b7980b0b-classes.dex", dex file "/data/data/com.xxxx.xxxx/files/instant-run/dex/slice-com.nexmo-verify-1.0.1_cd4a3cc975fddbbb575fa6b547072e2161516773-classes.dex", dex file "/data/data/com.xxxx.xxxx/files/instant-run/dex/slice-com.makeramen-roundedimageview-2.2.1_46d131cdfed35e4a7018bd57425cfc641ddfe605-classes.dex", dex file "/data/data/com.xxxx.xxxx/files/instant-run/dex/slice-com.google.android.gms-play-services-gcm-7.8.0_301a32ed9b03e6f63ceb114073f78f3619ce6ba2-classes.dex", dex file "/data/data/com.xxxx.xxxx/files/instant-run/dex/slice-com.google.android.gms-play-services-base-7.8.0_b8b6df7518af8cf95a099252f8e9717c521121f1-classes.dex", dex file "/data/data/com.xxxx.xxxx/files/instant-run/dex/slice-com.android.volley-volley-1.0.0_c520da1f78cc7e09764cefaaf779f40c2ea004a1-classes.dex", dex file "/data/data/com.xxxx.xxxx/files/instant-run/dex/slice-com.android.support-support-vector-drawable-23.2.1_0eb293a065398a508e001b028e43a82502ad64ac-classes.dex", dex file "/data/data/com.xxxx.xxxx/files/instant-run/dex/slice-com.android.support-support-v4-23.2.1_cf1e51f8ae1763e63685e8f45f29bf2e530d6b07-classes.dex", dex file "/data/data/com.xxxx.xxxx/files/instant-run/dex/slice-com.android
`
*I really want to use Realm, so please help me escape this issue. Thnx. *

**Comment by beeender** [comment]
It might be related with https://realm.io/docs/java/latest/#couldnt-load-librealm-jniso

Try to exclude other platform so as it is described in the doc :)

**Comment by kneth** [comment]
@pingothedoer I don't know PSJUA2 (I just looked it up), so I have a few questions:

* Do you build PSJUA2 yourself or do you use a precompile version?
* How do you include it in your Gradle setup?

Realm does support a broad range of architectures, including 64 bit ARM. If you include only a 32 bit ARM version of PSJUA2, the Android package system will still install Realm for 64 bit ARM on a 64 bit device, and you will get linker errors when the app starts. Please take a look at https://realm.io/docs/java/latest/#faq section "Couldn't load librealm-jni.so".

**Comment by pingothedoer** [comment]
thnx @kneth , I am making(generating .so) PJSUA2 myself and currently its only armeabi folder, not for v7a. And I am adding it by just making a jniLibs folder.

**Comment by pingothedoer** [comment]
Adding the following lines didn't help

` packagingOptions {
        exclude "lib/arm64-v8a/librealm-jni.so"
    }
`

**Comment by kneth** [comment]
@pingothedoer Try to use the APK split and only include ARM.

**Comment by pingothedoer** [comment]
Sorry @kneth  but I didn't get your last point?

**Comment by kneth** [comment]
@pingothedoer Since you are only building for a single architecture, you could either exclude all other architectures using `packagingOptions` *or* you could split your app. Splitting an app will leave your with an APK for each architecture. Moreover, you could specify that you only wish to create an APK for ARM.

If it is possible, can you provide a demo project which can reproduce the error? If so, we can take a look and learn a bit about including multiple `.so` files :-)

**Comment by pingothedoer** [comment]
@kneth , that will be very helpful. thnx. Where can I send you that demo ?

**Comment by kneth** [comment]
You can send it to help@realm.io

**Comment by pingothedoer** [comment]
@kneth , I have sent the demo on the email u cited above. Thnx alot

**Comment by kneth** [comment]
Got it. Thanks.

**Comment by pingothedoer** [comment]
Hello @kneth , did you find anything ? I have tried using *armeabi* and *armeabi-v7a* for PJSUA2. but still it clashes with realm.

**Comment by kneth** [comment]
@pingothedoer I have spent some time today. At first, I got the same error but then I disabled Instant Run and got a build error. Cleaning my build and reenable Instant Run and the app is working.

**Comment by pingothedoer** [comment]
also by adding this too :
`packagingOptions { exclude "lib/arm64-v8a/librealm-jni.so" } `
???

**Comment by kneth** [comment]
No, just using your app as it is.

**Comment by kneth** [comment]
@pingotjedoer Did you have any progress on this?

**Comment by pingothedoer** [comment]
@kneth , I followed the procedure you mentioned and it worked only the first time. I tried a lot but I couldn't solve so I had to use SQLite

**Comment by kneth** [comment]
@pingothedoer It's a bit strange that it only worked once. I'll leave the issue open so we don't to forget it.

**Comment by pingothedoer** [comment]
Actually the issue is, Why would I have to switch on and off the instant run every time. Cleaning the project did helped only once. Before the new update of Realm to include in project level build.gradle, it was easy to manage, why its becoming more difficult day by day. Every other dependency is working great whether they are included in project level build.gradle or app level.

**Comment by kneth** [comment]
@pingothedoer I hear what you say. We had added more complexity to our library over time. Today, Realm includes code in Java and C++, an annotation processor and a byte code transformer. We strongly believe that these components make it easier for developers to get to quickly to the market with their apps.

Instant Run has been a bit buggy, and I can't provide an explanation why and when Android Studio will behave as excepted. Just a few Instant Run bug reports:

* https://code.google.com/p/android/issues/detail?id=195062
* https://code.google.com/p/android/issues/detail?id=200635
* https://code.google.com/p/android/issues/detail?id=206627

**Comment by pingothedoer** [comment]
@kneth, is there any possibility you will modify the inclusion procedure of realm?
