### ISSUE TITLE
ExceptionInInitializerError in some devices

### ISSUE THREAD

**Issue by mihirjoshi21** [realm/realm-java#2606]
Caused by java.lang.ExceptionInInitializerError
io.realm.internal.SharedGroupManager. (SharedGroupManager.java:43)
io.realm.BaseRealm. (BaseRealm.java:76)
io.realm.Realm. (Realm.java:126)
io.realm.Realm.createAndValidate (Realm.java:246)
io.realm.Realm.createInstance (Realm.java:231)
io.realm.RealmCache.createRealmOrGetFromCache (RealmCache.java:114)
io.realm.Realm.getDefaultInstance (Realm.java:181)
com.conem.app.pocketthesaurus.display.ActivitySplash$1.doInBackground (ActivitySplash.java:58)
com.conem.app.pocketthesaurus.display.ActivitySplash$1.doInBackground (ActivitySplash.java:52)
android.os.AsyncTask$2.call (AsyncTask.java:287)
java.util.concurrent.FutureTask$Sync.innerRun (FutureTask.java:305)
java.util.concurrent.FutureTask.run (FutureTask.java:137)
android.os.AsyncTask$SerialExecutor$1.run (AsyncTask.java:230)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1076)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:569)
java.lang.Thread.run (Thread.java:856)

#### Version of Realm and tooling
Realm version(s): realm-android-0.87.4

Android Studio version: Android studio 2.1

Android version and device: 100% on Android 4(4.3 & 4.1.1.) - GTI8190

CPU Architecture - arm64-v8a

I am splitting the APK into 6 parts 
`ext.versionCodes = ['armeabi': 31, 'armeabi-v7a': 32, 'arm64-v8a': 33, 'mips': 34, 'x86': 35, 'x86_64': 36]`

And till now error is only for users who have arm64-v8a version

**Comment by kneth** [comment]
Does your app include other `.so` files? If so, does that `.so` supports all architectures? Please take a look at https://realm.io/docs/java/latest/#couldnt-load-librealm-jniso

**Comment by mihirjoshi21** [comment]
My app doesn't use any other .so files. Moreover, I tried on Lenovo K3 Note and Asus Z010D and it's also not working on them too.

**Comment by kneth** [comment]
Can you make a small project which can reproduce the problem? If you can do that, it is easier for us to help you.

**Comment by mihirjoshi21** [comment]
duplicate of https://github.com/realm/realm-java/issues/2611

**Comment by kneth** [comment]
@mihirjoshi21 I'll close this issue and keep the discussion in #2611 instead.
