### ISSUE TITLE
BaseRealm attribute in RealmObject is null sometimes

### ISSUE THREAD

**Issue by tiago7s** [realm/realm-java#2613]
Recently Realm started to allow custom methods in the extending RealmObject classes, which is great. Thank you for that. So I decided to move some of the logic to the classes.

When doing a beginTransaction and commitTransaction in the class using the BaseRealm object from the RealmObject class, sometimes works and sometimes throws NPE. I cast the BaseRealm object to Realm to call the begin and commit methods.

```
java.lang.NullPointerException: Attempt to invoke virtual method 'void io.realm.Realm.beginTransaction()' on a null object reference

((Realm) realm).beginTransaction();

status = updatedStatus;

((Realm) realm).commitTransaction();
```

Can you let me know why sometimes it works and others no?

**Comment by emanuelez** [comment]
The realm field is `protected` so it's not supposed to be used under normal circumstances. It is used internally to determine whether an object is managed by a Realm of if it's standalone. If `realm` is `null` then it means it's a standalone object.

**Comment by stk1m1** [comment]
@tiago7s Has our suggestion helped you? Could you share your progress with us?

**Comment by tiago7s** [comment]
@stk1m1 I ended up removing the custom methods that added the objects to Realm and got back to adding them outside their classes. Thank you anyway for the response.
