### ISSUE TITLE
**Bugs** can't download 0.89.0

### ISSUE THREAD

**Issue by ReyLiang** [realm/realm-java#2616]
Realm version(s): 0.89.0

Android Studio version: 2.1 beta2

https://jcenter.bintray.com/io/realm/realm-gradle-plugin/

can't find 0.89.0 or 0.89.0-SNAPSHOTS.

**Comment by cmelchior** [comment]
Hi @ReyLiang 
0.89 hasn't been released yet, so you have to use OJO for the SNAPSHOT. It is described here: https://github.com/realm/realm-java/blob/master/README.md#using-snapshots

**Comment by ReyLiang** [comment]
example's base on 0.89.0-SNAPSHOT. 
could you tell me, when is 0.89.0 release? i want to use it into my new project,

**Comment by cmelchior** [comment]
The plan is this week

**Comment by ReyLiang** [comment]
thx~~ : )
