### ISSUE TITLE
Realm doesn't update byte arrays

### ISSUE THREAD

**Issue by derekstavis** [realm/realm-java#2617]
When trying to update byte arrays it seems like Realm doesn't track the changes.

#### Goal

Update byte arrays by replacing the object.

#### Expected Results

Have the byte array updated after commiting the change.

#### Actual Results

Realm saves byte arrays with zeros.

#### Steps & Code to Reproduce

1. Create a subclass of RealmObject
1. Create a `byte[]` field
1. Create a new realm object from this class
1. Initialize the field with no elements
1. Persist the object
1. Retrieve the object from Realm
1. Replace the byte array with other byte array with elements
1. Persist the object
1. Retrieve the object from Realm
1. Check if the byte array have the expected contents

#### Code Sample

```java
public class MultipleOptionAnswer extends RealmObject {
    public byte[] choicesIds = new byte[0];
    public int questionId;

    public MultipleOptionAnswer() {}

    public int getQuestionId() {
        return questionId;
    }

    public void setQuestionId(int id) {
        questionId = id;
    }

    public Set<Integer> getIntegerChoicesIds() {
        Set<Integer> choices = new HashSet<>();
        if (null != choicesIds) {
            for (byte choice : choicesIds) {
                choices.add(choice & 0xFF);
            }
        }
        return choices;
    }

    public void setIntegerChoicesIds(Set<Integer> choicesIds) {
        int i = 0;
        this.choicesIds = new byte[choicesIds.size()];
        for (Integer choice : choicesIds) {
            this.choicesIds[i] = choice.byteValue();
            i++;
        }
    }
}
```

#### Version of Realm and tooling

Realm version(s): 0.88.2

Android Studio version: 2.0

Which Android version and device: Android 5.0, Asus Fonepad 7 (K00E)

**Comment by cmelchior** [comment]
Hi @derekstavis 

This unit test seems to indicate it should work fine:
```
    @Test
    public void setGet_byteArray() {
        realm.beginTransaction();
        AllJavaTypes obj = realm.createObject(AllJavaTypes.class);
        realm.commitTransaction();
        assertArrayEquals(null, obj.getFieldBinary());

        realm.beginTransaction();
        obj.setFieldBinary(new byte[] {1, 2, 3});
        realm.commitTransaction();

        assertArrayEquals(new byte[] {1, 2, 3}, obj.getFieldBinary());
        assertArrayEquals(new byte[] {1, 2, 3}, realm.where(AllJavaTypes.class).findFirst().getFieldBinary());
    }
```

Can you show some example code that demonstrate the behaviour you are seeing?

**Comment by derekstavis** [comment]
Hi @cmelchior, thanks for your fast response!!

The code that I'm using is, verbatim, the one I've pasted in the report. But there's one thing that I noticed that's different between the unit test code you pasted an my code: I'm assigning an empty array and then filling it afterwards. May this represent an issue to Realm?

This is how I use the pasted `MultipleOptionAnswer ` class:

```java
...

    private void toggleChoice(Choice choice) {
        realm().beginTransaction();

        if (null == mAnswer) {
            mAnswer = realm().createObject(MultipleOptionAnswer.class);
            mAnswer.questionId = mQuestion.id;
        }

        Set<Integer> choices = mAnswer.getIntegerChoicesIds();

        if (choices.contains(choice.id)) {
            choices.remove(choice.id);
        } else {
            choices.add(choice.id);
        }

        mAnswer.setIntegerChoicesIds(choices);

        realm().commitTransaction();
    }

...
```

**Comment by kneth** [comment]
@derekstavis You have discovered a short-coming in Realm - thanks! Let me explain. Realm transforms all assignments into getters or setters at the byte code level. That means that `this.age = 42` is transformed into `this.setAge(42)`. 

The way we transform code implies that it is not possible to access individual elements of a byte array (or a string). This is the short-coming as you have discovered. As a workaround, I suggest that you do:

    public void setIntegerChoicesIds(Set<Integer> choicesIds) {
        int i = 0;
        byte[] tmp = new byte[choicesIds.size()];
        for (Integer choice : choicesIds) {
            tmp[i] = choice.byteValue();
            i++;
        }
        this.choicesIds = tmp;
    }

The late statement will be transformed into the appropriate setter.

Our storage engine doesn't support access to individual elements of byte array - or strings - and detecting the assignment as you have is very hard. For those reasons I will not label this issue as a bug but we must clearly document this behavior.

**Comment by derekstavis** [comment]
Cool! I came back to tell that right after my last post I solved the issue by doing exactly what you advised me to do.

Thanks for a fast and precise response, and also for such an awesome library that have been freeing people from SQLite bureaucracy 😝

**Comment by Zhuinden** [comment]
Ah, you need to modify the byte array in one go, so you create the byte array on a different reference `tmp`, allocate and copy the stuff, and you modify the byte array itself only when you can directly assign it.

That's an interesting catch.

**Comment by kneth** [comment]
@derekstavis I have added a short section in our documentation.
