### ISSUE TITLE
How to replace old project in using realm???

### ISSUE THREAD

**Issue by hellworld** [realm/realm-java#2624]
I was confused that I had a lot of databases of a old project developed by android SQLiteOpenHelper, how can I use Realm replaced, and how to migrate the app in user's database's data??

**Comment by hellworld** [comment]
I was confused that I had a lot of databases of a old project developed  by android SQLiteOpenHelper, how can I use Realm replaced, and how to migrate the app in user's database's data??

**Comment by stk1m1** [comment]
Hi @hellworld 

We are currently looking into supporting such use case. As of now, you'd want to setup [RealmModel](https://realm.io/docs/java/latest/#models), export data from SQLite, and import toward Realm.

**Comment by hellworld** [comment]
Will the next version can support ？？？

**Comment by stk1m1** [comment]
@hellworld 

We'd love to give you a timeline, but, as of now, it can only be stated that the feature is  in our production pipeline. I'd plead for your understanding that features have different priorities.

**Comment by hellworld** [comment]
@stk1m1  OK,thanks for your answer!
