### ISSUE TITLE
Strings with Required Annotations creating empty String when using createOrUpdateAllFromJson

### ISSUE THREAD

**Issue by gwbenbarber** [realm/realm-java#2629]
#### Goal

Using the Required Annotation and the createOrUpdateAllFromJson when the object doesn't define the value for required field.

#### Expected Results

An Error message of some sort perhaps preventing the createOrUpdateAllFromJson from happening

#### Actual Results

Creating an empty String instead of making the field null or and exception

#### Steps & Code to Reproduce

Run the code below

#### Code Sample

```java
public class DudObject extends RealmObject {
    @PrimaryKey
    public String id;
    @Required
    public String name;

    public String getId() {
        return id;
    }

    public String getName() {
        return name;
    }

    public void setId(String id) {
        this.id = id;
    }

    public void setName(String name) {
        this.name = name;
    }
}
```

```java
public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        Realm realm = Realm.getInstance(new RealmConfiguration.Builder(this).build());
        realm.beginTransaction();
        try {
            realm.createOrUpdateAllFromJson(DudObject.class, getResources().openRawResource(R.raw.duds));
        } catch (IOException e) {
            e.printStackTrace();
        }
        realm.commitTransaction();

        for (DudObject object : realm.allObjects(DudObject.class)) {
            Log.d("Object", ""+object);
        }
    }
}
```

res/raw/duds.json
```json
[
  {
    "id": "1"
  }, {
    "id": "2"
  },{
    "id": "3"
  },{
    "id": "4"
  },{
    "id": "5"
  },{
    "id": "6"
  },{
    "id": "7"
  },{
    "id": "8"
  }
]
```

#### Version of Realm and tooling
Realm version(s): 0.88.3

Android Studio version:
Android Studio 2.0
Build #AI-143.2739321, built on April 5, 2016
JRE: 1.6.0_65-b14-468-11M4833 x86_64
JVM: Java HotSpot(TM) 64-Bit Server VM by Apple Inc.

Which Android version and device: 
Nexus 5X 6.0.1 (2nd April 2016 Patch)

**Comment by cmelchior** [comment]
Hi @gwbenbarber 
Thanks for the report. Right now we only use the `@Required` annotation to mean "non-null values", that seems a bit different than requiring a Json blob to have a field definition.

Can you elaborate a bit on your use case?

**Comment by gwbenbarber** [comment]
I was looking at having it so that if the Json blob either didn't have have a field definition or a is defined as null that Realm would present so some of error informing me that that these "Required" fields don't have a value assigned. 

I was aiming to use this at initial start time, to check whether the Realm had correctly imported two different Json files

**Comment by kneth** [comment]
@gwbenbarber I do understand the confusion coming from the fact that a "required" field isn't required in JSON. If you look at the three parsing rules in https://realm.io/docs/java/latest/#json, the last rule says that a missing field in JSON will leave the field unchanged in Realm. Since a required string field in Realm has the empty string as default value, you'll end up with the empty string.

**Comment by gwbenbarber** [comment]
So the way I've interpreted this is that the `@Required` behaves as a default value if no value is given in the Json? (Also a `@DefaultValue` attribute would be appreciated). 

What would be the best way of checking whether a value like the one given in the example has been properly imported?

**Comment by cmelchior** [comment]
It sounds more like you want to verify if some JSON string contains a particular field. You can use the standard JSON api for that:

```
JSONObject obj = new JSONObject(readFile(duds.json));
if (obj.has("fieldName")) {
  // JSON has the data
} else {
  // JSON doens't have the field, Realm will use the default value for that field.
  // Alternatively set it using obj.put("fieldName", value)
}
```

**Comment by cmelchior** [comment]
@gwbenbarber I assume the above answered your question? We would prefer not to override the meaning of "@Required" in terms of how it is used when interpreting JSON, so the above work-around should work for now.
