### ISSUE TITLE
android build tools 2.1.0-beta3 will throw exception

### ISSUE THREAD

**Issue by lqxing001** [realm/realm-java#2633]
I updated the project classpath today
`classpath 'com.android.tools.build:gradle:2.1.0-beta3'`

When the App run,realm will throw exception 

`io.realm.exceptions.RealmException: class XXX is not part of the schema for this Realm.`

but when building app not any error to tell me

I use 0.88.0 version of realm.

when I go back to use  `'com.android.tools.build:gradle:2.0.0'` , there is no problem.

**Comment by cmelchior** [comment]
Hi @lqxing001 Are you using Instant Run or does this happen from a clean build as well?

**Comment by stk1m1** [comment]
Hi @lqxing001 

As of today (Apr. 21, 2016), `com.android.tools.build:gradle:2.1.0-beta3` is just two days old. We'd also expect quite a bit of breaking change from the latest Gradle release that we would be highly appreciate if you could come to reopen this case when Gradle `2.1.0` is finally release.

**Comment by lqxing001** [comment]
I don't think this issues related to Instant Run,because there is no problem before the update.
And I have many clean and rebuild projects, but it is still the same

**Comment by beeender** [comment]
@lqxing001 I tried with `classpath 'com.android.tools.build:gradle:2.1.0-beta3'` , it works fine with my project. Would you please try with turning off instant run?

**Comment by bangarharshit** [comment]
+1. It is not working even with stable build. Not working with even clean build.

**Comment by stk1m1** [comment]
Hi @lqxing001, @bangarharshit 
Could you please share your `build.gradle` with us? I too tried `classpath 'com.android.tools.build:gradle:2.1.0-beta3` and everything works fine on my end.

If you want the scripts to be remain private, you can send them to help@realm.io.

**Comment by cmelchior** [comment]
@lqxing001 Can you try to update to the stable "2.1.0" and see if that makes a difference. If not please create a small sample project that reproduces this or send your current project to help@realm.io (it will be private there).

**Comment by beeender** [comment]
close due to no response
