### ISSUE TITLE
Add a "getPrimaryKeyType()" method to RealmObjectSchema

### ISSUE THREAD

**Issue by bkromhout** [realm/realm-java#2636]
#### Goal

`RealmObjectSchema` already has the `isPrimaryKey(String)`, `hasPrimaryKey()`, `addPrimaryKey(String)`, and `removePrimaryKey()` methods, but it lacks an easy way to check the `RealmFieldType` of an existing primary key field (if there is such a field, of course).

#### Expected Results

I would expect there to be some method with a signature like `RealmFieldType getPrimaryKeyType()`. Alternatively, there could be a `String getPrimaryKeyName()` method, which might be even more useful, and would allow something simple like `getFieldType(getPrimaryKeyName());` to be done.

#### Actual Results

Once I know there's a primary key, I have to do something like the following to find out what its `RealmFieldType` is:  
```java
// Assuming I already have a RealmObjectSchema variable called "schema" somewhere.
Set<String> fields = schema.getFieldNames();
RealmFieldType pkType;
for (String field : fields) {
    if (schema.isPrimaryKey(field)) {
        pkType = schema.getFieldType(field);
        break;
    }
}
```

**Comment by cmelchior** [comment]
I think a `getPrimaryKeyType()` would be a bit too specialised, but I agree with you that something like `getPrimaryKey()` or `getPrimaryKeyFieldName()` seems to be missing. Personally I would probably lean towards `getPrimaryKey()`.

We will happily accept any PR for it, if you feel like implementing it yourself.

**Comment by bkromhout** [comment]
Awesome. I might actually take a stab at it this weekend if I get some free time.

**Comment by bkromhout** [comment]
Hi @cmelchior, I've opened a PR to add this feature (a bit ago actually, I just didn't think to comment here until now).
