### ISSUE TITLE
Adding a @Default annotation? 

### ISSUE THREAD

**Issue by emanuelet** [realm/realm-java#2639]
Hi,
I wanted to ask if it was possible and viable to add a **@Default** annotation to the fields, so then when the object is created it has already some values without going through a constructor.

_eg.:_
```java
@Default("Lorem Ipsum")
private String body;
```

**Comment by beeender** [comment]
Yes, this is on our feature radar. #777 is the one reported before. So I am closing this one and we can have discussion in #777.

**Comment by emanuelet** [comment]
ah thank you, I searched for it but it didn't come up
