### ISSUE TITLE
OldVersion value of migrate function not incrementing when schema changes in Realm migration in android

### ISSUE THREAD

**Issue by deep4109** [realm/realm-java#2641]
> We LOVE to help with any issues or bug you have!

> **Questions**: If you have questions about how to use Realm, please ask on [SO](http://stackoverflow.com/questions/ask?tags=realm) - we monitor the Realm tag.

> **Feature Request**: Just fill in the first two sections below.

> **Bugs**: To help you as fast as possible with an issue or bug please describe your issue and the steps you have taken to reproduce it in as many details as possible.
>
> Thanks for helping us help you :-)
>
> Remove this and above before submitting.

#### Goal

> What do you want to achieve?

#### Expected Results

> ?

#### Actual Results

>  E.g. full stack trace with exception

#### Steps & Code to Reproduce

> Describe your current debugging efforts.

#### Code Sample

```java

> Your code here. Bigger samples should ideally be as separate Android Studio project, 
> in gists/repositories or privately at help@realm.io)

```

#### Version of Realm and tooling
Realm version(s): ?

Android Studio version: ?

Which Android version and device: ?

**Comment by deep4109** [comment]
@Override public void migrate(DynamicRealm realm, long oldVersion, long newVersion) {

    preferencesHelper = new PreferencesHelper(MyApplication.getAppContext());

    RealmSchema schema = realm.getSchema();
    latestMigrationVersion=preferencesHelper.GetPreferences(PREFS_NAME);



    // check if the previous migration took place
    if (oldVersion > 0 && oldVersion - 1 > latestMigrationVersion) {
        // user missed migration
        // then we need to run previous missed migrations before
        oldVersion = latestMigrationVersion;
    }







    if (oldVersion == 0) {


        schema.create("User")
                .addField("userId", int.class, FieldAttribute.PRIMARY_KEY)
                .addField("userName", String.class);

        oldVersion++;
    }


    if (oldVersion == 1) {


        schema.create("Pooja")
                .addField("poojaId", int.class, FieldAttribute.PRIMARY_KEY);


        oldVersion++;
    }

    if (oldVersion == 2) {


        schema.create("Deep")
                .addField("deepId", int.class, FieldAttribute.PRIMARY_KEY);


        oldVersion++;
    }
    // update latestMigrationVersion for future checks
    latestMigrationVersion = oldVersion;
    // save the property locally





    preferencesHelper.SavePreferences(PREFS_NAME,latestMigrationVersion);

    Log.d("latest",""+latestMigrationVersion);


    Log.d("MainActivity","Migration happend!");
}

**Comment by deep4109** [comment]
please reply

**Comment by stk1m1** [comment]
Hi @deep4109 

In order to provide a swift support, we'd encourage you to provide following details plus a small sample we could reproduce the problem, please.

- Realm version(s)  
- Android Studio version
- Which Android version and device  
- A sample project

**Comment by deep4109** [comment]
Android with java.
Realm version-realm 88.3
Android studio version 2.0
android version 5.0

**Comment by beeender** [comment]
So what exactly is your problem? `oldVersion` is always `0`? Have you tried to attach a debugger to get more information to help us/you locate the problem? 
Thanks!

**Comment by beeender** [comment]
conversation is going on SO http://stackoverflow.com/questions/36786400/oldversion-value-of-migrate-function-not-incrementing-when-schema-changes-in-rea

Close the issue here.
