### ISSUE TITLE
Android first time launch - showing blank screen for quite a long time

### ISSUE THREAD

**Issue by alicewang05** [realm/realm-java#2646]
Hello

After I import Realm to my android app, I noticed the app shows blank screen for a while when
 launch in the first time. The subsequent launch, it is fine. I also tried the examples you have. They are having this issue as well. I use Realm like this.
```
public class MyApp extends Application {
    @Override
    public void onCreate() {
        super.onCreate();
        RealmConfiguration config = new RealmConfiguration.Builder(this).build();
        Realm.setDefaultConfiguration(config);
    }
}
```
After I comment out `RealmConfiguration` part, the app still have this issue. 
I test this on nexus 6. I attach a screenshot
Thank you

![launch](https://cloud.githubusercontent.com/assets/12249700/14746844/73fb7054-08a9-11e6-84a5-18ac68d3d67b.png)

**Comment by cmelchior** [comment]
Hi @alicewang05 
Have you tried timing your application startup time? E.g. as described here: http://graphics-geek.blogspot.de/2015/10/measuring-activity-startup-time.html

That will give us some more solid numbers to work with. Also are you doing anything else in you application class or the first activity in your app?

**Comment by alicewang05** [comment]
Hello 

Thanks for getting back this for me.

It turns out this is not Realm issue. There is an issue in Android Studio 2.0 when it has `compile 'com.android.support:appcompat-v7:23.3.0` in dependencies. After I upgrade to android studio 2.1, the issue is fixed. 

Thanks for spending time on this for me. Will close this. 

Cheers,
Alice

**Comment by zyvpeople** [comment]
I had the same issue. Application launched 15 seconds. Solution with removing appcompat library works but I found another reason of this but - problem with Instant run. You should disable it.
