### ISSUE TITLE
a breaking update from 0.88.2 to 0.89.0 use of @Required on string key

### ISSUE THREAD

**Issue by dkuida** [realm/realm-java#2651]
a breaking update from 0.88.2 to 0.89.0
might be intended, but because @PrimaryKey no longer Implies @Required, if the key was String ( which is nullable by definition) adding a @Required to it leads to a compilation error
String cannot be converted to long - in the RealProxy for each file, removing  the @Required solves that.

//sample proxy failing line
 long rowIndex = table.findFirstLong(pkColumnIndex, ((BusinessRealmProxyInterface) object).realmGet$id());

**Comment by cmelchior** [comment]
Hi @dkuida 
Yes, somehow this bug eluded our testing. Right now it only works if you keep the String nullable. It was also reported here #2637 . We already have a fix here: https://github.com/realm/realm-java/pull/2644, so will be releasing a fix asap.

I'll close this as an duplicate.
