### ISSUE TITLE
RealmResults.sort is not working on 0.89.0

### ISSUE THREAD

**Issue by ccjeng** [realm/realm-java#2655]
RealmResults.sort works on 0.88.3.
After upgrading to 0.89.0, it is not working.

#### Code Sample

```java

RealmResults<Category> results = realm.where(Category.class).findAll();
results.sort("datetime", Sort.DESCENDING);

```

#### Version of Realm and tooling
Realm version(s): 0.89.0

Android Studio version: 2.1.0-beta3

Which Android version and device: N/A

**Comment by cmelchior** [comment]
Hi @ccjeng 
`sort` has changed to be in-place to return the sorted set in 0.89. Looking at the changelog I realise this is not entirely clear.

```
RealmResults<Category> results = realm.where(Category.class).findAll();
results = results.sort("datetime", Sort.DESCENDING);
```

Should work.

**Comment by ccjeng** [comment]
It works now. Thanks @cmelchior quick response.

**Comment by Zhuinden** [comment]
I guess a better alternative is to use `findAllSorted()` instead of `findAll().sort()`?

**Comment by biagionicp** [comment]
so now everytime my data changes i have to call sort, to properly reflect the change in my application?

**Comment by Zhuinden** [comment]
If you use `findAllSorted` then no

**Comment by kinsleykajiva** [comment]
this worked for me in Realm Android java 1.1.0

 results = myRealm.where(ClassesLecture.class).equalTo("classDay", DAY_IN_VIEW).findAllAsync();
        results=results.sort("classOrder", Sort.ASCENDING);

at the time of making this comment Realm.io/java had not updated there documentary because the one they have is not working in android.i just hope they update it..
