### ISSUE TITLE
Realm is not saved via BroadcastReceiver (when the app is not in the background)

### ISSUE THREAD

**Issue by hay12396** [realm/realm-java#2664]
Hello,

I'm using realm as part of my project.
The problem is that when i'm trying to save information into the realm when the app is not in the background the data is not saved.

I can confirmed that the broadcast onReceive method is called and that my code is executed.
I'm trying to save the information using this lines:

```java
Realm realm = Realm.getDefaultInstance();
realm.beginTransaction();
RealmElement el = realm.where(RealmElement.class).equalTo("Id", id).findFirst();
el.setElementType(type);
realm.copyToRealmOrUpdate(el);
realm.commitTransaction();
realm.close();
```

my RealmElement class is:

```java
class RealmElement extends RealmObject{
    @PrimaryKey
     private int Id;
     private ElementType;
//getters setters..
}
```
However, when i'm coming back to my app, the ElementType of this object is still the old one(the change i made was not saved).

With regards,
Hay.

**Comment by beeender** [comment]
@hay12396 Does your BroadcastReceiver run in another process than the app's?

> The problem is that when i'm trying to save information into the realm when the app is not in the background the data is not saved.

So if the app is still in the background, the data can be saved in the broadcast receiver?

Can you see any exception thrown in the logcat?

**Comment by hay12396** [comment]
Hello beeender,

The Broadcast is running in the same process, when the app is in the background, the data is saved.
I couldn't see any exceptions in the logcat.

**Comment by beeender** [comment]
@hay12396 I tried the similar case with BroadcastReceiver and it worked well.

Is it possible to share your project with us and tell us how to reproduce the issue? It would be great if you can even make a minimal project to show the problem. If you want to share it privately, you can send it to help@realm.io

Other things you can check in your side is:
Go to the directory of you Realm file, to see what the data is though Realm browser, or even simpler just check the time stamp. I doubt there is something wrong with your `Realm.setDefaultConfiguartion` which cause the data has been written to a different Realm file.

**Comment by cmelchior** [comment]
Closing due to no response.

**Comment by Jake21x** [comment]
I have the same issue .. 

There are no error . or Logcat exceptions

**Comment by Jake21x** [comment]
Im using alarm service then call the BroadcastReciever via PendingIntent to save the data .
now if i ternimate the app .. Expecting that my alarm service is setRepeating to call the  BroadCast  .. then BroadCast should work fine .. But is not saving the data .. with no error or any logs ..

**Comment by Zhuinden** [comment]
If you commit the transaction, it should definitely save the data.

In fact, if you use Realm 2.0+ (especially Realm 4.2.0+) then it should definitely work in all case

**Comment by mhashim6** [comment]
@Zhuinden . I'm having the same isssue, I use executeTransaction( ) which closes realm automatically.
I'm using realm 5.4.2.

**Comment by mhashim6** [comment]
I just let the receiver start an empty activity(with no layout) to handle the database. the same thing happened. I think it's no longer a BroadcastReceiver issue. It's strange, other realm transactions run perfectly in other activities/fragments.

I don't know if this is useful, but this broadcast is started by a notification action.

**Comment by mhashim6** [comment]
Actually I think BroadcastReceiver is the culprit: I let the activity handle the notification action directly  without the man(BroadcastReceiver) in the middle, and the transaction worked just fine, I don't understand why though.

**Comment by mhashim6** [comment]
I found my solution in this [SO answer](https://stackoverflow.com/a/52254947/3578585).
