### ISSUE TITLE
Possible bug in documentation

### ISSUE THREAD

**Issue by draskosaric** [realm/realm-java#2665]
Hi,

I have noticed that in [your documentation](https://realm.io/docs/java/latest/#best-practices) you suggested that you proposed closing realm in `onDestroy()` activity's method, but according to [this link](http://developer.android.com/reference/android/app/Activity.html#onDestroy%28%29) it is not very safe thing to do. Thoughts?

**Comment by Zhuinden** [comment]
I don't see why it wouldn't be safe. Changes to data are committed on `commitTransaction()`, not in `onDestroy()`.

**Comment by beeender** [comment]
Agree with @Zhuinden .
`Realm.close()` is to ensure you won't leak memory. In the case that the whole process get killed, not calling `Realm.close()` might cause db file contains some garbage pages but those can be reused when next time write to Realm.

**Comment by draskosaric** [comment]
I was curious about possible memory leak if realm.close() is not called, that's all, but @Zhuinden and @beeender explained that case perfectly. Thanks!
