### ISSUE TITLE
Can't use proguard with 0.89.x, LinkedTreeMap cannot be cast to io.realm.RealmModel

### ISSUE THREAD

**Issue by JulienDev** [realm/realm-java#2670]
#### Goal

> What do you want to achieve?

I want to use proguard on my Android App with Realm 0.89.x

#### Expected Results

It should work as it was working on 0.88.x

#### Actual Results

04-25 19:16:39.115 4881-5926/com.loreal.campus W/System.err: java.lang.ClassCastException: com.google.gson.internal.LinkedTreeMap cannot be cast to io.realm.RealmModel
04-25 19:16:39.116 4881-5926/com.loreal.campus W/System.err:     at io.realm.RealmList.add(SourceFile:52)
04-25 19:16:39.116 4881-5926/com.loreal.campus W/System.err:     at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.a(SourceFile:83)
04-25 19:16:39.116 4881-5926/com.loreal.campus W/System.err:     at com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.b(SourceFile:61)
04-25 19:16:39.116 4881-5926/com.loreal.campus W/System.err:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.a(SourceFile:116)
04-25 19:16:39.116 4881-5926/com.loreal.campus W/System.err:     at com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.b(SourceFile:216)
04-25 19:16:39.116 4881-5926/com.loreal.campus W/System.err:     at retrofit2.converter.gson.GsonResponseBodyConverter.convert(SourceFile:37)
04-25 19:16:39.116 4881-5926/com.loreal.campus W/System.err:     at retrofit2.converter.gson.GsonResponseBodyConverter.convert(SourceFile:25)
04-25 19:16:39.116 4881-5926/com.loreal.campus W/System.err:     at retrofit2.ServiceMethod.toResponse(SourceFile:116)
04-25 19:16:39.116 4881-5926/com.loreal.campus W/System.err:     at retrofit2.OkHttpCall.parseResponse(SourceFile:211)
04-25 19:16:39.116 4881-5926/com.loreal.campus W/System.err:     at retrofit2.OkHttpCall.execute(SourceFile:174)
04-25 19:16:39.116 4881-5926/com.loreal.campus W/System.err:     at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$RequestArbiter.request(SourceFile:171)
04-25 19:16:39.116 4881-5926/com.loreal.campus W/System.err:     at rx.internal.operators.OperatorSubscribeOn$1$1$1.request(SourceFile:80)
04-25 19:16:39.116 4881-5926/com.loreal.campus W/System.err:     at rx.Subscriber.setProducer(SourceFile:209)
04-25 19:16:39.116 4881-5926/com.loreal.campus W/System.err:     at rx.Subscriber.setProducer(SourceFile:205)
04-25 19:16:39.116 4881-5926/com.loreal.campus W/System.err:     at rx.internal.operators.OperatorSubscribeOn$1$1.setProducer(SourceFile:76)
04-25 19:16:39.116 4881-5926/com.loreal.campus W/System.err:     at rx.Subscriber.setProducer(SourceFile:205)
04-25 19:16:39.116 4881-5926/com.loreal.campus W/System.err:     at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(SourceFile:152)
04-25 19:16:39.116 4881-5926/com.loreal.campus W/System.err:     at retrofit2.adapter.rxjava.RxJavaCallAdapterFactory$CallOnSubscribe.call(SourceFile:138)
04-25 19:16:39.116 4881-5926/com.loreal.campus W/System.err:     at rx.Observable$2.a(SourceFile:162)
04-25 19:16:39.116 4881-5926/com.loreal.campus W/System.err:     at rx.Observable$2.call(SourceFile:154)
04-25 19:16:39.116 4881-5926/com.loreal.campus W/System.err:     at rx.Observable.a(SourceFile:8314)
04-25 19:16:39.116 4881-5926/com.loreal.campus W/System.err:     at rx.internal.operators.OperatorSubscribeOn$1.call(SourceFile:94)
04-25 19:16:39.116 4881-5926/com.loreal.campus W/System.err:     at rx.internal.schedulers.ScheduledAction.run(SourceFile:55)
04-25 19:16:39.116 4881-5926/com.loreal.campus W/System.err:     at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
04-25 19:16:39.116 4881-5926/com.loreal.campus W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:237)
04-25 19:16:39.116 4881-5926/com.loreal.campus W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:269)
04-25 19:16:39.116 4881-5926/com.loreal.campus W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
04-25 19:16:39.116 4881-5926/com.loreal.campus W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
04-25 19:16:39.116 4881-5926/com.loreal.campus W/System.err:     at java.lang.Thread.run(Thread.java:818)

#### Version of Realm and tooling
Realm version(s): 0.89.0 and 0.89.1

Android Studio version: 2.1 RC

Which Android version and device: 6.0.1, Nexus 5

**Comment by skptl** [comment]
Exactly, I was about to open the same issue.

**Comment by zaki50** [comment]
Hi @JulienDev 

If you don't use ProGuard, your app works well?

**Comment by fobid** [comment]
@zaki50  I use 0.89.1, this issue is occured, that's why I downgrade lib to 0.88.3.
and when I use 0.89.1, It works if not using ProGuard.

**Comment by zaki50** [comment]
@fobid thanks!

**Comment by JulienDev** [comment]
Exactly as @fobid, I have to downgrade to 0.88.3. The proguard configuration is the one provided in thé documentation.

**Comment by nhachicha** [comment]
Hi @JulienDev 
Thanks for reporting this issue, could you please provide a JSON example and your ProGuard conf to try to reproduce your crash (or your APK file). 
you can send it privately if you wish at help@realm.io

Cheers,

**Comment by Zhuinden** [comment]
This is definitely a side-effect of this change:

    It is no longer required to define an ExclusionStrategy when combining Realm and GSON.

**Comment by nhachicha** [comment]
Hi @JulienDev 
thanks for sending your JSON & model, I was able to reproduce the issue.

We add a new collection interface since `0.89` can you please try to add the following to your ProGuard configuration 
```
-keep class io.realm.RealmCollection
-keep class io.realm.OrderedRealmCollection
```
Note: you don't have to add the Realm ProGuard configuration into your application conf 
```
-keep class io.realm.annotations.RealmModule
-keep @io.realm.annotations.RealmModule class *
-keep class io.realm.internal.Keep
-keep @io.realm.internal.Keep class *
-dontwarn javax.**
-dontwarn io.realm.**
```
this is add for you by the library, so you can remove it from your own `proguard-rules.pro` 
we updated the documentation accordingly  https://realm.io/docs/java/latest/#proguard

Cheers,

**Comment by JulienDev** [comment]
It works, thank you very much ;)

**Comment by fobid** [comment]
:thumbsup:
