### ISSUE TITLE
Updating realm to 0.89.0 RealmList#first() throw IndexOutOfBoundsException at RealmList size is 0.

### ISSUE THREAD

**Issue by keiji** [realm/realm-java#2680]
Empty RealmList#first() throw IndexOutOfBoundsException instead of return null.

This issue is very similar to below issue.

https://github.com/realm/realm-java/issues/2659

#### Expected Results

RealmList#first() result is null;

    /**
     * Finds the first object.
     *
     * @return the first object or {@code null} if the list is empty.
     * @throws IllegalStateException if Realm instance has been closed or parent object has been removed.
     */
    public E first() {

#### Actual Results

    Process: io.keiji.kehai.debug, PID: 13565
    java.lang.IndexOutOfBoundsException: The list is empty.
     at io.realm.RealmList.first(RealmList.java:463)

#### Code Sample

```java

// setting.getList().size() is 0.
final WiFiApSetting wifiSetting = setting.getList().first();

if (wifiSetting == null) {
    return;
}

```

#### Version of Realm and tooling
Realm version(s): 0.89.1

Android Studio version: 2.0 (Stable)
gradle 2.0.0
buildToolsVersion 23.0.2

Which Android version and device: Nexus 5X (Android 6.0.1)

**Comment by zaki50** [comment]
@keiji Thank you for reporting this.

This is an intended change related to introducing `OrderedRealmCollection`.
We should clearly state that in `CHANGELOG.md`.

If you are using `first()` against possible empty `RealmList `, please check that with `isEmpty()`.

**Comment by Zhuinden** [comment]
Well the docs do say

     * @return the first object or {@code null} if the list is empty.

**Comment by cmelchior** [comment]
@Zhuinden Ups, look like mistake. That Javadoc should have been removed. You can see the correct behavior described in `OrderedRealmCollection`

**Comment by tbsandee** [comment]
I got tripped up on this too recently. Javadocs for RealmList are still wrong for first() and last().
