### ISSUE TITLE
Detect ConcurrentModification when deleting from RealmList

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#2688]
The following code does not work correctly:

```
RealmList<Dog> dogs = person.getDogs();

for (Dog dog : dogs) {
  dog.deleteFromRealm();
}
```

The reason being that changes to RealmList is reflected at once unlike RealmResult that are not updated until next looper event. The easy work-around is just using `dogs.deleteAllFromRealm()` but an ConcurrentModificationException should still be thrown in the above case.

RealmList keeps track of `modCount` just like a normal ArrayList, so it can detect ConcurrentModificationExceptions if you operate directly on the RealmList through e.g. `list.add()/list.remove()`, but that is currently not happening for "indirect" deletes like `obj.deleteFromRealm()`.

I don't have a good solution as there are a number of indirect deletes possible: `realm.delete(Dog.class) / dog.deleteFromRealm()`, but the standard ConcurrentModification doesn't catch all cases either.

The easiest is probably to keep track of a `size()` before each call to `next()` and throw if it changed, but there might be edge cases I didn't consider, and it adds a JNI overhead to all iterations.

We could also just document it, but I am not sure where the best place for that would be.

**Comment by diegomontoya** [comment]
I vote for only doc change. Perhaps add the warnings/explanations under "Concurrency -> Looping through Realm data Gotchas" section.  

At best, users need to understand that using java iterator, or your own for() loop while the size() is being modified in another thread will cause concurrent modify exceptions or index out of bound exceptions. User need to use their own locking to make sure looping is happening when no transaction can happen which affects the size of the looped data.

Realm can detect and throw exceptions all it wont but the only fix is for end users to understand this via doc.

**Comment by beeender** [comment]
`RealmResults` and `RealmList` has the unified behaviour now.
This has been documented here https://realm.io/docs/java/latest/#iterations--snapshots

I think we can close this issue. @cmelchior

**Comment by Zhuinden** [comment]
This definitely works since iterator operate on snapshot

**Comment by cmelchior** [comment]
Yes, we can close this.

**Comment by Khudoyshukur** [comment]
@cmelchior Hello.

I am getting crash in our production app.

![image](https://user-images.githubusercontent.com/60431559/227171834-cab9ba9a-d744-4a80-afb4-e16a895a8bb1.png)

As a solution, I am gonna use .deleteAllFromRealm(). Does it solve the issue? Can you confirm?

![image](https://user-images.githubusercontent.com/60431559/227171721-3546d669-9801-4ace-b0ee-94ffe7c35272.png)

**Comment by clementetb** [comment]
Hi @Khudoyshukur Would you mind opening a new issue? When opening the new issue please fill out the details of your setup, Realm version, etc, as requested.

This issue is 7 years old, and things have changed since.

**Comment by Khudoyshukur** [comment]
Thank you @clementetb. Opened a new issue here https://github.com/realm/realm-java/issues/7792
