### ISSUE TITLE
Realm model classes must either extend RealmObject or implement RealmModel to be considered a valid model class

### ISSUE THREAD

**Issue by FabianTerhorst** [realm/realm-java#2689]
Im getting Realm model classes must either extend RealmObject or implement RealmModel to be considered a valid model class. My class looks like the following:

```
@RealmClass
public class MyClass1 extends MyClass2 implements MyInterface1, RealmModel {
....
} 


public class MyClass2 extends RealmObject {
....
}

```

Realm version(s): 0.90.0-SNAPSHOT

Android Studio version: 2.1

Which Android version and device: Nexus 6p 6.0 (Unrelated)

**Comment by cmelchior** [comment]
Hi @FabianTerhorst 
We don't support extending other Realm classes just yet. It is being tracked here: #761, so i'll close this as an duplicate, but you can follow #761 instead.

**Comment by FabianTerhorst** [comment]
thanks for the fast answer

**Comment by Sulejman** [comment]
Is there alternative, I am looking for a way to implement caching on android app and I have a lot of polymorphism in models?

**Comment by Zhuinden** [comment]
You can share interfaces but you cannot share fields.
