### ISSUE TITLE
Realm model classes must either extend RealmObject or implement RealmModel to be considered a valid model class

### ISSUE THREAD

**Issue by MarcinOrlowski** [realm/realm-java#2691]
I got abstract class

    abstract public class ModelBase implements ModelInterface { 
      ...
    }

which is extended by my models. I now want some of them to be Realm powered:

    @RealmClass
    public class Something extends ModelBase implements RealmModel {
       ...
    }

But this throws during compilation:

    Error:(50, 8) error: Realm model classes must either extend RealmObject or implement RealmModel to be considered a valid model class

Is such model not supported or I am doing something obviously wrong here? Recent Realm version in use, so is Android Studio.

**Comment by cmelchior** [comment]
Hi @MarcinOrlowski 
We don't support extending other Realm classes just yet. It is being tracked here: #761, so i'll close this as an duplicate, but you can follow #761 instead.
