### ISSUE TITLE
Database values not consistent between UI thread and AsyncTask

### ISSUE THREAD

**Issue by tanayagrawal** [realm/realm-java#2694]
###Goal
I am trying to fetch a value from Realm in an Async Task which was committed from the UI thread right before starting the AsyncTask

### Expected Results
The value fetched from Realm in the AsyncTask should be same as the value which was committed in the UI thread. 

#### Actual Results
The value fetched from Realm in the AsyncTask is NOT same as the value which was committed in the UI thread.

#### Steps & Code to Reproduce
- Commit a object in the Realm from the UI thread.
- Make sure this object has some kind of unique ID associated with it.
- I try to fetch that same object from the realm using same unique ID from the AsyncTask since the objects cannot be passed across threads.
- After fetching this value, I have a loop running in my AsyncTask which uses this value. 
- For the first few iterations of the loop, the value of the object fetched from Realm is not updated(value which was committed from the UI thread) and is only updated after some of the iterations of the loop are over.
- This leads to inconsistency between the computations that take place in the loop depending on that RealmObject

Realm version(s): 0.89.1

Android Studio version: 2.0.0

Android Version : 5.0 
Device : OnePlus One

**Comment by cmelchior** [comment]
Hi @tanayagrawal 

Can you elaborate what you mean by these bullet points:

* After fetching this value, I have a loop running in my AsyncTask which uses this value.
* For the first few iterations of the loop, the value of the object fetched from Realm is not updated(value which was committed from the UI thread) and is only updated after some of the iterations of the loop are over.
* This leads to inconsistency between the computations that take place in the loop depending on that RealmObject

If you have a code sample, that would be even better.

**Comment by cmelchior** [comment]
Closing due to no response
