### ISSUE TITLE
Information about memory usage on realm.io

### ISSUE THREAD

**Issue by andreamontanari** [realm/realm-java#2696]
Hello,

I would like to start using realm on my android app.
But first, I want to know what's the memory usage in terms of megabytes per table (= number of rows) because I'm thinking of creating a "lightweight" app. I could not find anything on the documentation online so I thought it was the best idea to open an issue here.

Thank you

kind regards

Andrea

**Comment by cmelchior** [comment]
Hi @andreamontanari 
There is no "one" answer for that as it depends on the number of fields on your model classes and what data they contain.

There is also a difference between the data used in Java, and the size of the file on disk. I am not entirely sure which of the two you are referring to?

Generally we only load the data you actually access into the Java heap, so if you have a model with 100 fields and you only access 1 field, you only pay the memory cost of that 1 field. This lazy loading behaviour is different than what all the SQLite ORM's do for example. They load all the fields, so they will use more Java heap memory.

Regarding native memory, then Realm does something called bit-packing which means that if you have many fields with the same value they will take up far less space than if you saved each field individually.

I hope that clarifies it.

**Comment by andreamontanari** [comment]
Thank you for the complete answer.

I am considering to use a single table with maximum 5 cols with dataypes as date,string and integers.
I was wondering how much it would weigh this table with approximately 5k rows on the android device as **size of the file on disk**.

**Comment by kneth** [comment]
@andreamontanari I can't give you a definite answer as it depends on your data. But my best guess is that your Realm file will be smaller than with other databases.

@cmelchior does talk a bit about how our storage engine works in https://realm.io/news/fragmented-27-christian-melchior/

**Comment by cmelchior** [comment]
Hi @andreamontanari I assume the above answered your question. Closing.
