### ISSUE TITLE
Sorting broken in 0.89.1?

### ISSUE THREAD

**Issue by luzianscherrer** [realm/realm-java#2701]
#### Issue
I've upgraded from 0.87.2 to 0.89.1 and all of my sortings are not working any more. I can demonstrate a reproducible case to demonstrate it. But first I'd like to ask: am I missing something?

#### Version of Realm and tooling
Realm version(s): 0.89.1
Android Studio version: 1.5.1

**Comment by cmelchior** [comment]
Sorting was changed from being in-place to returning the sorted collection. Maybe that is what you are running into?

It wasn't highlighted very well in our release post which was probably a mistake, but it should be in the changelog: https://github.com/realm/realm-java/blob/master/CHANGELOG.md

**Comment by cmelchior** [comment]
The change was done as part of ensuring that all our collections had the same behaviour. I do realise those kinds of changes are annoying, especially if they start breaking functionality in unintuitive ways. We do think it will make the API better going forward though, but I am sorry you where hit by this.

**Comment by luzianscherrer** [comment]
Got it, thanks! I can confirm that it is working then... so I'm refactoring everything from

`            results.sort("created", Sort.ASCENDING);
`

to 

`            results = results.sort("created", Sort.ASCENDING);
`

**Comment by emanuelez** [comment]
Perfect! :)
