### ISSUE TITLE
Support for Joda date time

### ISSUE THREAD

**Issue by danijax** [realm/realm-java#2706]
#### Goal

> I want to save a realmobject that has a feild of joda DateTime Type
#### Expected Results

> normal behavior

#### Actual Results

>  Error:(18, 8) error: Type org.joda.time.DateTime of field createdAt is not supported
#### Steps & Code to Reproduce

> Describe your current debugging efforts.

#### Code Sample

```java

> @JsonSerialize(using = DateTimeSerializer.class)
    @JsonDeserialize(using = DateTimeDeserializer.class)
    @JsonProperty("created_at")
    private DateTime createdAt;
> 
```

#### Version of Realm and tooling
Realm version(s): 0.89.1

Android Studio version: Android studio 2.1

Which Android version and device: Android 5.0, samsung galaxy 5

**Comment by cmelchior** [comment]
Hi @danijax Thank you for raising this. The concept you are asking for is called TypeAdapters and is already being tracked here: #1694 
I'll close this as an duplicate, but you can follow progress in #1694
