### ISSUE TITLE
Realm causing ExceptionInInitializerError in some devices

### ISSUE THREAD

**Issue by mihirjoshi21** [realm/realm-java#2709]
I keep on getting this error on my production builds through crashlytics. 

```
Caused by java.lang.ExceptionInInitializerError
io.realm.internal.SharedGroupManager. (SharedGroupManager.java)
io.realm.BaseRealm. (BaseRealm.java)
io.realm.Realm. (Realm.java)
io.realm.Realm.createAndValidate (Realm.java:246)
io.realm.Realm.createInstance (Realm.java:231)
io.realm.RealmCache.createRealmOrGetFromCache (RealmCache.java:114)
io.realm.Realm.getDefaultInstance (Realm.java:181)
```

#### Version of Realm and tooling
Realm version(s):  0.87.4

Android Studio version: 2.1

Which Android version and device: ?  Samsung sgh_i257m55 (4.4.2) 
                                                            Samsung gt_i8190 (4.3) 
                                                            Acer A1-840FHD (4.4.2)
                                                            Nexus 4 (4.1.2)

**Comment by stk1m1** [comment]
Hello @mihirjoshi21 

You have opened issues on the same error at #2606, which is duplicated at #2611. Could you please repost your issue to #2611 and concentrate your discussion there?
