### ISSUE TITLE
Regression: New RealmResults.sort() behavior doesn't carry over RealmChangeListeners to returned RealmResults

### ISSUE THREAD

**Issue by bkromhout** [realm/realm-java#2710]
#### Behavior Regression/Possible Bug

In Realm 0.89.0, the `RealmResults.sort()` methods changed from sorting "in place" to returning a new, sorted, instance of `RealmResults`. 

In previous versions of Realm, if an instance of `RealmResults` had any `RealmChangeListener`s attached to it, those listeners would still be attached after a call to one of its `sort()` methods.

#### Expected Results

In Realm 0.89.0 an above, any `RealmChangeListener`s attached to a `RealmResults` instance whose `sort()` method is called should be "transferred" to the returned (sorted) instance of `RealmResults`, thus preserving the original behavior.

#### Actual Results

In Realm 0.89.0 and above, any `RealmChangeListener`s attached to an instance of `RealmResults` are not "transferred" to the new instance of `RealmResults` which is returned by the various `RealmResults.sort()` methods.

#### Other Comments

Since this is a fairly self-explanatory issue, I don't have a specific set of steps or code sample prepared.

I wouldn't be surprised if many haven't actually run into this regression yet–depending on what people are using their `RealmChangeListener`s to trigger, the effects of losing them due to sorting can range from subtle to blatant.

Even if it's decided that this is an acceptable regression in behavior, I think it might be worth documenting somewhere that `RealmChangeListener`s need to be reattached following a call to one of the `RealmResults.sort()` methods.

#### Version of Realm and tooling
Realm version(s): 0.89.0 and above

Android Studio version: N/A

Which Android version and device: N/A

**Comment by beeender** [comment]
Thanks a lot for the feedback! I think it is a very valid point.

We could:
1. copy the listeners, but user needs to manually remove listeners on the old `RealmResults`, otherwise the both listeners will be triggered.
2. add an method `RealmRetults.moveChangeListeners()`

I think option 1 seems to be more reasonable. Any better ideas? @realm/java

**Comment by cmelchior** [comment]
@bkromhout @beeender The change is actually intentional so I wouldn't catagorize it as a bug, and transfering the listeners would be even more strange I think. Is there any reason you cannot use `findAllSorted`?

**Comment by bkromhout** [comment]
@cmelchior The reason I need `sort` instead of `findAllSorted` is because the `RealmResults` are used to populate an adapter for showing a list of items, and one of my features is that the user can change the sort method and order at runtime, so I then use the `sort` method to apply their new preferred sort method (aka, field) and order (ASC vs DESC).

As far as it being intentional; as I mentioned, I think that it's probably an acceptable regression, but there just needs to be some sort of note somewhere that any calls to `sort` will mean their change listeners are lost.

**Comment by cmelchior** [comment]
I can see there might be an issue when migrating from previous versions of Realm to 0.89, but documenting that something _isn't_ happening in the Javadoc will just confuse people I think, especially 
since no other API's I know of have this behaviour. We should probably update our release blogpost for 0.89 to reflect this however.

In your case, would moving the changelistener to the sorted result not work?
```
RealmResults results = realm.where(Foo.class).findAll();

// user sort
sortedResults = results.sort();
sortedResults.addChangeListener(new RealmChangeListener() {
  public void onChange() {
    listView.notifyDatasetChanged();
  }
});
listView.setAdapter(new MyAdapter(sortedResults));
```

**Comment by bkromhout** [comment]
Sounds good.

And sorry, yes, that does work correctly and is what I'm doing, I just wasn't sure if that was the intended behavior as of 0.89.0, so I figured I'd open an issue. Thanks for the help!

**Comment by Zhuinden** [comment]
Out of curiosity, is there still any way to sort a `RealmResults<T>` in place instead of getting a new one?.

**Comment by beeender** [comment]
@Zhuinden No, there isn't in public API anymore ... Sorting on `RealmResults` will always return a new one.
