### ISSUE TITLE
NoClassDefFoundError in few devices

### ISSUE THREAD

**Issue by mihirjoshi21** [realm/realm-java#2714]
Logcat from crashlytics. 

```
Fatal Exception: java.lang.NoClassDefFoundError
io/realm/exceptions/RealmError
 Raw
io.realm.internal.SharedGroup.createNativeWithImplicitTransactions (SharedGroup.java)
io.realm.internal.SharedGroup. (SharedGroup.java)
io.realm.internal.SharedGroupManager. (SharedGroupManager.java)
io.realm.BaseRealm. (BaseRealm.java)
io.realm.Realm. (Realm.java)
io.realm.Realm.createAndValidate (Realm.java:246)
io.realm.Realm.createInstance (Realm.java:231)
io.realm.RealmCache.createRealmOrGetFromCache (RealmCache.java:114)
io.realm.Realm.getDefaultInstance (Realm.java:181)
```

#### Version of Realm and tooling
Realm version(s):  - 0.87.4

Android Studio version: 2.1

Which Android version and device: Asus and Samsung (4.4.2 and 4.4.4)

**Comment by cmelchior** [comment]
Hi @mihirjoshi21 
Are you using ProGuard in your app?

**Comment by mihirjoshi21** [comment]
Yes.

```
-keep class io.realm.annotations.RealmModule
-keep @io.realm.annotations.RealmModule class *
-dontwarn javax.**
-dontwarn io.realm.**
```

**Comment by cmelchior** [comment]
That is the cause then. The ProGuard configuration you posted is out-dated, you can see it doesn't include the RealmError being mentioned in Crashlytics. We started shipping it with the library from 0.88 to avoid these kind of problems.

I would encourage you to upgrade to the latest version 0.90. That will fix the problem.

**Comment by mihirjoshi21** [comment]
Updating Realm causing -

```
Error:Execution failed for task ':app:transformClassesWithRealmTransformerForDebug'.
> javassist.NotFoundException: io.realm.MyModelRealmProxyInterface
```

**Comment by cmelchior** [comment]
Hi @mihirjoshi21 Please create a new issue with all relevant information. Preferably a copy of your build files as well. It is easier to help you if we keep the issues separate.

**Comment by mihirjoshi21** [comment]
This bug is for [this](http://stackoverflow.com/questions/37029437/existing-realm-database-file-not-working-with-realm-0-90-0) SO question.

**Comment by mihirjoshi21** [comment]
I finally isolated the error. Whenever I try to do an APK split, It caused such problem. Here is the code to split -

```
splits {
        abi {
            enable true
            reset()
            include 'x86', 'x86_64', 'armeabi', 'armeabi-v7a', 'arm64-v8a', 'mips'
        }
    }
```

ext.versionCodes = ['armeabi': 55, 'armeabi-v7a': 56, 'arm64-v8a': 57, 'mips': 58, 'x86': 59, 'x86_64': 60]

```
import com.android.build.OutputFile

android.applicationVariants.all { variant ->
    variant.outputs.each { output ->
        output.versionCodeOverride =
                project.ext.versionCodes.get(output.getFilter(OutputFile.ABI)) * 1000000 + android.defaultConfig.versionCode
    }
}
```
