### ISSUE TITLE
Check if `SharedGroup` in a `Realm` is valid. 

### ISSUE THREAD

**Issue by stk1m1** [realm/realm-java#2718]
#### Goal

Checking if `SharedGroup` in a `Realm` is valid. 

#### Expected Results

In [`BaseRealm.checkIfValid()`](https://github.com/realm/realm-java/blob/master/realm/realm-library/src/main/java/io/realm/BaseRealm.java#L367) method, we should check if `SharedGroup` is closed as well.

#### Actual Results

In [`BaseRealm.checkIfValid()`](https://github.com/realm/realm-java/blob/master/realm/realm-library/src/main/java/io/realm/BaseRealm.java#L367) method, it only checks if `SharedGroupManager` is null or closed.

#### Version of Realm and tooling
Realm version(s): 0.89.1
Android Studio version: N/A
Which Android version and device: N/A

**Comment by beeender** [comment]
`BaseRealm.checkIfValid()` is supposed to be called in the same thread where the `SharedGroup` is in or with some proper locks (eg. locks on `RealmCache`). I think current 
```
public boolean isOpen() {
    return sharedGroup != null;
}
```

is good enough.

**Comment by cmelchior** [comment]
I agree. The current behaviour should be safe enough, and since this method is called extremely often, we should keep it as efficient as possible.

**Comment by stk1m1** [comment]
I'll close the issue.
