### ISSUE TITLE
Add checks for overflow/underflow in time conversion

### ISSUE THREAD

**Issue by kneth** [realm/realm-java#2722]
With the expanded resolution of `Date` fields, we store dates as `(seconds, nanoseconds)`. Converting to a `Date` might result in an overflow when `seconds > INT64_MAX/1000` (and similar for underflow). 

This is not a problem for Realm files used on Android only, but other bindings might be able to utilize the full range i.e., `seconds > INT64_MAX/1000`.

**Comment by cmelchior** [comment]
I guess the question is if we should either just accept the overflow or clamp it to `Long.MAX_VALUE/Long.MIN_VALUE`

E.g `List.size()` uses Integer.MAX_VALUE for all sizes above that value, but it is arguable an expensive operation to do compared to just accepting whatever overflow there is, and given how little chance there is of this occurring I think I am leaning towards this and just document the behaviour, but what do you think @realm/java ?

**Comment by stk1m1** [comment]
I'll investigate this issue as I need to work on #2707. I'll talk with other binding teams if necessary.

**Comment by kneth** [comment]
Core has some optimized functions for checking for overflow/underflow.

**Comment by stk1m1** [comment]
Thanks @kneth!

I'll make sure to make use/reference out of them.
