### ISSUE TITLE
Upgrade from 0.89.1 Could not find android-adapters-1.0.0

### ISSUE THREAD

**Issue by Honghe** [realm/realm-java#2731]
#### Goal

>  Upgrade from 0.89.1 to 0.90

#### Expected Results

> find android-adapters-1.0.0

#### Actual Results

```
Error:A problem occurred configuring project ':app'.
> Could not resolve all dependencies for configuration ':app:_debugCompile'.
   > Could not find io.realm:android-adapters:1.0.0.
     Searched in the following locations:
         file:/home/honghe/android-studio/gradle/m2repository/io/realm/android-adapters/1.0.0/android-adapters-1.0.0.pom
         file:/home/honghe/android-studio/gradle/m2repository/io/realm/android-adapters/1.0.0/android-adapters-1.0.0.jar
         https://jcenter.bintray.com/io/realm/android-adapters/1.0.0/android-adapters-1.0.0.pom
         https://jcenter.bintray.com/io/realm/android-adapters/1.0.0/android-adapters-1.0.0.jar
         file:/home/honghe/Android/Sdk/extras/android/m2repository/io/realm/android-adapters/1.0.0/android-adapters-1.0.0.pom
         file:/home/honghe/Android/Sdk/extras/android/m2repository/io/realm/android-adapters/1.0.0/android-adapters-1.0.0.jar
     Required by:
```

#### Code Sample
on Module:app build.gradle
```java
dependencies {
    compile 'io.realm:android-adapters:1.0.0'
}
```

#### Version of Realm and tooling
Realm version(s): 0.90.0

Android Studio version: 2.1

Which Android version and device:

**Comment by cmelchior** [comment]
Hi @Honghe 
Yes, we are terribly sorry for that. There was a mixup in testing it, so they where never actually published to JCenter :(

It should be fixed within 24 hours.

**Comment by Honghe** [comment]
@cmelchior You mean the [files](https://bintray.com/package/files/realm/maven/android-adapters?order=asc&sort=name&basePath=io%2Frealm%2Fandroid-adapters%2F1.0.0&tab=files) in the [JCencter/bintray](https://bintray.com/realm/maven/android-adapters) is wrong?

**Comment by cmelchior** [comment]
No, the file there is correct, but someone (_cough_ me), forgot to link it to JCenter. Which means it isn't actually in JCenter yet. 

Until we get it fixed your can use Jitpack instead:

```
 repositories {
        maven { url "https://jitpack.io" }
}

dependencies {
    compile 'com.github.realm:realm-android-adapters:v1.0.0'
} 
```


```

**Comment by wbervoets** [comment]
The jitpack workaround doesn't work for me either.

Wim

**Comment by cmelchior** [comment]
Version 1.0.1 should now be available in JCenter. Sorry for the trouble.
