### ISSUE TITLE
One to Many relationship not able to insert multiple values

### ISSUE THREAD

**Issue by Sutirth** [realm/realm-java#2732]
public class RewardSourceDB extends RealmObject {
    
        @PrimaryKey
        private int id;
        private String name;
        private int type;
        RealmList<RewardsDB> rewardsDB;
    }

    public class RewardsDB extends RealmObject {
    
        @PrimaryKey
        private int rewardId;
    
        private String title;
        private String description;
        private String productBrand;
        private int requiredSweatPoints;
        private int timeLimit;
        private String expiry;
        private int rewardStatus;
        private int userRewardStatus;
        private int totalQuantity;
        private int availableQuantity;
        private String itemCategory;
        private String itemImgUrlPrimary;
        private String itemImgUrlSecondary;
        private int itemPrice;
        private int itemDiscount;
    }

Above 2 are my database tables for the same. For inserting values inside the table I am writing code as follows:

               for(int i =0 ;  i < rewardsModel.getData().size() ; i++){
    
                                                RewardSourceDB rewardsSourceDB =  new RewardSourceDB();
                                                rewardsSourceDB.setId(rewardsModel.getData().get(i).getSource().getId());
                                                rewardsSourceDB.setName(rewardsModel.getData().get(i).getSource().getName());
                                                rewardsSourceDB.setType(rewardsModel.getData().get(i).getSource().getType());
                                                realm.copyToRealmOrUpdate(rewardsSourceDB);
    
    
    
                                                RewardSourceDB sourceDB =  realm.where(RewardSourceDB.class)
                                                        .equalTo("id",rewardsModel.getData().get(i).getSource().getId())
                                                        .findFirst();
    
    
    

    
                                                RewardsDB rewardsQuery = realm.where(RewardsDB.class)
                                                        .equalTo("rewardId",rewardsModel.getData().get(i).getId())
                                                        .findFirst();
    
    
    
    
                                                if(rewardsQuery !=null) {
                                                    rewardsQuery.setRewardId(rewardsModel.getData().get(i).getId());
                                                    rewardsQuery.setTitle(rewardsModel.getData().get(i).getTitle());
                                                    rewardsQuery.setDescription(rewardsModel.getData().get(i).getDescription());
                                                    rewardsQuery.setProductBrand(rewardsModel.getData().get(i).getProductBrand());
                                                    rewardsQuery.setRequiredSweatPoints(rewardsModel.getData().get(i).getRequiredSweatPoints());
                                                    rewardsQuery.setTimeLimit(rewardsModel.getData().get(i).getTimeLimit());
                                                    rewardsQuery.setExpiry(rewardsModel.getData().get(i).getExpiry());
                                                    rewardsQuery.setRewardStatus(rewardsModel.getData().get(i).getStatus());
                                                    rewardsQuery.setTotalQuantity(rewardsModel.getData().get(i).getTotalQuantity());
                                                    rewardsQuery.setAvailableQuantity(rewardsModel.getData().get(i).getAvailableQuantity());
                                                    rewardsQuery.setItemCategory(rewardsModel.getData().get(i).getDetails().getItemCategory());
                                                    rewardsQuery.setItemImgUrlPrimary(rewardsModel.getData().get(i).getDetails().getItemImgUrl1());
                                                    rewardsQuery.setItemImgUrlSecondary(rewardsModel.getData().get(i).getDetails().getItemImgUrl2());
                                                    rewardsQuery.setItemPrice(rewardsModel.getData().get(i).getDetails().getItemPrice());
                                                    rewardsQuery.setItemDiscount(rewardsModel.getData().get(i).getDetails().getItemDiscount());
                                                }else{
                                                    rewardsQuery = realm.createObject(RewardsDB.class);
                                                    rewardsQuery.setRewardId(rewardsModel.getData().get(i).getId());
                                                    rewardsQuery.setTitle(rewardsModel.getData().get(i).getTitle());
                                                    rewardsQuery.setDescription(rewardsModel.getData().get(i).getDescription());
                                                    rewardsQuery.setProductBrand(rewardsModel.getData().get(i).getProductBrand());
                                                    rewardsQuery.setRequiredSweatPoints(rewardsModel.getData().get(i).getRequiredSweatPoints());
                                                    rewardsQuery.setTimeLimit(rewardsModel.getData().get(i).getTimeLimit());
                                                    rewardsQuery.setExpiry(rewardsModel.getData().get(i).getExpiry());
                                                    rewardsQuery.setRewardStatus(rewardsModel.getData().get(i).getStatus());
                                                    rewardsQuery.setTotalQuantity(rewardsModel.getData().get(i).getTotalQuantity());
                                                    rewardsQuery.setAvailableQuantity(rewardsModel.getData().get(i).getAvailableQuantity());
                                                    rewardsQuery.setItemCategory(rewardsModel.getData().get(i).getDetails().getItemCategory());
                                                    rewardsQuery.setItemImgUrlPrimary(rewardsModel.getData().get(i).getDetails().getItemImgUrl1());
                                                    rewardsQuery.setItemImgUrlSecondary(rewardsModel.getData().get(i).getDetails().getItemImgUrl2());
                                                    rewardsQuery.setItemPrice(rewardsModel.getData().get(i).getDetails().getItemPrice());
                                                    rewardsQuery.setItemDiscount(rewardsModel.getData().get(i).getDetails().getItemDiscount());
                                                    sourceDB.getRewardsDB().add(rewardsQuery);
                                                }   
                                            }

So my RewardSourceDb contains 2 entries which should in turn contain multiple entries of rewardDb object. But it always contains one object which overrides the previous. I am confuse as to what I am doing wrong in this scenario?

**Comment by Sutirth** [comment]
My Api from backend 

    {
      "appStatusCode": 0,
      "data": [
        {
          "id": 5,
          "source": {
            "id": 5,
            "name": "MrCarrot",
            "type": 2
          },
          "title": "Amazon Git Coupon 100Rs",
          "description": "Earn this reward for 500 sweatPoints",
          "productBrand": "MrCarrot",
          "requiredSweatPoints": 500,
          "timeLimit": 365,
          "expiry": "2017-02-02T07:30:00Z",
          "status": 1,
          "totalQuantity": 10,
          "availableQuantity": 9,
          "details": {
            "itemId": "1",
            "itemCategory": "employer",
            "itemImgUrl1": "",
            "itemImgUrl2": "",
            "itemPrice": 0,
            "itemDiscount": 0
          }
        },
        {
          "id": 6,
          "source": {
            "id": 5,
            "name": "MrCarrot",
            "type": 2
          },
          "title": "Amazon Git Coupon 400Rs",
          "description": "Earn this reward for 500 sweatPoints",
          "productBrand": "MrCarrot",
          "requiredSweatPoints": 500,
          "timeLimit": 365,
          "expiry": "2017-02-02T07:30:00Z",
          "status": 1,
          "totalQuantity": 10,
          "availableQuantity": 10,
          "details": {
            "itemId": "2",
            "itemCategory": "employer",
            "itemImgUrl1": "",
            "itemImgUrl2": "",
            "itemPrice": 0,
            "itemDiscount": 0
          }
        },
        {
          "id": 7,
          "source": {
            "id": 6,
            "name": "abc123",
            "type": 1
          },
          "title": "New Reward",
          "description": "Earn 400 sweatpoints to clain this reward",
          "productBrand": "abc123",
          "requiredSweatPoints": 400,
          "timeLimit": 365,
          "expiry": "2016-05-25T18:30:00Z",
          "status": 1,
          "totalQuantity": 10,
          "availableQuantity": 10,
          "details": {
            "itemId": "3",
            "itemCategory": "employer",
            "itemImgUrl1": "",
            "itemImgUrl2": "",
            "itemPrice": 0,
            "itemDiscount": 0
          }
        },
        {
          "id": 9,
          "source": {
            "id": 6,
            "name": "abc123",
            "type": 1
          },
          "title": "Test reward 1",
          "description": "This is a description of reward...",
          "productBrand": "abc123",
          "requiredSweatPoints": 5,
          "timeLimit": 365,
          "expiry": "2016-11-30T18:30:00Z",
          "status": 1,
          "totalQuantity": 20,
          "availableQuantity": 19,
          "details": {
            "itemId": "5",
            "itemCategory": "employer",
            "itemImgUrl1": "",
            "itemImgUrl2": "",
            "itemPrice": 0,
            "itemDiscount": 0
          }
        }
      ]
    }

**Comment by Sutirth** [comment]
<img width="343" alt="screenshot 2016-05-04 13 34 57" src="https://cloud.githubusercontent.com/assets/3212997/15008325/2fec2798-11fd-11e6-9b91-f4647cee98a0.png">
<img width="1190" alt="screenshot 2016-05-04 13 35 12" src="https://cloud.githubusercontent.com/assets/3212997/15008326/2ff49de2-11fd-11e6-920c-0c93b1b64a71.png">

**Comment by cmelchior** [comment]
Hi @Sutirth 
From a quick glance it looks like it should work. Are you working from a clean database or one already with data? Because your `rewardsQuery` will find the correct award even though it isn't a child of anything?

You could try to verify it using:

```
if(rewardsQuery !=null) {
  // Verify
  if (sourceDB.getRewardDB().where().equalTo("rewardId", rewardsModel.getData().get(i).getId()).count() == 0) {
    throw new IllegalStateException("Reward was not attached to the proper sourceDB");
  }
  // ...
} ....
```

**Comment by Sutirth** [comment]
Hi @cmelchior 

If I use a fresh database by clearing all the data. It goes into else part and all 4 records are created. Secondly If I call the service the again it throws me illegalStateException

**Comment by cmelchior** [comment]
In that case it means that some of your previous data are not attached to their correct sourceDB, which would explain the behaviour you are seeing.

**Comment by Sutirth** [comment]
@cmelchior  So in order to resolve this what should I do??

**Comment by Sutirth** [comment]
@cmelchior In a fresh install case the RewardSourceDb overwrites and puts only one record which is last in api call.

**Comment by cmelchior** [comment]
You should fix your old data. 

```
  RewardsDB rewardsQuery = realm.where(RewardsDB.class)
                                                    .equalTo("rewardId",rewardsModel.getData().get(i).getId())
                                                    .findFirst();
```

This query is problematic because it will find RewardDB's that are not attached to their correct parent

````
  RewardsDB rewardsQuery = realm.where(RewardsDB.class)
                                                    .equalTo("rewardId",rewardsModel.getData().get(i).getId())
                                                    .findFirst();

  if (sourceDB.getRewardDB().where().equalTo("rewardId", rewardsModel.getData().get(i).getId()).count() == 0) {
    // Attach to correct parent
    sourcesDB.getRewardsDB().add(rewardsQuery);
  }

// ...
```
Is a hack, but should fix it for all faulty data.

**Comment by Sutirth** [comment]
Hi @cmelchior 

Tried the way. But its same scenario over all RewardsSourceDb - > RewardDB(1st entry) success.
RewardsSourceDb - > RewardDB(2nd entry) which overwrites the one in linking process.

**Comment by cmelchior** [comment]
I think this is happening because you are calling this each time:
```
RewardSourceDB rewardsSourceDB =  new RewardSourceDB();
rewardsSourceDB.setId(rewardsModel.getData().get(i).getSource().getId());
rewardsSourceDB.setName(rewardsModel.getData().get(i).getSource().getName());
rewardsSourceDB.setType(rewardsModel.getData().get(i).getSource().getType());
realm.copyToRealmOrUpdate(rewardsSourceDB);
```

It will effectively reset your rewardDB list as it is empty when doing the `copyToRealmOrUpdate` which means that Realm will clear it.

Instead do this:

```
int sourceDbId = rewardsModel.getData().get(i).getSource().getId();
RewardSourceDB sourceDB =  realm.where(RewardSourceDB.class)
                                                    .equalTo("id",sourceDbId)
                                                    .findFirst();
if (sourceDB == null) {
  // Create it
  sourceDB = realm.createObject(RewardsSourceDB.class);
  // set fields
} else {
  // manually update the fields. Calling copyToRealmOrUpdate will reset the list
  sourceDB.setName(...)
  sourceDB.setType(...)
}
```

**Comment by Sutirth** [comment]
Hi @cmelchior  You are right. I did a mistake by using copyToRealmUpdate this resolves the issue. Thnx a ton for help
