### ISSUE TITLE
Document how LoganSquare and Realm can work together

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#2735]
See http://stackoverflow.com/questions/36933091/could-not-be-mapped-to-a-json-object-in-logansquare

**Comment by cbush** [comment]
We are revamping the Realm docs. We're not ignoring this issue -- we've read through every one of them, and we'll be sure to address this as part of our updates. We're closing the GitHub issues and creating new JIRA tickets to track the work at a high level.

**Comment by Zhuinden** [comment]
Although you probably don't want to use the same object for your API response and your Realm schema anyway.
