### ISSUE TITLE
might be a dumb question, but how to import all the samples into android studio?

### ISSUE THREAD

**Issue by 1and1get2** [realm/realm-java#2736]
I can only import root folder without getting errors, however, nothing shows in android project view on the left of the screen

#### Version of Realm and tooling
Realm version(s): ?
9
Android Studio version: ?
2.1
Which Android version and device: ?

**Comment by cmelchior** [comment]
If you cloned our repository, you need to open the `examples` subfolder specifically. Our repo consists of a number of Gradle projects and the top-level one is just hooks into some of our most commonly used tasks in the other projects.

**Comment by 1and1get2** [comment]
thanks for such a fast reply ( i really wasn't expecting this), and pointing me to the right direction, it seems that the issue was mavenLocal() doesn't function on my machine. 
problem resolved by adding 
` maven {
                url 'http://oss.jfrog.org/artifactory/oss-snapshot-local'
            }`  into both repositories {}

>

**Comment by 1and1get2** [comment]
BTW, I was getting error: when trying to use gradle  version 2.1, rolling back to 1.5.0 can make the error go away
