### ISSUE TITLE
Realm Not able to  pass one extra value to my Adapter

### ISSUE THREAD

**Issue by vivek7c** [realm/realm-java#2737]
Hi All,

I have a realm Class called Game and have a property called "showDate" as shown below

   @SerializedName("show_date")
    @Expose
    @Ignore
    private Boolean showDate;

The use of this variable is to pass a custom value in to an Adaptor. I have fetch the data using a realm query  **realm.where(Game.class).equalTo("live", Boolean.FALSE).findAll()** and after that I set value to "showDate" variable manually using a for loop. But Once I have passed it to an adaptor 

new MatchesListRecyclerAdapter(getApplicationContext(), **allList**, MatchesListCalenderActivity.this)

the value got overwritten and not getting in adaptor.I am getting null instead!

1.I am not sure why it is happening. I believe Game Object is tightly coupled with Realm Session.Is it correct?
2. Is there any work around I can do to avoid the issue?

Thanks in advance.
Vivek

**Comment by cmelchior** [comment]
How are you setting the value if a for-loop? Unless you are saving the result somewhere, it will be override when a change is detected.

e.q
```
RealmResults<Game> result = realm.where(Game.class).equalTo("live", Boolean.FALSE).findAll();
for (Game g : result) {
  g.setShowDate(date);
}
new MatchesListRecyclerAdapter(getApplicationContext(), allList, MatchesListCalenderActivity.this)
```

 Will not work since RealmResults do not save that change

```
Game g1 = results.get(0);
Game g2 = results.get(0);
g1 != g2 but g1.equals(g2);
```

If you want to save the a temporary variable you need to save a list of all the objects:
```
RealmResults<Game> result = realm.where(Game.class).equalTo("live", Boolean.FALSE).findAll();
List<Game> customList = new ArrayList<>(result.size());
for (Game g : result) {
  g.setShowDate(date);
  customList.add(g);
}
new MatchesListRecyclerAdapter(getApplicationContext(), customList, MatchesListCalenderActivity.this);
```

**Comment by vivek7c** [comment]
Hi Christian Melchior,
Many thanks for the quick help. I will update you the result.
Regards
Vivek

**Comment by vivek7c** [comment]
Hi Melchior,

Still I am getting null only for all the variables I have set it manually including **monthName**, which is hardcoded!!
public static List<Game> manipulateDataForDisplay(List<Game> results) {
        List<Game> customList = new ArrayList<Game>(results.size());
        Date currentDate = null;
        for (Game game : results) {
            game.setShowMonth(true);
           ** game.setMonthName("Feb");        **
            customList.add(game);
        }
        return customList;
    }

Could you please take a look in to the code!!

Regards
Vivek

**Comment by vivek7c** [comment]
Oh.. I am sorry. I was using results.get(i) earlier and it is refetching from DB. It is working now.

Many thanks for the help Christian Melchior.

Closing this issue.
