### ISSUE TITLE
RealmResults<E> not auto-update

### ISSUE THREAD

**Issue by Honghe** [realm/realm-java#2738]
#### Goal

> RealmResults<E> auto-update.
> And also test RealmObject auto-update partially, is OK. But not sure whether all the RealmObject auto-update functionalities is OK.

#### Expected Results

> RealmResults<E> auto-update

#### Actual Results

>  RealmResults<E>  not auto-update
>  See the code comment 
> [https://github.com/Honghe/test_realm_autoupdate/blob/fc8a2570cf64ec809ade3978429e7d4ea01f3d40/app/src/main/java/top/honhe/test_realm_autoupdate/MainActivity.java#L58](https://github.com/Honghe/test_realm_autoupdate/blob/fc8a2570cf64ec809ade3978429e7d4ea01f3d40/app/src/main/java/top/honhe/test_realm_autoupdate/MainActivity.java#L58)

#### Steps & Code to Reproduce

> Test the following git code

#### Code Sample

[https://github.com/Honghe/test_realm_autoupdate.git](https://github.com/Honghe/test_realm_autoupdate.git)

#### Version of Realm and tooling
Realm version(s): 0.90.0, 0.89.1

Android Studio version: 2.1

Which Android version and device:

**Comment by beeender** [comment]
Hi, that is the expected behaviour we introduced in 0.89+
See https://realm.io/news/realm-java-0.89.0/ Stable iterators for more details.

**Comment by Honghe** [comment]
@beeender 
Got it.
> With 0.89, the auto-updating feature of RealmResults have changed slightly so instead of RealmResults being live all the time, they are now only updated on Looper events.

In this case, the first example in [https://realm.io/docs/java/latest/](https://realm.io/docs/java/latest/) should be modified = =!

**Comment by Zhuinden** [comment]
If you truly want to force the RealmResults to update, you can however still access the package-private method of `realmResults.syncIfNeeded()`

There's also some kind of `waitForChange()` and `stopWaitForChange()` thing going on, but I don't really understand what it does.

**Comment by Honghe** [comment]
@Zhuinden 
waitForChange() is more suited for use-cases where you can’t use the async API (because it requires a Looper thread).
calling waitForChange() will block the current Thread until a commit happens in the background or you call stopWaitForChange(), which will stop the wait of the Thread that called waitForChange().
Check this [Gist](https://gist.github.com/cmelchior/8786ec511f7e1f47673935a26f568106) example.
