### ISSUE TITLE
Openssl vulnerabilities

### ISSUE THREAD

**Issue by degea9** [realm/realm-java#2749]
According to announcement from Google

> Beginning July 11, 2016, Google Play will block publishing of any new apps or updates that use older versions of OpenSSL. If you’re using a 3rd party library that bundles OpenSSL, you’ll need to upgrade it to a version that bundles OpenSSL 1.02f/1.01r or higher.

>The vulnerabilities were addressed in OpenSSL 1.02f/1.01r. The latest versions of OpenSSL can be downloaded here. To confirm your OpenSSL version, you can do a grep search for ($ unzip -p YourApp.apk | strings | grep "OpenSSL").

I have created a small application to test which OpenSSL version is currently using in Realm and the result is OpenSSL 1.0.1p as below
![screen shot 2016-05-09 at 8 56 51 am](https://cloud.githubusercontent.com/assets/3315574/15102270/8bdf67ea-15c7-11e6-902f-0ec991992086.png)

Is this safe ? If not,have any plans to update new version to fix this issue ?

**Comment by kneth** [comment]
@degea9 We are using a very small subset of the OpenSSL library. But we do monitor the developments and vulnerability alerts, and we are currently working on upgrading our storage engine to use the latest version.

**Comment by kneth** [comment]
I have done  `git diff OpenSSL_1_0_1p OpenSSL_1_0_1t` of a clone of the OpenSSL git repository, and I can see any changes between version 1.0.1p and 1.0.1t in the subset we are using. So the answer to your question: yes, using Realm with encryption is safe.

Anyway, as you mention (details can be found at https://support.google.com/faqs/answer/6376725?hl=en), we will need to upgrade OpenSSL.

**Comment by degea9** [comment]
Thank you for the quick reply.I am waiting the next version of Realm will resolve this issue.

**Comment by beeender** [comment]
OpenSSL 1.0.1t is released with 0.90.1.

**Comment by cmelchior** [comment]
Actually it is not included before 0.91 #2790

**Comment by daleep-o2** [comment]
The version of OpenSSL used by Realm has been updated to 1.0.1t, so there is no longer an issue with submitting APKs to the Play Store.

However, the OpenSSL web site suggests that all support for the 1.0.1 branch will be discontinued on 31st December 2016 (https://www.openssl.org/source/).

It would therefore make sense to start using 1.0.2 some time before then.

**Comment by kneth** [comment]
@daleep-o2 You are absolutely right. I have created #3297 to track it.
