### ISSUE TITLE
Realm Kotlin Resolve$SymbolNotFoundError using inner class companion object

### ISSUE THREAD

**Issue by NitroG42** [realm/realm-java#2757]
###### Version of Realm and tooling
Realm version(s): 0.90.0
Android Studio version: 2.1.0

This bug is edited because i finally found a way to reproduce it, see below for a sample.

###### Bug
Using Kotlin and Realm, if we have a class like this one :
```
class Model() {
    enum class MyEnum(val str: String) {
        ONE("MyStr");

        companion object {
        }
    }
}
```
Building with command line ( ./gradlew clean assembleDebug ) give the following output :
**java.lang.ClassCastException: com.sun.tools.javac.comp.Resolve$SymbolNotFoundError cannot be cast to com.sun.tools.javac.code.Symbol$ClassSymbol**

This is the weirdest bug I have ever had. 
- If the enum has an Int attribute instead of a String one, it works.
- If we remove the companion object, it works.
- If we remove kapt { generateStubs = true } in the build.gradle, it works (but this not a good solution has many libraries requires this).

Sample :
[RealmSample.zip](https://github.com/realm/realm-java/files/256916/RealmSample.zip)

I will create a bug on the kapt side to be sure all part are aware of this (as the problem might not come from your side).
Edit : https://youtrack.jetbrains.com/issue/KT-12257

**Comment by NitroG42** [comment]
I just updated my issue with a sample project that reproduces the error. Thank you guys if you have some time to look at this.

**Comment by cmelchior** [comment]
Hi @NitroG42 
Sorry for being late getting back to you.
I tried running your sample project, but everything compiled for me from the commandline.
Also, that model class you posted is not a Realm model class, is that intentional?

Just a guess, but maybe it is related to the version of Java. I am using 

```
java version "1.8.0_25"
Java(TM) SE Runtime Environment (build 1.8.0_25-b17)
Java HotSpot(TM) 64-Bit Server VM (build 25.25-b02, mixed mode)
```

**Comment by NitroG42** [comment]
No problem, now I found where it comes from, I could easily find a workaround (I just created another file with the enum).
For the model, it is intentionnal, actually my project stopped compilling as soon as I integrated Realm, that's why I created a bug report here and on the Kotlin bug tracker.

I just downloaded my sample to be sure, and got the same error. Here's my gradle version : 
nitrog42@NitroMBA-2:~/Downloads/sample/RealmSample $ ./gradlew -version

------------------------------------------------------------
Gradle 2.13
------------------------------------------------------------

Build time:   2016-04-25 04:10:10 UTC
Build number: none
Revision:     3b427b1481e46232107303c90be7b05079b05b1c

Groovy:       2.4.4
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_74 (Oracle Corporation 25.74-b02)
OS:           Mac OS X 10.11.4 x86_64

I'll try with a different jvm.

**Comment by NitroG42** [comment]
OK I tried with a 1.7 JVM (  JVM:          1.7.0_71 (Oracle Corporation 24.71-b01) ) and 1.6 same problem.
Well it might be a problem from kapt but what worries me right now is that you couldn't reproduces it !
Are you on Windows or Mac ? 

as soon as I unzipped the project : 

```
./gradlew assembleDebug
Starting a new Gradle Daemon for this build (subsequent builds will be faster).
Incremental java compilation is an incubating feature.
:app:preBuild UP-TO-DATE
:app:preDebugBuild UP-TO-DATE
:app:checkDebugManifest
:app:preReleaseBuild UP-TO-DATE
:app:prepareComAndroidSupportAnimatedVectorDrawable2330Library UP-TO-DATE
:app:prepareComAndroidSupportAppcompatV72330Library UP-TO-DATE
:app:prepareComAndroidSupportSupportV42330Library UP-TO-DATE
:app:prepareComAndroidSupportSupportVectorDrawable2330Library UP-TO-DATE
:app:prepareComGetkeepsafeRelinkerRelinker121Library UP-TO-DATE
:app:prepareIoRealmRealmAndroidLibrary0900Library UP-TO-DATE
:app:prepareDebugDependencies
:app:compileDebugAidl UP-TO-DATE
:app:compileDebugRenderscript UP-TO-DATE
:app:generateDebugBuildConfig UP-TO-DATE
:app:mergeDebugShaders UP-TO-DATE
:app:compileDebugShaders UP-TO-DATE
:app:generateDebugAssets UP-TO-DATE
:app:mergeDebugAssets UP-TO-DATE
:app:generateDebugResValues UP-TO-DATE
:app:generateDebugResources UP-TO-DATE
:app:mergeDebugResources UP-TO-DATE
:app:processDebugManifest UP-TO-DATE
:app:processDebugResources UP-TO-DATE
:app:generateDebugSources UP-TO-DATE
:app:incrementalDebugJavaCompilationSafeguard UP-TO-DATE
:app:compileDebugKotlin UP-TO-DATE
:app:compileDebugJavaWithJavac
:app:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
:app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> java.lang.ClassCastException: com.sun.tools.javac.comp.Resolve$SymbolNotFoundError cannot be cast to com.sun.tools.javac.code.Symbol$ClassSymbol

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.
```

**Comment by cmelchior** [comment]
Mac, my JVM is a little older, but I would be surprised if that was it ... strange.
```
------------------------------------------------------------
Gradle 2.13
------------------------------------------------------------

Build time:   2016-04-25 04:10:10 UTC
Build number: none
Revision:     3b427b1481e46232107303c90be7b05079b05b1c

Groovy:       2.4.4
Ant:          Apache Ant(TM) version 1.9.6 compiled on June 29 2015
JVM:          1.8.0_25 (Oracle Corporation 25.25-b02)
OS:           Mac OS X 10.11.4 x86_64
```

**Comment by cmelchior** [comment]
I had two other people trying to build your project and they all work. It sounds like something in your setup, although it is a bit mysterious

**Comment by NitroG42** [comment]
Ok, I tried on a coworker computer, it works too. I don't know what causes that.  I'll investigate and let you know if I find anything.

**Comment by NitroG42** [comment]
Ok, the bug doesn't come from neither Kotlin nor Realm
It's because I had Android SDK Platform-tools installed in version 24.0.0-rc2 instead of 23.0.2
Sorry for the disturbance ! (And thanks for looking at this)
