### ISSUE TITLE
ArrayIndexOutOfBoundsException occurs when receiver calls Realm.getDefaultInstance()

### ISSUE THREAD

**Issue by maryangmin** [realm/realm-java#2764]
We have function of receiver when phone called and alarm by periodical time.

In the receivers, we call Realm.getDefaultInstance() and it occasionally fires ArrayIndexOutOfBoundsException.

I don't know why it happens. Do you have any idea about it? I attach crash log below.

http://crashes.to/s/7aa35297440
The line in CallReceiver is Realm.getDefaultInstance().

Thanks.

**Comment by beeender** [comment]
Do you have any logic in source code to restart the app?

**Comment by rfrost77** [comment]
I put migration logic in BaseApplication cause onCreate in Application is called when receiver called. 

In CallReceiver I don't have any Realm logic before Realm. getDefaultInstance().

**Comment by beeender** [comment]
I mean, do you have any logic that to quit current app process and send an intent to start an activity in a new process?

**Comment by rfrost77** [comment]
Yes like below code that clears all task and start new activity.

```
context.startActivity(new Intent(context, SigninActivity.class)
                .addFlags(Intent.FLAG_ACTIVITY_CLEAR_TASK | Intent.FLAG_ACTIVITY_NEW_TASK));
finish();
```

Does It affect receivers?

**Comment by beeender** [comment]
I have a theory that it might cause mulit-process concurrency problem. But I haven't confirm it yet.

In above function, before calling `finish()`, is all Realm instance closed?

**Comment by rfrost77** [comment]
I put Realm.close() in onDestroy() but I'm not sure all instances are closed.

Then, how can I close all Realm instances though I don't know how many instances are alive?

**Comment by beeender** [comment]
Give me some time, I will try to verify the theory i mentioned. If it is true, it might be worth to have a method "Realm.closeAll()`

**Comment by rfrost77** [comment]
I hope good news.

**Comment by cmelchior** [comment]
We talked about `Realm.closeAll()` before, and while it certainly has some nice usages, you also have a pretty big chance of accidentally closing Realms that are still being accessed, which will result on other crashes.

That might not stop us from actually implementing it, but if there is some other way, it would be much more preferable I think.

**Comment by rfrost77** [comment]
I also want to close each realm instance safely, but login token checking is essential you know, and it causes logout to users, which fires situation above.

Anyway, I would find other ways while waiting closeAll(). Thanks.

**Comment by Zhuinden** [comment]
Wait a second, does `FLAG_ACTIVITY_NEW_TASK` open a **new process**?

That's the flag that you have to use if you want to start an Activity using a non-Activity context according to the exception. That'd be some really problematic side-effect.

**Comment by beeender** [comment]
@Zhuinden no, it doesn't .... generally, but it quite difficult to explain the problem should only happen if there are  multi-processes accesses ... I am just guess there are some modified rom **might** create a new process in some conditions. But till now, i cannot find any evidence to prove that.

**Comment by cmelchior** [comment]
Outdated as the code in question has changed quite a lot.

**Comment by Zhuinden** [comment]
Not to mention, this was only possible if the schema was altered from a different process of an open realm, or something.
