### ISSUE TITLE
Date Sorting Changed/ Broken in .90

### ISSUE THREAD

**Issue by gllowmas** [realm/realm-java#2770]
There seems to be a bug with Sort.ASCENDING . In 88.3 this was working properly. 

#### Expected Results

I/System.out: dates:::Nov 20, 2012
I/System.out: dates:::Aug 03, 2012
I/System.out: dates:::Jul 23, 2013
I/System.out: dates:::Apr 17, 2013
I/System.out: dates:::Apr 14, 2014
I/System.out: dates:::Jul 17, 2014
I/System.out: dates:::Sep 11, 2014
I/System.out: dates:::Mar 14, 2015

#### Actual Results

I/System.out: dates:::Nov 20, 2012
I/System.out: dates:::Jul 23, 2013
I/System.out: dates:::Aug 03, 2012
I/System.out: dates:::Apr 17, 2013
I/System.out: dates:::Apr 14, 2014
I/System.out: dates:::Jul 17, 2014
I/System.out: dates:::Sep 11, 2014
I/System.out: dates:::Mar 14, 2015

#### Version of Realm and tooling
Realm version(s):  .90

**Comment by gllowmas** [comment]
It looks like the sort method before .9 would set the RealmResults object in the on sort. 

In 88.3 this would sort TestResutsRecordSet.
TestResultsRecordSet.sort("drawn_on");

In 90.0 you have to set the recordset to the sorted set. 
TestResultsRecordSet = TestResultsRecordSet.sort("drawn_on");

**Comment by rad182** [comment]
@gllowmas thanks for the info! been struggling about this issue for days.
