### ISSUE TITLE
Inconsistent query results outside a transaction

### ISSUE THREAD

**Issue by anandvenkatanarayanan** [realm/realm-java#2773]
#### Goal

1. I have two threads which access Realm in r/w fashion (both of them do read and writes). 

1. Thread 1 is the standard Android Looper thread (GUI thread) and thread 2 is a background thread that keeps running for the duration of the application. 

1. Thread 1 adds a local object to the DB using copyOrUpdateToRealm() semantics and then asks Thread 2 to send this object to the network via a Web Socket. 

1. Thread 2 sends this object to the web socket and on return, deletes the old object and inserts the new object. 

The Code fragment to achieve the above is shown below: 

#### Add Object to Realm

```java
// Get Realm Instance
Realm = realmInstance()

// Get DB Message from Message using POJO conversion and add it to DB
DbMessages dbMessage = DbMessages.from(message);

// Store it's Internal ID
Long value = dbMessage.getInternalID();
realm.beginTransaction();
realm.copyToRealmOrUpdate(dbMessage);
realm.commitTransaction();

// Close realm
realm.close();

// Send message to network
sendMessage(message);
return value;
```

#### Delete Local message from DB
```java
 // Server has acknowledged the message because it is played back on the web socket. 
 // Remove the local copy.         
Realm realm = realmInstance();
 DbMessages existing = realm.where(DbMessages.class)
                               .equalTo(DbMessages.MID, message.getInternalId())
                               .findFirst();
 realm.executeTransaction(realm1-> {

         if (null != existing) {
             Log.d("copyToRealm", "Delete Successfull");
             existing.deleteFromRealm();
        } else {
             Log.d("copyToRealm", "Delete FAILED!!");
       }
});
realm.close();
```
The above deletion code does not work always as findFirst() returns NULL. However if I modify the above code by putting the findFirst() within a transaction block, then it works all the time. 

```java
Realm realm = realmInstance();
 realm.executeTransaction(realm1-> {

              // Server has acknowledged the message because it is played back on the web socket. 
             // Remove the local copy.  
             DbMessages existing = realm.where(DbMessages.class)
                .equalTo(DbMessages.MID, message.getInternalId())
                .findFirst();
            if (null != existing) {
                Log.d("copyToRealm", "Delete Successfull");
                existing.deleteFromRealm();
            } else {
                Log.d("copyToRealm", "Delete FAILED!!");
            }
        });
realm.close()
```

Note that this was working perfectly w/o the wrapping of transaction on Realm 0.88.3. 

#### Version of Realm and tooling

Realm version(s):  0.90.0

Android Studio version: 2.1

Which Android version and device: From Android 5.1

**Comment by beeender** [comment]
`Delete Local message from DB` this section happens in which thread? Does that thread have a looper?

**Comment by anandvenkatanarayanan** [comment]
Delete Local message happens from a background thread started by the application which handles incoming and outgoing web socket notifications (during app startup). It is not a Looper thread.

**Comment by beeender** [comment]
If it is not a looper thread, then it won't be auto-updated -- which means it could be stay on an old version of Realm. You can call `Realm.refresh()` to move the realm version forward. Or you can just open/close an Realm instance whenever you need it in the thread. if the Realm instance is the first one opened in the thread, i will point to the latest version.

PS. `Realm.refresh()` is deprecated, which is replaced by `Realm.waitForChange()`. I am not quite if your use case it a good example that we should keep `Realm.refresh()`.

**Comment by anandvenkatanarayanan** [comment]
I am not sure if I understood the paradigm correctly here. What I always thought was, irrespective of the threads doing read or write, 

Thread(X) on Time(T):  
Realm realm = realmInstance();
realm.executeTransaction(realm1-> do inserts/modifications/writes/deletes); 
realm.close(); 

Thread(Y) on Time(T+5):
Realm realm = realmInstance();
DbMessage message = realm.where(clazz).equalTo(ID, VALUE).findFirst();

Assuming that the transaction on Thread(X) did succeed and did complete before (T+5), this means that the query in Thread(Y) should return back a valid value right? And since it does not work w/o wrapping inside a transaction as of 0.90.0, should I do the following? 

Thread(Y) on Time (T+5)
Realm realm = realmInstance();
realm.refresh() (OR) realm.waitForChange()
DbMessage message = realm.where(clazz).equalTo(ID, VALUE).findFirst();

But the waitForChange() is problematic because it blocks and will stop the web socket thread from receiving any thing else from the network, given that refresh() is deprecated. How else should I use realm to get this use case right? 

What changed b/w 0.88.3 and 0.90 that changed the behaviour, given that I did not have to do this on 0.88.3?

**Comment by Zhuinden** [comment]
You could for example make Thread(Y) into a looper thread, that way it'd get auto-refreshed by Realm on the next Looper event.

https://realm.io/docs/java/latest/#auto-refresh

**Comment by anandvenkatanarayanan** [comment]
Hmnn. Did not think of that one!! After modifying the code that handles WS notifications to post messages to a looper thread, which then queries realm, the problem seems to disappear. The code structure now becomes: 

Thread(X) => Looper Thread for UI => Adds a temporary message to the local realm DB => Sends it to network. 

Thread(Y) => Handles WS notifications => Posts Messages to Looper Thread Z. 

Thread (Z) => Looper thread => Performs Realm Queries and then deletes the temporary object in DB. 

Doing this approach seems reasonable, but is non-obvious for folks who are used to normal transaction semantics. It looks like every thread has it's own version of realm objects and this version either needs to be refreshed manually or automatically. I wonder what is the advantage of such an approach, since it adds complexity for the db clients as well as for realm as well.

**Comment by Zhuinden** [comment]
It's because of MVCC according to [this](https://realm.io/news/jp-simard-realm-core-database-engine/) and [this](https://realm.io/news/threading-deep-dive/)

> An MVCC database like Realm takes an alternative approach: Each connected thread will see a snapshot of the data at a particular point in time. [...] Realm is a bit different than a true MVCC database though. With a true MVCC, like git, you can have multiple candidates for what will become the HEAD of the tree. With Realm, only a single writer can be operating at any time and will always work on the latest version - it cannot work on an earlier one.

**Comment by anandvenkatanarayanan** [comment]
OMG! Just did not pay attention to the word MVCC till now. This is too cool 👍 . So realm is just GIT in a local device and background threads see a version of the DB which may not be the latest unless forwarded to the latest version. However that raises another Question. Querying results on a back ground thread (to avoid ANR issue) to update the UI (where BG thread is not a looper) is almost an anti-pattern here because of the API semantics of waitForChange(), which blocks until a new version is available. refresh() is deprecated but actually fits the bill very nicely to do something like: 

new AsyncTask<X,Y,Z>().execute() {
   doInBackground() {
          Realm realm = realmInstance();
          realm.refresh();
          RealmResults<XX> results = queryObject();
          updateAdapterWithResults(results); 
   }
}

Am i correct in concluding that this construct is not a very efficient, correct and reactive way to update the UI when other objects are added to the DB via different threads. Going through the use cases in my head again, I think that the reasoning for refresh() to be deprecated is sound and waitForChange() is a reasonable and a far better alternative. But given that AsyncTask.execute() pattern in android is very widespread, a better API would be waitForChange(timeout) that will return if nothing changed in the given timeout period, rather than indefinite blocking. It might just make it easier for those coming from SQLite background to adopt realm faster. 

Meanwhile you can close this issue as it answered my original Question...

**Comment by beeender** [comment]
@anandvenkatanarayanan Actually you can use our async API to do async queries
See doc https://realm.io/docs/java/latest/#asynchronous-queries

In a noon-looper thread which needs to both waiting changes from web-socket and Realm might not be ideal. I would like to use dedicate thread to route web-socket event as a handler event and use handler to do event loop. But it is off-topic :P 

I am closing the issue now. Thanks a lot for the feedback!

**Comment by Zhuinden** [comment]
@anandvenkatanarayanan you don't need to use `realm.refresh()` right after you open the Realm, because you see the newest snapshot at the time of opening.

I made the same mistake, it's *really* not needed - and for some reason didn't work for me in 0.89.0+ either :stuck_out_tongue_winking_eye:
