### ISSUE TITLE
Unable to use shared Realm db on Nexus 6P

### ISSUE THREAD

**Issue by dkpalmer** [realm/realm-java#2777]
#### Goal

Share a Realm db between iOS and Android. Database is generated in Swift and copied over to Android project.

#### Expected Results

Assuming models are consistent between iOS and Android, Realm db can be shared between projects and usable on all devices w/o migration.

#### Actual Results

When run on an emulator or a Nexus 5, works as expected: able to get a Realm instance and read from db.

When run on a (physical) Nexus 6P, getting a Realm instance results in RealmMigrationNeededExceptions with semi-random reasons, e.g.:
  - The XYZ class is missing from the schema for this realm. (class varies)
  - Field 'A' not found for type BCD. (field and class has been consistent here)

Note: Not reproducible in Nexus 6P Emulator, just device

#### Steps & Code to Reproduce

- Clean build
- Uninstall app from Nexus 6P
- Install on Nexus 6P
- Exception (100% reproducible)

I've also opened the database using Realm Browser, saved the Java and Swift model definitions out, and rebuilt the database and my app using them.

#### Version of Realm and tooling
Realm version(s): Android 0.89.1 and 0.90.0, Swift 0.98.8 and 0.101.0

Android Studio version: 2.1

Which Android version and device: Nexus 6P, Android 6.0.1

**Comment by zaki50** [comment]
Hi @dkpalmer 

Please make sure `Instant Run` is **off**.

![instantrun](https://cloud.githubusercontent.com/assets/406660/15190036/b7978ae2-1762-11e6-9916-05ffa87f186e.png)

If your Instant Run setting is on, please switch to off and clean project.

**Comment by dkpalmer** [comment]
Instant Run was indeed off for all of the above.

**Comment by cmelchior** [comment]
Hi @dkpalmer That sounds really strange. If it is something you can reproduce, can you share your project with us? If you want to do it privately you can do so via help@realm.io

**Comment by dkpalmer** [comment]
I can't share the project as-is, but I've started ripping out to an empty project to hopefully reproduce there for sharing.

Quick update: In a completely empty project with just my models, code to copy Realm db from R.raw to files dir, and a quick and dirty opening of a default Realm instance, I do _not_ encounter the crash on my N6P. I am slowing porting over different parts of my app to see where the problem is.

**Comment by emanuelez** [comment]
@dkpalmer ok, thank you very much!

**Comment by dkpalmer** [comment]
After several hours of troubleshooting, I went back to a known working tag and actually looked at my app. I realized that my app wasn't actually in a fresh state after an uninstall/reinstall. Android's Auto Backup was restoring an old database :/. Hence the need for migration.

Apologies for the false alarm.
