### ISSUE TITLE
Update from 0.88.3 to 0.90.0 deletes Realm file, but no exception

### ISSUE THREAD

**Issue by Marcel50506** [realm/realm-java#2778]
The previous version of my app runs Realm-java 0.88.3. Since this version, I did not make any changes to my RealmObjects.

The new version of my app runs Realm-java 0.90.0. When I update, my Realm-file is deleted. I first thought this would be because of the "@Required" change for primary fields in 0.89.0. However, I don't get a RealmMigrationNeededException. I also don't see any other output from Realm after updating my app. I do see my RealmMigration.migrate function is called.

How can I find out where possible errors/schema conflicts occur, or why my RealmFile is being thrown away?

#### Version of Realm and tooling
Realm version(s): 0.88.3 > 0.90.0

Android Studio version: 2.1

Which Android version and device: Moto G (3rd gen) with Android 6.0.1

**Comment by zaki50** [comment]
Hi @Marcel50506 

Are you calling `deleteRealmIfMigrationNeeded()` when you build `RealmConfiguration` instance?

**Comment by Marcel50506** [comment]
No, `deleteRealmIfMigrationNeeded` is not called anywhere in my code. For this version, the migration is not doing anything significant:

    public void migrate(DynamicRealm realm, long oldVersion, long newVersion) {
        // DynamicRealm exposes an editable schema
        RealmSchema schema = realm.getSchema();

        Timber.d("Updating from realm version %d to %d", oldVersion, newVersion);

        ... // migration for older versions

        if (oldVersion == 36) {
            oldVersion ++;
        }
    }

**Comment by beeender** [comment]
@Marcel50506 It would be easier if you can share your old and new apk with us. to help@realm.io

**Comment by beeender** [comment]
internal notes: conversion is going on here https://secure.helpscout.net/conversation/202084557/4257/?folderId=539748

**Comment by stk1m1** [comment]
@Marcel50506
This is being escalated to a bug and we'll keep investigating thorougly.

**Comment by stk1m1** [comment]
I'm closing this issue for now as it's insufficient to collect samples to reproduce.
