### ISSUE TITLE
I have updated my realm 0.81.2 to 0.89.1 and then I added one class after that I wrote my migration code,then error for every field is Field 'name' is required. Either set @Required to field 'name' or migrate using RealmObjectSchema.setNullable() it was working in realm 0.82.1 please reply I am in wid way my app is on play store

### ISSUE THREAD

**Issue by aes009** [realm/realm-java#2783]
> We LOVE to help with any issues or bug you have!

> **Questions**: If you have questions about how to use Realm, please ask on [SO](http://stackoverflow.com/questions/ask?tags=realm) - we monitor the Realm tag.

> **Feature Request**: Just fill in the first two sections below.

> **Bugs**: To help you as fast as possible with an issue or bug please describe your issue and the steps you have taken to reproduce it in as many details as possible.
>
> Thanks for helping us help you :-)
>
> Remove this and above before submitting.

#### Goal

> What do you want to achieve?

#### Expected Results

> ?

#### Actual Results

>  E.g. full stack trace with exception

#### Steps & Code to Reproduce

> Describe your current debugging efforts.

#### Code Sample

```java

> Your code here. Bigger samples should ideally be as separate Android Studio project, 
> in gists/repositories or privately at help@realm.io)

```

#### Version of Realm and tooling
Realm version(s): ?

Android Studio version: ?

Which Android version and device: ?

**Comment by aes009** [comment]
Please reply

**Comment by cmelchior** [comment]
Hi @aes009 
Please follow the template given and the guideline described here https://github.com/realm/realm-java/blob/master/CONTRIBUTING.md#filing-issues when creating issues. That way it will be easier for us to help you.

**Comment by aes009** [comment]
Android studio 2.1
Exception io.realm.exceptions.RealmMigrationNeededException: Field 'name' is required. Either set @Required to field 'neme' or migrate using RealmObjectSchema.setNullable().

I want to do migation
