### ISSUE TITLE
I have updated my realm 0.81.2 to 0.89.1 and then I added one class after that I wrote my migration code,then error for every field is Field 'name' is required. Either set @Required to field 'name' or migrate using RealmObjectSchema.setNullable() it was working in realm 0.82.1 please reply I am in wid way my app is on play store

### ISSUE THREAD

**Issue by aes009** [realm/realm-java#2786]
What do you want to achieve?

I want to migation.

#### Actual Results

io.realm.exceptions.RealmMigrationNeededException: Field 'name' is required. Either set @Required to field 'name' or migrate using RealmObjectSchema.setNullable().

#### Version of Realm and tooling
Realm version(s): 0.89.1

Android Studio version: 2.1

Which Android version and device: All devices

**Comment by stk1m1** [comment]
Hi @aes009 
Could you be kind enough to share your model with us? We've started allowing `null` as a `PrimaryKey` value, and we can help you with your code available to us.

**Comment by aes009** [comment]
public class User extends RealmObject {
    @PrimaryKey
    private long userID;

    private String name;
    private String mobileNumber;}

**Comment by cmelchior** [comment]
Hi @aes009 

In 0.83.0 we added Null support. It means that all your `String` fields must be annotated with `@Required` unless you want do do a migration to change them to nullable. You can read more here: https://realm.io/news/realm-java-0.83.0/

**Comment by aes009** [comment]
In my code there are many model class that contain string field.so how should i do that in migration code.

**Comment by cmelchior** [comment]
You don't have to write migration code. You can just add `@Required` to all your String fields, it means that the Strings are not allowed to be `Null` (which would be the old behaviour)

**Comment by aes009** [comment]
again error
 io.realm.exceptions.RealmMigrationNeededException: Field 'status' does support null values in the existing Realm file. Remove @Required or @PrimaryKey from field 'status' or migrate using RealmObjectSchema.setNullable().

**Comment by aes009** [comment]
All fields that that i have added @Required showing this error.

**Comment by stk1m1** [comment]
@aes009 

The exception can happen when you're to mark old _nullable_ fields with *@Required* for migration to a newer version, in thise case `0.89.1`. You don't have to mark every field as *@Required*. You only need to do those ones you want them to stay as _not nullable_.

In addition, could you share the correct model with us? It seems the last one does not match with the one you posted. Thanks!

**Comment by aes009** [comment]
Thanks.It worked!!!!!
