### ISSUE TITLE
Align un-managed/standalone/un-persisted terminology

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#2789]
Right now, our Javadoc and website documentation is fairly inconsistent when talking about Realm objects that are persisted and those that are not.

After agreement with @jpsim we have decided on the following terminology, that should be consistent across Cocoa/Java:

- Objects that are persisted in Realm should be called "managed objects" or "managed Realm objects"
- Objects not persisted should be called "unmanaged objects" or "unmanaged Realm objects"

The same holds for RealmList.

- [ ] Review Javadoc
- [ ] Review website docs (https://github.com/realm/realm.io/issues/2319)
- [ ] Review code comments

Cocoa issue: https://github.com/realm/realm-cocoa/issues/3566

**Comment by osama-lionheart** [comment]
@cmelchior, would an object copied using `copyFromRealm` be considered as an "unmanaged Realm objects"?

**Comment by nhachicha** [comment]
@osama-lionheart yes, it's a detached copy of the managed `RealmObject`
