### ISSUE TITLE
Not installing

### ISSUE THREAD

**Issue by tolgayildirim** [realm/realm-java#2791]
When I download xcode package manager "Realms Plugin" Download is not complemented end stick on % 30 approximately. Exactly what should I do?

**Comment by beeender** [comment]
Hi, i guess you want to report an issue to https://github.com/realm/realm-cocoa/ instead realm-java?

**Comment by beeender** [comment]
BTW, if you can supply more information when report it to cocoa repo, i believe you can get a quicker response :)

**Comment by tolgayildirim** [comment]
I apologise to you for writing mistake area. Thanks. :)
