### ISSUE TITLE
API docs correction

### ISSUE THREAD

**Issue by carotorrehdz** [realm/realm-java#2792]
Hi guys! I know sorting by child fields isn't allowed but it would be helpful for others if you can update your API docs; since by reading it you'll think you can sort by a child field if you use `findAllSorted("fatherField.childField")` or  `findAllSortedAsync("fatherField.childField")`, without specifying any sort order.
According to the current docs it'll only throw an exception if the field name does not exist.

Here's a screenshot of the correction I'm referring to:
<img width="1092" alt="screen shot 2016-05-12 at 11 32 09 am" src="https://cloud.githubusercontent.com/assets/3819186/15222417/314974f4-1835-11e6-8a62-0af0d91a9cd5.png">

**Comment by cmelchior** [comment]
Hi @carotorrehdz 
Your right, our docs should mention that. Thanks for the nudge.

**Comment by carotorrehdz** [comment]
Your welcome @cmelchior, happy to help!
