### ISSUE TITLE
Realm Migration Issue when adding a new column with Primary key for Android

### ISSUE THREAD

**Issue by bsmn99** [realm/realm-java#2797]
Hi,

I have done with Migrating some adding a new column, but failed when i try to add a new column with **FieldAttribute.PRIMARY_KEY**, it says the following error,

_Illegal Argument: Field "PayeeId" cannot be a primary key, it already contains duplicate values: 0_

Transformation also did to the migration added Field **_PayeeId_** like below

```
Schema.addField("PayeeId",Integer.class, FieldAttribute.PRIMARY_KEY).transform(new RealmObjectSchema.Function()
                {
                    @Override
                    public void apply(DynamicRealmObject obj)
                    {
                        obj.setInt("PayeeId", Utils.GenerateRandom());
                    }
                });
```
How it could be like this? Please help for the solution.

@beeender @timanglade

**Comment by beeender** [comment]
This has been reported here https://github.com/realm/realm-java/issues/2167

See workaround https://github.com/realm/realm-java/issues/2167#issuecomment-175442772

Generally you need to set it with a unique value, then add it as a primary key. Otherwise the default value 0 will be conflicted with others.

**Comment by bsmn99** [comment]
@beeender are u telling me to do like this?

//Transformation Method without setting values inside.
```
RealmResults<DynamicRealmObject> projectResults = realm.allObjects("PayeeList");

for(int i=0;i<projectResults.size();i++)
{
projectResults.get(i).setpayeeId(i);
}
Schema.addPrimaryKey("PayeeId").addIndex("PayeeId");
```

**Comment by beeender** [comment]
Yes! if the `i` is the pk value you want.

**Comment by beeender** [comment]
or you can use `RealmObjectSchema.transform()` to do the iteration and setting. But that requires you to generate the pk through some other ways (no index `i`).

**Comment by bsmn99** [comment]
Which one is best? Suggest a quicker and best.. But i need my pk starting with 0 to incremental.

**Comment by beeender** [comment]
I prefer your simple for loop in this case. Easy to write, obvious `i`.
Speed wise they are similar.They both need to traverse all elements.

**Comment by bsmn99** [comment]
ok @beeender let me try it and come, Thanks a ton.
