### ISSUE TITLE
Migration problem from 0.88.2 to 0.90.1

### ISSUE THREAD

**Issue by Sutirth** [realm/realm-java#2813]
I just upgraded the gradle build and my application is crashing with following log

 io.realm.exceptions.RealmMigrationNeededException: @PrimaryKey field 'eventType' does not support null values in the existing Realm file. Migrate using RealmObjectSchema.setNullable(), or mark the field as @Required.

```java
public class TimelineDB extends RealmObject {

    private String date;

    @PrimaryKey
    private String eventType;

    private int timeLineIdEventType;

    public String getDate() {
        return date;
    }

    private AllGoalsDB allGoalsDB;

    private LeaderBoardDb leaderBoardDb;

    private SweatPointFitnessDB sweatPointFitnessDB;

    private NotificationDB notificationDB;

}
```
Where I have stable Primary key already

**Comment by Sutirth** [comment]
Even I rebuild from IDE and start again I get error as
@PrimaryKey field 'forday' does not support null values in the existing Realm file. Migrate using RealmObjectSchema.setNullable(), or mark the field as @Required.

    public class SweatPointFitnessDB extends RealmObject {
    
        private String distance;
    
        private int stepCount;
    
        @PrimaryKey
        private String forday;
    
        private int userid;
    
        private int calories;
    
        private int sweatpoints;
    
        private String currentMonthNo;
    
        private String currentMonth;
    
        private int goalSweatPoints;
    
        private int BadgeSweatPoints;
    }

**Comment by stk1m1** [comment]
Hi @Sutirth,

The message indicate that you'd need to mark your primary key field with `@Required` such that its behavior is aligned with old one. The final would like below.

```java
@PrimaryKey
@Required
private String eventType;
```
You can also use `RealmObjectSchema.setNullable()` to allow the `eventType` field to accept `null`.

In addition, could you please kindly keep the original questionnaire form for us to help you in an aligned process? it also helps other users get appropriate amount of support as it reduces the amount of time we get to what you'd seek for. 

Thanks in advance.

**Comment by Sutirth** [comment]
@stk1m1 
Apologies for not keeping the questionnaire pattern same. So You mean I just need to add @Required field and no custom migration code right??

**Comment by stk1m1** [comment]
Yup. You just need to mark the field as @Required.

**Comment by Sutirth** [comment]
@stk1m1  Thanks it helps :)

**Comment by GaneshB-Extentia** [comment]
@stk1m1 @Sutirth Do we need add **@Required** annotation for all the fields ? Because I am getting same exception for all other fields also (fields other than primary field) .

**Comment by Sutirth** [comment]
@GaneshB-Extentia  Only primary key should have @Required that worked for me.

**Comment by GaneshB-Extentia** [comment]
@Sutirth I am getting exception for other fields also.

**Comment by GaneshB-Extentia** [comment]
@stk1m1 I am migrating from 0.81 to 1.1

**Comment by stk1m1** [comment]
@GaneshB-Extentia 

Please post your model that causes error by following [the guideline](https://github.com/realm/realm-java/blob/master/CONTRIBUTING.md#filing-issues) so we can provide the best possible support we can. Thanks!
