### ISSUE TITLE
Document and build an example for PrimaryKey

### ISSUE THREAD

**Issue by stk1m1** [realm/realm-java#2814]
#### Goal

As existing apps upgrading from `Pre-0.89.1` Realm, almost identical questions such as #2786 & #2813 keep arriving. Write best practices and examples to help users upgrade.
#### Version of Realm and tooling

Realm version(s): Pre-0.89.1
Android Studio version: 
Which Android version and device:

**Comment by cmelchior** [comment]
Closing this as we didn't have any more support issues around this and the change have been live for quite a while now.

**Comment by Zhuinden** [comment]
Actually, this came up at https://github.com/realm/realm-java/issues/3161
