### ISSUE TITLE
Unable to Sort Queries 

### ISSUE THREAD

**Issue by Sutirth** [realm/realm-java#2816]
Bug: Unable to sort using RealmResults

Goal: Tailored result based on sorting condition provided

Expected Result: To get result in sorting order

Actual Result: Realm is unable to sort

Realm version(s): 0.90.1
was working perfectly on 0.88.2

/*Database code*/
    realm = Realm.getDefaultInstance();
    
        RealmResults<RewardsDB> rewardResult = realm.where(RewardsDB.class)
                                                .equalTo(WorkoutCashConstants.COLUMN_REWARD_STATUS,REWARDS_ACTIVE)
                                                .notEqualTo(WorkoutCashConstants.COLUMN_USER_REWARDS_STATUS,REDEEM_REWARDS)
                                                .findAll();
    
        rewardResult.sort(WorkoutCashConstants.COLUMN_USER_REWARDS_STATUS,Sort.ASCENDING);
    
        if(rewardResult.size()!=0){
            rewardsAllRecyclerView.removeAllViewsInLayout();
            rewardsAllAdapter = new RewardsAllAdapter(rewardResult);
            rewardsAllRecyclerView.setAdapter(rewardsAllAdapter);
            sendAllRewardsBroadcast();
        }

/*Database Table*/
    public class RewardsDB extends RealmObject {
    
        @PrimaryKey
        private int rewardId;
    
        private String title;
        private String description;
        private String productBrand;
        private int requiredSweatPoints;
        private int timeLimit;
        private String expiry;
        private int rewardStatus;
        private int userRewardStatus;
        private int totalQuantity;
        private int availableQuantity;
        private String itemCategory;
        private String itemImgUrlPrimary;
        private String itemImgUrlSecondary;
        private int itemPrice;
        private int itemDiscount;
    }

<img width="1060" alt="screenshot 2016-05-16 18 24 21" src="https://cloud.githubusercontent.com/assets/3212997/15290023/7c941c6e-1b93-11e6-8af1-373e592bf003.png">

**Comment by cmelchior** [comment]
Hi @Sutirth 
`sort` was changed in `0.89` to return a sorted copy instead of being inplace. If you do
```
rewardResult = rewardResult.sort(WorkoutCashConstants.COLUMN_USER_REWARDS_STATUS,Sort.ASCENDING);
```

it should work.

**Comment by Sutirth** [comment]
Hi @cmelchior,

It works. thanks a ton !! May be perhaps documentation should have been updated

**Comment by cmelchior** [comment]
Yes, your right. It seems the website documentation wasn't updated in the process. We will fix that ASAP, thanks.
