### ISSUE TITLE
"Index not defined for existing Realm file" error while performing migration.

### ISSUE THREAD

**Issue by vladiulianbogdan** [realm/realm-java#2819]
Hello,

I'm using Realm 0.90.1.

I'm trying to perform a migration in which I want to create two more tables. One of them has a @PrimaryKey.

I've tried the manual way like this:

And the migration looks like this:

```
          public void migrate(DynamicRealm realm, long oldVersion, long newVersion) {
		RealmSchema schema = realm.getSchema();

		if (oldVersion == 0) {
			schema.create("Table1").addField("myid", long.class)
					.addField("test", boolean.class)
					.addPrimaryKey("myid");

			schema.create("Table2").addField("wID", int.class)
				.addField("uID", int.class)
				.addField("ts", long.class)
				.addField("type", String.class);

			oldVersion++;
		}
```

My applications crashes with the following exception:

`                                                                         
Process: com.vectorwatch.android, PID: 22182 java.lang.RuntimeException: Unable to create application com.android.tools.fd.runtime.BootstrapApplication: io.realm.exceptions.RealmMigrationNeededException: RealmMigration must be provided
                                                                             at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4664)`

I've dived deeper in Realm code and I've saw that an exception is thrown with the following detailsMessage:

`Index not defined for field myid in existing Realm file. Either set @Index or migrate using io.realm.internal.Table.removeSearchIndex().
`

So I assumed that I should call also addIndex() in the migration. This did the trick, but this is was kind of annoying. From the Realm documentation, I see that "(the annotation @PrimaryKey implicitly sets the annotation @Index)". The javadoc of the addPrimaryKey method says:

`
     * Adds a primary key to a given field. This is the same as adding the {@link io.realm.annotations.PrimaryKey} annotation on the field.
`

So I assumed that addPrimaryKey() also adds an Index. It is nowhere mentioned that when performing a migration, you should call addIndex() when you have an addPrimaryKey().

Can I make a pull request to add this use case in your Migration example app? Also please tell if I can help anymore you with this issue.

Thank you very much for this great framework!

**Comment by beeender** [comment]
You could change it to:
```java
schema.create("Table1").addField("myid", long.class, FieldAttribute.PrimaryKey)
                    .addField("test", boolean.class);
```
This will add search index automatically.

But you are right, I think `addPrimayKey` should implicitly add search index as well.

**Comment by stk1m1** [comment]
@vladiulianbogdan 

It's now patched. The next release will contain the bugfix. Thanks for pointing this out.

**Comment by vladiulianbogdan** [comment]
Thank you, guys!
