### ISSUE TITLE
I want to save List<String> in Social class.

### ISSUE THREAD

**Issue by chenzj-king** [realm/realm-java#2825]
As title.  
I want to save List<String> in CommunityData Class.

    public class CommunityData extends RealmObject {

	    @SerializedName("_id")
	    public String id;
	    @SerializedName("title")
	    public String title;
	    @SerializedName("crtime")
	    public String crtime;
	    @SerializedName("status")
	    public int status;
	    @SerializedName("location")
	    public List<String> location;
	
	   
	}

When i build project.It tell me.  

![](http://i.imgur.com/89QCaeN.png) 

only can i use RealmList<T extends ReamlmObject> to save List<Bean\>?

location is a longitude and latitude.  
in other class i need List<String\> in tags field include["text","voice","image"]

can you guide me to solve this problem.

#### Version of Realm and tooling
Realm version(s): 0.90.1

Android Studio version: 2.1.1

Which Android version and device: 5.1

**Comment by beeender** [comment]
Please check this issue https://github.com/realm/realm-java/issues/575
And see a possible workaround here https://github.com/realm/realm-java/issues/1652

I am closing this issue now since it is duplicated to #575

**Comment by chenzj-king** [comment]
@beeender 
Thanks. I do like [https://gist.github.com/bclymer/f569fffb41bab046c2d1](url).It work well.
