### ISSUE TITLE
Cannot delete realm

### ISSUE THREAD

**Issue by JM-Agrimap** [realm/realm-java#2834]
When starting up my app the first thing I am trying to delete the realm file.

The attached screenshot shows that if fails to delete the management directory.
/data/user/0/com.agrimap.mobile.android/files/default.realm.management

I checked the File.delete() method and it internally catches
android.system.ErrnoException: remove failed: ENOTEMPTY (Directory not empty)

The directory appears to have three files in it.
log_acces, log_a, log_b

![screen shot 2016-05-19 at 12 09 12 pm](https://cloud.githubusercontent.com/assets/19274339/15378846/348fa206-1dbb-11e6-9ec6-6b4ca0198e14.png)

#### Version of Realm and tooling
Realm version(s): 0.90.1
Android Studio version: 2.1.1
Which Android version and device: Emulator - Nexus 4

**Comment by beeender** [comment]
Thanks a lot for reporting this! It should be a bug and will be fixed right away.
