### ISSUE TITLE
App crashing 4.X devices. 

### ISSUE THREAD

**Issue by knsarath** [realm/realm-java#2836]
App crashing while initializing Realm configuration. Getting the error 

`05-19 10:12:49.810 10049-10067/? E/AndroidRuntime: FATAL EXCEPTION: Thread-341
                                                   Process: com.kotak.kaypay, PID: 10049
                                                   java.lang.NoClassDefFoundError: io.realm.internal.RealmCore
                                                       at io.realm.RealmConfiguration$Builder.<init>(RealmConfiguration.java:352)`

I'm using realm version `io.realm:realm-gradle-plugin:0.90.1`

and build tools version `buildToolsVersion '23.0.3'`

**Comment by leoouc** [comment]
hi ,i also came into this problem,how you solve it?
