### ISSUE TITLE
App crashing 4.X devices.   java.lang.NoClassDefFoundError: io.realm.internal.RealmCore

### ISSUE THREAD

**Issue by knsarath** [realm/realm-java#2837]
App crashing while initializing Realm configuration. Getting the error 

`05-19 10:12:49.810 10049-10067/? E/AndroidRuntime: FATAL EXCEPTION: Thread-341
                                                   Process:  PID: 10049
                                                   java.lang.NoClassDefFoundError: io.realm.internal.RealmCore
                                                       at io.realm.RealmConfiguration$Builder.<init>(RealmConfiguration.java:352)`

I'm using realm version `io.realm:realm-gradle-plugin:0.90.1`

and build tools version `buildToolsVersion '23.0.3'`

**Comment by emanuelez** [comment]
Hello @knsarath,

In order to help you we need more informations than the ones you provide. We have a template you can use here: https://github.com/realm/realm-java/blob/master/.github/ISSUE_TEMPLATE.md

Also, since this looks like a build issue, it would be nice if you provided your build.gradle files as well.

**Comment by leoouc** [comment]
I came to the same problem, this is my build.gradle:
apply plugin: 'com.android.application'
apply plugin: 'realm-android'
android {
    compileSdkVersion 23
    buildToolsVersion '23.0.3'
    useLibrary 'org.apache.http.legacy'
    defaultConfig {
        applicationId "com.bcgogo.lyx"
        minSdkVersion 16
        targetSdkVersion 23
        versionCode 1
        versionName '1.0.9'
        multiDexEnabled true
    }
    
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    
    sourceSets {
        main {
            jniLibs.srcDirs = ['libs']
        }
    }
    lintOptions {
        abortOnError false
    }
}
dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    testCompile 'junit:junit:4.12'

    compile project(':pull_to_refresh_library')
    compile project(':vitamio')
    compile project(':mylibrary')

    compile 'com.android.support:appcompat-v7:23.4.0'
    compile 'io.netty:netty-all:4.0.36.Final'
    compile 'com.google.protobuf:protobuf-java:2.6.1'
    compile 'com.squareup.okhttp:okhttp-urlconnection:2.7.5'
    compile 'com.mcxiaoke.volley:library:1.0.19'
    compile 'com.google.code.gson:gson:2.6.2'
    compile 'org.greenrobot:eventbus:3.0.0'
    compile 'com.android.support:support-v4:23.4.0'
    compile 'com.android.support:design:23.4.0'
    compile 'com.jakewharton:butterknife:7.0.1'
    compile 'org.apache.httpcomponents:httpcore:4.4.2'
}

**Comment by emanuelez** [comment]
I can see you have multidex enabled. I wonder if it's a case of multidex being naughty and not placing classes in the right dex. Would you be able to stay below the method count limit if you enabled proguard?

**Comment by leoouc** [comment]
@emanuelez I enable proguard,but still exceed the limit,so how can i do?

**Comment by zaki50** [comment]
Hi @leoouc 

To confirm that it's an issue of multides,
Would you try following configuration?

* create following file named `multi-dex-keep.txt` in the same directory as the `proguard-rules.pro`

```
-keep public class io.realm.internal.RealmCore  {
 *;
}
```

* add following line to `build.gradle` right after `multiDexEnabled true`

```
multiDexKeepProguard file('multi-dex-keep.txt')
```

**Comment by leoouc** [comment]
@zaki50 I tried multi-dex-keep.txt as follows, realm works, but another 3rd jar out, multidex digs a big hole for me /(ㄒoㄒ)/~~
-keep public class io.realm.*  {
 *;
}

**Comment by viniciusaires7** [comment]
I have the same problem!

**Comment by viniciusaires7** [comment]
The Realm 0.9x has this problem, in Android 4.x app is crashed on the build of Realm instance!

**Comment by viniciusaires7** [comment]
After hours trying to solve the problem I removed the library google play service (compile 'com.google.android.gms: play-services: 8.4.0') and put only the ones I'm using in my project and Realm work again in versions 4.x Android.

**Comment by Zhuinden** [comment]
In that case, it really was a multidexing issue.

**Comment by bunjix** [comment]
I have the same issue. But I need to keep 
```java 
multiDexEnabled true
```
How can I fixe this issue ?

Working as wanted on 5.x and above.

**Comment by leoouc** [comment]
@bunjix has your app extends MulitDexApplication?

**Comment by bunjix** [comment]
No. Should I expends MultiDexApplication ? I thought I just need to add the multiDexEnabled flag on my gradle flag.

**Comment by Zhuinden** [comment]
Huh? You have to call `Multidex.install()` from the application o-o

    Note: If your app uses extends the Application class, you can override the attachBaseContext() method and call MultiDex.install(this) to enable multidex.

**Comment by bunjix** [comment]
Ok thanks. Now it works.
But at runtime I got some exception like 

> MyClass.java is not part of the schema for this Realm schema

**Comment by bunjix** [comment]
Just found this new [section](https://realm.io/docs/java/latest/#kotlin) of the doc about this error with Kotlin.

**Comment by zaki50** [comment]
@bunjix Does adding @RealmClass annotation to model classes solve your problem?

**Comment by bunjix** [comment]
@zaki50 In fact it depends. Sometimes it works and sometimes not. 
When it does not work 

> class com.blabla.User is not part of the schema for this Realm.
I have to clean the project multiple times, then rebuild it. And then it works (sometimes).

**Comment by zaki50** [comment]
@bunjix Which do you place `apply plugin: 'realm-android'` or `apply plugin: 'kotlin-android' first?

If you place `apply plugin: 'realm-android'` first, please move it after `apply plugin: 'kotlin-android'`.

**Comment by kneth** [comment]
I close the issue due to lack of activity. @bunjix if the suggests above don't solve your issue, please either reopen or create a new issue.

**Comment by KrishHari** [comment]
Facing the same issue.
Is there a way out without making the application Multidex ?

**Comment by zaki50** [comment]
multi-dex-keep.txt doesn't work?

**Comment by KrishHari** [comment]
Multidex will work. But is that only the solution? Because I am making a android library project which has realm plugin. And I can't force the applications that integrate my library to make it MultidexApp

**Comment by Zhuinden** [comment]
Well if you have `multiDexEnabled true` then you need to make it `multi dex application`

**Comment by zaki50** [comment]
That sounds different issue from this.
Reducing method count (by hand or by sonething like Proguard) is the only way to avoid multidex.

**Comment by felixsoares** [comment]
i had the same problem and i solve creating a PrefsApplication, like that

        public class PrefsApplication extends Application {
             @Override
             public void onCreate() {
                   super.onCreate();

                  MultiDex.install(this);

                 Realm.init(this);
           }
        }


in AndroidManifest.xml


        <application android:name=".code.util.PrefsApplication" ....

**Comment by markizdeviler** [comment]
I'm facing same issue. is anyone found the solution. 
I enabled multidex correctly but not working

**Comment by markizdeviler** [comment]
thanks @Zhuinden  fixed my project
issue is related to alpha version of build gradle

**Comment by defaultbr** [comment]
i still have the issue even using https://github.com/realm/realm-java/issues/2837#issuecomment-355956410 and https://github.com/realm/realm-java/issues/2837#issuecomment-318484127


```
public class PontotelApplication extends Application {
@Override
    public void onCreate() {
        super.onCreate();
        MultiDex.install(this);
        Realm.init(this);
...
```


project gradle:

```
        classpath('io.realm:realm-gradle-plugin:4.3.1') {
            exclude group: 'com.android.tools.build', module: 'gradle'
        }
```

app gradle:

```
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-kapt'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'realm-android'


...
 defaultConfig {
...
        multiDexEnabled true
...
    }
```



```
   java.lang.NoClassDefFoundError: io.realm.Realm
                                                                  at lar21.pontotel.PontotelApplication.initRealm(PontotelApplication.java:137)
                                                                  at lar21.pontotel.PontotelApplication.onCreate(PontotelApplication.java:77)
                                                                  at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1007)
                                                                  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4541)
                                                                  at android.app.ActivityThread.access$1500(ActivityThread.java:151)
                                                                  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1381)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:110)
                                                                  at android.os.Looper.loop(Looper.java:193)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5299)
                                                                  at java.lang.reflect.Method.invokeNative(Native Method)
                                                                  at java.lang.reflect.Method.invoke(Method.java:515)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:829)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:645)
                                                                  at dalvik.system.NativeStart.main(Native Method)
```

**Comment by Zhuinden** [comment]
@defaultbr that's because you need to call `MultiDex.install(this);` in `attachBaseContext()` and not in `onCreate()`.

Read the relevant guide https://developer.android.com/studio/build/multidex.html

``` java
public class MyApplication extends SomeOtherApplication {
  @Override
  protected void attachBaseContext(Context base) {
     super.attachBaseContext(base);
     MultiDex.install(this);
  }
}
```

**Comment by defaultbr** [comment]
@Zhuinden  changed and still have the same crash =(

```

    @Override
    public void onCreate() {
        super.onCreate();
        initRealm();
        appComponent.inject(this);
    }

    @Override
    protected void attachBaseContext(Context context) {
        super.attachBaseContext(context);
        MultiDex.install(this);
    }
```

**Comment by Zhuinden** [comment]
then you can check following possible problems

1.) instant run is screwing up so do clean+rebuild

2.) you might have another version of Realm on classpath for example `compile 'io.realm.realm-android:0.87.5` or so which you should remove from dependencies

**Comment by defaultbr** [comment]
@Zhuinden no, i checked everything

Android 5.0 Works
Android 7.0 Works

Android 4.x crash 


ouch

**Comment by Zhuinden** [comment]
@defaultbr okay that is weird, does it by chance work with Realm 4.2.0?

**Comment by defaultbr** [comment]
@Zhuinden  i will try and post here again

**Comment by Zhuinden** [comment]
@defaultbr please try realm 4.3.2

**Comment by defaultbr** [comment]
@Zhuinden 4.2.0 and  4.3.2 still same error

the strange thing about 4.2.0 is that i lost the .sort and .addOnChangeListener methods, they doesnt exist (documentation way that 4.2.0 has it)

**Comment by gustavodbs** [comment]
The error continues with Realm 4.3.3 with alpha versions of build gradle (like alpha08, 09)

But when changing gradle to beta versión:
**classpath 'com.android.tools.build:gradle:3.0.1'**
The error did not come back (_or maybe, the solution was to clean the project a hundred times xD_)

By the way, it was not solved with any of the comments above, neither with MultiDex correctly installed

**Comment by ramzesrodriguez** [comment]
I got the same error and what I moved the component injector just after the MultiDex.install(this).

    @Override
    public void onCreate() {
        super.onCreate();
        //initializeInjector();
        //this.initializeLeakDetection();
    }

    @Override
    public void attachBaseContext(Context base){
        super.attachBaseContext(base);
        MultiDex.install(this);
        initializeInjector();
    }

Now this works with Android 4.4.2 and over.

**Comment by parthnumbertank** [comment]
I've done all the configuration as described above, It worked for me but after migrating to androidX it gives me below error while generating signed apk

Error: /Work/Android Work Space/Android-Staging/app/multi-dex-keep.txt, Failed to read file: /Work/Android Work Space/Android-Staging/app/multi-dex-keep.txt
