### ISSUE TITLE
Inheritance of any pojo (non RealObject) and implements RealModel

### ISSUE THREAD

**Issue by ronaldo-getreveel** [realm/realm-java#2850]
I have a concrete class with a few fields like this:

```
public class AnyModel{
   private Long id;
...
}
```

And other classes that extends this AnyModel:

```
@RealmClass
public class cl2 extends AnyModel implements RealmModel{
...
}
```

I'm getting an error about a non Realm model. 

`Error:(15, 8) error: Realm model classes must either extend RealmObject or implement RealmModel to be considered a valid model class`

Sounds like a bug as I'm implementing and annotating the concrete class properly.  Is not possible to extend any class than RealmObject?

Realm version: 0.90.0

Android Studio version: 2.1.0

**Comment by cmelchior** [comment]
No, it is not. Allowing to extend other classes depends on #761. So i'll close this as an duplicate, but you can follow progress on this in #761
