### ISSUE TITLE
No default RealmConfiguration was found. Call setDefaultConfiguration() first

### ISSUE THREAD

**Issue by jraczak** [realm/realm-java#2851]
The above error is being thrown when my activity calls `realm.getDefaultInstance`. I've declared the config in an application class. Relevant code below.

> MoviesApplication

```java

public class MoviesApplication extends Application {

    @Override
    public void onCreate() {
        super.onCreate();

        RealmConfiguration realmConfiguration = new RealmConfiguration.Builder(this)
                .name("movies.realm")
                .deleteRealmIfMigrationNeeded()
                .build();

        Realm.setDefaultConfiguration(realmConfiguration);
    }
}

```

> MovieDetail

```java

public class MovieDetail extends Activity {

    private final String LOG_TAG = MovieDetail.class.getSimpleName();

    private String mYouTubeVideoId;
    private int mMovieId;
    private Realm realm;



    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_movie_detail);

        realm = Realm.getDefaultInstance();

        //TODO: Determine if movie is in favorites and update favorite button
....

```

#### Version of Realm and tooling
Realm version(s): 0.90.1

Android Studio version: 1.5.1

Which Android version and device: Marshmallow Android Emu

**Comment by jraczak** [comment]
@cmelchior Here's the requested issue!

**Comment by cmelchior** [comment]
You mean you see this on the emulator? 2 questions:
1) Is the Application class defined in the manifest? Perhaps it is a manifest merger error, so decompiling the APK to check might be a good idea
2) Is the MovieDetail activity running in a separate process?

**Comment by jraczak** [comment]
Yes, this error is thrown on the emulator. 

1. The application class is not defined in the Manifest. Does it need to be?
2. Might be easiest for you to have full access to see this. Here's the project: https://github.com/jraczak/Movies/tree/phase-2

**Comment by cmelchior** [comment]
Yes, that is why it doesn't work. A custom application class needs to be registered in the manifest: https://developer.android.com/reference/android/app/Application.html

**Comment by jraczak** [comment]
Thank you, that is super helpful. Giving that a try right now. I know this isn't a realm-related question, but can you tell me if that change impacts any of the app/framework's default behavior? This `onCreate` override is the only thing I've declared in my subclass.

**Comment by cmelchior** [comment]
No, a custom application class is pretty normal. The only thing that happens is that you are guaranteed that that class will be run before any activity when you start the app, so it is a good point to setup global app state like Realm.

**Comment by jraczak** [comment]
Thanks so much for your help - this seems to be working now! Really appreciate the quick responses.
