### ISSUE TITLE
RealmTransformer should fail if using Unsupported methods on RealmResults.

### ISSUE THREAD

**Issue by diegomontoya** [realm/realm-java#2854]
There have been lots of method renaming and reorganization between 0.87 and the current 0.91.0 release. However, the use of "deprecation" here I think is a mistake. It would be better to actually remove these empty/exception throwing methods all together. Depending on semantics of "deprecation". there is nothing wrong technically but also not very dev friendly. 

1) The deprecated methods triggers run-time exceptions, not compile time. 
2) There are ways to trigger compile time exceptions by changing deprecated api detection to error level but in android builds, there are real needs of using deprecated android apis so this is not a solution. 
3) Deprecation in lots of software means "pending api death in future revision" but "workable" state. Here, it just crashes. If a method is removed, why keep it? Personally speaking, I would rather have it stop in compilation stage so I can fix it rather than using code analysis to hunt down the deprecated usage which is much more time consuming. 

``` java
    /** @deprecated */
    @Deprecated
    public void clear() {
        throw new UnsupportedOperationException("This method is not supported by RealmResults.");
    }
```

**Comment by cmelchior** [comment]
Hi @diegomontoya 

We cannot remove those methods because they are part of the List interface, so there has to be an implementation. You will see many other Collections doing the same thing. But you are right, it is not ideal.

It is also true, that we are abusing the `@Deprecated` annotation a bit, because as you point out it is normally used for methods that _do_ work.

However we think the IDE feedback you get when marking them as deprecated is a nice reminder that someone is wrong and you shouldn't use them.

I hope that clarifies it.

**Comment by diegomontoya** [comment]
@cmelchior Thanks for the clarification.  I see the problem with .clear() and List interface. Hmm...that is a tough nut to crack. 

How about this. Realm is already doing .class scanning and processing, perhaps the plugin can stop and spew out errors when deprecated/but-actually-removed realm methods are referenced?

**Comment by cmelchior** [comment]
That is an option, yes, but us implementing something like that will also depend on the overhead it adds to the compilation process.

**Comment by Zhuinden** [comment]
The `@Deprecated` annotation makes the IDE cross it out if you try to use it, I think that's really useful.

**Comment by diegomontoya** [comment]
@Zhuinden Ide cross it out when you view/write it, yet. But what happens when realm updates a whole bunch of APIs and removes methods after you have written tons of realm code? That is the problem I have experienced where I did not expect deprecation to mean run-time crash during code migration due to realm api update.

**Comment by cmelchior** [comment]
@diegomontoya 
Yes, we did change a lot of things in a recent update. However it is not something we do lightly, and we only did it becasue we think it mad the API better. It is unfortunate that it broke a lot of existing code, but we try hard to describe these cases in our release blog posts and changelog. 

That said, I don't see us making that amount of breaking changes again going forward.

**Comment by diegomontoya** [comment]
@cmelchior I understand the need for api migration but I still don't like the way it's handled. 

By implementing RealmResult.clear(), using this as example, to satisfy a Collection interface only to run-time crash absolutely breaks the contract of the interface in itself regardless if @deprecated was added. Conversely, the same can be argued that any alternative also breaks the contract.  

Replacing the run-time crash with error logs + stack traces to make sure the user is aware would be a better poison pill. 

The question is: If someone incorrectly used an API but that the result of that incorrect usage is "nothing happens because there is nothing here", should the API just crash/exception automatically?

**Comment by Zhuinden** [comment]
```
boolean	add(E e)
- Ensures that this collection contains the specified element **(optional operation).**
boolean	addAll(Collection<? extends E> c)
- Adds all of the elements in the specified collection to this collection **(optional operation)**.
void	clear()
- Removes all of the elements from this collection **(optional operation)**.
```

```
boolean	remove(Object o)
Removes a single instance of the specified element from this collection, if it is present **(optional operation)**.
boolean	removeAll(Collection<?> c)
Removes all of this collection's elements that are also contained in the specified collection **(optional operation)**.
boolean	retainAll(Collection<?> c)
Retains only the elements in this collection that are contained in the specified collection **(optional operation)**.
```

I've had this discussion before, all these methods are optional, therefore the current `throw new UnsupportedOperationException();` is the right way to go.

**Comment by diegomontoya** [comment]
i dont think realm will use the same type.of throw/crash style for future deprecation needs Closing this.

**Comment by Zhuinden** [comment]
@diegomontoya technically a possibility would be a Lint, but I think the transformer should be left out of it.
