### ISSUE TITLE
In android,Update Realm 0.82.1 to 0.89.1 after that I added @keyword before the string.then there is null pointer exception.I want some string to be null.please help

### ISSUE THREAD

**Issue by aes009** [realm/realm-java#2856]
What do you want to achieve?
 i want string to be null in realm 0.89.1

 Actual Results
Null pointer exception

 Describe your current debugging efforts.
I have debug in android studio

Android Studio version: 2.1.1

Which Android version and device: All

**Comment by stk1m1** [comment]
Hi @aes009 
I'd highly appreciate if you could follow and fill up the template as it is provided here <https://github.com/realm/realm-java/blob/master/CONTRIBUTING.md#filing-issues> when you file an issue. We can help you in appropreate way then.

**Comment by aes009** [comment]
hi,
I want the string to be null in realm 0.89.1 . how to achive that.

**Comment by stk1m1** [comment]
@aes009 

Could you please provide your model class and the field you want to set `null`?

**Comment by aes009** [comment]
public class User extends RealmObject {

    @PrimaryKey
    private long ID;

    @Required
    private String name;

    @Required
    private String mobileNumber;

    private boolean isVerified;

    private boolean isRegistered;

    @Required
    private String ID2;


I want filed ID may be null and i want all the string where I have put @Required keyword before string may be null.

but the realm error is -not null value is null.

**Comment by zaki50** [comment]
If you'd like to use `null` as String value, please do not add **Required** annotation. **Required** means that field does not accept `null` as a value.

**Comment by aes009** [comment]
hi,
But not adding this Kerword there was a error-Either set @Required to field 'name' or migrate using RealmObjectSchema.setNullable().

**Comment by stk1m1** [comment]
@aes009 

It seems `name` in your old schema is marked as `@Required` but now you want to relax the contraint to accept `null`. Then you'd have to use `RealmObjectSchema.setNullable()` in migration to convert old schema.  There's no other way around it.

**Comment by aes009** [comment]
So I have to remove @Required keywore and add RealmObjectSchema.setNullable() in my migration code.

**Comment by stk1m1** [comment]
@aes009 
Yes.

**Comment by aes009** [comment]
but I use   RealmSchema schema = realm.getSchema(); in my migartyion code.this will work?Realm 0.89.1

**Comment by zaki50** [comment]
I think [Migration.java](https://github.com/realm/realm-java/blob/master/examples/migrationExample/src/main/java/io/realm/examples/realmmigrationexample/model/Migration.java) in MigrationExample project  will help.

**Comment by stk1m1** [comment]
Hello @aes009,

Any progress so far?

**Comment by stk1m1** [comment]
Hello @aes009 

Have our suggestions helped you?

**Comment by aes009** [comment]
yes ,thank u sir

**Comment by aes009** [comment]
yes thank u

**Comment by stk1m1** [comment]
> @aes009 
> yes thank u

You're welcome. 😉
