### ISSUE TITLE
java.lang.illegalstateexception: Nested transactions are not allowed. Use commitTransaction() after each beginTransaction()

### ISSUE THREAD

**Issue by KevinChris** [realm/realm-java#2858]
**QUESTION**

I'm doing my first realm Async Transaction and it throws `IllegalStateException:  Nested transactions are not allowed. Use commitTransaction() after each beginTransaction().` 

This happens only If i do as Async Transaction. I get this every transaction throughout app. First I thought I might be doing something wrong so I came to check my first Async transcation and same thing happened. I also checked this [link](https://github.com/realm/realm-java/issues/542) but of no use for me. 

Note : This doesn't happen if i use sync transaction.

#### Expected Results

> It should do a successful transaction

#### Actual Results

>  E.g. `io.realm.internal.ImplicitTransaction.promoteToWrite(ImplicitTransaction.java:51)
                                                                                   io.realm.internal.SharedGroupManager.promoteToWrite(SharedGroupManager.java:111)
                                                                                   io.realm.BaseRealm.beginTransaction(BaseRealm.java:326)
                                                                                   io.realm.Realm.beginTransaction(Realm.java:120)
                                                                                   com.r.a.i.ui.activity.login.LoginInteractionImpl$2.execute(LoginInteractionImpl.java:133)
                                                                                   io.realm.Realm$2.run(Realm.java:1284)
                                                                                   io.realm.internal.async.BgPriorityRunnable.run(BgPriorityRunnable.java:34)
                                                                                   java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
                                                                                   java.util.concurrent.FutureTask.run(FutureTask.java:237)
                                                                                   java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
                                                                                   java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
                                                                                   java.lang.Thread.run(Thread.java:818)`

#### Steps & Code to Reproduce

> Inserting the list of data one by one into realm. At first insertion it throws me illeagalStateException later gives the below given error in logcat.

#### Code Sample

Application Class : 

       RealmConfiguration configuration = new RealmConfiguration.Builder(context)
                .name(Realm.DEFAULT_REALM_NAME)
                .schemaVersion(0)
                .build();

        Realm.setDefaultConfiguration(configuration);

In Activity :

        Realm realm = Realm.getDefaultInstance();
        realm.executeTransactionAsync(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {

                try {
                    for (MStateMaster mStateMaster : mStateMasterList) {
                        MStateRealm mStateRealm = new MStateRealm();
                        mStateRealm.setStateID(mStateMaster.getID().intValue());
                        mStateRealm.setStateValue(mStateMaster.getValues());

                        realm.beginTransaction();
                        realm.copyToRealmOrUpdate(mStateRealm);
                        realm.commitTransaction();
                    }
                } catch (Exception e) {
                    ExceptionLogger.printLogException(e, TAG);
                    realm.cancelTransaction();
                }
            }
        }, new Realm.Transaction.OnSuccess() {
            @Override
            public void onSuccess() {
                Log.e(TAG, "Trans Success");
            }
        }, new Realm.Transaction.OnError() {
            @Override
            public void onError(Throwable error) {
                ExceptionLogger.printLogException(error, TAG);
            }
        });`

#### Version of Realm and tooling
Realm version(s): 0.91.0

Android Studio version: 2.1.1

Which Android version and device: Samsung S5 (5.1.1), Moto G2 (5.0.2)

**Comment by cmelchior** [comment]
If you call `executeTransaction` you don't have to manually call call begin/commit/cancel. That is handled for you and the reason you get a complaint about nested transactions. It is already started when the `exceute` method is called.

**Comment by KevinChris** [comment]
Thank you for the quick response I got it working..
