### ISSUE TITLE
Queries like mongodb support skip limit

### ISSUE THREAD

**Issue by chenzj-king** [realm/realm-java#2860]
As title.  
In my UserInfo has many data. So I want to realm support skip limit like mongodb.
First I will load 10 items. And Then when i onScroll to end in recyclerview. I 
will get the 10-20 items and add to the end.
  
It's a loadmore fuction.  
But I just see the   

    RealmQuery<E>.findAll();

can you guide me to solve this problem.

#### Version of Realm and tooling
Realm version(s): 0.91.0

Android Studio version: 2.1.1

Which Android version and device: 5.1

**Comment by cmelchior** [comment]
Everything in Realm is lazy loaded so you shouldn't need to worry about using a limit. If you want you can use `findAll` with subList which gives almost the same behaviour. Otherwise we are tracking LIMIT as a feature here: #544

**Comment by chenzj-king** [comment]
@cmelchior 
Thank you for you answer. It look like subList can work well.

**Comment by xiaolongyuan** [comment]
+1
