### ISSUE TITLE
Using librealm-jni.so on linux 

### ISSUE THREAD

**Issue by duoho** [realm/realm-java#2865]
I'm preparing the prebuild realm database on my server for my apps, but there's no any exist tools can help to do this. May I ask is it possible to recompile the realm-jni and make it work on linux? (so that I can  use pure java and .so files on my server) Many thanks.

**Comment by cmelchior** [comment]
Hi @duoho 
The biggest blocker for using Realm Java on Linux is not compiling the SO file, but that our current API has some strong requirements on the Android framework. Mostly the Handler/Looper.

We definitely want to provide a Java only version as well. That is being tracked here: #2339 
Until then, one work-around is to create a small sample Android app that can create the pre-built file. You can then run this code in an emulator on the server and pull the file using ADB. All of this can be fully automated (although not an ideal workflow).

I'll close this as an duplicate, but you can follow progress in #2339
