### ISSUE TITLE
onChange() method is getting called even when the result of associated query has not changed

### ISSUE THREAD

**Issue by tanayagrawal** [realm/realm-java#2866]
#### Goal

> What do you want to achieve?

There are 4 different RealmChangeListeners attached to 4 different queries in a single activity.
The onChange() method for all the different listeners have different method calls associated with it.

#### Expected Results

When result of one of the query out of the 4 query changes, the onChange() for that particular query should be called. 

#### Actual Results

When result of one of the query out of the 4 query changes, the onChange() for all the queries is called resulting in all the method calls associated with it. This is resulting in unwanted and unexpected behaviour.  (All the 4 queries are entirely different)

Realm version(s): 0.88.2

Android Studio version: 2.1.1

Android device : All devices

**Comment by cmelchior** [comment]
Hi @tanayagrawal 
Can you provide some examples of those queries and the model classes used?

**Comment by tanayagrawal** [comment]
` public RealmResults<Form> getSurveys() {
        Realm realm = Realm.getDefaultInstance();
        return realm.where(Form.class).equalTo(Form.ACTIVE, true).findAll();
    }`

`public RealmResults<Response> getAllCompletedAndActiveResponse(final IListener<RealmResults<Response>> responseListenerCallback) {
        Realm realm = Realm.getDefaultInstance();
        RealmResults<Response> responses = realm.where(Response.class).equalTo(Response.STATE, Response.COMPLETED).
                equalTo(Response.ACTIVE, true).findAll();
        responseListenerCallback.onSuccess(responses);
    }`

`public void getInCompletedResponses(IListener<RealmResults<Response>> responseCallbackListener) {
        Realm realm = Realm.getDefaultInstance();
        RealmResults<Response> responses = realm.where(Response.class).equalTo(Response.STATE,
                Response.INCOMPLETED)
                .equalTo(Response.ACTIVE, true).findAll();
      
            responseCallbackListener.onSuccess(responses);
    }`

`public class Response extends RealmObject {
     private String _id;

    private MetaData _kmd; 

    private RealmList<Answer> answer_list;

    private String user_id;

    private long sync_time;

    private boolean edited;

    private AppVersion app_version;

    private String revision_last_published_in;

    private RealmList<ResponseLog> response_log_list;

    private ResponseNote response_note;

    private boolean syncing;

    private String device_id;

    private boolean active;

    private String state;

    private String organization_id;

    private String form_family_id;

    private String internet_status;

    @PrimaryKey
    private String response_id;

    private long created_time_stamp;

    private long submitted_time_stamp;

    private long last_modified_time_stamp;

    private String form_title;

    private boolean sync_state;

    public String get_id() {
        return _id;
    }

    public void set_id(String _id) {
        this._id = _id;
    }

    public MetaData get_kmd() {
        return _kmd;
    }

    public void set_kmd(MetaData _kmd) {
        this._kmd = _kmd;
    }

    public RealmList<Answer> getAnswer_list() {
        return answer_list;
    }

    public void setAnswer_list(RealmList<Answer> answer_list) {
        this.answer_list = answer_list;
    }

    public String getUser_id() {
        return user_id;
    }

    public void setUser_id(String user_id) {
        this.user_id = user_id;
    }

    public String getRevision_last_published_in() {
        return revision_last_published_in;
    }

    public void setSurvey_id(String revision_last_published_in) {
        this.revision_last_published_in = revision_last_published_in;
    }

    public ResponseNote getResponse_note() {
        return response_note;
    }

    public void setResponse_note(ResponseNote response_note) {
        this.response_note = response_note;
    }

    public String getDevice_id() {
        return device_id;
    }

    public void setDevice_id(String device_id) {
        this.device_id = device_id;
    }

    public boolean isActive() {
        return active;
    }

    public void setActive(boolean active) {
        this.active = active;
    }

    public String getState() {
        return state;
    }

    public void setState(String state) {
        this.state = state;
    }

    public String getOrganization_id() {
        return organization_id;
    }

    public void setOrganization_id(String organization_id) {
        this.organization_id = organization_id;
    }

    public String getSurvey_family_id() {
        return form_family_id;
    }

    public void setSurvey_family_id(String form_family_id) {
        this.form_family_id = form_family_id;
    }

    public String getInternet_status() {
        return internet_status;
    }

    public void setInternet_status(String internet_status) {
        this.internet_status = internet_status;
    }

    public String getResponse_id() {
        return response_id;
    }

    public void setResponse_id(String response_id) {
        this.response_id = response_id;
    }


    public long getSubmitted_time_stamp() {
        return submitted_time_stamp;
    }

    public void setSubmitted_time_stamp(long submitted_time_stamp) {
        this.submitted_time_stamp = submitted_time_stamp;
    }

    public long getLast_modified_time_stamp() {
        return last_modified_time_stamp;
    }

    public void setLast_modified_time_stamp(long last_modified_time_stamp) {
        this.last_modified_time_stamp = last_modified_time_stamp;
    }

    public String getForm_title() {
        return form_title;
    }

    public void setForm_title(String form_title) {
        this.form_title = form_title;
    }

    public boolean isSync_state() {
        return sync_state;
    }

    public void setSync_state(boolean sync_state) {
        this.sync_state = sync_state;
    }

    public long getCreated_time_stamp() {
        return created_time_stamp;
    }

    public void setCreated_time_stamp(long created_time_stamp) {
        this.created_time_stamp = created_time_stamp;
    }

    public boolean isEdited() {
        return edited;
    }

    public void setEdited(boolean edited) {
        this.edited = edited;
    }


    public long getSync_time() {
        return sync_time;
    }

    public void setSync_time(long sync_time) {
        this.sync_time = sync_time;
    }

    public boolean isSyncing() {
        return syncing;
    }

    public void setSyncing(boolean syncing) {
        this.syncing = syncing;
    }

    public RealmList<ResponseLog> getResponse_log_list() {
        return response_log_list;
    }

    public void setResponse_log_list(RealmList<ResponseLog> response_log_list) {
        this.response_log_list = response_log_list;
    }

    public AppVersion getApp_version() {
        return app_version;
    }

    public void setApp_version(AppVersion app_version) {
        this.app_version = app_version;
    }
}`

`public class Form extends RealmObject {
    
    @PrimaryKey
    private String _id;

    private MetaData _kmd;

    private String title;

    private String description;

    private boolean live;

    private long last_modified_at;

    private RealmList<Question> question_list;

    private int type;

    private int sector;

    private String organization_id;

    private String published_revision_last_published_in;

    private String form_family_id;

    private boolean response_email_enabled;

    private boolean response_sms_enabled;

    private EmailOrSms email_parameters;

    private EmailOrSms sms_parameters;

    private String owner;

    private boolean force_submit_disabled;

    public String get_id() {
        return _id;
    }

    public void set_id(String _id) {
        this._id = _id;
    }

    public MetaData get_kmd() {
        return _kmd;
    }

    public void set_kmd(MetaData _kmd) {
        this._kmd = _kmd;
    }

    public String getTitle() {
        return title;
    }

    public void setTitle(String title) {
        this.title = title;
    }

    public String getDescription() {
        return description;
    }

    public void setDescription(String description) {
        this.description = description;
    }

    public long getLast_modified_at() {
        return last_modified_at;
    }

    public void setLast_modified_at(long last_modified_at) {
        this.last_modified_at = last_modified_at;
    }

    public RealmList<Question> getQuestion_list() {
        return question_list;
    }

    public void setQuestion_list(RealmList<Question> question_list) {
        this.question_list = question_list;
    }

    public int getType() {
        return type;
    }

    public void setType(int type) {
        this.type = type;
    }

    public int getSector() {
        return sector;
    }

    public void setSector(int sector) {
        this.sector = sector;
    }

    public String getOrganization_id() {
        return organization_id;
    }

    public void setOrganization_id(String organization_id) {
        this.organization_id = organization_id;
    }

    public String getPublished_revision_last_published_in() {
        return published_revision_last_published_in;
    }

    public void setPublished_revision_last_published_in(String published_revision_last_published_in) {
        this.published_revision_last_published_in = published_revision_last_published_in;
    }

    public String getForm_family_id() {
        return form_family_id;
    }

    public void setForm_family_id(String form_family_id) {
        this.form_family_id = form_family_id;
    }

    public boolean isResponse_email_enabled() {
        return response_email_enabled;
    }

    public void setResponse_email_enabled(boolean response_email_enabled) {
        this.response_email_enabled = response_email_enabled;
    }

    public boolean isResponse_sms_enabled() {
        return response_sms_enabled;
    }

    public void setResponse_sms_enabled(boolean response_sms_enabled) {
        this.response_sms_enabled = response_sms_enabled;
    }

    public EmailOrSms getEmail_parameters() {
        return email_parameters;
    }

    public void setEmail_parameters(EmailOrSms email_parameters) {
        this.email_parameters = email_parameters;
    }

    public EmailOrSms getSms_parameters() {
        return sms_parameters;
    }

    public void setSms_parameters(EmailOrSms sms_parameters) {
        this.sms_parameters = sms_parameters;
    }

    public String getOwner() {
        return owner;
    }

    public void setOwner(String owner) {
        this.owner = owner;
    }

    public boolean isForce_submit_disabled() {
        return force_submit_disabled;
    }

    public void setForce_submit_disabled(boolean force_submit_disabled) {
        this.force_submit_disabled = force_submit_disabled;
    }

    public boolean isLive() {
        return live;
    }

    public void setLive(boolean live) {
        this.live = live;
    }
}`

I have added 3 queries and associated model classes with them.

**Comment by Zhuinden** [comment]
@cmelchior aren't the `RealmChangeListener`s associated with a `RealmResults<T>` called when the **underlying table** of the given class of T is changed (insert/delete/modify)? I personally would expect the View to be synced to the new version and send a change event even if the table has not actually altered the results shown in the View.

Then again, I'm not entirely sure, in my active production project I'm only using ChangeListeners on the `Realm` itself :smile:

**Comment by viizki** [comment]
The same problem confused me.

**Comment by beeender** [comment]
That is the expected behaviour for now. When ever a element with type `A` changed/deleted/added, all of the query result based on type `A` will be notified.

After #989 implemented, a more precised behaviour will be supplied.

**Comment by emanuelez** [comment]
It looks like this issue can now be closed. Please contact us for any other enquiry! :)
