### ISSUE TITLE
Big .so files inside apk

### ISSUE THREAD

**Issue by danielgomezrico** [realm/realm-java#2868]
Using the new `analize apk` feature in `Android Studio 2.2` found that with just one object realm the .so files inside apk are so big:

![screen shot 2016-05-24 at 11 52 26 am](https://cloud.githubusercontent.com/assets/76348/15512519/004e337e-21a6-11e6-9167-22ab69072f26.png)

#### Version of Realm and tooling
Realm version(s): ?
0.91.0
Android Studio version: ?
2.2
Which Android version and device: ?
x

**Comment by Zhuinden** [comment]
https://realm.io/news/reducing-apk-size-native-libraries/

**Comment by cmelchior** [comment]
@danielgomezrico  The `.so` file is our native library (= the database code), not your data. 
As @Zhuinden points out we ship support for all CPU architectures as part of the library.
Right now this is about 4.1 MB zipped for all architectures including the Java code. With APK split you get down to about 800 KB for one CPU architecture (zipped).

Android will only unpack the .so file needed for the phone you install on, so the unpacked size you see is a bit misleading. You still have to transfer the zipped data across the wire though, which is where APK split can come in handy.
