### ISSUE TITLE
Detect when adding a ChangeListener on an IntentService

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#2875]
IntentServices are Looper Threads, which means that Realm currently allow you to register change listeners there. However since every invocation of `onHandleIntent` is a single event. Registering a change listener will not work, since the Realm should be closed when exiting `onHandleIntent`.

We might be able to implement a heuristic that checks if the current thread is named `IntentServicer[XXX]` the same way we test for Looper threads now, and throw an exception in that case:

https://android.googlesource.com/platform/frameworks/base/+/master/core/java/android/app/IntentService.java#108

**Comment by Zhuinden** [comment]
Out of curiousity, is there a way to somehow intercept the handler of the Realm and make the Realm on an intent service looper thread also send its messages to the main looper instead?

**Comment by cmelchior** [comment]
That will happen automatically. Whenever you commit something we will notify all loopers. So all you have to do is register the proper change listeners.

**Comment by Zhuinden** [comment]
Oh, so the question here is that the results won't be able to update on the IntentService looper, but it works fine with the main looper's change listeners. And therefore in an IntentService, you should open/close the Realm like on any background thread.

**Comment by cmelchior** [comment]
Exactly

**Comment by evansgelist** [comment]
I found a strange behavior. If I upgrade the object with help beginTransaction/commitTransaction inside IntentService. Then inside the app stops working **findAllAsync** code
For example, such a sequence.
-Intent Service updates the object every 5 minutes
-after the next update I open fragment, which is called findAllAsync. As a result, I do not get a call RealmChangeListener

**if I don't update object inside IntentService, for example use only "realm.where", as result I don't have any problems**. What could be the reason for such behavior?

**Comment by beeender** [comment]
@evansgelist it sounds like a bug... what is the Realm version are you using?

**Comment by evansgelist** [comment]
I use 1.0.0

**Comment by beeender** [comment]
@evansgelist Can you share your project or a minimal project which can reproduce this issue? To help@realm.io

Thanks!

**Comment by beeender** [comment]
BTW, if the `IntentService` using a separated process?

**Comment by evansgelist** [comment]
**@evansgelist Can you share your project or a minimal project which can reproduce this issue?**
I do not know how best to do so as it is a commercial project. But I think a complete project, it is better to understand the problem

**BTW, if the IntentService using a separated process?**
I know. I also check with Service, but the same behavior (

**Comment by evansgelist** [comment]
I made a test example and sent to email with a description of the steps.
I hope it will help to understand the problem.

**Comment by beeender** [comment]
@evansgelist I got your project and I can reproduce the problem. The root cause is you create the `IntentService` in a different process by `android:process=":haspa_service_not"`, and multi-process is not supported by realm-java yet. See #1300 

INTERNAL NOTES: The reason is when the realm changed in a different process, and start async query in the main process, since the background asyc will query on an advanced Realm version and main process cannot get `REALM_CHANGED` event, the handover will always fail.

**Comment by evansgelist** [comment]
Ah. Many thanks for answer!!!
