### ISSUE TITLE
Realm 1.0 - Unable to use FindFirstAsync() in conjunction with asObservable()

### ISSUE THREAD

**Issue by unidaysgraham** [realm/realm-java#2879]
#### Goal

Prior to upgrading to Realm 1.0.0 I was able to use findFirstAsync with asObservable() in order to use RxJava.

The only thing I have noticed is that I have migrated some of the classes to use the annotations and interface rather than extending `RealmObject`.

I was under the impression that using the annotation + interface would react the same to extending as I want to use Parcelable with the same class.

So before I could do something similar to:

```
        Realm realm = Realm.getDefaultInstance();

        return realm.where(Blah.class)
                .equalTo("id", id)
                .findFirstAsync()
                .<Blah>asObservable()
                .doOnUnsubscribe(realm::close)
                .filter(blah -> blah.isLoaded())
                .flatMap(this::processGetCustomerResult);
```

Now the asObservable method cannot be found.

```

#### Version of Realm and tooling
Realm version(s): 1.0.0

Android Studio version: 2.1.1

Which Android version and device: 5+

**Comment by unidaysgraham** [comment]
Just an update. I can use `FindAll` and its variants so I suspect the interface isn't the issue.

**Comment by cmelchior** [comment]
If you are using the new `RealmModel` interface you have to use our static helper methods instead. Which means that you should use `RealmObject.asObservable(obj)` instead.

**Comment by unidaysgraham** [comment]
Can you give a code example please that would work with the above for completeness?

**Comment by unidaysgraham** [comment]
@cmelchior why can i use `FindAll` (at least the IDE claims I can) without using the static helper methods?

**Comment by cmelchior** [comment]
Something like the below should work:

```
       return RealmObject.asObservable(realm.where(Blah.class).equalTo("id", id).findFirstAsync())
                .doOnUnsubscribe(realm::close)
                .filter(blah -> blah.isLoaded())
                .flatMap(this::processGetCustomerResult);
```

Also note that `findAll()` is a method on RealmQuery, not a method on RealmObjects. The method you need to call statically are the ones in this class here: https://realm.io/docs/java/latest/api/

**Comment by kneth** [comment]
@unidaysgraham Did you have a chance to try what @cmelchior suggests?

**Comment by njovy** [comment]
@cmelchior I'm having the same problem. 
```
realm.where(Friend.class)
        .equalTo("id", userId)
        .findFirstAsync()
        .asObservable()
        .filter(f -> f.isLoaded())
        .observeOn(AndroidSchedulers.mainThread())
        .subscribe(user -> {
          updateFriendMenuItem();
        });
```
```subscribe``` never gets called.

**Comment by cmelchior** [comment]
Hi @njovy 
Your problem is not related to this issue. Can you create a separate issue for it? That way it is easier for us to help you.

**Comment by njovy** [comment]
@cmelchior Sorry for the confusion. My issue is same as #2748.

**Comment by emanuelez** [comment]
@unidaysgraham hasn't been answering for a week now so I will close this issue. Please contact us for any further inquiry!
