### ISSUE TITLE
Reduce native lib size

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#2888]
From @beeender:

Interesting article https://blog.algolia.com/android-ndk-how-to-reduce-libs-size/

And also we can do
- Remove unnecessary inline functions

**Comment by emanuelez** [comment]
@kneth tried that already and the benefit in terms of size is almost negligible, while it might hit performance in a way more visible way.

On the other hand heøs experimenting with Clang which might bring some improvements.

**Comment by cmelchior** [comment]
Folding this into #3506
