### ISSUE TITLE
Feature Request: auto migration

### ISSUE THREAD

**Issue by cgcgbcbc** [realm/realm-java#2891]
> We LOVE to help with any issues or bug you have!
> 
> **Questions**: If you have questions about how to use Realm, please ask on [SO](http://stackoverflow.com/questions/ask?tags=realm) - we monitor the Realm tag.
> 
> **Feature Request**: Just fill in the first two sections below.
> 
> **Bugs**: To help you as fast as possible with an issue or bug please describe your issue and the steps you have taken to reproduce it in as many details as possible.
> 
> Thanks for helping us help you :-)
> 
> Remove this and above before submitting.
#### Goal

> What do you want to achieve?

Borrowed this idea from backend development, for example django/ ruby on rails etc. They have commands which will discovery models and create an initial migration file in a directory prefix with `0000-xxx`. Then every time developers modify models, they can run the command again which will detect model changes and automatically generate migration if possible ( for example, create new model, add new field, add index, drop index). For migration which must be performed manually, it will ask developer to fulfill the migration ( for example, drop model, delete field, add primary key)
#### Expected Results

add a gradle task called migration. when first run it, it will create a migration folder and create an `schema.yaml` ( or JSON?) file:

```
version: '0'
model1:
  id:
    type: String
    primary: true
...
```

every time the migration task is called, it will analysis the difference between yaml and code, if there are difference, it will create a migration file called `${n}-${n+1}.json` where n is the version in `schema.yaml`, which contains an array of migration operation, and then update the schema.yaml to newest. When build, it will automatically create migration class based on the migration files.

**Comment by cmelchior** [comment]
Automatic migrations are impossible in the general case, except when you only allow additive migrations.
However we do have plans for an IntelliJ plugin and as part of that we want to be able to create automatic migration blocks for new classes. Having some sort of representation of schema change to do this analysis might be a good idea though.

**Comment by cmelchior** [comment]
Folding this into https://github.com/realm/realm-java/issues/2891
