### ISSUE TITLE
ArrayList Size is 5500+,Unrecoverable error. mremap(): failed: Out of memory in io_realm_internal_SharedGroup.cpp line 188

### ISSUE THREAD

**Issue by alvin87** [realm/realm-java#2894]
##  realm version   classpath "io.realm:realm-gradle-plugin:1.0.0"
   

      Realm realm = Realm.getInstance(getRealmConfiguration());
        lineList = response.getDatasList();
        for (int i = 0; i < lineList.size(); i++) {
          realm.beginTransaction();
          Stock stock = realm.createObject(Stock.class);
          stock.setCode(lineList.get(i).getCode());
          stock.setName(lineList.get(i).getName());
          Timber.d(i + " {}  code " + lineList.get(i).getCode() + "||  name " + lineList.get(i)
              .getName());
          realm.commitTransaction();
        }
    
        realm.close();

![image](https://cloud.githubusercontent.com/assets/4157773/15605146/af11435a-2436-11e6-9f01-5d0f1b7d123b.png)

**Comment by cmelchior** [comment]
Hi @alvin87 
You shouldn't run out memory on such a small number of items. Are you app doing something else?
Note that it will be more efficient to move the transaction outside the loop as well.

**Comment by Zhuinden** [comment]
realm.beginTransaction();
    for (int i = 0; i < lineList.size(); i++) {
      Stock stock = realm.createObject(Stock.class);
      stock.setCode(lineList.get(i).getCode());
      stock.setName(lineList.get(i).getName());
      Timber.d(i + " {}  code " + lineList.get(i).getCode() + "||  name " + lineList.get(i)
          .getName());

    }
    realm.commitTransaction();

should fix your problem. Although I would recommend using `realm.executeTransaction()` instead so that you rollback failed transactions.

**Comment by kneth** [comment]
@alvin87 It looks like our storage engine is trying to allocate 32 MB (335544320-301989888)/(1024*1024). It's a big chuck.  Can you say a bit about the `Stock` class?

**Comment by finnschiermer** [comment]
This allocation is large because the storage engine will grow the database in chunks. The actual storage needed for this particular transaction may be much smaller. The allocation likely fails because the device a) is out of virtual address space or b) the address space has become too fragmented, so that a 32MB block cannot be found. At the point of failure, the database is already ~300MB. I assume this is a 32-bit device. Do the app use lots of virtual memory for other purposes besides Realm? Possibly through 3rd party libraries?

**Comment by finnschiermer** [comment]
We have a pending Core issue on lowering the use of virtual memory during commit: https://github.com/realm/realm-core/issues/1478

**Comment by diegomontoya** [comment]
@finnschiermer Any estimate eta on the core issue? We have experienced this painful issue in the past whenever our realm db reached about 250mb range. Since then,  we actively avoid storing medium sized to large string data into realm and our oom errors went away.

**Comment by finnschiermer** [comment]
@diegomontoya We'll probably start testing a solution this week.

**Comment by swjjxyxty** [comment]
![screenshot](https://cloud.githubusercontent.com/assets/8953382/16027706/ba3fb716-320a-11e6-91ae-7ead084d4139.png)

**I got this.**

**Comment by Zhuinden** [comment]
@swjjxyxty Honestly, this message tends to occur more and more often when people open Realms on non-looper background threads that they don't close.

**Comment by kneth** [comment]
@swjjxyxty As @Zhuinden points out, closing Realms is important: https://realm.io/docs/java/latest/#closing-realm-instances

**Comment by swjjxyxty** [comment]
@kneth @Zhuinden  thanks,the problem has been resolved. 

I checked all the  `Realm.getDefaultInstance()`  ,find a line not close realm.

hopeing to provide a method for obtaining the reference count,or give a warning.

Because this error is difficult to exclude.

**Comment by kneth** [comment]
@swjjxyxty It's great to hear! Yes, finding a missing `close()` can be difficult.
