### ISSUE TITLE
Update with collection support

### ISSUE THREAD

**Issue by LPFinch** [realm/realm-java#2897]
#### Goal

> What do you want to achieve?

For example, i have 10 elements with **PrimaryKey** in my realm. New downloaded data contains only 5 elements. 3 exist in my realm and 2 is new. I need to **update** my table with simple way like this ->
**copyOrUpdate new data** and **delete outdated elements**.

#### Expected Results

> ?

```java
realm.beginTransaction();
realm.updateInRealm(Collection_with_new_data);
realm.commitTransaction();
```

**Comment by Zhuinden** [comment]
This is not necessarily something realm should do,  but it is something you can easily do

    public class Data extends RealmObject {
        private boolean isBeingSaved;

        //getter setter
    } 

    realm.beginTransaction();
    for(Data data : datas) data.setIsBeingSaved(true) ;
    realm.copyToRealmOrUpdate(data);
    realm.where(Data.class).equalTo("isBeingSaved", false).findAll().deleteAllFromRealm();
    for(Data data : realm.where(Data.class).equalTo("isBeingSaved", true)) data.setIsBeingSaved(false);
    realm.commitTransaction() ;

**Comment by LPFinch** [comment]
I'm doing the same thing, but if Realm can do this by default it would be nice

**Comment by beeender** [comment]
@LPFinch Realm doesn't do this by default :)
So please just use what @Zhuinden suggested.

**Comment by LPFinch** [comment]
@beeender Ok, thanks for reply
P.S. I'm already using the same logic.

**Comment by cmelchior** [comment]
Hi @LPFinch 
We generally try to keep our API small instead of having methods for all use cases as it will make it harder to learn. In this case the semantics of an `updateInRealm` method is not clear (e.g. what is an outdated object) and there is easy workarounds as described by @Zhuinden, so right now we don't have any plans for such a method.

Depending on the use case, deleting everything before adding the new data will also accomplish the same.

**Comment by Zhuinden** [comment]
>  Depending on the use case, deleting everything before adding the new data will also accomplish the same.

That however works only if your objects have no object links. I had object links and it's quite a pitfall. Which is why I came up with the one above.
