### ISSUE TITLE
RealmConfiguration.Builder missing Builder.Builder(Context, File) constructor 

### ISSUE THREAD

**Issue by diegomontoya** [realm/realm-java#2900]
RealmConfiguration.Build(filePath) constructor calls loadLibrary() without context which skips relinker which nullifies the protection relinker provides on some broken android installs/updates. But if you call Build(Context) it uses a default getFilesDir() of the context as path. The problem is I want to provide both android context (for relinker) and a custom file path. Right now, it is not possible for the Builder class. 

```java
       at java.lang.Runtime.loadLibrary(Runtime.java:365)
       at java.lang.System.loadLibrary(System.java:606)
       at io.realm.internal.RealmCore.loadLibrary(RealmCore.java:69)
       at io.realm.RealmConfiguration$Builder.<init>(RealmConfiguration.java:371)
```

On android, RealmConfiguration builder needs to have a 3rd constructor Builder(Context, File [FilePath]) which calls realmCore.loadLibrary(ctx)

**Comment by Zhuinden** [comment]
Can't you set the path with [name()](https://realm.io/docs/java/latest/api/io/realm/RealmConfiguration.Builder.html#name-java.lang.String-) method ?

**Comment by diegomontoya** [comment]
RealmConfiguration constsructor takes in Builder and uses both fileFolder and fileName var. If fileName can be path and vice versa, then might as well combine the two vars into 1.

```java
    private RealmConfiguration(Builder builder) {
        this.realmFolder = builder.folder;
        this.realmFileName = builder.fileName;
    }
```

**Comment by Zhuinden** [comment]
I think I was wrong then, name really does set filename. 

In which case not using ReLinker in case of File is a bug, considering that's the constructor you need if you want to save the Realm on the external storage for example. 

Realm will handle it I'd think

**Comment by cmelchior** [comment]
Hi @diegomontoya 
I would be inclined to agree with you. The original reason for leaving the Context out was that we wanted to be as independent from Android API's as possible, but right now Context is sneaking in in a few places. So revisiting this, especially in the context of Relinker is probably a good idea.
