### ISSUE TITLE
Request: Realm integer primary key behavior

### ISSUE THREAD

**Issue by anggrayudi** [realm/realm-java#2905]
#### Goal
I have a feature request for Realm, especially for Android. When working with Realm, I saw many advantages from this library, but I still waiting this feature until now. I want Realm to add `autoincrement` and `non-autoincrement` for integer primary key.

#### Steps & Code to Reproduce
I wrote the expected behavior of the integer primary key in Excel and convert it to JPG. You can see below image:

![integer primary key behavior](https://cloud.githubusercontent.com/assets/12292380/15651821/0ad28bc8-26ac-11e6-8ceb-80bc5a38df60.png)

An advantage from `non-autoincrement` above is we can reduce the memory consumption, because digits of the `id` always keep small.

#### Code Sample
This is what I expected to have:
```java
public class Person extends RealmObject {
    // for example, we set autoincrement to 'true'
    @PrimaryKey(autoincrement = true)
    private int id;
    private String name;
    ...
}
```

#### Version of Realm and tooling
Realm version(s): 1.0.0

Android Studio version: 2.1.1

**Comment by cmelchior** [comment]
Hi @anggrayudi 
Thanks for the input. We are already tracking this here: #469 So i'll close this as an duplicate, but you can follow progress in #469 .
