### ISSUE TITLE
When adding RealmObject as a filed error: cannot find symbol variable RealmObjectRealmProxy

### ISSUE THREAD

**Issue by FabianTerhorst** [realm/realm-java#2910]
#### Goal

To have a Filed like RealmObject realmObject in my RealmObject object.

#### Expected Results

No build errors.

#### Actual Results

Error:(276, 17) error: cannot find symbol variable RealmObjectRealmProxy

#### Steps & Code to Reproduce

Add a RealmObject as a file dto a RealmObject

#### Code Sample

```java

public static Table initTable(ImplicitTransaction transaction) {
        if (!transaction.hasTable("class_Test")) {
            Table table = transaction.getTable("class_Test");
            table.addColumn(RealmFieldType.INTEGER, "mIdentifier", Table.NOT_NULLABLE);
            if (!transaction.hasTable("class_RealmObject")) {
                RealmObjectRealmProxy.initTable(transaction);
            }
....
```

#### Version of Realm and tooling
Realm version(s): 1.1.0-SNAPSHOT

Android Studio version: 2.2

**Comment by cmelchior** [comment]
RealmObject is our top-level root object and is not meant to be referenced in model classes . What is your use case for wanting to do that?

**Comment by FabianTerhorst** [comment]
I have a list of object there are stored inside of a RealmList. These objects needs the parent object, but there are multiple types of objects.

**Comment by cmelchior** [comment]
That is unfortunately not supported right now by Realm. What you are looking for is polymorphism, and it is being tracked here: #761
