### ISSUE TITLE
Values to changed null after copyToRealmOrUpdate

### ISSUE THREAD

**Issue by FabianTerhorst** [realm/realm-java#2911]
#### Goal

values should be the same after copyToRealmOrUpdate

#### Actual Results

value is changing from 1 to null after calling copyToRealmOrUpdate, but the other field from the object doesn´t changed.

#### Steps & Code to Reproduce
```
List<ObjectName> objects = resultData.getObjects();
objects.get(0).getList(0).getValue() //1
objects.get(0).getList(0).getKey() //name1
objects = realm.copyToRealmOrUpdate(objects);
objects.get(0).getList(0).getValue() //null
objects.get(0).getList(0).getKey() //name1

public class MyObject extends RealmObject {

    @PrimaryKey
    @Type
    private String key;

    private String value;
```

#### Version of Realm and tooling
Realm version(s): 1.1.0-SNAPSHOT

Android Studio version: 2.2

**Comment by FabianTerhorst** [comment]
is it possible to have duplicate object with the same primary key in different realm lists?

**Comment by cmelchior** [comment]
@FabianTerhorst Yes

**Comment by FabianTerhorst** [comment]
@cmelchior but why are all other object with the same key are gone from the other realm lists as well?

**Comment by FabianTerhorst** [comment]
@cmelchior i checked the .realm file and its contains only one object for one type, but every object i have has a realm list with the objects

**Comment by FabianTerhorst** [comment]
http://imgur.com/a/lb8yc

**Comment by cmelchior** [comment]
You should think of Realm as an object graph just like in Java, so if you have a number of Person objects that all reference the same Dog object. If that Dog is deleted, all the Person objects will no longer have a reference to it. Does that answer your question?

**Comment by FabianTerhorst** [comment]
@cmelchior yes it does, thanks

**Comment by A86S** [comment]
@cmelchior how can we restrict that null values from being update with copyToRealmOrUpdate(listofObjects) , is there any method so we can stop some values from being update ? 

Thanks

**Comment by beeender** [comment]
@A86S Currently you need to remove the field you want to ignore from JSON object.

**Comment by A86S** [comment]
@beeender but its not good idea to ignore those objects.

**Comment by beeender** [comment]
> but its not good idea to ignore those fields from JSON object

So you still want it in the JSON but not save it to Realm?

One workaround might be rename the field in JSON. then rename it back after `copyToRealmOrUpdate()`.

There is a feature request for this scenario #2288, but it has not been implemented yet. You can get more information in that thread.

**Comment by Coletz** [comment]
> Currently you need to remove the field you want to ignore from JSON object.
@beeender any hint on how can I do it with kotlin? I can't create var that are not initialized in the main constructor, and I need an empty constructor for realm to work properly
