### ISSUE TITLE
Realm is bloating the APK

### ISSUE THREAD

**Issue by lawloretienne** [realm/realm-java#2914]
So I ran Analyze APK on my project and it looks like the components that are the largest are from Realm.

![screen shot 2016-05-31 at 5 31 02 pm](https://cloud.githubusercontent.com/assets/311187/15695167/43bcfaec-2759-11e6-86f3-eb418e5b6ef8.png)

I haven't started using Realm just yet in my project I only set up the gradle configuration.  Why is this so large?

#### Version of Realm and tooling
Realm version(s): 1.0.0

Android Studio version: 2.2 Preview 2

Which Android version and device: Android N on a Nexus 5X

**Comment by beeender** [comment]
Please see https://realm.io/docs/java/latest/#how-big-is-the-realm-library and https://realm.io/news/reducing-apk-size-native-libraries/

**Comment by cmelchior** [comment]
Also keep in mind that the APK Analyzer shows the unpacked size. The Realm AAR including all supported CPU architectures is about 4.1 MB.

**Comment by cmelchior** [comment]
I assume the above answered your question. If not feel free to reopen.
