### ISSUE TITLE
Problem with Realm and Facebook SDK

### ISSUE THREAD

**Issue by nmlemus** [realm/realm-java#2922]
I am using Realm in my app, right now I include the Facebook SDK and I have this error, java.lang.NoClassDefFoundError: io.realm.internal.RealmCore
                                                                at io.realm.RealmConfiguration$Builder.<init>(RealmConfiguration.java:388)

Can anyone help me please?

**Comment by stk1m1** [comment]
Hello @nmlemus 

When you bump into an issue, it helps us assist you quickly if you fill up the template following [our guide](https://github.com/realm/realm-java/blob/master/CONTRIBUTING.md#filing-issues). Could you kindly share your `build.gradle` please?

**Comment by nmlemus** [comment]
buildscript {
    repositories {
        maven { url 'https://maven.fabric.io/public' }
    }

    dependencies {
        classpath 'io.fabric.tools:gradle:1.+'
    }
}
apply plugin: 'com.android.application'
apply plugin: 'io.fabric'
apply plugin: 'com.google.gms.google-services'
apply plugin: 'realm-android'

repositories {
    maven { url 'https://maven.fabric.io/public' }
    // TODO: Quitar, es solo para ver Realm en el browser.
    maven {
        url 'https://github.com/uPhyca/stetho-realm/raw/master/maven-repo'
    }
}


android {
    compileSdkVersion 23
    buildToolsVersion "23.0.2"

    defaultConfig {
        applicationId "com.goblob"
        minSdkVersion 15
        targetSdkVersion 19
        versionCode 1
        versionName "0.6.0"

        // Enabling multidex support.
        multiDexEnabled true

    }

    dexOptions {
        incremental = true;
        preDexLibraries = false
        javaMaxHeapSize "2g" // 2g should be also OK
    }

    buildTypes {
        release {
            shrinkResources true
            minifyEnabled true
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
    sourceSets { main { jni.srcDirs = ['src/main/jniLibs', 'src/main/jniLibs/'] } }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    testCompile 'junit:junit:4.12'
    compile('com.digits.sdk.android:digits:1.10.0@aar') {
        transitive = true;
    }
    compile('com.crashlytics.sdk.android:crashlytics:2.5.5@aar') {
        transitive = true;
    }
    compile project(':shortcutbadger')
    compile project(':material_preferences_library')
    compile project(':profiles')

    compile 'com.android.support:appcompat-v7:23.3.0'
    compile 'com.android.support:design:23.3.0'
    compile 'com.android.support:multidex:1.0.0'
    compile 'com.github.nkzawa:socket.io-client:0.4.2'
    compile 'com.loopj.android:android-async-http:1.4.9'
    compile 'com.google.android.gms:play-services-gcm:8.3.0'
    compile 'com.google.android.gms:play-services-location:8.3.0'
    compile 'com.twitter.sdk.android:twitter-core:1.6.4'
    compile 'com.squareup.okhttp:okhttp:2.7.3'
    compile 'com.squareup.okhttp:okhttp-urlconnection:2.7.3'
    compile 'com.mcxiaoke.volley:library:1.0.18'
    compile 'com.github.chrisbanes.photoview:library:1.2.3'
    compile 'com.pkmmte.view:circularimageview:1.1'
    compile 'com.melnykov:floatingactionbutton:1.3.0'
    compile 'com.koushikdutta.ion:ion:1.+'
    compile 'org.igniterealtime.smack:smack-tcp:4.1.7'
    compile 'org.igniterealtime.smack:smack-resolver-minidns:4.1.7'
    compile 'org.igniterealtime.smack:smack-core:4.1.7'
    compile 'org.igniterealtime.smack:smack-android:4.1.7'
    compile 'org.igniterealtime.smack:smack-extensions:4.1.7'
    compile 'org.igniterealtime.smack:smack-im:4.1.7'
    compile 'org.igniterealtime.smack:smack-sasl-provided:4.1.7'

    compile 'com.koushikdutta.urlimageviewhelper:urlimageviewhelper:1.0.4'

    // TODO: Quitar, es solo para ver Realm en el browser.
    //compile 'com.facebook.stetho:stetho:1.3.1'
    //compile 'com.uphyca:stetho_realm:0.9.0'
    compile project(path: ':linkpreview')
    compile('com.crashlytics.sdk.android:crashlytics-ndk:1.1.2@aar') {
        transitive = true;
    }

    // Add facebook SDK
    compile 'com.facebook.android:facebook-android-sdk:4.12.0'
}

crashlytics {
    enableNdk true
    androidNdkOut 'src/main/obj'
    androidNdkLibsOut 'src/main/libs'
}

**Comment by stk1m1** [comment]
@nmlemus 

I'd appreciate if you can separate the product level gradle from the app level gradle. Your comment comes in one piece. (I added syntax highlight.)

One thing that stands out to me is the lack of realm classpath setup. Somewhere somehow you should have declared realm gradle plugin.

```gradle
buildscript {
    ...
    dependencies {
        classpath "io.realm:realm-gradle-plugin:1.0.0" // you can use different version
    }
    ...
}
```

Could you check your gradle script according [the installation guide](https://realm.io/docs/java/latest/#installation) as well?
