### ISSUE TITLE
ProxyState Error:(66, 27) 警告: [unchecked]

### ISSUE THREAD

**Issue by angcyo** [realm/realm-java#2929]
Error:(66, 27) 警告: [unchecked] 对作为原始类型ProxyState的成员的ProxyState(Class<? extends RealmModel>,E)的调用未经过检查
其中, E是类型变量:
E扩展已在类 ProxyState中声明的RealmModel
Error:(270, 36) 警告: [unchecked] 对作为原始类型CacheData的成员的CacheData(int,E)的调用未经过检查
其中, E是类型变量:
E扩展已在类 CacheData中声明的RealmModel
Error:(270, 22) 警告: [unchecked] 方法调用未经过检查: 将接口 Map中的方法 put应用到给定的类型
需要: K,V
找到: TestRealmObject,CacheData
其中, K,V是类型变量:
K扩展已在接口 Map中声明的Object
V扩展已在接口 Map中声明的Object
Error:(270, 36) 警告: [unchecked] 未经检查的转换
需要: V
找到:    CacheData
其中, V是类型变量:
V扩展已在接口 Map中声明的Object

by realm 1.0.0

**Comment by beeender** [comment]
So what is the source code  have this compiling error?

**Comment by beeender** [comment]
Close due to no response

**Comment by palmyer** [comment]
I have the same warning.
Program is running normally but clean console is better.
Thanks.

/Users/palmy/Desktop/aaaaaaaa/RdAndroid/tablet/build/generated/source/apt/debug/io/realm/GoodCateDataRealmProxy.java
Error:(121, 27) 警告: [unchecked] 对作为原始类型ProxyState的成员的ProxyState(Class<? extends RealmModel>,E)的调用未经过检查
其中, E是类型变量:
E扩展已在类 ProxyState中声明的RealmModel
```
public class GoodCateData extends RealmObject {
    public GoodCateData() {

    }
    @PrimaryKey
    public int ID;
    public int erp_store_id;
    public String is_add_children;
    public String is_edit;
    public String name;
    public int new_id;
    public String remark;
    public String text;
    public String update_time;
}
```
```
    /**
     * 添加list
     */
    public <T extends RealmObject> void addList(List<T> list) {
        getRealm().beginTransaction();
        getRealm().copyToRealmOrUpdate(list);
        getRealm().commitTransaction();
    }
```

**Comment by beeender** [comment]
@palmyer can you please share the `GoodCateDataRealmProxy.java` with us? it is an generated file which is located in your build directory.

**Comment by palmyer** [comment]
Of course

[GoodCateDataRealmProxy.java.txt](https://github.com/realm/realm-java/files/665769/GoodCateDataRealmProxy.java.txt)
