### ISSUE TITLE
delete problem

### ISSUE THREAD

**Issue by gushoubang** [realm/realm-java#2930]
I want delet the Object like this,but is error
```
    @Override
    public <T extends RealmObject> RealmResults<T> getByKeyAll(String realmKey, String findKey, Class<T> realmObjectClass) {
        return realm.where(realmObjectClass).equalTo(realmKey, findKey).findAll();
    }

    @Override
    public void deleteObject(final String realmKey, final String findKey, final Class<T> realmObjectClass) {
        realm.executeTransaction(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {
                getByKeyAll(realmKey, findKey, realmObjectClass).deleteAllFromRealm();
            }
        });
    }
```

**Comment by beeender** [comment]
But what error it is?
Please follow our guideline to report issue which will help us and yourself to solve it faster.

**Comment by gushoubang** [comment]
the screenshot is here
https://segmentfault.com/q/1010000005629305

**Comment by beeender** [comment]
The `public void deleteObject(final String realmKey, final String findKey, final Class<T> realmObjectClass)` take `realmKey` as a `final String`, but `realmKey` in `getByKeyAll` params is not final. You need to change that to final as well. 

The IDE probably gives you some error message about that, by checking that you will find lots of clues.
Also this question is not really related with Realm :)
