### ISSUE TITLE
Empty DB after application restart

### ISSUE THREAD

**Issue by kannadasbe** [realm/realm-java#2934]
Hi everyone.
I've got an error. I`m getting instance of realm in application onCreate like realm = Realm.getInstance(this);

Closing application from processes, start it again and trying to get any data from realm - but it`s empty.
I`m not deleting realm, not clearing it, not clearing cache. So what is it could be?
I am using latest 1.0 version

**Comment by kannadasbe** [comment]
Yes i am downloading and inserting the data on my first screen via background service and once it completes i will off my internet connection and do all operations offline from the realm models. It works fine no issue. But if i clear the application from processes and reopen it then all my realm data are getting cleared. 

And i have not used deleteIfMigrationNeeded in RealmConfiguration

**Comment by beeender** [comment]
What do you mean by "Closing application from processes"?
1. Quite the app through task switcher? Or kill the process by `adb shell kill <PID>` ?
2. How did you build the `RealmConfiguaration`?
3. Did you call `commitTransaction()` after data inserted>
4. Did you use Realm in multi-processes? If yes, how?

**Comment by kannadasbe** [comment]
1. I will go to my recently opened apps and close all the apps.
2. // init Realm with default config
        RealmConfiguration realmConfiguration = new RealmConfiguration.Builder(this)
                .build();
        Realm.setDefaultConfiguration(realmConfiguration);

3. Yes I am doing commitTransaction() after data inserted
Example: 
`private Realm realm;
public void insertOrReplaceAppointments(List<AppointmentModel> mAppointmentModel) {
        realm = Realm.getDefaultInstance();
        try {
            realm.beginTransaction();
            realm.copyToRealm(mAppointmentModel);
            realm.commitTransaction();
        }catch (Exception ex)
        {
            realm.cancelTransaction();
        }
    }`

4. My background service will call multiple server apis asynchronously and insert the response data in the realm. The code structure shown in point 3 is used everywhere in the code

**Comment by beeender** [comment]
@kannadasbe Can you share your project with us? To help@realm.io if you want to share it privately.

**Comment by kannadasbe** [comment]
It is a big project. I will remove all modules and send you a sample module alone. Hope that is enough to understand the issue. I will send u by monday

**Comment by beeender** [comment]
Thanks! Will check it on Monday!

**Comment by Zhuinden** [comment]
Background service? I can't help but feel like you're using a second process, and running into the issue that multi-processes are not yet supported.

Also worth noting the fact that you aren't closing your Realm on your background thread.

Personally I use this code for that:

``` java
public class RealmUtils {
    private static final String TAG = "RealmUtils";

    public interface RealmTransaction {
        void executeTransaction(Realm realm);
    }

    public static void executeInTransaction(RealmTransaction realmTransaction) {
        Realm realm = null;
        try {
            realm = Realm.getDefaultInstance();
            executeInTransaction(realm, realmTransaction);
        } finally {
            if(realm != null) {
                realm.close();
            }
        }
    }

    public static void executeInTransaction(Realm realm, RealmTransaction realmTransaction) {
        try {
            realm.beginTransaction();
            realmTransaction.executeTransaction(realm);
            realm.commitTransaction();
        } catch(Throwable e) {
            Log.e(TAG, "An error occurred.", e);
            if(realm != null) {
                try {
                    realm.cancelTransaction();
                } catch(Exception e2) {
                    Log.e(TAG, "Realm probably not in transaction.");
                }
            }
            throw e;
        }
    }
}
```

In your case this would be

``` java
public void insertOrReplaceAppointments(final List<AppointmentModel> mAppointmentModel) {
    RealmUtils.executeInTransaction(new RealmUtils.RealmTransaction() {
        @Override
        public void executeTransaction(Realm realm) {
            realm.copyToRealm(mAppointmentModel);
        }
    }
}
```

Try it and see what happens

**Comment by kneth** [comment]
@kannadasbe Did you have a chance to share some code with us?

**Comment by stk1m1** [comment]
@kannadasbe

Any progess on sharing a sample with us?

**Comment by Eldhose-Islet** [comment]
I do have this issue later, I found out that I was a accessing realm object  before setting default realm .
