### ISSUE TITLE
Strict mode violation, freezes app when loading

### ISSUE THREAD

**Issue by yavuzyurtbegendi** [realm/realm-java#2935]
```
RealmConfiguration realmConfiguration = new RealmConfiguration.Builder(this).build();
Realm.setDefaultConfiguration(realmConfiguration);
```

Configuring realm makes my app load slower, looks like the app is freezing, how can I overcome this issue ?

`D/StrictMode: StrictMode policy violation; ~duration=36 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=65567 violation=2`

`D/StrictMode: StrictMode policy violation; ~duration=35 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=65567 violation=2`

`D/StrictMode: StrictMode policy violation; ~duration=35 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=65567 violation=2`

**Comment by nhachicha** [comment]
Hi @yavuzyurtbegendi 
- I suppose you're using StrictMode only in Debug/Developer mode?
- do you see this duration on a specific device?

Cheers

**Comment by beeender** [comment]
Same question on SO http://stackoverflow.com/questions/37621743/realm-strict-mode-violation-freezes-app-when-loading

**Comment by yavuzyurtbegendi** [comment]
@beeender It is the same one, yes :)
@nhachicha I see it on my device and on emulator, you can see it when you try it, just paste initialization code, in your application class and you will see it :)

**Comment by kneth** [comment]
Issue #2299 is somewhat related, so you might wish to read some of the comments.

**Comment by yavuzyurtbegendi** [comment]
@kneth I read them but no help, it really takes time and damn it I have so many data in realm

**Comment by stk1m1** [comment]
@yavuzyurtbegendi 

Please consider following [our guide](https://github.com/realm/realm-java/blob/master/CONTRIBUTING.md#filing-issues) when you file an issue. 

Plus, could you share a sample project with us to reproduce? Although a code snippet of  two-liners is very elegant (as Turing might have loved), it does not help us to get to the root of your issue.

**Comment by yavuzyurtbegendi** [comment]
Okay, that is okay
