### ISSUE TITLE
I can't delete realm results

### ISSUE THREAD

**Issue by potnox** [realm/realm-java#2937]
#### Goal

> delete all items in RealmResults

#### Expected Results

> all items deleted

#### Actual Results

>  java.lang.UnsupportedOperationException: This method is not supported by RealmResults.
>  at io.realm.RealmResults.remove(RealmResults.java:551)
>  at io.realm.RealmResults.remove(RealmResults.java:69)

#### Steps & Code to Reproduce

> The code is to remove items from a list, within a OnClickListener.
> Specifically, the code belongs to the model.

#### Code Sample

```java

public void deletePlayer(Integer id, final OnPlayerDeleted playerDeletedListener) {
        Realm realm = Realm.getDefaultInstance();
        realm.beginTransaction();
        RealmResults<Player> results = realm.where(Player.class).equalTo("id", id).findAll();
        results.deleteAllFromRealm()
        realm.commitTransaction();
    }

```

#### Version of Realm and tooling
Realm version(s): 1.0

Android Studio version: 2.1.1

Which Android version and device: API 22 in Nexus 5 emulator

**Comment by angcyo** [comment]
you can like this:
public void deletePlayer(Integer id, final OnPlayerDeleted playerDeletedListener) {
        Realm realm = Realm.getDefaultInstance();
        RealmResults<Player> results = realm.where(Player.class).equalTo("id", id).findAll();

        realm.executeTransaction(new Realm.Transaction() {
                @Override
                 public void execute(Realm realm) {
                       results.deleteAllFromRealm();
                }
        });
    }

**Comment by Zhuinden** [comment]
I honestly doubt this is the offending code sample, considering the exception you get is from

    @Deprecated
    @Override
    public E remove(int index) {
        throw new UnsupportedOperationException(NOT_SUPPORTED_MESSAGE);
    }

And your sample calls

    /**
     * {@inheritDoc}
     */
    @Override
    public boolean deleteAllFromRealm() {
        realm.checkIfValid();
        if (size() > 0) {
            TableOrView table = getTable();
            table.clear();
            return true;
        } else {
            return false;
        }
    }

Which in `RealmResults` calls

    // Methods for deleting.
    @Override
    public void clear(){
        if (parent.isImmutable()) throwImmutable();
        nativeClear(nativePtr);
    }

`remove()` is NEVER called, therefore YOU are calling it somewhere else in your code.

**Comment by potnox** [comment]
First, thanks for the answers.
The sample code is launching mistake, I'm not mistaken.
I have done tests with the debugger and apparently working properly, but when the methods are resolved, java.lang.UnsupportedOperationException appears.
![captura de pantalla 2016-06-04 a las 15 58 18](https://cloud.githubusercontent.com/assets/3432038/15799920/38dbba3e-2a6d-11e6-95a6-d6947fe1df7b.png)

**Comment by potnox** [comment]
Thanks for the answers.
Solved, the problem was version error

**Comment by wemerson-costa** [comment]
Boa tarde, se atualizou a versão do realm com o app instalado e depois do build ele vai dar erro, deve remover sempre o app, dessa forma a versão do banco não vai afetar a utilização.
