### ISSUE TITLE
Realmlist listener

### ISSUE THREAD

**Issue by sandeshlasnapure** [realm/realm-java#2938]
I have table User and another table post and comments.
Relationship 
1. User has Post  
2. Post has comments.
3. Comment has data
while updating the post of users am adding post like user.getPost().add(new Post());
but when I show the list of only post am directly querying on post table.
And am getting realmresult<Post> and am adding change listener to postResult.
But after updating the post, change listener is not getting called.
Same things happening for comment and data.
Is there any solution for this to add changelistener to realm list.
Thanks.

**Comment by Zhuinden** [comment]
I don't understand what you're doing, can you please show with code

**Comment by sandeshlasnapure** [comment]
Actually am not able to add listener to realmlist.
I have converted realmlist to realmresult and added listener to it but still no luck.

**Comment by nhachicha** [comment]
Hi @sandeshlasnapure 
`RealmChangeListener` is not currently supported on `RealmList` this will probably be added once https://github.com/realm/realm-java/issues/1956 is implemented 
Cheers,

**Comment by Zhuinden** [comment]
Ah, that explains why you use a RealmChangeListener for the `BaseRealm` in the [RealmBaseAdapter's latest version](https://github.com/realm/realm-android-adapters/blob/master/adapters/src/main/java/io/realm/RealmBaseAdapter.java#L52).

**Comment by kneth** [comment]
@Zhuinden When a non-Realm user post a comment, `S:Waiting For User` is removed and we are notified once a day of issues without that label to remind us to response :-)

**Comment by Zhuinden** [comment]
@kneth  I see!

I may as well ask something relevant: what happens if I add a `RealmChangeListener` to a `RealmList` that I convert into a `RealmResults` using `realmList.where().findAll()`?

**Comment by kneth** [comment]
@Zhuinden The change listener isn't copied.

**Comment by Zhuinden** [comment]
@kneth  but will the newly obtained RealmList-driven RealmResults be notified by the change listener?

Of course, maybe I should just make a test case and see for myself, heh.

**Comment by stk1m1** [comment]
@Zhuinden 

> I may as well ask something relevant: what happens if I add a `RealmChangeListener` to a `RealmList` that I convert into a `RealmResults` using `realmList.where().findAll()`?

`RealmChangeListener` has a very specific, focused role of notifying any change (insert/delete/update) related an instance it is added to. In your scenario, a new `RealmResults` spawns as a copy (read) of `RealmList` and it does not cause any change.
