### ISSUE TITLE
Out of memory exception

### ISSUE THREAD

**Issue by vladiulianbogdan** [realm/realm-java#2940]
Hello,

I'm receiving the following exception:

Fatal Exception: io.realm.exceptions.RealmError: Unrecoverable error. mmap() failed: Out of memory size:

This exception appears in a method like this:

```
public void add(model) {
		Realm realm = Realm.getDefaultInstance();
		realm.beginTransaction();
		realm.copyToRealmOrUpdate(model);
		realm.commitTransaction();
		realm.close();
}
```

This method is called in a loop. I assured that I close all my realm instances. 

I've read all the posts about similar issues but I couldn't have nothing that could help me.

Do you have any idea why this could appear?

Realm version: 0.90.1.

**Comment by nhachicha** [comment]
Hi @vladiulianbogdan 
- do you have the same error if you use the same transaction? (instead of opening each time a new transaction, use the same one & call multiple time `void add(model)`)
- how big is your data, how many calls to `void add(model)`?
- Can you send an example that reproduce your issue?
Cheers

**Comment by vladiulianbogdan** [comment]
I've looked in the application data folder and I've seen that the "default.realm" file has 469762048 bytes.

And the exception is:
io.realm.exceptions.RealmError: Unrecoverable error. mmap() failed: Out of memory size: 469762048 offset: 0 in io_realm_internal_SharedGroup.cpp line 188

How can the realm file be so big? I've looked on other phones with the same application installed and the average size is ~ 60 mb.

This is the "ls" output:

`-rw------- u0_a250  u0_a250  469762048 2016-06-06 10:31 default.realm
-rw------- u0_a250  u0_a250      1120 2016-06-06 10:31 default.realm.lock
-rw------- u0_a250  u0_a250       104 2016-05-27 10:30 default.realm.log
-rw------- u0_a250  u0_a250     12288 2016-05-27 10:30 default.realm.log_a
-rw------- u0_a250  u0_a250      4096 2016-05-27 10:30 default.realm.log_b
drwx------ u0_a250  u0_a250           2016-06-06 10:31 default.realm.management
-rw-rw---- u0_a250  u0_a250        36 2016-05-05 18:24 gaClientId
drwx------ u0_a250  u0_a250           2016-06-06 10:19 instant-run`

**Comment by beeender** [comment]
@vladiulianbogdan For most cases, the big realm file is caused by forgetting to close the Realm instance in the background thread, which will make Realm keep all the versions of data for that thread.
Please take a look at https://realm.io/docs/java/latest/#large-realm-file-size

**Comment by Zhuinden** [comment]
If you don't close your Realm instances on non-looper background threads, then you'll retain previous versions of the database after each modification.

You should:

1.) make sure you close Realm instances you open on background threads

2.) not have multiple large transactions on background threads at the same time, try to execute them serially

**Comment by vladiulianbogdan** [comment]
Ok, I understand. Thank you, guys!

So now to fix this issue I have to:

1. do what you guys said about closing Realm instances.
2. call compactRealm method in order to reduce the realm size.

Is it safe to call compactRealm when my application starts?

**Comment by beeender** [comment]
`compactRealm` will throw if there are any Realm instances opened. So just keep that in mind.

Also, if you properly closed Realm instance in the background thread, I don't think you will see the file size insanely grows. If it doesn't grow too much, those spaces can be reused by Realm by the following transactions, so you might not need to call `compactRealm()`.

**Comment by vladiulianbogdan** [comment]
Thank you very much for your help!

**Comment by Zhuinden** [comment]
> Is it safe to call compactRealm when my application starts?

I'd advise against it, it's kinda slow in my opinion. The start-up time increase was noticeable, which is why I try it (in a try - catch exception block) when all my activities are closed.

**Comment by kneth** [comment]
@vladiulianbogdan Did you get rid of the out-of-memory issues?

**Comment by vladiulianbogdan** [comment]
Yes, I did. It works ok now.

Thank you!
