### ISSUE TITLE
Can't save into realm

### ISSUE THREAD

**Issue by gushoubang** [realm/realm-java#2941]
I use it like this,but can't save into realm

```
  public void saveRealmMapInfo(final AllInfoMapBean realmObject) {
        realm.executeTransactionAsync(new Realm.Transaction() {
            @Override
            public void execute(Realm bgRealm) {
                AllInfoMapBean allInfoMapBean = bgRealm.createObject(AllInfoMapBean.class);
                allInfoMapBean = realmObject;
            }
        });
    }
```

**Comment by Zhuinden** [comment]
Is this on a background thread or the UI thread? if it's on the UI thread, try adding a listener to this operation.

**Comment by stk1m1** [comment]
@gushoubang 

You should copy values from `realmObject` to `allInfoMapBean` to save values into Realm. 
By going over

```java
allInfoMapBean = realmObject;
```
You're making `allInfoMapBean` refer to `realmObject`, which doesn't do anything.

Also could you follow [our guideline](https://github.com/realm/realm-java/blob/master/CONTRIBUTING.md#filing-issues) for filling an issue please?

**Comment by gushoubang** [comment]
@stk1m1 OK,it's greate

**Comment by stk1m1** [comment]
@gushoubang 

Could you please close this issue if @Zhuinden's and my comments were helpful?
