### ISSUE TITLE
Realm.io site. Version is missed

### ISSUE THREAD

**Issue by jydimir** [realm/realm-java#2942]
Hi guys!

Today accidentally noticed that realm plugin version is missed on [realm.io](https://realm.io/docs/java/latest/#installation) site under the "Installation" section. I see [this](https://www.dropbox.com/s/wtzuyt68bjspju0/realm%20issue.PNG?dl=0). I think it should be: `classpath "io.realm:realm-gradle-plugin:1.0.0"`.

**Comment by beeender** [comment]
Thanks a lot! our web team is working on that. 
Since we have a bug created internally https://github.com/realm/realm.io-middleman/issues/767 , I will just close this one. It will be fixed soon.
