### ISSUE TITLE
Nested RealmObjects reference missing after transaction

### ISSUE THREAD

**Issue by Fintasys** [realm/realm-java#2954]
Hello together,

i just realized that the reference of nested RealmObjects get lost after transaction. Here is an example:
Is this wanted behaviour? 

#### Code

```
public class Trip extends RealmObject {
    Route route;
    @PrimaryKey
    String trip_id;
    // Getter & Setters
}
public class Route extends RealmObject {
    @PrimaryKey
    String route_id;
    // Getter & Setters
}

Trip t = new Trip();
Route r = new Route();
t.setRoute(r);

realm.beginTransaction();
t = realm.copyToRealm(t);
realm.commitTransaction();
```

#### Expected Results

Trip & Route created
t.getRoute() == r

#### Actual Results

Trip & Route created
t.getRoute() == null

#### Version of Realm and tooling
Realm version(s): 1.0.0

Android Studio version: 2.1.2

Which Android version and device: Galaxy A3 - 5.1.1

**Comment by emanuelez** [comment]
How do you actually perform the query and compare the route instance?

**Comment by Fintasys** [comment]
I'm very sorry, it was my mistake, not related to realm.io. Great Framework !
