### ISSUE TITLE
Creating Two Realm Databases  (Eg.  Players profile Databse , and league table Databse ) one after another

### ISSUE THREAD

**Issue by itzluxman** [realm/realm-java#2958]
When I try to write both of the async tasks one after another by calling the second async task in onPostExecute() of first async Task.  The internal memory crosses the roof (in my case >400MB)  but if i run those two async tasks in different program run (closing app completely after running one async task then running another ) but this is not how it was supposed to work right ? Or What are the probabilities that i am misusing ?

**Comment by kneth** [comment]
I am not sure I follow you completely. Do you have two Realms? In principle, they shouldn't interfere but a transaction will block the first Realm, and within this transaction you start a new, blocking the second Realm? 

Please post a little example for we can see what you try to do (and please use our template).

**Comment by cmelchior** [comment]
This issue sprang from this SO question: http://stackoverflow.com/questions/37682357/excessive-internal-memory-consumed-while-using-two-different-asynctask-on-same-r?noredirect=1#comment62864088_37682357

But please post the entire class, because the code on GitHub isn't a valid AsyncTask class.

**Comment by itzluxman** [comment]
@kneth   can you check this out once ? 

http://stackoverflow.com/questions/37682357/excessive-internal-memory-consumed-while-using-two-different-asynctask-on-same-r

**Comment by kneth** [comment]
@itzluxman We have added a couple of comments to the SO question :-)

**Comment by itzluxman** [comment]
Thanks :)  but i am  a bit confused about how do i execute what you told and how the same thing working and not working for two different type of contexts.

**Comment by itzluxman** [comment]
Can you guys try to run two async task in series ? and see the result ?  I have tried the things you said and if i close the realm object after completing one async task then i cannot use it anymore  for another async task by calling new Realm instance   `Realm realm = Realm.getDefaultInstance();`

**Comment by itzluxman** [comment]
guys i tried initializing   realm Instance inside doinbackground()'s start and closed it at the end of doinbackground()  it creates db  but unfortunately it takes more than 400MB , i think you guys should  definitely try running two separate asynctask in row (one after another ) and  try to solve this issue. and if it is not issue then it would be amazing but even after following all of you guys instruction i face the same issue.  I hope this issue(in case it is ) will be solved soon. But in case it is not an issue, it would be better than heaven if you guys can share the example of running two asyncTasks one after another in single program run with efficient internal memory usage.
