### ISSUE TITLE
Realm all data is cleared when called by other phone.

### ISSUE THREAD

**Issue by rfrost77** [realm/realm-java#2966]
If someone calls to my phone, my all Realm data is gone. It happens only in OS 4.4.2 and 4.4.4. I just registered receiver for getting call event, but the receiver does not have any code.

In detail, schema is back to right previous version, for example if current schema is 4, it would go to 3. It causes MigrationNeededException. My migration util is good so crash does not happen, but all data is gone with schema backing.

CallReceiver.java
```
    @Override
    public void onReceive(Context context, Intent intent) {
        LogUtil.d(TAG, "onReceive");
        // I tested code in here does not any affect the bug situation by removing all code.
    }
```

RealmConfigurationBuilder
```
public static RealmConfiguration.Builder mBuilder = new RealmConfiguration.Builder(BaseApplication.get())
            .name(Realm.DEFAULT_REALM_NAME)
            .schemaVersion(SCHEMA_VERSION)
            .migration(new MigrationRealmUtil());
```

migrate method in MigrationUtil.java
```
@Override
    public void migrate(DynamicRealm realm, long oldVersion, long newVersion) {
        LogUtil.d(TAG, "migrate old " + oldVersion + " to new " + newVersion);
        // I tested code in here does not any affect the bug situation by removing all code.
    }
```

The app version that fires above bug has change of Realm migration, especially used addRealmListField(). Would it be relevant to the bug?

I'll wait response.

**Comment by Zhuinden** [comment]
Do you by chance use `android:process=":remote"`?

**Comment by rfrost77** [comment]
I don't use that code.

**Comment by kneth** [comment]
Do you experience the issue if you change orientation?

**Comment by emanuelez** [comment]
@rfrost77 Do you have any update on this?

**Comment by kneth** [comment]
I am closing the issue due to inactivity. Please reopen or create new issue if any news.

**Comment by dalinaum** [comment]
@rfrost77 has reported all devices, which encountered this problem, used KitKat (4.0.2, 4.0.4) and Snapdragon (mostly, 800 MSM8974, but 400 and 600 encountered this problem too.)
