### ISSUE TITLE
RealmPrimaryKeyConstraintException when adding to RealmList

### ISSUE THREAD

**Issue by hedtech** [realm/realm-java#2969]
#### Scenario

Here is the following scenario :

```
class WrapperItemWithoutPrimaryKey implements ... {
    RealmList<ItemWithoutPrimaryKey> itemList;

    public void addItem( ItemWithPrimaryKey subitem  /* Already added in Realm */) {
        ItemWithoutPrimaryKey item = new ItemWithoutPrimaryKey(); // New
        item.setSubitem(subitem);
        itemList.add(item); // RealmPrimaryKeyConstraintException here
    } 
} 

class ItemWithoutPrimaryKey implements ... {
    ItemWithPrimaryKey subitem;
    int counter;

    ...
}

class ItemWithPrimaryKey implements ... {
    @PrimaryKey
    String primaryKey;
}
```

#### Expected Results

Correctly adding the item in the list

#### Actual Results

RealmPrimaryKeyConstraintException, value exists

#### Why

In function copyToRealmIfNeeded : copyToRealm is called instead of copyToRealmOrUpdate.

```
if (realm.getTable(object.getClass()).hasPrimaryKey()) {
    return realm.copyToRealmOrUpdate(object);
} else {
    return realm.copyToRealm(object);
}

```
#### Version of Realm and tooling
Realm version(s): 1.0.0

Android Studio version: 2.1.1

Which Android version and device: 5.0

**Comment by stk1m1** [comment]
@hedtech 

Could you share with us how you spawn `RealmList<ItemWithoutPrimaryKey> itemList`? Better yet, if you could create a small project to reproduce the error you're going through, we can help you faster.

I see `copyToRealmIfNeeded()` is an internal method and it works as designed.

**Comment by hedtech** [comment]
Hello,

The problem is that you decide to call copyToRealmOrUpdate or copyToRealm based on the top object. In this case is copyToRealm.
If the top object has no primary key but the nested do have copyToRealm will not work.

No ?

**Comment by hedtech** [comment]
How can I remove the Help label ? I already had an alternate solution (using the same primary key on the top item and the object as an ignored attribute).
I just think this is a limitation.

**Comment by stk1m1** [comment]
@hedtech 

Generally, it's not a great idea to have a top-level object without `@PrimaryKey` as it would follow the path you've been through. Glad you've found a solution. I'm closing the issue for now.

**Comment by hedtech** [comment]
I think it's a very good idea.
It's just a limitation not specified in the documentation !!!!!

Thanks

**Comment by stk1m1** [comment]
@hedtech 

We'll add mode description on that part. Thanks for the pointer! 👍

**Comment by hedtech** [comment]
Isn't is possible to call directly copyOrUpdate(object, boolean) ?
Can that corrupt the db ?

Thanks

**Comment by stk1m1** [comment]
I'd rather not. Internal methods are subject to change/removed/alternated anytime & all the time they are deemed necessary. If you're relying on an internal one, it might give you a hard time later correct your codebase. 

After all, the public API in 1.0.0 is our solemn vow to keep the convent for the community; they are here to stay.

**Comment by hedtech** [comment]
RealmList is part of the API & Library, no ? So I don't see any problem in calling internal private APIs.

**Comment by stk1m1** [comment]
RealmList _is_ a part of the API & Library. ;)
