### ISSUE TITLE
Firebase like APIs

### ISSUE THREAD

**Issue by dadino** [realm/realm-java#2973]
I've played a bit with **Firebase Realtime Database** and I have to say, their APIs are awesome.

**Reading** works in two way: listen for changes in the object (receiving the whole object in the callback) or listen for changes in the object child (receiving an added/removed/changed callback for a child of the object).  The first way is useful for when you read data of an object (I used it with Views that know the url of their attribute and read directly from the Snapshot), the second one is perfect for RecyclerView, to notify the adapter with events from the database.

You don't have a query API that returns the object, the listener is called immediately after you run the query (and every time something happens to the object).  
Callbacks return a DataSnapshot, a snapshot of the data of when the change happened. You can navigate the snapshot (or any other reference) by using urls, like:
 
    int horsePower = snapshot.child("john/cars/ford_mustang/horse_power");
    //Or the equivalent
    int horsePower = snapshot.child("john").child("cars").child("ford_mustang").child("horse_power");
This is mirrored for **writes**

    mJohnRef.child("cars").child("ford_mustang").child("horse_power").setValue(235);
    //Or the equivalent
    mJohnRef.child("cars/ford_mustang/horse_power").setValue(235);
It also works with POJOs to define the objects and just read/write them (it serialize/deserialize a JSON, ala Realm).
This is just a very quick explanation to show you the basic idea.

**Would it be possibile to create something like this with Realm?**

**Comment by cmelchior** [comment]
RealmChangeListeners work very much the same way, especially our async API's

```
// Return immediately a "promise" that can act as a list.
RealmResults<Car> cars  = realm.where(Car.class).findAllAsync(); 

// Register change listeners to get notified about all updates
cars.addChangeListener(new RealmChangeListener() {
  @Override
  public void onChange(RealmResults<Car> result) {
    // Called when the results are loaded or are otherwise updated.
  }
});
```

You can register change listeners for single objects as well or for any query, or you can use `asObservable()` to convert directly to RxJava observables.

Realm is an MVCC database, which gives you a consistent snapshot of the data for each thread. That snapshot is then automatically updated on looper events as needed, ensuring that all data is consistent at all times.

So yes, all the concepts you describe above should be expressible in the Realm API's.

**Comment by dadino** [comment]
That covers the first way of listening. What about the child events based listening? Getting a new list of Cars won't help me figure out what was added/removed/moved/changed.

Also, is there a way to read using paths, down to the single attribute?

Don't get me wrong, I use and love Realm, this is not a "Firebase is better, you suck" thread, I'm just suggesting an additional set of APIs.

**Comment by cmelchior** [comment]
Right now Realm doesn't support listening for changes on a child of an object. However that is planned as part of #989. Especially for RecyclerView animations the current listeners are not enough and those are definitely something we want to support as part of #989.

Realm uses a more type-safe approach and Java oriented approach than Firebase when it comes to the API's, so reading from paths is done just like you would a normal object, e.g.

```
/Car ford = realm.where(Car.class).equalTo("type", "Ford_mustang").findFirst();
ford.setHorsePower(255);
```

I am not familiar enough with Firebase, but I assume that this `cars/ford_mustang/horse_power` finds the property `horse_power` on the car with the unique id `ford_mustang` ?

**Comment by dadino** [comment]
Exactly. I think it is near your concept of dynamic Realm, but this one goes a little deeper.

**Comment by Zhuinden** [comment]
In order to receive change notifications from a child object, you need to specify a realm change listener for the child "table" (as in, a `RealmResults<T>` that queries child objects directly).

**Comment by kneth** [comment]
I guess what @Zhuinden suggests is that you could add a primary key (let's call it `id`), then you can do `RealmResults<Car> favoriteCar = realm.where(Car.class).equalTo("id", myFavotiteId).findAll()`. Adding a listener to `favoriteCar` is effectively be adding a listener to the object since `favoriteCar` will always only contain that particular object.

**Comment by cmelchior** [comment]
Just to summarise here: A syntax like `/obj/primaryKey/property` is not something we consider at this point as we generally try to drive our API's to be more type safe. We don't succeed fully in that, with the query API being an example, but it is a design goal and this proposal will definitely make that worse.

All other issues brought up around listeners should already be covered by other issues.
