### ISSUE TITLE
RealmConfiguration.allowWritesOnUiThread()

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#2976]
After a discussion in #2952, we came to the conclusion that given how async queries work, it is impossible to mix synchronous writes on the UI thread and async queries and still guarantee a consistent view for all RealmResults: https://github.com/realm/realm-java/pull/2952#issuecomment-225082505

Before we changed `syncIfNeeded` to only happen on Looper threads the problem also existed, but instead manifested itself as all async queries would convert to run directly on the UI instead, which broke the API contract given by `findAllAsync()`

After we changed it, the problem became worse though as now async RealmResults would `advance_read` (due to the commit), but detached row accessors might appear due to us not calling `syncIfNeeded`. This could result in unexpected crashes.

This race condition is impossible to avoid, so I suggest the following changes:
#2952 will introduce a log warning if you mix those async queries and sync writes. This will be shipped in 1.0.1

In 1.1.0 or later,  we introduce a new `RealmConfiguration.allowWritesOnUiThread()` option. The default value is `true` to avoid breaking changes, but it will make it possible for people to it on and fix their code.

In 2.0 we change the default value from `true` to `false`, so the default behaviour is that writes on the UI thread is not allowed.

**Comment by cmelchior** [comment]
See also https://github.com/realm/realm-cocoa/issues/3665 and https://github.com/realm/realm-cocoa/pull/3439 as Cocoa might be working on a competing proposal. We need to align on this.

**Comment by beeender** [comment]
So this will be only applied to the UI thread but not all looper thread? But all looper thread could have exact the same problem.

**Comment by cmelchior** [comment]
Yes, that is correct. Perhaps `allowWritesOnLooperThreads()` would be a better name :)

**Comment by beeender** [comment]
@cmelchior I think we can close this.

**Comment by cmelchior** [comment]
In order to avoid breaking the API too much if we change defaults I would suggest the API should be:

```
RealmConfiguration.Builder.allowWritesOnUiThread(bool)
RealmConfiguration.Builder.allowQueriesOnUiThread(bool)
```

**Comment by cmelchior** [comment]
Note, the OP description isn't actually accurate anymore. There are no consistency issues either way. But writing data on the UI thread still needs to flush to disk which can either lead to dropped frames or ANR crashes.

This is especially a problem for Synced Realms where background writes might happen at any time and the changesets being integrated could be rather large.

Having these options thus also puts the behaviour in line with Google recommendations of keeping I/O away from the UI thread.
