### ISSUE TITLE
while loop with deleteFirstFromRealm() causes A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x7ef84c3572

### ISSUE THREAD

**Issue by tucson-tom** [realm/realm-java#2981]
#### Goal

Delete multiple excess realm objects with deleteFirstFromRealm() in a while loop.

#### Expected Results

Anything but a segfault.

#### Actual Results

Multiple calls to deleteFirstFromRealm() results in:

`A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x7ef84c3572`

#### Steps & Code to Reproduce

When 'extraelements' contains 27 or more entries, the second call to deleteFirstFromRealm() triggers the SIGSEGV.

````
RealmResults<DBElement> extraelements = currsection.getElements().sort("starttime", Sort.ASCENDING);
while (extraelements.size() > 25)
{
  Log.d("THIS_IS_A_TEST", "[extraelements] " + extraelements.size());
  extraelements.deleteFirstFromRealm();
  Log.d("THIS_IS_A_TEST", "[extraelements] " + extraelements.size());
}
````

Outputs:

````
D/THIS_IS_A_TEST: [extraelements] 27
D/THIS_IS_A_TEST: [extraelements] 26
D/THIS_IS_A_TEST: [extraelements] 26
A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0xffffff9be54b6a in tid 11301 (on.appname)
````

#### Version of Realm and tooling
Realm version(s): 1.0.0
Android Studio version: 2.1.2
Which Android version and device: 6.0.1, Samsung Galaxy S6

#### Additional notes
This function is being executed inside a thread inside an IntentService.  Oddly, there is no stack trace available, so it took a long time to narrow the issue to that line of code.

**Comment by Zhuinden** [comment]
That's weird, you're clearly trying to delete an invalid object on the second time, but I thought Realm has already fixed that in 0.90.1.

RealmResults doesn't get automatically updated after deleting an element in it since 0.89.0, so if you delete the first element twice, the first element will be an invalid object on the second deletion. Considering the looper execution in an IntentService happens only when it actually receives an Intent, an IntentService essentially serves as a background thread, and not as a looper thread. So you can't really get auto-updating to work on a background thread.

Solution:

``` java
RealmResults<DBElement> extraelements = currsection.getElements().sort("starttime", Sort.ASCENDING);
while (extraelements.size() > 25)
{
  Log.d("THIS_IS_A_TEST", "[extraelements] " + extraelements.size());
  extraelements.deleteFirstFromRealm();
  extraelements = currsection.getElements().sort("starttime", Sort.ASCENDING);
  Log.d("THIS_IS_A_TEST", "[extraelements] " + extraelements.size());
}
```

**Comment by stk1m1** [comment]
@tucson-tom 

Thanks for the detailed report. Could you somehow share a small sample project including how you use Realm in a thread inside an IntentService please? While @Zhuinden's description on the nature of `RealmResults` is correct, it is nevertheless important for us to narrow down the root of the issue especially when there isn't much trace to follow.

Another suggestion is to use [`distinct`](https://realm.io/docs/java/1.0.0/api/io/realm/RealmQuery.html#distinct-java.lang.String-) for getting distinctive elements and sort them to get a result you're looking for.

**Comment by tucson-tom** [comment]
@Zhuinden - Thanks.  That helped put me on the right track.  It took a while to realize I was removing the actual elements instead of the references in the RealmList.

@stk1m1 - Making a small sample project is a bit out of scope and the project I'm working on is too large to boil down to something simple.  Sorry.
