### ISSUE TITLE
Requested table is not in this Realm. Creating it requires a transaction

### ISSUE THREAD

**Issue by BinarySatan** [realm/realm-java#2994]
when i first used `getDefaultRealm().where(clazz).equalTo(fieldName, (String) fieldValue).findFirst()`
it's no problem , **when i lock screen and then open it**,use the `getDefaultRealm().where(clazz).equalTo(fieldName, (String) fieldValue).findFirst()` it will crash

Requested table is not in this Realm. Creating it requires a transaction

**Comment by cmelchior** [comment]
Hi @BinarySatan 
I reopened https://github.com/realm/realm-java/issues/1017 instead. So if you can add any information there instead. That would be great. Especially if you can somehow reproduce this.
