### ISSUE TITLE
Is it "Support for cascading deletes" in Realm version(s): 1.0.0

### ISSUE THREAD

**Issue by gushoubang** [realm/realm-java#3000]
How can I use it,and if I use it like this https://github.com/realm/realm-java/issues/2717 ?

**Comment by beeender** [comment]
cascading deletes is still not implemented in `v1.0.0`. We have an open issue to track it #1104.
If you have any suggestion about this, you can comment on #1104. Sorry for the inconvenience.

**Comment by gushoubang** [comment]
Can it support in next version ?
