### ISSUE TITLE
Inconsistency when updating some field

### ISSUE THREAD

**Issue by yolapop** [realm/realm-java#3006]
#### Goal

> Having an object that is fully updated after performing update in Realm

#### Expected Results

> Same as goal

#### Actual Results

>  So I update 2 fields, the first field is always empty. But if I only update the first field and not the second field, the first field is not empty.

#### Code Sample

```java

public class Category extends RealmObject {
    @Setter @Getter @PrimaryKey private String id;
    @Setter @Getter private String name;
    @Setter @Getter private RealmList<SubCategory> subCategories;
    @Setter @Getter private RealmList<ProductItem> topProducts;
}

```

```java

public class SubCategory extends RealmObject {
    @Setter @Getter @PrimaryKey String id;
    @Setter @Getter String name;
    @Setter @Getter boolean category;

    /** Products that are shown in the front (in category screen) **/
    @Setter @Getter RealmList<ProductItem> items;

    /** Products that are shown in more products screen **/
    @Setter @Getter RealmList<ProductItem> moreProducts;
}

```

Now I do some update

```java

private void updateProducts(final RealmList<ProductItem> topProducts, final RealmList<SubCategory> subCategories) {
        realmAsync.executeTransactionAsync(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {
                Category category1 = realm.where(Category.class).equalTo("id", categoryId).findFirst();
                if (topProducts != null && topProducts.size() > 0) {
                    List<ProductItem> updatedTopProducts = realm.copyToRealmOrUpdate(topProducts);
                    RealmList<ProductItem> realmUpdatedTopProducts = new RealmList<ProductItem>();
                    realmUpdatedTopProducts.addAll(updatedTopProducts);
                    category1.setTopProducts(realmUpdatedTopProducts);
                }

                RealmList<SubCategory> subs = new RealmList<SubCategory>();
                for (int i = 0; i < 5; i++) {
                    SubCategory sub = new SubCategory();
                    sub.setId(999 + i + "");
                    sub.setName("sub " + 999 + i);
                    sub.setItems(topProducts); // this is the problem
                    subs.add(realm.copyToRealmOrUpdate(sub));
                }
                category1.getSubCategories().addAll(subs);
            }
        });
    }

```

I checked after the update

``` java

category.getTopProducts() // returns empty list

```

What's weird though

If I don't write this code `sub.setItems(topProducts);`, then `category.getTopProducts()` have the proper contents.

#### Version of Realm and tooling
Realm version(s): 0.88.0 and 1.0.0

Android Studio version: 2.1.1

Which Android version and device: Android One Marshmallow

**Comment by yolapop** [comment]
After further testing, this is caused by using realm object that has been added before.

`sub.setItems(topProducts)`

Here, `topProducts` actually has been added in here `category1.setTopProducts(realmUpdatedTopProducts)`

When I use `sub.setItems(someNewDummyProducts)`, the problem doesn't appear.

**Comment by stk1m1** [comment]
Hi @yolapop,

Thank you for the detailed report, and I think it might take few more questions to get the cause of your issue. There is, however, one thing stands out vividly to me.

in your logic above, you check if `topProducts` is an empty list.
> if (topProducts != null && topProducts.size() > 0) {

Then, there is no checker for `SubCategory`
> sub.setItems(topProducts); // this is the problem

Could you somehow verify that you are not adding an empty list to `SubCategory sub`?
It seems the same `topProducts` gets added to many `SubCategory sub` and one `Category category1` but null checking is inconsistent between the two types.

**Comment by yolapop** [comment]
Yes, I've verified that `topProducts` was not empty.

I was debugging for a whole day and ended up using the last commit that doesn't show this problem and tracing my code from that.

Eventually I've come to this:

Each of the `topProducts` was asigned a `Category`, and inside a `Category` there is `topProducts`.

Here's product model:

```java

public class ProductItem extends RealmObject {
    @Setter @Getter private Category category;
    @PrimaryKey @Setter @Getter private String id;
    @Setter @Getter private String name;
    @Setter @Getter private String description;
    /** possibly the cheapest price **/
    @Setter @Getter private double priceMain = 0;

```

Now, before I call `updateProducts` function, I set each of `topProducts` a `Category`.

``` java

response.setCategory(categoryA); // if I don't call this, the problem wouldn't occur

```

So, it seems like a circular link problem.

**Comment by yolapop** [comment]
I think I see the problem.

**Comment by yolapop** [comment]
Yeah, so I wasn't careful when using `copyFromRealm` and ended up copying stale objects.
Thanks for the support

**Comment by stk1m1** [comment]
@yolapop 
No problem. ;)
