### ISSUE TITLE
Realm issue: signal 11 (SIGSEGV), code 1 (SEGV_MAPERR)

### ISSUE THREAD

**Issue by Marcel50506** [realm/realm-java#3007]
In my app, I'm getting a SIGSEGV error:

`signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x240`

This happens when I bind a 'Werkbon' (extends RealmObject) to a row in a recyclerview through Android databinding. More specifically, while it tries to get the 'start' value (a Date object) in this 'Werkbon'.

It does not happen all the time, but it does occur after a full reinstall of the app.

Please see [this link](http://pastebin.com/raw/ZAnBm5Nr) for the tombstone, recorded from the emulator. Please let me know if you need any more information.

PS: I'll be out of the country for a couple of days, so response can take some time.

#### Version of Realm and tooling
Realm version: 
Realm-java 1.0.0

Android Studio version:
Android Studio 2.2 preview 3

Which Android version and device: ?
Both Android Emulator on API 23 and Moto G 3rd on API 23

**Comment by cmelchior** [comment]
A guess would be that you are trying to access a deleted object, but for some reason we are not throwing the proper exception, but without something to reproduce it. It is hard to say.

We have identified a few edge cases where something like this could happen for ListView/RecyclerView, and are working on a fix for 1.0.1

**Comment by Marcel50506** [comment]
I thought about this being an issue with a deleted element, but I expected an exception, not a SIGSEGV.

I will try to pinpoint it to possibly deleted objects, I'll come back to this.

Regarding reproducing: I wasn't able to reproduce this in a simple way, it only happens in this specific app.

**Comment by cmelchior** [comment]
Hi @Marcel50506 Yes, we have tried very hard to get rid of all native crashes, so you only experience Java exceptions. I tested the deleted object hypothesis on a single object and it don't seem to be that, so any more hints on how to reproduce this would welcome.

**Comment by Marcel50506** [comment]
**What happened before**

I was displaying some RealmObject A in a recyclerview . When I start the app (or it resumes), I reload all A's. In the response of the http-call, I delete all A's, and add the list of A's from the response to the realm.

**Status now**

I changed the way I replace the old A's with the new A's: First I look what the overlap is between the new list of A's (from the http-response), and delete everything else. After that, I add the A's in the response list to the realm through "copyToRealmOrUpdate". This way, A's that were deleted first and than added again, are now persisted.

Using the new approach ('status now'), I haven't seen any crashes anymore. Also I've seen the crash with the old approach, while using Realm 1.0.1.

**Comment by kneth** [comment]
@Marcel50506 Thanks for the update. It sounds like you have found a way to avoid the crash - that's good. Still, we don't want any users to experience native crashes, and it sounds like we have a case in our error detection which isn't fully waterproof.

**Comment by kneth** [comment]
@Marcel50506 I will close the issue for now. If you see any native exceptions again, please report them to us. As @cmelchior says, we try very hard to guard you against them but we might miss a few corner cases.
