### ISSUE TITLE
Realm is out of date after getDefaultInstance

### ISSUE THREAD

**Issue by markini** [realm/realm-java#3009]
Hello, I have some problems with synchronizing realms.

Here is a simplified version of what I'm trying to do (adding tasks to a project when the `Updated` value is null in a synchronized method --> `projectId` in `Project` is the `PrimaryKey`):

```java
public synchronized void addTasksToProject(String projectId, List<Task> tasks) {
	Realm realm = Realm.getDefaultInstance();
	try {
		final Project project = realm.where(Project.class).equalTo("projectId", projectId).findFirst();
		if (project.getUpdated() == null) {
			realm.executeTransaction(new Realm.Transaction() {
				@Override
				public void execute(Realm realm) {
					... add tasks
					project.setUpdated(some value);
				}
			});
		}
	} finally {
		realm.close();
	}
}
```

Issue: I have 2 threads (both worker threads, in the last instance the first was `Thread-6392` and the other was `RxComputationScheduler-3`) and both accessing this method with the same `projectId`.

When the second thread accesses the method, the `Updated` value of the project is still null and it is adding tasks. 

My question: does a `Realm.getDefaultInstance();` provided realm not guarantee a realm which is up to date?

**Comment by stk1m1** [comment]
Hi @markini 

Before begining a transaction, all Realm instances are gauranteed to recieve all changes from other threads. It is thus advisable to query items within a transaction block if the items might be updated. I'd rewite yours as

```java
public synchronized void addTasksToProject(String projectId, List<Task> tasks) {
    Realm realm = Realm.getDefaultInstance();
    try {
        realm.executeTransaction(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {
                final Project project = realm.where(Project.class).equalTo("projectId", projectId).findFirst();
                if (project.getUpdated() == null) {
                    ... add tasks
                    project.setUpdated(some value);
                }
            }
        });
    } finally {
        realm.close();
    }
}
```
You could also help us provide best possbile support if you can fill up our [issue filing template](https://github.com/realm/realm-java/blob/master/CONTRIBUTING.md#filing-issues) Thanks!

**Comment by markini** [comment]
Roger that, thanks for the support.
