### ISSUE TITLE
Realm 1.0 / Android - Exceptions trying to use realm db from assets 

### ISSUE THREAD

**Issue by ckompella** [realm/realm-java#3017]
> What do you want to achieve?

I want to use a realm db file created on iOS ( with realm 1.0.0) in my Android project. I have put the realmdb file in assets folder. This is a fresh project so migration is really not needed.

#### Expected Results  
Given code should not throw exception and migrate easily.

#### Steps & Code to Reproduce

Realm.removeDefaultConfiguration();

                RealmConfiguration config = new RealmConfiguration.Builder(TestActivity.this)
                        .name(Realm.DEFAULT_REALM_NAME)
                        .assetFile(TestActivity.this, MY_DB_FILE_NAME)
                        .build();
  // Note -  if I give schemaVersion(1) -> it gives MigrationNeeded Exception.
  // if I give don't give a schema version, it gives a version on disk is v1 vs v0 exception.

                Realm.setDefaultConfiguration(config);
                Log.d(TAG,"Config schema version"+config.getSchemaVersion());  <---- this returns 0
                Realm realm = Realm.getDefaultInstance();
                if (realm.isEmpty()) {
                    subscriber.onError(new Exception("Realm is empty"));
                } else {
                    subscriber.onCompleted();
                }

#### Version of Realm and tooling
Realm version(s): ? 1.0

Android Studio version: ? 2.1

Which Android version and device: ?  Marshmallow, Nexus 5x

**Comment by cmelchior** [comment]
It sounds like your asset file is a v1 file. The version in Java needs to match that. Have you tried:

```
            RealmConfiguration config = new RealmConfiguration.Builder(CategoriesActivity.this)
                    .name(Realm.DEFAULT_REALM_NAME)
                    .schemaVersion(1)
                    .assetFile(CategoriesActivity.this, MY_DB_FILE_NAME)
                    .build();
```

**Comment by ckompella** [comment]
yes, as mentioned, with that, I get a MigrationNeeded Exception.

**Comment by cmelchior** [comment]
The MigrationNeededException comes with a message, most likely the schema on Java doesn't match the iOS schema?

**Comment by ckompella** [comment]
from the realm db file, I generated the Java definitions using Realm browser and am using those java classes in my project. So, I doubt if it is that.

**Comment by stk1m1** [comment]
Hi @ckompella 

I see you're coming from <http://stackoverflow.com/questions/37844308/android-error-loading-realm-db-file-from-assets>. Could you possibly share your iOS and Android model, and an asset file with us at help@realm.io?

**Comment by ckompella** [comment]
ok

**Comment by stk1m1** [comment]
Discussion continues here. https://secure.helpscout.net/conversation/216048850/4925/?folderId=736840

**Comment by Zhuinden** [comment]
Can't this be because of the date millisecond support?

**Comment by stk1m1** [comment]
@Zhuinden 

Actually it's due to a delayed upgrade on our browser. There is PR [#184](https://github.com/realm/realm-browser-osx/pull/184) for this schedule to be merged and it will soon be fixed. 😉

**Comment by kneth** [comment]
I know that we have released a new version of the Realm Browser (for OS X) but the fix has been merge. I am closing the issue.

**Comment by manmohansoni** [comment]
Hi kneth, 
could you please let me know the proper implementation of the copy a realm file from asset folder. Please share any link with example. I need to set this functionality from starting of the project.

**Comment by beeender** [comment]
@manmohansoni https://realm.io/docs/java/3.4.0/api/io/realm/RealmConfiguration.Builder.html#assetFile-java.lang.String-
