### ISSUE TITLE
Uploading and Downloading Realm from a cloud database 

### ISSUE THREAD

**Issue by WanClem** [realm/realm-java#3019]
So my use case is that I want to upload a user's realm, used as the database for a chat app to a cloud database and download it later for use as the default realm for a user whenever he/she switches _log In_ device so he doesn't miss his messages...I.e Whenever user logs into app,users last realm(**user.realm**) is downloaded from a cloud store(if available) and used as the  default realm,else create a new realm using(**user.realm**)....How can I achieve this? Thanks...

**Comment by stk1m1** [comment]
Hi @WanClem 

Here's [a series of articles](https://medium.com/glucosio-project/backup-restore-a-realm-database-on-google-drive-with-drive-api-c238515a5975#.b3qdrr9du) regarding your use case. Hope this helps.

**Comment by Zhuinden** [comment]
Personally I would recommend against this approach because migrations will give you a massive headache, I'd just store a JSON on the server side and then recreate the Realm based on that.

**Comment by stk1m1** [comment]
@Zhuinden 

I agree with on migration issue. It would cause a headache, but regarding his use case, it seems to be a valid option for now.

**Comment by WanClem** [comment]
Oh boy! Migration issues!!! I hate writing migration codes,I just don't get it right often,leading to my app crashing occasionally,I will look for another work around....Thanks....

**Comment by WanClem** [comment]
Cool..
