### ISSUE TITLE
Implementing Parcelable with Realm and Retrofit

### ISSUE THREAD

**Issue by randomlock** [realm/realm-java#3020]
I am using Retrofit for HTTP request . Converting Retrofit Model class to Realm Models was very easy . Although i had to remove the parcelable interface from my model because it doesn't recognize RealmList . My main class look something like

```
public class GameDetailModal extends RealmObject {

   public String description;
   public String name;
   public RealmList<GameDetailImages> images;
   public RealmList<GameDetailCharacters> characters;
   public RealmList<GameDetailDevelopers> developers;
   public RealmList<GameDetailFranchises> franchises;
   public RealmList<GameDetailGenres> genres;
   public RealmList<GameDetailPublishers> publishers;
   public RealmList<GameDetailSimilarGames> similarGames;
   public RealmList<GameDetailThemes> themes;
}
````

I need to save the Modal Object during orientation change because i don't want to re-download the entire data again  . The user has the option to save the data if he wants . So if the user saves the data and orientation occurs i can query that object by primary key . But what if he doesn't save the object and Fragment restarts by configuration change or other reasons . Is there any solution to retain the data during the restart or do i need to to separate my Retrofit and Realm model in order to implement Parcelable  .  

Realm version(s): 1.0.0

Android Studio version:  2.1.2

**Comment by stk1m1** [comment]
Hello @randomlock 

> But what if he doesn't save the object and Fragment restarts by configuration change or other reasons. Is there any solution to retain the data during the restart or do i need to to separate my Retrofit and Realm model in order to implement Parcelable. 

Although we are looking into providing Parcelable in the future as issued in #878, it still is best to save the data in case Fragment is expected to restart. If user has not opted to save the data, you can delete it at the end of app or Fragment's lifecycle

Parcelable, or any serialization per se, is best suitable to deploy when you're moving data between boundaries such as between processes, network, or IO. In your use case, as it seems from your description, you simply need a temporary data holder for Fragment to restart.

Please don't hesitate to provide more description on your use case for us to provide best possible support. We'll be all ears!

**Comment by Zhuinden** [comment]
This guide might help: https://nullpointer.wtf/android/using-retrofit-realm-parceler/

**Comment by randomlock** [comment]
@stk1m1 @Zhuinden -  Thank you for the answer . I am satisfied by the answer . Saving it temporarily looks to be the best option .

**Comment by stk1m1** [comment]
@randomlock 

Glad it helps. I'm closing the issue for now.

**Comment by mabuthraa** [comment]
For Parcelable see : https://stackoverflow.com/a/44456222/2267723
