### ISSUE TITLE
Is there a way to sort RealmResults by customized pattern

### ISSUE THREAD

**Issue by MAJHOOOOOL** [realm/realm-java#3021]
Hello 

I have These fields in my Student class

String Name
boolean isGraduated 
Date birthday

this is my results 

RealmResults<Student > results = realm.where(Student .class).findAll();

is there a way to sort it like this

first one only should be the student when his name equal to some String I provided 
then 
All students who have graduated ''youngest first and oldest in the End''
then  
All students who did not graduated ''youngest first and oldest in the End''

Is there way to do these in realm

"Sorry I do not speak English well"

**Comment by stk1m1** [comment]
Hello @MAJHOOOOOL,

Suppose your Student class is built like below
```java
public class Student extends RealmObject {
    String Name
    boolean isGraduated
    Date birthday
}
```
Then we can construct query like following.

1. It seems you want student whose name contains some string you provide  

  > first one only should be the student when his name equal to some String I provided 

  `contains("Name", "some string")`  
2. Then sort by age and filter by graduation.

  > All students who have graduated ''youngest first and oldest in the End''
  
  `.equalsTo("isGraduated", true).findAllSorted("birthday",  Sort.ASCENDING)`

3. When it comes to your last condition, it is a contradiction of the second, `who have graduated` so you'd need to build a separate query to find what you want.
  
  > All students who did not graduated ''youngest first and oldest in the End''

To sum it up, your first and second conditions could become like this.

```java
RealmResults<Student> results = realm.where(Student .class)
                            .contains("Name", "some string")
                            .equalsTo("isGraduated", true)
                            .findAllSorted("birthday",  Sort.ASCENDING);
```

Then for your last condition, we'd have to build another query

```java
RealmResults<Student> results = realm.where(Student .class)
                            .contains("Name", "some string")
                            .equalTo("isGraduated", false)
                            .findAllSorted("birthday",  Sort.ASCENDING);
```
- - - 
Realm provide a flexible query system. There is [a good guide](https://realm.io/docs/java/latest/#queries) and [API document](https://realm.io/docs/java/1.0.1/api/io/realm/RealmQuery.html). I'd encourage you to take a look.

**Comment by MAJHOOOOOL** [comment]
Thank you for your answer @stk1m1 

Let me explain my situation 

I have Realm DB in my Android app and I use realm-recyclerview:

https://github.com/thorbenprimke/realm-recyclerview

The problem is I can not use 2 RealmResults as data resources 

And I think first Item will be duplicate in the Other results

Do what I say is true or I have a misunderstanding?

And 

Is there better way to sort a RecyclerView?

**Comment by stk1m1** [comment]
hi @MAJHOOOOOL,

In case you only want to have one `RealmResults`, you should remove the contradictory condition; 
> All students **who have graduated** ''youngest first and oldest in the End''
then
All students **who did not graduated** ''youngest first and oldest in the End''

You try to search 1) who have graduated, and 2) who did not graduate at the same time and you'll always get empty results.

**Comment by MAJHOOOOOL** [comment]
I do not want to search about graduated or not graduate 
I want to search about all Student 
And sort the results without filter the results 

I want to rearrange items inside RealmResults
To become like
in the top
Custom item "some string"
then
All students who have graduated '' youngest first and oldest in the End ''
.
.
.
.
then
All students who did not graduated '' youngest first and oldest in the End ''
.
.
.
.

Thank you

**Comment by kneth** [comment]
@MAJHOOOOOL you can sorting on multiple fields.That can result in:

All students who have graduated '' youngest first and oldest in the End ''
All students who did not graduated '' youngest first and oldest in the End ''

Can you give an example of what "Custom item "some string"" can be?

**Comment by stk1m1** [comment]
Hi @MAJHOOOOOL ,

If I get what you'd look for, the query will look like this.
```java
RealmResults<Student> results = realm.where(Student.class)
                            .contains("Name", "some string")
                            .findAll()
                            .sort("isGraduated",  Sort.Sort.DESCENDING, "birthday", Sort.ASCENDING);
```

In the last line, the results are sorted by two conditions in different order that could yield what you'd look for.

**Comment by Zhuinden** [comment]
I recommend a solution similar to this one: http://stackoverflow.com/a/34976540/2413303

**Comment by kneth** [comment]
@MAJHOOOOOL Did you find a solution?

**Comment by stk1m1** [comment]
@MAJHOOOOOL 

If same issue arise in the future, please let us know. I'm closing the issue for now.
