### ISSUE TITLE
Realm Plugin/Transformation 1.0.1 Suspicious "unexpectedly contains class" Warnings

### ISSUE THREAD

**Issue by diegomontoya** [realm/realm-java#3022]
We are getting massive amount of gradle warning logs during build with 1.0.1. 1.0.0 has no such issue. 

```java
Warning: class [folders/1/10/realm-optional-api/it/unimi/dsi/fastutil/chars/Char2ByteRBTreeMap$KeySet.class] unexpectedly contains class [it.unimi.dsi.fastutil.chars.Char2ByteRBTreeMap$KeySet]
Warning: class [folders/1/10/realm-optional-api/it/unimi/dsi/fastutil/chars/Char2ByteArrayMap$EntrySet$2.class] unexpectedly contains class [it.unimi.dsi.fastutil.chars.Char2ByteArrayMap$EntrySet$2]
api/it/unimi/dsi/fastutil/chars/Char2ByteRBTreeMap$KeySet.class] unexpectedly contains class [it.unimi.dsi.fastutil.chars.Char2ByteRBTreeMap$KeySet]
Warning: class [folders/1/10/realm-optional-api/it/unimi/dsi/fastutil/chars/Char2ByteArrayMap$EntrySet$2.class] unexpectedly contains class [it.unimi.dsi.fastutil.chars.Char2ByteArrayMap$EntrySet$2]
Warning: class [folders/1/10/realm-optional-api/it/unimi/dsi/fastutil/chars/Char2LongLinkedOpenHashMap.class] unexpectedly contains class [it.unimi.dsi.fastutil.chars.Char2LongLinkedOpenHashMap]
Warning: class [folders/1/10/realm-optional-api/it/unimi/dsi/fastutil/chars/CharBigArrays$1.class] unexpectedly contains class [it.unimi.dsi.fastutil.chars.CharBigArrays$1]
Warning: class [folders/1/10/realm-optional-api/it/unimi/dsi/fastutil/chars/AbstractChar2ObjectMap.class] unexpectedly contains class [it.unimi.dsi.fastutil.chars.AbstractChar2ObjectMap]
Warning: class [folders/1/10/realm-optional-api/it/unimi/dsi/fastutil/chars/Char2LongMaps$EmptyMap.class] unexpectedly contains class [it.unimi.dsi.fastutil.chars.Char2LongMaps$EmptyMap]
Warning: class [folders/1/10/realm-optional-api/it/unimi/dsi/fastutil/chars/Char2LongSortedMaps.class] unexpectedly contains class [it.unimi.dsi.fastutil.chars.Char2LongSortedMaps]
Warning: class [folders/1/10/realm-optional-api/it/unimi/dsi/fastutil/chars/Char2DoubleMap$Entry.class] unexpectedly contains class [it.unimi.dsi.fastutil.chars.Char2DoubleMap$Entry]
```

The "realm-optional-api" warnings encompass every single external class we use that have nothing to do with realm, realm-module, or realm-object classes. The amount of warning logs are extensive so I just included a few above.

**Comment by beeender** [comment]
Similar warning for proguard http://proguard.sourceforge.net/manual/troubleshooting.html#unexpectedclass

Let me try to reproduce it and get back to you.

**Comment by beeender** [comment]
@diegomontoya 

1. Can you share the full gradle log? 
2. How do you use `fastutil` in your project? a jar or through the `compile group: 'it.unimi.dsi', name: 'fastutil', version: '7.0.11'`?

**Comment by diegomontoya** [comment]
@beeender Just emailed the gradle.log to info@realm.io and support@realm.io. 

Our gradle config for fastuil is as follows. 
```
compile 'it.unimi.dsi:fastutil:7.0.12'
```

Android Studio 2.2 Preview 3
Gradle 2.1.14

**Comment by diegomontoya** [comment]
@beeender Just emailed gradle2.log which contains the build log with the only diff that it is running under 1.0.0 realm plugin.

**Comment by beeender** [comment]
The warning is reported by DexGuard :( And I cannot reproduce it with ProGuard ... 

The `realm-optional-api` was introduced to solve the `RxJava` class cannot be found problem. It is using android transformer to do byte code manipulating for removing the `RxJava` related interface from Realm classes. There is an limitation of Android transformer is we cannot only output realm related classes (we do limit the manipulating scope to `Scope.EXTERNAL_LIBRARIES`), instead, we need to output all classes even we don't change any of them except a few Realm classes.

I think maybe DexGuard can help to take a look to see why it doesn't play well with this specific case (io.realm.xxx classes are also there, but it doesn't give warning about them)?

At the meantime, I think i makes sense to have a gradle option in Realm side to turn off the optional API transformer. What do you think @realm/java ?

**Comment by cmelchior** [comment]
A Realm config block makes sense IMO. We talked about adding it before

**Comment by beeender** [comment]
OK, I am adding it right now.

**Comment by beeender** [comment]
The relevant transformer has been disabled.
