### ISSUE TITLE
wrong value in version.txt

### ISSUE THREAD

**Issue by Aidin** [realm/realm-java#3032]
value in **version.txt** should be 1.0.1-SNAPSHOT
current value is 1.1.0-SNAPSHOT

**Comment by MGaetan89** [comment]
Version 1.0.1 was already [released](https://github.com/realm/realm-java/releases/tag/v1.0.1). So I think that the current value is correct.

**Comment by emanuelez** [comment]
We release patch releases from the `releases` branch and minor releases from `master`. I just checked and the value in both branches is correct.
