### ISSUE TITLE
Accelarate Realm transformer

### ISSUE THREAD

**Issue by beeender** [realm/realm-java#3034]
We got some complains (http://stackoverflow.com/questions/37928953/realm-gradle-tasks) about the speed of transformers and there is always space to improve it, like:
- Replace slow groovy with kotlin
- ...

**Comment by cmelchior** [comment]
Is Groovy really slower than Kotlin? It is all byte code under the hood, which in turn is dex. I think we should switch for other reasons though, and there are probably room for improvement in any case.

**Comment by emanuelez** [comment]
I don't think switching to Groovy would improve performance a lot, simply because most of the time is spent in Javassist. A more promising change would probably be to switch to ASM from Javassist.

**Comment by cmelchior** [comment]
There is also some things we need to investigate from this: https://twitter.com/ebtokyo/status/808816830118653952

- When/how is the transformer triggered. Is it possible to be more clever about which files are processed. 
- How does incremental builds effect this.
- How/when is the annotation processor triggered. Especially, why is it triggered if there is no code changes. I would assume the gradle build system could easily detect this case.

**Comment by emanuelez** [comment]
The Transform API has support for incremental builds which we're not using right now so there's space for improvements.
We don't have much control over when the AP is triggered. In general, I think it needs to run on every build because the generated classes might use or be indirectly used by the classes being changed.

**Comment by eboudrant** [comment]
@cmelchior thanks for the followup, I just wanted to update you, the slowness I reported on Twitter about Gradle was not because of Realm, it was another problem (our BuildConfig modified for each build).

**Comment by beeender** [comment]
Complain from SO http://stackoverflow.com/questions/42208219/android-build-time-is-too-long-due-to-more-tables-in-realm-database

**Comment by bmeike** [comment]
Another request: https://stackoverflow.com/questions/45318711/dont-try-to-rebuild-realm-model-every-time-run-android-build/45335850#45335850

**Comment by nateridderman** [comment]
Incremental builds would be huge. When I change a line of Java code in a class unrelated to Realm, then Realm shouldn't have to transform everything again. Based on profiling my Gradle build, this would save me at least 20 seconds out of a 60 second build for the transformClassesWithRealmTransformer task, and it seems like Realm is also contributing towards the compileJavaWithJavac task.

**Comment by meierjan** [comment]
Any reasons why this task can take up to 38 secs?

```
:app:transformClassesWithRealmTransformerForXDebug | 37.690s
```

**Comment by thorbenprimke** [comment]
@beeender @cmelchior Any update on this? It's one of the longest gradle tasks when building our app (@pinterest). Even just improving it for incremental builds would be huge.

**Comment by whataa** [comment]
Several modules of our project used realm, the compile time has been steadily increasing linearly with the number of modules. But your team did not make any new progress on the issue in more than a year, any specific schedule on this?

**Comment by pvegh** [comment]
It is nonsense. How can you do actual development with such a huge turnaround?
Not touching any Realm parts but still wasting so much time on it is insane.

**Comment by AamirAbro** [comment]
have been hit by realm slow compilations issues too. transformClassesWithRealm some times take more than 30 secs.
`:app:transformClassesWithRealmTransformerForDebug | 38.287s`

**Comment by muthuraj57** [comment]
After change a line in layout xml or anything not even remotely connected to realm still triggers this task which takes more than half of my total build time.

`:app:transformClassesWithRealmTransformerForDebug | 1m 18s`

**Comment by thorbenprimke** [comment]
@cmelchior - thanks for the update. I'll get that patched in on Monday and will report back.

**Comment by muthuraj57** [comment]
@cmelchior This snapshot improved my build time considerably. Previously it took more than 3 minutes to incremental builds. Not it is more or less one minute. Thanks a lot.

**Comment by cmelchior** [comment]
@muthuraj57 Thank you for reporting back. Would it be possible to post the log numbers for your build as well? A minute still sounds like a lot for incremental builds, so would be interesting to see where the time is actually being spent

**Comment by thorbenprimke** [comment]
@cmelchior - do you know when you will release the next version (5.1.1 or 5.2) that will include the new transformer improvements?

**Comment by cmelchior** [comment]
5.2.0 should be available in the next 24 hours.
