### ISSUE TITLE
Add method "getRealm()" to RealmObject

### ISSUE THREAD

**Issue by AntekM** [realm/realm-java#3042]
It would be nice if it would be possible to retrieve realm instance from attached object, instead of relying always on Realm.getInstance(). 
I know those instances are cached - so it's not about performance, but I tend to separate my business logic from UI code, and also use fragments etc (so even while I do open and close realm in activity lifecycle, I don't have realm reference accessible everywhere), so in each business method (for example "statusManager.updateStatus(realmObjectX, newStatus)")  where I want to do any operation on realm objects I need to obtain realm instance and close it. 

Brief examination of RealmObject makes me believe there's some internal method that does it, so it seems doable, although of course I'm not aware of all implications :)

**Comment by stk1m1** [comment]
Hi @AntekM 

Thanks for your input. Like you pointed, it might not be hard to implement, but it could make not-so-user-friendly API as it could invoke confusion to users.

There are many aspects to consider and, among those, for example, the fact that `RealmObject` could be managed and unmanaged is one thing we could consider. Providing `getRealm()` could bring inconsistency between two types of objects.

**Comment by cmelchior** [comment]
Hi @AntekM 
We discussed this internally, and we don't feel that adding a `getRealm()` method would be a good move. It will make it a lot harder to reason about which Realm you are working + there are corner cases around managed and un-managed objects as well.

We would much rather encourage people to seperate their architecture, so you have a place that knows about the Realm instance as well as updating objects. You are already halfway there by seperating UI code and buisness logic it seems, but I would encourage you to look into the repository pattern: http://martinfowler.com/eaaCatalog/repository.html and http://www.slideshare.net/ChristianMelchior/painless-persistence-in-a-disconnected-world#12

As well as our NewsPaperExample that shows how it can be used together with Realm: https://github.com/realm/realm-java/tree/master/examples/newsreaderExample
