### ISSUE TITLE
Realm Migration Issue

### ISSUE THREAD

**Issue by Sutirth** [realm/realm-java#3045]
Bug: Realm Migrations

Goal: Successful Migration to be done

Expected Result: To get migration done successful

Actual Result: Migration crash

Realm version(s): 0.90.1

Step 1: I create new Database table 

    public class NewTeamStatisticsDB extends RealmObject {
        private String teamName;
        @PrimaryKey
        private long totalStepCount;
        private long totalCalories;
        private long totalDistance;
        private long totalSweatPoints;
    }
        
Step 2: Migration
     public class Migration implements RealmMigration {
    
            @Override
            public void migrate(final DynamicRealm realm, long oldVersion, long newVersion){
    
                RealmSchema schema = realm.getSchema();
    
                //  ***********************************************************
    //  **** This will migrate from version 0 to version 1 ****
    //  ***********************************************************
                if (oldVersion == 0) {
                    RealmObjectSchema sweatPointSchema = schema.get("UserInfoDB");
                    sweatPointSchema.addField("sweatPoints",Integer.class);
                    oldVersion++;
                }
    
    //  ***********************************************************
    //  **** This will migrate from version 1 to version 2 ****
    //  ***********************************************************
                if(oldVersion == 1) {
                    RealmObjectSchema teamInfoSchema = schema.get("TeamInfoDB");
                    teamInfoSchema.addField("teamDescription",String.class);
    
                    oldVersion ++;
                }
    
    //  ***********************************************************
    //  **** This will migrate from version 2 to version 3 ****
    //  ***********************************************************
                if(oldVersion == 2) {
                    RealmObjectSchema leaderboardInfoSchema = schema.get("LeaderBoardDb");
                    leaderboardInfoSchema.addField("displayName", String.class);
    
    
    
                    oldVersion ++;
                }
    //  ***********************************************************
    //  **** This will migrate from version 3 to version 4 ****
    //  ***********************************************************
    
                if(oldVersion == 3){
    
                    RealmObjectSchema sweatPointFitnessSchema = schema.get("SweatPointFitnessDB");
                    sweatPointFitnessSchema.addField("badgeSweatPoints", int.class);
                    sweatPointFitnessSchema.setNullable("badgeSweatPoints", true);
    
    
                    RealmObjectSchema userInfoSchema = schema.get("UserInfoDB");
                    userInfoSchema.addField("profileImageUpdatedAt", String.class);
    
                    oldVersion++;
                }
    
    
                //  ***********************************************************
    //  **** This will migrate from version 4 to version 5 ****
    //  ***********************************************************
    
    
                if(oldVersion == 4){
    
                    RealmObjectSchema sweatPointFitnessSchema = schema.get("SweatPointFitnessDB");
                    sweatPointFitnessSchema.setNullable("badgeSweatPoints", false);
    
    
    
    
                    oldVersion++;
                }
    
                //  ***********************************************************
    //  **** This will migrate from version 5 to version 6 ****
    //  ***********************************************************
    
                if(oldVersion == 5){
    
                    RealmObjectSchema sweatPointFitnessSchema = schema.get("SweatPointFitnessDB");
                    sweatPointFitnessSchema.setNullable("badgeSweatPoints", true);
    
    
    
    
                    oldVersion++;
                }
    
                //  ***********************************************************
                //  **** This will migrate from version 6 to version 7 ****
                //  ***********************************************************
    
                if(oldVersion == 6){
    
    
                    schema.get("LeaderBoardDb")
                    .addField("userPercentile", float.class)
                    .addField("userRank", int.class)
                    .addField("userRewards",int.class)
                    .addField("userSweatPointsEarned", int.class)
                    .removeField("percentile")
                    .removeField("rank")
                    .removeField("rewards")
                    .removeField("sweatPointEarned")
                            .renameField("userPercentile", "percentile")
                            .renameField("userRank", "rank")
                            .renameField("userRewards","rewards")
                            .renameField("userSweatPointsEarned", "sweatPointEarned");
    
                    oldVersion++;
                }
    
    
                //  ***********************************************************
                //  **** This will migrate from version 7 to version 8 ****
                //  ***********************************************************
    
    
                if(oldVersion == 7){
                    RealmObjectSchema teamInfoSchema = schema.get("TeamInfoDB");
                    teamInfoSchema.addField("profileImageUpdatedAt", String.class);
    
    
                    oldVersion++;
                }
    
                //  ***********************************************************
                //  **** This will migrate from version 8 to version 9 ****
                //  ***********************************************************
    
    
                if(oldVersion == 8){
                    RealmObjectSchema leaderBoardSchema = schema.get("LeaderBoardDb");
                    leaderBoardSchema.addField("profileImageUpdatedAt", String.class);
    
                    RealmObjectSchema sweatPointFitnessSchema = schema.get("SweatPointFitnessDB");
                    sweatPointFitnessSchema.setNullable("badgeSweatPoints", true);
    
    
    
                    oldVersion++;
                }
    
                //  ***********************************************************
                //  **** This will migrate from version 9 to version 10 ****
                //  **
    
                if(oldVersion == 9){
                    RealmObjectSchema sweatPointFitnessSchema = schema.get("SweatPointFitnessDB");
                    sweatPointFitnessSchema.removeField("badgeSweatPoints");
    
                    oldVersion++;
                }
    
    
                //  ***********************************************************
                //  **** This will migrate from version 10 to version 11 ****
                //  **
    
                if(oldVersion == 10){
                    RealmObjectSchema sweatPointFitnessSchema = schema.get("SweatPointFitnessDB");
                    sweatPointFitnessSchema.addField("BadgeSweatPoints", int.class);
                    oldVersion++;
                }
    
    
    
    
                //  ***********************************************************
                //  **** This will migrate from version 11 to version 12 ****
                //  **
                if(oldVersion == 11){
                    RealmObjectSchema rewardsDBSchema = schema.create("RewardsDB")
                                        .addField("rewardId", int.class , FieldAttribute.PRIMARY_KEY)
                                        .addField("title", String.class)
                                        .addField("description", String.class)
                                        .addField("productBrand", String.class)
                                        .addField("requiredSweatPoints", int.class)
                                        .addField("timeLimit",int.class)
                                        .addField("expiry", String.class)
                                        .addField("rewardStatus", int.class)
                                        .addField("userRewardStatus", int.class)
                                        .addField("totalQuantity", int.class)
                                        .addField("availableQuantity", int.class)
                                        .addField("itemCategory",String.class)
                                        .addField("itemImgUrlPrimary",String.class)
                                        .addField("itemImgUrlSecondary",String.class)
                                        .addField("itemPrice",int.class)
                                        .addField("itemDiscount",int.class);
    
    
    
                    RealmObjectSchema rewardSourceDB = schema.create("RewardSourceDB")
                                                    .addField("id", int.class, FieldAttribute.PRIMARY_KEY)
                                                    .addField("name", String.class)
                                                    .addField("type", int.class)
                                                    .addRealmListField("rewardsDB", rewardsDBSchema);
    
    
    
    
    
    
                    oldVersion++;
                }
    
    
            //  ***********************************************************
                //  **** This will migrate from version 12 to version 13 ****
                //  **
    
    
                if(oldVersion == 12){
                    RealmObjectSchema rewardsDBSchema = schema.get("RewardsDB")
                                        .addField("rewardChaseDate", String.class)
                                        .addField("rewardRedeemDate", String.class);
    
    
                    oldVersion++;
                }
    
                //  ***********************************************************
                //  **** This will migrate from version 13 to version 14 ****
                //  **
    
    
                    if(oldVersion == 13) {
                      RealmObjectSchema sweatPointFitnessDBSchema =  schema.get("SweatPointFitnessDB")
                                .addField("rewardSweatPoints", int.class);
                        oldVersion++;
                    }
    
                //  ***********************************************************
                //  **** This will migrate from version 14 to version 15 ****
                //  **
    
                if(oldVersion == 14) {
                    RealmObjectSchema sweatPointFitnessDBSchema =  schema.get("SweatPointFitnessDB")
                            .addField("fordayDistance", int.class);
                    oldVersion++;
                }
    
                //  ***********************************************************
                //  **** This will migrate from version 15 to version 16 ****
                //  **
    
                if(oldVersion == 15) {
                    RealmObjectSchema leaderBoardSchema =  schema.get("LeaderBoardDb")
                            .addField("userStatus", int.class);
                    oldVersion++;
                }
    
                //  ***********************************************************
                //  **** This will migrate from version 16 to version 17 ****
                //  **
    
                if(oldVersion == 16){
                    RealmObjectSchema newTeamStatisticsDB = schema.create("NewTeamStatisticsDB")
                                                            .addField("teamName", String.class)
                                                            .addField("totalStepCount",long.class, FieldAttribute.PRIMARY_KEY)
                                                            .addField("totalCalories",long.class)
                                                            .addField("totalDistance",long.class)
                                                            .addField("totalSweatPoints",long.class);
                    oldVersion++;
                }
    
            }
    
    
        }

Step 3:
I forgot to change the migration number in here
  RealmConfiguration realmConfiguration = new RealmConfiguration.Builder(this)
                                            .schemaVersion(16)
                                            .migration(new Migration())
                                            .build();

after the launch when I change it to 17
RealmConfiguration realmConfiguration = new RealmConfiguration.Builder(this)
                                            .schemaVersion(17)
                                            .migration(new Migration())
                                            .build();

My application crashes. How should I fix it
Crash Report
E/AndroidRuntime:  Caused by: java.lang.IllegalArgumentException: Class already exists: NewTeamStatisticsDB
  at io.realm.RealmSchema.create(RealmSchema.java:116)
   at com.workoutguru.workoutcash.realmDB.Migration.migrate(Migration.java:271)
    at io.realm.BaseRealm$3.onResult(BaseRealm.java:699)
     at io.realm.RealmCache.invokeWithGlobalRefCount(RealmCache.java:259)
   at io.realm.BaseRealm.migrateRealm(BaseRealm.java:679)
   at io.realm.Realm.migrateRealm(Realm.java:1457)
    at io.realm.Realm.migrateRealm(Realm.java:1444)
 at io.realm.Realm.createInstance(Realm.java:256)
     at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:118)
   at io.realm.Realm.getDefaultInstance(Realm.java:195)

**Comment by zaki50** [comment]
Hi @Sutirth 

I think it's the best way to have a check that schema already contains the class "NewTeamStatisticsDB".

```
            if(oldVersion == 16){
                if (!schema.contains("NewTeamStatisticsDB")) { // add this line
                RealmObjectSchema newTeamStatisticsDB = schema.create("NewTeamStatisticsDB")
                                                        .addField("teamName", String.class)
                                                        .addField("totalStepCount",long.class, FieldAttribute.PRIMARY_KEY)
                                                        .addField("totalCalories",long.class)
                                                        .addField("totalDistance",long.class)
                                                        .addField("totalSweatPoints",long.class);
                }  // add this line
                oldVersion++;
            }
```

**Comment by Sutirth** [comment]
@zaki50  Thnx a ton it works !!! any update on this https://github.com/realm/realm-java/issues/2891

**Comment by zaki50** [comment]
No progress that we can share ATM, sorry.

**Comment by TimCastelijns** [comment]
@zaki50 can you explain how it can be that a schema already contains a class that has not yet been created? Perhaps concurrent migrations? I am experiencing this error currently and have no clue what is causing it. It looks like the proposed solution would work, but it makes no sense to me.

**Comment by Zhuinden** [comment]
@TimCastelijns is there a chance that your migration is initiated by two processes? Because multi-process migrations kinda kill things.

**Comment by TimCastelijns** [comment]
@Zhuinden I have a Realm.getDefaultInstance() in a BroadcastReceiver that is triggered via the manifest. The BroadcastReceiver is failing because of this error. In theory yes this could happen at the exact same time a User logs in to the app for the first time, also calling Realm.getDefaultInstance(), but the odds seem so incredibly low. Btw I am talking multi threading, not multi processing
