### ISSUE TITLE
Build failure during initial build due to android-23 SDK not being installed

### ISSUE THREAD

**Issue by bdash** [realm/realm-java#3051]
#### Goal

Build realm-java by following instructions in README.

#### Expected Results

Success!

#### Actual Results

Java exception thrown about android-23 not being found in ~/Library/Android/sdks when running `./gradlew assemble`. It did not happen when I reran the build command, and I neglected to save the exception message 😞If I can figure out which local state I can clear out to give me a clean slate to reproduce this from I'll provide more detail.

android-23 is not mentioned as required in realm-java's README, and doesn't seem to really be required to build.

#### Version of Realm and tooling
Realm version(s): 76c6178c01ff62c69d95543b219a4c23f5a23873
Android Studio version: 2.1.2

**Comment by stk1m1** [comment]
Hi @bdash 

Thanks for reporting the issue to us with the template filled! Nice of you! 

It is nevertheless our short-coming to overlook clearly stating the requirements, Android-sdk v23 is nevertheless required as it is specified in [here](https://github.com/realm/realm-java/blob/master/realm/realm-library/build.gradle#L14). 

Realm-java build system is constructed with [Gradle](http://gradle.org/) and it allows us to have this beautiful, compartmentalized, and hierarchical build requirement tree such that it is possible to construct each sub-project (module in Gradle) to have their own per-requisites. It might not be obvious from the first look though.

I'll escalate this issue and queued for proper update! Thanks!

**Comment by zaki50** [comment]
README.md has been fixed in #3062 (releases branch) and #3074 (master branch).

Thanks @bdash
