### ISSUE TITLE
Realm Filter By Date...

### ISSUE THREAD

**Issue by lkhore** [realm/realm-java#3054]
**How can i filter data by date those have date year is in 2014**

> We LOVE to help with any issues or bug you have!

> **Questions**: If you have questions about how to use Realm, please ask on [SO](http://stackoverflow.com/questions/ask?tags=realm) - we monitor the Realm tag.

> **Feature Request**: Just fill in the first two sections below.

> **Bugs**: To help you as fast as possible with an issue or bug please describe your issue and the steps you have taken to reproduce it in as many details as possible.
>
> Thanks for helping us help you :-)
>
> Remove this and above before submitting.

#### Goal

> What do you want to achieve?

#### Expected Results

> ?

#### Actual Results

>  E.g. full stack trace with exception

#### Steps & Code to Reproduce

> Describe your current debugging efforts.

#### Code Sample

```java

> Your code here. Bigger samples should ideally be as separate Android Studio project, 
> in gists/repositories or privately at help@realm.io)

```

#### Version of Realm and tooling
Realm version(s): ?

Android Studio version: ?

Which Android version and device: ?

**Comment by kneth** [comment]
Questions like this is best asked at Stackoverflow. But the quick answer is to use the [`between()`](https://realm.io/docs/java/1.0.1/api/io/realm/RealmQuery.html#between-java.lang.String-java.util.Date-java.util.Date-) predicate to find dates between 2014-01-01and 2014-12-31.

**Comment by lkhore** [comment]
Thanks.... :)
