### ISSUE TITLE
Do Realm Support Multilevel and abstract implementation?

### ISSUE THREAD

**Issue by krishnalalstha** [realm/realm-java#3055]
Suppose I do have class name Car which inherit some properties from parent Class Vehicle. As show below

Public class Card extends Vehicle {

}

How can i save such class into Realm database? How it would look like in table structure?

#### Version of Realm and tooling
Realm version(s): ?

Android Studio version: 2.1.2

Which Android version and device: Android 5.0 +

**Comment by cmelchior** [comment]
Hi @krishnalalstha 
Realm currently doesn't support inheritance. It is being tracked here: #761 Until then we recommend using composition instead.

**Comment by krishnalalstha** [comment]
Thanks @cmelchior. I got the whole story behind this :).
