### ISSUE TITLE
primitive type issue

### ISSUE THREAD

**Issue by santoshgistto** [realm/realm-java#3059]
Example:
class A{
int id;
B b;

}
class B{

C[] c;

}
class C{

}
primitive types not supporting, how to achieve to save the object.

**Comment by cmelchior** [comment]
We don't support primitive arrays like `C[]`, you need to use a `RealmList<C>`.

**Comment by santoshgistto** [comment]
@cmelchior thanks for response

i am using Gson to parse response.
here response i am getting need to store this.

{
        "id": 6067,
        "date": "2016-04-27T16:41:35",
        "date_gmt": "2016-04-27T16:41:35",
        "guid": {
            "rendered": "http://..."
        },
        "modified": "2016-04-27T16:41:35",
        "modified_gmt": "2016-04-27T16:41:35",
        "slug": "order-your-train-food-and-get-30-off-on-rooms-3",
        "type": "offer",
        "link": "http://...",
        "title": {
            "rendered": "title ..."
        },
        "content": {
            "rendered": ""
        },
        "excerpt": {
            "rendered": ""
        },
        "author": 1,
        "featured_media": 535,
        "offer_cat": [
            300
        ],
        "offer_tag": [
            301
        ],
        "better_featured_image": {
            "id": 5335,
            "alt_text": "",
            "caption": "",
            "description": "",
            "media_type": "image",
            "post": 56025,
            "source_url": "http://..."
        },
        "offer_type": "coupon",
        "offer_start": "1458086400",
        "offer_expire": "1458930600",
        "offer_store": "5420",
        "coupon_code": "code",
        "coupon_link": "http://....",
        "coupon_link_with_code": "http://...",
        "deal_status": "has_items",
        "deal_type": "shared",
        "offer_in_slider": "no",
        "store_name": "xyx",
        "pure_taxonomies": {
            "offer_cat": [
                {
                    "term_id": 300,
                    "name": "Travel",
                    "slug": "travel",
                    "term_group": 0,
                    "term_taxonomy_id": 300,
                    "taxonomy": "offer_cat",
                    "description": "",
                    "parent": 0,
                    "count": 207,
                    "filter": "raw",
                    "object_id": 6067
                }
            ]
        }
    }

**Comment by pratamawijaya** [comment]
@santoshgistto please format your code

```
{
  "id": 6067,
  "date": "2016-04-27T16:41:35",
  "date_gmt": "2016-04-27T16:41:35",
  "guid": {
    "rendered": "http:\/\/..."
  },
  "modified": "2016-04-27T16:41:35",
  "modified_gmt": "2016-04-27T16:41:35",
  "slug": "order-your-train-food-and-get-30-off-on-rooms-3",
  "type": "offer",
  "link": "http:\/\/...",
  "title": {
    "rendered": "title ..."
  },
  "content": {
    "rendered": ""
  },
  "excerpt": {
    "rendered": ""
  },
  "author": 1,
  "featured_media": 535,
  "offer_cat": [
    300
  ],
  "offer_tag": [
    301
  ],
  "better_featured_image": {
    "id": 5335,
    "alt_text": "",
    "caption": "",
    "description": "",
    "media_type": "image",
    "post": 56025,
    "source_url": "http:\/\/..."
  },
  "offer_type": "coupon",
  "offer_start": "1458086400",
  "offer_expire": "1458930600",
  "offer_store": "5420",
  "coupon_code": "code",
  "coupon_link": "http:\/\/....",
  "coupon_link_with_code": "http:\/\/...",
  "deal_status": "has_items",
  "deal_type": "shared",
  "offer_in_slider": "no",
  "store_name": "xyx",
  "pure_taxonomies": {
    "offer_cat": [
      {
        "term_id": 300,
        "name": "Travel",
        "slug": "travel",
        "term_group": 0,
        "term_taxonomy_id": 300,
        "taxonomy": "offer_cat",
        "description": "",
        "parent": 0,
        "count": 207,
        "filter": "raw",
        "object_id": 6067
      }
    ]
  }
}
```

**Comment by zaki50** [comment]
@santoshgistto You need to add custom TypeAdapter to handle array of `C` to convert it into `RealmList<C>`.

This gist might help https://gist.github.com/cmelchior/1a97377df0c49cd4fca9

**Comment by santoshgistto** [comment]
@zaki50 thank you i will check :+1:

**Comment by zaki50** [comment]
@santoshgistto We have `GSON` section in our documentation. https://realm.io/docs/java/latest/#gson

I'll close this issue.
If you have further questions, feel free to reopen this.
