### ISSUE TITLE
 Illegal State: Table is no longer valid to operate on; because of realm.close() ?

### ISSUE THREAD

**Issue by MiralDesai** [realm/realm-java#3061]
#### Goal

> Create a relationship between two objects.

#### Expected Results

> The relationship to be working.

#### Actual Results

>  One object cannot be added to another if I call `realm.close()` after I make a query. Everything works fine when I do NOT call `realm.close()`

#### Steps & Code to Reproduce

I have a CreditCard object and a Payment object. A CreditCard can have many payments. As a result in my CreditCard object I have the following:

`public RealmList<Payment> payments;`

I make an API call to get the a credit card. While I'm parsing the JSON I make a query to get all associated payments for that card like this:

```
creditCard.payments = getAllPaymentsAssociatedToCard(returnIntegerValueFromJsonIfExistsOrNull(Constants.ID, json));

private RealmList<Payment> getAllPaymentsAssociatedToCard(int creditCardId) {
        Realm realm = Realm.getDefaultInstance();
        RealmList<Payment> allPayments = new RealmList<>();
        RealmResults<Payment> results = realm.where(Payment.class)
                .equalTo("id", creditCardId)
                .findAll();
        allPayments.addAll(results.subList(0, results.size()));
realm.close();
        return allPayments;
    }
```

This throws the exception I raised in the title of this ticket. If I do NOT call `realm.close() `here, everything works fine and the relationship is set. In general calling `realm.close()` seems to cause a lot of problems for me. Shouldn't the RealmList be accessible? Or is that just a reference like RealmResults as well? Would be good to know how to solve this because it's a real blocker.

#### Version of Realm and tooling
Realm version(s): 1.0.0

Android Studio version: 2.1.2

Which Android version and device: Nexus 5 Marshmallow

**Comment by Zhuinden** [comment]
Well yes, you're not supposed to call `realm.close()` there as that will effectively close the Realm that manages the results.

**Comment by MiralDesai** [comment]
Doesn't this mean it's forever stored in memory? I was under the impression that I should close realm every time I open it.

In my activities this is easy enough with onCreate and onDestroy but in helper classes I thought I should do the same.

**Comment by Zhuinden** [comment]
You're supposed to close a realm instance when you're no longer using it, but if you've closed a Realm instance then all managed objects and results that belong to it are invalidated.

**Comment by MiralDesai** [comment]
Ok fair enough. I've got a utility method to begin a transaction, save or update the object and then commit it. So I've solved it by passing the realm instance to that method and closing it there. All good now 👍
