### ISSUE TITLE
Changing datatype of Primary key throws Exception

### ISSUE THREAD

**Issue by gowtham2809** [realm/realm-java#3068]
When changing the data type of a Realm field from String to int and FYI the field is also a Primary Key. it threw `RealmMigrationNeededException`

My Model class

```
public class Team extends RealmObject {
    @SerializedName("id")
    @PrimaryKey
    private int id; // this field was initially a String 
    @SerializedName("name")
    private String name;
    @SerializedName("description")
    private String description;
}
```

my migration

```
        if (oldVersion == 6) {
            RealmObjectSchema teamSchema = schema.get("Team");
            teamSchema.addField("temp_id", int.class)
                    .transform(new RealmObjectSchema.Function() {
                        @Override
                        public void apply(DynamicRealmObject obj) {
                            obj.setInt("temp_id", Integer.valueOf(obj.getString("id")));
                        }
                    })
                    .removeField("id")
                    .renameField("temp_id", "id")
                    .addPrimaryKey("id");
        }
```

```
Realm Version
dependencies {
        classpath 'com.android.tools.build:gradle:2.2.0-alpha4'
        classpath "io.realm:realm-gradle-plugin:1.0.1"
    }
```

**Comment by Zhuinden** [comment]
I have a wild guess that you have to remove the previous primary key in order to add a new one using `removePrimaryKey() `

**Comment by stk1m1** [comment]
Hi @gowtham2809

Thanks for the detailed report. I've built a test and it passes fine. I believe you might have missed migration version. Plus, I'd check if former `String` field does not contain `null` value as there might have been one depending on the previous version you're using.

@Zhuinden 

Actually `removeField()` make sure a PK is removed when you remove a PK field. 😜

**Comment by gowtham2809** [comment]
@stk1m1 You were right... i forgot to increment the old version... sorry
