### ISSUE TITLE
Which Field type should be used for storing videos through android.

### ISSUE THREAD

**Issue by abdulgaffarabu** [realm/realm-java#3070]
I want to store the videos which is captured from users device. so i want to know which is the right field type must be used.

**Comment by Zhuinden** [comment]
Uh. Honestly, `byte[]` resembles the raw video type, but it has a limitation of max 32 MB. 

What you CAN do is store the video in a file, and then store the filename (or file path) in Realm as a String.

**Comment by emanuelez** [comment]
Correct. Also, querying on binaries does not really make sense, making the need to store such files in a Realm file much lower

**Comment by astigsen** [comment]
> querying on binaries does not really make sense

One common use case for querying on binary fields is when they are used for storing hashes.

**Comment by diegomontoya** [comment]
@abdulgaffarabu Don't store large blobs into realm. It will cause out of memory errors. Realm is not designed/optimized to be a blob storage.

**Comment by stk1m1** [comment]
@abdulgaffarabu 

Like @emanuelez and @diegomontoya suggested, it wouldn't make the best use case if you're to store video in Realm. Instead, it would best fit the bill to store a video as a file and store its metadata such as length, date, and/or location to realm that you can search it later with ease.

**Comment by abdulgaffarabu** [comment]
ok i would try to use the images/videos location to store on realm.
And Thanks for your support.
