### ISSUE TITLE
realmList.sort()

### ISSUE THREAD

**Issue by RJFares** [realm/realm-java#3073]
**Feature Request**
sort method that works on RealmLists (the current method returns only RealmResults)

**Comment by zaki50** [comment]
`RealmList` needs enclosing `RealmObject`.
That means `RealmList` can't create its sorted copy.

If you need in-place sorting, you can use `java.util.Collections.sort(List)`or  `java.util.Collections.sort(List,Comparator)`.
Do these methods solve your problem?

**Comment by RJFares** [comment]
Yes I fixed the issue as you said by using the sort method from Collections and using my own comparator, cheers

**Comment by zaki50** [comment]
I'm glad to hear that!

**Comment by sreejithvs333** [comment]
mNotes.sort(new Comparator<Note>() {
                    @Override
                    public int compare(Note o1, Note o2) {
                        return results.indexOf(o1.getId()) - results.indexOf(o2.getId());
                    }
                });

**Comment by ravirammysore** [comment]
Hi zaki, 

I am sorting a realm list using java.util.Collections.sort(List,Comparator).

I got illegalstateexception, then i enclosed the sort operation inside a realm transaction and it worked.

Is this the correct approach to sort a real list?

Also will there be any performance issues if i sort the realm list after every item is added?

**Comment by ravirammysore** [comment]
typo - Is this the correct approach to sort a realm list?
