### ISSUE TITLE
Using Map as class name causing compilation error

### ISSUE THREAD

**Issue by dawidhyzy** [realm/realm-java#3077]
As in title:

    public class Map extends RealmObject {

    private double latitude;
    private double longitude;
    private int zoom;

    public double getLatitude() {
        return latitude;
    }

    public void setLatitude(double latitude) {
        this.latitude = latitude;
    }

    public double getLongitude() {
        return longitude;
    }

    public void setLongitude(double longitude) {
        this.longitude = longitude;
    }

    public int getZoom() {
        return zoom;
    }

    public void setZoom(int zoom) {
        this.zoom = zoom;
    }

    }

Stacktrace:
[...]/app/build/generated/source/apt/debug/io/realm/MapRealmProxy.java
Error:(23, 1) error: a type with the same simple name is already defined by the single-type-import of Map
Error:(232, 80) error: type Map does not take parameters
Error:(242, 75) error: type Map does not take parameters
Error:(251, 94) error: type Map does not take parameters

Realm version(s): 1.0.1

Android Studio version: 2.2 preview 4

Which Android version and device: all

**Comment by cmelchior** [comment]
Most likely it conflicts with the use using the Collection `Map` interface in our proxy classes. I thought we fixed those errors (at least in some other cases). That should definitely be fixed.

**Comment by dawidhyzy** [comment]
Yes, this what I get in generated proxy class.

**Comment by zaki50** [comment]
fix has been merged into master #3090

**Comment by zaki50** [comment]
The fix has been released in `1.1.0`.
