### ISSUE TITLE
Auto initialization by ContentProvider

### ISSUE THREAD

**Issue by zaki50** [realm/realm-java#3078]
Having a `ContentProvider` for Realm initialization enables us to obtain `Context` without user's explicit initialization.

https://medium.com/@andretietz/auto-initialize-your-android-library-2349daf06920

There are two options for initialization code.

1) Only setting default configuration by using the context.
2) Keep a reference of the `Context` for further construction of RealmConfiguration.
- 1) enables for users to get default Realm instance without setting default configuration. No API changes.
- 2) enables for users to create `RealmConfiguration.Builder` instance without `Context`. In public API, default constructor of `RealmConfiguration.Builder` will be added and the constructors that accept `Context` as argument will be removed (it requires to bump version to `2.0`). This provides better API compatibility to JVM version of Realm-java (it's not existing though).

There are some concerns.
- Happening the initialization of `ContentProvider` is not officially documented (it means that it's an implementation detail and has a chance to be changed.).
- Need to accept some overhead for initialization.
- No way to control the order of initializations of other `ContentProvider`s (at least, Firebase crash reporting uses this techniqe).
- App's `build.gradle` must have `applicationId` directive.
- Keeping a reference to application context is not good for InstantRun.

**Comment by anotherdev** [comment]
Would this approach works regardless whether `Application.onCreate()` or `ContentProvider.onCreate()` is called first?

https://code.google.com/p/android/issues/detail?id=8727

**Comment by jbxberg** [comment]
Google does the same thing with firebase: https://firebase.googleblog.com/2016/12/how-does-firebase-initialize-on-android.html
However, as you stated, this is undocumented behaviour and IMO shouldn't be relied upon.

**Comment by Zhuinden** [comment]
`Application.onCreate()` doesn't guarantee that `getFilesDir() != null`, so I do not know if ContentProvider would guarantee it...

**Comment by cmelchior** [comment]
This doesn't work well with multiprocess either, and there doesn't seem to be pushback on using `Realm.init(context)`, so closing this.
