### ISSUE TITLE
Issues installing

### ISSUE THREAD

**Issue by Orbyt** [realm/realm-java#3080]
**EDIT:** Something I just noticed, If I start typing "Realm" i get the option to import `RealmClass` and `RealmModule` from `io.realm.annotations`. So it seems its able to load something for Realm, but I still cant use any regular Realm functionality, as it wont resolve any Realm classes.

While trying to debug my recently submitted issue: https://github.com/realm/realm-java/issues/3079

I decided to upgrade to a more recent version of Realm. I was previously using 0.84.1, and was wanting to upgrade to the latest version. I got rid of the old gradle dependency, and added `classpath "io.realm:realm-gradle-plugin:1.0.1"` to my projects build.gradle, and then `apply plugin: 'realm-android'` to the top of my modules build.gradle.

After that, I'm still unable to use Realm, as trying to results in a "Cannot resolve symbol" error, probably because the dependency isnt being loaded correctly. What might be the issue here?

This is my projects build.gradle

Code:

```groovy
buildscript {
    repositories {
        jcenter()
        maven {
            url "https://jitpack.io"
            credentials {
            }
        }
//        maven {
//            url 'http://oss.jfrog.org/artifactory/oss-snapshot-local'
//        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.1.2'
        classpath 'me.tatarka:gradle-retrolambda:3.2.5'
        classpath 'com.github.dcendents:android-maven-gradle-plugin:1.3'
       
        classpath "io.realm:realm-gradle-plugin:1.0.1"
    }
}
```

my project includes a module (which is a library):

```groovy
apply plugin: 'com.android.library'
apply plugin: 'me.tatarka.retrolambda'
apply plugin: 'com.github.dcendents.android-maven'
apply plugin: 'realm-android'
```

But I still cant use Realm. Ideas?

**Comment by kneth** [comment]
@Orbyt Have you tried to do `./gradlew assemble --refresh-dependencies` do refresh the cache?

**Comment by Orbyt** [comment]
Tried it and it failed because it couldnt find

**Comment by zaki50** [comment]
@Orbyt `compile` tree in the output of `./gradlew :<module name of library>:dependencies` contains `io.realm:realm-android-library:1.0.1`?

**Comment by Orbyt** [comment]
Yes, it does.

**Comment by stk1m1** [comment]
@Orbyt 

Could you somehow manage to remove the following repository?

```groovy
maven {
    url "https://jitpack.io"
    credentials {
    }
}
```

I've managed compile and everything works just fine.

**Comment by Orbyt** [comment]
@stk1m1 Im not sure what you mean. 

@kneth solution seem to be the fix, after commenting out all related realm code and calling the gradle command. My other issue is still present though: https://github.com/realm/realm-java/issues/3079

**Comment by kneth** [comment]
If you are able to build with Realm, and Android Studio can autocomplete again, please close issue.
