### ISSUE TITLE
Realm findAllSortedAsync doesn't work

### ISSUE THREAD

**Issue by kokeroulis** [realm/realm-java#3081]
Hello,

I am using realm 1.0.1 with rxjava. The problem is "findAllSortedAsync" doesn't work, it returns the results mixed up. I have create an example which is reproducing the issue. 

The issue is being appeared when i enter more than 10 items.

https://gist.github.com/kokeroulis/27205e1e7c54745422d9605bd5312992

![screenshot-2016-06-28_13 38 31 148](https://cloud.githubusercontent.com/assets/470064/16412813/ebaf4320-3d36-11e6-8b30-9f692af25ffd.png)

![studio](https://cloud.githubusercontent.com/assets/470064/16412923/71dbd56c-3d37-11e6-9d53-5ddae33d8513.png)

**Comment by cmelchior** [comment]
Hi @kokeroulis 
Those results seems to be sorted correctly? Your ID is a String so it will not sort based on the number value, but the string representation where e.g. "10" is before "2" because "1" < "2".

**Comment by kokeroulis** [comment]
Oups. Yes, sorry for the distrurb.
