### ISSUE TITLE
Unable to convert geojson to euivalent RealmObject representation

### ISSUE THREAD

**Issue by preetb123** [realm/realm-java#3082]
i have below json
```json
{
  "geometry": {
    "type": "LineString",
    "coordinates": [
      [
        78.477056833,
        17.410788883
      ],
      [
        78.477115251,
        17.410976359
      ]
    ]
  }
}
```
and its POJO representation
```java
public class Geometry {
    @SerializedName("type")
    @Expose
    public String type;
    @SerializedName("coordinates")
    @Expose
    public List<List<Float>> coordinates = new ArrayList<List<Float>>();
}
```

and i want to use this object in other class that implements ```RealmModel```.

I am not able to convert ```List<List<Float>>``` to its Realm equivalent.

#### Version of Realm and tooling
Realm version(s): 1.0.1

Android Studio version: 2.1.1

Which Android version and device: Nexus 5 with Android 6.0

**Comment by Zhuinden** [comment]
You should convert `List<Float>` into something like a `LatLon` class

    public class LatLon extends RealmObject {
         private float lat;
         private float lon;

         //getter setter
    }

**Comment by preetb123** [comment]
@Zhuinden this approach doesn't work.

**Comment by preetb123** [comment]
@cmelchior can you please assist. Is it possible without using a custom TypedAdapter?  Realm looked promising initially, but i am really disappointed now.

**Comment by Zhuinden** [comment]
@preetb123 yes it does work 

Even `List<Float>` or realm list of any primitive is currently on road map, it's a bit extreme to assume that `List<List<Float>>` would work. 

You need to convert the float pair into realm object, then store the Realm objects in a list.

**Comment by preetb123** [comment]
@Zhuinden i am converting json to java object with gson. How does gson know about which one is lat and long?

**Comment by Zhuinden** [comment]
index [0] and index [1]?

**Comment by cmelchior** [comment]
Unfortunately Realm doesn't support neither List of Lists nor List of primitives yet.
As @Zhuinden said, the solution right would be to use a custom GSON deserialiser to map it into `RealmList<LatLong>` or similar. That would also provide more readable and safe code.

There is e.g. a good intro here: http://www.javacreed.com/gson-deserialiser-example/

**Comment by preetb123** [comment]
@cmelchior Finally i had to change the json. I had to write lot of boilerplate code just because of realm. I used it for a pet project. i certainly don't want to change the logic and datamodels, no reason to write deserialiser if gson can do it for me in one line. Just wanted to try realm due to lot of hype around it. But will stick to SQLite and ORMs for now.

**Comment by Zhuinden** [comment]
Well yes, you can also change the JSON. I have a mapper layer between the JSONs and the Realm objects, for example.

**Comment by preetb123** [comment]
@Zhuinden have you used this mapper layer in any of your opensourced app on github?

**Comment by Zhuinden** [comment]
My "apps" on Github are mostly experiments with Flow (and Mortar, but I consider that library obsolete), they aren't really apps. It's literally just classes that take the JSON representation and then give you back a RealmObject.
