### ISSUE TITLE
Unable to delete RealmResults from database?

### ISSUE THREAD

**Issue by MiralDesai** [realm/realm-java#3084]
#### Goal

> What do you want to achieve?
To be able to make a query, and then delete the data returned from that query. A RealmResults<User> in this case.

#### Expected Results

For there be a simple api to delete the RealmResults that I got.

#### Actual Results

users.clear() is deprecated with no information on an alternative. realm.delete() is only for RealmModel objects. I don't want to delete the User object model. I want to delete a couple of Users returned in the RealmResults query.

#### Version of Realm and tooling
Realm version(s): 1.0.0

Android Studio version: 1.2.1

Which Android version and device: Nexus 5X on 6.0.1. Api related question, not device related.

**Comment by Zhuinden** [comment]
`realmResults.deleteAllFromRealm()`?

**Comment by Zhuinden** [comment]
`RealmResults<T>` is a view to the results directly in the database that satisfy the conditions of your query. You can't arbitrarily remove elements inside a `RealmResults<T>` as far as I know. Which means the only way to delete from a RealmResults directly is by deleting the objects underneath, and even then they only update on the next looper event.

You would need to copy your Realm objects from the RealmResults to a normal ArrayList and then remove objects in that.

**Comment by MiralDesai** [comment]
realmResults.deleteAllFromRealm() seems to be fine. Are you saying it won't work?

**Comment by Zhuinden** [comment]
Oh, sorry, apparently the lack of sleep is getting to me. I thought you want to delete elements from the list as if it were a list, but NOT delete them in the Realm, but all I need is better reading comprehension.

`deleteAllFromRealm()` does exactly what you want.

**Comment by MiralDesai** [comment]
perfect, thanks.
