### ISSUE TITLE
RealmThreadPoolExecutor.java may have non-optimal default settings

### ISSUE THREAD

**Issue by diegomontoya** [realm/realm-java#3085]
1) The core size and  max pool size are both the same at 2 x cpu cores + 1. This is fine but under the assumption that no other thread pools/executors exist for the android project which is highly unlikely. I would say the value should be `Math.Max(2,  cpucores /  2 + 1)`. 

2) Each thread in android allocates a 1MB stack. So less threads is good but the current pool, if there is a lot of blocking async queries, uses up to 2 x cpu core + 1 threads and never release them since coreSize and maxPoolSize is the same. For 2016 android where the mean cores is approaching 8  which means 17 threads could lead to lots of oom issues during critical times when there is a lot of blocking async transactions.

Suggestion:

1) Reduce coreSize to 0. Allow all threads to idle killable. 1 is also fine to avoid lots of thread creations over span of app life cycle. 
2) Reduce maxPoolSize to something like = `Math.Max(2,  cpucores /  2 + 1)`.
~~3) Increase queue size since we are not allowing that many concurrent async trans/queries~~
4) Set keepAlive idle time from 0 to 60s.

These are just my suggestions. Some real testing may be needed to see what the actual better values are compared to current.

``` java
public class RealmThreadPoolExecutor extends ThreadPoolExecutor {
    // reduce context switch by using a number of thread proportionate to the number of cores
    // from AOSP https://android.googlesource.com/platform/frameworks/base/+/refs/heads/master/core/java/android/os/AsyncTask.java#182
    private static final int CORE_POOL_SIZE = Runtime.getRuntime().availableProcessors() * 2 + 1;
    private static final int QUEUE_SIZE = 100;

    private boolean isPaused;
    private ReentrantLock pauseLock = new ReentrantLock();
    private Condition unpaused = pauseLock.newCondition();

    /**
     * Creates a default RealmThreadPool that is bounded by the number of available cores.
     */
    public static RealmThreadPoolExecutor newDefaultExecutor() {
        return new RealmThreadPoolExecutor(CORE_POOL_SIZE, CORE_POOL_SIZE);
    }

    private RealmThreadPoolExecutor(int corePoolSize, int maxPoolSize) {
        super(corePoolSize, maxPoolSize,
                0L, TimeUnit.MILLISECONDS, //terminated idle thread
                new ArrayBlockingQueue<Runnable>(QUEUE_SIZE));
    }
}
```

**Comment by cmelchior** [comment]
Hi @diegomontoya 
Thanks for the suggestions and detailed explanations. I definitely won't rule out that the settings could be tweaked, especially around allowing threads to be killed. Perhaps @nhachicha can expand on the reasoning for not doing that.

Defining "better" and actually measuring this might be extremely tricky though and will require some though, but I would assume this problem has also been looked at before so perhaps we should go digging through scientific papers for inspiration. 

> Increase queue size since we are not allowing that many concurrent async trans/queries

Did you really mean increase? or decrease? The reasoning we have a limit is that reaching that probably means you are doing something very suboptimal, like running async queries or transactions inside a loop. This value was inspired by what is in AsyncTask https://github.com/android/platform_frameworks_base/blob/master/core/java/android/os/AsyncTask.java#L197-Lundefined

**Comment by diegomontoya** [comment]
@cmelchior Now that you mentioned the reason for the queueSize, then the current queueSize value should be kept since it is meant to catch/prevent very long (badly constructed) transactions which is good.
