### ISSUE TITLE
realm +  retrofit + gson

### ISSUE THREAD

**Issue by mjliu** [realm/realm-java#3086]
@beeender 
realm +  retrofit + gson, 
RealmList<RealmString> 
java.lang.IllegalStateException: Expected BEGIN_OBJECT but was STRING at line 1 column 421 path $.result.teamGames[0].startingLineup[0]

what should I do to resolve this issues

**Comment by cmelchior** [comment]
@mjliu Please post your GSON adapter + Realm model class, but the error message says that Object was expected, but a String was encountered.

E.g. `["foo", "bar"] instead of `[{name:"foo"}, {name:"bar"}]`

**Comment by mjliu** [comment]
@cmelchior 
the response is 
![image](https://cloud.githubusercontent.com/assets/8022517/16450933/83b87f6e-3e32-11e6-9875-79c963b6a55f.png)

the object is RealmString.

**Comment by cmelchior** [comment]
Yes, you need to convert those into a RealmString using a custom GSON deserializer. You can see how here: https://realm.io/docs/java/latest/#gson
