### ISSUE TITLE
Async API's: Pin version during handover

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#3091]
With Realm Core 1.2 it is now possible to pin the version used during a handover.

This means that it is safe to assume on the receiving end that the version is reachable and will massively reduce the number of race conditions and errors we need to handle in the async API's.

Especially this means that a `BadVersionException` should not happen and we should cleanup the code appropriately.

**Comment by cmelchior** [comment]
@beeender Do you know if this is fixed by #3834 as well? (moving into progress, just so we don't forget)

**Comment by beeender** [comment]
yes, this is fixed by #3834.

**Comment by beeender** [comment]
#3834 is merged to master. will be fixed in `v2.4.0`.
