### ISSUE TITLE
Duplicate files copied in APK error

### ISSUE THREAD

**Issue by jpaseneta** [realm/realm-java#3092]
I recently upgraded a realm version as i was using 0.82.1 yesterday and used the recent 1.0.1 today and followed the aar dependency way. I was getting the following error.

> Error:Execution failed for task ':app:transformNative_libsWithMergeJniLibsForDebug'.
> > com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK lib/armeabi/librealm-jni.so
>   	File1: /Users/SmartwaveDev/.gradle/caches/modules-2/files-2.1/io.realm/realm-android/0.84.1/b86074e6240f0f876701810a047b0261f7bd060e/realm-android-0.84.1.jar
>   	File2: /Users/SmartwaveDev/Desktop/Work/Genie/app/build/intermediates/exploded-aar/io.realm/realm-android-library/1.0.1/jni

my app.gradle file contains:

apply plugin: 'realm-android'

and my project.gradle file has:
dependencies{
   classpath "io.realm:realm-gradle-plugin:1.0.1"
}

I already tried deleting the libraries in gradle cache, but apparently it is still downloading 0.84..
#### Version of Realm and tooling
Realm version(s): latest(1.0.1)

Android Studio version: 2.1

Which Android version and device: Android 2.1.1

**Comment by jpaseneta** [comment]
found the problem with this:

apparently i'm using https://github.com/thorbenprimke/realm-recyclerview 's and it already references a realm version..

**Comment by reshadf** [comment]
Have you found a solution for this problem @jpaseneta cause I am facing it too

**Comment by jpaseneta** [comment]
@reshadf double check your dependencies in your gradle file.

in my case, a 3pp library references a realm version different from using the official one.
check whether which version you want to use.

**Comment by CallumCoombes** [comment]
If I still want to use thorbenpimke's library, how do I break the reference to the other version of Realm from this library?

**Comment by Zhuinden** [comment]
@CallumCoombes use a newer version of it, such as  `compile 'com.github.thorbenprimke:realm-recyclerview:0.9.25'` which is made for Realm 2.2.1
