### ISSUE TITLE
Align RealmObject.isValid() with Cocoa/.NET

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#3101]
See https://github.com/realm/realm-dotnet/pull/668/files/cf8ba4f0d920f7ca5044a4a1e242ae134f84be28#r69203861

Right now we return `false` for unmanaged objects, both Cocoa and .NET return `true` in the same case.
This has the advantage that you can use `isValid()` to determine if you can use the data from the RealmObject.

Java has some extra considerations though as we also have to consider the loaded state. Right now we return `false` if the object isn't loaded yet. That makes sense to me I think.

In any case, any change to these semantics are a breaking change, thus should only be part of 2.0

**Comment by cmelchior** [comment]
|                  | isValid()           | isLoaded() | obj instanceof RealmObjectProxy (or isManaged() ?) |
| ---------------- | ------------------- | ---------- | ------------------------------------------------|
| Unmanaged        | false (true)    | true       | false                                           |
| Managed/Unloaded | false               | false      | true                                            |
| Managed/Loaded   | true                | true       | true                                            |
| Managed/Deleted   | false               | true       | true                                            |


**Current state**
- Hard to differentiate between `unmanaged` and `deleted`.

**When we change isValid() -> true for unmanaged objects**
- Hard to tell the difference between `unmanaged` and `managed objects`

**Alternative solution**
- Introduce `isManaged()`. .NET already has this method

I kinda like the 3rd + It will put us line with .NET. Thoughts @realm/java ?

**Comment by beeender** [comment]
:+1: fro the `isManaged()`

**Comment by stk1m1** [comment]
`isManaged()` == 👍
