### ISSUE TITLE
insertOrUpdate(T t) fails on RealmList<Persons> field

### ISSUE THREAD

**Issue by Zhuinden** [realm/realm-java#3105]
#### Goal

> What do you want to achieve?

Save a `RentalProgram` object that contains a `RealmList<Persons>` object

#### Expected Results

It should work just like when I used `copyToRealmOrUpdate()`, which works

#### Actual Results

Using `insertOrUpdate()`, the `rentalProgram.getCast()` is empty!

#### Steps & Code to Reproduce

> Describe your current debugging efforts.

Frickin' ProGuard eats my debug efforts, but it's quite clear that the `cast` list is empty if I use `insertOrUpdate()`, while it works as intended with `copyToRealmOrUpdate()`.

#### Code Sample

```java

public class RentalProgram extends RealmObject {
    @PrimaryKey
    private long id;
    private RealmList<RentalProgramVersion> versions;
    private String title;
    private String href;
    private String imageSrc;
    private String baseInfoText;
    private String originalTitle;
    private String trailerUrl;
    private String description;
    private String ageRating;
    private RealmList<Persons> cast;
    private String categoryHref;
    private String releaseYear;
    // getters setters
}

public class RentalProgramVersion extends RealmObject {
    @PrimaryKey
    private long id;
    private String releaseYear;
    private int ageRating;
    private String title;
    private long duration;
    private long price;
    private String vodType;
    private String packageName;
    private long packageExternalId;
    //getters setters
}

public class Persons
        extends RealmObject {
    @PrimaryKey
    private long id;
    private String role;
    private RealmList<Person> persons;
    //getters setters
}

public class Person
        extends RealmObject {
    @PrimaryKey
    private long id;
    private String name;
    //getters setters
}
```

and the code where persistence happens is

``` java
        RealmList<Persons> castList = new RealmList<>();
        if(rentalProgramAdditionalXML.getCast() != null && rentalProgramAdditionalXML.getCast()
                .getPersons() != null) {
            for(PersonsXML personsXML : rentalProgramAdditionalXML.getCast().getPersons()) {
                castList.add(personsMapper.toRealmObject(realm, personsXML, null));
            }
        }
        realm.beginTransaction();
        castList = personsRepository.persistOrUpdate(realm, castList);
        rentalProgram.setCast(castList);
        rentalProgram.setOriginalTitle(RealmUtils.nullToEmpty(rentalProgramAdditionalXML.getOriginalTitle()));
        rentalProgram.setTrailerUrl(RealmUtils.nullToEmpty(rentalProgramAdditionalXML.getTrailerUrl()));
        rentalProgram.setDescription(RealmUtils.nullToEmpty(rentalProgramAdditionalXML.getDescription()));
        rentalProgramRepository.saveOrUpdate(realm, rentalProgram);
        realm.commitTransaction();
```

where

``` java
    @Override
    public RealmList<T> persistOrUpdate(Realm realm, RealmList<T> list) {
        RealmList<T> realmList = new RealmList<>();
        for(T t : realm.copyToRealmOrUpdate(list)) {
            realmList.add(t);
        }
        return realmList;
    }

    @Override
    public void saveOrUpdate(Realm realm, T t) {
        realm.insertOrUpdate(t);
    }

    @Override
    public void saveOrUpdate(Realm realm, RealmList<T> list) {
        if(!list.isEmpty()) {
            realm.insertOrUpdate(list);
        }
    }
```

When I use `rentalProgramRepository.persistOrUpdate(realm, rentalProgram);` (copy to realm), the Cast list works properly, but when I use `rentalProgramRepository.saveOrUpdate(realm, rentalProgram);` (insert to realm), the Cast list is empty.

    rentalProgram = rentalProgramRepository.query(realmHolder.getRealm())
                                   .equalTo(RentalProgram.Fields.ID.getField(), programId).findFirst();
    for(int j = 0; j < rentalProgram.getCast().size(); j++) { //getCast() is empty with insert, and filled with copy
        Persons personGroup = rentalProgram.getCast().get(j);

I'll probably have to send code over to reproduce it.

Note: It might be relevant that my realm configuration is this:

     .modules(new SchemaRecordings(), new SchemaRental(), new SchemaTApps(), new SchemaTVPrograms())

and Persons is only in one of them:

``` java
@RealmModule(classes = {RentalCategory.class,
        RentalProgram.class,
        RentalProgramCategory.class,
        RentalProgramVersion.class,
        RentalSearchProgram.class})
public class SchemaRental {
}

@RealmModule(classes = {
        Person.class, Persons.class, Picture.class, PictureSizesAndUrl.class, ProgramInfo.class, ProgramInfoSchedule.class, ProgramNotification.class,
        Channel.class, Schedule.class, TVGroup.class
})
public class SchemaTVPrograms {
}
```

#### Version of Realm and tooling
Realm version(s): 1.1.0

Android Studio version: 2.1.1 (irrelevant)

Which Android version and device: 6.0.2, Nexus 5X

**Comment by nhachicha** [comment]
Hi @Zhuinden 
Thanks for the detailed report.

I didn't look deeper to it but do you have the same issue if you build completely your object graph `RentalProgram` as 1 object (outside of the commit transaction) then call `insertOrUpdate(rentalProgram)` ? this method will use the same cache for the entire insert/update operations

**Comment by Zhuinden** [comment]
I must also note before I waltz into further investigation that here, `rentalProgram` is a managed object that I obtained from the Realm.

I seem to have forgotten adding that fact.

**Comment by Zhuinden** [comment]
@nhachicha because `RentalProgram` is managed, I cannot build it outside the transaction, because it says that every element in `cast` list must be managed (`isValid()` must be true), so I must persist the `RealmList<Persons>` first and make it managed.

**Comment by nhachicha** [comment]
I think the following lines in your proxy `RentalProgramRealmProxy` are the cause 
```java
        long castNativeLinkViewPtr = Table.nativeGetLinkView(tableNativePtr, columnInfo.castIndex, rowIndex);
        LinkView.nativeClear(castNativeLinkViewPtr);
        RealmList<Persons> castList = ((RentalProgramRealmProxyInterface) object).realmGet$cast();
```
after the `nativeClear` the `castList` LinkView is empty (since they use the same pointer) I guess the fix should be to check if the RealmList is already managed then don't update it. This lead to me to your Use Case. Why are you calling `inserOrUpdate` (`rentalProgramRepository.saveOrUpdate(realm, rentalProgram);`)? 
 since you're already inside a transaction that updated the RealmList? (`rentalProgram.setCast(castList);` is setting a managed RealmList).
Removing `rentalProgramRepository.saveOrUpdate(realm, rentalProgram);` is a temporary fix in your case.

Good catch anyway 👍

**Comment by Zhuinden** [comment]
@nhachicha 

> Why are you calling inserOrUpdate (rentalProgramRepository.saveOrUpdate(realm, rentalProgram);)?  since you're already inside a transaction that updated the RealmList? 

This code is kinda legacy because I wrote it back when I didn't have a complete understanding of Realm (which is why the `findOne` is outside of the transaction, for example - so I figured I'd have to map the unmanaged object into the Realm), and I just changed every call to `copyToRealmOrUpdate()` to `insertOrUpdate()` to see what would happen, that's pretty much the gist of it.

Anyhow, I think it's quite an issue that if you insert an object twice, its lists get erased even when they're set :P

**Comment by beeender** [comment]
#3306 Fixed this.
