### ISSUE TITLE
How I can refresh the Realm default instance?

### ISSUE THREAD

**Issue by KikoPalomares** [realm/realm-java#3107]
How I can refresh the Realm default instance?
I do a write in the database in a thread. 
And if I ask data from another thread are not data.

**Comment by cmelchior** [comment]
Hi @KikoPalomares 
Please show some code for what you tried already. It is hard to tell with the current information. Alternatively look at our threading example here: https://github.com/realm/realm-java/tree/master/examples/threadExample

**Comment by KikoPalomares** [comment]
In a thread I do this:

```
Realm.getDefaultInstance().beginTransaction();
Realm.getDefaultInstance().copyToRealmOrUpdate(object);
Realm.getDefaultInstance().CommitTransaction();
```

And then another do this one:

`E Realm.getDefaultInstance object = () where (clazz).equalTo(field, identifier).findFirst ();`

If I do this in the same thread work; the problem is when I do it in another.

**Comment by cmelchior** [comment]
That should work. How does the other thread know that it has to start querying for data?

**Comment by kneth** [comment]
By doing `Realm.getDefaultInstance().beginTransaction()` you are not able to close the Realm instance properly. You should do

    Realm realm = Realm.getDefaultInstance();
    realm.beginTransaction();
    // ...
    realm.commitTransaction();
    realm.close();

**Comment by KikoPalomares** [comment]
The other thread does not need to know. It is code that is always executed later.
If I close the app and open again it works. (Because it is re-instantiates Realm).

@kneth yes, I've tried closing. But it does not work.

```
Realm.getDefaultInstance().beginTransaction();
Realm.getDefaultInstance().copyToRealmOrUpdate(object);
Realm.getDefaultInstance().commitTransaction();
Realm.getDefaultInstance().close();
```

**Comment by cmelchior** [comment]
If it is two threads you do not know which one runs later unless you synchronise their behaviour somehow. If it works after you reopen the app it is an indication that they do not run in the order you think

**Comment by KikoPalomares** [comment]
I change:

```
Realm.getDefaultInstance().beginTransaction();
Realm.getDefaultInstance().copyToRealmOrUpdate(object);
Realm.getDefaultInstance().commitTransaction();
Realm.getDefaultInstance().close();
```

to:

```
Realm realm = Realm.getDefaultInstance();
realm.beginTransaction();
realmObject.deleteFromRealm();
realm.commitTransaction();
realm.close();
```
But the result is the same. It does not work.

@cmelchior the code is executed in order; that is not the problem, I assure you that.

**Comment by cmelchior** [comment]
Please create a sample project that showcase the problem then, because we have a lot of unit tests and examples where this work, so unless there is a way to reproduce it I don't think we can tell you what is wrong.

**Comment by KikoPalomares** [comment]
The code is too long to extract an example. The idea is this:

I have a service android.
And on the other hand I have a IntentService where download a file. When the download is complete. I save the object realm.

After the main service attempt to query that object; but it is not updated. If I do that query right after saving it, in the IntentService. Yes, it's updated.

I read that Realm does not read the data directly from the file. If not that saves them in the instance; for faster access. If you run two thread realm, the instances are different.
In my main service, I have executed realm before the download; but always with the close (). After downloading and saving the data; the instance of the main service still has no new data. until you restart the App.

**Comment by Zhuinden** [comment]
A service by default runs on the UI thread, an IntentService runs on the background thread.

If you download something in the IntentService, then the main service needs to have a `RealmChangeListener` for the table into which you save the object.

**Comment by stk1m1** [comment]
@KikoPalomares 

If you could help us with a sample project to reproduce your issue at help@realm.io, we can support you in an accelerated manner. We will look forward. Thanks!

**Comment by KikoPalomares** [comment]
@Zhuinden RealmChangeListener have a problem. It is that comes instantly to save data. And not at the time when I need to access; It is much later. And I not always need to access the newly saved data.

@stk1m1  I made an example of simplified project where this happens. I leave it here:
[Download example](https://dl.dropboxusercontent.com/u/43431345/RealmBug.rar)

**Comment by kneth** [comment]
@KikoPalomares I have rewritten all `Realm.getDefaultInstance().where()` etc. to `Realm realm = Realm.getDefaultInstance(); realm.where()...` etc. That is, getting an instance and use that instead of getting new instance for every operation - and of course remembering to close the instance (`realm.close`). 

By clicking "Start Service" the log is:

```
07-04 10:37:06.183 11969-11969/io.realm.realmbug I/RealmBug: Service started
07-04 10:37:06.216 11969-12232/io.realm.realmbug I/RealmBug: Timer :: Version :: null
07-04 10:37:07.100 11969-11969/io.realm.realmbug I/RealmBug: Downloading :: 8
07-04 10:37:07.100 11969-11969/io.realm.realmbug I/RealmBug: Downloading :: 21
07-04 10:37:07.100 11969-11969/io.realm.realmbug I/RealmBug: Downloading :: 26
07-04 10:37:07.106 11969-11969/io.realm.realmbug I/RealmBug: Downloading :: 39
07-04 10:37:07.106 11969-11969/io.realm.realmbug I/RealmBug: Downloading :: 43
07-04 10:37:07.199 11969-11969/io.realm.realmbug I/RealmBug: Downloading :: 56
07-04 10:37:07.200 11969-11969/io.realm.realmbug I/RealmBug: Downloading :: 61
07-04 10:37:07.201 11969-11969/io.realm.realmbug I/RealmBug: Downloading :: 74
07-04 10:37:07.201 11969-11969/io.realm.realmbug I/RealmBug: Downloading :: 78
07-04 10:37:07.201 11969-11969/io.realm.realmbug I/RealmBug: Downloading :: 92
07-04 10:37:07.204 11969-11969/io.realm.realmbug I/RealmBug: Downloading :: 96
07-04 10:37:07.205 11969-11969/io.realm.realmbug I/RealmBug: Downloading :: 100
07-04 10:37:07.220 11969-11969/io.realm.realmbug I/RealmBug: Receiver :: Version :: 4
07-04 10:37:08.217 11969-12232/io.realm.realmbug I/RealmBug: Timer :: Version :: 4
07-04 10:37:10.215 11969-12232/io.realm.realmbug I/RealmBug: Timer :: Version :: 4
07-04 10:37:12.216 11969-12232/io.realm.realmbug I/RealmBug: Timer :: Version :: 4
07-04 10:37:14.214 11969-12232/io.realm.realmbug I/RealmBug: Timer :: Version :: 4
07-04 10:37:15.472 11969-11969/io.realm.realmbug I/RealmBug: Service onDestroy
```

**Comment by KikoPalomares** [comment]
It works!
I put the realm.close() after saving objects. 
But not to pick them up.

Thank you all!

**Comment by kneth** [comment]
Great to hear. Not closing Realm instances might lead to unpleasant surprises: https://realm.io/docs/java/latest/#large-realm-file-size

**Comment by lovearthhome** [comment]
@KikoPalomares Hi, how did you solve the problem? I m having the same problem. But I cant fix it by placing a realm.close() after commit transaciton!!

**Comment by Zhuinden** [comment]
@lovearthhome you are not closing the Realm instance in case of failure. Put it in try-finally. 

Also, you SHOULD see the results being updated when your RealmChangeListeners run.

**Comment by kneth** [comment]
@lovearthhome When `commitTransaction()` returns, the object is stored on disk and is ready for other threads. Of course, (write) transactions are blocking so `beginTransaction()` will wait until another transaction commits (or cancels).

**Comment by leon-softwarewot** [comment]
@kneth Is it possible to have `close()` when directly accessing `Realm.getDefaultInstance()`? I put in my models all queries such as `findAll()` where it would execute `return Realm.getDefaultInstance().where(Sample.class).findAll();`, would it be better if we could add the `close()` method at the end of the chain?

**Comment by leonapse** [comment]
@kneth Is it possible to have `close()` when directly accessing `Realm.getDefaultInstance()`? I put in my models all queries such as `findAll()` where it would execute `return Realm.getDefaultInstance().where(Sample.class).findAll();`, wouldn't it be better if we could add the `close()` method at the end of the chain?
