### ISSUE TITLE
Provide a method which transforms a realm object to a "real" object

### ISSUE THREAD

**Issue by leisim** [realm/realm-java#3108]
#### Goal

I want to pass Objects stored in Realm between threads. Or debug them with the Android Studio Debugger etc.

#### Expected Results

I propose a method like `RealmObject.disconnectFromRealm()` which returns a real object with filled properties which can be passed between threads but cannot be used with realm anymore (e.g. in transactions).

Even cooler would be a second method (`RealmObject.reconnectToRealm(Realm)`) which can "reconnect" the object with the realm instance of the new thread.

Is something like that possible?

**Comment by Zhuinden** [comment]
`copyFromRealm()`.

**Comment by leisim** [comment]
Oh thx xD I didn't see this one...

**Comment by cmelchior** [comment]
The methods are called `copyFromRealm()` and `copyToRealm()` respectively.
