### ISSUE TITLE
No annotations package with 1.1.0

### ISSUE THREAD

**Issue by Coletz** [realm/realm-java#3111]
Using realm <= 1.0.1 I can import io.realm.annotations.PrimaryKey
With realm 1.1.0 the package io.realm.annotations doesn't exist.
On your site latest version is 1.1.0, while on this github repo the latest version is 1.1.1. Maybe you've already solved this problem but changes aren't pushed yet? Thanks!

**Comment by stk1m1** [comment]
@Coletz 

Hi, Thanks for the report. I've tried to reproduce your issue but was not able to. Could you test with a fresh new project to see if this issue persists?

**Comment by Coletz** [comment]
I was probably having some issue with gradle, updating build tools seems to have fixed the problem. Thanks anyway
