### ISSUE TITLE
download for java not working

### ISSUE THREAD

**Issue by gbinder** [realm/realm-java#3113]
in java section, click on "download realm for android"

get the following:
404 Not Found

Code: NoSuchKey
Message: The specified key does not exist.
Key: downloads/java/realm-java-1.1.0.zip
RequestId: E6F4704345C94C49
HostId: /cBXlNMaRrpjPclBXEDFCuKXT/W7qCg2vdsKSle7xMPmT4HjxzS3ju+44JuWBiBc
An Error Occurred While Attempting to Retrieve a Custom Error Document

Code: NoSuchKey
Message: The specified key does not exist.
Key: 404.html

**Comment by stk1m1** [comment]
@gbinder 
Thanks for letting us know. The issue is fixed.
