### ISSUE TITLE
RealmList size is error.

### ISSUE THREAD

**Issue by mjliu** [realm/realm-java#3117]
@beeender 
the response is : size is twenty.
![image](https://cloud.githubusercontent.com/assets/8022517/16552491/11a5346a-41f4-11e6-8d84-b641fa2ee065.png)

but the received result is : size is three.
![image](https://cloud.githubusercontent.com/assets/8022517/16552500/2660d8fa-41f4-11e6-8b6b-c7e38872d9fc.png)

what should I do.

**Comment by Zhuinden** [comment]
If you add a `RealmString` (primitive wrapper for list)` for each element in `startingLineup` response including ones where you set the `value` of RealmString to `null`, then it should work.
