### ISSUE TITLE
RealmObjectSchema.setClassName() should amend pkTable entry

### ISSUE THREAD

**Issue by stk1m1** [realm/realm-java#3118]
#### Goal

We have covered cases where `@PrimaryKey` field is renamed or `RealmSchema.rename()` is involved.
When [`RealmObjectSchema.setClassName()`](https://github.com/realm/realm-java/blob/master/realm/realm-library/src/main/java/io/realm/RealmObjectSchema.java#L108) is called, however, it has potential to lose track of `@PrimaryKey` of a `Table`. This is addressed by @beeender and should be fixed.

#### Expected Results

`RealmObjectSchema.setClassName()` is called, `pkTable` should be adjusted accordingly.

#### Actual Results

`pkTable` is not adjusted as of now [3ff5741 (July 4th, 2016)](https://github.com/realm/realm-java/commit/3ff5741582e8bb550f66b1b4adcc925027c0dce6).

#### Steps & Code to Reproduce

N/A

#### Version of Realm and tooling
Realm version(s): 1.1.0
Android Studio version: N/A
Which Android version and device: N/A

**Comment by cmelchior** [comment]
Fixed by #3149
