### ISSUE TITLE
java.lang.ClassNotFoundException: Didn't find class "io.realm.Realm"

### ISSUE THREAD

**Issue by Daemon-Devarshi** [realm/realm-java#3120]
In my android app I am getting below error:

`java.lang.ClassNotFoundException: Didn't find class "io.realm.Realm" on path: DexPathList[[dex file "/data/data/com.example.devarshik.recyclersample/files/instant-run/dex/slice-support-annotations-23.4.0_e897d6018c0c7bba65d1902cb4c8da3548f8443f-classes.dex", dex file "/data/data/com.example.devarshik.recyclersample/files/instant-run/dex/slice-slice_9-classes.dex", dex file "/data/data/com.example.devarshik.recyclersample/files/instant-run/dex/slice-slice_8-classes.dex", dex file "/data/data/com.example.devarshik.recyclersample/files/instant-run/dex/slice-slice_7-classes.dex", dex file "/data/data/com.example.devarshik.recyclersample/files/instant-run/dex/slice-slice_6-classes.dex", dex file "/data/data/com.example.devarshik.recyclersample/files/instant-run/dex/slice-slice_5-classes.dex", dex file "/data/data/com.example.devarshik.recyclersample/files/instant-run/dex/slice-slice_4-classes.dex", dex file "/data/data/com.example.devarshik.recyclersample/files/instant-run/dex/slice-slice_3-classes.dex", dex file "/data/data/com.example.devarshik.recyclersample/files/instant-run/dex/slice-slice_2-classes.dex", dex file "/data/data/com.example.devarshik.recyclersample/files/instant-run/dex/slice-slice_1-classes.dex", dex file "/data/data/com.example.devarshik.recyclersample/files/instant-run/dex/slice-slice_0-classes.dex", dex file "/data/data/com.example.devarshik.recyclersample/files/instant-run/dex/slice-internal_impl-23.4.0_520771e0e0fd4950aa47c03eaa21989ceb84fe1d-classes.dex", dex file "/data/data/com.example.devarshik.recyclersample/files/instant-run/dex/slice-com.android.support-support-vector-drawable-23.4.0_b885b26cdcbbd4207ec83897d31b9cda1f7c4ccc-classes.dex", dex file "/data/data/com.example.devarshik.recyclersample/files/instant-run/dex/slice-com.android.support-support-v4-23.4.0_4fd64ed4c4e9a08dc696e34b833cac501a4bab06-classes.dex", dex file "/data/data/com.example.devarshik.recyclersample/files/instant-run/dex/slice-com.android.support-appcompat-v7-23.4.0_0f518cf4188dc4b90771dc05954db26d6ba48de5-classes.dex", dex file "/data/data/com.example.devarshik.recyclersample/files/instant-run/dex/slice-com.android.support-animated-vector-drawable-23.4.0_017cda62115464dfbdf91a46da369e9b3feb0b76-classes.dex"],nativeLibraryDirectories=[/vendor/lib, /system/lib, /vendor/lib, /system/lib]]`

Am clueless on that, any ideas?

My android studio version is - 2.1.1

**Comment by Zhuinden** [comment]
You should disable Instant Run.

**Comment by kneth** [comment]
Hopefully Google will soon get Instant Runs to work
