### ISSUE TITLE
last Object comes to deleted position when reload Results after deleted data

### ISSUE THREAD

**Issue by D3vel0pper** [realm/realm-java#3121]
#### Goal
sort order corrective after deleted Realm Object

#### Expected Results
the order of RealmResults before deleting
[0]=data1,[1]=data2,[2]=data3

after deleted data1
[0]=data2,[1]=data3

#### Actual Results
before deleting
[0]=data1,[1]=data2,[2]=data3

after deleted data1
[0]=data3,[1]=data2

#### Version of Realm and tooling
Realm version(s): 1.0.1

Android Studio version: 2.1

Which Android version and device: 6.0.1

**Comment by beeender** [comment]
Hello! can you please share more details with us?
1. How did you build the `RealmResults`? What is the sort condition?
2. How did you delete the element from results? 

If you can share a simple project with us to reproduce the problem, that will be perfect. Thanks!

**Comment by zaki50** [comment]
The order of elements in `RealmResults` is guaranteed only when the sort order is specified.

How did you create the `RealmResults`?

**Comment by Zhuinden** [comment]
If you use `sort()` then this is expected, if you use `findAllSorted()` then it is not.

**Comment by kneth** [comment]
`deleteFromRealm()` is optimized, and order will generally not be perserved. I agree that the documentation could be more clear.

**Comment by D3vel0pper** [comment]
sorry I didn't tell you about detail.
I just read it now and thanks to give me the solutions and comments.
I solved this problem by using sort() 
thank u all.
