### ISSUE TITLE
Finding a list of objects sorted by a property of another object

### ISSUE THREAD

**Issue by hay12396** [realm/realm-java#3129]
Hello,

So i'm having the following properties:
Item
{
Id,
Price
}

Favorite
{
Id,
ItemId,
FavDate
}

a user can favorite an item, and it's profile is suppost to show the items that he favorite sorted by the favorite time (FavDate Property).

I start by searching for the items that he favorite sorting by the FavDate property, but than when im requerying to get the items themself (using the Favorite.ItemId property), i'm receiving the items in an incorrect order(in the order that they are displayed in the database and not in the order that they were favorite by that user)

Is there any solution for such a problem?
Maybe a Join like operation? or some walkaround ?

**Comment by Zhuinden** [comment]
You should have something like

    Item {
        id,
        price,
        isFavorited,
        favDate
    }

Then your solution would be easy

**Comment by hay12396** [comment]
I can't do that because An item is not related to one user, alot of users could of favorite the same item, and you can see that on their profiles.

**Comment by kneth** [comment]
You can use relationships to model it: https://realm.io/docs/java/latest/#relationships

**Comment by hay12396** [comment]
Hey kneth,

If i understand correctly, i need to add a relation between an Favorite and an Item.
So the Favorite class will now hold the item it is related to instead of it's id.

Once i do this, how can i extract only the Items as a list?
I need to get RealmResults<Item> which will be in the same order of the RealmResults<Favorite> that i have.

**Comment by kneth** [comment]
You can begin with your `Item`:

    class Item extends RealmObject {
        long id;
        double price;
    }

Since a favorite is an item, you can have:

    class Favortite extends RealmObject {
        Item item;
        Date favDate;
    }

and users can have favorite items (and items):

    class User extends RealmObject {
        RealmList<Item> items;
        RealmList<Favorite> favorites;
    }

Let's say you have a `user`. If you need to get the favorite items in sorted order, you can do:

    RealmResults<Favorite> sortedFavortites = user.favorites.sort("favDate");
    for (Favorite favorite : sortedFavorites) {
        Log.d("APP", favorite.item.price);
    }

**Comment by hay12396** [comment]
My problem is that i am using realmrecyclerview and adapter and that i need to give those items as realmresults, how would you convert all of the favorite.item to realmresults?

**Comment by kneth** [comment]
Can't you use the `sortedFavorite` object and do `sortedFavorite.get(i).item` when you need the ith item?

**Comment by hay12396** [comment]
No because i don't fetch all of the items at once, and i do fetch all of the votes at once.
So what happen is that in the adapter i will try to show an item which is not fetched yet and it will crash.

**Comment by beeender** [comment]
You can have one more field to indicate if the item is fetched:
```
class Item extends RealmObject {
    long id;
    double price;
    boolean fetched;
}
```

And filter out them by `equalTo(fetched, true)`
