### ISSUE TITLE
"This Realm instance has already been closed, making it unusable." - Even when copying object?

### ISSUE THREAD

**Issue by MiralDesai** [realm/realm-java#3130]
#### Goal

> What do you want to achieve?
To be able to access the data in an object after calling realm.close.

#### Expected Results

> To get an object out of the Realm data store and use it's data after closing realm, by copying the object first.

#### Actual Results

>  RuntimeException: This Realm instance has already been closed, making it unusable.

#### Steps & Code to Reproduce

Code I am using:

```
Realm realm = Realm.getDefaultInstance();
        User user = realm.where(User.class)
                .equalTo(Constants.ID, 1)
                .findFirst();
        User copy = realm.copyFromRealm(user);
        realm.close();
        return copy;
```

I am currently under the impression that copying the object first gives me the ability to use that object freely, instead of it being just a reference to the realm backing store. I've got various helper methods to make queries to Realm for me, where I open a realm then close it in one go then return the data. Is this incorrect? By copying the object shouldn't there be no issue?

Interesting to hear your thoughts on the subject and what the correct procedure should be. I'm assuming I need to keep the realm open but that currently doesn't make sense to me.

#### Version of Realm and tooling
Realm version(s): 1.1.0

Android Studio version: 2.1.2

Which Android version and device: Nexus 5 Marshmallow.

**Comment by Zhuinden** [comment]
Are you sure this is the object that throws this error? This shouldn't happen, you're indeed correct.

What field of `User` are you accessing?

**Comment by MiralDesai** [comment]
user.id. Not using accessors if that means anything.

Here's the full thing:

`User user = RealmQueries.getMyUser();`

public static User getMeUser(int userId) {
        Realm realm = Realm.getDefaultInstance();
        User user = realm.where(User.class)
                .equalTo(Constants.ID userId)
                .findFirst();
        realm.close();
        return user;
    }

The crash actually happens on the line after, where I try to use the data.

So `int user id = user.id;` is where the crash happens.

**Comment by kneth** [comment]
I can't reproduce it using https://github.com/realm/realm-java/pull/3132

**Comment by MiralDesai** [comment]
Very confused. I am getting the crash consistently now. In a different place, but the same method above is being called, to get a user object.

Inside an `AsyncTask doInBackground` I call this method:

```
private void lookupBalance() {
            User user = RealmQueries.getMeObject();
            calculator.userCredit = new BigDecimal(user.balance);
            myImageUrl = user.imageUrl;
        }
```

```
The app crashes on the 2nd line in that method. new BigDecimal blah blah with the following:

java.lang.RuntimeException: An error occurred while executing doInBackground()
                                                                 at android.os.AsyncTask$3.done(AsyncTask.java:309)
                                                                 at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
                                                                 at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
                                                                 at java.util.concurrent.FutureTask.run(FutureTask.java:242)
                                                                 at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
                                                                 at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
                                                                 at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
                                                                 at java.lang.Thread.run(Thread.java:818)
                                                              Caused by: java.lang.IllegalStateException: This Realm instance has already been closed, making it unusable.

```

**Comment by Zhuinden** [comment]
@MiralDesai your actual helper method doesn't seem to have `user.copyFromRealm()` before closing the Realm.

**Comment by kneth** [comment]
@MiralDesai Please tell us what you find (especially if the issue persists so we can assist you).

**Comment by MiralDesai** [comment]
Yeah in this second case it was resolved by using copyFromRealm();

In my opening post I was already copying the object and it was causing this issue, as I said though, I fixed something semi-related in another activity and now it works, so could just be that. Will close this issue, and I'm not having any problems anymore.
