### ISSUE TITLE
Android studio 2.1.2 Error

### ISSUE THREAD

**Issue by DineshkumarDevarasu** [realm/realm-java#3134]
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException: org.gradle.process.internal.ExecException: Process 'command 'C:\Program Files\Java\jdk1.8.0_92\bin\java.exe'' finished with non-zero exit value 2

**Comment by Zhuinden** [comment]
Please share your `build.gradle` file, or at least your dependencies

**Comment by stk1m1** [comment]
Hi @DineshkumarDevarasu,

Could you please provide more details to get a hint of where the issue is coming from? If you can fill up [the issue template](https://github.com/realm/realm-java/blob/master/CONTRIBUTING.md#filing-issues) we can support you better and faster. Thanks!

**Comment by beeender** [comment]
Close due to no response

**Comment by Zhuinden** [comment]
Honestly, he probably exceeded the 65536 method limit.
