### ISSUE TITLE
java.lang.IllegalStateException: when use findAll().asObservable() with subscribeOn(Schedulers.io()). Similar to #2607

### ISSUE THREAD

**Issue by ar-g** [realm/realm-java#3147]
I'm getting this exception( Caused by: java.lang.IllegalStateException: You can't register a listener from a non-Looper thread) when executing this code
```java
return Observable.defer(() -> Observable.just(Realm.getInstance(realmConfiguration)))
        .flatMap(realm -> realm.where(clazz)
            .findAll()
            .asObservable()
            .filter(RealmResults::isLoaded)
            .map(sort)
            .map(realm::copyFromRealm)
            .doOnUnsubscribe(realm::close)
        );
```
My use case is to fetch data from Realm and then make NetworkRequest all this with `subscribeOn(Schedulers.io())`. What is the problem here?

**Comment by Zhuinden** [comment]
I'm not really sure about Rx, but shouldn't your code be the following instead?

``` java
return Observable.defer(() -> Observable.just(Realm.getInstance(realmConfiguration)))
        .flatMap(realm -> realm.where(clazz).findAll().asObservable())
        .filter(RealmResults::isLoaded)
        .map(sort)
        .map(realm::copyFromRealm)
        .doOnUnsubscribe(realm::close);
```

**Comment by cmelchior** [comment]
None of the above code should register a change listener. Are you sure you are not calling `findAllAsync()` or `findFirstAsync()` instead?

**Comment by ar-g** [comment]
If I remove `subscribeOn(Schedulers.io())` everything works fine. Also, I noticed if I replace 
```
realm.where(clazz)
            .findAll()
            .asObservable()
```
with 
```
Observable.just(realm.where(clazz).findAll())
```
it works  fine, but I won't get updates then

**Comment by Zhuinden** [comment]
In that case the error makes perfect sense, because in order to receive updates from the Realm, the thread you're listening on must be a looper thread. 

> ObserveOn — specify the scheduler on which an observer will observe this Observable
> Subscribe — operate upon the emissions and notifications from an Observable
> SubscribeOn — specify the scheduler an Observable should use when it is subscribed to

You should subscribe on the io(), but observe on the AndroidSchedulers.mainThread()

**Comment by ar-g** [comment]
> If you specify subscribeOn(), it appears to me that you by default observe on the same scheduler as you specified in subscribeOn(), which is not a looper thread.

That is the thing I want changes from realm went to retrofit in the same io Thread. If change to subscribeOn(AndroidSchedulers.mainThread()) and then switch to io Thread everything works ok, but I wanted to avoid passing schedulers.

> By the way, you can't get updates into detached copies returned by copyFromRealm().
Thanks, but isn't  asObservable() will emit new items when an object stored in the realm will change?

**Comment by Zhuinden** [comment]
Actually, I started looking into your problem, and it's actually not as complicated to figure out as I thought.

The `RealmObservableFactory` attempts to register a change listener when you call `asObservable()` with it, this is the code

``` java
    @Override
    public Observable<Realm> from(Realm realm) {
        final RealmConfiguration realmConfig = realm.getConfiguration();
        return Observable.create(new Observable.OnSubscribe<Realm>() {
            @Override
            public void call(final Subscriber<? super Realm> subscriber) {
                // Get instance to make sure that the Realm is open for as long as the
                // Observable is subscribed to it.
                final Realm observableRealm = Realm.getInstance(realmConfig);
                final RealmChangeListener<Realm> listener = new RealmChangeListener<Realm>() {
                    @Override
                    public void onChange(Realm realm) {
                        if (!subscriber.isUnsubscribed()) {
                            subscriber.onNext(observableRealm);
                        }
                    }
                };
                observableRealm.addChangeListener(listener);
                subscriber.add(Subscriptions.create(new Action0() {
                    @Override
                    public void call() {
                        observableRealm.removeChangeListener(listener);
                        observableRealm.close();
                    }
                }));
                subscriber.onNext(observableRealm);
            }
        });
    }
```

And this line

            observableRealm.addChangeListener(listener)

Works only if the Thread you're on supports auto-update, which the `Schedulers.io()` does not (it is not a Looper thread).

I guess a possible solution would be to either provide a different observable factory that doesn't try to add a change listener if the realm returns `realm.isAutoRefresh()` is true.

**Comment by Zhuinden** [comment]
@ar-g have you tried `.subscribeOn(Schedulers.io()).observeOn(AndroidSchedulers.mainThread())`?

**Comment by ar-g** [comment]
Ok, probably it makes sense to notice it in `asObservable()` docs that it won't work in io Thread. Because I'm expecting auto-update instances work in any thread, it was created
What I tried to do is passing observed items to retrofit2, without extra changing of threads
```java
//Model Layer
historyOrderRepository.getCopyOfLastOrdersFromRealm()
        .flatMap(orders -> networkService.makeRequest(orders))
//Ui Layer
        .subscribeOn(Schedulers.io())
        .observeOn(AndroidSchedulers.MainThread)
        .subscribe(...do ui stuff)
```

**Comment by Zhuinden** [comment]
I agree, you **should** be able to retrieve an observable RealmResults even on a non-looper thread and do operations with it as long as you keep it on that thread, in my opinion.

A possible workaround would be to create your own RealmObservableFactory, which doesn't rely on a change listener to create the observable... although the current implementation confuses me - I don't really use Rx. Also I'm constantly wondering even now how you should open a Realm instance on the io scheduler, and retain a reference to it throughout, and then close it at the end of subscription.

This is currently over my level of knowledge regarding Rx, but I think @cmelchior  can help.

**Comment by cmelchior** [comment]
A Realm observable on a non-looper thread doesn't make a lot of sense since there is no point in time when it is safe to call `onNext()` , so it would behave exactly as `Observable.just()`. You are right, we should document that better (it is described under our change listeners, but that get kinda hidden for Observables).

It is possible to create your own `RealmObservableFactory` that detects if it is on a looper thread though and just call `Observable.just()` in that case. However, I would be a bit cautious about adopting that pattern in the official API, since we otherwise try to keep everything up to data. We could of course just document that is what is happening.

If you don't want to create your own RealmObservableFactory. Doing the below would give you the same behaviour:

````
// This is the same 
Observable.just(realm.where(Foo.class).findAll())

// as this, _if_ `asObservable()` worked on a non-looper thread
realm.where(Foo.class).findAll().asObservable()

**Comment by ar-g** [comment]
Thanks for clearing it out for me. If I correctly understood for getting notified that items changed in realm, I should use only Main thread for now.

**Comment by cmelchior** [comment]
Yes, automatic notifications only work on Looper threads.

**Comment by Zhuinden** [comment]
On top of that, RealmObjects returned via `copyFromRealm()` are detached from the Realm, and no longer auto-updated.

**Comment by Zhuinden** [comment]
@ar-g I think the intended usage of `Realm`'s `asObservable()` method is like [this link](https://github.com/Zhuinden/rx-realm-recyclerview-experiment/blob/master/app/src/main/java/com/zhuinden/rxrealm/FirstView.java#L127-L146
)

So essentially

``` java
    EventEmitter.someObservable()
    .switchMap((x) -> query.findAllSortedAsync(Dog.Fields.NAME.getField()).asObservable())
    .filter(RealmResults::isLoaded) 
    .subscribe(dogs -> adapter.updateData(dogs));
```

**Comment by stk1m1** [comment]
Hi @ar-g 

Have comments here helped you? Could you update your status with us? Thanks.

**Comment by ar-g** [comment]
yes, my scenario is against design, closing this issue for now.
