### ISSUE TITLE
Query Realm for data that is NOT in array?

### ISSUE THREAD

**Issue by MiralDesai** [realm/realm-java#3154]
#### Goal

> What do you want to achieve?

To be able to pass in an ArrayList<Integer> of ids and to query realm with those ids, and collect all data that does NOT have that id.

#### Actual Results
 
With what I have tried, I am getting every object in my query, even those that match the ids in my `ArrayList`.

Is there a solution to this? This is what I have tried:

```
ArrayList<Integer> savedObjectIds = new ArrayList<>(); // just to show you what the ArrayList contains
RealmQuery<Object> query = realm.where(Object.class);
        for (int id : savedObjectIds) {
            query = query.notEqualTo(Constants.ID, id).equalTo(Constants.USER_ID, userId);
        }
        RealmResults<Object> objectsNotInArray = query.findAll();
```

So for a specific user I want to delete all of the Objects where the ids do not match any of those in the array.

Wondering if you guys have any potential solutions? I have thought about passing in the Objects itself then deleting everything in the model and just adding the Object ArrayList I have back in, but that seems like an unnecessary transaction.

#### Version of Realm and tooling
Realm version(s): 1.1.0

Android Studio version: 2.1.2

**Comment by Zhuinden** [comment]
``` java
public RealmResults<Object> getNotIn(List<Integer> savedObjectIds) {
    RealmQuery<Object> query = realm.where(Object.class);
    int i = 0;
    for(Integer id : ids) {
        if(i != 0) {
            query = query.or();
        }
        query = query.notEqualTo(Constants.ID, id);
        i++;
    }
    return query.findAll();
}
```

Please try this

**Comment by Zhuinden** [comment]
``` java
       RealmQuery<Object> query = realm.where(Object.class);
        for (int id : savedObjectIds) {
            query = query.notEqualTo(Constants.ID, id);
        }
        query = query.equalTo(Constants.USER_ID, userId);
        RealmResults<Object> objectsNotInArray = query.findAll();
```

I think this one based on what you've provided should work.

**Comment by MiralDesai** [comment]
Thanks, bottom one worked!

**Comment by heinrichreimer** [comment]
I wonder if this would also be possible using `RealmQuery.not()`?

**Comment by Zhuinden** [comment]
Probably. But I didn't think of that for some reason.

**Comment by matthewkrueger** [comment]
Can confirm, not() works.

`realm.where<Layout>().in("course.courseId", courseIds.toTypedArray()).not().in("layoutId", validLayoutIds).findAll()`
