### ISSUE TITLE
Disable auto updating of RealmObjects? RecyclerView order changing

### ISSUE THREAD

**Issue by MiralDesai** [realm/realm-java#3156]
#### Goal

> What do you want to achieve?
To be able to have consistent data across various activities. To stop my RecyclerView from updating and moving items into the wrong order.

#### Expected Results

> Load Activity with RecyclerView --> Tap on item --> Open new activity --> Tap on button --> Open new activity, and an api call is made to get the updated json for the item i tapped on --> Press back button to get to RecyclerView and the list is still in the same order.

#### Actual Results

Follow the above user journey, and when I go back to the main screen with my RecyclverView the item I tapped on has now jumped to the top of the list. If I do it again with a different item in the list, the item I tapped on jumps up to position 2, and if I do it again, position 3, etc etc. I think this is because the data for that object has been updated.

I do NOT use a realm change listener and this still happens. Refreshing my RecyclverView (pull to refresh) re-orders the list back into the correct order.

Is there a way for me to get an RealmResults<object> and not have it auto update?

#### Version of Realm and tooling
Realm version(s): 1.1.0

Android Studio version: 2.1.2

Which Android version and device: Nexus 5 Android M.

**Comment by Zhuinden** [comment]
You need to set `setStableIds(true)`, but you must also copy your Realm results into a new list with copyFromRealm on each of them. 

RealmResults frozen state is on the road map, but I think it has some other major dependencies first so I think it was P2.

**Comment by beeender** [comment]
@MiralDesai Hope above answered your question. Thanks a lot for your feedback!

**Comment by MiralDesai** [comment]
Sorry yeah it did, just haven't time to try it. in regards to @Zhuinden comment; I already use findAllSorted with a distance param, I think the stableIds is what I need and to copy my RealmResults.
