### ISSUE TITLE
Object is no longer valid to operate on

### ISSUE THREAD

**Issue by mancj** [realm/realm-java#3162]
please fix this stupid error "Object is no longer valid to operate on" or make a way to check if the object is accessible!

**Comment by Zhuinden** [comment]
This can be the result of either that:

1.) your Realm instance that this object belongs to has been closed

2.) your Realm object has been deleted in a transaction on some thread

Either way, it's not an error in Realm, unless the Realm closed unexpectedly.

**Comment by kneth** [comment]
@mancj Please use the template when creating issue. Without we can only guess which will not solve your problem.
