### ISSUE TITLE
Documentation is unclear about when migrations are run

### ISSUE THREAD

**Issue by spl** [realm/realm-java#3165]
#### Goal

Learn when migrations are run.
#### Expected Results

Reading the [Migrations section](https://realm.io/docs/java/1.1.0/#migrations) of the documentation, I expect to find a statement mentioning when migrations are run.
#### Actual Results

I find the following statement:

> Using this, the migration code will be run automatically if needed.

I don't mean to be pedantic, but this statement is a bit ambiguous and potentially misleading. First, what is “automatic” about running the migration code? Second, _is_ the code run only “if needed”? From my experiments, it seemed like `RealmMigration.migrate()` was being run every time I built the `RealmConfiguration`.

I could be wrong about this, but I think it's the pattern described in the [`RealmMigration` API docs](https://realm.io/docs/java/1.1.0/api/io/realm/RealmMigration.html) that provides the “if needed” aspect of the above statement. And I don't think there's anything automatic about running the `migrate()` method.

The quoted statement could lead me to think I don't have to do any work for migration. But, in reality, I have to do _all_ of the work to implement the migration.
#### Suggestion

I would change the quoted statement to something more precise and less misleading. For example:

> Using this, you can write a schema migration from any previous version to the latest.

I would also add a link to the [`RealmMigration` API reference](https://realm.io/docs/java/1.1.0/api/io/realm/RealmMigration.html) since that provides a useful description of the migration code pattern.

**Comment by Zhuinden** [comment]
Apparently it seems to me that calling `Realm.getInstance(configuration)` will call the `RealmCache` to see if there is a local Realm, and if there is no local Realm, then `Realm.createInstance(config, cache.typedColumnIndices)` is called, which calls `Realm.createAndValidate(config, indices)` which then calls 

        try {
            return createAndValidate(configuration, columnIndices);

        } catch (RealmMigrationNeededException e) {
            if (configuration.shouldDeleteRealmIfMigrationNeeded()) {
                deleteRealm(configuration);
            } else {
                try {
                    migrateRealm(configuration);

Which then is (after checking if there are any open realms and stuff with `RealmCache.invokeWithGlobalRefCount()`:

    public static void migrateRealm(RealmConfiguration configuration, RealmMigration migration)
            throws FileNotFoundException {
        BaseRealm.migrateRealm(configuration, migration, new MigrationCallback() {
            @Override
            public void migrationComplete() {
            }
        });
    }

I have this odd feeling that the migration happens on the first opening of Realm, **on the thread where that given Realm is opened**. :confused:

**Comment by cmelchior** [comment]
Yes, that is correct, which is also why we talked about providing an async `getInstance()`. So far we decided against it, but you can see the discussion in https://github.com/realm/realm-java/issues/2299

**Comment by cbush** [comment]
We are revamping the Realm docs. We're not ignoring this issue -- we've read through every one of them, and we'll be sure to address this as part of our updates. We're closing the GitHub issues and creating new JIRA tickets to track the work at a high level.
