### ISSUE TITLE
RealmList returns RealmModel instead of RealmObject. How to adapt this change?

### ISSUE THREAD

**Issue by GokhanArik** [realm/realm-java#3168]
Hi,

I just upgraded my Realm from 0.88.3 to 1.1.0. To delete RealmObjects from a RealmList, I used to use this method in a for loop:

`list.get(i).removeFromRealm();`

I saw that `removeFromRealm` is deprecated in favour of `deleteFromRealm`. When I replace method, it doesn't recognize the method because `get()` returns `RealmModel` instead of `RealmObject`.

Is it safe to cast `RealmModel` to `RealmObject` and use like I did below or is there a better solution?

`((RealmObject)list.get(i)).deleteFromRealm();`

#### Version of Realm and tooling
Realm version(s): 0.89.0 and above

**Comment by beeender** [comment]
Hi!
You can use `RealmList.deleteFromRealm(int location)` instead.
Or there is a static method added to `RealmObject`, `RealmObject.deleteFromRealm(E Object)` which can take a `RealmModel` as input param.

**Comment by GokhanArik** [comment]
Thanks @beeender , second one is what I was looking for!

**Comment by beeender** [comment]
:tada:
