### ISSUE TITLE
IllegalArgumentException: 'value' is not a valid managed object 

### ISSUE THREAD

**Issue by pawlo2102** [realm/realm-java#3169]
Hello. Would you be so kind to help me update attached model. The example of the code is attached below. Again and again I see the one mistake and nothing can avoid it including suggested solution

 public void setMessage(final Message message) {

      
        mRealm.beginTransaction();
        mRealm.copyToRealmOrUpdate(message);
        mRealm.commitTransaction();

        mRealm.beginTransaction();
        Chat chat = getChat(message.getApplicant());
        chat.setLast_message(message);
        mRealm.copyToRealmOrUpdate(chat);
        mRealm.commitTransaction();

    }

**Comment by Zhuinden** [comment]
Can't you do that in ONE transaction? 

Anyways, the issue is that your `message` remains unmanaged because you didn't do `message = mRealm.copyToRealmOrUpdate(message)`.

**Comment by pawlo2102** [comment]
Thx a lot!

**Comment by beeender** [comment]
@Zhuinden Thanks a again!
