### ISSUE TITLE
Why is executeTransactionAsync() slow?

### ISSUE THREAD

**Issue by GokhanArik** [realm/realm-java#3170]
Hi guys,

I recently started to replace my transaction methods with **executeTransactionAsync** and I'm having a serious performance issue. The API call I make returns an array of 425 objects, I loop through them and save to Realm and it is taking around 3-4 minutes. 

I've read somewhere else that Android limits background tasks and they won't be as fast as UI thread. I guess one reason is that. And the second reason might be **fromJson** method but I'm not sure.

I just wanted to check if any of you run into the same/similar problem and have a better idea to solve this problem.

Thanks

```
defRealm.executeTransactionAsync(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {
                // Update data in one transaction
                for (JsonElement element : json) {
                    Log.v(TAG, "JsonElement: " + json.toString());
                    JsonObject doc = element.getAsJsonObject();

                    final String type = doc.get("type").getAsString().toUpperCase();
                    doc.addProperty("type", type);
                    final ModelEnum modelEnum = ModelEnum.fromString(type);

                    if (modelEnum != null) {
                        addOrUpdate(realm, doc, modelEnum.getClazz());         
                }
            }
        }, new Realm.Transaction.OnSuccess() {
            @Override
            public void onSuccess() {
                Log.v(DataService.class.getName(), "Success");
            }
        }, new Realm.Transaction.OnError() {
            @Override
            public void onError(Throwable error) {
                error.printStackTrace();
            }
        });
```

```
private <T extends RealmObject> void addOrUpdate(Realm realm, JsonObject json, Class<T> modelClass) {
        final T obj = buildGsonAdapter().fromJson(json, modelClass);
        realm.copyToRealmOrUpdate(obj);
    }
```
#### Version of Realm and tooling
Realm version(s): 1.1.0

**Comment by Zhuinden** [comment]
I think it's your JSON parsing, and I'd try using `LoganSquare` instead of `Gson`. Also you shouldn't build a new Gson instance for each and every object you save, because Gson would be caching if it re-used the instance.

**Comment by GokhanArik** [comment]
No I'm not building Gson instance, it is returning cached one. I will check LoganSquare

**Comment by zaki50** [comment]
Hi @GokhanArik 

How many `ModelEnum` objects is in the realm database before calling `executeTransactionAsync()`?
And can you show us the definition of `ModelEnum`?

**Comment by GokhanArik** [comment]
Zero. I clear app data so I can test it better. I can't show since it has business logic but I can tell what it is. We have type field in our Json objects, that basically maps type of object to model. We use it to get Class of the object and to store some additional information about our models.

**Comment by beeender** [comment]
Hi @GokhanArik Can you please measure how much time does the `execute(Realm realm)` function take instead of the time elapsed before `Log.v(DataService.class.getName(), "Success");` ?

**Comment by GokhanArik** [comment]
Hi Chen @beeender , 

I've been working on this since this morning and I made good progress. I guess the problem was another call below this. I changed the structure of my code and it works fine now. I am still working on finalizing it, once I finish I will stash my old code and try to understand what the actual problem was. 

I deleted my old commit and rewrote the code and it started to work really fast. I will post my findings once I finish it. Thanks!

**Comment by beeender** [comment]
@GokhanArik Good to hear that! we will keep the issue opened for a bit longer in case there is still something not clear in the Realm side. Let us know when it is solved. Thanks a lot!

**Comment by GokhanArik** [comment]
Thanks @beeender , 

You can close the issue, I stashed the old code and found out something really stupid. The main thing that slows down my code was `toString` method of `json` object in my Log statement :

`Log.v(TAG, "JsonElement: " + json.toString());`

I would never think this call costs 0.5 seconds. 425 elements * 0.5 = 3.5 mins. 

Sorry for taking your time, you guys had great support as always!

**Comment by beeender** [comment]
:dancers:
