### ISSUE TITLE
All nested objects become null after I close my app (Android)

### ISSUE THREAD

**Issue by SupreeSeekSter** [realm/realm-java#3171]
I can save and retrieve data correctly but after I close my application the object "category" and "user" become null.

My object look like this 
```
public class Service extends RealmObject implements BaseModel {
    private RealmList<SubCategory> subCategories = new RealmList<>();
    private RealmList<District> districts = new RealmList<>();

    @PrimaryKey
    private String id;
    private String name;
    private String bio;
    private String address1;
    private String address2;

    **private Category category;**
    **private User user;**
```
----------------------------------------------------------------------------------------------
```
public class Category extends RealmObject implements BaseModel {
    private RealmList<SubCategory> subCategories = new RealmList<>();

    @PrimaryKey
    private String id;

    private String name;
    private String iconUrl;
    private String backgroundUrl;
```
---------------------------------------------------------------------------------------------
```
public class User extends RealmObject implements BaseModel {
    private RealmList<Service> services = new RealmList<>();

    @PrimaryKey
    private String id;

    private String email;
    private String name;
    private String gender;
    private String bio;
    private int credits;

    private Date dateOfBirth;
    private String profilePicture;
    private String phoneNumber;
```
I can save and retrieve "User" and "Category" but after I close my application and reopen it, my objects become null.

Please see the attached images. 

![before close app](https://cloud.githubusercontent.com/assets/19761196/16756039/7ad4bd78-482c-11e6-81fe-d85ae8fe38e1.PNG)
![after close app](https://cloud.githubusercontent.com/assets/19761196/16756042/8115b9c6-482c-11e6-98ec-2fa84342a0b5.PNG)

**Comment by beeender** [comment]
Can you share the code related with
1. Build the `RealmConfiguration`
2. Get Realm instance
3. Execute Realm transaction to write to the Realm db

**Comment by SupreeSeekSter** [comment]
1. RealmConfiguration

public class SeeksterApplication extends Application {

    @Override
    public void onCreate() {
        super.onCreate();
        Fabric.with(this, new Crashlytics(), new CrashlyticsNdk());
        FacebookSdk.sdkInitialize(getApplicationContext());
        AppEventsLogger.activateApp(this);
        Preferences.init(this);
        ColorHelper.init(this);

        RealmConfiguration realmConfiguration = new RealmConfiguration.Builder(this).build();
        Realm.setDefaultConfiguration(realmConfiguration);

        if (Preferences.getString("base_url") == null) {
            Preferences.setString("base_url", getString(R.string.base_url));
        }

        if (Preferences.getString("api_url") == null) {
            Preferences.setString("api_url", getString(R.string.api_url));
        }
    }
}


2. & 3.  Get Realm instance and execute transaction
Realm.getDefaultInstance().executeTransaction(new Realm.Transaction() {
                        @Override
                        public void execute(Realm realm) {
                            realm.copyToRealmOrUpdate(services);
                        }
                    });

**Comment by beeender** [comment]
`Realm.getDefaultInstance().executeTransaction()` calling like this might cause leaks since the returned instance of `Realm.getDefaultInstance()` is not closed. But it is not related with this problem.

How does the input `services` look like? How did you show the results?

**Comment by Zhuinden** [comment]
You need to set those fields in the RealmObject inside a transaction using `executeTransaction()` with the managed objects you'd like those fields to be.

**Comment by beeender** [comment]
@Zhuinden `copyToRealmOrUpdate()` should do that automatically for un-managed object. Unless there is a bug?

**Comment by SupreeSeekSter** [comment]
My input service :

    private void fetchServices() {
        Call<ListResponse<Service>> call = getAPI().myServices(Preferences.getString("access_token"), Locale.getDefault().getLanguage());
        call.enqueue(new Callback<ListResponse<Service>>() {
            @Override
            public void onResponse(Call<ListResponse<Service>> call, final Response<ListResponse<Service>> response) {
                if (response.isSuccessful()) {
                    services.clear();
                    services.addAll(response.body().list);
                    serviceAdapter.notifyDataSetChanged();

                    Realm.getDefaultInstance().executeTransaction(new Realm.Transaction() {
                        @Override
                        public void execute(Realm realm) {
                            realm.copyToRealmOrUpdate(services);
                        }
                    });
                }
            }

            @Override
            public void onFailure(Call<ListResponse<Service>> call, Throwable t) {
                t.printStackTrace();
            }
        });
    }


The result from the above images come from this library:
      compile 'com.scand:realm-browser:0.1.13'


I also check the result by logging inside the onCreate.
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        services.addAll(Realm.getDefaultInstance().where(Service.class).equalTo("user.id", Preferences.getUserId()).findAll());

        try {
            Log.d("TEST_REALM", "" + services.get(0).getUser().getId());
        }catch (Exception e){
            e.printStackTrace();
        }
    }

**Comment by beeender** [comment]
I have no idea without more information. If you can share your project which can reproduce the issue, we can help to take a look. To help@realm.io if you want to share it privately.

**Comment by Zhuinden** [comment]
@SupreeSeekSter  you seriously need to consider not opening so many Realm instances with `Realm.getDefaultInstance()`. A realm that was opened should also be closed, and using realm like this `Realm.getDefaultInstance().where(` and this `Realm.getDefaultInstance().executeTransaction(` will prevent that.

@beeender technically I said that because if you don't have primary keys, then you ought to set the object itself otherwise you'll end up with duplicates - but yes, you're correct, `copyToRealmOrUpdate()` does handle that with object links, although if you're mapping a RealmList into a managed object, then your RealmList must be persisted first with `copyToRealmOrUpdate()` (although for whatever reason returns an `ArrayList` so you can't just set it over for the object link)

**Comment by beeender** [comment]
close due to no response

**Comment by shashank090789** [comment]
@SupreeSeekSter hi , any update regarding this issue, I am facing the same issue.

**Comment by Zhuinden** [comment]
@shashank090789 then you are overwriting the object with a new instance where the linked property is null.

**Comment by shashank090789** [comment]
@Zhuinden I am not updating the object , it happens when I force closed the app.

**Comment by Zhuinden** [comment]
Then you're deleting the linked objects somewhere in your code when you re-open the app.. O_O

**Comment by AlbertMartorell** [comment]
Hi everybody.
@Zhuinden, I am facing the same issue. And as @shashank090789 mentioned, it happens randomly. I am using the io.realm:realm-gradle-plugin:4.3.3 version.
The key it seems the key is when a RealmObject is updated. And It looks like it does not matter that the field is a nested RealmObject or a "simple" one.

Below there is simplify schema of the model.

```
public class UserBook extends RealmObject {

    @PrimaryKey
    @Required
    public String id;
    @Required
    public String status;
    @Required
    public String accessType;
    @Required
    public String activationDate;
    @Required
    public String expirationDate;
    public boolean renewalEnabled;
    public int sizeNotDownloaded;
    public int currentUnit;
    public int currentSection;
    public ZoomBook zoomBook;

}
```

```
public class ZoomBook extends RealmObject {

    @PrimaryKey
    public String id_random = UUID.randomUUID().toString();
    public String bookId;
    public String userBookId;
    public String type;
    public String title;
    public String subtitle;
    public String shortName;
    public String status;
    public ZoomSubject subject;
    public String authors;
    public String year;
    public String isbn;
    public String educationLaw;
    public String isoCountry;
    public String orientation;
    public boolean forPads;
    public long lastUpdateJsonDate;
    public long createdAt;
    public long updatedAt;
    public ZoomThumbnail principalThumbnails;
    public ZoomSecondaryThumbnail secondaryThumbnails;
    public String locale;
    public Course course;
    public RealmList<ZoomAutonomies> autonomies;
    public ZoomColorSet colorSet;
    public ZoomStructure structure;

}
```

**Comment by Zhuinden** [comment]
> the data is successfully saved on the database, but sometimes when I closed the app and then I re-open it, both fields have the old values.

That is not possible if you successfully commit the transaction.

-----

Generally I think these overwrites you guys mention happens because you are trying to use an unmanaged object and use `copyToRealmOrUpdate()`/`insertOrUpdate()` to save it, but you forget setting a few fields, or your linked objects are not set.

Try using a query to obtain the managed object, and set the fields you want to change on that.
