### ISSUE TITLE
`copyToRealmOrUpdate(Iterable<T>)` returns `ArrayList` instead of `RealmList`

### ISSUE THREAD

**Issue by Zhuinden** [realm/realm-java#3172]
#### Goal

> What do you want to achieve?

I'd like to persist a list of RealmObjects with `copyToRealmOrUpdate()` and then set the managed list as a field in another object
#### Expected Results

I should be able to do this

``` java
    //assume I'm in a transaction
    RealmList<Channel> channels = new RealmList<>();
    for(ChannelBO channelBO : downloadedChannels) {
         channels.add(Channel.createFrom(channelBO)); // uses new Channel();
    }
    schedules.setChannels(realm.copyToRealmOrUpdate(channels));
```
#### Actual Results

The collection returned by `copyToRealmOrUpdate()` is an `ArrayList`, which cannot be set as a list field directly, you must first create a new RealmList and copy over the elements.

``` java
    @Override
    public RealmList<T> saveOrUpdate(Realm realm, RealmList<T> list) {
        RealmList<T> realmList = new RealmList<>();
        for(T t : realm.copyToRealmOrUpdate(list)) {
            realmList.add(t);
        }
        return realmList;
    }
```

Of course, with some extra thinking one can say you can use `realm.createObject(Channel.class, primaryKey)` to get managed copies from the start, but I like being able to use `new`

Anyways I think it throws a `ClassCastException` if I remember right.
#### Version of Realm and tooling

Realm version(s): 1.1.0

Android Studio version: 2.1.1 (irrelevant)

Which Android version and device: 6.0.1, Nexus 5X (irrelevant)

**Comment by beeender** [comment]
The use case does make sense but the idea of `RealmList` is that it is a representation of Realm underlying engine's `LinkView`. By returning a `RealmList`, it means we have a unmanaged `RealmList` which contains some managed `RealmObject`.

@realm/java What do you guys think?

**Comment by kneth** [comment]
Overloading on return type isn't possible in Java, so we can't have two different `copyToRealmOrUpdate()` methods. Since you are looping in your original snippet, you might do

    RealmList<Channel> channels = new RealmList<>();
    for(ChannelBO channelBO : downloadedChannels) {
         channels.add(realm.copyToRealm(channelBO));
    }
    schedules.setChannels(channels);

**Comment by Zhuinden** [comment]
@kneth  but that approach creates a new `HashMap<>` for each copied element like so

``` java
    public <E extends RealmModel> E copyToRealmOrUpdate(E object) {
        checkNotNullObject(object);
        checkHasPrimaryKey(object.getClass());
        return copyOrUpdate(object, true, new HashMap<RealmModel, RealmObjectProxy>());
    }
```

while the iterable creates only one hash map for the collection

``` java
        Map<RealmModel, RealmObjectProxy> cache = new HashMap<RealmModel, RealmObjectProxy>();
        ArrayList<E> realmObjects = new ArrayList<E>();
        for (E object : objects) {
            checkNotNullObject(object);
            realmObjects.add(copyOrUpdate(object, true, cache));
        }
```

And you do need the proxies in order to set the values in the RealmList.

I guess another possibility is to use `insertToRealmOrUpdate()` and when use a `findAll()` for the inserted elements, but that seems a bit extreme.

**Comment by cmelchior** [comment]
I agree with https://github.com/realm/realm-java/issues/3172#issuecomment-231972230 and https://github.com/realm/realm-java/issues/3172#issuecomment-231975270 on this. The current behaviour is what makes the most sense and the use case expressed here will just require additional code like:

```
List<Person> persons = realm.copyToRealm(getNetworkData());
realm.beginTransaction();
Party party = realm.where(Party.class).findFirst();
party.getAttendees().addAll(persons);
realm.commitTransaction();
```

**Comment by Zhuinden** [comment]
`copyToRealm()` outside of the transaction won't work, but yes, `addAll()` makes sense.
