### ISSUE TITLE
Unreachable statement in DefaultRealmModuleMediator

### ISSUE THREAD

**Issue by leisim** [realm/realm-java#3176]
#### Goal

Build without errors

#### Actual Results

```
Note: Creating DefaultRealmModule
C:\Users\me\StudioProjects\Apps\warehouse\build\generated\source\kapt\debug\io\realm\DefaultRealmModuleMediator.java:102: error: unreachable statement
            if (iterator.hasNext()) {
            ^
C:\Users\me\StudioProjects\Apps\warehouse\build\generated\source\kapt\debug\io\realm\DefaultRealmModuleMediator.java:130: error: unreachable statement
            if (iterator.hasNext()) {
            ^
2 errors
```

#### Code Sample
This is the generated method which causes the error:
```java
  @Override
  public void insert(Realm realm, Collection<? extends RealmModel> objects) {
        Iterator<? extends RealmModel> iterator = objects.iterator();
        RealmModel object = null;
        Map<RealmModel, Long> cache = new IdentityHashMap<RealmModel, Long>(objects.size());
        if (iterator.hasNext()) {
            //  access the first element to figure out the clazz for the routing below
            object = iterator.next();
            // This cast is correct because obj is either
            // generated by RealmProxy or the original type extending directly from RealmObject
            @SuppressWarnings("unchecked") Class<RealmModel> clazz = (Class<RealmModel>) ((object instanceof RealmObjectProxy) ? object.getClass().getSuperclass() : object.getClass());

            throw getMissingProxyClassException(clazz);
            if (iterator.hasNext()) { //This line can never be reached
                throw getMissingProxyClassException(clazz); //Line 102
            }
        }
    }
```

The same problem is in `insertOrUpdate()` (line 130)

#### Version of Realm and tooling
Realm version(s): 1.1.0

Android Studio version: 2.2 Preview 5

**Comment by Zhuinden** [comment]
Same issue as here

https://github.com/realm/realm-java/issues/3115

**Comment by Zhuinden** [comment]
By the way, a well-looking `insert()` looks like this

    @Override
    public void insert(Realm realm, Collection<? extends RealmModel> objects) {
        Iterator<? extends RealmModel> iterator = objects.iterator();
        RealmModel object = null;
        Map<RealmModel, Long> cache = new IdentityHashMap<RealmModel, Long>(objects.size());
        if (iterator.hasNext()) {
            //  access the first element to figure out the clazz for the routing below
            object = iterator.next();
            // This cast is correct because obj is either
            // generated by RealmProxy or the original type extending directly from RealmObject
            @SuppressWarnings("unchecked") Class<RealmModel> clazz = (Class<RealmModel>) ((object instanceof RealmObjectProxy) ? object.getClass().getSuperclass() : object.getClass());

            if (clazz.equals(blah.data.entity.objects.FeedCategory.class)) {
                io.realm.FeedCategoryRealmProxy.insert(realm, (blah.data.entity.objects.FeedCategory) object, cache);
            } else if (clazz.equals(blah.data.entity.objects.GalleryPost.class)) {
                io.realm.GalleryPostRealmProxy.insert(realm, (blah.data.entity.objects.GalleryPost) object, cache);
            } else if (clazz.equals(blah.data.entity.objects.GalleryItem.class)) {
                io.realm.GalleryItemRealmProxy.insert(realm, (blah.data.entity.objects.GalleryItem) object, cache);
            } else if (clazz.equals(blah.data.entity.objects.CompetitionPost.class)) {
                io.realm.CompetitionPostRealmProxy.insert(realm, (blah.data.entity.objects.CompetitionPost) object, cache);
            } else if (clazz.equals(blah.data.entity.objects.FeedItem.class)) {
                io.realm.FeedItemRealmProxy.insert(realm, (blah.data.entity.objects.FeedItem) object, cache);
            } else if (clazz.equals(blah.data.entity.objects.ResultFilter.class)) {
                io.realm.ResultFilterRealmProxy.insert(realm, (blah.data.entity.objects.ResultFilter) object, cache);
            } else {
                throw getMissingProxyClassException(clazz);
            }
            if (iterator.hasNext()) {
                if (clazz.equals(blah.data.entity.objects.FeedCategory.class)) {
                    io.realm.FeedCategoryRealmProxy.insert(realm, iterator, cache);
                } else if (clazz.equals(blah.data.entity.objects.GalleryPost.class)) {
                    io.realm.GalleryPostRealmProxy.insert(realm, iterator, cache);
                } else if (clazz.equals(blah.data.entity.objects.GalleryItem.class)) {
                    io.realm.GalleryItemRealmProxy.insert(realm, iterator, cache);
                } else if (clazz.equals(blah.data.entity.objects.GalleryPicture.class)) {
                    io.realm.GalleryPictureRealmProxy.insert(realm, iterator, cache);
                } else if (clazz.equals(blah.data.entity.objects.CompetitionPost.class)) {
                    io.realm.CompetitionPostRealmProxy.insert(realm, iterator, cache);
                } else if (clazz.equals(blah.data.entity.objects.FeedItem.class)) {
                    io.realm.FeedItemRealmProxy.insert(realm, iterator, cache);
                } else if (clazz.equals(blah.data.entity.objects.ResultFilter.class)) {
                    io.realm.ResultFilterRealmProxy.insert(realm, iterator, cache);
                } else {
                    throw getMissingProxyClassException(clazz);
                }
            }
        }
    }

So it's as if during your compilation process, the RealmObjects wouldn't be there, and the Realm-Transformer wouldn't be able to find them. Quite odd!

**Comment by Zhuinden** [comment]
@nhachicha wait a second, why is this here?

 if (iterator.hasNext()) {
            //  access the first element to figure out the clazz for the routing below
            object = iterator.next();
           if (iterator.hasNext()) {

?

**Comment by leisim** [comment]
Oh, sorry, I didn't see the other issue. Should I close this one?

The strange thing is that the build works *sometimes*. I didn't find out the cause yet :/

**Comment by Zhuinden** [comment]
Well in the other one, the root cause was mixing Kotlin with Java.

Another is the new Gradle build tool alpha 5 thing.

**Comment by leisim** [comment]
I don't use Java at all...

**Comment by beeender** [comment]
Dup to #3115 @leisim Let's discuss this in #3115
