### ISSUE TITLE
All fields are empty after bulk insert

### ISSUE THREAD

**Issue by suleymanccelik** [realm/realm-java#3182]
#### Goal

I am trying to bulk insert to my db after network operation is completed. For network operation I am using retrofit and response of network operation is successful and all json fields are non-empty or not null. Bulk insert operation is successful and all fields are non-empty on LG G3 ( Android 5.0.0 ) however same operation and same code have not successful result on Samsung Galaxy S4 Mini ( GT-I9190 Android 4.4.2). 

#### Expected Results

> After bulk insert operation, all fields must be filled on both phones. 

#### Code Sample
I am trying to add items with following codes. I also tried insertOrUpdate(listOfData) but after operation all fields are empty again.
```java
           dbRealm.beginTransaction();
           dbRealm.copyToRealmOrUpdate(institutionList);
           dbRealm.commitTransaction();

           or 

           dbRealm.executeTransaction(new Realm.Transaction() {
                @Override
                public void execute(Realm realm) {
                    realm.copyToRealmOrUpdate(listOfData);
                }
            });
```

#### Version of Realm and tooling
Realm version(s): 1.1.0

Android Studio version: 2.1.2

Which Android version and device: LG G3 -> Android 5.0.0 and Samsung Galaxy S4 Mini  -> Android 4.4.2

<img width="745" alt="screen shot 2016-07-13 at 15 12 24" src="https://cloud.githubusercontent.com/assets/1086099/16802980/46ff860a-490c-11e6-8dd4-f13ba35f16ee.png">

**Comment by beeender** [comment]
I should be same issue with #3105 and will be fixed by #3116

**Comment by suleymanccelik** [comment]
Thanks @beeender.

**Comment by Zhuinden** [comment]
@beeender it should not empty the list with copy, only with insert, though (according to the bug).

**Comment by beeender** [comment]
@suleymanccelik To confirm, you problem is using `insertOrUpdate`, right? with `copyToRealmOrUpdate` there is no problem?

**Comment by suleymanccelik** [comment]
@beeender No, I also have problem using copyToRealmOrUpdate method.

**Comment by beeender** [comment]
@suleymanccelik Sorry I misunderstood the issue at the beginning.

How do you get the `institutionList`? It is very strange the same code behave different on different devices since this part of logic doesn't have any native code magics.

Can you cofirm:
1. `institutionList` doesn't not have those empty fields when save them to Realm
2. Which tool are you using to check the result? Is there a chance the data is not refreshed in the tool?

**Comment by suleymanccelik** [comment]
I am getting institutionList using retrofit with same api endpoint and same json result on devices. On onResponse method of retrofit, I am trying to insert or copy institutionList. Some fields may be empty for example one of institutions has no phoneNumber. After transaction completed, I run findAll() query and query result has one element. And I view realm file of samsung phone using RealmBrowser on Mac.

**Comment by beeender** [comment]
> After transaction completed, I run findAll() query and query result has one element.

If you are running `findAll()` on a different thread than the one saves data, the Realm db might not be up to date. Maybe you need to check it in the `RealmChangeListener` 

> And I view realm file of samsung phone using RealmBrowser on Mac.

So you adb pull the db to mac and view it? If so, maybe you can try to close all the Realm instances and then pull the db.

**Comment by suleymanccelik** [comment]
I am running findAll() on same thread. I checked size of list in the RealmChangeListener on devices. It is very strange again, result list size has 184 item on LG G3 but result list size has 1 item on Samsung phone. 

Yes I am using adb pull the db from phones. I confirm that All realm instances are closed. If a sample project would be better for you to analyze issue, I can create a sample project?

**Comment by beeender** [comment]
@suleymanccelik Yes, a sample project will be super helpful!!! You can send it to help@realm.io if you want to share it privately. Otherwise share it anywhere we can get it.
Thanks a lot!!

**Comment by suleymanccelik** [comment]
@beeender There are several build variants in my application and multidex is enabled on one of build variants so realm behaves different. I make you too busy. Sorry for that.

**Comment by beeender** [comment]
@suleymanccelik No problem. Let us know if more help needed!
