### ISSUE TITLE
Migration finding a field that should not exist

### ISSUE THREAD

**Issue by spl** [realm/realm-java#3183]
#### Goal

Implement a schema migration to add a new field to a schema in which that field should not exist.

#### Expected Results

The migration succeeds.

#### Actual Results

The app is finding that the field already exists and throwing `RealmMigrationNeededException`.

#### Steps & Code to Reproduce

This is our first attempt at a schema migration. As we have iterated around in development, we have added a field to a schema in one `git` branch and not added it in another. I've tested multiple branches on my device. In this scenario, I'm working with our `master` branch (unreleased), which has a migration from schema version 0 to 1. (Before this, we were using `.deleteRealmIfMigrationNeeded()`, but we also did not change the schema during that time.)

The migration in `master` adds a new field `id_tmp` to the model `MyModel`, removes the primary key field `id`, renames `id_tmp` to `id`, and adds `id` as a primary key. There is no mention of a new nullable `String` field `newField` on `MyModel` that is created in another branch, `add-new-field`, which I want to merge to `master`. On `add-new-field`, we simply extended the migration in `master` with `.addField("newField")`.

When running `master` (debug flavor) on my device, the migration complains that the field count for `MyModel` is wrong (expected 7 but was 8). I print the fields with the following at the beginning of the `migrate(DynamicRealm realm, long oldVersion, long newVersion)` method, and, surprise, field `newField` shows up in the list:

```java
Log.e("Migration", "MyModel fields: " + schema.get("MyModel").getFieldNames());
```

I also log to confirm that this migration is happening for `oldVersion` of 0 and `newVersion` of 1.

The exception stack trace is (approximately):

```
java.lang.RuntimeException: An error occurred while executing doInBackground()
    at android.os.AsyncTask$3.done(AsyncTask.java:309)
    at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:354)
    at java.util.concurrent.FutureTask.setException(FutureTask.java:223)
    at java.util.concurrent.FutureTask.run(FutureTask.java:242)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234)
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
    at java.lang.Thread.run(Thread.java:818)
 Caused by: io.realm.exceptions.RealmMigrationNeededException: Field count does not match - expected 7 but was 8
    at io.realm.MyModelRealmProxy.validateTable(MyModelRealmProxy.java:241)
    at io.realm.DefaultRealmModuleMediator.validateTable(DefaultRealmModuleMediator.java:99)
    at io.realm.Realm.initializeRealm(Realm.java:297)
    at io.realm.Realm.createAndValidate(Realm.java:265)
    at io.realm.Realm.createInstance(Realm.java:244)
    at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:126)
    at io.realm.Realm.getDefaultInstance(Realm.java:176)
    ...
    at android.os.AsyncTask$2.call(AsyncTask.java:295)
    at java.util.concurrent.FutureTask.run(FutureTask.java:237)
    at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:234) 
    at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113) 
    at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588) 
    at java.lang.Thread.run(Thread.java:818) 
```

The migration finishes, and the exception is thrown at the first use of the `Realm` instance.

I would like to be able to do the following:

1. Run `master` without getting the `RealmMigrationNeededException` about a field that should not exist.
2. Run `add-new-field` (after uninstalling the app and starting fresh) to test it and eventually merge it to `master`.

Thinking that maybe the app data is not deleted, I do:

1. Uninstall any existing app on device.
2. Install `master` on device and verify that the app data is empty.
2. Run `master` on device.

But I still get the same problem.

Thinking that maybe some Realm build files are not getting regenerated, I do:

1. Build → Clean Project in Android Studio.
2. Ensure that `.../app/build/generated/source/apt/debug/io/realm` (where I see `io.realm.MyModelRealmProxy` and `io.realm.MyModelRealmProxyInterface`) is deleted.
3. Install `master` on device and verify that the app data is empty.
4. Run `master` on device.

But I still get the same problem.

#### Versions

Realm version(s): 1.0.1 (upgraded from 1.0.0 on `master` as part of primary key migration)

Android Studio version: 2.1.2

Device: Nexus 5x
Android version on device: 6.0.1

**Comment by beeender** [comment]
I am trying to understand the case, just a quick confirmation:
The `newField` doesn't exist in master branch ever and it should never be existing in the schema, right?

And the Realm db is saved in the internal storage, which means it should be deleted when clean data?

**Comment by beeender** [comment]
>     Build → Clean Project in Android Studio.
>     Ensure that .../app/build/generated/source/apt/debug/io/realm (where I see io.realm.MyModelRealmProxy and io.realm.MyModelRealmProxyInterface) is deleted.
>    Install master on device and verify that the app data is empty.
>   Run master on device.

I am a bit confused about this. If it is a fresh start, the schema should be generated automatically without calling the migration block (No migration exception should be thrown).

**Comment by spl** [comment]
@beeender: Thanks for the questions.

> The `newField` doesn't exist in master branch ever and it should never be existing in the schema, right?

Correct. I've verified that it is not found in the code. `newField` is only introduced in the `add-new-field` branch. I have installed and used the `add-new-field` branch in the past, but now I'm trying to test only the `master` branch.

> And the Realm db is saved in the internal storage, which means it should be deleted when clean data?

Correct. We are not doing anything out of the ordinary regarding saving the Realm DB file in our configuration.

This is the configuration change that introduced the migration in `master` in an override of `android.app.Application.onCreate()`:

```diff
         // Build the RealmConfiguration and set it to the default.
-        // TODO: Do proper configuration (e.g. version, etc.)
         final RealmConfiguration config = new RealmConfiguration.Builder(this)
-            // TODO: Remove this when done.
-            .deleteRealmIfMigrationNeeded()
+            .schemaVersion(SchemaMigration.SCHEMA_VERSION)
+            .migration(new SchemaMigration())
             .build();
         Realm.setDefaultConfiguration(config);
```

> I am a bit confused about this. If it is a fresh start, the schema should be generated automatically without calling the migration block (No migration exception should be thrown).

Are you saying that `RealmMigration.migrate()` should not even be called? I have confirmed that it _is_ being called even on an initial install of the app.

**Comment by beeender** [comment]
@spl for a fresh install (realm db doesn't exist), the schema will be generated according to the definition of existing `RealmObject`s, and migration should not be called since it is not needed.

Is `setDefaultConfiguration()` called only once? This function is not thread safe.

But it is totally weird `newField` gets inserted by some one.

You can try:
check if the realm file exist (File.exists() ?) before the first time Realm opened for a fresh install.
the realm path can be got from `RealmConfigraution.getPath()`

**Comment by spl** [comment]
@beeender:

> Is `setDefaultConfiguration()` called only once?

Yes, it is only called in the place mentioned above.

> check if the realm file exist (File.exists() ?) before the first time Realm opened for a fresh install.
> the realm path can be got from `RealmConfiguration.getPath()`

Now, something weird is happening that I don't understand. I added logging to `Application.onCreate()` to determine if the Realm DB file existed. But I don't see those log messages at all. I see the exception which happens in our login activity. If I remove the `.schemaVersion()` and `.migration()` from the `RealmConfiguration.Builder`, then I get the exception `RealmMigrationNeededException: RealmMigration must be provided`.

According to the [`Application.onCreate()` documentation](https://developer.android.com/reference/android/app/Application.html#onCreate()):

> Called when the application is starting, before any activity, service, or receiver objects (excluding content providers) have been created.

But I see that other people have reported problems on StackOverflow with `Application.onCreate()` not being called:

* [Log statements not being called in onCreate()](https://stackoverflow.com/questions/13939220/log-statements-not-being-called-in-oncreate)
* [Application onCreate() NOT getting called everytime](https://stackoverflow.com/questions/30260153/application-oncreate-not-getting-called-everytime)

Could it be that `Application.onCreate()` is not getting called? Or could it be that [Logcat is not ready](http://stackoverflow.com/a/7099586/545794)?

_Some more thinking and debugging occurs. I'm leaving the above discussion in the comment for posterity._

Okay, I now see the `Application.onCreate()` logs. I had to disable the “Show only selected application” filter and search for the tag used.

Here is what I wrote:

```java
        final RealmConfiguration config = new RealmConfiguration.Builder(this).build();
        if (new File(config.getPath()).exists()) {
            Log.e(MyApplication.class.getSimpleName(), "RealmConfiguration exists!");
        } else {
            Log.e(MyApplication.class.getSimpleName(), "RealmConfiguration does not exist.");
        }
        Realm.setDefaultConfiguration(config);
```

And I saw that `"RealmConfiguration exists!"` was printed.

I tried something else:

1. Uninstall the app.
2. Power my device off.
3. Power my device on.
4. Install and run.

And I saw that `"RealmConfiguration does not exist."` was printed.

**Comment by beeender** [comment]
@spl even when "RealmConfiguration does not exist." printed, the error still happens?

are you using multi-processes? `Application.onCreate` will be called multi times if you have multi processes in your apk.

Do you have a sticky service for the branch which has `newField`? But that doesn't explain ... the whole apk should be replaced by your master when you do install.

**Comment by spl** [comment]
@beeender:

> even when "RealmConfiguration does not exist." printed, the error still happens?

No, it did not at that point. I had also removed the `.migration()` as mentioned above.

> are you using multi-processes? Application.onCreate will be called multi times if you have multi processes in your apk.

No, we are not using multiple processes. The logs in `Application.onCreate()` were only printed once at app startup.

> Do you have a sticky service for the branch which has `newField`?

I don't think so. That's new to me. We don't override `android.app.Service.onStartCommand()` as described in the [Services guide](https://developer.android.com/guide/components/services.html).

**Comment by spl** [comment]
So, it seems that restarting my device deleted the existing Realm DB file, but uninstalling the app did not?

**Comment by beeender** [comment]
> So, it seems that restarting my device deleted the existing Realm DB file, but uninstalling the app did not?

Sounds like a rom bug ... stock ROM?
How did you uninstall it?

`adb uninstall <pkg-name>` `adb shell pm uninstall <pkg-name>` or through the UI?

Maybe you can verify after uninstall through `adb shell`

```
adb shell
run-as <pkg-name> ls /data/data/<pkg-name>
```

Also worth to check if the process gets killed after uninstallation (we haven't find a rom has this behaviour, but from bug reports we got, it seems some ROM still have the apk process alive after uninstallation/reinstallation)

```
adb shell ps | grep <pkg-name>
```

**Comment by spl** [comment]
@beeender:

> Sounds like a rom bug ... stock ROM?

Yes, direct from Google. No modifications, no rooting.

> How did you uninstall it?
> 
> adb uninstall <pkg-name> adb shell pm uninstall <pkg-name> or through the UI?

I used both the UI and `adb uninstall <pkg-name>` directly. I've also used Android Studio to do the uninstall, and it appears to do `adb shell pm uninstall <pkg-name>`.

> Maybe you can verify after uninstall through adb shell

Unfortunately, it seems that I can't do `run-as <pkg-name>` after uninstalling the package. But I did it after reinstalling the app but before using it, and `find` gave me:

```
/data/data/<pkg-name>
/data/data/<pkg-name>/cache
/data/data/<pkg-name>/code_cache
/data/data/<pkg-name>/code_cache/com.android.opengl.shaders_cache
/data/data/<pkg-name>/shared_prefs
/data/data/<pkg-name>/shared_prefs/com.google.android.gms.measurement.prefs.xml
/data/data/<pkg-name>/files
```

> Also worth to check if the process gets killed after uninstallation (we haven't find a rom has this behaviour, but from bug reports we got, it seems some ROM still have the apk process alive after uninstallation/reinstallation)

I checked and no process was found after uninstalling.

Could it have been caused by a previous exception we had during development of the migration? Could some file have been corrupted and not removed or left lying around somewhere?

**Comment by spl** [comment]
I can't seem to reproduce the problem at the moment. So, if you can think of any problem with Realm or my application, I'd love to know. Otherwise, feel free to close this issue.

Thanks to @beeender for helping me identify the core problem. Much appreciated! 💯

**Comment by beeender** [comment]
@spl No problem!
