### ISSUE TITLE
Behavior of insertToRealm/copyToRealm

### ISSUE THREAD

**Issue by roughboy** [realm/realm-java#3185]
I have question regarding behavior of  insertToRealm/copyToRealm. Let me give an example:

```java
class Dog extends RealmObject
{
String name;
}

class Dog extends RealmObject
{
String name;
RealmList<Dog> dogs;
}

realm.beginTransaction();
Dog dog = new Dog();
dog.name = "dog";
Person person = new Person();
person.name = "person";
person.dogs.add(dog);
realm.insertToRealm(person);
realm.commitTransaction(); 
```
In given example both dog and person will be inserted into realm or do I have to insert dog the same way as person (using insertToRealm/copyToRealm)? How about copyToRealm, does it behave the same?

**Comment by Zhuinden** [comment]
> person.dogs.add(dog);

There's a null pointer exception, so I'd say it behaves the same (crashes with NPE)

**Comment by Zhuinden** [comment]
``` java
``` java
class Dog extends RealmObject {
    String name;
}

class Person extends RealmObject {
    String name;
    RealmList<Dog> dogs;
}

realm.executeTransaction(new Realm.Transaction() {
    @Override
    public void execute(Realm realm) {
        Dog dog = new Dog();
        dog.name = "dog";
        Person person = new Person();
        person.name = "person";
        person.dogs = new RealmList<>();
        person.dogs.add(realm.copyToRealmOrUpdate(dog));
        realm.insertOrUpdate(person);
    }
});
```

The difference between `copy` and `insert` is that `copy` returns a managed proxy instance, while `insert` does not return an object.

**Comment by roughboy** [comment]
> There's a null pointer exception, so I'd say it behaves the same (crashes with NPE)

Yes that's true, I've missed creating new RealmList. 
Nevertheless now I get it - thanks for the fast answer!

**Comment by beeender** [comment]
thanks again and again! @Zhuinden 

@roughboy And let us know if you have further questions!

**Comment by sudhanshugaur4** [comment]
what is a managed proxy instance ??

**Comment by Zhuinden** [comment]
@sudhanshugaur4 it means that instead of being an in-memory object, its field access reads/writes into Realm directly.

You can see this by calling `isManaged()`, but you can also see it from the type because it tends to be called `SomeClassRealmProxy` instead of `SomeClass`.
