### ISSUE TITLE
Realm automatically remove my database content

### ISSUE THREAD

**Issue by tux-world** [realm/realm-java#3189]
I dont know why after some running android application my data in database is lost, and i dont have any data in database :(

my solution for using Realm and close database in all Android activities of fragments is:

    @Override
    protected void onCreate(@Nullable final Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_market_detail);
        realm                            = Realm.getDefaultInstance();
     }

    @Override
    protected void onResume() {
        super.onResume();
        if (realm.isClosed())
            realm = Realm.getDefaultInstance();
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        if (!realm.isClosed())
            realm.close();
    }

i dont have any ```realm.deleteAll();``` in my source code

Realm configuration in class which extended from Application

        byte[] key = new byte[64];
        new SecureRandom().nextBytes(key);
        RealmConfiguration realmConfiguration = new RealmConfiguration
                .Builder(this)
                .name("SignalApplication.db")
                .deleteRealmIfMigrationNeeded()
                .build();

        Realm.setDefaultConfiguration(realmConfiguration);

**Comment by Zhuinden** [comment]
.deleteRealmIfMigrationNeeded()

It's not a bug, you're probably adding fields to your classes or adding new classes, and you didn't specify a migration (and instead just deleted the Realm when migration was needed)

**Comment by tux-world** [comment]
maybe, please let me to check again, Thanks

**Comment by tux-world** [comment]
@Zhuinden Thanks. problem resolved
