### ISSUE TITLE
java.lang.IllegalArgumentException: Object not managed by Realm, so it cannot be removed.

### ISSUE THREAD

**Issue by yfsx** [realm/realm-java#3191]
hi, i try to delete object from realm and i got this error

>    java.lang.IllegalArgumentException: Object not managed by Realm, so it cannot be removed.

this is my model which i want to deleteFromRealm()

```java
    public class User extends RealmObject {
        @PrimaryKey
        private int userId;
        private String email;
        private String fullName;
        private String gender;
        private String phoneNumber;
        private String companyCode;
        private int roleId;
        private String roleName;
        private int groupId;
        private String groupName;
        private RealmList<RealmInteger> moduleIds = new RealmList<>();
        private RealmList<RealmInteger> menuIds = new RealmList<>();
        private RealmList<RealmInteger> pageIds = new RealmList<>();
        private boolean allowOutgoing =true;
        private boolean allowIncoming =true;
        public User() {
        }
    }
```

what i tried is 
```java
{
        User currentUser = getCurrentUser();
        realm.getRealm().beginTransaction();
        currentUser.deleteFromRealm();
        realm.commitTransaction();
}
```

thanks

**Comment by stk1m1** [comment]
Hi @yfsx,

You cannot delete an object that's neither created by nor queried from Realm instances. They are called unmanaged objects. For example the `User currentUser` seems to be spawned with `new User()`, which is an unmanaged object.

**Comment by yfsx** [comment]
Hi @stk1m1 , thanks for your reply

i think i got a solution inspired from your reply. yeay!
it seems my currentUser is saved on local variable, so i call realm query to recall currentUser data and success deleted from realm

many thanks for you!
