### ISSUE TITLE
copyToRealmOrUpdate overrite all my DB.

### ISSUE THREAD

**Issue by mjliu** [realm/realm-java#3192]
@beeender

this is my DB .
"game": {
			"id": "578c8acd6be3ff006ce6adc4",
.....
			"team": {
				"id": "5780acbaa341310061bcef31
				"members": [{
					"name": "朕",
					"username": "t8tgardym2xhib67fcgfooyer",
					"avatar": "http://ac-tSyVzkMT.clouddn.com/3ca9db64edcd32d86e26.jpg?imageView2/2/w/120",
......

when I get Response's game
			"id": "57833f5d8ac2470061fae5bf",
			"team": {
				"id": "5780acbaa341310061bcef31",
				"name": "mjliu",
				"avatar": "",
				"presetAvatar": "11",
				"creatorId": "5760f95d80dda4005f6ac839",
				"membersCount": 8,
				"createdAt": 1468050618084,
				"updatedAt": 1468828402413
			},
.....
then I update game info.
realm.copyToRealmOrUpdate(object);

I found that my DB is replaced all by response's game .I can't find my "members".

what should I do.

**Comment by beeender** [comment]
What does "I found that my DB is replaced all by response's game ." mean? I don't quite get what the problem is...

**Comment by Zhuinden** [comment]
`copyToRealmOrUpdate` overwrites the object in the Realm that has the same primary key if it's already in the Realm.

If you receive partial data from your API, then you need to find the object yourself, and append the new elements to the RealmList.

I'm just guessing at your problem, though.

**Comment by mjliu** [comment]
@Zhuinden 
you mean is find my local DB and merge API then copyOrUpdate?

**Comment by Zhuinden** [comment]
@mjliu yes, that's exactly what I mean

**Comment by mjliu** [comment]
@Zhuinden 
OK  I know,thank you .
