### ISSUE TITLE
Cannot wait for changes in IntentService

### ISSUE THREAD

**Issue by Zhuinden** [realm/realm-java#3193]
#### Goal

> What do you want to achieve?

Wait for changes on a background thread created by an IntentService

#### Expected Results

Be able to wait for change and update

#### Actual Results

Cannot wait for changes on a looper thread

#### Steps & Code to Reproduce

The code in [BaseRealm](https://github.com/realm/realm-java/blob/master/realm/realm-library/src/main/java/io/realm/BaseRealm.java#L273-L275) explicitly states that if you have a looper, then you cannot wait for change, even though  `RealmChangeListener`s don't work on IntentServices.

#### Code Sample

I'm asking because of [this SO question](http://stackoverflow.com/q/38396846/2413303).

#### Version of Realm and tooling
Realm version(s): 1.1.0

Android Studio version: 2.1.2

Which Android version and device: 6.0.1

**Comment by Zhuinden** [comment]
Related: https://github.com/realm/realm-java/issues/2875

**Comment by stk1m1** [comment]
@Zhuinden 

If my memory serves me correct, the main reason `waitForChange()` is provided is b/c there is no `Looper` mechanism in non-Looper thread that we cannot nicely provide changes via `ChangeListener`. 

I'm not disagreeing that there might be use cases where `waitForChange()` would have some use on Looper thread, but we put [far more efforts](https://github.com/realm/realm-java/blob/master/realm/realm-library/src/main/java/io/realm/HandlerController.java) in ChangeListeners for smooth experience. 

I'll keep this issue open as a discussion if you're to execuse me.

**Comment by beeender** [comment]
I am not quite sure how do we solve this right now, Some investigation needed first.

**Comment by zaki50** [comment]
Is it possible to allow to use `waitForChange()` on Looper thread where `auto refresh` is disabled?
If possible, that might help to solve this issue.

@realm/java

**Comment by Zhuinden** [comment]
@zaki50 but doesn't IntentService looper thread return `auto refresh` true?

**Comment by cmelchior** [comment]
It doesn't make sense to wait for changes in an IntentService. Its purpose is specifically to execute a list of jobs and then quit. Having non-blocking async methods as part of its execution is against what it is designed for.

That said, I fully agree that Realm right now does not handle this properly. The reasons are described in #2875.

I'll close this as a duplicate, but I think we should bump #2875 to P1 as well. The problem has come up enough times that implementing the heuristic would make sense.
