### ISSUE TITLE
Initialize RealmConfiguration by filename

### ISSUE THREAD

**Issue by apurvagoyal** [realm/realm-java#3194]
I would like to search RealConfiguration by filename and if it exists then load it. Currently there is no way to achieve it. If I specify the folder name in RealmConfiguration constructor, then the filename by default is always default.realm. 

     private boolean doesRealmExists(String username){

        try{
            SharedPreferences prefs = PreferenceManager.getDefaultSharedPreferences(this);
            String filePath=prefs.getString(getString(R.string.realm_file_path_key),null);
           if(Strings.isNullOrEmpty(filePath))
               return false;
            String fullFilePath=filePath + File.separator + username + ".realm";
            File file = new File(fullFilePath);
            if(!file.exists())
                return false;
            File folder=new File(filePath);

            RealmConfiguration realmConfiguration = new RealmConfiguration.Builder(folder)
                    .name(username + ".realm")
                    .build();
            if(realmConfiguration!=null)
                return true;
        }
        catch (NullPointerException ex){
            return false;
        }

        return false;

    }
    private void setRealmConfiguration(String username){
        //check if the configuration with same username exists or not
        boolean doesRealmExists=doesRealmExists(username);
        if(!doesRealmExists){
            RealmConfiguration realmConfiguration = new RealmConfiguration.Builder(this)
                    .name(username + ".realm")
                    .build();
            Realm.setDefaultConfiguration(realmConfiguration);
            //save the realm default path
            SharedPreferences prefs = PreferenceManager.getDefaultSharedPreferences(this);
            SharedPreferences.Editor editor = prefs.edit();
            String realFilePath=getRealmFilePath();
            if(!Strings.isNullOrEmpty(realFilePath)){
                editor.putString(getString(R.string.realm_file_path_key), getRealmFilePath());
                editor.commit();
            }

        }
    }

    private String getRealmFilePath(){
        String path=Realm.getDefaultInstance().getPath();
        if(!Strings.isNullOrEmpty(path)){
            File file=new File(path);
            if(file.exists())
                return file.getParent();
        }
        return null;
    }

Realm version(s): 0.91.0

Android Studio version: 2.1.1

Which Android version and device: : emulator, version 23.

**Comment by beeender** [comment]
I think http://stackoverflow.com/questions/38447310/search-realmconfiguration-by-name-and-use-it is the same question?

`RealmConfigration` is not a real thing exists on the disk, it is only used to build a Realm file.
So I think you need to check the Realm file existence instead. 

```java
File realmFile = new FIle(realmConfig.getPath());
return realmFile.exists();
```

**Comment by apurvagoyal** [comment]
Thanks! yes its the same question. Can you then use realmFile to load a particular configuration? I have a bunch of users using the same Android device. Each user has a different set of data to work with. How can I use different configuration file for each user?

**Comment by beeender** [comment]
Let's keep the conversation on SO, it is more visible for everybody.
http://stackoverflow.com/questions/38443688/realm-configuration-management
