### ISSUE TITLE
Realm messes up the order of actions in transaction (possibly)

### ISSUE THREAD

**Issue by mbberezovsky** [realm/realm-java#3195]
#### Goal

My application creates a la ERP documents with rows of data (to post it to ERP later on).
I create/modify document in a single transaction.
To make it simple (and faster) i do not check each row for changes but clear them all (first) and (then) save changed set ( i believe most document oriented systems work this way).
I store data in a relational way with rows stored separated having document id as "foreign key".

#### Expected Results
edited document contains changed rows of data after transaction is committed.

#### Actual Results
There is no exception raised but in result sometimes i receive as a result documents containing no rows, like if first rows have been added and then erased.

#### Steps & Code to Reproduce
I can't debug it deeply as committing transaction proceeds to native methods which are neither de-compiled nor debuggable (or i don't know how).

#### Code Sample
Operation - is a document, actions - are document rows, i renamed them as i was porting another authors app to Realm from ORMLite and so i don't get messed with different classes by the same names.
```java
               OperationDAO dao = new OperationDAO(getActivity());
	        dao.BeginTransaction();
	        // first have to check if previous rows are present and delete them
	        if (model.getUid() != null)
	        {
		        OperationObject realmDocument = dao.FindById(model.getUid());
		        if (realmDocument != null)
			        dao.Clear(model.getUid());
	        }
            try {
                OperationObject realmDocument = dao.AddOrUpdate(model.getUid(), document.getSalePoint().getId(), document.getType(), false, false, model.getComment());
                EquipmentDAO dao1 = new EquipmentDAO(getActivity());
                if (realmDocument != null) {
	                // so there is the empty operation, save its actions now
	                List<EquipmentView> list = model.getEquipments();
	                for (EquipmentView e : list) {
		                // check if equipment is existent or new
		                EquipmentObject realmEquipment = dao1.FindByValue(EquipmentObject.PKEY, e.getBarcode());
		                if (realmEquipment == null) {
			                // new - gotta save it first to Realm
			                realmEquipment = dao1.AddOrUpdate(e.getBarcode(), e.getModel(), document.getSalePoint().getId());
		                }
		                // TODO Save eq location change
		                if (!model.getSalePoint().getId().equals(realmEquipment.Location)) {
			                dao1.AddOrUpdate(e.getBarcode(), e.getModel(), document.getSalePoint().getId());
		                }
		                // and action
		                dao.AddOrUpdateAction(realmDocument.Id, realmEquipment.Barcode, e.getLonLat().getLat(), e.getLonLat().getLon(), e.getPhoto1(), e.getPhoto2(), e.getPhoto3(), e.Comment);
	                }
	                dao.CommitTransaction();
	                // control check!
	                int temp = dao.GetActions(realmDocument.Id).size();
	                if (temp == 0) // somehow actions have not been saved
	                {
		                Toast.makeText(getActivity(), getString(R.string.text_document_save_failed), Toast.LENGTH_LONG).show();
		                dao.Close();
		                return;
	                } // even if it passes control check i've added - still somehow rows are empty upon completion. 
// And the issue appears with some latency when app sends documents/or user tries to browse it.
                    Toast.makeText(getActivity(), getString(R.string.text_document_save_success), Toast.LENGTH_LONG).show();
                    dao.Close();
                }
                else
                {
                    Toast.makeText(getActivity(), getString(R.string.text_document_save_failed), Toast.LENGTH_LONG).show();
                    dao.CancelTransaction();
	                dao.Close();
                    return;
                }
            }
            catch (Exception e)
            {
	            e.printStackTrace();
                dao.CancelTransaction();
	            dao.Close();
                Toast.makeText(getActivity(), getString(R.string.text_document_save_failed), Toast.LENGTH_LONG).show();
                return;
            }
```
hope methods name speak themselves so you don't need any nested code.

#### Version of Realm and tooling
Realm version(s): ?
classpath 'io.realm:realm-gradle-plugin:1.1.0'

Android Studio version: ?
AS 2.1.2

Which Android version and device: ?
plenty of them, mostly with Android API 16-17

**Comment by mbberezovsky** [comment]
well i'm not too experienced with posting github issues, it seems it totally  messed up code formatting

**Comment by beeender** [comment]
@mbberezovsky Check the doc [here](https://guides.github.com/features/mastering-markdown/)  for code formatting which is quite easy!

**Comment by mbberezovsky** [comment]
it seems i managed with it

**Comment by beeender** [comment]
I cannot find the line where you get the `RealmResults`. But if you are talking about the `RealmResults` is not updated after commit transaction then you probably need to check the doc [here](https://realm.io/docs/java/latest/#notifications). If you get the `RealmResults` before the transaction committed, it will be updated in the next UI loop. Or you could choose to re-query to get a new `RealmResults` after committing transaction which contains the latest changes in the transaction.

**Comment by mbberezovsky** [comment]
`int temp = dao.GetActions(realmDocument.Id).size();` 
this code gets `RealmResults` and obviously checks for its size.
later in app i use strictly the same method to get documents rows.
full final (after some wrappings from one DAO to another) code is:
```
	public RealmResults<T> ListByValue(String pIdProperty, Object pValue, Class<T> pClass)
	{
		if (pValue instanceof String)
			return  AppRealm.where(pClass).equalTo(pIdProperty, (String)pValue).findAll();
		else if (pValue instanceof Integer)
			return AppRealm.where(pClass).equalTo(pIdProperty, (int)pValue).findAll();
		else if (pValue instanceof Boolean)
			return AppRealm.where(pClass).equalTo(pIdProperty, (boolean)pValue).findAll();
		else
			return null;
	}

```

**Comment by beeender** [comment]
Since you wrapped all the realm function calls, it is a bit difficult to tell what is going on the.

Is the `realmDocument` supposed to be stored by this line? If yes, can you share the source code of that function?
`// and action
                        dao.AddOrUpdateAction(realmDocument.Id, realmEquipment.Barcode, e.getLonLat().getLat(), e.getLonLat().getLon(), e.getPhoto1(), e.getPhoto2(), e.getPhoto3(), e.Comment);`

**Comment by mbberezovsky** [comment]
@beeender this line of code saves document row, where `realmDocument.Id` is the Id of document rows belong to

**Comment by mbberezovsky** [comment]
`	public ActionObject AddOrUpdateAction(int pDocumentId, String pEquipment, double pLat, double pLon, String pPhoto1, String pPhoto2, String pPhoto3, String pComment)
	{
		ActionDAO dao = new ActionDAO(DAOContext);
		return dao.AddOrUpdate(pDocumentId, pEquipment,pLat,pLon, pPhoto1, pPhoto2, pPhoto3, pComment);
	}`
// dao.AddOrUpdate() :
`	public ActionObject AddOrUpdate(int pDocumentId, String pEquipment, double pLat, double pLon, String pPhoto1, String pPhoto2, String pPhoto3, String pComment) {
		ActionObject object = new ActionObject();
		object.DocumentId = pDocumentId;
		object.Lon = pLon;
		object.Lat = pLat;
		object.Comment = pComment;
		object.Photo1 = pPhoto1;
		object.Photo2 = pPhoto2;
		object.Photo3 = pPhoto3;
		object.Equipment = pEquipment;
		object.Id = getNewId();

		return super.AddOrUpdate(object);
	}
`

// super method (of general dao class which contains most similar method for many classes app has).
    public T AddOrUpdate(T pEntry) {
	    T res = null;
	    try {
		    if (InTransaction)
			    res = AppRealm.copyToRealmOrUpdate(pEntry);
		    else {
			    AppRealm.beginTransaction();
			    res = AppRealm.copyToRealmOrUpdate(pEntry);
			    AppRealm.commitTransaction();
		    }
	    } catch (Exception e)
	    {
		    e.printStackTrace();
	    }
	    finally
	    {
		    return res;
	    }
	}

**Comment by beeender** [comment]
I saw you are catching `Exception` everywhere, did you see any of them in the logcat?

**Comment by mbberezovsky** [comment]
during the migration stage - probably (there were tons of code to migrate), so i added try...catches, but not now. Application throws no exceptions at all. I still have printStackTrace() just in case. But days of testing adding and saving data didnt raised any exception. Still i have occasional issues (like that). There's another one issue users experience on constant basis. But i report it later i guess. It also happens randomly.

**Comment by beeender** [comment]
Could you please add some debug code in `AddOrUpdateAction` like 'int temp = dao.GetActions(realmDocument.Id).size();` to see if the record has been saved there?

**Comment by mbberezovsky** [comment]
I am not sure if it's correct in any way to check for saved or not inside the transaction. Doesn't it actually return like some kind of `future` or `promise`?
What exactly do you want to check? If it returns valid `ActionObject` as `RealmObject`? Okay, i'll try to check it out.

**Comment by beeender** [comment]
I just want to know `AppRealm.copyToRealmOrUpdate(pEntry);` gets called with correct param without any issues.

**Comment by mbberezovsky** [comment]
Oh, it seems i found the problem.
Actions are added and its all fine, the problem seems to be in my get new id method:
`object.Id = getNewId();`
which was 
```
	public int GetNewId(Class<T> pClass)
	{
		return (int) Count(pClass) + 1;
	}
```
when i was deleting rows, their count was also reducing so id provided might actually cross the id of already existing row of another document. This is why missing rows were appearing afterwards, not during document saving (and they miss form other documents).

Speaking of which is there any correct way to auto increase `@PrimaryKey int` ?
I got this example from stackoverflow, which it seems has a flaw itself.
