### ISSUE TITLE
Realm crash in background jobs

### ISSUE THREAD

**Issue by kuno** [realm/realm-java#3198]
My app runs several background jobs (running in IntentService) to sync the  data with server periodically. Once got the http response, the app save those data into realm.

Some of my users (small number) are experiencing crash when try to open the realm instance.

Sorry, since I am not able to reproduce the crash by myself, I can only show the logs from real users. which their app has been obfuscated.

```log
Fatal Exception: java.lang.IllegalArgumentException: Illegal Argument: Invalid format of Realm file.
       at io.realm.internal.SharedGroup.createNativeWithImplicitTransactions(Unknown Source)
       at io.realm.internal.SharedGroup.ˊ(Unknown Source:95)
       at io.realm.internal.SharedGroup.<init>(Unknown Source:74)
       at ᵑ.<init>(Unknown Source:49)
       at ɼ.<init>(Unknown Source:81)
       at io.realm.Realm.<init>(Unknown Source:140)
       at io.realm.Realm.ˋ(Unknown Source:240)
       at io.realm.Realm.ˊ(Unknown Source:220)
       at т.ˊ(Unknown Source:126)
       at io.realm.Realm.ˉ(Unknown Source:166)
       at com.my.app.core.service.CardsSyncService.saveCardsToRealm(Unknown Source:34)
       at com.my.app.core.service.CardsSyncService.onGetCardsSuccess(Unknown Source:105)
       at com.my.app.core.manager.GatewayApiManager$7.onResponse(Unknown Source:513)
       at 〳$ˊ.ˋ(Unknown Source:133)
       at ﱠ.run(Unknown Source:32)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:831)
``` 

What might cause this ? It is because those periodic jobs are sharing the same interval (5 mins), so there are mightbe a race condition when serval  jobs want to write to realm at same time ?

I have been upgraded realm from `1.0.0` to `1.1.0`, but did not fix this issue.

**Comment by beeender** [comment]
1. Do you use Realm encryption?
2. Do you use multi-processes in your app?

**Comment by Zhuinden** [comment]
If your periodic task is achieved by a BroadcastReceiver that is started with `android:process=":remote"`, then you are accessing the Realm file from two processes, and that is not stable.

**Comment by kuno** [comment]
@beeender 

1, yes, I am using encryption, but the key never changed.

2, I am using the library [android-jobs](https://github.com/evernote/android-job) to schedule IntentService to run the jobs, so I dont think  I am using process.

And most importantly, this issue only occurs on about 20 users, but with very high  frequency, 25k in the last 3 weeks. So it might be device specific ?

**Comment by Zhuinden** [comment]
@kuno android-jobs uses [android:exported=false](https://github.com/evernote/android-job/blob/master/library/src/main/AndroidManifest.xml) on its services/broadcast receivers, so I don't think it's multiprocess either.

**Comment by beeender** [comment]
@kuno Really sorry for the late reply. 
1. What kind of devices have this problem?
2. Is it only happened to the Service? Do you see similar crash for your activity?

**Comment by Zhuinden** [comment]
@beeender funny thing actually, in 0.88.0-SNAPSHOT (yeah I know, not very conclusive -_-) I managed to get this crash in crash reporting even though the only thing I did with that specific Realm was open it in `onCreate()` and close it in `onDestroy()`. Never wrote into it or anything.

**Comment by beeender** [comment]
@Zhuinden were you using encryption at that time?

**Comment by Zhuinden** [comment]
@beeender nope

**Comment by kneth** [comment]
@kuno What do you use the Android Job library for?

**Comment by kneth** [comment]
@kuno Have you seen this crash recently?

**Comment by Zhuinden** [comment]
It's also interesting that that happened to me on a Realm only opened and closed in onCreate and onDestroy, but I've only seen this crash once and it was an old version. 

Still, it would be nice if there was a way to delete the Realm automatically on unrecoverable errors

**Comment by kneth** [comment]
@Zhuinden An error might originate from a programming error which is triggered in rare cases only. Silently deleting Realm files can be a dangerous road to enter as it might mask such errors, and the developer will never be able to find them.

**Comment by kneth** [comment]
@kuno I'm closing the issue. You are welcome to reopen or create a new if the issue surfaces again.
