### ISSUE TITLE
encrypt a local database

### ISSUE THREAD

**Issue by boywangqin** [realm/realm-java#3201]
我想用Realm加密本地数据库，然后用Realm使用加密的本地数据。不知道有没有什么办法

**Comment by boywangqin** [comment]
android phone

**Comment by beeender** [comment]
有啊！参考 https://realm.io/cn/docs/java/latest/#section-28

尽量用英文提问可能效果会更好哦，因为中文太难，这里能懂的人不多 😁

**Comment by boywangqin** [comment]
thank you

**Comment by stk1m1** [comment]
hi @boywangqin 

When this issue arises again, please reopen this. I am closing it for now.
