### ISSUE TITLE
Static Fields completely ignored.

### ISSUE THREAD

**Issue by dlillard** [realm/realm-java#3205]
#### Goal

>Make a RealmObject class with a static field

#### Expected Results

> Be able to use static fields with Realm. I believe #934 was supposed to add support for this.

#### Actual Results

>  Static fields are not recognized as persistable. You can see this in [ClassMetaData](https://github.com/realm/realm-java/blob/master/realm/realm-annotations-processor/src/main/java/io/realm/processor/ClassMetaData.java)'s categorizeClassElements() function. 

#### Steps & Code to Reproduce

>A RealmObject class with one static field will throw a "must have at least 1 persistable field" error. Adding non static fields allows compilation.

#### Code Sample
```
public class Preferences extends RealmObject {
     public static RealmList<RealmString> preference;
}
```

#### Version of Realm and tooling
Realm version(s): 1.1

**Comment by Zhuinden** [comment]
You misunderstood the pull request. That change allows you to declare static fields in your Realm object, as in the processor doesn't say "you cannot have static fields in your Realm object". A static field doesn't belong to an instance of the class, so it is not persisted along with the class either. 

``` java
     Set<Modifier> modifiers = variableElement.getModifiers();
     if (modifiers.contains(Modifier.STATIC)) {
           continue; // completely ignore any static fields
     }
```

**Comment by stk1m1** [comment]
Hi @dlillard

Has @Zhuinden's comment helped you?

**Comment by dlillard** [comment]
Ah, yes I see the difference now. I know static fields do not belong to an instance, but what is the feasibility of including static fields in Realm? Would this functionality be too tangential to the regular use case of Realm objects and such? Are there other issues with this idea?
My example use case is persisting a user preference, which there is only one of across the app.

**Comment by stk1m1** [comment]
@dlillard 

What could be your use case? It is highly unlikely that static object/list of object would be supported. If it is to be a managed objects/list of objects, any thread could approach and change the value at their whim. That would compromise the overall architecture of Realm, which promotes per thread, isolated operations for performance and safety.

**Comment by Zhuinden** [comment]
@dlillard to be fair, it's quite easy to create a new RealmObject that stores the static fields, and store only one instance of that RealmObject in the Realm. If possible, I'd probably add it to the Realm with `initialData(Realm.Transaction)`.

**Comment by dlillard** [comment]
Okay, thank you for the work around I'm completely new to Realm.

**Comment by stk1m1** [comment]
@dlillard 

I'll close this issue for now. When you have other issue, please feel comfortable to open another one. Thanks!
