### ISSUE TITLE
can't find the object in anohter thread

### ISSUE THREAD

**Issue by gushoubang** [realm/realm-java#3206]
I save the object in UI thread,but I sometime can query the object in another thread and some time can't query the object,I can query the object in UI thread

**Comment by Zhuinden** [comment]
Do you open the Realm instance AFTER that transaction on the UI thread is complete? 

Then again, if you expect to update a non-looper thread, you should use `waitForChange`.

**Comment by stk1m1** [comment]
In addtion to @Zhuinden's comment, you can also use `RealmChangeListener()` to track what has change.

Most of all, it would immensely helpful if you could fill up [our issue template](https://github.com/realm/realm-java/blob/master/CONTRIBUTING.md#filing-issues) for the best possible support. 😄

**Comment by Zhuinden** [comment]
@stk1m1 he did say he can query on the UI thread but not the another thread, which means he cannot use change listeners there because it's most possibly not a looper threadm

**Comment by stk1m1** [comment]
@Zhuinden 
I'm sorry. You are correct. I miss-read his description.

@gushoubang 
Could you share your code with us to support you in the best possible way? Thanks!

**Comment by gushoubang** [comment]
@stk1m1 
Ok I know the reason,because it not save into the realm

**Comment by stk1m1** [comment]
@gushoubang 

I'm closing this issue for now.

**Comment by gushoubang** [comment]
@stk1m1 ok
