### ISSUE TITLE
Andorid Realm get model fields on loop clause

### ISSUE THREAD

**Issue by tux-world** [realm/realm-java#3207]
this below class in my database model on Relam object

```
public class ModelMarketBanners extends RealmObject {
    @PrimaryKey
    private String id;
    private String marketId;
    private String imageFileName;
    private String title;
}
```

as far as i know i can get model fields data by class getter such as getId(), but i want to get filed name instead of class getter methods on loop clause, for example using for to show all class fields such as id or marketId, how can i do that?

i want to get all fileds data and if which one isn't empty attach layout with that data, instead of programing multi line to check and attaching that

for example:

```
    for(int i=0; i> model.field_count; i++){
         if (model.field.lenght() > 0) Log.v("data is: ", model.field);
    }
```

instead of

```
    SampleModel model = realm.where(SampleModel.class).findfirst();
    if(model.getId().lenght() > 0)
       Log.v("data is",model.getId());
    if(model.getmarketId().lenght() > 0)
       Log.v("data is",model.getmarketId());
    if(model.getImageFileName().lenght() > 0)
       Log.v("data is",model.getImageFileName());
```

**Comment by stk1m1** [comment]
@tux-world 

You can use `RealmModel` to achieve what you're looking for. 

For example,
```java
@RealmClass
public class ModelMarketBanners implements RealmModel {
    @PrimaryKey
    public String id;
    public String marketId;
    public String imageFileName;
    public String title;
}
```

You can also find more info here <https://realm.io/docs/java/latest/#realmmodel-interface>

**Comment by tux-world** [comment]
@stk1m1 ok, i'm changed class to 
```
@RealmClass
public class ModelProductsDetailInformation implements RealmModel, Parcelable {
```
now i could  not find on your introduced link how can i get class fields, this solution doesnt work on all version of android:

```
for (Field field : ModelProductsDetailInformation.class.getDeclaredFields()) {
    for (Method method : ModelProductsDetailInformation.class.getMethods()) {
        if ((method.getName().startsWith("get")) && (method.getName().length() == (field.getName().length() + 3))) {
            if (method.getName().toLowerCase().endsWith(field.getName().toLowerCase())) {
                try {
                    Object value = method.invoke(information);
                    if (!TextUtils.isEmpty(String.valueOf(value))) {
                        attachProductDetailOnChild(value.toString(), field.getName().toLowerCase());
                    }
                } catch (IllegalAccessException e) {
                } catch (InvocationTargetException e) {
                    e.printStackTrace();
                }
            }
        }
    }
}
```

**Comment by stk1m1** [comment]
@tux-world 

The link might not be accessble as it would have been blocked. We talked about this last time. 😅 
Plus,  I see your question is getting tracktion on SO here <http://stackoverflow.com/questions/38540335/java-get-class-fields-on-loop-clause-and-check-value>

Would you mind if I ask you to consult with users? I'm sure this question finds more helps there. Please pay attention to provide detailed information on the version of Android as well.

**Comment by tux-world** [comment]
@stk1m1  yes your right, i can use library documentation, no problem, but after opening that link i can't find solution about retrieve class fields, accepted post on SF doesnt work on android version 4.X

**Comment by stk1m1** [comment]
That seems be little odd. If something works on older version of android, it should work on 4.x.
Have you checked the visibility of the fields?  i.e. `private` -> `public`?

**Comment by tux-world** [comment]
@stk1m1 Oh no sir !! it worked on api level >4 not <5, then i cant use that soluton on android version 4.0, but work fine on api level >4

**Comment by tux-world** [comment]
@stk1m1 after clean up and rebuild project, problem resolved, Thanks sir

**Comment by stk1m1** [comment]
@tux-world 

I'm glad it works with you. 😄
