### ISSUE TITLE
Realm 1.1.0 jar?

### ISSUE THREAD

**Issue by HeXiZhang** [realm/realm-java#3211]
We couldn't download the dependecy package for we could not concect to the extranet.So could you please provide the latest jar dependency package for us if you have it.Thank you very much.

**Comment by stk1m1** [comment]
Hi @HeXiZhang 

Realm is consisted of several packages that it would be more practical to build yourself in that case. You can build Realm yourself following [the guide](https://github.com/realm/realm-java/#building-realm). 

When Realm is built, you can use `mavenLocal()` repository in your dependency declaration as illustrated here in [example build.gradle](https://github.com/realm/realm-java/blob/master/examples/build.gradle).

**Comment by stk1m1** [comment]
@HeXiZhang 

Have you successfully built Realm for you?

**Comment by HeXiZhang** [comment]
I didn't build realm,but set https agent on the android studio,and then successfully downloaded the dependency package of realm.Please be informed it works very well.Thanks for your support!

**Comment by HeXiZhang** [comment]
I didn't build realm,but set https agent on the android studio,and then successfully downloaded the dependency package of realm.Please be informed it works very well.Thanks for your support!

**Comment by stk1m1** [comment]
@HeXiZhang 

Good to hear that! I'm closing the issue for now. If you have the same issue in the future, please reopen it.
