### ISSUE TITLE
RxJava, expose results as Single

### ISSUE THREAD

**Issue by cvoronin** [realm/realm-java#3213]
#### What

I would like to have ability to get result of a query not only as Observable, but also as [Single](http://reactivex.io/documentation/single.html)

#### Why

Our Retrofit API often returns results as Single. 
If I had the ability to get query results as Single, it were possible to use those results in [concat:](http://reactivex.io/documentation/operators/concat.html)

```
Single
  .concat(getFromRealm(), getFromServer())
  .first()
  .subscribe(...)
```

Now I have to use something like this:
```
    fun loadAll(): Single<List<Item>> {
        return Single.just(
                with(realmProvider.get()) {
                    use { realm ->
                        realm.copyFromRealm( realm.where(Item::class.java).findAll() )
                    }
                }
        )
    }
```

**Comment by stk1m1** [comment]
Hi @cvoronin 

Thanks for the suggestion and I have to mention that someone already suggested Similar issue at #2272. All the related proposals are being tracked in #2126. Would you mind if I ask you to copy your issue to #2126? Copy and paste would work just fine.

I'll close this issue as a duplicate for now. Thanks!

**Comment by stk1m1** [comment]
I'm closing this issue as being copied to #2126.

**Comment by Zhuinden** [comment]
You're having these problems because you're concating the server response with the Realm observation, rather than keeping them two separate streams of events.
