### ISSUE TITLE
findAll() and findAllAsync() get different result for same query.

### ISSUE THREAD

**Issue by A86S** [realm/realm-java#3214]
I have apply findAll() and findAllAsync() on same query but getting different result.

Query 1 : realm.where(Model.class).equalTo(ModelColumns.IS_FAV_USER, "yes", Case.INSENSITIVE).findAll().sort(ModelColumns.USERNAME, Sort.ASCENDING);
*result - 0

Query 2 : realm.where(Model.class).equalTo(ModelColumns.IS_FAV_USER, "yes", Case.INSENSITIVE).findAllAsync().sort(ModelColumns.USERNAME , Sort.ASCENDING);
*result - 1

Android Studio Version : 2.2 Preview 5
Realm Version : 1.1.0 

please let me know , am i doing something wrong here ? 

Thanks.

**Comment by Zhuinden** [comment]
You should use `findAllSorted()` and `findAllSortedAsync()` instead of `findAll().sort()` and `findAllAsync().sort()`.

**Comment by A86S** [comment]
ok thanks it working perfectly with findAllSorted and findAllSortedAsync() but having different result while using findAll().sort() and findAllAsync().sort().

**Comment by A86S** [comment]
@Zhuinden i have on query which i have posted here #1080 can you please guide me over that. 

Thanks
