### ISSUE TITLE
Add quotes around field names in RealmProxy exceptions

### ISSUE THREAD

**Issue by spl** [realm/realm-java#3217]
**Feature Request**

#### Goal

Read an exception regarding a field and determing which field is being referred to. The field's name is `code`.

#### Expected Results

Immediate recognition that the problematic field is `code`.

#### Actual Results

Temporary confusion about message.

It is arguable that `code` is a bad name for a field, but I'm sure there are others that are just as problematic.

I ask that you simply change the exception string from:

```java
throw new IllegalArgumentException("Trying to set non-nullable field code to null.");
```

to:

```java
throw new IllegalArgumentException("Trying to set non-nullable field 'code' to null.");
```

This is the error I came across, but you may want to go through other generated error messages to see if there is a similar issue.

**Comment by stk1m1** [comment]
@spl

Thanks for the report! Since it's small, we'll fix it soon!
