### ISSUE TITLE
Realm Object not updating Correctly

### ISSUE THREAD

**Issue by SahajRana** [realm/realm-java#3220]
#### Goal

> Update Realm object

#### Expected Results

> To get updated with the provided fields/data

#### Actual Results

>  The update is somewhat not persistent and doesn't save it as required.
>  As I checked it By putting log for what is happening this is what i got,

````java
07-28 05:51:51.256 7482-7482/com.rana.sahaj.myyu E/SahajLOG18: hashaname String jjfjuffrGgu
07-28 05:51:51.266 7482-7482/com.rana.sahaj.myyu E/SahajLOG18: resultChecking [ToTal_ProfileModelRealmClass = [{userEmailKey:sahaj9917730102},{userNAME:Sahaj Rana},{picurl:lh5.googleusercontent.com},{gplusURL:plus.go},{userEmail:sahaj9917},{picurl50DP:lh5.g?sz=50},{course:B.Tech},{year:2010-2014},{branch:Information Technology},{campus:Meerut Institute Of Engineering And Technogy},{hashname:jjfjuffrGgu},{picOfflineName:jjfjuffrGgu},{birthday:null},{quote:null}]]
07-28 05:51:55.526 7482-7482/com.rana.sahaj.myyu E/SahajLOG18: hashaname String jjfjuffrGgu
07-28 05:51:55.536 7482-7482/com.rana.sahaj.myyu E/SahajLOG18: resultChecking [ToTal_ProfileModelRealmClass = [{userEmailKey:sahaj9917730102},{userNAME:Sahaj Rana},{picurl:lh5.googleusercontent.com},{gplusURL:plus.go},{userEmail:sahaj99177},{picurl50DP:lh5.g?sz=50},{course:course},{year:2010-2014},{branch:branch},{campus:campus},{hashname:jjfjuffrGgu},{picOfflineName:jjfjuffrGgu},{birthday:null},{quote:null}]]

````
In this log I have checked two times for the result the first time it shows the updated result but next time, it shows some alterations like ``{branch:branch},{campus:campus}`` which i never entered and I have checked it many times. I don't get it why is it happening.

Here's the Gist of it
<https://gist.github.com/SahajRana/fe4c5247019891c9f690b320a8f3bb3e#file-editprofileactivity-java-L46>

Line 46

**Comment by stk1m1** [comment]
@SahajRana 

Thanks for the detailed report.  Unfortunately, the gist page says `404 page not found`. Could you please update the gist with the version of Realm you're using? Thanks!

**Comment by SahajRana** [comment]
ya u have to copy paste it.. thats how it is working

**Comment by stk1m1** [comment]
@SahajRana 

Please refrain yourself from using `<script>` tag as it might trigger malicious activity. Github would take a good care of anything that would result in irreversible output, but we do not intend to misguide our unsuspecting users to fall in 3rd party scheme of any sort.

**Comment by Zhuinden** [comment]
@SahajRana you should `close()` every Realm instance that you open with `Realm.getInstance()`.

**Comment by stk1m1** [comment]
@SahajRana 

It's most likely that you are changing the values of `branch` and `campus` somewhere where you query `ToTal_ProfileModelRealmClass` with the same property as you search in `addOnFirebase()`. It would be more helpful if you could share other places, where `ToTal_ProfileModelRealmClass` is modified.

Plus, don't forget to call  `Realm.close()` as @Zhuinden pointed. Thanks!

**Comment by SahajRana** [comment]
Yaa.. thanks! for  pointing the mistake, I looked for the problem and as u stated there was a listener class which was putting data again in Realm, Now problem is Solved. :)
