### ISSUE TITLE
getting a value from created object returns null

### ISSUE THREAD

**Issue by lectricas** [realm/realm-java#3226]
```
private fun createNewTrack () {
        val track: Track
        realm.beginTransaction()
        track = realm.createObject(Track::class.java)
        realm.commitTransaction()
        startActivity<RecordingActivity>(Const.EXTRA_TRACK_ID to track.uuid) 
}
```

![160730-0003](https://cloud.githubusercontent.com/assets/8782219/17270281/1ec901ae-5670-11e6-85a8-cf07f5bcf665.png)

WHY?

**Comment by stk1m1** [comment]
@lectricas 

I cannot see what `track.uuid`'s type is. Is it `String`? Is it annotated to be `@Required`? We'd like to provide the best possible support as we can, but without detailed context, we cannot do so. Please consider fill up [the issue template](https://github.com/realm/realm-java/blob/master/CONTRIBUTING.md#filing-issues).

Plus, you can post the question to StackOverflow for more attention especially in weekend. 
Thanks!

**Comment by lectricas** [comment]
```
open class Track : RealmObject() {
    open var uuid: String = UUID.randomUUID().toString()
...
}
```
the object itself is ok, but when I'm trying to get a value, I'm getting null.

![160730-0002](https://cloud.githubusercontent.com/assets/8782219/17272656/54200af4-56ad-11e6-97e8-2ba87af04a54.png)

**Comment by stk1m1** [comment]
@lectricas 

1. Please consider sharing with us the full `Track` model. 
2. What's your Realm version?

**Comment by lectricas** [comment]
```
package org.loop.fixedlite.model


import io.realm.RealmList
import io.realm.RealmObject
import java.util.*


open class Track : RealmObject() {

    open var uuid: String = UUID.randomUUID().toString()
    open var isRunning: Boolean = false
    open var distance: Float = 0.toFloat()
    open var dateCreated: Date? = null
    open var dateClosed: Date? = null
    open var dateUpdated: Date? = null
    open var comments: String? = null
    open var type: Int = 0
    open var status: Int = 0
    open var track_owner: String? = null
    open var points: RealmList<Point> = RealmList()


    fun getType(): TrackType {
        return TrackType.fromDb(type)
    }

    fun setType(trackType: TrackType) {
        type = trackType.trackStatusDb
    }

    override fun equals(o: Any?): Boolean {
        if (o !is Track) {
            return false
        }
        return this.uuid == o.uuid
    }

    override fun hashCode(): Int {
        var hashCode = 1
        hashCode = hashCode * 37 + this.uuid.hashCode()
        return hashCode
    }

    companion object {

        val DEFAULT_UUID = UUID(0, 0)

        val TABLE_NAME = "Track"

        val COLUMN_NAME_UUID = "uuid"

        val COLUMN_NAME_IS_RUNNING = "isRunning"

        val COLUMN_NAME_DISTANCE = "distance"

        val COLUMN_NAME_DATE_CREATED = "dateCreated"

        val COLUMN_NAME_DATECLOSED = "dateClosed"

        val COLUMN_NAME_DATE_UPDATED = "dateUpdated"

        val COLUMN_NAME_COMMENTS = "comments"

        val COLUMN_NAME_TYPE = "type"

        val COLUMN_NAME_STATUS = "status"

        val COLUMN_NAME_TRACK_OWNER = "track_owner"
    }
}

```



classpath "io.realm:realm-gradle-plugin:1.0.0"

    compile 'com.facebook.stetho:stetho:1.3.1'
    compile 'com.uphyca:stetho_realm:0.9.0'
    compile 'io.realm:android-adapters:1.2.2'

**Comment by stk1m1** [comment]
@lectricas 

I've looked again your `Track` model and realized that we don't respect field values for default constructor when you create one with `Realm.createObject()`, which is being tracked in #777. 

I can see this is more likely to be expected when you're to spawn an instance. If you're strongly in need of fields value set in a new object, you can do this instead.

```kotlin
private fun createNewTrack () {
        val track: Track = Track()
        realm.beginTransaction()
        realm.copyToRealmOrUpdate(track)
        realm.commitTransaction()
        startActivity<RecordingActivity>(Const.EXTRA_TRACK_ID to track.uuid) 
}
```

I'll link this issue to #777 and close it for now. If you have another question related to this issue, please post your question over there. Thanks!
