### ISSUE TITLE
Importing examples into android studio fails

### ISSUE THREAD

**Issue by jhegedus42** [realm/realm-java#3227]
There is some gradle problem when importing examples to android studio, please see details here:

http://stackoverflow.com/questions/38678074/realm-android-example-in-android-studio-are-not-working

**Comment by zaki50** [comment]
Hi @jhegedus42 
I've answered on SO.

**Comment by Zhuinden** [comment]
I've also answered on SO.

**Comment by stk1m1** [comment]
As this is tracked in SO, I'll close this issue for now. Please concentrate an issue at one place at a time.
