### ISSUE TITLE
define groupBy and count field

### ISSUE THREAD

**Issue by ejahangiri** [realm/realm-java#3233]
How define sql query in realm ? 
`   SELECT COUNT(Id), Country   FROM Customer GROUP BY Country
`

**Comment by kneth** [comment]
We don't have direct support for it so you will have to do something like:

    RealmResults<Customer> customers = realm.where(Customer.class).distinct("country").findAll();
    for (Customer customer : customers) {
        // customer.getCountry() will return a few country for every iteration
    }

We have #2309 for tracking it.

**Comment by ejahangiri** [comment]
error
java.lang.IllegalArgumentException: Field name 'country' must be indexed in order to use it for distinct queries.

**Comment by Zhuinden** [comment]
You need to add `@Index` annotation on field `country` (which will require a migration)

**Comment by ejahangiri** [comment]
tnk

**Comment by Zhuinden** [comment]
long count = realm.where(Customer.class).distinct("country").findAll().size();

**Comment by ejahangiri** [comment]
tnk
how define count(Country )?
The number of repetitions one country

**Comment by kneth** [comment]
You could do something like:

    RealmResults<Customer> customers = realm.where(Customer.class).distinct("country").findAll()M
    for (Customer customer : customers) {
        long count = realm.where(Customer.class).equalTo("country", customer.getCountry()).findAll().size());
        // count is the number of occurrences of this particular country
    }

**Comment by ejahangiri** [comment]
tnk

**Comment by zahid--ali** [comment]
Is this addition has been added or any new solution?

**Comment by hmedat2008** [comment]
I have the save example 
But I can't distinct the result,  i got this exception
Invalid query: field 'room' in class 'RealmMessage' is of invalid type 'OBJECT'. 

When i'm trying to index my filed, i got "You can't index realm object"
