### ISSUE TITLE
Realm in maven repository

### ISSUE THREAD

**Issue by arenaq** [realm/realm-java#3236]
Hello,
issue is that you have 1.1.1 in changelog, but not in maven repository.

Can you tell me how can people know when will be new version available in maven repository?
And when will be 1.1.1 in maven repository?

Thank you.

**Comment by Zhuinden** [comment]
in reality, the snapshot is in 1.2.0-SNAPSHOT 

the current latest release version as per https://realm.io/docs/java/latest/ is 1.1.0

**Comment by cmelchior** [comment]
1.1.1 will be released this week. You can see here how to use our SNAPSHOT builds if you want to test it: https://github.com/realm/realm-java#using-snapshots

**Comment by arenaq** [comment]
Allright, is there any way (for future) to approximate when new release will be available?

**Comment by cmelchior** [comment]
Not really. We don't announce release dates far in advance as they are subject to change, so it would just set false expectations. 

All changes are available in our SNAPSHOT releases though, and we try to ship important bug fixes as soon as possible.

**Comment by zaki50** [comment]
There is no way to know release date in advance, but you can register yourself to https://bintray.com/realm/maven/realm-gradle-plugin as a watcher and the you'll get a notification e-mail once new release will be published to jcenter repository.

**Comment by arenaq** [comment]
@zaki50 Good tip, thanks.
