### ISSUE TITLE
Allow 0-length values array on RealmQuery.in() 

### ISSUE THREAD

**Issue by dalinaum** [realm/realm-java#3238]
Allow 0-length values array on RealmQuery.in() 

> cmelchior: Should we allow the 0-length values array? It would basically default to the query always returning the empty set, but I would imagine that this values array in most cases will be generated in a loop based on some other input, so I think that this array in a lot of cases will actually be empty, making it a hassle for the user to work around.
> 
> bdash: In Cocoa we have [`TrueExpression` and `FalseExpression`](https://github.com/realm/realm-cocoa/blob/30947f35a115db9e62e208a2ee2c2b75a3009e9b/Realm/RLMQueryUtil.mm#L88-L114) that we use for cases like [handling an `or` group containing zero elements](https://github.com/realm/realm-cocoa/blob/30947f35a115db9e62e208a2ee2c2b75a3009e9b/Realm/RLMQueryUtil.mm#L727-L732).

from [previous discussion](https://github.com/realm/realm-java/pull/3133#discussion_r73099630)

**Comment by cmelchior** [comment]
Folding this into https://github.com/realm/realm-java/issues/4011

**Comment by Zhuinden** [comment]
Also I'd be surprised if it just started not returning anything.

I'd rather expect it to do a no-op.
