### ISSUE TITLE
xxx is not part of the schema for this Realm

### ISSUE THREAD

**Issue by iAbdulaziz** [realm/realm-java#3242]
I just wrote this issue on Stackoverflow by using my phone. To avoid writing it twice, this is a link to the original post:

- http://stackoverflow.com/q/38733846/5358812

Thanks.

**Comment by Zhuinden** [comment]
What is your gradle tool version?

**Comment by iAbdulaziz** [comment]
A #1: v2.1.2

A #2: I used @RealmClass annotation before, but it didn't help.

A #3: Yes.

**Comment by Zhuinden** [comment]
Is Instant Run disabled?

**Comment by iAbdulaziz** [comment]
I am using AIDE app on Android not Android Studio!

**Comment by kneth** [comment]
Closing as it is better discussed at StackOverflow
