### ISSUE TITLE
Type HashMap<String, String> of field is not supported

### ISSUE THREAD

**Issue by Dragas** [realm/realm-java#3248]
Hi!

I've been poking around realm library as an internal storage for data in android and it works great. Lately I've been wondering whether or not you could replace shared app preferences (later: SP) with this particular storage as in my experience shared preferences tend to accept data only once and never let you to either clear or edit them. I am aware that if database is in app's internal storage, it can only be accessed by that particular app.

So far I've been using SP to store encoded cookies from server, which acted as a hash map. Meanwhile migrating to realm I've come to an issue that field type `java.util.HashMap<java.util.String, java.util.String>` is not supported. How come? Do all fields need to extend RealmObject or be primitive?

**Comment by cmelchior** [comment]
Yes, Maps and Sets are not yet supported, but it is on our roadmap. You can track the feature here: https://github.com/realm/realm-java/issues/759

In your particular use case, you could probably model it as a Configuration object though, and use Realm's queries instead of a hashmap:

```
public class Configuration extends RealmObject {
  @PrimaryKey
  private String id; // your encoded cookie

  // Your configuration
  private boolean foo;
  private String bar;
  private int baz;
}

// Find a specific configuration
Config config = realm.where(Configuration.class).equalTo("id", encodedCookie).findFirst();
```

**Comment by cmelchior** [comment]
In the mean time I'll close this as a duplicate as maps support is tracked in #759

**Comment by Dragas** [comment]
During the response time I already worked around it by making a class which extended RealmObject and wrapped it in RealmList.

Glad to know that HashMap support is on the way. Thank you for quick responses.

**Comment by MkazemAkhgary** [comment]
The alternative solution is to give mapping equivalent scheme.

for example i was mapping language code to language name. because i wanted to make language updates come from server instead of updating the application.

so for this simple mapping you use `Map<String, String>`. 

alternative is to do

```java
public class Language extends RealmObject {

    @PrimaryKey
    private String code;

    private String name;
}
```

and have `List<Language> languages` instead.

**Comment by NehaVerma993** [comment]
This issue is still here.. please someone suggest any solution

**Comment by Zhuinden** [comment]
A `Map<String, String>` field is a `String field` of a `RealmObject`.

Map your data into a compatible format.

**Comment by NehaVerma993** [comment]
But I can't use another, because I am getting dynamic key, value in JSOn from Server.

Ex. JSON : 

result : {
"key1" : "value1",
"key2" : "value2",
"key3" : "value3",
"key4" : "value4",
"key5" : "value5",
}

And to parse them I need to use Map only, as I don't know which key is gonna com from server side. So GSON suggest to use Map only.

**Comment by cmelchior** [comment]
Realm doesn't support Maps yet. If the keys are not a well-defined format, your best alternative is probably two RealmLists, one with keys and one with values.

**Comment by NehaVerma993** [comment]
ok I will check that. thanks

**Comment by johncelario** [comment]
> A `Map<String, String>` field is a `String field` of a `RealmObject`.
> 
> Map your data into a compatible format.

Will this work on dynamic key?
