### ISSUE TITLE
Data Integrity

### ISSUE THREAD

**Issue by martygriffin** [realm/realm-java#3257]
Does Realm doing anything special to ensure data integrity? 

And if so is there documentation on it?

I was unable to find it on the Realm website.

Cheers!

**Comment by cmelchior** [comment]
Not entirely sure what you mean by data integrity?

We have ACID guarantees and are crash safe.

For more information these two places are probably a good starting point:
- https://realm.io/news/jp-simard-realm-core-database-engine/
- https://realm.io/news/threading-deep-dive/

**Comment by Quantium1** [comment]
I know you have an ACID transaction engine, but what I'd like to know is if you perform any kind of Cyclic Redundancy Check (CRC) on the blocks of data that you store in the files. SQL Server, Oracle, Postgres, MySQL, etc., all store a CRC in their data blocks as part of their data integrity checking. Does Realm do anything like that?

**Comment by kneth** [comment]
No, not a such. Of course we check the integrity of the Realm file when it is opened.
