### ISSUE TITLE
java.lang.IllegalArgumentException: User is not part of the schema for this Realm

### ISSUE THREAD

**Issue by xiaosheng1126** [realm/realm-java#3260]
```
       at io.realm.internal.modules.CompositeMediator.getMediator(CompositeMediator.java:132)
                                                                  at io.realm.internal.modules.CompositeMediator.getTableName(CompositeMediator.java:79)
                                                                  at io.realm.Realm.getTable(Realm.java:1270)
                                                                  at io.realm.Realm.createObject(Realm.java:695)
                                                                  at com.putao.wechat.MainActivity$1.onClick(MainActivity.java:43)
                                                                  at android.view.View.performClick(View.java:4630)
                                                                  at android.view.View$PerformClick.run(View.java:19331)
                                                                  at android.os.Handler.handleCallback(Handler.java:733)
                                                                  at android.os.Handler.dispatchMessage(Handler.java:95)
                                                                  at android.os.Looper.loop(Looper.java:157)
                                                                  at android.app.ActivityThread.main(ActivityThread.java:5387)
                                                                  at java.lang.reflect.Method.invokeNative(Native Method)
                                                                  at java.lang.reflect.Method.invoke(Method.java:515)
                                                                  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1265)
                                                                  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1081)
                                                                  at dalvik.system.NativeStart.main(Native Method)
```

**Comment by xiaosheng1126** [comment]
String moduleName = "io.realm.DefaultRealmModule"; 
tracking Down This class does not exist.

**Comment by cmelchior** [comment]
It means the annotation processor isn't running for some reason. Are you using Android Studio?

**Comment by xiaosheng1126** [comment]
i use the tools android studio.

**Comment by cmelchior** [comment]
Can you post the gradle log from a clean build?

**Comment by xiaosheng1126** [comment]
/**
 * Created by Administrator on 2016/8/4.
 */
public class User extends RealmObject {

    @PrimaryKey
    private String userId;

    private String userName;

    public String getUserId() {
        return userId;
    }

    public void setUserId(String userId) {
        this.userId = userId;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }
}

**Comment by xiaosheng1126** [comment]
apply plugin: 'com.android.application'
apply plugin: 'realm-android'
android {
    compileSdkVersion 24
    buildToolsVersion "24.0.1"

    defaultConfig {
        applicationId "com.putao.wechat"
        minSdkVersion 15
        targetSdkVersion 24
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(include: ['*.jar'], dir: 'libs')
    compile project(':library')
    compile project(':http')
}

**Comment by xiaosheng1126** [comment]
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.1.2'
        classpath "io.realm:realm-gradle-plugin:1.1.1"
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

**Comment by xiaosheng1126** [comment]
My english is poor , you do chinese?

**Comment by cmelchior** [comment]
@beeender can 😄

**Comment by xiaosheng1126** [comment]
I can use chinese to communicate with you right

**Comment by cmelchior** [comment]
Yes

**Comment by xiaosheng1126** [comment]
前几天demo演示的时候貌似还可以用，今天就不可以了，一直报上面这个问题。

**Comment by beeender** [comment]
是 kotlin 工程么？还是 java 和 kotlin 混合的工程？

**Comment by xiaosheng1126** [comment]
我跟踪发现RealmConfiguration public static Object getDefaultModule() {
        String moduleName = "io.realm.DefaultRealmModule";
        Class<?> clazz;
        //noinspection TryWithIdenticalCatches
        try {
            clazz = Class.forName(moduleName);
            Constructor<?> constructor = clazz.getDeclaredConstructors()[0];
            constructor.setAccessible(true);
            return constructor.newInstance();
        } catch (ClassNotFoundException e) {
            return null;
        } catch (InvocationTargetException e) {
            throw new RealmException("Could not create an instance of " + moduleName, e);
        } catch (InstantiationException e) {
            throw new RealmException("Could not create an instance of " + moduleName, e);
        } catch (IllegalAccessException e) {
            throw new RealmException("Could not create an instance of " + moduleName, e);
        }
    }
返回了null,

**Comment by xiaosheng1126** [comment]
混合吧

**Comment by xiaosheng1126** [comment]
要不我把源码发给你看看

**Comment by beeender** [comment]
kotlin 和 java 混合的时候注解处理器会又点问题。

你试试把 `apply plugin: 'kotlin-android'` 放到 apply plugin: 'realm-android' 前面

如果不行的话，把源码发给我。发到 help@realm.io 或者其他你方便的方式。

**Comment by xiaosheng1126** [comment]
// Creates the mediator that defines the current schema
    private RealmProxyMediator createSchemaMediator(Builder builder) {

        Set<Object> modules = builder.modules;
        Set<Class<? extends RealmModel>> debugSchema = builder.debugSchema;

        // If using debug schema, use special mediator
        if (debugSchema.size() > 0) {
            return new FilterableMediator(DEFAULT_MODULE_MEDIATOR, debugSchema);
        }

        // If only one module, use that mediator directly
        if (modules.size() == 1) {
            return getModuleMediator(modules.iterator().next().getClass().getCanonicalName());
        }

        // Otherwise combine all mediators
        RealmProxyMediator[] mediators = new RealmProxyMediator[modules.size()];
        int i = 0;
        for (Object module : modules) {
            mediators[i] = getModuleMediator(module.getClass().getCanonicalName());
            i++;
        }
        return new CompositeMediator(mediators);
    }

**Comment by xiaosheng1126** [comment]
public CompositeMediator(RealmProxyMediator... mediators) {
        final HashMap<Class<? extends RealmModel>, RealmProxyMediator> tempMediators = new HashMap<>();
        if (mediators != null) {
            for (RealmProxyMediator mediator : mediators) {
                for (Class<? extends RealmModel> realmClass : mediator.getModelClasses()) {
                    tempMediators.put(realmClass, mediator);
                }
            }
        }
        this.mediators = Collections.unmodifiableMap(tempMediators);
    }

**Comment by xiaosheng1126** [comment]
this.mediators 这个集合是空的导致 // Returns the mediator for a given model class (not RealmProxy) or throws exception
    private RealmProxyMediator getMediator(Class<? extends RealmModel> clazz) {
        RealmProxyMediator mediator = mediators.get(clazz);
        if (mediator == null) {
            throw new IllegalArgumentException(clazz.getSimpleName() + " is not part of the schema for this Realm");
        }
        return mediator;
    }

**Comment by beeender** [comment]
呃，是的，但是这个代码对解决问题意义不大……主要是要看看为什么 注解处理器为什么没有在编译器执行。

gradle 的log 发出来看看？

**Comment by xiaosheng1126** [comment]
好的，非常感谢，代码马上邮件发给你！

**Comment by beeender** [comment]
收到邮件了，邮件里说。

**Comment by vsona** [comment]
别邮件里说呀。。。https://github.com/vsona/projectb
commit 3cc8b5aa4678e0a8090425246618d77ee451a34f
我这有相同的问题。

**Comment by beeender** [comment]
@vsona The problem of your project is Realm doesn't work with Jack compiler right now (well, it is because of Google hasn't made Jack work with transformer yet.). See https://github.com/realm/realm-java/issues/3038 . And the issue in google side: https://code.google.com/p/android/issues/detail?id=210730&q=Jack%20transform&colspec=ID%20Status%20Priority%20Owner%20Summary%20Stars%20Reporter%20Opened

**Comment by vsona** [comment]
Thank you very much！


2017-01-17 18:29 GMT+08:00 Chen Mulong <notifications@github.com>:

**Comment by slipy-spy** [comment]
我们项目之前用的SQLite，现在要改用realm，简单测了一下，总是报这个错：is not part of the schema for this Realm.求救啊

**Comment by Zhuinden** [comment]
@slipy-spy if you use `android-apt`, you need to apply it **before** `realm-android`

**Comment by slipy-spy** [comment]
@Zhuinden I don't use android-apt

**Comment by beeender** [comment]
@slipy-spy Are you using Realm in a kotlin project? how does your gradle file look like? Have your tried clean (deleting all build objects) and rebuild?

**Comment by slipy-spy** [comment]
@beeender  I use Realm in java project. Is it wrong because of the "jackOptions" of the JDK1.8 ? 

my build.gradle:

jackOptions {
            enabled true
}

compileOptions {
        targetCompatibility = JavaVersion.VERSION_1_8
        sourceCompatibility = JavaVersion.VERSION_1_8
}

**Comment by Zhuinden** [comment]
@slipy-spy yes, Jack *does* support the Transform API according to Jack, but Realm doesn't support Jack yet.

You can however use https://github.com/evant/gradle-retrolambda

**Comment by abdullo211** [comment]
I have same issue ` java.lang.IllegalArgumentException: Stock is not part of the schema for this Realm`
Its exception was after converting class file from java to Kotlin

**Comment by abdullo211** [comment]
Stock class:
` class Stock : RealmModel, Serializable {

    @PrimaryKey
    @SerializedName("id")
    @Expose
    var id: Int = 0

    @SerializedName("name")
    @Expose
    var name: String = ""

    @SerializedName("stock_type")
    @Expose
    val stockType: String? = null

}
`

**Comment by Zhuinden** [comment]
@abdullo211 You need to apply `kotlin-kapt` plugin before you apply `realm-android`

**Comment by abdullo211** [comment]
Thanks for answer
