### ISSUE TITLE
Realm Export and Import

### ISSUE THREAD

**Issue by koz01** [realm/realm-java#3265]
Hi,

I'm development in distribution management Android app using Realm.Sometime, tablet device is crush file.So i want to use realm database file export and import feature like Ms Sql restore and backup .bak file.
Now , i testing realm export and import but import function is not work.Please see below.

Code to initialize:
https://github.com/koz01/RealmExportImport
Let me know any advice.
Thank
Jordan

Realm version(s): 1.1.1

Android Studio version: 2.2 Preview 6

Which Android version and device: Lenovo

**Comment by kneth** [comment]
We will be happy to help you but please use our issue template so we have enough information to answer.
