### ISSUE TITLE
realm.close doesn't work!

### ISSUE THREAD

**Issue by lovearthhome** [realm/realm-java#3267]
We commit write in one thread(EventBus OnEvent Thread), and realm.close() is added. but i cannot get the data from another thread(EventBus OnEvent Thread) instantly. actually i must
1: wait enough long time(5~10min) or 
2: restart the app 
to see the commited data.

```
        ivitaConfig = new RealmConfiguration.Builder(context).name("ivita.realm")
                .modules(new IvitaModule()).deleteRealmIfMigrationNeeded()
                .build();
        realm = Realm.getInstance(ivitaConfig);
```

EventBus.OnMessageEvent()

```
       realm=Realm.getInstance(ivitaConfig);
        try {
            realm.beginTransaction();
            IvitaEvent ivitaEvent =realm.createObject(IvitaEvent.class);
            ivitaEvent.setType(type);
            ivitaEvent.setDuaid(duaid);
            ivitaEvent.setT0(t0);
            ivitaEvent.setData(data);
            ivitaEvent.setLot(lot);
            ivitaEvent.setUploaded(uploaded);
            realm.commitTransaction();
            realm.close();
            //fixme: the data will be written in db lazy later. why???, realm.close() dosent help!!
            return true;
        }catch (Exception e){
            e.printStackTrace();
            realm.cancelTransaction();
            return false;
        }
```

platform: android. realm-java latest by now

the problem cost us several days and makes us creazy.

it's really not a easy-to-use db framework.

**Comment by Zhuinden** [comment]
So you're saying you are trying to access the new version of data that you create with a commit on one non-looper background thread, and you send an event through a bus to another non-looper background thread? 

Yeah, that's to be expected. Only looper threads (like the UI thread) can be autoupdated. The UI thread is automatically `setAutoUpdate(true)`. Non-looper background threads need to use `waitForChange()`. You should probably put `realm.waitForChange()` in your `onEvent` method on your other background thread.

**Comment by Zhuinden** [comment]
P. S. you aren't closing your Realm instance in case of failure, and you should.

**Comment by Zhuinden** [comment]
@lovearthhome by the way, this is why I personally use `onEventMainThread()` when I'm done with a task. The main thread is always up to date with its Realm after a commit when it receives the message through the handler.

(sorry @stk1m1 :tongue: )

**Comment by kneth** [comment]
@lovearthhome Did the comments above help you to solve your issue?
