### ISSUE TITLE
Can

### ISSUE THREAD

**Issue by YanPaingHein** [realm/realm-java#3270]
> We LOVE to help with any issues or bug you have!

> **Questions**: If you have questions about how to use Realm, please ask on [SO](http://stackoverflow.com/questions/ask?tags=realm) - we monitor the Realm tag.

> **Feature Request**: Just fill in the first two sections below.

> **Bugs**: To help you as fast as possible with an issue or bug please describe your issue and the steps you have taken to reproduce it in as many details as possible.
>
> Thanks for helping us help you :-)
>
> Remove this and above before submitting.

#### Goal

> What do you want to achieve?

#### Expected Results

> ?

#### Actual Results

>  E.g. full stack trace with exception

#### Steps & Code to Reproduce

> Describe your current debugging efforts.

#### Code Sample

```java

> Your code here. Bigger samples should ideally be as separate Android Studio project, 
> in gists/repositories or privately at help@realm.io)

```

#### Version of Realm and tooling
Realm version(s): ?

Android Studio version: ?

Which Android version and device: ?

**Comment by YanPaingHein** [comment]
I export the table from SQLite with CSV format and import to the realm. But right now, I have 11 csv files and I want to add all the CSV file into one Realm file. I can't add like that. after adding one csv file to the Realm Browser. It's only default.realm file.

**Comment by Zhuinden** [comment]
Can't you merge the CSVs?

**Comment by kneth** [comment]
@YanPaingHein It sounds more like a Realm Browser issue. Please open an issue in the Realm Browser repository instead.

**Comment by Zhuinden** [comment]
Yeah, there is a Github issues for the Realm Browser in a separate repository: https://github.com/realm/realm-browser-osx/issues

**Comment by kneth** [comment]
@YanPaingHein I have created https://github.com/realm/realm-browser-osx/issues/193. You are welcome to comment on that issue about your use case.

**Comment by kneth** [comment]
@YanPaingHein The Realm Browser can now import multiple CSV files. Thanks for the suggestion :-)
