### ISSUE TITLE
Possible bug? Or feature? isNotEmpty and isNotNull "compatibility"

### ISSUE THREAD

**Issue by draskosaric** [realm/realm-java#3273]
Hi,

I have RealmObject of class A which has two following members:

String userAccount
String provider

So, I want to filter list of A objects with following criterium: give me all A objects which has non-empty userAccount members or have provider == "Something". So, at first I made query:

```java
realm
    .where(A.class)
    .beginGroup()
    .isNotEmpty("userAccounts")
    .or()
    .equals("provider", "Something")
    .endGroup()
    .findAll();
 ``` 

I get `RealmResults<A>` with some A objects that have userAccounts member to be `null`. Then I made second query which returned the correct result:

```java
realm
    .where(A.class)
    .beginGroup()
    .isNotNull("userAccounts") // this is the addition
    .isNotEmpty("userAccounts")
    .or()
    .equals("provider", "Something")
    .endGroup()
    .findAll();
 ```
 
So, I report this because I don't know if you implemented this deliberately or this was not how you planned to behave.

**Comment by Zhuinden** [comment]
Is `userAccounts` a `RealmList<UserAccount>`, or a `UserAccount`?

**Comment by draskosaric** [comment]
I just saw that I wrote `userAccounts` instead of `userAccount` and `userAccount` is just a `String`, not `RealmList`.

**Comment by Zhuinden** [comment]
Ah, well `isNotEmpty` is to specify that `realmList.size() > 0`, and `isNull` means `value == null`.

**Comment by kneth** [comment]
And for a string, `isNotEmpty` tests against `""`.
