### ISSUE TITLE
RealmRecyclerViewAdapter not accept RealmList<T>

### ISSUE THREAD

**Issue by shannavas** [realm/realm-java#3274]
RealmList<TimeStamp> result = new RealmList<>();
       result.add(realm.where(TimeStamp.class).findFirst());

   `  recyclerView.setAdapter(new MyRecyclerViewAdapter(this,result));`

 ` public MyRecyclerViewAdapter(RecyclerViewExampleActivity activity,`OrderedRealmCollection<TimeStamp> data) {
      `  super(activity ,data, true);`
      `  this.activity = activity;`
    `}`
Adapter does't show any thing.
**RealmRecyclerViewAdapter OrderedRealmCollection not accept RealmList , its only accept RealmResult**

**Comment by kneth** [comment]
In order to help you, we need you to use the issue template. Otherwise, we d not have enough information.

**Comment by Zhuinden** [comment]
Make sure you set a RecyclerView.LayoutManager for your recycler view as well.

**Comment by shannavas** [comment]
Recyclerview  working for RealmResult on setadapter()
but not working for RealmList<T> on setadapter()

```
RealmResults<Person> person = realm.where(Person.class).findAll();
                adapter = new BooksAdapter(MainActivity.this,person);
                recycler.setAdapter(adapter);
```
the above example is working fine

```
RealmList<person> firstPerson = new RealmList<>();
Person person = realm.where(Person.class).findFirst();
firstPersion.add(person);
                adapter = new BooksAdapter(MainActivity.this,firstPersion);
                recycler.setAdapter(adapter);
```
it's not working.

my adapter constructor
```
 public MyRecyclerViewAdapter(RecyclerViewExampleActivity activity,OrderedRealmCollection data){
super(activity,data,true);
}
```

**Comment by Zhuinden** [comment]
Oh, your `RealmList<>` is unmanaged, and `isValid()` returns false on unmanaged objects.

https://github.com/realm/realm-java/issues/3101

So yeah, **managed** RealmLists work.

**Comment by shannavas** [comment]
hoe to create managed RealmLists for the above.

**Comment by Zhuinden** [comment]
Customize your adapter.
