### ISSUE TITLE
Configurations cannot be different if used to open the same file

### ISSUE THREAD

**Issue by huazi0923** [realm/realm-java#3275]
Hi, i set realm DefaultConfiguration  in Application. And use getDefaultInstance to get Realm.
But, sometimes i get this error when i use getDefaultInstance,compare with Cached configuration and New configuration,I find migration is different. Could you tell me some reason?

Realm version(s): realm 0.88.3
Android Studio version: android studio 2.1.2
Which Android version and device: android 5.1.1 (22)

here is the error log:

 java.lang.IllegalArgumentException: Configurations cannot be different if used to open the same file. 
Cached configuration: 
realmFolder: /data/data/im.mixbox.magnet/files/realm
realmFileName : 57a1631d65d03935dd0010c5.realm
canonicalPath: /data/data/im.mixbox.magnet/files/realm/57a1631d65d03935dd0010c5.realm
key: [length: 0]
schemaVersion: 4
migration: im.mixbox.magnet.data.db.Migration@42b623a8
deleteRealmIfMigrationNeeded: false
durability: FULL
schemaMediator: io.realm.DefaultRealmModuleMediator@647d6e88

New configuration: 
realmFolder: /data/data/im.mixbox.magnet/files/realm
realmFileName : 57a1631d65d03935dd0010c5.realm
canonicalPath: /data/data/im.mixbox.magnet/files/realm/57a1631d65d03935dd0010c5.realm
key: [length: 0]
schemaVersion: 4
migration: im.mixbox.magnet.data.db.Migration@42fd6708
deleteRealmIfMigrationNeeded: false
durability: FULL
schemaMediator: io.realm.DefaultRealmModuleMediator@647d6e88

**Comment by cmelchior** [comment]
You are running into the problem described here: http://stackoverflow.com/questions/36907001/open-realm-with-new-realmconfiguration

**Comment by huazi0923** [comment]
Thanks, after check my code, I found it is possible that configuration can be created many timeN Now i want to override equals and hashCode and use other way to ensure configuration be created 
one time. Hope to solve this bug.

**Comment by beeender** [comment]
Great! I am closing this issue now. If you still need help on this, feel free to reopen it. Thanks!

**Comment by magillus** [comment]
I know this issue was resolved long time ago, but I saw same exception when `compactOnLaunch` is different. 
I used lambda method to handle `CompactOnLaunchCallback` and that caused the issue too.

**Comment by Zhuinden** [comment]
Well yeah it uses `equals` on all items provided to the configuration.

**Comment by Abfareye** [comment]
> I know this issue was resolved long time ago, but I saw same exception when `compactOnLaunch` is different. I used lambda method to handle `CompactOnLaunchCallback` and that caused the issue too.

i am facing the same issue 
`FATAL EXCEPTION: RealmModule
                                                                                                    Process: com.fareyereact.debug, PID: 30227
                                                                                                    java.lang.IllegalArgumentException: Configurations cannot be different if used to open the same file. 
                                                                                                    Cached configuration: 
                                                                                                    realmDirectory: /data/user/0/com.fareyereact.debug/files
                                                                                                    realmFileName : default.realm
                                                                                                    canonicalPath: /data/user/0/com.fareyereact.debug/files/default.realm
                                                                                                    key: [length: 64]
                                                                                                    schemaVersion: 151
                                                                                                    migration: null
                                                                                                    deleteRealmIfMigrationNeeded: true
                                                                                                    durability: FULL
                                                                                                    schemaMediator: io.realm.DefaultRealmModuleMediator@4c92c728
                                                                                                    readOnly: false
                                                                                                    compactOnLaunch: com.realm.RealmModule$$ExternalSyntheticLambda0@4e172bf
                                                                                                    maxNumberOfActiveVersions: 9223372036854775807
                                                                                                    
                                                                                                    New configuration: 
                                                                                                    realmDirectory: /data/user/0/com.fareyereact.debug/files
                                                                                                    realmFileName : default.realm
                                                                                                    canonicalPath: /data/user/0/com.fareyereact.debug/files/default.realm
                                                                                                    key: [length: 64]
                                                                                                    schemaVersion: 151
                                                                                                    migration: null
                                                                                                    deleteRealmIfMigrationNeeded: true
                                                                                                    durability: FULL
                                                                                                    schemaMediator: io.realm.DefaultRealmModuleMediator@4c92c728
                                                                                                    readOnly: false
                                                                                                    compactOnLaunch: com.realm.RealmModule$$ExternalSyntheticLambda0@3ae3d8c
                                                                                                    maxNumberOfActiveVersions: 9223372036854775807
                                                                                                    	at io.realm.RealmCache.validateConfiguration(RealmCache.java:606)
                                                                                                    	at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:457)
                                                                                                    	at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:422)`


Only compactOnLaunch is different in two realm  configurations

using this code for realm initialisation - 
`    @ReactMethod
     public void initRealm( final int schemaVersion) {
            Context applicationContext = getReactApplicationContext();
            Realm.init(applicationContext);
            RealmConfiguration.Builder builder = new RealmConfiguration.Builder();
            RealmConfiguration configuration = builder.schemaVersion(schemaVersion)
                    .compactOnLaunch((totalBytes, usedBytes) -> true)
                    .encryptionKey(ENCRYPTION_KEY)
                    .deleteRealmIfMigrationNeeded()
                    .build();
            Realm.setDefaultConfiguration(configuration);
    }`

**Comment by Abfareye** [comment]
> I know this issue was resolved long time ago, but I saw same exception when `compactOnLaunch` is different. I used lambda method to handle `CompactOnLaunchCallback` and that caused the issue too.

i am facing the same issue 
`FATAL EXCEPTION: RealmModule
                                                                                                    Process: com.fareyereact.debug, PID: 30227
                                                                                                    java.lang.IllegalArgumentException: Configurations cannot be different if used to open the same file. 
                                                                                                    Cached configuration: 
                                                                                                    realmDirectory: /data/user/0/com.fareyereact.debug/files
                                                                                                    realmFileName : default.realm
                                                                                                    canonicalPath: /data/user/0/com.fareyereact.debug/files/default.realm
                                                                                                    key: [length: 64]
                                                                                                    schemaVersion: 151
                                                                                                    migration: null
                                                                                                    deleteRealmIfMigrationNeeded: true
                                                                                                    durability: FULL
                                                                                                    schemaMediator: io.realm.DefaultRealmModuleMediator@4c92c728
                                                                                                    readOnly: false
                                                                                                    compactOnLaunch: com.realm.RealmModule$$ExternalSyntheticLambda0@4e172bf
                                                                                                    maxNumberOfActiveVersions: 9223372036854775807
                                                                                                    
                                                                                                    New configuration: 
                                                                                                    realmDirectory: /data/user/0/com.fareyereact.debug/files
                                                                                                    realmFileName : default.realm
                                                                                                    canonicalPath: /data/user/0/com.fareyereact.debug/files/default.realm
                                                                                                    key: [length: 64]
                                                                                                    schemaVersion: 151
                                                                                                    migration: null
                                                                                                    deleteRealmIfMigrationNeeded: true
                                                                                                    durability: FULL
                                                                                                    schemaMediator: io.realm.DefaultRealmModuleMediator@4c92c728
                                                                                                    readOnly: false
                                                                                                    compactOnLaunch: com.realm.RealmModule$$ExternalSyntheticLambda0@3ae3d8c
                                                                                                    maxNumberOfActiveVersions: 9223372036854775807
                                                                                                    	at io.realm.RealmCache.validateConfiguration(RealmCache.java:606)
                                                                                                    	at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:457)
                                                                                                    	at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:422)`


Only compactOnLaunch is different in two realm  configurations

using this code for realm initialisation - 
`    @ReactMethod
     public void initRealm( final int schemaVersion) {
            Context applicationContext = getReactApplicationContext();
            Realm.init(applicationContext);
            RealmConfiguration.Builder builder = new RealmConfiguration.Builder();
            RealmConfiguration configuration = builder.schemaVersion(schemaVersion)
                    .compactOnLaunch((totalBytes, usedBytes) -> true)
                    .encryptionKey(ENCRYPTION_KEY)
                    .deleteRealmIfMigrationNeeded()
                    .build();
            Realm.setDefaultConfiguration(configuration);
    }`
