### ISSUE TITLE
Add .equalTo(String fieldName, byte[] value) to RealmQuery

### ISSUE THREAD

**Issue by bkromhout** [realm/realm-java#3278]
#### Goal

`RealmQuery` is currently missing the ability to query against `byte[]` fields using `equalTo`, and since that *is* one of the supported field types, I believe such a thing should be possible.

#### Expected Results

I would like to be able to construct a `RealmQuery` which returns items based on whether a `byte[]` field's value matches a byte array I supply. For example:

```java
byte[] bytes = new byte[] {...}; // Some byte array.
RealmResults<Foo> foos = realm.where(Foo.class).equalTo("bar", bytes).findAll();
```

If this is something which I can help out with, I'd definitely be willing to (though I might need a few pointers as to where to look).

Thanks!

**Comment by kneth** [comment]
@bkromhout It is true that we don't support `equalTo()` and `notEqualTo()` on binary data (`byte[]`). Implementing it, requires a methods like https://github.com/realm/realm-java/blob/master/realm/realm-jni/src/io_realm_internal_TableQuery.cpp#L832 and https://github.com/realm/realm-java/blob/master/realm/realm-jni/src/io_realm_internal_TableQuery.cpp#L888.

**Comment by beeender** [comment]
#3285 is merged and released.
