### ISSUE TITLE
cannot find symbol variable AyatTextRealmProxy

### ISSUE THREAD

**Issue by droidahmed** [realm/realm-java#3279]
public class AyatText implements RealmModel {

     public String ayatText;
     public String suraNum;
     public String ayaNum;

     public AyatText() {
      }

      public AyatText(String ayatText, String suraNum, String ayaNum) {
       this.ayatText = ayatText;
      this.suraNum = suraNum;
      this.ayaNum = ayaNum;
      }

      public String getAyatText() {
         return ayatText;
      }

     public void setAyatText(String ayatText) {
        this.ayatText = ayatText;
       }

      public String getSuraNum() {
       return suraNum;
      }

      public void setSuraNum(String suraNum) {
       this.suraNum = suraNum;
      }

     public String getAyaNum() {
      return ayaNum;
    }

    public void setAyaNum(String ayaNum) {
       this.ayaNum = ayaNum;
      }

       @Override
        public String toString() {
         return "AyatText{" +
            "ayatText='" + ayatText + '\'' +
            ", suraNum='" + suraNum + '\'' +
            ", ayaNum='" + ayaNum + '\'' +
            '}';
          }
        }
 
       public static Table initTable(ImplicitTransaction transaction) {
       if (!transaction.hasTable("class_InfoTafseer")) {
        Table table = transaction.getTable("class_InfoTafseer");
        table.addColumn(RealmFieldType.STRING, "ayaText", Table.NULLABLE);
        if (!transaction.hasTable("class_Tafser")) {
            TafserRealmProxy.initTable(transaction);
        }
        table.addColumnLink(RealmFieldType.LIST, "tafserRealmList",    
       transaction.getTable("class_Tafser"));
        table.addColumn(RealmFieldType.STRING, "sora", Table.NULLABLE);
        table.addColumn(RealmFieldType.STRING, "suraNum", Table.NULLABLE);
        if (!transaction.hasTable("class_AyatText")) {
            AyatTextRealmProxy.initTable(transaction);
        }

    public class InfoTafseer  extends RealmObject {
    public String ayaText;
     public String sora;
    private String suraNum;
    public RealmList<AyatText>ayatTextRealmList;
    public String fileName;
         public String ayaNum;
    public String ayaTafser;
    public InfoTafseer() {
    }
    public InfoTafseer(String fileName) {
        this.fileName = fileName;
    }
    public String getAyaText() {
        return ayaText;
    }

    public void setAyaText(String ayaText) {
        this.ayaText = ayaText;
    }

    public String getSora() {
        return sora;
    }

    public void setSora(String sora) {
        this.sora = sora;
    }

    public String getFileName() {
        return fileName;
    }

    public void setFileName(String fileName) {
        this.fileName = fileName;
    }

    public String getAyaNum() {
        return ayaNum;
    }

    public void setAyaNum(String ayaNum) {
        this.ayaNum = ayaNum;
    }

    public String getAyaTafser() {
        return ayaTafser;
    }

    public void setAyaTafser(String ayaTafser) {
        this.ayaTafser = ayaTafser;
    }

    public String getSuraNum() {
        return suraNum;
    }

 

      public RealmList<AyatText> getAyatTextRealmList() {
        return ayatTextRealmList;
     }

      public void setAyatTextRealmList(RealmList<AyatText> ayatTextRealmList) {
        this.ayatTextRealmList = ayatTextRealmList;
       }

     public InfoTafseer(String suraNum, String sora, RealmList<AyatText> ayatTextRealmList, String 
     fileName, String ayaTafser, String ayaNum) {
         this.suraNum = suraNum;
        this.sora = sora;
        this.ayatTextRealmList = ayatTextRealmList;
        this.fileName = fileName;
        this.ayaTafser = ayaTafser;
        this.ayaNum = ayaNum;
     }

       public InfoTafseer(String ayaText, String sora, String suraNum, String fileName, String ayaNum,    
         String ayaTafser) {
        this.ayaText = ayaText;
        this.sora = sora;
        this.suraNum = suraNum;
        this.fileName = fileName;
        this.ayaNum = ayaNum;
        this.ayaTafser = ayaTafser;
      }

       public void setSuraNum(String suraNum) {
        this.suraNum = suraNum;
       }

      @Override
       public String toString() {
        return "InfoTafseer{" +
                 ", ayaNum='" + ayaNum + '\'' +
                ", sora='" + sora + '\'' +
                ", suraNum='" + suraNum + '\'' +
                '}';
          }
    }

Error:(255, 17) error: cannot find symbol variable AyatTextRealmProxy

     add realm 1.1.1
     classpath "io.realm:realm-gradle-plugin:1.1.1"

**Comment by Zhuinden** [comment]
You need to add `@RealmClass` annotation if you use `implements RealmModel`

**Comment by droidahmed** [comment]
thanks it solve the problem 
and I try extends RealmObject
it works for both 
thanks again
