### ISSUE TITLE
i have update realm database using this code:  Profile profile = mRealm.where(Profile.class).findFirst();                                               profile.setName(name.getText().toString());                                               profile.setMobile(mobile.getText().toString());                                               profile.setEmail(email.getText().toString());                                               profile.setCity(city.getText().toString());                                               profile.setSpecialty(speciality.getText().toString()); but this code is work set data in realm but old data is there.plz need help

### ISSUE THREAD

**Issue by Reenaefgh** [realm/realm-java#3282]
> We LOVE to help with any issues or bug you have!

> **Questions**: If you have questions about how to use Realm, please ask on [SO](http://stackoverflow.com/questions/ask?tags=realm) - we monitor the Realm tag.

> **Feature Request**: Just fill in the first two sections below.

> **Bugs**: To help you as fast as possible with an issue or bug please describe your issue and the steps you have taken to reproduce it in as many details as possible.
>
> Thanks for helping us help you :-)
>
> Remove this and above before submitting.

#### Goal

> What do you want to achieve?

#### Expected Results

> ?

#### Actual Results

>  E.g. full stack trace with exception

#### Steps & Code to Reproduce

> Describe your current debugging efforts.

#### Code Sample

```java

> Your code here. Bigger samples should ideally be as separate Android Studio project, 
> in gists/repositories or privately at help@realm.io)

```

#### Version of Realm and tooling
Realm version(s): ?

Android Studio version: ?

Which Android version and device: ?

**Comment by Zhuinden** [comment]
Please fix your title and include your transaction code, thank you

**Comment by kneth** [comment]
@Reenaefgh I am closing the issue. Please create a new issue which is properly formatted.
