### ISSUE TITLE
count() seems to have some cache, multiple process issue

### ISSUE THREAD

**Issue by bdelville** [realm/realm-java#3287]
#### Goal

Counting the number of item in an activity after deleting instance from another process
`realm.where(MyModel.class).count();`

#### Expected Results

Getting the new count() value

#### Actual Results

We get the value before the deletion from the other process

#### Steps & Code to Reproduce

* Create a service in another process and an activity in the default process
* Open a realm and count() the number of realm object in the activity
* deleteAllObject form the service, commit and close the database
* send a broadcast received by the application and count() again in the same realm

#### Version of Realm and tooling
Realm version(s): 1.1.0

Android Studio version: 2.1.2

Which Android version and device: Samsung Galaxy Tab A, Android 6.0.1

**Comment by bdelville** [comment]
If I close all realm instance in the activity, and open a new one before calling the count(), it does work

**Comment by beeender** [comment]
Really sorry but this is still the same issue with #1091 ...

Generally speaking, using Realm in multi-processes is not supported yet. So it won't work as expected, especially process won't be notified when the other process make changes to the Realm db.

I am closing and dup this issue, and really sorry for closing your 3 issues in a day :)

Please let us know if you have further questions. Or if you have any comments about multi-process, you can just leave a comment in #1091 

Thanks!!!
