### ISSUE TITLE
Update realm from another process works only after it's been closed.

### ISSUE THREAD

**Issue by bdelville** [realm/realm-java#3288]
#### Goal

Updating the data in the realm from a service in another process and see the result from the activity in the default process

#### Expected Results

I can retrieve the new data as soon as commit is called in the service

#### Actual Results

The realm in the service from another process has to be closed for the activity to see the new values.

#### Steps & Code to Reproduce

* Create a service in another process and an activity in the default process, and add a single item in the realm
* Edit this item in the realm from the process. Commit but don't close the realm.
* Notify the activity by Broadcast
* From the activity, access the object.

#### Version of Realm and tooling
Realm version(s): 1.1.0

Android Studio version: 2.1.2

Which Android version and device: Samsung Galaxy Tab A, Android 6.0.1

**Comment by beeender** [comment]
Still same issue as #1091 
Close and dup to #1091 

And thanks again for the feedback!
