### ISSUE TITLE
RealmChangeListener never fired if modification is made from another process

### ISSUE THREAD

**Issue by bdelville** [realm/realm-java#3289]
#### Goal

I want to be notified of a data edition even if it's made in another process

#### Expected Results

I get notified

#### Actual Results

I never get notified, event after commit and close realm from the process

#### Steps & Code to Reproduce

* Create a service in another process and an activity in the default process, and add a single item in the realm
* Register a RealmChangeListener in the activity to this realm
* Edit this item in the realm from the process. Commit and close the realm, whatever
* RealmChangeListener never fire
* From the activity, edit the item, the RealmChangeListener is fired

#### Version of Realm and tooling
Realm version(s): 1.1.0

Android Studio version: 2.1.2

Which Android version and device: Samsung Galaxy Tab A, Android 6.0.1

**Comment by beeender** [comment]
The multi processes support has not been added yet. But we are working on it.
We have an issue to track this already, see #1091 .

I will close this issue and dup it to #1091.

Thanks a lot for your feedback!

**Comment by bdelville** [comment]
Ok sorry for the duplicate. Thanks a lot for your work
