### ISSUE TITLE
Realm fields are not reflected on Java properties properly

### ISSUE THREAD

**Issue by athalay** [realm/realm-java#3291]
#### I have the following entity/RealmObject:
```java
public class TrackWodApplicationStateRealm extends RealmObject {
    @PrimaryKey
    public int ID;
    public int CurrentlyTrackedWodHistoryID;
    public int CurrentlyTrackedWodHistoryCmTrainingProgramID;
}
```

#### In my code I'm saving the following data into realm:
```java
final TrackWodApplicationStateRealm data = new TrackWodApplicationStateRealm();

data.ID = 0; //we store one instance of TrackWodApplicationStateRealm
data.CurrentlyTrackedWodHistoryID = 0;
data.CurrentlyTrackedWodHistoryCmTrainingProgramID = 78;

_realm.executeTransaction(new Realm.Transaction() {
    @Override
    public void execute(Realm realm) {
	_realm.copyToRealmOrUpdate(data);
    }
});
```

#### Then, on another activity I'm trying to read it out:
```java
RealmQuery<TrackWodApplicationStateRealm> query = _realm.where(TrackWodApplicationStateRealm.class);
query = query.equalTo("ID", 0); //we store one instance of TrackWodApplicationStateRealm
TrackWodApplicationStateRealm data = query.findFirst();
```
#### In Android Studio's debugger the following is displayed:
```java
data = TrackWodApplicationStateRealm = [{ID:0},{CurrentlyTrackedWodHistoryID:0},{CurrentlyTrackedWodHistoryCmTrainingProgramID:78}]
```
BUT, if I expand the following properties, or use them in code:
- CurrentlyTrackedWodHistoryID
- CurrentlyTrackedWodHistoryCmTrainingProgramID

**, then both of them have ZERO (0) values!!**

#### Version of Realm and tooling
Realm version(s): 1.1.1

Android Studio version: 2.1.1

Which Android version and device: 6.1, Nexus 6, but bug appears in genymotion emulator also

**Comment by Zhuinden** [comment]
Regarding the fields showing 0 in debugger:
- Well yes of course. Using field access is transformed by the transformer so that it would be replaced by the proxy getter/setter method call.

Regarding the field returning `CurrentlyTrackedWodHistoryCmTrainingProgramID` with `data.CurrentlyTrackedWodHistoryCmTrainingProgramID`:
- That shouldn't happen, that should return 78.

**Comment by cmelchior** [comment]
That is working as intended. See https://realm.io/docs/java/latest/#android-studio-debugging

**Comment by athalay** [comment]
Thanks guys, it works as you described. Thanks for the superfast response!
