### ISSUE TITLE
FATAL columnIndex is less than 0

### ISSUE THREAD

**Issue by Queatz** [realm/realm-java#3292]
#### Goal

Query on brand new DynamicRealm

#### Expected Results

Get an error similar to `Table "Thing" does not exist in schema`

#### Actual Results

Fatal crash `java.lang.ArrayIndexOutOfBoundsException: columnIndex is less than 0.`

#### Steps & Code to Reproduce

Create a new DynamicRealm
Run something like: `dynamicRealm.where("Thing").equalTo("id", id).findFirst();`

#### Version of Realm and tooling
Realm version(s): 1.1.1

Android Studio version: 2.2 Beta

Which Android version and device: Android 5.1 on Huawei Mate S

**Comment by Queatz** [comment]
Hmm, so I need to know what fields are going to be inserted in advance, or else I need to check for field existence before running each query?

**Comment by beeender** [comment]
@Queatz May I know why do you need to use DynamicRealm instead of Realm?
The one difference between DynamicRealm & Realm is, when the first time the instance gets created, DynamicRealm won't check the schema and create the schema, Realm will.

**Comment by Queatz** [comment]
I see. I have fairly arbitrary objects coming from a server with various fields filled out and I just want to store them as they come.  The fields will always be the same type, though, so I guess it could be a giant pojo, but always having to instantiate those seemed like overkill so I went with DynamicRealm. I just want it to grow as it finds new objects on the server.

**Comment by beeender** [comment]
Then I think you need to check for the field existence before running each query... 

Also, since you might have have usage on the DynamicRealm, please notice, if you remove any field on a DynamicRealm with a living RealmResults which is built on the specific type of DynamicRealm, you might run into this issue #2953 .

**Comment by Zhuinden** [comment]
You need to add this class and field for `Thing.java` through the Realm schema of the DynamicRealm

**Comment by Queatz** [comment]
I've updated the expected result.

**Comment by beeender** [comment]
#$
