### ISSUE TITLE
Migrate to OpenSSL 1.0.2

### ISSUE THREAD

**Issue by kneth** [realm/realm-java#3297]
According to https://www.openssl.org/policies/releasestrat.html, support of OpenSSL 1.0.1 will end 31st December 2016. We should switch to OpenSSL 1.0.2 or later. Or we could explore if [LibreSSL](http://www.libressl.org/) or [BoringSSL](https://boringssl.googlesource.com/boringssl/) are better alternatives.

**Comment by diegomontoya** [comment]
We have used boringSSL in the past, and like the cleaned up/trimmed api vs openssl which had, last time we compared, tons of very old compat code which boringssl stripped. Definitely worth investigating.

**Comment by kneth** [comment]
I upgraded to OpenSSL 1.0.2j: https://github.com/realm/realm-core/pull/2226
