### ISSUE TITLE
 Android Realm get Not inside a transaction Error

### ISSUE THREAD

**Issue by tux-world** [realm/realm-java#3299]
when i get data from dialog by listener as `interface` and try to save choosed data as class model. i can not create new row in table

get data from dialog:

    takeUserEwalletCurrency.setOnTakeUserEwallet(new TakeUserEwalletCurrency.IOnChooseEwallet() {
        @Override
        public void getItem(int item) {
            takeUserEwalletCurrency.dismissDialog();
            switch (item) {
                case 1:
                    String choiceUSDUserEwallet = "SHUSD" + userPhoneNumber.substring(1, userPhoneNumber.length());
                    updateEwalletsHistory(choiceUSDUserEwallet, "SHUSD");
                    to_ewallet.setText(choiceUSDUserEwallet);
                    validateEnteredEwalletNumber();
                    break;
                case 2:
                    ...
                    break;
            }
        }
    });
    takeUserEwalletCurrency.showDialog();

create new row:

    private void updateEwalletsHistory(final String currentEwallet, final String ewalletCurrency) {
        final EwalletsHistory exists_row = realm.where(EwalletsHistory.class).equalTo("ewalletName", currentEwallet).findFirst();

        if (exists_row == null) {
            realm.executeTransaction(new Realm.Transaction() {
                @Override
                public void execute(Realm realm) {
                    EwalletsHistory item = new EwalletsHistory();
                    item.setEwalletName(currentEwallet);
                    item.setEwalletCurrency(ewalletCurrency);
                    realm.commitTransaction();
                }
            });
        }
    }

both of them such as Dialog interface and create new row in table are the same activity

**Comment by Zhuinden** [comment]
Don't call commit transaction inside a transaction. 

Execute transaction calls commit already. Don't call it manually.

**Comment by tux-world** [comment]
Thanks sir, problem resolved by replace that with ```realm.copyToRealm(item);```
