### ISSUE TITLE
'com.intellij:annotations' lib included as generated code, causing DEX conflicts

### ISSUE THREAD

**Issue by mikeholler** [realm/realm-java#3307]
#### Goal

Build an application that depends on Realm and an `aar` dependency that includes `com.intellij:annotations` as a dependency.

#### Expected Results

The application builds successfully.

#### Actual Results

When assembling the application, I get this error.

```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':apps:questionnaire:app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process.ProcessException: java.util.concurrent.ExecutionException: com.android.dex.DexException: Multiple dex files define Lorg/jetbrains/annotations/NotNull;
```

#### Steps & Code to Reproduce

App build file contains the following:

```
buildscript {
    repositories {
        classpath 'io.realm:realm-gradle-plugin:1.1.0'
    }
}

dependencies {
    compile project(':path:to:library:project')
}
```

Library build file contains:

```
dependencies {
    compile 'com.intellij:annotations:12.0'
}
```

#### Workaround

Since Realm generates the annotations library into the `build/intermediates/transforms/RealmOptionalAPITransformer/debug/folders/1/10/realm-optional-api/org/jetbrains`, there is no way to exclude it from the classpath using Gradle's typical `exclude group: 'com.intellij', module: 'annotations'` method, so in order to fix it I've had to do:

```
configurations {
    compile.exclude group: 'com.intellij', module: 'annotations'
}
```

This solution works, but is not ideal. If the annotations module gets an update that dependent libraries (or even my app) require, I won't be able to get it until I update to a version of realm that supplies the updated annotations library (if one even exists). I recommend adding `compile 'com.intellij:annotations:12.0` to the project through the `realm-gradle-plugin`, instead of generating a copy of the intellij library in `build/intermediates/`.

#### Version of Realm and tooling
Realm version(s):

realm-gradle-plugin 1.1.0

**Comment by beeender** [comment]
This is strange, `RealmOptionalAPITransformer` is in the aar but is not used right now, we don't register it as a transformer. Have you tried clean the project?

**Comment by beeender** [comment]
I can just totally remove it.

**Comment by mikeholler** [comment]
I built everything from a fresh clone today and everything worked. I know I did a clean yesterday but still had this issue, but obviously some state was hanging on somehow since the fresh clone fixed it. Thanks for listening and for your prompt response.
