### ISSUE TITLE
Testing `Realm.setAutoRefresh()` 

### ISSUE THREAD

**Issue by beeender** [realm/realm-java#3318]
This method doesn't seems to be useful and it makes corner cases very difficult to be covered, like:
1. having async in current thread, and set auto refresh to false
2. should local committed transaction refresh RealmResults when this is false?

etc...

**Comment by cmelchior** [comment]
So deprecate now in 1.2, and remove in 2.0? Sounds 👍 with me

**Comment by Zhuinden** [comment]
Wouldn't that mean that HandlerThreads can no longer be auto-updated?

**Comment by cmelchior** [comment]
No, HandlerThreads would still work. 

We auto-detect the state of auto-refresh when opening the Realm, but this is a manual override of that. But as @beeender described there are a lot of edge cases where this might get weird. Also we are hard pressed to see _why_ you would want to override the default behavior in the first place.

**Comment by beeender** [comment]
I would like to know if there are any real cases need this API. :thought_balloon:

**Comment by beeender** [comment]
From ez

> The use case is when a user is scrolling a long list and lots of writes are happening in the mean time. you don’t want the list to jump around in a non predictable way.

I thinks this is still needed, and we need to make edge cases simple and working.

**Comment by Zhuinden** [comment]
Well, I saw that the code in `HandlerThread` requires you to call `setAutoRefresh(false)` so that you unsubscribe from the Realm's looper/handler controller thing. There's a warning message if you don't. But maybe I misunderstood it - after all, I never started using `HandlerThread`.

**Comment by beeender** [comment]
this is handled and tested by Object Store.
