### ISSUE TITLE
weird behavior of .findAllAsync().asObservable()

### ISSUE THREAD

**Issue by igoticecream** [realm/realm-java#3325]
Hello, I'm querying a table that could be empty with this:

`realm.where(MyClass.class)
                .findAllAsync()
                .asObservable()
                .filter(RealmResults::isLoaded)`

The observable never completes if the table is empty, no empty observable, no error, no nothing. As soon I insert the first row into MyClass the observable emits this value and finally completes.

The thing is, it should emit an empty observable if no data were found immediately and complete. Why does it have to wait for a row to be there? :S

Don't take me wrong, but realm's rxjava is not what i expected (I won't use the word "bad", I'm just dissapoined . I can't even apply my own schedulers to fetch data because exception is thrown) and i guess i'll stick with the traditional way and ditch away the rxjava support: Creating an observable, fetching data synchronous and put them onNext and apply my schedulers :S

**Comment by Zhuinden** [comment]
Please read the RxJava section

https://medium.com/@Zhuinden/how-to-use-realm-for-android-like-a-champ-and-how-to-tell-if-youre-doing-it-wrong-ac4f66b7f149

**Comment by igoticecream** [comment]
Please test what i said

**Comment by Zhuinden** [comment]
Technically I'm on my way home so I cannot test this at the moment. But the change listener should be called when the async query completes and returns a RealmResults with 0 size. 

Are you 100% certain that this doesn't happen?

**Comment by igoticecream** [comment]
Thanks for helping me, this is the exact statement; please create UserEntity with whatever and test this:

`		Realm realm = Realm.getInstance(mConfiguration);

		realm
			.where(UserEntity.class)
			.findAllAsync()
			.asObservable()
			.filter(RealmResults::isLoaded)
			.flatMapIterable(userEntities -> userEntities)
			.doAfterTerminate(realm::close)
			.subscribe(userEntity -> Timber.d(userEntity.toString()), throwable -> Timber.e(throwable, "Error"), () -> Timber.d("Completed"));`


It just wont call onComplete not onError if there is no data in the table.

**Comment by Zhuinden** [comment]
Well it should only call `onNext()` which it does for me:

    08-19 23:08:38.845 10098-10098/com.zhuinden.rxrealm 
                 D/DogView: Called onNext() of empty results with [[]]

**Comment by igoticecream** [comment]
Thanks for testing. But my statement doesn't call onNext, onComplete nor onError if the table is empty. Still looking for a solution :/

**Comment by igoticecream** [comment]
Nevermind, turns out i have to call .first() after .filter() to stop the emission.

**Comment by Zhuinden** [comment]
That is true, `onNext()` is called but `onComplete()` is not - the observable is intended to listen to changes until you unsubscribe.
