### ISSUE TITLE
Improve control of [possibly flawed] RealmLog default/custom logger

### ISSUE THREAD

**Issue by paulpv** [realm/realm-java#3326]
#### Goal/Expected Results

More reasonable control of RealmLog.LOGGERS; mostly the ability to remove the default logger.
RealmBase automatically adds during static initialization:
https://github.com/realm/realm-java/blob/master/realm/realm-library/src/main/java/io/realm/BaseRealm.java#L80
Possibly a RealmLog.set(Logger logger) or a RealmLog.clear() would be sufficient.

#### Actual Results

First of all, RealmBase's "BuildConfig.DEBUG ? DebugAndroidLogger : ReleaseAndroidLogger" logic is based off of "com.getkeepsafe.relinker.BuildConfig".
This logic seems like a bug...two actually.
1) The logic should probably be based off of "io.realm.BuildConfig".
2) Libraries by default build as Release, and I am assuming Realm is, so this will always evaluate to ReleaseAndroidLogger.

Second of all, RealmLog provides no way to remove this logger.
The result is that adding a custom logger ends up showing some duplicate messages.

#### Steps & Code to Reproduce

```java
if (REALM_LOG_LEVEL >= RealmLog.VERBOSE)
{
    if (false)
    {
        // Spews lots of not very useful [to me] info...
        io.realm.internal.Util.setDebugLevel(1);
    }

    //
    // NOTE: Realm already adds a DebugAndroidLogger or ReleaseAndroidLogger:
    //  https://github.com/realm/realm-java/blob/master/realm/realm-library/src/main/java/io/realm/BaseRealm.java#L80
    // But, that logic is flawed because it uses com.getkeepsafe.relinker.BuildConfig and will always compile as
    // Release and will always add ReleaseAndroidLogger.
    // Realm provides no way to remove this Logger.
    //
    AndroidLogger androidLogger = new AndroidLogger();
    androidLogger.setMinimumLogLevel(REALM_LOG_LEVEL);
    androidLogger.setTag("MYREALM");
    RealmLog.add(androidLogger);
}
```

#### Version of Realm and tooling
Realm version(s): 1.1.1
Android Studio version: 2.1.3
Which Android version and device: N/A

**Comment by zaki50** [comment]
@paulpv Thank you for reporting.

Referring to `com.getkeepsafe.relinker.BuildConfig` seems a bug.

I don't think we support adding/removing a custom logger since `RealmLog` is a internal class.
What do you think @realm/java ?

**Comment by Zhuinden** [comment]
Your visibility is 

    public final class RealmLog {
        public static void add(Logger logger) {
        public static void remove(Logger logger) {

So it seems odd to say that "you don't support adding/removing a custom logger", because you technically do. It can also be useful if you add an external crash logging thing to which you send warnings and errors so that it's not purely local.

However, the instance of the standard `AndroidLogger` is never kept as a reference, so it truly can never be removed.

A method like `removeAllListeners()` is not a bad idea. It's quite typical for anything with listeners.

**Comment by cmelchior** [comment]
The `RealmLog` was originally only intended to be part of our internal API. However I can understand the reasons for why some might want to either add their own or completely disable our implementation. 

The current API is intended to support multiple loggers, but adding something like `RealmLog.clear()` seems very reasonable to me.
