### ISSUE TITLE
Misleading migration example

### ISSUE THREAD

**Issue by mrexmelle** [realm/realm-java#3327]
#### Goal

> Providing a correct example to the developers who want to implement Realm migration procedure.
#### Expected Results

> When a developer wants to upgrade from version 1 to version 2, only one migration should take place, i.e. migration from 1 to 2.
#### Actual Results

>  When a developer wants to upgrade from version 1 to version 2, the migration continues until version 3. 
#### Steps & Code to Reproduce

> Clear enough.
## Currently

``` java

if(oldVersion == 0)
{
 // migration from version 0 to 1 takes place
 oldVersion++;
}

if(oldVersion == 1)
{
 // migration from version 1 to 2 takes place
 oldVersion++;
}

if(oldVersion == 2)
{
 // migration from version 2 to 3 takes place
 oldVersion ++;
}

```
## Expected

``` java

if(oldVersion == 0 && oldVersion<newVersion)
{
 // migration from version 0 to 1 takes place
 oldVersion++;
}

if(oldVersion == 1 && oldVersion<newVersion)
{
 // migration from version 1 to 2 takes place
 oldVersion++;
}

if(oldVersion == 2 && oldVersion<newVersion)
{
 // migration from version 2 to 3 takes place
 oldVersion ++;
}

```
#### Version of Realm and tooling

Realm version(s): 1.1.1

Android Studio version: 2.1.3

Which Android version and device: Any

**Comment by Zhuinden** [comment]
Well it [**does** say](https://github.com/realm/realm-java/blob/master/examples/migrationExample/src/main/java/io/realm/examples/realmmigrationexample/model/Migration.java#L27) it's an example of migrating a Realm from its previous versions to SchemaVersion 3, and I'm not sure why you'd ever want to stop at SchemaVersion 2, but technically it's true, even if you specified schema version 2, you'd still end up with schema version 3.

**Comment by cmelchior** [comment]
Hi @mrexmelle 
Technically you are correct, but since Realm doesn't allow downgrades I am hard pressed to see a situation where you would ship migration code for something that doesn't even exists yet?

**Comment by Zhuinden** [comment]
Yeah, to go from 3 to 2 you would have to make a 4th schema version that is an inverse of the operations you do in the migration to 3

**Comment by mrexmelle** [comment]
Hello @cmelchior,

The situation where it misleads comes to me as a Realm's new adopter. As someone who is still experimenting using Realm, I started by implementing __deleteRealmIfMigrationNeeded()__ without __schemaVersion()__ as an easy start.

Later in my project, I experimented by setting schemaVersion to 1 while adding __if(oldVersion==n)__ three times as in the example.

Later I figured out that the scheme follows the scheme of the third version.

I admit I have missed the statement where it said:
~~~~
/**
 * Example of migrating a Realm file from version 0 (initial version) to its last version (version 3).
 */
~~~~
as pointed out by @Zhuinden, but I believe it is more helpful for the beginners if we add the __newVersion<oldVersion__ guard so they don't have to go into the case I experienced to figure it out.

**Comment by Zhuinden** [comment]
@cmelchior I guess the concern does make sense if you take the migration code directly, experiment with setting the initial DOG, run the code, and think specifying the migration with schema version 0 will make you stick with schema version 0, but you get a "migration needed" because even if you're experimenting it runs up to schema 3.

If you intend to actually work your way through the example step by step, then that migration really does mess it up for you.

**Comment by spl** [comment]
I think adding the `oldVersion < newVersion` condition to every `if` is misleading. That's not to say that the examples or documentation couldn't be improved, as I suggested in #3165.

Perhaps it would help to add statements to the effect of:

* migrations are intended to bring any previous version of the schema up to date with the latest and
* if you want to test migration to a particular version during development, you may need to use a different approach.

**Comment by cmelchior** [comment]
I agree with @spl on this. IMO the solution is not to make the migration example more complicated, but improve the documentation in general around this. We already have a couple of issues tracking various aspects of this.

**Comment by TR4Android** [comment]
I really like [this](http://stackoverflow.com/documentation/android/871/sqlite/3253/onupgrade-method#t=20160823080935501113) approach to doing database migrations (should also apply to Realm). It's clear and concise, yet still fully functional to use in production code.

**Comment by cmelchior** [comment]
@TR4Android 
That pattern also works with Realm. The RealmMigration is only triggered if needed and we provide both old and new version number in the `void migrate(DynamicRealm realm, long oldVersion, long newVersion)` method

**Comment by TR4Android** [comment]
@cmelchior Thanks, I know :wink: This was just a suggestion for the Realm documentation, as it would work if used in production and still gives a clear idea of what a migration is supposed to do.

**Comment by cmelchior** [comment]
Ah sorry. I misunderstood you then :) ... But yes changing our example/docs to that pattern might be a good idea. It will definitely work if you just copy paste the code, and doesn't reduce readability that much. 

I still think the for loop in that example is a bit convoluted, but for code intended to copy/paste that might be fine. What do you think @realm/java ?

**Comment by kneth** [comment]
Our examples should be something people can copy/paste/adapt.

**Comment by beeender** [comment]
I like the loop in the example :P

**Comment by cmelchior** [comment]
@beeender You like C++ code so your opinion doesn't count 😛

**Comment by spl** [comment]
Not that anybody asked for my opinion 😉, but I think the `for` loop migration simplifies the code and improves readability by putting the condition checking and version bumping in one place. In particular, it removes the duplicate `oldVersion++` statements. I felt it necessary to leave a comment on that line to inform myself and others to always include it when writing a new migration, and I try to avoid comment-based specifications if at all possible.

**Comment by Zhuinden** [comment]
That loop is actually pretty cool and smart, it'll solve this problem **and** make the code more pretty

**Comment by mrexmelle** [comment]
I vote for the for-loop as well.
