### ISSUE TITLE
Gradle fails sync when realm-gradle-plugin:1.0.0 added to Android Studio project

### ISSUE THREAD

**Issue by shashank090789** [realm/realm-java#3331]
Error:Could not get unknown property 'options' for task ':app:compileDebugJavaWithJack' of type com.android.build.gradle.tasks.JackTask.

I am using java 8 with jack

**Comment by beeender** [comment]
Hi jack compiler is not supported yet because some feature we rely on has not been implemented by google.
See https://github.com/realm/realm-java/issues/3038
