### ISSUE TITLE
How to load static data?

### ISSUE THREAD

**Issue by Bajranghudda1** [realm/realm-java#3334]
I have a static table around 1 lac records, how should i use realm so that it can save my time. As i know i can put my static table directly in assets and can access it's data.

Is there any way to put static data?

**Comment by Zhuinden** [comment]
um... what is "static data"?

You'd probably just need to treat it like any other data.

**Comment by Bajranghudda1** [comment]
@Zhuinden 

Actually i have some static tables means its row-fields are static and just need to access its values through realm.

**Comment by Bajranghudda1** [comment]
And  the way i found is convert all table's data into json and then load it in phone using

realm.createAllFromJson("myjsondata");

But it seems will consume double disk space, isn't it?

**Comment by beeender** [comment]
@Bajranghudda1 You can build a realm and put is into asset folder. Load it with https://realm.io/docs/java/1.2.0/api/io/realm/RealmConfiguration.Builder.html#assetFile-android.content.Context-java.lang.String-

To create a Realm db, you can use Realm browser https://github.com/realm/realm-browser-osx .
