### ISSUE TITLE
Too many open files in io_realm_internal_SharedGroup.cpp

### ISSUE THREAD

**Issue by GiorgosOikonomou** [realm/realm-java#3338]
io.realm.exceptions.RealmError: Unrecoverable error. Too many open files in io_realm_internal_SharedGroup.cpp line 113
	at io.realm.internal.SharedGroup.createNativeWithImplicitTransactions(Native Method)
	at io.realm.internal.SharedGroup.a(SharedGroup.java:95)
	at io.realm.internal.SharedGroup.<init>(SharedGroup.java:74)
	at io.realm.internal.s.<init>(SharedGroupManager.java:49)
	at io.realm.d.<init>(BaseRealm.java:87)
	at io.realm.z.<init>(Realm.java:139)
	at io.realm.z.b(Realm.java:239)
	at io.realm.z.a(Realm.java:219)
	at io.realm.ac.a(RealmCache.java:126)
	at io.realm.z.b(Realm.java:183)

Realm version(s): 1.1.1

Android Studio version: 2.1.3

Which Android version and device: Nexus 6p and Samsung galaxy A3

**Comment by beeender** [comment]
How many different `RealmConfiguration` are you using?
Is it possible that you forget to close the Realm instance in the worker thread?

**Comment by GiorgosOikonomou** [comment]
I am using 4 different configurations. The problem occured in the default configuration. I am definitely sure that I have closed all the previously opened instance...

**Comment by beeender** [comment]
Have you met the problem in other Realm versions? It is strange since Realm `1.1.1` is supposed to fix this problem. Can you reproduce this issue?

**Comment by GiorgosOikonomou** [comment]
I had the same problem in version 1.1.0. I can't reproduce the issue manually. My app is a service that runs 24/7. The problem occurs once every few days.

**Comment by beeender** [comment]
So normally how many threads do you have? I really feel that for some reason, some Realm instances are not closed properly...
Do you use RXjava? And call the unsubsribe at the right time?

**Comment by beeender** [comment]
@GiorgosOikonomou Check https://github.com/realm/realm-java/issues/3197#issuecomment-235215117 it may help to check if there are any Realm instances are not closed

**Comment by Zhuinden** [comment]
I also recommend adding the following Proguard configuration first

```

#realm
-keepnames public class * extends io.realm.RealmObject
-keep @io.realm.annotations.RealmModule class *
-keep class io.realm.** { *; }
-dontwarn javax.**
-dontwarn io.realm.**

```

**Comment by GiorgosOikonomou** [comment]
```
RealmConfiguration conf = FileUtilities.buildRealmConfig(targetId, targetId);
      Realm realm = Realm.getInstance(conf);
      realm.beginTransaction();
      realm.copyToRealm(databaseDiagnostic);
      realm.commitTransaction();
      realm.close();
```

This code gave me the same exception about a minute ago.

**Comment by beeender** [comment]
@GiorgosOikonomou There is a limitation of how many file descriptors can be opened for a single process. So if the limitation reached, any place which tries to open a file might have the problem.

Would you please try to run your services for some rounds then check if there is any instances leaked by https://github.com/realm/realm-java/issues/3197#issuecomment-235215117 ?

**Comment by Zhuinden** [comment]
I can easily see this leave open Realm instances if an exception occurs in `copyToRealm()`

**Comment by beeender** [comment]
As @Zhuinden said, is that possible that you are using some thing like executorservice which will silently catch the exception which makes the Realm instance leaked when exception happens?

**Comment by GiorgosOikonomou** [comment]
@beeender Do you know what the limit is? @Zhuinden Do you suggest that I have to wrap all the transactions in a try-catch block and close the realm instance on the finally block?

**Comment by Zhuinden** [comment]
@GiorgosOikonomou  yes, and call `if(realm.isInTransaction()) { realm.cancelTransaction(); }` in the catch block too.

Or just use `realm.executeTransaction()`, but it is also recommended to close the Realm in finally.

[Check out my article which references this common issue](https://medium.com/@Zhuinden/how-to-use-realm-for-android-like-a-champ-and-how-to-tell-if-youre-doing-it-wrong-ac4f66b7f149)

**Comment by GiorgosOikonomou** [comment]
Ok. I am going to close the issue and test everything mentioned above.

**Comment by beeender** [comment]
On normal android device the limitation is about 1000.
Every Realm instance roughly takes 4 or 5 file descriptors (Didn't check), but for the same Realm file, only one instance is created in the same thread.

So for you case, 4 configurations, that will take some time to touch the limitation.

I thinks there will be a easy instance leaked, please take a look at https://github.com/realm/realm-java/issues/3338#issuecomment-241721608 , use the gist from there, it is every easy to check if you have instances which are accidentally not closed.
