### ISSUE TITLE
Realm Migration Issue

### ISSUE THREAD

**Issue by Sutirth** [realm/realm-java#3339]
Bug: Realm Migrations

Goal: Successful Migration to be done

Expected Result: To get migration done successful

Actual Result: Migration crash  

Realm version(s):1.1.0

Step 1: I create new Database table 
    public class DailyFitnessAverageDB extends RealmObject {
    
        @PrimaryKey
        private String teamName;
        private long stepCountAvg;
        private long caloriesAvg;
        private long distanceAvg;
        private long sweatPointAvg;
    }

Step 2 Migration

        public class Migration implements RealmMigration {
    
            @Override
            public void migrate(final DynamicRealm realm, long oldVersion, long newVersion){
    
                RealmSchema schema = realm.getSchema();
    
                //  ***********************************************************
    //  **** This will migrate from version 0 to version 1 ****
    //  ***********************************************************
                if (oldVersion == 0) {
                    RealmObjectSchema sweatPointSchema = schema.get("UserInfoDB");
                    sweatPointSchema.addField("sweatPoints",Integer.class);
                    oldVersion++;
                }
    
    //  ***********************************************************
    //  **** This will migrate from version 1 to version 2 ****
    //  ***********************************************************
                if(oldVersion == 1) {
                    RealmObjectSchema teamInfoSchema = schema.get("TeamInfoDB");
                    teamInfoSchema.addField("teamDescription",String.class);
    
                    oldVersion ++;
                }
    
    //  ***********************************************************
    //  **** This will migrate from version 2 to version 3 ****
    //  ***********************************************************
                if(oldVersion == 2) {
                    RealmObjectSchema leaderboardInfoSchema = schema.get("LeaderBoardDb");
                    leaderboardInfoSchema.addField("displayName", String.class);
    
    
    
                    oldVersion ++;
                }
    //  ***********************************************************
    //  **** This will migrate from version 3 to version 4 ****
    //  ***********************************************************
    
                if(oldVersion == 3){
    
                    RealmObjectSchema sweatPointFitnessSchema = schema.get("SweatPointFitnessDB");
                    sweatPointFitnessSchema.addField("badgeSweatPoints", int.class);
                    sweatPointFitnessSchema.setNullable("badgeSweatPoints", true);
    
    
                    RealmObjectSchema userInfoSchema = schema.get("UserInfoDB");
                    userInfoSchema.addField("profileImageUpdatedAt", String.class);
    
                    oldVersion++;
                }
    
    
                //  ***********************************************************
    //  **** This will migrate from version 4 to version 5 ****
    //  ***********************************************************
    
    
                if(oldVersion == 4){
    
                    RealmObjectSchema sweatPointFitnessSchema = schema.get("SweatPointFitnessDB");
                    sweatPointFitnessSchema.setNullable("badgeSweatPoints", false);
    
    
    
    
                    oldVersion++;
                }
    
                //  ***********************************************************
    //  **** This will migrate from version 5 to version 6 ****
    //  ***********************************************************
    
                if(oldVersion == 5){
    
                    RealmObjectSchema sweatPointFitnessSchema = schema.get("SweatPointFitnessDB");
                    sweatPointFitnessSchema.setNullable("badgeSweatPoints", true);
    
    
    
    
                    oldVersion++;
                }
    
                //  ***********************************************************
                //  **** This will migrate from version 6 to version 7 ****
                //  ***********************************************************
    
                if(oldVersion == 6){
    
    
                    schema.get("LeaderBoardDb")
                    .addField("userPercentile", float.class)
                    .addField("userRank", int.class)
                    .addField("userRewards",int.class)
                    .addField("userSweatPointsEarned", int.class)
                    .removeField("percentile")
                    .removeField("rank")
                    .removeField("rewards")
                    .removeField("sweatPointEarned")
                            .renameField("userPercentile", "percentile")
                            .renameField("userRank", "rank")
                            .renameField("userRewards","rewards")
                            .renameField("userSweatPointsEarned", "sweatPointEarned");
    
                    oldVersion++;
                }
    
    
                //  ***********************************************************
                //  **** This will migrate from version 7 to version 8 ****
                //  ***********************************************************
    
    
                if(oldVersion == 7){
                    RealmObjectSchema teamInfoSchema = schema.get("TeamInfoDB");
                    teamInfoSchema.addField("profileImageUpdatedAt", String.class);
    
    
                    oldVersion++;
                }
    
                //  ***********************************************************
                //  **** This will migrate from version 8 to version 9 ****
                //  ***********************************************************
    
    
                if(oldVersion == 8){
                    RealmObjectSchema leaderBoardSchema = schema.get("LeaderBoardDb");
                    leaderBoardSchema.addField("profileImageUpdatedAt", String.class);
    
                    RealmObjectSchema sweatPointFitnessSchema = schema.get("SweatPointFitnessDB");
                    sweatPointFitnessSchema.setNullable("badgeSweatPoints", true);
    
    
    
                    oldVersion++;
                }
    
                //  ***********************************************************
                //  **** This will migrate from version 9 to version 10 ****
                //  **
    
                if(oldVersion == 9){
                    RealmObjectSchema sweatPointFitnessSchema = schema.get("SweatPointFitnessDB");
                    sweatPointFitnessSchema.removeField("badgeSweatPoints");
    
                    oldVersion++;
                }
    
    
                //  ***********************************************************
                //  **** This will migrate from version 10 to version 11 ****
                //  **
    
                if(oldVersion == 10){
                    RealmObjectSchema sweatPointFitnessSchema = schema.get("SweatPointFitnessDB");
                    sweatPointFitnessSchema.addField("BadgeSweatPoints", int.class);
                    oldVersion++;
                }
    
    
    
    
                //  ***********************************************************
                //  **** This will migrate from version 11 to version 12 ****
                //  **
                if(oldVersion == 11){
                    RealmObjectSchema rewardsDBSchema = schema.create("RewardsDB")
                                        .addField("rewardId", int.class , FieldAttribute.PRIMARY_KEY)
                                        .addField("title", String.class)
                                        .addField("description", String.class)
                                        .addField("productBrand", String.class)
                                        .addField("requiredSweatPoints", int.class)
                                        .addField("timeLimit",int.class)
                                        .addField("expiry", String.class)
                                        .addField("rewardStatus", int.class)
                                        .addField("userRewardStatus", int.class)
                                        .addField("totalQuantity", int.class)
                                        .addField("availableQuantity", int.class)
                                        .addField("itemCategory",String.class)
                                        .addField("itemImgUrlPrimary",String.class)
                                        .addField("itemImgUrlSecondary",String.class)
                                        .addField("itemPrice",int.class)
                                        .addField("itemDiscount",int.class);
    
    
    
                    RealmObjectSchema rewardSourceDB = schema.create("RewardSourceDB")
                                                    .addField("id", int.class, FieldAttribute.PRIMARY_KEY)
                                                    .addField("name", String.class)
                                                    .addField("type", int.class)
                                                    .addRealmListField("rewardsDB", rewardsDBSchema);
    
    
    
    
    
    
                    oldVersion++;
                }
    
    
            //  ***********************************************************
                //  **** This will migrate from version 12 to version 13 ****
                //  **
    
    
                if(oldVersion == 12){
                    RealmObjectSchema rewardsDBSchema = schema.get("RewardsDB")
                                        .addField("rewardChaseDate", String.class)
                                        .addField("rewardRedeemDate", String.class);
    
    
                    oldVersion++;
                }
    
                //  ***********************************************************
                //  **** This will migrate from version 13 to version 14 ****
                //  **
    
    
                    if(oldVersion == 13) {
                      RealmObjectSchema sweatPointFitnessDBSchema =  schema.get("SweatPointFitnessDB")
                                .addField("rewardSweatPoints", int.class);
                        oldVersion++;
                    }
    
                //  ***********************************************************
                //  **** This will migrate from version 14 to version 15 ****
                //  **
    
                if(oldVersion == 14) {
                    RealmObjectSchema sweatPointFitnessDBSchema =  schema.get("SweatPointFitnessDB")
                            .addField("fordayDistance", int.class);
                    oldVersion++;
                }
    
                //  ***********************************************************
                //  **** This will migrate from version 15 to version 16 ****
                //  **
    
                if(oldVersion == 15) {
                    RealmObjectSchema leaderBoardSchema =  schema.get("LeaderBoardDb")
                            .addField("userStatus", int.class);
                    oldVersion++;
                }
    
                //  ***********************************************************
                //  **** This will migrate from version 16 to version 17 ****
                //  **
    
                if(oldVersion == 16){
                    if(!schema.contains("NewTeamStatisticsDB")) {
                        RealmObjectSchema newTeamStatisticsDB = schema.create("NewTeamStatisticsDB")
                                .addField("teamName", String.class)
                                .addField("totalStepCount", long.class, FieldAttribute.PRIMARY_KEY)
                                .addField("totalCalories", long.class)
                                .addField("totalDistance", long.class)
                                .addField("totalSweatPoints", long.class);
                    }
                    oldVersion++;
                }
    
    
                //  ***********************************************************
                //  **** This will migrate from version 17 to version 18 ****
                //  **
                if(oldVersion == 17){
                    RealmObjectSchema iwownDailyActivityDB = schema.create("IwownDailyActivityDB")
                                                            .addField("startTime", String.class, FieldAttribute.PRIMARY_KEY)
                                                            .addField("endTime", String.class)
                                                            .addField("steps", int.class)
                                                            .addField("calories", double.class)
                                                            .addField("distance", double.class)
                                                            .addField("isSynced", int.class);
    
                    oldVersion++;
                }
    
    
                //  ***********************************************************
                //  **** This will migrate from version 18 to version 19 ****
                //  **
                if(oldVersion == 18){
                    RealmObjectSchema dailyFitnessAverageDB = schema.create("DailyFitnessAverageDB")
                                                                .addField("stepCountAvg", long.class)
                                                                .addField("caloriesAvg", long.class)
                                                                .addField("distanceAvg", long.class)
                                                                .addField("sweatPointAvg", long.class);
    
    
                    oldVersion++;
                }
    
                //  ***********************************************************
                //  **** This will migrate from version 19 to version 20 ****
                //  **
    
                if(oldVersion == 19){
                    if(!schema.contains("DailyFitnessAverageDB")) {
                        RealmObjectSchema dailyFitnessAverageDB = schema.create("DailyFitnessAverageDB")
                                .addField("teamName", String.class, FieldAttribute.PRIMARY_KEY);
                    }
    
                    oldVersion++;
                }
    
            }
    
    
        }

   

Step 3:I update migration number as follows

    RealmConfiguration realmConfiguration = new RealmConfiguration.Builder(this)
                                                .schemaVersion(20)
                                                .migration(new Migration())
                                                .build();

Stack trace

    E: Process: com.workoutguru.workoutcash, PID: 13688
    E: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.workoutguru.workoutcash/com.workoutguru.workoutcash.OnboardProfileActivity}: io.realm.exceptions.RealmMigrationNeededException: Field count does not match - expected 5 but was 4
    E:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
    E:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
    E:     at android.app.ActivityThread.-wrap11(ActivityThread.java)
    E:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
    E:     at android.os.Handler.dispatchMessage(Handler.java:102)
    E:     at android.os.Looper.loop(Looper.java:148)
    E:     at android.app.ActivityThread.main(ActivityThread.java:5422)
    E:     at java.lang.reflect.Method.invoke(Native Method)
    E:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    E:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
    E:  Caused by: io.realm.exceptions.RealmMigrationNeededException: Field count does not match - expected 5 but was 4
    E:     at io.realm.DailyFitnessAverageDBRealmProxy.validateTable(DailyFitnessAverageDBRealmProxy.java:155)
    E:     at io.realm.DefaultRealmModuleMediator.validateTable(DefaultRealmModuleMediator.java:116)

**Comment by Zhuinden** [comment]
Please fix formatting by putting the whole thing in \`\`\`

Like this

``` 
hello
```

**Comment by Sutirth** [comment]
@Zhuinden Done

**Comment by Zhuinden** [comment]
Do you by chance have `DailyFitnessAverageDB`'s Version 0 and Version 20 class?

**Comment by Sutirth** [comment]
@Zhuinden I have recently added DailyFitnessAverageDB

**Comment by Zhuinden** [comment]
Oh the error is actually quite simple

                 if(!schema.contains("DailyFitnessAverageDB")) {
                    RealmObjectSchema dailyFitnessAverageDB = schema.create("DailyFitnessAverageDB")
                            .addField("teamName", String.class, FieldAttribute.PRIMARY_KEY);
                }

You only call `addField("teamName")` if the Realm  didn't previously have DailyFitnessAverageDB, which was added for the previous version
