### ISSUE TITLE
[Suggestion]Copying to realm or ignoring

### ISSUE THREAD

**Issue by Dragas** [realm/realm-java#3340]
Yo! Documentation states that realm has a function for copying to realm and updating an object, but is there an equivalent which instead of updating an object, ignores it? If not, will it be available in later releases?

**Comment by cmelchior** [comment]
Hi @Dragas Thanks for the suggestion.

We have an issue tracking it here: https://github.com/realm/realm-java/issues/900, so I'll close this as a duplicate, but you can follow progress in https://github.com/realm/realm-java/issues/900
