### ISSUE TITLE
Realm save  Instance State with Icepick

### ISSUE THREAD

**Issue by tux-world** [realm/realm-java#3342]
I'm using ```Icepick``` library on my project and i try to save `InstanceState` automatically by that, but after change phone state, i cant get data from ```savedInstance``` and put it on `List` as data

I get this error:

```
Unable to find generated Parcelable class for io.realm.RealmResults, verify that your class is configured properly and that the Parcelable class io.realm.RealmResults$$Parcelable is generated by Parceler.
```

My custom bundler:
```
public class SimCardsBundler implements Bundler<List<SimCardLists>> {
    @Override
    public void put(String s, List<SimCardLists> simCards, Bundle bundle) {
        bundle.putParcelable(s, Parcels.wrap(simCards));
    }

    @Override
    public List<SimCardLists> get(String s, Bundle bundle) {
        return Parcels.unwrap(bundle.getParcelable(s));
    }
}
```

Simcard's Model:

    @Parcel
    public class SimCardLists extends RealmObject {
    
        private String ID;
        private String Number;
        private String Price;
        private String Date;
        private String Status;
        private String Cat;
        private String SalesName;
        private String TransID;
        private String SalesDate;
        private String SalesTime;
        private String SalesSuccess;
    
        public SimCardLists() {
        }
        
        /* SETTER and GETTES*/
    }

My activity to use that:

    public class ActivityMain extends AppCompatActivity {
        @State(SimCardsBundler.class)
        List<SimCardLists> simLists;
    
        @BindView(R.id.simcard_lists)
        RecyclerView simcardListItems;
    
        @BindView(R.id.filter_by)
        TextView filter_by;
    
        @BindView(R.id.toolbar)
        Toolbar toolbar;
    
        private Context              context;
        private ActivityMain       activity;
        private Realm                 realm;
        private Handler              handler;
        private List<SimCardLists> simcardLists;
        private SimCardListAdapter adapter;
        private ProgressDialog     progressDialog;

        @Override
        protected void onCreate(Bundle savedInstanceState) {
            super.onCreate(savedInstanceState);

            Icepick.restoreInstanceState(this, savedInstanceState);

            setContentView(R.layout.activity_main);
            ButterKnife.bind(this);
    
            //@formatter:off
                context                         = getBaseContext();
                activity                          = ActivityMain.this;
                realm                            = Realm.getDefaultInstance();
                handler                         = new Handler();
                simcardLists                  = realm.where(SimCardLists.class).findAll();
                progressDialog             = new ProgressDialog(this);
            //@formatter:on
    
            realm.executeTransaction(new Realm.Transaction() {
                @Override
                public void execute(Realm realm) {
                    realm.deleteAll();
                }
            });
            List<SimCardLists> initialize = new ArrayList<>();
            simcardListItems.setLayoutManager(new LinearLayoutManager(context));
            adapter = new SimCardListAdapter(context, initialize, simcardListItems);
            simcardListItems.setAdapter(adapter);
    
            if (realm.where(SimCardLists.class).count() <= 0) {
                showProgressDialog();
                startService(
                        new Intent(
                                context, WebService.class)
                                .putExtra("category", 0)
                                .putExtra("request_type", "getLatestSimCardNumbers")
                );
            }else if (savedInstanceState == null) {
                Log.e("Its null", "");
                simLists = realm.where(SimCardLists.class).findAll();
                adapter.setData(simLists);
                adapter.notifyDataSetChanged();
            }else{
                Log.e("NOT null", "");
            }
        }
    
        @Override
        protected void onSaveInstanceState(Bundle outState) {
            super.onSaveInstanceState(outState);
            Icepick.saveInstanceState(this, outState);
        }
    
    }

I can not find any helpful tips to resolve this problem

**Comment by Zhuinden** [comment]
In simple terms, you're supposed to requery the RealmResults and shouldn't even try to parcel it with IcePick. Conceptually, considering that `RealmResults` is just an empty list that doesn't contain any elements with a redefined `get()` method that directly gives you the indexed RealmProxy, there's zero reason to even attempt to parcel it.

**Comment by tux-world** [comment]
Thanks. But i really dont know how can i fix that

**Comment by Zhuinden** [comment]
Remove `SimCardsBundler` class and remove `@State(SimCardsBundler.class)` annotation

**Comment by tux-world** [comment]
Then how is it work Icepick?

**Comment by Zhuinden** [comment]
There is no point to using IcePick with Realm, especially its Results.

**Comment by Zhuinden** [comment]
I guess what I should ask is,

**why are you trying to parcel RealmResults** ?

**Comment by Zhuinden** [comment]
> get list of data to store variable again

As said, instead of

        List<SimCardLists> initialize = new ArrayList<>();
        simcardListItems.setLayoutManager(new LinearLayoutManager(context));
        adapter = new SimCardListAdapter(context, initialize, simcardListItems);
        simcardListItems.setAdapter(adapter);

        if (realm.where(SimCardLists.class).count() <= 0) {
            showProgressDialog();
            startService(
                    new Intent(
                            context, WebService.class)
                            .putExtra("category", 0)
                            .putExtra("request_type", "getLatestSimCardNumbers")
            );
        }else if (savedInstanceState == null) {
            Log.e("Its null", "");
            simLists = realm.where(SimCardLists.class).findAll();
            adapter.setData(simLists);
            adapter.notifyDataSetChanged();

do

        simLists = realm.where(SimCardLists.class).findAll();
        simcardListItems.setLayoutManager(new LinearLayoutManager(context));
        adapter = new SimCardListAdapter(context, simLists, simcardListItems);
        simcardListItems.setAdapter(adapter);

        if (realm.where(SimCardLists.class).count() <= 0) {
            showProgressDialog();
            startService(
                    new Intent(
                            context, WebService.class)
                            .putExtra("category", 0)
                            .putExtra("request_type", "getLatestSimCardNumbers")
            );
        } else if (savedInstanceState != null) {
            Log.e("NOT null", "");
        }

**Comment by tux-world** [comment]
Reload from database each phone rotation? We are using save state to dont reload each phone rotation sir. I'm trying to save normally

**Comment by Zhuinden** [comment]
> Reload from database each phone rotation? 

You're not "reloading" anything. RealmResults don't contain data. No database copying is done when you call `realm.where(Blah.class).findAll()`.

Don't forget that you're using Realm. This is not SQLite.

**Comment by Zhuinden** [comment]
With that in mind, parcelling RealmResults doesn't make sense to do.
So with that, from my perspective, this issue is closed.

**Comment by tux-world** [comment]
So you mean is when i fetch data from table with some finds,on rotation
phone realm cache them and reload data from that when i use find again?

Refer your code as you said i try to use that

**Comment by Zhuinden** [comment]
> So you mean is when i fetch data from table with some finds,on rotation
phone realm cache them and reload data from that when i use find again?

Pretty much. If you use managed RealmResults, then you don't need to save instance state of Realm objects manually. If you were referring to an object, you'd have to save instance state its ID so that on rotation you can requery it. Calling `findAll()` is essentially free.

You should check out my [article on this stuff](medium.com/@Zhuinden/how-to-use-realm-for-android-like-a-champ-and-how-to-tell-if-youre-doing-it-wrong-ac4f66b7f149), I go into detail on how you don't have to copy the data you use from Realm; maybe it helps understand what I'm talking about.

Essentially, when you call `RealmResults.get(i)`, you have `___RealmProxy` objects created for that given index. And these are directly linked to the Realm (and can be modified only in a transaction). That means, you get READ access to them, and you see the data directly from the Realm - the data itself is not copied. This is Realm's "zero-copy design".

By parcelling a managed RealmResults, you would be copying it out of the Realm. It goes against the zero-copy design. So you don't actually need to do that. You essentially just have to execute the query again.

**Comment by tux-world** [comment]
Thank you very much for more information about that, i really dont doesnt
know this feature of Realm, i'm reading your introduced link, Thanks sir

**Comment by kneth** [comment]
@tux-world I hope that @Zhuinden's explanation has helped you understand Realm better. Please close the issue if your questions have been answered.

**Comment by tux-world** [comment]
@kneth Please let me to test today sir, Thanks

**Comment by beeender** [comment]
@tux-world Hope your issue gets solved. I am closing this now. Feel free to reopen it if further help needed.
