### ISSUE TITLE
Getting "RealmMigration must be provided" Exception

### ISSUE THREAD

**Issue by Bajranghudda1** [realm/realm-java#3343]
I'm getting "**io.realm.exceptions.RealmMigrationNeededException: RealmMigration must be provided Exception**"

Actually i'm using assetFile in reamconfiguration but first i'm creating a realm file like this way in another application:-

     RealmConfiguration realmConfiguration = new RealmConfiguration.Builder(this)
                .name("mydb")
                .schemaVersion(1)
                .deleteRealmIfMigrationNeeded()
                .build();
        Realm.setDefaultConfiguration(realmConfiguration);

And in my main application i'm using this (mydb) as assets and my migration code looks like:-

     RealmConfiguration config = new RealmConfiguration.Builder(this)
                .name(Realm.DEFAULT_REALM_NAME)
                .assetFile(this, "dn_db.realm")
                .schemaVersion(1)
                .build();
        Realm.setDefaultConfiguration(config);

And when i'm calling:-
Realm realm = Realm.getDefaultInstance();

getting exception "**io.realm.exceptions.RealmMigrationNeededException: RealmMigration must be provided**"

**Note:- I'm using same realm version 1.2.0** 
and removing app not working, bkz i'm still getting same error.

**Comment by Zhuinden** [comment]
Well it sounds like the two Realm schemas are mismatched.

Your classes that extend `RealmObject` must be the same, with same name and same fields.

**Comment by Bajranghudda1** [comment]
@Zhuinden 
I'm sure that both classes are same, because i'm using same model for both case.

**Comment by Bajranghudda1** [comment]
@Zhuinden 
Please see [this](http://stackoverflow.com/questions/37844308/android-error-loading-realm-db-file-from-assets), my issue is exactly same

**Comment by Bajranghudda1** [comment]
@Zhuinden 
Is there any way to successfully add a realm file in assets and then use it??
Because i don't any solution for it, Should i use core sqlite than?

**Comment by beeender** [comment]
What is the schema version of `dn_db.realm` ? You can try to add a migration to the configuration to get more detailed information about what is missing.

**Comment by Bajranghudda1** [comment]
@beeender 
In both case **schemaVersion(1)**

**Comment by beeender** [comment]
Can you try to add a migration to the configuration to get more detailed information about what is missing?

**Comment by Bajranghudda1** [comment]
Actually i don't know how to do that :-P

**Comment by beeender** [comment]
https://realm.io/docs/java/latest/#migrations Just put an empty migration block there .

**Comment by Zhuinden** [comment]
Well the only way for you to end up in a `RealmMigrationNeededException` is if your versions are mismatched.

        if (currentVersion != UNVERSIONED && currentVersion < requiredVersion && columnIndices == null) {
            realm.doClose();
            throw new RealmMigrationNeededException(configuration.getPath(), String.format("Realm on disk need to migrate from v%s to v%s", currentVersion, requiredVersion));
        }

Are you sure you are using the same Realm versions in both of your applications? There were breaking changes that require migration primarily in 0.83.0 and 0.89.0.

Essentially, validation fails at some point. And as @beeender said, you should try adding a migration, let Realm migrate itself, and it'll tell you what it's missing afterwards (that it expects 5 fields instead of 4, etc.)

Here is a basic migration to use

```
public class Migration implements RealmMigration {

    @Override
    public void migrate(final DynamicRealm realm, long oldVersion, long newVersion) {
        // no op
    }

    @Override
    public boolean equals(Object object) {
        return object != null && object instanceof Migration;
    }
 
    @Override
    public int hashCode() {
        return Migration.class.hashCode();
    }
}
```

Then in RealmConfiguration.Builder add

    .migration(new Migration())

**Comment by Bajranghudda1** [comment]
Yes @Zhuinden ,
**Well i tried it and problem is identified,** 

Well in first realm file (that i'm putting into assets) have only 2 tables, and and in my main application where i'm accessing that realm assets file have total more than 7 files.

Actually that 2 tables (in assets) have more than 10000 records so i fill the table entry using createAllFromJson("myjosnfile"), Do i fill these data in my main app? or is there any other way to include 2 table from assets and remaining from my main application.

So what should i do, i'm really a lit bit in confusion.

**Comment by Zhuinden** [comment]
> Well it sounds like the two Realm schemas are mismatched.
> Your classes that extend RealmObject must be the same, with same name and same fields.

In that case, your classes that extend RealmObject aren't the same. :tongue: 
ALL RealmObjects you have must be matched; OR you need to define the schema manually using a `@RealmModule` (although I don't think that's what you are trying to do)

> first realm file have only 2 tables, my other application where i'm accessing that realm assets file have total more than 7 files

In that case, your first Realm file should have all the "total more than 7 files" in the project when you create your asset realm.

**Comment by Bajranghudda1** [comment]
Thanks, @Zhuinden 

You people are really doing WoW :+1: , I applicate it.
 
Any other day I'll come back, because right now i have short of time. But yes I'm thankful to your whole team for your quick support. Keep on :100:
