### ISSUE TITLE
Realm One to many relationship insert value issue

### ISSUE THREAD

**Issue by Sutirth** [realm/realm-java#3345]
Goal: Successful one to many relationship

Expected Result: To form one to many relationship successful

Actual Result: unable to insert value in many relationship

Realm version(s):1.1.0

Step 1: My Database table and relationship

    public class AllGoalsDB extends RealmObject{
    
        private String updatedAt;
    
        private String title;
    
        private int status;
    
        private String createdAt;
    
        private String description;
    
        private RealmList<CompeletedDatesDB> compeletedDatesDBs;
        @PrimaryKey
        private int goalID;
    
        private String frequency;
    
        private String weekendBooster;
    
        private String sweatPoints;
    
        private String lastCompletedDate;
    }

    public class CompeletedDatesDB extends RealmObject {
    
        private String completedDate;
    }

Step 2 : My code for inserting values in the tables in a asyncTransaction

    for (int l = 0; l < syncApiModel.getData().get(entityNum).getGoalProgress().getUpdate().size(); l++) {
                                                   
                                                    AllGoalsDB allGoalsDB = realm.where(AllGoalsDB.class)
                                                            .equalTo("goalID", syncApiModel.getData().get(entityNum).getGoalProgress().getUpdate().get(l).getGoalId())
                                                            .findFirst();
    
    
                                                        if (allGoalsDB != null) {
                                                            for (int j = 0; j < syncApiModel.getData().get(entityNum).getGoalProgress().getUpdate().get(l).getProgress().size(); j++) {
                                                            CompeletedDatesDB compeletedDatesDB = realm.where(CompeletedDatesDB.class)
                                                                    .equalTo("completedDate",  syncApiModel.getData().get(entityNum).getGoalProgress().getUpdate().get(l).getProgress().get(j).getDate())
                                                                    .findFirst();
    
                                                            if (compeletedDatesDB != null) {
                                                                compeletedDatesDB.setCompletedDate( syncApiModel.getData().get(entityNum).getGoalProgress().getUpdate().get(l).getProgress().get(j).getDate());
                                                            } else {
                                                                compeletedDatesDB = realm.createObject(CompeletedDatesDB.class);
                                                                compeletedDatesDB.setCompletedDate( syncApiModel.getData().get(entityNum).getGoalProgress().getUpdate().get(l).getProgress().get(j).getDate());
                                                               allGoalsDB.getCompeletedDatesDBs().add(compeletedDatesDB);
                                                            }
    
                                                        }
                                                    }
                                                }

Step 3 : Response from server

    {
      "appStatusCode": 0,
      "data": {
        "update": [
          {
            "goalId": 165,
            "progress": [
              {
                "date": "2016-08-22",
                "sweatPoints": 3
              },
              {
                "date": "2016-08-23",
                "sweatPoints": 3
              },
              {
                "date": "2016-08-24",
                "sweatPoints": 3
              }
            ]
          }
        ]
    }

Attached screenshot of database table 
<img width="1174" alt="screenshot 2016-08-24 22 40 16" src="https://cloud.githubusercontent.com/assets/3212997/17940240/da4f6758-6a4b-11e6-9734-31221bd30f6b.png">

I have referred the docs and have constructed the same way. Whereas my other tables which have one to many relationship works exactly same way. But this is failing unable to find root cause. Can anyone guide me.

**Comment by Zhuinden** [comment]
Code a bit prettified:

``` java
Update update = syncApiModel.getData().get(entityNum).getGoalProgress().getUpdate();
for(int l = 0; l < update.size(); l++) {
    Goal goal = update.get(l);
    AllGoalsDB allGoalsDB = realm.where(AllGoalsDB.class).equalTo("goalID", goal.getGoalId()).findFirst();
    if(allGoalsDB != null) {
        for(int j = 0; j < goal.getProgress().size(); j++) {
            CompeletedDatesDB compeletedDatesDB = realm.where(CompeletedDatesDB.class)
                    .equalTo("completedDate", goal.getProgress().get(j).getDate())
                    .findFirst();
            if(compeletedDatesDB != null) {
                compeletedDatesDB.setCompletedDate(goal.getProgress().get(j).getDate());
            } else {
                compeletedDatesDB = realm.createObject(CompeletedDatesDB.class);
                compeletedDatesDB.setCompletedDate(goal.getProgress().get(j).getDate());
                allGoalsDB.getCompeletedDatesDBs().add(compeletedDatesDB);
            }
        }
    }
}
```

I can't help but feel like your problem stems from this query

``` java
CompeletedDatesDB compeletedDatesDB = realm.where(CompeletedDatesDB.class)
    .equalTo("completedDate",  syncApiModel.getData().get(entityNum).getGoalProgress().getUpdate().get(l).getProgress().get(j).getDate())
    .findFirst();
```

But I'm actually not sure. Reading through the code, it should not fail.

Do you know which part of your code executes, and doesn't do what you expect it to do?

**Comment by Sutirth** [comment]
@Zhuinden it should worked in my attached screenshot the completedDB table should have 3 entries but it shows only one entry. Secondly I have made other tables work same way

**Comment by Zhuinden** [comment]
I still think if you have multiple goals, then the completed dates that belong to the goals overwrite each other.

**Comment by Sutirth** [comment]
@Zhuinden  Then is your suggestion form a primary key as mentioned above and try it??

**Comment by Zhuinden** [comment]
Yup, please check if it fixes your issue ; if not, reply back and we'll look into it further

**Comment by Sutirth** [comment]
@Zhuinden 

I just changed one line and when I debug it I can see values enter in table. But when I see realm browser still there is no entry

if(compeletedDatesDB != null) {
                compeletedDatesDB.setCompletedDate(goal.getProgress().get(j).getDate());
            } else {
                compeletedDatesDB = realm.createObject(CompeletedDatesDB.class);
                compeletedDatesDB.setCompletedDate(goal.getProgress().get(j).getDate());
            }
 allGoalsDB.getCompeletedDatesDBs().add(compeletedDatesDB);



<img width="671" alt="screenshot 2016-08-25 12 23 06" src="https://cloud.githubusercontent.com/assets/3212997/17959586/e593fe8a-6abe-11e6-872a-370e6df3644c.png">

**Comment by kneth** [comment]
The query `realm.where(CompeletedDatesDB.class).equalTo("completedDate", syncApiModel.getData().get(entityNum).getGoalProgress().getUpdate().get(l).getProgress().get(j).getDate())` might be fulfilled for multiple objects if multiple goals have the dates in their list. @Zhuinden is right about that.

To ensure that you only get an object related to the goal, it might be easier to iterate through `allGoalsDB.getCompletedsDatesDBs()` to find the object.

**Comment by Sutirth** [comment]
@Kneth 

So I am bit confused at the moment how should I rectify this or do I need to add new field in the table

**Comment by Zhuinden** [comment]
You should either add a `@PrimaryKey` as I mentioned, or do it a bit more manually by

``` java
   CompeletedDatesDB completedDate = null;
   for(CompeletedDatesDB completed : allGoalsDB.getCompeletedDatesDBs()) {
        if(completed.getCompletedDate().equals(goal.getProgress().get(j).getDate()) {
              completedDate = completed;
              break;
        }
   }
   if(completedDate == null) {
        completedDate = realm.createObject(CompeletedDatesDB.class);
        allGoalsDB.getCompeletedDatesDBs().add(completedDate );
   }
   completedDate.setCompletedDate(goal.getProgress().get(j).getDate());
```

**Comment by Sutirth** [comment]
@Zhuinden  Will add a primary key and check

**Comment by Sutirth** [comment]
@Zhuinden Tried the above manual way. I debugged and I can see values inside in log

<img width="677" alt="screenshot 2016-08-25 14 02 07" src="https://cloud.githubusercontent.com/assets/3212997/17962102/dc16747e-6acc-11e6-9925-c23df7464efa.png">


But unable to see when I take dump of database file. This is still not working for me

**Comment by kneth** [comment]
By "dump", you mean that you copy the Realm file from your device/emulator and open it in the Realm Browser?

**Comment by Sutirth** [comment]
@Kneth Yes I mean the same

**Comment by Sutirth** [comment]
Okay something weird is happening I am trying to add primary key and I am getting migration exception


    public class CompeletedDatesDB extends RealmObject {
        @PrimaryKey
        private String goalIdAndDate;
    
        private String completedDate;
    }


     if(oldVersion == 20){
    
                    RealmObjectSchema compeletedDatesDB = schema.create("CompeletedDatesDB")
                                                            .addField("goalIdAndDate",String.class, FieldAttribute.PRIMARY_KEY);
    
                    oldVersion++;
                }


    RealmConfiguration realmConfiguration = new RealmConfiguration.Builder(this)
                                                .schemaVersion(21)
                                                .migration(new Migration())
                                                .build();


Stack Trace:


    E: java.lang.RuntimeException: Unable to start activity ComponentInfo{com.workoutguru.workoutcash/com.workoutguru.workoutcash.OnboardProfileActivity}: java.lang.IllegalArgumentException: Class already exists: CompeletedDatesDB
    E:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2416)
    E:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
    E:     at android.app.ActivityThread.-wrap11(ActivityThread.java)
    E:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
    E:     at android.os.Handler.dispatchMessage(Handler.java:102)
    E:     at android.os.Looper.loop(Looper.java:148)
    E:     at android.app.ActivityThread.main(ActivityThread.java:5422)
    E:     at java.lang.reflect.Method.invoke(Native Method)
    E:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
    E:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
    E:  Caused by: java.lang.IllegalArgumentException: Class already exists: CompeletedDatesDB



cc @Zhuinden @kneth

**Comment by Zhuinden** [comment]
Use `get` instead of create

**Comment by Sutirth** [comment]
@Zhuinden  Yes sorry corrected that but I end up getting this error now

java.lang.IllegalArgumentException: Illegal Argument: Field "goalAndDate" cannot be a primary key, it already contains duplicate values:

**Comment by Zhuinden** [comment]
That's weird. Unless you added the primary key field and it is null. In which case you probably won't be able to fix this with a migration, but with `deleteIfMigrationNeeded`.

**Comment by Sutirth** [comment]
So bit update:

    public class CompeletedDatesDB extends RealmObject {
    
    
        @Required
        private String goalAndDate;
    
        private String completedDate;
    }


    AllGoalsDB allGoalsDB = realm.where(AllGoalsDB.class)
                                                            .equalTo("goalID", syncApiModel.getData().get(entityNum).getGoalProgress().getUpdate().get(l).getGoalId())
                                                            .findFirst();
    
    
                                                        if (allGoalsDB != null) {
                                                            for (int j = 0; j < syncApiModel.getData().get(entityNum).getGoalProgress().getUpdate().get(l).getProgress().size(); j++) {
    
    
    
                                                            CompeletedDatesDB compeletedDatesDB = realm.where(CompeletedDatesDB.class)
                                                                    .equalTo("goalAndDate", syncApiModel.getData().get(entityNum).getGoalProgress().getUpdate().get(l).getGoalId()+"_"+syncApiModel.getData().get(entityNum).getGoalProgress().getUpdate().get(l).getProgress().get(j).getDate())
                                                                    .findFirst();
    
    
                                                              if (compeletedDatesDB != null) {
                                                                  compeletedDatesDB.setGoalAndDate(syncApiModel.getData().get(entityNum).getGoalProgress().getUpdate().get(l).getGoalId()+"_"+syncApiModel.getData().get(entityNum).getGoalProgress().getUpdate().get(l).getProgress().get(j).getDate());
                                                                  compeletedDatesDB.setCompletedDate( syncApiModel.getData().get(entityNum).getGoalProgress().getUpdate().get(l).getProgress().get(j).getDate());
                                                            } else {
                                                                compeletedDatesDB = realm.createObject(CompeletedDatesDB.class);
                                                                 compeletedDatesDB.setGoalAndDate(syncApiModel.getData().get(entityNum).getGoalProgress().getUpdate().get(l).getGoalId()+"_"+syncApiModel.getData().get(entityNum).getGoalProgress().getUpdate().get(l).getProgress().get(j).getDate());
                                                                compeletedDatesDB.setCompletedDate( syncApiModel.getData().get(entityNum).getGoalProgress().getUpdate().get(l).getProgress().get(j).getDate());
                                                               allGoalsDB.getCompeletedDatesDBs().add(compeletedDatesDB);
                                                            }
    
                                                        }
                                                    }


I still end up getting same thing

**Comment by Sutirth** [comment]
<img width="677" alt="screenshot 2016-08-25 16 17 19" src="https://cloud.githubusercontent.com/assets/3212997/17966488/6d100e06-6adf-11e6-8d4b-842890e30d37.png">

Only single record being inserted cc @Zhuinden
