### ISSUE TITLE
Is tril relationship possible?

### ISSUE THREAD

**Issue by Bajranghudda1** [realm/realm-java#3346]
For example

    public class Email extends RealmObject {
    private String address;
    private boolean active;
   private Contact contact;
    // ... setters and getters left out
}

    public class Contact extends RealmObject {
    private String name;
    private Email email;
    private RealmList<MyDemo> demolist;
    // ... setters and getters left out
}

public class MyDemo extends RealmObject {
    private String name;
    private Email email;
    // ... setters and getters left out
}

and i want to get result like this way.....
{"email":{"contect":[{"nfcurefno":12, "resident_at_home":"Y"}], {"contect1":[{"nfcurefno":12, "resident_at_home":"Y"}]}

I meant something like that, but i'm not able to get like above, i'm just getting {}

**Comment by Zhuinden** [comment]
Relevant code cleaned up:

**Comment by Zhuinden** [comment]
Relevant code cleaned up:

``` java
public class Email extends RealmObject {
    private String address;
    private boolean active;
    private Contact contact;
    // ... setters and getters left out
}

public class Contact extends RealmObject {
    private String name;
    private Email email;
    private RealmList<MyDemo> demolist;
    // ... setters and getters left out
}

public class MyDemo extends RealmObject {
    private String name;
    private Email email;
    // ... setters and getters left out
}
```

And the specified JSON is

```
{
	"email": {
		"contect": [{
			"nfcurefno": 12,
			"resident_at_home": "Y"
		}],
		{
			"contect1": [{
				"nfcurefno": 12,
				"resident_at_home": "Y"
			}]
		}
```

Technically nothing stops you from setting up those relations, but in order to help, we would need a **valid JSON**, and the transaction where you're setting it up (the code that doesn't work). Currently I don't have enough detail because I'm not sure what `nfcurefno` is, there is no `name` parameter, and the JSON isn't valid.

**Comment by kneth** [comment]
@Bajranghudda1 You might get some relevant info from https://realm.io/docs/java/latest/#json

**Comment by beeender** [comment]
@Bajranghudda1 Hope your issue gets solved. I am closing this now. Feel free to reopen it if further help needed.
