### ISSUE TITLE
Realm query giving outdated results in AsyncTask

### ISSUE THREAD

**Issue by flaushi** [realm/realm-java#3350]
Hi guys,
I am migrating to Realm currently, and I am nearly done.
So now I am experiencing *SOMETIMES* the following strange behaviour.
I do perform image procesing work in AsyncTasks.
As an example, I create a new Project on the UI thread, commit my transaction.
Then I start the background job, which queries the current project and computes sth. for it.
But sometimes, I get the old project in the background task!
```java
public class AppState extends RealmObject {
    public Project currentProject; // class Project extends RealmObject
}

// somewhere in Fragment:

(new AsyncTask<Void, Void, Void> {

		@Override
		protected void onPreExecute() {
			Realm r = Realm.getDefaultInstance();
			AppState appState = realm.where(AppState.class).findFirst(); // There does only exist one AppState in my Realm db
			r.beginTransaction();
			appState.currentProject = r.createObject(Project.class);
			r.setId(r.where(Project.class).max("id")+1); // autoincrement
			r.commitTransaction();
		}
		@Override
		protected Void doInBackground(Void...data) {
			Realm r = Realm.getDefaultInstance();
			AppState appState = r.where(AppState.class).findFirst();
			Log.d(TAG, appState.currentProject.getId()); // <----------sometimes gives me the OLD id!!!!!
		}
		@Override
		protected void onPostExecute(Void result) {}
	).execute();



```
Is it possible to wait for the Realm to finish all updates? It would be no problem for me to spend some time in doInBackground and wait for updated data..

Thank you very much in advance for your kind support!
Oliver 

#### Version of Realm and tooling
Realm version(s): 1.1.1

Android Studio version: 2.1.3

Which Android version and device: occurs on serveral devices, 4.2.2 to 5.x

**Comment by Zhuinden** [comment]
You don't seem to be closing your Realm in a finally block. Also, if you want to ensure that your background thread is 100% up to date, use a transaction (they block each other). 

However, please note that preExecute runs on the UI thread, so you should preferably use executeTransactionAsync, and start the AsyncTask in OnSuccess (instead of in onPreExecute)

**Comment by flaushi** [comment]
I left the closing out here for the sake of readability. In onPreExecute, I can access my realm instance that is managed by the Fragment, and in doInBackground i call close() in the very end.

But I'll give this asyncTransaction a try, thanks!

**Comment by Zhuinden** [comment]
Technically you should use executeTransactionAsync on the UI thread, and executeTransaction on the background thread (in `doInBackground`)

**Comment by flaushi** [comment]
Yeah, great help! Your hints were exactly what I was missing. Up to now, I always began and commited transactions (as in the code above). Now I have full control :) Thank you so much! 
Thread can be closed.
