### ISSUE TITLE
Human readable RealmQuery

### ISSUE THREAD

**Issue by JM-Agrimap** [realm/realm-java#3351]
When creating a complex realm query to filter data it would be very helpful when debugging to see a human readable version of the query especially where there are groups and you have conditional logic.

Generating a description using SQL-ish notation would be easy for most people to understand.

```
RealmQuery<Document> query = realm
.where(Document.class)
.equalTo("owner.id", 1)
.beginGroup()
.greaterThan("created", date)
.or()
.isNull("created)
.endGroup()
.contains("filename", "ABC");

boolean prettyFormat = true;
query.getStructuredDescription(prettyFormat);
```

Would become

```
SELECT "org.example.model.Documents"
WHERE owner.id = "1"
  AND (
    created > "2016-08-26 10:00:00"
    OR created IS NULL
  ) 
  AND filename contains "ABC"
```

**Comment by Zhuinden** [comment]
That doesn't seem hard to do and I can see it being useful when debugging weird conditional logic filled with groups and nots. 

Although this is a NoSQL db, the mapping looks obvious :D

**Comment by cmelchior** [comment]
Hi @JM-Agrimap 
It is an interesting suggestion. We won't rule it out, but it is not something we are considering at the moment.

What most likely will happen before is a shared text based query language across all our bindings. That will most likely look more like NSPredicate than SQL though.

**Comment by cmelchior** [comment]
Core now supports a `query_description` as part of supporting Partial Sync. My guess is that it should be trivial to add support for this now.

**Comment by ironage** [comment]
This should be possible because we have `Query::get_description()` which provides a query description text which is also valid syntax to run through the query parser.

**Comment by cmelchior** [comment]
We added support for `RealmQuery.getDescription()` a while back, so this should be supported now.
