### ISSUE TITLE
Realm stops calling onChange  though DB values are changed 

### ISSUE THREAD

**Issue by Nammari** [realm/realm-java#3359]
#### Goal
onChange should be called every time i do update as per documentation.
> What do you want to achieve?
onChange should be called every time i do update as per documentation.
#### Expected Results

> onChange should be called every time i do update as per documentation.

#### Actual Results
onChange not called though values in DB are changed !!

#### Steps & Code to Reproduce

> I have a button that changes a single value in DB i make quick repeated clicks to the button onChange is called but after sometime DB value is changed but onChange is never called.

#### Version of Realm and tooling
Realm version(s): 1.2.0

Android Studio version: 2.2 preview 7

Which Android version and device: android api level 23 Nexus 5X

**Comment by cmelchior** [comment]
Hi @Nammari Please provide some sample code or project that demonstrate that it doesn't work.

**Comment by Zhuinden** [comment]
> quick repeated clicks to the button onChange is called but after sometime DB value is changed but onChange is never called.

1.) make sure you retain a field reference to the `RealmResults<T>` that you're displaying (either in the adapter, or in the activity... just have a field reference)

2.) make sure you retain a field reference to the `RealmChangeListener` that you apply to your `RealmResults<T>` (either in the adapter or in the activity... just have a field reference)

So for example this will "fail over time":

    // this is bad
    results.addChangeListener(new RealmChangeListener() { ... });

Instead do this:

    private RealmResults<Something> results;
    private final RealmChangeListener realmChangeListener = new RealmChangeListener() {
        @Override
        public void onChange(Object element) {
            adapter.notifyDataSetChanged();
        }
    };
    
    // ...

    results = realm.where(Something.class).....findAll();
    results.addChangeListener(realmChangeListener);

**Comment by snowpong** [comment]
@Zhuinden @cmelchior Should it not be documented somewhere that a change listener goes dead if the RealmResult it's attached to goes out of scope?

Android Lint can suggest that a RealmResult<..> be converted from a field to a local variable, which will change the behavior for when attached change listeners are called. Is there a way to stop it suggesting this?

**Comment by Zhuinden** [comment]
@snowpong my workmate also ran into this issue when "removing lint errors", luckily code review caught it
