### ISSUE TITLE
use map problem

### ISSUE THREAD

**Issue by gushoubang** [realm/realm-java#3365]
As I know that it not't support map,I use like that http://stackoverflow.com/questions/35311755/realm-orm-how-to-deal-with-maps

```
class MyData extends RealmObject {
    private RealmList<MyMap> myMap;
}

class MyMap extends RealmObject {
    private String key;
    private MyClass value;
}
```
the myMap is the Map
but is error when I use Gson like this

com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Expected BEGIN_ARRAY but was BEGIN_OBJECT at line 1 column 2656 path $.layers[0].icons

because it's not array,it's object

**Comment by Zhuinden** [comment]
I'd say that's kinda because RealmList expects an array (because it's a list) but I have no specifics without seeing a sample json

**Comment by gushoubang** [comment]
but how can I Resolve hashmap

**Comment by Zhuinden** [comment]
I don't see HashMap anywhere in your question :disappointed:

**Comment by Zhuinden** [comment]
Seriously though, this doesn't qualify as a minimal verifiable complete example.

I don't know your JSON, I don't know where you are trying to use HashMap, and I don't know what `layers { icons {` is.

There isn't enough data here to answer your question.

**Comment by gushoubang** [comment]
OK,it's my reason,the all json is like that, the "icons" is map
 
`{"id":109116,"title":"一根线","level":12,"center":"116.36271970121324,40.032051578571654","org_id":10352,"creator":{"id":10352,"phone":"13021082046","nickname":"小谷","avatar":"/uploads/avatars/2016/8/23/d516bb047665f4ce5346d59ed3121b79.jpg"},"role":"管理员","mid":"OQxZHuXy0eUwSyR5I2WCiw","cooperation":[{"id":10352,"nickname":"小谷","phone":"13021082046","avatar":"/uploads/avatars/2016/8/23/d516bb047665f4ce5346d59ed3121b79.jpg","role":0}],"routing_layer_id":null,"default_template_id":69759,"viewer_template":"","location_timeout":600,"reply_templates":[{"id":69759,"map_id":109116,"name":"默认模板","fields":[{"name":"内容","type":"String"}],"has_img":true,"has_geo":false,"geo_tolerance":100,"editable":false}],"updated_at":"2016-08-30 17:32:30","created_at":"2016-06-20 17:17:55","layers":[{"type":"marker_layer","id":230134,"user_id":10352,"map_id":109116,"title":"标注图层1","uniform_title":"标题","show_fields":"标题,描述","display":"show","cooperation":[],"reply_template":"内容","reply_template_has_geo":false,"render_style":0,"uniform_config":{"icon_id":null,"color":"f86767","size":"s","symbol":"null","bubble":true,"is_cluster":false,"icon_url":null},"canvas_config":{"color":"#f86767","size":"BMAP_POINT_SIZE_SMALL","shape":"BMAP_POINT_SHAPE_CIRCLE"},"heatmap_config":{"gradient":"one","radius":20,"max":null,"field":null},"category_config":{"field":null,"is_number_field":false,"method":"unique","level":2,"is_categorized":true,"is_cluster":false,"size":"s","symbol":"null","bubble":true},"text_config":{"color":"#ffffff","size":12,"font":0,"show_decoration":true,"background_color":"#3ca0d3","border_color":"#ede8e4"},"sort_config":{"color":"f86767","size":"s","type":"a-z","is_cluster":false},"label_config":{"field":null,"style_type":0},"label":null,"label_style":0,"categories":[],"markers":[{"type":"marker","id":36932047,"marker_layer_id":230134,"uniform_title":"标题","locate_field":null,"lng":"116.315002","lat":"40.030063","cooperation":[],"icon":5292,"display":true,"created_at":"2016-08-30","user":10352,"imgs":[],"title":"点1","marker_attrs":[{"id":"36932047_475706","key":"标题","value":"点1"},{"id":"36932047_475707","key":"描述","value":""}]},{"type":"marker","id":36932048,"marker_layer_id":230134,"uniform_title":"标题","locate_field":null,"lng":"116.367319","lat":"40.029179","cooperation":[],"icon":15033,"display":true,"created_at":"2016-08-30","user":10352,"imgs":[],"title":"点2","marker_attrs":[{"id":"36932048_475706","key":"标题","value":"点2"},{"id":"36932048_475707","key":"描述","value":""}]}],"attrs":["标题","描述"],"users":{"10352":{"id":10352,"nickname":"小谷","phone":"13021082046","avatar":"/uploads/avatars/2016/8/23/d516bb047665f4ce5346d59ed3121b79.jpg"}},"icons":{"5292":{"id":5292,"url":"/uploads/icons/default/f86767-s-null.png","width":20,"height":33},"15033":{"id":15033,"url":"/uploads/icons/default/f86767-s-star.png","width":20,"height":33}}}]}`

**Comment by Zhuinden** [comment]
So you have icons that look like this

```
{
	"icons": {
		"5292": {
			"id": 5292,
			"url": "/uploads/icons/default/f86767-s-null.png",
			"width": 20,
			"height": 33
		},
		"15033": {
			"id": 15033,
			"url": "/uploads/icons/default/f86767-s-star.png",
			"width": 20,
			"height": 33
		}
	}
}
```

...uh. I'm actually not even sure how you'd get these with GSON. (although apparently you can do `Map<Long, Icon>`)

In reality, your icon that you have for key


                "15033": {
			"id": 15033,
			"url": "/uploads/icons/default/f86767-s-star.png",
			"width": 20,
			"height": 33
		}

The key itself doesn't provide additional information over the `id` parameter inside, so you could flatten this Map into a `RealmList` if you manually map from your JSON representation object to your RealmObject.

After all, this JSON would be simpler and would make more sense if it were

                "icons": [{
			"id": 5292,
			"url": "/uploads/icons/default/f86767-s-null.png",
			"width": 20,
			"height": 33
		}],

**Comment by gushoubang** [comment]
OK，I know.But is there any ohter method to support map？

**Comment by beeender** [comment]
@gushoubang I think it is fine to continue using the solution in your question. What you need is writing a customized GSON serializer. See https://realm.io/cn/docs/java/latest/#serialization

**Comment by beeender** [comment]
@gushoubang Hope your issue gets solved. I am closing this issue now, and feel free to reopen it if needed.
