### ISSUE TITLE
Refactor async queries

### ISSUE THREAD

**Issue by beeender** [realm/realm-java#3372]
- [ ] Use `Results` from ObejctStore
- [ ] Just use async query from OS? Maybe remove FIXME in `RealmNotifier`?
- [ ] Move `HandlerControler` and `AndroidNotifier` to `io.realm.internal`
- [ ] FIXME in `AndroidNotifier`, simplify the calling routing?
- [ ] Check the use case in https://github.com/realm/realm-java/issues/3668#issuecomment-255378795. `Realm.where(AllTypes.class).findAllAsync().where().findAllAsync()`. It is useful to build async queries for https://github.com/realm/realm-java/issues/3668#issuecomment-255351407

**Comment by cmelchior** [comment]
This is a prerequisite for #989

**Comment by beeender** [comment]
moved todos to #3834 . no need to keep this one opened.

**Comment by cmelchior** [comment]
Folding this into #3834
