### ISSUE TITLE
io.realm.internal.RealmProxyMediator.copyOrUpdate

### ISSUE THREAD

**Issue by mhgk** [realm/realm-java#3373]
Hey realm guys.
Iam using both Realm plugin 1.1.0 and the RealmSearchView 0.9.4. When building the apk i get a DublicateFileExeption from the .so files.

#### Goal

something that works :)

#### Expected Results

Realm gets updated with the list of data

#### Actual Results

FATAL EXCEPTION: main
Process: dk.domea.domeabeboerapp, PID: 9536
  java.lang.AbstractMethodError: abstract method "io.realm.RealmObject io.realm.internal.RealmProxyMediator.copyOrUpdate(io.realm.Realm, io.realm.RealmObject, boolean, java.util.Map)"
 at io.realm.Realm.copyOrUpdate(Realm.java:1166)
 at io.realm.Realm.copyToRealm(Realm.java:697)
 at io.realm.Realm.copyToRealm(Realm.java:735)
at dk.domea.domeabeboerapp.utils.FakeDataCreator.createFakeAddresses(FakeDataCreator.java:23)
at dk.domea.domeabeboerapp.FindAddressActivity.onStart(FindAddressActivity.java:76)
at android.app.Instrumentation.callActivityOnStart(Instrumentation.java:1265)
at android.app.Activity.performStart(Activity.java:6915)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3217)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3350)
at android.app.ActivityThread.access$1100(ActivityThread.java:222)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1795)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:158)
at android.app.ActivityThread.main(ActivityThread.java:7229)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)
08

#### Steps & Code to Reproduce

packagingOptions {
        pickFirst("lib/armeabi/librealm-jni.so")
        pickFirst("lib/x86/librealm-jni.so")
        pickFirst("lib/arm64-v8a/librealm-jni.so")
        pickFirst("lib/armeabi-v7a/librealm-jni.so")
        pickFirst("lib/mips/librealm-jni.so")
        pickFirst("lib/x86_64/librealm-jni.so")

Using above enables me to build and run the apk. However when trying to add data with

#### Code Sample

Realm realm = Realm.getDefaultInstance();
        realm.beginTransaction();
        realm.copyToRealm(list);
        realm.commitTransaction();

 i get this error instead:
 java.lang.AbstractMethodError: abstract method "io.realm.RealmObject io.realm.internal.RealmProxyMediator.copyOrUpdate(io.realm.Realm, io.realm.RealmObject, boolean, java.util.Map)"

Any suggestions would be very appreciated?                                                                          
``

#### Version of Realm and tooling
Realm version(s): 1.1.0

Android Studio version: 2.1.3

Which Android version and device: -

**Comment by Zhuinden** [comment]
This eerily resembles [this SO question](http://stackoverflow.com/questions/39244313/abstractmethoderror-realmproxymediator-getmodelclasses?noredirect=1#comment65826318_39244313), and I'd say you have to make sure you are not including 0.82.2 as a compile dependency.

If you aren't, then try a clean + rebuild.

**Comment by mhgk** [comment]
Well that was my own stackoverflow you refered to (thought i solved it).

Iam not including that, explicitly anyways. 
This is my dependenciese.
 dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:24.2.0'
    compile 'com.android.support:appcompat-v7:24.2.0'
    compile 'com.squareup.retrofit2:retrofit:2.0.2'
    compile 'com.squareup.retrofit2:converter-gson:2.0.0'
    compile 'com.jakewharton.timber:timber:4.1.2'
    compile 'joda-time:joda-time:2.9.1'
    compile 'com.android.support:design:24.2.0'
    compile 'com.android.support:recyclerview-v7:24.2.0'
    compile 'com.android.support:cardview-v7:24.2.0'
    compile 'com.android.support:support-v4:24.2.0'
    compile 'com.github.thorbenprimke:realm-searchview:0.9.4'
}

**Comment by zaki50** [comment]
Hi @mhgk 

As shown blow, `com.github.thorbenprimke:realm-searchview:0.9.4` contains `io.realm:realm-android:0.87.1`. `io.realm:realm-android` is old library and should not be used.

```
+--- com.github.thorbenprimke:realm-searchview:0.9.4
|    \--- com.github.thorbenprimke:realm-recyclerview:0.9.12
|         +--- com.android.support:design:23.1.1
|         |    +--- com.android.support:appcompat-v7:23.1.1 -> 24.1.1 (*)
|         |    +--- com.android.support:recyclerview-v7:23.1.1 -> 24.1.1 (*)
|         |    \--- com.android.support:support-v4:23.1.1 -> 24.1.1 (*)
|         +--- io.realm:realm-android:0.87.1
|         +--- com.android.support:recyclerview-v7:23.1.1 -> 24.1.1 (*)
|         \--- com.github.TonicArtos:SuperSLiM:ed0ba4b4d2
|              \--- com.android.support:recyclerview-v7:22.1.1 -> 24.1.1 (*)
```

The latest version (`0.9.6`) of realm-searchview seems to solve this issue.

**Comment by mhgk** [comment]
Jeps i found out. I didnt i have the latest searchview dependency, which caused that old realm to be imported.
