### ISSUE TITLE
RealmList to RealmResult

### ISSUE THREAD

**Issue by jjorian** [realm/realm-java#3374]
I have a JSON String and want Copy Datas to RealmResult, I write a Customize JSON Ecoder and work right
but I want Create a RealmResult to RealmAdaptor with no Save Data in RealmDatabase 
connat convert RealmList to Realm Result?
Please Help me For this problem ?

```
    public static RealmResult<FactorHead> FactorHeadList(String JsonArray)
    {
        RealmList<FactorHead>  ret=new RealmList<>();

        int count=0;
        try {
            final JSONArray factorHead = new JSONArray(JsonArray);
            for (int i = 0; i < factorHead.length(); i++) {
                final JSONObject row = factorHead.getJSONObject(i);
                FactorHead h = new FactorHead();
                h.setID(i);
                h.setFNum(row.getInt(FactorHead.COLUMN_FNum));
                h.setFDate(row.getString(FactorHead.COLUMN_FDate));
                h.setFKind(row.getInt(FactorHead.COLUMN_FKind));
                h.setHesab(row.getString(FactorHead.COLUMN_Hesab));;
                h.setSanadNum(row.getInt(FactorHead.COLUMN_SanadNum));
                h.setStrhCode(row.getInt(FactorHead.COLUMN_StrhCode));
                h.setFDiscount(row.getDouble(FactorHead.COLUMN_FDiscount));
                h.setPocket(row.getDouble(FactorHead.COLUMN_Pocket));
                h.setFComment(row.getString(FactorHead.COLUMN_FComment));
                h.setNumber(row.getString(FactorHead.COLUMN_Number));
                h.setUserID(row.getInt(FactorHead.COLUMN_UserID));
                h.setUserID(row.getInt(FactorHead.COLUMN_ID));
                h.setUserID(row.getInt(FactorHead.COLUMN_TableID));
                h.setStatus(row.getString(FactorHead.COLUMN_Status).charAt(0));
                h.setRegisterNum(row.getInt(FactorHead.COLUMN_RegisterNum));

                //getInstance().getRealm().beginTransaction();
                //getInstance().getRealm().copyToRealm(h);
                //getInstance().getRealm().commitTransaction();
                ret.add(h);
                count++;
            }

        }catch (Exception ee)
        {
            ee.printStackTrace();
        }
       return ret;

    }
```

#### Version of Realm and tooling
Realm version(s): ?1.1.0

Android Studio version: ?2.1.2

Which Android version and device: ?5.1.0

**Comment by Zhuinden** [comment]
... Ummm. If you want to show data in a RealmBaseAdapter or RealmRecyclerViewAdapter, then you must provide a managed OrderedRealmCollection to your adapter, which means you must persist the data to database and then define a query with `realm.where(FactorHead.class)` that returns the elements you want to show in your adapter...

**Comment by zaki50** [comment]
How about using another in-memory Realm?
in-memory Realm is deleted when the Realm instance is closed.

**Comment by jjorian** [comment]
Ops!!Thanks, This is not good but Realm is very Likable for me.
I create two data adapter in one fragment and somtime load from realmdatabase(RealmResult) and other Load From JSON To RealmList
But I cant run a search query in RealmList.
in your Opinion we can have a another sulotion?

**Comment by zaki50** [comment]
There is no way to create `RealmResults` for models not stored in any Realm.

Why using another in-memory Realm for the models converted from JSON is not good for you?

**Comment by jjorian** [comment]
I have  one Model and RealmAdaptor For FactorHead - Can i use from this with Main Realm Database toghether  with in-memory in one application?

**Comment by zaki50** [comment]
yes

**Comment by zaki50** [comment]
to use another Realm database, please prepare another RealmConfiguration like:

```
        RealmConfiguration configForInMemRealm = new RealmConfiguration.Builder(this)
                .name("temporary.realm")
                .inMemory()
                .build()
```

and then `Realm inMemoryRealm = Realm.getInstance(configForInMemRealm)`
