### ISSUE TITLE
RealmRecyclerViewAdapter example not working

### ISSUE THREAD

**Issue by Shajeel-Afzal** [realm/realm-java#3381]
I am trying to create RealmRecyclerAdapter following https://github.com/realm/realm-android-adapters but it is giving me the error about RealList.real, I was trying it with the latest version of Realm library 1.2.1 and also tried with 1.0.1 version because that is used by the example project but even then it is giving the same error.

The error is specifically at line number 158 in this file https://github.com/realm/realm-android-adapters/blob/master/adapters/src/main/java/io/realm/RealmRecyclerViewAdapter.java

`realmList.realm.handlerController.addChangeListenerAsWeakReference(listener);`

I want to create RecyclerAdapter that will automatically update when the Realm database/table will be updated.

Android Studio version: 2.1.3

**Comment by Zhuinden** [comment]
You should use realm-android-adapters 1.3.0 with realm-android 1.2.0

**Comment by Shajeel-Afzal** [comment]
@Zhuinden Thanks for your comment, I have included `compile 'io.realm:android-adapters:1.3.0'` but still i am facing the same problem. Can you please check?

**Comment by Shajeel-Afzal** [comment]
Thanks @Zhuinden, It solved my problem. However now, i am looking for a way to implement search easily.

**Comment by Zhuinden** [comment]
@OnTextChanged(R.id.edit_text)
    public void editTextChanged(CharSequence charSequence) {
        realmRecyclerViewAdapter.updateData(realm.where(Something.class).contains("someField", charSequence.toString()).findAllAsync());
    }
