### ISSUE TITLE
Info: Clarification on pr #3370 and monitor threads

### ISSUE THREAD

**Issue by diegomontoya** [realm/realm-java#3383]
@beeender pr #3370

Please clarify  latest changelog regarding the below since the warning directly applies to us and may  cause huge resource impact. We have 10+ realmConfigs. 

>The known problem is for every RealmConfiguration, a monitor thread will
be created which is not ideal for app which is using multiple
RealmConfiguration.

- Monitor thread count: Is this monitor thread per realm, per thread? If I open same realm in 2 different threads, how many monitor threads are there?

- Monitor thread life cycle: Is the thread created on first realm open and destroyed on last realm close?

Thanks

**Comment by beeender** [comment]
> Monitor thread count: Is this monitor thread per realm, per thread? If I open same realm in 2 different threads, how many monitor threads are there?

It is per Realm. If same Realm opened in two different threads, only one monitor thread is there. If you opened two Realms in one thread, two monitor threads will be there.

> Monitor thread life cycle: Is the thread created on first realm open and destroyed on last realm close?

Yes

And I created an issue here https://github.com/realm/realm-object-store/issues/152 . I Knew you are using multiple Realms, so the master(snapshot) might not be feasible  for you right now.

**Comment by diegomontoya** [comment]
@beeender Thanks for the info. Didn't catch the issue you already created before creating this. Consider this a duplicate.

**Comment by Zhuinden** [comment]
@diegomontoya in case you're curious, it's because each Realm belonging to a RealmConfiguration requires a daemon thread which uses the vague simplified logic below:

     while(realm.waitForChange()) {
         realm.notifyRealmChanged();
     }

It's to support multi-process notifications.

**Comment by diegomontoya** [comment]
@Zhuinden Getting off topic a bit but on Android is there a diff between non-daemon/daemon threads? I am under the assumpting that the app/jvm gets killed, all threads die.

Something like this could avoid the n x monitor thread problem. Assume there is 1 global for-all realm monitory thread, per process, that use a udp/tcp socket (or named pipe, or whatever that is multi-process accessible). Realmcore is only one doing the socket/shm writing while all the java process read:

```java
while() {
   int realmIdChanged = socket.readInt(); 
   realmMap.get(realmIdChanged).notifyRealmChanged();
}
```

**Comment by Zhuinden** [comment]
...don't forget I'm not an official Realm person, only @beeender knows the answer when we go so deep into threading :smile:

**Comment by beeender** [comment]
ObejctStore has different implementations for notification. The one use by realm-java `master` is https://github.com/realm/realm-object-store/blob/master/src/impl/android/external_commit_helper.cpp which is waiting on a named pipe :)
