### ISSUE TITLE
Regression issue after #3379 merged. Different default values when create with JSON Stream

### ISSUE THREAD

**Issue by beeender** [realm/realm-java#3386]
This is a regression issue after #3379 merged.

The APIs to create `RealmObject` from JSON stream will have different behaviours from other APIs.
Underneath, it is using the non-managed object's default constructor to create an object, then set its fields from JSON. Those absent field in JSON will have the default value set by the default non-managed object's constructor.

See comments from https://github.com/realm/realm-java/pull/3379#discussion_r77316752

It looks like it only effect the `create` part, not the `update` part right?
I see 3 choices:

1) Accept the current solution and document the breaking change 
2) Rewrite `createFromJsonStream` to create JSONObject instead and return the result from `createObjectFromJson(jsonObj)`
3) Add support for #777 

For expendiency, I would probably just go with 1) now and make an issue for looking into 2/3 in th next week or two, because we need a better solution before releasing anything publically.

If 3) is indeed fairly easy to do that would be awesome, if not I think we should do 2.

**Comment by zaki50** [comment]
If we can fix #2536, fixing #777 is very easy (just enabling the transforming in the constructor). However, it seems a bit difficult than fixing #777 directly.

**Comment by beeender** [comment]
#3397 fixed this.
