### ISSUE TITLE
Incorrect javadoc

### ISSUE THREAD

**Issue by xbezdeka** [realm/realm-java#3389]
Javadoc for method <code>public Builder encryptionKey(byte[] key)</code> in <code>RealmConfiguration.Builder</code> states:

/* Sets the 64 bit key used to encrypt and decrypt the Realm file. */

That means, that client should provide 8-byte key, but actually 64-bytes key is required, otherwise exception is thrown:

java.lang.IllegalArgumentException: The provided key must be 64 bytes. Yours was: 8

**Comment by cmelchior** [comment]
Ups, your right. That should get fixed
