### ISSUE TITLE
OrderedRealmCollection.first()/last() and default values

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#3399]
From http://stackoverflow.com/questions/35287974/android-realm-prevent-exception-with-first-method-and-empty-database/35314169?noredirect=1#comment65982070_35314169

Right now `RealmCollection.first()/last()` will throw `IndexOfOutRangeException` if called on an empty collection. This means that anyone using these API's have to write annoying boilerplate code around it like:

```
RealmResults<Foo> results = query.findAllSorted("endDate", Sort.DESCENDING);
Foo obj = (result.size() > 0) ? result.first() : null;
```

Instead we should make it easier to provide a default value in case of an empty list, this could e.g be:

```
RealmResults<Foo> results = query.findAllSorted("endDate", Sort.DESCENDING);
Foo obj = result.firstOrNull(); // Option A
Foo obj2 = result.first(null); // Option B, provide your own default value
```

Option B is more general, but I am not sure how useful it would be as `null` is probably used the majority of times.

Option A expresses the intent more clearly and is easier to autocomplete.

**Comment by spl** [comment]
> Option B is more general, but I am not sure how useful it would be as `null` is probably used the majority of times.

I'm not sure I would make that assumption. I find option B more attractive because it is explicit, flexible, and short.

**Comment by zaki50** [comment]
`first()` and `last()` are declared in `OrderedRealmCollection` not `RealmCollection`.
( It's minor thing, though...
