### ISSUE TITLE
 java.lang.IllegalStateException without message

### ISSUE THREAD

**Issue by ar-g** [realm/realm-java#3400]
I have this kind of stacktrace which doesn't say much when I'm trying to get a field from an object. 
```
Caused by java.lang.IllegalStateException
io.realm.internal.UncheckedRow.nativeGetString (SourceFile)
io.realm.internal.UncheckedRow.getString (SourceFile:153)
```
In the code I doing network call and updating-creating object in realm 
```java
realm.copyToRealmOrUpdate(item)
```
then just trying to get a field and getting that exception, I suppose that this object even not managed by realm

**UPDATE**

Part of model class 
```
@RealmClass public class Order implements RealmModel {
  @PrimaryKey @SerializedName("uid") @Expose private String uid;
```
code where it get used
```java
final Order orderFromHistory = storageInteractor.findByFieldAndCopy(Order.class, Order.ID, ooUID);
    return Observable.concat(

        Observable.just(orderFromHistory)
            .doOnNext(__ -> Logr.e("Getting history order from storage"))
            .filter(RxPretty::notNull)
            .filter(Order::hasDriver),

        networkService.
            .orderStatus()
            .doOnNext(__ -> Logr.e("Getting history order from network"))
            .flatMap(order -> networkService
                .feedbacks(order.getDriver().getUid())
                .doOnNext(feedbacks -> {
                  order.getDriver().setFeedbacks(feedbacks);
                  update(order);//updating in realm
                })
                .subscribeOn(Schedulers.io())
                .map(__ -> order))
    ).take(1)
     .observeOn(AndroidSchedulers.mainThread())
     .subscribe(__ -> Navigator.toOrderDetails(getActivity(),order.getUid())
```
Version: 1.1.1

**Comment by cmelchior** [comment]
Hi @ar-g 
Can you post a more complete example with your model class?

**Comment by Zhuinden** [comment]
Also, please specify your Realm version.

**Comment by ar-g** [comment]
@Zhuinden so I should switch to `mainThread` before updating entity in realm?

**Comment by Zhuinden** [comment]
What? No! We need the transaction code to help, though.

**Comment by Zhuinden** [comment]
Can we please also see the `update(order)` method?

**Comment by ar-g** [comment]
@Zhuinden `update` is transaction code

```java
    execute(realm -> realm.copyToRealmOrUpdate(item));//execute just doing transaction and closing realm
```

**Comment by Zhuinden** [comment]
What happens if you add

        Observable.just(orderFromHistory)
            .doOnNext(__ -> Logr.e("Getting history order from storage"))
            .filter(RxPretty::notNull)
            .filter(Order::hasDriver)
            .subscribeOn(AndroidSchedulers.mainThread()), // this line

And also

        networkService.
            .orderStatus()
            .subscribeOn(Schedulers.io())

And also

     .take(1)
     .subscribeOn(AndroidSchedulers.mainThread()),
     .observeOn(AndroidSchedulers.mainThread())

I'm not entirely sure though. Rx confuses me from time to time, and same for Kotlin

**Comment by ar-g** [comment]
@Zhuinden current code works perfectly fine the exception I get is from Crashlytics. But I will try to change and see what is going on in production then

**Comment by Zhuinden** [comment]
Oh, in that case I'm not sure what's going on and you should ignore what I said. :cry:

**Comment by beeender** [comment]
It is very strange that it doesn't have an exception message. @ar-g Can you check the raw exception in the Crashlytics to see if there is more details about the exception?

**Comment by kneth** [comment]
@ar-g I'm closing the issue. If you have new information, please reopen or create new issue.
