### ISSUE TITLE
RealmDeleteListener for Migration

### ISSUE THREAD

**Issue by riyase** [realm/realm-java#3401]
#### Goal

> It will be great if RealmConfiguration.Builder is expecting an interface  in deleteRealmIfMigrationNeeded() method so that we clear/reinitialize to App defaults.
Is there any existing way to do this?

#### Code Sample

```java

public interface RealmDeleteOnMigrationListener {
    public void onDeleteRealm() {
        //clear App cache
        // set App defaults
    }
}

RealmConfiguration config0 = new RealmConfiguration.Builder(context)
                .name(REALM_FILE)
                .schemaVersion(0)
                .deleteRealmIfMigrationNeeded(deleteListener)
                .encryptionKey(key.getBytes())
                .build();
```

**Comment by cmelchior** [comment]
`assetFile` and `initialData` should both be called when the Realm is deleted. In your case it sounds like you should look at `RealmConfiguration.Builder.initialData()`?

**Comment by riyase** [comment]
thank you. initailData() will do the work..
