### ISSUE TITLE
RealmObjects don't pass lint when implementing Parcelable

### ISSUE THREAD

**Issue by ghost** [realm/realm-java#3406]
#### Goal

Make a RealmObject, that has been copied from realm, Parcelable
#### Expected Results

The realm object can be passed as a Parcelable and pass lint tests
#### Actual Results

The proxy object for the realm object doesn't declare a CREATOR field, causing a lint error that cannot be suppressed.
#### Steps & Code to Reproduce

Create a RealmObject that implements Parcelable and run lint
#### Version of Realm and tooling

Realm version(s): 1.2.0

Android Studio version: 2.1.3

**Comment by Zhuinden** [comment]
Does this happen if you're using `Parceler` library also?

**Comment by kdaypossible** [comment]
It works and runs fine. I haven't tried using that library. However, Lint is listing it as an error. It's breaking build automation since lint is enabled and aborts on error.

**Comment by beeender** [comment]
I think we can easily fix this by adding a `@SuppressLint("ParcelCreator")` in the generated proxy class?

**Comment by mhmtk** [comment]
Anyone found a solution for this? Is using the Parceler library the way to go?
