### ISSUE TITLE
RealmPrimaryKeyConstraintException: Value already exists: 0

### ISSUE THREAD

**Issue by drduan** [realm/realm-java#3412]
Realm realm = Realm.getDefaultInstance();
                int nextID =  realm.where(Ticket.class).max("id").intValue() + 1;
				realm.beginTransaction();
				Ticket t = realm.createObject(Ticket.class); // Create a new object
				t.id = nextID;
				t.fee = Double.parseDouble(fee.getText().toString().replace('￥','0'));
				t.p_count = t.fee * lvTicketPassengerStep3.getChildCount();
				t.pay_status = 0;
				t.t_date = new Date().getTime();
				t.trainID = train_ID.getText().toString();
				realm.commitTransaction();

#### Version of Realm and tooling
RealmPrimaryKeyConstraintException: Value already exists: 0

**Comment by Zhuinden** [comment]
You need to use `Ticket t = realm.createObject(Ticket.class, nextID)`

**Comment by drduan** [comment]
thank you you
