### ISSUE TITLE
Permission denied in io_realm_internal_SharedGroup.cpp

### ISSUE THREAD

**Issue by mihirjoshi21** [realm/realm-java#3413]
Thank you for making Realm bug free but there is still one issue. 

```
Caused by: io.realm.exceptions.RealmError: Unrecoverable error. Permission denied in io_realm_internal_SharedGroup.cpp line 113
	at io.realm.internal.SharedGroup.createNativeWithImplicitTransactions(Native Method)
	at io.realm.internal.SharedGroup.a(SharedGroup.java:95)
	at io.realm.internal.SharedGroup.<init>(SharedGroup.java:74)
	at io.realm.internal.o.<init>(SharedGroupManager.java:49)
	at io.realm.a.<init>(BaseRealm.java:86)
	at io.realm.j.<init>(Realm.java:135)
	at io.realm.j.b(Realm.java:233)
	at io.realm.j.a(Realm.java:214)
	at io.realm.l.a(RealmCache.java:126)
	at io.realm.j.m(Realm.java:160)
	at com.conem.app.pocketthesaurus.display.b.a(ActivitySplash.java:144)
	at com.conem.app.pocketthesaurus.display.b.doInBackground(ActivitySplash.java:99)
	at android.os.AsyncTask$2.call(AsyncTask.java:295)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more
```
The above log is from playstore this is from Crashlytics. http://crashes.to/s/305f76efbc2
It is linked to #2762  

I have been using Realm before 0.70.0 and this bug is there since the beginning. Almost 5 out of 400 daily users who download my app are experiencing it. 

#### Version of Realm and tooling
Realm version(s): ? 1.2.1

Android Studio version: ? 2.1.1

Which Android version and device: ?

**Comment by Zhuinden** [comment]
Are you writing the Realm to the external storage?

**Comment by mihirjoshi21** [comment]
@Zhuinden  In Internal Storage.

**Comment by Zhuinden** [comment]
.... That is strange. I haven't seen this before in internal storage. 

Does this happen on first install?

**Comment by mihirjoshi21** [comment]
I don't know that but there is one thing I know for sure is it happens whenever the  database is accessed from inside the Service.

**Comment by beeender** [comment]
How does your `RealmConfiguration` look like?

**Comment by mihirjoshi21** [comment]
It doesn't have any encryption if that is what you want to know.

```
RealmConfiguration.Builder(context)
                .name("UserDatabase.realm")
                .schemaVersion(1)
                .migration(new Migration())
                .build();
```

**Comment by beeender** [comment]
From the backtrace, it doesn't look like it is the first time the app get a Realm instance. Can you confirm this? What I want to know is if app has opened the Realm file before then suddenly has this permission issue in a AsyncTask ...

**Comment by mihirjoshi21** [comment]
The very first time when the app opens, it copies the pre-shipped Realm file in internal storage, calls the configuration and makes the realm instance.

**Comment by Zhuinden** [comment]
...copies the pre-shipped file? I don't see `assetFile()` anywhere

**Comment by mihirjoshi21** [comment]
Not using `assetFile()` but copying database manually using outputstream​ from device raw folder.

**Comment by Zhuinden** [comment]
Does this happen in `Application.onCreate()`?

**Comment by mihirjoshi21** [comment]
It's happening right after I copied the database to internal storage and calling RealmConfiguartion from inside the Asynctask.

**Comment by mihirjoshi21** [comment]
Any update on this? I just received a review from someone having Galaxy S2 (GT-I9100P) with android 4.0.3 - 4.0.4 and he was complaining about the app not loading in his device.

**Comment by beeender** [comment]
@mihirjoshi21 Can your user always reproduce this issue? Is it possible to ask him help to do some testing?

**Comment by mihirjoshi21** [comment]
@beeender He is kind of pissed off with the app so I guess I need to arrange the device from somewhere myself.

**Comment by beeender** [comment]
@mihirjoshi21 If you have plan to release a new apk recently, I suggest you to move to `assetFile()` than copying through the stream since it will check if there are any instances opened in the same processes to avoid corrupt the realm file. But if you can reproduce this an any devices, please let us know. We'd happy to help check what is going wrong.

**Comment by mihirjoshi21** [comment]
When will you release v2.0.0? I will move to assetFile() when that will be released.

**Comment by kneth** [comment]
@mihirjoshi21 As you might have seen, we have release 2.0.0.

**Comment by mihirjoshi21** [comment]
Yes but it too has some known issues.I am waiting for 2.1.0 before I update the app.

**Comment by kneth** [comment]
@mihirjoshi21 Thanks for the patience.

**Comment by tamtom** [comment]
@Zhuinden , @kneth 
I have the same error on that 
`Fatal Exception: io.realm.exceptions.RealmError: Unrecoverable error. Permission denied in io_realm_internal_SharedGroup.cpp line 113
       at io.realm.internal.SharedGroup.createNativeWithImplicitTransactions(SharedGroup.java)
       at io.realm.internal.SharedGroup.openSharedGroupOrFail(SharedGroup.java:95)
       at io.realm.internal.SharedGroup.(SharedGroup.java)
       at io.realm.internal.SharedGroupManager.(SharedGroupManager.java)
       at io.realm.BaseRealm.(BaseRealm.java)
       at io.realm.Realm.(Realm.java)
       at io.realm.Realm.createAndValidate(Realm.java:233)
       at io.realm.Realm.createInstance(Realm.java:214)
       at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:126)
       at io.realm.Realm.getInstance(Realm.java:178)
     `
and I call get instance in onCreate 
`@Override
    public void onCreate() {
        super.onCreate();
        uiHandler = new Handler();
        long resetNotCompletedTasks = resetNotCompletedTasks();
    `
the restNotCompletetTasks(); is 
`private long resetNotCompletedTasks() {
        return RealmWrapper.getInstance().resetAllMediaChatTasks();
    }
` 
can you help me please

**Comment by Zhuinden** [comment]
@tamtom what is your Realm version

**Comment by tamtom** [comment]
@Zhuinden
realm version   io.realm:realm-gradle-plugin:1.2.0 
I'm using the default realm  like this 

```
        chatRealmConfiguration = new RealmConfiguration
                .Builder(App.getInstance())
                .name(CHAT_REALM_FILE)
                .schemaVersion(CHAT_REALM_VERSION)
                .modules(new ChatModule())
                .migration(new ChatRealmMigration())
                .build();

```

**Comment by Zhuinden** [comment]
@tamtom do you by chance know the type of the device?

**Comment by tamtom** [comment]
@Zhuinden there is no specific device

**Comment by soshial** [comment]
I had ths problem on LG G5 with `'io.realm:realm-gradle-plugin:1.1.1'`

**Comment by Zhuinden** [comment]
Something similar can still happen as per https://github.com/realm/realm-java/issues/5715
