### ISSUE TITLE
Query by RealmList element count (less than, equal, greater than, ...)

### ISSUE THREAD

**Issue by Zhuinden** [realm/realm-java#3414]
> **Feature Request**: Just fill in the first two sections below.

Based on [SO question](http://stackoverflow.com/questions/39380443/realm-query-for-all-objects-with-realmlist-containing-less-then-a-given-number-o)

#### Goal

> What do you want to achieve?

Query by number of elements in RealmList many relation

#### Expected Results

There should be a method for this

#### Actual Results

There is no way to do this

#### Version of Realm and tooling
Realm version(s): 1.2.0

**Comment by beeender** [comment]
Thank for doing my job! :grimacing:

**Comment by Zhuinden** [comment]
There's actually an article on how [it's easy to misinterpret the grimacing emoticon because it looks hostile](http://www.mirror.co.uk/tech/grimace-face-emoji-causing-awkward-7754205). Fascinating. 

That does not look like a grimace, lol.

**Comment by cmelchior** [comment]
Sorry to ruin your fun @beeender , but we are already tracking it here https://github.com/realm/realm-java/issues/1598  😄 

It is actually already supported by the underlying core database, we just need to find a good way to expose it. There is already a few suggestions in #1598.

I'll close this as a duplicate.

**Comment by Zhuinden** [comment]
....ah, I guess I missed that one, duplicate indeed

**Comment by cmelchior** [comment]
Yeah, but GitHub search isn't the best either. So no worries.
