### ISSUE TITLE
Couldn't load the Realm JNI library 'realm_jni32.dll or realm_jni64.dll'. Please include the directory to the library in java.library.path.

### ISSUE THREAD

**Issue by ivankarpey** [realm/realm-java#3419]
I want to try to implement some tests, which actaully use realm for real (not mocked), but when I trying to run those test it's crashes with exception

`java.lang.RuntimeException: Couldn't load the Realm JNI library 'realm_jni32.dll or realm_jni64.dll'. Please include the directory to the library in java.library.path.`

What should I do to fix this, where I could get those files?

**Comment by Zhuinden** [comment]
Unit test or instrumentation test?

It should work in instrumentation test.

**Comment by ivankarpey** [comment]
Unit one

**Comment by Zhuinden** [comment]
Yeah, that won't work. Realm-Java doesn't run outside Android.
