### ISSUE TITLE
Error:(2, 0) Plugin with id 'realm-android' not found.

### ISSUE THREAD

**Issue by luochune** [realm/realm-java#3420]
> We LOVE to help with any issues or bug you have!

> **Questions**: If you have questions about how to use Realm, please ask on [SO](http://stackoverflow.com/questions/ask?tags=realm) - we monitor the Realm tag.

> **Feature Request**: Just fill in the first two sections below.

> **Bugs**: To help you as fast as possible with an issue or bug please describe your issue and the steps you have taken to reproduce it in as many details as possible.
>
> Thanks for helping us help you :-)
>
> Remove this and above before submitting.

#### Goal

> What do you want to achieve?

#### Expected Results

> ?

#### Actual Results

>  E.g. full stack trace with exception

#### Steps & Code to Reproduce

> Describe your current debugging efforts.

#### Code Sample

```java

> Your code here. Bigger samples should ideally be as separate Android Studio project, 
> in gists/repositories or privately at help@realm.io)

```

#### Version of Realm and tooling
Realm version(s): ?

Android Studio version: ?

Which Android version and device: ?

**Comment by Zhuinden** [comment]
Make sure you add the plugin to the classpath in the project level build gradle

https://realm.io/docs/java/latest/#installation

**Comment by luochune** [comment]
Thanks for your tip,I have solved the problem successfully by writing two different definitions in project and application build.gradles
