### ISSUE TITLE
Unable to insert Values into tables after adding migration

### ISSUE THREAD

**Issue by Sutirth** [realm/realm-java#3421]
Bug: Unable to insert values into tables

Goal: values insertion

Expected Result: To get respective tables filled

Actual Result: tables are filled with 0s

Realm version(s): 1.2.0

Step 1 : Database table

```java
public class SweatPointFitnessDB extends RealmObject {

    private String distance;

    private int stepCount;

    @PrimaryKey
    @Required
    private String forday;

    private int userid;

    private int calories;

    private int sweatpoints;

    private String currentMonthNo;

    private String currentMonth;

    private int goalSweatPoints;

    private int BadgeSweatPoints;

    private int rewardSweatPoints;

    private int fordayDistance;

    private int bonusSweatPoints;

    private int dayTotalSweatPoints;
}
```

Step 2: migration

```java
//  ***********************************************************
//  **** This will migrate from version 22 to version 23 ****
//  **

if(oldVersion == 22){
    RealmObjectSchema sweatPointFitnessDBSchema=  schema.get("SweatPointFitnessDB")
            .addField("bonusSweatPoints", int.class);


    oldVersion++;
}

//  ***********************************************************
//  **** This will migrate from version 23 to version 24 ****
//  **

if(oldVersion == 23){
    RealmObjectSchema sweatPointFitnessDBSchema=  schema.get("SweatPointFitnessDB")
            .addField("dayTotalSweatPoints", int.class);



    oldVersion++;
}
```

Step 3: Async transaction

```java
cancelsyncSweatPointAsyncTransaction();
syncSweatPointAsyncTask = realm.executeTransactionAsync(new Realm.Transaction() {
    @Override
    public void execute(Realm realm) {
        for (i = 0; i < syncApiModel.getData().size(); i++) {
            final int entityNum = i;
            if (syncApiModel.getData().get(entityNum).getSweatPoints() != null){
            {

                if (syncApiModel.getData().get(entityNum).getSweatPoints().getUpdate() != null) {
                    for (int j = 0; j < syncApiModel.getData().get(entityNum).getSweatPoints().getUpdate().size(); j++) {
                        SweatPointFitnessDB sweatPointFitnessDB = realm.where(SweatPointFitnessDB.class)
                                .equalTo("forday", syncApiModel.getData().get(entityNum).getSweatPoints().getUpdate().get(j).getDate())
                                .findFirst();
                     
                        String dateSplit[] = syncApiModel.getData().get(entityNum).getSweatPoints().getUpdate().get(j).getDate().split("-");
                        currentMonthNo = dateSplit[1];
                        Calendar currentTime = Calendar.getInstance();
                        currentTime.set(Calendar.MONTH, Integer.valueOf(dateSplit[1]) - 1);
                        currentMonth = nameFormat.format(currentTime.getTime()).toString();


                        if (sweatPointFitnessDB == null) {

                            SweatPointFitnessDB sweatPointFitnessDBEnter = realm.createObject(SweatPointFitnessDB.class);
                            sweatPointFitnessDBEnter.setForday(syncApiModel.getData().get(entityNum).getSweatPoints().getUpdate().get(j).getDate());
                            sweatPointFitnessDBEnter.setGoalSweatPoints(syncApiModel.getData().get(entityNum).getSweatPoints().getUpdate().get(j).getGoalProgressSweatPoints());
                            sweatPointFitnessDBEnter.setBadgeSweatPoints(syncApiModel.getData().get(entityNum).getSweatPoints().getUpdate().get(j).getBadgeSweatPoints());
                            sweatPointFitnessDBEnter.setSweatpoints(syncApiModel.getData().get(entityNum).getSweatPoints().getUpdate().get(j).getFitnessSweatPoints());
                            sweatPointFitnessDBEnter.setRewardSweatPoints(syncApiModel.getData().get(entityNum).getSweatPoints().getUpdate().get(j).getRewardSweatPoints());
                            sweatPointFitnessDBEnter.setBonusSweatPoints(syncApiModel.getData().get(entityNum).getSweatPoints().getUpdate().get(j).getBonusSweatPoints());
                            sweatPointFitnessDBEnter.setDayTotalSweatPoints(syncApiModel.getData().get(entityNum).getSweatPoints().getUpdate().get(j).getDayTotalSweatPoints());
                            sweatPointFitnessDBEnter.setCurrentMonth(currentMonth);
                            sweatPointFitnessDBEnter.setCurrentMonthNo(currentMonthNo);
                        } else {
                       
                            sweatPointFitnessDB.setGoalSweatPoints(syncApiModel.getData().get(entityNum).getSweatPoints().getUpdate().get(j).getGoalProgressSweatPoints());
                            sweatPointFitnessDB.setBadgeSweatPoints(syncApiModel.getData().get(entityNum).getSweatPoints().getUpdate().get(j).getBadgeSweatPoints());
                            sweatPointFitnessDB.setSweatpoints(syncApiModel.getData().get(entityNum).getSweatPoints().getUpdate().get(j).getFitnessSweatPoints());
                            sweatPointFitnessDB.setRewardSweatPoints(syncApiModel.getData().get(entityNum).getSweatPoints().getUpdate().get(j).getRewardSweatPoints());
                            sweatPointFitnessDB.setBonusSweatPoints(syncApiModel.getData().get(entityNum).getSweatPoints().getUpdate().get(j).getBonusSweatPoints());
                            sweatPointFitnessDB.setDayTotalSweatPoints(syncApiModel.getData().get(entityNum).getSweatPoints().getUpdate().get(j).getDayTotalSweatPoints());
                           
                        }
                    }
                }
            }
            }
        }
    }
});
```

Sometimes values are inserted and sometimes they are not inserted. While debugging have observed the row which enters values is 0 though server is returning proper values. Unable to the issue

**Comment by Zhuinden** [comment]
You're using the accessors in debug to see the values in the managed realm object, right? 

https://realm.io/docs/java/latest/#android-studio-debugging

Otherwise, your transaction logic looks overcomplicated enough that it could have bugs in it, so try to debug using accessors instead of field values :smile:

**Comment by Sutirth** [comment]
@Zhuiden the thing is it works sometimes and fails sometimes so its really hard to debug why

**Comment by Zhuinden** [comment]
Well if I know one thing, you should reduce the length of your code by taking the `syncApiModel.getData().get(entityNum).getSweatPoints().getUpdate().get(j)` into a variable so you don't need to write it down again and again. 
Also you'll eventually have to use `realm.createObject(clazz, primaryKeyValue)` but otherwise I don't see what goes wrong

**Comment by stk1m1** [comment]
@Sutirth 

Few Suggestions,

1. Yes. You really need to setup a variable that calls `syncApiModel.getData().get(entityNum).getSweatPoints()` again and again. Plus, are you sure `syncApiModel` instance is handled only by the code above?

2. You can reduce following to one-liner and see if you have valid data. (You don't need double _if_ s)

  ```java
  if (syncApiModel.getData().get(entityNum).getSweatPoints() != null){
      if (syncApiModel.getData().get(entityNum).getSweatPoints().getUpdate() != null) {
      }
  }
  ```

3. So your double loop iterates 
`(not-null) syncApiModel.getData().get(entityNum).getSweatPoints()` x `syncApiModel.getData().get(entityNum).getSweatPoints().getUpdate().size()` times. 
Have you counted the number of `SweatPointFitnessDB` to see if the data from server is valid? If the received data is valid like you claimed, then at least you should have the valid number of `SweatPointFitnessDB` filled with `0`.

**Comment by Sutirth** [comment]
@stk1m1  

1) yes point taken would be reducing that 

2) Actually I have one more key in array "Delete" hence checking 2 conditions.

3)Data from the server is valid and yes SweatPointFitnessDB is filled with 0

**Comment by Zhuinden** [comment]
Make sure you look at the accessors (getter setter) values in debugger

**Comment by Sutirth** [comment]
@Zhuinden  Yeah thnx for the link up to docs tried the accessors way as well the output is same thing

**Comment by Sutirth** [comment]
SweatPointFitnessDB sweatPointFitnessDB = realm.where(SweatPointFitnessDB.class)
                                                                .equalTo("forday", syncApiModel.getData().get(entityNum).getSweatPoints().getUpdate().get(j).getDate())
                                                                .findFirst();
    
                                                        String dateSplit[] = syncApiModel.getData().get(entityNum).getSweatPoints().getUpdate().get(j).getDate().split("-");
                                                        currentMonthNo = dateSplit[1];
                                                        Calendar currentTime = Calendar.getInstance();
                                                        currentTime.set(Calendar.MONTH, Integer.valueOf(dateSplit[1]) - 1);
                                                        currentMonth = nameFormat.format(currentTime.getTime()).toString();
    
    
                                                        if (sweatPointFitnessDB == null) {
    
                                                            SweatPointFitnessDB sweatPointFitnessDBEnter = realm.createObject(SweatPointFitnessDB.class);
                                                            sweatPointFitnessDBEnter.setForday(syncApiModel.getData().get(entityNum).getSweatPoints().getUpdate().get(j).getDate());
                                                            sweatPointFitnessDBEnter.setGoalSweatPoints(syncApiModel.getData().get(entityNum).getSweatPoints().getUpdate().get(j).getGoalProgressSweatPoints());
                                                            sweatPointFitnessDBEnter.setBadgeSweatPoints(syncApiModel.getData().get(entityNum).getSweatPoints().getUpdate().get(j).getBadgeSweatPoints());
                                                            sweatPointFitnessDBEnter.setSweatpoints(syncApiModel.getData().get(entityNum).getSweatPoints().getUpdate().get(j).getFitnessSweatPoints());
                                                            sweatPointFitnessDBEnter.setRewardSweatPoints(syncApiModel.getData().get(entityNum).getSweatPoints().getUpdate().get(j).getRewardSweatPoints());
                                                            sweatPointFitnessDBEnter.setBonusSweatPoints(syncApiModel.getData().get(entityNum).getSweatPoints().getUpdate().get(j).getBonusSweatPoints());
                                                            sweatPointFitnessDBEnter.setDayTotalSweatPoints(syncApiModel.getData().get(entityNum).getSweatPoints().getUpdate().get(j).getDayTotalSweatPoints());
                                                            sweatPointFitnessDBEnter.setCurrentMonth(currentMonth);
                                                            sweatPointFitnessDBEnter.setCurrentMonthNo(currentMonthNo);
    
    
                                                            String date = sweatPointFitnessDBEnter.getForday();
                                                            int dayTotalSweatPoint = sweatPointFitnessDBEnter.getDayTotalSweatPoints();
                                                            Log.i(TAG, "Fresh Entry Date: " + date);
                                                            Log.i(TAG, "Fresh Entry dayTotal: " + dayTotalSweatPoint);
    
    
                                                        } else {
                                                            sweatPointFitnessDB.setGoalSweatPoints(syncApiModel.getData().get(entityNum).getSweatPoints().getUpdate().get(j).getGoalProgressSweatPoints());
                                                            sweatPointFitnessDB.setBadgeSweatPoints(syncApiModel.getData().get(entityNum).getSweatPoints().getUpdate().get(j).getBadgeSweatPoints());
                                                            sweatPointFitnessDB.setSweatpoints(syncApiModel.getData().get(entityNum).getSweatPoints().getUpdate().get(j).getFitnessSweatPoints());
                                                            sweatPointFitnessDB.setRewardSweatPoints(syncApiModel.getData().get(entityNum).getSweatPoints().getUpdate().get(j).getRewardSweatPoints());
                                                            sweatPointFitnessDB.setBonusSweatPoints(syncApiModel.getData().get(entityNum).getSweatPoints().getUpdate().get(j).getBonusSweatPoints());
                                                            sweatPointFitnessDB.setDayTotalSweatPoints(syncApiModel.getData().get(entityNum).getSweatPoints().getUpdate().get(j).getDayTotalSweatPoints());
    
                                                            String date = sweatPointFitnessDB.getForday();
                                                            int dayTotalSweatPoint = sweatPointFitnessDB.getDayTotalSweatPoints();
                                                            Log.i(TAG, "Update Entry Date: " + date);
                                                            Log.i(TAG, "update Entry dayTotal: " + dayTotalSweatPoint);
                                                        }


I tried via using accessors method as well I do the values printed in log but database shows 0 as their value. cc @Zhuinden

**Comment by Sutirth** [comment]
any help on this @beeender

**Comment by Zhuinden** [comment]
....you should really consider looking through your code step by step and see where it goes wrong

I mean really, your code should be just this

``` java
if (sweatPointFitnessDB == null) {
    sweatPointFitnessDB = realm.createObject(SweatPointFitnessDB.class, primaryKeyValue);
}
    sweatPointFitnessDB.setForday(syncApiModel.getData().get(entityNum).getSweatPoints().getUpdate().get(j).getDate());
    sweatPointFitnessDB.setGoalSweatPoints(syncApiModel.getData().get(entityNum).getSweatPoints().getUpdate().get(j).getGoalProgressSweatPoints());
    sweatPointFitnessDB.setBadgeSweatPoints(syncApiModel.getData().get(entityNum).getSweatPoints().getUpdate().get(j).getBadgeSweatPoints());
    sweatPointFitnessDB.setSweatpoints(syncApiModel.getData().get(entityNum).getSweatPoints().getUpdate().get(j).getFitnessSweatPoints());
    sweatPointFitnessDB.setRewardSweatPoints(syncApiModel.getData().get(entityNum).getSweatPoints().getUpdate().get(j).getRewardSweatPoints());
    sweatPointFitnessDBEnter.setBonusSweatPoints(syncApiModel.getData().get(entityNum).getSweatPoints().getUpdate().get(j).getBonusSweatPoints());
    sweatPointFitnessDB.setDayTotalSweatPoints(syncApiModel.getData().get(entityNum).getSweatPoints().getUpdate().get(j).getDayTotalSweatPoints());
    sweatPointFitnessDB.setCurrentMonth(currentMonth);
    sweatPointFitnessDB.setCurrentMonthNo(currentMonthNo);


    String date = sweatPointFitnessDB.getForday();
    int dayTotalSweatPoint = sweatPointFitnessDB.getDayTotalSweatPoints();
    Log.i(TAG, "Entry Date: " + date);
    Log.i(TAG, "Entry dayTotal: " + dayTotalSweatPoint);
}
```

**Comment by Sutirth** [comment]
@Zhuinden Could you explain me this 

if (sweatPointFitnessDB == null) {
    sweatPointFitnessDB = realm.createObject(SweatPointFitnessDB.class, primaryKeyValue);
}

where primarykeyvalue is what?? I mean any docs related to what you have wrote or an example. 

Rest I have gone through step by step I found nothing wrong.

**Comment by Zhuinden** [comment]
I'd say `primaryKeyValue` is most definitely `forday` but you're the one who sees which field is annotated with `@PrimaryKey`.  That should be the value of that field.

**Comment by Sutirth** [comment]
@Zhuinden  yes you are right forday is my primaryKeyValue . I would make the changes and will give an update here.

**Comment by kneth** [comment]
@Sutirth Did you have a chance to make the changes?

**Comment by Sutirth** [comment]
@kneth  Yep I did those. Working atm. Closing the thread
