### ISSUE TITLE
Different results on different threads?

### ISSUE THREAD

**Issue by nicolausYes** [realm/realm-java#3422]
Realm version(s): 1.2 (1.1)
Android Studio version: 2.2 Beta
Which Android version and device: Nexus 5, 4.4.4.

I'm interacting with Realm database on non-UI threads, using Java's ThreadPoolExecutor with a couple of threads to handle background tasks.

The Realm is initializing on UI thread like this.

`RealmConfiguration realmConfig = new RealmConfiguration.Builder(context).build();        Realm.setDefaultConfiguration(realmConfig);`

For example, I'm trying to change one of the fields of the realm object and get results base on this field value (add/remove story to Favorites, get a list of Favorites).

These two operations are happening on a background thread.
Add/remove from favorites.
```
Realm realm = Realm.getDefaultInstance();
StoryRealm storyRealm = realm.where(StoryRealm.class).equalTo("id", story.getId()).findFirst();
realm.beginTransaction();
if (storyRealm == null) {
    storyRealm = realm.createObject(StoryRealm.class);
    // many other stuff
} 
storyRealm.setFavorite(favorite);
realm.commitTransaction();
realm.close();
```

Getting list of favorites:

```
Realm realm = Realm.getDefaultInstance();
RealmResults<StoryRealm> results = realm.where(StoryRealm.class).equalTo("isFavorite", true).findAll();
// processing results
realm.close();
```

Everything is ok when nothing changes. When I change something (some adds, some deletes), then I'm starting to get different results using the code above. 
For example, I have 2 favorites, then I add 1 more favorite. Then the code above will return different results (almost for every request). Sometimes it can be 2 objects, sometimes 3. 
I've noticed, the results are bound to the realm object (for example, object with address `io.realm.Realm@65cc5e50 `always return 3 objects and `object io.realm.Realm@65c35130` returns 2). As far as I understood, Realm caches realm instances for different threads.

I was trying not to close realm object on the thread, but getting the same results.

Is it the correct way to deal with realm on different threads? Why I'm getting different results?

**Comment by stk1m1** [comment]
If you're to have a Realm object within a Looper thread such as UI thread (or Main thread), Realm automatically updates itself to the latest change such as new addition, or removal. 

On contrary, if you're to setup a Realm object in a non-Looper thread such as vanilla `Thread` or `ThreadPoolExecutor` in your case, it's up to you to use [`waitForChange()`](https://realm.io/docs/java/1.2.0/api/io/realm/Realm.html#waitForChange--) to update the Realm to the latest change.

You can read more about automatic refresh [here](https://realm.io/docs/java/latest/#auto-refresh).

**Comment by Zhuinden** [comment]
The Realm instances on non-looper background threads don't autoupdate. Also, Realm instances on non-looper background threads *must* be closed. 

If you want to ensure that you see the latest version of the Realm at all times on your non-looper background thread, consider executing your logic in a transaction.

**Comment by nicolausYes** [comment]
@stk1m1 the goal is to get the last version of data in a thread. At any moment. 
The use case is that user, for example, clicks Favorites and I'm adding a new task to ThreadExecutor to get a list (executing in a non-UI thread).
`waitForChange()` doesn't seem to help a lot, because it blocks current thread to wait for a data change. The problem is that I don't know is there any data changing at the moment. If nothing is happening (no write operations), it'll block current thread forever (till someone call `stopWaitForChange()`).
Are there any methods from what I can know if something happening in the database to decide to call `waitForChange()` or no?

**Comment by nicolausYes** [comment]
@Zhuinden 
> consider executing your logic in a (single) transaction on the thread. During transaction, you see the latest version of the Realm at all times.

I wish I can, but it depends on the user behaviour. I need to execute transaction after user commits some action (add to favorite, for example), he can do it a lot of times and quite often. I don't want to execute this on UI thread because some actions deal with a quite large amount of data (for example if a user clicks save all list of articles to offline. It can be 3-10 Mb of data. The same if I need to initialize 50-100 objects based on a data saved to database).

**Comment by Zhuinden** [comment]
>  the goal is to get the last version of data in a thread. At any moment. 

You'd need to execute the logic in a transaction then. A transaction always sees the latest version of data.

**Comment by kneth** [comment]
@nicolausYes Would you benefit from #3476?

**Comment by nicolausYes** [comment]
Yes.

**Comment by kneth** [comment]
@nicolausYes I close the issue, and ask you to follow #3476 as it will provide the solution, you need.
