### ISSUE TITLE
What is used in Realm instead of the Object field in Java

### ISSUE THREAD

**Issue by wushge11** [realm/realm-java#3423]
What is used in Realm instead of the Object field in Java

old ：
 private Object geo;
 private List<Object> darwin_tags;
now:
????

**Comment by Zhuinden** [comment]
You need specific RealmObject classes in your schema for it to work. 

Also List is `RealmList<T>`

**Comment by cmelchior** [comment]
Realm doesn't support standard `Object`... All references needs to be to `RealmObject` sub-classes and lists have to be `RealmList<? extends RealmObject>`. You can read more here: https://realm.io/docs/java/latest/#models

**Comment by wushge11** [comment]
Thanks
