### ISSUE TITLE
Jar realm where to download

### ISSUE THREAD

**Issue by yuwu** [realm/realm-java#3425]
Jar realm where to download？

**Comment by Zhuinden** [comment]
Realm is distributed as an AAR, through a Gradle plugin.

The last JAR version was 0.87.5 which is obsolete because current version is 1.2.0

**Comment by cmelchior** [comment]
@yuwu You can download all the artifacts manually from bintray here: https://bintray.com/realm/maven

but as @Zhuinden said, you should really just let the Gradle plugin handle it for you.

**Comment by kneth** [comment]
@yuwu I hope you have figured out how to download Realm.
