### ISSUE TITLE
Update schema version cache in SharedRealm in ObjectStore

### ISSUE THREAD

**Issue by zaki50** [realm/realm-java#3426]
`SharedRealm` in ObjectStore has a cache of schema version in it and we don’t seem to update it when we change the schema version in the Realm file.

It’s OK for now since current Java binding does not use any methods that use the schema version cache, but we will need to fix that when we move migration logic to ObjectStore.

**Comment by cmelchior** [comment]
Connected to #3800

**Comment by beeender** [comment]
#4887 fixed this.
