### ISSUE TITLE
RealmObject-->Object

### ISSUE THREAD

**Issue by JustinChiang123** [realm/realm-java#3428]
#### Goal

RealmObject-->Object(can);
Josn-->RealmObject (can);
RealmObject-->Json(can);
RealmList-->Json(can);
Json-->Object(can);
Object-->RealmObject(not);
Object-->Json-->RealmObject(can);

#### Expected Results

RealmObject-->Object(can);
Josn-->RealmObject (can);
RealmObject-->Json(can);
RealmList-->Json(can);
Json-->Object(can);
Object-->Json-->RealmObject(can);

#### Actual Results
RealmObject-->Object(not);
Josn-->RealmObject (can);
RealmObject-->Json(not);
RealmList-->Json(not);
Json-->Object(can);
Object-->Json-->RealmObject(can);

**Comment by Zhuinden** [comment]
Well to serialize fields with GSON,  you need to use `realm.copyFromRealm` first, because GSON always uses fields for serialization instead of accessors. 

Otherwise, it's unclear to me what you're trying to achieve exactly in `RealmObject -> Object`

**Comment by kneth** [comment]
@JustinChiang123 I'm closing the issue due to no updates. Please post a more specific question - including a code snippet.
