### ISSUE TITLE
Add Android "Instant Run" warning and help to documentation

### ISSUE THREAD

**Issue by apatrida** [realm/realm-java#3438]
There appear to be a lot of issues (28+ in this issue tracker) around Instant Run and using Realm.  Yet the documentation on realm.io doesn't mention it even once to warn people about this or give pro-active guidance about disabling this feaure or working around problems.

This should be added in some obvious place in the documentation to avoid the mystery errors produced by this problem.  They are non-obvious.

**Comment by Zhuinden** [comment]
You're right it should be in the [FAQ](https://realm.io/docs/java/latest/#faq)

**Comment by kneth** [comment]
Every time there is a release of Android Studio we hope the issue is fixed. But until that happens, we should mention potential problems with Instant Run in the documentation.

**Comment by cmelchior** [comment]
Outdated since Instant Run is no longer a thing. It is now called Apply Changes and should work much better.
