### ISSUE TITLE
How to set the executor for Realm

### ISSUE THREAD

**Issue by poldz123** [realm/realm-java#3442]
I wanna test Realm but I want it to be synchronous. How do I set the executor for Realm?

**Comment by Zhuinden** [comment]
I'm not sure if you can just change that on a whim.

https://github.com/realm/realm-java/blob/master/realm/realm-library/src/main/java/io/realm/BaseRealm.java#L61

**Comment by poldz123** [comment]
Yea I tried doing it with PowerMock but `RealmThreadPoolExecutor` contructor is private. :<

**Comment by cmelchior** [comment]
Hi @poldz123 
When you say you want to test Realm synchronous, what does this exactly mean? If you are using our async API's we depend on the Looper, so you cannot really turn that into an synchronous test.

What we perhaps could do was to make the Executor public so it would be easier to use something like Espresso idling resources? Would that solve your problem?

Also, internally we use a special test rule that allows testing as well `@RunTestInLooperThread`. Perhaps that could be useful for you as well? https://github.com/realm/realm-java/tree/master/realm/realm-library/src/androidTest/java/io/realm/rule

**Comment by poldz123** [comment]
Hi @cmelchior 
I am using Robolectric within the JUnit test and want all of the asynchronous read and write to realm to be to be synchronous.

I do not know if it will work to have a customize executor that  will just execute all the task right away making it synchronous. 

It would if you guys is exposing the executor itself I guess, but first I just wanna confirm having a customize executor will work.

**Comment by cmelchior** [comment]
Hi @poldz123 In that case, getting access to the Executor will not do you any good. Our Async queries uses the Looper ticks to communicate with the thread triggering them. You should either look into a test that can work with the Looper our find a way to hide the query results behind an interface.

**Comment by poldz123** [comment]
Thanks for all the info. Closing this.
