### ISSUE TITLE
Failed to access: /storage/emulated/0/Notah/Backup

### ISSUE THREAD

**Issue by iAbdulaziz** [realm/realm-java#3446]
#### Goal

> What do you want to achieve?

I am trying to copy the realm file to a folder that I created, so I can backup that file with Google Backup Agent service, so the user can see his contents when he just reinstall the app later.

#### Expected Results

Backup the file after after every time the app launching, means my code is in the MainActivity.java - onCreate(); method.

#### Actual Results

>  09-17 14:06:25.902 3302-3302/com.twitter.i_droidi.notah D/REALM: jni: ThrowingException 6, /storage/emulated/0/Notah/Backup, open("/storage/emulated/0/Notah/Backup") failed: File exists path: /storage/emulated/0/Notah/Backup.
09-17 14:06:25.902 3302-3302/com.twitter.i_droidi.notah D/REALM: Exception has been throw: Failed to access: /storage/emulated/0/Notah/Backup. open("/storage/emulated/0/Notah/Backup") failed: File exists path: /storage/emulated/0/Notah/Backup
09-17 14:06:25.902 3302-3302/com.twitter.i_droidi.notah W/System.err: io.realm.exceptions.RealmIOException: Failed to access: /storage/emulated/0/Notah/Backup. open("/storage/emulated/0/Notah/Backup") failed: File exists path: /storage/emulated/0/Notah/Backup
09-17 14:06:25.902 3302-3302/com.twitter.i_droidi.notah W/System.err:     at io.realm.internal.Group.nativeWriteToFile(Native Method)
09-17 14:06:25.903 3302-3302/com.twitter.i_droidi.notah W/System.err:     at io.realm.internal.Group.writeToFile(Group.java:226)
09-17 14:06:25.903 3302-3302/com.twitter.i_droidi.notah W/System.err:     at io.realm.internal.SharedGroupManager.copyToFile(SharedGroupManager.java:141)
09-17 14:06:25.903 3302-3302/com.twitter.i_droidi.notah W/System.err:     at io.realm.BaseRealm.writeEncryptedCopyTo(BaseRealm.java:254)
09-17 14:06:25.903 3302-3302/com.twitter.i_droidi.notah W/System.err:     at io.realm.Realm.writeEncryptedCopyTo(Realm.java:122)
09-17 14:06:25.903 3302-3302/com.twitter.i_droidi.notah W/System.err:     at io.realm.BaseRealm.writeCopyTo(BaseRealm.java:232)
09-17 14:06:25.903 3302-3302/com.twitter.i_droidi.notah W/System.err:     at io.realm.Realm.writeCopyTo(Realm.java:122)
09-17 14:06:25.903 3302-3302/com.twitter.i_droidi.notah W/System.err:     at com.twitter.i_droidi.notah.MainActivity.onCreate(MainActivity.java:82)
09-17 14:06:25.903 3302-3302/com.twitter.i_droidi.notah W/System.err:     at android.app.Activity.performCreate(Activity.java:6237)
09-17 14:06:25.903 3302-3302/com.twitter.i_droidi.notah W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
09-17 14:06:25.903 3302-3302/com.twitter.i_droidi.notah W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
09-17 14:06:25.903 3302-3302/com.twitter.i_droidi.notah W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
09-17 14:06:25.903 3302-3302/com.twitter.i_droidi.notah W/System.err:     at android.app.ActivityThread.-wrap11(ActivityThread.java)
09-17 14:06:25.903 3302-3302/com.twitter.i_droidi.notah W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
09-17 14:06:25.903 3302-3302/com.twitter.i_droidi.notah W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
09-17 14:06:25.903 3302-3302/com.twitter.i_droidi.notah W/System.err:     at android.os.Looper.loop(Looper.java:148)
09-17 14:06:25.903 3302-3302/com.twitter.i_droidi.notah W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5417)
09-17 14:06:25.903 3302-3302/com.twitter.i_droidi.notah W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
09-17 14:06:25.903 3302-3302/com.twitter.i_droidi.notah W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
09-17 14:06:25.903 3302-3302/com.twitter.i_droidi.notah W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

#### Code Sample

```
try
        {
            folder = new File(Environment.getExternalStorageDirectory() + File.separator
                    + "Notah" + File.separator + "Backup");
            boolean success = true;

            if(!folder.exists())
            {
                success = folder.mkdirs();
            }
            if(success)
            {
                if(folder.canWrite())
                {
                    this.realm.writeCopyTo(folder);
                    Log.i("MainActivity.java", "Copied");
                }
            }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
```

#### Version of Realm and tooling
Realm version(s): 1.2.0

Android Studio version: 2.1.3

Which Android version and device: Official emulator - Nexus 6P - 6.0

**Comment by Zhuinden** [comment]
Provide the path to the File you want to create, not the Folder that contains the file

    File file = new File(Environment.getExternalStorageDirectory() + File.separator
                    + "Notah" + File.separator + "Backup" + File.separator + "default.realm");
    this.realm.writeCopyTo(file);

**Comment by iAbdulaziz** [comment]
I tried it, but it shows the same problem.

> 09-17 14:50:52.135 8313-8313/com.twitter.i_droidi.notah D/REALM: jni: ThrowingException 6, , open("/storage/emulated/0/Notah/Backup/default.realm") failed: File exists path: /storage/emulated/0/Notah/Backup/default.realm.
09-17 14:50:52.135 8313-8313/com.twitter.i_droidi.notah D/REALM: Exception has been throw: Failed to access: 
09-17 14:50:52.135 8313-8313/com.twitter.i_droidi.notah W/System.err: io.realm.exceptions.RealmIOException: Failed to access: 
09-17 14:50:52.135 8313-8313/com.twitter.i_droidi.notah W/System.err:     at io.realm.internal.Group.nativeWriteToFile(Native Method)
09-17 14:50:52.135 8313-8313/com.twitter.i_droidi.notah W/System.err:     at io.realm.internal.Group.writeToFile(Group.java:226)
09-17 14:50:52.135 8313-8313/com.twitter.i_droidi.notah W/System.err:     at io.realm.internal.SharedGroupManager.copyToFile(SharedGroupManager.java:141)
09-17 14:50:52.135 8313-8313/com.twitter.i_droidi.notah W/System.err:     at io.realm.BaseRealm.writeEncryptedCopyTo(BaseRealm.java:254)
09-17 14:50:52.135 8313-8313/com.twitter.i_droidi.notah W/System.err:     at io.realm.Realm.writeEncryptedCopyTo(Realm.java:122)
09-17 14:50:52.135 8313-8313/com.twitter.i_droidi.notah W/System.err:     at io.realm.BaseRealm.writeCopyTo(BaseRealm.java:232)
09-17 14:50:52.135 8313-8313/com.twitter.i_droidi.notah W/System.err:     at io.realm.Realm.writeCopyTo(Realm.java:122)
09-17 14:50:52.135 8313-8313/com.twitter.i_droidi.notah W/System.err:     at com.twitter.i_droidi.notah.MainActivity.onCreate(MainActivity.java:82)
09-17 14:50:52.135 8313-8313/com.twitter.i_droidi.notah W/System.err:     at android.app.Activity.performCreate(Activity.java:6237)
09-17 14:50:52.135 8313-8313/com.twitter.i_droidi.notah W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
09-17 14:50:52.135 8313-8313/com.twitter.i_droidi.notah W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
09-17 14:50:52.135 8313-8313/com.twitter.i_droidi.notah W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
09-17 14:50:52.135 8313-8313/com.twitter.i_droidi.notah W/System.err:     at android.app.ActivityThread.-wrap11(ActivityThread.java)
09-17 14:50:52.135 8313-8313/com.twitter.i_droidi.notah W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
09-17 14:50:52.135 8313-8313/com.twitter.i_droidi.notah W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
09-17 14:50:52.136 8313-8313/com.twitter.i_droidi.notah W/System.err:     at android.os.Looper.loop(Looper.java:148)
09-17 14:50:52.136 8313-8313/com.twitter.i_droidi.notah W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5417)
09-17 14:50:52.136 8313-8313/com.twitter.i_droidi.notah W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
09-17 14:50:52.136 8313-8313/com.twitter.i_droidi.notah W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
09-17 14:50:52.136 8313-8313/com.twitter.i_droidi.notah W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

#### Code

```
try
        {
            file = new File(Environment.getExternalStorageDirectory() + File.separator
                    + "Notah" + File.separator + "Backup" + File.separator + "default.realm");
            boolean success = true;

            if(!file.exists())
            {
                success = file.mkdirs();
            }
            if(success)
            {
                if(file.canWrite())
                {
                    this.realm.writeCopyTo(file);
                    Log.i("MainActivity.java", "Copied");
                }
            }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
```

**Comment by Zhuinden** [comment]
I think you created a folder called `default.realm` with that.

try
        {
            folder = new File(Environment.getExternalStorageDirectory() + File.separator
                    + "Notah" + File.separator + "Backup");
            boolean success = true;

            if(!folder.exists())
            {
                success = folder.mkdirs();
            }
            if(success)
            {
                if(folder.canWrite())
                {
                    File file = new File(Environment.getExternalStorageDirectory() + File.separator
                    + "Notah" + File.separator + "Backup" + File.separator + "default.realm");
                    this.realm.writeCopyTo(file);
                    Log.i("MainActivity.java", "Copied");
                }
            }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }

**Comment by iAbdulaziz** [comment]
I created the file, but the log shows another exception.

> 09-17 15:09:52.600 19531-19531/com.twitter.i_droidi.notah D/REALM: jni: ThrowingException 4, /Notes.r, open("/Notes.realm") failed: Read-only file system path: /Notes.realm.
09-17 15:09:52.600 19531-19531/com.twitter.i_droidi.notah D/REALM: Exception has been throw: Failed to open /Notes.r
09-17 15:09:52.600 19531-19531/com.twitter.i_droidi.notah W/System.err: io.realm.exceptions.RealmIOException: Failed to open /Notes.r
09-17 15:09:52.600 19531-19531/com.twitter.i_droidi.notah W/System.err:     at io.realm.internal.Group.nativeWriteToFile(Native Method)
09-17 15:09:52.600 19531-19531/com.twitter.i_droidi.notah W/System.err:     at io.realm.internal.Group.writeToFile(Group.java:226)
09-17 15:09:52.600 19531-19531/com.twitter.i_droidi.notah W/System.err:     at io.realm.internal.SharedGroupManager.copyToFile(SharedGroupManager.java:141)
09-17 15:09:52.601 19531-19531/com.twitter.i_droidi.notah W/System.err:     at io.realm.BaseRealm.writeEncryptedCopyTo(BaseRealm.java:254)
09-17 15:09:52.601 19531-19531/com.twitter.i_droidi.notah W/System.err:     at io.realm.Realm.writeEncryptedCopyTo(Realm.java:122)
09-17 15:09:52.601 19531-19531/com.twitter.i_droidi.notah W/System.err:     at io.realm.BaseRealm.writeCopyTo(BaseRealm.java:232)
09-17 15:09:52.601 19531-19531/com.twitter.i_droidi.notah W/System.err:     at io.realm.Realm.writeCopyTo(Realm.java:122)
09-17 15:09:52.601 19531-19531/com.twitter.i_droidi.notah W/System.err:     at com.twitter.i_droidi.notah.MainActivity.onCreate(MainActivity.java:84)
09-17 15:09:52.601 19531-19531/com.twitter.i_droidi.notah W/System.err:     at android.app.Activity.performCreate(Activity.java:6237)
09-17 15:09:52.601 19531-19531/com.twitter.i_droidi.notah W/System.err:     at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1107)
09-17 15:09:52.601 19531-19531/com.twitter.i_droidi.notah W/System.err:     at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2369)
09-17 15:09:52.601 19531-19531/com.twitter.i_droidi.notah W/System.err:     at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2476)
09-17 15:09:52.601 19531-19531/com.twitter.i_droidi.notah W/System.err:     at android.app.ActivityThread.-wrap11(ActivityThread.java)
09-17 15:09:52.601 19531-19531/com.twitter.i_droidi.notah W/System.err:     at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1344)
09-17 15:09:52.601 19531-19531/com.twitter.i_droidi.notah W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:102)
09-17 15:09:52.601 19531-19531/com.twitter.i_droidi.notah W/System.err:     at android.os.Looper.loop(Looper.java:148)
09-17 15:09:52.601 19531-19531/com.twitter.i_droidi.notah W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:5417)
09-17 15:09:52.601 19531-19531/com.twitter.i_droidi.notah W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
09-17 15:09:52.601 19531-19531/com.twitter.i_droidi.notah W/System.err:     at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
09-17 15:09:52.601 19531-19531/com.twitter.i_droidi.notah W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)

#### Code

```
try
        {
            folder = new File(Environment.getExternalStorageDirectory() + File.separator
                    + "Notah" + File.separator + "Backup");
            boolean success = true;

            if(!folder.exists())
            {
                success = folder.mkdirs();
                realmFile = new File("Notes.realm");
            }
            if(success)
            {
                if(folder.canWrite())
                {
                    this.realm.writeCopyTo(realmFile);
                    Log.i("MainActivity.java", "Copied");
                }
            }
        }
        catch(Exception e)
        {
            e.printStackTrace();
        }
```

**Comment by Zhuinden** [comment]
You should seriously just take the code I gave you and see how that one works.

**Comment by iAbdulaziz** [comment]
Ah, you edited your comment, and I didn't noticed that. Sorry.

**Comment by iAbdulaziz** [comment]
Thanks, your code

**Comment by Zhuinden** [comment]
Glad to hear :smile:
