### ISSUE TITLE
Kotlin Companion Objects Confuse Realm's Column Name Generator

### ISSUE THREAD

**Issue by mikeholler** [realm/realm-java#3448]
I use Kotlin with Realm, and I like to keep my column name constants inside an object inside my `RealmObject` like so:

```kotlin
open class RealmExample(
        var fieldA: String = "defaultValue",
        var fieldB: Sting = "defaultValue"
): RealmObject() {
    object Columns {
        val fieldA = "fieldA"
        val fieldB = "fieldB"
    }
}
```

This generates the following `RealmExampleRealmProxy.RealmExampleColumnInfo` (**EXPECTED**):

```java
static final class RealmExampleColumnInfo extends ColumnInfo {

    public final long fieldAIndex;
    public final long fieldBIndex;

    RealmExampleColumnInfo(String path, Table table) {
        final Map<String, Long> indicesMap = new HashMap<String, Long>(2);
        this.fieldAIndex = getValidColumnIndex(path, table, "RealmExample", "fieldA");
        indicesMap.put("fieldA", this.fieldAIndex);

        this.fieldBIndex = getValidColumnIndex(path, table, "RealmExample", "fieldB");
        indicesMap.put("fieldB", this.fieldBIndex);

        setIndicesMap(indicesMap);
    }
}
```

However, today I tried making `Columns` a companion object instead:

```kotlin
open class RealmExample(
        var fieldA: String = "defaultValue",
        var fieldB: Sting = "defaultValue"
): RealmObject() {
    companion object Columns {
        val fieldA = "fieldA"
        val fieldB = "fieldB"
    }
}
```

And Realm generated the following `RealmExampleRealmProxy.RealmExampleColumnInfo` (**ACTUAL**):

```java
static final class RealmExampleColumnInfo extends ColumnInfo {

    public final long fieldA$1Index;
    public final long fieldB$1Index;

    RealmExampleColumnInfo(String path, Table table) {
        final Map<String, Long> indicesMap = new HashMap<String, Long>(2);
        this.fieldA$1Index = getValidColumnIndex(path, table, "RealmExample", "fieldA$1");
        indicesMap.put("fieldA$1", this.fieldA$1Index);

        this.fieldB$1Index = getValidColumnIndex(path, table, "RealmExample", "fieldB$1");
        indicesMap.put("fieldB$1", this.fieldB$1Index);

        setIndicesMap(indicesMap);
    }
}
```

I am using Realm v1.2.0.

I would not expect a companion object with constants to affect the Realm column naming schema, since companion objects themselves do not have meaning per-instance but in a sense similar to Java static members. I *do* expect Realm to generate the exact same code for both of my Kotlin snippets, but that does not seem to be happening.

**Comment by zaki50** [comment]
Hi @mikeholler

Thank you for reporting.
I'll take a look.

**Comment by zaki50** [comment]
I reproduced this.

I don't think we can declare *static* and *non-static* members those have the same name in one class.
For that reason, I guess kotlin compiler changes the field name automatically.

My recommendation is:

1) use different name for the constants
2) use `KProperty` provided by Kotlin. e.g. `RealmExample::fieldA.name` for `fieldA`. In this way, you don't need to add companion object anymore.

**Comment by zaki50** [comment]
I'll close this issue.
If you have further questions, feel free to reopen this.

**Comment by Zhuinden** [comment]
Shouldn't this be documented somewhere?

**Comment by lemberh** [comment]
>2 use KProperty provided by Kotlin. e.g. RealmExample::fieldA.name for fieldA. In this way, you don't need to add companion object anymore.
Works great for me

**Comment by Zhuinden** [comment]
Personally I just use https://github.com/cmelchior/realmfieldnameshelper which generates `___Fields` with the required constants.
