### ISSUE TITLE
Compile realm-java failed

### ISSUE THREAD

**Issue by yuwu** [realm/realm-java#3451]
realm v1.2.0 
jdk 7
mac
ndk10e

FAILURE: Build failed with an exception.

* Where:
Build file '/Users/applekf/git/realm-java/v1.2.0/realm/realm-jni/build.gradle' line: 219

* What went wrong:
Execution failed for task ':realm-jni:downloadCore'.
> Invalid checksum for file 'core-android-1.5.1.tar.gz'. Expected a034d3250c820a15126721142d168a2ac4a12223b75bb324958ca2a70442720d but got f9e818acbd8a6d274859fabf7837eaf531d0a7144b7e5cee570c10b9a779e8f0.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by cmelchior** [comment]
We have a checksum check when downloading our compiled core to make sure you get the correct one. Most likely your file got corrupted when being downloaded (spotty network perhaps?)

If you believe you got the right one, you can disable the check by commenting out this line: https://github.com/realm/realm-java/blob/master/realm/realm-library/build.gradle#L17

**Comment by kneth** [comment]
@yuwu If you haven't been able to build Realm Java, please either reopen or create new issue.

**Comment by lhb2435TW** [comment]
![image](https://user-images.githubusercontent.com/28702979/37968952-8838a29e-320a-11e8-8d1e-cf83a4463b33.png)

I have annotated the 17th line, and it says " Could not downloads file. "

**Comment by Zhuinden** [comment]
You need Linux or MacOS to build Realm.
