### ISSUE TITLE
When the data is in bulk and sync running in background in rx subscriber then before completing insertion in to realm tables it bye pass the data;Means complete data is not filled

### ISSUE THREAD

**Issue by devvishal06** [realm/realm-java#3463]
> We LOVE to help with any issues or bug you have!

> **Questions**: If you have questions about how to use Realm, please ask on [SO](http://stackoverflow.com/questions/ask?tags=realm) - we monitor the Realm tag.

> **Feature Request**: Just fill in the first two sections below.

> **Bugs**: To help you as fast as possible with an issue or bug please describe your issue and the steps you have taken to reproduce it in as many details as possible.
>
> Thanks for helping us help you :-)
>
> Remove this and above before submitting.

#### Goal

> What do you want to achieve?

#### Expected Results

> ?

#### Actual Results

>  E.g. full stack trace with exception

#### Steps & Code to Reproduce

> Describe your current debugging efforts.

#### Code Sample

```java

> Your code here. Bigger samples should ideally be as separate Android Studio project, 
> in gists/repositories or privately at help@realm.io)

```

#### Version of Realm and tooling
Realm version(s): ?

Android Studio version: ?

Which Android version and device: ?

**Comment by Zhuinden** [comment]
It *should* work if you follow the instructions on [stetho-realm](https://github.com/uPhyca/stetho-realm)

**Comment by Zhuinden** [comment]
You should use a single transaction on your background thread for saving the data.

**Comment by kneth** [comment]
@devvishal06 Did the suggestion above help you?

**Comment by kneth** [comment]
I am closing the issue. If the suggestion above didn't help you, please reopen or create new issue.
