### ISSUE TITLE
Verify that Object Store checks length of class name

### ISSUE THREAD

**Issue by kneth** [realm/realm-java#3470]
`RealmObjectSchema.setClassName()` (and possibly others) checks the length of class names since core has a limitation. Either core or object store should check it. And when one of them do, remove all checks.

**Comment by cmelchior** [comment]
Connected to https://github.com/realm/realm-java/pull/3800

**Comment by cmelchior** [comment]
This has been fixed with the with the move of all schema logic to Object Store. Closing.
