### ISSUE TITLE
Problem with 2.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by bryanspano** [realm/realm-java#3472]
2.0.0-SNAPSHOT 
Entering RealmConfiguration.java Android Studio says Library Source Code does not match the bytecode for class RealmConfiguration.

In this file:
public static final class Builder {
....
public Builder(Context context) {

Entering RealmConfiguration.class:
    public static final class Builder {
    ....
    Builder(Context context) {

In RealmConfiguration.java it's public
In RealmConfiguration.class it's internal

so new RealmConfiguration.Builder(this) does not compile with
Builder(android.content.Context) is not public...

#### Goal

> RealmConfiguration.Builder working

#### Expected Results

> RealmConfiguration.Builder should be public

#### Actual Results

>  Error:(16, 49) error: Builder(Context) is not public in Builder; cannot be accessed from outside package

#### Steps & Code to Reproduce

> Describe your current debugging efforts.

#### Code Sample

 RealmConfiguration realmConfiguration = new RealmConfiguration.Builder(this)
                .name(Realm.DEFAULT_REALM_NAME)
                .schemaVersion(0)
                .deleteRealmIfMigrationNeeded()
                .build();

#### Version of Realm and tooling
Realm version(s):  2.0.0-SNAPSHOT

Android Studio version:  2.2

Which Android version and device:  Nexus 10

**Comment by Zhuinden** [comment]
You should clean/rebuild and there was a breaking change, the `new RealmConfiguration.Builder(Context)` constructor was removed, now you need to call `Realm.init(Context)` from somewhere, and then the configuration has`new RealmConfiguration.Builder()`

**Comment by bryanspano** [comment]
https://github.com/realm/realm-java/tree/master/examples/introExample/src/main/java/io/realm/examples/intro

**Comment by Zhuinden** [comment]
Here's the commit https://github.com/realm/realm-java/commit/566c24f34e73732f38a88a32203921dde599072f

**Comment by NikhilRPatil** [comment]
Error:(44, 44) error: Builder(Context) is not public in Builder; cannot be accessed from outside package

 private void addAction() {
        String what = mInputWhat.getText().toString();
        long now = System.currentTimeMillis();
        RealmConfiguration configuration = new **RealmConfiguration.Builder**(getActivity()).build();
        Realm.setDefaultConfiguration(configuration);
        Realm realm = Realm.getDefaultInstance();
        Drop drop =new Drop(what,now,0,false);
        realm.beginTransaction();
        realm.copyToRealm(drop);
        realm.commitTransaction();
        realm.close();

    }
