### ISSUE TITLE
problem query item by date

### ISSUE THREAD

**Issue by tonyshare** [realm/realm-java#3475]
Realm 1.20 
I am using date to query realm objects, when the item's date is `Wed Sep 21 00:00:00`  and the query is `greatThanOrEqual("date", Wed Sep 21 00:00:00)` and `lessThanOrEqual("date", Wed Sep 21 23:59:59)`, I could not get the edge item.
Is there a graceful method to get realm object in a day?

**Comment by kneth** [comment]
Currently we don't many specialized methods for querying dates. You are welcome to create an issue for methods which you think could be useful.

The precision of Java dates is milliseconds, so adding and querying date in seconds might be less optimal. Moreover, time zone information might also cause problems as a date can easily drift into next day when it is stored in UTC.

**Comment by Zhuinden** [comment]
`greaterThanOrEqual("date", Wed Sep 21 00:00:00:000)` and `lessThanOrEqual("date", Thu Sep 22 00:00:00:000)` works for me. Just use `Date` instead of Strings of course.

**Comment by tonyshare** [comment]
Thanks for you help, when i add millisenconds, it work. Many thanks again.
