### ISSUE TITLE
Could not find io.realm:realm-gradle-plugin:2.0.0-SNAPSHOT

### ISSUE THREAD

**Issue by sixgodIT** [realm/realm-java#3479]
Error:Could not find io.realm:realm-gradle-plugin:2.0.0-SNAPSHOT.
Searched in the following locations:
    file:/Applications/Android Studio 2.app/Contents/gradle/m2repository/io/realm/realm-gradle-plugin/2.0.0-SNAPSHOT/maven-metadata.xml
    file:/Applications/Android Studio 2.app/Contents/gradle/m2repository/io/realm/realm-gradle-plugin/2.0.0-SNAPSHOT/realm-gradle-plugin-2.0.0-SNAPSHOT.pom
    file:/Applications/Android Studio 2.app/Contents/gradle/m2repository/io/realm/realm-gradle-plugin/2.0.0-SNAPSHOT/realm-gradle-plugin-2.0.0-SNAPSHOT.jar
    file:/Users/xzz/.m2/repository/io/realm/realm-gradle-plugin/2.0.0-SNAPSHOT/maven-metadata.xml
    file:/Users/xzz/.m2/repository/io/realm/realm-gradle-plugin/2.0.0-SNAPSHOT/realm-gradle-plugin-2.0.0-SNAPSHOT.pom
    file:/Users/xzz/.m2/repository/io/realm/realm-gradle-plugin/2.0.0-SNAPSHOT/realm-gradle-plugin-2.0.0-SNAPSHOT.jar
    https://jcenter.bintray.com/io/realm/realm-gradle-plugin/2.0.0-SNAPSHOT/maven-metadata.xml
    https://jcenter.bintray.com/io/realm/realm-gradle-plugin/2.0.0-SNAPSHOT/realm-gradle-plugin-2.0.0-SNAPSHOT.pom
    https://jcenter.bintray.com/io/realm/realm-gradle-plugin/2.0.0-SNAPSHOT/realm-gradle-plugin-2.0.0-SNAPSHOT.jar
    https://jitpack.io/io/realm/realm-gradle-plugin/2.0.0-SNAPSHOT/maven-metadata.xml
    https://jitpack.io/io/realm/realm-gradle-plugin/2.0.0-SNAPSHOT/realm-gradle-plugin-2.0.0-SNAPSHOT.pom
    https://jitpack.io/io/realm/realm-gradle-plugin/2.0.0-SNAPSHOT/realm-gradle-plugin-2.0.0-SNAPSHOT.jar
Required by:
    project :encryptionExample

**Comment by beeender** [comment]
You need run `./gradlew assemble` first.
See https://github.com/realm/realm-java/blob/master/README.md#build

**Comment by kneth** [comment]
I believe that the comment above answers the question. Don't hesitate to open a new issue if you have further questions.
