### ISSUE TITLE
Feature Request: between method on RealmLists

### ISSUE THREAD

**Issue by wickermoon** [realm/realm-java#3483]
**Feature Request**
#### Goal
I would like to filter any RealmList for a certain timespan. There is already a minDate and a maxDate method, but no between method.

#### Expected Results

RealmList<>::between(String dateColumnName, Date from, Date to) : RealmList<> returns a sublist of RealmObjects filtered by the given timespan from "from" to "to" on the column <dateColumnName>.

#### Code Sample

```java

father.getKids().between("timestamp", from, new Date()); // get every kid from some certain date up until now.

```

**Comment by Zhuinden** [comment]
Have you tried `father.getKids().where().between("timestamp", from, new Date()).findAll()`?

**Comment by wickermoon** [comment]
What stupid sheep I am. *blush* I totally missed the where method. I am so sorry. :(

**Comment by Zhuinden** [comment]
Glad to hear it works 😄
