### ISSUE TITLE
Architecture caused Nested transactions error ?

### ISSUE THREAD

**Issue by kuno** [realm/realm-java#3485]
I am using realm as the main database layout in my app, it was using by many components of the app.

* In the background there are several job to fetch the data from server then save into realm periodically.
* In the ui part, all Activity was inherited from a BaseActivity which has a `mRealm` instance.

In the last few days, I was experienced  a lot of crash caused by `Nested transactions error`, such as 

``` java
 java.lang.IllegalStateException: Nested transactions are not allowed. Use commitTransaction() after each beginTransaction().
```

I dont believe it was caused by specific piece of code, because I am just saving to realm in a "normal" way like

```kotlin
val model = SvcModel.createFromJsonData(data)
realm.beginTransaction()
realm.copyToRealmOrUpdate(model)
realm.commitTransaction()
```

It is possible the crash was caused by a ui transaction and background job transaction happens in same time ?

Edit:
Realm version: 1.2.0
Android Studio version: 2.2

I saw some people in https://github.com/realm/realm-java/issues/542 mentioned that if somewhere else in your app a transactioin was not properly closed, to open a new transaction will cause the problem.

**Comment by Zhuinden** [comment]
This shouldn't fail that way that's for sure, but using `realm.executeTransaction()` always makes things safer.

**Comment by kuno** [comment]
@austinzheng 

What about the sync and async transaction ?

**Comment by kneth** [comment]
It is correct that Realm doesn't support nested transactions. You can use [`Realm.isInTransaction()`](https://realm.io/docs/java/latest/api/io/realm/Realm.html#isInTransaction--) before doing a `beginTransaction()`. 

Async transactions are executed on another thread but they will be blocked until the "parent" transaction is either committed or cancels so I can't see how you benefit from that.

Best thing is to do a little review of your app's architecture to understand why you have nested transactions.

**Comment by kneth** [comment]
I'm closing the issue for now. Don't hesitate to ask/reopen/create new issue if you have further questions.
