### ISSUE TITLE
copyToRealmOrUpdate() and createAllFromJsonOrUpdate() must update not replace existing data

### ISSUE THREAD

**Issue by yaaminu** [realm/realm-java#3490]
When importing data into realm using on of the copyUpdate* methods, all exiting data are replaced by the new data which normally leads to losing data stored purposely for local use notably null values and empty arrays replacing locally set values. This is especially true when the local schema has extra fields than the  server sent data.

**Comment by Zhuinden** [comment]
Ummm.... So if Realm just "ignored"  null and empty values, how would you ever set any value to `null`? 

Unfortunately, updating makes sense by replacing the object. If you need to merge existing data, you should merge it yourself. After all, **you** know that you should ignore nulls.

**Comment by yaaminu** [comment]
@Zhuinden this makes it impossible to use the json import feature of realm. if it could be supported in realm where an overload of copyToRealmOrUpdate will take an extra boolean argument to decide whether to replace set non-null values, it will be simpler and faster.

**Comment by Zhuinden** [comment]
I'm just a community member, labeling this as a possible enhancement is up to @zaki50 and the others :smile:

**Comment by TR4Android** [comment]
I'll second that. I'd be nice to have `copyOrUpdate` methods that track what fields have been actually set and then

* use the default values for unset fields when the object doesn't exist
* keep the previously set values for unset fields when the object already exists

**Comment by snowpong** [comment]
I stumbled into this problem as well - see https://github.com/realm/realm-java/issues/3500. 

I think the method name is misleading. Users of the API seems to assume it updates fields that changed in the Realm Model, not that it overwrites them all wholesale (which it does).

In an SQL UPDATE I believe one can specify conditions (for example NOT NULL) for when/if the update should happen. And HTTP has both PATCH and PUT. Clearly there is a need for this sort of functionality in Realm as well.

**Comment by kneth** [comment]
Finally I can advice you to take a look at https://realm.io/docs/java/latest/#the-realm-mobile-platform

**Comment by TR4Android** [comment]
@kneth The primary key is not the problem, but the field updating policy is. Consider, for example, this model class:

```java
public class Model extends RealmObject {
    String remoteField;
    String localField;
}
```

When the database is synced only the `remoteField` is updated, which leaves the `localField` reset to the default value after a call to `copyToRealmOrUpdate`. I'm guessing that's also the case with @yaaminu.

**Comment by Zhuinden** [comment]
@TR4Android well, they should query the object and update its fields; and create it only if it doesn't yet exist.

**Comment by TR4Android** [comment]
@Zhuinden I know, but this leads to more code then necessary as different code needs to be written for new and updated objects. Plus, lots of people use JSON adapters that create POJOs and then this approach wouldn't work. In any case, ideas for solving this are discussed in issue #3500.

**Comment by yaaminu** [comment]
@Zhuinden your approach makes sense for small datasets, maybe less than 100. if i have a bout huge amount of data with different model, i may get lost in the middle as i have to check emptines and null-ness myeself in application code, worse, if my schema changes i have to updated that code too. also it wont scale. for a data set that gets updated from frequently. if  this is done under the hood for us, it will be very great.

**Comment by yaaminu** [comment]
@kneth I am very happy to hear about the realm mobile platform, but it doesn't fit my need here. all my data has to be stored somewhere and retrieved over http.

**Comment by kneth** [comment]
I'll close the issue and suggest that we use #3500 for further discussions.
