### ISSUE TITLE
Feature request for Realm instances that only last for one transaction

### ISSUE THREAD

**Issue by biagionicp** [realm/realm-java#3491]
In my android application I have a `RealmSingleton` class that I use to store all my configuration information, so when I want a particular Realm instance I do RealmSingleton.getUserInstance(). However, I find keeping track of which Realm is open where, and when to close which to be frustrating, especially when on Android there is no built-in method for determining when your application has been closed, opened from being closed, that the user just pressed the home button, or that the app has been resumed from not being closed; and the solutions I've seen that implement these methods don't seem very elegant.

Ideally, it would be in these methods where we get all our Realm instances and then close them, but being that they don't exist, another way would be to have Realm instances that are only open for a single transaction. That way, if you only make a small amount of changes to Realm throughout your code, you don't have to go through the hassle of opening and closing Realms at the appropriate times in your application, and can instead just get an instance that only lasts for one transaction, and not have to do something like this:
```
Realm userRealm = RealmSingleton.getUserInstance()
userRealm.executeTransactionAsync(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {
                //make changes
            }
        });
userRealm.close()
```
Another option would be to have a `Transaction` that just automaticaly closes the `Realm` when it's done.

**Comment by Zhuinden** [comment]
> the solutions I've seen that implement these methods don't seem very elegant.

I'm not sure which solutions you are referring to. 

But there is a reason why I made this method in my samples 

``` java
/**
 * Created by Zhuinden on 2016.07.29..
 */
public class RealmUtils {
    static void executeInTransaction(RealmConfiguration realmConfiguration, Realm.Transaction realmTransaction) {
        Realm realm = null;
        try {
            realm = Realm.getInstance(realmConfiguration);
            realm.executeTransaction(realmTransaction);
        } finally {
            if(realm != null) {
                realm.close();
            }
        }
    }

    public static void executeInTransaction(Realm.Transaction realmTransaction) {
        executeInTransaction(Injector.INSTANCE.getComponent().realmConfiguration(), realmTransaction);
    }
}
```

But this makes sense primarily only on background threads.

**Comment by biagionicp** [comment]
yea. i ended up just doing something similar.

**Comment by Zhuinden** [comment]
So i can access it in finally

**Comment by cmelchior** [comment]
Hi @biagionicp. Thanks for the suggestion.
I can see the use case, but we have to strike a fine balance between offering enough API's that make Realm easy to use while still keeping the API as small as possible.

In your case, you can easily achieve the same with a helper method of your own just like @Zhuinden suggested. So I don't think this is something we would want to add native support for as it would conflict with how we normally do transactions.
