### ISSUE TITLE
Fatal Exception: java.lang.UnsatisfiedLinkError : librealm-jni.so not found

### ISSUE THREAD

**Issue by cyber7eyes** [realm/realm-java#3496]
> What do you want to achieve?

No Problem is occured with realm

#### Actual Results

>  Some of Android Smartphone of LG are crashed

#### Steps & Code to Reproduce

> I fixed my code with "Couldn’t load “librealm-jni.so” from Realm Blog.

but We can't fix a bug.

#### Code Sample

```java

> 
RealmConfiguration config = new RealmConfiguration.Builder(this)
                .schemaVersion(47)
                .migration(new Migration())
                .build();

        Realm.setDefaultConfiguration(config);
        Realm.getInstance(config);

```

```
   ndk {
        abiFilters "armeabi", "armeabi-v7a", "x86", "x86_64"
   }

```

#### Version of Realm and tooling
Realm version(s): 1.2.0

Android Studio version: 2.2

Which Android version and device: 4.4.2 , 4.4.4 , 4.2.0

## ERROR LOG

http://crashes.to/s/c7a78b064b1

**Comment by kneth** [comment]
In the latest version (2.0.0 from yesterday), we have updated to a newer version of ReLinker.  Is it possible to upgrade your app and see if it solves your issue? If not, we will be happy to hear from you so we can investigate further.

**Comment by kneth** [comment]
I am closing the issue. Don't hesitate to reopen or create new if issue still persists.
