### ISSUE TITLE
io.realm.exceptions.RealmError: Unrecoverable error. Incompatible lock file in io_realm_internal_SharedGroup.cpp line 113

### ISSUE THREAD

**Issue by niknowzcd** [realm/realm-java#3498]
> I at the react-native set-up a realm by code
    
    const CarSchema = {
    name: 'Car',
    primaryKey: 'id',
    properties: {
    id: 'int',
    car_type: 'string',
    car_name: 'string',
    driver_name: 'string',
    }
    };
    
    //初始化Realm
    	
    let realm = new Realm({schema: [CarSchema]});
> 
> And  I at Android use this realm  by 
    
     RealmConfiguration configuration=new RealmConfiguration.Builder(this)
    //.name("myOtherRealm1.realm")
    .name("default.realm")
    .deleteRealmIfMigrationNeeded()
    .migration(new CustomMigration())
    .build();
    
    mRealm = Realm.getInstance(configuration);

### system take me the error :  
io.realm.exceptions.RealmError: Unrecoverable error. Incompatible lock file in io_realm_internal_SharedGroup.cpp line 113 ###

### ps: the question is not in realm name ###

**Comment by Zhuinden** [comment]
The core versions between realm react native and realm-java don't match, so they can't be used to operate on the same Realm file at the same time yet.

**Comment by niknowzcd** [comment]
> the core versions Refer to realm versions？

if true，
How can I do match realm versions

because i find realm react-native Newest versions is 0.14.3

realm-java is not 0.14.3 versions

**Comment by Zhuinden** [comment]
Technically the problem was that the core version for Realm-Android was 1.5.1 while Realm-React-Native was 1.5.0

Technically when Realm-React-Native comes out with support for Realm-Core 2.0.0, they'll work together

**Comment by niknowzcd** [comment]
Realm-React-Native was 1.5.0?

at [https://realm.io/ ](https://realm.io/) 
the Realm react-native core versions Latest is 0.14.0

I want confirm  Realm react-native  and Realm java  can
work together now in some core versions

ps:Thanks a lot,I'm sorry Occupies so much of your time in
this simple question

**Comment by kneth** [comment]
Sorry for the confusion - Realm has many products with different version numbers.

Realm Core is the underlying database engine which all products are using.

Latest version of Realm Java is 2.0.0 which uses Realm Core 2.0.0.
Latest version of Realm React 0.14.0 which uses Realm Core 1.5.0.

Realm Java 1.2.0 is using Realm Core 1.5.1.

On Android, we don't have multi-process support so you cannot have two apps sharing a Realm file.

**Comment by Zhuinden** [comment]
@kneth technically React-Native and Java would be in the same process, but they might not see each other as such.

**Comment by kneth** [comment]
Until Realm React is upgraded, you must use Realm Java 1.2.0 to be compatible.

**Comment by Zhuinden** [comment]
@kneth Realm Core 1.5.0 is compatible with 1.5.1?
