### ISSUE TITLE
We need armeabi in Realm 2.0 !

### ISSUE THREAD

**Issue by vincgao** [realm/realm-java#3508]
Our video Teams only provide us with video lib supported in armeabi. So I can't upgrade realm libs to the new version. 

So, We hope Realm 2.0 supported in armeabi can come back, thx ! :)

#### Version of Realm and tooling
Realm version(s): 2.0

Android Studio version: Android Studio 2.2

Which Android version and device: Samsung C7

**Comment by beeender** [comment]
There is a problem with ndk 10e that it failed to compile some of our cpp source code.
But we do have a plan to update the ndk version. I think it is possible and reasonable to bring armeabi back since some other native lib only support that .

**Comment by vincgao** [comment]
I'm using ndk 12b, Maybe we can try compiling cpp code with new ndk version.

Anyways, Thanks a lot for your distribution of this brilliant project!

**Comment by beeender** [comment]
close and dup to #3506 which has more information.
