### ISSUE TITLE
Reduce native build times

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#3515]
Moving to CMake has caused our build times to explode. We need to fix that.

Possible solutions:
- Some sort of custom caching.
- @emanuelez found http://audited-objects.sourceforge.net/ that might be an option
- New linker?
- CCache?
- Other options?

**Comment by emanuelez** [comment]
Ccache is a low-hanging fruit and it's being implemented by #3518.

I tried Audited Objects but it seems to fail miserably on Gradle builds. I opened an issue on the repo of the project [here](https://github.com/boyski/audited-objects/issues/10) but I will stop investigating this route for now.

**Comment by beeender** [comment]
lcache integrated with CI.
