### ISSUE TITLE
Conflict to JNI directory

### ISSUE THREAD

**Issue by plmmmmlq** [realm/realm-java#3519]
#### Goal

> What do you want to achieve?

#### Expected Results

> Read and write my chat records.

#### Actual Results

>  Confict to other libraries with .so files.

#### Steps & Code to Reproduce

> Describe your current debugging efforts.

My module uses Jpush and its *.so files are in "libs/armeabi", I deleted other directories such as "armeabi-v7a","armeabi-v8a","mips","x86","x86_64", and my app runs normal.When I configured REALM into my project, it could not run normal, exceptions below:

[JPushInterface] System.loadLibrary::jpush217java.lang.UnsatisfiedLinkError: dalvik.system.PathClassLoader[DexPathList[[zip file "/data/app/com.market.client-2/base.apk"],nativeLibraryDirectories=[/data/app/com.market.client-2/lib/arm, /vendor/lib, /system/lib]]] couldn't find "libjpush217.so"

No implementation found for int cn.jpush.android.service.PushProtocol.GetSdkVersion() (tried Java_cn_jpush_android_service_PushProtocol_GetSdkVersion and Java_cn_jpush_android_service_PushProtocol_GetSdkVersion__)
09-28 20:04:24.278 31415-31415/com.market.client E/JPush: [JPushGlobal] Get sdk version fail!

I want to know if I could configure the gradle in my build.gradle file so that REALM's don't conflict with mine. Thank you for helping me, If I couldn't solve this problem I have to use SQLITE database. Thank you again.

#### Version of Realm and tooling
Realm version(s): Realm Version:1.2.0

Android Studio version: 1.5.1

Which Android version and device: Android Version:5.1.1

**Comment by beeender** [comment]
See https://github.com/realm/realm-java/issues/3504#issuecomment-250077166

The solution would be similar to above. You need to exclude those `librealm-jni.so` ABIs which you don't have for jpush.

**Comment by plmmmmlq** [comment]
@beeender Thank you so much,I'll give you a feedback soon.

**Comment by plmmmmlq** [comment]
Sorry, I let you down. After I tried several times it still did not work.
``` groovy
    packingOptions {
        exclude "jni/arm64-v8a/" // Also tried exclude "jni/arm64-v8a/librealm-jni.so"
    }
```
And I have to give up this time because of slow progress.

**Comment by kneth** [comment]
I believe it should be `exclude "lib/arm64-v8a/librealm-jni.so"`. See also https://realm.io/docs/java/latest/#couldnt-load-librealm-jniso

**Comment by beeender** [comment]
@plmmmmlq you need to clean the project (at least delete those `so` files in the build folder before packaging). AS will just pack everything there. To check the result, just decompress the final `apk` file, and see if the file is still there. If yes, check the path in the `apk` and the path in your build file, they might be mismatched.

**Comment by kneth** [comment]
I hope that the comments above have help you. If not, don't hesitate to reopen or create new issue.

**Comment by plmmmmlq** [comment]
Thank you so much, I had no enough time to practise with REALM, so I used SQLITE instead, I'll practise with REALM in my next project.
