### ISSUE TITLE
Running a Realm Object Server on Android

### ISSUE THREAD

**Issue by gpulido** [realm/realm-java#3524]
Hello,
I've just read the documentation of your new Realm Object Server and it is very impressive.
However I would like to know if there is any way to share / sync one realm on several devices WITHOUT using a central server.
I have several android devices that have to be in sync with one central android device that is behaving as a master, at this moment I'm using a combination of zeroconf to discover, restserver on the master android device and retrofit with JSON serialization to move data from one device to the master and viceversa, and it would be amazing to just point the slaves Realms to the master ip and have all devices sharing the same data.

On the Realm Object Server it says:

```
Messaging
Share text, images, maps, or custom data. No server work needed.
```

How can it be achieved?
Thank you in advance

**Comment by Zhuinden** [comment]
Well while I'm pretty sure that's not possible at the moment, that would be ridiculously awesome for peer-to-peer applications.

**Comment by gpulido** [comment]
Hello,
Once the Realm already have the possibility to look outside the device for a realm using the sync context, I guess that the tricky part is to create some kind of server / service / socket wrapper over the android instance that is behaving as master.

The current Android status is to use Nearby messaging, but for using that you have to serialize / parse the data and it is cumbersome, or the solution that I came to:
The master starts a local http server and a zeroconf/bonjour to advertise it. The slaves just made push to share the info with the master after a serialization / parsing is made on both sides (in my case using retrofit and json) This mechanism forces to take care of all the object sync manually (obviously)

This would make game synchronization (for example) a breeze.

**Comment by nhachicha** [comment]
Hi @gpulido 
There's no peer to peer feature yet.

for the example doc you still need the server to sync those Realms, but not our event framework (the code you write using _Node.js_ server side)

The only samples now are:
- https://github.com/realm/realm-java/tree/master/examples/objectServerExample
- https://github.com/realm/RealmTasks/tree/master/RealmTasks%20Android

cheers

**Comment by nhachicha** [comment]
Sorry we don't provide a binary that could run on Android yet.
Theoretically this is not complicated since Android is GNU/ Linux (and we provide the binary for GNU/Linux). But   ww need to compile using NDK tools chain and make sure the lib you rely on are available on Android

**Comment by gpulido** [comment]
Hello,
Thank you for the answer.
Maybe in a future. As I said, that would made very easy to create p2p data sharing between devices without the need of having internet connection, just share a common connection.
I though that as you already have to compile the binary for the Realm database for Android, the "server" extension should be at least "accessible" (not easy, I know).

As a comment, The Object server would execute on a Raspberry pi? It would be another posibility, just to add a "sync server" on the network just to have a local network (not internet based) sharing data system.

**Comment by roberhofer** [comment]
This is unlikely on the cards for Realm in the near future. So closing.
