### ISSUE TITLE
How do i migrate from activeandroid to realm.

### ISSUE THREAD

**Issue by srinivas3120** [realm/realm-java#3535]
I have a live android app with activeandroid database. i want to migrate to realm. when app is upgraded, i want migrate all the data from activeandroid database to realm database ? how can i do this ? in how many ways can this be possible ? which one is the recommended one.

**Comment by zaki50** [comment]
Since Realm is not the ORM of SQLite, the only way to migrate from other databases is just read from them and write into Realm manually (maybe in background thread).

**Comment by srinivas3120** [comment]
@zaki50 thanks you.

**Comment by srinivas3120** [comment]
@zaki50 
1. does realm support joins(inner, outer joins) ? how can i achieve this if any alternatives.
2. how can i create content providers considering i have more than one databases(/encrypted) on my application ?

**Comment by Zhuinden** [comment]
@srinivas3120 "joins" don't make sense in Realm because it's not a relational database. But there are "relationships", which are essentially navigational properties between objects. You need to set the navigational properties manually.

    public class Dog extends RealmObject {
         private Person owner;

         // getter, setter
    }

2.) While 2.0.0+ supports multi-process, Realm doesn't expose Cursors yet, and the query language isn't SQL. So it's kinda messy to work with a ContentProvider, **but** RealmCursor actually exists as a pull request, so it's not impossible.

**Comment by zaki50** [comment]
Realm Java 2.0.0 does not support multi process yet (actively working on it though).

**Comment by Zhuinden** [comment]
@zaki50 it doesn't? But it handles interprocess transactions / locking

**Comment by srinivas3120** [comment]
are relationships supported across databases? Dog ReamObject belongs to one database and Person belongs to other. can this be possible? :P

**Comment by Zhuinden** [comment]
I don't think that's supported in SQLite either.

**Comment by srinivas3120** [comment]
@zaki50 relationships supported across databases(and tables)? is this one planned for future releases ?

**Comment by zaki50** [comment]
@srinivas3120 not supported and we don't have a plan to support it for now.

**Comment by zaki50** [comment]
@Zhuinden see https://github.com/realm/realm-java/issues/1091#issuecomment-244039670 about multi process support.
Not well tested and there is some limitations at least.

**Comment by zaki50** [comment]
I'll close this.

If you have further questions, feel free to reopen this.
