### ISSUE TITLE
(Thread problem)限制reaml相关API进行操作的线程是个不好的设计

### ISSUE THREAD

**Issue by ouyangzn** [realm/realm-java#3536]
**// in main thread**
```java
mCollectList = mApp.getGlobalRealm()
        .where(CollectedRepo.class)
        .findAllSortedAsync("collectTime", Sort.DESCENDING);
// 不能在rxJava创建的子线程调用，导致上面需要在main线程创建
// can't called in other io thread created by rxJava, so... mApp.getGlobalRealm() must in main thread
mCollectList.addChangeListener(mCollectChangeListener);
```
**// 在接下来的使用中，我也只能在main线程去操作realm相关的API
// other operate must in main thread**
```java
Observable.create(new Observable.OnSubscribe<Void>() {
      @Override public void call(Subscriber<? super Void> subscriber) {
        Realm realm = mApp.getGlobalRealm();
        try {
          realm.beginTransaction();
          realm.where(CollectedRepo.class).equalTo("id", repo.id).findAll().deleteAllFromRealm();
          realm.commitTransaction();
          subscriber.onNext(null);
        } catch (Exception e) {
          if (realm.isInTransaction()) realm.cancelTransaction();
          subscriber.onError(e);
        }
      }
      // can't in io thread, must in main thread
    }).subscribeOn(AndroidSchedulers.mainThread()).subscribe(new Action1<Void>() {
      @Override public void call(Void aVoid) {
        if (mView != null) {
          mView.showNormalTips(mApp.getString(R.string.tip_collect_cancel_success));
        }
      }
    }, new Action1<Throwable>() {
      @Override public void call(Throwable throwable) {
        Log.e(TAG, "---------取消收藏失败:", throwable);
        if (mView != null) {
          mView.showErrorTips(mApp.getString(R.string.error_collect_cancel_failure));
        }
      }
    });
```
这种操作很奇怪，一不小心就抛异常

**Comment by beeender** [comment]
Hi,

So `mApp.getGlobalRealm` will return a global Realm instance always? This is not designed usage of Realm instance ... Maybe our [document about thread](https://realm.io/cn/docs/java/latest/#threading) could help a bit here?

**Comment by ouyangzn** [comment]
Here is getGlobalRealm(). Because i have more than 1 database, so this is one way get realm.
```java
public Realm getGlobalRealm() {
    return Realm.getInstance(new RealmConfiguration.Builder(sApp).name(DB_NAME)
        // 密码必须64个字节
        .encryptionKey(getGlobalRealmKey())
        .schemaVersion(DB_VERSION)
        .migration(new GlobalRealmMigration())
        //.deleteRealmIfMigrationNeeded()
        .build());
  }
```

**Comment by beeender** [comment]
OK, the `getGlobalRealm` should be fine.

What is the exact problem you met? Is it about you were trying to use `mCollectList` from a different thread (than the one where you created the `mCollectList` on)?

**Comment by ouyangzn** [comment]
I want delete some data in mCollectList, but i must do this in main thead, can not in io thread.
just like this:
```java
Observable.create(new Observable.OnSubscribe<Void>() {
      @Override public void call(Subscriber<? super Void> subscriber) {
        Realm realm = mApp.getGlobalRealm();
        try {
          realm.beginTransaction();
          realm.where(CollectedRepo.class).equalTo("id", repo.id).findAll().deleteAllFromRealm();
          realm.commitTransaction();
          subscriber.onNext(null);
        } catch (Exception e) {
          if (realm.isInTransaction()) realm.cancelTransaction();
          subscriber.onError(e);
        }
      }
      // ---------------can't in io thread, must in main thread---------------
    }).subscribeOn(AndroidSchedulers.mainThread()).subscribe(new Action1<Void>() {
      @Override public void call(Void aVoid) {
        if (mView != null) {
          mView.showNormalTips(mApp.getString(R.string.tip_collect_cancel_success));
        }
      }
    }, new Action1<Throwable>() {
      @Override public void call(Throwable throwable) {
        Log.e(TAG, "---------取消收藏失败:", throwable);
        if (mView != null) {
          mView.showErrorTips(mApp.getString(R.string.error_collect_cancel_failure));
        }
      }
    });
```

**Comment by Zhuinden** [comment]
``` java
    public final class DeleteCollectedRepoByIdObservable
            implements Observable.OnSubscribe<Void> {
        @Override
        public void call(final Subscriber<? super Void> subscriber) {
            MainThreadSubscription.verifyMainThread();
            Realm realm = mApp.getRealm();
            realm.executeTransactionAsync(bgRealm -> {
                bgRealm.where(CollectedRepo.class).equalTo("id", repo.id).findAll().deleteAllFromRealm();
            }, () -> {
                if(!subscriber.isUnsubscribed()) {
                    subscriber.onNext(null);
                }
            }, error -> {
                if(!subscriber.isUnsubscribed()) {
                    subscriber.onError(error);
                }
            });
            
            //subscriber.add(new MainThreadSubscription() {
                //@Override
                //protected void onUnsubscribe() {
                // }
            //});
        }
    }
```

**Comment by ouyangzn** [comment]
here is my project:
[code](https://github.com/ouyangzn/OpenSource)
key code is in package:
[collect code](https://github.com/ouyangzn/OpenSource/tree/master/app/src/main/java/com/ouyangzn/github/module/collect)

**Comment by ouyangzn** [comment]
@Zhuinden 
Hi, thanks for answer, you code is right. Now i have a question, why this didn't work?
thrown exception: Realm access from incorrect thread
```java
MainThreadSubscription.verifyMainThread();
mApp.getGlobalRealm().executeTransactionAsync(bgRealm -> {
      // 此操作却会抛异常：Realm access from incorrect thread
      bgRealm.where(CollectedRepo.class).equalTo("id", repo.id).findAll().deleteAllFromRealm();
    }, () -> {
      if (mView != null) {
        mView.showNormalTips(mApp.getString(R.string.tip_collect_cancel_success));
      }
    }, error -> {
      Log.e(TAG, "---------取消收藏失败:", error);
      if (mView != null) {
        mView.showErrorTips(mApp.getString(R.string.error_collect_cancel_failure));
      }
    });
```

**Comment by Zhuinden** [comment]
It's probably going to be `repo.id` So change code like this:

    final long repoId = repo.id;
    mApp.getGlobalRealm().executeTransactionAsync(bgRealm -> {
      bgRealm.where(CollectedRepo.class).equalTo("id", repoId).findAll().deleteAllFromRealm();
    }, () -> {

Sorry about that oversight

**Comment by ouyangzn** [comment]
@Zhuinden 
@kneth 
sorry for waiting so long, because i have a long holiday.
```java
final long repoId = repo.id;
mApp.getGlobalRealm().executeTransactionAsync(bgRealm -> {
  bgRealm.where(CollectedRepo.class).equalTo("id", repoId).findAll().deleteAllFromRealm();
}, () -> {
```
this is right, but i don't know the reason. why?

**Comment by zaki50** [comment]
`repo` is bound to the UI thread, and `repo.id` is traslated to database access (`repo.realmGet$id()`) by Realm's transformer. This method call can be done only from the bound thread.

**Comment by ouyangzn** [comment]
Ok, i know, the `repo` is replaced with `CollectedRepoRealmProxy`, so we can only used `repo` at bound thread.
Thanks a lot!
By the way, i still can't understand the design that limit the thread of Realm. It brought me some thouble, i can't use RealmObject as well as normal Object.  ( ^_^ )

**Comment by Zhuinden** [comment]
This article might help: https://medium.com/@Zhuinden/how-to-use-realm-for-android-like-a-champ-and-how-to-tell-if-youre-doing-it-wrong-ac4f66b7f149

But the short story is this:

- in order to avoid having to synchronize values of RealmProxies between threads, they're thread-confined (this way, no actual "locking" is necessary and no "volatile" nonsense, thus making Realm access faster)
- each Realm instance that belongs to a specific thread is locked at the version of the Realm that existed when you obtained an instance to the Realm
- each Realm instance updates to the latest version of the Realm when `nativeSyncIfNeeded()` is called, this behavior is automatic on the UI thread (or any thread with a looper and `setAutoRefresh(true)`, but that is uncommon), after which the RealmChangeListeners are called
- a Realm instance always sees the *latest* version of the Realm while in a transaction, regardless of whether it's on a looper thread or not
- because synchronization locks are avoided, you can't access RealmObject from a different thread, only the thread it belongs to

Not sure if I helped

**Comment by zaki50** [comment]
I'll close this.

If you'll have further questions, feel free to reopen this.
