### ISSUE TITLE
Release v-2.1.0 to bintray

### ISSUE THREAD

**Issue by ravikumar-n** [realm/realm-java#3540]
Could you please push the version `2.1.0` to bintray?

 I see version `2.1.0` listed in `Changelog.md` file but the latest version available in bintray is `2.0.0`.

**Comment by FabianTerhorst** [comment]
The latest Version in the changelog is the Version from the last snapshot.

**Comment by zaki50** [comment]
That's the next release.

We usually releases the latest master as a SNAPSHOT, but now there is an issue #3513 
You'll be able to get latest master as a SNAPSHOT from bintray once we fix that issue.
