### ISSUE TITLE
RealmList.toString() -> Write out each elements toString() rather than the total size?

### ISSUE THREAD

**Issue by zoltish** [realm/realm-java#3543]
I love the `toString()` method your proxy classes use for realm-objects, but it would be extremely useful if it also included the elements in the given RealmList - rather than just writing out its size.

**Current:**
programDays:RealmList<ProgramDay>[3]

**Wish**
programDays:[{name: DayOne},{name: DayTwo},{name: DayThree}]

Hope to see that in a future release. Thank you!

**Comment by kneth** [comment]
If you have cyclic data structures, printing out all elements will take infinite time. That's one of the reasons we chose to not do it.

**Comment by loudenvier** [comment]
I don't think this is a great idea either. The cyclic redundancy can be overcome, but it is way too much trouble for little gain.

**Comment by cmelchior** [comment]
Hi @zoltish Thanks for the suggestion, but as already mentioned there is a number of concerns. Cyclic dependencies is one which could probably be solved by some arbitrary depth limit, but big lists would also be pretty bad. So for that reason we won't be implementing something like this.

If you want to debug a RealmList, using the following code would give you the same desired effect:

```
Arrays.toString(types.getFieldList().toArray());
```
