### ISSUE TITLE
Description field in Table as String is JSON automatically 

### ISSUE THREAD

**Issue by ialex90** [realm/realm-java#3544]
I have in my model a member class property called "description" as a String, among others. It seems to be that calling description to the property, when you insert data into it, it is saved as a JSON with all the info of the object, including the description.

When consuming the object from database, there's not problem at all, you call object.getDescription() and it works, but semantically in the DB is not correct.

I avoided this problem renaming that property, to "des", being a String yet, and it works perfectly.

I attached 2 pictures to give more details about what I explained above.

![des](https://cloud.githubusercontent.com/assets/5755545/19019949/de8df3d4-8891-11e6-9058-a2986288f6d2.png)
![description](https://cloud.githubusercontent.com/assets/5755545/19019951/de925334-8891-11e6-82d3-0b4f86336f97.png)

btw, I don't find any mention of this in the documentation.

Thanks :)

**Comment by stk1m1** [comment]
@ialex90 

Would it be too impolite to ask you to repost the issue on <https://github.com/realm/realm-browser-osx>? This is not Realm-Java specific issue per se. 

The word [`description`](https://developer.apple.com/reference/objectivec/1418956-nsobject/1418746-description?language=objc) is a reserved method for all `NSObject`s that confirm `NSObjectProtocol` which yields all the property values of an object in `NSString`. Realm Browser, as you can see, is written in ObjC for OSX and is thus under the influence of that rule just as apps in Java should follow the rules for the reserved words.

This also confirms that your observation on the behavior of `object.getDescription()` to be correct as the ObjC rule has nothing to do with Java.

My rough guess is that somehow Realm Browser slips a particular case where a RealmObject has a field named `description`, which should be treated specially. Experts at realm will take care of this issue in no time. 😉

**Comment by ialex90** [comment]
That does make sense, I got it. I didn't know if it was a problem related to the DB or the Realm Browser actually.

I won't report this issue in the realm browser repo because I found a thread already written in there talking about same issue:

https://github.com/realm/realm-browser-osx/issues/198

Anyways, I truly think there should be this info in the documentation.

Thanks for the help 👍
