### ISSUE TITLE
Installing ROS on Fedora

### ISSUE THREAD

**Issue by danogbuagu** [realm/realm-java#3546]
#### Goal

> Ability to install Realm Object Server in Fedora

#### Expected Results

> ?

#### Actual Results

>  E.g. full stack trace with exception

#### Steps & Code to Reproduce

> Describe your current debugging efforts.

#### Code Sample

```java

> Your code here. Bigger samples should ideally be as separate Android Studio project, 
> in gists/repositories or privately at help@realm.io)

```

#### Version of Realm and tooling
Realm version(s): ?

Android Studio version: ?

Which Android version and device: ?

**Comment by zaki50** [comment]
@danogbuagu There is a separate issue tracker for realm mobile platform.
Please create this on that.

https://github.com/realm/realm-mobile-platform/issues

I'll close this.
