### ISSUE TITLE
Explore alternatives to OpenSSL

### ISSUE THREAD

**Issue by kneth** [realm/realm-java#3548]
OpenSSL is a bloated library, and we should explore the alternatives.
- BoringSSL
- LibreSSL
- WolfSSL

**Comment by emanuelez** [comment]
WolfSSL seems promising in terms of history, size (20 times smaller than OpenSSL) and cross-platform support. One problem might be its license: it's GPLv2 with a commercial license available for purchase.

**Comment by tgoyne** [comment]
[PolarSSL](https://tls.mbed.org/) is now Apache 2.0, and is what I probably would have originally used for the encryption functionality if that had been the case then.

**Comment by morten-krogh** [comment]
I generally like the documentation and philosophy of mbed TLS (formerly PolarSSL).

It is not FIPS certified.

BoringSSL should be considered fro being the official Android library.
Doesn't it make sense to choose a library that is somewhat endorsed by Google for 
Android? If we use the same library as Java programs do, we should be fine with customers.

**Comment by tgoyne** [comment]
BoringSSL is just a set of patches on OpenSSL and is explicitly not intended for third-party use.

**Comment by diegomontoya** [comment]
@tgoyne BoringSSL is not a set of patches of OpenSSL. It is a complete fork followed by lots of low level refractor and used currently in Chrome for all platforms. https://boringssl.googlesource.com/boringssl/

**Comment by emanuelez** [comment]
It's also used on Android nowadays and that's why they started forbidding linking dynamically to libraries already installed on the phone. But they do say not to rely on its API to be stable.

**Comment by cmelchior** [comment]
Realm Core will be switching to Libre SSL once they are done with CMake support: https://github.com/realm/realm-core/pull/1883 . We will do the same as part of #3506
