### ISSUE TITLE
Flaky unittest - SecureKeyStore

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#3555]
---

io.realm.android.UserStoreTest > encrypt_decrypt_UsingAndroidKeyStoreUserStore[SHIELD Tablet K1 - 5.1.1] [31mFAILED [0m java.lang.AssertionError: expected:<io.realm.User@1cc7026d> but was:`<null>`

----

But all test devices have PIN enabled.

/cc @nhachicha

**Comment by cmelchior** [comment]
Another example: https://ci.realm.io/job/realm/job/realm-java/job/PR-3561/2/

**Comment by nhachicha** [comment]
https://github.com/realm/realm-java/issues/3565

**Comment by cmelchior** [comment]
This code has been moved to https://github.com/realm/realm-android-user-store. Closing
