### ISSUE TITLE
[Sync] Crashes in the error handler is swallowed by JNI

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#3559]
If the SyncClients error handler is called, it will call back to Java, but if there is an exception in the Java code for whatever reason, that error gets completely swallowed. We need to fix that somehow, so some error information surface somewhere.

**Comment by beeender** [comment]
What do you mean swallowed? if there is a java exception in the error handler, it will be thrown i think? How to reproduce this?

**Comment by cmelchior** [comment]
It is the same scenario as the RealmLog, e.g:

```
SyncManager.setDefaultSessionErrorHandler(new SyncSession.ErrorHandler() {
        @Override
        public void onError(SyncSession session, ObjectServerError error) {
          throw new RuntimeException("BOOM"); // This should result in a JVM Exception. Right now it gets swallowed by JNI (or it did some weeks back).
        }
});
```

**Comment by cmelchior** [comment]
Looks like we already had an issue for it @beeender :facepalm:

**Comment by kneth** [comment]
I am not sure that we should do anything. I mean, you shouldn't throw an exception in a callback/error handler. If any operation in your error handler could lead to an exception, it is better to do a `try`/`catch` within the error handler.

**Comment by kneth** [comment]
#4028 has been merged - closing.
