### ISSUE TITLE
Migrating fields crashes

### ISSUE THREAD

**Issue by crysan** [realm/realm-java#3560]
Bug: Realm Migrations
Goal: Successful Migration to be done
Expected Result: To get migration done successful
Actual Result: Migration crash
Realm version(s): 0.87.5
Android Studio version: 2.2
Android minSdkVersion: 15

Code:

```
 RealmSchema schema = realm.getSchema();
......
if (oldVersion == 16) {
   schema.get("News").addField("hide_news", boolean.class, FieldAttribute.REQUIRED);
   schema.get("News").removeIndex("date_create_long");
   schema.get("News").removePrimaryKey();
   schema.get("News").removeField("date_create_long");
    schema.get("News").addField("news_url_base", String.class, FieldAttribute.PRIMARY_KEY);

    oldVersion++;
}
```

```
myConfig = new RealmConfiguration.Builder(new File(func.getFolder("db")))
   .name(getResources().getString(R.string.app_name_db) + ".realm")
   .schemaVersion(17)
   .migration(Constants.migration)
   .build();
Realm.setDefaultConfiguration(myConfig);
```

Last Model:

```
@RealmClass
public class News extends RealmObject {
    @PrimaryKey
    private Long date_create_long = new Date(System.currentTimeMillis()).getTime();  
    private Date date_create = new Date(System.currentTimeMillis());  

    private Authors author;               
    private Books book;                    

    private String value_old;
    private String value_new;

    private Boolean author_new_fio;
    private Boolean author_new_photo;
    private Boolean author_new_about;
    private Boolean author_new_address;
    private Boolean author_new_date_of_birth;
    private Boolean author_new_residence;

    private Boolean book_upd = false;
    private Boolean book_new = false;
    @Required
    private Boolean author_err = false;
    @Required
    private Boolean book_err = false;
    @Required
    private Boolean book_err_true = false;
    .....
    setters and getters
}
```

New Model:

```
@RealmClass
public class News extends RealmObject {
    @PrimaryKey
    private String news_url_base;

    private Date date_create = new Date(System.currentTimeMillis()); 

    private Authors author;
    private Books book;

    private String value_old;
    private String value_new;

    private Boolean author_new_fio;
    private Boolean author_new_photo;
    private Boolean author_new_about;
    private Boolean author_new_address;
    private Boolean author_new_date_of_birth;
    private Boolean author_new_residence;


    private Boolean book_upd = false;
    private Boolean book_new = false;
    @Required
    private Boolean author_err = false;
    @Required
    private Boolean book_err = false;
    @Required
    private Boolean book_err_true = false;
    @Required
    private Boolean hide_news = false;

    .....
    setters and getters
}
```

The result of running the program:
`Application terminated.`

And the worst thing - there are no more messages.
What do you recommend?

**Comment by Zhuinden** [comment]
If you already had data in your Realm, then I'd assume your new `@PrimaryKey` field should have data filled which doesn't violate the primary key unique constraint.

This is a wild guess, though.

**Comment by crysan** [comment]
New `@PrimaryKey` it does not contain data because migration fails.

**Comment by Zhuinden** [comment]
I also think the problem could be that primary key is not nullable. So if your new primary key value is null, then it won't work.

**Comment by crysan** [comment]
New primary key is String.class. I can not add any data because it does not pass the migration.
And why the system does not display any error and immediately closes the program?

**Comment by Zhuinden** [comment]
You would need to add the new data inside the migration, possibly using `.transform()` if you have anything relevant to that.

**Comment by crysan** [comment]
example please

**Comment by Zhuinden** [comment]
There is an example here

https://github.com/realm/realm-java/issues/3068

**Comment by crysan** [comment]
Edit:
```
                schema.get("News").addField("news_url_base", String.class, FieldAttribute.PRIMARY_KEY)
                        .transform(new RealmObjectSchema.Function() {
                            @Override
                            public void apply(DynamicRealmObject obj) {
                                obj.setString("news_url_base", "lala");
                            }
                });
```
Application terminated

**Comment by Zhuinden** [comment]
You're still violating the primary key constraint. If you already have data in your database, then you must not have the same values on two objects, because you'll have two objects with the same primary key, and that violates the constraint.

You might want to consider just clearing the Realm with `deleteIfMigrationNeeded()` instead, or just keep the date and add the new `baseUrl` field and put `@Index` on that one.

**Comment by crysan** [comment]
Thanks for the answer!
Table News completely empty.
`.deleteRealmIfMigrationNeeded()` Lead to complete data loss.
It is necessary that the data from other tables saved

**Comment by Zhuinden** [comment]
In that case, I'd recommend keeping your current primary key, and just add a new field with `@Index`. If you do `findFirst()` with that and modify that object if it's not null, then you can update via its `Date` primary key as it is.

**Comment by crysan** [comment]
This is a possible solution.  But then we lose the ability to `copyToRealmOrUpdate()`

**Comment by Zhuinden** [comment]
Technically I deleted my answer (you wouldn't lose the ability because the date you save is `@PrimaryKey`, so you can still query based on the URL, and use that object with its already defined date-based primary key, so `update` works) because if News is empty, then it **shouldn't** crash.

``` java
if (oldVersion == 16) {
   schema.get("News").addField("hide_news", boolean.class, FieldAttribute.REQUIRED)
       .removeField("date_create_long");
       .addField("news_url_base", String.class, FieldAttribute.PRIMARY_KEY);
    oldVersion++;
}
```

Can you please check if this code works?

**Comment by Zhuinden** [comment]
Actually I think I found your problem. You use `Boolean` for booleans, even though they're `@Required`, and you added field `boolean.class` instead of `Boolean.class`.

Maybe that would have fixed it.

**Comment by crysan** [comment]
`Boolean.class`
Sorry. Application terminated.

**Comment by Zhuinden** [comment]
...I guess in this case, we should figure out if the culprit is `.addField("hide_news", Boolean.class, FieldAttribute.REQUIRED)` or `.removeField("date_create_long").addField("news_url_base", String.class, FieldAttribute.PRIMARY_KEY);`.

But I'm running out of ideas, unfortunately. :disappointed: 

Worst case scenario, you can send the project over to the Realm people at help[at]realm.io , or consider updating Realm version to 1.1.1 or 1.2.0 (I'd avoid 2.0.x for now) ~ but it's worth noting that 0.89.0 had some really major changes in behavior.

**Comment by zaki50** [comment]
@crysan No messages on logcat, right?

**Comment by crysan** [comment]
zaki50 Yes

**Comment by crysan** [comment]
But what if you just drop the table and recreate it be what you need?
```
            if (oldVersion == 16) {
                schema.remove("News");
                schema.create("News")
                        .addField("news_url_base", String.class, FieldAttribute.PRIMARY_KEY)
                        .addField("date_create", Date.class, FieldAttribute.REQUIRED)
                        .addField("author", Authors.class)
                        .addField("book", Books.class)
                        .addField("value_old", String.class)
                        .addField("value_new", String.class)
                        .addField("author_new_fio", Boolean.class)
                        .addField("author_new_photo", Boolean.class)
                        .addField("author_new_about", Boolean.class)
                        .addField("author_new_address", Boolean.class)
                        .addField("author_new_date_of_birth", Boolean.class)
                        .addField("author_new_residence", Boolean.class)
                        .addField("book_upd", Boolean.class, FieldAttribute.REQUIRED)
                        .addField("book_new", Boolean.class, FieldAttribute.REQUIRED)
                        .addField("author_err", Boolean.class, FieldAttribute.REQUIRED)
                        .addField("book_err", Boolean.class, FieldAttribute.REQUIRED)
                        .addField("book_err_true", Boolean.class, FieldAttribute.REQUIRED)
                        .addField("hide_news", Boolean.class, FieldAttribute.REQUIRED);
                oldVersion++;
            }
```
Result: `Application terminated.`

**Comment by crysan** [comment]
And the saddest thing.  Remove all migration to the original value.  Returned class News to the original value.  Launched.
Result: `Application terminated.`

**Comment by crysan** [comment]
I solved a problem since. Table News empty and let them be.
Сreated News2:
```
            if (oldVersion == 16) {
                try {
                    schema.create("News2")
                            .addField("news_url_base", String.class, FieldAttribute.PRIMARY_KEY)
                            .addField("date_create", Date.class)
                            .addRealmObjectField("author", schema.get("Authors"))
                            .addRealmObjectField("book", schema.get("Books"))
                            .addField("value_old", String.class)
                            .addField("value_new", String.class)
                            .addField("author_new_fio", Boolean.class)
                            .addField("author_new_photo", Boolean.class)
                            .addField("author_new_about", Boolean.class)
                            .addField("author_new_address", Boolean.class)
                            .addField("author_new_date_of_birth", Boolean.class)
                            .addField("author_new_residence", Boolean.class)
                            .addField("book_upd", Boolean.class, FieldAttribute.REQUIRED)
                            .addField("book_new", Boolean.class, FieldAttribute.REQUIRED)
                            .addField("author_err", Boolean.class, FieldAttribute.REQUIRED)
                            .addField("book_err", Boolean.class, FieldAttribute.REQUIRED)
                            .addField("book_err_true", Boolean.class, FieldAttribute.REQUIRED)
                            .addField("hide_news", Boolean.class);
                } catch (Exception e) {
                    e.printStackTrace();
                }

                oldVersion++;
            }
```
And then with her work.

But much pity that no error messages in the last migration.

**Comment by kneth** [comment]
@crysan I am happy that you have found a solution. It sounds that we should add a couple of extra tests on our migration code to discover uncovered corner cases. I'll relabel the issue so we don't forget to do so ;-)

**Comment by Zhuinden** [comment]
@kneth well it **was** a question for 0.87.5, so who knows if this has been fixed since.

**Comment by crysan** [comment]
Version realm 0.88.0; 0.88.1; 0.88.2; 0.88.3; 0.89.0; 0.89.1; also does not solve the problem.
Above version can not test, do not give your application code.

**Comment by bmunkholm** [comment]
Related to very old versions. Closing.
