### ISSUE TITLE
Property names that are forbidden in other languages

### ISSUE THREAD

**Issue by stel** [realm/realm-java#3562]
In Obj-C and Swift it's not possible to have a property with name e.g. `description` (and other `NSObject`'s accessors), while some users may have it in Java and other bindings. The reverse is also possible.

It should be reflected in Docs, or if it's possible, object store could output some debug logs in this case.

Some related issues: https://github.com/realm/realm-browser-osx/issues/198, https://github.com/realm/realm-cocoa/issues/2553

/cc @bmunkholm, @tgoyne, @jpsim

**Comment by cmelchior** [comment]
Ideally we should just have a blacklist of names in the Object Store I think

**Comment by zaki50** [comment]
I think it's better for each SDK to provide a mapping feature between variable name and column name.

**Comment by Zhuinden** [comment]
@zaki50 I agree, it's a bit messy to say "you can't name your field `description`", I think even one of my RealmObjects has a field called `description` because it's such a generic thing.

**Comment by cmelchior** [comment]
Yup, we probably need a mapping feature in any case, which would make this problem go away. One other option could also be to have a switch in the `realm` closure.

```
realm {
  enforceCrossPlatformNaming = false
}
```

That way, people that don't use Realm on more than 1 platform could opt out of this restriction.

**Comment by cbush** [comment]
We are revamping the Realm docs. We're not ignoring this issue -- we've read through every one of them, and we'll be sure to address this as part of our updates. We're closing the GitHub issues and creating new JIRA tickets to track the work at a high level.
