### ISSUE TITLE
NativeObjectReference and refIndex memory leak

### ISSUE THREAD

**Issue by gvoltr** [realm/realm-java#3576]
Hello, recently I started migrating my app to realm database and have issue with memory leak.
#### Expected Results

In DB I have table with Contacts - about 1k records.
I have fragment that display contacts, in fragment onCreate I create realm instance

`realm = Realm.getDefaultInstance()`

After that I load all records as observable and store subscription

`contactsSubscription = realm.where(RealmContact::class.java)
                ?.findAllAsync()
                ?.asObservable()
                ?.subscribe(...)
`

At `onDestroy()` I unsubscribe from contactsSubscription and call `realm.close()`

I expecting that realm will clear all currently taking memory.

#### Actual Results

After few times I opened/closed this fragment I noticed that heap growing.
One thing that continue taking memory is `refIndex in io.realm.internal.NativeObjectReference`
The second is `queueNext in io.realm.internal.NativeObjectReference
`

Maybe I clear/unsubscribe in some wrong way?

#### Version of Realm and tooling
Realm version(s): 2.0.1

Android Studio version: 2.2

Which Android version and device: AVD api level 19

**Comment by gvoltr** [comment]
I think this issue is close to https://stackoverflow.com/questions/39758862/possible-realm-memory-leak-in-android-when-creating-observable-from-where-clause

Test project is here https://github.com/willjgriff/android-realm-leak/tree/master/RealmLeakTest/app/src/main/java/com/github/willjgriff/realmleaktest

**Comment by cmelchior** [comment]
Hi @gvoltr It might also be related to this one #3552 
I'm looking into it right now

**Comment by Zhuinden** [comment]
The questions for me is

1.) is it verified that `onDestroy()` was called (why isn't this in `onDestroyView()...? that is more reliable)

-------

2.) is this native object reference retained because of the `RealmObservableFactory`, or because of the internal context?

**Comment by gvoltr** [comment]
1) Move unsubscribe and clean to onDestroyView() - done.

2) `RealmResults` retained because of the `RealmObservableFactory` 

Can't attach heap dump so here is dropbox link, maybe it might help

https://www.dropbox.com/s/h7e06n75g7wtta2/realm_leak_test.hprof?dl=0

**Comment by gvoltr** [comment]
I forked the repo from issue #3552 and make some updates that describe my situation. Here is the project - https://github.com/gvoltr/android-realm-leak

As for me, when I subscribe like 

```
	subscription = realm.where(Person.class)
			.findAllAsync()
			.asObservable()
				.subscribe(new Action1<RealmResults<Person>>() {
					@Override
					public void call(RealmResults<Person> persons) {
						Log.d("RXREALM", "OnNext called " + persons.size());
					}
				});
```

everything works ok.

But if I convert `RealmResult` to something another, for example 

```
subscription = realm.where(Person.class)
			.findAllAsync()
			.asObservable()
				.map(new Func1<RealmResults<Person>, ArrayList<String>>() {
					@Override
					public ArrayList<String> call(RealmResults<Person> persons) {
						ArrayList<String> emails = new ArrayList<>();
						for (Person person : persons){
							emails.add(person.getEmail());
						}
						return emails;
					}
				})
			.subscribe(new Action1<ArrayList<String>>() {
				@Override
				public void call(ArrayList<String> emails) {
					Log.d("RXREALM", "OnNext called " + emails.size());
				}
			});
```
then `NativeObjectReference` count from realm start growing.

**Comment by cmelchior** [comment]
Hi @gvoltr 

Thanks for the project. The increase you see in NativeObjectReference objects is as expected. Realm lazyloads all data, which means that when you iterate a RealmResult, you will actually allocate the object when it is accessed.

However, they are also removed again when the GC kicks in, and I didn't see an evidence of a long term leak. Note that these objects are really small, so it will be natural that there might be many of them before the GC decides to remove them.

**Comment by gvoltr** [comment]
Hi @cmelchior 

Thank you for the answer, now I understand how it works better.

But still I feel like I have problem in my main project, in heap dump that I posted above using MAT analyser I have next: 

> 225 instances of "io.realm.internal.Context", loaded by "dalvik.system.PathClassLoader @ 0xa50053f0" occupy 25,581,432 (73.79%) bytes.

Details is something like - 

```
java.lang.Thread @ 0xa4d2abd8 main Thread

    localValues java.lang.ThreadLocal$Values @ 0xa4d9d570

        table java.lang.Object[128] @ 0xa77c1ae8

              io.realm.rx.RealmObservableFactory$StrongReferenceCounter @ 0xa75d2f28

                   io.realm.RealmResults @ 0xa61684b0
                   ... 244 more RealmResults
``` 
The problem is I miss realm closing or unsubscribe somewhere in my app?

**Comment by Zhuinden** [comment]
> The problem is I missing realm closing or unsubscribe somewhere in my app?

yes

**Comment by cmelchior** [comment]
Hi @gvoltr 
I browsed through your memory dump a bit. The number of `Context` matches the number of `RealmResults` which is as expected. However, you have 225 RealmResults in memory and 3000+ objects, which is quite a lot. So either you are not unsubscribing correctly or another guess is that you are flat mapping some stream in a way the generate a huge number of RealmResults.

**Comment by gvoltr** [comment]
Ok, thank you for response @cmelchior !

**Comment by Zhuinden** [comment]
@cmelchior well, he *does* use `map()` for each element in the `RealmResults` which would result in creating a proxy for each element, which each has its own native object reference, which will each only disappear when the finalizers run
