### ISSUE TITLE
Is `kotlin-reflect` _really_ required?

### ISSUE THREAD

**Issue by joshfriend** [realm/realm-java#3580]
#### Goal

I would like to remove 11k methods from my dex count when using Realm in a Kotlin Android application.

#### Expected Results

Documentation should not require me to add `kotlin-reflect` as a dependency.

#### Actual Results

[Documentation states that `kotlin-reflect` is required](https://realm.io/docs/java/latest/#kotlin):

> Many of Realm APIs reference Java classes, and for that reason you must include `org.jetbrains.kotlin:kotlin-reflect:${kotlin_version}` as a compile dependency.

I believe this is false because the ability to get a java `Class<T>` from a Kotlin `KClass<T>` is [present in the Kotlin stdlib](https://kotlinlang.org/api/latest/jvm/stdlib/kotlin.jvm/java.html).

I've removed `kotlin-reflect` from my dependencies, ran a clean build, and the application still seemed to function normally.

**Comment by MGaetan89** [comment]
I have been using Realm in my Kotlin application for a couple of months without the `kotlin-reflect` dependency, and it is working as expected.

**Comment by cmelchior** [comment]
Website and example updated.

**Comment by joshfriend** [comment]
Awesome, thank you for confirming!
