### ISSUE TITLE
Is it possible add a chain method for copy Realm for RealmQuery?

### ISSUE THREAD

**Issue by zeroarst** [realm/realm-java#3582]
Typical one:
```
Person p = realm.copyFromRealm(realm.where(Person.class).equalTo(PersonFields.Name, "roy").findFirst())
List<Person> lst = realm.copyFromRealm(realm.where(Person.class).equalTo(PersonFields.Name, "roy").findAll())
```
Will be good if we have this !!
```
Person p = realm.where(Person.class).equalTo(PersonFields.Name, "roy").findFirst().copyFromRealm()
List<Person> lst = realm.where(Person.class).equalTo(PersonFields.Name, "roy").findAll().copyFromRealm()
```

**Comment by cmelchior** [comment]
Thanks for the suggestion. I can see why that might be useful. It might also be easier to use than going through a Realm object as we do currently. That said there is a nice symmetry between `realm.copyToRealm()` and `realm.copyFromRealm()` right now.

I am not sure we would want to have these methods in two places though as that just seems unnecessary.

Thoughts @realm/java ?

**Comment by zaki50** [comment]
I'm against adding those.

One big reason is that those are only for **typed** Realm.
We couldn't provide proper implementation for `DynamicRealm`.

**Comment by cmelchior** [comment]
Hmm, very good point.

**Comment by kneth** [comment]
Adding `copyFromRealm()` to all Realm object will increase app's method count. And I believe that having multiple ways to do the same thing isn't the best metric for a good API.

**Comment by cmelchior** [comment]
Ok, in that case, the downsides of doing this seems to outweigh the upsides. So we will keep `copyFromRealm` where it is.
