### ISSUE TITLE
Guidance in documentation on List vs LinkingObjects

### ISSUE THREAD

**Issue by michaelblight** [realm/realm-java#3584]
Oops, just realised I put this in realm-java, and although it applies to all, I am using Swift...

Realm provides two options for 1-to-many relationships - one where the parent has a reference to children (List<Object>) and one where the child has a reference to the parent (eg. myParent: Parent?). In the latter case, LinkingObjects can be used in the parent to easily get a reference to the children. It would be helpful if the documentation included some guidance on when to use each solution, or at least some pros and cons. (The documentation does warn about the pitfalls of using both together, which is good).

I have been using the second option because it seems more "proper", as it enforces each child to have only one parent (not trying to solve many-to-many here). However, most of the examples I've seen use List. My preference fell into a screaming heap when I wanted to serialize to JSON, for two reasons. Firstly, the LinkingObjects variable is unknown to the Realm schema, so I had to resort to using Mirror, which is unpleasant, but not a show-stopper. However, the second is that I could find no way to enumerate LinkingObjects generically. List has ListBase that provides access to the unerlying items, whereas LinkingObjectsBase does not. Or am I missing something? Nevertheless, it looks like the only situation where Realm provides two ways to achieve the same outcome, so further discussion in the documentation would be helpful. Excellent product by the way - Core Data always caused me grief.

**Comment by cmelchior** [comment]
Realm Java doesn't support LinkingObjects yet, although we have an issue for adding it. We will keep this in mind when documenting it. For now, I'll move this issue to the Realm-Cocoa repo: https://github.com/realm/realm-cocoa/issues/4193
