### ISSUE TITLE
nativeADvanceRead throwing a Wrong transactional state error.

### ISSUE THREAD

**Issue by bhargavms** [realm/realm-java#3585]
#### Goal

Understand what is causing this exception.

#### Expected Results

Fix the piece of code that causes this exception.

#### Actual Results

> Fatal Exception: io.realm.exceptions.RealmError: Unrecoverable error. Wrong transactional state (no active transaction, wrong type of transaction, or transaction already in progress) in io_realm_internal_SharedGroup.cpp line 157
>        at io.realm.internal.SharedGroup.nativeAdvanceRead(SourceFile)
>        at io.realm.internal.SharedGroup.advanceRead(SourceFile:137)
>        at io.realm.internal.ImplicitTransaction.advanceRead(SourceFile:35)
>        at io.realm.internal.SharedGroupManager.advanceRead(SourceFile:76)
>        at io.realm.HandlerController.realmChanged(SourceFile:445)
>        at io.realm.HandlerController.handleMessage(SourceFile:118)
>        at android.os.Handler.dispatchMessage(Handler.java:98)
>        at android.os.Looper.loop(Looper.java:148)
>        at android.os.HandlerThread.run(HandlerThread.java:61)

#### Steps & Code to Reproduce

This is a crashlytics crash report capture, has so far happened only once, so I don't know what could be causing this.

#### Version of Realm and tooling
Realm version(s): 1.2.0

Android Studio version: 2.2

Which Android version and device: Motorola XT1068 android OS version 6.0

**Comment by Zhuinden** [comment]
It sounds like (wild guess!) there was an active transaction on the UI thread when Realm wanted to update the results, although that sounds rather odd.

Do you do `realm.executeTransaction()` or `realm.beginTransaction()` on the UI thread anywhere?

**Comment by bhargavms** [comment]
I use beginTransaction() followed by commitTransaction(), whenever I updated/delete/add realmobjects

**Comment by kneth** [comment]
If you use `realm.executeTransaction()`, you don't have to worry about committing or canceling your transactions. Did you write a change listener yourself?

**Comment by bhargavms** [comment]
yes I have written a wrapper class, and a change listener which is called whenever the add/remove items to the realm

**Comment by Zhuinden** [comment]
Well on exceptions I can imagine things getting stuck (because you would not commit - you would have to `cancel`) and so `executeTransaction()` is recommended over `begin/commit()`, unless you add the catch clause yourself

**Comment by kneth** [comment]
@bhargavms Did your wrapper class (and upgrade) solve your issue?

**Comment by bhargavms** [comment]
@kneth Currently I haven't gotten this issue again, the apk I have just published now, will have to wait and see

**Comment by kneth** [comment]
@bhargavms Great to hear. I'll leave the issue open for a bit longer. Feel free to update if you see anything.

**Comment by kneth** [comment]
Let me close the issue. Just reopen if you have any updates.
