### ISSUE TITLE
SyncSession#notifySessionError() seems to be unused

### ISSUE THREAD

**Issue by zaki50** [realm/realm-java#3597]
The comment for `SyncSession#notifySessionError()` says that it is called from `Session.cpp`, but I couldn't find `Session.cpp`.
There is a file `io_realm_internal_objectserver_SyncSession.cpp`, but it doesn't call the method.

If it's not needed, we should remove it.
If it should be called from JNI, we should fix it.

**Comment by cmelchior** [comment]
It was supposed to be called from `JniSession` (objectserver_shared.cpp), but right now the error handler there logs the message instead of forwarding it to the error handler. This is a mistake and should be fixed.
