### ISSUE TITLE
Request Feature(realm.take(10).skip(10))

### ISSUE THREAD

**Issue by ouyangzn** [realm/realm-java#3599]
Hi everybody!
I have a problem, if my dadabase have many data, such as 200000+.
Than i want 20 of them, but there is only `findAll()` i can use.
It spent about 3s to find all, but i just want 20, it take me a lot of time. 
So, i need another way to find the 20 datas.

**Comment by cmelchior** [comment]
Hi @ouyangzn Thanks for the feature request. We already have an issue tracking this here: #544, so I will close this as an duplicate.

**Comment by Zhuinden** [comment]
Yep, I even mentioned it as design here: https://github.com/realm/realm-java/issues/544#issuecomment-248122396

I think the issue about it is the support for evaluating the `minDate()` and other aggregate operators for a sublist of the result set. This is a wild guess though, I'm still not a Realm person

**Comment by Zhuinden** [comment]
....wait a second

> It spent about 3s to find all, but i just want 20, it take me a lot of time. 

That can't be right, `findAll()` should return itself immediately.

**Comment by cmelchior** [comment]
No, for the synchronous `findAll()` it will block until the query is fully evaluated. For an immediate return you should use `findAllAsync()`.

**Comment by Zhuinden** [comment]
@cmelchior ohhh... makes sense. The RealmResults itself needs to be set up, and the evaluation is lazy after that.
