### ISSUE TITLE
Documentation for 1.2.0 is NOT valid!

### ISSUE THREAD

**Issue by janswist** [realm/realm-java#3603]
I have legacy app that I don't want migrate to 2.0.1 so I checked documenation and the outdated 1.2.0 is the same as 2.0.1. For starters, there is `Realm.init(context)` which is a new method (and it's not available on 1.2.0). It's really discouraging to be forced to use new version - I have no time now to migrate and handle new immutable primaryKey stuff.

**Comment by cmelchior** [comment]
Hmm, yes. That is definitely a mistake. Those changes should only be visible in the 2.0 documentation. We will fix that. Sorry for the trouble.

**Comment by cmelchior** [comment]
Fixed
