### ISSUE TITLE
Delete corrupt database and perform a fresh setup

### ISSUE THREAD

**Issue by XabierGoros** [realm/realm-java#3604]
Imagine for some reason we lose our encrypted database key ([see Android KeyStore issue](https://doridori.github.io/android-security-the-forgetful-keystore/)) and as a fallback we want to send the user to our app's registration process. There, the app workflow will be restarted and our Realm database would have to be deleted and set up again.

As we're not able to delete Realm using `deleteAll()` API method (lost key), we could remove Realm database file from the file system getting it's path previously.

Once I send the app to the registration process, I set up the new database with it's new configuration:

```
realmConfiguration =
                    new RealmConfiguration.Builder()
                            .encryptionKey(newEncryptionKey)
                            .directory(realmFile)
                            .deleteRealmIfMigrationNeeded()
                            .build();
```

In this step I get two behaviors:

1. If the database key is matches the previous one, I get a "_class_xxxxxx has no primary key defined_" error.
2. Instead, if the database key is different and fresh one, I get the "_Wrong key used to decrypt Realm._" error.

How could I solve this problem?

**Comment by zaki50** [comment]
Please use `Realm.deleteRealm()` instead of `Realm.deleteAll()`

**Comment by XabierGoros** [comment]
I cannot test it right now, but would it work since `Realm.deleteRealm()` needs a [configuration](https://github.com/realm/realm-java/blob/master/realm/realm-library/src/main/java/io/realm/Realm.java#L1544) as a parameter? The previous configuration cannot be recreated because of the lost key. If we create a new configuration and call that method will erase all Realm to start over?

Thanks for your reply

**Comment by kneth** [comment]
@XabierGoros I don't think we have ever considered this case - thanks for bringing it up :-)

Currently solution is either to manually delete the Realm file or use a different name.

Long term solution is that we add a `deleteRealmIfWrongEncryptionKey()` option to `RealmConfiguration`.

**Comment by XabierGoros** [comment]
@kneth the only way I could get rid of this is to use another database name. I tried to delete manually the Realm file but since the current configuration is corrupted with the lost key it is not possible to call deleteRealm:
- `deleteRealm(config)` 

> It's not allowed to delete the file associated with an open Realm. Remember to close() all the instances of the Realm before deleting its file: /data/data/com.xxxx.yyy/files/database/dbName.realm/default.realm) 

Obviously it is not possible to call the `close()` method since it requires `Realm.getDefaultInstance()` which fails. And without calling it in the initial re-setup it fails in the first `Realm.getDefaultInstance()`

> java.lang.IllegalStateException: class_MyTable has no primary key defined

However, if I kill the app after that state and start it over, it works fine in both cases. It seems Realm retains some memory state that doesn't allow me to perform that setup again. Is there any way to reset that state without killing the app?

**Comment by Zhuinden** [comment]
@XabierGoros it's not impossible to replicate the behavior of `Realm.deleteRealm(Configuration)` from the source code even without the path.

This code is for 1.1.1, so I don't know if anything changed for it in Realm 2.0.x.

``` java
    /**
     * Deletes the Realm file defined by the given configuration.
     */
    static boolean deleteRealm(final RealmConfiguration configuration) {
        final String management = ".management";
        final AtomicBoolean realmDeleted = new AtomicBoolean(true);

        RealmCache.invokeWithGlobalRefCount(configuration, new RealmCache.Callback() {
            @Override
            public void onResult(int count) {
                if (count != 0) {
                    throw new IllegalStateException("It's not allowed to delete the file associated with an open Realm. " +
                            "Remember to close() all the instances of the Realm before deleting its file: " + configuration.getPath());
                }

                String canonicalPath = configuration.getPath();
                File realmFolder = configuration.getRealmFolder();
                String realmFileName = configuration.getRealmFileName();
                File managementFolder = new File(realmFolder, realmFileName + management);

                // delete files in management folder and the folder
                // there is no subfolders in the management folder
                File[] files = managementFolder.listFiles();
                if (files != null) {
                    for (File file : files) {
                        realmDeleted.set(realmDeleted.get() && file.delete());
                    }
                }
                realmDeleted.set(realmDeleted.get() && managementFolder.delete());

                // delete specific files in root folder
                realmDeleted.set(realmDeleted.get() && deletes(canonicalPath, realmFolder, realmFileName));
            }
        });

        return realmDeleted.get();
    }
```

So it says you can delete the `blah.realm` file, and its "management folder", apparently.

**Comment by XabierGoros** [comment]
@Zhuinden I'm basically storing all Realm data in a custom folder, and erasing the whole folder which should be similar to the code above except it is performed by `RealmCache` (not accessible outside):

   ```
File realmFile = new File(mContext.getFilesDir() + "/database", "myDbName.realm");
if (realmFile != null) {
    deleteRecursive(realmFile.getParentFile());
}
..
private void deleteRecursive(File fileOrDirectory) {
    if (fileOrDirectory.isDirectory())
        for (File child : fileOrDirectory.listFiles())
            deleteRecursive(child);
     fileOrDirectory.delete();
}
```

**Comment by kneth** [comment]
@XabierGoros The snippet above is what I meant by "manually delete Realm" :-)

**Comment by XabierGoros** [comment]
@kneth you mean my snippet or the one of @Zhuinden? If it's mine, you said the manual deletion would work and it unfortunately doesn't, after deleting the Realm file I configure again the database and when I use it I get the following error mentioned before:

> java.lang.IllegalStateException: class_MyTable has no primary key defined

If you meant the other snippet, we are not able to use `RealmCache` as you know. Am I missing something?

**Comment by Zhuinden** [comment]
@XabierGoros use the snippet without the RealmCache, of course. Just delete the right files.

**Comment by kneth** [comment]
@XabierGoros Remember to delete both the Realm file, the files in `management` and the `management` folder.

**Comment by XabierGoros** [comment]
I'd like to give some of my thoughts and updates about my issue:

1. If I remove the /database folder which contains all realm related files, once I perform my database setup (init and create config) no files are created in the file structure. After doing `Realm.getInstance(myConfiguration)`, it creates an empty realm file. Doing a read operation it throws an `java.lang.IllegalStateException` exception complaining about an unexisting class which is logic due to the empty database. However, on a write file it throwed another `java.lang.IllegalStateException` exception saying "_A RealmObject with no *@PrimaryKey* cannot be updated_".
2. On the other hand, if I remove the /database folder and kill the app, run again, none of the above errors occurs and everything goes fine.

After investigating deeper, it turns out that that some of my Realm instances were not fully closed and those caused that misbehavior. I had to close those instances in their particular threads and it worked fine. I guess there's no other choice to force the closing of all the instances in a single point if we want to erase our database, am I right?

**Comment by cmelchior** [comment]
No, you need to close the Realm in all threads being used.
You can use `Realm.getGlobalInstanceCount(config)` to check if you still have any instances open though.
