### ISSUE TITLE
RealmResults<T> - greaterThan is not working properly

### ISSUE THREAD

**Issue by janswist** [realm/realm-java#3606]
I'm using Realm `1.2.0` and I found that one of my tables (with contacts) is not entirely propagated - some of contacts are missing while previewing with `Stetho`, but still accessible while querying for all contacts. But - if I use `greaterThan()` with `java.util.Date` then it doesn't work. It does not return contacts that are edited after specified date. Even though that it works on other table - this one just don't do this (or works from time to time).

**Comment by zaki50** [comment]
Could you provide a small code that reproduce this issue?

**Comment by janswist** [comment]
Here You are: https://gist.github.com/janswist/e855b08a8c030ce2d9033b5fabccda7a

**Comment by janswist** [comment]
I just added contact query when user starts app for the first time in case that might be the case.

**Comment by Zhuinden** [comment]
I would assume this question has to do with milisecond precision somehow. I set hour, minute, second and milisecond to 0 lately.

**Comment by janswist** [comment]
Database excerpt from Stetho:
![image](https://cloud.githubusercontent.com/assets/5583954/19250409/6a9aaae4-8f3a-11e6-981e-89357b73d210.png)

**Comment by janswist** [comment]
I just found that if I wait a minute or two it suddenly finds these contacts that were updated. `System.currentTimeInMillis()` and `Calendar.getInstance().getTime()` are saving proper values. Still searching.

**Comment by cmelchior** [comment]
@janswist This sounds mostly like you are querying the data from a thread that hasn't been updated yet.

Realm data is thread confined so each thread gets a consistent view of the data, but this also means that two threads might see the different "versions".

Realm will automatically update Looper threads. Just register a change listener to be notified when this happens, but background threads are not automatically updated. You need to either re-open the Realm or call `waitForChange` for that to happen.

**Comment by janswist** [comment]
@cmelchior Updated is from completely different class where I do this:
`RealmResults<CallLog> res = Realm.getDefaultInstance()
                .where(CallLog.class)
                .equalTo(Constants.EXTRA_CALL_LOG_PRIVATE, false)
                .equalTo(Constants.EXTRA_CALL_LOG_DEFAULT_SYNC, true)
                .greaterThan(Constants.EXTRA_CALL_LOG_DATE_EDIT, Utils.getUTCToDate(lastSuccessfulSync))
                .findAll();`

So the question is if `Realm.getDefaultInstance()` is sufficent to be a new thread?

**Comment by janswist** [comment]
Ok, for now it seems to be working when I wrapped it like this:
`Realm realm = Realm.getDefaultInstance();
        realm.beginTransaction();
        RealmResults<Contact> contactResults = realm
                .where(Contact.class)
                .equalTo(Constants.EXTRA_CONTACT_PRIVATE, false)
                .greaterThanOrEqualTo(Constants.EXTRA_CONTACT_DATE_EDIT, Utils.getUTCToDate(lastSuccessfulSync))
                .findAll();
        realm.commitTransaction();`
which I think shouldn't be the case. Why is that?

**Comment by Zhuinden** [comment]
Transactions see the latest version of the data at all times. Background threads are otherwise confined to the version that existed when it was opened.

**Comment by janswist** [comment]
@Zhuinden so RealmQuery is asynchronous by default? I thought otherwise...

**Comment by Zhuinden** [comment]
...huh? I never said that. Realm instances are thread confined, and they see the version that existed at the time of opening the Realm, and on looper threads (typically the UI thread), Realm updates the results and objects and the instance on that particular thread.

So the query returns "outdated" results because the Realm instance is outdated.

You can try [this workaround after `Realm.getDefaultInstance()` and see if it helped](http://stackoverflow.com/a/38839808/2413303).

**Comment by janswist** [comment]
@Zhuinden sorry if I misinterpreted Your words. I can't wrap my head around threading in Realm and how it's all related - especially when similar method works fine without transaction wrap. I just found that in [documentation](https://realm.io/docs/java/latest/#threading):

> You can operate on live objects in different threads, reading and writing to them, without worrying about what other threads are doing to those same objects. If you need to change data you can use a transaction. The other objects in the other threads will be updated in near real time (meaning that if they’re currently in the process of doing something the update will happen in the next iteration of the runloop).

So I'm really curious why my code that was nothing but reading data have to be in transaction to be executing as expected.

**Comment by Zhuinden** [comment]
>  (meaning that if they’re currently in the process of doing something the update will happen in the next iteration of the runloop).

That's why. Your background thread has no run-loop. It does not update.

**Comment by janswist** [comment]
Okay, I get that part. Still, though, there's one thing: after I edit contact as soon as I go back to the list I can see contact updated instantly. So, it seems to me that database is already updated. And then when I do synchronization it shows no recently edited objects and that's why I'm getting really confused about that.

**Comment by Zhuinden** [comment]
Well it's your synchronization that happens on a background thread with no looper, no? That's where being frozen on an older version can occur.

Although I'm a bit concerned, do you actually close the Realm instance on your background thread? You should.

**Comment by kneth** [comment]
I believe that https://realm.io/docs/java/latest/#auto-refresh is the relevant section of the documentation.

**Comment by janswist** [comment]
Sorry for late reply - I did my research and it has got not much to do with `auto-refresh`. It's still a mystery to me why instead of `Realm.getDefaultInstance().beginTransaction()` I had to split it up to two pieces so `realm.beginTransaction()` is on the second line. Works now so we can close I think. Thank You.

**Comment by Zhuinden** [comment]
@janswist I guess your Realm instance wasn't closed then, and it should have been.

That makes sense.
