### ISSUE TITLE
Getter for field not found even if it exists.

### ISSUE THREAD

**Issue by princebansal** [realm/realm-java#3607]
#### Goal

>I want to use a class model a Realm Object.

#### Expected Results

> I should be able to run my code and solve the runtime error. It works works for other classes i do in the same way, but doesn't work for FAQ and FAQResult.

#### Actual Results

>  Information:Gradle tasks [:app:assembleDebug]
Error:No getter found for field faqs
Warning:File for type 'io.realm.DefaultRealmModule' created in the last round will not be subject to annotation processing.
Warning:File for type 'io.realm.DefaultRealmModuleMediator' created in the last round will not be subject to annotation processing.
Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.
Information:BUILD FAILED
Information:Total time: 2.06 secs
Information:2 errors
Information:2 warnings
Information:See complete output in console

#### Steps & Code to Reproduce

> Tried @SerializedName and @Expose to solve. No luck. The fields name and function name correct as per the documentation.

#### Code Sample

`   package com.gdgvitvellore.devfest.Entity.Actors;
    
    import io.realm.RealmList;
    import io.realm.RealmObject;
    
    /**
     * @see <a href="https://github.com/GDGVIT/devfest-portal/wiki">API Reference</a>
     */
    
    public class FAQResult {
        private int status;
        private String message;
        private RealmList<FAQ> faqs;
    
    
        public int getStatus() {
            return status;
        }
    
        public void setStatus(int status) {
            this.status = status;
        }
    
        public String getMessage() {
            return message;
        }
    
        public void setMessage(String message) {
            this.message = message;
        }
    
        public RealmList<FAQ> getFaqs() {
            return faqs;
        }
    
        public void setFaqs(RealmList<FAQ> faqs) {
            this.faqs = faqs;
        }
    }
`
`   package com.gdgvitvellore.devfest.Entity.Actors;
    
    import io.realm.RealmObject;
    
    public class FAQ extends RealmObject{
    
        private String question;
        private String answer;
    
        public String getQuestion() {
            return question;
        }
    
        public void setQuestion(String question) {
            this.question = question;
        }
    
        public String getAnswer() {
            return answer;
        }
    
        public void setAnswer(String answer) {
            this.answer = answer;
        }
    }

`
#### Version of Realm and tooling
Realm version(s): 0.87.5

Android Studio version: 2.2

Which Android version and device: Motorola MotoG3, Android 6.0.1

**Comment by beeender** [comment]
Your class `FAQResult` is not extended from `RealmObject`?

And BTW, `0.87.5` is an very old version. Can you update to the latest version?

**Comment by kneth** [comment]
@princebansal If you experience the issue after an upgrade to latest version, please either reopen or create new issue.
