### ISSUE TITLE
Reduce Realm Transform Log Verbosity

### ISSUE THREAD

**Issue by diegomontoya** [realm/realm-java#3608]
Right now realm transform is taking a long time to process and a small part of that is the amount of print messages causing excess cpu usage on android studio. It is currently printing field/tokens for every single class/field even if they are not actually transformed.  One option is to only print those fields/tokens if they are  transformed. 

```
Behavior: nextToken
      Field being accessed: com.fasterxml.jackson.core.filter.FilteringParserDelegate._exposedContext
      Field being accessed: com.fasterxml.jackson.core.filter.FilteringParserDelegate._currToken
      Field being accessed: com.fasterxml.jackson.core.filter.FilteringParserDelegate._headContext
      Field being accessed: com.fasterxml.jackson.core.filter.FilteringParserDelegate._exposedContext
      Field being accessed: com.fasterxml.jackson.core.filter.FilteringParserDelegate.delegate
      Field being accessed: com.fasterxml.jackson.core.filter.FilteringParserDelegate._currToken
      Field being accessed: com.fasterxml.jackson.core.filter.FilteringParserDelegate._headContext
```
Realm Transform time: 6608 milliseconds

**Comment by beeender** [comment]
This log is using `info` level. What AS version are you using? I think by default this log should not be printed in the AS?

**Comment by diegomontoya** [comment]
Android Studio 2.2.1 (canary)
Gradle 2.14.1
Instant Run: Enabled (instant run extra logging disabled)
Compile Options/Flags: default/none

**Comment by beeender** [comment]
I made a sample project to test. With AS `2.2.0`, the gradle log is just like always (info level log is not printed). But after update AS to `2.2.1` which is in the stable channel now, all the logs start to be printed just like you described. I don't have too many ideas about why AS changed this ... But removing info level logs from Realm side doesn't seem to be a feasible solution?

**Comment by beeender** [comment]
Maybe we should use debug log level instead?

**Comment by cmelchior** [comment]
Yeah, reducing the log level sounds fine with me.
