### ISSUE TITLE
What is Realm Develoment Process?

### ISSUE THREAD

**Issue by inesfproenca** [realm/realm-java#3613]
We are studying Informatics and Computing Engineering at Faculty of Engineering of University of Porto. We are attending a subject called Software Engineering in which we are expected to contribute to an open source project. 
After carefully analysing some github projects, we decided to work on Realm. Therefore, we would like to know more about it.

- For how long has this project been on?
- How many contribuitors work on this project?
- Do you have a main team? How does it work? Are there specific roles? Are there meetings?
- Do you have a main client? Who works with Realm? Who needs it to be improved?
- What kind of Software process model do you work with?

We would be very thankfull if you could answer some of these questions as soon as possible.

**Comment by kneth** [comment]
* For how long has this project been on?

Almost 5 years

* How many contribuitors work on this project?

Realm Java has 6-7 contributors.

* Do you have a main team? How does it work? Are there specific roles? Are there meetings?

Realm Java is one team within the Realm organisation (Realm Inc.), and all members are developers (but also act as release managers, supporters, and testers). So no specific roles. We have regular video conferences and uses closed Slack channels for communication.

* Do you have a main client? 

No

* What kind of Software process model do you work with?

Agile is probably what comes closest to how we work.

**Comment by inesfproenca** [comment]
Thank you
