### ISSUE TITLE
Website typos in "Error Handling" section

### ISSUE THREAD

**Issue by Zhuinden** [realm/realm-java#3615]
In https://realm.io/docs/java/latest/#error-reporting it says

``` java
SyncConfiguration configuration = new SyncConfigurtion.Builder(user, serverURL)
  .errorHandler(new Session.Errorhandler {
    void onError(Session session, ObjectServerError error) {
        // do some error handling
    }
  })
  .build();
```

It should be something like

``` java
SyncConfiguration configuration = new SyncConfiguration.Builder(user, serverURL)
  .errorHandler(new Session.ErrorHandler() {
    void onError(Session session, ObjectServerError error) {
        // do some error handling
    }
  })
  .build();
```

**Comment by Zhuinden** [comment]
Isn't this exactly what was unused in https://github.com/realm/realm-java/issues/3597 ?

**Comment by beeender** [comment]
The implementation of error handler calling procedure is a bit confusing right now. `SyncManager.notifyErrorHandler()` will call the error handler in the configuration as well. And that will be passed as a callback in `io_realm_SyncManager.cpp`. @Zhuinden

**Comment by Zhuinden** [comment]
@beeender I don't see the fix for the typos on the site, does this have some delay of sorts?

**Comment by beeender** [comment]
@Zhuinden Yes! some minutes delay. The website deployment takes some time.
