### ISSUE TITLE
Website links to non-existing link in docs

### ISSUE THREAD

**Issue by Zhuinden** [realm/realm-java#3619]
Section https://realm.io/docs/java/latest/#conflict-resolution says that the Realm Object Server conflict resolution info is at https://realm.io/docs/realm-object-server/conflicts/

But it's actually at https://realm.io/docs/realm-object-server/#conflict-resolution

**Comment by kneth** [comment]
Good catch

**Comment by kneth** [comment]
Currently a PR at internal doc repo.
