### ISSUE TITLE
Support Changing Serializable Field Names

### ISSUE THREAD

**Issue by akperkins** [realm/realm-java#3622]
**Goal**

I would like to change the json key that is mapped to my RealmObject subclass.

**Expected Results**

I am currently saving the JSON that I get back straight to my realm db via

`RealmObjectSubclass object = realm.createOrUpdateObjectFromJson(RealmObjectSubclass.class, json);`

When you do this, similar to libraries like Gson, Realm will map the JSON keys to the field name of the class that you are saving.

However, unlike Gson, I don't see anyway in the Realm API to map a JSON key to a field unless they have the same name. This is usually solved in other JSON parsing libraries with annotations on the field like @SerializableName("actualKeyNameInTheJson").

**Comment by cmelchior** [comment]
Hi @akperkins 
Right now the answer is that you should use GSON or similar to achieve this. However, there is discussion going on in #682 right now for adding explicit support for it.

I'll close this as an duplicate, and let the discussion continue in #682

**Comment by Zhuinden** [comment]
@cmelchior technically I advised him to open the separate issue for it, but that'll work too 👅
