### ISSUE TITLE
io.realm.exceptions.RealmIOException: Failed to access

### ISSUE THREAD

**Issue by paisrikanth** [realm/realm-java#3632]
io.realm.exceptions.RealmIOException: Failed to access: . make_dir() failed: No such file or directory path: /data/data/com.test.app/files/default.realm.enc.management
                                                     at io.realm.internal.SharedGroup.createNativeWithImplicitTransactions(Native Method)
                                                     at io.realm.internal.SharedGroup.<init>(SharedGroup.java:64)
                                                     at io.realm.internal.SharedGroupManager.<init>(SharedGroupManager.java:49)
                                                     at io.realm.BaseRealm.<init>(BaseRealm.java:79)
                                                     at io.realm.Realm.<init>(Realm.java:138)
                                                     at io.realm.Realm.createAndValidate(Realm.java:248)
                                                     at io.realm.Realm.createInstance(Realm.java:228)
                                                     at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:126)
                                                     at io.realm.Realm.getDefaultInstance(Realm.java:174)
#### Version of Realm and tooling

Realm version(s): - 1.0.0

Android Studio version: - 2.2

Which Android version and device: -  Android 6.0 and Android 7.0 device is nexus 6P

When the existing app is updated from the playstore.. on marshmallow and Android I get the above exception and on Android lolipop its Invalid realm file exception

**Comment by paisrikanth** [comment]
despite having these files in the filesdir.. I get these exception

-rw------- u0_a96   u0_a96      16384 2016-10-14 16:38 default.realm.enc
-rw------- u0_a96   u0_a96       1120 2016-10-14 16:42 default.realm.enc.lock
drwx------ u0_a96   u0_a96            2016-10-14 16:42 default.realm.enc.management
-rw------- u0_a96   u0_a96        256 2016-10-14 16:37 realmKey
drwx------ u0_a96   u0_a96            2016-10-14 16:38 users

**Comment by kneth** [comment]
Can you share the code where you set up your `RealmConfiguration()`? I notice the error message says ` Failed to access: . ` so somehow you try to use `.` as directory or file name?

**Comment by paisrikanth** [comment]
`    fun setRealmMigrationConfiguration() {

        realmConfiguration = RealmConfiguration.Builder(this)
                .schemaVersion(1)
                .migration(RealmMigrationClass())
                .build()

        Realm.setDefaultConfiguration(realmConfiguration)

        keyStore.load(null)
        val realmKey = "realmKey"

        val realmKeyFile = File("${this.filesDir}/$realmKey")

        if(keyStore.containsAlias(alias)) {
            if(!realmKeyFile.exists()) {
                keyStore.deleteEntry(alias)
            }
        }

        val encryptedRealmFileName = "default.realm.enc"

        if (!keyStore.containsAlias(alias)) {

            //Generates key pair in key store
            generateKeyPairInKeyStore(alias)

            val privateKeyEntry = keyStore.getEntry(alias, null) as KeyStore.PrivateKeyEntry
            val publicKey = privateKeyEntry.certificate.publicKey

            val key = generateKey()

            val encryptedKey = encryptKey(publicKey,key)

            realmKeyFile.writeBytes(encryptedKey)

            val unencryptedRealm = File("${this.filesDir}/default.realm")
            val encryptedRealm = File("${this.filesDir}/$encryptedRealmFileName")

            if (unencryptedRealm.exists() && !encryptedRealm.exists()) {
                val realm = Realm.getDefaultInstance()
                realm.writeEncryptedCopyTo(encryptedRealm, MessageDigest.getInstance("SHA-512").digest(key))
                realm.close()
            }

            realmConfiguration = RealmConfiguration.Builder(this)
                    .schemaVersion(1)
                    .migration(RealmMigrationClass())
                    .name(encryptedRealmFileName)
                    .encryptionKey(MessageDigest.getInstance("SHA-512").digest(key))
                    .build()

            Realm.setDefaultConfiguration(realmConfiguration)

        } else {
            val privateKeyEntry = keyStore.getEntry(alias, null) as KeyStore.PrivateKeyEntry
            val privateKey = privateKeyEntry.privateKey

            val keyFile = realmKeyFile.readBytes()
            val buffer = decryptKey(privateKey,keyFile)

            realmConfiguration = RealmConfiguration.Builder(this)
                    .schemaVersion(1)
                    .migration(RealmMigrationClass())
                    .name(encryptedRealmFileName)
                    .encryptionKey(MessageDigest.getInstance("SHA-512").digest(buffer))
                    .build()
            Realm.setDefaultConfiguration(realmConfiguration)

            //To Test whether the realm file is decrypted correctly
            try {
                val realm = Realm.getDefaultInstance()
                realm.close()
            } catch(i: IllegalArgumentException) {
                realmConfiguration = RealmConfiguration.Builder(this)
                        .schemaVersion(1)
                        .migration(RealmMigrationClass())
                        .name(encryptedRealmFileName)
                        .encryptionKey(buffer)
                        .build()

                Realm.setDefaultConfiguration(realmConfiguration)

            }

        }
    }`

Code to set up my realm configuration (Kotlin syntax)

**Comment by beeender** [comment]
@paisrikanth are you able to reproduce this issue in your side?

**Comment by kneth** [comment]
@paisrikanth Closing for now. Don't hesitate to reopen if you have updates to share.

**Comment by paisrikanth** [comment]
It happens everytime I delete the Filedir

**Comment by paisrikanth** [comment]
please reopen the issue

**Comment by Zhuinden** [comment]
I'm not sure you're supposed to delete the folders if you have open Realm instances, please verify that global instance count is 0 before you delete Realm's folders

**Comment by paisrikanth** [comment]
I close all the open realm session and reccursively delete the filesdir

**Comment by Zhuinden** [comment]
Are you sure? Did you check `getGlobalInstanceCount()`?

**Comment by beeender** [comment]
@paisrikanth can you make a minimal project to reproduce the issue for us? thanks.

**Comment by paisrikanth** [comment]
I updated the version to 2.3.1

I have a new crash now 

`UncaughtException: io.realm.exceptions.RealmFileException: No such file or directory () in /home/cc/repo/realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 92 Kind: ACCESS_ERROR.
                                                                         at io.realm.internal.SharedRealm.nativeGetSharedRealm(Native Method)
                                                                         at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:209)
                                                                         at io.realm.BaseRealm.<init>(BaseRealm.java:82)
                                                                         at io.realm.Realm.<init>(Realm.java:138)
                                                                         at io.realm.Realm.createAndValidate(Realm.java:283)
                                                                         at io.realm.Realm.createInstance(Realm.java:264)
                                                                         at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:143)
                                                                         at io.realm.Realm.getDefaultInstance(Realm.java:209)`

**Comment by beeender** [comment]
if you want to delete the Realm file, you'd better to use `Realm.deleteRealm()` instead, that will check if all your Realm instances are closed first. Deleting the file directly will be dangerous,

Why do you need to delete the `files` dir? By default, realm file will be created in the `files` directory, which exists by default for every Android device after app installed. I don't really think you should delete that directory. Maybe consider to delete only files in the `files` directory instead?

**Comment by paisrikanth** [comment]
Yes.. What we are doing in the app is to delete all the files in the fliesdir when the user is logged out from the application. and create new Realm instance when he logs in back to the application.

When I updated the Realm version i dont have the crash while deleting the files, however I have a new exception which I posted above in the comments.. To fix this everytime I have to clear the data of the application and try again :(

**Comment by Zhuinden** [comment]
@paisrikanth consider naming the Realm file according to logged in user?

**Comment by kneth** [comment]
I hope you have been able to solve your issue. If not, don't hesitate to either reopen or create new issue.
