### ISSUE TITLE
Permission denied in io_realm_internal_SharedGroup.cpp line 113

### ISSUE THREAD

**Issue by GuaiShu** [realm/realm-java#3633]
io.realm.exceptions.RealmError: Unrecoverable error. Permission denied in io_realm_internal_SharedGroup.cpp line 113 at io.realm.internal.SharedGroup.createNativeWithImplicitTransactions(Native Method)                                                                                   at io.realm.internal.SharedGroup.openSharedGroupOrFail(SharedGroup.java:95)                                                                                   at io.realm.internal.SharedGroup.<init>(SharedGroup.java:74)                                                                                   at io.realm.internal.SharedGroupManager.<init>(SharedGroupManager.java:49)                                                                                   at io.realm.BaseRealm.<init>(BaseRealm.java:86)
at io.realm.Realm.<init>(Realm.java:135)
at io.realm.Realm.createAndValidate(Realm.java:233)
at io.realm.Realm.createInstance(Realm.java:214)
at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:126)
at io.realm.Realm.getDefaultInstance(Realm.java:160)
at com.example.ouxch.myrealmdemo.MainActivity.onCreate(MainActivity.java:43)
at android.app.Activity.performCreate(Activity.java:6303)
at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1108)
at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2376)
at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2483)
at android.app.ActivityThread.access$900(ActivityThread.java:153)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1349)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5438)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:739)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:629)

#### Version of Realm and tooling
Realm version(s): 1.2.0

Android Studio version: 2.2

Which Android version and device: Android 4.4.3 device is PDA

I am learning to use Realm database, I want modify Realm file path,and i found it can not be . In My Activity: I write like this:
        File dir = new File(Environment.getExternalStorageDirectory(), "MyRealmDemo");
        if (!dir.exists()) {
            dir.mkdirs();
        }
        RealmConfiguration realmConfiguration = new RealmConfiguration.Builder(this, dir)
                .deleteRealmIfMigrationNeeded()
                .name("myrealmdemo.realm").build();

        Realm.setDefaultConfiguration(realmConfiguration);
        Realm.getDefaultInstance();

**Comment by beeender** [comment]
Hi, there is a bug #3140 that Realm doesn't work on external storage with Android and SELinux. Please use internal storage for now.

**Comment by GuaiShu** [comment]
@beeender  thanks!  
My application may be relatively large data (0-1000M), internal storage may not be enough, is there any good solution? . Or when this bug will probably be repaired?

**Comment by zaki50** [comment]
@GuaiShu the fix of #3140 is under the review now.
I hope the fix fill be shipped with the next release.

**Comment by beeender** [comment]
1000M sounds really big, may I ask why do you need that big database? Do you try to store image files into the database?

**Comment by Zhuinden** [comment]
The only time I've ever seen Realms that big was when they didn't close the background thread Realm instances.

**Comment by GuaiShu** [comment]
@zaki50 . Thanks again. I also hope to release as soon as possible.
@beeender . Our application is enterprise-class, we have been using sqlite database, when a large amount of data, the query becomes very slow, and the user's data continues to grow. I hope Realm can solve our problem, but our device's internal storage really is too small.
@Zhuinden  . What do you mean? I do not quite understand what you're saying. My English is not good

**Comment by Zhuinden** [comment]
@GualShu nevermind then, you really have a lot of data. 

You should use `findAllAsync()` and `findAllSortedAsync()` methods when using Realm.

**Comment by GuaiShu** [comment]
@Zhuinden  . Sure! Thanks for your suggestion! But now the primary problem is that Realm can not be created in external storage. Waiting for the repair of this problem.

**Comment by kneth** [comment]
I have added a reference from #3591 to this so github will close it when the PR is merged.

**Comment by GuaiShu** [comment]
@kneth  ok, thanks your remind.

**Comment by zaki50** [comment]
fixed in #3591
