### ISSUE TITLE
 Gradle sync failed: Connection timed out: connect. If you are behind an HTTP proxy, please configure the proxy settings either in IDE or Gradle.             Consult IDE log for more details (Help | Show Log)

### ISSUE THREAD

**Issue by TrickyAnkit** [realm/realm-java#3636]
> We LOVE to help with any issues or bug you have!

> **Questions**: If you have questions about how to use Realm, please ask on [SO](http://stackoverflow.com/questions/ask?tags=realm) - we monitor the Realm tag.

> **Feature Request**: Just fill in the first two sections below.

> **Bugs**: To help you as fast as possible with an issue or bug please describe your issue and the steps you have taken to reproduce it in as many details as possible.
>
> Thanks for helping us help you :-)
>
> Remove this and above before submitting.

#### Goal

> What do you want to achieve?

#### Expected Results

> ?

#### Actual Results

>  E.g. full stack trace with exception

#### Steps & Code to Reproduce

> Describe your current debugging efforts.

#### Code Sample

```java

> Your code here. Bigger samples should ideally be as separate Android Studio project, 
> in gists/repositories or privately at help@realm.io)

```

#### Version of Realm and tooling
Realm version(s): ?

Android Studio version: ?

Which Android version and device: ?

**Comment by TrickyAnkit** [comment]
![screenshot_sun_oct_16_11 15 54](https://cloud.githubusercontent.com/assets/16396629/19415581/fe3efe66-9391-11e6-90f5-27fcaa6c8b1b.png)
 I am using Android Studio 2.2.1 and facing this error. I have tried almost everything read  more than 100+ articles but still i m on the same page unable to solve to solve this problem? Please Help me i'll be thankful to you!
Error:-
 Gradle sync failed: Connection timed out: connect. If you are behind an HTTP proxy, please configure the proxy settings either in IDE or Gradle.
            Consult IDE log for more details (Help | Show Log)

**Comment by zaki50** [comment]
example of http proxy configuration is here:

https://docs.gradle.org/current/userguide/build_environment.html#sec:accessing_the_web_via_a_proxy

**Comment by zaki50** [comment]
Feel free to reopen this if you have further question.

**Comment by Lukyanov03851** [comment]
turn off your firewall

**Comment by umutsoysl** [comment]
https://stackoverflow.com/questions/35692397/errorconnection-timed-out-connect

**Comment by vikas0** [comment]
**Solution: that worked for me**


***setting - 
   language and framework - 
         kotline - 
    update kotline plugin version -
     restart computer -
     run android studio and shhuk it works and it ran fater***
[![Update kotline plugin version][1]][1]

tried 
1) using local gradle repository

2) changing no proxy in setting-http

3) uninstalling, reinstalling, formating my laptop
after 2 days:

i tried to see a kotline in setting. then there was an update for kotline,


  [1]: https://i.stack.imgur.com/i57AT.png

**Comment by Kamil2412** [comment]
Hi, 
i am trying to build my project after making changes in gradle.build and Manifes file, the error is occuring again and again

ERROR: Cause: connect timed out

- i am not using any proxy
- Internet Connection is fine
- Android Studio is up to date


what to do with this error ?
please assist me...

![image](https://user-images.githubusercontent.com/36516390/67361991-b3f3cc00-f587-11e9-92ee-52ea770ddb87.png)

**Comment by kshitijk83** [comment]
> Hi,
> i am trying to build my project after making changes in gradle.build and Manifes file, the error is occuring again and again
> 
> ERROR: Cause: connect timed out
> 
> * i am not using any proxy
> * Internet Connection is fine
> * Android Studio is up to date
> 
> what to do with this error ?
> please assist me...
> 
> ![image](https://user-images.githubusercontent.com/36516390/67361991-b3f3cc00-f587-11e9-92ee-52ea770ddb87.png)

same here!

**Comment by ginty1** [comment]
Read timed out

**Comment by Lukyanov03851** [comment]
Maybe you need turn off your firewall

пн, 18 лист. 2019 о 22:38 Kshitiz Kumar <notifications@github.com> пише:

**Comment by Lukyanov03851** [comment]
Maybe you need turn off your firewall

чт, 12 бер. 2020 о 18:48 kondwani chiomba <notifications@github.com> пише:

**Comment by yarradedeepya** [comment]
same problem plzz help

**Comment by prof-kalabwa** [comment]
> > Hi,
> > i am trying to build my project after making changes in gradle.build and Manifes file, the error is occuring again and again
> > ERROR: Cause: connect timed out
> > 
> > * i am not using any proxy
> > * Internet Connection is fine
> > * Android Studio is up to date
> > 
> > what to do with this error ?
> > please assist me...
> > ![image](https://user-images.githubusercontent.com/36516390/67361991-b3f3cc00-f587-11e9-92ee-52ea770ddb87.png)
> 
> same here!

I also got the same problem. It is a newly created project but the gradle just won't build. It always give error

Gradle sync failed: Connection timed out: connect. If you are behind an HTTP proxy, please configure the proxy settings either in IDE or Gradle.

Though i'm not using proxy server. Also tried turning off the firewall and same error. anybody answer. please. Thank you

**Comment by prof-kalabwa** [comment]
> **Solution: that worked for me**
> 
> _**setting - language and framework - kotline - update kotline plugin version - restart computer - run android studio and shhuk it works and it ran fater**_
> [![Update kotline plugin version](https://camo.githubusercontent.com/6fcc0befb753652c4d8aa9632ee3ddfb27bcfc48/68747470733a2f2f692e737461636b2e696d6775722e636f6d2f69353741542e706e67)](https://i.stack.imgur.com/i57AT.png)
> 
> tried
> 
> 1. using local gradle repository
> 2. changing no proxy in setting-http
> 3. uninstalling, reinstalling, formating my laptop
>    after 2 days:
> 
> i tried to see a kotline in setting. then there was an update for kotline,

will this work if i'm using java?

**Comment by chinthaka01** [comment]
try: https://support.apple.com/guide/mac-help/enter-proxy-server-settings-on-mac-mchlp2591/mac this works for me.

**Comment by AravinthC-18** [comment]
When you have antivirus protection please turn it off.
