### ISSUE TITLE
Model reference becomes null after adding to a different model relation

### ISSUE THREAD

**Issue by chrisolsen** [realm/realm-java#3637]
#### Summary

With the code below it can be seen that I have an `Account` : `Program` relation as well as `Account` : `[]Account`. The `Program` can be accessed through the `Account` until a new relation is added, after that I the `account.program` is immediately null. Using stetho it can be seen that the program is now a null value.

##### Account

```java
class Account {
    public Program program;
    public RealmList<Account> following;
}
```

##### Follow account
```java
// ...
realm.executeTransaction(new Realm.Transaction() {
    @Override
    public void execute(Realm realm) {
        Account currentUser = realm.where(Account.class)
                .equalTo(Account.ATTR_KEY, Session.getAccountKey(context))
                .findFirst();

        Account a = resp.body();          // account's program is not null here
        Log.d("program", currentUser.program.name);   // shows the program name
        currentUser.following.add(a);   // results in Account -> Program disconnect
        Log.d("program", currentUser.program.name);   // null pointer exception
    }
});
// ...
```

#### Version of Realm and tooling
Realm version(s):
2.0.2

Android Studio version: ?
2.2.1

Which Android version and device: ?
4.2.1 Galaxy Nexus

**Comment by Zhuinden** [comment]
Does the primary key of `a` match the primary key of `currentUser`?

**Comment by chrisolsen** [comment]
Right now when testing, the primary key of `a` does match the current user, but I can't imagine why that would be a problem, especially when error is in setting a different relation to null.

The `resp.body` payload will 100% of the time contain account data that already exists in the database.

**Comment by Zhuinden** [comment]
Ah.

Please try

      currentUser.following.add(realm.copyToRealmOrUpdate(a));

**Comment by Zhuinden** [comment]
In that case this issue is quite simple, the newly obtained `Account` with the ID of `currentUser` has no object links when you download it, and you "update" the original object because primary key is shared.

Solution, if the account exists, find and merge it instead of just setting it directly

``` java
realm.executeTransaction(new Realm.Transaction() {
    @Override
    public void execute(Realm realm) {
        Account currentUser = realm.where(Account.class)
                .equalTo(Account.ATTR_KEY, Session.getAccountKey(context))
                .findFirst();

        Account a = resp.body();          // account's program is not null here
        Account dbA = realm.where(Account.class).equalTo(Account.ATTR_KEY, a.getAccountKey()).findFirst();
        if(dbA == null) {
             dbA = realm.copyToRealmOrUpdate(a);
        } else {
             // merge if needed
        }
        Log.d("program", currentUser.program.name);   // shows the program name
        currentUser.following.add(dbA);   // results in Account -> Program
        Log.d("program", currentUser.program.name);   // links should remain
    }
});
```

**Comment by chrisolsen** [comment]
You are right in regards to the account payload from `resp.body()` not containing the program and then deleting it. 

Performing a realm lookup for the account, then adding that account reference works.

Sorry for the post here, I thought it was a bug :(

**Comment by Zhuinden** [comment]
Well considering you overrode the original `currentUser` considering the proxy pointed to the same object, it's no wonder the error looked so arcane :slightly_smiling_face:
