### ISSUE TITLE
copyFromRealm OOM Crash

### ISSUE THREAD

**Issue by johnryan** [realm/realm-java#3645]
#### Goal

Copy a realm list out of a realm.

#### Expected Results

copyFromRealm returns a detached copy without crashing.

#### Actual Results

copyFromRealm sometimes crashes with a OOM error

#### Steps & Code to Reproduce

I'm not able to reproduce the crash but the crash always happens in conjunction with detaching a few hundred objects from the realm. I'm not sure if there's any other metrics I can gather to facilitate debugging. I'm also calling this from a new thread but I don't see why that would cause the issue.

#### Code Sample

```java
Thread asyncThread = new Thread(new Runnable() {
    @Override
    public void run() {
       Realm realm = Realm.getDefaultInstance();
       RealmQuery<MyObject> query = r.where(MyObject.class);
       RealmResults<MyObject> results = query.findAll().sort("startTime", Sort.DESCENDING);
       final List<MyObject> detachedResults = realm.copyFromRealm(results); //CRASHES HERE
}
```

Stack Trace: 

```
java.lang.OutOfMemoryError: Failed to allocate a 34 byte allocation with 2144 free bytes and 2144B until OOM
	at io.realm.internal.UncheckedRow.nativeGetString(UncheckedRow.java)
	at io.realm.internal.UncheckedRow.getString(UncheckedRow.java:153)
	at io.realm.TWCallRealmProxy.realmGet$mStatus(TWCallRealmProxy.java:483)
	at io.realm.TWCallRealmProxy.createDetachedCopy(TWCallRealmProxy.java:2019)
	at io.realm.DefaultRealmModuleMediator.createDetachedCopy(DefaultRealmModuleMediator.java:611)
	at io.realm.Realm.createDetachedCopy(Realm.java:1460)
	at io.realm.Realm.copyFromRealm(Realm.java:1151)
	at io.realm.Realm.copyFromRealm(Realm.java:1117)
```
#### Version of Realm and tooling
Realm version(s): 2.0.2

Android Studio version: 2.2.1

Which Android version and device: SM-J700P / 6.0.1

**Comment by Zhuinden** [comment]
Does your object have any links or realm lists?

**Comment by johnryan** [comment]
@Zhuinden yes the objects have two RealmList variables

**Comment by Zhuinden** [comment]
Do they by chance have a possibility of referencing each other?

You might want to consider adding a maximum depth to `copyFromRealm()`, such as 1 or 2.

**Comment by johnryan** [comment]
I can try adding the depth but no there is no possibility (unless i'm misunderstanding something about realm) that they reference each other. The RealmList variables are lists of objects that just contain Strings so no reference to any other RealmObject

**Comment by Zhuinden** [comment]
Well you can also try putting the `copyFromRealm()` into a transaction and see if that helped.

**Comment by Zhuinden** [comment]
Even with `realm.beginTransaction()`, copy, then `realm.cancelTransaction()` might work.

**Comment by cmelchior** [comment]
Hi @johnryan A few hundred objects shouldn't take up much memory, so my guess is that your app is memory constrained in some other way? Perhaps you are showing a lot of images at the same time?

As @Zhuinden  said, `copyFromRealm` is a deep copy, so it will also copy all referenced objects which depending on your models might be quite a lot.

I would start by using the memory analyzer on your app to figure out exactly what is going on.

**Comment by Zhuinden** [comment]
Ah yeah, if you use lots of images, you should consider loading them with an image loader library, like Picasso (or what I prefer, Glide). 

I'd definitely tell you to avoid Fresco if possible.

**Comment by johnryan** [comment]
@Zhuinden @cmelchior I am loading some images but i don't think that's the issue. After running the app with allocation tracking i'm seeing that around 50% of the memory allocated is coming from calls to copyFromRealm() and subsequently createDetachedCopy(). 

There are definitely a lot of objects (several hundred lightweight objects including the nested realm lists) being created here but not so many that i'd think it would crash the app without some sort of leak ...Do you have any other suggestions for debugging?

**Comment by johnryan** [comment]
I think i may have found the issue, there is a weird case where my detach gets called in a loop several times likely causing the crash. Thanks for the help, i'll re-open if there ends up being caused by realm. Thanks.
