### ISSUE TITLE
Relationship one to one

### ISSUE THREAD

**Issue by jjimenez0611** [realm/realm-java#3654]
Hi I'm working with Realm in my APP. I Have a Customer that have a ContactInformation

to save the information I use **copyToRealmOrUpdate(customer)** here I sent the entire object with all the ContactInformation Values.

If I see the ContactInformation table I can see the register, but If I make a query to the customer table the contactInformation comes empty, is like not exist a relationship between the customer and the contactInformation...
 

> We LOVE to help with any issues or bug you have!

> **Questions**: If you have questions about how to use Realm, please ask on [SO](http://stackoverflow.com/questions/ask?tags=realm) - we monitor the Realm tag.

> **Feature Request**: Just fill in the first two sections below.

> **Bugs**: To help you as fast as possible with an issue or bug please describe your issue and the steps you have taken to reproduce it in as many details as possible.
>
> Thanks for helping us help you :-)
>
> Remove this and above before submitting.

#### Goal

> What do you want to achieve?

#### Expected Results

> ?

#### Actual Results

>  E.g. full stack trace with exception

#### Steps & Code to Reproduce

> Describe your current debugging efforts.

#### Code Sample

```java

> Your code here. Bigger samples should ideally be as separate Android Studio project, 
> in gists/repositories or privately at help@realm.io)

```

#### Version of Realm and tooling
Realm version(s): ?

Android Studio version: ?

Which Android version and device: ?

**Comment by zaki50** [comment]
Can I see the code to construct and store Customer into Realm?

**Comment by jjimenez0611** [comment]
Hi

I resolve the problem...

The problem was a singlenton class, in other words was my foul...

But I have other question... Is a way to get the primary key declare on a
realm class? Like a method...

El 18 oct. 2016 9:36 PM, "Makoto Yamazaki" <notifications@github.com>
escribió:

Can I see the code to construct and store Customer into Realm?

—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub
<https://github.com/realm/realm-java/issues/3654#issuecomment-254702076>,
or mute the thread

**Comment by zaki50** [comment]
I'm glad to hear that.

Could you make another issue for the next question? thanks.
