### ISSUE TITLE
UnsatisfiedLinkError with ABI split

### ISSUE THREAD

**Issue by voidshad** [realm/realm-java#3658]
Hello

I am trying to use Realm together with ABI split. And this is what I am getting on attempt to create an Realm instance

java.lang.UnsatisfiedLinkError: No implementation found for long io.realm.internal.SharedRealm.nativeCreateConfig(java.lang.String, byte[], byte, boolean, boolean, boolean, boolean, java.lang.String, java.lang.String) (tried Java_io_realm_internal_SharedRealm_nativeCreateConfig and Java_io_realm_internal_SharedRealm_nativeCreateConfig__Ljava_lang_String_2_3BBZZZZLjava_lang_String_2Ljava_lang_String_2)
                      at io.realm.internal.SharedRealm.nativeCreateConfig(Native Method)
                      at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:166)
                      at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:155)
                      at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:124)
                      at io.realm.Realm.getInstance(Realm.java:228)

The code is pretty simple

```java
this.realmConfiguration = new RealmConfiguration.Builder()
				.name(realmName)
				.schemaVersion(0)
				.modules(new FeedRealmModule())
				.deleteRealmIfMigrationNeeded()
				.build();
Realm realm = Realm.getInstance(realmConfiguration);
```

librealm-jni.so is included in apk in the proper directory (armeabi-v7a) and that is the only directory in libs folder.

For this build I don`t use proguard (minifyEnabled false). 

Realm version(s): 2.0.2

Android Studio version: 2.2.1

Which Android version and device: Samsung galaxy s6

**Comment by zaki50** [comment]
Could you provide your `build.gradle`?

**Comment by voidshad** [comment]
Yep, sure
[build.gradle.zip](https://github.com/realm/realm-java/files/541787/build.gradle.zip)

**Comment by voidshad** [comment]
Ok, we`ve found a problem. It seems like appropriate version of librealm-jni.so has been substituted with an outdated one. That was the cause of problem.

I believe, this can be closed
