### ISSUE TITLE
java.lang.IllegalStateException: Requested table is not in this Realm.

### ISSUE THREAD

**Issue by mandrachek** [realm/realm-java#3659]
Realm Version: Realm 1.2.0
compileSdkVersion: 24
buildToolsVersion "24.0.3"
minSdkVersion 19
targetSdkVersion 24
Android Version: 6.0.1
Device: Motorola G3

StackTrace:

> Caused by java.lang.IllegalStateException: Requested table is not in this Realm. Creating it requires a transaction: class_VillageInvite
>        at io.realm.internal.Group.getTable(Group.java:193)
>        at io.realm.RealmSchema.getTable(RealmSchema.java:230)
>        at io.realm.RealmSchema.getSchemaForClass(RealmSchema.java:250)
>        at io.realm.RealmQuery.<init>(RealmQuery.java:139)
>        at io.realm.RealmQuery.createQuery(RealmQuery.java:88)
>        at io.realm.Realm.where(Realm.java:1050)
>        at com.myapp.app.data.adapters.VillageInviteAdapter.loadData(VillageInviteAdapter.java:53)
>        at com.myapp.app.data.adapters.VillageInviteAdapter.refresh(VillageInviteAdapter.java:47)
>        at com.myapp.app.fragments.profile.MyVillagesFragment.onResume(MyVillagesFragment.java:143)
>        at android.support.v4.app.Fragment.performResume(Fragment.java:2126)
>        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1151)
>        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1290)
>        at android.support.v4.app.FragmentManagerImpl.moveToState(FragmentManager.java:1272)
>        at android.support.v4.app.FragmentManagerImpl.dispatchResume(FragmentManager.java:2159)
>        at android.support.v4.app.FragmentController.dispatchResume(FragmentController.java:223)
>        at android.support.v4.app.FragmentActivity.onResumeFragments(FragmentActivity.java:507)
>        at android.support.v4.app.FragmentActivity.onPostResume(FragmentActivity.java:496)
>        at android.support.v7.app.AppCompatActivity.onPostResume(AppCompatActivity.java:172)
>        at android.app.Activity.performResume(Activity.java:6359)
>        at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3110)
>        at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3152)
>        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2495)
>        at android.app.ActivityThread.-wrap11(ActivityThread.java)
>        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1354)
>        at android.os.Handler.dispatchMessage(Handler.java:102)
>        at android.os.Looper.loop(Looper.java:148)
>        at android.app.ActivityThread.main(ActivityThread.java:5443)
>        at java.lang.reflect.Method.invoke(Method.java)
>        at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:728)
>        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:618)
> 

loadData, line 53 mentioned in the stack trace is the body of this method:
```
    @Override
    protected RealmResults<VillageInvite> loadData(Realm realm) {
        return realm.where(VillageInvite.class).findAllSorted("name", Sort.ASCENDING);
    }
```

Not sure how to reproduce currently. I have 1 crash recorded from Crahslytics, and am reaching out to the user to see if we can get more information.

**Comment by zaki50** [comment]
It is very strange.
When opening a typed Realm instance, it checks if the all tables exist in the database file.

**Comment by Zhuinden** [comment]
My guess goes for multiprocess access.

**Comment by mandrachek** [comment]
Yes, VillageInvite is included in the Realm. Not using multiprocess. But it is multi-threaded. 

I think I've managed to identify when it occurs, but haven't been able to reproduce it. 

When the user logs out, I call deleteAll() in an IntentService. However, it was possible for an update to come in from a delayed network request from another IntentService.  It looks like it was trying to update at the exact same instant the deleteAll() was being called.

I've taken steps to cancel all network operations and prevent results from coming back/being processed during the logout process.  Hopefully that will avoid the issue.

**Comment by Zhuinden** [comment]
That is odd, because you can only call `deleteAll`in a transaction, and no two transactions can occur at the same time. 

Maybe one of your RealmResults on your background thread was queried outside the transaction?

**Comment by kneth** [comment]
@mandrachek Any progress?

**Comment by mandrachek** [comment]
@kneth no, sorry, still haven't been able to reproduce, and haven't seen it again.
