### ISSUE TITLE
Change checkbox on RecyclerView without save selected items into database

### ISSUE THREAD

**Issue by tux-world** [realm/realm-java#3661]
How can i use ```checkbox``` on ```RecyclerView``` without save selected items into database? when i use model which is extends from RealmObject on recyclerview, for every change one of this model must be we use Transaction, :|  but i dont want to save it to database, its only for getting user selected Items, i can't resolve this problem

**Comment by zaki50** [comment]
I think this needs #3466 for easy implementation.

I think you need to have something like extra boolean array in the `Adapter` to keep the states of the checkboxes.

**Comment by tux-world** [comment]
checkbox are model items, this solution is very hard to manage that, because of maybe i have to create other class like with current model

**Comment by zaki50** [comment]
How about this?

```java
public class MyAdapter extends RealmRecyclerViewAdapter<Model, MyAdapter.Holder> {
    private Map<String, Boolean> checkBoxStates = new HashMap<>();

    @Override
    public void onBindViewHolder(Holder holder, int position) {
        //noinspection ConstantConditions
        final Model item = getItem(position);
        holder.text.setText(item.text);

        Boolean checkedState = checkBoxStates.get(item.id);
        holder.checkbox.setChecked(checkedState == null ? false : checkedState);
    }

    // call this when the checked state is changed
    private void onCheckChanged(int position, boolean checked) {
        final Model item = getItem(position);
        if (item == null) {
            return;
        }
        checkBoxStates.put(item.id, checked);
    }

    static class Holder extends RecyclerView.ViewHolder {
        public final TextView text;
        public final CheckBox checkbox;

        Holder(View itemView) {
            super(itemView);
            text = (TextView) itemView.findViewById(android.R.id.text1);
            checkbox = (CheckBox) itemView.findViewById(android.R.id.checkbox);
            // some more code...
        }
    }
}
```

**Comment by tux-world** [comment]
@zaki50 Thanks i think by this solution my problem will be resolved

**Comment by zaki50** [comment]
😁

**Comment by tux-world** [comment]
@zaki50  hi sir, i'm trying to use your solution over realm but it doesnt work correctly, could you please see my code on this link: http://stackoverflow.com/questions/40742992/android-checkbox-state-dont-change-state-after-some-click-on-that   Thanks

**Comment by tux-world** [comment]
@zaki50 Your correct solution is here : http://stackoverflow.com/questions/40739336/android-change-checkboxes-on-adapter-dont-work-correctly/40780350?noredirect=1#comment68786076_40780350
