### ISSUE TITLE
Reducing Android APK size 

### ISSUE THREAD

**Issue by tux-world** [realm/realm-java#3662]
when i install Realm on my project my apk size will be 11M, but without that apk file size is 5M, how can i compress or Reducing Android APK size when i want to release application? i just learn about this solution on[ this link](https://realm.io/news/reducing-apk-size-native-libraries/), but i don't know how can i reduce.

after use this feature on Gradle

```
android {
    // Some other configuration here...

    splits {
        abi {
            enable true
            reset()
            include 'x86', 'armeabi', 'armeabi-v7a', 'mips'
            universalApk false
        }
    }
}
```

which generated file is for android devices?

**Comment by tux-world** [comment]
you right, but most user don't know whats himself device architecture. in this result for apk file size:

```
-rw-rw-r-- 1 mahdi mahdi 4.8M Oct 19 22:41 app-armeabi-debug.apk
-rw-rw-r-- 1 mahdi mahdi 5.6M Oct 19 22:41 app-armeabi-v7a-debug.apk
-rw-rw-r-- 1 mahdi mahdi  11M Oct 19 22:36 app-debug.apk
-rw-rw-r-- 1 mahdi mahdi 6.1M Oct 19 22:41 app-mips-debug.apk
-rw-rw-r-- 1 mahdi mahdi 6.0M Oct 19 22:41 app-x86-debug.apk
```
i have different size in all files. ```app-debug.apk``` is default generated apk

**Comment by cmelchior** [comment]
Yes, but Google Play automatically detect what architecture the device has when it asks to install the app. The use doesn't have to choose that. It happens automatically.

**Comment by tux-world** [comment]
Thanks :100:

**Comment by billrancho** [comment]
great! that's what I m lookin 4.
