### ISSUE TITLE
Use Dependeny Injection for Realm

### ISSUE THREAD

**Issue by tux-world** [realm/realm-java#3664]
Hi, I'm novice on Dependency Injection and i'm trying to use that for using realm on project, [this link is my reference](https://github.com/zaki50/realm_template/tree/master/app/src/main/java/com/example/realm_template), after create some class as an component and model i get this error:

```
Error:(93, 14) error: cannot find symbol method init(Application)
/home/mahdi/Desktop/Home/Projects/CafeMaku/app/src/main/java/com/pishguy/androidapplication/cafemaku/DependencyInjection/ApplicationModule.java

Error:(26, 52) error: no suitable constructor found for Builder(no arguments)
constructor Builder.Builder(File) is not applicable
(actual and formal argument lists differ in length)
constructor Builder.Builder(Context) is not applicable
(actual and formal argument lists differ in length)
```

My Application Class:

```
    public void onCreate() {
        super.onCreate();
        ...

        self = this;

        Realm.init(this);

        component = DaggerApplicationComponent.create();
    }

    public static Context getContext() {
        return context;
    }

    public static Application get(Context context) {
        return (Application) context.getApplicationContext();
    }

    public static Application getInstance() {
        return self;
    }

    public ApplicationComponent getComponent() {
        return component;
    }
}
```

```cannot find symbol method init(Application)``` error is for ```Realm.init(this);``` 

and my applicationModel class is:

```
import javax.inject.Singleton;

import dagger.Module;
import dagger.Provides;
import io.realm.Realm;
import io.realm.RealmConfiguration;

@Module
public class ApplicationModule {

    @Provides
    Context provideApplicationContext() {
        return Application.getInstance();
    }

    @Provides
    @Singleton
    RealmConfiguration provideRealmConfiguration() {
        final RealmConfiguration.Builder builder = new RealmConfiguration.Builder()
                .schemaVersion(Migration.SCHEMA_VERSION)
                .builder.deleteRealmIfMigrationNeeded()
                .migration(new Migration());
        return builder.build();
    }

    @Provides
    Realm provideDefaultRealm(RealmConfiguration config) {
        return Realm.getInstance(config);
    }
}
```

```error: no suitable constructor found for Builder(no arguments)``` error is for this constructor ```new RealmConfiguration.Builder()```

Please help me to resolve this problem @zaki50

**Comment by zaki50** [comment]
I guess you are using old version of Realm Java.
What version of Realm are you using?
And can you upgrade it to `2.0.2`?

**Comment by tux-world** [comment]
@zaki50 Oh yes You right, I'm so sorry sir

**Comment by tux-world** [comment]
@zaki50 whats ```BuildConfig``` in Migration file? how can import that? i cant find that in your project

**Comment by zaki50** [comment]
That class is generated by android gradle plugin when it build the project.
Once you build your project, you can find the class under the package that you specified in your `AndroudManifest.xml`

**Comment by tux-world** [comment]
​need to install any library on Gradle or not? after rebuild project i get
this error:  ```Error:(29, 13) error: cannot find symbol variable
BuildConfig```

**Comment by zaki50** [comment]
no need to add anything.
The only thing you need to do is that adjusting the package of import to your own

**Comment by tux-world** [comment]
@zaki50 Ok Thanks man. let me to test that in other free time, You are grate man :+1:

**Comment by tux-world** [comment]
@zaki50 I'm so sorry, after installing Dagger for using Dependency Injection my project failed to start, could you see [this link](http://stackoverflow.com/q/40150609/6599627), maybe can help me
