### ISSUE TITLE
Link queries question

### ISSUE THREAD

**Issue by roughboy** [realm/realm-java#3668]
Recently i have studied link queries example with Person and Dogs:
https://realm.io/docs/java/latest/#link-queries

I am wondering how should I construct query in order to find Person which has dog named "Fluffy" and  that dog has "brown" color at the same time. The obvious result of such query is Person U2 named John, however I have no idea how I should construct such query. Any help?

**Comment by beeender** [comment]
Try this:
```
// r2 => [U2]
RealmResults<Person> r2 = realm.where(Person.class)
                             .equalTo("dogs.name", "Fluffy")
                             .findAll() // This the key point. Build a query based on the first query's result.
                             .where()
                             .equalTo("dogs.color", "Brown")
                             .findAll();
```

**Comment by roughboy** [comment]
Thanks a lot!

**Comment by Zhuinden** [comment]
@beeender out of curiousity, would this work?

``` java
// r2 => [U2]
RealmResults<Person> r2 = realm.where(Person.class)
                             .equalTo("dogs.name", "Fluffy")
                             .findAllAsync() // This the key point. Build a query based on the first query's result.
                             .where()
                             .equalTo("dogs.color", "Brown")
                             .findAllAsync();
```

?

**Comment by astigsen** [comment]
Could you shorten it to:

```java
RealmResults<Person> r2 = realm.where(Person.class)
                             .equalTo("dogs.name", "Fluffy")
                             .equalTo("dogs.color", "Brown")
                             .findAll();
```

or would that give wrong results?

**Comment by Zhuinden** [comment]
@astigsen that will return `has at least one dog with the name Fluffy and has at least one dog with the color Brown`

I thought you wanted `has at least one dog with the name Fluffy which has color brown`?

**Comment by astigsen** [comment]
Thanks, I had missed that the queries involved lists rather than individual links.

**Comment by kneth** [comment]
The documentation is correct, and queries above will result in `[U1, U2]`. You really need #607 to express it more elegant. So far, you can manually add and maintain relationship in the opposite direction i.e., a field `Person` to `Dog`. Then you can query for the dog and follow the link back to the owner/person.

**Comment by beeender** [comment]
@Zhuinden Thanks a lot for the use case in https://github.com/realm/realm-java/issues/3668#issuecomment-255378795 . It won't work now since the first `findAllAsync()` won't give a valid `TableView` immediately and it causes the 2nd `where` crash. I add an item in  https://github.com/realm/realm-java/issues/3372 

Since the original question has been answered, I will just close this issue.
