### ISSUE TITLE
Create ordered realm collection using a comparator

### ISSUE THREAD

**Issue by bhargavms** [realm/realm-java#3669]
#### Goal
Add an extra functionality to use a comparator implementation to sort realm collection and create
ordered realm collection

**Comment by Zhuinden** [comment]
Been discussed before, sorting is in C++ side so sending in an arbitrary comparator just isn't trivial.

**Comment by bhargavms** [comment]
whoops sorry, closing then?

**Comment by Zhuinden** [comment]
Well, there was https://github.com/realm/realm-java/issues/3625 but that was also a duplicate, so yeah :)

**Comment by Zhuinden** [comment]
The big thread was https://github.com/realm/realm-java/issues/2313

**Comment by kneth** [comment]
Sorting is done at C++ level, and calling back to Java is going to be expensive (you will probably do O(N*log(N)) comparisons).
