### ISSUE TITLE
Native code failure in librealm-jni.so

### ISSUE THREAD

**Issue by FrancescoCapari** [realm/realm-java#3670]
An user of my application has a problem that the application crashes everytime when using latest version of realm 2.0.2. I got a logcat from my user, see below. Is there please anything that I or him can do? I'm currently not sure if this will happen to more users, the same user was previously using Realm 1.1.0 and it was working correctly on the same device.

>*** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
>Build fingerprint: 'motorola/XT926_verizon/vanquish:4.4.2/KDA20.62-15.1/15:user/release-keys'
>Revision: 'p300'
>pid: 1817, tid: 1817, name: rak.myapplication  >>> com.myapplication <<<
>signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0000002c
>    r0 00000000  r1 4187e4d8  r2 00000000  r3 4187cfd8
>    r4 00000000  r5 4187cfd8  r6 5fa78e90  r7 5fa78e98
>    r8 416a3c38  r9 00000000  sl 416a3c38  fp 5b7f224c
>    ip 00000001  sp be81d478  lr 416353c9  pc 416353ce  cpsr 600d0030
>    d0  0000000000000000  d1  0000000000000000
>    d2  0000000000000000  d3  0000000000000000
>    d4  4026000000000000  d5  316c3131316c6c31
>    d6  4026000000000000  d7  0000000b00000000
>    d8  0000000000000000  d9  0000000000000000
>    d10 0000000000000000  d11 0000000000000000
>    d12 0000000000000000  d13 0000000000000000
>    d14 0000000000000000  d15 0000000000000000
>    d16 20646c756f632027  d17 6c20656220746f6e
>    d18 0b0a230b330b0a0b  d19 0a21230a09350a33
>    d20 35220a090a0d0e26  d21 0c022d230a24230a
>    d22 002b07e020f80a0a  d23 0cfa620a0a090a02
>    d24 0003000000030000  d25 0003000000030000
>    d26 0000002e0000002d  d27 000000300000002f
>    d28 0100010001000100  d29 0100010001000100
>    d30 0000000000000000  d31 0000000000000000
>    scr 60000010
> 
>backtrace:
>    #00  pc 0004e3ce  /system/lib/libdvm.so
>    #01  pc 00054eed  /data/app-lib/com.myapplication-1/librealm-jni.so (JNI_OnLoad+232)
>    #02  pc 00052d5d  /system/lib/libdvm.so (dvmLoadNativeCode(char const*, Object*, char**)+468)
>    #03  pc 0006a635  /system/lib/libdvm.so
>    #04  pc 000297e0  /system/lib/libdvm.so
>    #05  pc 00030ae8  /system/lib/libdvm.so (dvmMterpStd(Thread*)+76)
>    #06  pc 0002e180  /system/lib/libdvm.so (dvmInterpret(Thread*, Method const*, JValue*)+184)
>    #07  pc 00063751  /system/lib/libdvm.so (dvmInvokeMethod(Object*, Method const*, ArrayObject*, ArrayObject*, ClassObject*, bool)+392)
>    #08  pc 0006b713  /system/lib/libdvm.so
>    #09  pc 000297e0  /system/lib/libdvm.so
>    #10  pc 00030ae8  /system/lib/libdvm.so (dvmMterpStd(Thread*)+76)
>    #11  pc 0002e180  /system/lib/libdvm.so (dvmInterpret(Thread*, Method const*, JValue*)+184)
>    #12  pc 0006346d  /system/lib/libdvm.so (dvmCallMethodV(Thread*, Method const*, Object*, bool, JValue*, std::__va_list)+336)
>    #13  pc 0004ca37  /system/lib/libdvm.so
>    #14  pc 0004d267  /system/lib/libandroid_runtime.so
>    #15  pc 0004df8b  /system/lib/libandroid_runtime.so (android::AndroidRuntime::start(char const*, char const*)+354)
>    #16  pc 0000105b  /system/bin/app_process
>    #17  pc 0000e41b  /system/lib/libc.so (__libc_init+50)
>    #18  pc 00000d7c  /system/bin/app_process
> 
>code around pc:
>    416353ac 47ffe92d 460c4605 4629a803 4616461f  
>    416353bc ff1ef7fd 46219803 ff56f7fe 8094f8df  
>    416353cc 6ac344f8 2b074605 f020d029 bb30fa8b  
>    416353dc e0374604 07026860 e033d52a 0014f104  
>    416353ec f844f047 4a1c6923 447a4649 20034682  
>    416353fc 0408e88d f7d169ab 4650ea28 ea12f7d1  
>    4163540c 463b4916 f85869aa 49154001 46329200  
>    4163541c 01ecf8d4 f7fd4479 2400f977 4628e012  
>    4163542c 463a4631 fee2f020 28004604 e7e7d1d2  
>    4163543c 9030f8df 44f92003 f7d14649 2800ebec  
>    4163544c e7cbd0de f7fda803 4620fefb e8bdb004  
>    4163545c bf0087f0 0006e868 0005581f fffffe58  
>    4163546c 00055830 00050a62 b5f74603 a801460f  
>    4163547c 46164619 4508e9dd febaf7fd 46399801  
>    4163548c fef2f7fe 46026933 f01068f0 d0050f40  
>    4163549c 46294620 f7db18d2 e002ebc8 e9c118d1  
> 
>code around lr:
>    416353a8 00055863 47ffe92d 460c4605 4629a803  
>    416353b8 4616461f ff1ef7fd 46219803 ff56f7fe  
>    416353c8 8094f8df 6ac344f8 2b074605 f020d029  
>    416353d8 bb30fa8b e0374604 07026860 e033d52a  
>    416353e8 0014f104 f844f047 4a1c6923 447a4649  
>    416353f8 20034682 0408e88d f7d169ab 4650ea28  
>    41635408 ea12f7d1 463b4916 f85869aa 49154001  
>    41635418 46329200 01ecf8d4 f7fd4479 2400f977  
>    41635428 4628e012 463a4631 fee2f020 28004604  
>    41635438 e7e7d1d2 9030f8df 44f92003 f7d14649  
>    41635448 2800ebec e7cbd0de f7fda803 4620fefb  
>    41635458 e8bdb004 bf0087f0 0006e868 0005581f  
>    41635468 fffffe58 00055830 00050a62 b5f74603  
>    41635478 a801460f 46164619 4508e9dd febaf7fd  
>    41635488 46399801 fef2f7fe 46026933 f01068f0  
>    41635498 d0050f40 46294620 f7db18d2 e002ebc8

#### Version of Realm and tooling
Realm version(s): 2.0.2

Android Studio version: 2.2.2

Which Android version and device: Android 4.4.2, Motorola Razr HD

**Comment by beeender** [comment]
That is very strange, but after #3643 merged, this part of code should be the same with before. Can you help to try after we merged #3643 ?

**Comment by FrancescoCapari** [comment]
I will try to contact the specific customer to see if he is able to co-operate on this - currently I made a version with realm 1.X for Motorola Razr HD devices as 2.X is not currently working for more of them.

**Comment by kneth** [comment]
@FrancescoCapari Please report back when you know if you can get the customer to help,

**Comment by FrancescoCapari** [comment]
Verified by the customer - working correctly on realm 2.1.1 on Motorola Razr. Thanks guys, issue resolved.
