### ISSUE TITLE
Rx off thread loading memory leak

### ISSUE THREAD

**Issue by gvoltr** [realm/realm-java#3672]
Hello guys, I will be very grateful for any help in understanding this issue.

I really enjoy the way I can async subscribe to data changes with Rx, but I have next situation - I need to convert RealmObjects to another objects from my project. Because the count of objects is huge, I want to do this conversion in off thread also and subscribe to all this stuff from Main thread.

So I am trying to do something like this:
```kotlin
 val workerThreadScheduler = AndroidSchedulers.from(threadManager?.getDBThread()?.looper)
 subscription = Observable.defer {
            Log.d(LOG_TAG, "create realm in ${Thread.currentThread().name}")
            Observable.just(Realm.getDefaultInstance())
        }.flatMap { realm ->
            realm.where(Person::class.java)
                    .findAll()
                    .asObservable()
                    .doOnSubscribe { Log.d(LOG_TAG, "subscribe in ${Thread.currentThread().name}") }
                    .doOnUnsubscribe {
                        Log.d(LOG_TAG, "unsubscribe and close realm in ${Thread.currentThread().name}")
                        realm.close()
                    }
                    .map { persons ->
                        val emails = ArrayList<String>()
                        for (person in persons) emails.add(person.email)
                        return@map emails
                    }
        }
                .subscribeOn(workerThreadScheduler)
                .unsubscribeOn(workerThreadScheduler)
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe { emails -> Log.d(LOG_TAG, "got emails ${emails.size}") }
```

Here I am trying to subscribe to RealmResults from my own `HandlerThread` with looper, so that way I can manipulate with RealmObjects in off thread. I subscribe, unsubscribe, create and close Realm instance in this thread, ` .doOnUnsubscribe` method fired.

The code behaves exactly as I want, except all RealmResults are leaking.

Full example project is here https://github.com/gvoltr/android-realm-leak/tree/master/RealmLeakTest

Realm version: 2.0.2

**Comment by Zhuinden** [comment]
If you really can't avoid copying from your zero-copy database, then I'd recommend this setup for copying your objects out:  http://stackoverflow.com/questions/38981751/android-kotlin-realm-proper-way-of-query-return-unmanaged-items-on-bg-thread/38983203#38983203

It's tried and tested in the sense that this is the only way I could get it to do what I wanted it to do.

**Comment by gvoltr** [comment]
First of all I really benefit from zero-copy database, because for example in my original app I have large RealmContact model, but when I load all contacts to display them in list I take only few fields and build SimpleContact from them.

I know about solution that avoids `asObservable` but I really want to use it and listen for changes.

I updated example project a bit,  so now it display the leaking and not leaking way.
The difference is that when I reuse `HandlerThread` instance and keeping it alive leak happen. When I use new instance of HandlerThread each time and call ` thread.quit()` in ` .doOnUnsubscribe` it works ok, but I have to create a lot of threads.

**Comment by zaki50** [comment]
@gvoltr I don't think you need to make SimpleContact since Realm does not load any field value until the field value is actually referenced.

**Comment by Zhuinden** [comment]
(which also means you currently **are** loading **every** field value that you map just for the mapping itself)

**Comment by gvoltr** [comment]
What is the problem to have layer of abstraction above DB module with realm?

**Comment by Zhuinden** [comment]
@gvoltr other than partly eliminating the benefits of a zero-copy-database by evaluating the entire result set immediately when creating the list of `SimpleContact`, rather than just when each element is accessed/necessary to be read, nothing :slightly_smiling_face: 

Don't forget, you only read fields when you actually access them. Whether the object has 10 fields or 2000 doesn't matter unless you actually read from all those fields. But to build the `SimpleContact` list, you're accessing the fields for each element in the result set, thus having to iterate and read out every element even when you're not showing them yet.

**Comment by gvoltr** [comment]
I understand. And I have my own reasons to do it that way. My question is about memory leak, not architecture. Can you help me with this?

**Comment by cmelchior** [comment]
Hi @gvoltr. This could be related to https://github.com/realm/realm-java/issues/3552.
I just discovered a bug that would result in RealmResults leaking even though you unsubscribe from them.

**Comment by cmelchior** [comment]
2.1.0 was just released with a fix for this.
