### ISSUE TITLE
APK is 1.5MB bigger on 2.0.2 than on 1.2.0

### ISSUE THREAD

**Issue by Jeff11** [realm/realm-java#3681]
#### Goal

Using the newest version of Realm without adding 1.5 MB to APK size. I'm comparing release builds with proguard enabled.
#### Expected Results

An APK that is not 1.5 MB bigger
#### Actual Results

An APK that is 1.5 MB bigger
#### Steps & Code to Reproduce

Update from Realm 1.2.0 to 2.0.2
#### Version of Realm and tooling

Realm version(s): 2.0.2

Realm sync feature enabled: no

Android Studio version: 2.2.2

Relates to #3506

**Comment by kneth** [comment]
We added features in version 2.0. But we are aware of the situation. We wish to upgrade to latest NDK to get a better compiler and linker (see #3506) so reduce the size.

**Comment by cmelchior** [comment]
I'm folding this into #3506, since we would not tackle this independently from that anyway.
