### ISSUE TITLE
RealmObject with Retrofit 2

### ISSUE THREAD

**Issue by NorbertSzydlowski** [realm/realm-java#3686]
Hi,

I have one problem and I don't know how to fix this.

I have got realmObject's that I need send to my server via Retrofit.

If I send data to server all fields are null because RealmObject use RealmProxy.

Is any way to get RealmObject fileds with data instead RealmProxy?

**Comment by cmelchior** [comment]
Yes, you can use `realm.copyFromRealm(obj)`, which will give you a in-memory copy. Which will allow GSON (I assume that is what you use) to read the fields.

**Comment by Zhuinden** [comment]
But you can also use another parser that reads from fields directly rather than via reflection, like LoganSquare.

**Comment by beeender** [comment]
@NorbertSzydlowski Hope above comments solved your issue. Thanks for the feedback!
