### ISSUE TITLE
Hi I am geeting  this error java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.abl.myrealmapplication/com.example.abl.myrealmapplication.activity.MainActivity}: java.lang.NullPointerException: No default RealmConfiguration was found. Call setDefaultConfiguration() first

### ISSUE THREAD

**Issue by YdRakesh** [realm/realm-java#3688]
public class RealmController {     private static RealmController instance;     private final Realm realm;      public RealmController(Application application) {         realm = Realm.getDefaultInstance();     }     public static RealmController with(Fragment fragment){         if(instance==null){             instance=new RealmController(fragment.getActivity().getApplication());         }         return instance;     }     public static RealmController with(Activity activity){         if(instance==null){             instance=new RealmController(activity.getApplication());         }         return instance;     }     public static RealmController with(Application application){         if(instance==null){             instance=new RealmController(application);         }         return instance;     }     public static RealmController getInstance(){         return instance;     }     public Realm getRealm(){         return realm;     }     public void refresh(){         realm.refresh();     }     public void clearAll(){         realm.beginTransaction();         realm.clear(Book.class);         realm.commitTransaction();     }     public RealmResults<Book> getBook(){         return realm.where(Book.class).findAll();     }     public Book getBook(String id){         return realm.where(Book.class).equalTo("id",id).findFirst();     }     public boolean hasBook(){         return !realm.allObjects(Book.class).isEmpty();     }     public RealmResults<Book>queryedBooks(){         return realm.where(Book.class).contains("author","Author 0").or().contains("title","Realm").findAll();     } }

**Comment by kneth** [comment]
Please reformat the code so it is readable. And please use our issue template.

**Comment by Zhuinden** [comment]
Ah, I remember this code, it's that tutorial thing from http://www.androidhive.info/2016/05/android-working-with-realm-database-replacing-sqlite-core-data/

That code is garbage. That tutorial is lying to you. The latest Realm version is 2.0.3, not frickin 0.82.1.

If you wanted to stick to a stable version, you'd use 1.1.1.

Either way, that tutorial is garbage, it should be purged by the wrathful blaze of a thousand Suns. 

Refer to this code instead:  https://github.com/Zhuinden/realm-book-example

**Comment by kneth** [comment]
Thanks @Zhuinden. 

@YdRakesh I will close the issue. Don't hesitate to create a new issue if you have a question but please use the issue template in the future.
