### ISSUE TITLE
Java examples don't compile due to version.txt mismatch

### ISSUE THREAD

**Issue by dsjstc** [realm/realm-java#3690]
The realm-examples gradle script references the root version.txt, which currently contains `2.2.0-SNAPSHOT`.  It sets `classpath "io.realm:realm-gradle-plugin:${currentVersion}"`.  jcenter does not have any such version of the plugin.  This results in the error:

    Gradle sync failed: Could not find io.realm:realm-gradle-plugin:2.2.0-SNAPSHOT.
           Searched in the following locations:
           file:/opt/android-studio-22b2/gradle/m2repository/io/realm/realm-gradle-plugin/2.2.0-SNAPSHOT/maven-metadata.xml
           etc.
           etc.
           https://jcenter.bintray.com/io/realm/realm-gradle-plugin/2.2.0-SNAPSHOT/maven-metadata.xml
           https://jcenter.bintray.com/io/realm/realm-gradle-plugin/2.2.0-SN...

To compile, one must explicitly specify the 2.0.2 version of the plugin.

**Comment by cmelchior** [comment]
If you just clone your repository you need to install it locally. You can run `./gradlew installRealmJava` from the top-level directory. This is also described in our README: https://github.com/realm/realm-java/blob/master/README.md#examples

**Comment by dsjstc** [comment]
Please consider updating the docs then.  The top of the examples section says "You just Import Project in Android Studio and hit run."   Obviously, that's not correct.   https://realm.io/docs/java/latest/#examples

**Comment by cmelchior** [comment]
Yes, we should definitely do that. Thanks for pointer.
