### ISSUE TITLE
Investigate how Google Play backup/store works

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#3694]
While adding a section about `writeCopyTo` for the docs I started thinking about Google Play Services Backup/Restore.

 We should investigate how it actually works in detail. If it takes a backup of an open file or restore it overriding an existing file, it might explain some of the weird Illegal File errors we are seeing from time to time.

Also having it documened how it actually works also be beneficial.

**Comment by cmelchior** [comment]
According to this: https://developer.android.com/guide/topics/data/autobackup.html
Auto-backup will kill the app before doing backup and restore is done before the app is available to users. This means there shouldn't be a chance of app code interfering with backup/restore. Only limitation relevant for us is the 25 MB limit.

**Comment by beeender** [comment]
fold to #2603
