### ISSUE TITLE
How to perform an update operation

### ISSUE THREAD

**Issue by lizixian18** [realm/realm-java#3701]
How to perform an update operation，the  document is unclear.。

**Comment by Zhuinden** [comment]
1.) start a transaction (use `executeTransaction`) 

2.) get element by id

3.) modify element

4.) commit transaction (done by `executeTransaction` automatically)

**Comment by cmelchior** [comment]
Hi @lizixian18 
You can read about transactions here: https://realm.io/docs/java/latest/#writes
And there is an example of how to write/update here: https://github.com/realm/realm-java/blob/master/examples/introExample/src/main/java/io/realm/examples/intro/IntroExampleActivity.java#L108

Apart from that we have the `copyToRealm()` and `insertOrUpdate()` methods for overriding Realm data with data from e.g. a JSON API. 

Javadoc for those are here:
https://realm.io/docs/java/latest/api/io/realm/Realm.html#copyToRealmOrUpdate-E-
https://realm.io/docs/java/latest/api/io/realm/Realm.html#insertOrUpdate-io.realm.RealmModel-

An example using Retrofit/Realm is here as well:
https://github.com/realm/realm-java/blob/master/examples/newsreaderExample/src/main/java/io/realm/examples/newsreader/model/network/NYTimesDataLoader.java#L92

**Comment by lizixian18** [comment]
thanks @Zhuinden @cmelchior
