### ISSUE TITLE
Realm Migration Crash

### ISSUE THREAD

**Issue by Sutirth** [realm/realm-java#3705]
#### Goal

Migration by creating new table

#### Expected Results

successful migration

#### Actual Results

    Caused by: io.realm.exceptions.RealmMigrationNeededException: Invalid type 'int' for field 'groupStatus' in existing Realm file.
           at io.realm.GroupWeeklyDBRealmProxy.validateTable(GroupWeeklyDBRealmProxy.java:324)
           at io.realm.DefaultRealmModuleMediator.validateTable(DefaultRealmModuleMediator.java:114)
           at io.realm.Realm.initializeRealm(Realm.java:280)
           at io.realm.Realm.createAndValidate(Realm.java:248)
           at io.realm.Realm.createInstance(Realm.java:228)
           at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:126)
           at io.realm.Realm.getDefaultInstance(Realm.java:160)

#### Code Sample

    public class GroupWeeklyDB  extends RealmObject{
    
        @PrimaryKey
        private int groupId;
        private String groupName;
        private String groupDescription;
        private int groupStatus;
        private boolean hasImage;
        private int sweatPoints;
        private long steps;
        private int rank;
        private float percentile;
        private int noOfUsers;
        private boolean isCurrentUserPartOfGroup;
        private boolean isCurrentUserOwner;
    }

    if(oldVersion == 33){
                    if(!schema.contains("GroupWeeklyDB")) {
                        schema.create("GroupWeeklyDB")
                                .addField("groupId", int.class, FieldAttribute.PRIMARY_KEY)
                                .addField("groupName", String.class)
                                .addField("groupDescription", String.class)
                                .addField("groupStatus", int.class)
                                .addField("hasImage", boolean.class)
                                .addField("sweatPoints", int.class)
                                .addField("steps", long.class)
                                .addField("rank", int.class)
                                .addField("percentile", float.class)
                                .addField("noOfUsers", int.class)
                                .addField("isCurrentUserPartOfGroup", boolean.class)
                                .addField("isCurrentUserOwner", boolean.class);
                    }
    
                    oldVersion++;
                }

P.S I had earlier written groupStatus as String.class (by mistake) after changing it to int and rebuilding the app it sill crashes

#### Version of Realm and tooling
Realm version(s): 2.1.0

Realm sync feature enabled: no

Android Studio version: ? 2.2

Which Android version and device: Nexus 6p

**Comment by Zhuinden** [comment]
Have you tried removing the field if it exists, and then adding the `int` field again?

**Comment by Sutirth** [comment]
If i try to remove the field from table and migration both. It throws me error no. of field mismatch expected 12 but got 11

**Comment by Sutirth** [comment]
Issue Solved: Apparently I had to make the field String in table again in next iteration had to remove the field
