### ISSUE TITLE
Realm-Transformer crashes if you have a class that ends with `RealmProxy` but isn't an actual proxy generated by Realm

### ISSUE THREAD

**Issue by Zhuinden** [realm/realm-java#3709]
http://stackoverflow.com/questions/40258259/cannot-invoke-method-hasannotation-on-null-object/40284179#40284179

The transformer attempts to access `superclass` but it is not guaranteed to exist if you yourself create a class that ends with the name `RealmProxy`.

**Comment by cmelchior** [comment]
Thanks for finding this 😄
