### ISSUE TITLE
Enforce TLS if it was used for authentication

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#3710]
Right now it is possible to e.g login to ROS using `https` while using `realm` as the sync protocol.
While technical possible to use `https` for auth and `realm` for sync, it is counter productive and against security best practises.

We should enforce people using `realms` if using `https` by throwing an `IllegalArgumentException` if it happens.

**Comment by nhachicha** [comment]
@cmelchior I'm not sure this is a decision we should enforce at the app level, IMO this depends more on the sysadmin/network topology 

You can have the auth server outside a DMZ where you should use TLS, whereas the sync server is inside a DMZ for instance?, I know this sounds silly but it should be up to the sysadmin to make this decision

maybe the best effort in our case is to log a warning?

**Comment by cmelchior** [comment]
To be honest, I cannot remember what sparked this issue, so if we have concern implementing it, I'm fine just closing it until a use case surfaces. As you said, it is really something that should be decided outside the app.
