### ISSUE TITLE
Fatal signal 11 (SIGSEGV) at 0x5bb29ffe (code=2) on API 17 (4.2.2)

### ISSUE THREAD

**Issue by maysaini** [realm/realm-java#3711]
When I try to use 

Realm realm = Realm.getDefaultInstance(); 

the app gives that error while it runs well on 4.4 and above

**Comment by cmelchior** [comment]
There should be more output in Logcat. Can you post that as well?
If that is not the case. Is it something you can reproduce?

**Comment by maysaini** [comment]
This is what Im getting everytime I run it on a 4.2.2 device . In this case the device is Samsung Tab3 Neo

Here is the stacktrace

Fatal signal 11 (SIGSEGV) at 0x5bb29ffe (code=2), thread 29349

**Comment by cmelchior** [comment]
What version of Realm are you using?

**Comment by maysaini** [comment]
2.0.2

**Comment by cmelchior** [comment]
Please try to add the following when you init 
```
Realm.init(context);
RealmLog.clear();
RealmLog.add(new AndroidLogger(Log.VERBOSE));
```

and post the entire logcat from start.

**Comment by maysaini** [comment]
Here:

10-28 01:55:11.210 30902-30902/com.raremediacompany.vihaan V/REALM:  --> Java_io_realm_internal_SharedRealm_nativeCreateConfig
10-28 01:55:11.210 30902-30902/com.raremediacompany.vihaan V/REALM:  --> Java_io_realm_internal_SharedRealm_nativeGetSharedRealm 1539538208
10-28 01:55:11.210 30902-30902/com.raremediacompany.vihaan V/REALM:  --> Java_io_realm_internal_SharedRealm_nativeCloseConfig 1539538208
10-28 01:55:11.210 30902-30902/com.raremediacompany.vihaan V/REALM:  --> Java_io_realm_internal_SharedRealm_nativeHasTable 1573429136
10-28 01:55:11.210 30902-30902/com.raremediacompany.vihaan V/REALM:  --> Java_io_realm_internal_SharedRealm_nativeCloseSharedRealm 1573429136
10-28 01:55:11.218 30902-30902/com.raremediacompany.vihaan V/REALM:  --> Java_io_realm_internal_SharedRealm_nativeCreateConfig
10-28 01:55:11.218 30902-30902/com.raremediacompany.vihaan V/REALM:  --> Java_io_realm_internal_SharedRealm_nativeGetSharedRealm 1539538208
10-28 01:55:11.218 30902-30902/com.raremediacompany.vihaan V/REALM:  --> Java_io_realm_internal_SharedRealm_nativeGetVersion 1523347560
10-28 01:55:11.218 30902-30902/com.raremediacompany.vihaan V/REALM:  --> Java_io_realm_internal_SharedRealm_nativeCloseConfig 1539538208
10-28 01:55:11.218 30902-30902/com.raremediacompany.vihaan V/REALM:  --> Java_io_realm_internal_SharedRealm_nativeIsClosed 1523347560
10-28 01:55:11.218 30902-30902/com.raremediacompany.vihaan V/REALM:  --> Java_io_realm_internal_SharedRealm_nativeGetVersion 1523347560
10-28 01:55:11.226 30902-30902/com.raremediacompany.vihaan V/REALM:  --> Java_io_realm_internal_SharedRealm_nativeGetVersion 1523347560
10-28 01:55:11.226 30902-30902/com.raremediacompany.vihaan V/REALM:  --> Java_io_realm_internal_SharedRealm_nativeIsClosed 1523347560
10-28 01:55:11.226 30902-30902/com.raremediacompany.vihaan V/REALM:  --> Java_io_realm_internal_SharedRealm_nativeBeginTransaction 1523347560
10-28 01:55:11.226 30902-30902/com.raremediacompany.vihaan V/REALM:  --> Java_io_realm_internal_SharedRealm_nativeGetVersion 1523347560
10-28 01:55:11.226 30902-30902/com.raremediacompany.vihaan V/REALM:  --> Java_io_realm_internal_SharedRealm_nativeSetVersion 1523347560
10-28 01:55:11.234 30902-30902/com.raremediacompany.vihaan A/libc: Fatal signal 11 (SIGSEGV) at 0x5bb29ffe (code=2), thread 30902 (acompany.vihaan)

**Comment by cmelchior** [comment]
Thanks. It seems the same error as this one: https://github.com/realm/realm-java/issues/3651.
Do you have the model number of your device?

**Comment by maysaini** [comment]
Samsung Tab 3 Neo

**Comment by cmelchior** [comment]
Ok. It is the exact same device as in #3651 then. I'll fold this into that one then.

We haven't found the root cause yet. Mostly because we haven't been able to reproduce this on any other device. Right now there is no workaround unfortunately.

**Comment by diegomontoya** [comment]
@cmelchior Some related info while testing a local Realm 1.2.0 fork (realm core 1.5.1) which back-ports some of the 2.x branch bug fixes back to 1.5.1 core. 

We compiled and tested both our custom 1.5.1 core via ndk r10e and r12b.  r12b build crashes with similar SIGSEGV the moment we attempt to load a realm db on 2 out of 3 Android 4.2.2 devices which this bug references. r10e build was perfectly fine.  Non-4.2.2 devices ran both ndk builds libs fine thus far. 

Crashing 4.2.2 devices

1) Samsung GT-I9118 (Broadcom BCM28155 cpu)
2) Samsung SM-G3818 (Qualcomm Snapdragon 200 MSM8225Q cpu)

This 4.2.2 device did not crash
1) ZTE V818 (MT-6572 cpu)

Is the Realm 2.X release build using newer android NDK?

**Comment by Zhuinden** [comment]
@diegomontoya no it is still using r10e, but it also includes the so-called [realm-object-store](https://github.com/realm/realm-object-store)

**Comment by lmonte** [comment]
i have the same problem now! Any information about that?

**Comment by Zhuinden** [comment]
@lmonte device type? Realm version? relevant code?

**Comment by jehad-suliman** [comment]
Same problem
Device : Samsung S3 Mini GT-I8200
Android version : 4.2.2 
Realm Version : 2.3.1  

is there any solution ??

**Comment by Zhuinden** [comment]
https://github.com/realm/realm-java/pull/4402 might fix this
