### ISSUE TITLE
Realm mode class can not extends

### ISSUE THREAD

**Issue by carl1990** [realm/realm-java#3715]
I have a Class Name `User` extends from `RealmObject`,  then I have a class name `CurrentUser` extends User,But there happen error when compile with info `Error:(9, 8)  Realm model classes must either extend RealmObject or implement RealmModel to be considered a valid model class`.

how can I save this two class data into DB by do not copy the parent Class filed into subClass

**Comment by Zhuinden** [comment]
Inheritance in RealmObjects is not supported https://github.com/realm/realm-java/issues/761

**Comment by cmelchior** [comment]
Realm doesn't support inheritance yet ( #761 ). You have two options:

1) Either copy fields (you can still implement a shared interface)
2) Use composition:

```
public class CurrentUser extends RealmObject {
  public User user;
  // ... current user fields
}
```
