### ISSUE TITLE
Sync Integration Tests should also install the Auth Server

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#3716]
Right now our integration tests: https://github.com/realm/realm-java/tree/master/realm/realm-library/src/syncIntegrationTest/java/io/realm/objectserver only installs the Object Server. 

This is fine for testing sync protocol interaction, but some recent features depend on the the Auth Server being installed as well (Permissions). 

We need to find a way to install both the Object Server and Auth Server for integration tests.

**Comment by cmelchior** [comment]
This might already be happening. We just need to verify it.

**Comment by beeender** [comment]
I am pretty sure this one has been there already. But we do need more tests about auth part.

**Comment by cmelchior** [comment]
Integration tests are working
