### ISSUE TITLE
Mediator not generated

### ISSUE THREAD

**Issue by RobGThai** [realm/realm-java#3719]
I tried to follow kotlin-example but I can't get it to work.

If I use `Realm.getDefaultInstance`, it tell me the object is not part of schema.
If I set module manually, I get `ClassNotFoundException` on `Mediator`.

I did check issues both here and SO but I can't seem to fix it. I updated everything to the latest version including `kotlin_version = '1.0.4'` and `realm_version = '2.1.1'`. I also tried the `kotlin.incremental=false` trick but problem still persist.

The model class extends `RealmObject`, I even added `@RealmClass` in afterward when all else fail but still not working.

Here's my repo: https://github.com/RobGThai/kotlin-realm-test

I'm running this on `Galaxy Tab A` with `Android 5.0.2`.

**Comment by RobGThai** [comment]
It seems like Gradle plugin is not working correctly. I manually added kapt and the classes were generated correctly.

```
kapt 'io.realm:realm-annotations:2.1.1'
kapt 'io.realm:realm-annotations-processor:2.1.1'
```

Here's the Android Studio build I'm using.

```
Android Studio 2.2.2
Build #AI-145.3360264, built on October 18, 2016
JRE: 1.8.0_112-release-b05 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```

**Comment by zaki50** [comment]
Could you remove `com.neenbedankt.android-apt` plugin?
If it was applied, Realm's plugin adds its processor to `apt` configuration instead of `kapt` configuration.

**Comment by kneth** [comment]
@RobGThai Did the suggestion above help you?

**Comment by RobGThai** [comment]
@zaki50 @kneth Yes, removing it fix the problem. Thank you very much.

**Comment by klein-artur** [comment]
@zaki50 

> Could you remove com.neenbedankt.android-apt plugin?

What is if I need this plugin because I need it for other dependencies. Is there another workaround?

**Comment by Zhuinden** [comment]
> What is if I need this plugin because I need it for other dependencies. Is there another workaround?

If you're using Kotlin, then you don't need android-apt.

You only need kapt.

**Comment by zaki50** [comment]
@klein-artur Writing the model classes in Java maybe?

**Comment by alexander-fischer** [comment]
@zaki50 for me, this doesn't work.

**Comment by Zhuinden** [comment]
@alexander-fischer what have you tried?

Realm version, Gradle configuration (plugin apply and their order), etc.

**Comment by NitroG42** [comment]
Hello, the problem is still occuring if we use Kotlin KAPT 3 (apply plugin 'kotlin-kapt')
Reverting to kapt 1 (remove apply plugin kapt and add kapt {generateStubs = true}) seems to fix the issue but it's annoying.
I'll try to make a sample and maybe open another issue.

**Comment by Zhuinden** [comment]
Do you apply Kotlin kapt before Realm android?

**Comment by NitroG42** [comment]
Yes, I did it + clean project
