### ISSUE TITLE
Trying to delete Realm but somehow an instance of realm is open

### ISSUE THREAD

**Issue by mihirjoshi21** [realm/realm-java#3720]
It is only happening in like 1 percent of the production devices.

I have an old pre-shipped realm file which I want to replace with the new version of the realm file after copying user data from the old file.

```
Realm realm = null;
try {
 realm = Realm.getDefaultInstance();

 RealmQuery < WordHistoryModel > query = realm.where(WordHistoryModel.class);
 RealmResults < WordHistoryModel > result = query.findAllSorted("timeLong", Sort.DESCENDING);
 if (!result.isEmpty()) {
  mHistory = ProjectUtil.getGsonInstance().toJson(result);
 }
} catch (Exception realmError) {
 realmError.printStackTrace();
 Crashlytics.logException(realmError);
}
if (realm != null && !realm.isClosed()) {
 realm.close();
}
}

Realm.deleteRealm(ProjectUtil.getRealmConfiguration(ProjectUtil.getSharedPreferencesInt(mActivity,
 AppConstants.DATABASE_VERSION)));
Realm.removeDefaultConfiguration();
```

This is on the splash screen and the first time when I am opening the realm instance but when I am deleting the realm file there is an illegalStateException that the realm file is still open.
Is there a way to release all instances from realm cache?

**Comment by Zhuinden** [comment]
Have you tried putting realm.close() in `finally` instead?

**Comment by mihirjoshi21** [comment]
No I didn't but I kept it outside try catch block so anyhow it should work right?

**Comment by beeender** [comment]
@mihirjoshi21 Do you have any other activity/service is opening Realm instance? The code you show is in the Application or the splash activity? Does `Crashlytics.logException(realmError);` give us more information about this? What is the backtrace you got when `deleteRealm` failed?

**Comment by mihirjoshi21** [comment]
@beeender Here is the crash log http://crashes.to/s/38169a0513e

**Comment by beeender** [comment]
@mihirjoshi21 I just checked your crash log, `com.conem.app.pocketthesaurus.display.ActivitySplash$1.doInBackground (ActivitySplash.java:98)` this shows that the Realm is actually opened in a background thread (async task). Could it be possible a Realm instance is opened somewhere in the UI thread before? eg. in the `Application.onCreate()` or `SplashActivity.onCreate()` and so on?

**Comment by mihirjoshi21** [comment]
So I updated my app closing a realm instance opened by the Service. From past two days, there is no bug. I am waiting for few more days to see if it's resolved or not.

**Comment by kneth** [comment]
@mihirjoshi21 Sounds great. Please either update or close (if fixed) issue.

**Comment by mihirjoshi21** [comment]
@kneth Just saw two more crashes http://crashes.to/s/38169a0513e
I needed a way to close all realm instances. This is generally happening when the user is updating the app and the old database is getting deleted.

**Comment by kneth** [comment]
@mihirjoshi21 Is the app upgraded using Google Play Store or an alternative store?

**Comment by mihirjoshi21** [comment]
Yes play store mostly. But I don't have any way to track it.

**Comment by cmelchior** [comment]
Hi @mihirjoshi21 What is the app logic for showing the splash screen? Perhaps there is something in that logic that triggers the splash screen even though it shouldn't?

Also note that you can use `Realm.getLocalInstanceCount(config)` and `Realm.getGlobalInstanceCount(config)` to get an idea about how many open Realm instances you have either on the current thread or across all threads. Perhaps that can give some hints to why this is happening.

**Comment by mihirjoshi21** [comment]
Instead of `Realm.getLocalInstanceCount(config)` is there a way to  close all those instances.

**Comment by Zhuinden** [comment]
@mihirjoshi21 that is your responsibility to do in your code, although the documentation is quite clear on the best practices regarding that.

**Comment by kneth** [comment]
@mihirjoshi21 Did you find a solution to close your Realm instances?

**Comment by Zhuinden** [comment]
Technically he should use `finally { if(realm != null) { realm.close(); } }`.

**Comment by mihirjoshi21** [comment]
You can close this issue. An instance was opened by the service. I haven't faced this problem from the last couple of builds.

**Comment by kneth** [comment]
@mihirjoshi21 Thanks for the update.
