### ISSUE TITLE
Firebase POJO's inherits realm data properties 

### ISSUE THREAD

**Issue by harisvsulaiman** [realm/realm-java#3723]
Realm and firebase together causes problems for me.
Manage, loaded, and valid fields are are copied over to firebase .
![screenshot from 2016-10-29 16 33 40](https://cloud.githubusercontent.com/assets/6212932/19829101/e234e21c-9df5-11e6-8443-f2051c0ddfaa.png)

**Comment by Zhuinden** [comment]
I'm not entirely sure how you're saving the proxies themselves over to Firebase.

**Comment by cmelchior** [comment]
Those properties are part of the `RealmObject` base class. We cannot really do much about how Firebase decides which fields to include. You can however use our `RealmModel` interface instead of extending `RealmObject`. This would prevent this from happening: https://realm.io/docs/java/latest/#realmmodel-interface

**Comment by harisvsulaiman** [comment]
@Zhuinden i'm extending the object from realm object

**Comment by beeender** [comment]
@harisvsulaiman does comments https://github.com/realm/realm-java/issues/3723#issuecomment-257090099 solve your problem?

**Comment by Zhuinden** [comment]
Using RealmModel should fix this

**Comment by harisvsulaiman** [comment]
@beeender haven't tried it. Still prototyping so i dont mind extra fields in the model.
i will migrate to interface soon.

**Comment by Zhuinden** [comment]
Just make sure you don't forget to add `@RealmClass` as well, not just `RealmModel`

**Comment by 3llomi** [comment]
if we can access these methods in **POJO** Class we can exclude it using the `@Exclude` annotation from **Firebase SDK** 
however i can only **override** the **isManaged** method and it has excluded.
can we access the `isValid` and `isLoaded` methods in `POJO `Class?

**Comment by cmelchior** [comment]
That `isManaged` is not final is a bug that we should fix, `isValid` and `isLoaded` is `final` as intented. But if you `extends RealmObject` there is no way to mark these methods as excluded. Instead you should use our `RealmModel` interface as described in https://realm.io/docs/java/latest/#realmmodel-interface
