### ISSUE TITLE
Realm file overwritten on run

### ISSUE THREAD

**Issue by nickdbush** [realm/realm-java#3725]
For some reason today when I ran my app using Android Studio (no instant run) my realm file gets overwritten and all the data is deleted. I checked it out and it isn't missing, or empty, it's just been reset to it's 'initial state'. There is no stacktrace, I'm certain I close all my instances and I don't delete on migrations. It's really starting to slow down development as I have to uninstall the app every time, and then login again. Just closing and restarting the app does not change the database, and no shared preferences get deleted. I'm really sorry I can't be more helpful (and I understand that what you don't just want to be tech support reps) but any help would be greatly appreciated. I can give you access to the repo if that would be of assistance.
## Possible relevant bits of code:

```
        public static final String REALM_FILENAME = "filename.realm";

        RealmConfiguration realmConfiguration = new RealmConfiguration.Builder(this)
                .schemaVersion(SCHEMA_VERSION)
                .name(REALM_FILENAME)
                .migration(new RealmMigration() {
                    @Override
                    public void migrate(DynamicRealm realm, long oldVersion, long newVersion) {
                        if (oldVersion == 1) {
                            // No migrations yet
                        }
                    }
                })
                .build();
        Realm.setDefaultConfiguration(realmConfiguration);
```

```
                realm.beginTransaction();
                for (Lesson lesson : result.lessons) {
                    realm.copyToRealm(lesson);
                }
                try {
                    realm.createAllFromJson(Event.class, getAssets().open("calendar.json"));
                } catch (IOException e) {
                    e.printStackTrace();
                }
                realm.commitTransaction();

```

Apart from this, Realm works properly. This is what is so infuriatingly annoying! 
## To reproduce:
1. Run application once to install on device. Login. Data downloads. Normal. Close, open, pause all works.
2. Make a small change to the codebase so application will install again
3. Application reinstalls, and everything in Realm has gone.
## (Hopefully) helpful info

Realm versions: 1.2.0

Realm sync feature enabled: no

Android Studio version: 2.2.2 (no instant run)

Android version and device: Nexus 6P, Android 7.1.1

Target SDK: 25
Min SDK: 19

**Comment by Zhuinden** [comment]
Are you sure you don't call `realm.deleteAll()` somewhere unexpected?

**Comment by nickdbush** [comment]
No, I don't do any mass deleting (just checked through the entire project). Sorry again for not being more helpful!

**Comment by cmelchior** [comment]
Hi @nickdbush Without further information it is hard to say. Getting access to the repo would help a lot.

**Comment by nickdbush** [comment]
It seems to have fixed itself. I have no idea how, or why, but if it happens. It seems temperamental. I'll get back to you if it decides to start again! Sorry for wasting your time!

**Comment by cuagia** [comment]
I face the same issue, what did you fix it @nickdbush

**Comment by nickdbush** [comment]
Unfortunately no, as it was too intermittent to form a substantial bug report. In the end we dropped Realm and moved to Firebase, but that's an even nastier can of worms.
