### ISSUE TITLE
Unusual Behavior On Delete in realm (listview) 

### ISSUE THREAD

**Issue by SahajRana** [realm/realm-java#3728]
#### Goal

> To make the deletion in realm-listview work properly

#### Actual Results

> Currently, On Deletion of item in listview, the deletion works properly but, after deletion the position of item which which was deleted get replaced by the latest item which was inserted before.

**The realm-listview is used as the messaging chat room containing chats**

#### Steps & Code to Reproduce

> Could't find any solution to it.

#### Code Sample

```java

 mImageViewDeleteSelect.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View view) {
                AlertDialog.Builder builder1 = new AlertDialog.Builder(SingleMessageRoomActivity.this);
                builder1.setMessage("Are you sure");
                builder1.setCancelable(false);
                builder1.setPositiveButton(
                        "Yes!",
                        new DialogInterface.OnClickListener() {
                            public void onClick(DialogInterface dialog, int id) {
                                realm.executeTransaction(new Realm.Transaction() {
                                    @Override
                                    public void execute(Realm realm) {
                                        SparseBooleanArray checked = mListView.getCheckedItemPositions();
                                        for (int ii = 0; ii < checked.size(); ii++) {
                                            if(checked.valueAt(ii)) {
                                                selectedRow = checked.keyAt(ii);
                                                String key = adapter.getItem(selectedRow).getKey();
                                                String OtherEmailPref=adapter.getItem(selectedRow).getChatWith();
                                                RealmResults<MessageRealm> result1 = realm.where(MessageRealm.class).equalTo("chatWith", OtherEmailPref).equalTo("key",key).findAll();
                                                Log.e("SahajLOG", "selected Row--> "+selectedRow+" KEy --> " + key + " result-->" + result1);
                                                result1.deleteAllFromRealm();

                                            }
                                        }
                                        mToolbar1.setVisibility(View.GONE);
                                        Count=0;
                                        mListView.clearChoices();
                                        adapter.notifyDataSetChanged();
                                    }
                                });
                                dialog.cancel();
                            }
                        });
                builder1.setNegativeButton("Cancel", new DialogInterface.OnClickListener() {
                    public void onClick(DialogInterface dialog, int id) {
                        dialog.cancel();
                        mToolbar1.setVisibility(View.GONE);
                        Count=0;
                        mListView.clearChoices();
                        adapter.notifyDataSetChanged();
                    }
                });
                AlertDialog alert11 = builder1.create();
                alert11.setCancelable(false);
                alert11.setCanceledOnTouchOutside(false);
                alert11.show();
            }
        });

````
**before:**
![screenshot_2016-10-31-22-28-11_com rana sahaj myyu](https://cloud.githubusercontent.com/assets/16938202/19863352/f0c5e05e-9fb9-11e6-8606-67f8329fd42e.png)

**on Selection for delete:**
![screenshot_2016-10-31-22-28-30_com rana sahaj myyu](https://cloud.githubusercontent.com/assets/16938202/19863378/0c57a546-9fba-11e6-9274-a5ebbe675983.png)

**After deletion '4' moved in place on '2'**
![screenshot_2016-10-31-22-28-36_com rana sahaj myyu](https://cloud.githubusercontent.com/assets/16938202/19863426/332ebad8-9fba-11e6-8b86-3f27bb6beab8.png)

#### Version of Realm and tooling
Realm version(s): 2.1.1

Realm sync feature enabled: no

Which Android version and device: kitkat

**Comment by Zhuinden** [comment]
Do you ensure a stable sort order using `findAllSorted`? 

Insertion order is not preserved on deletion.

**Comment by SahajRana** [comment]
no i haven't. How can that be done?

**Comment by beeender** [comment]
How did you create your `RealmResults` which is passed to the adapter?

**Comment by Zhuinden** [comment]
The Realm-Cocoa docs mention that 

[Note that the order of Results is only guaranteed to stay consistent when the query is sorted. For performance reasons, insertion order is not guaranteed to be preserved. If you need to maintain order of insertion, some solutions are proposed here.](https://realm.io/docs/swift/latest/#sorting)

And that's what you see here, deletion messes up your insertion order, which means your messages should be sorted.

**Comment by zaki50** [comment]
@SahajRana `resultRealm` in your code is `RealmQuery`, not `RealmResults`.

How do you get `Realm Results` from the `resultRealm`?

**Comment by SahajRana** [comment]
thanks for help, actually @Zhuinden was right, after the use of `findAllSorted()` it sorted the whole list even after deletion

**Comment by kneth** [comment]
@SahajRana I'll close the issue. Don't hesitate to reopen or create new issue if you experience the issue again.
