### ISSUE TITLE
NullPointerException: Null reference used for synchronization. SharedRealm.finalize()

### ISSUE THREAD

**Issue by YaroslavYrm** [realm/realm-java#3730]
#### Actual Results

> E/System: Uncaught exception thrown by finalizer
> E/System: java.lang.NullPointerException: Null reference used for synchronization (monitor-enter)
> 	at io.realm.internal.SharedRealm.finalize(SharedRealm.java:318)
> 	at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:217)
> 	at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:200)
> 	at java.lang.Thread.run(Thread.java:818)

#### Steps & Code to Reproduce

>Was reproduced by client. Appeared multiple times in logcat.
>"Once in a while a popup error message is shown telling that the app has crashed."

#### Version of Realm and tooling
Realm version(s): 2.0.2

Realm sync feature enabled: no

Which Android version and device: Samsung Galaxy A5 (Android 6.0.1)

**Comment by beeender** [comment]
If i remembered correctly, this happens when the construction of `SharedRealm` is interrupted (by exception or something). To suppress this, we can simply check null of the context in the `SharedRealm` 's finalize, or even get rid of the `SharedRealm`'s finalize by adding it to the phantom queue.

**Comment by mbunyard** [comment]
When will v2.3.1 be released/available with this fix?
