### ISSUE TITLE
[Feature Request] Bulk Update

### ISSUE THREAD

**Issue by Zhuinden** [realm/realm-java#3738]
Based on http://stackoverflow.com/q/40382818/2413303

#### Goal

> What do you want to achieve?

#### Expected Results

Update a certain field of every RealmObject in a RealmResults to a certain value.

Something like this:

``` java
    RealmResults<RObj> results = realm.where(RObj.class).findAll();
    results.setValues(RObjFields.DELETED, true);
```

#### Actual Results

There is no such thing even though Realm-Cocoa exists:

``` 
[[RLMRealm defaultRealm] transactionWithBlock:^{
   // all pubs in pubsToDelete will be updated 
   [pubsToDelete setValue:@YES forKeyPath:@"deleted"];
}];
```

#### Version of Realm and tooling
Realm version(s): 2.1.x

**Comment by cmelchior** [comment]
Hi @Zhuinden 
Thanks for the suggestion. We already have an issue tracking this although the name was a bit bad: https://github.com/realm/realm-java/issues/762.

**Comment by Zhuinden** [comment]
@cmelchior gah, I looked for it but didn't find it >.>
