### ISSUE TITLE
Realm crashing when added as system application

### ISSUE THREAD

**Issue by FarhanAhmad** [realm/realm-java#3740]
#### What do you want to achieve?
I am creating a system application which is using realm for database.

#### Actual Results
Exception: Read-only file system in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 81, .

#### Steps & Code to Reproduce
Just made a system app, and on starting the app it crashes on:
Realm realm = Realm.getDefaultInstance();

I first made this a simple user app and installed on android phone using studio. When everything was ok, I moved it to ROM and made it a system app. It has all the permissions signed with platform so permissions is not a problem. Since the error is read-only file system. May be Realm is not able to create its db file on system ! Any help is highly appreciated.

#### Version of Realm and tooling
Realm version(s): 2.0.1 (since with gradle we are only applying plugin in build.grade and not giving any versions so i checked the cache of gradle and 2.0.1 is the version it had downloaded)

Realm sync feature enabled: yes/no 
I don't know !

Android Studio version: 2.2.2

Which Android version and device: Nexus 5

**Comment by Zhuinden** [comment]
You should try the latest version 2.1.0, although some other guy previously reported that SELinux blocked system apps from creating named pipes.

**Comment by cmelchior** [comment]
Hi @FarhanAhmad 
https://github.com/realm/realm-java/issues/3644 describe this issue as well + a workaround. I'll close this as an duplicate so discussion can continue in #3644 .

**Comment by FarhanAhmad** [comment]
sure thanx.
