### ISSUE TITLE
Migrate UserStore interface + implementations to ObjectStore

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#3743]
The ObjectStore has a default implementation for the UserStore. We should use that instead of the `SharedPrefsUserStore`, but at the same time we also still want to support encrypted User Stores.

- [ ] Implement a UserStore that uses the ObjectStores implementation. This might involve refactoring the UserStore interface
- [ ] Consider deprecating/removing `SharedPrefsUserStore`
- [ ] Figure out the impact on the current SecureUserStore implementation.

**Comment by Zhuinden** [comment]
> The ObjectStore has a default implementation for the ObjectStore. 

Oddly tautological 👅

**Comment by cmelchior** [comment]
@nhachicha This is done, right?

**Comment by nhachicha** [comment]
@cmelchior yep only part left is to update the SecureUserStore
