### ISSUE TITLE
about the RealmObject problem

### ISSUE THREAD

**Issue by lizixian18** [realm/realm-java#3745]
Hello!,when my bean extends the RealmObject,there will be this problem：

![image](https://cloud.githubusercontent.com/assets/16240767/19998695/32a47b9c-a2a9-11e6-98ed-ca3928ed83b6.png)

I don`t know why and how to do.

**Comment by Zhuinden** [comment]
You probably have an unsupported field.

The compiler error output would tell you what's wrong, but consider looking at what fields are supported.

https://realm.io/docs/java/latest/#models

**Comment by lizixian18** [comment]
The reason is that I did not write default constructor。

**Comment by Zhuinden** [comment]
Ah. Yeah, you need a default constructor, so that the RealmProxy can inherit it and be created from its class.

**Comment by kneth** [comment]
This question is better asked at StackOverflow (much larger community = faster answer). Please take a look at https://realm.io/docs/java/latest/#limitations
