### ISSUE TITLE
Disable the default RealmModule generation if no realm model/module

### ISSUE THREAD

**Issue by NitroG42** [realm/realm-java#3746]
#### Goal

Some developpers might want to create a library that will use Realm, but won't declare any model or module in it. The problem is that if we don't declare any of them, the compilation will failed because the generated Mediator will contains no classes and throw a `getMissingProxyClassException(clazz);`
The same issue can happens (I think) if we have a Library that declare the model in Realm + a LibModule, and we use only the LibModule in the application, without declaring any more models.

#### Expected Results

A flag in build.gradle or a check that disable the generation of realm class or module for project that use Realm without declaring any of both.

**Comment by cmelchior** [comment]
Hi @NitroG42 

If have neither any modules nor model classes the annotation processor shouldn't run (since there is no annotations to trigger it). Are you seeing otherwise?

**Comment by NitroG42** [comment]
Yes, I should have made a bug report instead because : It works in Java (no generation), but in kotlin it does generate the Mediator, even without any realm annotation.

**Comment by cmelchior** [comment]
Fixed by #3749
