### ISSUE TITLE
about the findAllAsync() and findAll() problem

### ISSUE THREAD

**Issue by lizixian18** [realm/realm-java#3756]
hello，my problem is that :

I have two parameter： day = 8 and month = 11。

and the data source have two data：

year=2016, month=11, day=8
year=2016, month=11, day=9

so,when I used 
```
mRealm.where(Example.class).equalTo("day", day).equalTo("month", month).findAllAsync();
```
the result is all the data , so is wrong，
but when I used 
```
mRealm.where(Example.class).equalTo("day", day).equalTo("month", month).findAll();
```
the result is 

year=2016, month=11, day=8， so is true,

so why does this happen?

**Comment by Zhuinden** [comment]
Asynchronous queries take some time to be evaluated, and you must add a `RealmChangeListener` to be notified of when it's done.

But if you use synchronous transactions on the UI thread, then strange things can happen to async queries. Do you by chance have any synchronous transactions on the UI thread? It is not recommended.

**Comment by lizixian18** [comment]
I used isLoaded() to check if the query has completed，but the result is the same。

**Comment by lizixian18** [comment]
if used the RxJava，can not add a RealmChangeListener？

**Comment by kneth** [comment]
Please post more code so we have an idea of the context.

**Comment by lizixian18** [comment]
OK，this is my bean：
```
public class ExpRecord extends RealmObject {
    public String year;
    public String month;
    public String day;
    public long time;
}
```
my  parameter is month = 11  day = 08 and the data source have two data：
```
year=2016, month=11, day=08
year=2016, month=11, day=09
```

![](https://cloud.githubusercontent.com/assets/16240767/20092425/28439f7a-a5d3-11e6-9720-5ecfe1e2c736.png)

the result is：

![](https://cloud.githubusercontent.com/assets/16240767/20092445/3b3470f0-a5d3-11e6-85e4-3bbd147d6758.png)

**Comment by cmelchior** [comment]
Do you have  a background thread that is writing data at the same time? or how did the data come into the Realm?

**Comment by lizixian18** [comment]
No，just query the data。

**Comment by Zhuinden** [comment]
You're supposed to use `findAllSortedAsync()` instead of `findAllAsync().sort()` because you're sorting an unloaded result set.

**Comment by kneth** [comment]
@lizixian18 I believe that the comment above solves your issue.
