### ISSUE TITLE
RealmChangeListener stops receiving updates

### ISSUE THREAD

**Issue by patrickhammond** [realm/realm-java#3759]
#### Goal

> RealmChangeListener stops receiving updates to objects added from another thread/realm instance.

#### Expected Results

> RealmChangeListener should continue to receive updates as new objects are added.

#### Actual Results

>  RealmChangeListener stops receiving updates after a period of time/multiple calls.  In the demo project below the listener stops receiving updates fairly quickly when objects are added on a separate thread, but takes a little longer (still less than 1min) when added on the same thread.

#### Steps & Code to Reproduce

I've put together a sample project (below) that reproduces the issue and have put together a screencast (https://cl.ly/1N1N2t282S2C) demonstrating the issue of adding.

#### Code Sample

Project demonstrating the issue:
https://github.com/patrickhammond/RealmChangeListenerIssue

#### Version of Realm and tooling
Realm version(s): reproduced against 2.1.1, 1.2.0, and 1.1.1

Realm sync feature enabled: no

Android Studio version: 2.2.2

Which Android version and device: Nexus 6P with Android 7.1.1, emulator with Android 7.0

**Comment by Zhuinden** [comment]
You don't retain a strong reference to

        RealmResults<Unique> results = realm.where(Unique.class).findAll();

You should have a field

        RealmResults<Unique> results;

and then add change listener to that

    results = realm.where(Unique.class).findAll();
    results.addChangeListener(new RealmChangeListener<RealmResults<Unique>>() {
        @Override
        public void onChange(RealmResults<Unique> element) {
            handleResults(element);
        }
    });

Personally I also tend to make the RealmChangeListener into a field variable.

**Comment by patrickhammond** [comment]
That was it.  Thank you!

Digging deeper into the docs I see the strong reference pattern as an example in https://realm.io/docs/java/latest/#notifications.  There is probably also value in updating the sample code in https://realm.io/docs/java/latest/#auto-updating-results to call out that the results should be kept as a strong reference.  Possibly also a lint check?

**Comment by Zhuinden** [comment]
@cmelchior that's not a bad idea tbh this is a common and not obvious error
