### ISSUE TITLE
Can not convert db data to json by Gson

### ISSUE THREAD

**Issue by carl1990** [realm/realm-java#3760]
I get a object from realm db:

    CurrentUser user = realm.where(CurrentUser.class).findFirst();
and want to convert this object to json by Gson:

    new Gson().toJson(user)

but my program waiting here util no response

**Comment by cmelchior** [comment]
Gson does not work well with Realms proxy classes, so you need to copy the data into memory first

```
CurrentUser realmUser = realm.where(CurrentUser.class).findFirst();
CurrentUser inMemoryUser = realm.copyFromRealm(realmUser);
new Gson().toJson(inMemoryUser);
```

**Comment by carl1990** [comment]
I has tried  ,this code work well.
thank you
