### ISSUE TITLE
Multiple Realm async transactions exception

### ISSUE THREAD

**Issue by chashmeetsingh** [realm/realm-java#3763]
#### Goal

> What do you want to achieve?
Updating multiple records around 1000 in the db in async

#### Expected Results

> Should work fine 

#### Actual Results

>  `Fatal Exception: java.util.concurrent.RejectedExecutionException
Task java.util.concurrent.FutureTask@3f779bcf rejected from io.realm.internal.async.e@880995c[Running, pool size = 5, active threads = 5, queued tasks = 100, completed tasks = 18]`

#### Code Sample

```java
private void writeToDB(final onUpdateListener listener) {
        Realm realm = RealmSingleton.getInstance().getRealm();
        realm.executeTransactionAsync(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {
                    // update code .......
             }
        }, new Realm.Transaction.OnSuccess() {
            @Override
            public void onSuccess() {
                listener.onResults(true);
            }
        });

```

#### Version of Realm and tooling
Realm version(s): `io.realm:realm-cradle-plugin:1.2.0`

Android Studio version: 2.2.2

Which Android version and device: Sony, 6.0

**Comment by Zhuinden** [comment]
Well you should use **1** async transaction for updating multiple records, not **10000**.

This is on your side to fix.

**Comment by chashmeetsingh** [comment]
@Zhuinden we have a single async transaction which updates around 1k records

**Comment by Zhuinden** [comment]
@chashmeetsingh well then that async transaction starts 100+ other async transactions.

Still, this error says that you're starting up 100+ async transactions at the same time, and the queue rejects it.

**Comment by chashmeetsingh** [comment]
@Zhuinden I need to have a look at this again. Thanks for correcting me 👍

**Comment by chashmeetsingh** [comment]
thanks @Zhuinden found the issue. You were right 👍
