### ISSUE TITLE
SyncConfiguration conflict with default configuration

### ISSUE THREAD

**Issue by vitorprado** [realm/realm-java#3766]
I need to update my app using sync over `Object Server`.. But after set `SyncConfiguration` as `defaultConfiguration`, when I call `Realm.getDefaultInstance()` realm throws this error:
```
java.lang.IllegalArgumentException: Configurations cannot be different if used to open the same file. 
Cached configuration: 
                                                                              
                                                                              
New configuration: 
                                                                              
```

my code:
```
RealmConfiguration realmConfig = new SyncConfiguration.Builder(SyncUser.currentUser(), REALM_URL).build();
Realm.setDefaultConfiguration(realmConfig);
realm = Realm.getDefaultInstance();
```

I can't update my config to use `Object Server`? should I create another Realm and copy my current into that?

**Comment by Zhuinden** [comment]
> should I create another Realm and copy my current into that?

Unfortunately if I know right, that's how you create a sync realm from an existing realm, yes.

**Comment by cmelchior** [comment]
@vitorprado 
That error should only happen if you have multiple configurations? Are you creating other configurations somewhere and how do they look?

That said, you cannot use "old" Realms with the Object Server. You will have to craete a new one and move the data there.

**Comment by vitorprado** [comment]
This is not described in `Object Server` docs, by the way the doc don't describe how to use the object server in Android would be nice to have a section talking about it.

**Comment by vitorprado** [comment]
I'd change my config and set another name to realm, but realm still break with different configurations:

My old code:
```
 RealmConfiguration realmConfig = new RealmConfiguration
                .Builder(AcessoApplication.getApplication())
                .schemaVersion(1)
                .migration(Migration.getInstance())
                .build();

        Realm.setDefaultConfiguration(realmConfig);
        realm = Realm.getDefaultInstance();
```

my new code:
```
        SyncConfiguration realmConfig = new SyncConfiguration
                .Builder(SyncUser.currentUser(), REALM_URL)
                .name(DB_NAME)
                .build();
        realm = Realm.getInstance(realmConfig);
```

the error:
```
  Caused by: java.lang.IllegalArgumentException: Configurations cannot be different if used to open the same file. 
                                                                              Cached configuration: 
                                                                              
                                                                              
                                                                              New configuration: 
                                                                              
                                                                                  at io.realm.RealmCache.validateConfiguration(RealmCache.java:279)
                                                                                  at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:118)
                                                                                  at io.realm.Realm.getInstance(Realm.java:229)
```

**Comment by cmelchior** [comment]
Hi @vitorprado I haven't been able to reproduce this. What are you using for `REALM_URL` and `DB_NAME` ?

I did notice that our `SyncConfiguration.toString()` is not outputting the correct information and we should fix that, but it shouldn't be the cause of this.

**Comment by vitorprado** [comment]
here:
```
private static final String REALM_URL = "realm://" + BuildConfig.REALM_OBJECT_SERVER_IP + ":9080/~/" + BuildConfig.REALM_NAME;
private static final String DB_NAME = "new_sync_database";
```

I'm calling `Realm.init(context);` in my Application `onCreate`, could be a problem? The global `init` create a `defaultConfiguration` and initialize a `SharedRealm`
When I remove the global init the `object server` library crash when I call `SyncUser.currentUser()`,  I think the `UserStore` isn't initialized.

**Comment by cmelchior** [comment]
You should only get the `IllegalArgumentException` if you accidentally opened the Realm using the default configuration first, e.g.

```
Realm.init(context);
Realm.getDefaultInstance().close();
 RealmConfiguration realmConfig = new RealmConfiguration
                .Builder(AcessoApplication.getApplication())
                .schemaVersion(1)
                .migration(Migration.getInstance())
                .build();

Realm.setDefaultConfiguration(realmConfig);
realm = Realm.getDefaultInstance(); // This would crash since the defaultConfig and realmConfig point to the same file but are not the same.
```

It is a requirement to call `Realm.init()` before calling any Realm API including `SyncUser.currentUser()` so that crash is expected.

Would it be possible for you to share a sample project demonstrating the issue?

**Comment by vitorprado** [comment]
If I call `Realm.getDefaultInstance().close()` after `init` I receive this: `                                                    Caused by: java.lang.IllegalArgumentException: Realm on disk is newer than the one specified: v1 vs. v0`

**Comment by vitorprado** [comment]
Unfortunately I can't share the project with you. 😢

**Comment by vitorprado** [comment]
I found a solution to my problem, I wanted to keep my old `.realm` file but I give up this ideia.
I'm deleting the old realm before open the new one(SyncConfiguration):
```
        Realm.init(this);
        RealmConfiguration realmConfig = new RealmConfiguration
                .Builder()
                .schemaVersion(1)
                .migration(Migration.getInstance())
                .build();

        Realm.deleteRealm(realmConfig);
        SyncConfiguration realmConfig = new SyncConfiguration
                .Builder(SyncUser.currentUser(), REALM_URL)
                .name(DB_NAME)
                .build();
        Realm.setDefaultConfiguration(realmConfig);
```
Now it's working.
Thanks for helping me!

**Comment by vitorprado** [comment]
Still crashing with: `java.lang.IllegalArgumentException: Configurations cannot be different if used to open the same file.` .. but it's not the same file 😢

**Comment by vitorprado** [comment]
I found why it's crashing.
The default config was set everytime I got the realm object, when I use this with simple `RealmConfig` it's ok but when I use it with `SyncConfig` it crashes.
The `RealmCache` call `validateConfiguration` and check if new config is equal to cached config.. and I don't know why but it's different(should be equals).
Thanks!!!

**Comment by michael-mckenna** [comment]
Getting the same issue now, what was the solution? Sorry, not quite following how you fixed it.

**Comment by Zhuinden** [comment]
@michael-mckenna typically the issue is that `equals()` is checked between RealmConfigurations, but people often forget to override hashCode/equals to make two Migrations seem like the same thing. (for example `equals { return obj != null && obj instanceof MyMigration; }`)

**Comment by adellhk** [comment]
Hi, I'm having a similar issue. In the onSuccess of my `SyncUser.loginAsync` callback I set my default realm configuration and then access my default realm configuration and I keep getting an Illegal Argument Exception warning me about multiple configurations being used to open the same file. I don't think I have any open Realm instances or configurations applied at this point and I don't have any migrations. If, after logging in I close and restart my app it works fine with my syncConfiguration as the default realm configuration. Can anyone help? Full text below:

````Java

private static void setDefaultRealmConfiguration(SyncUser syncUser) {
    SyncConfiguration syncConfig =
        new SyncConfiguration.Builder(syncUser, AuthUtility.SYNC_REALM_URL)
            .build();
    Realm.setDefaultConfiguration(syncConfig);
  }

public static void loginRealm(SyncCredentials syncCredentials) {
    SyncUser.Callback callback = new SyncUser.Callback() {
      @Override
      public void onSuccess(SyncUser syncUser) {
        setDefaultRealmConfiguration(syncUser);
        //access Realm.getDefaulInstance and crash with IEA.
````

````
java.lang.IllegalArgumentException: Configurations cannot be different if used to open the same file. 
                  Cached configuration: 
                  realmDirectory: /data/user/0/io.adell.whatsthebeta/files/realm-object-server/common
                  realmFileName : sync
                  canonicalPath: /data/data/io.adell.whatsthebeta/files/realm-object-server/common/sync
                  key: [length: 0]
                  schemaVersion: 0
                  migration: null
                  deleteRealmIfMigrationNeeded: false
                  durability: FULL
                  schemaMediator: io.realm.DefaultRealmModuleMediator@35bc2404
                  serverUrl: [redacted]/common/sync
                  user: {UserId: 137475412ac63ad1b6c47ee9f1d6d859, AuthUrl:  [redacted]/auth, IsValid: true, Sessions: 1}
                  syncPolicy: io.realm.internal.syncpolicy.AutomaticSyncPolicy@9abfacd
                  errorHandler: io.realm.SyncManager$1@c326f82
                  deleteRealmOnLogout: false
                  
                  New configuration: 
                  realmDirectory: /data/user/0/io.adell.whatsthebeta/files/realm-object-server/common
                  realmFileName : sync
                  canonicalPath: /data/data/io.adell.whatsthebeta/files/realm-object-server/common/sync
                  key: [length: 0]
                  schemaVersion: 0
                  migration: null
                  deleteRealmIfMigrationNeeded: false
                  durability: FULL
                  schemaMediator: io.realm.DefaultRealmModuleMediator@35bc2404
                  serverUrl:  [redacted]/common/sync
                  user: {UserId: 0ce60c7104212f834b48846788f515c0, AuthUrl:  [redacted]/auth, IsValid: true, Sessions: 0}
                  syncPolicy: io.realm.internal.syncpolicy.AutomaticSyncPolicy@fff4693
                  errorHandler: io.realm.SyncManager$1@c326f82
                  deleteRealmOnLogout: false
````

**Comment by Zhuinden** [comment]
The user ID looks super different, and it also has 1 open session, so there might be an unclosed Realm somewhere.

**Comment by adellhk** [comment]
I found a nested realm reference, which I got rid of and updated my Realm to 3.5.0 which fixed some of my problems. I can still recreate this crash now even with identical UserIds and 0 sessions for both the cached config and new one, but it only happens on logout and then re-login via facebook (so logout must not be clearing my configuration), which is edgy enough to leave alone for now.

````java
public static void logout() {
    LoginManager.getInstance().logOut();
    MyApplication.clearCurrentClimber();
    Realm.removeDefaultConfiguration();
    if (SyncUser.currentUser() != null) {
      try {
        SyncUser.currentUser().logout();
      } catch (Exception e) {
        Log.d("AuthUtility:logout()", "logout: " + e);
      }
    }
  }
````
