### ISSUE TITLE
 io.realm.exceptions.RealmPrimaryKeyConstraintException: Value already exists: 0

### ISSUE THREAD

**Issue by JoeBoeJoe** [realm/realm-java#3767]
Started using Realm for few days , and it is great thing so far.
I got two fragments, I want to pass data between EditText in fragment 1 and TextView in fragment 2.

I have already seen some solutions here and StackOverflow, but none of them worked for me.and I am still getting error RealmPrimaryKeyConstraintException,

There is some problem with setting Primary key ID = 0, so I did try to set it to 5, but nothing worked for me.

Fragment 1:
```
 @OnClick(R.id.btn_forgot)
    public void onButtonClick() {
    
        Realm realm = getRealm();
        realm.beginTransaction();

           Email email1 = realm.createObject(Email.class) ;
        email1.setUsername(editEmail.getText().toString());
        realm.copyToRealmOrUpdate(email1);
        realm.commitTransaction();
    }

Fragment 2:


  ```
  @Override
    public void onStart() {
        super.onStart();

        realm = getRealm();
        RealmQuery<Email> query1 = realm.where(Email.class);
        Email result1 = query1.findFirst();
        resendTxt = (AutoResizeTextView) getView().findViewById(R.id.resend_txt) ;

        if(resendTxt != null){
            this.resendTxt.setText(result1.getUsername());
        }

    }

Model:

```
public class Email extends RealmObject {
    @PrimaryKey
    private int id = 0;
    private String username;

    public String getUsername() {
        return username;
    }
    public void setUsername(String username) {
        this.username = username;
    }
}
```
```
```

**Comment by Zhuinden** [comment]
This line

           Email email1 = realm.createObject(Email.class) ;

implicitly creates a new managed RealmObject with default ID value (this is **disallowed** in Realm 2.x and throws an exception), and the default ID value is `0`.

The solution is to create the object with its ID set:

    Email email1 = realm.createObject(Email.class, id) ;

**Comment by adnxy** [comment]
@Zhuinden Should I change name of my Primary key id to realmId = 0, and then make this change  Email email1 = realm.createObject(Email.class, realmId) ;     thx a lot for help

**Comment by Zhuinden** [comment]
Renaming isn't necessary, but creating object with the primary key value would fix this, yes

**Comment by JoeBoeJoe** [comment]
Still not geting over this one, again exception.
I do not get this exception when I first open app, because id is set for first time.When I try to open app again and enter new input, ID is still same as before and app crashes:
 (createObject io.realm.exceptions.RealmPrimaryKeyConstraintException: Value already exists: 0)

I created a standalone object, set values of the fields, and then copy it to Realm by copyToRealm() method,and still get same error:

 Realm realm = getRealm()

        Email emailUser = new Email();
        realm.beginTransaction();
        emailUser.setUsername(editEmail.getText().toString());
        realm.copyToRealmOrUpdate(emailUser, id);
        realm.commitTransaction();

**Comment by Zhuinden** [comment]
Do you use `copyToRealm` anywhere instead of `copyToRealmOrUpdate`?

**Comment by JoeBoeJoe** [comment]
Not on these two fragments, but project is big so others are working inside some other Activitys and Fragments.

**Comment by Zhuinden** [comment]
Well, look for either unparametrized `createObject` call, or `copyToRealm`.

**Comment by kneth** [comment]
See also https://realm.io/docs/java/latest/#primary-keys
