### ISSUE TITLE
i get A default public constructor with no argument must be declared error when i have default contstructor

### ISSUE THREAD

**Issue by tux-world** [realm/realm-java#3772]
I'm trying to define simple class like with web service result to get that and save it into database, but i get this error:

> Error:A default public constructor with no argument must be declared if a custom constructor is declared.

I'm wondering because i have default constructor on class definition

```
public class ContactUs extends RealmObject{

    private PartOne partOne;
    private PartTwo partTwo;
    private PartThree partThree;

    public ContactUs() {
    }

    /* Setters and Getters */
}

public class PartOne extends RealmObject{
    private String title;
    private String imgUrl;
    private String description;
    private RealmList<Telephone> telephone;

    public PartOne() {
    }
}

public class PartTwo extends RealmObject {
    private String title;
    private String imgUrl;
    private String description;
    private RealmList<Telephone> telephone;

    public PartTwo() {
    }
}

public class PartThree extends RealmObject {
    private String title;
    private String imgUrl;
    private String description;
    private RealmList<Telephone> telephone;

    public PartThree() {
    }
} 
```

**Comment by Zhuinden** [comment]
All of those fields must be RealmObject, or must be marked with `@Ignore`.  Also make sure those classes also have a public default constructor.

**Comment by tux-world** [comment]
@Zhuinden my post updated, please review that

**Comment by Zhuinden** [comment]
How about `Telephone`

**Comment by tux-world** [comment]
@Zhuinden yes you are right, i had forgotten to create default constructor for that, Thanks

**Comment by Zhuinden** [comment]
To have a default constructor, ALL of your variables need to have a default value.

**Comment by ViktorMorgachev** [comment]
Many thanks. So Great
