### ISSUE TITLE
RealmQuery get the wrong results!

### ISSUE THREAD

**Issue by iBotasky** [realm/realm-java#3777]
@kishikawakatsumi Hello again, I got a problem about RealmQuery!
The code under here is my Code:
```
RealmQuery<Running> runningRealmQuery = realm.where(Running.class); runningRealmQuery.lessThanOrEqualTo("createTime", runningDto.getCreateTime());
runningRealmQuery.equalTo("valid", "1");
runningRealmQuery.equalTo("deviceType", 11).or().equalTo("deviceType", 10);
runningRealmQuery.equalTo("userRemoteId", GlobalVar.remoteId);
RealmResults<Running> runningRealmResults = runningRealmQuery.findAllSorted("createTime", Sort.DESCENDING);
int size = runningRealmResults.size();
```
but i got the wrong size, here is my screenshot of the view in `DEBUG` mode:
![image](https://cloud.githubusercontent.com/assets/13627665/20215588/2fd6d700-a850-11e6-8e6c-7344a3dcf1e2.png)

the size i got in the code is 7, but I'm sure there is only 1 record on my realm, so i browse the realm
file, the is only 1 record of the query `runningRealmQuery.equalTo("userRemoteId", GlobalVar.remoteId);`, but i don't know i got 7 result. Here is the realm file screenshot:
![image](https://cloud.githubusercontent.com/assets/13627665/20215632/8fc1c7b0-a850-11e6-87a2-ac8b241c1fcc.png)

And I guess the method `lessThanOrEqualTo`  has a bug,  because, sometimes I got a wrong record of this method , eg: the `lessThanOrEqualTo()` put a  date type of 2016-11-1, and the results will get a result of Date 2016-11-2;

**Comment by Zhuinden** [comment]
Your query is wrong. The device type conditions should be in a pair of `beginGroup().equalTo().or().equalTo().endGroup()`.

**Comment by iBotasky** [comment]
@Zhuinden Wao~~! Thanks again,  I have been to try for the code. it's my false that I don't read the document carefully. Thanks again and apologize to bother you！
