### ISSUE TITLE
Help with encrypted realm version 0.87.5

### ISSUE THREAD

**Issue by jpgpuyo** [realm/realm-java#3779]
Hello,

We feel very confortable working with realm database on Android, but right now we have some problems with encrypted realm.

To generate a encrypted key for realm, we generate a random sequence of bytes:
```
byte[] key = new byte[64];
 new SecureRandom().nextBytes(key);
```
We encrypt this with a private key found in the android keystore and we save it in shared preferences, that is generated only during the first run of the app.

We are using crashlytics to report issues, and we have detected that in some android devices, especially in samsung devices, when user changes the pin o change the lock pattern, android keystore is wiped, so we need to generate a new realm encryption key.

We don't know how to detect this case, so our best option is try to init realm, and if we can't init realm properly, delete database, generate a new realm key and start the app with a clean realm database.

The problem is: 
¿How can we delete a realm instance if encryption key is lost?
Method deleteRealm needs a RealmConfiguration, but we don't have RealmConfiguration because encryption key generates a exception.

So, our best option (fast and dirty option) is this (in the android Application class):

```
 private void initRealmConfiguration() {
        RealmConfiguration myConfig = new RealmConfiguration.Builder(this)
            .schemaVersion(RealmVersions.VERSION_1)
            .migration(new RealmMigrationUtil())
            .encryptionKey(getRealmEncryptionKey())
            .build();
        Realm.setDefaultConfiguration(myConfig);

        if (!isRealmInstanceOk()) {
            Realm.deleteRealm(myConfig);
            restartDatabase();
        }
    }

private boolean isRealmInstanceOk() {
        Realm realm = null;
        boolean ok = false;
        try {
            realm = Realm.getDefaultInstance();
            ok = true;
        } catch (Exception e) {
            ok = false;
            CrashlyticsUtils.sendCustomLog(TAG, "isRealmInstanceOk()", e);
        } finally {
            if (realm != null) {
                realm.close();
            }
        }
        return ok;
    }

    private void restartDatabase() {
        preferencesUtil.resetApp();
        initApplication();
    }

/**
     * TODO We try to ensure that getRealmEncryptionKey never is null,
     * but we are not sure if second attempt will work,
     * so if first attempt to generate a realm key fails,
     * we force a second attempt.
     * If second attempt fails, we will return null
     * @return
     */
    private byte[] getRealmEncryptionKey() {
        byte[] result = null;
        try {
            String realmKey = preferencesUtil.getRealmKey();
            if (TextUtils.isEmpty(realmKey)) {
                realmKey = createRealmKey();
            }

            result = Base64.decode(realmKey, Base64.DEFAULT);
        } catch (Exception exceptionInFirstAttempt) {
            CrashlyticsUtils.sendCustomLog(TAG, "getRealmEncryptionKey() first attempt", exceptionInFirstAttempt);

            try {
                String realmKey = createRealmKey();
                result = Base64.decode(realmKey, Base64.DEFAULT);
            } catch (Exception exceptionInSecondAttempt) {
                CrashlyticsUtils.sendCustomLog(TAG, "getRealmEncryptionKey() second attempt", exceptionInSecondAttempt);
            }
        }
        return result;
    }
```
And  a code snippet from PreferencesUtil:

```
    public String getRealmKey() {
        String key = getStringProperty(KEY_REALM_DB);
        if (TextUtils.isEmpty(key)) {
            return key;
        } else {
            return CrypterHandler.decrypt(context, getStringProperty(KEY_REALM_DB));
        }
    }

    public void setRealmKey(String key) {
        setStringProperty(KEY_REALM_DB, CrypterHandler.encrypt(context, key));
    }

    public void resetApp() {
        SharedPreferences.Editor editor = sharedPreferences.edit();
        editor.clear();
        editor.apply();
    }

```

So, my questions:
1. ¿How can you delete realm instance without create a realm configuration?
2. If we want maximum security, is there another way to generate a realm key without android keystore? Probably you know a library or another easy way to do it....
3. What do you think about storing encrypted realm key in shared preferences? If you don't store in shared preferences, where do you store it?
4. It is difficult migrate 0.87.5 version to last version of realm, but if we do it, we can solve this problem with encryption in a easy way?

Thank you so much!

Best regards,
Joaquim

#### Goal

> Delete realm instance when encrypted key is missing and start the app with realm database in a clean state.
> Know how to work with encrypted realm and best practices about the encryption in realm.

#### Expected Results

> User lose old database because the encrypted key is missing, but he can use the new realm database.
> 100% free crash sessions of crashlytics

#### Actual Results
```
Fatal Exception: java.lang.RuntimeException: Unable to create application 
....AndroidAppApplication: java.lang.IllegalArgumentException: A non-null key must be provided
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5010)
       at android.app.ActivityThread.access$1600(ActivityThread.java:172)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1483)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:145)
       at android.app.ActivityThread.main(ActivityThread.java:5832)
       at java.lang.reflect.Method.invoke(Method.java)
       at java.lang.reflect.Method.invoke(Method.java:372)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1399)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1194)
Caused by java.lang.IllegalArgumentException: A non-null key must be provided
       at io.realm.RealmConfiguration$Builder.encryptionKey(RealmConfiguration.java:347)
       at ....AndroidAppApplication.initRealmConfiguration(AndroidAppApplication.java:111)
       at ....AndroidAppApplication.initApplication(AndroidAppApplication.java:96)
       at ....AndroidAppApplication.onCreate(AndroidAppApplication.java:50)
```

#### Steps & Code to Reproduce

> We are trying to investigate about the different use cases that are causing crashes.

#### Version of Realm and tooling
Realm version(s): 0.87.5
Realm sync feature enabled: no
Android Studio version: 2.1.3
Which Android version and device: 4.4.2

**Comment by Zhuinden** [comment]
Back in the day my failsafe code rebuilt the path like this:

     getFilesDir().getPath() + File.separator + "default.realm";

You'd have to verify if it fits your usecase. Also, newer version of Realm create some other stuff like the "management folder" which is a bit more complicated, but this works in 0.87.5.

**Comment by zaki50** [comment]
I don't think `Realm.deleteRealm(RealmConfiguration)` uses encryption key.
Could you try to make a `RealmConfiguration` without encryption key?

**Comment by kneth** [comment]
I'm closing the issue for now. Don't hesitate to reopen if you have updates.

**Comment by jpgpuyo** [comment]
I will try the proposals commented in this post! Thanks to all!
