### ISSUE TITLE
Realm with big data

### ISSUE THREAD

**Issue by NhenDen** [realm/realm-java#3780]
Hello everybody,
I have issue with Realm when i must insert 34,000 item in database.
My code:
`for (int i = 0; i < sizeDataCustomer; i++) {
                    CustomerDownloadData.RowsUpdated rowsUpdated = mDataCustomerDownload.get(i);
                    CustomerData customerData = getCustomerDataConvert(rowsUpdated);
                    realm.beginTransaction();
                    realm.copyToRealm(customerData);
                    realm.commitTransaction();
}`
sizeDataCustomer = 34000;
But app not response. It close after 1 minute and insert success 4000 item.
I haven't no idea, please help me. Thanks.

**Comment by Zhuinden** [comment]
See that's why you can optimize this code waaay more:

realm.executeTransaction(new Realm.Transaction() {
    @Override
    public void execute(Realm realm) {
        for (int i = 0; i < sizeDataCustomer; i++) { 
            CustomerDownloadData.RowsUpdated rowsUpdated = mDataCustomerDownload.get(i);    
            CustomerData customerData = getCustomerDataConvert(rowsUpdated); 
            realm.insert(customerData); 
        }
    }
});

Just like here: http://stackoverflow.com/a/39385985/2413303

**Comment by kneth** [comment]
As @Zhuinden points out, use the batch insert function. And maybe use an async write transaction.

**Comment by Zhuinden** [comment]
@kneth his problem was that he started a new transaction for every single object he saved

**Comment by kneth** [comment]
True, but even with the faster batch insert functions, it might be better to insert large number of object async in order to avoid NRE.
