### ISSUE TITLE
Realm Android - Multiple Threads, updating objects not working at all...

### ISSUE THREAD

**Issue by heitorpr** [realm/realm-java#3788]
> What do you want to achieve?
Fetch an object from Realm on one instance and another has the latest update.

#### Expected Results
1 - Thread 1 create object with primary key
2 - Fetch the object on Thread 2 and the object is returned

#### Actual Results
1 - Thread 2 bring null object =(

#### Steps & Code to Reproduce
1 - Init realm on application class

        Realm.init(this);
        realmConfiguration = new RealmConfiguration.Builder()
                .schemaVersion(17)
                .migration(new RunrunitMigration())
                .build();

        Realm.setDefaultConfiguration(realmConfiguration);
        Realm realm = Realm.getDefaultInstance();
        realm.setAutoRefresh(true);

2 - Create object and update it on main thread. The object is created with UUID this way:

Client example

    public static Client create() {
        return new Client(create(new RealmClient(UUID.randomUUID().toString())));
    }

On Model Generic Class:

    public static <T extends RealmObject> T create(T object) {
        Realm realm = Realm.getDefaultInstance();
        realm.beginTransaction();
        object = realm.copyToRealmOrUpdate(object);
        realm.commitTransaction();
        realm.close();

        return object;
    }

3 - to save the object on updates I do the following code:

    public void save() {
        if (valuesToUpdate.isEmpty())
            return;

        Realm realm = Realm.getDefaultInstance();
        realm.executeTransaction(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {
                doSave(model);
            }
        });
    }

4 - To send the object I call a method that is async sending the UUID to the job, with that I can fetch the realm object there, this way:

    public T find(String key, Object objId) {
        Realm realm = null;
        T realmObject = null;

        if (objId != null) {
            try {
                realm = Realm.getDefaultInstance();
                realmObject = realm.where(type).equalTo(key, (String) objId).findFirst();
            } catch (Exception ex) {
                Utils.logException(getClass().getSimpleName() + ":find:" + objId, ex);
            } finally {
                if (realm != null) {
                    realm.close();
                }
            }
        }

        this.model = realmObject;
        return realmObject;
    }

5 - In the end... my object is null.. Before updating the realm, I was using realm.refresh() to obtain the object on the async task.

6 - Well, I really do not know what to do to solve this... Tried to create a new realmObject with the same UUID on the async task, and it works... But, should work? =(, I'm confused and sad! Thought the realm objects was updated across threads... Don't know what I'm doing wrong, but my entire app when creating or updating objects use this logic =/. Some help plz! =D

7 - Observation: I am receiving this warning:

REALM_JAVA: Mixing asynchronous queries with local writes should be avoided. Realm will convert any async queries to synchronous in order to remain consistent. Use asynchronous writes instead.

#### Version of Realm and tooling
Realm version(s): ? 
2.1.1

Realm sync feature enabled: yes/no
yes

Android Studio version: ?
2.2.2

Which Android version and device: ?
6.0

**Comment by cmelchior** [comment]
If the object isn't visible in your job thread, most likely there is a problem with an old instance hanging around that isn't getting updated. Your find method does look fine though.

- How do you `doSave()` method communicate with the worker thread? Is there a chance the worker begins before the save completed?
- You can check for open Realm instances by using `Realm.getLocalInstanceCount(realmConfiguration)`. Can you check it returns `0` before opening the Realm in the worker thread?

**Comment by Zhuinden** [comment]
RealmObjects do get updated along with the Realm instance. Except Realm instances don't automatically get updated when they're on background threads. I've written about this [here](https://medium.com/@Zhuinden/understanding-realm-version-retention-and-synchronization-9a513c2445bb#.ohj789z6g).

You can force a refresh on your background threads like this: http://stackoverflow.com/a/38839808/2413303

But you're also writing synchronously on the UI thread, so that's not too great.

You should try to remove all writes from the UI thread, and you should also make sure you close Realm instances in *finally*.

---------


...also, did that `find()` method ever work? You're kinda closing the instance the returned RealmObject belongs to. That can't be right.

**Comment by heitorpr** [comment]
1 - The find method get a realm instance just for him, but the activity or thread that called it, has it own instance (on same thread) following activity, fragment or job life cycle. It kind works =).

doSave(model) do not talks with worker thread, it is local too.

    private void doSave(RealmProject model) {
        if (model == null) return;

        for (Map.Entry<String, Object> entry : valuesToUpdate.entrySet()) {
            String key = entry.getKey();
            Object value = entry.getValue();

            switch (key) {
                case "id":
                    model.setId(Utils.parseString(value));
                    break;
                case "name":
                    model.setName(Utils.parseString(value));
                    break;
 
                ...
                case "activities":
                    model.setActivities(Utils.parseLong(value));
                    break;
            }
        }
    }

2 - I checked before calling the worker thread, my object is updated before going to the new thread. And there my object is not created. Also without using my "find()" method, using direct the realm way, my object is not created also.

3 - Observation.. I have a java object called Model that has a RealmModel, so on Model I do all operations and interfaces to save,update,fetch the realmModel. And on realmModel it just contains data from the database, no methods there.

4 - Getting null pointer on worker thread before calling realm when tried to run `Realm.getLocalInstanceCount(realmConfiguration)`:

> java.lang.NullPointerException: Attempt to invoke virtual method 'int java.lang.Integer.intValue()' on a null object reference

On RealmCache.java -- > RealmCacheType.values() returns 2 values, (the second is DYNAMIC_REALM, null pointer happens inside the for loop on line 405.

    static int getLocalThreadCount(RealmConfiguration configuration) {
        RealmCache cache = cachesMap.get(configuration.getPath());
        if (cache == null) {
            return 0;
        } else {
            int totalRefCount = 0;
            for (RealmCacheType type : RealmCacheType.values()) {
                totalRefCount += cache.refAndCountMap.get(type).localCount.get();
            }
            return totalRefCount;
        }
    }

**Comment by cmelchior** [comment]
Seems there is a bug in `getLocalInstanceCount()` we need to fix. I created #3791 for it.
Regarding your other issue. Would it be possible for you to create or share a sample project demonstrating your problem. Debugging this from just code snippets doesn't seem feasible.

**Comment by heitorpr** [comment]
Yes @cmelchior , I will need some time to create a project, will try to do it in a few hours. Will come back with the github url in some time. Thanks! =)

**Comment by heitorpr** [comment]
@cmelchior, I created the project with the bug here:

https://github.com/heitorpr/heitorBugRealm.git

I could not reproduce in the sample project the bug where the object is not even created on the worker thread. But, the object is not being updated on the second time. Follow the instructions on code to reproduce the problem.

If you wish to talk with me. You can send me an email, heitorprodrigues@gmail.com, or just comment bellow =).

Thank you for your help!

**Comment by cmelchior** [comment]
Hi @heitorpr 
I think you are mixing up your logic. The check you referer to is run _before_ you save the state: https://github.com/heitorpr/heitorBugRealm/blob/master/app/src/main/java/heitor/br/realmbugandroidheitor/managers/rest/ClientRest.java#L89

Also, the first save in the UI will never run as the `valuesToUpdate` is empty.

I didn't see anything that indicate a bug in Realm only app logic bugs, so I'll close this issue. If you find a bug you can trace back to Realm, feel free to re-open or create new issue.

**Comment by lucasleongit** [comment]
hi @heitorpr!

Were you able to fix this issue? I think I am getting the same issue in my project.

**Comment by Zhuinden** [comment]
@lucasleongit this is common if you're using `Schedulers.io()` and querying outside of transactions on that background scheduler thread pool.

**Comment by dev-JE02** [comment]
@Zhuinden I am also doing the same thing. So, which scheduler could I possibly use? Or if possible could you share how to use a dedicated Looper for Realm?

**Comment by Zhuinden** [comment]
@dev-JE02 technically I forgot to mention that querying outside of transactions on Schedulers.io() only reuslts in stale data if you have unclosed Realm instances for that thread.

But yes, if you do "safe integration" as people tend to claim, then doing queries on Schedulers.io() is not necessarily a smart idea; you should use a [LooperScheduler](https://github.com/Zhuinden/simple-stack/blob/master/simple-stack-example-mvp/src/main/java/com/zhuinden/simplestackdemoexamplemvp/application/MainScopeListener.java#L39-L52).
