### ISSUE TITLE
Realm data lost after an exception occurs in the application

### ISSUE THREAD

**Issue by santimendon** [realm/realm-java#3793]
> **Questions**: 
**How to persist previously saved Realm data even after an Exception occurs in the application**

#### Goal

If the application already has some realm data saved previously, then this data should persist after an exception has occurred in the application

#### Expected Results

> 1. Save data locally using Realm ex userSelectedValue="abc" is the data which has been saved initially
>2. The app crashed unexpectedly during the flow due to some reason.
>3. When I restart the app, the value of userSelectedValue should persist and not become null

#### Actual Results

>  When I restart the app after a crash, the value of userSelectedValue becomes null

#### Code Sample
>1.  Dto used to store data
`
import io.realm.RealmObject;
import io.realm.annotations.PrimaryKey;

public class RealmLocalObject extends RealmObject {

    @PrimaryKey
    private int userID;
    private String userName;
    private String userLocality;
    private String userGender;

	public int getUserID() {
        return userID;
    }

    public void setUserID(int userID) {
        this.userID = userID;
    }

    public String getUserName() {
        return userName;
    }

    public void setUserName(String userName) {
        this.userName = userName;
    }
	
	public String getUserLocality() {
        return userLocality;
    }

    public void setUserLocality(String userLocality) {
        this.userLocality = userLocality;
    }
	
	public String getUserGender() {
        return userGender;
    }

    public void setUserGender(String userGender) {
        this.userGender = userGender;
    }

	private static RealmLocalObject relamIODTO;

    public void RealmLocalObject() {

    }

    public static synchronized RealmLocalObject getRealmSingletonInstance() {
        if (relamIODTO == null) {
            relamIODTO = new RealmLocalObject();
        }
        return relamIODTO;
    }

    public void setter(RealmLocalObject idto) {
        userID = idto.getUserID();
        employmentType = idto.getEmploymentType();
        areaOfBusiness = idto.getAreaOfBusiness();
    }

}

`

>2.  BaseActivity containing the insertion and retrieval methods

`
public abstract class MyBaseActivity extends AppCompatActivity {

    public RealmLocalObject mRealmObj;
    private static Realm mRealm = null;

    @Override
    protected void onCreate(final Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setRequestedOrientation(ActivityInfo.SCREEN_ORIENTATION_PORTRAIT);
        /*get the singletone instanceof RealmClass*/
        mRealmObj = RealmLocalObject .getRealmSingletoneInstance();
    }
	
	public abstract void initViews();

    public Realm getRealmInstance() {
        if (mRealm == null) {
            RealmConfiguration realmConfig = new RealmConfiguration.Builder(this)
                    .name("testingrealm")
                    .modules(Realm.getDefaultModule(), new AllModulesClasses())
                    .deleteRealmIfMigrationNeeded()
                    .build();
            mRealm = Realm.getInstance(realmConfig);
        }
        return mRealm;
    }

    public RealmLocalObject getStoredDataFromLocally() {
        RealmLocalObject result = null;
        try {
            result = getRealmInstance().where(RealmLocalObject.class)
                    .findFirst();
        } catch (Exception e) {
			e.printStackTrace();
        }
        return result;
    }

    public void storeIntoRelamLocalData() {
            this.getRealmInstance().executeTransaction(new Realm.Transaction() {
                @Override
                public void execute(Realm realm) {
                    mRealmObj.setUserID(InstaConstant.PRIMARY_KEY_VALUE);
                    getRealmInstance().copyToRealmOrUpdate(mRealmObj);
                }
            });
    }

}
`
>3. Activity where the data is stored into Realm

`
public class Activity1 extends MyBaseActivity{

	@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        initViews();

    }

    @Override
    public void initViews() {
        saveLocalData();
    }

    private void saveLocalData() {
        String userName = "Test User";
        mRealmObj.setUserName(userName);
        storeIntoRealmLocalData();
    }
}

`

>4. Activity where data is retrieved after restarting the app after an exception has occured

`
public class Activity2 extends MyBaseActivity {

   @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        updateViews();

    }

    @Override
    public void initViews() {
        //Init screen components
    }

    public void updateViews() {
        try {
            if (mRealmObj != null) {
                String userName = mRealmObj.getUserName();
            }
        } catch (NullPointerException ex) {
            ex.printStackTrace();
        }
    }
 
}
`

>5. Exception I get is a null pointer exception since I have put a validation for one of the parameters coming from realm but this value is null
```

Realm version(s): 
1.1.0

Realm sync feature enabled: yes

Android Studio version: 2.1.1

Which Android version and device: OS version: 5.0.1 & 5.1
Devices: Samsung GT-I9500 and Moto G !st Edition to name a few. But the issue occurred in every device we tested so far

**Comment by Zhuinden** [comment]
Well if you want to retain inserted data, then on restart you should requery that instead of creating a new unmanaged version of it.

**Comment by cmelchior** [comment]
Hi @santimendon Please create a sample project demonstrating this issue. It is hard to tell what is going on when you description does not match the code you posted.

**Comment by Zhuinden** [comment]
@cmelchior the Realm itself doesn't clear anything on exception, he's just using a "singleton" unmanaged object some of the time instead of a managed object. So it is a user error.

Of course, a sample project would make it easier to solve the issue.

**Comment by santimendon** [comment]
@cmelchior Will upload a demo project with the code which I used.
@Zhuinden May I know what you mean by a managed object? Should I create a realm instance instead of using a singleton?

**Comment by Zhuinden** [comment]
Look here:

``` java
public static synchronized RealmLocalObject getRealmSingletonInstance() {
    if (relamIODTO == null) {
        relamIODTO = new RealmLocalObject();
    }
    return relamIODTO;
}
```

You're creating a detached, unmanaged RealmObject and then you're manipulating this across your app.

However, you **don't** ever seem to use the object that you actually persisted into the Realm.

``` java
public RealmLocalObject getStoredDataFromLocally() {
    RealmLocalObject result = null;
    try {
        result = getRealmInstance()
                .where(RealmLocalObject.class)
                .findFirst(); // <---- actual Realm query, obtaining data from Realm
    } catch (Exception e) {
		e.printStackTrace();
    }
    return result;
}
```

**Comment by kneth** [comment]
I hope that the comment above has helped. If so, please either reopen or create new issue.
