### ISSUE TITLE
AVL reports virus for all applications using Realm.io

### ISSUE THREAD

**Issue by FrancescoCapari** [realm/realm-java#3795]
Hello guys,

I want to start with saying that it is NOT your fault and that I know it is a false positive by dumb antivirus software. But I think you should know that and maybe you can even try to figure out why it's happening.

All applications that are using Realm.io library version 2.1.1 and higher are marked as "Trojan/FakeKernel" malicious virus by AVL antivirus software (https://play.google.com/store/apps/details?id=com.antiy.avl).

I received several reports from my users and starting to get down-rates on Google Play because of this - so I investigated and I figured out that it's because of Relam.io.

Version 2.1.0 is considered safe and clean by AVL and since version 2.1.1, all applications that contains Relm.io are marked as a malicious extremely dangerous virus in AVL.

Any idea what has changed between 2.1.0 and 2.1.1 what can cause this? Any way to fix it? Since I doubt AVL will listen to you.

#### Version of Realm and tooling
Realm version(s): 2.1.1

Android Studio version: 2.2

Which Android version and device: ALL

**Comment by zaki50** [comment]
Hi thank you for your report.

I have no idea...
Changes between `2.1.0` and `2.1.1` are only followings:
```
$ git log v2.1.0..v2.1.1
commit 12db1c7a0d2d93ae2ba0b591b22d73135252ad3a
Author: Makoto Yamazaki <makoto1975@gmail.com>
Date:   Thu Oct 27 16:24:02 2016 +0900

    Release v2.1.1

commit 5c2cc8736bab193634bcb338fe5464703b673ac3
Author: Makoto Yamazaki <makoto1975@gmail.com>
Date:   Thu Oct 27 16:14:00 2016 +0900

    fix a bug that proguard configuration keeps all class names. (#3693)

    * fix a bug that proguard configuration keeps all class names.

    * Update CHANGELOG.md

    * update changelog

    * update javadoc comment

commit c4a4edb1325b4ebe807267c7ffc871df0f3d7cdc
Author: Makoto Yamazaki <makoto1975@gmail.com>
Date:   Thu Oct 27 14:56:50 2016 +0900

    Set default RxFactory in SyncConfiguration when RxJava is available. (#3695)

    * Set default RxFactory in SyncConfiguration when RxJava is available.

    * update CHANGELOG

commit 1f9319d3fdce1cf49c36804f5b1281a19012525c
Author: Chen Mulong <chenmulong@gmail.com>
Date:   Wed Oct 26 08:45:26 2016 -0500

    Remove env for TR_ENTER (#3699)

commit dbc23ff9e1883ed50f87b78e956b3f2640176d02
Author: Christian Melchior <christian@ilios.dk>
Date:   Tue Oct 25 11:17:16 2016 +0200

    Prepare next release v2.1.1-SNAPSHOT
```

Is `2.2.0` also reported as malicious?

**Comment by FrancescoCapari** [comment]
Hello,

I just tested it on  dummy application with different Realm.io versions. Interestingly enough, only 2.1.1 is affected. I build 3 release APKs with the same signatures, same code base and I was only changing Realm.io version:

- 2.1.0 = clean
- 2.1.1 = "malicious" (Trojan/FakeKernel)
- 2.2.0 = clean

I repeated full Gradle clean and release tasks 3 times for each version just to be sure, it's really only 2.1.1 that is reported by AVL as malicious. I suspect hard to tell what's in their fancy heuristic, it doesn't say much. I also checked the diff, no idea why 2.1.1 is malicious. I sent them an mail, but I don't really expect any response since it returned 3 times back with 'full mailbox' response (4th came through).

**Comment by kneth** [comment]
@FrancescoCapari Does AVL give any hints on why it flags the app? If it does, it might help us understand what not to do in the future.

**Comment by FrancescoCapari** [comment]
@kneth no response from AVL. But it can be reproducible easily with all applications using realm.io 2.1.1 - they are all marked as virus.

**Comment by kneth** [comment]
@FrancescoCapari I have just about to email AVL :-)

**Comment by kneth** [comment]
@FrancescoCapari I wrote the company too - and have had any response yet :-(

**Comment by kneth** [comment]
@FrancescoCapari I haven't got a reply yet. What about you?

**Comment by kneth** [comment]
Still no reply.

**Comment by beeender** [comment]
This issue has been confirmed by AVL and will be solved soon. Close it from realm side.

**Comment by beeender** [comment]
We got updates from AVL:

> Thanks your feedback. At last we found it flaged by our heuristic rule. We have removed this rule . 

🎉
