### ISSUE TITLE
Rename PermissionChange to SyncPermissionChange

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#3799]
Needed to align class names across bindings: https://github.com/realm/realm-cocoa/blob/master/RealmSwift/Sync.swift#L248

**Comment by kishikawakatsumi** [comment]
The table name must be `PermissionChange`. Cocoa bindings introduce custom table mapping feature to avoid conflict class names between Swift and Objective-C.

The table name is still `PermissionChange` in Cocoa.
https://github.com/realm/realm-cocoa/blob/master/RealmSwift/Sync.swift#L313

I think Java binding doesn't have an ability to map classes to custom table names. The class name should be kept `PermissionChange`?

**Comment by cmelchior** [comment]
Ah great. I was just browsing the Cocoa docs when I noticed this. Thanks for clarification
