### ISSUE TITLE
Software architecture

### ISSUE THREAD

**Issue by HelderAntunes** [realm/realm-java#3801]
Hi, my colleagues and i have already asked questions about various organizational aspects of Realm, such as [software processes](https://github.com/realm/realm-java/issues/3613) and [elicitation requirements](https://github.com/realm/realm-java/issues/3687).

Now we want to know: what are the **architectural patterns** followed by Realm?

An architectural pattern that obviously seems to exist is Client-Server Architecture pattern, but we wanted to know if you are using other architectural patterns.

Thanks in advance.

**Comment by cmelchior** [comment]
`Client-Server` is such a broad term that literally could mean anything in a distributed system. Given that Realm is a database intended to be part of larger systems, we don't follow any architectural patterns as such, we just try to be usable by them.
