### ISSUE TITLE
Information about change

### ISSUE THREAD

**Issue by evgenysuetin** [realm/realm-java#3803]
Hi, is there something like RealmCollectionChange class from java in realm?
If not, how to get information about the changes in a table or query?

That problem is that the cause `notifyDataSetChange()` or `notifyItemRangeChanged(0, size())` bad for recyclerView.

**Comment by Zhuinden** [comment]
Not yet, unfortunately it's being tracked here: https://github.com/realm/realm-java/issues/989

**Comment by cmelchior** [comment]
No, not right now. One work-around could be to use `realm.copyFromRealm()` and DiffUtils ( https://developer.android.com/reference/android/support/v7/util/DiffUtil.html ), but it will only be feasible for smaller data sets.
