### ISSUE TITLE
RxJava dependency in documentation can cause confusion.

### ISSUE THREAD

**Issue by long-greg-c** [realm/realm-java#3805]
#### Goal

The documentation for using [RXJava with Realm](https://realm.io/docs/java/latest/#configuration) will lead the user to believe they need to add the **realm-android** dependency direct. However the **realm-android** dependency is added as a gradle plugin.

#### Expected Results

Remove the unneeded dependency from the documentation.

#### Version of Realm and tooling
Realm version(s): All documentation versions for Realm Java >= 0.88.0

**Comment by zaki50** [comment]
Hi @long-greg-c 
Thanks!

I'll update the documents.

**Comment by zaki50** [comment]
deployed.
