### ISSUE TITLE
TRIM/REPLACE symbols during String search

### ISSUE THREAD

**Issue by ubeyou** [realm/realm-java#3807]
the current version does not support strip entries symbol

E.g. in my db entries, there is
"Dick & Harry"
"Dick Hobbs"

When I fill contains() with "Dick H", only "Dick Hobbs" will appear as the result.

there is no feature such MYSQL Trim or Replace.

**Comment by Zhuinden** [comment]
You would need to create a new field that you can search based upon which does not contain the & and only one space instead of 2.

**Comment by cmelchior** [comment]
Yes, this is currently not supported by Realm. I can see the use case though

**Comment by astigsen** [comment]
When LIKE queries is implemented (#3752) you could do it by searching for `"Dick *H"`

**Comment by cmelchior** [comment]
`like()` was released in 2.3.0. Closing
