### ISSUE TITLE
RealmThreadPoolExecutor: desired CORE_POOL_SIZE != calculated

### ISSUE THREAD

**Issue by diegomontoya** [realm/realm-java#3810]
```java
Runtime.getRuntime().availableProcessors()
```

Returns the number of online/active cores in Android. If the class is loaded while the phone was in heavy sleep, it may report value of 1 even when it has 8 cores which translates to a much lower CORE_POOL_SIZE for the duration of the app than desired. 

Referenced from http://stackoverflow.com/questions/10133570/availableprocessors-returns-1-for-dualcore-phones.

**Comment by Zhuinden** [comment]
That's interesting because I specifically remember that that executor is initialized based on code in AsyncTask, but apparently that was also a lie already.

**Comment by cmelchior** [comment]
Thanks @diegomontoya Viable implementation seems to be here: http://stackoverflow.com/questions/7962155/how-can-you-detect-a-dual-core-cpu-on-an-android-device-from-code/10377934#10377934

**Comment by diegomontoya** [comment]
@cmelchior Yes. That linked implementation does work on all android we have tested but missing 1 optimization. It should compile the pattern in the class and re-use it for matching instead of potentially re-generating the regex on each filterFilter accept method call. In android, a regex pattern is a heavy duty object with native ptr and finalizer. 

@Zhuinden We take Android for what it is. 99% open, lots of bad code, lots of great code, and documentation written by robots. =)

**Comment by diegomontoya** [comment]
1) Start app. Do nothing.
2) Have app thread.sleep for 60s then log core count.
3) Turn off screen.  (trigger device sleep mode)
4) Check log. 

I have not tried above but it should trigger the issue.

**Comment by diegomontoya** [comment]
Come to think of it, the easier way to test is with adb. Force device to go into sleep mode via adb command and log the cpu core api output.

**Comment by bmeike** [comment]
@diegomontoya Yeah... definitely.  I was hoping, though, for something that I could put in a unit test...

**Comment by bmeike** [comment]
Closing, with the merge of 3997.  A new issue 4006, explores an explicit native solution.
