### ISSUE TITLE
Error:Execution failed for task ':app:transformNative_libsWithMergeJniLibsForDebug'.

### ISSUE THREAD

**Issue by campanoon** [realm/realm-java#3814]
When executing,  the app crash with following dump in logcat:
Error:Execution failed for task ':app:transformNative_libsWithMergeJniLibsForDebug'.
> com.android.build.api.transform.TransformException: com.android.builder.packaging.DuplicateFileException: Duplicate files copied in APK lib/x86/librealm-jni.so
  	File1: /home/campanon/.gradle/caches/modules-2/files-2.1/io.realm/realm-android/0.82.1/3e4f47bc60063111a375200f866192bf821efa93/realm-android-0.82.1.jar
  	File2: /home/campanon/AndroidStudioProjects/nowcook/app/build/intermediates/exploded-aar/io.realm/realm-android-library/2.2.0/jni

**Comment by Zhuinden** [comment]
You have Realm-Android 0.82.1 in your project for some reason

**Comment by campanoon** [comment]
Thanks you! I was using that lib to use adapters, I already saw that this exists: compile 'io.realm: android-adapters: 1.4.0'

**Comment by Zhuinden** [comment]
realm android adapters shouldn't bring in Realm 0.82.1, so it's something else

**Comment by cmelchior** [comment]
Try `./gradlew dependencies` and see if you somehow import Realm twice

**Comment by tonywump** [comment]
Thanks @Zhuinden !
I have the same issue and solve the issue by
checking `settings.gradle` file and the dependencies in `./app/build.gradle` file.
