### ISSUE TITLE
RealmObservableFactory don‘t call subscriber.onComplete();

### ISSUE THREAD

**Issue by yinshudi** [realm/realm-java#3815]
#### Goal

> I want use Result.asObservable() in concat operator of RxJava.

#### Expected Results

> Emit realmObservable first,and then emit retrofit observable
#### Actual Results

>  Just emit realmObservable.And both onComplete() and onError() don't be called.

#### Steps & Code to Reproduce

> Finally I find the reason.There don't call onComplete() method in RealmObservableFactory’s from() method,so concat() won't emit the other observable。

#### Code Sample

```java

@Override
    public Observable<Realm> from(Realm realm) {
        final RealmConfiguration realmConfig = realm.getConfiguration();
        return Observable.create(new Observable.OnSubscribe<Realm>() {
            @Override
            public void call(final Subscriber<? super Realm> subscriber) {
                // Get instance to make sure that the Realm is open for as long as the
                // Observable is subscribed to it.
                final Realm observableRealm = Realm.getInstance(realmConfig);
                final RealmChangeListener<Realm> listener = new RealmChangeListener<Realm>() {
                    @Override
                    public void onChange(Realm realm) {
                        if (!subscriber.isUnsubscribed()) {
                            subscriber.onNext(observableRealm);
                        }
                    }
                };
                observableRealm.addChangeListener(listener);
                subscriber.add(Subscriptions.create(new Action0() {
                    @Override
                    public void call() {
                        observableRealm.removeChangeListener(listener);
                        observableRealm.close();
                    }
                }));
                subscriber.onNext(observableRealm);
                // There don't call subscriber.onComplete() method !!!
            }
        });
    }

```

#### Version of Realm and tooling
Realm version(s): 2.1.1
RxJava version : 1.1.1

Realm sync feature enabled: no

Android Studio version: 2.2

Which Android version and device: Android 4.4 and 5.0

**Comment by Zhuinden** [comment]
Well yes, it doesn't call `onComplete()` because the applied RealmChangeListener is always listening, which means it's a hot observable, so it doesn't actually ever complete.

However, you could be on to something - according to Jake Wharton, the order of operations should be this:

                subscriber.add(Subscriptions.create(new Action0() {
                    @Override
                    public void call() {
                        observableRealm.removeChangeListener(listener);
                        observableRealm.close();
                    }
                }));
                observableRealm.addChangeListener(listener);

As per

https://github.com/JakeWharton/RxBinding/commit/3759aaae388c89059b3953efffa6fa027d7eb03f

**Comment by yinshudi** [comment]
I have found solution in [this question](http://stackoverflow.com/questions/35127841/realm-db-realm-asobservable-emits-results-twice)

> If you are only interested in the first "real" result you can do something like this:

```
realm.where(Foo.class).findAllAsync().asObservable()
  .filter(obj::isLoaded) // isLoaded is true when query is completed
  .first() // Only get the first result and then complete
  .subscribe(...)
```

thx ~

**Comment by Zhuinden** [comment]
@cmelchior please check https://github.com/realm/realm-java/issues/3815#issuecomment-261462477
