### ISSUE TITLE
logic in getter has not called

### ISSUE THREAD

**Issue by Sejen27** [realm/realm-java#3820]
i add logic in getter, but it does nothing

**Comment by Zhuinden** [comment]
What is your Realm version?

**Comment by Sejen27** [comment]
@Zhuinden  my Realm version is  2.2.0 ， my code is below

    private String contentStr;
    public String getContentStr() {
        if (contentStr == null && content != null) {
            contentStr = new JSONObject(content).toString();
        }
        return contentStr;
    }

**Comment by Zhuinden** [comment]
I would assume the problem is that `content` is null and so is `contentStr`

**Comment by Sejen27** [comment]
@Zhuinden content is not null, i have print the return value of contentStr , but the getter is not call when i save with copyToRealmOrUpdate()，and the value of contentStr is null in db

**Comment by Zhuinden** [comment]
....why would `copyToRealmOrUpdate()` call the getter? It copies the data to Realm via the fields.

To set the field, you should provide custom setter logic, which **you** would call. Then the fields would be set as you expect.

**Comment by Sejen27** [comment]
@Zhuinden  ok, thanks
