### ISSUE TITLE
BeginsWith using "%" and "_"

### ISSUE THREAD

**Issue by berkayturanci** [realm/realm-java#3823]
Hi there, 

I searched it a lot but could not find any significant thing about that. 

Is there a support for "The percent sign (%)" and "The underscore (_)" in BeginsWith method in Realm ?

Thanks

#### Goal

> I am trying to use "%" sign and "_" sign in my beginsWith query. The purpose of those notations are;
The percent sign represents zero, one, or multiple numbers or characters. The underscore represents a single number or character. These symbols can be used in combinations.

#### Version of Realm and tooling
Realm version(s): 2.2.0

Realm sync feature enabled: no

Android Studio version: 2.2.2

Which Android version and device: API 17

**Comment by cmelchior** [comment]
Hi @berkayturanci Not right now, but we have an issue tracking it here (with slightly different syntax): #3752
