### ISSUE TITLE
io.realm.exceptions.RealmError: Unrecoverable error.

### ISSUE THREAD

**Issue by zhangwenjia616** [realm/realm-java#3825]
Caused by: io.realm.exceptions.RealmError: Unrecoverable error. Failure when computing UTF-16 size error_code = 5; retcode = 56; StringData.size = 74; StringData.data = http://img4.bitautoimg.com/autoalbum/files/20160AAAA in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_UncheckedRow.cpp line 136

version 2.0.2

**Comment by kneth** [comment]
Can you provide more context? For example by using the issue template!

**Comment by zhangwenjia616** [comment]
Realm version(s): 2.0.2

Realm sync feature enabled: no

Android Studio version: 2.2.2

Which Android version and device: ?
<img width="695" alt="screen shot 2016-11-22 at 9 35 53 am" src="https://cloud.githubusercontent.com/assets/2179197/20507673/1e0d89b6-b097-11e6-829b-51537ca26ed4.png">

**Comment by kneth** [comment]
Is the string `http://img4.bitautoimg.com/autoalbum/files/20160AAAA` what you expect? The error message says it is 56 characters long (`retcode` - and it is correct) but it expect it to be 74 characters long. Does your input string contains any characters after the last `A`?

**Comment by zhangwenjia616** [comment]
The crash is reported by umeng, but I am not sure is there any other characters after the last A. And I can't get the user's realm file. I will try to add some characters and save to see whether the crash will reproduce.

**Comment by kneth** [comment]
@zhangwenjia616 Can you provide more information by answering the questions above?

**Comment by kneth** [comment]
I am closing the issue since no new information has been provided. Please reopen or create new issue if you encounter it again.
