### ISSUE TITLE
Hi Is it possible to make a join in two tables

### ISSUE THREAD

**Issue by manmohansoni** [realm/realm-java#3829]
I have two tables  1.  PartnerTable ,  ProductTable 
and partnerCode is common column between these two. 

I want to fetch all th partners from 'PartnerTable' which has a specific product let say 'watch' in  'ProductTable' 

Please suggest me the solution for this query. How should i achieve this in realm ?
 Please answer soon ....  I really need it.

**Comment by beeender** [comment]
Please check the doc https://realm.io/docs/java/latest/#link-queries

**Comment by Zhuinden** [comment]
@manmohansoni if you have set up links between the tables with `RealmList<ProductTable>` in `PartnerTable`, then you can do `realm.where(ProductTable.class).equalTo("products.productName", "watch").findAll()`

**Comment by kneth** [comment]
This question is better asked at StackOverflow which has a much larger and broader community.
