### ISSUE TITLE
Doc: IntentService should also close Realm in finally block

### ISSUE THREAD

**Issue by Zhuinden** [realm/realm-java#3831]
Currently the doc doesn't always enforce the `try { ... } finally { ... }` pattern for brevity.

https://realm.io/docs/java/latest/#strategies-when-dealing-with-android-framework-threads

It should either be in `try - finally`, or just use try-with-resources (`try(Realm realm = Realm.getDefaultInstance) { ... }`).

**Comment by zaki50** [comment]
I've updated the documentation.

I will be deployed soon.

**Comment by Zhuinden** [comment]
@zaki50 have you also seen https://github.com/realm/realm-java/issues/3830 ? That one is more important because it causes bugs

**Comment by zaki50** [comment]
yes. I updated all codes that uses `close()`.

The change has been deployed. Could you check the latest documentation?
