### ISSUE TITLE
Async reads and writes should not use same thread pool

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#3832]
**Use case:**
Reported by a user: Starting an app that runs a large number of synchronization jobs on startup (20+). Goal is to have something to show in the UI as fast as possible using async queries, but currently there can be a large delay before data is available.

**Problem:**
We only have one Realm thread pool for both async reads and writes. As Realm write transactions are blocking across threads, If  more write jobs than available processors exists the thread pool will effectively be serialized and act as a single-threaded pool as Realm Core will block all parallel write jobs running. In the worst case where writes are scheduleded before queries, the queries could be blocked for a long time.

**Solution:**
Split the current thread pool into two: 1 for reads and 1 for writes. The one for writes just needs to be a single-threaded pool as multiple threads doesn't make sense. This would mean that async queries always have a chance to run.

**Comment by beeender** [comment]
This will be solved by move async queries to OS: OS is re-run the async query in the notifier daemon thread which is a different thread than the async transaction's.

**Comment by cmelchior** [comment]
This will be fixed as part of #3834

**Comment by beeender** [comment]
#3834 is merged to master. will be fixed in `v2.4.0`.
