### ISSUE TITLE
Migrating from 2.1.1 to 2.2.0 schema problem

### ISSUE THREAD

**Issue by RJFares** [realm/realm-java#3836]
In my app, a base activity starts invisibly, checks if the user exists and credentials OK, then moves either to LoginActivity or MainActivity.
In that invisible activity, it checks for a user with:
`User user = mRealm.where(User.class).findFirst();`
This was fine in 2.1.1, until I upgraded to 2.2.0.
It threw error:

> Caused by: java.lang.IllegalArgumentException: User is not part of the schema for this Realm
>                                                                               at io.realm.internal.modules.CompositeMediator.getMediator(CompositeMediator.java:172)
>                                                                               at io.realm.internal.modules.CompositeMediator.getTableName(CompositeMediator.java:90)
>                                                                               at io.realm.RealmSchema.getTable(RealmSchema.java:296)
>                                                                               at io.realm.RealmSchema.getSchemaForClass(RealmSchema.java:316)
>                                                                               at io.realm.RealmQuery.<init>(RealmQuery.java:138)
>                                                                               at io.realm.RealmQuery.createQuery(RealmQuery.java:87)
>                                                                               at io.realm.Realm.where(Realm.java:1213)
>                                                                               at ...SplashActivity.onCreate(SplashActivity.java:27)

I cannot see anything in the changelog that causes a breaking change which forbids me to query for a user in User.class if that class is empty (I did a full uninstall of the app on the phone, followed by clean / rebuild)

**Comment by Zhuinden** [comment]
Probably same as https://github.com/realm/realm-java/issues/3827

**Comment by RJFares** [comment]
You were right, it was about the order of applied plugin, would've never guessed.
i swapped the apt processor to go above realm plugin and it was ok.
apply plugin: 'android-apt'
apply plugin: 'realm-android'
