### ISSUE TITLE
io.realm.internal.Table io.realm.Realm.getTable(java.lang.Class)' is inaccessible

### ISSUE THREAD

**Issue by mgoyanes** [realm/realm-java#3841]
Hi.

Using realm (version 2.2.0) in my aar. I the proguard rules of the aar I've added this:

```
-keep class io.realm.annotations.RealmModule
-keep @io.realm.annotations.RealmModule class *
-keep class io.realm.internal.Keep
-keep @io.realm.internal.Keep class * { *; }
-keep class io.realm.internal.KeepMember
-keep @io.realm.internal.KeepMember class * { @io.realm.internal.KeepMember *; }
-dontwarn javax.**
-dontwarn io.realm.**
-keep class io.realm.RealmCollection
-keep class io.realm.OrderedRealmCollection
-keepclasseswithmembernames class io.realm.** {
    native <methods>;
}
-keep class io.realm.internal.Table
```

After setting the aar in a demo app and setting realm, I'm getting this error in release mode:

`java.lang.IllegalAccessError: Method 'io.realm.internal.Table io.realm.Realm.getTable(java.lang.Class)' is inaccessible to class 'hu' (declaration of 'hu' appears in /data/app/com.pushmgm-1/base.apk)
                                                     at hu.b(Unknown Source)
                                                     at io.realm.DefaultRealmModuleMediator.insertOrUpdate(Unknown Source)
                                                     at io.realm.Realm.insertOrUpdate(Realm.java:1035)
                                                     at ac.e(Unknown Source)
                                                     at gb.h(Unknown Source)
                                                     at gb.a(Unknown Source)
                                                     at gb.a(Unknown Source)
                                                     at ay.f(Unknown Source)`

Any idea why?

Thanks

**Comment by Zhuinden** [comment]
I always use these rules with Realm

```
#realm
-keepnames public class * extends io.realm.RealmObject
-keep @io.realm.annotations.RealmModule class *
-keep class io.realm.** { *; }
-dontwarn javax.**
-dontwarn io.realm.**

#realm 0.84.1+
-keep class io.realm.annotations.RealmModule
-keep @io.realm.annotations.RealmModule class *
-keep class io.realm.internal.Keep
-keep @io.realm.internal.Keep class *
-dontwarn javax.**
-dontwarn io.realm.**

#realm 0.89.0+
-keep class io.realm.RealmCollection
-keep class io.realm.OrderedRealmCollection
```

I got them a while ago. At least one of them should help

**Comment by zaki50** [comment]
Does your app work when you removed your pro guard rules?

**Comment by mgoyanes** [comment]
@Zhuinden Removed my rules and replaced for yours and it worked (at least in my initial tests) so now must discover what line(s) yours rules differ from mine (suspect is -keep class io.realm.** { *; } but is overkill).

@zaki50 Removed all the rules but the problem still remains.

**Comment by zaki50** [comment]
Hmm, what is the original fully qualified class name of the `hu`?

**Comment by mgoyanes** [comment]
I'm not able to reproduce the issue anymore :(

Closing.

Thanks for the help
