### ISSUE TITLE
Different RealmResult on the same query

### ISSUE THREAD

**Issue by krcho** [realm/realm-java#3842]
I want to get Always UPDATED RealmResult.

I did update table like this

```java
public void stockMasterlistInsert(ExchangeCountry e, List<StockMaster> list) {
     Log.d("REALMDEBUG", "INSERT SIZE : " + list.size());
     Realm realm = getRealm();
     realm.beginTransaction();
     realm.copyToRealmOrUpdate(list);
     realm.commitTransaction();
     realm.close();
 }
```

after update is complete, I query like this
```java
public RealmResults<StockMaster> getStockMasterList(ExchangeCountry e) {
    RealmResults<StockMaster> results =
                    getRealm()
                    .where(StockMaster.class)
                    .equalTo("exchangeCountry", e.name())
                    .findAll();
    Log.d("REALMDEBUG", e.name() + " StockMasterList SIZE : " + results.size());
    return results;
}
```

And, go to using activity, the query result is wrong - the before state data -

Look my Log
```
11-25 11:18:50.195 D/REALMDEBUG: ------------------DOWNLOAD PROCESS -------------------
11-25 11:18:50.217 D/REALMDEBUG: KOREA StockMasterList SIZE : 2575
11-25 11:18:50.217 D/REALMDEBUG: DELISTED SIZE : 2575
11-25 11:18:54.587 D/REALMDEBUG: INSERT SIZE : 2576
11-25 11:18:57.702 D/REALMDEBUG: KOREA StockMasterList SIZE : 2576
11-25 11:18:57.705 D/REALMDEBUG: DELETED SIZE : 0

11-25 11:19:32.841 D/REALMDEBUG: KOREA StockMasterList SIZE : 2575
```

The data is Stock data. so the Index is never change 
just "delisted" or newly insert

#### Version of Realm and tooling
Realm version(s): 1.2.0
Realm sync feature enabled: no
Android Studio version: 2.2.2
Which Android version and device: API 23

**Comment by Zhuinden** [comment]
There isn't enough code here to know the exact context.

**Comment by krcho** [comment]
@Zhuinden more source code is added!

**Comment by Zhuinden** [comment]
> And, go to using activity, the query result is wrong - the before state data -

Do you listen for changes in the Realm using `RealmChangeListener` added to a `RealmResults` that is stored in a field variable?

**Comment by krcho** [comment]
I solve this issue. 
using waitforchange() 
https://gist.github.com/cmelchior/8786ec511f7e1f47673935a26f568106
