### ISSUE TITLE
Setting up development environment

### ISSUE THREAD

**Issue by HelderAntunes** [realm/realm-java#3845]
Hi, I would like to understand and contribute to this project. For this, I would like to know which tools (Android Studio or other) are necessary to easily run unit tests.

I tried to follow README.md, but I can´t run unit tests in android studio. Is there any more specific tutorial about this?

**Comment by zaki50** [comment]
What error do you get?

**Comment by Zhuinden** [comment]
There is https://github.com/realm/realm-java/tree/master/examples/unitTestExample

**Comment by zaki50** [comment]
We are developing Realm Java with latest Android Studio and can run unit tests from Android Studio.

Are you creating AndroidTest launch configuration?

**Comment by HelderAntunes** [comment]
When i run `./gradlew assemble` i get the error:

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':realm-library'.
> NDK not configured. 
  Download it with SDK manager.)

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.
```

I download NDK version 13.1.3345770 with SDK manager, but give me the same error again.

**Comment by Zhuinden** [comment]
You need NDK R10e

**Comment by HelderAntunes** [comment]
yes, but where i put that file?

**Comment by Zhuinden** [comment]
I think anywhere works, but you also need to set an environment variable that points to it. 

What OS are you on? I actually gave up on *compiling* Realm on Windows.

**Comment by HelderAntunes** [comment]
I'm on ubuntu 14.04.

I run: `export ANDROID_NDK_HOME=/home/helder/android-ndk-r10e-linux-x86_64.bin `

`/home/helder/android-ndk-r10e-linux-x86_64.bin` is where i save the file.

**Comment by HelderAntunes** [comment]
give me the same error:

```
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':realm-library'.
> NDK not configured. /home/helder/android-ndk-r10e-linux-x86_64.bin
  Download it with SDK manager.)

* Try:
Run with --stacktrace option to get the stack trace. Run with --debug option to get more log output.

```

**Comment by zaki50** [comment]
`android-ndk-r10e-linux-x86_64.bin` is an archive of the NDK.
You need to install it.

See http://stackoverflow.com/questions/26967722/how-to-install-android-ndk-in-linux

**Comment by HelderAntunes** [comment]
Thanks, I got it. 

I did `./gradlew assemble` and `./gradlew installRealmJava`. Now, i imported the project into android studio, but i don't know how to run tests.  How do i create the Unit test configuration?

**Comment by zaki50** [comment]
nothing special.
Just the same as usual Android test for Android application.

**Comment by HelderAntunes** [comment]
I follow [this]( https://github.com/realm/realm-java/tree/master/examples/unitTestExample), and i get this error:` Error running ExampleActivityTest: No junit.jar in Module 'realm-java'`

**Comment by zaki50** [comment]
That's JVM test, not Android test.

You need to create a launch configuration of `Android Tests` (or `Android Instrumented Tests`).

Don't forget to choose `realm-library` module in the configuration.

![2016-11-30 3 43 44](https://cloud.githubusercontent.com/assets/406660/20723775/3ac5a71e-b6af-11e6-833d-9b18be38ddb0.png)

**Comment by HelderAntunes** [comment]
I don't have the option Android Instrumented Tests.
[screenshot](https://postimg.org/image/ravyxeja3/)

**Comment by Zhuinden** [comment]
@HelderAntunes are you sure it's not in the + sign menu?

**Comment by HelderAntunes** [comment]
In + sign i get this:
![screenshot from 2016-11-29 19 07 05](https://cloud.githubusercontent.com/assets/15159872/20724755/59815bb4-b667-11e6-97fe-41ddd0a58167.png)

**Comment by zaki50** [comment]
`Android Tests` is the way you should go.

**Comment by HelderAntunes** [comment]
Module won't show up in Edit Configuration.

![screenshot from 2016-11-30 19 39 26](https://cloud.githubusercontent.com/assets/15159872/20768179/d5b65e78-b734-11e6-928e-fe40f81e972a.png)

Other question: to run tests it's necessary connect a device to Android Studio?

**Comment by zaki50** [comment]
You need a device or emulator to run the tests.

No idea why you can't see the module.
Did you import `realm` folder as a project instead of root folder?

**Comment by HelderAntunes** [comment]
I import the project this way:
- Select the option `Import project(Eclipse ADT, Gradle, etc.)`.
![screenshot from 2016-12-01 18 42 43](https://cloud.githubusercontent.com/assets/15159872/20807338/67de8e1c-b7f6-11e6-9424-8842bc0bb5f3.png)
- Choose the path of build.gradle in root folder. 
![screenshot from 2016-12-01 18 43 56](https://cloud.githubusercontent.com/assets/15159872/20807339/6b008bfe-b7f6-11e6-94b3-7691d492629a.png)

Is it supposed to import in another way?

**Comment by zaki50** [comment]
You need to import `examples`, `gradle-plugin`, `realm`, `realm-annotation`, `realm-transformer` in the directory separately.

https://github.com/realm/realm-java/blob/master/README.md#gotchas

**Comment by HelderAntunes** [comment]
Ok, i did it. But now, i get an error about the environment variable `Android_NDK_HOME`. 
I check `ndk.dir` in local.properties of realm and set the environment variable `Android_NDK_HOME`.

![screenshot from 2016-12-02 21 38 13](https://cloud.githubusercontent.com/assets/15159872/20851477/aa0ca282-b8d8-11e6-8806-512a0370a4cf.png)

**Comment by HelderAntunes** [comment]
As long as I can not run the tests, is someone able to give me the current number of tests and the current test coverage?

Also I have some questions about the testing process (for a university course):

- Does the coverage of unit tests need to be greater than a certain value?
- What technologies do you use for unit testing?
- Is there any tool you use that checks, for example, if the code style complies with the standards?

**Comment by zaki50** [comment]
You need to set `ANDROID_NDK_HOME ` environment variables  for Android Studio.
There are several ways to achieve that. The easiest way it to launch Android Studio from the command line.

**Comment by zaki50** [comment]
See https://github.com/realm/realm-java/blob/master/Jenkinsfile for our testing.
It is executed on out CI machine.

**Comment by zaki50** [comment]
I'll close this. If you have further questions, feel free to reopen this.

**Comment by HelderAntunes** [comment]
I ran the tests in android studio successfully. But I can not see the code coverage. Is it necessary to run the Jenkinsfile? If yes, how to do that?
