### ISSUE TITLE
Changing Realm data can only be done from inside a transaction.

### ISSUE THREAD

**Issue by AndroidJohnsonWang** [realm/realm-java#3846]
version:realm2.2.0.
![image](https://cloud.githubusercontent.com/assets/15881869/20654399/e59f8df6-b553-11e6-86c0-23cae4008319.png)
RecyclerView loadMore(addAll),addData is error, eShows is a RealmList;
but setNewData is List=RealmList.this is success;
![image](https://cloud.githubusercontent.com/assets/15881869/20654449/6191442c-b554-11e6-94c6-32c273311324.png)
How to solve this problem?
RecyclerView loadMore is popular,I hope the problem can be solved，Thanks.

**Comment by zaki50** [comment]
When you add a data to managed `RealmList`, you need to execute it in a transaction.

**Comment by AndroidJohnsonWang** [comment]
I do not have to save it, I just want to increase the RecyclerView List data only

**Comment by zaki50** [comment]
If you don't want to persist the change, you need to use unmanaged `RealmList`.
Managed `RealmList` is bound to the database file and any change to it is reflected to the database file.

**Comment by Zhuinden** [comment]
I don't understand what you mean by "increase RecyclerView size only", why not use RealmResults directly with RealmRecyclerViewAdapter? It shows every element and listens to underlying changes in the database.

**Comment by zaki50** [comment]
I'll close this.

If you have further questions, feel free to reopen this.
