### ISSUE TITLE
Lags on long operations on One Plus 3 (OxygenOs) Android device, give ANR.

### ISSUE THREAD

**Issue by harshgaba** [realm/realm-java#3847]
Hello, Firstly, i really like the Realm, and its working great for me on mostly all android devices but i'm getting major lag issues on One Plus 3(OxygenOs, Android version 6.0), its a wide known android mobile device and our app have more than 6 percent users on this device. below is the description:- 

> What do you want to achieve?

 I have very big JSON which i'm parsing on background thread and saving the data in multiple tables in Realm in the same background thread, Basically i have a pagination Api call which give me result in pair of 20 rows set and my scenario is i hit the Api by using retrofit 2 then parse the data by Gson and then save the data in realm. And this process is going on till the app fetches all the data from server, and i'm hitting the API one by one which means first i hit data with page number one then parse the JSON and then save it into realm and then after successful save Realm operation, i again hit the data API. the whole scenerio is working fine on One Plus 3 if there is very data entries like 20 or 30 but if i have 150 to 1000 row entries then it lags very heavily because in this case, there are more number of API calls and then it lags, i tested it very deeply if there is same issues with my network calls but it works fine if i removed the Realm.

> Actual Results?

This is working fine on all devices but only on OxygenOs devices majorly on One Plus 3 its lags very heavily and give ANR every time, even for small Realm Table operations like update , delete or add any entry in table, my code is working fine on every devices. but only on this devices it lags.
Here is the device link if you want to check:- https://oneplusstore.in/3/oxygenos 

> Describe your current debugging efforts.

->I debug it with various method by firstly checking the debugger and monitor of Android studio 2.2,
-> then i tried with checking some third party library like Pury, which provides execution time of every method and it gives long execution time on table operations methods.
-> then finally, i tried with native sqlite by replacing realm, with the same table structure and operations and then its working fine on OxygenOs and mainly on One Plus 3.

#### Version of Realm and tooling
Realm version(s):  I'm using the latest version of realm as per on doc in today's date.

Realm sync feature enabled: yes

Android Studio version: 2.2

Which Android version and device: Android version 6.0, OxygenOs and device is One Plus 3,
https://oneplusstore.in/3/oxygenos

**Comment by harshgaba** [comment]
Here is my Function:-

public boolean saveToRealm(Context context, final List<NewBookmark> bookmarksList) {
        System.gc();
        Realm realm = Realm.getDefaultInstance();

        realm.executeTransaction(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {
                Log.wtf("bookDb", bookmarksList.size() + " ");
                for (int i = bookmarksList.size() - 1; i >= 0; i--) {
                    Log.wtf("bookDb", bookmarksList.size() + " " + bookmarksList.get(i).getType());

                    if (bookmarksList.get(i).getArticle() != null) {
                        if (!checkIfBookmarkExists(bookmarksList.get(i).getArticle().getId())) {
                            Bookmark object = realm.createObject(Bookmark.class);
                            object.setId(bookmarksList.get(i).getArticle().getId());
                            object.setWpId(bookmarksList.get(i).getArticle().getWpId());
                            object.setType(bookmarksList.get(i).getType());
                            object.setTitle(bookmarksList.get(i).getArticle().getTitle());
                            if (bookmarksList.get(i).getArticle().getMore() != null) {
                                if (bookmarksList.get(i).getArticle().getMore().getFeaturedImage() != null) {
                                    if (bookmarksList.get(i).getArticle().getMore().getFeaturedImage().getAttachmentMeta() != null) {
                                        if (bookmarksList.get(i).getArticle().getMore().getFeaturedImage().getAttachmentMeta().getSizes() != null) {
                                            if (bookmarksList.get(i).getArticle().getMore().getFeaturedImage().getAttachmentMeta().getSizes().getThumbnail() != null) {
                                                object.setImage(bookmarksList.get(i).getArticle().getMore().getFeaturedImage().getAttachmentMeta().getSizes().getThumbnail().getUrl());
                                            }
                                        }
                                    }
                                }
                            }
                            if (bookmarksList.get(i).getArticle().getCategories() != null) {
                                if (bookmarksList.get(i).getArticle().getCategories().size() != 0) {
                                    object.setCategoryId(bookmarksList.get(i).getArticle().getCategories().get(0).getId());
                                    object.setCategoryTitle(bookmarksList.get(i).getArticle().getCategories().get(0).getTitle());
                                    object.setCategoryIcon(bookmarksList.get(i).getArticle().getCategories().get(0).getIcon());
                                }
                            }
                            object.setSlug(bookmarksList.get(i).getArticle().getSlug());
                            object.setLocation(bookmarksList.get(i).getArticle().getProvider());
                            object.setBookmarkState(1);
                            object.setBookmarkStatus(1);
                            object.setTimestamp(Utils.IsoToEpoch(bookmarksList.get(i).getCreated()));
                        }
                    } else if (bookmarksList.get(i).getEvent() != null) {
                        if (!checkIfBookmarkExists(bookmarksList.get(i).getEvent().getId())) {

                            Bookmark object = realm.createObject(Bookmark.class);
                            object.setId(bookmarksList.get(i).getEvent().getId());
                            object.setWpId("");
                            object.setType(bookmarksList.get(i).getType());
                            object.setTitle(bookmarksList.get(i).getEvent().getName());
                            if (bookmarksList.get(i).getEvent().getThumbnail() != null)
                                object.setImage(bookmarksList.get(i).getEvent().getThumbnail());
                            else {
                                if (bookmarksList.get(i).getEvent().getFeaturedImage() != null)
                                    object.setImage(bookmarksList.get(i).getEvent().getFeaturedImage());
                            }

                            if (bookmarksList.get(i).getEvent().getTags() != null) {
                                if (bookmarksList.get(i).getEvent().getTags().size() != 0) {
                                    object.setCategoryId(bookmarksList.get(i).getEvent().getTags().get(0).getId());
                                    object.setCategoryTitle(bookmarksList.get(i).getEvent().getTags().get(0).getSlug());
                                    object.setCategoryIcon("");
                                }
                            }
                            object.setSlug("");
                            object.setLocation(bookmarksList.get(i).getEvent().getProvider());
                            if (bookmarksList.get(i).getEvent().getPlace() != null) {
                                object.setPlaceId(bookmarksList.get(i).getEvent().getPlace().getId());
                                if (bookmarksList.get(i).getEvent().getPlace().getLocation().getLocality() != null) {
                                    if (bookmarksList.get(i).getEvent().getPlace().getLocation().getLocality().size() > 0)
                                        object.setPlaceName(bookmarksList.get(i).getEvent().getPlace().getName() + ", " + bookmarksList.get(i).getEvent().getPlace().getLocation().getLocality());
                                    else
                                        object.setPlaceName(bookmarksList.get(i).getEvent().getPlace().getName());
                                } else
                                    object.setPlaceName(bookmarksList.get(i).getEvent().getPlace().getName());
                            } else {
                                if (bookmarksList.get(i).getEvent().getMore() != null) {
                                    if (bookmarksList.get(i).getEvent().getMore().getPlace() != null)
                                        object.setPlaceName(bookmarksList.get(i).getEvent().getMore().getPlace());
                                }
                            }

                            if (bookmarksList.get(i).getEvent().getStart() != null)
                                object.setStartTime(bookmarksList.get(i).getEvent().getStart());

                            if (bookmarksList.get(i).getEvent().getEnd() != null)
                                object.setEndTime(bookmarksList.get(i).getEvent().getEnd());

                            if (bookmarksList.get(i).getEvent().getStartingOn() != null)
                                object.setStartingOn(bookmarksList.get(i).getEvent().getStartingOn());

                            object.setBookmarkState(1);
                            object.setBookmarkStatus(1);
                            object.setTimestamp(Utils.IsoToEpoch(bookmarksList.get(i).getCreated()));

                        }
                    }

                }
            }
        });


        return true;

    }

**Comment by Zhuinden** [comment]
It's because you call `System.gc()` manually, and also because you use `realm.createObject(Bookmark.class)` instead of using 1 unmanaged object with `insertOrUpdate()` to create the managed RealmObject

What version of Realm are you using?

**Comment by harshgaba** [comment]
I called System.gc() manually, because it shows too much memory consumption in Android monitor, but by using this it does not any impact on performance, this issue is still if i removed the System.gc() and I'm using:- 

io.realm:realm-gradle-plugin:1.0.1
'io.realm:android-adapters:1.3.0'

and sorry i'm not getting that unmanaged and managed object, can you explain it in detail, it will be more helpful for me to debug it. My (Bookmark.class ) is a class which extends RealmObject. Here is the below classes:-


public class Bookmark extends RealmObject {
//    @PrimaryKey
//    private int order;
    private String id;
    private String wpId;
    private String type;
    private String image;
    private String title;
    private String categoryTitle;
    private String categoryId;
    private String categoryIcon;
    private String slug;
    private String location;
    private String placeId;
    private String placeName;
    private String startTime;
    private String endTime;
    private String startingOn;
    private int bookmarkState;
    private int bookmarkStatus;
    private long timestamp;

//all getter and setters..
}

and here is my Api POJO class:-

public class NewBookmark {

    @SerializedName("_id")
    @Expose
    private String id;
    @SerializedName("article")
    @Expose
    private Article article;
    @SerializedName("event")
    @Expose
    private EventDetail event;
    @SerializedName("__v")
    @Expose
    private Integer v;
    @SerializedName("created")
    @Expose
    private String created;
    @SerializedName("reminders")
    @Expose
    private List<Object> reminders = new ArrayList<Object>();
    @SerializedName("user")
    @Expose
    private String user;
    @SerializedName("type")
    @Expose
    private String type;

// all getter and setters.
}

**Comment by Zhuinden** [comment]
You should batch-insert like this http://stackoverflow.com/a/39385985/2413303

**Comment by harshgaba** [comment]
Ok, cool , i didn't know about the insertOrUpdate() method, I will try this and update you about the performance.

**Comment by Zhuinden** [comment]
Well technically it was added in 1.1.0, so you should update your Realm version to 1.1.1

Don't worry, 1.1.1 is stable, actually it's more stable than 1.0.1

**Comment by beeender** [comment]
@harshgaba My feeling is your `System.gc()` call caused different behaviors as @Zhuinden said. The batch-insert may solve your problem.

But if you are still meeting the problem with it, please get some information to debug:
1. Update the Realm to the latest, (v2.2.0)
2. Enable some logs by calling `RealmLog.setLevel(LogLevel.ALL);` after `Realm.init()`
3. Get full logs with the non-one-plus devcies and logs with one-plus device so we can compare with thread and time enable logcat (` adb logcat -v thread -v time`)

**Comment by Zhuinden** [comment]
@harshgaba actually, you should update only to Realm 1.1.1 as I said and switch to `insertOrUpdate`, then see if it helped fix your issue :slightly_smiling_face:

**Comment by harshgaba** [comment]
ok cool, i will try this and then send you the All logs, 👍

**Comment by Zhuinden** [comment]
@harshgaba oh by the way, I've just remembered after looking at your code - if you are saving this data on a background thread (which you should), then you should definitely not forget to close your Realm.

public boolean saveToRealm(Context context, final List<NewBookmark> bookmarksList) {
        ///////System.gc();
        Realm realm = null;
        try {
            realm = Realm.getDefaultInstance();

            realm.executeTransaction(new Realm.Transaction() { // on background thread!
                @Override
                public void execute(Realm realm) {
                    Log.wtf("bookDb", bookmarksList.size() + " ");
                    for (int i = bookmarksList.size() - 1; i >= 0; i--) {
                         // ....
                    }
                }
            });
        } finally {
            if(realm != null) {
                realm.close();
            }
        }
        return true;
    }

**Comment by diegomontoya** [comment]
@harshgaba do you know how many unnecessary java objects you are creating in your code? If you continue to write in this fashion, it doesn't matter if you use realm or not, your app will slow down if there are more code like this everywhere.

**Comment by kneth** [comment]
@harshgaba Did you find a solution?

**Comment by harshgaba** [comment]
Hello @kneth, Sorry i was out from city,  insertOrUpdate() not solved my problem, i also optimised my code and batch-insert like this http://stackoverflow.com/a/39385985/2413303. but the problem is same.

 public boolean saveToRealm(Context context, final List<NewBookmark> bookmarksList) {
 Realm realm = Realm.getDefaultInstance();
       try {
           realm.executeTransaction(new Realm.Transaction() {
             @Override
               public void execute(Realm realm) {
                   realm.insertOrUpdate(bookmarks);
             }
         });
       } catch (Exception e) {
          e.printStackTrace();
        } finally {
           realm.close();
     }}

**Comment by kneth** [comment]
@harshgaba I have reopened the issue, and we need to investigate it. Have you seen the issue with other devices?

**Comment by kneth** [comment]
@harshgaba Could you try to upgrade to 2.3.0 and report back?

**Comment by bmeike** [comment]
@harshgaba Any news?  If we can be of further help, please let us know.  Otherwise we can close this ticket.

**Comment by kneth** [comment]
I'll close the issue. Don't hesitate to reopen or create new issue.
