### ISSUE TITLE
Restore Realm Database auto Update

### ISSUE THREAD

**Issue by Amit-khatkar** [realm/realm-java#3849]
I used [Restore realm database](https://medium.com/glucosio-project/example-class-to-export-import-a-realm-database-on-android-c429ade2b4ed#.hm8t6zgrf) method to backup and restore database. everything was working fine but then i noticed that on clicking restore database it restores the database but updates it in next launch or on restart of app. Is there any way we can use the restored Realm database without restarting the app?

**Comment by zaki50** [comment]
Closing all Realm instances in all threads solves this.

You can use https://realm.io/docs/java/2.2.0/api/io/realm/Realm.html#getGlobalInstanceCount-io.realm.RealmConfiguration- and https://realm.io/docs/java/2.2.0/api/io/realm/Realm.html#getLocalInstanceCount-io.realm.RealmConfiguration- to check the open instances count.

**Comment by Amit-khatkar** [comment]
I tried closing all instances but it causes crash

**Comment by Zhuinden** [comment]
So what is the crash

**Comment by Amit-khatkar** [comment]
java.lang.IllegalStateException: Illegal State: Table is closed, and no longer valid to operate on.

**Comment by Zhuinden** [comment]
Ah. Well, you shouldn't be reading from closed Realm instances while you're restoring stuff. Or at least, you should requery them after the new Realm is open from the new Realm file.

**Comment by Amit-khatkar** [comment]
i'm closing instance in adapter then it occurs.

**Comment by Zhuinden** [comment]
Why is your Realm lifecycle management inside the adapter?

**Comment by Amit-khatkar** [comment]
I'm using Recyclerview and card view so it fetch the data from realm database and bind the views

**Comment by Zhuinden** [comment]
`RealmRecyclerViewAdapter`?

**Comment by Amit-khatkar** [comment]
yes it extends RealmRecyclerViewAdapter

**Comment by Zhuinden** [comment]
...great, now you're running into https://github.com/realm/realm-android-adapters/issues/58

**Comment by zaki50** [comment]
I made a PR (realm/realm-android-adapters#71) to fix realm/realm-android-adapters#58

**Comment by Amit-khatkar** [comment]
`Intent mainIntent = new Intent(Settings.this, Settings.class);
                mainIntent.addFlags(Intent.FLAG_ACTIVITY_CLEAR_TASK  );
                startActivity(mainIntent);
                System.exit(2);`

adding this restarts the app and it loads data correctly

**Comment by zaki50** [comment]
I'll close this.
If you have further questions, feel free to reopen this.
