### ISSUE TITLE
Overriding hashCode() has effect on copyToRealmOrUpdate(Iterable<E> objects)

### ISSUE THREAD

**Issue by TimCastelijns** [realm/realm-java#3857]
#### Goal

> What do you want to achieve?

Store a list of Asset objects that have a custom implementation for `equals()` and `hashCode()` in Realm, using `Realm.copyToRealmOrUpdate(Iterable<E> objects)`.

#### Expected Results

I expected all Asset objects to be stored, regardless of the return value for `equals()` and `hashCode()`. The [documentation](https://realm.io/docs/java/latest/#models) for this says that I can provide a custom implementation for `equals()`, but it does not mention `hashCode()`. [My source](http://stackoverflow.com/questions/27581/what-issues-should-be-considered-when-overriding-equals-and-hashcode-in-java) however says that if you override `equals()` you should also override `hashCode()`, which is why I did.

#### Actual Results

Assets that are evaluated to be equal to a previously processed Asset (through calling `hashCode()`) are not stored in Realm.

#### Steps & Code to Reproduce

> Describe your current debugging efforts.

I have a `List<Asset> assets` with 138 self-created Asset objects. 17 of these have the same mac address (`""`). Only the first one is stored in Realm, the rest seems ignored without a warning log message.

#### Code Sample

```java

public class Asset extends RealmObject {
    @PrimaryKey
    private long id;
    private String macAddress;

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getMacAddress() {
        return macAddress;
    }

    public void setMacAddress(String macAddress) {
        this.macAddress = macAddress;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;
        Asset asset = (Asset) o;
        return Objects.equals(macAddress, asset.macAddress);
    }

    @Override
    public int hashCode() {
        return Objects.hash(macAddress);
    }
}

public class AssetLocalRepository {
    public static void storeAssets(List<Asset> assets) {
        Log.d("realm", "size= " + assets.size());
        Realm realm = Realm.getDefaultInstance();
        realm.executeTransaction(realm1 -> realm1.copyToRealmOrUpdate(assets));
        Log.d("realm", "q ct= " + realm.where(Asset.class).count());
        realm.close();
    }
}
```

When I call `storeAssets(assets)` where `assets` contains 121 assets with a unique value for mac address and 17 assets that have the same mac address (`""`), it logs 

```
size= 138
q ct= 122
```
When I inspect with stetho-realm, I see only one Asset with mac address `""`.

If I comment out the overridden implementation of `hashCode()`, it logs

```
size= 138
q ct= 138
```
When I the inspect with stetho-realm, I see all 17 Assets with mac address `""`.

If I change the overridden method implementation to
```java
@Override
public int hashCode() {
    return 1;
}
```

it logs
```
size= 138
q ct= 1
```

It stores only the first, because all that follow are evaluated to be equal.

#### Version of Realm and tooling
Realm version: 1.2.0

Realm sync feature enabled: no

Android Studio version: 2.3 Canary 1

Which Android version and device: 6.0.1, OnePlus One

**Comment by Zhuinden** [comment]
The code in `copyToRealmOrUpdate` starts with

    return copyOrUpdate(object, true, new HashMap<RealmModel, RealmObjectProxy>());

Where the `hashMap` is the cache.

Have you considered using `insertOrUpdate()`, which is much faster in this particular use-case?

Another option would be

        realm.executeTransaction(realm1 -> {
            for(Asset asset : assets) {
                realm1.insertOrUpdate(asset);
            }
        });

**Comment by cmelchior** [comment]
@TimCastelijns That is the expected behavior. `equals/hashcode` is a pair. In your implementation you only compare the `macAddress` ignoring the `id`. So all normal Java semantics would assume that your objects are equal even with different ID's. In your case it sounds like those objects aren't truely equal if they have different `id`'s, so you should modify your equals/hashcode to also include the `id`.

**Comment by TimCastelijns** [comment]
@cmelchior I came up with this implementation a long time ago. The idea was to be able to maintain a List<Asset> where no asset in that list had the same mac address as another. The ids are not important for that list

**Comment by TimCastelijns** [comment]
@Zhuinden I will try that, thanks for the suggestion. I did not know about the caching in `copyToRealmOrUpdate()`. I assume the following would be equal to your example?
```java
realm.executeTransaction(realm1 -> {
        realm1.insertOrUpdate(assets);
});
```

**Comment by MarkOSullivan94** [comment]
> Would it be reasonable to request a note about consequences of overriding hashCode() to be added to the documentation?

This would be great. I wasn't aware of the potential consequences until I seen this issue.

**Comment by cmelchior** [comment]
@TimCastelijns Yes, that is the purpose of overriding equals/hashcode, but in your case you are mixing responsibilities. In one case you want id to matter (when inserting into Realm), in the other you don't (when part of your list).

I see a number of options: 
1) Make the mac-address the primary key instead (id `id` isn't used anyway)
2) Make a specialized `List` class that only checks the `macAddress` when inserting objects
3) Create a new non-Realm `Asset` class with different equal/hashcode implementations and methods for converting between them.

**Comment by cmelchior** [comment]
@MarkOSullivan94 I wouldn't be against further documentation as such, but Realm behaves just like any standard Java collection in this regard. E.g. inserting those `Asset` objects into a `Set` would also only result in one mac address being present in the end.

**Comment by TimCastelijns** [comment]
@cmelchior Thanks :) I will most likely go with option 2 for my use case.

I was not aware of scenarios where Realm behaves like a Collection. Now that I am, it makes a lot more sense. Thanks for the clarification.

**Comment by cmelchior** [comment]
No problem 👍 . Closing
