### ISSUE TITLE
Not compatible with Blackberry Z3.

### ISSUE THREAD

**Issue by mihirjoshi21** [realm/realm-java#3858]
Realm version(s): 2.2.0

Realm sync feature enabled:  No

Android Studio version: 2.1.2

Which Android version and device: Blackberry z3

**Comment by Zhuinden** [comment]
root cause https://github.com/realm/realm-java/issues/3735

**Comment by FabianTerhorst** [comment]
You can downgrade to 1.x when you want bb support.

**Comment by Zhuinden** [comment]
Yup, 1.1.1 or 1.2.0.

Beware that Realm files created by Realm 2.x cannot be read by Realm 1.x

**Comment by mihirjoshi21** [comment]
I rather wait for the bug to get fixed. There are not many users who have blackberry

**Comment by kneth** [comment]
Please read https://realm.io/docs/java/latest/#blackberry-devices.

**Comment by beeender** [comment]
@mihirjoshi21 Do you have a complete exception log and more information for this problem? It might be an different problem with #3735 .

I just tested `v2.2.0` with blackberry z10, It worked fine.

**Comment by Zhuinden** [comment]
@beeender I'd assume the problem is those funky blackberry devices like Rim Passport and co

**Comment by Zhuinden** [comment]
@mihirjoshi21 do you know anything about this issue?

**Comment by beeender** [comment]
I guess there are quite a few users are using z3 right now. close it.

**Comment by Zhuinden** [comment]
Yeah, Blackberry is dead.
