### ISSUE TITLE
io.realm.exceptions.RealmError  Unrecoverable error. Permission denied

### ISSUE THREAD

**Issue by deco-ding** [realm/realm-java#3859]
Version:Realm2.2.1
Realm mRealm = Realm.getDefaultInstance();

Unrecoverable error. Permission denied in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 92

io.realm.internal.SharedRealm.nativeGetSharedRealm(Native Method)
io.realm.internal.SharedRealm.a(SharedRealm.java:205)
io.realm.internal.SharedRealm.a(SharedRealm.java:182)
io.realm.t.a(RealmCache.java:124)
io.realm.r.l(Realm.java:209)

![image](https://cloud.githubusercontent.com/assets/4246885/20739254/1730d5cc-b6f4-11e6-9892-f3aa3f002390.png)

**Comment by beeender** [comment]
@deco-ding Do you create the Realm file on the external storage? Can you please share your `RealmCofiguration`?

**Comment by deco-ding** [comment]
@beeender Just using default config
private void initRealmDB() {
    Realm.init(this);
    RealmConfiguration configuration = new RealmConfiguration.Builder()
        .name(RealmBaseHelper.DB_NAME)
        .deleteRealmIfMigrationNeeded()
        .build();
    Realm.setDefaultConfiguration(configuration);
  }

**Comment by beeender** [comment]
@deco-ding Are you using a testing farm to do the test? Which one is it? I can try to reproduce it from our side.

**Comment by deco-ding** [comment]
@beeender  I have not used

**Comment by diegomontoya** [comment]
@deco-ding 你发的图片上看上去是用了自动测试服务。是那一家公司？

**Comment by deco-ding** [comment]
@diegomontoya tencent bugly

**Comment by beeender** [comment]
@deco-ding Can you reproduce the issue with any of your devices? I tried with my API 22 emulator but no luck :(

**Comment by deco-ding** [comment]
@beeender It‘s a release version and it always be all right, the crash is catched by tencent bugly.

**Comment by beeender** [comment]
Same issue with #3972 . close and dup this.

@deco-ding see my comments in #3972 , we are still not able to reproduce it :( If you have any more information, please comment in #3972.
