### ISSUE TITLE
filter With params failure but filter success With No params

### ISSUE THREAD

**Issue by AlasKuNull** [realm/realm-java#3864]
I sort object Success. 

model.barCode = @"1234";

NSInteger indx = [res indexOfObjectWhere:@"BarCode = %@ AND Type = 'Old'",model.barCode];
This Code return NotFound.

 NSInteger indx = [res indexOfObjectWhere:@"BarCode = '1234' AND Type = 'Old'"];
But This Code return 1

please help me,Thanks

**Comment by Zhuinden** [comment]
This looks eerily like Realm-Cocoa, so it should be in https://github.com/realm/realm-cocoa/issues

**Comment by AlasKuNull** [comment]
Thank you
