### ISSUE TITLE
Feature: expose a client identifier on SyncSession

### ISSUE THREAD

**Issue by dsjstc** [realm/realm-java#3865]
#### Goal

[As described here](http://stackoverflow.com/questions/40917766/any-way-to-differentiate-realm-object-server-clients), my synchronized objects need to have a relationship to the specific client that is working on them.  I see no property anywhere in Realm that uniquely identifies a client.

SyncUser can be logged concurrently from multiple clients.  

SyncSession.hashCode() might work, but INT32 is too small a hash-space for comfort, and besides, it is  non-persistent.  On Android, I would expect it to change after the Activity is destroyed (for example) by device rotation.

#### Expected Results

SyncSession (or perhaps SyncConfiguration) exposes a primitive identifier that consistently, uniquely, and persistently identifies the client.

**Comment by zaki50** [comment]
How about  generating UUID on each clients and use it as an if?

**Comment by cmelchior** [comment]
See also: https://developer.android.com/training/articles/user-data-ids.html

**Comment by Zhuinden** [comment]
I pass this one around between projects

``` java
//http://stackoverflow.com/a/17625641/2413303
public class PseudoUUIDGenerator {
    private static final String TAG = "PseudoUUIDGenerator";

    public static String getUniquePseudoID() {
        // If all else fails, if the user does have lower than API 9 (lower
        // than Gingerbread), has reset their phone or 'Secure.ANDROID_ID'
        // returns 'null', then simply the ID returned will be solely based
        // off their Android device information. This is where the collisions
        // can happen.
        // Thanks http://www.pocketmagic.net/?p=1662!
        // Try not to use DISPLAY, HOST or ID - these items could change.
        // If there are collisions, there will be overlapping data
        String m_szDevIDShort = "35" + (Build.BOARD.length() % 10) + (Build.BRAND.length() % 10) + (Build.DEVICE
                .length() % 10) +
                (Build.MANUFACTURER.length() % 10) + (Build.MODEL.length() % 10) + (Build.PRODUCT.length() % 10);

        // Thanks to @Roman SL!
        // http://stackoverflow.com/a/4789483/950427
        // Only devices with API >= 9 have android.os.Build.SERIAL
        // http://developer.android.com/reference/android/os/Build.html#SERIAL
        // If a user upgrades software or roots their phone, there will be a duplicate entry
        String serial = null;
        try {
            serial = android.os.Build.class.getField("SERIAL").get(null).toString();

            // Go ahead and return the serial for api => 9
            return new UUID(m_szDevIDShort.hashCode(), serial.hashCode()).toString();
        } catch(Exception e) {
            // String needs to be initialized
            serial = "serial"; // some value
        }

        // Thanks @Joe!
        // http://stackoverflow.com/a/2853253/950427
        // Finally, combine the values we have found by using the UUID class to create a unique identifier
        return new UUID(m_szDevIDShort.hashCode(), serial.hashCode()).toString();
    }
}
```

**Comment by zaki50** [comment]
Does that code work in multi user environment?

Using device dependent identifier is not a good idea in most cases.

**Comment by Zhuinden** [comment]
@zaki50 well this **does** generate a device-dependent identifier without taking current user into account, but that can be added into it somewhere

**Comment by dsjstc** [comment]
Thanks folks, hadn't thought of a persisted UUID on the client side, but it ought to take care of my immediate need.  I'll close the issue; I see no other functionality from this request that will be useful until there's an [object-level permissions feature](https://github.com/realm/realm-mobile-platform/issues/22#issuecomment-259534739).

@cmelchior, thanks for the link.  Hadn't run across that, and it's important reading.
