### ISSUE TITLE
Exception in 2.2.1 version. RealmObject is not part of the schema for this Realm

### ISSUE THREAD

**Issue by Rotenkampf** [realm/realm-java#3867]
Hello. I use a Realm in my project for two month and i love it. But recently i updated Realm version from 2.1.1 to 2.2.1 and clean project. After that when i want to grab or add data from/to Realm, i have next exception: 
xxx is not part of the schema for this Realm. (xxx is name of my RealmObject)
#### Goal

I want know how to upgrade my Realm without this exception;

#### Actual Results

The only solution for me now - is downgrade version of Realm to 2.1.1

#### Steps & Code to Reproduce

just update to 2.2.1

#### Version of Realm and tooling
Realm version(s): 2.2.1

Realm sync feature enabled: no

Android Studio version: 2.2.2

Which Android version and device: 5.0.1 SM-T531

**Comment by Zhuinden** [comment]
root cause https://github.com/realm/realm-java/issues/3827

**Comment by Rotenkampf** [comment]
ok. I was blind. Changing order of plugins really make a difference
