### ISSUE TITLE
Remove final modifers from public classes

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#3869]
So the question of testability and Mockito keeps coming up in support. Mockito still doesn't support final classes and PowerMock seems to cause problems for people.

Would anyone have big objections if I removed the `final` modifier from our public classes? It would be less pure, but more pragmatic.

Thoughts @realm/java ?

Affected classes:

- Realm
- RealmResults
- RealmQuery
- RealmList
- RealmConfiguration
- RealmSchema
- RealmObjectSchema
- DynamicRealm
- DynamicRealmObject

- SyncConfiguration
- SyncManager
- SyncSession
- SyncUser
- SyncCredentials

**Comment by kneth** [comment]
How likely is it that someone will extend any of these classes? And what consequence will that have?

**Comment by cmelchior** [comment]
Probably very unlikely. Subclassing in most cases is useless since we generate almost all the classes internally. Subclassing would be harmless in most cases unless you started to tinker with the internal state which could potentially break a lot of things.

IMO I would just document it as as such. "We remove the final modifier to make testing easier, but still consider all non-public fields/methods private API's that can change without warning."

**Comment by beeender** [comment]
Sounds good to me. :+1:

**Comment by zaki50** [comment]
:+1:

**Comment by dalinaum** [comment]
:+1:
