### ISSUE TITLE
How to close realm safely when app crash?

### ISSUE THREAD

**Issue by xturbofan** [realm/realm-java#3872]
I save data in a Activity and I press home button,app entered backgroud.Now I kill app and when i reopen app,i found that data wasn't saved.I saw this https://realm.io/docs/java/latest/#controlling-the-lifecycle-of-realm-instances  and i realized that realm maybe not closed safely.But how?What can I do when user kill app or app closed abnormal.Thanks.

**Comment by Zhuinden** [comment]
Data won't be saved if the transaction is not commited.

**Comment by kneth** [comment]
Realm is ACID: https://realm.io/docs/java/latest/#writes

**Comment by xturbofan** [comment]
@kneth  Thanks,realm is  perfect.It's all my fault ,I delete realm in application.
