### ISSUE TITLE
existData

### ISSUE THREAD

**Issue by seransaca** [realm/realm-java#3873]
For a week I've seen that the "queue" that I have implemented does not work properly, and sooner.
When I take an item and treat it, then I delete it. When there is only one element, I treat that element and eliminate it. Well there are times that after removing the last element, and I check whether there are elements or not, to know how to treat the new element to insert, it tells me that it has an element, when it really is not true that there are elements and not To that it can be due, since in the code I have verified that the queue has 0 elements, but when trying to treat the new element it tells me that if there are elements and it does not let me try the new or none, since it looks for the first one ( Id = 1) when it does not really exist.
Ids are tightly controlled.

I have created 2 realm instances, in two different activities (I do not know if that can be the problem)

#### Version of Realm and tooling
Realm version(s): 1.1.0

Realm sync feature enabled: no

Android Studio version: 2.2.2

Which Android version and device: 6.0

**Comment by Zhuinden** [comment]
Without the code that doesn't work as expected, we cannot identify the problem.

**Comment by seransaca** [comment]
This is my function to check if there are data:
`public static boolean exitsData(Realm realm){
        RealmResults<Data_DB> push = realm.where(Data_DB.class).findAll();
        Log.e("existsData","en cola-->"+String.valueOf(push.size()));
        if(push.size()==0){
            return false;
        }else{
            return true;
        }
    }`
This is my function to delete last element of the queue:
`public static void deleteData(Realm realm){
        realm.executeTransaction(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {
                if(exitsData(realm)) {
                    realm.where(Data_DB.class).findAllSorted("id").deleteFirstFromRealm();
                }
            }
        });

    }`

**Comment by Zhuinden** [comment]
Code reformatted to readable form:

``` java
        public static boolean exitsData (Realm realm){
            RealmResults<Data_DB> push = realm.where(Data_DB.class).findAll();
            Log.e("existsData", "en cola-->" + String.valueOf(push.size()));
            if(push.size() == 0) {
                return false;
            } else {
                return true;
            }
        }
```

and

``` java
        public static void deleteData (Realm realm){
            realm.executeTransaction(new Realm.Transaction() {
                @Override
                public void execute(Realm realm) {
                    if(exitsData(realm)) {
                        realm.where(Data_DB.class).findAllSorted("id").deleteFirstFromRealm();
                    }
                }
            });
        }
```

**Comment by kneth** [comment]
Does `deleteFirstFromRealm()` return `true` or `false`?

**Comment by seransaca** [comment]
Sorry but I don't know if this function retunr anything

**Comment by Zhuinden** [comment]
Well, you need to check if it returns true or false

**Comment by seransaca** [comment]
Ok, but I check with "chrome://inspect" and there aren't any element of this class

**Comment by Zhuinden** [comment]
Have you tried using a debugger on your application?

**Comment by seransaca** [comment]
Yes and I also use Log to view all the activity in my aplication, but the Log is not equal than chrome://inspect

**Comment by zaki50** [comment]
I guess the Realm instance is not closed properly on the non-looper thread.
