### ISSUE TITLE
Each element of 'value' must be a valid managed object.

### ISSUE THREAD

**Issue by xX7** [realm/realm-java#3876]
#### Goal

> Persist the Product Class in Realm and link the Recipients in Realm to copied ones.

#### Expected Results

> Works

#### Actual Results

> Each element of 'value' must be a valid managed object.

#### Code Sample

Needed code from the "Product Class":

```
 public void setRecipients(RealmList<RecipientData> mRecipientDatas) {
        this.mRecipients = mRecipientDatas;
    }

    public void addRecipient(RecipientData recipientData){
        if(mRecipients != null){
            mRecipients.add(recipientData);
        }
    }

    public void clearRecipients(){
        mRecipients = new RealmList<>();
    }

```

What works:

```
Realm.getDefaultInstance().beginTransaction();

RealmProductModel copy = Realm.getDefaultInstance().copyToRealm(productModel);
	         copy.clearRecipients();

		List<RecipientData> recipientDatas = Realm.getDefaultInstance().copyFromRealm(productModel.getRecipients());
		for(RecipientData d : recipientDatas){
			d.setFloatingRecipient(true);
			d.setID(PrimaryKeyFactory.getInstance().nextKey(RecipientData.class));
			copy.addRecipient(d);
			}
```

What is not working:

```
Realm.getDefaultInstance().beginTransaction();

RealmProductModel copy = Realm.getDefaultInstance().copyToRealm(productModel);

List<RecipientData> recipientDatas = Realm.getDefaultInstance().copyFromRealm(productModel.getRecipients());
		for(RecipientData d : recipientDatas){
			d.setFloatingRecipient(true);
			d.setID(PrimaryKeyFactory.getInstance().nextKey(RecipientData.class));
			}
			RealmList<RecipientData> r = new RealmList<>();
			r.addAll(recipientDatas);
			copy.setRecipients(r);
```

			

#### Version of Realm and tooling
Realm version(s): 2.2.0

Realm sync feature enabled: no

Android Studio version: 2.2.2

Which Android version and device: OnePlus 3

**Comment by Zhuinden** [comment]
1.) you're calling `Realm.getDefaultInstance()` multiple times which is reference counted ( https://realm.io/docs/java/latest/#closing-realm-instances ), so your Realm instance will never be closed again ( as per `Realm.getDefaultInstance().beginTransaction();`, and other similar `Realm.getDefaultInstance().[...]`).

2.) you shouldn't need to call `copyFromRealm()` in this case **at all, not even once**.

-------

But otherwise unfortunately I'm not sure what object relations you're trying to set up here between what models, so I can't tell you how to do it properly.

**Comment by xX7** [comment]
1.) I am closing the realm instances, this is just a snipped to show, that im in a transaction.

2.) I need to call copyFromRealm because at this time the "productModel.getRecipients()" returns a managed list of Recipients and I want to copy them for that particular persisted model

**Comment by Zhuinden** [comment]
1.) It is irrelevant that you call `close()` once, because that decrements the reference counter only once.

`getDefaultInstance()` and `close()` calls are paired. If you call `getDefaultInstance()` 6 times, then you receive 6 variables that you should call `close()` on.

2.) in that case your question is unclear, and you should specify your Realm models, and what you intend to actually do.

**Comment by xX7** [comment]
I know thank you. Like I said, its just a coed piece.

Actually you can see what I want to archive? Persist the product class in Realm, do a copy of the managed Recipients, change their id and a boolean and copy them as reference to the persisted product class. I want to archive that, because I dont want to have a reference to the "original" Recipient in realm.

**Comment by xX7** [comment]
The Problem is, that these code snippets are indentically, but one crashes where the other one doenst

**Comment by kneth** [comment]
@xX7 What do you mean by "crashes"?

**Comment by Zhuinden** [comment]
Please include a Stack Trace for the crash.

**Comment by xX7** [comment]
I mean it throws an exception in the realm proxy class class :

Each element of 'value' must be a valid managed object.

But it shouldn't, because both of the snippets are identical in its behavior

**Comment by Zhuinden** [comment]
``` java
public class Product extends RealmObject {
     private RealmList<RecipientData> mRecipients;

     public void setRecipients(RealmList<RecipientData> mRecipientDatas) {
        this.mRecipients = mRecipientDatas;
     }

    public void addRecipient(RecipientData recipientData){
        if(mRecipients != null){
            mRecipients.add(recipientData);
        }
    }

    public void clearRecipients() {
        mRecipients = new RealmList<>();
    }
}
```

and what is said to **work**:

``` java
        try(Realm realm = Realm.getDefaultInstance()) {
            realm.executeTransaction(new Realm.Transaction() {
                @Override
                public void execute(Realm realm) {
                    RealmProductModel managedProductModel = realm.copyToRealm(originalProductModel);
                    managedProductModel.clearRecipients(); // calls mRecipients = new RealmList<>();

                    List<RecipientData> unmanagedRecipientDatas = realm.copyFromRealm(originalProductModel.getRecipients());
                    for(RecipientData recipientData : unmanagedRecipientDatas) {
                        recipientData.setFloatingRecipient(true);
                        recipientData.setId(getNewKey(RecipientData.class));
                        managedProductModel.addRecipient(recipientData);
                    }
                }
            });
        }
```

What is said to **fail**:

``` java
        try(Realm realm = Realm.getDefaultInstance()) {
            realm.executeTransaction(new Realm.Transaction() {
                @Override
                public void execute(Realm realm) {
                    RealmProductModel managedProductModel = realm.copyToRealm(productModel);
                    // managedProductModel.clearRecipients(); // calls mRecipients = new RealmList<>();

                    List<RecipientData> unmanagedRecipientDatas = realm.copyFromRealm(productModel.getRecipients());
                    for(RecipientData recipientData : unmanagedRecipientDatas) {
                        recipientData.setFloatingRecipient(true);
                        recipientData.setId(getNextKey(RecipientData.class));
                    }
                    RealmList<RecipientData> newRealmList = new RealmList<>();
                    newRealmList.addAll(unmanagedRecipientDatas);
                    managedProductModel.setRecipients(newRealmList);
                }
            });
        }
```

Maybe this *should* be investigated although I think there's probably some hidden detail missing from the example code.

**Comment by xX7** [comment]
thanks, no there are not hidden details missing. As Soon as I change the exacte same code the Problem occurs. The code I copied above is an exact copy from the original source code

**Comment by beeender** [comment]
@xX7 I think it is not allowed to call setter on a list with any unmanaged object inside. See the test case https://github.com/realm/realm-java/blob/3cbc084b3c888e9555629638e31adebbfd369c8f/realm/realm-library/src/androidTest/java/io/realm/RealmObjectTests.java#L765

Your working code example is OK
Or you could do something like below if you really want to add them to a list first:

```java
Realm realm = Realm.getDefaultInstance();
realm.beginTransaction();

RealmProductModel copy = realm.copyToRealm(productModel);

List<RecipientData> recipientDatas = Realm.getDefaultInstance().copyFromRealm(productModel.getRecipients());
RealmList<RecipientData> r = new RealmList<>();
for(RecipientData d : recipientDatas){
    d.setFloatingRecipient(true);
    d.setID(PrimaryKeyFactory.getInstance().nextKey(RecipientData.class));
    r.add(realm.copyToRealm(t));
}
copy.setRecipients(r);
realm.commitTransaction();
realm.close();
```

**Comment by Zhuinden** [comment]
@beeender but if he shouldn't be able to set an unmanaged list on a managed object, then how come `clearRecipient` is able to set an unmanaged list?

Or if he can set an empty unmanaged list, then add unmanaged objects to it, shouldn't he be able to do that later on? 

I think the problem here is that he seems to get past a check with his empty unmanaged list set to a managed object.

**Comment by xX7** [comment]
@Zhuinden This is exactly what I was trying to tell. Thanks for clearing that out :)

**Comment by beeender** [comment]
Anyway, it seems the original issue is solved. I am closing it now. Feel free to reopen it if needed. :)

**Comment by Zhuinden** [comment]
@beeender technically I hope I won't forget about this one because it seems that he can get past an error check for whatever reason
