### ISSUE TITLE
Doc: Fragment lifecycle creation should be `onCreateView()`/`onDestroyView()`

### ISSUE THREAD

**Issue by Zhuinden** [realm/realm-java#3881]
Docs say
https://realm.io/docs/java/latest/#controlling-the-lifecycle-of-realm-instances

``` java
// Use onStart()/onStop() for Fragments as onDestroy() might not be called.
public class MyFragment extends Fragment {
    private Realm realm;

    @Override
    public void onStart() {
        super.onStart();
        realm = Realm.getDefaultInstance();
    }

    @Override
    public void onStop() {
        super.onStop();
        realm.close();
    }
}
```

but it should be

``` java
// Use onCreateView()/onDestroyView() for Fragments as onDestroy() might not be called.
public class MyFragment extends Fragment {
    private Realm realm;

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup parent, Bundle savedInstanceState) {
        realm = Realm.getDefaultInstance();
        ... 
        return view;
    }

    @Override
    public void onDestroyView() {
        realm.close();
        super.onDestroyView();
    }
}
```

**Comment by kneth** [comment]
@Zhuinden Thanks

**Comment by Zhuinden** [comment]
...... This is still not added. 

This makes it hard to point people towards best practices.

**Comment by bmeike** [comment]
Zhuinden, can you comment on why you prefer create/destroy to start/stop for managing the Realm instance?

**Comment by Zhuinden** [comment]
@bmeike because `onCreateView()` creates the view, and `onDestroy()` creates the view, which means that typically you call `updateData(realm.where(Blah.class).findAllAsync());` on your `RealmRecyclerViewAdapter` when you set the data, which happens in `onCreateView()` - so unless you want to re-initialize your adapter content in `onStart()` and set your data to `null` in `onStop()`, which is rather uncommon, you should open/close the Realm instance in `onCreateView()` / `onDestroyView()` respectively.

**Comment by bmeike** [comment]
Yep.  I'll buy that.  Thanks.

**Comment by diegomontoya** [comment]
@Zhuinden  @bmeike opening realm in onCreateView() is not optimized for UI "speed" perception. If you put any code in onCreateView() and it is slow, the android app fragment will not render on the screen until onStart(). Async queries are non-blocking but getting a realm is heavy duty stuff depending on size of current db. The end result is the app fragment displaying a white screen while your realm is being opened. Putting it in onStart() will still block the UI but at least the fragment is rendered so there is visible cues. perceived UI progression for the user to see while he waits. The perception of app speed is very important. If using sync realm queries, than onCreateView() is even more of a drag.

**Comment by bmeike** [comment]
Yep, exactly.  I was concerned that closing the db in `onDestroyView` would hold resources for too long, especially in the case in which it isn't called at all.  The consensus is that it is all good.

**Comment by bmeike** [comment]
I propose the following:

`// Setup Realm in your Application
public class MyApplication extends Application {
    @Override
    public void onCreate() {
        super.onCreate();
        Realm.init(this);
        RealmConfiguration realmConfiguration = new RealmConfiguration.Builder().build();
        Realm.setDefaultConfiguration(realmConfiguration);
    }
}

// onCreate()/onDestroy() overlap when switching between activities.
// Activity2.onCreate() will be called before Activity1.onDestroy().
public class MyActivity extends Activity {
    private Realm realm;
    private RecyclerView recyclerView;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        setContentView(R.layout.activity_main);

        realm = Realm.getDefaultInstance();

        recyclerView = (RecyclerView) findViewById(R.id.recycler_view);
        recyclerView.setAdapter(new MyRecyclerViewAdapter(this, realm.where(MyModel.class).findAllAsync()));

        // ...
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        realm.close();
    }
}

// Use onCreateView()/onDestroyView() for Fragments.
// Note that if the db is very large, getting the realm may block rendering.
// In that case, it may be preferable to use onStart/onStop so that at least
// the fragment frame is rendered, while the db is opening.
public class MyFragment extends Fragment {
    private Realm realm;
    private RecyclerView recyclerView;

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        realm = Realm.getDefaultInstance();

        View root = inflater.inflate(R.layout.fragment_view, container, false);

        recyclerView = (RecyclerView) root.findViewById(R.id.recycler_view);
        recyclerView.setAdapter(new MyRecyclerViewAdapter(getActivity(), realm.where(MyModel.class).findAllAsync()));

        // ...

        return root;
    }

    @Override
    public void onDestroyView() {
        super.onDestroyView();
        realm.close();
    }
}
`

**Comment by bmeike** [comment]
I propose the following:

```
// Setup Realm in your Application
public class MyApplication extends Application {
    @Override
    public void onCreate() {
        super.onCreate();
        Realm.init(this);
        RealmConfiguration realmConfiguration = new RealmConfiguration.Builder().build();
        Realm.setDefaultConfiguration(realmConfiguration);
    }
}

// onCreate()/onDestroy() overlap when switching between activities.
// Activity2.onCreate() will be called before Activity1.onDestroy().
public class MyActivity extends Activity {
    private Realm realm;
    private RecyclerView recyclerView;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        setContentView(R.layout.activity_main);

        realm = Realm.getDefaultInstance();

        recyclerView = (RecyclerView) findViewById(R.id.recycler_view);
        recyclerView.setAdapter(new MyRecyclerViewAdapter(this, realm.where(MyModel.class).findAllAsync()));

        // ...
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        realm.close();
    }
}

// Use onCreateView()/onDestroyView() for Fragments.
// Note that if the db is very large, getting the realm may block rendering.
// In that case, it may be preferable to use onStart/onStop so that at least
// the fragment frame is rendered, while the db is opening.
public class MyFragment extends Fragment {
    private Realm realm;
    private RecyclerView recyclerView;

    @Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        realm = Realm.getDefaultInstance();

        View root = inflater.inflate(R.layout.fragment_view, container, false);

        recyclerView = (RecyclerView) root.findViewById(R.id.recycler_view);
        recyclerView.setAdapter(new MyRecyclerViewAdapter(getActivity(), realm.where(MyModel.class).findAllAsync()));

        // ...

        return root;
    }

    @Override
    public void onDestroyView() {
        super.onDestroyView();
        realm.close();
    }
}
```

**Comment by bmeike** [comment]
Fixed in https://github.com/realm/realm.io/pull/2712

**Comment by bmeike** [comment]
realm/realm.io#2712 merged
