### ISSUE TITLE
Stable iterators for RealmCollection

### ISSUE THREAD

**Issue by beeender** [realm/realm-java#3883]
### Problem

This has been discussed before
https://github.com/realm/realm-java/issues/640
https://github.com/realm/realm-java/issues/602

https://github.com/realm/realm-wiki/wiki/Java-Iterators (Internal wiki page)

So #2124 was introduced to solve below problem:

```java
RealmResults<Person> persons = realm.allObjects(Person.class);
realm.beginTransaction();
for (int i = 0; persons.size(); i++) {
	// Will only delete half the elements due to size() calling
	// sync_if_needed.
	persons.get(i).removeFromRealm(); 
 }
realm.commitTransaction();
```

Then we added #2990 to make sure the `RealmResults` gets updated in very next event loop by calling `handler.postAtFrontOfQueue()`. 

Usually above works fine, this becomes a topic again for below reasons:

#### 1. However there are still corner cases which could trigger an exception:

> java.lang.IllegalStateException: Object is no longer managed by Realm. Has it been deleted?

eg.: Delete an element in `RealmResults` then calling the corresponding `ListView.measure()` method. `measure()` will try to get views by calling adapter's `getView()` to measure, but at this time, since it is still in the same event loop the elements get deleted, the `RealmResults` has not been updated yet.

#### 2. PR #3834 met some difficulties to support the exact same behavior with OS `Results`.

`Results` will sync the `TableView` when ever any accessor called unless it is an snapshot.

### `Results::snapshot()`

This call returns a special `Results` object that never updates to reflect changes in the underlying data.

Since `Results` can be created on `Query`/`LinkView`/`TableView`, so a snapshot can be created from those as well.

#### 1. Change all `RealmResults`'s  backend to a snapshot when `beginTransaction()` called. 
And change them back in the very next event loop. This could allow us to make #3834 and stay with current `RealmResults`'s behaviors.
But this won't solve the problem 2 and 3.

#### 2. Introduce a new `RealmCollection` type `RealmSnapshotCollection`. 

`RealmSnapshotCollection` is backed by a snapshot of OS `Results`. So the collection itself won't be updated, size and order stay the same forever (elements inside are still live objects.).
It could be created by `RealmResults.snapshot()` or `RealmList.snapshot()`.
Since it won't be auto-updated, so there is no point to allow listener related APIs on it. Calling `addChangeListener` will just throw.
The iteration (both simple loop and foreach loop) will be always stable.
It is supposed to be used when the `RealmCollection`'s size and order will be changed. Take the top example again, with `RealmSnapshotCollection`, it will be implemented as:

```java
RealmResults<Person> persons = realm.allObjects(Person.class);
RealmSnapshotCollection<Person> snapshot = persons.snapshot();
realm.beginTransaction();
for (int i = 0; snapshot.size(); i++) {
       // Will reach all the element in the query results since snapshot is stable.
	snapshot.get(i).removeFromRealm(); 
 }
realm.commitTransaction();

log(persons.size()) // = 0, The RealmResults is always alive
log(snapshot.size()) // = original size.
```

* **+** Solves problem 1, 2, 3
* **+** Overhead is very small for `RealmResults` since the `Results::snapshot` is using move constructor to build the `TableView`.
* **+** We could have the same behavior for `RealmResults` and `RealmList`, and they are live always.
* **+** It is still possible to make `RealmResults`/`RealmList`'s `foreach` iterator stable. But the simple loop won't be stable anymore.
* **-** break API change.
* **-** Will it be difficult to understand by users?

**Comment by Zhuinden** [comment]
Well, the breaking change since 0.89.0 already creates a RealmResults that is essentially a "snapshot", mostly because it doesn't auto-update anymore due to not calling `syncIfNeeded()` (although if I recall right, the elements inside it still get invalidated).

I would assume that the behavior provided by receiving a `RealmResults` that is a snapshot if the Realm is in a transaction would provide the same behavior, no?

**Comment by beeender** [comment]
@Zhuinden yes, the snapshot will work like the current `RealmResults`. I am thinking to make the `RealmResults` live all the time again and use the new shapshot to achieve the stable iterator.

I feel I will meet trouble when deal with fined grained notifications which is triggered by the local transaction commit. Let's see, i will update more details here.

**Comment by Zhuinden** [comment]
I feel that this is eerily relevant in realm-cocoa: https://github.com/realm/realm-cocoa/blob/master/CHANGELOG.md#210-release-notes-2016-11-18

**Comment by beeender** [comment]
### Corner cases with `Handler.postAtFrontOfQueue()`

1. Methods like `View.measure()` will call into adapters immediately which gives us no chance to refresh the `RealmResults`
2. `Handler.postAtFrontOfQueue` is not guaranteed to be always at the first of queue in the Android Java world. e.g: Any other library or user's code could call the `postAtFrontOfQueue()` again which makes our results refresh event go to the 2nd position of the queue.
3. In native code, Alooper could be called to deliver messages. The whole Android looper is based on the `epoll`. The Android java will create a epoll fd and listen to it, all the java message queue relies on this epoll fd. But if native code create a new Alooper and listen to that new epoll fd, there is no guarantee at all `postAtFrontOfQueue` which is monitored by the java epoll fd will be triggered first. In OS, we are using Alooper for deliver notifications in native code, it would be possible to hack our own implementation. But if any other 3rd party lib using the Alooper in the native code, we have no way to workaround.

**Comment by beeender** [comment]
Also, what is the expected results for current implementation:

```java
int size = dogs.size(); // size = 3
dogs.get(0).deleteFromRealm();
size = dogs.size(); // size = 3, dogs.get(0) becomes invalid
dogs.deleteLast();
size = dogs.size(); // size = 1, but actually it feels it should be 2!
```

**Comment by beeender** [comment]
Unfortunately current `RealmResults` doesn't play well with Object Store collection fine grained notification.

The collection notification will be delivered immediately when advance read (eg.: calling `beginTransaction()`). See case like below:

```java
RealmResults results = realm.where(Dog.class).findAll();
results.addChangeListener(new RealmChangeLitener() {
    public void onChange(RealmResults results, ChangeSet changeSet) {
    }
})

realm.beginTransaction();
realm.createObject(Dog.class);
realm.commitTransaction();

realm.beginTransaction(); // Object Store will deliver collection notification here
realm.commitTransaction();
```

When the 2nd `beginTransaction()` called, the Object Store will deliver the notification with 1 insertion in the change set. But at this point, the `results` is in snapshot state, the notification will just be dropped.

**Comment by beeender** [comment]
#3834 Fixed this.

**Comment by Zhuinden** [comment]
If anyone asks, the solution for the example presented above uses `snapshot` solution, instead of the "swapping out" solution

------

``` java
realm.beginTransaction();
RealmResults<Person> persons = realm.where(Person.class).findAll();
for (int i = 0, OrderedRealmCollection<Person> snapshot = persons.snapshot(); i < snapshot.size(); i++) {
	snapshot.get(i).removeFromRealm(); 
 }
realm.commitTransaction();
```
