### ISSUE TITLE
Sort by locale (ą, ę, ł, ó etc.)

### ISSUE THREAD

**Issue by janswist** [realm/realm-java#3884]
Guys, I think sorting by locale in Java should already be here. Is there any workaround for that? It's really frustrating, because I have whole app based on Realm and now I can't properly sort it. Now it's ("a", "b", "c","d", "ą", "ć") when it should be ("a","ą","b","c","ć","d").

**Comment by Zhuinden** [comment]
I tend to create a second field where every accent is removed, primarily because case_insensitive sorting/querying doesn't work due to some sort of native limitation that also binds SQLite.

**Comment by janswist** [comment]
@Zhuinden Seems reasonable, but think about this - You have contacts like this:
Ląpa
Łanik

After normalization it will be in this order:
Łanik
Ląpa

so this would mess everything. I tried Collections.sort() but yielded `java.lang.RuntimeException: Unable to start activity ComponentInfo{pl.aype.cbm/pl.aype.cbm.BaseActivity}: java.lang.UnsupportedOperationException: Replacing and element is not supported` which is not good.

**Comment by kneth** [comment]
@janswist Realm has limited support for locale aware sorting: https://realm.io/docs/java/latest/#sorting-and-querying-on-string

Related to #1031 and #2313

Android doesn't currently support locales on NDK level which makes it difficult for database vendors to provide proper sorting (see also https://android-review.googlesource.com/#/c/121180/).
