### ISSUE TITLE
Can‘t use List<String> replace RealmString ？

### ISSUE THREAD

**Issue by baoyachi** [realm/realm-java#3886]
It's look like so ugly in code ！ Must be like this？

**Comment by Zhuinden** [comment]
Personally I've realized that creating a `RealmObject` for it is a massive overhead.

So I personally put them in one string field, separated.

For example, you can store it as a JSON string list, or CSV.

    ["hello", "world"]

But you can also use other separator characters in order to ensure queryability.

**Comment by cmelchior** [comment]
Hi @baoyachi 
For now, unfortunately yes. We have a issue tracking it here #575.

**Comment by baoyachi** [comment]
add this [https://gist.github.com/baoyachi/f227100e24d182452975bf4ab4c6b278](https://gist.github.com/baoyachi/f227100e24d182452975bf4ab4c6b278)
