### ISSUE TITLE
insert does not insert all the data, but insertOrUpdate does

### ISSUE THREAD

**Issue by chrisolsen** [realm/realm-java#3887]
#### Goal

When an API search is performed only a small portion of the data is returned per model. This data is inserted into a *programs* table via the `.insert()` method to prevent overwriting an existing complete models.

The program model contains simple string/int properties as well as an array of `tags` of a `StringValue` type (the hack to store an array of strings). The `tags` are inserted correctly when using the `.insertOrUpdate` method, but are *not* inserted when using the `.insert()` method.

#### Expected Results

StringValue array should be inserted into the db when calling the realm `.insert()` method.

#### Actual Results

`.insertOrUpdate()` inserts the array of StringValues, but `.insert()` does not

#### Code Sample

```java
Response<List<Program>> resp = Endpoints.getApi(this).searchPrograms(filter).execute();
final List<Program> programs = resp.body();
if (resp.isSuccessful()) {
    realm.executeTransaction(new Realm.Transaction() {
        @Override
        public void execute(Realm realm) {
            for (Program p : programs) {
                try {
                    realm.insert(p);   <==== fails, but insertOrUpdate(p) works 
                } catch (RealmPrimaryKeyConstraintException e) {
                    // just means the object is already in the database
                }
            }
        }
    });
}
```

#### Version of Realm and tooling
Realm version(s): 2.2.1

Realm sync feature enabled: not sure
Android Studio version: 2.2.3

Which Android version and device: 4.2.1, nexus 4

**Comment by kneth** [comment]
@chrisolsen I believe that `insert()` should create the `StringValue` objects too. We have a test similar to want you describe: https://github.com/realm/realm-java/blob/master/realm/realm-library/src/androidTest/java/io/realm/BulkInsertTests.java#L88

Can you see if you are doing it differently? If so, that might help us write another test to find which use cases we haven't covered.

**Comment by beeender** [comment]
close due to no response. @chrisolsen If you can reproduce it, feel free to reopen this issue.
