### ISSUE TITLE
io.realm.exceptions.RealmError: Unrecoverable error. mmap() failed: Out of memory

### ISSUE THREAD

**Issue by anonymoused** [realm/realm-java#3888]
#### Goal

> I am using realm in an app I am developing.  While using the application, after general usage for 30-40 minutes it crashes and throws an io.realm.exceptions.RealmError.

#### Expected Results

> I expect the application to continue to function.

#### Actual Results

I have seen it crash in an IntentService:

>  FATAL EXCEPTION: IntentService[UpdateTestsService]
Process: com.company.project, PID: 18026
io.realm.exceptions.RealmError: Unrecoverable error. mmap() failed: Out of memory in io_realm_internal_SharedGroup.cpp line 113
   at io.realm.internal.SharedGroup.createNativeWithImplicitTransactions(Native Method)
   at io.realm.internal.SharedGroup.<init>(SharedGroup.java:67)
   at io.realm.internal.SharedGroupManager.<init>(SharedGroupManager.java:47)
   at io.realm.BaseRealm.<init>(BaseRealm.java:76)
   at io.realm.Realm.<init>(Realm.java:126)
   at io.realm.Realm.createAndValidate(Realm.java:246)
   at io.realm.Realm.createInstance(Realm.java:231)
   at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:114)
   at io.realm.Realm.getDefaultInstance(Realm.java:181)
   at com.company.project.services.background.AbstractIntentService.beforeHandleIntent(AbstractIntentService.java:34)
   at com.company.project.services.background.AbstractIntentService.onHandleIntent(AbstractIntentService.java:28)
   at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:66)
   at android.os.Handler.dispatchMessage(Handler.java:102)
   at android.os.Looper.loop(Looper.java:148)
   at android.os.HandlerThread.run(HandlerThread.java:61)

I have also seen it crash in the main thread.  This stacktrace happened after I relaunched the app after a crash:
> E/AndroidRuntime: FATAL EXCEPTION: main
Process: com.company.project, PID: 19226
io.realm.exceptions.RealmError: Unrecoverable error. mmap() failed: Out of memory size: 1006632960 offset: 0 in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 92
  at io.realm.internal.SharedRealm.nativeGetSharedRealm(Native Method)
  at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:205)
  at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:182)
  at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:124)
  at io.realm.Realm.getDefaultInstance(Realm.java:209)
  at com.company.project.App.onCreate(App.java:64)
  at com.android.tools.fd.runtime.BootstrapApplication.onCreate(BootstrapApplication.java:370)
  at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1024)
  at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5361)
  at android.app.ActivityThread.-wrap2(ActivityThread.java)
  at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1528)
  at android.os.Handler.dispatchMessage(Handler.java:102)
  at android.os.Looper.loop(Looper.java:154)
  at android.app.ActivityThread.main(ActivityThread.java:6077)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:865)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:755)

#### Steps & Code to Reproduce

> I have read the following tickets and SO questions:
1) Memory Leak with long lived Realm Objects: https://github.com/realm/realm-java/issues/3583
2) Out of memory , sharedgroup error or Unrecoverable error: https://github.com/realm/realm-java/issues/1639
3) Out of memory in io_realm_internal_SharedGroup.cpp: https://github.com/realm/realm-java/issues/794
4) Out of memory in io_realm_internal_SharedGroup.cpp: https://github.com/realm/realm-java/issues/2209
5) Proper Realm usage patterns/best practices?: http://stackoverflow.com/questions/31590717/proper-realm-usage-patterns-best-practices/31594548#31594548
6) Unrecoverable error. mremap(): failed: Out of memory in io_realm_internal_SharedGroup.cpp line 188: http://stackoverflow.com/questions/33384913/unrecoverable-error-mremap-failed-out-of-memory-in-io-realm-internal-shared
7) io.realm.exceptions.RealmError: Unrecoverable error. mmap() failed: Out of memory in io_realm_internal_SharedGroup.cpp line 115: http://stackoverflow.com/questions/31510545/io-realm-exceptions-realmerror-unrecoverable-error-mmap-failed-out-of-memor
8) Realm android application crash: io.realm.exceptions.RealmError: Unrecoverable error. mmap() failed: Out of memory size: http://stackoverflow.com/questions/38051678/realm-android-application-crash-io-realm-exceptions-realmerror-unrecoverable-e
9) Out of memory in io_realm_internal_: http://stackoverflow.com/questions/33567151/out-of-memory-in-io-realm-internal
10) Android Realm: Out of memory: http://stackoverflow.com/questions/29641874/android-realm-out-of-memory

>I feel as though I am properly opening and closing all realm connections, but I am still reaching this error.  The device I am testing on has over 2gb of free space still available after the exception is thrown.

#### Code Sample

>All activities open and close realm in onCreate/onDestroy.

```java
    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        this.realm = Realm.getDefaultInstance();
        this.languageService = new LanguageService(this, realm);
        this.securityService = new SecurityService(this, realm);
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();

        this.languageService = null;
        this.securityService = null;
        this.realm.close();
    }
```
	
All fragments open and close realm in onStart/onStop.

```java
	@Override
    public void onStart() {
        super.onStart();

        this.realm = Realm.getDefaultInstance();
        this.languageService = new LanguageService(getActivity(), realm);
        this.securityService = new SecurityService(getActivity(), realm);
        this.assetService = new AssetService(getActivity(), realm);
    }

    @Override
    public void onStop() {
        super.onStop();

        this.languageService = null;
        this.securityService = null;
        this.assetService = null;
        this.realm.close();
    }
```

All IntentService open and close realm in a try/finally in onHandleIntent.

```java
    @Override
    protected void onHandleIntent(Intent intent) {
        this.realm = Realm.getDefaultInstance();
        try {
            beforeHandleIntent(intent);
            handleIntent(intent);
            afterHandleIntent(intent);
        } finally {
            this.realm.close();
        }
    }
```

There are a few Async tasks that manage their own realm as well, they all follow this format:

```java
	Realm realm = Realm.getDefaultInstance();

	try {
		//use realm here
	} catch (Exception ex) {
		ex.printStackTrace();
	} finally {
		realm.close();
	}

```

#### Version of Realm and tooling
Realm version(s): 2.2.1

Realm sync feature enabled: yes/no - unsure what this means

Android Studio version: 2.2.2

Which Android version and device: Nexus 9 running Android 7.0 (SDK 24).

**Comment by Zhuinden** [comment]
Why is Realm.getDefaultInstance outside of the try? 

Anyways, if all realm instances are closed on all background threads properly, then you probably execute too many transactions at once (for example begin and commit transaction in a loop).

**Comment by anonymoused** [comment]
I have put Realm.getDefaultInstance outside of the try because of the examples in the Realm documentation.

https://realm.io/docs/java/latest/#closing-realm-instances

Every example in that section shows the getDefaultInstance outside the try.

I will look into the issue of executing too many transactions at a time.  What is the correct way to save many results at once?

**Comment by Zhuinden** [comment]
Try to keep transaction count per thread to 1. 

But technically you just shouldn't do 

    for(...)
        realm.executeTransaction 

Instead 

    realm.executeTransaction 
        for

**Comment by anonymoused** [comment]
We were executing too many transactions at a time.  Moving transactions out of loops helped tremendously.  Thanks for the excellent support.

**Comment by trr-amsiq** [comment]
@Zhuinden does the loop rule apply to the insertOrUpdateMethod?

**Comment by Zhuinden** [comment]
@trr-amsiq yes

**Comment by Kharlos** [comment]
> @trr-amsiq yes

Question, what is better instance of realm in each activity that i use OR create one instance in my application class and use it in all app? something like this

`public class App extends Application {

    private static App instance;
    private static Realm realm;

    @Override
    public void onCreate() {
        super.onCreate();
        instance = this;
        Realm.init(instance);
        RealmConfiguration realmConfig = new RealmConfiguration.Builder()
                .deleteRealmIfMigrationNeeded()
                .build();
        Realm.setDefaultConfiguration(realmConfig);
        realm = Realm.getInstance(realmConfig);//Realm.getDefaultInstance();

    }

    @Override
    public void onTerminate() {
        realm.close();
        super.onTerminate();
    }`

**Comment by ankursharma234** [comment]
@Zhuinden need to know a case. I got the same error. I am updating a realm list which is in a loop ofcourse and that happens inside executeTransaction. For example : 

final Realm realm = RealmUtils.getRealm(companyId);
        try {
            realm.executeTransaction(new Realm.Transaction() {
                @Override
                public void execute(Realm realm) {
                    calculateLastSaleDate(realm);
                }
            });
        } finally {
            RealmUtils.close(realm, false);
        }

Can this be a reason for out of memory ?

**Comment by viniciusgati** [comment]
> @Zhuinden need to know a case. I got the same error but its random for some users (not all suffer from this issue but some). I am updating a realm list which is in a loop ofcourse and that happens inside executeTransaction. For example :
> 
> ```
> final Realm realm = RealmUtils.getRealm(companyId);
>         try {
>             realm.executeTransaction(new Realm.Transaction() {
>                 @Override
>                 public void execute(Realm realm) {
>                     calculateLastSaleDate(realm);
>                 }
>             });
>         } finally {
>             RealmUtils.close(realm, false);
>         }
> ```
> 
> Can this be a reason for out of memory ?

same here, only some devices.
