### ISSUE TITLE
sir,when support Rxjava2.0

### ISSUE THREAD

**Issue by bilaizi** [realm/realm-java#3889]
> We LOVE to help with any issues or bug you have!

> **Questions**: If you have questions about how to use Realm, please ask on [SO](http://stackoverflow.com/questions/ask?tags=realm) - we monitor the Realm tag.

> **Feature Request**: Just fill in the first two sections below.

> **Bugs**: To help you as fast as possible with an issue or bug please describe your issue and the steps you have taken to reproduce it in as many details as possible.
>
> Thanks for helping us help you :-)
>
> Remove this and above before submitting.

#### Goal

> What do you want to achieve?

#### Expected Results

> ?

#### Actual Results

>  E.g. full stack trace with exception

#### Steps & Code to Reproduce

> Describe your current debugging efforts.

#### Code Sample

```java

> Your code here. Bigger samples should ideally be as separate Android Studio project, 
> in gists/repositories or privately at help@realm.io)

```

#### Version of Realm and tooling
Realm version(s): ?

Realm sync feature enabled: yes/no

Android Studio version: ?

Which Android version and device: ?

**Comment by Zhuinden** [comment]
it's worth noting that even the [RxJava1 support doesn't include much magic](https://github.com/realm/realm-java/blob/master/realm/realm-library/src/main/java/io/realm/rx/RealmObservableFactory.java), just a reference queue and the creation of Observables that have a Realm instance that exists until unsubscribed, and a RealmChangeListener that calls `onNext`

**Comment by kneth** [comment]
Already tracked by #3497

**Comment by cmelchior** [comment]
In the meantime you can use this library to convert between RxJava1 and 2: https://github.com/akarnokd/RxJava2Interop
