### ISSUE TITLE
java.lang.IllegalStateException: This Realm instance has already been closed, making it unusable.

### ISSUE THREAD

**Issue by LPFinch** [realm/realm-java#3891]
Open realm instance in activity onCreate()
Close realm instance in activity onDestroy()
Similar https://realm.io/docs/java/latest/#best-practices
I have button, when button is clicked i search in realm by name.

`RealmResults<Foo> results = realm.where(Foo.class)
                .equalTo("name", name).findAll();`
But i have exception 
`java.lang.IllegalStateException: This Realm instance has already been closed, making it unusable.`
Realm instance is closed but activity onDestroy doesn't fired, its magic! 

Realm 2.2.1
Android 5.1
Android studio 2.2.2

**Comment by LPFinch** [comment]
After some research i found interesting thing.
When i locked my phone, activity onPause is fired, onDestroy not fired. After 30 sec i unlock my phone onResume fired. I check realm instance 
`if (realm != null && !realm.isClosed()) {`
but realm is not ok =)
https://gist.github.com/zaki50/9d8f0eacf6be05a66c372c0002164e3c
RealmUtil show total: 0 instance(s).
I think is GC. I'm really sad =( 
Any solution?

**Comment by Zhuinden** [comment]
Do you store RealmResults as field variable?

**Comment by LPFinch** [comment]
Yes

**Comment by Zhuinden** [comment]
I've actually seen this before but could not reliably reproduce it nor haven't found anything specific as to why this would happen.

That's when I started using a UI-thread Realm instance that is open until all activities are closed in the app.

(I'm still not a Realm member)

**Comment by kneth** [comment]
@LPFinch Thanks for bringing it up. We definitely have to understand the life cycle better in order to give better advice in our documentation. Have you tried on different Android versions?

**Comment by cmelchior** [comment]
@LPFinch Can you post the complete code you see this for?

**Comment by siebeprojects** [comment]
Sounds like the same and I do the same It seems somehow that an invalid Realm gets recovered after Android recreates an Activity. For example when the app has been sleeping and then woken up and launches the same Activity. Somehow it then is corrupted although I do the onDestroy and also closes the Realm instance when not needed anymore.

**Comment by kneth** [comment]
@siebeprojects Interesting observations.

**Comment by cmelchior** [comment]
@siebeprojects Is it something you can reproduce as well? Would love to see some code samples in that case. Some other things that could be interesting is:

- Do you see this only on Realm Java 2.2.1 or also on previous version?
- Is it specific devices?

**Comment by kneth** [comment]
I'm closing the issue for now. @LPFinch You are welcome to post code so we can reopen the issue.
