### ISSUE TITLE
Observables on RealmObject containing a RealmList behaving unexpectedly

### ISSUE THREAD

**Issue by shaunpanjabi** [realm/realm-java#3894]
#### Goal

> RealmObjectA contains an id, value, and RealmList<RealmObjectB>. RealmObjectB contains just an id, and value.
> Observable on RealmObjectA should only call onNext for changes within RealmObjectA table.

#### Expected Results

> Observable on RealmObjectA should only call onNext for changes within RealmObjectA table.

#### Actual Results

>  A change in RealmObjectB causes RealmObjectA Observable onNext to get called.

#### Steps & Code to Reproduce

> See the code below. When committing a transaction to RealmObject2, RealmObject1 observable is called.

#### Code Sample

```java
public class RealmObject1 extends RealmObject {
    @PrimaryKey
    Integer id;
    String value;

    RealmList<RealmObject2> relatedList1;
}

public class RealmObject2 extends RealmObject {
    @PrimaryKey
    Integer id;
    String value;
}

Realm.init(getApplicationContext());
        final Realm realm = Realm.getDefaultInstance();
        RealmResults<RealmObject1> rr = realm.where(RealmObject1.class).findAll();

        rr.asObservable().subscribe(new Action1<RealmResults<RealmObject1>>() {
            @Override
            public void call(RealmResults<RealmObject1> realmObject1) {
                Log.d("MainActivity", "Observable Called");
                Log.d("MainActivity", Integer.toString(realmObject1.size()));
            }
        });

Runnable runnable = new Runnable() {
            @Override
            public void run() {
                Log.d("MainActivity", "Begin Transaction");
                realm.beginTransaction();
                RealmObject2 ro2 = new RealmObject2();
                ro2.id = 1;
                ro2.value = "some string";
                realm.copyToRealmOrUpdate(ro2);
                realm.commitTransaction();
                Log.d("MainActivity", "Commit Transaction");
            }
        };

        Handler handler = new Handler();
        handler.postDelayed(runnable, 5000);
```

#### Version of Realm and tooling
Realm version(s): 2.2.1

Realm sync feature enabled: no

Android Studio version: 2.2.3

Which Android version and device: Nexus 5x Emulator (Android 6.0)

**Comment by beeender** [comment]
#3834 should be able to fix this.

**Comment by beeender** [comment]
For making the PR smaller, `RowNotifier` has been removed from #3834 and it will still have false positive notifications on RealmObject like current implementation.

This will be fixed by integrate row notifications from object store in the following PR.

**Comment by Zhuinden** [comment]
I think Realm 3.0.0 should have changed this.

**Comment by beeender** [comment]
Fixed by #4101

**Comment by Zhuinden** [comment]
Hmm that's a bit odd though, what if I use the relation link field of the class, how would I listen to its changes?

Add a RealmChangeListener  to the RealmList?

**Comment by beeender** [comment]
@Zhuinden the listener on results will be triggered if the list field's elements get added/deleted. however, the list element's content changes won't trigger the result's listener. I think you don't have to add listener to the RealmList in this case? This original issue should be about the false positive notifications before.

**Comment by Zhuinden** [comment]
Oh I see, I misunderstood. 🌵
