### ISSUE TITLE
Realm for android data file size on API 21 is higher than Api 17

### ISSUE THREAD

**Issue by monajafi** [realm/realm-java#3903]
For the same app, realm data file size in Api 21(3.15 MB) is higher than Api 17(72KB)
Also app's first loading is slower in Api 21 compared to Api 17 .
I tried `        Realm.compactRealm(realmConfig);
` but it hadn't effect

**Comment by kneth** [comment]
@monajafi That's an interesting observation. Can you share your app with us? Or create a small sample app with reproduces it?

**Comment by monajafi** [comment]
here is the modified version of adapters sample project. which inserts objects in for loop
[RealmAdapter.zip](https://github.com/realm/realm-java/files/651313/RealmAdapter.zip)
If you run your Adapters sample project. the results are same. file size at startup in api 21 is higher 
but in api 17 after inserting 10k objects file size increase more than api 21 as following table:
Raw realm file before any insert:
api 17= 48KB  Api 21= 3.05MB
After inserting 10k Objects:
api 17= 4.56MB  Api 21= 3.68MB
there is one problem with adapters library in api 21 which leads more delay at app's first start up compared to api 17 which is not good thing.

**Comment by monajafi** [comment]
Actually this is not an issue even with 20k inserts Api 21 data size is far smaller than Api 17 
Realm is amazing and I've decided to use that in my app . Thanks for every contributor in the project

**Comment by kneth** [comment]
@monajafi Thanks for your kind words! Our efforts are fuelled by happy users :-)
