### ISSUE TITLE
Method addChangeListener in RealmObject cannot infer type on RealmChangeListener argument when using with java 8 lambdas.

### ISSUE THREAD

**Issue by IlyaGulya** [realm/realm-java#3908]
#### Goal

Use `RealmObject.addChangeListener(RealmChangeListener<E> listener)` and provide `RealmChangeListener` as lambda, not anonymous class.

#### Expected Results

Simply use lambda like this:
```java
Folder.getById(1)
      .addChangeListener(folder -> Timber.e(folder.getName()));
```

#### Actual Results

Instead, i need to cast lambda argument to specified type like this:
```java
Folder.getById(1)
      .addChangeListener(folder -> Timber.e(((Folder) folder).getName()));
```
or add type argument to method like this:
```java
Folder.getById(1)
      .<Folder>addChangeListener(folder -> Timber.e(folder.getName()));
```
or provide change listener as anonymous class like this:
```java
Folder.getById(1)
      .addChangeListener(new RealmChangeListener<Folder>() {
        @Override
        public void onChange(final Folder folder) {
          Timber.e(folder.getName())
        }
      });
```
Both variants looks very dirty for me.

#### Version of Realm and tooling
Realm version(s): 2.2.1
Android Studio version: 2.2.3

**Comment by Zhuinden** [comment]
I feel like

    Folder.getById(1)
          .addChangeListener((Folder folder) -> Timber.e(folder).getName()));

should work

**Comment by IlyaGulya** [comment]
@Zhuinden thanks for response!
Yeah, it will work that way. However, this is the same way to fix my problem as casting or adding generic type to method. Is it really impossible to make it work without need of such workarounds?
For example, we can add generic type argument to `RealmObject` and extend it like this:
```
public class Folder extends RealmObject<Folder>
```
In this case, i think such methods of `RealmObject` will have ability to correctly infer generic type of argument.

**Comment by kneth** [comment]
I will close the issue for now. @IlyaGulya Please create a new issue (feature request) where you explain your idea of a generic type argument.

**Comment by IlyaGulya** [comment]
@Zhuinden let's move to #3998 and discuss this :smile:
