### ISSUE TITLE
Illegal Argument: Failure when converting to UTF-8; error_code = 5;

### ISSUE THREAD

**Issue by hardartcore** [realm/realm-java#3912]
In our application I've decided to start using Realm instead of SQLite and as we store user chat history in our application I had to create a class which will copy all chat messages stored in SQLite database and insert them in Realm. So as you can guess it's a chat between two people, that means there can be lots of options for input, text in different languages, emoticons and etc. at some point (for now only with one user) there is thrown an exception in our Crashlytics profile

`Non-fatal Exception: java.lang.IllegalArgumentException: Illegal Argument: Failure when converting to UTF-8; error_code = 5;  0x0434 0x0430 0x002c 0x0020 0x0449 0x0435 0x0020 0x043c 0x0435 0x0020 0x0432 0x043a 0x0430 0x0440 0x0430 0x0020 0x0432 0x0020 0x0431 0x0435 0x043b 0x044f 0x002e 0x002e 0xda0e 0xdc3d 0xda00 0xdc3d 0xda00 0xdc3d 0xde00 in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_Table.cpp line 700
       at io.realm.internal.Table.nativeSetString(SourceFile)
       at io.realm.ChatMessageRealmProxy.insertOrUpdate(SourceFile:2014)
       at io.realm.DefaultRealmModuleMediator.insertOrUpdate(SourceFile:1777)
       at io.realm.Realm.insertOrUpdate(SourceFile:1035)
       at com.package.upgrade.LocalDbToRealmUpgradeIntentService$2.execute(SourceFile:268)
       at io.realm.Realm.executeTransaction(SourceFile:1253)
       at com.package.upgrade.LocalDbToRealmUpgradeIntentService.handleUpgradeAction(SourceFile:265)
       at com.package.upgrade.LocalDbToRealmUpgradeIntentService.onHandleIntent(SourceFile:58)
       at android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
       at android.os.Handler.dispatchMessage(Handler.java:111)
       at android.os.Looper.loop(Looper.java:194)
       at android.os.HandlerThread.run(HandlerThread.java:61)`

And yes, it's not fatal exception, which means it won't crash our app, but it means that the code which copies chat messages to Realm will fail and won't transfer anything.
And here is actually what I am doing:

    String query = "BLAH BLAH SQL STATEMENT";
    Cursor cursor = sqLiteDatabase.rawQuery(query, null);
    if (cursor != null) {
        if (cursor.getCount() > 0) {
            final List<ChatMessage> chatMessages = new ArrayList<>();
            for (cursor.move(0); cursor.moveToNext(); cursor.isAfterLast()) {

                String messageId = cursor.getString(cursor.getColumnIndex("custom_msg_id"));

                String messageFromJid = cursor.getString(cursor.getColumnIndex("message_from_jid"));
                String messageToJid = cursor.getString(cursor.getColumnIndex("message_to_jid"));
                // GET ALL FIELDS

                ChatMessage chatMessage = new ChatMessage();
                chatMessage.setMessageId(messageId);
                chatMessage.setFrom(messageFromJid);
                // SET ALL FIELDS

                // ADD TO ARRAYLIST
                chatMessages.add(chatMessage);
            }
            try {
                realm = Realm.getDefaultInstance();
                realm.executeTransaction(new Realm.Transaction() {
                    @Override
                    public void execute(Realm realm) {
                        realm.insertOrUpdate(chatMessages); // IT FAISL HERE
                    }
                });
            } finally {
                if (realm != null && !realm.isClosed()) {
                    realm.close();
                }
            }
        }
        cursor.close();
    }

**Comment by kneth** [comment]
It looks like you have invalid characters in your database. For example the value 0xDC3D is not valid (http://www.fileformat.info/info/unicode/char/dc3d/index.htm). 

In order to ensure platform independence (so you can move Realm files between Android and iOS), Realm is translating any string to UTF-8. Instead of silently ignoring invalid characters, Realm will throw an exception.

If you have an idea of what the string is supposed to be, it could be interesting to know. It could be an unofficial emoji.

**Comment by cmelchior** [comment]
Also note that we have seen invalid Strings happen if you split a string the wrong way. E.g. `String.substring()` can e.g. split a surrogate pair (emoji) the wrong way, which can produce invalid strings. 

It doesn't seem to happen in the code you provided, but I don't know if SQLite might accept such an invalid String. If it does, it will not fail until you try to read it into Realm.

**Comment by hardartcore** [comment]
I don't split emojis or anything in messages. The message body is inserted in SQLite as user types or with emoji codes, for example: 0x1F600 , 0x1F601 ... and so on.

**Comment by cmelchior** [comment]
It can also happen in other ways. Basically any API that modifies a string can corrupt it if it works on char instead of code points.

Unfortunately it is not something we can do much about from our side. You will have to follow code path all the way back to where you get the String and figure out where it might go wrong.

**Comment by hardartcore** [comment]
Basically this code is executed before even starting any other process in app after an upgrade. If I try to insert all messages one by one just to get the string which causes this exception is it going to affect the speed of insert or not significantly because it is inside a transaction at all? Just to say that there can be like 10K messages and maybe more.

**Comment by cmelchior** [comment]
There wouldn't be any performance penality between doing `insertOrUpdate(collection)` or `insertOrUpdate(object)`. The only thing the collection method is doing the loop for you. So you could loop all the messages yourself within a try/catch, and discard/log/alter the messages that are somehow wrong.

**Comment by hardartcore** [comment]
So I just got a report with the string which fails to convert in UTF-8:
> да, ще ме вкара в беля..㠽==?

**Comment by kneth** [comment]
Do you have the error message for the failure? Most of the string seems to be fine but I am wondering what our conversion method is considering as invalid.

**Comment by hardartcore** [comment]
It's the same error, same logca I've just logged the message which causes this exception and that's what I got on crashlytics.

**Comment by kneth** [comment]
@hardartcore Sorry for the late reply.

Looking over the JNI source code of SQLite for Android (https://android.googlesource.com/platform/external/javasqlite/+/master/src/main/native/sqlite_jni.c#410), I can easily imagine that custom keyboards' emojis are copied just fine. Since Realm is a cross-platform tool, we cannot allow that behaviour.

**Comment by Zhuinden** [comment]
@kneth well technically you're still supposed to be able to store an emoji and then retrieve it later.

**Comment by kneth** [comment]
@Zhuinden Yes and no. Realm checks if strings are *valid* UTF. Some keyboard might be using invalid code points.

**Comment by Zhuinden** [comment]
@kneth I can't help but feel it should be a bit more lenient though.

It should either tell you on insert that it doesn't like it, or it should be lenient on retrieval.

Just a hunch.

**Comment by kneth** [comment]
@Zhuinden At some point, we saw many string errors. Back then, the conclusion was that too many developers were ignoring exceptions which was leading to corrupt Realm files. A more relaxed (or lenient) approach would simply mask that apps were buggy.

Cross-platform is now becoming more important than ever (due to Realm Mobile Platform) so now might be a good time to align the Realm products (Realm Cocoa is a bit more lenient).

Btw, this issue is that it tells you it doesn't like the string at insertion. If you need to store *invalid* code points, you can store it as binary data.

**Comment by kneth** [comment]
@hardartcore Have you been able to convert the data?

**Comment by hardartcore** [comment]
@kneth If you use binary data instead of it's ok, but I need this data to be String.

**Comment by Zhuinden** [comment]
@hardartcore you could store the data as binary for the chat, and you could also store a stripped UTF-8 version for searching and queries and stuff

**Comment by kneth** [comment]
@hardartcore By using binary data, you can store any emoji, and you can do the conversion from binary data to string in your app.

**Comment by bmeike** [comment]
@hardartcore Any news?  Did you try using binary data?  If there is anything more we can do for you, chime in.  Otherwise we'll close this ticket.

**Comment by hardartcore** [comment]
@bmeike You can close it.

**Comment by wwgc** [comment]
Entering the same emoji on different devices has different effects.

**Comment by wwgc** [comment]
Entering the same emoji on different devices has different effects:
0x0041 0x006e 0x0061 0x0064 0x0072 0x0065 0x0020 0x0061 0x0020 0x0070 0x0061 0x0072 0x006c 0x0061 0x0072 0x0067 0x006c 0x0069 0x0069 0x0069 0x0069 0x0069 0x0069 0x0069 0x0069 0x0021 0xdc4c 0xd83d 0xde09

**Comment by mkaflowski** [comment]
I have problem for 

> 🔥🔥🔥 The 85 South Show squad took their talents to Miami for a hilarious comedy show that only DC Young Fly, Karlous Miller and Chico Bean could pull off.

And doing substring(3, 9). Shout it be handled by Realm or by me?

**Comment by cmelchior** [comment]
@mkaflowski It is your responsibility to send correct UTF-8 to Realm. `String.substring` is not safe with regard to emojis in this regard as it might break surrogate pairs apart resulting in invalid UTF-8. Depending on your exact use case. If you want to support emojis you need to look into using String API's that operate on code points.
