### ISSUE TITLE
RealmList not implements java.io.Serializable

### ISSUE THREAD

**Issue by unthinkfull** [realm/realm-java#3915]
Please add, thanks!

**Comment by Zhuinden** [comment]
What exactly do you need `Serializable` for? Most of the time, you can easily save an object to the Realm, in which case serializing it to not-Realm and juggling an unmanaged copy is typically not needed.

A possible work-around is to use Parcelable with Parceler, or just convert it to an intermediate type like JSON string.

**Comment by kneth** [comment]
@unthinkfull The purpose of Realm is that Realm takes care for persistence for you. If you really to to store your objects somewhere else, you find do `realm.copyFromRealm(realmList.where().findAll())`.

**Comment by fablue** [comment]
I still think it would be a good idea to implement Serializable, because you might want to use ObjectOutputStream/ObjectInputStream with the models of your application.

**Comment by Zhuinden** [comment]
You're already serializing to Realm, so that seems redundant.

**Comment by fablue** [comment]
It's not about storing it, it is about sending/receiving it. There are certainly cases where you would like to use ObjectOutputStream/ObjectInputStream which requires Serializable. 

And even though: Are you sure, that there is NO reason ever to store your model in a file using Serializable. RealmList should not make this completely IMPOSSIBLE, in my opinion, it should be as powerful as the regular List.

**Comment by Zhuinden** [comment]
`List` does not implement `Serializable`, I think you're thinking of `ArrayList`.

**Comment by fablue** [comment]
Okay my fault, but still: Why not giving me the option to use Serializable to communicate with my server/another process, ... ?

**Comment by algrid** [comment]
It also would be convenient for passing objects in Android Intent extras.

**Comment by Zhuinden** [comment]
@algrid the official Android recommendation is to pass the ID of the object, and query it in the other activity.

**Comment by algrid** [comment]
@Zhuinden Yes, that's to keep it compact and fast. But they still allow to pass Serializable. Consider the scenario when you're doing startActivityForResult and that activity returns you a constructed RealmObject ready to be saved. But you decide whether it'd be saved or modified before saving in calling activity. Of course that all could be done in some other way but sometimes it's just convenient to have it Serializable.

**Comment by Zhuinden** [comment]
> that all could be done in some other way 

Parcelable? 😄

**Comment by algrid** [comment]
Well,
 > or just convert it to an intermediate type

:)

**Comment by fablue** [comment]
@Zhuinden Can you explain to us what reasons we do have NOT to implement Serializable?

**Comment by fablue** [comment]
Would be OK for me but I understand that this could cause confusion.
