### ISSUE TITLE
RealmFileException: Not a Realm file

### ISSUE THREAD

**Issue by lindyfish** [realm/realm-java#3916]
Hi

I've got this crash in my app crash report. 
io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/data/com.xxxx/files/xxxx.realm': Not a Realm file. in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 92 Kind: ACCESS_ERROR.
at io.realm.internal.SharedRealm.nativeGetSharedRealm(Native Method) at io.realm.internal.SharedRealm.getInstance(SourceFile:205) at io.realm.internal.SharedRealm.getInstance(SourceFile:182) at io.realm.RealmCache.createRealmOrGetFromCache(SourceFile:124) at io.realm.Realm.getInstance(SourceFile:227) at 

This is my create Realm code:
    synchronized Realm getRealm() {
        String realmName = getRealmName();
        RealmConfiguration realmConfiguration = mRealmConfigurations.get(realmName);
        if (realmConfiguration == null) {
            mRealmConfigurations.put(realmName, realmConfiguration =
                new RealmConfiguration.Builder().name(realmName).deleteRealmIfMigrationNeeded().build());
        }
        return Realm.getInstance(realmConfiguration);
    }

How can I solve this problem? Thanks.

I'm sorry for my poor english.

#### Version of Realm and tooling
Realm version(s): 2.2.1
Realm sync feature enabled: no
Android Studio version: 2.2.3
Which Android version and device: Android 6.0 HUAWEI \ Android 6.0.1 SM-G9350 and others

**Comment by Zhuinden** [comment]
What is `getRealmName()`

**Comment by lindyfish** [comment]
getRealmName() is a method to generate realm file name.

**Comment by Zhuinden** [comment]
That's great, but what does it actually generate?

**Comment by lindyfish** [comment]
that is not the point, right?
mRealmConfigurations is a HashMap<String, RealmConfiguration>

**Comment by Zhuinden** [comment]
> that is not the point, right?

That is the point, you are generating an invalid filename. So it breaks.

**Comment by lindyfish** [comment]
Oh, really ?
"shana.c8c50ce7d6dd4c85ace8b2d1d125a2c0.realm", it's the full filename.

**Comment by Zhuinden** [comment]
Ah, now that's a bit different than `files/.realm` isn't it? 

Anyways, in that case, I just wonder if the identifier is too long. I'll leave answering this to actual Realm fellaa

**Comment by diegomontoya** [comment]
Maybe related https://github.com/realm/realm-java/issues/3895

**Comment by kneth** [comment]
Android devices are often using FAT based file systems which have a few limitations: https://msdn.microsoft.com/en-us/library/aa365247(VS.85).aspx But I don't think you are hit by any of those.

Why do you mean `synchronized`? Do you have multiple threads which are creating Realms?

**Comment by lindyfish** [comment]
Yes, you're right, there is no need to mean synchronized, Let me try it.
Could this be the reason?

**Comment by sunshinehu** [comment]
I‘m also the team member，I want to know what will happen when the app crashes while the Realm is writing the file?

**Comment by lindyfish** [comment]
Will using Realm.getInstance and Realm.close frequently cause this crash?

**Comment by Zhuinden** [comment]
@lindyfish only if you either have a Realm instance that you don't close on background thread, or if you do this in a concurrent **process** (like a BroadcastReceiver with `android:process=":remote"`)

**Comment by kneth** [comment]
@sunshinehu If a crash happens during a write, the file should be fine. The only case where a corruption in theory can happen is if the device looses power.

**Comment by kneth** [comment]
@lindyfish @sunshinehu Did @Zhuinden's latest comment help you to resolve the issue?

**Comment by Zhuinden** [comment]
@kneth I don't think it did. I ran out of ideas on this one.

**Comment by kneth** [comment]
I leave the issue open and give the reporters a chance to comment.

**Comment by bmeike** [comment]
No response from OP.  Closing.
