### ISSUE TITLE
When using Realm with RxJava's Schedulers.io(), the Realm instance is not updated

### ISSUE THREAD

**Issue by garretyoder** [realm/realm-java#3923]
#### Goal
Make calls to Realm from within a RxJava observable on the io scheduler thread

#### Expected Results
Calling `Realm.getDefaultInstance();` and using said Realm instance should have the latest copy of data and operate properly.

#### Actual Results
A old(?) copy of the Realm database is fetched (presumably the one created by the first use of the Scheduler IO thread) that is not up to date with more recent changes in the database.

*NOTE* Using `Schedulers.newThread()` over `Schedulers.io()` fixes the problem, presumably because this is a new thread and has a brand new instance of realm.

#### Steps & Code to Reproduce
1. Make some change to the realm database on the UI thread
2. Try to access the changed data from a Observable subscribing on `Schedulers.io()`.

#### Code Sample
Sample from the Gallery project I found this bug in. This observable is responsable for deleting entries from the database that are marked with a boolean.
```java
public static Observable<Boolean> deleteFiles(final String album) {
        return Observable
                .create(new Observable.OnSubscribe<Boolean>() {
                    @Override
                    public void call(Subscriber<? super Boolean> subscriber) {
                        boolean result = true;
                        final Album target = Realm.getDefaultInstance().where(Album.class).equalTo("path", album).findFirst();
                        for (MediaItem item : target.getSelected()) {
                            if (!deleteFileImpl(target, item)) {
                                result=false;
                            }
                        }
                        Realm.getDefaultInstance().executeTransaction(new Realm.Transaction() {
                            @Override
                            public void execute(Realm realm) {
                                target.clearMediaSelection();
                                target.setLastModified(new File(target.getPath()).lastModified());
                                if (target.getMedia().size()<1) {
                                    realm.where(Album.class).equalTo("path", target.getPath()).findAll().deleteAllFromRealm();
                                }
                            }
                        });
                        subscriber.onNext(result);
                        subscriber.onCompleted();
                    }
                })
                .observeOn(AndroidSchedulers.mainThread())
                .subscribeOn(Schedulers.newThread());
    }
```
The realm instance provided should have the latest changes (changing the booleans of the items flagged for deletion to `true`) but this is not what happens.

#### Version of Realm and tooling
Realm version(s): 2.2.0

Realm sync feature enabled: no

Android Studio version: 2.2.3

Which Android version and device: HTC10 - N & any emulator version

**Comment by Zhuinden** [comment]
You're opening Realm instances that you never close, so your version gets retained. 

I wrote an article about this and it's actually the first day in the current [Realm adventure calendar](https://realm.io/news/realm-adventure-schedule-2016/).

So yeah, this is to be expected.

**Comment by garretyoder** [comment]
That was it, so that was my own personal mistake. Thanks and cheers!

**Comment by Zhuinden** [comment]
On thread-pools, sometimes you can have multiple threads running at the same time, and a previous thread can still have an open Realm while the new thread would like to see a newer version of the Realm.

In such cases, with some minor internal API usage, it is possible to [refresh the Realm after `Realm.getDefaultInstance()`](http://stackoverflow.com/a/38839808/2413303).

But not closing the Realm is the immediate issue, it can cause trouble later if you don't.
