### ISSUE TITLE
AMap only support armabi 

### ISSUE THREAD

**Issue by ab503044120** [realm/realm-java#3924]
now , I Use AMap, their only support 'armabi' ,but realm not support 'armabi'
I think you should support 'armabi' 
here fix it 'https://github.com/realm/realm-java/blob/master/realm/realm-library/build.gradle'
by adding 'armabi'
 
#### Version of Realm and tooling
Realm version(s): ?
2.2.1
Android Studio version: ?
2.2.3

**Comment by ab503044120** [comment]
i try to fixit by move *.so files from 'armeabi' to 'armeabi-v7a' ,and add 
` splits {
        // Split apks on build target ABI, view all options for the splits here:
        // http://tools.android.com/tech-docs/new-build-system/user-guide/apk-splits
        abi {
            enable true
            reset()
            include  'armeabi-v7a'//, 'arm64-v8a', 'mips', 'x86', 'x86_64'//'armeabi'
        }
    }`
to gradle .
at end please support armabi ,  it is very important
![image](https://cloud.githubusercontent.com/assets/5219122/21300668/f8913bce-c5e0-11e6-96a4-309486be3bd1.png)

**Comment by kneth** [comment]
@ab503044120 Adding support for ARMEABI is tracked by #3506.

**Comment by Zhuinden** [comment]
In the meantime, if you haven't actually released the app in production yet, then you can easily revert to 1.2.0 which still supports armeabi.

**Comment by Zhuinden** [comment]
https://github.com/realm/realm-java/issues/4440#issuecomment-292113812
