### ISSUE TITLE
Reverse an ordered RealmList

### ISSUE THREAD

**Issue by Murtaza0xFF** [realm/realm-java#3925]
Is it still not possible to reverse an ordered RealmList? I made a mistake of not adding a date column, and now I want it sorted by most recent. The only way to achieve that seems to be reversal. Since it hasn't yet been implemented, is the general consensus that this is a bad idea?

**Comment by beeender** [comment]
You can build a query based on that:
```java
RealmResults<YourModel> results = yourList.where().findAllSorted("date", Sort.Desending);
```

**Comment by Murtaza0xFF** [comment]
Yeah, I'm aware I can do that, but I don't have a date column is what the problem is.

**Comment by beeender** [comment]
Then I don't think there is a reliable way to do that ... sorry ..

**Comment by cmelchior** [comment]
@Murtaza0xFF Any problems just reversing the list in a migration step when people upgrade the app?

**Comment by Murtaza0xFF** [comment]
Yeah, I might just have to do that.

**Comment by SteveKamau72** [comment]
You could try:

`Collections.reverse(myRealmModelRealmResults);`
