### ISSUE TITLE
Not access to Realm Dashboard at the localhost following installation tuturial

### ISSUE THREAD

**Issue by ojarabo** [realm/realm-java#3927]
Hi all, 
I have been following the tutorial to start using the Realm Mobile Platform. I have installed Realm Object server without throwing any error in the console. The Realm Mobile Platform has been installed locally in my computer, which runs a Ubuntu 16.04, to start programming locally.  

The problem is that I can't access to the Realm Dashboard when I go to http://localhost:9080. It just appeared the typical Unable to connect. Has anyone had a similar problem?

Sorry for the inconvenience and thanks in advance.

**Comment by cmelchior** [comment]
Not that we are aware of. Are you 100% you started the server? Also to rule out any network issues, have you tried connecting to `http://127.0.0.1:9080` instead?

**Comment by ojarabo** [comment]
Sorry for the delay, 
I was updating my question in [here](https://github.com/realm/realm-mobile-platform/issues/74). There is a better explanation of what I am trying to do. 

Answering your question. Yes, I have tried `http://127.0.0.1:9080` with same result.

**Comment by kneth** [comment]
I close the issue as it is better answered in your issue at the `realm-mobile-platform` repository.
