### ISSUE TITLE
Error with Realm 2.2+ Could not find method apt()

### ISSUE THREAD

**Issue by ch-vadim-maximov** [realm/realm-java#3929]
Error:(135, 1) A problem occurred evaluating project ':app'.
> Could not find method apt() for arguments [org.parceler:parceler:1.1.6] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

Hello,

Trying to upgrade from Realm 1.2.0 to 2.2.1

As soon as I change version to 2.2.0 or 2.2.1 I get the following error:

Error:org.gradle.internal.metaobject.AbstractDynamicObject$CustomMessageMissingMethodException: Could not find method apt() for arguments [org.parceler:parceler:1.1.6] on object of type org.gradle.api.internal.artifacts.dsl.dependencies.DefaultDependencyHandler.

Versions 2.0.x - 2.1.x work fine.

Android Studio version: 2.2.3

Is there any way to fix this? Workarounds?
Thanks!

**Comment by Zhuinden** [comment]
Please share your gradle plugin order 

    apply plugin: 'com.android.application'
    // ...

**Comment by ch-vadim-maximov** [comment]
`apply plugin: 'com.android.application'
apply plugin: 'realm-android'
apply plugin: 'io.fabric'
apply plugin: 'jacoco'`

`dependencies {
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
        classpath 'com.android.tools.build:gradle:2.2.3'
        classpath "io.realm:realm-gradle-plugin:2.2.1"
        // The Fabric Gradle plugin uses an open ended version to react
        // quickly to Android tooling updates
        classpath 'io.fabric.tools:gradle:1.+'
    }`

**Comment by Zhuinden** [comment]
If by chance you use `apt` scope on any of your dependencies, then change it to `annotationProcessor`.

**Comment by ch-vadim-maximov** [comment]
@Zhuinden Thank you!
Yes I had:
```
    compile 'org.parceler:parceler-api:1.1.6'
    apt 'org.parceler:parceler:1.1.6'
```
Fixed with:
```
    compile 'org.parceler:parceler-api:1.1.6'
    annotationProcessor 'org.parceler:parceler:1.1.6'
```
