### ISSUE TITLE
findAllAsync() sometimes fails to return any results when using it in sync mode

### ISSUE THREAD

**Issue by joluet** [realm/realm-java#3938]
Sometimes `findAllAsync()` does not call the change listener. 

I created a sample project that demonstrates the issue. Actually, I just copied the _RealmTasks_ example, removed the Facebook SDK and then replaced `findAll()` with `findAllAsync()`. You can find it here: https://github.com/joluet/RealmTasksDemo

This project lets you reproduce the issue consistently. To reproduce it I follow these steps:
1. Make sure Realm Object Server is running and connected
2. Register a new user in the app
3. Navigate back to get to the TaskListActivity 
5. Observe that there is **no task list**
6. Rotating the phone or restarting the app will bring back the list called _My Task_

Also, deleting, adding, or editing list items can make task lists disappear.

**Comment by cmelchior** [comment]
Thank you very much for this. We will look into it.

**Comment by dalinaum** [comment]
I just reproduced this problem. I am checking whether there is a mistake of RealmTasks.

**Comment by joluet** [comment]
@dalinaum @cmelchior any progress on this one?

**Comment by cmelchior** [comment]
@dalinaum What is the status on this?

**Comment by cmelchior** [comment]
We need to verify that this is still a problem after #3834 has been merged.

**Comment by dalinaum** [comment]
@joluet There is a work-around. If you move some code from `onStart` and `onStop` to `onResume` and `onPause`, it would works. 
We will look into this issue with a new implementation soon.

**Comment by Zhuinden** [comment]
I don't think that should affect anything,.. 😞

**Comment by beeender** [comment]
@dalinaum can you please help to verify if this is fixed by #3834? It has been merged to the master and the snapshot should be available.

**Comment by Zhuinden** [comment]
This should have been fixed by either Realm 3.0 or Realm 3.1....

**Comment by cmelchior** [comment]
This should have been fixed by Realm Java 3.1 with notifications on commit.
