### ISSUE TITLE
Fatal Exception: java.lang.IllegalStateException Fatal Exception thrown on Scheduler.Worker thread.

### ISSUE THREAD

**Issue by bryanleesh** [realm/realm-java#3941]
Realm version(s): 0.88.2

I'm getting quite a lot of crashes regarding to this log. (using fabric) Just want to have some direction where can I debug this because I couldn't replicate this issue but it seems like quite random happen in user device.

The log is quite long so i attach the file here.
[crash_log.txt](https://github.com/realm/realm-java/files/670522/crash_log.txt)

Seems like this is the main cause.
`Caused by io.realm.exceptions.RealmError: Unrecoverable error. mmap() failed: Out of memory size: 117440512 in io_realm_internal_SharedGroup.cpp line 188`
But i don't understand why this happen.

**Comment by Zhuinden** [comment]
This tends to happen if you:

1.) open Realm instances on background thread that you don't close

2.) you create many transactions in a loop, instead of using 1 transaction that begins outside the loop

**Comment by kneth** [comment]
Please consider to upgrade - we have fixed many issues and added many improvements since 0.88.2.
