### ISSUE TITLE
java.lang.IllegalStateException: Mutable method call during read transaction.

### ISSUE THREAD

**Issue by vranacse** [realm/realm-java#3942]
> We LOVE to help with any issues or bug you have!

> **Questions**: Hey I just want to delete some entries from the already queried from Realm. But i am getting this exception 

> **Feature Request**:IT should be simmple to delete or remove just from queried data but not from the realm itself

> **Bugs**: See this
>
>
>
> 

#### Goal

> Just see and give the appropriate solution for this

#### Expected Results

> should be removed from the list

#### Actual Results

>    java.lang.IllegalStateException: Mutable method call during read transaction.
                                                                                at io.realm.internal.TableView.throwImmutable(TableView.java:944)
                                                                                at io.realm.internal.TableView.remove(TableView.java:566)
                                                                                at io.realm.RealmResults.remove(RealmResults.java:464)

#### Steps & Code to Reproduce

> Describe your current debugging efforts.

#### Code Sample

```java

> for (int i = 0; i < RealmContractItemList.size(); i++) {
            if (RealmContractItemList.get(i).getID().equalsIgnoreCase(key)) {
                Log.e(TAG,RealmContractItem.get(i).getID());
                RealmContractItemList.remove(i);
            }
        }
> 

```

#### Version of Realm and tooling
Realm version(s): ?

Realm sync feature enabled: yes/no

Android Studio version: ?

Which Android version and device: ?

**Comment by beeender** [comment]
You need to begin transaction when making changes to Realm.
See https://realm.io/docs/java/latest/#writes

**Comment by vranacse** [comment]
I dont wan to make changes in realm  db that ok ! i am just population queried  data in some view but i need to remove data from the already queried data

**Comment by beeender** [comment]
But you are calling `RealmContractItemList.remove(i);` where `RealmContractItemList` is an managed Realm collection, `remove()` will modify the underlying Realm data.

From what i can tell, you can use query instead. Something like:
```
eealmContractItemList = realm.where(YouModel.class).equalTo("subObject.ID",  key, case.INSENSITIVE).findALL();
```

See https://realm.io/docs/java/latest/#queries

**Comment by vranacse** [comment]
you mean i cannot remove the item from RealmContractItemList  Realm collection?  if its possible to remove without writing any other query  . HOW?

**Comment by Zhuinden** [comment]
@beeender actually, it is a `RealmResults` and he is calling `remove(int)` on it.

It should throw `UnsupportedOperationException` since 0.89.0.

```
    /**
     * Not supported by RealmResults.
     *
     * @throws UnsupportedOperationException
     */
    @Deprecated
    @Override
    public E remove(int index) {
        throw new UnsupportedOperationException(NOT_SUPPORTED_MESSAGE);
    }
```

**Comment by vranacse** [comment]
yeah ! exactly

**Comment by Zhuinden** [comment]
@vranacse `RealmResults` is a Cursor (in the form of a list) to the underlying database, it contains a list of pointers to the elements that satisfy the query conditions. You cannot mutate the "result set returned for those given conditions", unless you mutate the underlying data. This is to always obtain a consistent view of the result set - after all, if you arbitrarily remove an element from that results, but you also commit a write transaction that updates the result set, then who will keep track of which element shouldn't be evaluated by the Realm Core?

`realmResults.remove()` wouldn't even be allowed, you are using an outdated version of Realm. I'm not sure which, it's definitely something before 0.89.0.

You have two hacky workarounds:

1.) 

    List<E> list = new ArrayList<>();
    list.addAll(realmResults);

2.)

    List<E> list = realm.copyFromRealm(realmResults);

**Comment by vranacse** [comment]
Yeah that good but still not a good way to process the data

On 23-Dec-2016 7:30 PM, "Gabor Varadi" <notifications@github.com> wrote:

@vranacse <https://github.com/vranacse> RealmResults is a Cursor (in the
form of a list) to the underlying database, it contains a list of pointers
to the elements that satisfy the query conditions. You cannot mutate the
"result set returned for those given conditions", unless you mutate the
underlying data. This is to always obtain a consistent view of the result
set - after all, if you arbitrarily remove an element from that results,
but you also commit a write transaction that updates the result set, then
who will keep track of which element shouldn't be evaluated by the Realm
Core?

realmResults.remove() wouldn't even be allowed, you are using an outdated
version of Realm. I'm not sure which, it's definitely something before
0.89.0.

You have two hacky workarounds:

1.)

List<E> list = new ArrayList<>();
list.addAll(realmResults);

2.)

List<E> list = realm.copyFromRealm(realmResults);

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/realm/realm-java/issues/3942#issuecomment-268994021>,
or mute the thread

**Comment by Zhuinden** [comment]
Well the point of a RealmResults is that it *always* provides a *consistent view* of the data inside the Realm database.

So `remove()` doesn't really make sense on it.

**Comment by vranacse** [comment]
Yeah thanks friends ! I
