### ISSUE TITLE
I am trying to store JSON data to Realm but it's not storing RealmList inside RealmObject

### ISSUE THREAD

**Issue by aravindcraj** [realm/realm-java#3944]
**Goal:**
> To store the JSON data received from the server.

**Output:**
> Realm objects are stored in Realm but RealmList<BookmarkedPost> is storing data it's empty.

**Steps done:**
I was trying to store all JSON data I fetched from the server and make a                                 

`realm.createObjectFromJson(User.class,` response);` but it is avoiding my inner RealmList and not storing any data.

> **Realm transaction to store from JSON:**

```
`realm.executeTransaction(new Realm.Transaction() {
                            @Override
                            public void execute(Realm realm) {
                                realm.createObjectFromJson(User.class, response);
                            }
                        });`

```
And the JSON looks like this, 

```

`{
  "success": true,
  "token": "t88LLNEXQL3w4K9mlB9MOwtt",
  "user": {
    "id": 28,
    "name": "Aravind",
    "email": "ar@gmail.com",
    "mobile": "9176",
    "points": 0,
    "leader": true,
    "username": "ar",
    "bookmarked_posts": [
      {
        "id": 7
      },
      {
        "id": 8
      }
    ]
 }`


```
And POJO for that looks like this,

```
public class User extends RealmObject {

    @SerializedName("id")
    private String id;
    @SerializedName("name")
    private String name;
    @SerializedName("email")
    private String email;
    @SerializedName("mobile")
    private String mobile;
    @SerializedName("points")
    private String points;
    @SerializedName("leader")
    private String isAnonyomous;
    @SerializedName("username")
    private String username;
    @SerializedName("bookmarked_posts")
    private RealmList<BookmarkedPost> bookmarkedPost;
```

And BookmarkedPost looks like this,

```
`public class BookmarkedPost extends RealmObject {

    @SerializedName("id")
    private int id;`

```
Now Realm is storing all User details such as name, username, email.. etc. but BookmarkedPost data is not present. It's not storing in Database.

**Comment by beeender** [comment]
Realm doesn't respect `@SerializedName` annotation. So you need to make the field name match the one in the JSON. See #1470 .

**Comment by Zhuinden** [comment]
The `createOrUpdateObjectFromJson()` would work only if you receive a json like this

```
{
    "id": 28,
    "name": "Aravind",
    "email": "ar@gmail.com",
    "mobile": "9176",
    "points": 0,
    "leader": true,
    "username": "ar",
    "bookmarked_posts": [
      {
        "id": 7
      },
      {
        "id": 8
      }
   } 
```

This is not the case, so you'll need to save the object via a Java object and `insertOrUpdate` call

**Comment by abhinav-adtechs** [comment]
@aravindcraj 
use the @ignore annotation conveniently to fix this issue.

**Comment by shankarsimu** [comment]
how to store API data in realm database??

**Comment by cmelchior** [comment]
Hi @shankarsimu Please create a new issue with more details.
