### ISSUE TITLE
jni: ThrowingException 7, std::exception in /Users/zaki/fromgit/realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp line 1160

### ISSUE THREAD

**Issue by hanguodong** [realm/realm-java#3949]
when I play a music stream by mediaplayer realm throw this exception, but if  I play a music file the reaml is alright

**Comment by beeender** [comment]
Can you please share some more logs? It would be helpful it contains some log some minutes before exception happens. Can you reproduce this issue? Does it crash the app or it is just some log printed in the background?

**Comment by hanguodong** [comment]
1. not crash
2.when playing music by mediaplayer, then use realm to query ,findAllAsync will not call back change listener and throw this jni exception but findAll is allright
3. when playing music ,copyOrUpdate is ok in version 2.0.2,but the same code in 2.2.2 always save the latest model

**Comment by beeender** [comment]
It is difficult to tell what is happening with limited information. For 1 & 2, there is going to be some changes after #3834 merged, I suggest you try the new release after #3834 merged.

for 3, can you demonstrate the problem with a minimal project? I don't quite understand the problem according to the description.
