### ISSUE TITLE
Lags on long operations on One Plus 3 (OxygenOs) Android device, give ANR.

### ISSUE THREAD

**Issue by harshgaba** [realm/realm-java#3953]
old issue:- https://github.com/realm/realm-java/issues/3847

Hello @kneth, Sorry i was out from city, insertOrUpdate() not solved my problem, i also optimised my code and batch-insert like this http://stackoverflow.com/a/39385985/2413303. but the problem is same.
i updated to classpath "io.realm:realm-gradle-plugin:2.2.1" still same problem :(

here is my code:-
public boolean saveToRealm(Context context, final List bookmarksList) {
Realm realm = Realm.getDefaultInstance();
try {
realm.executeTransaction(new Realm.Transaction() {
@Override
public void execute(Realm realm) {
realm.insertOrUpdate(bookmarksList);
}
});
} catch (Exception e) {
e.printStackTrace();
} finally {
realm.close();
}}

**Comment by Zhuinden** [comment]
What thread is this on? Try using `executeTransactionAsync`

**Comment by harshgaba** [comment]
its in Sepreate thread by calling: -
 Thread t = new Thread() {
                            @Override
                            public void run() {
                             saveToRealm(context,bookmarksList)
                                }};
                        t.start();

and i also tried with executeTransactionAsync but same freezing my UI, and even i have paginated call, means i'm getting data in 20 items per call and when i get the first 20 items then i parse it with gson and then save it in realm by above function code. i also tried it with AsynTask but didn't work. :(

**Comment by Zhuinden** [comment]
Do you use `findAll()`, or `findAllAsync()` for obtaining the results?

**Comment by harshgaba** [comment]
Yes, i'm using findAll(), but with RealmRecyclerViewAdapter with  recycler view, with auto updation, 
here is my Adapter constructor:-

 public bookyAdapter(@NonNull Context context, @Nullable OrderedRealmCollection data, boolean autoUpdate) {
        super(context, data, autoUpdate);
        bookmarkManager = BookmarkManager.getInstance(context);
        appPreference=new AppPreference(context);
    }


i'm using:- compile 'io.realm:android-adapters:1.3.0'

And here is my Query:-

 public RealmResults<Bookmark> fetchBookmarkedData(Context context) {
        Realm realm = Realm.getDefaultInstance();
        RealmResults<Bookmark> bookmarks = null;
        if (realm != null) {
            bookmarks = realm.where(Bookmark.class).equalTo("bookmarkState", 1).findAll().sort("timestamp", Sort.DESCENDING);
        }
        return bookmarks;
    }

**Comment by Zhuinden** [comment]
You can try using `findAllSortedAsync()` instead of `findAll().sort()`. 

Also, considering this is OxygenOS, if you are showing ANY images anywhere, you should use Glide library to load the image.

**Comment by harshgaba** [comment]
Sorry i didn't get that "OxygenOs", I'm using Glide everywhere for showing images. Ok i will try findAllSortedAsync() but i think i'm getting this issue in inserting the data in Realm. because i tried  by removing the MY Recycler View, means just parse the data and save in realm, no data fetch query from realm after saving.

**Comment by harshgaba** [comment]
No improvement in performance:-
Here is the code:-
 bookmarks=realm.where(Bookmark.class).equalTo("bookmarkState", 1).findAllSortedAsync("timestamp");

**Comment by Zhuinden** [comment]
You forgot the `Sort.DESCENDING`  compared to your original code. 

If your JSON is very large (10000+ items), then parsing it into a list will trigger GC when your operations are done, which can  cause lag. 

You should consider profiling your application using SysTrace to see what operation is causing the jitter.

**Comment by harshgaba** [comment]
I have big JSON but not more than max 100 items, and i'm using Retrofit2 with GSON to parse the data, now in this case i'm only getting 20 items in one Api call response and i call next when all realm operations done, and all in background thread.

->I debug it with various method by firstly checking the debugger and monitor of Android studio 2.2,
-> then i tried with checking some third party library like Pury, which provides execution time of every method and it gives long execution time on table operations methods.
-> then finally, i tried with native sqlite by replacing realm, with the same table structure and operations and then its working fine on OxygenOs and mainly on One Plus 3.

**Comment by harshgaba** [comment]
ok i will try profiling application using SysTrace. and will send my implementation code at help[at] realm.io.

**Comment by kneth** [comment]
Did you have a chance to profile your app?

**Comment by bmeike** [comment]
@harshgaba Any news for us?  If not, I think we can just close this ticket.

**Comment by bmeike** [comment]
If there is anything else we can do for you, please don't hesitate to re-open this ticket, or to create a new one.
