### ISSUE TITLE
Object is no longer valid to operate on.

### ISSUE THREAD

**Issue by MahmoudAlyuDeen** [realm/realm-java#3955]
Realm throws "Object is no longer valid to operate on" when I try to edit it.
I just queried the object from a fresh instance and the objects .isValid returns true.

Note: this only happens when I have earlier queried all objects from that class and called .deleteAllFromRealm on the results. that however mustn't cause the .findFirst() query called afterwards to return an invalid object.

Note: the weird thing about this issue is that it always happens only the first time I try to access that object after deleting it from realm and then re-adding it again. the crash happens even if I delete all from realm, then exit the application altogether, then open it again and add the object, then try to access it. and it only happens once, it never happens twice in a row without me deleting all in between.

Code:
```java
public static void storeRestricted(PersonResponse personResponse) {
        Realm realm = Realm.getDefaultInstance();
        Owner owner = realm.where(Owner.class).findFirst();
        if (owner == null) {
            return;
        }
        owner.load();
        Log.d("@@@@", "storeRestricted: " + owner.isValid());
        realm.beginTransaction();
        owner.setRestricted(
                getRealmStringListFromStringList(realm, personResponse.getRestricted()));
        realm.copyToRealmOrUpdate(owner);
        realm.commitTransaction();
        realm.close();
    }
```

Result:
```12-27 21:06:18.486 5608-5643/com.forartstudio.fady D/@@@@: storeRestricted: true
12-27 21:06:18.487 5608-5643/com.forartstudio.fady E/REALM_JNI: Row true is no longer attached!
12-27 21:06:18.487 5608-5643/com.forartstudio.fady E/REALM_JNI: jni: ThrowingException 8, Object is no longer valid to operate on. Was it deleted by another thread?, .
12-27 21:06:18.487 5608-5643/com.forartstudio.fady E/REALM_JNI: Exception has been throw: Object is no longer valid to operate on. Was it deleted by another thread?
12-27 21:06:18.489 5608-5643/com.forartstudio.fady E/AndroidRuntime: FATAL EXCEPTION: pool-4-thread-1
                                                                     Process: com.forartstudio.fady, PID: 5608
                                                                     java.lang.IllegalStateException: Object is no longer valid to operate on. Was it deleted by another thread?
                                                                         at io.realm.internal.UncheckedRow.nativeGetLinkView(Native Method)
                                                                         at io.realm.internal.UncheckedRow.getLinkList(UncheckedRow.java:173)
                                                                         at io.realm.OwnerRealmProxy.realmSet$restricted(OwnerRealmProxy.java:613)
                                                                         at com.forartstudio.fady.beans.Owner.setRestricted(Owner.java:33)
                                                                         at com.forartstudio.fady.Utilities.storeRestricted(Utilities.java:355)
                                                                         at com.forartstudio.fady.main.MainPresenter$2$1.run(MainPresenter.java:184)
                                                                         at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1133)
                                                                         at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:607)
                                                                         at java.lang.Thread.run(Thread.java:761)
12-27 21:06:18.492 1054-6629/system_process W/ActivityManager:   Force finishing activity com.forartstudio.fady/.main.MainActivity
```

**Comment by Zhuinden** [comment]
Okay so this

        owner.setRestricted(
                getRealmStringListFromStringList(realm, personResponse.getRestricted()));

involves an unknown method `getRealmStringListFromStringList` which is relevant to this question; and also in `Owner` class, what is the field type for `Restricted`?

**Comment by Zhuinden** [comment]
Btw please try this method like this:

``` java
    public static void storeRestricted(PersonResponse personResponse) {
        Realm realm = Realm.getDefaultInstance();
        realm.beginTransaction();
        Owner owner = realm.where(Owner.class).findFirst();
        if (owner == null) {
            realm.cancelTransaction();
            realm.close();
            return;
        }
        owner.setRestricted(
                getRealmStringListFromStringList(realm, personResponse.getRestricted()));
        realm.copyToRealmOrUpdate(owner);
        realm.commitTransaction();
        realm.close();
    }
```

**Comment by MahmoudAlyuDeen** [comment]
>this involves an unknown method getRealmStringListFromStringList which is relevant to this question; and also in Owner class, what is the field type for Restricted?

that method's return type is RealmList<RealmString>, and I don't think the method is relative as your suggestion worked.

However I'm curious as to why it works, I know that making the query inside a Realm transactions guarantees that the query is executed on an up to date realm instance, but the object my old method crashed on was indeed valid and not one of the deleted objects.

thanks

**Comment by Zhuinden** [comment]
It was valid according to a Realm instance that if this is on a background thread, then it probably had its version retained, for example due to `if( == null)` ever occurred, then the Realm instance was never closed.

So in reality the object was valid according to an out of date Realm instance, but the object had already been deleted in the new version of the Realm (because Realm gets updated to the latest when you call `realm.beginTransaction()`, so `isValid()` would probably have returned false afterwards.)

**Comment by Zhuinden** [comment]
If you want to read a bit more about version retention, I wrote [this article about it a while ago](https://medium.com/@Zhuinden/understanding-realm-version-retention-and-synchronization-9a513c2445bb#.h52laf4m3).

**Comment by MahmoudAlyuDeen** [comment]
That clears everything up very well, thanks a lot.
