### ISSUE TITLE
Too many open files in io_realm_internal_SharedGroup 0.88.2

### ISSUE THREAD

**Issue by monkeyfdude** [realm/realm-java#3956]
> What do you want to achieve?

No app crash

>  E.g. full stack trace with exception

io.realm.exceptions.RealmError: Unrecoverable error. open() failed: Too many open files in io_realm_internal_SharedGroup.cpp line 113
!	1	at io.realm.internal.SharedGroup.createNativeWithImplicitTransactions(Native Method)
2	at io.realm.internal.SharedGroup.<init>(SourceFile:64)
3	at io.realm.internal.SharedGroupManager.<init>(SourceFile:49)
4	at io.realm.BaseRealm.<init>(SourceFile:76)
5	at io.realm.Realm.<init>(SourceFile:138)
6	at io.realm.Realm.b(SourceFile:268)
7	at io.realm.Realm.a(SourceFile:248)
8	at euu.a(SourceFile:114)
9	at io.realm.Realm.getInstance(SourceFile:213)

#### Code Sample

```java

        RealmConfiguration realmConfig = new RealmConfiguration.Builder(context)
                .name("myRealm")
                .schemaVersion(0)
                .build();

        return Realm.getInstance(realmConfig);

```

#### Version of Realm and tooling
Realm version(s): 0.88.2

Android Studio version: 2.1

Which Android version and device: Various different devices.

**Comment by beeender** [comment]
It seems you have some Realm instances NOT CLOSED in the background thread. I suggest you to check. Instance returned by `getInstance()` needs to be closed properly.

**Comment by monkeyfdude** [comment]
I do have following realm.close executed every time I do a getInstance()

       try {
            realm = RealmCommon.getInstance(context);
            realm.beginTransaction();
            realm.commitTransaction();
        } finally {
            if (realm != null) {
                realm.close();
            }
        }

**Comment by monkeyfdude** [comment]
Is there a way I can detect this leak if I am closing or not. From code review, it seems ok to me.

**Comment by Zhuinden** [comment]
You should create the RealmConfiguration only once, although I'm not sure if this can cause this problem.

You might just have far too many concurrent threads.

**Comment by beeender** [comment]
Do you open any other files (not realm file) in your app? opening files without closing them cause the process run out of file descriptors.

**Comment by monkeyfdude** [comment]
Yes I do. I am closing this issue for now. I will reopen if needed. Thanks.
