### ISSUE TITLE
Realm 1.2.0: removing @PrimaryKey constraint does not trigger RealmMigrationNeededException

### ISSUE THREAD

**Issue by Zhuinden** [realm/realm-java#3966]
I like the whole issue template thing, but this one really doesn't need one.

`deleteIfMigrationNeeded()` did not delete Realm after removing `@PrimaryKey` annotation.

#### Version of Realm and tooling
Realm version(s): 1.2.0

Realm sync feature enabled: no

Android Studio version: .

Which Android version and device: .

**Comment by nhachicha** [comment]
seems like a bug in the proxy class

**Comment by beeender** [comment]
We missed the checking in the generated proxy file for it should NOT be a primary key.
But checking for every field sounds stupid. the PK should only be checked once in the `validateTable`.

**Comment by nhachicha** [comment]
fixed in `2.2.2`
