### ISSUE TITLE
Related objects via RealmList are not returned when queried on the parent object

### ISSUE THREAD

**Issue by jraczak** [realm/realm-java#3967]
#### Goal

> Returning a count of Realm objects related to a given Realm object via standard getter

#### Expected Results

> A count, via `.size()`, of related objects in a `RealmList`.

#### Actual Results

>  No results are returned. Log confirms empty results: `D/DashboardWorkoutAdapter: Workout has Set@[] sets`

#### Steps & Code to Reproduce

> Describe your current debugging efforts.

#### Code Sample

```java

// Workout model (parent object)
public class Workout extends RealmObject implements Parcelable {

    private static final String LOG_TAG = Workout.class.getSimpleName();

    @PrimaryKey
    private Integer realmId;
    @Required
    private String name;
    private RealmList<Set> sets;
    public RealmList<Exercise> exercises;
    private Date date;
    private Date startTime;
    private Date finishTime;
...

// Set Getter from Workout model, standard stuff
    public RealmList<Set> getSets() {
        return sets;
    }

// Set model (child object)
public class Set extends RealmObject implements Parcelable {

    private final static String LOG_TAG = Set.class.getSimpleName();

    @PrimaryKey
    private Integer realmId;
    @Required
    private Date date;
    private Workout workout;
    private Exercise exercise;
    private int reps;
    private float weight;
...

// Activity where set is created and relationship to workout is linked
public void onSetsSaved(Exercise exercise, Workout workout, int reps, float weight) {
        Log.d(LOG_TAG, "onSetsSaved called");

        mRealm.beginTransaction();
        Set set = mRealm.createObject(Set.class, Set.getNewAutoIncrementId());
        set.setWorkout(workout);
        set.setExercise(exercise);
        set.setDate(new Date());
        set.setReps(reps);
        set.setWeight(weight);
        //set.setRealmId(Set.getNewAutoIncrementId());
        mRealm.commitTransaction();
        Log.d(LOG_TAG, "id of managed realm set is " + set.getRealmId() + " and workout id is " + set.getWorkout().getRealmId());
        //Log.d(LOG_TAG, "id of managed realm object is " + realmSet.getRealmId());
        mRealm.close();
...

// Where I'm trying to use this count in UI
...
workoutNameTextView = (TextView) cardView.findViewById(R.id.workout_card_workout_name);
        workoutNameTextView.setText(workout.getName());
        setCountTextView = (TextView) cardView.findViewById(R.id.workout_card_set_count);
        //TODO: Abide the rules and don't use string concatenation here
        QUERY HERE --> setCountTextView.setText(String.valueOf(workout.getSets().size()) + " sets");
        Log.d(LOG_TAG, "Workout has " + String.valueOf(workout.getSets() + " sets"));
        exerciseCountTextView = (TextView) cardView.findViewById(R.id.workout_card_exercise_count);
        exerciseCountTextView.setText(String.valueOf(workout.getExercises().size()) + " exercises");
...

```

#### Version of Realm and tooling
Realm version(s): 2.0.0

**Comment by nhachicha** [comment]
Hi @jraczak 
is `onSetsSaved` called from another thread?

is the `workout` passed to `onSetsSaved` a managed or unmanaged ?
I don't see in `onSetsSaved` where you associate the newly created `set` with the `workout`? that explains why `workout.getSets().size()` is still empty.

**Comment by Zhuinden** [comment]
You never called `workout.getSets().add(set);`

**Comment by jraczak** [comment]
@nhachicha Thank you for the quick response! Do I need to set the relationship on _both_ objects? I'm newer to mobile and Realm and have more experience in web. I assumed that by setting the relationship on the set that the chain of relationship would be properly instantiated. But now that I think about it, that is probably more Rails' blackbox magic doing things I didn't realize in the background. 😄 I'll try explicitly setting the `set` on the workout now.

**Comment by jraczak** [comment]
@Zhuinden Should I need the `getSets()` part of that query? Based on my `addSet` method, I should be able to call it directly, no? 

```java
public void addSet(Set set) {
        Realm realm = Realm.getDefaultInstance();
        realm.beginTransaction();
        this.sets.add(set);
        realm.commitTransaction();
        realm.close();
    }
```

**Comment by Zhuinden** [comment]
uh.

It should just be this.

``` java
// Activity where set is created and relationship to workout is linked
public void onSetsSaved(Exercise exercise, Workout workout, int reps, float weight) {
        Log.d(LOG_TAG, "onSetsSaved called");

        mRealm.beginTransaction();
        Set set = mRealm.createObject(Set.class, Set.getNewAutoIncrementId());
        set.setWorkout(workout);
        set.setExercise(exercise);
        set.setDate(new Date());
        set.setReps(reps);
        set.setWeight(weight);
        //set.setRealmId(Set.getNewAutoIncrementId());
        workout.getSets().add(set);  ///// <------ added missing method call
        mRealm.commitTransaction();
        Log.d(LOG_TAG, "id of managed realm set is " + set.getRealmId() + " and workout id is " + set.getWorkout().getRealmId());
        //Log.d(LOG_TAG, "id of managed realm object is " + realmSet.getRealmId());
        mRealm.close();
```

**Comment by jraczak** [comment]
@Zhuinden I'd like to learn where I am doing things wrong. Can you explain why you include `getSets()` in the method chain? It didn't seem to me that I should need `getSets()` in between and it does seem to be working without it. But if I'm doing something against convention, I'd like to learn.

**Comment by Zhuinden** [comment]
@jraczak because you have to set up relationships between elements if you want to have relationships between them.

**Comment by jraczak** [comment]
@Zhuinden Sorry for the long delay. I understand the need for the relationships. I'm asking about your use of `.getSets` specifically in performing the assignment. What is the difference between

`workout.getSets().addSet(set);`
and
`workout.addSet(set);`

To reiterate, maybe the difference is nothing but I'm trying to make sure I'm not overlooking something or doing something against convention. I'm currently setting the workout with `workout.addSet()` and it seems to be working as expected. Thanks for all your time in explaining.

**Comment by Zhuinden** [comment]
Well I definitely don't like that every "add" would use a new transaction.

**Comment by jraczak** [comment]
@Zhuinden How does adding `getSets()` to the chain address that?

**Comment by Zhuinden** [comment]
By not creating a new transaction for adding the item to the set, of course

Have you actually tried the code I provided? I'm curious if it fixes the issue

**Comment by kneth** [comment]
@jraczak `getSets().add()` will add to am existing list while `setSets()` will assign a list to field. Please take a look at https://realm.io/docs/java/latest/#many-to-many

**Comment by kneth** [comment]
@jraczak I am closing the issue. Don't hesitate to reopen or create new issue if you have further questions.
