### ISSUE TITLE
No static method init

### ISSUE THREAD

**Issue by iotechFabioGM** [realm/realm-java#3969]
> Hi,

#### Goal

> I am trying to insert a Realm database to my project

#### Expected Results

> Execute the app in a cell phone to start the tests

#### Actual Results
> **Bug**: I am trying to build my project, but when I run the app in the phone, it appears:

```java
[...]
E/AndroidRuntime: FATAL EXCEPTION: main
                  Process:<myProject>, PID: 4097
                  java.lang.NoSuchMethodError: No static method init(Landroid/content/Context;)V in class Lio/realm/Realm; or its super classes (declaration of 'io.realm.Realm' appears in /data/data/myProject/files/instant-run/dex/slice-realm-android-0.74.0_2d8f06e00866d1b7ed76e286c5d5a9d8da8b13b0-classes.dex)
                      at myProject.Service.Realm.RealmConfig.onCreate(RealmConfig.java:13)
                      at com.android.tools.fd.runtime.BootstrapApplication.onCreate(BootstrapApplication.java:370)
[...]
```

#### Steps & Code to Reproduce

> My app isn`t running. The app is closed forcedly before appears.

#### Code Sample

> My RealmConfig class is just below:
```java
import android.app.Application;
import android.util.Log;
import io.realm.Realm;

public class RealmConfig extends Application {

    @Override
    public void onCreate() {
        // Initializing Realm
        Realm.init(this);   //<-- This is the row 13
        Log.d("Application", "Realm initialized");
    }
}
```
> **AndroidManifest**:
```java
[...]
<application
        android:name=".Service.Realm.RealmConfig"
[...]
```

#### Version of Realm and tooling
2.2.1

Realm sync feature enabled: no

Android Studio version: 2.2.3

Which Android version: 5.0.2 and device: Samsung SM-G360BT

**Comment by Zhuinden** [comment]
Some kind of dependency in your application is pulling in Realm 0.74.0.

Try disabling instant run, or doing a clean+rebuild, or checking if you have some outdated RealmSearchView external dependency among the compile dependencies somewhere.

**Comment by kneth** [comment]
@iotechFabioGM Did you have any success when clean+rebuild and disabling instant run? You could also try to do a `./gradlew assemble --refresh-dependencies` so ensure that you get a newer version of Realm.

**Comment by iotechFabioGM** [comment]
Hi Mrs...

Like Zhuinden said... There really was a Realm 0.74.0 dependency

On my app gradle  there was:

```
java
[...]
dependencies{
(...)
    //Realm
    compile 'io.realm:realm-android:0.74.0'
(...)
}
```

Thanks guys... Now I have another problem!

**Comment by kneth** [comment]
@iotechFabioGM I close this issue. If you have any Realm related questions, either ask at StackOverflow or create a Github issue.
