### ISSUE TITLE
Help resolve StrictMode policy violation

### ISSUE THREAD

**Issue by aftabsikander** [realm/realm-java#3976]
#### Goal
I would like to resolve this Strick mode policy violation issue caused by Realm.
#### Expected Results
No StrictMode policy violation when calling Realm init
#### Actual Results
I have been seen this log varies times on multiple devices. 

```
01-03 17:29:33.184 30198-30198/com.example.realmSample D/StrictMode: StrictMode policy violation; ~duration=178 ms: android.os.StrictMode$StrictModeDiskReadViolation: policy=65543 violation=2
at android.os.StrictMode$AndroidBlockGuardPolicy.onReadFromDisk(StrictMode.java:1263)
at libcore.io.BlockGuardOs.open(BlockGuardOs.java:182)
at libcore.io.IoUtils.canOpenReadOnly(IoUtils.java:163)
at dalvik.system.DexPathList$Element.findNativeLibrary(DexPathList.java:485)
at dalvik.system.DexPathList.findLibrary(DexPathList.java:400)
at dalvik.system.BaseDexClassLoader.findLibrary(BaseDexClassLoader.java:77)
at java.lang.Runtime.loadLibrary(Runtime.java:361)
at java.lang.System.loadLibrary(System.java:1076)
at com.getkeepsafe.relinker.SystemLibraryLoader.loadLibrary(SystemLibraryLoader.java:24)
at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(ReLinkerInstance.java:163)
at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(ReLinkerInstance.java:136)
at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:70)
at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:57)
at io.realm.internal.RealmCore.loadLibrary(RealmCore.java:61)
at io.realm.Realm.init(Realm.java:187)
at com.example.realmSample.application.RealmApplication.setupRealmConfiguration(RealmApplication.java:49)
at com.example.realmSample.application.RealmApplication.initRealmConfiguration(RealmApplication.java:64)
at com.example.realmSample.application.RealmApplication.onCreate(RealmApplication.java:30)
at com.android.tools.fd.runtime.BootstrapApplication.onCreate(BootstrapApplication.java:370)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1013)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:4707)
at android.app.ActivityThread.-wrap1(ActivityThread.java)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1405)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:5417)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:616)
```

#### Code Sample
Following is the complete code where this StrickMode violation is coming
```java

public class RealmApplication extends Application {
    @Override
    public void onCreate() {
        super.onCreate();
        turnOnStrictMode();
        //LeakCanary.install(this);
        //setupRealmConfiguration();
        initRealmConfiguration(this);
        setupFabricForCrashlytics();
    }

    /***
     * Setup fabric and crashlytics
     */
    protected void setupFabricForCrashlytics() {
        // Set up Crashlytics, disabled for debug builds
        Crashlytics crashlyticsKit = new Crashlytics.Builder()
                .core(new CrashlyticsCore.Builder().disabled(BuildConfig.DEBUG).build())
                .build();

        // Initialize Fabric with the debug-disabled Crashlytics.
        Fabric.with(this, crashlyticsKit);
    }

    protected void setupRealmConfiguration() {
        // Initialize Realm. Should only be done once when the application starts.
        Realm.init(this);
        RealmConfiguration realmConfiguration = new RealmConfiguration.Builder()
                .deleteRealmIfMigrationNeeded()
                .name(ApplicationConstant.DATABASE_NAME)
                .build();
        Realm.setDefaultConfiguration(realmConfiguration);
    }

    public void initRealmConfiguration(Context context) {
        ActivityManager activityManager =
                (ActivityManager) context.getSystemService(Context.ACTIVITY_SERVICE);
        for (ActivityManager.RunningAppProcessInfo ProcessInfo : activityManager.getRunningAppProcesses()) {
            if (Process.myPid() == ProcessInfo.pid) {
                if (TextUtils.equals(ProcessInfo.processName, BuildConfig.APPLICATION_ID)) {
                    // The Initiate Process of default on the App only
                    setupRealmConfiguration();
                }
                break;
            }
        }
    }

    private void turnOnStrictMode() {
        if (BuildConfig.DEBUG) {
            StrictMode.setThreadPolicy(new StrictMode.ThreadPolicy.Builder()
                    .detectDiskReads()
                    .detectDiskWrites()
                    .detectNetwork()   // or .detectAll() for all detectable problems
                    .penaltyLog()
                    .build());
            StrictMode.setVmPolicy(new StrictMode.VmPolicy.Builder()
                    .detectLeakedSqlLiteObjects()
                    .detectLeakedClosableObjects()
                    .penaltyLog()
                    .detectActivityLeaks()
                    .build());
        }
    }


}

```

#### Version of Realm and tooling
Realm version(s):  
`io.realm:realm-gradle-plugin:2.2.1`

Realm sync feature enabled: 
`No it is disabled`

Android Studio version: 
```
Android Studio 2.2.3
Build #AI-145.3537739, built on December 2, 2016
JRE: 1.8.0_76-release-b03 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
```
Which Android version and device: ?
```
Model no: Nexus 5
OS version: 6.0.1
android studio: 2.2.3
```

**Comment by Zhuinden** [comment]
.detectDiskReads()

and

```
at java.lang.Runtime.loadLibrary(Runtime.java:361)
at java.lang.System.loadLibrary(System.java:1076)
at com.getkeepsafe.relinker.ReLinker.loadLibrary(ReLinker.java:57)
at io.realm.internal.RealmCore.loadLibrary(RealmCore.java:61)
at io.realm.Realm.init(Realm.java:187)
```

Indicates that the problem is that you detect all `diskRead` in your strict mode, and don't allow Realm to load its `.so` files so that Realm's native libraries would be available in your code.

**Comment by cmelchior** [comment]
Hi @aftabsikander That is not really possible. We are using a library called Relinker due to numerous bugs on Android with regard to loading native code, and it is that library that is causing the error you are seeing. Unfortunately we need to load the native code to work at all, so there isn't much we can do about it.

The only work around would be to call `Realm.init()` on a background thread, which is possible, but will introduce other headaches as you now need to synchronize the bg thread and the UI thread.

**Comment by beeender** [comment]
`io.realm.Realm.init()` needs to call Relinker then load the native `so` files from disk. That is causing strict mode violation. But there is quite little we can do from Realm side, the `Realm.init()` needs to be called before any other Realm API.

What you can do:
- Turn on the strict mode after `Realm.init()`
- Or call `Realm.init()` from another thread, block your UI interactions with a spinner of whatever until the `Realm.init()` returns. (I assume you need Realm APIs for UI thread)

**Comment by aftabsikander** [comment]
@Zhuinden @cmelchior Thanks for the explaining the root cause of this, 

> The only work around would be to call Realm.init() on a background thread, which is possible, but will introduce other headaches as you now need to synchronize the bg thread and the UI thread.
>
This would be a hick-tic  workaround. As you said their is nothing what can be done. 

> call Realm.init() from another thread, block your UI interactions with a spinner of whatever until the Realm.init() returns. (I assume you need Realm APIs for UI thread)
>
@beeender  This would not solve the big picture because as the database size increase `Realm.init()` will take more time hence more users will face app freeze when loading database and StrictMode policy violation will still occur. 

What I am going to do is turn on the strict mode after `Realm.init()`

**Comment by dalinaum** [comment]
I think its consuming time doesn't depend on the database size. `Realm.init()` would not take more time. How about the following code?

```
    public void onCreate() {
        super.onCreate();
        //LeakCanary.install(this);
        //setupRealmConfiguration();
        initRealmConfiguration(this);
        turnOnStrictMode();
        setupFabricForCrashlytics();
    }
```

**Comment by beeender** [comment]
> this would not solve the big picture because as the database size increase Realm.init() will take more time

No, `Realm.init()` takes constant time and it doesn't matter how big the database size is. Its major job it to load the native lib.

**Comment by aftabsikander** [comment]
@dalinaum @beeender I have updated the code, If I receive any other Strick Mode related Issues will report again, I believe during migration writing process will take time and Strick Mode will occur again

**Comment by Zhuinden** [comment]
@aftabsikander yes, you are correct. Migration also does disk writes on first `Realm.getDefaultInstance()` call

**Comment by aftabsikander** [comment]
@Zhuinden I found a similar ticket [#2299](https://github.com/realm/realm-java/issues/2299), [#2935 ](https://github.com/realm/realm-java/issues/2935 )regarding migration on background thread, Once this get resolved then I believe disk write violation would not occur.

**Comment by cmelchior** [comment]
@aftabsikander Not really. It is `Realm.init()` causing the violation. The two issues you reference are more about opening the Realm file itself.

**Comment by aftabsikander** [comment]
@cmelchior I am talking about disk writing, I know we can't do anything about native .so being read and causing violation. What I am talking about is that same thing can be happened when doing migration if it takes to much time hence causing violation again, correct me If I am wrong.
