### ISSUE TITLE
many to many Query

### ISSUE THREAD

**Issue by osama-raddad** [realm/realm-java#3986]
dear realm team, 
first of thanks for the great library  , secondly i have question   i have this data structure :  

```java
public class Country extends RealmObject {
    @PrimaryKey
	public String key;
    public RealmList<City> cities;
    ...
}
```
```java
public class City extends RealmObject {
	public String key;
    public RealmList<Area> areas;
    ...
}
```
```java
public class Area extends RealmObject {
    public String name;
    public String key;
    ...
}
```

how can i get just the Area object from specific City from specific Country

i have tried this query :

```java
   realm.where(Country.class)
      .equalTo("cities.areas.key","KEY")
      .findAll();
```

and it returns a list of Countries and tried this query :
```java
   realm.where(Country.class)
      .equalTo("cities.areas.key","KEY")
      .findFirst();
```
and it and it returns a object of Country and inside a full list of Cities and areas and i just need a specific area by key from specific City by key from specific Country by key.

**Comment by Zhuinden** [comment]
make Area point to City, and City point to Country; then you can do a query for Area which can obtain the County via `area.getCity().getCountry()`

**Comment by kneth** [comment]
@osama-raddad Querying many-to-many relations is a bit tricky. Your query will find the first `Country` object with at least one area with key `KEY`. Please take a look at https://realm.io/docs/java/latest/#link-queries

What @Zhuinden is suggesting is that you set up back links manually. Eventually we wish to support that (see #607).
