### ISSUE TITLE
Add generic type to RealmObject

### ISSUE THREAD

**Issue by IlyaGulya** [realm/realm-java#3998]
#### Goal

Use `RealmObject.addChangeListener(RealmChangeListener<E> listener)` or same typed methods and provide `RealmChangeListener` as lambda without necessity to specify type in lambda.

#### Expected Results

Simply use lambda like this:
```java
Folder.getById(1)
      .addChangeListener(folder -> Timber.e(folder.getName()));
```

#### Actual Results

Instead, i need to specify type for lambda argument like this:
```java
Folder.getById(1)
      .addChangeListener(Folder folder -> Timber.e(folder.getName()));
```
It looks dirty.

The way we can fix this is to provide type argument to `RealmObject` like this:
```java
public class Folder extends RealmObject<Folder>
```

Main benefit of such way to specify type is to move dirt from our code to model class declaration.

This issue is based on #3908

#### Version of Realm and tooling
Realm version(s): 2.2.1
Android Studio version: 2.2.3

**Comment by Zhuinden** [comment]
does that **actually** fix the `addChangeListener` call?

Also, now that I think about it, such chaining will make sure you cannot keep a field reference to your RealmObject, which means the GC will eat it and the change listener will stop being called.

**Comment by IlyaGulya** [comment]
@Zhuinden  to fix the issue of course  we need to charge method signature to use class-level generic type, not local. After that return type will be known at the compilation time. Also, I don't understand the problem with GC. Why I would not be able to keep a field reference?

**Comment by Zhuinden** [comment]
because `addChangeListener` returns void

**Comment by IlyaGulya** [comment]
If you look on `public static <E extends RealmModel> void addChangeListener` method definition, you will see, that reference to `RealmObject` to which you adding change listener keeped internally in realm (at BaseRealm.handlerController).
However, it does not actually matter for discussion about adding generic type to `RealmObject`

**Comment by kneth** [comment]
I must admit that `public class Folder extends RealmObject<Folder>` is a heavy burden to put on all developers who are not implementing their own change listeners.

**Comment by IlyaGulya** [comment]
They can drop out generic type and everything will be okay. In this case they will have the same behaviour as now.

**Comment by Zhuinden** [comment]
Then they'll be getting a lint error which is worse

**Comment by kneth** [comment]
Especially that everybody who don't need this will get linting errors :-(

**Comment by kneth** [comment]
I am closing this issue. It is unlike we wish to complicate our API for most users.
