### ISSUE TITLE
Sort realm data/ Add data to the beginning

### ISSUE THREAD

**Issue by DanteAndroid** [realm/realm-java#4000]
#### Goal 
Add new data at the beginning of realm database (so that the new data would be shown on the 1st page when user refreshes).
#### Expected Results
My `Image` data would be sorted by ID.

#### Actual Results
My data are sorted by ID, but IDs are all increased by a certain number.

#### Steps & Code to Reproduce 
Note: I only test **anime** type.
Before:
![before](https://cloud.githubusercontent.com/assets/10005563/21738863/300a8268-d4c8-11e6-8d31-d910f20d0032.png)

After:
![after](https://cloud.githubusercontent.com/assets/10005563/21738864/31f625fa-d4c8-11e6-80d0-aef667844ce0.png)

log:
![log](https://cloud.githubusercontent.com/assets/10005563/21738963/ad65f32c-d4c9-11e6-884b-46ea30be23c2.png)

#### Code Sample
My sort code is from Stackoverflow, if it's not best practice, please guide me.
 [Check on github](https://github.com/DanteAndroid/beauty/blob/master/app/src/main/java/com/dante/girls/picture/CustomPictureFragment.java#L218)
 

#### Version of Realm and tooling
Realm version(s):  classpath "io.realm:realm-gradle-plugin:2.2.1"

Realm sync feature enabled: don't know

Android Studio version: 2.2.3

Which Android version and device: N

**Comment by kneth** [comment]
From your code, it looks like you discard the new `RealmResults` when sorting. `RealmResults.sort()` returns a *sorted* `RealmResults`. We change from in-place sort in version 0.89.

**Comment by DanteAndroid** [comment]
1. Is Realm auto-updated，y should I use the returned data then? 
1. and since is updated, I found in "onComplete" the data size does not change until I query again, why, is it I'd better use observable? 
1. Whats the difference between autoupdate n observable)

These really confused me… I can't give up Realm for its easy API. So can you guide me a little bit, whtas the best practice to deal with Realm to `load data, load more data(new dada added to the bottom of the list) to recyclerview and notify, fresh dada(new dada added to the 0 position) and notify`. Love with you!

**Comment by Zhuinden** [comment]
http://stackoverflow.com/a/38873498/2413303

**Comment by kneth** [comment]
I imaging that https://github.com/DanteAndroid/beauty/blob/master/app/src/main/java/com/dante/girls/picture/CustomPictureFragment.java#L233 should be `images = images.sort()`.

**Comment by DanteAndroid** [comment]
@kneth well that doesn't matter now, could you give me a little tip about:

1. Is Realm auto-updated，y should I use the returned data then?
2. and since is updated, I found in "onComplete" the data size does not change until I query again, why, is it I'd better use observable?
3. Whats the difference between autoupdate n observable)

These really confused me… I can't give up Realm for its easy API. So can you guide me a little bit, whtas the best practice to deal with Realm to load data, load more data(new dada added to the bottom of the list) to recyclerview and notify, fresh dada(new dada added to the 0 position) and notify.

**Comment by Zhuinden** [comment]
@DanteAndroid Realm retains the sort after an auto-update only if you use `findAllSorted()` instead of `findAll()`.

**Comment by DanteAndroid** [comment]
@Zhuinden you sure? How can I notice that?

**Comment by kneth** [comment]
If you change/add/delete an object, the query is rerun and the  `RealmResults` is updated. If a sort order was applied previously, the `RealmResults` will stay sorted. If you observe some deviation from that, we will be happy if you can condense your code to a simple unit test which reproduces the issue.

Btw, questions about Realm and other Android libraries are much better asked at StackOverflow which has a much larger community.
