### ISSUE TITLE
containsAll always returns false

### ISSUE THREAD

**Issue by DanteAndroid** [realm/realm-java#4001]
My app fetch data and save in realm, but when I pull to refresh, I get the same list data, then I use filter to get no duplicate data. But the following code always returns false. 
 ```
    public static boolean hasImages(Realm realm, Collection<Image> list, String imageType) {
        boolean resut = realm.where(Image.class).equalTo(Constants.TYPE, imageType).findAll().containsAll(list);
        Log.d(TAG, "hasImages : " + resut);
        return resut;
    }
```
I'm sure the list data is the same as I saved before. What should I check? Thankx

**Comment by kneth** [comment]
@DanteAndroid Can you share how you store the data in Realm? Is the code running on a Looper thread? Instead of `containsAll()`, can you do `size() > 0` instead? If `list` is not a collection of managed objects, it will return false.

**Comment by DanteAndroid** [comment]
[This is how I store](https://github.com/DanteAndroid/beauty/blob/master/app/src/main/java/com/dante/girls/picture/CustomPictureFragment.java#L215), and [this is how I use `contains`](https://github.com/DanteAndroid/beauty/blob/master/app/src/main/java/com/dante/girls/picture/CustomPictureFragment.java#L152)

**Comment by kneth** [comment]
@DanteAndroid I don't see where `contains` is used in the link above. Please try to use `size()` instead of `containsAll()`.

**Comment by DanteAndroid** [comment]
Well, I just updated the code. I give up using [contains](https://github.com/DanteAndroid/beauty/blob/master/app/src/main/java/com/dante/girls/model/DataBase.java#L56), with [query statement](https://github.com/DanteAndroid/beauty/blob/master/app/src/main/java/com/dante/girls/model/DataBase.java#L51) instead.

**Comment by kneth** [comment]
Makes sense when `list` is a collection of unmanaged objects.

**Comment by DanteAndroid** [comment]
@kneth What are unmanaged objects like? Sorry to bother!

**Comment by Zhuinden** [comment]
Objects not associated with a Realm instance.

**Comment by DanteAndroid** [comment]
@Zhuinden  I already save those objects in Realm, aren't they managed then?

**Comment by cmelchior** [comment]
Yes, if objects are persisted in Realm they are managed. These are not:

```
public class Dog extends RealmObject {
}

new Dog(); // unmanaged
Dog unmanagedDog = realm.copyFromRealm(realm.where(Dog.class).findFirst()); // Convert managed to unmanaged
```

```

**Comment by DanteAndroid** [comment]
@cmelchior I get it. Then my problem is because they are unmanaged. (They are list object I fetch from net, although I saved them in Realm, but not the same object)
