### ISSUE TITLE
Realm.init() cannot resolve method

### ISSUE THREAD

**Issue by lawloretienne** [realm/realm-java#4014]
I tried to set up realm similarly to how it is set up here
https://github.com/realm/realm-java/blob/master/examples/introExample/src/main/java/io/realm/examples/intro/MyApplication.java

but it cannot resolve the method `init()`.

I have v2.2.2 of the realm-gradle-plugin set up.  What could be causing this issue?

**Comment by beeender** [comment]
Do you have step 1 and step 2 described here https://realm.io/docs/java/latest/#installation?

**Comment by lawloretienne** [comment]
Okay so my issue was i forgot to remove the old dependency 
`compile 'io.realm:realm-android:0.84.2'`.  I also did a project clean and now the method is resolved.  Thanks for the quick response.
