### ISSUE TITLE
Typo in Realm Android recycler view tutorial doc

### ISSUE THREAD

**Issue by adellhk** [realm/realm-java#4020]
Hey, I'm not sure if this is the most efficient way to contact, but I wasn't sure how else to. There's a simple typo in the Realm [Android recycler view tutorial](https://realm.io/news/android-recycler-view/) which could be confusing. The line `compile 'com.github.thorbenprimke:realm-recycler-view:0.9.4'` should be `compile 'com.github.thorbenprimke:realm-recyclerview:0.9.25'`*. Cheers!

\* *0.9.25, not 0.9.25*:
In addition to the hyphen typo I suspect that using realm-recyclerview:0.9.4 was giving me a Gradle error (DuplicateFileException), which went away using the [latest current release](https://github.com/thorbenprimke/realm-recyclerview/releases) 0.9.25.

**Comment by adellhk** [comment]
Actually potentially using realm-recyclerview:0.9.4 was giving me a Gradle error (DuplicateFileException), which went away using the [latest current release](https://github.com/thorbenprimke/realm-recyclerview/releases) 0.9.25 anyway.

So `'com.github.thorbenprimke:realm-recyclerview:0.9.4'`

**Comment by kneth** [comment]
@adellhk Thanks!!

**Comment by beeender** [comment]
Fixed on contentful. should be available in a few minutes.
