### ISSUE TITLE
Realm Crash with too many files open

### ISSUE THREAD

**Issue by Sutirth** [realm/realm-java#4024]
Bug: Realm crash with too many files open

Goal: Values inserting into tables in proper desired format

Expected Result: To get respective tables filled

Actual Result: Unable to reproduce crash at my side but fabric reports some devices facing problems.

Devices crash occurring: Coolpad, Moto g(4), Letv Operating system= 5.1, 6.0, 6.0.1

Below is the piece of code where the crashlytics reports the error. P.S This is inside an Intent Service.

    for (Field field : dp.getDataType().getFields()) {
    
                        realm = Realm.getDefaultInstance();
    
    
                        FitnessDB fitnessDBRealmResults = realm.where(FitnessDB.class)
                                .equalTo(WorkoutCashConstants.COLUMN_ACTIVITY_START_TIME, insertStartTime)
                                .equalTo(WorkoutCashConstants.COLUMN_ACTIVITY_END_TIME, insertEndTime)
                                .findFirst();
    
    
    
                        Log.i(TAG, "Step Count value:   " + dp.getValue(field).toString());
    
                        if (fitnessDBRealmResults == null) {
                            realm.beginTransaction();
                            FitnessDB fitnessDB = new FitnessDB();
                            fitnessDB.setActivityStartTime(insertStartTime);
                            fitnessDB.setActivityEndTime(insertEndTime);
                            fitnessDB.setCurrentMonth(monthText);
                            fitnessDB.setStepCount(dp.getValue(field).asInt());
                            fitnessDB.setIsSynced(0);
                            realm.copyToRealmOrUpdate(fitnessDB);
                            realm.commitTransaction();
                            realm.close();
                        } else {
                            
                            realm.beginTransaction();
                            fitnessDBRealmResults.setStepCount(dp.getValue(field).asInt());
                            fitnessDBRealmResults.setIsSynced(0);
                            realm.commitTransaction();
                            realm.close();
                     
                        }
    
    
                    }

Line no. 393: realm = Realm.getDefaultInstance();

<img width="1150" alt="screenshot 2017-01-12 13 06 47" src="https://cloud.githubusercontent.com/assets/3212997/21881293/b3f63374-d8c9-11e6-9ee6-1a3ce7d6f6d0.png">

Realm version: 2.1.1

**Comment by beeender** [comment]
It could be caused by #4002 But it could also be caused by some `File` is opened from your application and never get closed. Did you open any file in your app?

**Comment by Sutirth** [comment]
@beeender  nope not using any file in the entire application

**Comment by beeender** [comment]
@Sutirth OK. I will just dup this issue to #4002 and start fixing it. You can follow the prgress on that one. thanks for the feedback!

**Comment by Sutirth** [comment]
@beeender  Thank you for feedback. Will look out issue over !!

**Comment by Zhuinden** [comment]
@Sutirth you could probably fix this error by moving the `begin/commit` outside of the for loop.

**Comment by Sutirth** [comment]
@Zhuinden Yep I tried doing that as well and had sent to 2 separate build but crashlytics shows be same error
