### ISSUE TITLE
I am doing a realm sort and I want all non alphabetic result to appear at the bottom of the list and not on top, is there a way to do that? To clarify more my search result should be in order "ABCDEFGHIJ......1234ect"

### ISSUE THREAD

**Issue by Poojagupta0686** [realm/realm-java#4034]
> We LOVE to help with any issues or bug you have!

> **Questions**: If you have questions about how to use Realm, please ask on [SO](http://stackoverflow.com/questions/ask?tags=realm) - we monitor the Realm tag.

> **Feature Request**: Just fill in the first two sections below.

> **Bugs**: To help you as fast as possible with an issue or bug please describe your issue and the steps you have taken to reproduce it in as many details as possible.
>
> Thanks for helping us help you :-)
>
> Remove this and above before submitting.

#### Goal

> What do you want to achieve?

#### Expected Results

> ?

#### Actual Results

>  E.g. full stack trace with exception

#### Steps & Code to Reproduce

> Describe your current debugging efforts.

#### Code Sample

```java

> Your code here. Bigger samples should ideally be as separate Android Studio project, 
> in gists/repositories or privately at help@realm.io)

```

#### Version of Realm and tooling
Realm version(s): ?

Realm sync feature enabled: yes/no

Android Studio version: ?

Which Android version and device: ?

**Comment by beeender** [comment]
I am sorry but it cannot be achieved by calling `sort()` directly, see this issue https://github.com/realm/realm-java/issues/2313

However, I believe there is workaround for it, and you may get a answer in short time if you ask it on [SO](http://stackoverflow.com/questions/ask?tags=realm) - we monitor the Realm tag.
