### ISSUE TITLE
RealmVersionChecker.java uses cleartext HTTP

### ISSUE THREAD

**Issue by jamie-beardedhen** [realm/realm-java#4043]
#### Goal

> Realm should perform network requests over a secure channel by default.

#### Expected Results

> All requests use HTTPS.

#### Actual Results

>  RealmVersionChecker.java calls two endpoints over HTTP.

#### Steps & Code to Reproduce

> Launch any app with Realm initialised and view Logcat.

#### Code Sample
See [RealmVersionChecker.java](https://github.com/realm/realm-java/blob/3cbc084b3c888e9555629638e31adebbfd369c8f/realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmVersionChecker.java) at line 26 and 31.

**Comment by kneth** [comment]
@jamie-beardedhen Thanks for the suggestion.
