### ISSUE TITLE
RealmResults<SomeClass> and  Observable.concat()

### ISSUE THREAD

**Issue by itslonua** [realm/realm-java#4048]
> I have trouble with concat two RealmResults, can i get result as RealmResults<SomeClass> or only List<SomeClass>?

Observable<RealmResults<SomeClass>> asyncObservable1 = realm.where(SomeClass.class) .findAllSortedAsync("field") .asObservable();

Observable<RealmResults<SomeClass>> asyncObservable1 = realm.where(SomeClass.class) .beginsWith("field", filterString).findAllSortedAsync("field") .asObservable();

Observable.concat(asyncObservable1, asyncObservable2).startWith(asyncObservable1). .filter(RealmResults::isLoaded)
.subscribe(this::filterObserver);

void filterObserver(RealmResults<SomeClass> words) {
            updateRealmResults(words);
}

I need filter Realm database filter by string with formatting:

Needle?
?Needle?
?Needle

**Comment by Zhuinden** [comment]
``` java
    RealmResults<Cat> equalTo;
    RealmResults<Cat> beginsWith;

    @Override
    public void onViewRestored(boolean forcedWithBundler) {
        compositeSubscription = new CompositeSubscription();
        equalTo = realm.where(Cat.class).equalTo("field", filterString).findAllSorted("field");
        beginsWith = realm.where(Cat.class).beginsWith("field", filterString).findAllSorted("field");
        compositeSubscription.add(realm.asObservable()
                .switchMap(new Func1<Realm, Observable<Cat>>() {
                    @Override
                    public Observable<Cat> call(Realm realm) {
                        return Observable.concat(Observable.from(equalTo), Observable.from(beginsWith));
                    }
                })
                .toList()
                .subscribe(cats -> {
                    // update adapter with List<Cat>
                }));
```

Maybe someone smarter can make it work with the `Async` operators and `filter` too.

**Comment by kneth** [comment]
Can the `like` predicate (see #3752) be of any use here?

**Comment by itslonua** [comment]
Yes, (like) predicate is best for my task, buy i used Realm version below 2.0

**Comment by kneth** [comment]
You cannot concatenate `RealmResults` but doing a `Or` of two queries is supported.

**Comment by Zhuinden** [comment]
....oh wow, why didn't I think of that >.<
