### ISSUE TITLE
NDK r10e no longer on homebrew

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#4057]
NDK r10e was removed from Homebrew: https://github.com/Homebrew/homebrew-versions/pull/1444

We should update the README to indicate how else to get that version (or upgrade to a later version ourselves)

**Comment by beeender** [comment]
upgrade to latest NDK!
upgrade to latest NDK!
upgrade to latest NDK!

**Comment by cmelchior** [comment]
If I remember correctly we disabled LTO support when we added CMake, and apparently that will be back in r14 (which is the next release), but I don't know if anything prevents us from upgrading to r13b, @kneth?

**Comment by Zhuinden** [comment]
Doesn't this depend on Core https://github.com/realm/realm-core/pull/1883 ?

**Comment by bmeike** [comment]
Can we separate this into two issues: fix the doc for the immediate release; update to latest NDK.  If that's ok with folks, I will open a separate issue to update NDK, assign this ticket to myself and fix the doc.

**Comment by cmelchior** [comment]
@bmeike Sounds good to me 👍

**Comment by bmeike** [comment]
Forked https://github.com/realm/realm-java/issues/4060 to track updating the NDK dependency.  This now tracks updating the documentation.

**Comment by kneth** [comment]
@cmelchior The change to cmake in Realm Core is holding us back.
