### ISSUE TITLE
Update to use the most recent NDK

### ISSUE THREAD

**Issue by bmeike** [realm/realm-java#4060]
We should update our dependency to be r13 or r14.

Forked from https://github.com/realm/realm-java/issues/4057.

From that issue:

1) Doesn't this depend on Core realm/realm-core#1883 ?

2) If I remember correctly we disabled LTO support when we added CMake, and apparently that will be back in r14 (which is the next release), but I don't know if anything prevents us from upgrading to r13b, @kneth?

**Comment by kneth** [comment]
I guess it is related to #3506. Yes, we need Realm Core to switch to CMake.

**Comment by cmelchior** [comment]
Ah yeah. Already tracking it as part of #3506. Closing this as an duplicate then
