### ISSUE TITLE
SyncSession needs to handle SESSION_DISABLED

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#4062]
Sync introduced a new error code (213 - SESSION_DISABLED). We need to handle it in Java until #3742 is completed.

**Comment by beeender** [comment]
Do we need to do anything with it? https://github.com/realm/realm-object-store/blob/master/src/sync/sync_session.cpp#L330 Object Store just ignores it.

**Comment by cmelchior** [comment]
I didn't look into the specifics, but yes in that case it looks like we should just ignore it. Right now it will be reported to the error handler, and judging from the OS comment we should just swallow it. I'm guessing that the OS will automatically restart the underlying Core session, so we should be sure we do the same.

**Comment by kneth** [comment]
I tend to agree with @beeender. We don't do anything with other error codes (for example `ProtocolError::session_closed`).
