### ISSUE TITLE
Like predicate not available (Android / 2.2.2)

### ISSUE THREAD

**Issue by sebastianmarschall** [realm/realm-java#4063]
I'm using the realm-gradle-plugin:2.2.2 in my android project. According to the Changelog the like predicate should be available since 2.2.2.
Its not available though, am I missing something?

**Comment by cmelchior** [comment]
Yes, that item got the wrong location in the changelog. It should be under 2.3, which is currently only available as a SNAPSHOT. Sorry about that. We will get that fixed
