### ISSUE TITLE
Build realm-java under windows

### ISSUE THREAD

**Issue by Drjacky** [realm/realm-java#4070]
I'm going to build realm. So run this command in command prompt:
```Javascript
gradlew assemble
```
But I got this error:
```Javascript
* What went wrong:
Execution failed for task ':realm-library:downloadCore'.
> Java heap space
```

Windows 7 64-bit Ultimate
Gradle 3.1
cygwin 2.5.2 64bit
Installed JDKs and JREs:
64bit:
```Java
jdk1.8.0_121
jre1.8.0_121
```
32bit:
```Java
jdk1.8.0_121
jre1.8.0_121
jdk1.7.0_80
jre7
jdk1.6.0_45
jre6
```
Used java version in Environment Variables: 1.8.0_121

![realmbuilderroruntitled](https://cloud.githubusercontent.com/assets/2296754/22098839/cc273500-de3d-11e6-9010-1f137c9262b0.png)

**Comment by Zhuinden** [comment]
Well it claims it ran out of memory, you can try adding more memory if you have a build.gradle where you can put this:

    dexOptions{
        javaMaxHeapSize "4g"
    }

Although considering this is not dex, i'm not sure if it helps

**Comment by Drjacky** [comment]
@Zhuinden I tested this before, and didn't help.
Even change 
```Java
org.gradle.jvmargs=-XX:MaxPermSize=512m
```
From
```Java
\realm\realm-java\gradle.properties
```
To something more
Or change
```Java
org.gradle.jvmargs=-Xms512m -Xmx2048m
```
From
```Java
\realm\realm-java\realm\gradle.properties
```
To something more
Or
Put gradle.properties under
```Java
\realm\realm-java\realm
```
With this content:
```Java
org.gradle.jvmargs=-Xms2048m -Xmx4048m
```

Didn't help.

**Comment by Zhuinden** [comment]
Make sure you close Chrome and other memory intensive stuff for this process to work

**Comment by kneth** [comment]
From the screenshot I assume that you are using Windows. We have tried to build under Windows so I can't tell if it's a Windows issue or not. Moreover, building Realm requires Android NDK which in the past wasn't working that well under Windows. My recommendation is that you install Linux in a virtual machine and try to build using that.

Switch to Windows 10 and use the built-in Linux support might be another option. Again, we haven't tried that.

**Comment by Drjacky** [comment]
@Zhuinden I have 32GB memory on my machine; And about 20GB is free. @kneth I'll try these solution too...

**Comment by kneth** [comment]
Can it be that you are using the 32 bit version of the JVM? The number reported indicated that you are not allowed to allocate more than 2 GB.

**Comment by kneth** [comment]
Btw, building Realm Java requires NDK r10e. Previously the NDK had issues on Windows: https://github.com/android-ndk/ndk/issues/139

**Comment by Drjacky** [comment]
@kneth Memory heap problem caused by JDK 32bit. I changed it to JDK 64bit and I get this error now:
![reamerror2untitled](https://cloud.githubusercontent.com/assets/2296754/22237019/5da2738a-e21e-11e6-9e0f-d1c4ea435d14.png)

I downloaded CMake from Android Studio.

**Comment by beeender** [comment]
It could be the same problem with https://github.com/taka-no-me/android-cmake/issues/94

@Drjacky would you please try to modify the `./realm/realm-library/src/main/cpp/android.toolchain.cmake` as it is described [here](https://github.com/bingmann/android-cmake/commit/e0ec7de86d454894b3837a62b8676635b6d318f6) and let us know the results? I don't have a windows machine right now so i cannot verify it :(
Thanks!

**Comment by Drjacky** [comment]
@beeender After those changes: I got this:
![realmerror3untitled](https://cloud.githubusercontent.com/assets/2296754/22237857/9e11fb84-e223-11e6-9df7-dc48961b75f0.png)

**Comment by beeender** [comment]
@Drjacky Make sure the `javah` is in your system's `PATH` so cmake can find it to generate jni header files from java class.

**Comment by Drjacky** [comment]
@beeender It's exist!
![javahexistuntitled](https://cloud.githubusercontent.com/assets/2296754/22238130/fc38b6b6-e224-11e6-954c-339c9946d9be.png)

**Comment by beeender** [comment]
hmmm, maybe it is trying to find the `javah` by `JAVA_HOME`. Can you try to set the `JAVA_HOME` to your JDK home?

**Comment by Drjacky** [comment]
@beeender  This is my whole Environment Variables:
![systenvbothuntitled](https://cloud.githubusercontent.com/assets/2296754/22240955/91149b6c-e232-11e6-944a-4ba50f1807c1.png)

**Comment by beeender** [comment]
Does `C:\Program Files\Java\jdk1.8.0_121\bin\javah.exe` exist?

**Comment by Drjacky** [comment]
@beeender Yes.
![javahexist64untitled](https://cloud.githubusercontent.com/assets/2296754/22241416/72736f42-e234-11e6-8f97-2dd183232ef6.png)

**Comment by beeender** [comment]
It is very strange. Probably caused by the cmake doesn't play well with windows path separator.
So maybe you can try to handcode the javah path in `./realm/realm-library/src/main/cpp/android.toolchain.cmake`.  Before line 10 `else()`, something like:
```cmake
    elseif (EXISTS "C:/Program Files/Java/jdk1.8.0_121/bin/javah.exe")
        set(Java_JAVAH_EXECUTABLE "C:/Program Files/Java/jdk1.8.0_121/bin/javah.exe")
```

You might need to remove the line 6-7 since you actually have the `JAVA_HOME` set.

Also, if it doesn't work, try to change the path separator to `\\`.

**Comment by beeender** [comment]
or maybe you only need to add `.exe` to line 6-7

**Comment by Drjacky** [comment]
@beeender I coudn't find that line. This is my `android.toolchain.cmake`
***Note:** Attaching ZIP file failed. So I changed text file extension to JPG. Please download this file and remove JPG extension.
[Link](https://cloud.githubusercontent.com/assets/2296754/22243786/1a9afbe6-e23e-11e6-9576-54037706a805.jpg)

![android toolchain - copy cmake](https://cloud.githubusercontent.com/assets/2296754/22243786/1a9afbe6-e23e-11e6-9576-54037706a805.jpg)

**Comment by beeender** [comment]
uh ... Really sorry, I put a wrong file path there. It should be `./realm/realm-library/src/main/cpp/CMakeLists.txt`

**Comment by Drjacky** [comment]
@beeender Adding .exe to javah didn't help. But when I added another `elseif`, javah not found error gone, but this error:
![ninjaerroruntitled](https://cloud.githubusercontent.com/assets/2296754/22247710/73c588aa-e250-11e6-84cc-fc88bfae13a5.png)

**Comment by beeender** [comment]
It might be a cmake bug which is similar to https://llvm.org/bugs/show_bug.cgi?id=27226 ...
I don't have immediate idea right now ... I suggest you to try compile it under linux (virtual machine maybe?) or maybe you can try with build it in `cygwin`? It might solve it but i am not sure.

I will mark this as an low priority issue then. And it might not be solved soon since no one is using windows in the team. Sorry :(

**Comment by cmelchior** [comment]
Folding this into the original issue about Windows support: #911
