### ISSUE TITLE
calling Realm#migration with a SyncConf should throw

### ISSUE THREAD

**Issue by nhachicha** [realm/realm-java#4075]
Sync Realm perform automatic migration, we shouldn't mislead the user to call [migrateRealm](https://github.com/realm/realm-java/blob/master/realm/realm-library/src/main/java/io/realm/BaseRealm.java#L608) with a specified migration block, this should throw `UnsupportedOperationException` instead of silently ignoring the user migration block

**Comment by cmelchior** [comment]
Fixed by #4292
