### ISSUE TITLE
A payload for Realm transaction

### ISSUE THREAD

**Issue by Miha-x64** [realm/realm-java#4079]
Hello, Realm team, and thank you for your work!

I've made my own RecyclerView.Adapter subclass which uses DiffUtil from support library to update RecyclerView's contents smoothly.
It needs to compare old and new data set, but it was impossible to hold old database table's snapshot because it's memory-expensive, so I considered filling an array of old table record IDs and a set of IDs of changed records instead — this information is a required minimum to make DiffUtil work properly.

Unfortunately, when Realm sends its notification about changes, there is no way to deliver another information along with updated Realm object, so I've implemented delivery of additional information in quite weird and crazy way.
Of course, I could add 'changedInLastTransaction' and 'existedBeforeLastTransaction' flags into my model, but building diff with them could be less efficient.

#### Goal

I'd like to have an ability to carry some additional information along with updated object.

#### Expected Results

I'm expecting that it will be possible to commit a transaction passing an arbitary object (tag, payload) which will be delivered to observers along with update.

For example, committing transaction could look like this:
```java
realm.commitTransaction("hello");
```
or
```java
realm.executeTransactionAsync(realm -> {
    ...
    realm.setPendingTransactionPayload("hello");
});
```

And receiving update:
```java
@Override
void onChange(RealmResults<Whatever> element, Object payload) {
```

UPD.
While Realm updates are coarse-grained, Transaction Payload could also help to understand which parts of data were updated and which data observers should update their state, and which ones shouldn't.

**Comment by beeender** [comment]
@Miha-x64 thanks a lot for you suggestion. But I think what you need is the fine grained notifications from Realm which has been tracked by #989 . And we have already started work on that one. You can see the API proposal on #3977 . Does those new APIs fulfil your requirement?

**Comment by Miha-x64** [comment]
Hello @beeender. Thank you for your response.
Fine-grained notifications API looks very interesting and convenient, I think it will fulfil my requirement.

But I still believe that Transaction Payload may be helpful in some cases, maybe its neccessity or uselessness will be more clear after some experience using fine-grained notifications. :)

**Comment by beeender** [comment]
@Miha-x64 Thanks a lot for the feedback. I hope the fine grained notification will solve your issue. I will just close this issue for now. If this is still needed after the fine grained notification released, let's reopen this and discuss it again.

**Comment by consp1racy** [comment]
In Realm 3.0.0 the adapter gets information on 

* what items were removed,
* what items were added,
* what items were changed.

This has been tracked in #989 and works beautifully afaict.

The outstanding issue is still the `payload` or *what precisely changed about the items that have changed*.

This `List<Object> payload` is supplied for each changed item. An empty list denotes a complete change (that's how it works now). I propose the list contains names of fields that have changed.

**Comment by beeender** [comment]
@consp1racy I think #4101 will be what you need. And that will be implemented soon :)

**Comment by consp1racy** [comment]
@beeender On second thought I don't think #4101 is the complete answer. It proposes an individual field listener. You get a notification when a field changes. That would mean that you'd have to setup listeners on each field of each object. (?)

Instead a list of field names that have changed should be passed in the `CollectionChangeSet` object.

```
public interface OrderedCollectionChangeSet {
    ...
    List<String> getChangedFields(final int position);
    // or
    ChangeSet getChangeSet(final int position);
}

class ChangeSet {
    List<String> fields;
}
```

where `position` is in `getChanges()`.

Would that be possible?
