### ISSUE TITLE
Sync- User should be notified about client reset

### ISSUE THREAD

**Issue by nhachicha** [realm/realm-java#4080]
currently error code related to the sync client reset are managed directly in JNI
https://github.com/realm/realm-java/blob/master/realm/realm-library/src/main/cpp/objectserver_shared.hpp#L87-L110

the current implementation will schedule a Realm backup/reset when the app starts again, we need also to return an error code so the user have a chance to stop the app.

**Comment by nhachicha** [comment]
This should probably be implemented in the ObjectStore by allowing the `SyncSession` to call the `error_handler` after this https://github.com/realm/realm-object-store/blob/f2571bfd66f797f3985463a0646d27287053ea72/src/sync/sync_session.cpp#L470

The SyncManager can then notify the error handler defined by the user to react to this kind of error

**Comment by cmelchior** [comment]
We need to expose the Client Reset information somehow. I see two options:

```
// Option A
// Specialized error class
@Override
void onError(ObjectServerError e) {
	// or if (e instanceof ClientResetError) {
	if (e.getErrorCode == ErrorCode.CLIENT_RESET) {
 		ClientResetError err = (ClientResetError) e
 		File backupFile = err.getBackupFilePath();
 		err.beginClientReset(); // Execute reset manually. Will crash if Realms are open
	}
}

// Option B
// Map with keys (Cocoa does something like this)
@Override
void onError(ObjectServerError e)
	if (e.getErrorCode == ErrorCode.CLIENT_RESET) {
		File backupFile = e.getUserInfo(ObjectServerError.KEY_BACKUP_FILE_PATH);

		// Possible another specific wrapper class?
		Runnable r = e.getUserInfo(ObjectServerError.KEY_INITIATE_CLIENT_RESET)
		r.run();	
	}
}
```

I would probably lean towards option A though. Thoughts @realm/java ?

**Comment by kneth** [comment]
I don't have a strong opinion but if we add more cases in the future, option B will keep the number of methods down.

**Comment by Zhuinden** [comment]
So this is for handling use-case described in https://realm.io/docs/realm-object-server/#client-recovery-from-a-backup right? (basing that on sync-session)

But what do I as developer need to do exactly when I receive one of these errors?
