### ISSUE TITLE
realm recyclerview adapter scroll issue

### ISSUE THREAD

**Issue by randomlock** [realm/realm-java#4085]
I am using the realm-android-adapter provided by realm to load data from database . Whenever the UI of the recyclerview is updated the scroll position  is reset to start . Also when changing the view of the recyclerview no animation is played . I looked at the adapter code and found that `notifyDataSetChanged()` is used each time when updating the view . Shouldn't it be replaced by `      notifyItemRangeChanged(0,getItemCount());` to avoid the above two problem ?

If not is there any way i can update scroll position + add animation when updating UI .

**Comment by Zhuinden** [comment]
I don't think scroll position should reset. That doesn't happen for me...

**Comment by kneth** [comment]
It is better to create an issue in https://github.com/realm/realm-android-adapters. When you do, please provide some source code so we can see how you are using the adapter.

**Comment by tjmille2** [comment]
Happens to me to.
