### ISSUE TITLE
`.in()` not working with Kotlin

### ISSUE THREAD

**Issue by ppamorim** [realm/realm-java#4092]
Hello, the method `.in(fieldName, [])` is not working with Kotlin because the language has this parameter, common used on the control flow of data (loop, when).

For example, this code doesn't compile:

```kotlin
val counts = arrayOf(0,3,5,10)
return realm.where(User::class.java).in("count", counts).findAll()
```

You must add `.'in'()` to use this method. This is not a big problem but can generate problems in some point of the future.

**Comment by ppamorim** [comment]
@beeender Is this a valid question?

**Comment by beeender** [comment]
@ppamorim thanks a lot for pointing this out. I tried coding something with the `in` function in the AS kotlin code, actually AS's auto-completion is smart enough to show suggestion about `in` APIs when you type `.` and it actually completes the function with `'in'()`.

So, IMO current thing is acceptable since `in` is short and easy to understand for users. Also it doesn't really create troubles for kotlin programmers. By adding an alias API, for example `inQuery`, it may confuse people and increasing the methods count a bit. And there may not be lots of user really using it since the kotlin auto-completion will suggest the `in` first anyway. 

@realm/java what do you think?

**Comment by zaki50** [comment]
If you want to avoid `.'in'()`, you can define an extension method as you like.

**Comment by heinrichreimer** [comment]
That should do the trick:

```kotlin
/**
 * Map Realm's [RealmQuery.in] methods to `oneOf` to bypass using Kotlin's `in` keyword
 * as a method name.
 */
fun <E : RealmModel> RealmQuery<E>.oneOf(fieldName: String, values: Array<String>): RealmQuery<E> = `in`(fieldName, values)
/**
 * Map Realm's [RealmQuery.in] methods to `oneOf` to bypass using Kotlin's `in` keyword
 * as a method name.
 */
fun <E : RealmModel> RealmQuery<E>.oneOf(fieldName: String, values: Array<String>, casing: Case): RealmQuery<E> = `in`(fieldName, values, casing)
/**
 * Map Realm's [RealmQuery.in] methods to `oneOf` to bypass using Kotlin's `in` keyword
 * as a method name.
 */
fun <E : RealmModel> RealmQuery<E>.oneOf(fieldName: String, values: Array<Byte>): RealmQuery<E> = `in`(fieldName, values)
/**
 * Map Realm's [RealmQuery.in] methods to `oneOf` to bypass using Kotlin's `in` keyword
 * as a method name.
 */
fun <E : RealmModel> RealmQuery<E>.oneOf(fieldName: String, values: Array<Short>): RealmQuery<E> = `in`(fieldName, values)
/**
 * Map Realm's [RealmQuery.in] methods to `oneOf` to bypass using Kotlin's `in` keyword
 * as a method name.
 */
fun <E : RealmModel> RealmQuery<E>.oneOf(fieldName: String, values: Array<Int>): RealmQuery<E> = `in`(fieldName, values)
/**
 * Map Realm's [RealmQuery.in] methods to `oneOf` to bypass using Kotlin's `in` keyword
 * as a method name.
 */
fun <E : RealmModel> RealmQuery<E>.oneOf(fieldName: String, values: Array<Long>): RealmQuery<E> = `in`(fieldName, values)
/**
 * Map Realm's [RealmQuery.in] methods to `oneOf` to bypass using Kotlin's `in` keyword
 * as a method name.
 */
fun <E : RealmModel> RealmQuery<E>.oneOf(fieldName: String, values: Array<Double>): RealmQuery<E> = `in`(fieldName, values)
/**
 * Map Realm's [RealmQuery.in] methods to `oneOf` to bypass using Kotlin's `in` keyword
 * as a method name.
 */
fun <E : RealmModel> RealmQuery<E>.oneOf(fieldName: String, values: Array<Float>): RealmQuery<E> = `in`(fieldName, values)
/**
 * Map Realm's [RealmQuery.in] methods to `oneOf` to bypass using Kotlin's `in` keyword
 * as a method name.
 */
fun <E : RealmModel> RealmQuery<E>.oneOf(fieldName: String, values: Array<Boolean>): RealmQuery<E> = `in`(fieldName, values)
/**
 * Map Realm's [RealmQuery.in] methods to `oneOf` to bypass using Kotlin's `in` keyword
 * as a method name.
 */
fun <E : RealmModel> RealmQuery<E>.oneOf(fieldName: String, values: Array<Date>): RealmQuery<E> = `in`(fieldName, values)
```

**Comment by cmelchior** [comment]
Kotlin Extension functions named `oneOf` as an alias for `in` will be available in 4.3

**Comment by deweyx** [comment]
I get an error:

    val myList = intent?.extras?.getIntArray(KEY_LIST)?.toTypedArray()
    realm.where<Item>().oneOf(FIELD_ID, myList)

`Error:(83, 24) None of the following functions can be called with the arguments supplied:
[...]
public fun <T : RealmModel> RealmQuery<Ticket>.oneOf(propertyName: String, value: Array<Int?>): RealmQuery<Ticket> defined in io.realm.kotlin`

This still works:

    realm.where<Item>().`in`(FIELD_ID, myList)

These function definitions should probably be `Array<out xx>`?

    fun <T : RealmModel> RealmQuery<T>.oneOf(propertyName: String,
                                         value: Array<out Int?>): RealmQuery<T> {
        return this.`in`(propertyName, value)
    }

Should I file a separate issue?

**Comment by cmelchior** [comment]
We actually just fixed that as the current implementation only allows nullable arrays. It should be in the next release.

**Comment by deweyx** [comment]
Awesome, thanks!
