### ISSUE TITLE
RealmObservableFactory unsubscription subscriber order and addChangeListener should be inverted

### ISSUE THREAD

**Issue by Zhuinden** [realm/realm-java#4095]
#### Goal

> What do you want to achieve?

Use `take(1)`

#### Expected Results

Unsubscribe as needed.

#### Actual Results

Not sure, but according to Jake Wharton, I think the code in [RealmObservableFactory](https://github.com/realm/realm-java/blob/master/realm/realm-library/src/main/java/io/realm/rx/RealmObservableFactory.java#L81-L82) might not work as expected with `take(1)` and this change in RxBinding can be seen in https://github.com/JakeWharton/RxBinding/commit/3ccbd006152bfd282e75304836744971521b661c

#### Version of Realm and tooling
Realm version(s): 2.3.0

**Comment by Zhuinden** [comment]
@kneth well i know that bugs and features are hard to distinguish over time, but I'm pretty sure this is not a feature :tongue:

**Comment by kneth** [comment]
@Zhuinden Sorry about that :-)

**Comment by cmelchior** [comment]
Should be fixed by moving to RxJava2: https://github.com/realm/realm-java/pull/4991
