### ISSUE TITLE
Sync Progress Notifications

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#4104]
Sync in Object Store exposes sync progress notifications: https://github.com/realm/realm-object-store/pull/310

The Cocoa implementation is here: https://github.com/realm/realm-cocoa/pull/4535

We should expose similar functionality in Java.

**Object Store description**

-----
Here is what the object store will provide:

* Bindings can register separate listeners for download and upload progress.
* For each of upload and download, bindings can register a listener either in the "stream" mode, in which updates will be provided forever, or in the non-streaming mode, in which the "downloadable" or "uploadable" value will be fixed at their value when the callback was registered.
* Bindings can register an unlimited number of listeners on a given session.
* Callbacks registered in the non-streaming mode will automatically unregister themselves when their progress reaches 100% or greater.
* Callbacks registered can be manually unregistered by calling an unregistration method and passing it the token integer returned when the callback was first registered.
* No matter the type of listener, upon registration it will immediately be called once to provide the app with the most recent information about upload and download status. If, at this point, the object store doesn't know what the uploadable or downloadable values are (since `sync` hasn't yet told it), it will make this clear to the binding.
----

**Use Cases**
1. Generic spinner when syncing is occurring
2. Opening a realm, getting progress on any initial download
3. Committing a write transaction and getting progress on the upload

**Tasks**

- [ ] Define the public API
- [ ] Implement API
- [ ] Integration tests
- [ ] Unit tests
- [ ] Javadoc
- [ ] Website updates

Implementation depends on #3742  being merged first.

**Comment by monajafi** [comment]
when Sync Progress Notifications will be published for java ?

**Comment by monajafi** [comment]
I can't find sync progress and notification in realm java 3.0. it was planned for version 2.5 already
when do you estimate this feature will be implemented for java?

**Comment by Zhuinden** [comment]
Well it does say milestone 3.1

**Comment by markst** [comment]
Will the include the ability to identify whether an individual object has completed sync?

**Comment by cmelchior** [comment]
@markst No, not in the first iteration of this API, but we are considering adding that ability later.
