### ISSUE TITLE
Async Transactions and Try-With-Resources

### ISSUE THREAD

**Issue by unosmiles** [realm/realm-java#4112]
(Perhaps this is just my ineptitude)

This code:

```java 
try (Realm realm = Realm.getDefaultInstance()) {
            realm.executeTransactionAsync(new Realm.Transaction() {
                @Override
                public void execute(Realm realm) {
                    func.execute(realm);
                }
            }, new Realm.Transaction.OnSuccess() {
                @Override
                public void onSuccess() {
                    singleSubscriber.onSuccess(null);
                }
            }, new Realm.Transaction.OnError() {
                @Override
                public void onError(Throwable error) {
                    singleSubscriber.onError(error);
                }
            });
        }
```

Never calls through to the OnSuccess/ OnError block. I'm assuming this is because the try-with-resources statement closes the realm before the respective callbacks can be executed, but I haven't been able to get to the bottom of this.

Is this an issue or a limitation of Realm?

**Comment by cmelchior** [comment]
Async API's doesn't work with `try-with-ressources`. Because they are async they use the Looper to communicate back, but you closed the Realm when exiting the block, so the callbacks can never be called.

**Comment by unosmiles** [comment]
I assumed as much. Thanks for your help.
