### ISSUE TITLE
Search with Case.INSENSITIVE not working with some Roman (latin) letters

### ISSUE THREAD

**Issue by shiami** [realm/realm-java#4122]
For example:

Á, À, Â, Ā, A̍, and same with other letters (Í, Ú, É, Ó, Ń, Ḿ...).
The result is still Case.SENSITIVE.

#### Version of Realm and tooling
Realm version(s): 2.3.0

Realm sync feature enabled: no

Android Studio version: 2.2.3

Which Android version and device: 6.0.1, Nexus 5

**Comment by Zhuinden** [comment]
https://realm.io/docs/java/latest/#sorting-and-querying-on-string

**Comment by shiami** [comment]
No chance to support it?
Any workaround?

**Comment by Zhuinden** [comment]
Personally I had a second field that had all accents truncated out of it, and did the sorting based on that.

This is what I used: http://stackoverflow.com/a/36500456/2413303

**Comment by cmelchior** [comment]
This is also being tracked here: https://github.com/realm/realm-java/issues/1031
See e.g https://github.com/realm/realm-java/issues/1031#issuecomment-230469563

Closing as a duplicate
