### ISSUE TITLE
run the example module

### ISSUE THREAD

**Issue by jacky1234** [realm/realm-java#4126]
> We LOVE to help with any issues or bug you have!

> **Questions**: when I run `./gradlew installRealmJava` from the top-level directory.the issue occured. here is the problem:

![image](https://cloud.githubusercontent.com/assets/10626484/22453151/ad364914-e7b7-11e6-8a78-7c01bfa356eb.png)
It seems the include file <util/format.hpp> can't be found , how do I fix it? thank you!

**Comment by cmelchior** [comment]
@jacky1234 Did you also checkout our git submodule: https://github.com/realm/realm-java/blob/master/README.md#download-sources ?

**Comment by bmeike** [comment]
@jacky1234 Did you resolve this?  Can we close the ticket?

**Comment by jacky1234** [comment]
@cmelchior No.I solve this by simply download the standalone examples  from web site https://realm.io/docs/java/latest/#getting-started. Thank you!
