### ISSUE TITLE
Fatal signal 11 (SIGSEGV) on Xiaomi(Android 6.0.1)

### ISSUE THREAD

**Issue by LPFinch** [realm/realm-java#4134]
Hi, we catch this bug on Xiaomi Redmi only 2 times.
Realm 2.2.2
Any solutions?
Thanks
P.S. Log in attach
[log_xiaomi.txt](https://github.com/realm/realm-java/files/745683/log_xiaomi.txt)

**Comment by bmeike** [comment]
Can you show us the code for com.myapp.ui.fragment.NotificationsFragment, please?

**Comment by LPFinch** [comment]
Sure, give me your email

**Comment by bmeike** [comment]
help@realm.io.  Please cite this GitHub issue...

**Comment by bmeike** [comment]
@LPFinch did you get a chance to send that code?

**Comment by bmeike** [comment]
@LPFinch Please forward your code to help@realm.io and re-open this ticket if there is anything further we can do for you.
