### ISSUE TITLE
Realm instance has already been closed, making it unusable

### ISSUE THREAD

**Issue by judemanutd** [realm/realm-java#4149]
[https://stackoverflow.com/questions/42057566/realm-instance-has-already-been-closed-making-it-unusable](Realm instance has already been closed, making it unusable)

Sorry about linking my stackoverflow question but it seemed easier.

**Comment by kneth** [comment]
Realm Java 2.2.2 changed major classes to be non-final to help Mockito users. Which version do you use?

**Comment by Zhuinden** [comment]
@kneth I don't think this question has anything to do with unit testing

**Comment by kneth** [comment]
@Zhuinden My mistake - I was reading a question at Stackoverflow at the same time. @judemanutd Please ignore my comment ;-)

**Comment by judemanutd** [comment]
@kneth if it makes an difference now , i am using 2.3.0

**Comment by kneth** [comment]
`getDefaultInstance()` is not really able to return `null`. In error situations it will throw an exception. Can you set a breakpoint where you call `getDefaultInstance()` so to be sure that you actually calls it the second time?

**Comment by Zhuinden** [comment]
@kneth I've got `null` for Realm.getInstance() before when `˙context.getFilesDir()` returned null in `Application.onCreate()`, but that was back in 0.88.0

**Comment by zaki50** [comment]
Since `DataRepository` keeps PoliticoDataRepository instance to static field, `DataRepository.getInstance()` might return old `PoliticoDataRepository` instance which contain closed Realm instance.
You should remove static field of `dataRepository` from `DataRepository`.

**Comment by bmeike** [comment]
Answered here and on GitHub.  Closing.
