### ISSUE TITLE
Multi language schema generator / conversor

### ISSUE THREAD

**Issue by gpulido** [realm/realm-java#4150]
I'm using Realm.io as db for an android project, and since the release of the mobile plattform I would like to use the same db schema in other languages (mainly node.js).

My schema is pretty big with a lot of classes and relations, that I must replicate in javascript.
I'm wondering if there any tool / way to transform from one language (java) to another (js in this case).

I'm thinking on something similar to protobuffers / flatbuffers, when one "schema" definition is transformed in the language of choice.
Is I'm using Realm.io as db for an android project, and since the release of the mobile plattform I would like to use the same db schema in other languages (mainly node.js).

My schema is pretty big with a lot of classes and relations, that I must replicate in javascript.
I'm wondering if there any tool / way to transform from one language (java) to another (js in this case).

I'm thinking on something similar to protobuffers / flatbuffers, when one "schema" definition is transformed in the language of choice.

Is such tool in project?
Thank you in advance

**Comment by Zhuinden** [comment]
the Realm Browser for Mac OS should be able to do that

**Comment by kneth** [comment]
The Realm Browser doesn't support JavaScript yet but it is coming very soon: https://github.com/realm/realm-browser-osx/pull/272

**Comment by gpulido** [comment]
Hello,
Although it is nice to have such feature in the browser, I was thinking in a development tool / parser like the protobuff, so anytime the schema changed, it can generate versions for every language needed.

**Comment by kneth** [comment]
The alternative is that you open your Realm file as a `DynamicRealm`, traverse the schema, and generate the JavaScript definition: https://realm.io/docs/java/2.3.0/api/io/realm/RealmSchema.html

**Comment by cmelchior** [comment]
We are also tracking this feature here https://github.com/realm/realm-mobile-platform/issues/24, where it probably makes more sense than to track it in the Java repo by itself. I'll close this as an duplicate, but please provide any information about your use case and how you see such a tool work in your workflow in the RMP issue.
