### ISSUE TITLE
Realm Migration Code When User Don't Have Any Data

### ISSUE THREAD

**Issue by saeedrooyekhat** [realm/realm-java#4154]
when i create realm database and don't have any data from past , after set default configuration and getDefaultInstance i get an error "The 'RealmClientCondition' class is missing from the schema for this Realm" ! . but when i have some data in realm from the past never i get any error like this?

my sample code
```java
Realm.setDefaultConfiguration(new RealmConfiguration.Builder(getApplicationContext())
                .name("LocalDatabase.realm")
                .schemaVersion(2)
                .migration(new RealmMigration())
                .build());

```

if i use from this code in first time also i don't get error
```java
Realm.setDefaultConfiguration(new RealmConfiguration.Builder(getApplicationContext())
                .name("LocalDatabase.realm")
                .schemaVersion(2)
                .migration(new RealmMigration())
                .deleteRealmIfMigrationNeeded()
                .build());

```

RealmMigrationCode
```java
RealmSchema schema = realm.getSchema();
        if (oldVersion == 1) {
            RealmObjectSchema roomSchema = schema.get("RealmRoom");
            roomSchema.addField("keepRoom", boolean.class, FieldAttribute.REQUIRED);

            RealmObjectSchema realmRoomMessageSchema = schema.get("RealmRoomMessage");
            realmRoomMessageSchema.addField("authorRoomId", long.class, FieldAttribute.REQUIRED);
            oldVersion++;
        }

```
Realm version(s):1.2.0

Android Studio version: 2.2.1

Which Android version and device: 4.4.2 (api 19)

**Comment by cmelchior** [comment]
```
Realm.setDefaultConfiguration(new RealmConfiguration.Builder(getApplicationContext())
                .name("LocalDatabase.realm")
                .schemaVersion(2)
                .migration(new RealmMigration())
                .deleteRealmIfMigrationNeeded()
                .build());
```

This code is most likely wrong. Setting `deleteRealmIfMigrationNeeded()` will mean your migration function is never triggered.

Regarding: `RealmClientCondition`. At what version did you add this class? If it was after the initial version, it doesn't look like you are adding it in the migration code?

**Comment by saeedrooyekhat** [comment]
i add RealmClientCondition in schema 1. when i run app again have same error with different RealmObjectClass. like this "The 'RealmUserInfo' class is missing from the schema for this Realm".
If I install the application before and install the new one I don't get this error.

**Comment by cmelchior** [comment]
The schema starts at version 0, so if you add that class in v1, you are missing it from your migration code. You need to add the new class like this: https://github.com/realm/realm-java/blob/master/examples/migrationExample/src/main/java/io/realm/examples/realmmigrationexample/model/Migration.java#L93

**Comment by saeedrooyekhat** [comment]
i used schema 1 from first launching in this app and have RealmUserInfo or another RealmObjects in that version  @of schema .

**Comment by bmeike** [comment]
Hey @saeedrooyekhat,

There may be some confusion about what it means to "migrate" a database.  We intend "migration" to mean modifying an existing database to add additional data.  It may, under some circumstances, be possible to delete the existing database and recreate it, with the new extensions.  This is not migration and if you use this strategy, you do not need to specify a `.migration()` clause.

  We've identified a couple of problems in the code you sent us: you should not be using `deleteRealmIfMigrationNeeded()` if you need to migrate; your migration code doesn't seem to add the needed `RealmClientCondition` class.

If you are still having problems, please open a new ticket, with your current code.  This will help to avoid confusion.  If we can see exactly the code that is causing trouble, we are much more likely to be able to provide useful suggestions.  If you open a new ticket (and, by all means, do that, if you are still having problems!!) just include the exact code that is the current problem and a description of what you expect it to do.  We will need:
