### ISSUE TITLE
error Realm access from incorrect thread

### ISSUE THREAD

**Issue by poly-sb** [realm/realm-java#4157]
I cannot figure out why this code give me a 'error Realm access from incorrect thread'.

I instantiated my dao on the main thread of my BaseActivity.
```java
protected Dao dao;

@Override
protected void onCreate(@Nullable Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    dao = new Dao();
}
```

Here the body of my dao:
```java
private Realm realm;

public Dao() {
    realm = Realm.getDefaultInstance();
}

public void removeEntity(Long id) {
     realm.executeTransactionAsync((r) -> {
         TaskEntity t = r.where(TaskEntity.class).equalTo(MyEntity.ID, id).findFirst();
         t.deleteFromRealm();
     });
}
```

On my child activity I use the instance from my BaseActivity to persist my entity.
```java
@Override
public void onWebSocketMessage(String id) {
    runOnUiThread(()->{
        dao.removeEntity(Long.valueOf(id))
    });
}

```
Realm version: io.realm:realm-gradle-plugin:2.2.1
Realm sync feature enabled: no
Android Studio version: 2.2.2

**Comment by Zhuinden** [comment]
If `MyEntity` is a managed object queried from the main thread, then accessing it in `executeTransactionAsync()` that runs on a background thread will fail.

**Comment by poly-sb** [comment]
ok sorry I just update my code.

**Comment by cmelchior** [comment]
It happens because you create the Realm instance in the constructor. It means the Dao is tied to whatever thread created the Dao in the first place. If you call the Dao from many threads, you should get the instance in each of your Dao methods.

**Comment by poly-sb** [comment]
@cmelchior all right but I'm actually creating and retrieving the instance from the main thread right!?

**Comment by cmelchior** [comment]
Yes, from the code you posted it looks like it. I would try to move it into the `removeEntity` method though, just to verify that assumption.

**Comment by poly-sb** [comment]
Calling runOnUiThread inside the removeEntity Fail too. 
Actually I try this and it work.

```java

Handler mainHandler = new Handler(context.getMainLooper());
mainHandler.post(()->{
    realm.executeTransaction((r) -> {
        // same code here
    });
});

```
It should be the cause of the websocket callback which is created from a background service my two cents.

from [here](http://stackoverflow.com/questions/19366301/run-callback-on-main-thread)
