### ISSUE TITLE
Detect Migration Need Or Not

### ISSUE THREAD

**Issue by saeedrooyekhat** [realm/realm-java#4160]
i want migrate realm db and add two fields. i used from this migration code

```java
public class RealmMigration implements io.realm.RealmMigration {

    @Override
    public void migrate(DynamicRealm realm, long oldVersion, long newVersion) {
        RealmSchema schema = realm.getSchema();
        if (oldVersion == 1) {
            RealmObjectSchema roomSchema = schema.get("RealmRoom");
            if (roomSchema != null) {
                roomSchema.addField("keepRoom", boolean.class, FieldAttribute.REQUIRED);
            }

            RealmObjectSchema realmRoomMessageSchema = schema.get("RealmRoomMessage");
            if (realmRoomMessageSchema != null) {
                realmRoomMessageSchema.addField("authorRoomId", long.class, FieldAttribute.REQUIRED);
            }
            oldVersion++;
        }
    }
}
```
and there is no problem . my realm db migrated after install new app over older version. but if i uninstall older version app realm info will be cleared , and finally after install new version with new schema i get this error

```java
 Caused by: io.realm.exceptions.RealmMigrationNeededException: The 'RealmClientCondition' class is missing from the schema for this Realm.
```

in schema 2 i just add two fields and all of the other RealmObjects and fields was exist in schema 1.

also i tested this actions with simple project and don't get any errors! 
Is it possible that i got this error for existing too many realm classes in main project (about 30).

also when don't exist any data in realm , i don't want migrate db , but how can detect my user is a new one or had a older version of my application. is there any way to detect realm info exist now or not.
i can't try this code

```java
Realm.getInstance(config).isEmpty();
```
or 
```java
Realm.getDefaultInstance().isEmpty();
```
because when i want getInstance from realm i get error.

**[before issue in this regard](https://github.com/realm/realm-java/issues/4154)**

the schema for the previous version of the db : 1
the schema for the new version of the db : 2

Realm version(s):1.2.0

Android Studio version: 2.2.1

Which Android version and device: 4.4.2 (api 19)

**Comment by Zhuinden** [comment]
You can check the schema version by opening the Realm as a DynamicRealm.

**Comment by cmelchior** [comment]
```
DynamicRealm dRealm = DynamicRealm.getInstance(config);
dRealm.getVersion(); // Returns version of Realm file on disk
dRealm.close();
```

This will give you the current version of the Realm without forcing an upgrade.

**Comment by bmeike** [comment]
Hey @saeedrooyekhat !
  Can we be of any more assistance?  If not, we should close this ticket.

**Comment by saeedrooyekhat** [comment]
@cmelchior thank you for your solution. it worked!

now i use from this code

```java
RealmConfiguration configuration = new RealmConfiguration.Builder(getApplicationContext()).name("iGapLocalDatabase.realm").schemaVersion(2).migration(new RealmMigration()).build();
        DynamicRealm dynamicRealm = DynamicRealm.getInstance(configuration);
        dynamicRealm.getVersion(); // Returns version of Realm file on disk
        if (dynamicRealm.getVersion() == -1) {
            Realm.setDefaultConfiguration(new RealmConfiguration.Builder(getApplicationContext()).name("iGapLocalDatabase.realm").schemaVersion(2).deleteRealmIfMigrationNeeded().build());
        } else {
            Realm.setDefaultConfiguration(new RealmConfiguration.Builder(getApplicationContext()).name("iGapLocalDatabase.realm").schemaVersion(2).migration(new RealmMigration()).build());
        }
        dynamicRealm.close();
```

when version is -1 i don't user migrate and otherwise use from migration.
