### ISSUE TITLE
llegal Argument: Invalid type

### ISSUE THREAD

**Issue by MikeKasperlik** [realm/realm-java#4167]
We got a strange crash for multiple of our users currently. This is 100% HUAWEI although we have way more users with other devices. 

#### Expected Results

No crash

#### Actual Results

```
Fatal Exception: java.lang.IllegalArgumentException: Illegal Argument: Invalid type - Only String, Date, boolean, byte, short, int, long and their boxed variants are supported.
       at io.realm.internal.TableView.nativeDistinct(TableView.java)
       at io.realm.internal.TableView.distinct(TableView.java:722)
       at io.realm.RealmQuery.distinct(RealmQuery.java:1375)
       at SyncAdapter.onPerformSync(SyncAdapter.java:122)
       at android.content.AbstractThreadedSyncAdapter$SyncThread.run(AbstractThreadedSyncAdapter.java:272)
```

#### Steps & Code to Reproduce

RealmObject:
```
public class TripData extends RealmObject {
    @PrimaryKey
    private long date;
    @Index
    private String trip_local_id;
    private byte[] data;
}
```

Query:
```
        RealmResults<TripData> distinctTripSamples = realm
                .where(TripData.class)
                .distinct("trip_local_id"); // This line crashes?
```

#### Version of Realm and tooling
Realm version(s): 2.3.0

Realm sync feature enabled: no

Android Studio version: 2.2.3

Which Android version and device: 
<img width="1052" alt="screen shot 2017-02-09 at 22 37 45" src="https://cloud.githubusercontent.com/assets/1431474/22804252/821076fc-ef18-11e6-8047-966b7fb70de6.png">

**Comment by Zhuinden** [comment]
Is this distinct inside a transaction?

**Comment by MikeKasperlik** [comment]
No

**Comment by Zhuinden** [comment]
Do you have any transaction inside this Sync adapter? If yes, consider moving queries into the transaction.

**Comment by MikeKasperlik** [comment]
We do have multiple transactions in this SyncAdapter. I will try if wrapping the query into a transaction helps. Is this documented anywhere?

**Comment by Zhuinden** [comment]
This is just a wild guess from my part, but a write transaction keeps the Realm at "the latest version" in which case I would assume you can't accidentally end up with an invalid index. However this could also be a core bug, only a true Realm person would know.

**Comment by kneth** [comment]
@MikeKasperlik How often does it fail on those devices? I mean, does it happen every time or only on rare cases?

**Comment by MikeKasperlik** [comment]
Only sometimes. At ~6% of all Sessions of the affected devices.

**Comment by beeender** [comment]
@MikeKasperlik I re-checked our test cases on Huawei Hornor 7 (PLK-AL10) device, no crash can be found. Can you please share your apk with use privately so we can test it? to help@realm.io . Also please let us know the possible reproduce steps. Thanks!

**Comment by kneth** [comment]
@MikeKasperlik I am closing the issue for now. If you have a APK which can reproduce the error, please send it to us.
