### ISSUE TITLE
Android Studio Strict Mode Unable to Locate Error

### ISSUE THREAD

**Issue by judemanutd** [realm/realm-java#4170]
Could someone tell me if realm is causing the issue in my code here.

[https://stackoverflow.com/questions/42159421/android-studio-strict-mode-unable-to-locate-error](Android Studio Strict Mode Unable to Locate Error)

**Comment by Zhuinden** [comment]
No, your crash is SQLite Cursor related, but Realm does not use SQLite.

**Comment by judemanutd** [comment]
@Zhuinden Thank you for your prompt reply.
