### ISSUE TITLE
Permission denied in /home/cc/repo/realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp

### ISSUE THREAD

**Issue by radzish** [realm/realm-java#4182]
Posting new issue as old one was closed, but is still actual.
Realm version used: 2.3.0
Device: HUAWEI MT7-L09
Trace:
`
Exception io.realm.exceptions.RealmError: Unrecoverable error. Permission denied in /home/cc/repo/realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 92
io.realm.internal.SharedRealm.nativeGetSharedRealm (SharedRealm.java)
io.realm.internal.SharedRealm.getInstance (SharedRealm.java:209)
io.realm.internal.SharedRealm.getInstance (SharedRealm.java:186)
io.realm.RealmCache.createRealmOrGetFromCache (RealmCache.java:124)
io.realm.Realm.getDefaultInstance (Realm.java:209)
`

**Comment by beeender** [comment]
@radzish 
1. How does your `RealmConfiguration` look like?
2. Did you use the Realm file on the external storage?
3. From the log, is it the first time your app tries to open the Realm?

**Comment by beeender** [comment]
close and dup this one to #3972 
@radzish if you have any more information, please comment in #3972.
