### ISSUE TITLE
 Crash: Unable to open a realm at path '/data/data/com.app/files/Realm': Realm file decryption failed. (Realm file decryption failed) in /home/cc/repo/realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp

### ISSUE THREAD

**Issue by MiralDesai** [realm/realm-java#4183]
#### Goal

> What do you want to achieve?

For the app not to crash when trying decrypt the realm database. I tested it myself with no issue, however this is happening to a few of our users. I'm unsure why. I specifically made it so that the key was recreatable to avoid issues that the Android Keystore has. However it's still causing issues. Could it be something to do with moving from an unencrypted realm to and encrypted realm?

#### Actual Results

`Fatal Exception: io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/data/com.app/files/Realm': Realm file decryption failed. (Realm file decryption failed) in /home/cc/repo/realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 92
       at io.realm.internal.SharedRealm.nativeGetSharedRealm(SourceFile)
       at io.realm.internal.SharedRealm.getInstance(SourceFile:209)
       at io.realm.internal.SharedRealm.getInstance(SourceFile:186)
       at io.realm.RealmCache.createRealmOrGetFromCache(SourceFile:124)
       at io.realm.Realm.getDefaultInstance(SourceFile:209)
       at com.google.android.gms.internal.zzart$zzb$1.zza(Unknown Source)
       at com.google.android.gms.internal.zzart$zzb$1.zzs(Unknown Source)
       at com.google.android.gms.internal.zzaaz.zzb(Unknown Source)
       at com.google.android.gms.internal.zzaaz$zza.handleMessage(Unknown Source)
       at android.os.Handler.dispatchMessage(Handler.java:102)
       at android.os.Looper.loop(Looper.java:168)
       at android.app.ActivityThread.main(ActivityThread.java:5845)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:797)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:687)`

#### Steps & Code to Reproduce

I'm not sure why this is happening. I've tried to replicate the issue however my Realm file is being decrypted correctly, without issue.

#### Code Sample

This is what I've been doing to move from an unencrypted realm to an encrypted realm. Removing the default config and applying it again. I'm not sure why it's unable to decrypt.

```
`Realm.removeDefaultConfiguration();
            RealmConfiguration configuration = new RealmConfiguration.Builder()
                    .name("Realm")
                    .schemaVersion(1)
                    .deleteRealmIfMigrationNeeded()
                    .encryptionKey(hash)
                    .build();
            Realm.setDefaultConfiguration(configuration);`
```

#### Version of Realm and tooling
Realm version(s): 2.3.0

Realm sync feature enabled: no

Android Studio version: 2.2.3

Which Android version and device: Two devices the crash has occurred on so far. Samsung S6 on 6.0.1 and HTC One M8 on 6.0

**Comment by Zhuinden** [comment]
2.4.0-SNAPSHOT has a relevant bugfix that might help

**Comment by MiralDesai** [comment]
Ah ok. Will wait for 2.4.0 then

**Comment by MiralDesai** [comment]
Just as a follow up, this is starting to affect a large number of my user base, do we have on estimate on when 2.4.0 will be released?

I guess I'm going to have to release an update to turn off encryption for the time being?

**Comment by kneth** [comment]
How did you move from unencrypted to encrypted? Did you write the Realm to a new file?

**Comment by MiralDesai** [comment]
No. I only removed the configuration and added a new one. As shown above.

**Comment by kneth** [comment]
Did you removed the unencrypted Realm file?

**Comment by MiralDesai** [comment]
Again, I didn't. Are these two things I should have done? Delete the existing realm and start fresh?

I bumped the schemaVersion and I've got deleteRealmIfMigrationNeeded() in there, but I guess that's not the same thing.

**Comment by kneth** [comment]
My best guess is that you try to open the old, unencrypted Realm file with an encryption key. That will fail as Realm will believe that you are opening with a wrong key. You can encrypt (or change key) by calling [`Realm.writeEncryptedCopyTo()`](https://realm.io/docs/java/2.3.1/api/io/realm/Realm.html#writeEncryptedCopyTo-java.io.File-byte:A-).

**Comment by kneth** [comment]
I am closing the issue. If my suggestion did work out for you, please either reopen or create new issue.
