### ISSUE TITLE
HOW TO SOLVE: This method is only available in managed mode error?

### ISSUE THREAD

**Issue by Muddz** [realm/realm-java#4184]
When I install my app for first time on my phone, the app crashes because of the Realm error: `This method is only available in managed mode`

This happends when I try to retrive a sorted list of `ListItem` in the class `Shoplist` which has a reference of `RealmList<ListItem>`

```java

    public class Shoplist extends RealmObject implements Serializable {

    private RealmList<ListItem> itemList;   //ListItem extends `RealmObject`

    @Ignore
    private Realm realm;

    @PrimaryKey
    private long id;

    public Shoplist() {

        realm = Realm.getDefaultInstance();
    }

    public RealmList<ListItem> getItemList() {
        return itemList;
    }

  public List<ListItem> getItems(String listOrder) {

        RealmResults<ListItem> realmResults;

        switch (listOrder) {
            case PrefActivity.ASCENDING:
                realmResults = getItemList().where().findAll(); // this crashes!
                break;

            case PrefActivity.DESCENDING:
                realmResults = getItemList().where().findAllSorted(ListItem.TIME_STAMP, Sort.DESCENDING);
                break;
        }

        return realmResults;
       }
    }

```

**STATS:** 

Realm Gradle Plugin: 2.3.1
Gradle Plugin: 2.2.3
Compile version: 25
Android Studio version: 2.2.3
Test phone: Samsung Galaxy S7

**Comment by Zhuinden** [comment]
`getItemList()` seems to return the RealmList from an unmanaged `ListItem`

solution: call `getItemList()` only on managed ListItems

**Comment by Muddz** [comment]
@Zhuinden I dont understand. Could you provide me with an example?

**Comment by Zhuinden** [comment]
unmanaged RealmList:

    ListItem listItem = new ListItem();
    listItem.setItemList(new RealmList<>());
    listItem.getItems("blah"); // crash

managed RealmList:

    ListItem listItem = realm.createObject(ListItem.class);
    // or
    ListItem listItem  = realm.where(ListItem.class).findFirst();
    listItem.getItems("blah"); // works

**Comment by Muddz** [comment]
@Zhuinden But I need it as this: `RealmList<ListItem> itemList;` not as a single ListItem object.

**Comment by Zhuinden** [comment]
You need to obtain the RealmList from a managed instance of `Shoplist`.

I meant `Shoplist` in most cases of my example, I'll edit accordingly.

**Comment by Muddz** [comment]
@Zhuinden This approach is not right!

I don't want to create a new realm object like that: `Shoplist shoplist= realm.createObject(Shoplist.class);`
Why would create a new object of Shoplist inside the Shoplist class itself?

A Shoplist object, contains a `RealmList` of `ListItems` I I want `ListItems` in different orders.

The user In the app can create a new shoplist with a user defined name, Lets call that "Picnic party"
Now the use can choose to add items/products into the Picnic Party list and choose to have this list of items shown in different orders.


`

**Comment by Zhuinden** [comment]
What is the value of `isManaged()` inside ` getItems()` when you get the crash?

Please debug and set a watcher for `this.isManaged()` inside `getItems()` before the crash

**Comment by Muddz** [comment]
On first time run after i installed the app the result is: 

    Log.d("TAG", "itemList.isManaged():  " + itemList.isManaged()); **= FALSE**
    Log.d("TAG", "this.isManaged():  " + isManaged()); **= FALSE**


But for some strange reason the app starts normally when I start it again right after the crash

**Comment by Muddz** [comment]
I may have found the error! Give me 10 minutes

**Comment by Zhuinden** [comment]
`ShopList shopList = new ShopList()` creates an unmanaged instance on which Realm's query API doesn't work on the `RealmList`

**Comment by Muddz** [comment]
@Zhuinden 


So this is wrong? I call  createShoplist(); from a class called RealmService()


    public Shoplist createShoplist(String title) {

        realm = Realm.getDefaultInstance();
        realm.beginTransaction();
        Shoplist shoplist = new Shoplist(new RealmList<ListItem>(), title);
        realm.copyToRealm(shoplist);
        realm.commitTransaction();

        return shoplist;

    }

**Comment by Zhuinden** [comment]
1.) you open a new Realm instance that will never be closed, because you are not following https://realm.io/docs/java/latest/#controlling-the-lifecycle-of-realm-instances

2.) you return an unmanaged instance

-------

You would be returning managed instance like this:

``` java
public Shoplist createShoplist(˙Realm realm, String title) {
   Shoplist shoplist = new Shoplist(new RealmList<ListItem>(), title);
    try {
        realm.beginTransaction();
        shoplist = realm.copyToRealm(shoplist); // <-- !
        realm.commitTransaction();
    } catch(Exception e) {
        if(realm.isInTransaction()) {
            realm.cancelTransaction();
        }
        throw new RuntimeException(e);
    }
    return shoplist;
}
˙˙

**Comment by Muddz** [comment]
@Zhuinden Allright I will edit my realm codes now. But I actually close my Realm Instance when the MainActiviity's onDestroy is called.

**Comment by Zhuinden** [comment]
You should pass the Realm instance to the method, instead of creating new instance

**Comment by Muddz** [comment]
@Zhuinden Yeah thanks! That is what I'm changing now everywhere that i use Realm instances

**Comment by Muddz** [comment]
I have sovled it now and changed my methods according to your suggestions. Thanks!
