### ISSUE TITLE
BUG: Inserted sub-objects not being linked to parent object

### ISSUE THREAD

**Issue by marchy** [realm/realm-java#4187]
We have a simple scenario that we cannot seem to get working despite trying every approach we've seen in the docs/issue list.

We have two objects (Chat/Message), with chat having a list of messages:
NOTE: We use Kotlin
```
@RealmClass
class Chat, RealmModel {
    ....
    var messages = RealmList<Message>()
    ....
}

@RealmClass
class Message : RealmModel {
    @PrimaryKey
    lateinit var id:String
    ....
}
```

When we insert new Messages into the Chat the Message object is being inserted in the database correctly but the Chat object is not linked to it – despite the Message being inserted THROUGH the Chat object (definitely a bug)

We've verified in the Realm Browser and there are indeed no linked messages (ie: it's a persitence issue not a querying one)

Insertion code:
```
val chatService:ChatService = ....
val chatID:String = ...

// insertion code
val database:Realm = Realm.getDefaultInstance()
var message:Message = Message.fromJSON( dataJSON )
database.beginTransaction()
// message = database.copyToRealmOrUpdate( message ) // tried this too, makes no difference
val chat:Chat = chatService.getChatWithID( chatID )
// database.copyToRealmOrUpdate( chat ) // tried this too, makes no difference
chat.messages.add( message )
database.commitTransaction()
```

NOTE: We've also tried manually patching the object with JSON and we get the exact same effect (messages are updated, but chat does not have them linked)
```
val chatData:Map<String, Any?> = mapOf(
    "id" to chatID,
    "messages" to chat.messages.map{ ... conversion to JSON ... }
)
database.createOrUpdateObjectFromJson( Chat::class.java, JSONObject( chatData ))
database.commitTransaction()
```

**Comment by Zhuinden** [comment]
``` java
val database:Realm = Realm.getDefaultInstance()
var message:Message = Message.fromJSON( dataJSON )
database.beginTransaction()
val chat:Chat = chatService.getChatWithID( chatID )
message = database_inner.copyToRealmOrUpdate( message )
chat.messages.add( message )
database.commitTransaction()
```

**Comment by marchy** [comment]
@Zhuinden Tried that as well, no difference

**Comment by Zhuinden** [comment]
Well the only other thing I see is that `class Chat {` doesn't seem to implement `RealmModel`? But I write that up to the example being wrong.

Otherwise, what i posted should work

**Comment by marchy** [comment]
@Zhuinden sorry that's my copy/paste typo (simplifying our model here so I manually typed that out). But yeah I tried your approach and definitely doesn't work (thus the Realm bug).

The Message object gets inserted in the DB but no link is made on Chat (so therefore queries as 0 Messages). Not sure what else could be at play: could having all the properties on the classes set to "open" make a difference (perhaps runtime proxy generation?)

**Comment by Zhuinden** [comment]
That's worth a try; I don't know all the pitfalls of Kotlin unfortunately. I just know that what I posted should work in Java, assuming you listen to changes with RealmChangeListener.

**Comment by beeender** [comment]
@marchy 
I tested with our kotlin example, and adding to `RealmList` works fine. See https://github.com/realm/realm-java/blob/master/examples/kotlinExample/src/main/kotlin/io/realm/examples/kotlin/KotlinExampleActivity.kt#L158

Please notice there is a bug in the example and will be fixed by #4188 

My doubt is your `getChatWithID()` returns a unmanaged `RealmObject`, would you please share the code of that function? About managed VS unmanged see https://realm.io/docs/java/latest/#what-is-the-difference-between-a-normal-java-object-and-a-realm-object

**Comment by kneth** [comment]
@marchy I hope that the links above have help you to solve your problem.

**Comment by marchy** [comment]
Unfortunately they have not. This issue still persists. Please re-open.

**Comment by kneth** [comment]
@marchy Can you check if your objects are managed (there is a `isManaged()` method)?

**Comment by marchy** [comment]
Oh fantastic, didn't know about ```isManaged()```. Will get back to you on this by the end of this week (need to await the end of the current dev cycle as we moved on with a temporary hack/work-around for now)

**Comment by Zhuinden** [comment]
`isManaged()` was added in 2.x

**Comment by kneth** [comment]
@marchy May I close the issue?

**Comment by marchy** [comment]
@kneth please await us trying this out and confirming that it IS still an issue (from our code the object looks like it is indeed managed). We're still awaiting our current dev cycle to finish but testing is in our next sprint. We can then move forward on FIXING the issue as opposed to closing it unresolved.

**Comment by kneth** [comment]
@marchy Is it still an issue for you? Or can we close?

**Comment by beeender** [comment]
close due to no response.

**Comment by marchy** [comment]
Hey @kneth excuse us as our biz priorities changed and we ended up focusing fully on the iOS app for the last month. We’re now back on Android and confirmed this is still an issue (even in Realm 3.1.4).

We tried inlining the parent object fetching to be done on the same Realm instance as opposed to using 'copyToRealmOrUpdate', as well as trying to perform each of the two parts of it in a separate transaction.

```
// TRIED THIS
val database:Realm = Realm.getDefaultInstance()
var message:Message = Message.fromJSON( dataJSON )
database.beginTransaction()
val chat:Chat = database.where( Plan::class.java )
    .equalTo( "id", planID )
    .findFirst()
message = database.copyToRealmOrUpdate( message )
chat.messages.add( message )
database.commitTransaction()
database.close()
```

```
// ALSO TRIED THIS
val database:Realm = Realm.getDefaultInstance()
var message:Message = Message.fromJSON( dataJSON )
database.beginTransaction()
val chat:Chat = database.where( Plan::class.java )
    .equalTo( "id", planID )
    .findFirst()
message = database.copyToRealmOrUpdate( message )
database.commitTransaction()

database.beginTransaction()
chat.messages.add( message )
database.commitTransaction()
database.close()
```

What else could we try? Not being able to link simple parent-->child objects in a one-to-many is on a critical path and impacting the feasibility of our Realm adoption.

The only other thing that I can think of is we are performing this during our full sync operation where we are looping this on potentially hundreds/thousands of objects that come through. Nothing fancy going on there other than being in a loop.

```
val database:Realm = Realm.getDefaultInstance()
for( syncOperation:SyncOperation in pulledOperations ){
    when( syncOperation.entityType!! ){
        SyncOperation.OperationEntity.Chat -> {
            ....
        }
        SyncOperation.OperationEntity.Message -> {
            // code above
        }
    }
}
database.close()
```

We also tried creating a Realm instance inside each loop to the same effect. Side-question: Does this have adverse implications on performance or notifications that we should be avoiding?

```
for( syncOperation:SyncOperation in pulledOperations ){
    val database:Realm = Realm.getDefaultInstance()
    when( syncOperation.entityType!! ){
        SyncOperation.OperationEntity.Chat -> {
            ....
        }
        SyncOperation.OperationEntity.Message -> {
            // code above
        }
    }
    database.close()
}
```


**Lastly, our iOS/Cocoa implementation does the EXACT same thing and it works – ie: definitely a Realm Java bug.**

**Comment by Zhuinden** [comment]
I've used Realm quite a bit and I can guarantee that the following should work, in the sense that chat.messages should contain the newly added message 

```
database.beginTransaction()
val chat:Chat = database.where( Plan::class.java )
    .equalTo( "id", planID )
    .findFirst()
message = database.copyToRealmOrUpdate( message )
chat.messages.add( message )
database.commitTransaction()
```

If you're trying to access Chat from Message, then you're supposed to use LinkingObjects.

**Comment by marchy** [comment]
Nevermind guys, we chased this down to a separate issue.

We were incorrectly using 'copyToRealmOrUpdate' instead of 'createOrUpdateObjectFromJson' in our synching loop so partial updates to the Chat metadata was overriding the 'messages' relationship that WAS successfully set earlier in the loop and causing it to be emptied out.

Good to close this  👍🏻
