### ISSUE TITLE
Cannot be cast to io.realm.UserRealmProxyInterface

### ISSUE THREAD

**Issue by Ryokooo** [realm/realm-java#4189]
this is my model:
public class User extends RealmObject{
    @PrimaryKey
    private String id;
    private String name;
    ...
}
    when I save to Realm and it made an Exception that say ''model User cannot be cast to  io.realm.UserRealmProxyInterface "
    I do not know where is wrong?

**Comment by Zhuinden** [comment]
You need to show your Gradle plugin order and your classpath plugins

**Comment by Ryokooo** [comment]
when I add " apply plugin: 'android-apt' " in app/build.gradle  Realm can not work correctly until  remove it from my app .why?

**Comment by Zhuinden** [comment]
You need to apply `android-apt` before you apply `realm-android`

**Comment by kneth** [comment]
@Ryokooo Please take a look at https://realm.io/docs/java/latest/#installation

**Comment by Ryokooo** [comment]
@kneth I know, Thanks!

**Comment by Zhuinden** [comment]
Have you tried https://github.com/realm/realm-java/issues/3783#issuecomment-260578984 according to https://github.com/realm/realm-java/issues/3827 ?

**Comment by Ryokooo** [comment]
yes,it worked!thanks @kneth @Zhuinden
