### ISSUE TITLE
com.sun.tools.javac.code.Symbol$CompletionFailure: class file for rx.Observable not found

### ISSUE THREAD

**Issue by xiang23** [realm/realm-java#4197]
Maybe because of i used rxjava2 instead of rxjava1  in my project ?  
Are there any solutions ?

Realm version(s): 2.2.2
Android Studio version: 2.2.3

**Comment by Zhuinden** [comment]
Create a package called `rx` and create an empty class in it called `Observable`

**Comment by xiang23** [comment]
@Zhuinden It works! Thanks for you!
