### ISSUE TITLE
java.lang.IllegalArgumentException: Configurations cannot be different if used to open the same file. The most likely cause is that equals() and hashCode() are not overridden in the migration class

### ISSUE THREAD

**Issue by AndroidJohnsonWang** [realm/realm-java#4199]
Test phone:SUNSUNG S7 EDGE
OS: android 6.0
Realm :2.3.1
I want to create a different database for different users in my application.
Here's my code.
![qq 20170220100030](https://cloud.githubusercontent.com/assets/15881869/23109349/7332a874-f753-11e6-9a84-0c5051d2581f.png)

**Comment by zaki50** [comment]
Hi @AndroidJohnsonWang As the message said, you must override `MyMigration#equals()` and `DefaultMigration#equals()` correctly.

Those method must return true if the two migration instance is for the same realm file.

One simple implementation is just checking the class.
```
public class MyMigration {
    @Override
    public boolean equals(Object other) {
        if (other == null) {
            return false;
        }
        return getClass() == other.getClass();
    }

    @Override
    public int hashCode() {
        return getClass().hashCode();
    }
}
```

**Comment by AndroidJohnsonWang** [comment]
@zaki50 Thank you for solving my problem.Success!
