### ISSUE TITLE
RealmList of RealmLists

### ISSUE THREAD

**Issue by DougSteiert** [realm/realm-java#4205]
I am a graduate student studying mobile smartphone location privacy. I have been using Realm since last semester with storing data in my application. Part of my project, though, is simulating mobility traces, semantically, that a user can take. In such a case, I already create a RealmList which contains place names and their coordinates. However, each location that samples a simulated mobility trace has its own RealmList of attributes. I want to be able to store each RealmList into a list for storage functionality so that I can always cycle through the main storage list and access each list within it to get values. As of now, I tried doing something of sorts, but I just lose too much information when trying to store the original RealmList as string values, basically.

Is there a workaround for this, maybe?

**Comment by Zhuinden** [comment]
I can't really figure out what you're doing without seeing the data model classes.

**Comment by DougSteiert** [comment]
Okay, didn't think that it would help much, since there is no such thing that exists to do what I want to do..

Here is one class I have to store data about objects:

`public class Semantics extends RealmObject {
    public String type;
    public double lat;
    public double lng;
    public String name;

    public String getType() {
        return type;
    }

    public String getName() {
        return name;
    }

    public Semantics setName(String placeName) {
        this.name = placeName;
        return this;
    }

    public Semantics setLng(double longitude) {
        this.lng = longitude;
        return this;
    }

    public double getLng() {
        return lng;
    }

    public Semantics setLat(double latitude) {
        this.lat = latitude;
        return this;
    }

    public double getLat() {
        return lat;
    }

    public Location getLocation() {
        Location location = new Location();
        location.setLong(lng);
        location.setLat(lat);

        return location;
    }

    public Semantics setType(String aType) {
        this.type = aType;
        return this;
    }
}`

I then have a public RealmList<Semantics> semanticTraces that holds each object. However, I basically want a RealmList<RealmList<Semantics>> mobilityTraces. Such that, for each spot within the outer RealmList, I can access a new RealmList made up of several traces.

**Comment by DougSteiert** [comment]
Just like having an ArrayList<ArrayLists> that Android supports. I have read a few comments about Realm saying they do not support it (and I believe I have tried), but I am just curious if people have gotten around this.

**Comment by Zhuinden** [comment]
Is this `Semantics` class supposed to have this `RealmList<RealmList<???>> mobilityTraces`?

**Comment by zaki50** [comment]
Hi @DougSteiert Realm currently does not support `RealmList` of `RealmList`.

One workaround is that defining a class which contains a list of `Semantics` like:

```
public class Trace extends RealmObject {
    public RealmList<Semantics> data;
}
```

And then define a class that have a list of `Trace`.

```
public class Container extends RealmObject {
    public RealmList<Trace> mobilityTraces;
}
```

**Comment by DougSteiert** [comment]
Thanks for that zaki. So in that case, for each spot of mobilityTraces, I could access another RealmList<Semantics> data object, and then in each spot of that data (per your notation), would be different places? If so, that seems perfect and not too difficult to maneuver.
