### ISSUE TITLE
Common prefix for Object Store Classes

### ISSUE THREAD

**Issue by beeender** [realm/realm-java#4215]
To match the same `Results` in Object Store.
Blame me. I made the confusing name.

Use common prefix `Os`

`Collection` -> `OsResults`
`SharedRealm` -> `OsSharedRealm`

**Comment by cmelchior** [comment]
`Collection` -> `OsResults` have been merged. Only missing `SharedRealm` -> `OsSharedRealm` now.

**Comment by beeender** [comment]
DONE
