### ISSUE TITLE
Row True No Longer Attached

### ISSUE THREAD

**Issue by DougSteiert** [realm/realm-java#4223]
I have recently been getting:
 
    02-22 13:02:08.346 28634-28634/com.djsg38.locationprivacyapp E/REALM_JNI: Row true is no longer attached!
    02-22 13:02:08.346 28634-28634/com.djsg38.locationprivacyapp E/REALM_JNI: jni: ThrowingException 8, Object is no longer valid to operate on. Was it deleted by another thread?, .
    02-22 13:02:08.346 28634-28634/com.djsg38.locationprivacyapp E/REALM_JNI: Exception has been throw: Object is no longer valid to operate on. Was it deleted by another thread?

I am not sure where it is coming from. Sometimes my code executes fine, other times it errors here and breaks my application. What are some common causes of this happening? Anytime I edit an object or delete from it, I check if it is empty (for deletion) and put it in a transaction. I am just so confused how an object could already be deleted?

For example, I would do at the beginning of each for loop to clear its contents:

    if(!trace.getSingleTrace().isEmpty()) {
            realm.beginTransaction();
            trace.getSingleTrace().deleteAllFromRealm();
            realm.commitTransaction();
     }

Should I may just do .clear()?

**Comment by Zhuinden** [comment]
What version of Realm is this?

**Comment by Zhuinden** [comment]
Oh, I've just realized. You've only shown 3 lines of code here, although there's a lot more going on around it. Most likely having a Results that gets some elements invalidated in the transaction, but it stays at its initial value.

Consider adding the rest of the code, and just do the entire write operation inside a single transaction instead of multiple ones.

**Comment by zaki50** [comment]
Hi @DougSteiert 
`beginTransaction()` updates all live objects to the latest version.

This means that `beginTransaction()` can change whether `trace.getSingleTrace().isEmpty()` is `true` or `false` .
You should check it again after `beginTransaction()`.

**Comment by DougSteiert** [comment]
Hey @Zhuinden and @zaki50 , instead of me pasting the code again (I will if you absolutely want it), you can refer to my other question [here](https://github.com/realm/realm-java/issues/4222)! This has most of the code that seems to be problematic - check within the for(XMLAttributes) section. Since I am trying to work with this Realm code after my other partner left the project, he last has to compile realm:android-adapters:1.4.0 and has realm-gradle-plugin:2.2.2. Maybe after looking at my code, you can help me out a bit more with what I may be doing wrong. I am doing my best to try to understand how to appropriately use Realm.

**Comment by zaki50** [comment]
@DougSteiert Moving the emptiness check into the transaction solved the error?

**Comment by DougSteiert** [comment]
@zaki50 I moved the transaction to begin before the for loop and end after it, as per the other thread you commented on, and I just got a "row true is no longer attached!" So it appears even checking for emptiness within the transaction did not fix it.

**Comment by DougSteiert** [comment]
Oh wait.. forgot I checked for emptiness of another object outside a transaction.

**Comment by Zhuinden** [comment]
No I'm pretty sure if you do these checks in a transaction, you can't end up with invalid objects unless your RealmResults you index one where the object got deleted.

**Comment by DougSteiert** [comment]
I understand that, I just do not know what is going on - it is still happening and that part is not debatable. I have tried creating possible a new Trace object each iteration of the for loop, to be stored in each spot of the Session RealmList, but now I am getting errors for checking isEmpty() on a null object reference, even will I add an empty value to the singleTrace List if a place is not stored.

**Comment by DougSteiert** [comment]
I might've found a problem. In the startup of the app, if the RealmObject "Trace" was not created, it would do such a thing. Then I would try to apply different transactions on it and such. However, I have deleted that part of creating it, since I do not want that object to be auto-updating, I will manipulate as such, such as the Semantics class is. I still have the null reference issue now, though.

**Comment by Zhuinden** [comment]
If you create an unmanaged RealmObject, then you must also initialize its RealmList property manually.

**Comment by kneth** [comment]
@DougSteiert Maybe https://realm.io/docs/java/latest/#creating-objects isn't as clear as it should be. A managed object is an object which is created by either `copyToRealm()` or `createObject()` (or one of the many variants). Notice that `copyToRealm()` *returns* the managed object. Calling Realm methods with unmanaged (or Plain Old Java) objects as arguments will often be wrong.

**Comment by DougSteiert** [comment]
Oh okay! Yeah the documentation, for me, is a bit quirky to understand, but I also am not an expert on database usage. I will try to initialize the RealmList inside my unmanaged object and see how that helps. For some reason that just never crossed my mind, even though you have to initialize other Lists in Java. Thank you!

**Comment by DougSteiert** [comment]
It appears my initialization of RealmLists for unmanaged objects worked. I have gone through several runs of my application am no longer getting Row True errors as would happen every other run. Thank you so much for all of the help, guys!
