### ISSUE TITLE
Support for suppressing specific listeners from writes

### ISSUE THREAD

**Issue by beeender** [realm/realm-java#4225]
Similar issue from cocoa: https://github.com/realm/realm-cocoa/issues/3665

> The current fine-grained notifications approach makes it challenging to support scenarios where the UI is updated before the data model, rather than the reactive approach of the model being the canonical source of truth that the UI merely displays. The simplest motivating use-case is UITableView reordering; when using the built-in functionality for dragging rows around the delegate is merely notified of changes already displayed in the UI, and re-applying those changes in the collection notification block after the Realm is committed will corrupt the order to the UITV. Because notifications are coalesced, users can't reasonably filter out these redundant updates themselves. and even if they could it would be very easy to get wrong.

> We should expose a variant of `Realm.write(_:)` that would specify that the transaction should not produce notifications on the current thread, as the things they want to update with the notifications are already up-to-date. In addition, this variant of write transactions would block until all async notifications are ready and delivers them, since otherwise the UI could easily get "out of sync".

> An alternative approach would be to instead let the user pass in the tokens for notification blocks which they want to suppress. This is more flexible and makes it work with commits on a different thread from the notified thread, but maybe would make the API even more complex.

Generally speaking, this will be very useful for drag & drop on recycler views after #989 implementation.

The APIs would be something like:
`Realm.commitTransaction(RealmListener... listenersToSuppress);`
`Realm.executeTransaction(TransactionBlock transaction, ErrorCallback, SuccessCallback, RealmListener... listenersToSuppress)`

To implement that a few things need to be considered:
* The same listener could be applied to different RealmResults, the have to be suppressed all.
* For the collection listener, current implement in JIN only holds one `NotificationToken` for every collection. That has to be refactored to holding different tokens for different listeners on the same collection.
* How does this work with row notifications?

**Comment by cmelchior** [comment]
I'm not entirely convinced we need this at all if we trigger notifications on `commitTransaction()`. See https://github.com/realm/realm-java/issues/4245#issuecomment-282432206

**Comment by beeender** [comment]
We choose to use a different approach to solve this. See #4368
