### ISSUE TITLE
Add Release Date to changelog

### ISSUE THREAD

**Issue by anotherdev** [realm/realm-java#4227]
Similar to [realm-cocoa changelog](https://github.com/realm/realm-cocoa/blob/master/CHANGELOG.md), would it be possible to add the release date of each version in the [realm-java changelog](https://github.com/realm/realm-java/blob/master/CHANGELOG.md).

**Comment by zaki50** [comment]
Hi @anotherdev That's a good idea.

I've updated release documentation and created a PR to add release date to CHANGELOG.

**Comment by zaki50** [comment]
I'll close this.
You can see the release date on the `CHANGELOG.md` at the next release.
