### ISSUE TITLE
Read , write data are not synchronized with RXJAVA2

### ISSUE THREAD

**Issue by Kyba1985** [realm/realm-java#4229]
Hi, i'm using Realm with RxJava2.

I'm using mvp pattern with interactors.

the atomic operations of getlist and addorupdate are not synchronized, when i get the list of objects and go in to the detail of object and change it, when i return back to the list and reload the data with a query the object changed is not in synk. The strange thing is after the update operation, if i go forward and backward from list to detail , one time i see the object updated and i time no...  

If i remove close in the finally block i have this problem, if i remain close instruction the app crash with: 
java.lang.IllegalStateException: This Realm instance has already been closed, making it unusable.

The operations are executed in background thread of Schedulers.io() and observed in main thread.

The only way at the moment to get the code works well is use main thread for both subsribeOn and observedOn and remove close in finally block, but i want only the results on the main thread.

Where is the problem?

the operations of get list and save:

    public Single<List<BookmarkEntry>> getBookMarkList() {

        return Single.create(new SingleOnSubscribe<List<BookmarkEntry>>() {
            @Override
            public void subscribe(SingleEmitter<List<BookmarkEntry>> e) throws Exception {
                Realm dbConnection = Realm.getDefaultInstance();
                try {
                    ArrayList<BookmarkEntry> entries = new ArrayList<BookmarkEntry>();
                    RealmResults<BookmarkEntry> result = dbConnection.where(BookmarkEntry.class).findAllSorted("title", Sort.ASCENDING);
                    for (BookmarkEntry entry : result) {
                        entries.add(dbConnection.copyFromRealm(entry));
                    }
                    e.onSuccess(entries);
                } catch (Exception ex) {
                    e.onError(ex);
                } finally {
                    dbConnection.close();
                }
            }
        });
    }

    public Single<BookmarkEntry> addOrUpdateEntry(final String title, final String url) {

        return Single.create(new SingleOnSubscribe<BookmarkEntry>() {
            @Override
            public void subscribe(final SingleEmitter e) throws Exception {
                Realm dbConnection = Realm.getDefaultInstance();
                dbConnection.executeTransaction(new Realm.Transaction() {
                    @Override
                    public void execute(Realm realm) {
                        try {
                            BookmarkEntry entry = new BookmarkEntry();
                            entry.setTitle(title);
                            entry.setUrl(url);
                            realm.copyToRealmOrUpdate(entry);
                            e.onSuccess(entry);
                        } catch (Exception ex) {
                            e.onError(ex);
                        } finally {
                            realm.close();
                        }
                    }
                });

            }
        });

    }

**Comment by zaki50** [comment]
Hi @Kyba1985 
You should not close Realm instance in `execute()` method.
Instead, you must close the instance right after `executeTransaction();`.

```
public Single<BookmarkEntry> addOrUpdateEntry(final String title, final String url) {
    return Single.create(new SingleOnSubscribe<BookmarkEntry>() {
        @Override
        public void subscribe(final SingleEmitter e) throws Exception {
            Realm dbConnection = Realm.getDefaultInstance();
            try { // added
            dbConnection.executeTransaction(new Realm.Transaction() {
                @Override
                public void execute(Realm realm) {
                    try {
                        BookmarkEntry entry = new BookmarkEntry();
                        entry.setTitle(title);
                        entry.setUrl(url);
                        realm.copyToRealmOrUpdate(entry);
                        e.onSuccess(entry);
                    } catch (Exception ex) {
                        e.onError(ex);
//                    } finally {
//                        realm.close();
                    }
                }
            } finally { // added
                dbConnection.close(); // added
            } // added
            });
        }
    });
}
```

**Comment by Kyba1985** [comment]
Hi @zaki50.

Yes, after a lot of try i get the correct composition of instructions. Thanks for support , use RXJava has added some problems in my work with realm :)

public Single<BookmarkEntry> addOrUpdateEntry(final String title, final String url) {

        return Single.create(new SingleOnSubscribe<BookmarkEntry>() {
            @Override
            public void subscribe(final SingleEmitter<BookmarkEntry> e) throws Exception {
                Realm dbConnection = null;
                try {
                    dbConnection = Realm.getDefaultInstance();
                    final BookmarkEntry entry = new BookmarkEntry();
                    entry.setTitle(title);
                    entry.setUrl(url);
                    dbConnection.executeTransaction(new Realm.Transaction() {
                        @Override
                        public void execute(Realm realm) {
                            realm.copyToRealmOrUpdate(entry);
                        }
                    });
                    e.onSuccess(entry);
                } catch (Exception ex) {
                    e.onError(ex);
                } finally {
                    if (dbConnection != null) dbConnection.close();
                }

            }
        });
