### ISSUE TITLE
Website header stuck in the middle of the screen on mobile

### ISSUE THREAD

**Issue by AOrobator** [realm/realm-java#4234]
Using Chrome and a Nexus 6P,  browsing the realm java documentation online,  I experience the following bug: When scrolling down, the header containing the version of Realm stays in the middle of the screen, instead of scrolling up like the top header. I've attached a screenshot for clarity. 
![screenshot_20170223-084323](https://cloud.githubusercontent.com/assets/4106884/23261552/bae9f3f4-f9a4-11e6-89b8-73af1bd2328f.png)

**Comment by cmelchior** [comment]
Hi @AOrobator 
Thanks for reporting it. I forwarded it to our webdevs.

**Comment by cmelchior** [comment]
This should have been fixed. Closing
