### ISSUE TITLE
duplicate entry: io/realm/DefaultRealmModule.class

### ISSUE THREAD

**Issue by SoNep** [realm/realm-java#4240]
#### Goal
working realm with different modules.

#### Expected Results
successful build

#### Actual Results
Error:Execution failed for task ':BlerterAndroid:transformClassesWithJarMergingForDebug'.
> com.android.build.api.transform.TransformException: java.util.zip.ZipException: duplicate entry: io/realm/DefaultRealmModule.class

#### Steps & Code to Reproduce
root gradle
` dependencies
    {
       classpath "io.realm:realm-gradle-plugin:2.3.1" 
    }`

in both module
`apply plugin: 'realm-android'`

`@RealmModule(classes = { UserRO.class})
public class MyModule {
}`

`@RealmModule(allClasses = true)
public class MainRealmModule
{
}
`

`public class TempRealm
{
    private static Realm farmRealm;
    private static RealmConfiguration farmAnimalsConfig;

    public void initRealm( Context context) {
        Realm.init( context );
        RealmConfiguration defaultConfig = new RealmConfiguration.Builder().build();
        farmAnimalsConfig = new RealmConfiguration.Builder()
                .name("farm.realm")
                .modules( Realm.getDefaultModule(), new MainRealmModule(), new MyModule())
                .build();
        Realm defaultRealm = Realm.getInstance(defaultConfig);
        Realm.setDefaultConfiguration( farmAnimalsConfig );
        farmRealm = Realm.getInstance(farmAnimalsConfig);
        Realm.deleteRealm( defaultConfig );
        Realm.deleteRealm( farmAnimalsConfig );
        StorageManager second = StorageManager.getInstance( context );
    }

    public static Realm getFarmRealm() {
        return  Realm.getInstance( farmAnimalsConfig );
    }
}`

#### Version of Realm and tooling
Realm version(s): 2.3.1

Android Studio version: 2.2.3

Which Android version and device:

**Comment by Kernald** [comment]
@SoNep did you actually solve your issue? I have pretty much the same situation, I would be interested in details.

**Comment by SoNep** [comment]
@Kernald No. we didn't and moved to room

**Comment by Kernald** [comment]
Okay, thanks. If anyone encounter the same issue, in my case, I forgot the `library = true` argument on the `@Module` annotation. Adding it (it defaults to `false` solved this duplicate entries exception. (It looks like you had the same issue in your code.)
