### ISSUE TITLE
RealmBasedRecyclerViewAdapter is not recycling views/refreshing when adding to list

### ISSUE THREAD

**Issue by Muddz** [realm/realm-java#4246]
I have a list that I can add items into, but the the inserted items do not show right away! I have to restart the app to see the changes. This is how I have implemented the Realm adapter for my Realm Recyclerview. 

    public class RealmlistAdapter extends RealmBasedRecyclerViewAdapter<ListItem, RealmlistAdapter.Viewholder> {

    private String valutaSign;
    private RealmResults<ListItem> realmResults;

    public RealmlistAdapter(Context context, RealmResults<ListItem> realmResults, String valutaSign) {
        super(context, realmResults, true, false);
        this.valutaSign = valutaSign;
        this.realmResults = realmResults;
    }

    public void setValutaSign(String valutaSign) {
        this.valutaSign = valutaSign;
        notifyDataSetChanged();
    }

    

    @Override
    public Viewholder onCreateRealmViewHolder(ViewGroup viewGroup, int i) {
        View rootView = inflater.inflate(R.layout.item_product, viewGroup, false);
        return new Viewholder(rootView);
    }

    @Override
    public void onBindRealmViewHolder(Viewholder viewholder, int i) {

        final ListItem listItem = realmResults.get(i);

        viewholder.title.setText(listItem.getTitle());
        viewholder.title2.setText(listItem.getLocation() + " " + Utils.getFormattedPrice(listItem.getPrice()) + " " + valutaSign);
        viewholder.checkBox.setChecked(listItem.getIsBought() == 1);
    }

    public static class Viewholder extends io.realm.RealmViewHolder {

        @BindView(R.id.item_list_textview1)
        TextView title;
        @BindView(R.id.item_list_textview2)
        TextView title2;
        @BindView(R.id.item_list_checkbox)
        CheckBox checkBox;
        @BindView(R.id.item_list_menuBtn)
        ImageButton imageButton;

        public Viewholder(View itemView) {
            super(itemView);
            ButterKnife.bind(this, itemView);

        }
    }

    }

**Comment by Zhuinden** [comment]
How do you add into the list?

**Comment by Muddz** [comment]
@Zhuinden  Like this via a presenter:


    public void add(String title, String location, double price, long listId) {

        Shoplist shoplist = realm.where(Shoplist.class).equalTo(Shoplist.ID, listId).findFirst();
        shoplist.addItem(realm, title, location, price);
    }


But strangely it works normally again

**Comment by Zhuinden** [comment]
where do you begin/commit the transaction?

**Comment by Muddz** [comment]
Shoplist is a object containg af RealmList<Listitem>
and in the Shoplist class I have this add method for the ListItem


    public void addItem(Realm realm, final String title, final String location, final double price) {
        realm.executeTransaction(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {
                ListItem listItem = realm.createObject(ListItem.class, System.currentTimeMillis());
                listItem.setTitle(title);
                listItem.setLocation(location);
                listItem.setPrice(price);
                itemList.add(listItem);
            }
        });
    }

**Comment by Zhuinden** [comment]
@muddz have you tried using `realm.executeTransactionAsync()`?

**Comment by Muddz** [comment]
@Zhuinden No. But I will try to recreate the issue again and try with async and see if that helps

**Comment by Zhuinden** [comment]
Wait a second... `RealmBasedRecyclerViewAdapter` is not Realm's own recyclerview adapter.

Consider using https://github.com/realm/realm-android-adapters

**Comment by Muddz** [comment]
@Zhuinden aaah I was of the impression that it was, from a tutorial I read!

Thanks I will implement the officiel one
