### ISSUE TITLE
UnsatisfiedLinkError: Native method not found: io.realm.log.RealmLog.nativeLog

### ISSUE THREAD

**Issue by jahs4488** [realm/realm-java#4260]
#### Goal

> enabling automatic synchronization of data across devices

#### Expected Results

> synchronization of data across devices

#### Actual Results

>  FATAL EXCEPTION: main
Process: dom.mx, PID: 22340
java.lang.RuntimeException: Unable to start activity ComponentInfo{dom.mx.activities.SplashActivity}: UNKNOWN(-1)
 java.lang.UnsatisfiedLinkError: Native method not found: io.realm.log.RealmLog.nativeLog:(ILjava/lang/String;Ljava/lang/Throwable;Ljava/lang/String;)
at io.realm.log.RealmLog.nativeLog(Native Method)
at io.realm.log.RealmLog.log(RealmLog.java:371)
at io.realm.log.RealmLog.debug(RealmLog.java:233)
at io.realm.log.RealmLog.debug(RealmLog.java:222)
at io.realm.internal.network.OkHttpAuthenticationServer.authenticate(OkHttpAuthenticationServer.java:109)
at io.realm.internal.network.OkHttpAuthenticationServer.loginUser(OkHttpAuthenticationServer.java:53)
at io.realm.SyncUser.login(SyncUser.java:189)

#### Steps & Code to Reproduce

> I have the following code in an activity:

#### Code Sample

```java

> SyncCredentials myCredentials = SyncCredentials.usernamePassword("email@mail.com", "test", false);
        SyncUser user = SyncUser.login(myCredentials, "http://server-realm:9080/auth");
        UserManager.setActiveUser(user);
        SyncConfiguration configuration = new SyncConfiguration.Builder(user, "realm://server-realm:9080/~/realm").build();

```

#### Version of Realm and tooling
Realm version(s): realm-gradle-plugin:2.3.0

Realm sync feature enabled: yes

Android Studio version: 2.2.3

Which Android version and device: 
Android 4.4 - device Samsung Galaxy SM-A300M
Android 5.1 - device Samsung Galaxy SM-J700M

**Comment by Zhuinden** [comment]
You either also have an old version of Realm in the dependencies, or instant run / incremental build is messing with you and you need to clean / rebuild.

**Comment by cmelchior** [comment]
Or possible your are trying to log something before calling `Realm.init()`

**Comment by jahs4488** [comment]
# The solution is: 
> Realm.init();
# Thanks
