### ISSUE TITLE
Adding RealmQuery#distinctAsync for multiple fields 

### ISSUE THREAD

**Issue by zaki50** [realm/realm-java#4269]
We currently have distinct methods in `RealmQuery` class.
```
public RealmResults<E> distinct(String fieldName)
public RealmResults<E> distinctAsync(String fieldName)
public RealmResults<E> distinct(String firstFieldName, String... remainingFieldNames)
```

We should provide `public RealmResults<E> distinctAsync(String firstFieldName, String... remainingFieldNames)` as well.

**Comment by beeender** [comment]
the `distinctAsync()` will be removed soon. Refer to https://github.com/realm/realm-java/pull/5568
