### ISSUE TITLE
Language problem

### ISSUE THREAD

**Issue by yusufozcan** [realm/realm-java#4271]
I am working on an Arabic dictionary but query functions (e.i. equalTo(), contains() etc) not working with arabic parameters. 

`query.contains("normal", "خرج");
`
this always returns empty ResultList. There is no structural mistake. If I try other fields it is working as desired.

#### Version of Realm and tooling
Realm version(s): 3.0

Realm sync feature enabled: no

Android Studio version: latest

Which Android version and device: emulator

**Comment by yusufozcan** [comment]
Sorry. I have mistake with the values in database. I discovered after iterating my docs.

**Comment by zaki50** [comment]
@yusufozcan Can I close this?

**Comment by yusufozcan** [comment]
Yes. I solved my problem completely. Sorry for this topic.
