### ISSUE TITLE
Between, greaterThan, lessThan... ISO date support

### ISSUE THREAD

**Issue by atouchsimo** [realm/realm-java#4283]
Hi guys
Is there a ``possibility`` to  support iso date on :)
- ``between()``
- ``greaterThan()``
- ``lessThan()``
- ``greaterThanOrEqualTo()``
- ``lessThanOrEqualTo()``

**Comment by Zhuinden** [comment]
Why not store date as `Date`?

**Comment by atouchsimo** [comment]
The api already returns ``ISO String`` saving it as ``Date`` needs to for loop each item and convert each ``ISO String`` field value to ``Date``

**Comment by cmelchior** [comment]
Hi @atouchsimo . Doing that conversion for each query would be so much more expensive than you doing the conversion when inserting data into Realm. Also it would slow down any query as we would have to check if the input string was a ISO date.

So this is not something we would want to do. The `Date` data type was meant for this type of thing after all.

Note you can just do the conversion in your model classes

```
public Foo extends RealmObject {
  private Date date;
  SimpleDateFormat inFormat = new SimpleDateFormat("yyyy-MM-dd'T'HH:mm:ssZ"); // Needs to be thread-local. It is not thread safe.

  public void setDate(String date) {
    date = inFormat.parse(date);
  } 
}
```

**Comment by Zhuinden** [comment]
This really is why I tend to say, it's best to keep API objects and RealmObjects separate.

**Comment by nolanamy** [comment]
@cmelchior How about `between`/`lessThan`/`greaterThan` support for `String`s?

**Comment by Zhuinden** [comment]
So what exactly would it mean to be `between` two strings?

**Comment by nolanamy** [comment]
Well... `greaterThan` one and `lessThan` the other, I suppose 😏

I'd like to use it to grab a series of alphabetically-sorted chunks from a collection. If we can sort on a type (like `String`), then we should be able to comparison-query on it too.

**Comment by sandeepbol** [comment]
How do we check if a Date stored in realm is greater than today (new Date()) @Zhuinden ?
