### ISSUE TITLE
How to migrate the data from Sqlite to Realm

### ISSUE THREAD

**Issue by longph92** [realm/realm-java#4284]
Hi there,
I have the data with Sqlite but now I need to migrate it into Realm for easier to manage. So is there any easy way to do that?

**Comment by Zhuinden** [comment]
Typically by creating the RealmObjects and storing the data into those instead.

SQLite is sql-based and relational, while Realm is an object store. So any migration between the two cannot be automatic, because the schema works differently.

**Comment by kneth** [comment]
The Realm Browser (for macOS) can import data from CSV files. SQLite is a relational database, and combining two tables is done ny joining the tables. Being an object database, Realm's approach is different and you will have to create links/relationship between objects manually.
