### ISSUE TITLE
Incorrect documentation

### ISSUE THREAD

**Issue by osheral** [realm/realm-java#4288]
In Java doc, code for sync is :
SyncUser user = getUserFromLogin();
String serverURL = "realm://my.realm-server.com/~/default";
SyncConfiguration configuration = new SyncConfiguration.Builder(user, serverURL).build();

whereas it should be 
String serverURL = "realm://my.realm-server.com:**9080**/~/default";

**Comment by kneth** [comment]
Thanks! I have created a PR against our internal documentation repository so it should be online soon.
