### ISSUE TITLE
Expose Permission Realm

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#4296]
Expose the Permission Realm in a similar way to Cocoa: https://github.com/realm/realm-cocoa/pull/4563

See https://docs.google.com/document/d/1RN6xFxtnBFZQaIuJ3rBXFmxxOjDM3ftZcrJn5Pv2shw/edit

**Comment by cmelchior** [comment]
Note the scope of this has changed and we should implement the nicer Permission Wrappers instead: https://github.com/realm/realm-cocoa/pull/4799

**Comment by Zhuinden** [comment]
Wait a sec, if Permission Realm is not in yet, then what is `Added support for `PermissionOffer` and `PermissionOfferResponse` to `SyncUser.getManagementRealm()`.`?

Or is this a completely different thing?

**Comment by cmelchior** [comment]
It is a different thing.

**Comment by Zhuinden** [comment]
Is this the thing needed to share a Realm between two specific users, but not globally to everyone?
