### ISSUE TITLE
Add notIn predicate support to queries

### ISSUE THREAD

**Issue by consp1racy** [realm/realm-java#4297]
#### Goal

In one go I'd like to select/delete all entities whose `field` value is *not in* a supplied set of values. An inverse function to `RealmQuery.in(String, T[])`.

#### Expected Results

Such `notIn` function would have the same signature as preexisting `in` function.
It would be great if it supported empty (non-null) input (the `in` function throws in such case).

#### Current approach

```
fun <E : RealmModel> RealmQuery<E>.notIn(fieldName: String, values: Array<Int>): RealmQuery<E> {
    values.forEach {
        notEqualTo(fieldName, it)
    }
    return this
}
```

**Comment by carotorrehdz** [comment]
+1

**Comment by carotorrehdz** [comment]
I also need a feature like this, but I could achieved it without needing a for loop. 
You just have to add `not()` to your`in(..)` condition.
Like this:

``` java
query.not().in(fieldName, values);
```

**Comment by consp1racy** [comment]
🤦‍♂️  Thank you :smile:
