### ISSUE TITLE
copyToRealmOrUpdate do not work correct 

### ISSUE THREAD

**Issue by af-abe** [realm/realm-java#4298]
#### Goal

I want to insert or update a RealmObject with a PrimaryKey. After that I wannt to load that Object in a other Thread via Android Loader or AsyncTask.

#### Expected Results
I get the inserted or updated Object.

#### Actual Results

I get sometimes the old one. And if I load again I can get the new one or the old one.
This Bug happens on Loader more then in AsyncTasks.

video: https://drive.google.com/file/d/0B6QlbCWj5PHtNDR2dl8tNldxVEE/view?usp=sharing

#### Steps & Code to Reproduce
run the test App:
https://github.com/af-abe/realm_test/tree/master/RealmTest

#### Code Sample
how i insert the Object:
```
 Realm realm = Realm.getDefaultInstance();
        final Model m = new Model();
        m.setBla(text.get());
        m.setId(1L);
        realm.executeTransaction(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {
                  realm.copyToRealmOrUpdate(m);
            }
        });
```
```

#### Version of Realm and tooling
Realm version(s): 2.3.2 and 3.0.0

Realm sync feature enabled: no

Android Studio version: 2.3

Which Android version and device: all

**Comment by Zhuinden** [comment]
Well yes, you never close your Realm instance on the AsyncTaskLoader's non-looping background thread ( [src](https://github.com/af-abe/realm_test/blob/master/RealmTest/app/src/main/java/appsfactory/de/realmtest/Loader.java#L19-L26) ), so the Realm version gets retained at an older version and will never be able to update.

Solution, close the Realm instance

**Comment by af-abe** [comment]
realm.close(); after the executeTransaction-blog dose not help ;-(

**Comment by af-abe** [comment]
ok, if i close on each block where i get the instanc, than it work correct. thanks
