### ISSUE TITLE
Deleted RealmObjects appears again when I query them

### ISSUE THREAD

**Issue by Muddz** [realm/realm-java#4302]
I have an App where the user can create a `Shoplist` (RealmObject), that Shoplist has a `RealmList<ListeItem>` member variable which is the one users add items into.

Now If you delete theese `Shoplist` Realm objects then `RealmList<ListItem>` all object in that list should also be deleted. But when the user press on a `Show All` button which shall show all current objects of `ListItem` then all these that have been deleted before shows up:

**The Show All button's code:**

     //Creates the Shoplist objects of all ListItem.class objects or Updates it when calledd
     private void createOrUpdateAll() {
        realm.executeTransaction(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {
                if (getShowAll() == null) {
                    showAll = realm.createObject(Shoplist.class, Long.MAX_VALUE);
                    showAll.setTitle("ALL ITEMS");
                    showAll.setItemList(null);

                } else {
                    getShowAll().setItemList(getList());
                }
            }
        });
    }

    //Creates a List of all existing Item.class objects and return it
    private RealmList<ListItem> getList() {

        RealmList<ListItem> listItems = new RealmList<>();

        for (int i = 0; i < realm.where(ListItem.class).count(); i++) {
            listItems.add(realm.where(ListItem.class).findAll().get(i));
        }
        
        return listItems;
    }

**The code for adding List items to the `RealmList<ListItem>`:**

     public void add(String title, String location, double price, long listId) {

        Shoplist shoplist = realm.where(Shoplist.class).equalTo(Shoplist.ID, listId).findFirst();
        shoplist.addItem(realm, title, location, price);
    }

**The addItem method In the Shoplist.class:**

    public void addItem(Realm realm, final String title, final String location, final double price) {
        realm.executeTransaction(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {
                ListItem listItem = realm.createObject(ListItem.class, System.currentTimeMillis());
                listItem.setTitle(title);
                listItem.setLocation(location);
                listItem.setPrice(price);
                itemList.add(listItem);
            }
        });
    }

**And this is how the items gets deleted (should get deleted):**

    public void deleteAllFromList(Realm realm) {
        realm.executeTransaction(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {
                itemList.deleteAllFromRealm();
            }
        });
    }

**Comment by Zhuinden** [comment]
Because you're supposed to be using `RealmResults` with `RealmChangeListener` instead of creating unmanaged `RealmList` into which you add each item while creating N query results for N items

**Comment by Muddz** [comment]
@Zhuinden Hi. I think either we misunderstand each other or I didn't make my issue clear.
I made a video demo that better describes the problem [Video Demo](https://www.youtube.com/watch?v=UA5xLDr5xFQ)

Please take a look.

**Comment by Zhuinden** [comment]
You're not supposed to have `new RealmList<>()` like this in your code, unless you are setting up relationship, which you aren't.

**Comment by Muddz** [comment]
@Zhuinden Are you referring to the code at line 2?



    private RealmList<ListItem> getList() {

      //----->  RealmList<ListItem> listItems = new RealmList<>();   <----

    for (int i = 0; i < realm.where(ListItem.class).count(); i++) {
        listItems.add(realm.where(ListItem.class).findAll().get(i));
    }
    
    return listItems;
}

**Comment by Zhuinden** [comment]
Yes.

**Comment by Muddz** [comment]
@Zhuinden  I dont think that's the problem. Did you see the video?

The only thing that is bothering me is that when I delete a `Shoplist.class` object then its `RealmList<ListItem>` is not deleted. 

Proces: 

1 - Creating 2 `Shoplist.class` objects
2- Add items to their `RealmList<ListItem> list`
3 - Delete both `Shoplist.class` objects
4 - Call the Show All method and wupti. The supposed deleted objects of `ListItem` are stil there


**Show All method**

    private RealmList<ListItem> getList() {
        RealmList<ListItem> listItems = new RealmList<>();
        RealmResults<ListItem> itemResult = realm.where(ListItem.class).findAll();

        for (int i = 0; i < itemResult.size(); i++) {
            listItems.add(itemResult.get(i));
        }

        return listItems;
    }

Now this has to be a `RealmList` because when I call `getList()` I use it to update `RealmList<ListItem>` of the  `Show All (Shoplist.class)` object like that:


     private void createOrUpdateAll() {
        realm.executeTransaction(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {
                if (getShowAll() == null) {
                    showAll = realm.createObject(Shoplist.class, Long.MAX_VALUE);
                    showAll.setTitle("ALL ITEMS");
                    showAll.setItemList(new RealmList<ListItem>());

                } else {
                     //Update the RealmList<ListItem> with the `getList()`
                    getShowAll().setItemList(getList());
                }
            }
        });
    }

**Comment by Muddz** [comment]
Btw I do use RealmRecyclerAdapter 

and in Shoplist.class I get the data I need for the RecyclerView like this:

     public RealmResults<ListItem> getItems(String listOrder) {
        RealmResults<ListItem> results;
        results = itemList.where().findAll();


        switch (listOrder) {
            case PrefActivity.ASCENDING:
                results = results.sort(ListItem.TIME_STAMP, Sort.ASCENDING);
                break;
            case PrefActivity.ASCENDING_ABOVE:
                results = results.sort(ListItem.IS_BOUGHT, Sort.DESCENDING);
                break;

            case PrefActivity.ASCENDING_BELOW:
                results = results.sort(ListItem.IS_BOUGHT, Sort.ASCENDING);
        }

        return results;
    }

**Comment by Zhuinden** [comment]
> Now If you delete theese Shoplist Realm objects then RealmList<ListItem> all object in that list should also be deleted. But when the user press on a Show All button which shall show all current objects of ListItem then all these that have been deleted before shows up:

If you delete a ShopList item, you need to manually delete its list first

see https://github.com/realm/realm-java/issues/1104

**Comment by kneth** [comment]
I am closing the issue as @Zhuinden has provided excellent answers.

**Comment by Muddz** [comment]
@Zhuinden  Thank you for your effort and time. I appreciate that alot. 

Anyway I just solved my problem with just a extra line on my current code:

This is inside my `RecyclerView` adapter when a Shoplist is deleted. So before I delete the Shoplist objects, I delete first their `RealmList<ListItem>` and it works! 

                    realm.executeTransaction(new Realm.Transaction() {
                        @Override
                        public void execute(Realm realm) {
                            getData().get(getAdapterPosition()).getItemList().deleteAllFromRealm();
                            getData().get(getAdapterPosition()).deleteFromRealm();
                        }
                    });

**Comment by Muddz** [comment]
@Zhuinden Is it because Realm keeps a strong reference to nested RealmObjects like in this case?
