### ISSUE TITLE
Realm Database viewer/brower for windows machine

### ISSUE THREAD

**Issue by SachinRana028** [realm/realm-java#4303]
Hi All,
I want know is there any database viewer for windows. If, yes could you guys point me to the link from where I can get that. If, no then how I can view database on windows machine.
Regards

**Comment by kneth** [comment]
@SachinRana028 Currently we only have Realm Browser for macOS but we hope that we can provide a browser fr other operating systems soon.

**Comment by iamdangerous** [comment]
Hey @SachinRana028 check this StackOverflow's post [http://stackoverflow.com/questions/28478987/how-to-view-my-realm-file-in-the-realm-browser/34187414#34187414](url) regarding usage of Stetho Realm or their official link [https://github.com/uPhyca/stetho-realm](url) . Hope this helps

**Comment by Zhuinden** [comment]
(  http://stackoverflow.com/questions/28478987/how-to-view-my-realm-file-in-the-realm-browser/34187414#34187414 )
