### ISSUE TITLE
Realm Mac browser not showing the same data type for table columns.

### ISSUE THREAD

**Issue by Sachin-MTN** [realm/realm-java#4308]
Hi, I have created a table in android like this: 

public class label_type extends RealmObject {
    @PrimaryKey
    private long id;
    @Required
    private String label;
    private long updated;
    public label_type() {
    }
}

When I am opening my database in mac browser its showing field type int for long type fields.

Here is the attached screenshot for the above table from realm mac browser.

(https://cloud.githubusercontent.com/assets/25761572/23792828/9c1942b6-05ae-11e7-8c1d-9863e76d589f.png)

Could you please point out what I am doing wrong or what's the right approach for creating a table with above field so that I can get expected result.

Thanks

**Comment by kneth** [comment]
Realm Core has only one column type for integers, and Realm Java (and other products) maps all integer types (`short`, `int`, `long`, etc.) to that column type. Realm Browser does not know your model class' declaration, and shows the type as `int`.
