### ISSUE TITLE
Realm API Below 19

### ISSUE THREAD

**Issue by nikiizvorski** [realm/realm-java#4312]
realm.createObject doesn't do anything in background and does work as intended on api 19 and above! I think something is simply replaced or missed to be added!

Realm works and it works pretty well the only problem is with devices below API 19.

I think it simply doesn't do anything when you ask it to create an object and the other thing i found is

That just show you only one result from the whole DB and replace it in RealResultAdapter.

RealmAdapter -> Above API 19 show all

Realm Adapter -> Below API 19 show only one element

Realm Create -> Works properly Abobe 19

Realm Create -> Not working at all some times replace old object which is only 1.

Android Studio: latest
Realm: latest

**Comment by Zhuinden** [comment]
Please post actual example code that reproduces the problem, I tend to run my code in API 17 emulator and have never seen this problem

**Comment by nikiizvorski** [comment]
Sure 

Realm.createObject();

Make a couple objects on API 16, 17 and show them with RealmBaseAdapter as ListView well you get only one item. Which is constantly replacing it self.

**Comment by beeender** [comment]
@nikiizvorski Can you make a sample project to reproduce the problem? I tried with API 16,17 and it works fine.

**Comment by kneth** [comment]
I am closing the issue. If you create a sample project which can reproduce it, we will reopen it.

**Comment by nikiizvorski** [comment]
Well it is not a problem for me i told you before:

Realm.createObject();

API 16 is the problem i have no problems with the other API 19 and above!

**Comment by Zhuinden** [comment]
API 16?

Do you by chance know which device? There's a list of some broken Samsung devices with an error in native function call `std::memcpy` which will get fixed in next version.

**Comment by nikiizvorski** [comment]
Well yep a couple Samsung devices and a couple Emulators on Google:

- GT-I8262

- GT-I8190

- GT-P3100

- Lenovo A319

There are more but main problem was that RealmResultAdapter just show one item and the DB for those devices that are API 16 have only one item in it. And it is constantly replacing it self. Or the app just crash that is what happens. It is working pretty well on everything that is above API 19.

**Comment by Zhuinden** [comment]
I think https://github.com/realm/realm-java/pull/4402 will fix this, stay tuned
