### ISSUE TITLE
Document `@LinkingObject`s in the documentation website

### ISSUE THREAD

**Issue by bmeike** [realm/realm-java#4320]
#### Goal

@LinkingObjects easily and correctly used

-----
### Tasks
- [ ] Update website documentation.
- [ ] Doc: Multiple links from instance A to instance B cause B to have multiple backlinks (on @LinkingObjects annotation).

#### Version of Realm and tooling

Realm version(s): 3.1

**Comment by kneth** [comment]
The website documentation is updated but waits to be merged (prior to release).
