### ISSUE TITLE
@LinkingObjects fields should be validated against libraries on the classpath, at compilation

### ISSUE THREAD

**Issue by bmeike** [realm/realm-java#4322]
#### Goal

Early notification of `@LinkingObjects` errors

`@LinkingObjects` fields are verified against sources that are part of the same compilation unit.  They are verified, again, at runtime.  They are not checked, at compile time, against sources that are in libraries (.jar).  They should be.

-----
### Tasks
- [ ] Backlink verification is incomplete.  Evil code can cause native crashes.
- [ ] Compile time errors for malformed backlinks in libraries.

#### Version of Realm and tooling
Realm version(s): 3.1

**Comment by zaki50** [comment]
Do we need to do this?
If the model is not included current classpath, no way to compile the app/library.

**Comment by beeender** [comment]
This might be related with the ongoing work for Object Store schema integration.

**Comment by bmeike** [comment]
I don't think this really involves the ObjectStore Integration.  The problem can occur that a @LinkingObject declaration depends on something that is not part of the current compilation unit.  In the general case this will break at runtime.  We *can* though, catch things like those tested by the LinkingObjectsManagedTests (I believe those tests would pass, if updated).  We also can (and should) catch errors in libraries that are present at compile time.
I think I can do this pretty quickly, so I'm going to take it.

**Comment by bmeike** [comment]
@zaki50 : have a look at those tests if you want to see how it can happen.

**Comment by beeender** [comment]
@bmeike the checking has been done in https://github.com/realm/realm-java/pull/4960 . It will throw the first time when user open the Realm instance. And i think it is good enough since user cannot open a Realm instance if the backlink is wrong. Also please notice, the proxy file will be changed a lot after the Object Store schema integration. So i you really want to do compile time checking, would you please do it after my Object Store schema work done?

**Comment by beeender** [comment]
Also please notice that since we have `RealmProxyMediator`, user can dynamically change the set of Realm Object to be used. I don't think there is an easy way to do the checking during the compile time. Again, i think #4960 is enough.

**Comment by bmeike** [comment]
Let me have a look.  I will, absolutely, not interrupt your OS work.  If I make changes, I'll do them after you commit.
... and I agree that it is not easy.  But that's not a great excuse...

**Comment by bmeike** [comment]
I'm going to put this on hold until after @beeender's stuff gets checked in.

**Comment by beeender** [comment]
This has been checked at runtime immediately when user open the first Realm instance in the Object Store with a clear exception message. Should be enough.
