### ISSUE TITLE
Move the Java bindings to use ObjectStore schema

### ISSUE THREAD

**Issue by bmeike** [realm/realm-java#4324]
This will allow removing boatloads of code from Proxy table initialization and verification.

**Comment by cmelchior** [comment]
Work is already under way here: #3066

**Comment by Zhuinden** [comment]
Is this related to https://github.com/realm/realm-java/pull/4674?

**Comment by Zhuinden** [comment]
...and to https://github.com/realm/realm-java/pull/4887 , I guess.

I wonder if that's the last step.

**Comment by beeender** [comment]
#4887 merged
