### ISSUE TITLE
Error:Execution failed for task ':introExample:transformClassesWithRealmTransformerForDebug'. > utf-8-

### ISSUE THREAD

**Issue by kaushik1221** [realm/realm-java#4325]
I am getting this error on Running realm standalone examples. I have new OS ubuntu 16.04 and AndroidStudio 3.0

What I have tried till now:
Changed character encoding in android studio to UTF-8 everywhere.
Changed ubuntu locale to language with UTF-8 encoding everywhere.
Downloaded and installed new android studio as well as realm library package with examples.
Cleaned project, re-build project, invalidate catches and restarted android studio.

Error in Detail:
```
Executing tasks: [:introExample:assembleDebug]

Configuration on demand is an incubating feature.
:introExample:preBuild UP-TO-DATE
:introExample:preDebugBuild UP-TO-DATE
:introExample:checkDebugManifest
:introExample:preReleaseBuild UP-TO-DATE
:introExample:prepareComGetkeepsafeRelinkerRelinker122Library
:introExample:prepareIoRealmRealmAndroidLibrary300Library
:introExample:prepareDebugDependencies
:introExample:compileDebugAidl UP-TO-DATE
:introExample:compileDebugRenderscript
:introExample:generateDebugBuildConfig UP-TO-DATE
:introExample:generateDebugResValues UP-TO-DATE
:introExample:generateDebugResources
:introExample:mergeDebugResources UP-TO-DATE
:introExample:processDebugManifest UP-TO-DATE
:introExample:processDebugResources
:introExample:generateDebugSources
:introExample:incrementalDebugJavaCompilationSafeguard
:introExample:javaPreCompileDebug
:introExample:compileDebugJavaWithJavac
Note: Processing class Cat
Note: Processing class Person
Note: Processing class Dog
Note: Creating DefaultRealmModule

:introExample:compileDebugNdk UP-TO-DATE
:introExample:compileDebugSources
:introExample:mergeDebugShaders
:introExample:compileDebugShaders
:introExample:generateDebugAssets
:introExample:mergeDebugAssets
:introExample:transformClassesWithRealmTransformerForDebug FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':introExample:transformClassesWithRealmTransformerForDebug'.
> utf-8-

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 4.972 secs
```

Error with Stack Trace option:

**Comment by Zhuinden** [comment]
> Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

**Comment by kneth** [comment]
We build our example on Linux boxes as part of CI, and we haven't seen this before. I'll try to build manually, and see how it goes.

**Comment by Zhuinden** [comment]
@kneth this looks similar to http://stackoverflow.com/questions/42732357/execution-failed-for-task-apptransformclasseswithrealmtransformerfordebug

**Comment by kneth** [comment]
@Zhuinden Yes, same issue, same user. Marked it as such in our internal support tool ;-)

**Comment by kneth** [comment]
I have successfully built the example on Ubuntu 16.10. I never use my country's locale (Denmark), and my current locale is:

```
LANG=en_US.UTF-8
LANGUAGE=en_US:en
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC="en_US.UTF-8"
LC_TIME="en_US.UTF-8"
LC_COLLATE="en_US.UTF-8"
LC_MONETARY="en_US.UTF-8"
LC_MESSAGES="en_US.UTF-8"
LC_PAPER="en_US.UTF-8"
LC_NAME="en_US.UTF-8"
LC_ADDRESS="en_US.UTF-8"
LC_TELEPHONE="en_US.UTF-8"
LC_MEASUREMENT="en_US.UTF-8"
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

**Comment by beeender** [comment]
@kaushik1221 
1. Can you try with build through command line? from the project root directory: `./gradlew assemble`
2. Maybe it is a Android Studio problem? I saw your are using the beta version 3.0. I am using the stable version 2.3 .

**Comment by kneth** [comment]
@kaushik1221 Did you have a chance to take a look at two questions above?
