### ISSUE TITLE
Realm doesn't send notifications

### ISSUE THREAD

**Issue by k-egor-smirnov** [realm/realm-java#4327]
Why code below doesn't work?

Code in my fragment

```java

@Override
            public void onChange(RealmResults<Event> element) {
                for (final ActionRealm event : element) {
                            events.add(0, event);
                            getActivity().runOnUiThread(new Runnable() {
                                @Override
                                public void run() {
                                    mAdapter.notifyDataSetChanged();
                                }
                            });
                }
            }
        });

```

Code in my Service
```java
re.beginTransaction();

                    Event event = re.createObject(Event.class);
                    event.setType(((TdApi.UpdateUserStatus) object).status.getClass().getSimpleName());
                    event.setTiming(System.currentTimeMillis());
                    event.setUserId(((TdApi.UpdateUserStatus) object).userId);

                    re.commitTransaction();
```
Realm version(s): 3.0.0

Realm sync feature enabled:no

Android Studio version: 2.3

Which Android version and device: Genymotion SDK 22

**Comment by k-egor-smirnov** [comment]
I wanted to simplify the variables in the code, but I made a little mistake. Sorry for that

**Comment by kneth** [comment]
Do you still experience the issue? I am a bit confused by your comment and close/reopen.

**Comment by k-egor-smirnov** [comment]
@kneth I missed the button ¯\_(ツ)_/¯

**Comment by Zhuinden** [comment]
The `RealmChangeListener` is probably added to a `RealmResults` that was not kept as a field reference.

Also, I'm not even sure why the events aren't just handled as a `realm.where(Event.class).findAllSorted("timing", Sort.DESCENDING);` and a `RealmRecyclerViewAdapter` or something like that.

**Comment by kneth** [comment]
@k-egor-smirnov Maybe https://realm.io/docs/java/latest/#working-with-android might be of help.

**Comment by k-egor-smirnov** [comment]
By the way, I insert the elements in the Service

**Comment by Zhuinden** [comment]
> The RealmChangeListener is probably added to a RealmResults that was not kept as a field reference.

**Comment by k-egor-smirnov** [comment]
@Zhuinden ```java
RealmResults<Event> results = realm.where(Event.class).findAllAsync();
        results.addChangeListener(new RealmChangeListener<RealmResults<Event>>() {
```

doesn't work too

**Comment by Zhuinden** [comment]
@k-egor-smirnov Well yes,  because that's also not kept as a field reference, it's a local reference

You need to have class-level field

**Comment by k-egor-smirnov** [comment]
@Zhuinden It works! Thank you
