### ISSUE TITLE
in.demo.db.models.InfoEntity is not part of the schema for this Realm.

### ISSUE THREAD

**Issue by anandkparmar** [realm/realm-java#4333]
I am getting above error when I am creating a RealmObject 

_PFA the code snippet -_

Realm realm = Realm.getDefaultInstance();

        realm.executeTransaction(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {
                InfoEntity entity = realm.createObject(InfoEntity.class);
                entity.setName(response.getFirstName());
                entity.setDob(response.getDob());
                entity.setEmail(response.getEmail());
                entity.setGender(response.getGender());
                entity.setMobileNumber(response.getHandleValue());
                entity.setPhotograph(response.getPhotograph());
            }
        });

**This is how entity is defined -** 

public class InfoEntity extends RealmObject { 

}

Kindly help.

> We LOVE to help with any issues or bug you have!

> **Questions**: If you have questions about how to use Realm, please ask on [SO](http://stackoverflow.com/questions/ask?tags=realm) - we monitor the Realm tag.

> **Feature Request**: Just fill in the first two sections below.

> **Bugs**: To help you as fast as possible with an issue or bug please describe your issue and the steps you have taken to reproduce it in as many details as possible.
>
> Thanks for helping us help you :-)
>
> Remove this and above before submitting.

#### Goal

> What do you want to achieve?

#### Expected Results

> ?

#### Actual Results

>  E.g. full stack trace with exception

#### Steps & Code to Reproduce

> Describe your current debugging efforts.

#### Code Sample

```java

> Your code here. Bigger samples should ideally be as separate Android Studio project, 
> in gists/repositories or privately at help@realm.io)

```

#### Version of Realm and tooling
Realm version(s): ?

Realm sync feature enabled: yes/no

Android Studio version: ?

Which Android version and device: ?

**Comment by Zhuinden** [comment]
Possible causes:

1.) the `InfoEntity` class is defined in a different module of the application (as part of a library for example), and that library didn't expose its RealmModels as a `@RealmModule`; and if it did, then the `RealmConfiguration.Builder` was not given that RealmModule

2.) `android-apt` was executed *after* `realm-android`

3.) `jack` is enabled even though it should be disabled

**Comment by kneth** [comment]
Does `InfoEntity` have any fields? Try to add `@RealmClass` to it.

**Comment by kneth** [comment]
I am closing the issue. If you are still experiencing the issue, please reopen or create a new issue.
