### ISSUE TITLE
Unified Coding Style

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#4335]
To avoid more arguments about code style and generally avoid clutter in PR's,  we want to start using a shared code style that can be configured and used by everyone.

Right now we have a XML file in https://github.com/realm/realm-java/tree/master/realm/config/studio/Realm-style.xml , but from what I can tell it requires that everyone manually import the file for it to work?

If we use the trick in this blogpost instead we just include it in the `.idea` folder instead. Which would make it work automatically from what I can tell? Thoughts @bmeike ?

https://tips.seebrock3r.me/share-the-settings-with-the-whole-team-android-studio-protip-6-3cce16eb2ea4#.avxfndd7r This blog post here

**Comment by zaki50** [comment]
I think we should have following option in the `Realm-style.xml`
```
<option name="FORMATTER_TAGS_ENABLED" value="true" />
```

And both manual importing and `Copy to Project` seem to be required to get the configuration file worked.

**Comment by cmelchior** [comment]
@bmeike Any comments to above, or can this be closed since #4351 was merged?
