### ISSUE TITLE
Android studio 2.3 with realm - instant run

### ISSUE THREAD

**Issue by wjdtncjs** [realm/realm-java#4345]
#### Goal

> I don't know it is android studio 2.3  bug or not. but If I use realm It causes that' Instant run' is not working.  (*I know 'apply button from 2.3' )

android studio says that  "Instant Run applied code changes and restarted the app. Static Initializer Change" even small change like xml change or  log adding.

but If I remove all realm dependency from my code. then instant run is working properly.

Do you have any solution? 

#### Version of Realm and tooling
Realm version(s): ? 2.3.1

Realm sync feature enabled: no

Android Studio version: ? 2.3

Which Android version and device: ? compileSdkVersion  25 and Test Phone GalaxyS3(5.0.1)

**Comment by Zhuinden** [comment]
> Certain third-party plugins that perform bytecode enhancement may cause issues with how Instant Run instruments your app.

from https://developer.android.com/studio/run/index.html#ir-limitations

----------

Realm performs bytecode enhancement to support replacing all field access with proxy method access, which is necessary for Realm to work.

Which means I don't think Instant Run can work with it.

**Comment by cmelchior** [comment]
I tried playing around with our IntroExample using Android Studio 2.4 Preview 2. There Instant Run seems to be work as intended. 

In my experience, Instant Run is great when it works, but sadly there is a lot of cases where it doesn't  work, and those cases are a bit hard to predict. 

In any case, it is not something Realm as a library can do something about. If you find a case where Instant Run isn't working as intended, you should create a bug report on the official Google bug tracker with a repo case: http://tools.android.com/filing-bugs
