### ISSUE TITLE
Better error message when number of fields doesn't match during migration

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#4346]
A few people have seen something like the below error message after executing a (wrong) migration

 "io.realm.exceptions.RealmMigrationNeededException: Field count is less than expected - expected 20 but was 19".

To make it easier for people to debug, we should try to diff the list of field names in the proxy class with the list of field names in the Realm file. That way we can output which field names cause this to happen:

Eg.

```
 io.realm.exceptions.RealmMigrationNeededException: Field count is less than expected - expected 20 but was 19. Missing [<fieldName>] from model class.

 io.realm.exceptions.RealmMigrationNeededException: Field count is more than expected - expected 19 but was 20. Remove [<fieldName>] from model class.
```

**Comment by beeender** [comment]
This has been improved. The migration exception message is produced by Object Store and it is clear about what is wrong.
