### ISSUE TITLE
prepopulate databases?

### ISSUE THREAD

**Issue by MarsVard** [realm/realm-java#435]
does realm have a way of using prepopulated databases?

**Comment by lidemin** [comment]
Hi, @bmunkholm may I know how is the progress of this feature for browser? Thanks

**Comment by bmunkholm** [comment]
Unfortunately not much progress on that - sorry to say. We are still prioritising many other core features above this one.
It's actually one of those features which anyone could relatively easily implement in the browser. We are considering to better mark those features as "help wanted" for the community to pick up. We could certainly use some help on those kind of features which are not a core part of the database.
