### ISSUE TITLE
Storage with realm

### ISSUE THREAD

**Issue by DanteAndroid** [realm/realm-java#4364]
I found that starting with realm, my app's data size has become a large amount (easily more than 100m).
Does realm produce larger data files than other database libs?
Any way to reduce the data size?
Thx

**Comment by Zhuinden** [comment]
Generally, you end up with an unusually large Realm file only if you have open Realms created by `Realm.getDefaultInstance` or `Realm.getInstance` that is ignored and/or not closed. 

Each open call should be paired with a close call. 

Then, `compactRealm` can reduce file size when there are no open Realms.

**Comment by cmelchior** [comment]
Controlling the Realm instance lifecycle is key to avoid inflated file sizes. See these tips:
https://realm.io/docs/java/latest/#closing-realm-instances
https://realm.io/docs/java/latest/#controlling-the-lifecycle-of-realm-instances
https://realm.io/docs/java/latest/#large-realm-file-size

**Comment by DanteAndroid** [comment]
Any way to detect unclosed Realm? Thx

**Comment by DanteAndroid** [comment]
Is it safe I write `    public void close() {
        realm.removeAllChangeListeners();
        realm.close();
    }`
These 2 methods together OnDestroy?

**Comment by Zhuinden** [comment]
> Any way to detect unclosed Realm? Thx

[Realm.getGlobalInstanceCount()](https://realm.io/docs/java/latest/api/io/realm/Realm.html#getGlobalInstanceCount-io.realm.RealmConfiguration-)

**Comment by cmelchior** [comment]
@DanteAndroid Yes, combining those should be safe.

**Comment by kneth** [comment]
I am closing the issue since it sounds like it can been answered fully.
