### ISSUE TITLE
Save in a separate Realm

### ISSUE THREAD

**Issue by DanteAndroid** [realm/realm-java#4374]
I have a model called `Diary`.
In the home page, app shows all diaries.
In a certain page, app loads some private diaries. I want to cache them, but I don't want home page to access them(when querying all diaries in Realm). So is any way I save them in a separate space?
I don't want to add a `boolean` to filter, cause adding a variable will add a lot of work

**Comment by DanteAndroid** [comment]
Or, if you can provide me a method like `containsField`, because the difference between them is one doesn't has certain field.

**Comment by Zhuinden** [comment]
Well, there should be a boolean field that indicates whether a diary is private.

**Comment by DanteAndroid** [comment]
Actually `private` is just my description for convenience. The only difference is one contains `user` field, and another doesn't. And I found `contains` method, it works, thx!

**Comment by cmelchior** [comment]
Great you found a solution. Closing.
