### ISSUE TITLE
The getter for a RealmList returns null.

### ISSUE THREAD

**Issue by wbervoets** [realm/realm-java#4375]
#### Goal

The following query which returns a RealmList sometimes returns null which is unexpected.

realm.where(SearchItem.class)
                .equalTo("query", searchQuery)
                .findFirst()
                .getArticles();

Model object:

public class SearchItem extends RealmObject {

    @PrimaryKey
    private Long id;

    @Required
    private String query;

    private int priority;

    private RealmList<Article> articles;
    private RealmList<Folder> folders;
    private RealmList<Producer> producers;
    private RealmList<Brand> brands;

.... getters/setters

    public RealmList<Article> getArticles() {
        return articles;
    }

}
#### Expected Results

Documentation states:  The getter for a RealmList will never return null. The returned object is always a list but the length might be zero.

#### Actual Results

Null value returned

#### Version of Realm and tooling
Realm version(s): 3.0.0

Realm sync feature enabled: no

Android Studio version: 2.3

Which Android version and device: OnePlus 3T, Android 7

**Comment by beeender** [comment]
Is `findFirst()` returning `null`? What is the backtrace?

**Comment by cmelchior** [comment]
Note, It can return `null` if the object is unmanaged.

**Comment by Zhuinden** [comment]
are you sure it is not `findFirst()` that returned null?

**Comment by wbervoets** [comment]
sorry, it was findFirst() that sometimes returned null because an async write transaction was sometimes already completed and sometimes not

**Comment by silviokuehn** [comment]
Try and just initialize the list, the resolve this issue that occours on unmanaged object.

private RealmList<RmCategory> subCategories **= new RealmList<>()**;

public RealmList<RmCategory> getSubCategories() {
    return subCategories;
}

public void setSubCategories(RealmList<RmCategory> subCategories) {
    this.subCategories = subCategories;
}

**Comment by Zhuinden** [comment]
@minaairsupport your code is for Realm Xamarin, you should ask at https://github.com/realm/realm-dotnet/

**Comment by minaairsupport** [comment]
Sorry but I think its the same issue

**Comment by Zhuinden** [comment]
No it's not. It is a completely different binding.

**Comment by silviokuehn** [comment]
Maybe my last answer from May 2017 goes for Xamarin implementation, too.

**Comment by minaairsupport** [comment]
I tried by the way and the app crashes , have you tried something else

**Comment by Zhuinden** [comment]
I'd try reading the crash stack trace for possible error messages that can help deciding what the cause of the error is.

**Comment by minaairsupport** [comment]
11-05 05:38:28.314 D/Mono    ( 6876): Assembly Ref addref CB.Core.Conversion[0xddc89160] -> CB.Core.Common[0xf3cf1e20]: 7
Resolved pending breakpoint at 'ConvertorHelper.cs:84,1' to CB.Core.Entities.FlightListItem CB.Core.Conversion.ConvertorHelper.FlightListItemModelConvertor (CB.Core.Models.FlightListItem item) [0x00160].
11-05 05:38:28.380 F/        ( 6876): * Assertion at /Users/builder/jenkins/workspace/xamarin-android-d15-8/xamarin-android/external/mono/mono/mini/unwind.c:635, condition `cfa_reg != -1' not met
11-05 05:38:28.381 F/libc    ( 6876): Fatal signal 6 (SIGABRT), code -6 in tid 7076 (Thread Pool Wor)

**Comment by Zhuinden** [comment]
Now if I look for this error online, it says that a possible workaround is to use English system locale on the system that compiles the C# code.

**Comment by minaairsupport** [comment]
could you provide link ?

**Comment by Zhuinden** [comment]
https://answers.unity.com/questions/1327929/-assertion-at-monominiunwindc620-condition-cfa-reg.html

**Comment by minaairsupport** [comment]
thanks for link but is it normal to find IList<Entity> with null and cant add to it

**Comment by Zhuinden** [comment]
That is not related to the error message you posted *at all*

**Comment by silviokuehn** [comment]
Please stop spamming this closed issue with unregarding stuff.

**Comment by minaairsupport** [comment]
yea this happen when I try silviokuehn answer 
private RealmList<RmCategory> subCategories = new RealmList<>();
I do the same 
private RealmList<RmCategory> subCategories => subCategories  ?? new RealmList<>();

**Comment by Zhuinden** [comment]
Bring it over to realm-dotnet.

I will stop answering anything beyond this point.

**Comment by minaairsupport** [comment]
reported issue https://github.com/realm/realm-dotnet/issues/1787
