### ISSUE TITLE
OrderedRealmCollectionChangeListener  Update Notification

### ISSUE THREAD

**Issue by shakil807g** [realm/realm-java#4383]
Is this is valid to do update in recyclerview  Item  i am using RealmRecyclerViewAdapter 
 

                new Thread(new Runnable() {
                                    @Override
                                    public void run() {

                                        Realm realm = Realm.getDefaultInstance();

                                        Group group = realm.where(Group.class)
                                                .equalTo(Group.FIELD_GROUPID, 1).findFirst();

                                        for (int i = 0; i < 100; i++) {

                                            Log.d(TAG, "execute: "+i);
                                            realm.beginTransaction();
                                            group.setProgress(i);
                                            realm.commitTransaction();

                                            try {
                                                Thread.sleep(1000);
                                            } catch (InterruptedException e) {
                                                e.printStackTrace();
                                            }
                                        }

                                        realm.close();

                                    }
                                }).start();

Realm Java 3.0.0

**Comment by Zhuinden** [comment]
No need to use thread.sleep() and you should use `Executors.newSingleThreadedPool()` instead of `new Thread(new Runnable()) {...`, because it can cause problems.

**Comment by beeender** [comment]
Yes, i think so!

**Comment by shakil807g** [comment]
i have another use case  where i am using   rxjava  

               disposableSubscriber =
            Flowable.fromCallable(() ->         DbHelper.getRealmFirstTimeStamp(RMyContact.class,RMyContact.KEY_N_TIME_STAMP))
                           .flatMap(time -> {
                            Query lastMessages = mDatabase.child("conversations").orderByChild("negative_create_at").endAt(time);
                    return RxFirebaseDatabase.observeChildEvent(lastMessages,BackpressureStrategy.BUFFER);
                })
                .filter(dataSnapshotRxFirebaseChildEvent ->
                        dataSnapshotRxFirebaseChildEvent.getEventType().equals(RxFirebaseChildEvent.EventType.ADDED)
                                || dataSnapshotRxFirebaseChildEvent.getEventType().equals(RxFirebaseChildEvent.EventType.CHANGED))
                .subscribeOn(Schedulers.io())
                 .subscribeWith(new DisposableSubscriber<RxFirebaseChildEvent<DataSnapshot>>() {
                    @Override
                    public void onNext(RxFirebaseChildEvent<DataSnapshot> item) {

                        Log.d(TAG, "onNext: "+item.getValue().child("title").getValue());


                        String msg = item.getValue().child("title").getValue().toString();
                        long time  = (long) item.getValue().child("create_at").getValue();


                        try(Realm realmInstance = Realm.getDefaultInstance()) {
                            realmInstance.executeTransaction((realm) -> {

                                RMyContact myContact = new RMyContact();
                                myContact.setGroupID(item.getKey());
                                myContact.setIndex(DbHelper.getAutoID(realm,RMyContact.class,RMyContact.KEY_INDEX));
                                myContact.setLastText(msg);
                                myContact.setNegativeTimeStamp(-time);
                                myContact.setTimestamp(time);
                                realm.copyToRealmOrUpdate(myContact);

                            });
                        }

                    }
                    @Override
                    public void onError(Throwable t) {

                    }

                    @Override
                    public void onComplete() {

                    }
                });





The important thing to note in this code is  onNext() method is called on background thread Multiple time e.g (1000) and  i am   doing  **try(Realm realmInstance = Realm.getDefaultInstance()) {**      on every called in order to insert a value  on each onNext  call  will there will performance impact or any other issues

**Comment by nhachicha** [comment]
@shakil807g If you're concerned with the performance (doing too much transactions) you can use a RxJava _backpressure_ strategy, example using [buffer](http://reactivex.io/documentation/operators/buffer.html) operator to group and insert chunks of data

```java
       .buffer(50)
        .subscribe(new Action1 < List < RxFirebaseChildEvent > () {
         @Override
         public void call(List < RxFirebaseChildEvent > events) {
          realm.beginTransaction();
          realm.insert(events);
          realm.commitTransaction();
         }
        });
```
further more, since you're only inserting the data, it's better for performance to use `Realm#insert(Collection<? extends RealmModel> objects)` instead of `copyToRealmOrUpdate` since it's generally more performant.

**Comment by shakil807g** [comment]
@nhachicha  the reason i am using **copyToRealmOrUpdate** is because as soon as the first data insert  i am listening to the  insert event through **OrderedRealmCollectionChangeListener** on other fragment  in order  to show that item in Recylerview . and with   **Realm#insert(Collection<? extends RealmModel> objects)**  i have to wait for all the all item to come before showing in Recylerview

**Comment by shakil807g** [comment]
@nhachicha  i am just worried about this code which is calling frequently e.g like 1000 time in some cases
        

      try (Realm realmInstance = Realm.getDefaultInstance()) {
          realmInstance.executeTransaction((realm) -> {

        RMyContact myContact = new RMyContact();
        myContact.setGroupID(item.getKey());
        myContact.setIndex(DbHelper.getAutoID(realm, RMyContact.class, RMyContact.KEY_INDEX));
        myContact.setLastText(msg);
        myContact.setNegativeTimeStamp(-time);
        myContact.setTimestamp(time);
        realm.copyToRealmOrUpdate(myContact);

      });
    }

it is ok to call Realm.getDefaultInstance()  multiple times ?

**Comment by nhachicha** [comment]
As long as you have an open instance of Realm elsewhere (in UI) for example, you will not incur all the costly initialisation of a Realm again (`schemaValidation`, `columnIndices` etc.)

The cost of `Realm.getDefaultInstance()` will be the cost of opening a `SharedGroup`

**Comment by beeender** [comment]
@shakil807g I hope your issue is solved. I am closing this issue now, if you still need help on this, please let us know.
