### ISSUE TITLE
RealmList's addChangeListener,when  copyToRealm(RealmList),the listener not work!

### ISSUE THREAD

**Issue by Misayanice** [realm/realm-java#4387]
RealmList's addChangeListener,when  copyToRealm(RealmList),the listener not work!

**Comment by beeender** [comment]
what do you mean by "the listener not work"? what you please add some source code to explain that?

**Comment by Misayanice** [comment]
1. onCreate()--------------->RealmList<IndexResultBean> indexResultBeanRealmList = realm.where(IndexObjBean.class).findFirst().getResult();
        indexResultBeanRealmList.addChangeListener(orderedRealmCollectionChangeListener);

2.  private OrderedRealmCollectionChangeListener orderedRealmCollectionChangeListener=new OrderedRealmCollectionChangeListener<RealmList<IndexResultBean>>() {
        @Override
        public void onChange(RealmList<IndexResultBean> collection, OrderedCollectionChangeSet changeSet) {
            LogUtils.e("ModelActivity","onChange");
            if (changeSet == null) {
                multipleItemQuickAdapter.notifyDataSetChanged();
                return;
            }
            // For deletions, the adapter has to be notified in reverse order.
            OrderedCollectionChangeSet.Range[] deletions = changeSet.getDeletionRanges();
            for (int i = deletions.length - 1; i >= 0; i--) {
                OrderedCollectionChangeSet.Range range = deletions[i];
                multipleItemQuickAdapter. notifyItemRangeRemoved(range.startIndex, range.length);
            }

            OrderedCollectionChangeSet.Range[] insertions = changeSet.getInsertionRanges();
            for (OrderedCollectionChangeSet.Range range : insertions) {
                multipleItemQuickAdapter.  notifyItemRangeInserted(range.startIndex, range.length);
            }

            OrderedCollectionChangeSet.Range[] modifications = changeSet.getChangeRanges();
            for (OrderedCollectionChangeSet.Range range : modifications) {
                multipleItemQuickAdapter.  notifyItemRangeChanged(range.startIndex, range.length);
            }
        }
    };

3.
IndexObjBean objBean = indexBean.getObj();
realm.copyToRealm(objBean);
4."    LogUtils.e("ModelActivity","onChange");" not print

**Comment by beeender** [comment]
I assume your `IndexObjBean` is defined like:
```java
public class IndexObjBean {
    private RealmList<Result> results;
}
```

The listener on `results` will only be triggered when the `results` itself is changed (add/remove elements from the `RealmList`). So I don't think your step 3 should trigger the listener since it doesn't change anything on the results of `RealmList indexResultBeanRealmList = realm.where(IndexObjBean.class).findFirst().getResult();`

**Comment by Misayanice** [comment]
" So I don't think your step 3 should trigger the listener since it doesn't change anything on the results of RealmList indexResultBeanRealmList = realm.where(IndexObjBean.class).findFirst().getResult();"------->
realm.copyToRealm ---->change my database table of (IndexObjBean  Result)

**Comment by beeender** [comment]
Yes, but `IndexObjBean.results` is a list of `Result`. For example, it contains 1 element before, after your `copyToRealm` called, the `results` contains the same 1 element just like before which means it has been changed. So the listener is not called. I am not sure what do you want to do here, maybe you want to do `indexResultBeanRealmList.add(objBean)`? That will trigger the listener.

**Comment by Misayanice** [comment]
I understand.I'm doing paging cache, each network request and 10 data cache.
