### ISSUE TITLE
When I delete some of the data in the realm, the results are in the wrong order？it is disturbing

### ISSUE THREAD

**Issue by Misayanice** [realm/realm-java#4392]
When I delete some of the data in the realm, the results are in the wrong order？it is disturbing.

**Comment by Zhuinden** [comment]
Order is unspecified unless you sort. Insertion order is not retained after deletions.

**Comment by Zhuinden** [comment]
@cmelchior although apparently I found the note for this in the Swift docs, so maybe this is actually a documentation thing for Java side:

https://realm.io/docs/swift/latest/#sorting
