### ISSUE TITLE
realm-tasks demo

### ISSUE THREAD

**Issue by RebelSoft** [realm/realm-java#4393]
#### Goal

> What do you want to achieve?

I would like to test the realm-tasks app with my realm object server. Then do a few tests to see if this would work for my use case.

#### Actual Results

UNKNOWN(-1)
java.lang.UnsatisfiedLinkError: No implementation found for void io.realm.log.RealmLog.nativeLog(int, java.lang.String, java.lang.Throwable, java.lang.String) (tried Java_io_realm_log_RealmLog_nativeLog and Java_io_realm_log_RealmLog_nativeLog__ILjava_lang_String_2Ljava_lang_Throwable_2Ljava_lang_String_2)
	at io.realm.log.RealmLog.nativeLog(Native Method)
	at io.realm.log.RealmLog.log(RealmLog.java:284)
	at io.realm.log.RealmLog.debug(RealmLog.java:146)
	at io.realm.log.RealmLog.debug(RealmLog.java:135)
	at io.realm.internal.network.OkHttpAuthenticationServer.authenticate(OkHttpAuthenticationServer.java:109)
	at io.realm.internal.network.OkHttpAuthenticationServer.loginUser(OkHttpAuthenticationServer.java:53)
	at io.realm.SyncUser.login(SyncUser.java:189)
	at io.realm.SyncUser$1.run(SyncUser.java:228)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:423)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1113)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:588)
	at java.lang.Thread.run(Thread.java:818)

#### Steps & Code to Reproduce

>I have commented out the next section of code could be part of my issue.
I get a null reffrence exception on SyncUser.currentUser();

 // Check if we already got a user, if yes, just continue automatically
if (savedInstanceState == null) {
     if (!ACTION_IGNORE_CURRENT_USER.equals(getIntent().getAction())) {
         final SyncUser user = SyncUser.currentUser();
         if (user != null) {
             loginComplete(user);
         }
     }
 }

#### Code Sample

I setup facebook Auth it seems to be working. Its getting token and everything but get an error on SyncUser.loginAsync(credentials, AUTH_URL, SignInActivity.this);

// Setup Facebook Authentication
facebookAuth = new FacebookAuth((LoginButton) findViewById(R.id.login_button)) {
    @Override
    public void onRegistrationComplete(final LoginResult loginResult) {
        UserManager.setAuthMode(UserManager.AUTH_MODE.FACEBOOK);
        SyncCredentials credentials = SyncCredentials.facebook(loginResult.getAccessToken().getToken());
        SyncUser.loginAsync(credentials, AUTH_URL, SignInActivity.this);
    }
};

```

#### Version of Realm and tooling
Realm version(s): 3.0.0

Realm sync feature enabled: yes

Android Studio version: v2.2.3

Which Android version and device: 6.0.1, API 23, Sony Z3

**Comment by Zhuinden** [comment]
after changing 2.3.0 to 3.0.0 in line [here](https://github.com/realm-demos/realm-tasks/blob/master/RealmTasks%20Android/build.gradle#L10), did you clean + rebuild?

**Comment by RebelSoft** [comment]
Yes, Just cleaned I rebuild again no joy.

**Comment by cmelchior** [comment]
@RebelSoft Just to be clear. Are you seeing that error from cloning the RealmTask repo or from your own code?

**Comment by RebelSoft** [comment]
@cmelchior I cloned it and I could not run the code gradle and all the dependencies are missing. So What I did was I copied all the classes and resource contents over to a new project. I pulled in all the dependencies until the code could build successfully. I did not exclude any code. I added my servers IP address where needed. On the first run the following section of code crashed in the SignInActivity .

Null Pointer on SyncUser.currentUser();

// Check if we already got a user, if yes, just continue automatically
if (savedInstanceState == null) {
if (!ACTION_IGNORE_CURRENT_USER.equals(getIntent().getAction())) {
final SyncUser user = SyncUser.currentUser();
if (user != null) {
loginComplete(user);
}
}
}

This code does not seem that important to me yet it just keeps track of your logged in state.I could be wrong but I commented it out. I set up facebook auth and it response back with success but as soon as
SyncUser.loginAsync(credentials, AUTH_URL, SignInActivity.this); excutes it starts the thread and gives me the error as stated above.

// Setup Facebook Authentication
facebookAuth = new FacebookAuth((LoginButton) findViewById(R.id.login_button)) {
@Override
public void onRegistrationComplete(final LoginResult loginResult) {
UserManager.setAuthMode(UserManager.AUTH_MODE.FACEBOOK);
SyncCredentials credentials = SyncCredentials.facebook(loginResult.getAccessToken().getToken());
SyncUser.loginAsync(credentials, AUTH_URL, SignInActivity.this);
}
};

**Comment by RebelSoft** [comment]
@cmelchior I see that this one line is commented out in the draw demo of theirs.
RealmLog.setLevel(LogLevel.TRACE);
 Will comment it the tasks app as well and see what it does.  I think it could solve the problem.

**Comment by cmelchior** [comment]
It is a debug setting that logs everything. Normally it shouldn't be needed. It shouldn't crash by setting that though.

**Comment by RebelSoft** [comment]
got the draw demo to work :D.... So Will close.

**Comment by Zhuinden** [comment]
@cmelchior it sounds problematic that the JNI crashed with the logger, though
