### ISSUE TITLE
Get a notification about deleted RealmObject

### ISSUE THREAD

**Issue by parizene** [realm/realm-java#4398]
```java
        Realm realm = Realm.getDefaultInstance();
        RealmResults<Item> items = realm.where(Item.class).findAllAsync();
        // items contain item with id = 1
        items.addChangeListener(new OrderedRealmCollectionChangeListener<RealmResults<Item>>() {
            @Override
            public void onChange(RealmResults<Item> collection, OrderedCollectionChangeSet changeSet) {
                OrderedCollectionChangeSet.Range[] deletions = changeSet.getDeletionRanges();
                // deletions array contains item with id = 1 in range, but collection does not have this item
            }
        });
        realm.executeTransaction(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {
                Item item = realm.where(Item.class).equalTo(Item.ID, 1).findFirst();
                item.deleteFromRealm();
            }
        });
```
The question is how to get deleted `RealmObject`? `collection` does not have it, only index is received in `getDeletionRanges` (it is ok for `RecyclerView` adapter, `collection` represents current db state). But how to get a notification about deleted `RealmObject`?
Maybe `OrderedCollectionChangeSet` can return deleted objects too, not only indices?

**Comment by Zhuinden** [comment]
What do you need deleted item for? Generally you seem to have it before `item.deleteFromRealm()` is called, you could for example make a copy there with `realm.copyFromRealm()`.

**Comment by parizene** [comment]
Item can be deleted in manager, I want to update map markers on ui for e.g without updating all of them, only removing one by id, or other stuff not related to `RecyclerView`.

**Comment by istx25** [comment]
Thanks for reaching out about this, @parizene. I wanted to let you know that we've received your message and that someone on the Realm Java team will review what you've shared and follow-up with you soon. Cheers.

**Comment by beeender** [comment]
can you map the index from `RealmResults` to your map makers? How does you map makers data structure look like?

**Comment by parizene** [comment]
The main problem is: I have 50 items in db for e.g, but I'm working with 5 of them, and displaying them (these 5 are not `RealmResults`). If one of them items is deleted from db, I want to update my 5 items, to delete missing item id

**Comment by beeender** [comment]
@parizene Then maybe what you need is this https://github.com/realm/realm-java/pull/4331 . it has been merged to master a few hours ago, you can try it with our snapshot build.

**Comment by parizene** [comment]
@beeender still can't resolve `ObjectChangeSet` in last 3.1.0-SNAPSHOT, waiting

**Comment by beeender** [comment]
@parizene It should be there. Try a clean then sync the gradle? (I tried the snapshot half hour ago.)

**Comment by parizene** [comment]
@beeender yes, I tried it, so I have to set `addChangeListener` on every `RealmObject` in list, to get notification that one of them was deleted. I can't set 1 listener on all objects in list, because `onChange` does not return `RealmObject`.
I have a list of A items that doesn't come from realm db, every A item has a key. I'm mapping A item key to the B `RealmObject` item from db using key. So if the corresponded B item in db will be deleted how can I notify my A list items to delete A item? I should set `RealmObjectChangeListener` on every mapped B item? I really liked `OrderedRealmCollectionChangeListener` approach for `RecyclerView` but there is no way do detect deleted B item.

**Comment by beeender** [comment]
I think you can build map for {IndexInRealmResults, IndexInYourDataStructure}, then you can still use the `OrderedRealmCollectionChangeListener`.

**Comment by parizene** [comment]
@beeender probably the only way to do it now, thanks

**Comment by beeender** [comment]
The reason we don't support reading the deleted objects is because it makes the API too complex. To support that, the API needs to be changed to something like:

```
public interface CollectionChangeListener {
void beforeChange(ChangeSet changeSet);
void afterChange(ChangeSet changeSet);
}
```

The `beforeChange` will be called before moving the database version forward. That may cause some UI&data inconsistency if it is used in a wrong way. e.g: refresh the UI in `beforeChange()` and actually at this time the corresponding data is not deleted.

@parizene thanks a lot for you feedback. I am closing this issue now, let us know if you still have questions about this case.
