### ISSUE TITLE
Don't force objects to extend RealmObject

### ISSUE THREAD

**Issue by mighter1488** [realm/realm-java#440]
Is it possible to save Object.class descendants directly, without extending RealmObject?

**Comment by bangarharshit** [comment]
I also have a case where composition may not work - https://github.com/realm/realm-java/issues/735 . Inheritance will surely be useful.

**Comment by cmelchior** [comment]
Just to follow up on this. After an internal design discussion we have decided that the requirement to extend RealmObject is here to stay for the foreseeable future, so I am closing this enhancement here now.

However we certainly still want to support subclassing / polymorphism which instead will be tracked here: https://github.com/realm/realm-java/issues/761

**Comment by murilowlima** [comment]
I know that this issue is closed, but I want leave this comment.

I really liked this library, but I want to implement my domain classes whithou any infrastructure code. An example is the Hibernate mapping, which I as a architecture can separate the domain and the database code.
Forcing objects to extend RealmObject makes me unable to use DDD, as an example. http://martinfowler.com/tags/domain%20driven%20design.html

Thanks

**Comment by cmelchior** [comment]
One possible solution for achieving the best of both worlds could perhaps be to to develop a custom Realm IntelliJ plugin that did static analysis. This would obviously only work inside IntelliJ, but Google are doing the same with their support annotations: http://tools.android.com/tech-docs/support-annotations and they even managed to get it to work with the Gradle plugin.

Something like this:

```
// 1. We remove the RealmObject class
// 2. annotate all methods that require an RealmObject like so
public <E> E createObject(@RealmClass Class<E> class) {
 // ...
}

// 3. When calling this method we do static analysis and let IntelliJ mark it as an error
realm.createObject(MyRealmObject.class); // This would work
realm.createObject(NonRealmObject.class); // This would be marked as an error
```

**Comment by danijax** [comment]
Hey, I know this issue has been closed, but what if the `RealmObject` class has a field for `_ID` like the android `BaseColumns` class.

**Comment by kneth** [comment]
@danijax We have internally discussed adding a global and unique id to all objects. Many issues could be solved by doing so but so far we still believe that users can add primary keys when they need something this a unique identifier.

**Comment by Suresh-Reddevil** [comment]
I have three model classes. Two of them extends RealmObject while the remaining one does not. 
the first class extends the RealmObject;
```
public class Party extends RealmObject implements Parcelable {
    @PrimaryKey
    public int id;
    public String name;
    public String name_en;
    public String name_ne;
    public String address;
    public String phoneNumber;
    public String taxRegistrationNumber;
    public String partyType;
```
the second class holds a field of type Party. But this does not extends RealmObject

```
public class CreatePurchaseOrder implements Parcelable {
    public int voucherNumber;
    public Date date;
    public Party party;
    String agent;
```
The third class holds a field for CreatePurchaseOrder and extends RealmObject
 ```
public class CreatePurchaseOrderRow extends RealmObject implements Parcelable {
    @PrimaryKey
    public int id;
    private int serialNumber;
    private String specification;
    private float quantity;
    private float rate;
    private String remarks;
    private boolean fulfilled;
    private CreatePurchaseOrder createPurchaseOrder;
```


With this approach it generates an error message 
![error](https://cloud.githubusercontent.com/assets/13093548/16940331/e70aabc0-4da8-11e6-954e-84307db071e5.png)

Do i need to extend every class with RealmObject?

Thanks in advance,

**Comment by danijax** [comment]
@Suresh-Reddevil all of your classes have to either extend ```RealmObject``` or implement ```RealmModel```

**Comment by zaheerahmad** [comment]
Hi,

Any idea when would this be implemented? Just an idea?

**Comment by Zhuinden** [comment]
@zaheerahmad what is your use-case

**Comment by zaheerahmad** [comment]
@Zhuinden 
I have a response coming up from server, in which we have class as Task, and there are different types of tasks.

For now, I have implemented this way:

@Index
    @PrimaryKey
    @SerializedName("TaskID")
    private String taskId;

    @SerializedName("TaskType")
    private int taskType;

    @Index
    @SerializedName("Name")
    private String name;

    @SerializedName("Description")
    private String description;

    @SerializedName("BeginDateTime")
    private String beginDateTime;

    @SerializedName("EndDateTime")
    private String endDateTime;

    @Index
    @SerializedName("StoreNumber")
    private String storeNumber;

    @SerializedName("CreatedBy")
    private String createdBy;

    @SerializedName("CreationDateTime")
    private String creationDateTime;

    @Index
    @SerializedName("TaskStatusId")
    private int taskStatusId;

    @SerializedName("Modified")
    private String modifiedDateTime;

    @SerializedName("SubTaskCount")
    private int subTaskCount;

    //TODO: it should be a separate class and inherit CPUCTask class.
    ///Right now in Realm, polymorphism support is not added.. so adding it here.
    //Reference: https://github.com/realm/realm-java/issues/2643 and https://github.com/realm/realm-java/issues/440
    @SerializedName("CountSubTasks")
    private RealmList<CPUCCountSubTask> countSubTasks;

**Comment by CsabaZz** [comment]
This is why U abadonned to use Realm anymkre. Creating entities’s copy as RealmObject is ridiculous and useless extra work. :( There are alternatives that does the same thing with annotations, so I hope Realm will such smart lib once.
