### ISSUE TITLE
Type mismatch: Was STRING, expected [BOOLEAN].

### ISSUE THREAD

**Issue by warchildmd** [realm/realm-java#4401]
I'm experiencing some strange behavior with my app.

* Realm version: io.realm:realm-gradle-plugin:3.0.0
* Schema version: 2 (migration includes allowing some nulls).
* No manual migration called.

Flow:
1. Empty DB (freshly installed app)
2. [Optional] Create entries in the database tables from the app.
3. Successfully restore a previously made backup. 
4. At the first query to the database involving the `initial` field, this exception is thrown. All the later calls succeed without error.

Field `initial` is of type boolean in my class, and always was a boolean.

Backup is just a copy of the whole `db.realm` file, and restore is just copy back the `backup.realm` file over the current `db.realm` file.

```
FATAL EXCEPTION: 
Caused by: java.lang.IllegalArgumentException: Field 'initial': type mismatch. Was STRING, expected [BOOLEAN].                                                                        
at io.realm.RealmObjectSchema.getColumnIndices(RealmObjectSchema.java:717)                                                                        
at io.realm.RealmQuery.equalTo(RealmQuery.java:403)                                                                        
at ro.mb.mastery.data.services.ActivityDatabaseService.getActivitiesPerTimeInterval(ActivityDatabaseService.java:43)                                                                        
at ro.mb.mastery.fragments.ActivityFragment.reloadRecyclerView(ActivityFragment.java:152)                                                                        
at ro.mb.mastery.fragments.ActivityFragment.onResume(ActivityFragment.java:127)                                                                        
at android.support.v4.app.Fragment.performResume(Fragment.java:2238)    
```

**Comment by Zhuinden** [comment]
> Successfully restore a previously made backup.

`Realm.getInstance()` should thrown if there is a schema version mismatch. Is this reproducible?

**Comment by nhachicha** [comment]
Can you please post how you're doing the backup/restore. Schema validation and column indices calculation, are only performed and cached,  the first time you open the Realm within your app (for performance reasons).  You may be replacing Realm underneath, without closing  all instances, which causes the cached version to still believe to work with the configuration of the initial Realm.

**Comment by warchildmd** [comment]
It does that **only** at the first restore operations after a clean install.

I'm replacing realm underneath, but the versions match. Also, why it says `Was STRING` when that field is a boolean?

I'll post the backup / restore code in a couple of hours.

**Comment by cmelchior** [comment]
@warchildmd You can also try to open the Realm using a `DynamicRealm` and use that to investigate the schema of the old Realm. Perhaps that can give you some ideas about what is going wrong.

**Comment by warchildmd** [comment]
Backup code:

```
DatabaseConfigManager databaseConfigManager = DatabaseConfigManager
        .getInstance(getActivity());
Realm userRealm = Realm.getInstance(databaseConfigManager.getRealmUserConfig());

// Trying to write a backup on sdcard
File sdCard = Environment.getExternalStorageDirectory();
File dir = new File(sdCard.getAbsolutePath() + "/MasteryApp/Backups");
if (!dir.exists() && !dir.mkdirs()) {
    complain(getString(R.string.permissions_storage_complain));
}
File realm = new File(userRealm.getPath());
File file = new File(dir, String.valueOf(Calendar.getInstance().getTimeInMillis()) + ".realm");
userRealm.close();

try {
    FileChannel in = new FileInputStream(realm).getChannel();
    FileChannel out = new FileOutputStream(file).getChannel();

    out.transferFrom(in, 0, in.size());
} catch (IOException e) {
    e.printStackTrace();
}
```

and Restore code:

```
DatabaseConfigManager databaseConfigManager = DatabaseConfigManager.getInstance(getActivity());
Realm userRealm = Realm.getInstance(databaseConfigManager.getRealmUserConfig());

File realm = new File(userRealm.getPath());
File file = new File(dir, backups.get(which));

userRealm.close();

try {
    FileChannel in = new FileInputStream(file).getChannel();
    FileChannel out = new FileOutputStream(realm).getChannel();

    out.transferFrom(in, 0, in.size());
} catch (IOException e) {
    e.printStackTrace();
}
```

**Comment by Zhuinden** [comment]
Why not use `realm.writeCopyTo`?

**Comment by kneth** [comment]
Another benefit of using `writeCopyTo()` is that the file is compacted too.

See also https://realm.io/docs/java/latest/#how-to-back-up-and-restore-realm

**Comment by beeender** [comment]
@warchildmd Hope `writeCopyTo` solved your issue. Let us know if you still need help on this issue.

**Comment by Zhuinden** [comment]
Maybe the schema could be logged a bit better when such an exception  is thrown

**Comment by kneth** [comment]
@Zhuinden You mean the entire schema?

**Comment by Zhuinden** [comment]
Hmm... then the message would be a bit long... but it'd definitely help to understand the fields and types and where the mismatch is.

**Comment by kneth** [comment]
@Zhuinden We should provide a browser all our non-Mac users!

**Comment by Zhuinden** [comment]
I agree with that, as a Windows user :p
