### ISSUE TITLE
OrderedRealmCollectionChangeListener stops getting changes

### ISSUE THREAD

**Issue by eygraber** [realm/realm-java#4407]
If I set the following on a `RealmResults`, everything works:

```
realmResults.addChangeListener { collection, changeSet ->
      if(changeSet != null) {
        Log.e("TEST", "Insertion size ${changeSet.insertions.size}")
        Log.e("TEST", "Insertion range size ${changeSet.insertionRanges.map { it.length }.size}")
        Log.e("TEST", "Deletion size ${changeSet.deletions.size}")
        Log.e("TEST", "Deletion range size ${changeSet.deletionRanges.map { it.length }.size}")
        Log.e("TEST", "Change size ${changeSet.changes.size}")
        Log.e("TEST", "Change range size ${changeSet.changeRanges.map { it.length }.size}")
      }
}
```

If I set that twice on the same `RealmResults`, everything works fine.

If I set that on a `RealmResults`, and then set another listener, on another `RealmResults` for the same query as the first one, I only get changes on the first one for the first few changes. After that, nothing gets logged. The second one gets all the changes.

Am I missing something, or is this a bug?

**Comment by beeender** [comment]
is `realmResults` a local var? if the results get GCed, the listener will not be triggerred anymore.

**Comment by eygraber** [comment]
@beeender It is a local reference. Thanks!
