### ISSUE TITLE
java.lang.NoSuchFieldError

### ISSUE THREAD

**Issue by harshvishu** [realm/realm-java#4410]
#### StackTrace

>  FATAL EXCEPTION: main
Process:----------------------------, PID: 26030
java.lang.NoSuchFieldError: No instance field handlerController of type Lio/realm/HandlerController; in class Lio/realm/BaseRealm; or its superclasses (declaration of 'io.realm.BaseRealm' appears in /data/app/--------------------------/base.apk)
at io.realm.RealmBaseAdapter.addListener(RealmBaseAdapter.java:67)
at io.realm.RealmBaseAdapter.<init>(RealmBaseAdapter.java:60)
at

#### Steps & Code to Reproduce

> Updated from Realm version 2.3.0 to 3.0.0 (Latest)
> Another dependency is io.realm:android-adapters:1.4.0. Also tried with io.realm:android-adapters:2.0.0

#### Code Sample

```java

public class DevicesDropdownAdapter extends RealmBaseAdapter<Device> implements ThemedSpinnerAdapter {

    private ThemedSpinnerAdapter.Helper themeHelper;

    public DevicesDropdownAdapter(@NonNull Context context, @Nullable OrderedRealmCollection<Device> data) {
        super(context, data);
        themeHelper = new ThemedSpinnerAdapter.Helper(context);
    }
    // Nothing major below. Simple code for getView()
}

```

#### Version of Realm and tooling

- Realm version(s): 3.0.0
- Realm sync feature enabled: no
- Android Studio version: 2.3
- Which Android version and device: Xiaomi Redmi Note 3, Android 6.0.1, Api 23

**Comment by Zhuinden** [comment]
update to realm-android-adapters 2.0.0 and do clean+rebuild

**Comment by beeender** [comment]
Hope your issue is solved. Feel free to reopen this if needed.

**Comment by harshvishu** [comment]
Yeap! that was resolved but there are some other issues now. #4503
