### ISSUE TITLE
Reading .Realm File 

### ISSUE THREAD

**Issue by devvishal06** [realm/realm-java#4413]
Can any one please let me know i have Test.realm file which is exported by me from Another Project.I want to read and use this file in my project(On Android Platform).I am already using realm for my application.
I am placing the file in assets folder;can you please let me know how to access this file.

**Comment by Zhuinden** [comment]
`RealmConfiguration.Builder` has a method named `assetFile()`, if you set that filename as parameter then it'll be used as source of initial Realm

**Comment by devvishal06** [comment]
public RealmController(Context application) {




        realmConfiguration = new RealmConfiguration.Builder(application)
                .deleteRealmIfMigrationNeeded()
                .schemaVersion(DB_VERSION).build();
        // Clear the realm from last time
    
        Realm.setDefaultConfiguration(realmConfiguration);
        realm = Realm.getInstance(realmConfiguration);
    }

**Comment by kneth** [comment]
You can have multiple configurations in an app, and you can get instances of them. Realms cannot be mixed. For example, you cannot query multiple Realms in a single query. Moreover, you will have to manually copy objects from one Realm to the other (combining `copyFromRealm()` and `copyToRealm()` is one way).

**Comment by devvishal06** [comment]
Can you please send me the code snippet how to read .realm file from asset folder in android;with parallel using my default realm  schema.

**Comment by kneth** [comment]
You need to specify two different file name. Just use `name()` in your configuration: https://realm.io/docs/java/3.0.0/api/io/realm/RealmConfiguration.Builder.html#name-java.lang.String-

    RealmConfiguration config1 = new RealmConfiguration.Builder(this)
            .assetFile(this,"data/BizGeo.realm")
            .name("BizGeo.realm")
            .schemaVersion(30)
            .build();

    RealmConfiguration config2 = new RealmConfiguration.Builder(this)
            .name("somethingElse.realm") // not required: default.realm is fine
            .build();

**Comment by Zhuinden** [comment]
Indeed, you need to specify `name("[filename].realm")` to open the asset realm into a different Realm file, the default `name` is `default.realm`.

What is `RealmController`?

**Comment by beeender** [comment]
Hope your issue is solved. Feel free to reopen this if needed.
