### ISSUE TITLE
Empty results after updating to 3

### ISSUE THREAD

**Issue by atouchsimo** [realm/realm-java#4426]
I've update to version ``3.0.0`` tried the ``snapshot`` version too the same issue
``findAll`` returns empty list
``findFirst`` returns null object

**Comment by Zhuinden** [comment]
Updated from what version? And what are you trying to do exactly on which thread? Code sample to reproduce?

**Comment by atouchsimo** [comment]
``2.3.0``

**Comment by beeender** [comment]
Can you produce it with a sample project? With limited information it is difficult for us to tell what is wrong :(

**Comment by atouchsimo** [comment]
i used ``.setAutoRefresh(false)`` changing it to true fixed the issue, is that a normal behavior ?

**Comment by beeender** [comment]
Yes, if the auto refresh is turned off, the realm instance on that thread will not be automatically updated, and all notifications won't be delivered automatically. May I ask why do you need to call `setAutoRefresh(false)`?

**Comment by Zhuinden** [comment]
Well if you call `setAutoRefresh(false)` then Realm won't deliver notifications in which case `RealmChangeListener` won't be called, that's expected behavior.
