### ISSUE TITLE
Spelling mistake in 'Unique values' section of Java documentation

### ISSUE THREAD

**Issue by TonnyL** [realm/realm-java#4428]
https://realm.io/docs/java/latest/#unique-values

There is a spelling mistake of the doc. It may be the `with` rather than `wth`.

![](https://ww1.sinaimg.cn/large/006tNc79gy1feayca79dhj31dm0do41t.jpg)

**Comment by istx25** [comment]
Hi @TonnyL. Thanks for letting us know. I'll get that fixed as quickly as possible.

**Comment by kneth** [comment]
I have fixed it in the documentation. @TonnyL thanks!

Internal note: https://github.com/realm/realm.io/pull/3117
