### ISSUE TITLE
can I query single the value of one object ?

### ISSUE THREAD

**Issue by xiaogu-space** [realm/realm-java#4434]
bacause the object is very large,but I just need one value of the object

**Comment by beeender** [comment]
Realm is always lazy loading, which means even you have a very big string field in a `RealmObject`, as long as you don't access the field, the very big string will never be loaded into the memory. So you don't need to worry about that.

**Comment by Zhuinden** [comment]
You receive a proxy class from Realm, and read the String field only when you access the String field. 

Data is not loaded unless their corresponding fields are accessed.

**Comment by xiaogu-space** [comment]
thanks
