### ISSUE TITLE
io.realm.exceptions.RealmError

### ISSUE THREAD

**Issue by NicoTic** [realm/realm-java#4439]
Unrecoverable error. open() failed: No space left on device in io_realm_internal_SharedGroup.cpp line 113

io.realm.internal.SharedGroup.createNativeWithImplicitTransactions(Native Method)
2 io.realm.internal.SharedGroup.<init>(SharedGroup.java:67)
3 io.realm.internal.SharedGroupManager.<init>(SharedGroupManager.java:47)
4 io.realm.BaseRealm.<init>(BaseRealm.java:76)
5 io.realm.Realm.<init>(Realm.java:126)
6 io.realm.Realm.createAndValidate(Realm.java:246)
7 io.realm.Realm.createInstance(Realm.java:231)
8 io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:114)
9 io.realm.Realm.getInstance(Realm.java:197)
10 com.jw.iworker.db.DbHandler.getRealm(DbHandler.java:43)
11 com.jw.iworker.db.Helper.DbHelper.getRealm(DbHelper.java:18)
12 com.jw.iworker.db.Helper.UserHelper.userWithDictionary(UserHelper.java:32)
13 com.jw.iworker.io.NetworkLayerApi$9.onResponse(NetworkLayerApi.java:234)
14 com.jw.iworker.io.NetworkLayerApi$9.onResponse(NetworkLayerApi.java:227)
15 com.jw.iworker.io.base.JsonObjectRequest.deliverResponse(JsonObjectRequest.java:70)
16 com.jw.iworker.io.base.JsonObjectRequest.deliverResponse(JsonObjectRequest.java:29)
17 com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99)
18 android.os.Handler.handleCallback(Handler.java:725)
19 android.os.Handler.dispatchMessage(Handler.java:92)
20 android.os.Looper.loop(Looper.java:153)
21 android.app.ActivityThread.main(ActivityThread.java:5299)
22 java.lang.reflect.Method.invokeNative(Native Method)
23 java.lang.reflect.Method.invoke(Method.java:511)
24 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:833)
25 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:600)
26 dalvik.system.NativeStart.main(Native Method)

gradle:

        classpath 'com.android.tools.build:gradle:2.2.0'
        classpath "io.realm:realm-gradle-plugin:0.87.5"
        classpath 'com.google.gms:google-services:1.3.0-beta1'

**Comment by beeender** [comment]
As the exception says, there is no disk space left on the device.

This could happen if:
1. The device's disk space is running out because of the system/other app takes too much space. For this case, i don't think you can do anything with it :(
2. The realm db takes too much space because of https://realm.io/docs/java/latest/#large-realm-file-size . To solve this, you should close all the Realm instances properly especially those instances created in the background thread.

**Comment by paulpv** [comment]
That looks like it is an ancient version of Realm!

**Comment by Zhuinden** [comment]
>  classpath "io.realm:realm-gradle-plugin:0.87.5"

That's weird. Realm gradle plugin was released only in 0.88.0

**Comment by zaki50** [comment]
@Zhuinden We started to provide grade plugin earlier that 0.88. 0.88 is the first version which dropped  a support of non-plugin installation.

**Comment by beeender** [comment]
close due to no response.
