### ISSUE TITLE
realm getSchema incorrect return type

### ISSUE THREAD

**Issue by idok595** [realm/realm-java#4443]
realm.getSchema() function return object from type StandardRealmSchema 
this type is object have packcge only access so it is impossible to access his methods,
the only way is to convert this object to (RealmSchema), i think it is mistake 
the return type need to be RealmSchema and not StandardRealmSchema 

realm version in use :3.1.0

**Comment by Zhuinden** [comment]
Yep that does sound like a bug @bmeike

**Comment by zaki50** [comment]
It's a mistake. I'll make a PR to fix this.
Sorry for inconvenience.

**Comment by zaki50** [comment]
We need more fix.

https://github.com/realm/realm-java/blob/releases/realm/realm-library/src/main/java/io/realm/BaseRealm.java#L467
