### ISSUE TITLE
Writing same data should not trigger a RealmCollectionChangeListener notification

### ISSUE THREAD

**Issue by DanteAndroid** [realm/realm-java#4449]
Code(in `onChange`):
```
      OrderedCollectionChangeSet.Range[] modifications = changeSet.getChangeRanges();
        for (OrderedCollectionChangeSet.Range range : modifications) {
            log("notifyItemRangeChanged " + range.startIndex + " to " + (range.startIndex + range.length));
            adapter.notifyItemRangeChanged(range.startIndex, range.length);
        }
```
`getDeletionRanges` & `getInsertionRanges` works well, but when I save the same data to Realm, it seems that Realm still consider it changes(which result in a blink of recyclerview's item).

**Comment by beeender** [comment]
Yes, that is the expected behaviour for now. Realm consider the data is changed even if you write the same data to the same field.

**Comment by DanteAndroid** [comment]
So is there any workaround? I don't want it to trigger. Will you change that behaviour in the future? Thx for quick response.

**Comment by cmelchior** [comment]
Work around right now is that you check before writing to Realm yourself:

```
if (!obj.getString().equals(newString)) {
  obj.setString(newString);
}
```

At this point we are still evaluating if we will change this behaviour in the future, as doing so comes with quite a performance penalty.

**Comment by DanteAndroid** [comment]
I think if the check is done in Realm, the performance penalty may be avoided. Thanks again.

**Comment by cbush** [comment]
We are revamping the Realm docs. We're not ignoring this issue -- we've read through every one of them, and we'll be sure to address this as part of our updates. We're closing the GitHub issues and creating new JIRA tickets to track the work at a high level.
