### ISSUE TITLE
RealmProxy is not generated

### ISSUE THREAD

**Issue by maxmaxandr** [realm/realm-java#4454]
#### Goal
I have tried to update Realm v1.1.0 to Realm v3.1.1 but have the next issue: 
RealmProxy classes don't generate for RealmObject. 

#### Code Sample
I have a simple class like this. It use Parcel, but PremiseRealmProxy not exists so project can not be compiled.
```java
@org.parceler.Parcel(implementations = {PremiseRealmProxy.class},
        value = Parcel.Serialization.FIELD,
        analyze = {Premise.class})
public class Premise extends RealmObject{
....
```
build.gradle
```java 
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.1'
        classpath "io.realm:realm-gradle-plugin:1.1.0"
..
also the latest version of parceler
    compile 'org.parceler:parceler-api:1.1.6'
    apt 'org.parceler:parceler:1.1.6'

```
PS.  I got this warning 
"Warning:Using incompatible plugins for the annotation processing: android-apt. This may result in an unexpected behavior." 
Maybe this reason of error.

#### Version of Realm and tooling
Realm version(s): 3.1.1

Realm sync feature enabled: no

Android Studio version: 2.3.1

**Comment by Zhuinden** [comment]
What is your Gradle plugin order? `apply plugin...`

**Comment by maxmaxandr** [comment]
Resolved for me
Was 
apply plugin: 'realm-android'
apply plugin: 'com.neenbedankt.android-apt'

just changed order on 
apply plugin: 'com.neenbedankt.android-apt'
apply plugin: 'realm-android'

And it works. Thank you.

**Comment by Zhuinden** [comment]
Yeah, the other fix is to apply `android-apt` before `realm-android` :smile:

**Comment by cmelchior** [comment]
Also note that apt is deprecated: https://bitbucket.org/hvisser/android-apt/wiki/Migration

**Comment by maxmaxandr** [comment]
@cmelchior  @Zhuinden  Thank you.  
I missed info about that apt is deprecated.

**Comment by Aks-4125** [comment]
Realm 5.0.0 or higer requires full name including package with `_` 

`@Parcel(implementations = {com_example_test_SomeClassRealmProxy.class},
    value = Parcel.Serialization.BEAN,
    analyze = {SomeClass.class})`
