### ISSUE TITLE
Support Merging RealmObject

### ISSUE THREAD

**Issue by shilch** [realm/realm-java#4456]
I am facing the following problem:

Let's say there is the following data in Table `A`:
```
 id |  text | text2
----+-------+------
123 | "Bla" | NULL
```

Now I create a new instance of A but leave out property `text`:
```java
A a = new A();
a.setId(123);
a.setText2("Hello");
realm. copyToRealmOrUpdate(a);
```

Now, the result looks like this:
```
 id |  text | text2
----+-------+------
123 | NULL  | "Hello"
```
This is of course the expected behavior, however I am looking for a `copyToRealmOrMerge()` method that - the name says it - merges the new object with the existing one. Like `Object.assign()` in JavaScript but here in the Database.
So the merges result would be:
```
 id |  text | text2
----+-------+------
123 | "Bla" | "Hello"
```

Does such a method already exist or can this be implemented?

Thank you in advance!

**Comment by Zhuinden** [comment]
What do you mean?

**Comment by shilch** [comment]
Excuse me, I accidentally hit the `Comment` button and shortly after my router went to sleep :)
I'll have a look at the linked issue.

**Comment by shilch** [comment]
#2288 Talks about excluding fields, I am looking for merging.
However, I read about `createOrUpdateAllFromJson()` which sound promising since I am dealing with a REST Api that not always returns all fields. I will have a look at this method.

**Comment by shilch** [comment]
Okay, `createOrUpdateAllFromJson()` is working fine.
I'll close this issue since this is the solution I am looking for.
