### ISSUE TITLE
Access relationship using one of both objects

### ISSUE THREAD

**Issue by shilch** [realm/realm-java#4457]
I wasn't sure about the title but I hope it is clear to some degree.

Let's assume we have two classes (extending RealmObject) with a one-to-many relationship:
```java
class Group extends RealmObject {
  @PrimaryKey
  private int id;

  private String name;

  private RealmList<Person> persons = new RealmList<>();
}
```
and
```java
class Person extends RealmObject {
  @PrimaryKey
  private int id;

  private String first;

  private Group group;
}
```
So one `Group` has many `Person`s.

Now, creating an instance of `Person` together with a `Group`:
```java
Person p = new Person();
p.id = 123;
p.first = "John";
Group g = new Group();
g.id = 321;
g.name = "Hello World";
p.group = g;
realm.copyToRealmOrUpdate(p);
```

The person and the corresponding group are getting inserted.
However, if we want to access the persons of a group:
```java
g.persons.size(); // = 0
```
The RealmList does not get updated.

It seems that Realm detects two relationships:

1. One `Group` has many `Person`s
2. One `Person` has one `Group`

Is there a way to tell Realm, that this is **one** relationship?
Thank you in advance!

**Comment by Zhuinden** [comment]
You didn't do `g.persons.add(p)`

**Comment by shilch** [comment]
This was an inaccurate explanation.
I'll explain it how I do it:
I get the data via a REST Api with JSON response.
E.g.: a `Person`
```json
{
  "id": 123,
  "first": "John",
  "group": {
    "id": 321,
    "name": "Hello World"
  }
}
```

Now, when I call `createOrUpdateObjectFromJson(Person.class, json)` the person is getting inserted and the group can be accessed using `person.getGroup()`.
But if I now search for the group and call `getPersons()`, the size of the returned list equals 0.
How can I get the `createOrUpdateObjectFromJson` method to add the person to the list in the group object?

**Comment by zaki50** [comment]
Hi @shilch

You can use Inverse Relationships which was introduces Realm Java 3.1.

https://realm.io/news/realm-java-3-1/#inverse-relationships-beta

```java
class Group extends RealmObject {
  @PrimaryKey
  private int id;

  private String name;

  @LinkingObjects("group")
  private final RealmResults<Person> persons = null;
}
```
Please note that it's still a beta feature and you can't use `persons` field in `Group` in query for now.

**Comment by shilch** [comment]
Thank you for your response. This is exactly what I was looking for!
It does not matter that this is beta.
