### ISSUE TITLE
RealmChangeListener not triggered on RealmObject field change

### ISSUE THREAD

**Issue by methelas** [realm/realm-java#4460]
RealmObject `A` contains field `B` which is also a RealmObject.
`B` contains field `C` which is also a RealmObject.
`B` contains field `value` which is Boolean.
`C` contains field `value` which is a Boolean.

When adding RealmChangeListener to `B`, it is not triggered when the `value` of `C` is changed.
Prior to 3.0.0, onChange been triggered on ANY change inside `B` or its fields. Since 3.1.0 it is called only when changing direct fields of `B`, but not fields of its fields.

I attach code example below, that worked prior to 3.0.0, but not anymore. The Log.i() is called only when calling `modifyBvalue`

public class Test {

    private Realm realm;

    private B b;

    public Test() {

        realm = Realm.getDefaultInstance();

        realm.executeTransaction(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {

                A a = realm.createObject(A.class);
                B b = realm.createObject(B.class);
                C c = realm.createObject(C.class);

                a.b = b;
                b.c = c;

                c.value = false;
                b.value = false;
            }
        });

        A a = realm.where(A.class).findFirst();
        b = a.b;

        b.addChangeListener(new RealmChangeListener<RealmModel>() {
            @Override
            public void onChange(RealmModel element) {
                Log.i("ON-CHANGE", b.toString());
            }
        });
    }

    public void modifyBvalue(final boolean newValue) {

        realm.executeTransaction(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {
                b.value = newValue;
            }
        });
    }

    public void modifyCvalue(final boolean newValue) {

        realm.executeTransaction(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {
                b.c.value = newValue;
            }
        });
    }  
}

#### EDIT 1
Also tried with `RealmObjectChangeListener`

#### Version of Realm and tooling
Realm version(s): 3.0.0 / 3.1.0 / 3.1.1

Realm sync feature enabled: no

Android Studio version: 2.2.2

Which Android version and device: OnePlus 3, Android 7.0

**Comment by beeender** [comment]
This is expected behavior:
> If a field points to another RealmObject this listener will only be triggered if the field is set to a new object or null. Updating the referenced RealmObject will not trigger this listener. 

See https://realm.io/docs/java/3.1.1/api/io/realm/RealmObjectChangeListener.html

Before `v3.0.0` it was a false positive notification

Currently you should register a listener on object C if you want be notified when fields of object C change.

**Comment by methelas** [comment]
Thats unfortunate, it was quite useful. 
Thanks anyway :-)

**Comment by Zhuinden** [comment]
@beeender i always kinda wondered though, the `getter` will always return a new instance of the connected proxy class, so where are you supposed to store the connected proxy class in order to prevent it from being eaten alive by the finalizer thread? 😄

**Comment by Zhuinden** [comment]
You might want to keep a reference to the proxy you receive from the getter to which you add the realm object change listener
