### ISSUE TITLE
Remove armeabi from abi splits in FAQ

### ISSUE THREAD

**Issue by mliberato** [realm/realm-java#4464]
#### Goal

Update FAQ so people don't get confused.

#### Version of Realm and tooling
Realm version(s): 2.0.0 +

Please update the following page to remove "armeabi" from abi splits. In fact, if you include it, it will generate a -armeabi version without any native library bundled:

https://realm.io/docs/java/latest/#faq

**Comment by zaki50** [comment]
Hi @mliberato 

Thank you for your reporting.
I'll update our documentation.

**Comment by zaki50** [comment]
I've made a PR in internal repository.

**Comment by zaki50** [comment]
Published.
