### ISSUE TITLE
Does realm provides a "needs update schema / version" notification for synched realms?

### ISSUE THREAD

**Issue by gpulido** [realm/realm-java#4466]
Hello,
I'm using a SyncServer that already has a realm with version 3.0.0.
After the release of realm-java 3.1.1 I want to update my code and my schemas but I have the problem of the right mechanism to do it on clients and the server without losing data. 
I don't know if the following sequence is right:
-First Case:
Synched realm version: 3.0.0. Synched  Realm schema version 1. Client Local realm version: 3.0.0. Realm Schema version 1.
The client already has a right "SyncUser.currentUser" so it can connects and syncs with the synched realm

-Second Case
Synched realm version: 3.0.0. Synched  Realm schema version 1. Client Local realm version: 3.1.1. Realm Schema version 1.
The first time the client tries to connect to the synched realm with the currentUser, it will upgrade synched version to 3.1.1. Is that right? And since then the sync version is 3.1.1

-Third Case
Synched realm version: 3.1.1. Synched  Realm schema version 1. Client Local realm version: 3.0.0. Realm Schema version 1.
This is a client that haven upgrade the app so it holds and old realm version. And tries to connect to the synched realm version. what is going to happen here?

Thank you in advance.
Gabriel

**Comment by beeender** [comment]
Hi!

`v3.0.0` and `v3.1.1` are the realm library versions which means the android realm-java version in your case. And they won't be updated unless you update your apk with the newer version and user installed the updated apk file.

For most cases, the sync protocol is backward-compatible which means the client should work with the old version of realm library. However, there might be cases that the client side realm library needs to be updated to work with the newer version of realm-object-server.

**Comment by gpulido** [comment]
@beeender 
From the changelog for realm-java 3.1.0:
"Updated file format of Realm files. Existing Realm files will automatically be migrated to the new format when they are opened, but older versions of Realm cannot open these files."

So if I have one client that connects using a 3.1.1 to a sync server with a 3.0.0 I guess it migrates the server version to the new format. If so, what happens with clients with version 3.0.0 that connects to the 3.1.1 synched realm? the changelog claims that it can't open the file.

I asume that there will be cases where the user must update, Is there any kind of exception that could be caught to inform the user that it must update before closing the app?

**Comment by beeender** [comment]
I think in this case your client with realm-java `3.0.0` will stay at the old db file format version.

But let me confirm this with our core guys then get back to you.

**Comment by gpulido** [comment]
Thank you, I will wait for the answer.

Also I think I will have the same problem with schema versions, when a client with an old version of app with an old realm schema connects to a syncserver that already has been upgraded, what happens there?

**Comment by beeender** [comment]
Check with our sync guys.

1. Server side Realm lib version VS client side Realm lib version.
We keep the protocol backward-compatible as much as we can, which means even you updated the server side Realm, the client should just work with the old lib version. But, if there is something we have to fix it in the protocol side, a `WRONG_PROTOCOL_VERSION` will be passed to your sync session error handler, and you can handle that to ask user update the apk.

2. schema version update:
This can be seen in our doc https://realm.io/docs/java/latest/api/io/realm/SyncConfiguration.html
> Synchronized Realms only support additive migrations which can be detected and performed automatically, so the following builder options are not accessible compared to a normal Realm:

additive migration is the only one we supported to sync Realm right now.

**Comment by gpulido** [comment]
Thank you so much for the clarification. The WRONG_PROTOCOL_VERSION is what I was looking for as it allows me to detect such case and inform properly the user.
Regarding the schema, I already knew about the restriction (I hope it could be modified on the future), but what happens when I add a new field to an RealmObject (that would increase the schema number if there where any) so the realmserver has the "updated schema" and one old client (with the not updated schema) connects to the server? I guess that a different configuration exception will be thrown, won't be?

**Comment by Zhuinden** [comment]
> But of cause, you still need to handle the mismatched schema in your new version of app.

What do you mean?

**Comment by beeender** [comment]
@Zhuinden 
eg.: 
you have two devices running different schema versions for sync Realm:
v1:
```java
public class Person {
    String name;

    public String getName() {
        return name;
    }
}
```

v2:
```java
public class Person {
    String name;
    String firstName;
    String lastName;
    public String getName() {
        return firstName + LastName;
    }
}
```

For the device running with v1, it would have no idea that `firstName` and `lastName` are added in v2, which means it change the `name` and the db synced to the device with the v2 data, it is v2's responsibility to still handle those data changes from old version if it still want to display the name correctly.

**Comment by beeender** [comment]
> but what happens when I add a new field to an RealmObject (that would increase the schema number if there where any) so the realmserver has the "updated schema" and one old client (with the not updated schema) connects to the server? I guess that a different configuration exception will be thrown, won't be?

In this case, the device with old version will just migrate the schema with new fields included automatically. And I think there is no notification will be sent. In this case, you can check the schema version instead.

But after checking our code & documentation, there seems to be something wrong:
The doc shows this is not available for `SyncConfigration`
```
 *     <li>{@code schemaVersion(long version)}</li>
```
But the below code is actually there:
```java
        /**
         * Sets the schema version of the Realm. This must be equal to or higher than the schema version of the existing
         * Realm file, if any. If the schema version is higher than the already existing Realm, a migration is needed.
         *
         * @param schemaVersion the schema version.
         * @throws IllegalArgumentException if schema version is invalid.
         */
        public Builder schemaVersion(long schemaVersion) {
            if (schemaVersion < 0) {
                throw new IllegalArgumentException("Realm schema version numbers must be 0 (zero) or higher. Yours was: " + schemaVersion);
            }
            this.schemaVersion = schemaVersion;
            return this;
        }
```

The doc needs to be fixed. Relevant issue: #3982

@bmeike @cmelchior

**Comment by cmelchior** [comment]
`schemaVersion` must be bumped for a device to upgrade the schema locally, as in, when you open the Realm we compare the schemas and if a migration is needed, the schemaVersion must be incremented. This is so you don't accidentally make a change to schema that makes it into the wild, because once such a change has been synced to other devices, it is pretty hard to get rid of. 

I'll update the docs.
