### ISSUE TITLE
Auto Compaction

### ISSUE THREAD

**Issue by diegomontoya** [realm/realm-java#4468]
Initially I was going to post this to core but on second thought, this feature can be better addressed within the java/cocoa api wrapper.

Related to https://github.com/realm/realm-core/issues/2343

Realm needs auto-compaction and I don't mean compact on startup since there are times when it is too late for the app to crash due to OOM and do compaction on next startup. The realm data file size explosion issue has actually already existed pre v2.0 with improper usage and now with log data, the problem has manifested into a more critical issue for more users with pure normal usage. It was already an issue before v2.0, but the log/data merge has lit a fire to it. 

Don't get me wrong, we still need smaller transaction logs. But the long game is compaction, auto-compaction, and some self awareness within realm to tell itself, "Hey I have this gigantic idle log section or hundreds of smaller free pieces that total to a huge number that no one is using and waiting for someone to recycle me in the not so distant future is pure speculation at best. Perhaps I should auto-compact myself now."  

For example, let users set sane free-space percentage of 10% space within realm for data growth and logs. Once the limit is reached, do a stop-the-world compaction. A 200ms pause on UI can be a better choice than an exponential increase in chance that a user app crashes.

**Comment by beeender** [comment]
My first thought was the ongoing cocoa feature compact on launch https://github.com/realm/realm-cocoa/pull/4755 . If we need that implemented in the java side, we also need to  consider the time compact operation will take, #2299 will be a necessary thing to have.

But actually what you are asking is basically Realm db file garbage collection which we have been discussed internally (cannot find any core issue is tracking that @finnschiermer )

Do you think if the `compact on launch` will be good enough to solve the problem in the real world?

**Comment by Zhuinden** [comment]
Compact on launch can slow down start-up quite badly, this is why I moved it to "compact when all activities are closed"

**Comment by diegomontoya** [comment]
@beeender compact on launch is only a stop gap fix and as @zhuinden mentions, doing so can perhaps cause havoc on launch ui speed exepectations of an end user. 

The core issue is internal idle space auto-compaction/gc should be semi-automatic and not 100% controlled by realm developer since realm dev does not know how/when/by how much any realm transaction or api can impact internal memory/space. There is a lot of logic that is hidden and rightfully so by realm core which impacts file size.

Within current feature set a realm dev can do this:

1) wrap/extend realm transaction with custom onsuccess code that check n compares file size after each transaction
2) check freeable() is greater than 15% of file size
2) check if realm ref count is zero
3) check.if currently on non-Ui thread
4) acquire lock on realm and do compaction

I can do this and.plan to do this but the more I think about it the more i feel like it is something that should be more naturally handled within realm and not externally.

**Comment by Zhuinden** [comment]
Compact on launch will be pretty nice if asynchronous opening Realm is also added. 

According to https://realm.io/news/realm-objc-swift-2.6/ cocoa has this

**Comment by cmelchior** [comment]
Yes, this will added to Java as well: #2299 and your right that it would work nicely with compactOnLaunch

**Comment by cmelchior** [comment]
`getInstanceAsync()` was added in 3.2 and `compactOnLaunch()` will be released in 3.5. This means you can create whatever policy makes sense in your app and then run the compaction on a background thread.

Any further changes to this will not happen as part of the Java API's in terms of `auto-compact`, but by re-using or freeing space more intelligently. This is being tracked by e.g. https://github.com/realm/realm-core/issues/984,  so I'll close this issue on the Java side.
