### ISSUE TITLE
NoSuchMethodError for notifyChangeListeners thrown on Realm 3.1

### ISSUE THREAD

**Issue by Jeff11** [realm/realm-java#4473]
Since we updated to Realm 3.1, we get these crashes.

> Fatal Exception: java.lang.NoSuchMethodError: no method with name='notifyChangeListeners' signature='([Ljava/lang/String;)V' in class Lio/realm/internal/OsObject; at io.realm.internal.SharedRealm.nativeCommitTransaction(SharedRealm.java) at io.realm.internal.SharedRealm.commitTransaction(SharedRealm.java:251) at io.realm.BaseRealm.commitTransaction(BaseRealm.java:320) at io.realm.Realm.commitTransaction(Realm.java:127) at io.realm.Realm.executeTransaction(Realm.java:1348)

**Comment by Zhuinden** [comment]
Just got fixed in https://github.com/realm/realm-java/issues/4463

**Comment by beeender** [comment]
yeah, and see workaround https://github.com/realm/realm-java/issues/4463#issuecomment-293150605

**Comment by Jeff11** [comment]
oh thanks guys
