### ISSUE TITLE
Jenkins `java-merge-releases-into-master` project is broken

### ISSUE THREAD

**Issue by larkost** [realm/realm-java#4477]
The internal Jenkins project `java-merge-releases-into-master` is currently broken. It is not clear to me what the goal is on this project, but the proximate failure is because it is doing a `git pull` without the credentials that are implicitly added to steps like the preceding `checkout` step (which is working).

A naive solution to this would be to change the `git checkout` to `git merge --ff-only origin/master`, which would avoid the network request that is currently causing the failure. But understanding the goal might lead to a better solution.

**Comment by cmelchior** [comment]
@emanuelez ☝️

**Comment by emanuelez** [comment]
The job is a relic of the past. It has now been deleted.
