### ISSUE TITLE
Persist and Fetch operations on huge data

### ISSUE THREAD

**Issue by RameshReddyKolla** [realm/realm-java#4481]
## Goals

Trying to persist and fetch 2 lakh records into realm DB table.

## Expected Results

Persist and fetch the data in the faster way(less time).

## Actual Results
Taking a long time to perform save and fetch operations on the table of 2 lakh records.

## Code Sample
// Persisting Operation
 mRealm.beginTransaction();
  mRealm.createAllFromJson(City.class, cityJson); // cityJson.json  is the assets file with 2 lakh records
 mRealm.commitTransaction();

// Fetch Operation
RealmResults<City> realmResults = mRealm.where(City.class).findAll(); 

#### Version of Realm and tooling
Realm version(s): 3.1.0

Realm sync feature enabled: no

Android Studio version: 2.3

Which Android version and device: 6.0 & Nexus6(emulator)

**Comment by Zhuinden** [comment]
Writes should happen on a background thread for a reason.

**Comment by RameshReddyKolla** [comment]
Fetch Operation is taking a long time.Any suggestions?

**Comment by Zhuinden** [comment]
`findAllAsync()` + `RealmChangeListener`

**Comment by RameshReddyKolla** [comment]
will RealmChangeListener help us in reducing the fetch query execution time?

I know that RealmChangeListener will notify us when modifications are done on Realm object or Realm Results.

**Comment by Zhuinden** [comment]
`findAllAsync()` executes the query on background thread, and provides the results to UI thread only when results is evaluated - but this is provided through RealmChangeListener

**Comment by RameshReddyKolla** [comment]
yeah, correct. But can we reduce execution time taken by the query with large data.

**Comment by zaki50** [comment]
Could you show us the code that takes large execution time?

**Comment by beeender** [comment]
close due to no response.
