### ISSUE TITLE
When inserting an object with a null required field: say which one

### ISSUE THREAD

**Issue by BoD** [realm/realm-java#4484]
#### Goal

Currently, when trying to insert an object that has a `null` field which is required, the exception looks like this:

```
java.lang.IllegalArgumentException: Illegal Argument: This field is not nullable.
```
Unfortunately my object has many fields, and so it's a waste of time trying to debug what the issue is.

#### Expected Results

Please change the message to something like `The field 'fooBar' is not nullable.`

#### Version of Realm and tooling
Realm version(s): 3.1.0

Realm sync feature enabled: no

Android Studio version: 2.4 Preview 5

Which Android version and device: Emulator API level 23

**Comment by zaki50** [comment]
@BoD thank you for your report. I'm woking on it.

**Comment by zaki50** [comment]
I've made a PR to fix this (#4491)

**Comment by zaki50** [comment]
@BoD the fix has been merged into both `releases` and `master` branch.
It will be available in the next release.

**Comment by BoD** [comment]
Great responsiveness! Thanks a lot 👍

**Comment by zaki50** [comment]
@BoD Realm Java 3.1.3 which contains this fix has been released.
