### ISSUE TITLE
Are your docs correct?

### ISSUE THREAD

**Issue by Schrobie** [realm/realm-java#4496]
I see this in the latest docs and it seems to me that "result.removeChangeListeners()" should really be "realm.removeAllChangeListeners()" is that correct?

<img width="633" alt="screen shot 2017-04-13 at 9 12 12 pm" src="https://cloud.githubusercontent.com/assets/4185372/25032036/313c193c-208e-11e7-82fa-6cf1327ea85d.png">

**Comment by beeender** [comment]
uh, it should be `removeAllChangeListeners()`. will fix it right now.

**Comment by beeender** [comment]
https://github.com/realm/realm.io/pull/3158 will fix this.

**Comment by beeender** [comment]
Fix merged. The website will be updated soon.
