### ISSUE TITLE
add/remove listeners in onStart/onStop causes crash

### ISSUE THREAD

**Issue by cknibbe** [realm/realm-java#4502]
#### Goal
Starting with Realm 3.1.0, I can cause a crash by adding/removing a RealmObject listener in onStart/onStop.

I have created a test project, with a junit test.  The junit test passes when using Realm 3.0.0, but crashes with Realm 3.1.0, 3.1.1, and 3.1.2

Goal: not crash.

#### Actual Results

The junit error is:

> Test failed to run to completion. Reason: 'Instrumentation run failed due to 'Native crash''. Check device logcat for details

The logcat:
[logcat.txt](https://github.com/realm/realm-java/files/923781/logcat.txt)

#### Steps & Code to Reproduce

To reproduce the problem, download the Android Studio project (RealmBug) in the given repo, and run the test "test()".

The test project is comprised of 2 activities.  MainActivity has a RealmObject. It adds/removes a listener to the RealmObject in onStart/onStop.  SecondActivity is effectively empty.

To see the problem (this is what the junit test "test()" does):

- start MainActivity
MainActivity.onStart() will attach listener to RealmObject
- click on the button to launch SecondActivity
MainActivity.onStop() will remove listener from RealmObject
- click on the back arrow, to return to MainActivity
MainActivity.onStart() is called, then crash happens

Observations:

- If the call to "removeAllChangeListeners" in onStop() is commented out, the program no longer crashes
- If the call to "removeAllChangeListeners" is replaced by "removeChangeListener", the program still crashes

#### Code Sample

[https://clo_knibbe@bitbucket.org/clo_knibbe/realmbug.git](url)

#### Version of Realm and tooling
Realm version(s): 3.1.0, 3.1.1, 3.1.2

Realm sync feature enabled: no

Android Studio version: 2.3

Which Android version and device: Nexus 7 AVD, API 23

**Comment by zaki50** [comment]
Hi @cknibbe 

Thank you for the detailed report.
I'll investigate it.

**Comment by zaki50** [comment]
I reproduced the crash on `Nexus 7 AVD, API 23, armeabi-v7a`.

`Nexus 7 AVD, API 23, x86` worked fine.

**Comment by beeender** [comment]
Parsed stack trace. looks like a bug in Object Store.

```
********** Crash dump: **********
Build fingerprint: 'Android/sdk_google_phone_x86_64/generic_x86_64:7.1.1/NYC/3756122:userdebug/test-keys'
pid: 2450, tid: 2467, name: le.clo.realmbug  >>> com.example.clo.realmbug <<<
signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x10
Stack frame #00 pc 00000000000e10eb  /data/app/com.example.clo.realmbug-1/lib/x86_64/librealm-jni.so: Routine realm::_impl::ObjectNotifier::do_attach_to(realm::SharedGroup&) at sfp-exceptions.c:?
Stack frame #01 pc 00000000000ecb70  /data/app/com.example.clo.realmbug-1/lib/x86_64/librealm-jni.so: Routine realm::_impl::RealmCoordinator::run_async_notifiers() at sfp-exceptions.c:?
Stack frame #02 pc 00000000000ed1a2  /data/app/com.example.clo.realmbug-1/lib/x86_64/librealm-jni.so: Routine realm::_impl::RealmCoordinator::on_change() at sfp-exceptions.c:?
Stack frame #03 pc 00000000001076bc  /data/app/com.example.clo.realmbug-1/lib/x86_64/librealm-jni.so: Routine realm::_impl::ExternalCommitHelper::DaemonThread::listen() at sfp-exceptions.c:?
Stack frame #04 pc 0000000000107779  /data/app/com.example.clo.realmbug-1/lib/x86_64/librealm-jni.so: Routine _ZNSt6thread5_ImplISt12_Bind_simpleIFZN5realm5_impl20ExternalCommitHelper12DaemonThreadC4EvEUlvE_vEEE6_M_runEv at external_commit_helper.cpp:?
Stack frame #05 pc 000000000023a990  /data/app/com.example.clo.realmbug-1/lib/x86_64/librealm-jni.so: Routine execute_native_thread_routine at /s/ndk-toolchain/src/gcc/gcc-4.9/libstdc++-v3/src/c++11/thread.cc:84
Stack frame #06 pc 00000000000897f1  /system/lib64/libc.so (_ZL15__pthread_startPv+177)
Stack frame #07 pc 0000000000029a6b  /system/lib64/libc.so (__start_thread+11)
Stack frame #08 pc 000000000001cae5  /system/lib64/libc.so (__bionic_clone+53)
```

**Comment by cknibbe** [comment]
I see on the linked bug report that the problem has been fixed.  Thanks for handling it so promptly!

Can I expect it to be included in your next patch release?  Any idea when that might be?

**Comment by beeender** [comment]
@cknibbe Sorry for the late response, the fix has been merged to master, so you should be able to use it with our snapshot release in 1 hour (I guess :P )

We will make a patch release in this week.

**Comment by cknibbe** [comment]
@beeender Thanks!
