### ISSUE TITLE
JNI getX() methods returns fake data when it should throw exception or just crash

### ISSUE THREAD

**Issue by diegomontoya** [realm/realm-java#4505]
There are code in checked/UncheckedRow, table jni getX() that returns phantom data when row check fails. 

example:
https://github.com/realm/realm-java/blame/master/realm/realm-library/src/main/cpp/io_realm_internal_CheckedRow.cpp#L85

Returning a phantom value for an invalid row is worse than throwing exceptions. I would expect the code to  crash or throw an exception.

**Comment by zaki50** [comment]
`ROW_AND_COL_INDEX_AND_TYPE_VALID` is actually throwing an exception to Java layer.

It is calling `ThrowException` https://github.com/realm/realm-java/blob/d0644234ecb4ed9ed460565a3535e3e53f2e8df1/realm/realm-library/src/main/cpp/util.cpp#L127 and `ThrowException` is calling `env->ThrowNew(jExceptionClass, message.c_str());` https://github.com/realm/realm-java/blob/d0644234ecb4ed9ed460565a3535e3e53f2e8df1/realm/realm-library/src/main/cpp/util.cpp#L187

Calling `env->ThrowNew()` then returning fake value is a normal way to throw an exception from JNI to Java .

**Comment by diegomontoya** [comment]
@zaki50 Got it. Exceptions thrown deeper within isValid() inlined methods. 

How about https://github.com/realm/realm-java/blame/master/realm/realm-library/src/main/cpp/io_realm_internal_CheckedRow.cpp#L125

Shouldn't above code return NULL? Also with jbytearray get method.

To make it consistent with https://github.com/realm/realm-java/blame/master/realm/realm-library/src/main/cpp/io_realm_internal_CheckedRow.cpp#L38

**Comment by zaki50** [comment]
@diegomontoya Agree. I think they should be `NULL` OR `nullptr` though I'm not a C++ expert..

What do you think @beeender @kneth ?

**Comment by beeender** [comment]
yup, `nullptr` will be better. I will fix this.
