### ISSUE TITLE
GoogleSignInResult returns Status{statusCode=unknown status code: 12501, resolution=null} when requesting Token

### ISSUE THREAD

**Issue by ojarabo** [realm/realm-java#4509]
Hi there,
I am trying to enable google auth in my app. I have been following your example, but it didn't work. 

In you example, you request the IdToken in the GoogleSignInOptions.Builder 
```java
GoogleSignInOptions gso = new GoogleSignInOptions.Builder(GoogleSignInOptions.DEFAULT_SIGN_IN)
                .requestEmail()
                .requestIdToken(fragmentActivity.getString(R.string.server_client_id))
                .build();
```
to later use it onRegistrationComplete 
```java

 googleAuthLogin     = new GoogleAuth((Button) findViewById(R.id.google_default_button), this) {
            @Override
            public void onRegistrationComplete(GoogleSignInResult result) {
                UserManager.setAuthMode(UserManager.AUTH_MODE.GOOGLE);
                GoogleSignInAccount acct = result.getSignInAccount();
                SyncCredentials credentials = SyncCredentials.google(acct.getIdToken());
                SyncUser.loginAsync(credentials, AUTH_URL, SplashScreenActivity.this);
            }

            @Override
            public void onError(String s) {
                super.onError(s);
            }
        };
```

I have registered my app in the google console as an Android Client. However, during the execution, my app never got onRegistrationComplete because GoogleSignInResult returned a status code 12501.

I have been researching for a while an I have discovered that if I enabled the Outh client as a web application the error would disappear. However, my app will never reach onSuccess. It would instead call onError with a value of INVALID_CREDENTIALS. This is caused because the IdToken is linked to the web application and not to the Android Client, so the credentials don't match.  

Could you please clarify if the app has to be only declared as a web application or if I am doing something else wrong?

Thanks

**Comment by Zhuinden** [comment]
I've seen similar error in firebase-auth where the problem was that the keystore SHA-1 was mismatched compared to the Firebase console.

So this error might not be obvious.

**Comment by ojarabo** [comment]
Hi @Zhuinden,
I haven't register my app in Firebase console, but only in google console. Should I register the app in both places?

**Comment by dalinaum** [comment]
@ojarabo I don't think so. GoogleAuth doesn't depend on Firebase.

Please check SHA-1 key, `applicationId` of build.gradle and other stuffs again. Something doesn't match with your console's setting.

**Comment by ojarabo** [comment]
@dalinaum 
Thanks for the info. I have deleted the credentials in google console in order to create then again. What kind of credentials should I create, a web app or an android app? because if I create as android app, GoogleSignInResult will return code 12501 when requesting idToken. 

Thanks

**Comment by dalinaum** [comment]
Credentials should be for an android app. There are many reasons that users encounter an error code 12501. If registered SHA-1 key is for release and a user uses a debug app, a user encounters 12501. Sometimes `applicationId` of build.gralde doesn't match with a registered id. Please check your console and your android studio carefully. A very small difference can make the problem.

Thanks.

**Comment by ojarabo** [comment]
@dalinaum  @Zhuinden 
Thanks for your contribution and help. I deleted the project from the Google console and created a clean one. I checked the suggested points of conflicts, but everything seemed correct. I don't know if the problem was that the certificates and the configuration of the project was created on the fly. Now, it is working perfectly. 

Many thanks. I really appreciate.

**Comment by dalinaum** [comment]
@ojarbo No problem. I am happy to hear that your app is working perfectly now.
