### ISSUE TITLE
Declare model/field names via annotations like @RealmClass.

### ISSUE THREAD

**Issue by dmytrodanylyk** [realm/realm-java#451]
Currently table column name equals to object variable name. I think is not safe, as if someone re-name variable -> `Proxy` is re-generated which lead to database migration. I think it will be better to have possibility to declare table column names via annotations. E.g.

```java
public class User extends RealmObject {

	@Row("id")
	private int id;
	@Row("age")
    private int age;
	@Row("first_name")
    private String name;

}
```

P.S. I know you have a lot of work but it would be great if you can share your TODO list, to know what to expect in next version.

**Comment by cgcgbcbc** [comment]
+1 for this feature

**Comment by mrexmelle** [comment]
This feature will be useful to help organizations that enforce certain coding convention (in particular to naming attribute of a class). Hopefully this feature will chip in soon.

**Comment by navjotbedi** [comment]
+1 for this feature.

**Comment by cmelchior** [comment]
Folding this issue into #1470. Lets continue the discussion there.

**Comment by issamux** [comment]
Features absolutely Needed , like one in Android Room 
  `@ColumnInfo(name` = Constants.DESTINATION)
   `public` String destination;
