### ISSUE TITLE
Realm too slow?

### ISSUE THREAD

**Issue by methelas** [realm/realm-java#4510]
So heres the deal:

I have an RealmObject called "A" which contains RealmList\<B>. B are also a RealmObject.
In background service I'm updating object A with a new RealmList\<B> containing several B objects. Whole update takes place in transaction. 

AFTER(!) calling `realm.commitTransaction();` I'm sending event from the service to activity to open next fragment.
Said fragment is about to display B objects in a list. So I query my object A(as I need some other things from it) and then i try to get position 0 from its RealmList\<B> but... its not there... yet!

I'm getting 
`java.lang.ArrayIndexOutOfBoundsException: rowIndex > available rows: 0 > 0`
but only when I query it right away. The error wont occur if i delay sending event from service to activity by 1 sec or so.

it never happened before until I've updated my os to 7.1.1
It's like `realm.commitTransaction();` doesn't take place immediately but with slight(few hundrets millis) delay

Affected device is:
OnePlus 3, OxygenOS 4.1.3(which is based on Android 7.1.1)

#### Version of Realm and tooling
Realm version(s): 3.1.1 - 3.1.2

Realm sync feature enabled: no

Android Studio version: 2.2.2

Which Android version and device: OxygenOS 4.1.3(Android 7.1.1), OnePlus 3 (A3003)

**Comment by Zhuinden** [comment]
You can try [this](http://stackoverflow.com/a/38839808/2413303) in your event receiver and see if it helps.

**Comment by cmelchior** [comment]
@methelas Realm gives each thread a snapshot of your data. It is not the same snapshot across all threads. We use the Looper to coordinate updating the changes. This means that sending your own notification is usually the wrong way to go about it and there is a high change the the thread reciving your own notification hasn't been fully updated yet.

Instead, you should register a `RealmChangeListener` on the data you are interested in and react to that.

**Comment by methelas** [comment]
It's all clear for me now. I was under impression that everything happens immediately when you commit transaction and so far I haven't faced this issue. Turns out I was just lucky.
Thanks for help, I've added realmChangeListener now and it seems to be working fine.
Thanks again :)
