### ISSUE TITLE
RealmObject as a byte array

### ISSUE THREAD

**Issue by lbensaad** [realm/realm-java#4511]
#### Goal
 1 - Convert  a RealmObject to byte[]
 2 - Convert a byte[] to RealmObject

In order to save any ReamlObject to a file I think it should be converted first to a byte[] in internal implementation of Realm. So, is it possible to expose that byte[] to use it in Java, 

#### Expected Results

if a class User extends RealmObject, I want to be able to convert any User object to byte[] and vice versa like this 
` User user = new User(id,name, email);`
`byte[] userData = user.toByteArray();`
`User user2 = new User(userData); `

**Comment by cmelchior** [comment]
Hi @lbensaad. I'm not entirely sure what you are trying to accomplish? 

Realm will automatically serialise the object to disk, this is not something you as a user of Realm have to do.

If you want to serialize the object yourself for some reason I would probably recommend using GSON or some other JSON library, since storing the binary representation of a Realm Object has a high chance of not working as you expect since data in Realm is exposed through Proxy classes that are not easily serializable.

**Comment by lbensaad** [comment]
Thanks @cmelchior. I need it to send the object over the network to the server after it is stored locally in Realm. But as you said, the server will not know how to deserialize them. I just did not want to add a serialization library, but this seems inevitable. I will see how to use Flatbuffers with Realm.

**Comment by Zhuinden** [comment]
@lbensaad why not JSON?

**Comment by lbensaad** [comment]
@Zhuinden, I think binary is faster in parsing and smaller than JSON

**Comment by nhachicha** [comment]
@lbensaad have you thought about using [realm-mobile-platform](https://realm.io/products/realm-mobile-platform/) 
The object will be synced so you don't have to worry about serialising or networking.

**Comment by lbensaad** [comment]
Yes @nhachicha, but it is payable, I do not want to use it, I am trying gRPC

**Comment by dalinaum** [comment]
Hello @nhachicha 

Although binary is faster and smaller than JSON, it seems hard to support by Realm. Supporting `toByteArray` method may require Realm to assume some binary representations and invest time and effort to maintain them.

I think the practical answer is to create a converter that converts between JSONs and binaries.

**Comment by nhachicha** [comment]
@lbensaad [Developer Edition](https://realm.io/pricing/) is free though, I think it covers your use case.

**Comment by lbensaad** [comment]
@dalinaum I think the function toByteArray is already implemented in the internals of Realm, I just wanted them to expose it in the API.
Thanks brother @nhachicha, but for me it will be expansive in production. I have a website that has 10k visitors per day, and I am converting it to app because 70% of the visitors are using mobile (Android), and it may grow bigger. So I prefer to invest some extra time now developing the server side rather than to be bound to a life time payment.
I am still testing gRPC, but I think it will be perfect as it will save my time writing the net protocole, but I will need some extra code to convert from protobuf to RealmObject, that is all. if RealmObject exposes the toByteArray, then I will not need that extra conversion code.
That is why I asked of that function. just to use it when sending object over the net.

**Comment by cmelchior** [comment]
Realm doesn't represent single objects as byte arrays internally, so what you are asking is not possible, nor will it be. Also keep in mind that JSON gzips really well, so the difference between byte arrays and json is probably not as large as you think.

**Comment by cmelchior** [comment]
I'm closing this issue as a Won't Fix. You can definitely convert Realm Objects to some other representation on the wire: bytes, json, whatever, but that is all outside the scope of Realm. Just converting objects to JSON is the responsibility of e.g GSON instead of Realm.

**Comment by lbensaad** [comment]
Thanks @cmelchior, understood

**Comment by Zhuinden** [comment]
And if they were raw byte[], then interpreting them according to a given schema would also come with problems of migration, what fields a given class has, etc. so that'd be very risky.
