### ISSUE TITLE
Cannot access the Realm object attributes from a secondary thread.

### ISSUE THREAD

**Issue by matheus511377** [realm/realm-java#4514]
(I'm starting with Realm) I'm using a REALMLIST that owns a product object. A product list. I can usually access the main thread, but on a secondary thread, I can not access the attributes of the product object. Any tips?

//it works
for (PreVenda item : preVendaList) {
    item.getProduto.getDescricao
}

//It does not work
 new Thread(new Runnable() {
        for (PreVenda item : preVendaList) { 
            item.getProduto.getDescricao
         }
}).start();

**Comment by beeender** [comment]
See https://realm.io/docs/java/latest/#threading

**Comment by Zhuinden** [comment]
You need to open a Realm instance on the background thread, and query `preVendaList` from that Realm instance. Then, you should close the Realm instance when the thread ends (use `try(Realm realm = Realm.getDefaultInstance()) { ... }`

**Comment by bmeike** [comment]
Hey @matheus511377 
Haven't heard from you in a while, so I'm assuming that documentation got you back on course.  If you have an other issues, by all means open a new ticket... or, better yet, ask your question on StackOverflow.
