### ISSUE TITLE
Doubts about users accessing to their own private data or others public data

### ISSUE THREAD

**Issue by ojarabo** [realm/realm-java#4516]
Hi there, 
I have a question about accessing data created by the user. I will explain below with a case study.

Lets say that I have an app using Realm Mobile Platform. The app uses Realm Auth to allow users to register by email, google and facebook account. 

Imaging that I have UserA and UserB. Once the users have registered in the app, they would be redirected to a project activity. Each user would be able to create their own projects. Before Realm Mobile Platform (Realm Mobile Database), user data was stored in user devices. When users entered in the project activity, the activity requested all the existing projects.

With the Realm Mobile Platform, both share same Realm. So, if the app requests exiting projects, realm would return all the exiting projects belonging to both UserA and UserB. A way to solve this would be adding an user identifier (index) to the project  realmObject and requesting all the projects where the user identifier equals the current user identifier. Therefore, UserA and UserB would only see their own projects.

However, there is a search activity where users can search for public projects. For example, the UserA makes public Project1. UserB should be able to find Project1 and follow it, or ask the owner to become a contributor. In both cases, UserB would be able to see the Project1 in the Project activity (ignoring the user privileges in Project1). For this case, projectRealmObject could contain a list of users with their project privileges and request projects that users are subscribed or collaborating with. 

Another possible way would be creating a UserRealmObject, since SyncUser doesn't contain much info about the user, containing a list of project (owned, subscribed, and collaborating).

What I would like to know is: is there a better way of doing this with realm? or are there any best practices working with realm in this matter?

Thanks

**Comment by dalinaum** [comment]
Hello @ojarabo 

Generally, each user has a different Server URL, indeed. If Server URL is `String serverURL =" realm: //my.realm-server.com: 9080 / ~ / default ";`, then the `~` will replace the user's ID. So each user will access a different database.

**Comment by ojarabo** [comment]
Thanks @dalinaum.
We are studying the info you sent. We will reopen the issue in case we have further doubts on the matter to not keep you waiting. 

Thanks again, truly appreciate it.

**Comment by ojarabo** [comment]
Hi there, 
I am reopening the issue because we have been trying to create a global file and give write/read privilege to all user in order to allow all user to share data between them as it was suggested. I am logging in the app with Realm Object Server Admin, who is supposed to have the admin privilege to create global files. However, nothing is working. We posted a question about it [here](https://github.com/realm/realm-mobile-platform/issues/189) a week ago with no answer. You will find the code we are using there. 

Moreover, every time the Admin is logging into the app and try to create a global file, the Realm Object Server is throwing a trace in the log tap. 

> [proxy] internal error. Code undefined, status: undefined, message: SyntaxError: Unexpected token j in JSON at position 0 at Object.parse (native) at ProxyService.webSocketUpgradeHandler (/usr/lib/nodejs/realm-object-server-developer/.build/src/node/services/proxy.js:104:30) at ProxyService.safeUpgrade (/usr/lib/nodejs/realm-object-server-developer/.build/src/node/services/proxy.js:78:12) at emitThree (events.js:116:13) at Server.emit (events.js:194:7) at onParserExecuteCommon (_http_server.js:411:14) at HTTPParser.onParserExecute (_http_server.js:379:5)

Could you please help us with that. 
Thanks

**Comment by kneth** [comment]
@ojarabo Was the suggestion in https://github.com/realm/realm-mobile-platform/issues/189 useful for you?

**Comment by beeender** [comment]
https://github.com/realm/realm-java/issues/4516#issuecomment-304252816 should be fixed by 3.3.2 . Close this issue now.
