### ISSUE TITLE
RealmObjectChangeListener Not call

### ISSUE THREAD

**Issue by henjue** [realm/realm-java#4521]
MainActivity.java
```java

    @Override
    protected void onPause() {
        super.onPause();
        PomeloUtils.getInstance().setNotify(false);
        if (matches != null) matches.removeAllChangeListeners();
        if (realm != null) {
            realm.close();
        }
    }

    @Override
    protected void onResume() {
        super.onResume();
        PomeloUtils.getInstance().setNotify(true);
        realm = Realm.getDefaultInstance();
        matches = realm.where(Matche.class).findAll();
        matches.addChangeListener(new RealmChangeListener<RealmResults<Matche>>() {
            @Override
            public void onChange(RealmResults<Matche> matches) {
                setOnScoreListener(matches);
            }
        });
        setOnScoreListener(matches);
    }

    private void setOnScoreListener(RealmResults<Matche> matches) {
        for (Matche matche : matches) {
            RealmObject.addChangeListener(matche, this);
        }
    }

    @Override
    public void onChange(Matche matche, ObjectChangeSet objectChangeSet) {
        //No call here
        LogUtils.d(LOG_TAG, "objectChangeSet:%s", Arrays.toString(objectChangeSet.getChangedFields()));
    }
```
GamePushService.java
```java
        Realm.getDefaultInstance().executeTransactionAsync(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {
                RealmResults<Matche> matches = realm.where(Matche.class).findAllSorted("orderIndex");
                if (matches.size() > 0) {
                    Matche matche = matches.get(0);
                    if (new Random().nextBoolean()) {
                        matche.getHome().setScore(matche.getHome().getScore() + 1);
                    } else {
                        matche.getVisite().setScore(matche.getVisite().getScore() + 1);
                    }
                }
            }
        });
```
Matche.java
```java
 */
@RealmClass
public class Matche implements Serializable, RealmModel {

    /**
     * 比赛id
     */
    @Index
    @PrimaryKey
    private long id;
    /**
     * 主队信息
     */
    private MatcheTeam home;
    /**
     * 客队信息
     */
    private MatcheTeam visite;
    //other codes
```
MatcheTeam .java
```java
@RealmClass
public class MatcheTeam implements RealmModel, Serializable, Parcelable {
    private long id;
    private int score;
    //other codes
```

**Comment by beeender** [comment]
The listener in `setOnScoreListener()` is not called? See https://realm.io/docs/java/latest/#notifications
> The notification delivery will also be stopped if the object which the listener was registered on is GCed or the correspoding Realm instance is closed. You should keep a strong reference of the object which the listener is registered on as long as you still need the notification to be delivered.

**Comment by Zhuinden** [comment]
private void setOnScoreListener(RealmResults<Matche> matches) {

this method adds change listeners, but the proxy classes are not retained anywhere, so they get GC'd and Realm cannot notify them anymore

**Comment by henjue** [comment]
```java
class A{
private String a_name;
private B b;
}
```
```java
class B{
private String b_name;
}
```
```java
datas = realm.where(A.class).findAll();
        datas.addChangeListener(new RealmChangeListener<RealmResults<A>>() {
            @Override
            public void onChange(RealmResults<A> matches) {
//I want to change “b_name” in B when there call "onChange" method
            }
        });
```

**Comment by beeender** [comment]
@henjue So what is your question?

**Comment by dongorigin** [comment]
I have a similar problem, reason is linked Object has  GC'd. I think the document need to explain on the linked Object GC

**Comment by kneth** [comment]
@dongorigin Any suggestions on how to improve the documentation as @beeender is quoting?

**Comment by Zhuinden** [comment]
BTW `Realm.getDefaultInstance().execute...` creates an unclosable Realm instance.

**Comment by dongorigin** [comment]
I have been using Realm for 2 years, before I totally did not realize that multiple calls to get linked object would return different objects, and the previous object would be GC

The following code is intuitive, but the behavior is completely wrong:
```
onCreate() {
    person.getDog().addChangeListener(listener);
}
onDestroy() {
    person.getDog().removeChangeListener(listener);
}
```

The reason should be as follows:
1.person.getDog() // DogRealmProxy@1
2.person.getDog() // DogRealmProxy@2
3.GC
4.DogRealmProxy@1 and DogRealmProxy@2 is GCed

**Comment by kneth** [comment]
@dongorigin I see now that we need to expand the documentation of keeping references to objects. And we should emphasize the importance of avoiding creating unclosable Realm instances.

**Comment by Zhuinden** [comment]
https://realm.io/docs/java/latest/#notifications

> The notification delivery will also be stopped if the object which the listener was registered on is GCed or the correspoding Realm instance is closed. You should keep a strong reference of the object which the listener is registered on as long as you still need the notification to be delivered

**Comment by Zhuinden** [comment]
I think this has been documented

**Comment by dongorigin** [comment]
I think it may be necessary to add example about Notifications. Notifications is important, and now the behavior is not intuitive.
And, I want to know `the importance of avoiding creating unclosable Realm instances.`

**Comment by Zhuinden** [comment]
@dongorigin if you don't close all local Realms then you won't be able to compact, and if you don't close them on background non-looper threads then your Realm file size can grow to be very large if you have many transactions.

**Comment by dongorigin** [comment]
@Zhuinden Thank you, very useful, is it necessary to add to the document?

**Comment by kneth** [comment]
@dongorigin It is documented in https://realm.io/docs/java/latest/#large-realm-file-size and https://realm.io/docs/java/latest/#auto-refresh. I will appreciate feedback on our documentation so we know where to improve it.

**Comment by dongorigin** [comment]
I have already understood, thank you very patiently.

**Comment by beeender** [comment]
this has been documented well on the https://realm.io/docs/java/latest/#notifications
