### ISSUE TITLE
Support @LinkingObjects relations in in createAllFromJson/createOrUpdateAllFromJson

### ISSUE THREAD

**Issue by joeywp** [realm/realm-java#4531]
Currently the new @LinkingObjects aren't supported in the createAllFromJson and createOrUpdateAllFromJson methods. For example, look at these models:

```
@RealmClass
public class ModelA extends RealmObject {
  @PrimaryKey
  @Getter
  @Setter
  private int id;

  @LinkingObjects("modelA")
  @Getter
  private final RealmResults<ModelB> modelB = null;
}
```

```
@RealmClass
public class ModelB extends RealmObject {
  @PrimaryKey
  @Getter
  @Setter
  private int id;

  @Getter
  @Setter
  private String someData;

  @Getter
  @Setter
  private ModelA modelA;
}
```

Provide this JSON of a ModelA instance to the Realm instance using createObjectFromJson or createOrUpdateAllFromJson:
```
{
  "id": 1,
  "modelB": [
    {
      "id": 1,
      "someData": "This is test data"
    },
    {
      "id": 2,
      "someData": "This is test data"
    }
  ]
}
```

What happens is, it creates a ModelA instance with the id correctly set to 1, but the model_b list of the ModelA instance is empty. Most of the private API's I use are structured like the JSON I provided above. I think it would be useful to many if the properties with the @LinkingObjects annotation would be supported in createObjectFromJson method so that if the JSON contains a list for this property, that those objects would be created and automatically linked back. In the example this would mean that the ModelB contained in the JSON would be created and have it's modelA property set to the ModelA given in the top level of the JSON.

**Comment by Zhuinden** [comment]
ModelA contains a ModelB, so if your ModelA had a field of ModelB, and ModelB would have a backlink to ModelA, then it should work.

**Comment by joeywp** [comment]
The thing is that ModelA can contains multiple of ModelB. In the example it only contains 1 ModelB instance, but maybe I should have made it more clear that it can also contain more than 1 ModelB instance.

 I also tried what you suggested, but that would mean that ModelA would have to have a RealmList<ModelB> and ModelB would have to have a RealmResults<ModelA> with the LinkedObjects("modelB") annotation. While that kind of works as a workaround it feels a bit hacky.

**Comment by Zhuinden** [comment]
`modelB` in this case is a field of `modelA` in that JSON example.

The real hack is that the API sends down an inverse relationship. 👅

**Comment by bmeike** [comment]
@joeywp 
Did you sort this out?  I think that what @cmelchior is saying is that LinkingObjects are very like shadows.  It make sense to construct the shadow from the person but much less sense to construct the person from the shadow.

LinkingObjects are not a bi-directional relationship.  A graph with LinkingObjects is still acyclic.   In your model, ModuleB has-a ModuleA.  ModuleA does not have-a ModuleB.  There LinkingObject exists only if B has an A.  Not symmetric.

I'm going to close this ticket as answered.  If you have *any* other questions about this, feel absolutely free to re-open it.  If there is anything else we can help you with, open a new issue.

**Comment by joeywp** [comment]
Forgot to reply, but yeah, I changed to models a bit so it works as intended now, thanks :P
