### ISSUE TITLE
Same query, different results

### ISSUE THREAD

**Issue by geolyth** [realm/realm-java#4532]
#### Goal

I would like to obtain same results from same query but I don't understand because not happen.

#### Expected Results

Same RealmResults

#### Actual Results

RealmResults in code sample 1 has some values, RealmResults in code sample 2 has 0 results.

#### Steps & Code to Reproduce

I execute code sample 1 at startup of my fragment and I obtain some results.
When I fill an EditText and click on action search, code sample 2 returns 0 results but the query is the same.

N.B. The "parent" and "name" attributes are String.

#### Code Sample 1

```java

Realm realm = Realm.getDefaultInstance();
realm.executeTransaction(new Realm.Transaction() {
    @Override
    public void execute(Realm realm) {
        final RealmResults<Sector> results = realm.where(Sector.class)
                .equalTo("parent", "")
                .contains("name", "", Case.INSENSITIVE)
                .findAll();
        loadDataUi(mContext, new ArrayList<Sector>(results));
    }
});

```

#### Code Sample 2

```java

etSearch.setOnEditorActionListener(new TextView.OnEditorActionListener() {
    @Override
    public boolean onEditorAction(final TextView v, int actionId, KeyEvent event) {
        if (actionId == EditorInfo.IME_ACTION_SEARCH) {
            Realm realm = Realm.getDefaultInstance();
            realm.executeTransaction(new Realm.Transaction() {
                @Override
                public void execute(Realm realm) {
                    final RealmResults<Sector> results = realm.where(Sector.class)
                            .equalTo("parent", "")
                            .contains("name", v.getText().toString().trim(), Case.INSENSITIVE)
                            .findAll();
                    loadDataUi(mContext, new ArrayList<Sector>(results));
                }
            });
            return true;
        }
        return false;
    }
});

```

#### Version of Realm and tooling
Realm version(s): 3.1.3

Realm sync feature enabled: no

Android Studio version: 2.3.1

Which Android version and device: Emulator and real devices with Android SDK 25

**Comment by Zhuinden** [comment]
can you guarantee that `v.getText().toString().trim()` == `""` and also `loadDataUi()` is not bugged?

It makes me wonder why you are displaying an ArrayList instead of a `RealmResults` directly using a `RealmRecyclerViewAdapter`, for example.

**Comment by geolyth** [comment]
I tried also to comment ".contains..." and "loadDataUi" but the result is the same, so Code Sample 1 has N results and Code Sample 2 has 0 results and I don't understand why.

**Comment by Zhuinden** [comment]
Well the only difference is `v.getText().toString().trim()` so that is where I'd focus my attention.

**Comment by geolyth** [comment]
I thought the problem was equalTo followed by containes clause but after I commented the last one, I discovered this not the issue.

I hope someone could explain me why this happen and how I can fix this strange situation.

**Comment by jarklee** [comment]
why just you try to query first block code twice to determine whether v.getText().toString().trim() != "" cause strange behavior or by realm framework itself

**Comment by Zhuinden** [comment]
Technically you are in a transaction in both cases, so it's not possible that you'd see "outdated data". Both results have to return the same elements for the same conditions.

**Comment by geolyth** [comment]
@jarklee The problem is not "contains" I think because when I commented "contains" clause the problem remain.

**Comment by geolyth** [comment]
@Zhuinden The same thought...my workaround is:

```java
ArrayList<Sector> a = new ArrayList<Sector>();
for (int i = 0; i < results.size(); i++) {
    if (results.get(i).getParent() == null) {
        a.add(results.get(i));
    }
}
```

I discovered If I use a value instead of "" 

```java
in .equalTo("parent", "")
```

I obtain a right result...so I don't understand :)

**Comment by Zhuinden** [comment]
`""` is not `null`, if you want to look for `getParent() == null` then you should use `isNull()` operator

**Comment by geolyth** [comment]
@Zhuinden I am so noob with Realm...sorry :(
