### ISSUE TITLE
LinkingObjects does not work

### ISSUE THREAD

**Issue by RuslanPrimak** [realm/realm-java#4537]
#### Goal

Test LinkingObjects annotation

#### Expected Results

Execute simple Android app with example specified with documentation

#### Actual Results

FATAL EXCEPTION: Caused by: java.lang.IllegalArgumentException: Invalid query: field 'owners' does not exist in table 'Dog'.

#### Steps & Code to Reproduce

Implementing simple application with Person and Dog objects

#### Code Sample

```java

public class Dog extends RealmObject {
    String name;
    @LinkingObjects("dog")
    final RealmResults<Person> owners = null;
}

public class Person extends RealmObject {
    String name;
    Dog dog;
}

public class MainActivity extends AppCompatActivity {
    private final static String TAG = MainActivity.class.getSimpleName();

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_main);

        Realm.init(this);
        RealmConfiguration conf = new RealmConfiguration.Builder().build();
        Realm.deleteRealm(conf);

        Realm realm = Realm.getInstance(conf);

        // Check data
        Log.d(TAG, "onCreate: " + realm.where(Dog.class).equalTo("owners.dog.name", "Fido")
                .findAll().size());

        realm.close();
    }
}

```

#### Version of Realm and tooling
Realm version(s): 3.1.1

Realm sync feature enabled: no

Android Studio version: 
Android Studio 2.3.1
Build #AI-162.3871768, built on April 1, 2017
JRE: 1.8.0_112-release-b06 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

Which Android version and device: ?
Android 7.1.2, Asus TF7007T

**Comment by cmelchior** [comment]
Queries are not supported in the initial version as noted in the changelog: https://github.com/realm/realm-java/blob/master/CHANGELOG.md#enhancements-2

They should be part of the next release. You can follow progress here: #4519
