### ISSUE TITLE
Some query not working in 3.1.3.

### ISSUE THREAD

**Issue by RajeshkumarA-Contus** [realm/realm-java#4539]
For example, 
1. Refresh the database,
2. Checking database has content.
etc.

**Comment by Zhuinden** [comment]
You really need to post more code, for example what thread is this on, etc

**Comment by RajeshkumarA-Contus** [comment]
Hi Zhuinden,

I have not implemented RxJava. I need to confirm all the functionality will work in 3.1.3 version.  Is any dependency is available.

**Comment by Zhuinden** [comment]
You're in luck, it will be re-added in Realm 3.2.0.

**Comment by RajeshkumarA-Contus** [comment]
K fine. I am in working on the project. Will the Realm 3.2.0 will release early.

**Comment by RajeshkumarA-Contus** [comment]
Hi,

I have another doubt,
How can i use BaseObservable and RealmObject in same class.. for DataBinding.

**Comment by Zhuinden** [comment]
Technically I would need to know your current Realm version, considering refresh was removed in 0.89.0, and that was about 1.5 years ago. 

But Realm 3.1+ is closest to 0.88.3 in behavior, so that's great.

**Comment by kneth** [comment]
Please add the information as the issue template outlined.

**Comment by Zhuinden** [comment]
For the time being, you can  do `public class MyObject extends RealmObject implements Observable`

**Comment by RajeshkumarA-Contus** [comment]
Hi,

Can we use this for above scenario
public class Person extends BaseObservable implements RealmModel{}
or
public class Person extends RealmBaseObservable {}

Is this proper way.. or want to use 
public class MyObject extends RealmObject implements Observable

**Comment by cmelchior** [comment]
@RajeshkumarA-Contus See #4534 . For now you need to do:

```
public class Person extends RealmObject implement Observable {

}
```

**Comment by RajeshkumarA-Contus** [comment]
K fine.. Thanks for your kind information.

**Comment by kneth** [comment]
I close the issue as @RajeshkumarA-Contus has a workaround until #4534 is implemented.
