### ISSUE TITLE
Support Stable ID's

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#4542]
We need to support the Stable ID feature for synced Realms: https://github.com/realm/realm-object-store/pull/434

A (not final) list includes:
- [x] Remove usage of instructions no longer supported (This especially impact creating objects with  primary keys)
- [x] Create a migration scheme for older Realms, since we need to add the ID column to older tables
- [x] Change all code paths that create tables/objects so they use the new methods for synced Realms.

Currently blocked on support for this being merged in Object Store.

**Comment by cmelchior** [comment]
We need to start doing this without proper releases from Sync / Objectstore, since there are some dependencies between the upstream releases that make it impossible to make a release at this point.


This means that this work should be started using the HEAD of these branches:
https://github.com/realm/realm-object-store/tree/su/stable-id-support
https://github.com/realm/realm-sync/tree/su/stable-ids

**Comment by simonask** [comment]
Corresponding issue in realm-cocoa: https://github.com/realm/realm-cocoa/issues/4909
Corresponding issue in realm-dotnet: https://github.com/realm/realm-dotnet/issues/1371
Corresponding issue in realm-js: https://github.com/realm/realm-js/issues/985

**Comment by Zhuinden** [comment]
>  Remove usage of instructions no longer supported (This especially impact creating objects with primary keys)

That's a bit scary, what about `createObject(SomeObj.class, pkValue);`?

**Comment by cmelchior** [comment]
It will still be supported. This is pure internal change that hopefully will benefit us greatly further down the line :)

**Comment by Zhuinden** [comment]
Ah, okay.

Interesting to see an `Urgent` tag, I guess if Sync finishes the stable IDs, it would break every client, so they need to follow even before they're done? 😄

**Comment by cmelchior** [comment]
According to https://github.com/realm/realm-cocoa/issues/4909#issuecomment-298508815, it sounds like we cannot migrate existing files. Making the migration process somewhat easier.

**Comment by cmelchior** [comment]
Support for this has been merged. Closing
