### ISSUE TITLE
Unable to perform filter on realm results using SearchView and RealmRecyclerViewAdapter

### ISSUE THREAD

**Issue by RameshReddyKolla** [realm/realm-java#4543]
#### Goal
How to perform Filterable on realm results.

#### Expected Results

Need to get filtered text from the realm results.

#### Actual Results
Throwing error saying that realm results can only be used on the thread on which they are created.

#### Version of Realm and tooling
Realm version(s): 3.1.0

Realm sync feature enabled: no

Android Studio version: 2.3

Which Android version and device: 25 & Nexus 6(emulator)

**Comment by Zhuinden** [comment]
http://stackoverflow.com/a/40632613/2413303

**Comment by RameshReddyKolla** [comment]
Yeah. I implemented this http://stackoverflow.com/a/40632613/2413303 process, this is completely fine.In this process, we write the query and get the filter results.But in my case, filtering has to be done on realm results which are already queried.

**Comment by Zhuinden** [comment]
`getData().where()./*do condition stuff here*/.findAll()`

**Comment by RameshReddyKolla** [comment]
Thank You, Zhuinden.It is working, Great!

**Comment by AlanVerne** [comment]
Your solution is not async, yep?

**Comment by Zhuinden** [comment]
@AlanVerne if you use findAllAsync instead of findAll, then it is.
