### ISSUE TITLE
proxyState is completed false on synchronous query

### ISSUE THREAD

**Issue by ebbnormal** [realm/realm-java#4545]
We found a potential realm bug running Samsung Edge S7 using realm-java 2.2.1 and doing a synchronous realm query. 
We have a `Dog` class which has the following definition:

```

@Parcel
public class Dog extends RealmObject{

    @PrimaryKey
    public int id;
    public int countOfEatenCookies = 25;
    public int countOfDestroyedToys = 25;
    public float priceOfFavoriteDogTreat = 18.75f;
    public float priceOfEasilyChewedDogToy = 0.75f;
    public int timesGoneOutsideToday = 10;
    public boolean active;
    public Date created;
    public int createdBy;
    public Date modified;
}

```

We have an `Activity` which sees if an object is in `Realm()` and if not, updates the realm data with a new server call to retrieve said object. 

When we have the following code in the `onCreate()` of our activity. 

```
  if(cachingManager.getCachedDog() != null) {
            detail = cachingManager.getCachedDog();
            binding.setDetail(detail);
            computeDogAttributes();
        }else {
            showProgressDialog();

            cachingManager.refreshDog(new CachingManager.CachingManagerListener() {
                @Override
                public void onSaveFinished(Object savedModel) {
                    hideProgressDialog();
                    detail = (Dog) savedModel;
                    binding.setDetail(detail);
                    computeDogAttributes();
                }

                @Override
                public void onFailedToSave() {
                    showGeneralFailureMessage();
                }
            });
        }

```

The realm query we use is 

```
 public Dog getCachedDog() {
        Realm realm = dbManager.getRealm();
        return realm.where(Dog.class).equalTo("active", true).findFirst();
    }

```

Our expected result was that when we call `cachingManager.getCachedDog()` which makes a synchronous realm query and returns as a result a `Dog()` was that we get the cached object. 

However there seems to be an issue where the `proxyState` had was incomplete. My suspicion that this happens is that in our `Activity` we have `Dog()` called `detail` which is constructed at the beginning of the Activity. The default values of the dog are shown in the constructor above. The problem is that all the attributes of the dog which is set with `binding.setDetail()` for this error state were all 0 instead of the values given above, or the values of the single dog which we persist in realm (which is always without exception non-zero for all attributes). The `proxyDog` which is the managed version of the `Dog()` returned by the `realm.where` function in a synchronous mode is the only thing that sets a `Dog()` object temporarily to these default values, and that is what displayed on the UIThread after we bind to it in our layout resource. 

That or `findFirst()` fails and then what returns as the `Dog()`? the `DogProxy` ? 

The bug is hard to reproduce but did happen, and the only explanation I can envision, is that the values on the `Dog detail` are coming from the `Realm DogProxy` object as opposed to the managed realm object `Dog` itself. 

Further Notes Concerning Architecture: 

`dbManager` refers to a class `DBManager` which, using Dagger, is injected into the `BaseActivity` which the activity which had the error inherits. It follows @cmelchior suggestion and @Zhuinden suggestion to tie UI-thread based `Realm.getInstance()` and `Realm.close` to the `onCreate()` and `onDestroy()` android methods respectively. 

Also it is worth noting that we don't perform any realm writes async / on any BG threads, so it isn't possible that anything from another activity is writing to realm when we have the one case where, if the active `Dog` is not in realm, that the write in the following case is blocked `realm.copyToRealmOrUpdate(response.body());`

**Comment by Zhuinden** [comment]
so Dog has a default no-arg constructor that sets up default values?

Where do you call`realm.createObject()`?

**Comment by ebbnormal** [comment]
Yes I have a Dog no-arg constructor which sets up default values which are all non-zero. The only time I see zeros are when querying directly from Realm and then there are zeros on every attribute of the Dog the DogProxy has the lazy loaded version which has non-zero values.

**Comment by Zhuinden** [comment]
Hold on, I think you're just running into https://realm.io/docs/java/latest/#testing-and-debugging as in while you're debugging, you should look at the accessor values, and not the field values.

**Comment by ebbnormal** [comment]
Yes I get that but is there anyway the field values could be written to my UI if some error state occurs?

**Comment by Zhuinden** [comment]
No, the Realm-Transformer transforms all field access into proxy getter calls.

**Comment by ebbnormal** [comment]
Okay. But there was a state in the app which I have yet to reproduce which was not based on confusing field values with accessor values. I believe it is from realm. For example we are writing to realm in a UI thread, which cmelchior says not to do in the Realm docs, but my colleague just says that could make the UI jittery but wouldn't mess with the integrity of the data.

**Comment by Zhuinden** [comment]
With Realm 3.1+ the updating of RealmResults / RealmObjects on the UI thread is immediate for local transactions, and while it does force a `load()` on async transactions, it shouldn't/cannot cause inconsistency.

**Comment by ebbnormal** [comment]
okay but what if `proxyState == null` and then it tries to do this `        proxyState.setAcceptDefaultValue$realm(context.getAcceptDefaultValue());`

**Comment by ebbnormal** [comment]
then it could potentially set my object to have weird values ,and then i could bind the UI to that!

**Comment by ebbnormal** [comment]
or if somehow 
```
        if (proxyState.isUnderConstruction()) {
            if (!proxyState.getAcceptDefaultValue$realm()) {
                return;
            }
```

is triggered  then it returns from the accessor method from my Dog's attribute with a value that I dont want.

**Comment by Zhuinden** [comment]
uh. The exact behavior of how default values are set up is a bit out of my scope.

If you can set up a sample project that reproduces the error, that would greatly simplify the search for the cause. In the meantime, @zaki50 knows how this part of the transformation works.

**Comment by ebbnormal** [comment]
Specifically, if the `proxy` is null when the field getter is called on an object, then it uses  `   proxyState.setAcceptDefaultValue$realm(context.getAcceptDefaultValue());` I guess that would assume `findFirst()` returns a non null value and I got the object from realm synchronously.

**Comment by ebbnormal** [comment]
@Zhuinden is it possible that because we don't wrap the original write to realm in a `try{} finally{ realm.close()}`? Or would you not do that if you are closing on the destruction of an `Activity`

**Comment by ebbnormal** [comment]
you suggest doing that , but for BG threads, where as this is all on the main thread (https://medium.com/@Zhuinden/how-to-use-realm-for-android-like-a-champ-and-how-to-tell-if-youre-doing-it-wrong-ac4f66b7f149)

**Comment by ebbnormal** [comment]
_"Closing the UI thread’s Realm is not crucial, because it is on a looper thread with auto-update."_ nevermind!

**Comment by zaki50** [comment]
@ebbnormal `proxyState` never be `null` in property setters since we injected `realm$injectObjectContext();` to all constructors in all model classes.

https://github.com/realm/realm-java/blob/master/realm-transformer/src/main/groovy/io/realm/transformer/BytecodeModifier.groovy#L92

This `realm$injectObjectContext();` call happens before any setter calls including default value assignment.

**Comment by ebbnormal** [comment]
I haven't been able to reproduce it. If I have more information or reason to believe it is realm (That is not conjectural!) then I will reopen. Thank you for your thoroughness @zaki50 and @Zhuinden
