### ISSUE TITLE
How to modify realm results by adding or removing obj android

### ISSUE THREAD

**Issue by RameshReddyKolla** [realm/realm-java#4546]
#### Goal

How to add and remove realm objects to realm results.

#### Expected Results

realm object has to be added to realm results.

#### Actual Results

unable to add and remove realm object from Realm results.
#### Code Sample
RealmResults<A> realmResults = mRealm.where(A.class).findAll();

A obj = new A(); ##### Here A extends realm object
obj.setValue(1212);
realmResults.add(obj); // which is not supported.

#### Version of Realm and tooling
Realm version(s):3.1.0

Realm sync feature enabled: no

Android Studio version:2.3

Which Android version and device: 25 & Nexus 6

**Comment by Zhuinden** [comment]
``` java
mRealmResults = mRealm.where(A.class).findAll();
realm.executeTransaction(new Realm.Transaction() {
    @Override
    public void execute(Realm realm) {
        A obj = new A(); ##### Here A extends realm object
        obj.setValue(1212);
        realm.insertOrUpdate(obj);
    }
});
// now RealmResults has `obj` too
```

**Comment by RameshReddyKolla** [comment]
Yes, correct, I think this will update or insert the realm obj into the database.But I just need to add to RealmResults, not to DB.

**Comment by kneth** [comment]
@RameshReddyKolla It is not possible to add to `RealmResults` and they are live objects so when you modify/add/delete from your Realm, `RealmResults` objects are automatically updated.

**Comment by Zhuinden** [comment]
When you insert in Realm, you insert in RealmResults.

**Comment by zaki50** [comment]
You need to create your own List class which merges `RealmResults` and own elements.

**Comment by RameshReddyKolla** [comment]
Yes, am doing the following way.
RealmResults<A> results = mRealm.where(A.class).findAll();
List<A> list ==> contains both realm results and  class A objs like **list.add(new A());**
But when i use this list in Filterable class which is in Adapter class throwing exception realm objects can only be accessed the theread on which they were created.

**Comment by Zhuinden** [comment]
http://stackoverflow.com/a/40632613/2413303

**Comment by zaki50** [comment]
@RameshReddyKolla You can access `RealmResults` and `RealmObject`s only from the thread where those instances are generated.

**Comment by RameshReddyKolla** [comment]
correct.

**Comment by Zhuinden** [comment]
@RameshReddyKolla  you need to set new results in `publishResults` method

**Comment by bmeike** [comment]
@RameshReddyKolla 
It seems that there are a couple of issues here:
1) the `RealmResults` are a view of the DB.  If you add things to or remove things from it, you are changing the db.  If you need a non-live copy, use `copyFromRealm` and a `List`
2) you cannot pass Realm objects between threads.  Here again, `copyFromRealm` is your friend.

I'm going to close this ticket because we haven't seen any activity for a while.  By all means, though, re-open it if you have further questions on this topic... or open a new issue if there is something else with which we can help you.

**Comment by Zhuinden** [comment]
Although I must note that generally rethinking the design is a better option than using `copyFromRealm()`.

I've only seen a need for `copyFromRealm()` to:

- create editable forms where you have a SAVE button when you actually save the object

- want to send managed obj through reflection-based serializers (GSON/Moshi)
