### ISSUE TITLE
getDeletionRanges should be empty

### ISSUE THREAD

**Issue by DanteAndroid** [realm/realm-java#4555]
The data in Realm are not changed at all, but `changeSet.getDeletionRanges()` and `getInsertionRanges()` is not empty.
Code:
```
 @Override
    public void onChange(RealmResults<Image> collection, OrderedCollectionChangeSet changeSet) {
        // `null`  means the async query returns the first time.
        if (changeSet == null) {
            log("no change");
            adapter.notifyDataSetChanged();
            return;
        }
        // For deletions, the adapter has to be notified in reverse order.
 //        OrderedCollectionChangeSet.Range[] deletions = changeSet.getDeletionRanges();
 //       for (int i = deletions.length - 1; i >= 0; i--) {
 //           OrderedCollectionChangeSet.Range range = deletions[i];
 //          log("notifyItemRangeRemoved from: " + range.startIndex + " length: " + range.length);
 //         adapter.notifyItemRangeRemoved(range.startIndex, range.length);
 //     }
 // I have to comment it out to fix this problem

        OrderedCollectionChangeSet.Range[] insertions = changeSet.getInsertionRanges();
        for (OrderedCollectionChangeSet.Range range : insertions) {
            log("notifyItemRangeInserted from: " + range.startIndex + " length: " + range.length);
            adapter.notifyItemRangeInserted(range.startIndex, range.length);
            if (page == 1) {
                recyclerView.scrollToPosition(0);
            }
        }

//        OrderedCollectionChangeSet.Range[] modifications = changeSet.getChangeRanges();
//        for (OrderedCollectionChangeSet.Range range : modifications) {
//            log("no notifyItemRangeChanged " + range.startIndex + " to " + range.length);
//            adapter.notifyItemRangeChanged(range.startIndex, range.length);
//        }
    }

```

This problem happens when:
I refresh the data, the same data is saved into Realm, then `notifyItemRangeRemoved` & `notifyItemRangeInserted` is executed which result in recyclerview's weird behavior.

You may want to check out my repository [here](https://github.com/DanteAndroid/Beauty/blob/master/app/src/main/java/com/dante/girls/picture/CustomPictureFragment.java#L306) and [here](https://github.com/DanteAndroid/Beauty/blob/master/app/src/main/java/com/dante/girls/picture/PictureFragment.java#L145)  and [here](https://github.com/DanteAndroid/Beauty/blob/master/app/src/main/java/com/dante/girls/picture/CustomPictureFragment.java#L210)

Realm Version: `classpath "io.realm:realm-gradle-plugin:3.0.0"`

**Comment by beeender** [comment]
the `collection` needs to be sorted to avoid this problem.
Realm doesn't guarantee the order of unsorted `RealmResults`. For example,
You have some data stored in the Realm like:

`[-1,0,1,2,3,4,5]`

And you have a UNSORTED results to get all values greater than or equal to (>=) `0`

`[0,1,2,3,4,5]`

If you removed the `-1` from Realm, you may receive a change notification says deletion at 0 and insertion at 0 because of the order of how data stored underneath becomes:

`[5,0,1,2,3,4]`

Then your UNSORTED results actually becomes the same:

`[5,0,1,2,3,4]`

This is expected behaviour. and solution is just sort the `RealmResults`.

**Comment by DanteAndroid** [comment]
Thx for quick reply.
I don't think I haven't sorted it. [Check here](https://github.com/DanteAndroid/Beauty/blob/master/app/src/main/java/com/dante/girls/model/DataBase.java#L75) and [here](https://github.com/DanteAndroid/Beauty/blob/master/app/src/main/java/com/dante/girls/picture/PictureFragment.java#L145)

**Comment by beeender** [comment]
`findFavoriteImages` is not sorted, could that be the case?

**Comment by DanteAndroid** [comment]
No, favoriteImages only appear in `FavoriteFragment`.
Actually, when I remove `sort`, just with `findAll()` it seems normal. Really confused now.

**Comment by Zhuinden** [comment]
How about `findAllSorted()`?

**Comment by beeender** [comment]
I tried your project, also re-enabled the code in your issue description, but cannot reproduce it by pulling to refresh.

Can you let me know how to reproduce it?

**Comment by DanteAndroid** [comment]
I'm sorry, you need to change MainActivity's method here to enable secret mode:

![7775e560-b41f-47d9-91f9-851cfba117cc](https://cloud.githubusercontent.com/assets/10005563/25428959/01b9ccec-2aaa-11e7-9eda-24a9421ca557.png)

then you'll see the secret column on the main page. Just try to refresh in the db_xxx section.

**Comment by beeender** [comment]
I still cannot reproduce it :(

When you met this problem, what is the output of 
`log("notifyItemRangeRemoved from: " + range.startIndex + " length: " + range.length);`
and
`log("no notifyItemRangeChanged " + range.startIndex + " to " + range.length);`

**Comment by DanteAndroid** [comment]
Well, sometime I cannot either. Actually I don't know when it happens.
When it happens, it seems ** like ** the pictures are all deleted and inserted one by one
![image](https://cloud.githubusercontent.com/assets/10005563/25463388/75159530-2b28-11e7-9b86-30f87e542289.png)

**Comment by Zhuinden** [comment]
Now hold on a second, you should update to Realm 3.1.3.

Realm 3.0.0's commit behavior is kind of iffy.

**Comment by DanteAndroid** [comment]
@Zhuinden Well, I change to 3.1.3 but the problem still exists.

**Comment by DanteAndroid** [comment]
@Zhuinden To be clear, it only happens with `.findAllSorted("xxx", Sort.DESCENDING)`. Works well with `findAll()`

**Comment by beeender** [comment]
I spent some time to check your project again, so the problem is in your `CustomPictureFragement.java` line 167

```
                            image = Image.getFixedImage(this, image, imageType);
                            if (!isGank) {
                                image.setPublishedAt(new Date());
                            }
```

The problem happens when you re-fetch the pictures, even when the pictures are not changed, the `Image.publishedAt()` will be reset to current time.

Also, the images objects are not store in a single transaction, so case like below will happen:

```
// Before:
image1.date = 14:03
image2.date = 14:02
image3.date = 14:01

// After the 1st transaction
image3.date = 15:01
image1.date = 14:03
image2.date = 14:02

```
