### ISSUE TITLE
Android databinding is not working with realm-gradle-plugin:1.0.0

### ISSUE THREAD

**Issue by codewithvikas** [realm/realm-java#4565]
Do I need higher version of data binding. 
read some where that realm-gradle-plugin:1.0.0 is using the gradle version which is not compatible for data binding in android.

Please Help.

Thanks

#### Goal

> What do you want to achieve?
Databinding in Android

#### Expected Results

> ?

#### Actual Results

> Error:Execution failed for task ':library:transformClassesAndResourcesWithSyncLibJarsForRelease'.
> failure, see logs for details.  Generated class list does not exist ......../AndroidStudioProjects/git/........./library/build/intermediates/data-binding-info/release/_generated.txt

#### Steps & Code to Reproduce

> Describe your current debugging efforts.

#### Code Sample

```java

> Your code here. Bigger samples should ideally be as separate Android Studio project, 
> in gists/repositories or privately at help@realm.io)

```

#### Version of Realm and tooling
Realm version(s):  1.0.0

Realm sync feature enabled: yes/no

Android Studio version: 2.3.1

Which Android version and device: 6

**Comment by cmelchior** [comment]
The latest Realm version is 3.1.3, but what exactly isn't working with databinding?

**Comment by Zhuinden** [comment]
> which is not compatible for data binding in android.

what do you mean?

**Comment by codewithvikas** [comment]
I am using Data Binding Library of android. which needed com.android.tools.build:gradle:1.5.alpha or higher. 
and i was using  realm (io.realm:realm-gradle-plugin:1.0.0). 
So my question is does this version of realm not work for Data Binding Library ?.
However i tried with higher one (io.realm:realm-gradle-plugin:3.1.1).It works

**Comment by cmelchior** [comment]
You probably need to clean your build directories

**Comment by codewithvikas** [comment]
Thanks @cmelchior 
I updated realm version with latest one ( 3.1.3). It works fine.
I am closing the issue.
Thanks Again. :-)
