### ISSUE TITLE
How can I open an encrypted Realm file in Realm Browser?

### ISSUE THREAD

**Issue by koukoucai** [realm/realm-java#4568]
I have curiosity about how can I open an encrypted Realm file in Realm Browser?

I encrypt my Realm file in android app.

I pull this file and byte[64] key file to the mac .Want to open it with Realm Browser.

But it prompt that "Please enter a valid encryption key for this Realm file"

I'm confused there is a byte[] file from app , how can I get the valid encryption key from the byte[] file?

It maybe some rules in this I thought.

Can somebody answer this?

Just forget it if that is internal secret

**Comment by kneth** [comment]
You need to convert your `byte[]` array into a string where each element in the array is represented as a hexadecimal number. 

If you have `byte[64] key = {0, 1, 2, 250, 64, 129, ...}` your app, you can convert it using `echo "0, 1, 2, 250, 64, 129, ..." | tr "," "\n" | while read n ; do printf "%02X" $n ; done`
