### ISSUE TITLE
OrderedRealmCollectionChangeListener considering insertion/deletion as a change

### ISSUE THREAD

**Issue by ikscn** [realm/realm-java#4571]
#### Goal

Efficient usage of OrderedRealmCollectionChangeListener

#### Expected Results

When I work on RealmResults, with a query like below, I expect that if the result of the query changes, Realm should consider this as a deletion or an insert.

#### Actual Results

Currently, Realm considers these as a change.

#### Code Sample
`Calendar timeOut = Calendar.getInstance();`
`timeOut.add(Calendar.SECOND, -60);`
`RealmResults<MyData> results = realm.where(MyData.class).greaterThan("updateDate", timeOut).findAll();
 `

#### Version of Realm and tooling
Realm version(s): 3.0.0

Android Studio version: 2.3.1

Target sdk version: 25

**Comment by kneth** [comment]
What changes do you do in order for the query to be rerun? Do you delete or create new objects?

**Comment by ikscn** [comment]
I just add the listener below, and suppose I update some of my records on MyData (via column updateDate).
After 1 minute, the result count is changed since some of the records didn't get updates.. So my code looks like this:

`Calendar timeOut = Calendar.getInstance();`
`timeOut.add(Calendar.SECOND, -60);`

`RealmResults<MyData> results = realm.where(MyData.class).greaterThan("updateDate", timeOut).findAll();`
`results.addChangeListener(new OrderedRealmCollectionChangeListener<RealmResults<MyData>>() {`
                        @Override
                        public void onChange(RealmResults<MyData> collection, OrderedCollectionChangeSet changeSet) {
                            if(changeSet.getInsertions().length>0
                                    || changeSet.getDeletions().length>0){

                                updateUI();

                            }
                        }
                    });`

**Comment by Zhuinden** [comment]
You need to keep `RealmResults<MyData> results;` as a field reference in the class, and not just a local reference in the method

**Comment by ikscn** [comment]
I already use it as a field in the class.

**Comment by kneth** [comment]
The listener is only triggers by commits. I'm not sure if I understand you correctly: do you expect that the query is rerun since you query a field which means time for you?

**Comment by ikscn** [comment]
Yes, this could be my expectation.
Otherwise, it doesn't sound logical whether I put a listener on a query of RealmResults with or without the filter.

**Comment by kneth** [comment]
You have probably already read https://realm.io/docs/java/latest/#notifications. The listeners are only triggered when a commit happens (and in some cases also when a transaction begins). In your case, the listener will not be trigger as no changes have happened (your Realm does not have a sense of time). You could add a thread which commits an empty transaction once every minute.

**Comment by bmeike** [comment]
Hey @ikscn ,
  I think that @kneth has answered the question, so I'm going to close this ticket.

  By all means, feel free to re-open this ticket if you have more questions about this issue or open another if there is something else with which we can help you.
