### ISSUE TITLE
Ghost record getting generated

### ISSUE THREAD

**Issue by debjitk** [realm/realm-java#4578]
[model]

class File extends RealmObject {

    @PrimaryKey
    private long id;

    @Index
    private long pid;

    .... 
}

Please not the file id "2314356523452636310L". I have not added any files with the id neither have i added any files with this as the parent id. Now when I am trying to find files with parent id as "2314356523452636310L" I am getting a couple of records. Where are these records coming from ? Surprisingly the ghost records data is not wrong they are matching with the server.

I have logged every insert into realm and I am not getting any trace of any inserts with id "2314356523452636310L" or with pid "2314356523452636310L".

A few lines more the log ....

04-29 19:33:32.012 20435-20897/com.[...].android D/FilesSyncService:     LOOKUP CHILDS FOR PID 2314356523452636310
04-29 19:33:32.012 20435-20897/com.[...].android D/FilesSyncService:     [NONE]
04-29 19:33:33.502 20435-20897/com.[...].android D/FilesSyncService:     SAVING FILE FOR PID 0 : 2344182679026576787
04-29 19:33:33.502 20435-20897/com.[...].android D/FilesSyncService:     SAVING FILE FOR PID 0 : 2343798489906982222
04-29 19:33:33.502 20435-20897/com.[...].android D/FilesSyncService:     SAVING FILE FOR PID 0 : 2337272514733976183

.....

04-29 19:34:23.002 20435-20897/com.[...].android D/FilesSyncService:     FOUND CHILDS FOR PID 2314356523452636310: 21
04-29 19:34:23.002 20435-20897/com.[...].android D/FilesSyncService:     LOOKUP CHILDS FOR PID 2314356523452636310
04-29 19:34:23.002 20435-20897/com.pixo.android D/FilesSyncService:     FOUND CHILD FOR PID 2314356523452636310: 2314031677896170384
04-29 19:34:23.002 20435-20897/com.[...].android D/FilesSyncService:     FOUND CHILD FOR PID 2314356523452636310: 2314031673601203087
04-29 19:34:23.002 20435-20897/com.[...].android D/FilesSyncService:     FOUND CHILD FOR PID 2314356523452636310: 2314031665011268494
04-29 19:34:23.012 20435-20897/com.[...].android D/FilesSyncService:     FOUND CHILD FOR PID 2314356523452636310: 2312171514675370485

Now as you can see the child ids were also never inserted.

The link to the entire log file:
https://www.evernote.com/shard/s3/sh/3bd65632-51e6-4e32-8c26-c797052283f8/33eb298db9debdb0

**Comment by Zhuinden** [comment]
Well, it's most likely the result of you inserting such an item at some point.

**Comment by debjitk** [comment]
No i am not inserting any item anywhere in the code. Just to make sure I have created a clean function and skipped all other calls on app first time run.

**Comment by Zhuinden** [comment]
In that case, a sample project that reproduces this error is needed.

**Comment by debjitk** [comment]
Solved.

You were right. It was not a Realm issue. It was actually two processes accessing different sets of data and the second process was creating the data incase it was absent. Not a bug or any technical issue. It was just the complexity of the entire code base that puzzled me.
