### ISSUE TITLE
RealmObjectChangeListener not called for newly created objects?

### ISSUE THREAD

**Issue by shahzaibmuneeb** [realm/realm-java#4594]
#### Goal

I do `findFirstAsync()` on an object which does not yet exist in my DB. I then add a RealmObjectChangeListener to this so that when a seperate network request goes through and the object IS created then I expect the change listener to trigger  and populate the UI.

```java
person = rootActivity.getRealm().where(Person.class).equalTo("id", userID).findFirstAsync();
person.addChangeListener(new RealmObjectChangeListener<RealmModel>() {
            @Override
            public void onChange(RealmModel object, ObjectChangeSet changeSet) {
                if(person.isValid()){
                    populateUi();
                    if(updateUICallback != null){
                        updateUICallback.onUpdateUI();
                    }
                }
            }
        });

// Fetch from network using same realm
rootActivity.showBusyAnimation();
EMDataManager.fetchUser(rootActivity.getRealm(), userID, new NetworkResponse() {
            @Override
            public void onResponse(Type responseType, @Nullable Object object) {
                rootActivity.hideBusyAnimation();
            }
        });

```

 `Person person;` variable is initialised at the fragment level so this is a strong reference.

#### Actual Results

Change listener is not triggered upon creation of this Person object. However if I restart the app, once the network request has created the person object in my Realm DB and restart this fragment, then the change listener IS called as it already exists in the Realm DB.

The way I add the object to the DB via the network request above is like so:

```java
public static void fetchUser(final Realm realm, long userID, @Nullable final NetworkResponse networkResponse){
        EMRestClient.getEMRestService().getUserProfileInfo(userID).enqueue(new Callback<Person>() {
            @Override
            public void onResponse(Call<Person> call, final Response<Person> response) {
                if(response.isSuccessful()){
                    realm.executeTransaction(new Realm.Transaction() {
                        @Override
                        public void execute(Realm realm) {
                            Person responsePerson = response.body();
                            realm.copyToRealmOrUpdate(responsePerson);
                        }
                    });

                    if(networkResponse != null){
                        networkResponse.onResponse(NetworkResponse.Type.SUCCESS, null);
                    }

                }else{
                    if(networkResponse != null){
                        networkResponse.onResponse(NetworkResponse.Type.FAILURE, null);
                    }
                }
            }

            @Override
            public void onFailure(Call<Person> call, Throwable t) {
                CommonNetworkResponses.displayNetworkRequestFailureMessage(App.getInstance());
                if(networkResponse != null){
                    networkResponse.onResponse(NetworkResponse.Type.FAILURE, null);
                }
            }
        });
    }
```

#### Version of Realm and tooling
Realm version(s):  "io.realm:realm-gradle-plugin:3.1.3"

**Comment by Zhuinden** [comment]
Re-running the query until an element was found was undocumented/buggy behavior, fixed in https://github.com/realm/realm-java/issues/4352 .

You might want to use a listener added to a `RealmResults` instead, and do a `results.where().equalTo("id", id)....`

**Comment by shahzaibmuneeb** [comment]
I see - happy to do it that way however I am using 3.1.3, which according to the thread you referenced, has been fixed and merged? Right ? So it should work? (Just asking for my own knowledge)

**Comment by Zhuinden** [comment]
@shahzaibmuneeb  the behavior you are looking for was a bug, so you need a different approach. 

So instead of storing `person`, you should store a `results`, and use `findFirst()` in its `RealmChangeListener` with the given user id.

**Comment by shahzaibmuneeb** [comment]
Cool thank you :)
