### ISSUE TITLE
OnSuccess callback called infinite times for Async Transaction 

### ISSUE THREAD

**Issue by TonyHaddad91** [realm/realm-java#4595]
#### Goal

Do an action on onSuccess of async transaction 

#### Expected Results

onSuccess listener invoked once 

#### Actual Results

onSuccess Listener invoked infinite times

#### Code Sample

```java
  realm.executeTransactionAsync(r -> {

            ChatDialog dialog = r.where(ChatDialog.class).equalTo(
                    ChatDialog.FIELDS.DIALOG_ID, id).findFirst();
            if (dialog != null) {
                dialog.getChatInfo().setDealerChatStatus(status);
                dialog.getChatInfo().setConsumerChatStatus(status);
            }
        }, success);
```

And here is the onSuccess Code 
```
 realm.executeTransaction(r -> {
            List<ChatDialog> ChatDialogs = realm.where(ChatDialog.class).equalTo(
                    ChatDialog.FIELDS.DEALER_CHAT_STATUS, localStatus).findAll();
            if (ChatDialogs.size() > 0) {
                for (ChatDialog carChatDialog :ChatDialogs) {
                    carChatDialog.getChatInfo().setDealerChatStatus(status);
                   ChatService.start(context,
                            SyncDialogStatusCommand.getSyncDialogStatusCommandIntent(
                                    carChatDialog.getDialogId()));
                }
            }
        });
```

#### Version of Realm and tooling
Realm version(s): 3.0.0 but this issue not produceable on same code using version 1.2.0

Realm sync feature enabled: no

Android Studio version: 2.3.1

Which Android version and device: 6.0.0, galaxy note 5

**Comment by beeender** [comment]
can you share you code of `success`?

**Comment by TonyHaddad91** [comment]
@beeender  i've updated my code

**Comment by beeender** [comment]
OK, I can see the problem, will fix it right away. Thanks for reporting this!

**Comment by TonyHaddad91** [comment]
@beender just out of curiosity, was the issue race condition in the Async transaction?

**Comment by beeender** [comment]
It is more like a bug, we have callbacks stored as a list and trigger them when transaction committed. But the mechanism from async transactions changes a bit in the recent version, so the synced transaction in your success callback will trigger the `did_change` again immediately at that time the callback list has not been cleared.
See https://github.com/realm/realm-java/blob/master/realm/realm-library/src/main/java/io/realm/internal/RealmNotifier.java#L101

**Comment by TonyHaddad91** [comment]
@beeender Thanks again, now i have clear idea about the issue

**Comment by TonyHaddad91** [comment]
@beeender do you have an estimated time for releasing this fix?
Regards

**Comment by beeender** [comment]
@TonyHaddad91 We have another issue needs to be fixed in the next release, so hope we can make a release this week. But it might be possible that is delayed to the next week.

**Comment by Zhuinden** [comment]
The case insensitive strings in case the string consists of only numbers?
