### ISSUE TITLE
Question regarding better/more-optimized practice

### ISSUE THREAD

**Issue by gajicm93** [realm/realm-java#4604]
Essentially, which way of inserting objects into database is better?

```
Dog dog = new Dog();
dog.setName("Rex");
dog.setAge(1);

realm.beginTransaction();
final Dog managedDog = realm.copyToRealm(dog); // Persist unmanaged objects
realm.commitTransaction();
```

As far as I've tested, this first way also allows me to use a constructor instead of setters?

OR

```
realm.beginTransaction();
Dog managedDog= realm.createObject(Dog.class); // Create managed objects directly
managedDog.setName("Rex");
managedDog.setAge(1);
realm.commitTransaction();
```

**Comment by cmelchior** [comment]
They both have their use cases:

`copyToRealm()`
- You can create a full in-memory object before using it.
- You can use non-default constructors
- It is slightly slower than creating objects directly.
- It uses more memory as you have both the unmanaged and managed object in memory at the same time.
- If inserting large amounts of data consider `insert(dog)` instead. It doesn't return the managed object but is much faster.

`createObject()`
- Only default constructor can be used
- Avoid memory overhead of `copyToRealm()` 
- Is better if creating objects in loops.
- If you want more fine-grained control than `copyToRealm()`, e.g partial updates.

**Comment by gajicm93** [comment]
That's it, thanks!
