### ISSUE TITLE
Unable to install debug apk.

### ISSUE THREAD

**Issue by ronaldgalangy** [realm/realm-java#4615]
```
Compiling with JDK Java compiler API.
Note: Processing class User
Note: Creating DefaultRealmModule
An exception has occurred in the compiler (1.8.0_11). Please file a bug at the Java Developer Connection (http://java.sun.com/webapps/bugreport)  after checking the Bug Parade for duplicates. Include your program and the following diagnostic in your report.  Thank you.
com.sun.tools.javac.code.Symbol$CompletionFailure: class file for rx.Observable not found
:app:compileDebugJavaWithJavac FAILED
:app:compileDebugJavaWithJavac (Thread[Daemon worker Thread 5,5,main]) completed. Took 15.912 secs.

FAILURE: Build failed with an exception.
```
**User class**
```
public class User extends RealmObject {
   @PrimaryKey
   private long id;
   private String username;
}
```
In my Application class, onCreate method.
```
Realm.init(this);
```

Im not able to use the realm java for android. Im not sure if there is conflict between the realm and java 8. Do i need to use different java version?

Realm version(s): 3.1.4

Realm sync feature enabled: no

Android Studio version: 2.3.1

Which Android version and device: Any device

**Comment by Zhuinden** [comment]
You're using something hacky which seems to miss `rx.Observable` from the classpath,

considering you probably don't use RxJava1, you don't have to - just create a package in your project called `rx`, and create an empty class in it called `Observable`, then it will work

**Comment by bmeike** [comment]
@ronaldgalangy we can't reproduce this behavior.  Can you get us something that will let us see it happen?

**Comment by bmeike** [comment]
Hey @ronaldgalangy 
Haven't heard from you in a while.  I'm going to close this issue because we can't reproduce it.  By all means, if there is more that we can do, please get back in touch. I suggest that the best place to post an issue like this is StackOverflow.  I we can be of further assistance, please open a question there and we'll get right on it.

**Comment by lrodriguez** [comment]
This happened to me aswell, I solved it using the embedded JDK from Android Studio 3.0.1. instead of custom JDK installation
