### ISSUE TITLE
Allow removing fields from Synced schemas

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#4618]
Cocoa added support for removing properties from a model class again. It will not remove the field, but just hide it. We should implement something similar.

See https://realm.io/docs/swift/latest/#syncing-migrations

**Comment by cmelchior** [comment]
Should be fixed in 3.2.1

**Comment by Zhuinden** [comment]
Wait, really? You can hide fields now,

**Comment by cmelchior** [comment]
Yes, only in synced Realms though.

**Comment by Zhuinden** [comment]
That's still nice. It's better than having to have two set of your model classes with same name but different packages, one defined with this RealmModule, the other with that RealmModule, opening two Realms, mapping over, and saving the new data as the "recommended way to handle destructive schema migration" was. 😄
