### ISSUE TITLE
Support LinkingObjects in native glue code

### ISSUE THREAD

**Issue by bmeike** [realm/realm-java#4620]
There is a lot of code in the binding, now, to support queries on LinkingObjects.  The native code needs a few further fixes in order to make them work.

- [ ] Fix the getTableByArray method to support backlink queries
- [ ] Re-enable the backlink query unit tests, make sure they are clear and that they pass.
- [ ] Address @kneth 's comments, captured here.
- [ ] Add new unit tests as necessary to get good coverage

This issues follows #2904, #4529, #4323, #4321, #4519, and #4576

**Comment by bmeike** [comment]
In: realm/realm-library/src/androidTest/java/io/realm/LinkingObjectsQueryTests.java
```
    // Similar to the version in TestHelper, but with more Backlinks
    // Creates 3 NullTypes objects. The objects are self-referenced (link) in
    // order to test link queries.
    //
    // +-+--------+------+---------+--------+--------------------+
    // | | string | link | numeric | binary | numeric (not null) |
    // +-+--------+------+---------+--------+--------------------+
    // |0| Fish   |    0 |       1 |    {0} |                  1 |
    // |1| null   | null |    null |   null |                  0 |
    // |2| Horse  |    1 |       3 |  {1,2} |                  3 |
    // +-+--------+------+---------+--------+--------------------+
```
kneth: Can you include object in the table too?

**Comment by bmeike** [comment]
In: realm/realm-library/src/androidTest/java/io/realm/LinkingObjectsQueryTests.java
```
            // 10 Date
            nullTypes.setFieldDateNull(dates[i]);
            if (dates[i] != null) {
                nullTypes.setFieldDateNotNull(dates[i]);
            }

            nullTypesArray[i] = testRealm.copyToRealm(nullTypes);
        }
        nullTypesArray[0].setFieldObjectNull(nullTypesArray[0]);
        nullTypesArray[1].setFieldObjectNull(null);
        nullTypesArray[2].getFieldListNull().add(nullTypesArray[1]);
        testRealm.commitTransaction();
```

kneth: What will nullTypeArray[0].getFieldListNull() return? To increase readability, I think all three times fieldObjectNull and fieldListNull should be set.

Note that this code is strongly related to code it `TestHelper`.  If this code changes, perhaps that code should be reviewed as well.  Better yet, they should be re-united.

**Comment by Zhuinden** [comment]
Hmm... It's surprising that there are still native bugs if iOS has this, what's their secret?

**Comment by kneth** [comment]
Closing since #4704 has been merged. #4704 contains the glue code and fixes unit tests.
