### ISSUE TITLE
How to delete half of Realm

### ISSUE THREAD

**Issue by koukoucai** [realm/realm-java#4635]
My Code like that:

`realm.where(Test.class).findAll().sort("startDateString", Sort.ASCENDING);
  realmResults.deleteAllFromRealm();`

deleteAllFromRealm  this would  delete all of the data.
But I want delete half of it.
How can I do it？

**Comment by Zhuinden** [comment]
RealmResults<Test> test = realm.where(Test.class).findAllSorted("startDateString", Sort.ASCENDING);
    OrderedRealmCollection<Test> snapshot = test.createSnapshot();
    for(int i = 0; i < snapshot.size()/2; i++) {
          snapshot.get(i).deleteFromRealm();
    }

**Comment by koukoucai** [comment]
Except the circulate ,there were some better solution?

**Comment by Zhuinden** [comment]
Only if you set up some sort of ranking system on insertion.

Then you can do

    realm.where(Test.class).greaterThan("rank", realm.where(Test.class).count()/2).findAll().deleteAllFromRealm();

**Comment by koukoucai** [comment]
Got it. 
I  like your idea
