### ISSUE TITLE
I wants to save a key value pairs in the DB but Realm stops the compiling of the project when getting object like so

### ISSUE THREAD

**Issue by MohamedWael** [realm/realm-java#4639]
**Goal**
saving keyVlaue pair in the DB

**Expected Results**
keyValue pairs saved in the DB

**Actual Results**
the project stops compile as of Realm doesn't generate proxy classes 

**Code Sample**
```java
public class KeyValue <T extends RealmObject> extends RealmObject{
    @PrimaryKey
    private String key;
    private T object;

    public RealmKeyValue() {
    }

    public void setKeyValue(String key, T object) {
        this.key = key;
        this.object = object;
    }
}
```

**Version of Realm and tooling**
3.1.4

Realm sync feature enabled: no

Android Studio version: 2.3.2

Which Android version and device: 6

**Comment by Zhuinden** [comment]
Generic RealmObjects are not supported.

**Comment by MohamedWael** [comment]
Thanks for response

What if i want to do something like that, what it should like to be ?

**Comment by bmeike** [comment]
It isn't like we don't support that because we are grumps, I just isn't clear what it would mean, when storing stuff in the DB. ;-)  So, I have to ask:. When you say "I want to do something like that", what do you mean, exactly?  What are you trying to accomplish?  Happy to help, with a little more info...

**Comment by bmeike** [comment]
It isn't like we don't support that because we are grumps! It just isn't clear what that would mean, when storing stuff in the DB. ;-)  So, I have to ask:. When you say "I want to do something like that", what do you mean, exactly?  What are you trying to accomplish?  Happy to help, with a little more info...

**Comment by Zhuinden** [comment]
The problem is that each generic type of this class would be a new table, and I don't think that can be detected.

It would work if generics worked like they do in C++ but it doesn't.

**Comment by MohamedWael** [comment]
@bmeike My use case is to store many instances of an object that has no identifier ( primary ) key to use them in different contexts in my app i.e. 

I have a tutorial screen which display an array of image , title and some text - the object to be saved - each in a horizontal scrolling view, this is used to explain many different cases in my app.
I've been suggesting to store the ```tutorials``` objects in the form of key value in the DB, each object with the corresponding case, in order to get it using its key in the right context.

I hope i could make it more clear. 
```json
{
  "data": {
    "tutorials": [
      {
        "imageUrl": "https://www.google.com/logos/doodles/2015/googles-new-logo-5078286822539264.3-hp2x.gif",
        "title": "tutorial title",
        "content": "the content of the tutorial the content of the tutorial the content of the tutorial"
      },
      {
        "imageUrl": "https://www.google.com/logos/doodles/2015/googles-new-logo-5078286822539264.3-hp2x.gif",
        "title": "tutorial title",
        "content": "the content of the tutorial the content of the tutorial the content of the tutorial"
      },
      {
        "imageUrl": "https://www.google.com/logos/doodles/2015/googles-new-logo-5078286822539264.3-hp2x.gif",
        "title": "tutorial title",
        "content": "the content of the tutorial the content of the tutorial the content of the tutorial"
      }
    ]
  },
  "message": "success",
  "code": "200"
}
```

**Comment by Zhuinden** [comment]
Why not just

      public class Item extends RealmObject {
          private String imageUrl;
          private String title;
          private String content;
          @Index
          private String type; // <-- "tutorial"
       ...

**Comment by MohamedWael** [comment]
@Zhuinden 
I've done this solution few hours ago but i was clearing the case to @bmeike

**Comment by bmeike** [comment]
@MohamedWael I think you nailed it.  If it works, I'm happy!

Ok to close this now?

**Comment by MohamedWael** [comment]
yes, thank you
