### ISSUE TITLE
Automatically ignore static fields

### ISSUE THREAD

**Issue by aemeryjsa** [realm/realm-java#464]
Currently, static fields in the model contribute to the model definition. 

For example, the following class contains the static, final field MAX_ROOMS.

``` java
public class House extends RealmObject {
    private int roomCount;
    public static final int MAX_ROOMS = 10;
}
```

Attempting to compile results in the the following compile-time exception:
Error:The fields of the model must be private

I don't think static fields should contribute to the model definition. They belong to the class, not the instance, so it doesn't make sense for them to become a model property. They should be implicitly ignored.

Adding the Ignore annotation to the field allows it to compile:

``` java
public class House extends RealmObject {
    private int roomCount;
    @Ignore public static final int MAX_ROOMS = 10;
}
```

Also, the error message could be improved by mentioning what field in what class caused the exception.

Realm: 0.70.1
Android Studio: 0.8.11
OS: Window 8

**Comment by Groxx** [comment]
fwiw that pull request appears to only ignore static _methods_.  I haven't read it closely enough to be certain, but the comments imply it, and at the very least Realm 0.76.0 doesn't ignore my static fields.

**Comment by denley** [comment]
This is not fixed. I am having the same issue using 0.76.0.

Static methods are ignored properly, but not static fields.

**Comment by mpost** [comment]
Confirmed. public static final fields are not ignored in <code>0.78.0</code>

**Comment by freezy** [comment]
Also it crashes with the dreaded NPE that doesn't give any indication at all what the problem might be.

**Comment by mpost** [comment]
The debug message leaves something to be desired indeed. When running code without an @Ignore from inside AndroidStudio it doesn't hint at what the problem is. Only when running an <code>gradlew assemble -info</code> do we get proper error messages.
