### ISSUE TITLE
Upgrading from Realm 2.3.0 to 3.1.4 wiped the data

### ISSUE THREAD

**Issue by ozv101** [realm/realm-java#4640]
#### Goal

> Realm doesn't delete the DB when upgrading Realm versions

#### Expected Results

> Data remains.

#### Actual Results

>  Data is cleared. 

#### Steps & Code to Reproduce

> Upgrade Realm and launch the project.

#### Version of Realm and tooling
Realm version(s): 2.3.0 to 3.1.4

Realm sync feature enabled: no

Android Studio version: 2.3.2

Which Android version and device: 7.1

**Comment by cmelchior** [comment]
Hi @ozv101 
Realm doesn't delete any data when upgrading, so something in your code must be doing it.

**Comment by Zhuinden** [comment]
You probably had `deleteIfMigrationNeeded` on and changed fields or added classes

**Comment by ozv101** [comment]
Ok so it was a data issue on my end. I was not using `deleteIfMigrationNeeded` though. 
Thanks.
