### ISSUE TITLE
how to Building Realm

### ISSUE THREAD

**Issue by ScalletLeng** [realm/realm-java#4653]
> We LOVE to help with any issues or bug you have!

> **Questions**: If you have questions about how to use Realm, please ask on [SO](http://stackoverflow.com/questions/ask?tags=realm) - we monitor the Realm tag.

> **Feature Request**: Just fill in the first two sections below.

> **Bugs**: To help you as fast as possible with an issue or bug please describe your issue and the steps you have taken to reproduce it in as many details as possible.
>
> Thanks for helping us help you :-)
>
> Remove this and above before submitting.

#### Goal

> my current project has armeabi，and  we want to use realm in our project。But we know   armeabi is not supported anymore in realm.So  we want to build realm myself ，then we can use realm jar and so。

#### Expected Results

> build jar and so files。

#### Actual Results

>  Error:A problem occurred configuring project ':realm-library'.
 executing external native build for cmake E:\workspace_as\1__down_to_learn_app\realm-java\realm\realm-library\src\main\cpp\CMakeLists.txt

#### Steps & Code to Reproduce

> Describe your current debugging efforts.

#### Code Sample

click CMake button

> Your code here. Bigger samples should ideally be as separate Android Studio project, 
> in gists/repositories or privately at help@realm.io)

```

#### Version of Realm and tooling
Realm version(s): the lastest 3.1.4

Realm sync feature enabled: yes

Android Studio version: 2.3.1

Which Android version and device: android 25

**Comment by beeender** [comment]
You cannot build Realm with ndkr10e for armeabi because of there is some problems to compile atomics with gcc 4.9 for armeabi.

You actually can just use arm-v7a instead since as far as I know there is quite a few devices only support armeabi in the market.

**Comment by lengqi19860101** [comment]
How do I build realm in order to get arm-v7a?

**Comment by beeender** [comment]
It comes with our release, `armeabi-v7a`.

**Comment by ScalletLeng** [comment]
Thank you. I'm so stupid

**Comment by ScalletLeng** [comment]
Why did I fail to compile? Can you tell me the procedure?

**Comment by beeender** [comment]
I am not sure why did you fail. None of us uses Windows 😀

**Comment by ScalletLeng** [comment]
All right. But I didn't find release, armeabi-v7a，can you tell me where it is?

**Comment by beeender** [comment]
It is released as a gradle plugin. it will be packed to your apk file automatically if you follow our installation steps https://realm.io/docs/java/latest/#installation

**Comment by ScalletLeng** [comment]
I know this.But because our project only supports armeabi, so gradle plugin will fail. I want to introduce realm in the form of jar and so.

**Comment by beeender** [comment]
What do you mean by "our project only supports armeabi"? Is that because of you have some other 3rd party libs which only have `armeabi` so files?

**Comment by ScalletLeng** [comment]
Yes, that's it

**Comment by beeender** [comment]
you can just copy the 3rd party so file from `armeabi` directory to `armeabi-v7a` directory.

**Comment by ScalletLeng** [comment]
No, people from third parties told me they only supported armeabi ，they told me I just copy the realm  armeabi-v7a library into our armeabi

**Comment by beeender** [comment]
`armeabi` should be supported on all `armeabi-v7a` devices, but NOT the vice versa.

**Comment by ScalletLeng** [comment]
The 3rd party can not be changed, then we can not use realm?

**Comment by beeender** [comment]
First, there will be a risk if you use `armeabi-v7a` so on `armeabi` only devices as I said before.
you can:
1. There should be a way to copy `so` file from `armeabi-v7a` to `armeabi` during packaging stage in gradle. But I don't have an immediate answer, you may need to figure it our by yourself.
or
2. you can find all the realm-java native libraries file in `$HOME/.m2/repository/io/realm/realm-android-library/x.x.x/realm-android-library-x.x.x.aar`. Just unzip it then you can find them in the `jni` folder.

**Comment by ScalletLeng** [comment]
Ok，I‘ll hava a try .Thank you.

**Comment by bmeike** [comment]
Hey @ScalletLeng!
I'm going to close this ticket, because it looks to me as if @beeender has answered your question.  By all means let us know if you have any other questions.  We'd prefer to handle things like this (questions, not feature requests or bugs) on StackOverflow, if that works for you.
