### ISSUE TITLE
Investigate odd memory use

### ISSUE THREAD

**Issue by bmeike** [realm/realm-java#4657]
This application runs out of memory in a particularly precipitous manner.  It is likely to be a bug and requires investigation.

https://drive.google.com/open?id=0B8IZPM39UfyXWnN0RWgzUUkza2s

**Comment by bmeike** [comment]
Here is a profile of a run of the app, from button push, to failure.

![profileii](https://cloud.githubusercontent.com/assets/277848/26174651/f60b2b00-3b04-11e7-9dab-3b7013152b14.png)

**Comment by Zhuinden** [comment]
``` java
    private void saveIntoDatabase() {
        realm.executeTransactionAsync(new Realm.Transaction() {
            @Override
            public void execute(Realm bgRealm) {
                Person person = new Person();
                for(int i=0;i<500000;i++){
                    person.name = "rami"+i;
                    person.age = 27;
                    person.info1 = "some random string";
                    person.info2 = "some random string";
                    person.info3 = "some random string";
                    person.info4 = "some random string";
                    person.info5 = "some random string";
                    person.info6 = "some random string";
                    person.info7 = "some random string";
                    person.info8 = "some random string";
                    person.info9 = "some random string";
                    person.info10 = "some random string";
                    person.info11 = "some random string";
                    person.info12 = "some random string";
                    person.info13 = "some random string";
                    person.info14 = "some random string";
                    person.info15 = "some random string";
                    person.info16 = "some random string";
                    person.info17 = "some random string";
                    person.info18 = "some random string";
                    person.info19 = "some random string";
                    person.info20 = "some random string";
                    person.info21 = "some random string";
                    person.info22 = "some random string";
                    person.info23 = "some random string";
                    person.info24 = "some random string";
                    person.info25 = "some random string";
                    person.info26 = "some random string";
                    person.info27 = "some random string";
                    person.info28 = "some random string";
                    person.info29 = "some random string";
                    person.info30 = "some random string";
                    person.info31 = "some random string";
                    person.info32 = "some random string";
                    person.info33 = "some random string";
                    person.info34 = "some random string";
                    person.info35 = "some random string";
                    person.info36 = "some random string";
                    person.info37 = "some random string";
                    person.info38 = "some random string";
                    person.info39 = "some random string";
                    person.info40 = "some random string";

                    Log.i("item",i+" inserted");
                    bgRealm.insert(person);
                }
            }
        }, new Realm.Transaction.OnSuccess() {
            @Override
            public void onSuccess() {
                // Transaction was a success.
                Log.v(LOG_TAG, "Stored successfully");
                closeRealm(realm);
                progressDialog.cancel();
            }
        }, new Realm.Transaction.OnError() {
            @Override
            public void onError(Throwable error) {
                // Transaction failed and was automatically canceled.
                Log.e(LOG_TAG, "Error came up while insertion, rolled back");
            }
        });

    }
```

Please try with these changes

**Comment by bmeike** [comment]
Sure!  Why?

**Comment by Zhuinden** [comment]
Just curious about what happens if you insert the 500000  items with 1 unmanaged java object instead of 500000 new objects. As in, does it still do the same odd memory usage thing.

**Comment by bmeike** [comment]
This seems to be related to the cache that we keep in the Mediator object:  ```    public static void insertOrUpdate(Realm realm, Iterator<? extends RealmModel> objects, Map<RealmModel,Long> cache) {
        Table table = realm.getTable(model.Person.class);
        long tableNativePtr = table.getNativePtr();
        PersonColumnInfo columnInfo = (PersonColumnInfo) realm.schema.getColumnInfo(model.Person.class);
        model.Person object = null;
        while (objects.hasNext()) {
            object = (model.Person) objects.next();
            if(!cache.containsKey(object)) {
                if (object instanceof RealmObjectProxy && ((RealmObjectProxy)object).realmGet$proxyState().getRealm$realm() != null && ((RealmObjectProxy)object).realmGet$proxyState().getRealm$realm().getPath().equals(realm.getPath())) {
                    cache.put(object, ((RealmObjectProxy)object).realmGet$proxyState().getRow$realm().getIndex());
                    continue;
                }
                long rowIndex = OsObject.createRow(realm.sharedRealm, table);
                cache.put(object, rowIndex);
```
While not yet a smoking gun, it is clear that this Map is getting *very* big.

**Comment by bmeike** [comment]
Some data from the memory analyzer.

<img width="1946" alt="mem-2" src="https://cloud.githubusercontent.com/assets/277848/26333608/b64dc924-3f13-11e7-9048-abbf78525774.png">

<img width="1949" alt="mem-3" src="https://cloud.githubusercontent.com/assets/277848/26333612/bb2c5f00-3f13-11e7-9f8f-e3690f53f82f.png">

Note that using Realm 3.2.1, the app hangs but does not abort.

**Comment by bmeike** [comment]
There are two separable issues, here:

1. You can run a program out of memory, by adding things to a Realm DB
2. The way the application appears to run out of memory, in the snapshot above, is odd. 

WRT #1: yes, you can run an application out of memory by storing things to a Realm DB.  That issue is tracked here: https://github.com/realm/realm-core/issues/2614 and here: https://github.com/realm/realm-core/issues/1467

WRT #2: the memory graph looks funny because of a `Log` statement.  The program being profiled first constructs a List with 500000 objects in it, and then attempts to commit entire contents of the List.  The Log statement logs each new item as it is added to the List.  Because of that, the List creation takes nearly 2 minutes (the slow part of the graph).  At approximately 2:15, the List is complete and the program starts insertion into the DB, causing the rapid memory growth.

Here is a picture of memory use for the same program, with the `Log` statement removed:
<img width="1328" alt="crash-single" src="https://cloud.githubusercontent.com/assets/277848/26417914/5b53a6f8-406f-11e7-8a36-e623638467fc.png">

Closing this ticket as a duplicate of the two mentioned in WRT #1 above.
