### ISSUE TITLE
Realm loses context while running in the background. 

### ISSUE THREAD

**Issue by monkeyR** [realm/realm-java#4660]
I'm using Realm version 1.1.0. 
My application's main objective is to run in background using a service. While running in the background, after long time (for example after 3 hours)
Realm loses context and crashes, giving me "java.lang.IllegalArgumentException: A non-null Context must be provided." I don't know why this is happening.
Context is provided from Application. Problem is very urgent, because my application is published and used by many users. 
Can you help me?

Android Studio version: 2.3.2
Android version and device: all systems and devices

**Comment by karolszmajapzumi** [comment]
I got the same situation in our production application. I hope that there is a workaround for this serious issue.

**Comment by cmelchior** [comment]
Without more context, there is not much we can do. E.g what does the code look like that acquires the `Context`.

But note that the newest version is `3.2.0`, so I would recommend upgrading to that instead. It has among other things changed how the Context is acquired and held.

**Comment by monkeyR** [comment]
Thank you for the tip, I'm making the upgrade of version of Realm. I'm testing application now.
I hope that this solution will solved the problem.

**Comment by Zhuinden** [comment]
Depends on where you initially set the context.

**Comment by monkeyR** [comment]
I initiate context in my backgroud service. It is context from application (getApplicationContext()).

**Comment by bmeike** [comment]
@monkeyR, without code, we really can't move forward with this.

My guess is that you are not synchronizing the lifecycles of the thread on which you are running Realm, with the lifecycle of the Context object you pass to the Realm.  THis could happen, for instance, if a Service spawned a thread and you used the Service as the context for the Realm.  Eventually, when the Service is stopped and the Realm thread is not, the application fails.

Delighted to help, but we are going to need code.

**Comment by bmeike** [comment]
@monkeyR Can you provide some code that will drive the issue you are seeing?  Unless we can reproduce it, we aren't going to be able to do much about it.

**Comment by monkeyR** [comment]
Thank you for your replies. Your suggestions helped me solve this problem. :)  
However, there is another one when I try to "add" the Realm element to list:

This method is not supported by 'RealmResults' or 'OrderedRealmCollectionSnapshot
This situation is only when working in background and when my service is restarting.  Realm is initiated again when the backgroud loses the context. 

Is there any way to circumvent this?

**Comment by Zhuinden** [comment]
@monkeyR well what method is it?

**Comment by kneth** [comment]
@monkeyR Could you post some code so we have a better chance to understand the issue?

**Comment by kneth** [comment]
I am closing the issue due to lack of activity. @monkeyR When you have the time to post code, you are welcome to reopen the issue.
