### ISSUE TITLE
Realm 3.2.0 No Sources Attached

### ISSUE THREAD

**Issue by eygraber** [realm/realm-java#4671]
Using Android Studio 2.3.2, I updated to Realm 3.2.0, and there are no longer any Java sources attached. Only the class files.

**Comment by beeender** [comment]
Try clean and re-sync? I just checked the bintray, the 3.2.0 source is uploaded.

**Comment by beeender** [comment]
hmmm, I can reproduce this, no idea what is wrong...

**Comment by beeender** [comment]
I switch back to `3.1.4` then `3.2.0`, AS could find the source again. It seems to be an AS problem? Can you try it?

**Comment by eygraber** [comment]
Downgraded to `3.1.4` and no `Realm` class could be resolved. Restarted AS and they were resolved, but still no sources. Updated back to `3.2.0` and still no sources 😢

**Comment by beeender** [comment]
does `clean & gradle sync` help?

**Comment by eygraber** [comment]
Nope

**Comment by beeender** [comment]
try `gradle build --refresh-dependencies` ?

**Comment by beeender** [comment]
also, you may want to try to delete the gradle caches `rm -rf $HOME/.gradle/caches/`, that will delete all gradle caches ..

**Comment by eygraber** [comment]
Still nothing.

This is from the "External Libraries" view in AS:


![capture](https://cloud.githubusercontent.com/assets/1100381/26232267/060029b0-3c23-11e7-8627-b58df153fc31.PNG)

**Comment by beeender** [comment]
Do you have `$HOME/.m2/repository/io/realm/realm-android-library/3.2.0/realm-android-library-3.2.0-sources.jar` on your disk?

**Comment by eygraber** [comment]
I have `$HOME/.m2/repository/` but nothing recent in it. I think that's when AS started using the build cache.

**Comment by Zhuinden** [comment]
You can try invalidate caches and restart in file menu

**Comment by eygraber** [comment]
@Zhuinden tried that too.

**Comment by Zhuinden** [comment]
At this rate I'd try reimporting the project

**Comment by bmeike** [comment]
@eygraber , you might also try killing off gradle daemons, if there are any of them around.
This is some kind of caching issue.  You might also try removing ~/.gradle.  I believe that gradle is actually storing the sources in ./caches/modules-2/files-2.1/io.realm/realm-android-library/3.2.0

**Comment by eygraber** [comment]
@bmeike that directory just contains an aar with no sources in it. I stopped all daemons, deleted the directory, opened AS, and checked that directory again. Still just an aar:
[
![capture](https://cloud.githubusercontent.com/assets/1100381/26265190/1598282e-3cae-11e7-8c23-46ad5853e15a.PNG)
](url)

**Comment by bmeike** [comment]
I have just verified that the source for the 3.2.1 release is downloaded and visible from the IDE.

I deleted all caches (.gradle, .m2, etc) and created a new project.  I added the Realm plugin, command-clicked `Realm.init` and was immediately taken to the source, including comments.  Autoscrolling the project browser to from the source shows that the source is in the file realm-android-library-3.2.1.  I believe this is conclusive.  The source is located in:

~/.gradle/caches/modules-2/files-2.1/io.realm/realm-android-library/3.2.1/<hash>/realm-android-library-3.2.1-sources.jar

Please note, @eygraber , that the cached source is not in the `res` directory in your project, it is in your home directory.

**Comment by bmeike** [comment]
This appears to be a gradle problem.  Gradle is parsing the pom and then downloading its contents, piece by piece.  Although the source download worked fine, for me, with Gradle 3.3, simply switching to Gradle 3.4.1 breaks it.  It takes, essentially, reloading the entire project, using Gradle 3.3, and clearing all caches to get it to work again. 

Filed: https://issuetracker.google.com/issues/38504662

**Comment by bmeike** [comment]
FWIW: The issue has been fixed and is scheduled for release in 3.0.  See the ticket above.
