### ISSUE TITLE
Indexes cannot change in Synced Realm schemas

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#4672]
Discovered while working on https://github.com/realm/realm-java/pull/4666

Currently, our annotation processor generates code that checks for indexes or not based on the local Realm schema, and it doesn't look like the Object Store logic correctly rebuild indexes even if the schema version is changed.

This needs to be fixed.

The semantics for changing indexes are a bit unclear to me though, so those needs to be clarified first.

Cases (schemaVersion, index)

| Device A   | Server | Result |
| ------------- | ------------- | ------------- |
| (1, hasIndex)  | (1, noIndex)  |  (1, hasIndex)? |
| (1, hasIndex)  | (2, noIndex)  |  (2, hasIndex)? |
| (2, hasIndex)  | (1, noIndex)  |  (2, hasIndex)? |
| (1, noIndex)  | (1, hasIndex)  |  (1, hasIndex)? |
| (1, noIndex)  | (2, hasIndex)  |  (2, hasIndex)? |
| (2, noIndex)  | (1, hasIndex)  |  (2, hasIndex)? |

**Comment by beeender** [comment]
@cmelchior I think #4887 fixed this? (It removes the related tests' FIXME)
