### ISSUE TITLE
`User` is not part of the schema for this Realm

### ISSUE THREAD

**Issue by madd86** [realm/realm-java#4675]
Say I wanna know whether User is empty (whether it's their first time using the app).

This is my code: 

    public boolean isEmpty() {
        Realm myRealm = Realm.getInstance(this);
        User results1 = myRealm.where(User.class).findFirst();
        return results1 == null;
    }

If it's the first time using the app, I need to know that, because if that's the case, I need to ask the user to fill the form. (It's not really authentication, just a simple form).

In this situation, how can I know whether User exists without having to create a record.

Edit:

Here's the stack:

    FATAL EXCEPTION: main
                                                                      java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.ga.xuser/com.example.ga.xuser.View.Activities.Profile}: java.lang.IllegalArgumentException: User is not part of the schema for this Realm
                                                                          at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2211)
                                                                          at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2261)
                                                                          at android.app.ActivityThread.access$600(ActivityThread.java:141)
                                                                          at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1256)

**Edit**: To clarify, I'm using 0.82.1

**Comment by Zhuinden** [comment]
Why are you still using 0.82.1?

**Comment by madd86** [comment]
Yeah, I was following a tutorial. Since, most tutorials are based on the old versions.

I apologize. After upgrading to 3.2.1 a simple check whether results are null now work.

Please close this topic. Thank you.

**Comment by Zhuinden** [comment]
You were following the Ravi Tamada tutorial on androidhive.info, right? 

That's a pretty bad tutorial, filled with bad practices. 

I recommend checking out [my article](https://medium.com/@Zhuinden/how-to-use-realm-for-android-like-a-champ-and-how-to-tell-if-youre-doing-it-wrong-ac4f66b7f149) but also its two accompanying example repositories (one of which is a rewrite of the tutorial you mentioned):

https://github.com/Zhuinden/realm-book-example

And

https://github.com/Zhuinden/xkcd-example/
