### ISSUE TITLE
Call reconnect when refresh token is received

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#4676]
For details:

> there should be very little to change binding-side to resolve this, just to call `cancel_reconnect_delay()` when receiving a refreshed token. See cocoa PR: https://github.com/realm/realm-cocoa/pull/4957

**Comment by nhachicha** [comment]
@cmelchior we already call `reconnect` in the Java binding, the only thing needed is to update to the latest ObjectStore version that includes the logic to ask for token refresh (in case of reconnect).

current OS commit for release is `4330f13eedfad4f34bcecdca25f71fb949fbc4b2` which doesn't include this fix, I can make a PR to update the OS but this will require pulling sync `1.10.0` like [Cocoa](https://github.com/realm/realm-object-store/compare/f5e1ce7bb5ceda14dfff9b2412618f8ea9f6be74...1e3cbb178952e26112a474f596aad6bf4f938adf#diff-2ff290528e51915a0bbb14a336ff2683). are we cool with this?

**Comment by nhachicha** [comment]
This issue can be closed once https://github.com/realm/realm-java/pull/4707 is merged

**Comment by nhachicha** [comment]
https://github.com/realm/realm-java/pull/4707 merged
