### ISSUE TITLE
Realm and RXJAVA2 together with the use of the problem

### ISSUE THREAD

**Issue by AndroidJohnsonWang** [realm/realm-java#4679]
I use the latest Realm, see examples inside the RXJAVA is out of date, would like to ask whether compatible with RXJAVA2?
Thanks

**Comment by cmelchior** [comment]
Realm currently exposes RxJava 1 Observables, but you can relatively easy wrap our RealmChangeListeners to expose RxJava2 Flowables/Observables instead, see e.g https://github.com/realm/realm-java/issues/3497#issuecomment-275383550 

Alternatively interop libraries exists like https://github.com/akarnokd/RxJava2Interop

We will switch to RxJava2, but when hasn't been decided yet, nor exactly how the API is going to look like. You can follow #3497 for progress on that.

**Comment by KomoriWu** [comment]
Thank you, hard work
