### ISSUE TITLE
how to modify java source code or build realm myself?

### ISSUE THREAD

**Issue by halo332035436** [realm/realm-java#4680]
hi there, i would like to make some changes on realm java source code. however installing realm based on ur online instruction does not allow me to change the source code. I tried to build realm my self based on ur suggestion on the github realm java page，but still failed because there is no file unamed r10e in the folder android-ndk-r10e, and no file named local.roperties. Any solution?

**Comment by cmelchior** [comment]
You should create `local.properties` yourself (Android Studio does this automatically afaik).
Android NDK r10e might live in another location, depending on where you installed it, but as long as you point to it, it should work.

**Comment by halo332035436** [comment]
thanks for reply. i followed ur instruction. Since i do not have https protocol，i cannot use got clone command. i download the zip file of source code directly from realm-java website. then when i try to build in git with "./gradlew assemble", it says: a problem occurred configuring project ': realm-annotations'.  Could you pls help on this? Thanks.

**Comment by kneth** [comment]
I don't it is possible to build without access to Github. Parts of our source code is coming from another git repository as a submodule. Simply put, the zip file doesn't contain the full code. 

Sorry for my ignorance, but why can't you clone using HTTPS?

**Comment by kneth** [comment]
@halo332035436 If you can clone from Github, I believe that you might have to do `./gradlew installRealm` first.
