### ISSUE TITLE
RealmChangeListener's onChange doesn't get triggered at times

### ISSUE THREAD

**Issue by prvnmit** [realm/realm-java#4681]
> **Bugs**: 

I use RealmChangeListener to listen when an async query returns. But, the listener's onChange doesn't get triggered at times

Am not sure if the way I use the listener is wrong, or there is an issue with the listener's implementation. 
Please help out:

I use the below code:

#### Code Sample

```java
void showUI() {
	RealmResults<MyRecord> results = mRealm.where(MyRecord.class).findAllSortedAsync("mMyLabelUpperCase");

	RealmChangeListener<RealmResults<MyRecord>> appResultsListener = new RealmChangeListener<RealmResults<MyRecord>>() {
		@Override
		public void onChange(RealmResults<MyRecord> myRecords) {
			// my code to show UI will be here...
			
			myRecords.removeChangeListener(this);
		}
	};

	results.addChangeListener(appResultsListener);
}
```

#### Version of Realm and tooling
Realm version(s): 3.1.3

Android Studio version: 2.3.2

Which Android version and device: Android 7.1.1/Le 2 ; Android 4.3/ Samsung galaxy S3

**Comment by beeender** [comment]
> The notification delivery can be stopped by calling the removeChangeListener() or removeAllChangeListeners() method. The notification delivery will also be stopped if the object which the listener was registered on is GCed or the corresponding Realm instance is closed. You should keep a strong reference of the object which the listener is registered on as long as you still need the notification to be delivered.

https://realm.io/docs/java/latest/#notifications

You need to keep `results` as a member var to make sure it is not GCed before you end with the listener.

**Comment by prvnmit** [comment]
Thank you so much for the response. 
I have updated my code as below : 
```java
private RealmResults<MyRecord> mRealmMyResults;

void showUI() {
	mRealmMyResults = mRealm.where(MyRecord.class).findAllSortedAsync("mMyLabelUpperCase");

	RealmChangeListener<RealmResults<MyRecord>> appResultsListener = new RealmChangeListener<RealmResults<MyRecord>>() {
		@Override
		public void onChange(RealmResults<MyRecord> myRecords) {
			// my code to show UI will be here...
			
			mRealmMyResults.removeChangeListener(this);
		}
	};

	mRealmMyResults.addChangeListener(appResultsListener);
}
```
Hope I'm doing it the right way now! Correct me if I'm wrong
Thank you.

**Comment by beeender** [comment]
Yes, it should work as long as your object instance is not GCed.
