### ISSUE TITLE
Invalid type 'String' for field 'id' in existing Realm file

### ISSUE THREAD

**Issue by madd86** [realm/realm-java#4682]
I got a realm database going.

    @PrimaryKey
    private String id;
    private String type;
    private byte[] file;

With their respective getters and setters.

I'm trying to add a record to that database by the following command:

        try {
            loadRealm(); // Realm.init(context) and myRealm = Realm.getDefaultInstance()
            myRealm.executeTransaction(realm -> {
                SolicitationDatabase solicitationDatabase = myRealm.createObject(SolicitationDatabase.class, UUID.randomUUID().toString());
                solicitationDatabase.setType(mMainVariables.getType());
                solicitationDatabase.setFile(new byte[0]); //This should be empty, I'm only storing a file IF a file is found.
            });
        } finally {
            if(myRealm != null) {
                myRealm.close();
            }
        }

Error: 

    05-22 16:32:11.151 30366-30366/com.example.ga.realm3 E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: com.example.ga.realm3, PID: 30366
                                                                       io.realm.exceptions.RealmMigrationNeededException: Invalid type 'String' for field 'id' in existing Realm file.
                                                                           at io.realm.SolicitationDatabaseRealmProxy.validateTable(SolicitationDatabaseRealmProxy.java:605)
                                                                           at io.realm.DefaultRealmModuleMediator.validateTable(DefaultRealmModuleMediator.java:56)

**Comment by kneth** [comment]
The error message indicates that you have changed the type of field `id`.

**Comment by madd86** [comment]
@kneth I changed from int to String, since the only the only way I found to generate the id is `UUID.randomUUID().toString()`.

How can I fix it?

**Comment by madd86** [comment]
Uninstalled the app on the device and ran it again, that seems to have fixed it.

**Comment by kneth** [comment]
Good to hear!

If you are in the development phase, I will recommend that you add `.deleteRealmIfMigrationNeeded()` to your `RealmConfiguration`. Once in production, you will need a [migration step](https://realm.io/docs/java/latest/#migrations) when you modify a model class in order for your users not loosing data when upgrading the app.

**Comment by Zhuinden** [comment]
If you change field type from `int` to `string`, you need to increment schema version and define a migration that adds a temporary field with `string`, do a `transform()` that maps existing int `id` to the temporary field, call `removePrimaryKey()`, remove the id field, rename the temporary field to `id`, and `addPrimaryKey` to the new `id` field.
