### ISSUE TITLE
Data sometimes not available immediately after commitTransaction

### ISSUE THREAD

**Issue by gajicm93** [realm/realm-java#4688]
So this is what I do:

1. Create an object (main thread)
2. Insert it into realm (main thread)
3. Commit transaction (main thread)
4. Start network request with that object (main thread)

Now this is where the problem happens:

5. When the request callback returns (network thread), which is 50-100ms later for example, I try to fetch that same object from Realm on the network thread (because I can't reuse object from main thread right?), and Realm returns null, it can't find it.

I'm on Android, but it's also happening to colleagues on iOS.

**Comment by cmelchior** [comment]
Realm is a MVCC database. This means that each thread gets its "own" version of Realm. We automatically update threads, but this is done using the Looper, so there is a delay.

If you use RealmChangeListeners, you _will_ be notified when the data is available, but if you use your own mechanism like an eventbus, that event might arrive before Realm has updated that thread.

I would recommend reading: https://news.realm.io/news/threading-deep-dive/
With 3.2 we re-added `Realm.refresh()` that will force any thread to the newest version, but it will also force all async queries to be synchronous, which might not be what you want.

**Comment by gajicm93** [comment]
@cmelchior Ok but just to be clear, the Realm instance for the network thread is created for the first time after I call commit on the previous transaction (so it's not a previously existing instance that's supposed to be updated). Is that still a normal behavior?

**Comment by cmelchior** [comment]
In that case, yes, the data should be in the Realm. 
A Realm should always be at the latest version when:
1) Opening the Realm for the first time
2) You call `beginTransaction()`
3) You call `realm.refresh()`

Could the network thread be using an old Realm version by accident? E.g. if you are not closing the Realm again

**Comment by gajicm93** [comment]
```
Project onSuccess(Response response) throws IOException, JSONException, ParseException {
        JSONObject projectJson = new JSONObject(response.body().string());
        Realm realm = Realm.getDefaultInstance();
        realm.beginTransaction();
        Project project = realm.where(Project.class).equalTo("mServerId", projectJson.getInt("id")).findFirst();
        project.update(projectJson);
        realm.commitTransaction();
        realm.close();
        return project;
    }
```

This is the complete callback which is running on the network thread. Realm sometimes returns null for the Project (which was created and commited on the main thread before even starting a network request). So I call both getInstance and beginTransaction, and always close Realm afterwards.

NOTE: I'm using OkHttp, which uses a ThreadPoolExecutor, which reuses threads, so in theory it might be possible that I get called on the thread used for previous network call, and that Realm already has an instance for that thread. But I also always call close.. So that should be happening..

**Comment by cmelchior** [comment]
Yes, queries inside transactions should always be up to date. Are you 100% the data wasn't perhaps deleted in the meantime?

**Comment by gajicm93** [comment]
@cmelchior My mistake, posted you the wrong code, in the request that was a problem I did a query before beginTransaction.

But still, the only case it should cause a problem is if OkHttp reused a thread, and Realm already had an instance for it.. But I always call close.. So still shouldn't be happening.

Anyways, I'll see if querying after beginTransaction fixes it.. But it's still weird.

Thanks for all the info for now.

**Comment by cmelchior** [comment]
If you `onSuccess` callback crashes, it might never close the instance. I would wrap it in a try-finally

**Comment by gajicm93** [comment]
@cmelchior Already did, in a super-class all my requests extend from 😄

**Comment by gajicm93** [comment]
Btw, your support around here is just amazing, congratulations and thank you! @cmelchior

**Comment by Zhuinden** [comment]
On background non-looper threads, querying inside transaction guarantees that you always see the latest version of the data. 

Realm 3.2.0 (re-)introduced `realm.refresh()` which allows a background non-looper thread to refresh itself to the latest data even if it was stuck on a previous version. Although with general use, that tends to happen if a Realm instance is unclosed.

**Comment by kneth** [comment]
@gajicm93 Sounds like you have got answers so I am closing the issue. As always, don't hesitate to create a new issue.

**Comment by Jenishleap** [comment]
:ok:
