### ISSUE TITLE
Querying the realm db by element in list  - help

### ISSUE THREAD

**Issue by lazarvgd** [realm/realm-java#4691]
Hi, I need help to query the db. I have class Movie that contains List<Genre> objects.
Every Genre object has a name that represent the name of genre. I need to write query so I can get list of all movies which contains genre object with(for example) name="horror".

Can you please help me to learn and write this query for realm db in java?

Thanks

p.s. If you need any additional information, please let me know.

**Comment by cmelchior** [comment]
```
realm.where(Movie.class).equalTo("genres.name", "horror").findAll();
```
Should do the trick
Queries on RealmLists will match if any element in the list matches.

**Comment by lazarvgd** [comment]
thanks buddy :) this works just fine :+1:
