### ISSUE TITLE
updating realm object dynamicly

### ISSUE THREAD

**Issue by idok595** [realm/realm-java#4692]
it is possible to update realm obejct dynamcly? 
for example let assume that i have 2 realm objects from the same type, this type of obejct has no primary key

objectA -  is valid and manges realm object 
objectB -  is not manged but valid realm object,

i want to replace all values inside objectA with values from objectB without knowing the sturectre of this objects, in DynamicRealmObject it is possbile simple itarete all feilds but i think it will be very usefull to have this functionality also in RealmObject

**Comment by Zhuinden** [comment]
This can be done with reflection, as long as you use accessor methods instead of fields directly.

**Comment by kneth** [comment]
@idok595 As @Zhuinden points out, you can use reflection. But reflection on Android is pretty expensive, and that's why we took another route ;-)
