### ISSUE TITLE
No Longer Receiving Object Creation Notification

### ISSUE THREAD

**Issue by qtstc** [realm/realm-java#4695]
I was using 
```java
realm.where(Item.class).equalTo("id", id).findFirstAsync().asObservable().filter(
    new Func1<item, Boolean>() {
      @Override public Boolean call(Item item) {
        return item.isLoaded() && item.isValid();
      }
    }).subscribe(new Action1<Item>() {
  @Override public void call(Item item) {
     // Do stuff
  }
})
```
to listen to changes to the Item with the id. Before 3.1.0, if the item with the specified id is not in Realm yet, the observable would be triggered when the item is created. This is no longer the case.

**Comment by Zhuinden** [comment]
That's because the old behavior was a bug, see https://github.com/realm/realm-java/pull/4358

You're looking for `findAllAsync()` in this use-case.

**Comment by qtstc** [comment]
That worked! Thanks! 

One thing I noticed after switching to findAllAsync is that findAllAsync doesn't seem to support single object notification, e.g. the observable's onNext is called when a RealmObject field of Item is changed. This is different from the behavior of findFirstAsync when I am querying for the Item with the same id.

**Comment by kneth** [comment]
`findAllAsync()` returns a collection of objects (a `RealmResults`) while `findFirstAsync()` returns a single object (`RealmObject`). For `RealmResults` you get a change set so you know which objects are changed - and how. Not the same thing, I know.

**Comment by Zhuinden** [comment]
Well. You can actually try the following, although I'm not sure about its behavior.

``` java
realm.where(Item.class).equalTo("id", id).findAllAsync().asObservable().filter(
    new Func1<item, Boolean>() {
      @Override public Boolean call(RealmResults<Item> items) {
        return items.isLoaded() && items.isValid() && !items.isEmpty();
      }
    }).switchMap(new Func1<RealmResults<Item>, Item>() {
        @Override
        public Observable<Item> call(RealmResults<Item> items) {
            return items.get(0).asObservable();
        }
    }).subscribe(new Action1<Item>() {
  @Override public void call(Item item) {
     // Do stuff
  }
})
```
