### ISSUE TITLE
Request for community comments: Better Kotlin support 

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#4701]
With an awesome I/O17 being over, one of the big announcements were official support for [Kotlin](https://blog.jetbrains.com/kotlin/2017/05/kotlin-on-android-now-official/).

Realm is already fully interoperable with Kotlin and we have a [Kotlin example here](https://github.com/realm/realm-java/tree/master/examples/kotlinExample) and [here](https://github.com/realm-demos/realm-surveys/tree/master/Kotlin) that demonstrates how it works.

But we want to make that support even better and In order to do that, we are looking for feedback on what you would most like to see changed so Realm works even better with Kotlin

We have a few ideas ourselves:

1) Add extension functions for all classes with methods that currently accept `Class<? extends RealmModel>` so `KClass` can be used directly, e.g. `realm.where(Person::class)` instead of `realm.where(Person::class.java)`.

2) **(DONE)** Detect nullability automatically in model classes. Right now you are required to use the Realm  `@Required` annotation, but we can add support for JetBrains `@NotNull` as well which is how the Kotlin bytecode indicate not-null values. Example `var name : String` instead of of `@Required var name : String`

3) **(DONE)** Annotate our public API with JSR305 annotations in a [similar way to Okio/OKHttp](https://medium.com/square-corner-blog/rolling-out-nullable-42dd823fbd89). This means that Realm will expose correctly the nullability of return values and input paramaters. For example: `val result : RealmResults<Person> = realm.where(Person::class).findAll()` instead of `val results : RealmResults<Person>? = realm.where(Person::class).findAll()`. Also being tracked here: https://github.com/realm/realm-java/issues/4643

 But we are very interested what problems _you_ are running into when using Realm from Kotlin.

**Comment by levibostian** [comment]
🎊 Kotlin!!! 🎊

When you say problems you are having with Realm using Kotlin, I do not have many problems. realm-java works really well with Kotlin at the moment. I have a few apps that are 100% Kotlin and Realm code bases. Works great. 

My vote for priority is your list item #2. Here is an example of a Realm model I create in a Kotlin app using Kotlin nullability data type in them for optional fields:

```
open class FooModel(@PrimaryKey override var realm_id: Int = 0,
                      @SerializedName("id") override var api_id: Int = 0,
                      var name: String? = null,
                      var created_at: Date = Date(),
                      var updated_at: Date = Date(),
                      var position: Int? = null,
                      var bar: BarModel? = null): RealmObject() 
```

So not needing annotations and instead using the data types of my Kotlin properties would be awesome.

**Comment by diegomontoya** [comment]
Nullability annotation would be a good start so Kotlin side knows exactly which method returns are of T? type so optional unwraps are enforced on Kotlin side. By default, if no annotation is used, the below dangerous code would compile.

```kotlin
fun Take(c: RealmCategory) {
//do stuff
}

Take(realm.where(Category.class).findFirst())
```
Take() will crash if findFirst() returns null since Kotlin injects null checks at Take().

By adding @Nullable annotation to return of RealmQuery.fiindFirst(), Kotlin would not even compile the above code and forces coder to make modifications to handle the null protection

```kotlin
fun Take(c: RealmCategory?) {
let v = c ?: return
//do stuff with v
}

**Comment by Zhuinden** [comment]
Was there a way to support a non-null initializing value (like "empty RealmResults") for a `@LinkingObjects`?

**Comment by cmelchior** [comment]
It would be relatively easy if we throw on creating queries, basically just creating an empty stub object, but if queries should be allowed it gets enormously more tricky.

**Comment by zaki50** [comment]
I think we can do something for `async`/`await` (coroutine). It's still experimental though.

**Comment by cmelchior** [comment]
@zaki50 Got anything specific in mind?

**Comment by zaki50** [comment]
@cmelchior Sorry, no.

**Comment by heinrichreimer** [comment]
Maybe async queries could use Kotlin coroutines.

**Comment by zaki50** [comment]
https://github.com/realm/realm-java/issues/4092#issuecomment-274723530

**Comment by heinrichreimer** [comment]
1. For @cmelchior's first suggestion:
    ```kotlin
    /**
     * Use [Realm.where] with [KClass]es.
     */
    fun <E : RealmModel> Realm.where(clazz: KClass<E>): RealmQuery<E> {
        return where(clazz.java)
    }
    ```
2. Group `RealmQuery` conditions:
    ```kotlin
    /**
     * Group conditions on a [RealmQuery].
     */
    fun <E : RealmModel> RealmQuery<E>.group(body: () -> Unit) {
        beginGroup()
        body()
        endGroup()
    }
    ```
3. `LiveData` support:
    ```kotlin
    /**
     * Map [RealmResults] to a [LiveData].
     */
    fun <E : RealmModel> RealmResults<E>.toLiveData(): LiveData<RealmResults<E>> {
        val liveData = MutableLiveData<RealmResults<E>>()
        addChangeListener{ results ->
            liveData.value = results
        }
        return liveData
    }

    /**
     * Map [RealmObject] to a [LiveData].
     */
    fun <E : RealmObject> E.toLiveData(): LiveData<E> {
        val liveData: MutableLiveData<E> = MutableLiveData()
        this.addChangeListener<E> {
            result -> liveData.value = result
        }
        return liveData
    }
    ```

**Comment by Zhuinden** [comment]
@heinrichreimer 

why not

/**
 * Group conditions on a [RealmQuery].
 */
fun <E : RealmModel> RealmQuery<E>.group(body: (RealmQuery<E>) -> Unit) { // <-- changed here
    beginGroup()
    body()
    endGroup()
}

I'm not sure about Kotlin generic syntax, but you get the idea.

**Comment by heinrichreimer** [comment]
@Zhuinden You're right! But it would be even better if the higher order function (`body`) passed to the group would be an extension function on the `RealmQuery` itself.

```kotlin
/**
 * Group conditions on a [RealmQuery].
 */
fun <E : RealmModel> RealmQuery<E>.group(body: RealmQuery<E>.() -> Unit) {
    beginGroup()
    body()
    endGroup()
}
```

**Comment by cmelchior** [comment]
Another Kotlin fun fact:

`Long::class.java` actually returns a Class reference to `long` not `Long`, this is really easy mistaken when writing migrations:

```
realm?.schema?.create("Person")
        ?.addField("id", Long::class.java) // Non-nullable

// Instead we should document that people need to use these instead
.addField("id", Long::class.javaObjectType) // Nullable
.addField("id", Long::class.javaPrimitiveType) // Non-nullable
```

Even better would be supporting the KClass equivalents directly:

```
.addField("id", Long::class) // Non-nullable
.addField("id", Long::class).setNullable("id") // Being nullable is hard in Kotlin
```

**Comment by heinrichreimer** [comment]
@cmelchior I wonder if there would be something like `Long?::class` in Kotlin...

**Comment by cmelchior** [comment]
There isn't: https://stackoverflow.com/questions/44473284/how-do-i-specify-a-boxed-field-can-be-nullable-in-my-realm-migration-code

**Comment by rdadkins** [comment]
@zaki50 
> Maybe async queries could use Kotlin coroutines.

@cmelchior 
> @zaki50 Got anything specific in mind?

Perhaps a Realm [context](https://github.com/Kotlin/kotlin-coroutines/blob/master/kotlin-coroutines-informal.md#coroutine-context) with a Continuation that exposes the Realm thread to work with objects "across" threads.

**Comment by zaki50** [comment]
Adding a method similar to `executeTransaction()` but it can have  return value and `this` becomes `Realm`.

```
fun <T> Realm.callTransaction(action: Realm.() -> T): T {
    val ref = AtomicReference<T>()
    executeTransaction {
        ref.set(action(it))
    }
    return ref.get()
}
```
We can write a transaction like:

```
val (group, artifact) = realm.callTransaction {
    val group = createObject(Group::class)
    group.name = "foo"

    val artifact = createObject(Artifact::class)
    artifact.name = "bar"

    Pair(group, artifact)
}

group.name == "foo"
```

```
val (group, subGroup, artifact) = realm.callTransaction {
    val group = createObject(Group::class)
    group.name = "foo"

    val group = createObject(SubGroup::class)
    group.name = "bar"

    val artifact = createObject(Artifact::class)
    artifact.name = "baz"

    Triple(group, artifact)
}

artifact.name == "baz"
```

**Comment by zaki50** [comment]
Adding static methods in `RealmObject` as extension functions to `RealmModel` like

```
fun RealmModel.deleteFromRealm() {
    RealmObject.deleteFromRealm(this)
}
```

```
@RealmClass
open class Foo(
    var name: String? = null
) : RealmModel

f: Foo = realm.where(Foo::class).findFirst()
f.deleteFromRealm()
```

**Comment by zaki50** [comment]
Supporting type-safe query.

```
fun <T : RealmModel> RealmQuery<T>.equalTo(property: KMutableProperty1<T, out String?>,
                                           value: String, case: Case = Case.SENSITIVE): RealmQuery<T> {
    return this.equalTo(property.name, value, case)
}

fun <T : RealmModel> RealmQuery<T>.equalTo(property: KMutableProperty1<T, out Int?>,
                                           value: Int): RealmQuery<T> {
    return this.equalTo(property.name, value)
}

...
```

```
@RealmClass
open class Foo(
    var name: String? = null,
    var age: Int? = null
) : RealmModel

@RealmClass
open class Bar(
    var name: String? = null,
) : RealmModel

realm.where(Foo::class).equalTo(Foo::name, "abc") // OK
realm.where(Foo::class).equalTo(Foo::name, 0) // compile error (name field is not Int
realm.where(Foo::class).equalTo(Bar::name, "abc") // compile error(Model classes are different
```

**Comment by cmelchior** [comment]
Type-safe queries are a nice idea, but right now it would require a dependency to `kotlin-reflect` which afaik pulls in ~10K extra methods.

**Comment by heinrichreimer** [comment]
Maybe it would be worth it to pull out Kotlin support in a separate dependency. Then developers could decide on their own if they need type safety.

**Comment by zaki50** [comment]
use `reified` when defining extension functions that take `Class` parameter.

```
inline fun <reified T : RealmModel> Realm.where(): RealmQuery<T> {
    return this.where(T::class.java)
}

realm.where<User>().equalTo(...)
```

**Comment by zaki50** [comment]
@cmelchior 

> Type-safe queries are a nice idea, but right now it would require a dependency to kotlin-reflect which afaik pulls in ~10K extra methods.

I was thinking so, but it seems to be working without  kotlin-reflect dependency.
I tested it with https://github.com/zaki50/GoogleRepositoryChecker/

**Comment by ericmaxwell2003** [comment]
@zaki50 @cmelchior  
> I was thinking so, but it seems to be working without kotlin-reflect dependency.

Right, it's not using reflection.  I thought this SO answer was a great explanation, helped me grok it a bit better.  https://stackoverflow.com/questions/45949584/what-does-the-reified-keyword-in-kotlin-really-do

I wonder if Type Safe builders could be used in some creative way for complex queries

    val peopleWithPuppies = realm.where<Person>() { dog { age {  lessThan(2) }}

    // given
    @RealmClass
    open class Person : RealmModel {
        @PrimaryKey var id=""
        var name =""
        var dog: Dog? = null
    }

    @RealmClass
    open class Dog : RealmModel {
        @PrimaryKey var id=""
        var name = ""
        var age = 0
    }

    // Where that query would equate to
    realm.where<Person>().lessThan("dog.age", 2)

Not much to look at, but it is type safe. :-)

**Comment by SarthakM9** [comment]
Hello Everyone, 

With latest Kotlin support from Realm v3.6.0 onwards. my equalTo(String, Integer) query is marked as ambiguous. I am passing an int primitive. Is there a neat way to do it other than explicit casting.

Thanks in advance!

**Comment by heinrichreimer** [comment]
In Kotlin `in` is a keyword, so there should be a way to call `in(String fieldName, String[] values)` with another method name. I would suggest:

```kotlin
/**
 * Map Realm's [RealmQuery.in] methods to `oneOf` to bypass using Kotlin's `in` keyword
 * as a method name.
 */
fun <E : RealmModel> RealmQuery<E>.oneOf(fieldName: String,
        values: Array<String>): RealmQuery<E> = `in`(fieldName, values)
```

**Comment by zaki50** [comment]
@heinrichreimer I  wrote the same code! https://github.com/realm/realm-java/pull/4684/files#diff-ffacb4808566a8a610dec8f6cfacc93fR72

**Comment by Zhuinden** [comment]
@heinrichreimer the future says that the function we mentioned should have `inline` :smile:
