### ISSUE TITLE
android Aapt2 error

### ISSUE THREAD

**Issue by rmasarovic** [realm/realm-java#4708]
Hi i just trying new features android studio 3 and when i try enable  on gradle.properties 
android enableAapt2=true 

then build error is in realm plugin

 Error:(34, 0) No signature of method: java.lang.String.registerTransform() is applicable for argument types: (io.realm.transformer.RealmTransformer) values: [io.realm.transformer.RealmTransformer@79c7b597]

**Comment by bmeike** [comment]
Yeah... We need to do something about that.  The Transform API on the android plugin, appears to have changed.  We'll probably want to support it.  Enqueuing on the backlog.

**Comment by cmelchior** [comment]
Realm 4.1.0 seems to work fine with Build Tools 3.0.0-rc2 and aap2 enabled. Closing

**Comment by nirvikBasnet** [comment]
This issue is still there with Build tools 3.5.1
