### ISSUE TITLE
After `login_withAccessToken`, sync client thread not responses anymore

### ISSUE THREAD

**Issue by beeender** [realm/realm-java#4711]
To reproduce this issue, just pull branch `mc/sync-client-no-responding-error`
and run test under package `io.realm.objectserver.integrationtest`

It will run two tests, `login_withAccessToken` then `expectSimpleCommit`

After `login_withAccessToken` finished, Realm can be opened successfully in `expectSimpleCommit` without any error message on the main process. However, when changes committed in the remote process, the sync client thread on the main process doesn't have any response to it.

Very much like something is not right in sync.

But if `expectALot` is enabled in `ProcessCommitTests` as well, the `expectSimpleCommit` will still fail but `expectALot` will pass. It feels like the sync client gets reset at some point.

**Comment by nhachicha** [comment]
are we sure we're using two different SyncClient thread? can we check using the `thread_id`
although the tests run on a different process, they still store files, under the same package name

**Comment by beeender** [comment]
@nhachicha I think you might be right! there should be two sync client thread in each process, but they may use the same files with the same package name!

We need to introduce a `SyncManger.init(String path)` for testing purpose.

**Comment by cmelchior** [comment]
I'm not sure it is allowed to have multiple Sync Clients. At least I believe I heard something like that from @simonask

**Comment by cmelchior** [comment]
That might be problematic since it is hidden behind `Realm.init()`, but perhaps we can automatically add the process ID to the path when in debug mode? Or something like that? https://stackoverflow.com/questions/19631894/is-there-a-way-to-get-current-process-name-in-android

**Comment by beeender** [comment]
What if user wants to use sync for multi-processes? does the user need separated dir as well?

**Comment by cmelchior** [comment]
Yes. Basically, you are treating your two processes as two separate devices. It isn't particularly efficient though as you need to round-trip to the server 😢

**Comment by beeender** [comment]
This seems to be fixed, cannot be reproduced anymore.
We can enable `login_withAccessToken()` after the recent flaky tests are solved.
