### ISSUE TITLE
Fatal signal 11 (SIGSEGV)

### ISSUE THREAD

**Issue by mywaystar** [realm/realm-java#4721]
Hi, after upgrading to Realm 3.X, we are having crash issues

We are not using Realm Sync.

What logcat tells:
A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x345ad830 in tid 27482

**Comment by Zhuinden** [comment]
Which version is Realm 3.x?

There were numerous improvements between 3.0.x and 3.1.x, and 3.1.4 added additional validation checks that were missing between 3.0.0 and 3.1.3.

**Comment by mywaystar** [comment]
This bug is in the 3.3.1 version. We had the same bug on 3.0.x and new release

**Comment by cmelchior** [comment]
@mywaystar We need more info to be able to debug this. What code are you calling when it crashes like this?

**Comment by Zhuinden** [comment]
Also, do you use encryption?

**Comment by mywaystar** [comment]
We are not using encryption.

I think that that is breaking is a list

Le 29 mai 2017 à 18:43, Gabor Varadi <notifications@github.com> a écrit :

Also, do you use encryption?

**Comment by Zhuinden** [comment]
You'll need to find the code where this native crash occurs, or at least provide log from RealmLogger

**Comment by Zhuinden** [comment]
Hello have you by chance made progress on figuring out what you do that might be causing the native crash?

**Comment by mywaystar** [comment]
We did’t have the time to figure so we want back to Realm 2.

Le 13 juin 2017 à 15:59, Gabor Varadi <notifications@github.com> a écrit :

Hello have you by chance made progress on figuring out what you do that might be causing the native crash?

**Comment by kneth** [comment]
@mywaystar Please reopen when you have an app or test which can reproduce it.
