### ISSUE TITLE
Deleting a record on a for loop?

### ISSUE THREAD

**Issue by madd86** [realm/realm-java#4723]
The idea is to send the object through retrofit and delete it from storage afterwards. Also, if you have any idea on how to make the for loop wait until the first task is done to continue, please tell me.

This is what I have:
        loadRealm();
        if (!myRealm.where(SolicitationQueue.class).findAll().isEmpty()) {
            RealmResults<SolicitationQueue> my = myRealm.where(SolicitationQueue.class).findAll();
            for (SolicitationQueue solQueue : my) {
                solQueue.deleteFromRealm();
                addSolicitation(xfile, true);
                try {
                    Thread.sleep(3000);
                } catch (InterruptedException e) {
                    e.printStackTrace();
                }
             }

Stacktrace: 

    05-29 13:16:16.722 32018-32018/com.example.ga.realm3 E/AndroidRuntime: FATAL EXCEPTION: main
                                                                       Process: com.example.ga.realm3, PID: 32018
                                                                       java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.ga.realm3/gmv.dlcity.View.Activities.MainActivity}: java.lang.IllegalStateException: Cannot modify managed objects outside of a write transaction.
                                                                           at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)
                                                                           at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2726)
                                                                           at android.app.ActivityThread.-wrap12(ActivityThread.java)

**Edit**:

Changed it to the following:

                try {
                    myRealm.executeTransaction(realm -> {
                        solQueue.deleteFromRealm();
                    });
                } finally {
                    if (myRealm != null) {
                        myRealm.close();
                    }
                }

Now I get the following stacktrace:

    05-29 13:21:48.746 4397-4397/com.example.ga.realm3 E/AndroidRuntime: FATAL EXCEPTION: main
                                                                     Process: com.example.ga.realm3, PID: 4397
                                                                     java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.ga.realm3/gmv.dlcity.View.Activities.MainActivity}: java.lang.IllegalStateException: Access to invalidated Results objects in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_Collection.cpp line 192
                                                                         at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2665)

**Comment by Zhuinden** [comment]
Have you tried doing Retrofit call on background thread synchronously and when that finishes with success **then** do the deletion?

Also you should start the transaction, **then** query, **then** delete objects.

**Comment by madd86** [comment]
Hi Zhuinden, you're always there 👍  Thanks.

I don't know how would I be able to do the deletion on the results (using rxjava).

Perhaps I can add a unique field of each row into an array, and then query that array and delete the rows with the results?

How can I query and array for multiple results?

**Comment by Zhuinden** [comment]
Unfortunately with the amount of code snippet provided I'm not sure why any of those hacks are necessary, the original sample did not include anything from Rx either after all :cry:

**Comment by madd86** [comment]
Actually I fixed it the way you said it.

First open a transaction, then query, then delete a record all of it on a background thread using rxjava. Certainly can be optimized, it's a monstrosity.

        Single.fromCallable(() -> {
            loadRealm();
            if (!myRealm.where(SolicitationQueue.class).findAll().isEmpty()) {
                try {
                    myRealm.executeTransaction(realm -> {
                        RealmResults<SolicitationQueue> my = myRealm.where(SolicitationQueue.class).findAll();
                        for (SolicitationQueue solQueue : my) {
                            mMainVariables.setType(solQueue.getType());

                            byte[] xf = solQueue.getFile();
                            File xfile = new File("");
                            if (xf.length > 0) {
                                try {
                                    ByteArrayInputStream bis = new ByteArrayInputStream(xf);
                                    ObjectInputStream ois = new ObjectInputStream(bis);
                                    File fileFromBytes = (File) ois.readObject();
                                    bis.close();
                                    ois.close();
                                    xfile = fileFromBytes;
                                } catch (ClassNotFoundException | IOException e) {
                                    e.printStackTrace();
                                }
                            }

                            addSolicitation(xfile, true);

                            solQueue.deleteFromRealm(); //TODO move this to result
                        }
                    });
                } finally {
                    if (myRealm != null) {
                        myRealm.close();
                    }
                }
            }
            return "Success";
        }).subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribe((result) -> {
                    //result
                });

**Comment by Zhuinden** [comment]
if you are using Realm 3.3.x then you should do

        loadRealm();
        myRealm.refresh(); // <-- just in case
        if (!myRealm.where(SolicitationQueue.class).findAll().isEmpty()) {

**Comment by madd86** [comment]
Thanks!
