### ISSUE TITLE
Add Realm.getDefaultConfiguration()

### ISSUE THREAD

**Issue by zaki50** [realm/realm-java#4725]
We added `Realm.getInstanceAsync()` and `DynamicRealm.getInstanceAsync()` and those always required `RealmConfiguration` ( or `SyncConfiguration`).

In order to pass default configuration to those methods, it's better to have `Realm.getDefaultConfiguration()`.

What do you think? @realm/java

**Comment by beeender** [comment]
Agree, and shall we make those APIs thread safe? They are not right now.

**Comment by cmelchior** [comment]
People could always store whatever is the default configuration in a static variable on e.g. the Application, That said, I think I have seen other requests for this + it is a minimal change for us that also mirrors the `setDefaultConfiguration()`, so it is fine with me.

They should be threadsafe though.
