### ISSUE TITLE
java.util.IllegalFormatConversionException: d != io.realm.ErrorCode error

### ISSUE THREAD

**Issue by bigparksh** [realm/realm-java#4726]
I used the latest version(3.2.0) of the realm-java.
And I found a bug on the SyncSession.java 327 line.

```java
RealmLog.debug("Session[%s]: Failed to get access token (%d)", configuration.getPath(), response.getError().getErrorCode());

```

The 2nd format of message is "%d", but 2nd argument is ErrorCode enum.
So, a exception was fire at the String.format(message, args).

I hope the bugs will be fixed as soon as possible.

Thanks.

#### Version of Realm and tooling
Realm version(s): 3.2.0

Realm sync feature enabled: yes

Android Studio version: 2.3.2

Which Android version and device: Android version 7.0, Samsung Galaxy S8

**Comment by cmelchior** [comment]
Thanks for reporting this, and yes this should be fixed as soon as possible.

**Comment by zaki50** [comment]
fixed in `releases` branch.

**Comment by bigparksh** [comment]
To the Realm team, Thanks for supporting.
I checked on the SNAPSHOT version. :)
