### ISSUE TITLE
Typo in SyncConfiguration error message

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-java#4736]
There's a typo in https://github.com/realm/realm-java/blob/master/realm/realm-library/src/objectServer/java/io/realm/SyncConfiguration.java#L831:
> SSL Verification is **disable**, server certificate provided will not be used

Additionally, the wording can probably be improved:
> SSL Verification is disabled, the provided server certificate will not be used

**Comment by cmelchior** [comment]
Fixed by #4739
