### ISSUE TITLE
Malformed JSON when accessing synced Realms

### ISSUE THREAD

**Issue by mrackwitz** [realm/realm-java#4750]
#### Goal

Several users reported about their attempts to change permissions and make use of those extended permissions. It's not yet exactly clear yet when and where the error is happening, but from the reports we've received so far it appears to be related to client-side code paths used around permission management or accessing global Realms.

https://github.com/realm/realm-mobile-platform/issues/199
https://github.com/realm/realm-mobile-platform/issues/202
https://github.com/realm/realm-mobile-platform/issues/205
https://github.com/realm/realm-java/issues/4516#issuecomment-304252816

#### Preliminary Investigation Results

In these cases the SDK is connecting with a malformed access token. The value used here must have been set to the sync client session, so that the value is passed into the header field `X-Realm-Access-Token` which is filled by the sync client implementation.

```sh
[proxy] internal error. Code undefined, status: undefined, message: SyntaxError: Unexpected token j in JSON at position 0
    at Object.parse (native)
    at ProxyService.webSocketUpgradeHandler (/usr/lib/nodejs/realm-object-server-developer/.build/src/node/services/proxy.js:104:30)
    at ProxyService.safeUpgrade (/usr/lib/nodejs/realm-object-server-developer/.build/src/node/services/proxy.js:78:12)
    at emitThree (events.js:116:13)
    at Server.emit (events.js:194:7)
    at onParserExecuteCommon (_http_server.js:411:14)
    at HTTPParser.onParserExecute (_http_server.js:379:5)
```

[Logs](https://pastebin.com/3yjvxJNV), we've received, show that the following headers are sent to the server when trying to establish a websockets connection:
```
GET /realm-object-server HTTP/1.1
Connection: Upgrade
Host: 192.168.1.70
Sec-WebSocket-Key: uGIkQ5M+ipdA8KBswVeGoQ==
Sec-WebSocket-Protocol: io.realm.protocol
Sec-WebSocket-Version: 13
Upgrade: websocket
X-Realm-Access-Token: {"authUrl":"http:\/\/192.168.1.70:9080\/auth","userToken":{"token":"","token_data":{"identity":"a163774fa72aeabff4f05cfa472cccd3","path":"","expires":1811193952,"access":["unknown"],"is_admin":true}},"realms":[]}
```

The server would expect a Base64-encoded access token concatenated with its signature, separated by a colon. (basically interpreted as `JSON.parse(tokenJson.split(':')[0])`) Trying to interpret the given value as such would cause a syntax error as seen above. The syntax error occuring which is internally caught and causes that the request is rejected with status code 400 as Bad Request which eventually prevents the client from establishing a connection.

The value given equals the internal JSON representation exclusively used by the Java SDK to represent an `ObjectServerUser` or `SyncUser`.

#### Version of Realm and tooling

This was reported for:

Server OS & Version: Ubuntu 16.04, Realm Object Server v1.7.2

Client Version: 3.3.1

Realm sync feature enabled: yes

Android Studio version: 2.3.2 (compileSdkVersion 25)

Which Android version and device: unknown

/c @bigfish24 @cmelchior @kneth

**Comment by cmelchior** [comment]
This has been fixed with Realm Java 3.3.2
