### ISSUE TITLE
Object is not part of the schema for this Realm

### ISSUE THREAD

**Issue by xiehuiyun** [realm/realm-java#4767]
![y 8 9iyf4k9bmx ton qku](https://user-images.githubusercontent.com/20488041/26960970-d947d3e0-4d0d-11e7-9c21-f1b0f9333064.png)
![a 2 v_ 9c9g6e5 a btbfa](https://user-images.githubusercontent.com/20488041/26960971-d9544e4a-4d0d-11e7-997e-215b43f636b1.png)
![juigf kompgs kua od80](https://user-images.githubusercontent.com/20488041/26960972-d955289c-4d0d-11e7-9a89-756f7ec3e01b.png)
![wb 2 e a4olox h7 ht ut](https://user-images.githubusercontent.com/20488041/26960973-d96e52ea-4d0d-11e7-83a0-a6e81c8730b3.png)
![x6 3_eijn n 4 rvp fn8](https://user-images.githubusercontent.com/20488041/26960974-d972c168-4d0d-11e7-9e0b-4cda69e10dd6.png)
i don't know why this is wrong.I have refer to official documents.

**Comment by Zhuinden** [comment]
Migrations are not automatic, and if you didn't set a default configuration that would have `deleteIfMigrationNeeded()` then you'd need to add the class to the schema manually.

It's actually super-similar to how you'd need to implement `onUpgrade()` method in `SQLiteOpenHelper` and increment schema version.

But considering you're still in development, you probably should just set `deleteIfMigrationNeeded()` on your default RealmConfiguration

**Comment by xiehuiyun** [comment]
I have add deleteIfMigrationNeeded() to my RealmConfiguration,but still wrong.
![q3 s w2_4 z p 9i w kf](https://user-images.githubusercontent.com/20488041/26964006-4333c93a-4d22-11e7-9f01-0199a8da7008.png)
I clicked two Buttons,all reported wrong.
![t ndf23 c2ym dlp3 p f](https://user-images.githubusercontent.com/20488041/26964020-5022e4a0-4d22-11e7-8211-bf9ec6c13442.png)
![krrwz 680ld p yb91 _0](https://user-images.githubusercontent.com/20488041/26964023-504c3b5c-4d22-11e7-892c-1691707a01a4.png)

**Comment by Zhuinden** [comment]
Why not create the RealmConfiguration in Application, then set it as default configuration with `Realm.setDefaultConfiguration(realmConfiguration);`?

**Comment by xiehuiyun** [comment]
I have searched many other articles ,they all do this way,before I asked you.so I do it.And you say this way,I haved try it,still wrong.Error is same.

**Comment by Zhuinden** [comment]
@xiehuiyun No, I have never seen any articles that do it the way you said. 

They always do this:

``` java
public class CustomApplication
        extends Application {
    @Override
    public void onCreate() {
        super.onCreate();
        Realm.init(this);
        RealmConfiguration realmConfiguration = new RealmConfiguration.Builder() //
                .deleteRealmIfMigrationNeeded() //
                .build();
        Realm.setDefaultConfiguration(realmConfiguration);
    }
```

Then `Realm.getDefaultInstance()` consistently

**Comment by xiehuiyun** [comment]
I try it, it still wrong.The error still it;

![Uploading 9WQBI5Y1SCD6(@_ARKJBU05.png…]()

![5 eqwuf cl l wp9qverm](https://user-images.githubusercontent.com/20488041/26968657-613f97b6-4d35-11e7-862f-b5cbd4654870.png)

**Comment by beeender** [comment]
@xiehuiyun will it work if you clean your app data cache and run it at the first time? you can try to uninstall the app and install it again.

**Comment by xiehuiyun** [comment]
i have tried it,still wrong.and the wrong is nochange

**Comment by beeender** [comment]
@xiehuiyun I saw you enabled `jack` in the gradle, which is not supported by Realm. Could you please try to disable it?

But strange thing is, it should fail in the build stage if i remembered correctly.

**Comment by xiehuiyun** [comment]
where you saw "I saw you enabled jack in the gradle"?

**Comment by xiehuiyun** [comment]
I have solved this problem.Thanks!The reason is that I added
       jackOptions {
            enabled true
        }

to my build.gradle(Module:app) file.
