### ISSUE TITLE
dataBinding and realm use @={xxx} problem

### ISSUE THREAD

**Issue by liangjianqi** [realm/realm-java#4771]
bean :  
Persion extends RealmObject

databinding  xml:
 EditText---android:text="@={persion.name}"

Activity :
          Person persion;
          persion = binding.getPersion();
          **persion.setAge = 10;**

here is problem:
java.lang.IllegalStateException
Cannot modify managed objects outside of a write transaction.

problem line in  **persion.setAge=10;**

how can i fix it?

Thanks

**Comment by bmeike** [comment]
This should be really easy to fix!  The problem is, as the exceptions says, that you are modifying the object outside of a transaction, when you assign the value 10 to one of its fields.
Please have a look at the documentation, here:
    https://realm.io/docs/java/latest/
It explains, literally in the first page, how to do this.

**Comment by liangjianqi** [comment]
Thanks for reply @bmeike  ,Maybe I did not describe it clearly.

bean :
Persion extends RealmObject

databinding xml:
EditText---android:text="@={persion.name}"

Activity :
Person persion = realm.where(Persion.class).equalTo("name","xxx").findFirst();
binding.setPersion= persion;

here's the click event (no click)：
persion = binding.getPersion();  (get the EditText value)
persion.setAge = 10;

But the problem is when I enter the EditTExt value
java.lang.IllegalStateException
Cannot modify managed objects outside of a write transaction.

**Comment by Zhuinden** [comment]
In Realm, all writes are transactional, so writes made to **managed** objects ***must be done in a transaction***.

So you can either begin/commit a new transaction for every single modified value, which seems to be massive overhead; or you can create an unmanaged copy of the object with `realm.copyFromRealm(persion)` that you'll save back later to Realm inside a transaction when for example user presses SAVE button.

**Comment by mwshubham** [comment]
You need to execute it in the transaction.

` Realm realm = Realm.getDefaultInstance();
        realm.executeTransactionAsync(realm1 -> {
            try {
                realm1.createAllFromJson(CategoryData.class, getResources().openRawResource(R.raw.category));
            } catch (IOException e) {
                e.printStackTrace();
            } catch (RealmException e) {
                e.printStackTrace();
            } catch (IllegalArgumentException e) {
                e.printStackTrace();
            }
        });`

**Comment by derohimat** [comment]
try with this code
```

realm.beginTransaction();
object.setValue("some data");
realm.copyToRealmOrUpdate(object);
realm.commitTransaction();

```
