### ISSUE TITLE
create xxRealmProxy.java error, help

### ISSUE THREAD

**Issue by tyousyuka** [realm/realm-java#4782]
注: Version 3.3.2 of Realm is now available: http://static.realm.io/downloads/java/latest
注: Processing class EstateInfoDb
注: Processing class MeterInfoDb
注: Processing class MeterSystemInfo
注: Creating DefaultRealmModule
/Users/xx/Desktop/Project/Android/YCB/app/build/generated/source/apt/debug/io/realm/EstateInfoDbRealmProxy.java:27: 错误: EstateInfoDbRealmProxy不是抽象的, 并且未覆盖RealmObjectProxy中的抽象方法realmGet$proxyState()
public class EstateInfoDbRealmProxy extends EstateInfoDb
       ^
/Users/xx/Desktop/Project/Android/YCB/app/build/generated/source/apt/debug/io/realm/EstateInfoDbRealmProxy.java:30: 错误: EstateInfoDbColumnInfo不是抽象的, 并且未覆盖ColumnInfo中的抽象方法copy(ColumnInfo,ColumnInfo)
    static final class EstateInfoDbColumnInfo extends ColumnInfo {
                 ^
/Users/xx/Desktop/Project/Android/YCB/app/build/generated/source/apt/debug/io/realm/EstateInfoDbRealmProxy.java:48: 错误: 对于ColumnInfo(没有参数), 找不到合适的构造器
        EstateInfoDbColumnInfo(String path, Table table) {
                                                         ^
    构造器 ColumnInfo.ColumnInfo(int)不适用
      (实际参数列表和形式参数列表长度不同)
    构造器 ColumnInfo.ColumnInfo(ColumnInfo,boolean)不适用
      (实际参数列表和形式参数列表长度不同)
    构造器 ColumnInfo.ColumnInfo(int,boolean)不适用
      (实际参数列表和形式参数列表长度不同)
/Users/xx/Desktop/Project/Android/YCB/app/build/generated/source/apt/debug/io/realm/EstateInfoDbRealmProxy.java:50: 错误: 找不到符号
            this._idIndex = getValidColumnIndex(path, table, "EstateInfoDb", "_id");
                            ^
  符号:   方法 getValidColumnIndex(String,Table,String,String)
  位置: 类 EstateInfoDbColumnInfo
/Users/xx/Desktop/Project/Android/YCB/app/build/generated/source/apt/debug/io/realm/EstateInfoDbRealmProxy.java:53: 错误: 找不到符号
            this.nameIndex = getValidColumnIndex(path, table, "EstateInfoDb", "name");

**Comment by zaki50** [comment]
Could you provide generated `EstateInfoDbRealmProxy.java` under `/Users/xx/Desktop/Project/Android/YCB/app/build/generated/source/apt/debug/io/realm/`?

**Comment by Zhuinden** [comment]
What version of Realm are you using?

**Comment by tyousyuka** [comment]
@zaki50 under the path generated EstateInfoDbRealmProxy.java, but have errors

**Comment by tyousyuka** [comment]
@Zhuinden 3.3.2，the day before yesterday，I use 3.3.1 it is OK，no this error！could you help？

**Comment by tyousyuka** [comment]
@realm-ci what is this problem？could you answer it？

**Comment by Zhuinden** [comment]
I'd actually just try a clean+rebuild.

**Comment by beeender** [comment]
hope `clean+rebuild` solved your problem.
