### ISSUE TITLE
Add SyncUser.allSessions()

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#4783]
Swift docs mention that they have a `SyncUser.allSession()` method. 
We should add a similar method.

They also have a `SyncUser.getSessionForUrl()` method, but that seems covered by our `SyncManager.getSession(configuration)`.

**Comment by kneth** [comment]
The Realm Cocoa implementation: https://github.com/realm/realm-cocoa/blob/master/Realm/RLMSyncUser.mm#L213
