### ISSUE TITLE
Breaking change Wishlist for 4.0

### ISSUE THREAD

**Issue by beeender** [realm/realm-java#4785]
This ticket is for general discussion of the breaking changes in the coming 4.0 release.

**Please edit the main post to add a topic with a sequence number, and we can discuss it in the comments. If the breaking change is decided to be worthy to add, then create a separated issue for it.**

1) [POSTPONED] Do not allow having both typed Realm instance and Dynamic Realm instance on the same thread. Throw an exception instead.
    This creates lots of troubles with Realm instance cache management. By disallowing it, the `RealmCache` implementation can be much simpler and give us an option to totally manage the Realm instance through Object Store.

2) [POSTPONED]  Change the behavior of `distinct()` to work against query result. See #4774

3) [DONE] ~~Replace RxJava1 with RxJava2. This issue here #3497 describes an approach where we split RxJava support into a separate library, but after trying that out in a sample project, it just feels really clunky. Doing `realm.where(Person.class).findAll().asFlowable()` is just so much nicer than doing `RxRealm.asFlowable(realm.where(Person.class).findAll())` and if one thing Kotlin has proved, then it is that small things matter~~ 😄 

4) [POSTPONED] Remove the mips so file since there is NO mips device in the market.

5) [DONE](https://github.com/realm/realm-java/pull/5314) [NH] ~~Rename [getAccessToken](https://github.com/realm/realm-java/blob/691c0f4720156187bb5cde1dfa4cc1272a0aaa11/realm/realm-library/src/objectServer/java/io/realm/SyncUser.java#L569) either rename it to reflect the fact that it's returning a `refresh_token`, or abstract the name to the end user.~~

6) [DONE](https://github.com/realm/realm-java/pull/5314) [NH] ~~Remove deprecated methods `retrieveUser` and `retrieveUserAsync` as well as the deprecated `SyncUser#Callback`~~

**Comment by cmelchior** [comment]
> Do not allow having both type Realm instance and Dynamic Realm instance on the same thread. 

I assume you mean for the same `RealmConfiguration` right? I would probably tend to agree. I'm not sure there is a single use case where having a typed Realm and a Dynamic open at the same time make sense. Although I believe we do it during a migration, that is purely an implementation detail we can probably fix.

**Comment by beeender** [comment]
> Do not allow having both type Realm instance and Dynamic Realm instance on the same thread.
Yes, for the same `RealmConfiguration`! Migration is different where we control the Realm instance internally.

**Comment by Zhuinden** [comment]
But with official Kotlin support you can get away with `RxRealm.asObservable(realmResults)` anyways because you can add extension methods that add it to the RealmResults from an external library

**Comment by cmelchior** [comment]
Yes. Extension methods are absolutely wonderful when making a modular API.

**Comment by cmelchior** [comment]
We now have a `master-4.0` branch where all these changes should go.

**Comment by Zhuinden** [comment]
It seems a bit early to create 4.0 when armeabi support isn't back yet.

**Comment by cmelchior** [comment]
We have other things we want to do in 4.0 other than upgrading the NDK, so this is mostly to allow other breaking features to continue without waiting for that.

**Comment by beeender** [comment]
> Do not allow having both typed Realm instance and Dynamic Realm instance on the same thread. Throw an exception instead.
This creates lots of troubles with Realm instance cache management. By disallowing it, the RealmCache implementation can be much simpler and give us an option to totally manage the Realm instance through Object Store.

I have revisited this change, it doesn't have too much value without breaking the semantics of `getinstance()`/`close()` 
```
// Current
Realm realm1 = Realm.getInstance();
Realm realm2 = Realm.getInstance();
realm1 == realm2; // true
realm1.close();
realm1.isClosed(); //false
realm1.close();
realm2.isClosed(); // true

// Alternative
Realm realm1 = Realm.getInstance();
Realm realm2 = Realm.getInstance();
realm1 == realm2; // false
realm1.close();
realm1.isClosed(); // true
realm2.isClosed(); // false
realm2.close();
realm2.isClosed(); // true
```

I will leave it as it is until we decide a better semantics of  Realm instances life control.

**Comment by cmelchior** [comment]
Feature set for 4.0 is complete. Moving the rest of the items to #5372. Closing
