### ISSUE TITLE
Realm Table Column does not  exist

### ISSUE THREAD

**Issue by RameshReddyKolla** [realm/realm-java#4793]
#### Goal

Implementing UXCAM to my app in which realm is used as DB.

#### Expected Results

Should show table data.

#### Actual Results
Getting table column does not exist exception

#### Steps & Code to Reproduce

When I add UXCAM related dependencies, throwing above exception.And when I remove the UXCAM dependencies, then it is working as expected.

#### Version of Realm and tooling
Realm version(s): 3.1.0

Realm sync feature enabled: no
Android Studio version: 2.3.3

Which Android version and device: nexus6 emulator

**Comment by RameshReddyKolla** [comment]
I am not getting why it's happening, please help me out

**Comment by cmelchior** [comment]
Please provide the code that isn't working. Without that, there isn't much we can do.

**Comment by RameshReddyKolla** [comment]
When I add this dependency  **compile 'com.uxcam:uxcam:2.5.7@aar'** and below maven  
**maven
{
       url 'http://sdk.uxcam.com/android/'
    }**
And if removed, no exception is throwing.

**Comment by cmelchior** [comment]
Hi @RameshReddyKolla 
Sorry, that is not enough for us to reproduce this. Can you provide a sample project that demonstrates this error?

**Comment by RameshReddyKolla** [comment]
Now problem is solved, Registered to UXCAM after realm instance is created in the code.
