### ISSUE TITLE
3.3.1 version /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 109 Kind: ACCESS_ERROR

### ISSUE THREAD

**Issue by jmonani** [realm/realm-java#4800]
#### Goal
SUPPORTED_64_BIT_ABIS: 
                                                 versionCode: 9999
                                                 BOARD: shamu
                                                 BOOTLOADER: moto-apq8084-72.01
                                                 TYPE: user
                                                 ID: NBD91P
                                                 TIME: 1477417461000
                                                 BRAND: google
                                                 TAG: Build
                                                 HARDWARE: shamu
                                                 SERIAL: ZX1G22V3KN
                                                 SUPPORTED_ABIS: [Ljava.lang.String;@41886d9
                                                 CPU_ABI: armeabi-v7a
                                                 IS_DEBUGGABLE: false
                                                 RADIO: unknown
                                                 MANUFACTURER: motorola
                                                 IS_EMULATOR: false
                                                 TAGS: release-keys
                                                 CPU_ABI2: armeabi
                                                 UNKNOWN: unknown
                                                 PERMISSIONS_REVIEW_REQUIRED: false
                                                 USER: android-build
                                                 FINGERPRINT: 
                                                 HOST: vpeb9.mtv.corp.google.com
                                                 versionName: 1.9.6_develop
                                                 PRODUCT: shamu
                                                 DISPLAY: NBD91P
                                                 MODEL: Nexus 6
                                                 DEVICE: shamu
                                                 io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/data/com.myapp/files/myDB.realm': Unsupported Realm file format version. (Unsupported Realm file format version) (/data/data/com.myapp/files/myDB.realm) in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 109 Kind: ACCESS_ERROR.
                                                     at io.realm.internal.SharedRealm.nativeGetSharedRealm(Native Method)
                                                     at io.realm.internal.SharedRealm.<init>(SharedRealm.java:187)
                                                     at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:229)
                                                     at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:204)
                                                     at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:124)
                                                     at io.realm.Realm.getDefaultInstance(Realm.java:210)

> What do you want to achieve?
Get latest Library version with complete fix/resolution of above exception.
#### Expected Results
Crash in Realm Android 3.3.1 version of library. Works as expected in version 3.0.0.

> ?

#### Actual Results
Crash while app open or resume with newer version of library (3.3.1).

>  E.g. full stack trace with exception
io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/data/com.myapp/files/myDB.realm': Unsupported Realm file format version. (Unsupported Realm file format version) (/data/data/com.myapp/files/myDB.realm) in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 109 Kind: ACCESS_ERROR.
                                                     at io.realm.internal.SharedRealm.nativeGetSharedRealm(Native Method)
                                                     at io.realm.internal.SharedRealm.<init>(SharedRealm.java:187)
                                                     at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:229)
                                                     at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:204)
                                                     at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:124)
                                                     at io.realm.Realm.getDefaultInstance(Realm.java:210)

#### Steps & Code to Reproduce

> Describe your current debugging efforts.

#### Code Sample

```java

 private Realm getDefalutRealm() {

        try {
            mRealm = Realm.getDefaultInstance();
        } catch (RealmMigrationNeededException me) {
            LogUtil.e("RealmDBHelper", me.getMessage());
            if(!Realm.getDefaultInstance().isClosed())
                Realm.getDefaultInstance().close();
            Realm.deleteRealm(mConfig);
            mRealm = Realm.getDefaultInstance();
        }
        return mRealm;
    }
> Your code here. Bigger samples should ideally be as separate Android Studio project, 
> in gists/repositories or privately at help@realm.io)

```

#### Version of Realm and tooling
Realm version(s): ?
3.3.1
Realm sync feature enabled: yes/no
no
Android Studio version: ?
2.3.3
Which Android version and device: ?
7.0.0

**Comment by Zhuinden** [comment]
if(!Realm.getDefaultInstance().isClosed()) // <-- opens a new unclosable local Realm instance
                Realm.getDefaultInstance().close(); // <-- shouldn't run unless there are 0 local Realm instances on any threads, therefore 0 global instances

Have you considered using `RealmConfiguration.Builder().deleteIfMigrationNeeded()` instead?

**Comment by jmonani** [comment]
Yes, i am using deleteIfMigrationNeeded, this block is if there is RealmMigrationNeededException. Also rewriting migration as well, so hopefully there wont be RealmMigrationNeededException. Though this io.realm.exceptions.RealmFileException is when app opens or resumes having new library 3.3.1 version over older version of sdk. Please let's know when it is going to be fixed.

**Comment by beeender** [comment]
@jmonani 

> Though this io.realm.exceptions.RealmFileException is when app opens or resumes having new library 3.3.1 version over older version of sdk. 

Which version was the **older version of sdk**?

**Comment by jmonani** [comment]
earlier one is 3.0.0.

**Comment by beeender** [comment]
@jmonani do you use encryption? can you please share your code of building the `RealmConfiguration`?

**Comment by jmonani** [comment]
mConfig = new RealmConfiguration.Builder()
                                        .schemaVersion(SCHEMA_VERSION)
                                        .name("myDB.realm")
                                        .deleteRealmIfMigrationNeeded()
                                        .build();

**Comment by beeender** [comment]
@jmonani I tried to make a testing project but no luck to reproduce it.

1. Can you always reproduce it?
2. Can you reproduce it on other devices/emulators?
3. can you share you apk (both with with 3.0.0 and 3.3.1) with us so i can try it? to help@realm.io if you want to share it privately.

**Comment by jmonani** [comment]
Yes, it's is always reproducible as per steps i mentioned earlier and devices I've tried so far. I'll share more details for the earlier version of sdk.

Thanks
Jignesh

**Comment by jmonani** [comment]
sent details, please look into the crash and let me know when new version is available. Thanks.

**Comment by beeender** [comment]
To be clear, correct me if I am wrong

The issue happened when
a. The APK was using a previous Realm release (< 1.0)
b. Update the APK with a Realm (3.3.1). 

Right?

1. if that is the case, what version of Realm were you using for step a)? I can try build some test based on this information. 
2. Since you cannot share the apk, would you please make a small sample project to reproduce the issue? That would be very helpful for us to locate the issue. Thanks!

**Comment by kneth** [comment]
@jmonani Did you have a chance to create a small project which reproduces the issue?

**Comment by jmonani** [comment]
Sorry i missed to update. i am travelling currently with limited coverages,
will take a look again when back. i noticed similar crashes reported on
same cpp file. Wonder if its not good enough detail to troubleshoot.

Thanks.
Jignesh

**Comment by kneth** [comment]
@jmonani I'll leave the issue open, and when you get home, please update with details about the similar crashes.

**Comment by bmeike** [comment]
Hey @jmonani,
  Where are we on this?  Is it still a problem?  Have you had any luck in reproducing it?

-blake

**Comment by bmeike** [comment]
@jmonani 
We haven't heard from you in a while, and we have had no luck reproducing the problem.  I'm going to close this issue.
Please, by all means, if you encounter the problem again or get more information about it, open a new issue.  We'd be more than happy to work it with you.
-blake

**Comment by jmonani** [comment]
Hello,

I am working on redesign of app with new feature and will update once we
have it ready.

Thanks much for following up.

Jignesh
