### ISSUE TITLE
IllegalArgumentException: Could not parse user json

### ISSUE THREAD

**Issue by Maxxan** [realm/realm-java#4822]
#### Goal

I'm trying to create a synced realm database

#### Expected Results

That the database should not crash even if it failed to login

#### Actual Results

SyncUser.currentUser throws an exception, crashing the whole application and it's not possible to delete that invalid user.
The error is something like:
Caused by:
```
 java.lang.IllegalArgumentException: Could not parse user json: eyJpZGVudGl0eSI6IjQ0ZWU5Y2ZlNGMwNDc5YTVmZDU4MWMwOTQ5OTI5Y2YxIiwiZXhwaXJlcyI6MTgxMzM1NDkzNCwiYXBwX2lkIjoiY29tLmxvc3RwaXhlbHMuZmllbGRzZXJ2aWNlIiwiYWNjZXNzIjpbInJlZnJlc2giXSwiaXNfYWRtaW4iOmZhbHNlLCJzYWx0IjowLjY1OTEwMjg3OTYyMzExNTN9:P1KRa4IykFyVWdd9CUt84jytP7r+O3X8P7bgwtXjJBrgbwLtf0Fz8+ezfKP01G5mjumsjx9bc4ZCY+JkaEOjSu1U+kDck0Oi7fOgvhpf2cpPjPryrEMF/XXkNq8EBzUfumdNRsxoBEJhNsGcOui/UO8kEI1y0qlxUdjVwEupqv62BPlz4AzGCC27MWsKUACDLJUekC/pdMTRYcrWEVTfmZXZHrm90QtXwmJVSUKePmwWhE5xTvDQKw49bT1FJzX45RhRZez3pP2SAYpwNH8IVpnMqN1M4+OruwTt//eRwO8VQdPJKgXLk3T2Cx1AWnjL+AkuW0dcKBmbjJt3Cs3v1g==
                                                                                 at io.realm.SyncUser.fromJson(SyncUser.java:157)
                                                                                 at io.realm.RealmFileUserStore.toSyncUserOrNull(RealmFileUserStore.java:84)
                                                                                 at io.realm.RealmFileUserStore.getCurrent(RealmFileUserStore.java:44)
                                                                                 at io.realm.SyncUser.currentUser(SyncUser.java:110)

```
#### Steps & Code to Reproduce

I first start with an offline realm database. Then I create a synced user with this code
```
GoogleSignInResult result = Auth.GoogleSignInApi.getSignInResultFromIntent(data);
        if (result.isSuccess()) {
            GoogleSignInAccount acct = result.getSignInAccount();
            String token = acct.getIdToken();
            SyncCredentials myCredentials = SyncCredentials.google(token);
            String authURL = serverUrl + "/auth";
            return SyncUser.login(myCredentials, authURL);
        }
```

I then merge the offline and online database

```
if (user != null && user.isValid()) {
            RealmConfiguration configuration = getSyncConfig(user);
            Realm offlineRealm = Realm.getDefaultInstance();
            Realm.setDefaultConfiguration(configuration);
            Realm onlineRealm = Realm.getDefaultInstance();

            // Merge
            try {
                onlineRealm.refresh();
                // Code for merging offline database to online database
            } finally {
                offlineRealm.close();
                onlineRealm.close();
            }
        }
```

If an exception occurs I catch it and logout that user
```
SyncUser user = SyncUser.currentUser();
        if (user != null && user.isValid()) {
            user.logout();
        }
```

Now if an exception occur, then next time the app is started SyncUser.currentUser() will throw the above exception and it's not possible to use the app until the data of the app is cleared.

A local Realm object is a member of the activity and is closed after login/merge is done and set to default instance again to now point to correct realm database.

Is it possible to clear the invalid user without deleting all data? What can cause this to happen? Encryption is not applied to the databases. The realm server is running locally on my Mac. I can't reproduce the problem every time, but 1 out of 3 times when I try, I get this problem and needs to clear app data to be able to use the app again.

#### Version of Realm and tooling
Realm version(s): 3.3.2

Realm sync feature enabled: yes

Android Studio version: 2.3

Which Android version and device: Emulator, android API 24

**Comment by nhachicha** [comment]
Hi @Maxxan 

- which version of ROS are you using?

- does the crash happen, when using a user with `SyncCredentials.usernamePassword`?

**Comment by azamatsulaiman** [comment]
same error for me, I used `SyncCredentials.usernamePassword`

**Comment by Maxxan** [comment]
Hi!
ROS? Is that the same as Realm Mobile Platform? If so, then it's version 1.7.4
If an exception is thrown in the merging code due to an error there, I get the error next time I start the app. So the crash is not in realm the first time. So it's strange that I can call SyncUser.currentUser() and logout the user (due to the error), but next time when I call SyncUser.currentUser() it throws that previous exception.

```
// Merge
            try {
                onlineRealm.refresh();
                // If an exception is thrown here, then SyncUser.currentUser will crash next time I use the app 
            } finally {
                offlineRealm.close();
                onlineRealm.close();
            }
```

**Comment by Maxxan** [comment]
Would it help with an APK file that reproduces the problem? (I tried to make a small sample code, but I couldn't reproduce it. But with the original APK I can reproduce it.

**Comment by nhachicha** [comment]
@Maxxan yes the APK  would be helpful to try to reproduce

**Comment by Maxxan** [comment]
Here is a link to the APK. [https://drive.google.com/open?id=0B5lZ90EH9U_SejVMbHJaZk1CRjA](url)

It uses a local server in Mac. So start the emulator, Android API 24 and the local Realm server. 
Enable Google API login with this ID: 529208223328-7k8nd1b933o5f09hucn49jsgrdagnmju.apps.googleusercontent.com
Login to a Google account on the emulator.
Install the APK on the emulator. 
Start the app (Ministry Assistant) and tap next and on second page, switch to enable syncing and tap "Done". Now you should get an account picker dialog, so select your account.
Wait for it to sync and fail. (There is a debug log message saying "Creating an exception to reproduce the bug")
Kill the app and start it again. Now it will hopefully give the above error.

**Comment by nhachicha** [comment]
Hi @Maxxan thanks for sending the APK, 
however, it's stripped from all your classes:
```
06-23 00:45:20.579  1623  1623 E AndroidRuntime: Caused by: java.lang.ClassNotFoundException: Didn't find class "com.lostpixels.fieldservice.MinistryAssistant" on path: DexPathList[[zip file "/data/app/com.lostpixels.fieldservice-1/base.apk"],nativeLibraryDirectories=[/data/app/com.lostpixels.fieldservice-1/lib/x86, /data/app/com.lostpixels.fieldservice-1/base.apk!/lib/x86, /system/lib, /vendor/lib]]
06-23 00:45:20.579  1623  1623 E AndroidRuntime: 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
06-23 00:45:20.579  1623  1623 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:380)
06-23 00:45:20.579  1623  1623 E AndroidRuntime: 	at java.lang.ClassLoader.loadClass(ClassLoader.java:312)
06-23 00:45:20.579  1623  1623 E AndroidRuntime: 	at android.app.Instrumentation.newApplication(Instrumentation.java:992)
06-23 00:45:20.579  1623  1623 E AndroidRuntime: 	at android.app.LoadedApk.makeApplication(LoadedApk.java:796)
```

Using _classyshark_ to inspect the APK
<img width="861" alt="screen shot 2017-06-23 at 05 44 47" src="https://user-images.githubusercontent.com/1793238/27467107-70d1cd64-57d7-11e7-9232-1c39d1c88e88.png">

you can share privately the APK, by sending it to help@realm.io

Cheers

**Comment by nhachicha** [comment]
also this
```
java.lang.IllegalArgumentException: Could not parse user json: eyJpZGVudGl0eSI6IjQ0ZWU5Y2ZlNGMwNDc5YTVmZDU4MWMwOTQ5OTI5Y2YxIiwiZXhwaXJlcyI6MTgxMzM1NDkzNCwiYXBwX2lkIjoiY29tLmxvc3RwaXhlbHMuZmllbGRzZXJ2aWNlIiwiYWNjZXNzIjpbInJlZnJlc2giXSwiaXNfYWRtaW4iOmZhbHNlLCJzYWx0IjowLjY1OTEwMjg3OTYyMzExNTN9:P1KRa4IykFyVWdd9CUt84jytP7r+O3X8P7bgwtXjJBrgbwLtf0Fz8+ezfKP01G5mjumsjx9bc4ZCY+JkaEOjSu1U+kDck0Oi7fOgvhpf2cpPjPryrEMF/XXkNq8EBzUfumdNRsxoBEJhNsGcOui/UO8kEI1y0qlxUdjVwEupqv62BPlz4AzGCC27MWsKUACDLJUekC/pdMTRYcrWEVTfmZXZHrm90QtXwmJVSUKePmwWhE5xTvDQKw49bT1FJzX45RhRZez3pP2SAYpwNH8IVpnMqN1M4+OruwTt//eRwO8VQdPJKgXLk3T2Cx1AWnjL+AkuW0dcKBmbjJt3Cs3v1g==
```

doesn't look like the complete JSON payload. It should log something like

```
{"authUrl":"http:\/\/127.0.0.1:9080\/auth","userToken":{"token":"eyJpZGVudGl0eSI6IjY4NTVlMWNmYmZiZDg3MjI3YzBmNDNjYjQ2MDRkZjVmIiwiZXhwaXJlcyI6MTgxMzU1MDg4MywiYXBwX2lkIjoiaW8ucmVhbG0udGVzdCIsImFjY2VzcyI6WyJyZWZyZXNoIl0sImlzX2FkbWluIjpmYWxzZSwic2FsdCI6MC44NzY4MDE5NTMyOTk4OTIzfQ==:lYhwWjd0nGHTHR45OjFiws\/PM24rEuF6OCYVsOPoC3oH4kbSIrpAPb5d67BveD7l3J8QI1UOFNfK2OS8jUkLDAn39Z4qos3pxHWXk\/Q\/hNV43XVyaoPBRDJQ1Vrj4fEKOX7NPnOoHUBfQN9iT3\/vHqYIxJ8UydVJntPYE8ySZWVt2UA9KtYgAoGtdCR4c3WRfiHYNzV54teZqlLa2q\/sXE2OMU2IAeAmQcYHHEir0coGGieydh2dUX7FQ1wPKkcE30v5+GxriXX5+wAAJWuNcavdGCLzijHmTB1XOhASa58wCWdMIU6\/kIXexO4iNleHevDC7IgfzqUclb0C+mf5sg==","token_data":{"identity":"6855e1cfbfbd87227c0f43cb4604df5f","path":"","expires":1813550883,"access":["unknown"],"is_admin":false}},"realms":[]}
```

what we see in your case is only the `token`, which is also surprisingly mal-encoded in B64
try it [here](https://www.freeformatter.com/base64-encoder.html)

Did you remove elements from the log?

@azamatsulaiman do you have the log? or APK as well to reproduce?

**Comment by Maxxan** [comment]
@nhachicha I tried to disable all proguard and minify and uploaded it again.
[https://drive.google.com/file/d/0B5lZ90EH9U_SZnU1Q2dXNG9jQ2s/view?usp=sharing](url)

Another thing that is strange:  If I have the emulator and server running on my computer and puts it to sleep, next time when I try to sign in to the server, it says that the credentials are invalid. But if I restarts the emulator and try again, it works just fine. But that's just a minor problem..

**Comment by nhachicha** [comment]
@Maxxan Thanks, I'm able to reproduce your crash.

Somehow, like I mentioned, when the user is logged in what is persisted is not the entire `SyncUser` JSON example 
```
{"authUrl":"http:\/\/192.168.1.65:9080\/auth","userToken":{"token":"eyJpZGVudGl0eSI6ImZiZjllYzJlYWFmNjFlMzA5YzAwNmEwYzc0MTRiYjk3IiwiZXhwaXJlcyI6MTgxMzU4NjcxMywiYXBwX2lkIjoiaW8ucmVhbG0ucmVhbG10YXNrcyIsImFjY2VzcyI6WyJyZWZyZXNoIl0sImlzX2FkbWluIjpmYWxzZSwic2FsdCI6MC41MDY1MzIyNDQ1NjcyOTA0fQ==:UtaxTPPQcaBzaALTSkDqFKeLkaNKFqt4xiguwM5iKYxQe2dCkd16EdOEKPm7KEKUIMM+LQUHLOWw7eQMVcKrjoGaLfJk0G8jkkmGe50jfdlVuuqfS6Veru1XXqhp+9PKTMyBdTxbG5uxGrDJxafpq3RN807ZVdw3fdTr0P9dCqLyLmiJV9nyXWaRJP8B6LSpbqB4OHVNFEl6McbSYdIB9ww+n3Jh0dHZ4d7H0H3Ld8LFkkIz\/Qx02bf4UkOTaJt2s73hvfmKQK2mU5ovii+qBq6BOOmukMKqN3Kd5dDUvH1WWECQlTHxSpxR4MggMNf4LIMiyX2PLJ4IGAtRRGEjIg==","token_data":{"identity":"fbf9ec2eaaf61e309c006a0c7414bb97","path":"","expires":1813586713,"access":["unknown"],"is_admin":false}},"realms":[]}
```

but only the `token`, which is not a valid (expected) JSON that will parse to the current user.

Can you please try to put a breakpoint inside `RealmFileUserStore` at the `put` method.
this first should persist the correct JSON structure into disk

<img width="681" alt="screen shot 2017-06-23 at 15 17 11" src="https://user-images.githubusercontent.com/1793238/27486237-e2aeaefc-5827-11e7-8a6c-4c11f7c55a89.png">

What do you see as the value of `userJson` ?

**Comment by Maxxan** [comment]
Good that you can reproduce it.

If it set a breakpoint there, userJson looks like:
`{"authUrl":"http:\/\/10.0.2.2:9080\/auth","userToken":{"token":"eyJpZGVudGl0eSI6Ijg4YTQ4ZWM3M2U4NjMwMmY1MWY0NjBkMmEzYzQ2MGNhIiwiZXhwaXJlcyI6MTgxMzYxMzk4NSwiYXBwX2lkIjoiY29tLmxvc3RwaXhlbHMuZmllbGRzZXJ2aWNlIiwiYWNjZXNzIjpbInJlZnJlc2giXSwiaXNfYWRtaW4iOmZhbHNlLCJzYWx0IjowLjk0MTQ0MjM1NDU1MjkxNTR9:hHjXz5QFUkuNR3V\/HV31Wm25ryYrLwxCDGuABhc9UuP+31Ul1tzeHSDwGcYq4L4Z5iI5VCKOFvbq322OkYhOSbyhs5cZqNOukIDcCeT3t28mTrZuW7MHM5ZYz8YjyPJdqrq8Smo1MHiTK1\/l+2GDbYCUXxkdB1ZEaIc21UTjC4leiXelUHspFldodpx4szUDB4cqoVr78Lj3wNp3fzC0Sc9RY+la96Nk\/GtXHeXmt9aHqKyl05a3RNY\/4WyycfJ5NffMb4SRi1yKDrY7RiFQirQGwlkGkWnV5R1G62WjUC0EEJZmKH75yFwomcehNnANJgIDCG77R2jz1yP05AL9qQ==","token_data":{"identity":"88a48ec73e86302f51f460d2a3c460ca","path":"","expires":1813613985,"access":["unknown"],"is_admin":false}},"realms":[]}`
which looks correct.

**Comment by Maxxan** [comment]
I found out that I don't need to close the app to reproduce the problem, I only need to close the connection to the realm database and open it again. The sequence is:
1. The activity starts for the first time, call Realm.getDefaultInstance() to get the offline database and set a member variable in that activity class.
2. The user want to enable syncing, login the user.
3. Open a connection to both the offline and online databases and merge the data.
4. Close the connections made in 4. Here getCurrent still returns correct json (null since we're logged out due to exception)
5. When the login thread is done, in the main thread, close the connection to the offline database created in 1.
6. Set the activity realm member variable connection to Realm.getDefaultInstance. Now getCurrent returns only the token, not null/valid json as it should.

**Comment by Maxxan** [comment]
I know what the problem is now. Here is a small project that reproduces the problem.
[RealmTest.zip](https://github.com/realm/realm-java/files/1099515/RealmTest.zip)

**Comment by nhachicha** [comment]
@Maxxan there's a PR now trying to address some of the issues https://github.com/realm/realm-java/pull/4862

in the mean time you can fix your example by not reusing the default configuration `Realm.getDefaultInstance()` in the `onPostExecute` since the user was logged out previously, this means the `SyncConfiguration` can not be reused. You should log in the user again to obtain a new `token`

**Comment by Maxxan** [comment]
Thanks for the information!
