### ISSUE TITLE
Race condition between commitTransaction returning and values being available on UI thread

### ISSUE THREAD

**Issue by tmtrademarked** [realm/realm-java#4826]
#### Goal

There seems to be a race condition when propagating data between realms on different threads. Specifically, after calling commitTransaction on a background thread, the written data is not immediately available on the UI thread. See the code sample for more details.

#### Expected Results

I would expect that after commitTransaction returns, the data is written to the current Realm *and* reflected to other Realms. That does not appear to be the case.

#### Actual Results

When querying on the UI thread after posting back to a Handler, the data does not appear to be present.

#### Code Sample

Unfortunately, it's slightly hard to create a simple code sample which reliably produces the problem. But I've attempted to describe it as concisely as possible here.

```java

// On UiThread:
service.doSomeWork(new Callback() {
  void findObject() {
    try (Realm realm = Realm.getDefaultInstance()) {
      MyObject obj = realm.where(MyObject.class).equals("id", mObjId).findFirst();
      // Assert obj is not null.
    }
  }
}

// On background thread:
try (Realm realm = Realm.getDefaultInstance()) {
  // Call server, receive MyObject obj in json.
  realm.beginTransaction();
  realm.createOrUpdateObjectFromJson(MyObject.class, json);
  realm.commitTransaction();
}
mHandler.post(new Runnable() {
  public void run() {
    callback.findObject();
  }
}

```

This works most of the time - but occasionally, will crash with a null object in findObject.  If I replace the call to "mHandler.post" with "mHandler.postDelayed" with a tiny delay (2ms seems to work), everything works as expected reliably. As best I can tell here, there appears to be a slight delay between when commitTransaction returns and when the message synchronizing the UI thread's Realm instance is actually sent/enqueued with the main thread handler.

In this case, it's slightly awkward to solve the problem by using a RealmListener, because the object we're waiting for doesn't exist in Realm yet. We could use a query with expected size 1 instead of returning the object directly, but that's not as clean to work with.

#### Version of Realm and tooling
Realm version(s): 3.3.1

Realm sync feature enabled: no

Android Studio version: 2.3.3

Which Android version and device: Any tested (seen on multiple devices/API levels)

**Comment by Zhuinden** [comment]
That's because UI thread queries are evaluated asynchronously by default (especially if you use `async` query api), and there is no guarantee that they are immediately available after one event loop later.

But you can define a `RealmResults<MyObject> results = realm.where(MyObject.class).equalTo("id", id).findAllAsync();` and if you add a RealmChangeListener to it, it'll be called when the item is inserted into Realm

**Comment by beeender** [comment]
Also, the Realm instance on UI needs a notification to be refreshed when the BG changes data. The notification is delivered though handler in another daemon thread. So it is no guarantee that Realm change notification will be delivered first before your own handler message.

**Comment by kneth** [comment]
@tmtrademarked Did the two comments above answer your questions?

**Comment by tmtrademarked** [comment]
I think so, unfortunately - it sounds like there's currently no way to guarantee delivery in this case, so you have to use RealmListeners.

As a question, though, would it be at all possible to change the semantics of "commitTransaction" to not return until the refresh notification has been dispatched to the event handler? That would allow use cases like mine more easily. (I haven't dug into the guts of the Realm implementation, but just wanted to offer a suggestion here)

**Comment by beeender** [comment]
> would it be at all possible to change the semantics of "commitTransaction" to not return until the refresh notification has been dispatched to the event handler? 

I am sorry but I don't think that is the right thing to do.

If you don't want to use the `RealmChangeListener`, you can call `Realm.refresh()` on the UI thread which will refresh everything to the latest version. Please notice, when you call the `refresh()`, every live query you made on the UI thread will be re-executed on UI thread.

So, the suggestion is, using the listeners if it is possible since Realm will try to do all the work on the background thread.

**Comment by cmelchior** [comment]
The above is correct. If you want to control exactly when the UI thread is updated, using `Realm.refresh()` when you receive your own notification is the only option, but it comes at the cost of running all queries on the UI thread.

If that trade-off is worth it, is up to you. In most cases Realm queries can be run effectively on the UI thread, but there are edge cases which is also why we recommend using change listeners as much as possible.

Closing

**Comment by tmtrademarked** [comment]
Quick question here - I'm working on updating our implementation to use a query and listeners instead. But I was wondering if there was a way to help make this a bit simpler for users by introducing something like an Optional for single Realm objects.

In our original use case, we were querying for a single object. If that object doesn't exist on disk, we can't listen for it (since the return from findFirst is null, meaning you can't register a listener on it). Changing this code to use a RealmResults (and use findAll) works, but it loses the semantics we had originally - the code now thinks it can take an arbitrary size list, which isn't ideal.

It would be a tiny bit simpler if there was a way to get something from findFirst like "Optional<T>", and register a listener on the optional. Would that be something that would fit with the Realm APIs?

**Comment by Zhuinden** [comment]
A single-element subscription that could be either `value` or `null`, but could register a query and change listener just like a `Results`, except it could have only one or zero element.

It'd be nice but knowing how most things as of late are just a mirror to the OS, personally I think it's unlikely. For this use-case, I tend to do `RealmResults` where I query specifically for the primary key field value.

**Comment by tmtrademarked** [comment]
Yeah, that's what I changed our code to use - it's just not ideal, since we have to document that the list is expected to have size 0 or 1 (and it's not obvious to readers who don't notice that comment). The `RealmOptional` or similar would be a more obvious semantic.

**Comment by Zhuinden** [comment]
@tmtrademarked You probably should! I'll vote with a "yeah that would make `findFirstAsync()` and `findFirst()` semantics much more obvious"

**Comment by tmtrademarked** [comment]
Done - thanks, @Zhuinden !
