### ISSUE TITLE
Expose User Lookup API

### ISSUE THREAD

**Issue by mrackwitz** [realm/realm-java#4828]
### Goal

Our users need a way to look up the random generated user IDs to connect those with their own user models of existing backends and can interact with user-specific Realms. We've an API which covers a minimum useful solution to achieve a user lookup. As this is subject to change, it would be desirable to wrap this API endpoint, so that our users can rely on a stable API and we can change the implementation details.

#### `SyncUser SyncUser.retrieveUser(String provider, String providerId)`

Retrieve another user by the provider identifier of one of their accounts. This is done synchronously and involves the network, so calling this method on the Android UI thread will always crash.
This user needs admin privilege in order to retrieve another user.

#### `RealmAsyncTask SyncUser.retrieveUserAsync(String provider, String providerId, SyncUser.Callback callback)`

Retrieve another user asynchronously by the provider identifier of one of their accounts.
This user needs admin privilege in order to retrieve another user.

**Comment by cmelchior** [comment]
@mrackwitz Do you have a design doc for the end point somewhere?
Specifically, what is the `providerId`?

**Comment by mrackwitz** [comment]
I linked this from the product issue. 
The `providerId` would be the email / username for the password provider or the Facebook user ID for Facebook.
