### ISSUE TITLE
Records missing while using copyToRealmOrUpdate

### ISSUE THREAD

**Issue by prvnmit** [realm/realm-java#4835]
#### Goal

> What do you want to achieve?

Delete all existing records from a realm table and insert a set of new records

#### Expected Results

> The table should contain the set of new records

#### Actual Results

>  Out of the 73 new records being inserted, one get missed and only 72 gets inserted

#### Steps & Code to Reproduce

> Screen snap of a debug session - https://ibb.co/jkbKck

#### Code Sample

```java
            realm.executeTransaction(new Realm.Transaction() {
                 @Override
                 public void execute(Realm realm) {
                     RealmResults<AppRecord> appResults = realm.where(AppRecord.class).findAll();
                     appResults.deleteAllFromRealm();

                     realm.copyToRealmOrUpdate(appRecords); // Size of appRecords is 73

                     RealmResults<AppRecord> ar1 = realm.where(AppRecord.class).findAll();
                     Log.i("HELLO", "initializeApps: " + ar1); // Size of ar1 is only 72
                 }
            });
```

#### Version of Realm and tooling
Realm version(s): 3.1.3

Android Studio version: 2.3.3

Which Android version and device:  Android 7.1.1 & LeEco Le 2

**Comment by Zhuinden** [comment]
If their primary key matches then they can  overwrite each other.

**Comment by prvnmit** [comment]
Stupid me, I never expected my data to have dupes, but it turns out that it has
Closing this out, thank you !
