### ISSUE TITLE
Support android gradle plugin 3.0.0

### ISSUE THREAD

**Issue by andrewpmoore** [realm/realm-java#4838]
Original title: <TableName> is not part of the schema for this realm when using gradle:3.0.0-alpha4

I'm using the latest version of realm (3.4.0) but I've also tried with an older project on 2.x

If I create a build with com.android.tools.build:gradle:2.4.0-alpha7 the app builds fine and runs, but as soon as I upgrade to com.android.tools.build:gradle:3.0.0-alpha4 the app still builds fine, but as the app crashes straight away with 

<TableName> is not part of the schema for this realm.

As far as config of the realm I'm using the following

`RealmInspectorModulesProvider.builder(this).withFolder(getCacheDir()).withMetaTables().withDescendingOrder().withLimit(1000).databaseNamePattern(Pattern.compile(".+\\.realm")).build();
Realm.init(this);
RealmConfiguration config = new RealmConfiguration.Builder().deleteRealmIfMigrationNeeded().build();
Realm.setDefaultConfiguration(config);`

Is there anything that needs to change to get new gradle builds working?

**Comment by beeender** [comment]
hi, the android plugin 3.0 support is still in progress, see https://github.com/realm/realm-java/pull/4663

**Comment by andrewpmoore** [comment]
Thanks for the update on that, I knew there'd been some issues, but hadn't seen this one specifically mentioned, just didn't want it to not be known about :)

**Comment by beeender** [comment]
No problem! I will keep this open for tracking it! thanks!

**Comment by zaki50** [comment]
@andrewpmoore I'd like to test the project with agp_3.0 branch.

Could you provide a sample project that reproduce this issue?

**Comment by cmelchior** [comment]
3.0.0 support was added in https://github.com/realm/realm-java/pull/4663. Currently, we are compatible with alpha4 with alpha5 support coming here: #4899.

Closing
