### ISSUE TITLE
impossible to get progress notification with readOnly database at the first time

### ISSUE THREAD

**Issue by idok595** [realm/realm-java#4845]
when trying to open readOnly realm at the first time it is require to waitForInitialRemoteData(), the only way to work with such config is to getInstanseAsync, when i am trying to work with this method and adding Progress lisetener i am getting error "Cannot register a progress listener before a session is created. A session will be created after the first call to Realm.getInstance()" even if i do that after call to getInstanseAsync, if i will call getInstanse() i will block the ui thread so i will never be able to add the progress notification.

Realm Version: 3.4.0

**Comment by cmelchior** [comment]
Yes, this is tied to the fact that currently a Session is tied to the Realm lifecycle. We want to decouple this for other reasons, in which case this will be possible.

**Comment by idok595** [comment]
this is a design bug, the first time of downloading the database is the must important one, this is the only case that the app must to delay the user.

**Comment by kneth** [comment]
@idok595 It is currently labeled "Blocked" as we need to coordinate with the other SDKs.

**Comment by cmelchior** [comment]
This has been fixed in Realm Java 6.0.2
