### ISSUE TITLE
Crash: mmap() with size 0: offset 0

### ISSUE THREAD

**Issue by diegomontoya** [realm/realm-java#4848]
```java
Non-fatal Exception: io.realm.exceptions.RealmError: Unrecoverable error. mmap() failed: Invalid argumentsize: 0offset: 0 in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 281
       at io.realm.internal.SharedRealm.nativeCommitTransaction(SharedRealm.java)
       at io.realm.internal.SharedRealm.commitTransaction(SharedRealm.java:260)
       at io.realm.BaseRealm.commitTransaction(BaseRealm.java:359)
       at io.realm.Realm.commitTransaction(Realm.java:130)
       at io.realm.Realm.executeTransaction(Realm.java:1465)
```

The debug trace is a little wonky but we can say it is either caused by a .deleteFromRealm() call or .copyToRealmOrUpdate() small transaction.  The size value of 0 and offset 0 looks like a realm core bug.

That's all the details we have right now. Will appened if the trace becomes clearer. This happened on 

1) Android 7.0 with no disk or memory pressure (LGLS992)
2) Realm 3.3.2
3) No encryption. Db on internal disk.

**Comment by beeender** [comment]
dup #5199 to this

**Comment by cmelchior** [comment]
Closing due to being outdated. The underlying native code has changed quite a bit. If this is still a problem with newer versions of Realm feel free to reopen this issue.
