### ISSUE TITLE
How to update database real time after Add or Insert ?

### ISSUE THREAD

**Issue by trinhvanminh2009** [realm/realm-java#4855]
I have to turn off my dialog to see new data after add.
Check my image attached 

`  if(!editComment.getText().toString().trim().matches(""))
                {
                    realm.executeTransaction(new Realm.Transaction() {
                        @Override
                        public void execute(Realm realm) {
                            Comment comment = realm.createObject(Comment.class,"cmt"+countOrder());
                            comment.setContent(editComment.getText().toString());
                            comment.setDateTime(getCurrentTime());
                            comment.setUser(getCurrentUser());
                            realm.insertOrUpdate(comment);
                            adapter.notifyDataSetChanged();
                            realm.setAutoRefresh(true);
                            

                        }
                    });

                }`
#### Version of Realm and tooling
Realm version(s): 3.3.2

Realm sync feature enabled: yes

Android Studio version: 2.3.3

Which Android version and device: 6.0

**Comment by Zhuinden** [comment]
Have you tried using RealmChangeListener added to a RealmResults kept as a field reference, [as said in the docs?](https://realm.io/docs/java/latest/#realm-notifications)

**Comment by kneth** [comment]
I am closing the issue in the hope that the link above helped you. Don't hesitate to reopen if you still have the issue.
