### ISSUE TITLE
Realm 3.4.0: exception for nested isNull() query

### ISSUE THREAD

**Issue by baloghz** [realm/realm-java#4856]
#### Goal
I had a nested _isNull_ query on a child object (like described in the [documentation](https://realm.io/docs/java/latest/#chaining-queries)). The query worked well until I updated to realm version 3.4.0.

#### Expected Results
I expected that the query is executed without exception using realm version 3.4.0 like it was with realm version 3.3.2.

Documentation of _isNull_:
```java
 /**
     * Tests if a field is {@code null}. Only works for nullable fields.
     * <p>
     * For link queries, if any part of the link path is {@code null} the whole path is considered to be {@code null}
     * e.g., {@code isNull("linkField.stringField")} will be considered to be {@code null} if either {@code linkField} or
     * {@code linkField.stringField} is {@code null}.
     *
     * @param fieldName the field name.
     * @return the query object.
     * @throws java.lang.IllegalArgumentException if the field is not nullable.
     * @see Required for further infomation.
     */
```

#### Actual Results
I received an exception using the nested _isNull_ query
```
java.lang.IllegalArgumentException: Illegal Argument: isNull() by nested query for link field is not supported.
 at io.realm.internal.TableQuery.nativeIsNull(Native Method)
 at io.realm.internal.TableQuery.isNull(TableQuery.java:611)
 at io.realm.RealmQuery.isNull(RealmQuery.java:205)
 at com.bz.realmchildquery.MainActivity.executeQuery(MainActivity.java:63)
```

#### Code Sample
You can download a sample project from: 
https://github.com/baloghz/RealmChildQuery.git

For demonstration I slightly modified the example from the [documentation](https://realm.io/docs/java/latest/#chaining-queries). A person can have one optional dog and the dog has an optional parameters (ate_at).

```java
public class Dog extends RealmObject {
    private Long ate_at;  // optional
    // getters & setters ...
}

public class Person extends RealmObject {
    private Dog dog; // optional
    // getters & setters ...
}
```
I would like to find the Persons whose dog's ate_at is null
```java
RealmQuery<Person> query = realm.where(Person.class).isNull("dog.ate_at");
```

Try to change realm versions and you can see that everything works fine in 3.3.2 and not in 3.4.0

#### Version of Realm and tooling
Realm version when the query worked: 3.3.2 
Realm version when the query gave an exception: 3.4.0

Realm sync feature enabled: no

Android Studio version: 2.3.3

Which Android version and device: API21, Samsung SM-N9005

**Comment by kneth** [comment]
@baloghz Thanks for the detailed issue. I'll investigate and get back.

**Comment by kneth** [comment]
@baloghz I have added a simple test inspired by you - and it hints on where the bug is.

**Comment by baloghz** [comment]
@kneth Thank you for your response and keep up the good work guys!

**Comment by kneth** [comment]
@baloghz Quick update: I think I have a fix ready.

**Comment by kneth** [comment]
@baloghz I'll merge #4870 once our CI system approves it.

**Comment by kneth** [comment]
@baloghz I have merged a fix so I am closing the issue. Thanks for reporting!

**Comment by baloghz** [comment]
@kneth Thx again for the quick fix! I assume it will be part of the next release.
