### ISSUE TITLE
Realm 3.4.0: realm.createObject shows "Table has no columns" after schema.create has created them

### ISSUE THREAD

**Issue by eduxavier** [realm/realm-java#4860]
#### Goal

I want to create another object and moving data to it during migration process.

#### Expected Results

Create new objects. Moving all data. 

#### Actual Results

After changing from version 1.1.0 to 3.4.0 it stopped working. I've tried others versions but got differents messages. So I stuck in the last.

#### Steps & Code to Reproduce

Setup the application just like this:
```
public class RevendusApplication extends Application {

    @Override
    public void onCreate() {
        super.onCreate();
        Realm.init(this);

        RealmConfiguration realmConfiguration = new RealmConfiguration.Builder()
                .schemaVersion(CustomMigrations.VERSAO_ATUAL)
                .migration(new CustomMigrations())
                .build();
        Realm.setDefaultConfiguration(realmConfiguration);
   }
}


//create a migration structure as follows:
 if (schema.contains("CalendarioItemObj"))
            {
                schema.remove("CalendarioItemObj");
            }

 if (!schema.contains("CalendarItemObj"))
 {
                schema.create("CalendarItemObj")
                        .addField("id",long.class);
 }

```
And now, have another object to get the data from:

```
 schema.get("OrderObj")
                        .transform(new RealmObjectSchema.Function() {
                            @Override
                            public void apply(DynamicRealmObject obj)
                            {
                                 //problem happens here - can't create
                                 DynamicRealmObject entity= realm.createObject("CalendarItemObj");
                                    entity.setLong("id", obj.getLong("id"));
                            }
                        });
```

#### Code Sample

Code sample is above. Actually, everything went fine until I tried latest 2 or 3 versions.

This line:
`DynamicRealmObject entity= realm.createObject("CalendarItemObj");`

show an error:

```
java.lang.IllegalStateException: Table has no columns
```

#### Version of Realm and tooling
Realm version(s): ?
3.4.0
Realm sync feature enabled: yes/no
no.

Android Studio version: ?
2.32

Which Android version and device: ?
Android 7.1.1 - Nexus 5X

**Comment by Zhuinden** [comment]
This probably has to do with that an object must be created with its primary key set since 2.0.x

**Comment by eduxavier** [comment]
Hi @Zhuinden I forgot to mention that I remove the object and create the structure. 
First I do:
 if (schema.contains("CalendarioItemObj"))
            {
                schema.remove("CalendarioItemObj");
            }
Then
if (!schema.contains("CalendarItemObj"))
{
schema.create("CalendarItemObj")
.addField("id",long.class);
}

But I set no primary key.

**Comment by eduxavier** [comment]
Did some work here. I have downgraded to 1.1.0 and the error was different.

The time i run the core to schema.remove("CalendarioItemObj"); and then schema.create("CalendarItemObj"), I cannot add a new element in it with the code
DynamicRealmObject entity= realm.createObject("CalendarItemObj");

It seems a problem with the transaction. But I really don't know...

**Comment by kneth** [comment]
Your `transform()` is applied to `OrderObj` (you do `schema.get("OrderObj").transform()`) and you cannot create a `CalendarItemObj` object. Actually, `transform()` is for changing existing objects.

**Comment by bmeike** [comment]
Hey @eduxavier,
  Where are we with this issue?  Has your problem been resolved?

-blake

**Comment by bmeike** [comment]
Hi @eduxavier 
  We haven't heard from you for a while, so I'm going to assume that you've found a solution for this problem, so I'm going to close this issue.  If that is not the case, by all means, feel free to open a new issue.
-blake
