### ISSUE TITLE
Main object not being notified when a  "LinkingObjects" collection changes

### ISSUE THREAD

**Issue by gpulido** [realm/realm-java#4875]
Hello,
I have the following structure (I only write down the relevant parts)

```java
public class Parapet extends RealmObject 
{
 @PrimaryKey
    publicString String UUID;
 
@LinkingObjects("parapet")
    public final RealmResults<Letter> letters = null;

}
```

And the related class:

```java
public class Letter extends RealmObject {
    @PrimaryKey
    publicString UUID;   
    public Parapet parapet;
    public Contender contender;
}
```

And the last one:

```java
public class Contender extends RealmObject 
{
    @PrimaryKey
    publicString  String UUID;
}
```

I have a parapet with 4 letters asociated.
When I change one of the associated letters contender, the related parapet is not being notified (for example when I use a RealmResults of parapets as a source for a RecyclerViewAdapter
I'm using realm 3.4.0.
Before being a @LinkingObjects I had it as a RealmList<Letter> and it did notified.

I don't know if with the new @LinkingObjects functionallity this kind of notificiations are not being raised anymore.

**Comment by kneth** [comment]
@gpulido How do you add the change listener? If it is GC'ed too early, you might never get the callback.

**Comment by gpulido** [comment]
@kenth I have made the following test:
```
RealmResults<Parapet> parapets = realm.where(Parapet.Class).findAll()
RealmResults<Letter> letter = realm.where(Letter.Class).findAll()
 letters.addChangeListener(new RealmChangeListener<RealmResults<Letter>>() {
            @Override
            public void onChange(RealmResults<Letter> letters) {
                Timber.d("Letter changed");
            }
        });
        parapets.addChangeListener(new RealmChangeListener<RealmResults<Parapet>>() {
            @Override
            public void onChange(RealmResults<Parapet> parapets) {
                Timber.d("Parapet changed");
            }
        });
```
Then any time I change the contender on a letter I receive the Letter changed but not the Parapet changed.
Both listeners are initialized the same way and in the same class so they have the same lifecycle.

**Comment by kneth** [comment]
@gpulido Thanks for clarifying. I label the issue "Reproduction Required" so we remember to write a test 😅

**Comment by gpulido** [comment]
@kneth No prob.
I have also tested to add a listener to the letters collection to each parapet:
```Java
for(Parapet parapet:parapets)
        {
            parapet.letters.addChangeListener(new RealmChangeListener<RealmResults<Letter>>() {
                @Override
                public void onChange(RealmResults<Letter> letters) {
                    Timber.d("Letter on parapet collection changed");
                }
            });
        }

```
And I'm not receiving the notification either.

**Comment by Zhuinden** [comment]
You need to store a strong reference to keep them alive. `parapet` will be consumed by GC.

**Comment by gpulido** [comment]
@Zhuinden 
Even having a strong reference to the parapets list? OK
That explain the last example and have sense.
Regarding the first one (the parapets list doesn't receiving the notification when any of their related letters is changed), it should be receiving the notification, shouldn't it?

**Comment by kneth** [comment]
@gpulido Let me see if I understand you correctly.

As an example, you have a `Letter` object `L` which has a `Parapet` object `P` in the list `L.parapet`. You register a listener om `P.letters`, and when modifying `L`, you don't get a notification?

Please notice that you will need one listener for each `Parapet` object.

**Comment by gpulido** [comment]
@kneth I have several letters  L1, L2, L3, L4 that belong to a parapet P1. And several letters L5,L6,L7,  L8 that belong to a parapet P2 and so on.
Another way to express it is that a parapet have a list of  letters and a letter is only related to one parapet.
Each letter have properties, one of them is the Contender assigned to the letter.
I have a list of parapets (RealmResult<Parapet>) and a listener to the changes of any element of the parapet list. I expected that when a contender's letter is changed the parent  a parapet 
a of the letter is notified and hence the list listener (in a RealmRecyclerAdapter for example)

**Comment by gpulido** [comment]
@kneth I have several letters  L1, L2, L3, L4 that belong to a parapet P1. And several letters L5,L6,L7,  L8 that belong to a parapet P2 and so on.
Another way to express it is that a parapet have a list of  letters and a letter is only related to one parapet.
Each letter have properties, one of them is the Contender assigned to the letter.
I have a list of parapets (RealmResult<Parapet>) and a listener to the changes of any element of the parapet list. I expected that when a contender's letter is changed the parent  parapet 
of the letter would be notified and hence the list listener (in a RealmRecyclerAdapter for example)

**Comment by kneth** [comment]
@gpulido I have created two tests in #4906 to reproduce your issue. I will appreciate if you take a look and verify that the tests are equivalent to what you describe above.

**Comment by gpulido** [comment]
@kneth The listenerOnParentChangeChild is the one that reflects my problem.
The only thing that is slight different is that the child change in my case is not a "basic property" (the string id in the test case) but a reference to another RealmObject. But I guess it should be the same.

**Comment by kneth** [comment]
@gpulido This is - for the time being - the expected behaviour. Change listeners will not be triggered when backlinks are changed. It is mentioned in the documentation: https://realm.io/docs/java/3.4.0/api/io/realm/annotations/LinkingObjects.html ("Listeners on an object with a `@LinkingObject` field will not be triggered if the linking objects change.")

I will leave the issue open and keep it labeled as a bug since we wish to revisit the behaviour of the listeners.

See also https://github.com/realm/realm-cocoa/issues/4305

**Comment by gpulido** [comment]
@kneth sorry for the waste of time. I  made the change from hardlinks to backlinks as my model had very cyclic references and some of the serializations and copyfrom / to realm were very slow. The backlinks are a nice feature and made the model more straightforward and more "classic" so it seems logic that some of the  OORealm features are lost. There is not such a perfect solution.
In my case I have ended adding listeners manually to the LinkgObjects to know the change. Just in case, is there any way to force a "refresh" of an object to notify all listeners?.
In my example, when the letters change, with the letterslistener in place I would like to notify all the parentparapet listeners that the parapet may have changed, is that possible?

**Comment by beeender** [comment]
@gpulido Sorry for the late reply!

> In my example, when the letters change, with the letterslistener in place I would like to notify all the parentparapet listeners that the parapet may have changed, is that possible?

I think you can call the listener on the parent paratpet manually in the `letters`'s listner?
Something like:

```java
RealmChangeListener listenerOnParapet = {...};
parapet.addChangeListener(listenerOnParaPet);

// You need to keep a strong reference of this to ensure the listener won't be GCed!
RealmResults<Letter> letters = parapet.getLetters();
letters.addChangeListener(-> {
    listenerOnParapet.onChnaged();
});
```

So if you have separated listener instances for different `Parapet`, the listener on `Parapet` will be ensured to be called when the different `letters` changed.

**Comment by gpulido** [comment]
@beender At the end I'm doing something like that. However with that implementation, the letter listener must know which parapet listener has to call.
This means that in other places where the parapet are being listened, doesn't know about the "change".
What I was asking is for a way to "touch" a RealmObject so all the listeners are being notified.  I know that I can change a property on the parapet and that would trigger the change but seems a little dirty:

```Java
// You need to keep a strong reference of this to ensure the listener won't be GCed!
RealmResults<Letter> letters = parapet.getLetters();
letters.addChangeListener(-> {
    Letter letter = (obtain the letter that has changed through the listener).
    letter.parapet.touch()
});
```
