### ISSUE TITLE
keep realm db after android app update

### ISSUE THREAD

**Issue by Ksernik** [realm/realm-java#4877]
Hi everyone =)
I have the problem with app updating. When users update my app from Market, they lose authorization data, which are recorded in db. I found post on stackoverflow, but there is no answer.. (https://stackoverflow.com/questions/42527530/keep-realm-db-after-android-app-update)
What can i do for keep session data?

Realm init:
```
RealmConfiguration config = new RealmConfiguration.Builder(this)
                .name("myapp.realm")
                .schemaVersion(mRealmSchemaVersion)
                .deleteRealmIfMigrationNeeded()
                .build();
Realm.setDefaultConfiguration(config);
```

(schemaVersion is not change)

Realm version: 1.0.1
Android Studio version: 2.3.2
Which Android version and device: this is mass problem

Thanks for answers or advice =)

**Comment by cmelchior** [comment]
The Realm file on disk doesn't get deleted when people upgrade your app, but you have set `deleteRealmIfMigrationNeeded()`. This will delete the file if you changed the Realm schema somehow. You need to set a schema version and migration instead. See https://realm.io/docs/java/latest/#migrations

**Comment by Ksernik** [comment]
yes, i know it, but Realm schema does not change)))
ok, thanks, i will try set migration

**Comment by Ksernik** [comment]
yep, seems all work fine with migration =)
thanks a lot! =)

**Comment by kzdeveloper12345** [comment]
How to make it .
Please explain me.

**Comment by Zhuinden** [comment]
@kzdeveloper12345 here is an example: [migration-example](https://github.com/realm/realm-java/blob/c274673c84d3349b4934ff744dc8479813795ec5/examples/migrationExample/src/main/java/io/realm/examples/realmmigrationexample/model/Migration.java)

But you can reference the code in [**this**](https://github.com/Zhuinden/realm-auto-migration/blob/60154ada6e2c36e11adadece644e73611425ae7a/auto-migration/src/main/java/com/zhuinden/realmautomigration/AutoMigration.java) to know how to handle complex cases like changing primary key, or adding primitive lists
