### ISSUE TITLE
Realm like query  operations

### ISSUE THREAD

**Issue by RameshReddyKolla** [realm/realm-java#4880]
#### Goal
I want to perform first **beginsWith** and next **contains** both on the realm query.

#### Expected Results
Realm Results should have beginsWith data first and next contains data.

#### Actual Results
Always result has contains data first and next beginsWith data.

#### Code Sample
realmResults.where().beginsWith(searchColumnName, text, Case.INSENSITIVE).contains(searchColumnName, text, Case.INSENSITIVE);

#### Version of Realm and tooling
Realm version(s): 3.1.0

Realm sync feature enabled: no

Android Studio version: 2.3.3

Which Android version and device: Nexus 6 emulator

**Comment by RameshReddyKolla** [comment]
Please help me in this

**Comment by cmelchior** [comment]
@RameshReddyKolla 
The query just define a predicate that matches the objects you are after. If you want a specific sorting you should use `findAllSorted(fieldName, sorting)`

**Comment by RameshReddyKolla** [comment]
if i search for **IT** text on results, am getting the results as below:
servicesIT
abcITdef
IT services

but first i need IT serices, then next rest of the results

**Comment by cmelchior** [comment]
@RameshReddyKolla A requirement like that is really hard to generalize, so I'm not sure this is something we specifically would want to add support specifically.

Could you instead do 2 queries and combine them in the UI? Then you could be in full control over which order they came in.

This would generalize into something like a `new CompositeRealmResults(query1, query2)`, which I could see being useful for other cases as well

**Comment by Zhuinden** [comment]
I think you are missing an `or()` call. But I've seen this done in https://stackoverflow.com/questions/34975080/complexe-sorting-for-search-in-realm

**Comment by RameshReddyKolla** [comment]
@Zhuinden, above solution is fine but how can i update the results to adapter by **updateData() ** method which accepts only realm results but not arraylist..

**Comment by Zhuinden** [comment]
you can take relevant code from `RealmBaeeAdapter` and add it to `BaseAdapter` (or recyclerview's, both works)

**Comment by cmelchior** [comment]
@RameshReddyKolla I assume the above solved your issue. Please re-open if that is not the case.

Closing.
