### ISSUE TITLE
Report: java.lang.IllegalArgumentException: Illegal Argument: in_begin != in_end when converting to UTF-8

### ISSUE THREAD

**Issue by jpmcosta** [realm/realm-java#4881]
#### Goal

Crash report.

#### Results

```
Fatal Exception: java.lang.IllegalArgumentException: Illegal Argument: in_begin != in_end when converting to UTF-8; error_code = 4;  0x0041 […] 0xd83d in /home/cc/repo/realm/release/realm/realm-library/src/main/cpp/io_realm_internal_UncheckedRow.cpp line 308
       at io.realm.internal.UncheckedRow.nativeSetString(Unknown Source)
       at io.realm.internal.UncheckedRow.getColumnCount(Unknown Source:42)
       at io.realm.Object1RealmProxy.realmSet$text2(Unknown Source:94)
       at io.realm.Object1RealmProxy.copy(Unknown Source:64)
       at io.realm.Object1RealmProxy.realmSet$_largeIconByteArray(Unknown Source:190)
       at io.realm.DefaultRealmModuleMediator.createRealmObjectSchema(Unknown Source:111)
[…]
```

#### Steps & Code to Reproduce

The property in question is a `ByteArray` (I'm using Kotlin), but it is **not** used. I **never** read or write it. 

The previous property is a **String** (`text6`), and that seems the value being used.

The hex values for `0x0041 […] 0xd83d` were from a tweet (that could probably be in `text6` or `text2`) and it had some emojis at the end, namely: 🔥 💃

#### Code Sample (Kotlin)

```kotlin
open class Object1 : RealmObject() {

    @PrimaryKey
    open var id: Long = 0

    open var text1: String? = null

    open var text2: String? = null

    open var text3: String? = null

    open var text4: String? = null

    open var text5: String? = null

    open var text6: String? = null

    open var _largeIconByteArray: ByteArray? = null

    open var number1: Long = -1L

    @Index
    open var time: Long = 0L

    @Ignore
    var lazy: Lazy = Lazy()


    inner class Lazy {

        val largeIcon: Bitmap? by lazy {
            _largeIconByteArray?.getBitmap()
        }
    }

    /*
     * Methods.
     */
}
```

#### Version of Realm and tooling
Realm version: 3.3.1

Android Studio version: 3.0 Canary 4

Gradle version: 3.5

Android version and device: 8 (Google Pixel)

**Comment by cmelchior** [comment]
@jpmcosta Do you have the full stack trace? 

Also, what is that `getBitmap()` method on the ByteArray. Is that a custom extension function?

**Comment by jpmcosta** [comment]
@cmelchior yes, it's an extension function. Converts `ByteArray` to `Bitmap`.

**Comment by jpmcosta** [comment]
@cmelchior I didn't feel it was relevant, still:

```kotlin
fun ByteArray.getBitmap(): Bitmap {
    return BitmapFactory.decodeByteArray(this, 0, size)
}
```

**Comment by cmelchior** [comment]
It probably isn't. I was just wondering.

Something look fishy in your stack trace. It mentions `realmSet$text` but you don't have any fields named `text`?

**Comment by jpmcosta** [comment]
@cmelchior I changed the property names, except for properties related to `_largeIconByteArray`. `text` would be `text2`.

**Comment by cmelchior** [comment]
Okay, thanks. Do you also have the contextual information where this crashes. I'm a bit surprised it mentions `createRealmObjectSchema`. This normally indicates something happening when you open a Realm for the first time?

**Comment by jpmcosta** [comment]
The context is a running service. That happens when the service is called to create an instance of `Object1`.

I'm not sure why `createRealmObjectSchema` appears in the stack trace, as the realm instance should be created when Realm is injected to the service class, and that only happens once in the beginning (I just double checked it).

**Comment by cmelchior** [comment]
Ok. Can you post exactly how you are creating the object? Are you using `copyToRealm` or `realm.createObject()` ?

**Comment by jpmcosta** [comment]
I'm using `copyToRealm`. I have a companion object in `Object1`:
```kotlin
companion object {

    fun create(id: Long, text1: String?, text2: String?, text3: String?, text4: String?,
               text5: String?, text6: String?): Object1 {
        val object1 = Object1()
        object1.id = id
        object1.text1 = text1
        object1.text2 = text2
        object1.text3 = text3
        object1.text4 = text4
        object1.text5 = text5
        object1.text6 = text6
        return object1
    }
}
```
Then, to create the object, I call `copyToRealm(Object1.create(id, text1, text2, text3, text4, text5, text6))`.

**Comment by jpmcosta** [comment]
@cmelchior I think this might an issue only present in Android 8. Have you tested it there?

**Comment by kneth** [comment]
@jpmcosta We don't systematically test on Android 8. Do you see the issue on emulators? If you do, we can easily test 😄

**Comment by jpmcosta** [comment]
@kneth I'm sorry for the delayed answer: I just tried to test this with a simple project on an emulator, and even tried to reproduce the use case on my app.
I couldn't replicate the issue. 
So, I would suggest to close this issue, and if I get any reports on the future release of Android 8 (not a preview build), I'll reopen it, or create a new one.

**Comment by kneth** [comment]
@jpmcosta Thanks for the update. Yes, don't hesitate to reopen and mention me :smile:
