### ISSUE TITLE
Unable to open a realm at path (/data/data/me.beelink.beetrack2/files/default.realm.management) in /home/cc/repo/realm/release/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 217 Kind: ACCESS_ERROR

### ISSUE THREAD

**Issue by jplazcano87** [realm/realm-java#4890]
java.lang.RuntimeException: Unable to create application me.beelink.beetrack2.application.BeetrackApplication: io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/data/me.beelink.beetrack2/files/default.realm.management': make_dir() failed: I/O error. (make_dir() failed: I/O error) (/data/data/me.beelink.beetrack2/files/default.realm.management) in /home/cc/repo/realm/release/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 217 Kind: ACCESS_ERROR.

I'm having this crash when my application is starting in onCreate of myApp extends android.app.Application., my migration is working in all other devices. this crash only happens in some older devices
```
    RealmConfiguration config = new RealmConfiguration.Builder()
        .schemaVersion(2) // Must be bumped when the schema changes
        .migration(new Migration()) // Migration to run
        .build();
    Realm.setDefaultConfiguration(config);
```

#### Version of Realm and tooling
Realm version(s): 3.4.0

Realm sync feature enabled: no

Android Studio version: 2.3.3

Which Android version and device: 4.3 / GT-I9300

**Comment by beeender** [comment]
Hi, can you please set a breakpoint at the first time `getDefaultInstance()` called. And when the debugger stops, check if `/data/data/me.beelink.beetrack2/files` exists through adb? 
thanks!

**Comment by beeender** [comment]
Also, when this problem happens, can you see which thread does it happen on? The main thread?

**Comment by jplazcano87** [comment]
this problem came to me via rollbar, so i don't have the device, this code is running in the main thread, as i said early, this crash happens only on this device/os version GT-I9300/4.3

**Comment by cmelchior** [comment]
@jplazcano87 Do you know if this only happens once or consistently?

**Comment by beeender** [comment]
`I/O error` - `EIO` when `mk_dir` called sounds like the nand flash is broken on the device :( Doe the phone work normal for other apps? especially does it pass the disk benchmark or some other heavy disk usage app?

**Comment by jplazcano87** [comment]
finally i figured out that the device was rooted, so the user has a "cleaning app" installed, so this app deleted the realm file in background, thanks for the help.

**Comment by beeender** [comment]
great ! i will close this issue then. Thanks a lot for the feedback!
