### ISSUE TITLE
realm.io/products/realm-mobile-database example would get GCd

### ISSUE THREAD

**Issue by Zhuinden** [realm/realm-java#4892]
#### Goal

> What do you want to achieve?

Read through the Realm Mobile Database page and learn the basics of how it works with Java

#### Expected Results

Code shouldn't have hidden errors

#### Actual Results

``` java
public void onActivityCreated(Bundle savedInstanceState) {
  realm = Realm.getDefaultInstance();
  RealmResults<Customer> customers = realm.where(Customer.class).findAllAsync(); // <-- would get GC'd!
  changeListener = new RealmChangeListener() {
    @Override
    public void onChange(RealmResults<Customer> results) {
      listAdapter.notifyDataSetChanged(); // Update the UI
    }
  };
  customers.addChangeListener(changeListener);
}
```

If `onActivityCreated()` is shown, then `RealmResults<Customer> customers;` should be a field.

#### Version of Realm and tooling
Realm version(s): not relevant

Realm sync feature enabled: no

Android Studio version: not relevant

Which Android version and device:  not relevant

**Comment by zaki50** [comment]
@Zhuinden Thank you for your reporting.

https://realm.io/products/realm-mobile-database/

**Comment by cmelchior** [comment]
Fixed. Closing
