### ISSUE TITLE
Load Realm File From SdCard 

### ISSUE THREAD

**Issue by morteza-moradi** [realm/realm-java#4895]
I Compressed a Realm File (myrealm.realm)  And Saved in Asset Folder , in First Run App I Decpmpress and Save it to A Folder in SdCard , now How Can i load Data from this File ?
Where i put Realm file  Address When i Configuration ?

**Comment by Zhuinden** [comment]
`.directory()` and `file()` might help. Just make sure you have adequate permissions for reading/writing external storage.

**Comment by cmelchior** [comment]
Hi @morteza-moradi I assume the above solved your issue. Please re-open if that was not the case.
