### ISSUE TITLE
model extending RealmObject cannot have field with name 'tableName'

### ISSUE THREAD

**Issue by TKolbusz** [realm/realm-java#4907]
If you create model that extends RealmObject with field that name is `tableName` Realm does not compile because it's getter name `getTableName` conflicts with RealmProxy auto-generated class static getter with same name.
#### Version of Realm and tooling
Realm version(s): realm-android 0.87.5
Realm sync feature enabled: no
Android Studio version: 2.3.3

**Comment by zaki50** [comment]
Hi @TKolbusz 

We already removed this kind of restrictions in later versions.
In latest version, you don't need to extend `RealmObject` (implement `RealmModel` interface and add `@RealmClass` annotation instead), and you don't need to define setters and getters.
Could you try latest version?

**Comment by TKolbusz** [comment]
@zaki50 Thanks for answer, I'm using latest Realm version for Android and there isn't `RealmModel` interface available. Any way to switch to version with `RealmModel`?

**Comment by beeender** [comment]
@TKolbusz The installation steps changed a lot for the latest realm compared with `0.87.5`. Please check this doc carefully https://realm.io/docs/java/latest/#installation

also see https://realm.io/docs/java/latest/#realmmodel-interface about `RealmModel`.

**Comment by beeender** [comment]
@TKolbusz with the latest Realm, you can also still extend the `RealmObject`, keep the field name `tableName` but use a different getter name like `getMyTableName`.

**Comment by bmeike** [comment]
Hey @TKolbusz,
  It looks like this issue was resolved with the newer version or Realm. I'm going to close it.  If it or any other problem recurs please feel to open a new one.  Better yet, ask on [StackOverflow](https://stackoverflow.com/) 
-blake
