### ISSUE TITLE
findAllSortedAsync causing ANR or UI freeze while tested with ~30k records

### ISSUE THREAD

**Issue by RajendraSinghBohra** [realm/realm-java#4910]
In my project, I need to get all records(~30k) based on some sorting and then show in the recyclerview. but while trying with  findAllSortedAsync() sometimes I gets ANR or UI get's freeze. 
The code is as follows:

```
 RealmResults<RecipeRealmObject> recipeRealmResult=null;
 public void fetchNewlyAddedRecipe(boolean withImage, final OnCompleteListener onCompleteListener) {
        RealmQuery<RecipeRealmObject> query = realm.where(RecipeRealmObject.class);
        if (withImage) {
            query.isNotNull("mainImage");
        }
        Logger.e("time before query", new Date().toString());

        recipeRealmResult = query.findAllSortedAsync("dateCreated", Sort.DESCENDING);
        RealmChangeListener realmChangeListener = new RealmChangeListener() {
            @Override
            public void onChange(Object element) {
                if (recipeRealmResult != null) {
                    Logger.e("time after query", new Date().toString());

                    onCompleteListener.onSearchComplete(recipeRealmResult);
                    recipeRealmResult.removeAllChangeListeners();

                }
            }
        };
        recipeRealmResult.addChangeListener(realmChangeListener);
    }
```

Any help would be greatly appreciated .

**Comment by beeender** [comment]
See comment https://github.com/realm/realm-java/issues/4904#issuecomment-312803273

**Comment by cmelchior** [comment]
@beeender That should just slow down notifications, not freeze the UI though?

If ANR's are triggered, I'm guessing that your async query is getting converted to a synchronous query somehow. Are you calling `Realm.refresh()` anywhere or making synchronous transactions on the UI thread?

**Comment by beeender** [comment]
not only `Realm.resfresh()` will slow down UI, calling `realm.beginTransaction()/commitTransaction()` on UI thread will slow down UI as well.

**Comment by RajendraSinghBohra** [comment]
@cmelchior  I haven't used Realm.refresh().

**Comment by Zhuinden** [comment]
Make sure your transactions are not on the UI thread.

**Comment by RajendraSinghBohra** [comment]
Found the issue, I was making transactions on the UI thread.
Thanks everyone for the help
