### ISSUE TITLE
Javadoc of RealmConfiguration still shows builder with "context" in constructor param

### ISSUE THREAD

**Issue by Zhuinden** [realm/realm-java#4916]
https://realm.io/docs/java/latest/api/io/realm/RealmConfiguration.html (3.4.0) says

    RealmConfiguration config = new RealmConfiguration.Builder(getContext()).build())

But that is not true, it is

    Realm.init(getContext());
    RealmConfiguration config = new RealmConfiguration.Builder().build();

**Comment by cmelchior** [comment]
Thanks for noticing that 👍 It should be fixed in #4917

**Comment by cmelchior** [comment]
Merged
