### ISSUE TITLE
Distinct query on date field without considering time

### ISSUE THREAD

**Issue by chiara79** [realm/realm-java#4931]
Hi guys,
it's possible to run a query with distinct on field type Date but considering only **date** and not **date time**?

I've a several records in my db with field `start` (type date) and `name` (type string).
I would like to make the distinct query only on the start field, but considering only the date and not the time. I try to make an example:

I've 5 records:

| Field Id  | Field Name | Field Start |
| ------------- | ------------- | ------------- |
| 1 | Task 1 | 2017-06-01 11:20:22 |
| 2 | Task 2 | 2017-06-01 12:43:28 |
| 3 | Task 3 |2017-06-01 10:30:47 |
| 4 | Task 4 |2017-06-02 09:36:49 |
| 5| Task 5 | 2017-06-02 12:32:59 |

Running the query with the distinct on `start` field, I should only get 2 records:
2017-06-01
2017-06-02 

It's possible in realm?

#### Version of Realm and tooling
Realm version(s): 3.4.0
Realm sync feature enabled: no
Android Studio version: 2.3.3
Which Android version and device: Nexus 5

Thanks :)

**Comment by Zhuinden** [comment]
Only if you add another field to your object that is the same Date, but with hour minutes seconds milliseconds set to 0

**Comment by cmelchior** [comment]
What @Zhuinden said. If you want to query for date specifically you need to strip the time information yourself. Alternatively, you can maintain two fields in your model class, once with the timestamp and one with only the date information.

Java 6/7 doesn't really have a concept for only dates (although `Calendar` comes close), and we haven't ruled out adding support for the new Java 8 `java.time` API's, but it is not on the short-term roadmap.
