### ISSUE TITLE
xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxzzzzzzzzzzzzzzzzzzzzzzzzzzsssssssssssssssssssssssssssssssssssssssssssssttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttttaaaaaaaaaaaaaaaaaaaaaaaaaddddddddddddddddddddddddddddfffffffffffffffffffffffffffffffffogggggggggggggggggggggggggggpphp[[jjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjjj

### ISSUE THREAD

**Issue by Dimoshka** [realm/realm-java#4936]
#### Goal

> What do you want to achieve?

#### Expected Results

> ?

#### Actual Results

>  E.g. full stack trace with exception

#### Steps & Code to Reproduce

> Describe your current debugging efforts.

#### Code Sample

```java

> Your code here. Bigger samples should ideally be as separate Android Studio project, 
> in gists/repositories or privately at help@realm.io)

```

#### Version of Realm and tooling
Realm version(s): ?

Realm sync feature enabled: yes/no

Android Studio version: ?

Which Android version and device: ?

**Comment by cmelchior** [comment]
Looks like the cat took a nap on the keyboard 😸  If this was intentional, please reopen with a proper title and the template filled out.
