### ISSUE TITLE
io.realm.exceptions.RealmError  No space left on device 

### ISSUE THREAD

**Issue by koukoucai** [realm/realm-java#4945]
#### Goal

To allow app to work by solving realm error

#### Steps & Code to Reproduce

My app start IntentService every 3 minutes to query and upload the realm data.
My realm data has the max lines (1000),because I find that intserting 1 line the realm file increases around 7kb .
I also use the Aspectj to monitor every http request to insert them into the Realm file.
I am true that I use the Realm.close() in the query and insert.
So is there some better solutions ?

Unrecoverable error. write(): failed: No space left on device in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 109

io.realm.internal.SharedRealm.nativeGetSharedRealm(Native Method)
 io.realm.internal.SharedRealm.<init>(SourceFile:187)
 io.realm.internal.SharedRealm.a(SourceFile:229)
 io.realm.internal.SharedRealm.a(SourceFile:204)
 io.realm.RealmCache.a(SourceFile:124)
 io.realm.t.l(SourceFile:210)
com.greenline.netmonitor.NetMonitor.b(SourceFile:391)
com.greenline.netmonitor.service.NetMonitorService.onHandleIntent(SourceFile:62)  android.app.IntentService$ServiceHandler.handleMessage(IntentService.java:65)
 android.os.Handler.dispatchMessage(Handler.java:102)
 android.os.Looper.loop(Looper.java:135)
 android.os.HandlerThread.run(HandlerThread.java:61)

#### Code Sample

```java


public class NetMonitor {
    .............
    public static List<NetModel> queryNotUpload() {
        Realm realm = Realm.getDefaultInstance();
        final List<NetModel> realmResult = new ArrayList<>();
        try {
            realm.executeTransaction(new Realm.Transaction() {
                @Override
                public void execute(Realm realm) {
                    List<NetModel> r = null;
                    List<NetModel> netModels = realm.where(NetModel.class).equalTo("isUpload", false).findAll().sort("startDateString", Sort.DESCENDING);;
                    netModels = realm.copyFromRealm(netModels);
                    int size = netModels.size();
                    //default number 100
                    if (subEnd == 0) {
                        subEnd = 100;
                    }
                    if (size >= subEnd) {
                        r = netModels.subList(subStart, subEnd);
                    } else {
                        r = netModels.subList(subStart, size);
                    }
                    realmResult.addAll(r);
                }
            });
        } catch (Exception e) {
            e.printStackTrace();
        } finally {
            realm.close();
        }
        return realmResult;
    }
}


public class NetMonitorService extends IntentService {
    ...........
    @Override
    protected void onHandleIntent(Intent intent) {
        if (intent != null) {
            final String action = intent.getAction();
            if (ACTION_FOO.equals(action)) {
                //upload data
                try {
                    List<NetModel> netModels = NetMonitor.queryNotUpload();
                    //no empty data
                    if (netModels.isEmpty()){
                        return;
                    }
                    String body = NetUtil.getUploadStatisticParam(netModels).toString();
                    if (NetMonitor.DEBUG) {
                        Log.i(TAG,"fixed time upload");
                    }
                    HttpNetClient.getInstance().uploadStatistic(NetMonitor.getRelativeUrl(), body);
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
        }
    }
}
```

#### Version of Realm and tooling
Realm version(s):  "io.realm:realm-gradle-plugin:3.0.0"

Realm sync feature enabled: yes/no

Android Studio version: 2.3.3

Which Android version and device:  Android 5.0, Galaxy Note3 N9008V

**Comment by beeender** [comment]
> My realm data has the max lines (1000),because I find that intserting 1 line the realm file increases around 7kb .

1. How big the Realm file end with when the issue happens? 7KB x 1000 = 7MB doesn't sound too big i think?
2. What is the type you store the line? as `String`?

**Comment by koukoucai** [comment]
1.I can't make sure the Realm file's size when it happens. The report displays that there is 0.00kb can use in storage. 
The data's rule is max lines(1000)  but only app starts we check the Realm data's lines.  if the lines > 1000, I delete half of it.  
There is questions I doubt.  First , the time of user use app ,  this issue happens in a lot of android devices . The app using time is from seconds to some hours. In some hours's using and no quit the app, the issue's happening may be the realm file is too big . But in seconds the issue happens, I think it may not close some Realm instance which open in background (like the intentService ).

2.I store the lines is all String  from http's request's body and response's body.

**Comment by beeender** [comment]
It is hard to tell what is wrong... if you think the data should not be that big, then i still guess there would be some unclosed Realm instance on some background thread ...

You could debug it with `Realm.getGlobalInstanceCount()` and `Realm.getLocalInstanceCount()` to check if it is the problem.

Also, we have introduced a new API to do compact on the first time you open the Realm, see https://realm.io/docs/java/3.5.0/api/io/realm/CompactOnLaunchCallback.html
That may help you a bit if you had the exploded Realm file size problem before (due to unclosed instance on bg thread).

another thinking is since you only do 1000 lines check at the beginning, so the size may grow up a lot during the app running. So it might be a good idea you do the 1000 lines check whenever you want to insert more data.

**Comment by koukoucai** [comment]
`Realm.getGlobalInstanceCount()` and `Realm.getLocalInstanceCount()`  I will test later.

1000 lines check at the beginning ,if lines >1000 ,I delete half of it. 
For example :
` RealmResults<NetModel> realmResults = realm.where(NetModel.class).findAll().sort("startDateString", Sort.ASCENDING);
                        int size = realmResults.size();
                        if (DEBUG){
                            Log.e(TAG,"deleteHalf.........:size..."+size);
                        }
                        for (int i = 0;i < size/2;i++){
                            realmResults.get(i).deleteFromRealm();
                        }`

The delete way in api ,I just find that delete all  or delete one . Is there a better way to do this ?

So it might be a good idea you do the 1000 lines check whenever you want to insert more data.
Do it  affect some app's performing ?  I mean  query all count to do 1000lines check whenever inert more data?

**Comment by beeender** [comment]
> In the api ,I just find that delete all or delete one . Is there a better way to do this ?

You could also have some field as the condition. eg.: delete all whose modify data is before some certain time. deleting one by one is surely slower than delete a collection in one run.

> Do it affect some app's performing ? I mean query all count to do 1000lines check whenever inert more data?
Yes, it will. But depends on how you delete them and where do you delete them, i think it can be handled well. eg.: do transaction in the background thread.

**Comment by koukoucai** [comment]
Thanks to give me help。

**Comment by bmeike** [comment]
Hey @koukoucai 
  It looks like you are back up an running.  I'm going to close it.  If it or any other problem recurs please feel to open a new one.  Better yet, ask on [StackOverflow](https://stackoverflow.com/) 
-blake
