### ISSUE TITLE
the app has two process,does two process can access the same Realm

### ISSUE THREAD

**Issue by Wlazly** [realm/realm-java#4950]
the Realm java 3.5.0 write"Although Realm files can be accessed by multiple threads concurrently, they can only be accessed by a single process at a time. Different processes should either copy Realm files or create their own. Multi-process support is coming soon."

my  app has two processes, does two processes can not access the same Realm？

**Comment by beeender** [comment]
We don't officially support multi-processes right now. However, you will find even the notification works in the multi-processes environment.

But there are some limitations on multi-processes support, see https://github.com/realm/realm-java/issues/1091#issuecomment-244039670
There might be more some other limitations/issues not listed in the issue for multi-processes support. We won't prioritise issues with multi-processes for now.

**Comment by Wlazly** [comment]
That is that two processes can access the same Realm, but it has some potential issues??

**Comment by beeender** [comment]
Yes, please refer to #1091 to see more details.

**Comment by Zhuinden** [comment]
@Wlazly migrations and encryption have issues, basically.

**Comment by beeender** [comment]
@Wlazly I am closing this issue now. If you have more questions/suggestions on the multi-process support, we can discuss it in #1091
