### ISSUE TITLE
Duplicate PrimaryKeys with CopyToRealmOrUpdate - how is this possible?

### ISSUE THREAD

**Issue by jennymolske** [realm/realm-java#4957]
Hi,
I've got some nested RealmObjects which I try to insert into Realm via copytoRealmOrUpdate. This is my object

```
public class Site extends RealmObject {

    @Required
    @PrimaryKey
    private String SiteUUID;

    private RealmList<AttributeObject> mAttributeObjects;
    private RealmList<Campaign> Campaigns;

    public Site() {}

    //getter und setter
}

public class Campaign extends RealmObject {

    @Required
    @PrimaryKey
    private String CampaignUUID;

    @Expose
    @SerializedName("name")
    private String Name;

    public Campaign() {}
}

public class AttributeObject extends RealmObject {

    @PrimaryKey
    @Required
    private String AttributeObjectUUID;

    private Site site;

    public AttributeObject() {}
}
```

The tricky part for this object relies in this other class attributes which could contain a copy of the site object themselfs. I try to clarify this with the JSON which gets parsed into the Site object.

```
{
    "siteUUID": "4d310340-1dd1-436b-ab05-723eaea9730f",
    "attributes": [
        {
            "attributeUUID": "270568ce-f31a-4343-9a53-ba32f3a0ded8",
            "site": {
                "siteUUID": "4d310340-1dd1-436b-ab05-723eaea9730f",
                "campaigns": [
                    {
                        "campaignUUID": "2c2890d0-b15b-497b-946d-affce01c0bfa",
                        "name": "Campaign1"
                    }
                ]
            }
        }
    ],
    "campaigns": [
        {
            "campaignUUID": "2c2890d0-b15b-497b-946d-affce01c0bfa",
            "name": "Campaign1"
        }
    ]
}
```
As we can see the root Site object got a campaign and some other objects called "attributes". However these objects need to have a reference to its parent site and this site also contains the Campaign object. So we have two Sites with the same PrimaryKey and two Campaign objects with the same PrimaryKey. 

After I've parsed the object from JSON to RealmObject I tried to store the object in the database with my appendToRealm method

```
public static RealmObject appendToRealm(final RealmObject object) {
       try (Realm realm = Realm.getDefaultInstance()) {

           final RealmObject[] managedObject = new RealmObject[1];
           realm.executeTransaction(new Realm.Transaction() {
               @Override
               public void execute(Realm realm) {
                    managedObject[0] = realm.copyToRealmOrUpdate(object);
               }
           });

           return managedObject[0];
       } catch (Exception e) {
           e.printStackTrace();
           HockeyCrashHelper.getInstance().sendCrash(e);
       }

       return null;
}
```
If my understanding is correct I expect Realm to loop the object tree recursively and inserts or updates all objects to the database. And because both duplicate objects contain the same primary key I expected Realm to only contain one Site object and only one Campaign object in the database after the appendToRealm method. But the Campaign object was inserted twice. If I see the logs in my app and inspect the database in RealmBrowser they show two instances of the Campaign object with the same uuid as primary key. The Site object is present only once, although it has been twice in the JSON, too. How is this even possible? For all other objects copyToRealmOrUpdate works as expected. Maybe you can clarify this problem?

Thanks in advance :)

#### Version of Realm and tooling
Realm version(s): 3.3.2
Realm sync feature enabled: no
Android Studio version: 2.3.3
Which Android version and device: Sony Xperia Z5, Android 7.0

**Comment by beeender** [comment]
hello! do you have the full stack trace so we can get more clues?

**Comment by Zhuinden** [comment]
@beeender I don't think there is a stack trace, he just somehow manages to insert 2 items with the same GUID even though it is annotated with `@PrimaryKey` if I see right

**Comment by jennymolske** [comment]
What stacktrace? There is no exception thrown ;-)

**Comment by beeender** [comment]
@jennymolske Yes, sorry, my bad...

I re-checked this part of logic, it seems fine.
Would it possible that two `campaignUUID` has some invisible characters that make them different?

**Comment by Zhuinden** [comment]
@beeender well they *look* similar...

**Comment by jennymolske** [comment]
@beeender 99.999999999% sure that there are no invisible characters :-D This was the first thing I've checked (multiple times)

**Comment by beeender** [comment]
If they are the same string, then definitely there is a bug somewhere... I check the relevant code again, but still cannot see what is going wrong.

Is it possible for you to share you project with us? to help@realm.io if you want to share it privately.
Otherwise is it possible to create a sample project to reproduce the problem?

Also, if you can reproduce this easily, you can set a breakpoint at `CampaignRealmProxy.copyOrUpdate()`. CampaignRealmProxy.java is a generated class.

These two lines will be related:
```
long pkColumnIndex = table.getPrimaryKey();
long rowIndex = table.findFirstString(pkColumnIndex, ((CampaignRealmProxyInterface) object).realmGet$CampaignUUID());
```

The roIndex will be a non `-1` value if the same PK exists already.

**Comment by jennymolske** [comment]
@beeender I rechecked my problem and discovered that not the campaign object is duplicated in the database but the linking to the Site object is. An unfortunate presentation of the tables in the RealmBrowser has led me to the assumption I posted above...

But is this duplicate linking the correct behaviour? Can you clarify this please?
Doesn't it work this way:
- Realm inserts nested, nested campaign
- Realm inserts nested site and creates the link to the nested campaign
- Realm inserts the "root" campaign which is nested in the root site. Because the primary key already exists the campaign only gets updated. No duplicate in db. What happens with the link to the nested site?
- Realm inserts the root site. Because an object with the same uuid already exists the object is only updated. What happens to the link from the nested site to the nested campaign? Is it still linked here? That would be explain why the site object gets linked with the campaign twice...

**Comment by Zhuinden** [comment]
Ya this is why I'd love me some [RealmLinkedSet](https://github.com/realm/realm-java/issues/759#issuecomment-305455059)

**Comment by beeender** [comment]
We used to have a similar bug before, but that has been fixed long long time ago.

According to your model class definition, the process should be like:
* Realm create `Site`
* Realm create `Campaign`
* Realm link the created `Campaign` to the `Site`'s list

You could do a little debug by set breakpoint at `SiteRealmProxy.update()` and `SiteRealmProxy.copy()`.

in the `update()` method, you can see something similar to:
```
RealmList<some.test.AllTypes> columnRealmListList = realmObjectSource.realmGet$columnRealmList();
RealmList<some.test.AllTypes> columnRealmListRealmList = realmObjectTarget.realmGet$columnRealmList();
columnRealmListRealmList.clear();
```
As you can see if it is an existing `Site` object, it will clear the list first, then add.

in the `copy()` method, no clear steps since the list should be empty.

Are you sure your unmanaged object `Site` doesn't have multiple `Campaign` in the `Campaigns` list?

**Comment by jennymolske** [comment]
Yes, I'm sure. This is my code
```
Log.d("debug", "before site:" + site.getCampaigns().size());
Site managedSite = (Site) RealmUtils.appendToRealm(site);
Log.d("debug", "after site:" + managedSite.getCampaigns().size());
```

and its printing
```
before site:1
after site:2
```

I will try debugging with the methods you suggested next. :)

**Comment by jennymolske** [comment]
I found it!! :D 

What does the trick (I've updated my data model above for better understanding):
I needed to change the declaration order of `mAttributeObjects` and `Campaigns`. With the changed order the SiteRealmProxy firstly handles the `Campaigns` and afterwards the `mAttributeObjects`. But I've got no further understanding why this works and the reverse declaration ordering do not.

I've created an example project for reproducing. I was able to reproduce 10 of 10 errors with the wrong declaration error and 10 of 10 non-errors with the reversed declaration order.
https://drive.google.com/file/d/0B1aHkcAaWIA-MFRoVWphTlhFMk0/view?usp=sharing

I'm happy that I've got a "fast" solution for this, although its a hacky workaround, but I think this should definitely be fixed as soon as possible. Debugging of this bug is very stressful and time-consuming.

A [RealmLinkedSet](https://github.com/realm/realm-java/issues/759#issuecomment-305447449) or sth similar would have been very nice in this case.

**Comment by beeender** [comment]
Thanks a lot to find this case!
It is actually caused by the `Site` objects are different java objects for `entityResponse` and `entityResponse.mAttributeObjects.site`. That caused Realm created it twice.

#5023 will fix this.

![image](https://user-images.githubusercontent.com/449296/28614349-1b69ad04-7228-11e7-95f3-02fa2cccf4b1.png)
