### ISSUE TITLE
Outdated documentation: OutOfMemoryError

### ISSUE THREAD

**Issue by dvdmunckhof** [realm/realm-java#4968]
The [changelog of v3.5.0](https://github.com/realm/realm-java/blob/master/CHANGELOG.md#350-2017-07-11) states `io.realm.internal.OutOfMemoryError` has been replaced with `java.lang.OutOfMemoryError`. However, the [documentation of Realm v3.5.0](https://realm.io/docs/java/3.5.0/#what-to-do-about-out-of-memory-exceptions) still states an `io.realm.internal.OutOfMemoryError` will be thrown. This paragraph should be updated to reflect the recent changes.

**Comment by bmeike** [comment]
Opened https://github.com/realm/realm.io/pull/3571 to fix the documentation.

**Comment by bmeike** [comment]
The docs have been fixed.  Good catch @dvdmunckhof !
