### ISSUE TITLE
tgkill crashes in realm

### ISSUE THREAD

**Issue by Prashanth-Nelli** [realm/realm-java#4970]
#### Regarding Realm tgkill Crashes

> Hi guys recently I am seeing crashes due to realm in some specific devices mostly **motorola deivces** (till now around 40 crashes happend) 
I have used crashlytics to capture crashes but these are not being captured by crashlytics.
I am seeing this crashes only in playstore ANRs & Crashes section.

before posting it here I have searched online but couldn't find any solution

#### Error details

>  backtrace:
  native: pc 0000000000049c44  /system/lib/libc.so (tgkill+12)
  native: pc 00000000000473e3  /system/lib/libc.so (pthread_kill+34)
  native: pc 000000000001d535  /system/lib/libc.so (raise+10)
  native: pc 0000000000019081  /system/lib/libc.so (__libc_android_abort+34)
  native: pc 00000000000170e4  /system/lib/libc.so (abort+4)
  native: pc 000000000015d938  /data/app/com.appsbynelli.seniorbro-1/lib/arm/librealm-jni.so (_ZN9__gnu_cxx27__verbose_terminate_handlerEv+348)
  native: pc 00000000001307ec  /data/app/com.appsbynelli.seniorbro-1/lib/arm/librealm-jni.so (_ZN10__cxxabiv111__terminateEPFvvE+8)
  native: pc 000000000013088c  /data/app/com.appsbynelli.seniorbro-1/lib/arm/librealm-jni.so (_ZSt9terminatev+12)
  native: pc 000000000015c828  /data/app/com.appsbynelli.seniorbro-1/lib/arm/librealm-jni.so
  native: pc 0000000000046eb3  /system/lib/libc.so (_ZL15__pthread_startPv+22)
  native: pc 0000000000019acd  /system/lib/libc.so (__start_thread+6)

#### Version of Realm and tooling
Realm version(s): 3.0.0

Realm sync feature enabled: no

Which Android version and devices: ?
Moto G(4) Plus (athene_f)	8	22.9%
Moto X Play (lux_uds)	7	20.0%
Moto G (5) Plus (potter_n)	6	17.1%
One (A0001)	6	17.1%
VIBE K6 Power (K33a42)	4	11.4%
Moto E3 Power (taido_row)	3	8.6%
X (OnePlus)	1	2.9%

By Android Version :- 

Android 7.0 | 18 | 51.4%
-- | -- | --
Android 6.0 | 17 | 48.6%

**Comment by Zhuinden** [comment]
Do you have any UI thread transactions?

**Comment by Prashanth-Nelli** [comment]
Yes, my app has lot of ui thread transactions.
I am using ResponseCallback class to return response to the ui thread (here I am assuming this callback will gets executed on ui thread).

public void getBookmarks(final ResponseCallback callback){

        final ArrayList<TopicFeed> bookmarks = new ArrayList<>();

        if(db.isClosed()){
            assignInstance();
        }

        db.executeTransactionAsync(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {

                RealmResults<TopicFeedModel> realmResults = realm.where(TopicFeedModel.class)
                        .equalTo("bookmarked",true)
                        .findAll();

                if(realmResults != null && realmResults.size() > 0){
                    for(TopicFeedModel topicFeedModel : realmResults){
                        Gson gson = new Gson();
                        TopicFeed topicFeedDao = new TopicFeed();
                         ................
                         bookmarks.add(topicFeedDao);
                    }
                }

            }
        }, new Realm.Transaction.OnSuccess() {
            @Override
            public void onSuccess() {
                callback.onResponse(bookmarks);
            }
        }, new Realm.Transaction.OnError() {
            @Override
            public void onError(Throwable error) {
                callback.onError(error);
            }
        });
    }

In some scenarios I have used the following form. (here I am explicitly running callback on ui thread).

    public void getTopicCount(final ResponseCallback callback){

        if(db.isClosed()){
            assignInstance();
        }

        db.executeTransactionAsync(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {
                final int count = realm.where(TopicModel.class).findAll().size();
                ((AppCompatActivity)context).runOnUiThread(new Runnable() {
                    @Override
                    public void run() {
                        callback.onResponse(count);
                    }
                });
            }
        }, new Realm.Transaction.OnError() {
            @Override
            public void onError(Throwable error) {
                callback.onResponse(0);
            }
        });
    }

**Comment by Zhuinden** [comment]
Can you share an example of `callback.onResponse(bookmarks);` what callback is?

**Comment by Prashanth-Nelli** [comment]
**callback class :-**

public abstract class ResponseCallback<Response,Error> {

    public void onResponse(Response response){};

    public void onError(Error error){};

}

I have created a class Store which has a private realm db instance and it exposes some public methods I will use those exposed public methods in my activity and fragments to fetch data

 **One of the exposed public method.**

    public void bookmark(final String topicId, final boolean bookmark, final String feedId, final ResponseCallback callback){

        if(db.isClosed()){
            assignInstance();
        }

        db.executeTransactionAsync(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {

                TopicModel topicModel = realm.where(TopicModel.class)
                        .equalTo("id",topicId).findFirst();
                topicModel.setHasBookmarks(bookmark);

                TopicFeedModel topicFeedModel = realm.where(TopicFeedModel.class)
                        .equalTo("_id",feedId).findFirst();
                topicFeedModel.setBookmarked(bookmark);

            }
        }, new Realm.Transaction.OnSuccess() {
            @Override
            public void onSuccess() {
                callback.onResponse(null);
            }
        }, new Realm.Transaction.OnError() {
            @Override
            public void onError(Throwable error) {
                callback.onError(error);
            }
        });
    }



**here is how I use ResponseCallback**

```
store.bookmark(id, bookmark, feedId, new ResponseCallback() {
            @Override
            public void onResponse(Object o) {
                super.onResponse(o);
                .......do something with the response........
            }

            @Override
            public void onError(Object o) {
                super.onError(o);
                ........handle errors..........
            }
        });
```

**Comment by beeender** [comment]
Decoded call stack.
```
execute_native_thread_routine
/s/ndk-toolchain/src/gcc/gcc-4.9/libstdc++-v3/src/c++11/thread.cc:92
std::terminate()
/s/ndk-toolchain/src/gcc/gcc-4.9/libstdc++-v3/libsupc++/eh_terminate.cc:57 (discriminator 1)
```

It seems something wrong when starting pthread in the native code. 

Is that the whole information you get on the play store console?

**Comment by Prashanth-Nelli** [comment]
yes that is only information I am seeing in the playstore crashes section.

**Comment by beeender** [comment]
With limited information we cannot do too much right now ... Please let us know if you get more information on this issue. Sorry.

**Comment by Prashanth-Nelli** [comment]
Ok, Thank you guys for the help.

**Comment by nhachicha** [comment]
Please reopen if you have more information to share.
