### ISSUE TITLE
RealmRecyclerViewAdapter's getData() returns old data randomly

### ISSUE THREAD

**Issue by sirudog** [realm/realm-java#4971]
Hi, 
I have a problem with RealmRecyclerViewAdapter's getData() method. My RealmRecyclerViewAdapter implements Filterable. MyViewHolder extends RecyclerView.ViewHolder and implements View.OnLongClickListener. The filter part works well, I use  RealmRecyclerViewAdapter's updateData() method to update the data associated to the Adapter, but when I long click on a filtered list item and call RealmRecyclerViewAdapter's getData() method, sometimes it returns the old OrderedRealmCollection data,  sometimes it works and I get the updated data back. I have done a lot of debugging, but I was not able to find the reason. It seems quite random. I have also updated io.realm:android-adapters from 2.0.0 to 2.1.0 and io.realm:realm-gradle-plugin from 3.3.2 to 3.5.0, but it did not fix it.
Can you help me to solve my problem?
Thanks

#### Code Sample

```java

public class WordDAdapter extends RealmRecyclerViewAdapter<WordD, WordDAdapter.MyViewHolder> implements Filterable {
    Realm realm = Realm.getDefaultInstance();
    private Activity mActivity;

    public WordDAdapter(Activity activity, RealmResults<WordD> wordDRealmResults) {
        super(wordDRealmResults, true);

        this.mActivity = activity;
        registerAdapterDataObserver(new RecyclerView.AdapterDataObserver() {
        });
    }

    @Override
    public MyViewHolder onCreateViewHolder(ViewGroup parent, int viewType) {
        View itemView = LayoutInflater.from(parent.getContext()).inflate(R.layout.listview, parent, false);
        return new MyViewHolder(itemView);
    }

    @Override
    public void onBindViewHolder(MyViewHolder holder, int position) {
        final WordD wordD = getItem(position);
        holder.language1.setText(wordD.getMlanguage1());
        holder.language2.setText(wordD.getMlanguage2());
        holder.sampleSentence.setText(wordD.getMSampleSentence());
        if (wordD.getIsSelected()){
            holder.MyListView.setBackgroundColor(ContextCompat.getColor(mActivity, R.color.selected));
            holder.language1.setTextColor(ContextCompat.getColor(mActivity, R.color.colorWhite));
            holder.language2.setTextColor(ContextCompat.getColor(mActivity, R.color.colorWhite));
            holder.sampleSentence.setTextColor(ContextCompat.getColor(mActivity, R.color.colorWhite));
        } else {
            if (position % 2 == 0 ) {
                holder.MyListView.setBackgroundColor(ContextCompat.getColor(mActivity, R.color.colorDivider));
            } else  {
                holder.MyListView.setBackgroundColor(ContextCompat.getColor(mActivity, R.color.colorWhite));
            }
            holder.language1.setTextColor(ContextCompat.getColor(mActivity, R.color.secondary_text));
            holder.language2.setTextColor(ContextCompat.getColor(mActivity, R.color.colorPrimaryLight));
            holder.sampleSentence.setTextColor(ContextCompat.getColor(mActivity, R.color.secondary_text));

        }
    }


    public void filterResults(String text) {
        text = text == null ? null : text.toLowerCase().trim();
        if(text == null || "".equals(text)) {
            updateData(WordDHelper.getActiveWorkbook().getWords().where().findAll());
        } else {
            updateData(realm.where(WordD.class)
                    .contains("mlanguage1", text, Case.INSENSITIVE)
                    .or()
                    .contains("mlanguage2", text, Case.INSENSITIVE)
                    .findAll());
        }
    }

    public Filter getFilter() {
        WordDFilter filter = new WordDFilter(this);
        return filter;
    }

    private class WordDFilter extends Filter {
        private final WordDAdapter adapter;

        private WordDFilter(WordDAdapter adapter) {
            super();
            this.adapter = adapter;
        }
        @Override
        protected FilterResults performFiltering(CharSequence constraint) {
            return new FilterResults();
        }

        @Override
        protected void publishResults(CharSequence constraint, Filter.FilterResults results) {
            adapter.filterResults(constraint.toString());
        }
    }

    @Override
    public int getItemCount() {
        return getData().size();
    }

    class MyViewHolder extends RecyclerView.ViewHolder implements View.OnClickListener, View.OnLongClickListener {

            TextView language1;
            TextView language2;
            TextView sampleSentence;
            private LinearLayout MyListView;


            MyViewHolder(View view) {
                super(view);
                language1 = (TextView) view.findViewById(R.id.language1);
                language2 = (TextView) view.findViewById(R.id.language2);
                sampleSentence = (TextView) view.findViewById(R.id.sample_sentence);
                MyListView = (LinearLayout) view.findViewById(R.id.list_item);

                view.setOnLongClickListener(this);
            }

        @Override
        public boolean onLongClick(View view) {
          int position = getAdapterPosition();
          String selectedWordID = WordDAdapter.this.getData().get(position).getID(); // here getData() returns old data sometimes
           WordD selectedWord =  WordDAdapter.this.getData().get(position);
          WordDHelper.setWorkbookSelected(selectedWord.getWorkbookID());
          WordDHelper.setSelectedWorkbookActive();
            ((MainActivity) mActivity).changeDataset();
            ((MainActivity) mActivity).prepareToolbar(selectedWordID);
            return true;
        }

        @Override
        public void onClick(View view) {

            if (MainActivity.isInActionMode) {
                String selectedWordID = getData().get(getAdapterPosition()).getID();
                ((MainActivity) mActivity).prepareSelection(selectedWordID);
            }
        }
    }
}

```

#### Version of Realm and tooling
Realm version(s): 
io.realm:android-adapters: 2.1.0
io.realm:realm-gradle-plugin: 3.5.0

Android Studio version: 2.3.3

Which Android version and device: 
android 7.1.2, API 25
google pixel XL

**Comment by Zhuinden** [comment]
Please explain what

```

        @Override
        public boolean onLongClick(View view) {
          int position = getAdapterPosition();
          String selectedWordID = WordDAdapter.this.getData().get(position).getID(); // here getData() returns old data sometimes
           WordD selectedWord =  WordDAdapter.this.getData().get(position);
          WordDHelper.setWorkbookSelected(selectedWord.getWorkbookID());
          WordDHelper.setSelectedWorkbookActive();
            ((MainActivity) mActivity).changeDataset();
            ((MainActivity) mActivity).prepareToolbar(selectedWordID);
            return true;
        }
```

this block of code does, especially `changeDataset()` method and also the `WordDHelper` methods

**Comment by sirudog** [comment]
Thanks for the quick reply!

The problem is in this statement: `WordDAdapter.this.getData()`. 
This sometimes gives me an OrderedRealmCollection which is not in sync with the filtered OrderedRealmCollection. The filtering is done in filterResults method:
`updateData(realm.where(WordD.class)
                    .contains("mlanguage1", text, Case.INSENSITIVE)
                    .or()
                    .contains("mlanguage2", text, Case.INSENSITIVE)
                    .findAll())`

When I was debugging it, after `updateData()`, I called `getData()` and it gave me the updated (filtered) data back. After filtering I long click on one of the filtered items, I call the `getData()` in the long click handler, but sometimes it returns old, not filtered data. Most of the times it works though.

What happens after getData() is not relevant to my opinion, but here it is: 
I have a WordD realm object with an ID field. When I long click on a list item, based on the adapter position I want to get the WordD object which is in the clicked list item with this line:
 `WordD selectedWord =  WordDAdapter.this.getData().get(position)`
I also need the ID of this object, so I get it with this line: 
`String selectedWordID = WordDAdapter.this.getData().get(position).getID()`
After these lines, I use `selectedWord ` and `selectedWordID` variables with my WordDHelper class to manipulate the UI (formatting, etc), but the problem happens before we even get here.

**Comment by sirudog** [comment]
After checking the issue further I have found the cause of the problem:
I use `realmrecyclerview.swapAdapter()` method later in my code, which is wrong based on the answer to this stackoverflow issue: https://stackoverflow.com/questions/34758251/recyclerview-doesnt-swap-adapters-onbindviewholder-indexoutofbounds

> Swap between two list will work only if they are of same size, if one of the list is shorter or larger than other your swap will not work as expected, you are getting a assumed result.
> Example: String one = {"1","2"} swap with String two = {"4","8","10"}. you know what will happen the last element will be discarded in the two array as one array does not have the 3rd element.
> Although swapAdapter();, does not show the documentation this is something you can assume.
> The best and fastest way to deal with it is to make a new adapter and assign it to the RecyclerView.

By changing `realmrecyclerview.swapAdapter()` to `realmrecyclerview.setAdapter()` the problem goes away.
Köszönöm a segítséget! ;-)

**Comment by Zhuinden** [comment]
Nice find. I wouldn't have thought of that. Typically I would just use `updateData()` and it would work.
