### ISSUE TITLE
Relationships created by methods of a RealmObject

### ISSUE THREAD

**Issue by Villason** [realm/realm-java#4973]
#### Goal

Realm saves objects created by other realm objects.

#### Expected Results

Simplified code:

```
public class Barcode extends RealmObject{
    public String message;
}

public class Ticket extends RealmObject{
    public Barcode barcode;

    public setBarcode(String message){
        barcode = new Barcode();
        barcode.message = message;
    }
}

// client code:

Ticket ticket = realm.createObject(Ticket.class);
ticket.setBarcode("12345");
realm.insertOrUpdate(ticket);

```

Expectations: the Barcode object is stored automatically, along with the Ticket object.

#### Actual Results

java.lang.IllegalArgumentException: 'value' is not a valid managed object.

It crashes in the proxy created for the Ticket object. The workaround is to pass the Realm inside the Ticket object but that is mean and nasty.

#### Version of Realm and tooling
Realm version(s): 3.5.0

Realm sync feature enabled: no idea. Default.

Android Studio version: 2.3.3

Which Android version and device: Nougat emulator

**Comment by Zhuinden** [comment]
> ticket.setBarcode("12345");

This would not compile, `ticket.setBarcode` expects a `BarCode` and not a `String`.

**Comment by Zhuinden** [comment]
You cannot set an unmanaged object as the linked object of a managed object.

You would need to do `setBarcode(Barcode barcode)` where `Barcode` was also created by `realm.createObject(Barcode.class)`.

**Comment by Villason** [comment]
In the real use case Ticket is an interface so I have to implement
setBarcode with a string parameter. If there is no solution I will need to
pass the Realm to the implementation object.

**Comment by beeender** [comment]
@Villason try this instead:

```
Ticket ticket = new Ticker();
ticket.setBarcode("12345");
realm.insertOrUpdate(ticket);
```

**Comment by bmeike** [comment]
Hey @Villason ,
  It looks like you've got an answer: I'm going to close this issue.  If you have any more questions/problems feel absolutely free to open a new one.  Better yet, ask on [StackOverflow](https://stackoverflow.com/) 
-blake
