### ISSUE TITLE
IllegalStateException: Cannot create asynchronous query while in a write transaction

### ISSUE THREAD

**Issue by DanteAndroid** [realm/realm-java#4974]
```
java.lang.IllegalStateException: Cannot create asynchronous query while in a write transaction in /home/cc/repo/realm/release/realm/realm-library/src/main/cpp/io_realm_internal_Collection.cpp line 310
	at io.realm.internal.Collection.nativeStartListening(Native Method)
	at io.realm.internal.Collection.addListener(SourceFile:490)
	at io.realm.RealmResults.a(SourceFile:149)
	at com.dante.diary.main.MainDiaryFragment.initData(SourceFile:335)
	at com.dante.diary.base.BaseFragment.onActivityCreated(SourceFile:95)
	at android.support.v4.app.Fragment.performActivityCreated(SourceFile:2201)
	at android.support.v4.app.FragmentManagerImpl.moveToState(SourceFile:1326)
	at android.support.v4.app.FragmentManagerImpl.moveFragmentToExpectedState(SourceFile:1528)
	at android.support.v4.app.BackStackRecord.executeOps(SourceFile:753)
	at android.support.v4.app.FragmentManagerImpl.executeOps(SourceFile:2363)
	at android.support.v4.app.FragmentManagerImpl.executeOpsTogether(SourceFile:2149)
	at android.support.v4.app.FragmentManagerImpl.optimizeAndExecuteOps(SourceFile:2103)
	at android.support.v4.app.FragmentManagerImpl.execPendingActions(SourceFile:2013)
	at android.support.v4.app.FragmentManagerImpl.executePendingTransactions(SourceFile:763)
	at com.ncapdevi.fragnav.FragNavController.g(SourceFile:571)
	at com.ncapdevi.fragnav.FragNavController.b(SourceFile:214)
	at com.dante.diary.base.BottomBarActivity.c(SourceFile:103)
	at com.dante.diary.base.BottomBarActivity.a(SourceFile)
	at com.dante.diary.base.BottomBarActivity$$Lambda$3.a(Unknown Source)
	at com.roughike.bottombar.BottomBar.g(SourceFile:793)
	at com.roughike.bottombar.BottomBar.a(SourceFile:773)
	at com.roughike.bottombar.BottomBar.onClick(SourceFile:744)
	at android.view.View.performClick(View.java:5273)
	at android.view.View$PerformClick.run(View.java:21315)
	at android.os.Handler.handleCallback(Handler.java:743)
	at android.os.Handler.dispatchMessage(Handler.java:95)
	at android.os.Looper.loop(Looper.java:150)
	at android.app.ActivityThread.main(ActivityThread.java:5665)
	at java.lang.reflect.Method.invoke(Native Method)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:799)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:689)
```
## version
        classpath "io.realm:realm-gradle-plugin:3.1.3"

**Comment by beeender** [comment]
That is an restriction of adding listeners.
Please just move `RealmResults.addChangeListerner()` out of the transaction block.

**Comment by DanteAndroid** [comment]
Thank you for quick reply. I can't remove `addChangeListener()` coz I'm using it.

```
code:
        diaries = base.findTodayDiaries();
        diaries.addChangeListener(this);


  public RealmResults<Diary> findTodayDiaries() {
        Date today = new Date();
        return realm.where(Diary.class)
                .between("created", DateUtil.getStartOfDate(today), DateUtil.getEndOfDate(today))
                .isNotNull("user")
                .findAllSorted("created", Sort.DESCENDING);


    @Override
    public void onChange(RealmResults<Diary> collection, OrderedCollectionChangeSet changeSet) {
        // `null`  means the async query returns the first time.
        if (changeSet == null) {
            log("no change");
            adapter.notifyDataSetChanged();
            return;
        }
        // For deletions, the adapter has to be notified in reverse order.
        OrderedCollectionChangeSet.Range[] deletions = changeSet.getDeletionRanges();
        for (int i = deletions.length - 1; i >= 0; i--) {
            OrderedCollectionChangeSet.Range range = deletions[i];
            log("no notifyItemRangeRemoved " + range.startIndex + " to " + range.length);
            adapter.notifyItemRangeRemoved(range.startIndex, range.length);
        }

        OrderedCollectionChangeSet.Range[] insertions = changeSet.getInsertionRanges();
        for (OrderedCollectionChangeSet.Range range : insertions) {
            adapter.notifyItemRangeInserted(range.startIndex, range.length);
            if (page == 1) {
                scrollToTop(range.length);
            }
        }
//        OrderedCollectionChangeSet.Range[] modifications = changeSet.getChangeRanges();
//        for (OrderedCollectionChangeSet.Range range : modifications) {
//            log("notifyItemRangeChanged " + range.startIndex + " to " + (range.startIndex + range.length));
//            adapter.notifyItemRangeChanged(range.startIndex, range.length);
//        }
    }
```

**Comment by beeender** [comment]
I mean, just don't call it inside a transaction.
you can do something like:
```
realm.beginTransaction();
diaries = base.findTodayDiaries();
realm.commitTransaction();
diaries.addChangeListener(this);
```

**Comment by DanteAndroid** [comment]
Well, I'm really confused now. Do you mean I should add `realm.beginTransaction();` & `realm.commitTransaction();` for `diaries = base.findTodayDiaries();`?
But what you say is `DONT call it inside a TRANSACTION`

**Comment by beeender** [comment]
queries are allowed inside the transaction, but async query are not ... From `v3.0.0`, all the queries's **LISTENERS** will be triggered by async query in a background thread.

So, just don't call `xxx.AddChangeListener` inside a transaction.

**Comment by Zhuinden** [comment]
The better question is, **why** is the UI thread in write-mode (inside a transaction) when you're creating an adapter.

**Comment by DanteAndroid** [comment]
@Zhuinden Because realm transaction is fast, which is written in official doc.

**Comment by Zhuinden** [comment]
@DanteAndroid not what I meant. Your code does not include where you begin the transaction.

Although now that I've checked the code, the only thing I see is that the `DataBase` class starts transactions, and there is also one more background thread transaction with `base.realm.executeTransactionAsync()`...

I don't see where change listener is added to a RealmResults inside a transaction. That is odd.

@beeender I do not see him using `addChangeListener` on a RealmResults *inside a transaction block*, I wonder how he ended up in one?

**Comment by DanteAndroid** [comment]
@Zhuinden Well I don't quite understand. `diaries` is just the RealmResults, which are able to add a change listener. And query is not asked to be done inside a transaction block, isn't it?
```
      diaries = base.findTodayDiaries();
    
        diaries.addChangeListener(this);
```

**Comment by Zhuinden** [comment]
@danteAndroid it is specifically asked for it not to be in a transaction, that's what the exception says.

**Comment by DanteAndroid** [comment]
@Zhuinden that's really odd. coz I didn't do that

**Comment by beeender** [comment]
`at com.dante.diary.main.MainDiaryFragment.initData(SourceFile:335)`

From the backtrace, this line needs to be moved out of the transaction.

**Comment by DanteAndroid** [comment]
thats just:
```
    public RealmResults<Diary> findTodayDiaries() {
        Date today = new Date();
        return realm.where(Diary.class)
                .between("created", DateUtil.getStartOfDate(today), DateUtil.getEndOfDate(today))
                .isNotNull("user")
                .findAllSorted("created", Sort.DESCENDING);
    }
```
It's not inside the transaction block

**Comment by beeender** [comment]
Isn't it called in `at com.dante.diary.main.MainDiaryFragment.initData(SourceFile:335)`??
Is the transaction started there?

**Comment by Zhuinden** [comment]
@beeender it's not. I've just checked. 😞

**Comment by DanteAndroid** [comment]
@Zhuinden onNext should be happening in io thread

**Comment by beeender** [comment]
@DanteAndroid since you are using: 

```
        realm.beginTransaction();
        // xxx
        realm.commitTransaction();
```
To change the realm, so if anything in between throws an exception, the transaction will not be closed and may cause this issue.

so:
1. Find where does the exception throws. If you can reproduce the issue, this can be easily found by setting a exception breakpoint when any exception throws.
2. Use `Realm.executeTransaction()` throws. This API ensures the transaction will be cancelled if any exception has been thrown during the transaction.

**Comment by DanteAndroid** [comment]
@beeender what if I think I'm not using begin & commitTransaction in that class(MainDiaryFragment)?

**Comment by beeender** [comment]
But you are using it in the `DataBase.java`, right? I checked out your project and did a quick check.

if you have for example `DataBase.clearAll()` in the previous UI loop, and an exception has been caught silently, then you have the Realm instance is still in transaction in the current UI loop. Wouldn't that be possible?

**Comment by DanteAndroid** [comment]
Does that mean using `realm.executeTransaction` is safer?

**Comment by beeender** [comment]
yes, it will prevent you from having a unclosed transaction.

There is actually no magic in the `executeTransaction()`:
```
    public void executeTransaction(Transaction transaction) {
        if (transaction == null) {
            throw new IllegalArgumentException("Transaction should not be null");
        }

        beginTransaction();
        try {
            transaction.execute(this);
            commitTransaction();
        } catch (Throwable e) {
            if (isInTransaction()) {
                cancelTransaction();
            } else {
                RealmLog.warn("Could not cancel transaction, not currently in a transaction.");
            }
            throw e;
        }
    }
```

**Comment by DanteAndroid** [comment]
So I wonder why don't you recommend using executeTransaction in official doc?

**Comment by Zhuinden** [comment]
@DanteAndroid they do, I remember opening the issue about it like a year ago. https://realm.io/docs/java/latest/#transaction-blocks

**Comment by cmelchior** [comment]
We mention it here: https://realm.io/docs/java/latest/#writes, but it could perhaps be clearer.

**Comment by Zhuinden** [comment]
@cmelchior I think the website here https://realm.io/products/realm-mobile-database/ should be changed to show `executeTransaction()` after AS 3.0 comes out to stable and lambda support will be provided by build tools.

**Comment by DanteAndroid** [comment]
You guys helped me a lot. Thx again for your time.

**Comment by cmelchior** [comment]
@Zhuinden Yes, that is a good idea.

**Comment by bmeike** [comment]
Thanks for the input, @DanteAndroid.  We've opened #5018 to update the docs as soon as Android Studio 3.0 is stable.
