### ISSUE TITLE
 java.lang.IllegalStateException: Illegal State: Object is no longer valid to operate on. Was it deleted by another thread?

### ISSUE THREAD

**Issue by projectdmc16** [realm/realm-java#4977]
I have a list of contacts displayed in a recyclerView ,with each contact having a checkbox to get selected .
Whenever i try to delete any contact from the list i get this error.
I referred to all the solutions shared for this previously but none of them helped my problem to get resolved.

 realm.executeTransaction(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {

                RealmResults<BlockedList> rows = realm.where(BlockedList.class).equalTo("phoneNumber", phoneNo).findAll();
                rows.clear();
            }
        });
Android studio version: 2.3.1

Thanks

**Comment by Zhuinden** [comment]
Not enough code. We do not know the adapter code that crashes and how it is initialized.

**Comment by dalinaum** [comment]
Hello @projectdmc16 

Please give us more detail information such as Realm version, Adapter version, full stack trace and etc. With limited information, it is difficult to investigate this problem.

**Comment by bmeike** [comment]
@projectdmc16, we haven't heard from you in a week.  I'm going to close this issue.  By all means, if you are still having issues please open a new issue or, better yet, ask your question on StackOverflow.  We'll get to it post haste.
