### ISSUE TITLE
can not see table in stetho

### ISSUE THREAD

**Issue by Wlazly** [realm/realm-java#4978]
```
compile 'com.facebook.stetho:stetho:1.5.0'
compile 'com.uphyca:stetho_realm:2.0

repositories {  //添加stetho-realm代码仓库地址
    maven {
        url 'https://github.com/uPhyca/stetho-realm/raw/master/maven-repo'
    }
}

 dependencies {
        classpath 'com.android.tools.build:gradle:2.3.2'
        classpath "io.realm:realm-gradle-plugin:3.3.2"

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
```

i have make all configuration, but still not see table in stetho in chrome browser

**Comment by dalinaum** [comment]
Hello @Wlazly 

I think you should modify your `app/build.gradle` instead of `build.gradle` and `compile`s should be in `dependencies` block. Please the following link: https://github.com/uPhyca/stetho-realm#download

**Comment by Wlazly** [comment]
dependencies {
classpath 'com.android.tools.build:gradle:2.3.2'
classpath "io.realm:realm-gradle-plugin:3.3.2"

    // NOTE: Do not place your application dependencies here; they belong
    // in the individual module build.gradle files
}

above I modify it in build.gradle

follow I modify it in app/build.gradle.
compile 'com.facebook.stetho:stetho:1.5.0'
compile 'com.uphyca:stetho_realm:2.0

repositories { //添加stetho-realm代码仓库地址
maven {
url 'https://github.com/uPhyca/stetho-realm/raw/master/maven-repo'
}
}

Does it wrong

**Comment by dalinaum** [comment]
I think `app/build.gradle` should be modified as follows.

```
repositories { 
    maven {
        url 'https://github.com/uPhyca/stetho-realm/raw/master/maven-repo'
    }
}

dependencies {
    compile 'com.facebook.stetho:stetho:1.5.0'
    compile 'com.uphyca:stetho_realm:2.0.0'
}
```

**Comment by Wlazly** [comment]
Yes, i do as you write.  but still can not see table in stetho.

**Comment by zaki50** [comment]
Are you using non-default database name?
If so, could you try `'com.uphyca:stetho_realm:2.1.0'` released yesterday that contains a fix for the issue.

**Comment by Zhuinden** [comment]
I can't believe I didn't find that bug in stetho-realm while I was reading through its code... I guess I was looking elsewhere. :disappointed:

**Comment by bmeike** [comment]
Hey @Wlazly 
Did those suggestions fix your issue?  Since we haven't heard from you in a while, I'm going to assume so.
If you have any further problems, feel free to open a new issue.  Better yet, open a StackOverflow question.  We'll get right on it.

-blake
