### ISSUE TITLE
Query giving wrong result in Realm v3.5.0

### ISSUE THREAD

**Issue by SarthakM9** [realm/realm-java#4982]
**Bugs**: Query working in Realm v3.4.0 but fetching wrong result in v3.5.0

#### Goal
```
// Call this function!
fun fetchResult(): RealmResults<DataClass> {
       return realm.where(DataClass::class.java)
       .greaterThan(COUNT, 0)
       .addConstraint()
       .findAll()
 }

 private fun RealmQuery<DataClass>.addConstraint(): RealmQuery<DataClass> {
        return this.beginGroup()
                .isNotNull(SOME_KEY_1)
                .isNotEmpty(SOME_KEY_1+ "." + SOME_OTHER_KEY_1)
                .endGroup()
                .or()
                .beginGroup()
                .isNotNull(SOME_KEY_2)
                .isNotEmpty(SOME_KEY_2 + "." + SOME_OTHER_KEY_2)
                .endGroup()
}
```
#### Expected Results

> When calling fetchResult(), it should fetch rows which have COUNT > 0

#### Actual Results

>  in Realm 3.5.0, fetching 1 extra result that has COUNT= 0.

#### Steps & Code to Reproduce

> If I try to revert to v3.4.0 the fetched result is correct but then I cannot use linked queries as it was fixed in 3.5.0. i.e: The method addConstraint() crashes the app in 3.4.0 saying "Column not found".

#### Version of Realm and tooling
Realm version(s): ? v3.5.0

Realm sync feature enabled: No

Android Studio version: 2.3.2

Which Android version and device: Moto G2 v6.0

**UPDATE:**
using v3.5.0, If I don't call addConstraint() method, the query fetches correct results!

**Comment by Zhuinden** [comment]
@SarthakM9 can you create a sample project that reproduces this?

**Comment by SarthakM9** [comment]
@Zhuinden ok will try to! :)

**Comment by zaki50** [comment]
I guess `A` and `B` or `C` is equal to  (`A` and `B`) or `C`.

Does adding `beginGroup()` and `endGroup` around `addConstraint()` solve this?

E.g.
```
private fun RealmQuery<DataClass>.addConstraint(): RealmQuery<DataClass> {
        return this.beginGroup()
                .beginGroup()
                .isNotNull(SOME_KEY_1)
                .isNotEmpty(SOME_KEY_1+ "." + SOME_OTHER_KEY_1)
                .endGroup()
                .or()
                .beginGroup()
                .isNotNull(SOME_KEY_2)
                .isNotEmpty(SOME_KEY_2 + "." + SOME_OTHER_KEY_2)
                .endGroup()
                .endGroup()
}
```

**Comment by SarthakM9** [comment]
@zaki50 Yes! It's working! :D
but couldn't understand your explanation, can you please elaborate?

**Comment by dalinaum** [comment]
@SarthakM9 It's good to hear it's working. I'm closing this issue. :)

**Comment by dalinaum** [comment]
@SarthakM9 Sorry. I don't read your comment entirely. 

There are three groups, A, B, and C. 

A)

```
greaterThan(COUNT, 0)
```

B)

```
.beginGroup()
.isNotNull(SOME_KEY_1)
.isNotEmpty(SOME_KEY_1+ "." + SOME_OTHER_KEY_1)
.endGroup()
```

C)

```
.beginGroup()
.isNotNull(SOME_KEY_2)
.isNotEmpty(SOME_KEY_2 + "." + SOME_OTHER_KEY_2)
.endGroup()
```

If you use `A and B or C`, it is processed as `(A and B) or C`, so you should group `B or C` as `A.beginGroup().B.or().C.endGroup()`.

**Comment by SarthakM9** [comment]
@dalinaum yes got it! thanks! :)
