### ISSUE TITLE
why auto-refresh only live in Loop thread or IntentService.

### ISSUE THREAD

**Issue by Wlazly** [realm/realm-java#4983]
If  in internal  it deliver message by Handler？

**Comment by cmelchior** [comment]
We use the Looper/Handler to coordinate events created Realm like change listeners. This gives us a single point in time where we can safely update the Realm data and trigger notifications. 
Without an event queue like the Looper, there would be no good place to trigger these. Nothing really prevents us from using another queue abstraction, but so far no use cases for this have existed on Android.

Does this answer your question?

**Comment by Zhuinden** [comment]
No, it doesn't work in IntentService, because IntentService does not loop.

**Comment by cmelchior** [comment]
@Wlazly I assume the above answered your question. If not, feel free to re-open.
