### ISSUE TITLE
ChangeListener is not being called on RealmObject

### ISSUE THREAD

**Issue by GitHubMurt** [realm/realm-java#4984]
classpath "io.realm:realm-gradle-plugin:3.5.0"

I'm converting objects froming from realm to LiveData (lastly introduced) using extension method

`fun<T: RealmObject> T.asLiveData(realm: Realm) = LiveDataRealmObject(this, realm)`

Belo is how I convert RealmObject from Realm to set them to LiveData
**LiveDataRealmObject::class**
```
class LiveDataRealmObject<T : RealmObject>(private val result: T, realm: Realm) : LiveData<T>() {
    
    private val listener = RealmChangeListener<T> { t ->
        if (t != null && t.isValid)
            realm.executeTransaction {
                value = realm.copyFromRealm(t)
            }

    }

    override fun onActive() {
        result.addChangeListener(listener)
    }

    override fun onInactive() {
        result.removeChangeListener(listener)
    }
}
```
I retrieve results like this.
```
fun getCarDetails(): LiveData<CarDetails> {
        return (mRealm.where(CarDetails::class.java).equalTo(CarDetails.ID, 1).findFirstAsync()).asLiveData(mRealm)
    }
```
And save new one, either override like this
```
fun saveCarDetails(carDetails: CarDetails){
        mRealm.executeTransactionAsync { realm ->
            carDetails.id = 1 // keep only one copy of the object
            realm?.copyToRealmOrUpdate(carDetails)
// listener isn't trigged
        }
    }
```

However listener of LiveDataRealmObject is not called - it is called just one after first results came.
This works if I'would operate on RealmResults by quering .findAllAsync()

**Comment by Zhuinden** [comment]
> it is called just one after first results came.

This is expected behavior, see documentation:

> Similar to findFirst() but runs asynchronously on a worker thread. An listener should be registered to the returned RealmObject to get the notification when query completes. The registered listener will also be triggered if there are changes made to the queried RealmObject. If the RealmObject is deleted, the listener will be called one last time and then stop. **The query will not be re-run.**

You can also see https://github.com/realm/realm-java/issues/4360#issuecomment-288123036 and https://github.com/realm/realm-java/issues/4352#issuecomment-287959676

If you need to observe whether a RealmObject exists, then you'll need to obtain `RealmResults<T>` with `findAllAsync()`

**Comment by GitHubMurt** [comment]
That means copyOrUpdate remove object if it want to updateIt?

**Comment by Zhuinden** [comment]
No, but it means that if the object didn't exist, then `findFirstAsync()` won't return it for you with a change listener **after** it was added.

**Comment by GitHubMurt** [comment]
ok I understand

**Comment by dalinaum** [comment]
Hello. @GitHubMurt 

As @Zhuinden said, this is expected behavior.

I am closing this issue. If you have another idea, feedback, we can discuss it in another issue. Thanks.
