### ISSUE TITLE
Does Realm insert speed lower than SQlite

### ISSUE THREAD

**Issue by Wlazly** [realm/realm-java#4986]
Does Realm insert speed lower than SQlite?

**Comment by dalinaum** [comment]
Hello @Wlazly [Realm is usually faster than SQLite](https://github.com/realm/realm-java-benchmarks#results).

I'm closing this issue. Please feel free to make another issue if you have other issues.

**Comment by Zhuinden** [comment]
Technically, inserts should be on a background thread, and they should be done in as small number of transactions as possible.
