### ISSUE TITLE
Object is not part of the schema for this Realm

### ISSUE THREAD

**Issue by balrampandey19** [realm/realm-java#4988]
```
buildscript {
    repositories {
        jcenter()
        mavenCentral()
        maven { url 'https://maven.fabric.io/public' }
    }
    dependencies {

        classpath 'com.android.tools.build:gradle:2.3.0'
        classpath 'com.google.gms:google-services:3.0.0'
        classpath 'me.tatarka:gradle-retrolambda:3.2.3'
        classpath 'com.jakewharton:butterknife-gradle-plugin:8.7.0'
        classpath 'io.fabric.tools:gradle:1.22.0'
        classpath "io.realm:realm-gradle-plugin:3.3.2"
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.8'
        classpath 'io.fabric.tools:gradle:1.+'
    }
}
allprojects {
    repositories {
        jcenter()
        mavenCentral()
        maven { url 'http://clojars.org/repo' }
        maven { url 'https://oss.sonatype.org/content/repositories/snapshots' }
        maven { url 'https://maven.fabric.io/public' }
        maven { url "https://jitpack.io" }
        flatDir {
            dirs 'libs'
        }

    }
}
task clean(type: Delete) {
    delete rootProject.buildDir
}
```

#### Version of Realm and tooling
Realm version(s): 3.3.2

Realm sync feature enabled: yes

Android Studio version: 2.3

Which Android version and device: 6.0

**Comment by Zhuinden** [comment]
Did you Apply migration for your newly added class?

**Comment by balrampandey19** [comment]
@Zhuinden  it seems like some device issue because this is working on HTC, Samsung and Nexus 5x devices but not working on xiaomi Note 3 device. 
I have also Uninstall the app and re install. but this error always comes on xiaomi device.

**Comment by cmelchior** [comment]
@balrampandey19 Is this from tests locally? Because that error message should never only happen one type of devices. Normally it is a sign that something is wrong in the build process like the annotation processor not being triggered.

Alternative it is a problem with migrations as @Zhuinden points out, which should also the be same across all devices.

**Comment by bmeike** [comment]
@balrampandey19 We haven't heard from you in quite a while.  I hope that's good news; that we've addressed your problem.
I'm going to close this issue.  By all means, if you are still having any kind of problems, feel free to open a new issue.  Better yet, open a StackOverflow question.  We'll get right on it
