### ISSUE TITLE
Android studio Gradle build very slow

### ISSUE THREAD

**Issue by ssunkar** [realm/realm-java#4995]
#### Goal

> What do you want to achieve?
Want android studio to buid gradle faster

#### Expected Results> ?
It should take less than 20 secs (same as other projects without realm)

#### Actual Results
It takes 5 to 10 minutes with realm installed in it

> Describe your current debugging efforts.
I tried enabling Offline Work in Gradle settings

#### Version of Realm and tooling
Realm version(s): ?
1.2.0

Realm sync feature enabled: yes/no

Android Studio version: ? 2.2.3

Which Android version and device: ? Android N, Moto G5 plus (almost all devices)

**Comment by Zhuinden** [comment]
It only takes me that long if Chrome takes up too much of my memory (8 GB RAM)

**Comment by ssunkar** [comment]
I tried closing all the applications, still it takes 5 minutes. It happens on first time building an app.
Is this common to everyone?

**Comment by Zhuinden** [comment]
Only if the project is like 65000+ lines of code, for me anywa

**Comment by ssunkar** [comment]
ohk thanks
