### ISSUE TITLE
realm migration

### ISSUE THREAD

**Issue by ssunkar** [realm/realm-java#5002]
#### Goal

> What do you want to achieve?
successfully installing new apk with changes in Realm object

#### Expected Results
should install app without crash and load all the data from server into realm

#### Actual Results
07-20 12:36:02.571 20760-20760/com.tcrsoftware.android W/System.err: java.lang.IllegalArgumentException: Trying to set non-nullable field 'Name' to null.
07-20 12:36:02.571 20760-20760/com.tcrsoftware.android W/System.err:     at io.realm.JobRealmProxy.realmSet$Name(JobRealmProxy.java:822)
07-20 12:36:02.571 20760-20760/com.tcrsoftware.android W/System.err:     at io.realm.JobRealmProxy.copy(JobRealmProxy.java:1536)
07-20 12:36:02.571 20760-20760/com.tcrsoftware.android W/System.err:     at io.realm.JobRealmProxy.copyOrUpdate(JobRealmProxy.java:1499)
07-20 12:36:02.571 20760-20760/com.tcrsoftware.android W/System.err:     at io.realm.DefaultRealmModuleMediator.copyOrUpdate(DefaultRealmModuleMediator.java:597)
07-20 12:36:02.571 20760-20760/com.tcrsoftware.android W/System.err:     at io.realm.Realm.copyOrUpdate(Realm.java:1599)
07-20 12:36:02.571 20760-20760/com.tcrsoftware.android W/System.err:     at io.realm.Realm.copyToRealm(Realm.java:1055)
07-20 12:36:02.571 20760-20760/com.tcrsoftware.android W/System.err:     at com.tcrsoftware.android.dbservices.JobDB$2.execute(JobDB.java:95)
07-20 12:36:02.571 20760-20760/com.tcrsoftware.android W/System.err:     at io.realm.Realm.executeTransaction(Realm.java:1403)
07-20 12:36:02.571 20760-20760/com.tcrsoftware.android W/System.err:     at com.tcrsoftware.android.dbservices.JobDB.saveJobs(JobDB.java:92)
07-20 12:36:02.571 20760-20760/com.tcrsoftware.android W/System.err:     at com.tcrsoftware.android.fragments.baseactivities.MainMenuActivity.onJobsComplete(MainMenuActivity.java:983)
07-20 12:36:02.571 20760-20760/com.tcrsoftware.android W/System.err:     at com.tcrsoftware.android.tasks.TicketsTask.onPostExecute(TicketsTask.java:696)
07-20 12:36:02.571 20760-20760/com.tcrsoftware.android W/System.err:     at android.os.AsyncTask.finish(AsyncTask.java:660)
07-20 12:36:02.571 20760-20760/com.tcrsoftware.android W/System.err:     at android.os.AsyncTask.-wrap1(AsyncTask.java)

My Model class
   Job.java
   @Required
    public String Name;
    public Boolean IsModified;
RealmSchema schema = realm.getSchema();
schema.get("Job").addField("Name", String.class, FieldAttribute.REQUIRED);

#### Version of Realm and tooling
Realm version(s): ?
3.5.0

Android Studio version: ?
2.2.3

Which Android version and device: ? Android N

**Comment by ssunkar** [comment]
Edit:

I removed @Required for field "Name". It works fine.

Can you please explain 
1) when to use required and

2) when to use RealmObjectSchema.setnullable("field", true) and
RealmObject.setNullable("field", false)

**Comment by Zhuinden** [comment]
`@Required` means its value **cannot be null**

**Comment by dalinaum** [comment]
Hello @ssunkar Good to hear that it works fine. 

There are two links that seem useful.
 * https://realm.io/docs/java/latest/#required-fields-and-null-values
 * https://realm.io/docs/java/3.5.0/api/io/realm/RealmObjectSchema.html#setNullable-java.lang.String-boolean-

I'm closing this issue.
