### ISSUE TITLE
Realm executeTransactionAsync calling new Realm.Transaction.OnError() always

### ISSUE THREAD

**Issue by swaruprs** [realm/realm-java#5004]
Can someone explain what am I missing out!
It calls Realm.Transaction.OnError() instead Realm.Transaction.OnSuccess()

Why?

public class ChatZoomActivity extends AppCompatActivity {

    private void saveDataToRealm(final ItemChatMessages newMessage) {
        Realm mRealm = null;
        try {
            mRealm = Realm.getDefaultInstance();
            RealmAsyncTask atSaveChatMessage = mRealm.executeTransactionAsync(new Realm.Transaction() {
                @Override
                public void execute(Realm realm) {
                    /*Toast.makeText(getApplicationContext(),"Transc",Toast.LENGTH_LONG).show();*/
                    RealmChatMessages chatMessage = realm.createObject(RealmChatMessages.class);
                    chatMessage.setChatMessageId(newMessage.chatDate + newMessage.chatUserName);
                    chatMessage.setChatDate(newMessage.chatDate);
                    chatMessage.setChatText(newMessage.chatText);
                    chatMessage.setChatUserName(newMessage.chatUserName);
                    chatMessage.setChatRoomId("Room1"+"+"+newMessage.chatUserName);

                }
            }, new Realm.Transaction.OnSuccess() {
                @Override
                public void onSuccess() {
                    // Do something
                    /*Toast.makeText(getApplicationContext(),"Success",Toast.LENGTH_LONG).show();*/
                }
            }, new Realm.Transaction.OnError() {
                @Override
                public void onError(Throwable error) {
                    Log.e("Realm error", "Realm error", error);
                    // Transaction failed and was automatically canceled
                    Toast.makeText(getApplicationContext(),"Error",Toast.LENGTH_LONG).show();
                }
            });
        } finally {
            if(mRealm != null) {
                mRealm.close();
            }
        }
    }

    @Override
    protected void onStop() {
        super.onStop();
        if ( atSaveChatMessage != null && !atSaveChatMessage.isCancelled()) {
            atSaveChatMessage.cancel();
        }
    }
}

public class RealmChatMessages extends RealmObject {

    private String chatUserName;
    private String chatText;
    private String chatDate;

    private String chatRoomId;

    @PrimaryKey
    private String chatMessageId;

    public RealmChatMessages() {

    }

    public String getChatUserName() {
        return chatUserName;
    }

    public void setChatUserName(String chatUserName) {
        this.chatUserName = chatUserName;
    }

    public String getChatText() {
        return chatText;
    }

    public void setChatText(String chatText) {
        this.chatText = chatText;
    }

    public String getChatDate() {
        return chatDate;
    }

    public void setChatDate(String chatDate) {
        this.chatDate = chatDate;
    }

    public String getChatRoomId() {
        return chatRoomId;
    }

    public void setChatRoomId(String chatRoomId) {
        this.chatRoomId = chatRoomId;
    }

    public String getChatMessageId() {
        return chatMessageId;
    }

    public void setChatMessageId(String chatMessageId) {
        this.chatMessageId = chatMessageId;
    }
}

public class AppStart extends Application {

    private RealmConfiguration realmConfiguration;

    @Override
    public void onCreate() {
        super.onCreate();

        Realm.init(this);
        realmConfiguration = new RealmConfiguration.Builder().build();
        Realm.setDefaultConfiguration(realmConfiguration);

    }
}

**Comment by cmelchior** [comment]
What is the exception message?

**Comment by swaruprs** [comment]
E/Realm error: Realm error io.realm.exceptions.RealmException: 'RealmChatMessages' has a primary key, use 'createObject(Class<E>, Object)' instead

After adding annotation @PrimaryKey to chatMessageId, forgot to update realm.createObject  

@PrimaryKey
private String chatMessageId;

Solved by: 
RealmChatMessages chatMessage = realm.createObject(RealmChatMessages.class,newMessage.chatMessageId);

Closing it.
Thanks cmelchior
