### ISSUE TITLE
retrieveUserInfo/retrieveUserInfoAsync

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#5008]
User lookup was implemented in https://github.com/realm/realm-java/issues/4828 and https://github.com/realm/realm-java/pull/4882

Unfortunately, some miscommunication happened and 4 bindings actually managed to implement it in 4 different ways :man_facepalming: 

Long story short. We need to deprecate the current `retrieveUser` implementation and implement `retrieveUserInfo()` and `retrieveUserInfoAsync()` instead as described in: https://github.com/realm/product/issues/364#issuecomment-317110948

**Comment by austinzheng** [comment]
Sorry! :( We'll do better next time.

**Comment by cmelchior** [comment]
@nhachicha Has any progress been made on this?

**Comment by nhachicha** [comment]
the initial implementation is here https://github.com/realm/realm-java/tree/nh/user_profile need to be refactored
