### ISSUE TITLE
Async query cannot be created on current thread. Realm cannot be automatically updated on an IntentService thread

### ISSUE THREAD

**Issue by cyph3rcod3r** [realm/realm-java#5009]
I want to update my default realm object from the intent service.

**Comment by Zhuinden** [comment]
IntentService looper doesn't loop, so Realm cannot update it.

**Comment by cyph3rcod3r** [comment]
I got the issue. But I want to do it from that service itself. How can i make it work?

**Comment by Zhuinden** [comment]
I have edited my answer above.

**Comment by cyph3rcod3r** [comment]
Realm.getDefaultInstance().refresh();
        mItem = RealmHelper.getInstance().getTodo(intent.getStringExtra(TodoNotificationService.TODOUUID));
        if (mItem != null) {
            mItem.setState(Constants.NOTE_STATE_ARCHIVED);
            dataChanged();
            RealmHelper.getInstance().saveOrUpdateTodo(mItem);
        }

**Comment by cyph3rcod3r** [comment]
`Realm.getDefaultInstance().refresh();
        pojo = RealmHelper.getInstance().getPojo(id);
        if (pojo != null) {
            RealmHelper.getInstance().saveOrUpdatePojo(pojo);
        }`

you mean this?

**Comment by cyph3rcod3r** [comment]
Ohh Got it, I was trying to query it asynchronously in the intent service. Thanks!

**Comment by Zhuinden** [comment]
Every `Realm.getDefaultInstance()` call needs to be matched with a `realm.close()` call.
