### ISSUE TITLE
inMemory not working for SyncConfiguration

### ISSUE THREAD

**Issue by Maxxan** [realm/realm-java#5015]
#### Goal

I want to create an in memory database when the unit test goes out of scope, it removes the database. I do not want to call "deleteAll" for the database, since I want to keep the online data.

#### Expected Results

Should work with in memory database.

#### Actual Results

It fails to open default instance with the message "Durability setting (as passed to the SharedGroup constructor) was not consistent across the session"

#### Steps & Code to Reproduce

```java
SyncCredentials myCredentials = SyncCredentials.usernamePassword("User", "Password");
SyncUser user = SyncUser.login(myCredentials, "http://server-address/auth");
Realm.setDefaultConfiguration(new SyncConfiguration.Builder(user, "realm://server-address/~/testDB").inMemory().build());
Realm realm = Realm.getDefaultInstance(); // Will fail here
```

#### Version of Realm and tooling
Realm version(s): 3.5.0

Realm sync feature enabled: yes

Android Studio version: 2.3.3

**Comment by beeender** [comment]
It is because of you have a Realm opened before and that Realm has the same path to this one but different "Durability setting".
You could set different `directory` of the `SyncConfiguration` for different test cases. Aslo you can consider to use JUNI4 `TemporaryFolder` to use a new temp folder for every test.

**Comment by Maxxan** [comment]
In the code I tried with 
```
File file = new File(getFilesDir(), randomName);
file.mkdir();
Realm.setDefaultConfiguration(new SyncConfiguration.Builder(user, "realm://server-address/~/testDB").directory(file).inMemory().build());
```
and in a test I tried with 
```
 @Rule
 public TemporaryFolder folder= new TemporaryFolder();
...
Realm.setDefaultConfiguration(new SyncConfiguration.Builder(user, "realm://server-address/~/testDB").directory(folder.getRoot()).inMemory().build());
```
but I get the same error.

**Comment by beeender** [comment]
can you share your whole test file? to help@realm.io if you want to share it privately.
Also, even for testing, `Realm.close()` should be called properly.

**Comment by Maxxan** [comment]
Sure! Here is a project. Look in the main activity.
[RealmTest.zip](https://github.com/realm/realm-java/files/1172711/RealmTest.zip)

**Comment by beeender** [comment]
@Maxxan i got your project and I can run `ExampleInstrumentedTest` successfully. What is the problem? How can I reproduce it?

**Comment by Maxxan** [comment]
The test does nothing, it's in the main activity I added it. "Look in the main activity"

**Comment by beeender** [comment]
@Maxxan thanks a lot!! I can reproduce the issue with your project and it is a bug in our side!!

Test case to reproduce the issue:

```java
    @Test
    public void inMem() throws InterruptedException {
        final RuntimeException[] exception = new RuntimeException[1];
        final SyncUser user = UserFactory.createUniqueUser(Constants.AUTH_URL);
        SyncConfiguration config = configurationFactory.createSyncConfigurationBuilder(user, Constants.USER_REALM)
                .inMemory()
                .build();
        Realm realm = null;
        while (true) {
            try {
                realm = Realm.getInstance(config);
            } finally {
                if (realm != null) {
                    realm.close();
                }
            }
        }
    }
```

@simonask It seems sync client ignore the durability setting in config. Instead it create the Realm with `Durability::Full` always. Is it expected?

**Comment by simonask** [comment]
No, that seems to definitely be a bug. :-)

I'm surprised by it though — we use in-memory Realms in our internal tests. Perhaps the Object Store isn't forwarding the option correctly?

**Comment by sipersso** [comment]
@simonask This still seems to be an issue. Any input on how to setup a synced realm for testing? How do you use in-memory realms in your internal tests?

**Comment by nhachicha** [comment]
@sipersso have you tested with the recent versions of Realm? I couldn't reproduce this issue using `5.4.0` for example. Note that In-memory Realms might still use disk space if memory is running low, but all files created by an in-memory Realm will be deleted when the Realm is closed.

**Comment by sipersso** [comment]
@nhachicha I was using 5.3.1 before, but I upgraded to 5.4.0. No change. I use a nickname user configuration and I am running the test against a realm realm object server instance. The first test it is being used in works. But all subsequent tests fail with the message "Durability setting (as passed to the SharedGroup constructor) was not consistent across the session"

Changing to not using an in-memory realm works without any issues. 

```
val credentials = SyncCredentials.nickname("test", true)
val user = SyncUser.logIn(credentials, testEndPoint)
syncConfiguration = user.createConfiguration(testEndPoint+"/default")
        .inMemory()
        .modules(MyConnectedModule()).build()
```
