### ISSUE TITLE
[Feature Request] Project Lombok integration?

### ISSUE THREAD

**Issue by arcadefire** [realm/realm-java#502]
Hi to all,
first of all, great job. 

I tried to make cooperate Lombok (http://projectlombok.org) and Realm.io together, but the compilation stops when the processor analyzes the annotation (@Getter/@Setter) in classes that integrate Lombok's style. 

It would be nice if the two libraries could coexist. You would have a cleaner code.

**Comment by sirvon** [comment]
+1

**Comment by andrewazores** [comment]
+1

**Comment by spierce7** [comment]
+1

**Comment by sxua** [comment]
Summoning @rzwitserloot in this thread :smiley:

**Comment by mandrachek** [comment]
+1

**Comment by b52** [comment]
What's the state on this one? Lombok solves a real issues you forces us to bear.

**Comment by skptl** [comment]
Any updates on the issue?

**Comment by emanuelez** [comment]
No update on this yet, but we're working on a way to use Realm by manipulating fields instead of accessors. After that is complete we will re-evaluate Lombok support.

**Comment by rzwitserloot** [comment]
Lombok (tries to) execute before other APs so that other APs get to see the changes. If that is not happening, possibly all you really need to do is re-order your classpath. If that still doesn't work, we'll have to investigate.

**Comment by hamen** [comment]
+1

**Comment by mihirjoshi21** [comment]
+1

**Comment by skhaz** [comment]
+1

**Comment by skhaz** [comment]
bump

**Comment by cyberrob** [comment]
Really looking forward to this!

**Comment by kneth** [comment]
Just in case you are wondering if we are getting close, you can take a look at #2196.

**Comment by tuochi** [comment]
+1

**Comment by orubel** [comment]
+1

**Comment by bmunkholm** [comment]
@orubel What are you missing? This is already supported.

**Comment by mariusz-k** [comment]
What type of annotation from Lombok are available ? I try to use @Builder in class and compilation of project crash ?

**Comment by Allsimon** [comment]
Strange, this is working with 1.1.0
```@Data
@Parcel
@Builder
@Wither
@NoArgsConstructor
@AllArgsConstructor
@EqualsAndHashCode(of = "objectId", callSuper = false)
public class RealmUserPost extends RealmObject{```

**Comment by mariusz-k** [comment]
Ok after add :

`@Data
@Builder
**@NoArgsConstructor
@AllArgsConstructor**
@EqualsAndHashCode(callSuper = false)
`
Every thing start work. Thank !
