### ISSUE TITLE
[Sync] Change stop policy to SyncSessionStopPolicy::

### ISSUE THREAD

**Issue by nhachicha** [realm/realm-java#5028]
Current policy for the session is `SyncSessionStopPolicy::Immediately` we should change it to `SyncSessionStopPolicy:: AfterChangesUploaded` to align with other binding and to prevent use cases where the Realm might be deleted before the last changes get synchronised. This can happen when using `logout`which will mark the `SyncUser` and associated Realms to be deleted on the next app launch.
https://github.com/realm/realm-object-store/blob/master/src/sync/sync_user.cpp#L177-L182
https://github.com/realm/realm-object-store/blob/master/src/sync/sync_manager.cpp#L123-L140

**Comment by beeender** [comment]
So if user logged out with Realm instances opened, the session won't be stopped until all Realm instances are closed and all data uploaded to the server?

**Comment by nhachicha** [comment]
If you logout associated sessions will become inactive or not depending on the chosen stop policy  

_from sync_session.cpp_
```C++
void close(std::unique_lock<std::mutex>& lock, SyncSession& session) const override
    {
        switch (session.m_config.stop_policy) {
            case SyncSessionStopPolicy::Immediately:
                session.advance_state(lock, inactive);
                break;
            case SyncSessionStopPolicy::LiveIndefinitely:
                // Don't do anything; session lives forever.
                break;
            case SyncSessionStopPolicy::AfterChangesUploaded:
                // Wait for all pending changes to upload.
                session.advance_state(lock, dying);
                break;
        }
    }
```

in the case of `AfterChangesUploaded` the session will upload the changes before it becomes inactive, if the `SyncUser` is used again all the sessions put on the inactive pool will resume syncing again.

**Comment by beeender** [comment]
Issue reported by user https://stackoverflow.com/questions/45587481/realm-android-when-call-method-realm-close?noredirect=1#comment78192431_45587481

**Comment by cmelchior** [comment]
But syncing will stop immediately no matter what when you logout right? This SyncSessionPolicy just controls what happens when you close the `Realm`

**Comment by beeender** [comment]
Currently even without logging out, syncing will be stopped if all Realm instances are closed. Right?

**Comment by cmelchior** [comment]
Yes. Login/loggedout only determine if you _can_ have an active session, but it is the Realm life cycle that determines if the session exists at all.

**Comment by beeender** [comment]
Yeah, that is actually the problem... since we always teach user to manage the Realm life cycle carefully, but in this case, if user did that, the syncing will actually stop.

**Comment by cmelchior** [comment]
I don't think it is a problem. IMO it makes the mental model a lot simpler e.g. if the session outlives the Realm lifecycle, you will never know when you can delete the file for example.

But I agree that in default use case you would probably want to keep the session alive.

In any case we need to add more controls to `SyncSession` anyway, which will allow for more advanced use cases, like 

```
session.hasLocalChanges();
session.start();
session.stop(); 
// and so on
```

**Comment by cmelchior** [comment]
Fixed by https://github.com/realm/realm-java/pull/5020

**Comment by robsonbbs** [comment]
@cmelchior This solution was released? 
As @beeender said here (https://stackoverflow.com/questions/45587481/realm-android-when-call-method-realm-close) thanks to this issue while using the Synced Realm, local data wouldn't be uploaded to cloud instance if all local instances are closed. Now I am using Realm 5.10.0 and this scenario happens.
