### ISSUE TITLE
Loading Realm Objects on the UI Thread

### ISSUE THREAD

**Issue by mikeholler** [realm/realm-java#503]
In [Using Realm Across Threads](http://realm.io/docs/java/0.71.0/#using-a-realm-across-threads), the documentation states that,

>"The only rule to using Realm across threads is to remember that Realm, RealmObject or RealmResults instances cannot be passed across threads."

In Android (and any other GUI application) it's a big no-no to load/query data on the UI thread. When using SQLite, the convention is to create an AsyncTask in your Activity that populates the UI elements with data from the SQLite database.

With Realm, the documentation actively advises against passing results to from a background thread to a UI thread (as it's considered "across" a thread). I have seen the [RealmConcurrencyExample](https://github.com/realm/realm-java/tree/master/examples/concurrencyExample), but unfortunately it uses two background (non-UI threads). In [RealmGridViewExample](https://github.com/realm/realm-java/tree/master/examples/gridViewExample), the query to the Realm database is made on the UI thread.

My questions about this are:

* Is loading Realm data on the UI thread okay? Are there any disadvantages to doing so?
* If it's not okay to load Realm data on the UI thread, how should I populate my UI elements with Realm data when potentially large queries are involved?
* Would it be possible to update the documentation to explain to developers whether it's okay to load on the UI thread? I would think many other Android developers would be concerned about executing a Realm call on the UI thread without knowing the ramifications.

By the way, you guys have a great product here. I can't wait to see how it grows.

**Comment by vvictor10** [comment]
@cmelchior  @bmunkholm - Passing realm instances and realm objects between threads was mentioned in a couple of threads. Is that something being actively worked on and can we expect to see that coming out in the next couple of versions? Needless to say, that would be a game changer for many folks evaluating Realm as a possible solution.

**Comment by cmelchior** [comment]
Yes, it is being worked on in the core database atm. I doubt it will make it into the next couple of releases though, but it is one of your top priorities.

**Comment by spierce7** [comment]
+1. I keep checking back every few weeks to see if this is done so I can play around with realm.

**Comment by mrleolink** [comment]
So... this thread is still open, it means Realm still doesn't support multi-threading yet?
But how about this example? https://github.com/realm/realm-java/tree/master/examples/threadExample

**Comment by Exaper** [comment]
+1 on new features development. Waiting for non-UI queries too.

**Comment by dkpalmer** [comment]
+1

**Comment by kneth** [comment]
Core issue: https://github.com/realm/realm-core/issues/725

**Comment by sawcioo** [comment]
+1

**Comment by emanuelez** [comment]
Closing in favor of #1208
