### ISSUE TITLE
Why there is no (.JAR) or (.AAR) file available for latest realm. 

### ISSUE THREAD

**Issue by raghul-s** [realm/realm-java#5042]
If my system firewall blocks external 3rd party dependencies like realm, retrofit etc.  I am forced to use (.jar) or (.aar) file.

I am unable to use realm now becuase there is no official. AAR or. JAR file available. 

Version 0.85 jar is available but it is largely outdated. How can I overcome these issues. 

#### Goal

> What do you want to achieve?

#### Expected Results

> ?

#### Actual Results

>  E.g. full stack trace with exception

#### Steps & Code to Reproduce

> Describe your current debugging efforts.

#### Code Sample

```java

> Your code here. Bigger samples should ideally be as separate Android Studio project, 
> in gists/repositories or privately at help@realm.io)

```

#### Version of Realm and tooling
Realm version(s): ?

Realm sync feature enabled: yes/no

Android Studio version: ?

Which Android version and device: ?

**Comment by Zhuinden** [comment]
Well the trick is that Realm is distributed as a Gradle plugin that adds the dependencies and registers the Realm Transformer task. 

Maybe if you have all components compiled locally then you can make Gradle execute it?

**Comment by raghul-s** [comment]
Yes only locally compiled files will work with studio.

**Comment by nhachicha** [comment]
Hi @raghul-s why don't you build Realm [locally](https://github.com/realm/realm-java#building-realm)? 

you can then publish to your local maven repo, using `./gradlew installRealmJava`. 

An alternative way is to copy the Realm dependencies from a machine which is not behind a Firewall
just copy everything under `~/.m2/repository/io/realm/` to your machine behind  the firewall 
(note you need to enable local repo in your Gradle configuration in order to resolve the dependencies locally as well).

Example:
```Groovy
buildscript {
    repositories {
        maven {
            url '/Users/Nabil/.m2/repository/'
        }
        jcenter()
    }
    dependencies {
        classpath 'io.realm:realm-gradle-plugin:3.5.0'
    }
}

allprojects {
    repositories {
        maven {
            url '/Users/Nabil/.m2/repository/'
        }
        jcenter()
    }
}
```

**Comment by raghul-s** [comment]
hi @nhachicha Your solution is a possible one but an issue is behind this. Locally building the project behind firewall or using the entire code base will increase my (.apk) size and codeBase size. My doubt is why (@realm-admin)  Realm developers dropped creating .aar file  for latest builds. Being a popular alternate to sqlite. Due to this issue I am dropping the use of REALM and moving to SQLITE with worry.

**Comment by Zhuinden** [comment]
@raghul-s Realm provides a Gradle plugin so that developers don't need to worry about what dependencies to add, and how to register the Realm-Transformer gradle task (for running the bytecode transformer that replaces field access with proxy method calls).

**Comment by nhachicha** [comment]
Hi @raghul-s we listed the reasons why we switched to the plugin in this blog post back at the time https://blog.realm.io/android-installation-change/
