### ISSUE TITLE
Exception and crash when Realm.Init()

### ISSUE THREAD

**Issue by csi111** [realm/realm-java#5049]
**Bugs**

I've got this crash from Sony G3116 device.

How can I solve this problem?

on the Application.class
```
    @Override
    public void onCreate() {
        super.onCreate();
        LeakCanary.install(this);
        initGlobalApplication();
        Realm.init(this); 
       ....
    }
```

Exception java.lang.UnsatisfiedLinkError: dlopen failed: "/data/data/io.agit/app_lib/librealm-jni.so.3.5.0" is 32-bit instead of 64-bit
java.lang.Runtime.load0 (Runtime.java:897)
java.lang.System.load (System.java:1505)
com.f.a.e.b (SystemLibraryLoader.java:29)
com.f.a.d.c (ReLinkerInstance.java:198)
com.f.a.d.a (ReLinkerInstance.java:136)
com.f.a.c.a (ReLinker.java:70)
com.f.a.c.a (ReLinker.java:57)
io.realm.internal.l.a (RealmCore.java:60)
io.realm.l.a (Realm.java:200)
com.kakao.agit.application.GlobalApplication.onCreate (GlobalApplication.java:113)
android.app.Instrumentation.callApplicationOnCreate (Instrumentation.java:1025)
android.app.ActivityThread.handleBindApplication (ActivityThread.java:5613)
android.app.ActivityThread.-wrap2 (ActivityThread.java)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1640)
android.os.Handler.dispatchMessage (Handler.java:110)
android.os.Looper.loop (Looper.java:203)
android.app.ActivityThread.main (ActivityThread.java:6361)
java.lang.reflect.Method.invoke (Method.java)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:1063)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:924)
Realm version(s): 3.5.0

Realm sync feature enabled: yes

Android Studio version: 2.3.3

Which Android version and device

Manufacturer: Sony
Model: G3116
Board: Unknown
Android API: 24
Android OS: 7.0

**Comment by beeender** [comment]
do you have other native libraries than Realm?

**Comment by csi111** [comment]
Just 1 library added in my project, but the lib is just for voice chat.

**Comment by beeender** [comment]
@csi111 Can you please share your apk file somewhere?

**Comment by csi111** [comment]
You can search 'agit' in GooglePlayStore and download it.
[https://play.google.com/store/apps/details?id=io.agit](https://play.google.com/store/apps/details?id=io.agit)

**Comment by beeender** [comment]
Unfortunately I don't have a rooted phone right now, so I cannot get the apk file from play store :( Could you please send the apk file to help@realm.io? thanks.

**Comment by csi111** [comment]
Today I sent to email with my APK file. Please check your email.

**Comment by beeender** [comment]
@csi111 You are using other native libs than Realm. 

```
.
./x86
./x86/librealm-jni.so
./x86/libpl_droidsonroids_gif.so
./x86/libpl_droidsonroids_gif_surface.so
./armeabi-v7a
./armeabi-v7a/librealm-jni.so
./armeabi-v7a/libpl_droidsonroids_gif.so
./armeabi-v7a/libpl_droidsonroids_gif_surface.so
./armeabi
./armeabi/libpl_droidsonroids_gif.so
./armeabi/libpl_droidsonroids_gif_surface.so
./mips
./mips/librealm-jni.so
./mips/libpl_droidsonroids_gif.so
./mips/libpl_droidsonroids_gif_surface.so
```

Realm doesn't supply an `armeabi` so file for now, but you have `pl_droidsonroids` so files for that. This may cause the issue you reported.

To fix that, you can exclude the `armeabi` for all native libs you are using -- and it will be safe since there should be no device only support `armeabi` in the market.

Also, `mips` can be excluded as well to reduce your apk size. I don't think there are real users using mips Android device :P 

I closing this issue now. thanks for your feedback.

**Comment by csi111** [comment]
Thank you for your answer.
However, I have curious if I remove 'armeabi lib libpl_droidsonroids_gif.so'
in my gradle, doesn't it happen crash any more?

Because I added ndk filter "armeabi", "armeabi-v7a", "x86" in my gradle
option.

Do I also remove filter "armeabi" ? or Doesn't it matter to remove?

defaultConfig {
...
    ndk {
        abiFilters "armeabi", "armeabi-v7a", "x86"
    }



2017-08-09 11:45 GMT+09:00 Chen Mulong <notifications@github.com>:

**Comment by beeender** [comment]
You have to remove `armeabi` from `abiFilters` since Realm doesn't supply `armeabi` so for now. See the section related with `so` files in this article for more details https://academy.realm.io/posts/kenneth-geisshirt-tales-developing-sdks-at-scale/

**Comment by csi111** [comment]
Thank you for your kind.

Have a good day~

**Comment by foxbunlong** [comment]
funny thing is that I faced same problem and after upgrading to newest Realm. It's fixed magically ^_^~
