### ISSUE TITLE
How to store List<Long> with relam? - Question

### ISSUE THREAD

**Issue by lazarvgd** [realm/realm-java#5052]
Hi, how can I store to Realm list of Long's?

For example i have class Person:

Person extends RealmObject{
private List<Long> accountId;
}

Thanks

**Comment by Zhuinden** [comment]
As `String`.

**Comment by idok595** [comment]
store it in json array of integer format as a string the you can parse it from String and to string using GSON library

**Comment by cmelchior** [comment]
Hi @lazarvgd I assume the above answered your question. If not, feel free to reopen.
