### ISSUE TITLE
Duplicate zip entry [classes.jar:io/realm/BaseRealm$1.class]

### ISSUE THREAD

**Issue by vkreal** [realm/realm-java#5054]
Hi, anyone know how we can fix this error below with having duplicate realm? This only occur during our build process.

`(Can't read [/Users/vorunk/.android/build-cache/f0950fea0b476b5e617c9329b00630442fff9eaa/output/jars/classes.jar(;;;;;;**.class)] (Duplicate zip entry [classes.jar:io/realm/BaseRealm$1.class]))`

#### Version of Realm and tooling
Realm version(s): 3.0.0
Realm sync feature enabled: no
Android Studio version: 2.3.1
Which Android version and device: Nexus 5X

**Comment by nhachicha** [comment]
Hi @vkreal can you share your gradle configuration, may be you're there's a transitive dependency that's using Realm, that you need to exclude.

You can also run `./gradlew dependencies` to see your dependencies

**Comment by vkreal** [comment]
@nhachicha first of all thanks for helping! So I ran `./gradlew dependencies` and noticed 6 references to `io.realm` screen below. You think it's causing the duplicate issue?

<img width="879" alt="screen shot 2017-08-01 at 10 45 38 am" src="https://user-images.githubusercontent.com/230700/28838929-c5b0d38c-76a6-11e7-80a5-4df20435eff7.png">

**Comment by Zhuinden** [comment]
That `store-sdk-android` is bringing in Realm 3.0.0 as well.

**Comment by nhachicha** [comment]
What is `platform-sdk-android:approvals-sdk`? try to exclude the transitive dependency to Realm from this dependency 

```gradle
compile('platform-sdk-android:approvals-sdk:2.2.21-test1') {
    exclude group: 'io.realm'
}
```

here I assume the scope of your dependency`platform-sdk-android:approvals` is `compile` please change to other scope if not

**Comment by vkreal** [comment]
@nhachicha Thanks! I will take a look and get back.

**Comment by vkreal** [comment]
@nhachicha awesome it works. Thank you!
