### ISSUE TITLE
Bad Realm file header (#3)

### ISSUE THREAD

**Issue by AlexTip** [realm/realm-java#5063]
Hi there! We've got growing Realm exception (kinda about 17k crashes from about 800 users for the last 30 days) with the next stack trace: 
```
Fatal Exception: io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/data/com.package.name/files/db.realm': Bad Realm file header (#3). (Bad Realm file header (#3)) (/data/data/com.package.name/files/db.realm) in /home/cc/repo/realm/release/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 217
       at io.realm.internal.SharedRealm.nativeGetSharedRealm(SharedRealm.java)
       at io.realm.internal.SharedRealm.(SharedRealm.java)
       at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:237)
       at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:206)
       at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:127)
       at io.realm.Realm.getDefaultInstance(Realm.java:266)
```

Device stats (fairly no pattern): https://prnt.sc/g3ryyh
The only thing to mention is that crashing scenario is happening from new thread invoked from the service.

**Comment by beeender** [comment]
1. What is your Realm version? Does the crash happen to a specific Realm version?
2. Do you use encryption? 
3. Do you open Realm from multiple processes?

**Comment by AlexTip** [comment]
1. Realm version - 3.5.0
2. No
3. No

**Comment by beeender** [comment]
Does it happen when you update the Realm from the older version to `3.5.0`? If yes, what is the old version?

**Comment by AlexTip** [comment]
As far as I can see this crash was persistent for all the time in minor volumes about 10 crashes a day, but when we updated 3.1.4 to 3.4.0 and further the number of crashes started to grow incredibly.

**Comment by beeender** [comment]
Do you use `Realm.compactRealm()`?

**Comment by AlexTip** [comment]
No, the configuration is trivial enough
```
RealmConfiguration.Builder()
                .name(DATABASE_NAME)
                .schemaVersion(DATABASE_VERSION)
                .migration(new Migration())
                .build()
```
No additional features are used

**Comment by beeender** [comment]
Should be the same issue with https://github.com/realm/realm-core/issues/2258 let's discuss there.

**Comment by Zhuinden** [comment]
Technically "bad Realm file header" means corruption, but you currently don't seem to be doing anything that ought to cause corruption.

I guess the next question is:

- how many threads try to start transaction concurrently (shouldn't cause a problem but hey), for example are Realm writes on a dedicated Realm-write-thread, or in AsyncTask/other threadpools

- do you have two or more processes in your app, 

- is there a chance that you have multiple process AND execute migration in multiple processes at once by accident? (for example first Realm is opened inside Application class, and you have two processes)

**Comment by cmelchior** [comment]
@AlexTip Are you compacting your Realm at any point. We are seeing other reports that if it fails it appears to corrupt the original file: #5011

**Comment by cmelchior** [comment]
Closing due to no response.

**Comment by ozv101** [comment]
@cmelchior @beeender im seeing a few of these similiar issues opened and it seems like no one can reproduce them. is this something we're going to have to live with?

**Comment by Zhuinden** [comment]
@ozv101 realm version, error / exception stack trace

**Comment by ozv101** [comment]
@Zhuinden https://github.com/realm/realm-java/issues/5629
