### ISSUE TITLE
Detach Realm from RealmQuery

### ISSUE THREAD

**Issue by VenomVendor** [realm/realm-java#5066]
## Problem statement.
As described in https://stackoverflow.com/q/44035272/1008278
Create a **RealmQuery** in Thread A & pass it across to be executed conditionally in different Thread.
This triggers `IllegalStateException(BaseRealm.INCORRECT_THREAD_MESSAGE);`.
[Solution provided cannot be used, as listeners can be added only if Looper is available](https://stackoverflow.com/a/44043733/1008278) & it is not necessary the result will always update UI.

[RealmQuery.createQuery(this, clazz);](https://github.com/realm/realm-java/blob/5e20952decab2a2f4dda826a06a21a3b93115665/realm/realm-library/src/main/java/io/realm/Realm.java#L1346)
Creates a query binding realm Object tightly to RealmQuery, but the actual usage of realm is required only when query is executed. [createRealmResults](https://github.com/realm/realm-java/blob/5e20952decab2a2f4dda826a06a21a3b93115665/realm/realm-library/src/main/java/io/realm/RealmQuery.java#L1972), [findFirstAsync](https://github.com/realm/realm-java/blob/5e20952decab2a2f4dda826a06a21a3b93115665/realm/realm-library/src/main/java/io/realm/RealmQuery.java#L1936) or similay query. 
As mentioned in doc, RealmQuery is built on builder pattern. Clearly there is no dependency of Realm until execution.

RealmQuery should be detached from Realm & should be able to execute after attaching to Realm.

Ex:
``` java
Query query = Realm.where(clazz); // Query is detached from realm.
 (or)
Query query = Realm.createQuery(clazz); // Realm.prepareQuery();
```
> query[.equalTo(String fieldName, String value)](https://github.com/realm/realm-java/blob/5e20952decab2a2f4dda826a06a21a3b93115665/realm/realm-library/src/main/java/io/realm/RealmQuery.java#L238)[.equalTo(String fieldName, Byte value)](https://github.com/realm/realm-java/blob/5e20952decab2a2f4dda826a06a21a3b93115665/realm/realm-library/src/main/java/io/realm/RealmQuery.java#L271)...

Since the above query is detached from Realm, this can be passed across threads & doesn't cause any harm. This is still a plain Object ready to be executed.

Before execution, Query can attach itself to Realm returning RealmQuery.
``` java
// Below cannot be transmitted across threads.
RealmQuery realmQuery = query.attachWith(realm); // Attaches to realm
RealsResults results = realmQuery.findAll(); // findAllAsync(), findFirst(), findAllSortedAsync(), ...
```

**Comment by Zhuinden** [comment]
> Clearly there is no dependency of Realm until execution.

That's not really true though, [query methods call down to native](https://github.com/realm/realm-java/blob/master/realm/realm-library/src/main/java/io/realm/internal/TableQuery.java#L626-L710) and things get tricky

**Comment by nhachicha** [comment]
Although it looks like a POJO, the `RealmQuery` uses underneath C++ `Table`,`TableView` and accessors which are thread confined.

**Comment by VenomVendor** [comment]
Is it possible to move the operations performed while creating query, to execute before query execution. Detaching realm from query would be greatly helpful.

**Comment by cmelchior** [comment]
Hi @VenomVendor 
Queries sometimes depend on other queries (what we call "constraining views"). This is the reason that Realm Queries not automatically can be transferred across threads as completely separate objects.

E.g. consider

```
Person p = realm.where(Person.class).findFirst(); // Constraining view
RealmQuery<Person> childQuery = p.getChildren().where().equalTo("name", "Peter");
```

In that case you could not transfer `childQuery` because it depends on other state as well.
Note, that we do want to make it possible to transfer queries across threads as this solve other use cases like #1978 . How exactly it is going to look like is not is not determined yet though, but most likely it will be the form discussed here: https://github.com/realm/realm-java/issues/4059

I'll close this as an duplicate, but you can follow #4059 for updates.
