### ISSUE TITLE
Slight documentation error in chapter Threading?

### ISSUE THREAD

**Issue by aschrijver** [realm/realm-java#5071]
#### Goal

> I am reading about Threading to investigate [this Realm SO question](https://stackoverflow.com/q/45530635/8295283) and found a confusing line of text.

#### Confusing text

See: https://realm.io/docs/java/latest/#threading

> Once the background service adds new customers **to the UI**, the customers list is automatically updated in the UI without any additional intervention on your part.

Confusion: So if you update it in the UI, it is updated in the UI???

#### Expected

> Once the background service adds new customers **to the realm database**, the customers list is automatically updated in the UI without any additional intervention on your part.

#### Version of Realm and tooling
Realm version(s): latest

**Comment by Zhuinden** [comment]
I'd just say `to Realm` but you seem to be right.

**Comment by aschrijver** [comment]
I'll PR `to Realm` then, if that's okay.

**Comment by cmelchior** [comment]
Hi @aschrijver Thanks for noticing that. You're right. It looks like a mistake.

**Comment by cmelchior** [comment]
Fix has been merged and should be public shortly

**Comment by aschrijver** [comment]
Thanks a lot @cmelchior !
