### ISSUE TITLE
Can not delete single row from Realm with RxJava

### ISSUE THREAD

**Issue by lordofprograms** [realm/realm-java#5074]
Error:

> Cannot create asynchronous query while in a write transaction in /home/cc/repo/realm/release/realm/realm-library/src/main/cpp/io_realm_internal_Collection.cpp line 320

Delete func:

```kotlin
fun <T : RealmObject> delete(clazz: Class<T>, id: Int): Observable<RealmObject> {
        val realm = Realm.getInstance(config)

        return realm.where(clazz).equalTo("id", id).findAll().asObservable()
                .flatMap { tasks -> Observable.from<RealmObject>(tasks) }
                .doOnError { error -> Log.e("Delete", error.message) }
                .doOnSubscribe{realm.beginTransaction()}
                .doOnUnsubscribe {
                    realm.commitTransaction()
                    realm.close()
                }
    }
```

And using delete func:

```kotlin
holder.delete.setOnClickListener{
            DbService().delete(Task::class.java, position).subscribe{ tasks -> tasks.deleteFromRealm()}
            notifyDataSetChanged()
        }
```

**Comment by Zhuinden** [comment]
You will never call `unsubscribe()` with that setup.

**Comment by zaki50** [comment]
As @Zhuinden said, you need to unsubscribe.

**Comment by lordofprograms** [comment]
I have the same error with this code:

`class HistoryAdapter(val activity: Activity): RecyclerView.Adapter<HistoryAdapter.HistoryItemViewHolder>() {

    private var historyList: ArrayList<Task> = ArrayList()
    val subs = CompositeSubscription()

    fun setList(list: ArrayList<Task>){
        this.historyList = list
    }

    override fun onCreateViewHolder(parent: ViewGroup, viewType: Int): HistoryItemViewHolder {
        val view = parent.inflate(R.layout.item_history)
        return HistoryItemViewHolder(view)
    }

    override fun onBindViewHolder(holder: HistoryItemViewHolder, position: Int) {
        holder.time.text = historyList[position].time
        holder.task.text = historyList[position].task
        holder.delete.setOnClickListener{
            DbService().delete(Task::class.java, position).subscribe{ tasks -> tasks.deleteFromRealm()}
            updateView(activity)
        }
    }

    override fun getItemCount(): Int {
        return historyList.size
    }

    override fun onViewDetachedFromWindow(holder: HistoryItemViewHolder?) {
        subs.unsubscribe()
        super.onViewDetachedFromWindow(holder)
    }

    inner class HistoryItemViewHolder(view: View): RecyclerView.ViewHolder(view){
        val time = view.findViewById(R.id.taskTime) as TextView
        val task = view.findViewById(R.id.taskName) as TextView
        val delete = view.findViewById(R.id.delete) as ImageView
    }

}`

**Comment by Zhuinden** [comment]
***You're not unsubscribing the Delete method, so your transaction will never end.***

**Comment by zaki50** [comment]
You need to unsubscribe the observable in click listener in order to commit the transaction.

**Comment by zaki50** [comment]
I'm closing this because of no response.

Feel free to reopen it when you have further questions.
