### ISSUE TITLE
"Register a callback" in Asynchronous Queries section of Documentation would get GC'd

### ISSUE THREAD

**Issue by Zhuinden** [realm/realm-java#5085]
https://realm.io/docs/java/latest/#asynchronous-queries

``` java
public void onStart() {
    RealmResults<User> result = realm.where(User.class).findAllAsync(); // <---
    result.addChangeListener(callback);
}
```

it should be field variable.

**Comment by zaki50** [comment]
Thanks.
I've created a PR to fix the code in documentation repository.
I'll close this when the PR will be merged.

**Comment by bmeike** [comment]
Will want to do this after Watt's massive re-write...

**Comment by zaki50** [comment]
I've merged the PR into master.
https://realm.io/docs/java/latest/#asynchronous-queries will be updated shortly.
