### ISSUE TITLE
"customers" in "Realm Threading Example" section of Documentation would get GC'd

### ISSUE THREAD

**Issue by Zhuinden** [realm/realm-java#5086]
https://realm.io/docs/java/latest/#realm-threading-example

``` java
// in a Fragment or Activity, etc
@Override
public void onActivityCreated(Bundle savedInstanceState) {
    // ... boilerplate omitted for brevity
    realm = Realm.getDefaultInstance();
    // get all the customers
    RealmResults<Customer> customers = realm.where(Customer.class).findAllAsync(); // <--
```

it should be a field variable.

**Comment by zaki50** [comment]
`customers` should be owned by adapter.
So, I don't think `customers` should be a field.

**Comment by Zhuinden** [comment]
True! In that case, I think for the sake of example, there shouldn't even be an `adapter.notifyDataSetChanged()` call because that should be handled by `RealmBaseAdapter`/`RealmRecyclerViewAdapter`, just calling some unshown method called `updateUi()` would work better I think.

Either way, local variable + change listener for async query is not GC-friendly.

**Comment by zaki50** [comment]
I've created a PR to update the code.
