### ISSUE TITLE
[Sync] Provide migration to new OS Realm path

### ISSUE THREAD

**Issue by nhachicha** [realm/realm-java#5097]
The ObjectStore changed the location where it stores the local sync file https://github.com/realm/realm-object-store/pull/497

>  Local copies of synced Realms are now stored in a directory based on a locally assigned UUID, rather than the user identity

if we want to align with this behaviour, we need to refactor from the current implementation which uses the user identity only `/data/data/io.realm.test/files/realm-object-server/user-identity/user-identity`

Until this is fixed the deleting the Realm after the `SyncUser` logout and restart the app won't work, since the OS delete method assume the Realm location is using the new `local_uuid`

**Comment by nhachicha** [comment]
also related to https://github.com/realm/realm-object-store/issues/515 to be clarified

**Comment by nhachicha** [comment]
potentially blocked by https://github.com/realm/realm-object-store/issues/515

**Comment by cmelchior** [comment]
In `v10` Realms are now stored as `<appId>/<globalUserId>/<partitionValue>.realm`. Closing as outdated.
