### ISSUE TITLE
@SerializedName not working

### ISSUE THREAD

**Issue by alphaDroid89** [realm/realm-java#5099]
Hi,

I have tried to insert a data from .json file (the size great than 15MB) which is located in mobile storage.  The file has minimum 20K records. To insert the values in realm database i used `realm.createAllFromJson(MyTestModel.class, stream);`. 

The sample Json looks like 
`[{
	"No": "CB3425",
	"Name": "Alpha",
	"IndividualID": "HUI2945",
	"FirstName": "Alpha",
	"LastName": "Beta"
}]`

I created a Model class which off course I extends RealmObject. While i'm try to insert this code in database i got the exact size of total records, but there is no values inside it. Yes, all the values are Null.

i converted all json keys to lower case, then i tried to insert in database, all values are inserted without any issue.
`[{
	"no": "CB3425",
	"name": "Alpha",
	"individualid": "HUI2945",
	"firstname": "Alpha",
	"lastname": "Beta"
}]`

So in my model class i tried with GSON's annotation  @SerializedName its not working it throws null value. Kindly guide me how can i change the keys it too lowercase while i'm creating ModelClass or any other solution i need to follow.

FYI - i referred this URL https://github.com/realm/realm-java/blob/master/examples/jsonExample/src/main/java/io/realm/examples/json/JsonExampleActivity.java

Thanks in advance.

**Comment by zaki50** [comment]
Hi @alphaDroid89 

Currently we don't support `@serializedname` annotation.

You need to convert the JSON string before passing it to `createAllFromJson()` or create `MyTestModel` instance by using GSON and then pass it to `insert()` or `copyToRealm()`.

**Comment by Zhuinden** [comment]
Using a prefilled Realm file with `assetFile()` could be a better option.

**Comment by zaki50** [comment]
@alphaDroid89 As @Zhuinden said, using https://realm.io/docs/java/3.5.0/api/io/realm/RealmConfiguration.Builder.html#assetFile-java.lang.String- is much easier and faster.

**Comment by zaki50** [comment]
I'm closing this issue. If you have further questions, feel free to reopen this.

**Comment by alphaDroid89** [comment]
@zaki50 Thanks for the quick reply. As i mentioned my file is too big, by this approach i need to copy my file from sdcard to assest folder than parse. 

I changed my with all small case, its saved me as of now. Can you please add these serialization like feature with out two level of process (In my case).

Thank you so much @zaki50 @Zhuinden :)
