### ISSUE TITLE
Try new dex compiler (D8)

### ISSUE THREAD

**Issue by zaki50** [realm/realm-java#5100]
https://android-developers.googleblog.com/2017/08/next-generation-dex-compiler-now-in.html?m=1

**Comment by zaki50** [comment]
dex compiler is only used in application project.
Closing this PR.

**Comment by cmelchior** [comment]
Perhaps we should just enable it for your example projects?

**Comment by zaki50** [comment]
@cmelchior I think so. I already enable it on agp-3.0 PR https://github.com/realm/realm-java/pull/4899/commits/5ffa933163dddc61ea78c9c2482cdface5482b72

**Comment by cmelchior** [comment]
D8 is now running in our `newsReaderExample`
