### ISSUE TITLE
Adding Support for XML

### ISSUE THREAD

**Issue by ErfanThinker** [realm/realm-java#5108]
Hey there,
I crossed a problem and I guess a new feature should be added to realm. consider this XML:
```{
   "Content":{
      "ContentDetail":[
         {
            "FileName":"test.mp3",
            "ContentTypeID":3,
            "ContentDetailMetadata":{
               "Metadata":[
                  {
                     "ID":2,
                     "Value":"2017-08-02 09:40:30"
                  },
                  {
                     "ID":1,
                     "Value":"35.73876557934912,51.50785446166992"
                  }
               ]
            }
         },
         {
            "FileName":"2.jpg",
            "ContentTypeID":2,
            "ContentDetailMetadata":[
               {
                  "Metadata":{
                     "ID":2,
                     "Value":"2017-08-02 09:40:30"
                  }
               },
               {
                  "Metadata":{
                     "ID":1,
                     "Value":"35.73876557934912,51.50785446166992"
                  }
               }
            ]
         }
      ]
   }
}
```
 in which all nodes except Content can exist or be 1 of them or more than one of them. mapping this to Json and createObjectFromJson() won't work since it produces JsonObject or JsonArray base on number of sub-nodes. if there was a method like createObjectFromXML() which would handle this problem would be very nice.

[Related SO Question.](https://stackoverflow.com/questions/45678292/realm-cant-create-nested-objects-from-json/45690907?noredirect=1#comment78340708_45690907)

**Comment by cmelchior** [comment]
That sounds like a problem with your `XML` -> `JSON` parser? If the parser creates `object` when there is only 1 item, but `array` if multiple exists. Ideally, any parser should follow the XSD if such a one exists for your XML?

We have talked about adding XML support to Realm, but the use case comes up so infrequently that I don't think we can give it a high priority any time soon.

**Comment by cmelchior** [comment]
However, It is a use case we are considering and it is included in our general thoughts for an import/export API: https://github.com/realm/realm-java/pull/3758

I'll fold this issue into that, but you can follow #3758 for updates
