### ISSUE TITLE
Create an Android library depending on Realm

### ISSUE THREAD

**Issue by GauthierButel** [realm/realm-java#511]
Hello Realm,

First of all, let me say that I find that you're doing a great work with Realm, which is really an elegant solution for database management. So keep up the good work!

I'm facing an issue, which is most a question regarding a limitation I found on Realm.

I'm trying to build an Android library integrating Realm, so that several Android applications can use a common data model system, thanks to this library.
The use case I want to achieve is that the developer of the application can have its own Realm database and can integrate the library which will deal with the common data model system at the same time.

Unfortunately, when trying to do so, I encounter the following error:
UNEXPECTED TOP-LEVEL EXCEPTION:
com.android.dex.DexException: Multiple dex files define Lio/realm/ValidationList; 

My understanding is that Realm creates this ValidationList class according to the classes that extend RealmObject inside the project, and so there is a ValidationList class created for the library and another one created for the application, which result in this Multiple dex files define error.
I also understand that the ValidationList has to be created at a unique location, inside the io.realm package.

So, my question is: is this a known limitation for Realm? Can we consider the use case feasible in a future version of Realm?

Once again, congratulations for the work done so far with Realm: it's very easy to understand and use!

Thanks,

Gauthier

**Comment by tbsandee** [comment]
I found this enhancement already open after preparing this repro in github, so might as well share it in case it's helpful:

https://github.com/tbsandee/realm-lib-app-failure.

Would love to see first-class support for using realm in a library and app together, but until then we will just move the realm support our of our library projects and push them up to the app.

**Comment by cmelchior** [comment]
This will be part of #938

**Comment by Zhuinden** [comment]
Asking because of http://stackoverflow.com/questions/39101265/how-to-create-android-library-that-depends-on-realm#39101265

Has anything regarding the usage of Realm in libraries changed because of the switch to a Gradle plugin in 0.88.0 ?
