### ISSUE TITLE
Large transaction on HandlerThread blocks transactions on UiThread but not itself?

### ISSUE THREAD

**Issue by methelas** [realm/realm-java#5111]
#### Goal

> Login second user from UiThread after first user was fully synchronized on background thread

#### Description

When I'm logging user in my application I do it like this:

```
Api.get().login(username, password)
.subscribeOn(Shcedulers.io)
.observeOn(AndroidSchedulers.mainThread())
.subscribe(new Subscriber<User>() {
            @Override
            public void onCompleted() {
               notifyThatItFinished();
            }

            @Override
            public void onError(Throwable e) {
                e.printStackTrace();
                notifyItFailed();
            }

            @Override
            public void onNext(User user) {
                Realm realm = Realm.getDefaultInstance();
                realm.executeTransaction(
                new Realm.Transaction() {
                    @Override
                    public void execute(Realm realm) {
                        LoggedUserRealmAPI.addOrUpdate(realm, user);
                    }
                });
                realm.close();
            }
        });
```

After that, an ongoin HandlerThread receives a series of messages telling it to synchronize this user data. Synchronizations are performed in exact order in which they were received(I can see it in logs).
When user is logged, around 10 messages are sent to synchronize different parts of his data.
Every single one of them works. Data is synchronized, written to realm and the results are visible in UI when realmChangeLIsteners are notified about new data.

But... after that when I try to login another user. The call above gets stuck inside transaction. As if there is another one going. But if it was the case, the progress spinner should freeze right? Since transaction is performed on UiThread?
What really happens is that transaction gets stuck for about 1 or 2 min. Progress spinner still spins like nothing is freezed. Then after about 2 minutes a breakpoint ive set on realm.close() is called, user gets logged in and everything is fine.

From my investigation, it turned out that one of the synchronizations causes it. But... its not the last or first synchro, its about the 5th in the queue. In logs I can see that other synchronizations after that were not blocked, and in UI I can see all the data synchronized in any of the syncs. Yet the issue occurs.

The 5th synchro is responsible for syncing users travel data. For certain users its about 60-100 objects with references to other objects present in realm way before that. Since I can see the results correctly and browse through them I assume that the whole transaction was finished properly and all references are there.

When the 5th synchro has small amount of data the issue disappears, another user can log instantenously.

Any ideas, why large transaction on HandlerThread causes this login transaction to take so much time, even when its already finished(HT transaction)?
I'm trying to solve it for 2 days now, and I'm slowly losing my mind :/

I made sure that nothing else is occupying realm transaction in mean time.

#### Version of Realm and tooling
Realm version(s): 3.5.0

Realm sync feature enabled: no

Android Studio version: 2.2.2

Which Android version and device: OnePlus 3, but it occurs on other devices aswell

**Comment by Zhuinden** [comment]
>  it turned out that one of the synchronizations causes it. But... its not the last or first synchro, its about the 5th in the queue.

Code is relevant for this.

**Comment by methelas** [comment]
> Code is relevant for this.

The messages are sent like this. 
SYNCHRO is an enum, it just determines which case from switch() statement in synchronize() method will run.
```
    public void postSynchronizations(final Integer userId, final Synchronizer.SYNCHRO... synchros) {
        for (Synchronizer.SYNCHRO synchro : synchros)
            postSynchronization(userId, synchro);
    }

    private void postSynchronization(final Integer userId, final Synchronizer.SYNCHRO synchro) {

        Message message = new Message();
        message.obj = synchro;
        message.what = userId;

        handler.sendMessage(message);
    }
```

This is the handler which handles the messages. Its a handler created with Looper received from getLooper() in HandlerThread.
```
handler = new Handler(getLooper(), new Handler.Callback() {
            @Override
            public boolean handleMessage(Message msg) {
                try {
                    synchronize(msg.what, (Synchronizer.SYNCHRO) msg.obj);
                } catch (Exception e) {
                    e.printStackTrace();
                }

                return true;
            }
        });
```

And below you can see an example of actual synchronization method.
Every single one of them is the same, the only thing thats different is the data returned from endpoints and the size of it.
```
Api.get().FooSynchro()
                .subscribe(new Subscriber<Foo>() {
                    @Override
                    public void onCompleted() {
                    }

                    @Override
                    public void onError(Throwable e) {
                        e.printStackTrace();
                    }

                    @Override
                    public void onNext(final Foo foo) {
                        realm.executeTransaction(new Realm.Transaction() {
                            @Override
                            public void execute(Realm realm) {
                                FooRealmAPI.addOrUpdate(realm, foo);
                            }
                        });
                    }
                });
```

As I mentioned above, the problem-causing synchro is being executed 5th out of 10.
All synchros after that are also executed, so nothing is being blocked.
And it only causes the issue when the data is big,


*realm* is a single realm instance, opened when the thread starts, its shared by all the synchros, and closed when the thread dies(exiting app)

**Comment by methelas** [comment]
What I already tried:
1. Openening new realm instance for every synchronizator before transaction, and closing right after it
2. Dividing 5th synchro data to smaller parts, and adding it in several smaller transactions
3. subscribing/observing on Schedulers.immediate() just to be sure
4. posting it as runnable, not message
5. putting refresh everywhere(including the realm instance for login call)

**Comment by cmelchior** [comment]
Note, that transactions are blocking across all threads, including the one running the synchronization. This means that transactions on the UI thread is a _very_ bad idea if you use the Realm Object Server.

Secondly, if you are doing transactions on the UI thread, you are also running the code for triggering notifications on the UI thread. Some certain types of model classes (with circular references) can cause our change detecting algorithm to become very slow. If this is the case or not depends on your model classes and your data.

As a first step, I would try to move all your writes to a background thread.

**Comment by beeender** [comment]
I am closing this issue now. Please let us know if you still need help on this.

**Comment by methelas** [comment]
@cmelchior helped me to pinpoint the exact issue. I had some circular references in my models and after removal of those everything started to work as intented
Thanks!!
