### ISSUE TITLE
Realm change listener on RealmResults not always firing

### ISSUE THREAD

**Issue by ericmaxwell2003** [realm/realm-java#5112]
Came across an issue with a user running `Client 3.5.0`, `ROS 1.8.2`.

1.  They run a query for which they expect no results initially.
```// Query
realmResultsFromRealm1 = realm1.where(SomeRealm1Model.class).equalTo("id", id).findAll();
```

2.  They attach a change listener to those results because they expect there will be a record that matches soon
```// Add change listener
realmResultsFromRealm1.addChangeListener(new RealmChangeListener<RealmResults<SomeRealm1Model>>() {
        @Override
        public void onChange(RealmResults<SomeRealm1Model> updatedSomeRealm1Models) {
              // Sometimes fires, sometimes not this is the issue
        }
});
```

3.  In a separate realm they write an object, which triggers a Global Notifier process, which in turns writes a `SomeRealm1Model` object to the `realm1` which will match what they queried for in step 1.  This usually triggers the change notification listener to fire, but not always.
```
realm2.executeTransaction(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {
            realm.createObject(DifferentRealm2Model.class, <someIdVal>);
});
```
When the results listener doesn't fire, I don't mean delayed.. it never fires.  If they back out of the activity with the back button, and then go back into it, the data is present in the query of step 1.  This makes me think that there is nothing wrong with their query.  I just seems like we're dropping the changeListener notification sometimes. 

**Notes**
- No errors in logs.  
- All three steps happen synchronously on the main thread (in the same method even).
- Both realms, and the realm results involved are class member variables.
- I am working to reproduce locally.

**Comment by Zhuinden** [comment]
I think this might be related to https://github.com/realm/realm-java/issues/4878 which I closed saying "if I turn it asynchronous then it works", but I'm not sure that's correct that way.

I could not reproduce it reliably and gave up on it, but I'm sure it is there.

**Comment by ericmaxwell2003** [comment]
Interesting.. Thanks @Zhuinden.  I will see if switching to async works around the issue for now.

**Comment by ericmaxwell2003** [comment]
Sadly, I too cannot reproduce locally.  It works like a charm.  I will follow up with the user today and see if async seems to improve or if there is something else going on.

**Comment by Zhuinden** [comment]
My theory was that if you create a RealmResults with `findAll()` somewhere between `commitTransaction()` (bg thread) and notification delivery, then that `RealmResults` won't be called even if it has changed.

But I couldn't prove it - when I was logging and debugging everything, the bug just didn't come up.

**Comment by cmelchior** [comment]
Interesting. We would probably need a way to reproduce this to get any idea where to start, but it does sound like there is a problem somewhere.

@ericmaxwell2003 It sounds like in your case they expect the initial result to be empty and then it would fill with data. Was that the same case with your @Zhuinden ?

**Comment by Zhuinden** [comment]
@cmelchior technically I had my `findAll()` in essentially `onCreateView()` bound to a `RealmRecyclerViewAdapter`, and I made a change in another fragment, then navigated back to the previous fragment. The previous fragment still showed outdated data, which was rather odd.

I had additional complexity because my RealmResults was on a background looper thread. This is partly why I kinda gave up on it at the time. But I think the RealmChangeListener *should* have been called, it seems to work as I intended with async query.

**Comment by ericmaxwell2003** [comment]
In my case, I couldn't reproduce locally (with the same setup) after many attempts yesterday.  

So, I talked with the developer more and it turns out there was another spot in his codebase that sometimes removed allChangelisteners() on that class member `realmResultsFromRealm1`.  He didn't realize that there were any other references to it during our initial conversations. 

@cmelchior - I'll close this issue since there is already one open from @Zhuinden regarding his issue.

**Comment by Zhuinden** [comment]
@ericmaxwell2003 I had closed my issue, you should keep this issue open.

**Comment by mecoFarid** [comment]
I have tried the exact pattern as OP posted (from official docs) and it still doesn't work on synchronous queries.
