### ISSUE TITLE
Commiting transaction slow

### ISSUE THREAD

**Issue by mgohin** [realm/realm-java#5114]
Hi there,

I'm using Android Realm 3.3.1. I load a csv with 800k lines into Realm.
To do so I parse the csv, map each line into a Java bean (with a `Pools.SynchronizedPool`) and inserting every 1000 records into a transaction block.

Here is the block (`timeCounter.getStep()` is giving me elapsed time since the `TimeCounter.get()`)

```java
final TimeCounter timeCounter = TimeCounter.get();
realm.executeTransaction(new Realm.Transaction() {
    @Override
    public void execute(Realm realm) {
        realm.insert(items);
        long delayToInsert = timeCounter.getStep();
        log.debug("Saved %d items in %d ms", items.size(), delayToInsert);
    }
});
log.debug("Commit transaction in %d ms", timeCounter.getStep());
```
Here is the result after a while (around 100k inserted) :

    Saved 1000 items in 351 ms
    Commit transaction in 1180 ms

The insert always takes 300~500ms but the transaction commit is getting bigger and bigger with time. It starts around 500ms (just a bit more than the simple insert), but ends more than 3000ms.

You can see that the monitoring is fine
![image](https://user-images.githubusercontent.com/3430304/29371208-05163c1c-82a8-11e7-9975-29e115e43fab.png)

So I'm a doing something wrong ?

Edit : I tried async transaction, it's worse
Edit2 : Removing `@PrimaryKey` from the Java Bean helps a lot, but still, transactions commit time is going up slowly (800ms after 250k inserted)
Edit3 : No `@PrimaryKey`, inserting 880k with batch of 5000, starting at 1900ms, finishing at 3000ms. It's better but not perfect. Still looking for a solution, our csv will grow up

**Comment by cmelchior** [comment]
From a quick glance, it looks about as efficient as it can get, but I would try to insert more than 1000 items pr. transaction.

Apart from that, it is hard to know if the times are reasonable or not. It will depend heavily on the hardware. What device are you testing on? As you noticed, If there is a primary key it will slow down over time as we need to check if each item is already present.

**Comment by mgohin** [comment]
Thanks.

I'm aware about that `@Index` or `@PrimaryKey` will slow any request, it's ok.
I'll try to insert more than 1000, but I don't have any clue about the amount I can insert in one transaction to be efficient.
I'm working on very recent devices, even on my phone (One+ 3T).

**Comment by mgohin** [comment]
Any chance to deactivate indexes for a `RealmObject` and then reactivate it ? I guess not, I did not found anything about that.

**Comment by cmelchior** [comment]
@mgohin You can do it through a migration, but if you want to do it in the same app version, then you need to use `DynamicRealmObject` which is a lot slower than our normal typed access, so any savings would probably be lost.

**Comment by mgohin** [comment]
Ok. So I'll not :D
Any clue about the insert time getting bigger with time event without indexes?

**Comment by cmelchior** [comment]
Regarding batch size. The reason people normally batch is because they would otherwise OOM in Java. I don't know much your 800K objects are in terms of Java memory, but I suspect that 1K is a really conservative number. Realm will convert that java memory to native memory usage during a transaction, but since most devices have _a lot_ more native memory than Java, you can normally have everything inside one transaction unless you are talking 100's of MB.

So if you are concerned about running out of memory in Java I would recommend trying to stream the data inside a transaction. Note that transactions are blocking across all threads though, so if other parts of the app are writing during this it could get delayed quite a bit.

Regarding the insert time getting bigger, I would need to see the full Realm model class to speculate on that.

**Comment by mgohin** [comment]
I'll not do a single transaction, it's about 30min of import now, I wish to do some retrieve, that's why I batch inserts. I'll try with 10k.
Android apps are memory limited, so I can't load 800k with peace of mind :D

You can speculate on my beans. I use Lombok, and I use `Pools.SynchronizedPool` to keep memory as low as possible.

```java
@Getter
@Setter
public class ArticleEntity extends RealmObject {

    @Getter(AccessLevel.NONE)
    @Setter(AccessLevel.NONE)
    private String id;

    @Getter(AccessLevel.NONE)
    @Setter(AccessLevel.NONE)
    private String type;

    private Boolean sterilizable;
    private Boolean active;
    private Date importModified;
    private RealmList<ArticlePNEntity> partNumbers = new RealmList<>();
    private RealmList<ArticleCodEntity> codifications = new RealmList<>();

    public UUID getId() {return id == null ? null : UUID.fromString(id);}
    public void setId(UUID id) {this.id = id == null ? null : id.toString();}
    public ArticleType getType() {return type == null ? null : ArticleType.valueOf(type);}
    public void setType(ArticleType type) {this.type = type.name();}


    @Ignore
    private static final Pools.SynchronizedPool<ArticleEntity> sPool = new Pools.SynchronizedPool<>(LoadArticlesTask.ARTICLE_BATCH_MAX_SIZE);

    public static ArticleEntity obtain() {
        ArticleEntity instance = sPool.acquire();
        return (instance != null) ? instance : new ArticleEntity();
    }

    public void recycle() {
        id = null;
        type = null;
        manufacturer = null;
        sterilizable = null;
        active = null;
        importModified = null;
        for (ArticlePNEntity partNumber : partNumbers) {
            partNumber.recycle();
        }
        for (ArticleCodEntity codification : codifications) {
            codification.recycle();
        }
        partNumbers.clear();
        codifications.clear();
        sPool.release(this);
    }
}


@Getter
@Setter
@RealmClass
public class ArticlePNEntity implements RealmModel {

    private String pn;
    private String npn;

    public ArticlePNEntity() {}

    @Ignore
    private static final Pools.SynchronizedPool<ArticlePNEntity> sPool = new Pools.SynchronizedPool<>(LoadArticlesTask.ARTICLE_BATCH_MAX_SIZE * 10);

    public static ArticlePNEntity obtain() {
        ArticlePNEntity instance = sPool.acquire();
        return (instance != null) ? instance : new ArticlePNEntity();
    }

    public void recycle() {
        pn = null;
        npn = null;
        sPool.release(this);
    }
}


@Getter
@Setter
@RealmClass
public class ArticleCodEntity implements RealmModel {

    private String type;
    private String value;

    public CodType getType() {return type == null ? null : CodType.valueOf(type);}
    public void setType(CodType type) {this.type = type == null ? null : type.name();}

    @Ignore
    private static final Pools.SynchronizedPool<ArticleCodEntity> sPool = new Pools.SynchronizedPool<>(LoadArticlesTask.ARTICLE_BATCH_MAX_SIZE * 10);

    public static ArticleCodEntity obtain() {
        ArticleCodEntity instance = sPool.acquire();
        return (instance != null) ? instance : new ArticleCodEntity();
    }

    public void recycle() {
        type = null;
        value = null;
        sPool.release(this);
    }
}

**Comment by cmelchior** [comment]
30 minutes? 😱 
I just talked to our Core team and they say that insertion isn't constant and it would probably be more like `O(log(n))`, but 3 seconds to insert 5000 items sounds doesn't sound right.

What kind of hardware are you testing this on?

**Comment by mgohin** [comment]
Honeywell CT50 2Go RAM
Android 6.0.1

**Comment by cmelchior** [comment]
From your description inserting the data is more or less constant time, but committing the data is what increases. Realm will do some extra work during commit (re-allocate, expand filesize, etc.), but how slow that is will be dictated by the underlying filesystem.

So without more profiling of the native code, it is hard for me to say, but I'm not entirely clear how this could take 30 minutes? Some quick math shows that 800K items should take 8 minutes if each 5K block took 3 seconds?

A few questions/ideas:

1) Are you saving the Realm on SD Card (external disk) or internally.
2) Have you tried running the same code on your laptop (Genymotion/Emulator)?
3) Are the Honeywell running any security software like device management etc. that monitors your filesystem?

**Comment by mgohin** [comment]
Ok so removing Pools free a lot of time, recycling objects was very time consuming, I'll leave GC doing it's work.
I got the timing you calculate now (my timings were not considering object recycle).

It's way better now 👍 

The only piece of code you would need is that one I guess (I had to obfuscate it a bit).
To be able to use insert to do fast insertions, I keep track of MEntity and linked ArticleEntities to save it after and update links. Maybe it's not a good way to do it.
For 800k ArticleEntities we have about 2k MEntities.

```java
public doImport(){
    List<ArticleEntity> articles = new ArrayList<>();
    HashMap<UUID, List<String>> mACache = new HashMap<>();
    HashMap<UUID, MEntity> mCache = new HashMap<>();
    for (CSVRecord record : parser) { //parse the 880k lines
        articles.add(map(record, mCache, mACache));
        if (articles.size() == ARTICLE_BATCH_MAX_SIZE) {
            saveArticles(articles, realm);
            articles.clear();
        }
    }
    saveMa(mCache, mACache, realm);
}

private ArticleEntity map(CSVRecord record, HashMap<UUID, MEntity> mCache, HashMap<UUID, List<String>> maCache) {
    ArticleEntity article = new ArticleEntity();
    article.setId(UUID.fromString(record.get("article_id")));
    article.setSte(getBoolean(record.get("ste")));
    article.setActive(true);
    article.setType(ArticleType.valueOf(record.get("type")));

    try {
        Date modified = modifiedSdf.parse(record.get("modified"));
        article.setImportModified(modified);
    } catch (Exception e) {
        //nothing to do
    }

    String[] pns = record.get("pns").split("@\\|\\|@");
    for (String pn : pns) {
        ArticlePNEntity apn = new ArticlePNEntity();
        apn.setPn(pn);
        apn.setNpn(Strings.normalize(pn));
        article.getPns().add(apn);
    }

    String[] cods = record.get("cods").split("@\\|\\|@");
    for (String cod : cods) {
        ArticleCodEntity aCod = new ArticleCodEntity();
        String[] split = cod.split("=");
        aCod.setType(CodType.valueOf(split[0]));
        aCod.setValue(split[1]);
        article.getCods().add(aCod);
    }

    mapM(record, mCache, maCache);

    return article;
}

private void mapM(CSVRecord record, HashMap<UUID, MEntity> mCache, HashMap<UUID, List<String>> maCache) {
    UUID mId = UUID.fromString(record.get("m_id"));
    MEntity m = mCache.get(mId);

    if (m == null) {
        m = new MEntity();
        m.setId(mId);
        m.setName(record.get("m_name"));
        mCache.put(mId, m);
    }

    if (!maCache.containsKey(mId)) {
        maCache.put(mId, new ArrayList<String>());
    }
    maCache.get(mId).add(record.get("article_id"));
}

private void saveArticles(final List<ArticleEntity> articles, final Realm realm) {
    if (articles.isEmpty()) {
        return;
    }

    final TimeCounter timeCounter = TimeCounter.get();
    realm.executeTransaction(new Realm.Transaction() {
        @Override
        public void execute(Realm realm) {
            realm.insert(articles);
        }
    });
    long delayToInsert = timeCounter.getStep();
    log.debug("Saved %d articles in %d ms", articles.size(), delayToInsert);
}

**Comment by cmelchior** [comment]
It is a bit hard for me to follow the logic in that code as the caches don't seem to be used for creating the `ArticleEntity`? In any case, any speed up there shouldn't have any effect on how fast/slow Realm is, just on how much time is spent on the doing the full import.

**Comment by mgohin** [comment]
Ok.

I removed the logic of caches, now I use `copyToRealmOrUpdate` to insert all entities every time.
Full import is now around 10mins (with Articles and MEntities).

Thanks for your support. Realm really changed our life for our Android App 👏

**Comment by cmelchior** [comment]
🙇 
You probably want to use `insertOrUpdate` over `copyToRealmOrUpdate` though, especially if you don't plan to use the returned objects from `copyToRealmOrUpdate`

**Comment by mgohin** [comment]
Ho right 👍

**Comment by finnschiermer** [comment]
@mgohin:
1) What is the average size of each object?
2) Are you by any chance holding on to an earlier version of the data while doing all these commits?

**Comment by mgohin** [comment]
1. Don't know. But it contains just a bit of infos
2. No, I add all data into a list that I save then clear the list.

**Comment by Zhuinden** [comment]
Is the list a LinkedList or ArrayList?

**Comment by mgohin** [comment]
ArrayList

**Comment by finnschiermer** [comment]
Re 2) let me elaborate: we've seen some cases where thread A holds on to a specific version of the database (technically, it's in the same read transaction), while thread B does some work. If thread B does multiple commits, while A does not advance, all those commits (or versions) are kept by realm, because thread A may need to get to them later.

**Comment by mgohin** [comment]
I do all the work in an AsyncTask and nothing happen on the UI Thread :/

**Comment by Zhuinden** [comment]
One AsyncTask or multiple AsyncTasks?

**Comment by mgohin** [comment]
Just one, I tried and failed with MultiThreading :D

**Comment by finnschiermer** [comment]
@cmelchior Does the java binding expose the core method SharedGroup::get_number_of_versions() ? 
If it did, it would be useful to print it on every commit to see if we're accumulating versions without cleaning up - and if so, we can start looking for a reason. If not, we'll need to look elsewhere.

**Comment by cmelchior** [comment]
@finnschiermer Not right now, but sounds like something we would want to as it could a nice debug tool for e.g. Realms getting too large.

**Comment by mgohin** [comment]
If you have any beta build I can try to help if needed

**Comment by cmelchior** [comment]
@mgohin If you only have the Realm opened on the UI thread and in one AsyncTask, then that shouldn't be the issue for you.

**Comment by mgohin** [comment]
ok ;)

**Comment by cmelchior** [comment]
But you can easily verify it today by calling `Realm.getGlobalInstanceCount(config)`. This will report the number of threads with an open Realm.

**Comment by mgohin** [comment]
After transaction commit I have 2 instances (one on the UI Thread and one on the AsyncTask I guess), so everything looks ok

**Comment by mgohin** [comment]
New test : no `@PrimaryKey` on articles, using `insertOrUpdate` and insert time is pretty stable, around 6500ms for 15k articles transaction

**Comment by mgohin** [comment]
Just tried why json, not as fast as my current code
