### ISSUE TITLE
Realm crashes when I try to call close() after executeTransaction()

### ISSUE THREAD

**Issue by arifnadeem7** [realm/realm-java#5144]
I am calling this code after I get response from server.     

        Observable.fromCallable(new Callable<Boolean>() {
            @Override
            public Boolean call() throws Exception {
                Realm realm = mDbManager.getDBInstance();
                ChefLogger.e(TAG, "Realm Instance: " + realm.toString());
                realm.executeTransaction(new Realm.Transaction() {
                    @Override
                    public void execute(Realm realm) {
                        realm.copyToRealmOrUpdate(object);
                        if (!realm.isClosed())
                            realm.close();
                    }
                });
                return true;
            }
        }).subscribeOn(Schedulers.newThread()).subscribe();

The app is crashing on **realm.close()** with error **java.lang.IllegalStateException: This Realm instance has already been closed, making it unusable.**

**Comment by Zhuinden** [comment]
Don't close the Realm inside an active transaction.

Also we don't know what `mDbManager.getDBInstance();` ***is***.

**Comment by arifnadeem7** [comment]
Ok getDBInstance was this

    public Realm getDBInstance() {
        return Realm.getDefaultInstance();
    }

In your example of try with resources is realm.close() not needed?

**Comment by arifnadeem7** [comment]
Ok I just looked at BaseRealm and it implements Closeable, so thanks for this neat solution!
