### ISSUE TITLE
Attempting to persist new model to realm with relation not linking the existing model.

### ISSUE THREAD

**Issue by Zeroe31890** [realm/realm-java#5155]
I am attempting to persist a new model to realm. The model is `Account`. It is associated with a `BudgetGroup`.  I link the `BudgetGroup` with the `Account` with `@LinkingObjects("budgetGroup")`. When trying to save it although I see that the unmanaged `Account` has the `BudgetGroup`, the managed returned `Account` does not. So it seems the `LinkingObject` is not working as expected. I included another example of a `LinkingObject` that is working, which is the `TransactionCategory`. I am doing the exact same thing in that example and it actually links the `TransactionCategory` with the `BudgetGroup`. Models and my usage below.

```
public class BudgetGroup extends RealmObject implements Parcelable {
    @PrimaryKey
    private String id;
    private String name;
    private boolean isDeleted;
    private String createdAt;
    private String updatedAt;
    @LinkingObjects("budgetGroup")
    private final RealmResults<TransactionCategory> categories;
    @LinkingObjects("budgetGroup")
    private final RealmResults<Account> accounts;
}

public class Account extends RealmObject implements Parcelable {
    @PrimaryKey
    private String id;
    private String name;
    private String accountType;
    private boolean excludeFromCalculation;
    private long balance;
    private boolean isDeleted;
    private long createdAt;
    private long updatedAt;
    private BudgetGroup budgetGroup;
}

public class TransactionCategory extends RealmObject implements Parcelable {
    private BudgetGroup budgetGroup;
}
```

Saving the `Account`:

            // "account" created manually, so not managed.
            // "budgetGroup" is managed.
            // Surrounded by try catch of course to cancel commit if necessary.
            realm.beginTransaction();
            final BudgetGroup budgetGroup = realm.where(BudgetGroup.class)
                    .equalTo(BudgetGroup.PRIMARY_KEY_FIELD,
                            userAppSettings.getString(UserAppSettings.SELECTED_BUDGET_GROUP))
                    .findFirst();
            account.setBudgetGroup(budgetGroup)
            Account persistedAccount = realm.copyToRealmOrUpdate(account);
            realm.commitTransaction();
            // persistedAccount does not have access to the budget we just added.
            // I also tried realm.copyToRealm and same result.

The weird thing is I am doing the same with the `TransactionCategory` model and persisting it. The linking is successful. So I am honestly at a loss as to what I am doing wrong or different, because they are identical with the exception of the model names. I also don't get any warning so have no idea how to fix. Any insight would be greatly appreciated.

**Comment by beeender** [comment]
1. Are those the full definition of your model classes?
2. what does `persistedAccount.getBudgetGroup()` return? null or a different `BudgetGroup`?

**Comment by Zeroe31890** [comment]
@beeender 

1. It was not the full definition. I updated with the full number of fields.
2. `persistedAccount.getBudgetGroup()` returns null because it never persisted. But `final BudgetGroup budgetGroup` is most certainly not null.

**Comment by beeender** [comment]
will below work?

```
Account persistedAccount = realm.copyToRealmOrUpdate(account);
persistedAccount.setBudgetGroup(budgetGroup)
```

Is it possible to share your project with us? or a simple project can reproduce the issue?
