### ISSUE TITLE
Realm closed after Android killed app process

### ISSUE THREAD

**Issue by chinhub2001** [realm/realm-java#5160]
Hi, 
I have a problem using Realm in my Android app. When the OS killed the app process (you can force this disabling background process in developer options), for example when switching to camera app, and returning, my app crashes.

I get the following error when I access to any Realm data:

java.lang.IllegalStateException: This Realm instance has already been closed, making it unusable.

¿Is there any way to handle app process killing by Android?

This is the code:

```
try(Realm realm = Realm.getDefaultInstance()) {
            return realm
                    .where(LocalSessionModel.class)
                    .findFirst().getDtStartSession();
        }catch (Exception ex){
            Log.d("@dev", "Error" ,ex);
            return null;
        }
```

Thanks!

**Comment by Zhuinden** [comment]
What is `.getDtStartSession();`?

**Comment by chinhub2001** [comment]
Hi,
getDtStartSession() is the field in the "LocalSessionModel" that I want to get. That getter throws the exception I mentioned before.

I've read the lifecycle section, but I'm using a layer architecture so I open/close Realm in the data layer.
This code works 99% of time. The problem happens when the OS kills the app process. ¿Any Ideas/suggestion?


Thanks!

**Comment by Zhuinden** [comment]
I think the only reason why it tends to work is because somewhere you have an unclosed Realm instance, and otherwise wouldn't work right either way.

**Comment by beeender** [comment]
Hope above comments helped you to solve the issue. Close it now. Please let us know if you still need help on this.
