### ISSUE TITLE
Lag on createObject() or copyToRealm() with UUID as PrimaryKey

### ISSUE THREAD

**Issue by adellhk** [realm/realm-java#5167]
#### Goal

Add Realm object `Move` to a RealmList on UI thread or within <50ms.

#### Actual Results
It seems like the transaction isn't.. "completing"?  If I create the object in a synchronous transaction, the transaction doesn't finish for more than a minute. If I execute it with a realm async transaction I can see the object created almost instantly on my Mac OS Realm Browser,  but then I don't get the onSuccess callback or RealmChangeListener notification for at least 10 seconds. I upgraded from Realm 2.3 to 3.5.0 yesterday (because I was previously using RealmRecyclerView), but this has only been a problem since I also switched from integer primary keys (starting at 1) to UUIDs.
```
D/REALM_SYNC: Using already open Realm file: /data/data/io.adell.whatsthebeta/files/realm-object-server/b5adeec4c7028e9e32820b69760c597f/common/sync
D/REALM_SYNC: Connection[1]: Session[2]: Sending: UPLOAD(client_version=11, server_version=450, changeset_size=105, timestamp=83906861344)
D/REALM_SYNC: message_type = download
D/REALM_SYNC: Download message compression: is_body_compressed = 0, compressed_body_size=0, uncompressed_body_size=0
D/REALM_SYNC: Connection[1]: Session[2]: Received: DOWNLOAD(scan_server_version=451, scan_client_version=11, latest_server_version=451, latest_server_session_ident=1110201841958167034, latest_client_version=11, downloadable_bytes=38108, number_of_changesets=0)
D/REALM_SYNC: Using already open Realm file: /data/data/io.adell.whatsthebeta/files/realm-object-server/b5adeec4c7028e9e32820b69760c597f/common/sync
D/REALM_SYNC: Using already open Realm file: /data/data/io.adell.whatsthebeta/files/realm-object-server/b5adeec4c7028e9e32820b69760c597f/common/sync
D/REALM_SYNC: Connection[1]: Session[2]: Progress handler called, downloaded = 38108, downloadable = 38108, uploaded = 1879, uploadable = 1879, progress version = 1, snapshot version = 12
D/TransferService: Stop self
D/VideoMoveTaggingFragmen: addMove: realm transaction took 133676ms
```

#### Steps & Code to Reproduce

If I create an unmanaged object `Move newMove = new Move(milliseconds, attempt);` it takes <1ms, as you would expect. When I try to copy that object to realm or to create it within realm it breaks.  I am calling this method `addMove()` while playing a video and receiving touch events.

#### Code Sample

```java

private void addMove(final Attempt attempt, final int milliseconds) {
    final long startTime = SystemClock.uptimeMillis();
    Move newMove = new Move(milliseconds, attempt);
    realm.executeTransaction(realm -> {
      realm.copyToRealm(newMove);

    // get attempt by id as a holdover from async implementation, but just in case referring to the method parameter "attempt" outside of the transaction is more expensive?
      realm.where(Attempt.class).equalTo("id", attemptId).findFirst().getMoves().add(newMove);
    });
    Log.d(TAG, "addMove: realm transaction took "+ (SystemClock.uptimeMillis() - startTime) + "ms");
}

// or

private void addMove(final Attempt attempt, final int milliseconds) {
    final long startTime = SystemClock.uptimeMillis();
    realm.executeTransaction(realm -> {
        Move newMove = realm.createObject(Move.class, UUID.randomUUID().toString());
        Attempt attempt1 = realm.where(Attempt.class).equalTo("id", attemptId).findFirst();
        attempt1.getMoves().add(newMove);
        newMove.setAttempt(attempt1);
        newMove.setPlaybackPosition(milliseconds);
    });
    Log.d(TAG, "addMove: realm transaction took "+ (SystemClock.uptimeMillis() - startTime) + "ms");
}

// or

private void addMove(final Attempt attempt, final int milliseconds) {
    realm.executeTransactionAsync(realm -> {
//      use async realm instance to retrieve copies of other objects via ID instead of reference to instance since cannot share managed objects across realms.
      Attempt attempt1 = realm.where(Attempt.class).equalTo("id", attemptId).findFirst();
      Move newMove = realm.createObject(Move.class, UUID.randomUUID().toString());
      newMove.setAttempt(attempt1);
      newMove.setPlaybackPosition(milliseconds);
      attempt1.getMoves().add(newMove);
      Log.d(TAG, "addMove: ");
    }, new Realm.Transaction.OnSuccess() {
      @Override
      public void onSuccess() {
        Log.d(TAG, "onSuccess: ");
      }
    }, new Realm.Transaction.OnError() {
      @Override
      public void onError(Throwable error) {
        Log.d(TAG, "onError: " + error);
      }
    });
}
```
#### Version of Realm and tooling
Realm version(s): RMD v3.5.0 / ROS v1.8.3

Realm sync feature enabled: yes

Android Studio version: 2.3.3

Which Android version and device: Nexus 6P, API 25

**Comment by beeender** [comment]
Do your models have circular links? committing transaction will trigger computing of fine grained notifications, and there would be some slowness caused by deep circular links. See #4544 

One solution is to use `@LinkingObjects` instead.
Or you can try `3.6.0-snapshot`. We have made some optimization to make this case faster.

**Comment by Zhuinden** [comment]
@beeender 

        Attempt attempt1 = realm.where(Attempt.class).equalTo("id", attemptId).findFirst();
        attempt1.getMoves().add(newMove);
        newMove.setAttempt(attempt1);

Circular.

 Although considering before `@LinkingObjects` was introduced, this was *the* way to define a bidirectional relation, it's a bit awkward that it is a bottleneck for evaluating result changes.

**Comment by adellhk** [comment]
@beeender, @Zhuinden Thanks!! I implemented `@LinkingObjects`, which I'm excited to see in Realm!
