### ISSUE TITLE
java.lang.UnsatisfiedLinkError: Native method not found: io.realm.internal.UncheckedRow.nativeSetLink:(JJJ)V

### ISSUE THREAD

**Issue by zhiweiofli** [realm/realm-java#5169]
I caught some crash about jni type(UnsatisfiedLinkError)

The problem occurred in the application did not last long, and `Realm.init()` was invoked in `application.onCreate()`. 

### Crash Log:
```
Thread Name: 'pool-id-1-thread-id-3-total-thread-num-3'
--
  |   | Back traces starts.
  |   | java.lang.UnsatisfiedLinkError: Native method not found: io.realm.internal.UncheckedRow.nativeSetLink:(JJJ)V
  |   | at io.realm.internal.UncheckedRow.nativeSetLink(Native Method)
  |   | at io.realm.internal.UncheckedRow.m(ProGuard:255)
  |   | at io.realm.ab.a(ProGuard:230)
  |   | at io.realm.ab.a(ProGuard:50243)
  |   | at io.realm.at.a(ProGuard:50221)
  |   | at io.realm.DownloadModelsMediator.a(ProGuard:172)
  |   | at io.realm.cd.a(ProGuard:1639)
  |   | at io.realm.cd.c(ProGuard:1261)
  |   | at com.ct.rantu.download.data.realm.h.aj(ProGuard:80)
  |   | at com.ct.rantu.download.ar.run(ProGuard:277)
  |   | at com.baymax.commonlibrary.thread.task.l.run(ProGuard:19)
  |   | at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1080)
  |   | at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:573)
  |   | at java.lang.Thread.run(Thread.java:841)
``` 

### Logcat
```
08-25 15:07:21.090 20479 20479 I dalvikvm: DexOpt: unable to optimize static field ref 0x0463 at 0x0d in Lcom/c/a/f;.Ll
--
  |   | 08-25 15:07:21.090 20479 20479 D dalvikvm: Trying to load lib /data/app-lib/com.ct.rantu-1/librealm-jni.so 0x42b41288
  |   | 08-25 15:07:21.120 20479 20479 D dalvikvm: Added shared lib /data/app-lib/com.ct.rantu-1/librealm-jni.so 0x42b41288
```

I have no idea about that~

#### Version of Realm and tooling
Realm version(s): ?
some old app is 2.2.1 --> 3.3.1 on last app version
 
Realm sync feature enabled: yes/no
no

Android Studio version: ?
AS 2.3.3 with gradle plugin 2.2.3

Which Android version and device: ?
Mobile Information: 'model: GT-I9308/version: 4.3/sdk: 18'

**Comment by Zhuinden** [comment]
Do you have any other native libraries in the project?

**Comment by zhiweiofli** [comment]
@Zhuinden yes，about 10

**Comment by zhiweiofli** [comment]
I set my `defaultConfig` with 
```
ndk{
   abiFilters "armeabi-v7a"
}
```

**Comment by cmelchior** [comment]
The native library should be loaded, otherwise your app would have failed a lot sooner, so something else is wrong. Is it a crash reported by a user or something you can reproduce?

**Comment by beeender** [comment]
We have seen problems if user load different `so` files from different threads -- there was a bug in Android before. Try to load all `so` files from the same thread.

**Comment by zhiweiofli** [comment]
@cmelchior it auto report by crash-SDK

**Comment by zhiweiofli** [comment]
@beeender you meat to load other  native libraries at same time and same thread?

**Comment by zhiweiofli** [comment]
I'm sure Realm.init() was invoke on application.onCreate(). it's main thread!

**Comment by beeender** [comment]
@zhiweiofli i mean not only the realm's so file, but also other native so files. I think i have seen a Android bug mentioned there is a race condition issue in the old version of `System.loadLibrary()` (cannot find the bug right now :( ) .

You can try to load all your native libraries on the UI thread to see if it solve the issue (including `Realm.init()` which will load the `librealm_jni.so`)

**Comment by zhiweiofli** [comment]
why other sdk with native library not throw this issue like realm?

**Comment by Zhuinden** [comment]
Another question is if this code works on same device without Proguard. If this is reproduceable on your side.

**Comment by cmelchior** [comment]
@zhiweiofli Has this error just been reported once? or is it hitting multiple users?

**Comment by beeender** [comment]
> why other sdk with native library not throw this issue like realm?

It is probably because of every Realm call is calling into the native code and usually Realm is the first native library get called in the APP to access the data.

Please let us know if
https://github.com/realm/realm-java/issues/5169#issuecomment-325604796
doesn't solve your problem.

**Comment by cylee0909** [comment]
does anyone knows, whether this issue has been resolved?

**Comment by cmelchior** [comment]
This should only occur if you didn't call `Realm.init()` before accessing some random Realm code, so yes.
