### ISSUE TITLE
Is I need every time call method realm.insert(permissionOffer)?

### ISSUE THREAD

**Issue by lmdic** [realm/realm-java#5183]
Code (Android) that generate token:

```java
public class MyApplication extends Application {
    private void createToken(SyncUser syncUser, final PermissionOffer permissionOffer) {
        Realm managementRealm = syncUser.getManagementRealm();
        managementRealm.executeTransaction(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {
                realm.insert(permissionOffer);
            }
        });

        RealmResults<PermissionOffer> permissionOfferRealmResults = managementRealm.where(PermissionOffer.class)
                .equalTo("statusCode", 0)
                .findAll();

        permissionOfferRealmResults.addChangeListener(new RealmChangeListener<RealmResults<PermissionOffer>>()) {
            @Override
            public void onChange(RealmResults<PermissionOffer> offers) {
        for (int index = 0; index < offers.size(); index++) {
                    PermissionOffer currentOffer = offers.get(index);
                    String token = currentOffer.getToken(); // send to client
            }
        });
    }
}
```

As you can see when application is start it EVERY time call  method `realm.insert(permissionOffer).`
As result after time the RealmResults<PermissionOffer> offers become big (count of records > 1000) and it constantly growing.

Question:
Is I need every time to call method `realm.insert(permissionOffer) `when appliction is start?

Or maybe is better if once generate new token (and sent it to client) no more call method `realm.insert(permissionOffer)?`

**Comment by Zhuinden** [comment]
First question is, what permission are you offering to whom?

**Comment by lmdic** [comment]
I try to do the next:

1. I have Android application install on many devices
2. The Android client on this devices will be login to Realm Object Server only by **ONE** user (e.g.: _test@test.com_) to Realm (**myProjectRealm**)
3. So as result on server side I need to generate ONLY one token for Realm **myProjectRealm**
4. As result I use method `realm.insert(permissionOffer)` and `onChange(RealmResults<PermissionOffer> offers)` to get token
5. After get token I send them to all clients

If my algorithm is correct the question is:
After success generate token, is I need to again use method `realm.insert(permissionOffer)` every time on start server side?  Or I not need any more use this method (because already has token)?

**Comment by cmelchior** [comment]
Hi @lmdic 
Sorry for the late reply.

You should create the token once. With your code, you keep creating new offers, which will work, but doesn't really do anything since the user most likely already accepted the first token, so there is no need for them to accept any further.

Also note that we shipped the `SyncUser.getPermissionManager()` in 3.7, which will make handling this a lot easier.

**Comment by Zhuinden** [comment]
@cmelchior Welp, at least once JNI loads it properly with the fix that just got merged. He is the same guy who got the native crash from it not being loaded, he'll probably need the snapshot
