### ISSUE TITLE
release step failed at monkeyDebug

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#5192]
I got a COULD_NOT_FIND_MATCHING_ABI error when running `monkeyDebug` against our GridViewExample that uses APK Split. We need to figure out why

**Comment by beeender** [comment]
dup to #5184

**Comment by beeender** [comment]
reported to the upstream novoda/gradle-android-command-plugin#122

**Comment by nhachicha** [comment]
fixed in https://github.com/realm/realm-java/pull/5478
