### ISSUE TITLE
Crash in Realm native - mmap() failed: Invalid argument

### ISSUE THREAD

**Issue by tmtrademarked** [realm/realm-java#5199]
We're seeing an error reported by users in the wild. From what we can tell, this isn't an OutOfMemory error, and it appears to be highly reproducible for at least one user.

#### Actual Results

Exception io.realm.exceptions.RealmError: Unrecoverable error. mmap() failed: Invalid argumentsize: 0offset: 2097152 in /home/cc/repo/realm/release/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 295
io.realm.internal.SharedRealm.nativeCommitTransaction (SharedRealm.java)
io.realm.internal.SharedRealm.commitTransaction (SharedRealm.java:262)
io.realm.BaseRealm.commitTransaction (BaseRealm.java:359)
io.realm.Realm.commitTransaction (Realm.java:132)
com.blueapron.service.cache.Portal.commitTransaction (Portal.java:39)
com.blueapron.service.server.sequencers.PackageSequencer.execute (PackageSequencer.java:81)
com.blueapron.service.server.sequencers.BaseSequencer.run (BaseSequencer.java:48)
java.util.concurrent.ThreadPoolExecutor.runWorker (ThreadPoolExecutor.java:1133)
java.util.concurrent.ThreadPoolExecutor$Worker.run (ThreadPoolExecutor.java:607)
java.lang.Thread.run (Thread.java:762)

#### Steps & Code to Reproduce

So far, we can't produce this locally - we have one user who's reported this so far, but it's apparently reproducible even after she clears her data.

#### Version of Realm and tooling
Realm version(s):  3.5.0

Realm sync feature enabled: No

Android Studio version: NA

Which Android version and device: Samsung (SM-G955U) running Android 7.0

**Comment by tmtrademarked** [comment]
We've also got a report which may or may not be related (but including here in case this is instructive for debugging) of another native crash on a Samsung device running Android 5.0. It's not immediately apparent if this is the same issue or not, but it appears to be an error while JNI is logging something (and we have no native code in our app besides Realm).


  native: pc 00000000001eace0  /system/lib/libart.so (art::Monitor::VisitLocks(art::StackVisitor*, void (*)(art::mirror::Object*, void*), void*, bool)+43)
  native: pc 000000000022a971  /system/lib/libart.so (art::StackDumpVisitor::VisitFrame()+348)
  native: pc 0000000000224feb  /system/lib/libart.so (art::StackVisitor::WalkStack(bool)+250)
  native: pc 000000000022cf4b  /system/lib/libart.so (art::Thread::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&) const+210)
  native: pc 0000000000235889  /system/lib/libart.so (art::ThreadList::DumpLocked(std::__1::basic_ostream<char, std::__1::char_traits<char> >&)+104)
  native: pc 000000000021d735  /system/lib/libart.so (art::AbortState::Dump(std::__1::basic_ostream<char, std::__1::char_traits<char> >&)+236)
  native: pc 000000000021d981  /system/lib/libart.so (art::Runtime::Abort()+72)
  native: pc 00000000000a8363  /system/lib/libart.so (art::LogMessage::~LogMessage()+1322)
  native: pc 00000000000b1989  /system/lib/libart.so (art::JniAbort(char const*, char const*)+1060)
  native: pc 00000000000b1ee5  /system/lib/libart.so (art::JniAbortF(char const*, char const*, ...)+60)
  native: pc 00000000001a0879  /system/lib/libart.so (art::JNI::CallVoidMethodV(_JNIEnv*, _jobject*, _jmethodID*, std::__va_list)+580)
  native: pc 0000000000062a23  /system/lib/libandroid_runtime.so
  native: pc 0000000000071f5d  /system/framework/arm/boot.oat

**Comment by Zhuinden** [comment]
What is

     com.blueapron.service.cache.Portal.commitTransaction (Portal.java:39)

?

**Comment by tmtrademarked** [comment]
Portal is just a thin wrapper around a Realm instance - it delegates the calls directly to a Realm object.

**Comment by beeender** [comment]
@tmtrademarked do you use Realm encryption?

**Comment by tmtrademarked** [comment]
We don't explicitly opt in to encryption (today). So we're only using any
default encryption, if any.

Tom

**Comment by beeender** [comment]
@tmtrademarked Thanks! This should be a dup issue to #4848 , and there is a core issue tracking this https://github.com/realm/realm-core/issues/2694

I am closing this issue now, if you have more information about this, please comment on https://github.com/realm/realm-core/issues/2694

**Comment by Zhuinden** [comment]
If you don't specify an `encryptionKey` for your RealmConfiguration, then you aren't using encryption.
