### ISSUE TITLE
Build Gradle Failed With "Conflict with dependency..." message

### ISSUE THREAD

**Issue by RuslanPrimak** [realm/realm-java#5200]
#### Goal

> Use Realm on empty project which is created by default with Andoird Studio.

#### Expected Results

> Build succeed

#### Actual Results

>  Error:Conflict with dependency 'com.google.code.findbugs:jsr305' in project ':app'. Resolved versions for app (3.0.2) and test app (2.0.1) differ. See http://g.co/androidstudio/app-test-app-conflict for details.

#### Steps & Code to Reproduce

> Create new empty project by wizard in Android Studio
Specify classpath "io.realm:realm-gradle-plugin:3.7.0" and apply plugin: 'realm-android' in corresponding build.gradle files

#### Version of Realm and tooling
Realm version(s): 3.7.0

Realm sync feature enabled: no

Android Studio version: 
Android Studio 2.3.3
Build #AI-162.4069837, built on June 6, 2017
JRE: 1.8.0_112-release-b06 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o

Which Android version and device: ?

**Comment by beeender** [comment]
Check this similar issue: https://github.com/trello/RxLifecycle/issues/154

**Comment by cmelchior** [comment]
@RuslanPrimak I assume the above answered your question. If not, feel free to reopen
