### ISSUE TITLE
Realm 3.7.0: PermissionManager.AcceptTokenCallback() not exist

### ISSUE THREAD

**Issue by lmdic** [realm/realm-java#5201]
Realm 3.7.0 ,Android 4,3 , Gradle 4.1.

In official example has:

```
PermissionManager pm = user.getPermissionManager();

String token = getToken();
var realmUrl = pm.acceptOffer(token,  new PermissionManager.AcceptTokenCallback() {
    @Override
    public void onSucces(String realmUrl, Permission permission) {
        // User can now access the Realm
        SyncConfiguration config = new SyncConfiguration.Builder(realmUrl, user).build();
        Realm realm = Realm.getInstance(config);
    }

    @Override
    public void onError(ObjectServerError error) {
        // An error happened
    }
    });

```

But class `PermissionManager.AcceptTokenCallback() `not exist in Realm 3.7.0.

https://realm.io/docs/java/latest/api/io/realm/PermissionManager.html

Maybe must use `PermissionManager.AcceptOfferCallback()
`
?

**Comment by beeender** [comment]
Hi @lmdic , what do you mean `PermissionManager.AcceptTokenCallback()` doesn't exist? I am using the project you sent to us and I can get the interface in the Android Studio.

Maybe you need a clean & rebuild?

**Comment by lmdic** [comment]
Realm 3.7.0, Android Studio 2.3.3, Gradle 4.1

```
PermissionManager permissionManager = syncUser.getPermissionManager();
        permissionManager.acceptOffer(offerToken, new PermissionManager.AcceptTokenCallback() {

            @Override
            public void onSuccess(String realmUrl, Permission permission) {
            }

            @Override
            public void onError(ObjectServerError error) {
            }
        });
}
```

In Android Studio error:
`Error:(58, 72) error: cannot find symbol class AcceptTokenCallback`

Also I try to build project from console
`gradlew assemble`

Result:

```
:app:compileDevJavaWithJavacD:\com\myproject\service\RealmService.java:58: error: cannot find symbol
        permissionManager.acceptOffer(offerToken, new PermissionManager.AcceptTokenCallback() {
                                                                       ^
  symbol:   class AcceptTokenCallback
  location: class PermissionManager
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
1 error
 FAILED
:app:copyDevKotlinClasses SKIPPED

FAILURE: Build failed with an exception.
```

**Comment by beeender** [comment]
That is strange, compiles fine here.

Does you project have any other libraries also depends on Realm? That feels like there is a Realm version conflict in the project.

**Comment by lmdic** [comment]
If I use `AcceptOfferCallback()` than project success build and run. So as result ->  no conflicts with Realm

**Comment by beeender** [comment]
Uh, you mean https://realm.io/docs/java/latest/#granting-permissions is wrong?
Yes, it should be `AcceptOfferCallback()`. Sorry for the confusion, fixing it now.

**Comment by lmdic** [comment]
OK :-)
