### ISSUE TITLE
Keep boolean variable naming

### ISSUE THREAD

**Issue by kenticus** [realm/realm-java#521]
On my models I get a error when trying to compile.
Error:(16, 5) error: method does not override or implement a method from a supertype

It only occurs on models with a boolean type. 
My boolean name is "isDeleted"....once changed to "deleted" and I regenerate the getters/setters the error goes away.

I would prefer to be able to keep my naming conventions.

**Comment by ramakrishna-sunkara** [comment]
I am facing this issue still.I need to use **"isActive"** boolean in RealmObject but its not accepting.If i changed to **"active"** its working.But I need to use **"isActive"** only.
Please any one help solution for this.?

**Comment by kneth** [comment]
@ramakrishna-sunkara Can you write a small code snippet to demonstrate the issue?
