### ISSUE TITLE
Realm:Android: When call realm.close on simple class (not Activity)?

### ISSUE THREAD

**Issue by lmdic** [realm/realm-java#5214]
Realm 3.5.0

I have Android application that on start set Realm configuration:

```
public class MyApplication extends Application {

Realm.setDefaultConfiguration(syncConfig);

}
```

OK.
Also I have service class ProfileService (simple class) that try to add/update profile from incoming JSON:

```
public class ProfileService {
  public void addOrUpdatePofile(final String profile) {
        Realm realm = Realm.getDefaultInstance();

        realm.executeTransactionAsync(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {
                try {
                    Profile profile = JsonUtil.gson.fromJson(profile, Profile.class);
                    realm.createObjectFromJson(Profile.class,profile);
                    Log.d(TAG, "execute: SUCCESS ADD/UPDATE");
                } finally {
                    realm.close();
                }
            }
        });
}
```

This method is success executed. On logcat show:
`execute: SUCCESS ADD/UPDATE`

But the data is not upload (not sync) to Realm Object Server.

But if I remove mehtod

`realm.close();`

and again start `addOrUpdatePofile() `then data **SUCCESS** upload(sync) to ROS.

Question:
When I must call `realm.close()`?

P.S> ProfileService is a simple class. It's not Activity and not Fragment.

**Comment by Zhuinden** [comment]
In OnSuccess/OnError callbacks.

**Comment by beeender** [comment]
The `realm` in the `execute(Realm realm)` **doesn't** have to be closed.

actually you only need to close the realm instance is get/create by yourself through `Realm.getXxxInstance()`

**Comment by lmdic** [comment]
If I use this code:

```
final Realm realm = Realm.getDefaultInstance();

        realm.executeTransactionAsync(new Realm.Transaction() {
            @Override
            public void execute(Realm bgRealm) {
                Log.d(TAG, "addOrUpdateProfile: execute: START EXECUTE");
                // METHOD NOT CALL!!!
                // some code

            }
        }, new Realm.Transaction.OnSuccess() {
            @Override
            public void onSuccess() {
                realm.close();
                Log.d(TAG, "addOrUpdateProfile: onSuccess: ");
            }
        }, new Realm.Transaction.OnError() {
            @Override
            public void onError(Throwable error) {
                realm.close();
                Log.e(TAG, "addOrUpdateProfile: onError: ", error);
            }
        });
```

The method `execute(Realm bgRealm)` NOT CALL!

In logcat no message:

`addOrUpdateProfile: execute: START EXECUTE`

Questions:

1. Why `execute(Realm bgRealm) not call?

2. Is it correct to call `realm.close()` in method `onSuccess() `and `onError()` ?

`

**Comment by cmelchior** [comment]
Uploading data to ROS is not immediate and closing the Realm will close the connection, at least before 3.6.0. So this is most likely what you see happen.

If you want to postpone closing the Realm until data has been uploaded, you can use our Progress Notifications listeners or `SyncSession.uploadAllLocalChanges()`: https://blog.realm.io/realm-java-3-4/

**Comment by lmdic** [comment]
My change:

`  
```
public void addOrUpdatePofile(final String profileJson) {
        Realm realm = Realm.getDefaultInstance();

        realm.executeTransactionAsync(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {
                realm.createObjectFromJson(Profile.class, profileJson);
            }
        });
        try {
            SyncConfiguration syncConfiguration = (SyncConfiguration) Realm.getDefaultConfiguration();
            SyncManager.getSession(syncConfiguration).uploadAllLocalChanges();
        } catch (InterruptedException e) {
            Log.e(TAG, "addOrUpdatePofile: " + e.getMessage(), e);
        } finally {
            Log.d(TAG, "addOrUpdatePofile: FINALLY");
            realm.close();
        }
    }`

```


Is this a correct code? Is I'm correct call `realm.close()` ?

**Comment by cmelchior** [comment]
If you call that code from the UI thread it should crash as `uploadAllLocalChanges()` are not allowed to be called from there. This also means you probably don't need run an async transaction. This also means that your count should be 2 most likely. One for the UI thread and one from the background thread where this is running.

**Comment by lmdic** [comment]
This code is never run on UI thread (not from Activity/Fragment). It's run from separate simple class.

So now I run non async (`realm.executeTransaction)`:

```
public void addOrUpdatePofile(final String profileJson) {
        Realm realm = Realm.getDefaultInstance();

        realm.executeTransaction(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {
                realm.createObjectFromJson(Profile.class, profileJson);
            }
        });
        try {
            SyncConfiguration syncConfiguration = (SyncConfiguration) Realm.getDefaultConfiguration();
            SyncManager.getSession(syncConfiguration).uploadAllLocalChanges();
        } catch (InterruptedException e) {
            Log.e(TAG, "addOrUpdatePofile: " + e.getMessage(), e);
        } finally {
            Log.d(TAG, "addOrUpdatePofile: FINALLY");
            realm.close();
        }
    }`
```


And It also success sync with ROS.

Is all is correct?

**Comment by cmelchior** [comment]
Yes, that looks fine 👍

**Comment by lmdic** [comment]
Thank you 👍

**Comment by nitinaid** [comment]
For me 

```
inline fun Realm.executeTransactionWithClose(crossinline block: (Realm) -> Unit) {
    executeTransaction { it.use(block) }
}

Realm.getDefaultInstance().executeTransactionWithClose {
       // code here
}
```

**Comment by Zhuinden** [comment]
Doesn't this close the Realm before the transaction is committed?
