### ISSUE TITLE
 Object not managed by Realm, so it cannot be removed.

### ISSUE THREAD

**Issue by Chinakangliang** [realm/realm-java#5215]
Detele  SQL  Data

#### Goal

> What do you want to achieve?

#### Expected Results   

> Detele  SQL  Data

#### Actual Results
java.lang.IllegalArgumentException: Object not managed by Realm, so it cannot be removed.

> Describe your current debugging efforts.

#### Code Sample

 realm = Realm.getDefaultInstance();
            DaoUtils daoUtils = new DaoUtils(realm);
            final List<DaoLoginModel> loginModels = daoUtils.queryAllDog();

            realm.executeTransaction(new Realm.Transaction() {
                @Override
                public void execute(Realm realm) {
                    loginModels.get(0).deleteFromRealm();

                }
            });

> Your code here. Bigger samples should ideally be as separate Android Studio project, 
> in gists/repositories or privately at help@realm.io)

```

#### Version of Realm and tooling
Realm version(s): ?

Realm sync feature enabled: yes/no

Android Studio version: ?

Which Android version and device: ?

**Comment by Zhuinden** [comment]
I'm pretty sure this cannot be answered without knowing what's in `DaoUtils`

**Comment by Chinakangliang** [comment]
​

2017-09-06 17:17 GMT+08:00 Gabor Varadi <notifications@github.com>:

**Comment by Zhuinden** [comment]
I don't see anything in that message :o

**Comment by Chinakangliang** [comment]
Yeah. I thought I did not make mistakes in full accordance with the
official document ~ ~ but this makes me very different, my data is some can
query out, but can not be deleted～！

2017-09-06 17:24 GMT+08:00 Gabor Varadi <notifications@github.com>:

**Comment by Zhuinden** [comment]
.... You still haven't included DaoUtils source code which is required to answer this question.

You're probably copying from the Realm and then expect it to be a managed object even though it's not.

**Comment by beeender** [comment]
Check this doc to see if it helps https://realm.io/docs/java/latest/#faq-pojo-vs-realmobject

`deleteFromRealm()` must be called on a managed realmobject

**Comment by Chinakangliang** [comment]
谢谢你们，谢谢！

2017-09-06 17:30 GMT+08:00 Chen Mulong <notifications@github.com>:
