### ISSUE TITLE
Not update custom object (RealmObject) in Realm.

### ISSUE THREAD

**Issue by lmdic** [realm/realm-java#5228]
Realm 3.7.1, Android 4.3.

```
public class Profile extends RealmObject {
    @PrimaryKey
    private long id;
    private boolean isReady;
    private MyCustomField name;
}

public class MyCustomField extends RealmObject {
    private RealmList<CustomString> customStringList = new RealmList<>();
}

public class CustomString extends RealmObject {
    private String text;
    private String value;

}
```

My service method that try to update Profile in Realm:

```
public Profile updateProfile(final String profileJson) {
        Realm realm = Realm.getDefaultInstance();
        try {
            final Profile profile = JsonUtil.gson.fromJson(profileJson, Profile.class);
            realm.executeTransaction(new Realm.Transaction() {
                @Override
                public void execute(Realm realm) {
                    realm.copyToRealmOrUpdate(profile);
                }
            });
            SyncManager.getSession((SyncConfiguration) Realm.getDefaultConfiguration()).uploadAllLocalChanges();
            return profile;
        } catch (InterruptedException e) {
            return null;
        } finally {
            realm.close();
        }
}

```
And it's update only some data: **ONLY** `Profile.id `and `Profile.isReady.`
But field `Profile.name `is **NOT** updatad in Realm.

Why?

**Comment by Zhuinden** [comment]
I assume the JSON you have doesn't match the objects that you've defined

**Comment by cmelchior** [comment]
Hard to tell without more information. Like @Zhuinden said, the most likely is that your `JsonUtil.gson.fromJson(profileJson, Profile.class);` returns something where the name isn't set for some reason

**Comment by lmdic** [comment]
Result of `JsonUtil.gson.fromJson(profileJson, Profile.class);`

Profile (POJO):
```
{
id = 1,
isReady = true,
name = [{text = Text1, value ='profile_1_Name 08-09-2017 14:47:31'} {text =Text2, value ='profile_1_Name 08-09-2017 14:47:31'} ],
```
call method : `realm.copyToRealmOrUpdate(profile);`
After add new profile to Realm **all data success inserted**. 


Now I update Profile POJO by new  Json (`JsonUtil.gson.fromJson(profileJson, Profile.class);`)

Update Profile (POJO): 
```
id = 1,
isReady = false,
name = [{text = Text1, value ='profile_1_Name 08-09-2017 14:12:11'} {text =Text2, value ='profile_1_Name 08-09-2017 14:51:12'} ],
```


But now afer call method `realm.copyToRealmOrUpdate(profile);`

in Realm updated **ONLY** `Profile.id,` `Profile.isReady`.

But field `Profile.name `is NOT UPDATED in Realm.

**Comment by Zhuinden** [comment]
I'd think the problem is that 

the JSON is 

```
{
  "id": 1,
  "isReady": false,
  "name": [
    {
      "text": "Text1",
```

and not

```
{
  "id": 1,
  "isReady": false,
  "name": {
       "customStringList": [
            {
             "text": "Text1",
            }
       ]
   }
}
``` 

which actually matches your object.

If this assertion is wrong, then include the custom deserializer as well.

**Comment by lmdic** [comment]
I explicitly exclude field **customStringList** from JSON. As result JSON looks more compact and clearer.  The client not need to know about my custom filed **customStringList**. This JSON import from client.

Here my custom deserilizer:

```
import com.google.gson.JsonDeserializationContext;
import com.google.gson.JsonDeserializer;
import com.google.gson.JsonElement;
import com.google.gson.JsonParseException;

public class MyCustomFieldAdapteJsonDeserilizer implements JsonDeserializer<MyCustomField> {
    private static final String TAG = MyCustomFieldAdapteJsonDeserilizer.class.getName();

    @Override
    public MyCustomField deserialize(JsonElement json, Type typeOfT, JsonDeserializationContext context) throws JsonParseException {
        MyCustomField myCustomField = new MyCustomField();
        RealmList<CustomString> translatedStringList = new RealmList<>();
        JsonArray jsonArray = json.getAsJsonArray();
        for (int index = 0; index < jsonArray.size(); index++) {
            JsonElement translatedStringJsonElement = jsonArray.get(index);
            CustomString translatedString = JsonUtil.gson.fromJson(translatedStringJsonElement, CustomString.class);
            translatedStringList.add(translatedString);
        }
        myCustomField.setCustomStringList(translatedStringList);
        return myCustomField;
    }
}

```

**Comment by lmdic** [comment]
Sorry I'm wrong. The Profile.name in ADD every time when execute `realm.copyToRealmOrUpdate(profile);`
So after 5 times executed `realm.copyToRealmOrUpdate(profile);` in Realm will be 5 records of `Profile.name`

The question is why not only ONE record in Realm?

**Comment by cmelchior** [comment]
Because those elements do not have a primary key, so the old list elements will continue to stay in the Realm.

**Comment by Zhuinden** [comment]
Because it's a `RealmList<` meaning it's a `List<` so it can contain "the same object" multiple times, but in your case it's not the "same object" because the object has no primary key, so each insertion creates a new object.

There is a possibility that overriding `hashCode()`/`equals()` in `MyCustomField` solves that, but I'm actually not sure

**Comment by cmelchior** [comment]
Overriding hashcode doesn't, only have the same primary key would, and even then you can risk having loose elements.

This is something we want to solve as part of Cascading deletes at some point, but right now you can also detect them using the `@LinkingObjects`https://realm.io/docs/java/latest/#inverse-relationships

**Comment by lmdic** [comment]
I need something like cascade update. 
If no way, then maybe before call `realm.copyToRealmOrUpdate(profile)` I MUST delete `Profile.name`?

Something like this:

```
  Profile findProfile = realm.where(Profile .class)
                            .equalTo(Profile .ID, profileid)
                            .findFirst();
                    if (findProfile != null) {
                        // update name
                        LocalizedString name = findProfile.getName();
                        name.deleteFromRealm();
                    }
                    realm.copyToRealmOrUpdate(profile);
```

**Comment by lmdic** [comment]
I think I found solution: https://github.com/realm/realm-java/issues/5230
