### ISSUE TITLE
How update complex RealmObject?

### ISSUE THREAD

**Issue by lmdic** [realm/realm-java#5230]
```
public class Company extends RealmObject {
 @PrimaryKey 
private long id; 
private boolean isCheck
private CustomLocale name; 
 private CustomLocale address;
private CustomLocale news
}

 public class CustomLocale extends RealmObject { 
private RealmList<CustomString> customStringList = new RealmList<>()
 }

 public class CustomString extends RealmObject {
Private String text; 
private String value; }
 
```

My service method that try to update Company in Realm:

```
public void updateCompany(final Company company) { 
Realm realm = Realm.getDefaultInstance(); 
try {
 realm.executeTransaction(new Realm.Transaction() 
{ 
@Override public void execute(Realm realm) { 
      realm.copyToRealmOrUpdate(company); } }
);
```

after call `updateCompany` the Pojo `Company` success insert in Realm. OK.
But if again call `updateCompany` for company with same ID the field `isCheck` success updated.  But all another fields (`name,address,news`) INSERT AGAIN. Not update. 
I know this is because `CustomLocale` has no primary key
But `CustomLocale` not need to have primary key. It.s not unique entity.
So the question is:
How update Pojo `Company` with all it's fields?

**Comment by lmdic** [comment]
I found solution:
My change POJO:

```
public class Company extends RealmObject {
@PrimaryKey 
private long id; 
private boolean isCheck
private CustomLocale name; 
private CustomLocale address;
private CustomLocale news;

public CustomLocale getName() {  return name;}
public CustomLocale getAddress() {  return name;}
public CustomLocale getNews() { return name;}
}
```

Another POJO:

```
public class CustomLocale extends RealmObject { 
    private RealmList<CustomString> customStringList = new RealmList<>()

    public void cascadeDelete() {
        translatedStringList.deleteAllFromRealm(); // The cascade part
        deleteFromRealm(); // delete this object
    }
}
```

Here my code that update Company:

```
public void updateCompany(final Company company) { 
            Realm realm = Realm.getDefaultInstance();
            realm.executeTransaction(new Realm.Transaction() {
                @Override
                public void execute(Realm realm) {
                    Company findCompany = realm.where(Company.class)
                            .equalTo(Company.ID, company.getId())
                            .findFirst();
                    if (findCompany != null) {
                        findCompany.getName().cascadeDelete();
                        findCompany.getAddress().cascadeDelete();
                        findCompany.getNews().cascadeDelete();
                    }
                    realm.copyToRealmOrUpdate(company);
                }
		});
}
```


And it's success work.
Describe my steps for update complex object Company:

1. Add to class **CustomLocale** the custom method `cascadeDelete `that correct delete **CustomLocale** from Realm.
2. In transaction find **Company** by id
3. if success found company then for all variables with type **CustomLocale** call `cascadeDelete()`
4. Update to Realm by `copyToRealmOrUpdate(company);`

As result complex object **Company** success updated in Realm.

So my approach is: before `copyToRealmOrUpdate()` I cascade delete all variables with type **CustomLocale**.

The quistion is:
Is this a correct and best solution for update complex object like **Comany**?

**Comment by nhachicha** [comment]
@lmdic do you have the same behaviour when using `insertOrUpdate` instead?
