### ISSUE TITLE
Crash: property 'x' has been made unindexed after updating version of realm from 3.5.0

### ISSUE THREAD

**Issue by krottv** [realm/realm-java#5237]
#### Goal

I want to update realm from 3.5.0 to any higher version (suppose 3.6.0)

#### Expected Results

Everything goes smooth

#### Actual Results

App crashes after I call `Realm.getInstance` for the first time with the exception:

```
09-09 23:22:29.827 11012-11012/com.wordace.learn.debug W/System.err: io.realm.exceptions.RealmMigrationNeededException: Migration is required due to the following errors:
09-09 23:22:29.828 11012-11012/com.wordace.learn.debug W/System.err: - Property 'Word.translation' has been made unindexed.
09-09 23:22:29.828 11012-11012/com.wordace.learn.debug W/System.err: - Property 'Word.writing' has been made unindexed.
09-09 23:22:29.828 11012-11012/com.wordace.learn.debug W/System.err: - Property 'Word.skipped' has been made unindexed.
09-09 23:22:29.828 11012-11012/com.wordace.learn.debug W/System.err: - Property 'Word.enabled' has been made unindexed.
09-09 23:22:29.829 11012-11012/com.wordace.learn.debug W/System.err:     at io.realm.internal.SharedRealm.nativeGetSharedRealm(Native Method)
09-09 23:22:29.829 11012-11012/com.wordace.learn.debug W/System.err:     at io.realm.internal.SharedRealm.<init>(SharedRealm.java:177)
09-09 23:22:29.829 11012-11012/com.wordace.learn.debug W/System.err:     at io.realm.internal.SharedRealm.getInstance(SharedRealm.java:224)
09-09 23:22:29.829 11012-11012/com.wordace.learn.debug W/System.err:     at io.realm.b.<init>(BaseRealm.java:124)
09-09 23:22:29.829 11012-11012/com.wordace.learn.debug W/System.err:     at io.realm.b.<init>(BaseRealm.java:93)
09-09 23:22:29.830 11012-11012/com.wordace.learn.debug W/System.err:     at io.realm.v.<init>(Realm.java:150)
09-09 23:22:29.830 11012-11012/com.wordace.learn.debug W/System.err:     at io.realm.v.a(Realm.java:417)
09-09 23:22:29.830 11012-11012/com.wordace.learn.debug W/System.err:     at io.realm.RealmCache.b(RealmCache.java:348)
09-09 23:22:29.830 11012-11012/com.wordace.learn.debug W/System.err:     at io.realm.RealmCache.a(RealmCache.java:281)
09-09 23:22:29.830 11012-11012/com.wordace.learn.debug W/System.err:     at io.realm.v.b(Realm.java:346)
09-09 23:22:29.830 11012-11012/com.wordace.learn.debug W/System.err:     at com.wordace.learn.WelcomeActivity$f$3$1.a(WelcomActivity.kt:564)
09-09 23:22:29.830 11012-11012/com.wordace.learn.debug W/System.err:     at com.wordace.learn.WelcomeActivity$f$3$1.call(WelcomActivity.kt:182)
09-09 23:22:29.830 11012-11012/com.wordace.learn.debug W/System.err:     at io.reactivex.internal.operators.observable.e.b(ObservableFromCallable.java:42)
09-09 23:22:29.831 11012-11012/com.wordace.learn.debug W/System.err:     at io.reactivex.e.a(Observable.java:10903)
09-09 23:22:29.831 11012-11012/com.wordace.learn.debug W/System.err:     at io.reactivex.internal.operators.observable.ObservableSubscribeOn$a.run(ObservableSubscribeOn.java:96)
09-09 23:22:29.831 11012-11012/com.wordace.learn.debug W/System.err:     at io.reactivex.j$a.run(Scheduler.java:452)
09-09 23:22:29.831 11012-11012/com.wordace.learn.debug W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.run(ScheduledRunnable.java:61)
09-09 23:22:29.831 11012-11012/com.wordace.learn.debug W/System.err:     at io.reactivex.internal.schedulers.ScheduledRunnable.call(ScheduledRunnable.java:52)
09-09 23:22:29.831 11012-11012/com.wordace.learn.debug W/System.err:     at java.util.concurrent.FutureTask.run(FutureTask.java:266)
09-09 23:22:29.831 11012-11012/com.wordace.learn.debug W/System.err:     at java.util.concurrent.ScheduledThreadPoolExecutor$ScheduledFutureTask.run(ScheduledThreadPoolExecutor.java:301)
09-09 23:22:29.831 11012-11012/com.wordace.learn.debug W/System.err:     at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)
09-09 23:22:29.832 11012-11012/com.wordace.learn.debug W/System.err:     at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)
09-09 23:22:29.832 11012-11012/com.wordace.learn.debug W/System.err:     at java.lang.Thread.run(Thread.java:764)
```
#### What I tried

I tried to add @Index annotation to specified columns, but it doesn't change a thing

#### Code Sample

Here's code of my model
```
open class Word : RealmObject() {

    @PrimaryKey @Required
    open var id: Long? = null
    open var translation: String? = null
    open var transcription: String? = null
    open var writing: String? = null
    @Required
    open var skipped: Boolean? = null
    @Required
    open var enabled: Boolean? = null 
    @Required
    open var level: Int? = null
}
```

#### Version of Realm and tooling
Realm version(s): 3.6.0 and above

Realm sync feature enabled: yes

Android Studio version: 3.0.0 - BETA5

Which Android version and device: 8.0.0, nexus 6p

**Comment by beeender** [comment]
hmmm, i cannot reproduce it with a java project. trying with a kotlin project now.

@krottv does `translation`/`writing`/... ever have `@Index` before?

**Comment by beeender** [comment]
No, no luck to reproduce with a kotlin project either.

@krottv what did you do other than updating realm to `3.6.0+`  ?

**Comment by krottv** [comment]
@beeender 
No, I've never used @Index annotations
Please, try to use my realm file - it is bundled with my app. https://yadi.sk/d/tx51Ou3o3MnbjW

**Comment by beeender** [comment]
Hi, i made a project to test your file. And i found `Word.translation`, `Word.writing`.`Word.skipped', `Word.enabled` do have `@Index` before. And after add `@Index` to all of them, the file can be opened normally and `Word` can be queried.

Maybe you have added `@Index` during testing by accident?

See my testing project in the attachment. 
[kotlintest.zip](https://github.com/realm/realm-java/files/1294606/kotlintest.zip)

**Comment by krottv** [comment]
Thank you very much for testing. That's very strange, then why does it work without `@Index` annotations on version 3.5.0?

**Comment by beeender** [comment]
@krottv Just tried with 3.5.0 and checked the code, it was actually a bug in 3.5.0 that for some reasons, the indexed annotation was not checked during validating the schema :(

**Comment by krottv** [comment]
@beeender Thank you for help. As it turned out to be - bug was in 3.5.0 version, not in new ones.

**Comment by mvojtkovszky** [comment]
I encountered the same issue after publishing an update (which also bumped realm from 3.5.0 to 3.7.2), all of the sudden we have a bunch of crash reports with this issue.

Is there a suggested workaround? 
If I understand correctly, indexed should be added and it should work normally?

**Comment by mvojtkovszky** [comment]
Hi @beeender , that was a quick reply.
After checking into it more thoroughly, i noticed one of the older migrations in my model adds an index to the field that doesn't have it.
So the fault is exclusively mine in this case

**Comment by beeender** [comment]
@mvojtkovszky OK !! well, it was all caused by the old bug in our side :P 

Some reminder for the testing,
let's assume you adding the index by mistake at version 5, then the latest version with Realm 3.7.2 is version 7.
please test below cases after you fix it in your side:
1. install version 4, then install version 7
2. install version 4, install version 5, then install version 7
3. install version 6, then install version 7

**Comment by mvojtkovszky** [comment]
Nice, all working now.

Aside from adding @Index to model, I bumped the database version (in your example to version 8) with migration that added index to affected field(s), if index wasn't there yet. 
This will save the currently affected users on update to version >= 8.
