### ISSUE TITLE
Deletion handling in onChangeListeners

### ISSUE THREAD

**Issue by RJFares** [realm/realm-java#5241]
When adding a realm/object change listener to a managed realm object, I'm expecting the change listener to be called when the object is also deleted from the database.

Instead, my IDE now tells me I should add a @NonNull to the object param, and also I can't check for nulls from the change listener interface.

If that is the intended logic, how can I handle problems which arise when an object is deleted while I have a listener on that object (not on let's say a list<object> or realm because those aren't a problem).

**
Using v3.7.1

**Comment by Zhuinden** [comment]
>  I'm expecting the change listener to be called when the object is also deleted from the database.

Yeah, that is the case since Realm 3.0 if I recall right

> Instead, my IDE now tells me I should add a @nonnull to the object param, and also I can't check for nulls from the change listener interface.

I think you receive the object as `isValid() == false`, also since Realm 3.0

**Comment by Zhuinden** [comment]
Actually, see specifics in https://github.com/realm/realm-java/blob/master/CHANGELOG.md#breaking-changes-4

**Comment by RJFares** [comment]
I confirm, I forgot about this part too "Use RealmObject.isValid() to check this state(#3138)."
So change listeners always return an object and the only way to check for null is through isValid.
Thanks
