### ISSUE TITLE
...is not part of the schema for this Realm.

### ISSUE THREAD

**Issue by Chaintrooper** [realm/realm-java#5243]
#### Goal

Added new parameters to an existing RealmObject including getter and setter methods. 

#### Expected Results

To work as usual with the new methods. 

#### Actual Results

`java.lang.RuntimeException: Unable to create application com.codelikeahipser.heartlock.BaseApplication: io.realm.exceptions.RealmException: class com.codelikeahipser.heartlock.Model.CandidateDAO is not part of the schema for this Realm.
                                                                                   at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5125)
                                                                                   at android.app.ActivityThread.access$1600(ActivityThread.java:177)...`

#### Steps & Code to Reproduce

Read many other issues here regarding the not part of this Realm. Since its still in development, applied:

`RealmConfiguration realmConfiguration = new RealmConfiguration.Builder()
                .name("myproject.realm")
                .deleteRealmIfMigrationNeeded()
                .modules(new MyModule())
                .schemaVersion(5)
                .build();
        Realm.setDefaultConfiguration(realmConfiguration);`

reordered gradle apply:

`apply plugin: 'com.android.application'
apply plugin: 'io.fabric'
apply plugin: 'realm-android'`

removed instant run from Android Studio.

Tried both Realm versions 3.5 (former) and 3.7.1 (current)

#### Code Sample

The error occurs when I try to fill realm with a small json:

`        realm.executeTransaction(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {
                realm.deleteAll();
            }
        });

        realm.executeTransaction(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {
                try {
                    InputStream inputStream = getResources().openRawResource(R.raw.people);
                    realm.createAllFromJson(CandidateDAO.class, inputStream);
                } catch (IOException e) {
                    throw new RuntimeException(e);
                }
            }
        });`

#### Version of Realm and tooling
Realm version(s): 3.5 / 3.7.1

Realm sync feature enabled: no

Android Studio version: 2.3.3

Which Android version and device: Android 5.1 and 6

**Comment by cmelchior** [comment]
You are specifying a custom module using `new MyModule()`. This module apparently do not include `CandidateDAO`

**Comment by Chaintrooper** [comment]
I guess I was just blind. Spent so much time with the config, so I couldn't see the obvious. 
Working already! Thanks a lot!
