### ISSUE TITLE
RealmList iteration behavior does not match RealmResults iteration behavior

### ISSUE THREAD

**Issue by Zhuinden** [realm/realm-java#5244]
#### Goal

> What do you want to achieve?

Iterate a `RealmList` and delete some items with `deleteFromRealm()`

#### Expected Results

Iterator should iterate on all objects using `for(Blah blah: list)` even if items are deleted

#### Actual Results

[Iterator skips elements because deletion modifies the RealmList but the Iterator does not realize this](https://github.com/realm/realm-java/issues/5236#issuecomment-328348209)

If RealmList also created snapshot on iteration, this behavior would be unified (I think?)

#### Version of Realm and tooling
Realm version(s): 3.7.1

Realm sync feature enabled: no

**Comment by cmelchior** [comment]
Actually, I believe this is working as intended. A RealmList works like a normal `ArrayList` in that regard. You cannot remove elements from an ArrayList without a normal for-loop breaking either. 

With a normal ArrayList, you would use `Iterator.remove()` to work around this and this would work for RealmList as well.

If you wanted the semantics you outline, you can actually achieve it by converting the `RealmList` to a `RealmResults` by doing:

```
RealmResults<Foo> snapshot = list.where().findAll().createSnapshot();
```

**Comment by Zhuinden** [comment]
In that case deletion from the Realm while iterating RealmList with iterator should throw ConcurrentModificationException, but the provided solution is perfectly plausible.

**Comment by beeender** [comment]
```
RealmResults<Foo> snapshot = list.where().findAll().createSnapshot();
```

no need to use that long statement, just do:

```
RealmResults<Foo> snapshot = list.createSnapshot();
```

**Comment by jpmcosta** [comment]
Since this issue was closed, I believe the documentation should still be updated, since it states that:
>Iterators created from Realm collections will use a snapshot automatically. RealmResults and RealmList have a createSnapshot method to create one manually.

Source: https://realm.io/docs/java/4.1.0/

**Comment by Zhuinden** [comment]
True, `RealmList` doesn't seem to create snapshot automatically.
