### ISSUE TITLE
无法插入到指定位置

### ISSUE THREAD

**Issue by cv0cv0** [realm/realm-java#5250]
比如删除了一个对象，想重新插回去，只能插到最后。

**Comment by Zhuinden** [comment]
You should sort the results to give you the positions that you want.

**Comment by cv0cv0** [comment]
Insert into the specified location in the display list is very useful, you can use with the adapter, sorting, after all, can not surprise operation.

**Comment by Zhuinden** [comment]
Except then the results wouldn't work as the result set of a query.
