### ISSUE TITLE
recyclerview的item变动没有动画

### ISSUE THREAD

**Issue by cv0cv0** [realm/realm-java#5251]
插入删除没有动画，很生硬。

**Comment by Zhuinden** [comment]
If you use RealmRecyclerViewAdapter (or at least check its source code) you can see how to use `OrderedRealmCollectionChangeListener` to get RecyclerView animations see [here](https://github.com/realm/realm-android-adapters/blob/34bad2f1ef98daa3b13efa5fb5851678d88e2f3f/adapters/src/main/java/io/realm/RealmRecyclerViewAdapter.java#L44-L75)

**Comment by cv0cv0** [comment]
@Zhuinden Thank you!I just think why RecyclerView has a display animation method why not use it?
