### ISSUE TITLE
How sort by complex field?

### ISSUE THREAD

**Issue by lmdic** [realm/realm-java#5252]
Realm 3.7.1

```
public class Contact extends RealmObject {
    @PrimaryKey
    private long id;
    private String name;
}
```

If I want to get all **contacts** and sort by **name** I use the next method:

```
RealmResults<Contact> contactRealmResults = realm.where(Contact.class)
                           .findAllSorted("name");
```

And it's work fine. OK.

Now the type of field `Contact.name` is change. The value of filed `Contact.name `is in `TranslatedString.value`

```
public class Company extends RealmObject {
    @PrimaryKey
    private long id;
    private LocalizedString name;
}

public class LocalizedString extends RealmObject {
    private RealmList<TranslatedString> translatedStringList = new RealmList<>();
}

public class TranslatedString extends RealmObject {
    private String locale;
    private String value;
}
```

So now I need to sort by field `TranslatedString.value` .
And how I can do this?

**Comment by cmelchior** [comment]
To turn the question around? What exactly do you expect the result to be?

**Comment by Zhuinden** [comment]
Probably just 

``` java
RealmResults<Company> contactRealmResults = realm.where(Company.class)
                           .findAllSorted("name.value");
```

**Comment by lmdic** [comment]
Field `TranslatedString.locale `content language. Field `TranslatedString.value `content value of name on specific language.
So I want the next:
Get me all conacts where `TranslatedString.locale = "en"` and sort result by `TranslatedString.value` .

How I can do this?

**Comment by cmelchior** [comment]
I'm still not sure what you mean.

`Company.name` is a list of `TranslatedString` items. Sorting by a list doesn't really make sense unless in some very specific context specific to your application.

E.g if you only want to sort by the `en` entry in that list you should instead pull that value into a separate field like:

```
public class LocalizedString extends RealmObject {
    private enLocaleValue = ""; 
    private RealmList<TranslatedString> translatedStringList = new RealmList<>();
}
```

Then you can sort using:

```
RealmResults<Company> contactRealmResults = realm.where(Company.class)
                                                .findAllSorted("name.value");
```

**Comment by lmdic** [comment]
I can't change model.
The language is in field `TranslatedString.locale`.
So I need something like this:

RealmResults<Company> contactRealmResults = realm.where(Company.class)
                                                 .equalTo("name.locale", "en")
                                                .findAllSorted("name.value");

**Comment by Zhuinden** [comment]
I think that sounds like it would be possible

**Comment by lmdic** [comment]
Something is wrong:

```
RealmResults<Contact> contactRealmResults = realm.where(Contact.class)
                    .equalTo("name.translatedStringList.locale", lang)
                    .findAllSorted("name.translatedStringList.value");
```

I get error:

```
FATAL EXCEPTION: main
java.lang.IllegalArgumentException: Invalid query: field 'translatedStringList' in class 'LocalizedString' is of invalid type 'LIST'.
	at io.realm.internal.fields.FieldDescriptor.verifyColumnType(FieldDescriptor.java:277)
	at io.realm.internal.fields.FieldDescriptor.verifyInternalColumnType(FieldDescriptor.java:230)
	at io.realm.internal.fields.CachedFieldDescriptor.compileFieldDescription(CachedFieldDescriptor.java:83)
	at io.realm.internal.fields.FieldDescriptor.compileIfNecessary(FieldDescriptor.java:285)
	at io.realm.internal.fields.FieldDescriptor.getFinalColumnType(FieldDescriptor.java:213)
	at io.realm.internal.SortDescriptor.checkFieldType(SortDescriptor.java:110)
	at io.realm.internal.SortDescriptor.getInstance(SortDescriptor.java:95)
	at io.realm.internal.SortDescriptor.getInstanceForSort(SortDescriptor.java:65)
	at io.realm.internal.SortDescriptor.getInstanceForSort(SortDescriptor.java:54)
	at io.realm.RealmQuery.findAllSorted(RealmQuery.java:1797)
	at io.realm.RealmQuery.findAllSorted(RealmQuery.java:1832)
	at com.myproject.service.ContactService.getContacts(ContactService.java:34)
	at com.myproject.app.MainApp$3.onSuccess(MainApp.java:304)
	at com.myproject.app.MainApp$3.onSuccess(MainApp.java:290)
	at io.realm.RealmCache$CreateRealmRunnable$1.run(RealmCache.java:142)
	at android.os.Handler.handleCallback(Handler.java:730)
	at android.os.Handler.dispatchMessage(Handler.java:92)
	at android.os.Looper.loop(Looper.java:137)
	at android.app.ActivityThread.main(ActivityThread.java:5103)
	at java.lang.reflect.Method.invokeNative(Native Method)
	at java.lang.reflect.Method.invoke(Method.java:525)
	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:737)
	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:553)
	at dalvik.system.NativeStart.main(Native Method)
   Force finishing activity com.myproject.dev/com.myproject.activity.RegistrationActivity
```

**Comment by cmelchior** [comment]
No, that isn't possible.  You cannot sort on list elements in a child object when querying on the parent object. You need one single value you can sort on, not multiple.

**Comment by lmdic** [comment]
OK. If I can't sort, then at least is I can get all contacts only on English?
Somethink like this:

```
RealmResults<Contact> contactRealmResults = realm.where(Contact.class)
                    .equalTo("name.translatedStringList.locale", "en")
                    .findAll();

```

**Comment by cmelchior** [comment]
That query will find all `Contact` with an english locale, yes, but the `name` list will still contain the other locales. They will not be filtered out.

**Comment by lmdic** [comment]
So maybe by chaining queries I can get all contacts only on English?

**Comment by cmelchior** [comment]
No, you need to rethink your data model if you want to query and retrieve only specific languages. In Realm, what you put in, is what you get out. 

But why do you need to only return the english contact? If you have a `Contact` object and you know you want to display the English title, you can just pull that from the localized list because the query ensured that it will be there.

**Comment by lmdic** [comment]
And the main questions are:
How it should look like class `Contact`  to I can do:

1.  Get all contacts by specific language
2.  Get all contacts by specific language and sort by **name**

What I need to change in my model?

**Comment by lmdic** [comment]
I want to get only english contact by Realm because it's more comfortable.

Аlternative is: 

1.  Get all contact on all languages by Realm:
```
RealmResults<Contact> contactRealmResults = realm.where(Contact.class)
                    .findAll();
```
2. Iterate all contacts (using Java) and return  only English contacts. 

Do you suggest this solution?

**Comment by cmelchior** [comment]
Why not just have a localized contact class like:

```
public class LocalizedContact extends RealmObject {
    @Index 
    private long id;
    private String locale
    private String name;
}
```

This approach only has an impact on your ID's. Which no longer can be marked as a primary key as the same ID will be shared between multiple `LocalizedContact` objects. I don't know if that is a problem or not.

**Comment by Zhuinden** [comment]
@cmelchior or make a "composite" primary key by concatenating multiple fields into a single String

``` java
public class Contact extends RealmObject {
    @PrimaryKey
    private String idAndLocale;
    @Index
    private long id;
    @Index
    private String locale;

    private String name;
}
```

**Comment by lmdic** [comment]
And the main questions are:
How it should look like class Contact to I can do:

Get all contacts by specific language
Get all contacts by specific language and sort by name

What I need to change in my model?

**Comment by Zhuinden** [comment]
The **real** question is if this thing you've been tinkering with for the past week is already in production or not, because you seem to be using Realm Sync (considering you logged in a SyncUser the other day with PermissionManager )

**Comment by lmdic** [comment]
For now I'm postponed using **PermissionManager** .  For now I select another way - without tokens.

**Comment by cmelchior** [comment]
@Imdic Change your `Contact` class to look like what I described in https://github.com/realm/realm-java/issues/5252#issuecomment-328793553 or @Zhuinden did, then you can simply do

```
// Get all contacts by language
realm.where(Contact.class).equalTo("locale", "en").findAll();

// Get all contacts by language and sorted
realm.where(Contact.class).equalTo("locale", "en").findAllSorted("name");
```

**Comment by lmdic** [comment]
Yes you was right. The next method not help:

```
 RealmResults<Contact> contactRealmResults = realm.where(Contact.class)
                    .equalTo("name.translatedStringList.locale", "en")
                    .findAll();
```

This NOT filter by "en". It's return all contacts on all languages.

So maybe I need to change my model.

**Comment by lmdic** [comment]
So you here change model:

```
public class Contact extends RealmObject {
    @PrimaryKey
    private int id;
    private RealmList <LocalizedContact> localizedContact;
}

public class LocalizedContact extends RealmObject {
    private String locale;
    private String name;
    private String address;
}
```


And as result now I can create queries like this:

```
// Get all contacts by language
realm.where(Contact.class).equalTo("locale", "en").findAll();

// Get all contacts by language and sorted
realm.where(Contact.class).equalTo("locale", "en").findAllSorted("name");
```

Is I'm right?

**Comment by Zhuinden** [comment]
``` java
public class Contact extends RealmObject {
    @PrimaryKey
    private String idAndLocale; // "" + id + "_" + locale
    @Index
    private long id;
    @Index
    private String locale;
    @Index
    private String name;

    private String address;
}

// Get all contacts by language and sorted
realm.where(Contact.class).equalTo("locale", "en").findAllSorted("name");
```

**Comment by cmelchior** [comment]
@lmdic I assume the above answered your question. If not, feel free to reopen.
