### ISSUE TITLE
Realm clear data after application update from store

### ISSUE THREAD

**Issue by kraa** [realm/realm-java#5256]
I have two realm DB. First read from asset file and second fills by data from app:

```java
        RealmConfiguration realmConfiguration1 = new RealmConfiguration.Builder()
                .assetFile(EXPORT_REALM_FILE_NAME)
                .schemaVersion(2)
                .build();

        RealmConfiguration realmConfiguration2 = new RealmConfiguration.Builder()
                .name(FAV_REALM_NAME)
                .schemaVersion(0)
                .build();

        mRealm = Realm.getInstance(realmConfiguration1);
        mFavRealm = Realm.getInstance(realmConfiguration2);
```

mFavRealm store data that was added to favorites. But after update app from Google Store all data from mFavRealm disapear and it's become empty...
There was no any scheme change or something.. Why it's happenes ?

**Comment by cmelchior** [comment]
Those configurations will not cause the Realm to be removed, so something else must have done it. There is a number of options:

- The file was deleted somehow (uninstalling the app?)
- Calling `Realm.deleteRealm()` somewhere
- Some code is deleting all objects in the Realm, using e.g. `Realm.delete*()` or `RealmResults.delete*()`

**Comment by kraa** [comment]
oh.. What a stupid I am!! It was realy deleteAllFromRealm in one place of project code! 
Thanks !!
