### ISSUE TITLE
Verify behavior of using `asFlowable().switchMap()` on UI thread while starting a UI thread transaction

### ISSUE THREAD

**Issue by Zhuinden** [realm/realm-java#5257]
There were some weird `nativeStartListening()` stuff using `RealmObject.asObservable()` so it might be work checking if UI thread transaction is allowed if using `realmObject.asFlowable()` somewhere.

This is more a mental note for... me or anyone else, really

#### Version of Realm and tooling
Realm version(s): 4.0.0-BETA3

Realm sync feature enabled: no

Android Studio version: 3.0.0

**Comment by Zhuinden** [comment]
Now I remember what I should have been doing this weekend... hrm

**Comment by cmelchior** [comment]
Closing as outdated. Frozen objects should solve any issues with Realm and weird threading behavior.
