### ISSUE TITLE
Where find example about filtering  in RealmBaseAdapter?

### ISSUE THREAD

**Issue by lmdic** [realm/realm-java#5273]
Realm 3.7.2

In my Android app I use **Fragment** and **ListView** with **RealmBaseAdapter**.
In the ListView show all contacts.
Now I need to filter contacts. 
So as result I add component **SearchView** in the top of screen. 
And when user input some contact name I need to show(filter) only  names.

E.g. 
Suppose all list content the next names:
```
Jill
William
Alex
Trillian
```

When input name = "ill"
Resul must be:
```
Jill
William
Trillian
```

The question is: Where I can find example about filtering in **RealmBaseAdapter**?

**Comment by lmdic** [comment]
I found solution 
I must use special method of RealmBaseAdapter:

myRealmBaseAdapter.`updateData`(myNewRealmResults);

**Comment by Zhuinden** [comment]
https://stackoverflow.com/questions/40630322/how-to-implement-filterable-in-realmrecyclerviewadapter
