### ISSUE TITLE
Cannot access Realm Sync Core

### ISSUE THREAD

**Issue by vivekkiran** [realm/realm-java#5275]
I am not able to access Realm Sync Core mentioned at https://github.com/realm/realm-java/blob/master/dependencies.list, I am getting 404 error, is the repository public or private, how can I access it?

https://github.com/realm/realm-sync/releases

**Comment by cmelchior** [comment]
Our core database consists of Realm Core and Realm Sync. The Sync parts are not open source, but the core parts are here: https://github.com/realm/realm-core.

**Comment by vivekkiran** [comment]
@cmelchior it will be great if certain parts of Realm Sync are made open source, which is relevant to this repository and community edition of realm.

**Comment by cmelchior** [comment]
The sync parts are only used when enabled specially and only works in conjunction with the Realm Object Server. All parts of the local database should be open source (what you call community edition).

What specifically are you looking for?

**Comment by beeender** [comment]
@vivekkiran I am closing this issue now. Please let us know if you still need more information on this.
