### ISSUE TITLE
realm can user annotation replace column name or table name

### ISSUE THREAD

**Issue by liyuyitong** [realm/realm-java#5278]
realm can user annotation replace column name or table name?

**Comment by Zhuinden** [comment]
The class name is used for table name, and the field name is used for column name.

**Comment by cmelchior** [comment]
Yes, this is a duplicate of #2476. So lets keep the discussion there.
I actually have a prototype for this, but I need to find the time to prioritize it. You can see it here: https://github.com/realm/realm-java/pull/5280

Let me know if that doesn't support your use case.
