### ISSUE TITLE
io.realm.exceptions.RealmError

### ISSUE THREAD

**Issue by saeedmozaffari** [realm/realm-java#5279]
i see following error in google error reporter and fabric, I've received an error for many users

![1 2](https://user-images.githubusercontent.com/16954656/30579124-8a12d684-9d2c-11e7-996a-f13fe64f3f40.jpg)

error line is
```java
DynamicRealm dynamicRealm = DynamicRealm.getInstance(configuration);
```
this is the full code
```java

private void realmConfiguration() {
        /**
         * before call RealmConfiguration client need to Realm.init(context);
         */
        Realm.init(context);

        RealmConfiguration configuration = new RealmConfiguration.Builder().name("iGapLocalDatabase.realm").schemaVersion(14).migration(new RealmMigration()).build();
        DynamicRealm dynamicRealm = DynamicRealm.getInstance(configuration);
        /**
         * Returns version of Realm file on disk
         */
        if (dynamicRealm.getVersion() == -1) {
            Realm.setDefaultConfiguration(new RealmConfiguration.Builder().name("iGapLocalDatabase.realm").schemaVersion(14).deleteRealmIfMigrationNeeded().build());
        } else {
            Realm.setDefaultConfiguration(new RealmConfiguration.Builder().name("iGapLocalDatabase.realm").schemaVersion(14).migration(new RealmMigration()).build());
        }
        dynamicRealm.close();

        try {
            Realm.compactRealm(configuration);
        } catch (UnsupportedOperationException e) {
            e.printStackTrace();
        }
    }
```

Where is my mistake?

-----------------------------------------------------------------------
Realm version(s): 3.7.2
Realm sync feature enabled: no
Android Studio version: 2.3.3
Which Android version and device: Samsung Galaxy C5 Pro, also some of other devices...

**Comment by cmelchior** [comment]
@saeedmozaffari That code should work fine. The RealmError should also have a more detailed message attached to it?

**Comment by Asad4429** [comment]
i am getting the same error please tell me if there is any solution.

![screenshot from 2017-09-21 12-08-50](https://user-images.githubusercontent.com/14857273/30683445-f08120f6-9ec6-11e7-99a7-7fc798e0d519.png)

**Comment by Asad4429** [comment]
Realm version(s): 3.7.2

**Comment by cmelchior** [comment]
@Asad4429 Does the RealmError comes with a more detailed exception message?

**Comment by Asad4429** [comment]
no, it's just showing this detail only
RealmException in Realm.getInstance() method. 
it occurs frequently not always

**Comment by Asad4429** [comment]
i found some more details
![screenshot from 2017-09-22 18-24-52](https://user-images.githubusercontent.com/14857273/30746597-b4d6e394-9fc3-11e7-8843-c9aabc1ac71e.png)

**Comment by Zhuinden** [comment]
What device is this on?

**Comment by Asad4429** [comment]
Major device is X700 PRO (X700_PRO) 
and others are 
Honor 5X (HNKIW-Q) 
Moto G(4) Plus (athene_f) 
Droid Ultra (obake) 
P8 Lite (hwALE-H)

**Comment by beeender** [comment]
@Asad4429 

1. You crash doesn't seem to be related with the original issue here.
2. Your crash log is not completed. It seems to be dead lock somewhere, and coincidentally it contains a backtrace with Realm. **If you can post a full backtrace, maybe we can find some clue**
3. "First i am getting this crash on realm version 2.3.2" `Realm.createExpectedSchemaInfo` was added in `3.6.0`, so you should not meet the same callstack on version `2.3.2`. please also post the **full** backtrace with `2.3.2` as well.

**Comment by beeender** [comment]
@saeedmozaffari @Asad4429 The new google play console seems removed the exception message by default. And it makes us no way to figure out what is going on there.

See 
https://www.reddit.com/r/androiddev/comments/6ihcr7/exception_messages_missing_in_new_play_console/

And https://developers.google.com/analytics/devguides/collection/android/v4/exceptions

Is it possible for you to get the exception message back to your app when reporting crash?

**Comment by nhachicha** [comment]
@saeedmozaffari @Asad4429 have you managed to get the exception message back?

**Comment by cmelchior** [comment]
Closing due to no response.
