### ISSUE TITLE
and keyword in realm - question/help

### ISSUE THREAD

**Issue by lazarvgd** [realm/realm-java#5283]
Hi, I am struggling to write query in android app so i can get object from list which match next condition:

someObject.getStart().before(end) && someObject.getEnd.after(start)

where **end** and **start** are Date objects, and methods **getStart** and **getEnd** return Date objects.

realm.where(Event.class).equalTo("id",id).lessThanOrEqualTo("start", end).**_and()_**.greaterThanOrEqualTo("end", start);

I know that there is no method **"AND"**, so can somebody explain me how to write query above?

please sorry if this is duplicate question, but I have spend 30 mins searching for similar answer but without luck.

Thanks

**Comment by beeender** [comment]
`realm.where(Event.class).equalTo("id",id).lessThanOrEqualTo("start", end).greaterThanOrEqualTo("end", start);`

should just work? the default relationship for each query conditions is `and`.

but the problem is do you need `equalTo("id",id)` in your query?
