### ISSUE TITLE
Invalid query: field 'id' in class is of invalid type 'INTEGER' - issue

### ISSUE THREAD

**Issue by lazarvgd** [realm/realm-java#5286]
Hi, me again.

I got the error java.lang.IllegalArgumentException: Invalid query: field 'id' in class 'Event' is of invalid type 'INTEGER'.
The **id** field is type of **long**, 
And my query was:
realm.where(Event.class).equalTo("id",id).findFirst();

What am I doing wrong?

Thanks

**Comment by cmelchior** [comment]
That sounds odd. Can you post your entire `Event` as well as what type the `id` parameter you are parsing in?

**Comment by lazarvgd** [comment]
right now afk, will post entity later. The ii is
String id = String.valueOf(event.getId())

Where, getId returns long type value.

**Comment by Zhuinden** [comment]
@lazarvgd if `event.getId()` is `long` and the field called `id` is `long` then why are you converting it to String?

**Comment by beeender** [comment]
@lazarvgd Hope above comments solved you problem. Please let us know if you still need help on this.

**Comment by marcoRS** [comment]
Hello I am seeing a related error when upgrading from Realm 1.2.0 -> 4.1.1. The JsonObject I obtain has a int id from the following api response:

```json
{
  "this_week": {
    "wednesday": false,
    "tuesday": false,
    "thursday": false,
    "sunday": false,
    "saturday": false,
    "monday": false,
    "friday": false
  },
  "status": {
    "workout_source": false,
    "week_streak": 0,
    "streak": 0,
    "max_streak": 0,
    "danger_zone": false
  },
  "settings": {
    "weight": 127,
    "utc": 4,
    "unit_system": true,
    "onboard": true,
    "height": 208,
    "has_facebook": false,
    "completed_registration": true
  },
  "profile_pic": "https:\/\/secure.gravatar.com\/avatar\/535a68a5d17826dbf09b96d5c744ea7a?r=g&d=identicon&s=750",
  "last_name": "",
  "last_event": null,
  "id": 7567,
  "gender": null,
  "first_name": "Marc",
  "cheat_progress": 0,
  "cheat_days": 1,
  "birthdate": null
}
```

This was working in the previous version when calling: 
```java
Realm realm = Realm.getDefaultInstance();
 realm.beginTransaction();
 realm.createOrUpdateObjectFromJson(RJUser.class, response);
 realm.commitTransaction();
```
Now we are seeing the following error:
`java.lang.IllegalArgumentException: JSON object doesn't have the primary key field 'id'.`

**Comment by beeender** [comment]
@marcoRS 

we may have some bug in `1.2.0` which forget the check the PK existence in JSON object. But it should be fine with `4.1.1`. Would you please do a double check of your JSON object and the `RJUser` definition? If you still have issues, please provide a sample project to reproduce the problem and create a new issue here. Thanks!

**Comment by marcoRS** [comment]
Hello RJUser has the following structure, with details omitted here for brevity:

```java
public class RJUser extends RealmObject {
    @PrimaryKey
    private String id;
    private String first_name;
    private String last_name;
    private String email;
    private String profile_pic;
    private String birthdate;
    private String gender;
    private boolean current_user;
    ..... getters and setters here
}

Does the fact that the Model have a String id vs Json int id affect anything? The id is clearly in the JsonObject, I've checked various times.

**Comment by beeender** [comment]
@marcoRS 

Does below code give you the right `id`? (7567) Call it before `createOrUpdateObjectFromJson`
```
response.getInt("id");
```

**Comment by Zhuinden** [comment]
> Does the fact that the Model have a String id vs Json int id affect anything?

yes

**Comment by marcoRS** [comment]
The type difference did not seem to make a difference in 1.2.0. Is there now a more strict type check?

**Comment by beeender** [comment]
It shouldn't matter.

The generated proxy file is something like:

```
       if (obj == null) {
            if (json.has("id")) {
                if (json.isNull("id")) {
                    obj = (io.realm.PrimaryKeyAsIntegerRealmProxy) realm.createObjectInternal(io.realm.entities.PrimaryKeyAsInteger.class, null, true, excludeFields);
                } else {
                    obj = (io.realm.PrimaryKeyAsIntegerRealmProxy) realm.createObjectInternal(io.realm.entities.PrimaryKeyAsInteger.class, json.getInt("id"), true, excludeFields);
                }
            } else {
                throw new IllegalArgumentException("JSON object doesn't have the primary key field 'id'.");
            }
        }
```

It will throw that exception only if the given json object doesn't have `id` field.

**Comment by marcoRS** [comment]
I see, thanks so that would give a hint that `id` might not actually be in the JsonObject I'm dealing with. I'll have to check again to verify. I even tried adding a random `id` to the JsonObject before storing and it seemed to fail.

**Comment by r9software** [comment]
I had the very same issue: 
speciesName = realm.where(Specie.class).equalTo("id",Integer.valueOf(speciesId)).findFirst().getName();
the equalTo was expecting an Int and I was using an String

**Comment by engr-erum** [comment]
@Zhuinden  https://pastebin.com/d8abU4Ns can u pls check what is the issue in query ? 
getting exception   java.lang.NullPointerException: Attempt to get length of null array

**Comment by Zhuinden** [comment]
@engr-erum you are passing null instead of an empty array
