### ISSUE TITLE
Realm model class not a part of schema.

### ISSUE THREAD

**Issue by vamshikhoslalabs** [realm/realm-java#5292]
Error:Error converting bytecode to dex:
Cause: Dex cannot parse version 52 byte code.
This is caused by library dependencies that have been compiled using Java 8 or above.
If you are using the 'java' gradle plugin in a library submodule add 
targetCompatibility = '1.7'
sourceCompatibility = '1.7'
to that submodule's build.gradle file.

**Comment by Zhuinden** [comment]
Is this some android studio 3.0 thing?

**Comment by vamshikhoslalabs** [comment]
@Zhuinden Android 2.3.3

**Comment by Zhuinden** [comment]
Huh. You probably should add Retrolambda if you are using Java 1.8 features with Android Studio 2.3

**Comment by vamshikhoslalabs** [comment]
@Zhuinden ok when I have added retrolambda this error starts showing up.

**Comment by Zhuinden** [comment]
That's weird, but I think I'd have to know more about applied plugins and if there are multiple project modules that use Realm and stuff to know what could be up.

Is it possible for you to create a minimal project that reproduces this, or send reproducing code to help[at]realm.io?

**Comment by vamshikhoslalabs** [comment]
@Zhuinden I have mailed you can you check that

**Comment by vamshikhoslalabs** [comment]
@Zhuinden Any progress regarding the issue??

**Comment by cmelchior** [comment]
@vamshikhoslalabs He does not have access to that email 😄 I responded to it.

**Comment by vamshikhoslalabs** [comment]
@cmelchior Thank you. I thought @Zhuinden has took over my issue. Sorry.

**Comment by vamshikhoslalabs** [comment]
Hi Christian, any update on this?



<https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=vamshi@khoslalabs.com&idSignature=22>

*Vamshi Krishna* | Android Developer
Khosla labs | Bangalore <http://address.khoslalabs.com>
Phone : 9036627235 | vamshi@khoslalabs.com
Khosla labs <http://www.khoslalabs.com>

**Comment by cmelchior** [comment]
I tried to open it in `3.0.0-beta6` of Android Studio. There it worked and compiled without problems. I, unfortunately, haven't had time to dig more into it yet.

**Comment by vamshikhoslalabs** [comment]
Hi Christian, Thanks for reply but i'm on Android Studio 2.3.3 can you
suggest any fix for this version of IDE.



<https://mailtrack.io/> Sent with Mailtrack
<https://mailtrack.io/install?source=signature&lang=en&referral=vamshi@khoslalabs.com&idSignature=22>
<#>

*Vamshi Krishna* | Android Developer
Khosla labs | Bangalore <http://address.khoslalabs.com>
Phone : 9036627235 | vamshi@khoslalabs.com
Khosla labs <http://www.khoslalabs.com>

**Comment by beeender** [comment]
@vamshikhoslalabs Please take a look at https://stackoverflow.com/questions/37020413/android-dex-cannot-parse-version-52-byte-code

especially:
https://stackoverflow.com/a/46162939/1396606
https://stackoverflow.com/a/37426385/1396606

**Comment by vamshikhoslalabs** [comment]
@beeender @Zhuinden @cmelchior I fixed this issue myself just added this to my gradle.properties file.

```
retrolambda {
jvmArgs '-Xmx2048m'
}
android.enableDesugar=false
```


Thank you for your response and support. 👍

**Comment by LeslieKoma** [comment]
I also encountered the same problem when you integrated the latest realm, can you help me?
apply plugin: 'me.tatarka.retrolambda'
apply plugin: 'realm-android'
compileOptions {
         sourceCompatibility JavaVersion.VERSION_1_8
         targetCompatibility JavaVersion.VERSION_1_8
     }


   classpath 'me.tatarka: gradle-retrolambda: 3.7.0'
   classpath "io.realm: realm-gradle-plugin: 4.3.3"

I am using androidstudio 2.3.2
