### ISSUE TITLE
Option to disable thread check

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#5293]
@emanuelez came up with this idea to boost performance:

Instead of always having thread checks for every access in model classes we instead introduce an extra boolean in our gradle plugin:

```
realm {
  enableThreadCheckForRelease = false;
}
```

The effect of this boolean should be that when set to `false`, whenever an app is built for release mode, the thread check is completely disabled, which should provide a quite significant performance boost (we need to check how much). This means that people can run tests on a debug build and catch all cases where they might break the invariant and then disable the check when releasing the app.

```
// Current check
// Thread.currentThread is a nativeMethod that returns an object.
if (threadId != Thread.currentThread().getId()) {
  throw new IllegalStateException(BaseRealm.INCORRECT_THREAD_MESSAGE);
}

// The trivial replacement
if (BuildConfig.REALM_THREAD_CHECK && threadId != Thread.currentThread().getId()) {
  throw new IllegalStateException(BaseRealm.INCORRECT_THREAD_MESSAGE);
}
```

Hooking this up to the build system might not be entirely trivial though. 

There are other ways this can be accomplished, e.g bytecode manipulation, but trying to do advanced things to replace a `boolean` check is probably not worth it https://stackoverflow.com/questions/7958108/performance-of-overriding-vs-if-statement

**Comment by cmelchior** [comment]
A quick test shows no difference between having check or not:

With check
![image](https://user-images.githubusercontent.com/406066/30670089-4a45d37c-9e61-11e7-9618-35caa06a32e2.png)

Without check
![image](https://user-images.githubusercontent.com/406066/30670104-581522d2-9e61-11e7-9d9c-ccb1756f3e0e.png)


This actually surprises me a little.
The test was really quick though, but it doesn't seem like the savings are going to be that massive.

**Comment by tgoyne** [comment]
Our benchmarking when we first added the thread check to Cocoa showed that it had an unmeasurable impact on anything but the cheapest of operations (e.g. reading a bool property on an object) and even there it wasn't significant.

**Comment by cmelchior** [comment]
Benchmarking prototypes shows no benefit in pursuing this approach at this point. Closing
