### ISSUE TITLE
Reproducible segmentation fault on trying to open a Realm file

### ISSUE THREAD

**Issue by raja-baz** [realm/realm-java#5302]
#### Description

I have a realm cache I pulled out of an installed instance of our app(production build, installed from store, no weird shenanigans going on). The app currently crashes on launch when trying to read the realm in question.

I pulled it out of the device, tried to load it in the desktop realm browser(latest version), it crashed it as well. So this seems to be an issue in realm-core but I'm posting it here because the file itself was generated from realm-java

#### The crash

```
09-21 12:45:52.697 10862 10862 F libc    : Fatal signal 11 (SIGSEGV), code 1, fault addr 0xc88760ce in tid 10862 (com.anghami)
09-21 12:45:52.789 10895 10895 F DEBUG   : *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
09-21 12:45:52.789 10895 10895 F DEBUG   : Build fingerprint: 'google/sailfish/sailfish:8.0.0/OPR3.170623.007/4286350:user/release-keys'
09-21 12:45:52.789 10895 10895 F DEBUG   : Revision: '0'
09-21 12:45:52.790 10895 10895 F DEBUG   : ABI: 'arm'
09-21 12:45:52.790 10895 10895 F DEBUG   : pid: 10862, tid: 10862, name: com.anghami  >>> com.anghami <<<
09-21 12:45:52.790 10895 10895 F DEBUG   : signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0xc88760ce
09-21 12:45:52.790 10895 10895 F DEBUG   :     r0 dd1bb908  r1 c88760ce  r2 cb7989a1  r3 c88760ce
09-21 12:45:52.790 10895 10895 F DEBUG   :     r4 dd1bb998  r5 dd1bb908  r6 00000001  r7 00000000
09-21 12:45:52.790 10895 10895 F DEBUG   :     r8 00000000  r9 00000000  sl dd1b3e90  fp ffab8ec0
09-21 12:45:52.790 10895 10895 F DEBUG   :     ip cb8b2e34  sp ffab8bb0  lr cb720c67  pc cb7989a6  cpsr 40070030
09-21 12:45:52.792 10895 10895 F DEBUG   :
09-21 12:45:52.792 10895 10895 F DEBUG   : backtrace:
09-21 12:45:52.792 10895 10895 F DEBUG   :     #00 pc 000989a6  /data/app/com.anghami-92GS1FzrO0vSXUc839kCQg==/lib/arm/librealm-jni.so
```

#### The realm file in question

[cache.realm.zip](https://github.com/realm/realm-java/files/1320695/cache.realm.zip)

#### Version of Realm and tooling
Realm version(s): 3.7.2

Realm sync feature enabled: no

Which Android version and device: Any

**Comment by Zhuinden** [comment]
Do you have a complete backtrace?

**Comment by raja-baz** [comment]
What I posted is all I have (had to pull it out of logcat and that's all it
gave me) but it's extremely easy to reproduce, that realm file even crashes
the Mac app, so if you need more info, just reproduce it under a controlled
environment

**Comment by beeender** [comment]
Got some more information and created a core issue https://github.com/realm/realm-core/issues/2874

Let's discuss there.
