### ISSUE TITLE
JSON parser throws IndexOutOfBoundsException when converting ISO8601-compliant dates with a 2-digit time zone designator

### ISSUE THREAD

**Issue by JussiPekonen** [realm/realm-java#5309]
#### Goal

I want to parse JSON data that contains ISO8601-compliant timestamps with a 2-digit time zone designator, such as `2017-09-20T20:00:00+04`, using Realm’s own JSON parse. Based on the discussion on Issue #1213 the parser should support all valid ISO8601 dates. According to IS8601, the time zone can be indicated with only 2 digits.

#### Expected Results

The JSON is parsed successfully and the object(s) is(are) created successfully.

#### Actual Results

The parser throws IndexOutOfBoundException with message "Mismatching time zone indicator: GMT04 given, resolves to GMT0400".

#### Steps & Code to Reproduce

Create a class with a Date field. Try to convert JSON data that contains the corresponding parameter as a valid ISO8601 date with a 2-digit time zone designator using Realm’s own parser. Observe the exception to be thrown.

#### Code Sample

Example class:
```
public class Foo extends RealmObject {
    private Date bar;
}
```

JSON parsing:
```
final String json = "{\"bar\":\"2017-09-20T20:00:00+04\"}";
final Realm realm = Realm.getDefaultInstance();
realm.beginTransaction();
realm.createOrUpdateObjectFromJSON(Foo.class, json);
realm.commitTransaction();
realm.close();
```

That will lead to IndexOutOfBoundsException with the message given above.

#### Version of Realm and tooling
Realm version(s): 3.7.2 (was originally observed with 3.5.0)

Realm sync feature enabled: no

Android Studio version: -

Which Android version and device: -

**Comment by cmelchior** [comment]
Closed by https://github.com/realm/ros/pull/382

**Comment by Zhuinden** [comment]
@cmelchior you mean https://github.com/realm/realm-java/pull/5327 ?
