### ISSUE TITLE
java.lang.IllegalArgumentException: Object not managed by Realm, so it cannot be removed

### ISSUE THREAD

**Issue by miPlodder** [realm/realm-java#5316]
I'm trying to delete Object from realm, but first time, I try to delete it, the application crashes, but then I reopen the application and try to delete, it is deleted. (doing this is recycler view)

```
realm.executeTransaction(new Realm.Transaction() {
                    @Override
                    public void execute(Realm realm) {

                        NotesPOJO note = notes.get(key);
                        note.deleteFromRealm();   //this is the line which shows the error


                    }
                });
```

For second attempt for item of recycler view, its deleting but for the first attempt the application is crashing.

**Comment by Zhuinden** [comment]
What is

> NotesPOJO note = notes.get(key);

?

**Comment by Zhuinden** [comment]
My wager goes for that the object in `notes` is not a managed object, so calling `deleteFromRealm()` on it throws an illegal state exception saying that to delete an object it has to be managed, but this is just my guess.

**Comment by Zhuinden** [comment]
> java.lang.IllegalArgumentException: Object not managed by Realm, so it cannot be removed

That's simple, it's because `notes` is some kind of map, not a RealmResults or anything, and the `NotesPOJO` you're storing inside it is not a managed RealmObject (was not obtained by querying Realm).

To delete an object from the Realm, the object you call `deleteFromRealm()` on has to be managed, aka it must be obtained from a `RealmQuery`.

**Comment by miPlodder** [comment]
In documentation, its written 
```
Dog dog = results.get(5);
dog.deleteFromRealm();
```

The first time, when I delete objects, I added a **LOG** message which is "_com.example.saksham.notemakerclipboard.Model.NotesPOJO@873e06b_" and the application was crashing here.

Whereas, I open my application again after crash, and now I am able to delete and the **LOG** message is "_NotesPOJO = proxy[{index:1},{text:},{timeStamp:Sun, 24 Sep 2017 14:53 PM}]_"

**Comment by Zhuinden** [comment]
Apparently you're mixing managed and unmanaged objects in an ArrayList or something.

But this is precisely what using `RealmResults + RealmRecyclerViewAdapter` are supposed to solve.

**Comment by miPlodder** [comment]
Can you write some demo code ?

**Comment by Zhuinden** [comment]
https://github.com/Zhuinden/rx-realm-recyclerview-experiment/blob/a5a1bcbecf24203ea2973d6a9223825aa7aa1aff/app/src/main/java/com/zhuinden/rxrealm/path/cat/CatAdapter.java#L18
