### ISSUE TITLE
To check if RealmResults ChangeListener reports insertions while deleting objects in Realm.

### ISSUE THREAD

**Issue by SarthakM9** [realm/realm-java#5318]
#### Goal

To check if deletions in RealmResults reports insertions.

see: https://stackoverflow.com/questions/46199239/deleting-objects-in-realmresults-somehow-triggers-a-insertion-change-listener

#### Expected Results

> when deleting realm objects, ChangeListener should not report insertions.

#### Actual Results

>  Same as expected results.

#### Code Sample

https://github.com/SarthakM9/RealmTest

#### Version of Realm and tooling
Realm version(s): 3.7.2

Realm sync feature enabled: No

Android Studio version: 2.3.3

Which Android version and device: Nexus 5 Emulator API 24

**Comment by Zhuinden** [comment]
Why is it that even though Kotlin users have the `.use() {` clause, they still manage to [not close Realms they open](https://github.com/SarthakM9/RealmTest/blob/master/app/src/main/java/com/sample/realmtest/realm/RealmManager.kt#L47)?

**Comment by SarthakM9** [comment]
@Zhuinden sorry, missed that! :)
The pattern we are using in our main project cannot be used with library functions, so we manage realm instances manually! :)

**Comment by beeender** [comment]
@SarthakM9 I just played your project, first I added lots of object by clicking the `Add Message`, then I click `Remove Message`. But i have never seen the `Test: insertions` in the log. Is there any tricks to reproduce it?

**Comment by SarthakM9** [comment]
@beeender I mentioned on SO as well that I am not seeing this issue in my project! This was just a sample project to show that everything is working as expected! :)

**Comment by beeender** [comment]
@SarthakM9 Oppppppps ..... I mentioned the wrong guy on the SO!!! Really sorry for that!! 

Thanks a lot for your sample project!! I will just mention the original author to ask him to make a project to show the problem .....

**Comment by SarthakM9** [comment]
@beeender No worries! most of the code was already written! :)
