### ISSUE TITLE
Realm Java 4.0 Doc updates

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#5321]
We need to update the website docs for the breaking changes gone into 4.0:

- Array of Primitives + be really explicit about what is missing and will come in 4.1
- RxJava 2 
- Other things?

**Comment by Zhuinden** [comment]
Is the ability to add value lists to existing schemas really missing in 4.0? :o

**Comment by cmelchior** [comment]
Right now it is, but next week, hopefully not.

**Comment by Zhuinden** [comment]
...wait, so is Realm-Java 4.0 going to use Realm-Core 4.0?

Surprised to see such a quick Core version, but okay!

Although I see it brings file format upgrade along with it. No going back! 😄

**Comment by cmelchior** [comment]
Semantic version is a pain sometimes. Realm Core 4.0 only brings support for a single new thing required for primitive array support. We just discovered it was missing during testing :)

**Comment by cmelchior** [comment]
Fixed in https://github.com/realm/realm.io/pull/3864
