### ISSUE TITLE
RealmTransformer Performance

### ISSUE THREAD

**Issue by eygraber** [realm/realm-java#5322]
If I do a clean build of my app, and profile it, I see that `transformClassesWithRealmTransformerForDebug` takes ~30 seconds. I have 20 realm models in the project. Does that make sense?

**Comment by Zhuinden** [comment]
I mean it has to replace any field access with proxy accessors, so probably yeah

**Comment by beeender** [comment]
We have an open issue to track the performance of transformer. See #3034 

But we haven't found time to optimize it :(
