### ISSUE TITLE
contains (case insensitive)  - not work for cyrillic.

### ISSUE THREAD

**Issue by lmdic** [realm/realm-java#5326]
Realm 3.7.2
```

public class Profile extends RealmObject {
    @PrimaryKey
    private long id;
    private String name;
}

...
profileAdapter.updateData(realm.where(Profile.class)
                     .contains(Profile.NAME, newText.trim(), Case.INSENSITIVE)
                    .findAllSorted(Profile.NAME));


```

If the `Profile.NAME `is on latin, then `contains` is sucess work. But if `Profile.NAME` is on cyrillic then `contains` is not correct work. Not found name of cyrillic.

**Comment by beeender** [comment]
can you please let us know what is the specific cyrillic strings for fields of `Profile.NAME` and `newText.trim()`??

**Comment by lmdic** [comment]
I has fragment that show all profiles names:

In this fragment I has Android component **SearchView**.
This component filter profile names "on fly" when input some text.
I want to filter input text with **case insensitive**.
When I input text on Latin the names is correct filtered.
When I input text on Cyrillic then names not correct filtered.

Here all values on Cyrillic (Profile names):

```
current_profile: {id = 108, name = Without name}
current_profile: {id = 109, name = Without surname}
current_profile: {id = 110, name = Клуб Молодых}
current_profile: {id = 112, name = Клубная компания}
current_profile: {id = 113, name = Любители клубов}
current_profile: {id = 102, name = Русская компания}

```

So I use this code:


```
    @Override
    public boolean onQueryTextChange(String newText) {
        Log.d(TAG, "onQueryTextChange: newText = " + newText);
        if (TextUtils.isEmpty(newText)) {
            profilesAdapter.updateData(realm.where(Profile.class)
                    .findAllSorted(Profile.NAME));
        } else {
            profilesAdapter.updateData(realm.where(Profile.class)
                    .contains(Profile.NAME, newText.trim(), Case.INSENSITIVE)
                    .findAllSorted(Profile.NAME));
        }
        return false;
}
```

So I want to find all names that contains text "**клуб**" with **case insensitive**.

Here result of logcat when input text:

```
onQueryTextChange: newText = к
onQueryTextChange: newText = кл
onQueryTextChange: newText = клу
onQueryTextChange: newText = клуб
```

The result must be next:

```
Клуб Молодых
Клубная компания
Любители клубов
```

But result is
`Любители клубов`

As you can see I use **Case.INSENSITIVE.**
Why it not found another name with word "**клуб**" ?

**Comment by beeender** [comment]
Oh... it is case insensitive match ... I am sorry that case insensitive match is not supported by realm-java right now.

There is an open issue to track this https://github.com/realm/realm-java/issues/1031

And the relevant core issue: https://github.com/realm/realm-core/issues/777

**Comment by Zhuinden** [comment]
Yeah, that is important detail.

I used to remove accents from letters to bypass this limitation using https://stackoverflow.com/a/36500456/2413303 but I do not know how to make it work for cyrillic

**Comment by cmelchior** [comment]
Closing as duplicate

**Comment by nikitoSha** [comment]
Not working with russian language. Even "contains" without Case. Realm returns not all rows for russian search string :(
