### ISSUE TITLE
Duplicate objects when id is marked as PrimaryKey.

### ISSUE THREAD

**Issue by waqasmoazzam88** [realm/realm-java#5330]
Inserting list of Offers with id property annotated as PrimaryKey still adds duplicate items in realm table. If I use copyToRealm method instead of copyToRealmOrUpdate then I get an exception regarding primary key constraint. I want to use copyToRealmOrUpdate/insertOrUpdate methods but primary key constraint is not being enforced as I see duplicates.

> Describe your current debugging efforts.
I set breakpoints inside copyOrUpdate method in OfferRealmProxy.java. There I saw cache which is a Map uses Offer object as key. If the list I am inserting has 5 Offer objects out of which 3 are same with id="3" should not map key be Offer.id to keep items unique in the map? Keeping full object as key does not seem to work. I provided equals and hash methods in Offer class as well. I believe primary key should be the key in that Map

#### Code Sample

```
public class Offer extends RealmObject {
    
   @PrimaryKey private String id;
    private Date timestamp;
    private String imageUrl;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public Date getTimestamp() {
        return timestamp;
    }

    public void setTimestamp(Date timestamp) {
        this.timestamp = timestamp;
    }

    public String getImageUrl() {
        return imageUrl;
    }

    public void setImageUrl(String imageUrl) {
        this.imageUrl = imageUrl;
    }

    @Override
    public boolean equals(Object o) {
        if (this == o) return true;
        if (o == null || getClass() != o.getClass()) return false;

       Offer that = (Offer) o;
        return id.contentEquals(that.id);
    }

    @Override
    public int hashCode() {
        return id.hashCode();
    }
}


saving it in realm like this: 


public void saveOffers(final List<Offer> Offers) {
        Realm realm = getRealmInstance();
       realm.executeTransaction(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {
                realm.delete(Offer.class);
                realm.copyToRealmOrUpdate(offers);
            }
        });
        realm.close();
}
```
#### Version of Realm and tooling
Realm version(s): 3.7.2

Realm sync feature enabled: no

Android Studio version: 2.3.3

Which Android version and device: OS 7.1 on Samsung Galaxy s7 Edge

**Comment by beeender** [comment]
hi, we have a test case to ensure that:

```
    @Test
    public void copyToRealmOrUpdate_iterable() {
        realm.executeTransaction(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {
                PrimaryKeyAsLong obj = new PrimaryKeyAsLong();
                obj.setId(1);
                obj.setName("Foo");
                realm.copyToRealm(obj);

                PrimaryKeyAsLong obj2 = new PrimaryKeyAsLong();
                obj2.setId(1);
                obj2.setName("Bar");

                PrimaryKeyAsLong obj3 = new PrimaryKeyAsLong();
                obj3.setId(1);
                obj3.setName("Baz");

                realm.copyToRealmOrUpdate(Arrays.asList(obj2, obj3));
            }
        });

        assertEquals(1, realm.where(PrimaryKeyAsLong.class).count());
        assertEquals("Baz", realm.where(PrimaryKeyAsLong.class).findFirst().getName());
    }
```


Can you reproduce the problem in a sample project so we can take a look? You can send the project to help@realm.io if you want to share it privately.

**Comment by waqasmoazzam88** [comment]
Hey, I extracted offer class and realm utility class. Used Gson to convert JSON into list of offers and saved through realm copyToRealmOrUpdate method. But this time it is not duplicating. Not sure what is wrong in the original project.

**Comment by beeender** [comment]
OK! I will keep this issue opened for a while. Please let us know if there is more information about this.

**Comment by ghgef** [comment]
i want filter the duplicate names in realm database when i am adding mobile contacts in listview. i donot want add same name in 2 times in listview

**Comment by Zhuinden** [comment]
You might want to consider using `distinctValues("name")` then in your RealmQuery
