### ISSUE TITLE
"Invalid Object" when I print the Arraylist of POJO

### ISSUE THREAD

**Issue by miPlodder** [realm/realm-java#5334]
Why is it showing "Invalid Object" when I add object to the REALM DB, but when I open the application again, then my Arraylist is not showing "Invalid Objects for previously created Object" ?

![device-2017-09-28-034857](https://user-images.githubusercontent.com/22195621/30940816-1fe71cd6-a400-11e7-91b4-e76218fc7c6d.png)

**Comment by miPlodder** [comment]
I guess, I found that the problem is this function "**executeTransactionAsync**". When I executed "executeTransaction" it didnot showed "Invalid Object" ?

**Comment by Zhuinden** [comment]
You kinda need to add the relevant code snippet for people to figure out what's happening, maybe even specify what you did to make that happen...

**Comment by miPlodder** [comment]
This is the Snippet of code which executed.

```
realm.executeTransactionAsync(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {
                POJO user = realm.createObject(POJO.class, etId.getText().toString());
                user.setNote(note);
                list.add(user);
                realm.copyToRealmOrUpdate(user);
            }
        }, new Realm.Transaction.OnSuccess() {
            @Override
            public void onSuccess() {
                Toast.makeText(MainActivity.this, "Success", Toast.LENGTH_SHORT).show();
            }
        }, new Realm.Transaction.OnError() {
            @Override
            public void onError(Throwable error) {
                Toast.makeText(MainActivity.this, "Error", Toast.LENGTH_SHORT).show();
            }
        });
```

**Problem**

**_(Showing Invalid Object after inserting and viewing)_**
![screenshot_2017-10-07-23-13-06-281_com example testapplication](https://user-images.githubusercontent.com/22195621/31310519-0a6e0c48-abb7-11e7-8958-f948c3aeaaa2.png)


**_(But after closing, opening again, and them viewing it working fine)_**
![screenshot_2017-10-07-23-14-00-960_com example testapplication](https://user-images.githubusercontent.com/22195621/31310538-721f0266-abb7-11e7-9a5f-64843d732383.png)

I guess there is some sort of problem/bug in **Async Execution** as if I execute the save code in the **Sync Execution**, it works fine.
```
realm.executeTransaction(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {

                POJO user = realm.createObject(POJO.class, etId.getText().toString());
                user.setNote(note);

                list.add(user);

                realm.copyToRealmOrUpdate(user);

            }
        });
```

**Comment by Zhuinden** [comment]
Because you're adding the managed object of the background thread Realm to the list which you are accessing on the UI thread.

**Comment by miPlodder** [comment]
Then, how would I be able to add my data from realm to Arraylist (which is in UI Thread) without having to close and open the application again ?

**Comment by Zhuinden** [comment]
https://realm.io/docs/java/latest/#reuse-realmresults-realmobjects

**Comment by miPlodder** [comment]
**Got it**, But had to add a condition to insert only the last added **item** to the **list**.
```
for(POJO item : result) {

                    if(index == list.size())
                        list.add(item);

                    index++;
                }
```

**Morever, are all the items of Realm DB stored in order of insertion or randomly like HashMap, because that my above logic will fail ?**

**Comment by cmelchior** [comment]
@miPlodder We do not make any guarantees. Most of the time it will be by order of insertion though.  This is why you should always use `findAllSorted()` if you want a sorted order when reading items.

**Comment by miPlodder** [comment]
Is it possible to find Object sorted using timestamp ( if my POJO object has a data field for timestamp ) , i guess the algorithm is just similar to **_compareTo()_** ?

**Comment by Zhuinden** [comment]
That's what `findAllSorted("dateField", Sort.ASCENDING)` is for

**Comment by miPlodder** [comment]
It not working, as its sorting them in **Alphabetical Order**. For example,  _Thur and Tues_ are added together, but Wednesday should be in between them.

**Comment by Zhuinden** [comment]
Then add a rank `int` field and sort based on that.

**Comment by Zhuinden** [comment]
...you know, what I didn't realize is... why on earth is the Date stored as a String, instead of `Date`? :smile:
