### ISSUE TITLE
Annotations `@Ignore`, `@PrimaryKey`, `@Index` and `@Required` are not retained for RUNTIME

### ISSUE THREAD

**Issue by Zhuinden** [realm/realm-java#5344]
#### Goal

> What do you want to achieve?

I'm tinkering with auto-migration based on reflection.

#### Expected Results

I would hope to be able to access the `@Ignore`, `@PrimaryKey`, `@Index` and `@Required` annotations with `field.getAnnotation(annotationClass)`.

#### Actual Results

The annotations are not retained for runtime, only for class.

#### Code Sample

I'm experimenting with this [here](https://github.com/Zhuinden/realm-auto-migration/blob/18063e72f1b9169953adddbf7232ea6a485a256f/auto-migration/src/main/java/com/zhuinden/realmautomigration/AutoMigration.java#L209) and I was hoping I wouldn't need to write an annotation processor for it 😄 

Of course, this is nothing critical, considering Realm doesn't use it for reflection, only for annotation processing, so `RetentionPolicy.CLASS` makes perfect sense.

So it's like, totally up to you. 

Technically I can just define my own annotations otherwise.

#### Version of Realm and tooling
Realm version(s): 3.7.2

Realm sync feature enabled: no

Android Studio version: 2.3.3

Which Android version and device: irrelevant

**Comment by beeender** [comment]
secret thing: if you want to support automatic migration, just change this https://github.com/realm/realm-java/blob/master/realm/realm-library/src/main/java/io/realm/internal/OsRealmConfig.java#L189 to `SCHEMA_MODE_AUTOMATIC`

**Comment by cmelchior** [comment]
I'm sympathetic towards making it easier for other library developers to work with Realm. We did a similar thing with the annotation processor where we didn't consume the annotations.

Keeping these annotations in the class file would be a (very) small increase, so I would be fine with that.
