### ISSUE TITLE
Facebook Authentication - INVALID_PARAMETERS(601) "Your request parameters did not validate"

### ISSUE THREAD

**Issue by seferdemir** [realm/realm-java#5345]
I get an error code even though I have edited the configuration.yml file.

#### Facebook Authentication Provider

> https://realm.io/docs/realm-object-server/#facebook

#### Version of Realm and tooling
Realm version(s): 3.5.0

Realm sync feature enabled: yes

Android Studio version: 2.3.3

Which Android version and device: API level 21 version 5 / LG-D855

**Comment by Zhuinden** [comment]
My wild guess goes for that you might need to set things up in the Facebook developer console to make it allow the ROS to communicate with it.

Most likely to do with https://developers.facebook.com/docs/facebook-login/android/

**Comment by beeender** [comment]
And check if https://realm.io/docs/realm-object-server/#facebook helps

**Comment by seferdemir** [comment]
@Zhuinden thaks for your reply. What is the ROS? How can i do it?

**Comment by seferdemir** [comment]
@beeender thanks for your reply. I already did it. The problem continues. Likewise, Google sign-in does not work too.

**Comment by Zhuinden** [comment]
@seferdemir Google might require some additional configuration in the Google API Console, according to https://developers.google.com/identity/sign-in/android/sign-in

You might need to set up your debug keystore's SHA-1 fingerprint. I know I had trouble with Google Login because of the SHA-1 thing.

**Comment by seferdemir** [comment]
@Zhuinden it is debug keystore's SHA-1 as you said. However, the sign-in does not respond. Then the pop-up window closes. How did you solve it?

**Comment by seferdemir** [comment]
Is there someone who can help me? I've been working for two weeks :(

**Comment by cmelchior** [comment]
@seferdemir Can you post the provider section of your `configuration.yml`. Also, can you post how you are getting the facebook token?

**Comment by seferdemir** [comment]
@cmelchior thanks for your interest. my `configuration.yml` file is below.
[configuration.txt](https://github.com/realm/realm-java/files/1349491/configuration.txt)

And i am getting the facebook token like the demo app. `https://github.com/realm-demos/realm-tasks`.
I am using the FacebookAuth.java. `https://github.com/realm-demos/realm-tasks/blob/master/RealmTasks%20Android/app/src/main/java/io/realm/realmtasks/auth/facebook/FacebookAuth.java`

```java
    // Setup Facebook Authentication
    facebookAuth = new FacebookAuth((LoginButton) findViewById(R.id.login_button)) {
        @Override
        public void onRegistrationComplete(final LoginResult loginResult) {
            UserManager.setAuthMode(UserManager.AUTH_MODE.FACEBOOK);
            SyncCredentials credentials = SyncCredentials.facebook(loginResult.getAccessToken().getToken());
            SyncUser.loginAsync(credentials, AUTH_URL, SignInActivity.this);
        }
    };
```

**Comment by seferdemir** [comment]
I solved the problem as follows:

    signingConfigs {
        config {
            storeFile rootProject.file("keystore/debug.keystore")
            storePassword "android"
            keyAlias "androiddebugkey"
            keyPassword "android"
        }
    }

    buildTypes {
        release {
            signingConfig signingConfigs.config
        }
    }

**Comment by rnandyala** [comment]
I am having the same issue
  signingConfigs {
        config {
            keyAlias 'androiddebugkey'
            keyPassword 'android'
            storeFile rootProject.file("C:\\Users\\rajap\\.android\\debug.keystore")
            storePassword 'android'
        }
    }

    buildTypes {
        debug {
            signingConfig signingConfigs.config
        }
    }
added these lines to my build file but I still get the same error
//
passing Accesstoken to credential and URL is my cloud instance
SyncUser.logInAsync(credentials, auth_url, new SyncUser.Callback<SyncUser>() {
            @Override
            public void onSuccess(SyncUser user) {
                // SyncConfiguration defaultConfig = new SyncConfiguration.Builder(user, Constant.REALM_BASE_URL).build();
                // Realm.setDefaultConfiguration(defaultConfig);
                //SyncConfiguration configuration = SyncUser.current().getDefaultConfiguration();
                //Realm.setDefaultConfiguration(configuration);
                Intent i = new Intent(MainActivity.this, Activity2.class);
                i.putExtra("key1", "success");
                startActivity(i);
            }

            @Override
            public void onError(ObjectServerError error) {
                Log.e("tag1", "can be anything" + error.getMessage());
            }
        });
    }

**Comment by i-schuetz** [comment]
How to solve this in iOS? Getting this error for Facebook and Google. It used to work.
