### ISSUE TITLE
Valid model classes must either extend RealmObject or implement RealmModel.

### ISSUE THREAD

**Issue by trantronghien** [realm/realm-java#5347]
I followed the example [Inheritance / Polymorphism #761](https://github.com/realm/realm-java/issues/761) but I have a problem that is "classes must either extend RealmObject or implement RealmModel"
BaseModel.class
```
public abstract class BaseModel extends RealmObject {
    @Expose(serialize = false , deserialize = false)
    @PrimaryKey
    protected long id;

    @Expose(serialize = false , deserialize = false)
    protected boolean statusUpdate;
}
```
Sms.class
```
public class Sms extends BaseModel{
    @Ignore
    @Expose(serialize = false , deserialize = false)
    private String body;
    @SerializedName("name")
    private String name;
    @SerializedName("number")
    private String number;
   ..... geter and setter
}
```

**Comment by beeender** [comment]
Polymorphism is not supported right now. I guess the example you talked about is the sample code that we were discussing about how to support it.

**Comment by Zhuinden** [comment]
The workaround is https://github.com/realm/realm-java/issues/761#issuecomment-299627923
