### ISSUE TITLE
custom method in realm class. Error: Only getters and setters should be defined in model classes

### ISSUE THREAD

**Issue by Daffodil23** [realm/realm-java#5352]
I'm using list and on list item click I've to open link in the browser. I'm using Dictionary to store data(URL, description) now I want to assign dictionary to list adapter, since it cannot be done as it only allows string. I want to  extend toString() method in my realm class so it can return only description. 

I cannot extend .toString() in realmobject class, getting the following error:

  @Override
    public String toString() {
        return description;
    }

Error:(57, 19) error: Only getters and setters should be defined in model classes

**Comment by cmelchior** [comment]
This is because you are using a version of Realm that does not support overriding `toString()`. Upgrading to the latest version (currently 5.3.1) should fix this.

**Comment by Zhuinden** [comment]
Honestly, any version after 0.88.0 supports `toString()`
