### ISSUE TITLE
How call method in Fragment after success loaded all data?

### ISSUE THREAD

**Issue by lmdic** [realm/realm-java#5353]
Some service class (not Fragment):

MyService.java:

```
private void loadProfiles() {
        Realm.getInstanceAsync(Realm.getDefaultConfiguration(), new Realm.Callback() {
            @Override
            public void onSuccess(Realm realm) {
                Log.d(TAG, "onSuccess: All profiles was success loaded!!!");
            }

            @Override
            public void onError(Throwable throwable) {
            }
        });
}
```

I also has **Fragment** that show all profiles in list.

```
public class OrganizationsFragment extends Fragment {

@Override
    public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
}

private void allDataSuccessLoaded() {
 // do some thing when all data (profiles) was success loaded
...
 
}
```
In my fragment I has method `allDataSuccessLoaded().` 
I need to call this method **ONLY AFTER** was success called method in MyService: `MyService.loadProfiles().onSuccess()`.

How I can do this?

**Comment by nhachicha** [comment]
@lmdic you can use Android [Messenger](https://developer.android.com/reference/android/os/Messenger.html) or [ResultReceiver](https://developer.android.com/reference/android/os/ResultReceiver.html) to send a message from the `Service` to the `Activity/Fragment` once the Realm has been synchronously opened. So you can start using the instance and call `allDataSuccessLoaded`.
