### ISSUE TITLE
When to provide a custom query structure

### ISSUE THREAD

**Issue by wb1992321** [realm/realm-java#5360]
When to provide a custom query structure
We need to query to return a custom structure, and even a specific basic data type field

**Comment by Zhuinden** [comment]
I do not understand the question.

**Comment by cmelchior** [comment]
@wb1992321 Can you clarify what you mean?

**Comment by wb1992321** [comment]
I hope that through the query can be customized to return to a table of a set of attributes, for example: class all students name, I just need a name of a collection of fields!
And I would like to query the third grade and third grade two classes to participate in the afternoon speech students! How are these slightly more complicated queries going on?

**Comment by Zhuinden** [comment]
Realm doesn't support projection because it is an object database. If you need to access only a few properties, then just call the right getters on the managed object returned by Realm. Every access is lazy-loaded, so you don't load more elements into memory than what you actually ask for.

So for example, you can make a query against `Student` class like `realm.where(Student.class).equalTo("grade", 2).findAll()` or whatever your schema is.

See [the documentation for more information on queries](https://realm.io/docs/java/latest/#queries).

**Comment by wb1992321** [comment]
I would like to know how to reverse the query, for example: I would like to query to return to meet the conditions of the dogs

**Comment by beeender** [comment]
@wb1992321 https://realm.io/docs/java/latest/#link-queries

**Comment by wb1992321** [comment]
`public class Person extends RealmObject implements Parcelable, ItemBean {

    @PrimaryKey
    private long userId;
    private long companyId;
    private long departmentId;
    @Index
    private String extensionTel;
    private String job;
    @Index
    private String officeTel;
    @Index
    private String personalTel;
    @Index
    private String userName;

    @Index
    private String pinyin;
    private String shortPinyin;
    private String indexPinyin;
}`
`public class Department extends RealmObject implements Parcelable, ItemBean {

    @PrimaryKey
    private long departmentId;
    private long companyId;
    private String departmentName;
    private RealmList<Person> person;

    private String pinyin;
    private String shortPinyin;
    private String indexPinyin;
}`
If I want to query a person collection but the query conditions are departmentName and userName and even the companyName
How can i ask? I think this scene is not uncommon, right? After all, this structure is returned by the server

**Comment by wb1992321** [comment]
@beeender Sorry! I want to get dogs

**Comment by beeender** [comment]
@wb1992321 Sorry, i posted a wrong link. here is he right one https://realm.io/docs/java/latest/#inverse-relationships

try add `@LinkingObjects` then do the linking query, like:

```
public class Person extends RealmObject implements Parcelable, ItemBean {
    // ....
    @LinkingObjects("person")
    private RealmResults<Department> departments;
}

// query
realm.where(Person.class).equalTo("userName", "someName").equalTo("departments.departmentName", "someName").findAll();
```

**Comment by wb1992321** [comment]
error：
`Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.`

**Comment by wb1992321** [comment]
@beeender 
![image](https://user-images.githubusercontent.com/10239402/31063445-93df0e0a-a6f8-11e7-9fe5-919e2cdddc06.png)

**Comment by wb1992321** [comment]
@beeender 
`错误: A @LinkingObjects field "cn.timeface.contact.bean.Person.departments" must be final.
1 个错误`

How to do?

**Comment by beeender** [comment]
```
private final RealmResults<Department> departments = null;
```
