### ISSUE TITLE
case insensitive search

### ISSUE THREAD

**Issue by petersnoopy** [realm/realm-java#537]
Hello, I want to use Realm in combination with a ListView using RealmBaseAdapter. In my case I also need a SearchView to filter the list. The following is a examle how I want to filter:

RealmResults<User> r = realm.where(User.class)
                            .beginGroup()
                                .contains("name", searchString)
                            .endGroup()
                            .findAll();

How can I perform case insensitive queries? Like this:
select \* from user where lower(name) = 'fred';

**Comment by janswist** [comment]
It's now working properly - when I have `John` it will not find it by typing lower case `j` when using `contains` or `beginsWith`

**Comment by prashant31191** [comment]
RealmResults<DLocationModel> arrDLocationModel = realm.where(DLocationModel.class)
                    .contains("Country", strTextCountry, Case.INSENSITIVE)
                    //.contains("Country", strTextCountry,false)
                    //.containsIgnoreCase("Country", strTextCountry)
                    .findAll();
