### ISSUE TITLE
Real escape  image size on save transaction

### ISSUE THREAD

**Issue by sdarvish** [realm/realm-java#5370]
hi, i have a model that has a field  'photoUrl'  , its like this ["photo_url": "http://towerpal.dev.edoramedia.com/img/315/Arch2O-Empire-Tower-Abu-Dhabi-UAE-2.jpg/555x600"]("photo_url": "http://towerpal.dev.edoramedia.com/img/315/Arch2O-Empire-Tower-Abu-Dhabi-UAE-2.jpg/555x600")
at the first time a save this model every thing is ok but when i update an object the realm escape '/555x600' this part of image url.

**Comment by Zhuinden** [comment]
considering this is a string, you're most likely saving an escaped version when you're updating it.

**Comment by cmelchior** [comment]
Realm is not escaping anything in Strings, so most likely you have some code somewhere doing that when updating the object.
