### ISSUE TITLE
Breaking WishList for 5.0

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#5372]
This ticket is for general discussion of the breaking changes in a future 5.0 release. Some items have been moved from #4785 

Please edit the main post to add a topic with a sequence number, and we can discuss it in the comments. If the breaking change is decided to be worthy to add, then create a separate issue for it.

1. Do not allow having both typed Realm instance and Dynamic Realm instance on the same thread. Throw an exception instead. This creates lots of troubles with Realm instance cache management. By disallowing it, the RealmCache implementation can be much simpler and give us an option to totally manage the Realm instance through Object Store.

2. Remove the mips so file since there is NO mips device in the market. Perhaps consider having a parameter in the `realm` closure for including `mips/arm` but not have them be part of the standard library. We would need to modify our build system for that.

**Comment by Zhuinden** [comment]
> Change the behavior of distinct() to work against query result. See #4774

Isn't this the same as 

> Calling distinct() on a sorted RealmResults no longer clears the sorting (#3503).

?

**Comment by cmelchior** [comment]
Yup. I closed the issue. Thanks 👍

**Comment by Zhuinden** [comment]
Haha, my most absurd breaking change wish would be to rename

`Realm.getInstance()` to `Realm.open()`

`Realm.getDefaultInstance()` to `Realm.openDefault()`

**Comment by Zhuinden** [comment]
I feel like the new sort mechanics should have the keyword `sorted` instead of just `sort`.

**Comment by cmelchior** [comment]
Replaced by #6500
