### ISSUE TITLE
waitForInitialData_resilientInCaseOfRetriesAsync fails

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#5373]
`SyncedRealmTests#waitForInitialData_resilientInCaseOfRetriesAsync` fails somewhat consistently on both CI and me locally.

I have only been able to reproduce it when running all tests in `SyncedRealmTests`, so perhaps it is interactions with previous tests, although given the error that is kinda weird.

Log from a failed run is:

```
10-03 08:37:29.034 4699-4740/io.realm.test A/REALM_JNI: An exception has been thrown on the sync client thread:
                                                        open("/data/data/io.realm.test/files/realm-object-server/d6769925c090ed605dd6235c9ad74a80/d6769925c090ed605dd6235c9ad74a80/tests.management/access_control.write.mx") failed: No such file or directory
10-03 08:37:29.035 4699-4740/io.realm.test E/AndroidRuntime: FATAL EXCEPTION: Thread-7
                                                             Process: io.realm.test, PID: 4699
                                                             io.realm.exceptions.RealmError: An exception has been thrown on the sync client thread:
                                                             open("/data/data/io.realm.test/files/realm-object-server/d6769925c090ed605dd6235c9ad74a80/d6769925c090ed605dd6235c9ad74a80/tests.management/access_control.write.mx") failed: No such file or directory
```

**Comment by beeender** [comment]
> open("/data/data/io.realm.test/files/realm-object-server/d6769925c090ed605dd6235c9ad74a80/d6769925c090ed605dd6235c9ad74a80/tests.management/access_control.write.mx") failed: No such file or directory

normally this caused by the test is finished, so we delete realm + remove the temp dir. But the realm instance on the sync client has not been closed.

**Comment by beeender** [comment]
with the new core API, we can make the `deleteRealm()` process safe which could also throw in `tearDown()` when `deleteRealm()` called.

**Comment by beeender** [comment]
OK, this test is not going to work before of #5416 
`deleteRealm` will always throw in the executor service because of the Realm instance on the sync client thread is not closed.
