### ISSUE TITLE
Direct Dependency on realm-android-library

### ISSUE THREAD

**Issue by eygraber** [realm/realm-java#5378]
Is it OK to just have a dependency on `realm-android-library` and not the plugin? It's for a library module that doesn't have any `RealmObject` or `RealmModel` in it.

**Comment by cmelchior** [comment]
If you don't have that, why have the dependency in the first place?

Our plugin does other things as well, like applying the transformer, so depending on your use case, it might or might not work, but you can see what our Plugin does here https://github.com/realm/realm-java/blob/master/gradle-plugin/src/main/groovy/io/realm/gradle/Realm.groovy, and then just copy whatever you need to your own build file.

**Comment by eygraber** [comment]
I still need it to access the `Realm` class. 

I took a look at that, and everything seems to be working so far; just wanted to get the official opinion.
