### ISSUE TITLE
Retrieve/copy recursive nested objects with fine-grained depth restriction

### ISSUE THREAD

**Issue by MrNovado** [realm/realm-java#5383]
I would like you to reconsider #4441
I have a data-driven application and the domain is composed with deeply nested objects like this:
```kotlin
open class Module : RealmObject() {
    var data: Data
    var children: RealmList<Module>? = null
}
```
Where's `data` is also a huge object with it's own dependencies.
Obviously I don't want:
- to retrieve/copy the entire hierarchy of these `modules` every time I need just one (and it's immediate children)
- to break my domain objects apart 
- and I can't use `realm.copyFromRealm(obj, maxDepth = 10)`, because `maxDepth` is global restriction

I think this particular case isn't solved in any ORM as of today. Which is sad because being able to work with objects with natural and intuitive hierarchies is much easier than with tables...

I feel like `Realm` have an opportunity and huge potential to become trully object-oriented-db by supporting (amongst polymorphism and other helpful stuff) fine-grained depth restrictions kinda like this:
```kotlin
realm.where(Module::class.java)
    .restrict('children', 'RECURSIVE_DEPTH', maxRecursiveDepth)
    .equalTo(...)
    .findAll()
---
realm.copyFromRealm(
    obj, 
    { restrictions ->
        restrictions
             .add('children', 'RECURSIVE_DEPTH', maxRecursiveDepth)
            .add(...)
    },
)
```

**Comment by Zhuinden** [comment]
I mean technically you only load an item when you access it with an accessor, so if you create a recursive traversal with a maximum depth parameter then you'll be able to read down to a maximum given depth.

**Comment by MrNovado** [comment]
Well, yes? But I only want to restrict the `children` field, not any other `module` level field like data which have it's own composition.
Right now the only ways to this:
- is to make a related DTO and use that instead of `realm.copy*`
- or not to use recursive composition at all and/or break it using ids lists
```kotlin
open class Module : RealmObject() {
    var data: Data
    var childrenIds: RealmList<ChildIds/String>? = null
    @Ignore var children: RealmList<Module>? = null
            get() {
                  Realm.getDefaultInstance().use { /* query children sync */ }
            }
}
```
Creating an infrastracture like this is ugly and a huge pain to continuously support...

**Comment by Zhuinden** [comment]
But as long as you can identify the module you actually want with a primary key for example, you only read the object you query for, and any other object you access with accessors.

Realm doesn't read unless accessed, that's the primary selling point of the managed objects.

**Comment by MrNovado** [comment]
I get that, but I want my objects to be unmanaged... I yet to see any good examples with live data.

**Comment by Zhuinden** [comment]
Then read it with a depth of 2.

**Comment by MrNovado** [comment]
And what will happen with the `data` field that has depth of 6?

**Comment by cmelchior** [comment]
@MrNovado We do have sympathy for your use case, but we also have to consider our API complexity vs. how many actually can use a given feature.

What you are requesting is basically a way to map the internal object structure to something else when fetched, kinda like ViewModels, I have some ideas in that area that I would like to write up, but either way, it is not something that has a high priority.

For your specific use case, you can also consider cloning our Realm annotation processor, and change it so it outputs the code you want in some helper class.

**Comment by Zhuinden** [comment]
A possibility would be to create the unmanaged object, copy from Realm with depth 2 on one property and depth 6 on the other, and put them together into the unmanaged object.

**Comment by MrNovado** [comment]
@cmelchior I see. Should the issue stay or will you close it? Who knows maybe your immediate clients decided from the very start to work around this? Maybe this case will get more PR in some future as the demand for more complex apps grows?

Anyway, forking `Realm annotation processor` doesn't seem feasible for me short-term... And I want a dynamic solution -- the depth at which the data should be cloned is decided at runtime.

@Zhuinden This will make any domain refactoring a huge pain: any contributer will have to hold in mind that changing certain models must be reflected in repository layer in magic numbers. This will also potentually make data-validation much harder, or will force us to make complex map-transactions and DTOs.

@cmelchior  @Zhuinden, It seems the least painful workaround for me would be to partually migrate to managed-objects... Having an RX-based infrastructure I will have to:
- make sure I'am not moving any objects between threads (only ids maybe)
- make some kind of scoped manager for realm instances since they are closable
- define scopes
- probably predefine some single-threaded realm and realm-IO schedulers and use only sync transactions
- make sure that objects are edited inside transactions only (presentation layer ?)
- and everyone will have to be especially careful not to mix managed and unmanaged objects

Well, working with umanaged data seemed much easier.

**Comment by cmelchior** [comment]
@MrNovado I added a description of a concept of projections in #5426 which should support your use case. So I will be folding this issue into that one. If the proposed API doesn't support what you want, please let us know in that issue.

Closing.
