### ISSUE TITLE
Can't initiate Realm Configuration in AttachBaseContext in Application Class.

### ISSUE THREAD

**Issue by ViperAlpha** [realm/realm-java#5389]
#### Expected Results

Realm initialized with the RealmConfiguration.

#### Actual Results

java.lang.IllegalStateException: Call `Realm.init(Context)` before creating a RealmConfiguration

#### Steps & Code to Reproduce

Can't set realm configuration in Application class in attachBaseContext. it is possible in OnCreate.

#### Code Sample

```java

@Override
	protected void attachBaseContext(final Context base) {
		initRealm(base);
}
private void initRealm(Context context) {
		Realm.init(context);

		try {
			RealmConfiguration configuration = new RealmConfiguration.Builder().name(REALM_NAME).schemaVersion(1).deleteRealmIfMigrationNeeded()
					.build();
			Realm.setDefaultConfiguration(configuration);
		} catch (Exception ignore) {
			ignore.printStackTrace();
		}

	}

```

#### Version of Realm and tooling
Realm version(s): ?

3.7.2

Realm sync feature enabled: yes/no

no.

Android Studio version: ?

3.0 b7

Which Android version and device: ?

Emulator, any android version.

**Comment by Zhuinden** [comment]
have you tried calling `super.attachBaseContext(base)` first, then using `this`?

**Comment by ViperAlpha** [comment]
I haven't because  I need Realm to wrap my base context (according to user preference).

**Comment by Zhuinden** [comment]
....what?

**Comment by ViperAlpha** [comment]
I haven't found a way to change app. language at runtime without wrapping the base context. But anyway, I believe it is a bug because I still can use Realm before attaching, just can't set my configuration.

**Comment by Zhuinden** [comment]
Well if you check the source code, then [you can see that you get this error message if `BaseRealm.applicationContext == null`](https://github.com/realm/realm-java/blob/fd09f67604fd98b75abbe88ed6c576680cde6c60/realm/realm-library/src/main/java/io/realm/Realm.java#L320-L322), which means that the context you provide to `Realm.init(context)` has its `getApplicationContext()` method called, and [it returns `null`.](https://github.com/realm/realm-java/blob/fd09f67604fd98b75abbe88ed6c576680cde6c60/realm/realm-library/src/main/java/io/realm/Realm.java#L249)

**Comment by cmelchior** [comment]
Any reason you need to access the Realm that early in the app's lifecycle? We require the context to be able to find `context.getFilesDir()` without that, you will not be able to save or open any Realm file.

**Comment by ViperAlpha** [comment]
The reason why is I have a User.class and it has language preference. In my App initialization I do a ContextWrap. Realm works (it opens my db) without problem EVEN before attaching the baseContext. I can initialize Realm and use it, I just can't set a Configuration.

**Comment by cmelchior** [comment]
Looking into this, it seems you are right. The reason we are calling `context.getApplicationContext()` was original to protect against memory leaks, like people using an Activity for the Context.

However, given the pattern where Realm is normally initialized in the Application subclass, the chance of that happening is really low.

So I don't have a problem with us changing it to just use the Context directly.

**Comment by cmelchior** [comment]
See https://github.com/realm/realm-java/pull/5406
