### ISSUE TITLE
RealmList of a RealmObject [Error]

### ISSUE THREAD

**Issue by michaelspeed** [realm/realm-java#5392]
`Error:Element type of RealmList must be a class implementing 'RealmModel' or one of the 'java.lang.String', 'byte[]', 'java.lang.Boolean', 'java.lang.Long', 'java.lang.Integer', 'java.lang.Short', 'java.lang.Byte', 'java.lang.Double', 'java.lang.Float', 'java.util.Date'.`

i have two RealmObjects 

```
open class Comment : RealmObject(){
    @PrimaryKey var Id : String? = null
    var commentText : String? = null
    var commentType : String? = null
    var comment1: RealmList<Comment>? = RealmList()
    var comment2: Comment? = null
    var createdAt: Date? = null
    var file: File? = null
    var post: Post? = null
    var user: User? = null
    var reactions : RealmList<User>? = RealmList()
}
```

and 
```
open class User : RealmObject() {
    @PrimaryKey var Id: String? = null
    var userType: String = "User"
    var token: String? = null
    var name: String? = null
    var email: String? = null
    var profilePic: String? = null
    var emailAllow: String? = null
    var timeline: String? = null
    var appIntro : Boolean? = true
    var blockList : User? = null
    var blockedUser : User? = null
    var coverPic : User? = null
    var createdAt: Date? = null
    var dateofBirth : String? = null
    var files : RealmList<File>? = RealmList()
    var gender : String? = null
    var homeTown : String? = null
    var inRelation : User? = null
    var lastActivity : Date? = null
    var location : String? = null
    var messageses : RealmList<Message>? = RealmList()
    var playerID: String? = null
    var phonenumber : String? = null
    var post : RealmList<Post>? = null
    var postReactions : RealmList<Post>? = RealmList()
    var workContainers : RealmList<WorkContainer>? = RealmList()
    var alerts : RealmList<Notification>? = RealmList()
    var educationContainer : RealmList<EducationalContainer>? = RealmList()
    var friendList : FriendList? = null
    var grouChannels : RealmList<GroupChannel>? = RealmList()
}
```

#### Goal

Build

#### Expected Results

To create Realm many to many connections

#### Actual Results
Note: Processing class Comment
error: Element type of RealmList must be a class implementing 'RealmModel' or one of the 'java.lang.String', 'byte[]', 'java.lang.Boolean', 'java.lang.Long', 'java.lang.Integer', 'java.lang.Short', 'java.lang.Byte', 'java.lang.Double', 'java.lang.Float', 'java.util.Date'.
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.

#### Code Sample

attached above

#### Version of Realm and tooling
Realm version(s): 4.0.0 rc

Realm sync feature enabled:no

Android Studio version: 3 beta 7

Which Android version and device: ?

**Comment by cmelchior** [comment]
Can you post your `Comment` class?

**Comment by Zhuinden** [comment]
Comment must be either

``` java
@RealmClass
public class Comment implements RealmModel {
```

or

``` java
public class Comment extends RealmObject {
```

**Comment by michaelspeed** [comment]
`open class Comment : RealmObject(){
    @PrimaryKey var Id : String? = null
    var commentText : String? = null
    var commentType : String? = null
    var comment1: RealmList<Comment>? = RealmList()
    var comment2: Comment? = null
    var createdAt: Date? = null
    var file: File? = null
    var post: Post? = null
    var user: User? = null
    var reactions : RealmList<User>? = RealmList()
}`

**Comment by Zhuinden** [comment]
Is your plugin order like so:

``` groovy
apply plugin: 'com.android.application'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-kapt'
apply plugin: 'realm-android'
```

?
