### ISSUE TITLE
JAVA Documentation "logical operators" subsection of "Queries" has a sample with method that doesn't exist

### ISSUE THREAD

**Issue by soutoss** [realm/realm-java#5394]
#### Goal

> Correction on Realm JAVA documentation 3.7.2 

#### Expected Results

> With this particular query, though, it’s easier to use in:

```java
RealmResult<User> r = realm.where(User.class)
                           .not()
                           .in("name", new String[]{"Peter", "Jo"})
                           findAll();


```

#### Actual Results

>  With this particular query, though, it’s easier to use in:

```java
RealmResult<User> r = realm.where(User.class)
                           .not()
                           .in("name", new String[]{"Peter", "Jo"})
                           finalAll();


```

**finalAll() doesn't exist.**

#### Steps & Code to Reproduce

>  open https://realm.io/docs/java/latest/#filtering
   Look for Logical operators and see the mistake at "in clause sample".

#### Version of Realm and tooling
Realm version(s): 3.7.2 (JAVA DOCUMENTATION)

**Comment by Zhuinden** [comment]
Huh, just above https://realm.io/docs/java/latest/#sorting it really does say `finalAll()`.

**Comment by nhachicha** [comment]
Hi, thanks for the report. it's obviously a typo 👍

**Comment by cmelchior** [comment]
Fixed

**Comment by soutoss** [comment]
@cmelchior , @nhachicha . I found another error at the same place. At the same line, "RealmResult" type doesn't exist. I didn't see that before, sorry.

**Comment by nhachicha** [comment]
@soutoss please do, although I think I've fixed all the `RealmResult` ... 
is it on https://realm.io/docs/java/latest/ ? have you refreshed your cache?

**Comment by Zhuinden** [comment]
@nhachicha 
Negate conditions with not. You can use the not operator with beginGroup/endGroup to negate sub-conditions only. If you wanted to all find users who are not named “Peter” or “Jo,” the query could be:
Copy to clipboardRealmResult<User> r = realm.where(User.class)
                           .not()
                           .beginGroup()
                                .equalTo("name", "Peter")
                                .or()
                                .contains("name", "Jo")
                            .endGroup()
                            .findAll();
