### ISSUE TITLE
Android: Only local Realm. Need any permissions?

### ISSUE THREAD

**Issue by lmdic** [realm/realm-java#5399]
Android. I want to use Realm only for local storage (no sync).
Is I need to do local admin (with read/write rights)? Or by default I has all permissions for local Realm?

**Comment by cmelchior** [comment]
Local Realms do not have the concept of Permissions, so any restrictions would be imposed by the filesystem, e.g. if the file is read-only. So yes, the default behaviour is that you have all permissions.
