### ISSUE TITLE
频繁调用异步执行数据库更新操作数据库文件过大

### ISSUE THREAD

**Issue by liuguangsen** [realm/realm-java#5400]
#### Goal

> What do you want to achieve?

#### Expected Results

> ?

#### Actual Results

>  E.g. full stack trace with exception

#### Steps & Code to Reproduce

> Describe your current debugging efforts.

#### Code Sample

```java

> Your code here. Bigger samples should ideally be as separate Android Studio project, 
> in gists/repositories or privately at help@realm.io)

```

#### Version of Realm and tooling
Realm version(s): ?

Realm sync feature enabled: yes/no

Android Studio version: ?

Which Android version and device: ?

**Comment by Zhuinden** [comment]
You should use `try(Realm realm = Realm.getDefaultInstance())` to ensure that your local Realm instances are closed.

If you have `Realm.getLocalInstanceCount(Realm.getDefaultConfiguration()) >= 1` even when the thread has ended its execution on a background scheduler like `AsyncTask`, then this can cause problems!

**Comment by liuguangsen** [comment]
thank you, i will try it
