### ISSUE TITLE
Realm docs could recommend the 512-bit key to be generated separately as 256-256 then concatenated

### ISSUE THREAD

**Issue by Zhuinden** [realm/realm-java#5401]
I'm attending a seminar kind of thing (Devfest Budapest) and it was a recommendation that the key should be generated separately (256 and 256) then concatenated.

I will update this post later with slides and stuff.

**Comment by Zhuinden** [comment]
Docs for the talk https://speakerdeck.com/baloghtamas/secure-android-applications

**Comment by cbush** [comment]
We are revamping the Realm docs. We're not ignoring this issue -- we've read through every one of them, and we'll be sure to address this as part of our updates. We're closing the GitHub issues and creating new JIRA tickets to track the work at a high level.
