### ISSUE TITLE
Unable to add RealmList<RealmString> while doing RealmMigration

### ISSUE THREAD

**Issue by girdharpatel** [realm/realm-java#5402]
#### Goal

> We have added RealmList<RealmString> in one of our Realm class and now want to specify the same during RealmMigration.  We have a method named addRealmListField(String fieldName, RealmObjectSchema objectSchema) in RealmObjectSchema. We are unable to understand what should be passed as 2nd argument in this method for RealmList<RealmString>.

#### Expected Results

Should be able to add RealmList<RealmString> in RealmMigration

#### Actual Results

Unable to specify RealmList<RealmString> in RealmMigration

#### Version of Realm and tooling
Realm version(s): 3.0.0

Realm sync feature enabled: no

Android Studio version: 2.3.3

Which Android version and device: Redmi Note 4

public class RealmString extends RealmObject {
    private String string;

    public String getString() {
        return string;
    }

    public void setString(String string) {
        this.string = string;
    }
}

**Comment by Zhuinden** [comment]
You should specify the class you added the list in, whether RealmString was already part of the schema, and why not just switch to 4.0.0-RC1 and use `RealmList<String>` directly (having to use linked queries against the field is a reasonable answer)

**Comment by cmelchior** [comment]
```
schema.create("Foo")
  .addRealmListField("list", schema.get("RealmString"))
```

Should do it if you already have in your Schema, but yeah, consider if switching to 4.0.0-RC1 wouldn't be better.

**Comment by girdharpatel** [comment]
@cmelchior Thanks, it worked.

Also, we will try switching it to 4.0.0-RC1
