### ISSUE TITLE
Getting io.realm.exceptions.RealmMigrationNeededException randomly

### ISSUE THREAD

**Issue by rahulmenezes** [realm/realm-java#5409]
This crash happens randomly when getting Realm configuration and does not happen during the actual migration part.

#### Realm Configuration Code

```
private static int realmDBVersion = 10;
        if(mRealmConfiguration==null)
        {
                mRealmConfiguration = new RealmConfiguration.Builder()
                        .name(dbFileName + ".realm")
                        .encryptionKey(password)
                        .schemaVersion(realmDBVersion)
                        .migration(new MyRealmMigration())
                        .build();
        }
        return mRealmConfiguration;
```

#### MyRealmMigration code

```
RealmSchema schema = realm.getSchema();

   if(oldVersion ==9){
            schema.create("CodeTypeItemAuxiliary");

            RealmObjectSchema formMappingAreaSchema = schema.get("FormMappingArea");
            RealmObjectSchema codeTypeItem = schema.get("CodeTypeItem");
            RealmObjectSchema codeTypeItemAuxiliary = schema.get("CodeTypeItemAuxiliary");

            codeTypeItemAuxiliary
                    .addField("objectId",int.class, FieldAttribute.PRIMARY_KEY)
                    .addField("codeTypeItemId", String.class)
                    .addField("formFieldAttribute", String.class)
                    .addField("value", String.class);

            formMappingAreaSchema.addField("formFieldAttribute", String.class);
            codeTypeItem.addRealmListField("codeTypeItemAuxiliaryList",codeTypeItemAuxiliary);

            oldVersion++;
        }

```
#### Version of Realm and tooling
Realm version(s): 3.3.1

Realm sync feature enabled: no

Android Studio version: 2.3.3

Which Android version and device: Samsung S7

**Comment by Zhuinden** [comment]
You probably call `Realm.getDefaultInstance()` somewhere, without actually calling `Realm.setDefaultConfiguration()` first.

**Comment by rahulmenezes** [comment]
I double checked and my first Realm getInstance call is the code below

```
public static RealmController getInstance() {
        if (instance == null)
        {
            instance = new RealmController();
            try
            {
                Realm.setDefaultConfiguration(getDefaultConfiguration(
                        MyApp.getUser().getUserFolderName(),
                        Hex.decodeHex(MyApp.getUser().getRealmDbKey().toCharArray())));

                if (mRealm != null && !mRealm.isClosed())
                    mRealm.close();

                mRealm = Realm.getDefaultInstance();
            }
            catch (Exception e)
            {
                Common.makeLog(RealmController.getInstance().getClass(), e.getMessage(), Level.ERROR);
            }
        }
        return instance;
    }
```

The getDefualtConfiguration code is the one I posted in my first post.

**Comment by beeender** [comment]
can you please post the full backtrace here?

**Comment by rahulmenezes** [comment]
Ok, I have attached the text file of the crash stack trace.

[crashreport.txt](https://github.com/realm/realm-java/files/1379491/crashreport.txt)

**Comment by beeender** [comment]
@rahulmenezes 
can you please share a decoded stacktrace? With a obfuscated stack trace, it is quite difficult to find any clue.

**Comment by Zhuinden** [comment]
If you did all this config initialization in `Application.onCreate()` then this problem would not be possible.

**Comment by rahulmenezes** [comment]
Sorry for the delayed response, we are having issues with deobfuscating our New Relic crash reports. I have a ticket open with New Relic to get this resolved. In the meantime, I am attaching a partically deobfuscated crash report. Hopefully this helps a bit.
[crashreport (4).txt](https://github.com/realm/realm-java/files/1422441/crashreport.4.txt)

**Comment by beeender** [comment]
It is called from 
```
android.app.Activity.onDestroy()(Activity.java:1940)
android.support.v4.app.FragmentActivity.onDestroy()(FragmentActivity.java:386)
android.support.v7.app.AppCompatActivity.onDestroy()(AppCompatActivity.java:209)
com.scenedoc.SceneDoc.SignInActivity.onDestroy()(unknown:1399)
android.app.Activity.performDestroy()(Activity.java:7220)
```

which is strange since it feels like the Realm instance has not been created before this `Activity.onDestory()` called. Would you please check your code to see if this is possible and if the `RealmConfiguration` in the `Activity.onDestory()` has the migration configured?

**Comment by cmelchior** [comment]
Closing due to no response. @rahulmenezes feel free to reopen if you have new information.
