### ISSUE TITLE
Error:Could not find io.realm:realm-gradle-plugin:4.0.0.pre.rc1

### ISSUE THREAD

**Issue by jaisontj** [realm/realm-java#5410]
Issue Type: BUG
============

#### Goal
> Integrate the latest version of realm-java in an android app.

#### Expected Results
> Smooth integration using Gradle 

#### Actual Results
> Error:A problem occurred configuring root project 'BomPod'.
> Could not resolve all dependencies for configuration ':classpath'.
> Could not find io.realm:realm-gradle-plugin:4.0.0.pre.rc1.
Searched in the following locations: 
file:/Applications/Android Studio.app/Contents/gradle/m2repository/io/realm/realm-gradle-plugin/4.0.0.pre.rc1/realm-gradle-plugin-4.0.0.pre.rc1.pom
file:/Applications/Android Studio.app/Contents/gradle/m2repository/io/realm/realm-gradle-plugin/4.0.0.pre.rc1/realm-gradle-plugin-4.0.0.pre.rc1.jar
https://jcenter.bintray.com/io/realm/realm-gradle-plugin/4.0.0.pre.rc1/realm-gradle-plugin-4.0.0.pre.rc1.pom
https://jcenter.bintray.com/io/realm/realm-gradle-plugin/4.0.0.pre.rc1/realm-gradle-plugin-4.0.0.pre.rc1.jar
Required by:
    project :

#### Steps & Code to Reproduce
> Following instructions [here](https://realm.io/docs/java/latest/#installation) 

#### Code Sample

```java
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.3'
        classpath "io.realm:realm-gradle-plugin:4.0.0.pre.rc1"
    }
}

allprojects {
    repositories {
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```

``` java
apply plugin: 'com.android.application'
apply plugin: 'realm-android'

android {
    compileSdkVersion 26
    buildToolsVersion "26.0.0"
    defaultConfig {
        applicationId "com.jaison.bompod"
        minSdkVersion 21
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

realm {
    syncEnabled = true;
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    androidTestCompile('com.android.support.test.espresso:espresso-core:2.2.2', {
        exclude group: 'com.android.support', module: 'support-annotations'
    })
    compile 'com.android.support:appcompat-v7:26.+'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    testCompile 'junit:junit:4.12'
}
```

#### Version of Realm and tooling
Realm version(s): realm-gradle-plugin:4.0.0.pre.rc1

Realm sync feature enabled: yes

Android Studio version: 2.3.3

Which Android version and device: N/A

**Comment by beeender** [comment]
sorry, the version in the doc seems to be wrong.
try:
`io.realm:realm-gradle-plugin:4.0.0-RC1"

**Comment by jaisontj** [comment]
Thank you, do you want me to raise another issue asking for this fix in the docs ? Anywho, closing this issue.

**Comment by beeender** [comment]
uh, thanks! no need to raise another issue, we will fix it.
