### ISSUE TITLE
Realm migration between 3.5.0 and 3.7.2 crash

### ISSUE THREAD

**Issue by ppamorim** [realm/realm-java#5412]
Related to #5270

#### Expected Results

> No migration involved.

#### Actual Results

>  App is crashing during the Realm initialization, all Realm objects were forced to migrate, even if there is no changes on these objects.

#### Steps & Code to Reproduce

> Send privately to help@realm.io.

#### Version of Realm and tooling
Realm version(s): 3.7.2

Realm sync feature enabled: No

Android Studio version: 3.0 Beta 7

Which Android version and device: All

**Comment by Zhuinden** [comment]
Because of object store schema support, you should be getting messages on the exact changes that are expected to be done to the Realm schema as a result of the mismatch between the models and the schema.

**Comment by ppamorim** [comment]
@Zhuinden No migration involved. There are no changes on the models. All models are forced to migrate to... the same?

**Comment by Zhuinden** [comment]
.....wait, what?

Maybe there was a change in schema version?

**Comment by ppamorim** [comment]
@Zhuinden Nothing too, if you have access to help@realm.io you are able to understand what is happening. Some of these information are confidential.

**Comment by Zhuinden** [comment]
@ppamorim I don't, but the Realm people will handle it then 😄

**Comment by ppamorim** [comment]
Bump migration doesn't solve.

**Comment by beeender** [comment]
I got your project and I totally understand you pain for this.

It is actually a breaking change for you (kotlin users) which need to modify lots of code to update realm version.

That was introduced by this change https://github.com/realm/realm-java/blob/master/realm/realm-annotations-processor/src/main/java/io/realm/processor/ClassMetaData.java#L530

Let me try if there is a way to work around this. Maybe add some param in the gradle like:
```
realm {
  ignoreKotlinNullability = true;
}
```

**Comment by beeender** [comment]
```
realm {
  ignoreKotlinNullability = true;
}
```
is not easy. I didn't find a way to add one option to the annotation processor without overwriting the existing ones.

Also tried
```
kapt {
  arguments {
    arg("realm.ignoreKotlinNullability", true)
  }
}
```

But it seems kapt will overwrite the `@SupportedOptions` in `RealmProcessor` which makes realm cannot capture the option set there.
by printing the `ProcessingEnvironment.getOptions()` I only got:
```
: {kapt.kotlin.generated=/bigdick/home/cc/tmp/5412/t-pro-android/tpro-rules/build/generated/source/kaptKotlin/debug}
```

could it be a kapt bug?

**Comment by cmelchior** [comment]
@beeender Have you tried https://stackoverflow.com/questions/27607509/annotationprocessor-option-not-recorgnized-by-any-processor ?

**Comment by beeender** [comment]
Just tried. Didin't work :( 
Maybe i missed something?

f38595427e7629ef00feef12d64f68acaf306d88

in the testing project app's build.gradle:
```
kapt {
  arguments {
    arg("realm.ignoreKotlinNullability", true)
  }
}
```

**Comment by Zhuinden** [comment]
GreenRobot's EventBus figured it out somehow: http://greenrobot.org/eventbus/documentation/subscriber-index/#Using_kapt

I asked about it here https://github.com/greenrobot/EventBus/issues/452#issuecomment-317348765

**Comment by beeender** [comment]
Yeah, it works. I am stupid, adding things to a wrong sub-project's build.gradle.

**Comment by ppamorim** [comment]
@beeender Maybe using a default empty constructor for this? But it clashes with the primary key... :(

**Comment by beeender** [comment]
> Maybe using a default empty constructor for this? Realm could identify this class and use it as default value. But it clashes with the primary key... :(

I don't quite get it. is it a different problem?

**Comment by ppamorim** [comment]
@beeender No, just a idea.

**Comment by ppamorim** [comment]
@beeender I tried to set on the root `build.gradle` (or all `build.gradle` too):

    kapt {
      arguments {
        arg("realm.ignoreKotlinNullability", true)
      }
    }

And failed to recognize, any idea?

**Comment by beeender** [comment]
@ppamorim uh, sorry. this fix has not been released and it is not in the snapshot ... we have some issues with CI tests recently.

**Comment by Zhuinden** [comment]
I see 4.1.0 is out with this?

**Comment by beeender** [comment]
yes, `4.1.0` has been released just now and includes the fix!

**Comment by ppamorim** [comment]
@beeender 4.1.0 working like a charm.
