### ISSUE TITLE
@LinkingObjects get list without manual iterate by loop?

### ISSUE THREAD

**Issue by lmdic** [realm/realm-java#5421]
Example from your official documentation about **Inverse relationships** :  

https://realm.io/docs/java/latest/   

```
public class Person extends RealmObject {
  private String id;
  private String name;
  private RealmList<Dog> dogs;
}

public class Dog extends RealmObject {
  private String id;
  private String name;
  private String color;
  @LinkingObjects("dogs")
  private final RealmResults<Person> owners;
}


RealmResults<Dog> brownFluffies = realm.where(Dog.class).equalTo("color", "Brown").equalTo("name", "Fluffy").findAll();
for (Dog brownFluffy : brownFluffies) {
    RealmResults<Person> owners = brownFluffy.getOwners();
}
```

OK. It's work fine. 

But I need to get Person's name of all persons that has dog by brown color and name Fluffy.
 I wan't to do manualy iterate by loop. Is Realm can get this kind of list? 
As result I need list of persons's names.
`RealmResult<String> personNames`

**Comment by Zhuinden** [comment]
What exactly do you need specifically the *names* in a list for?

If in an adapter, then you could get `RealmResults<Person>` and just call the getter when you need to show the item?

**Comment by lmdic** [comment]
I need to get list names of persons. But I wan't do this by java via iterate loop. Because this list can contain many items (10000 persons). I want to write query for Realm that return 10000 list of only names of persons. Is it possible to do on Realm by ONE query?

**Comment by Zhuinden** [comment]
Well that's when you can open Realm on a background thread, iterate through the Person results, add the names into a `List` via the getter, and get the names back to the UI thread

**Comment by lmdic** [comment]
So I can't do only by one query to Realm the next:

**Get all persons's name that has brown dogs with name Fluffy**

?

P.S. I want avoid manual iterate of list.

**Comment by Zhuinden** [comment]
You can only get a list of proxy objects, where you can read their attributes via accessor methods.

**Comment by lmdic** [comment]
So I can't do some kind of JOIN query in Realm?

**Comment by Zhuinden** [comment]
Even in SQL this is called `projection` and Realm only provides the whole object as proxy

**Comment by cmelchior** [comment]
Note that Realm objects are all lazy-loaded, so the difference between `RealmResults<Person>` and `RealmResults<String>` would be very minimal, but if you _really_ need a list of strings then doing it manually is the only way for now.

Also, projections are not supported in Realm yet, but I did make a description of the concept in #5426 though.
