### ISSUE TITLE
Error in javadoc of findAllAsync(): "Finds all objects that fulfill the query conditions and sorted by specific field name"

### ISSUE THREAD

**Issue by octarino** [realm/realm-java#5422]
There isn't a fieldName parameter. Someone copypasted the description from findAllSorted which is below.

https://github.com/realm/realm-java/blob/d9e0ae4ac083286c5440cc4bdb0f18d9c70fdb45/realm/realm-library/src/main/java/io/realm/RealmQuery.java#L1805-L1812

I checked and it isn't fixed in 4.0

https://github.com/realm/realm-java/blob/master-4.0/realm/realm-library/src/main/java/io/realm/RealmQuery.java#L1805

**Comment by cmelchior** [comment]
Hey @octarino Thank you. It should be fixed in #5427
