### ISSUE TITLE
Ability to query based on relation of multiple fields in the same table

### ISSUE THREAD

**Issue by Zhuinden** [realm/realm-java#5424]
#### Goal

> What do you want to achieve?

Return a `RealmResults` where `obj.a < obj.b` is true.

#### Expected Results

This should be possible.

#### Actual Results

It is not possible, and I haven't found an issue that shows queries like this as an enhancement.

#### Steps & Code to Reproduce

https://stackoverflow.com/q/46747637/2413303

#### Version of Realm and tooling
Realm version(s): 4.0.0-RC1

Realm sync feature enabled: no

Android Studio version: 3.0.0-beta7

Which Android version and device: API 26, Nexus 5X

**Comment by kspangsege** [comment]
This is a limitation in our cross-platform query parser. The underlying querying subsystem can handle such queries. That parser will be built out at some point.

Note: In Cocoa/Swift, we use the native `NSPredicate` parser, which means that such queries are already supported there. Unfortunately, this is so far only the case there.

I don't know when a build-out of the cross platform parser is planned, but maybe somebody else can fill in?

**Comment by cmelchior** [comment]
This is already being tracked here: https://github.com/realm/realm-java/issues/1615, so closing as a duplicate. But it would be nice if you could weigh on on that issue @Zhuinden, at least just so we know if the API proposed there would solve your need?

**Comment by kspangsege** [comment]
Oh, I had forgotten that queries are not specified in text form when working through the Java binding. Sorry for the confusing answer.

**Comment by Zhuinden** [comment]
@cmelchior eh, I opened it for the SO question because I didn't know it's called `multi-field comparisons`. Nothing too specific from my part.

@kspangsege one day, maybe Realm raw queries will also be supported :smile:

**Comment by kspangsege** [comment]
@Zhuinden Yeah, my feeling is that it eventually should be.
