### ISSUE TITLE
Realm.getInstanceAsync callbacks does not get called, when new user created on realm-server

### ISSUE THREAD

**Issue by lonelyfugitive** [realm/realm-java#5428]
#### Goal

> create new synced user on realm-server and receive callback

#### Expected Results

> Either of onSuccess() or onError() methods must be called after first sync.

#### Actual Results

>  Neither of onSuccess() or onError() methods does not get called after first sync.
Overrided onSuccess() does get called only after same actions, but with synced user present on realm-server (on second app launch).

#### Steps & Code to Reproduce

> 1. Remove synced user from realm-server (if has one);
2. Trying to sync same user again from device with Realm.getInstanceAsync(syncConfiguration, new Realm.Callback() {});

#### Code Sample

```java

> final SyncConfiguration syncConfiguration = new SyncConfiguration.Builder(user, DBHelper.getServerURL()).disableSSLVerification().waitForInitialRemoteData().build();
        Realm.getInstanceAsync(syncConfiguration, new Realm.Callback() {

            @Override
            public void onError(@NonNull Throwable exception) {
                super.onError(exception);
                onFinished(exception.getMessage());
            }

            @Override
            public void onSuccess(@NonNull Realm realm) {
                Realm localRealm = Realm.getDefaultInstance();
                realm.beginTransaction();
                realm.copyToRealmOrUpdate(localRealm.where(ModelFolder.class).findAll());
                realm.copyToRealmOrUpdate(localRealm.where(ModelTrack.class).findAll());
                realm.copyToRealmOrUpdate(localRealm.where(ModelBookmark.class).findAll());
                realm.commitTransaction();
                realm.close();
                localRealm.close();
                AppSettings.setSyncMode(syncMode);
                DBHelper.updateDefaultConfiguration(syncConfiguration);
                onFinished(null);
            }
        });

```

#### Version of Realm and tooling
Realm version(s): io.realm:realm-gradle-plugin:4.0.0-RC1
realm-server:2.0.0-RC2

Realm sync feature enabled: yes

Android Studio version: 2.3.3

Which Android version and device: Api 15+

**Comment by lonelyfugitive** [comment]
I found that waitForInitialRemoteData() method makes callbacks unused if realm-server doesn't contain current user. Without that - everything works as intended. 
`final SyncConfiguration syncConfiguration = new SyncConfiguration.Builder(user, DBHelper.getServerURL()).build();`

**Comment by cmelchior** [comment]
Have you tried configuring an `ErrorHandler` on the `SyncConfiguration`? It does sound like a bug that the `onError` callback isn't triggered in any case though.

**Comment by beeender** [comment]
just tried, it seems work fine with ROS 2.0.0-rc11

@lonelyfugitive would you please update your realm-object-server from 2.0.0-rc2 to 2.0.0-rc11?

**Comment by molind** [comment]
@beeender is there any way to launch it inside container?

It asks to agree terms. Without any way to agree from command line.

**Comment by cmelchior** [comment]
Either set the environment variable JENKINS=1 or create an empty `realm-object-server-agreement.json` file from where you start ROS.

This is really something we need to document.

**Comment by molind** [comment]
@cmelchior Thanks! :)

**Comment by molind** [comment]
Ok. It started. But where is data located now? And where is new config? :) A whole bunch of questions without documentation.

**Comment by cmelchior** [comment]
Sorry about that. Documentation will go online in the next 24 hours.

**Comment by beeender** [comment]
@molind doc updated here https://realm.io/docs/realm-object-server/latest/#cli

**Comment by beeender** [comment]
@molind Please let us know if it still doesn't work the latest ROS.

I am closing this issue for now. Feel free to reopen it.
