### ISSUE TITLE
[Docs] Realm Browser section out of date

### ISSUE THREAD

**Issue by Zhuinden** [realm/realm-java#5435]
> The browser is macOS-only. ***While we’re working on a web-based Realm Browser***, right now you can use the Stetho-Realm plugin for Stetho, an Android debug bridge for the Chrome browser created by Facebook.

The announcement today says that Realm Studio is out and available, see https://blog.realm.io/realm-platform-reaches-v2-0/

**Comment by mgohin** [comment]
YESSS !!! Finally !!!!!!
