### ISSUE TITLE
LIMIT

### ISSUE THREAD

**Issue by gjcameron** [realm/realm-java#544]
It would be very useful to be able to specify the maximum number of objects to return in a query, similar to LIMIT in SQL. Otherwise the RealmResults list must be manually trimmed with subList.

**Comment by haskellcamargo** [comment]
+1. Althought the results are lazily loaded, `subList` is unsafe (`IllegalArgumentException`, `ArrayOutOfBoundsException`) and specifying a value out of range will give a runtime error. This is particularly problematic when you deal with pagination, for example, If I want to take the values in a range of `100` starting by page `1`:

```java
List<Equipment> filtered;
try {
  filtered = results.subList((page - 1) * 100, page * 100);
 } catch (IndexOutOfBoundsException lastPage) {
  try {
    filtered = results.subList((page - 1) * 100, results.size());
  } catch (IllegalArgumentException noMoreData) {
    filtered = new ArrayList<>();
  }
}
```

**Comment by Saketme** [comment]
@haskellcamargo Isn't it the dev's job to check the size before calling subList? I maintain a utility method `subListSafely` which does exactly this. This isn't the job of Realm IMO. :)

**Comment by haskellcamargo** [comment]
Not exactly in this case. In case of `LIMIT` or `TOP`, we would **securely** have the values (also if we provided `TOP 100` when we have only `50` items, and we lose the query abstraction that is provided by Realm. It is made to leave the boilerplate away. We lose an utility that is safely implemented by the relational databases and that is quite common. We mix the index check logic with the query logic (ah, and don't forget we have no extension methods in Java, like C#, to abstract it in a respectable way by extending `RealmResult`). I really believe that, as I said, although it is lazy, it would be useful to have a built-in feature for that and to keep the things clear. Abstraction and expressiveness are the way.

**Comment by cmelchior** [comment]
You would also have safety using `Math.min/max`:
```
int size = results.size();
results.subList(Math.max((page - 1) * 100, 0) , Math.min(page * 100, size));
```

That said we are not against adding some kind of LIMIT functionality as it can also have a positive impact on performance alongside the other benefits you mentioned. It does not have a high priority however, so I cannot give you any timeline for when we can add it.

**Comment by AlokBansal8** [comment]
:+1:

**Comment by bleppard** [comment]
:+1:

**Comment by mmublackpirate** [comment]
:+1:

**Comment by olidroide** [comment]
:+1:

**Comment by xiaolongyuan** [comment]
+1

**Comment by davroux** [comment]
👍

**Comment by frogggias** [comment]
👍

**Comment by carloseduardosx** [comment]
👍

**Comment by Zhuinden** [comment]
@carloseduardosx I don't understand why you guys want a LIMIT.

All you need to do is SORT your RealmResults, and then do not index above your arbitrary threshold.

For example, in a Results that "contains" 225 elements, to obtain the second page (1 -> 2) of 50, all you need to do is index like this

    // pageNum is 2
    int min = (pageNum-1)*50;   //50
    int max = pageNum*50;   //100, not inclusive
    int size = realmResults.size(); // 225

    // pageNum is 5
    int min = (pageNum-1)*50;   //200
    int max = pageNum*50;   //250, not inclusive
    int size = realmResults.size(); // 225

Adapter:

    public int getItemCount() {
        // assume pageNum = 5
        int min = (pageNum-1)*50;   //200
        int max = pageNum*50;   //250, not inclusive
        int size = realmResults.size(); // 225
        int elementCount = Math.min(max-min, size-min);
        return elementCount < 0 ? 0 : elementCount;
    }

Then index

    public void onBindViewHolder(RecyclerView.Holder holder, int position) {
         Element element = getItem(pageCount * 50 + position);
    }

I did not test this but conceptually this is equivalent to a "LIMIT" as a query in terms of functionality in your application.

There is no point to limiting a Results. Just paginate your elements.

**Comment by Zhuinden** [comment]
Although I guess I can see a `.skip(20).take(50)` instead of `limit()`.

**Comment by ahmadalibaloch** [comment]
@Zhuinden And we don't understand why you guys dont implement the `Limit` query method to satisfy hundred people ;-). I need to use RealmResults for RecycleView (autoupdating) and need to limit results in a products suggestion page. I have spent 30 minutes exploring best way and then implementing custom way. its a basic feature in Library lie Realm.

**Comment by Zhuinden** [comment]
@ahmadalibaloch hey, I'm just a community member, not an official realm person :tongue:

But to paginate the results, you just have to limit your index to show from the lowest and highest bound of your index, and show item size of  the minimum of 30 or the remaining element count

**Comment by beeender** [comment]
Another use case is to delete first n objects from a query results.
See http://stackoverflow.com/questions/41327579/how-to-delete-first-n-rows-in-realm

**Comment by cmelchior** [comment]
Core issue tracking this: https://github.com/realm/realm-core/issues/1239

**Comment by dtmandroid** [comment]
I have a Record Table. I want to display 5 records every time, user clicks on Next button until last record of Table. Please help me..  Thank you for your time...

**Comment by beeender** [comment]
@dtmandroid it is actually very simple, you could do something in your adapter:
```java
public class MyAdapter {
private int baseIndex;

public void selectPage(int page) {
    baseIndex = 5 * page;
}

@Override
public void getIndex(int pos) {
    return adapterData.get(baseIndex + pos);
}

@Override
public void getCount() {
    return adapterData.size() - 5 > 0 ? 5 : adapterData.size() - baseIndex;
}

}
```

The above just shows the basic idea how to achieve you use case, I am sure you need to write more code to make a full implementation.

**Comment by dtmandroid** [comment]
Thank for the answer. I could get first 5 records but crashes when get next 5 records. So will you please explain where to write selectPage() and getIndex()  method and use of it.. Thank You,

**Comment by Zhuinden** [comment]
@dtmandroid you can also try this approach http://stackoverflow.com/a/38873498/2413303

**Comment by null-dev** [comment]
Please please please implement this. Calling `size` on `RealmResults` with > 20000 items can take 5+ seconds to complete. Lazy loading doesn't help so much when I don't know what is available to load!

**Comment by babedev** [comment]
I also have problem with `count()` or `size. I have data over than 300K row it took about 3 seconds to finished counting.

Here is my code

```kotlin
realm.where(SomeClass::class.java)
  .findAll()
  .asFlowable()
  .map { it.count() }
```

I use `findAll()` with `Flowable` because I want to observe event on this table.

**Comment by Zhuinden** [comment]
You might want to try `realm.where<SomeClass>().findAllAsync().asFlowable().filter { it.isLoaded() }`
