### ISSUE TITLE
Querying List of Primitive Type (INTEGER_LIST)

### ISSUE THREAD

**Issue by vivekkiran** [realm/realm-java#5444]
How do i query list of primitive types which contains a particular value in realm 4.0.
blogPosts = (int) mRealm.where(BlogPost.class).equalTo("categories", categoryId).count();

For a sample json response make a call to GET:  https://hariome.com/wp-json/wp/v2/posts in postman. (This is a response from wordpress rest api)

I need to be able to query for count/occurrences of a particular category id for a list of objects in a json array.

Previously I have used GsonType Adapter to modify response and then used this query which used to work perfectly fine, this is before realm 4.0, I am now upgrading to realm 4.0 to use list of primitive types natively.
Previously: blogPosts = (int) mRealm.where(BlogPost.class).equalTo("categories.val", categoryId).count();

Now: blogPosts = (int) mRealm.where(BlogPost.class).equalTo("categories", categoryId).count();

Error:

 java.lang.IllegalArgumentException: Invalid query: field 'categories' in class 'BlogPost' is of invalid type 'INTEGER_LIST'.

Since this feature is recently implemented, there is not much documentation or solutions for it available anywhere. Please help.

For Reference: https://github.com/realm/realm-java/issues/5361

**Comment by Zhuinden** [comment]
From https://github.com/realm/realm-java/blob/master/CHANGELOG.md#enhancements-1 :

> Enhancements

> RealmList can now contain String, byte[], Boolean, Long, Integer, Short, Byte, Double, Float and Date values. [**Queries**](https://github.com/realm/realm-java/issues/5361) and Importing primitive lists from JSON **are not supported yet.**
