### ISSUE TITLE
[Docs] Update Documentation On List of Primitives

### ISSUE THREAD

**Issue by vivekkiran** [realm/realm-java#5445]
https://realm.io/docs/java/latest/#other-libraries
After the other libraries section there is a section on Primitive lists which is outdated since there is support for list of primitives in Realm 4.0, Please remove it or update with with current known limitations with this approach, like lack of support for querying list of primitives etc.

<img width="913" alt="screen shot 2017-10-20 at 12 15 02 am" src="https://user-images.githubusercontent.com/5557539/31788307-fa5ba3c8-b52b-11e7-8eea-d7343f8879ea.png">

**Comment by Zhuinden** [comment]
Apparently GSON is kinda stupid and you have to use a TypeAdapter to make it read `RealmList<Primitive>` as well.

https://stackoverflow.com/questions/47045761/unable-to-create-converter-for-class-retrofit2-realm4-and-gson/47047030#47047030
