### ISSUE TITLE
Type 'T' of field is not supported

### ISSUE THREAD

**Issue by goddestroyer** [realm/realm-java#5448]
#### Problem

I want to pass different datatype object into ContentWrapperPO class so I have 'T' as my generic parameter as I know that Realm version 4.0.0 RealmList start support primitive type. But when I build project with gradle, error below show that type T is not support. Am I doing anything wrong?

Can any pro help me with this?

####  Error Code

>D:\Android\RealmTesting2\app\src\main\java\my\com\realmtesting2\ContentWrapperPO.java
>Error:(9, 8) error: Type 'T' of field 'content' is not supported
>Warning:Unclosed files for the types '[io.realm.ContentWrapperPORealmProxy]'; these types will not undergo annotation processing
>Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

#### Code Sample
This is ResourceBundlePO Class
```java

public class ResourceBundlePO<T> extends RealmList<ContentWrapperPO<T>> {

    public ResourceBundlePO() {
    }

    public ContentWrapperPO<T> getContentWrapperPO(String locale) {
        for (ContentWrapperPO<T> contentWrapper : this) {
            if (contentWrapper.getLanguageCode().equals(locale)){
                return contentWrapper;
            }
        }
        return null;
    }

    public T getContent() {
        ContentWrapperPO<T> selectedContentWrapper = getContentWrapperPO(Locale.getDefault().getLanguage());
        return selectedContentWrapper.getContent();
    }
}

```

This is ContentWrapperPO class
```java

public class ContentWrapperPO<T> extends RealmObject{

    //region Database column name
    // (If the class variable's name changed, REMEMBER to update it here as well)
    public static final String COLUMN_LANGUAGE_CODE = "languageCode";
    public static final String COLUMN_CONTENT = "content";
    //endregion

    private String languageCode;
    private T content;

    public ContentWrapperPO() {
    }

    public ContentWrapperPO(ContentWrapper<T> contentWrapper) {
        this.languageCode = contentWrapper.getLanguageCode();
        this.content = contentWrapper.getContent();
    }

    public ContentWrapperPO(String languageCode, T content) {
        this.languageCode = languageCode;
        this.content = content;
    }

    public String getLanguageCode() {
        return languageCode;
    }

    public T getContent() {
        return content;
    }
}

```

#### Version of Realm and tooling
Realm version(s): 4.0.0

Android Studio version: 2.3.3

**Comment by beeender** [comment]
Generic types for `RealmObject` is not supported right now.
Dup of https://github.com/realm/realm-java/issues/3605

**Comment by Zhuinden** [comment]
Realm has a schema, so it doesn't really support dynamic typing like that....

Possible workaround if there is no alternative would be to map object as JSON string, and also add `String type;` to know what type of object is stored.
