### ISSUE TITLE
When using Kotlin, the equalTo function gives a compiler error

### ISSUE THREAD

**Issue by jokigenki** [realm/realm-java#5450]
#### Goal

> What do you want to achieve?

Call equalTo

#### Expected Results

The method to not give a compiler error

#### Actual Results

>  E.g. full stack trace with exception

Error:(49, 69) Overload resolution ambiguity:
public open fun equalTo(p0: String!, @Nullable p1: Byte?): RealmQuery<MenuItem!>! defined in io.realm.RealmQuery
public open fun equalTo(p0: String!, @Nullable p1: Int?): RealmQuery<MenuItem!>! defined in io.realm.RealmQuery
public open fun equalTo(p0: String!, @Nullable p1: Long?): RealmQuery<MenuItem!>! defined in io.realm.RealmQuery
public open fun equalTo(p0: String!, @Nullable p1: Short?): RealmQuery<MenuItem!>! defined in io.realm.RealmQuery

#### Steps & Code to Reproduce

> Describe your current debugging efforts.

#### Code Sample

```java

realm.where(MenuItem::class.java).equalTo(RealmProp.level.value, 0)

//workaround (in Java class)

public RealmQuery<MenuItem> equalToLevel (RealmQuery<MenuItem> query, int value) {
        return query.equalTo(RealmProp.level.value, value);
    }
```

#### Version of Realm and tooling
Realm version(s): ?
4.0.0

Realm sync feature enabled: yes/no

Android Studio version: ?
3.0

Which Android version and device: ?

**Comment by cmelchior** [comment]
You can use `realm.where(MenuItem::class.java).equalTo(RealmProp.level.value, 0.toInt())`, although that generate a "redundant conversion" warning in IntelliJ. 

It looks like Kotlin might have changed semantics in later releases regarding this. Although I do wonder why we have 4 overloads of the same integer type.

**Comment by jokigenki** [comment]
Thanks, that's much cleaner than my workaround.

**Comment by cmelchior** [comment]
So after looking into this, the reason we have overloads is that these methods take the boxed variants (Byte/Short/Integer/Long) in order to support null values and it is not possible to automatically convert between e.g `Byte` and `Long`.

This looks like a bug in IntelliJs Kotlin support.

**Comment by jokigenki** [comment]
Thanks for looking into this. Thinking about it, the compiler should be
able to recognise the difference between the types, so I think that you're
right.

Owen
