### ISSUE TITLE
No generic type supplied for field when extends RealmList<any datatype>

### ISSUE THREAD

**Issue by goddestroyer** [realm/realm-java#5457]
#### Problem

> When I have my model extends RealmList<**any type**>, the error below will show
Is there any solution or any alternative way to do this?

#### Error

>  D:\Android\RealmTesting2\app\src\main\...\Model.java
Error:(26, 30) error: No generic type supplied for field
Error:Execution failed for task ':app:compileDebugJavaWithJavac'.
Compilation failed; see the compiler error output for details.

#### Steps & Code to Reproduce

> Having model A extends RealmList<**any datatype**>
and model B has model A as one of the variable

#### Code Sample 1
StringBundle Class 
```java

> public class StringBundle extends RealmList<String> {
    public StringBundle() {
    }
}

```

Model Class 
```java

public class Model extends RealmObject {
    private StringBundle test;
}

```

#### Code Sample 2
Content Class 
```java

> public class Content extends RealmObject {

    public String stringContent;
    public int intContent;
    public double doubleContent;

    public Content() {
    }
}

```

ContentBundle Class 
```java

public class ContentBundle extends RealmList<Content> {
    public ContentBundle() {
    }
}

```

Model2 Class 
```java

public class Model2 extends RealmObject {
    private ContentBundle contents;
}

```

#### Version of Realm and tooling
Realm version(s): 4.0.0

Android Studio version: 2.3.3

Which Android version: android version 4.2 and above

**Comment by cmelchior** [comment]
We don't support custom `ReamList` implementations, in your case you need to replace 

```
public class Model extends RealmObject {
    private StringBundle test;
}
```

with 

```
public class Model extends RealmObject {
    private RealmList<String> test;
}
```

The error message isn't particularly helpful in this regard though.

**Comment by Zhuinden** [comment]
Extending RealmList is possible only for the sake of mocking during tests, otherwise it would be final.
