### ISSUE TITLE
How get list of inner POJOs more simple?

### ISSUE THREAD

**Issue by lmdic** [realm/realm-java#5467]
Realm 4.1.

My POJOs:

```
public class Store extends RealmObject {
    @PrimaryKey
    private int id;
    private RealmList<Product> products = new RealmList<>();
}

public class Product extends RealmObject {
    @PrimaryKey
    private int id;
    private String name;
}
```

I want to get list of all products of all stores.

Here my code. 

```
public static List<Product> getProductsList() {
        Realm realm = Realm.getDefaultInstance();
        try {
            List<Product> allProductsList = new ArrayList<>();
            RealmResults<Store> realmResultsStores = realm.where(Store.class).findAll();
            for (Store store : realmResultsStores) {
                RealmList<Product> merachantProductsList = store.getProducts();
                allProductsList.addAll(realm.copyFromRealm(merachantProductsList));
            }
            return allProductsList;
        } finally {
            realm.close();
        }
}
```

It's work. Fine.
But I think it's to much code.
The question is: Is there an easier way to get list of all products of all stores?

**Comment by Zhuinden** [comment]
I recommend

    public static RealmResults<Product> getProductsList(Realm realm) {
        return realm.where(Product.class).findAll();
    }

**Comment by lmdic** [comment]
Yes , this exactly what I need:

```
    // Get all products of all stores
    public static List<Product> getProductsList() {
        Realm realm = Realm.getDefaultInstance();
        try {
            List<Product> productsList = new ArrayList<>();
            RealmResults<Product> realmResults = realm.where(Product.class).findAll();
            productsList.addAll(realm.copyFromRealm(realmResults));
            return productsList;
        } finally {
            realm.close();
        }
    }
```

**Comment by lmdic** [comment]
The one more questiion.
My fragments/activity show list of products. 
What is better:
 return to fragment the list as` List<Product>` or maybe is better `RealmList<Product>`?

Has any difference?

**Comment by Zhuinden** [comment]
`RealmList<>` only makes sense for building relations.

Theoretically you could be using `RealmRecyclerViewAdapter` with `RealmResults`, which would handle auto-updating RecyclerView in case of any writes that modify insert or delete item from RealmResults.

**Comment by lmdic** [comment]
Yes, in my fragment I use     

`private RealmResults<Product> productRealmResults;`

I use this to can add listener to Realm.

So I return to fragment exact `RealmResults<Product>`.

OK. Thanks
