### ISSUE TITLE
Joint query in Realm

### ISSUE THREAD

**Issue by zahid--ali** [realm/realm-java#5476]
I have two realm objects UserRealmModel and MessageRealmModel and following is the structure
```Java
public class UserRealmModel extends RealmObject {
    @PrimaryKey
    private int id;
    private String phone;
    private String name;
    private String image;
    private String status;
    private boolean is_active;
    private boolean is_reported;
    private boolean is_blocked;
    private Date created_at;
    private Date updated_at;
}

public class MessageRealmModel extends RealmObject {
@PrimaryKey
    private int id;
    private int conversation_id;
    private UserRealmModel sender;
    @Index
    private int message_type;
    private String message;
    @Index
    private String status;
    private String media_url;
    private String media_mime_type;
    private boolean is_starred;
    private double media_size;
    private String media_name;
    private double latitude;
    private double longitude;
    private String received_timestamp;
    @Index
    private Date created_at;
    private Date deleted_at;
}
```

I would like to retrieve the last message created for each distinct user sorted by date.(Like Whatsapp) last message on top of the list for each user in the inbox.
How can I do it? In SQL I am fetching it by 
SELECT m.id, MAX(m.created_at), m.conversation_id, m.sender_id, m.message, u.name FROM messages m LEFT JOIN user u ON u.id = m.sender_id GROUP BY sender_id ORDER BY m.created_at DESC

**Comment by Zhuinden** [comment]
This is possible since Realm 4.0.0+


First  

public class UserRealmModel extends RealmObject {
... 
    @LinkingObjects("sender")
    private final RealmResults<MessageRealmModel> sentMessages;
```

Then 

``` java
realm.where(MessageRealmModel.class)
      .findAllSorted("received_date", Sort.DESCENDING)
      .where()
      .distinct("sender.id");
```

I don't remember if `distinct` works across links. I think it should.

**Comment by zahid--ali** [comment]
@Zhuinden I tried this and across links are supported in the Realm 4.0.0+ but the application crashes.

**Comment by Zhuinden** [comment]
> but the application crashes.

Stack trace

**Comment by zahid--ali** [comment]
@Zhuinden it says "Field name 'sender.id' does not exist"

**Comment by Zhuinden** [comment]
Aw that is a shame, apparently distinct is [not supported across links](https://github.com/realm/realm-java/issues/1906).

So you have two options:

1.) denormalize the schema and include `sender_id` in the `MessageRealmModel` next to the actual link

``` java
public class MessageRealmModel extends RealmObject {
@PrimaryKey
    private int id;
    private int conversation_id;
    private UserRealmModel sender;
    @Index
    private int sender_id;

    public void setSender(UserRealmModel sender) {
        this.sender = sender;
        if(sender != null) {
              this.sender_id = sender.getId();
        }
    }
```

Then you can do

``` java
realm.where(MessageRealmModel.class)
      .findAllSorted("received_date", Sort.DESCENDING)
      .where()
      .distinct("sender_id");
```

2.) rewrite the query like this

``` java
public class UserRealmModel extends RealmObject {
    @PrimaryKey
    private int id;
    private String phone;
    private String name;
    private String image;
    private String status;
    private boolean is_active;
    private boolean is_reported;
    private boolean is_blocked;
    private Date created_at;
    private Date updated_at;

    @LinkingObjects("sender")
    private final RealmResults<UserRealmModel> sentMessages = null;
}
```

and

``` java
RealmResults<UserRealmModel> users = realm.where(UserRealmModel.class)
      .findAllSorted("sentMessages.received_date", Sort.DESCENDING)
      .where()
      .distinct("id");

public void onBindViewHolder(ViewHolder holder, int position) {
    UserRealmModel user = getData().getPosition();
    MessageRealmModel latestMessage = user.getSentMessages().where().findAllSorted("received_timestamp", Sort.DESCENDING).first(null);
    if(latestMessage != null) { 
        ...
    }
}
```

I prefer the first, it is less tricky.

**Comment by zahid--ali** [comment]
BTW why I tried the first one before, but I was confirming that am I following the standard way or not. Thank you @Zhuinden 
Why does it take longer than SQLite? is the sorting algorithm of Realm is poor or SQLite is faster in term of joint queries?

**Comment by Zhuinden** [comment]
You can try adding `@Index` on `received_date` and see if that improves performance.

**Comment by beeender** [comment]
> Why does it take longer than SQLite? is the sorting algorithm of Realm is poor or SQLite is faster in term of joint queries?

which specific sorting is slow? this one `.findAllSorted("received_date", Sort.DESCENDING)`?

**Comment by zahid--ali** [comment]
@beeender this is the query I am using
`realm.where(MessageRealmModel.class).findAllSorted(MessageRealmModel.CREATED_AT, Sort.DESCENDING).where().distinct(MessageRealmModel.SENDER);`

**Comment by beeender** [comment]
@zahid--ali I think add `@Index` on the `MessageRealmModel.create_at` and `MessageRealmModel.sender` will improve the query speed significantly.

**Comment by zahid--ali** [comment]
@beeender I did but still the performance is poor, beside that I compared the contains query of Realm and Like query of SQLite, Realm runtime performance was poorer than SQLite.

**Comment by beeender** [comment]
@zahid--ali is it possible to share your benchmark project (realm vs sqlite) with us? to help@realm.io if you want to share it privately.

**Comment by zahid--ali** [comment]
@beeender It's my research project I am comparing Realm with SQLite, benchmarking both databases. How can I share the repo with you?

**Comment by beeender** [comment]
you can zip the repo and send it to help@realm.io if you want to share it privately.
Or you can share it on github or any other repo hosting services/ online disks we can get if you don't mind to share it publicly.

**Comment by beeender** [comment]
hi, we haven't got your project so far. So i am going to close this issue now. Thanks for your feedback!
