### ISSUE TITLE
Replace exist field from json that not content this field?

### ISSUE THREAD

**Issue by lmdic** [realm/realm-java#5483]
POJO:

```
public class Offer extends RealmObject {
    @PrimaryKey
    private int id;
    private String name;
    private boolean downloaded;
}
```

I update field "**download**" by **true** like this (click special button in my app):

```
public static void update(final int offerId, final boolean downloaded) {
        Realm realm = Realm.getDefaultInstance();
        try {
            realm.executeTransaction(new Realm.Transaction() {
                @Override
                public void execute(Realm realm) {
                    Offer offer = realm.where(Offer.class).equalTo(Offer.ID, offerId).findFirst();
                    offer.setDownloaded(downloaded);
                }
            });
        } finally {
            realm.close();
        }
    }

```

OK. It's work. Now field  **download = true**.
And I need this field not change any more!

But then incoming json like this (in this json no field "download")

```
[
  {
    "id": 1,
    "name": "my name"
  },
  {
    "id": 2,
    "name": "my name2"
  }
  ]
```

I update Offer like this :

    public static void updateOffers(final List<Offer> offersList) {
        Realm realm = Realm.getDefaultInstance();
        try {
            realm.executeTransaction(new Realm.Transaction() {
                @Override
                public void execute(Realm realm) {
                    RealmList<Offer> offersRealmList = new RealmList<>();
                    offersRealmList.addAll(offersList);
                    realm.copyToRealmOrUpdate(offersRealmList);
                }
            });
        } finally {
            realm.close();
        }
    }

And after this update all fields "**download**" again = **FALSE**!!!

Questions:
1.This is a normal of Realm to replace exist field? (In json no this field)
2.How avoid to replace filed "**download**"?

**Comment by Zhuinden** [comment]
The default value of this field is `false`, so you parse it as `false`.

Realm then takes your objects, and updates the ones in the Realm by primary key (because you used `copyToRealmOrUpdate()`). So the `download` field will be false.

This is expected behavior. If you

**Comment by lmdic** [comment]
If change field **download** to object **Boolean**. Default value is null. Maybe then Realm ignore this feald?

**Comment by Zhuinden** [comment]
There is no reason why it should ignore it. :|

**Comment by Zhuinden** [comment]
You could for example save the object, then set the `downloaded` flag back to `true` manually, for objects that already had `true`.

**Comment by Zhuinden** [comment]
``` java
public static void updateOffers(final List<Offer> offersList) {
    Realm realm = Realm.getDefaultInstance();
    try {
        realm.executeTransaction(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {
                SparseBooleanArray downloaded = new SparseBooleanArray();
                for(Offer offer : offersList) {
                     Offer realmOffer = realm.where(Offer.class).equalTo("id", offer.getId()).findFirst();
                     if(realmOffer != null) {
                         downloaded.put(realmOffer.getId(), realmOffer.isDownloaded());
                     }
                }
                realm.insertOrUpdate(offersRealmList);
                for(Offer offer : offersList) {
                     Offer realmOffer = realm.where(Offer.class).equalTo("id", offer.getId()).findFirst();
                     if(realmOffer != null) {
                         realmOffer.setDownloaded(downloaded.get(realmOffer.getId(), false));
                     } 
                }
            }
        });
    } finally {
        realm.close();
    }
}
```

**Comment by lmdic** [comment]
Here my solution.
Note: When client click button(download) field `Offer.download = true `and never change!

So as result here my solution:

```
public class Store extends RealmObject {
    @PrimaryKey
    private int id;
    private String name;
    private RealmList<Offer> offers = new RealmList<>();
}


public class Offer extends RealmObject {
    @PrimaryKey
    private int id;
    private String name;
    private boolean downloaded;
}
```


Get all offers with **download = true**;

```
public static List<Offer> getoffersList(boolean downloaded) {
        Realm realm = Realm.getDefaultInstance();
        try {
            List<Offer> offersList = new ArrayList<>();
            RealmResults<Offer> realmResults = realm.where(Offer.class).equalTo(Offer.DOWNLOADED ,true).findAll();
            offersList.addAll(realm.copyFromRealm(realmResults));
            return offersList;
        } finally {
            realm.close();
        }
    }

```

And here result method that update list of stores.
`newStoresList `- create from incoming Json (without field "**download**")

Algorithm:
1. **offersDownloadTrueList** - Get all offers with **download = true**
2. Iterate list of stores and find offers that are on `offersDownloadTrueList`
3. Replace field **download** by value true (by default it's value is false)
4. update Realm with cnanged `newStoresList`

Here implementation:


```
 public static void updateStores(final List<Store> newStoresList) {
             Realm realm = Realm.getDefaultInstance();
        try {
            realm.executeTransaction(new Realm.Transaction() {
                @Override
                public void execute(Realm realm) {
                    List<Offer> offersDownloadTrueList = OfferService.getoffersList(true);
                    for (Store store : newStoresList) {
                        List<Offer> newOffersList = store.getOffers();
                        for (Offer newOffer : newOffersList) {
                            if (offersDownloadTrueList.contains(newOffer)) {
                                Debug.d(TAG, "execute: Found_offer_with field 'download' =  true,  offerId = " + newOffer.getId());
                                newOffer.setDownloaded(true);
                            }
                        }
                    }

                    RealmList<Store> storesRealmList = new RealmList<>();
                    storesRealmList.addAll(newStoresList);
                    realm.copyToRealmOrUpdate(storesRealmList);
                }
            });
        } finally {
            realm.close();
        }
}
```

And now in Realm offers that has field **download = true** not change.
OK. It's work. Fine.

The question is: Is this a best solution?

**Comment by beeender** [comment]
yes, that would be a fine solution for now.

We have an issue to track this #2288
