### ISSUE TITLE
Set/remove @Ignore programatically

### ISSUE THREAD

**Issue by lmdic** [realm/realm-java#5485]
Is it possible to set and remove annotation @ignore programmatically?

**Comment by Zhuinden** [comment]
`@Ignore` is used by Realm's annotation processor, so that wouldn't really help.

**Comment by ppamorim** [comment]
What about build settings, you can create a custom BuildConfig for this. But I don't recommend.

**Comment by Zhuinden** [comment]
Technically he wants something like https://github.com/realm/realm-java/issues/2288

**Comment by beeender** [comment]
dup to #2288
