### ISSUE TITLE
Error:Execution failed for task

### ISSUE THREAD

**Issue by Mahdihp** [realm/realm-java#5487]
':app:transformNativeLibsWithStripDebugSymbolForDebug'. > A problem occurred starting process 'command '/home/mahdi/sdk/ndk-bundle/toolchains/x86-4.9/prebuilt/windows-x86_64/bin/i686-linux-android-strip''
Screen shot error : 
':app:transformNativeLibsWithStripDebugSymbolForDebug'. > A problem occurred starting process 'command '/home/mahdi/sdk/ndk-bundle/toolchains/x86-4.9/prebuilt/windows-x86_64/bin/i686-linux-android-strip''
[Screen shot error](http://bayanbox.ir/view/6182967818727391985/Screenshot-from-2017-08-20-20-07-50.png)

**Comment by Zhuinden** [comment]
Gradle Console -> specific error?

**Comment by ppamorim** [comment]
Is this error related to `Realm`? Could you specify more? Could you try to delete all build folders and clean the project and also remove `Realm` of the project (if possible for testing) and see if it compiles.

**Comment by beeender** [comment]
@Mahdihp Are you building realm from source? Does your project have native code? Android gradle will try to strip native so files automatically (which is stupid) but it shouldn't happen if you are not having any native code.

**Comment by Mahdihp** [comment]
OS name : Linux Mint
When I use this library on Linux Mint
This error shows.
Maybe
  Not updating NDK !!

**Comment by beeender** [comment]
It feels some build configurations is not set rightly on you Linux mint since `/home/mahdi/sdk/ndk-bundle/toolchains/x86-4.9/prebuilt/windows-x86_64/bin/i686-linux-android-strip` actually points to a windows prebuilt NDK. Do you have ndk set in your `local.properties`? Try to remove it?

**Comment by Mahdihp** [comment]
fixed (;
I deleted the folder NDk.
/home/mahdi/sdk/ndk-bundle

**Comment by ifishing** [comment]
I fix by  copying the files from ndk 16 (https://dl.google.com/android/repository/android-ndk-r16b-darwin-x86_64.zip) to  local ndk directory .

**Comment by akilanarasu1994** [comment]
For macOS, following @Mahdihp's suggestion, do this in terminal:
 **rm -rf ~/Library/Android/sdk/ndk-bundle**

**Comment by josinaldobarbosa** [comment]
remove works but my folder has 2.4gb if I need it will it be downloaded again?

**Comment by smkhadishi** [comment]
I renamed folder NDk.
/home/mahdi/sdk/ndk-bundle

**Comment by kamleshhello** [comment]
@smkhadishi it worked for me ...thanks

**Comment by Arty1994** [comment]
http://q.gs/EilEI

**Comment by kumarkundan** [comment]
> For macOS, following @Mahdihp's suggestion, do this in terminal:
> **rm -rf ~/Library/Android/sdk/ndk-bundle**

worked for me
