### ISSUE TITLE
stack out of memory exception

### ISSUE THREAD

**Issue by LambdaV5** [realm/realm-java#5490]
when this version(4.1.0) works with fastjson,stack out of memory exception occurred
#### Goal

> What do you want to achieve?

#### Expected Results

> ?

#### Actual Results

>  E.g. full stack trace with exception

#### Steps & Code to Reproduce

> Describe your current debugging efforts.

#### Code Sample

```java

> Your code here. Bigger samples should ideally be as separate Android Studio project, 
> in gists/repositories or privately at help@realm.io)

```

#### Version of Realm and tooling
Realm version(s): ?4.1.0

Realm sync feature enabled: yes/no no

Android Studio version: ?3.0

Which Android version and device: ? 7.0

**Comment by beeender** [comment]
Stack trace please?

**Comment by LambdaV5** [comment]
sorry,it's StackOverflowError
[heap.zip](https://github.com/realm/realm-java/files/1429727/heap.zip)

**Comment by beeender** [comment]
@LambdaV5 
Sorry, Android Studio 3 remove the hprofviewer so I cannot open the file you shared.
A screenshot of the stack would be helpful.

My guess is you are committing transaction synchronically in the `onChange()` callback. The synchronized transaction will trigger the relevant listeners on the same thread synchronically  which may create a endless recursion on that thread. To fix that, you can use `executeTransactionAsync()` instead in the `onChange()` callback.

**Comment by LambdaV5** [comment]
you can just drag this file into studio,then you will see the content of it
as far as i'am considered ,it's the getRealm method which parameter is this makes the recursion

**Comment by beeender** [comment]
![image](https://user-images.githubusercontent.com/449296/32210616-9db02938-be49-11e7-805a-a13897bb17dc.png)

1. The heap usage of Realm seems to be fine to me? Isn't it a stack-over-flow error?
2. Do you have a backtrace of the exception when the `StackOverflowError` throws? Or if you can share the project with us which can reproduce the issue, it will also be helpful. You can send your project to help@realm.io if you want to share it privately. Otherwise you can put it anywhere we can get. And let us know how to reproduce it.

**Comment by beeender** [comment]
Is it the same issue with https://github.com/alibaba/fastjson/issues/1536 ?

**Comment by LambdaV5** [comment]
yes,it is

**Comment by beeender** [comment]
Aaccording to your comments in https://github.com/alibaba/fastjson/issues/1536 , if the issue is caused by the newly added getter `getRealm()`, then you probably should think about filter it out when calling `toJSONString()`.

I haven't used the `fastjson` before, with a quick look, this might be what you want https://github.com/alibaba/fastjson/wiki/%E4%BD%BF%E7%94%A8SimplePropertyPreFilter%E8%BF%87%E6%BB%A4%E5%B1%9E%E6%80%A7

**Comment by LambdaV5** [comment]
i will try it,thanks a lot!

**Comment by LambdaV5** [comment]
this works for me,thanks again

**Comment by TommyLemon** [comment]
@beeender @LambdaV5 
It's not enough to egnore serialize getRealm().
I've already tried to add an Annotation for this method:
```java
	@JSONField(serialize = false)
	@Override
	public Realm getRealm() {
		return super.getRealm();
	}
```
And another exception came:
```
 write javaBean error, class io.realm.com_test_bean_BeanRealmProxy, write javaBean error, class io.realm.com_test_bean_URLDtoRealmProxy, fieldName : 0, write javaBean error, class io.realm.Realm, fieldName : realm, write javaBean error, class io.realm.ImmutableRealmSchema, fieldName : schema, write javaBean error, class io.realm.ImmutableRealmObjectSchema, fieldName : 0
```
Here is the JavaBeans:
```java
public class URLDto extends RealmObject implements Serializable {
	private String url;

	public String getUrl() {
		return url;
	}
	public void setUrl(String url) {
		this.url = url;
	}
}
```
```java
public class Bean extends RealmObject implements Serializable {
	private static final long	serialVersionUID	= 1L;

	@JSONField(serialize = false)
	@Override
	public Realm getRealm() {
		return super.getRealm();
	}

	@PrimaryKey
	private Long id;
	private RealmList<URLDto> visitImgs;

	public Long getId() {
		return id;
	}
	public void setId(Long id) {
		this.id = id;
	}
	
	public RealmList<URLDto> getVisitImgs() {
		return visitImgs;
	}
	public void setVisitImgs(RealmList<URLDto> visitImgs) {
		this.visitImgs = visitImgs;
	}
}
```

**Comment by TommyLemon** [comment]
And by this way I solved the problem:
```java
	public static String toJSONString(final Object obj) {
		if (obj instanceof String) {
			return (String) obj;
		}
		try {
			PropertyFilter filter = new PropertyFilter() {
				@Override
				public boolean apply(Object object, String name, Object value) {
					if (object instanceof Realm
							|| object instanceof OsSharedRealm
							|| object instanceof RealmSchema
							|| object instanceof RealmMigration
							|| object instanceof RealmNotifier
							) {
						return false;
					}

					if (name.equalsIgnoreCase("loaded")
							|| name.equalsIgnoreCase("valid")
							|| name.equalsIgnoreCase("managed")
							){
						return false;
					}
					return true;
				}
			};

			return com.alibaba.fastjson.JSON.toJSONString(obj, filter);
		} catch (Exception e) {
			Log.e(TAG, "toJSONString  catch \n" + e.getMessage());
		}

		return null;
	}
```

I would like to add the codes above to my libraries:
[A JSON Transmission Protocol and an ORM Library for auto providing APIs and Documents.](https://github.com/TommyLemon/APIJSON)
[An MVP Android Framework for building UI fastly](https://github.com/TommyLemon/Android-ZBLibrary)

**Comment by Zhuinden** [comment]
If those fields are causing you problems, you could just use `@RealmClass public class x implements RealmModel`
