### ISSUE TITLE
Lifecycle of Realm instances

### ISSUE THREAD

**Issue by LPFinch** [realm/realm-java#5492]
Can anybody help with understanding?
If i have 2 activity, ActivityA and ActivityB, in both i need a realm.
ActivityA is info, ActivityB is settings. 
ActivityA and ActivityB example
```java
@Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        realm = Realm.getDefaultInstance();
    }

@Override
    protected void onDestroy() {
        super.onDestroy();
        realm.close();
    }
```
ActivityA -> ActivityB, in ActivityB i change and write some data by executeTransactionAsync with success callback
```java
realm.executeTransactionAsync(new Realm.Transaction() {
            @Override
            public void execute(Realm bgRealm) {
                //bla bla bla
            }
        }, new Realm.Transaction.OnSuccess() {
            @Override
            public void onSuccess() {
                // Transaction was a success.
            }
        }, new Realm.Transaction.OnError() {
            @Override
            public void onError(Throwable error) {
                // Transaction failed and was automatically canceled.
            }
        });
```
when i close ActivityB and return to ActivityA sometimes RealmChangeListeners doesn't work, ActivityA doesn't change anything, after close/open app ActivityA show changes.

do I need to close realm instance in ActivityB?
Thanks

**Comment by beeender** [comment]
Managing the Realm lifecycle in `onCreate`/`onDestory` is the suggested way. 

> when i close ActivityB and return to ActivityA sometimes RealmChangeListeners doesn't work, ActivityA doesn't change anything, after close/open app ActivityA show changes.

This might be caused by the object you added the listener on is GCed.
> Notifications will also stop if the object on which the listener is registered gets garbage collected, or if its Realm instance is closed. You should keep a strong reference of the object you’re listening to as long as you need the notifications.

https://realm.io/docs/java/latest/#notifications

**Comment by LPFinch** [comment]
It's magic, i press home button and after 1 sec open app again, i repeat this 3 times
after that realm is closed xD but onDestroy not called
that's for sure GC

**Comment by Zhuinden** [comment]
Please show the RealmResults that has outdated data and if you have  a RealmChangeListener added to it and the code where that happens

**Comment by LPFinch** [comment]
All works, it's my fault, please close
