### ISSUE TITLE
RealmRecyclerViewAdapter: Replace OrderedRealmCollection by java.util.List

### ISSUE THREAD

**Issue by lmdic** [realm/realm-java#5498]
I have fragment with RecyclerView.

I need the next:

1. When Realm was changed in fragment the RecyclerVeiw must autoupdate.
2. Data show in sorted order

Here my fragment:
```
public class MyFragment extends Fragment {
 private RealmRecyclerViewAdapter sortAdapter;
 private Realm realm;
 private RealmResults<?> realmResults;

 @Nullable
  @Override
public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        realm = Realm.getDefaultInstance();
        realmResults = realm.where(Offer.class).findAllSorted(sortByFieldName, Sort.DESCENDING);
        sortAdapter = new OfferSortAdapter(realmResults)
        sortRecyclerView.setAdapter(sortAdapter);
}

```

Here my adapter:

```
public class OfferSortAdapter extends RealmRecyclerViewAdapter<Offer, OfferSortAdapter.OfferViewHolder> {

public OfferSortAdapter(OrderedRealmCollection<Offer> data) {
        super(data, true);
        setHasStableIds(true);
}
```

And as result all work fine. When Realm change `MyFragment `is autoupdate. Nice!

As you can see in constructor `OfferSortAdapter `I use parameter `OrderedRealmCollection`.

Question:
Can I use `java.util.List `as parameter in `OfferSortAdapter`? Is it does not break anything?

Something like this:
myFragment:

```
public class MyFragment extends Fragment {
 private RealmRecyclerViewAdapter sortAdapter;
 private Realm realm;
private RealmList<Offer> offers = new RealmList<>();

 @Nullable
 @Override
public View onCreateView(LayoutInflater inflater, ViewGroup container, Bundle savedInstanceState) {
        realm = Realm.getDefaultInstance();
        realmList= MyService.getOffersAsRealmList(int id)
        sortAdapter = new OfferSortAdapter(realmList)
        sortRecyclerView.setAdapter(sortAdapter);
}

```

adapter: 

```
public OfferSortAdapter(java.util.List<Offer> data) {
        super((OrderedRealmCollection<Offer>) data, true);
        setHasStableIds(true);
}
```

I remind you that I need 2 things:
1.When Realm was changed in fragment the `RecyclerVeiw `must autoupdate.
2.Data show in sorted order

**Comment by Zhuinden** [comment]
> private RealmList<Offer> offers = new RealmList<>();

This will not work with RealmRecyclerViewAdapter because this is an unmanaged collection.

You should use RealmResults for this, unless the RealmList is obtained from a managed RealmObject.

**Comment by lmdic** [comment]
So I can obtain `RealmList `only from `RealmObject`. But `RealmObject `I can obtain if only create query to Realm?

**Comment by Zhuinden** [comment]
Yup

**Comment by cmelchior** [comment]
@lmdic The above seems to answer you question, so I'm closing this issue. Feel free to reopen if that is not the case
