### ISSUE TITLE
Setup inMemory Realm for Instrumented Tests

### ISSUE THREAD

**Issue by SarthakM9** [realm/realm-java#5503]
#### Goal

> Setup inMemory Realm while running Instrumented tests

#### Actual Results

>  Realm cannot be initialized from androidTest package

#### Steps & Code to Reproduce
```
@Before
fun setup() {
    Realm.init(MessengerApplication.context)
    val config = RealmConfiguration.Builder()
            .name("realm.test")
            .inMemory()
            .build()
    realm = Realm.getInstance(config)
}
```

> java.lang.NoSuchMethodError: No static method init(Landroid/content/Context;)V in class Lio/realm/Realm; or its super classes

**Strangely, the code works if I setup realm in my Application class and set the default config to inMemory.**

#### Version of Realm and tooling
Realm version(s): 4.1.1

Realm sync feature enabled: No

Android Studio version: 3.0

Which Android version and device: 7.0

**Comment by cmelchior** [comment]
It looks like your instrumentation tests are using an older version of Realm that didn't include the init method for some reason.

**Comment by SarthakM9** [comment]
@cmelchior Sorry, I didn't get you. How can my tests use older version of Realm, as I am using version 4.1.1.
Also I am specifying `Realm.init()` in the `@Before` already.

**Comment by cmelchior** [comment]
I don't know, maybe you are pulling in a specific version in your test dependencies that are older. `java.lang.NoSuchMethodError: No static method init(Landroid/content/Context;)V in class Lio/realm/Realm; or its super classes` Indicate that the `init` method isn't present which was the case in before Realm Java 2.0

**Comment by SarthakM9** [comment]
@cmelchior Yeah I understand that, it cannot find any methods at Runtime. But I have only mentioned realm plugin at one place. :(
Thanks for the help, will post the resolution if I find one! :)

**Comment by SarthakM9** [comment]
@cmelchior I think I found the problem!

```
debug {
    minifyEnabled true
    useProguard false 
    proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
}
````
as I was removing all unused methods in the debug build, `inMemory()` was not found when I mentioned in the androidTest package. Moreover, when I moved all the Realm initialization to androidTest, it could not find anything!
simply ignoring Realm classes in Proguard settings resolved the issue!

**Comment by cmelchior** [comment]
Interesting. Thanks for the info 👍
