### ISSUE TITLE
Sync not working 

### ISSUE THREAD

**Issue by RajeshDhalange** [realm/realm-java#5504]
#### Goal

> Sync Server data with app

#### Expected Results

> App changes should reflect on server

#### Actual Results

>  not connecting

#### Code Sample

          SyncCredentials myCredentials = SyncCredentials.usernamePassword("rajesh@gmail.com", "rajesh", false);
         SyncUser.loginAsync(myCredentials, BaseApplication.SERVER_URL, new 
         SyncUser.Callback<SyncUser>() {
            @Override
            public void onSuccess(SyncUser result) {
                Log.i(TAG, "onSuccess: " + result.getIdentity());
            }

            @Override
            public void onError(ObjectServerError error) {
                Log.e(TAG, "onError: ", error);
                Log.i(TAG, "onError: " + error.getErrorCode());
            }
        });
        
        SyncConfiguration config = new SyncConfiguration.Builder(SyncUser.currentUser(), BaseApplication.REALM_URL)
                .initialData(new Realm.Transaction() {
                    @Override
                    public void execute(@Nonnull Realm realm) {
                        realm.createObject(Subject.class, SyncUser.currentUser().getIdentity());
                    }
                })
                .build();
        
        Realm.getInstance(config);

Getting Following error
          E/REALM_SYNC: Connection[1]: Writing failed: End of input

#### Version of Realm and tooling
Realm version(s): ?
4.1.1

Realm sync feature enabled: yes/no
Yes

Android Studio version: ?
3.0

Which Android version and device: ?
Android N

**Comment by Zhuinden** [comment]
Do you have INTERNET permission given to the app?

**Comment by beeender** [comment]
And what is your Realm Object Server version? realm-java 4.x needs the ROS version >= 2.0.0

**Comment by RajeshDhalange** [comment]
Yes obviously I have internet connection Its executing login function successfully

**Comment by RajeshDhalange** [comment]
Installed object server by following instruction https://realm.io/docs/get-started/installation/linux/

**Comment by cmelchior** [comment]
What does the server log say if you enable debug logging?

**Comment by RajeshDhalange** [comment]
Connection: Upgrade
Host: 51.255.50.246
Sec-WebSocket-Key: kPCn8PiwaPzC+8v99IPFhQ==
 Sec-WebSocket-Protocol: io.realm.sync.22
Sec-WebSocket-Version: 13
Upgrade: websocket
 Connection[1]: Writing failed: End of input
Connection[1]: Connection closed due to error
 Connection[1]: Reconnecting in 435 milliseconds
Connection[1]: Resolving '51.255.50.246:9080'
 Connection[1]: Connecting to endpoint '51.255.50.246:9080' (1/1)
 Connection[1]: Connected to endpoint '51.255.50.246:9080' (from '192.168.0.100:45864')
 Connection[1]: WebSocket::initiate_client_handshake()
 Connection[1]: HTTP request =
GET /realm-sync/%2Ffad4f82dbaa893bcadf968702735e3da%2F__management HTTP/1.1
 Authorization: Realm-Access-Token version=1

**Comment by RajeshDhalange** [comment]
Hello, team please help for this. It's decision-making time whether go with Realm or not.

**Comment by cmelchior** [comment]
Hi @RajeshDhalange Without more information it is hard to tell what might be the cause of this. Is the server sitting behind a firewall or similar that might prevent the connection?
