### ISSUE TITLE
Not able persist data after restart (Realm Android)

### ISSUE THREAD

**Issue by thakurSonu** [realm/realm-java#5509]
I am facing strange issue after restart my database value not exist. As i believe it due to third part lib (Quickblox). Because in fresh project it is working.  To fix this i try to create custom module still facing same issue. I am using below custom module still facing same issue.

1. can i restrict third party lib to change my config?
2. How can i fix issue using custom module. Can i override delete method? 

My Module code 

@RealmModule(classes = {ChatDialog.class, ChatQB.class, User.class})
public class RealmDocModule {
}

I am using below realm default instance. 

public static Realm getDefaultInstance() {
        if (realmConfiguration == null) {

            realmConfiguration = new RealmConfiguration.Builder()
                    .name(Global_Setting.REALM_NAME)
                    .migration(new RealmMigrations())
                    .schemaVersion(1)
                    .encryptionKey(Global_Setting.getResourceString(R.string.saltKey2).getBytes())
                    .modules(new RealmDocModule())
                    .build();
        }

        return Realm.getInstance(realmConfiguration);
    }

**Comment by cmelchior** [comment]
Hi @thakurSonu 

That code looks correct and shouldn't delete the Realm file, so most likely you have some other code running that does this. Given the available information it is pretty hard for me to speculate what though.

**Comment by thakurSonu** [comment]
I have third party lib Quickblox also using realm. Quickblox can delete my file? can i separate my config from quickblox.

**Comment by Zhuinden** [comment]
I honestly think you just call the Realm with the wrong configuration somewhere.

**Comment by thakurSonu** [comment]
no i am using my own above method RealmModule.getDefaultInstance(). Can you please guide me 
 stuck from last 2 day.

**Comment by thakurSonu** [comment]
**Application class**

Realm.init(this); 

**Custom Module**

public class RealmModule {

    private static RealmConfiguration realmConfiguration;

    private RealmModule(){}

    public static Realm getDefaultInstance() {
        if (realmConfiguration == null) {

            realmConfiguration = new RealmConfiguration.Builder()
                    .name(Global_Setting.REALM_NAME)
                    .migration(new RealmMigrations())
                    .schemaVersion(1)
                    .encryptionKey(Global_Setting.getResourceString(R.string.saltKey2).getBytes())
                    .modules(new RealmDocModule())
                    .build();
        }

        return Realm.getInstance(realmConfiguration);
    }
}

 **Get realm Method**
public static Realm getRealm() {
        return RealmModule.getDefaultInstance();
    }

**Insert or update work** 


RealmController.getRealm().executeTransactionAsync(new Realm.Transaction() {
                @Override
                public void execute(Realm realm) {



                    for (qb_list_getDialog model : params[0]) {

                        if(model.getParticipant() != null && model.getParticipant().size()>0) {
                            ChatDialogDb chatDialog = new ChatDialogDb();
                            chatDialog.setId(RealmController.getNextKey(realm, ChatDialogDb.class));
                            
                            realm.insertOrUpdate(chatDialog);
                        }


                    }



                }

            });

            RealmController.commitInput();
            RealmController.closeRealm();



public static void commitInput(){
        getRealm().beginTransaction();
        getRealm().commitTransaction();

    }

 public static void closeRealm(){
        getRealm().close();
    }

**Comment by thakurSonu** [comment]
finally working .. now

**Comment by Sopheak0** [comment]
@thakurSonu what is your solution?
