### ISSUE TITLE
Is Realm close automatically in method in which it was created?

### ISSUE THREAD

**Issue by lmdic** [realm/realm-java#5510]
Realm 4.1.
My activity:

```
public class MyActivity extends AppCompatActivity {
private Realm realm;


    @Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        Bundle extras = getIntent().getExtras();
        Produt product = null;
        if (extras != null) {
            product = extras.getInt(Product.PRODUCT);
        }
        setContentView(R.layout.shopping_details);
        realm = Realm.getDefaultInstance();
        imagesList = realm.copyFromRealm(product.getGallery());

        init(product);
}

  private void init(Product product) {
  // some stuff here
  }

   @Override
    public void onDestroy() {
        super.onDestroy();
        realm.close();
    }

```

OK. It's work. 
As you can see I create Relam in `onCreate() `method and close in `onDestroy()`.

But I need realm object **ONLY** in method `onCreate()`. I need to call method `realm.copyFromRealm(...) `only in `onCreate()

`So do the next change:

1. remove` onDestroy() `method
2. Remove declaration of variable: `private Realm realm;`
3. Change `onCreate() `method

Here result:

```

@Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        Bundle extras = getIntent().getExtras();
        Produt product = null;
        if (extras != null) {
            product = extras.getInt(Product.PRODUCT);
        }
        setContentView(R.layout.shopping_details);
        Realm realm = Realm.getDefaultInstance();
        imagesList = realm.copyFromRealm(product.getGallery());

        init(product);
}

  private void init(Product product) {
  // some stuff here
}


```
So as result I have:
1. I create Realm object only in specific method: `onCreate()`
2. After method `onCreate()` finish the realm object will be destroy automatically
3. In method `init() `the Realm object not exist
4. I don't need anymore to close Realm in method `onDestroy()`

Is I'm right?

**Comment by Zhuinden** [comment]
> I don't need anymore to close Realm in method onDestroy()
> Is I'm right?

No, now you're supposed to call `realm.close()` after `imagesList = realm.copyFromRealm(product.getGallery());`.

**Comment by lmdic** [comment]
something like this:

```
@Override
    protected void onCreate(@Nullable Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        Bundle extras = getIntent().getExtras();
        Produt product = null;
        if (extras != null) {
            product = extras.getInt(Product.PRODUCT);
        }
        setContentView(R.layout.shopping_details);
        Realm realm = Realm.getDefaultInstance();
        try {
            imagesList = realm.copyFromRealm(product.getGallery());
            init(product);
        } finally {
            realm.close();
        }
    }


    private void init(Product product) {
      // some stuff here
    }
```

So, no need to close  Realm in `onDestroy()` method?

?

**Comment by Zhuinden** [comment]
If you use copyFromRealm then no, but this also means you'll eagerly evaluate all your data on the UI thread. Which is... Well, with large enough data set, it is slow 

Also you can't add RealmChangeListener to an unmanaged list

**Comment by lmdic** [comment]
Resume:

1. In this case, not need close Realm in `onDestroy()`.
2. The method `product.getGallery()`  return little size of data (about 5 little objects). So as result there is not a problem to call `realm.copyFromRealm()` in UI thread.

Is I'm right?

**Comment by Zhuinden** [comment]
Yeah in that case your above code will work as you expect

**Comment by cmelchior** [comment]
@Imdic It sounds like your question was answered. If you need more information you can also read https://realm.io/docs/java/latest/#closing-realms and https://realm.io/docs/java/latest/#realm-instance-lifecycle
