### ISSUE TITLE
RealmError

### ISSUE THREAD

**Issue by yaxin3690** [realm/realm-java#5514]
11-08 11:22:14.273 10008 10008 E REALM_JNI: jni: ThrowingException 5, mmap() failed: Out of memory size: 134217728 offset: 1476395008 in /home/cc/repo/realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 207, .
14411-08 11:22:14.273 10008 10336 E REALM_JNI: jni: ThrowingException 5, mmap() failed: Out of memory size: 134217728 offset: 1476395008 in /home/cc/repo/realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 108, .
14511-08 11:22:14.283 10008 10008 E REALM_JNI: Exception has been throw: Unrecoverable error. mmap() failed: Out of memory size: 134217728 offset: 1476395008 in /home/cc/repo/realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 207

11-08 11:22:14.303 10008 10336 E REALM_JNI: Exception has been throw: Unrecoverable error. mmap() failed: Out of memory size: 134217728 offset: 1476395008 in /home/cc/repo/realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 108

**Comment by cmelchior** [comment]
You are trying to open a 140 MB file, which caused Android to run out of memory. Normally you should be able to open a file at that size, so most likely you are leaking resources somewhere in the system. One thing might be that you are forgetting to close your Realm instances when done with them.

You can check this by using `Realm.getGlobalInstanceCount(config)`. This can tell you on how many threads you a Realm file open.

**Comment by yaxin3690** [comment]
Yes, I checked, and found that the problem is to operate the same file in multiple threads

**Comment by nhachicha** [comment]
How are you closing the Realm you're using in the background? holding onto an old Realm in the background may increase the size of the file (as Realm need to keep all the versions in-between persisted)

**Comment by Zhuinden** [comment]
Check if `Realm.getGlobalInstanceCount()` is higher than expected.
