### ISSUE TITLE
File handles are not released in RealmTransformer

### ISSUE THREAD

**Issue by gavra0** [realm/realm-java#5521]
realm-gradle-plugin:4.1.1
Original issue: https://issuetracker.google.com/69114369
Android plugin for Gradle: 3.0.0

JarFile opened in RealmTransform is not closed, which causes issues on Windows. The issue seems to be this line: https://github.com/realm/realm-java/blob/c1302392424a3b8bed323d3164ed5f875551e174/realm-transformer/src/main/groovy/io/realm/transformer/RealmTransformer.groovy#L245

Stacktrace showing where the file got opened (and not closed) ->
[stacktrace.txt](https://github.com/realm/realm-java/files/1460873/stacktrace.txt)

There is another file handle to the same file, captured in this stacktrace ->
[stacktrace_classpool.txt](https://github.com/realm/realm-java/files/1460891/stacktrace_classpool.txt)

This one seems to be caused by not closing the javassist.JarClassPath opened on this line https://github.com/realm/realm-java/blob/c1302392424a3b8bed323d3164ed5f875551e174/realm-transformer/src/main/groovy/io/realm/transformer/RealmTransformer.groovy#L219

Thanks!

**Comment by cmelchior** [comment]
Should be fixed in `4.2.0-SNAPSHOT`
