### ISSUE TITLE
Input dispatching timed out

### ISSUE THREAD

**Issue by BaldaMax** [realm/realm-java#5522]
if you block the phone:
Reason: Input dispatching timed out (Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago.  Wait queue length: 37.  Wait queue head age: 5503.8ms.)

**Comment by nhachicha** [comment]
We need more context here. How is this related to Realm? are you doing a transaction on the UI thread?

**Comment by BaldaMax** [comment]
Sorry,I confused libraries, this does not apply to the realm. Sorry)
