### ISSUE TITLE
How can I listen for changes on an RealmObject or RealmResults

### ISSUE THREAD

**Issue by RajeshDhalange** [realm/realm-java#5526]
1. How can I implement particuler field change listener on Realm object? ie If I want to change listener like onCommentAdded, onCommentRemoved, onCommentUpdated on Feed Object
2.  In RealmResults change listener how to identified for which object updated or removed from the list?

**Comment by Zhuinden** [comment]
> onCommentAdded, onCommentRemoved, onCommentUpdated on Feed Object

using `RealmObjectChangeListener`

> In RealmResults change listener how to identified for which object updated or removed from the list?

You get the *position* where insertion/deletion/modification happens using `OrderedRealmCollectionChangeListener`

**Comment by cmelchior** [comment]
What @Zhuinden said.

`RealmObjectChangeListener` provides an [ObjectChangeset](https://realm.io/docs/java/latest/api/io/realm/ObjectChangeSet.html) and OrderedRealmCollectionChangeListener provides a [OrderedCollectionChangeSet](https://realm.io/docs/java/latest/api/io/realm/OrderedCollectionChangeSet.html)

**Comment by RajeshDhalange** [comment]
Thanks for help
