### ISSUE TITLE
Compile issue: javassist.CannotCompileException

### ISSUE THREAD

**Issue by coletz** [realm/realm-java#5527]
#### Goal

Just compile a project

#### Expected Results

The project compile

#### Actual Results

Gradle is not compiling, cleaning the project does nothing.
Seems like something is broken with the `BytecodeModifier$FieldAccessToAccessorConverter.edit` method. 

--stacktrace gist: https://gist.github.com/anonymous/46db0a479a9d71ad2e87c3df6433c5da
--debug gist: https://gist.github.com/anonymous/6c390cca19d4016965b0f744b438fa54

#### Steps & Code to Reproduce

I can't post the full project here (NDA) and really don't know what caused this problem. I will try to go back with commit and find the cause of the problem in the next few days. If I can't find the root of this problem I can provide the project stripping down every sensitive data

#### Version of Realm and tooling
Realm version: 4.1.0

Realm sync feature enabled: no

Android Studio version: 3.0 stable

**Comment by Zhuinden** [comment]
Hmm, that happens inside Javassist in `catch(BadBytecode e) {`.

See [the line](https://github.com/jboss-javassist/javassist/blob/e1f0bba5de4dc03a9debfab333683f07cfbcb594/src/main/javassist/expr/FieldAccess.java#L243).

I wonder what can cause this.

**Comment by coletz** [comment]
Solved, but dunno what the actual problem was. I was using Kotlin for everything but a class. Converted to Kotlin and the problem disappeared. But this class is a java class since forever and I've never had a problem until now. And I actually don't really know what's the root of the problem.

**Comment by Zhuinden** [comment]
> * @throws BadBytecode if the bytecode violates the jvm spec

> * @throws BadBytecode if the bytecode does not comply with the JVM specification

I don't know either, but something was totally broken!

**Comment by nhachicha** [comment]
did it start happening exactly at `4.1.0`?  we need to look at this since we're planning an update to JavaAssist to `3.22.0-GA` in `4.1.2`

**Comment by coletz** [comment]
I'm sure it was happening with 4.1.0, but I was using it already. Then I updated to 4.1.1 and the problem was still happening. As I said converting the file to kotlin stopped the problem. I can try to reproduce in some way but I haven't commited it so I don't have a copy of the problem

**Comment by nhachicha** [comment]
please re-open if you manage to reproduce.
