### ISSUE TITLE
Optimize realm database when Out of memory caused

### ISSUE THREAD

**Issue by kainjinez** [realm/realm-java#5528]
I'm facing with out of memory error. Here is stack trace:
`Exception io.realm.exceptions.RealmError: Unrecoverable error. mmap() failed: Out of memory size: 738197504 offset: 0 in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 238`
I found a solution is using `compactRealm` and I put `Realm.compactRealm(getRealmConfig());` at line 116 in `OnCreate()` of Application class.
It is ok if database become not too large enough to get `Out of memory size` or I get this exception.
`Exception io.realm.exceptions.RealmError: Unrecoverable error. mmap() failed: Out of memory size: 939524096 offset: 0 in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 238
io.realm.internal.SharedRealm.nativeGetSharedRealm (SharedRealm.java)
io.realm.internal.SharedRealm.<init> (SharedRealm.java:185)
io.realm.internal.SharedRealm.getInstance (SharedRealm.java:237)
io.realm.internal.SharedRealm.getInstance (SharedRealm.java:201)
io.realm.BaseRealm.compactRealm (BaseRealm.java:601)
io.realm.Realm.compactRealm (Realm.java:1772)
x.y.z.App.onCreate (App.java:116)`

#### Version of Realm and tooling
Realm version(s): 3.4 Snapshot

Android Studio version: 3.0.0

Which Android version and device: 5.0.2

**Comment by cmelchior** [comment]
If a database grows too large, it is most commonly a sign that you are not closing your Realm instances correctly. See https://realm.io/docs/java/latest/#closing-realms and https://realm.io/docs/java/latest/#realm-instance-lifecycle

But yes, otherwise using `compactRealm` or `compactOnLaunch` would be the way to reduce the size.

**Comment by kainjinez** [comment]
@cmelchior Ya. I tried to close realm carefully. But with Out of Memory user, i use `compactRealm` but it is too big to compact. What can I do?

**Comment by cmelchior** [comment]
It the Realm is too big to compact on the device your options are unfortunately limited. 

1) You can upload the file to a server and compact it there
2) You can create a new file and manually write all changes from one file to another.

Neither option is particularly appealing.

**Comment by kainjinez** [comment]
I'm very sure that cannot do these options. 
First, my stack trace is about 1GB database file, upload 1GB to server won't be a good option.
Second, I cannot get RealmInstance using `Realm.getInstance(config)` then I think i cannot access to data inside.

**Comment by nhachicha** [comment]
Hi @kainjinez one option is to try to open the Realm file on a desktop (which obviously should have more memory compared to the device) then perform a compaction. I created a feature request in RealmStudio https://github.com/realm/realm-studio/issues/422 for this.

Alternatively, you can try to use the Javascript SDK/.NET on desktop to open then compact the Realm

**Comment by kainjinez** [comment]
Hi @nhachicha your github link is 404 with me. It is pretty easy if it only happen with me, but too hard with users because I cannot ask Android users to copy their database from phone to desktop, then compact and copy to phone again. I'm thinking about alert them to delete database file and start over although it is a bad idea.

**Comment by Zhuinden** [comment]
How much data do you need to store in the database which makes you end up with such a large file?

**Comment by kainjinez** [comment]
Hi @austinzheng 
I forgot using `realm.close()` when developing small app. By time, i received some Firebase crash from user that they reached Out of Memory with Realm. Now i close realm in java code and trying to compact database for who reached Out of Memory error. That's it.

**Comment by eduxavier** [comment]
I know a year has passed but I'm on this serious problem too.  In the long run realm is so dificult to maintain and this was worse problem it happened to me in the past year. How can I say to a costumer that information recorded for the whole day is lost?

People say... you forgot to realm.close() or do realm.close() in the app. Now doesn't matter if I had closed or not (in my case I did), So I can't follow @cmelchior suggestion neither. This compactRealm or compactOnLaunch doesn't work at all. And as @kainjinez says, the systems breaks at the very first access at Realm.getInstance(config)... and now, nothing can be done.

After 24 hours looking for help, I believe is time to train the argument about loosing the customer for that. I don't trust Realm anymore. My costumers works offline and they are loosing sales info about whole day. Its seems so easy to use and maintain basic work but when it comes to big real hell problem, you down, man! You just loose!

**Comment by Zhuinden** [comment]
> Realm read transaction lifetimes are tied to the memory lifetime of Realm instances. Avoid “pinning” old Realm transactions by using auto-refreshing Realms and wrapping all use of Realm APIs from background threads

> In order to give you a consistent view of your data, Realm only updates the active version accessed at the start of a run loop iteration. This means that if you read some data from the Realm and then block the thread on a long-running operation while writing to the Realm on other threads, the version is never updated and Realm has to hold on to intermediate versions of the data which you may not actually need, resulting in the file size growing with each write.

> Any single Realm file cannot be larger than the amount of memory your application would be allowed to map — this changes per device, and depends on how fragmented the memory space is at that point in time. 

> Java cannot automatically administer these resources. It is essential that code that opens a Realm instance closes it when it is no longer needed. The underlying resources are released only when all of the instances on that thread are closed.

> https://realm.io/docs/java/latest/#faq-large-realm-file-size .

Yes, I do personally believe that you shouldn't be able to `open` a Realm instance and keep it alive outside of a scope, and its lifecycle should be managed by its observers (if you have a RealmResults with a registered RealmChangeListener, then keep it alive. If not, close it). I even wrote a not-official library for it.

And while the developer is in *too much control* of the lifecycle in this regard, I can't say these limitations are undocumented. Yet, people throw around `Realm.getDefaultInstance().where(...).findAll()` as if it was nothing.

**Comment by cmelchior** [comment]
Also keep an eye out for warnings like this: "Remember to call close() on all Realm instances. Realm %s is being finalized without being closed, this can lead to running out of native memory."

This Realm object finalizer will log this as warnings if close is not correctly called. If you don't see these and still run out of memory because of large file sizes, it means that you are actively holding on to resources somehow.
