### ISSUE TITLE
Sum an object from RealmList

### ISSUE THREAD

**Issue by ankursharma234** [realm/realm-java#5529]
App crashes on sum("realmList.object")
is sum allowed for an object in realm list inside an object ?

For example:

Foo is a realm object
final String id
final RealmList<User> userList

User is another realm object
which has following:
userName
age
etc.

now i have to sum userList.age

Can i perform the sum on it ? if not then whats the alternate way you can suggest

**Comment by Zhuinden** [comment]
RealmList.object.age should work
