### ISSUE TITLE
E/REALM_JNI: jni: ThrowingException 7, std::exception in /Users/zaki/fromgit/realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp line 1285,

### ISSUE THREAD

**Issue by lakmalz** [realm/realm-java#5530]
#### Goal

> What do you want to achieve?
My application chat application i have use realrecyclerviewadpter also.so some times return above i menstion exception when i scrolling conversation list in fragmentview
give me a answer for this exception from cpp file

#### Expected Results

> ?

#### Actual Results

E/REALM_JNI: jni: ThrowingException 7, std::exception in /Users/zaki/fromgit/realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp line 1285,

#### Steps & Code to Reproduce

> Describe your current debugging efforts.

#### Code Sample

```java

> Your code here. Bigger samples should ideally be as separate Android Studio project, 
> in gists/repositories or privately at help@realm.io)

```

#### Version of Realm and tooling
Realm version(s): ?
compile 'io.realm:android-adapters:1.4.0
classpath "io.realm:realm-gradle-plugin:2.1.1"

Realm sync feature enabled: yes/no

Android Studio version: ? 2.3.3

Which Android version and device: ?
All Android device, and specially i teseted in Samsung s7

**Comment by Zhuinden** [comment]
This no longer happens in Realm 3.0.0 and above, so...

I actually remember getting this message when multiple transactions occurred during the evaluation of an asynchronous query, and the asynchronous query took longer than the transaction commits. So the async query retrieved data from an "old version of Realm", and so `Exception 7` is `BadVersionException`, meaning the query has to be re-evaluated.

If I remember right, this shouldn't cause any actual problems beyond logs.

**Comment by beeender** [comment]
The mechanism of async queries has been changed a lot after we introduce the fine grained notifications. So please try to update to the latest version of realm-java.
