### ISSUE TITLE
Date.setTime isn't saved

### ISSUE THREAD

**Issue by Maxxan** [realm/realm-java#5533]
#### Goal

To save changes in the data.

#### Actual Results

Changes were not updated to the realm object. Where does the updated value disappear?

#### Code Sample

```java

class A extends RealmObject {
    Date date;
    public update(Date newDate) {
       // date = newDate 
        date.setTime(newDate.getTime()); // Set the internal date value instead of assigning it
    }
}

    final A a = realm.where(A.class).findFirst();

    realm.executeTransaction(new Realm.Transaction() {
        @Override
        public void execute(Realm realm) {
            a.updateDate(new Date(100)); // Set to some new date
        }
    });

    assert(a.getDate().getTime() == 100); // Fails since the date wasn't not saved.

```

#### Version of Realm and tooling
Realm version(s): 4.1.1

Realm sync feature enabled: no

Android Studio version: 3.0

Which Android version and device: SDK 24, emulator

**Comment by Zhuinden** [comment]
This is the same thing as with `byte[]`, it's the assignment operator that is swapped to proxy setter call, not modifying the mutable Date instance.

**Comment by Maxxan** [comment]
I make sure that I always use the assignment operator then. I was just surprised and had a few bugs due to this..
