### ISSUE TITLE
How to access realm in case realm folder outside android project import [bcz of react-native structure]?

### ISSUE THREAD

**Issue by zxccvvv** [realm/realm-java#5539]
I have react-native project with realm as database,

and for now i'm using android studio as a native module for react-native project,

the problem is how to access realm database in case my realm folder is outside android imported folder?

**Comment by beeender** [comment]
I don't get your question. Do you want to access Realm file with realm-java which is created by the realm react native?

**Comment by zxccvvv** [comment]
@beeender actually i've post the question in [StackOverflow](https://stackoverflow.com/questions/47320911/how-to-access-realm-model-realmobject-from-react-native-in-android-studio)

I want to access my `realmObject` that declared outside android project, because of limited tutorial, i'm not yet getting what i want,

**Comment by beeender** [comment]
Discussion is happening on SO . Close issue here.
