### ISSUE TITLE
Realm migration needed without Realm changes

### ISSUE THREAD

**Issue by shidobecker** [realm/realm-java#5542]
#### Goal

> Update my application without need to migrate Realm, or provide a migration that works for all cases

#### Expected Results

> Application updated without RealmMigrationNeededException.

#### Actual Results

> Sometimes I'm getting a RealmMigrationNeededException, sometimes I don't.
Reference: [https://stackoverflow.com/questions/47210891/realm-migration-required-without-realm-structure-changes]
@cmelchior answered my there, but I still can't understand what's going on.

#### Steps & Code to Reproduce

> 1) Publish an android app with build version number  24. 
> 2) Realm schema version number is the same as build version number. Make no changes to Realm objects, update it to 25, ou 26, or 27. 

No migration should be required but it does. And providing a simple code as listed below works for some cases but doesn't in other cases.
I'm getting all kinds of migration exception messages, from

> Field count is more than expected - expected 4 but was 5

> The 'Table' class is missing from the schema for this Realm.

But it doesn't happen everytime, that's why it bugs me,  I've tested with all app versions that I had on store. Installed, logged in, and then installed my newer version with my migration, it never breaks. But I'm getting fabric crashes like thoses listed above in some cases.
I trying to understand a couple of things. Like why it happens sometimes only?
And why Realm is asking for a migration since I didn't change anything in any RealmObject?
I already made some changes, changed build version and Realm didn't ask for any migration, which I think it's the correct behavior. 
I'm avoiding to go to  _deleteRealmIfMigrationNeeded_  because I don't know how many users will have their data erased. But it looks like it's the only way to workaround this issue.

#### Code Sample

```
 if (oldVersion == 24) {

        oldVersion++;
    }

```

This is my AppClass code to get Realm configuration:

```
 Realm.init(this);

realmConfiguration = new RealmConfiguration.Builder()
            .schemaVersion(BuildConfig.VERSION_CODE)
            .migration(new MigrationUtil())
            .build();
        Realm.setDefaultConfiguration(realmConfiguration);

```

And this is the changes I've made to force a deleteRealm in case a migration exception occurs(which i left it commented for now)

```
        Realm.init(this);

realmConfiguration = new RealmConfiguration.Builder()
                .schemaVersion(BuildConfig.VERSION_CODE)
                .migration(new MigrationUtil())
                .build();
        Realm.setDefaultConfiguration(realmConfiguration);

        try{
            Realm realm = Realm.getInstance(realmConfiguration);
            realm.close();
        }catch(RealmMigrationNeededException e){
            Realm.deleteRealm(realmConfiguration);
        }
        Realm.getInstance(realmConfiguration);
```

#### Version of Realm and tooling
Realm version(s): 3.3.2

Realm sync feature enabled: no

Android Studio version: 3.0.0

Which Android version and device: Android versions 5, 6 and 7
Devices list:
TCL 8050E
LG K8 LTE
ASUS_Z017DC
Samgung Galaxy J7

**Comment by Zhuinden** [comment]
Generally if you get `RealmMigrationNeededException` *sometimes* then you might have a call to `Realm.getDefaultInstance()` without having set your own custom configuration first.

Otherwise you could have missed something in your migration code. 

A last resort I can offer is this ["somewhat alpha although it should work"](https://github.com/Zhuinden/realm-helpers/blob/master/realm-auto-migration/src/main/java/com/zhuinden/realmautomigration/Realmautomigration.java) class that works only with Realm 4.0.0+ (so 4.1.1) but if you annotate your RealmList fields properly, it can migrate the Realm's schema to match the models. Please don't forget the Proguard configuration as it is reflection based.

**Comment by shidobecker** [comment]
@Zhuinden  Thank you for your reply, this is getting clear to me. I provided my AppClass code to see if the second block of code, which I left commented is what I should be doing.

I'll try to update realm plugin and take a look to this migration helper class.

**Comment by Zhuinden** [comment]
The migration helper can be used either in a migration, or you can also use it with `DynamicRealm dynRealm = DynamicRealm.getInstance(config)`.

**Comment by ppamorim** [comment]
I recommend you to update `Realm` to last version. @Zhuinden Wasn't this version that included this issue on build > `3.3.0`?

**Comment by shidobecker** [comment]
@ppamorim Thank you for your reply, I updated to version 4.1.1, and we'll probably release our new version with it, and still make some tests with the auto migration class @Zhuinden provided.  I'll still use the code to force a deleteRealm in case a migration fails.
But interesting to know this  might be a bug on that build. Because the weird thing about it is that Realm asked for a migration without any realm structure changes.

**Comment by Zhuinden** [comment]
The migration was probably caused by the Realm Object Store schema verification integration, although while I've seen people saying they've been getting unexpected migrations, it also provides better error messages, so it should be able to tell you what is mismatched in the schema.

Still, that lib I linked should be able to undo any mismatches, but it takes the latest RealmModels into account.

**Comment by shidobecker** [comment]
@Zhuinden I'll force those migration exceptions from different versions of my app to see what messages it gives me, and I'll post it then

**Comment by shidobecker** [comment]
@Zhuinden Sorry for the delay, 
So I've tested all different versions that we had on store, and the only Migration message is this one:

                                                   java.lang.RuntimeException: Unable to start activity ComponentInfo{edu.mira.aula/edu.mira.aula.Activities.SplashActivity}: io.realm.exceptions.RealmMigrationNeededException: Realm on disk need to migrate from v22 to v29


And it only varies the "from" and "to" versions.

That's why provided this  simple code:

 if (oldVersion <= 22) {
            oldVersion = 29;
        }


This solved but still made some devices crashes.
I'm going to test realm 4.1.1 with auto migration soon to give you another feedback.

**Comment by Zhuinden** [comment]
@shidobecker just make sure to apply the MigratedList annotation of RealmLists and don't forget the proguard rules.

**Comment by shidobecker** [comment]
Just to make sure, proguard configs are these ones right?
-keep class io.realm.annotations.RealmModule
-keep @io.realm.annotations.RealmModule class *
-keep class io.realm.internal.Keep
-keep @io.realm.internal.Keep class *
-dontwarn javax.**
-dontwarn io.realm.**

Or there are more?

And the MigratedList annotation I can annotate on every RealmList on every model, correct?

**Comment by shidobecker** [comment]
@Zhuinden I've made some tests with the auto migration class you provided, it works fine on almost every case except for lists.
I annotated them with MigratedList annotation like this:

`open class Occurrence(
        @PrimaryKey var id: String ="",
        var testLong: Long = 2,
        var testString: String = "test string",
        var testInt: Int = 100,
        @RealmAutoMigration.MigratedList(listType = SimpleContent::class)
        var simpleContents: RealmList<SimpleContent> = RealmList()
): RealmObject()`

My proguard rules:

`-keepnames public class * extends io.realm.RealmObject
-keep @io.realm.annotations.RealmModule class *
-keep class io.realm.** { *; }
-dontwarn javax.**
-dontwarn io.realm.**
-keepattributes *Annotation*`

Tried adding a list in a java class realm model and the same error happened:
   Caused by: io.realm.exceptions.RealmMigrationNeededException: Migration is required due to the following errors:
                                                   - Property 'Teacher.simpleContents' has been added.


Am I missing something? Are my annotations not been processed? 

Don't know if it helps, but I have this on my build.gradle


```
kapt {
    generateStubs = true
    arguments {
        arg("realm.ignoreKotlinNullability", true)
    }
}

```

**Comment by Zhuinden** [comment]
@shidobecker it says `Teacher.simpleContents` and not `Occurrence.simpleContents` though, maybe the `@MigratedList` is missing there?

**Comment by shidobecker** [comment]
Sorry I pasted the wrong message. "Teacher.simpleContents "was the message I received when i tried adding this same in a java class. But a error message with "Occurrence.simpleContents"  was shown as well

**Comment by Zhuinden** [comment]
@shidobecker aaahhh you might be right! I think when I added support for primitive RealmList, I messed up the following line of code:

`if(listType.isAssignableFrom(RealmModel.class)) {`

and it should be

`if(RealmModel.class.isAssignableFrom(listType)) {`

How disappointing. Now that's exactly why I shouldn't have been lazy with the integration tests.

**Comment by shidobecker** [comment]
@Zhuinden It works!!! Man, I'm so happy, you have no idea, it worked like a charm, I have no words to describe how amazing this is. Really, I should buy you a beer! This is one of many reasons why working with Realm is so much fun.

**Comment by Zhuinden** [comment]
@shidobecker  thank *you* for the bug report! 🙂 

Although now that I check again, you should also add the following Realm-Auto-Migration specific proguard:

```
-keepnames public class * extends io.realm.RealmModel
-keep public class * extends io.realm.RealmModel { *; }
```

Because I need to know the name of the RealmObjects in order to get them from the schema, without working with internal things inside the realm schema mediator.

**Comment by shidobecker** [comment]
@Zhuinden  My pleasure, you have my thanks for helping me so much with Realm.

And I just added
My final proguard-rules looked like this:

```
-keepnames public class * extends io.realm.RealmObject
-keep public class * extends io.realm.RealmModel { *; }
-keep @io.realm.annotations.RealmModule class *
-keep class io.realm.** { *; }
-dontwarn javax.**
-dontwarn io.realm.**
-keepattributes *Annotation*
```

**Comment by beeender** [comment]
It seems the issue is solved. Feel free to reopen it if needed. 🎉
