### ISSUE TITLE
The data is changes are reverted as i removes the app from recent in android app. The data is updated using the realm.executeTransactionAsync method.

### ISSUE THREAD

**Issue by manmohansoni** [realm/realm-java#5544]
#### Goal

> What do you want to achieve?

#### Expected Results

> ?

#### Actual Results

>  E.g. full stack trace with exception

#### Steps & Code to Reproduce

> Describe your current debugging efforts.

#### Code Sample

```java

> Your code here. Bigger samples should ideally be as separate Android Studio project, 
> in gists/repositories or privately at help@realm.io)

```

#### Version of Realm and tooling
Realm version(s): ?

Realm sync feature enabled: yes/no

Android Studio version: ?

Which Android version and device: ?

**Comment by Zhuinden** [comment]
```
Actual Results

E.g. full stack trace with exception
Steps & Code to Reproduce

Describe your current debugging efforts.
Code Sample

> Your code here. Bigger samples should ideally be as separate Android Studio project, 
> in gists/repositories or privately at help@realm.io)
```

**Comment by beeender** [comment]
Without more information, we are not able to give any suggestions on this issue.
