### ISSUE TITLE
Suggestion: Bad encryption exception is too broad - IllegalArgumentException

### ISSUE THREAD

**Issue by magillus** [realm/realm-java#5545]
#### Goal
Can we have better encryption handling exception thrown from Realm? 
Currently when bad passphrase is used on configuration the `IllegalArgumentException: Wrong key used to decrypt Realm.` is thrown.

#### Expected Results

I would like to suggest to use `RealmFileException` with its own `RealmFileException.Kind.WRONG_ENCRYPTION_KEY` or something similar to better catch that specific issue and handle it.

**Comment by cmelchior** [comment]
Hi @magillus Doing so is not trivial due to how encryption works. We have an issue already tracking this however, so I'll fold this issue into https://github.com/realm/realm-java/issues/3641 where you can also see the details.

Closing as a duplicate.
