### ISSUE TITLE
Issue with custom realm directory setup

### ISSUE THREAD

**Issue by saravanakumarimpiger** [realm/realm-java#5549]
I tried to set custom directory with realm configuration in android. While accessing the path, its simply returning default canonical path. 
      

Is my data saved in custom  path or in default path?
Please some one help, how to setup  custom path to save data? 

#### Expected Results
To know where my data saved

#### Actual Results
Need to save my data in custom path

#### Code Sample

   Realm.init(this);
        String path = getFilesDir().getPath();
        File realmFile = new File(path);
        RealmConfiguration realmConfiguration = new RealmConfiguration
                .Builder()
                .directory(realmFile)
                .name("appname.realm")
                .deleteRealmIfMigrationNeeded()
                .build(); 
         Realm.setDefaultConfiguration(realmConfiguration);
        Logger.d("Realm Migration Config Success", Realm.getDefaultConfiguration().getPath());//Error returning path

> Your code here. Bigger samples should ideally be as separate Android Studio project, 
> in gists/repositories or privately at help@realm.io)

```

#### Version of Realm and tooling
Realm version(s): 4.2.0

Realm sync feature enabled: yes/no

Android Studio version: 3.0

Which Android version and device: ?

**Comment by Zhuinden** [comment]
`getFilesDir()` returns the default `data` folder of your application, which is the same thing as the default.

**Comment by saravanakumarimpiger** [comment]
Thanks for your reply
While using getFilesDir() it returns /data/user/0/com.app.test/files/
But canonical path returning as  /data/data/com.app.test/files/

**Comment by cmelchior** [comment]
They are the same thing on disk. One is just a symlink to the other (or that is normally the case)

**Comment by saravanakumarimpiger** [comment]
https://github.com/realm/realm-java/issues/5546
Can you please refer this issue. We get this issue. so only we moved to custom path setup

**Comment by saravanakumarimpiger** [comment]
We created custom path for realm and configured to it. but while accessing 
  Realm realm = Realm.getDefaultInstance();

We are getting error:
Caused by: io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/user/0/com.dentons.compass.test/files/dentons.realm.management': make_dir() failed: No such file or directory. (make_dir() failed: No such file or directory) (/data/user/0/com.dentons.compass.test/files/dentons.realm.management) in /home/cc/repo/realm/release/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101 Kind: ACCESS_ERROR.
                                                         at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
                                                         at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:172)
                                                         at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:219)

Can you please look on it

**Comment by beeender** [comment]
I have asked for a trial of MDM. Let's see if we can reproduce it.

**Comment by saravanakumarimpiger** [comment]
Thanks.
Comment here once you are able to reproduce it.

**Comment by beeender** [comment]
Hi, I just use the MDM to install our introExample (https://github.com/realm/realm-java/tree/master/examples/introExample) and it works fine.

Since it works fine without MDM, maybe you need to seek help from MDM?

**Comment by beeender** [comment]
@saravanakumarimpiger Any updates for this issue? Did you get any response from MDM?

**Comment by saravanakumarimpiger** [comment]
Issue seems to be due to the changes happening as part of the MDM wrapping process. We are checking this further and will post a note once we have some findings.
