### ISSUE TITLE
query objects by child attribute with in() return all objects

### ISSUE THREAD

**Issue by kmitj** [realm/realm-java#5554]
**Goal**

query objects by child attribut with in() retrun all objects

#### Code Sample

```java

public class Chat extends RealmObject {
    private RealmList<Contact> contactsList;
}
public class Contact extends RealmObject {
    private PhoneNumber phoneNumber;
}
public class PhoneNumber extends RealmObject {
    private String number;
}

String tArray[] = new String[]{"234234","234423432","23432423"};
RealmQuery<Chat> realmQuery  = realm.where(Chat.class).in("contactsList.phoneNumber.number",tArray);
RealmResults<Chat> chatList = realmQuery.findAll();

#### Version of Realm and tooling
Realm version(s): ?
4.1.0

Realm sync feature enabled: yes/no
no

Android Studio version: ?
3

Which Android version and device: ?
Android version: Android 7.0
Devices:
    Galaxy S7

**Comment by beeender** [comment]
It might be the thing we documented here: https://realm.io/docs/java/latest/#link-queries

Please take a look at it first.

**Comment by michael-snow** [comment]
`String tArray[] = new String[]{"234234","234423432","23432423"};
 RealmQuery<Chat> realmQuery  = realm.where(Chat.class).in("contactsList.phoneNumber.number",tArray);
 RealmResults<Chat> chatList = realmQuery.findAll();
`

this query return all objects from realm. In(contactsList.phoneNumber.number,tArray) not works.

**Comment by beeender** [comment]
Can you create a sample project to show the problem?

**Comment by mgohin** [comment]
Maybe related to : https://forums.realm.io/t/more-than-one-value-in-a-in-and-i-become-crazy/727/3 ? 
I created an example project to show the problem

**Comment by beeender** [comment]
see relevant core issue https://github.com/realm/realm-core/issues/2945
