### ISSUE TITLE
java.lang.UnsatisfiedLinkError: No implementation found for void io.realm.internal.e.nativeCleanUp(long, long) 

### ISSUE THREAD

**Issue by TomBoBo** [realm/realm-java#5563]
I installed version 2.1.0 before ,  and now I want to upgrade to version 4.2.0 .When not proguard, he can work normally，Error after minifyEnabled setting “true”.

**Error message：**
java.lang.UnsatisfiedLinkError: No implementation found for void io.realm.internal.e.nativeCleanUp(long, long) (tried Java_io_realm_internal_e_nativeCleanUp and Java_io_realm_internal_e_nativeCleanUp__JJ)
	at io.realm.internal.e.nativeCleanUp(Native Method)
	at io.realm.internal.e.a(NativeObjectReference.java:87)
	at io.realm.internal.k.run(FinalizerRunnable.java:38)
	at java.lang.Thread.run(Thread.java:818)

**realm version :** 
4.1.0  4.2.0

**error code  about   app/build.gradle ：**
buildTypes {
        debug {
            resValue "string", "app_name", "*******"
            buildConfigField("boolean", "LOG_DEBUG", "true")  
            minifyEnabled true
            zipAlignEnabled true
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
            testCoverageEnabled true
        }
    }

**normal code  about   app/build.gradle ：**
buildTypes {
        debug {
            resValue "string", "app_name", "*******"
            buildConfigField("boolean", "LOG_DEBUG", "true")  
            **minifyEnabled false**
            zipAlignEnabled true
            shrinkResources false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
            signingConfig signingConfigs.release
            testCoverageEnabled true
        }
    }

**Comment by TomBoBo** [comment]
Please help me find zhe reason , very thanks.

**Comment by Zhuinden** [comment]
That's odd, `io.realm.internal.FinalizerRunnable` is not kept by proguard.

If you specify 

`-keep class io.realm.internal.** { *;} 

Then it'll work, although you shouldn't have to. @beeender?

**Comment by TomBoBo** [comment]
we have tired it , it not work .

**Comment by beeender** [comment]
It doesn't same to be related with proguard, it feels like your apk is running with the old version of realm native `so` files.

Try to do a full clean & rebuild.

It is still doesn't work, please share your root and app level `build.gradle`.

**Comment by TomBoBo** [comment]
I`m sure not old version of realm native so files. how can  i do?

**Comment by TomBoBo** [comment]
is very strange ,as the document of realm says: don't need us write the proguard file ,but when we run the release task and  set the minifyEnabled "true"。and the bug is occur

**Comment by TomBoBo** [comment]
which method of java will invoke the io.realm.internal.e.nativeCleanUp?

**Comment by beeender** [comment]
Try with:

```
-keepclasseswithmembernames,includedescriptorclasses class * { 
    native <methods>; 
} 
```

See https://www.guardsquare.com/en/proguard/manual/examples#native

But this is strange, this should be the default option for proguard IMO. You are the first one meet this problem.

**Comment by TomBoBo** [comment]
**I tried this code  ,  but it can`t keep the target method.**


**proguard-rules.pro**
-keep class com.gome.work.oa.model.bean.** { *; }
-keep class com.gome.work.im.model.bean.** { *; }
-keep class com.gome.work.im.channel.model.bean.**{*;}
-keepclasseswithmembernames,includedescriptorclasses class * {
    native <methods>;
}

**mapping.txt**
o.realm.internal.NativeObject -> io.realm.internal.d:
    long NULLPTR -> NULLPTR
    long getNativePtr() -> getNativePtr
    long getNativeFinalizerPtr() -> getNativeFinalizerPtr
io.realm.internal.NativeObjectReference -> io.realm.internal.e:

**Comment by Zhuinden** [comment]
`-keep class io.realm.internal.** { *;}` ?

**Comment by TomBoBo** [comment]
I found the reason, we made a low - level error, using another wrong mapping.txt file.
Thank you very much for the suggest  @beeender  @Zhuinden offered.

the error code is **'-applymapping mapping.txt'** at -applymapping mapping.txt .   The problem was solved by removing the error code
