### ISSUE TITLE
The data obtained from the database is not updated

### ISSUE THREAD

**Issue by liuguangsen** [realm/realm-java#5565]
#### Goal

> What do you want to achieve?

#### Expected Results

> ?

#### Actual Results

>  E.g. full stack trace with exception

#### Steps & Code to Reproduce

> Describe your current debugging efforts.

#### Code Sample

```java

> Your code here. Bigger samples should ideally be as separate Android Studio project, 
> in gists/repositories or privately at help@realm.io)

```

#### Version of Realm and tooling
Realm version(s): ?

Realm sync feature enabled: yes/no

Android Studio version: ?

Which Android version and device: ?

**Comment by Zhuinden** [comment]
> Your code here. Bigger samples should ideally be as separate Android Studio project, 
> in gists/repositories or privately at help@realm.io)

**Comment by liuguangsen** [comment]
I can give a simple for that , as follows：
First，Entity class  
 class User extends RealmObject {
    private String name；
    private int  age；
 。。。。。。set andr get
}
Then， I user okhttp to get a jsonString and get a User from response，code is as follows：
Realm realm = Realm.getDefaultInstance();
                                        realm.beginTransaction();
                                        realm.insertOrUpdate(user);
                                        realm.commitTransaction();
In the same code location，I got the User right away，code is as follows：
 Realm realm = Realm.getDefaultInstance();
            User first = realm.where(User.class).findFirst();
            String name =first.getName;
          Log.d(TAG,"name1"+name);

Then，I have a class ，here is this：
class UserUtil{
    public static String isNewstUser(){
         Realm realm = Realm.getDefaultInstance();
            User first = realm.where(User.class).findFirst();
            String name =first.getName;
          Log.d(TAG,"name2"+name);
     }
}，only I call the method isNewstUser() in a In the child thread 。
finally，I find the Log  name1  and name2  is different and name2  is  old value ，but name1 is newest value。 why ？？？  why The reaml results obtained by two different code locations are different ？

**Comment by Zhuinden** [comment]
``` java
Realm realm = Realm.getDefaultInstance();
realm.beginTransaction();
realm.insertOrUpdate(user);
realm.commitTransaction();
```

should be

``` java
try(Realm realm = Realm.getDefaultInstance()) {
    realm.executeTransaction((r) -> {
        r.insertOrUpdate(user);
    });
}
```

**Comment by Zhuinden** [comment]
And

``` java
Realm realm = Realm.getDefaultInstance();
User first = realm.where(User.class).findFirst();
```

should be

``` java
try(Realm realm = Realm.getDefaultInstance()) {
    User first = realm.where(User.class).findFirst();
    Log.d(TAG,"name2"+name);
    return name；
}
```

**Comment by liuguangsen** [comment]
I will have a try , thank you
