### ISSUE TITLE
error after opening realm file from older core version

### ISSUE THREAD

**Issue by idok595** [realm/realm-java#5572]
realm version:4.2.0

/home/jenkins/workspace/lm_realm-core_release_4.0.2-RNFCDCCLGDTPVWB6AN462VLRP3AO2MMCJ4FCKBECRDMDNG3DX22A@2/src/realm/util/thread.cpp:183: [realm-core-4.0.2] Destruction of mutex in use
                                                          IMPORTANT: if you see this error, please send this log to help@realm.io.

**Comment by Zhuinden** [comment]
If this happens each time, you might want to send the Realm file over to help[at]realm.io

**Comment by beeender** [comment]
do you have a full backtrace of this issue?

**Comment by beeender** [comment]
Dup to #5578
