### ISSUE TITLE
Add support for JWT authentication

### ISSUE THREAD

**Issue by nirinchev** [realm/realm-java#5580]
We need to provide a built-in credentials type for JWT. It only accepts a token like:

```java
SyncCredentials credentials = SyncCredentials.JWT("my-token");
```

ROS issue: https://github.com/realm/realm-object-server-private/issues/701

**Comment by cmelchior** [comment]
Just to mention it here. This is already supported today by using 
```
SyncCredentials.custom("my-token", "jwt", null);
``

**Comment by nirinchev** [comment]
Yes - all bindings have support for login with custom provider, but we'd like to make it more streamlined and easy to discover.

**Comment by cmelchior** [comment]
Sure, it is being added in #5581
