### ISSUE TITLE
The condition equalTo() seems wrong

### ISSUE THREAD

**Issue by JarvanMo** [realm/realm-java#5585]
Here's peek from my java file ```PlayHistory.java```:
```java
public class PlayHistory extends RealmObject{
    @PrimaryKey
    private String id;
    public String categorySn = "";
    public String mediaSn = "";
    private int type = TYPE_AUDIO_ONLY;
}
```
And this my query:
```java
 PlayHistory playHistory = realm.where(PlayHistory.class)
                .equalTo("type", type)
                .equalTo("categorySn", categorySn)
                .findFirst();
```
It works well until the categorySn   becomes integer, like "11115454454".The ```playHistory``` is always ```null```  if  ```categorySn``` is an integer.
I don't know why.
I use Realm-4.2.0.

**Comment by cmelchior** [comment]
Your primary key is a `String`, so trying to use an `Int` as input will not work as Realm will not automatically convert the value to a String. It should not return `null` though, but throw an exception instead.

**Comment by JarvanMo** [comment]
I can't promise  ```categorySn```  is always a normal ```String```.

**Comment by beeender** [comment]
I feel that after you change `categorySn` to integer, the stored data was not correct. How do you store it? You may need to inspect your realm file first. try realm-studio.

**Comment by JarvanMo** [comment]
@beeender  Here's my peek from realm-studio:
![image](https://user-images.githubusercontent.com/11608487/33701012-911da6b6-db57-11e7-8655-ed9e32c5c173.png)

**Comment by Zhuinden** [comment]
Maybe it's actually a `long` and not an `int`?

**Comment by JarvanMo** [comment]
@Zhuinden I think that's not the point because the `categorySn` is stored as a `String`。

**Comment by beeender** [comment]
@JarvanMo from the screenshot, your `categorySn` is `String`.  is it possible that `categorySn` has some characters doesn't match the case? by default, the `equalTo` is case sensitive match.
Also, is it possible that your string has some invisible characters? maybe you can try with `contains(fieldName, value, Case.INSENSITIVE)` to identify the issue.

**Comment by VenomVendor** [comment]
@beeender 
From the issue reported.
>  It works well until the categorySn becomes integer, like "11115454454".

```java
String test = "11115454454";
System.out.println(test.toUpperCase().equals(test.toLowerCase())); // true
````

@JarvanMo 
What is the log of below snippet.

```java
RealmResults<PlayHistory> playHistories = realm.where(PlayHistory.class)
                                            .equalTo("type", type)
                                            .findAll();

for (PlayHistory playHistory : playHistories) {
    if (categorySn.equals(playHistory.categorySn)) {
        Log.e(TAG, "Match Found : Id is " + playHistory.id);
        break;
    } else if (categorySn.trim().equals(playHistory.categorySn)) {
        Log.e(TAG, "Match Found, but not valid : Id is " + playHistory.id);
        break;
    } else if (playHistory.categorySn != null
            && categorySn.trim().equals(playHistory.categorySn.trim())) {
        Log.e(TAG, "Match Found, but double Invalid : Id is " + playHistory.id);
        break;
    }
}
```

**Comment by beeender** [comment]
close due to no response
