### ISSUE TITLE
4.3.0 adds kotlin stdlib into project

### ISSUE THREAD

**Issue by Kazemir** [realm/realm-java#5587]
After update from 4.2.0, I found that my project had a dependency on kotlin stdlib.

Well, I'm glad that kotlin became official language for Android Development, but isn't it too soon? :)
I guess, that is a bug and kotlin + extensions must be optional.

#### Version of Realm and tooling
Realm version(s): 4.3.0
Realm sync feature enabled: no
Android Studio version: 3.0.1

**Comment by cmelchior** [comment]
It should only do that if you already include Kotlin?

But you can disable it by adding this to your `build.gradle`:

```
android {
...
}
realm {
  kotlinExtensionsEnabled = false
}

**Comment by Kazemir** [comment]
I do not use kotlin in project. Also, there is no Kotlin classes in apk when I build it with 4.2.0.
With `kotlinExtensionsEnabled = false` I also have Kotlin classes in output apk. I'll try to create example project.

**Comment by Kazemir** [comment]
Here is an example project: [RealmKotlinExample.zip](https://github.com/realm/realm-java/files/1531984/RealmKotlinExample.zip)
And here is an APK analyzer result of assembleDebug output:
![apk](https://user-images.githubusercontent.com/1805554/33618258-9bdba9b6-da14-11e7-842e-5b46db933114.png)

**Comment by cmelchior** [comment]
I can reproduce this. It's a really embarrassing bug 😢 . There will be a 4.3.1 fixing this tomorrow.

**Comment by cmelchior** [comment]
Fixed by #5592

**Comment by cmelchior** [comment]
4.3.1 has been released with a fix for this

**Comment by Kazemir** [comment]
Thanks! Now it works properly.
