### ISSUE TITLE
Lists Of Primitives for Kotlin-types (String, Int etc.)

### ISSUE THREAD

**Issue by hardysim** [realm/realm-java#5594]
#### Goal

I want to use the new **Lists Of Primitives**-Feature with **Kotlin**.
So it needs to support Kotlin-types as well (e.g. `kotlin.String` instead of only `java.lang.String`).

See https://realm.io/docs/java/latest/#lists-of-primitives
Refs https://github.com/realm/realm-java/pull/5031#issuecomment-346624558

#### Expected Results

A `RealmList` with a Kotlin-type should be possible.

```kotlin
open class Foo(
        var bar: RealmList<kotlin.String>? = null
) : RealmObject()
```

#### Actual Results

The compiler gives the following error:

> Error:Element type of RealmList must be a class implementing 'RealmModel' or one of the 'java.lang.String', 'byte[]', 'java.lang.Boolean', 'java.lang.Long', 'java.lang.Integer', 'java.lang.Short', 'java.lang.Byte', 'java.lang.Double', 'java.lang.Float', 'java.util.Date'.

Using `RealmList<java.lang.String>` produces the same error.

#### Steps & Code to Reproduce

Just create a new Kotlin-class with the code above and try to compile.

#### Code Sample

See code above

#### Version of Realm and tooling
Realm version(s): 4.2.0 / 4.3.0

Realm sync feature enabled: no

Android Studio version: 3.0.1

Which Android version and device: 8.1 beta (but doesn't matter)

**Comment by Zhuinden** [comment]
Can you try adding `@Required` annotation on it?

**Comment by hardysim** [comment]
> Can you try adding @Required annotation on it?

You mean like this?

```kotlin
open class Foo(
        @Required
        var bar: RealmList<String>? = null
) : RealmObject()
```

Nope, does not work. Same error.

**Comment by Zhuinden** [comment]
Maybe `@field:Required var bar: RealmList<String>? = null`

**Comment by hardysim** [comment]
> Maybe `@field:Required var bar: RealmList<String>? = null`

Nope. Does not compile neither.

---

And I don't see the idea behind this, because the compiler is clearly stating that the *generic* used for `RealmList` must be one of the mentioned classes:

> `java.lang.String`, `byte[]`, `java.lang.Boolean`, `java.lang.Long`, `java.lang.Integer`, `java.lang.Short`, `java.lang.Byte`, `java.lang.Double`, `java.lang.Float`, `java.util.Date`

So it looks like one need to modify the *allowed types for the generic* in `RealmList` (and not adding some annotations to the model-class).

---

Funny though, the signature of `RealmList` in `realm-android-library-4.3.0-sources.jar` looks like this:

```java
public class RealmList<E> extends AbstractList<E> implements OrderedRealmCollection<E>
```

So it does not define any of those types and should actually *allow any type*?!

**Comment by Zhuinden** [comment]
The `RealmList` does, but the annotation processor will throw an error at compile time.

What's weird is that I'm pretty sure this worked for me last time I tried it. What's your Gradle plugin apply order?

**Comment by hardysim** [comment]
Ah ok, good to know. Thanks.

My order is:

```gradle
apply plugin: 'com.android.library'
apply plugin: 'kotlin-android'
apply plugin: 'kotlin-android-extensions'
apply plugin: 'com.jakewharton.hugo'
apply plugin: 'realm-android'
```

**Comment by Zhuinden** [comment]
Ah. `apply plugin: 'kotlin-kapt'` is missing from before `realm-android`

**Comment by hardysim** [comment]
> `apply plugin: 'kotlin-kapt'` is missing

This does the trick!

I didn't saw it in the documentation but it's (now?) there.
So anyone stumbling over this issue have a look at https://realm.io/docs/java/latest/#kotlin
