### ISSUE TITLE
Realm.getInstance(String key) method?

### ISSUE THREAD

**Issue by anggrayudi** [realm/realm-java#5595]
#### Goal

Will Realm add `Realm.getInstance(String key)` method, instead of `Realm.getInstance(RealmConfiguration configuration)`?

#### Expected Results
Using `Realm.getInstance(RealmConfiguration configuration)` is hard to maintain the memory leak. We need to set `RealmConfiguration` instance to `null` when app is closed to prevent the leak. But sometimes, recreating a new instance of this configuration causes <i>Realm configuration cannot be initiated twice.</i> So, is there a safer method to replace it? I mean, can you add `Realm.getInstance(String key)` method?

I hope we can get the instance easier:

````
Realm.addConfiguration("config_item_buy", new RealmConfiguration.Builder()
                .schemaVersion(0)
                .name("store.realm")
                .migration(new DataMigration())
                .build());

Realm realm = Realm.getInstance("config_item_buy");
````

**Comment by Zhuinden** [comment]
> We need to set RealmConfiguration instance to null when app is closed to prevent the leak

What leak? RealmConfiguration doesn't hold reference to Context, AFAIK. 

Definitely not since 2.0

**Comment by anggrayudi** [comment]
I did that because I set `RealmConfiguration`'s modifier to `public static`, so that it can be accessed anywhere. But I read a stackoverflow post which tells me that setting an instance's modifier to `public static` without `final` keyword might causes memory leak.

**Comment by beeender** [comment]
> But I read a stackoverflow post which tells me that setting an instance's modifier to public static without final keyword might causes memory leak.

that might not be true in some cases.

But why don't you set the `RealmConfiguration` with `public final static` since i don't think you need to change it during the life cycle of the app.

**Comment by cmelchior** [comment]
A RealmConfiguration is immutable anyway, so having it in a `public static final RealmConfiguration CONFIGURATION` field should be perfectly safe anyway.

**Comment by Zhuinden** [comment]
> setting an instance's modifier to public static without final keyword might causes memory leak.

That's only true if the thing you're setting as static has a reference to a Context (not app context)/View/etc.

**Comment by beeender** [comment]
We are not going to add API `Realm.getInstance(String key)`. But thanks a lot for your feedback!

**Comment by Zhuinden** [comment]
Indeed, storing your own `Map<String, RealmConfiguration>` would basically do the same thing.
