### ISSUE TITLE
The library need to decrease in size

### ISSUE THREAD

**Issue by jrcacd** [realm/realm-java#5596]

**Comment by Zhuinden** [comment]
Abi splits?

**Comment by cmelchior** [comment]
Yes or abiFilters. Read https://realm.io/docs/java/latest/#faq-library-size for more info.

**Comment by Zhuinden** [comment]
Also, MIPS will be removed later so that'll also reduce a bit of size 🙂

**Comment by jrcacd** [comment]
Ok, Thanks
