### ISSUE TITLE
Project no longer building after upgrade to 4.3.0

### ISSUE THREAD

**Issue by ecramer** [realm/realm-java#5598]
#### Goal

My application can no longer build after updating to 4.3.0. My project had no issue building with 4.2.0. My application uses `compile 'com.android.support:multidex:1.0.2'`

#### Actual Results

```java

Error:java.lang.RuntimeException: com.android.builder.dexing.DexArchiveMergerException: Error while merging dex archives

```
#### Steps & Code to Reproduce

My build.gradle does not have jack enabled but I tried enabling jackOptions and it did not help. I do not have any ideas on what else to try, it is literally the difference between using 4.2.0 and 4.3.0 of Realm.

#### Version of Realm and tooling
Realm version(s): 4.3.0

Realm sync feature enabled: no

Android Studio version: Android Studio 3.0.0 with gradle 3.0.1

Which Android version and device: N/A

**Comment by Zhuinden** [comment]
Have you tried **4.3.1**

Also, don't enable `jackOptions`, not only does it not support javassist, it's also deprecated since March...

**Comment by ecramer** [comment]
Yes it would appear 4.3.1 works. Thanks
