### ISSUE TITLE
AbstractMethodError : getExpectedObjectSchemaInfoMap()

### ISSUE THREAD

**Issue by mhdtouban** [realm/realm-java#5605]
Goal
To use latest realm version with kotlin

Expected Results
smooth integration 

Actual Results
java.lang.IllegalStateException: Fatal Exception thrown on Scheduler.
12-08 22:44:46.862 4705-4705/org.who.measures W/System.err:     at io.reactivex.android.schedulers.HandlerScheduler$ScheduledRunnable.run(HandlerScheduler.java:111)
12-08 22:44:46.862 4705-4705/org.who.measures W/System.err:     at android.os.Handler.handleCallback(Handler.java:790)
12-08 22:44:46.862 4705-4705/org.who.measures W/System.err:     at android.os.Handler.dispatchMessage(Handler.java:99)
12-08 22:44:46.862 4705-4705/org.who.measures W/System.err:     at android.os.Looper.loop(Looper.java:164)
12-08 22:44:46.862 4705-4705/org.who.measures W/System.err:     at android.app.ActivityThread.main(ActivityThread.java:6494)
12-08 22:44:46.862 4705-4705/org.who.measures W/System.err:     at java.lang.reflect.Method.invoke(Native Method)
12-08 22:44:46.863 4705-4705/org.who.measures W/System.err:     at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:438)
12-08 22:44:46.863 4705-4705/org.who.measures W/System.err:     at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:807)
12-08 22:44:46.863 4705-4705/org.who.measures W/System.err: Caused by: java.lang.AbstractMethodError: abstract method "java.util.Map io.realm.internal.RealmProxyMediator.getExpectedObjectSchemaInfoMap()"
12-08 22:44:46.863 4705-4705/org.who.measures W/System.err:     at io.realm.internal.modules.CompositeMediator.getExpectedObjectSchemaInfoMap(CompositeMediator.java:68)
12-08 22:44:46.864 4705-4705/org.who.measures W/System.err:     at io.realm.Realm.createExpectedSchemaInfo(Realm.java:182)
12-08 22:44:46.864 4705-4705/org.who.measures W/System.err:     at io.realm.Realm.<init>(Realm.java:153)
12-08 22:44:46.864 4705-4705/org.who.measures W/System.err:     at io.realm.Realm.createInstance(Realm.java:424)
12-08 22:44:46.864 4705-4705/org.who.measures W/System.err:     at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:342)
12-08 22:44:46.864 4705-4705/org.who.measures W/System.err:     at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:282)
12-08 22:44:46.864 4705-4705/org.who.measures W/System.err:     at io.realm.Realm.getDefaultInstance(Realm.java:332)

Steps & Code to Reproduce

- add realm dependency version 4.3.1 
Code Sample

 Realm.getDefaultInstance()
by just trying to get a realm instance you will encounter the issue.

Version of Realm and tooling

Realm version(s): 4.3.1

Realm sync feature enabled: no

Android Studio version: 3.0.1

Which Android version and device: All devices

**Comment by Zhuinden** [comment]
Have you tried clean+rebuild?

This sounds like one of those things where you either clean+rebuild or you have an old version of Realm in your project as well from somewhere.

**Comment by mhdtouban** [comment]
yeah, I tried clean+build but that didn't work.

**Comment by Zhuinden** [comment]
You should check with `gradlew :app:dependencies` to see if you are bringing in Realm from anywhere else.

Another thing you can do is `Invalidate Caches / Restart` in AS

**Comment by beeender** [comment]
What was the realm version before?

**Comment by mhdtouban** [comment]
This was solved by upgrading the other modules realm versions to 4.3.1.
