### ISSUE TITLE
Save and Delete Object in realm Database

### ISSUE THREAD

**Issue by fahadazizahmed** [realm/realm-java#5608]
I store the location latitude and longitude when internet is off and then send to server when internet on again. I store the location object successfully when internet off, now the problem is when internet on how i get the single object from realm database and send to server and delete this object at the same time when it send to server.

**Comment by beeender** [comment]
what do you mean by "server" here? Do you mean the Realm Object Server?

**Comment by Zhuinden** [comment]
When the network call succeeds, run a Realm transaction that deletes the item from the Realm
