### ISSUE TITLE
OrderedRealmCollectionChangeListener receives multiple notifications of insertions when inserting only one record

### ISSUE THREAD

**Issue by jrcacd** [realm/realm-java#5616]
We do a search for all results that meet a condition and ask for only unique results (distinctValues).

We added a changeListener in the RealmResults.

When we add a single record on another activity an return to the previews one, we often receive 2 or more records to add in the OrderedRealmCollectionChangeListener.

Realm version: 4.3.1

**Comment by beeender** [comment]
It is hard to tell what is going wrong based on your description. Would you please make a sample project to show the issue?
thanks.
