### ISSUE TITLE
Partial Sync: Unify Notification System

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#5619]
See https://github.com/realm/product/issues/392 for details.

Note that this introduce a small breaking change to the Java API's as `OrderedChangeSet` will no longer be `@Nullable` in callbacks.

**Comment by nhachicha** [comment]
is this the only breaking change? how about `getState()` and `getError()` will you create an issue to track them in `OrderedCollectionChangeSet` ?

**Comment by cmelchior** [comment]
We don't make it possible for people to create their own subclasses of OrderedCollectionChangeSet, so while technically yes, it is a breaking change to add these methods, it shouldn't impact anyone.

This issue is supposed to track all that is required to make it work. Most of it is already implemented in #5611 though.

**Comment by Zhuinden** [comment]
Realm-android-adapters will also need an update then.

**Comment by Zhuinden** [comment]
Why wasn't this closed by https://github.com/realm/realm-java/pull/5611 ?
