### ISSUE TITLE
:app:compileDebugJavaWithJavac || Compilation failed; see the compiler error output for details.

### ISSUE THREAD

**Issue by gwanjar** [realm/realm-java#5622]
:app:compileDebugJavaWithJavac
:app:compileDebugJavaWithJavac - is not incremental (e.g. outputs have changed, no previous execution, etc.).
D:\React\awesome\android\app\src\main\java\com\awesome\MainApplication.java:19: error: cannot find symbol
      return BuildConfig.DEBUG;
             ^
  symbol: variable BuildConfig
1 error
:app:compileDebugJavaWithJavac FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:compileDebugJavaWithJavac'.
> Compilation failed; see the compiler error output for details.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 16.397 secs
Could not install the app on the device, read the error above for details.
Make sure you have an Android emulator running or a device connected and have
set up your Android development environment:
https://facebook.github.io/react-native/docs/android-setup.html

**Comment by gwanjar** [comment]
please help, why java not compile? thanks before

**Comment by Zhuinden** [comment]
If you're using React Native, then this question most likely belongs to Realm-js issues, because they use a different core and all that.

**Comment by nhachicha** [comment]
Please re-open the issue on https://github.com/realm/realm-js 
it would be helpful if you can include your project as well
