### ISSUE TITLE
Strange Issue in debug Mode

### ISSUE THREAD

**Issue by Rajeshr34** [realm/realm-java#5624]
Every things works normal but until 2nd time debug runs all data get erase

1st Debug Mode works file.
2nd attempt debug mode realm returns null  app crashes

i had to uninstall every time while working on that.

but in production works fine.

Note: disabled instant run

**Comment by nhachicha** [comment]
Hi, can you please describe how you're using Realm (configuration, etc) or share the code so we can have an idea of what's going wrong?

**Comment by Rajeshr34** [comment]
```
    compileSdkVersion 27
    buildToolsVersion "27.0.2"
```

Fixed My Issue.
