### ISSUE TITLE
Gradle sync error when update 4.2.0 to 4.3.1

### ISSUE THREAD

**Issue by hendrawd** [realm/realm-java#5625]
**Bugs**: I want to update Realm database from version 4.2.0 to 4.3.1, but after gradle sync, it will fail

#### Goal
Update Realm from 4.2.0 to 4.3.1

#### Expected Results
Gradle sync will success

#### Actual Results
Gradle sync failed with stacktrace:
```
FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':app:processDebugResources'.
> Could not get unknown property 'packageForR' for task ':app:processDebugResources' of type com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask.

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

* Get more help at https://help.gradle.org

BUILD FAILED in 36s
```

#### Steps & Code to Reproduce
- Change `classpath "io.realm:realm-gradle-plugin:4.2.0"` from project-level build.gradle to `classpath "io.realm:realm-gradle-plugin:4.3.1"`
- Sync gradle

#### Code Sample
Not related to code

#### Version of Realm and tooling
Realm version(s): 4.3.1

Realm sync feature enabled: no

Android Studio version: 3.0.1

Which Android version and device: not related to android version and device

**Comment by Zhuinden** [comment]
What version of android build tools are you using? It's in the project level classpath plugins just like Realm.

**Comment by hendrawd** [comment]
The newest one, classpath 'com.android.tools.build:gradle:3.0.1'

**Comment by nhachicha** [comment]
can you build from the command line (outside Android Studio)? 
stop any gradle daemon `./gradlew --stop` then do a clean build, also it's preferable to include `--stacktrace` option to gradle

Can you post your build configuration?

**Comment by sunrisemoment** [comment]
Here is same issue with realm 4.3.1 version.
Gradle version is 3.0.1 and buildToolsVersion is 27.0.2

**Comment by hendrawd** [comment]
@nhachicha here are my build configurations:

```
    compileSdkVersion = 26
    buildToolsVersion = "26.0.2"
    supportLibVersion = "26.1.0"
    minSdkVersion = 16
    targetSdkVersion = 25
```

**Comment by hendrawd** [comment]
Looks like it's not Realm fault, but my fault.
It might be because of my wrong build.gradle configuration. I can update realm after i change all the annotation processor to kapt since i use kotlin now, especially `kapt "com.android.databinding:compiler:$gradle_version"`, then invalidate caches and restart

**Comment by iman2420** [comment]
@hendrawd I did it but my problem was not solved! What other solution do you have?

**Comment by hendrawd** [comment]
@iman2420 Sorry, I don't.

**Comment by Zhuinden** [comment]
Use Realm 4.3.2+
