### ISSUE TITLE
Method can generate java.lang.NullPointerException

### ISSUE THREAD

**Issue by jonathansilva** [realm/realm-java#5627]
Should I ignore?
With or without @Nullable, I have these notifications

![0](https://user-images.githubusercontent.com/33843748/34080301-d03efe12-e322-11e7-99fd-651478df1a85.png)

or

![1](https://user-images.githubusercontent.com/33843748/34080302-d500f25c-e322-11e7-8b10-4f8343f3b69e.png)

#### Version of Realm and tooling
Realm version(s): 4.3.1

Realm sync feature enabled: yes

Android Studio version: 3.0.1

Which Android version and device: 5.0.1

**Comment by MGaetan89** [comment]
You should annotate the parameter with `@NotNull` (or whichever annotation you are using).
