### ISSUE TITLE
Crash: property 'x' has been made unindexed

### ISSUE THREAD

**Issue by tamtom** [realm/realm-java#5628]
Goal

I want to  fix & reproduce the following crash,  we have recently updated the realm version from 3.3.1 to
4.2.0 and everything goes fine after the release we had this crash on Fabric that we couldn't reproduce  

App crashes after I call Realm.getInstance for the first time with the exception:
Crash log
```
Fatal Exception: io.realm.exceptions.RealmMigrationNeededException: Migration is required due to the following errors:
- Property 'RealmMessage.messageId' has been made unindexed.
       at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(OsSharedRealm.java)
       at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:172)
       at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:219)
       at io.realm.a.<init>(BaseRealm.java:124)
       at io.realm.a.<init>(BaseRealm.java:93)
       at io.realm.x.<init>(Realm.java:153)
       at io.realm.x.a(Realm.java:424)
       at io.realm.aq.b(RealmCache.java:342)
       at io.realm.aq.a(RealmCache.java:282)
       at io.realm.x.b(Realm.java:353)
     
```

**Code Sample**
```

 private long messageId;
    @PrimaryKey
    private long localMessageId;
    private RealmRoom room;
    private RealmPost post;
    private RealmUser otherUser;
    private int status;
    private int localStatus;
    private String mediaURL;
    private String mediaURI;
    private String videoThumbnail;
    private long mediaSize;
    private boolean isMine;
    @Index
    private boolean isRead;
    private String text;
```

and no changes happened to this class only one change before 1 year 
that was the `messageId` is the PrimaryKey 
I tried to install the version that we did that and upgrade it to the latest build no crash happened 
and here is the old code of migration  

```

        schema.get(RealmMessage.class.getSimpleName())//Chat Messages
                .addField(RealmMessage.MEDIA_URL, String.class)
                .addField(RealmMessage.MEDIA_URI, String.class)
                .addField(RealmMessage.VIDEO_THUMBNAIL, String.class)
                .addField(RealmMessage.MEDIA_SIZE, long.class)
                .addField(RealmMessage.NUMBER_OF_RETRIES, int.class)
                .addField(RealmMessage.LOCAL_STATUS, int.class)
                .addField(RealmMessage.LOCAL_MESSAGE_ID, long.class)
                .transform(obj -> obj.setLong(RealmMessage.LOCAL_MESSAGE_ID,
                        obj.getLong(RealmMessage.MESSAGE_ID)))
                .removePrimaryKey()
                .addPrimaryKey(RealmMessage.LOCAL_MESSAGE_ID);
```
I've checked this issue but nothing could help me #5237 
#### Version of Realm and tooling 
Realm version(s): 4.2.0

Realm sync feature enabled: no

Android Studio version: 3.0.0

Which Android version and device: Samsung Galaxy Grand Neo Plus, Galaxy S5

**Comment by Zhuinden** [comment]
That's because previously the Realm-Java schema validation  didn't properly check for index mismatch. Now that in I think 3.7.1+ the object store schema integration is complete, there is better validation and better messages.

So I guess the field was made unindexed!

**Comment by tamtom** [comment]
@Zhuinden I've checked the all git changes on this field it was never index, how to solve this problem?

**Comment by Zhuinden** [comment]
Primary keys are indexed by default since around 0.82.0, so if the messageId used to be a primary key, then it was also indexed. So you can add @Index on it and it should still work

**Comment by tamtom** [comment]
@Zhuinden so the solution to avoid the crash is just to add the **@index**  on it? no migration code needed?

**Comment by Zhuinden** [comment]
I think that would solve it, yes

**Comment by beeender** [comment]
Same issue with https://github.com/realm/realm-java/issues/5237
