### ISSUE TITLE
Stale data (Race condition ?) when using Realm with Rx Java `concatMap` and Retrofit

### ISSUE THREAD

**Issue by nkanellopoulos** [realm/realm-java#5631]
#### Goal

I want to use Rx Java's `concatMap` operator to control the order of network requests.
I update some objects in step_1 and reload them in step_2.

#### Expected Results

Unless I am wrong, accessing objects from (potentially) another thread requires just a new query.
I do not get any exception, BUT I get back stale data.

#### Actual Results

I get back **stale data**.
This means, the field I updated in step1 still has the **old value** when I read it in step2.

Unless I add this code: 

    Thread.sleep(300)
    realm.refresh()

Of course this `Thread.sleep(XXX)` is a huge issue for me.

Here is a sample run:
```
17:25:18.714 .fieldobservations E/Rx: doOnSubscribe
17:25:18.728 .fieldobservations E/Rx: [RxCachedThreadScheduler-1]  concatMap: 1: Send Traps
17:25:18.730 .fieldobservations E/Rx: [RxCachedThreadScheduler-1] syncPendingTraps(): Enter
17:25:18.744 .fieldobservations E/Rx: [RxCachedThreadScheduler-1] Enter postTrapsNew()
17:25:19.246 .fieldobservations E/Rx: [RxCachedThreadScheduler-2]  concatMap: 2: Send Arrests
17:25:19.246 .fieldobservations E/Rx: [RxCachedThreadScheduler-2] syncPendingArrests(): Enter
17:25:19.251 .fieldobservations E/Rx: [RxCachedThreadScheduler-3] onNext: PostResult
17:25:19.258 .fieldobservations E/Rx:   onNext details: Trap
17:25:19.258 .fieldobservations E/Rx: [RxCachedThreadScheduler-3] postTrapsHelper(): Enter
17:25:19.276 .fieldobservations E/Rx: [RxCachedThreadScheduler-3] postTrapHelper(): arrests that hold a ref to Trap with id -1: 1
17:25:19.331 .fieldobservations E/Realm: Updated primary key for object of Trap: from -1 to 544
17:25:19.333 .fieldobservations E/Rx: [RxCachedThreadScheduler-3] postTrapHelper(): arrests that hold a ref to Trap with id -1 (after PK update): 1
17:25:19.333 .fieldobservations E/Sync: [RxCachedThreadScheduler-3] postTrapHelper(): Updated id of Arrest FK: -1 -> 544
17:25:19.365 .fieldobservations E/Rx: [RxCachedThreadScheduler-3] postTrapHelper(): trap id of the 1st arrest (after PK update): 544
17:25:19.415 .fieldobservations E/Rx: [RxCachedThreadScheduler-2] syncPendingArrests(), id: -1, trap.id: -1, trap.name: b 17:22
17:25:19.582 .fieldobservations E/Rx: onError: HTTP 422 Unprocessable Entity
```

As you can see, in the next to last line, `trap.id` is still -1 instead of 544

#### Steps & Code to Reproduce

In my log I can see that things run in the expected order, and that my updates do take place.

#### Code Sample

```kotlin

// This is a simplified version of my code.
// I get back data from the network in `step_1`, 
// update my Realm objects, 
// and load them again at `step_2`

data class SyncStep(val stepNumber: String, val name: String,
                    val obs: () -> Observable<*>)

data class PostResult (val oldID : Long, val newID : Long, val typeOfResult: KClass<*>? = null)

// see below for the definition of syncPendingArrests
val step2 = SyncStep("2", "Send Arrests", { syncPendingArrests(messages) })

// List of 'SyncStep'
val stepsList = listOf(step1, step2, step3 /*, ... */ )

val stepsObservable : Observable<SyncStep> = Observable.fromIterable(stepsList)


stepsObservable
                .concatMap { elem: SyncStep ->
                    Log.e("Rx", "$threadName  concatMap: ${elem.stepNumber}: ${elem.name}")

                    updateProgress(elem.name)
                    return@concatMap elem.obs()
                }
                .subscribeOn(Schedulers.io())
                .observeOn(Schedulers.io())
                .subscribeBy(
                        onNext = { item ->
                        })



    private fun syncPendingArrests(messages: MutableList<String>) : Observable<PostResult> {
        Log.e("Rx", "$threadName syncPendingArrests(): Enter")
        val realm = Realm.getDefaultInstance()


        // ΝΟΤΕ: Waiting before calling realm.refresh() seems necessary :(
        Thread.sleep(250)
        realm.refresh()

        val pendingArrests = realm.where(Arrest::class.java)
                .equalTo("submitted", false)
                .findAll()
                .sort("id", Sort.DESCENDING)
                .toList()


        if (pendingArrests.count() == 0) {
            messages.add("Nothing to send.")
        }


        //detach from Realm, copy values to fields
        val detached = realm.copyFromRealm(pendingArrests)  //pendingArrests.map { managed -> realm.copyFromRealm(managed) }
        
        
        for (item: Arrest in detached) {
            Log.e("Rx", "$threadName syncPendingArrests(), id: ${item.id}, trap.id: ${item.trap?.id}, trap.name: ${item.trap?.name}")
        }

        
        realm.close()
        return arrestManager.postObservationNew(detached)
    }
```

#### Version of Realm and tooling
Realm version(s): 4.3.1

Realm sync feature enabled: no

Android Studio version: 3.0.1

Which Android version and device: Samsung S7 running android 6.0.1, Nexus 4 running android 5.1

**Comment by Zhuinden** [comment]
Refresh immediately refreshes Realm to the latest version, so if you need to add a delay before that, that means your transaction is not yet committed at that time, AFAIK.

**Comment by nkanellopoulos** [comment]
@Zhuinden any idea how I could work around this issue? Using a Thread.sleep() is guaranteed to break. Just use a slow-enough device. The idea was to use Rx to deal with concurrency. But although `concatMap` triggers the network requests in order, the responses can still come in a different order, causing issues with Realm.

**Comment by Zhuinden** [comment]
You can begin and cancel a transaction manually. That way if there is an ongoing transaction, it'll block, and still refresh the Realm if it's already done.

**Comment by nkanellopoulos** [comment]
Starting a new transaction wouldn't throw an exception? Am I missing something?

**Comment by Zhuinden** [comment]
Why would it throw? Transactions only throw if a transaction is already in progress.

**Comment by nkanellopoulos** [comment]
The issue was that although Rx triggered actions in the proper order, a Realm transaction could still be running when a new net request should fire. Thus, querying Realm would return data that seemed "stale". But technically they were not. 

This is not a Realm bug. 
Just a sad fact of life :)

**Comment by Zhuinden** [comment]
That's why I always recommend running the query *inside* the transaction if you're on a background thread :smile:

**Comment by nkanellopoulos** [comment]
@Zhuinden Unfortunately, I do not control the thread pool of Rx 🙃
HOWEVER, if I ask my Realm instance  if a transaction is in progress, this should return true even the Transaction was started from another thread, right?

**Comment by Zhuinden** [comment]
>  this should return true even if the Transaction was started from another thread, right?

I don't think so.

``` c++
bool Realm::is_in_transaction() const noexcept
{
    if (!m_shared_group) {
        return false;
    }
    return m_shared_group->get_transact_stage() == SharedGroup::transact_Writing;
}
```

`shared_group` is specific to a `shared_realm`, and `shared_realm` is thread-specific.

**Comment by nkanellopoulos** [comment]
This means, we can do nothing to check whether a transaction is in progress in some other thread?
I think there is room for improvement here.
