### ISSUE TITLE
Assertion failed: ref + size <= after_ref with (ref, size, after_ref, ndx, m_free_positions.size()) = [0, 8, 0, 0, 4]

### ISSUE THREAD

**Issue by eddienuel** [realm/realm-java#5632]
#### Goal

> What do you want to achieve?
Initialize an existing realm db in android
#### Expected Results

> Successfully initilize an existing realm Database to perform CRUD
#### Actual Results
App crashes though the device had complained of low disk space and the database file had already grown up to 330MB. The realm version was 3.0.0. After reading similar raised issue, it was confirmed that version 4.0.0-RC1 fixed it. But i still get the error after upgrading to version 4.0.0-RC1. Could this be an issue with disk space of the device with realm? and how can i recover the data from the db?, because it appears the database is corrupt. When i tried to open the database file with the new REALM STUDIO i get no schema found. here is the stack trace
>  E.g. full stack trace with exception
E/REALM: /home/jenkins.1/workspace/lm_realm-core_release_4.0.1-H662K7IA6U2B7ZK6DBECBDZYPHHQYXQ5UYSL7U2WUDUM5MVJKVQA/src/realm/group_writer.cpp:392: [realm-core-4.0.1] Assertion failed: ref + size <= after_ref with (ref, size, after_ref, ndx, m_free_positions.size()) =  [0, 8, 0, 0, 4]
                                                              IMPORTANT: if you see this error, please send this log to help@realm.io.
12-14 14:15:27.612 7820-7861/com.seamfix.bioregistra A/libc: Fatal signal 6 (SIGABRT) at 0x00001e8c (code=-6), thread 7861 (Thread-3935)

#### Version of Realm and tooling
Realm version(s): ?
3.0.0
Realm sync feature enabled: yes/no
no
Android Studio version: ?
2.3.3
Which Android version and device: ?
4.4.2

**Comment by cmelchior** [comment]
Unfortunately, once the file was hit by this, upgrading to the latesdt version cannot fix it. Just prevent it from happening again. Could this be the case? That the file was already damaged?

**Comment by eddienuel** [comment]
Thanks for your response. 

I'm not sure if the file was already damaged. I tried to open the file with REALM STUDIO 1.12.0 but I get a "no schema found" error message. Does this mean the Database is corrupt? If yes, is there a way we can recover the data in the Realm Database file? We desperately need to recover the data in the file. We are also willing to share the database file for further analysis if that would help.

Finally, please whats the best possible way to prevent this from happening again? As it seems realm does not warn low disk space.

**Comment by cmelchior** [comment]
@eddienuel Sorry for the late reply. As it seems this issue has moved to email. I'll close it here.

But in general Realm will crash with an error message if it runs out of disk space.
