### ISSUE TITLE
application publish a new version  with add some attribute in realm ,this is something information show me: the "field" is missing from the schema for this realm

### ISSUE THREAD

**Issue by lxww14** [realm/realm-java#5633]
#### Goal

> What do you want to achieve?

#### Expected Results

> ?

#### Actual Results

>  E.g. full stack trace with exception

#### Steps & Code to Reproduce

> Describe your current debugging efforts.

#### Code Sample

```java

> Your code here. Bigger samples should ideally be as separate Android Studio project, 
> in gists/repositories or privately at help@realm.io)

```

#### Version of Realm and tooling
Realm version(s): ?

Realm sync feature enabled: yes/no

Android Studio version: ?

Which Android version and device: ?

**Comment by lxww14** [comment]
application publish a new version  with add some attribute in realm ,this is something information show me: the "field" is missing from the schema for this realm

**Comment by Zhuinden** [comment]
That means you didn't add a migration that would add the field to the schema.

**Comment by beeender** [comment]
See https://realm.io/docs/java/latest/#migrations
