### ISSUE TITLE
Realm objects can only be accessed on the thread they were created

### ISSUE THREAD

**Issue by hmedat2008** [realm/realm-java#5635]
I'm using this method **copyFromRealm** to copy the realm result, i do it one time, then i make it singleton  
<img width="632" alt="screen shot 2017-12-20 at 4 01 36 pm" src="https://user-images.githubusercontent.com/4534097/34210614-2e95852a-e59f-11e7-8cbd-01e09a0d45a1.png">

And as I read from doc 
<img width="831" alt="screen shot 2017-12-20 at 4 04 38 pm" src="https://user-images.githubusercontent.com/4534097/34210714-8769175c-e59f-11e7-8c3f-d73dac68ade6.png">

Why i got this error: 
<img width="1027" alt="screen shot 2017-12-20 at 4 06 30 pm" src="https://user-images.githubusercontent.com/4534097/34210804-c9986c68-e59f-11e7-8265-5d7b680d6749.png">

**I except i can access the copied result in whatever thread**

Version of Realm and tooling
Realm version(s): 4.2.0

Realm sync feature enabled: no

Android Studio version: 3.0.1

Which Android version and device: 
<img width="1143" alt="screen shot 2017-12-20 at 4 05 29 pm" src="https://user-images.githubusercontent.com/4534097/34210754-a56ff932-e59f-11e7-96ac-4174384ece25.png">

**Comment by Zhuinden** [comment]
Because you update the clsss's field and it will never be null so you never actually copy it out.

**Comment by hmedat2008** [comment]
Sorry I don't get you

**Comment by Zhuinden** [comment]
You update the field `mRmRootConfig` with `findFirst`.

This is not null because it exists in Realm. 

So `if!=null` is false, and you never do `copyFromRealm`.

**Comment by hmedat2008** [comment]
**So if!=null is true** isn't false baby

**Comment by hmedat2008** [comment]
I have solved it, I forgot to set **synchronized** to get root config method. 

Sorry, it's a bad mistake.

**Comment by Zhuinden** [comment]
... Whoops... Vacation made me code blind. Anyways ad you've solved it
