### ISSUE TITLE
no support ..

### ISSUE THREAD

**Issue by ruanbaojun1105** [realm/realm-java#5637]
#### Goal

> What do you want to achieve?

#### Expected Results

>

#  public class ShopCache extends RealmObject {
    @PrimaryKey
    private String listTag;
    private RealmList<RealmObject> realmObjectList;
    private long # creatDate;
}

#### Actual Results

>  E.g. full stack trace with exception

#### Steps & Code to Reproduce

> Describe your current debugging efforts.

#### Code Sample

```java

> Your code here. Bigger samples should ideally be as separate Android Studio project, 
> in gists/repositories or privately at help@realm.io)

```

#### Version of Realm and tooling
Realm version(s): 3.1.1

Realm sync feature enabled: yes/no

Android Studio version: no

Which Android version and device: ?

**Comment by Zhuinden** [comment]
> private RealmList<RealmObject> realmObjectList;

Needs to be specific RealmObject classes.

**Comment by ruanbaojun1105** [comment]
so bad~~~

**Comment by Zhuinden** [comment]
@ruanbaojun1105 actually now that you mention it, it could be `RealmList<String>` too to store primary keys, but then you need to also keep track of what type it belongs to, possibly also with some string identifier (because you can't just directly store `Class`)

But it could work

**Comment by ruanbaojun1105** [comment]
@Zhuinden so bad!!!!!-------RealmList<RealmObject> ---->All my production classes are extends  RealmObject ，So why can't it?mengbi!

**Comment by Zhuinden** [comment]
Because links are type-specific, so you can't just do `RealmList<RealmObject>`.

**Comment by beeender** [comment]
@ruanbaojun1105 See https://realm.io/docs/java/latest#relationships which might be helpful.
