### ISSUE TITLE
Why all gradle plugin is build on alpha android plugin?

### ISSUE THREAD

**Issue by WeJoy** [realm/realm-java#5640]
It will cause the test only apk problem of android studio

see this: [https://stackoverflow.com/questions/14643564/android-error-install-failed-test-only](https://stackoverflow.com/questions/14643564/android-error-install-failed-test-only)

**Comment by WeJoy** [comment]
Err, never mind, 4.2.0 is good.

**Comment by cmelchior** [comment]
Ugh. This is a bug. We should not dictate the version of Build tools for users. We should only list the build tools as a `provided` dependency or as a minimum only depend on the lowest one we support (which I believe is 1.5).

Realm 4.2.0 depends on `2.1`: https://bintray.com/realm/maven/realm-gradle-plugin/4.2.0#files/io%2Frealm%2Frealm-gradle-plugin%2F4.2.0

Realm 4.3.0 depends on `3.1.0-alpha03`: https://bintray.com/realm/maven/realm-gradle-plugin/4.3.0#files/io%2Frealm%2Frealm-gradle-plugin%2F4.3.0

**Comment by paulpv** [comment]
I am compiling w/:
classpath  'com.android.tools.build:gradle:3.0.1'
classpath 'io.realm:realm-gradle-plugin:4.3.1'

The build fails with "Could not get unknown property 'manifestFile' for task ':lib:generateDebugRFile' of type com.android.build.gradle.internal.res.GenerateLibraryRFileTask'"

If I drop back to classpath 'io.realm:realm-gradle-plugin:4.2.0' the build is successful.

**Comment by paulpv** [comment]
I tried with classpath 'com.android.tools.build:gradle:3.1.0-alpha06' and realm 4.3.1 and get the same build failure error message.

**Comment by Zhuinden** [comment]
You could try

```
dependencies {
    classpath('io.realm:realm-gradle-plugin:4.3.1') {
        exclude group: 'com.android.tools.build', module: 'gradle'
    }
}
```

**Comment by paulpv** [comment]
That seems to have worked and done the trick!

**Comment by nhachicha** [comment]
Hi  can you please try the [4.3.2-SNAPSHOT](https://github.com/realm/realm-java#using-snapshots) this should include a fix

**Comment by Zhuinden** [comment]
This should be fixed by 4.3.2 released today

**Comment by Zhuinden** [comment]
@cmelchior I'm pretty sure this is fixed in 4.3.2+

**Comment by cmelchior** [comment]
yes, this has been fixed

**Comment by yayaa** [comment]
Hey @Zhuinden could you please point me to the commit that fixes the issue?

**Comment by Zhuinden** [comment]
@yayaa https://github.com/realm/realm-java/commit/1ae964239fd7deb8329c1a07e01f80c273af2c97
