### ISSUE TITLE
Save bundle to realm

### ISSUE THREAD

**Issue by abdullo211** [realm/realm-java#5644]
Is there any way to save object with the bundle?

**Comment by Zhuinden** [comment]
Bundles are dynamically typed and Android-specific, so you'd have to make it into some more concrete type (maybe even just `byte[]`) instead of Bundle

**Comment by zaheerahmad** [comment]
If it is about Android, then I have saved a RealmObject in a bundle. Follow the steps:

1. Implement 'Parcelable' interface in your model class (Even if it is extending 'RealmObject')
2. Now do it in following way

> Bundle bundle = new Bundle();
> bundle.putParcelable(KEY_USER, user);
> ActivityUtils.launchActivity(getBaseActivity(), MainActivity.class, true, bundle);

And here is my user

> public class User extends RealmObject implements Parcelable {
> 
>     public User() {
>     }
> 
>     protected User(Parcel in) {
>         id = in.readString();
>         firstName = in.readString();
>         lastName = in.readString();
>         email = in.readString();
>         password = in.readString();
>         phoneNumber = in.readString();
>         userType = in.readString();
>     }
> 
>     public static final Creator<User> CREATOR = new Creator<User>() {
>         @Override
>         public User createFromParcel(Parcel in) {
>             return new User(in);
>         }
> 
>         @Override
>         public User[] newArray(int size) {
>             return new User[size];
>         }
>     };
> 
>     @Override
>     public int describeContents() {
>         return 0;
>     }
> 
>     @Override
>     public void writeToParcel(Parcel parcel, int i) {
>         parcel.writeString(id);
>         parcel.writeString(firstName);
>         parcel.writeString(lastName);
>         parcel.writeString(email);
>         parcel.writeString(password);
>         parcel.writeString(phoneNumber);
>         parcel.writeString(userType);
>     }
> 
>     public enum UserType {
>         Broker, Agent, Dealer, Private
>     }
> 
>     @PrimaryKey
>     private String id;
> 
>     @SerializedName("FirstName")
>     private String firstName;
> 
>     @SerializedName("LastName")
>     private String lastName;
> 
>     @SerializedName("Email")
>     private String email;
> 
>     @SerializedName("Password")
>     private String password;
> 
>     @SerializedName("PhoneNumber")
>     private String phoneNumber;
> 
>     @SerializedName("UserType")
>     private String userType;
> 
>     public String getFirstName() {
>         return firstName;
>     }
> 
>     public void setFirstName(String firstName) {
>         this.firstName = firstName;
>     }
> 
>     public String getLastName() {
>         return lastName;
>     }
> 
>     public void setLastName(String lastName) {
>         this.lastName = lastName;
>     }
> 
>     public String getEmail() {
>         return email;
>     }
> 
>     public void setEmail(String email) {
>         this.email = email;
>     }
> 
>     public String getPassword() {
>         return password;
>     }
> 
>     public void setPassword(String password) {
>         this.password = password;
>     }
> 
>     public String getPhoneNumber() {
>         return phoneNumber;
>     }
> 
>     public void setPhoneNumber(String phoneNumber) {
>         this.phoneNumber = phoneNumber;
>     }
> 
>     public String getUserType() {
>         return userType;
>     }
> 
>     public void setUserType(String userType) {
>         this.userType = userType;
>     }
> 
>     public String getId() {
>         return id;
>     }
> 
>     public void setId(String id) {
>         this.id = id;
>     }
> }

Please let me know if it helps.

**Comment by abdullo211** [comment]
Thanx for answer!
