### ISSUE TITLE
Object Server migration required after sync failed.

### ISSUE THREAD

**Issue by SiarheiSm** [realm/realm-java#5647]
Hi,
I have an issue on ROS-Android sync. it hard to reproduce but i got it few times.
i have few(1-3) schema that i need to sync, and do sync in queue (waiting for first completed than starts second) 
each schema contains 3-5 tables, each table 3-7 columns and 10-500 rows 
The issue appears in case user is new (he is just install the application), than app connects to the ROS and try to sync data, but in case app got time-out exception (by some reason) there is a chance that schema will be "corrupted". And in this case on next try to sync data i got "migration needed" exception. 
but as i understand there is no chance to do delete-On-Migration-Needed for SyncUser.
How can i handle this? 
Thank you

#### Version of Realm and tooling
Realm version(s): 4.3.1

Realm sync feature enabled: yes

Android Studio version: 3.0.1

Which Android version and device: 7.1.0, google pixel xl

**Comment by beeender** [comment]
what is the full backtrace and the exception message of the "migration needed" exception?

**Comment by SiarheiSm** [comment]
haven't save trace :( will share it when faced issue again
