### ISSUE TITLE
"Failed to notify project evaluation listener" when upgrading to 4.3.+

### ISSUE THREAD

**Issue by flocsy** [realm/realm-java#5650]
#### Goal

> Upgrade classpath "io.realm:realm-gradle-plugin:4.2.0" to classpath "io.realm:realm-gradle-plugin:4.3.1"

#### Expected Results

> successful build

#### Actual Results

>  $ ./gradlew app:dependencies
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring project ':chegg-sdk'.
> Failed to notify project evaluation listener.
   > com.android.build.gradle.tasks.ProcessAndroidResources.getOriginalApplicationId()Ljava/lang/String;

In AndroidStudio 3.0.1 When I try to do Gradle Sync I get this error:

"Error:Unable to find method 'com.android.build.gradle.tasks.ProcessAndroidResources.getOriginalApplicationId()Ljava/lang/String;'.
Possible causes for this unexpected error include:<ul><li>Gradle's dependency cache may be corrupt (this sometimes occurs after a network connection timeout.)
<a href="syncProject">Re-download dependencies and sync project (requires network)</a></li><li>The state of a Gradle build process (daemon) may be corrupt. Stopping all Gradle daemons may solve this problem.
<a href="stopGradleDaemons">Stop Gradle build processes (requires restart)</a></li><li>Your project may be using a third-party plugin which is not compatible with the other plugins in the project or the version of Gradle requested by the project.</li></ul>In the case of corrupt Gradle processes, you can also try closing the IDE and then killing all Java processes."

#### Steps & Code to Reproduce

Android Studio 3.0.1
Gradle 4.1
classpath 'com.android.tools.build:gradle:3.0.1'
classpath "io.realm:realm-gradle-plugin:4.3.1"

> Describe your current debugging efforts.

#### Code Sample

```java

> Your code here. Bigger samples should ideally be as separate Android Studio project, 
> in gists/repositories or privately at help@realm.io)

```

#### Version of Realm and tooling
Realm version(s): 4.3.1

Realm sync feature enabled: no

Android Studio version: 3.0.1

Which Android version and device: 
    buildToolsVersion = "27.0.3"
    compileSdkVersion = 26
    minSdkVersion = 16
    targetSdkVersion = 25
Device: Irrelevant, but: (Google) Pixel,  Android 8.0.0

**Comment by cmelchior** [comment]
This looks more like a build system failure than a Realm problem. Unfortunately fixing Gradle bugs can be rather annoying.

I would try:
---
./gradlew --stop
// Delete all cache files in your project. With git: `git -xfd clean` 
// Delete global cache dir. On Mac it is located in `~/.gradle/caches
```

**Comment by cmelchior** [comment]
I assume you resolved the issue, if not, feel free to reopen. Closing

**Comment by rmorrise** [comment]
I had an issue with a similar error message, but it turned out that I needed to upgrade my ```gradle-clover-plugin```.

**Comment by satty82** [comment]
Awesome man . You saved my day.

Actually What I used was : gradlew.clean

Thankyou so much
