### ISSUE TITLE
Android Studio 3.0.1, Realm integrated issue with DataBinding

### ISSUE THREAD

**Issue by uhha123** [realm/realm-java#5654]
I tried to build project demo that used data binding and realm, but my data binding had errors (for all Binding). When I removed Realm gradle plugin, it worked fine. Or was disable databind, realm will work.

When using compile "io.realm:realm-android-library:$realm", have not issue for building but when executing app, I got the error "`Temp` is not part of the schema for this Realm".

Gradle:
// Top-level build file where you can add configuration options common to all sub-projects/modules.

buildscript {
    ext.kotlin_version = '1.2.10'
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.0.1'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
        classpath "io.realm:realm-gradle-plugin:4.3.1"
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        maven {
            url 'https://github.com/uPhyca/stetho-realm/raw/master/maven-repo'
        }
    }
}

--App Gradle:
apply plugin: 'com.android.application'

apply plugin: 'kotlin-android'

apply plugin: 'kotlin-android-extensions'
apply plugin: 'realm-android'

android {
    compileSdkVersion 26
    defaultConfig {
        applicationId "com.sutrix.tca.testrealm"
        minSdkVersion 21
        targetSdkVersion 26
        versionCode 1
        versionName "1.0"
        testInstrumentationRunner "android.support.test.runner.AndroidJUnitRunner"
    }
    dataBinding {
        enabled = true
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: 'libs', include: ['*.jar'])
    implementation "org.jetbrains.kotlin:kotlin-stdlib-jre7:$kotlin_version"
    implementation 'com.android.support:appcompat-v7:26.1.0'
    implementation 'com.android.support.constraint:constraint-layout:1.0.2'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'com.android.support.test:runner:1.0.1'
    androidTestImplementation 'com.android.support.test.espresso:espresso-core:3.0.1'

    compile 'io.realm:android-adapters:1.3.0'

    compile 'com.uphyca:stetho_realm:2.0.0'

    //Stetho
    compile 'com.facebook.stetho:stetho:1.5.0'
}

Realm version(s): 4.3.1

Realm sync feature enabled: no

Android Studio version: 3.0.1

Which Android version and device: compileSdkVersion 26

**Comment by Zhuinden** [comment]
compile "io.realm:realm-android-library:$realm 

You should not have that, it won't work 

    apply plugin: 'com.android.application'

    apply plugin: 'kotlin-android'

    apply plugin: 'kotlin-android-extensions'
    apply plugin: 'realm-android'

You are missing `apply plugin: 'kotlin-kapt'` after `kotlin-android`

Also you are missing the databinding dependency from the gradle dependencies block. Specified with `kapt`.

**Comment by uhha123** [comment]
@Zhuinden, when I tried kapt "com.android.databinding:compiler:3.0.1", I got error: "Could not find accessor ..****\data bindind error"?

**Comment by Zhuinden** [comment]
I was basing the solution on https://stackoverflow.com/a/46429553/2413303

**Comment by uhha123** [comment]
@Zhuinden , it worked fine. But the new issue has showed. "No such property: syncEnabled for class:java.lang.String". Can you help me, pls?

**Comment by Zhuinden** [comment]
You can try https://github.com/realm/realm-java/issues/5640#issuecomment-355497076

**Comment by uhha123** [comment]
Thanks @Zhuinden so much, You saved my days.

**Comment by Zhuinden** [comment]
This issue will no longer occur after 4.3.2+

**Comment by nmmacmillan** [comment]
I'm still having this issue with realm 4.3.4 in android studio 3.0.1 with gradle 4.4.

**Comment by Zhuinden** [comment]
@nmmacmillan what exactly is the issue you are getting?

**Comment by nmmacmillan** [comment]
Databinding just fails to generate binding objects, so compilation fails with "cannot find symbols" for all of the binding classes.  The solutions in this thread solved it, namely adding the kapt databinding compiler.  If there's anything I can do to provide more data or logs, etc. please let me know, I would love to revert to a more typical gradle configuration.

**Comment by Zhuinden** [comment]
Well if https://github.com/realm/realm-java/issues/5654#issuecomment-354960409 solved it, then that's great :smile:

**Comment by nmmacmillan** [comment]
I shouldn't be declaring that in gradle (gradle plugin 3.1 will actually yell at you for doing it), so I'm considering that a temporary workaround for what seems to be a realm issue.  Is this something you guys are still working on or is it considered a non-issue?

**Comment by Zhuinden** [comment]
@nmmacmillan it's not a Realm issue that databinding needs `kapt` scope if you're using Kotlin O_o

**Comment by nmmacmillan** [comment]
hah, yeah I hear what you're saying.  But I only have to do that when I introduce the realm gradle plugin, which is why I suspect something strange going on with how realm is affecting the gradle setup
