### ISSUE TITLE
java.lang.NoClassDefFoundError Model RealmClass

### ISSUE THREAD

**Issue by gauris26** [realm/realm-java#5655]
I'm the error below at runtime when my app start running. Please help me to figure out how fix this issue. I implements a interface SpinnnerItem for build province cascade spinner. 

java.lang.NoClassDefFoundError: com.mypackage.movilaplication.model.Barrio
at io.realm.DefaultRealmModuleMediator.<clinit>(DefaultRealmModuleMediator.java:29)
at java.lang.Class.classForName(Native Method)
at java.lang.Class.forName(Class.java:324)
at java.lang.Class.forName(Class.java:285)
at io.realm.RealmConfiguration.getModuleMediator(RealmConfiguration.java:372)
at io.realm.RealmConfiguration.<clinit>(RealmConfiguration.java:78)
at io.realm.RealmConfiguration$Builder.initializeBuilder(RealmConfiguration.java:501)
at io.realm.RealmConfiguration$Builder.<init>(RealmConfiguration.java:487)
at io.realm.Realm.init(Realm.java:248)
at ado.com.solucionesscotiabank.siemovilasalariado.logic.AsalariadoAplication.onCreate(AsalariadoAplication.java:27)
at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1037)
at android.app.ActivityThread.handleBindApplication(ActivityThread.java:6499)
at android.app.ActivityThread.access$1800(ActivityThread.java:230)
at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1888)
at android.os.Handler.dispatchMessage(Handler.java:102)
at android.os.Looper.loop(Looper.java:148)
at android.app.ActivityThread.main(ActivityThread.java:7409)
at java.lang.reflect.Method.invoke(Native Method)
at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1230)
at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1120)

### Code when error occurr

private static final Set<Class<? extends RealmModel>> MODEL_CLASSES;
    static {
        Set<Class<? extends RealmModel>> modelClasses = new HashSet<Class<? extends RealmModel>>(21);
        modelClasses.add(com.mypackage.mobileapplication.model.Barrio.class);
        modelClasses.add(com.mypackage.mobileapplication.model.BasicInformation.class);
        modelClasses.add(com.mypackage.mobileapplication.model.Canal.class);
        modelClasses.add(com.mypackage.mobileapplication.model.CargoEmpresa.class);
        modelClasses.add(com.mypackage.mobileapplication.model.DatosComParametros.class);
        modelClasses.add(com.mypackage.mobileapplication.model.DistritoMunicipal.class);
        modelClasses.add(com.mypackage.mobileapplication.model.Empresa.class);
        modelClasses.add(com.mypackage.mobileapplication.model.EstadoCivil.class);
        modelClasses.add(com.mypackage.mobileapplication.model.Municipio.class);
        modelClasses.add(com.mypackage.mobileapplication.model.NivelEstudio.class);
        modelClasses.add(com.mypackage.mobileapplication.model.pojo.SMMParametros.class);
        modelClasses.add(com.mypackage.mobileapplication.model.Producto.class);
        modelClasses.add(com.mypackage.mobileapplication.model.Profesion.class);
        modelClasses.add(com.mypackage.mobileapplication.model.PropositoPrestamo.class);
        modelClasses.add(com.mypackage.mobileapplication.model.Provincia.class);
        modelClasses.add(com.mypackage.mobileapplication.model.Referencia.class);
        modelClasses.add(com.mypackage.mobileapplication.model.Sector.class);
        modelClasses.add(com.mypackage.mobileapplication.model.SectorLaboral.class);
        modelClasses.add(com.mypackage.mobileapplication.model.SmartModel.class);
        modelClasses.add(com.mypackage.mobileapplication.model.SubBarrio.class);
        modelClasses.add(com.mypackage.mobileapplication.model.TipoVivienda.class);
        MODEL_CLASSES = Collections.unmodifiableSet(modelClasses);
    }

#### Model
public class Barrio extends RealmObject implements SpinnnerItem {
    @PrimaryKey
    private int codigo;
    private String descripcion;
    public RealmList<SubBarrio> subBarrios;

    public int getCodigo() {
        return codigo;
    }

    public void setCodigo(int codigo) {
        this.codigo = codigo;
    }

    public String getDescripcion() {
        return descripcion;
    }

    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }

    public RealmList<SubBarrio> getSubBarrios() {
        return subBarrios;
    }

    public void setSubBarrios(RealmList<SubBarrio> subBarrios) {
        this.subBarrios = subBarrios;
    }

    public List<SubBarrio> getChilds(){
        return subBarrios;
    }
}

#### Version of Realm
Realm version(s): 4.3.1

Realm sync feature enabled: no

#### Android Studio
Android Studio version: 3.0.1
Build Tools Version: 27.0.3
Which Android version and device: Samsung Galaxy J7 Prime (Android Marshmallow)

**Comment by Zhuinden** [comment]
Do you use kotlin?

What plugins do you apply?

Is the RealmObject specified in a library module?

**Comment by gauris26** [comment]
**Do you use kotlin?** No

**What plugins do you apply?**

### Plugins 
        classpath 'com.android.tools.build:gradle:3.0.1'
        classpath 'io.realm:realm-gradle-plugin:4.3.1'

### Here my dependecies:

    compile 'com.android.support:appcompat-v7:27.0.2'
    compile 'com.android.support:design:27.0.2'
    compile 'com.android.support:support-v13:27.0.2'
    compile 'com.android.support:percent:27.0.2'
    compile 'com.android.support.constraint:constraint-layout:1.0.2'
    compile 'com.android.support:cardview-v7:27.0.2'
    compile 'com.android.support:recyclerview-v7:27.0.2'
    compile 'com.android.support:support-v4:27.0.2'
    compile 'com.google.android.gms:play-services-maps:11.8.0'
    compile 'com.google.android.gms:play-services-location:11.8.0'
    compile 'com.github.mthli:Slice:v1.2'
    compile 'com.github.pinball83:masked-edittext:1.0.3'
    compile 'com.gordonwong:material-sheet-fab:1.2.1'
    compile 'com.jakewharton:butterknife:8.5.1'
    compile 'com.github.ybq:Android-SpinKit:1.1.0'
    compile 'com.code-troopers.betterpickers:library:3.1.0'
    compile 'cn.pedant.sweetalert:library:1.3'
    compile 'com.github.jrvansuita:PickImage:2.1.2'
    compile 'io.reactivex:rxjava:1.2.9'
    compile 'io.reactivex:rxandroid:1.2.1'
    compile 'com.squareup.okhttp3:okhttp:3.7.0'
    compile 'com.squareup.retrofit2:retrofit:2.2.0'
    compile 'com.squareup.retrofit2:converter-jackson:2.2.0'
    compile 'com.squareup.retrofit2:adapter-rxjava:2.2.0'
    compile 'com.bignerdranch.android:expandablerecyclerview:3.0.0-RC1'
    compile 'com.github.aakira:expandable-layout:1.6.0@aar'
    compile 'com.mobsandgeeks:android-saripaar:2.0.3'
    compile 'com.fasterxml.jackson.core:jackson-databind:2.9.0.pr3'
    annotationProcessor 'com.jakewharton:butterknife-compiler:8.5.1'
    compile 'rebus:permission-utils:2.0.1'
    compile 'com.jsoniter:jsoniter:0.9.20'
    compile files('src/main/assets/joda-time-2.9.9.jar')

**Is the RealmObject specified in a library module?** 

I'm not using any library module.

### Here my Realm initialization code:

 Realm.init(this);

RealmConfiguration config = new RealmConfiguration.Builder()
                .name("db_sm_asa.realm")
                .schemaVersion(1)
                .encryptionKey(SecurityManager.getSaltSecretKey())
                .deleteRealmIfMigrationNeeded()
                .build();

**Comment by Zhuinden** [comment]
What API version does this happen on?

Do you have `multiDexEnabled true` in your build.gradle?

**Comment by gauris26** [comment]
### What API version does this happen on?
   ***compile Sdk Version*** 27
   ***build Tools Version*** 27.0.3

### Do you have multiDexEnabled true in your build.gradle?
Yes, I do.

**Comment by Zhuinden** [comment]
Do you properly call `MultiDex.install(this)` in Application, or extend MultiDexApplication?

``` java
public class MyApplication extends Application {
  @Override
  protected void attachBaseContext(Context base) {
     super.attachBaseContext(base);
     MultiDex.install(this);
  }
}
```

or

``` java
public class MyApplication extends MultiDexApplication {
}
```

And

```
<application android:name=".MyApplication"
```

See https://developer.android.com/studio/build/multidex.html

**Comment by gauris26** [comment]
It worked! after I extended the MultiDexApplication class, cleaned and rebuilt!
