### ISSUE TITLE
String too big ?

### ISSUE THREAD

**Issue by chihung93** [realm/realm-java#5658]
I cant update my item because this error:

01-05 14:51:54.609 29242-29545/com.exmaple.realm E/REALM_JNI: jni: ThrowingException 8, String too big, .
01-05 14:51:54.609 29242-29545/com.exmaple.realm E/REALM_JNI: Exception has been thrown: String too big

#### Version of Realm and tooling
Realm version(s): ?
lasted
Realm sync feature enabled: yes/no
no
Android Studio version: 3.0
Which Android version and device: Zenfone Android 6.0

How to fix it?
Thanks.

**Comment by cmelchior** [comment]
Realm has a 16 MB limit on Strings, what kind of String are you trying to insert?

**Comment by chihung93** [comment]
It is an SQL script ( 558965 lines )
File size: 92MB
Each line is not too long.
Ex : 
Insert into HomeLocation (HLocation,Seq,Longitude,Latitude,HomeID,TotalMileage) values ('S32.1233',7,-84.2826855101213,33.5414092372612,'2312312321',10000);

**Comment by Zhuinden** [comment]
The maximum "column" size is 16 MB, so storing 92 MB as one block won't succeed.

**Comment by chihung93** [comment]
so I must split a string to array? 
Which solution is simpler for this case?
Thanks, @cmelchior @Zhuinden

**Comment by cmelchior** [comment]
It depends on what you want to do with it, but yes I suspect that either splitting by each line or some predefined chunks would be the way to go. You could change your model class to have a list of Strings instead of just a single String:

```
public class SQLMapper extends RealmObject {
  public String script; // Your current approach
  public RealmList<String> scriptlines = new RealmList<>(); // Use a list instead with an entry for each line.
}
```

**Comment by Zhuinden** [comment]
`RealmList<String>` doesn't count as a a single column for size limits? That's cool.

**Comment by cmelchior** [comment]
I assume the above answered your question. If not, feel free to reopen.
