### ISSUE TITLE
copyToRealmOrUpdate - size of application is increase

### ISSUE THREAD

**Issue by lmdic** [realm/realm-java#5661]
In Activity I has method:  

```
public static void updateMerchants(final List<Merchant> newMerchantsList) {
        Debug.d(TAG, "updateMerchants: Start, before_newMerchantsList(" + newMerchantsList.size() + ")\n" + newMerchantsList);
        Realm realm = Realm.getDefaultInstance();
        try {
            realm.executeTransaction(new Realm.Transaction() {
                @Override
                public void execute(Realm realm) {
                    realm.copyToRealmOrUpdate(newMerchantsList);

                    List<Merchant> resultMerchantsList = getMerchantsList();
                    Debug.d(TAG, "updateMerchants: after_resultMerchantsList(" + resultMerchantsList.size() + ")\n" + resultMerchantsList);
                }
            });
        } finally {
            realm.close();
         }
}

    public static List<Merchant> getMerchantsList() {
        Realm realm = Realm.getDefaultInstance();
        try {
            List<Merchant> merchantsList = new ArrayList<>();
            RealmResults<Merchant> realmResults = realm.where(Merchant.class).findAll();
            merchantsList.addAll(realm.copyFromRealm(realmResults));
            return merchantsList;
        } finally {
            realm.close();
        }
    }
```

Here Merchant POJO:

```
public class Merchant extends RealmObject {
    @PrimaryKey
    private int id;
    private Image preview;
    private RealmList<PointOfSale> pointsOfSale = new RealmList<>();
}


public class PointOfSale extends RealmObject {
    @PrimaryKey
    private int id;
    private String phone;
    private Coordinates coordinates;
}

public class Coordinates extends RealmObject {
    private double latitude;
    private double longitude;
}

```

Method `updateMerchants()` call in Activity in `onResume()`;

`newMerchantsList `has same size (**9**) and has same merchants (**ids are equals**). Lists `newMerchantsList `has same size as `resultMerchantsList`.
But every time when method `updateMerchants `is call the size of application is **increase** (about 200 KB).
In App info, section Storage, size is increase about 200 KB.

**Comment by Zhuinden** [comment]
Probably because of transaction log

**Comment by lmdic** [comment]
Hm, and how to fix this?

**Comment by Zhuinden** [comment]
Compact, probably

**Comment by lmdic** [comment]
Any example? Thanks

**Comment by Zhuinden** [comment]
Well there is [compactOnLaunch()](https://realm.io/docs/java/latest/api/io/realm/RealmConfiguration.Builder.html#compactOnLaunch--) but personally I used `Realm.compactRealm(configuration)` when all activities were finished.

**Comment by lmdic** [comment]
I try `compactOnLaunch()` but it not help. I get same result. Application's size is constantly growing.

**Comment by cmelchior** [comment]
Have you tried inspecting the data in the Realm. Perhaps you are duplicating data by accident?

**Comment by lmdic** [comment]
Do you mean ,to extract Realm db file and check it?

**Comment by cmelchior** [comment]
Yes, you can view the content using Realm Studio: https://realm.io/products/realm-studio/

**Comment by lmdic** [comment]
Here my POJO:

```
public class Merchant extends RealmObject {
    @PrimaryKey
    private int id;
    private Image preview;
    private RealmList<PointOfSale> pointsOfSale = new RealmList<>();
}


public class PointOfSale extends RealmObject {
    @PrimaryKey
    private int id;
    private String phone;
    private Coordinates coordinates;
}

public class Coordinates extends RealmObject {
    private double latitude;
    private double longitude;
}
```


So I extract myproject.realm db file.

And here statistics (open file by Realm Studio):

Count of objects:

Merchant - 9
Image - 604
PointOfSale - 98
Cooridanates - 10094

OK. Now I extract file after application's size increase.

And here statistics (open file by Realm Studio):
Merchant - 9
Image - 604
PointOfSale - 98
Cooridanates - **10780**

As you can see the count of objects **Cooridanates** was increase.
In POJO **Cooridanates** no field with `@PrimaryKey.`
I my code to update realm db I use method:

`realm.copyToRealmOrUpdate(merchantsRealmList);
`
Desctiption of this method:
_"Updates an existing RealmObject that is identified by the same PrimaryKey or creates a new copy if no existing object could be found"_

So, my POJO **Coordinates** no primary key and as result, the Realm will **create new copy**(not update) exist Coordinates.

But I need to update Coordinates. So to fix this I **MUST** add primary key to POJO Coordinates.
Something like this:

```
public class Coordinates extends RealmObject {
    @PrimaryKey
    private int id;
    private double latitude;
    private double longitude;
}
```

Is I'm right?

If yes, then...  POJO Merchant is incoming from remote server as json. And in this json the Cooridates not id field. And how I can fill id for POJO Coordinates?

**Comment by Zhuinden** [comment]
Honestly, personally I'd just not have a `Coordinates` RealmObject. I'd have those two fields directly as part of `PointOfSale`.

**Comment by lmdic** [comment]
I can't change this hierarchy of POJOs.

**Comment by Zhuinden** [comment]
Well, good luck then 😄

**Comment by lmdic** [comment]
The problem is not only with POJO `Coordinates`. Also with `ImageFormats,ImageSource`. I update my post.

**Comment by Zhuinden** [comment]
`copyToRealmOrUpdate()` will make a new instance of the object if it's not a managed object and it doesn't have a primary key.

So there is no bug in Realm in this regard, it works as expected

**Comment by lmdic** [comment]
So as result is possible two solutions:

-

1.  Add primary key to `Coordinates,ImageFormats,ImageSource`
2.  First delete from Realm POJOs `Coordinates,ImageFormats,ImageSource` and then insert new incoming `Coordinates,ImageFormats,ImageSource` ?

Is I'm right?

**Comment by cmelchior** [comment]
@lmdic Yes, that is correct.

**Comment by lmdic** [comment]
So, in incoming json items `Coordinates,ImageFormats,ImageSource` no content field **ID** . So I have only one option  - to use second approach: 

_For every merchant, first delete from Realm POJOs Coordinates,ImageFormats,ImageSource and then insert new incoming Coordinates,ImageFormats,ImageSource 

Is I'm right?

**Comment by cmelchior** [comment]
Yes, `copyToRealmOrUpdate` will do that for you, but you need to delete all the old ones manually.
