### ISSUE TITLE
Realm-Android object properties does not save Ask

### ISSUE THREAD

**Issue by namhvcntt** [realm/realm-java#5663]
Realm database does not save data.
I am trying to save an object data but when the last phase executed, an AccessToken record is saved but Account.accessToken still null.
Account class

    public class Account extends RealmObject implements Serializable {
        private AccessToken accessToken;

        public AccessToken setAccessToken(AccessToken accessToken) {
            return this.accessToken = accessToken;
        }
    }

AccessToken class:

    public class AccessToken extends RealmObject {
        private long expiration_date;

        private String access_token;
        public void setExpirationDate(long expiration_date) {
            this.expiration_date = expiration_date;
        }
        public void setAccessToken(String access_token) {
            this.access_token = access_token;
        }
    }

Realm saving data code:

    public void changeAccountAccessToken(final Account account, final AccessToken srcAccessToken) {
        realm.executeTransaction(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {
                AccessToken accessToken = realm.createObject(AccessToken.class);
                accessToken.setAccessToken(srcAccessToken.getAccessToken());
                accessToken.setExpirationDate(srcAccessToken.getExpirationDate());
                account.setAccessToken(accessToken);
            }
        });
    }

**Comment by Zhuinden** [comment]
Because `account` is serializable, most likely means you are trying to do `account.setAccessToken` on an unmanaged instance of `account`

**Comment by namhvcntt** [comment]
@Zhuinden I checked account instance: account.isValid() = true. Does true means account is managed by Realm?

**Comment by Zhuinden** [comment]
isManaged()

**Comment by namhvcntt** [comment]
isManaged() returns false, what should I do to save data?

**Comment by Zhuinden** [comment]
Modify an instance of `account` that you obtained from. Realm

**Comment by namhvcntt** [comment]
Thank you very much. I waste 3 days with my stupid code.
