### ISSUE TITLE
Latest version (4.3.1) produse infinite install process for signed apk

### ISSUE THREAD

**Issue by brucemax** [realm/realm-java#5664]
#### Expected Results

> Notmal installation for signed apk

#### Actual Results

>  User complain on infinite installation for some devices (Lg g4, xiaomi), also I have xiaomi phone which also have the same problem during installation signed apk 

Just switch to realm 4.2.0 solve the problem 

#### Version of Realm and tooling
Realm version(s): 4.3.1

Realm sync feature enabled: no

Android Studio version: 3.0.1

Which Android version and device: Android 6.0 Lg G4, Xiaomi Redmi 4

**Comment by Zhuinden** [comment]
For whatever weird reason, this might be fixed by https://github.com/realm/realm-java/issues/5640#issuecomment-355497076

**Comment by Zhuinden** [comment]
This should be fixed by 4.3.2 released today

**Comment by cmelchior** [comment]
I assume the above fixed your issue. If not, feel free to reopen.

**Comment by brucemax** [comment]
Could I ask how you fixed particular this bug?
