### ISSUE TITLE
LinkingObjects isNull query on date field not working

### ISSUE THREAD

**Issue by josephjreij** [realm/realm-java#5665]
#### Goal

I am attempting a backlink query on a date field, i need all the records having null dates in the backlink table.

#### Results

i should be getting one entity in return, but i am in fact getting two. 
![screenshot 1](https://user-images.githubusercontent.com/20541381/34677015-7733e9dc-f497-11e7-90ae-32d64d70a1fd.png)

#### Steps & Code to Reproduce

If i switch the query the other way (to start from the other table without using the LinkingObjects), it works.

Also the issue is only with this date field and isNull condition, other queries on the linking objects fields work just fine for me.

#### Code Sample

non working code (returns two results)

```kotlin

            realm.where(ClassEntity::class.java)
                    .isNull("childClasses.endDate")
                    .equalTo("childClasses.childEntity.id", childId)
                    .findAll()

```

working code (returns one result)

```kotlin

            val classId = realm.where(ChildClassEntity::class.java)
                .isNull("endDate")
                .equalTo("childEntity.id", childId)
                .findFirst()?.classEntity?.id

        return realm.where(ClassEntity::class.java)
                .equalTo("id", classId)
                .findFirst()

```

models

```kotlin

open class ChildClassEntity : RealmObject(){
    @PrimaryKey
    var id: Int = 0

    var classEntity: ClassEntity? = null
    var childEntity: ChildEntity? = null
    var startDate: Date = Date()
    var endDate: Date? = null
}

open class ClassEntity : RealmObject(){
    @PrimaryKey
    var id: Int = 0

    @LinkingObjects("classEntity")
    val childClasses: RealmResults<ChildClassEntity>? = null
}

open class ChildEntity : RealmObject(), ServerEntity {
    @PrimaryKey
    var id: Int = 0

    @LinkingObjects("childEntity")
    val childClasses: RealmResults<ChildClassEntity>? = null
}

```

#### Version of Realm and tooling
Realm version(s): 4.3.1

Realm sync feature enabled: yes

Android Studio version: 3.0.1

Which Android version and device: Nexus 6P - Android 8.1.0

**Comment by Zhuinden** [comment]
Maybe

            realm.where(ClassEntity::class.java)
                    .isNull("childClasses.endDate")
                    .findAll()
                    .where()
                    .equalTo("childClasses.childEntity.id", childId)
                    .findAll()

**Comment by josephjreij** [comment]
Just tried it, same thing. Also note that i tried many other conditions, all are working fine except for isNull("childClasses.endDate")

**Comment by Zhuinden** [comment]
Wow, I'm guessing same is true if you do

        realm.where(ClassEntity::class.java)
                .equalTo("childClasses.childEntity.id", childId)
                .findAll()
                .where()
                .isNull("childClasses.endDate")
                .findAll()

That's weird. I remember that `isNull` had troubles back when it was being created, but I thought that was all fixed up.

Maybe @beeender knows, considering kneth and bmeike aren't around in `realm-java` anymore.

If you have a small sample project that reproduces it then that is super-helpful.

**Comment by josephjreij** [comment]
Nope, same thing. Funny thing is that i tried isNotNull and it worked!

**Comment by nhachicha** [comment]
Hi @josephjreij can you please share your sample project, I'll try to reproduce

**Comment by josephjreij** [comment]
I don't have a sample project for this issue, i provided the models, queries (working and not working) and a snapshot of 2 rows that can help reproduce the issue

**Comment by Zhuinden** [comment]
@nhachicha actually he's right, we have all the models and stuff. Could even make a unit test out of it.

**Comment by nhachicha** [comment]
@josephjreij 
By 2 rows you mean 2 `ChildClassEntity` using the same reference to the `ChildEntity` and `ClassEntity` as follow?
```Kotlin
Realm.getInstance(realmConfiguration).use { realm ->
            realm.executeTransaction { realmWrite ->
                val classEntity = realmWrite.copyToRealm(ClassEntity().apply {
                    id = 10
                })

                val childEntity = realmWrite.copyToRealm(ChildEntity().apply {
                    id = 51
                })

                realmWrite.insert(ChildClassEntity().apply {
                    id = 73
                    this.childEntity = childEntity
                    this.classEntity = classEntity
                })

                realmWrite.insert(ChildClassEntity().apply {
                    id = 94
                    endDate = Date()
                    this.childEntity = childEntity
                    this.classEntity = classEntity
                })
            }

            // queries
            val result = realm.where(ClassEntity::class.java)
                    .isNull("childClasses.endDate")
                    .equalTo("childClasses.childEntity.id", 51 as Int)
                    .findAll()
            assert(result.size == 1) // ClassEntity with id = 10

        }
```

**Comment by Zhuinden** [comment]
@nhachicha you can now use `import io.realm.kotlin.where` and then you can do `realm.where<ClassEntity>().isNull...` 😄

**Comment by josephjreij** [comment]
@nhachicha no the idea is to have 2 ClassEntity linked to 1 ChildEntity through 2 ChildClassEntity, one of them having endDate null and the other not null

However, i was correcting your code and testing it and it worked!!! So i kept checking and found out that in order to reproduce the bug, we need another ChildEntity and another ChildClassEntity with endDate null

Check this out:

This code is working:
```kotlin

Realm.getInstance(realmConfiguration).use { realm ->
    realm.executeTransaction { realmWrite ->
        val classEntity1 = realmWrite.copyToRealm(ClassEntity().apply { id = 1 })
        val classEntity2 = realmWrite.copyToRealm(ClassEntity().apply { id = 2 })

        val childEntity1 = realmWrite.copyToRealm(ChildEntity().apply { id = 1 })

        realmWrite.insert(ChildClassEntity().apply {
            id = 1
            this.childEntity = childEntity1
            this.classEntity = classEntity1
        })

        realmWrite.insert(ChildClassEntity().apply {
            id = 2
            endDate = Date()
            this.childEntity = childEntity1
            this.classEntity = classEntity2
        })
    }

    // queries
    val result = realm.where(ClassEntity::class.java)
            .isNull("childClasses.endDate")
            .equalTo("childClasses.childEntity.id", 1 as Int)
            .findAll()
    assert(result.size == 1) //returns ChildClassEntity[id=1]

}
```

While this is not working:
```kotlin

Realm.getInstance(realmConfiguration).use { realm ->
    realm.executeTransaction { realmWrite ->
        val classEntity1 = realmWrite.copyToRealm(ClassEntity().apply { id = 1 })
        val classEntity2 = realmWrite.copyToRealm(ClassEntity().apply { id = 2 })

        val childEntity1 = realmWrite.copyToRealm(ChildEntity().apply { id = 1 })
        val childEntity2 = realmWrite.copyToRealm(ChildEntity().apply { id = 2 })

        realmWrite.insert(ChildClassEntity().apply {
            id = 1
            this.childEntity = childEntity1
            this.classEntity = classEntity1
        })

        realmWrite.insert(ChildClassEntity().apply {
            id = 2
            endDate = Date()
            this.childEntity = childEntity1
            this.classEntity = classEntity2
        })

        realmWrite.insert(ChildClassEntity().apply {
            id = 3
            this.childEntity = childEntity2
            this.classEntity = classEntity2
        })
    }

    // queries
    val result = realm.where(ClassEntity::class.java)
            .isNull("childClasses.endDate")
            .equalTo("childClasses.childEntity.id", 1 as Int)
            .findAll()
    assert(result.size == 1) //returns ChildClassEntity[id=1] and ChildClassEntity[id=2]

}
```
So the third `ChildClassEntity` [id=3] ruined the result.

Note that although [id=3] affected the result, the query actually returns [id=1] and [id=2]
Also note that if i add an `endDate` to [id=3], the query works and returns [id=1] only

**Comment by nhachicha** [comment]
Ok here's a representation of your model
```
       +-----------+
       |           |
       |           |
       |           |
       +-----------+                         +------------+
                              +------------> |ClassEntity1|
       +------------------+   |              +------------+
       |                  +---+              +------------+
null   |ChildClassEntity1 |          +-----> |ChildEntity1|
       |                  +----------+   +-^ +------------+
       +------------------+   +----------+
                              |              +------------+
       +------------------+   |  +---------> |ClassEntity2|
       |ChildClassEntity2 +---+  |    +-----^-------------+
       |                  +------+   ++      +------------+
       +------------------+          |       |ChildEntity2|
       +------------------+          |       +------+-----+
       |                  +----------+              ^
null   |ChildClassEntity3 |                         |
       +------------------+-------------------------+
```
Let's break the query into steps
1- we run `realm.where(ClassEntity::class.java).isNull("childClasses.endDate")` which brings the following backlinks `[ChildClassEntity1, ChildClassEntity3]`, both have links to `ClassEntity1` and `ClassEntity2`.

2- now you run a query (`.equalTo("childClasses.childEntity.id", 1 as Int)`) from the preivous result (i.e `[ClassEntity1, ClassEntity2]`)  which will select the  `ClassEntity` which have a backlinks pointing to `ChildEntity1` which are `ChildClassEntity1` and `ChildClassEntity2`, hence you end up with `ClassEntity1` and `ClassEntity2`

The confusion might come from the fact that you think `.equalTo("childClasses.childEntity.id", 1 as Int)` is running against `[ChildClassEntity1, ChildClassEntity3]`, whereas your query from the beginning is working on the `ClassEntity` table.

A workaround could be to query from `ChildClassEntity` as follow
```Kotlin
realm.where(ChildClassEntity::class.java).isNull("endDate").equalTo("childEntity.id", 1 as Int).findAll()
```

**Comment by josephjreij** [comment]
Ok i think i got your point. I was thinking of this as one JOIN query while actually Realm executes each query separately from the other. Thanks.
