### ISSUE TITLE
Change listener not fired if query is fast

### ISSUE THREAD

**Issue by cioraneanu** [realm/realm-java#5667]
I am using the async query along with a change listener to fetch some data from Realm. However depending on the complexity of the query(and how much time it takes to return the results) I get situations when the listener isn't called. 

I even tried to add a separate check if the result is finished before attaching the listener but that still didn't work.

My code:
```
// Dynamic where_in query, generated with multitple .or() chain
final RealmResults<...> list = realm.where(...).findAllAsync();
if (list.isLoaded()) {
    updateUI(list);
} else {
    list.addChangeListener(new OrderedRealmCollectionChangeListener<RealmResults<...>>() {
    @Override
    public void onChange(RealmResults<...> list, @javax.annotation.Nullable OrderedCollectionChangeSet changeSet) {
        if (changeSet == null) {
            updateUI(list);
            list.removeAllChangeListeners();
        }
    }
    });
}
```

Even with this method in my log I don't see the updateUI() method called every time.

I would have expected that even with a fast query, attaching a listener the very next line would still call me the listener with a null changeSet.

**Comment by cmelchior** [comment]
Even if the query is fast the listener should trigger, but judging from your code, if `list` is GC'ed then the listener will not trigger.

**Comment by cioraneanu** [comment]
Just checked. You are right. Thanks for your fast response.
