### ISSUE TITLE
In activity, cannot put realm object of array list into another activity

### ISSUE THREAD

**Issue by huhuanming** [realm/realm-java#567]
User is a subclass of RealmObject
userList is a ArrayList<User> 

Intent intent = new Intent(this,otherActivity.class);
Bundle bundle = new Bundle();
bundle.putSerializable("user", userList);
intent.putExtras(bundle)

But in otherActivity,  I only get userList size.
If I want get User in userList, it will throw a error.

**Comment by kentcheung2000** [comment]
Can you also give me an example of using identifier of your object.  I am having the same problem of retrieving data from realm object in my second activity....

**Comment by huhuanming** [comment]
please wait... i have to look my code.

**Comment by beeender** [comment]
@kentcheung2000 @huhuanming We recently added an example of passing objects via IDs, check https://github.com/realm/realm-java/commit/4d301dfe6294884ab6d81ebf169df0fce358023b

**Comment by huhuanming** [comment]
not recommended  use Realm a lot  in  Android, if data what you cannot want to save anywhere.
Please use it for important data and  read it from Realm database in another activity
