### ISSUE TITLE
Android java.lang.IllegalStateException: Realm access from incorrect thread. Realm objects can only be accessed on the thread they were created.

### ISSUE THREAD

**Issue by jay5586** [realm/realm-java#5671]
I have create database from realm display all value in recyclerview in android.

When i have delete two or three records in adapter getting error realm object can only be accessed on the thread they were created.

Any solution?

Delete code

 myRealm.executeTransactionAsync(new Realm.Transaction() {
            @Override
            public void execute(Realm bgRealm) {

                ColabrationContact item = bgRealm.where(ColabrationContact.class).equalTo("share_name", itemName).findFirst();
                if (item != null) {
                    try {
                        item.deleteFromRealm();
                    } catch (Exception e) {
                        e.printStackTrace();
                    }

                }
            }
        }, new Realm.Transaction.OnSuccess() {
            @Override
            public void onSuccess() {
                // Transaction was a success.
                Log.d("JD", "database" + "Delete ok");
            }
        }, new Realm.Transaction.OnError() {
            @Override
            public void onError(Throwable error) {
                // Transaction failed and was automatically canceled.
                Log.d("JD", "database = " + error.getMessage());
            }
        });

**Comment by Zhuinden** [comment]
I don't think this is where the exception happens.

**Comment by cmelchior** [comment]
No response. Closing
