### ISSUE TITLE
Can't check empty realm list size

### ISSUE THREAD

**Issue by san92der** [realm/realm-java#5674]
Hi all! I Have an empty realm list, that i loaded from base. If I check list size in debugger or print list size, it always equal 0. But it's doesn't pass the if-statement and throw an exception at second return-statement.
```
    Log.d(TAG, "list is empty = " + (myRealmList.size() == 0));//print true

    if (myRealmList.size() == 0)
            return null;

    return Float.parse(myRealmList.get(0).floatTextField);//throw Attempt to invoke virtual method 'float java.lang.Float.floatValue()' on a null object reference
```

What I did wrong?

**Comment by Zhuinden** [comment]
The object exists, but you store a `Float floatTextField;` value in Realm, which is **nullable**, and you are passing `null` to `Float.parse()` which crashes.

**Comment by san92der** [comment]
But it throw IndexOutOfBoundsException if myRealmList's size = 0
How can I check is list size is empty?

**Comment by Zhuinden** [comment]
You need to check both things.

**Comment by Zhuinden** [comment]
if (myRealmList.size() == 0)
            return null;
    if(myRealmList.get(0).floatTextField != null) {
         return Float.parse(myRealmList.get(0).floatTextField);
    } else {
         return null;
    }

**Comment by VenomVendor** [comment]
@san92der, the realm way.
```java
if (myRealmList.isEmpty()) {
     return null;
} 
if (myRealmList.first().floatTextField != null) {
     // Caution!, the value of floatTextField, is not guaranteed to be non-null at this point.
     return Float.parse(myRealmList.first().floatTextField);
} else {
     return null;
}

**Comment by cmelchior** [comment]
Question should be answered, so closing
