### ISSUE TITLE
Realm does not generate getters and setters.

### ISSUE THREAD

**Issue by diegohdez90** [realm/realm-java#5694]
#### Goal

Implements getters and setters

#### Expected Results

What is the best way to implements getters and setters from my models?

#### Actual Results

When I click in **Build -> Make Project** I expect Realm generate getters and setter of my model but I don'et see progress.

#### Steps & Code to Reproduce

I updated my models from GreenDao to Realm manually.

#### Code Sample

[My models](https://gist.github.com/diegohdez90/0fe51f76f504f8815012e72ea59a3419).
[build.gradle](https://gist.github.com/diegohdez90/b4b277c917dd35f7c5dd02abbb17f41c).

#### Version of Realm and tooling
Realm version(s): 4.3.1

Realm sync feature enabled: yes

Android Studio version: 3.0.1

Which Android version and device: 6

**Comment by Zhuinden** [comment]
Well it does generate getters/setters, in the `___RealmProxy` class, which is created when you obtain the object from Realm or RealmResults (or a RealmList obtained from a RealmObject obtained from Realm/RealmResults).

So the getters/setters are actually used when the object is a managed RealmObject class.

If you expect getters/setters to magically pop up in your RealmObject classes themselves though, then you should look into `Lombok`. :smile:

**Comment by diegohdez90** [comment]
Thanks @Zhuinden
