### ISSUE TITLE
User is not part of the schema for this Realm。

### ISSUE THREAD

**Issue by KnightOneAdmin** [realm/realm-java#5697]
#### Goal

> What do you want to achieve?

#### Expected Results

> ?

#### Actual Results

>  E.g. full stack trace with exception

#### Steps & Code to Reproduce

> Describe your current debugging efforts.

#### Code Sample

```java

> Your code here. Bigger samples should ideally be as separate Android Studio project, 
> in gists/repositories or privately at help@realm.io)

```

#### Version of Realm and tooling
Realm version(s): ?

Realm sync feature enabled: yes/no

Android Studio version: ?

Which Android version and device: ?

**Comment by KnightOneAdmin** [comment]
User is not part of the schema for this Realm.

**Comment by Zhuinden** [comment]
1.) are you using kotlin

-  if yes, do you apply `kotlin-kapt` plugin
 
      - if yes, do you apply `kotlin-kapt` ***before*** `realm-android` plugin

           - if no, then apply kotlin kapt before realm-android

     - if no, you need to apply kotlin-kapt plugin

- if no, then check other options
1.

2.) are you trying to use `User` class from library project's RealmModule

3.) is the `User` class a newly added class that was supposed to be added via a migration, but the `schemaVersion` was not increased and the migration was not provided?

It's most likely not `deleteIfMigrationNeeded()`.

**Comment by KnightOneAdmin** [comment]
Thx, I will check the direction you provided, thanks again.

**Comment by cmelchior** [comment]
I assume the above solved your issue, if not feel free to reopen. Closing.
