### ISSUE TITLE
Random crashes, Huge instabilities with latest 5 version(s) (double free, RealmFinalizing..etc.)

### ISSUE THREAD

**Issue by drakeowen** [realm/realm-java#5703]
We're developing an application that heavily relies on Realm. We moved out from SQLite/SnappyDB since after benchmarking we found Realm outperform them all.

For the past period we've tried everything and every design/execution/transaction pattern possible to avoid random crashes allover our application, practically we rewrote everything related to DB around 3 or 4 times allover without any luck trying to avoid humongous amount of crashs.

The crashes are not consistent, happens everywhere, however we've narrowed them down to a sorted list and %95 of them happen when a GC is triggered. They're all related to RealmFinalizing attempting to free an already freed object or memory location, no idea!

We've got similar issues when were developing a JNI library where we were attempting to free an already freed pointer or freeing it before its attempted to be used.

I'll be pasting you here snippets from the crash.

Our crashes occurs more commonly on ART running devices, however they occur on Dalvik ones too (since both of them handles GCing differently).

Android versions tried on (4.4, 5.0, 6.0, 7.0) both arm-v7 and arm-v8a.

The reason we waited months before reporting this issue is from what we can get reading over the issues we see you always demand a source code or an apk and providing any of these is extremely hard, nearly impossible however we can provide any help possible trying to reproduce this issue.

#### Goal

> What do you want to achieve?

Have no crashes using Realm. We currently run 4.3.3

#### Actual Results

Crash #1 -> https://pastebin.com/uvpsm51j

Crash #2 -> https://pastebin.com/PeJnzsLF

Crash #3 -> https://pastebin.com/zwyzAxqa

Crash #4 -> https://pastebin.com/QDcey7wm

Crash #5 -> https://pastebin.com/PPZ45Yvm

Crash #6 -> https://pastebin.com/fbej9DWr

#### Version of Realm and tooling
Realm version(s): 4.3.3, 4.3.2, 4.3.1, 4.3.0, 4.2.0

Android Studio version: 2.x, 3.x

Which Android version and device: ?
Android versions tried on (4.4, 5.0, 6.0, 7.0) both arm-v7 and arm-v8a.

**Comment by Zhuinden** [comment]
This is a bit over my level as a random community member, but out of curiosity, do you have any of the following in no particular order:

- encryption 

- `RealmList<Integer>` / `RealmList<String>`

- `RealmObjectChangeListener`

- create multiple configuration instances for accessing the same Realm

- the following construct:

```
for(something something)  {
    RealmResults<T> results =... 
    realm.executeTransaction((r) -> {
       ... 
```

Especially if this is on a background thread pool or AsyncTask doInBackground 

- the following construct 

```
RealmChangeListener realmChangeListener = (element) -> {
    RealmResults results = realm.where... 
    results.addChangeListener(...
};
```

And did this start occurring at 4.2.0? Or what was the previous version where this didn't happen? 

Of course, Realm will ask for APK and stuff to help[at]realm.io when they get here

**Comment by drakeowen** [comment]
Hello @Zhuinden 

We use encryption, RealmObjectChangeListener

Also we have multiple instances opened of any Realm instance we have. At least 5 ~ 7 instances.

We use TPEs, AsyncTask and doInBackground. We use the first code construct sample you enlisted however not in the same exact manner as we always loop inside a transaction. We do use addChangeListener however not in the same manner as well.

4.2.0 was the earliest that we tried.

I've seen a handful number of issues that seemed related to our case however none helped.

Our app can't hold itself for more than a couple of minutes or less without crashing.

No debugging way is useful at all. Just trial an error, and that also didn't work!

**Comment by Zhuinden** [comment]
I should have also asked if you use `RealmRecyclerViewAdapter` with `super(results,true,false)`.

My intuition tells me that it could be related to closed Activities that show a RecyclerView with ViewHolders that hold a RealmObject with a RealmObjectChangeListener, and the Activity is finished, but the RealmObjectChangeListener stays added to the RealmObject. 

I haven't put together a sample yet to see what happens with lots of background thread transactions and many calls to System.gc()

**Comment by bmunkholm** [comment]
@drakeowen Really sorry you are experiencing this. It's of no help to you to know that we have not heard of any others experiencing this. This does, however, indicate that it seems very related to your code, but not necessarily your bug. Perhaps you are just using Realm in a unique way that triggers a bug in our code.
As you obviously understand, it is extremely hard to resolve this issue without any way for us to see and debug your code.
Please do get in touch with us at help at realm.io to discuss how we can approach this.

Let's however not kill the discussion here with good ideas from others!

**Comment by drakeowen** [comment]
Thanks Brian. Will email you the soonest on help.

**Comment by Zhuinden** [comment]
I've attempted to set up something that could have broken based on what I could assess, but I haven't succeeded in reproducing. :disappointed: 

The attempt is https://github.com/zhuinden/realm-break-5703

**Comment by cmelchior** [comment]
So just to clarify, you are not seeing this problem if using a version of Realm that is lower than 4.2.0?

**Comment by drakeowen** [comment]
@bmunkholm We've emailed you already.

@cmelchior We tried previously getting to older versions however had the same crashes and now we removed deprecated stuff like `findAllSorted()` for example so we have to change decent amount of code to be able to downgrade.

**Comment by bmunkholm** [comment]
@drakeowen We never got any responses on the emails, so I'm going to close this one here. Don't hesitate to reach out by email in case you need more help.
