### ISSUE TITLE
How can I sort Date field whitch has some nulls ?

### ISSUE THREAD

**Issue by luao419** [realm/realm-java#5704]
My project has some field instanceof Date whitch is null in the realm. How can I use the sort API to do the same things like that 'from A  as a order by a.b asc null last' in Oracle.
There is some objects in my project , now I want to sort them with one Date field by Sort.DESCENDING.But, they has some objects whitch the field is null. so how can I put them on the last of the realmresult or fiirst?
Please help me ,Thanks!

**Comment by cmelchior** [comment]
NULL is placed first when sorting ASCENDING or last when sorting DESCENDING. There is currently no way to change that behaviour outside manually sorting the `RealmResults` afterwards.

We are already tracking this feature request in https://github.com/realm/realm-java/issues/3209 so I'll fold it into that one.
