### ISSUE TITLE
How get table data size?

### ISSUE THREAD

**Issue by fenggit** [realm/realm-java#5705]
#### Goal

> What do you want to achieve?

#### Expected Results

> ?

#### Actual Results

>  E.g. full stack trace with exception

#### Steps & Code to Reproduce

> Describe your current debugging efforts.

#### Code Sample

```java

> Your code here. Bigger samples should ideally be as separate Android Studio project, 
> in gists/repositories or privately at help@realm.io)

```

#### Version of Realm and tooling
Realm version(s): ?
news 
Realm sync feature enabled: yes/no
no
Android Studio version: ?
3.0
Which Android version and device: ?

**Comment by Zhuinden** [comment]
What do you mean `table data size`? The number of items can be acquired as `realm.where(MyObject.class).count()`

**Comment by fenggit** [comment]
Thanks Reply ，but **.findAll().size()** is Overhead。

**Comment by Zhuinden** [comment]
For existing `realmResults` you can use `.size()`, for query you can do `.count()`

**Comment by fenggit** [comment]
okay ， I want to have to listen DB size, mainly in order to upload data, such as when the data reaches 1M, went to upload

**Comment by Zhuinden** [comment]
``` java
RealmResults<T> results;

void blah() {
    results = realm.where(Blah.class).findAll();
    results.addChangeListener(new RealmChangeListener<RealmResults<Blah>>() {
        @Override
        public void onChange(RealmResults<Blah> element) {
            if(element.size() > 1000000) {
                ...
```

**Comment by fenggit** [comment]
Ok, thanks for the help。
