### ISSUE TITLE
Gradle build something wrong with io.realm:realm-gradle-plugin:4.3.3

### ISSUE THREAD

**Issue by koukoucai** [realm/realm-java#5708]
#### Actual Results

```groxy
Error:associated EnclosingMethod attribute. This class was probably produced by a
Error:compiler that did not target the modern .class file format. The recommended
Error:solution is to recompile the class from source, using an up-to-date compiler
Error:and without specifying any "-target" type options. The consequence of ignoring
Error:this warning is that reflective operations on this class will incorrectly
 processError:indicate that it is *not* an inner class.
Error:Error converting bytecode to dex:
Cause: Dex cannot parse version 52 byte code.
This is caused by library dependencies that have been compiled using Java 8 or above.
If you are using the 'java' gradle plugin in a library submodule add 
targetCompatibility = '1.7'
sourceCompatibility = '1.7'
to that submodule's build.gradle file.
Error:1 error; aborting
Error:Execution failed for task ':app:transformClassesWithDexForDebug'.
> com.android.build.api.transform.TransformException: com.android.ide.common.process
.ProcessException: java.util.concurrent.ExecutionException: com.android.ide.common.process.ProcessException:
 Return code 1 for dex
```

#### Steps & Code to Reproduce

> I just update io.realm:realm-gradle-plugin:3.5.0 to io.realm:realm-gradle-plugin:4.3.3
>Then  gradle build this program , something happened like the message.
>That message suggests me to use java 1.7 ? not 1.8 ? If I keep using java 1.8 ,there would be better solution?

#### Version of Realm and tooling
Realm version(s): 4.3.3

Realm sync feature enabled: yes

Android Studio version: 3.0

Which Android version and device: java 1.8,  android compile 25 ,gradle plugin 2.2.0

**Comment by edicarreras** [comment]
Same problem here. Any clue?

Realm version(s): 4.3.3
Realm sync feature enabled: no
Android Studio version: 3.0
Which Android version and device: java 1.8, android compile 24 ,gradle plugin 2.3.3

**Comment by koukoucai** [comment]
I used Realm version(s): 4.0.0  to avoid this problem for program's stability.

**Comment by cmelchior** [comment]
Can you try upgrading the Gradle plugin to 3.0 ?

**Comment by cmelchior** [comment]
I assume the above answered your question. If not, feel free to reopen.
