### ISSUE TITLE
Deep copy for nested objects

### ISSUE THREAD

**Issue by eGorets** [realm/realm-java#5711]
I have an object with nested models like below 

```
class Parent(
     @PrimaryKey var name: String,
     var kids: Kid
)

class Kid(
    var boy: Child,
    var girl: Child,
)

class Child(var name: String)
```

and I save few `Parents`objects to Realm using `insertOrUpdate`, but when I'm getting back their `Child`, they have empty params, sometimes I can get Child' name, but I have no idea why it's not working as expected

**Comment by Zhuinden** [comment]
Well I can't really know what you're *actually* saving, so I can't know what you're querying back either 😄 

I'm also kinda confused why it's not just

``` kotlin
class Parent : RealmObject() {
    var kids: RealmList<Kid>? = null
}
```

**Comment by cmelchior** [comment]
That should work, so without some way to reproduce this, it is hard to tell why it seems to not work.

**Comment by eGorets** [comment]
I'm a little bit confused. I've created sample and it works perfect, but my real project works with random Realm behaviour. Only few diffs are work project coded on Kotlin + Rx and data fetching from API, but sample is on Java. Is it possible kapt issue or there is no time for saving nested object into reactive stream?? I think this ticket can be closed, I will keep testing my case.
Thanks for your help.

**Comment by eGorets** [comment]
It's definitely json mapping issue, I did mock object into the real project and it saved all nested object, but when it comes from API it doesn't do deep copying
