### ISSUE TITLE
findFirst() not working with sort()

### ISSUE THREAD

**Issue by paldrian** [realm/realm-java#5714]
Using DynamicRealm 4.3.3 

A) 
`DynamicRealmObject lastTrack = realm.where(Model.TRACK).sort("timeStart", Sort.DESCENDING).findAll().first(null);`
and 
B) 
`DynamicRealmObject lastTrack = realm.where(Model.TRACK).sort("timeStart", Sort.DESCENDING).findFirst();`

A) and B) have different results. A) is correct working, B) not working

**Comment by cmelchior** [comment]
What do you mean with "not working" ?

**Comment by Zhuinden** [comment]
@cmelchior I'd assume it returns a different value than `findAll().first()`.

**Comment by paldrian** [comment]
exactly what @Zhuinden said

A returns the correct object, b returns an other object

**Comment by MikeKasperlik** [comment]
Ouh this one is very bad. Is this how it should work? I hope not, confused two devs for quite some time finding the cause of an bug.

**Comment by Zhuinden** [comment]
There didn't use to be a `findFirstSorted()` so I think this is probably just an oversight.

`findAll().first(null)` is recommended at this time.

**Comment by wightwulf1944** [comment]
just spent 4 hours troubleshooting this thinking that I made a mistake somehow

**Comment by cmelchior** [comment]
Fixed by #5848

**Comment by tulioccalazans** [comment]
It is not working yet!
Realm version 4.3.3. @cmelchior

**Comment by Zhuinden** [comment]
Well yeah it was fixed in 5.0.1
