### ISSUE TITLE
How to store many to many, sharing the same object?

### ISSUE THREAD

**Issue by jrcacd** [realm/realm-java#5716]
What is needed:
- **Object** and **tag** are entities
- 1 **Object** can have many **tags**
- tags have a unike ID 
- Tags can belong to multiple objects.
- Searching for one specific tag ID must return all object's that have that tag

**Comment by cmelchior** [comment]
```
public class Object extends RealmObject {
  RealmList<Tag> tags;
}

public class Tag extends RealmObject {
  @PrimaryKey public String id;

  @LinkingObjects("tags")
  RealmResults<Object> objects;
} 
```

**Comment by jrcacd** [comment]
Code: 
```
//transaction
var tag = db.where<Tag>()
	.equalTo(TagFields.ID, id)
	.findFirst()

var object = Object()
object.tags.add(tag)
db.insert(object)
//transaction end
```

**Comment by Zhuinden** [comment]
You should be using `insertOrUpdate()` for inserting the element if it already exists.

If `Object` has no primary key, then however you should be doing

     val obj = realm.create<Object>();
     obj.tags.add(tag)

**Comment by jrcacd** [comment]
But why do I need to do `insertOrUpdate()` when inserting the **object** if only the **tag** already exist?

**Comment by Zhuinden** [comment]
Because insert happens hierarchically. Anyways, I did say what you can do.

**Comment by jrcacd** [comment]
> Because insert happens hierarchically.
Ok, I didn't know.

> Anyways, I did say what you can do.
Yes. You'r right. thanks.
Error found
