### ISSUE TITLE
Java error using kotlin delegated properties with generics

### ISSUE THREAD

**Issue by ethanblake4** [realm/realm-java#5719]
Consider the following code:

```kotlin
//Track.kt
interface Track {
    val name: String
}

//MusicTrack.kt
open class MusicTrack (
    override var name: String = ""
) : RealmObject(), Track

//Album.kt
interface Album {
    val tracks: List<Track>
}

//MusicAlbum.kt
open class MusicAlbum (
    override var tracks: RealmList<MusicTrack> = RealmList()
) : RealmObject(), Album

```

When building this code, the following error is thrown by javac and the build fails:
```java
error: getTracks() in MusicAlbum cannot implement getTracks() in Album
public class MusicAlbumRealmProxy extends com.xyz.model.MusicAlbum
       ^
  return type RealmList<MusicTrack> is not compatible with List<Track>
```
There are no lint errors and no warnings from Kotlin or Realm.

#### Version of Realm and tooling
Realm version(s): 4.3.3

Realm sync feature enabled: no

Android Studio version: 3.1 Canary 8

Which Android version and device: minSdk 21, targetSdk 27. Device N/A

**Comment by cmelchior** [comment]
Fixed in #5723

**Comment by cmelchior** [comment]
Ups, wrong issue. Reopining

**Comment by ashughes** [comment]
I just ran into this as well.

Realm: 5.0.1
Kotlin: 1.2.31
Android Studio: 3.1.1

**Comment by nhachicha** [comment]
@ethanblake4 @ashughes 
The proxy is compiled in Java, I think to make it work with Kotlin we'd have to define `Album` as follows:

```Kotlin
interface Album {
    val tracks: List<@JvmWildcard Track>
}
```

**Comment by Zhuinden** [comment]
Actually, I think this is because `override var` creates `public List<Track> getTrack()` while you already have a `public RealmList<Track> getTrack()` at the same time and they clash.

Solution would be to have a separate variable for the RealmList and the List.

``` kotlin
//MusicAlbum.kt
open class MusicAlbum (
    override val tracks: List<Track>
        get() = musicTracks

    var musicTracks: RealmList<MusicTrack>? = null
) : RealmObject(), Album
```

**Comment by cmelchior** [comment]
Closing due to no response. Feel free to reopen if this is still a problem.
