### ISSUE TITLE
Flutter support

### ISSUE THREAD

**Issue by Zhuinden** [realm/realm-java#5728]
I wonder if that'll ever happen. If there's Xamarin, there could even be Flutter? 😄

I don't actually use Flutter personally, I just wanted to make an issue for it.

**Comment by MarkOSullivan94** [comment]
Would it be better to just support Dart in general? I know there's AngularDart for building web apps ofr example.

**Comment by johnpryan** [comment]
related: https://github.com/realm/realm-object-server/issues/55

**Comment by sergeyfitis** [comment]
Any news, updates? Flutter has been reached stable release 1.0.

**Comment by KingWu** [comment]
Any update?

**Comment by bmunkholm** [comment]
There is no new update - please follow realm/realm-object-server#55 instead - and assume there is no update unless one is posted ;-)
