### ISSUE TITLE
Support string based queries

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#5730]
With https://github.com/realm/realm-core/pull/2979 nearing completion the query serializer is soon in a state where can consider exposing it in the public API since it supports use cases not yet covered by the static query API like #1615 and #1598.  

Suggestions:
```

// 1) `filter` as a new predicate that takes a string. 
RealmResults<Person> results = realm.where(Person.class).filter("field1 > field2").findAll();

// 2) `filter` as an alternative to `where`. Makes the difference more "important" 
      plus aligns better with Swift naming
RealmResults<Person> results = realm.filter(Person.class, "field1 > field2").findAll();

// 3) Let filter be fully lazy, like e.g. Cocoa. A step toward unifying semantics 
      across bindings. It will probably massively complicate the internals though, 
      also means we cannot combine typed/stringbased predicates.
RealmResults<Person> results = realm.filter("Person.class, "field1 > field2");
```

It is still missing support for backlink queries and sorting/distinct, but that should be acceptable since it should be possible to combine the string-based and function based API's: 

```
realm.where(Person.class)
    .filter( "field1 > field2")
    .equalTo("name", "Jane")
    .sort("name")
    .findAll()
```

Some caveats:
- An initial simple implementation will only work with cores internal names and not the names defined in Java (this could be a problem when using `@RealmField` to change names). This is especially problematic if combining typed and string based input

**Comment by ironage** [comment]
I like this idea :) Note that the parser is built independently from core as `realm-core-parser.a` because it adds about 1.4MB to the binary. Would this be a concern to Android users? Maybe users could opt-in to add the parser if they don't mind the extra space?

By the way, sort and distinct in the query string is also supported (in https://github.com/realm/realm-core/pull/2979) but you can also chain it to the typed API if preferred like the example above.

**Comment by cmelchior** [comment]
If it is 1.4 MB pr. architecture, that seems excessive, and something we would need to think extremely hard about how to include because I doubt we can make that the default in that case, but it should be possible as some sort of extension I guess.

**Comment by Zhuinden** [comment]
@ironage but there [used to be a query parser in object-store too, so I'd guess there must have been some size gain from moving it into a core module?](https://github.com/realm/realm-object-store/commit/21e671a155989f4e34e279fc8a7ace5817495de0)

I can't really tell how much size difference it makes overall, though :D that's a bit bigger than I expected, but still, this feature would be super-powerful.

So you'd need to use `internal names` like you do for the DynamicRealm / migrations, right?

**Comment by ironage** [comment]
@Zhuinden it's a good point, it may end up being the same size as when the parser was embedded in the object store. At some point we should just try it and compare the sizes.

Using internal names would work, but the parser is also going to support [name aliasing](https://github.com/realm/realm-core/pull/2989/files#diff-d69ee68d9dcbfc8f1b35f82a93e09ac7R33) which could be utilised to do the string replacement at some point.

**Comment by tgoyne** [comment]
The object store version was never actually built or included in the library for any of the client SDKs other than javascript.

**Comment by cmelchior** [comment]
https://github.com/realm/realm-java/pull/6116 merged support for String-based query predicates. This will be part of 10.4.0.
