### ISSUE TITLE
Could not get unknown property 'packageForR' for task '::processDebugResources' of type 

### ISSUE THREAD

**Issue by iman2420** [realm/realm-java#5731]
**Bugs**: I want to update Realm database from version 4.2.0 to 4.3.3, but after gradle sync, it will fail

**Goal**

Update Realm from 4.2.0 to 4.3.3

**Expected Results**

Gradle sync will success

**Actual Results**

Gradle sync failed with stacktrace:

```
Error:Execution failed for task ':QuizApp:processDebugResources'.
> Could not get unknown property 'packageForR' for task ':QuizApp:processDebugResources' of type com.android.build.gradle.internal.res.LinkApplicationAndroidResourcesTask.
```

**Comment by cmelchior** [comment]
This doesn't look like it is related to Realm. Try cleaning your gradle cache and stop the gradle daemon. Then retry the build.

**Comment by iman2420** [comment]
Yeah. i find it. its relate to **butterknife** plugin.

**Comment by fymo** [comment]
@iman2420 I'm facing the same problem, what was the solution?

**Comment by Zhuinden** [comment]
@fymo removing ButterKnife gradle plugin, and using the annotationProcessor + implementation version of adding it to project instead.
