### ISSUE TITLE
Realm throwing LIMITS_EXCEEDED frequently after updating it 4.2.0 to 4.3.0|4.3.1

### ISSUE THREAD

**Issue by ghost** [realm/realm-java#5732]
Questions: Why this exception took place after updating realm from 4.2.0 to 4.3.+ , it was working absolutely fine before that even no syncing issue was there but now it is so frequent.

Bugs: Realm is throwing the LIMITS_EXCEEDED  exception 

ObjectServerError Error Message null, LIMITS_EXCEEDED(104)
Connection reset by peer
	at io.realm.SyncSession.notifySessionError(SyncSession.java:178)
	at io.realm.SyncManager.notifyErrorHandler(SyncManager.java:324)
	at dalvik.system.NativeStart.run(Native Method)

## Goals
We need sync of data whether there is connection or not. 

## Expected Results
Syncing should work whether there is active internet connection or not 

## Actual Results
Device was committing location based data so frequently, there was a connection lost for more than 1 hour, so there can be 700-800 commits without internet, and when internet was reconnected the exception took place

FYI: On release version 4.3.0 and 4.3.1 there was an issue that whenever internet was disconnected it was throwing badintent error and sync was stopped after that, but it was not found on 4.3.2 or above realm version but the LIMITS_EXCEEDED is consistent after 4.3.0.

ObjectServerError Error Message null, LIMITS_EXCEEDED(104)
Connection reset by peer
	at io.realm.SyncSession.notifySessionError(SyncSession.java:178)
	at io.realm.SyncManager.notifyErrorHandler(SyncManager.java:324)
	at dalvik.system.NativeStart.run(Native Method)

## Steps to Reproduce
Make 700-800 commit around 272 bites of data, without internet connection.

## Code Sample
1. Create a sync user
1. Create realm object of around 272 bites of data
1. Start committing the data after each 5 second.
1. Disconnect the internet for more than 1 hour.
1. Turn on the internet connection now.

## Version of Realm and Tooling
* Realm Object Server Version: 2.4.4
* Flavor:
  * [ ] Professional
* Server OS & Version: Ubuntu 16.0.4
* Client SDK Version From where issue was found: 4.3.0
* Current Client SDK Version: 4.3.3
* Client OS & Version: 19

**Comment by anujjpandey** [comment]
Guys Any update..!

**Comment by Zhuinden** [comment]
@nhachicha

**Comment by cmelchior** [comment]
Hi @anujjpandey Thanks for the detailed bug report. I have forwarded it to our sync team as it looks like some kind of problem in the underlying protocol

**Comment by anujjpandey** [comment]
```
 new SyncConfiguration
                        .Builder(user, url)
                        .directory(syncDir)
                        .modules(new SharedSyncModule())
                        .name(REMOTE_SHARED_DIRECTORY + ".realm")
                        .schemaVersion(BuildConfig.REALM_VERSION)
                        .errorHandler(new SyncSession.ErrorHandler() {
                            @Override
                            public void onError(SyncSession session, ObjectServerError error) {
                                AppLoger.e(Tags.REALM_ERROR, " " + error.getErrorMessage());
                                error.printStackTrace();
                               
                            }
                        }).waitForInitialRemoteData().build();
  
```

**Comment by anujjpandey** [comment]
@cmelchior any update...!

**Comment by cmelchior** [comment]
Hey @anujjpandey 
Sorry for the late response. I had a talk with our Sync team, but unfortunately, the error you are seeing can be the result of multiple things and unfortunately the error codes are not fine-grained enough to tell the difference, which is something we are rectifying. 

In the meantime, is it possible for you to turn on `trace` logging on the server and send the output? If you want to keep it private you can send it to help@realm.io. Thanks.

**Comment by anujjpandey** [comment]
hey @cmelchior  we are watching our server log for the same issue but didn't getting anything also now the error message got changed, I'm no more able to see LIMITS_EXCEEDED, now it is

```
JSON_EXCEPTION(1)
End of input
	at io.realm.SyncSession.notifySessionError(SyncSession.java:177)
	at io.realm.SyncManager.notifyErrorHandler(SyncManager.java:324)
	at dalvik.system.NativeStart.run(Native Method)
```

**Comment by nhachicha** [comment]
Hi @anujjpandey still experiencing the issue with the latest release (`5.0.0`)? do you see any warnings/ errors before the `notifySessionError`? it could be a proxy/HTTP error that could not be parsed into JSON

**Comment by anujjpandey** [comment]
Not updated it to 5.0.0 as the object server require for it is on beta mode and no idea about stability of it.

**Comment by cmelchior** [comment]
Hi @anujjpandey 5.0.0 is now stable. Can you upgrade and see if you still see this error?

**Comment by bmunkholm** [comment]
@anujjpandey Are you still having the issue?

**Comment by cmelchior** [comment]
I have seen this a few times when doing unrelated testing, but have not been able to reproduce it yet.
