### ISSUE TITLE
Typo in the docs #initial-downloads

### ISSUE THREAD

**Issue by melnibon** [realm/realm-java#5734]
Hi,
There seems to be a typo in the documentation https://realm.io/docs/java/latest/#initial-downloads. The right method is `waitForInitialRemoteData()` instead of `waitForRemoteInitialData()` (2 occurrences, in the text and in the example): https://github.com/realm/realm-java/blob/615d9a0e5209adf42f84bb3a32f1e1bb55a4eb65/realm/realm-library/src/objectServer/java/io/realm/SyncConfiguration.java#L821

And there is an unnecessary `;` at the end of line in the example.
Best wishes,
Pierre

**Comment by cmelchior** [comment]
Hi @melnibon 
Thanks for noticing. It should be fixed shortly.
