### ISSUE TITLE
ExponentialBackoffTask reduce waiting time when connection is back

### ISSUE THREAD

**Issue by nhachicha** [realm/realm-java#5735]
The current `ExponentialBackoffTask` perform an indefinite retry (except for the `logout` query) when there's a network issue. This is suboptimal since we do have a network listener that we rely on internally to hint to Sync client that the connection might be re-established to resume sync, we can use this event to retry immediately rather than waiting for the wait the `ExponentialBackoffTask` is undergoing

**Comment by Zhuinden** [comment]
Your jobqueue doesn't pause when network is not available? 😮 ❓ ❗️

**Comment by nhachicha** [comment]
@Zhuinden no, for now, it's not attached to the network listener, the `exponential` part, prevents it from hammering the network stack with queries (and drain battery), but it also penalises use cases where the network is re-established while waiting to retry

**Comment by Zhuinden** [comment]
Hmm I worked too much with Android Priority JobQueue then, one time I wrote a job queue and it had pause but not retries :smile:

**Comment by cmelchior** [comment]
Fixed in `4.3.4`
