### ISSUE TITLE
Realm Issues

### ISSUE THREAD

**Issue by hmedat2008** [realm/realm-java#5740]
Since there are no replies for my issues here: 

https://github.com/realm/realm-java/issues/5634
https://github.com/realm/realm-java/issues/4176

Is That correct to clear data once we face these crashes?

**Comment by cmelchior** [comment]
@hmedat2008 I'm not sure what the question is? Deleting the file and recreate it from the server would fix both the issues mentioned if that is what your asking?

**Comment by hmedat2008** [comment]
@cmelchior i'm facing the two crashes in the fabric and still they didn't fix. 
Our user uninstall then install the app to solve these issues

**Comment by bmunkholm** [comment]
I'm closing this, as creating another issue in reference to two other issue doesn't help anyone.

**Comment by hmedat2008** [comment]
?

**Comment by bmunkholm** [comment]
@hmedat2008 What is the question? The point is this issue doesn't help resolve the other issues. Please pursue those issues separately. Creating this umbrella issue is not helping.
