### ISSUE TITLE
Different results after rearranging query conditions

### ISSUE THREAD

**Issue by gartesk** [realm/realm-java#5748]
Hello there!

I'm having a problem with using complex conditions in RealmQuery. 
I'm trying to build the condition `(A and (B or C)) or D`, but the results seem to include only items satisfying the left part (before the second 'or'). However, if I rearrange the conditions as `((B or C) and A) or D` it works as expected.

I'd really appreciate if someone pointed out what am I doing wrong here.

Gist: https://gist.github.com/gartesk/df072f5c3002a23ff723a6b2f8d6c063

Realm version: 4.3.4 (also reproduced it on 3.7.2)
Realm sync feature enabled: no
Android Studio version: 3.0.1
Which Android version and device: x86 emulators with API 22-26

**Comment by tgoyne** [comment]
This might be caused by https://github.com/realm/realm-core/pull/2953.

**Comment by clementetb** [comment]
Closing due inactivity. Please comment in case you get more information and the issue still persists
