### ISSUE TITLE
Verify if Realm works on Chromebook

### ISSUE THREAD

**Issue by Zhuinden** [realm/realm-java#5749]
https://support.google.com/chromebook/answer/7021273?hl=en

Chromebooks can run Android apps now, but does it actually work?

**Comment by cmelchior** [comment]
Yes, we should probably verify that. Now, to find a Chromebook 😄

**Comment by Zhuinden** [comment]
Yeah, unfortunately I don't have one at my disposal either 😄

**Comment by Zhuinden** [comment]
It probably works.
