### ISSUE TITLE
RealmList<Integer / String / ...>

### ISSUE THREAD

**Issue by an-k** [realm/realm-java#575]
Dear realm-Team, 

I'm really impressed by Realm and I do like the way you're providing support and solutions on github, SO and gGroups! I like working with Realm - however there are three really big drawbacks for me:

1) No model-instantiation by `= new ...` - I know you're on it. I can't wait for this! Do we have to wait for the "whole" JSON-Upgrade or will there be an earlier release providing this feature?

2) No model-passing across threads. That's hindering all the great benefits of EventBus and Android Priority Job Queue. But I read that it will be possible in the further versions and I'm looking forward on this.

3) **The reason for this issue:**
In my model class I'm allowed to have primitive fields as well as object fields of objects that extend `RealmObject`.
But I'm not allowed to have a field type like `RealmList<Integer>` or `RealmList<String>`.
However it is possible to work around this by

``` java
RealmList<RealmString> names;
```

and

``` java
public class RealmString extends RealmObject {
private String name;
// getter & setter
```

It works but it's _really_ ugly and should be unnecessary in my opinion.
Is there any improvement planned regarding this?

Thanks again for your great work - I'm glad Realm helps me developing my app!

--- 

Related PRs:
 - [ ] API design (#4165)
 - [ ] Implementation (#5031)

**Comment by jenzz** [comment]
Can I ask what the current state and/or priority of this feature request is?
Or: What is the recommended workaround for now?

**Comment by mpost** [comment]
I agree that this is a worthwhile feature. +1.

**Comment by PeterKomoot** [comment]
Yes, please

**Comment by kboyarshinov** [comment]
+1

**Comment by kaushikmukunda** [comment]
Would help solve issues like http://stackoverflow.com/questions/28733024/gson-deserialization-of-liststring-into-realmlistrealmstring 
+1

**Comment by FHellmann** [comment]
+1

**Comment by theyann** [comment]
+1 for the List of primitive and also +1 for the Enums.
I'm actually kinda stuck now as I have a JSON with a list of strings that needs to go to the DB, not quite sure yet how to deal with that.

**Comment by RobertoArtiles** [comment]
+1

**Comment by kbpontius** [comment]
+1

**Comment by jmachete** [comment]
+1

**Comment by marianmoldovan** [comment]
+1

**Comment by theostanton** [comment]
+1

**Comment by eygraber** [comment]
+1

**Comment by harish1312** [comment]
A list of Strings is a very common use case for JSON responses. When you are given an array of Strings such as 

"phoneNumbers":["000-000-0000", "111-111-1111"] 

and you need to store it in the database, you need a list of Strings.

Implementing a workaround for every instance of a JSONArray of Strings would be bloated and ugly, unless I'm not understanding the workaround correctly. Can I create a RealmString once and use it in place of String everywhere that I would need a RealmList of Strings? How would I get RetroFit (REST library from Square) to play nice with such an implementation?

In any case, having this issue resolved would simplify the code and it seems that many people are looking for the same feature. Perhaps the priority of this feature should be increased over something else.

**Comment by kneth** [comment]
@harish1312 In the documentation (http://realm.io/docs/java/latest/#other-libraries) you can read on how to use Realm with RetroFit and GSON.

**Comment by theCodingWizard** [comment]
+1

**Comment by yoavst** [comment]
+1

**Comment by LouisCo** [comment]
+1

**Comment by dulakm** [comment]
+1

**Comment by azizj1** [comment]
+1

**Comment by pavanjaju** [comment]
+1

**Comment by jmodrako** [comment]
+1

**Comment by jk2K** [comment]
+1

**Comment by ganlaw** [comment]
+1

**Comment by skptl** [comment]
+1

**Comment by tehwayne** [comment]
+1

**Comment by subhasha1** [comment]
+1

**Comment by natanloterio** [comment]
+1

**Comment by alirezaaa** [comment]
+1

**Comment by mmvicsonvictor** [comment]
+1 This is a very important one.

**Comment by ianrumac** [comment]
Please stop with +1s. It's just spamming everyone and won't speed up anything. They understand it and they said they're on it, but it needs a lot of time to be implemented since it spans across multiple teams. If you want more info, join Realm office hours next time or email them directly.

**Comment by rajyvan** [comment]
+1

**Comment by zsavely** [comment]
+1

**Comment by jaivikram** [comment]
+1

**Comment by davroux** [comment]
+1

**Comment by oiramcro** [comment]
+1

**Comment by HappyDr0id** [comment]
+1 of course

**Comment by gabuchan** [comment]
+1

**Comment by AlexAlbala** [comment]
+1

**Comment by gorje001** [comment]
+1

**Comment by laurentiuonac** [comment]
+1

**Comment by pandringa** [comment]
+1

**Comment by claudioredi** [comment]
+1

**Comment by riyase** [comment]
+1

**Comment by tgbarker** [comment]
+1

**Comment by skhaz** [comment]
+1

**Comment by pratamawijaya** [comment]
+1

**Comment by AamirAbro** [comment]
+1

**Comment by vergauwen-simon** [comment]
+1

**Comment by sam33rdhakal** [comment]
+1

**Comment by paulpv** [comment]
+1

**Comment by dan4ik95dv** [comment]
+1

**Comment by CDRussell** [comment]
I'll +1 for notifications.

**Comment by arshakavag92** [comment]
+1

**Comment by dlet24** [comment]
+1

**Comment by hendry64** [comment]
+1

**Comment by bclymer** [comment]
For any Kotlin users out there who don't want to manage a large tree of connected objects, I've been using this. 

https://gist.github.com/bclymer/f569fffb41bab046c2d1

It creates a single `RealmObject` by storing the `Int`s or `Long`s as a comma delimited `String`. Then it uses an extension function to recreate the `List<Type>`

**Comment by MGaetan89** [comment]
+1

**Comment by erakitin** [comment]
+1

**Comment by pavel-mukhanov** [comment]
+1

**Comment by lman** [comment]
+1

**Comment by MGaetan89** [comment]
In #1652, a workaround was provided until it is supported in realm.
I don't think it was given here, so here it is: https://gist.github.com/cmelchior/1a97377df0c49cd4fca9

**Comment by SilkSama** [comment]
+1 like everyone ;-)

**Comment by pauloavelar** [comment]
+1

**Comment by ruclip** [comment]
+1

**Comment by kim-montano** [comment]
+1

**Comment by xdgimf** [comment]
+1

**Comment by saityoukou** [comment]
+1

**Comment by mehrad-rafigh** [comment]
Why isn't this supported until now? Definitely +1

**Comment by Crysis21** [comment]
+1

**Comment by relaxedSoul** [comment]
+1

**Comment by radi-ratlh** [comment]
+1 for this essential feature.

**Comment by pbodsk** [comment]
+1

**Comment by shmidt** [comment]
+1

**Comment by paulpv** [comment]
A year and a quarter later this issue is still open and has ~75 votes.
Seems like kind of a high important issue.

**Comment by pedrox-3w** [comment]
+1

**Comment by alhazmy13** [comment]
+1

**Comment by wwwlight** [comment]
+1

**Comment by everyun** [comment]
+1

**Comment by silva96** [comment]
+1

**Comment by Queatz** [comment]
+1

**Comment by mithrann** [comment]
+1

**Comment by ZherebtsovAlexandr** [comment]
+1

**Comment by Waboodoo** [comment]
+1

**Comment by batista-mihai** [comment]
+1

**Comment by dbauduin** [comment]
+1

**Comment by dhenry** [comment]
+1

**Comment by marcelohd** [comment]
Will implements ? `RealmList<RealmString> strings;` retrofit recongnize as object. I Need String

**Comment by sstoyanova** [comment]
+1

**Comment by kimbeejay** [comment]
++i

**Comment by ilyator** [comment]
+1

**Comment by harryh27** [comment]
+1

**Comment by doubleDragon** [comment]
+1

**Comment by jagtejsodhi** [comment]
+1

**Comment by micronax** [comment]
+1

**Comment by abohomol** [comment]
+1

**Comment by chmoder** [comment]
+1

**Comment by ramirorinaldi** [comment]
+1

**Comment by Alviere** [comment]
+1

**Comment by orium-dev** [comment]
+1

**Comment by Zhuinden** [comment]
This is pretty much **the** only feature in Realm that's still missing for it to be easy to use for any use-case. I wonder what's up with it.

**Comment by Rakatan** [comment]
+1

**Comment by alexaccandr** [comment]
+1

**Comment by kneth** [comment]
@Zhuinden We are currently focusing on support, bugs and P1 issues. Don't worry, we haven't forgot the P2 issues, and we hope to work on them very soon.

**Comment by neokree** [comment]
+1

**Comment by Dima564** [comment]
+1

**Comment by Zhuinden** [comment]
@kneth I'm just surprised this is not P1.

**Comment by manuelrego27** [comment]
+fucking one, add a wrapper class in the meanwhile so we don't have to do it at least

**Comment by phearme** [comment]
++

**Comment by zzerk** [comment]
+1

**Comment by RJFares** [comment]
+1

**Comment by feludens** [comment]
+1

**Comment by DaveInga** [comment]
+1

**Comment by kosmonastya** [comment]
+1

**Comment by tomaslad** [comment]
+1

**Comment by droidizer** [comment]
+1

**Comment by theisegeberg** [comment]
+1

**Comment by DanMorganiOS** [comment]
+1

**Comment by imp8468** [comment]
+1 for the List of primitive

**Comment by wengelef** [comment]
+1

**Comment by slyfox4** [comment]
+1

**Comment by paulimfavarato** [comment]
+1

**Comment by hari2109** [comment]
+1

**Comment by nimitsolanki** [comment]
+1

**Comment by dawidhyzy** [comment]
+1

**Comment by caman9119** [comment]
+1

**Comment by iguerendiain** [comment]
+1

**Comment by jpmcglone** [comment]
+1

**Comment by angcyo** [comment]
+1

**Comment by sergiomarquesmoura** [comment]
+1

**Comment by andriipanasiuk** [comment]
+1

**Comment by giaotuancse** [comment]
+1

**Comment by b-raines** [comment]
How is this still not supported?!?

**Comment by hasanabuzayed** [comment]
+1

**Comment by henriquedesousa** [comment]
+1

**Comment by MGaetan89** [comment]
Can someone from the team lock this conversation until there is some news? For the moment it's just spamming everyone watching.
If someone else want to follow it, there is a "Subscribe" button on the right...

**Comment by bmunkholm** [comment]
Everyone should really get used to using the nice new smileys in the top description field of the issue :-) But we will Lock this for now. 
This feature is among a handfull of top features that we hope to take on next. We will however give the current 1.0 a bit of peace to ensure stability before we push a lot of new features.

**Comment by kneth** [comment]
See also http://stackoverflow.com/questions/39804941/what-the-best-way-to-use-liststring-in-realm-android

**Comment by cmelchior** [comment]
Work in Realm Core can be tracked here: https://github.com/realm/realm-core/issues/1881
