### ISSUE TITLE
Fail when opening link in Readme.md

### ISSUE THREAD

**Issue by ppaulojr** [realm/realm-java#5753]
#### Goal

I want to use the README file to download Android documentation

#### Expected Results

Valid link

#### Actual Results

Points to an empty page https://realm.io/docs/java/#installation

#### Steps & Code to Reproduce

Click the link in the README.md

#### Code Sample

```java

just_check_for_deadlinks();

```

#### Version of Realm and tooling
Realm version(s): Latest

Realm sync feature enabled: no

Android Studio version: Latest

Which Android version and device: Any

**Comment by Zhuinden** [comment]
Yep, should be https://realm.io/docs/java/latest/#installation

**Comment by cmelchior** [comment]
Thanks for reporting this. The link should have been fixed.
