### ISSUE TITLE
Help with frequently updated realm objects (specifying the listener more precisely?)

### ISSUE THREAD

**Issue by ursusursus** [realm/realm-java#5754]
Hi, I have this case, where I have a Library screen with list of realm objects, diffed via asChangesetObservable. 

```
mRealm.where(LibraryBook.class)
                .equalTo(LibraryBookFields.BOOK.TYPE, bookType)
                .sort(LibraryBookFields.OPENED_TIMESTAMP, Sort.DESCENDING,
                        LibraryBookFields.ADDED_TIMESTAMP, Sort.ASCENDING)
                .findAllAsync()
                .asChangesetObservable()
                .filter(change -> change.getCollection().isLoaded());
```

**My problem is that sometimes updates happen very quickly, for example in case of downloading a file, I update "download progress" field realm. This in turn triggers my observable and redraws my list.**

**The problem is that in that Library screen list I dont care about progress value, only progress status changing started / success / error, etc. also a realm field.** 

Is there a way to tell that changed or somehow specify the listener or black list some fields? Without this I am redrawing recyclerview (even tho only 1 item via notifyItemChanged, but still) on the background for no reason.

I also tried pausing on onPause/onResume, via proxying the CollectionChange to BehaviourSubject and unsubscribing from it in onPause, and then when view comesback in onResume, it will get that last emit. However this also is buggy as I get diff against the last realm state, not the state when I paused at, which leaves my recyclerview messed up with multiple duplicate items etc.

So either I keep all the changesets, which is not really cool in terms of memory, and then apply some compacting logic (I would get n-times notifyItemChanged(0), or somehow add logic to notifyDataSetChanged in onResume, or force possible detach the objects and do diffing my self)

_Not getting notified in the cases I dont care about would be the best, then Id be cool with being updated on the background aswell because its not very infrequent_

Thanks

**Comment by Zhuinden** [comment]
> Without this I am redrawing recyclerview (even tho only 1 item via notifyItemChanged, but still) on the background for no reason.

Actually, yes, if you use `RealmRecyclerViewAdapter`'s constructor as `super(results, true, false)` and use a `RealmObjectChangeListener` in your `bindViewHolder` on your managed RealmObject.

There, you get exact field changes by `"string"` field names, and can ignore whichever you are not interested in.

**Comment by ursusursus** [comment]
how can I see what field changed? 

```
book.addChangeListener(new RealmChangeListener<LibraryBook>() {
            @Override public void onChange(LibraryBook realmModel) {
            }
        });
```

comparing book vs realmModel instances would result in same data, no?

**Comment by ursusursus** [comment]
If I 

```
public void onBindBookViewHolder(ViewHolder holder, int position) {
        LibraryBook book = getBookAt(position);
        if (book != null) {
            book.removeAllChangeListeners();
            book.addChangeListener((RealmObjectChangeListener<LibraryBook>) (newLibraryBook, changeSet) -> {
                if (changeSet != null) {
                    String[] changedFields = changeSet.getChangedFields();
                    for (int i = 0; i < changedFields.length; i++) {
                             //
                    }
                }
            });
            holder.bindTo(mContext, book);
        }
    }
```

Will this leak the listener? Since realmResults.get() (transitively in getBookAt) creates a new instance everytime, there fore no way to remove the listener unless I cache the object?

**Comment by cmelchior** [comment]
The listener will be removed once the Book object is GC'ed, so no, it shouldn't leak. 

And yes, adding a dedicated Realm Object Change Listener would be the way to work around it.

**Comment by ursusursus** [comment]
Honestly @cmelchior its really wonky solution because that listener notifies only the direct fields, and my objects have several realm object references, id need to setup like 5, and ofc it does not scale automatically.

Would it be real trouble for changeset listener to carry the field names as in the object listener?

Btw about that gc, isnt that bad? Okay it doesnt get leaked but will be elligible for gc once onBindHolder finishes, and since Realmresults.get() returns new instance every time, I need to add a HashMap cache aswell

Btw

**Comment by Zhuinden** [comment]
You actually don't need a hashmap cache if you put the RealmObject in a `.setTag(R.id.your_custom_id, realmObject)` using 

``` xml
<?xml version="1.0" encoding="utf-8"?>
<resources>
    <item type="id" name="item_key"/>
</resources>
```

Though if you're listening to deep hierarchy then you might want a... set?

**Comment by ursusursus** [comment]
@Zhuinden thats even worse, that creates sparsearray per each view

**Comment by Zhuinden** [comment]
I think each is an overstatement. ViewHolders are re-used.

**Comment by ursusursus** [comment]
So? 5 sparsearrays maps of 1 item, is worse for memory than 1 sparsearray of 5 items

**Comment by Zhuinden** [comment]
Then just use `view.setTag(realmObject)` if creating 12 sparse arrays bothers you

``` java
    /**
     * Sets the tag associated with this view. A tag can be used to mark
     * a view in its hierarchy and does not have to be unique within the
     * hierarchy. Tags can also be used to store data within a view without
     * resorting to another data structure.
     *
     * @param tag an Object to tag the view with
     *
     * @see #getTag()
     * @see #setTag(int, Object)
     */
    public void setTag(final Object tag) {
        mTag = tag;
    }
```

**Comment by ursusursus** [comment]
Doesnt viewholder instance use that?

**Comment by Zhuinden** [comment]
no

**Comment by ursusursus** [comment]
Okay sorry my bad, its what has been used in ListView days for holder caching. Either way 5 listeners is more annoying than the cache issue. Okay Ill try it

**Comment by cmelchior** [comment]
I assume the above answered your question. If not feel free to reopen.
