### ISSUE TITLE
Hello I would like to collaborate as a translator to Spanish, which is my native language

### ISSUE THREAD

**Issue by UlisesTJ** [realm/realm-java#5762]

**Comment by knz** [comment]
@UlisesTJ https://github.com/cockroachdb/cockroach/issues/23038#issuecomment-368220870

**Comment by cmelchior** [comment]
Hi @UlisesTJ 
@knz excellent response pretty much mirrors what I was going to say. While your offer is appreciated, the only place that is suitable for translation is really our website docs, which are not part of this open source repo.

So I'll be closing this issue, but if you find a more suitable area where you want to contribute, feel free to create an issue and/or reach out.
