### ISSUE TITLE
Realm crashes after importing a realm file

### ISSUE THREAD

**Issue by Bridouille** [realm/realm-java#5765]
#### Goal

> Export / Import a realm database

#### Expected Results

> Ability to write the content of `default.realm` in a file. Ability to take the content of a file and write it to `default.realm`

#### Actual Results

> 
W/google-breakpad: ### ### ### ### ### ### ### ### ### ### ### ### ###
W/google-breakpad: Chrome build fingerprint:
W/google-breakpad: 2.4.2-debug
W/google-breakpad: 29
W/google-breakpad: ### ### ### ### ### ### ### ### ### ### ### ### ###
A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 14669 (rvaltimer.debug

#### Steps & Code to Reproduce

I'm exporting a realm database to a file. With:
```
// Export
val file = File(context.filesDir, "default.realm")
outputStream.write(Okio.buffer(Okio.source(file)).readByteArray())

// Import
val localFile = File(context.filesDir, "default.realm")
                    
val bufferedSink = Okio.buffer(Okio.sink(localFile))
bufferedSink.writeAll(Okio.source(stream)) // stream is an InputStream with my selected file

val config = RealmConfiguration.Builder()
                            .schemaVersion(4)
                            .migration(Migration())
                            .build()

Realm.setDefaultConfiguration(config)
```

So the export works fine I can retrieve a file with my default.realm content.
The import works fine as well, the thing is when I try to query realm after that (from another fragment somewhere in my app after doing the import), it simply crashes, I'm wondering if there is a way to tell realm "hey the default.realm file has changed, reload it" or something like that. Or if there is another way to import a realm database from a file, I'll take it.

Also following this, Is there a way to sanity check that a file is a valid realm database? In my use case I'm letting the user pick a file and basically re-import / restore the state of his database, and in case I pick a random file then realm crashes.

After the crash, when the app restarts it works well and the database is well imported.

#### Version of Realm and tooling
Realm version(s): 4.3.3 ?

Realm sync feature enabled: no

Android Studio version: 3.0.1 ?

Which Android version and device: 8.0 (Oero) ?

**Comment by Zhuinden** [comment]
1.) use Realm.writeCopyTo

2.) you can't just overwrite an open Realm and expect it to work, it's memory mapped and stuff

**Comment by Bridouille** [comment]
1- Thanks for the quick answer, is there any difference between Realm.writeCopyTo and what I'm doing with Okio?

2- I see. So the only alternative that I see now is to create a temporary realm file "tmp.realm" with my inputStream, then get ahold of the `Realm.getDefaultInstance()`, perform a `.deleteAll()` and then query EVERY class that I have in my `tmp.realm` and `copyToRealm` into the second one, would that be a viable solution ?

**Comment by Zhuinden** [comment]
1.) yes, writeCopyTo is guaranteed to work when Realm is open and also creates a compacted version

2.) No, but you need to ensure you close all open Realm instances (`Realm.getGlobalInstanceCount(config) == 0`) and then reopen it after overwriting the file.

**Comment by Bridouille** [comment]
Thanks for the insights! Going to switch to `Realm.writeCopyTo()` then.

I did a couple of tries while closing all realm instances and it works like a charm. Having instances opened was messing things up.

Thanks a lot 👍

**Comment by kalpeshp0310** [comment]
@Zhuinden Do you think below code will work for restoration?

	final Realm fromRealm = Realm.getInstance(new RealmConfiguration.Builder()
	  .directory(restorationFile.getParentFile().getAbsoluteFile())
	  .name(restorationFile.getName())
	  .build());

	if (Realm.getGlobalInstanceCount(Realm.getDefaultConfiguration()) == 0) {
	  Realm realm = Realm.getDefaultInstance();
	  realm.executeTransaction(realm1 -> realm1.deleteAll());
	  realm.close();
	  new java.io.File(Realm.getDefaultConfiguration().getPath()).delete();
	  fromRealm.writeCopyTo(new java.io.File(Realm.getDefaultConfiguration().getPath()));
	  fromRealm.close();
	} else {
	  fromRealm.close();
	  throw new IllegalStateException(
	    "Can not restore realm file as Realm instance is open.");
	}
