### ISSUE TITLE
Fatal Exception: io.realm.exceptions.RealmFileException

### ISSUE THREAD

**Issue by baldraider** [realm/realm-java#5767]
I'm trying to instantiate realm object using this code

```
public synchronized Realm provideRealm(){
        if (mRealm == null){
            Realm.init(mContext);
            RealmConfiguration config = new RealmConfiguration.Builder()
                    .name("abcdef.realm")
                    .schemaVersion(5)
                    .deleteRealmIfMigrationNeeded()
                    .build();
            mRealm = Realm.getInstance(config);
        } else if (mRealm.isClosed()){
            mRealm = null;
            provideRealm();
        }
        return mRealm;
    }
```

getting this exception and app is unable to open.

```
Fatal Exception: io.realm.exceptions.RealmFileException
Unable to open a realm at path '/data/data/com.myapp.app/files/abcdef.realm': Incompatible histories. Expected a Realm with no or in-realm history. (Incompatible histories. Expected a Realm with no or in-realm history) (/data/data/com.myapp.app/files/abcdef.realm) in /home/cc/repo/realm/release/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 91
```

How to solve this problem it is happeing in many devices like huawei, xiaomi...

#### Version of Realm and tooling
Realm version(s): 3.7.2

Realm sync feature enabled: no

Android Studio version: 3.0.1

Android version and device: 7.0, Galaxy S6 
--

**Comment by cmelchior** [comment]
Hi @hangonsushant 
It looks like the Realm "abcdef.realm" might already exist. Normally that error is thrown if you try to open a synchronized Realm the wrong way, but it sounds like you are not using the Realm Object Server.

In that case, my best guess is that the Realm file has become corrupted somehow. Is it something you can reproduce locally?

**Comment by hangonsushant** [comment]
No, I tried to produce the same error from my side but no success. I got the crash report from my crash analytics and from the users of my app. It happened automatically after months of use.

**Comment by hangonsushant** [comment]
How are the ways to the Realm file made corrupted?

**Comment by cmelchior** [comment]
The most common is if something is manipulating the Realm file while in use, but without access to a broken file, it is hard to tell exactly what could be wrong with it.

**Comment by hangonsushant** [comment]
What type of manipulation isyou considering?

**Comment by cmelchior** [comment]
Like deleting the file while it is still being used or restoring an old file from backup (overriding the current one), while it is in use.

**Comment by clementetb** [comment]
Closing due inactivity. Please comment in case you get more information and the issue still persists
