### ISSUE TITLE
How create user in Realm Object server?

### ISSUE THREAD

**Issue by lmdic** [realm/realm-java#5772]
I write Java application (server side) that create realm file add insert data to this realm DB. And I want my andoid clients to sync with this realm file.  I use realm ver.  **3.7.2**
So, first I need to create user on ROS. How I can do this? I official documentation:

https://realm.io/docs/java/latest/#users

When I click on link 
For more details about the server URL, please refer to our **authentication documentation**

It's not work. Nothing download.

**Comment by Zhuinden** [comment]
Is there any particular reason why you are using ROS 1.8.x and Realm 3.x instead of ROS 2.x and Realm 4.x?

**Comment by lmdic** [comment]
My java application for ROS and android app was created before 6 months. Then actual version of ROS was **1.8.3** and Realm **3.7.2**. This is a reason.

So, you advise me to update ROS to **2.x** and Realm to **4.x**?

**Comment by cmelchior** [comment]
Yes, you should upgrade if possible

**Comment by lmdic** [comment]
What about old android clients? They use Realm **3.7.2** ?  Is it will work with new Realm version **4.3.3**.  ?
Has Realm backward compatibility?

**Comment by bmunkholm** [comment]
Yes - the database will be upgraded locally in clients if needed.

**Comment by cmelchior** [comment]
I assume the above answered your question. If not, feel free to reopen.
