### ISSUE TITLE
How export realm to csv file?

### ISSUE THREAD

**Issue by lmdic** [realm/realm-java#5774]
How export realm to csv file?

**Comment by Zhuinden** [comment]
Manually.

**Comment by lmdic** [comment]
Is it possible from Realm Studio? Or has some another tool?

**Comment by Zhuinden** [comment]
I'd probably do it via the Java API and some CSV library.

**Comment by bmunkholm** [comment]
@lmdic Studio can do it for simple tables. Not relations.

**Comment by Asalle** [comment]
see also #2880
