### ISSUE TITLE
RealmQuery broken links in Realm Database Java docs

### ISSUE THREAD

**Issue by MDNion** [realm/realm-java#5775]
In the Queries section of the latest java docs for Realm database, 
https://realm.io/docs/java/latest#queries, there are two broken links to the RealmQuery API reference.

https://realm.io/docs/java/api/io/realm/RealmQuery.html  displays a 404 error page.

inks should be changed to https://realm.io/docs/java/latest/api/io/realm/RealmQuery.html

**Comment by Zhuinden** [comment]
https://realm.io/docs/java/latest/api/io/realm/RealmQuery.html

**Comment by cmelchior** [comment]
Thanks for reporting this. A fix has been merged and should be online soon.
