### ISSUE TITLE
[Realm-Studio]: A JavaScript error occurred in the main process

### ISSUE THREAD

**Issue by Drjacky** [realm/realm-java#5777]
#### Goal

> Running Realm Studio

#### Expected Results

> See the Realm Studio screen

#### Actual Results

![image](https://user-images.githubusercontent.com/2296754/36778948-870522ea-1c83-11e8-9b84-b6e091bb3741.png)

#### Version of Realm and tooling
Realm Studio version: 1.18.5

OS version: Windows 7 64-bit

**Comment by cmelchior** [comment]
Hi @Drjacky 
How did you run into this? Just by opening Realm Studio?

**Comment by Drjacky** [comment]
Hi @cmelchior 
Yes. Even by `Run as Administrator`.
![image](https://user-images.githubusercontent.com/2296754/36779263-a31dab0e-1c84-11e8-9538-17474001ee5c.png)

**Comment by cmelchior** [comment]
Ups, I missed you are using Windows 7. We unfortunately doesn't support Windows 7 at this point: https://stackoverflow.com/questions/47198349/realm-studio-for-windows-javascript-error

**Comment by Zhuinden** [comment]
Ya, I have a VirtualBox set up with Ubuntu 16.04 (amd64 version!! i have intel cpu but that is what you need) on it for this stuff.
