### ISSUE TITLE
How bind realm after import form CSV?

### ISSUE THREAD

**Issue by lmdic** [realm/realm-java#5778]
1. Start ROS ver. 2.0
2. Start Realm Studio
3. Connect to server.
4. Login by default user **realm-admin**
5. Create new user: **my-user**

Here result:

![users](https://user-images.githubusercontent.com/303539/36780319-4dacfbec-1c7b-11e8-94e3-2c32c1f1338d.png)

6. File->Create realm from CSV
As result I get this:

![csv](https://user-images.githubusercontent.com/303539/36779477-c3d83c9e-1c78-11e8-886a-49e872b0b552.png)

OK. Nice.
But the questions are: 

1. What I need to press to show new realm in list of realms?
2. How I can bind this realm (default.realm) to my custom user **my-user**?

**Comment by cmelchior** [comment]
Answered here: https://github.com/realm/realm-java/issues/5773
