### ISSUE TITLE
Better error when calling where with RealmModel

### ISSUE THREAD

**Issue by eygraber** [realm/realm-java#5779]
In Kotlin I sometimes end up in a situation where a type that I pass to `where` is treated as a `RealmModel` instead of a `RealmModel` subclass, but it's not always obvious from looking at the code. The problem is `where` eventually calls `Util.getOriginalModelClass` which get a superclass of null, causing a runtime NPE exception (`superclass.equals` because superclass is null).

It would be nice if there was a more informative message so that I could tell what was happening right away.

**Comment by Zhuinden** [comment]
with `realm.where<Something>().findAll()`:

**Comment by eygraber** [comment]
Yes, but `Something` is `T : RealmModel` and could get in a situation where the exact type is erased, and all that's left is `RealmModel`. It's not always easy to notice that, especially if there aren't any compiler errors.

**Comment by Zhuinden** [comment]
> could get in a situation where the exact type is erased, 

How did that happen? 😕

**Comment by eygraber** [comment]
I'm still trying to figure it out :see_no_evil: 

Basically in order to run a bunch of generic code, the starting type is `*`. Then I unsafe (but technically safe) cast it to `T` but all the compiler knows at that point is that `T` must be a `RealmModel`.

It's pretty complex and proprietary so I have to see if I can generalize it so I can share a sample.

**Comment by Zhuinden** [comment]
Sooo you end up with something like:

    fun <T: RealmModel> getStuff(realm: Realm) = realm.where<T>().findAll()

and it no longer works?

**Comment by eygraber** [comment]
There's a whole bunch of casting and tricks before, but what you wrote is basically the end result, just inlined and reified.

**Comment by cmelchior** [comment]
This is not something a compiler ever will be able to detect, the best we can do is to add a better exception, something like "RealmModel or RealmObject was parsed a function argument. This is not a proper Realm model class"

**Comment by eygraber** [comment]
That's what I was asking for (by message, I meant the exception message).

**Comment by cmelchior** [comment]
Fixed by #5796
