### ISSUE TITLE
Not show realm db in browser

### ISSUE THREAD

**Issue by lmdic** [realm/realm-java#5786]
Linux Mint 18

I create my custom Realm - **sg.realm**

Here screens:

![realms_sg](https://user-images.githubusercontent.com/303539/36796701-da118d68-1cae-11e8-8df6-c54103d0e604.png)
![user_real-admin](https://user-images.githubusercontent.com/303539/36796714-e3fd31ec-1cae-11e8-8b4e-c79cc61a04ef.png)
![sg_org](https://user-images.githubusercontent.com/303539/36796722-e768283c-1cae-11e8-9f7e-de8be71cfcaf.png)

As you can see in my Realm **sg.realm** has 2 organizations.
Nice.
The ROS 2.0 is started.
I success open `http://localhost:9080`

Nice.
But when I try to open `http://localhost:9080/sg`

I get error: 
`Cannot GET /sg`

Why I can't show my cusom db `sg.realm` in browser?

**Comment by cmelchior** [comment]
Do you mean you cannot open the Realm in the app or in the browser?
Note that the realm name is "sg" not "sg.realm"

**Comment by lmdic** [comment]
yes, I can't open my Realm in browser.

`http://localhost:9080/sg`

**Comment by bmunkholm** [comment]
@lmdic 
There is no http server for your realm. So it's expected. If you want to see or change the content of a realm you should use Studio and double click the realm as you have done above.
