### ISSUE TITLE
Can't create property RealmList<TranslatedString> by Realm Studio

### ISSUE THREAD

**Issue by lmdic** [realm/realm-java#5787]
Here my Realm object

```
public class LocalizedString extends RealmObject {
    private RealmList<TranslatedString> translations = new RealmList<>();
 
    public RealmList<TranslatedString> getTranslations() {
        return translations;
    }

}
```

I want to create this schema by Realm Studio
So here screenshots:

![step1](https://user-images.githubusercontent.com/303539/36804028-fe75c4cc-1cc1-11e8-877e-061be9e279fd.png)

But I get error:

![error](https://user-images.githubusercontent.com/303539/36804031-02a07ef2-1cc2-11e8-8f51-7a629900de54.png)

Why I can't create properties `RealmList<TranslatedString> translations`  ?

**Comment by Zhuinden** [comment]
You need to untick "Allow null values in the list".

It is not possible to support nullability of RealmList elements in linked type.

**Comment by lmdic** [comment]
If I untick "Allow null values in the list" the the result model will be:

```
public class LocalizedString extends RealmObject {
    @Required
    private RealmList<String> translations;

    public RealmList<String> getTranslations() { return translations; }

    public void setTranslations(RealmList<String> translations) { this.translations = translations; }
}
```

But I need the property **translations** to **not** be `@Required`. 
How I can do this?

**Comment by Zhuinden** [comment]
Hold on, then the type you specify should be `RealmList<String>`, not `RealmList<TranslatedString>`....

**Comment by lmdic** [comment]
I't unpossible because all our android and iphone client use this model: **not required** property `translations`

**Comment by Zhuinden** [comment]
`RealmList<T extends RealmModel>` does not support null elements.

**Comment by cmelchior** [comment]
It's unclear what exactly you are trying to accomplish as @Zhuinden said, there is a big difference between your list having `String` or `TranslatedString` in your model class. `String` values can be `null` but references to other `TranslatedString` cannot.

But we should update Realm Studio so you cannot change the nullability state for RealmModel references

**Comment by lmdic** [comment]
I user Realm Studio: Version 1.18.5

**Comment by lmdic** [comment]
I need to create the next POJO

```
public class LocalizedString extends RealmObject {
    private RealmList<TranslatedString> translations = new RealmList<>();
}

```

How I can do this by Realm Studio (ver. 1.18.5) ?

**Comment by Zhuinden** [comment]
In that case, `RealmList<TranslatedString>` cannot contain null elements.

**Comment by cmelchior** [comment]
Realm Studio has been updated to no longer show invalid combinations for the nullability flag. This should be part of the next release.
