### ISSUE TITLE
How create not required RealmList property

### ISSUE THREAD

**Issue by lmdic** [realm/realm-java#5788]
Android client: Realm version: **4.1.0**
ROS ver. **2.8.0**
Realm Studio ver. **1.18.5**

Organization is create in Realm by import from json.

Here POJO.

```
public class Organization extends RealmObject {
    @PrimaryKey
    private long id;
    private boolean ready = false;
    @Required
    private String name;
    private RealmList<RealmInt> recommendations;
}

public class RealmInt extends RealmObject {
  private int value;
}
```

When first time import orgranization from json the property `recommendations` is missing. First time the organization can not contain recommendations. **It's a normal situation**.
The recommendations can be update later. From another json.
That is a reason why I create property `recommendations` **WITHOUT** annotation `@Required`.

So I start my android app and login by admin credentials (download/upload). And as result it's sync with ROS.
As result on ROS success created my custom realm with all tables. Nice.
Now in Realm Studio I save model definition in java format.
And as result I get the next `Organizaion.java`

```
public class Organization extends RealmObject {
    @PrimaryKey
    private long id;
    private boolean ready = false;
    @Required
    private String name;
    @Required
    private RealmList<RealmInt> recommendations;
}

public class RealmInt extends RealmObject {
  private int value;
}
```

As you can see the property `recommendations` now has annotation `@Required`. Why?
As I describe earlier this is not required field.

**Comment by Zhuinden** [comment]
Doesn't really matter considering model RealmList is always required implicitly.

**Comment by lmdic** [comment]
So when I  import from json to create organization, this json must contain field `recommendations`.
Is I'm right?

**Comment by Zhuinden** [comment]
I think `recommendations: []` should work

**Comment by lmdic** [comment]
It's not good. Because in ROS 1.xx we has model with not anotation `@Required` in property `recommendations`. And it's work fine. I can't change this model. So I need some approach when property `recommendations` will be without annotation `@Required`

**Comment by Zhuinden** [comment]
`@Required` never did anything on a `RealmList<T extends RealmModel>`. It has no effect. That list cannot store nulls. It never could.

**Comment by cmelchior** [comment]
I have updated Realm Studio, so you can no longer set the nullability status of lists when referencing model classes. This should prevent this situation from happening in the future. It will be in the next release of Realm Studio
