### ISSUE TITLE
How get details http/webSockets logs when Realm create http request?

### ISSUE THREAD

**Issue by lmdic** [realm/realm-java#5798]
In my android client I set:

`RealmLog.setLevel(Log.VERBOSE);`

I have error on android client:

```
I/System.out(11361): srv    pxy <- cli HTTPSProxy: session valid: false
V/FA-SVC  ( 1709): Network upload failed. Will retry later. code, error: 0, javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.
I/System.out(11361): srv   <pxy>   cli HTTPSProxy: get stream exception java.net.SocketException: Socket is closed
I/System.out(11361): srv   <pxy>   cli HTTPSProxy: cleanup
V/FA-SVC  ( 1709): Upload scheduled in approximately ms: 1809994
D/REALM_SYNC(23915): Connection[1]: WebSocket::handle_http_response_received()
E/REALM_SYNC(23915): Connection[1]: HTTP: Failed to switch protocols (response status = 403)
I/REALM_SYNC(23915): Connection[1]: Connection closed due to error
D/REALM_SYNC(23915): Connection[1]: Reconnecting in 3492280 milliseconds
```

This information is not enough.  So I want to show details http logs when Realm send http request
How I can do this?

**Comment by lmdic** [comment]
Is Fiddler can help me?
https://www.telerik.com/fiddler

**Comment by cmelchior** [comment]
A proxy like Fiddler or Charles can help you intercept the HTTP traffic, so yes, they can be used for that. But note that the above is a WebSocket failure, and I don't think those tools can intercept that kind of traffic.

What version of ROS and Realm Java are you using? It could also be incompatible versions.

**Comment by lmdic** [comment]
ROS version: 1.8.3
Android Realm version: 3.7.2

**Comment by lmdic** [comment]
Can you advise some tool than can show detail logs of WebSockets from my android device to ROS? Or some sniffer maybe?
I need to understand why I get this error: 
```

D/REALM_SYNC(16953): Connection[1]: WebSocket::handle_http_response_received()
E/REALM_SYNC(16953): Connection[1]: HTTP: Failed to switch protocols (response status = 403)

```
Thanks.

**Comment by lmdic** [comment]
We found solution. The problem was not in our android realm code. The problem was in settings of network proxy. Our administrator help us. 
Thanks.
