### ISSUE TITLE
gradle build system cannot find libopencv_jav3.so

### ISSUE THREAD

**Issue by timurstarchenko** [realm/realm-java#5801]
Hello.
I use the PayCards_Android library in the project.
After connecting to the Realm project, the PayPards ceases to work, because  gradle build system cannot find libopencv_jav3.so
I'm using the version of Realm 4.3.4
Tested on android 7.1.1
Tell me what could be the problem?

Sorry for my English

**Comment by Zhuinden** [comment]
Is libopencv `armeabi`?

**Comment by timurstarchenko** [comment]
it seems not, is armeabi-v7a

**Comment by cmelchior** [comment]
Without knowing what kind of build failure you are seeing it is hard to speculate, but usually problems arise if libraries do not provide a 64-bit versions of their code as Realm do.

You can see https://realm.io/docs/java/latest/#faq-librealm-jni for the details, but the gist of it is to make sure to only include support for the architectures you have ABI's for.

You can also use ABI split to achieve this: https://realm.io/docs/java/latest/#faq-library-size

**Comment by cmelchior** [comment]
I assume the above solved your issue. If not, feel free to reopen.
