### ISSUE TITLE
Broken links for RealmBaseAdapter & RealmRecyclerViewAdapter

### ISSUE THREAD

**Issue by MDNion** [realm/realm-java#5802]
In the Adapters section, https://realm.io/docs/java/latest/#adapters, the links for RealmBaseAdapter & RealmRecyclerViewAdapter need to be adjusted to include /latest/ in their URLs.

https://realm.io/docs/java/adapter/io/realm/RealmBaseAdapter.html          --> 404
https://realm.io/docs/java/adapter/io/realm/RealmRecyclerViewAdapter.html  --> 404
https://realm.io/docs/java/latest/adapter/io/realm/RealmBaseAdapter.html          --> works
https://realm.io/docs/java/latest/adapter/io/realm/RealmRecyclerViewAdapter.html  --> works

**Comment by cmelchior** [comment]
Thanks for reporting this. I'll look into it.

**Comment by cmelchior** [comment]
It should be fixed now. The change should be online in ~ 15 minutes.
