### ISSUE TITLE
Data lost after restart application Realm version 4.1.1

### ISSUE THREAD

**Issue by haunguyen** [realm/realm-java#5803]
#### Goal

> What do you want to achieve?
I have issue with realm that make data lost after once time restart application. I used multple file realm with difference config and not manually delete data.
#### Expected Results

> ?

#### Actual Results

>  E.g. full stack trace with exception
User used app with large data ( maybe, i'm not sure about that ). After once restart application, all data lost. In the below code, I only init and compact realm into Application oncreate()
#### Steps & Code to Reproduce

> Describe your current debugging efforts.

#### Code Sample
try {
            Realm.init(this);
            initRealm();
            Realm.compactRealm(getRealmConfig());
            Intent intent1 = new Intent(context, BreastfeedingService.class);
            context.startService(intent1);
        } catch (Error e) {
            e.printStackTrace();
            outMemoryRealm = true;
        } catch (Exception e) {
            e.printStackTrace();
            outMemoryRealm = true;
        }

 public void initRealm() {
        String lastRealm = SharedPreferencesHelper.getStringValue(AppConstants.LAST_REALM);
        RealmConfiguration.Builder _config = new RealmConfiguration.Builder();
        _config.name(lastRealm + ".realm");
        _config.schemaVersion(CURRENT_REALM_VERSION);
        _config.migration(new MyRealmMigration());
        RealmConfiguration config = _config.build();
        realmConfigurationHashMap.put(lastRealm, config);
//        Realm.setDefaultConfiguration(config);
    }
> Your code here. Bigger samples should ideally be as separate Android Studio project, 
> in gists/repositories or privately at help@realm.io)

```

#### Version of Realm and tooling
Realm version(s): ?
classpath 'io.realm:realm-gradle-plugin:4.1.1'
Realm sync feature enabled: no
  
Android Studio version: ?
Android studio 3.0.1
Which Android version and device: ?
Android version 7.0 and 7.1.1

**Comment by cmelchior** [comment]
Without more information, it is pretty hard to speculate what is going wrong. It would be ideal if you could provide an example project showing what is wrong.

But Realm will not lose data by itself, so my guess that you are deleting the data somehow by accident, but where is impossible to say from the code you posted.

**Comment by haunguyen** [comment]
I still debug this issue, i'm not have detail about this. My application has 2 user repport about lost data, but i check some case data could not lost data.
 1. user 1 lost data after once time restart app, last session about 30 minute ago
 2. user 2 lost data after device is low battery, and reboot

I'm not sure about delete data, maybe when realm mapping data in memory, it can be error?
And if file realm is over maxsize 16MB( real size), it can be overload?

**Comment by cmelchior** [comment]
Realm has ACID properties, so once a `commitTransaction` succeeds, the data has been written to disk. There should be no chance of data loss after that, at least not because of that.

Also, the 16 MB limit is only pr. field in a model class. Your Realm can be as large as you want.

**Comment by Zhuinden** [comment]
@cmelchior caveat: `mmap()` will fail if the Realm file is larger than the total memory your device has.

This seems to come up if you insert 5000 elements in 5000 transactions on a background thread.

**Comment by cmelchior** [comment]
True. there is some caveats there, but that means hitting 400 MB on 32-bit devices and much much higher on 64 bit systems.

**Comment by clementetb** [comment]
Hi. Version 7 and upward of Realm had a significant updated underlying database engine that improves stability and performance. We recommend updating to version 10. Closing this issue as outdated please reopen if you experience it again.
