### ISSUE TITLE
Adding object to RealmList causes all objets in list to equal most recently added object

### ISSUE THREAD

**Issue by royherma** [realm/realm-java#5809]
#### Goal

Figure out the cause of this issue and if its fixable..

#### Expected Results

A `ReamList` with unique/correct objects

#### Actual Results

A `ReamList` with duplicate objects equal to the most recently (last added objects)

#### Steps & Code to Reproduce

I have for example three classes:

**Portfolio.java**
```
@PrimaryKey
String serverId;
RealmList<StockItem> items = new RealmList<StockItem>();

```

**StockItem.java**
```
StockItem.java
@PrimaryKey
String uid;
RealmList<Exchange> exchanges = new RealmList<Exchange>();

```

**Exchange.java**
```
String name = "";
String id = "";
RealmList<Long> xValues = new RealmList<>();
RealmList<Double> yValues = new RealmList<>();

```

This snippet works:

```
Portfolio portfolio = new Portfolio("some_id");
StockItem fb = new StockItem("fb");
StockItem aapl = new StockItem("aapl");
StockItem google = new StockItem("google");
portoflio.items.add(fb);
portoflio.items.add(aapl);
portoflio.items.add(google);

Resulting items in portoflio => [fb,aapl,googl]

```

This snippet **DOESN'T** works:

```
Portfolio portfolio = new Portfolio("some_id");
realm.insertOrUpdate(portfolio);
StockItem fb = new StockItem("fb");
StockItem aapl = new StockItem("aapl");
StockItem google = new StockItem("google");
portoflio.items.add(fb);
portoflio.items.add(aapl);
portoflio.items.add(google);

portfolio = realm.where(Portfolio.class).equalTo("serverid", "some_id").findFirst();

Resulting items in portoflio => [googl,googl,googl]

```

It seems that adding the `portfolio` to realm causes issues with adding items to it. Any ideas why this might be happening, or is this a bug?

#### Version of Realm and tooling
Realm version(s): Newest realm version as of March 7th, 2018

Realm sync feature enabled: No

Android Studio version: 3.0.2

Which Android version and device: ?
Emulator, nexus 5

**Comment by Zhuinden** [comment]
The StockItems you add *after* calling `insertOrUpdate`should have no effect, so the error is most likely somewhere else.

**Comment by royherma** [comment]
@Zhuinden what do you exactly mean by "no effect"? The size of the `items` array clearly changes depending on the amount of items I add to it, regardless if it was done before or after `insertOrUpdate`, however all of the items in the array hold the same values as the most recently added item.

**Comment by Zhuinden** [comment]
Well it should have no effect on what's in the Realm, considering you're creating new classes with `new __()` and you are not talking to a managed proxy, and you showed no indication that you'd be using `insertOrUpdate()` anywhere *after* the first insert.

**Comment by royherma** [comment]
I'm thinking it might be possibly related to the fact that a realm object cannot have a realm list of an object which old realm lists of another object? I tried creating another realm list for the "Portoflio" class which holds strings, and this issue didn't occur. Is it possible its related to that?

**Comment by cmelchior** [comment]
My guess is that your code is doing something not shown in the snippet:

```
Portfolio portfolio = new Portfolio("some_id");
realm.insertOrUpdate(portfolio); // This should have been portfolio = realm.copyToRealmOrUpdate(portfolio);
StockItem fb = new StockItem("fb");
StockItem aapl = new StockItem("aapl");
StockItem google = new StockItem("google");
portoflio.items.add(fb); // You are adding fb to the unmanaged copy, not the Realm object
portoflio.items.add(aapl); You are adding appl to the unmanaged copy, not the Realm object
portoflio.items.add(google); You are adding google to the unmanaged copy, not the Realm object

portfolio = realm.where(Portfolio.class).equalTo("serverid", "some_id").findFirst();

Resulting items in portoflio => [googl,googl,googl] // This must come from somewhere else
```

**Comment by cmelchior** [comment]
I assume the above solved your issue. If not, feel free to reopen.
