### ISSUE TITLE
Problems with partial sync tutorial app

### ISSUE THREAD

**Issue by jedelbo** [realm/realm-java#5811]
We assume that you have built the first version of the demo app without partial sync and have the data syncked with the cloud.

If you then go on and build the advanced app with partial sync, then it cannot sync with the cloud. You get logs like this:
```
03-07 09:22:29.139 4099-4099/io.realm.todo W/IInputConnectionWrapper: finishComposingText on inactive InputConnection
03-07 09:22:29.139 4099-4099/io.realm.todo W/IInputConnectionWrapper: finishComposingText on inactive InputConnection
03-07 09:22:29.214 4099-4150/io.realm.todo E/REALM_SYNC: Connection[1]: Websocket: HTTP response is 502-504
03-07 09:22:29.216 4099-4150/io.realm.todo W/REALM_JAVA: Unknown error code: 8
03-07 09:22:29.216 4099-4150/io.realm.todo E/REALM_JAVA: Session Error[realms://my-shopping-list.us1a.cloud.realm.io/items]: UNKNOWN(-1)
                                                         Bad WebSocket handshake response 502-504 received
03-07 09:22:30.070 4099-4150/io.realm.todo E/REALM_SYNC: Connection[1]: Websocket: HTTP response is 502-504
```
The app is running on Nexus 5X / Android 8.1.0

**Comment by jedelbo** [comment]
Newest info on this: When I run the application against a selfhosted ROS it works!

**Comment by cmelchior** [comment]
We discovered it was due to an incompatible Realm Cloud version. The lesson from this: We should include supported version of Realm Cloud in all changelog notes.
