### ISSUE TITLE
[Sync] Add API to create a schemaless Realm

### ISSUE THREAD

**Issue by nhachicha** [realm/realm-java#5812]
There are use cases in Sync where we need to wait for the schema to be synchronised by the server before opening the Realm:
- Read-only scenario (since we can't create an empty Readonly Realm with a schema), it needs first to exist with the corresponding schema
- In case of the new permission system, we may choose to start with an empty Realm to synchronise the permission schema from the server before start modifying it (to avoid working on a duplicate permission offline that might be corrected/removed by sync later)

**Comment by cmelchior** [comment]
`SyncConfiguration.readOnly()` and `SyncConfiguration.waitForInitialRemoteData()` in combination should solve this issue. Closing
