### ISSUE TITLE
Fatal signal 11 from copyToRealmOrUpdate

### ISSUE THREAD

**Issue by smithjake** [realm/realm-java#5815]
#### Goal

A crash free experience

#### Expected Results

My realm objects stay updated without crashing.

#### Actual Results

Intermittently and randomly, the app crashes and I get a realm trace that ends with a Java_io_realm_internal_UncheckedRow_nativeGetLong call.  No tombstone is written.  Let me know how I can provide more details for you.  

Java_io_realm_internal_UncheckedRow_nativeGetLong 547954833728
A/libc: Fatal signal 11 (SIGSEGV), code 1, fault addr 0x100000098 in tid 23300 (com.####)

#### Steps & Code to Reproduce

It happens randomly in the app.  I'm able to avoid the crash by commenting out the code that writes to realm.  These writes are happening from a background thread that is the response from an API call.

#### Code Sample

```java
realm.executeTransactionAsync(
         realm -> realm.copyToRealmOrUpdate(store)
);
```

#### Version of Realm and tooling
Realm version(s): 4.3.3

Realm sync feature enabled: no
Android Studio version: 3.0.1

Which Android version and device: Android 6.0, Nexus 5X

**Comment by cmelchior** [comment]
Unfortunately the above isn't much to go from. Is there any way you can reproduce this?

A couple of questions though: 

1) How often does it crash?
2) What is in the store variable? What does the model class look like?

**Comment by smithjake** [comment]
For anyone who ends up here in the future, this was due to a change listener that was not getting removed properly in some scenarios.
