### ISSUE TITLE
Asynchronous query exception

### ISSUE THREAD

**Issue by preyesm** [realm/realm-java#5837]
**Cannot create asynchronous query while in a write transaction in /Users/Nabil/Dev/realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_Collection.cpp line 274**

I have few doubts:
1. Change listener is attached to RealmResults A and RealmResults B, both retrieved from cache using singleton realm instance. 
2. After the API call result i am updating objectA using the same instance and the app crashes at the change listener of B with the above error.

Is this is the expected behaviour? and what is the best way to handle this? 
1. Should i make all executeTransaction as Async 
2. Should i maintain the order of api call so that only one change listener is being called at any point of time 
3. Should i maintain only 1 change listener per page?

**Comment by Zhuinden** [comment]
I think this can only happen (according to a repro case someone created) if you call `realm.executeTransaction` inside a RealmChangeListener's `onChange` method.

**Comment by preyesm** [comment]
@Zhuinden nope, i do not have any execute transaction within change listener. execute transaction happens whenever i get the result from API. I think using same realm instance for change listener and execute transaction is causing the issue. 
object b's change listener has the following code:

if (count != null) {
            if (count.getFollowerCount() == 0 && count.getFollowingCount() == 0) {
                binding.followFollowerLayout.setVisibility(GONE);
            } else {
                binding.followFollowerLayout.setVisibility(VISIBLE);
            }
        }
    }

whereas as per the stacktrace of crash, crash started at execute transaction block where i am trying to update the object A but it has ended up crashing in the change listener of object B.

Anyways after i remove the change listener of object B, it doesnt crash further. I shall continue with the same.

**Comment by Zhuinden** [comment]
> crash started at execute transaction block where i am trying to update the object A

where is that?

**Comment by preyesm** [comment]
else if (responseWrapper.response instanceof AgentGroups) {
                ApplicationDataHandler.getRealm().executeTransaction(new Realm.Transaction() {
                    @Override
                    public void execute(Realm realm) {
                        final String agentId = responseWrapper.request.getAsJsonObject().get("agentId").getAsString();
                        ((AgentGroups) responseWrapper.response).setAgentId(agentId);
                        realm.insertOrUpdate((AgentGroups) responseWrapper.response);
                    }
                });

**Comment by preyesm** [comment]
Stack trace is:

Last Exception Backtrace
--
0 | java.lang.IllegalStateException: Cannot create asynchronous query while in a write transaction in /Users/Nabil/Dev/realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_Collection.cpp line 274
1 | at io.realm.internal.OsResults.nativeStartListening(Native Method)
2 | at io.realm.internal.OsResults.a(OsResults.java:431)
3 | at io.realm.internal.OsResults.a(OsResults.java:438)
4 | at io.realm.cz.a(RealmResults.java:175)
5 | at com.agentdesks.android.crm.fragments.agent.AgentProfileFragment.setData**(AgentProfileFragment.java:420)**
6 | at com.agentdesks.android.crm.fragments.agent.AgentProfileFragment.lambda$onViewCreated$0$AgentProfileFragment(AgentProfileFragment.java:108)
7 | at com.agentdesks.android.crm.fragments.agent.AgentProfileFragment$$Lambda$0.onChange(Unknown Source)
8 | at io.realm.internal.ObservableCollection$c.a(ObservableCollection.java:40)
9 | at io.realm.internal.ObservableCollection$b.a(ObservableCollection.java:21)
10 | at io.realm.internal.ObservableCollection$a.a(ObservableCollection.java:65)
11 | at io.realm.internal.ObservableCollection$a.a(ObservableCollection.java:55)
12 | at io.realm.internal.j.a(ObserverPairList.java:109)
13 | at io.realm.internal.OsResults.notifyChangeListeners(OsResults.java:472)
14 | at io.realm.internal.SharedRealm.nativeBeginTransaction(Native Method)
15 | at io.realm.internal.SharedRealm.beginTransaction(SharedRealm.java:247)
16 | at io.realm.n.b(BaseRealm.java:389)
17 | at io.realm.bw.b(Realm.java:135)
18 | at io.realm.bw.a(Realm.java:1392)
19 | at com.agendesks.android.datahandler.k.a**(NetworkDataHandler.java:619)**
20 | at com.agendesks.android.datahandler.c$1.a(BaseDataHandler.java:32)
21 | at com.agendesks.android.datahandler.c$1.onResponse(BaseDataHandler.java:29)
22 | at com.agendesks.android.datahandler.net.b.deliverResponse(AbstractAgentDesksRequest.java:86)

(NetworkDataHandler.java:619) - code of execute transaction of object A
(AgentProfileFragment.java:420) - code of change listener of object B

**Comment by Zhuinden** [comment]
Interestingly, this means you can't reliably call `addChangeListener` inside a change listener either. That's what the stack trace says you're doing.

It's because `executeTransaction` can call RealmChangeListeners if the transaction  updated the Realm version.

A possible hacky solution would be to move that `addChangeListener` into a `handler.post`

**Comment by Zhuinden** [comment]
It says so right here:

```
at com.agentdesks.android.crm.fragments.agent.AgentProfileFragment.lambda$onViewCreated$0$AgentProfileFragment(AgentProfileFragment.java:108)
 at com.agentdesks.android.crm.fragments.agent.AgentProfileFragment$$Lambda$0.onChange(Unknown Source)

at io.realm.internal.OsResults.notifyChangeListeners(OsResults.java:472)
 at io.realm.internal.SharedRealm.nativeBeginTransaction(Native Method)
 at io.realm.internal.SharedRealm.beginTransaction(SharedRealm.java:247)
```

**Comment by preyesm** [comment]
Thanks for pointing it out @Zhuinden. Though we have no direct change listener calls inside the other, it could be because of two execute transaction occuring at the same time and calling their corresponding change listener at the same time.

**Comment by Zhuinden** [comment]
Calls to `executeTransaction` are blocking across threads, but if you start `executeTransaction` inside `executeTransaction` then you should get `nested transactions are not supported`
