### ISSUE TITLE
Realm Migration -Painful tasks upon non-uniform upgrade

### ISSUE THREAD

**Issue by TSG9876** [realm/realm-java#5845]
I would like to explore can the Realm Migration  for the intended RealmObject()  be restrict  to all the essential parameters be  written  once only  in the application or main activity only  incorporating the required version number also stated as singularity ?

Current Migration Practice for the upgrade for just one Realm Objects must ensure all the following be complete 

  val    version_no=1 --> propose defined just once in the application class where Realm.init(this) is executed 
 val       rec_config = RealmConfiguration.Builder()
                .name("Grocery_Rec.realm")
                .schemaVersion(version_no)
                .migration(Grocery_Realm_Migration())
                .build()

Currently I noticed that whatever fragment  or sub-activity having realm instance called  must also include      .migration(Grocery_Realm_Migration())   line in addition to the .schemaVersion(xx) defined.

Can't this "version_no" be  simplified and coded as an Global integer with just  the latest version number  be  defined as   .schemaVersion(version_no)  without the ever confusing .migration(xx) line . 

 I currently  solved this daunting  version_no keep track as one the POJO object return field integer having the latest number.
Any new schema upgrade , I just  alter the number to latest version  once only. This would be good if this could just be defined once in the Application class only ??

It would also be very tedious to search around every line in all the fragments and activities to hunt  for that  unique  particular realm instance called to make sure the  .migration(xx) is  added to avoid the App from Crashing .

 Real Painful task whenever an upgrade is required as not all the " tables" or RealmObject() in the complex App need to upgraded uniformly per se.

**Comment by cmelchior** [comment]
I'm not entirely sure what you mean? There definitely isn't a need to create a configuration every time you access the Realm.

The normal pattern is to do it in your `Application` subclass and then just set it as a default configuration, like:


```
public class MyApplication extends Application {
  @Override
  public void onCreate() {
    super.onCreate();
    Realm.init(this);
    RealmConfiguration config = new RealmConfiguration.Builder()
       // config parameters
      .build();
    Realm.setDefaultConfiguration(config);
  }
}


public MyActivity extends Activity {
  
  private Realm realm;

  @Override
  public void onCreate(...) {
    realm = Realm.getDefaultInstance();
  }
}
```

**Comment by TSG9876** [comment]
My view is simple if I have multiple realmObject  class under the realm projects , not all  are affected by the upgrade or migration , may be just one or two RealmObject class are affected , can your default configuration cater for such needs  especially on the .name( ) line? Example as below taken directly from guide whenever a config is needed in every fragment call.
 

RealmConfiguration myConfig = new RealmConfiguration.Builder()
  .name("myrealm.realm")
  .schemaVersion(2)
.migration(xx)---> must defined if there is migration  involving config related to myrealm.realm
  .modules(new MyCustomSchema())
  .build();

RealmConfiguration otherConfig = new RealmConfiguration.Builder()
  .name("otherrealm.realm")
  .schemaVersion(5)
  .modules(new MyOtherSchema())
  .build();

Realm myRealm = Realm.getInstance(myConfig);
Realm otherRealm = Realm.getInstance(otherConfig);

**Comment by TSG9876** [comment]
public class MyApplication extends Application {
  @Override
  public void onCreate() {
    super.onCreate();
    // The default Realm file is "default.realm" in Context.getFilesDir();
    // we'll change it to "myrealm.realm"
    Realm.init(this);
    RealmConfiguration config = new RealmConfiguration.Builder().name("myrealm.realm").build();-->singular only 
    Realm.setDefaultConfiguration(config); -one config only
  }
}

public class MyActivity extends Activity {
  @Override
  protected void onCreate(Bundle savedInstanceState) {
    super.onCreate(savedInstanceState);
    Realm realm = Realm.getDefaultInstance(); // opens "myrealm.realm" as one singular only 
    try {
      // ... Do something ...
    } finally {
      realm.close();
    }
  }
}

**Comment by cmelchior** [comment]
I'm not sure what you mean by "singular", if a Realm model class has changed, you need to migrate all the Realm files that have this class using a custom migration block for each Realm.

If you have multiple configurations, you can probably not use `getDefaultInstance()` but need to save the configuration in a variable and then reference that, like:

```
public class MyApplication extends Application {
   
  public static RealmConfiguration CONFIG1;
  public static RealmConfiguration CONFIG2;

  @Override
  public void onCreate() {
    super.onCreate();
    Realm.init(this);
    CONFIG1 = new RealmConfiguration.Builder()
       // config parameters
      .build();

    CONFIG2 = new RealmConfiguration.Builder()
       // config parameters
      .build();
  }
}
```

**Comment by TSG9876** [comment]
public static RealmConfiguration CONFIG1;
  public static RealmConfiguration CONFIG2; 

are these  Global confg1 and config 2 thread safe , I suppose if only config2 is affected by the upgrade , .migration need  to include  the schema update as well ?

**Comment by cmelchior** [comment]
Configurations are immutable, so yes, they are. And if only config2 needs a migration, then you should only add a `migration` block to that config.

**Comment by TSG9876** [comment]
Alright , let me try to test in production to see if any memory leaks .
