### ISSUE TITLE
Partial Sync canonicalPath is wrong

### ISSUE THREAD

**Issue by nhachicha** [realm/realm-java#5849]
Currently, using a global or partial sync will end up using the same path locally, which may cause some problems when we try to connect to a partially sync Realm after a connection to a global (reference) Realm. https://realmio.slack.com/archives/C04LCFHDL/p1521476821000250

This is due to the nature of `SyncConfiguration#getCanonicalPath` which is used to set the path of the C++ `conf` to open the Realm, this method doesn't build a different path for global/partial sync, as it should be (see https://github.com/realm/realm-object-store/pull/630)

A quick fix could be to set the correct path when building the native configuration ex:

```C++
JNIEXPORT jstring JNICALL Java_io_realm_internal_OsRealmConfig_nativeCreateAndSetSyncConfig(
    JNIEnv* env, jclass, jlong native_ptr, jstring j_sync_realm_url, jstring j_auth_url, jstring j_user_id,
    jstring j_refresh_token, jboolean j_is_partial, jbyte j_session_stop_policy)
// ...
        // set sync local path (for instance default path doesn't distinguish between global and __partial
        // since the canonical path passed from Java is the same
        config.path = SyncManager::shared().path_for_realm(*user, config.sync_config->realm_url());

```

**Comment by cmelchior** [comment]
Hmm. I'm seeing `BAD_SERVER_VERSION_DOWNLOAD(111)` when running `SyncedRealmIntegrationTest#defaultRealm`. I wonder if this is related somehow: https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-java/detail/PR-5846/11/

**Comment by nhachicha** [comment]
@cmelchior I think it's more relevant to https://github.com/realm/realm-sync/issues/2042 where shutting down the server while the client was running caused the issue

**Comment by cmelchior** [comment]
Partially Sync has been removed. Closing as outdated
