### ISSUE TITLE
RealmChangeListener<RealmResults<Item> puts changed item at bottom of RealmResults

### ISSUE THREAD

**Issue by Coffeegerm** [realm/realm-java#5850]
When trying to watch for changes to a RealmResults list to my database the item that is chosen to be changed doesn't return to its normal spot until you return to the fragment after navigating away.

This is an Android ViewModel and here is how I have it structured, I even attempted sorting the returned list within the change listener to see if that would help, but the returned items were still out of order until you come back. 

```class ListViewModel(var databaseManager: DatabaseManager) : ViewModel() {
  
  private val entriesLiveData = MutableLiveData<RealmResults<EntryItem>>()
  private val entries: RealmResults<EntryItem> = databaseManager.getAllSortedDescending()
  
  init {
    entriesLiveData.postValue(databaseManager.getAllSortedDescending())
    entries.addChangeListener(RealmChangeListener<RealmResults<EntryItem>> {
      it.sort("date", Sort.DESCENDING)
      entriesLiveData.postValue(it)
    })
  }
  
  fun getEntriesLiveData(): LiveData<RealmResults<EntryItem>> = entriesLiveData
  
}```

**Comment by Zhuinden** [comment]
you might want to check out the [official archComponentsExample](https://github.com/realm/realm-java/blob/master/examples/architectureComponentsExample/src/main/java/io/realm/examples/arch/livemodel/LiveRealmResults.java) which might be a bit nicer

**Comment by cmelchior** [comment]
Hi @Coffeegerm Without further information it is hard to say what could be wrong. Preferably an example project that demonstrates it.

But it sounds more like an UI problem than a Realm problem.

Note, that `it.sort(...)` does not sort in-place, but returns the sorted list.

**Comment by Zhuinden** [comment]
Oh yeah, I totally didn't notice that it should be `entriesLiveData.postValue(it.sort("date", Sort.DESCENDING))`

**Comment by cmelchior** [comment]
I assume the above answered your question. If not feel free to reopen.
