### ISSUE TITLE
Combining Timeout & RunTestInLooperThread could fails

### ISSUE THREAD

**Issue by nhachicha** [realm/realm-java#5854]
Combining `Timeout` rule
```Java
   public Timeout globalTimeout = Timeout.seconds(120);
```
with `RunInLooperThread` could fail since `Timeout` will use its own thread to run the test https://github.com/junit-team/junit4/blob/master/src/main/java/org/junit/internal/runners/statements/FailOnTimeout.java#L124
which is different from the looper thread. This will break thread confined operation like closing a Realm, so using `looperThread.closeAfterTest(realm);` will break since the Realm was opened from "Time-limited test" thread and attempt to be closed from "RunInLooperThread" (`RunInLooperThread#closeResources`)

For now, avoid using `looperThread.closeAfterTest` or `Timeout` rule with `RunInLooperThread`

**Comment by cmelchior** [comment]
As part of moving all our tests to Kotlin we now have have a `BlockingLooperThread` test construct that isn't a rule, so it should work nicely with the Timeout rule. Closing as outdated.
