### ISSUE TITLE
Realm removeChangeListener for not valid objects

### ISSUE THREAD

**Issue by idok595** [realm/realm-java#5855]
hey i am suggesting to change the api behaivor, currently if i will try to removeChangeListener for not valid objects (realm is closing) the method throwing exception, why not simply ignore such cases and just print warning?

**Comment by cmelchior** [comment]
Thanks for the suggestion, but we try to opt for a "fail fast" paradigm, and removing a changelistener from an unmanaged object is a logic error somewhere.

If you want to guard against it you can do:

```
if (obj.isValid()) {
  obj.removeChangeListener(listener);
}
```

**Comment by Zhuinden** [comment]
@cmelchior oy oy oy, that was a bit quick there

He says `!isValid() && isManaged()`

**Comment by cmelchior** [comment]
Hmm, your right I was a bit quick there. I guess there is no harm removing listeners from objects no longer valid. My concern was mostly about unmanaged objects, which definitely indicate a logic flaw somewhere.
