### ISSUE TITLE
Deleting objects while iteration using OrderedRealmCollectionSnapshot

### ISSUE THREAD

**Issue by AlonShahaf** [realm/realm-java#5859]
Hi,

I'm trying to delete dangling objects in the DB for a specific class.
To do so I'm building a map of all member objects that my class holds a reference to, and deleting any objects that don't exist in that map.

for example, I have an object class with RealmList<AnotherObj>, and the DB has many instances of AnotherObj that doesn't belong to any class.
My map holds <Object,String> where Object is the Realm_Object itself, so at the end, this map contains all AnotherObj objects that have links to the base object.

#### Expected Results

> when commenting out the deleteFromRealm() line, i get the exact number of items_deleted i expect (total members AnotherObj in the base class).

#### Actual Results

>  more data is deleted, and it seems only half of the data is kept.

#### Code Sample

My code that 'clean' up dangling member classes:
```java
final OrderedRealmCollectionSnapshot my_obj_snap = my_obj.createSnapshot();
        realm.executeTransaction(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {
                int items_deleted = 0;
                for (int i=0; i< my_obj_snap.size(); i++) {

                    if (!my_obj_map.containsKey(my_obj_snap.get(i))) {
                        items_deleted++;
                        my_obj_snap.deleteFromRealm(i); 
                    }
                }
            }
        });

```

#### Version of Realm and tooling
Realm version(s): 3.3.1

Realm sync feature enabled: no

Android Studio version: 3.0.1

Which Android version and device: Xiaomi A1, 8.0

**Comment by AlonShahaf** [comment]
Thanks for your response @Zhuinden , 
the above gives me the same results.

**Comment by Zhuinden** [comment]
Interesting, in that case:

        realm.executeTransaction(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {
                final OrderedRealmCollectionSnapshot my_obj_snap = my_obj.createSnapshot();
                int items_deleted = 0;

**Comment by AlonShahaf** [comment]
Creating the snapshot inside the transaction didn't help either.

**Comment by Zhuinden** [comment]
Does your RealmObject have `equals()` re-defined?

**Comment by AlonShahaf** [comment]
no.

**Comment by Zhuinden** [comment]
Then `snapshot.get()` returns a new instance, so `if (!my_obj_map.containsKey(myObject ))` is most likely always true

**Comment by AlonShahaf** [comment]
If I comment out the delete part, items_deleted has the expected objects number, so I deducted that the comparison was ok.
nevertheless, what are the thumb rule of overriding equals() on my objects?

**Comment by Zhuinden** [comment]
That `results.get()` gives you a new instance each time you call it, so I'd rather mix-and-match against primary key value if I store the RealmObject in a map.

**Comment by AlonShahaf** [comment]
Ok thanks.
Do you have any recommendations how to go over 'orphan' RealmObjects that aren't linked to anything (they don't have any PK's or reverse mapping) ?

**Comment by Zhuinden** [comment]
Why no reverse mapping? Linking objects are essentially free.

**Comment by AlonShahaf** [comment]
Does that mean I can add LinkingObjects on my objects using migration, query elements without links and delete them easily?

**Comment by AlonShahaf** [comment]
Thanks @Zhuinden ! This is much better and cleaner way.
One more question regarding LinkingObjects, is it possible to link a class to two different classes using the same link key?
```
@LinkingObjects("field")
public final RealmResults<Realm_ClassA> rootsA = null;

@LinkingObjects("field")
public final RealmResults<Realm_ClassB> rootsB = null;
```

**Comment by AlonShahaf** [comment]
@Zhuinden can you please help me with the above questions?

**Comment by Zhuinden** [comment]
1.) considering you can't really have the same field name for two different fields of two different types, probably not? But you can have ClassA a; and `RealmList<ClassB> bs`; and have linking objects for both 

2.) yes, that is possible

3.) I'm not sure if linking objects work in DynamicRealm unfortunately because unnamed backlinks like `linkingObjects(field).name` isn't supported in queries yet. :/

**Comment by AlonShahaf** [comment]
Thanks!
