### ISSUE TITLE
Snapshots not building/appearing on jfrog.org repo

### ISSUE THREAD

**Issue by diegomontoya** [realm/realm-java#5863]
The latest 5.0.X master branch commits are not generating snapshot builds

http://oss.jfrog.org/oss-snapshot-local/io/realm/realm-gradle-plugin/5.0.0-SNAPSHOT/

**Comment by cmelchior** [comment]
Most likely the CI build failed for `master` resulting the artifact not being deployed and with no new changes merged to master it will not trigger a new build, but I'll look into it.

**Comment by cmelchior** [comment]
`5.1.0-SNAPSHOT` should be available again.
