### ISSUE TITLE
Sort by the most common value

### ISSUE THREAD

**Issue by anggrayudi** [realm/realm-java#5866]
Does Realm support ordering by the most common values? I want to display user's web histories and sort them by the most visited web page. In MySQL, we can use this query:

```sql
SELECT url, COUNT(url) c FROM web_history
GROUP BY url
ORDER BY c DESC;
```
Temporarily, I use this code in Realm:
```java
TreeMap<Integer, String> map = new TreeMap<>(Collections.<Integer>reverseOrder());
RealmResults<WebHistory> histories = realm.where(WebHistory.class).distinct("url").findAll();
for (WebHistory history : histories){
    int visited = (int) realm.where(WebHistory.class).equalTo("url", history.url).count();
    map.put(visited, history.url);
}
```
I think the above code is not efficient. Will Realm create something like `sortMost(String fieldName)` in next release?

**Expected results**
```java
RealmResults<WebHistory> histories = realm.where(WebHistory.class).sortMost("url").findAll();
```

**Comment by cmelchior** [comment]
Hi @anggrayudi 
We will not be adding a specific function for your use case, but GROUP-BY is tracked here https://github.com/realm/realm-java/issues/2309 so I will fold your request into that issue.

**Comment by Zhuinden** [comment]
You'll need to track the number of occurrence yourself.
