### ISSUE TITLE
insert data duplicate

### ISSUE THREAD

**Issue by AungmyoHtwekh** [realm/realm-java#5867]
#### Goal

> What do you want to achieve?

#### Expected Results

> ?

#### Actual Results

>  E.g. full stack trace with exception

#### Steps & Code to Reproduce

> Describe your current debugging efforts.

#### Code Sample

```java

> Your code here. Bigger samples should ideally be as separate Android Studio project, 
> in gists/repositories or privately at help@realm.io)

```

#### Version of Realm and tooling
Realm version(s): ?

Realm sync feature enabled: yes/no

Android Studio version: ?

Which Android version and device: ?

**Comment by Zhuinden** [comment]
Use a `@PrimaryKey`

**Comment by cmelchior** [comment]
@AungmyoHtwekh 
Please follow the template instead of just putting a question in the title, but like @Zhuinden is saying if you are worried about creating duplicates when inserting data, you should assign a primary key.
