### ISSUE TITLE
Getting started page has 404 example.

### ISSUE THREAD

**Issue by hyunstyle** [realm/realm-java#5868]
Good evening, today I'm trying to follow realm's awesome guide for Java&Kotlin in [Realm official guide page, Korea](https://realm.io/kr/docs/java/latest/#examples). and I've found a trivial bug that cannot access some examples. below is detailed screenshot.

![screenshot](https://user-images.githubusercontent.com/25246960/38194422-61ee89f8-36b2-11e8-8141-8d5cba94078e.png)

as boxed above, when clicks the upper [adapterExample](https://github.com/realm/realm-java/tree/master/examples/adapterExample), 404 returned. that's it. other things were perfect.

And thanks always, as one of the person using your wonderful project, hopefully things will get better!

**Comment by Zhuinden** [comment]
That's probably because it moved to https://github.com/realm/realm-android-adapters/tree/master/example/src/main/java/io/realm/examples/adapters

**Comment by cmelchior** [comment]
@hyunstyle I updated the docs. They should be live shortly.
