### ISSUE TITLE
Filter RealmBaseAdapter content

### ISSUE THREAD

**Issue by desugar-64** [realm/realm-java#587]
Hi. Can I some how filter RealmBaseAdapter? I wrote a method in adapter's class:

public void filter(String queryText) {
    RealmResults<User> filtered = realmResults
                                                                            .where()
                                                                            .contains("name", queryText)
                                                                            .findAll();
    updateRealmResults(filtered);
}

But it throw exception java.lang.ClassCastException: io.realm.internal.TableView cannot be cast to io.realm.internal.Table at line with .contains("name", queryText);
Can you help me?

**Comment by lmdic** [comment]
In Realm 3.7.2 
I use special method of RealmBaseAdapter:

myRealmBaseAdapter.`updateData`(myNewRealmResults);

**Comment by Zhuinden** [comment]
https://stackoverflow.com/questions/40630322/how-to-implement-filterable-in-realmrecyclerviewadapter
