### ISSUE TITLE
OrderedRealmCollectionChangeListener triggers twice with insertions = 1 on single copyToRealmOrUpdate

### ISSUE THREAD

**Issue by NeverwinterMoon** [realm/realm-java#5874]
#### Goal

> 

#### Expected Results

> I want to have a single notification for one insertion

#### Actual Results

> I get 2 notifications in a row for one insertion

#### Steps & Code to Reproduce

Here is how I make the subscription
```
val trips = realm
        .where<Trip>()
        .equalTo("isSuperTrip", true)
        .findAllAsync()
trips.addChangeListener(tripChangeListener)

val tripChangeListener = OrderedRealmCollectionChangeListener { trips: RealmResults<Trip>, changeSet ->
        when (changeSet.state!!) {
          OrderedCollectionChangeSet.State.INITIAL -> {
            Timber.d(Logs.Messages.realmTripsInit(name = "superTrip", trips = trips))
          }
          OrderedCollectionChangeSet.State.UPDATE -> {
            val deletions = changeSet.deletions
            val insertions = changeSet.insertions
            val updates = changeSet.changes

            Timber.d(Logs.Messages.realmTripsUpdate(
                name = "superTrip",
                trips = trips,
                deletions = deletions,
                insertions = insertions,
                updates = updates
            ))
         }
          OrderedCollectionChangeSet.State.ERROR -> {
            Timber.e(Logs.Messages.realmError())
          }
        }
      }
```

And then I add the trip once like this:
```
realmDatabase.getInstance().executeTransactionAsync { realm ->
   realm.copyToRealmOrUpdate(unmanagedTrip)
}
```

Right after I call the above, I get this in the Logcat:
```
onChange: Realm update for [superTrip] detected. Current trips: [{123abc}]. Deletions: [0]. Insertions: [1]. Updates: [0].
onChange: Realm update for [superTrip] detected. Current trips: [{123abc}]. Deletions: [0]. Insertions: [1]. Updates: [0].
```

I actually do some API requests when changes are detected, so this situation is very sub-optimal. Do I misunderstand and it works as expected (for some very unclear reason) or is it something worse?

#### Version of Realm and tooling
Realm version(s): 5.0.0

Realm sync feature enabled: no

Android Studio version: 3.1

Which Android version and device: 7.1.1 emulator

**Comment by NeverwinterMoon** [comment]
Yes, it seems I was a victim of my own poor architecture and Realm had nothing to do with it. Because of how deep links were handled, the same (main) activity was not reused, as it should have been, but created anew, thus creating a new subscription.

**Comment by Zhuinden** [comment]
You need to store RealmResults as a field.

**Comment by NeverwinterMoon** [comment]
@Zhuinden I know that. The example was a tiny bit simplified. The reason for my problem, as I described, was not limiting the main activity to singleTask, which resulted in multiple subscriptions.
