### ISSUE TITLE
Migration required after upgrading Realm

### ISSUE THREAD

**Issue by AlonShahaf** [realm/realm-java#5876]
#### Goal

> When we upgraded Realm from 3.3.1 --> 3.6.0 we encountered migration problems with the @required annotation.
After reading some of the issues here we managed to fix it by removing PK's before setting the fields as required, and then set them back to PK.

#### Expected Results
Migration to complete successfully.

#### Actual Results

>  though our migration tests pass, some of our users are having migration required error:

```
Caused by io.realm.exceptions.RealmMigrationNeededException: Migration is required due to the following errors: - Property 'Realm_Machine.internalId' has been made required. - Property 'Realm_UserDataHierarchy.internalId' has been made required.
--

1 |   | io.realm.internal.SharedRealm.nativeGetSharedRealm(Native Method)
2 |   | io.realm.internal.SharedRealm.<init>(SharedRealm.java:177)
3 |   | io.realm.internal.SharedRealm.getInstance(SharedRealm.java:224)
4 |   | io.realm.BaseRealm.<init>(BaseRealm.java:124)
5 |   | io.realm.BaseRealm.<init>(BaseRealm.java:93)
6 |   | io.realm.Realm.<init>(Realm.java:150)
7 |   | io.realm.Realm.createInstance(Realm.java:417)
8 |   | io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:348)
9 |   | io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:281)
10 |   | io.realm.Realm.getInstance(Realm.java:346)
```

#### Steps & Code to Reproduce

> Our models:

```
public class Realm_Machine extends RealmObject{

    @PrimaryKey
    @Required
    private String internalId;
    private String publicId;
    private String name;

    // getters & setters 
    // ....
}
```

```
public class Realm_UserDataHierarchy extends RealmObject {

    @PrimaryKey
    @Required
    private String internalId;
    private String publicId;
    // getters & setters 
    // ....
}
```

Our migration code:
```
        if (oldVersion == 46) { // Update Realm to 3.6.0
            RealmObjectSchema realmMachine = schema.get(Realm_Machine.class.getSimpleName());
            if (realmMachine.hasPrimaryKey() && !realmMachine.isRequired("internalId")) {
                realmMachine.removePrimaryKey();
                realmMachine.setRequired("internalId", true);
                realmMachine.addPrimaryKey("internalId");
            }

            RealmObjectSchema realmUserDataHierarchy = schema.get(Realm_UserDataHierarchy.class.getSimpleName());
            if (realmUserDataHierarchy.hasPrimaryKey() && !realmUserDataHierarchy.isRequired("internalId")) {
                realmUserDataHierarchy.removePrimaryKey();
                realmUserDataHierarchy.setRequired("internalId", true);
                realmUserDataHierarchy.addPrimaryKey("internalId");
            }
            oldVersion++;
        }
```

The project is written in Java, but I understood that Kotlin support was added in this version. maybe it's related?

#### Version of Realm and tooling
Realm version(s): 3.6.0

Realm sync feature enabled: no

Android Studio version: 3.01

Which Android version and device: Xiaomi A1, 8.1

**Comment by AlonShahaf** [comment]
Thanks for the quick response,
The field 'internalId' on both tables was created/changed on a previous migration:
 ```
       if (oldVersion == 41) {
            schema.get(Realm_Machine.class.getSimpleName())
                    .setRequired("internalId",true) // must be in this order since the field exists and causes an exception otherwise
                    .addPrimaryKey("internalId");

            schema.get(Realm_UserDataHierarchy.class.getSimpleName())
                    // PRIMARY_KEY can't be changed after creation, so we will add a regular
                    // field and change it after the change
                    .addField("internalId", String.class)
                    .transform(new RealmObjectSchema.Function() {
                        @Override
                        public void apply(DynamicRealmObject dynamicRealmObject) {
                            dynamicRealmObject.setString("internalId", UUID.randomUUID().toString());
                        }
                    })
                    .setRequired("internalId", true)
                    .addPrimaryKey("internalId");

            oldVersion++;
        }
```

on every migration tests we ran, the fields were indeed required and set as PK. 
what could be the problem?

**Comment by cmelchior** [comment]
I have a little hard time following the logic , but generally having `if` statements like the below:
``
 if (realmUserDataHierarchy.hasPrimaryKey() && !realmUserDataHierarchy.isRequired("internalId"))
```

Is a really bad idea, because it indicates that you don't trust the migration flow which can often lead to the problem you are now having. 

My guess is that those users that crash doesn't have a primary key at all for some reason, which will cause them to never enter the if statement. How that happened is impossible to say from the given code.

One explanation could be if you are distributing beta builds that read the same Realm file as your release builds, then all bets are probably off with regards to what kind of errors you can encounter.

If you cannot find a reasonable explanation, I would suggest trying to add asserts of your own into the migration code that throw more detailed exceptions about what is wrong. At least you will be in a better situation to debug. Alternatively getting a file from a user would probably also make it easier.

**Comment by AlonShahaf** [comment]
@cmelchior The reason for the if statements were that we forgot to set the field 'internalId' as required at the previous migration (41), so on the latest migration (46) we also changed 41 for older clients.
Can the problem occur if a client that passed the old 41 scheme, 'internalId' set to be PK only, and then upgraded to the latest version of where the model set to both PK & required? I mean could the migration fail when going through 41-->42 even though 42 is unrelated and its some kind of Realm internal verification?

I'm trying to get a client DB to understand it better.

@Zhuinden sorry I didn't understand, do you mean to test my models using auto-migration to conclude the migration is buggy? 
Does it support all Realm features (backlinks etc)?

**Comment by Zhuinden** [comment]
@AlonShahaf as you can see it tries to verify list properties only if you annotate them `@AutoMigration.MigratedList(listType = Cat.class)` but otherwise yes it supports everything

It has this code:

                    if(fieldType == RealmResults.class) { // computed field (like @LinkingObjects), so this should be ignored.
                        //noinspection UnnecessaryContinue
                        continue;

**Comment by cmelchior** [comment]
I assume the above answered your question. If not feel free to reopen the issue.
