### ISSUE TITLE
Realm android error

### ISSUE THREAD

**Issue by jukinhaum** [realm/realm-java#5877]
This is the error:

E/AndroidRuntime: FATAL EXCEPTION: main
                  Process: com.trip, PID: 2210
                  java.lang.ExceptionInInitializerError
                      at io.realm.com_trip_models_trip_FlightRealmProxy.getExpectedObjectSchemaInfo(com_trip_models_trip_FlightRealmProxy.java:807)
                      at io.realm.DefaultRealmModuleMediator.getExpectedObjectSchemaInfoMap(DefaultRealmModuleMediator.java:39)
                      at io.realm.Realm.createExpectedSchemaInfo(Realm.java:193)
                      at io.realm.Realm.<init>(Realm.java:164)
                      at io.realm.Realm.createInstance(Realm.java:435)
                      at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:342)
                      at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:282)
                      at io.realm.Realm.getDefaultInstance(Realm.java:343)
                      at com.trip.models.trip.TripStatus.<clinit>(TripStatus.java:39)
                      at com.trip.models.trip.TripStatus.getAll(TripStatus.java:117)
                      at com.trip.activities.TripListActivity.fetchTrips(TripListActivity.java:94)
                      at com.trip.activities.TripListActivity.onCreate(TripListActivity.java:46)
                      at android.app.Activity.performCreate(Activity.java:6975)
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213)
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770)
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892)
                      at android.app.ActivityThread.-wrap11(Unknown Source:0)
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593)
                      at android.os.Handler.dispatchMessage(Handler.java:105)
                      at android.os.Looper.loop(Looper.java:164)
                      at android.app.ActivityThread.main(ActivityThread.java:6541)
                      at java.lang.reflect.Method.invoke(Native Method)
                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240)
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767)
                   Caused by: java.lang.NullPointerException: Attempt to invoke virtual method 'long io.realm.internal.OsObjectSchemaInfo.getNativePtr()' on a null object reference
                      at io.realm.internal.OsSchemaInfo.convertObjectSchemaInfoListToNativePointerArray(OsSchemaInfo.java:66)
                      at io.realm.internal.OsSchemaInfo.<init>(OsSchemaInfo.java:41)
                      at io.realm.Realm.createExpectedSchemaInfo(Realm.java:193)
                      at io.realm.Realm.<init>(Realm.java:164)
                      at io.realm.Realm.createInstance(Realm.java:435)
                      at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:342)
                      at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:282)
                      at io.realm.Realm.getDefaultInstance(Realm.java:343)
                      at com.trip.models.trip.Flight.<clinit>(Flight.java:73)
                      at io.realm.com_trip_models_trip_FlightRealmProxy.getExpectedObjectSchemaInfo(com_trip_models_trip_FlightRealmProxy.java:807) 
                      at io.realm.DefaultRealmModuleMediator.getExpectedObjectSchemaInfoMap(DefaultRealmModuleMediator.java:39) 
                      at io.realm.Realm.createExpectedSchemaInfo(Realm.java:193) 
                      at io.realm.Realm.<init>(Realm.java:164) 
                      at io.realm.Realm.createInstance(Realm.java:435) 
                      at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:342) 
                      at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:282) 
                      at io.realm.Realm.getDefaultInstance(Realm.java:343) 
                      at com.trip.models.trip.TripStatus.<clinit>(TripStatus.java:39) 
                      at com.trip.models.trip.TripStatus.getAll(TripStatus.java:117) 
                      at com.trip.activities.TripListActivity.fetchTrips(TripListActivity.java:94) 
                      at com.trip.activities.TripListActivity.onCreate(TripListActivity.java:46) 
                      at android.app.Activity.performCreate(Activity.java:6975) 
                      at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1213) 
                      at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2770) 
                      at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2892) 
                      at android.app.ActivityThread.-wrap11(Unknown Source:0) 
                      at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1593) 
                      at android.os.Handler.dispatchMessage(Handler.java:105) 
                      at android.os.Looper.loop(Looper.java:164) 
                      at android.app.ActivityThread.main(ActivityThread.java:6541) 
                      at java.lang.reflect.Method.invoke(Native Method) 
                      at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:240) 
                      at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:767) 
E/CrashlyticsCore: Failed to execute task.
                   java.util.concurrent.TimeoutException
                       at java.util.concurrent.FutureTask.get(FutureTask.java:206)
                       at com.crashlytics.android.core.CrashlyticsExecutorServiceWrapper.executeSyncLoggingException(CrashlyticsExecutorServiceWrapper.java:44)
                       at com.crashlytics.android.core.CrashlyticsUncaughtExceptionHandler.uncaughtException(CrashlyticsUncaughtExceptionHandler.java:251)
                       at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1068)
                       at java.lang.ThreadGroup.uncaughtException(ThreadGroup.java:1063)
                       at java.lang.Thread.dispatchUncaughtException(Thread.java:1953)

and my classes are:

TripStatus.class

`@Parcel(implementations = {io.realm.com_trip_models_trip_TripStatusRealmProxy.class},
        value = Parcel.Serialization.BEAN,analyze = {TripStatus.class})
public class TripStatus extends RealmObject {

    @PrimaryKey
    Integer id;

    String passengerName;

    Integer flightStepOrdinal;

    Integer currentFlight;

    Date updatedAt;
    @ParcelPropertyConverter(RealmListParcelConverter.class)
    RealmList<Flight> flights = new RealmList<>();

    static Realm realm = Realm.getDefaultInstance();

    //Empty constructor for Parceler
    public TripStatus() {
        super();
    }

    public TripStatus(RealmList<Flight> flights) {
        this.flights = flights;
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        id = (int) UUID.randomUUID().getMostSignificantBits();
        this.id = id;
    }

    public String getPassengerName() {
        return passengerName;
    }

    public void setPassengerName(String passengerName) {
        this.passengerName = passengerName;
    }

    public RealmList<Flight> getFlights() {
        if (flights == null || flights.size() < 1) {
            RealmResults<Flight> flightRealmResults = realm.where(Flight.class)
                    .equalTo("id", id).findAll()
                    .sort("arrivalTimeUTC", Sort.ASCENDING);

            flights.addAll(flightRealmResults);
        }
        return flights;
    }
    @ParcelPropertyConverter(RealmListParcelConverter.class)
    public void setFlights(RealmList<Flight> flights) {
        this.flights = flights;
    }

    public Integer getCurrentFlight() {
        return currentFlight;
    }

    public Flight getCurrentFlightInstance() {
        return flights.get(currentFlight);
    }

    public void setCurrentFlight(Integer currentFlight) {
        this.currentFlight = currentFlight;
    }

    public Integer getFlightStepOrdinal() {
        return flightStepOrdinal;
    }

    public void setFlightStepOrdinal(Integer flightStepOrdinal) {
        this.flightStepOrdinal = flightStepOrdinal;
    }

    public Date getUpdatedAt() {
        return updatedAt;
    }

    public void setUpdatedAt(Date updatedAt) {
        this.updatedAt = updatedAt;
    }

    public static TripStatus get(Integer id) {
        return realm.where(TripStatus.class).equalTo("id", id).findFirst();
    }

    public static RealmList<TripStatus> getAll() {
        RealmResults<TripStatus> realmResults = realm.where(TripStatus.class).findAll();
        RealmList<TripStatus> realmList = new RealmList<>();
        realmList.addAll(realmResults);
        return realmList;
    }

    public static void persist(TripStatus tripStatus) {
        for (Flight f : tripStatus.getFlights()) {

            realm.beginTransaction();

            realm.copyToRealm(f);

            realm.commitTransaction();

        }
        tripStatus.setUpdatedAt(new Date());
        realm.copyToRealm(tripStatus);
    }

    public static TripStatus saveOrUpdateTrip(TripStatus trip, FlightStatus flight, String seatNo, Appendix appendix) {
        Flight f = new Flight(flight, seatNo, appendix);
        if (trip == null || trip.getId() == null) {
            return createNewTrip(new RealmList<Flight>(f));
        }
        return updateTrip(trip, f);
    }

    public static TripStatus createTrip(RealmList<ScheduledFlight> scheduleFlights, Appendix appendix) {
        RealmList<Flight> flights = new RealmList<Flight>();
        for (ScheduledFlight s : scheduleFlights) {
            flights.add(new Flight(s, appendix));
        }
        return createNewTrip(flights);
    }

    public static void deleteTrip(TripStatus trip) {

        realm.beginTransaction();

        RealmQuery<TripStatus> realmQuery = realm.where(TripStatus.class);
        realmQuery.equalTo("id", trip.id);

        final TripStatus tripStatus = realmQuery.findFirst();

        if(tripStatus!=null){
            realm.executeTransaction(new Realm.Transaction() {
                @Override
                public void execute(Realm realm) {
                    tripStatus.deleteFromRealm();
                }
            });
        }

        realm.commitTransaction();
    }

    private static TripStatus updateTrip(TripStatus trip, Flight flight) {
        boolean isNewFlight = true;
        for (int i = 0; i < trip.getFlights().size(); i++) {
            Flight f = trip.getFlights().get(i);
            if (f.getFlightNumber() == flight.getFlightNumber() && f.getDepartureAirportIATA() == flight.getDepartureAirportIATA()) {
                Flight.mergeFlights(f, flight);
                try{
                realm.beginTransaction();

                realm.copyToRealm(f);

                realm.commitTransaction();}finally {
                    realm.close();
                }
                isNewFlight = false;
                break;
            }
        }
        if (isNewFlight) {
            flight.setTripId(trip.getId());
            try {
            realm.beginTransaction();

            realm.copyToRealm(flight);

            realm.commitTransaction();
            trip.getFlights().add(flight);}finally {
                realm.close();
            }
        }
        trip.setUpdatedAt(new Date());
        realm.beginTransaction();

        realm.copyToRealmOrUpdate(trip);

        realm.commitTransaction();
        return trip;
    }

    private static TripStatus createNewTrip(RealmList<Flight> flights) {
        TripStatus trip = new TripStatus();
        trip.setCurrentFlight(0);
        trip.setUpdatedAt(new Date());
        try{
        realm.beginTransaction();

        realm.copyToRealmOrUpdate(trip);

        realm.commitTransaction();}finally {
            realm.close();
        }
        int i = 0;
        for (Flight f : flights) {
            f.setTripId(trip.getId());
            try{

            realm.beginTransaction();

            realm.copyToRealmOrUpdate(f);

            realm.commitTransaction();}finally {
                realm.close();
            }
        }
        return TripStatus.get(trip.getId());
    }
}
`

Flight.class

`package com.trip.models.trip;

import android.text.TextUtils;

import com.trip.models.airline.Airline;
import com.trip.models.airport.Airport;
import com.trip.models.flightstatus.AirportResources;
import com.trip.models.flightstatus.Appendix;
import com.trip.models.flightstatus.FlightStatus;
import com.trip.models.flightstatus.ScheduledFlight;
import com.trip.utils.Utils;

import org.parceler.Parcel;

import java.util.Date;
import java.util.List;
import java.util.UUID;

import io.realm.Realm;
import io.realm.RealmList;
import io.realm.RealmObject;
import io.realm.RealmResults;
import io.realm.annotations.PrimaryKey;

@Parcel(implementations = {io.realm.com_trip_models_trip_FlightRealmProxy.class},
        value = Parcel.Serialization.BEAN,analyze = {Flight.class})
public class Flight extends RealmObject {

    @PrimaryKey
    Integer id;

    Integer tripId;

    String flightNumber;

    String flightCarrier;

    String flightCarrierName;

    Integer flightId;

    String seatNumber;

    String baggage;

    String departureGate;

    String departureTime;

    String departureTerminal;

    Date departureTimeUTC;

    String departureAirportIATA;

    String departureCity;

    String arrivalGate;

    String arrivalTime;

    String arrivalTerminal;

    Date arrivalTimeUTC;

    String arrivalAirportIATA;

    String arrivalCity;

    String arrivalCityImageUrl;

    static Realm realm = Realm.getDefaultInstance();

    //Empty constructor for Parceler
    public Flight() {
    }

    public Flight(ScheduledFlight sch, Appendix appendix) {
        super();
        this.setArrivalAirportIATA(sch.getArrivalAirportFsCode());
        this.setArrivalTerminal(sch.getArrivalTerminal());
        this.setArrivalTime(sch.getArrivalTime());
        this.setDepartureAirportIATA(sch.getDepartureAirportFsCode());
        this.setDepartureTerminal(sch.getDepartureTerminal());
        this.setDepartureTime(sch.getDepartureTime());
        this.setFlightCarrier(sch.getCarrierFsCode());
        this.setFlightNumber(sch.getFlightNumber());
        if (appendix != null) {
            setAppendinxData(appendix);
        }
    }

    public Flight(FlightStatus flightStatus, String seatNo, Appendix appendix) {
        super();
        this.setArrivalAirportIATA(flightStatus.getArrivalAirportFsCode());
        this.setArrivalTime(flightStatus.getArrivalDate().getDateLocal());
        this.setDepartureAirportIATA(flightStatus.getDepartureAirportFsCode());
        this.setDepartureTime(flightStatus.getDepartureDate().getDateLocal());

        this.setArrivalTimeUTC(Utils.parseLongFormatDate(flightStatus.getArrivalDate().getDateUtc()));
        this.setDepartureTimeUTC(Utils.parseLongFormatDate(flightStatus.getArrivalDate().getDateUtc()));

        this.setFlightId(flightStatus.getFlightId());
        this.setFlightCarrier(flightStatus.getCarrierFsCode());
        this.setFlightNumber(flightStatus.getFlightNumber());

        AirportResources ar = flightStatus.getAirportResources();
        if (ar != null) {
            this.setDepartureGate(ar.getDepartureGate());
            this.setDepartureTerminal(ar.getDepartureTerminal());
            this.setArrivalTerminal(ar.getArrivalTerminal());
        }

        if (!TextUtils.isEmpty(seatNo)) {
            this.setSeatNumber(seatNo);
        }
        if (appendix != null) {
            setAppendinxData(appendix);
        }
    }

    private void setAppendinxData(Appendix appendix) {
        List<Airport> airports = appendix.getAirports();
        List<Airline> airlines = appendix.getAirlines();
        // Find airport name
        for (Airport a : airports) {
            if (a.getFs().equals(this.getArrivalAirportIATA())) {
                this.setArrivalCity(a.getCity());
                Date localDate = Utils.getUTCDate(this.getArrivalTime(), a.getTimeZoneRegionName());
                this.setArrivalTimeUTC(localDate);

            }
            if (a.getFs().equals(this.getDepartureAirportIATA())) {
                this.setDepartureCity(a.getCity());
                Date localDate = Utils.getUTCDate(this.getDepartureTime(), a.getTimeZoneRegionName());
                this.setDepartureTimeUTC(localDate);
            }
        }

        // Find carrier name
        for (Airline al : airlines) {
            if (al.getFs().equals(this.getFlightCarrier())) {
                this.setFlightCarrierName(al.getName());
                break;
            }
        }
    }

    public Integer getId() {
        return id;
    }

    public void setId(Integer id) {
        id = (int) UUID.randomUUID().getMostSignificantBits();
        this.id = id;
    }

    public String getFlightNumber() {
        return flightNumber;
    }

    public void setFlightNumber(String flightNumber) {
        this.flightNumber = flightNumber;
    }

    public String getFlightCarrier() {
        return flightCarrier;
    }

    public void setFlightCarrier(String flightCarrier) {
        this.flightCarrier = flightCarrier;
    }

    public String getFlightCarrierName() {
        return flightCarrierName;
    }

    public void setFlightCarrierName(String flightCarrierName) {
        this.flightCarrierName = flightCarrierName;
    }

    public String getAirlineIconUrl() {
        return String.format("http://www.gstatic.com/flights/airline_logos/70px/%s.png", flightCarrier);
    }

    public String getDepartureTerminal() {
        return departureTerminal;
    }

    public void setDepartureTerminal(String departureTerminal) {
        this.departureTerminal = departureTerminal;
    }

    public String getArrivalTerminal() {
        return arrivalTerminal;
    }

    public void setArrivalTerminal(String arrivalTerminal) {
        this.arrivalTerminal = arrivalTerminal;
    }

    public String getSeatNumber() {
        return seatNumber;
    }

    public void setSeatNumber(String seatNumber) {
        this.seatNumber = seatNumber;
    }

    public Integer getTripId() {
        return tripId;
    }

    public void setTripId(Integer tripId) {
        this.tripId = tripId;
    }

    public Integer getFlightId() {
        return flightId;
    }

    public void setFlightId(Integer flightId) {
        this.flightId = flightId;
    }

    public String getDepartureGate() {
        return departureGate;
    }

    public void setDepartureGate(String departureGate) {
        this.departureGate = departureGate;
    }

    public String getDepartureAirportIATA() {
        return departureAirportIATA;
    }

    public void setDepartureAirportIATA(String departureAirportIATA) {
        this.departureAirportIATA = departureAirportIATA;
    }

    public String getDepartureCity() {
        return departureCity;
    }

    public void setDepartureCity(String departureCity) {
        this.departureCity = departureCity;
    }

    public String getArrivalAirportIATA() {
        return arrivalAirportIATA;
    }

    public void setArrivalAirportIATA(String arrivalAirportIATA) {
        this.arrivalAirportIATA = arrivalAirportIATA;
    }

    public String getArrivalCity() {
        return arrivalCity;
    }

    public void setArrivalCity(String arrivalCity) {
        this.arrivalCity = arrivalCity;
    }

    public String getDepartureTime() {
        return departureTime;
    }

    public void setDepartureTime(String departureTime) {
        this.departureTime = departureTime;
    }

    public Date getDepartureTimeUTC() {
        return departureTimeUTC;
    }

    public void setDepartureTimeUTC(Date departureTimeUTC) {
        this.departureTimeUTC = departureTimeUTC;
    }

    public String getArrivalTime() {
        return arrivalTime;
    }

    public void setArrivalTime(String arrivalTime) {
        this.arrivalTime = arrivalTime;
    }

    public Date getArrivalTimeUTC() {
        return arrivalTimeUTC;
    }

    public void setArrivalTimeUTC(Date arrivalTimeUTC) {
        this.arrivalTimeUTC = arrivalTimeUTC;
    }

    public String getBaggage() {
        return baggage;
    }

    public void setBaggage(String baggage) {
        this.baggage = baggage;
    }

    public String getArrivalGate() {
        return arrivalGate;
    }

    public void setArrivalGate(String arrivalGate) {
        this.arrivalGate = arrivalGate;
    }

    public String getArrivalCityImageUrl() {
        return arrivalCityImageUrl;
    }

    public void setArrivalCityImageUrl(String arrivalCityImageUrl) {
        this.arrivalCityImageUrl = arrivalCityImageUrl;
    }

    //=================== DB operations ========================

    public static Flight get(Integer id) {
        return realm.where(Flight.class).equalTo("id", id).findFirst();
    }

    public static RealmList<Flight> getAll() {
        RealmResults<Flight> realmResults = realm.where(Flight.class).findAll();
        RealmList<Flight> realmList = new RealmList<>();
        realmList.addAll(realmResults);
        return realmList;
    }
`

**Comment by Zhuinden** [comment]
`static Realm realm = Realm.getDefaultInstance();` remove this from your `RealmObject` class and it should work.

**Comment by jukinhaum** [comment]
sorry i forgot to insert one class which is this:

`
public class TripListActivity extends AppCompatActivity {

    public static final String TAG = TripListActivity.class.getSimpleName();

    private RealmList<TripStatus> trips;
    private RealmList<Flight> flights;
    private FlightListAdapter flightListAdapter;

    @BindView(R.id.rvTrips) RecyclerView rvTrips;
    @BindView(R.id.fabNewTrip) FloatingActionButton fabNewTrip;
    @BindView(R.id.toolbar)
    Toolbar toolbar;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_trip_list);
        ButterKnife.bind(this);

        setupRecyclerView();
        setupListeners();
        setSupportActionBar(toolbar);
        fetchTrips();
    }

    private void setupListeners() {
        fabNewTrip.setOnClickListener(v -> {
            // Open create trip activity
            Intent i = new Intent(TripListActivity.this, NewTripActivity.class);
            startActivityForResult(i, NewTripActivity.REQUEST_FLIGHT_SELECTION);
        });

        flightListAdapter.getItemClickSubject().retry().subscribe(flight -> {
            Intent i = new Intent(TripListActivity.this, TripInfoActivity.class);
            TripStatus trip = getTripForFlight(flight);
            i.putExtra(Constants.PARAM_TRIP, Parcels.wrap(trip));
            startActivity(i);
        });

        flightListAdapter.getDeleteSubject().retry().subscribe(flight -> {
            int index = flights.indexOf(flight);
            flights.remove(flight);
            flightListAdapter.notifyItemRemoved(index);
            TripStatus trip = getTripForFlight(flight);
            TripStatus.deleteTrip(trip);
        });
    }

    private TripStatus getTripForFlight(Flight flight) {
        for (TripStatus t: trips) {
            if (t.getFlights().contains(flight)) {
                return t;
            }
        }

        return null;
    }

    private void setupRecyclerView() {
        trips = new RealmList<>();
        flights = new RealmList<>();
        flightListAdapter = new FlightListAdapter(this, flights);
        rvTrips.setAdapter(flightListAdapter);
        LinearLayoutManager layout = new LinearLayoutManager(getApplicationContext(), LinearLayoutManager.VERTICAL, false);
        rvTrips.setLayoutManager(layout);
        rvTrips.addItemDecoration(new SimpleDividerItemDecoration(getApplicationContext()));
    }

    private void fetchTrips() {
        flights.clear();
        trips = TripStatus.getAll();

        for (TripStatus ts : trips) {
            flights.addAll(ts.getFlights());
        }
        flightListAdapter.notifyDataSetChanged();
    }

    @Override
    protected void onActivityResult(int requestCode, int resultCode, Intent data) {
        super.onActivityResult(requestCode, resultCode, data);
        fetchTrips();
    }
}
`

the error seems to be on fetchTrips() method and then on trips = TripStatus.getAll();

**Comment by jukinhaum** [comment]
sorry you were right.. i deleted that line in other class and worked sorry for bother!
