### ISSUE TITLE
Issue on my all Android devices

### ISSUE THREAD

**Issue by nabievnurlan7** [realm/realm-java#5878]
What causes this issue?
What should i do to fix this?
I use "classpath "io.realm:realm-gradle-plugin:4.3.1"" in my my gradle file for Android.

04-06 12:52:05.919 E/REALM: /home/jenkins/workspace/realm_realm-core_PR-2932-3UKZX3DIAA6C7HYY2BXKB2YPDOKXKDHJILDG3TPJMCH6YENXIJWQ@10/src/realm/group_writer.cpp:392: [realm-core-4.0.4] Assertion failed: ref + size <= after_ref with (ref, size, after_ref, ndx, m_free_positions.size()) =  [0, 8, 0, 0, 10]
                            IMPORTANT: if you see this error, please send this log to help@realm.io.
04-06 12:52:05.919 A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 6610 (icapapps.enurse)
04-06 12:52:05.969 D/hwcomposer: void android::intel::UeventObserver::onUevent(): received Uevent: REPEATED_FRAME
04-06 12:52:05.969 D/hwcomposer: virtual void android::intel::Hwcomposer::invalidate(): invalidating screen...
04-06 12:52:05.969 D/hwcomposer: void android::intel::DisplayAnalyzer::handleIdleEntryEvent(int): handling idle entry event, count 0
04-06 12:52:06.019 I/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
04-06 12:52:06.019 I/DEBUG: Build fingerprint: 'asus/WW_P01T_1/P01T_1:5.0.1/LRX22C/WW_epad-12.14.4.29.2-20150922:user/release-keys'
04-06 12:52:06.019 I/DEBUG: Revision: '0'
04-06 12:52:06.019 I/DEBUG: ABI: 'x86'
04-06 12:52:06.019 I/DEBUG: pid: 6610, tid: 6610, name: icapapps.enurse  >>> kz.icapapps.enurse <<<
04-06 12:52:06.019 I/DEBUG: signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------
04-06 12:52:06.029 I/DEBUG:     eax 00000000  ebx 000019d2  ecx 000019d2  edx 00000006
04-06 12:52:06.029 I/DEBUG:     esi f7796f08  edi 00000011
04-06 12:52:06.029 I/DEBUG:     xcs 00000023  xds 0000002b  xes 0000002b  xfs 00000007  xss 0000002b
04-06 12:52:06.029 I/DEBUG:     eip f76f8356  ebp 000019d2  esp ffbe34d0  flags 00200206
04-06 12:52:06.029 I/DEBUG: backtrace:
04-06 12:52:06.029 I/DEBUG:     #00 pc 00084356  /system/lib/libc.so (tgkill+22)
04-06 12:52:06.029 I/DEBUG:     #01 pc 000310a3  /system/lib/libc.so (pthread_kill+163)
04-06 12:52:06.029 I/DEBUG:     #02 pc 00032975  /system/lib/libc.so (raise+37)
04-06 12:52:06.029 I/DEBUG:     #03 pc 0002ac65  /system/lib/libc.so (abort+85)
04-06 12:52:06.029 I/DEBUG:     #04 pc 0021cf59  /data/app/kz.icapapps.enurse-1/lib/x86/librealm-jni.so
04-06 12:52:06.029 I/DEBUG:     #05 pc 0021cfa6  /data/app/kz.icapapps.enurse-1/lib/x86/librealm-jni.so
04-06 12:52:06.029 I/DEBUG:     #06 pc 0021d0ef  /data/app/kz.icapapps.enurse-1/lib/x86/librealm-jni.so
04-06 12:52:06.039 I/DEBUG:     #07 pc 001b3aad  /data/app/kz.icapapps.enurse-1/lib/x86/librealm-jni.so
04-06 12:52:06.039 I/DEBUG:     #08 pc 001afcc2  /data/app/kz.icapapps.enurse-1/lib/x86/librealm-jni.so
04-06 12:52:06.039 I/DEBUG:     #09 pc 001afff0  /data/app/kz.icapapps.enurse-1/lib/x86/librealm-jni.so
04-06 12:52:06.039 I/DEBUG:     #10 pc 001b208a  /data/app/kz.icapapps.enurse-1/lib/x86/librealm-jni.so
04-06 12:52:06.039 I/DEBUG:     #11 pc 0010361b  /data/app/kz.icapapps.enurse-1/lib/x86/librealm-jni.so
04-06 12:52:06.039 I/DEBUG:     #12 pc 000f4190  /data/app/kz.icapapps.enurse-1/lib/x86/librealm-jni.so
04-06 12:52:06.039 I/DEBUG:     #13 pc 000d8639  /data/app/kz.icapapps.enurse-1/lib/x86/librealm-jni.so
04-06 12:52:06.039 I/DEBUG:     #14 pc 000dc1d0  /data/app/kz.icapapps.enurse-1/lib/x86/librealm-jni.so
04-06 12:52:06.039 I/DEBUG:     #15 pc 000f85fb  /data/app/kz.icapapps.enurse-1/lib/x86/librealm-jni.so
04-06 12:52:06.039 I/DEBUG:     #16 pc 000d82b6  /data/app/kz.icapapps.enurse-1/lib/x86/librealm-jni.so
04-06 12:52:06.039 I/DEBUG:     #17 pc 00051043  /data/app/kz.icapapps.enurse-1/lib/x86/librealm-jni.so (Java_io_realm_internal_OsSharedRealm_nativeGetSharedRealm+547)
04-06 12:52:06.039 I/DEBUG:     #18 pc 006114ae  /data/dalvik-cache/x86/data@app@kz.icapapps.enurse-1@base.apk@classes.dex

**Comment by bmunkholm** [comment]
@nabievnurlan7 Please fill out the template we provide automatically for all issues, Then we will have a look. Thanks!

**Comment by cmelchior** [comment]
Duplicate of #5300  Folding into that one
