### ISSUE TITLE
[Sync] Schema validation failed

### ISSUE THREAD

**Issue by nhachicha** [realm/realm-java#5883]
This was triggered while testing the permission [chat demo](https://github.com/realm/my-first-realm-app/pull/30) not always reproducible ...

```
E/REALM_JNI( 5823): jni: ThrowingException 8, Schema validation failed due to the following errors:
E/REALM_JNI( 5823): - Property 'PrivateChatRoom.permissions' of type 'array' has unknown object type '__Permission', .
E/REALM_JNI( 5823): Exception has been thrown: Schema validation failed due to the following errors:
E/REALM_JNI( 5823): - Property 'PrivateChatRoom.permissions' of type 'array' has unknown object type '__Permission'
D/AndroidRuntime( 5823): Shutting down VM
E/AndroidRuntime( 5823): FATAL EXCEPTION: main
E/AndroidRuntime( 5823): Process: io.realm.todo, PID: 5823
E/AndroidRuntime( 5823): java.lang.RuntimeException: Unable to start activity ComponentInfo{io.realm.todo/io.realm.todo.ChatRoomsActivity}: java.lang.IllegalStateException: Schema validation failed due to the following errors:
E/AndroidRuntime( 5823): - Property 'PrivateChatRoom.permissions' of type 'array' has unknown object type '__Permission'
E/AndroidRuntime( 5823): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2325)
E/AndroidRuntime( 5823): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2387)
E/AndroidRuntime( 5823): 	at android.app.ActivityThread.access$800(ActivityThread.java:151)
E/AndroidRuntime( 5823): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1303)
E/AndroidRuntime( 5823): 	at android.os.Handler.dispatchMessage(Handler.java:102)
E/AndroidRuntime( 5823): 	at android.os.Looper.loop(Looper.java:135)
E/AndroidRuntime( 5823): 	at android.app.ActivityThread.main(ActivityThread.java:5254)
E/AndroidRuntime( 5823): 	at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime( 5823): 	at java.lang.reflect.Method.invoke(Method.java:372)
E/AndroidRuntime( 5823): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
E/AndroidRuntime( 5823): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
E/AndroidRuntime( 5823): Caused by: java.lang.IllegalStateException: Schema validation failed due to the following errors:
E/AndroidRuntime( 5823): - Property 'PrivateChatRoom.permissions' of type 'array' has unknown object type '__Permission'
E/AndroidRuntime( 5823): 	at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
E/AndroidRuntime( 5823): 	at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:171)
E/AndroidRuntime( 5823): 	at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:241)
E/AndroidRuntime( 5823): 	at io.realm.BaseRealm.<init>(BaseRealm.java:136)
E/AndroidRuntime( 5823): 	at io.realm.BaseRealm.<init>(BaseRealm.java:105)
E/AndroidRuntime( 5823): 	at io.realm.Realm.<init>(Realm.java:164)
E/AndroidRuntime( 5823): 	at io.realm.Realm.createInstance(Realm.java:435)
E/AndroidRuntime( 5823): 	at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:342)
E/AndroidRuntime( 5823): 	at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:282)
E/AndroidRuntime( 5823): 	at io.realm.Realm.getDefaultInstance(Realm.java:343)
E/AndroidRuntime( 5823): 	at io.realm.todo.ChatRoomsActivity.onCreate(ChatRoomsActivity.java:88)
E/AndroidRuntime( 5823): 	at android.app.Activity.performCreate(Activity.java:5990)
E/AndroidRuntime( 5823): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1106)
E/AndroidRuntime( 5823): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2278)
E/AndroidRuntime( 5823): 	... 10 more
W/ActivityManager(  755):   Force finishing activity 1 io.realm.todo/.ChatRoomsActivity

```

@cmelchior this looks similar to some issue we were seeing while adding the permission schema into the next-major ...

**Comment by FatihYalmanbas** [comment]
I have the same problem where it looks like it doesnt recognize one of my realm object classes.

`
E/REALM_JNI: jni: ThrowingException 8, Schema validation failed due to the following errors:
    - Property 'RealmDestination.departure' of type 'object' has unknown object type 'RealmPortLocation'
    - Property 'RealmDestination.arrivalList' of type 'array' has unknown object type 'RealmPortLocation', .
    Exception has been thrown: Schema validation failed due to the following errors:
    - Property 'RealmDestination.departure' of type 'object' has unknown object type 'RealmPortLocation'
    - Property 'RealmDestination.arrivalList' of type 'array' has unknown object type 'RealmPortLocation'
`

**Comment by cmelchior** [comment]
This seems to have been fixed. At least we haven't seen it surface again. Closing.

**Comment by naaraayananr** [comment]
Hi,

Similar problem is currently blocking my work. I had built two Classes Project.java and Unit.java both extending RealmObject with Primary Key field and all other fields being String types. Projects included a RealmList of Units. Lately, I needed to add another level between them Property.java that's a similar RealmObject like Project in structure. Only adding another level of nesting. So, Projects have List of Properties and Properties have Units. After this change, I'm facing the following error:

> Schema validation failed due to the following errors:
>     - Property 'project.properties' of type 'array' has unknown object type 'Property', .
>     Exception has been thrown: Schema validation failed due to the following errors:
>     - Property 'project.properties' of type 'array' has unknown object type 'Property'

Below are my class files. Please help me find what I'm missing or doing wrong.

`Project.java:`

	package com.storage.realm;

	import java.util.Objects;

	import io.realm.RealmList;
	import io.realm.RealmObject;
	import io.realm.annotations.PrimaryKey;

	public class Project extends RealmObject {
		@PrimaryKey private String              id;
		private             String              project_name;
		private             String              project_image_url;
		private             RealmList<Property> properties;

		public Project () {
		}

		public Project (final String id, final String project_name, final String project_image_url,
			final RealmList<Property> properties) {
			setId(id);
			setProject_name(project_name);
			setProject_image_url(project_image_url);
			setProperties(properties);
		}

		public RealmList<Property> getProperties () {
			if (null == this.properties) {
			return this.properties;
			}

			RealmList<Property> copy2Share = new RealmList<>();

			copy2Share.addAll(this.properties);

			return copy2Share;
		}

		public void setProperties (RealmList<Property> properties) {
			if (null == properties) {
			this.properties = properties;

			return;
			}

			RealmList<Property> copy2Store = new RealmList<>();

			copy2Store.addAll(properties);

			this.properties = copy2Store;
		}

		@Override public int hashCode () {
			return Objects.hash(getId(), getProject_name(), getProject_image_url());
		}

		@Override public boolean equals (final Object o) {
			if (this == o) {
			return true;
			}
			if (o == null || getClass() != o.getClass()) {
			return false;
			}
			final Project project = (Project) o;
			return Objects.equals(getId(), project.getId()) &&
				Objects.equals(getProject_name(), project.getProject_name()) &&
				Objects.equals(getProject_image_url(), project.getProject_image_url());
		}

		@Override public String toString () {
			final StringBuffer sb = new StringBuffer("Project{");
			sb.append("id='").append(id).append('\'');
			sb.append(", project_name='").append(project_name).append('\'');
			sb.append(", project_image_url='").append(project_image_url).append('\'');
			sb.append('}');
			return sb.toString();
		}

		public String getId () {
			return id;
		}

		public void setId (final String id) {
			this.id = id;
		}

		public String getProject_name () {
			return project_name;
		}

		public void setProject_name (final String project_name) {
			this.project_name = project_name;
		}

		public String getProject_image_url () {
			return project_image_url;
		}

		public void setProject_image_url (final String project_image_url) {
			this.project_image_url = project_image_url;
		}
	}

`Property.java:`

	package com.storage.realm;

	import java.util.Objects;

	import io.realm.RealmList;
	import io.realm.RealmObject;
	import io.realm.annotations.PrimaryKey;

	public class Property extends RealmObject {
		// @LinkingObjects("properties")
		// private final RealmResults<Project> parents = null;
		@PrimaryKey private String          id;
		private             String          project_id;
		private             String          property_name;
		private             String          property_image_url;
		private             RealmList<Unit> units;

		public Property () {
		}

		public Property (final String id, final String project_id, final String property_name,
			final String property_image_url, final RealmList<Unit> units) {
			setId(id);
			setProject_id(project_id);
			setProperty_name(property_name);
			setProperty_image_url(property_image_url);
			setUnits(units);
		}

		public RealmList<Unit> getUnits () {
			if (null == this.units) {
			return this.units;
			}

			RealmList<Unit> copy2Share = new RealmList<>();

			copy2Share.addAll(this.units);

			return copy2Share;
		}

		public void setUnits (RealmList<Unit> units) {
			if (null == units) {
			this.units = units;

			return;
			}

			RealmList<Unit> copy2Store = new RealmList<>();

			copy2Store.addAll(units);

			this.units = copy2Store;
		}

		@Override public int hashCode () {
			return Objects.hash(getId(), getProject_id(), getProperty_name(), getProperty_image_url());
		}

		@Override public boolean equals (final Object o) {
			if (this == o) {
			return true;
			}
			if (o == null || getClass() != o.getClass()) {
			return false;
			}
			final Property property = (Property) o;
			return Objects.equals(getId(), property.getId()) &&
				Objects.equals(getProject_id(), property.getProject_id()) &&
				Objects.equals(getProperty_name(), property.getProperty_name()) &&
				Objects.equals(getProperty_image_url(), property.getProperty_image_url());
		}

		@Override public String toString () {
			final StringBuffer sb = new StringBuffer("Property{");
			sb.append("id='").append(id).append('\'');
			sb.append(", project_id='").append(project_id).append('\'');
			sb.append(", property_name='").append(property_name).append('\'');
			sb.append(", property_image_url='").append(property_image_url).append('\'');
			sb.append('}');
			return sb.toString();
		}

		public String getId () {
			return id;
		}

		public void setId (final String id) {
			this.id = id;
		}

		public String getProject_id () {
			return project_id;
		}

		public void setProject_id (final String project_id) {
			this.project_id = project_id;
		}

		public String getProperty_name () {
			return property_name;
		}

		public void setProperty_name (final String property_name) {
			this.property_name = property_name;
		}

		public String getProperty_image_url () {
			return property_image_url;
		}

		public void setProperty_image_url (final String property_image_url) {
			this.property_image_url = property_image_url;
		}
	}

`Unit.java:`

    package com.storage.realm;

    import java.util.Objects;

    import io.realm.RealmList;
    import io.realm.RealmObject;
    import io.realm.annotations.PrimaryKey;

    public class Unit extends RealmObject {
        // @LinkingObjects("units")
        // private final       RealmResults<Property> parents = null;
        @PrimaryKey private String              id;
        private             String              assigned_id;
        private             String              block_id;
        private             String              layout;
        private             String              phase;
        private             String              priority;
        private             String              property_id;
        private             String              title;

        public Unit () {
        }

        public Unit (final String id, final String assigned_id, final String block_id,
                final String layout, final String phase, final String priority, final String
                property_id, final String title) {
            setId(id);
            setAssigned_id(assigned_id);
            setBlock_id(block_id);
            setLayout(layout);
            setPhase(phase);
            setPriority(priority);
            setProperty_id(property_id);
            setTitle(title);
        }

        @Override public int hashCode () {
            return Objects.hash(getId(), getAssigned_id(), getBlock_id(), getLayout(), getPhase(),
                    getPriority(), getProperty_id(), getTitle());
        }

        @Override public boolean equals (final Object o) {
            if (this == o) {
                return true;
            }
            if (o == null || getClass() != o.getClass()) {
                return false;
            }
            final Unit unit = (Unit) o;
            return Objects.equals(getId(), unit.getId()) &&
                    Objects.equals(getAssigned_id(), unit.getAssigned_id()) &&
                    Objects.equals(getBlock_id(), unit.getBlock_id()) &&
                    Objects.equals(getLayout(), unit.getLayout()) &&
                    Objects.equals(getPhase(), unit.getPhase()) &&
                    Objects.equals(getPriority(), unit.getPriority()) &&
                    Objects.equals(getProperty_id(), unit.getProperty_id()) &&
                    Objects.equals(getTitle(), unit.getTitle());
        }

        @Override public String toString () {
            final StringBuffer sb = new StringBuffer("Unit{");
            sb.append("id='").append(id).append('\'');
            sb.append(", assigned_id='").append(assigned_id).append('\'');
            sb.append(", block_id='").append(block_id).append('\'');
            sb.append(", layout='").append(layout).append('\'');
            sb.append(", phase='").append(phase).append('\'');
            sb.append(", priority='").append(priority).append('\'');
            sb.append(", property_id='").append(property_id).append('\'');
            sb.append(", title='").append(title).append('\'');
            sb.append('}');
            return sb.toString();
        }

        public String getId () {
            return id;
        }

        public void setId (final String id) {
            this.id = id;
        }

        public String getAssigned_id () {
            return assigned_id;
        }

        public void setAssigned_id (final String assigned_id) {
            this.assigned_id = assigned_id;
        }

        public String getBlock_id () {
            return block_id;
        }

        public void setBlock_id (final String block_id) {
            this.block_id = block_id;
        }

        public String getLayout () {
            return layout;
        }

        public void setLayout (final String layout) {
            this.layout = layout;
        }

        public String getPhase () {
            return phase;
        }

        public void setPhase (final String phase) {
            this.phase = phase;
        }

        public String getPriority () {
            return priority;
        }

        public void setPriority (final String priority) {
            this.priority = priority;
        }

        public String getProperty_id () {
            return property_id;
        }

        public void setProperty_id (final String property_id) {
            this.property_id = property_id;
        }

        public String getTitle () {
            return title;
        }

        public void setTitle (final String title) {
            this.title = title;
        }
    }

**Comment by AAlier** [comment]
E/REALM_JNI: jni: ThrowingException 8, Schema validation failed due to the following errors:
    - Property 'GoalEntity.amount' of type 'object' has unknown object type 'Amount'
    - Property 'GoalEntity.targetAmount' of type 'object' has unknown object type 'Amount', .
2020-05-08 00:06:04.266 25950-25950/com.finca.bank E/REALM_JNI: Exception has been thrown: Schema validation failed due to the following errors:
    - Property 'GoalEntity.amount' of type 'object' has unknown object type 'Amount'
    - Property 'GoalEntity.targetAmount' of type 'object' has unknown object type 'Amount'
2020-05-08 00:06:04.269 25950-25950/com.finca.bank E/[Koin]: Instance creation error : could not create instance for [Single:'io.realm.Realm']: java.lang.IllegalStateException: Schema validation failed due to the following errors:
    - Property 'GoalEntity.amount' of type 'object' has unknown object type 'Amount'
    - Property 'GoalEntity.targetAmount' of type 'object' has unknown object type 'Amount'
    	io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
    	io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:171)
    	io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:241)
    	io.realm.BaseRealm.<init>(BaseRealm.java:136)
    	io.realm.BaseRealm.<init>(BaseRealm.java:103)
    	io.realm.Realm.<init>(Realm.java:163)
    	io.realm.Realm.createInstance(Realm.java:499)
    	io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:360)
    	io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:290)
    	io.realm.Realm.getDefaultInstance(Realm.java:407)
    	core.di.CommonModule$createModule$1$15.invoke(CommonModule.kt:131)
    	core.di.CommonModule$createModule$1$15.invoke(CommonModule.kt:44)
    	org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:50)
    	org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:40)
    	org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:48)
    	org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:87)
    	org.koin.core.scope.Scope.resolveInstance(Scope.kt:209)
    	org.koin.core.scope.Scope.access$resolveInstance(Scope.kt:31)
    	org.koin.core.scope.Scope$get$1.invoke(Scope.kt:172)
    	org.koin.core.time.MeasureKt.measureDurationForResult(Measure.kt:50)
    	org.koin.core.scope.Scope.get(Scope.kt:171)
    	com.finca.feature.home.HomeModule$create$1$2.invoke(HomeModule.kt:97)
    	com.finca.feature.home.HomeModule$create$1$2.invoke(HomeModule.kt:36)
    	org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:50)
    	org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:40)
    	org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:48)
    	org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:87)
    	org.koin.core.scope.Scope.resolveInstance(Scope.kt:209)
    	org.koin.core.scope.Scope.access$resolveInstance(Scope.kt:31)
    	org.koin.core.scope.Scope$get$1.invoke(Scope.kt:172)
    	org.koin.core.time.MeasureKt.measureDurationForResult(Measure.kt:50)
    	org.koin.core.scope.Scope.get(Scope.kt:171)
    	com.finca.feature.home.HomeModule$create$1$3.invoke(HomeModule.kt:101)
    	com.finca.feature.home.HomeModule$create$1$3.invoke(HomeModule.kt:36)
    	org.koin.core.instance.InstanceFactory.create(InstanceFactory.kt:50)
    	org.koin.core.instance.SingleInstanceFactory.create(SingleInstanceFactory.kt:40)
    	org.koin.core.instance.SingleInstanceFactory.get(SingleInstanceFactory.kt:48)
    	org.koin.core.registry.InstanceRegistry.resolveInstance$koin_core(InstanceRegistry.kt:87)
    	org.koin.core.scope.Scope.resolveInstance(Scope.kt:209)

**Comment by rorbech** [comment]
Are you certain that you actually have moved the `Amount` class along? Maybe could also be something with incremental building that causes it to somehow not pick up the changes. Have you tried doing a clean build?
