### ISSUE TITLE
Optional fields in migration Kotlin 

### ISSUE THREAD

**Issue by Jparrgam** [realm/realm-java#5887]
Hi
the migration of optional kotlin objects in realm generates the following error.

> java.lang.RuntimeException: Unable to create application com.merqueo.app.AppController: io.realm.exceptions.RealmMigrationNeededException: Migration is required due to the following errors:
   - Property 'ProductTracker.departmentId' has been made optional.
   - Property 'ProductTracker.shelfId' has been made optional.
   - Property 'ProductTracker.price' has been made optional.
   - Property 'ProductTracker.specialPrice' has been made optional.
   - Property 'ProductTracker.bestPriceGuaranteed' has been made optional.
   - Property 'ProductTracker.position' has been made optional.

**Comment by Zhuinden** [comment]
Don't put `?` after the type

**Comment by Jparrgam** [comment]
@Zhuinden in this example project from realm, class model contain optionals values 

![screen shot 2018-04-10 at 2 06 34 pm](https://user-images.githubusercontent.com/8985838/38578090-80bfe48c-3cc8-11e8-93a6-4f6fcba333d9.png)

**Comment by cmelchior** [comment]
@Jparrgam Yes, and that is what the exception says. You made the fields optional, but the on-disk schema still things they are required. So you need to migrate the schema: https://realm.io/docs/java/latest/#migrations

**Comment by Zhuinden** [comment]
You could set a default value then, like `var name : String = ""`

**Comment by lemberh** [comment]
Related question
In migration I'm adding few optional fields:
```
realm.schema.get("Class")?.apply {
            addField("lat", Double::class.java)
            addField("lng", Double::class.java)
      }
```
that is how they look in model
```
var lat: Double? = null
var lng: Double? = null
```
but after migration I got exception
>Migration is required due to the following errors: - Property 'Class.lat' has been made optional.

**Comment by Zhuinden** [comment]
That's not possible if your migration actually ran, unless you had previously had `lat: Double = 0.0` or something. :/

**Comment by cmelchior** [comment]
I think a bell rings somewhere. If I remember correctly then in in Kotlin `Double:class` is actually `double` in Java, not `Double`.

So changing nullability in Kotlin migrations require you to set `nullable(true)` explicitely. We had an older issue at some point, but I cannot find it right now

**Comment by cmelchior** [comment]
Ah yeah. Here it is: https://github.com/realm/realm-java/issues/4701#issuecomment-307489143
I don't know why we didn't add this to the Kotlin section of the website. I'll do that now.

**Comment by Zhuinden** [comment]
@cmelchior Yeah, `javaPrimitiveType` is `double`, but this guy has a `Double?` so "making the field nullable" shouldn't be a problem

**Comment by cmelchior** [comment]
I added it to the website docs under the Kotlin section. Should be online shortly

**Comment by dsuresh-ap** [comment]
I found that you can also use  `Double::class.javaObjectType` which will give you the wrapper class
