### ISSUE TITLE
Can't view realm database file

### ISSUE THREAD

**Issue by jglanfield** [realm/realm-java#5888]
#### Goal

I would like to be able to view an exported .realm file.

#### Expected Results

Realm Browser: should be able to open an exported .realm file

Realm Studio: should be able to open an exported .realm file

#### Actual Results

Realm Browser: asks me to enter an encryption key (i'm not using encryption, that I know of)

Realm Studio: can't open the .realm file due to "bad file size"

#### Steps & Code to Reproduce

Export the .realm file from the device using ADB.
Try opening the exported .realm file with Realm Browser or Realm Studio.
Will not open.

#### Version of Realm and tooling
Realm version(s): 5.0.0

Realm sync feature enabled: Not sure.

Android Studio version: 3.0.1

Which Android version and device: Android 8.1 on Pixel 2

(I'm happy to ask this somewhere else if there is a more appropriate place.)

**Comment by Zhuinden** [comment]
Export the Realm file from device with ADB why? You can use Android File Explorer and save it without much hacking.

**Comment by jglanfield** [comment]
Ok, thanks for the insight. When I locate the file in the File Explorer, I associate it with .sql (probably wrong, but wasn't sure what else to select), and it is unreadable. How should I open it?
