### ISSUE TITLE
Poor behavior of Realm with transient keyword

### ISSUE THREAD

**Issue by AntonAndreevEpam** [realm/realm-java#5889]
#### Goal
I am having few cases where I needed to exclude fields from Gson serialization, but I need them in my Realm database.

#### Expected Results
Previously I used `transient` keyword for such cases and it worked fine. 

#### Actual Results
Right now I'm having `java.lang.IllegalArgumentException: Field does not exist` exception when trying to do a query by using field marked as `transient`.

I found out that this is happening because of behavior implemented in this issue #4279 

Fields marked as `transient` are ignored even if I put `@Required` on them. 

#### Version of Realm and tooling
Realm version(s): 5.0.0

**Comment by Zhuinden** [comment]
Transient fields are implicitly ignored since 3.2.0 and it's perfectly fine that way (#4279).

**Comment by AntonAndreevEpam** [comment]
Hmm, somehow I missed @Expose annotation and used `excludeFieldsWithModifiers(Modifier.TRANSIENT)` instead.
Thank you for enlighten me.
