### ISSUE TITLE
Integrate ADB into Realm Studio

### ISSUE THREAD

**Issue by eygraber** [realm/realm-java#5894]
Using Realm Studio is extremely annoying, because anytime something changes, I have to copy the realm file from the Android device to my local filesystem so that Realm Studio can read it.

There should be an option to give RealmStudio a path on the Android device, and use adb to sync it to the local filesystem.

Not sure where to file requests for Realm Studio, so I put it here.

**Comment by cmelchior** [comment]
Issue moved to [realm/realm-object-server #358](https://github.com/realm/realm-object-server/issues/358) via [**ZenHub**](https://www.zenhub.com/)

**Comment by cmelchior** [comment]
@eygraber 
We are working on open sourcing the Realm Studio repo, in the meantime I moved the issue to the appropriate place. I do agree with you though that the experience around syncing files from the device could be improved.
