### ISSUE TITLE
RealmChangeListener does not worked

### ISSUE THREAD

**Issue by luao419** [realm/realm-java#5901]
#### Goal

> What do you want to achieve?

#### Expected Results

> RealmChangeListener should be worked.

#### Actual Results

> It worked with executeTransaction，but does not with executeTransactionAsync.

#### Code Sample

```java

   RealmResults<CheckListItem> checkListItems = mRealm.where(CheckListItem.class).isNotNull("id")
                .findAllAsync();
        checkListItems.addChangeListener(new RealmChangeListener<RealmResults<CheckListItem>>() {
            @Override
            public void onChange(RealmResults<CheckListItem> checkListItems) {
                Log.i("MAIN_APPLICATION", "  --------- callBack");
            }
        });


        RealmResults<CheckListItem> all = mRealm.where(CheckListItem.class).findAll();
        mRealm.beginTransaction();
        all.get(1).setContent("11111");
        mRealm.commitTransaction();;//it worked 

        RealmResults<CheckListItem> all = mRealm.where(CheckListItem.class).findAll();
        mRealm.beginTransaction();
        all.deleteFromRealm(1);
        mRealm.commitTransaction();// It did not work.
> in gists/repositories or privately at help@realm.io)

```

#### Version of Realm and tooling
Realm version(s): 4.3.1

Realm sync feature enabled: yes

Android Studio version: 3.1.1

Which Android version and device: api25

**Comment by Zhuinden** [comment]
As it says in the [docs](https://realm.io/docs/java/5.0.0/api/io/realm/RealmResults.html#addChangeListener-io.realm.RealmChangeListener-):

> Registering a change listener will not prevent the underlying RealmResults from being garbage collected. If the RealmResults is garbage collected, the change listener will stop being triggered. To avoid this, keep a strong reference for as long as appropriate e.g. in a class variable.
> 
>  
> ```
>  public class MyActivity extends Activity {
> 
>      private RealmResults<Person> results; // Strong reference to keep listeners alive
> 
>      \@Override
>      protected void onCreate(Bundle savedInstanceState) {
>        super.onCreate(savedInstanceState);
>        results = realm.where(Person.class).findAllAsync();
>        results.addChangeListener(new RealmChangeListener<RealmResults<Person>>() {
>            \@Override
>            public void onChange(RealmResults<Person> persons) {
>                // React to change
>            }
>        });
>      }
>  }
> ```
