### ISSUE TITLE
Documentation: Threading example doesn't retain strong reference to async query result

### ISSUE THREAD

**Issue by Zhuinden** [realm/realm-java#5903]
https://realm.io/docs/java/latest/#threading-example

``` java
// in a Fragment or Activity, etc
@Override
public void onActivityCreated(Bundle savedInstanceState) {
    // ... boilerplate omitted for brevity
    realm = Realm.getDefaultInstance();
    // get all the customers
    RealmResults<Customer> customers = realm.where(Customer.class).findAllAsync();
```

I'm pretty sure I've reported this before, but this results would still be consumed by GC and stop notifying.

**Comment by Zhuinden** [comment]
Oh wait, I remember.

The assumption is that you give the results to the Adapter, so the Adapter retains the strong ref.

Can you guys add that to the example, that it is passed to adapter? Just for sake of clarity

**Comment by cmelchior** [comment]
Fixed. The docs should be online in ~10 minutes.

**Comment by Zhuinden** [comment]
Thanks! 😄
