### ISSUE TITLE
How Realm Cloud sync selected tables only

### ISSUE THREAD

**Issue by kainjinez** [realm/realm-java#5905]
How to sync only tables which is selected? For example: I have 3 tables: user / eat / play. I only want to sync table user and eat. How to do that?

#### Version of Realm and tooling
Realm version(s): 4.3.1

Realm sync feature enabled: yes

Android Studio version: Android Studio 3.1.1

Which Android version and device: Android Oreo

**Comment by Zhuinden** [comment]
Use a `.partialRealm()` as SyncConfiguration property

**Comment by kainjinez** [comment]
Thanks. I tried it and i see it can't sync down from server to device. But if i want it doesn't sync up?

**Comment by cmelchior** [comment]
I'm not sure what you mean? If you enable partial synchronization it should synchronize both ways.

**Comment by kainjinez** [comment]
I cloned PartialSync project on Github and changed `findAllAsync` to `findAll` to let it scan in local db only:
`RealmResults<Project> projects = realm
                .where(Project.class)
                .equalTo("owner", SyncUser.current().getIdentity())
                .sort("timestamp", Sort.DESCENDING)
                .findAll();`
Then I tried to add value on cloud, it did not show -> ok
But when I add Project using this:
`.setPositiveButton("Add", (dialog, which) -> realm.executeTransactionAsync(realm -> {
                        Project project = new Project();
                        String userId = SyncUser.current().getIdentity();
                        String name = taskText.getText().toString();

                        project.setId(UUID.randomUUID().toString());
                        project.setOwner(userId);
                        project.setName(name);
                        project.setTimestamp(new Date());

                        realm.insert(project);
                    }))`
It shown and disappear in recyclerview immediately. And this project's record pushed to cloud.
What i mean is when I don't want Project table be syncable, created record won't be push to cloud.
Sorry for my bad English!

**Comment by cmelchior** [comment]
So to be clear. You have some tables in you Realm you want to be local only and others that are synced. No matter what happens to them?

**Comment by Zhuinden** [comment]
If you want a non-synchronized Realm, then you need a second RealmConfiguration which is not a SyncConfiguration. That way it would not be stored in Realm Cloud.

**Comment by kainjinez** [comment]
@cmelchior Yes. I have some temporary tables inside only 1 Realm and I don't want to sync them to cloud, only primary tables able to sync up.
@Zhuinden I've thought about your idea before. But can RealmConfiguration and SyncConfiguration orient to same realm database?

**Comment by Zhuinden** [comment]
@kainjinez you can use same schema but they'd need to be specified as two different files
