### ISSUE TITLE
How to query data from server sequentially

### ISSUE THREAD

**Issue by kainjinez** [realm/realm-java#5911]
I want to getting data in 3 tables on realm server and mix + sort them manually in a AsyncTask. So how to query findAllAsync sequentially? I tried findAll but got no data and findAllAsync needs callback but i can't do it in AsyncTask. Thanks

#### Version of Realm and tooling
Realm version(s): 5.0.0

Realm sync feature enabled: yes

Android Studio version: 3.1.1

Which Android version and device: Oreo

**Comment by cmelchior** [comment]
It sounds like you don't need them sequentially, but just need to know when all the data is there? If that is correct then you can use our ProgressListeners to know when all the data is there. See https://realm.io/docs/java/latest/#progress-notifications

**Comment by kainjinez** [comment]
I have more than 3 tables and i only want to track changes only 3 tables above. I've checked the ProgressListener, it looks like tracking all database. Any other way to archive this?
