### ISSUE TITLE
RealmObject is not a part of the schema of this realm

### ISSUE THREAD

**Issue by preyesm** [realm/realm-java#5913]
Hi, I have gone through most the issues under the same title, but my use case is bit different and hence wanted to clarify few things on the ways to use realm.
I am moving from MVC architecture to the MVP and for so long we had dependency on a separate application(**Dependent**) which defined realm in its gradle and was providing the realm classes to the parent application(**Parent**) depending on it. But I am looking to remove this dependency and slowly converge both the projects into one.

Steps:
1. Have moved realm classpath to project level
2. apply plugin: realm-android is given on both the application level gradle.
3. Singleton realm instance is created on the dependent application **Dependent**.
4. have defined classes extending from realm in both the projects(as I said gradually we ll merge)
5. classes defined in application **Parent** extends from realm which gives error that this model is not part of the schema for this realm. 

Am i right in using realm in two applications under same project using same singleton instance.

**Comment by cmelchior** [comment]
If you want to use Realm model classes from a library project or other module, you need to expose them using a `RealmModule`. You can read more here: https://realm.io/docs/java/latest/#schemas

**Comment by preyesm** [comment]
@cmelchior , thanks for pointing out to the location. I ll read through this and get back, If I am stuck

**Comment by cmelchior** [comment]
I assume you found a solution to your problem. If not feel free to reopen the issue.
