### ISSUE TITLE
Host realm on maven central

### ISSUE THREAD

**Issue by vanniktech** [realm/realm-java#5914]
Would it be possible to host realm also on maven central? jcenter / bintray has been having some problems lately and mavenCentral is more reliable. This is similar to #434

**Comment by cmelchior** [comment]
Hi @vanniktech 
We have no current plans to move to Maven Central. Can you elaborate on the problems on JCenter?

**Comment by vanniktech** [comment]
JCenter / Bintray was down yesterday for quite some hours and has been down a few weeks ago for almost one and a half days.

If you use Bintray for publishing you can activate a [syncing mechanism](https://bintray.com/docs/usermanual/uploads/uploads_syncingwiththirdpartyplatforms.html).

**Comment by vanniktech** [comment]
No longer using realm.
