### ISSUE TITLE
Super slow comparing RealmResults

### ISSUE THREAD

**Issue by mkaflowski** [realm/realm-java#5917]
I got some list of object from database:
```java
newSubscribedEpisodes = realm.where(Episode.class).equalTo("isNew", true).sort("publishedDate", Sort.DESCENDING).findAll();
```
There is about 1100 results.

I check if those results are in the other list (about 1000 elements): 
```java
       for (Episode episode : newSubscribedEpisodes) {
            KLog.d(podcast + " " +episode + " pol");
            KLog.w(episodes.contains(episode) + " pol");
        }
```
And it takes about 10 seconds. But when I do a copy of the realm results list it takes 0,5s.
```java
       realm.copyFromRealm(newSubscribedEpisodes)
```

It could be a walkaround but for bigger lists I get OOM for copyFromRealm().

**Comment by Zhuinden** [comment]
> I check if those results are in the other list 

what other list?

**Comment by mkaflowski** [comment]
I get episodes from rss into List<Episode> episodes and want to compare with the episodes in database.

**Comment by Zhuinden** [comment]
Any reason why you aren't just `insertOrUpdate()`ing the new episode list?

**Comment by mkaflowski** [comment]
I want to show user notifications with new episodes so I need to get the difference between the lists. I use removeAll but this is the same case. It is very fast with the copy list and slow with realm result list.

**Comment by cmelchior** [comment]
It isn't terribly surprising that        
```
newSubscribedEpisodes = realm.where(Episode.class).equalTo("isNew", true).sort("publishedDate", Sort.DESCENDING).findAll();
for (Episode episode : newSubscribedEpisodes) {
            KLog.w(episodes.contains(episode) + " pol");
}
```
is slow. You are running an O^2 algorithm which is about 1.2 million comparisons in your case, which for the RealmResult case have to go through JNI which is definitely slower than doing it in-memory. I'm a bit surprised that is so much slower though. Note that `equals` can be a dangerous method when iterating objects like you do since the generated method pulls in all fields in order to compare objects. Creating a lightweight custom equals method might help quite a lot here.

**Comment by mkaflowski** [comment]
My equals() looks that:
```
@Override
    public boolean equals(Object obj) {
        if (obj == null)
            return false;
        Episode episode = (Episode) obj;
        return episode.id != null && id != null && episode.id.equals(id);
    }
```

**Comment by nhachicha** [comment]
can't you extract only the episodes ids from RSS then use `not in` to discriminate episodes in Realm which are not from the RSS feed, this way you don't have to `copyFromRealm` or iterate the `RealmResults` to do the comparison outside 

Something like 
```Java
String[] listOfRSSEpisodeIds = new String[]{"1", "7"};
realm.where(Episode.class)
                           .not()
                           .in("id", listOfRSSEpisodeIds)
                           .findAllAsync();
```

**Comment by cmelchior** [comment]
Above solution seems to have worked. Closing
