### ISSUE TITLE
RealmMigrationNeededException: Migration is required due to the following errors

### ISSUE THREAD

**Issue by firelion0725** [realm/realm-java#5921]
Caused by: io.realm.exceptions.RealmMigrationNeededException: Migration is required due to the following errors:
    - Property 'PersonRealmDAO.id' has been made indexed.
    - Property 'PersonRealmDAO.name' has been made optional.
    - Property 'PersonRealmDAO.sex' has been made optional.
    - Primary Key for class 'PersonRealmDAO' has been added.

Realm： 5.0.1 AS：3.1

```
@RealmClass
public class PersonRealmDAO implements RealmModel {

    @PrimaryKey
    private long id;
    private String name;
    private String sex;

    public long getId() {
        return id;
    }

    public void setId(long id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public String getSex() {
        return sex;
    }

    public void setSex(String sex) {
        this.sex = sex;
    }
}

```
 public class MyRealmMigration implements RealmMigration {

    private final String TAG = getClass().getSimpleName();
    private long oldVersion;

    @Override
    public void migrate(@NonNull DynamicRealm realm, long oldVersion, long newVersion) {
        this.oldVersion = oldVersion;
        Log.i(TAG, "oldVersion:" + this.oldVersion);
        Log.i(TAG, "newVersion:" + newVersion);
        while (this.oldVersion < newVersion) {
            updateVersion(getUpdateFun(realm, this.oldVersion));
        }
    }

    private void updateVersion(UpdateVersion updateVersion) {
        if (updateVersion != null) {
            updateVersion.update();
        }
    }

    /**
     * 更新版本統一接口 状态模式
     */
    interface UpdateVersion {
        /**
         * 具体的更新执行
         */
        void update();
    }

    /**
     * 获取更新实际更新类
     *
     * @param oldVersion 旧版本号
     */
    private UpdateVersion getUpdateFun(@NonNull DynamicRealm realm, long oldVersion) {
        if (oldVersion == 0) {
            return new UpdateToVersion1(realm);
        }
        return null;
    }

    /**
     * 升级到版本的具体方法及版本变更详情
     */
    class UpdateToVersion1 implements UpdateVersion {

        DynamicRealm realm;

        UpdateToVersion1(DynamicRealm realm) {
            this.realm = realm;
        }

        @Override
        public void update() {
            //具体更新参考 详见 https://realm.io/docs/java/latest#migrations
            RealmSchema schema = realm.getSchema();
            RealmObjectSchema personSchema = schema.create(PersonRealmDAO.class.getSimpleName());
            Field[] fields = PersonRealmDAO.class.getDeclaredFields();
            for (Field field : fields) {
                field.setAccessible(true);
                Log.i(TAG, "name:" + field.getName());
                Log.i(TAG, "type:" + field.getType().getSimpleName());
                personSchema.addField(field.getName(), field.getType(), FieldAttribute.REQUIRED);
            }
            MyRealmMigration.this.oldVersion++;
        }
    }
 }

我做Realm升级测试 一直报错 用了反射机制 按照官方demo做的 不解哪的问题

I test realm Migration error，I use java fields to get name and type ，I don‘t know how to fix this issue.
I'm madding......

**Comment by cmelchior** [comment]
`String` is an optional type in Java since it can be `null`, but in your Migration, you are trying to make it required. If that is the case, you need to add `@Required` in the model class as well:

```
@RealmClass
public class PersonRealmDAO implements RealmModel {

    @PrimaryKey
    private long id;
    @Required
    private String name;
    @Required
    private String sex;
}
```

**Comment by firelion0725** [comment]
@cmelchior think you very much!  My demo is work, so happy. Think you again!
