### ISSUE TITLE
Implement SyncUser.deleteUser() and SyncUser.deleteRealm()

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#5922]
See https://github.com/realm/realm-object-server-private/pull/444

**Comment by sipersso** [comment]
@cmelchior The link doesn’t seem valid. 

This enhancement would be crucial to be able to implement the new European privacy rules (GDPR) that will be in effect from may 25th

**Comment by Zhuinden** [comment]
It's valid, we just don't see it as it's in private

**Comment by sipersso** [comment]
Ah, ok, that is understandable

**Comment by cmelchior** [comment]
Outdated with the integration with MongoDB. In 10.0.0-BETA.x there are API's for controlling remote users and local Realms. Deleting remote Realms is no longer a concept as the data is stored in MongoDB. But this can be controlled using a Mongo Driver or the RemoteMongoClient API's if needed.
