### ISSUE TITLE
[Android 8] Realm instance is not updated

### ISSUE THREAD

**Issue by carlosdanieldrury** [realm/realm-java#5927]
Hi guys, maybe is an issue you guys didn ´t notice but it was happening on Android 8 devices.
I could fix the problem using refresh() method to avoid inconsistent instances.

Well, let me describe my problem.

As we have to open and close realm instances, we add for all activities a method to control opening and closing actions avoiding huge databases files on device.
For services, as a message service for push notifications, we had to use the default realm instance which has access to live objects that are been handled on view.

The problem is when we have to manipulate this data on Android 8 devices. The data has been not updated when we get a push notification. the solution for that was call .refresh() method to force update.

I realize that some information was missing on this service when the data is not updated, so maybe there is something I missed or maybe it is, in fact, a gap for Android 8 devices.

Note: This only happens on Android 8 devices, other devices have a regular behavior.

Java: 8
Realm version(s): 4.3.1
Realm sync feature enabled: yes
Android Studio version: 3.0
Android version: 8.0 / Any device

**Comment by Zhuinden** [comment]
Which thread requires refresh?

**Comment by carlosdanieldrury** [comment]
Look at this piece of code:

public class MessagingService extends FirebaseMessagingService {

    @Override
    public void onMessageReceived(RemoteMessage remoteMessage) {
        handleMessage(getApplicationContext(), remoteMessage);
    }

    private void handleMessage(Context context, RemoteMessage remoteMessage) {
        Map<String, String> payload = remoteMessage.getData();
        Realm databaseInstance = null;
        try{
            databaseInstance = Realm.getDefaultInstance();
            **databaseInstance.refresh();**


Without refresh() works fine for Android < 8.0

**Comment by Zhuinden** [comment]
Nah, `onMessageReceived()` runs on a background thread, so you should verify that `Realm.getLocalInstanceCount(Realm.getDefaultConfiguration()) == 0` before calling `Realm.getDefaultInstance()` in `handleMessage`, otherwise you are having version retention because of unclosed Realm instance on non-looper background thread.

**Comment by Zhuinden** [comment]
So I think you're not closing Realm properly. You'd generally use `try(Realm realm = Realm.getDefaultInstance())` on background thread.

**Comment by carlosdanieldrury** [comment]
Well, as mentioned before, that was just a piece of code. I close realm properly in the end of code:

} finally {
            if(databaseInstance != null) {
                databaseInstance.close();
            }
        }

I didn´t add this code due to I have sensitive data on my class.

I guess as you mentioned using Realm.getLocalInstanceCount(Realm.getDefaultConfiguration()) == 0 would help, as we can check if there are threads running on view and use them.

It is weird we had this behavior only on Android 8 devices.

**Comment by cmelchior** [comment]
I assume you found a solution to your problem. If not feel free to reopen the issue.
