### ISSUE TITLE
Remove Javax.* dependency from library code

### ISSUE THREAD

**Issue by tseglevskiy** [realm/realm-java#593]
Below is the message from Lint:

InvalidPackage: Package not included in Android
../../../../../../.gradle/caches/modules-2/files-2.1/io.realm/realm-android/0.73.1/3d71534849c19a9b086bab110feba1d3ff752ce5/realm-android-0.73.1.jar: Invalid package reference in library; not included in Android: javax.tools. Referenced from io.realm.processor.RealmProxyClassGenerator.
Priority: 6 / 10
Category: Correctness
Severity: Error
Explanation: Finds API accesses to APIs that are not supported in Android.
This check scans through libraries looking for calls to APIs that are not included in Android.

When you create Android projects, the classpath is set up such that you can only access classes in the API packages that are included in Android. However, if you add other projects to your libs/ folder, there is no guarantee that those .jar files were built with an Android specific classpath, and in particular, they could be accessing unsupported APIs such as java.applet.

This check scans through library jars and looks for references to API packages that are not included in Android and flags these. This is only an error if your code calls one of the library classes which wind up referencing the unsupported package.

More info:

To suppress this error, use the issue id "InvalidPackage" as explained in the Suppressing Warnings and Errors section.

**Comment by arminelec** [comment]
This issue is still there on 0.82.2.

**Comment by jturolla** [comment]
I'm having this issue when building using `./gradlew build`, is there a workaround?

**Comment by cmelchior** [comment]
We recently migrated to a new build system where the annotation processor is not part of the final library AAR. This will fix this issue going forward. It is still only on our master branch though and has not been publicly released yet.

Full descriptions for getting it to work is in our README if you want to test it. Otherwise you need to suppress the warning as described above.

**Comment by zaki50** [comment]
Hi @jturolla 

Please use `lintOptions` in `build.gradle` to ignore `InvalidPackage` check of lint as a workaround.

```
android {

    ...

    lintOptions {
        ignore 'InvalidPackage'
    }
}
```

**Comment by jturolla** [comment]
Thank you! The lint options fixed for now. I'll be moving to the new build next week.
