### ISSUE TITLE
Realm read query time too long - 300 ms++ GUID keys (primary)

### ISSUE THREAD

**Issue by Archit256** [realm/realm-java#5931]
**Bugs**: I am using REALM on both iOS and Android - The realm read queries on android take significantly longer than on iOS. 

The query that I have traced is taking 200-300 ms ++ 

_public class Field extends RealmObject {
    @PrimaryKey
    private String id; (uuid) _ 

_public class Option extends RealmObject {
    @PrimaryKey
    private String id; (uuid)
    private Field field;_

This is the structure of the schema that I have .. I have about 4500+ options in the database and about 1500+ fields in the database. 

This is the query I have -> 
RealmResults<Option> optRes = mRealm.where(Option.class).isNotNull("field").
                    in("field.id",fieldArray).isNull("deleted_at").findAll();

the fieldArray probably has 75-100 fields with about 300+ options which should be part of the result when querying. 

**This query is taking between 250-350 ms - which is probably about 10 times what it takes on the iOS platform.** 

#### Goal
 What do you want to achieve?
Speed. 

#### Expected Results
The query to take no more than 10 - 25 ms
> ?

#### Actual Results

>  E.g. full stack trace with exception

#### Steps & Code to Reproduce

> Describe your current debugging efforts.

#### Code Sample

```java

> Your code here. Bigger samples should ideally be as separate Android Studio project, 
> in gists/repositories or privately at help@realm.io)

```

#### Version of Realm and tooling
Realm version(s): ? latest

Realm sync feature enabled: no

Which Android version and device: Samsung s8 plus - Android 8.0.0 API 26

**Comment by cmelchior** [comment]
There are a number of factors in play here.

1) The hardware between iOS and Android is different. Although a Samsung S8 is powerful it is hard to compare.

2) `in()` queries in Java is fairly expensive as it internally is converted to a JNI call pr. element in the array. It shouldn't result in 100 of milliseconds though.

3) Measuring is hard. I don't see any indication of how you measured the difference on both iOS and Android

4) Beware that there a big difference in how iOS and Android run their queries. iOS are fully lazy, meaning the query isn't actually run until you start accessing an element. On Java it is run when you call `findAll()`. So depending on how you measure I suspect this is the real culprit.

**Comment by Zhuinden** [comment]
You do get the same behavior as iOS if you use findAllAsync() though I'd think

**Comment by Archit256** [comment]
Hi Christian, 

Thanks for the quick reply - 
TimingLogger timings = new TimingLogger(TAG, "Reading from Realm");
String[] fieldArray = fieldIDList.toArray(new String[fieldIDList.size()]);
timings.addSplit("Converted field array list to field array");
RealmResults<Option> optRes = mRealm.where(Option.class).isNotNull("field").
        in("field.id",fieldArray).isNull("deleted_at").findAll();
timings.addSplit("Fetched Options for Fields");
I m using a timing logger to log the time for all the queries - so the time taken does reflect the time that it takes the query to execute. 

> in() queries in Java is fairly expensive as it internally is converted to a JNI call pr. element in the array. It shouldn't result in 100 of milliseconds though.
> 
I tried this using a loop and sending individual read requests - that pretty much takes about the same time. 
Am I measuring this incorrectly? Any advise here?

Similar queries here take significantly less time - 

05-08 13:49:05.363 17998-17998/? D/InspectionDetails: Reading from Realm:      3 ms, Fetched Sections for Template
05-08 13:49:05.363 17998-17998/? D/InspectionDetails: Reading from Realm:      12 ms, Fetched Fields for Sections -> This takes significantly less time 
05-08 13:49:05.363 17998-17998/? D/InspectionDetails: Reading from Realm:      14 ms, Mapped fields to sections
05-08 13:49:05.363 17998-17998/? D/InspectionDetails: Reading from Realm:      1 ms, Converted field array list to field array
05-08 13:49:05.363 17998-17998/? D/InspectionDetails: Reading from Realm:      212 ms, Fetched Options for Fields
05-08 13:49:05.363 17998-17998/? D/InspectionDetails: Reading from Realm:      25 ms, Mapped Options to Fields


On Swift I am using option 1 below - Option 1 takes significantly less time than option 2 although both are querying the same results. The app was jittery throughout when we used the ID method to query but querying with the actual object made it a lot faster. 

1) let optionObjects = realm.objects(inspection_template_field_option.self).filter("deleted_at == nil AND inspectionTemplateField = %@",inspectionField!)


2) let optionObjects = realm.objects(inspection_template_field_option.self).filter("deleted_at == nil AND inspectionTemplateField.id = \(inspectionField.id)").sorted(byKeyPath: "option_order" , ascending : true)

On iOS since the actual query is lazy - I checked the time it takes when I do a optionObjects.count (because this forces the query to run & evaluate).


250-350 milliseconds on android seems like a lot to fetch those results. Any advise - anywhere I am making a mistake here?

Regards
Archit

**Comment by cmelchior** [comment]
Outdated, so closing. 

Performance measurements are inherently difficult to get correct, especially across platforms. 

If you think you found a performance problem please re-open and provide a working sample project demonstrating it as guessing about performance is next to impossible without actually running code.
