### ISSUE TITLE
OrderedRealmCollectionChangeListener isnt being triggered

### ISSUE THREAD

**Issue by wrightX** [realm/realm-java#5934]
I am settinng change listener for RealmResults. I am getting updates from my server and saving them by calling copyToRealmOrUpdate on my Realm object.  Objects in that RealmResults have boolean field and if its value is being changed to false change listener is being called correctly but when value is being set to listener is not being called. What can be the reason for that and how can I fix it?

**Comment by cmelchior** [comment]
Hard to tell without seeing any code. Most likely your RealmResults is getting GC'ed which means the listener will stop being triggered.

**Comment by cmelchior** [comment]
Garbage collected, but without seeing the code in question it is hard to speculate why your listener doesn't work as expected.

**Comment by wrightX** [comment]
Ok here is code from my activity

```
private RealmResults<Parking> parkings;
private OrderedRealmCollectionChangeListener<RealmResults<Parking>> realmParkingListener =new OrderedRealmCollectionChangeListener<RealmResults<Parking>>() {
        @Override
        public void onChange(RealmResults<Parking> parkings, OrderedCollectionChangeSet changeSet) {
            for(int i=0;i<changeSet.getChanges().length;i++){
                mView.updateClusterItem(parkings.get(changeSet.getChanges()[i]));
            }
        }
    };
    Handler refreshHandler = new Handler();
    Runnable refreshRunnable = new Runnable() {
        @Override
        public void run() {
            DataProvider.getInstance().getParkings(); //this line updates realm
            refreshHandler.postDelayed(refreshRunnable, REFRESH_INTERVAL);
        }
    };

public void onStart(){
        if(parkings!=null){
            parkings.removeAllChangeListeners();
        }
        parkings = DataProvider.getInstance().getParkings();
        refreshHandler.postDelayed(refreshRunnable, REFRESH_INTERVAL);
        parkings.addChangeListener(realmParkingListener);
    }
```

**Comment by cmelchior** [comment]
Sorry for the late reply on this.  There doesn't appear to be anything inherently wrong with your code. We will probably need an example project in order to figure out what is going on.

**Comment by cmelchior** [comment]
Closing due to no response. Feel free to reopen if this is still a problem.
