### ISSUE TITLE
Realm Migration Crashing on some devices

### ISSUE THREAD

**Issue by rethinkautismdev** [realm/realm-java#5935]
#### Goal

> Add a column to a Realm Object and update the Realm with a Migration accordingly.

#### Expected Results

> The app does not crash.

#### Actual Results

> The app crashes only sometimes. Of 2k users, 200 of them have experienced a crash with migrating the Realm. The versions it occurs on spans all supported versions, 4.4 - 8.1 and across a variety of devices. The crash does not happen on any locally tested devices. Between the releases some plugins, Android Studio, and gradle has been updated but Realm has not been. It is v 4.3.0 on both versions of the app.

> Caused by io.realm.exceptions.RealmMigrationNeededException
Migration is required due to the following errors: - Property 'Container.date' has been added.

#### Steps & Code to Reproduce

> Describe your current debugging efforts.

I have been trying to update that app in a variety of states.
Open up a copy of the old version, and update it to the new version.
Before updating try not having saved data, having data saved in a variety of combinations, updating at different points in the app, etc. 
I cannot make it crash on my devices, the migration seems to be working, but the crash reports I am receiving say otherwise.

#### Code Sample

I have one realm that is a login realm where user credentials are stored, and then each user has his own realm for their respective data. The field added is only relevant to the user realm, not the login realm. 

There was no explicitly defined schema or migration before this. I added one once the migration was needed. I did not update the login realm, as it does not access or use the property.

```java

// Login Realm Setup
 RealmConfiguration realmLoginConfig = new RealmConfiguration.Builder()
                .encryptionKey(key)
                .name(USERS + ".realm")
                .deleteRealmIfMigrationNeeded()
                .build();
        realm = Realm.getInstance(realmLoginConfig);
```
```java
// User Realm Setup
RealmConfiguration realmConfiguration = new RealmConfiguration.Builder()
                .encryptionKey(realmKey)
                .name(login.getUsername() + ".realm")
                .schemaVersion(1)
                .migration(new Migration())
                .build();
        Realm.setDefaultConfiguration(realmConfiguration);
```
```java
// Migration Code
public class Migration implements RealmMigration {
    @Override
    public void migrate(DynamicRealm realm, long oldVersion, long newVersion) {
        RealmSchema schema = realm.getSchema();

        if (oldVersion == 0) {
            schema.get("Container").addField("date", String.class);
            oldVersion++;
        }
    }

    @Override
    public int hashCode() {
        return Migration.class.hashCode();
    }

    @Override
    public boolean equals(Object obj) {
        if (obj == null) {
            return false;
        }

        return obj instanceof Migration;
    }
}

```

#### Version of Realm and tooling
Realm version(s):  4.3.0

Realm sync feature enabled: no

Android Studio version: 3.1.2

Which Android version and device: 4.4 - 8.1

**Comment by rethinkautismdev** [comment]
That realm has the deleteMigrationsIfNecesary flag set, so it should reset if needed anyways.

**Comment by Zhuinden** [comment]
oh yeah, I didn't notice that. Hrmm.

**Comment by cmelchior** [comment]
So to be clear, it is the User Realm that throws this exception?
Is it possible that users have used a beta version of your app that didn't include the field?

My guess is that for some reason the on-disk Realm have a schema version that is `!= 0` which will prevent it from entering your `if`-statement, but how that happened I cannot tell from what you posted.

**Comment by rethinkautismdev** [comment]
Yes, the User Realm throws this exception, the Login Realm was not changed. I do not think it is possible for the users to have a beta version of the app.

The guess regarding schema makes sense, but I have not been able to find a reason for that to happen, especially only for some users. Is there a way to check if a realm instance has a field or not and run the migration then?

I have run into this issue with another update as well, with the app now mostly in Kotlin. It does seem like for some reason the version code gets messed up on some devices.

**Comment by anggrayudi** [comment]
I am facing this with Redmi Note 4X. In my case, I had to remove all non-Realm annotations from class members, e.g. `@BillingClient.SkuType`. I think we need to make some changes in Realm classes to trigger Realm processor to delete old Proxy.

Before:
```kotlin
    @BillingClient.SkuType
    var type: String? = null
```

After:
```kotlin
    var type: String? = null
```

I don't know why this happens. Please fix this bug ASAP. I am using Realm 5.9.1 without ObjectServer.

**Comment by cmelchior** [comment]
Outdated, so closing. If this is still a problem please re-open and provide a sample project demonstrating the issue so we can debug it.
