### ISSUE TITLE
Make it easy to delete serverside Realm during development

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#5936]
From https://realmio.slack.com/files/U03426T1Y/FAMG06LNT/Findings_from_implementing_Partial_Sync_in_an_app

> 8 ) Make it easy to delete server Realm on schema changes
The rapid development cycle is extremely annoying on a partial synced Realm. For every change you need A) Goto the instance and delete the reference + partial Realm B) delete the app on the device to avoid client resets. It would be nice if deleteRealmIfMigrationRequired was also available for synced Realms and it would also delete the server Realm (or some other easy-to-use option).

Suggesed API:

```
// Will delete both server and local Realm 
// Requires an admin user otherwise the server Realm cannot be deleted.
// Naming is hard ....
SyncConfiguration.Builder(user, url)
  .deleteServerAndLocalRealmIfMigrationRequired()   
  .build()
```

This API will probably be a bit difficult to implement as deleting a Realm requires a REST API call, but since this option should only be used in development, blocking the UI thread until it completes is probably acceptable. We should most likely put very strict checks into it so the option can never be used in a release build.

**Comment by nhachicha** [comment]
The current use case narrows it down only to migration, should we instead add a general API to delete Realms?

**Comment by cmelchior** [comment]
No longer relevant with MongoDB as the backend.
