### ISSUE TITLE
Format Date field type return wrong value

### ISSUE THREAD

**Issue by kkooff114** [realm/realm-java#5939]
Hi, I got an issue from my customer, he submitted an order on 2018-04-21, but our system received the date is 2018-01-01.
I got log from his mobile and found the value in realm database file is right . but, after `String d = new SimpleDateFormat("yyyy-MM-dd").format(value)` , `d` become "2018-01-01"

The value in realm database file : `2018年4月21日 上午11:01:45`

Java code:

```
OrderUploader order = realms.where(OrderUploader.class)
                                        .equalTo("uploadStatus", Constant.STATUS_UPLOAD)
                                        .findFirst();
String d = new SimpleDateFormat("yyyy-MM-dd").format(order.getCreateTime()) // d = "2018-01-01"
```

What can I do for this issue.
realm(4.3.1)

**Comment by Zhuinden** [comment]
What is `order.getCreateDate()?

**Comment by kkooff114** [comment]
@Zhuinden Date

**Comment by nhachicha** [comment]
@kkooff114 `SimpleDateFormat` is using the default locale which might be different for the user device, maybe uses `SimpleDateFormat(String pattern, Locale locale)` instead. 

You can check that Realm is storing the correct date by checking the epoch value  `createTime.getTime()` you then check it using https://www.epochconverter.com/ for example

**Comment by kkooff114** [comment]
@nhachicha I'm sure the storage time is correct and use the right locale. It is important that, there is no problem with the data next to this problematic date from the mobile log. 

It looks like `order.getCreateTime()` from Realm contains only the year information, but other information is missing.

Only occasional.

**Comment by nhachicha** [comment]
@kkooff114 just to confirm,

> It looks like order.getCreateTime() from Realm contains only the year information

How are you observing this? via the log? does the log display the timestamp or the date formatted via the SDF? I'm trying to figure our if Realm occasionally saves only the year (which I doubt since the date support was added a while ago) or the transformation into the `Date` object & using SDF is sometimes bogus 

I recommend adding the timestamp to the logs as well so when you observe aninvalid date you can check if it's saved correctly in Realm

**Comment by cmelchior** [comment]
Technically storing as a Realm Date allows nano-second precision, but the Date class in Java doesn't support that so for the intent of storing `java.util.Date` either should work.

**Comment by cmelchior** [comment]
@kkooff114 I assume the above answered your question. If not feel free to reopen the issue.
