### ISSUE TITLE
When App is closed getting error Callback cannot be delivered on current thread Realm cannot be automatically updated on a thread without a looper.

### ISSUE THREAD

**Issue by sudhanshugaur4** [realm/realm-java#5940]
I am trying to Add a record in Realm using insertOrUpdate when my App is closed(When my app receives a push notification through firebase) but I am getting the error.

> Callback cannot be delivered on current thread. Realm cannot be automatically updated on a thread without a looper.

**Comment by Zhuinden** [comment]
You're trying to add a change listener or call an async transaction with an onsuccess/onerror callback on a thread that does not have a looper

**Comment by sudhanshugaur4** [comment]
Yeah got the solution.

**Comment by Redhac** [comment]
can you share your solution pls ?

**Comment by sudhanshugaur4** [comment]
@Redhac The solution is don't use async transaction because as there is no looper attached.
