### ISSUE TITLE
Get username from user identity

### ISSUE THREAD

**Issue by kainjinez** [realm/realm-java#5941]
How to get username (and other info like email, social id..v.v not password) if i have user identity?

**Comment by cmelchior** [comment]
You can call `SyncUser.retrieveInfoForUser()` which will return the metadata for the user that is stored on the server.

**Comment by kainjinez** [comment]
I got this message while using
```
user.retrieveInfoForUserAsync("65622bc0f3bb85b8248f1ef85e5e5777", SyncCredentials.IdentityProvider.USERNAME_PASSWORD, new SyncUser.Callback<SyncUserInfo>() {
                    @Override
                    public void onSuccess(SyncUserInfo result) {
                        Log.i("hieu", "");
                    }

                    @Override
                    public void onError(ObjectServerError error) {
                        Log.i("hieu", "");
                    }
                });
```
`SyncUser needs to be admin in order to lookup other users ID.`
Any way to make regular user A to get user B's email if user A is not an Admin?

**Comment by nhachicha** [comment]
There's no such API for now (besides the admin approach highlighted before). Is it an option to store the username locally, you can, for example, have a table that stores the user config & uses the identity as a PK
