### ISSUE TITLE
Sync data local to remote - Android

### ISSUE THREAD

**Issue by jreyes256** [realm/realm-java#5945]
#### Goal

> Synchronize local data to a remote server

#### Expected Results

> I need to synchronize my local data to my Realm server, only the classes are created, what is the optimal way to send data to the server?

#### Actual Results

>  Only classes are created

#### Steps & Code to Reproduce

> Describe your current debugging efforts.
![image](https://user-images.githubusercontent.com/25693015/39937197-93ccdb98-5514-11e8-9084-ca3a10748791.png)

#### Code Sample

 private void onLoginSuccess(SyncUser user) {
        // Building syncing configuration using received authorized user
        SyncConfiguration syncConfiguration = new SyncConfiguration.Builder(user, REALM_URL)
                .errorHandler(new SyncSession.ErrorHandler() {
                    @Override
                    public void onError(SyncSession session, ObjectServerError error) {
                        Log.d(TAG, "onSyncSessionError: " + error.toString());
                    }
                })
                // waiting for until remote data arrives
                .waitForInitialRemoteData()
                .build();

        Realm.getInstanceAsync(syncConfiguration, new Realm.Callback() {
            @Override
            public void onSuccess(Realm realm) {
                onRealmInstanceReceived(realm);
            }
        });
    }

    private void onRealmInstanceReceived(Realm realm) {
        this.database = realm;
        queryRealmData();
        setChangeListeners();
    }

    private RealmResults<Usuario> usuarioList;
    // Change Listeners
    private GlobalChangeListener globalChangeListener = new GlobalChangeListener();
    private OrderedRealmChangeListener<Usuario> usuariosChangeListener = new OrderedRealmChangeListener<>("Usuario");

    private void queryRealmData() {
        this.usuarioList = this.database.where(Usuario.class).findAllAsync();
        //this.usuarioList = usuarioDao.findAllContainingSugarAsync();
    }

    private void setChangeListeners() {
        this.database.addChangeListener(globalChangeListener);
        this.usuarioList.addChangeListener(usuariosChangeListener);
    }

    private static class GlobalChangeListener implements RealmChangeListener<Realm> {
        @Override
        public void onChange(Realm realm) {
            Log.d(TAG, "onGlobalChange: ");
        }
    }

    private static class OrderedRealmChangeListener<T extends RealmModel> implements OrderedRealmCollectionChangeListener<RealmResults<T>> {

        private final String name;

        private OrderedRealmChangeListener(String name) {
            this.name = name;
        }

        @Override
        public void onChange(RealmResults<T> realmResults, OrderedCollectionChangeSet changeSet) {
            Log.d(TAG, "EEEEHHHH: ");
            if (changeSet != null) {
                for (OrderedCollectionChangeSet.Range range : changeSet.getChangeRanges()) {
                    Log.d(TAG, name + " onChange. Range startIndex = " + range.startIndex + ". Range length = " + range.length);
                }

                for (OrderedCollectionChangeSet.Range range : changeSet.getDeletionRanges()) {
                    Log.d(TAG, name + " onDelete. Range startIndex = " + range.startIndex + ". Range length = " + range.length);
                }

                for (OrderedCollectionChangeSet.Range range : changeSet.getInsertionRanges()) {
                    Log.d(TAG, name + " onInsert. Range startIndex = " + range.startIndex + ". Range length = " + range.length);
                }
            }
        }
    }

> Your code here. Bigger samples should ideally be as separate Android Studio project, 
> in gists/repositories or privately at help@realm.io)

```

#### Version of Realm and tooling
Realm version(s): 5.1.0

Realm sync feature enabled: yes

Android Studio version: 3.1.2

Which Android version and device: 6.0.1

**Comment by cmelchior** [comment]
Data should synchronize automatically. Is there no information being printed in the log?

Alternatively, you can force the client to upload data using `SyncManager.getSession(syncConfig).uploadAllLocalChanges()`

**Comment by jreyes256** [comment]
What would be the correct procedure to synchronize my local data to the server, example please.

**Comment by Zhuinden** [comment]
It should be automatic if you write into the Realm and have at least 1 open instance.

**Comment by jreyes256** [comment]
but if I have the data stored locally because I also work offline

**Comment by cmelchior** [comment]
You can find a simple example here: https://github.com/realm/realm-java/tree/master/examples/objectServerExample

But like @Zhuinden said, Realm will automatically sync in the background, including automatic resuming it if you go from offline to online.

**Comment by jreyes256** [comment]
@cmelchior  Does this code work locally and remotely? I clarify another doubt that I can have data by users and all grouped in the default

**Comment by Zhuinden** [comment]
if you are using Sync Realm then yes

**Comment by cmelchior** [comment]
I assume the above answered your question. If not, feel free to reopen.
