### ISSUE TITLE
What REALM_CORE_VERSION is included in realm-java?

### ISSUE THREAD

**Issue by stephenlaughton** [realm/realm-java#5947]
#### Goal

Clarity on which REALM_CORE_VERSION is included in this SDK. This is available in most of the other realm SDKs and I am trying to match REALM_CORE_VERSION across platforms (including realm-js).
![screen shot 2018-05-11 at 2 34 30 pm](https://user-images.githubusercontent.com/11642718/39948034-0894d57a-5529-11e8-8d12-adfa113b3115.png)

#### Expected Results

To see REALM_CORE_VERSION in `dependencies.list`

#### Actual Results

Do not see REALM_CORE_VERSION in `dependencies.list`

#### Steps & Code to Reproduce

> Describe your current debugging efforts.

#### Code Sample

```java

> Your code here. Bigger samples should ideally be as separate Android Studio project, 
> in gists/repositories or privately at help@realm.io)

```

#### Version of Realm and tooling
Realm version(s): ?

Realm sync feature enabled: no

Android Studio version: ?

Which Android version and device: ?

**Comment by Zhuinden** [comment]
You can check the changelog.md for info on this

**Comment by cmelchior** [comment]
The reason it isn't in `dependencies.list` is that Java includes it as part of the sync dependency due to build system reasons. In any case, the `dependencies.list` is just an internal tool, but like @Zhuinden says, the information should be in the changelog.
