### ISSUE TITLE
This Realm instance has already been closed, making it unusable.

### ISSUE THREAD

**Issue by preyesm** [realm/realm-java#5949]
Hi,
This crash doesnt happen on my test mobile but has been reportedly very frequently on my client's devices. So the use case is
1. I have page which display feeds of any particular group
2. I click on the list of groups and it crashes with the above error, when i try to load the groups in recycler view.

I open my realm instance at the application level and close it only when the user logs out of the app. 

Crash location:
 @Override
    public void bindViewHolder(FlexibleAdapter adapter, final GroupViewHolder holder, int position, List payloads) {
        *holder.binding.groupName.setText(networkGroupCache.getGroupName());*
        if (networkGroupCache.getMemberCount() != null) {
            holder.binding.totalAgents.setText("5 Agent");
        }
        holder.binding.unreadCount.setTag(networkGroupCache.getId());
        setAgentImages(holder);
NetworkGroupCache is a ream object.
It crashes in the bolded lines, i do not understand why, the instance is closed. The logs are below

Last Exception Backtrace
--
0 | java.lang.IllegalStateException: This Realm instance has already been closed, making it unusable.
1 | at io.realm.n.e(BaseRealm.java:421)
2 | at io.realm.NetworkGroupCacheRealmProxy.q(NetworkGroupCacheRealmProxy.java:190)
3 | at com.agendesks.android.datahandler.realmModel.network.NetworkGroupCache.h(NetworkGroupCache.java:135)
4 | at com.agentdesks.android.crm.fragments.network.GroupSectionItem.bindViewHolder(GroupSectionItem.java:60)
5 | at com.agentdesks.android.crm.fragments.network.GroupSectionItem.bindViewHolder(GroupSectionItem.java:34)
6 | at eu.davidea.flexibleadapter.b.onBindViewHolder(FlexibleAdapter.java:1396)
7 | at android.support.v7.widget.RecyclerView$Adapter.bindViewHolder(RecyclerView.java:6515)
8 | at android.support.v7.widget.RecyclerView$Recycler.tryBindViewHolderByDeadline(RecyclerView.java:5458)
9 | at android.support.v7.widget.RecyclerView$Recycler.tryGetViewHolderForPositionByDeadline(RecyclerView.java:5724)
10 | at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5563)
11 | at android.support.v7.widget.RecyclerView$Recycler.getViewForPosition(RecyclerView.java:5559)
12 | at android.support.v7.widget.LayoutState.next(LayoutState.java:100)
13 | at android.support.v7.widget.StaggeredGridLayoutManager.fill(StaggeredGridLayoutManager.java:1570)
14 | at android.support.v7.widget.StaggeredGridLayoutManager.onLayoutChildren(StaggeredGridLayoutManager.java:682)
15 | at android.support.v7.widget.StaggeredGridLayoutManager.onLayoutChildren(StaggeredGridLayoutManager.java:604)
16 | at android.support.v7.widget.RecyclerView.dispatchLayoutStep2(RecyclerView.java:3693)
17 | at android.support.v7.widget.RecyclerView.onMeasure(RecyclerView.java:3109)
18 | at android.view.View.measure(View.java:23279)
19 | at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6928)
20 | at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
21 | at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
22 | at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
23 | at android.view.View.measure(View.java:23279)
24 | at android.support.v4.widget.NestedScrollView.measureChildWithMargins(NestedScrollView.java:1446)
25 | at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
26 | at android.support.v4.widget.NestedScrollView.onMeasure(NestedScrollView.java:512)
27 | at android.view.View.measure(View.java:23279)
28 | at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6928)
29 | at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
30 | at android.view.View.measure(View.java:23279)
31 | at android.widget.RelativeLayout.measureChildHorizontal(RelativeLayout.java:715)
32 | at android.widget.RelativeLayout.onMeasure(RelativeLayout.java:461)
33 | at android.view.View.measure(View.java:23279)
34 | at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6928)
35 | at android.support.design.widget.CoordinatorLayout.onMeasureChild(CoordinatorLayout.java:714)
36 | at android.support.design.widget.CoordinatorLayout.onMeasure(CoordinatorLayout.java:786)
37 | at android.view.View.measure(View.java:23279)
38 | at android.support.v4.widget.DrawerLayout.onMeasure(DrawerLayout.java:1060)
39 | at android.view.View.measure(View.java:23279)
40 | at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6928)
41 | at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
42 | at android.support.v7.widget.ContentFrameLayout.onMeasure(ContentFrameLayout.java:139)
43 | at android.view.View.measure(View.java:23279)
44 | at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6928)
45 | at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
46 | at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
47 | at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
48 | at android.view.View.measure(View.java:23279)
49 | at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6928)
50 | at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
51 | at android.view.View.measure(View.java:23279)
52 | at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6928)
53 | at android.widget.LinearLayout.measureChildBeforeLayout(LinearLayout.java:1514)
54 | at android.widget.LinearLayout.measureVertical(LinearLayout.java:806)
55 | at android.widget.LinearLayout.onMeasure(LinearLayout.java:685)
56 | at android.view.View.measure(View.java:23279)
57 | at android.view.ViewGroup.measureChildWithMargins(ViewGroup.java:6928)
58 | at android.widget.FrameLayout.onMeasure(FrameLayout.java:185)
59 | at com.android.internal.policy.DecorView.onMeasure(DecorView.java:898)
60 | at android.view.View.measure(View.java:23279)
61 | at android.view.ViewRootImpl.performMeasure(ViewRootImpl.java:2832)
62 | at android.view.ViewRootImpl.measureHierarchy(ViewRootImpl.java:1869)
63 | at android.view.ViewRootImpl.performTraversals(ViewRootImpl.java:2124)
64 | at android.view.ViewRootImpl.doTraversal(ViewRootImpl.java:1738)
65 | at android.view.ViewRootImpl$TraversalRunnable.run(ViewRootImpl.java:7745)
66 | at android.view.Choreographer$CallbackRecord.run(Choreographer.java:911)
67 | at android.view.Choreographer.doCallbacks(Choreographer.java:723)
68 | at android.view.Choreographer.doFrame(Choreographer.java:658)
69 | at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:897)
70 | at android.os.Handler.handleCallback(Handler.java:789)
71 | at android.os.Handler.dispatchMessage(Handler.java:98)
72 | at android.os.Looper.loop(Looper.java:164)
73 | at android.app.ActivityThread.main(ActivityThread.java:6938)
74 | at java.lang.reflect.Method.invoke(Native Method)
75 | at com.android.internal.os.Zygote$MethodAndArgsCaller.run(Zygote.java:327)
76 | at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1374)

**Comment by cmelchior** [comment]
Hi @preyesm 
Its impossible to say what could be wrong from the code above. One suggestion might be that if an app is put in the background, killed and restarted at that particular activity, then the Realm isn't opened for some reason.

**Comment by preyesm** [comment]
Is it possible that this bug can occur, if there is an execute transaction going on in parallel in my data layer and i am trying to access this object in the UI?

**Comment by preyesm** [comment]
This error happens in two different scenarios. 
1. One as reported above. 
2. I am moving my project to use and dagger 2 with realm.  The overall app access the common static method to get the realm instance, and the first fragment where i use @Inject Realm realm, this error comes up.
Note:
The module that provides the singleton realm instance also uses the same static method defined in the application class to provide realm instance. I can submit the code, if there is any confusion

**Comment by preyesm** [comment]
*Application level class*
private synchronized Realm getRealmAPI() {
        if (realm == null) {
            initRealmAPI();
        }
        return realm;
    }

 private void initRealmAPI() {
        try {
            realm = Realm.getDefaultInstance();
            System.out.println("realm created");
        } catch (RealmMigrationNeededException ex) {
            ex.printStackTrace();
            Realm.deleteRealm(RealmUtils.getRealmConfiguration());
            clearLastFetchTime();
            realm = Realm.getDefaultInstance();
            if (RealmUtils.isUserLoggedIn())
                AgentDesksDataHandler.getInstance().getUserDataHandler().getAgentProfile();
        }
    }

Dagger 2 module class:

    @Provides
    @Singleton
    public Realm providesRealm() {
        return ApplicationDataHandler.getRealm();
    }


All other mvc classes accesses the realm instance by directly invoking the application level static method. And this happens only for the first time. When i close the app and come back it works fine.

**Comment by cmelchior** [comment]
Do you ever call `realm.close()` ?

**Comment by preyesm** [comment]
I call it only when the user logs out of the app, only once.
I delete all my local cache and close realm

**Comment by cmelchior** [comment]
Depending on your Dagger setup that might be why, because Dagger caches the singleton Realm meaning you will be served a closed instance for the next user.

**Comment by Zhuinden** [comment]
```
@Provides
// @Singleton
public Realm providesRealm() {
    return ApplicationDataHandler.getRealm();
}
```

**Comment by preyesm** [comment]
there can be only one user for the app. for all session

**Comment by preyesm** [comment]
@Zhuinden I shall try with the suggestion, but again the confusion arises of why would it happen only for the first time after I open realm instance. Because I don't call close realm until user logs out, providing realm instance via dagger crashes for the first and only one time. @cmelchior  any suggestion for point 1?

**Comment by cmelchior** [comment]
Not really, but you seem to have multiple layers of caching where one of them get it wrong for some reason, e.g. your `getRealmAPI()` also caches the Realm instance, Dagger caches it because you marked it `@Singleton`, so my best guess is that one of these caches are not cleared correctly.

**Comment by preyesm** [comment]
dagger implementation is very recent, for which i will remove *@Singleton* as you have suggested and try. But the crash for which this issue was opened has been occurring very intermittently and I am not getting clue to debug or try an alternate. If requesting the realm instance again whenever this happens, will do the trick, it is impossible to do in all places in the app.

**Comment by Zhuinden** [comment]
You probably need to test against either putting app to background, or process death, or both.

**Comment by preyesm** [comment]
@Zhuinden as per the user session the crash has happened in the first second after he has opened the app. Attaching the screenshot
<img width="406" alt="screen shot 2018-05-14 at 4 24 12 pm" src="https://user-images.githubusercontent.com/20237597/39993388-4fbc2e1e-5793-11e8-8386-81b181223cd7.png">

so going to background or killing it might not be the case is my suspect. Will go through your link though. Also I have started usign realm wtih rx java to get data independent of realm instance. 
Please confirm, if this can happen if the bug is elsewhere and that is causing the crash. If so, i can debug more on the other modules of the app.

**Comment by Zhuinden** [comment]
It could easily be a cause if the way you use Rx is incorrect 😄

**Comment by cmelchior** [comment]
@preyesm I assume you found a solution. If that is not the case, feel free to reopen the issue.
