### ISSUE TITLE
Null configuration returned on first application launch Android P

### ISSUE THREAD

**Issue by Kyba1985** [realm/realm-java#5959]
Android version: 28

Device: Emulator with android P api 28

Realm version: 4.1.0

GOAL: create and get a realm configuration

I'm testing an application with realm on android P, in first launch of the application after i set the permission of write_external_storage to true every time a want get the realm configuration with method below the configuration returned is always null.

If I kill the application and relaunch all works well , but is broken the first UX for the user whe the application is downloaded and first started. This happens only on android P. 

What can i do? Is it a problem of the emulator?

```
public RealmConfiguration getUpdatedConfigRealmArchive() throws IllegalStateException {
        synchronized (lockConfigurationRealm) {
            int permission = ActivityCompat.checkSelfPermission(this, android.Manifest.permission.WRITE_EXTERNAL_STORAGE);
            if (permission != PackageManager.PERMISSION_GRANTED) {
                throw new IllegalStateException("db not ready for permissions");
            }
            if (configurationRealmArchive == null) {
                File directory = new File(Environment.getExternalStorageDirectory(), ConstantsApp.ROOT_DIRECTORY_FOLDER);
                File realmDBFolder = new File(directory, ConstantsApp.REALM_ARCHIVE_DIRECTORY_FOLDER);
                configurationRealmArchive = new RealmConfiguration.Builder().directory(realmDBFolder).name(ConstantsApp.REALM_ARCHIVE_NAME).schemaVersion(ConstantsApp.REALM_SCHEMA_VERSION).build();
                try {
                    Realm.migrateRealm(configurationRealmArchive, new MigrationRealm());
                } catch (Exception ex) {
                    //ignore error
                    ex.printStackTrace();
                }
                Realm.setDefaultConfiguration(configurationRealmArchive);
                return configurationRealmArchive;
            } else return configurationRealmArchive;
        }
    }
```

**Comment by cmelchior** [comment]
I don't see how this function can return `null` unless you are manipulating the `configurationRealmArchive` outside this method.

**Comment by Kyba1985** [comment]
@cmelchior when i take the result value of this method when i am on Android P (emulator) the RealmConfiguration is always null. I set the permission storage at the startup of the application. the realm returns to work well if i kill the app , go to app settings remove and set another time the storage permissions. 

I can't understand if is a problem of Androd P , Realm or only the emulator. At the moment i can't test o a real device android P.

**Comment by cmelchior** [comment]
Hi @Kyba1985 
Are you still seeing this issue? If yes, then we need to be able to reproduce it somehow. Preferably using a sample project.

**Comment by Kyba1985** [comment]
Hi @cmelchior ,
at the moment i can't test on a real Android P device. I hope that soon i will test on a real P device. Are you testing Realm on Android P with no issues? Our apps with realm are on half milion of users without problems on this method. I will continue to monitoring fabric and when i will test on android P device i will report on this thread if you don't close it.

**Comment by cmelchior** [comment]
Since nothing was reported, I will assume you either fixed the issue or are not encountering it in the wild. If you are seeing it we probably need an example project in order to debug it.
