### ISSUE TITLE
UnsatisfiedLinkError: No implementation found for long io.realm.internal.OsSharedRealm.nativeGetFinalizerPtr()

### ISSUE THREAD

**Issue by serj-lotutovici** [realm/realm-java#5960]
We are seing a crash in Crashlytics on Pixel 2 and Pixel 2 XL devices with Android P, that happens when `Realm.init(Context)` is called. I've tried to reproduce on my Pixel 2 with the beta installed, but no luck.

The stack trace from crashlytics is as follows:
```
Fatal Exception: java.lang.UnsatisfiedLinkError: No implementation found for long io.realm.internal.OsSharedRealm.nativeGetFinalizerPtr() (tried Java_io_realm_internal_OsSharedRealm_nativeGetFinalizerPtr and Java_io_realm_internal_OsSharedRealm_nativeGetFinalizerPtr__)
       at io.realm.internal.OsSharedRealm.nativeGetFinalizerPtr(Unknown Source)
       at io.realm.internal.OsSharedRealm.(Unknown Source:154)
       at io.realm.internal.OsSharedRealm.initialize(Unknown Source:258)
       at io.realm.Realm.init(Unknown Source:255)
       ...
       at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:1154)
       at android.app.ActivityThread.handleBindApplication(ActivityThread.java:5865)
       at android.app.ActivityThread.access$1000(ActivityThread.java:198)
       at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1637)
       at android.os.Handler.dispatchMessage(Handler.java:106)
       at android.os.Looper.loop(Looper.java:164)
       at android.app.ActivityThread.main(ActivityThread.java:6649)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:493)
       at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:826)
```

#### Version of Realm and tooling
Realm version(s): **4.3.3**

Realm sync feature enabled: **no**

Which Android version and device: **P**

Devices are **not** rooted.

**Comment by cmelchior** [comment]
To the best of our knowledge Realm should work fine on the Pixel 2. This seems to be a problem with the native code somehow. The native library has been loaded, but this error could indicate a problem with it somehow. Have you seen it just once or do you have reports from multiple users?

**Comment by serj-lotutovici** [comment]
Just checked the crash reports. Currently, we see this happening for a few users. All of them tried to start the app on a Pixel 2 with Android P in the last 7 days. But I can't reproduce this my self, we have two Pixel's (one with P, and one with Orio).

**Comment by serj-lotutovici** [comment]
@cmelchior I started looking into this more deeply and I noticed that the `realm-jni` native lib that ends up in the apk differs for debug and release builds (At least size wise). 
I've looked into the gradle-plugin source code, but couldn't find any piece of code that would indicate that the binaries are being swapped somehow. Any ideas why this is happening?

**Comment by cmelchior** [comment]
Yes, the debug libraries are larger because they contain debug symbols, but debug libraries are only used for unit and integration tests. All releases including those on Bintray are done using the release binaries, so e.g. setting the `debug` flag in your project's grade file will still use Realms release binaries.

**Comment by serj-lotutovici** [comment]
This is weird. I first fought, that it may have something to do with our proguard setup. But after disabling it, I could still manage to reproduce.  The crash. It crashes only on P, and only if it's a `release` build.

**Comment by serj-lotutovici** [comment]
I'll try to create one today.

**Comment by serj-lotutovici** [comment]
I can consistently reproduce it in our project :) Yesterday created a sample but it doesn't crash. I thought it has to do with our build config or a plugin, but no luck. Looking if some library from our dependencies is doing this.

**Comment by cmelchior** [comment]
I'll assume you found the bug outside Realm and close this issue. If not, feel free to reopen.
