### ISSUE TITLE
Does null objects takes up space ?

### ISSUE THREAD

**Issue by debjitk** [realm/realm-java#5961]
Does a null object in a realm object takes up any space ?

**Comment by Zhuinden** [comment]
RealmObjects link to other RealmObjects, think of it as a pointer.

So "null" is also a "pointer".

But deleted objects are more likely to take up space considering that space is primarily removed only by compacting.

**Comment by cmelchior** [comment]
@debjitk Zhuinden explained it pretty well, so I hope that answers your question. If not feel free to reopen.
