### ISSUE TITLE
 Type 'Results' appears more than once in the schema.

### ISSUE THREAD

**Issue by priyanka9879** [realm/realm-java#5962]
Hi ,

I have develop application using realm but I am getting the issue. 
                                                              Caused by: java.lang.IllegalStateException: Schema validation failed due to the following errors:
                                                             - Type 'Results' appears more than once in the schema.

can you please help ?

**Comment by Zhuinden** [comment]
I don't see your schema definition (read: the RealmObject causing the error) so I don't know how to help.

**Comment by cmelchior** [comment]
Most likely you have two `Results` classes in different packages of your app? If you have that you need to give one of them a different internal name using the `@RealmClass(name = '')` annotation. Support for this was added in Realm 4.4.0

**Comment by priyanka9879** [comment]
@cmelchior Thanks you so much it works for me

**Comment by priyanka9879** [comment]
@cmelchior  I have one more question. I have created application using litepal framework that is to save data locally. and uploaded to play store now in next version  I am removing  litepal and adding realm. and again upload to play store. now what happeens when someone update app from play store ?

**Comment by cmelchior** [comment]
Well, they would just start using your new app with Realm meaning the data in SQLite database is lost unless you move it manually.

**Comment by priyanka9879** [comment]
@cmelchior  okay thanks
