### ISSUE TITLE
Parceler: Code generation did not complete 

### ISSUE THREAD

**Issue by KingWu** [realm/realm-java#5963]
I upgrade Realm from 3.5.0 to 5.1.0. Parceler : 1.1.9
After compile, show this error. Any idea?

Parceler: Code generation did not complete

**Comment by Zhuinden** [comment]
The name of the Realm Proxy classes has changed to the fully qualified name with package separator `. ` being replaced with `_`

**Comment by Zhuinden** [comment]
You'll also need a clean rebuild.

**Comment by cmelchior** [comment]
The above have been added to the Parceler documentation on the website. Closing
