### ISSUE TITLE
java.lang.NoSuchFieldError: No instance field handlerController of type Lio/realm/HandlerController; in class Lio/realm/BaseRealm; or its superclasses (declaration of 'io.realm.BaseRealm' appears in /data/app/xyz.com.xyzinc-1/base.apk)

### ISSUE THREAD

**Issue by bijoyjoseph** [realm/realm-java#5964]
Here is my RealmModelAdapter class:

public class RealmModelAdapter<T extends RealmObject> extends RealmBaseAdapter<T> {

    public RealmModelAdapter(@NonNull Context context, @Nullable OrderedRealmCollection<T> data) {
        super(context, data);

    }

    @Override
    public View getView(int position, View convertView, ViewGroup parent) {
        return null;
    }
}

and ReamlDataAdapter class:

public class RealmDataAdapter extends RealmModelAdapter<MyData> {

    public RealmDataAdapter(@NonNull Context context, @Nullable OrderedRealmCollection data) {
        super(context, data);
    }
}

I am getting this error when the super() method is called in both the classes

I am using 'io.realm:android-adapters:1.3.0' and "io.realm:realm-gradle-plugin:3.1.4"

**Comment by Zhuinden** [comment]
'io.realm:android-adapters:1.3.0' only supports Realm versions up to 2.3.0

For 3.0.0 (and below 5.0.0) you need to use 'io.realm:android-adapters:2.1.1'

**Comment by bijoyjoseph** [comment]
Thanks, I will check into it
