### ISSUE TITLE
realm 1.1.0 with gradle plugin 3.x.x

### ISSUE THREAD

**Issue by llooz** [realm/realm-java#5972]
I need to build an old project that uses realm 1.1.0 with gradle plugin 3.x.x.

Unfortunately the project code can't be updated to align with the breaking changes of the new realm versions 

The issue is related to removal of `apt` and the introduction of the new `annotationProcessor`.

Is there a way to use a plugin version compatible the gradle plugin 3.x.x and at the same time have a dependency on the realm library 1.1.0?

**Comment by cmelchior** [comment]
Sorry, no this isn't possible. `apt` is not supported in that version of the gradle plugin and when Realm Java 1.1 was released it was. Your only option is downgrading Android Studio and the Gradle plugin.

**Comment by Zhuinden** [comment]
Technically I was wondering if it's possible to just apply the stuff the Gradle task would on its own, and specify the scopes and dependencies manually

**Comment by cmelchior** [comment]
It depends on how far back you want to go, e.g. the Realm Transformer is only supported from Gradle Plugin 1.5 and forward, but yes, perhaps applying https://realm.io/docs/java/latest/#how-do-i-customize-dependecies-defined-by-the-realm-gradle-plugin and replacing `kapt/annotationProcessor`  with `apt` might work.
