### ISSUE TITLE
No cached version of io.realm:realm-annotations-processor:5.1.0 available for offline mode.

### ISSUE THREAD

**Issue by srinivas3120** [realm/realm-java#5973]
getting following error after updating android studio to 3.1.2.
`No cached version of io.realm:realm-annotations-processor:5.1.0 available for offline mode.`

**Comment by cmelchior** [comment]
![image](https://user-images.githubusercontent.com/406066/40531391-93ca7c16-5ffc-11e8-913e-76ec8b89b67b.png)
You need to disable offline mode in Android Studio. It isn't a bug in Realm.

**Comment by srinivas3120** [comment]
@cmelchior it is disabled. still getting this error

**Comment by srinivas3120** [comment]
Issue resolved after following these steps.
1. Uncheck "Offline work" and remove  "--offline" in **Command-line Options:** in Android Studio 0.6.0:
```
File->Settings->Gradle->Global Gradle Settings
or in OSX:
Preferences->Gradle->Global Gradle Setting
or in more recent versions:
File->Settings->Build, Execution, Deployment->Build tools->Gradle
```
2. Resync the project, for example by restarting the Android Studio
3. Once synced, you can check the option again back to work offline.


![40531391-93ca7c16-5ffc-11e8-913e-76ec8b89b67b](https://user-images.githubusercontent.com/8431202/40535476-ddb9c528-6026-11e8-96e2-bd1f30ae4f71.png)

<img width="1045" alt="hoca5" src="https://user-images.githubusercontent.com/8431202/40535161-f773dd2e-6025-11e8-97e1-af608137b213.png">
