### ISSUE TITLE
deleteAll() produces "JNI DETECTED ERROR IN APPLICATION"

### ISSUE THREAD

**Issue by jimmy510s** [realm/realm-java#5980]
Hi,

When i try to clear the database (user logs out) in my app i get the following weird error? that i have included in the logcat file. The code in the project is written by many developers but as i see everything works ok and the data are being stored and retrieved normally but for a reason i cannot delete all the database.

Thank you

[logcat.txt](https://github.com/realm/realm-java/files/2048402/logcat.txt)

**Comment by Zhuinden** [comment]
> com.msensis.mymarket.activities.MainActivity$13.onChange(io.realm.RealmResults, io.realm.OrderedCollectionChangeSet) (MainActivity.java:853)

MainActivity has a change listener that tries to get the first item with `.first()` from the RealmResults it belongs to without checking if it's empty or not.

**Comment by jimmy510s** [comment]
Hi,

Thanks for the quick response so i suppose that i have to remove all listeners first and then clear the database. Right?

**Comment by cmelchior** [comment]
Not really. You just need to guard you listeners against the result possibly being empty.

**Comment by cmelchior** [comment]
Like @Zhuinden said. `results.first()` can take an argument that is used instead if no results are found. Instead of `null` you can also use a dummy object. What to use depends on your exact use case.

**Comment by jimmy510s** [comment]
Thank you very much for your help!! 👍
