### ISSUE TITLE
Only armeabi error reporting is supported

### ISSUE THREAD

**Issue by to686312** [realm/realm-java#5998]
Project use only armeabi architecture will be submitted to the can't find some architecture realm so libraries But I can't add armeabi project - v7a because I integrated navigation provides only armeabi library so he armeabi - v7a does not support So only armeabi an architecture How to make a architecture realm only support armeabi

**Comment by cmelchior** [comment]
Google has deprecated armeabi support so ideally all vendors should be upgrading their native build systems. Also armeabi support was removed in Realm 2.0 and we have no current plans of re-adding support for it.

It is however still possible to build Realm from source with armeabi support:

1) Clone  https://github.com/realm/realm-java.git
2) Add the following to `realm-java/realm/gradle.properties`. Adjust the list of ABI's to the ones you want.

```
org.gradle.jvmargs=-Xms512m -Xmx2048m
org.gradle.caching=true
kotlin.incremental=false;
buildTargetABIs=armeabi,x86,x86_64,armeabi-v7a,arm64-v8a,mips
``

3) Build the Realm library using the guide described here: https://github.com/realm/realm-java#building-realm

**Comment by Zhuinden** [comment]
Wait, if it's that simple to build Realm with ARMEABI, how come it was removed back in 2.0?

Or... it's Realm Sync that cannot be built against armeabi?

**Comment by cmelchior** [comment]
Actually, I might have been a bit quick here. Going through git history https://github.com/realm/realm-java/pull/2998/files#diff-d570448a45da414d868f816795c808e6R54 it could look like we had some compiler issues and just ended up removing armeabi instead of trying to fix it since all devices should support armeabi-v7a and above anyway.

**Comment by freeyob** [comment]
I also want armeabi support
