### ISSUE TITLE
Method with invalid locals information from RealmTransformer for Non-Realm Class

### ISSUE THREAD

**Issue by eygraber** [realm/realm-java#5999]
The past month or so (which may have correlated with us starting to use D8), I've been noticing this log entry every time I built my app (package name changed):

> AGPBI: {"kind":"warning","text":"Methods with invalid locals information:\n  com.myapp.RenderOutput com.myapp.ClusterIconGenerator.render(com.myapp.AnimationState, com.myapp.RenderOutput)\n  Attempt to define local of type float as $i$f$using","sources":[{"file":"<path to my app>/app/build/intermediates/transforms/RealmTransformer/debug/0/com/myapp/ClusterIconGenerator.class"}],"tool":"D8"}

This happens in the `:app:transformClassesWithRealmTransformerForDebug` task.

This is the references `render` method. Neither the method, nor the class it's in, reference anything to do with Realm.

```

fun render(state: AnimationState, output: RenderOutput): RenderOutput {
    with(view) {
      val count = minOf(state.count, avatarViews.size)
      for (index in 0 until count) {
        val alpha = state.alpha[index]
        val scale = state.scale[index]
        val avatar = state.avatars[index]?.apply { updateColor(alpha) } ?: loadingIcon
        with(avatarViews[index]) {
          avatarViews[index].visibility = View.VISIBLE
          setImageDrawable(avatar)
          scaleX = scale
          scaleY = scale
        }
      }

      for (index in count until avatarViews.size) {
        avatarViews[index].visibility = View.GONE
      }

      // TODO Animate transition
      if (state.count > MAX_SLOTS) {
        avatarViews.last().visibility = View.GONE
        counter.visibility = View.VISIBLE
        counter.text = "+${state.count - MAX_SLOTS + 1}"
      }
      else {
        counter.visibility = View.GONE
      }

      location.visibility = if(state.text.isBlank()) View.GONE else View.VISIBLE
      location.text = state.text
      updateMeasure()
    }
```

**Comment by nhachicha** [comment]
@eygraber The transformer [now](https://github.com/realm/realm-java/blob/master/CHANGELOG.md#520-2018-06-06) supports incremental builds, can you try with the `5.2.0` version to see if this is still the case?

**Comment by eygraber** [comment]
Sorry, I forgot to mention I'm using realm 5.2.0

**Comment by eygraber** [comment]
Still occurring with 5.3.1

**Comment by cmelchior** [comment]
Can you try to replace the Realm gradle plugin with the setup described here: https://realm.io/docs/java/latest/#how-do-i-customize-dependecies-defined-by-the-realm-gradle-plugin

And then try to set the Realm Transformer to 5.1. It would be interesting to know if it makes any difference.

**Comment by eygraber** [comment]
Not sure if you meant to only set the Realm Transformer to 5.1.0 and keep everything else at 5.3.1, or change all the dependencies to 5.1.0, but in either case this happens when I clean build:

```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':realm:transformClassesWithRealmTransformerForDebug'.
	at io.realm.transformer.RealmTransformer.sendAnalytics(RealmTransformer.groovy:183)
	at io.realm.transformer.RealmTransformer.transform(RealmTransformer.groovy:148)
```

**Comment by cmelchior** [comment]
Does it work if you disable D8?
```
android.enableD8=false
```

If that is the case, I would recommend filling a bug for D8 here: https://issuetracker.google.com/issues?q=componentid:317603%20status:open

**Comment by eygraber** [comment]
Just to clarify, the build works fine; I just thought it was weird that the realm transformer would be touching these files.

Building with `android.enableD8=false` does not output the warning.

**Comment by nhachicha** [comment]
please re-open if you have more details from the issue tracker

**Comment by eygraber** [comment]
Filed https://issuetracker.google.com/issues/111404865
