### ISSUE TITLE
Unrecoverable error. mmap() failed: Out of memory

### ISSUE THREAD

**Issue by trr-amsiq** [realm/realm-java#6001]
HI I am seeing a lot of crashes like this with the exact same size.
The crash seems to occur within a ```executeTransactionAsync``` call

Can anyone help me understanding the crash and what size means?

#### Actual Results

>  Caused by io.realm.exceptions.RealmError: Unrecoverable error. mmap() failed: Out of memory size: 1048576 offset: 3145728 in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 144
       at io.realm.internal.OsSharedRealm.nativeCommitTransaction(OsSharedRealm.java)
       at io.realm.internal.OsSharedRealm.commitTransaction(OsSharedRealm.java:273)
       at io.realm.BaseRealm.commitTransaction(BaseRealm.java:412)
       at io.realm.Realm.commitTransaction(Realm.java:146)
       at io.realm.Realm$1.run(Realm.java:1519)
       at io.realm.internal.async.BgPriorityRunnable.run(BgPriorityRunnable.java:34)
       at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:422)
       at java.util.concurrent.FutureTask.run(FutureTask.java:237)
       at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
       at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
       at java.lang.Thread.run(Thread.java:818)

#### Version of Realm and tooling
Realm version(s): 5.1

Realm sync feature enabled: yes/no

Android Studio version: 3.1.2

Which Android version and device: random

**Comment by cmelchior** [comment]
You are doing something that requires too much memory. On older 32 bit devices it can be because the Realm file has gotten to big. See https://realm.io/docs/java/latest/#faq-large-realm-file-size for details.

On 64 bit devices it could be because you are writting to much data inside a single transaction.

**Comment by cmelchior** [comment]
Ok, that should work perfectly well. In that case, I would check if you are doing something that requires a lot of native memory.  Exactly what is hard to tell, so it probably requires you to attach a profiler.

Some possible starting points:
- If you are leaking Realm instances on many threads
- Eg. Fresco uses native memory to do image loading. Other libraries might do the same.

**Comment by trr-amsiq** [comment]
Realm count returns 1. 
I read and update multiple RealmList in this exact transaction.
So I should split it to smaller transactions?

**Comment by cmelchior** [comment]
That would possibly help, but if you entire Realm file is only 30 MB then I doubt you are writing much data into the Realm. Meaning that it probably isn't the root cause.

**Comment by Zhuinden** [comment]
> Realm count returns 1.

getGlobalInstanceCount?

**Comment by trr-amsiq** [comment]
Yes

**Comment by Zhuinden** [comment]
> should return false, but it is true. 

Sounds like a bug in your code 🙄

**Comment by cmelchior** [comment]
@trr-amsiq I assume the above answered your question. If not, feel free to reopen the issue.

**Comment by cmelchior** [comment]
@trr-amsiq Have you tried attaching a profiler and see if that reveals anything?

**Comment by trr-amsiq** [comment]
Yes and I am not seeing anything obvious. I've tried to run with non async and it seems to reduce the crash rate. 
I am considering if it could be related to the UI attached Realm which is never closed unless the activity is destroyed, is causing some issues when transactions are executed async. Other Realms are open on IO threads and closed when transactions are done.

**Comment by Zhuinden** [comment]
One day, hopefully Realm will support online compact.

Ever since Realm 2.0, compaction of Realm instances has been quite important.

**Comment by trr-amsiq** [comment]
@Zhuinden Any advice?

**Comment by Zhuinden** [comment]
if you're not compacting Realms when you quit the app (activity count reaches 0), you probably should.

**Comment by trr-amsiq** [comment]
Thanks! I will give it a try

**Comment by fenjuly** [comment]
Hi trr-amsiq, 
I have faced the same error. Have you found the reason? Any solutions?

**Comment by trr-amsiq** [comment]
My solution was to cleanup my realm file by:

1. Making sure that all objects have a primary key.
2. Delete subObjects that are no longer linked to any other object
3. Compact realm at launch

**Comment by fenjuly** [comment]
> My solution was to cleanup my realm file by:
> 
> 1. Making sure that all objects have a primary key.
> 2. Delete subObjects that are no longer linked to any other object
> 3. Compact realm at launch

Thanks for your reply, I will try above solutions.
