### ISSUE TITLE
Search with two diffrent table with single realm adapter with dividor

### ISSUE THREAD

**Issue by vavadiyahiren** [realm/realm-java#6004]
I am trying to implement search in my application with single realm adapter and from two diffrent table.

Right we are qureying the data from two diffrent table and then we are merging those two result set to set data in single realm adapter which is taking much time while searching and we are getting bad user experience.

Current database pattern

**Table 1** 

id - int, primary key,
name - String.
description - String

**Table 2** 

id - int primary key,
profile image path - String 
Last activity  - String.

Now we are trying to search text from last activity performed by user as well as we wanted to serach the name as well, And we are trying to show the search results with one devidor in single adaptor.

What currnely we are doing is we are searching it from the first table and then querying from the second one after that we are combining them which works well upto certain limit of data but when we planned to search with more then 10k records it is taking much much time to featch results so any option available in realm which can search from two diffrenent data structure and we can display them directly.

Realm Version - 4.3.3
Android Version - 5.0  and above.

Thanks,
Hiren Vavadiya

**Comment by Zhuinden** [comment]
See https://stackoverflow.com/questions/34975080/complex-sorting-for-search-in-realm-union-of-multiple-realmresults

**Comment by vavadiyahiren** [comment]
Sorry for being late to respond you i will try it and let you know my best results.

**Comment by cmelchior** [comment]
I assume the above solution solved your issue. If not, feel free to re-open the issue.
