### ISSUE TITLE
Always query with null RealmList

### ISSUE THREAD

**Issue by KingWu** [realm/realm-java#6009]
First, i get a json array from serve.
[
 {'id': '1', 'title': 'a'},  {'id': '2', 'title': 'b'} 
]

i force to create RealmList. but still get null. For 3.5.0, i don't need to check null. Also, i call the executeTransactionAsync again. Always get null.

```java
public class Plan extends RealmObject {
    @PrimaryKey
    private String id;
    String title = "";
    public RealmList<Place> places;
}

realm.executeTransactionAsync(
                    new Realm.Transaction() {
                        @Override
                        public void execute(Realm realm) {
                           realm.createOrUpdateAllFromJson(Plan.class, jsonArray);
                           Plan plan = realm.where(Plan.class).equalTo("id", "1").findFirst();
                           Log.d(plan.places); // <--- always null
                           if(null == plan.places){
                              plan.places = new RealmList<>();
                           }
                        }
                    });
```

#### Version of Realm and tooling
Realm version(s): Upgrade from 3.5.0 to 5.2.0

Realm sync feature enabled: no
Android Studio version: 3.1.3
Which Android version and device: 7.0.0

**Comment by KingWu** [comment]
Tried to clean project and clear app data. Finally, downgrade from 5.2.0 to 5.1.0. Issues fixed.
i think 5.2.0 has some bugs

**Comment by Zhuinden** [comment]
So, not even clean/rebuild helped?

**Comment by cmelchior** [comment]
Closing due to no response. Feel free to reopen if this is still a problem.
