### ISSUE TITLE
'value' is not a valid managed object.

### ISSUE THREAD

**Issue by ioviov** [realm/realm-java#6014]
Hello!
I have two RealmObject:

public class SongsDB extends RealmObject {
    public String describe = "";
    public boolean hasAccord = false;
    public String lyrics = "";
    public String lyricsAccord = "";
    public String name = "";
    public String bibleVerse = "";
    public String bibleLink = "";
    public SongsLanguageDB language;
    public FavoriteDB favorite;
    public AlbumsDB album;
    @PrimaryKey
    public String uuid = "";
}

AND

public class FavoriteDB extends RealmObject {
    public SongsDB song;
}

When I have created SongsDB object in Realm and I try to update it, I have an error "'value' is not a valid managed object."

My code for the update:

Realm realm = Realm.getDefaultInstance();
        
        SongsDB songDB = realm.where(SongsDB.class).equalTo("uuid", "fdse-3424-vvf43").findFirst();

        FavoriteDB favoriteDB = new FavoriteDB();
        favoriteDB.song = songDB;

        realm.beginTransaction();
        songDB.favorite = favoriteDB; // WRITE HERE THE ERROR APPEARS
        realm.copyToRealm(favoriteDB);
        realm.commitTransaction();

Thanks for help!

**Comment by Zhuinden** [comment]
I think it's probably because.. the value is not a managed object, so it's not a valid managed object.

The following would work.

```
    realm.beginTransaction();
    songDB.favorite = realm.copyToRealm(favoriteDB);
    realm.commitTransaction();
```

**Comment by Zhuinden** [comment]
Well yeah, because in that example, `songsDB` is not a managed object, and it's saved "recursively" by `copyToRealmOrUpdate`

**Comment by ioviov** [comment]
I see, Thanks a lot!

**Comment by cmelchior** [comment]
I assume the above answered your question. If not, feel free to reopen
