### ISSUE TITLE
Realm object's fields are only accessible using getter

### ISSUE THREAD

**Issue by anggrayudi** [realm/realm-java#6034]
#### Goal

I am trying to fetch `RealmObject`s using this query:

```java
        RealmResults<Task> tasks = realm.where(Task.class)
                .sort(Column.NAME)
                .findAllAsync();
        tasks.addChangeListener(new RealmChangeListener<RealmResults<Task>>() {
            @Override
            public void onChange(@NonNull RealmResults<Task> results) {
                results.removeChangeListener(this);
                for (Task task : results) {
                    Log.d(TAG, "ID: " + task.id);
                    Log.d(TAG, "Name: " + task.name);
                    Log.d(TAG, "Date: " + task.when);
                }
            }
        });
```
#### Expected Results

| ID | Name | When (Date) |
|----|----|----|
| 1 | Washing car | 1529493689 |
|2|Cleaning bedroom|1529402347|

#### Actual Results

| ID | Name | When |
|----|----|----|
| 0 | null | null |
|0|null|null|

#### Steps & Code to Reproduce

This bug happens when you trying to access data without getter, for example:

```java
Task task = realm.where(Task.class).findFirst();
System.out.println(task.id); // 0
System.out.println(task.name); // null
```

But when you add getters, everything works fine:

```java
System.out.println(task.getId()); // 1
System.out.println(task.getName()); // Washing car
```

#### Version of Realm and tooling
Realm version(s): 5.3.0

Realm sync feature enabled: No

Android Studio version: 3.1.3

Which Android version and device: API 21

I must downgrade to Realm 5.2.0 since this bug does not appear here.

**Comment by Zhuinden** [comment]
Considering that'd mean the incremental transformer task is bugged, is there any chance you have sample project that can reproduce this?

**Comment by cmelchior** [comment]
Also interesting to know if this happens if you do a clean build?

**Comment by anggrayudi** [comment]
Ah, my bad. You are right. After I ran clean build, everything works like a charm.

Thank you.

**Comment by cmelchior** [comment]
Note, this could still mean problems with the incremental build, so please keep an eye on it if it happens again and see https://realm.io/docs/java/latest/#limitations-incremental-builds.
