### ISSUE TITLE
Realm crashes when using multiple executeTransactions

### ISSUE THREAD

**Issue by holtaf** [realm/realm-java#6039]
When using multiple `executeTransactions` in a sequence Realm crashes. What am I doing wrong ? If I replace `executeTransaction` with an `executeTransactionAsync` it seems to work without any problems. Also all of this runs in a UI thread. Thanks in advance.

```java
// MainActivity.java
Realm.init(this);

final Realm realm = Realm.getDefaultInstance();

User user1 = realm.where(User.class).equalTo("id", "").findFirstAsync();
user1.addChangeListener(new RealmChangeListener<RealmModel>() {
	@Override
	public void onChange(@NonNull RealmModel realmModel) {
		realm.executeTransaction(realm -> Log.d("RealmTest", "Transaction 1"));
	}
});

User user2 = realm.where(User.class).equalTo("id", "").findFirstAsync();
user2.addChangeListener(new RealmChangeListener<RealmModel>() {
	@Override
	public void onChange(@NonNull RealmModel realmModel) {
		realm.executeTransaction(realm -> Log.d("RealmTest", "Transaction 2"));
	}
});

User user3 = realm.where(User.class).equalTo("id", "").findFirstAsync();
user3.addChangeListener(new RealmChangeListener<RealmModel>() {
	@Override
	public void onChange(@NonNull RealmModel realmModel) {
		realm.executeTransaction(realm -> Log.d("RealmTest", "Transaction 3"));
	}
});
```
```java
// User.java
public class User extends RealmObject {
	private String id;
}

```

This is my log.

`
06-23 19:56:48.039 20989-20989/com.holtaf.testandroidapplication D/RealmTest: Transaction 3
06-23 19:56:48.042 20989-20989/com.holtaf.testandroidapplication D/RealmTest: Transaction 2
06-23 19:56:48.053 20989-20989/com.holtaf.testandroidapplication A/zygote64: java_vm_ext.cc:534] JNI DETECTED ERROR IN APPLICATION: JNI NewLocalRef called with pending exception java.lang.IllegalStateException: The query has been executed. This 'PendingRow' is not valid anymore.
    java_vm_ext.cc:534]   at void io.realm.internal.PendingRow.executeQuery() (PendingRow.java:258)
    java_vm_ext.cc:534]   at void io.realm.internal.OsSharedRealm.executePendingRowQueries() (OsSharedRealm.java:510)
    java_vm_ext.cc:534]   at void io.realm.internal.OsSharedRealm.beginTransaction() (OsSharedRealm.java:268)
    java_vm_ext.cc:534]   at void io.realm.BaseRealm.beginTransaction() (BaseRealm.java:401)
    java_vm_ext.cc:534]   at void io.realm.Realm.beginTransaction() (Realm.java:146)
    java_vm_ext.cc:534]   at void io.realm.Realm.executeTransaction(io.realm.Realm$Transaction) (Realm.java:1403)
    java_vm_ext.cc:534]   at void com.holtaf.testandroidapplication.MainActivity$1.onChange(io.realm.RealmModel) (MainActivity.java:28)
    java_vm_ext.cc:534]   at void com.holtaf.testandroidapplication.MainActivity$1.onChange(java.lang.Object) (MainActivity.java:25)
    java_vm_ext.cc:534]   at void io.realm.ProxyState$RealmChangeListenerWrapper.onChange(io.realm.RealmModel, io.realm.ObjectChangeSet) (ProxyState.java:50)
    java_vm_ext.cc:534]   at void io.realm.internal.OsObject$ObjectObserverPair.onChange(io.realm.RealmModel, io.realm.ObjectChangeSet) (OsObject.java:73)
    java_vm_ext.cc:534]   at void io.realm.ProxyState$QueryCallback.onCalled(io.realm.internal.OsObject$ObjectObserverPair, java.lang.Object) (ProxyState.java:70)
    java_vm_ext.cc:534]   at void io.realm.ProxyState$QueryCallback.onCalled(io.realm.internal.ObserverPairList$ObserverPair, java.lang.Object) (ProxyState.java:65)
    java_vm_ext.cc:534]   at void io.realm.internal.ObserverPairList.foreach(io.realm.internal.ObserverPairList$Callback) (ObserverPairList.java:109)
    java_vm_ext.cc:534]   at void io.realm.ProxyState.notifyQueryFinished() (ProxyState.java:132)
    java_vm_ext.cc:534]   at void io.realm.ProxyState.onQueryFinished(io.realm.internal.Row) (ProxyState.java:199)
    java_vm_ext.cc:534]   at void io.realm.internal.PendingRow.notifyFrontEnd() (PendingRow.java:247)
    java_vm_ext.cc:534]   at void io.realm.internal.PendingRow.access$000(io.realm.internal.PendingRow) (PendingRow.java:20)
    java_vm_ext.cc:534]   at void io.realm.internal.PendingRow$1.onChange(io.realm.internal.PendingRow) (PendingRow.java:48)
    java_vm_ext.cc:534]   at void io.realm.internal.PendingRow$1.onChange(java.lang.Object) (PendingRow.java:45)
    java_vm_ext.cc:534]   at void io.realm.internal.ObservableCollection$RealmChangeListenerWrapper.onChange(java.lang.Object, io.realm.OrderedCollectionChangeSet) (ObservableCollection.java:39)
    java_vm_ext.cc:534]   at void io.realm.internal.ObservableCollection$CollectionObserverPair.onChange(java.lang.Object, io.realm.internal.OsCollectionChangeSet) (ObservableCollection.java:20)
    java_vm_ext.cc:534]   at void io.realm.internal.ObservableCollection$Callback.onCalled(io.realm.internal.ObservableCollection$CollectionObserverPair, java.lang.Object) (ObservableCollection.java:64)
    java_vm_ext.cc:534]   at void io.realm.internal.ObservableCollection$Callback.onCalled(io.realm.internal.ObserverPairList$ObserverPair, java.lang.Object) (ObservableCollection.java:54)
    java_vm_ext.cc:534]   at void io.realm.internal.ObserverPairList.foreach(io.realm.internal.ObserverPairList$Callback) (ObserverPairList.java:109)
.....
`

I'm not posting the whole log because it's too long.

#### Version of Realm and tooling
Realm version: 5.0.0

Realm sync feature enabled: no

Android Studio version: 3.1.3

Which Android version and device: Google Pixel 2 XL

**Comment by Zhuinden** [comment]
While generally running synchronous transaction inside change listener is a bad idea, it shouldn't *crash*.

I think this is an edge case that only happens with `findFirstAsync`

**Comment by holtaf** [comment]
Thanks for the reply. Yes, the error remains if I change them to fields.

What's the solution for this ? I need to use `executeTransactionAsync` instead ?

**Comment by Zhuinden** [comment]
Actually, you could probably just put it in a `handler.post(new Runnable` and it'd work.

**Comment by holtaf** [comment]
I know that there are workarounds, but what's the correct way ?

For example: I got a list of users from server and I need to update them in my database. 

```java
List<ServerUserData> userDataFromServer = ...

for (ServerUserData serverUserData : userDataFromServer) {
  User user = realm.where(User.class).equals("id", serverUserData.getId()).findFirstAsync();
  user.addChangeListener(realmObject -> {
    realm.executeTransaction(r -> {
      if (user.isLoaded() && user.isValid()) {
        user.removeAllChangeListeners();
        
        user.setSomeField("someValue");
      }
    });
  });
}
```

Is this the correct way of doing it ? Or do I need to get them from the database as a `RealmResults` and change them within a single transaction ?

**Comment by Zhuinden** [comment]
The correct way is to not execute transactions inside change listeners, because you shouldn't need to do that anyway. In fact, you shouldn't need `findFirstAsync()` for this because you'd be running your network call on a background thread, and you'd be using `executeTransaction` synchronously using `findFirst()`.
