### ISSUE TITLE
People report that the incremental transformer doesn't always work

### ISSUE THREAD

**Issue by Zhuinden** [realm/realm-java#6041]
https://stackoverflow.com/q/51008957/2413303

He says 5.3.x was returning nulls and 0s on field access, while 5.1.0 returns the correct values. 

This implies that the incremental transformer sometimes silently fails (or just ignores certain parts).

**Comment by cmelchior** [comment]
Yes, we have seen various reports that indicate the incremental transformer might not work 100% of the time. I have not been able to reproduce anything yet. I'll keep this issue open as an umbrella for any issues that might be related to it though.

**Comment by nhachicha** [comment]
Similar to #6056 should be fixed in https://github.com/realm/realm-java/pull/6058

**Comment by cmelchior** [comment]
Fixed in #6058
