### ISSUE TITLE
database file is too large which only contains several records

### ISSUE THREAD

**Issue by JamesKarl** [realm/realm-java#6044]
**Bugs**
I inserted lots of records into the realm database and deleted some of them later. I noticed that the database file is still very large. It should get smaller after deleting records from it.

##Versons

Realm: 5.3.0
Android: 7.0

Android Studio: 3.1.3.

![realm-studio-records](https://user-images.githubusercontent.com/2962357/41893584-dc5eed8e-794e-11e8-95a7-d3938d8cdf6b.png)
![realm-file-property](https://user-images.githubusercontent.com/2962357/41893583-dc580988-794e-11e8-94df-478e9b5448c2.png)

**Comment by bmunkholm** [comment]
The database does not shrink automatically after you delete objects, so this is working as expected. This is done so for performance reasons. You can compact the database at startup if you think you need to. 
Please see the documentation here: https://www.realm.io/docs/swift/latest/#compacting-realms.

**Comment by Zhuinden** [comment]
You need to use Compact to remove space left behind by old items also it helps if you use less transactions than many transactions

**Comment by JamesKarl** [comment]
@Zhuinden @bmunkholm 
Your explanation and advices help me a lot. Now I have solved the issue. Realm is a great database really. Thank you very much.

Best Regards.
