### ISSUE TITLE
On some devices data not fully syncing 

### ISSUE THREAD

**Issue by SiarheiSm** [realm/realm-java#6046]
Hello. 
we are using realm and realm object server (latest builds) for syncing user data between devices and  have few reports from users that thy missing some date on they android devices (for example table on ios contains 200 rows, but only 80 on android). when i logs in to user account with the same app build on my devices i see the all data. 
restarting and reinstalling application on user device not helps.
also i've tried to call force synchronization from time to time. also dose not help.
user devices: Samsung J7,   Samsung S9+, Samsung s8+, Samsung Galaxy 8, ZTE MAX™ XL N9560. 
android 7 and 8.

application syncs 3 schemas with the same SyncUser, it looks like this:
```
SyncUser.logInAsync(syncCredentials, serverHost, new SyncUser.Callback<SyncUser>() {
                  @Override
                  public void onSuccess(SyncUser user) {
                      if (syncConfigurationAccount == null)
 syncConfigurationAccount = new SyncConfiguration
                                  .Builder(user, serverAccount + accountId)
                                  .waitForInitialRemoteData()
                                  .name("account_" + userId + ".realm")
                                  .modules(new schema.AccountSchemaModules())
                                  .errorHandler(getErrorHandlerOnline())
                                  .build();

                      Realm.getInstanceAsync(syncConfigurationAccount, new Realm.Callback() {
                          @Override
                          public void onSuccess(Realm realm) {
                              syncUser(userId, user);
                          }
                      });
                  }
```
storage capacity should be enough to sync all data. 

what can i try to avoid this issue? :)

**Comment by Zhuinden** [comment]
You might want to store the Realm you get from the callback

**Comment by SiarheiSm** [comment]
Hello. Thank you for responses.

@Zhuinden, i saves 3 `SyncConfiguration`s  and then, to access the data, i do the  `Realm.getInstance(getConfigurationUser());` call. 
is it ok? or should i try to save 'Realm's i got in the `getInstanceAsync`s callback and try to use this ones?

@cmelchior, 
1) yes, data actually in the server, i've used Realm Studio for windows to check. 
2) `SyncSession.downloadAllRemoteChanges()`, as i remember i've tried this when i got the first issue report... but i'm not sure. i'll try again.
3) yes, i have the callback + progress bar, and trying to access db only when sync fully completed.  

thank you

**Comment by SiarheiSm** [comment]
Hello. i've tried to do the way i described above but users still have an issue :(

**Comment by cmelchior** [comment]
Without more information, it is hard to speculate what might be wrong. If the data is the server, but never reaches the devices we need the device logs to be able to diagnose it. Depending on the users network, it might be a firewall that prevents them from syncing.

**Comment by SiarheiSm** [comment]
ok, thank you, i'll try to get logs.

**Comment by SiarheiSm** [comment]
is it possible to save realm log to file on android device? or get logs in string?

**Comment by cmelchior** [comment]
Realm just logs to logcat as the default, so anything that reads LogCat will do. If you want to add a custom logger that writes to something else like a file, you can use `RealmLog.addLogger(RealmLogger)`

**Comment by SiarheiSm** [comment]
Hello, yes, thank you, i've already found this feature. trying to get the logs from user devices. 
i'll let you know when there is any news.
thank you

**Comment by cmelchior** [comment]
Closing due to no response. Feel free to reopen if you can provide more information
