### ISSUE TITLE
Using method reference as change listener

### ISSUE THREAD

**Issue by matt18224** [realm/realm-java#6047]
Are method references whose signatures are equivalent to that of a change listener functionally equivalent to holding a strong reference to an anonymous class or lambda, and therefore guaranteed to be called? Or are these method references subject to garbage collection, and therefore not guaranteed to be called?

For example, in Kotlin:
```
fun onDogsLoaded(dogs: RealmResults<Dog>, changeSet: OrderedCollectionChangeSet?) {
    //Bind data
}

fun onCreate(savedInstanceState: Bundle?) {
    realm.where<Dog>().findAllAsync().addChangeListener(::onDogsLoaded)
}
```

Is `onDogsLoaded()` guaranteed to be called as if it were held as a strong reference? I searched through previous issues and the docs and couldn't find anything about using method references. Thanks!

**Comment by Zhuinden** [comment]
Method reference is ok, but `realm.where<Dog>().findAllAsync()` must be stored as field ref

**Comment by matt18224** [comment]
I just now realized I misread the documentation and thought that the change listener itself needed to be kept as a strong reference or it could be GCd. I realize now that the documentation was saying that simply adding a change listener would not keep the underlying RealmObject from being garbage collected were it not stored as a strong reference, which makes more sense. 

Regardless, I appreciate the response. Thanks!
