### ISSUE TITLE
Read schema version without opening Realm file

### ISSUE THREAD

**Issue by kainjinez** [realm/realm-java#6049]
I have a realm database version 1. When I update many Model (which extends RealmObject) in my app and increase it to 2, I want to check if user db version is 1, i will make a backup for this db before migration to 2. How to get that?
I tried to google it and found this on iOS https://stackoverflow.com/questions/36785743/how-can-i-check-my-realm-schema-version-without-opening-the-realm-file#comment61146952_36785743
Does RealmJava have any function like this?

#### Version of Realm and tooling
Realm version(s): 4.3.2

Realm sync feature enabled: no

Android Studio version: 3.1.1

Which Android version and device: Oreo

**Comment by Zhuinden** [comment]
Technically you still need to open the Realm file, but without a schema check.

You can use `DynamicRealm realm = DynamicRealm.getInstance(realmConfiguration);` to open a dynamic Realm, which has a `getSchemaVersion()` method.
