### ISSUE TITLE
[Cannot pass List realm Object to another activity]

### ISSUE THREAD

**Issue by vfa-tuantt** [realm/realm-java#6052]
I'm facing with a problem. 
I wana to send a list List<Master> into another activity.

```
@Table(name = CL_TABLE_NAME)
@Parcel(
        implementations = arrayOf(MasterRealmProxy::class),
        value = Parcel.Serialization.BEAN,
        analyze = arrayOf( Master::class ))
open class Master( 

): RealmObject() {
}
```
I pass list master data to another activity by this way.
```
var listMaster: List<Master>?
var args = Bundle()
args.putParcelable(IntentKey.INTENT_MASTER_DATA, Parcels.wrap(listMaster))
```

But i got this error:
`org.parceler.ParcelerRuntimeException: Unable to find generated Parcelable class for io.realm.RealmList, verify that your class is configured properly and that the Parcelable class io.realm.RealmList$$Parcelable is generated by Parceler.`

If you know what is problem happening. Please help me. Thank you so much

**Comment by cmelchior** [comment]
sume the above solution solved your issue. If not, feel free to re-open the issue.
