### ISSUE TITLE
your not number one

### ISSUE THREAD

**Issue by ZhangKuixun** [realm/realm-java#6053]
https://github.com/AlexeyZatsepin/Android-ORM-benchmarkhttps://github.com/AlexeyZatsepin/Android-ORM-benchmarkhttps://github.com/AlexeyZatsepin/Android-ORM-benchmark

## Models
```java
public class Library{ 
    String address;
    String name;
}

public class Book{
    String author;
    String title;
    int pagesCount;
    int bookId; 
    Library library;
}
public class Person{
    String firstName;
    String secondName;
    Date birthdayDate;
    String gender;
    long phone;
    Library library;
}
```

## Test cases
* Simple - 1 Library object per 1000 Book objects 
* Complex - 1 Library object for 500 Book objects and 400 Person objects (5 Libraries, 2500 Books, 2000 Persons)
* Balanced - 1 Library object for 50 Book objects and 50 Person objects (50 Libraries, 2500 Books, 2500 Persons)

For each test cache/lazy initialization were turned off, and we perform an average of 10 measurements per operation.
<a href="url"><img src="https://github.com/AlexeyZatsepin/Android-ORM-benchmark/blob/master/screenshots/complex1.jpg?raw=true" align="center" height="640" width="360"></a>
<a href="url"><img src="https://github.com/AlexeyZatsepin/Android-ORM-benchmark/blob/master/screenshots/complex2.jpg?raw=true" align="center" height="640" width="360"></a>
<a href="url"><img src="https://github.com/AlexeyZatsepin/Android-ORM-benchmark/blob/master/screenshots/simple1.jpg?raw=true" align="center" height="640" width="360"></a>
<a href="url"><img src="https://github.com/AlexeyZatsepin/Android-ORM-benchmark/blob/master/screenshots/simple2.jpg?raw=true" align="center" height="640" width="360"></a>

## Results Table

|Library|write(s)|read(s)|update(s)|delete(s)|write(c)|read(c)|update(c)|delete(c)|write(b)|read(b)|update(b)|delete(b)|
|:-----:|:------:|:-----:|:-------:|:-------:|:------:|:-----:|:-------:|:-------:|:------:|:-----:|:-------:|:-------:|
|ORMLite|151|666|122|105|445|3836|857|811|1563|3426|724|728|
|SugarORM|245|842|252|152|1402|4129|1467|1003|2204|4397|1702|1197|
|Freezer|248|5430|240|4797|1337|78982|2221|22104|3255|134942|1887|29515|
|DBFlow|97|757|459|186|360|3534|3124|1044|1129|4653|5204|1268|
|Requery|87|1501|147|129|461|8057|861|802|1368|8002|886|763|
|Realm|151|29|1079|723|698|688|19666|9180|1522|210|21129|10006|
|GreenDAO|81|1238|117|97|357|5552|455|274|598|5905|504|315|
|ActiveAndroid|3123|930|2293|2423|14671|4165|15958|13023|17213|4653|19303|14642|
|Sprinkles|5766|1050|6364|605|25978|4334|65579|2428|27774|4526|37705|2519|
|Room|131|699|170|109|562|3201|717|403|1330|3532|790|507|
|SQLite|50|436|63|80|386|2155|192|284|1146|2313|213|318|

**Comment by Zhuinden** [comment]
```
    //Realm
    realmCompile 'io.realm:realm-android:0.82.1'
```

Latest version is 5.3.1

**Comment by bmunkholm** [comment]
There are many ways to make benchmarks - including a lot of wrong ways :-) We have attempted to note some of those gotchas here https://github.com/realm/realm-java-benchmarks.
Closing as it's not clear that any action is required.
