### ISSUE TITLE
[realm-core-5.6.2] Assertion failed: r == 0

### ISSUE THREAD

**Issue by DFGDEN** [realm/realm-java#6054]
Realm version(s):
5.3.1
Android version:
8.0.0
Device:
HUAWEIATU-L31

E/REALM: /home/jenkins/workspace/realm_realm-core_master-ZBP7YYGK7EEKLBWAJKZQMIXPK7BHX4IZSAMXTSGLQ5SXVPPKKJMQ/src/realm/util/file.cpp:1015: [realm-core-5.6.2] Assertion failed: r == 0
!!! IMPORTANT: Please send this log and info about Realm SDK version and other relevant reproduction info to help@realm.io.
Fatal signal 6 (SIGABRT), code -6 in tid 18325 (pool-3-thread-2)

**Comment by bmunkholm** [comment]
@DFGDEN Can you please include the full crash log please? Thanks!

**Comment by shawhkhi** [comment]
Thanks

saadzmee33

في الجمعة، ٦ يوليو، ٢٠١٨ ١٨:٢٩ Brian Munkholm <notifications@github.com>
كتب:

**Comment by shawhkhi** [comment]
Ok

**Comment by cmelchior** [comment]
Closing due to no response. Feel free to reopen if this is still a problem.
