### ISSUE TITLE
Remember to call close() on all Realm instances.

### ISSUE THREAD

**Issue by iman2420** [realm/realm-java#6055]
#### Goal

>To allow app to work by solving realm memory issues

#### Expected Results

>  Optimize realm memory usage on all devices

#### Actual Results

>  --> Java_io_realm_internal_OsSharedRealm_nativeIsClosed -1272509336
     --> Java_io_realm_internal_OsSharedRealm_nativeIsInTransaction -1272509336
     --> Java_io_realm_internal_UncheckedRow_nativeSetLong -1575890096
     --> Java_io_realm_internal_OsSharedRealm_nativeIsClosed -1272509336
     --> Java_io_realm_internal_OsSharedRealm_nativeIsInTransaction -1272509336
     --> Java_io_realm_internal_UncheckedRow_nativeSetString -1575890096
     --> Java_io_realm_internal_UncheckedRow_nativeGetIndex -1575890144
     --> Java_io_realm_internal_OsSharedRealm_nativeIsClosed -1272509336
     --> Java_io_realm_internal_UncheckedRow_nativeIsAttached -1575890144
     --> Java_io_realm_internal_UncheckedRow_nativeGetIndex -1575890144
     --> Java_io_realm_internal_OsSharedRealm_nativeIsInTransaction -1272509336
     --> Java_io_realm_internal_UncheckedRow_nativeSetLink -1575890096
     --> Java_io_realm_internal_OsSharedRealm_nativeIsClosed -1272509336
     --> Java_io_realm_internal_OsSharedRealm_nativeIsInTransaction -1272509336
     --> Java_io_realm_internal_UncheckedRow_nativeSetString -1575890096
     --> Java_io_realm_internal_OsSharedRealm_nativeIsClosed -1272509336
     --> Java_io_realm_internal_OsSharedRealm_nativeIsInTransaction -1272509336
     --> Java_io_realm_internal_UncheckedRow_nativeSetTimestamp -1575890096
     --> Java_io_realm_internal_OsSharedRealm_nativeIsClosed -1272509336
     --> Java_io_realm_internal_OsSharedRealm_nativeIsInTransaction -1272509336
     --> Java_io_realm_internal_UncheckedRow_nativeNullifyLink -1575890096
     --> Java_io_realm_internal_UncheckedRow_nativeGetIndex -1575890112
     --> Java_io_realm_internal_OsSharedRealm_nativeIsClosed -1272509336
     --> Java_io_realm_internal_UncheckedRow_nativeIsAttached -1575890112
     --> Java_io_realm_internal_UncheckedRow_nativeGetIndex -1575890112
     --> Java_io_realm_internal_OsSharedRealm_nativeIsInTransaction -1272509336
     --> Java_io_realm_internal_UncheckedRow_nativeSetLink -1575890096
     --> Java_io_realm_internal_OsSharedRealm_nativeIsClosed -1272509336
     --> Java_io_realm_internal_OsSharedRealm_nativeIsInTransaction -1272509336
     --> Java_io_realm_internal_UncheckedRow_nativeSetBoolean -1575890096
     --> Java_io_realm_internal_OsSharedRealm_nativeIsClosed -1272509336
     --> Java_io_realm_internal_OsSharedRealm_nativeIsInTransaction -1272509336
     --> Java_io_realm_internal_UncheckedRow_nativeSetNull -1575890096
     --> Java_io_realm_internal_OsSharedRealm_nativeIsClosed -1272509336
     --> Java_io_realm_internal_OsSharedRealm_nativeIsInTransaction -1272509336
     --> Java_io_realm_internal_UncheckedRow_nativeSetLong -1575890096
     --> Java_io_realm_internal_OsSharedRealm_nativeIsClosed -1272509336
     --> Java_io_realm_internal_OsSharedRealm_nativeIsClosed -1272509336
     --> Java_io_realm_internal_UncheckedRow_nativeGetIndex -1575890096
     --> Java_io_realm_internal_OsList_nativeAddRow -1551789440
     --> Java_io_realm_internal_OsSharedRealm_nativeIsClosed -1272509336
     --> Java_io_realm_internal_OsSharedRealm_nativeCommitTransaction -1272509336
07-07 02:56:23.573 com.android.quiz V/REALM_JNI:  --> Java_io_realm_internal_OsSharedRealm_nativeIsClosed -1370896504
07-07 02:56:23.573 com.android.quiz W/REALM_JAVA: Remember to call close() on all Realm instances. Realm /data/data/com.android.xxx/files/default.realm is being finalized without being closed, this can lead to running out of native memory.
07-07 02:59:52.021 com.android.quiz V/REALM_JNI:  --> Java_io_realm_internal_OsSchemaInfo_nativeCreateFromList
     --> Java_io_realm_internal_OsRealmConfig_nativeCreate
     --> Java_io_realm_internal_OsRealmConfig_nativeSetInMemory -1370380416
     --> Java_io_realm_internal_OsRealmConfig_nativeEnableChangeNotification -1370380416
     --> Java_io_realm_internal_OsRealmConfig_nativeSetSchemaConfig -1370380416
     --> Java_io_realm_internal_OsRealmConfig_nativeSetCompactOnLaunchCallback -1370380416
     --> Java_io_realm_internal_OsSharedRealm_nativeGetSharedRealm -1370380416
     --> Java_io_realm_internal_OsSharedRealm_nativeGetSchemaInfo -1370896000

#### Code Sample

```Realm realm = App.getRealmInstance();
            try {
                realm.beginTransaction();
                ....
				....
				....
                realm.commitTransaction();
            } catch (JSONException | ParseException e) {
                e.printStackTrace(); realm.cancelTransaction();
            } finally {
                realm.close();
            }

> Your code here. Bigger samples should ideally be as separate Android Studio project, 
> in gists/repositories or privately at help@realm.io)

```

#### Version of Realm and tooling
Realm version(s): ?

>         classpath "io.realm:realm-gradle-plugin:5.1.0"

Android Studio version: 

> Android Studio 3.1.3
Build #AI-173.4819257, built on June 4, 2018
JRE: 1.8.0_152-release-1024-b02 amd64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
Windows 10 10.0

**Comment by cmelchior** [comment]
@iman2420 I assume the above answered your question. If not feel free to reopen.
