### ISSUE TITLE
how to in library use realm?

### ISSUE THREAD

**Issue by ZhangKuixun** [realm/realm-java#6057]
library/build.gradle/apply:
apply plugin: 'com.android.library'
apply plugin: 'realm-android'

app/build.gradle/apply:
apply plugin: 'com.android.application'

error:User is not part of the schema for this Realm

not Kotlin

**Comment by Zhuinden** [comment]
you need to expose `User` class with a `@RealmModule` and then add it to the schema, typically like `RealmConfiguration.Builder().schema(Realm.getDefaultModule(), YourLibraryModule()).build()`

**Comment by ZhangKuixun** [comment]
It's complicated，I want to wrap it up. 
e.g.:
`public interface IRealm<T extends RealmObject> {
    void create(Class rm);
    void insert(T rm) ;
}`

**Comment by Zhuinden** [comment]
Then you're basically looking to write https://github.com/Zhuinden/realm-monarchy/ yourself

**Comment by ZhangKuixun** [comment]
oh,I love you
