### ISSUE TITLE
How to set realm result to realm recyvlerview in background thread

### ISSUE THREAD

**Issue by vavadiyahiren** [realm/realm-java#6059]
Hi Team,

I am using realm for one of my android application.

I am using realm adapater and getting results from the two diffrent table and then intializing to the adapter which is currently happening on ui thread which tens to bad user experience because for the intial it takins some time to load to adapter.

I have gone through many examples in all such examples realm results are getting execute on ui thread only but those requirements are very easy to fulfill so i believe realm are enough fast and they didn't get any performance impect but this is very critical for me so how to get result on background thread and set the result and listners only on ui thread.

I have tried to do the same but it is throwing exeception like i am doing operation on wrong thread so realm won't allow us to do the same so anyone have answer for this to how to do it safly then please help us to get out of it.

Thanks,
Hiren vavadiya

**Comment by Zhuinden** [comment]
You need to do what this answer does, except with findAllAsync: https://stackoverflow.com/a/34976540/2413303

**Comment by vavadiyahiren** [comment]
Thanks i will try this one out and let you know my best results.

**Comment by cmelchior** [comment]
I assume the above solution solved your issue. If not, feel free to re-open the issue.
