### ISSUE TITLE
How many transactions can be used in background?

### ISSUE THREAD

**Issue by demid4shared** [realm/realm-java#6065]
#### Goal

Example 1
> Thread 1{
  realm.executeTransaction{
  write realm object
  }
  do something 
  realm.executeTransaction{
  write realm object
  }
  not update RealmObject
}

Example 2
>Thread 1{
  realm.executeTransaction{
  write realm object
  }
  do something 
  realm.refresh
  realm.executeTransaction{
  write realm object
  }
  realm.refresh 
  not update RealmObject
}

Work only
Example 3
>Thread 1{
  realm.executeTransaction {
  write realm object
  do something
  write realm object
  do something
  }
}

Why is that? Why can not I update the objects and see their results after executeTransaction?

#### Version of Realm and tooling
Realm version(s): 5.3.1

Realm sync feature enabled: no

Android Studio version: 3.1.3

**Comment by Zhuinden** [comment]
I don't understand your pseudocode, can you provide real code?

**Comment by demid4shared** [comment]
public class MainClass {

    public static class RealmDao {

        public static void insertOrUpdate(String id, String str) {
            try (Realm realm = DBManager.getInstance().getRealm()) {
                realm.executeTransaction(realm1 -> {
                    RealmObject object = realm1.where(RealmObject.class).equalTo("id", id).findFirst();
                    object.setStringValue(str);
                    realm1.insertOrUpdate(object);
                });
            }
        }

        public static void updateValue(String id, boolean value) {
            try (Realm realm = DBManager.getInstance().getRealm()) {
                realm.executeTransaction(realm1 -> {
                    RealmObject object = realm1.where(RealmObject.class).equalTo("id", id).findFirst();
                    object.setValue(value);
                    realm1.insertOrUpdate(object);
                });
            }
        }

        public static RealmObject getCopiedObject(String id) {
            try (Realm realm = DBManager.getInstance().getRealm()) {
                return realm.where(RealmObject.class).equalTo("id", id).findFirst();
            }
        }
    }
    
    public static void main(String[] args) {
        send("id", "object");
    }

    private static void send(String id, String str) {
        new Thread(() -> {
            RealmDao.insertOrUpdate(id, str);
            send(id);
        }).start();
    }

    private static void send(String id) {
        RealmDao.updateValue(id, true);
        //not updated realm object 
        NetworkApi.getInstance().updateInServer(RealmDao.getCopiedObject(id));
        RealmDao.updateValue(id, false);
        //not updated realm object
    }
}

**Comment by demid4shared** [comment]
Even if I delete RealmDao.updateValue (id, false), I will not see the object update - RealmDao.updateValue (id, true);
It seems that executeTransaction does not work, but there are no errors.

**Comment by cmelchior** [comment]
It isn't clear to me why your code shouldn't work? You are not showing the code that checks the value? Can you provide a fully working example?

Also you don't need `realm1.insertOrUpdate(object);` when changing a managed object. In that case, that method does nothing.

**Comment by demid4shared** [comment]
there is incomprehensibility

**Comment by demid4shared** [comment]
```java
public class ExampleObject extends RealmObject {
    @Required
    @PrimaryKey
    private String id;
    private String value;
    private boolean valueBool;

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }

    public String getValue() {
        return value;
    }

    public void setValue(String value) {
        this.value = value;
    }

    public boolean isValueBool() {
        return valueBool;
    }

    public void setValueBool(boolean valueBool) {
        this.valueBool = valueBool;
    }
}

public class MainClass {

    public static class RealmDao {

        public static void insertOrUpdate(String id, String str) {
            try (Realm realm = DBManager.getInstance().getRealm()) {
                realm.executeTransaction(realm1 -> {
                    ExampleObject exampleObject = new ExampleObject();
                    exampleObject.setId(id);
                    exampleObject.setValue(str);
                    realm1.copyToRealmOrUpdate(exampleObject);
                });
            }
        }

        public static void updateValue(String id, boolean value) {
            try (Realm realm = DBManager.getInstance().getRealm()) {
                realm.executeTransaction(realm1 -> {
                    ExampleObject object = realm1.where(ExampleObject.class).equalTo("id", id).findFirst();
                    object.setValueBool(value);
                });
            }
        }

        public static ExampleObject getCopiedObject(String id) {
            try (Realm realm = DBManager.getInstance().getRealm()) {
                return realm.copyFromRealm(getObject(realm, id));
            }
        }

        public static ExampleObject getObject(Realm realm, String id) {
            return realm.where(ExampleObject.class).equalTo("id", id).findFirst();
        }

        public static RealmResults<ExampleObject> getObjects(Realm realm) {
            return realm.where(ExampleObject.class).findAll();
        }
    }

    private static RealmResults<ExampleObject> realmResults;

    public static void send(String id, String str) {
        Realm realm = DBManager.getInstance().getRealm();
        realmResults = RealmDao.getObjects(realm);

        realmResults.addChangeListener((realmResults1, changeSet) -> {
            if (changeSet.getChangeRanges().length > 0) {
                ExampleObject object = realmResults1.get(0);
                if (object.isValueBool()) {
                    Log.d(">>>>>>>>>>>", "is bool true");
                } else {
                    Log.d(">>>>>>>>>>>", "is bool false");
                }
            }
        });

        new AsyncTask<Void, Void, Void>() {
            @Override
            protected Void doInBackground(Void... voids) {
                RealmDao.insertOrUpdate(id, str);
                send(id);
                return null;
            }

            @Override
            protected void onPostExecute(Void aVoid) {
                ExampleObject object = RealmDao.getCopiedObject("id");
                Log.d(">>>>>>>>>>>", "Background is finished");
                if (object.isValueBool()) {
                    Log.d(">>>>>>>>>>>", "is bool true");
                } else {
                    Log.d(">>>>>>>>>>>", "is bool false");
                }
            }
        }.execute();
    }

    private static void send(String id) {
        Log.d(">>>>>>>>>>>", "set first true");
        RealmDao.updateValue(id, true);
        Log.d(">>>>>>>>>>>", "set first false");
        RealmDao.updateValue(id, false);
        try {
            Thread.sleep(2000);
        } catch (InterruptedException ignored) {
        }
        Log.d(">>>>>>>>>>>", "set second true");
        RealmDao.updateValue(id, true);
    }
}

public class ExampleActivity extends ThemedActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        MainClass.send("id", "example");
    }
}

=================================================
Logs:
07-18 14:15:45.732 D/>>>>>>>>>>>: set first true
07-18 14:15:45.739 D/>>>>>>>>>>>: set first false
07-18 14:15:47.746 D/>>>>>>>>>>>: set second true
07-18 14:15:47.760 D/>>>>>>>>>>>: is bool true
07-18 14:15:47.762 D/>>>>>>>>>>>: Background is finished
    is bool true

**Comment by demid4shared** [comment]
why does not "ChangeListener" work between
07-18 14: 15: 45.732 D / >>>>>>>>>>>: set first three
and
07-18 14: 15: 45.739 D / >>>>>>>>>>>: set first false

**Comment by demid4shared** [comment]
realm.refresh () does not help. Works only with Thread.sleep (250);

**Comment by demid4shared** [comment]
And time, too, does not help. This indicates that there must be one transaction for each thread to see updates in ui

**Comment by Zhuinden** [comment]
Well the `realm.refresh()` would need to be executed in `onPostExecute`.

**Comment by demid4shared** [comment]
so I need events in the "ChangeListener"

**Comment by demid4shared** [comment]
and in "ChangeListener" all the events on the change do not come

**Comment by demid4shared** [comment]
Logs:
07-18 14:15:45.732 D/>>>>>>>>>>>: set first true 
07-18 14:15:45.739 D/>>>>>>>>>>>: set first false
07-18 14:15:47.746 D/>>>>>>>>>>>: set second true
07-18 14:15:47.760 D/>>>>>>>>>>>: is bool true - 
07-18 14:15:47.762 D/>>>>>>>>>>>: Background is finished is bool true
