### ISSUE TITLE
help

### ISSUE THREAD

**Issue by ruanbaojun1105** [realm/realm-java#6070]
![e u2t5 uh4 z i w b tc](https://user-images.githubusercontent.com/7459297/42933288-05da011e-8b77-11e8-9c65-e8b3a9dc179a.png)

#### Version of Realm and tooling
Realm version(s): 5.2.0

Realm sync feature enabled: yes

Android Studio version: 3.1.3

Which Android version and device: 8.1

**Comment by Zhuinden** [comment]
How big is your Realm file? This should only happen if your Realm file is at least 2+ GB.

**Comment by ruanbaojun1105** [comment]
ok,thanks! i try close it
