### ISSUE TITLE
When Using realm The App Is too Heavy

### ISSUE THREAD

**Issue by IamJithendra** [realm/realm-java#6071]
How to  Use Pro guard For This Issue ?

**Comment by cmelchior** [comment]
What do you mean with "too heavy"?

**Comment by Zhuinden** [comment]
ABI splits.

**Comment by IamJithendra** [comment]
Without realm the App size is 4 MB and when using Realm The App is 9 MB

**Comment by cmelchior** [comment]
Yes, that is expected. Realm with all ABI's is around ~5 MB. You can use ABI splits to reduce it to 1-1.5 MB. See https://realm.io/docs/java/latest/#faq-library-size
