### ISSUE TITLE
RealmThreadPoolExecutor must be public constructor

### ISSUE THREAD

**Issue by gelbertgel** [realm/realm-java#6081]
Realm version : 5.4.0

I have realmThreadExecutor and I want to extend RealmThreadPoolExecutor by realm but it is not add super constructor because of RealmThreadPoolExecutor's constructor is private. I want to add something to the realmThreadExecutor by myself.

Could you do public RealmThreadPoolExecutor's's constructor? 

```
public class RealmThreadExecutor extends RealmThreadPoolExecutor {

    private String TAG = RealmThreadExecutor.class.getSimpleName();
    private RealmManager realmManager;

    RealmThreadExecutor() {
        super(1,1);  ---> it doesn't
        realmManager = new RealmManager();
    }

    @Override
    protected void beforeExecute(Thread thread, Runnable runnable) {
        super.beforeExecute(thread, runnable);

        Realm realm = realmManager.getLocalInstance();

        RealmRunnable realmRunnable = (RealmRunnable) runnable;
        realmRunnable.setRealm(realm);
        realmRunnable.setThread(thread);
    }

    @Override
    protected void afterExecute(Runnable runnable, Throwable throwable) {
        super.afterExecute(runnable, throwable);

        RealmRunnable realmRunnable = (RealmRunnable) runnable;
        Realm realm = realmRunnable.getRealm();
        realmManager.close(realm);

        //stop threads
        realmRunnable.getThread().interrupt();
        shutdown();
    }

    private void printCurrentThreads() {

        Set<Thread> threadSet = Thread.getAllStackTraces().keySet();

        for (Thread thread : threadSet) {
            Mylog.i(TAG, " getAllCurrentThreadCount cikis : " + thread.getName());
        }
    }
}
```

**Comment by nhachicha** [comment]
I'm not sure what you're trying to achieve but note that:
- `RealmThreadPoolExecutor` is an internal package 
- Even if you could subclass `RealmThreadPoolExecutor`, we have no public API to replace the Threadpool (_unless you use reflection_)

**Comment by gelbertgel** [comment]
Could you do public RealmThreadPoolExecutor's constructor?

**Comment by Zhuinden** [comment]
Even if they did, it would not solve your problem

**Comment by gelbertgel** [comment]
How can I solve my problem. do you have suggestions

**Comment by cmelchior** [comment]
Outdated, so closing. If you want to use whatever functionality the `RealmThreadPoolExecutor` provides you can just copy the logic into your own class.

It isn't that we are against modifying our internal classes to suit needs but we would need a compelling use case for it, which in this case doesn't seem to be present compared to the alternative (just copy the class).
