### ISSUE TITLE
Samsung S8 librealm-jni.so crash

### ISSUE THREAD

**Issue by Delphian2015** [realm/realm-java#6085]
Hello. 

Our app crashes on Samsung S8 devices.  It depends on the debuggable flag 

```
android {
  buildTypes {
    release {
       debuggable false
    }
  }
}
```
If we set flag in TRUE mode everything ok, but if we set FALSE we catch the error:

![crash](https://user-images.githubusercontent.com/14300153/43327039-05b66dd8-91c3-11e8-86a4-96f8b59d2134.jpg)

Using:
io.realm:realm-gradle-plugin:5.3.1

**Comment by Delphian2015** [comment]
Works without crash on the version 3.5.0

**Comment by Zhuinden** [comment]
And it crashes with 3.7.1 and above?

**Comment by Delphian2015** [comment]
We upgraded version to 4.0.0 because of mockito. Mockito doesn't work on 3.5.0. Higher versions didn't test.

**Comment by cmelchior** [comment]
Outdated, so closing. If this is still a problem please re-open and provide a sample project demonstrating the issue so we can debug it.

**Comment by lubbo** [comment]
I'm having the same problem with Samsung A8 Android 8.0.0
