### ISSUE TITLE
Query child objects with multiple queries like SUBQUERY on iOS

### ISSUE THREAD

**Issue by kevinvanmierlo** [realm/realm-java#6092]
I want to be able to add multiple queries on child objects. For example I have a `Member` object which has multiple `MemberOther` objects. `MemberOther` is actually a collection for numerous things. I'm trying to query a `RealmList` which contains members to retrieve `MemberOther` objects using a filter. The problem that I'm having is that I need to query multiple things on `MemberOther` objects. For example a simple query would be that a `MemberOther` object should be a specific type AND lower than a specific number. So I thought I would do this query:

```Kotlin
members.equalTo("others.type", type).lessThanOrEqualTo("others.startYear", yearFilter.startYear)
```

So from the first `equalTo` retrieves the members which have memberOthers of a specific type. But the second one retrieves the members which have a startYear lower than my filter BUT doesn't take into account the specific type I used for the first query. 

On iOS this is possible using a SUBQUERY:

```objective-c
[NSPredicate predicateWithFormat:@"SUBQUERY(memberOthers, $memberOther, $memberOther.type == %@ AND $memberOther.startYear <= %@) .@count > 0", type, @(yearFilter.startYear)];
```

I've read other issues like https://github.com/realm/realm-java/issues/1237 and https://github.com/realm/realm-java/issues/1598. But one is already closed and the other is about the aggregate queries and not specifically about multiple queries on child objects. 

Do you have anything on the timeline that will support these kind of queries?

Thanks in advance!

**Comment by cmelchior** [comment]
Unfortunately `SUBQUERY` isn't supported in the Java SDK yet but you can read https://realm.io/docs/java/latest/#link-queries which can give you some insight in to how to build up a query doing something similar.

**Comment by kevinvanmierlo** [comment]
I have looked at the documentation, but unfortunately it isn't able to do this kind of query. What I have done now is query all the objects and filter them by using Kotlin collection functions. While this would suffice for small lists, it could be a problem when the list grows. Because the thing I want to do is filter the list by two conditions of the child objects at the same time. So I can write the conditions, but Realm will only execute one at the time. 

For example I have an object which has two child objects. One has the type "yearclub" and the other has the type "comission". The first will have startYear of 2015 and the second startYear of 2017. I want to get get an object which has a child object with type "yearclub" and startYear above or equal to 2016. If I write the query `members.equalTo("others.type", "yearclub").greaterThanOrEqualTo("others.startYear", 2016)` it will first get the members which have a child object of type yearclub. Which is true. And then filter that list if the child object has startYear above or equal to 2016. This is also true because the commission type has a startYear of 2017. This happens because this query is done one by one. But for this query I want both conditions in the same query. So it would be I want the child object which has type "yearclub" AND startYear above or equal to 2016. This would return no results because our "yearclub" has a startYear of 2015.

So as of right now it is not possible to do the kind of query I want to perform. I can only filter this myself using collection functions.

Is the `SUBQUERY` on the timeline for the Java SDK or another way of executing these kind of queries?

**Comment by cmelchior** [comment]
Yes, the only way to express this in Java currently is something like:

```
members
  .equalTo("others.type", type)
  .findAll()
  .where()
  .lessThanOrEqualTo("others.startYear", yearFilter.startYear)
  .findAll();
```

Unfortunately, this means running two queries in sequence which cannot currently be done in the background easily.

We are currently exploring adding syntax support for the text-based query language used in Cocoa. You can see the PR here #6116. This is probably the easiest way to add the kind of support you need.

**Comment by kevinvanmierlo** [comment]
The PR would open some possibilities on more complex queries! I gave it a thumbs up!

Just to be extra clear, the query you just wrote would still give back the wrong results. This is because it is not filtering the `others` but it's filtering the `members`. Every `member`  has `others`. `others` have a `type` and a `startYear` (they have more, but that's not the point right now). So when we have two members, with both 2 `others`. I will write it below to make some visualisation

```
Member1 others:
{
   "type": "yearclub",
   "startYear": 2015
},
{
   "type": "commission",
   "startYear": 2017
}

Member2 others:
{
   "type": "yearclub",
   "startYear": 2017
},
{
   "type": "commission",
   "startYear": 2012
}
```

As you said the query would be done in sequence. So let's start with the first part: 
```
.equalTo("others.type", "yearclub").findAll()
``` 
This would return both members, since both have an `other` with type "yearclub". 

So let's continue to the next part: 
```
.where()
  .greaterThanOrEqualTo("others.startYear", 2016)
  .findAll()
```
This would also return both members, since the first member has an `other` with "startYear" 2017. This is not a "yearclub" but it does meet the conditions of the query. 

It makes sense that the query does this, but it is not what I'm looking for. What I was looking for would be that the result of this query would only return Member2. Because this `member` is the only one that meets both of the conditions.

**Comment by cmelchior** [comment]
https://github.com/realm/realm-java/pull/6116 merged support for String-based query predicates, which should support this. This will be part of 10.4.0.
