### ISSUE TITLE
Get all rows with date > current date + 1 day?

### ISSUE THREAD

**Issue by lmdic** [realm/realm-java#6094]
Here my java Realm object on my Android application.

```
public class Offer extends RealmObject {
    @PrimaryKey
    private int id;
    private boolean favorite;
    private Date dateUntil = new Date();
}
```

I need to write request to Realm that return all `offers `with **dateUntil > (current date + 1 day)**.

E.g. 
Suppose the current date is **02 Aug 2018** and I have 5 offers with the next `dateUntil`:

```
01 Aug 2018
02 Aug 2018
03 Aug 2018
04 Aug 2018
05 Aug 2018
```

The request must return only the 2 offers with the next `dateUntil`:
```
04 Aug 2018
05 Aug 2018
```

How I can do this request in Realm?

**Comment by Zhuinden** [comment]
Have you tried:

    Calendar calendar = Calendar.getInstance();
    calendar.add(Calendar.DAY_OF_YEAR, 1);
    calendar.set(Calendar.HOUR_OF_DAY, 0);
    calendar.set(Calendar.MINUTE, 0);
    calendar.set(Calendar.SECOND, 0);
    calendar.set(Calendar.MILLISECOND, 0);
    Date tomorrow = calendar.getTime();
    RealmResults<Offer> offers = realm.where(Offer.class).greaterThanOrEqualTo("dateUntil", tomorrow).findAll();
