### ISSUE TITLE
realm from Non-UI thread invoking changelistener from UI thread.

### ISSUE THREAD

**Issue by sudhanshugaur4** [realm/realm-java#6097]
I have two realm instances one in Non-UI thread and other in UI thread, I am updating realm values in `Non-UI thread` but how the change listener is getting invoked in `UI` thread?

Actually, I want this behaviour to happen but in docs, I read that this cannot happen as different realm instances have different copies of data if they are created in different threads?

**Comment by Zhuinden** [comment]
>  but how the change listener is getting invoked in UI thread?

If you commit a transaction, then this happens automatically.

    RealmResults<T> results;

    public void __() {
        results = realm.where(...)./*...*/.findAllAsync();
        results.addChangeListener(...);
