### ISSUE TITLE
bad

### ISSUE THREAD

**Issue by ruanbaojun1105** [realm/realm-java#6098]
![image](https://user-images.githubusercontent.com/7459297/43703593-c97ecffc-998f-11e8-8bc8-758dd9fda3f5.png)
![image](https://user-images.githubusercontent.com/7459297/43703598-d23e6d32-998f-11e8-8b5a-aeffcdaf2560.png)

i cannot Understand！！！！
caiji

**Comment by Zhuinden** [comment]
RealmObject cannot extend another RealmObject.

https://github.com/realm/realm-java/issues/761
