### ISSUE TITLE
Android Migration Error: Field name doesn't exist on object 'PaperlessItem': primaryKey

### ISSUE THREAD

**Issue by subash-poudel** [realm/realm-java#6099]
I am working on an existing project and need to update our Realm migration in android.
My work flow and requirements:
In an existing realm class **Page**, need to add a new field **private RealmList<PaperlessItem> paperlessItems;**

Page class already exists and **PaperlessItem** model is added in the current migration.

**PaperlessItem.java** class

`public class PaperlessItem extends RealmObject {

  @PrimaryKey private long primaryKey;
  @Index private String changeMessage;
  @Index private String note;
  @Index private String uom;
  @Index private String serviceType;
  private int quantity;
  @Index private String charge;
  @Index private String description;
  private FieldPosition serialNoPosition; // this is another realm object
  @Index private String productCode;

  public PaperlessItem() {
  }`

Relevant migration block:

`if (oldVersion == 18) {
      RealmObjectSchema pageSchema = realm.getSchema().get("Page");
      // create the required schema
      RealmObjectSchema paperlessItemsSchema = realm.getSchema().create("PaperlessItem");
      paperlessItemsSchema.addPrimaryKey("primaryKey"); 
      paperlessItemsSchema.addField("changeMessage", String.class, FieldAttribute.INDEXED);
      paperlessItemsSchema.addField("note", String.class, FieldAttribute.INDEXED);
      paperlessItemsSchema.addField("uom", String.class, FieldAttribute.INDEXED);
      paperlessItemsSchema.addField("serviceType", String.class, FieldAttribute.INDEXED);
      paperlessItemsSchema.addField("quantity", Integer.class, FieldAttribute.REQUIRED);
      paperlessItemsSchema.addField("charge", String.class, FieldAttribute.INDEXED);
      paperlessItemsSchema.addField("description", String.class, FieldAttribute.INDEXED);
      paperlessItemsSchema.addField("productCode", String.class, FieldAttribute.INDEXED);

      RealmObjectSchema serialNoPositionSchema = realm.getSchema().get("FieldPosition");
      paperlessItemsSchema.addRealmObjectField("serialNoPosition", serialNoPositionSchema);

      pageSchema.addRealmListField("paperlessItems", paperlessItemsSchema).transform(new RealmObjectSchema.Function() {
        @Override public void apply(DynamicRealmObject obj) {
          Timber.e("inside paperlessItems schema transform");
        }
      });
      oldVersion++;
    }`

Realm Configuration:
`realmConfiguration = new RealmConfiguration.Builder().name(REALM_NAME)
          .schemaVersion(CURRENT_VERSION)
          .migration(new DeliveryTrackRealmMigration())
          .modules(new RealmAppModule())
          .build();
    }`

I am getting error:
Cannot find primaryKey in PaperlessItem

On this line:
      paperlessItemsSchema.addPrimaryKey("primaryKey");

#### Goal

> What do you want to achieve?

#### Expected Results

> ?

#### Actual Results

>  E.g. full stack trace with exception

#### Steps & Code to Reproduce

> Describe your current debugging efforts.
I have tried the examples of migration from realm-java github repo. My requirement is similar to the Pet realm list add example but with a primary key. I am unable to get it to work.
#### Code Sample

```java

> Your code here. Bigger samples should ideally be as separate Android Studio project, 
> in gists/repositories or privately at help@realm.io)

```

#### Version of Realm and tooling
Realm version(s): ?
2.1.0
Realm sync feature enabled: yes/no
no
Android Studio version: ?
3.1.3
Which Android version and device: ?
Samsung Galaxy S8 Android 8.0

**Comment by Zhuinden** [comment]
You need to actually add the field to the schema before you can set a primary key constraint on the field.

**Comment by subash-poudel** [comment]
@Zhuinden I changed the migration code to:
`paperlessItemsSchema.addField("primaryKey", Long.class, FieldAttribute.INDEXED);
      //paperlessItemsSchema.removeIndex("primaryKey");
      paperlessItemsSchema.addPrimaryKey("primaryKey");`

I am getting another error when doing something like above:

```
Migration is required due to the following errors:
    - Property 'PaperlessItem.primaryKey' has been made required.
```
I tried setting other FieldAttribute but to no avail.

**Comment by Zhuinden** [comment]
`@PrimaryKey private long primaryKey;` is defined as `long` and not `Long`, so it's implicitly required.

You need to add it as paperlessItemsSchema.addField("primaryKey", Long.class, FieldAttribute.REQUIRED);`. Doing `FieldAttribute.INDEXED` should be unnecessary because `addPrimaryKey` is implicitly `indexed` too.

**Comment by subash-poudel** [comment]
@Zhuinden Thank you for the help. This particular migration caused a lot of trouble for me.
