### ISSUE TITLE
Unrecoverable error, while refreshing the access Token (ACCESS_DENIED(614)

### ISSUE THREAD

**Issue by pvtai** [realm/realm-java#6105]
#### Goal

> What do you want to achieve?
I just created new realm cloud account and using new instance to build Android app, But often this error, can not sync data: 
REALM_JAVA: Unrecoverable error, while refreshing the access Token (ACCESS_DENIED(614)
    The path is invalid or current user has no access.) reschedule will not happen

#### Expected Results

> Resolved this error and sync data smoothly.

#### Actual Results

>  E.g. full stack trace with exception
REALM_JAVA: Unrecoverable error, while refreshing the access Token (ACCESS_DENIED(614)
    The path is invalid or current user has no access.) reschedule will not happen

#### Steps & Code to Reproduce

> Describe your current debugging efforts.

#### Code Sample

```java

> Your code here. Bigger samples should ideally be as separate Android Studio project, 
> in gists/repositories or privately at help@realm.io)

```

#### Version of Realm and tooling
Realm version(s): 
implementation 'io.realm:android-adapters:3.0.0'
classpath "io.realm:realm-gradle-plugin:5.4.1"

Realm sync feature enabled: yes

Android Studio version: 3.1.4

Which Android version and device: Moto G 5.1.1

**Comment by pvtai** [comment]
@cmelchior Thank you for your reply.
My code for setup:

```
public class RealmConstants {
    private static final String INSTANCE_ADDRESS = "handmade-concrete-shirt.us1.cloud.realm.io";
    public static final String AUTH_URL = "https://" + INSTANCE_ADDRESS + "/auth";
    public static final String REALM_BASE_URL = "realms://" + INSTANCE_ADDRESS +"/LifeSiteRealmDB";
}
```

```
public class RealmHelper {
public static void configRealm() {
        SyncConfiguration configuration = SyncUser.current()
                .createConfiguration(RealmConstants.REALM_BASE_URL)
                .build();
        Realm.setDefaultConfiguration(configuration);
    }
}
```


```
private void doLogin() {
String username = txUsername.getText().toString();
		String pass = txPass.getText().toString();
		SyncCredentials credentials = SyncCredentials.usernamePassword(username, pass, false);
		SyncUser.logInAsync(credentials, RealmConstants.AUTH_URL, new SyncUser.Callback<SyncUser>() {
			@Override
			public void onSuccess(@NonNull SyncUser user) {
				RealmHelper.configRealm();
				navigateToMain();
			}

			@Override
			public void onError(@NonNull ObjectServerError error) {
				dismissProgress();
				Toast.makeText(getContext(), "Login failed", Toast.LENGTH_SHORT).show();
			}
		});
}
```

Please help to review, thanks.

**Comment by nhachicha** [comment]
- Did you create the user using Realm Studio? 
- Did you set any special permission on the Realm you're trying to connect to? 
- Can you post a screenshot from Realm Studio to show the partial Realms? (`view`/`Show Partial Realms`) Can you check that the owner of the Realm is the your user you're trying to connect with?

**Comment by cmelchior** [comment]
Closing due to no response. Feel free to reopen if this is still a problem.
