### ISSUE TITLE
get RealmObject's property value wrong?

### ISSUE THREAD

**Issue by davidgerka** [realm/realm-java#6109]
My RealmObject's property is public, when i get votes value like "long k = city.votes;", k is 0 always.I only get the real value like "long a = city.getVotes();", is that a bug ?
#### Code Sample
public class City extends RealmObject {
    @PrimaryKey
    public String name; 
    public long votes;  

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public long getVotes() {
        return votes;
    }

    public void setVotes(long votes) {
        this.votes = votes;
    }

}

realm.executeTransactionAsync(bgRealm -> {
           City city = bgRealm.where(City.class).equalTo("name", name).findFirst();
            if (city != null) {
                long a = city.getVotes(); // a is real value
                long k = city.votes;    //why k is 0 ?
                city.setVotes(k+1);
            }
        });

#### Version of Realm and tooling
Realm version(s): 5.3.1

Realm sync feature enabled: any

Android Studio version: any

Which Android version and device: any

**Comment by cmelchior** [comment]
This is a bug that should have been fixed if you upgrade to the latest version (5.4.2).
