### ISSUE TITLE
SSL handshake failed: certificate verify failed

### ISSUE THREAD

**Issue by pvtai** [realm/realm-java#6112]
Realm Studio in Ubuntu 16.04 after upgrade to 2.5.0/2.6.1 always show error as file attachment, in the log I see this line "ERROR: Connection[1]: SSL handshake failed: certificate verify failed" although I have tried  to reconnect many time, but it not pass this case. Please help to recheck, this error not occur in the previous version (2.4.5).
Thank you.
![realmstudio_ubuntu_ssl_error](https://user-images.githubusercontent.com/4888072/44245461-f5aa1980-a202-11e8-9b83-a862655da3ea.png)

**Comment by nhachicha** [comment]
Hi @pvtai thanks for the report. I think the `2.6` build was corrupted, @kraenhansen is investigating, in the meantime, you can revert to the `2.4.5` version.

**Comment by pvtai** [comment]
@nhachicha Thank you for your reply, but I cannot get the old version in your site

**Comment by nhachicha** [comment]
@pvtai I don't think there's a `2.4.5` published, you can download the `2.4.1` 

Mac: https://static.realm.io/downloads/realm-studio/Realm%20Studio-2.4.1.dmg
Linux: https://s3.amazonaws.com/static.realm.io/downloads/realm-studio/realm-studio-2.4.1-x86_64.AppImage

**Comment by nhachicha** [comment]
please follow the progress of the issue in https://github.com/realm/realm-studio/issues/898

**Comment by kraenhansen** [comment]
@pvtai a fix for this issue just got released as Realm Studio 2.6.2, please allow your version of Studio to automatically update or download the latest version from https://realm.io/products/realm-studio.
