### ISSUE TITLE
NoSuchFieldError (No field sharedRealm) when using R8 shrinker

### ISSUE THREAD

**Issue by chrisbln** [realm/realm-java#6114]
When I shrink the app with the new R8 shrinker then it will be thrown a NoSuchFieldError when getting a new Realm instance.

**gradle.properties**
```java
android.enableR8=true
```

**project build.gradle**
```java
dependencies {
  classpath 'io.realm:realm-gradle-plugin:5.4.2'
}
```

**app build.gradle**
```java
android {
    compileSdkVersion 28
    buildToolsVersion '28.0.0'

    defaultConfig {
        minSdkVersion 21
        targetSdkVersion 28
       // ....
    }
}
```

**stacktrace**
```java
java.lang.NoSuchFieldError: No field sharedRealm of type Lio/realm/internal/OsSharedRealm; in class Lio/realm/D; or its superclasses (declaration of 'io.realm.D' appears in base.apk)
        at io.realm.D.<init>(Realm.java:166)
        at io.realm.D.a(Realm.java:449)
        at io.realm.F.b(RealmCache.java:342)
        at io.realm.F.a(RealmCache.java:282)
        at io.realm.D.c(Realm.java:378)
        at com.moviebase.d.b.D.a(RealmExt.kt:17)
```

**Comment by Zhuinden** [comment]
Kinda looks like `io.realm.*` was completely not kept by R8, hmm

**Comment by cmelchior** [comment]
I tried to reproduce using our `GridViewExample` https://github.com/realm/realm-java/blob/master/examples/gridViewExample/build.gradle, but it seems to work fine if you enable R8 in `gradle.properties`. Can you create a sample project that reproduces the problem?

**Comment by chrisbln** [comment]
@cmelchior Thanks! It's good to know. I will check what is wrong with my project configuration.
