### ISSUE TITLE
Change primary key from long to string -> not work query (@LinkingObjects)

### ISSUE THREAD

**Issue by lmdic** [realm/realm-java#6117]
In my android project.

REALM_VERSION = '4.1.0'

```
public class Merchant extends RealmObject {
    @PrimaryKey
    private long id;
    private String name;
    private Category category;
    private RealmList<Product> products = new RealmList<>();

   public static final String PRODUCTS = "products";
}

public class Product extends RealmObject {
    @PrimaryKey
    private long id;
    private String name;
    private Date purchased_date;

    @LinkingObjects(Merchant.PRODUCTS)
    private final RealmResults<Merchant> merchants = null;

}

public class Category extends RealmObject {
    @PrimaryKey
    private long id;
    private String name;
    private Date updatedAt = new Date();

}

```
and here query:
get filtered products (only with specific `category.id`):

```
public static RealmResults<Product> getProducts(Realm realm, Bundle filter, String sortByFieldName) {
       RealmQuery<Product> realmQuery = realm.where(Product.class);
       realmQuery = realmQuery.equalTo(fieldName, fieldValue);
       return realmQuery.findAllSorted(sortByFieldName, Sort.DESCENDING);    
}
```

 fieldName = `merchants.category.id`
 fieldValue = `9`

and it's work fine. It's return filter produts (only with specific `category.id)`.
Nice.

But if I add new String field `uniqueId` and set is as primary key on Product like this:

```
public class Product extends RealmObject {
    @PrimaryKey
    private String uniqueId;
    private long id;
    private String name;
    private Date purchased_date;

    @LinkingObjects(Merchant.PRODUCTS)
    private final RealmResults<Merchant> merchants = null;
}
```

the query not work correct. It's return incorrect result. The query always return all products (not filtered).
Why?

**Comment by cmelchior** [comment]
Hi @lmdic 
Adding a different primary key shouldn't make any difference, but it isn't clear to me how your query look after adding the new primary key? If you are still querying on `id` and not `uniqueId` is there a chance that the values in the old `id` field are wrong?

**Comment by cmelchior** [comment]
Outdated so closing. If this is still a problem please re-open and provide a sample project demonstrating the issue so we can debug it.
