### ISSUE TITLE
Null exception object not getting created

### ISSUE THREAD

**Issue by debjitk** [realm/realm-java#6119]
I have a two models like:

```
class ModelA extends RealmObject {
  ...
}

class ModelB extends RealmObject {
  ...
  private RealmList<ModelA> list;
  ...

  public ModelB() {
    list = new RealmList<ModelA>();
  }
}
```
But the list member is not getting created and i am getting null exception when trying to access the list.

PS: I have noticed many times that if i create an object in another thread and immediatly query it on another thread i get null object.

Why is it so ? Do i have to call refresh all the time ?

When i am debugging i am not the null error because the database might be getting enough time to refresh or sync with the data storage.

What is really happening here ?

**Comment by debjitk** [comment]
@cmelchior The code is pretty much what I described.

I have two classes as shown below (names obfuscated):

`

public class MyModelA extends RealmObject {

    @PrimaryKey
    private long id;

   // ...

    @LinkingObjects("items")
    private final RealmResults<MyModelB> parents = null;

    /**
     * ctor
     */
    public MyModelA() {
    }
}


public class MyModelB extends RealmObject {

    @PrimaryKey
    private long id;

    private RealmList<MyModelA> items;

    /**
     * ctor
     */
    public MyModelB() {
        this.items = new RealmList<>();
    }

    /**
     * ctor
     *
     * @param id
     */
    public AlbumPhotos(long id) {
        this.id = id;
        this.items = new RealmList<>();
    }

`


On Fragment A, say i am creating an object of MyModelB with id '1' and inserting into realm. **Upon success I am loading Fragment B and I am getting a null exception when i am querying like the following:

realm.where(MyModelB.class).equalTo("id", 1).findFirst().gettems().sort("field", Sort.DESCENDING);

But, if i don't immediatly open Fagment B and do something like ...

**Upon success I am updating the list on Fragment A and then when i click on the newly created item and open Fragment B i am not getting any exception as if "_Realm is taking some time to fsync the transaction to storage which I understand technically sounds insane_".

**Comment by Zhuinden** [comment]
> Realm::refresh() is also not helping.

If that is true, then the object is not yet inserted when you are calling `refresh()`.

**Comment by cmelchior** [comment]
Closing due to no response. We really need a sample project demonstrating the issue before we can speculate what exactly the issue is.
