### ISSUE TITLE
SSL handshake failed - certificate verify failed.

### ISSUE THREAD

**Issue by alokomkar** [realm/realm-java#6122]
#### Goal

> We are trying to setup production SSL certificate on Android - currently we have received SSL certificated and have put it under ssl_staging.pem file under assets folder of the project.

Realm - android version - 4.3.4

#### Expected Results

> We expect the connection to go through post cerificate verification successfully allowing us to perform read and write operations on Realm database.

#### Actual Results

>  We are facing issues in verification of the certificate.

#### Steps & Code to Reproduce

> Current configuration :

#### Code Sample

```java

val user = SyncUser.currentUser()
var serverEndPoint = Constants.SERVER_URL + realmEndPoint
val adminId : String ?= NineBxApplication.getPreferences().adminId
if( !adminId.isNullOrEmpty() ) {
    serverEndPoint = Constants.SERVER_ADDRESS + adminId + "/" + realmEndPoint
}
val config = SyncConfiguration.Builder(user, serverEndPoint)
        .trustedRootCA(com.ninebx.BuildConfig.SSL)
        .waitForInitialRemoteData()
        .build()
Realm.getInstanceAsync(config, callback)

```

#### Version of Realm and tooling
Realm version(s): 4.3.4

Realm sync feature enabled: yes

Android Studio version: 3.1

Which Android version and device: Any

```
Error stacktrace :
REALM_SYNC: Connection[1]: SSL handshake failed: certificate verify failed
REALM_JAVA: Session Error[realms://stageapp.ninebx.com:443/54927a3c59d294f2e983f04938e951bd/Users]: SSL_SERVER_CERT_REJECTED(117)
                                                        SSL server certificate rejected
```
Update : We are using certificate signed by CA Let's encrypt

```java
val config = SyncConfiguration.Builder(user, serverEndPoint)
            //.trustedRootCA(com.ninebx.BuildConfig.SSL)
            .disableSSLVerification()
            .waitForInitialRemoteData()
            .build()
```
Disabling the SSL verification works, however we still see the warnings in stacktrace.

**Comment by cmelchior** [comment]
Hmm, interesting. We do have integration tests that verifies that the SSL functionality should work, so I'm not 100% what could be wrong here.

Have you tried installing the certificate directly in Android? Then you should be able to test if the certificate works without setting the the rootCA in the app.

**Comment by alokomkar** [comment]
Here are some more details which might help : 

The Realm Object Server on staging is 2.0.22.
The Realm Object Server installed on new staging server via Realm's .deb package is 1.8.3-83.

We haven't tried installing the certificate directly in Android, we have tried having the certificate file available locally as a .pem file.

The .pem file contains single signature we received from our server team. 

Format :
-----BEGIN CERTIFICATE----- 
(Primary SSL certificate: your_domain_name.crt) 
-----END CERTIFICATE----- 

We have also tried extracting the certificate from the website (https://stageapp.ninebx.com/) directly and having it in a .cert file in the project's assets folder.

**Comment by nhachicha** [comment]
@alokomkar, as described in the [documentation](https://github.com/realm/realm-java/blob/master/realm/realm-library/src/objectServer/java/io/realm/SyncConfiguration.java#L900) the PEM file, should include also the entire chain (root CA you trust and any intermediate authority [example](https://github.com/realm/realm-java/blob/master/realm/realm-library/src/syncIntegrationTest/assets/trusted_ca.pem))

**Comment by alokomkar** [comment]
We have included all the certificates in the .pem file, however it still is causing the same issue.

**Comment by cmelchior** [comment]
Outdated so closing. Our SSL implementation has undergone changes since this issue was opened. So If this is a still a problem with the latest 5.9.1, please re-open.

**Comment by VincentAuguin** [comment]
Hi, i'm facing the same issue here.

Realm-java version : 10.10.1
Android version: 7.0 (API 24)

I'm using an emulator behind my company VPN. They have their own CA certifiates which re-sign all SSL certificates.

First I've faced the following issue

`NETWORK_IO_EXCEPTION(realm::app::CustomError:1000): javax.net.ssl.SSLHandshakeException: java.security.cert.CertPathValidatorException: Trust anchor for certification path not found.`

And this makes sense since the CA certificate is not trusted. So I resolved that by installing my company CA certificates in the Android Trustore and defined the network security configuration in the Manifest with this xml:

```xml
<?xml version="1.0" encoding="utf-8"?>
<network-security-config>
    <debug-overrides>
        <trust-anchors>
            <certificates src="user" />
        </trust-anchors>
    </debug-overrides>
    <base-config>
        <trust-anchors>
            <certificates src="system" />
        </trust-anchors>
    </base-config>
</network-security-config>
```

Now Realm is handshaking correctly with the server but when Realm tries to Sync, it fails with another SSL certificate validation error:

```
D/REALM_SYNC: WebSocket::Websocket()
D/REALM_SYNC: Resolving 'ws.eu-west-1.aws.realm.mongodb.com:443'
D/REALM_SYNC: Connecting to endpoint '52.16.113.157:443' (1/1)
I/REALM_SYNC: Connected to endpoint '52.16.113.157:443' (from '10.0.2.15:55714')
D/REALM_SYNC: Verifying server SSL certificate using root certificates, host name = ws.eu-west-1.aws.realm.mongodb.com, server port = 443, certificate =
    -----BEGIN CERTIFICATE-----
    // public certificate encoded in Base 64
    -----END CERTIFICATE-----
I/REALM_SYNC: Verifying server SSL certificate using 155 root certificates
E/REALM_SYNC: The server certificate was not signed by any root certificate
E/REALM_SYNC: server SSL certificate rejected using root certificates, host name = ws.eu-west-1.aws.realm.mongodb.com, server port = 443
E/REALM_SYNC: Connection[1]: SSL handshake failed: wrong signature length
I/REALM_SYNC: Connection[1]: Connection closed due to error
W/REALM_JAVA: Unknown error code: 'openssl:67702903'
E/REALM_JAVA: Session Error[wss://realm.mongodb.com/]: UNKNOWN(openssl:67702903): wrong signature length
D/REALM_SYNC: Connection[1]: Allowing reconnection in 765 milliseconds
```
And it loops like this without throwing any `java.lang.Exception`.

I'm confused because my CA certificate is well detected by Realm client but when the sync is trying to connect openSSL fails (does it read CA certificates from Android User Trustore?).

Have you any leads on the subject ?

Of course I can work around this issue by using a real device connected on a free-VPN network; but still I would like to make this work since it *should* work.
