### ISSUE TITLE
Invalid query: field '@count' not found in class 'LSUser'

### ISSUE THREAD

**Issue by pvtai** [realm/realm-java#6128]
#### Goal

> What do you want to achieve?
I have 2 RealmObject class as below:
1. LSUser.java
```
public class LSUser extends RealmObject {
    @PrimaryKey
    @Required
    private String userId;
    @Required
    private String username;
    @Required
    private String displayName;
}
```

2. LSConversation.java
```
public class LSConversation extends RealmObject {
    @PrimaryKey
    @Required
    private String conversationId;
    @Required
    private String displayName;
    private RealmList<LSUser> users;
}
```
And I have created the query:
```
Realm realm = Realm.getDefaultInstance();
realm.executeTransactionAsync(bgRealm -> {
	LSConversation lsConversations = bgRealm.where(LSConversation.class)
		.equalTo("users.@count", 1)
		.findFirst()
}
```

#### Expected Results

> I want to count LSUser inside RealmList users inside LSConversation and return LSConversation successfully.

#### Actual Results

> Invalid query: field '@count' not found in class 'LSUser'.
>  E.g. full stack trace with exception

#### Steps & Code to Reproduce

> Describe your current debugging efforts.

#### Code Sample

```java

> Your code here. Bigger samples should ideally be as separate Android Studio project, 
> in gists/repositories or privately at help@realm.io)

```

#### Version of Realm and tooling
Realm version(s): 
implementation 'io.realm:android-adapters:3.0.0'
classpath "io.realm:realm-gradle-plugin:5.4.2"
Realm sync feature enabled: yes

Android Studio version: 3.1.4

Which Android version and device: Moto G 5.1.1

**Comment by cmelchior** [comment]
Aggregate functions are unfortunately not supported in Java yet. See #1598
