### ISSUE TITLE
Loading time is too long

### ISSUE THREAD

**Issue by debjitk** [realm/realm-java#6132]
I have about 60000 realm objects stored. when i am making a query to findAll sorted by an indexed column it is taking over 4-5 seconds for the query to return. Since realm does lazy loading i don't understand why the delay. Though on a high end android with lots of memory and processor cores the load time is acceptable.

**Comment by cmelchior** [comment]
It still needs to prepare the query result, so it is ready. With that amount of data, I would suggest using an async query instead using `findAllAsync()`

**Comment by debjitk** [comment]
Forgot to mention. I am using async query.

On 29-Aug-2018, at 1:17 AM, Christian Melchior <notifications@github.com<mailto:notifications@github.com>> wrote:


It still needs to prepare the query result, so it is ready. With that amount of data, I would suggest using an async query instead using findAllAsync()

**Comment by Zhuinden** [comment]
You also shouldn't run UI thread transactions because that makes async query run sync.

**Comment by cmelchior** [comment]
Depending on the query it could also be related to the change notification calculation. Especially if you have circular dependencies in your model graph. I do not know if that is the case? If it is you can most likely speed things up by using `@LinkingObjects` instead of forward references.
