### ISSUE TITLE
Realm Java 5.4.1 crashes at buildtime when using Android Gradle Plugin 2.3.1

### ISSUE THREAD

**Issue by roniahmad** [realm/realm-java#6133]
#### Goal

> I'm new in Realm. I tried to use Realm plugin version 5.4.1. When I tried to syn gradle dependencies, it's successful but got error when tried to build my project. I tried snapshoot version as explained here 

#### Expected Results

> ?

#### Actual Results

>  
Error:Execution failed for task ':app:transformClassesWithRealmTransformerForNormalDebug'.
> com.android.build.gradle.BaseExtension.getDefaultConfig()Lcom/android/build/gradle/internal/dsl/DefaultConfig;

#### Steps & Code to Reproduce

> Create a new project and add realm version 5.4.1 plugin
in my project gradle config

buildscript {
    
    repositories {
        google()
        jcenter()
        maven {
            url 'http://oss.jfrog.org/artifactory/oss-snapshot-local'
        }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:2.3.1'
        classpath "io.realm:realm-gradle-plugin:5.4.1"
//        classpath "io.realm:realm-gradle-plugin:5.5.0-SNAPSHOT"
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

in my app module gradle

apply plugin: 'com.android.application'
apply plugin: 'realm-android'

#### Code Sample

```java

> Your code here. Bigger samples should ideally be as separate Android Studio project, 
> in gists/repositories or privately at help@realm.io)

```

#### Version of Realm and tooling
Realm version(s):  5.4.1

Realm sync feature enabled: no

Android Studio version: 3..0.1

Which Android version and device: ?

**Comment by Zhuinden** [comment]
Any particular reason why your Android build tools are 2.3.1 and not something like, `classpath 'com.android.tools.build:gradle:3.1.3'`?

**Comment by roniahmad** [comment]
I have old project using Android build tools version 2.3.1.  I tried to upgrade to newer 3.0.0 version but got many errors. So I decided to stick with 2.3.1 version at the moment.
There is no particular reason.

Any way I just  use realm plugin version 4.2.0 and build successfully.

**Comment by cmelchior** [comment]
Hmm, seems we have a bug in our Plugin. We do strive to be backward compatible.

**Comment by dacaoyuan** [comment]
implementation 'io.realm:realm-android-library:3.4.0'

**Comment by Zhuinden** [comment]
dude you don't have to downgrade to 3.4.0 because of this

**Comment by obaidjatoi** [comment]
Any Solution ??

**Comment by Zhuinden** [comment]
You can try to do what the Realm-Android plugin does, by hand, so that you don't need to rely on a gradle plugin to do it for you.

See https://realm.io/docs/java/latest/#how-do-i-customize-dependecies-defined-by-the-realm-gradle-plugin

**Comment by obaidjatoi** [comment]
Thanks , but i need java settings, it is for kotlin.

**Comment by cmelchior** [comment]
```
buildscript {
    ext.realm_version = '5.9.1'
    repositories {
        jcenter()
        mavenCentral()
    }
    dependencies {
        classpath "io.realm:realm-transformer:$realm_version"
    }
}

apply plugin: 'com.android.application'

import io.realm.transformer.RealmTransformer
android.registerTransform(new RealmTransformer(project))

dependencies {
  api "io.realm:realm-annotations:$realm_version"
  api "io.realm:realm-android-library:$realm_version"
  annotationProcessor "io.realm:realm-annotations-processor:$realm_version"
}
```

**Comment by obaidjatoi** [comment]
Already done but faced this in gradle

Cannot resolve symbol RealmTransformer

**Comment by Zhuinden** [comment]
You need to do Gradle Sync and remove `apply plugin: 'realm-android'` if you do this approach.

**Comment by obaidjatoi** [comment]
Already done as you guided in app level gradle but not luck.

Had error mentioned below and also Cannot resolve symbol RealmTransformer

Error:Could not find io.realm:realm-transformer:5.9.1.
Searched in the following locations:
    file:/Applications/Android Studio 2.app/Contents/gradle/m2repository/io/realm/realm-transformer/5.9.1/realm-transformer-5.9.1.pom
    file:/Applications/Android Studio 2.app/Contents/gradle/m2repository/io/realm/realm-transformer/5.9.1/realm-transformer-5.9.1.jar
    https://maven.fabric.io/public/io/realm/realm-transformer/5.9.1/realm-transformer-5.9.1.pom
    https://maven.fabric.io/public/io/realm/realm-transformer/5.9.1/realm-transformer-5.9.1.jar
    https://oss.sonatype.org/content/repositories/releases/io/realm/realm-transformer/5.9.1/realm-transformer-5.9.1.pom
    https://oss.sonatype.org/content/repositories/releases/io/realm/realm-transformer/5.9.1/realm-transformer-5.9.1.jar
Required by:
    project :app


this is my app level gradle

buildscript {
    ext.realm_version = '5.9.1'
    repositories {
        maven { url 'https://maven.fabric.io/public' }
        maven { url "https://oss.sonatype.org/content/repositories/releases" }
    }

    dependencies {
        classpath 'io.fabric.tools:gradle:1.+'
        classpath "io.realm:realm-transformer:$realm_version"
    }
}

import io.realm.transformer.RealmTransformer
android.registerTransform(new RealmTransformer(project))

   compile "io.realm:realm-annotations:$realm_version"
    compile "io.realm:realm-android-library:$realm_version"
    annotationProcessor "io.realm:realm-annotations-processor:$realm_version"

**Comment by cmelchior** [comment]
You need `jcenter()` in your `repositories` block

**Comment by obaidjatoi** [comment]
this is already present in project level gradle.

repositories {
        jcenter()
        maven {
            url 'https://maven.google.com/'
            name 'Google'
        }
    }

**Comment by obaidjatoi** [comment]
Gradle Verison : 4.1
Android Plugin Version : 2.3.2

**Comment by obaidjatoi** [comment]
Should i use any other version ? i need to integrate realm asap in my working project please guide me.. Thanks in advance :)

**Comment by cmelchior** [comment]
You need `jcenter` in both the `buildscript` and normal `repositories`  block.

**Comment by Zhuinden** [comment]
Is 5.9.1 release? I thought the latest out was 5.9.0

**Comment by cmelchior** [comment]
Yes, there was some issues with getting the release out correctly, but the latest should be 5.9.1

**Comment by Zhuinden** [comment]
Your documentatino at https://realm.io/docs/java/latest/  does not reflect this. 🤔

**Comment by cmelchior** [comment]
Hmm, you are right. Seems the automatic merge between `releases` and `master` is broken. Thanks 👍

**Comment by obaidjatoi** [comment]
Sir with 5.9.0
I am getting same error

Error:Execution failed for task ':app:transformClassesWithRealmTransformerForWhatsupDebug'.
> com.android.build.gradle.BaseExtension.getDefaultConfig()Lcom/android/build/gradle/internal/dsl/DefaultConfig;

after adding `jcenter` in both the `buildscript` and normal `repositories` block.

still getting this Cannot resolve symbol RealmTransformer in graddle file in red color.....

**Comment by cmelchior** [comment]
Yeah, that looks related to what this issue is about. Unfortunately, your best bet right now is upgrading to Build Tools 3.0+.

**Comment by obaidjatoi** [comment]
Can you please tell me on which Gradle Verison and Android Plugin Version (minimum ) should be updated to get it working ??

**Comment by cmelchior** [comment]
Android Plugin 3.0 and whatever Gradle version it complains about needing, but if you can upgrade to 3.0 you should be able to to the latest which is 3.3.0 I believe.

**Comment by obaidjatoi** [comment]
Thanks

**Comment by cmelchior** [comment]
This could point to the fact that the minimum version of the build gradle tools we support is higher than we think. We should investigate this and document it.
