### ISSUE TITLE
kotlin+ module. cause error

### ISSUE THREAD

**Issue by swepthong** [realm/realm-java#6134]
There are ModuleExample(java) and kotlinExample.   ,but  have no. kotlin+ module example

can you supply  kotlin+ module example

I write kotlin+ module project follow.  ModuleExample(java) , cause error:

Could not find io.realm.***ModuleMediator

**Comment by Zhuinden** [comment]
Defining `@RealmModule` classes shouldn't cause problems whether Java or Kotlin
