### ISSUE TITLE
Unable to open a realm at path '/data/data/com.android.android/files/e_android.realm.lock': open() failed: Too many open files

### ISSUE THREAD

**Issue by gelbertgel** [realm/realm-java#6140]
`My realm version : 5.4.1`

I used realm in main thread by `RealmManager` and used in realm thread by `RealmThreadExecutor`. 

I get this error when trying to use it concurrently. Do I make a mistake in the realm configuration file or is it somewhere else?

error log:

> Fatal Exception: io.realm.exceptions.RealmFileException Unable to open
> a realm at path
> '/data/data/com.android.android/files/e_android.realm.lock': open()
> failed: Too many open files.
> (open("/data/data/com.android.android/files/a.realm.lock") failed: Too
> many open files)
> (/data/data/com.android.android/files/e_android.realm.lock) in
> /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp
> line 101 io.realm.internal.OsSharedRealm.nativeGetSharedRealm
> (OsSharedRealm.java) io.realm.internal.OsSharedRealm.
> (OsSharedRealm.java:171) io.realm.internal.OsSharedRealm.getInstance
> (OsSharedRealm.java:241) io.realm.BaseRealm. (BaseRealm.java:134)
> io.realm.BaseRealm. (BaseRealm.java:103) io.realm.Realm.
> (Realm.java:164) io.realm.Realm.createInstance (Realm.java:449)
> io.realm.RealmCache.doCreateRealmOrGetFromCache (RealmCache.java:342)
> io.realm.RealmCache.createRealmOrGetFromCache (RealmCache.java:282)
> io.realm.Realm.getDefaultInstance (Realm.java:357)
> com.android.android.dao.RealmManager.open (RealmManager.java:17)
> com.android.android.dao.management.RealmThreadExecutor$ParallelExecutor.beforeExecute
> (RealmThreadExecutor.java:60)
> java.util.concurrent.ThreadPoolExecutor.runWorker
> (ThreadPoolExecutor.java:1109) java.lang.Thread.run (Thread.java:841)

RealmManager:

    public class RealmManager {
    
        private final ThreadLocal<Realm> localRealms = new ThreadLocal<>();
    
        public RealmManager() {
            checkDefaultConfiguration();
        }
    
        public Realm open() {
    
            Realm realm = Realm.getDefaultInstance();
    
            if (!checkRealm(localRealms.get())) {
                localRealms.set(realm);
            }
    
            realm.refresh();
    
            return realm;
        }
    
        public Realm getLocalInstance() {
    
            Realm realm = localRealms.get();
    
            if (!checkRealm(realm)) {
                realm = open();
            }
    
            realm.refresh();
    
            return realm;
        }
    
        public void close(Realm realm) {
    
            if (!checkRealm(realm)) {
                return;
            }
    
            realm.close();
            controlLocalInstanceCount();
        }
    
        public void close() {
    
            Realm realm = localRealms.get();
            close(realm);
        }
    
        private static void checkDefaultConfiguration() {
    
            if (Realm.getDefaultConfiguration() == null) {
                new RealmEncryptionHelper().setDefaultConfiguration();
            }
        }
    
        public boolean checkRealm(Realm realm) {
            return realm != null && !realm.isClosed();
        }
    
        private void controlLocalInstanceCount() {
    
            // noinspection ConstantConditions
            int localInstanceCount = Realm.getLocalInstanceCount(Realm.getDefaultConfiguration());
            // noinspection ConstantConditions
    //        int globalInstanceCount = Realm.getGlobalInstanceCount(Realm.getDefaultConfiguration());
    
            // noinspection ConstantConditions
            if (localInstanceCount <= 0) {
                localRealms.set(null);
            }
        }
    
    
    }

RealmThreadExecutor:

    public class RealmThreadExecutor {
    
        private static String TAG = RealmThreadExecutor.class.getSimpleName();
    
        private static final BlockingQueue<Runnable> sPoolWorkQueue = new LinkedBlockingQueue<>();
        /**
         * An {@link Executor} that can be used to execute tasks in parallel.
         */
        private static ThreadPoolExecutor threadPoolExecutor;
    
        public void addRealmRunnable(RealmRunnable realmRunnable) {
    
            if (sPoolWorkQueue.size() == 0) {
                getPoolExecutor().execute(realmRunnable);
            } else {
                sPoolWorkQueue.add(realmRunnable);
            }
        }
    
        private static ThreadPoolExecutor getPoolExecutor() {
    
            if (threadPoolExecutor == null) {
                threadPoolExecutor = new ParallelExecutor();
            }
            return threadPoolExecutor;
        }
    
        private static class ParallelExecutor extends ThreadPoolExecutor {
    
            private RealmManager realmManager;
    
            private ParallelExecutor() {
                super(1, 1, 0L, TimeUnit.MILLISECONDS, sPoolWorkQueue, new BackgroundThreadFactory());
                realmManager = new RealmManager();
            }
    
            @Override
            protected void beforeExecute(Thread thread, Runnable runnable) {
                super.beforeExecute(thread, runnable);
    
                Realm realm = realmManager.open();
    
                RealmRunnable realmRunnable = (RealmRunnable) runnable;
                realmRunnable.setRealm(realm);
                realmRunnable.setThread(thread);
            }
    
            @Override
            protected void afterExecute(Runnable runnable, Throwable throwable) {
                super.afterExecute(runnable, throwable);
    
                RealmRunnable realmRunnable = (RealmRunnable) runnable;
                Realm realm = realmRunnable.getRealm();
                realmManager.close(realm);
    
                Thread thread = realmRunnable.getThread();
                thread.interrupt();
    
                scheduleNext();
            }
    
            private synchronized void scheduleNext() {
                if (sPoolWorkQueue.size() != 0) {
                    getPoolExecutor().execute(sPoolWorkQueue.poll());
                }
            }
    
        }
    
        private static class BackgroundThreadFactory implements ThreadFactory {
    
            @Override
            public Thread newThread(@NonNull Runnable runnable) {
                Thread thread = new Thread(runnable);
                thread.setName("realmPoolThread");
                thread.setPriority(Process.THREAD_PRIORITY_BACKGROUND);
    
                return thread;
            }
        }

defaultConfiguration : 

    public class RealmEncryptionHelper {
    
        private static final String ENCRYPTION_FILE_PREFIX = "e_";
    
        public void setDefaultConfiguration() {
    
            String DEFAULT_REALM_NAME = "a.realm";
    
            Realm.init(MyApplication.getContext());
    
            RealmConfiguration.Builder realmConfigurationBuilder = new RealmConfiguration.Builder()
                    .name(DEFAULT_REALM_NAME)
                    .schemaVersion(Constants.realmVersion)
                    .migration(new Migration());
    
            Realm.init(MyApplication.getContext());
            RealmConfiguration unencryptedConfig = realmConfigurationBuilder.build();
    
            RealmConfiguration encryptedConfig = new RealmConfiguration.Builder()
                    .name(ENCRYPTION_FILE_PREFIX + unencryptedConfig.getRealmFileName())
                    .schemaVersion(Constants.realmVersion) 
                    .migration(new Migration())
                    .encryptionKey(new RealmCreateKey().get())
                    .build();
    
            migrationIfNeeded(unencryptedConfig, encryptedConfig);
            Realm.setDefaultConfiguration(encryptedConfig);
        }
    
        private void migrationIfNeeded(RealmConfiguration unencryptedConfig, RealmConfiguration encryptedConfig) {
            File unencryptedFile = new File(unencryptedConfig.getPath());
            File encryptedFile = new File(encryptedConfig.getPath());
    
            Realm unencryptedRealm = null;
            if (!encryptedFile.exists() && unencryptedFile.exists()) {
                try {
                    unencryptedRealm = Realm.getInstance(unencryptedConfig);
                    unencryptedRealm.writeEncryptedCopyTo(encryptedFile, encryptedConfig.getEncryptionKey());
                } catch (Exception e) {
                    Mylog.printStackTrace("RealmEncryptionHelper migrationIfNeeded error", e);
                } finally {
                    if (unencryptedRealm != null) {
                        unencryptedRealm.close();
                    }
                }
            }
        }
    }

**Comment by cmelchior** [comment]
Realm uses file descriptors when opened on different threads, so my guess is that you are opening too many Realms somehow and not closing them. Your code does seem to have logic that should close the Realm, but my guess is that there is a bug in there somewhere.

**Comment by cmelchior** [comment]
That should work out of the box, but if you have too many threads running it might be a problem. This is also why the internal ThreadPools in Realm have a limit of 100

**Comment by gelbertgel** [comment]
Thank you. My configuration file is truth?

**Comment by Zhuinden** [comment]
I don't know what that means?

**Comment by gelbertgel** [comment]
from RealmEncryptionHelper : 

is it true or upstream code true?

   ```
 public void setConfiguration() {

        String DEFAULT_REALM_NAME = "a.realm";

        Realm.init(MyApplication.getContext());

        RealmConfiguration encryptedConfig = new RealmConfiguration.Builder()
                .name(ENCRYPTION_FILE_PREFIX + DEFAULT_REALM_NAME)
                .schemaVersion(Constants.realmVersion) 
                .migration(new Migration())
                .encryptionKey(new RealmCreateKey().get())
                .build();

        Realm.setDefaultConfiguration(encryptedConfig);
    }
```

**Comment by cmelchior** [comment]
If you mean that the code is correct, then yes, it appear so.

**Comment by gelbertgel** [comment]
which one? above `RealmEncryptionHelper setDefaultConfiguration` or `setConfiguration` method?

**Comment by Zhuinden** [comment]
Your threads die too fast. This thing isn't even related.

**Comment by gelbertgel** [comment]
ok I increase keep alive time. do I need to do something else?

**Comment by Zhuinden** [comment]
Test if it helped :D

**Comment by gelbertgel** [comment]
I've already tested but release version's phones encounter :( . Thanks for your helps.
