### ISSUE TITLE
@RealmClass, @RealmField value name 

### ISSUE THREAD

**Issue by mlykotom** [realm/realm-java#6145]
#### Goal

I would like to be able to write `@RealmClass("name_of_the_class")` or `@RealmField("name_of_field")` instead of  `@RealmClass(name="name_of_the_class")` or `@RealmField(name="name_of_field")` which is unnecesarilly verbose I think.

#### Expected Results

The annotations classes should use `value()` for specifying name of the class/field.
The same concept use e.g. libraries parsing from JSON (e.g. GSON's `@SerializedName`)

#### Actual Results

Annotation classes use method `name()` and therefore it must be specified when using the annotations.

#### Version of Realm and tooling
Realm version: 5.5.0

Realm sync feature enabled: no

Android Studio version: 3.1.4

**Comment by cmelchior** [comment]
Yes, that looks mostly like something we overlooked when designing the API. Making the explicit names the default parameter seems reasonable to me.
