### ISSUE TITLE
Android outOfMemoryException

### ISSUE THREAD

**Issue by shinbc** [realm/realm-java#6147]
Hello everyone. I have a problem with inserting a lot of objects into realm file. I have default realm file with >70k objects (450 mb - size of file). When I download new realm file via firebase, I must copy 140k objects (150 mb - size of new file), I catch OutOfMemoryException. I tried all methods - copyToRealm, insert. And this error catches only for devices with heap size < 128 mb

**Comment by Zhuinden** [comment]
You're probably creating a new object instead of resetting the current object and using `insertOrUpdate` on that object.

See https://stackoverflow.com/a/39385985/2413303

**Comment by shinbc** [comment]
I do the same operation. InsertOrUpdate inside async transaction. As I said this error appears only on devices which have heap size < 128 mb, other devices haven't this problem

**Comment by cmelchior** [comment]
I assume the above solution solved your issue. If not, feel free to re-open the issue.
