### ISSUE TITLE
Assertion Failed - OsSharedRealm$SchemaChangedCallback

### ISSUE THREAD

**Issue by bmunkholm** [realm/realm-java#6155]
@finnschiermer commented on [Thu May 03 2018](https://github.com/realm/realm-object-store/issues/651)

@ianpward commented on [Thu May 03 2018](https://github.com/realm/realm-core-private/issues/143)

Freshdesk Ticket ID: <a href='https://support.realm.io/helpdesk/tickets/572' target='_blank'>572</a> <br/> Freshdesk Ticket Agent: Unassigned<br/>Freshdesk Ticket Agent Email: Unavailable<br/>Ticket Priority: Low<br/>Freshdesk Ticket Description:<div>
<span></span>My app crashed when starting , here is the log. </div>
<div><br></div>
<div>Thanks~</div>
<div><br></div>
<div>========================================================================================</div>
<div>05-03 14:51:50.056 30727-30727/? E/REALM: /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/jni_util/java_class.cpp:50: [realm-core-5.4.0] Assertion failed: cls with (class_name) =  ["io/realm/internal/OsSharedRealm$SchemaChangedCallback"]<br>                                          IMPORTANT: if you see this error, please send this log to help@realm.io.<br>05-03 14:51:50.056 30727-30727/? A/libc: Fatal signal 6 (SIGABRT), code -6 in tid 30727 (com.huicent.ns)<br>                                         <br>                                         [ 05-03 14:51:50.056   415:  415 W/         ]<br>                                         debuggerd: handling request: pid=30727 uid=10542 gid=10542 tid=30727<br>05-03 14:51:50.126 30746-30746/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***<br>05-03 14:51:50.126 30746-30746/? A/DEBUG: Build fingerprint: 'HUAWEI/SLA-AL00/HWSLA-Q:7.0/HUAWEISLA-AL00/C00B191:user/release-keys'<br>05-03 14:51:50.126 30746-30746/? A/DEBUG: Revision: '0'<br>05-03 14:51:50.126 30746-30746/? A/DEBUG: ABI: 'arm'<br>05-03 14:51:50.126 30746-30746/? A/DEBUG: pid: 30727, tid: 30727, name: com.huicent.ns  &gt;&gt;&gt; com.huicent.ns &lt;&lt;&lt;<br>05-03 14:51:50.126 30746-30746/? A/DEBUG: signal 6 (SIGABRT), code -6 (SI_TKILL), fault addr --------<br>05-03 14:51:50.126 30746-30746/? A/DEBUG:     r0 00000000  r1 00007807  r2 00000006  r3 00000008<br>05-03 14:51:50.126 30746-30746/? A/DEBUG:     r4 b651e58c  r5 00000006  r6 b651e534  r7 0000010c<br>05-03 14:51:50.126 30746-30746/? A/DEBUG:     r8 00000032  r9 9900c7e0  sl aa5766e8  fp aa5766f0<br>05-03 14:51:50.126 30746-30746/? A/DEBUG:     ip 00000054  sp bec8da20  lr b5124887  pc b51270e4  cpsr 200f0010<br>05-03 14:51:50.134 30746-30746/? A/DEBUG: backtrace:<br>05-03 14:51:50.134 30746-30746/? A/DEBUG:     #00 pc 0004a0e4  /system/lib/libc.so (tgkill+12)<br>05-03 14:51:50.134 30746-30746/? A/DEBUG:     #01 pc 00047883  /system/lib/libc.so (pthread_kill+34)<br>05-03 14:51:50.134 30746-30746/? A/DEBUG:     #02 pc 0001d525  /system/lib/libc.so (raise+10)<br>05-03 14:51:50.134 30746-30746/? A/DEBUG:     #03 pc 00019071  /system/lib/libc.so (__libc_android_abort+34)<br>05-03 14:51:50.134 30746-30746/? A/DEBUG:     #04 pc 000170d8  /system/lib/libc.so (abort+4)<br>05-03 14:51:50.134 30746-30746/? A/DEBUG:     #05 pc 00140fbb  /data/app/com.huicent.ns-1/lib/arm/librealm-jni.so<br>05-03 14:51:50.134 30746-30746/? A/DEBUG:     #06 pc 00140fe7  /data/app/com.huicent.ns-1/lib/arm/librealm-jni.so<br>05-03 14:51:50.134 30746-30746/? A/DEBUG:     #07 pc 001410ad  /data/app/com.huicent.ns-1/lib/arm/librealm-jni.so<br>05-03 14:51:50.134 30746-30746/? A/DEBUG:     #08 pc 000690a5  /data/app/com.huicent.ns-1/lib/arm/librealm-jni.so<br>05-03 14:51:50.134 30746-30746/? A/DEBUG:     #09 pc 000690bb  /data/app/com.huicent.ns-1/lib/arm/librealm-jni.so<br>05-03 14:51:50.134 30746-30746/? A/DEBUG:     #10 pc 00064ccf  /data/app/com.huicent.ns-1/lib/arm/librealm-jni.so<br>05-03 14:51:50.134 30746-30746/? A/DEBUG:     #11 pc 00064d5d  /data/app/com.huicent.ns-1/lib/arm/librealm-jni.so<br>05-03 14:51:50.134 30746-30746/? A/DEBUG:     #12 pc 00064e1f  /data/app/com.huicent.ns-1/lib/arm/librealm-jni.so (JNI_OnLoad+42)<br>05-03 14:51:50.134 30746-30746/? A/DEBUG:     #13 pc 00239b51  /system/lib/libart.so (_ZN3art9JavaVMExt17LoadNativeLibraryEP7_JNIEnvRKNSt3__112basic_stringIcNS3_11char_traitsIcEENS3_9allocatorIcEEEEP8_jobjectP8_jstringPS9_+1844)<br>05-03 14:51:50.134 30746-30746/? A/DEBUG:     #14 pc 00003173  /system/lib/libopenjdkjvm.so (JVM_NativeLoad+178)<br>05-03 14:51:50.134 30746-30746/? A/DEBUG:     #15 pc 71002045  /data/dalvik-cache/arm/system@framework@boot.oat (offset 0x5fa000)<br>
</div>
<div><br></div>
<div><br></div>
<div><br></div>
<hr style="WIDTH: 210px; HEIGHT: 1px" align="left">
<div><span><div style="MARGIN: 10px; FONT-FAMILY: verdana; FONT-SIZE: 10pt"><div>wugj@redapplenet.com</div></div></span></div>

<br>

 <br/>

---

@tgoyne commented on [Thu May 03 2018](https://github.com/realm/realm-object-store/issues/651#issuecomment-386350188)

This is a realm-java thing.

**Comment by cmelchior** [comment]
Outdated, so closing.
