### ISSUE TITLE
invalid long

### ISSUE THREAD

**Issue by morteza-moradi** [realm/realm-java#6163]
> Hello  when i  insert data to realm  i get this error : 
>**invalid long (packagename) ObjectName @(number)**
> Error is like : 
>invalid long: "com.test.WordModel@78b7709"
>Invalid long: "com.test.WordModel@2eeb7ac5"
> **realm version 5.4.1**

> My ObjectModel : 

  **public class WordModel extends RealmObject
 {**

    @PrimaryKey
    private long id;

    public String mainword;
    public long getId() {
        return id;
    }
    public void setId(long id) {
        this.id = id;
    }
    public String getMainword() {
        return mainword;
    }
    public void setMainword(String mainword) {
        this.mainword = mainword;
    }}

> And This is my code for Insert Data: 

    WordModel data = new WordModel();
    data.setId(1);
    data.setMainWord("hello");

        realm.executeTransactionAsync(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {
                WordModel word= realm.createObject(WordModel.class,data);

            }
        }, new Realm.Transaction.OnSuccess() {
            @Override
            public void onSuccess() {
                Toast.makeText(context, "Succesfully added", Toast.LENGTH_SHORT).show();
            }
        }, new Realm.Transaction.OnError() {
            @Override
            public void onError(Throwable error) {
                Toast.makeText(context, error.getMessage().toString(), Toast.LENGTH_SHORT).show();

            }

        });

**Every Thing is Like Realm documentation. so Why i got this Error ??**

**Comment by Zhuinden** [comment]
> WordModel word= realm.createObject(WordModel.class,data);

realm.createObject(clazz, ***primaryKeyValue***).
