### ISSUE TITLE
Unrecoverable error. mmap() failed: Out of memory size: 1879048192 offset: 0 in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101

### ISSUE THREAD

**Issue by eduxavier** [realm/realm-java#6165]
#### Error

> Unrecoverable error. mmap() failed: Out of memory size: 1879048192 offset: 0 in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101

#### Context

> The application was used for the entire day. The user did save some records. Then the App reached 1,78 GB. After some research I did compact the Realm during the startup. The code below is what I have used:

```  .compactOnLaunch(new CompactOnLaunchCallback()
                    {
                        @Override
                        public boolean shouldCompact(long totalBytes, long usedBytes)
                        {
                            Log.write("totalBytes... " + totalBytes + " usedBytes " + usedBytes);
                            return true;
                        }
                    })
```
I've got "totalBytes... 73728 usedBytes 13424 which doesn't sound abnormal.
Application has 35,48 MB
Data 1,75 GB

#### Actual Results

>  RealmError
Unrecoverable error. mmap() failed: Out of memory size: 1879048192 offset: 0 in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101
io.realm.internal.OsSharedRealm in nativeGetSharedRealm
io.realm.internal.OsSharedRealm in <init> at line 171
io.realm.internal.OsSharedRealm in getInstance at line 241
io.realm.internal.OsSharedRealm in getInstance at line 231
io.realm.RealmCache in doCreateRealmOrGetFromCache at line 319
io.realm.RealmCache in createRealmOrGetFromCache at line 282
io.realm.Realm in getDefaultInstance at line 357

#### Steps & Code to Reproduce

> I really don't know. It sundenly stopped at the user's device.

#### Code Sample
Anywhere calling  getDefaultInstance does't that.

#### Version of Realm and tooling
Realm version(s): 5.4.0

Realm sync feature enabled: set to default.

Android Studio version: 3.1.14

Which Android version and device: Android 5.1.1 Sumsung SM-T285M

**Comment by eduxavier** [comment]
Hi @Zhuinden 
Everywhere in the App I use realm.close() I don't use the stament anywher try(Realm realm = Realm.getDefaultInstance()) but I make sure the realm close is called.

But in fact this problem happens during the app startup when I first call Realm.getDefaultInstance()

**Comment by cmelchior** [comment]
Realms should only reach that size if you are somehow pinning versions. See https://realm.io/docs/java/latest/#faq-large-realm-file-size

After this, if it is still an issue please re-open the issue.
