### ISSUE TITLE
Kotlin use GSON Serialize endless loop

### ISSUE THREAD

**Issue by Kandom** [realm/realm-java#6169]
Code:
```
open class Person : RealmObject() {
    var age: Int = 0
    var name: String = ""
}


class PersonSerializer : JsonSerializer<Person> {
    override fun serialize(src: Person, typeOfSrc: Type, context: JsonSerializationContext): JsonElement {
        val jsonObject = JsonObject()
        jsonObject.addProperty("name", src.name)
        jsonObject.addProperty("age", src.age)
        return jsonObject
    }
}


        val realm = Realm.getDefaultInstance()
        val person = realm.where(Person::class.java).findFirst()
        val gson = GsonBuilder()
                .setExclusionStrategies(object : ExclusionStrategy {
                    override fun shouldSkipField(f: FieldAttributes): Boolean {
                        return f.declaringClass == RealmObject::class.java
                    }

                    override fun shouldSkipClass(clazz: Class<*>): Boolean {
                        return false
                    }
                })
                .registerTypeAdapter(Person::class.java, PersonSerializer())
                .create()

        val personJSON = gson.toJson(person)
        Log.d("MainActivity", "$personJSON")
        realm.close()
```
It cause an endless loop. But if I change to
val personJSON = gson.toJson(realm.copyFromRealm(person))

The entity serialized fine. I just translate the realm GSON demo from java to Kotlin with the official document https://gist.github.com/cmelchior/ddac8efd018123a1e53a

Some body can help?

#### Version of Realm and tooling
Realm version(s): 5.4.1

Realm sync feature enabled: NO

Android Studio version: 3.4.1

Which Android version and device: compileSdkVersion 27

**Comment by cmelchior** [comment]
@Kandom What do you mean it causes an endless loop? 

But you need to use `copyFromRealm()` anyway, since GSON uses reflection to read field values, and that will not work on managed Realm objects.

**Comment by Kandom** [comment]
@cmelchior Thanks for your help, I got your idea and I read Kotlin-Realm-Extensions source code, it use copyFromRealm() method too.  
Will fastjson work on managed Realm objects? Thanks

**Comment by Zhuinden** [comment]
Keep in mind that `Kotlin-Realm-Extensions` is not an official Realm library

**Comment by Kandom** [comment]
@Zhuinden Thanks, I'll keep in mind
