### ISSUE TITLE
Run realm on Bazel project

### ISSUE THREAD

**Issue by Kadanza** [realm/realm-java#6173]
I use Bazel instead Gradle.
I have android Bazel project. I want use Realm in this project. But Realm requires plugin for Gradle and  Bazel does not have such plugin! I can't auto generate realm-classes

https://docs.bazel.build/versions/master/bazel-overview.html
https://github.com/bazelbuild/bazel

I want to work with Realm on Bazel Android Project

**Comment by cmelchior** [comment]
@Kadanza Have you tried looking at https://realm.io/docs/java/latest/#how-do-i-customize-dependecies-defined-by-the-realm-gradle-plugin 

This describes how to setup Realm without using the Gradle plugin

**Comment by Morfly** [comment]
It looks like the Realm documentation was recently updated and the page above is not available anymore.

I'm curious if it's still possible to set up without the Gradle plugin. If so, could you please share the link with the documentation about it? Thank you!

**Comment by rorbech** [comment]
I don't know how you would apply the gradle plugin to generate the realm classes, but here is the content of the old section of applying the dependencies manually.:

> Realm uses a Gradle plugin because it makes it easier to setup a larger number of dependencies, but it unfortunately also makes it a bit harder to customize, e.g. if you want to ignore some transitive dependencies.
> 
> If you want to customize Realm beyond what is exposed by the plugin, you can manually setup all the dependencies and ignore the Gradle plugin. How to do this for Kotlin projects is shown below:
> 
> *Standard approach when using the gradle plugin:*
> 
> ```gradle
> buildscript {
>     ext.kotlin_version = '1.2.41'
>     repositories {
>         jcenter()
>         mavenCentral()
>     }
>     dependencies {
>         classpath "io.realm:realm-gradle-plugin:<%= render_version %>"
>         classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
>     }
> }
> 
> apply plugin: 'com.android.application'
> apply plugin: 'kotlin-android'
> apply plugin: 'kotlin-kapt'
> apply plugin: 'realm-android'
> ```
> 
> *Manual setup:*
> 
> ```gradle
> buildscript {
>     ext.kotlin_version = '1.2.41'
>     ext.realm_version = '<%= render_version %>'
>     repositories {
>         jcenter()
>         mavenCentral()
>     }
>     dependencies {
>         classpath "io.realm:realm-transformer:$realm_version"
>         classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:$kotlin_version"
>     }
> }
> 
> apply plugin: 'com.android.application'
> apply plugin: 'kotlin-android'
> apply plugin: 'kotlin-kapt'
> 
> import io.realm.transformer.RealmTransformer
> android.registerTransform(new RealmTransformer(project))
> 
> dependencies {
>   api "io.realm:realm-annotations:$realm_version"
>   api "io.realm:realm-android-library:$realm_version"
>   api "io.realm:realm-android-kotlin-extensions:$realm_version"
>   kapt "io.realm:realm-annotations-processor:$realm_version"
> }
> ```
> 
> If you are using the Realm Object Server, `realm-android-kotlin-extensions` and `realm-android-library` needs to be suffixed with `-object-server` so they become: `realm-android-kotlin-extensions-object-server` and `realm-android-library-object-server`.
