### ISSUE TITLE
isNull not working on annotated linked objects

### ISSUE THREAD

**Issue by shahsurajk** [realm/realm-java#6176]
#### Goal

Make query with a backlinked object (annotated with `@LinkingObjects`)

#### Expected Results

> Query should work 

#### Actual Results

 Crash with the following exception: 
> java.lang.IllegalArgumentException: Illegal Argument: LinkingObject from field dog is not nullable.
        at io.realm.internal.TableQuery.nativeIsNull(Native Method)

#### Steps & Code to Reproduce

Make a query to a linked object: 
`RealmQuery<Dog> query = realm.where(Dog.class).isNull("linkedPerson");` 

Tried on 3.5.0 and 5.5.0, check [detailed comment](https://github.com/realm/realm-java/issues/4996#issuecomment-423459210)

The same works with a forward linking object (non-annotated) linking object, but crashes for backlinked object (one with annotation in the model and object type `RealmResults`). 

Similar issue was pointed out in #4996 but was marked closed with a link to #4856, but #4856 was for forward link (direct nested link) which was fixed in 3.5.0 but not #4996. 

#### Code Sample

Model:
```
public class Dog extends RealmObject {

	private Long ate_at;

	public Long getAte_at() {
		return ate_at;
	}

	public void setAte_at(Long ate_at) {
		this.ate_at = ate_at;
	}

	@LinkingObjects("dog")
	public final RealmResults<Person> linkedPerson= null;
}
```

#### Version of Realm and tooling
Realm version(s): 3.5.0 and 5.5.0

Realm sync feature enabled: no

Android Studio version: 3.1.3

Which Android version and device: Nexus 6P, stock, 8.1.0, ARMv8x64

**Comment by Zhuinden** [comment]
Well it is not nullable, Linking Objects is a collection. Have you tried using `.isEmpty()` instead?

**Comment by shahsurajk** [comment]
Wow, it does work with `isEmpty` tried on both my production use case and the test use case. Thank you very much for your quick reply, i tried searching a lot of places for this, in and out of issues for realm for hours. But how does it work with `isEmpty`? does it do this:  `RealmResults` object is created but it has no results, hence `isEmpty`?

**Comment by Zhuinden** [comment]
Yeah, pretty much. It's a non-null collection from the DB's perspective (linking objects of a managed object through non-reflective access is never null.)
