### ISSUE TITLE
java.lang.IllegalStateException: Object is no longer valid to operate on. Was it deleted by another thread?

### ISSUE THREAD

**Issue by shaunty21** [realm/realm-java#6181]
//Delete Item Function
   DatabaseManager.getInstance().deleteSymptomDatebyId(symptomsDbModels.get(position).getDatevalue(), symptomsDbModels.get(position).getId());
                symptomsDbModels.remove(position);
                notifyItemRemoved(position);
                notifyItemRangeChanged(position, symptomsDbModels.size());
                notifyDataSetChanged();
               
//Realm Query
   RealmResults<SymptomsDbModel> symptomsDbModel = realm.where(SymptomsDbModel.class).equalTo("datevalue", date).equalTo("id", id).findAll();

        realm.beginTransaction();
        symptomsDbModel.deleteFirstFromRealm();
        realm.commitTransaction();

**Comment by Zhuinden** [comment]
Use RealmChangeListener or [RealmRecyclerViewAdapter](https://github.com/realm/realm-android-adapters)

**Comment by cmelchior** [comment]
Duplicate of #6182
