### ISSUE TITLE
**Bug** In release with Realm

### ISSUE THREAD

**Issue by gerostam** [realm/realm-java#6187]
I am building a library and I am using Realm as the database. After Realm version 5.3.0 (i.e. 5.5.0) I cannot build a release version of my library and I receive the error:

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':osevensdk:transformClassesWithRealmTransformerForRelease'.
> com.android.build.gradle.BaseExtension.getDefaultConfig()Lcom/android/build/gradle/internal/dsl/DefaultConfig;

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 16.135 secs
Cause: com.android.build.gradle.BaseExtension.getDefaultConfig()Lcom/android/build/gradle/internal/dsl/DefaultConfig;
1:16:53 PM: Task execution finished 'uploadArchives'.

When I use Realm 5.3.0 everything works fine. Also obfuscation is enabled.
 
Please tell me a possible solution, because I cannot upgrade the Realm version.

Thanks in advance!

**Comment by cmelchior** [comment]
@gerostam Which version of Android Studio and the Android Build tools are you using?

**Comment by gerostam** [comment]
@cmelchior I am using Android Studio version 3.1.4, com.android.tools.build:gradle:3.1.4 and buildToolsVersion "27.0.3"

**Comment by gerostam** [comment]
@cmelchior I also used realm version 5.7.0 and the lastest Android Studio (3.2.0), build gradle 3.2.0 and and buildToolsVersion "28.0.3" and the result is the same. The problem arises when i run the command uploadArchives from gradle.

**Comment by cmelchior** [comment]
Does it only happen if you call `uploadArchieves`? What about `./gradlew clean assemble` ?

**Comment by gerostam** [comment]
The same!

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':osevensdk:transformClassesWithRealmTransformerForDebug'.
> com.android.build.gradle.BaseExtension.getDefaultConfig()Lcom/android/build/gradle/internal/dsl/DefaultConfig;

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

**Comment by cmelchior** [comment]
Ok, that was expected. It is just weird you are seeing this error with the Build Tools 3.1.4. It is a known issue on versions before 3: https://github.com/realm/realm-java/issues/6133, but Realm itself is using 3.1.4 and all our examples build fine in release mode with this.

Are you 100% sure you are using Build Tools 3.1.4?

**Comment by gerostam** [comment]
@cmelchior You are correct, my main Build tolls was below 3.14. I have not finished investigating the issue, because I have another problem with the gradle but i believe realm is ok as far as it is concerned.
