### ISSUE TITLE
issue on realm 5.7.0 for android API Added Partial Query not reflect on cloudRealm Each time - mostly after 5 minute

### ISSUE THREAD

**Issue by sshakilms** [realm/realm-java#6197]
#### Goal

> What do you want to achieve?

#### Expected Results

> ?

#### Actual Results

>  E.g. full stack trace with exception

#### Steps & Code to Reproduce

realmCollectionOrder listener not working or Live notification not happening

#### Code Sample

```java
 public void attachRealmAsync(String id) {
db.where(MyEntity.class)
                    .equalTo(DataContract.MyEntry.COLUMN_Id, id)
                    .findAllAsync().addChangeListener(, new OrderedRealmCollectionChangeListener<RealmResults<MyEntity>>() {
                    @Override
                    public void onChange(RealmResults<MyEntity> myEntity, OrderedCollectionChangeSet changeSet) {
                        Timber.d("Entity Synced"+myEntity.size());
                        realmSyncChat_db.refresh();
                    }
                });
        }
```

#### Version of Realm and tooling
Realm version(s): 5.7.0

Realm sync feature enabled: yes

Android Studio version: 3.1.4

**Comment by Zhuinden** [comment]
I assume it's because GC ate your RealmResults.

**Comment by sshakilms** [comment]
it means whenever i used GarbageCollection then i need to reattach RealmQuery Listener 
and how i can prevent from it.

**Comment by cmelchior** [comment]
See https://realm.io/docs/java/latest/#notifications

**Comment by cmelchior** [comment]
I assume the above solution solved your issue. If not, feel free to re-open the issue.
