### ISSUE TITLE
 io.realm.exceptions.RealmException: Could not find io.realm.MySchemaMediator

### ISSUE THREAD

**Issue by sshakilms** [realm/realm-java#6204]
#### Goal

> What do you want to achieve?

#### Expected Results

> ?

#### Actual Results

 Caused by: java.lang.ClassNotFoundException: io.realm.MySchemaMediator
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:324)
        at java.lang.Class.forName(Class.java:285)
        at io.realm.RealmConfiguration.getModuleMediator(RealmConfiguration.java:372)
        at io.realm.RealmConfiguration.createSchemaMediator(RealmConfiguration.java:351) 
        at io.realm.SyncConfiguration$Builder.build(SyncConfiguration.java:1166) 
        at com.XXX.database.util.RealmService.setRealmConfigInstance(RealmService.java:114) 
       
#### Steps & Code to Reproduce
after Upgrading Android Studio
[Android Studio 3.2
Build #AI-181.5540.7.32.5014246, built on September 18, 2018
JRE: 1.8.0_152-release-1136-b06 x86_64
JVM: OpenJDK 64-Bit Server VM by JetBrains s.r.o
macOS 10.13.6]
Getting Realm Schema Mediator Error

#### Code Sample

```java
realmSyncConfig = user.createConfiguration(REALM_URL)
                            .fullSynchronization()
                            .modules(new MySchema())
                            .schemaVersion(SCHEMA_VERSION)
                            .waitForInitialRemoteData()
                            .errorHandler((session, error) -> {
                                Timber.e("User error:%s", String.valueOf(session));
                                Timber.e("User error:%s", error.getErrorCode());
                            })
                            .build();

////Schema Code

@RealmModule(classes={
        MyEntity.class,
        SetEntity.class,
        UserEntity.class})
public class MySchema {

}

```

#### Version of Realm and tooling
Realm version(s): ?
5.7.0
Realm sync feature enabled: yes
Android Studio version: ?
3.2

**Comment by cmelchior** [comment]
Most likely it is a build cache problem. Have you tried doing a full rebuild?

**Comment by sshakilms** [comment]
> Most likely it is a build cache problem. Have you tried doing a full rebuild?

yes i Invalidate Android Studio Cache Build

**Comment by sshakilms** [comment]
code was working fine but after Update Android Studio and Kotlin it started giving error
I tried to clean cache and Project Clean and Rebuild but still it coming.

**Comment by Zhuinden** [comment]
Have you tried reverting Kotlin version?

**Comment by sshakilms** [comment]
not yet

**Comment by sshakilms** [comment]
> Have you tried reverting Kotlin version?

// last upgraded to ext.kotlin_version = '1.2.71'
//now Downgraded to version    ext.kotlin_version = '1.2.51' 
it is working now Thanks
