### ISSUE TITLE
Realm returns empty although is not 

### ISSUE THREAD

**Issue by mike91E16** [realm/realm-java#6205]
Realm version used: io.realm:realm-gradle-plugin:5.5.0
I have built an application that stores data using Realm database.
Periodically, a JSON backup file is created so the app, when uninstall and re-install, can restore old datas.

When i launch the app, it finds and read the JSON file, then writes rows in Realm.

    public static void restoreJSON() throws Exception{
            Log.d(TAGDOC,"Restore from JSON bkp [START]");
            File f = new File(Environment.getExternalStorageDirectory() + BuildConfig.JSON_BKP);

        if(!f.exists()){
            Log.d(TAGDOC,"Backup JSON file doesn't exist");
            return;
        }

        FileInputStream is = new FileInputStream(f);
        int size = is.available();
        byte[] buffer = new byte[size];
        is.read(buffer);
        is.close();
        String mResponse = new String(buffer);
        JSONArray allDocsArray = new JSONArray(mResponse);
        Log.d(TAGDOC,"Document array found, length: " + allDocsArray.length());
        Realm realm = Realm.getDefaultInstance();
        for(int i = 0; i < allDocsArray.length(); i++){
                realm.beginTransaction();
                JSONObject obj = allDocsArray.getJSONObject(i);
                JSONObject nodeObj = obj.has("mNode") ? obj.getJSONObject("mNode") : null;
                RealmDocumentNode node = nodeObj != null ? new RealmDocumentNode(nodeObj) : null;
                RealmDocument doc = new RealmDocument(obj,node);
                Log.d(TAGDOC,"Processing doc number " + doc.getID());
                realm.insertOrUpdate(doc);
                realm.commitTransaction();
        }
        List<RealmDocument> res = realm.where(RealmDocument.class)
                .sort("mReadedDate", Sort.ASCENDING)
                .equalTo("mUserID", Integer.parseInt(AppUtils.getCurrentUserID()))
                .findAll();
        Log.d(TAGDOC,"Documents found with query: " + res.size());
        realm.close();
        Log.d(TAGDOC,"Restore from JSON bkp [END]");
    }

It works well, Logcat display it:

    Restore from JSON bkp [START]
    Document array found, length: 5
    Processing doc number 1460
    Processing doc number 1459
    Processing doc number 1450
    Processing doc number 1444
    Processing doc number 1445
    Documents found with query: 5
    Restore from JSON bkp [END]

So, the login activity is closed and another activity that holds fragments is open.

In one of those, when i try to execute the same query used in the restore method, it return no results.

public List<RealmDocument> getFilesByUser(int userID){
	Realm realm = Realm.getDefaultInstance();
	realm.refresh();

	List<RealmDocument> res = realm.where(RealmDocument.class)
		.sort("mReadedDate", Sort.ASCENDING)
		.equalTo("mUserID", userID)
		.findAll();

	realm.close();

	return res;
    }

No error and exceptions in logcat.

Why does Realm returns empty? I checked if some instances are opened and not closed between the restore and the next query but there aren't.

**Comment by cmelchior** [comment]
That is hard to tell from the code you posted. E.g your 2nd query involves a `userID` so if something went wrong inserting that into Realm or you are querying on an ID that doesn't exists, then no results could be found.

Can you reproduce this is in a sample project?
