### ISSUE TITLE
Realm SyncConfic giving OTHER_ERROR(101)  OR OTHER_ERROR(101) 

### ISSUE THREAD

**Issue by sshakilms** [realm/realm-java#6208]
#### Goal
i want Sync Should not stop till app close its Chat App.
#### Expected Results

> ?

#### Actual Results

>  E.g. full stack trace with exception

#### Steps & Code to Reproduce

after Realm connection between 5 minutes to   10 minutes it produce 
BAD_ORIGIN_FILE_IDENT(110) Or OTHER_ERROR(101) 
what is error asking me to do reconnect SyncFile Or something else...
is it good practice if i maintain static app level Realm instance.

#### Code Sample

```java
     if (error.getErrorCode() == ErrorCode.CLIENT_RESET) {
            ClientResetRequiredError err = (ClientResetRequiredError) error;
            closeAllRealmInstance();
            err.executeClientReset(); // Manually do the reset
            err.getBackupFile(); // Reference to backed up file
        } else {
            // Handle other errors
            refereshSync();
        }
```

#### Version of Realm and tooling
Realm version(s): 5.7.0

Realm sync feature enabled: yes

Android Studio version: 3.2

Which Android version and device: any

**Comment by cmelchior** [comment]
I'm not exactly sure what you are asking. The code you posted is related to Client Reset, which can happen if you delete the Server side Realm while devices are still using it. 

When that happens, you should close all access to the local Realm file as it can no longer be synchronized. We provide the backup file in case you want to transfer data somewhere, possible to a new Realm created on the server.

**Comment by sshakilms** [comment]
> I'm not exactly sure what you are asking. The code you posted is related to Client Reset, which can happen if you delete the Server side Realm while devices are still using it.
> 
> When that happens, you should close all access to the local Realm file as it can no longer be synchronized. We provide the backup file in case you want to transfer data somewhere, possible to a new Realm created on the server.

i am using partial Realm Sync and after 5 to 10 minutes Sync will give me these errors
BAD_ORIGIN_FILE_IDENT(110) Or OTHER_ERROR(101) 
on any Sync error is it necessary to recreate all Realm Instance or Realm Listener or it automatically reconnect object and Listener

**Comment by cmelchior** [comment]
BAD_ORIGIN_FILE_IDENT should only happen if something really bad either happened to the local Realm file or the server Realm file. Are you manually deleting some of these files?

OTHER_ERROR could be a lot of things. You can get more information if you print the error to logcat by using `ObjectServerErrror.toString()`

**Comment by sshakilms** [comment]
> BAD_ORIGIN_FILE_IDENT should only happen if something really bad either happened to the local Realm file or the server Realm file. Are you manually deleting some of these files?
> 
> OTHER_ERROR could be a lot of things. You can get more information if you print the error to logcat by using `ObjectServerErrror.toString()`

on any Sync error is it necessary to recreate all Realm Instance or Realm Listener or it automatically reconnect object and Listener

**Comment by cmelchior** [comment]
It depends on the Sync error, so hard to tell. Many of them are not something a restart will fix but are configuration errors that need to be fixed.

**Comment by sshakilms** [comment]
> It depends on the Sync error, so hard to tell. Many of them are not something a restart will fix but are configuration errors that need to be fixed.
if Realm instance refresh on Error is it work (and i will reattach all Object Listener right after that )
Or Close Realm instance and Open again

**Comment by sshakilms** [comment]
> It depends on the Sync error, so hard to tell. Many of them are not something a restart will fix but are configuration errors that need to be fixed.

if Realm instance refresh on Error is it work (and i will reattach all Object Listener right after that )
Or Close Realm instance and Open again

**Comment by cmelchior** [comment]
In most cases, the easiest is to close the Realm and open it again before reattaching Object Listeners, but note that the two errors you posted probably will not be fixed by closing and reopening the Realm. Especially `BAD_ORIGIN_FILE_IDENT` is a quite severe error code meaning that someone is tampering with the underlying files.

**Comment by sshakilms** [comment]
it giving me : 
"RealmService: Config error:BAD_ORIGIN_FILE_IDENT(110)
Connection timed out"

**Comment by sshakilms** [comment]
REALM_SYNC: Connection[3]: Reading failed: Connection timed out 
just after that getting these error 
RealmService: Chat error:BAD_ORIGIN_FILE_IDENT(110)
    Connection timed out

**Comment by cmelchior** [comment]
Folding this into https://github.com/realm/realm-java/issues/6364
The real cause here is the error message "Connection timed out", i.e. some kind of network issue. The `BAD_ORIGIN_FILE_IDENT` is wrong due to the bug in #6364.
