### ISSUE TITLE
Realm init in application not recognised as valid realm in custom provider

### ISSUE THREAD

**Issue by TSG9876** [realm/realm-java#6213]
in Kotlin , Realm configuration defined in companion object with proper init and well defined configuration appeared as null object in any custom provider despite being properly setup in the Application class
 
 companion object {

        var config1: RealmConfiguration? = null
        var config2: RealmConfiguration? = null

    }

 override fun onCreate() {
    super.onCreate();
    Realm.init(this);
    config1 = RealmConfiguration.Builder()
       // config parameters
      .build();
    config2 =  RealmConfiguration.Builder()
       // config parameters
      .build();
  }

only way to get the realm configuration is to init  again and follow up with  the essential configuration declaration   at the  custom provider oncreate call ,could not understand why the companion object could not work to get the predefined realm configuration at the application class??

Realm-java version 5.7

**Comment by Zhuinden** [comment]
I think you're just running into the fact that `RealmConfiguration?` is nullable.

**Comment by Zhuinden** [comment]
You could define the RealmConfigs as `private` and create a `fun` that returns `config!!`.

**Comment by TSG9876** [comment]
In fact,there is nothing wrong with the nullable var,it is just funny that under content provider,a new instance of realm configuration must be obtained through the companion call whenever a realm is neeed. Realm config instance obtained through oncreate failed to persist

**Comment by cmelchior** [comment]
ContentProviders are initialized before the Application class, this might be the cause of the confusion?

**Comment by TSG9876** [comment]
Agreed,it is  just strange to realise that the whole android architecture being designed without  application class being the 1st startup point of initialization.
