### ISSUE TITLE
Update Data In Realm File With Realm Studio

### ISSUE THREAD

**Issue by morteza-moradi** [realm/realm-java#6227]
Hello 
**Is There Any Way To Update one or All Data In Realm File With Realm Studio with Query?**
Thanks.

**Comment by cmelchior** [comment]
Issue moved to [realm/realm-studio #965](https://github.com/realm/realm-studio/issues/965) via [**ZenHub**](https://www.zenhub.com/)

**Comment by cmelchior** [comment]
Hi @morteza-moradi This issue belongs in Realm Studio, so I moved it there.
