### ISSUE TITLE
Set Int Not Work!

### ISSUE THREAD

**Issue by morteza-moradi** [realm/realm-java#6230]
hello
this is my model:

 **public class WordModel extends RealmObject {**
    .....

    private int iddatabase;

    public int getIddatabase() {
        return iddatabase;
    }

    public void setIddatabase(int iddatabase) {
        this.iddatabase = iddatabase;
    }

   .....
   
**}**

when i want to create a model and set data like this ->

 **WordModel data= new WordModel();
                   ....
                    data.setIddatabase(1);**

after save data to realm
**All Data like string, long and etc currently saved inside realm file but  iddatabase is 0 while i set it 1**

**Comment by bmunkholm** [comment]
@morteza-moradi Please always use the template we provide for reporting issues.
Including providing a complete code example to reproduce your issue.
You can start with one of our examples to see how to do and check the differences to what you are doing, that will likely lead you to find your bug.
Thanks!

**Comment by Zhuinden** [comment]
```
WordModel data= new WordModel();
....
data.setIddatabase(1);
```

If you want the changes to affect the data you saved in Realm, then you need to use `realm.where(WordModel.class).equalTo("id", id).findFirst();` to get a managed object, and modify *that*.
