### ISSUE TITLE
"not part of the schema for this Realm" error for basic project with kotlin

### ISSUE THREAD

**Issue by trashc0de** [realm/realm-java#6233]
#### Goal
can't run a simple project with a simple model (2 fields).

#### Actual Results
when i try to save the model i get this error

io.realm.exceptions.RealmException: <MODEL> is not part of the schema for this Realm

when adding modules to realm configuration got this

 io.realm.exceptions.RealmException: Could not find io.realm.DefaultModuleMediator
       
#### Steps & Code to Reproduce
    class TestApplication : Application() {

    override fun onCreate() {
        super.onCreate()

        Realm.init(this)
        val realmConfig = RealmConfiguration.Builder()
                .name("test.realm")
                .schemaVersion(0)
                .build()
        Realm.setDefaultConfiguration(realmConfig)
    }
    }
 
    open class MyModel : RealmObject() {

    @PrimaryKey
    var mykey: String = ""
    var value: String? = null

    fun initWithModel(key: String, value: String): MyModel {
        this.mykey = key
        this.value = value

        return this
    }

    }

    class MainActivity : AppCompatActivity() {

    override fun onCreate(savedInstanceState: Bundle?) {
        super.onCreate(savedInstanceState)
        setContentView(R.layout.activity_main)

        val realm = Realm.getDefaultInstance()

        val model = MyModel().initWithModel("key1", "value1")

        realm.executeTransaction {
            it.copyToRealmOrUpdate(model)
        }

    }
    }

Android Project can be downloaded here https://www.dropbox.com/s/t67uonrvzagw6qu/realm_test.zip?dl=0

#### Version of Realm and tooling

Realm version(s): realm-gradle-plugin:5.7.0

Realm Sync feature enabled: No

Android Studio version: 3.2

Android Build Tools version: 28.0.3

Gradle version: 3.2.1

Which Android version and device(s): Huawei Nexus 6P Android 8.1 Api 27

**Comment by trashc0de** [comment]
actually it seems that adding 
"apply plugin: 'kotlin-kapt'"
fix the thing 

why so ?

**Comment by Zhuinden** [comment]
Because your models are in Kotlin, and for Java annotation processors to run over your Kotlin code, you have to apply `kotlin-kapt`.

Same thing you have to do if you use Dagger2 or anything else that uses annotation processing, tbh

**Comment by trashc0de** [comment]
yeah thanks, now i know it too. i'd like it to be more clear
