### ISSUE TITLE
App Bundle not able to find .so file

### ISSUE THREAD

**Issue by wbervoets** [realm/realm-java#6237]
#### Goal
Realm.init(context) initializes the Realm and does not crash the app

#### Actual Results
A crash occured on Google Nexus 5X device.

Caused by com.b.a.b: librealm-jni.so
       at com.getkeepsafe.relinker.ApkLibraryInstaller.sourceDirectories(Unknown Source)
       at com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal(Unknown Source)
       at com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary(Unknown Source)
       at com.getkeepsafe.relinker.ReLinker.loadLibrary(Unknown Source)
       at com.getkeepsafe.relinker.ReLinker.loadLibrary(Unknown Source)
       at io.realm.internal.RealmCore.loadLibrary(Unknown Source)
       at io.realm.Realm.createExpectedSchemaInfo(Unknown Source)

#### Steps & Code to Reproduce
- Call Realm.init(context) in the Android Application onCreate().
- On a LG Nexus 5x device (also see a crashreport from Emulator and Batmobile Defy but these are not important) 
- Our application is distributed as an Android App Bundle. Realm is the only native library we include.

#### Version of Realm and tooling
Realm version(s): 5.7.0

Realm Sync feature enabled: No

Android Studio version: 3.2.0

Android Build Tools version: 28.0.2

Gradle version: 4.6

Which Android version and device(s): LG Nexus 5X Android v5.0.2 / v5.1.1 / v6.0.1

I assume it happens because of the Android App Bundle, becasuse we didn not have this crash in the previous release where we had one APK with everything included

**Comment by cmelchior** [comment]
Hi @wbervoets do you have the exact stack trace? It seems that some parts of it was cut out from what you posted. Especially the exact error message?

Also have you access to the APK and are able to verify that the `.so` file is actually present in it?

**Comment by bukenov** [comment]
I have the same problem

**Comment by sumonlbbd** [comment]
I do also have the same problem. Are there any solution to this ? I am also getting a crash on green robot event bus..
Crash details is

Fatal Exception: java.lang.RuntimeException
Unable to start activity ComponentInfo{littleblackbook.com.littleblackbook.lbbdapp.lbb/littleblackbook.com.littleblackbook.lbbdapp.lbb.UI.UGCPlaceTypeActivity}: org.greenrobot.eventbus.EventBusException: Subscriber class littleblackbook.com.littleblackbook.lbbdapp.lbb.Fragments.UGCPlaceTypeFragment and its super classes have no public methods with the @Subscribe annotation

**Comment by Zhuinden** [comment]
@sumonlbbd it sounds like you are missing the Proguard rules for EventBus `@Subscribe` methods.

```
-keepattributes *Annotation*
-keepclassmembers class * {
    @org.greenrobot.eventbus.Subscribe <methods>;
}
-keep enum org.greenrobot.eventbus.ThreadMode { *; }
 
# Only required if you use AsyncExecutor
-keepclassmembers class * extends org.greenrobot.eventbus.util.ThrowableFailureEvent {
    <init>(java.lang.Throwable);
}
```

**Comment by sumonlbbd** [comment]
@Zhuinden -  I have already added all this stuffs in my Proguard file. This are all present.

**Comment by Zhuinden** [comment]
Then you are registering an Activity to the Bus that has no `@Subscribe` method.

I think I just used to catch this exception because "who cares", both on register and unregister.

**Comment by sumonlbbd** [comment]
@Zhuinden I have added that also. Have added  @Subscribe annotation at onEvent call .Are there any possible reasons for the same.

**Comment by oferDanon** [comment]
Hey @cmelchior , 
I'm also experiencing this crash when using AppBundle, any news on this? 
Thanks.

**Comment by cmelchior** [comment]
The underlying root cause is probably https://github.com/realm/realm-java/issues/5977, so I'll fold this issue into that one.
