### ISSUE TITLE
 Can not use realm query in thread or async task

### ISSUE THREAD

**Issue by morteza-moradi** [realm/realm-java#6238]
Hello
I have a realm database with 500k record
when i run a query the **UI** is block!
I just want to Run realm  query in thread or async task  to solve this problem but with any method i got errors like : 

**When i run query in Thread :** Caused by: java.lang.IllegalStateException: Realm access from incorrect thread. Realm objects can only be accessed on the thread they were created.

**When i run query in async task :**  Caused by: java.lang.IllegalStateException: Async query cannot be created on current thread. Realm cannot be automatically updated on a thread without a looper.

Please Help me How can I put realm query in thread please give me a example
Thanks

note: i define and init my realm in Application Class that extends Application and use it in serveral activity and freagment just in main fragment i need to search in 500k record , another activity and fragment do not need 500k search

**Comment by cmelchior** [comment]
Don't use an `AsyncTask`, use `findAllAsync()` instead of `findAll()` directly on the UI thread. Realm will automatically handle the threading then. Read more here: https://realm.io/docs/java/latest/#asynchronous-queries

**Comment by morteza-moradi** [comment]
sir when i use findAllAsync I Got Different Result !

**Comment by Zhuinden** [comment]
You also need to set it as a field variable and then use `results.addChangeListener((items) -> { /* now your query is fetched */`
