### ISSUE TITLE
Issue when using different packages

### ISSUE THREAD

**Issue by petersnoopy** [realm/realm-java#624]
If two RealmObjects are linked together using the many-to-many relation such as the following example:

```
public class Contact extends RealmObject {
    private RealmList<Email> emails;
 }
```

then the proxy class 'ContactProxy' can't find Contact.class if the RealmObjects are stored on different packages.

```
com.demo.myapplication.aaaa.Contact
com.demo.myapplication.bbbb.Email
```

**Comment by njovy** [comment]
Yes please make sure you mention this factor in document.
I started to migrate one project from sqlite with different sub packages in the model package. It took me some time to figure out this issue until I read issues on repo.
