### ISSUE TITLE
How check is any references to Realm object?

### ISSUE THREAD

**Issue by lmdic** [realm/realm-java#6250]
In my Android app I has realm object:

```
public class Product extends RealmObject {
    @PrimaryKey
    private long id;
    private String name;
    private float price;
}

```

Sometime I need to delete this object. But... I need delete it **ONLY** if no any references in Realm to this object.
So the question is: Can I check is any references to this object? Something like if c**ount of references = 0** then I can delete this object. Else I can't do it.
Is it possible in Realm?

**Comment by Zhuinden** [comment]
Have you tried to check the size of linking objects?

**Comment by lmdic** [comment]
> Have you tried to check the size of linking objects?

How I can do this?  Any example?

**Comment by cmelchior** [comment]
It is called Inverse Relationships. You can read more about it here: https://realm.io/docs/java/latest/#inverse-relationships

**Comment by lmdic** [comment]
I has 3 Pojos that has ref. to pojo **Product** 

Smt like this:


```
public class Profile extends RealmObject {
    @PrimaryKey
    private long id;
    private String name;
    private Product product;
}

public class User extends RealmObject {
    @PrimaryKey
    private long id;
    private String name;
    private Image image;
    private RealmList<Offer> offers;
}

public class Image extends RealmObject {
    @PrimaryKey
    private long id;
    private String name;
    private RealmList<Product> products;
}

public class Offer extends RealmObject {
    @PrimaryKey
    private long id;
    private Product product;
}
```

So before delete **Product**  I need to understand to has any reference to object product. 
So in my case: Is object Profile , Image,  Offer has references to Product.
So in Product I need smt like this:


```
public class Product extends RealmObject {
    @PrimaryKey
    private long id;
    private String name;
    private float price;

  @LinkingObjects("product")
  private final RealmResults<Profile> profiles;
  @LinkingObjects("products")
  private final RealmResults<Image> images;
  @LinkingObjects("product")
  private final RealmResults<Offer> offers;
}
```

So now I can create query to Realm that:
 Give me list of all **profiles** that contain this **product**
or
Give me list of all **images** that contain this **product**
or
Give me list of all **offers** that contain this **product**

Is I'm right?

**Comment by cmelchior** [comment]
Well, you don't need to create the query. That has already been done for you.

If you want to delete all objects that references you just need something like this:

```
realm.executeTransaction(r -> {
  Product product = getProduct();
  product.profiles.deleteAllFromRealm();
  product.images.deleteAllFromRealm();
  product.offers.deleteAllFromRealm();
  product.deleteFromRealm();
});


```

**Comment by lmdic** [comment]
> Well, you don't need to create the query. That has already been done for you.
> 
> If you want to delete all objects that references you just need something like this:
> 
> ```
> realm.executeTransaction(r -> {
>   Product product = getProduct();
>   product.profiles.deleteAllFromRealm();
>   product.images.deleteAllFromRealm();
>   product.offers.deleteAllFromRealm();
>   product.deleteFromRealm();
> });
> ```

No. I need next:
1. Has any references to **Product**?
2. If has than NOT delete **Product**
3. If not has any references than delete **Product**

How I can do this via  `@LinkingObjects`

**Comment by cmelchior** [comment]
Just check the size of `profiles`, `images` and `offers` if they are all `0` it means that nothing references it.
