### ISSUE TITLE
No previous value of object without primary key.

### ISSUE THREAD

**Issue by lmdic** [realm/realm-java#6252]
In my Android app I has pojos:

```
public class Merchant extends RealmObject {
    @PrimaryKey
    private long id;
    private Translated name;

}
public class Translated  extends RealmObject {
    private String locale;
    private String value;
}
```
As you can see the `Translated `has no primary key.

To add list of **merchants** to Realm I use the next method:

 ```
public static void updateMerchantList(final List<Merchant> incomingMerchantsList) {
        Realm realm = Realm.getDefaultInstance();
        try {
            realm.executeTransaction(new Realm.Transaction() {
                @Override
                public void execute(Realm realm) {                   
                    RealmList<Merchant> incomingMerchantsRealmList = new RealmList<>();
                    incomingMerchantsRealmList.addAll(incomingMerchantsList);
                    realm.copyToRealmOrUpdate(incomingMerchantsRealmList);
                }
            });
        } finally {
            realm.close();
        }
    }
```
As result in Realm success insert list of merchants.

Execute the next tests:

List of merchant consist from one Merchant:
**Tests#1:**

 ```
Merchant.id = 1;
 Translated.value = "Value_one"
```

After execute this test in Realm I has in table `Merchant `- one record **merchant** with `id = 1`. And one record `Translated.vale = "Value_one"` in table `Translated`.

Nice. It's correct.

Tests#2:

List of merchants consist from **two** merchants:

```
1.
 Merchant.id = 1
 Translated.value = "Value_one"

2.
 Merchant.id = 1
 Translated.value = "Value_second"
```

As you can see second **merchant** has same `id`, but different `Translated.value.`

As result in table `Merchant `I has **ONE** record in table `Merchant `with **id = 1**. And in the table `Translated ` has **TWO** records with value =  `"Value_second"`.
So now in table `Translated `has **NO** records with value `"Value_one"`.

Is it correct behavior?

**Comment by cmelchior** [comment]
Yes, this is the correct behavior. Without primary keys, we cannot assume anything about the `Translated` object being referenced, so we are just creating a new one, leaving the old one in the database.

Granted, it is a fairly common use case to want to delete these orphan objects and #1104 will enable that use case. Until that is implemented you can instead use linking objects to find and delete `Translated` objects that do not belong to anything. This can be done this way:


```
public class Translated  extends RealmObject {
    private String locale;
    private String value;
    @LinkingObjects("name")
    RealmResults<Merchant> merchants;
}


// Find an delete objects with no Merchant that reference them
realm.executeTransactionAsync(bgRealm -> {
  RealmResults<Translated> objects = bgRealm.where(Translated.class).findAll();
  for (int i = objects.size() - 1; i >=0; i--) {
    Translated obj = objects.get(i);
    if (obj.merchants.size() == 0) {
      obj.deleteFromRealm(); 
    }
  }      
});
```

**Comment by lmdic** [comment]
> Yes, this is the correct behavior. Without primary keys, we cannot assume anything about the `Translated` object being referenced, so we are just creating a new one, leaving the old one in the database.

Is Translated object with value `Translated.value = "Value_one"` is stay in Realm and need manually delete them. Or Realm autodelete it?
Because result of Test#2 show that `Translated.value = "Value_one"` is not exit anymore. I'm not delete them manually.
What is a correct way?

**Comment by cmelchior** [comment]
You need to manually delete it.

**Comment by lmdic** [comment]
> You need to manually delete it.

Alghorimt:
1. Get all local merchants from Realm
2. Iterate local merchant
3. If local merchant's name not exist in incoming list of merchant and no ref to them the delete it

Here code:

```
 public static void updateMerchantList(final List<Merchant> incomingMerchantsList) {
         Realm realm = Realm.getDefaultInstance();
        try {
            realm.executeTransaction(new Realm.Transaction() {
                @Override
                public void execute(Realm realm) {                
                    RealmResults<Merchant> localMerchantList = getMerchants(realm, new Bundle(), null);
                    for (int indexMerchant = localMerchantList.size() - 1; indexMerchant >= 0; indexMerchant--) {
                        Merchant currentLocalMerchant = localMerchantList.get(indexMerchant);
                        int findLocalMerchantIndex = incomingMerchantsList.indexOf(currentLocalMerchant);
                        if (findLocalMerchantIndex > -1) { // exist
                            Merchant findIncomingMerchant = incomingMerchantsList.get(findLocalMerchantIndex);
                            LocalizedString currentLocalMerchantName = currentLocalMerchant.getName();
                            LocalizedString findIncomingMerchantName = findIncomingMerchant.getName();
                            if (!EqualsUtil.areEqual(currentLocalMerchantName, findIncomingMerchantName)) {
                                currentLocalMerchant.setName(realm.copyToRealm(findIncomingMerchantName));
                                // delete (if no refs) currentLocalMerchantName
                                if (currentLocalMerchantName.getCountRefs() == 0) {
                                    currentLocalMerchantName.deleteFromRealm(); // not delete from Realm
                                }
                            }
                        }
                    } // end for localMerchantList            
                }
            });
        } finally {
            realm.close();
        }
    }
```

As result new value is insert to the Realm, but old value not delete from Realm. Method 

`currentLocalMerchantName.deleteFromRealm();`

not delete object `currentLocalMerchantName` from Realm.
