### ISSUE TITLE
Insertion of 3K elements with relationship is very slow (20sec)

### ISSUE THREAD

**Issue by ganfra** [realm/realm-java#6254]
#### Goal
I'm using realm to insert some elements with relationships. Here is the code

```
open class ChunkEntity(var prevToken: String? = null,
                       var nextToken: String? = null,
                       var events: RealmList<EventEntity> = RealmList()
) : RealmObject() {

    @LinkingObjects("chunks")
    val room: RealmResults<RoomEntity>? = null

    companion object
}
```

```
open class EventEntity(@PrimaryKey var eventId: String = "",
                       var type: String = "",
                       var content: String = "",
                       var prevContent: String? = null,
                       var stateKey: String? = null,
                       var originServerTs: Long? = null,
                       var sender: String? = null,
                       var age: Long? = 0
) : RealmObject() {

    companion object

    @LinkingObjects("events")
    val chunk: RealmResults<ChunkEntity>? = null

}
```

```
fun List<Event>.addManagedToChunk(realm: Realm, chunkEntity: ChunkEntity) {
    this.forEach { event ->
        if (event.eventId == null) {
            return@forEach
        }
        val eventEntity = EventEntity.where(realm, event.eventId).findFirst()
                          ?: realm.createObject(event.eventId)

        eventEntity.fillWith(event)
        if (!chunkEntity.events.contains(eventEntity)) {
            chunkEntity.events.add(eventEntity)
        }
    }
}
```

This for loop is included in one executeTransaction. 

#### Actual Results
The transaction takes really too much time... like 20sec... 
I use it elsewhere with insertOrUpdate and it's ok. But I can't do that here as I have a relationship to enrich.

#### Version of Realm and tooling

Realm version(s): 5.7.0

Realm Sync feature enabled: No

Android Studio version: ? 3.1.4

Which Android version and device(s): ? Nexus 5x on Android 7.1

Thanks guys

**Comment by cmelchior** [comment]
How are you measuring this? Note that transactions are blocking across all threads so if you have another transaction running it might impact your measurements.

But also, you are running 3000 queries from what I can tell with:  
```
val eventEntity = EventEntity.where(realm, event.eventId).findFirst()
                          ?: realm.createObject(event.eventId)
```

Followed by some sort list search which is O(n). That is going to take some time no matter what.

**Comment by ganfra** [comment]
I'm using measureMillis arround the execute transaction block.
Yes, I know transactions are blocking across all threads, but for the test I have made it in isolation.

Do you have any recommandation for not doing these queries if I want to avoid duplicate in the list ?

**Comment by cmelchior** [comment]
It doesn't right now as it only really works if the object has a primary key. We do use a short-cut in the `equals` method that only compare the actual entry in Realm instead of all fields, but it will still need to create a Java wrapper for each object it wants to compare.

**Comment by ganfra** [comment]
Ok thanks for your help, using query to check contains makes it way faster!
