### ISSUE TITLE
Failure when converting to UTF-8; error_code = 6;

### ISSUE THREAD

**Issue by Myeongwon-Kang** [realm/realm-java#6269]
#### Goal
Caused by java.lang.IllegalArgumentException: Illegal Argument: Failure when converting to UTF-8; error_code = 6;  0x004d 0x0075 0x0073 0x0075 0x0068 0x0020 0xd83d in /Users/Nabil/Dev/realm/master/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_Table.cpp line 837

And what is error code 6?

#### Actual Results
Caused by java.lang.IllegalArgumentException: Illegal Argument: Failure when converting to UTF-8; error_code = 6;  0x004c 0x0069 0x0074 0x0074 0x006c 0x0065 0x0020 0x0054 0x0069 0x006e 0x0079 0xd83d in /Users/Nabil/Dev/realm/master/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_Table.cpp line 837
       at io.realm.internal.Table.nativeSetString(Table.java)
       at io.realm.co.abcd_data_model_db_ContactRealmProxy.insertOrUpdate(co_abcd_data_model_db_ContactRealmProxy.java:905)
       at io.realm.DefaultRealmModuleMediator.insertOrUpdate(DefaultRealmModuleMediator.java:215)
       at io.realm.Realm.insertOrUpdate(Realm.java:1175)
#### Steps & Code to Reproduce
public void insertAll(List<Contact> contactList) {
        realm.beginTransaction();
        realm.insertOrUpdate(contactList);
        realm.commitTransaction();
    }

#### Version of Realm and tooling

Realm version(s): 5.3.1

Realm Sync feature enabled: Yes/No

Android Studio version: 3.2.1

Android Build Tools version: ? 28.0.3

Gradle version: ? 4.6

Which Android version and device(s): ? HUAWEI(TRT-L21A) os 8

**Comment by cmelchior** [comment]
It means that the String you are trying to save into Realm is not correct UTF-8. Where did it come from?

You can see the last character is `0xd83d`. This is part of what is called a surrogate pair (see https://en.wikipedia.org/wiki/UTF-16) and is not allowed to be by itself. Surrogate pairs are commonly used to encode emojis.

This can e.g. happen if you are doing String manipulation that isn't Unicode aware like using `String.substring()`.

**Comment by Myeongwon-Kang** [comment]
It happened when using Arabic address book.

I did not cut the string.

thanks.
