### ISSUE TITLE
How relam object communicate between background thread and UI thread

### ISSUE THREAD

**Issue by KingWu** [realm/realm-java#6291]
Currently, i use Realm for local storage. I find a strange bug.

I use the local data to render UI. At the same time, i request the server whether the local data is changed. Sometime the app throw null-pointer exception.

When upading UI, the realm object is locked until the rendering UI is finished? After finish the update, and then get the realm change?

In fact, how realm object communicate between background thread and UI thread?

**Comment by Zhuinden** [comment]
`RealmChangeListener` with `realmResults.addChangeListener(realmChangeListener);`.
