### ISSUE TITLE
io.realm.exceptions.RealmFileException(5.8.0)

### ISSUE THREAD

**Issue by scsfwgy** [realm/realm-java#6292]
#### Goal
Know why,To solve it！

#### Actual Results

**It all happened background,Using the duration:1~3s,then crash**

Directory at path '/data/data/com.tophold.xcfd/files/default.realm' does not exist. (open("/data/data/com.tophold.xcfd/files/default.realm") failed: No such file or directory) (/data/data/com.tophold.xcfd/files/default.realm) in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101

java.lang.RuntimeException:Unable to create application com.tophold.xcfd.TopHoldApplication: io.realm.exceptions.RealmFileException: Directory at path '/data/data/com.tophold.xcfd/files/default.realm' does not exist. (open("/data/data/com.tophold.xcfd/files/default.realm") failed: No such file or directory) (/data/data/com.tophold.xcfd/files/default.realm) in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101 Kind: NOT_FOUND.

#### Steps & Code to Reproduce

All happened at our  Analysis of the crash platform, can`t reproduce.

#### Version of Realm and tooling

Realm version(s): 5.4.1、5.8.0

Realm Sync feature enabled: Yes/No

Android Studio version: 3.2.1

Android Build Tools version:  3.2.1

Gradle version: gradle-4.6-all

Which Android version and device(s): 5.0~9.0...

**Comment by Zhuinden** [comment]
This can only happen if you delete an open Realm file by hand.

**Comment by cmelchior** [comment]
You can probably reproduce this by deleting the app data under settings while the app is running.

**Comment by scsfwgy** [comment]
thx,Is there a solution?

**Comment by cmelchior** [comment]
Depends on why it happened. If it was a user that did it, there isn't really anything you can do except trying to re-create the file or restart the app.

**Comment by scsfwgy** [comment]
Is Realm delete and create in not main thread?
If no,there is always this possibility: when I'm deleting or creating realm, I'm going to use it. 
Is there a way that I can listening to the delete and create successfully?

**Comment by Zhuinden** [comment]
Technically if you want to delete all items in a Realm file, you can use `Realm.deleteAll()` function instead of deleting the Realm file while it's open

**Comment by scsfwgy** [comment]
No,I mean when "deleteRealmIfMigrationNeeded", is here can listener the state? 
The crash log:
`Directory at path '/data/data/com.tophold.xcfd/files/default.realm' does not exist. ` may be “Realm.getDefaultInstance()” occur?

**Comment by cmelchior** [comment]
I'm not entirely sure what you mean. If you enabled `deleteRealmIfMigrationRequired` the file will be deleted, but also created again, so the error above shouldn't happen.

If you can provide a sample project where this error happens it will be much easier to help you.

**Comment by scsfwgy** [comment]
Hi, I have solved the problem.It‘s due to **multiprocess**. Thanks for your patiently answer this question! @cmelchior @Zhuinden
