### ISSUE TITLE
How to exclude a Realm model class from a specific Realm file in DB scheme?

### ISSUE THREAD

**Issue by Kolyall** [realm/realm-java#6303]
Realm version:
 

   ` classpath "io.realm:realm-gradle-plugin:5.8.0"`

I [found that][1] I should add modules to `io.realm.RealmConfiguration`. So I made this:
```
    RealmConfiguration.Builder builder = new RealmConfiguration.Builder()
                .deleteRealmIfMigrationNeeded()
                .schemaVersion(1)
                .encryptionKey(/*my encryption key*/)
                .name("pay_card.realm");
        
            builder.addModule(new RPayCardRealmModule());
        
        return Realm.getInstance(builder.build());
```
RPayCardRealmModule.class
```
    @RealmModule(library = true,classes = {
            RPayCard.class
    })
    public class RPayCardRealmModule {
    }
```
RPayCard.class
```
    @lombok.Getter
    @lombok.Setter
    @lombok.ToString(includeFieldNames = false)
    @lombok.Builder
    @lombok.AllArgsConstructor
    @lombok.NoArgsConstructor
    @lombok.EqualsAndHashCode(of = "id")
    public class RPayCard extends RealmObject {
        @io.realm.annotations.PrimaryKey
        @io.realm.annotations.Required
        String id;
    
        private String billNumber;
        private String cardNumber;
        private String cardExpirationDate;
        private String cardType;
        private String cardHolderName;
        private boolean selected;
    
    }
```

But when I look into the db file "pay_card.realm". 

It looks like that. Why other classes are added to db scheme? How to exclude them?
[![enter image description here][2]][2]

  [1]: https://stackoverflow.com/a/43615171/2425851
  [2]: https://i.stack.imgur.com/uQMfn.png

**Comment by Zhuinden** [comment]
You need to provide a `@RealmModule` to specify the classes to be used in the schema

**Comment by cmelchior** [comment]
Like @Zhuinden says. Classes already created will not be removed by setting a module. It will just restrict what is being created going forward. If you delete the Realm file you should only see the classes defined in the module.

**Comment by Kolyall** [comment]
@Zhuinden and @cmelchior thanks, resolved by changing `.addModule` to `.modules`

**Comment by Zhuinden** [comment]
Ah, that makes sense, because `Realm.getDefaultModule()` is added by default.
