### ISSUE TITLE
How disable autocheck update for Realm Studion

### ISSUE THREAD

**Issue by lmdic** [realm/realm-java#6305]
Every day when I start Realm studio (ver. 3.0.6) it's tell me about available new version. How I can disable autocheck for new version?

![image](https://user-images.githubusercontent.com/303539/48625982-5d663100-e9b9-11e8-80b7-8b8934c09c28.png)

**Comment by bmunkholm** [comment]
Issue moved to [realm/realm-studio #1014](https://github.com/realm/realm-studio/issues/1014) via [**ZenHub**](https://www.zenhub.com/)
