### ISSUE TITLE
Apache Cordova (phonegap) plugin

### ISSUE THREAD

**Issue by peta15** [realm/realm-java#631]
New feature request

It would be fantastic if there was a Apache Cordova (aka Phonegap) plugin for Realm.  Hybrid apps appear to be underserved by persistence (mostly they only have localStorage) so this would be a great opportunity for Realm.

**Comment by confile** [comment]
+1 that would be great!

**Comment by steffimueller** [comment]
+1

**Comment by komocode** [comment]
+1

**Comment by ataraxus** [comment]
+1

**Comment by davidpp** [comment]
+1

**Comment by jsolano** [comment]
+1

**Comment by shkkmo** [comment]
+1

**Comment by rleira** [comment]
+1

**Comment by alfredooo** [comment]
+1

**Comment by gpowork** [comment]
+1

**Comment by jeromelavigne** [comment]
+1

**Comment by manhhaiphp** [comment]
+1
+1
...
+1

**Comment by jeffpoulton** [comment]
+1

**Comment by tonholis** [comment]
+1

**Comment by krisanalfa** [comment]
+1

**Comment by iffifan** [comment]
+1

**Comment by aromka** [comment]
+1

**Comment by netrevisanto** [comment]
+1

**Comment by arastu** [comment]
+1

**Comment by treylon** [comment]
+1

**Comment by jasdeepsingh** [comment]
:+1:

**Comment by machei** [comment]
+1

**Comment by matthewford** [comment]
+1

**Comment by dalinaum** [comment]
:+1:

**Comment by timanglade** [comment]
You can now register for any eventual beta of Realm for JavaScript via this form: http://goo.gl/forms/ue2MtdCO4e

**Comment by kneth** [comment]
An unofficial plugin https://github.com/airamrguez/cordova-plugin-realm ("unofficial" as in "done by an awesome programmer not associated with Realm").

**Comment by clementetb** [comment]
Closing due inactivity. Please comment in case you get more information and the issue still persists
