### ISSUE TITLE
Allow model field name with different getter/setter

### ISSUE THREAD

**Issue by lukaspili** [realm/realm-java#633]
Hi, 
(When ?) Do you plan to allow a field name to have not the exact same name as its getter/setter ?
For instance, lot of people use hungarian notation in Android, with prefix "m" for field names.
I understand it is forbidden, but in my opinion this limitation is too strict.

In addition, the error related to that issue in 0.74 is an unclear Realm null pointer exception.

Lukasz

**Comment by cmelchior** [comment]
This is already covered by #909 and #908 so closing this as a duplicate.
