### ISSUE TITLE
io.realm.exceptions.RealmError: Unrecoverable error. Too many open files in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101

### ISSUE THREAD

**Issue by jkkey** [realm/realm-java#6357]
#### Actual Results

11-29 00:43:32.599  4558  4558 E AndroidRuntime: FATAL EXCEPTION: main
11-29 00:43:32.599  4558  4558 E AndroidRuntime: Process: com.aiwinn.jarvis.app.mix, PID: 4558
11-29 00:43:32.599  4558  4558 E AndroidRuntime: io.realm.exceptions.RealmError: Unrecoverable error. Too many open files in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101
11-29 00:43:32.599  4558  4558 E AndroidRuntime: 	at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
11-29 00:43:32.599  4558  4558 E AndroidRuntime: 	at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:171)
11-29 00:43:32.599  4558  4558 E AndroidRuntime: 	at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:241)
11-29 00:43:32.599  4558  4558 E AndroidRuntime: 	at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:231)
11-29 00:43:32.599  4558  4558 E AndroidRuntime: 	at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:319)
11-29 00:43:32.599  4558  4558 E AndroidRuntime: 	at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:282)
11-29 00:43:32.599  4558  4558 E AndroidRuntime: 	at io.realm.Realm.getInstance(Realm.java:364)
11-29 00:43:32.599  4558  4558 E AndroidRuntime: 	at com.aiwinn.jarvis.module.hostdb.HostRealmConfig.getDefault(HostRealmConfig.java:45)
11-29 00:43:32.599  4558  4558 E AndroidRuntime: 	at com.aiwinn.jarvis.module.hostdb.HostRealmImpl.queryVersionByName(HostRealmImpl.java:671)
11-29 00:43:32.599  4558  4558 E AndroidRuntime: 	at com.aiwinn.jarvis.module.hostdb.HostDbServices$LibVersion.queryByName(HostDbServices.java:478)
11-29 00:43:32.599  4558  4558 E AndroidRuntime: 	at com.aiwinn.jarvis.app.host.activity.HomeActivity.onResume(HomeActivity.java:384)
11-29 00:43:32.599  4558  4558 E AndroidRuntime: 	at android.app.Instrumentation.callActivityOnResume(Instrumentation.java:1269)
11-29 00:43:32.599  4558  4558 E AndroidRuntime: 	at android.app.Activity.performResume(Activity.java:6774)
11-29 00:43:32.599  4558  4558 E AndroidRuntime: 	at android.app.ActivityThread.performResumeActivity(ActivityThread.java:3477)
11-29 00:43:32.599  4558  4558 E AndroidRuntime: 	at android.app.ActivityThread.handleResumeActivity(ActivityThread.java:3546)
11-29 00:43:32.599  4558  4558 E AndroidRuntime: 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1577)
11-29 00:43:32.599  4558  4558 E AndroidRuntime: 	at android.os.Handler.dispatchMessage(Handler.java:110)
11-29 00:43:32.599  4558  4558 E AndroidRuntime: 	at android.os.Looper.loop(Looper.java:203)
11-29 00:43:32.599  4558  4558 E AndroidRuntime: 	at android.app.ActivityThread.main(ActivityThread.java:6247)
11-29 00:43:32.599  4558  4558 E AndroidRuntime: 	at java.lang.reflect.Method.invoke(Native Method)
11-29 00:43:32.599  4558  4558 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1063)
11-29 00:43:32.599  4558  4558 E AndroidRuntime: 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:924)
#### Version of Realm and tooling

Realm version(s): ?
5.1.0
Realm Sync feature enabled: Yes/No

Android Studio version: ?
3.0.1
Android Build Tools version: ?
27
Gradle version: ?
3.0.1
Which Android version and device(s): ?
7.0

**Comment by abayomiAkanji** [comment]
[This](https://github.com/realm/realm-java/issues/4777) might help you.

**Comment by jkkey** [comment]
This is a mistake that happened in my project ， t took hours for the APP to appear ， 
not very often, but several times

**Comment by Zhuinden** [comment]
Also worth noting that if you open too many threads (like `Schedulers.newThread()` or `new Thread(new Runnable() {` or create a new executor for each background task for w/e reason) then that can cause problems too.

**Comment by jkkey** [comment]
> [This](https://github.com/realm/realm-java/issues/4777) might help you.

Thanks

**Comment by jkkey** [comment]
> Also worth noting that if you open too many threads (like `Schedulers.newThread()` or `new Thread(new Runnable() {` or create a new executor for each background task for w/e reason) then that can cause problems too.

I call it  in main thread

**Comment by cmelchior** [comment]
Outdated, so closing. If this is still a problem we need an example project demonstrating the issue, but the underlying problem should be described above.
