### ISSUE TITLE
RealmList of primitive must be marked with @Required in order to work with Swift

### ISSUE THREAD

**Issue by stephenmcbride** [realm/realm-java#6358]
#### Goal
I have a RealmObject that contains a field which is a list of Strings. I want to be able to export data containing this realm object to populate a realm on iOS.

According to Realm's Java docs 

> Fields with primitive types and the RealmList type are required implicitly

 so I shouldn't need the @Required annotation.

According to Realm's Swift docs, lists of any type cannot be optional so must be declared like: 
`let value = List<Type>()`

So we should be fine, right?

#### Actual Results
The iOS app will crash when attempting to load the realm file exported from Java.

> Property 'RealmObject.listOfStrings' has been made required.

This is because it's interpreting the field in the populated realm file as being optional but the one in the Swift realm is non-optional. This crash can be fixed by annotating the listOfStrings field with the @Required tag in Java.

#### Steps & Code to Reproduce
- Create a simple RealmObject which has only one field, a RealmList of String type.
`public RealmList<String> listOfStrings;`
- Run the app and extract the realm file from the device.
- Create a Swift class extending from Object in RealmSwift in the iOS app which again only has one field: 
`let listOfStrings = List<String>()`
- Add your realm file to XCode and open it in the app delegate:
```
let config = Realm.Configuration(
            fileURL: Bundle.main.url(forResource: "prepopulated", withExtension: "realm"),
            readOnly: true, schemaVersion: currentSchemaNumber)
let bundledRealm = try! Realm(configuration: config)
```

       
- Run that app and you will see it will crash with error mentioned before.
- Go back to the Java class and add the @Required annotation and repeat the other previous steps.
- Observe that the iOS app now runs successfully.

Either the docs need to be update to mention this caveat when going between Java and Swift or else the Swift interpreter needs to be a bit smarter.

#### Version of Realm and tooling

Realm version(s): Java 5.7.0 Swift 3.11.1

Realm Sync feature enabled: No

Android Studio version: 3.3 Beta 1

Android Build Tools version: N/A

Gradle version: N/A

Which Android version and device(s): N/A

**Comment by cmelchior** [comment]
`String` isn't a primitive type, but I agree the documentation could be more clear about this.

**Comment by cmelchior** [comment]
Updated the  Javadoc for the `@Required` annotation to better explain nullability around strings.

**Comment by stephenmcbride** [comment]
Thanks Christian
