### ISSUE TITLE
Caused by: io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/data/com.realm/files/demo.realm': Realm file decryption failed. (Realm file decryption failed) (/data/data/com.realm/files/demo.realm) in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 238 Kind: ACCESS_ERROR.

### ISSUE THREAD

**Issue by rajkateshiya** [realm/realm-java#6359]
#### Goal
When launch app then getting error on trying decrypt the realm database

#### Actual Results
Caused by: io.realm.exceptions.RealmFileException: Unable to open a realm at path '/data/data/com.realm/files/demo.realm': Realm file decryption failed. (Realm file decryption failed) (/data/data/com.realm/files/demo.realm) in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 238 Kind: ACCESS_ERROR.

Realm version(s): 3.4.0

Realm Sync feature enabled: No

Android Studio version: 3.0 Beta 2

Android Build Tools version: 28.0.3

Which Android version and device(s): Motorola Moto G (5) Plus (Android 8.1.0, API 27)

**Comment by abayomiAkanji** [comment]
Hi @rajkateshiya you are likely attempting to decrypt the DB with a key different from the one you used to encrypt it.

How are you generating your keys?

**Comment by cmelchior** [comment]
Outdated, so closing, but I assume you fixed the error. If not, feel free to re-open and provide a sample project demonstrating the problem.
