### ISSUE TITLE
After creating a snapshot of RealmList, some objects become invalid

### ISSUE THREAD

**Issue by Dwite** [realm/realm-java#6366]
#### Goal
Delete RealmList objects from Realm 

#### Actual Results
After creating a snapshot of RealmList some objects are invalid, looping through them in order to delete them produce an 

```
java.lang.IllegalStateException: Object is no longer valid to operate on. Was it deleted by another thread?
        at io.realm.internal.UncheckedRow.nativeGetIndex(Native Method)
        at io.realm.internal.UncheckedRow.getIndex(UncheckedRow.java:127)
        at io.realm.RealmObject.deleteFromRealm(RealmObject.java:114)
        at io.realm.RealmObject.deleteFromRealm(RealmObject.java:86)

```

#### Steps & Code to Reproduce
My object:
```
open class NorwaySiteEntity(
    @PrimaryKey
    var siteID: String = "",
    var roles: RealmList<WorkerRoleEntity> = RealmList()
) : RealmObject()
```
This is how I delete this objects. I tried to loop throigh **roles** before creating the snapshot - all objects are valid. But after snapShot, some objects might become invalid.
 ```
val snapshotRoles = site.roles.createSnapshot()
snapshotRoles.forEach {
    it.deleteFromRealm()
}
```

#### Version of Realm and tooling

Realm version(s): 5.1.0

Realm Sync feature enabled: No

Android Studio version: 3.2.1

Android Build Tools version: 28.0.3

Gradle version: plugin 3.2.1, gradle 4.10.3

Which Android version and device(s): Samsung Note 8, Android 8.0

**Comment by Dwite** [comment]
> Is the same object in the list multiple times?

Looks like yes, two objects have the same PrimaryKey. And because we remove the same object under the hood, when we try to remove it second time it's invalid, am I correct?

**Comment by Zhuinden** [comment]
> when we try to remove it the second time it's invalid, am I correct?

Then yes

**Comment by cmelchior** [comment]
Yes, `snapshot` just freezes the collection size, but the items inside can still be invalidated (e.g. by deleting them).  

```
val snapshotRoles = site.roles.createSnapshot()
snapshotRoles.deleteAllFromRealm()
```

Is also faster to use, so if you don't need custom filtering I would use that instead of `forEach`. Otherwise you need to check all objects with `obj.isValid()` before trying to delete it.

**Comment by Dwite** [comment]
> Yes, `snapshot` just freezes the collection size, but the items inside can still be invalidated (e.g. by deleting them).
> 
> ```
> val snapshotRoles = site.roles.createSnapshot()
> snapshotRoles.deleteAllFromRealm()
> ```
> Is also faster to use, so if you don't need custom filtering I would use that instead of `forEach`. Otherwise you need to check all objects with `obj.isValid()` before trying to delete it.

Thank you very much, I believe in this case we can close the issue.
