### ISSUE TITLE
Version upgrade, query part of the data scrambling

### ISSUE THREAD

**Issue by zhoukai0203** [realm/realm-java#6367]
Realm version 5.8.0 encrypted database, switching database configuration when switching users, resulting in some content queries displayed as scrambled code, 5.4.1 does not have this problem.

Realm version(s):  5.8.0

Realm Sync feature enabled: no

Android Studio version: 3.2

Android Build Tools version: 28

Gradle version: 4.6

Which Android version and device(s): 8.1 all

**Comment by cmelchior** [comment]
Outdated, so closing. 

It is also unclear exactly what the issue is. Please provide a working example project if you are still having issues.
