### ISSUE TITLE
 library implements Realm. export the library to an AAR file and import it in a project 

### ISSUE THREAD

**Issue by kehanchenk** [realm/realm-java#6369]
Our sdk use realm, we generate an aar file ,when app use this aar, objects that extends RealmObject will 
case  NullPointerException. such  as schema.get("ResSingleGroupModel")

**Comment by cmelchior** [comment]
Well, `schema.get("ResSingleGroupModel")` returning `null` means that the class `ResSingleGroupModel` is not part of the schema for the Realm being opened. If that class comes from your library, people need it include it in their schema. You can read more about it here: https://realm.io/docs/java/latest/#schemas

**Comment by kehanchenk** [comment]
Thank you for your patience .
 projectuse this module  no problem , but this module generate an aar file import project, This problem has happened

**Comment by cmelchior** [comment]
If you can provide a sample project that can reproduce it, I will be happy to take a look. But I cannot tell you what you are doing wrong from just the short description above.

Most likely though you need to include the library classes in the schema, something like:


```
RealmConfiguration config = new RealmConfiguration.Builder()
   .addModule(new MyLibraryModule())
  .build();
```

But this should be described in the link I posted.

**Comment by cmelchior** [comment]
I assume the above answered your question. If not, feel free to re-open this issue. Closing.
