### ISSUE TITLE
cancelable delete

### ISSUE THREAD

**Issue by MkazemAkhgary** [realm/realm-java#6373]
#### Describe your problem or use case

I have a JSON file and I want to update my database from this file. (this JSON is flat and can not be updated directly using `createOrUpdateAllFromJson`. )

How ever I want a fresh update, so I call this inside async realm transaction.

```java
realm.deleteAll(); // get rid of old data

// code to update database from JSON.
```

but if my update fails, say a JSON exception happens, then old data is gone and nothing is added. isn't there any way to make `deleteAll` work like a transaction? if transaction fails and canceled nothing should be affected.

---

Also `createOrUpdate` is not what I want, because items with old id can be deleted from JSON database but they are never deleted from realm database. that's why I tried `realm.deleteAll`.

**Comment by cmelchior** [comment]
It is hard to tell exactly what you are doing without a complete code example, but if you cancel a transaction everything inside it will be reversed. E.g doing it this way:

```
realm.beginTransaction();
try {
  realm.deleteAll();
  realm.createOrUpdateFromJson(Person.class, loadJson());
  realm.commitTransaction();
} catch (Exception) {
  realm.cancelTransaction();
}
```

**Comment by MkazemAkhgary** [comment]
Oh my god, I had a try-catch for parsing JSON that was eating the exception. I forgot to put `throw new RuntimeException(e)`

Im really sorry for this mistake. I really missed it.
