### ISSUE TITLE
Log 500 errors better

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#6381]
In some cases ROS might be misbehaving resulting in it not sending proper JSON back to the client.
This will result in errors like this:

```
D/REALM_JAVA: AuthenticateResponse - Error: JSON_EXCEPTION(1)
   Server failed with 500, but could not parse error.
   org.json.JSONException: Value <html> of type java.lang.String cannot be converted to JSONObject
       at org.json.JSON.typeMismatch(JSON.java:111)
       at org.json.JSONObject.<init>(JSONObject.java:160)
```

In those cases, we should log the output of the HTML page as part of the exception as this will make debugging easier.

**Comment by Zhuinden** [comment]
or ROS could send a JSON that has a `link` attribute for whatever HTML it wants to send :thinking:

**Comment by cmelchior** [comment]
Well, the problem here is that the error handling on the server is not working, so I don't think we can expect the server to do that either 😄
