### ISSUE TITLE
Issues maintaining Realm Instances

### ISSUE THREAD

**Issue by abayomiAkanji** [realm/realm-java#6388]
Hi everyone, please I need your input.

In order to easily maintain my realm DB, I created a wrapper class to maintain the **instance**.
Despite that, I keep getting this error: `io.realm.exceptions.RealmError: Unrecoverable error. mmap() failed: Out of memory size:`

I would like you to look into my code and see what I am doing wrong.

Below is the class that manages the realm instance:

```
class AppDatabase {

   companion object {
       @JvmStatic
       fun getInstance(): AppDatabase = AppDatabase().apply {}
   }

   fun realmDao(): RealmDao {
       return RealmDao(getRealm())
   }

   private fun getRealm(): Realm {
       val config = RealmConfiguration.Builder()
               .name(dbName)
               .schemaVersion(5)
               .encryptionKey(KEY)
               .migration(DbMigration())
               .build()

       return Realm.getInstance(config)
   }

}
````

N.B: `RealmDao`  is the **Data Access Object** to save and query the DB. It receives the **realm instance** via it's constructor for it's use.

**Comment by Zhuinden** [comment]
I mean, we can't possibly know if you ever close the Realm instance you are passing to your `RealmDao` object that the `getRealm()` function creates on each call to `realmDao()`.

**Comment by abayomiAkanji** [comment]
Yes I do. For every instance where I **query** or **save** to dB, I do a `try and finally block` and I call the `realm.close()` in the finally block.

Yet the error persists.

**Comment by Zhuinden** [comment]
For queries? Then how do you use RealmChangeListener? You need at least one open Realm instance for that.

**Comment by abayomiAkanji** [comment]
Is there a way to effectively create a **single instance** of the **realm object** throughout the app lifecycle?

I believe that creating a single instance could solve the issue. What do you think?

**Comment by Zhuinden** [comment]
I can't really give tips because the rules are given: Realm should be open PER THREAD for as long as it is used, and it should be closed PER THREAD and as many times as `getInstance(config)` was called on that thread when it is no longer used.

As long as you do that, things work fine.

If you have open Realms on non-looper background threads, then you can easily run out of memory.

**Comment by abayomiAkanji** [comment]
Thanks for your contributions.

I will consider passing the realm instance from my activities/fragments when needed and close them in the `onDestroy()` method. Hopefully that’ll solve the lingering issue. 

I am just a bit scared of how easy one would be able to manage such implementation if there is a need to change the database library (in future). I might need to start changing all instances where I’ve created the `realm object` on the UI thread.

I would also look into the RealmChangeListener()

**Comment by Zhuinden** [comment]
> I am just a bit scared of how easy one would be able to manage such implementation if there is a need to change the database library (in future). I might need to start changing all instances where I’ve created the realm object on the UI thread.

oh look a [wild Realm-instance auto-management library occurred that uses the same abstraction (`LiveData<List<T>>`) as Room does](https://github.com/Zhuinden/realm-monarchy/)

**Comment by abayomiAkanji** [comment]
Many thanks for your contributions and prompt responses. The issue seems resolved now.

I had to create the instance at the points they are needed and they are being closed after the activities/fragments are destroyed.
