### ISSUE TITLE
How can i get only added items in RealmResult<>

### ISSUE THREAD

**Issue by ghorbanzadeh-me** [realm/realm-java#6393]
I have a change listener like below .
Its return all records . but i want to return just added records .

how can i implement it ?

        chats.addChangeListener(new RealmChangeListener<RealmResults<Chats>>() {
            @Override
            public void onChange(RealmResults<Chats> newChat) {
                    // codes
            }
        });

**Comment by Zhuinden** [comment]
You receive insertions if you add `OrderedRealmCollectionChangeListener`.

**Comment by ghorbanzadeh-me** [comment]
Thank you !
