### ISSUE TITLE
class io.realm.ab$a declares multiple JSON fields named a

### ISSUE THREAD

**Issue by abayomiAkanji** [realm/realm-java#6395]
I am converting an Class (which has a list of `realm objects` as a field) to JSON.

The app keeps crashing with error `class io.realm.ab$a declares multiple JSON fields named a` meanwhile it works fine on some devices.
I updated my `proguard file` to keep the class members (as suggested on Slackoverflow) but all to no avail.

Below is my code snippet.

```
val intent = Intent(this, MyActivity::class.java)
intent.putExtra(KEY, Gson().toJson(object)) //this line causes the error
startActivity(intent)
```

Someone should help with a working solution.

**Comment by Zhuinden** [comment]
But you *are* serializing the object to json.

Although that'd already only work for detached objects. 🤔

**Comment by abayomiAkanji** [comment]
That's thoughtful.
I never expected to see the error because I eventually set the **list of realm objects** to `ArrayList()` and eventually set them in the next activity using the primary keys (which are in a separate field).

**Comment by Zhuinden** [comment]
I'd never put managed RealmObjects in an ArrayList.

**Comment by abayomiAkanji** [comment]
Thanks for your response. I will look into that to enable best practice.

I will let you know if the issue still persists after updating the proguard rule.
