### ISSUE TITLE
Remove all listeners cascade

### ISSUE THREAD

**Issue by mgohin** [realm/realm-java#6396]
#### Describe your problem or use case
I have a `RealmObject` (I'll call it `mainObject`) that contains multiple other managed `RealmObject`s and I set listeners everywhere (`mainObject`, nested objects, lists etc).
To describe all contained objects - that may also contain objects - I'll call it `NestedObjectsTree`.

#### Describe the solution you'd like
Add a boolean to `removeAllChangeListeners` function, or create a new function to remove listeners with cascade.

When I call `mainObject.removeAllChangeListeners(true)` it'll remove all listeners on `mainObject` and all listeners on all objects of `NestedObjectsTree`, down the tree.

Feel free to edit or suggest modifications (vocabulary, feature etc).

**Comment by Zhuinden** [comment]
The real trick is that you need to prefer a field ref to the observed objects because the getter returns a new instance each time. This is much more complex than it looks.

Maybe you just want to observe a RealmResults of the root element?

**Comment by mgohin** [comment]
Do you have a link to get more explanation about `the getter returns a new instance each time.` please ?

**Comment by Zhuinden** [comment]
just check the implementation of `get[YourLinkedObject]` in the `___RealmProxy.java` file.

**Comment by mgohin** [comment]
So I should apply listeners only on the `mainObject` or `RealmResults` ?

**Comment by Zhuinden** [comment]
Depends on what changes you want to be notified of.

**Comment by cmelchior** [comment]
That we return a new object instance is probably something we want to optimize when given time, but yes, the current behavior is to return a new instance every time you call `get<ObjectReference>()`.

Tracking all listeners that flows from a single root object is not trivial nor am I sure it is something that belongs directly in the Realm API's. Right now you can either manually call `removeListener` or just let the objects be GC'ed. For more advanced use cases my default reaction is that it is up to the users of the API to handle it.

That said, I'm not 100% sure about your use case. Can you describe it in more detail? You have a root object, that is common. But why do you need to unregister all listeners at once?

**Comment by mgohin** [comment]
Example

    class MainObject extends RealmModel {
        ...
        SubObject subObject; //is a managed realm object
        ...
    }

Let's say I want to be notified when `subObject.myProperty` change (let's say it's a boolean)

**Comment by Zhuinden** [comment]
Then you need to keep a reference both to `MainObject` and to `SubObject` obtained via `mainObject.getSubObject()` and add a listener to both to make sure you know everything

**Comment by cmelchior** [comment]
> But as I understand now, if I don't keep mainObject.getSubObject() into a variable, next time I call mainObject.getSubObject() I'll get a new one, that will not have my listener ?

That is correct, but I'm not sure how you can end up in a situation where it matters unless you are handling registering and unregistering listeners in two completely different parts of your code base. Which (generally speaking) probably is an architectural problem and a code smell.

**Comment by cmelchior** [comment]
Or I guess if you use code like 

```
mainObject.getSubObject().addChangeListener(...);
mainObject.getSubObject().removeChangeListener(...);
```

Which, I grant, feels like it should work, but currently doesn't.

**Comment by mgohin** [comment]
There is a moment in my app's workflow where I need to remove all changeListeners I did set, to avoid running code that does not have to be called anymore.
I'll close this feature request as it's not possible for now ;)

Thanks for your answers guys !

**Comment by mgohin** [comment]
In fact I do have a last question about 

    mainObject.getSubObject().addChangeListener(...);
    mainObject.getSubObject().removeChangeListener(...);

if `subObject` is a RealmList, is it the same problem ?

**Comment by Zhuinden** [comment]
Of course :wink:

**Comment by mgohin** [comment]
ok thanks ;)
