### ISSUE TITLE
ReclmRecyclerViewAdapter needs scroll to show added item

### ISSUE THREAD

**Issue by ghorbanzadeh-me** [realm/realm-java#6398]
Hi . I'm using realm Recycler View Adapter that implemented as RealmRecyclerViewAdapter .

It need scroll to show added items even the position of recyclerview is Zero ( 0 ) .

Is it possible to scroll automatically when item added without using scrollToPosition ?

**Comment by Zhuinden** [comment]
Whether you use your own adapter or RealmRecyclerViewAdapter, you'd have to manually scroll to position for this.

**Comment by ghorbanzadeh-me** [comment]
No . in my opinion its not true .

Because when i am using my own adapter its working fine and no need to scroll .

Take a look please : The commented lines working fine ( my own adapter ) but RealmRecyclerViewAdapter not .

Realm realmConnection = Realm.getDefaultInstance();
        RealmResults<Chats> chats = realmConnection.where(Chats.class).equalTo("userId" , userName).sort("unixTime", Sort.DESCENDING).findAll();
        RealmChatAdapter adapter = new RealmChatAdapter(chats , true , true);
        LinearLayoutManager linearLayoutManager = new LinearLayoutManager(recyclerView.getContext() , LinearLayoutManager.VERTICAL, true);
        linearLayoutManager.setStackFromEnd(false);
        recyclerView.setLayoutManager(linearLayoutManager);
        recyclerView.setAdapter(adapter);
        recyclerView.addItemDecoration(new DividerItemDecoration(recyclerView.getContext(), DividerItemDecoration.VERTICAL));

        /*if(mAdapter == null)
        {
            LinearLayoutManager linearLayoutManager = new LinearLayoutManager(recyclerView.getContext() , LinearLayoutManager.VERTICAL, true);
            linearLayoutManager.setOrientation(LinearLayoutManager.VERTICAL);
            linearLayoutManager.setStackFromEnd(false);
            recyclerView.setLayoutManager(linearLayoutManager);
            mAdapter = new ChatAdapter(chatMessagesViewModelArrayList);
            recyclerView.setAdapter(mAdapter);
        }
        else
        {
            mAdapter.update(chatMessagesViewModelArrayList);
        }*/

**Comment by cmelchior** [comment]
Closing this issue since it is not related to Realm but how the RecyclerViewAdapter works.
