### ISSUE TITLE
Change listener unintentional invoked

### ISSUE THREAD

**Issue by mgohin** [realm/realm-java#6401]
I'm bringing you this to your attention because I'm in the same case : https://stackoverflow.com/questions/54188149/realm-change-listener-unintentional-invoked

I did not find anything in doc to provide explanations, or I did not check properly ?

**Comment by cmelchior** [comment]
When you call `exceuteTransaction()` it will advance the Realm version to the latest to ensure ACID properties. This will also trigger notifications if the Realm changed, so it is expected if that happened?

**Comment by cmelchior** [comment]
If you want to avoid it, you should use `executeTransactionAsync` which will run the transaction in the background and notifications will trigger "as normal"

**Comment by cmelchior** [comment]
It is slightly slower, yes, but since it happens on a background thread it doesn't matter for the UI speed. In fact, it will probably speed it up, since writing to disk will also happen in the background.

**Comment by mgohin** [comment]
Ok I tried and I still have the same behavior.
All objects are linked to one :

    class Parent extends RealmObject {
        Child child; //realm object
        RealmList<Car> cars;
    }

I have a `RealmObjectChangeListener` on `parent.child` and a `OrderedRealmCollectionChangeListener` on `parent.cars`.

When I update child (with `executeTransactionAsync`), the listener on cars gets called and has in the `changeSet.getChanges()` all cars index.

**Comment by Zhuinden** [comment]
There isn't enough info about the RealmResults to actually tell what's up.

But it is true that RealmChangeListener on a RealmResults is notified of nested list changes, but not of nested object property changes, I think.

**Comment by mgohin** [comment]
My example is wrong, in fact `Car` and `Child` has a reference to `Parent` so it triggers their listener.
So I must get ride of those references :)
