### ISSUE TITLE
Not receiving updated if using map in Flowable chain

### ISSUE THREAD

**Issue by lemberh** [realm/realm-java#6404]
I'm fetching data from realm using flowable
Table is empty I execute following code:
```
Realm.getDefaultInstance().where(MyClass::class.java).findAllAsync().asFlowable()
                .subscribe {
                    it.firstOrNull()?.isEnabled
                }
```
then when I put some data into this table I receive it in subscribe callback
If I change this code to following I stop receiving updates
```
Realm.getDefaultInstance().where(MyClass::class.java).findAllAsync().asFlowable()
                .map { it.firstOrNull() }
                .subscribe {
                    it?.isEnabled
                }
```
But if table was not empty I receive initial data and updates  when data changes
Kotlin 1.3
Realm version(s): 5.8
Realm Sync feature enabled: No

**Comment by cmelchior** [comment]
It is because `Realm.getDefaultInstance().where(MyClass::class.java).findAllAsync().asFlowable()` will emit immediately when subscribed to, but at that point, the async query isn't done yet, so you are receiving an unloaded result which basically acts as the empty list.

If you change it to this I suspect it will work: 

```
Realm.getDefaultInstance().where(MyClass::class.java).findAllAsync().asFlowable()
                .filter { it.isLoaded } // Only continue with actual query results
                .map { it.firstOrNull() }
                .subscribe {
                    it?.isEnabled
                }
```

**Comment by Zhuinden** [comment]
Also don't use `Realm.getDefaultInstance().where(` because it has unintended side effects.

**Comment by cmelchior** [comment]
I assume the above answered your question. If not feel free to re-open this issue. Closing.
