### ISSUE TITLE
RealmFileException

### ISSUE THREAD

**Issue by 1322202454** [realm/realm-java#6405]

**Comment by 1322202454** [comment]
Realm version(s): 5.8.0
Android Studio version: 3.3

**Comment by Zhuinden** [comment]
Sounds like you didn't set the correct encryption key for the RealmConfiguration set as default configuration

**Comment by cmelchior** [comment]
You need to provide the same encryption key that was first used to create the Realm. It is unclear from the above code what `StringUtil.getUUID()` does.

**Comment by Zhuinden** [comment]
If you are getting a new random UUID each time you start the app, then yes, the encryption key will differ and you won't be able to open previously created Realm files. 🤔

**Comment by 1322202454** [comment]
> If you are getting a new random UUID each time you start the app, then yes, the encryption key will differ and you won't be able to open previously created Realm files. 🤔

When the App is first started, it will generate a key that will be stored in sharedpreferences and then it will be fetched from sharedpreferences to initialize the Realm

**Comment by Zhuinden** [comment]
In that case there is a chance that you are trying to use `Realm.getDefaultInstance()` somewhere without having set the default configuration in time.

For example, set the default config in `SplashActivity.onCreate` instead of `CustomApplication.onCreate()`.

**Comment by 1322202454** [comment]
> You need to provide the same encryption key that was first used to create the Realm. It is unclear from the above code what `StringUtil.getUUID()` does

When the APP is first started, it generates two uuids that form a 64-bit Realm key that is stored in sharedpreferences

**Comment by 1322202454** [comment]
> In that case there is a chance that you are trying to use `Realm.getDefaultInstance()` somewhere without having set the default configuration in time.
> 
> For example, setting the default config in `SplashActivity.onCreate` instead of `CustomApplication.onCreate()`.

Thank you. I'll try

**Comment by Zhuinden** [comment]
@1322202454 I'm not sure if I confused you, but you should create and set the default RealmConfiguration in your Application class

**Comment by 1322202454** [comment]
> @1322202454 I'm not sure if I confused you, but you should create and set the default RealmConfiguration in your Application class

I'm now at the RealmConfiguration that I set up in my Application, and after a while Realm file decryption fails

**Comment by cmelchior** [comment]
If you are still having this problem we probably need an example project demonstrating the issue in order to debug it further.
