### ISSUE TITLE
[android] what is the difference between two of this values?

### ISSUE THREAD

**Issue by SiarheiSm** [realm/realm-java#6409]
![image](https://user-images.githubusercontent.com/24812695/51555409-983c8780-1e88-11e9-8dcf-6642e0a4db2f.png)
i mean param that comes from toString() and values in the object.
Could you please clarify? :)

**Comment by Zhuinden** [comment]
Fields are not initialized, but values accessed from the accessors are.

toString() uses the accessors, therefore its values are correct.

**Comment by SiarheiSm** [comment]
ok, thank you
