### ISSUE TITLE
Why my Checkbox get uncheked in RecyclerView when i leave activity

### ISSUE THREAD

**Issue by Amiable1996** [realm/realm-java#6419]
My Code is 
`package com.example.sindhifarm;

import android.content.Context;
import android.content.Intent;
import android.support.annotation.NonNull;
import android.support.v7.widget.RecyclerView;
import android.view.LayoutInflater;
import android.view.View;
import android.view.ViewGroup;
import android.widget.CheckBox;
import android.widget.CompoundButton;
import android.widget.ImageView;
import android.widget.TextView;

import java.text.SimpleDateFormat;
import java.util.Calendar;
import java.util.UUID;

import io.realm.Realm;
import io.realm.RealmResults;

public class cropsSeedingAdapter extends RecyclerView.Adapter<cropsSeedingAdapter.MyViewHolder> {

    private Context mContext;
    private RealmResults<CropsSeedingModel> mRealmCropList;
    private LayoutInflater mInflater;
    private Realm mRealm;

    public cropsSeedingAdapter(Context context, Realm myRealm, RealmResults<CropsSeedingModel> cropList) {
        this.mContext = context;
        this.mRealm = myRealm;
        this.mRealmCropList = cropList;
        this.mInflater = LayoutInflater.from(context);

    }

    @NonNull
    @Override
    public cropsSeedingAdapter.MyViewHolder onCreateViewHolder(@NonNull ViewGroup viewGroup, int viewType) {
        View itemView = mInflater.inflate(R.layout.activity_crops_seed_list_item,viewGroup, false);
        cropsSeedingAdapter.MyViewHolder viewHolder = new cropsSeedingAdapter.MyViewHolder(itemView);
        return viewHolder;

    }

    @Override
    public void onBindViewHolder(@NonNull final cropsSeedingAdapter.MyViewHolder myViewHolder, int i) {
        CropsSeedingModel cropsSeedingModel = mRealmCropList.get(i);
        myViewHolder.setData(cropsSeedingModel,i);
        myViewHolder.setListeners();

    }

    @Override
    public int getItemCount() {
        return mRealmCropList.size();
    }

    public class MyViewHolder extends RecyclerView.ViewHolder {

        private int position;
        private CheckBox checkToCultivate;
        private TextView txvCropName,txvCropField, txvCropDate;
        private ImageView imgDelete, imgEdit;

        public MyViewHolder(View itemView) {
            super(itemView);
            txvCropName		= (TextView) itemView.findViewById(R.id.txvCropdName);
            txvCropField = (TextView) itemView.findViewById(R.id.txvCropField);
            txvCropDate 	= (TextView) itemView.findViewById(R.id.txvDateCrop);
         checkToCultivate = itemView.findViewById(R.id.checkBox);
            imgDelete 			= (ImageView) itemView.findViewById(R.id.ivRowDelete);
            imgEdit 			= (ImageView) itemView.findViewById(R.id.ivRowEdit);
        }

        public void setData(CropsSeedingModel cropsIn, int position) {
            this.position = position;

            final String cropName = "فصل جو نالو" + " : " + cropsIn.getCropName();
            txvCropName.setText(cropName);

            final String cropField = "فصل جي زمين" +" : " + cropsIn.getCropFeild() ;
            txvCropField.setText(cropField);

            final String cropDate = "ابتدائي تاريخ" + " : "+cropsIn.getCropDate() ;
            txvCropDate.setText(cropDate);

            //CheckBox Logic
        checkToCultivate.setOnClickListener(new View.OnClickListener() {
            @Override
            public void onClick(View v) {

                if(checkToCultivate.isChecked())
                {
                    mRealm.executeTransaction(new Realm.Transaction() {
                        @Override
                        public void execute(Realm realm) {
                            cropsCultivateModel cropCultivate = mRealm.createObject(cropsCultivateModel.class,UUID.randomUUID().toString());

                            cropCultivate.setCultivateName(cropName);
                            cropCultivate.setCultivateFeild(cropField);
                            Calendar calendar = Calendar.getInstance();
                            SimpleDateFormat mdformat = new SimpleDateFormat("dd / MM / yyyy ");
                            String strDate = mdformat.format(calendar.getTime());
                            cropCultivate.setCultivateDate(strDate);
                        }
                    });
                }

                else
                {

                }

            }
        });

        }

        public void setListeners() {

            imgDelete.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {

                    mRealm.executeTransaction(new Realm.Transaction() {
                        @Override
                        public void execute(Realm realm) {
                            mRealmCropList.deleteFromRealm(position);
                            notifyItemRemoved(position);
                            notifyItemRangeChanged(position, mRealmCropList.size());

                        }
                    });
                }
            });

            imgEdit.setOnClickListener(new View.OnClickListener() {
                @Override
                public void onClick(View v) {
                    Intent intent = new Intent(mContext, cropsSeedingEdit.class);
                    intent.putExtra("position", position);
                    mContext.startActivity(intent);

                }
            });
        }
    }
}
`

**Comment by Amiable1996** [comment]
@Zhuinden when the checkbox is checked , i wanted to save data in other model...

**Comment by Amiable1996** [comment]
@Zhuinden  @cmelchior  any suggestion how to maintain state of checkbox in recycler view , i have to submit my project tomorrow??

**Comment by Zhuinden** [comment]
Ah, this isn't even a Realm-specific thing. Normally you store a `HashSet<IdType>` which contains `selectedItemids` and you set the checkbox state based on that.

In our code it looks like this:

``` kotlin
    private fun refreshFriendList(friends: List<Opponent>) {
        recyclerViewFriends.adapter = adapter.replaceItemsWith {
            addAll(friends.map { friend: Opponent -> SelectFriendsUserRowItem(this@SelectFriendsView, friend, selectedFriends.contains(friend)) })
        }
        updateSelectedMatchesCount()
    }
```

**Comment by cmelchior** [comment]
Outdated, so closing. Also, the above solution should work.
