### ISSUE TITLE
No migration required

### ISSUE THREAD

**Issue by ameet20** [realm/realm-java#6421]
Hi,

Getting a `RealmMigrationNeededException` exception in case of a schema version bump without migration, even without schema changes.

Result says: Thrown no exception 

Following case fails 

```
@Test
    fun schemaVersionBumpRequiresMigration() {
        val realmV0config = RealmConfiguration.Builder()
            .build()

        Realm.getInstance(realmV0config).close()

        val realmV1config = RealmConfiguration.Builder()
            .schemaVersion(1)
            .build()

        var realm: Realm? = null

        try {
            realm = Realm.getInstance(realmV1config)
            fail()
        } catch (expected: RealmMigrationNeededException) {
        } finally {
            realm?.close()
        }
    }
```

If I add a migration to `realmV1config` it actually get's called - this behavior seems inconsistent. I think if Realm sees a schema version bump it should require a migration and throw if it's missing instead of deciding that it is optional. If the current behavior is expected, the `Javadoc` of RealmConfiguration.Builder.schemaVersion should reflect that.

**Comment by MongoCaleb** [comment]
Will be part of #6500
