### ISSUE TITLE
RealmSearch View

### ISSUE THREAD

**Issue by Amiable1996** [realm/realm-java#6422]
Why thorbenPrime's search view gradle implementation is not working?
Is anyone confronted same issue?

**Comment by Zhuinden** [comment]
Because it hasn't been updated in about 4 years.

**Comment by Amiable1996** [comment]
So how can we implement searchview?

**Comment by Zhuinden** [comment]
Well, you can either fix the Thorbenprimke library or you can do it yourself. Generally it's just an EditText that updates a RecyclerView, no?

In which case you just need to do the same thing as https://stackoverflow.com/questions/40630322/how-to-implement-filterable-in-realmrecyclerviewadapter/40632613#40632613

**Comment by Amiable1996** [comment]
Thanks @Zhuinden , by the way also inventory problem is done...

**Comment by cmelchior** [comment]
Answered, so closing
