### ISSUE TITLE
Encrypted realm file is way smaller. Is that normal ?

### ISSUE THREAD

**Issue by ArilesGit** [realm/realm-java#6425]
Sorry in advance. This is not a question about how to encrypt but rather, I wanted to make sure that this is not a bug (in my code or in Realm).

#### Goal
Not actually a goal, but I was surprised to see that the encrypted file is way smaller than the original.

#### Actual Results
Here is the output to the `ls -l`: 

```
-rw-------   ****   ****     5767168         default.realm
-rw-------   ****   ****     1184            default.realm.lock
drwx------   ****   ****                     default.realm.management
-rw-------   ****   ****     1601536         encrypted.realm
-rw-------   ****   ****     1184            encrypted.realm.lock
drwx------   ****   ****                     encrypted.realm.management
```

#### Steps & Code to Reproduce
I used a test key created in a silly way (just as shown in the doc's example)
   ```
    Realm realm = Realm.getInstance(defaultConfig);
    realm.writeEncryptedCopyTo(file, key);
    realm.close();
```

#### Realm version(s): ?
5.7.0

#### Realm Sync feature enabled: Yes/No
No

#### Android Studio version: ?
3.3.1

#### Android Build Tools version: ?
3.3.1

#### Gradle version: ?
4.10.1

#### Which Android version and device(s): ?
Android 6.0

**Comment by Zhuinden** [comment]
when you write a copy, the Realm that is saved is a compacted copy.

This means that you might want to use `Realm.compactRealm(realmConfig)` sometimes on your original Realm, I personally used to do it when the activity count in my app went from 1 to 0.

**Comment by ArilesGit** [comment]
Thank you @Zhuinden for the quick reply.  
I think I might just leave it as is, as long as I don't lose data during the encryption process.
