### ISSUE TITLE
help me!!!

### ISSUE THREAD

**Issue by zhanglinkai** [realm/realm-java#6434]
**version:0**
public class TestRealm extends RealmObject {
    private String name;
    private int age;
**version1:**
public class TestRealm extends RealmObject {
    private String name;

**application:**

 Realm.init(this);
        Stetho.initialize(//Stetho初始化
                Stetho.newInitializerBuilder(this)
                        .enableDumpapp(Stetho.defaultDumperPluginsProvider(this))
                        .enableWebKitInspector(RealmInspectorModulesProvider.builder(this).build())
                        .build());
        RealmConfiguration config =new RealmConfiguration.Builder().name("test").schemaVersion(1).migration(new MyMigration()).build();
        Realm realm=Realm.getInstance(config);

**RealmMigration:**

  if (oldVersion == 0) {
            RealmObjectSchema personSchema = schema.get("TestRealm");
            personSchema.removeField("age");
            oldVersion++;
        }

**Exception:**

io.realm.exceptions.RealmMigrationNeededException: Migration is required due to the following errors:

 Caused by: io.realm.exceptions.RealmMigrationNeededException: Migration is required due to the following errors:
   - Property 'TestRealm.age' has been removed.

**Comment by Zhuinden** [comment]
Clearly the provided snippet should work. Maybe you should also set it as default configuration?

**Comment by cmelchior** [comment]
@zhanglinkai From the code snippet above it is hard to say. It looks correct. Have you tried to attach a debugger to see if the migration step is actually being triggered correctly?

**Comment by zhanglinkai** [comment]
In the first step, I deleted age in Test Realm, in the second step, I added the version number of application, in the third step, I added the relevant code in Realm Migration, and then run. Is that correct?

**Comment by zhanglinkai** [comment]
Realm realm=Realm.getInstance(config);
this is question
should also set it as default configuration

thanks
