### ISSUE TITLE
Upgrade to Android Gradle Plugin 3.3.+

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#6441]
It looks like the Andoroid Gradle Plugin 3.3.+ uses Lazy Task Configuration which breaks our `realm/realm-library/build.gradle` file.

The reason seems to be that we are calling tasks/modifying them in a way not compatible with the new Task Provider API's. Solving this doesn't seem straight forward and we need to investigate how to migrate. 

Some resources:
https://developer.android.com/studio/releases/gradle-plugin?utm_source=android-studio#behavior_changes
https://docs.gradle.org/current/userguide/lazy_configuration.html

Errors look something like this:
```
WARNING: API 'variant.getExternalNativeBuildTasks()' is obsolete and has been replaced with 'variant.getExternalNativeBuildProviders()'.
It will be removed at the end of 2019.
For more information, see https://d.android.com/r/tools/task-configuration-avoidance.
To determine what is calling variant.getExternalNativeBuildTasks(), use -Pandroid.debug.obsoleteApi=true on the command line to display a stack trace.
```
```
* What went wrong:
Execution failed for task ':kotlin-extensions:publishBasePublicationPublicationToMavenLocal'.
> Failed to publish publication 'basePublication' to repository 'mavenLocal'
   > Invalid publication 'basePublication': artifact file does not exist: '/Users/cm/Realm/realm-java/realm/kotlin-extensions/build/outputs/aar/realm-kotlin-extensions-base-release.aar'

```

**Comment by Zhuinden** [comment]
Personally I'd recommend just killing the Gradle plugin entirely, and asking the users to copy-paste a different snippet (namely the one that registers the transformer task + the libraries) instead. 😉

**Comment by cmelchior** [comment]
It turned out to be a bug with Gradle 5.* instead. Closing for now
