### ISSUE TITLE
Security - Reword issue tracker links into non-URL statements on Java code

### ISSUE THREAD

**Issue by peterbetos** [realm/realm-java#6445]
#### Goal
Issue tracker links are not included on the Java code. They should have been reworded like "see Google tracker issue site with ID 36918154"

#### Actual Results
Issue tracker links are included on the Java code. This exposes potential vulnerability on how the obfuscated variables can be recognised as Context class.

#### Steps & Code to Reproduce
1. Have the application security-scanned by a security provider.
2. Cite the java code exception that throws the issue tracker link on the exception log.

`"Context.getFilesDir() returns " + context.getFilesDir() + " which is not an existing directory. See https://issuetracker.google.com/issues/36918154"`

#### Version of Realm and tooling

Realm version(s): 5.8.0

Realm Sync feature enabled: No

Android Studio version: ? 3.3.1

Android Build Tools version: ? 28.0.3

Gradle version: 4.6

Which Android version and device(s): ?

**Comment by cmelchior** [comment]
I'm not sure exactly what you mean by "obfuscated variables can be recognised as Context class"? 
Are you afraid that if Proguard renames `context` to `a`, then you can guess the real name? While that might be a concern, I don't see how it is related to the URL referenced?

**Comment by peterbetos** [comment]
The Security Team was able to extract http links embedded on the java code using their PenTest suite for the APK:

![screenshot_security](https://user-images.githubusercontent.com/3241327/53614398-cbef9780-3c14-11e9-9ebe-b813d14c7eba.png)
(Rest of the links are redacted for security)

Since they are able to extract a link, they will be able to find the link string on the obfuscated file using code search and substitute the potential variables as context classes.

**Comment by bmunkholm** [comment]
@peterbetos PenTest suites sometimes have false warnings :-)
Can you please explain in details how having an URL in a string can be a security risk?
"substitute the potential variables as context classes." is not understood.

See the code here:
https://github.com/realm/realm-java/blob/master/realm/realm-library/src/main/java/io/realm/Realm.java#L382

**Comment by diegomontoya** [comment]
@peterbetos I think the issue boils down to whatever error string you change to, the variable can be deobfuscated. Obfuscation is not real security nor does it claim to be.  For example, you can obfuscate 100% of all methods and variables into random giberrish and in your case, someone can just look at the bytecode and see the place where it called realm c++ native method that requires a context and boom, i know that variable is Context and modify it via bytecode to whatever end I wish.

**Comment by cmelchior** [comment]
Without a description of an actual attack vector, I very much favour explicit error messages, so closing this issue.
