### ISSUE TITLE
New Kotlin version will cause primary key annotation to disappear

### ISSUE THREAD

**Issue by siralam** [realm/realm-java#6454]
#### Goal
Update Kotlin version to 1.3.21

#### Actual Results
```
Caused by: java.lang.IllegalArgumentException: A RealmObject with no @PrimaryKey cannot be updated: xxxxxxxxxxxxxx
    at io.realm.Realm.checkHasPrimaryKey(Realm.java:1729)
    at io.realm.Realm.copyToRealmOrUpdate(Realm.java:1090)
```

#### Steps & Code to Reproduce
1. Update Kotlin version from 1.2.71 to 1.3.21
2. Build and run the project
3. The above exception is thrown

#### Version of Realm and tooling

Realm version(s): 5.9.1

Realm Sync feature enabled: No

Android Studio version: 3.3.2

Gradle version: 4.8.1

Which Android version and device(s): Any

#### More observations:
After updating kotlin to 1.3.21, in order to build the project, I have to move `apply plugin: 'kotlin-kapt'` above `apply plugin: 'realm-android'` in my `build.gradle`. Otherwise it will throw the below:
```
* What went wrong:
A problem occurred evaluating project ':app'.
> Failed to apply plugin [id 'realm-android']
   > Configuration with name 'kapt' not found.
```

**Comment by cmelchior** [comment]
Yes, this order of plugins should already be documented in our docs: https://realm.io/docs/java/latest/#kotlin

**Comment by siralam** [comment]
@cmelchior I am sorry but I guess you didn't get what I meant... The observation is just meant for providing as much information as I can on this issue, but the observation itself is not an issue. I am aware of that `apply plugin 'kotlin-kapt'` needs to be above `apply plugin: `realm-android;`.

Would you re-open the issue, or do I have some misunderstanding here?

**Comment by cmelchior** [comment]
Are you saying you are getting that error even if `kotlin-kapt` is above `realm-android` ?
Our Kotlin example is already compiling with `1.3.40`, so maybe it is a build cache issue on your machine? Can you reproduce the behaviour on multiple machines?
