### ISSUE TITLE
Connection reset by peer

### ISSUE THREAD

**Issue by pavelpoley** [realm/realm-java#6458]
After i open the app and running some minutes in background i have this error:

```
` E/REALM_SYNC: Connection[4]: Reading failed: Connection reset by peer
E/REALM_JAVA: Error in __permission:
    CONNECTION_RESET_BY_PEER(realm.basic_system:104): Connection reset by peer
E/REALM_SYNC: Connection[1]: Reading failed: Connection reset by peer
 E/REALM_JAVA: Error in __wildcardpermissions:
    CONNECTION_RESET_BY_PEER(realm.basic_system:104): Connection reset by peer
 E/REALM_SYNC: Connection[2]: Reading failed: Connection reset by peer`
```

What can be the reason? i am using 2 different configurations,  full sync and query based.
The app not crash but data no showing, does it mean i need to sign in again or how to prevent this issue?

Realm version(s): 5.9.1

Realm Sync feature enabled: Yes

Android Studio version:3.3.2 ?

**Comment by marcus-hiles** [comment]
Yeah carrying out a test project with Android studio and got an error here too, any help guys?

**Comment by cmelchior** [comment]
`Connection reset by peer` is a network error: https://stackoverflow.com/questions/1434451/what-does-connection-reset-by-peer-mean

Most likely you stopped the server or dropped the connection somehow.

**Comment by pavelpoley** [comment]
I even don't know how to stop the server, it is not randomly happen, it happen every time after 3-4 minutes. I am using cloud platform without additional backend code.

**Comment by cmelchior** [comment]
How is your device connected to the Internet? Does it, in general, have problems with connectivity e.g. when using the browser?

**Comment by pavelpoley** [comment]
I am using WIFI, i don't have problems with Internet, checked without WIFI and on emulator same problem

```
`E/REALM_SYNC: Connection[3]: Reading failed: End of input

 E/REALM_JAVA: Session Error[realms://***.us1a.cloud.realm.io/753fa***74ce/pavel.poley88__gmail.com__1]: MISC_END_OF_INPUT(realm.util.misc_ext:1): End of input

 E/REALM_SYNC: Connection[2]: Reading failed: End of input15536-15612/com.***.next.app
 
E/REALM_SYNC: Connection[5]: Reading failed: End of input

 E/REALM_JAVA: Session Error[realms://***.us1a.cloud.realm.io/users]: MISC_END_OF_INPUT(realm.util.misc_ext:1): End of input

 E/REALM_SYNC: Connection[4]: Reading failed: End of input

 E/REALM_JAVA: Error in __permission:  MISC_END_OF_INPUT(realm.util.misc_ext:1): End of input

 E/REALM_SYNC: Connection[1]: Reading failed: End of input

 E/REALM_JAVA: Error in __wildcardpermissions:
    MISC_END_OF_INPUT(realm.util.misc_ext:1): End of input`
```

**Comment by pavelpoley** [comment]
Does the problem can happen because of open realms/permissionManagers?

**Comment by cmelchior** [comment]
No, both `end of input` and `connection reset by peer` are indications of network problems somewhere.

**Comment by cmelchior** [comment]
Since these errors are network related errors I'll be closing this issue. If you still think this is an issue with Realm itself we would need a sample project to be able to debug this.

**Comment by pavelpoley** [comment]
I guess it is somehow related to `PermissionManager ` or system permissions, usually this connection reset happen after some time when  PermissionManager.getPermissions() called.

Also, after this error the non system realms still syncing and updating data but when i try to call PermissionManager.getPermissions() again error is thrown, and i need to restart the app.

**Comment by pavelpoley** [comment]
I see this error also in Realm todo-full-sync app example

> 2019-04-14 13:27:52.996 32320-32347/io.realm.todo E/REALM_SYNC: Connection[3]: Reading failed: Connection reset by peer
2019-04-14 13:27:52.997 32320-32347/io.realm.todo E/REALM_JAVA: Error in __permission:
    CONNECTION_RESET_BY_PEER(realm.basic_system:104): Connection reset by peer

If i comment the code with `PermissionManager `this error not happen, so maybe this is not connection error at least in the client side?

But lets say it was connection error, it can happen, i think the problem is that after connection is drooped i don't have access to permission manager anymore, it return error. All other realms after drooped connection work fine updating and syncing.

**Comment by pavelpoley** [comment]
> Since these errors are network related errors I'll be closing this issue. If you still think this is an issue with Realm itself we would need a sample project to be able to debug this.

Same happen on Realm todo-full-sync app example
