### ISSUE TITLE
IllegalStateException: Realm access from incorrect thread. Realm objects can only be accessed on the thread they were created.

### ISSUE THREAD

**Issue by rohitlien** [realm/realm-java#6459]
Hi I have written an intentService to check for data in realm data base and then submit it to the backend and then delete it .

It goes as : 
public class SubmitNBPostService extends IntentService {
    public SubmitNBPostService() {
        super(SubmitNBPostService.class.getName());
    }

    @Override
    protected void onHandleIntent(@Nullable Intent intent) {

        checkForUpdates();

    }

    private void checkForUpdates() {
       List<RealmPostViewData> likePostDataList = RealmHelper.getTypeBasedPostViewData("like");

       if(likePostDataList.size()>0){
            sendLikeData(likePostDataList);
           }
    }

   

    private void sendLikeData(final List<RealmPostViewData> likePostDataList) {
        String likeNbPostUrl = "something"
        likeNbPostUrl = HttpManager.getAbsoluteUrl(likeNbPostUrl);
        if(likePostDataList!=null && likePostDataList.size()>0){
            try {
                JSONObject jsonObject= new JSONObject();
                JSONArray jsonArray = new JSONArray();
                for(int i=0;i<likePostDataList.size();i++){
                    JSONObject j = new JSONObject();
                    if(likePostDataList.get(i)!=null) {
                        RealmPostViewData realmPostViewData = likePostDataList.get(i);
                        j.put("nbId", realmPostViewData.getNbId());
                        j.put("postId",realmPostViewData.getPostid());
                        j.put("likeStatus",realmPostViewData.isLike());
                        j.put("timestamp",realmPostViewData.getTimeStamp());
                        jsonArray.put(j);
                    }
                }
                jsonObject.put("dataList",jsonArray);

                JsonObjectRequest jsonObjReq = new JsonObjectRequest(Request.Method.PUT, likeNbPostUrl, jsonObject, new Response.Listener<JSONObject>() {
                    @Override
                    public void onResponse(JSONObject response) {
                        deletePostViewData(likePostDataList);
                    }
                }, new Response.ErrorListener() {
                    @Override
                    public void onErrorResponse(VolleyError error) {
                        Log.e("Error", "" + error);
                    }
                }) {
                    @Override
                    public Map<String, String> getHeaders() throws AuthFailureError {
                        Map<String, String> params = new HashMap<String, String>();
                        try {
                            params.put("api-key", OustPreferences.get("api_key"));
                            params.put("org-id", OustPreferences.get("tanentid"));
                        } catch (Exception e) {
                            e.printStackTrace();
                        }

                        return params;
                    }
                };
                jsonObjReq.setShouldCache(false);
                jsonObjReq.setRetryPolicy(new DefaultRetryPolicy(15000, 2, 100000f));
                OustSdkApplication.getInstance().addToRequestQueue(jsonObjReq, "first");

            } catch (JSONException e) {
                e.printStackTrace();
            }
        }
    }
    

    public static void deletePostViewData(final List<RealmPostViewData> realmPostViewDataList) {
        Realm backGroundRealm = Realm.getDefaultInstance();
        try {
           
                backGroundRealm.executeTransactionAsync(new Realm.Transaction() {
                    @Override
                    public void execute(Realm realm) {
                        for (RealmPostViewData realmPostViewData : realmPostViewDataList) {
                            realmPostViewData.deleteFromRealm();
                        }
                    }
                });
            
        }catch (Exception e){
            e.printStackTrace();
        }finally {
            backGroundRealm.close();
            //OustSdkTools.closeInitRealm();
        }
    }
}

The problem is i am not able to delete the data when api call finishes.
But then my question is how i am able to get the data when i call RealmHelper.getTypeBasedPostViewData("like");

The method is as :

public static List<RealmPostViewData> getTypeBasedPostViewData(String type) {
        ArrayList<RealmPostViewData> postViewDataList = new ArrayList<>();
Realm realm = Realm.getDefaultInstance();
        try {
            RealmQuery<RealmPostViewData> query = realm.where(RealmPostViewData.class).equalTo("type", type);
            RealmResults<RealmPostViewData> results = query.findAll();

            for (RealmPostViewData cplMediaData : results) {
                postViewDataList.add(cplMediaData);
            }
        }catch (Exception e){
            e.printStackTrace();
        }finally {
            realm.close();
            OustSdkTools.closeInitRealm();
        }
        return postViewDataList;
    }

Can you please explain

**Comment by Zhuinden** [comment]
Which line throws the exception,

**Comment by rohitlien** [comment]
This line : realmPostViewData.deleteFromRealm();

Since reading data didn't create exception , i was wondering why this is happening

**Comment by Zhuinden** [comment]
You probably wanted to use executeTransaction instead of executeTransactionAsync.

**Comment by cmelchior** [comment]
@rohitlien I assume the above answered your question. If not, feel free to re-open this issue, but we would need a sample project in order to debug it.
