### ISSUE TITLE
Support filterable interface on RealmBaseAdapter.

### ISSUE THREAD

**Issue by bmunkholm** [realm/realm-java#646]
As pr. this discussion on Google Groups: 
https://groups.google.com/forum/#!topic/realm-java/KMwalH1sD3Y

This will require being able to move objects between threads. Will at least require https://github.com/realm/realm-java/issues/503 first

**Comment by sahal2080** [comment]
Any workaround in the meantime?

**Comment by johngamarra** [comment]
almost a year, some progress with this feature would be really nice

**Comment by freezy** [comment]
Second that. At least provide a workaround please.

**Comment by freezy** [comment]
After comments from @gpulido and @Saketme in #1736, here's a workaround that works for me:

```java
public abstract class FilterableRealmBaseAdapter<T extends RealmObject> extends ArrayAdapter<T> implements Filterable {

	private final RealmResults<T> mRealmObjectList;
	private List<T> mResults;

	public FilterableRealmBaseAdapter(Context context, @LayoutRes int layout, RealmResults<T> realmObjectList) {
		super(context, layout);
		mRealmObjectList = realmObjectList;
	}

	@Override
	public int getCount() {
		return mResults == null ? 0 : mResults.size();
	}

	@Override
	public T getItem(int position) {
		return mResults == null ? null : mResults.get(position);
	}

	@Override
	public Filter getFilter() {

		return new Filter() {
			private boolean mHasResults = false;

			@Override
			protected FilterResults performFiltering(CharSequence constraint) {
				// do nothing here because it's executed in another thread and Realm really
				// doesn't like treating data from another thread.
				final FilterResults results = new FilterResults();
				results.count = mHasResults ? 1 : 0; // AutoCompleteTextView already hides dropdown here if count is 0, so correct it.
				return results;
			}

			@Override
			protected void publishResults(CharSequence constraint, FilterResults results) {
				// back on the main thread, we can do the query and notify
				if (constraint != null) {
					mResults = performRealmFiltering(constraint, mRealmObjectList);
					mHasResults = mResults.size() > 0;
					notifyDataSetChanged();
				}
			}
		};
	}

	protected abstract List<T> performRealmFiltering(@NonNull CharSequence constraint, RealmResults<T> results);
}
```

Basically you extend this class and implement `performRealmFiltering()`, which is executed on the main thread.

**Comment by johngamarra** [comment]
@freezy could you please provide an example of your workaround?, thanks

**Comment by freezy** [comment]
What's not clear with the code I've posted?

**Comment by johngamarra** [comment]
my bad, it works, thanks

**Comment by VyshnavKR** [comment]
@freezy @johngamarra  Hi, Itried this, but its shown "class is abstract and cannot be instantiated". How do I solve this?

**Comment by freezy** [comment]
As I said, you need to **extend** that class and implement `performRealmFiltering()`. If that isn't clear enough you're probably better off searching at StackOverflow than here.

**Comment by VyshnavKR** [comment]
But MainActivity already extends AppCompatActivity! That's my prob.
And yeah I'm going to Stack that.

**Comment by Zhuinden** [comment]
http://stackoverflow.com/questions/40630322/how-to-implement-filterable-in-realmrecyclerviewadapter/40632613#40632613

**Comment by cmelchior** [comment]
Moved to https://github.com/realm/realm-android-adapters/issues/79. Closing here.
