### ISSUE TITLE
Migration is required when a new Class has been added

### ISSUE THREAD

**Issue by Ishwor-Shrestha** [realm/realm-java#6461]
I get the following error:

`io.realm.exceptions.RealmMigrationNeededException: Migration is required due to the following errors:
    - Class 'CreditCardBankRealm' has been added.
    - Class 'CreditCardRealm' has been added.
`
I thought migration is need only when properties of a class is changed.

**Comment by cmelchior** [comment]
Realm creates a default schema from all Realm model classes it can find in your Java code and then compares those against what is actually in the Realm file.

It seems you added two new Java classes `CreditCardBankRealm` and `CreditCardRealm`.

If you don't want them to be part of the schema you can define a custom schema using `@RealmModule` and the `RealmConfiguration.modules(module)` config option. That way you can avoid the migration warning.

If you want them as part of your schema you need to define a migration step that adds them like here: https://github.com/realm/realm-java/blob/master/examples/migrationExample/src/main/java/io/realm/examples/realmmigrationexample/model/Migration.java#L93

**Comment by Zhuinden** [comment]
Non-sync Realm on Android is using manual migration which means you do need to add all the changes.

**Comment by cmelchior** [comment]
I assume the above answered your question. If not, feel free to re-open this issue.

**Comment by sshanzel** [comment]
Is there  any automatic way that Realm will identy `RealmObject`s which will then be created on the DB itself?

**Comment by happyHou** [comment]
I had the same problem。It is mainly because of RealmMigration#updateSchema currentVersion is equal schemaVersion.I change RealmMigration#updateSchema currentVersion-1 then it work。I miss the document by this Migrate from version 39 to version 40.

**Comment by vipozdn** [comment]
According to [documentation](https://docs.mongodb.com/realm-legacy/docs/java/latest/index.html#migrations) if you want to add a new RealmObject class to schema you have to implement migration which requires two changes to your RealmConfiguration: setting a new schema version, and writing code to perform migration:

`// Example migration adding a new class
public class MyMigration implements RealmMigration {
  @Override
  public void migrate(DynamicRealm realm, long oldVersion, long newVersion) {

     // DynamicRealm exposes an editable schema
     RealmSchema schema = realm.getSchema();

     // Migrate to version 1: Add a new class.
     // Example:
     // public Person extends RealmObject {
     //     private String name;
     //     private int age;
     //     // getters and setters left out for brevity
     // }
     if (oldVersion == 0) {
        schema.create("Person")
            .addField("name", String.class)
            .addField("age", int.class);
        oldVersion++;
     }

     // Migrate to version 2: Add a primary key + object references
     // Example:
     // public Person extends RealmObject {
     //     private String name;
     //     private int age;
     //     @PrimaryKey
     //     private int id;
     //     private Dog favoriteDog;
     //     private RealmList<Dog> dogs;
     //     // getters and setters left out for brevity
     // }
     if (oldVersion == 1) {
        schema.get("Person")
            .addField("id", long.class, FieldAttribute.PRIMARY_KEY)
            .addRealmObjectField("favoriteDog", schema.get("Dog"))
            .addRealmListField("dogs", schema.get("Dog"));
        oldVersion++;
     }
  }
}`
