### ISSUE TITLE
: Fatal signal 7 (SIGBUS), code 2, fault addr 0x926d20c8 in tid 4686

### ISSUE THREAD

**Issue by hiteshkamani** [realm/realm-java#6462]
#### Goal
Need to replace default.real file which is downloaded from server.

#### Actual Results
I downloaded default.realm file from server and downloaded file on path of realm.getPath() and then insert data in to the table and its fatal signal 7 error.

#### Version of Realm and tooling

Realm version(s): 5.9.1"

Realm Sync feature enabled: No

Android Studio version: 3.3.2

Android Build Tools version: 3.3.0

Gradle version: 

Which Android version and device(s): ? MotoG

**Comment by Zhuinden** [comment]
You need to close the Realm on all threads, do the replace, then reopen it.

**Comment by hiteshkamani** [comment]
but i need to replace latest .realm file after user login in app.How can i handle this scenario?? can you please suggest?

**Comment by Zhuinden** [comment]
Yes, close the Realm on all threads, replace the file, then reopen the Realm.

**Comment by cmelchior** [comment]
@hiteshkamani I assume the above answered your question. If not feel free to re-open this issue.
