### ISSUE TITLE
Samsung Galaxy J7, SM-J700F device: Fatal signal 11 (SIGSEGV)

### ISSUE THREAD

**Issue by satutigroove** [realm/realm-java#6463]
Application crash in **Samsung Galaxy J7, SM-J700F device only having Android  version 6.0.1** while inserting data into realm database. In all other devices it's working fine.

#### Actual Results

App crash in one particular device Samsung 6.0.1 , Galaxy J7, SM-J700F

crash exception ;
03-01 18:24:52.871 4253-4253/? A/libc: Fatal signal 11 (SIGSEGV), code 2, fault addr 0x35e23944 in tid 4253
03-01 18:24:52.931 2173-2173/? A/DEBUG: *** *** *** *** *** *** *** *** *** *** *** *** *** *** *** ***
03-01 18:24:52.931 2173-2173/? A/DEBUG: Build fingerprint: 'samsung/j7eltexx/j7elte:6.0.1/MMB29K/J700FXXU4BRL2:user/release-keys'
03-01 18:24:52.931 2173-2173/? A/DEBUG: Revision: '0'
03-01 18:24:52.931 2173-2173/? A/DEBUG: ABI: 'arm'
03-01 18:24:52.931 2173-2173/? A/DEBUG: pid: 4253, tid: 4253, name: groove.feetport  >>> 
03-01 18:24:52.931 2173-2173/? A/DEBUG: signal 11 (SIGSEGV), code 2 (SEGV_ACCERR), fault addr 0x35e23944
03-01 18:24:52.961 2173-2173/? A/DEBUG:     r0 6fa0b784  r1 136d02c0  r2 0026da05  r3 f1906070
03-01 18:24:52.961 2173-2173/? A/DEBUG:     r4 0026da05  r5 136d02c0  r6 6fa0add0  r7 7023cee0
03-01 18:24:52.961 2173-2173/? A/DEBUG:     r8 13508e20  r9 f4ff6500  sl ffee2298  fp ffee220c
03-01 18:24:52.961 2173-2173/? A/DEBUG:     ip f1906070  sp ffee2190  lr 7376a705  pc f4bc07f8  cpsr 000d0030
03-01 18:24:52.971 2173-2173/? A/DEBUG: backtrace:
03-01 18:24:52.971 2173-2173/? A/DEBUG:     #00 pc 000ea7f8  /system/lib/libart.so (art_quick_imt_conflict_trampoline+7)
03-01 18:24:52.971 2173-2173/? A/DEBUG:     #01 pc 02fd3703  /system/framework/arm/boot.oat (offset 0x2fa5000)

#### Version of Realm and tooling

Realm version(s): ? 5.3.1

Realm Sync feature enabled:  No

Android Studio version: 3.2.1

Android Build Tools version: 28.0.3

Gradle version: 3.2.1

Which Android version and device(s):  Samsung 6.0.1 , Galaxy J7, SM-J700F Android version 6.0.1

**Comment by cmelchior** [comment]
@satutigroove Can you provide a sample project demonstrating this issue?

**Comment by satutigroove** [comment]
we can not provide sample project, as this issue occurs in our production app. It occurs only in one particular device i.e.Samsung Galaxy J7, SM-J700F device.

**Comment by mehulsutariya** [comment]
@cmelchior In the issue that I have raised here: https://github.com/realm/realm-java/issues/6362, we also face issues more prominently on Samsung devices, specifically J series.

**Comment by AbhignGit** [comment]
This is issue is Also raised in Samsung galaxy On7 pro,SM-G600FY

**Comment by janet-rivas** [comment]
I'm having the same issue, 
I'm able to replicate Samsung7 Model SM-G930F  Android 7.0  "realm": "^2.26.0",

**Comment by pziecin** [comment]
I had the same problem with ImageReader when I'm using it as a second output in camera 2 API.

ImageReader.newInstance(mPreviewSize.getHeight(), mPreviewSize.getWidth(), ImageFormat.YUV_420_888, 1);

I have changed maxImages from 1 to 10 and problems disappear but then I returned to first version 10 -> 1 and everything is ok. Can u explain to me this?

**Comment by cmelchior** [comment]
@satutigroove Is this still a problem? Are you using encryption? Because then this might be fixed by Realm Java 6.0.1?

**Comment by mehulsutariya** [comment]
@cmelchior We upgraded our app to Realm java 6.0.1, but we are still seeing errors in Samsung Devices primarily.

https://github.com/realm/realm-java/issues/6665

**Comment by cmelchior** [comment]
Since the underlying implementation changed in Realm Java 7.0.0. I'm closing this as outdated. Please re-open if you are still seeing this on 7.0.2 and above.
