### ISSUE TITLE
PermissionManager.getPermissions() returns wrong result

### ISSUE THREAD

**Issue by pavelpoley** [realm/realm-java#6465]
I have strange behavior or i don't understand how to use this api, i am trying to get specific  permission for current user to check if he can manage this Realm.

The problem is on first start after installing the app when i call this method, it return only system permissions (one more permission is exist and missing in the result, i checked in realm studio) so my query `permissions.where().endsWith("path", projectName).findFirstAsync()` returns `null`, **when we call second time this method all work fine**.

I added some test iterations, what i see that after `onSuccess(@NonNull RealmResults<Permission> permissions)` is called:
first called `'iteration-1'` with only 3 system permissions, 
then after some delay is called `'iteration-2'` `onChange `with 4 permission(correct result)

`PermissionManager.getPermissions()` doesn't need to return all result after sync with platform?
I can use `addChangeListener` but it will work only for first time, the second time `onChange `will not triggered 

How i need to fetch permissions or there are another way?

```
`public void canManage(PermissionManager pm, ResultCallback<Boolean> callback) {

        if (currentUser() != null) {

            String projectName = getProjectName();

            pm.getPermissions(new PermissionManager.PermissionsCallback() {

                @Override
                public void onSuccess(@NonNull RealmResults<Permission> permissions) {
                
                   //for testing start ----------------------------------

                    permissions.addChangeListener(new RealmChangeListener<RealmResults<Permission>>() {
                        @Override
                        public void onChange(@NonNull RealmResults<Permission> permissionss) {
                            for (Permission permission : permissionss) {
                                Log.d(TAG, "onSuccess: iteration-1 >>>>>>>>>>> " + permission.toString());
                            }
                        }
                    });

                    for (Permission permission : permissions) {
                        Log.d(TAG, "onSuccess: iteration-2 >>>>>>>>>>> " + permission.toString());
                    }
                    //for testing end ------------------------------------

                    if (permissions.isLoaded()) {

                        Permission perm = permissions.where().endsWith("path", projectName).findFirst();

                      if (perm != null) {
                            callback.onSuccess(perm.mayManage());
                        } //else on error
                    }

                }

                @Override
                public void onError(@NonNull ObjectServerError error) {
                    callback.onError(error.getLocalizedMessage());
                }
            });
        }

    }`
```

Using Realm 5.9.1 and full synchronization

**Comment by Zhuinden** [comment]
Just don't use findFirstAsync like ever, use findAllAsync

**Comment by pavelpoley** [comment]
Can i ask why?:) i mean findAllAsync guaranties that i receive correct result?
Also why to call getPermissions() then query the permissions then add changeListener, i thought the getPermissions() method need to return permissions from server?

**Comment by Zhuinden** [comment]
Good news is that with Realm-Java 6.0.0, this question is obsolete, because the PermissionManager was removed and replaced.
