### ISSUE TITLE
How can I generate a Realm file that I can bundle with the project?

### ISSUE THREAD

**Issue by dev-JE02** [realm/realm-java#6467]
I basically have a lot of content that need to be already available on the app upon first launch. I had a solution to download the content and then save them locally which took like 10 seconds for 40 items. We have 250 items to download each with thousands of subitems. Is it possible to generate a Realm file somewhere so that we can download it and bundle into the project?

**Comment by GWStuartClift** [comment]
You could use [assetFile(String assetFile)](https://realm.io/docs/java/5.9.1/api/io/realm/RealmConfiguration.Builder.html#assetFile-java.lang.String-) method on `RealmConfiguration.Builder` to open a  realm bundled in your assets if this data does not change. 
> Is it possible to generate a Realm file somewhere so that we can download it and bundle into the project?

Yes, just download it and open the path, though you may have issues if your schema changes. The *officially* recommended solution would probably be to use their [Realm Sync](https://realm.io/products/realm-platform/) platform.

**Comment by cmelchior** [comment]
Yes, you can bundle the file using the `assetFile` API mentioned above.

Creating the file itself can be done in either of two ways:

1) Create a small Android project that generates it for you. You can then download the file from that project.

2) Create the file manually using Realm Studio.

For anything non-trivial, I would recommend having a small project that can generate the Realm file. Unfortunately, we do not have a pure JVM API yet, so it will need to be an Android project.

**Comment by Zhuinden** [comment]
(or a NodeJS project 🤔 )

**Comment by cmelchior** [comment]
Yes, that is also an option 😄

**Comment by dev-JE02** [comment]
Thank you guys
