### ISSUE TITLE
AndroidStudio could not resolve io.realm:realm-gradle-plugin:5.9.1

### ISSUE THREAD

**Issue by ykbjson** [realm/realm-java#6471]
FAILURE: Build failed with an exception.

* What went wrong:
A problem occurred configuring root project 'maxbrowser'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not resolve io.realm:realm-gradle-plugin:5.9.1.
     Required by:
         project :
      > Could not resolve io.realm:realm-gradle-plugin:5.9.1.
         > Could not get resource 'https://jcenter.bintray.com/io/realm/realm-gradle-plugin/5.9.1/realm-gradle-plugin-5.9.1.pom'.
            > Could not GET 'https://jcenter.bintray.com/io/realm/realm-gradle-plugin/5.9.1/realm-gradle-plugin-5.9.1.pom'. Received status code 502 from server: Bad Gateway

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

CONFIGURE FAILED in 1s
ERROR: Could not GET 'https://jcenter.bintray.com/io/realm/realm-gradle-plugin/5.9.1/realm-gradle-plugin-5.9.1.pom'. Received status code 502 from server: Bad Gateway
---------------------------------------------------------------------------------
project level build.gradle 
buildscript {
    repositories {
        google()
        jcenter()
        maven { url 'https://dl.bintray.com/ykbjson/maven' }
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:3.2.1'
        //realm
        classpath "io.realm:realm-gradle-plugin:5.9.1"
        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
        maven { url 'https://dl.bintray.com/ykbjson/maven' }
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}

**Comment by Zhuinden** [comment]
jCenter is dying, just add `mavenCentral` to your build.gradle as repository ABOVE jcenter

**Comment by cmelchior** [comment]
JCenter had an outage earlier today, that is probably what you experienced. Closing
