### ISSUE TITLE
Make it possible to use in-memory realm without Android Context

### ISSUE THREAD

**Issue by jstefanowski** [realm/realm-java#6474]
Currently, in order to write proper unit tests that could be executed outside of Android device and without Robolectric (which has its own issues) we need to either mock all calls to the database or create fake databases that would be used instead Realm. 

If there could be an option to i.e. setup in-memory realm which doesn't need Context for initialization then writing unit tests would be much easier. No need for mocks or creating fakes, possible to test transactions, etc. I understand why context is needed for regular Realm but I think that in-memory version could be used without it.

**Comment by Zhuinden** [comment]
Actually the real problem is that the Realm notification mechanism depends on Android Looper in C++ code.

**Comment by bmunkholm** [comment]
Unfortunately, we are not going to pursue this until we make it generally support standalone JVM.
