### ISSUE TITLE
Is there a way to sort `RealmResults` by two columns?

### ISSUE THREAD

**Issue by zsavely** [realm/realm-java#648]
I am trying to sort `RealmResults` by two columns:
```java
RealmResults<User> results = realm.where(User.class).equalTo("relevant", true).findAll();
results.sort("balance", RealmResults.SORT_ORDER_ASCENDING);
results.sort("visible", RealmResults.SORT_ORDER_ASCENDING);
setListViewData(getActivity(), results, true);
```
But in the listview the results are only sorted by the column `visible`.
So is there a way to sort by two columns? 

I am using version 0.75.1.

**Comment by cmelchior** [comment]
This was released with 0.77.0

**Comment by njzk2** [comment]
It would be nice if it was at least indicated in the documentation that the sort is not stable.

**Comment by cmelchior** [comment]
@njzk2 Yes we should. That is an unfortunate oversight.

**Comment by kneth** [comment]
@njzk2 Notice that objects in a Realm are unordered while objects in a `RealmResults` are ordered. The in-place `RealmResults.sort()` is stable (according to the classical definition: http://en.wikipedia.org/wiki/Sorting_algorithm#Stability).

To test/illustrate this, I have expanded the unit tests - please take a look at #778. We should definitely update the documentation to explain this clearly.

**Comment by njzk2** [comment]
@kneth isn't that in contradiction with the initial report by @zsavely? Shouldn't stability inherently allow multiple successive sorts?

**Comment by kneth** [comment]
@njzk2 Not really. The initial report was using single field sorting twice which is sorting two different lists. After that report, we have implemented multi-field sorting.
