### ISSUE TITLE
Realm Fails to compact when file size is 1476395008

### ISSUE THREAD

**Issue by abhi-scenedoc** [realm/realm-java#6483]
#### Goal
Trying to compact a large realm file 

#### Actual Results
ERROR: 
Caused by: io.realm.exceptions.RealmError: Unrecoverable error. mmap() failed: Out of memory size: 1476395008 in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101
        at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
        at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:184)
        at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:254)
        at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:244)
        at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:319)
        at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:282)
        at io.realm.Realm.getDefaultInstance(Realm.java:332)

#### Steps & Code to Reproduce
Hi,

I just want to ask if there is a way to compact a realm file of size 1476395008 bytes. The Realm.compactRealm() is failing with 

We are using encrypted realm file.

I can share a snippet of code I used to blow up the realm file to 1476395008 bytes. 

Here is the snippet. 
```
GlobalScope.launch(Dispatchers.Main) {
           //some ui manipulation here
          // I used x=10000 and ran it for 2 rounds til completion to get the file size to 1476395008 bytes.
          //The Note RealmObject is simple enough, it has a primary key and few other fields which I am 
         //not populating.
            async(Dispatchers.IO) {
                for (i in 0..x) {
                    Realm.getDefaultInstance().executeTransaction {
                        val note = Note()
                        note.objectId = Note.nextObjectId(it)
                        note.title = "testing"
                        it.copyToRealmOrUpdate(note)
                    }
                }
            }.await()
          //some ui manipulation 
}
```

Let me know if you require any other information. 

#### Version of Realm and tooling

Realm version(s): 4.3.1

Realm Sync feature enabled: No

Android Studio version: 3.2.1

Android Build Tools version: 28.0.3

Gradle version: 4.6

Which Android version and device(s): Note 8, Android 8.0

**Comment by abhi-scenedoc** [comment]
Bump

**Comment by jasper-chan** [comment]
Is there an update/response on this particular matter? This is a serious problem for us as customers may lose data due to the application being unable to launch

**Comment by jasper-chan** [comment]
Bump

**Comment by Zhuinden** [comment]
I don't know of a way to open a Realm file with a file size that exceeds the available RAM. 😲 

As you can see, it's on my wishlist too for what Realm is ought to support: https://old.reddit.com/r/androiddev/comments/bgv2be/realm_is_to_be_acquired_by_mongodb_the/eloxfdg/

**Comment by bmunkholm** [comment]
@abhi-scenedoc As Zhuinden says - there is no way to do that short of moving the file to a desktop with sufficient memory and compact there.
