### ISSUE TITLE
In the Sync Docs, RealmChangeListener() example is not valid

### ISSUE THREAD

**Issue by zeeshanz** [realm/realm-java#6484]
The example at https://realm.io/docs/java/latest/#realm-notifications is missing a closing bracket and couldn't compile, plus it doesn't work even if you put the bracket there, and gives error: 'anonymous io.realm.RealmChangeListener' to 'io.realm.RealmChangeListener<io.realm.RealmResults<com.fastenal.datamanager.model.Person>...

<img width="1055" alt="Screen Shot 2019-04-09 at 2 01 06 AM" src="https://user-images.githubusercontent.com/4508321/55776962-5fb25000-5a6c-11e9-9fa1-cb26894bbe73.png">

Realm version(s): 5.10.0

Android Studio version: 3.3.2

Android Build Tools version: 28

Gradle version: 5.3.1

**Comment by Zhuinden** [comment]
It's missing the `<Customer>`.

**Comment by zeeshanz** [comment]
I have tried many things, including lambda, before posting this bug report. Realm docs have overwhelmingly obsolete and non-working examples, and this is just one of them. All I am pointing out here is to update the doc with working code.

**Comment by bmunkholm** [comment]
@zeeshanz Thanks for posting this. We should certainly get that fixed. If you find other examples you find outdated please do let us know and we will get them fixed.
Thanks!

**Comment by cmelchior** [comment]
Fixed
