### ISSUE TITLE
Potential bug in StoreEncryptionPassword  example

### ISSUE THREAD

**Issue by marccala** [realm/realm-java#6485]
Hello Realm team,

I think i found an error in your StoreEncryptionPassword  example.

File:
realm-java / examples / StoreEncryptionPassword / src / main / java / realm / io / storeencryptionpassword / Store.java 

As is:
new byte[Integer.SIZE + iv.length + encryptedKeyForRealm.length];
To: be:
new byte[Integer.BYTES+ iv.length + encryptedKeyForRealm.length];

Explanation:
Integer.Size  returns the number of BITS (ie. 32) but iv.length and encryptedKeyForRealm.length return the number of BYTES

Regards,
Marc

**Comment by bmunkholm** [comment]
Thanks @marccala for reporting this. We will get that fixed.

**Comment by cbush** [comment]
@bmunkholm Does this example still exist somewhere?

**Comment by bmunkholm** [comment]
This is really on an unsupported branch I figured: https://github.com/realm/realm-java/blob/feature/example/store_password/examples/StoreEncryptionPassword/src/main/java/realm/io/storeencryptionpassword/Store.java

It's fixed now.
