### ISSUE TITLE
error:Valid model classes must either extend RealmObject or implement RealmModel. Why?

### ISSUE THREAD

**Issue by vvvv0527** [realm/realm-java#6488]
![image](https://user-images.githubusercontent.com/25765907/55859944-b40d1b00-5ba5-11e9-96dd-cbb62ae61565.png)
I did,but it's still wrong

**Comment by cmelchior** [comment]
Maybe it is a build cache problem. Did you try to do a clean build? `./gradlew clean assemble` ?

**Comment by SergeyAppDroid** [comment]
Do I have a similar problem? What is the solution? How to solve this problem?

**Comment by SergeyAppDroid** [comment]
@vvvv0527 Do I have a similar problem? What is the solution? How to solve this problem?
