### ISSUE TITLE
Query based realm - OrderedCollectionChangeSet wrong behavior

### ISSUE THREAD

**Issue by pavelpoley** [realm/realm-java#6490]
`onChange `give wrong result, i am using `query based` realm with `OrderedCollectionChangeSet `, i am sending some "`RealmOffer`" from one device and fetch it in another device, on first start the realm return wrong result, on second start(app restart) return correct result.

Log from first launch:
onChange: isCompleteResult false size 0
onChange: isCompleteResult true size 0 < wrong result but `isCompleteResult  `is `true`
onChange: isCompleteResult false size 1 <= correct result but `isCompleteResult `is `false`

Log from second launch:
onChange: isCompleteResult false size 0
onChange: isCompleteResult true size 1 < correct result

To reproduce it is important to close the app from task manager.

- Upload some object to query based realm
- close the app
- Delete or add some object from realm studio in the same class
- open the app and fetch result, on first run you will see old result, on second start new result

i think it is wrong behavior, but maybe i am wrong.

```
`Realm.getInstanceAsync(configurationManager.getSharedConfiguration(), new Realm.Callback() {
                @Override
                public void onSuccess(@NonNull Realm realm) {//todo close realm

                    RealmResults<RealmOffer> realmResults = realm.where(RealmOffer.class)
                            .equalTo(RealmOffer.FIELD_TARGET_EMAIL, email)
                            .equalTo(RealmOffer.FIELD_IS_ACCEPTED, false)
                            .findAllAsync();

                    realmResults.addChangeListener(new OrderedRealmCollectionChangeListener<RealmResults<RealmOffer>>() {
                        @Override
                        public void onChange(@NonNull RealmResults<RealmOffer> realmOffers, @NonNull OrderedCollectionChangeSet changeSet) {

                            Log.d(TAG, "onChange: isCompleteResult " + changeSet.isCompleteResult() +" size " + realmOffers.size());

                            if (changeSet.isCompleteResult()) {
                                    //handling result
                            }
                        }
                    });

                }

                @Override
                public void onError(@NonNull Throwable exception) {
                    Log.d(TAG, "onError: findOffers " + exception.getLocalizedMessage());
                    callback.onError(exception.getLocalizedMessage());
                }
            });`
```

Realm: 5.10.0

**Comment by Chesteer89** [comment]
Got same error on Realm 5.14.0.

**Goal**
OrderedRealmCollectionChangeListener works fine after first synchronization.

**Actual Results**
After first synchronization Realm listeners doesn't fired.

**Steps & Code to Reproduce**
Simple app - create OrderedRealmCollectionChangeListener, add some dummy object to database (synced). Close app.
Add new dummy object via RealmStudio. 
Run app.

**You'll not be notified of any changes.** 

Add another dummy object - You'll be notified about both objects.

**Comment by clementetb** [comment]
Closing this issue as query-based realms are no longer supported and due to inactivity.
