### ISSUE TITLE
Realm.getDefaultInstance() error:  Native method not found: io.realm.internal.SharedRealm.nativeCancelTransaction:(J)V

### ISSUE THREAD

**Issue by youlongsam** [realm/realm-java#6508]
# main(1)

java.lang.UnsatisfiedLinkError

Native method not found: io.realm.internal.SharedRealm.nativeCancelTransaction:(J)V

io.reactivex.exceptions.UndeliverableException:java.lang.UnsatisfiedLinkError: Native method not found: io.realm.internal.SharedRealm.nativeCancelTransaction:(J)V
--
2 io.reactivex.e.a.a(SourceFile:366)
3 ......
4 Caused by:
5 java.lang.UnsatisfiedLinkError:Native method not found: io.realm.internal.SharedRealm.nativeCancelTransaction:(J)V
6 io.realm.internal.SharedRealm.nativeCancelTransaction(Native Method)
7 io.realm.internal.SharedRealm.cancelTransaction(SourceFile:255)
8 io.realm.a.d(SourceFile:333)
9 io.realm.au.d(SourceFile:127)
10 io.realm.au.a(SourceFile:379)
11 io.realm.au.b(SourceFile:317)
12 io.realm.au.a(SourceFile:266)
13 io.realm.RealmCache.a(SourceFile:145)
14 io.realm.au.o(SourceFile:211)
15 com.kwai.m2u.manager.data.realm.module.impl.DownloadDao.query(SourceFile:55)
16 com.kwai.m2u.manager.download.M2UDownloadManager.isDownloaded(SourceFile:31)
17 com.kwai.m2u.manager.download.MultiDownloadTask.isAllDownloaded(SourceFile:144)
18 com.kwai.m2u.manager.download.MultiDownloadManager.isAllDownloaded(SourceFile:23)
19 com.kwai.m2u.manager.download.M2UMultiDownloadManager.mvResourceAllDownloaded(SourceFile:46)
20 com.kwai.m2u.helper.o.a.a(SourceFile:44)
21 com.kwai.m2u.main.a.g.a(SourceFile:234)
22 com.kwai.m2u.main.a.g.b(SourceFile:37)
23 com.kwai.m2u.main.a.g$1.a(SourceFile:81)
24 com.kwai.m2u.main.a.g$1.onSuccess(SourceFile:65)
25 com.kwai.m2u.module.impl.MvModuleImpl$1.accept(SourceFile:82)
26 com.kwai.m2u.module.impl.MvModuleImpl$1.accept(SourceFile:77)
27 io.reactivex.internal.observers.LambdaObserver.onNext(SourceFile:63)
28 io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.drainNormal(SourceFile:200)
29 io.reactivex.internal.operators.observable.ObservableObserveOn$ObserveOnObserver.run(SourceFile:252)
30 io.reactivex.a.b.b$b.run(SourceFile:109)
31 android.os.Handler.handleCallback(Handler.java:733)
32 android.os.Handler.dispatchMessage(Handler.java:95)
33 android.os.Looper.loop(Looper.java:136)
34 android.app.ActivityThread.main(ActivityThread.java:5120)
35 java.lang.reflect.Method.invokeNative(Native Method)
36 java.lang.reflect.Method.invoke(Method.java:515)
37 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:818)
38 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:634)
39 dalvik.system.NativeStart.main(Native Method)

**Comment by Zhuinden** [comment]
Realm version? Android Studio version? Is it proguarded? Is it using R8/D8?

**Comment by bmunkholm** [comment]
@youlongsam Please use the issue template when posting issues so we get all relevant info.

**Comment by bmunkholm** [comment]
Closing due to no response.
Please reopen when/if you can provide more details.
