### ISSUE TITLE
java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.myapplication/com.example.myapplication.MessengerActivity}: java.lang.IllegalStateException: Can't commit a non-existing write transaction in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 144 –

### ISSUE THREAD

**Issue by kyodgorbek** [realm/realm-java#6510]
I am developing a new app but I am getting the following exception after initializing realm

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.myapplication/com.example.myapplication.MessengerActivity}: java.lang.IllegalStateException: Can't commit a non-existing write transaction in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 144
        at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:3102)
        at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:3237)
        at android.app.servertransaction.LaunchActivityItem.execute(LaunchActivityItem.java:81)
        at android.app.servertransaction.TransactionExecutor.executeCallbacks(TransactionExecutor.java:135)
        at android.app.servertransaction.TransactionExecutor.execute(TransactionExecutor.java:95)
        at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1929)
        at android.os.Handler.dispatchMessage(Handler.java:106)
        at android.os.Looper.loop(Looper.java:209)
        at android.app.ActivityThread.main(ActivityThread.java:7021)
        at java.lang.reflect.Method.invoke(Native Method)
        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:486)
        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:872)
     Caused by: java.lang.IllegalStateException: Can't commit a non-existing write transaction in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 144
        at io.realm.internal.OsSharedRealm.nativeCommitTransaction(Native Method)
        at io.realm.internal.OsSharedRealm.commitTransaction(OsSharedRealm.java:273)
        at io.realm.BaseRealm.commitTransaction(BaseRealm.java:416)
        at io.realm.Realm.commitTransaction(Realm.java:145)
        at com.example.myapplication.MessengerActivity.onCreate(MessengerActivity.java:120)

below my code

public class RealmUtility {
       private static final int SCHEMA_V_PREV = 1;// previous schema version
        private static final int SCHEMA_V_NOW = 2;// change schema version if any change happened in schema

        public static int getSchemaVNow() {
            return SCHEMA_V_NOW;
        }

        public static RealmConfiguration getDefaultConfig() {
            return new RealmConfiguration.Builder()
                    .schemaVersion(SCHEMA_V_NOW)
                    .deleteRealmIfMigrationNeeded()// if migration needed then this methoud will remove the existing database and will create new database
                    .build();
        }
}

public class RealmMigrations implements RealmMigration {

    private static final int SCHEMA_V_PREV = 1;
    private static final int SCHEMA_V_NOW = 2;
    @Override
    public void migrate(DynamicRealm realm, long oldVersion, long newVersion) {
        final RealmSchema realmSchema = realm.getSchema();

        if (oldVersion == 1) {
             RealmObjectSchema saveMessage =
                    realmSchema.get("SaveMessage");
            if(saveMessage==null){
                saveMessage=realmSchema.create("SaveMessage");}
            saveMessage.addField("mId", int.class);
            saveMessage.addField("mUserName", String.class);
            saveMessage.addField("mContent", String.class);
            saveMessage.addField("mCreatedAt", Date.class);
            saveMessage.addField("mRightMessage", boolean.class);
            saveMessage.addField("mPictureString", String.class);
            saveMessage.addField("mType", String.class);
            // all field add here similarly
            oldVersion++;
        }
    }

    public static RealmConfiguration getDefaultConfig() {
        return new RealmConfiguration.Builder()
                .schemaVersion(SCHEMA_V_NOW)
                .migration(new RealmMigrations())
                .build();
    }
}

below realm initialization

realm = Realm.getInstance(RealmUtility.getDefaultConfig());
        realm.beginTransaction();

        User userModel =  realm.createObject(User.class);

        Integer userId = Integer.valueOf("0");
        String userName = "Michael";

        userModel.setId(userId);
        userModel.setName(userName);
        //userModel.setIcon("icon");
        Integer userId1 = Integer.valueOf("1");
        String userName1 = "Lily";

        userModel.setId(userId1);
        userModel.setName(userName1);

        realm.commitTransaction();

        RealmResults<User> userModels = realm.where(User.class).findAll();
        for (User user : userModels) {
            Integer getId = Integer.valueOf(user.getId());
            String getName = user.getName();
            realm.commitTransaction();

        }

        SaveMessage saveModel = realm.createObject(SaveMessage.class);

       Integer saveId = Integer.valueOf("0");
       String savedName = "Michael";
        Integer saveIds = Integer.valueOf("1");
        String savedNames = "Lily";
        saveModel.setmId(saveId);
        saveModel.setmUsername(savedName);
        saveModel.setmContent("content");
        saveModel.ismRightMessage("isRightMessage");
        Date now = Calendar.getInstance().getTime();
        saveModel.setDate(now);
        realm.commitTransaction();

        RealmResults<SaveMessage> savesModels = realm.where(SaveMessage.class).findAll();
        for (SaveMessage saveMessage : savesModels) {
            Integer getId = saveMessage.getId();
            String getName = saveMessage.getUsername();
            String getContent = saveMessage.getContent();
            Date date = saveMessage.getDate();
            String rightMessage = String.valueOf(saveMessage.ismRightMessage());

            realm.commitTransaction();

        }

below SaveMessages model class
@RealmClass
public class SaveMessage extends RealmObject {

    private int mId;
    private String mUsername;
    private String mContent;
    private Date mCreatedAt;
    private boolean mRightMessage;
    private String mPictureString;
    private String mType;

    public SaveMessage(int id, String username, String content, Date createdAt, boolean isRightMessage) {
        mId = id;
        mUsername = username;
        mContent = content;
        mCreatedAt = createdAt;
        mRightMessage = isRightMessage;
    }

    public SaveMessage() {

    }

    public int getId() {
        return mId;
    }

    public String getUsername() {
        return mUsername;
    }

    public String getContent() {
        return mContent;
    }

    public Date getDate() {
        return mCreatedAt;
    }

    public void setDate(Date createdAt) {

        mCreatedAt = createdAt;
    }

    public boolean ismRightMessage() {
        return mRightMessage;
    }

    public int getmId() {
        return mId;
    }

    public void setmId(int mId) {
        this.mId = mId;
    }

    public String getmUsername() {
        return mUsername;
    }

    public void setmUsername(String mUsername) {
        this.mUsername = mUsername;
    }

    public String getmContent() {
        return mContent;
    }

    public void setmContent(String mContent) {
        this.mContent = mContent;
    }

    public boolean ismRightMessage(String isRightMessage) {
        return mRightMessage;
    }

    public void setmRightMessage(boolean mRightMessage) {
        this.mRightMessage = mRightMessage;
    }

    public String getPictureString() {
        return mPictureString;
    }

    public void setPictureString(String pictureString) {
        mPictureString = pictureString;
    }

    public String getType() {
        return mType;
    }

    public void setType(String type) {
        mType = type;
    }

}

below User.java model class
RealmClass
public class User extends RealmObject implements IChatUser {
    Integer id;
    String name;
    @Ignore
    Bitmap icon;

    public User() {
    }

    public User(int id, String name, Bitmap icon) {
        this.id = id;
        this.name = name;
        this.icon = icon;
    }

    @Override
    public String getId() {
        return this.id.toString();
    }

    @Override
    public String getName() {
        return this.name;
    }

    public void setId(Integer id) {
        this.id = id;
    }

    public void setName(String name) {
        this.name = name;
    }

    @Override
    public Bitmap getIcon() {
        return this.icon;
    }

    @Override
    public void setIcon(Bitmap icon) {
        this.icon = icon;
    }
}

**Comment by Zhuinden** [comment]
The error message specifically says that the problem is that you are calling `commitTransaction()`, without having called `beginTransaction()` beforehand.

Consider using `realm.executeTransaction` which basically calls `begin` and `commit` for you around the block you provide.

**Comment by kyodgorbek** [comment]
@Zhuinden what is your suggestion then

**Comment by Zhuinden** [comment]
Don't call `commitTransaction()` without having called `beginTransaction()`, or use `executeTransaction` in place of begin/commit calls
