### ISSUE TITLE
Realm.init without ApplicationContext

### ISSUE THREAD

**Issue by dd-david** [realm/realm-java#6512]
**What happened if I call Realm.init(without applicationContext)?**

I encountered some native crashes.
Is there any problem with Realm.init() without applicationContext?

**Comment by Zhuinden** [comment]
What are you passing its place, `null`?

**Comment by dd-david** [comment]
@Zhuinden 
I put others, such as serviceContext, as parameter.

**I wanna know if there is any side-effects without using applicationContext?**
For instance, 
```
contextA | initialize Realm.init(contextA) 
contextA(parallel) | Realm.getInstance() > use it > close > contextA destroyed
contextB(parallel) | Realm.getInstance() > use it > (what happened? no issue?)
```

**Comment by cmelchior** [comment]
I assume the question has been answered. So closing
