### ISSUE TITLE
All data wiped out after update app from Google Play

### ISSUE THREAD

**Issue by okq91** [realm/realm-java#6518]
I have changed Realm schema and published new release on google play,
When update App from internal test on google play all data has been deleted.

Realm data shouldn't be deleted since i have added the new schema to my realm migration without use deleteRealmIfMigrationNeeded() 

Realm version: 5.9.1

Android version: various versions 

Android device: various devices.

Realm Sync feature enabled: No

Android Studio version: 3.2

Android Build Tools version: 3.3.2

Realm configuration:

```
 RealmConfiguration realmConfiguration;
        int newVersion = 3;
        realmConfiguration = new RealmConfiguration.Builder()
                .name(Realm.DEFAULT_REALM_NAME)
                .schemaVersion(newVersion)
                .migration(new MyRealmMigration())
                .build();
        Realm.setDefaultConfiguration(realmConfiguration);
```

MyRealmMigration as below:

```
 val schema = realm.schema
        when (oldVersion.toInt()) {
            1 -> {
                schema.create("Source")
                        .addField("id", String::class.java).addPrimaryKey("id")
                        .addField("name", String::class.java)
                        .addField("thumb", String::class.java)
                        .addField("categoryID", String::class.java)
                        .addField("isSelected", Boolean::class.java)
            }
            2 -> {

                val bSchema = schema.get("Source")
                bSchema?.renameField("isSelected", "isSubscribed");
                schema.create("ContentData")
                        .addField("id", String::class.java).addPrimaryKey("id")
                        .addField("title", String::class.java)
                        .addField("body", String::class.java)
                        .addField("type", String::class.java)
                        .addField("sourceUrl", String::class.java)
                        .addField("isBreaking", Boolean::class.java).setNullable("isBreaking", true)
                        .addField("timestamp", Long::class.java).setNullable("timestamp", true)
                        .addField("isSelected", Boolean::class.java)
                        .addRealmObjectField("featuredImage",
                                schema.create("FeaturedImage")
                                        .addField("url", String::class.java)
                                        .addField("isVideo", Boolean::class.java).setNullable("isVideo", true))
                        .addRealmObjectField("source", bSchema)
            }
        }
```

**Comment by Zhuinden** [comment]
The  `when` statement is not a good idea, because you won't fall-through to 2 if you came from 0.

**Comment by okq91** [comment]
Thank you @Zhuinden I will change it to if statement, but i think the migration worked properly otherwise application wouldn't work and will crash after update,
Anyway i have updated from version 2 to 3, so case 2 must be evaluated without delete data right?

**Comment by Zhuinden** [comment]
If you pass a migration, then it won't just delete data unless you are calling `deleteRealm` elsewhere

**Comment by okq91** [comment]
I'm sure that nowhere in my app calling deleteRealm

**Comment by okq91** [comment]
@Zhuinden This issue still not fixed do you have any suggestion?

**Comment by Zhuinden** [comment]
Are you sure you are not setting a configuration in some other place that accidentally sets `.deleteIfMigrationNeeded`?

**Comment by okq91** [comment]
Yes I'm sure, my Realm migration as mentioned above without set .deleteIfMigrationNeeded 
This code were working fine on old version of Realm 4.0.0, I think this issue has been produced on new version  5.9.1.

**Comment by cmelchior** [comment]
Realm is not deleting data at any point unless `deleteIfMigrationNeeded` is set, so my guess is that something else is happening. Perhaps you are accessing another default Realm than the one you expect, which would look like data has been deleted. 

But that isn't clear from the code you posted. You can see where the Realm is located by calling either `realm.getPath()` or `RealmConfiguration.getPath()`

**Comment by cmelchior** [comment]
Closing as I assume the question has been answered.
