### ISSUE TITLE
realm 如果模型定义在两个lib module中各自定义realm model模型,将无法使用

### ISSUE THREAD

**Issue by axuan2015** [realm/realm-java#6519]
#### Version of Realm and tooling

Realm version(s): ?

Realm Sync feature enabled: Yes/No

Android Studio version: ?

Android Build Tools version: ?

Gradle version: ?

Which Android version and device(s): ?

**Comment by axuan2015** [comment]
ealm 如果模型定义在两个lib module中各自定义realm model模型,将无法使用 #6519

**Comment by bmunkholm** [comment]
Sorry, we only do support in English.
