### ISSUE TITLE
asLiveData is being seen as unresolved reference.

### ISSUE THREAD

**Issue by abayomiAkanji** [realm/realm-java#6520]
Hi everyone, I am implementing `LiveData` with `RealmDB` but I have issue resolving the reference for `asLiveData` method in the `Dao` class. Here is where I'm calling the method  `**asLiveData**(mRealm.where(objectToFetch::class.java).findAllAsync())`

Below is the class implementation I did for it as seen in [here](https://github.com/ericmaxwell2003/android-persistence/blob/master/app/src/main/java/com/example/android/persistence/codelab/realmdb/utils/Realm%2BDao.kt) however, I couldn't resolve the reference.

```
@file:JvmName("RealmUtils") // pretty name for utils class if called from

import io.realm.Realm
import io.realm.RealmModel
import io.realm.RealmResults

fun Realm.outreach(): OutreachDao = OutreachDao(this)

fun <T:RealmModel> RealmResults<T>.asLiveData() = LiveRealmData<T>(this)
```

I would appreciate your assistance.

**Comment by bmunkholm** [comment]
As mentioned in the issue template, we use this repo for bug reports and feature requests. For questions about how to use realm, we defer to [StackOverflow](http://stackoverflow.com/questions/ask?tags=realm), where we monitor the `realm` tag. Or you can ask in our [Forum](https://forums.realm.io/c/java)

Thanks for your help!
