### ISSUE TITLE
Unrecoverable error. Crash of other process detected, session restart required

### ISSUE THREAD

**Issue by JoyHong** [realm/realm-java#6528]
Crash when invoke beginTransaction in thread.

# pool-9-thread-1(9619)

io.realm.exceptions.RealmError

Unrecoverable error. Crash of other process detected, session restart required in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 126

#### Version of Realm and tooling

Realm version(s): 5.10.0

Realm Sync feature enabled: No

Android Studio version: 3.2

Android Build Tools version:  3.2.1

Gradle version: 4.9

Which Android version and device(s):  BNTV400，Android 4.0.4,level 15

**Comment by cmelchior** [comment]
Also reported here: https://github.com/realm/realm-js/issues/697

@JoyHong 
Is this something you can reproduce?

**Comment by kylin17** [comment]
Also encountered the same problem.
``
io.realm.exceptions.RealmError: Unrecoverable error. Crash of other process detected, session restart required in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 126
	at io.realm.internal.OsSharedRealm.nativeBeginTransaction(Native Method)
	at io.realm.internal.OsSharedRealm.beginTransaction(Unknown Source)
``

**Comment by JoyHong** [comment]
@cmelchior 

i can't reproduce it, i find this issue on my buggly reports.

**Comment by bmunkholm** [comment]
Closing as we can't get progress without a way to reproduce this. If you still experience this with the newest version, please create a new issue, and we will see if there is anything we can learn from that. Thanks!
