### ISSUE TITLE
Realm with different configurations

### ISSUE THREAD

**Issue by pavelpoley** [realm/realm-java#6532]
We need to enable or disable `fullSynchronization()` based on some circumstances.

For example:

```
private SyncConfiguration createSyncConfiguration(String projectPath, boolean isExist, boolean enableSync) {
  
        String path = "/" + projectPath;
        String url = AppConsts.REALM_URL + path;

        SyncConfiguration.Builder builder = SyncUser.current().createConfiguration(url)          
                .schemaVersion(1)
                .initialData(new Realm.Transaction() {
                    @Override
                    public void execute(@NonNull Realm realm) {
                        if (!isExist)
                            RealmDbHelper.createDefaultStore(realm);
                    }
                    @Override
                    public boolean equals(Object obj) {
                        return true;
                    }
                });

        if (enableSync) {
            builder.fullSynchronization();
        }

        return builder.build();
    }  
```

But when the configuration changes it throws exception

> Configurations cannot be different if used to open the same file

I know that this is not a issue, but is there workaround?

**Comment by cmelchior** [comment]
Most likely the URL is the same. The same URL cannot both be fully synchronized and query-based?

**Comment by pavelpoley** [comment]
In this case it is only fully synchronized and not query based.

**Comment by cmelchior** [comment]
What does the exception say? Also keep in mind that when you override equals, you should also override `hashCode()`, e.g something like:

```
@Override public boolean hashCode() {
  return 37;
}
```

**Comment by pavelpoley** [comment]
Exception say:

```
`Configurations cannot be different if used to open the same file. 
    Cached configuration: 
    realmDirectory: /data/user/0/com.***/files/realm-object-server/BY***t1/BY***t1
    realmFileName : ***__gmail.com__1
    canonicalPath: /data/data/com.***/files/realm-object-server/BY***t1/BY***t1/***__gmail.com__1
    key: [length: 0]
    schemaVersion: 1
    migration: null
    deleteRealmIfMigrationNeeded: false
    durability: FULL
    schemaMediator: io.realm.internal.modules.CompositeMediator@a0937bbb
    readOnly: false
    compactOnLaunch: null
    serverUrl: realms://***.io/BY***t1/***__gmail.com__1
    user: {UserId: BY***t1, AuthUrl: https://***.io/auth}
    errorHandler: io.realm.SyncManager$1@757e77c
    deleteRealmOnLogout: false
    waitForInitialRemoteData: false
```
    
    New configuration: 
    realmDirectory: /data/user/0/com.***/files/realm-object-server/BY***t1/BY***t1
    realmFileName : ***__gmail.com__1
    canonicalPath: /data/data/com.***/files/realm-object-server/BY***t1/BY***t1/***__gmail.com__1
    key: [length: 0]
    schemaVersion: 1
    migration: null
    deleteRealmIfMigrationNeeded: false
    durability: FULL
    schemaMediator: io.realm.DefaultRealmModuleMediator@74c3da78
    readOnly: false
    compactOnLaunch: null
    serverUrl: realms://***.io/BY***t1/***__gmail.com__1
    user: {UserId: BY***t1, AuthUrl: https://***/auth}
    errorHandler: io.realm.SyncManager$1@757e77c
    deleteRealmOnLogout: false
    waitForInitialRemoteData: false`

**Comment by cmelchior** [comment]
The schema seems to be different for some reason? `schemaMediator: io.realm.internal.modules.CompositeMediator@a0937bbb vs schemaMediator: io.realm.DefaultRealmModuleMediator@74c3da78` ?

**Comment by pavelpoley** [comment]
What can be the reason?

**Comment by pavelpoley** [comment]
Oh i think i forgot that without `fullSynchronization()` the realm is query based by default, no?
I there way to disable synchronization to full-sync realm?

**Comment by cmelchior** [comment]
Yes, the default behaviour is query-based.

You can disable synchronization by calling `stop()` on the session, e.g. `SyncManager.getSession(config).stop();

**Comment by pavelpoley** [comment]
I will try
