### ISSUE TITLE
How to detect that realm is closed correctly? Or realm.close(); works incorrect

### ISSUE THREAD

**Issue by ioviov** [realm/realm-java#6533]
Hi, 
How to detect that realm is closed correctly? Or realm.close(); works incorrect

I print the value of realm object after realm.close() and this value still exist:

```
CommonModel commonModel = new CommonModel();
CommonDB data = commonModel.getData();

Log.i("realmFirst", "value: " + data.maxSortPosition);

commonModel.realmClose();

Log.i("realmSecond", "value: " + data.maxSortPosition);
```

My structure is:

```
public class SongsFragment extends Fragment {

  private void initListView() {
    CommonModel commonModel = new CommonModel();
    CommonDB data = commonModel.getData();

    Log.i("realmFirst", "value: " + data.maxSortPosition);

    commonModel.realmClose();

    Log.i("realmSecond", "value: " + data.maxSortPosition);
  }
}

public class CommonDB extends RealmObject {
    public Integer maxSortPosition = 0;
}

public class CommonModel {
  private Realm mRealm;

  public CommonModel() {
    mRealm = Realm.getDefaultInstance();
  }

  public CommonDB getData() {
    return mRealm.where(CommonDB.class).findFirst();
  }

  public void realmClose() {
    if (mRealm != null) {
      mRealm.close();
      mRealm = null;
    }
  }
} 
```

**Comment by cmelchior** [comment]
Realm instances are reference counted, so each `getInstance()` must be matched by a `close()` and only the last `close()` will fully close it. You can read more here: https://realm.io/docs/java/latest/#realm-instance-lifecycle

You can also use `Realm.getLocalInstanceCount(config)` which will return the number of open instances on this particular thread.

**Comment by Zhuinden** [comment]
`close()` is ref-counted.

You need to call `close()` exactly as many times as you called `getInstance`.

**Comment by ioviov** [comment]
Thanks, 
As you can see I called `getInstance` only once in my object

```
public CommonModel() {
    mRealm = Realm.getDefaultInstance();
}
```

So, called `close()` also once

```
public void realmClose() {
    if (mRealm != null) {
      mRealm.close();
      mRealm = null;
    }
}
```

Maybe a problem is appeared because I work with realm in object `CommonModel` instead create `realmInstance` in `Fragment` and put `close()` to `onDestroy()` as I saw in many examples?

**Comment by cmelchior** [comment]
Putting those methods there are fine, but keep in mind that `Fragment.onDestroy()` might not be called when you expect it to, especially it isn't necessarily called when the fragment isn't visible. So depending on what you are trying to accomplish, it might be safer putting those methods in `onStart/onStop`.

**Comment by ioviov** [comment]
Thanks, guys!
`close()` works correctly...

Your answers help me:

@cmelchior 
> Realm instances are reference counted, so each getInstance() must be matched by a close() and only the last close() will fully close it.

and 

@Zhuinden 
> You need to call close() exactly as many times as you called getInstance.

**Comment by ioviov** [comment]
I'm sorry that reopen...

Could you provide me an advice, please

I have only one `MainActivity` on my app, so could I call `Realm.getDefaultInstance()` once, save it to static variable and use it everywhere I need? And should I call `realm.close()` somewhere?

As I understand after close the app `realm instance` will be destroyed?

Thanks!

**Comment by ioviov** [comment]
I'm sorry that reopen...

Could you provide me an advice, please

I have only one `MainActivity` on my app, so could I call `Realm.getDefaultInstance()` once, save it to static variable and use it everywhere I need? And should I call `realm.close()` somewhere?

As I understand after close the app `realm instance` will be destroyed?

Thanks!

**Comment by ioviov** [comment]
Please, somebody, help me to understand that :(

**Comment by Zhuinden** [comment]
Realm instances are thread-local, so you still need to open/close are) Realm for background threads.

**Comment by cmelchior** [comment]
Yes, you need to open/close Realm on any background threads, but for the UI thread, it is fine to store the Realm reference in a static variable. This article might be helpful: https://academy.realm.io/posts/threading-deep-dive/

**Comment by ioviov** [comment]
@cmelchior thanks for the article! I will read it.
For more understand how `Realm` works, could you answer, please:

1. When I call `Realm.getDefaultInstance()` the realm creates a file on devise's disk, yes?
2. And for example, I don't call `realm.close()` and after close an app this realm file will be deleted?
3. I have only one `realm instance` and save it to a static variable because I work on `UI thread` and I use this static var any time I need, so is it ok? I mean the file that was created when `realm instance` was called doesn't increase a lot off? 

A lot of thanks!

Maybe you could provide some articles about Realm

**Comment by cmelchior** [comment]
1) Yes, if it doesn't already exist.
2) No, the file is not deleted when you close the app. If you want that behaviour, you can set `inMemory()` on the `RealmConfiguration`, but then nothing is persisted to disk. This is normally not what you want.
3) Realm internally caches instances so if you want to use a static variable for performance, there really is no need. It is only "expensive" to open a Realm for the first time, open it after that just returns the cached instance.

**Comment by ioviov** [comment]
@cmelchior 

1.
If I create and use on `realm instance` on UI thread, where should I close this instance?
I have only on `MainActivity` and a lot of `Fragments`

2.
And I still don't understand, why is it bad if I don't close this one realm instance?
I thought that after the App close, everything is ok 

Thanks!
Sorry for the miss understanding, I really appreciate your help!

**Comment by Zhuinden** [comment]
Closing Realm instances is important if you want to use compact, or if you're on a non-looper background thread.

**Comment by ioviov** [comment]
@Zhuinden thanks
