### ISSUE TITLE
Realm.finalize() timed out

### ISSUE THREAD

**Issue by ruanbaojun1105** [realm/realm-java#6534]
#### Version of Realm and tooling

Realm version(s): ?
classpath "io.realm:realm-gradle-plugin:5.9.1"
Realm Sync feature enabled: Yes/No

Android Studio version: ?
3.4
Android Build Tools version: ?
28.0.0
Gradle version: ?
4.10.1
Which Android version and device(s): ?
8.1

![image](https://user-images.githubusercontent.com/7459297/58843815-c176eb00-86a6-11e9-9f86-c2afd0a97af4.png)

**Comment by cmelchior** [comment]
Hmm, odd. The only place we (Realm) uses a finalizer is for the Realm instance, and that isn't doing any heavy lifting at all. It is basically just a check if `close()` has been called on it.

Is this something you can reproduce?

**Comment by cmelchior** [comment]
Closing due to no response, please reopen if this is still an issue.
