### ISSUE TITLE
App_name is overridden by realm-android-kotlin-extensions library

### ISSUE THREAD

**Issue by nmrsmn** [realm/realm-java#6536]
#### Goal
Installing the app with my chosen name from the strings.xml

#### Actual Results
The app name (app_name) is "kotlin-extensions"

#### Steps & Code to Reproduce
Setup a new project, using kotlin-dsl gradle, make it modulair and include Realm in the additional module (I have multiple modules, but only the cache module implements Realm). Run the app. App_name is now "kotlin_extensions".

#### Version of Realm and tooling

Realm version(s): 5.11.0
Realm Sync feature enabled: No
Android Studio version: 3.4.1
Android Build Tools version: 28
Gradle version: 5.1.1

Which Android version and device(s):

**Comment by cmelchior** [comment]
Yes, this is a bug on our side. We should not define the `app_title`

**Comment by cmelchior** [comment]
Should be fixed by #6541
