### ISSUE TITLE
Current user is not valid if more that one valid, logged-in user exists

### ISSUE THREAD

**Issue by pavelpoley** [realm/realm-java#6537]
I am try to log out and log in (JWT auth)  with different account and i have this exception:

> Current user is not valid if more that one valid, logged-in user exists.

With same account this is not happen.

I am using this function:

```
public void logOut() {
      Map<String, SyncUser> all = SyncUser.all();
            for (Map.Entry<String, SyncUser> entry : all.entrySet()) {
                entry.getValue().logOut();
            }  
    }
```

To force this work, I need to log out and restart the app, otherwise it will always crash.

Realm 5.11.0

**Comment by cmelchior** [comment]
Hi @pavelpoley 
Can you provide a small sample app demonstrating the issue?

**Comment by cmelchior** [comment]
Closing due to no response. Please reopen if this is still an issue.
