### ISSUE TITLE
I am getting this log on Realm object server Sync Connection[6822]: Session[1]: Token expired (message_type='bind', signed_user_token='...NzQDvUaAfmcqf2GooVD7++x8waDA=='). 5:59:53 PMerror sync: Sync Connection[6822]: Session[1]: Token expired (signed_user_token='...NzQDvUaAfmcqf2GooVD7++x8waDA==').ject server

### ISSUE THREAD

**Issue by krishnasharma2018** [realm/realm-java#6538]

**Comment by cmelchior** [comment]
Hi @krishnasharma2018 

Yes, that doesn't need to be an error as such. 

Realm access tokens have a limited lifetime, but the clients will automatically attempt to create a new one before the old one expires. In some cases, they might not make it in time, which can cause the error on the server, but the error is benign as the Clients will still automatically refresh their tokens.
