### ISSUE TITLE
annotationProcessor warning during build

### ISSUE THREAD

**Issue by lksnmnn** [realm/realm-java#6545]
#### Goal

Compile application without warnings.

#### Actual Results

Gradle logs the following warning:
```
app: 'annotationProcessor' dependencies won't be recognized as kapt annotation processors. Please change the configuration name to 'kapt' for these artifacts: 'io.realm:realm-annotations-processor:5.11.0', 'io.realm:realm-annotations-processor:5.11.0'.
```

#### Steps & Code to Reproduce

build.gradle
```
buildscript {
    dependencies {
        classpath 'com.android.tools.build:gradle:3.4.1'
        classpath 'io.realm:realm-gradle-plugin:5.11.0'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.3.40"
   }
}
plugins {
    id "realm-android"

    id "kotlin-android"
    id "kotlin-android-extensions"
    id "kotlin-kapt"
}
```

#### Version of Realm and tooling

Realm version(s): 5.11.0

Realm Sync feature enabled: No

Android Studio version: 3.4.1

Android Build Tools version: 3.4.1

Gradle version: 5.1.1

Which Android version and device(s): 28

**Comment by cmelchior** [comment]
The order of your plugins are not correct. They need to match what is described here: https://realm.io/docs/java/latest/#kotlin in order to avoid the warnings
