### ISSUE TITLE
Realm using TimeZone of Date object in greaterThanOrEqualsTo(Date)

### ISSUE THREAD

**Issue by gnarbaiz** [realm/realm-java#6546]
#### Goal
I want to query using date value independently from the timezone of Date object has.

#### Actual Results
When using greaterThanOrEqualTo(String fieldName, Date value) the method recognizes the timezone date object has, and it is not making the query properly.

#### Steps & Code to Reproduce
I want to receive inputs within the beginning and the end of the day. I get the today's date, and set time to 00:00:00.000 when getting de date from the calendar instance, it uses the device timezone, and when the method is executed is not using UTC.

Calendar calendar = new GregorianCalendar();
        calendar.set(Calendar.HOUR_OF_DAY, 0);
        calendar.set(Calendar.MINUTE, 0);
        calendar.set(Calendar.SECOND, 0);
        calendar.set(Calendar.MILLISECOND, 0);
        Date today = calendar.getTime();
        calendar.add(Calendar.DAY_OF_MONTH, 1);
        Date tomorrow = calendar.getTime();

        result= realm.where(OrderRealm.class)
                .beginGroup()
                .greaterThanOrEqualTo("time", today)
                .lessThan("time", tomorrow)
                .endGroup()
                .findAll();

_Alternatively I set UTC to calendar instance_
_calendar.setTimeZone(TimeZone.getTimeZone("UTC"));_

#### Version of Realm and tooling

Realm version(s): 361

Realm Sync feature enabled: Yes

Android Studio version: 3.4

Android Build Tools version: 28

Which Android version and device(s): 6

**Comment by Zhuinden** [comment]
I think you sohuld probably set the timezone manually before you start the query

**Comment by gnarbaiz** [comment]
Before getting the time from the calendar instance, I used also the line _calendar.setTimeZone(TimeZone.getTimeZone("UTC"))_ but the Date object generated uses the device timezone, and the result from Realm is the same.

**Comment by cmelchior** [comment]
Realm just calls `Date.getTime()` (See https://github.com/realm/realm-java/blob/master/realm/realm-library/src/main/java/io/realm/internal/TableQuery.java#L256) which returns the value of the Date object in UTC, so my guess is that you are using the Calendar API in a wrong way. It has been a while since I used it so I cannot point to anything specifically wrong with your usage of it, but I do remember a number of pitfalls.

If you still think there is a problem with Realm, please provide a small sample project demonstrating the problem so we can debug it.

**Comment by cmelchior** [comment]
Closing due to no response. Please reopen if this is still an issue.

**Comment by xeno-sama** [comment]
> Realm just calls `Date.getTime()` (See https://github.com/realm/realm-java/blob/master/realm/realm-library/src/main/java/io/realm/internal/TableQuery.java#L256) which returns the value of the Date object in UTC, so my guess is that you are using the Calendar API in a wrong way. It has been a while since I used it so I cannot point to anything specifically wrong with your usage of it, but I do remember a number of pitfalls.
> 
> If you still think there is a problem with Realm, please provide a small sample project demonstrating the problem so we can debug it.

imao
it just wrong to return date in UTC (which is of course system)  so coders have to make workaround (save additional fields with needed timezone and convert)

it's just better not return with UTC  .. coders always could use .toUtc() manually if needed
