### ISSUE TITLE
android\app\build.gradle' line: 1  * What went wrong: A problem occurred evaluating project ':app'. > ASCII

### ISSUE THREAD

**Issue by poojasharma3106** [realm/realm-java#6549]
#### Version of Realm and tooling

Realm version(s): ?

Realm Sync feature enabled: Yes/No

Android Studio version: ?

Android Build Tools version: ?

Gradle version: ?

Which Android version and device(s): ?

**Comment by bmunkholm** [comment]
@poojasharma3106 Please fill out the entire template. A headline is unfortunately not sufficient to help you in any way.
