### ISSUE TITLE
 Realm Partial Sync Off (if app open for 5 minute or more)

### ISSUE THREAD

**Issue by sshakilms** [realm/realm-java#6554]
#### Goal
chat app - we want Continues Sync but after 5 minute  app SDK not Sync with Cloud server

#### Actual Results
after 5 minute  app SDK not Sync with Cloud server

#### Steps & Code to Reproduce
Open app for Five minutes and after that Sync Stop

#### Version of Realm and tooling
We have Realm Cloud support 
In my Android App Sync will off if open my android app for long time.
I have 2 Partial Files one file I am using for Chat Purpose .I need Proper sync each time whenever user type or if he get notifications,
I attached Realm Listener to all my RealmResult and 

Q- I read some documentation they mention that some OS stop thread to save battery. is it true?
to prevent that I attached one thread that work always in background:
```
syncTimer=new Timer();
syncTimer.scheduleAtFixedRate(new TimerTask() {
    @Override
    public void run() {
        try {
            if(LoopHealthApplicationClass.getInstance().physicianUser!=null && LoopHealthApplicationClass.getInstance().physicianUser.getPhysicianId()!=null) {
                boolean chatBoolean=ChatSyncDao.addChatSyncAt(LoopHealthApplicationClass.getInstance().physicianUser.getPhysicianId());
                boolean userBoolean=SyncDao.addUserSyncAt(LoopHealthApplicationClass.getInstance().physicianUser.getPhysicianId());
                Timber.d("chatRealm: "+chatBoolean+" | userRealm: "+userBoolean+"| SyncAt");
            }
        }catch(Exception e) {
            e.printStackTrace();
            SyncManager.refreshConnections(); //Refresh Connection
        }
    }
}, 10000, 10000);

```

ANdroid Realm Lib: 
`classpath "io.realm:realm-gradle-plugin:5.12.0"`
In App Level Gradle:
apply plugin: 'realm-android'
```
realm {
    syncEnabled = true
}
```

I  mentioned Logs details below before Sync Stoped
```
2019-07-01 21:55:05.327 26590-26843/com.invoqhealth.loophealth2 I/REALM_SYNC: Connection[3]: Session[3]: Received: ERROR(error_code=202, message_size=20, try_again=0)
2019-07-01 21:55:05.327 26590-26843/com.invoqhealth.loophealth2 D/REALM_SYNC: Connection[3]: Session[3]: Suspended
```

Version of Realm Object Server : 
Realm version(s): v3.23.1

Realm Sync feature enabled: Yes

Android Studio version: 5.12.0

Android Build Tools version: '28.0.3'

Gradle version: 3.4.1

Which Android version and device(s): All

**Comment by bmunkholm** [comment]
@sshakilms I can see you already filed a support ticket at support.realm.io. That's the right place for paid support and it's too confusing to support through multiple channels. So I'll close this.
