### ISSUE TITLE
Priority Async transaction?

### ISSUE THREAD

**Issue by bagvand** [realm/realm-java#6559]
I have some transaction that has high priority and I want to say this for method excuteTransactionAsync.
How can I do it?

**Comment by Zhuinden** [comment]
What does "high priority" mean? Transactions are executed in order of opening them.

**Comment by bagvand** [comment]
for example, some transaction that End-user needs its response has higher priority from other transaction.

**Comment by Zhuinden** [comment]
I think in that case, I'd just handle the threading myself and that way I have control over the execution order beyond sequential ordering.

**Comment by cmelchior** [comment]
Yes, in that case you would need to implement your own transaction controller or job queue that is able to receive a priority parameter. There isn't much magic to the async methods in Realm they are just helper methods so people don't have to worry about it. 

You can implement it by having a background looper thread that accepts jobs and then just runs synchronous transactions on that looper thread.
