### ISSUE TITLE
realm sync to web backend database 

### ISSUE THREAD

**Issue by TariqTawalbeh** [realm/realm-java#6564]
I've searched about how we can sync new data on realm with mysql db, I would like to know how can we do it and if it's not provided via realm, is there anyway that I can do it using any other service or whatever?!

Thanks

**Comment by cmelchior** [comment]
We have connectors that support syncing a Realm database to Postgres or MSSQL, but no support for MySQL. You can read more here: https://docs.realm.io/sync/backend-integration
