### ISSUE TITLE
Too many open files in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101

### ISSUE THREAD

**Issue by arsalankhan994** [realm/realm-java#6569]
#### Actual Results
Exception has been thrown: Unrecoverable error. Too many open files in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101 07-08 19:16:21.815 15170-15446/co.example.app.release E/AndroidRuntime: FATAL EXCEPTION: Thread-46                                                                      Process: co.example.app.release, PID: 15170                                                                      java.lang.RuntimeException: An error occurred while executing doInBackground()                                                                          at android.os.AsyncTask$3.done(AsyncTask.java:365)                                                                          at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)                                                                          at java.util.concurrent.FutureTask.setException(FutureTask.java:252)                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:271)                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)                                                                          at co.foree.app.bll.threadpool.PriorityThreadFactory$1.run(PriorityThreadFactory.java:26)                                                                          at java.lang.Thread.run(Thread.java:784)                                                                       Caused by: io.realm.exceptions.RealmError: Unrecoverable error. Too many open files in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101                                                                          at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)                                                                          at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:171)                                                                          at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:241)                                                                          at 
io.realm.BaseRealm.<init>(BaseRealm.java:136)                                                                          at io.realm.BaseRealm.<init>(BaseRealm.java:103)                                                                          at io.realm.Realm.<init>(Realm.java:163)                                                                          at io.realm.Realm.createInstance(Realm.java:499)                                                                          at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:341)                                                                         at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:284)                                                                          at io.realm.Realm.getInstance(Realm.java:428)                                                                          at co.foree.app.utils.RealmManagerUtil.getSessionRealmInstance(RealmManagerUtil.java:110)                                                                          at co.foree.app.realm.repository.SessionRealmRepository.getLongForKey(SessionRealmRepository.java:247)                                                                          at co.foree.app.utils.Session.getSerialNumber(Session.java:449)                                                                          at co.foree.app.realm.helper.RealmHelper$AssignSerialNumberAndInsert.doInBackground(RealmHelper.java:553)                                                                          at co.foree.app.realm.helper.RealmHelper$AssignSerialNumberAndInsert.doInBackground(RealmHelper.java:500)                                                                          at android.os.AsyncTask$2.call(AsyncTask.java:345)                                                                          at java.util.concurrent.FutureTask.run(FutureTask.java:266)                                                                          at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1162)                                                                          at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:636)                                                                          at co.foree.app.bll.threadpool.PriorityThreadFactory$1.run(PriorityThreadFactory.java:26)                                                                          at java.lang.Thread.run(Thread.java:784)

#### Version of Realm and tooling

Realm version(s): ?
5.1.0

Android Studio version: ?
3.4.1

Android Build Tools version: ?
26

Gradle version: ?
4.1-all

Which Android version and device(s): ?
7.0

**Comment by cmelchior** [comment]
This error is thrown by the underlying file system. It happens because your ThreadPool is keeping Realm instances alive, and apparently your thread pool is so large that it hits the kernel limit.

You need to either:

A) Close Realm instances when done with them in the thread pool
B) Limit the number of threads in the pool. Note that if you are doing writes, then having many threads doesn't make much sense since Realm can only have 1 write transaction across all threads and processes at a time due to the ACID guarantees Realm has.

**Comment by arsalankhan994** [comment]
But I am closing my realm instance after operations and I have already set the limit of thread pool which is 8.

**Comment by cmelchior** [comment]
You can verify how many threads have open Realm instances by calling `Realm.getGlobalInstanceCount(config)` This will return the number of threads that currently have Realms opened.

If that number is still low, you are probably leaking file descriptors somewhere else, and Realm just happens to trigger it. 

We use around 5 file descriptors pr. thread for Realm and the normal limit is 1024.

**Comment by arsalankhan994** [comment]
I already tried Realm.getGlobalInstanceCount(config). But this return 8 to 9 instance. "you are probably leaking file descriptors somewhere else" what does it mean?

**Comment by cmelchior** [comment]
That your app is opening other files and that you are forgetting to close them again. One option could be to use the memory profiler in Android Studio and look for a large number of `File` objects.

**Comment by arsalankhan994** [comment]
Thanks I will try this
