### ISSUE TITLE
'getInstance(io.realm.RealmConfiguration)' in 'io.realm.Realm' cannot be applied to '(android.content.Context)' error

### ISSUE THREAD

**Issue by shymaaelnakeeb** [realm/realm-java#6587]
Realm realm=Realm.getInstance(getApplicationContext());
                realm.beginTransaction();
                realm.copyToRealmOrUpdate(car);
                realm.commitTransaction();

**Comment by bmunkholm** [comment]
@shymaaelnakeeb Please fill out the entire template when you create an issue. We have no way to help you with this little context.

**Comment by shymaaelnakeeb** [comment]
> 
> 
> @shymaaelnakeeb Please fill out the entire template when you create an issue. We have no way to help you with this little context.
wich  template ?

**Comment by Zhuinden** [comment]
```
#### Goal
<!-- What do you want to achieve? -->

#### Actual Results
<!-- What happened? If an exception was thrown please copy/paste the stack trace from Logcat. -->

#### Steps & Code to Reproduce
<!-- What steps resulted in the crash? Please show any relevant code or steps that can be used to -->
<!-- reproduce it, including any Realm model classes used. Even better is a full sample project -->
<!-- that can reproduce the crash. Code can be shared privately at help@realm.io if needed. -->

#### Version of Realm and tooling

Realm version(s): ?

Realm Sync feature enabled: Yes/No

Android Studio version: ?

Android Build Tools version: ?

Gradle version: ?

Which Android version and device(s): ?
```

And the answer is, stop following a tutorial written for a version older than 0.83.0, it won't work.

Refer to newer material, or the samples, etc.

**Comment by shymaaelnakeeb** [comment]
this error appear 'getInstance(io.realm.RealmConfiguration)' in 'io.realm.Realm' cannot be applied to '(android.content.Context)'
with this code
Realm realm=Realm.getInstance(getApplicationContext());
in app
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath "io.realm:realm-gradle-plugin:5.14.0"

    }
}

**Comment by Zhuinden** [comment]
The method `Realm.getInstance(Context)` does not exist since 0.83.0. 

Use `Realm.getInstance(RealmConfiguration)`.

You are probably also missing `Realm.init(context)` and `Realm.setDefaultConfiguration(RealmConfiguration)` in your `Application.onCreate`.
