### ISSUE TITLE
What is wrong with this code؟

### ISSUE THREAD

**Issue by shymaaelnakeeb** [realm/realm-java#6591]
when i add this code
car's name appear in showall page
but 
the program is stoped in addcar page
Showall page:

@Override
protected void onResume() {
    super.onResume();

    Realm realm =Realm.getDefaultInstance();
    realm.beginTransaction();
    List<car>cars=realm.where(car.class).findAll();
    String[] names=new String[cars.size()];
    for(int i=0;i<names.length;i++){
        names[i]=cars.get(i).getName();
    }

    ListView listView=(ListView)findViewById(R.id.listview);
    ArrayAdapter<String> adapter=new ArrayAdapter<String>(this,android.R.layout.simple_list_item_1,names);
    listView.setAdapter(adapter);

}
Addcar page

final Button addcar =(Button)findViewById(R.id.addbutton);
addcar.setOnClickListener(new View.OnClickListener() {
    @Override
    public void onClick(View v) {

        car carss = new car();
        carss.setName(name.getText().toString());
        carss.setId(id.getText().toString());
        carss.setModel(model.getText().toString());
        carss.setStatus(status.isChecked());

        Realm realm = Realm.getDefaultInstance();
        realm.beginTransaction();
        realm.copyToRealmOrUpdate(carss);
        realm.commitTransaction();

        Toast.makeText(addcar.this, "تم اضافة السيارة", Toast.LENGTH_LONG).show();
        finish();

    }
});

**Comment by Zhuinden** [comment]
Please don't start a write transaction and then leave it hanging (no call to cancelTransaction, commitTransaction). 

You don't need to open a transaction to start reading. You'll just break the app.

**Comment by shymaaelnakeeb** [comment]
> 
> 
> Please don't start a write transaction and then leave it hanging (no call to cancelTransaction, commitTransaction).
> 
> You don't need to open a transaction to start reading. You'll just break the app.
> 
> Put the app in background, bring it foreground, it will crash.

thank you
