### ISSUE TITLE
Unrecoverable error. mmap() failed: Out of memory size

### ISSUE THREAD

**Issue by AliTarhini** [realm/realm-java#6594]
#### Goal
Don't let the realm file crashed.

It is impossible that I forgot to close a Realm. I checked it. 

#### Actual Results

Fatal Exception: io.realm.exceptions.RealmErrorUnrecoverable error. mmap() failed: Out of memory size: 738197504 offset: 0 in /home/cc/repo/realm/release/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 217 Raw Text
--
  | io.realm.internal.SharedRealm.nativeGetSharedRealm (SharedRealm.java)
  | io.realm.internal.SharedRealm.<init> + 190 (SharedRealm.java:190)
  | io.realm.internal.SharedRealm.getInstance + 237 (SharedRealm.java:237)
  | io.realm.internal.SharedRealm.getInstance + 206 (SharedRealm.java:206)
  | io.realm.RealmCache.createRealmOrGetFromCache + 127 (RealmCache.java:127)
  | io.realm.Realm.getDefaultInstance + 211 (Realm.java:211)
  | net.cardiodiagnostics.cardioconnect.dataAccess.repositories.realm.RealmHelpers.createInstance + 19 (RealmHelpers.java:19)
  | net.cardiodiagnostics.cardioconnect.bluetooth.Adapters.eFaros.modeTransmitters.WirelessEventTransmitter.processEventPackets + 116 (WirelessEventTransmitter.java:116)
  | net.cardiodiagnostics.cardioconnect.bluetooth.Adapters.eFaros.modeTransmitters.WirelessEventTransmitter.transmitData + 92 (WirelessEventTransmitter.java:92)
  | net.cardiodiagnostics.cardioconnect.bluetooth.Adapters.eFaros.modeTransmitters.WirelessEventTransmitter$1.run + 105 (WirelessEventTransmitter.java:105)
  | java.lang.Thread.run + 818 (Thread.java:818)

**Comment by Zhuinden** [comment]
Hmm, it says the Realm file was only 704 MB when this happened.

Maybe the trick is that the background processing where you save new data should be happening on a HandlerThread (`AndroidSchedulers.from(handlerThread.getLooper())` if using Rx), rather than `Schedulers.io()`, although it is already a surprise to me that 704 MB would be too much.

I always used a single threaded executor for making Realm writes.

**Comment by AliTarhini** [comment]
Actually we're not using Rx, it's an old application.

Is there any ideas that can help to find a solution for the problem ?

**Comment by EdwardvanRaak** [comment]
There might be a different memory leak in your application.

However we also gets hundreds of incomprehensible native crashes each day as well that are related to memory issues, firebase is reporting less than 50MB available when these `lib.c` errors occur while other (normal) crashes show 500-1000GB RAM available. 

We are already using `Realm.getInstance().use{}` everywhere so non-closed realm instances are impossible in our case. We also simulated hours of use with our apps without crashes on an emulator. Yet for some reason on 1% of our users these crashes happen. We also made sure realm files aren't growing out of proportion and we made sure we just crash the app when OOM errors occur. But after all this we still we clearly see realm files going corrupt.

Maybe it's a mistake in our apps, or maybe realm but that's the whole problem with these crashes. It's impossible to know so we often just end up clearing realm files for users so they don't have to uninstall the app over and over and over.

**Comment by cmelchior** [comment]
Do you know which devices this happens on? 32-bit devices are generally pretty constrained and cannot open Realm files that are above 300-400 MB.

Apart from that, it is hard to tell. My initial assumption is that you are leaking Realm instances somehow, which doesn't seem to be the case. Note you can double check this by using `Realm.getGlobalInstanceCount(config)`

Alternatively, you are using that memory somewhere else and Realm just happens to trigger it, e.g. image processing/loading?

**Comment by AliTarhini** [comment]
@cmelchior I'm using Samsung Galaxy Grand Prime Plus ( sm-g532f ), it's a 64 bit device

**Comment by Rekklas** [comment]
@AliTarhini Do you have some RealmObjects which aggregate some other RealmObjects without PrimaryKeys? So after copyOrUpdate them you don't update, but create some additional copies. Also you can use deleteFromRealm for such objects, but be aware that realm doesn't provide cascade removing.

**Comment by cmelchior** [comment]
Regarding large Realm sizes, you can find possible explanations here: https://realm.io/docs/java/latest/#faq-large-realm-file-size

Alternatively we have this issue for tracking opening large files: https://github.com/realm/realm-java/issues/6667
