### ISSUE TITLE
Don't enforce jCenter repository

### ISSUE THREAD

**Issue by MGaetan89** [realm/realm-java#6597]
#### Describe your problem or use case

My project is building on a Jenkins instance, which does not have access to the external network. All our dependencies are downloaded through our local repository:

```groovy
buildscript {
    repositories {
        maven {
            url 'https://maven.my-company.com/'
        }
    }
}

allprojects {
    repositories {
        maven {
            url 'https://maven.my-company.com/'
        }
    }
}
```

In [Realm.groovy#L75](https://github.com/realm/realm-java/blob/789740d8050ba020c8990fd7983fb709b748f7b3/gradle-plugin/src/main/groovy/io/realm/gradle/Realm.groovy#L75), I can see that you are explicitly adding the `jCenter` repository.
This causes my build to take way longer than necessary, because Gradle is trying to connect to an unreachable repository for each of the declared dependency.

#### Describe the solution you'd like

Don't enforce the `jCenter` repository if it is not necessary.

#### Additional context

In https://github.com/gradle/gradle/issues/10376#issuecomment-525336635, @lacasseio provided some tips on how this issue could be addressed: only adding `jCenter` if no other repositories are defined.

**Comment by cmelchior** [comment]
Yes, I can see why we could this smarter. We should change this. We are also happy to accept any PR for it.

**Comment by MGaetan89** [comment]
I'm building Realm now. I'll see if I can make a PR for this.

**Comment by Zhuinden** [comment]
PR @ #6598

**Comment by MGaetan89** [comment]
I just updated to version 5.15.0 and the fix seems to work as expected :+1:
