### ISSUE TITLE
Migration crashes on newly created object

### ISSUE THREAD

**Issue by jpmcosta** [realm/realm-java#6604]
#### Goal
I'm trying to migrate my database. The migration creates new objects that hold lists of other objects, in order to speed-up search queries. It's related to #6601.

#### Actual Results
The migration unexpectedly crashes with:

```
Fatal Exception: java.lang.IllegalStateException
Object is no longer valid to operate on. Was it deleted by another thread?
io.realm.internal.UncheckedRow.nativeGetIndex
```

#### Steps & Code to Reproduce
This is the relevant part of the code:

```kotlin
val allItems = realm.where("Item").sort("updatedAt", Sort.ASCENDING).findAll()
val itemCount = allItems.size
if (0 < itemCount) {
    var id = NO_ID
    val maxItemCount = 5_000
    var fromIndex = 0
    do {
        val toIndex = min(itemCount, fromIndex + maxItemCount)
        val itemsSubList = allItems.subList(fromIndex, toIndex)
        val items = RealmList<DynamicRealmObject>().apply { addAll(itemsSubList) }
        val lastUpdatedAt = itemsSubList.last().getLong("updatedAt")

        val itemPage = realm.createObject("ItemPage", ++id)
        itemPage.setList("items", items) // Might crash here (most common).
        itemPage.setLong("lastUpdatedAt", lastUpdatedAt) // Might crash here (less common).

        fromIndex = toIndex
    } while (toIndex < itemCount)
}
```

Notes:

* this issue is in production
* I never run into this issue while testing; I've migrated databases with 5_000 and 50_000 items
* I'm using multi-process

#### Version of Realm and tooling
Realm version(s): 5.14.0

Realm Sync feature enabled: No

Android Studio version: 3.5

Android Build Tools version: 28.0.3

Gradle version: 5.4.1

Which Android version and device(s): 7.1, 8.1, and 9 (currently)

**Comment by jpmcosta** [comment]
I've also found a similar issue on StackOverflow:
https://stackoverflow.com/questions/56006227/realm-db-dynamicrealmobject-not-valid-during-migration

**Comment by jpmcosta** [comment]
I'm puzzled by the lack of response. I understand that the issue itself might be complex and difficult to reproduce. However, I was hoping to, at least, get some tips on how I could **try** to hotfix/minimize the issue.

I did release an updated yesterday, trying to change the migration slightly, but I still got crash reports today.

We are talking about a "simple" migration here. On the affected devices, the app is completely dead. On some cases, depending on the Android API, it was probably showing multiple error dialogs, because, due to its nature, it tries to start automatically. This has lead to some users uninstalling the app and others probably cleared their storage and lost their data in the process.

While my user base is **very** small, I had crashes on roughly 10% of my users (unique) and multiple 
crashes by user. Going forward, should I be worried every time I need to make a migration similar to this one?

**Comment by jpmcosta** [comment]
Hello,

Earlier today I posted a comment on this issue where I demanded some kind of support. After a minutes and after re-reading it I understood how wrong this line of thought was.

So, I want to apologize for that. I'm sorry if I caused you harm in any way.

Best regards and keep the great work.

Note: I'm going to remove this comment after posting it as well.

**Comment by cmelchior** [comment]
@jpmcosta Hmm, it is rather surprising that it is indeterministic which line crashes

Are you saying that you have stack traces for both a crash here:

```
itemPage.setList("items", items) // Might crash here (most common).
```

and here:

```
itemPage.setLong("lastUpdatedAt", lastUpdatedAt) // Might crash here (less common)
```

If that is true, that sounds really puzzling and would point to some kind of race condition, but since a migration runs inside a write transaction, no other changes should be allowed.

Are they crashing with the same error?

**Comment by jpmcosta** [comment]
@cmelchior these are the errors:

```
Fatal Exception: java.lang.IllegalStateException: Object is no longer valid to operate on. Was it deleted by another thread?
       at io.realm.internal.UncheckedRow.nativeGetIndex(UncheckedRow.java)
       at io.realm.internal.UncheckedRow.k + 2(UncheckedRow.java:2)
       at io.realm.DynamicRealmObject.setModelList + 137(DynamicRealmObject.java:137)
```
and
```
Fatal Exception: java.lang.IllegalStateException: Object is no longer valid to operate on. Was it deleted by another thread?
       at io.realm.internal.CheckedRow.nativeSetLong(CheckedRow.java)
       at io.realm.internal.UncheckedRow.b + 10(UncheckedRow.java:10)
       at io.realm.DynamicRealmObject.setLong + 148(DynamicRealmObject.java:148)
```

I've released an update where I would create the `ItemPage` objects before iterating the list, but that didn't solve the issue.

I've released a more recent update where I've changed `allItems` to:
```kotlin
val allItems = realm.where("Item").sort("updatedAt", Sort.ASCENDING).findAll().createSnapshot()
```

And I also catch a possible exception when setting the list and the long values, and retry to find or create the `ItemPage`. I still don't have much data about this update.

**Comment by jpmcosta** [comment]
Also, `Item` as a `@LinkingObjects` to its `ItemPage`.

**Comment by jpmcosta** [comment]
The crashes are still occurring with the `createSnapshot()` call. They seem to be happening less times. However, when they do happen, by catching the exception and retrying to find the object, I think I was able to prevent all migration issues.

**Comment by Zhuinden** [comment]
Sounds like in certain versions of the app, `lastUpdatedAt` does not exist and should have been added as part of the migration in case the field is not there.

**Comment by jpmcosta** [comment]
@Zhuinden thank you for your feedback. Unfortunately, I'm afraid it's not that simple.

`lastUpdatedAt` is always added and, after catching the exception, retrying to find the object, and re-applying the migration, it works.

**Comment by bmunkholm** [comment]
@jpmcosta If this is now resolved, will you close the issue?

**Comment by jpmcosta** [comment]
@bmunkholm I don't consider this issue is resolved. As @cmelchior stated, it seems there are racing conditions that are making migrations fail, but that shouldn't happen since we are inside a transaction.

Personally, I believe this issue is very serious and should have top priority. When migrations don't work, applications become dead. However, if you feel this is an edge-case and unimportant, maybe you could add a "won't fix" label and close it.

**Comment by cmelchior** [comment]
No, this issue shouldn't be closed. There is clearly a bug that we need to find.

**Comment by bmunkholm** [comment]
Ahh, sorry @jpmcosta I just read your last two words: "it works" :-)

**Comment by Zhuinden** [comment]
There should be a block across all processes as the transaction over a dynamic realm is still a transaction.

It would be rather surprising if there truly is a race condition during initialization / migration... 

I'd assume Realm would need a way to repro this in order to proceed further.
