### ISSUE TITLE
Update Encryption Docs

### ISSUE THREAD

**Issue by dsuresh-ap** [realm/realm-java#6605]
#### Describe your problem or use case
The encryption docs only states that AES-256 is used and a 512-bit key is required. This is confusing to some of us not too familiar with encryption. It looks like a 512-bit key is required because 256-bits are used by AES and the rest by HMAC.

#### Describe the solution you'd like
This [solution](https://github.com/realm/realm-java/issues/3309#issuecomment-281008349) was beneficial to figuring out how Realm actually uses the key. It would be nice for the encryption docs to be a little more clear on how Realm handles encryption for the different projects that require more info on security and encryption.

From contributor: `We use AES-256 which takes a 256 bit key, not bytes ... Since a byte is 8 bit, we thus take a 512 (64x8) bit key. The first 256 bits used used by AES, the last 256 bits by the HMAC.`

#### Additional context
[Source](https://realm.io/docs/java/latest/#encryption)
`The Realm file can be encrypted on disk by passing a 512-bit encryption key (64 bytes) `
`Realm transparently encrypts and decrypts data with standard AES-256 encryption`

**Comment by cmelchior** [comment]
Yes, you are right. We should make the docs more clear about this. Especially since this isn't the first time it has caused confusion
