### ISSUE TITLE
ConnectableObservable<T> publish() and connect should emit the value after asFlowable

### ISSUE THREAD

**Issue by q1q1w1w1q** [realm/realm-java#6607]
#### Goal
ConnectableObservable<T> publish() and connect() should emit the value after asFlowable

#### Actual Results
There are no emitting events like `onNext , onError` in the subscribe() block after connect().
I have checked there are values in the query.
If I swap the dataObservable to `Observable.fromArray(arrayListOf(1,2,3,4,5)).publish()`,
It works.

#### Steps & Code to Reproduce
        val dataObservable = Realm.getDefaultInstance().let { realm ->
                    realm.where(CurrencyModel::class.java)
                            .findAll()
                            .sort("name", Sort.ASCENDING)
                            .asFlowable()
                            .toObservable()
                            .doFinally {
                                if(!realm.isClosed) realm.close()
                            }
                }.publish()
        
        subscriptions.add(
            dataObservable
                .subscribeOn(AndroidSchedulers.mainThread())
                .subscribe( // This is the block which is not triggered at all
                    {
                        view?.setCurrency(it)
                    },
                    { Timber.e(it, "Failed to read currencies from database") }
                )
        )
        dataObservable.connect()

#### Version of Realm and tooling

Realm version(s): 5.13.0

Realm Sync feature enabled: No

Android Studio version: 3.4

Android Build Tools version: 28.0.3

Gradle version: 3.4.0

Which Android version and device(s): PIXEL2 simulator with SDK 28

**Comment by Zhuinden** [comment]
Sounds like you're missing a `replay(1)`.

**Comment by q1q1w1w1q** [comment]
After changing publish() to replay(1), it works!
Thank you for the great reply.

```
   val dataObservable = Realm.getDefaultInstance().let { realm ->
                realm.where(CurrencyModel::class.java)
                        .findAll()
                        .sort("name", Sort.ASCENDING)
                        .asFlowable()
                        .toObservable()
                        .doFinally {
                            if(!realm.isClosed) realm.close()
                        }
            }.replay(1) // Here
```
