### ISSUE TITLE
io.realm.internal.UncheckedRow.nativeSetDouble (UncheckedRow.java)

### ISSUE THREAD

**Issue by teja8692** [realm/realm-java#6608]
#### Describe your problem or use case

**While i am performing multiple operation in realm at a time i am getting issue** 

**io.realm.internal.UncheckedRow.nativeSetDouble (UncheckedRow.java)**
Caused by java.lang.IllegalStateException: Object is no longer valid to operate on. Was it deleted by another thread?
       at io.realm.internal.UncheckedRow.nativeSetDouble(UncheckedRow.java)
       at io.realm.internal.UncheckedRow.setDouble + 208(UncheckedRow.java:208)

**Comment by stennie** [comment]
Closing this issue due to no response. Please comment if you have additional information that may help reproduce this issue.
