### ISSUE TITLE
DynamicRealmObject.setList documentation is misleading

### ISSUE THREAD

**Issue by BlueCobold** [realm/realm-java#6616]
#### Goal
Setting a list-field of a DynamicRealmObject by reference and adding values to that list afterwards should result in the DynamicRealmObject's list to contain the added value.

#### Actual Results
The list is not set by reference, although the documention implies so. It only copies the values of the list.

#### Steps & Code to Reproduce
```
DynamicRealmObject handle = realm.createObject(Handle.class.getSimpleName(), "testhandle");
RealmList<DynamicRealmObject> tokens = new RealmList<>();
handle.setList("tokens", tokens);
DynamicRealmObject token = realm.createObject(Token.class.getSimpleName(), "testtoken");
tokens.add(token);
```
The handle is created in the DB, the token is also created in the DB, but the token is not included in the handle's token-list. According to the documention, I would expect that it is included.

#### Version of Realm and tooling

Realm version(s): 5.13.1

**Comment by Zhuinden** [comment]
> `Handle.class.getSimpleName()`

This is not recommended because

1.) now if you change the name of `Handle` class, the migration will break

2.) now if you use Proguard but don't keep the name of `Handle` class, then your migration will break

> > Sets the reference to a RealmList on the given field.

You're right, it grabs the existing managed RealmList and sets its items to be the items that are provided in the list. Probably a copy-paste error.

To get the behavior you expect, you should do:

``` java
DynamicRealmObject handle = realm.createObject(Handle.class.getSimpleName(), "testhandle");
RealmList<DynamicRealmObject> tokens = handle.getList("tokens");
// handle.setList("tokens", tokens);
DynamicRealmObject token = realm.createObject(Token.class.getSimpleName(), "testtoken");
tokens.add(token);
```

**Comment by BlueCobold** [comment]
Thanks. I am aware of the issues mentioned in (1) and (2) and I also know how to achieve what I need. But it would be better if the documentation would reflect the behaviour correctly. That would have saved me some time.
