### ISSUE TITLE
distinct ignore null field

### ISSUE THREAD

**Issue by QiLiKing** [realm/realm-java#6618]
#### Describe your problem or use case
my field(let's call it "displayName") is Nullable. Now I just want to distinct not null displayNames, and left the nulls. But realm does not support this.

**Comment by Zhuinden** [comment]
`realm.where(YourClass.class).isNotNull("displayName").distinct("displayName")`?

**Comment by QiLiKing** [comment]
I want to keep the null value left, and only distinct between the NonNull values.
for example:
1.  displayName=null,  realName="aaaaa"
2. displayName=null,  realName="bbbb"
3. displayName="disC" realName="cccc"
4. displayName="disC" realName="caca"
5. displayName="disD" realName="dddd"

after "distinct", should left 1, 2, 3,  5   OR   1, 2, 4, 5
Sorry for my pool English.

**Comment by QiLiKing** [comment]
"distinct" filters null value, but there is already a "isNotNull" method which user could use to filter null value. I prefer "distinct" skips null and empty value. Thanks.

**Comment by cmelchior** [comment]
`null` is a value like any other, so while I have sympathy for your use,  I don't think the behavior you want is something we should do by default. This is also how SQLite behaves: https://www.sqlite.org/lang_select.html#distinct

You would either have to do the query manually on all the objects or maybe combine two different Realm queries into one result:

```
List<YourClass> list = new ArrayList<>();
RealmResults<YourClass> result1 = realm.where(YourClass.class).isNull("displayName").findAll();
RealmResults<YourClass> result2 = realm.where(YourClass.class).isNotNull("displayName").distinct("displayName").findAll();
list.addAll(result1);
list.addAll(result2);
```

Both of these approaches do have performance drawbacks though.

**Comment by QiLiKing** [comment]
Thanks, I have went the wrong way.  Now, I have to distinct and notify refresh by myself, and also could not use "RealmRecyclerView". %>_<%
