### ISSUE TITLE
Database corrupted after update on some devices. 

### ISSUE THREAD

**Issue by Kyba1985** [realm/realm-java#6620]
#### Goal
Realm must work well after app update.

#### Actual Results
On some devices the database is corrupted and user can't use it after an update of the app. Must delete the folder where the database is stored to recreate the database and the app return to work well , but the users missing their data. 

#### Steps & Code to Reproduce
User update the app

#### Version of Realm and tooling

Realm version(s): 5.0.0

Realm Sync feature enabled: No

Android Studio version: 3.5

Android Build Tools version: 28.0.3

Gradle version: 4.9

Which Android version and device(s): different os version and devices , high percentage huawei.

Hi , after a normal update where the db layer has not been modified, the app it's not work properly due to realm error in the database layer. Is it a bug in realm? For us it's a very bad problem , for now happens on a few number of users, but this users are very unhappy because they lost data of the app. 

Do you know if i will update the realm to last version this will be fixed?

**Comment by bmunkholm** [comment]
@Kyba1985 Could you please provide more details on how you can see the database is corrupted?
What specific error are you seeing?
Are the devices rooted?
Which devices are you seeing this on?
Is it only end-users that experience this? Or have you seen this is your testing?
Do you have any of the files available?

**Comment by Kyba1985** [comment]
Hi , i see this from logs and bad reviews from users. At this time i know only that the code after the update go in a catch on a realm error. And this is only for some users , not all, and i can't reproduce this issue. This version is with .aab releases. 

Most of users has huawei devices. But not all. I will update realm to last version , create a new beta and log with crashlytics the stacktrace of this error, but this is a big problem for our app. 

Devices are not rooted , the number at this time are near one hundred , from reviews that we see at moment. But i think that are much number more by observation of uninstall curve of the app. 

I'm very unhappy with this issue of realm (if it's realm issue after more investigation). I'm quite sure that is not related on the app code because the code review with git has proven that the data layer was not changed. 

This is the first report on this?

**Comment by cmelchior** [comment]
@Kyba1985 We need some specific stack traces in order to speculate about exactly what it could be.

**Comment by cmelchior** [comment]
Mostly like reason being this bug fixed in 5.15.0 : https://github.com/realm/realm-java/blob/master/CHANGELOG.md#51502019-09-05

Please read the FAQ entry linked from the bug entry for more information.

For now, I'll close this as fixed. If the problem persists after upgrading Realm feel free to re-open the issue.
