### ISSUE TITLE
Reproducible mmap() failed (size: 0, offset is 0) crash

### ISSUE THREAD

**Issue by EdwardvanRaak** [realm/realm-java#6622]
#### Goal
While attempting some experiments on realm I found the following (undefined?) behavior which perhaps can be classified as a bug. I'm not sure...maybe it makes sense? If it does just close the issue of course.

#### Steps & Code to Reproduce
Anywhere in my code if I call:

```
Realm.getDefaultInstance().use {
	val file = File(it.path)
	FileOutputStream(file).close() 
}
```
It results in `mmap() failed (size: 0, offset is 0)` directly after I attempt to perform an insert transaction on realm objects.

On an perhaps unrelated note, if I deliberately corrupt the realm file (for example overriding the first bytes using `fileOutputStream.write(42)` this code can also cause java `OutOfMemory` crashes (but also a more expected decryption failed error).

I have not attempted to reproduce this in the example project yet but it's easily reproducible in our own code.

#### Version of Realm and tooling

Encryption enabled: Yes

Realm version(s): 5.14.0

Realm Sync feature enabled: No

Android Studio version: 3.5

Which Android version and device(s): Any device including emulators

**Comment by bmunkholm** [comment]
Yeah, doing any file operations on the Realm file is not allowed and is undefined behavior.

**Comment by EdwardvanRaak** [comment]
@bmunkholm I was apparently mistaken that merely initializing an output stream without doing any **actual** stream operations can cause some undefined behavior related to manipulating memory. 

One of the features of realm was that it is multi platform. So how would any developer programmatically copy a realm file from Android to iOS without doing _any_ file operations? I assume you mean that it not allowed after initializing realm?

Also wondering if this could happen by accident, for example by the OS or other unrelated library attempting to loop through files on the drive.

Anyways thanks for clearing it up.

**Comment by bmunkholm** [comment]
Yes. You just can't do file operations on the file while it's in use by Realm. But otherwise you can copy the file when it's properly close by Realm.
