### ISSUE TITLE
realm get instance as thread

### ISSUE THREAD

**Issue by omar-othmann** [realm/realm-java#6623]
Hello, i was tired to find realm.getDefaultInstance or getInstance as thread

let we say we have 2 classes is working on background to get message from server

and when i use realm from some class  to save message:
Realm.init(context);
Realm realm = Realm.getDefaultInstance();
realm.beginTransaction();
// save all data
realm.commitTransaction();
realm.close();

in other class i get catch and the application is going down
Error: realm is already in a write transaction
or: realm has already closed

and when i load data from realm:
application load data very slow and some time i get: application did't response
1- close app
2- wait

load data from realm code:

new Thread(() -> {
            list.clear();
            Realm.init(context);
            Realm realm = Realm.getInstance(MoonApplication.group);
            RealmResults<MessageRoom> chats = realm.where(MessageRoom.class).equalTo("from", username).and().equalTo("to", us).or().equalTo("from", us).and().equalTo("to", username).findAll();
            if(chats != null){
                for(int i=0; i<chats.size(); i++){
                    long id = chats.get(i).getId();
                    String from = chats.get(i).getFrom();
                    String to = chats.get(i).getTo();
                    String body = chats.get(i).getBody();
                    String time = chats.get(i).getTime();
                    String type = chats.get(i).getM_type();
                    String status = chats.get(i).getM_status();
                    String nick = chats.get(i).getNick();
                    String mm = chats.get(i).getMedia();
                    int media;
                    if(mm != null){
                        media = Integer.parseInt(chats.get(i).getMedia());
                    }else{
                        media = 0;
                    }
                    MoonCast.MessagesType t = MoonCast.getType(type);
                    switch (t){
                        case TEXT:
                            Message m = new Message(id, nick, from, to, body, time, type);
                            m.setStatus(MoonCast.getStatus(status));
                            list.add(m);
                            break;
                        case IMAGE:
                            list.add(new Image(context, id, nick, from, to, time, status, body, media));
                            break;
                        case AUDIO:
                            list.add(new Audio(context, id, nick, from, body, status, time, media));
                            break;
                        case VIDEO:
                            list.add(new Video(context, id, nick, from, to, time, status, body, media));
                            break;
                        case ADV:
                            list.add(new RoomNotify(body, time));
                            break;
                    }
                }
            }
            realm.close();
            ((Activity)context).runOnUiThread(this::notifyDataSetChanged);
            Intent intent = new Intent(MoonCast.C_MESSAGE_NOTIFICATION);
            intent.putExtra(MoonCast.EXTRA_FROM, username);
            intent.putExtra(MoonCast.EXTRA_TYPE, MoonCast.TYPE_MOVE);
            context.sendBroadcast(intent);
        }).start();
    }

and when i get data from server, save or update code is:

`Realm realm = Realm.getInstance(MoonApplication.group);
if(!realm.isInTransaction()){
    realm.beginTransaction();
}
Log.e("FRom", "From: "+from);
MessageRoom chat = realm.where(MessageRoom.class).equalTo("id", Long.parseLong(id)).and().equalTo("to", room).findFirst();
if(chat != null){
   chat.setM_status("ok");
   Log.e("Updated", "Chat to: "+chat.getTo());
   realm.insertOrUpdate(chat);
}

realm.commitTransaction();
realm.close();
Intent i = new Intent(MoonCast.C_MESSAGE_NOTIFICATION);
i.putExtra(MoonCast.EXTRA_TYPE, MoonCast.TYPE_UPDATE_ITEM);
i.putExtra(MoonCast.EXTRA_FROM, room);
i.putExtra(MoonCast.EXTRA_ID, message.getPacketID());
context.sendBroadcast(i);`

Note: i was add:
`if(!realm.isInTransaction()){
     realm.beginTransaction();
}`

and the problem: realm is already in a write transaction, was solved

but application is slow to load data from realm

and when i close realm from some class it's closed from all class

**Comment by Zhuinden** [comment]
Well, yes, Realm's thread local behavior also provides lazy loading.

**Comment by bmunkholm** [comment]
Hey @omar-othmann 
As mentioned in the issue template, we only use this repo for bug reports and feature requests. For questions about how to use realm, we defer to [StackOverflow](http://stackoverflow.com/questions/ask?tags=realm), where we monitor the `realm` tag. Or you can ask in our [Forum](https://forums.realm.io/).

One quick comment though: beginTransaction() will block in case another thread is already in a write transaction, and it will resume when that transaction is committed. So using inTransaction() conditionally seems like a bad workaround. You should only use that in cases where you have a method you call both from multiple places and where you sometimes already are in a transaction.

Thanks for your help!
