### ISSUE TITLE
Java SyncSession is removed when the Realm is closed

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#6625]
When the Realm thread counter reaches 0 we are removing the Java `SyncSession`, this is a problem in the case where you still want to listen for progress listeners after the Realm is closed (which is how the design currently is, and how the C++ layer work). 

But because the Java session might be GC'ed, the listeners are never called, giving the impression that upload isn't happening.

We need to figure out a way to keep the SyncSession alive for as long as needed.

**Comment by Zhuinden** [comment]
The real question is, what is "as long as needed"

**Comment by cmelchior** [comment]
Yup, that is the tricky part.
