### ISSUE TITLE
findAllAsync().addChangeListener within a change listener

### ISSUE THREAD

**Issue by funct7** [realm/realm-java#6629]
#### Goal
Subscribe to queries in a serially chained manner.

#### Actual Results
The block for `findAllAsync().addChangeListener` is never called.

#### Steps & Code to Reproduce
The first listener:
```kt
realm.account.forTrip(tripId).findAllAsync().addChangeListener { it, _ ->
    // `realmAccounts` is an ivar on this class
    realmAccounts = it
    updateRecordsObservation()
}
```

Inside `updateRecordsObservation()`:
```kt
private fun updateRecordsObservation() {
    if (!realmAccounts.isValid) return

    val idList: List<String>

    try {
        // To ensure that the code below try-catch block is called.
        // No exception is actually thrown due to precondition checks.
        idList = realmAccounts
            .filter { it.isCashAccount }
            .takeIf { it.isNotEmpty() }
            ?.map { it.id }
            ?: throw InvalidStateException()
    } catch (e: Exception) {
        onUpdateFailure(this, e)
        return
    }

    realm.record
        .`in`("to", idList.toTypedArray())
        .findAllAsync()
        .addChangeListener { it, _ ->
            // This block is never called.
            Log.d("DataManager", "records: $it")
            realmRecords = it
        }
    // This is just to ensure that the method didn't return on the first line or in the catch block.
    Log.d("DataManager", "post async call")
}
```

`realm.account` and `realm.record` are extension functions like so:
```kt
val Realm.account: RealmQuery<RealmAccount>
    get() = where(RealmAccount::class.java)
```
When `updateRecordsObservation()` is called on the next cycle by making an async call, the listener works fine.

#### Version of Realm and tooling

Realm version(s): 5.14.0

Realm Sync feature enabled: No

Android Studio version: 3.5.1

Android Build Tools version: 29.0.2

Gradle version: 3.5.1

Which Android version and device(s): Tested on Lollipop real device and API 28 Nexus 5 emulator.

**Comment by cmelchior** [comment]
You need to keep a strong reference to the `RealmResults` in order to trigger its listeners. In your case it is probably being GC'ed.

**Comment by Zhuinden** [comment]
You can put your RealmResults in an IdentityHashMap and then remove it when the change listener is called

**Comment by funct7** [comment]
Changing similar code like so solved the issue: 

```kt
realmAccounts = realm.account.forTrip(tripId).findAllAsync()
realmAccounts.addChangeListener { it, _ ->
    realmAccounts = it
    lastMapper.update(KEY_ACCOUNTS, it)
    updateRecordsObservation()
}
```

Thanks!
