### ISSUE TITLE
RealmConfiguration error

### ISSUE THREAD

**Issue by gajendrapandeya** [realm/realm-java#6630]
- 
- here i am making a realm object and configuring it
- 
     //this method simply add my data to realm
-    private void addAction() {
- 
-         String what = mInputWhat.getText().toString(); // to get input from user
-         long now = System.currentTimeMillis(); // to get current date
- 
- 
-         RealmConfiguration configuration = new RealmConfiguration.Builder().build();
-         Realm.setDefaultConfiguration(configuration);
- 
-         Realm realm = Realm.getDefaultInstance();
- 
-         Drop drop = new Drop(what, now, 0, false);
- 
-         realm.beginTransaction();
-         realm.copyFromRealm(drop);
-         realm.commitTransaction();
-         realm.close();
- 
- 
-     }
- 
- The error is: "Call `Realm.init(Context)` before creating a RealmConfiguration"
- 
- Actually I am making todo list app . In this app i am using Realm database for storing goal and date from the user.
- When i am  using Realm.init() method and passing getActivity() as a context then my "Add it" button doesn't work
- When I am  not using this method then my app is getting crashed.
- What should i do now??
- 
-

**Comment by cmelchior** [comment]
You need to call `Realm.init(context)` before touching any Realm API's. This is commonly done in an Application subclass, see e.g. https://github.com/realm/realm-java/blob/master/examples/introExample/src/main/java/io/realm/examples/intro/MyApplication.java#L29
