### ISSUE TITLE
PermissionManager not found in version 6.0

### ISSUE THREAD

**Issue by selyon** [realm/realm-java#6633]
#### Goal
Build the example app, Full-Sync ToDoList

#### Actual Results
Build fail when using classpath "io.realm:realm-gradle-plugin:6.0.0"

#### Steps & Code to Reproduce
I downloaded the example android project, but inside ProjectsActivity it gives me an error
io.realm.PermissionManager cannot resolve symbol PermissionManager

#### Version of Realm and tooling

Realm version(s): 6.0.0

Realm Sync feature enabled: yes

Android Studio version: 3.5

Android Build Tools version: 3.5.1

Gradle version: 5.4.1

**Comment by cmelchior** [comment]
Yes, we haven't had a chance to update the Full-Sync Todo list tutorial yet, sorry about that.
The `PermissionManager` was removed in 6.0.0 pr. the changelog. The methods now live on `SyncUser`. See https://github.com/realm/realm-java/blob/master/CHANGELOG.md#6002019-10-01
