### ISSUE TITLE
Native crash: [realm-core-5.23.1] Assertion failed: !(ref & 7)

### ISSUE THREAD

**Issue by wuhenzhizao** [realm/realm-java#6634]
#### Goal
No Crash

#### Actual Results

E/REALM   (16667): /home/jenkins/workspace/realm_realm-core_release_5.23.1@5/src/realm/alloc_slab.cpp:686: [realm-core-5.23.1] Assertion failed: !(ref & 7) with (ref, get_file_path_for_assertions()) =  [33554484, "/data/data/*/files/T1RVeE56ST0=.realm"]
E/REALM   (16667): <backtrace not supported on this platform>!!! IMPORTANT: Please send this log and info about Realm SDK version and other relevant reproduction info to help@realm.io.

Thread 28 (crashed)
 0  libc.so + 0x4a640
     r0 = 0x00000000    r1 = 0x00006782    r2 = 0x00000006    r3 = 0x00000008
     r4 = 0xca787978    r5 = 0x00000006    r6 = 0xca787920    r7 = 0x0000010c
     r8 = 0x000002ae    r9 = 0xcc0b4778   r10 = 0xca7872b4   r12 = 0x00000011
     fp = 0x000000ef    sp = 0xca787080    lr = 0xebdacd47    pc = 0xebdaf640
    Found by: given as instruction pointer in context
 1  librealm-jni.so + 0x29e851
     sp = 0xca787094    pc = 0xcc0b4853
    Found by: stack scanning
 2  libc.so + 0x1db2f
     sp = 0xca787098    pc = 0xebd82b31
    Found by: stack scanning
 3  libc.so + 0x19547
     sp = 0xca7870a0    pc = 0xebd7e549
    Found by: stack scanning
 4  librealm-jni.so + 0x29e851
     sp = 0xca7870b4    pc = 0xcc0b4853
    Found by: stack scanning
 5  librealm-jni.so + 0x29e851
     sp = 0xca7870c4    pc = 0xcc0b4853
    Found by: stack scanning
 6  libc.so + 0x172ee
     sp = 0xca7870c8    pc = 0xebd7c2f0
    Found by: stack scanning
 7  librealm-jni.so + 0x18af75
     sp = 0xca7870d0    pc = 0xcbfa0f77
    Found by: stack scanning
 8  librealm-jni.so + 0x18afb9
     sp = 0xca7870d8    pc = 0xcbfa0fbb
    Found by: stack scanning
 9  librealm-jni.so + 0x18b07f
     sp = 0xca7870f0    pc = 0xcbfa1081
    Found by: stack scanning

#### Steps & Code to Reproduce
Only Crashed on some devices，No more info to indicate how to reproduce it

#### Version of Realm and tooling

Realm version(s):  5.14.0

Realm Sync feature enabled: No

Android Studio version: 3.4.2

Android Build Tools version: 

Gradle version: 3.3.2

Which Android version and device(s):

**Comment by bmunkholm** [comment]
We are currently tracking down a related issue, that might also be causing this.
Let us know if you get more info on how to reproduce this.

**Comment by cmelchior** [comment]
@wuhenzhizao Are you using encryption?

**Comment by wuhenzhizao** [comment]
@cmelchior ，yes，we use encryption in production envirionment

**Comment by wuhenzhizao** [comment]
@bmunkholm ，it occurred on few devices  in production environment with less info, so it's hard to reproduce，could you tell me the link of the related issue?

**Comment by cmelchior** [comment]
This one: https://github.com/realm/realm-java/issues/6152#issuecomment-539666096. At least the assertion looks similar.

**Comment by wuhenzhizao** [comment]
@bmunkholm  @cmelchior ，i found some [UTF-16 Crash](https://github.com/realm/realm-java/issues/4987) before，it looks like that realm-core still has some bug when realm data is operated on multiple write thread. while i created an thread-pool with only one core-thread to execute all realm write task，this crash dismissed.

**Comment by cmelchior** [comment]
Should be fixed in 6.0.1 (not released yet), but `6.0.1-SNAPSHOT` should be available. See https://github.com/realm/realm-java/blob/master/README.md#using-snapshots

**Comment by wuhenzhizao** [comment]
@cmelchior ，it reproduced in 6.1.0
