### ISSUE TITLE
misconfiguration of s3 bucket

### ISSUE THREAD

**Issue by MuhammadAhmadSakhawat** [realm/realm-java#6637]
i found that anyone can access your s3 bucket without having aws account.
I have no account of aws thats why i'm not able to perform other operation like Delete file,and mv.
If this bucket is available for public then sorry  for this report.
your s3 bucket is :   realm-ci-artifacts
Example: 
aws s3 ls s3://realm-ci-artifacts/  --no-sign-request
It will show your all data.

**Comment by cmelchior** [comment]
Those artifacts are for public consumption, so that should be safe.
