### ISSUE TITLE
Realm query between doesn't work properly for dates in the bounds

### ISSUE THREAD

**Issue by alcivanio** [realm/realm-java#6638]
#### Goal
I am trying to fetch an object saved on Realm. This object contains a date field. The date of the object is 'Fri Mar 01 00:00:00 EST 2019'. I am using a query 'between' the dates to try to get this object. The dates used are 'Fri Mar 01 00:00:00 EST 2019' and 'Sun Mar 31 23:59:59 EDT 2019', what is basically the very beginning and end of that month. 

#### Actual Results
The query returns empty (when i call find all). The weird thing is that sometimes it actually returns me something. I read the documentation, and for what i understood, the expected behaviour is to have that object being returned.

#### Steps & Code to Reproduce
val query = realm.where(MyDateObject::class.java)
query.between("date", dateReference.beginningOfMonth, dateReference.endOfMonth)
val list = query.findAll()

#### Version of Realm and tooling

Realm version(s): 6.0.0

Realm Sync feature enabled: No

Android Studio version: 3.5.1

Android Build Tools version: ?

Gradle version: ?

Which Android version and device(s): Android 10, Pixel 3XL

**Comment by alcivanio** [comment]
I also opened this question on StackOverflow, in case someone wants to take a look:

https://stackoverflow.com/questions/58452219/problems-on-realm-query-between-dates-when-the-target-date-is-in-bounds?noredirect=1#comment103247990_58452219

**Comment by clementetb** [comment]
Closing due inactivity. Feel free to reopen if the issue persists.
