### ISSUE TITLE
Failure when converting to UTF-8

### ISSUE THREAD

**Issue by tiebenxin** [realm/realm-java#6641]
error msg:
REALM_JNI: Exception has been thrown: Illegal Argument: Failure when converting to UTF-8; error_code = 6;  0xd83c in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_Table.cpp

Process of appearance：
When I save the  Info of a User,who' s name has a emoji，It saved success.
but when I put it in a List, List<User>, and save the list, An error occurred.

How it occurred? and what can I do to fix it?
the relations of tabs:

public User extends RealmObject {
   String name;
}

public Group extends RealmObject {
   RealmList<User> users;
}

the error name is “[orange]Liszt”, [orange] means an orange emoji

**Comment by tiebenxin** [comment]
encryption  isn't enabled

**Comment by cmelchior** [comment]
It means that you are trying to insert something into Realm that isn't valid UTF-8. This can happen if you are doing string manipulation on the input string (e.g. using `String.substring()`) Also, we have seen custom keyboards producing invalid UTF-8.

But if this is something you can reproduce with sample project or unit test, I will happily take a look.

**Comment by tiebenxin** [comment]
Is realm surpport  utf8mb4  character-set? the name with emoji was produced by Mobile end，and I can't input the emoji in Android Studio

**Comment by cmelchior** [comment]
No, we only support UTF-8

**Comment by tiebenxin** [comment]
Why RealmObject can support a emoji in utf8 or utf8mb4  character-set, but RealmList couldn't surpport it?

**Comment by cmelchior** [comment]
There shouldn't be any difference. The problem in your case seems to be that you are only trying to store `0xd83c`. This is what is known as a high surrogate (https://everythingfonts.com/unicode/0xD83C) and this must always be paired with a low surrogate, otherwise, it is invalid UTF-8. See https://en.wikipedia.org/wiki/Universal_Character_Set_characters#Surrogates

So you need to figure out how it is possible for users to input that into Realm.

**Comment by tiebenxin** [comment]
Sorry, I have found a law: when emoji was at the last or midde position in name, like "List[orange] or  Liszt[orange]aa", RealmList can save sucess, but when emoji was at the first postion in name, like [orange]Liszt, RealmList save failed

**Comment by cmelchior** [comment]
Can you create a small sample project that reproduces this? The exact details of how the String and emojii is created matters quite a lot.

E.g the error message you reference only mentions one character (0xd83c), but I assume you are talking about the `Orange` emojii https://emojipedia.org/emoji/%F0%9F%8D%8A/ which should be `0xD83C 0xDF4A` (https://graphemica.com/%F0%9F%8D%8A) so something is missing, which is what Realm complains about.

**Comment by tiebenxin** [comment]
Yeah, but I'm going on holiday in the next few days. So the demo project will be later,I'm sorry for that

**Comment by cmelchior** [comment]
@tiebenxin Any update?
