### ISSUE TITLE
query nothing when using "or()" method

### ISSUE THREAD

**Issue by QiLiKing** [realm/realm-java#6644]
I have got a strange issue for query with "or" method. There is a snippet in my query chain as follows:
`realmQuery.beginGroup();
                for (int i = 0; i < folders.size(); i++) {
                    EdoFolder folder = folders.get(i);
                    realmQuery.equalTo("folderId", folder.pId);
                    if (i < folders.size() - 1) {
                        realmQuery.or();
                    }
                }
 realmQuery.endGroup();`
Result: query nothing!  And still nothing even if I change ` folders.size()` to `2`

change it to:
`List<String> folderIds = ArrayUtil.mapNotNull(folders, f -> f.pId);
  realmQuery.in("folderId", folderIds.toArray(new String[0]));`
Result:still nothing!

But, I can get correct results by one of the following ways:
1.  remove the snippet from chain
2. change it to: 
`realmQuery.equalTo("folderId",folders.get(0).pId);` 
OR `realmQuery.equalTo("folderId",folders.get(1).pId);` 
... 
OR `realmQuery.equalTo("folderId",folders.get(folders.size()-1).pId);`
3. change it to: 
`realmQuery.beginGroup();
                for (int i = 0; i < 1; i++) {
                    EdoFolder folder = folders.get(i);
                    realmQuery.equalTo("folderId", folder.pId);
                }
                realmQuery.endGroup();`

In a word, my folderIds are correct, but result is always empty when I query in more than one folderId!

This issue is hard to reproduce. The realm works normally most of the time.

realm version: 5.14.0

**Comment by QiLiKing** [comment]
If I replace `realmQuery.equalTo("folderId", folder.pId);` with `realmQuery.equalTo("folderId", folder.pId, Case.INSENSITIVE);` OR `realmQuery.contains("folderId", folder.pId);`
All is OK!  WHY???

**Comment by cmelchior** [comment]
It surprises me that you say this issue is hard to reproduce? To me this would indicate that the problem are with the folderId's not the query itself. Is there any chance you can reproduce this in a sample project we can debug?

**Comment by QiLiKing** [comment]
This issue occurs after I restructure my project. Before I do this, realm only create two file: xxx.realm & xxx.realm.lock. Now, realm create an extra file: xxx.realm.note(always 0 Byte). I don't know which codes create this file.  Any help for this issue?   And I will try to create a sample project to reproduce this.

**Comment by QiLiKing** [comment]
Latest news: If I set realm version <=5.15.1, this issue occurs. >=5.15.2, it disappears. Now I set it to 6.0.0 and everything works well.
If anyone knows the reason, please tell me. Thanks. 
Email: zhaoshuo@edison.tech
