### ISSUE TITLE
io.realm.exceptions.RealmMigrationNeededException: Migration is required due to the following errors:

### ISSUE THREAD

**Issue by unengchen** [realm/realm-java#6646]
#### Goal
io.realm.exceptions.RealmMigrationNeededException: Migration is required due to the following errors:

#### Actual Results
io.realm.exceptions.RealmMigrationNeededException: Migration is required due to the following errors:
    - Class 'Cabinet' has been added.
    - Class 'Gun' has been added.
    - Class 'Magazine' has been added.
    - Class 'Room' has been added.
        at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
        at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:171)
        at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:241)
        at io.realm.BaseRealm.<init>(BaseRealm.java:136)
        at io.realm.BaseRealm.<init>(BaseRealm.java:103)
        at io.realm.Realm.<init>(Realm.java:163)
        at io.realm.Realm.createInstance(Realm.java:499)
        at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:355)
        at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:285)
        at io.realm.Realm.getInstance(Realm.java:428)
        at com.zcla.armamentsystem.manager.RealmManager.getRoomRealm(RealmManager.java:175)
        at com.zcla.armamentsystem.fragment.childfragment.ChildConfigRoomFragment.initData(ChildConfigRoomFragment.java:81)
        at com.unengchen.basesdk.view.BaseFragment.onCreateView(BaseFragment.java:45)

#### Steps & Code to Reproduce
migration：
public class RoomMigration implements RealmMigration {
    @Override
    public void migrate(DynamicRealm realm, long oldVersion, long newVersion) {
        RealmSchema schema = realm.getSchema();
        if (oldVersion == 0) {
            // 创表
            RealmObjectSchema gun = schema.create("Gun");
            gun.addField("uid", String.class)
                    .addField("code", String.class)
                    .addField("name", String.class);

            RealmObjectSchema magazine = schema.create("Magazine");
            magazine.addField("uid", String.class, FieldAttribute.PRIMARY_KEY)
                    .addField("code", String.class)
                    .addField("name", String.class);
//
            RealmObjectSchema cabinet = schema.create("Cabinet");
            cabinet.addField("uid", String.class, FieldAttribute.PRIMARY_KEY)
                    .addField("code", String.class)
                    .addField("name", String.class)
                    .addField("lock_code", String.class)
                    .addField("type", int.class)
                    .addRealmListField("gun_list", gun)
                    .addRealmListField("magazine_list", magazine);

            schema.create("Room")
                    .addField("uid", String.class, FieldAttribute.PRIMARY_KEY)
                    .addField("code", String.class)
                    .addField("name", String.class)
                    .addField("lock_code", String.class)
                    .addField("type",int.class)
                    .addField("temperature",String.class)
                    .addField("humidity",String.class)
                    .addField("smoke",String.class)
                    .addField("first_room", boolean.class)
                    .addRealmListField("cabinet_list", cabinet);
            oldVersion++;
        }
    }
}

 realm module：

@RealmModule(classes = {Room.class, Cabinet.class, Gun.class, Magazine.class})
public class RoomModule implements RealmModel {
}

Room：
public class Room extends RealmObject {

    @PrimaryKey
    private String uid;
    private String code;
    private String name;
    private String lock_code;
    private int type; // 1-枪库，2-弹库，3-其他
    private String temperature;     // 温度
    private String humidity;  // 湿度
    private String smoke;   // 烟雾浓度
    private boolean first_room;

    private RealmList<Cabinet> cabinet_list;

    @Ignore
    private boolean selected;
}

Cabinet：
public class Cabinet extends RealmObject {

    @PrimaryKey
    private String uid;
    private String code;
    private String name;
    private String lock_code;
    private int type; // 1-是枪柜，2-是弹柜，3-是综合柜

    private RealmList<Gun> gun_list;
    private RealmList<Magazine> magazine_list;

    @Ignore
    private boolean selected;
}

Gun:
public class Gun extends RealmObject {

    @PrimaryKey
    private String uid;
    private String code;
    private String name;
}

Magazine:
public class Magazine extends RealmObject {

    @PrimaryKey
    private String uid;
    private String code;
    private String name;
}

config:
mRoomInfoRealmConfig = new RealmConfiguration.Builder()
                .name(USER_DATABASE_NAME)
                .schemaVersion(1)
                .modules(new RoomModule())
                .migration(new RoomMigration())
                .build();

call: 
public Realm getRoomRealm(){
        try {
            return Realm.getInstance(mRoomInfoRealmConfig);
        } catch (RealmFileException e) {
            Realm.deleteRealm(mRoomInfoRealmConfig);
            return Realm.getInstance(mRoomInfoRealmConfig);
        }
    }

#### Version of Realm and tooling

Realm version(s): 5.15.1

Realm Sync feature enabled: No

Android Studio version: 3.4

Android Build Tools version: 28

Gradle version: 3.4.1

Which Android version and device(s): 8.0

**Comment by Zhuinden** [comment]
Sounds like you are trying to open the Realm before you actually set this configuration with the migration, is that ever possible?

**Comment by unengchen** [comment]
impossible，set this configuration when app star-up ， open the realm in other activity

**Comment by unengchen** [comment]
@Zhuinden I am so sorry，the realm name is wrong，because the realm name is repeated with other realm，so sorry。
