### ISSUE TITLE
Found staggering difficulties while reading 'Getting started' docs

### ISSUE THREAD

**Issue by Liverm0r** [realm/realm-java#6650]
In your [docs](https://realm.io/docs/java/latest#installation) you misleadingly point out where to find the project level build gradle.

![as_project_screen](https://user-images.githubusercontent.com/14236531/67928255-61945a00-fbdc-11e9-92f7-cb4ea956c816.png)

I don't have any idea what did you mean by that screen. Where is the so called build.gradle file?! I don't have anything like it!

![as_screen](https://user-images.githubusercontent.com/14236531/67928344-9c968d80-fbdc-11e9-890e-a6135c3aa301.jpg)

**Comment by TimofeyTalenfeld** [comment]
Finally at least someone asked this question.
Docs are absolutely not clear! Thanks, dude

**Comment by bmunkholm** [comment]
Thanks for reporting this @Liverm0r!
@TimofeyTalenfeld Don't hold back! If you have stumpled upon things that are unclear, would you mind reporting them? That's about the best way to improve them ;-)
Thanks!

**Comment by Zhuinden** [comment]
That's because you have it set to `Android` tab rather than `Project` tab in the dropdown above the directory selector.

For `Android` tab, you have to open down the `Gradle Scripts`.

**Comment by Liverm0r** [comment]
That's the point. Every android developer knows what is the project build.gradle file. But if you started to point out such an obvious details you are expected to be consistent :)

**Comment by Zhuinden** [comment]
I guess could also add the tab that's selected... :thinking_face:

**Comment by cbush** [comment]
Thanks for raising the issue and for your comments. Added an image indicating where to set the view and the following text:

>To follow along, be sure to be on the “Projects” view in the top left panel. Click the dropdown in the top left corner of Android Studio and select “Projects”:

Hope this helps.
