### ISSUE TITLE
update just modified data

### ISSUE THREAD

**Issue by aabolfazl** [realm/realm-java#6655]
hello guys
i use realm change listener,the problem i have this:
when i set again model value i already have in DB change listener call again!

        Person person = new Person();
        person.setName("Abolfzal");
        person.setId(10);

        DbManager.getInstance().doRealmTask(realm -> {
            realm.executeTransaction(realm1 -> realm1.copyToRealmOrUpdate(person));
        });

        Person person1 = DbManager.getInstance().doRealmTask(realm -> {
            return realm.where(Person.class).equalTo("id", 10).findFirst();
        });

        person1.addChangeListener((realmModel, changeSet) -> {
            Person p = ((Person) realmModel);
            Log.i("abbasiRealm", "onViewCreated: " + p.getName() + " " + p.getId());
        });

       handler.postDelayed(() -> {
            DbManager.getInstance().doRealmTask(realm -> {
                realm.executeTransaction(realm1 -> {
                    person1.setName("Abolfazl");
                    realm1.copyToRealmOrUpdate(person1);
                });
            });
        }, 10000);

**Comment by cmelchior** [comment]
Not sure I understand the problem. You are changing the name inside the transaction so the `person1` object is modified. Which results in the changelistener being triggered. Note that calling `copyToRealmOrUpdate` on a managed object is a no-op. Just setting `person1.setName(...)` is enough

**Comment by Zhuinden** [comment]
The change listener is triggered on changes. This sounds like expected behavior to me.

But to make sure you are always getting the change notifications, you should make the `Person person1;` into a field variable. Otherwise it is a weak reference, and can be GCed.

**Comment by cmelchior** [comment]
Outdated. If this is still a problem, feel free to reopen the issue.
