### ISSUE TITLE
How to add two schemas  from different .realm files to one files?

### ISSUE THREAD

**Issue by rishabhsahrawat** [realm/realm-java#6660]
I am doing everything in Kotlin, but bc of lack of documentation related to that, it is almost impossible to use Realm library. Please add some documentation!
The examples written in Java on realm.io don't even work for Kotlin.

I have two schemas each consisting single class with 2 properties. I want to use both of these in my Android App. I faced some Migration error, so what I understood was that I have to merge these two schemas into one i.e., one of the classes have to be extended into either of the files and then this new file alone will provide the DB. But it is literally impossible even to understand anything via the documentation. There is literally one example which doesn't even help in understanding MIgration.

**Comment by cmelchior** [comment]
It would be much easier to help you if you described in code what you have tried so far. It is very hard to tell exactly what you have done from the description given.

But it sounds like you need to create a `@RealmModule` class listing the model classes part of your 
combined schema. Something like:

```
@RealmModule(classes = arrayOf(Person::class, Dog::class))
class MyModule {
}

val config = RealmConfiguration.Builder().modules(MyModule()).build()
val realm = Realm.getInstance(config)
```

**Comment by Zhuinden** [comment]
> I am doing everything in Kotlin, but bc of lack of documentation related to that, it is almost impossible to use Realm library.

There is a Kotlin Example that shows how to use Realm's Kotlin extensions, and also the best practices regarding how to create Realm model classes: https://github.com/realm/realm-java/tree/dc67440f62fee3637f1e308f6d55b4dc41fce8d5/examples/kotlinExample/src/main/kotlin/io/realm/examples/kotlin/model

(Specifically, `open class` with no-arg constructor, and making properties `var`).

Therefore, it's not impossible, and it is also somewhat documented.

> The examples written in Java on realm.io don't even work for Kotlin.

They should, because of Java/Kotlin interoperability. Do you know any specific examples of cases where it doesn't?

> I have two schemas each consisting single class with 2 properties. I want to use both of these in my Android App.

I assume you mean you have two `@RealmModule` classes and two `RealmConfiguration`s, then?

> I faced some Migration error, so what I understood was that I have to merge these two schemas into one

I'm pretty sure there is no need to merge modules, but you would definitely need to add two separate Migrations for the two separate RealmConfigurations for the two separate RealmModules and Realm files.

It is described in multiple locations, but most precisely in https://stackoverflow.com/a/36498525/2413303 that Migrations are required when:

- a field is added/removed to an existing RealmObject
- a new RealmObject class is added
- an existing RealmObject is removed
- `@Required` is added/removed to an existing field in an existing RealmObject
- `@PrimaryKey` is added/removed to an existing field in an existing RealmObject
- `@Index` is added/removed to an existing field in an existing RealmObject

If any of these changes are applied to any RealmObjects in any schemas in your project that already exist in a Realm file on the disk, then a migration is needed.

You do NOT need to "merge schemas together" to supply a schema migration.

**Comment by rishabhsahrawat** [comment]
Thank you for very quick answers. I appreciate that. Using following objects, I created two RealmDBs 
```
open class JsonDataStorage : RealmObject() { 
    @PrimaryKey
    var id : String = UUID.randomUUID().toString()
    var key : String? = null
    var values : RealmList<Double>? = null
}

open class CSVDataStorage :  RealmObject() {
    var csvUUID : String? = null
    var Label : String? = null
}
```
Now I want to access these DBs (have nothing in common) in the same app in different functions.
On using following function to access first DB (called **rishabs.realm**) with class `JsonDataStorage`, I am facing error `Migration error....`
```
Realm.init()
val JSONconfig = RealmConfiguration.Builder().name("rishabs.realm").build()
val realm = Realm.getInstance(JSONconfig)
```

In order to solve this problem, I went through many suggestions and after that I understood what I explained in my first comment above. As @Zhuinden said, I dont have to merge then can you please share some straight forward way to access these DB files in the app?. I still have to go extensively through your comments above.

**Comment by Zhuinden** [comment]
Those currently are not two separate files. By default, all RealmObjects defined in a given compilation module (in this case, most likely `app` module) are merged together into a single, default schema.

In order to separate RealmObject classes into separate schemas in separate files, you need to use `@RealmModule`, then define two `RealmConfiguration` (with two different names, and the specified modules).

**Comment by rishabhsahrawat** [comment]
I think one mistake I did while writing DBs is that I wrote them one at a time, so I got two files with different names. One is called `rishabs.realm` and `CSV.realm` with properties mentioned above. 

SInce I have two files, I defined two `RealmConfiguration` as following in two different functions-
````
// for first realm file
val JSONconfig = RealmConfiguration.Builder().name("rishabs.realm").build()
val realm = Realm.getInstance(JSONconfig)

// for second realm file
val CSVconfig = RealmConfiguration.Builder().name("CSV.realm").build()
val CSVrealm = Realm.getInstance(CSVconfig)
````
But this is the part giving me `Migration error...`

**Comment by rishabhsahrawat** [comment]
**Based on your first comment above** @Zhuinden 
> I'm pretty sure there is no need to merge modules, but you would definitely need to add two separate Migrations for the two separate RealmConfigurations for the two separate RealmModules and Realm files.

I think I need to do this part. BUt now I can not follow up with the example supplied [here](https://realm.io/docs/java/latest/#migrations). There is no function `getSchema` in kotlin. So I replaced it with `realm.schema.get()` but I might be wrong since there is no documentation on this I could read.

**Comment by rishabhsahrawat** [comment]
Now as per ypur suggestion:-
> I'm pretty sure there is no need to merge modules, but you would definitely need to add two separate Migrations for the two separate RealmConfigurations for the two separate RealmModules and Realm files.

I wrote Migration, as follows, first to only access/use the `rishabs.realm` containing `JsonDataStorage` class, 
`````
open class Migration : RealmMigration {
    override fun migrate(realm: DynamicRealm, oldVersion: Long, newVersion: Long) {
        realm.schema.create("JsonDataStorage").addField("id", String.javaClass, FieldAttribute.PRIMARY_KEY).addField("key", String.javaClass).addRealmListField("values", Double.javaClass)
    }
}
// configuration
val JSONconfig = RealmConfiguration.Builder().schemaVersion(10).name("rishabs.realm").migration(Migration()).build()
`````
but now it is throwing following error-
````
java.lang.IllegalArgumentException: Illegal Argument: Class already exists: 'JsonDataStorage'.
````
Based on my understanding, the error is that I am trying to write a new Realm with the same names/properties that already are there in this file. But if they are already there then why do I need to write another one.

**Comment by Zhuinden** [comment]
> There is no function getSchema in kotlin. So I replaced it with realm.schema

Java getters/setters are replaced with Kotlin property accessors, but this is default Kotlin interop behavior, see https://kotlinlang.org/docs/reference/java-interop.html#getters-and-setters

Realm-Java is a Java library, therefore Kotlin -> Java interop rules apply.

```
// for first realm file
val JSONconfig = RealmConfiguration.Builder().name("rishabs.realm").build()
val realm = Realm.getInstance(JSONconfig)

// for second realm file
val CSVconfig = RealmConfiguration.Builder().name("CSV.realm").build()
val CSVrealm = Realm.getInstance(CSVconfig)
```

You are missing `.module()` definition. Please revise my above post on how to use `@RealmModule`.

**Comment by Zhuinden** [comment]
For migration example, refer to

https://github.com/realm/realm-java/blob/dc67440f62fee3637f1e308f6d55b4dc41fce8d5/examples/migrationExample/src/main/java/io/realm/examples/realmmigrationexample/model/Migration.java#L38-L72

**Comment by rishabhsahrawat** [comment]
After following all the suggestions, I am again receiving Migration error-
Here is what I have done-

`````
@RealmModule(library = true, classes = arrayOf(JsonDataStorage::class, CSVDataStorage::class))
open class JsonDataStorage : RealmObject() { // Class extending RealmObject for JSON file
    @PrimaryKey
    var id : String = UUID.randomUUID().toString()
    var key : String? = null
    var values : RealmList<Double>? = null
}

open class CSVDataStorage : RealmObject() { // Class extending RealmObject for the CSV file.
    var csvUUID : String? = null
    var Label : String? = null
}

open class Migration : RealmMigration {
    override fun migrate(realm: DynamicRealm, oldVersion: Long, newVersion: Long) {
        val mySchema = realm.schema
        if (oldVersion == 0L) {

            val JsonSchema = mySchema.get("JsonDataStorage")
            
        }
        oldVersion.inc()
    }
}

// THE CONFIGURATION. JUST WANNA USE FIRST DB
val JSONconfig = RealmConfiguration.Builder().schemaVersion(1).name("rishabs.realm").modules(JsonDataStorage()).migration(Migration()).build()
val realm = Realm.getInstance(JSONconfig)
`````
I don't know what is still left to do.

**Comment by Zhuinden** [comment]
I recommend reading the exception stack trace, newer versions of Realm include everything regarding the changes that are found to be mismatched against the Realm file schema on disk.

If this is not an app in production yet, consider clearing data of the app, or uninstalling/reinstalling the app.

**Comment by cmelchior** [comment]
@rishabhsahrawat I assume the above answered your questions. If not feel free to re-open this issue.
