### ISSUE TITLE
Android - Realm does not work in a project with more than one module

### ISSUE THREAD

**Issue by luispereira** [realm/realm-java#6661]
#### Goal
* I have 2 modules where realm is located. One handles the database generic and another the database of the actually application. However When I try to add a RealmObject to the @RealmModule class it keeps telling me the RealmObject is not an object.
However, if I change the location of the class to the application database module it actually works...

Exception trying to compile is the following: 

```
e: error: RealmOne could not be added to the module. Only classes extending RealmObject or implementing RealmModel, which are part of this project, can be added.
```

#### Steps & Code to Reproduce
Application Module

* UserRealmModule

```
@RealmModule(classes = [RealmOne::class, RealTwo::class], library = true)
class UserRealmModule
```

Generic Database Module

* RealmOne 

```
open class RealmOne(
    @Required
    @PrimaryKey
    @RealmField(REALM_ONE_ID)
    var id: String = ""
) : RealmObject() 
```

* RealmTwo 

```
open class RealmTwo(
    @Required
    @PrimaryKey
    @RealmField(REALM_TWO_ID)
    var id: String = ""
) : RealmObject() 
```

#### Version of Realm and tooling
Realm version(s): {{io.realm:realm-gradle-plugin:5.8.0 }}

Android Studio version: 3.5.2

Android Build Tools version: 28.0.3

Gradle version: `com.android.tools.build:gradle:3.5.1`

**Comment by Zhuinden** [comment]
Did you add `UserRealmModule` to the RealmConfiguration?

**Comment by luispereira** [comment]
Yes @Zhuinden, but wouldn't impact only in runtime? I'm having an issue in compile time
```
 RealmConfiguration.Builder()
            .name(storageName)
            .schemaVersion(REALM_CURRENT_VERSION)
            .migration(realmMigrate)
            .modules(UserRealmModule())
            .deleteRealmIfMigrationNeeded()
```

**Comment by Zhuinden** [comment]
Ah, now I see it. `UserRealmModule` is supposed to be in the "generic database module", because that is what can expose the RealmObjects of "generic database module" to the "application module" to use.

**Comment by luispereira** [comment]
My problem is when generic database is shared between more than one project, and should not have specific realm object classes (only "application module should have those kind of objects"), is there any way to do this?

**Comment by Zhuinden** [comment]
Your "generic database module" already has classes that `extends RealmObject`. You could probably expose `interface` instead of `open class: RealmObject()` in your generic database module?

**Comment by luispereira** [comment]
The problem with interface is that I did not wanted to set and maintain the `RealmOne` fields in more than one application module. Because `RealmOne` is the same for everyone

**Comment by Zhuinden** [comment]
Well that's why you'd expose the `interface One { val blah: String`, no?

**Comment by cmelchior** [comment]
@luispereira Why not just expose a module from the generic database module and combine them when opening the Realm?

```
 RealmConfiguration.Builder()
            .name(storageName)
            .schemaVersion(REALM_CURRENT_VERSION)
            .migration(realmMigrate)
            .modules(GenericModule(), UserModule())
            .deleteRealmIfMigrationNeeded()
```

**Comment by luispereira** [comment]
> Well that's why you'd expose the `interface One { val blah: String`, no?
Well yeah, but than the @Required, defaults and @RealmFields annotations would need to be set in both applications

@cmelchior that would be awesome, however In my application the "`GenericModule()`" is dependent by each user which I have in `UserRealmModule`, which means I will have a database for each user

**Comment by clementetb** [comment]
Closing due inactivity.

**Comment by Hatzen** [comment]
I am facing the exact same issue using interfaces might work with some duplications.  
It would be nice to avoid this duplicates
