### ISSUE TITLE
Access related object by its ID

### ISSUE THREAD

**Issue by hardysim** [realm/realm-java#6666]
#### Describe your problem or use case
I'm looking for a way to access related objects (`Bar`) directly from `Foo` by their ID (primary key). Basically just like I can access relations via the included Many-to-one / Many-to-many functionality 
but via an ID.

This would help persisting fetched data from a server which does not embed relations as whole objects but a list of the IDs of related objects.

Currently, we need a workaround by adding an additional field to `Foo` which queries related `Bars` in its getter.

```kotlin
open class Foo : RealmObject()
{
  @PrimaryKey
  var id: Int = 0

  var name: String? = null
  var bars: RealmList<Integer> = RealmList()

    val allBars: RealmResults<Bar>
      get() = this.realm
              .where(Bar::class.java)
              .in("id", this.bars.toArray(arrayOf<Int>()))
              .findAll()
}

open class Bar : RealmObject()
{
  @PrimaryKey
  var id: Int = 0

  var name: String? = null
}
```

#### Describe the solution you'd like
It would be great if realm includes this workaround directly. Maybe via an annotation (`@ObjectsById`) which would map `Foo.bars` (the list of IDs) to an list of actual `Bar`-objects? Something magically like `@LinkingObjects` which adds the relation without the need of an migration etc..

#### Additional context
See https://stackoverflow.com/questions/58951131/insert-object-from-json-into-realm-with-relation-based-on-id.

**Comment by hardysim** [comment]
Just found #4627 which seems like the same problem.

**Comment by Zhuinden** [comment]
``` kotlin
  var bars: RealmList<Integer> = RealmList()

    val allBars: RealmResults<Bar>
      get() = this.realm
              .where(Bar::class.java)
              .in("id", this.bars.toArray(arrayOf<Int>()))
              .findAll()
```

I've worked with APIs that sent down a list of IDs and the solution was to also have those classes in Realm, then set up a proper relation `RealmList<Bar>`.

**Comment by hardysim** [comment]
> I've worked with APIs that sent down a list of IDs and the solution was to also have those classes in Realm, then set up a proper relation RealmList<Bar> during save process.

You mean
1. fetch all objects from the server (Foo, Bar)
1. identify related objects by the ID (query B for all matching the ID mentioned in Foo) and add those to the referencing object (Foo)
1. add the "enhanced" object (Foo) to realm (as well as all Bar)

Seems like way more work then querying related objects in this workaround-getter. Is there a performance hit when using this query each time Foo is read instead of having the correct relations set up once? I could think of "no" because a query does not impact performance until actual fields are read, right?

**Comment by Zhuinden** [comment]
> add the "enhanced" object (Foo) to realm (as well as all Bar)

Technically you add `Bar`s first, then you add the `Foo`, and you add the `Bar`s into the managed Foo's RealmList field.

> Is there a performance hit when using this query each time Foo is read instead of having the correct relations set up once? I could think of "no" because a query does not impact performance until actual fields are read, right?

uh. It's mostly so that you can use link queries (`ANY` subquery) and `@LinkingObjects`, but on the flip side, when Realm introduced fine-grained query listeners in Realm 3.0, just having bi-directional RealmLists took a big performance hit and change listeners could take a long time to finish just by having a "cycle" in the schema ( https://github.com/realm/realm-java/issues/4544 ), which hopefully got fixed by now?

Anyways, sure, it's mostly a question of whether you need link queries or not.

**Comment by cmelchior** [comment]
Yeah, this problem should ideally be solved when you import data and it doesn't fit Realms Object model. Querying should be done based on a propert Realm model.

That makes since more or less the same as #4627 so I'll merge it into that one.
