### ISSUE TITLE
Java Build with Core does NOT work

### ISSUE THREAD

**Issue by JirkaKrivanek** [realm/realm-java#6671]
#### Goal

Build my own Realm Database for Android from sources, including building the C++ core.

The reason for also building the Realm C++ Core is that it contains high vulnerabilities - therefore I have to modify the code.

I have to use the MicroFocus Fortify tool to scan the sources. I can provide the list of vulnerabilities separately, there is only a few of it, and only HIGH, no CRITICAL (in addition, there is hundreds of code quality issues, but I am not mandated to fix all those).

*Note:* I tried to report it also [here](https://support.realm.io/support/tickets/5224) but the traffic there is ZERO...

#### Actual Results

My build fails with this error (see it also in a context below):
```
CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
```

#### Steps & Code to Reproduce

I followed the guide here:
https://github.com/realm/realm-java

If I execute this (after all the required setup, for/on MacOS):
```
./gradlew assemble
```
then my build succeeds (after 43 minutes of running 🙂).

But it downloads the pre-built core archives. Which is not trusted. Plus, as I wrote above, the Realm Core contains vulnerabilities, which I have to fix.

I was also able to build the Realm-Core separately (I have the TAR file).

Therefore I need to do the full build by executing this:
```
./gradlew assembleBase -PcoreSourcePath=../../../realm-core
```
then my build fails with this error:
```
CMake Error: CMake was unable to find a build program corresponding to "Ninja".  CMAKE_MAKE_PROGRAM is not set.  You probably need to select a different build tool.
```

I also tried this (no success):
```
./gradlew assembleBase -PcoreSourcePath=../../../realm-core -PbuildTargetABIs=armeabi-v7a
```

I was digging around and inside a lot and found that the 
```
realm-java/realm/realm-library/build.gradle
```
references this cmake file:
```
src/main/cpp/android.toolchain.cmake
```

And that file contains this:
```
Android CMake toolchain file, for use with the Android NDK r5-r10d
set( ANDROID_SUPPORTED_NDK_VERSIONS ${ANDROID_EXTRA_NDK_VERSIONS} -r10d -r10c -r10b -r10 -r9d -r9c -r9b -r9 -r8e -r8d -r8c -r8b -r8 -r7c -r7b -r7 -r6b -r6 -r5c -r5b -r5 "" )
```

But the Realm build guide (linked above) clearly states:
Realm currently requires version r10e of the NDK.

Which all together sounds like a deadlock and a buggy build system - what am I missing here (or better: how to fix it)?

Note: I am currently using CMake 3.6.x - do I have to use any other, very specific version of the CMake?

#### Version of Realm and tooling

Realm version(s): 6.0.1

Realm Sync feature enabled: Do not know - how can I learn this?

Android Studio version: 3.5.2 (but I build on Command LIne, MacOS Terminal)

Android Build Tools version: I have the latest 29.0.2 but I do not know which version is used (I have many versions installed in my Android SDK)

Gradle version: Corresponding to the Android Gradle plugin, I do not know which is configured in your build system

Which Android version and device(s): Multiple, starting with Lollipop

**Comment by cmelchior** [comment]
You need to install Ninja to compile Core manually. If you are using Homebrew `brew install ninja` should do the trick

**Comment by JirkaKrivanek** [comment]
> You need to install Ninja to compile Core manually. If you are using Homebrew `brew install ninja` should do the trick

Thank you for an advice - before doing it, I would like to understand a bit more:

* Yes, I use Homebrew. But regarding Ninja: Is it going to break my standard (normal gradle/Android Studio) builds?

* Also how come that I am able to build Realm-Corer separately but CANNOT build it as part of Realm-Java?

**Comment by bmunkholm** [comment]
@JirkaKrivanek I understand it may be confusing where to report issues, but just for the future, the support channel you used is only for commercial support. The right place is here if you have trouble building core and use it in Java. I don't think many people build their own core and use in Java, so it could be that the instructions here are not complete. If you find other things that are not crystal clear, a PR with updates to the instructions are highly appreciated!

When you have fixed the core issues you need, I would also encourage you to submit a PR in realm-core, so your fixes can come into the main repo and you don't have to maintain this in the future.

**Comment by cmelchior** [comment]
No, installing Ninja should not affect your normal Android builds (at least I have never noticed any issues)

> Also how come that I am able to build Realm-Corer separately but CANNOT build it as part of Realm-Java?

Core is built as part of building Realm Java. We are using CMake to build our native code. The CMake files in Realm Java then call out to the CMake files in Realm Core.

**Comment by JirkaKrivanek** [comment]
> @JirkaKrivanek I understand it may be confusing where to report issues, but just for the future, the support channel you used is only for commercial support. The right place is here if you have trouble building core and use it in Java.

Yes, I already closed the ticket there. It was actually created automatically for me based on an email I sent to some email address I found.

> I don't think many people build their own core and use in Java, so it could be that the instructions here are not complete. If you find other things that are not crystal clear, a PR with updates to the instructions are highly appreciated!

I actually do prepare the SH script which does the build in one shot. It is still NOT complete (I need to include the Realm-Core part with it). Please find the intermediate version below (or attached, if I find out how to attach any file here).

> When you have fixed the core issues you need, I would also encourage you to submit a PR in realm-core, so your fixes can come into the main repo and you don't have to maintain this in the future.

OK, I will try to, but I need to learn first what you mean with the PR (we are using it here in my corporation, but I never done it on GitHub).

Anyways, I think some of it will NOT be acceptable for you (e.g. we need to prevent the ".." in the paths to prevent attacks on file system which may not be acceptable for some of your users who do not care about security at all).

**Comment by JirkaKrivanek** [comment]
```
#!/bin/sh

############################################################################################################################
# Configuration
############################################################################################################################

REALM_SOURCE_VERSION="6.0.1"
REALM_BUILD_VERSION="$REALM_SOURCE_VERSION.1-GTO"
ANDROID_SDK_ROOT_PATH="/Applications/Android/sdk"

GIT_QUIET="-q"
GRADLE_QUIET="-q"

clear

############################################################################################################################
# Pre-cleanup
############################################################################################################################

if [ -d "realm-java" ]; then
    printf "Deleting old sources..."
    rm -rf realm-java
    printf " OK\n"
fi
if [ -d "android-ndk-r10e" ]; then
    printf "Deleting old Android NDK..."
    rm -rf android-ndk-r10e
    printf " OK\n"
fi

############################################################################################################################
# Android NDK
############################################################################################################################

printf "Downloading required Android NDK..."
curl -s -O http://dl.google.com/android/ndk/android-ndk-r10e-darwin-x86_64.bin
if [ "$?" -ne "0" ]; then
    printf " Error\n\n"
    exit 1
fi
printf " OK\n"
printf "Extracting required Android NDK..."
chmod +x android-ndk-r10e-darwin-x86_64.bin
if [ "$?" -ne "0" ]; then
    printf " Error\n\n"
    exit 1
fi
./android-ndk-r10e-darwin-x86_64.bin > /dev/null
if [ "$?" -ne "0" ]; then
    printf " Error\n\n"
    exit 1
fi
rm -f ./android-ndk-r10e-darwin-x86_64.bin
printf " OK\n"
ANDROID_NDK_ROOT_PATH="$PWD/android-ndk-r10e"
printf "Android NDK path: $ANDROID_NDK_ROOT_PATH\n"

############################################################################################################################
# Environment
############################################################################################################################

printf "Setting up environment..."
export ANDROID_HOME="$ANDROID_SDK_ROOT_PATH"
if [ $? -ne "0" ]; then
    printf " Error\n\n"
    exit 1
fi
export ANDROID_NDK_HOME="$ANDROID_NDK_ROOT_PATH"
if [ $? -ne "0" ]; then
    printf " Error\n\n"
    exit 1
fi
printf " OK\n"
printf "ANDROID_NDK_HOME=$ANDROID_NDK_HOME\n"
printf "ANDROID_HOME=$ANDROID_HOME\n"

############################################################################################################################
# GIT: Clone
############################################################################################################################

printf "Cloning sources from GIT..."
git clone https://github.com/realm/realm-java.git --recursive "$GIT_QUIET"
if [ "$?" -ne "0" ]; then
    printf " Error\n\n"
    exit 1
fi
printf " OK\n"

############################################################################################################################
# GIT: Checkout
############################################################################################################################

printf "Checking out version $REALM_SOURCE_VERSION from GIT..."
cd realm-java
git checkout "v$REALM_SOURCE_VERSION" "$GIT_QUIET"
if [ "$?" -ne "0" ]; then
    cd ..
    printf " Error\n\n"
    exit 1
fi
cd ..
printf " OK\n"

############################################################################################################################
# Preparation: Build version
############################################################################################################################

printf "Preparing proprietary build version $REALM_BUILD_VERSION..."
REALM_VERSION_FILE="realm-java/version.txt"
if [ -f "$REALM_VERSION_FILE" ]; then
    rm "$REALM_VERSION_FILE"
fi
printf "$REALM_BUILD_VERSION" > "$REALM_VERSION_FILE"
printf " OK\n"

############################################################################################################################
# Preparation: Gradle local properties
############################################################################################################################

printf "Setting local properties for Gradle..."
REALM_GRADLE_LOCAL_PROPERTIES="realm-java/realm/local.properties"
if [ -f "$REALM_GRADLE_LOCAL_PROPERTIES" ]; then
    rm "$REALM_GRADLE_LOCAL_PROPERTIES"
fi
printf "ndk.dir=$ANDROID_NDK_ROOT_PATH" > "$REALM_GRADLE_LOCAL_PROPERTIES"
printf " OK\n"

############################################################################################################################
# Preparation: Android NDK source properties
############################################################################################################################

printf "Setting source properties for Android NDK..."
ANDROID_NDK_SOURCE_PROPERTIES_FILE="$ANDROID_NDK_ROOT_PATH/source.properties"
if [ -f "$ANDROID_NDK_SOURCE_PROPERTIES_FILE" ]; then
    rm "$ANDROID_NDK_SOURCE_PROPERTIES_FILE"
fi
printf "Pkg.Desc = Android NDK\nPkg.Revision = 10.0.0" > "$ANDROID_NDK_SOURCE_PROPERTIES_FILE"
printf " OK\n"

############################################################################################################################
# Gradle: Build + Deploy to local Maven
############################################################################################################################

printf "Building REALM...\n\n"

cd realm-java

./gradlew "$GRADLE_QUIET" assemble

cd ..

printf "\n\nBuilding REALM: OK\n\n"

############################################################################################################################
# Cleanup
############################################################################################################################

printf "Cleaning up..."
rm -rf realm-java
rm -rf android-ndk-r10e
rm -f "$ANDROID_NDK_SOURCE_PROPERTIES_FILE"
printf " OK\n"

printf "\n\nDONE\n\nPlease find the output of the build in the <HOME>/.m2/repository/io/realm\n\n"

############################################################################################################################
# DONE
############################################################################################################################
```

**Comment by cmelchior** [comment]
Outdated... closing
