### ISSUE TITLE
Realm @LinkingObject does not work @RealmField

### ISSUE THREAD

**Issue by filipkowicz** [realm/realm-java#6672]
#### Goal
Want to use `@LinkingObjects` on fields defined with custom name with `@RealmField`

#### Actual Results
It compiles with "java" field name but crash when accessing field
it does not compile with "RealmField"

by bet it compile validation works agains Realm (Typed) which uses java names but it is executed against dynamic Realm which uses realm field names (how it is stored in DB)

#### Steps & Code to Reproduce
define realmObject with field that has custom name
define another realmObject and define relationship with LinkingObject

#### Version of Realm and tooling

Realm version(s): 5.9.1

Realm Sync feature enabled: No

Android Studio version: 3.6

Android Build Tools version: 3.4.2

Gradle version: 5.1.1

Which Android version and device(s): -

**Comment by Zhuinden** [comment]
Wasn't this fixed in 5.15.0?

**Comment by cmelchior** [comment]
Yes, we fixed a bug around this in 5.15: https://github.com/realm/realm-java/blob/master/CHANGELOG.md#51502019-09-05

But it isn't clear from the above description if this is what happens.

@filipkowicz Can you please try upgrading to latest version (6.0.2) and if that doesn't solve the issue, provide a fully working code sample.

**Comment by filipkowicz** [comment]
it's fixed in new version, sorry for interrupting
