### ISSUE TITLE
Better error message when loading native code

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#6673]
With App Bundle and APK splits, it has become more common that people are sideloading the wrong APK for their device which results in a mismatch of the native code. Right now this results in a rather unfriendly error message like here: https://github.com/realm/realm-java/issues/6635

`MissingLibraryException librealm-jni.so` 

If this happens we should try to detect which architecture the device is running and which binaries are available in the APK so we can provide the developer with better diagnostics (and reduce our support load on the matter).

**Comment by cmelchior** [comment]
This should ideally be fixed upstream. I created a PR against ReLinker here https://github.com/KeepSafe/ReLinker/pull/65. We should update our version of ReLinker once it is hopefully accepted.

**Comment by danpe** [comment]
When will this be fixed/merged?

**Comment by Zhuinden** [comment]
@danpe ask the Relinker side of things, although they seem to have ignored the request.

**Comment by emarc-m** [comment]
Dependency PR https://github.com/KeepSafe/ReLinker/pull/65 on ReLinker side has been merged and released as version `1.4.0`. Apologies for the delay.

**Comment by cmelchior** [comment]
I updated ReLinker to 1.4.0. It will be part of 6.1. Hopefully released end of this week.

**Comment by Tweener** [comment]
Brilliant. Thanks @cmelchior !

**Comment by yesidlazaro** [comment]
@cmelchior still happening on v6.1.0 , on Nexus 5 with android 6.0.1

**Comment by Zhuinden** [comment]
@yesidlazaro but is there a new error message?

**Comment by yesidlazaro** [comment]
@Zhuinden , oh yes ,my fault, i just commented here because there is a issue related with loading native lib , https://github.com/realm/realm-java/issues/6727 . i think you can keep this ossue close. but checkout this new issue please.
