### ISSUE TITLE
How to use two realm DB files from assets folder inside the app?

### ISSUE THREAD

**Issue by rishabhsahrawat** [realm/realm-java#6675]
I have two realm DB files inside assets file. These files were working fine inside the Device File Explorer, however I can not access any data from the files, it returns null.
Note: I deleted the files from the Device File Explorer

Below is my code to access the files from assets folder.
````
// First file
val JSONconfig = RealmConfiguration.Builder().assetFile("rishabs.realm").modules(JsonDataStorage()).schemaVersion(3).build()
val realm = Realm.getInstance(JSONconfig) 

// second file
val CSVconfig = RealmConfiguration.Builder().assetFile("CSV.realm").modules(CSVDataStorage()).schemaVersion(2).build()
val CSVrealm = Realm.getInstance(CSVconfig)
````

Based on the documentations, I guess this is the right way to access these files from assets folder. I am sure they are not empty files, they have data. My question is how to fetch data from them. 
Also, when I executed the command for creating configursation for the first file, I noticed it created a file in Device Explorer with the name `default.realm` and it could access the data from this file but not from the second one. So, my questions, why is it creating a `default.realm` file having the same size as the first file? And if that will always happen when the app is being run on the Android phone then will not it take twice the storage space and also how to set the `schema_version` automatically?
 Please help. Thank you!

**Comment by Zhuinden** [comment]
You forgot to specify the `name("rishabs.realm")` and `name("CSV.realm")`

**Comment by rishabhsahrawat** [comment]
Thank you for your reply. Okay, yes after doing this it works. But why does it create, again these files inside Device File Explorer in Android Studio since they are already available inside the assets folder?.

**Comment by cmelchior** [comment]
The asset folder is compressed inside the APK. You cannot read them directly, this is why the file needs to be copied out first.

**Comment by rishabhsahrawat** [comment]
okay, I understand them. I am sorry, if my questions are too naive I am a bit new in Android and Realm world. So, now I have this question-
1. It gives me a schemaVersion Error if I set a new file name inside `.name()`. I can set it manually to get rid of it, but is there a way to set it automatically.?
Thank you!

**Comment by cmelchior** [comment]
No, the `schemaVersion` is designed to be set by you. If you don't care about the schema version you dont have to set it.

**Comment by rishabhsahrawat** [comment]
okay, that is better but now if I dont' set it I am receiving an error saying `Provided schema version 0 is less than last set version 3`. Now is there a way to fall back to the first version.

**Comment by Zhuinden** [comment]
It means the `assetFile` you provided was at `schemaVersion(3)`. You most likely want to set the schema version that was set on the asset file.

**Comment by rishabhsahrawat** [comment]
In order to fall back to version 0, how can I do that?. Should I just delete the files from assets and paste them again there?.

**Comment by cmelchior** [comment]
You need to recreate the asset file with a schema version of 0.

**Comment by rishabhsahrawat** [comment]
okay thank you both for helping me out. Have a good one!
