### ISSUE TITLE
Enhance io.realm:android-adapters to use or be compatible with AndroidX

### ISSUE THREAD

**Issue by MDNion** [realm/realm-java#6681]
This is an enhancement request.
We use RealmRecyclerViewAdapter from io.realm:android-adapters:2.1.1
It is a great resource, but is now one of the things preventing us from upgrading to AndroidX.
  
Would it be possible to provide a newer version of io.realm:android-adapters that uses or is compatible with AndroidX?
 
https://realm.io/docs/java/latest/adapter/io/realm/RealmRecyclerViewAdapter.html refers to the android.support.v7 namespace.
The RealmRecyclerViewAdapter class extends `android.support.v7.widget.RecyclerView.Adapter<S>`, and it's S type extends `android.support.v7.widget.RecyclerView.ViewHolder`.
  
The AndroidX migration guide at https://developer.android.com/jetpack/androidx/migrate/class-mappings#androidsupportv7 seems to indicate that `android.support.v7.widget.RecyclerView` could be replaced by `androidx.recyclerview.widget.RecyclerView`

In either case, thanks for providing the RealmRecyclerViewAdapter class.  
It has been a great tool.

**Comment by Zhuinden** [comment]
You can also copy-paste the `RealmRecyclerViewAdapter` class as it is only 1 class if I remember correctly, that way it won't be in the way of your migration process.

**Comment by cmelchior** [comment]
We already have it merged actually. It just seems I never got around to actually releasing it 🤦‍♂

**Comment by MDNion** [comment]
> You can also copy-paste the `RealmRecyclerViewAdapter` class as it is only 1 class if I remember correctly, that way it won't be in the way of your migration process.

From what I understand, our migration attempt didn't work specifically because `RealmRecyclerViewAdapter` uses `android.support.v7.widget.RecyclerView.Adapter` which in turn is not compatible with AndroidX.

**Comment by Zhuinden** [comment]
@MDNion if you copy-paste it into your project, then whether it is `android.support.v7` or `androidx.recyclerview.RecyclerView` is actually irrelevant; the moment it is in your codebase, you can just swap out any reference to android.support to its AndroidX counterpart and you won't need the Jetifier anymore.

**Comment by cmelchior** [comment]
AndroidX support was shipped as part of Android Adapters 4.0
