### ISSUE TITLE
io.realm.exceptions.RealmMigrationNeededException  Migration is required due to the following errors: - Class 'RemotePubServie' has been added.

### ISSUE THREAD

**Issue by skyyanyujiangnan** [realm/realm-java#6682]
部分机型会报出
io.realm.exceptions.RealmMigrationNeededException:Migration is required due to the following errors: 
- Class 'RemotePubServie' has been added.
其中下面代码在三个类（登录成功页面，闪屏页面，进入主页面时候）中都有初始化：
    RealmConfiguration config = new RealmConfiguration.Builder()
                    .name(userEntry.getMId() + ".realm")
//                    .schemaVersion(1)
                    .schemaVersion(2).migration(new CustomMigration())
                    .build();
            Realm.setDefaultConfiguration(config);
数据库升级操作如下：
public class CustomMigration implements RealmMigration {
    @Override
    public void migrate(DynamicRealm realm, long oldVersion, long newVersion) {
        RealmSchema schema = realm.getSchema();
        if (oldVersion == 1 && newVersion == 2) {
            if (!schema.contains("RemotePubServie")) {
                RealmObjectSchema remotePubService = schema.create("RemotePubServie");
                remotePubService.addField("messageId", int.class,FieldAttribute.PRIMARY_KEY);
                remotePubService.addField("uid", String.class);
                remotePubService.addField("msg_schedule_type", String.class);
                remotePubService.addField("msg_schedule", String.class);
                remotePubService.addField("service_no_id",String.class);
                remotePubService.addField("service_no_name",String.class);
                remotePubService.addField("extra", String.class);
            }
            //注意这里要++，因为Realm不会自动为其增加
            oldVersion++;
        }

    }

    @Override
    public boolean equals(Object other) {
        if (other == null) {
            return false;
        }
        return getClass() == other.getClass();
    }

    @Override
    public int hashCode() {
        return getClass().hashCode();
    }
}
报错行代码如下：
 nickname = TextUtils.isEmpty(nickname) ? ChatRealmUtil.getUserName(targetId, Realm.getDefaultInstance()) : nickname;
各位大佬帮忙分析下

**Comment by skyyanyujiangnan** [comment]
部分机型会报出
io.realm.exceptions.RealmMigrationNeededException:Migration is required due to the following errors:

Class 'RemotePubServie' has been added.

其中下面代码在三个类（登录成功页面，闪屏页面，进入主页面时候）中都有初始化：
`RealmConfiguration config = new RealmConfiguration.Builder()
.name(userEntry.getMId() + ".realm")
// .schemaVersion(1)
.schemaVersion(2).migration(new CustomMigration())
.build();
Realm.setDefaultConfiguration(config);`
数据库升级操作如下：
`public class CustomMigration implements RealmMigration {
@override
public void migrate(DynamicRealm realm, long oldVersion, long newVersion) {
RealmSchema schema = realm.getSchema();
if (oldVersion == 1 && newVersion == 2) {
if (!schema.contains("RemotePubServie")) {
RealmObjectSchema remotePubService = schema.create("RemotePubServie");
remotePubService.addField("messageId", int.class,FieldAttribute.PRIMARY_KEY);
remotePubService.addField("uid", String.class);
remotePubService.addField("msg_schedule_type", String.class);
remotePubService.addField("msg_schedule", String.class);
remotePubService.addField("service_no_id",String.class);
remotePubService.addField("service_no_name",String.class);
remotePubService.addField("extra", String.class);
}
//注意这里要++，因为Realm不会自动为其增加
oldVersion++;
}

}

@override
public boolean equals(Object other) {
if (other == null) {
return false;
}
return getClass() == other.getClass();
}

@override
public int hashCode() {
return getClass().hashCode();
}
}`
报错行代码如下：
`nickname = TextUtils.isEmpty(nickname) ? ChatRealmUtil.getUserName(targetId, Realm.getDefaultInstance()) : nickname;`

help help help

**Comment by Zhuinden** [comment]
Sounds like you are not handling when schemaVersion is 0 and goes to 1, so 1 to 2 never runs

**Comment by skyyanyujiangnan** [comment]
@Zhuinden 
RealmConfiguration config = new RealmConfiguration.Builder() .name(userEntry.getMId() + ".realm") // .schemaVersion(1) .
schemaVersion(2).migration(new CustomMigration()) .build(); 
Realm.setDefaultConfiguration(config);

this version is2 last  version is 1

**Comment by cmelchior** [comment]
Have you tried adding 

```
if (oldVersion == 0) {
 oldVersion++;
}
```

At the beginning of your migration code?

**Comment by cmelchior** [comment]
I assume the above answered your questions. If not, feel free to reopen.
