### ISSUE TITLE
[Realm MIgration]How to add primaryKey and set value from field in other table

### ISSUE THREAD

**Issue by wuhenzhizao** [realm/realm-java#6683]
```
open class Message : RealmObject() {
    @PrimaryKey
    lateinit var uniqueId: String

    var content: MessageContent? = null
}
```

```
open class MessageContent : RealmObject() {
    var state: Int = 0
}
```

We have two table as above，Message and it's subTable MessageContent，all of theme are not empty in database.

```
open class MessageContent : RealmObject() {
    @PrimaryKey
    lateinit var messageUniqueId: String

    var state: Int = 0
}
```

we hope to add a @PrimaryKey named "messageUniqueId" to MessageContent，set it's value to uniqueId in Message，How can i do it ?

**Comment by Zhuinden** [comment]
Exactly as you've just said, although personally as it seems a Message can only ever have 1 Content, it'd be even easier to just inline all fields of MessageContent into Message and remove the class.

**Comment by cmelchior** [comment]
Closing as outdated. If this is still an issue, feel free to reopen.
