### ISSUE TITLE
[realm-core-5.23.6] Destruction of mutex in use

### ISSUE THREAD

**Issue by wuhenzhizao** [realm/realm-java#6689]
#### Goal
No crash

#### Actual Results
Crashed in rate
12-15 23:07:29.851 E/REALM   (23208): /home/jenkins/workspace/realm_realm-core_release_5.23.6@3/src/realm/util/thread.cpp:185: [realm-core-5.23.6] Destruction of mutex in use
12-15 23:07:29.851 E/REALM   (23208): <backtrace not supported on this platform>!!! IMPORTANT: Please send this log and info about Realm SDK version and other relevant reproduction info to help@realm.io.

#### Version of Realm and tooling

Realm version(s): v6.01

Realm Sync feature enabled: No

Which Android version and device(s): vivo X7

#### More thread info

armARMv1 ARM part(0x4100d030) features: half,thumb,fastmult,vfpv2,edsp,neon,vfpv3,vfpv4,idiva,idivt8 CPUs

Thread 40 (crashed)
 0  libc.so!tgkill + 0xc
     r0 = 0x00000000    r1 = 0x00005b02    r2 = 0x00000006    r3 = 0x00000000
     r4 = 0xdb6dddd8    r5 = 0x00000006    r6 = 0x0000000b    r7 = 0x0000010c
     r8 = 0x000000b9    r9 = 0xdc19ab4c   r10 = 0xffffffff   r12 = 0x00005b02
     fp = 0xdb6ddbd8    sp = 0xdb6dd918    lr = 0xf7541b61    pc = 0xf7567b88
    Found by: given as instruction pointer in context
 1  libc.so!pthread_kill + 0x36
     r4 = 0xdb6dddd8    r5 = 0x00000006    r6 = 0x0000000b    r7 = 0x0000010c
     r8 = 0x000000b9    r9 = 0xdc19ab4c   r10 = 0xffffffff    fp = 0xdb6ddbd8
     sp = 0xdb6dd918    pc = 0xf7541b61
    Found by: call frame info
 2  librealm-jni.so + 0x2acb2e
     sp = 0xdb6dd92c    pc = 0xdc19ab30
    Found by: stack scanning
 3  libc.so!raise + 0xc
     sp = 0xdb6dd930    pc = 0xf754277f
    Found by: stack scanning
 4  libc.so!__libc_android_abort + 0x26
     sp = 0xdb6dd938    pc = 0xf753eff9
    Found by: stack scanning
 5  librealm-jni.so + 0x2acb2e
     sp = 0xdb6dd950    pc = 0xdc19ab30
    Found by: stack scanning
 6  libc.so!abort + 0x6
     sp = 0xdb6dd960    pc = 0xf753d558
    Found by: stack scanning
 7  librealm-jni.so + 0x198055
     r3 = 0x00000000    sp = 0xdb6dd968    pc = 0xdc086057
    Found by: call frame info
 8  librealm-jni.so + 0x198099
     sp = 0xdb6dd970    pc = 0xdc08609b
    Found by: stack scanning
 9  librealm-jni.so + 0x1980f1
     sp = 0xdb6dd988    pc = 0xdc0860f3
    Found by: stack scanning

**Comment by Zhuinden** [comment]
This is fixed in Core 5.23.7.

But that's not released yet on Realm-Java side.

**Comment by wuhenzhizao** [comment]
@Zhuinden Great
