### ISSUE TITLE
Realm objects can only be accessed on the thread they where created.

### ISSUE THREAD

**Issue by Queatz** [realm/realm-java#669]
Doing a testing transition from GreenDAO to Realm and it getting this all over the place.  Would be nice to be able to reference objects across threads.

For example, in my Android application, I have a User object in the Application class.  I naturally need to check the user from virtually anywhere, which seems to call for extra work for the programmer and more calls to the db in Realm.

**Comment by manmohansoni** [comment]
The following method is not working


 Realm.getInstance(getContext())

**Comment by beeender** [comment]
@manmohansoni See https://realm.io/docs/java/latest/#configuring-a-realm

`Realm.getInstance(Context)` API has been removed.

**Comment by Zeyad-37** [comment]
you can use the copyFromRealm() method, to have a copy of your users and save it globally and use it where ever you want.

**Comment by Zhuinden** [comment]
Although you typically just need to send primary keys between the threads and requery the object if it's needed.

**Comment by Zhuinden** [comment]
The tricky thing is that if you have a detached object, then it's unlikely to be managed properly unless you listen to Realm updates for the given table *somewhere.
