### ISSUE TITLE
Obfuscation causes crashes on REALM

### ISSUE THREAD

**Issue by JirkaKrivanek** [realm/realm-java#6690]
#### Goal

Deliver AAR which internally uses RELM. Hide the realm usage evidences by obfuscation as much as possible.

#### Actual Results

The final app using the AAR (which in turns embeds REALM) is crashing if the AAR is obfuscated and repackaged (we are using DexGuard, as ProGuard is not considered secure enough in our case).

If I just disable the obfuscation using `-dontobfuscate` then things start working like a charm...

This is the exception I have:
```
java.lang.AbstractMethodError: abstract method "java.util.Map io.realm.internal.RealmProxyMediator.getExpectedObjectSchemaInfoMap()"
        at io.realm.Realm.createExpectedSchemaInfo(Realm.java:192)
        at io.realm.Realm.<init>(Realm.java:163)
        at io.realm.Realm.createInstance(Realm.java:499)
        at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:355)
        at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:285)
        at io.realm.Realm.getInstance(Realm.java:428)
        at com.gemalto.mbi.common.internal.realm.c.open(MbiRealmPersistingFacility.java:149)
        at util.n.ad.open(MbiPersisterImpl.java:91)
        at util.n.X.b(MbiBioOperationManagerImpl.java:738)
        at util.n.X.load(MbiBioOperationManagerImpl.java:728)
        at controller.init.ControllerContextImpl.load(ControllerContextImpl.java:400)
        at controller.di.manager.operations.command.RefreshOperations.execute(RefreshOperations.java:45)
        at controller.di.manager.common.AbstractCommand.run(AbstractCommand.java:59)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

Note: We do not obfuscate code yet, only class/method/field names.

#### Steps & Code to Reproduce

- Generate AAR which embeds REALM and enable obfuscation
- Use the AAR in the target App
- App crashes (see the stack trace above)

I tried to add a rule to keep the class from the stack trace `-keep class io.realm.internal.RealmProxyMediator { *; }`. Unfortunately it did not help, things are not so easy...

#### Version of Realm and tooling

Realm version(s): 6.0.1

Realm Sync feature enabled: No

Android Studio version: 3.5.2

Android Build Tools version: Implied by the latest Gradle plugin

Gradle version: Latest implied by the Android Gradle plugin

Which Android version and device(s): Many different (the issue seems to be independent)

**Comment by JirkaKrivanek** [comment]
This is the setup of my RALM:

```
    @Override
    public void open() {
        MbiLogger.d(toString(), "Open...");
        if (mRealmInst != null) {
            throw new IllegalStateException();
        }
        synchronized (MbiRealmPersistingFacility.class) {
            if (!mRealmDirectory.isDirectory() && !mRealmDirectory.mkdirs()) {
                throw new IllegalStateException();
            }
            final RealmConfiguration.Builder builder = new RealmConfiguration.Builder();
            builder.directory(mRealmDirectory);
            builder.name(mRealmName);
            if (mRealmKey != null) {
                builder.encryptionKey(mRealmKey.clone());
            }
            builder.addModule(new MbiRealmModule());
            final RealmConfiguration configuration = builder.build();
            mRealmInst = Realm.getInstance(configuration);
        }
        MbiLogger.d(toString(), "Open: OK");
    }
```

And this is the module:
```
@RealmModule(library = true, classes = {A.class, B.class})
class MbiRealmModule {

}
```

**Comment by JirkaKrivanek** [comment]
So I found out that I have to add this rule to my obfuscation config:

`-keep class io.realm.MbiRealmModuleMediator { *; }`

The class is generated by the REALM magic on background somehow.

So my last question before I will close this bug:
- Is this a proper solution or do I miss anything important here?

**Comment by JirkaKrivanek** [comment]
Another question: I found these rules in the REALM AAR:

```
# Realm commons

-dontwarn rx.Observable
-dontnote rx.Observable

-dontnote android.security.KeyStore
-dontwarn okio.Okio
-dontwarn okio.DeflaterSink

-dontnote com.android.org.conscrypt.SSLParametersImpl
-dontnote org.apache.harmony.xnet.provider.jsse.SSLParametersImpl
-dontnote sun.security.ssl.SSLContextImpl

-keep class io.realm.annotations.RealmModule
-keep @io.realm.annotations.RealmModule class *
-keep @interface io.realm.annotations.RealmModule { *; }
-keep class io.realm.annotations.RealmModule { *; }

-keep class io.realm.internal.Keep
-keep @io.realm.internal.Keep class * { *; }

-keep class io.realm.internal.KeepMember
-keep @io.realm.internal.KeepMember class * { @io.realm.internal.KeepMember *; }

-keep class io.realm.RealmCollection
-keep class io.realm.OrderedRealmCollection
-keepclasseswithmembernames class io.realm.** { native <methods>; }
```

It seems that it causes most of the REALM unobfuscated: Is that really an intention to keep most of the REALM?

Or do I miss something important here?

**Comment by cmelchior** [comment]
We try to make it possible to obfuscate as much of possible of the Realm code, but any code that is called through reflection or from JNI cannot be obfuscated, unfortunately. This is the primary reason for the `@Keep` and `@KeepMember` annotations. 

Realm Module definitions from other Gradle modules are looked up through reflection which is why they cannot be obfuscated, but that should already be covered by these rules:

```
-keep class io.realm.annotations.RealmModule
-keep @io.realm.annotations.RealmModule class *
-keep @interface io.realm.annotations.RealmModule { *; }
-keep class io.realm.annotations.RealmModule { *; }
```
as all our mediators have the `@RealmModule` annotation. I don't know why that doesn't work for you out of the box 🤔

**Comment by JirkaKrivanek** [comment]
Problem solved, my Realm usage is NOT as simple as just an end-app. And because Realm integration via the Gradle plugin hides a lot of matters/issues, also the obfuscation rules did not reach the DexGuard (yes, we are using DexGuard, not ProGuard/R8 - as there are considered almost useless, regarding the protection quality).

I am closing this ticket...

**Comment by Simon-Raes** [comment]
@JirkaKrivanek What was the fix you ended up using? We're running into the exact same issue at the moment (a library using Realm, causing a runtime crash in a Dexguard-protected app that uses it).

**Comment by JirkaKrivanek** [comment]
@Simon-Raes The rules mentioned above were leading to working product (no more ugly exceptions).

The fact that it is actually NOT fully obfuscated was mad the "accepted risk" (better than keep it completely unobfuscated) in our risk management process.

I am afraid that is all we could do for it, as the Realm design seems to be focusing more on performance and functionality than on security...
