### ISSUE TITLE
slower build in intranet 

### ISSUE THREAD

**Issue by chouex** [realm/realm-java#6691]
#### Describe your problem or use case
task app:transformClassesWithRealmTransformerForDebug will add 6 sec build time in intranet environment

by analytic the network traffic found out it wait for dns query api.mixpanel.com until timeout. (due to unable connect on internet)

#### Describe the solution you'd like
after add api.mixpanel.com to hosts the execute time of task app:transformClassesWithRealmTransformerForDebug will less than 1000ms.

solution:
how to disable realm analytics in my project?
or not try to access internet while gradle offline flag is on.

#### Additional context
I already set --offline flag on in gradle

realm-java:6.0.0 and 6.0.2

**Comment by cmelchior** [comment]
Sounds like something we should easily be able to detect and fix. I'll look into it.

**Comment by cmelchior** [comment]
Fixed in #6692
