### ISSUE TITLE
Caused by com.getkeepsafe.relinker.MissingLibraryException librealm-jni.so

### ISSUE THREAD

**Issue by AnkurChitranshiBOL** [realm/realm-java#6699]
**Goal**
Successfully init the Realm object

**Actual Results**
com.getkeepsafe.relinker.ApkLibraryInstaller.installLibrary (ApkLibraryInstaller.java:123)
com.getkeepsafe.relinker.ReLinkerInstance.loadLibraryInternal (ReLinkerInstance.java:180)
com.getkeepsafe.relinker.ReLinkerInstance.loadLibrary (ReLinkerInstance.java:136)
com.getkeepsafe.relinker.ReLinker.loadLibrary (ReLinker.java:70)
com.getkeepsafe.relinker.ReLinker.loadLibrary (ReLinker.java:57)
io.realm.internal.RealmCore.loadLibrary (RealmCore.java:60)
io.realm.Realm.initializeRealm (Realm.java:322)
io.realm.Realm.init (Realm.java:265)
com.gravty.sdk.GravtySDK.init (GravtySDK.java:28)
com.gravty.everyday.viewmodels.BaseViewModel.setUp (BaseViewModel.java:75)
com.gravty.everyday.viewmodels.BaseViewModel<init> (BaseViewModel.java:64)
java.lang.reflect.Constructor.newInstance (Constructor.java)java.lang.reflect.Constructor.newInstance (Constructor.java:288)
androidx.lifecycle.ViewModelProvider$AndroidViewModelFactory.create (ViewModelProvider.java:230)androidx.lifecycle.ViewModelProvider.get (ViewModelProvider.java:164)
androidx.lifecycle.ViewModelProvider.get (ViewModelProvider.java:130)
com.gravty.everyday.views.activities.BaseActivity.onCreate (BaseActivity.java:53)
com.gravty.everyday.views.activities.SplashActivity.onCreate (SplashActivity.java:34)
android.app.Activity.performCreate (Activity.java:5989)
android.app.Instrumentation.callActivityOnCreate (Instrumentation.java:1106)
android.app.ActivityThread.performLaunchActivity (ActivityThread.java:2283)
android.app.ActivityThread.handleLaunchActivity (ActivityThread.java:2392)
android.app.ActivityThread.access$800 (ActivityThread.java:156)
android.app.ActivityThread$H.handleMessage (ActivityThread.java:1308)
android.os.Handler.dispatchMessage (Handler.java:102)
android.os.Looper.loop (Looper.java:135)
android.app.ActivityThread.main (ActivityThread.java:5278)
java.lang.reflect.Method.invoke (Method.java)java.lang.reflect.Method.invoke (Method.java:373)
com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run (ZygoteInit.java:903)
com.android.internal.os.ZygoteInit.main (ZygoteInit.java:698)

**Steps & Code to Reproduce**
I was just initializing the realm object in oncreate()  of launcher activity.

**Version of Realm and tooling**
io.realm:android-adapters:2.1.1
io.realm:realm-gradle-plugin:6.0.0

Realm Sync feature enabled: Don't know

**Android Studio version:** 3.5

**Android Build Tools version:** com.android.tools.build:gradle:3.5.3

**Gradle version:** 5.4.1

**Which Android version and device(s): ?** 
**Devices:** Mi 9X, Samsung Galaxy A70,  viov s1
**Android version:** 5.1

**Note:**    Firebase showing that 80% are rooted devices. This crash logged in Firebase as 10 crashes and 4 users.

**Comment by Zhuinden** [comment]
> io.realm:android-adapters:2.1.1

Should be using at least `3.0.0`.

**Comment by cmelchior** [comment]
This sounds like https://github.com/realm/realm-java/issues/6673, so will be merging it into that one.
