### ISSUE TITLE
Potential memory leak: Passing Realm instance as a parameter in RealmRecyclerViewAdapter

### ISSUE THREAD

**Issue by woshiieugene** [realm/realm-java#6700]
Hi, lately I have been experiencing some app performance issue and am wondering if there is there any correlation in passing realm instance into a realm recyclerview adapter which will may impact app performance? 

My adapter  constructor looks like this: 

    private Realm realm;
    private Context context;

    public MyAdapter(Context context,  Realm realm) {
        super(articles, true);
        this.context = context;
        this.realm = realm;
    }

and my Adapter class extends `RealmRecyclerViewAdapter`. 
Assuming I'm passing in an open instance of realm into this adapter, will it cause a memory leak? 

Assuming of course, within this adapter itself, some realm operation/queries are in operation. 

Curious. 
Thanks in advance for any advice!

**Comment by Zhuinden** [comment]
>  if there is there any correlation in passing realm instance into a realm recyclerview adapter which will may impact app performance?

nope

> Assuming I'm passing in an open instance of realm into this adapter, will it cause a memory leak?

nope

> Assuming of course, within this adapter itself, some realm operation/queries are in operation.

That depends on what you're doing. Writes on the UI thread for example can definitely impact app performance.

**Comment by cmelchior** [comment]
Closing as answered. Please reopen if this is not the case.
