### ISSUE TITLE
Handling realm in multiple thread

### ISSUE THREAD

**Issue by HosseinA** [realm/realm-java#6705]
In our project for several operations, we create different threads and do realm transaction in each one of them. But in the mean time we got several crash reports regarding the "out of memory" problem. we believe that the source of problem is having multiple instances of realm in each of the threads and the queue for transactions.
Do you have any recommendation for solving this problem?

**Comment by Zhuinden** [comment]
If you are using `getInstance()` but not `close()` and you are neither using `try(Realm realm = Realm.getDefaultInstance()) {` or `Realm.getDefaultInstance().use { realm ->` then you should be doing at least one of those two.

**Comment by HosseinA** [comment]
we are using `try(Realm realm = Realm.getDefaultInstance())` in our project. so we are `close()` our instance. do you have any idea?

**Comment by Zhuinden** [comment]
You can also try to constrain the number of background thread Realms by running writes on a single-thread executor (Realm transactions are blocking across all threads anyway).

**Comment by cmelchior** [comment]
It would be nice to know exactly what kind of memory errors you are seeing? Opening a Realm on many threads shouldn't lead to running out memory as such. Trying to write too much data in a single transaction could cause this, but it would have to be really large inserts in that case.

**Comment by rorbech** [comment]
In 7.x there is also a config option on `RealmConfiguration` called `maxNumberOfActiveVersions()` which can help shed some light on issues with to many overlapping transactions. 

Closing as outdated.
