### ISSUE TITLE
CHANGED PROPERTIES EVENT LISTENER

### ISSUE THREAD

**Issue by Kreateyou** [realm/realm-java#6706]
#### Describe your problem or use case
Have an event listener feature to listen to realm object being saved and returning only the attributes that have changed during update or entire object attributes if its a new realm object This will be important if you you need to keep track of what changed during an update

**Comment by Zhuinden** [comment]
This already exists: https://realm.io/docs/java/latest/api/io/realm/RealmObjectChangeListener.html
