### ISSUE TITLE
How to search/filter in realm database?

### ISSUE THREAD

**Issue by cemalsayin** [realm/realm-java#6707]
Hi, I want to create a search view in my realm db, how can i make a search/filter in listview or recycler with search view. I found [that](https://academy.realm.io/posts/android-search-text-view/) tutorial in academy but it archived now i cant use it. I'm waiting your helps or advices. Could you help me please?

**Comment by Zhuinden** [comment]
Check https://github.com/realm/realm-java/issues/2887#issuecomment-221972396
