### ISSUE TITLE
How to know wether there is a table in my database or not?

### ISSUE THREAD

**Issue by Catherineliujj** [realm/realm-java#6709]
I am using Realm datebase. Now I have problem in knowing there is a table in my database?

**Comment by Zhuinden** [comment]
Well if you're missing any tables, the Realm migration will run, and you'll need to add it to the schema.

**Comment by Catherineliujj** [comment]
> Well if you're missing any tables, the Realm migration will run, and you'll need to add it to the schema.
> 
> If you didn't increment the schema version number and define a migration, and you didn't set deleteIfMigrationNeeded, then it'll give you an exception that'll tell you that you have a missing table.
@Zhuinden 
Thank you. Maybe I didn`t describe my problem well. Then agree me describe its details.
I use table A in a component, but when I package this component separately, table A may not exist and is not created, I need to know wether it exsist or not to decide which action I should take.

**Comment by Zhuinden** [comment]
Well, if you add the table with a `@RealmModule` and it's not there, then it will trigger a migration.

**Comment by Catherineliujj** [comment]
@Zhuinden 
I think this has nothing to do with the old and new versions of realm, so it does not need to be migrated

**Comment by Catherineliujj** [comment]
@Zhuinden 
This is other database`s method, I find it on the Intenet.
`    java.sql.Connection con = getYourConnection();  
         
    ResultSet rs = con.getMetaData().getTables(null, null, "yourTable", null);  
    if (rs.next()) {  
    //yourTable exist  
    }else {  
    //yourTable not exist  
    } `

**Comment by Zhuinden** [comment]
Okay, technically you can check if Realm has a table with a given name using 

``` kotlin
val dynamicRealm = DynamicRealm.getInstance(realmConfiguration)
val schema = dynamicRealm.schema
val hasTable = schema.get("MyTableName") != null
```

**Comment by Catherineliujj** [comment]
Thank you very much, I will try it.

**Comment by rorbech** [comment]
Closed as question seems to have been answered.
