### ISSUE TITLE
Illegal Argument: Provided schema version 32 is less than last set version 33.

### ISSUE THREAD

**Issue by KenChoi1992** [realm/realm-java#6714]
#### Goal
No such error

#### Actual Results
My app is normal when first install, this error happens if I not using my app after few hours, I can't figure out any solution. If I use my app frequently, everything is just fine.

#### Steps & Code to Reproduce
Getting realm instance crashed.
```
if (configuration == null) {
                    val dbMigration = DbMigration()
                    configuration = RealmConfiguration.Builder()
                            .schemaVersion(dbMigration.newestVersion.toLong())
                            .migration(dbMigration)
                            .rxFactory(RealmObservableFactory())
                            .build()
                }
                return Realm.getInstance(configuration!!)
```
DBMigration:
```
public class DbMigration implements RealmMigration {
    @Override
    public void migrate(@NonNull DynamicRealm realm, long oldVersion, long newVersion) {
        RealmSchema schema = realm.getSchema();
        long version = oldVersion;
        if (version == 0) {
            RealmObjectSchema petSchema = schema.get("User");
            if (petSchema != null) {
                petSchema.addField("showTogether", boolean.class);
            }
            version++;
        }
       ...
       if (version == 32) {
            ...
            version++;
        }
    }

    int getNewestVersion() {
        return 33;
    }
}
```

crash log:
```
Caused by: java.lang.IllegalArgumentException: Illegal Argument: Provided schema version 32 is less than last set version 33.
        at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
        at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:171)
        at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:241)
        at io.realm.BaseRealm.<init>(BaseRealm.java:135)
        at io.realm.BaseRealm.<init>(BaseRealm.java:103)
        at io.realm.Realm.<init>(Realm.java:163)
        at io.realm.Realm.createInstance(Realm.java:499)
        at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:341)
        at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:284)
        at io.realm.Realm.getInstance(Realm.java:428)
        at cn.lianqinba.strings.data.db.AppDbHelper$Companion.getInstance(AppDbHelper.kt:37)
```

#### Version of Realm and tooling

Realm version(s): io.realm:realm-gradle-plugin:5.9.0

Realm Sync feature enabled: No

Android Studio version: 3.5.2

Android Build Tools version: 28.0.3

Gradle version: 5.4.1-all

Which Android version and device(s): Android 9, Vivo iQOO

**Comment by Zhuinden** [comment]
Interesting. Where does the 32 still come from?

**Comment by KenChoi1992** [comment]
@Zhuinden  I also want to know why.

**Comment by KenChoi1992** [comment]
Another wired thing, when I try to reinstall my app,  Android Studio show INSTALL_FAILED_VERSION_DOWNGRADE error, but I never change my versionCode ever.

**Comment by cmelchior** [comment]
Could it be caused by debug builds on the phone with the same package name?

**Comment by cmelchior** [comment]
Or if you are using "Apply Changes" in Android Studio, it might be some caching going wrong. That feature isn't exactly known to be bug-free.

**Comment by KenChoi1992** [comment]
@cmelchior But debug builds never show INSTALL_FAILED_VERSION_DOWNGRADE error before, until I encounter the Illegal Argument bug I mentioned above.

**Comment by KenChoi1992** [comment]
@Zhuinden @cmelchior I guess realm db version has been downgraded for some reason, that's why I reinstall app show INSTALL_FAILED_VERSION_DOWNGRADE error.

**Comment by cmelchior** [comment]
`INSTALL_FAILED_VERSION_DOWNGRADE` is an Android OS error, not a Realm one. You get that if the version code of your app is lower than the one installed.

**Comment by cmelchior** [comment]
How do you define the version code in your gradle file?

**Comment by KenChoi1992** [comment]
```
defaultConfig {
    versionCode 148
    versionName "2.4.2"
}
```
I'm not change versionCode unless app need publish new version.

**Comment by cmelchior** [comment]
Weird, maybe caused by accidentally building from a different git branch with a different version number?

**Comment by KenChoi1992** [comment]
@cmelchior These days I encounter the bug 100%, I will try to clean Android Studio cache anyway.

**Comment by KenChoi1992** [comment]
Not working, the bug appear in next day.

**Comment by KenChoi1992** [comment]
Why `OsRealmConfig.nativeCreate(config.getPath(), false, true)` would return version value 32 after dozens minutes not using app. The config path is same as install, and `syncEnabled` is never set

**Comment by cmelchior** [comment]
I don't know. It isn't something the Realm library is doing. Is there any chance the file is being manipulated from elsewhere? E.g. being replaced by a backed up file?

**Comment by KenChoi1992** [comment]
@cmelchior No, I never access realm file. Previous versions are normal, until I upgrade db version to 33, but I have done realm migrate and no error to run. Don't know why realm file would be changed.

**Comment by KenChoi1992** [comment]
After I upgrade db version to 34, the error still show 32:
```
REALM_JNI: jni: ThrowingException 1, Provided schema version 32 is less than last set version 34., .
REALM_JNI: Exception has been thrown: Illegal Argument: Provided schema version 32 is less than last set version 34.
Caused by: java.lang.IllegalArgumentException: Illegal Argument: Provided schema version 32 is less than last set version 34.
        at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
        at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:171)
        at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:241)
        at io.realm.BaseRealm.<init>(BaseRealm.java:135)
        at io.realm.BaseRealm.<init>(BaseRealm.java:103)
        at io.realm.Realm.<init>(Realm.java:163)
        at io.realm.Realm.createInstance(Realm.java:499)
        at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:341)
        at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:284)
        at io.realm.Realm.getInstance(Realm.java:428)
        at cn.lianqinba.strings.data.db.AppDbHelper$Companion.getInstance(AppDbHelper.kt:37)
```

**Comment by KenChoi1992** [comment]
@cmelchior Will realm execute  db migration even db version not changed?

**Comment by KenChoi1992** [comment]
@cmelchior if `getTotalGlobalRefCount()` is not equal to 0 means realm instance has not close correctly? My logcat always show warning `Remember to call close() on all Realm instances`

**Comment by cmelchior** [comment]
Yes, it means that a Realm is being GC'ed instead of being correctly closed.

**Comment by KenChoi1992** [comment]
That's why cause this bug?

**Comment by KenChoi1992** [comment]
@cmelchior After  torturing me about two weeks, I fixed this bug by upgrading `versionCode` in build.gradle, can't believe it!!!  Is there has any relation between `versionCode` and realm schema version?
