### ISSUE TITLE
有没有支持复杂查询的？比如查询聊天记录

### ISSUE THREAD

**Issue by zhoufeng1213** [realm/realm-java#6716]
我需要查询私人聊天记录，比如在一个视频会议中，有私聊的功能，只把聊天数据存本地，要查询两个人的聊天记录，那么条件就需要
1、会议号equalsTo
2、聊天类型-私聊equalTo
3、（发送人id-equalTo 本人 并且 接收人id-equalTo 对方）or （接收人id-equalTo 本人 并且 发送人id-equalTo 对方）
这三个条件的话realm无法组合起来？
请问有什么办法能组合起来呢？

**Comment by bmunkholm** [comment]
@zhoufeng1213 I'm sorry but we can only provide support in english.
