### ISSUE TITLE
when I used Gson.toJson(realmList) , it didn't work。

### ISSUE THREAD

**Issue by unengchen** [realm/realm-java#6719]
#### Goal
when I used Gson.toJson(realmList) , it didn't work，and have a error。
if I want to get the json from realmlist , I need to build every object(like new User())  and copy value ? 

#### Actual Results
java.lang.StackOverflowError: stack size 1038KB

#### Steps & Code to Reproduce
 Gson gson = new GsonBuilder().setExclusionStrategies(new ExclusionStrategy() {
                @Override
                public boolean shouldSkipField(FieldAttributes f) {
                    return f.getDeclaringClass().equals(RealmObject.class);
                }

                @Override
                public boolean shouldSkipClass(Class<?> clazz) {
                    return false;
                }
            }).create();
            for (User user : users) {
                String userUid = user.getUser_uid();
                RealmList<Face> faceList = user.getFace_list();
                String faJson = gson.toJson(faceList);
                String faceImage = FileUtils.imageToBase64(user.getUser_photo_path());
                List<Fp> fpList = user.getFp_list();
                String fpJson = gson.toJson(fpList);
                String userPassword = user.getUser_password();
                mSocketManager.uploadUser(userUid, faJson,faceImage, fpJson, userPassword);

            }

#### Version of Realm and tooling

Realm version(s): 6.0.2

Realm Sync feature enabled: NO

Android Studio version: 3.5

Android Build Tools version: 28

Gradle version: 3.5.2

Which Android version and device(s): 8.0，Rk3288

**Comment by Zhuinden** [comment]
`for (User user : users) {` you want to use `realm.copyFromRealm(users)` for this loop.

**Comment by unengchen** [comment]
thanks
