### ISSUE TITLE
RealmObject.isValid() 

### ISSUE THREAD

**Issue by ultimateHandsomeBoy666** [realm/realm-java#6724]
#### Can anybody tell me if the method RealmObject.isValid()  really reliable?
I have the code below to delete a realm object, which is "event" in the code, from a Event table in the android main thread, if the event has been posted to the server successfully by Rxjava.
```
compositeDisposable.add(dataManager.postEvent(event)
        .observeOn(AndroidSchedulers.mainThread())
        .subscribe({
            event.realm.executeTransaction {
                if (event.isValid){ // the event hasn't been deleted yet
                    event.deleteFromRealm()
                }
            }
        }, { throwable ->
            Timber.e("Post event failed: %s", throwable.message)
        }))
```
as you can see, I have checked whether the event is deleted before deleting by `if (event.isValid)`.And the realm document says that about this method:

>Checks if the RealmObject is still valid to use i.e., the RealmObject hasn't been deleted nor has the
{@link io.realm.Realm} been closed. It will always return {@code true} for unmanaged objects.

Based on this doc, I think the code would be fine, but released apps still crashed occasionally with error info like:
> main(1) 
>java.lang.IllegalStateException
>the object is already deleted. 

the stack trace is like:

>io.realm.RealmObject.getRealm(RealmObject.java:332)
>io.realm.RealmObject.getRealm(RealmObject.java:305)

Can anybody tell me why this happens?

Realm version(s): realm-gradle-plugin:5.9.0

Android Studio version: 3.5.0

Android Build Tools version: 27.0 ~29.0

Gradle version: 5.4.1

Which Android version and device(s): mostly on android 6 and 7 devices

**Comment by Zhuinden** [comment]
You're calling `event.realm` before you are calling `event.isValid`.

Only valid managed RealmObjects have an associated Realm instance.

**Comment by ultimateHandsomeBoy666** [comment]
wow! You got the point! I was entangled with what is executing in the transaction, without even noticing `event.realm` might probably go wrong.
Thanks bro!
