### ISSUE TITLE
How can i replace a list[objects] with object feild in Realm?

### ISSUE THREAD

**Issue by miladsalimiiii** [realm/realm-java#6725]
I want to import existing `token` into `tokenList` as first item , for example if someone has a `token="abc"` after migration , i want he/she has `tokenList` that `tokenList[0]=="abc"`

This is my migration code:

```
public class RealmMigration implements io.realm.RealmMigration {
.
.
.
    if (oldVersion == 3) {
        final RealmObjectSchema bankSchema = realmSchema.get("Bank");
        final RealmObjectSchema tokenSchema = realmSchema.get("Token");
        DynamicRealmObject bank = realm.createObject("Bank",1);
        Token token = bank.get("Token");
        bankSchema.addRealmListField("tokenList", tokenSchema);
        List<Token> tokenList = bank.get("tokenList");
        if (token != null) tokenList.add(token);
        bankSchema.removeField("Token");
        }
}
```
I replace this :

```
    @RealmField(name = "tokenList")
    private RealmList<Token> mTokenList;

```

With this in my class : 
```
    @RealmField(name = "Token")
    private Token mToken;
```

[stackoverflow link](https://stackoverflow.com/questions/59855380/how-can-i-replace-a-listobjects-with-object-feild-in-realm)

**Comment by Zhuinden** [comment]
Have you tried https://realm.io/docs/java/latest/api/io/realm/RealmObjectSchema.html#addRealmObjectField-java.lang.String-io.realm.RealmObjectSchema- ?

**Comment by miladsalimiiii** [comment]
> Have you tried https://realm.io/docs/java/latest/api/io/realm/RealmObjectSchema.html#addRealmObjectField-java.lang.String-io.realm.RealmObjectSchema- ?

Yes but it does not help.

In IOS we have something like this :

```
                    if oldSchemaVersion < 3 {
                        let dbToken = oldObject!["Token"] as! MigrationObject
                        let tokenObject = migration.create(Token.className(), value: dbToken)
                        let tokenList = newObject?["TokenList"] as? List<MigrationObject>
                        tokenList?.append(tokenObject)//in this line we add token that we want to remove it to tokenList
                        migration.delete(dbToken)
                    }
```

I want something like this in android.
Please pay attention to my comment in code.

**Comment by miladsalimiiii** [comment]
@cmelchior , hi please check my isuue

**Comment by Zhuinden** [comment]
The question title asked to replace a list with an object, but the actual code seems to replace an object with a list. That causes confusion regarding answers.

Anyways, I think that part works fine, the issue is that you're creating a new bank instance. You should be using `realm.where("Bank").transform()` if I remember correctly.

**Comment by miladsalimiiii** [comment]
`realm.where("Bank")` does not have `transform()`

**Comment by Zhuinden** [comment]
Sorry it's been a while since I had to write  a migration. Checking my answer from 3 years ago on a very similar problem 

https://forum.realm.io/t/migrate-list-of-realmstring-string/616/4

Apparently the `transform` method is on `RealmSchema`

So like, 

```
dynamicRealm.getSchema()
   .get("Bank")
   .addRealmListField(...)
   .transform((obj) ->
         // add field from existing token to RealmList field added to obj
     )
     .removeField("mToken")

**Comment by miladsalimiiii** [comment]
Yeeesss, Thankssssss Gabor
If you want please answer this in [StackoverFlow](https://stackoverflow.com/questions/59855380/how-can-i-replace-a-listobjects-with-object-field-in-realm) for the use of others
