### ISSUE TITLE
`IllegalStateException` thrown when deleting Realm, but no instances open.

### ISSUE THREAD

**Issue by Orbyt** [realm/realm-java#6742]
#### Goal
Delete Realm (via `Realm#deleteRealm()`) when decryption fails.

#### Actual Results
> java.lang.IllegalStateException: It's not allowed to delete the file associated with an open Realm.

Realm throws an `IllegalStateException` when attempting to delete. No Realm instances are opened in any other part of our application.

Additionally, `Realm#getGlobalInstanceCount()` and `Realm#getLocalInstanceCount()` return `0` right before the `IllegalStateException` is thrown, verifying that no instances are actually open and contradicting the exception. 

Finally, note our call to `Realm#deleteRealm()` only occurs in a `catch` block invoked when _opening Realm fails_. 

Due to these reasons, we suspect this is a valid bug in Realm.

#### Steps & Code to Reproduce
First, the code in question:
```kotlin
 fun setupRealm() {                                                                                  
     Realm.init(context)                                                                             
                                                                                                     
     val realmFileName = "my_db.realm"                                                               
     val key = EncryptDecryptHelper.loadKey(spHelper)                                                
     val version = 1L                                                                                
                                                                                                     
     val defaultConfig = RealmConfiguration.Builder().apply {                                         
         name(realmFileName)                                                                         
         encryptionKey(key)                                                                          
         schemaVersion(version)                                                                      
         deleteRealmIfMigrationNeeded()                                                                                                                                       
     }.build()                                                                                       
     Realm.setDefaultConfiguration(defaultConfig)                                                    
    
     // Attempt to open a Realm. We expect this to fail with a RealmFileException when 
     // users on old versions have just updated as we've modified the `encryptionKey`.                                                                                                                   
     try {                                                                                           
         Realm.getInstance(defaultConfig)                                                            
     } catch (exception: RealmFileException) {                                                       
         RollbarHelper.logWarning("Failure while reading realm file", exception.toString(), spHelper)                                              
         var instances = Realm.getGlobalInstanceCount(defaultConfig)                                 
         var localInstances = Realm.getLocalInstanceCount(defaultConfig)                             
         Log.d("testing", "Instances: global:$instances local:$localInstances")                                                                                                                
         Realm.deleteRealm(Realm.getDefaultConfiguration()!!)                                                                             
     }                                                                                               
 }                                                                                                   
```

Reproduced on a Samsung Galaxy S10+. The steps we are using to reproduce this are:

1. Install an older version of application with a set `encryptionKey` and ensure Realm initializes.
2. With the application running and in the foreground, update the application via `adb install -r <path to apk>`. The `-r` flag is important as it simulates an app update instead of a fresh install. This new version of the app should have the same Realm setup, but utilize a different `encryptionKey`.
3. The system will close the application when the install completes. Immediately open the now updated app. With the above code in place, `Realm#deleteRealm` will throw an `IllegalStateException`, even though Realms `Realm#get*InstanceCount()` functions will return `0`.

As of now, this does _not_ appear to be reproducible on anything but a physical Samsung device. This issue is causing a considerable number of crashes for affected users, and is considered critical.

#### Version of Realm and tooling
Realm: `io.realm:realm-gradle-plugin:6.0.1`
Realm Extensions: `com.github.vicpinm:krealmextensions:2.5.0` (should be irrelevant, but including just in case)

Android Studio version: 3.5.3
Which Android version and device(s): Samsung Galaxy S10+ running Android 10

**Comment by Orbyt** [comment]
Possible related: https://github.com/realm/realm-java/pull/5417/files/ed30b600fafc672f805e3d9c74251c710653bba2#diff-4ac32a78649ca5bdd8e0ba38b7006a1eR17

**Comment by Zhuinden** [comment]
If we take https://github.com/realm/realm-java/pull/5417/files/ed30b600fafc672f805e3d9c74251c710653bba2#r144535306 into account, a crazy idea would be to call `System.gc()` before `Realm.deleteRealm(`.

My old fallback code was to catch any exception, get the file path from the configuration, and delete the file manually. But of course, that's not exactly safe either if there really is an open Realm instance somewhere internally that we don't know about.

Note: I'm not a member of Realm, I'm just curious about this issue you've encountered.

**Comment by Orbyt** [comment]
@Zhuinden We've attempted to use Realm's internal `Util#deleteRealm()` function which _appears_ to circumvent the core issue (it just deletes the Realm file's on the file system). This is still a big issue for us; we encourage the Realm team to look into this.

**Comment by nhachicha** [comment]
@cmelchior could this be related to the named pipe being retained by the previous process as seen in some Samsung devices?

**Comment by cmelchior** [comment]
We changed how files are managed in Realm Java 7.0 and above. So I'll close this issue as outdated. Please reopen this issue if it still persists in Realm Java 7.0.2.
