### ISSUE TITLE
Field 'id' cannot be set as primary key since there are duplicated values for field

### ISSUE THREAD

**Issue by gfzy9876** [realm/realm-java#6746]
I have a Class,but does't has primary key, in old version;
In new version, I add a field 'id' as primary key value;

```
schema.get("Ch")
                    .addField("id", String.class, FieldAttribute.PRIMARY_KEY)
oldVersion++;
```
then it throw an Exception:
```
Field 'id' cannot be set as primary key since there are duplicated values for field 'id' in Class 'Ch'.

```

but I dont have add Primary key,it point to itself.Who could give me some help.

**Comment by Zhuinden** [comment]
The default value for primitives is 0, and for non-primitives is null.

0 and null are valid Pk values but only for 1 object. If you just add ID as primary key, it will be initialized to 0 on each object, causing unique violation.

**Comment by nhachicha** [comment]
As mentioned by Gabor, you're violating a pre-condition to add a primary key on an existing schema. Your table `Ch` already has duplicate values for the column `id`. 
Note: you can query for unique values  https://realm.io/docs/java/latest#unique-values

**Comment by Zhuinden** [comment]
The trick is that you need to first initialize the field as non-primary-key field, use `transform` to initialize the values to unique values, and THEN use `addPrimaryKey` to make the field a primary key.
