### ISSUE TITLE
RealmMigration only called once despite having 2 schemas

### ISSUE THREAD

**Issue by luispereira** [realm/realm-java#6747]
I have 2 different configuration files with different modules and I want to do migration on the 2 schemas. 
However, only one RealmMigration is called.

I called the code below twice, for each different module
```
   RealmConfiguration.Builder()
            .name(FIRST_DB_NAME) //SECOND_DB_NAME
            .schemaVersion(VERSION)
            .migration(RealmMigration())
            .modules(AppRealmModule()) //for the seconds database -> UserRealmModule()
```

However, when I bump the realm database version, and change a little the realm schema (in this case adding a previous realm class to AppRealmModule, that was already in UserRealmModule), the realm migration is only called once.
```
abstract class StorageRealmMigration : RealmMigration {

    override fun migrate(realm: DynamicRealm, oldVersion: Long, newVersion: Long) {
        //this is called only once, despite the version of both realm configurations passing from 1 to 2
    }
}
```

In my case, what I want to do is to pass one realm class from UserRealmModule to AppRealmModule with all current information. I have something like this:
```
override fun migrate(realm: DynamicRealm, oldVersion: Long, newVersion: Long) {
         val isApplicationConfig = realm.configuration.realmFileName == applicationDatabaseName()

        if(oldVersion <= FIRST_VERSION){
            if(isApplicationConfig){
                create(MigratedRealm::class.java.simpleName).apply{
                    //adding fields here
                 }
             } else {
                  //this is never called :(
                  realm.executeTransaction {
                    results = it.where(MigratedRealm::class.java.simpleName).findAll()
                    //I NEED TO add results to ApplicationRealmModule
                } 
                remove(MigratedRealm::class.java.simpleName)
             }
        }
}
```

Am I doing something wrong here? Realm should call the migration twice right?

src: https://stackoverflow.com/questions/60154638/realmmigration-only-called-once-despite-having-2-schemas

**Comment by luispereira** [comment]
I think I know what the problem was, since I had no queries for UserRealmModule tables, the realm did not trigger the migraiton, I had to do something like this to trigger the migration:
```
realm.where(MigratedRealm::class).findAll()
```

Is there any other method to trigger the migration, instead of doing a query?

**Comment by Zhuinden** [comment]
Sure, `Realm.migrateRealm`
