### ISSUE TITLE
errorHandler(new FooHandler()) cause  java.lang.IllegalArgumentException: Configurations cannot be different if used to open the same file

### ISSUE THREAD

**Issue by robsonbbs** [realm/realm-java#6751]
#### Goal
Add a custom ErrorHandler to a SyncConfiguration

#### Actual Results
I am receiving this exception:

 java.lang.IllegalArgumentException: Configurations cannot be different if used to open the same file

#### Steps & Code to Reproduce

Just creates a SyncConfiguration adding an ErrorHandler;

#### Version of Realm and tooling

Realm version(s): 6.0.2

Realm Sync feature enabled: Yes

Android Studio version: 3.5.1

Android Build Tools version: 28.0.3

Gradle version: 3.5.2

Which Android version and device(s): 9

**Comment by Zhuinden** [comment]
Implement equals / hashCode in your ErrorHandler so that two instances of ErrorHandler could as the same thing (`return obj != null && obj instanceof FooHandler;`)

**Comment by robsonbbs** [comment]
I realized that right now.
Thanks @Zhuinden, my bad!
