### ISSUE TITLE
RealmFileException: Unable to open a realm at path ($path): Realm file decryption failed Path:. (Realm file decryption failed Path: ($path)) (($path)) in /Users/jasonflax/Development/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRe

### ISSUE THREAD

**Issue by AzhimkulovAzamat** [realm/realm-java#6766]
#### Goal
Open encrypted realm file without error.

#### Actual Results
When I call methods `Realm.getInstance(this.realmConfiguration)` an error occurs (see stack below). And the file no longer opens. App has to delete the realm file and re-create it. And so every time this error occurs.

**Error stack:**
`Caused by: io.realm.exceptions.RealmFileException: Unable to open a realm at path '($path)': Realm file decryption failed Path:. (Realm file decryption failed Path: ($path)) (($path)) in /Users/jasonflax/Development/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 101
	at io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
	at io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:171)
	at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:241)
	at io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:231)
	at io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:332)
	at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:285)
	at io.realm.Realm.getInstance(Realm.java:428)`

**RealmConfiguration builder**
`new RealmConfiguration.Builder()
                        .encryptionKey(realmEncryptionKeyProvider.getEncryptionKey())
                        .name(REALM_NAME)
                        .schemaVersion(REALM_SCHEMA_VERSION)
                        .migration(new RemoveUserGenderAndEmailMigration()).build();`

#### Steps & Code to Reproduce
I can not reproduce this error on my phone.

#### Version of Realm and tooling

Realm version(s): 6.0.1

Realm Sync feature enabled: No

Android Studio version: 3.5.3

Android Build Tools version: 29.0.0

Gradle version: 3.5.0

Which Android version and device(s): 
**Huawei:** 
YAL-L21, v 9
P10, v 9
POT-LX1, v 9
Honor 10, 9
P20 Pro, 9
P20 Pro, 10

**Vivo**
vivo 1806, 9

**Samsung**
Galaxy S7 Edge, 8.0.0
SM-G970F, 9

**Google**
Pixel 2, 8.1.0

**Comment by Zhuinden** [comment]
Sounds like `realmEncryptionKeyProvider` returns the wrong key, OR you are also opening the Realm with a different configuration elsewhere

**Comment by AzhimkulovAzamat** [comment]
So I get the encryption key

**Comment by AzhimkulovAzamat** [comment]
So I get the encryption key
`String savedKey = getSavedEncryptionKey();
        if (savedKey.isEmpty()) {
            key = generateKey();
            String keyString = encodeToString(key);
            saveStringEncryptionKey(keyString);
        } else {
            key = decodeFromString(savedKey);
        }
        return key;`
This is the only way to get key and it excludes providing the wrong key.
And I searched in the whole project for such lines of code as `getInstance` or `getDefaultInstance`

**Comment by AzhimkulovAzamat** [comment]
> So I get the encryption key
> `String savedKey = getSavedEncryptionKey(); if (savedKey.isEmpty()) { key = generateKey(); String keyString = encodeToString(key); saveStringEncryptionKey(keyString); } else { key = decodeFromString(savedKey); } return key;`
> This is the only way to get key and it excludes providing the wrong key.
> And I didn't find in the whole project for such lines of code as `getInstance` or `getDefaultInstance`, except for the class of the realm provider

**Comment by AzhimkulovAzamat** [comment]
> Sounds like `realmEncryptionKeyProvider` returns the wrong key, OR you are also opening the Realm with a different configuration elsewhere

I checked and the code excludes such possibilities

**Comment by cmelchior** [comment]
@AzhimkulovAzamat We would need a sample project that reproduces this to be a able to debug this further. I'll close this issue for now, but if you can provide a project reproducing it, please feel free to reopen the issue.
