### ISSUE TITLE
Core 10 cannot open Realms created by iOS Core 6

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#6789]
These tests are failing on Core 10 using realm-core-10.0.0-alpha.3

`IOSRealmTests`:

../src/realm/obj.cpp:256: [realm-core-10.0.0-alpha.3] Assertion failed: type == ColumnTypeTraits<T>::column_id

**Comment by jedelbo** [comment]
Fixed

**Comment by jedelbo** [comment]
Ok not fixed in this repo
