### ISSUE TITLE
error: "com.getkeepsafe.relinker.MissingLibraryException"

### ISSUE THREAD

**Issue by ehabreda** [realm/realm-java#6798]
Hi,

I want to prevent this error or handle it: "com.getkeepsafe.relinker.MissingLibraryException"

MissingLibraryException is reported by Google play store for one of our App users, this app is in production and is used by thousands of users.

Realm Sync feature enabled: (I am not sure) but if the question is about syncing with a cloud server, than the answer is no, it is a local database only

in project gradle: classpath '**io.realm:realm-gradle-plugin:6.0.2**'

in module gradle: implementation '**io.realm:android-adapters:3.1.0**'

Android Studio version: 3.6.2

Android Build Tools version: 18.March.2020

Gradle version: gradle:3.6.2

Which Android version and device(s): Android 8.1, Oppo CPH1909 (CPH1909), 2816MB RAM

![realm_error](https://user-images.githubusercontent.com/32043913/78616513-b9627b80-7874-11ea-9a5c-63b5f4e81748.jpg)

**Comment by cmelchior** [comment]
The error message has been improved in the latest version of Realm. Try upgrading to `6.1.0`, but most likely you are hitting something like this: https://github.com/realm/realm-java/issues/6812

So I'll be closing this as a duplicate. If you upgrade and discover it is a different error, please reopen this issue.
