### ISSUE TITLE
Read only file system

### ISSUE THREAD

**Issue by demonar** [realm/realm-java#681]
Got this error from my bug tracker:

Unspecified exception. open() failed: Read-only file system in io_realm_internal_SharedGroup.cpp line 109

this happened when doing:

Realm realm = Realm.getInstance(context);

does this give you enough information?

**Comment by kneth** [comment]
@demonar Did you have time to look into questions a-d?

**Comment by cmelchior** [comment]
@demonar 
Closing due to lack of feedback and we can't reproduce it. Please reopen if there is additional information.

**Comment by denley** [comment]
I've received a crash report that's similar to this.

The app has been live for over a month and this is the first report I've received about it, so it definitely works fine on the vast majority of cases.

I can also see that this crash occurred in a line of my code that can only occur after already loading an item from the Realm. So this means that the same device has already successfully saved data to the Realm.

It's using Realm version 0.78.0

    java.lang.RuntimeException: Unspecified exception. msync() failed: Read-only file system in io_realm_internal_SharedGroup.cpp line 164
        at io.realm.internal.SharedGroup.nativeCommitAndContinueAsRead(Unknown:-2)
        at io.realm.internal.SharedGroup.commitAndContinueAsRead(Unknown:-1)
        at io.realm.internal.ImplicitTransaction.commitAndContinueAsRead(Unknown:-1)
        at io.realm.Realm.commitTransaction(Unknown:-1)
        ...

```
apiLevel 21
batteryLevel 0
brand htc
charging false
dpi 480
freeDisk 26667683840.0
freeMemory 200004528
jailbroken false
locale en_US
locationStatus allowed
manufacturer HTC
model HTC One_M8
networkAccess wifi
orientation portrait
osBuild LRX22C release-keys
osName android
osVersion 5.0.1
screenDensity 3
screenResolution 1776x1080
time 2015-03-03T01:17:29Z
totalMemory 201326592
```
