### ISSUE TITLE
add object listener on null object

### ISSUE THREAD

**Issue by aabolfazl** [realm/realm-java#6828]
Hello,
i have a relam DB,here is the thing : i want to call a transaction in Realm for a null Obj (write it),and get notified right after the transaction state has changed(put on db successfully)
i know realm has a listener that get notified for any transaction result change for list obj,what i want is to have the same result for one obj and not an array list obj

**Comment by cmelchior** [comment]
Not entirely sure what you mean. If you want to be notified when a write is successful you can add a change listener to the transaction itself?

```
val realm = Realm.getDefaultInstance()
 realm.executeTransactionAsync(Realm.Transaction{
     it.insert(MyRealmObject())
 }, Realm.Transaction.OnSuccess {  
     // Object was created
 })
```

Otherwise, you can create a query and wait for it to return more than 0 results.

```
val realm = Realm.getDefaultInstance()
val id = "my-id"
val results = realm.where<MyRealmObject>().equalTo("id", id).findAllAsync()
results.addChangeListener {
  if (it.size > 0) {
    handleObject(it.first()) // Object was created
  }
} 
 realm.executeTransactionAsync { it.insert(MyRealmObject("my-id")) }
```

**Comment by aabolfazl** [comment]
thanks but you add change listener on result,i want add them just once object!
