### ISSUE TITLE
Does the IntentService check for RealmChangeListeners still make sense?

### ISSUE THREAD

**Issue by jpmcosta** [realm/realm-java#6829]
#### Describe your problem or use case
1. I have an `IntentService` where I perform some transactions in `Realm`
1. I want to set a `RealmChangeListener` in the beginning of `onHandleIntent(Intent)`, perform all transactions, and remove the listener before returning
1. the listener should be called, if any relevant changes are made
1. I get the following error when I try to add the listener: `Realm cannot be automatically updated on an IntentService thread.`

#### Describe the solution you'd like
I understand why this happens, since `onHandleIntent(Intent)` calls `stopSelf()` before returning, it could potentially cause a problem, since the `IntentService` and its `HandlerThread` could be terminated, preventing the listener to be called.

However, I have created a replica of `IntentService` (changing its name avoid Realm's [detection](https://github.com/realm/realm-java/blob/e6380b7d9cbc0a594f978b569ee6c265af269ed4/realm/realm-library/src/main/java/io/realm/internal/android/AndroidCapabilities.java#L72)) and I haven't had any issues with my listener being called.

My listener's `onChange()` method is consistently called before `stopSelf()`.

So, my question would be if [this check](https://github.com/realm/realm-java/blob/e6380b7d9cbc0a594f978b569ee6c265af269ed4/realm/realm-library/src/main/java/io/realm/internal/android/AndroidCapabilities.java#L57) is still needed, since it was updated 3 years ago and Realm has changed a lot during that time.

#### Additional context
If you think the check is still needed, I was wondering if there were any patterns you recommend as an alternative. I'm trying to simplify this workflow, since I could have a different `Service` listening for changes, but that could create some race conditions, since I wouldn't want to have `Realm` always open.

Thanks!

**Comment by cmelchior** [comment]
Yes, the check is there so people don't accidentally believe the listener will be called when they exit the `onHandleIntent`. For all practical purposes, the IntentThread is just like a background thread. So the check is mostly there to prevent people from shooting themselves in the foot.

If your listeners depend on write transactions inside the onHandleIntent, then yes, they will work as starting the transaction will trigger them, but most people I saw used them to listen to other things which would not work.

I'm not 100% why you are using listeners though? The code inside the onHandleIntent already run in the background, so you can safely use all the synchronous methods and not the *Async ones?

**Comment by jpmcosta** [comment]
Thank you for your quick answer.

I'm using both the listener and synchronous methods. 

The `IntentService` performs multiple actions that may or may not change the content of some predefined `RealmResults`. It also runs different actions, depending on the `Intent`.

Instead of manually keeping track of the need to process changes, I register the listener in the beginning of `onHandleIntent()`, perform all the necessary actions, and, if anything changes, the listener gets triggered and processes the changes. 

Am I overcomplicating things? Is there a simpler way to detect changes? From your answer I feel I'm missing something obvious I should know about by now.

**Comment by cmelchior** [comment]
Well, without seeing your code. It is hard to tell. But I can easily envision that in some scenarios using listeners might make some code flow easier.

Depending on the nature of your listeners, you might just track it through your own custom boolean. Like a global `AtomicBoolean` but obviously that isn't very nice if you are tracking multiple changes.

**Comment by cmelchior** [comment]
I guess alternatively we could make it possible to disable the IntentService-check, but it is a very exotic use case, so I would rather not introduce something too complicated for that.

**Comment by jpmcosta** [comment]
> Depending on the nature of your listeners, you might just track it through your own custom boolean. Like a global AtomicBoolean but obviously that isn't very nice if you are tracking multiple changes.

Initially, I was going to do something like this, but I'm trying to avoid it, especially to make the code future-proof.

>I guess alternatively we could make it possible to disable the IntentService-check, but it is a very exotic use case, so I would rather not introduce something too complicated for that.

I can see why the check is there and I agree it makes sense. I knew that this could be the case, but I was wondering if there was an actual limitation initially where the listeners would never get called.

My custom `IntentService` is a good enough "solution", I don't think that feature would bring much value overall.

I will close this issue now. Feel free to reopen it at any time. Thank you very much for all your help.
