### ISSUE TITLE
fatal error: collection_notifications.hpp: No such file or directory

### ISSUE THREAD

**Issue by hhx20120607** [realm/realm-java#6849]
When building realm-java from source, I encountered an error as: fatal error: collection_notifications.hpp: No such file or directory. Can anyone help me? Thanks a lot.

**Comment by cmelchior** [comment]
Hi @hhx20120607 Sorry for the late reply. Did you also clone the git submodule as pr: https://github.com/realm/realm-java/blob/master/README.md#download-sources

**Comment by hhx20120607** [comment]
Thanks a lot. I'm a new coder.
