### ISSUE TITLE
Proxy class imports can cause ambiguous references 

### ISSUE THREAD

**Issue by osama-lionheart** [realm/realm-java#686]
While migrating to use the just-landed json features, I encountered an issue while deserializing a json object with string array property, something like:

```
{
    arr: [ 'item1', 'item2', 'item3' ]
}
```

previously I fixed the issue by creating a wrapper class (e.g `RealmString`) and since I was parsing json manually via gson, it was working ok, but now I can't find a workaround to this issue, any ideas?

// other small issues...
- why can't we get a list of created objects via `realm.createAllFromJson()` similar to what we get from `realm.createObjectFromJson()`?
- I get `reference is ambiguous` error in the generated proxy class, when I have a model named `Thread`.

Thanks for your great efforts, and keep up the good work!

**Comment by kneth** [comment]
@osama-lionheart I'm working on fixing the bug with the ambiguous references in proxy classes.

**Comment by osama-lionheart** [comment]
@kneth, cool, thanks for keeping us up to date and for your great work!

**Comment by kneth** [comment]
I have merged #722 into master, and it will be part of next release. If you experience the same issue in the future, please reopen this issue.

**Comment by osama-lionheart** [comment]
Thanks @kneth, just confirming that it has been fixed in v0.77.

**Comment by bmunkholm** [comment]
Thanks for the confirmation!
