### ISSUE TITLE
Can't open file in Studio after upgrading to realm-java 7.0.0 - Studio asks for encryption key.

### ISSUE THREAD

**Issue by zeeshanrasool91** [realm/realm-java#6863]
After updating to version 7.0.0 of Realm for android, i am facing a strange issue. i am not using any encryption key or anything. when i export RealmFile from device to open in realm browser it ask for encrypttion key. and also the size is very less like 1 mb while the when i generate database using v6.1.0 the database size is approx 6 MB

**Comment by bmunkholm** [comment]
It's likely because you are using an older version of Studio. You need to use version 3.11. You can get that [here](https://github.com/realm/realm-studio/releases/tag/v3.11.0).

**Comment by zeeshanrasool91** [comment]
> It's likely because you are using an older version of Studio. You need to use version 3.11. You can get that [here](https://github.com/realm/realm-studio/releases/tag/v3.11.0).

yes it solved the problem thanks alot. actually it was not showing me any update on website. i tried to get the updated version from website
