### ISSUE TITLE
Realm and retrofit always return empty RealmList with get request

### ISSUE THREAD

**Issue by nishantt12** [realm/realm-java#6877]
#### Goal
RealmList always returns an empty list when I make a get request using retrofit even when the json array is null for that object. It should return null when JsonArray is null and empty list when JsonArray is empty. 

MyObject: {
RealmList<String> statues;
}

sample json-1:{
"statues": [""]
}

Current Output: MyObect.statues = empty list.

Expected output: MyObect.statues = empty list. This is the correct behavior.

sample json-2:{
"statues": null or not set
}

Current Output: MyObect.statues = empty list.

Expected output: MyObect.statues = null. This is not the correct behavior. RealmList should be null.

Realm version(s): 5.12.0

Realm Sync feature enabled: No

Android Studio version: 3.5.3

Gradle version: 5.4.1

Which Android version and device(s): All

**Comment by cmelchior** [comment]
It isn't clear how you are getting data from Retrofit into Realm, but if you are accessing a managed RealmObject, RealmLists can never be `null` in those, which might be what you are seeing.

This is currently a restriction from the underlying Core database that lists cannot be `null`, just `empty`.

**Comment by cmelchior** [comment]
I assume the above answered your question. If not, feel free to reopen.
