### ISSUE TITLE
Unable to create DynamicRealm

### ISSUE THREAD

**Issue by IgorGanapolsky** [realm/realm-java#6887]
#### Goal
Follow DynamicRealm creation as indicated in this instruction: 
https://realm.io/docs/kotlin/latest/#creating-objects

#### Actual Results
Crash:
> Process: com.myapp.us.debug, PID: 12865
    java.lang.IllegalArgumentException: The class 'NfcTag' doesn't exist in this Realm.
    (/Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp:234)
        at io.realm.internal.OsSharedRealm.nativeGetTableRef(Native Method)
        at io.realm.internal.OsSharedRealm.getTable(OsSharedRealm.java:306)
        at io.realm.RealmSchema.getTable(RealmSchema.java:157)
        at io.realm.DynamicRealm.createObject(DynamicRealm.java:138)

**Comment by cmelchior** [comment]
Well, the exception message is pretty clear? `NfcTag` is not part of the Schema for the Realm for some reason?

**Comment by IgorGanapolsky** [comment]
> Well, the exception message is pretty clear? `NfcTag` is not part of the Schema for the Realm for some reason?

DynamocRealm does not need a schema.  That's why it's "Dynamic"

**Comment by cmelchior** [comment]
No, but it cannot automatically create one either. So if the file doesn't that class you will get that error.

Realm files still have a schema when you open them with a Dynamic Realm, you just don't have to specify it up front.

**Comment by cmelchior** [comment]
I assume the above answered your question, so closing this issue. Feel free to reopen if you are still having issues.
