### ISSUE TITLE
How to get only the relations matching the where clause when using link queries?

### ISSUE THREAD

**Issue by cornflakes** [realm/realm-java#689]
Say I have two classes:

    Foo extends ReamlObject {
        RealmList<Bar> bars;
    }

    Bar extends RealmObject {
        boolean active;
    }

When I then make the query:

    RealmResults<Foo> fooResults = realm.where(Foo.class).equalTo("bars.active", true).findAll();

It returns all Foos that have atleast one active Bar, but in the RealmList: bars all nonactive Bar object still resides.

How can I make a link query where this is not the case?

**Comment by cmelchior** [comment]
@cornflakes 
I assume your question was answered, please reopen if that was not the case.
