### ISSUE TITLE
Realm gradle library causes ClassNotFoundException

### ISSUE THREAD

**Issue by redmi111** [realm/realm-java#6890]
So I'm getting this exception while trying to run the application which uses realm Gradle plunging and kotlin.

`Unable to instantiate application com.myapp.application.Application: java.lang.ClassNotFoundException: Didn't find class "com.nyapp.application.Application"`
The app works just fine if I remove the realm library and it's imports completely from the project.

Also sometimes I'm getting CoreComponantFactory not found, exception as well.

The project is using the support library not the AndroidX and the issue occurs with almost all versions of the realm Gradle plugin.

And yeah, the project is using multidex but I had added multiDexKeepProguard for the whole package so I believe it doesn't cause the issue here since the Application class is in primary dex also I noticed below error line in the logs

`Failed to verify Dex: *path*: Duplicate interface: 'Lio/realm/com_myapp_models_Realm_Model_MyModelRealmProxyInterface;`'

Help will be very much appreciated. Thanks in advance.

#### Version of Realm and tooling

Realm version(s): Tried all versions above 5.+.+

Realm Sync feature enabled: Yes/No

Android Studio version: 3.6.+

Android Build Tools version: 28.0.0

Gradle version: 3.6.+

Which Android version and device(s): Android 10 (API 29)

**Comment by cmelchior** [comment]
Hi @redmi111 

Sorry for the late reply. It sounds like some sort of project-related problem, but without being able to reproduce it is is probably hard to help. Can you share some sort of example project demonstrating the problem?

**Comment by rorbech** [comment]
Closing, assuming this is no longer relevant. Feel free to reopen with further details if needed.
