### ISSUE TITLE
Build error: cannot find symbol class RealmObject

### ISSUE THREAD

**Issue by pp67yu** [realm/realm-java#6910]
####Goal
Why the class is not being recognized?

####Error
Build: public class Employee extends RealmObject {
                              ^
  symbol: class RealmObject
1 error
cannot find symbol class RealmObject

#### Steps & Code to Reproduce
<
package com.example.realmdatabasedemo;

public class Employee extends RealmObject {
    private int employee_id;
    private String employee_name;

    private int getEmployee_id(){
        return employee_id;
    }

    public String getEmployee_name() {
        return employee_name;
    }

    public void setEmployee_id(int employee_id) {
        this.employee_id = employee_id;
    }

    public void setEmployee_name(String employee_name) {
        this.employee_name = employee_name;
    }
}
>

#### Version of Realm and tooling

Realm version(s): 7.0.0

Realm Sync feature enabled: Don't No

Android Studio version: 4.0

Android Build Tools version: 29.0.3

Gradle version: 4.0.0

Which Android version and device(s):  Don't No

Please help

**Comment by cmelchior** [comment]
It looks like it cannot find `RealmObject`. Did you configure the project according to: https://realm.io/docs/kotlin/latest/#getting-started

**Comment by pp67yu** [comment]
Yes,I have configured the project according to: https://realm.io/docs/kotlin/latest/#getting-started
by adding certain lines of code
##This is build.gradle(Project:RealmDatabaseDemo) file##
```
// Top-level build file where you can add configuration options common to all sub-projects/modules.
buildscript {
    repositories {
        google()
        jcenter()
    }
    dependencies {
        classpath "com.android.tools.build:gradle:4.0.0"
        classpath "io.realm:realm-gradle-plugin:6.0.2"    //Line added by  https://realm.io/docs/kotlin/latest/#getting-started

        // NOTE: Do not place your application dependencies here; they belong
        // in the individual module build.gradle files
    }
}

allprojects {
    repositories {
        google()
        jcenter()
    }
}

task clean(type: Delete) {
    delete rootProject.buildDir
}
```
## This is build.gradle(Module:app) file##
```
apply plugin: 'com.android.application'
apply plugin: 'realm-android'      //Line added by https://realm.io/docs/kotlin/latest/#getting-started
android {
    compileSdkVersion 29
    buildToolsVersion "29.0.3"

    defaultConfig {
        applicationId "com.example.realmdatabasedemo"
        minSdkVersion 16
        targetSdkVersion 29
        versionCode 1
        versionName "1.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    implementation fileTree(dir: "libs", include: ["*.jar"])
    implementation 'androidx.appcompat:appcompat:1.1.0'
    implementation 'androidx.constraintlayout:constraintlayout:1.1.3'
    testImplementation 'junit:junit:4.12'
    androidTestImplementation 'androidx.test.ext:junit:1.1.1'
    androidTestImplementation 'androidx.test.espresso:espresso-core:3.2.0'

}
```

**Comment by cmelchior** [comment]
Yes, that should work. We would need a full working example demonstrating the bug to be able to debug further, but I assume it either a project setup or build cache error. Have you tried doing a full clean build from the commandline?

**Comment by rorbech** [comment]
Did you resolve this? It looks like you are missing an
```
import io.realm.RealmObject
```

**Comment by pp67yu** [comment]
Yes. It working fine now. Thank you for considering my request.
