### ISSUE TITLE
Realm can not find RealmObject extended models which are present in my custom .jar

### ISSUE THREAD

**Issue by Chinmay-Acharya** [realm/realm-java#693]
Hi,

I am creating a jar which contains Realm Models for storing data. Then user will add my jar and realm.jar seperatly in his project. so, in this scenario inside ".apt_generated" annotation folder the required proxy classes for realm are not getting generated as a result there is no entry in ValidationList.java class.

Below is the exception -
java.lang.IllegalStateException: Objects cannot be changed outside a transaction; see beginTransaction() for details.
W/System.err( 4036):    at io.realm.internal.Group.throwImmutable(Group.java:318)
W/System.err( 4036):    at io.realm.internal.Group.getTable(Group.java:213)
W/System.err( 4036):    at io.realm.Realm.getTable(Realm.java:233)
W/System.err( 4036):    at io.realm.RealmQuery.getTable(RealmQuery.java:101)
W/System.err( 4036):    at io.realm.RealmQuery.<init>(RealmQuery.java:58)
W/System.err( 4036):    at io.realm.Realm.where(Realm.java:756)

**Comment by cmelchior** [comment]
Hi @Chinmay-Acharya 
Just to follow up on this.
The ValidationList files contains the list of Model classes that Realm should know about. If you just deleted the ValidationList file from you library project, Realm in the app project doesn't know that the models in your library exists, thus the Nullpointer when you try to use them.

Instead you should copy all the strings from you library ValidationList file to your app ValidationList. It is a bit cumbersome and manually process atm, but we plan to make it a lot simpler going forward.

**Comment by bmunkholm** [comment]
@Chinmay-Acharya Did this help you? Please close the issue if no problems.

**Comment by Chinmay-Acharya** [comment]
Hi @cmelchior and @bmunkholm ,
Thanks for the reply. I followed your instructions and copy pasted all the strings in ValidationList.java class. So, jar realm model became accessible.

But in android studio, If project get build then user need to follow all the process again and again.

So currently, I am using SQL lite for library creation. I am really looking forward and curious for simpler version.

**Comment by evasquezcr** [comment]
Hello @cmelchior , I've been working with Realm and Parceler, I saw that I need to use :

@Parcel(implementations = { FooBarProxy.class}, value = Parcel.Serialization.BEAN, analyze = {FooBar.class})

Well, I don't know how or where my 'Proxy.class' is generated... where can I find it?

Thanks!

**Comment by cmelchior** [comment]
It is under `build/intermediates/classes` but you need the APT Gradle plugin in your build file to be able to reference the classes there: https://bitbucket.org/hvisser/android-apt.

**Comment by evasquezcr** [comment]
@cmelchior and the dependencies like this ?
dependencies {
     compile 'org.parceler:parceler-api:1.0.3'
     apt 'org.parceler:parceler:1.0.3'
}
