### ISSUE TITLE
Unrecoverable error. No corresponding table

### ISSUE THREAD

**Issue by JoyHong** [realm/realm-java#6947]
#### Goal
can open realm

#### Actual Results
can not open realm

#### Steps & Code to Reproduce

io.realm.exceptions.RealmError

Unrecoverable error. No corresponding table in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 107

1 io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
2 io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:175)
3 io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:251)
4 io.realm.a.<init>(BaseRealm.java:137)
5 io.realm.a.<init>(BaseRealm.java:104)
6 io.realm.w.<init>(Realm.java:163)
7 io.realm.w.a(Realm.java:499)
8 io.realm.y.a(RealmCache.java:507)
9 io.realm.y.a(RealmCache.java:473)
10 io.realm.y.a(RealmCache.java:414)
11 io.realm.w.b(Realm.java:428)

#### Version of Realm and tooling

Realm version(s): 7.0.0

Realm Sync feature enabled: No

Android Studio version: ?

Android Build Tools version: ?

Gradle version: ?

Which Android version and device(s): ?

**Comment by cmelchior** [comment]
I think this was fixed by https://github.com/realm/realm-core/issues/3701 , we just need to make a patch release with it. It should be fixed for `10.0.0-BETA.4` though, so you can attempt to upgrade to that.

**Comment by cmelchior** [comment]
We will be making a release of 7.0.1 shortly. Which should fix this, so i'll close this.

**Comment by JoyHong** [comment]
> We will be making a release of 7.0.1 shortly. Which should fix this, so i'll close this.

hello, when will it release?

**Comment by cmelchior** [comment]
Sorry. It was delayed due to a bug we uncovered when testing the new release. Hopefully we can have it ready by tomorrow

**Comment by JoyHong** [comment]
thanks
