### ISSUE TITLE
How to update upload/download progressbar in RealmRecyclerViewAdapter

### ISSUE THREAD

**Issue by iman2420** [realm/realm-java#6962]
I have a process in each item from the **RealmRecyclerViewAdapter** that I want to upload/download the file at the same time. But when I use RealmRecyclerViewAdapter, the UI hangs up and eventually crashes.

    ` override fun onProgressUpdate(percentage: Int, fileClass: FileClass) {
        Log.d(BaseFragment.TAG, "onProgressUpdate $percentage isManaged " + fileClass.isManaged)
        realm.executeTransaction { fileClass.uploadProcess = percentage }
    }`

And Adapter is: 

    `class FileListAdapter(
    data: OrderedRealmCollection<FileClass?>,
    private val realm: Realm? = Realm.getDefaultInstance()) :
    RealmRecyclerViewAdapter<FileClass, FileListAdapter.MyViewHolder>(data, true) {
    init {
        setHasStableIds(true)
    }....`

**Comment by cmelchior** [comment]
@iman2420 It is a bit unclear exactly how and what crashes. Can you provide a full working example that reproduces the problem?

**Comment by rorbech** [comment]
Closed due to inactivity. If the problem still persists, feel free to reopen with some more details.
