### ISSUE TITLE
Number of active versions (33) in the Realm exceeded the limit of 32 in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 128

### ISSUE THREAD

**Issue by JoyHong** [realm/realm-java#6977]
#### Goal
can transaction

#### Actual Results
can't transaction

#### Steps & Code to Reproduce
config = new RealmConfiguration.Builder()
...
.maxNumberOfActiveVersions(32)
.compactOnLaunch()
.build()

after run below code serval times on UI thread or background thread, error happens,
i don't why it still happens even i close realm every time, pls help me.

try (Realm realm = Realm.getInstance(config)) {
   doSomeRealmWriteTransaction();
}

#### Version of Realm and tooling

Realm version(s): 7.0.0

Realm Sync feature enabled: NO

Android Studio version: ?

Android Build Tools version: ?

Gradle version: ?

Which Android version and device(s): ?

**Comment by cmelchior** [comment]
It means you holding on to Realm versions somewhere, but from where is hard to tell from the information you given. 
Do you have an example project that demonstrates the issue?

**Comment by YanCorey** [comment]
[RealmDemo.zip](https://github.com/realm/realm-java/files/4862211/RealmDemo.zip)
This is our test demo

We first get a realm in the activity, which is used to monitor the updated data.

Then click AddDogOnThread on the main page of the demo. In the thread, reacquire a realm for adding data.

At this time, the index in realm's getVersionID will continue to increase.

When maxNumberOfActiveVersions is set to 6, the app will crash after the data increases about 8 times.

Can the index of the realm re-acquired not increase when there is a realm object?

**Comment by JoyHong** [comment]
@cmelchior can u help to have a check please?

**Comment by JoyHong** [comment]
any update?

**Comment by rorbech** [comment]
I have been able to reproduce this from the sample project. For some reason some of the old versions are not properly discarded after updates. Have not found the root of this yet, but could be related to doing new queries in the change listener 
```
realm.where(Dog.class).findAll())
```
Defining `RealmResults<Dog> dogs = realm.where(Dog.class).findAll();` elsewhere, e.g. in `onResume` and using this result in the change listener, seems to avoid the issue.

**Comment by cmelchior** [comment]
A fix for this has been merged and will be part of 7.0.3 which will be released shortly.
