### ISSUE TITLE
Crash when accessing Realm ByteArray parameter multiple times

### ISSUE THREAD

**Issue by satohu20xx** [realm/realm-java#6987]
#### Goal
Not crash

#### Actual Results
```
E/REALM: /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/jni_util/jni_utils.cpp:51: [realm-core-5.23.8] Assertion failed: false
    <backtrace not supported on this platform>!!! IMPORTANT: Please send this log and info about Realm SDK version and other relevant reproduction info to help@realm.io.
```

#### Steps & Code to Reproduce
The class is as follows.

```
open class Sample: RealmObject() {
    @PrimaryKey
    var id: String = ""
    var byteArrayParameter: ByteArray? = null
}
```

After assigning this byteArrayParameter to a local variable and access it multiple times, Application crash.

#### Version of Realm and tooling

Realm version(s): 6.1.0

Realm Sync feature enabled: No

Android Studio version: 4.0

Android Build Tools version: 3.5.3

Gradle version: 6.2.1

Which Android version and device(s): Pixcel 3a - Android 10

**Comment by cmelchior** [comment]
Exactly how is it crashing, can you provide a full description or sample project? Also,  do you have the full stack trace?

**Comment by satohu20xx** [comment]
> Exactly how is it crashing, can you provide a full description or sample project?

There is no sample project to reproduce. The Application dose not crash when changing the parameter type from ByteArray to String. So I think the access to ByteArray is suspicious.

> Also, do you have the full stack trace?

No stack trace when crashing... Only the logs described in the issue are output.

> It should always be present, so some way of reproducing would be nice.

OK. I try to create sample project.
But I am not sure if it will work, so I would like to know if there is a workaround.

**Comment by satohu20xx** [comment]
Sorry. I couldn't make a simple sample program.
If it is difficult to survey, you can close this issue.

**Comment by cmelchior** [comment]
Closing. Feel free to reopen if there is more information we can go after.
