### ISSUE TITLE
Realm Database size increases when updating more than 100 data via socket connection

### ISSUE THREAD

**Issue by sharawanan** [realm/realm-java#6997]
Background Thread to execute the write transaction. the realm DB size automatically increased to 1GB

**Comment by bmunkholm** [comment]
@sharawanan Please fill in the entire issue template. Thanks!
Did you check out the [documentation about big files](https://realm.io/docs/java/latest/#faq-large-realm-file-size)?

**Comment by sharawanan** [comment]
socket.on(Socket.EVENT_CONNECT, Emitter.Listener { args: Array<Any?> -> }).on("server") { args: Array<Any> ->
            val obj = args[0] as JSONObject
            val person = Person()
            person.id = obj.getInt("id")
            person.name = obj.getString("name")
            Realm.getDefaultInstance().use { realm -> realm.executeTransaction { realm1 -> realm1.copyToRealmOrUpdate(person)
                }
            }
        }


I'm getting bulk of data via the socket connection. realm database size increased within 15 minutes

**Comment by cmelchior** [comment]
Closing due to no response. If this is still a problem, please see https://realm.io/docs/java/latest/#faq-large-realm-file-size. If that doesn't fix the issue, feel free to reopen the issue.
