### ISSUE TITLE
Using Application context instead of Activity context for Realm object instantiation

### ISSUE THREAD

**Issue by sam-ghosh** [realm/realm-java#700]
In all the examples, I see that the Context used is an activity context

```
Realm realm = Realm.getInstance(this);
```

My app has multiple activities, and I want to unify all database operations in the App class (extends Application). Will it be fine to call the same getInstance(this) in Application class, with the Application context?

Thanks

**Comment by lambed** [comment]
How would you go about getting the Context in a Unit Test environment?

**Comment by cmelchior** [comment]
Realm isn't supported currently when running JVM unit tests. For that we need #2339 . For integration tests you can use `InstrumentationRegistry.getTargetContext()`

**Comment by lambed** [comment]
Thank you.


Edward L. Walker
414-220-0418 (Google Voice)


 
 

    On Tuesday, April 10, 2018, 2:52:04 PM CDT, Christian Melchior <notifications@github.com> wrote:  
 
 
Realm isn't supported currently when running JVM unit tests. For that we need #2339 . For integration tests you can use InstrumentationRegistry.getTargetContext()
