### ISSUE TITLE
Gradle sync failed: Connection timed out: connect. If you are behind an HTTP proxy, please configure the proxy settings either in IDE or Gradle.

### ISSUE THREAD

**Issue by prof-kalabwa** [realm/realm-java#7001]
I am using newly Android Studio 4.0.1, have excellent internet connection and not using proxy servers. I made a new project and get this error. Anyone who have solve this? Thank you.

**Comment by edualonso** [comment]
Hello @prof-kalabwa. In what way is this issue related to Realm? Also, could you use the bug report template instead? Thanks.

**Comment by rorbech** [comment]
Closed due to lack of information.
