### ISSUE TITLE
Saving in to new object

### ISSUE THREAD

**Issue by rameshcool** [realm/realm-java#7006]
I created a new object in realm database, but can't save in to that object showing null. which method need to call...I'm working on kotlin android

**Comment by rameshcool** [comment]
When i create an new object in realm android database and migrate new database name changes to default.realm. why it changes from original name to default. when i use these instances after migration shows error.which should be used
           Realm.setDefaultConfiguration(realmConfig)
           private var realm: Realm = Realm.getInstance(realmConfig) - before migration
            private var realm: Realm = Realm.getDefaultInstance()

**Comment by edualonso** [comment]
Hi @rameshcool. Please make sure to read the documentation regarding:
- models (https://realm.io/docs/kotlin/latest/#models) and object creation (https://realm.io/docs/kotlin/latest/#creating-objects)
- realms (https://realm.io/docs/kotlin/latest/#realms) and migrations - https://realm.io/docs/kotlin/latest/#migrations
You should be able to find all the information you need there.
