### ISSUE TITLE
2020-07-28 15:41:37.948498+0500 Inspektify[19461:419187] Task <0E36BE37-2F73-4D2A-A1CD-CC019FB263B4>.<1> finished with error [-1009] Error Domain=NSURLErrorDomain Code=-1009 "The Internet connection appears to be offline." UserInfo={_kCFStreamErrorCodeKey

### ISSUE THREAD

**Issue by FawadMahmood** [realm/realm-java#7008]
#### Actual Results

Offline stop working after app restart, get error https failed auth. 

#### Steps & Code to Reproduce

 dispatch({
            type:inspection.LOADING24HOURS,
            payload:true
        })
        if(realmInstance){
            console.log("FETCHING 24/7 RECORD")
            let inspections = []
            realmInstance.objects(INSPECTION).filtered('datetime >= $0', startOfDay(new Date()), endOfDay(new Date())).map((a)=>{
                console.log("FETCHING 24/7 RECORD" , a);
                
                let inspection={
                    address:{
                        state:a.address.state,
                        street:a.address.street,
                        zip:a.address.zip,
                    },
                    agent:{
                        name: a.agent.name,
                        checked: a.agent.checked,
                        email:a.agent.email,
                        phone:a.agent.phone,
                        type:a.agent.type,
                    },
                    client: {
                        name:a.client.name,
                        email:a.client.email,
                        checked:a.client.checked,
                        phone:a.client.phone,
   
                    },
                    fee: a.fee,
                    paid: a.paid,
                    template: a.template,
                    uid: a.uid,
                    datetime:a.datetime,
                  }
          
                  inspections.push(inspection);
            });

            console.log("FETCHING 24/7 RECORD" , inspections);

            dispatch({
                type:inspection.INSPECTION24HOURS,
                payload:inspections
              })
 
              dispatch({
                  type:inspection.LOADING24HOURS,
                  payload:false
              })

            // let inspections = []
            // realm.objects(INSPECTION).filtered('datetime >= $0', startOfDay(new Date()), endOfDay(new Date())).map((a)=>{
            
            //  });

           
             
        }
       

#### Version of Realm and tooling

Realm JS SDK Version: ^6.0.3
Node or React Native: 0.62.2
Client OS & Version: Mac OS/Iphone
Which debugger for React Native: Chrome/Release

**Comment by FawadMahmood** [comment]
Offline data stop showing after app close forcefully and restarts while offline.

**Comment by geragray** [comment]
@FawadMahmood would it be possible to change the issue name to reflect the problem and also fill in other fields in the description? It would help us to troubleshoot issue better. Thank you.

**Comment by FawadMahmood** [comment]
https://www.loom.com/share/f37e22190d814868986a2b2f0aa2674d here's video reference of issue I am having.

**Comment by blagoev** [comment]
@FawadMahmood the video shows that offline data is correctly displayed while offline. I can't say what is happening on create of new record. If your app needs to authenticate then you need to be online to do that. 

The code in the first post is not helping much. Could you file a new issue on the realm-js repo here: https://github.com/realm/realm-js preferably with a simple sample app which demos the exact problem.

**Comment by blagoev** [comment]
closing this one due since its a duplicate

**Comment by FawadMahmood** [comment]
> @FawadMahmood the video shows that offline data is correctly displayed while offline. I can't say what is happening on create of new record. If your app needs to authenticate then you need to be online to do that.
> 
> The code in the first post is not helping much. Could you file a new issue on the realm-js repo here: https://github.com/realm/realm-js preferably with a simple sample app which demos the exact problem.

But my application is already authenticated.
