### ISSUE TITLE
Caused by: io.realm.exceptions.RealmException: Could not initialize the Realm Object Server

### ISSUE THREAD

**Issue by wlingf** [realm/realm-java#7009]
release {                                  
            minifyEnabled true        
        }

**Comment by edualonso** [comment]
Hi @wlingf. Please use the bug report template to report bugs. Could you also provide us with the full stacktrace to fully understand what goes on? Thanks.

**Comment by rorbech** [comment]
Closing due to insufficient description. If reopening please provide all the details for the bug report template at https://github.com/realm/realm-java/issues/new?template=bug_report.md
