### ISSUE TITLE
Dynamic Query Builder In Realm Java

### ISSUE THREAD

**Issue by duongnv1996** [realm/realm-java#7011]
Hi dev team,

I'm new in realm DB. 
I wonder how to create dynamic query builder in the Realm. 
For example I want to add " equalTo/Not In/Greater than/Less than..." in the query to execute in Runtime. 
User will use these syntaxes to query my DB. 
How to using it.
Could you please guild me?
Thank you.

**Comment by cmelchior** [comment]
`RealmQuery` is a class you can call methods on. So if you have a dynamic query buildup. I would just store a reference to that class and then call `query.equalTo(field, value)` based on the user input.

Once the user click "Search", you can run either `query.findAll()` or `query.findAllAsync()`.

**Comment by cmelchior** [comment]
I assume the above answered your question. If not, feel free to reopen this issue.
