### ISSUE TITLE
App froze & crash

### ISSUE THREAD

**Issue by namtran303** [realm/realm-java#7018]
#### Goal
Add addUploadProgressListener to check when data upload to realm server success.

#### Actual Results

E/ActivityManager: ANR in jp.txcom.vplayer.free.beta (jp.txcom.vplayer.free.beta/jp.txcom.vplayer.free.EpisodeDetailActivity)
    PID: 26618
    Reason: Input dispatching timed out (Waiting to send non-key event because the touched window has not finished processing certain input events that were delivered to it over 500.0ms ago.  Wait queue length: 35.  Wait queue head age: 21743.0ms.)
    Load: 11.7 / 12.42 / 12.83
    CPU usage from 73288ms to 0ms ago (2020-08-04 10:34:37.536 to 2020-08-04 10:35:50.824) with 99% awake:
      99% 26618/jp.txcom.vplayer.free.beta: 81% user + 18% kernel / faults: 176047 minor 232 major
      20% 3685/audioserver: 19% user + 0.4% kernel / faults: 929 minor 150 major
      18% 3687/surfaceflinger: 12% user + 6.6% kernel / faults: 2328 minor 23 major
      14% 3861/media.codec: 7.6% user + 7.3% kernel / faults: 1906 minor 66 major
      12% 4166/system_server: 7.4% user + 5.3% kernel / faults: 26907 minor 640 major
      8.8% 3665/android.hardware.graphics.composer@2.1-service: 3.9% user + 4.8% kernel / faults: 443 minor
      6.8% 928/kswapd0: 0% user + 6.8% kernel
      6.3% 30398/adbd: 1.1% user + 5.1% kernel / faults: 626517 minor 1 major
      5.1% 3668/android.hardware.sensors@1.0-service: 2.6% user + 2.4% kernel / faults: 235 minor 4 major
      2.7% 16658/kworker/u16:1: 0% user + 2.7% kernel
      2.6% 3267/kworker/u16:6: 0% user + 2.6% kernel
      2.5% 25048/kworker/0:0: 0% user + 2.5% kernel
      2.1% 2025/decon0: 0% user + 2.1% kernel
      1.6% 25511/com.facebook.katana: 1.4% user + 0.1% kernel / faults: 18107 minor 97 major
      1.6% 3560/logd: 0.6% user + 0.9% kernel / faults: 1153 minor 312 major
      1.5% 26061/kworker/u16:7: 0% user + 1.5% kernel
      1.5% 17485/com.google.android.gms.persistent: 0.9% user + 0.5% kernel / faults: 14593 minor 3778 major
      1.2% 4448/com.android.systemui: 0.8% user + 0.3% kernel / faults: 12988 minor 1565 major
      0.8% 3264/kworker/u16:2: 0% user + 0.8% kernel
      1.1% 7/rcu_preempt: 0% user + 1.1% kernel
      1% 3656/android.hardware.audio@2.0-service: 0.3% user + 0.7% kernel / faults: 227 minor 50 major
      1% 17581/com.google.android.gms: 0.6% user + 0.3% kernel / faults: 10430 minor 339 major
      0.9% 894/cfinteractive: 0% user + 0.9% kernel
      0.8% 3266/kworker/u16:5: 0% user + 0.8% kernel
      0.7% 5416/com.sec.android.sdhms: 0.3% user + 0.3% kernel / faults: 5203 minor 289 major
      0.5% 26298/kworker/u17:3: 0% user + 0.5% kernel
      0.5% 1772/mmc-cmdqd/0: 0% user + 0.5% kernel
      0.5% 6774/kworker/u17:0: 0% user + 0.5% kernel
      0.4% 2800/ueventd: 0.3% user + 0% kernel / faults: 495 minor
      0.3% 23696/kworker/3:2: 0% user + 0.3% kernel
      0.3% 1593/irq/98-12c30000: 0% user + 0.3% kernel
      0.1% 4817/com.samsung.accessibility: 0.1% user + 0% kernel / faults: 4737 minor 876 major
      0.2% 2023/decon0-vsync: 0% user + 0.2% kernel
      0.2% 1558/irq/198-hxcommo: 0% user + 0.2% kernel
      0.2% 3686/lmkd: 0% user + 0.1% kernel
      0.1% 3855/netd: 0% user + 0.1% kernel / faults: 850 minor 1 major
      0.1% 25884/kworker/2:2: 0% user + 0.1% kernel
      0.1% 3859/wificond: 0% user + 0.1% kernel / faults: 89 minor
      0.1% 3561/servicemanager: 0% user + 0.1% kernel / faults: 143 minor 1 major
      0.1% 3664/android.hardware.graphics.allocator@2.0-service: 0% user + 0.1% kernel / faults: 108 minor
      0.1% 4407/com.android.phone: 0% user + 0% kernel / faults: 1942 minor 23 major
      0.1% 31341/dev.firebase.appdistribution: 0% user + 0% kernel / faults: 1005 minor 108 major
      0.1% 17013/jp.txcom.vplayer.free.dev: 0% user + 0% kernel / faults: 1654 minor 229 major
      0.1% 1//init: 0% user + 0% kernel / faults: 248 minor 1 major
      0.1% 3666/android.hardware.memtrack@1.0-service: 0% user + 0% kernel / faults: 150 minor
      0.1% 3835/argosd: 0% user + 0% kernel / faults: 21 minor
      0.1% 23743/kworker/1:0: 0% user + 0.1% kernel
      0% 25943/com.samsung.android.sm.policy: 0% user + 0% kernel / faults: 2628 minor 404 major
      0% 25964/com.sec.android.app.soundalive: 0% user + 0% kernel / faults: 2035 minor 440 major
      0% 2785/kworker/0:1H: 0% user + 0% kernel
      0% 3857/statsd: 0% user + 0% kernel / faults: 591 minor 9 major
      0% 3863/rild: 0% user + 0% ke

#### Steps & Code to Reproduce
- Have button, when lick on it will update data to realm and add **addUploadProgressListener** function.
```
session.addUploadProgressListener(ProgressMode.CURRENT_CHANGES, new ProgressListener() {
                    @Override
                    public void onChange(Progress progress) {
                                            
                    }
                });
```

- When i do action multi click and fast on button then app froze and crash.

#### Version of Realm and tooling
Currently, I using 'io.realm:realm-gradle-plugin:6.0.2'

Realm Sync feature enabled: Yes

Android Studio version:3.6.1

Android Build Tools version: 28.0.3

Gradle version: 3.4.1

Which Android version and device(s): all

**Comment by namtran303** [comment]
Could you please help us check it. if you need more information. Please let us know. Thanks

**Comment by cmelchior** [comment]
The progress listeners should not block the UI thread. The crash you get is an App-Not-Responding error because something is blocking the UI thread for an extended period. My guess is that you have a onclick listener that does something more than what you posted?

**Comment by namtran303** [comment]
Yes, the "addUploadProgressListener(ProgressMode.CURRENT_CHANGES, listener)" call in onclick function.
my code:

```
public void onClick(View view) {
        int id = view.getId();
        if (mRealm != null) {
            try {
                mRealm.beginTransaction();
               
                    onUpdateObject(id);
              
                mRealm.commitTransaction();
            } catch (Exception e) {
                
            }

              addUploadRealmListener(reactionName);
        }

    }

private void addUploadRealmListener(String reactionName) {
        ProgressListener listener = new ProgressListener() {
            @Override
            public void onChange(Progress progress) {
                if (progress.isTransferComplete()) {
                    if (mReactionListener != null)
                        mReactionListener.onEventReaction(reactionName);
                }
            }
        };

        if (SyncUser.current() != null) {
            SyncConfiguration mConfig = new SyncConfiguration.Builder(SyncUser.current(), Constants.REALM_URL)
                    .disableSSLVerification()
                    .waitForInitialRemoteData()
                    .build();
            SyncSession session = SyncManager.getSession(mConfig);
            session.addUploadProgressListener(ProgressMode.CURRENT_CHANGES, listener);
        }
    }
```

Do you have anything idea help to resolve this issue? Please give me to fix it.

Thanks

**Comment by cmelchior** [comment]
I see a number of issues with that code.

1) The progress listeners are not being called on the UI thread, so most likely this check `if (mRealm != null)` does the wrong thing since it probably check if a Realm exists on the UI thread.

2) Then you attempt to open a transaction, which I suspect fail, and then you swallow the exception

3) This leads you to calling `addUploadRealmListener()` again where you re-add the upload listener inside the first upload listener. I cannot remember at the top of my head if that is supposed to work or not, but it looks suspicious.

**Comment by rorbech** [comment]
It seems like you are just doing transactions on the UI thread and if doing many of these you will probably just block the UI completely. Try offloading the actual transaction from the UI thread.

**Comment by cmelchior** [comment]
@namtran303 I assume the above answered your questions. If not, feel free to reopen this issue.
