### ISSUE TITLE
Realm Database not persisting data on next app session

### ISSUE THREAD

**Issue by somghosh** [realm/realm-java#702]
I am writing to a Realm database (with beginTransaction) and then soon after commit, I can halt the process in debugger and run a query and find all the written data being queried.

Then I restart the debugger (Android Studio), and I run the same query (and I see that Realm realm object has the same file name), but the query this time is unable to find any data

    // inside the Application class

    if (appFirstTime == false){
            Realm realm3 = Realm.getInstance(getApplicationContext());
            RealmResults<FeedDBTableRow> query3 = realm3.where(FeedDBTableRow.class).findAll();
            // here, in the second run of the app, after data is written in the first time run, 
            // i can't see any rows, query size = 0 although it should have 10 rows

            }
    else{
        // get data and write on the first time of the app
        ArrayList<Feed> newsFeedList = response.getResults();

        Realm realm = Realm.getInstance(getApplicationContext());

        for (Feed f : newsFeedList) {
            realm.beginTransaction();
            FeedDBTableRow newRow = realm.createObject(FeedDBTableRow.class);

            newRow.setId(f.getId());
            newRow.setText(f.getText());
            newRow.setTime_created(f.getTime_created());
            newRow.setTime_modified(f.getTime_modified());
            newRow.setComments_count(f.getComments_count());
            newRow.setLikes_count(f.getLikes_count());
            newRow.setFeed_type(f.getFeed_type());
            newRow.setObj_id(f.getObj_id());
            newRow.setImage(f.getImage());
            newRow.setUser_name(f.getUser_name());
            newRow.setUser_earthmile_points(f.getUser_earthmile_points());
            newRow.setLiked(f.isLiked());
            newRow.setCommented(f.isCommented());
            newRow.setIs_private(f.is_private());
            newRow.setUrl(f.getUrl());
            newRow.setFeed_creator_id(f.getFeed_creator_id());

            realm.commitTransaction();
        }

        Realm realm2 = Realm.getInstance(getApplicationContext());
        RealmResults<FeedDBTableRow> query2 = realm2.where(FeedDBTableRow.class).findAll();
        // here I can see all the 10 rows in query object in database, when i query soon after writing in the same app session

        // set first time to false in preferences so that next time database is accessed
        appFirstTime = false

    }

**Realm class**

    public class FeedDBTableRow extends RealmObject {
        private int id;
        private String text;
        private Date time_created;
        private Date time_modified;
        private int comments_count;
        private int likes_count;
        private String feed_type;
        private int obj_id;
        private String image;
        private String user_name;
        private String user_earthmile_points;
        private boolean liked;
        private boolean commented;
        private boolean is_private;
        private String url;
        private int feed_creator_id;

    }

**Comment by cmelchior** [comment]
@somghosh 
Sorry for the late reply. Christmas and new years came in the way.

I took a look at your code, and from a quick glance it looks OK. Are you sure you are not somehow clearing/deleting the DB when in debug mode. I can see you have a if statement doing that. It might be triggered in debug mode?

**Comment by cmelchior** [comment]
Hi  @somghosh 
I assume you found a way to get it to work. If not please feel free to reopen.

**Comment by olayinkasf** [comment]
I'm having the same problem, I persist in the background send a broadcast to the opened activity and the activity can't find the persisted data.

**Comment by farmazon3000** [comment]
This issues (and similar like this http://stackoverflow.com/questions/27041093/realm-java-data-lost-when-restarting-application) are because you Realm are making examples with
```
Realm.deleteRealm(realmConfiguration); // Clean slate
```
in [Application.#onCreate()](https://developer.android.com/reference/android/app/Application.html#onCreate%28%29) like so https://github.com/realm/realm-java/blob/61d14cbcb0419c1962f044500e34d92ac23112a4/examples/threadExample/src/main/java/io/realm/examples/threads/MyApplication.java.

Fix your examples.
