### ISSUE TITLE
 java.util.concurrent.TimeoutException: io.realm.Realm.finalize() timed out after 10 seconds

### ISSUE THREAD

**Issue by kevinjam** [realm/realm-java#7030]
Am receiving io.realm.Realm.finalize() timed out after 10 seconds 
How do I solve this issue on inside realm  Daemons.java online 79

#### Version of Realm and tooling

Realm version(s): 6.1.0

Realm Sync feature enabled: Yes/No

Android Studio version: 3.6.3

Android Build Tools version: ?

Gradle version: 3.5.3

Which Android version and device(s): 5.1

**Comment by cmelchior** [comment]
Generally, the finalizers should run pretty fast. Is it something you can reproduce?

**Comment by cmelchior** [comment]
Closing due to no response. Also, how memory is managed has changed significantly In Realm Java 7.0.x. Please reopen if you can reproduce this issue in Realm Java 7.0.2+
