### ISSUE TITLE
Avoid copying listeners if not necessary

### ISSUE THREAD

**Issue by yigit** [realm/realm-java#704]
The listener interface copies the list every time a notification will be dispatched to avoid ConcurrentModificationException. [Realm#sendNotifications](https://github.com/realm/realm-java/blob/f58c6071eecab62ba96d1eebfc65aebcc58627a1/realm/src/main/java/io/realm/Realm.java#L992)
This is really bad for Android where GC is not good when cleaning short living objects. Instead, you can replace it with [CopyOnWriteArrayList](http://docs.oracle.com/javase/7/docs/api/java/util/concurrent/CopyOnWriteArrayList.html) and don't care about concurrent modification exceptions and be nice to the GC.

**Comment by emanuelez** [comment]
Thank you for the heads up! Will look into it in detail.

**Comment by cmelchior** [comment]
This was implemented as part of #1141
