### ISSUE TITLE
Update 6.1.0 to 7.0.0 - Default sort order change

### ISSUE THREAD

**Issue by 2ma** [realm/realm-java#7040]
#### Goal
Using realm in our project we relied on the default sort order for ordering elements, meaning we inserted a sorted list and we got the same list back. Migrating from 6.1.0 to 7.0.0 the default sort order is random and changes. Goal is to get the same sorted list back that we insert.

#### Actual Results
The list isn't sorted when querying it from the database.

#### Steps & Code to Reproduce
Create database, insertOrUpdate list of sorted elements.
Query findAll elements.
Results are in random order.

#### Version of Realm and tooling

Realm version(s): 7.0.1

Realm Sync feature enabled: No

Android Studio version: 4.0.1

Android Build Tools version: 30.0.1

Gradle version: 6.1.1

Which Android version and device(s): Nexus 5x running Android 8.1.0, emulator running sdk29

**Comment by rorbech** [comment]
@finnschiermer @jedelbo Is this intentional (or at least known) or did we never want to give such guarantees?

**Comment by cmelchior** [comment]
No, we never promised this order would be stable. In fact, it isn't. If you delete an object in the middle of a table, the last object would move to that position.

So inserting objects would only look stable if you never deleted objects.

If you want a stable order, you should always apply a sort parameter.

**Comment by 2ma** [comment]
We use it as cache so every item gets deleted before inserting anything, but I see your point. In that case we either stick with 6.1.0 or refactor our code base. Good to know at least, thanks!

**Comment by bennnjamin** [comment]
In my case, objects are never deleted. So to see the default sort ordered change between two versions of Realm is quite unexpected. @cemlechior mentions that sort order would look stable if you do not delete objects; however between two version of Realm, it's not stable. Before 7.0.0 there is one sort order and on 7.0.0 there is new sort order, even when objects are never deleted. In other words, the data in the database did not change between Realm versions, but the default sort order did.

Regardless of no sort order guarantees, there this seems like an undocumented change and at the very least this should be in the changelog as that is the first place I checked to see why the default sort order had suddenly changed. Of course it's easy to work around by sorting on a field name which is what we should have done anyway.

**Comment by ppamorim** [comment]
@bennnjamin You are totally right. This change should have been documented.

**Comment by jedelbo** [comment]
One thing to note is that with 7.0.0, the order of the objects is stable. The order will be maintained also when you delete objects. This is actually the main reason for making 7.0.0.
