### ISSUE TITLE
build failed exception : realm master

### ISSUE THREAD

**Issue by nitiwari-dev** [realm/realm-java#706]
I'm getting build exception from ream-master on rebuilding or ./gradlew assemble

FAILURE: Build failed with an exception.
* Where:
Build file '/home/nitesh/Desktop/realm-java-master/realm-jni/build.gradle' line: 150

* What went wrong:
Execution failed for task ':realm-jni:buildAndroidJniMips'.
> Process 'command 'make'' finished with non-zero exit value 2

Local.properties:

sdk.dir=/usr/share/android-studio/data/sdk
ndk.dir=/home/nitesh/android-ndk-setup/android-ndk-r9d

stacktrace of exception
http://pastebin.com/vzyQUA6U

I have tried downgrading my NDK from r9d from 10.

My GCC version :4.6.4

**Comment by emanuelez** [comment]
Hello,
this was reported before but we were not able to reproduce it.
Did you start from a fresh clone or the repo or have you been using it for a while before? Does a `./gradlew clean` help in any way?

**Comment by cmelchior** [comment]
@nitiwari-dev 
Did you get it to work?

**Comment by nitiwari-dev** [comment]
Hello,
starting with fresh clone did the work :-)
