### ISSUE TITLE
Move objectServerExample to Kotlin Example

### ISSUE THREAD

**Issue by Pey-crypto** [realm/realm-java#7066]
#### Describe your problem or use case

Right now the objectServerExample resides in the realm-java folder.

#### Describe the solution you'd like

It is written in kotlin and needs to be moved to the realm kotlin example directory

**Comment by cmelchior** [comment]
We don't have a Realm Kotlin example directory right now, so not entirely sure what you refer to? In any case, the examples right now are a mix of Kotlin and Java, which is on purpose, because we want to show how you can use the Realm Java library from Kotlin.

**Comment by Pey-crypto** [comment]
It would be really helpful if you could put the example in different folders....Just a suggestion
