### ISSUE TITLE
RealmTests#getNumberOfActiveVersions indicates version leaks

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#7067]
As part of the implementation in https://github.com/realm/realm-java/pull/7055 I added a new unit test that verifies the behavior of `getNumberOfActiveVersions()`. The numbers reported do look at bit odd though and could indicate that we are leaking versions in certain scenarios. It could point to a bug in our caching layer or how Object Store manages the transactions.

```
    @Test
    public void getNumberOfActiveVersions() throws InterruptedException {
        CountDownLatch bgWritesCompleted = new CountDownLatch(1);
        CountDownLatch closeBgRealm = new CountDownLatch(1);
        // TODO: Why 2 instead of 1?
        assertEquals(2, realm.getNumberOfActiveVersions());
        Thread t = new Thread(() -> {
            Realm bgRealm = Realm.getInstance(realmConfig);
            assertEquals(2, bgRealm.getNumberOfActiveVersions());
            for (int i = 0; i < 5; i++) {
                bgRealm.executeTransaction(r -> { /* empty */ });
            }
            assertEquals(6, bgRealm.getNumberOfActiveVersions());
            bgWritesCompleted.countDown();
            TestHelper.awaitOrFail(closeBgRealm);
            bgRealm.close();
        });
        t.start();
        TestHelper.awaitOrFail(bgWritesCompleted);
        assertEquals(6, realm.getNumberOfActiveVersions());
        closeBgRealm.countDown();
        t.join();
        // TODO realm.refresh() does not work. But closing and reopening the Realm brings it correctly down? 
        realm.close();
        realm = Realm.getInstance(realmConfig);
        assertEquals(1, realm.getNumberOfActiveVersions());
        realm.close();
        try {
            realm.getNumberOfActiveVersions();
            fail();
        } catch (IllegalStateException ignore) {
        }
    }
```

**Comment by finnschiermer** [comment]
@cmelchior Realm refresh cannot by itself trigger GC of old versions. Although it will release those versions for later GC, they can only be reclaimed by a commit. So you need a commit after any refresh, before you can see the expected result in getNumberOfActiveVersions().

**Comment by cmelchior** [comment]
Ah, interesting. Thanks 👍

**Comment by cmelchior** [comment]
So seems the only "problem" is why the test starts with 2 active versions. That might just be an artifact on how we set up Realm with background notifiers, but we need to understand exactly what is going on.

**Comment by cmelchior** [comment]
Talking to the Core team, we can explain the above numbers. It starts out as 2 due to how Core count versions and due to us needing to write the schema when creating the first file.

Closing as working-as-intended.
