### ISSUE TITLE
REALM   : ../src/realm/group_writer.cpp:211: [realm-core-5.23.8] Assertion failed: m_free_positions.size() == m_free_lengths.size() with (top.get_ref(), m_free_positions.size(), m_free_lengths.size()) =  [590056, 56, 0]

### ISSUE THREAD

**Issue by wuhenzhizao** [realm/realm-java#7070]
#### Goal
No Crash

#### Actual Results
Crash when app launched

Realm version(s): 6.1.0

Realm Sync feature enabled: No

REALM   : ../src/realm/group_writer.cpp:211: [realm-core-5.23.8] Assertion failed: m_free_positions.size() == m_free_lengths.size() with (top.get_ref(), m_free_positions.size(), m_free_lengths.size()) =  [590056, 56, 0]

**Comment by edualonso** [comment]
Hi @wuhenzhizao. Could you provide a use case that helps us with reproducing the issue? Additionally, could you provide a full stack trace of the crash?

**Comment by wuhenzhizao** [comment]
It's hard to reproduce

**Comment by edualonso** [comment]
Unfortunately, we cannot do much with the information you are providing us. Is this happening in a production environment? Have you been able to reproduce it yourself? If so, what is it that you do when the app is launched and when does it crash? e.g. migrating to a new schema, inserting something, deleting something, etc. Anything can be of help.
