### ISSUE TITLE
How to migrate moving RealmObject to another module

### ISSUE THREAD

**Issue by edgar-zigis** [realm/realm-java#7073]
I have been developing a monolith app for a while already, but recently I have decided to create a separate data layer module where I would keep all the realm classes. However, I didn't really find an example how to deal with the migration.
Could maybe somebody share such experience?

**Comment by clementetb** [comment]
You will not need any migration if you don't modify the models' names:

1. Move your existing models into the new module, at any package location, but keep their names.
2. Expose these modules via `RealmModule`. [Schemas doc](https://realm.io/docs/java/latest/#schemas)
3. Use the new module in your Realm configuration, keep the same Realm name.

Be aware that if you modify or rename the models you will need to migrate the data.

**Comment by edgar-zigis** [comment]
Thank you @clementetb ! It did work correctly! I would like to add to the 3rd point, that just moving RealmModule to the library package will work (if you want completely move all the entities).
