### ISSUE TITLE
Is Realm  support "group by"  like MySql

### ISSUE THREAD

**Issue by tiebenxin** [realm/realm-java#7099]
for example, group data by mouth,  according to the  time of data

**Comment by sdex** [comment]
Yeah, use [distinct](https://realm.io/docs/java/latest/api/io/realm/RealmQuery.html#distinct-java.lang.String-).

**Comment by tiebenxin** [comment]
> Yeah, use [distinct](https://realm.io/docs/java/latest/api/io/realm/RealmQuery.html#distinct-java.lang.String-).

Ok, Thank you very much!

**Comment by cmelchior** [comment]
There is also: https://github.com/realm/realm-java/issues/2309
