### ISSUE TITLE
Realm doesn't auto-refresh immediately

### ISSUE THREAD

**Issue by ImGauravC** [realm/realm-java#714]
I have an activity where I make an api call to load a JSONArray and show it on the UI using a RealmBaseAdapter with automaticUpdate set to true. I add stuff to the Realm in the onSuccess callback of the api request using a handler thread. 

My issue is that the UI is not automatically updated for a while after committing the transaction. How do I make it work?

**Comment by cmelchior** [comment]
Without more info and code it is hard to say. From you description it sounds like it happens eventually? How long after? 

It could indicate that something in your UI is not updating itself properly when notifyDatasetChanged() is called.

One place to start could by adding your own RealmChangedListener and checking that it gets called immediately after committing your transaction.

**Comment by cmelchior** [comment]
Hi @ImGauravC 
I assume you figured this out? It not, please fill free to reopen.
