### ISSUE TITLE
Cannot copy a normal Pojo from RealmExtendedClass from an object created by CreateObject()

### ISSUE THREAD

**Issue by somghosh** [realm/realm-java#715]
I have a class AccountData extends RealmObject, and then I createObject() and write to Realm, and then I am trying to use that same variable by copying it into another one, but that seems not to work

	Realm realm = Realm.getInstance(App.this);
	realm.beginTransaction();
	AccountData newAccountData = realm.createObject(AccountData.class);
	newAccountData.setName("ABC")
	realm.commitTransaction();
	
	AccountData myVar = newAccountData;		// this does not work, i dont get myVar.name = "ABC"

**Comment by cmelchior** [comment]
You can't use ```myVar.name```. Currently Realm only works using getters and setters, you should get a compile error otherwise if you try to create a RealmObject with public fields .

What does ```myVar.getName()``` return?

**Comment by cmelchior** [comment]
Hi @somghosh 
I assume you figured it out. If not, please feel free to reopen this.
