### ISSUE TITLE
Is Time complexity of findFirst() after sort in Realm is O(n), If the field is not indexed?

### ISSUE THREAD

**Issue by sudhanshugaur4** [realm/realm-java#7155]
In Realm is the Time complexity of findFirst() after sort always O(n) ? If the field is not indexed, Because if it is optimizing it's query then it should be O(n) ?

**Comment by rorbech** [comment]
@sudhanshugaur4 It is not optimized for that. You would have to add an index to achieve that.

**Comment by sudhanshugaur4** [comment]
@rorbech So even if I am querying for findFirst() the query is not running in O(n), Can you guys please add this, as it is very basic functionality to implement, I would have never thought functionality like this is still missing from the realm, Also I don't think it is a very much time-consuming thing to implement.

**Comment by sudhanshugaur4** [comment]
@rorbech and what is the time complexity for `max()` If the field is not indexed? Is it still not of O(n)?

**Comment by nirinchev** [comment]
Are you experiencing issues due to the asymptotic performance of `findFirst` on a sorted collection - what are the query times you're seeing? And if so, why is adding an index not an option? While I don't question the performance gain of reducing a O(nlogn) operation to O(n), it hasn't been a big enough problem for users and there have been more meaningful areas we can focus on. The good news is that the Core database is [open source](https://github.com/realm/realm-core) and we'd be happy to accept a contribution that optimizes this case.

**Comment by sudhanshugaur4** [comment]
@nirinchev I am not adding index as it is not a good option to index every field and currently I am already indexing fields which I am performing most of my query on, I need to find the maximum on a field that's why I thought why waste index on a field which I am only querying at only one place. Also can you please tell me `is the time complexity for max() If the field is not indexed? Is it still not of O(n)?`

**Comment by jedelbo** [comment]
If you run max() on a query then the performance is O(n). But this was not how you put the question in the first place. If you run a query and then subsequently sort the result, the the performance is O(n m log m), where n is the table size and m is the match count.

**Comment by sudhanshugaur4** [comment]
@jedelbo So according to you the query `realm.where(MyClass.class).sort("time").findFirst()` performance is O(n*m*log(m)) and as m=1(match count) so performance is O(n*1*log(1)) = O(n), am I correct ?

**Comment by jedelbo** [comment]
Sorry - I was mistaken about the way Java maps the queries onto the Core functionality. Unfortunately your query ends up sorting all elements in the table - so O(n log n). If you goal is just to find the object with the lowest timestamp, then there should be a `RealmQuery.minimumDate()` with O(n) performance.

**Comment by sudhanshugaur4** [comment]
@jedelbo Yes I know and thanks for telling, actually I want other fields too at minimumDate that's why I cannot only use `RealmQuery.minimumDate() `.

**Comment by cmelchior** [comment]
@sudhanshugaur4 I assume the above answered your question, so closing this issue. If not, feel free to reopen.
