### ISSUE TITLE
Crash when registering change listeners with Realm 7.0.8

### ISSUE THREAD

**Issue by weizhonglai** [realm/realm-java#7158]
#### Goal
Bug fixed

#### Actual Results
Logcat: Fatal signal 11 (SIGSEGV), code 1 (SEGV_MAPERR), fault addr 0x0 in tid 12354

#### Steps & Code to Reproduce
I getting 2 crash in realm v7.0.8, but it's working on realm v3.5.0

1. It will crash when addChangeListener is added. 
   private OrderedRealmCollectionChangeListener<RealmResults<ModelC>> orderRealmChangeListener = (orders, changeSet) -> {
        if (!orders.isValid()){
          //order invalid
        }
    };

```
ModelA modelA = realm.where(ModelA.class).equalTo(ID, "1").findFirst();
RealmList<ModelB> realmListModelB = modelA.getModelB(); **realmListModelB = 2 result, must have more than 1 result, if only 1 result, no crash**
RealmResults<ModelB> realmResultModelB = realmListModelB.where().equalTo(ID, "1", Case.INSENSITIVE).findAll(); **there are getting no result**
modelC.removeAllChangeListeners();
modelC.addChangeListener(orderRealmChangeListener); **crash here**
```

1. Under the following conditions, it will crash.
        ModelA modelA = realm.where(ModelA.class).equalTo(ID, "1").findFirst();
        RealmList<ModelB> realmListModelB = modelA.getModelB(); **realmListModelB = 2 result, must have more than 1 result, if only 1 result, no crash**
        RealmResults<ModelB> realmResultModelB = realmListModelB.where().equalTo(ID, "1", Case.INSENSITIVE).findAll();  **added Case.INSENSITIVE in query, and realmResultModelB no result found.**

```
    if (!realmResultModelB.isEmpty()){ **Must have isEmpty or .size() with realmResultModelB**
        android.util.Log.i("TEST","IN!");
    }else{
        modelC.addChangeListener(orderRealmChangeListener);
    }
```

**When all the codes are executed, it will not crash, but when any query with realm is executed again, it will crash**
removed Case.INSENSITIVE, the app will no crash

#### Version of Realm and tooling
Realm version(s): 7.0.8

Realm Sync feature enabled: Yes

Android Studio version: 4.1

Android Build Tools version: 28.0.2

Gradle version: 4.1.0

Which Android version and device(s): Nexus 5X API 28 emulator

**Comment by Raynor999** [comment]
Java_io_realm_internal_OsSharedRealm_nativeCancelTransaction

OS Version: Android 10 (QP1A.190711.020.F9160ZCU1ATI4)
Report Version: 104

Exception Type: Unknown (SIGSEGV)

Application Specific Information:
Segfault

Thread 0 Crashed:
0   librealm-jni.so                 0xb14cc366          <unknown> + 2974597990
1   librealm-jni.so                 0xb14cc323          <unknown> + 2974597923
2   librealm-jni.so                 0xb14359db          <unknown> + 2973981147
3   librealm-jni.so                 0xb152290b          <unknown> + 2974951691
4   librealm-jni.so                 0xb15252db          <unknown> + 2974962395
5   librealm-jni.so                 0xb148e175          <unknown> + 2974343541
6   librealm-jni.so                 0xb148d7dd          <unknown> + 2974341085
7   librealm-jni.so                 0xb14399b1          Java_io_realm_internal_OsSharedRealm_nativeCancelTransaction
8   base.odex                       0xbebaf2d9          <unknown> + 3199922905

**Comment by vangivang** [comment]
We are seeing something similar (if not the same) but I only have Crashlytics info that doesn't reveal a lot. Perhaps you can get the functions names out of the pcs:

Android 11 (Pixel 3a).
Application was in the background (there is a Foreground service running).

Crashed: Thread :  SIGABRT  0x0000281700004362
#00 pc 0x72ac4e8e4c libc.so 
#01 pc 0x72ac4e8e1c libc.so 
#02 pc 0x6f99e6e25c librealm-jni.so 
#03 pc 0x6f99e6e3b4 librealm-jni.so 
#04 pc 0x6f99e6b4f8 librealm-jni.so 
#05 pc 0x6f99e6ae00 librealm-jni.so 
#06 pc 0x6f99c43af4 librealm-jni.so 
#07 pc 0x72ac54a788 libc.so 
#08 pc 0x72ac4eae08 libc.so

**Comment by cmelchior** [comment]
@Raynor999 @vangivang Do you have the full stack traces for this crashes?

**Comment by vangivang** [comment]
> @Raynor999 @vangivang Do you have the full stack traces for this crashes?

No.. I'm sorry. The only indication I have is what I see in the Crashlytics report which was copied here.
I am trying to reproduce it but so far it did not succeed.

**Comment by Raynor999** [comment]
> @Raynor999 @vangivang Do you have the full stack traces for this crashes?

sorry，I found this crash in the Crashlytics report。

**Comment by Raynor999** [comment]
OS Version: Android 10 (HRY-AL00Ta 10.0.0.168(C00E70R4P7))
Report Version: 104

Exception Type: Unknown (SIGSEGV)

Application Specific Information:
Segfault

Thread 0 Crashed:
0   librealm-jni.so                 0xb468d366          <unknown> + 3026768742
1   librealm-jni.so                 0xb468d323          <unknown> + 3026768675
2   librealm-jni.so                 0xb45f69db          <unknown> + 3026151899
3   librealm-jni.so                 0xb46e390b          <unknown> + 3027122443
4   librealm-jni.so                 0xb46e9fd1          <unknown> + 3027148753
5   librealm-jni.so                 0xb46e85c5          <unknown> + 3027142085
6   librealm-jni.so                 0xb46485ff          <unknown> + 3026486783
7   librealm-jni.so                 0xb4638cfd          <unknown> + 3026423037
8   librealm-jni.so                 0xb4638c91          <unknown> + 3026422929
9   librealm-jni.so                 0xb46392ad          <unknown> + 3026424493
10  librealm-jni.so                 0xb4639191          <unknown> + 3026424209
11  librealm-jni.so                 0xb4639323          <unknown> + 3026424611
12  librealm-jni.so                 0xb4647807          <unknown> + 3026483207
13  librealm-jni.so                 0xb4647687          <unknown> + 3026482823
14  librealm-jni.so                 0xb4638de9          <unknown> + 3026423273
15  librealm-jni.so                 0xb45fa543          Java_io_realm_internal_OsSharedRealm_nativeGetSharedRealm
16  base.odex                       0xb93d0ee5          <unknown> + 3107786469

**Comment by rorbech** [comment]
@weizhonglai Are you able to provide a minimal example project that shows the crashes? It is a bit unclear how you model looks and what you are trying to achieve from the initial description.

**Comment by rorbech** [comment]
@vangivang @Raynor999 You issues does not look related to the original issue of registering change listeners, so consider adding a separate issue with description of what you are trying to achieve and any indicators of around what fails. The stack traces are required to be in a format somewhat like described in https://developer.android.com/ndk/guides/ndk-stack for us to be able to unroll.

**Comment by cmelchior** [comment]
This sounds like the same bug that was fixed here: https://github.com/realm/realm-core/blob/master/CHANGELOG.md#fixed-1

We will be making a 10.0.1 release shortly that should fix this.

**Comment by cmelchior** [comment]
Realm Java 10.0.1 has been released which I believe should fix this. If not, please reopen the issue.
