### ISSUE TITLE
Realm Exception while inserting data

### ISSUE THREAD

**Issue by vaibhav2800** [realm/realm-java#7167]
I am using realm-android for my project and using 5.10.0 as project is OLD.

Whenever data tried to insert in Realm , it got following error.

**Found error inside the execution block of add data , io.realm.exceptions.RealmException: '' doesn't exist in current schema.**
	at io.realm.internal.b.a(ColumnIndices.java:112)
	at io.realm.aq.e(RealmSchema.java:241)
	at io.realm.ar.a(SchemaConnector.java:48)
	at io.realm.internal.a.a.a(CachedFieldDescriptor.java:71)
	at io.realm.internal.a.c.e(FieldDescriptor.java:304)
	at io.realm.internal.a.c.a(FieldDescriptor.java:190)
	at io.realm.RealmQuery.c(RealmQuery.java:316)
	at io.realm.RealmQuery.a(RealmQuery.java:311)
	at io.realm.RealmQuery.a(RealmQuery.java:296)

I have crossed checked and schema exists and was working fine earlier . It is showing schema name '' empty . I am not able to reproduce it . I have also cross verified for ProGuard and it seems fine. This particular data table was in sync mode. I have resolved this issue by clearing data but that data got lost. I am looking for reason so that in future this issues should not arise . 

**P.S. :: Proguard line**
-keep public class * extends io.realm.RealmObject { *; }

Realm version(s):  5.10.0
Realm Sync feature enabled: Yes
Android Build Tools version: 27.0.3
Gradle version: 3.1.3

Which Android version and device(s):  8.1.0

**Comment by rorbech** [comment]
It is really hard to say anything around this from the current details. We would need some more details around how the model looks and what operations are leading to this to be able to reproduce. Are you able to get a hold of a realm exhibiting this behavior? If so are you able to open it with Realm Studio?

**Comment by vaibhav2800** [comment]
This issue was found in production so not able to check it on realm studio (chances are that realm may be corrupted).
As of now provided quick fix by removing DB files , but i am looking for root cause so that it can be avoided in future .

Table Structure :
class A extends RealmObject{
String id;
List<B> list;

}

class B extends RealmObject{
}

Realm query :: 
realm.where(A.class).equalTo("id", id).findAll();

**Comment by cmelchior** [comment]
@vaibhav2800 Can you provide more information about how often this error has happened and on which devices?

**Comment by vaibhav2800** [comment]
@cmelchior I have observed this issue 3 times in 3 months . ( As I have that much data only )
OS :: Android 8.1

I have not seen this after reporting it, but would be better if can get root cause .

**Comment by rorbech** [comment]
I cannot find a valid path for emitting the error you have observed given the model and query you have provided. Please push any new observations or ideally the Realm-file exhibiting this our way.

**Comment by vaibhav2800** [comment]
As i do not have new data and not encountered this error for some time. closing it.
