### ISSUE TITLE
Update migration example realms to Core 6 supported formats

### ISSUE THREAD

**Issue by rorbech** [realm/realm-java#7169]
As of Core 6:
```
Only file format versions from 6 and onwards can be opened (realm core v2.0.0)
```
We should update the realm files in our migration example to a format supported by the current core version.

**Comment by IgorGanapolsky** [comment]
How to resolve this crash?
> Process: examples.realm.io.migration, PID: 7100
    java.lang.RuntimeException: Unable to start activity ComponentInfo{examples.realm.io.migration/io.realm.examples.realmmigrationexample.MigrationExampleActivity}: io.realm.exceptions.RealmFileException: Opening Realm files of format version 2 is not supported by this version of Realm (Database has an unsupported version and cannot be upgraded
    Exception backtrace:
    <backtrace not supported on this platform>) (/data/data/examples.realm.io.migration/files/default0.realm) in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 107 Kind: FORMAT_UPGRADE_REQUIRED.

**Comment by rorbech** [comment]
@IgorGanapolsky We need to update the realms stored in the example to a newer format that is supported by the current core implementation.

**Comment by IgorGanapolsky** [comment]
@rorbech Is there an easy updater or migration tool for that?  I have the same requirement in my project.

**Comment by rorbech** [comment]
You can open the realm and save it with an old version of Realm Studio that supports reading the old format but saves it in a newer format, e.g. https://studio-releases.realm.io/v3.8.3

**Comment by IgorGanapolsky** [comment]
**When I go to save the DB, how do I specify the newer format here?**

<img width="1792" alt="Screen Shot 2020-10-27 at 12 12 13 PM" src="https://user-images.githubusercontent.com/201209/97329687-b26d7b80-184d-11eb-9865-e3bc08fc33dc.png">

**Comment by rorbech** [comment]
You cannot select it manually. It use the most recent format for the bundled core implementation, but we only dropped support for very old format, so saving it with Realm Studio v. 3.8.3 (last version supporting the very initial format) should make it good to go.
