### ISSUE TITLE
Null string is not allowed

### ISSUE THREAD

**Issue by somghosh** [realm/realm-java#717]
I am trying to set a String variable in the RealmObject extended MyObject to "", and it says Null String is not allowed. My JSON responses from server are Null string and that's what I need to store. What is the way around? Thanks

**Comment by cmelchior** [comment]
The current work around is having a boolean like eg. strIsNull in your model and set it to true when needed.

We do however want to add support for null values: It is tracked here https://github.com/realm/realm-java/issues/478

**Comment by cmelchior** [comment]
I assume that this answered your question. If not please feel free to reopen.

**Comment by aercanozcan** [comment]
That doesn't solve many cases. I have a lot of string data that can be null and I cant track them like this every time. On the other hand we are not capable to implement methods in model classes therefore we don't have a control over model like (gson+retrofit) if (x==null){ x="";//or xNull=true} in setter method.

**Comment by cmelchior** [comment]
@aercanozcan Actually realm will transparently handle null values if your object is coming from Retrofit. It will automatically be converted to "" (empty string). Of course if your business logic depends on a difference between `null` and `''` then that approach won't work and the only workarounds is a companion boolean. Sorry.

**Comment by aercanozcan** [comment]
> if your object is coming from Retrofit. It will automatically be converted to "" 

that calms me down :)

**Comment by beeender** [comment]
@aercanozcan We have a bug in the update from JSON interface. When you update your object with JSON which contains a field with null value, that field will be ignored. See #1344 . Fix is on the way.

**Comment by aercanozcan** [comment]
Thank you! I will  use some workaround until the fix arrives.
