### ISSUE TITLE
Listen for change of data in background with realm (Realm + Flow + Clean Architecture + Background)

### ISSUE THREAD

**Issue by hoanganhtuan95ptit** [realm/realm-java#7187]
#### Problem

I am working with **Realm** in **Clean Architecture**, I have a problem with listening for change of data in DB because my DB is handled in the **background thread**.

If I use the listener in the background an error is fired asking the listener to be handled in the looper.

#### Solution

Thankfully I have found a solution with **Flow**

Code Base

```kotlin
     @OptIn(ExperimentalCoroutinesApi::class)
     fun <S : RealmObject, R> handlerAndReturnListFlow(block: () -> RealmQuery<S>): Flow<List<R>> = callbackFlow {

        val results = block().findAllAsync()!!
        val realm = results.realm!!

        val listener = RealmChangeListener<RealmResults<S>> { t ->
            offer(realm.copyFromRealm(t))
        }

        results.addChangeListener(listener)

        offer(realm.copyFromRealm(results))

        awaitClose {
            if (!realm.isClosed) {
                results.removeChangeListener(listener)
                realm.close()
            }
        }
    }.flowOn(Dispatchers.Main) // listener in looper main thread 
    /*.flowOn(android.os.Handler(HandlerThread("RealmDb").apply { start() }.looper).asCoroutineDispatcher("db"))*/ //  or listener in looper background thread
    .map {
        convert entity db to entity normal
    }
```

Code in Database

```kotlin
    fun getAll() = handlerAndReturnListFlow {
        Realm.getDefaultInstance().where(TestObject::class.java)
    }
```

Code in Repository

```kotlin
    fun getAll() = testDb.getAll()
```

Code in UseCase

```kotlin
    fun execute() = testRepository.getAll().map{
         // TODO in background 
    }
```

Code in ViewModel 

```kotlin
    fun listTest = getAllTest.execute()
        .asLiveData(Dispatchers.IO) // background
```

Code in Activity 

```kotlin
    viewModel.listTest.observe(this){
         Log.d("HoangAnhTuan95Ptit", "onCreate: ${it.size}")
    }
```

**Comment by cmelchior** [comment]
I'm not sure if there is a question here, but yes, listening to changes require Looper because we need a point in time where we can advance the Realm without doing so in the middle of users running code.

This is most commonly the Main thread, but any Looper will do. `Dispatcher.Main` runs on the UI thread, which is why it works there.

Maybe this article can provide more light on it: https://academy.realm.io/posts/threading-deep-dive/

**Comment by rorbech** [comment]
Closing with no further action. Already supplied some documentation of behavior/requirements. Feel free to open if the issue persists or further clarification is needed.
