### ISSUE TITLE
Case insensitivesearch doesn't work with UTF-8 cyrillic symbols 

### ISSUE THREAD

**Issue by tseglevskiy** [realm/realm-java#719]
My database contains word "Лиза". Method .contains("description", "Лиз", false) founds the record, but  .contains("description", "лиз", false) founds nothing.

**Comment by cmelchior** [comment]
Hi @tseglevskiy 

It is a known limitation caused by differences in UTF-8 implementations. We are tracking it here: https://github.com/realm/realm-java/issues/581

Closing this a duplicate.
