### ISSUE TITLE
Updating realm causes Primary Key property class has duplicate values after migration

### ISSUE THREAD

**Issue by philippeauriach** [realm/realm-java#7202]
## Goals
Update Realm version without making my app crash on update. 

## Expected Results
No crash

## Actual Results
Realm cannot open (happened to 90% of users who made the update). The error is :
```
java.lang.IllegalStateException: Primary key property 'class_CatchDAO.primaryKeyStr' has duplicate values after migration.
```

I should mention that I am not touching those classes, the primary keys are here for a long time (a few years) and working as expected.

By the way, it happens on iOS too (see https://github.com/realm/realm-cocoa/issues/6941).

## Steps for others to Reproduce
I could not reproduce. Happened only in production, when updating my app from the previous version (with realm 7.0.0) to the latest version with realm 7.0.5 or 7.0.8

## Code Sample
One of the affected classes:
```java
@org.parceler.Parcel
public class CatchDAO extends RealmObject implements BaseDAO {
    @PrimaryKey
    @SerializedName("creationDeviceId")
    String primaryKeyStr;
//...more props and getter setters
}
```

#### Version of Realm and tooling
Realm version(s): 7.0.8

Realm Sync feature enabled: No

Android Studio version: 4.1

Android Build Tools version: ?

Gradle version: 6.1.1

Which Android version and device(s): Any

**Comment by clementetb** [comment]
A part of the Realm library version upgrade, did you happen to do any schema change too? If so could you share the migration logic?

**Comment by philippeauriach** [comment]
I added two fields :
```
        if (oldVersion < 96) {
            schema.get("CatchDAO")
                    .addField("releasedCount", Double.class);
            schema.get("CatchDAO")
                    .addField("individualMeasurementsJsonString", String.class);
        }
```

**Comment by clementetb** [comment]
How come you use a `<` char in the migration, aren't you following the [recommended pattern](https://realm.io/docs/java/latest/api/io/realm/RealmMigration.html)?

**Comment by philippeauriach** [comment]
I didn't know about the recommended pattern, just kept adding migrations the following way :
```
...
        if (oldVersion < 95) {
            schema.get("CatchDAO")
                    .addField("fishingType", String.class);
        }
        if (oldVersion < 96) {
            schema.get("CatchDAO")
                    .addField("releasedCount", Double.class);
            schema.get("CatchDAO")
                    .addField("individualMeasurementsJsonString", String.class);
        }
...
```
Which, if I'm not mistaking or missing something, will perform the same thing as in the recommended pattern, just without having an incremented variable in each block?

Anyway, the primary key field was never modified wince the creation of the class (which was here at the beginning, before any migration). The problems occurs after migrating from the previous schema version, 95. What do you mean by "what steps it goes through"?

**Comment by rorbech** [comment]
@jedelbo Any thoughts on this? Could this be a result of any underlying upgrade in core? Also reported in https://github.com/realm/realm-cocoa/issues/6941

**Comment by jedelbo** [comment]
This is strange. First of all I cannot figure out why the uniqueness is even checked while there is no change in primary key column. There are clearly some parts of the picture missing. @philippeauriach could you by any chance share a sample file produced by the version that worked (v7.0.0?). Looking at the schema in more detail might give us a hint what might go wrong. You can send the file to jorgen.edelbo@mongodb.com.

**Comment by philippeauriach** [comment]
What do you mean by a sample file? A sample realm file? I'm not sure I can get one as I did not manage to reproduce on my end.
 
(for info, since then I added a new migration which just wipe the database, which forces users to login and then data came back with my synchronisation service).

**Comment by jedelbo** [comment]
Yes, a sample realm file. It does not need to be one that actually reproduces the error. It would be optimal to get the file as produced by v7.0.0 and also after upgrading to v7.0.8.

**Comment by philippeauriach** [comment]
Sorry for the delay, I'll try to get two files asap

**Comment by philippeauriach** [comment]
Hi @jedelbo , I finally had time to sen you the files by email, I'm really sorry for the time it took.

Hope it helps!

**Comment by jedelbo** [comment]
@philippeauriach Unfortunately I was not able to come up with a possible cause based on the files received. I think I would need a file that actually produces the error, but I can feel that that could be difficult as you are not able to reproduce the error.

**Comment by philippeauriach** [comment]
@jedelbo indeed I have no way to reproduce, therefore I'm not able to get a file. We might want to close this issue as I found a dirty workaround, and I'll open it if it comes back next time I upgrade my realm version.

Thanks anyway !
