### ISSUE TITLE
OutOfMemoryError to get Big String

### ISSUE THREAD

**Issue by gvmarozzi** [realm/realm-java#7205]
I am getting OutOfMemoryError to access one attribute that contains a big string.

```
Fatal Exception: java.lang.OutOfMemoryError: Failed to allocate a 510076 byte allocation with 299448 free bytes and 292KB until OOM
       at io.realm.internal.UncheckedRow.nativeGetString(UncheckedRow.java)
       at io.realm.internal.UncheckedRow.getString(UncheckedRow.java:157)
       at io.realm.br_com_inndev_onticket_bar_model_ItemCardapioRealmProxy.realmGet$imagemBase64(br_com_inndev_onticket_bar_model_ItemCardapioRealmProxy.java:505)
       at br.com.inndev.onticket.bar.model.ItemCardapio.getImagemBase64(ItemCardapio.java:109)
```

My ItemCardapio class.

```
public class ItemCardapio extends RealmObject implements Parcelable {

    @PrimaryKey
    private Long id;
    ...
    private String imagemBase64;

   public String getImagemBase64() {
        return imagemBase64; //This is the line 109
    }

    public void setImagemBase64(String imagemBase64) {
        this.imagemBase64 = imagemBase64;
    }
   ...
}
```

Version realm = io.realm:realm-gradle-plugin:5.0.0
Version Android: 5.1

**Comment by clementetb** [comment]
You got that error because the app runs out of java heap memory, you got 0.29MB free by the time you fetch the string (0.5MB).

You might be catching instances of these big strings that are filling the heap, or it might be that you have a memory leak. Try using CanaryLeak and/or the Android Studio memory profiling tools to spot any of those.

**Comment by rorbech** [comment]
Closing this as it most likely is related to memory usage patterns of the app itself and not related to Realm. Feel free to reopen if you gain more insight on the topic and and can provide at bit more information about the use case that points towards an issue related to Realm.
