### ISSUE TITLE
[Doc] executeTransactionAwait 

### ISSUE THREAD

**Issue by rlatapy-luna** [realm/realm-java#7209]
#### Goal
I'm facing some JNI errors like this one = `JNI DETECTED ERROR IN APPLICATION: JNI NewLocalRef called with pending exception kotlinx.coroutines.JobCancellationException: StandaloneCoroutine was cancelled'`
I suppose this is due to coroutine canceled while Realm is running a transaction. I just saw that there is an extension fun `executeTransactionAwait` to run transaction in a suspendable way. The doc say
```
 * Canceling the scope or job in which this function is executed does not cancel the transaction itself. If you want to ensure
 * your transaction is cooperative, you have to check for the value of [CoroutineScope.isActive] while running the transaction:
 *
 * ```
 * coroutineScope.launch {
 *   // insert 100 objects
 *   realm.executeTransactionAwait { transactionRealm ->
 *     for (i in 1..100) {
 *       // all good if active, otherwise do nothing
 *       if (isActive) {
 *         transactionRealm.insert(MyObject(i))
 *       }
 *     }
 *   }
 * }
 * ```
```
But how can we call `isActive()` (or `coroutineContext.isActive`) from the transaction block as the lambda is not itself `suspend` because of non suspend `executeTransaction` fun.

#### Version of Realm and tooling

Realm version(s): 10.0.1

**Comment by edualonso** [comment]
@rlatapy-luna that's right. The transaction itself will not be cancelled when the job or scope are cancelled because the `executeTransactionAwait` suspend function calls `executeTransaction` internally, which does not support cancellation. However, if the job or scope are cancelled and your transaction is executing a code block like the one from the documentation, then you can make your transaction block cooperative by checking the value of `isActive` (see https://kotlinlang.org/docs/reference/coroutines/cancellation-and-timeouts.html#making-computation-code-cancellable).

**Comment by rlatapy-luna** [comment]
Yes I did it thanks. My issue was in my helper function which now use `executeTransactionAwait` + `isActive` (see below). I was trying to use `yield()` to make the transaction cooperative.
Btw, does the code below looks safe to you? I use it for every writes (I disabled `allowWritesOnUiThread` & `allowQueriesOnUiThread`). Of course if the transaction block contains a loop or many modification I will handle it differently with more `isActive` checks. 
```kotlin
suspend fun executeRealmTransactionOnIO(block: CoroutineScope.(realmTr: Realm) -> Unit) {
    return withContext(Dispatchers.IO) {
        Realm.getDefaultInstance().use { realm ->
            realm.executeTransactionAwait((Dispatchers.IO)) { realmTr ->
                if (isActive) {
                    block(realmTr)
                }
            }
        }
    }
}
```
Regarding `executeTransactionAwait` impl,could I reuse the same realm instance as another one will be get?

**Comment by edualonso** [comment]
I think it is safe, yes. As long as you don't change context within `block` and use your Realm instance in this hypothetically new context everything should be fine - remember you still cannot pass Realm instances between different threads.
