### ISSUE TITLE
Lateinit fields need migration when upgrading kotlin gradle plugin to version 1.4.20

### ISSUE THREAD

**Issue by qmetzler-luna** [realm/realm-java#7226]
#### Goal
Ugrade kotlin-gradle-plugin from version 1.4.10 to 1.4.20

#### Actual Results
Realm migration is needed for lateinit fields as they become optional

#### Steps & Code to Reproduce
Have a realm object in your db with a lateinit
```
@RealmClass
open class MyObject : RealmModel {
    @PrimaryKey
    var id: Int = -1
    lateinit var test: String
}
```
Switch kotlin-gradle-plugin version from 1.4.10 to 1.4.20. Realm needs a migration as Property 'MyObject.test' has been made optional.
#### Version of Realm and tooling

Realm version(s): 10.1.1

Realm Sync feature enabled: No

Android Studio version: 4.1.1

Android Build Tools version: 30

Gradle version: 4.1.1

Which Android version and device(s): Any

**Comment by cmelchior** [comment]
If I remember correctly, this is a change in the underlying bytecode emitted by Kotlin. Until we can figure out a fix on our end, it should be possible to work around it by manually adding the `@Required` annotation.

**Comment by qmetzler-luna** [comment]
Thanks for the info! That's what we're doing in the meantime 😉

**Comment by edualonso** [comment]
Seems everyone was happy with the resolution :-)
Closing ticket.
