### ISSUE TITLE
Flaky test: SyncSessionTests.registerConnectionListener

### ISSUE THREAD

**Issue by edualonso** [realm/realm-java#7253]
Seen in https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-java/detail/PR-7252/1/tests

**Comment by nhachicha** [comment]
The CI job referenced is no longer available for investigation, please attach Jenkins logs and outputs to the issue to avoid losing the job.
btw is this still happening @edualonso ?

**Comment by edualonso** [comment]
Unfortunately I don't remember whether it was a crash or a failing test. It was a one-off unrelated to the work I was doing when I spotted it for sure and I haven't seen it happen again.

**Comment by nhachicha** [comment]
No worries, please feel free to reopen if this happens again 👍

**Comment by edualonso** [comment]
Seen again in https://ci.realm.io/blue/organizations/jenkins/realm%2Frealm-java/detail/PR-7273/2/pipeline
