### ISSUE TITLE
Memory kept growing in size in version 10.0.1?

### ISSUE THREAD

**Issue by NelzkieCoder** [realm/realm-java#7255]
I have been using realm for a while now. I am on the process on updating my app. I was using **4.3.1** and updated to 10. For some reason, my app suddenly lags a lot. I check the profiler and the memory kept increasing just for idling. I thought a leak but I am not getting any notification from leakcanary. Then until I found out that the only circumstance that my app will lag is if my activity is open with data on it. I downgraded to 4.3.1 and my memory is stable. Im confuse. Is this a bug?

Here is the SS for my memory profiler using 4.3.1
[Screen-Shot-2020-12-27-at-12-05-17-PM.png](https://postimg.cc/SXnrJ0Wm)

Here is the 10.0.1
[Screen-Shot-2020-12-27-at-12-10-55-PM.png](https://postimg.cc/grVKwH6L)

Any ideas why is that? Thanks

**Comment by clementetb** [comment]
We would need more information to be able to diagnose the cause. Do you reckon what piece of code is causing this behavior?

**Comment by NelzkieCoder** [comment]
> We would need more information to be able to diagnose the cause. Do you reckon what piece of code is causing this behavior?

Forgot to close this. Its all good. Turns out the issue was the coroutine doing something weird

**Comment by NelzkieCoder** [comment]
No related to realm at all. Seems like my code is doing something that is causing the usage of memory to spike.
