### ISSUE TITLE
Unrecoverable error

### ISSUE THREAD

**Issue by Lemac** [realm/realm-java#7257]
#### Goal
realm db file can access normally

#### Actual Results
Always generate these bug.

# main(1)

io.realm.exceptions.RealmError

Unrecoverable error. mmap() failed (size: 1184, offset: 0: Permission denied in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 106
1 io.realm.internal.OsSharedRealm.nativeGetSharedRealm(Native Method)
2 io.realm.internal.OsSharedRealm.<init>(OsSharedRealm.java:173)
3 io.realm.internal.OsSharedRealm.getInstance(OsSharedRealm.java:249)
4 io.realm.BaseRealm.<init>(BaseRealm.java:138)
5 io.realm.BaseRealm.<init>(BaseRealm.java:105)
6 io.realm.Realm.<init>(Realm.java:159)
7 io.realm.Realm.createInstance(Realm.java:495)
8 io.realm.RealmCache.createInstance(RealmCache.java:481)
9 io.realm.RealmCache.doCreateRealmOrGetFromCache(RealmCache.java:448)
10 io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:412)
11 io.realm.Realm.getDefaultInstance(Realm.java:403)
12 com.xx.db.xxRealmDBHelper.getVideoSettings(xxRealmDBHelper.java:1187)
13 com.xx.db.xxRealmDBHelper.getVideoStorageDir(xxRealmDBHelper.java:1117)
14 com.xx.video.xxCameraActivity.updateStorageState(xxCameraActivity.java:1615)
15 com.xx.video.xxCameraActivity.handleMessage(xxCameraActivity.java:2131)
16 com.xx.ui.uds.base.BaseHandler.handleMessage(BaseHandler.java:59)
17 android.os.Handler.dispatchMessage(Handler.java:111)
18 android.os.Looper.loop(Looper.java:194)
19 android.app.ActivityThread.main(ActivityThread.java:5643)
20 java.lang.reflect.Method.invoke(Native Method)
21 java.lang.reflect.Method.invoke(Method.java:372)
22 com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:982)
23 com.android.internal.os.ZygoteInit.main(ZygoteInit.java:777)

#### Version of Realm and tooling

Realm version(s): 10.0.1

Realm Sync feature enabled: No

Android Studio version: 4.1

Android Build Tools version: 3.5.3

Gradle version: gradle-5.5-all

Which Android version and device(s): 5.1

**Comment by clementetb** [comment]
Could you share more details on how you get this error? Is it possible that the Realm is in external storage and the user doesn't have write permissions for it?

**Comment by Lemac** [comment]
> Could you share more details on how you get this error? Is it possible that the Realm is in external storage and the user doesn't have write permissions for it?

No, db file's path is data/data/com.xx/files/xxx.realm
Sometimes this file is damaged, I don't know how to reproduce. This bug reproduced random.

**Comment by rorbech** [comment]
@Lemac You state that it _"always generates these bugs"_, but you also mention it is _"reproduced at random"_. Can you maybe elaborate a bit more on what you are overall doing in your app.
- What devices are this happening on?
- What is the realm configuration?
- How are the overall usage of realm in the app?

Ideally you could supply a minimal project exhibiting this

**Comment by bmunkholm** [comment]
@Lemac I'm closing this until you can provide us with more information. Thanks!.
