### ISSUE TITLE
Realm migration background/loader support

### ISSUE THREAD

**Issue by gaurav-likeminds** [realm/realm-java#7260]
If the app has a heavy db migration requirement, the app get stuck due to the write transactions on ui thread.

Is there any solution to do the db migration on background thread or to get ui context to show loader?

**Comment by cmelchior** [comment]
Yes, you can use `Realm.getInstanceAsync()`, alternatively there is a static method called `Realm.migrateRealm()` you can trigger manually before opening the Realm as well. 

If you want to support showing a loader, using `Realm.getInstanceAsync()` is probably the easiest as you can show the loader when calling the method and hide it again when the onSuccess callback is triggered.

**Comment by gaurav-likeminds** [comment]
Thank you. I will try the async one.

**Comment by rorbech** [comment]
Closing as advice seems address the question. Feel free to reopen if further input is needed.
