### ISSUE TITLE
Error: SERVICE_UNKNOWN(realm::app::ServiceError:-1): authentication via 'local-userpass' is unsupported during register?

### ISSUE THREAD

**Issue by NelzkieCoder** [realm/realm-java#7261]
Just following the tutorial on realm android here https://docs.mongodb.com/realm/tutorial/android-kotlin. I created the backend and imported the one provided. Tried creating a user but met with this error 

```
2021-01-12 10:07:47.873 20101-20101/com.mongodb.tasktracker E/LoginActivity: Could not register user.
2021-01-12 10:07:47.893 20101-20101/com.mongodb.tasktracker E/LoginActivity: Error: SERVICE_UNKNOWN(realm::app::ServiceError:-1): authentication via 'local-userpass' is unsupported
```

Found on some issue created here that it was a bug although has been fixed. I am using the version where the fix has been implemented but still having this issue. Any help? Thanks

**Comment by clementetb** [comment]
Have you enabled the email/password provider and deployed the changes?

**Comment by NelzkieCoder** [comment]
> Have you enabled the email/password provider and deployed the changes?

Yeah I did. I enabled them. Still having this issue.

**Comment by NelzkieCoder** [comment]
> Have you enabled the email/password provider and deployed the changes?

Ah. Right. I'd have to deploy. My Bad. Thank you. Will close this ticket
