### ISSUE TITLE
toFlow operator creates many instance

### ISSUE THREAD

**Issue by rlatapy-luna** [realm/realm-java#7294]
#### Goal
We recently migrate all of our homemade Realm-listener-to-flow extension to the built-in `toFLow` extension. It works well but... 

#### Actual Results
...when we want to delete the Realm db (logout usecase), some instance are still opened and we cannot delete the file. By monitoring the amount of instance during the app life, I saw that since we started using the `toFlow` extension the number of opened instance grows up during the whole life of the app, especially when we update some data. I suspect the freeze call to generate these instances https://github.com/realm/realm-java/blob/dfbf7977981e0eee9ca501568325f7400fbbf6f4/realm/realm-library/src/main/java/io/realm/internal/coroutines/InternalFlowFactory.kt#L539

#### Steps & Code to Reproduce

I did not try to reproduce it outside of the application, I could try if needed. But the steps would be
1. Observe a realm result using `toFLow` + `asLiveData` (androidx) from a viewmodel/fragment
2. Monitor realm instance
```kotlin
var instanceCount = 0
GlobalScope.launch {
    while (true) {
        val newCount = Realm.getGlobalInstanceCount(config)
        if (instanceCount != newCount) {
            instanceCount = newCount
            Timber.i("Realm instance count = $instanceCount")
        }
        delay(500)
    }
}
```
3. Update the data observed
4. Instance count grows up
5. Finish the activity then try to delete Realm, too many instances opened. Wait some times (3~5 seconds in my app), now instances are close and we can delete Realm.

#### Version of Realm and tooling

Realm version(s): 10.3.1

Realm Sync feature enabled:No

Android Studio version: 4.1.2

Android Build Tools version: 30.0.2

Gradle version: 6.8

Which Android version and device(s): 11 / Pixel 3XL

**Comment by cmelchior** [comment]
Yes, the frozen objects will keep the Realm open until you close the Flow. So it seems that the Flows are still running when you try to delete the Realm?

If you use the Android lifecycle scopes, that should close them automatically when you exit the Activity, but something like `GlobalScope` is a bit harder to control. In those cases, you would need to monitor the Job being returned and wait for it to complete.

Can you try to elaborate on exactly how you create Flows and where you delete the Realm?

**Comment by rlatapy-luna** [comment]
Usually we use the `asLivadata` ext fun and we observe it using the `viewLifecycleOwner`. But sometimes we use the `viewModelScope` to collect the flow, it's probably the reason why we have to wait some time before every instance are closed... I will try to always use the UI scope.
Anyway, would it be a great idea to specify a realm instance when using the `toFlow` extension? In our case we keep an instance on the UI thread and every queries are done using this instance (that's why we don't have the same issue with our toFlow extension).
Thanks for you answer

**Comment by rlatapy-luna** [comment]
I'm (re)doing some investigation on how we handle realm -> flow -> liveData in our app. 
- Firstly we had a simple problem with the `asLiveData` and `liveData { }` fun offered by androidx.lifecycle, by default these use a timeout (5sec) before closing the flow to handle configuration changes... That's why we had to wait some times before all instances are closed.
- I also found that we are "leaking" some realm instance when using the toFlow fun because we only use one global realm instance for querying data (on main thread) that is therefore never destroyed. So even when we close the flow, the instance created by freeze seems to remain.
For example we have a case where we use the `first()` final operator on a flow backed by `toFLow()`. Each time we call it, a new instance remains, whereas we don't need the realm object anymore.

**Comment by adriankremski** [comment]
> Usually we use the `asLivadata` ext fun and we observe it using the `viewLifecycleOwner`. But sometimes we use the `viewModelScope` to collect the flow, it's probably the reason why we have to wait some time before every instance are closed... I will try to always use the UI scope.
> Anyway, would it be a great idea to specify a realm instance when using the `toFlow` extension? In our case we keep an instance on the UI thread and every queries are done using this instance (that's why we don't have the same issue with our toFlow extension).
> Thanks for you answer

`SyncConfiguration.Builder` and `RealmConfiguration.Builder` have `flowFactory` method that can be used to provide your own logic for flow creation.  If you don't provide it then by default `InternalFlowFactory` is used.

**Comment by clementetb** [comment]
Closing as resolved.
