### ISSUE TITLE
JCenter to be dismissed - migrate to Maven Central

### ISSUE THREAD

**Issue by venator85** [realm/realm-java#7295]
Jcenter is scheduled to be dismissed on May 1st, 2021, and no more submissions will be accepted starting from February 28th.
Realm should be migrated to Maven Central as soon as possible.
https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/

**Comment by cmelchior** [comment]
Hi @venator85 

Yes, thank you for this issue. We are currently evaluating our options, but yes moving to Maven Central is probably the most likely outcome.

**Comment by moezbhatti** [comment]
Are you planning on moving over all versions of the library, or only more recent versions?

**Comment by cmelchior** [comment]
If possible we will be looking into moving all versions over.

**Comment by moezbhatti** [comment]
That's good to hear! I'm still on version 5.8 due to some issues with migrating to more recent versions

**Comment by ArneKoeckeritz** [comment]
Hi guys,
What's the current status ?
There are just 5 work days left before sunsetting !

**Comment by erikhuizinga** [comment]
@ArneKoeckeritz
The deadline is May 1st, not March 1st. So still a bit more (but not too much) time left!

**Comment by 01AlexandruTanase** [comment]
"To clarify, the JCenter repository will keep serving packages for 12 months until February 1st 2022. Only the JCenter REST API and UI will be sunsetted on May 1st 2021."

Does this mean that we will be able to continue using the latest realm version in our projects till 2022 but after May 1st no more library updates will be available through JCenter?

**Comment by cmelchior** [comment]
Our understanding is that from March 31st, we will no longer be able to push releases to JCenter, but all versions will still be available until 2022.

Note, we are in the process of migrating to MavenCentral. This will include all previous releases, but we are focusing on new releases first.

**Comment by saintjab** [comment]
@cmelchior any update on this? Its been quite here

**Comment by cmelchior** [comment]
Sorry, for not updating this. We have started doing releases to Maven Central https://search.maven.org/artifact/io.realm/realm-android-library

We originally had plans to migrate all releases as well, but since JCenter promised to keep these indefinitely this has not as high a priority as before.
