### ISSUE TITLE
Sort for Latin Supplement and Latin Extended-A not working as intended

### ISSUE THREAD

**Issue by 2ma** [realm/realm-java#7334]
#### Goal
I want to sort a list of strings that contain characters from Latin Supplement and Latin Extended-A character sets. (ä Ä ö Ö ő Ő)

#### Actual Results
The following characters are put at the and of the list: ä Ä ö Ö ő Ő

#### Steps & Code to Reproduce
Code for reproducing can be found here: https://github.com/2ma/RealmSorting
Insert any list that contains following characters:  ä Ä ö Ö ő Ő , retrieve the list sorted by the strings starting with the characters.

#### Version of Realm and tooling

Realm version(s): 10.3.1

Realm Sync feature enabled: No 

Android Studio version: 4.1.2

Android Build Tools version: 30.0.3

Gradle version: 6.5

Which Android version and device(s): Nexus 5x Android 8.1.0, Emulator running API 30 (Android 11.0)

**Comment by edualonso** [comment]
Hi @2ma. Unfortunately there is not a straightforward way to support this - see https://github.com/realm/realm-java/issues/1031 for reference. I'm sad to say, I do not think this will be added to the development pipeline any time soon.

**Comment by 2ma** [comment]
Hi @edualonso thank you for the answer! I'll look for a workaround then.
