### ISSUE TITLE
Unrecoverable error. No corresponding table

### ISSUE THREAD

**Issue by bobekos** [realm/realm-java#7348]
#### Goal
- no crashes

#### Actual Results
Stacktrace:
```
Fatal Exception: io.realm.exceptions.RealmError
Unrecoverable error. No corresponding table in /Users/cm/Realm/realm-java-release/realm/realm-library/src/main/cpp/io_realm_internal_OsSharedRealm.cpp line 107
io.realm.internal.OsSharedRealm.nativeGetSharedRealm (OsSharedRealm.java)
io.realm.internal.OsSharedRealm.<init> (OsSharedRealm.java:175)
io.realm.internal.OsSharedRealm.getInstance (OsSharedRealm.java:251)
io.realm.internal.OsSharedRealm.getInstance (OsSharedRealm.java:239)
io.realm.BaseRealm.compactRealm (BaseRealm.java:774)
io.realm.Realm.compactRealm (Realm.java:1808)
```

First of all, we cannot reproduce the error. It was reported by firebase crashlytics only from one user (from about 5k active installs). The crash happen when the "compactRealm" Method was called. In total there are 45 crashes from this user in a time span of less than 1 minute. You can say 1 crash per second.

Relationship with #6947

#### Steps & Code to Reproduce
No idea and unfortunately I can't give you a dumb of the database as it is not allowed to be given out. The only reference i got is the compact method of realm.

#### Version of Realm and tooling

Realm version(s): 7.0.5

Realm Sync feature enabled: No

Android Studio version: -

Android Build Tools version: sdk compile version 30

Gradle version: 4.1.1

Which Android version and device(s): Samsung Galaxy S8+ Android 7

**Comment by cmelchior** [comment]
Hi @bobekos 

Yes, this was a bug that has been fixed. I would recommend upgrading to latest version which is 10.3.1. Note that the version major bump doesn't have any impact on the local database. It was mostly to reflect the fact that our Sync support changed significantly.

**Comment by bobekos** [comment]
@cmelchior 
Alright, we will update the version. I will close the issue for now and if necessary create a new one if the error occurs again. Thanks for the response.
