### ISSUE TITLE
shouldCompact block not called

### ISSUE THREAD

**Issue by grangej** [realm/realm-java#7351]
#### Goal
We are trying to make sure the realm is compacted on launch as well as firing some analytic events so we know how often this is happening on our app. 

#### Actual Results
We implemented the code as best as per examples found online but we do not see analytics events nor is the block called when debugging the app.

#### Steps & Code to Reproduce
Add the following code in App.kt

```
    private fun initRealm() {

        Realm.init(this)

        val objRealmConfig = RealmConfiguration.Builder()
            .compactOnLaunch { totalBytes, usedBytes ->
                val minSize = (100 * 1024 * 1024).toLong()

                val shouldCompact = totalBytes > minSize && usedBytes / totalBytes.toDouble() < 0.5

                if (shouldCompact) {
                    analyticsManager.sendEvent(RealmInitEvent(totalBytes, "Realm Database Compacted"))
                } else {
                    analyticsManager.sendEvent(RealmInitEvent(totalBytes, "Realm Database Not Compacted"))
                }

                return@compactOnLaunch shouldCompact
            }
            .build()

        Realm.setDefaultConfiguration(objRealmConfig)
    }
```

#### Version of Realm and tooling
Realm version(s): Latest

Realm Sync feature enabled: No

Android Studio version: 4.0 / 4.2

Android Build Tools version: ?

Gradle version: ?

Which Android version and device(s): Pixel 5

**Comment by cmelchior** [comment]
We have tests verifying that compactOnLaunch should work here: https://github.com/realm/realm-java/blob/master/realm/realm-library/src/androidTest/java/io/realm/RealmTests.java#L1212 and here: https://github.com/realm/realm-java/blob/master/realm/realm-library/src/androidTestObjectServer/kotlin/io/realm/mongodb/sync/SyncedRealmTests.kt#L230

So I wonder if something else is wrong in your setup. Do you have a sample project that can reproduce the behaviour or some other way we can debug it?

**Comment by bmunkholm** [comment]
@grangej Closing this as we haven't heard back from you. Let us know if this is still an issue and you can provide us with more info on how to reproduce. Thanks!
