### ISSUE TITLE
Server errors not being fully propogated to Mobile SDK logs

### ISSUE THREAD

**Issue by AniketSK** [realm/realm-java#7363]
#### Goal
Propagating server mobile errors to the mobile sdk.

#### Actual Results
The error on mobile. This is the complete and only log posted.

`Ending session with error: failed to validate upload changesets: SET instruction had incorrect partition value for key "event" { expectedPartition: {default}, foundPartition: 6051a679142a60ce4ad5c7e8 } (ProtocolErrorCode=212)`

However the server error contains the following information. This can be seen in Realm Logs.
`BadChangeset Error
Mar 17 16:43:20+05:30
1ms
Sync
Write
--
6051e443e1ba6508f986aa99
6051e4456a76d037ac34bdc8
Error:
failed to validate upload changesets: SET instruction had incorrect partition value for key "event" { expectedPartition: {6051e443e1ba6508f986aa99}, foundPartition: 6051e443e1ba6508f986aa99q } (ProtocolErrorCode=212)
Partition:
6051e443e1ba6508f986aa99
Write Summary:
{
  "TileClaim": {
    "inserted": [
      "6051e44e32fd4a0791e477f8"
    ]
  }
}
Remote IP Address:
1.23.212.6
SDK:
android v10.2.0
Platform Version:
11`

#### Steps & Code to Reproduce
Open a synced realm with a certain partition value. Insert a value into it that has a different partition value.

#### Version of Realm and tooling
Realm 10.2.0 on Android

Realm version(s): ?
10.2.0

Realm Sync feature enabled: Yes

Android Studio version: ?
Android Studio Arctic Fox Canary 10

Android Build Tools version: ?
buildToolsVersion "30.0.3"

Gradle version: ?
        classpath 'com.android.tools.build:gradle:7.0.0-alpha10'
        classpath "org.jetbrains.kotlin:kotlin-gradle-plugin:1.4.31"

Which Android version and device(s): ?
Nexus 5 Emulator API 30

https://github.com/mongodb-developer/EmojiGarden/tree/main/app

**Comment by cmelchior** [comment]
I have been looking into this.

It turns out that we are propagating server messages correctly, except for one case: Client Reset. There we override the message. This is a behavior from the old Realm Server implementation and we should fix it for when used with MongoDB Realm.
