### ISSUE TITLE
Can you provide Chinese documents ?

### ISSUE THREAD

**Issue by BlackC0** [realm/realm-java#7366]
Have provided.
But now is not.
It may not be the latest version.
But need to have.
It helps me a lot.
Can you provide ?

**Comment by BlackC0** [comment]
Please and thanks.

**Comment by cmelchior** [comment]
Hi @BlackC0 

We currently do not have the resources to maintain Chinese versions of our docs. Sorry for the inconvenience.

**Comment by BlackC0** [comment]
Can you just reopen ex-chinese-docs？
