### ISSUE TITLE
Build was configured to prefer settings repositories over project repositories but repository 'MavenRepo' was added by plugin 'realm-android'

### ISSUE THREAD

**Issue by NelzkieCoder** [realm/realm-java#7374]
Getting this error any fix for this? 
`Build was configured to prefer settings repositories over project repositories but repository 'MavenRepo' was added by plugin 'realm-android'`

Thanks

**Comment by AniketSK** [comment]
@NelzkieCoder it could be worked around by allowing project repos. This would require changing the **settings.gradle** in the Android project.

Replace the line:
`repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)`
with
`repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)`

That's a [gradle setting](https://docs.gradle.org/current/userguide/declaring_repositories.html#sub:centralized-repository-declaration) which allows this to work.

Out of curiosity were you using the Android Studio Canary?

**Comment by mohit-sharma-87** [comment]
@NelzkieCoder : You can try moving to the latest version i.e. "10.4.0", which should resolve your issue as we have migrated from JCenter to mavenCentral.

I am also suspecting as @AniketSK  mentioned, changes in setting.gradle file which has been introduced in latest Android Studio Canary.

**Comment by AniketSK** [comment]
@mohit-sharma-87 I was on Realm 10.4.0 and the (2020.3.1 canary 12) Android Canary and this is still an issue.

**Comment by cmelchior** [comment]
This a duplicate of https://github.com/realm/realm-java/issues/7365#issuecomment-816672104, So I'll merge it into that one.

Unfortunately fixing it would require breaking change, but there is a work-around described in the comment I linked to.

**Comment by evan766** [comment]
> PREFER_SETTINGS
thx, solve my problam

**Comment by NueeKip** [comment]
@AniketSK It worked like a charm, Thank you 🤣🤣.

**Comment by mohit-sharma-87** [comment]
@eugenegrib : I don't think so you need this anymore as the root issue as been fixed. 

https://github.com/realm/realm-java/issues/7365

**Comment by sharsad** [comment]
In settings.gradle just comment out the whole block

dependencyResolutionManagement {
    repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
    repositories {`enter code here`
        google()
        mavenCentral()
        jcenter() // Warning: this repository is going to shut down soon
    }
}

**Comment by sharsad** [comment]
In settings.gradle you can add the repositories you want to add to the project

dependencyResolutionManagement {
   repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)
   repositories {
      google()
      mavenCentral()
      jcenter()
      maven { url "https://maven.xyz.com" }
    }
}

**Comment by attamunim** [comment]
i deleted the lines
repositories{
maven()
}
from gradle
and it worked

**Comment by traiyani** [comment]
remove

**Comment by pedrofsn** [comment]
Thanks @sharsad!

**Comment by SurajBahadur** [comment]
> @NelzkieCoder it could be worked around by allowing project repos. This would require changing the **settings.gradle** in the Android project.
> 
> Replace the line: `repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)` with `repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)`
> 
> That's a [gradle setting](https://docs.gradle.org/current/userguide/declaring_repositories.html#sub:centralized-repository-declaration) which allows this to work.
> 
> Out of curiosity were you using the Android Studio Canary?

IT WORKED

**Comment by Hasims2001** [comment]
Thank you so much

**Comment by tihiydo** [comment]
> In settings.gradle you can add the repositories you want to add to the project
> 
> dependencyResolutionManagement { repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS) repositories { google() mavenCentral() jcenter() maven { url "https://maven.xyz.com" } } }

Only this works, idk why :)

**Comment by AlexanderCop1983** [comment]
это не работает(

**Comment by Ohior** [comment]
> 
If `repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)` generates error why was it been used?
`

**Comment by ozZ-Y** [comment]
Thank you, bug fixed
@AniketSK  ♥

**Comment by ezzeldin01010** [comment]
> @NelzkieCoder it could be worked around by allowing project repos. This would require changing the **settings.gradle** in the Android project.
> 
> Replace the line: `repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)` with `repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)`
> 
> That's a [gradle setting](https://docs.gradle.org/current/userguide/declaring_repositories.html#sub:centralized-repository-declaration) which allows this to work.
> 
> Out of curiosity were you using the Android Studio Canary?

You saved me, thank you

**Comment by Sarat-1997** [comment]
> @NelzkieCoder it could be worked around by allowing project repos. This would require changing the **settings.gradle** in the Android project.
> 
> Replace the line: `repositoriesMode.set(RepositoriesMode.FAIL_ON_PROJECT_REPOS)` with `repositoriesMode.set(RepositoriesMode.PREFER_SETTINGS)`
> 
> That's a [gradle setting](https://docs.gradle.org/current/userguide/declaring_repositories.html#sub:centralized-repository-declaration) which allows this to work.
> 
> Out of curiosity were you using the Android Studio Canary?

Thanks a lot brother. It works!!!

**Comment by neha01mittal** [comment]
Did the trick! Ty!
