### ISSUE TITLE
Native crush when I trying executeTransaction() to write changes on few parallel async tasks

### ISSUE THREAD

**Issue by IgoBobrov** [realm/realm-java#7400]
E/REALM: /tmp/realm-java/realm/realm-library/src/main/cpp/realm-core/src/realm/alloc_slab.cpp:539: [realm-core-10.3.3] Assertion failed: prev->first + prev->second <= ref with (ref, size, prev->first, prev->second, get_file_path_for_assertions()) =  [1522896, 7816, 1476456, 54256, "/data/user/0/ru.mdh.mtsamarket2memory.android.debug_prod/files/upload.realm"]
    <backtrace not supported on this platform>!!! IMPORTANT: Please send this log and info about Realm SDK version and other relevant reproduction info to help@realm.io.
A/libc: Fatal signal 6 (SIGABRT), code -6 (SI_TKILL) in tid 16088 (pool-20-thread-), pid 15903 (roid.debug_prod)

reproduced on Xiaomi Redmi 6, Android 9. 
There is no this bug on 7.0.8v

**Comment by cmelchior** [comment]
Hi @IgoBobrov Sorry for the late reply.  Are you saying you can reproduce this? Does this mean you have the Realm file in question? If so, can you send it to christianmelchior@mongodb.com so we can take a look at it
