### ISSUE TITLE
RealmObject addChangeListener

### ISSUE THREAD

**Issue by DOSEEARE** [realm/realm-java#7404]
#### Version of Realm and tooling

Realm version(s): ? 4.3.4

Realm Sync feature enabled: Yes/No no

Android Studio version: ? 4.1.2

Android Build Tools version: ? 

Gradle version: ? 

Which Android version and device(s): ? Redmi 9 

Hello! 

I have ParentEntity and i want to use addChangeListener on this table. 

ParentEntity is:

open class ParentEntity(
    @PrimaryKey
    var name: String? = null,
    var digit: Int? = null,
    var child: ChildEntity? = null
) : RealmObject()
_________________________________________
ChildEntity is:

open class ChildEntity(
    @PrimaryKey var name: String? = null,
    var digit: Int? = null
) : RealmObject()

____________________________________________

im finding parent entity and using addChangeListener like this. 

    Repository.findParent().addChangeListener(RealmObjectChangeListener<ParentEntity> { t, changeSet ->
                Log.d("TEST_REALM", "Listener triggered")
            })

ChangeListener is working while i'm changing some value in ParentEntity. But is not workштп whшду i'm changing some value in ChildEntity, Help me plz.

**Comment by cmelchior** [comment]
Hi @DOSEEARE 

Sorry for the late reply. This is the current intended behavior. Changelisteneners on an object only trigger on changes to direct properties, not referenced objects. The enhancement is currently tracked at.

Change notifications on RealmResults due trigger if child objects are updated however (and yes, I agree that inconsistency is rather confusing). We are tracking it here https://github.com/realm/realm-java/issues/4786, but for the time being a work-around could be writing the code to use a RealmResults instead.
