### ISSUE TITLE
Make it work with Fragment.setRetainInstance(true)?

### ISSUE THREAD

**Issue by yolapop** [realm/realm-java#741]
Hi, I'm wondering, since the constructor of Realm is using `Context` we have to instantiate it again every time the device rotates. Is it possible to bind Realm with the `Fragment` itself, to avoid re-instantiation and re-query?

Thanks.

**Comment by cmelchior** [comment]
Hi @yolapop 
The context is just used to call Context.getFilesDir(), so you can use the ApplicationContext instead which should survive rotation changes.

**Comment by yolapop** [comment]
Oh great, thanks very much.
