### ISSUE TITLE
Out of memory size

### ISSUE THREAD

**Issue by dakexuan** [realm/realm-java#7439]
Unrecoverable error. mmap() failed: Out of memory size: 1342177280 offset: 0 in /Users/cm/Realm/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 92

#00 pc 00049b58 /system/lib/libc.so (tgkill+12) [armeabi-v7a]
--
2 #01 pc 000472d3 /system/lib/libc.so (pthread_kill+34) [armeabi-v7a]
3 #02 pc 0001d575 /system/lib/libc.so (raise+10) [armeabi-v7a]
4 #03 pc 000190c1 /system/lib/libc.so (__libc_android_abort+34) [armeabi-v7a]
5 #04 pc 00017124 /system/lib/libc.so (abort+4) [armeabi-v7a]
6 #05 pc 0000c54d /system/lib/libcutils.so (__android_log_assert+112) [armeabi-v7a]

Maybe it is 1.2G、1.7G、1.8G of realm file，Anyway，When it stores more data，It will happen，How can I fix it？
The larger the realm, the more RAM will be used?

**Comment by cmelchior** [comment]
Hi @dakexuan I will recommend reading https://docs.mongodb.com/realm-legacy/docs/java/latest/index.html#faq-large-realm-file-size
