### ISSUE TITLE
executeTransactionAsync onSuccess or onError is not invoked

### ISSUE THREAD

**Issue by Pro-55** [realm/realm-java#7448]
Goal:
1. InsertOrUpdate data in the table.
2. onSuccess -> Push same object to the server
3. onError -> notify user to retry

Actual Results:
The app gets stuck on progress bar.
On adding logs and toasts we found out that neither of the call back methods are being triggered

Realm version(s): 10.3.1

Realm Sync feature enabled: No

Android Studio version: 4.3.1

Android Build Tools version: 30.0.2

Gradle version: 4.1.2

Which Android version and device(s): 
1. Realme devices => Android 10

**Comment by dhanashripatkar** [comment]
Yes, I am also facing the same issue.
Please have a look at below code

public static void addAll(final String companyId, final List<OrderEntry> orderEntries) {
        final Realm realm = RealmUtils.getRealm(companyId);
        realm.executeTransactionAsync(new Realm.Transaction() {
            @Override
            public void execute(Realm realm) {
                realm.insertOrUpdate(orderEntries);
            }
        }, new Realm.Transaction.OnSuccess() {
            @Override
            public void onSuccess() {
                Ln.d("Transaction Success");
            }
        }, new Realm.Transaction.OnError() {
            @Override
            public void onError(Throwable error) {
                Ln.d("Transaction Failed");
            }
        });

        RealmUtils.close(realm, false);
    }

And it neither prints success nor error message.


Realm version(s): 10.3.1
Realm Sync feature enabled: No
Android Studio version: 4.3.1
Android Build Tools version: 30.0.2
Gradle version: 4.1.2
Which Android version and device(s):
  1. Realme devices => Android 10

**Comment by cmelchior** [comment]
Hi @Pro-55 Can you provide a fully working example showing that it doesn't work? From the description you have right now, it is hard to tell what might be wrong.

**Comment by Pro-55** [comment]
Here is the code snippet for inserting multiple objects into the db:

`
    public void addAllAsync(final String id, 
                            final List<Object> objects,
                            @NotNull final Callback callback) {
        final Realm realm = RealmUtils.getRealm(id);
        realm.executeTransactionAsync(realm1 -> realm1.insertOrUpdate(objects),
                () -> {
                    callback.onSuccess();
                    RealmUtils.close(realm);
                }, error -> {
                    Analytics.logException(error);
                    callback.onFailure();
                    RealmUtils.close(realm);
                });
    }
`

And here is the realm config I am using:

`
    public RealmConfiguration getRealmConfig(final Context context,
                                                                          final String id) {
        final byte[] key = KeystoreUtils.getEncryptionKey(context, id);
        if (key != null) {
            return new RealmConfiguration.Builder()
                    .name(id)
                    .schemaVersion(143)
                    .migration(new Migration())
                    .encryptionKey(key)
                    .allowWritesOnUiThread(true)
                    .build();
        } else {
            return null;
        }
    }
`

**Comment by Pro-55** [comment]
Is there any way we can call insert or update directly inside a coroutine?

**Comment by Pro-55** [comment]
I used `executeTransaction` inside a coroutine scope yet it still froze my UI.

Here is the code for that:

`
    fun createOrderEntry(id: String, objects: List<Object>): LiveData<Resource<Boolean>> =
        resourceFlow<Boolean> {
            val realm = RealmUtils.getRealm(id)
            realm?.executeTransaction { it.insertOrUpdate(objects) }
            emit(Resource.success(true))
            RealmUtils.close(realm)
        }
            .asLiveData()
`

**Comment by Pro-55** [comment]
Is there a suspend function for the same in Kotlin counterpart of the library?

**Comment by clementetb** [comment]
Currently we don't provide a suspend function for executing transactions. 

The UI gets blocked on the execute transaction as it the resourceFlow is executed on the UI thread. 

If the order entry objects are unmanaged you might try writing your own suspend function, something along the line:

```
suspend fun insertOrUpdate(objects: List<Object>) {
        return suspendCoroutine { continuation ->
            realm.executeTransactionAsync({ realm ->
                realm.insertOrUpdate(objects)
            }, {
                continuation.resumeWith(Result.success(Unit))
            }, { exception ->
                continuation.resumeWith(Result.failure(exception))
            })
        }
    }
```
