### ISSUE TITLE
Android pda close realm db connection make app crash

### ISSUE THREAD

**Issue by simikb** [realm/realm-java#7452]
Hai , 
My realm query returns null and make my app crash for some devices
I am using realm for 6 month in my sunmi android app, in my last update large no of data is inserting in db for offline storage in a timer thread.

but recently some of the pda device crashes due to db is returning zero rows even db contain data
All query is returning null, if close app and restart app , app working fine then

relam db is in my sd card

**Comment by cmelchior** [comment]
Hi @simikb 

It is hard to provide guidance without the actual code. Can you reproduce the problem in a small unit test or sample project we can look at?
