### ISSUE TITLE
realm table columns repeating when updating

### ISSUE THREAD

**Issue by simikb** [realm/realm-java#7453]
Db updating

result is android app crash

table one 
categoryId
int?
categoryCode
string?
categoryName
string?
activeStatus
bool?
categoryId_4
int?
categoryCode_5
string?
categoryName_6
string?
activeStatus_7
bool?

colunms repeating after update

Realm version(s): ?io.realm:realm-gradle-plugin:4.1.1

Android Studio version: 4.1.3

Android Build Tools version: com.android.tools.build:gradle:4.0.1

Gradle version: ?4.0.1

Which Android version and device(s): ? sunmi pda device

**Comment by simikb** [comment]
![image](https://user-images.githubusercontent.com/15665783/116804742-eb5d1480-ab3e-11eb-8525-3310a6b720e0.png)

**Comment by simikb** [comment]
4,5,6 data is automaticaly repeating, and my realm object dont have category_4 ,categoryCode_6 etc cloumns

**Comment by cmelchior** [comment]
Hi @simikb 

It is a bit hard to provide guidance with the information you have given. We would need to see some example code or a project demonstrating the behaviour in order to debug it.
