### ISSUE TITLE
Can not change the timeout when calling a function

### ISSUE THREAD

**Issue by Trailqueen** [realm/realm-java#7455]
#### Goal
Change the timeout for calling a function

#### Actual Results
When calling 'app.getFunctions(user).callFunctionAsync()' I get a timeout after 10 seconds. The function however takes longer than 10 seconds, but definetly less than 90 seconds (which is the limit for functions).

I tried to change the timeout with:
AppConfiguration.Builder(APP_ID)
 .requestTimeout(90000, TimeUnit.MILLISECONDS)
 .build()

However this does not have any effect on the 10 second timeout.  According to issue #6878  there is no other way to change the timeout. I would be nice if the timeout could be separatly set for a function.

After setting the timeout in the builder to 90 seconds I get 'app.configuration.requestTimeoutMs = 90000000'. Which would be micro and not milliseconds. But I don't think that this is relatd to my error..

#### Steps & Code to Reproduce
Calling a function that takes longer than 10 seconds to execute

#### Version of Realm and tooling

Realm version(s): 10.4.0

Realm Sync feature enabled: Yes

Android Studio version: 4.1.3

Android Build Tools version: 30.0.3

Gradle version: 4.1.3

**Comment by cmelchior** [comment]
Hi @Trailqueen 

Sorry for the late response. Yes, there is a bug in the timeout conversion, but that is just making it longer. I'm looking into it now.

**Comment by cmelchior** [comment]
A fix has been merged and is part of next release (10.6.1).
