### ISSUE TITLE
Default Codec Registry is not exposed via MongoClient

### ISSUE THREAD

**Issue by nathan-contino-mongo** [realm/realm-java#7458]
#### Goal
Most custom codecs for the MongoDB Java Driver use the default codec registry to support encoding/decoding built-in Java types (int, bool, String, etc). The default codec registry is accessible in the Driver via `MongoClient.getDefaultCodecRegistry()`. Even enabling something as simple as encoding/decoding of POJOs (which uses another built-in codec provider) is dependent upon this registry to encode/decode built-in Java types. (see the [MongoDB Java Driver docs](https://mongodb.github.io/mongo-java-driver/3.5/driver/getting-started/quick-start-pojo/) for more information).

#### Actual Results
The default codec registry is not accessible via the `MongoClient` class, and the only workaround to get access to the default codec registry seems to be indirectly accessing the default codec registry through a collection with default codecs, shown [here in the Realm docs](https://docs.mongodb.com/realm/sdk/android/examples/mongodb-remote-access/#instantiate-a-mongodb-collection-handle).

#### Steps & Code to Reproduce
Reproducible in any Realm application.

#### Version of Realm and tooling

Realm version(s): All versions of Realm since 10.0.0 are effected.

Realm Sync feature enabled: Issue exists for Sync and non-Sync applications.

Android Studio version: N/A

Android Build Tools version: N/A

Gradle version: N/A

Which Android version and device(s): N/A

**Comment by cmelchior** [comment]
Sorry for the confusion. These API's already exist here:

https://docs.mongodb.com/realm-sdks/java/latest/io/realm/mongodb/AppConfiguration.Builder.html
https://docs.mongodb.com/realm-sdks/java/latest/io/realm/mongodb/AppConfiguration.html#getDefaultCodecRegistry--
