### ISSUE TITLE
Automatically order input when using between()

### ISSUE THREAD

**Issue by AlanHassen** [realm/realm-java#747]
Hi folks,
I am trying to use realm for a project, but I'm not able to use the between
query with decimal numbers.

For example:
RealmQuery<ObjectRealm> query = realm.where(ObjectRealm.class);
query.between("someData", -53.85610, -53.89252);
RealmResults<PostRealm> result = query.findAll();

The realm object has a double column "someData" with the value -53.874312. Using between should return an object, but its just returning an empty list.

Is this a bug, or am I doing something wrong?

**Comment by cmelchior** [comment]
Hi @AlanHassen 
If you reverse the order of arguments, it will work, ie. 
```
RealmQuery query = realm.where(ObjectRealm.class);
query.between("someData", -53.89252, -53.85610);
RealmResults result = query.findAll();
```

It is described in the JavaDoc, but is not immediately apparent from the parameter names that the lowest number should be first. We should probably consider making the order irrelevant to avoid confusion like this when working with negative numbers.

**Comment by bmunkholm** [comment]
To make the order of the parameters irrelevant, you would have to complicate the query and make it slower. I'm not sure that's a good idea. But we should make it more clear in the parameter names and warn in the docs.

**Comment by cmelchior** [comment]
After some internal discussion on this we have decided that the current implementation is better as it has a strict mathematical definition ( a <= x <= b). It is also the same behaviour as SQLite. Changing behaviour depending on input will be problematic if you are not controlling the input parameters directly.

For cases where you always want the the results between ```a``` and ```b``` no matter the ordering, you can do the following:

```realm.where(Foo.class).between("bar", Math.min(a,b), Math.max(a,b)).findAll()```
