### ISSUE TITLE
Support RealmObject referencing a RealmObject from a different compilation module

### ISSUE THREAD

**Issue by jd565** [realm/realm-java#7474]
#### Describe your problem or use case
When modularising an app by feature, there may be a common structure that is used by many features, and a Realm representation of this structure may want to be shared by sitting in a common module.

For instance, we may have a profile feature, and an album feature, both of which want to save media information, so you would have:
- Profile Module (depends on core)
- Album Module (depends on core)
- Core module

And Profile Module has

```
open class RealmProfile(var media: RealmMedia? = null): RealmObject()
```

Album Module

```
open class RealmAlbum(var media: RealmMedia? = null): RealmObject()
```

Core Module

```
open class RealmMedia(var name: String? = null): RealmObject()
```

Right now, this will throw an exception in the annotation processor because RealmMedia cannot be found. This can be solved by marking the RealmMedia object as embedded, but there may be some situations where these two things may want to reference the same object.

#### Describe the solution you'd like
From my brief look at the issue in the processor, it needs to find the referenced class to see whether the class has a primary key to change insertion behaviour. It seems like it should be possible to add information to a RealmClass annotation to tell the processor this information (as the processor can determine whether the referenced class is embedded or not from the annotation), something like:

```
@RealmClass(hasPrimaryKey = RealmHasPrimaryKey.TRUE)
open class RealmMedia(var name: String? = null): RealmObject()
```

where the RealmHasPrimaryKey enum is like:
```
public enum RealmHasPrimaryKey {
    TRUE, FALSE, UNDEFINED
}
```

This way if the hasPrimaryKey field is set to either TRUE or FALSE the processor can use that field, and if it is undefined it can fall back to the default of looking up the class in the parsed collection.

#### Additional context
There is a git repo that hits the existing issue here: https://github.com/jd565/realm-modularised/tree/main

**Comment by cmelchior** [comment]
Hi @jd565 Sorry for the late reply. This looks like a regression as I'm pretty sure this has worked in the past. I'll look into it.

**Comment by petersnoopy** [comment]
Please fix this issue as soon as possible. I can't upgrade from 10.3.1.

**Comment by rorbech** [comment]
We should be able to look up the information from the external module through reflection as shown in #7525
