### ISSUE TITLE
Can change the data type of a field in an object?

### ISSUE THREAD

**Issue by huycung** [realm/realm-java#7475]
I want to change the data type of a field from string to RealmList in an object when the received data changes. For example: version 1 receives data as String, version 2 receives data as RealmList? Can this be done?

**Comment by cmelchior** [comment]
Hi @huycung 

That depends on exactly what you mean by "receiving data", if you mean data from a REST API and you need to modify the data before inserting into Realm. Then you could use a JSON mapper like Moshi or GSON which has support for adapters that can do this sort of transformation. 

But we would need more details to provider better guidance.
