### ISSUE TITLE
Failed to parse, or apply received changeset: ERROR: ArrayInsert: Invalid prior_size (list size = 4, prior_size = 0)

### ISSUE THREAD

**Issue by kunalgharate** [realm/realm-java#7480]
Not able to sync with realm app 

Failed to parse, or apply received changeset: ERROR: ArrayInsert: Invalid prior_size (list size = 4, prior_size = 0)

there is no log to rectify the issue

**Comment by kunalgharate** [comment]
@cmelchior  we got this log only no schema here is defined in the error log or no more information is there to understand

**Comment by nirinchev** [comment]
Are you using embedded objects that contain lists of values? We've identified an issue related to those and I wonder if it's the same problem or a brand new one.

**Comment by kunalgharate** [comment]
![image](https://user-images.githubusercontent.com/20945934/121320170-890be680-c92a-11eb-823f-bc32b040bc5a.png)

we have multiple level embed objects within that we have realm list

**Comment by nirinchev** [comment]
Then I believe it's the same issue as https://github.com/realm/realm-core/pull/4741.

**Comment by kunalgharate** [comment]
@nirinchev  what is the solution for this?

**Comment by nirinchev** [comment]
There is no solution - the linked PR needs to be merged and released.

**Comment by kunalgharate** [comment]
@nirinchev  how we can handle this for now because I am not getting any schema error where I can make changes directly

**Comment by kunalgharate** [comment]
The issue with the embedded realm list.

**Comment by cmelchior** [comment]
10.5.1 was released with a fix for this.
