### ISSUE TITLE
Is cross Realm possible?

### ISSUE THREAD

**Issue by yolapop** [realm/realm-java#749]
So I have one default Realm and then for some reason I need multiple Realm files for each `Fragment` inside a `ViewPager` which is tied to the default Realm.

    objectFromDefaultRealm = defaultRealm.query().find();

    realm = Realm.getInstance("fragmentFile" + viewpagerPosition);
    RealmObject fragmentObject = realm.createObject();
    fragmentObject.setProperty(objectFromDefaultRealm);
    realm.commit();

That's a brief code that explains what I mean. And it turns out the property from default realm is not saved. I wonder if this behavior is correct? If cross realm is not supported I think there should be a `clone` method to copy the `RealmObject`?

Thanks.

**Comment by kneth** [comment]
Copying an object to another realm is not supported. We are currently working on standalone objects (#728) at the moment.

Creating an standalone object, and then add it to two different Realms will be possible. However, you will then have two independent realm objects and changes to one of them is not reflected on the other object in the other realm.

**Comment by yolapop** [comment]
Thank you!
