### ISSUE TITLE
RealmCache broken logic: waitForInitialRemoteData doesn't trigger correctly

### ISSUE THREAD

**Issue by nhachicha** [realm/realm-java#7517]
@hennasingh https://github.com/hennasingh/Restaurants created an app  using Sync and stumbled upon a weird behaviour of combining `waitForInitialRemoteData` with `asynOpen`, the callback `onSuccess` bring a Realm that is empty, as if the  `waitForInitialRemoteData` didn't happen.

After digging in the code I discovered that the caching mechanism used in [doCreateRealmOrGetFromCache](https://github.com/realm/realm-java/blob/master/realm/realm-library/src/main/java/io/realm/RealmCache.java#L421-L437) is broken:
```Java
        ReferenceCounter referenceCounter = getRefCounter(realmClass, version);
        boolean firstRealmInstanceInProcess = (getTotalGlobalRefCount() == 0);

        if (firstRealmInstanceInProcess) {
            // ...
            boolean realmFileIsBeingCreated = !configuration.realmExists();
            if (configuration.isSyncConfiguration() && realmFileIsBeingCreated) {
                // ...
                ObjectServerFacade.getSyncFacadeIfPossible().downloadInitialRemoteChanges(configuration);
            }
        
```
We need `realmFileIsBeingCreated` to be `true` to `downloadInitialRemoteChanges`, which means no one created the Realm file already. This is not guarantee when using sync because before calling [doCreateRealmOrGetFromCache](https://github.com/realm/realm-java/blob/master/realm/realm-library/src/main/java/io/realm/RealmCache.java#L420) we call  [doCreateRealmOrGetFromCacheAsync](https://github.com/realm/realm-java/blob/master/realm/realm-library/src/main/java/io/realm/RealmCache.java#L398) which invokes`createNativeSyncSession` that call `app.getSync().getOrCreateSession(syncConfig)` this will create a the Realm file, making `realmFileIsBeingCreated` `false` even on the first ever run.

**Comment by cmelchior** [comment]
@mohit-sharma-87 is also running into this in his example app.

**Comment by cmelchior** [comment]
It looks like it is the combination with `Realm.getInstanceAsync()` that is broken.... Using `Realm.getInstance()` works as expected with `waitForInitialRemoteData()`
