### ISSUE TITLE
Realm sum from inner relationship fields

### ISSUE THREAD

**Issue by mirkovicmiroslav** [realm/realm-java#7520]
#### Goal

Get sum from inner relationship fields

#### Actual Results

` java.lang.IllegalArgumentException: Field does not exist: trailParts.track.trackDefinitions.lengthFromPrevPoint
        at io.realm.RealmObjectSchema.getAndCheckFieldColumnKey(RealmObjectSchema.java:652)
        at io.realm.RealmQuery.sum(RealmQuery.java:2208)`

#### Steps & Code to Reproduce

Model
```java
class Trail {
    RealmList<TrailPart> trailParts;
}
class TrailPart {
    Track track;
}
class Track {
     RealmList<TrackDefinition> trackDefinitions;  
}
class TrackDefinition {
      double lengthFromPrevPoint;
      Date timeStamp;
}
```
1) e.g. this is working fine. I'm getting right results.
```java
 RealmResults<Trail> trails = realm.where(Trail.class)
                    .greaterThanOrEqualTo("trailParts.track.trackDefinitions.timeStamp", CommonUtils.getOneDayEarlier())
                    .findAll();
```
2) After this, I want to `get length of Trail` via `sum of lengthFromPrevPoint` from TrackDefinition and this is how I'm trying to get (but I'm getting the mentioned exception)
```java
trail.getTrailParts()
                   .sum("track.trackDefinitions.lengthFromPrevPoint")
                   .doubleValue();
```
and this approach is not working, I'm getting always that `Field does not exist` but actually, field exist in TrackDefinition model but seems like `sum expecting just fields from querying Model`...

I also tried this approach but I'm getting the same exception
```java
 realm.where(Trail.class)
                     .equalTo("id", trail.getId())
                     .and()
                     .sum("trailParts.track.trackDefinitions.lengthFromPrevPoint").doubleValue();
```
Reason why I'm trying through this approach is that I don't want to loop through TrailParts ..
Below example is working fine but I need to loop through all TrailParts from each Trail, for me that is unnecessary if above example would work...

```java
 for (TrailParts trailPart : trail.getTrailParts()) {
        trailDefinitionsLength +=trailPart.getTrack().getTrackDefinitions().sum("lengthFromPrevPoint").doubleValue();
  }
```
#### Version of Realm and tooling
`io.realm:realm-gradle-plugin:10.6.0`

Realm version(s): ?

Realm Sync feature enabled: Yes/No 
No

Android Studio version: ?
`4.2.2`

Android Build Tools version: ?
`29.0.3`

Gradle version: ?
`6.5`
`com.android.tools.build:gradle:4.1.2`

Which Android version and device(s): ?
`Nokia 6.1`
`Android 10`

**Comment by bmunkholm** [comment]
@mirkovicmiroslav Did you get this resolved or are you still having issues with this?

**Comment by bmunkholm** [comment]
Closing due to lacking response.

**Comment by mirkovicmiroslav** [comment]
Sorry for not responding on you comment.
No, I didn't resolve an issue (also didn't find better way then loop..).
