### ISSUE TITLE
Upgrade to Java 11

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#7533]
With Android Studio Arctic Fox, the default Java version shipped is now Java 11.

In order to avoid too many project-specific environment requirements, we should attempt to support this version as a minimum.

Currently, we depend on Java 8 due to https://github.com/realm/realm-java/blob/master/realm/realm-annotations-processor/build.gradle#L15.

This is required due to this extension function https://github.com/realm/realm-java/blob/master/realm/realm-annotations-processor/src/main/java/io/realm/processor/Utils.kt#L649.

Unfortunately, it seems that these API's moved in Java 9 to the `jdk.compiler` module https://docs.oracle.com/javase/9/docs/api/com/sun/tools/javac/package-summary.html

I haven't tried to use Java 9 modules yet, so it is a bit unclear if we can actually use these and still be compatible with Java 8. 

Forcing consumers to be on Java 9 or 11 seems a rather big breaking change. An alternative could be to call into all of these API's using reflection. That might be acceptable since the code path is already expected to be "slow".

This upgrade is further made difficult by the fact that it doesn't seem we have any tests that actually exercise the code path :(

**Comment by rorbech** [comment]
With https://github.com/realm/realm-java/pull/7535/files#diff-f902446382e6f861eea8777ac5a93b95476520e4bcb64d7c63a8e61889c242e3R17 we are still able to use the old API until abandoning JDK 8 completely and migrating to `jdk.compiler`.

There are however some subtleties in different APIs, so ended up differentiating lookup of class symbols between JDK 8 and 9 by reflection as we would not be able to process projects using JDK8.
