### ISSUE TITLE
Invalid predicate error on try to sort by field with name "sort".

### ISSUE THREAD

**Issue by TemMax** [realm/realm-java#7545]
#### Goal
Want to receive a sorted list from db.

#### Actual Results
App is crashed with this log:
Caused by: java.lang.IllegalArgumentException: Illegal Argument: Invalid predicate: 'TRUEPREDICATE SORT(sort ASC)': syntax error, unexpected sort in /tmp/realm-java/realm/realm-library/src/main/cpp/io_realm_internal_TableQuery.cpp line 527

#### Steps & Code to Reproduce
For reproduce you can try to create a class that extents RealmObject, add field (var sort: Int = 0). Then try to fetch this objects with query with .sort() function call.

#### Version of Realm and tooling

Realm version(s): 10.7.1

Realm Sync feature enabled: No

Android Studio version: 2020.3.1

Android Build Tools version: 30.0.3

Gradle version: 7.0.2

Which Android version and device(s): 11

**Comment by bmunkholm** [comment]
@ironage is "sort" considered a reserved keyword that users can't use a field?

**Comment by bmunkholm** [comment]
@TemMax For now I think you should consider "sort" a field name we don't support. I'm not sure if we will in the future. I'll see what @ironage has to say about that.

**Comment by TemMax** [comment]
Sure. I already wrote migration for my DB. But it's strange that "sort" field name was supported in old versions (4-6) and not supported in current versions :)
I faced with this bug due migration my old app with very old version of Realm on the last one.

**Comment by bmunkholm** [comment]
Yeah it seems like an oversight when we replaced our query engine. I honestly can't recall if we mentioned that in the release notes and was too lazy to check it ;-).
