### ISSUE TITLE
Missing Javadoc

### ISSUE THREAD

**Issue by CoolKangaroo2022** [realm/realm-java#7546]
Hello! I find in your [CONTRIBUTING.md](https://github.com/realm/realm-java/blob/master/CONTRIBUTING.md#javadoc) that 
> All public classes and methods must have Javadoc describing their purpose.

However, I still witness some public classes without Javadocs, e.g.,
* realm/realm-library/src/androidTest/java/io/realm/instrumentation/ActivityLifecycle.java
* realm/realm-library/src/androidTest/java/io/realm/entities/CatOwner.java
* realm/realm-library/src/syncTestUtils/java/io/realm/objectserver/utils/UserFactory.java

I also find likely missing Javadoc for public methods in the following files:
* realm/realm-library/src/objectServer/java/io/realm/internal/objectstore/OsAppCredentials.java
* realm/realm-library/src/main/java/io/realm/internal/OsResults.java
......

Would you like to add Javadoc for these methods or classes, or they are just not that important?
If there is anything I can help with?

**Comment by bmunkholm** [comment]
Hey @CoolKangaroo2022 - thanks for the feedback and offer for help!
We only really require documentation for the public API methods. All the ones you listed there are for test or internal classes / methods. I'll close this for now, but if you find public facing methods that are missing docs, please do let us know by creating another issue.
Thanks!
