### ISSUE TITLE
Invalid download.src url in realm-jni/build.gradle:downloadCore task when enabling encryption=true with v0.76.0

### ISSUE THREAD

**Issue by idelgado** [realm/realm-java#756]
Enabling encryption=true with a fresh checkout of realm-java(v0.76.0) causes the downloadCore task to fail.

Setting encryption=true in local.properties modifies the project.coreVersion variable at realm-jni/build.gradle:31. This causes the download.src url to be invalid in the downloadCore task.

**Comment by kneth** [comment]
Currently we cannot enable encryption in our releases. We hope to do so in the very near future.

**Comment by idelgado** [comment]
How can i build the encryption feature? I tried building from master as well, both fail the downloadCore task. I guess it's not clear to me whether your plan was to serve up a core-0.86.X-encryption.tar.gz or that my error is in fact a gradle bug and it should be core-0.86.tar.gz even when trying to build with encryption.

Also, do you have a timeline for when this feature will become part of the release? We are really interested in using it :+1:

**Comment by idelgado** [comment]
I'm happy to help/contribute in any way possible too!

**Comment by bmunkholm** [comment]
Support for Encryption will be released in the coming week.

**Comment by cmelchior** [comment]
@idelgado We have released 0.78.0 with support for encryption. Let us know if you have any problems with it :)
