### ISSUE TITLE
large number of Native crash/OutOfMemory exception,  after upgrading Realm from 6.1.0 to 10.7.1 

### ISSUE THREAD

**Issue by Raynor999** [realm/realm-java#7560]
### How frequently does the bug occur?

Sometimes

### Description

A large number of crashes have occurred ,after upgrading Realm from 6.1.0 to 10.7.1 。

The latest features are used
1. Embedded     （Database Migration ✔️）
2. coroutine /toFlow()    , FrozenObjects

### Stacktrace & log output

```shell
Download
OS Version: Android 10 (LYA-AL00L 10.1.0.163(C00E159R1P8))
Report Version: 104

Exception Type: Unknown (SIGABRT)

Application Specific Information:
Abort

Thread 0 Crashed:
0   libc.so                         0xe7a9e502          abort
1   libc.so                         0xe7a9e79f          __assert2
2   librealm-jni.so                 0xb23f248f          <unknown> + 2990482575
3   librealm-jni.so                 0xb23f25f5          <unknown> + 2990482933
4   librealm-jni.so                 0xb23f2521          <unknown> + 2990482721
5   librealm-jni.so                 0xb23f20fd          <unknown> + 2990481661
6   librealm-jni.so                 0xb24b9405          <unknown> + 2991297541
7   libc.so                         0xe7ae6547          <unknown> + 3886966087
8   libc.so                         0xe7a9f9f7          <unknown> + 3886676471

Address Range
0x0000c380e000 – 0x0000c3bb8000
Debug ID
0c824531-aa69-db1c-caeb-989c42d19f7c
Debug File
—
Code ID
3145820c69aa1cdbcaeb989c42d19f7ce525323a
Code File
/data/app/com.sundayfun.daycam-YfzaiTFSV9BZZ_zwbd7VZA==/lib/arm/librealm-jni.so
Architecture
—
Processing
Symbolication
```

### Can you reproduce the bug?

Yes, sometimes

### Version

10.6.1

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

Android 10

### Build environment

Android Studio version:  Android Studio Arctic Fox | 2020.3.1 Patch 2
Android Build Tools version:  30.0.2
Gradle version:   gradle-6.5.1
android_gradle_plugin : 4.1.0

**Comment by cmelchior** [comment]
Hi @Raynor999 

Do you have the complete stacktrace?

Also, when you are reproducing, are there any specific steps you are taking. From the information in this report, it is hard to tell exactly what could be wrong.

**Comment by bmunkholm** [comment]
@Raynor999 Unless we can get more information, there is nothing we can do and the issue will be closed.
