### ISSUE TITLE
Perfomance loss between versions 5.15.1 and 10.8.0 (x5)

### ISSUE THREAD

**Issue by mederic** [realm/realm-java#7570]
### How frequently does the bug occur?

All the time

### Description

We recently upgraded realm in our project from 5.15.1 to 10.8.0 and found out that our app performance decreases drastically : some actions that was almost immediate take now several seconds. Note that we are using realm intensively in our app, which would explain the amount of query done in the attached sample.

### Stacktrace & log output

```
v5.15.1
------
For 25 queries: 73ms (average)
For 50 queries: 136ms (average)
For 100 queries: 241ms (average)
For 200 queries: 506ms (average)
For 400 queries: 1009ms (average)
For 600 queries: 1677ms (average)
For 800 queries: 1813ms (average)
For 1000 queries: 2227ms (average)

v10.8.0
-------
For 25 queries: 271ms (average)
For 50 queries: 529ms (average)
For 100 queries: 1057ms (average)
For 200 queries: 2085ms (average)
For 400 queries: 4329ms (average)
For 600 queries: 6193ms (average)
For 800 queries: 8185ms (average)
For 1000 queries: 10492ms (average)
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

We managed to reproduce that in a sample project, that log some durations: (https://github.com/mederic/RealmPerformanceIssue)

### Version

10.8.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

Android 24

### Build environment

Android Studio version: 4.0.1
Android Build Tools version: 4.0.1
Gradle version: 6.1.1

**Comment by cmelchior** [comment]
Hi @mederic Thank you very much for the project. I can see the same behavior. We are looking into it.

How data is stored changed between version 5 and 10, so it isn't surprising that there are changes, but this order of magnitude could point to a problem somewhere.

**Comment by cmelchior** [comment]
Playing around with it a little bit. 

- Adding Indexes to both fields being queried actually makes the whole query slower on both versions. 
- Removing the index on the indexed fields makes the query quite a lot faster on both versions.

**Comment by jedelbo** [comment]
@mederic I can understand that you have put an index on the property you are using in the query. Can you inform how many objects you have of the relevant type and the distribution of values for the property - or in other words: how many values do you have in total and how many unique values do you have?

**Comment by mederic** [comment]
Hi @jedelbo . As an example, we have a class which can contains a 60-80k rows with two indexed fields. First one may have between 1 and 5 distinct values. The other can have 30-40k distincts values. And of course, it's pretty current that we query over those two fields at the same time :).

Does that help?
