### ISSUE TITLE
Realm android (java) i use 1.8 gb memory, and app crash out of memory what can i do? i close all realms and try to compact. but nothing didn't help. when i calling get instance crash i need data from this device. 

### ISSUE THREAD

**Issue by TonnyWhite** [realm/realm-java#7577]

**Comment by bmunkholm** [comment]
@TonnyWhite I hope Christians answer helped you, so I'll close this. If you experience bugs in the future please ensure to fill out the issue template. If you have questions and need some help, we also have a [forum](https://www.mongodb.com/community/forums/c/realm/realm-sdks/58) where the community helps out. Thanks!
