### ISSUE TITLE
Build failed of realm-java and realm-core

### ISSUE THREAD

**Issue by aguludunu** [realm/realm-java#7596]
### How frequently does the bug occur?

All the time

### Description

I build realm-java and realm-core, and it freezed at "installTransformer"

<===========--> 86% EXECUTING [23m 14s]
> :installBuildTransformer
> :installTransformer

And, although sometimes installTransformer passed(I don't know why), there are another errors such as some files can not be found or some functions is wrong.

I think the version of realm-java and realm-core is not match. But the version is written on readme, and I tried some other versions, also failed.

Can you supply a right version of realm-java and realm-core that I can build successfully?

Errors like this:
/realm-java-10.8.1/realm/realm-library/src/main/cpp/io_realm_internal_OsResults.cpp:277:75: error: unknown type name 'ConstTableView'; did you mean 'ConstTableRef'?

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

1. Download the tools and versions.

2. Modify realm-core version in dependencies.list
REALM_CORE=x.x.x

3. Move realm-core to realm-java/realm/realm-library/src/main/cpp/

4. Set environment variables.
export JAVA_HOME=/xx/xx/jdk1.8.0_311
export NDK_HOME=/xx/xx/android-sdk/ndk/22.0.7026061
export ANDROID_HOME=/xx/xx/android-sdk

5.  ./gradlew assemble

### Version

API 29

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

Linux Ubuntu 18.04

### Build environment

OS                     Ubuntu18.04
GCC                   7.5.0
JDK		          8
Android SDK     API 29
Android NDK 	  22.0.7026061
CMake 	          3.18.4
Ninja	          1.8.2
Gradle 	          6.8.3

realm-java         10.8.1
realm-core         v11.5.1/v11.5.2/v11.6.0

**Comment by cmelchior** [comment]
Yes, this is probably caused by a bug in Gradle. We have also seen this. Gradle 7.2 does seem to work correctly. Alternatively, we used this work-around: https://github.com/realm/realm-java/pull/7535/files#diff-e6ffa5dc854b843b3ee3c3c28f8eae2f436c2df2b1ca299cca1fa5982e390cf8L239

**Comment by aguludunu** [comment]
hi cmelchior, thanks very much!

I use the newest code on master and put realm-core 11.6.0 into realm-java(if i don't do this, realm-core is empty), and get an error that **"could not find RealmConfig.cmake"**
Could you help me how to fix it?

My env:
OS Ubuntu21.10
GCC 11.2.0
JDK 11.0.13
Android SDK API 30
Android NDK 23.1.7779620
CMake 3.21.4
Ninja 1.10.2
Gradle 7.2
realm-java :newest on master ,Wed Nov 24 2021
realm-core 11.6.0

the error is below:

**> Task :realm:realm-library:configureCMakeRelWithDebInfo[arm64-v8a]-2 FAILED**
C/C++: objectServerRelease|arm64-v8a :Build type: RelWithDebInfo
C/C++: objectServerRelease|arm64-v8a :JNI Header directory: /root/davidwang/realm-java/realm/realm-library/src/main/cpp/../../../build/intermediates/javac/objectServerRelease/jni_include
C/C++: objectServerRelease|arm64-v8a :CMake Error at CMakeLists.txt:134 (include):
C/C++: objectServerRelease|arm64-v8a :  include could not find requested file:
C/C++: objectServerRelease|arm64-v8a :    /root/davidwang/realm-java/realm/realm-library/.cxx/RelWithDebInfo/3f6e4c4w/arm64-v8a/realm-RelWithDebInfo-v11.6.0-Android-arm64-v8a-devel/lib/cmake/Realm/RealmConfig.cmake

> Task :installRealm FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':realm:realm-library:configureCMakeRelWithDebInfo[arm64-v8a]-2'.
> [CXX1405] error when building with cmake using /root/davidwang/realm-java/realm/realm-library/src/main/cpp/CMakeLists.txt: Build command failed.
  Error while executing process /usr/local/bin/cmake with arguments {-H/root/davidwang/realm-java/realm/realm-library/src/main/cpp -DCMAKE_SYSTEM_NAME=Android -DCMAKE_EXPORT_COMPILE_COMMANDS=ON -DCMAKE_SYSTEM_VERSION=16 -DANDROID_PLATFORM=android-16 -DANDROID_ABI=arm64-v8a -DCMAKE_ANDROID_ARCH_ABI=arm64-v8a -DANDROID_NDK=/root/davidwang/android-sdk/ndk/23.1.7779620 -DCMAKE_ANDROID_NDK=/root/davidwang/android-sdk/ndk/23.1.7779620 -DCMAKE_TOOLCHAIN_FILE=/root/davidwang/android-sdk/ndk/23.1.7779620/build/cmake/android.toolchain.cmake -DCMAKE_MAKE_PROGRAM=/usr/local/bin/ninja -DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/root/davidwang/realm-java/realm/realm-library/build/intermediates/cxx/RelWithDebInfo/3f6e4c4w/obj/arm64-v8a -DCMAKE_RUNTIME_OUTPUT_DIRECTORY=/root/davidwang/realm-java/realm/realm-library/build/intermediates/cxx/RelWithDebInfo/3f6e4c4w/obj/arm64-v8a -DCMAKE_BUILD_TYPE=RelWithDebInfo -B/root/davidwang/realm-java/realm/realm-library/.cxx/RelWithDebInfo/3f6e4c4w/arm64-v8a -GNinja -DREALM_JAVA_BUILD_CORE_FROM_SOURCE=false -DCMAKE_INTERPROCEDURAL_OPTIMIZATION=true -DREALM_FLAVOR=objectServer}
  -- android-16 is not supported for arm64-v8a. Using minimum supported LP64 version 21.
  -- Android: Targeting API '21' with architecture 'arm64', ABI 'arm64-v8a', and processor 'aarch64'
  -- Android: Selected unified Clang toolchain
  -- The C compiler identification is Clang 12.0.8
  -- The CXX compiler identification is Clang 12.0.8
  -- Detecting C compiler ABI info
  -- Detecting C compiler ABI info - done
  -- Check for working C compiler: /root/davidwang/android-sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64/bin/clang - skipped
  -- Detecting C compile features
  -- Detecting C compile features - done
  -- Detecting CXX compiler ABI info
  -- Detecting CXX compiler ABI info - done
  -- Check for working CXX compiler: /root/davidwang/android-sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++ - skipped
  -- Detecting CXX compile features
  -- Detecting CXX compile features - done
  -- Found Java: /root/davidwang/jdk-11.0.13/bin/java (found version "11.0.13") found components: Development 
  -- Using prebuilt Realm Core.
  PATH=/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/usr/games:/usr/local/games:/snap/bin
  LESSCLOSE=/usr/bin/lesspipe %s %s
  XDG_DATA_DIRS=/usr/local/share:/usr/share:/var/lib/snapd/desktop
  JAVA_HOME=/root/davidwang/jdk-11.0.13
  MOTD_SHOWN=pam
  TERM=xterm
  LANG=en_US.UTF-8
  XDG_SESSION_TYPE=tty
  XDG_SESSION_ID=20
  ANDROID_HOME=/root/davidwang/android-sdk
  NDK_HOME=/root/davidwang/android-sdk/ndk/23.1.7779620
  LOGNAME=root
  PWD=/root/davidwang/realm-java
  _=./gradlew
  XDG_SESSION_CLASS=user
  LESSOPEN=| /usr/bin/lesspipe %s
  SHELL=/bin/bash
  SSH_CLIENT=61.161.201.201 61041 22
  SSH_TTY=/dev/pts/3
  OLDPWD=/root
  USER=root
  SSH_CONNECTION=61.161.201.201 61041 45.32.211.36 22
  XDG_RUNTIME_DIR=/run/user/0
  LS_COLORS=rs=0:di=01;34:ln=01;36:mh=00:pi=40;33:so=01;35:do=01;35:bd=40;33;01:cd=40;33;01:or=40;31;01:mi=00:su=37;41:sg=30;43:ca=30;41:tw=30;42:ow=34;42:st=37;44:ex=01;32:*.tar=01;31:*.tgz=01;31:*.arc=01;31:*.arj=01;31:*.taz=01;31:*.lha=01;31:*.lz4=01;31:*.lzh=01;31:*.lzma=01;31:*.tlz=01;31:*.txz=01;31:*.tzo=01;31:*.t7z=01;31:*.zip=01;31:*.z=01;31:*.dz=01;31:*.gz=01;31:*.lrz=01;31:*.lz=01;31:*.lzo=01;31:*.xz=01;31:*.zst=01;31:*.tzst=01;31:*.bz2=01;31:*.bz=01;31:*.tbz=01;31:*.tbz2=01;31:*.tz=01;31:*.deb=01;31:*.rpm=01;31:*.jar=01;31:*.war=01;31:*.ear=01;31:*.sar=01;31:*.rar=01;31:*.alz=01;31:*.ace=01;31:*.zoo=01;31:*.cpio=01;31:*.7z=01;31:*.rz=01;31:*.cab=01;31:*.wim=01;31:*.swm=01;31:*.dwm=01;31:*.esd=01;31:*.jpg=01;35:*.jpeg=01;35:*.mjpg=01;35:*.mjpeg=01;35:*.gif=01;35:*.bmp=01;35:*.pbm=01;35:*.pgm=01;35:*.ppm=01;35:*.tga=01;35:*.xbm=01;35:*.xpm=01;35:*.tif=01;35:*.tiff=01;35:*.png=01;35:*.svg=01;35:*.svgz=01;35:*.mng=01;35:*.pcx=01;35:*.mov=01;35:*.mpg=01;35:*.mpeg=01;35:*.m2v=01;35:*.mkv=01;35:*.webm=01;35:*.webp=01;35:*.ogm=01;35:*.mp4=01;35:*.m4v=01;35:*.mp4v=01;35:*.vob=01;35:*.qt=01;35:*.nuv=01;35:*.wmv=01;35:*.asf=01;35:*.rm=01;35:*.rmvb=01;35:*.flc=01;35:*.avi=01;35:*.fli=01;35:*.flv=01;35:*.gl=01;35:*.dl=01;35:*.xcf=01;35:*.xwd=01;35:*.yuv=01;35:*.cgm=01;35:*.emf=01;35:*.ogv=01;35:*.ogx=01;35:*.aac=00;36:*.au=00;36:*.flac=00;36:*.m4a=00;36:*.mid=00;36:*.midi=00;36:*.mka=00;36:*.mp3=00;36:*.mpc=00;36:*.ogg=00;36:*.ra=00;36:*.wav=00;36:*.oga=00;36:*.opus=00;36:*.spx=00;36:*.xspf=00;36:
  SHLVL=1
  HOME=/root
  CC=/root/davidwang/android-sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64/bin/clang
  CXX=/root/davidwang/android-sdk/ndk/23.1.7779620/toolchains/llvm/prebuilt/linux-x86_64/bin/clang++
  LC_ALL=
  LC_MESSAGES=
  -- Downloading realm-RelWithDebInfo-v11.6.0-Android-arm64-v8a-devel...
  -- Uncompressing realm-core...
  -- Configuring incomplete, errors occurred!
  See also "/root/davidwang/realm-java/realm/realm-library/.cxx/RelWithDebInfo/3f6e4c4w/arm64-v8a/CMakeFiles/CMakeOutput.log".
  
  Build type: RelWithDebInfo
  JNI Header directory: /root/davidwang/realm-java/realm/realm-library/src/main/cpp/../../../build/intermediates/javac/objectServerRelease/jni_include
  CMake Error at CMakeLists.txt:134 (include):
    include could not find requested file:
  
      **/root/davidwang/realm-java/realm/realm-library/.cxx/RelWithDebInfo/3f6e4c4w/arm64-v8a/realm-RelWithDebInfo-v11.6.0-Android-arm64-v8a-devel/lib/cmake/Realm/RealmConfig.cmake**
  
  


* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output. Run with --scan to get full insights.

* Get more help at https://help.gradle.org

Deprecated Gradle features were used in this build, making it incompatible with Gradle 8.0.

You can use '--warning-mode all' to show the individual deprecation warnings and determine if they come from your own scripts or plugins.

See https://docs.gradle.org/7.2/userguide/command_line_interface.html#sec:command_line_warnings

Execution optimizations have been disabled for 2 invalid unit(s) of work during this build to ensure correctness.
Please consult deprecation warnings for more details.

BUILD FAILED in 22m 18s
4 actionable tasks: 4 executed

**Comment by cmelchior** [comment]
Realm Core is a git submodule, so not 100% what you mean when you say "put realm-core 11.6.0 into realm-java".

But if you check out the whole repo with `git clone https://github.com/realm/realm-java.git --recursive` or call `git submodule update --init --recursive` from the root, it should fetch the right version of Realm Core and put it in the correct location.

**Comment by aguludunu** [comment]
first I just git clone https://github.com/realm/realm-java.git and there is no  realm-core, so I download realm-core and put it into "realm/realm-library/src/main/cpp/realm-core"

then i use git clone https://github.com/realm/realm-java.git --recursive and realm-core is downloaded automaticlly.

but in both cases i get the error below:

CMake Error at CMakeLists.txt:134 (include):
    include could not find requested file:
  
      /root/zhut/1/realm-java/realm/realm-library/.cxx/RelWithDebInfo/4wo4v3x4/arm64-v8a/realm-RelWithDebInfo-v11.6.0-Android-arm64-v8a-devel/lib/cmake/Realm/RealmConfig.cmake

**Comment by clementetb** [comment]
Does the `/root/zhut/1/realm-java/realm/realm-library/.cxx/RelWithDebInfo/4wo4v3x4/arm64-v8a/realm-RelWithDebInfo-v11.6.0-Android-arm64-v8a-devel/lib/cmake/Realm/` directory exist?

Have you tried clearing the gradle caches, and removing any local maven packages?

**Comment by cmelchior** [comment]
Hi @aguludunu Did the above fix your problem?
