### ISSUE TITLE
Frozen realm object returns null for realm object field

### ISSUE THREAD

**Issue by ayecarranda** [realm/realm-java#7597]
### How frequently does the bug occur?

All the time

### Description

I have a Realm object `Conversation` that has a nullable realm object field `user`. I have a changesetFlow subscribed to all Conversations in the application. The issue is that every time I access `it.collection` from within the changesetFlow, and iterate over those Conversation objects, the `user` field is null on the frozen object when it shouldn't be. I know the user field is non-null from inspecting the local realm file with Realm Studio. 

I've traced the issue to the Proxy class, where i can see that `isNullLink(columnInfo.userColKey)` returns true, and thus I get a null result. I was unable to find documentation of the behavior of realm object and realm list fields in frozen objects - is this expected? If so, what is the workaround - is it to query an 'thawed' version of the object each time?

```
Conversation
     var user: User? // User is another realm object
```

```
where<Conversation>.findAllAsync().toChangesetFlow().onEach {
     it.collection.forEach { frozenConversation ->
           // frozenConversation.user is null
     }
}.launchIn(scope)
```

```
// class ConversationRealmProxy.java (proxy for realm object, Conversation
    @Override
    public User realmGet$user() {
        proxyState.getRealm$realm().checkIfValid();
        if (proxyState.getRow$realm().isNullLink(columnInfo.userColKey)) {
            return null;
        }
        return proxyState.getRealm$realm().get(User.class, proxyState.getRow$realm().getLink(columnInfo.userColKey), false, Collections.<String>emptyList());
    }
```

### Can you reproduce the bug?

Yes, always

### Version

10.8.1

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

Android 12

### Build environment

Android Studio version: Arctic Fox 2020.3.1 Patch 3
Android Build Tools version: 31
Gradle version: 7.0.2

**Comment by clementetb** [comment]
If there is a user associated to that conversation it should not be null, even if frozen. 

How are you checking the nullity? Is it through the debugger, or are you asserting it?

**Comment by cmelchior** [comment]
Hi @ayecarranda Is this still a problem?
