### ISSUE TITLE
Unable to create SyncConfiguration with UUID-typed partitionValue

### ISSUE THREAD

**Issue by leonidovia** [realm/realm-java#7598]
### How frequently does the bug occur?

All the time

### Description

In my Sync I use the partitionKey of type UUID, but I cannot create the appropriate SyncConfiguration because SyncConfiguration.Builder(User user, @Nullable UUID partitionValue)) is missing.
realm-cocoa has it and my Sync works.

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

Try to create SyncConfiguration with UUID-typed partitionValue.

### Version

10.8.1

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

Android 11

### Build environment

Android Studio version: ...
Android Build Tools version: ...
Gradle version: ...

**Comment by cmelchior** [comment]
Hi @leonidovia Sorry about that. We somehow missed adding support for this. A fix has been merged that is available in `10.9.0-SNAPSHOT`. A proper release should be available in the next few days.
