### ISSUE TITLE
Add a check to see if RealmObject exists in Realm or in memory

### ISSUE THREAD

**Issue by gautamjain** [realm/realm-java#760]
With the introduction of stand alone objects, is there anyway to check if an instance of `RealmObject` is persisted in Realm or just in memory?

**Comment by cmelchior** [comment]
With the 0.77.0 release we added a RealmObject.isValid() method that returns false if the object is either a standalone object, has been deleted in the Realm or the Realm has been closed.

You can read more about it here: http://realm.io/docs/java/0.77.0/api/io/realm/RealmObject.html#isValid()

If that is enough, it would be interesting to hear more about your specific use case?

**Comment by gautamjain** [comment]
That would work fine!  I had seen that method earlier, but it wasn't clear in the documentation that it would return false if it was called on a standalone object.  Thanks!

**Comment by cmelchior** [comment]
Good to hear. And yes, it seems we forgot to document the behaviour for stand alone objects. Will fix asap :)

**Comment by AnixPasBesoin** [comment]
Thanx for posting this issue! Solved my problem ^^

**Comment by AnixPasBesoin** [comment]
I would like to ask for some clarifications please.
What would isValid() return for a realmObject which has been updated in another thread?
Will realm update the realmObject I hold in my current thread (non updating thread)? Or consider it as invalid?
This hard for me to test, and the documentation seems to not provide a clear answer to that.

**Comment by Zhuinden** [comment]
@AnixPasBesoin a non-autoupdating thread will retain the version of the Realm that it was opened with until the Realm is closed, a transaction is committed, or (somehow) refreshed.

Deleted objects come `isValid() == false`.

`realm.beginTransaction()` bumps the version of the Realm instance, for example. Which is why it is recommended to query inside the transaction, not outside of it.

**Comment by AnixPasBesoin** [comment]
@Zhuinden May I know how do I check a thread if it's auto-updating or not?
May you provide some links?

**Comment by Zhuinden** [comment]
@AnixPasBesoin well typically the UI thread is auto-updating, and the others are not; unless you specifically open a `HandlerThread` and set it to `setAutoRefresh(true)`
