### ISSUE TITLE
Inconsistent order in annotation processing

### ISSUE THREAD

**Issue by jprinet** [realm/realm-java#7615]
### How frequently does the bug occur?

Sometimes

### Description

Annotation processing is not a fully consistent process given the usage of an unsorted `Set` to [retrieve annotated elements](https://docs.oracle.com/javase/7/docs/api/javax/annotation/processing/RoundEnvironment.html#getElementsAnnotatedWith(java.lang.Class))

This randomly leads to some differences (usually using different JVM/OS) in the generated source code as `RealmProxyMediatorGenerator` is using this Set as a source of information:
https://github.com/realm/realm-java/blob/e9a855f24292a43334ba3f30c61533313aba9ee1/realm/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyMediatorGenerator.kt#L40

This is fine syntax wise but prevent to benefit from Gradle remote cache as outputs are changing over time.
Ordering the collection would solve this issue.

### Stacktrace & log output

```shell
n/a
```

### Can you reproduce the bug?

Yes, sometimes

### Reproduction Steps

Having different JVM / OS can help to generate different orderings.

### Version

10.9.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

MacOs and Linux

### Build environment

n/a

**Comment by cmelchior** [comment]
Great catch, yes, that should be easy to fix. Thanks 👍

**Comment by jprinet** [comment]
I initiated a PR
https://github.com/realm/realm-java/pull/7616

unit testing it is not trivial though
