### ISSUE TITLE
Batch or bulk updates

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#762]
Feature request following this discussion: https://groups.google.com/forum/#!topic/realm-java/6NeywfWmCA4

Basically it allows setting a property on many objects in one operation just like this SQL:

```
UPDATE Foo SET isDeleted = 1 WHERE name = "123"
```

One option could be

```
RealmResults<Foo> foos = realm.where(Foo.class).equalsTo("name", "123");
realm.beginTransaction();
foos.updateAllObjects("isDeleted", 1);
realm.commitTransaction();
```

**Comment by kneth** [comment]
This should definitely be implemented mostly in C++ for better performance.

**Comment by bmunkholm** [comment]
The priority will be low as there are clear and easy workarounds for this. This is mainly a performance optimization.

**Comment by finnschiermer** [comment]
When it comes to code that makes changes in the database, the cost of the
commit that
will follow it will most likely dwarf all other contributions, so it might
not make a significant difference
in performance.

**Comment by bmunkholm** [comment]
That all depends on the number of objects you want to update and if you persist to disk or possible in-memory. But commit to disk and updating few objects, you are right.

**Comment by finnschiermer** [comment]
The cost of commit does grow with the amount that is committed, the
break-even point
may be further out than we'd like.

/Finn

**Comment by njovy** [comment]
It would be great if a batch processing feature is implemented as this feature can add the IN clause.

**Comment by RobertoArtiles** [comment]
+1 Will really make things look prettier.

**Comment by basememara** [comment]
What exactly is the workaround? Is it this:
```
RealmResults<Foo> results = realm.where(Foo.class).equalTo("read", false).findAll();

for (int i = 0; i < results.size(); i++) {
    results.get(i).setRead(true);
}
```
I tried this and it doesn't update anything after 200 records for me, is there a limit or a soft fail if it reaches a memory threshold? I'm wrapping the above code in a `realm.executeTransaction`. A method for `updateAllObjects` makes total sense.

**Comment by Saketme** [comment]
@basememara It's a wrong idea to loop over a RealmResults. Since you're changing the RealmObjects (Foo in your case), the `results` is getting auto-updated on each update. Your indices will never be consistent!

**Comment by kneth** [comment]
@Saketme It depends on where you begin your transaction. As  `setRead()` requires a transaction, the code could be

    realm.beginTransaction();
    RealmResults<Foo> results = realm.where(Foo.class).equalTo("read", false).findAll();
    
    for (int i = 0; i < results.size(); i++) {
        results.get(i).setRead(true);
    }
    realm.commit();

**Comment by Saketme** [comment]
No, I am talking about something else. This line of code get all `Foo` items that are "unread", right?

    realm.where(Foo.class).equalTo("read", false).findAll();

Now, if you iterate over it using a for-i loop, setting each item to "read", it will cause the `RealmResults` list to auto-update itself on every iteration. 

On every iteration, on every item that gets marked as "read", the `RealmResults` list will contain one less item, because it's only supposed to contain "unread" items. 

As a result, the for loop will skip every alternate item.

**Comment by kneth** [comment]
@Saketme Well, you can do

    realm.beginTransaction();
    RealmResults<Foo> results = realm.where(Foo.class).equalTo("read", false).findAll();

    for (int i = results.size() - 1; i >= 0; i--) {
        results.get(i).setRead(true);
    }
    realm.commit();

**Comment by Saketme** [comment]
Aha! That's a really nice idea :D Thanks!

**Comment by Zhuinden** [comment]
Seriously though, this is in iOS here:

https://realm.io/docs/swift/latest/#key-value-coding

Realm really will need something like this, because creating 3000 objects to update 3000 properties isn't very good for GC.

**Comment by cmelchior** [comment]
I tend to agree. 
Having `RealmCollection.setValue(String fieldName, Object value)` would probably be relatively easy and straight forward. It would not support manipulating a `RealmList` but that is probably outside the scope of this issue anyway.

**Comment by cmelchior** [comment]
For reference: https://www.reddit.com/r/androiddev/comments/5npdk2/big_realmresult_how_to_iterate_through_all_of_it/, some users are hitting memory issues because of this, so we should probably prioritize getting it in relatively soon.

**Comment by Zhuinden** [comment]
Any chance of this one appearing any time soon?

It's kinda a necessity for working with larger data sets.

**Comment by Zhuinden** [comment]
@cmelchior Out of curiousity, then `realmList.where().findAll().setValue(fieldName, value)` wouldn't work either?

**Comment by kneth** [comment]
@cmelchior @Zhuinden Realm Core doesn't have a such a setter so if we were to implement `setValue()`, we have to loop. Of course we could move the looping to C++ to lower the memory pressure.

**Comment by Zhuinden** [comment]
@kneth but iOS has this 😕

**Comment by cmelchior** [comment]
@Zhuinden We just talked about this internally, and we want to bump the priority on this, but because we don't want to do the work twice, we would like to move this functionality to our Object Store. Because a generic `setValue()` method require some information about the underlying schema we depend on #4324. Fortunately, @kneth is resuming work on that this week.

**Comment by cmelchior** [comment]
Just to iterate the current design:

- [ ] Add a new `setValue(String fieldName, Object value)` method to `RealmCollection`.
- [ ] Determine how to handle unmanaged RealmLists's. We can only support them using reflection, so I would be tempted to just disallow that use case.
- [ ] Validation of fieldName vs. type of input should happen in Object Store. Currently blocked on #4324.
- [ ] Determine how to iterate all objects to update. It can be done in either Object Store or Core. Both kinda makes sense.

````
// Public API Example
RealmResults<Person> guests = realm.where(Person.class).equalTo("inviteSent", false).findAll();
realm.beginTransactions();
persons.setValue("inviteSent", true);
realm.commitTransaction();
```





```

**Comment by cireficc** [comment]
I am very excited for this feature, as I have a million and one for loops iterating to set a property. This will make my code just a little bit cleaner, which is always appreciated! Great work guys 👍

**Comment by ursusursus** [comment]
Very needed, move "move to trash" function which only sets a flag but has to iterate through large dataset takes even 1 minute possibly

**Comment by Zhuinden** [comment]
I don't really understand why this isn't higher priority, iteration is O(N) memory usage :(

**Comment by bmeike** [comment]
@cireficc You realize, of course, that this will simply put that loop in *our* code, instead of yours ;-P

**Comment by Zhuinden** [comment]
@bmeike if you can move that loop off the Java heap, that'd be great for larger data sets though :stuck_out_tongue_winking_eye:

**Comment by cmelchior** [comment]
Yes, that is the primary reason to move this into c++. It becomes zero-allocation on the Java side.

**Comment by cireficc** [comment]
@bmeike Exactly, then my code will be just a tad bit cleaner ;P

**Comment by Zhuinden** [comment]
Technically the real thing here is that updating would take O(N) memory which is bad, SQLite can do this with UPDATE without any allocation. So this will help remove a possible bottleneck in Realm if you ask me

**Comment by Zhuinden** [comment]
So, uh, is this still in RMP 2.0 milestone?

**Comment by kneth** [comment]
@Zhuinden Maybe you are the magician?

**Comment by cmelchior** [comment]
@Zhuinden Yes, this is still scheduled for RMP 2.0 milestone, but not a high priority so if things get tight you have to wait for 4.1 😄

**Comment by VenomVendor** [comment]
Any updates, we are in `4.3.1`?

**Comment by eugens-github** [comment]
It seems there is a snapshot concept, for at least a natural iterate/update scenarios: https://realm.io/docs/java/latest/#iterations-snapshots
So the gotcha "Never loop over RealmResults and update its items" is not a real problem if you do not access the result items by index.

**Comment by lmdic** [comment]
In my Android application I has pojo:

```
public class Product extends RealmObject {
    @PrimaryKey
    private long id;
    private float price;
    private boolean favorite;
}
```

Suppose in Realm table I has 100 products. Nice.
Now I want to update property `favorite = true `only of 5 products with `id `= **1, 14, 38, 78, 90**.

I need something like this:

`UPDATE Product SET favorite = true WHERE id in [1, 14, 38, 78, 90]`

How I can do this?

Thanks.

**Comment by cmelchior** [comment]
```
realm.beginTransaction();
RealmResults<Person> persons = realm.where(Product.class).in("id", new long[] { 1, 14, 38, 78, 90 }).findAll();
for (Person p : persons) {
  p.setFavorite(true);
}
realm.commitTransaction();
```

Should work

**Comment by cmelchior** [comment]
Support has been added in https://github.com/realm/realm-java/pull/5133. It will be part of 5.8.0

**Comment by cmelchior** [comment]
I thought you might like it 😉
