### ISSUE TITLE
Is there a way to use realm-gradle-plugin(7.0.8 or below) without jcenter()?

### ISSUE THREAD

**Issue by mansurrrr** [realm/realm-java#7622]
We are currently using 'realm-gradle-plugin-7.0.8' in out project.
Migrating to 10.0.0 or higher is the best, but we have no time before jcenter closes.

I think the way below is same as using 'realm-gradle-plugin', but i'm not sure

Can i implement libraries separately?
1) 'realm-android-kotlin-extensions:7.0.8' - implement aar file locally 
2) 'realm-android-library:7.0.8' - implement aar file locally
3) 'realm-annotations:7.0.8' - implement(kapt) jar file locally

**Comment by rorbech** [comment]
According to https://jfrog.com/blog/into-the-sunset-bintray-jcenter-gocenter-and-chartcenter/ JFrog have chosen to keep hosting existing packages. Do you have any indicators that it will not be the case?
