### ISSUE TITLE
Involuntary invocation of close()

### ISSUE THREAD

**Issue by gillde** [realm/realm-java#763]
I have three AsyncTaskLoaders in which I make calls to a REST Api.

Loader A and B: Two of them are simple one-shot calls. I receive a json (JSONObject) and put that object into my Realm.
Loader C: The third one has a while loop. In this loop I retrieve a json (JSONArray) from my server and add them to my Realm. So, in short, the loop approx loops for ~80 times and within each cycle I begin a transaction, put a jsonstring consisting of 500 objects into my realm and commit the transaction.

My app is really small. I have a Realm.getInstance(this) in onStart and realm.close() in onStop of my Activity.
Within each loader I have the mandatory loadInBackground. At the beginning of that method I have Realm.getInstance(context) and at the end of it I have realm.close(). So I can see no duplicate or redundant close() call in my app.

When I start my app and start Loader C everything works fine. If I start my app and start loader A and B and after that C, I get "Calling close() on a Realm that is already closed: /data/data/*/files/default.realm" TWICE at the first two iterations of the loop, but everything is added correctly to my Realm.

Debugging calls to Realm.close() shows that it is called with the following stack (but not called by me)
close():181, Realm (io.realm)
finalize():169, Realm (io.realm)
doFinalize():190, Daemons$FinalizerDaemon (java.lang)
run():173, Daemons$FinalizerDaemon (java.lang)
run():818, Thread (java.lang)

That call to close() gives me the above mentioned output.

If I can investigate more, let me now :)

Realm Version: 0.77

**Comment by petersnoopy** [comment]
Same problem happens when making a few asynchronous webservice calls using Retrofit.

**Comment by cmelchior** [comment]
@gillde 
Thank you for the detailed bug report. However, I am having a bit of a problem reproducing it. I created a small sample Activity from your description that is listed below. Running that works as expected and doesn't output any close() warnings. Can you see where your code differs from mine or even better reduce your code to breaking example? 

```
public class IntroExampleActivity extends Activity implements LoaderManager.LoaderCallbacks<Boolean> {

    public static final String TAG = IntroExampleActivity.class.getName();
    private LinearLayout rootLayout = null;

    private Realm realm;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        setContentView(R.layout.activity_realm_basic_example);
        rootLayout = ((LinearLayout) findViewById(R.id.container));
        rootLayout.removeAllViews();
        getLoaderManager().initLoader(1, null, this).forceLoad();
        getLoaderManager().initLoader(2, null, this).forceLoad();
        getLoaderManager().initLoader(3, null, this).forceLoad();
    }

    @Override
    protected void onStart() {
        super.onStart();
        realm = Realm.getInstance(this);
    }

    @Override
    protected void onStop() {
        super.onDestroy();
        realm.close();
    }

    public void showStatus(String txt) {
        Log.i(TAG, txt);
        TextView tv = new TextView(this);
        tv.setText(txt);
        rootLayout.addView(tv);
    }

    @Override
    public Loader<Boolean> onCreateLoader(int id, Bundle args) {
        return new CustomLoader(this, id * 100);
    }

    @Override
    public void onLoadFinished(Loader<Boolean> loader, Boolean data) {
        showStatus("Loader done: " + loader.getId());
        showStatus("Persons: " + realm.allObjects(Person.class).size());
    }

    @Override
    public void onLoaderReset(Loader<Boolean> loader) {
        // Ignore
    }

    private static class CustomLoader extends AsyncTaskLoader<Boolean> {

        private final int iterations;

        public CustomLoader(IntroExampleActivity context, int iterations) {
            super(context);
            this.iterations = iterations;
        }

        @Override
        public Boolean loadInBackground() {
            Realm realm = Realm.getInstance(getContext());
            realm.beginTransaction();
            for (int i = 0; i < iterations; i++) {
                Person p = realm.createObject(Person.class);
                p.setName("Name " + i);
            }
            realm.commitTransaction();
            realm.close();
            return Boolean.TRUE;
        }
    }
}
```

**Comment by gillde** [comment]
I simplified my project. DataB and DataC are essentially the same (in this example only of course). 
The *.json files are simple jsons containing mock data. The C.json is an array of 500 objects. After running this it takes some seconds and then it displays the above mentioned output about close()

public class DataA extends RealmObject {

    private int id;
    private String name;

    public int getId() {
        return id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return name;
    }

    public void setName(String name) {
        this.name = name;
    }
}



public class MainActivity extends ActionBarActivity implements LoaderManager.LoaderCallbacks<String> {

    private static final int LOAD_NETWORK_A = 1;
    private static final int LOAD_NETWORK_B = 2;
    private static final int LOAD_NETWORK_C = 3;
    private Realm mRealm;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        getLoaderManager().initLoader(LOAD_NETWORK_A, null, this).forceLoad();
        getLoaderManager().initLoader(LOAD_NETWORK_B, null, this).forceLoad();
        getLoaderManager().initLoader(LOAD_NETWORK_C, null, this).forceLoad();

        //For testing purpose, start with a fresh database
        Realm.deleteRealmFile(this);
    }

    @Override
    protected void onStart() {
        super.onStart();
        mRealm = Realm.getInstance(this);
    }

    @Override
    protected void onStop() {
        super.onStop();
        mRealm.close();
    }

    @Override
    public Loader<String> onCreateLoader(int i, Bundle bundle) {
        switch (i) {
            case LOAD_NETWORK_A:
                return new ApiLoaderTask(this, DataA.class, "A.json");
            case LOAD_NETWORK_B:
                return new ApiLoaderTask(this, DataB.class, "B.json");
            case LOAD_NETWORK_C:
            default:
                return new ApiLoaderTask(this, DataC.class, "C.json");
        }
    }

    @Override
    public void onLoadFinished(Loader<String> loader, String string) {
    }

    @Override
    public void onLoaderReset(Loader<String> loader) {
    }

    public static class ApiLoaderTask extends AsyncTaskLoader<String> {

        private String mFile;
        private Class mClass;

        public ApiLoaderTask(Context context, Class klass, String file) {
            super(context);
            mFile = file;
            mClass = klass;
        }

        @Override
        public String loadInBackground() {
            Log.d("Loader", mFile);
            Realm realm = Realm.getInstance(getContext());

            if (!mClass.equals(DataC.class)) {
                try {
                    loadJsonFromStream(realm);
                } catch (IOException e) {
                    e.printStackTrace();
                }
            } else {
                for (int i = 0; i < 80; i++) {
                    try {
                        loadJsonFromStream(realm);
                    } catch (IOException e) {
                        e.printStackTrace();
                    }
                }
            }

            realm.close();

            return "";
        }

        private void loadJsonFromStream(Realm realm) throws IOException {
            // Use streams if you are worried about the size of the JSON whether it was persisted on disk
            // or received from the network.
            InputStream stream;
            stream = getContext().getAssets().open(mFile);

            // Open a transaction to store items into the realm
            realm.beginTransaction();
            try {
                realm.createAllFromJson(mClass, stream);
                realm.commitTransaction();
            } catch (IOException e) {
                // Remember to cancel the transaction if anything goes wrong.
                realm.cancelTransaction();
            } finally {
                if (stream != null) {
                    stream.close();
                }
            }
        }
    }
}

**Comment by cmelchior** [comment]
@gillde 
Thank you. I can reproduce the behaviour from your example. I will keep you posted.

**Comment by cmelchior** [comment]
@gillde 
Thank you for your code. I found the bug and it should be fixed in the above PR. Your code is sound so you don't need to change anything. The warning will go away in the next release :)

**Comment by gillde** [comment]
Yeah, I thought so, because despite the warning all objects are added properly to my realm.

Glad I could help!
