### ISSUE TITLE
Realm android permissions

### ISSUE THREAD

**Issue by Lir10** [realm/realm-java#7644]
### Problem

I couldn't find it in the docs but I'm using the default config to connect to realm.
Should we define a permission to write into external storage? seems like it's working on my device (Samsung S21) without that permission though

**Comment by edualonso** [comment]
Hi @Lir10 
If your code targets SDK version 30 and above, you are forced to use scoped storage. In this case, using app-specific storage does not require explicit permissions, see https://developer.android.com/training/data-storage. See https://developer.android.com/about/versions/11/privacy/storage for more info on scoped storage.
