### ISSUE TITLE
Realm.getInstanceAsync callback not called

### ISSUE THREAD

**Issue by Dargoz** [realm/realm-java#7647]
### How frequently does the bug occur?

All the time

### Description

I've work with `Realm.getDefaultInstance()` previously and work as well, but when I tried to migrate to `Realm.getInstanceAsync` it not work :

When I create this method I've confirmed that my observeable method called, but when try to create instance async and receive callback `onSuccess` nothing happen and my Log inside `onSuccess` method never called;
```java
@Override
    public Observable<String> getLanguage() {
        return Observable.create(emitter -> {

            assert Realm.getDefaultConfiguration() != null;
            Log.d("DRG","realm configuration : not null");
            Realm.getInstanceAsync(Realm.getDefaultConfiguration(), new Realm.Callback() {
                @Override
                public void onSuccess(@NonNull Realm realm) {
                    try {
                        Log.d("DRG","onSuccess : " + realm);
                      

                    } catch (Exception e) {
                       
                        emitter.onNext("");
                    }
                    realm.close();
                }

                @Override
                public void onError(Throwable exception) {
                    Log.d("DRG","realm instance onError : " + exception.getMessage());
                    super.onError(exception);
                }
            });

        });
    }
```

### Stacktrace & log output

```shell
2022-02-17 11:36:42.371 27589-27589/com.example.android D/DRG: call
2022-02-17 11:36:42.377 27589-27672/com.example.android D/DRG: realm configuration : not null
```
```


### Can you reproduce the bug?

Yes, always

### Reproduction Steps

_No response_

### Version

10.8.1

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

Yes, using encryption

### Platform OS and version(s)

I tried it on my Android 12, but I think that's not OS issue

### Build environment

Android Studio version:
```
Android Studio Bumblebee | 2021.1.1 Patch 1
Build #AI-211.7628.21.2111.8139111, built on February 2, 2022
Runtime version: 11.0.11+9-b60-7590822 amd64
VM: OpenJDK 64-Bit Server VM by Oracle Corporation
Windows 10 10.0
GC: G1 Young Generation, G1 Old Generation
Memory: 1280M
Cores: 16
Registry: external.system.auto.import.disabled=true
Non-Bundled Plugins: Lombook Plugin (0.34.1-2019.1), com.jetbrains.nim (1.4.1-203), com.jetbrains.plugins.ini4idea (211.6693.44), com.thoughtworks.gauge (211.6693.111), org.jetbrains.kotlin (211-1.6.10-release-923-AS7442.40), org.intellij.plugins.markdown (211.7142.37)
```
Android Build Tools version: 30.0.3
Gradle version: 6.9.2

**Comment by edualonso** [comment]
Hi @Dargoz 

I've run a code snippet similar to yours and it works just fine:

```
public class MainActivity extends AppCompatActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);

        Realm.init(this);

        setContentView(R.layout.activity_main);
        getLanguage().subscribe(s -> {
            Log.d("---", "------------> subscribed: " + s);
            s.close();
        }, throwable -> {
            Log.d("---", "------------> error: " + throwable.getMessage());
        });
    }

    public Observable<Realm> getLanguage() {
        Realm.getDefaultInstance();
        return Observable.create(emitter -> {
            assert Realm.getDefaultConfiguration() != null;
            Log.d("---", "------------> realm configuration : not null");
            Realm.getInstanceAsync(Realm.getDefaultConfiguration(), new Realm.Callback() {
                @Override
                public void onSuccess(@NonNull Realm realm) {
                    try {
                        Log.d("---", "------------> onSuccess : " + realm);
                        emitter.onNext(realm);
                    } catch (Exception e) {
                        emitter.onError(e);
                    }
                }

                @Override
                public void onError(Throwable exception) {
                    Log.e("---", "------------> realm instance onError : " + exception.getMessage());
                    super.onError(exception);
                }
            });
        });
    }
}

// Output:
// D/---: ------------> realm configuration : not null
// D/---: ------------> onSuccess : io.realm.Realm@c3317a7
// D/---: ------------> subscribed: io.realm.Realm@c3317a7
```

Are you perhaps subscribing to the observable on a non-looper thread? Realm instances cannot be loaded asynchronously on a non-looper thread as they would not be able to receive updates. Is your observable part of a more complex stream where exceptions might be swallowed by another error callback?

**Comment by Dargoz** [comment]
well, unfortunately i'm using complex stream due to my application design, most likely will be like this :

```java
getLanguage().subscribeOn(Schedulers.io())
                .observeOn(AndroidSchedulers.mainThread())
                .subscribeWith(new DisposableObserver<String>() {
                    @Override
                    public void onNext(String s) {
                        Log.d("DRG","use case on next : " + s);
                    }

                    @Override
                    public void onError(Throwable e) {

                    }

                    @Override
                    public void onComplete() {

                    }
                });
```

when I'm using only `subscribeOn()` it works like you've already tried.. could it be that's not possible to do in my way using disposableObserver ?

**Comment by edualonso** [comment]
> could it be that's not possible to do in my way using disposableObserver ?

I don't think so. You are simply using one of the many overloads RxJava offers to subscribe to a stream.

In any case, using `subscribeOn(Schedulers.io())` will yield an exception when opening a realm since said scheduler doesn't have any threads attached to a looper and therefore the execution flow will go through the `onError(Throwable e)` callback you wrote in your `DisposableObserver`. That's why you never see Realm's `onSuccess(@NonNull Realm realm)` or RxJava's `onNext(String s)` callbacks being triggered because the exception is thrown before the realm can be opened.

This is happening because you are conflating both RxJava and Realm asynchronous callbacks. You need to handle any potential exceptions triggered before opening the realm itself inside your RxJava observables in your subscription because you are opening the realm there. I would recommend adding some code in the `onError(Throwable e)` observer callback, clearly showing the stream ends up landing there, or else you won't notice there has been an error.

I will close the issue since it appears to be an implementation mistake but feel free to ask any questions should you have any.
