### ISSUE TITLE
Realm.isEmpty() method

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#766]
Feature request from this thread: https://groups.google.com/forum/#!topic/realm-java/u2DUhFbgMAc

Add a ```realm.isEmpty()``` method that returns true if there is no objects in the Realm. It is just a utility method, but fits nicely with the Realm object store abstraction.

**Comment by bmunkholm** [comment]
I'm not convince this will be useful to many. Most of the time you would know which models you want to check? We should only add very useful or needed features to keep the API lean. So unless people really +1 this feature, I would close it.

**Comment by cmelchior** [comment]
I agree, but the issue came up during a help request. This way we can also track it, even if we decide against it.

**Comment by kristofer** [comment]
+1 - My situation is that I'm backing up the realm into cloudkit and when I switch devices, I need to know if the realm that was created is empty and I should "restore" from the "last backup"

**Comment by cauli** [comment]
+1. Use-case: I want to bundle a prepopulated database with the app but also maintain a updatable one when possible. I need to check if the updatable is empty. If true, I'll use the prepulated one.
