### ISSUE TITLE
Crashing with SIGSEGV due to bad_function_call

### ISSUE THREAD

**Issue by satohu20xx** [realm/realm-java#7669]
### How frequently does the bug occur?

Sometimes

### Description

We are experiencing many instances of applications crashing with the following logs.

```
0: librealm-jni.so: std::__ndk1::bad_function_call::~bad_function_call()
1: librealm-jni.so: Java_io_realm_internal_OsList_nativeFreeze
2: librealm-jni.so: Java_io_realm_internal_OsList_nativeFreeze
3: librealm-jni.so: Java_io_realm_internal_OsList_nativeFreeze
4: librealm-jni.so: Java_io_realm_internal_OsList_nativeFreeze
```

I am aware that the freeze function is not used because I am using the following RealmConfigration, is there any way to avoid this crash?

```kotlin
    RealmConfiguration.Builder()
        .name(REALM_FILE_NAME)
        .rxFactory(RealmObservableFactory(false))
        .flowFactory(RealmFlowFactory(false))
        .build()
```

Also, what are the possible causes of bad_function_call?

### Can you reproduce the bug?

Not yet

### Version

10.10.1

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

macOS Catalina 10.15.6

### Build environment

Android Studio version:
```
Android Studio Bumblebee | 2021.1.1 Patch 2
Build #AI-211.7628.21.2111.8193401, built on February 17, 2022
Runtime version: 11.0.11+0-b60-7590822 x86_64
VM: OpenJDK 64-Bit Server VM by JetBrains s.r.o.
```

Android Build Tools version: `31.0.0`
Gradle version: `com.android.tools.build:gradle:7.1.2`

**Comment by satohu20xx** [comment]
Sorry. It seems that this crash was caused by the interference of another library. I'm closed this issue as the problem has been resolved by modifying the another library.

**Comment by bmunkholm** [comment]
No problem - good to hear!
