### ISSUE TITLE
How to build MacOS .dylib file?

### ISSUE THREAD

**Issue by seabornlee** [realm/realm-java#7679]
### Problem

Dear maintainers

I am trying to get Realm working with Robolectric.
I saw in the official documents saying it's not supported, and also saw the feature request to the Robolectric team https://github.com/realm/realm-java/issues/904.

I am thinking, you have realm-jni, so it should be possible to call from Java code.
I am working on Mac OS, the problem is I can't build a `.dylib` from gradle tasks. The `.so` is generated.

### Solution

It will be great if you can build `.dylib` by calling gradle task with argument.

### How important is this improvement for you?

Would be a major improvement

**Comment by cmelchior** [comment]
Hi @seabornlee 

That is correct, in theory, we could build a `.dylib` but it would be significant work, so unlikely to happen soon.

Our Realm Kotlin SDK has this support built in already, so depending on your use case, you might consider switching to that: https://github.com/realm/realm-kotlin

**Comment by seabornlee** [comment]
> Hi @seabornlee
> 
> That is correct, in theory, we could build a `.dylib` but it would be significant work, so unlikely to happen soon.
> 
> Our Realm Kotlin SDK has this support built in already, so depending on your use case, you might consider switching to that: https://github.com/realm/realm-kotlin

Thanks @cmelchior !
That is awesome! I will check it out right now.
