### ISSUE TITLE
Not receive change notification when RealmObject has a variable which is instance of itself

### ISSUE THREAD

**Issue by JoyHong** [realm/realm-java#7683]
### How frequently does the bug occur?

All the time

### Description

```
class Person extends RealmObject {
          private Person child;
}
```
eg.
list = PersonA(child=B), PersonB(child=C), PersonC,
when PersonB is changed, list can't receive PersonA is changed.

### Can you reproduce the bug?

Yes, always

### Version

10.5.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

Android All

### Build environment

Android Studio version: ...
Android Build Tools version: ...
Gradle version: ...

**Comment by cmelchior** [comment]
Hi @JoyHong 
This is a known issue. The root cause is here: https://github.com/realm/realm-java/issues/4786 So I will fold that issue into that one.

One work-around for know is to use `RealmResults` changelisteners. That will trigger on a change like this, i.e. something like

```
val results = realm.where<Person>().equalTo("id", personAId").findAll()
results.addChangeListener {
  handleChange(it.first())
}
```
