### ISSUE TITLE
Used setNulllable/setNull and I'm getting Property has been made optional crash

### ISSUE THREAD

**Issue by davieskent** [realm/realm-java#7690]
### How frequently does the bug occur?

Sometimes

### Description

I've updated my app on the play store and started having the crash:

```
Fatal Exception: java.lang.IllegalArgumentException: Illegal Argument: This field(name) is not nullable.
       at io.realm.internal.UncheckedRow.nativeSetNull()
       at io.realm.internal.UncheckedRow.setNull(:286)
       at io.realm.internal.CheckedRow.setNull(:96)
       at io.realm.DynamicRealmObject.setNull(:1051)
       at 
```

I've changed my model from:

```
@Required
@RealmField(NAME)
var name: String = ""
```

to:
```
@Required
@RealmField(NAME)
var name: String? = null
```

When the model was created, it was like `addField(PersonRealm.NAME, String::class.java, isRequired = true)`

And on the migration, only have added:

```
schema.get(PersonRealm::class.java.simpleName)?.apply {
    transform { dynamicRealmObject ->
        dynamicRealmObject.setNull(PersonRealm.NAME)
    }
}
```

I've removed the `@Required` annotation from the field and changed my migration to:
```
schema.get(PersonRealm::class.java.simpleName)?.apply {
    setNullable(PersonRealm.NAME, true)
    transform { dynamicRealmObject ->
        dynamicRealmObject.setNull(PersonRealm.NAME)
    }
}
```

I've locally tested, and it seemed the migration was now correct, but after uploading a new version to the store I'm still having the crash (way less crashes nevertheless):

```
Fatal Exception: io.realm.exceptions.RealmMigrationNeededException: Migration is required due to the following errors:
- Property 'PersonRealm.name' has been made optional.
       at io.realm.internal.OsSharedRealm.nativeGetSharedRealm()
       at io.realm.internal.OsSharedRealm.<init>(:173)
       at io.realm.internal.OsSharedRealm.getInstance(:249)
```

Do I need to change anything more in my migration?

### Can you reproduce the bug?

Not yet

### Version

10.4.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

Yes, using encryption

### Platform OS and version(s)

Android 9 and 11

**Comment by rorbech** [comment]
@davieskent Is this still a problem or do you have any further observations that could shed light on the issue?
