### ISSUE TITLE
Sync Error:231 for Compensating writes comes as. "unknown" 

### ISSUE THREAD

**Issue by hennasingh** [realm/realm-java#7716]
### How frequently does the bug occur?

Seen once

### Description

In the Realm Java 10.11.1 version, ErrorCompensatingWrites is introduced, such that when user does not have permissions, write is not committed. but I am unable to catch this error via name as it shows as "Unknown".

Could we do a name mapping to this?
Attached screenshot of debug report:

![Screenshot 2022-09-05 at 15 44 25](https://user-images.githubusercontent.com/22836317/188486382-c770b88d-5c8f-46a8-aa63-e52ee595bcf5.png)
the 

### Stacktrace & log output

```shell
screenshot attached above
```

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

Make a write in your application without granting permissions on Cloud UI.
(@clementetb has seen the reproduction)

### Version

10.11.1

### What SDK flavour are you using?

MongoDB Realm (i.e. Sync, auth, functions)

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

12

### Build environment

Android Studio version: ... Chipmunk 2021.2.1 Patch 1
Android Build Tools version: 29.0.3
Gradle version: 4.0.2

**Comment by cmelchior** [comment]
It it this app: https://github.com/hennasingh/RestaurantApp

**Comment by edualonso** [comment]
The error type has been added in `v10.12.0` and @hennasingh confirmed the error is correctly mapped now. Closing issue.
