### ISSUE TITLE
Problematic OpenSSL version (OpenSSL 1.1.1g)

### ISSUE THREAD

**Issue by Daidairu** [realm/realm-java#7732]
### How frequently does the bug occur?

All the time

### Description

I updated my new version app to google play and got the warning below.

<img width="977" alt="screen_shot" src="https://user-images.githubusercontent.com/16202889/195774812-db8fb69e-b7e4-4407-9910-33b7559da5e6.png">

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

Submit to the play store and get the warning response

### Version

10.3.1

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

android

### Build environment

Android Studio version: 4.1.2
Android Build Tools version: 28.0.3
Gradle version: 3.5.3

**Comment by mkpoul** [comment]
I want to ask about realm/realm-dotnet. Which version realm-dotnet I should use to get rid off Defective OpenSSL Version?
<img width="917" alt="Screenshot 2022-11-14 at 14 55 45" src="https://user-images.githubusercontent.com/22868740/201666003-bb8243fb-42f8-46c2-af27-4843bf273086.png">

**Comment by DWaterhouse1** [comment]
@mkpoul did you manage to find which realm-dotnet version was needed? I have the same issue as you.

**Comment by mkpoul** [comment]
> @mkpoul did you manage to find which realm-dotnet version was needed? I have the same issue as you.

At that moment I updated Realm-dotnet up to 10.18.0
