### ISSUE TITLE
Question: create and close of realm instances on main thread

### ISSUE THREAD

**Issue by petersnoopy** [realm/realm-java#774]
What is the best practice for handling realm instances (create and close) on ui thread when having an app with a lot of Fragments? Should I use only one realm instance per Fragment or a single instance for all ui operations?

**Comment by cmelchior** [comment]
That really depends on how you want to your code to look like.

The Realm instances are cached on the same thread using reference counting, so having many calls to ```Realm.getInstance()``` on the UI thread is really cheap, and has the advantage that it is easy to check if it is being closed properly. 

It has the downside that you will have more code to write as you have to implement onCreate/onDestroy or onStart/onStop in all your activities/fragments. I would not use onResume/onPause as they don't overlap between activities, meaning that the cache will be fully cleared between activities if you close it on onPause. This **will** make it more expensive to reopen.

Personally I would probably put it in either a custom Application class or inject it using a DI framework like Dagger, as it is less code to write and is easy to control. The downside to that approach is that non-UI threads still have to use Realm.getInstance() so you would have to handle two concepts in your code.

**Comment by petersnoopy** [comment]
If I put it in an custom Application class how can i close the realm instance before the Application is destroyed or recreated?

	public class MyApplication extends Application {

		private Realm realm;

		@Override
		public void onCreate() {
			super.onCreate();
			realm = Realm.getInstance(getApplicationContext());
		}

		public Realm getRealm() {
			return realm;
		}
	}

**Comment by cmelchior** [comment]
Hmm, my memory must be getting old and rusty. You are correct there is no onDestroy method on the Application class. 

I would use onCreate/onDestroy in all activities in that case, ie. use 1 instance pr. Activity/Fragment. Having it on a BaseActivity/BaseFragment that all your activities and fragments extend would make it fairly simple.

```
public class BaseActivity extends Activity {

    private Realm realm;

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        realm = Realm.getInstance(this);
    }

    @Override
    protected void onDestroy() {
        super.onDestroy();
        realm.close();
    }

    public Realm getRealm() {
        return realm;
    }
}

public class BaseActivity extends BaseActivity {

    @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        RealmResults<Foo> foos = getRealm().allObjects(Foo.class);
    }
}

**Comment by petersnoopy** [comment]
Ok thanks, I will try your suggestion.

**Comment by cmelchior** [comment]
Great. Let us know if you run into any more problems.

**Comment by Saketme** [comment]
A slight improvement here would be to open lazily open Realm. :)

**Comment by tiramakantraore** [comment]
Is it possible to close the realm instance in Application.onTerminate ?

**Comment by cmelchior** [comment]
No, as `onTerminate` is not called on devices: http://developer.android.com/reference/android/app/Application.html#onTerminate()

**Comment by tiramakantraore** [comment]
Ok tank you very much
Le 11 févr. 2016 06:07, "Christian Melchior" <notifications@github.com> a
écrit :

**Comment by hoangtu23** [comment]
@petersnoopy How does the suggestion work?
