### ISSUE TITLE
multi table

### ISSUE THREAD

**Issue by dakexuan** [realm/realm-java#7743]
### Problem

how can i create double table base on one model？

**Comment by rorbech** [comment]
Hi @dakexuan. It is not clear what you mean by "double table". Could you elaborate a bit?

**Comment by dakexuan** [comment]
I have a model MessageEntity for storing group and individual chat messages，The message structure is the same，I'd like to store them separately，How can I do that？Like SQLit，a table can be created using different table names

**Comment by clementetb** [comment]
Hi @dakexuan you will need to create a second model with a copy of the data from the first. 

If the use case is that a group or an individual owns a message, you might use [object relationships](https://www.mongodb.com/docs/realm/sdk/kotlin/realm-database/schemas/relationships/) to define it. It would allow reusing the same model whether an individual or a group binds it.

Realm even allow you to define backward relationships based on a relationship to be able to navigate the objects in any direction.
