### ISSUE TITLE
deleteAllFromRealm() issue with gradle-plugin:10.13.0  - OK with realm-gradle-plugin:10.12.0

### ISSUE THREAD

**Issue by LeonardDaVinci** [realm/realm-java#7748]
### How frequently does the bug occur?

All the time

### Description

Hello,

I wanted to upgrade realm in my Android (Dolphin) project
from dependencies = classpath 'io.realm:realm-gradle-plugin:10.12.0'
to dependencies = classpath 'io.realm:realm-gradle-plugin:10.13.0'

I have noticed that using exactly the same code, deleteAllFromRealm() does NOT work with gradle-plugin:10.13.0 - records are not deleted at all!

Making the same with with gradle-plugin:10.12.0 all records get deleted as usual.

This is the piece of code, that has two differents results using it with Realm 10.12.0 or Realm 10.13.0

    public void deleteOrderHistoriesFromDB(final String time) {
        realm.executeTransactionAsync(new Realm.Transaction() {
            @Override
            public void execute(@NonNull Realm realm) {
                RealmResults<OderHistoryOl> results = realm.where(OderHistoryOl.class).equalTo("time", time).findAll();
                results.deleteAllFromRealm();
            }
        });
    }

Am I making some mistake in code?

Thank you for help.

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

Leaving exactly the same java code, but only changing build.gradle 
dependencies = classpath 'io.realm:realm-gradle-plugin:10.12.0'  
to  dependencies = classpath 'io.realm:realm-gradle-plugin:10.13.0'
will allways cause the  issue

### Version

classpath 'io.realm:realm-gradle-plugin:10.13.0'

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

Yes, using encryption

### Platform OS and version(s)

Android 7, Android 11

### Build environment

Win10 64Bit
Android Studio Dolphin | 2021.3.1  
Android Gradle Plugin Version 7.3.0  
Gradle version 7.6

**Comment by cmelchior** [comment]
Hi @LeonardDaVinci 

I tried to reproduce this behavior, but it seems to work also in 10.13. Your code looks correct, but it sounds like something you can reproduce? 

Perhaps it is a problem with your input parameter to the function. Have you verified that `RealmResults<OderHistoryOl> results` actually returns any results?

**Comment by LeonardDaVinci** [comment]
Hi @edualonso. I made test, writing also using .allowQueriesOnUiThread(true) but still no luck. I wrote .executeTransaction but app crash!... I have to think some other solution..

**Comment by clementetb** [comment]
Hi @LeonardDaVinci we need more context about the issue to tell what's going on. Would you be able to create and share a test project that reproduces this issue?
