### ISSUE TITLE
Invalid instrumented test code coverage for libraries when applying Realm plugin.

### ISSUE THREAD

**Issue by Plo4ox** [realm/realm-java#7749]
### How frequently does the bug occur?

All the time

### Description

This is a gradle plugin issue, it only happens when applying the "realm-android" plugin on an android library. No issue raised when executing it on an app.

Expected:
After executing the connected android test ("mylibrary:connectedDebugAndroidTest"), the generated "coverage.ec" must not be empty.

Actually happening:
After executing the connected android test, the generated "coverage.ec" is empty 

### Can you reproduce the bug?

Yes, always

### Reproduction Steps

Here is a link to a Github repository containing what is described in the following steps.
https://github.com/Plo4ox/RealmJavaSdkIssue
Branches:
- main: (**issue**) Latest Gradle version with latest realm plugin version applied
- feature/without-realm: (**no issue**) Latest Gradle version without applying Realm plugin
- feature/use-older-gradle7.2: (**no issue**) Gradle 7.2 version with lastest realm plugin applied

Here is what can be done to reproduce the issue:
- Create an android application project
- Create a library in this project
- Add and apply the java realm plugin in the app and the library
- Enable the coverage in both app/library gradle files.
```
android {
...
buildTypes {
    debug {
        testCoverageEnabled true
    }
...
}
```
- Then add a simple class to be tested in the created library and app, here is an example
```
class LibClassToBeTested {
    fun onePlusOne() = 1 + 1
}
```
- Then to test this class add an instrumented test
```
@RunWith(AndroidJUnit4::class)
class LibClassToBeTestedTest {
    @Test
    fun testOnePlusOne() {
        assertEquals(2, LibClassToBeTested().onePlusOne())
    }
}
```
- To have a good view start by executing the app tests with the following command (Be sure to have a connected device/emulator)
```
./gradlew app:connectedDebugAndroidTest
```
- At the end of it, a file with the coverage must be created, as it can be seen here the file is not empty.
```
ls -la "app/build/outputs/code_coverage/debugAndroidTest/connected/<YOUR DEVICE>/coverage.ec"
-rw-r--r--  1 plo4ox  staff  **2650** Dec 12 12:00 app/build/outputs/code_coverage/debugAndroidTest/connected/<YOUR DEVICE>/coverage.ec
```
- Now by doing the same thing on the library,
```
./gradlew lib:connectedDebugAndroidTest
```
- The generated file is empty, which must not be the case.
```
ls -la "mylibrary/build/outputs/code_coverage/debugAndroidTest/connected/<YOUR DEVICE>/coverage.ec"
-rw-r--r--  1 plo4ox  staff  **0** Dec 12 12:00 mylibrary/build/outputs/code_coverage/debugAndroidTest/connected/<YOUR DEVICE>/coverage.ec
```

As it can be seen this is only happening with the library, thus the code coverage on the library classes is empty. 
This is not the case with the code coverage of the app.

Temporary workarounds:
- Create another library, which applies the realm plugin, containing only your realm objects and your realm module. And use this library in the main library.
- I don't like this option but you can also revert to a Gradle version older than the 7.3.3.
- Or if you don't already have a big project using realm java sdk, migrating to the kotlin sdk also seems like a good/quick fix.

### Version

10.13.0

### What SDK flavour are you using?

Local Database only

### Are you using encryption?

No, not using encryption

### Platform OS and version(s)

Android 12

### Build environment

Android Studio version: Android Studio Dolphin | 2021.3.1 Patch 1
Android Build Tools version: 7.3.1
Gradle version: 7.4

**Comment by edualonso** [comment]
Hi @Plo4ox 
We are aware of some changes to the transformer API in AGP 7.3. Unfortunately we don't support this new API due to a bug that cannot be fixed for previous versions. We have though an experimental branch that runs with AGP 7.4 which can be found at https://central.sonatype.dev/artifact/io.realm/realm-android-library/10.12.0-transformer-api
Could you try and test it with the experimental branch and [AGP 7.4](https://developer.android.com/reference/tools/gradle-api)?

**Comment by Plo4ox** [comment]
Hi,

Thanks for the quick answer!
I tested with [10.13.0-transformer-api](https://central.sonatype.dev/artifact/io.realm/realm-android-library/10.13.0-transformer-api), and indeed the issue seems to be fixed! 😃👍
It has been tested here
[https://github.com/Plo4ox/RealmJavaSdkIssue/tree/feature/working-10-13-transformer-api
](https://github.com/Plo4ox/RealmJavaSdkIssue/tree/feature/working-10-13-transformer-api
)

@edualonso Do you know what the plans are for this experimental branch in the future?

**Comment by clementetb** [comment]
It will become the main branch once AGP 7.4 is released.

**Comment by Plo4ox** [comment]
Ok great, thanks! 😃
