### ISSUE TITLE
Jacoco failed with xxx--transformer-api realm import

### ISSUE THREAD

**Issue by Oshuremy** [realm/realm-java#7770]
### How frequently does the bug occur?

Always

### Description

When I run JacocoReport task from jacoco library, the coverage isn't generate

Here you can find the jacoco.gradle
```
apply plugin: "jacoco"

def flavorName = "release"
def projectName = "app"

def testTaskName = "test${flavorName.capitalize()}UnitTest"
def reportTaskName = "${projectName}JacocoReport"
def coverageVerificationTaskName = "${projectName}JacocoCoverageVerification"

def generatedClassesDir = "$buildDir/tmp/kotlin-classes/${flavorName}"
def sourceDir = "src/main/java"
def execFile = "$buildDir/jacoco/${testTaskName}.exec"

def excludes = []
def includes = []

jacoco {
    // https://github.com/jacoco/jacoco/releases
    toolVersion = "0.8.8"
}

task "${reportTaskName}"(type: JacocoReport, dependsOn: "${testTaskName}") {
    group = "Reporting"
    description = "Generate Jacoco coverage reports for $projectName build"

    reports {
        xml.required = false
        csv.required = false
        html.outputLocation = layout.buildDirectory.dir('jacoco-coverage')
    }

    classDirectories.from = fileTree(dir: generatedClassesDir,
            includes: includes,
            excludes: excludes)
    sourceDirectories.from = files(sourceDir)
    executionData.from = files(execFile)
}
```

### Stacktrace & log output

```shell
> Task :app:appJacocoReport SKIPPED
Skipping task ':app:appJacocoReport' as task onlyIf 'Any of the execution data files exists' is false.
AAPT2 aapt2-7.4.1-8841542-windows Daemon #0: shutdown
AAPT2 aapt2-7.4.1-8841542-windows Daemon #1: shutdown
AAPT2 aapt2-7.4.1-8841542-windows Daemon #2: shutdown
AAPT2 aapt2-7.4.1-8841542-windows Daemon #3: shutdown
AAPT2 aapt2-7.4.1-8841542-windows Daemon #4: shutdown
AAPT2 aapt2-7.4.1-8841542-windows Daemon #5: shutdown
AAPT2 aapt2-7.4.1-8841542-windows Daemon #6: shutdown
AAPT2 aapt2-7.4.1-8841542-windows Daemon #7: shutdown
```

### Can you reproduce the bug?

Always

### Version

10.13.2-transformer-api

### What Atlas App Services are you using?

-- select --

### Are you using encryption?

-- select --

### Platform OS and version(s)

Android

### Build environment

Gradle version: 7.4.1

**Comment by edualonso** [comment]
Possibly related to https://github.com/realm/realm-kotlin/issues/1243

**Comment by edualonso** [comment]
Hi @Oshuremy. Is this problem present in versions pre-transformer API? Also, to confirm, this problem you are seeing happens only with Gradle 7.4.1? And which Android Gradle Plugin version are you using?

**Comment by Oshuremy** [comment]
Hi,

> Is this problem present in versions pre-transformer API ? 
No

> This problem you are seeing happens only with Gradle 7.4.1? 
Before Gradle 7.4.1 we don't need tranformer and I didn't try to upgradle Gradle more

> Which Android Gradle Plugin version are you using?
gradle-7.6-bin.zip

**Comment by rorbech** [comment]
This just seems to be a side effect of #7771. For some reason the junit framework is not picking up any tests if the tests are in a `jar`-file (which is the case with the new transformer infrastructure) instead of a temporary directory. Since there are many other issues with running unittests with Realm (as the Android context is not available, etc.) we have currently bypassed our transformation for the unittest component to avoid this in #7780. This will also render actual output of the unittest stage that is linked in the `testTaskName` from your `jacoco.gradle` and JaCoCo will then generate the reports from the output.

**Comment by rorbech** [comment]
Closing this as it is a direct consequence of #7771. Please track that instead.
