### ISSUE TITLE
Investigate necessary steps to support Gradle 8.0

### ISSUE THREAD

**Issue by edualonso** [realm/realm-java#7773]
This is an umbrella ticket for existing reported issues in connection with upgrading the project to Gradle 8.0. We will write findings here as we tackle the upgrade:
- ~https://github.com/realm/realm-java/issues/7771~ not Gradle8 related
- https://github.com/realm/realm-java/issues/7765

**Comment by edualonso** [comment]
According to [this table](https://developer.android.com/studio/releases/gradle-plugin#updating-gradle) Gradle version 8 should be paired with AGP 8. However, it is still in a preview state (see [here](https://developer.android.com/reference/tools/gradle-api)) so we can't guarantee everything will work until they release a stable version.

Despite this, compiling the project using Gradle 8 together with AGP 7.4.1 appears to succeed without issues after solving a few deprecation and task precedence issues.

**Comment by rorbech** [comment]
@clementetb confirmed that the latest version of realm-java works with Gradle 8
