### ISSUE TITLE
App crash after installing using dexguard

### ISSUE THREAD

**Issue by nicola-cab** [realm/realm-java#7787]
### How frequently does the bug occur?

Always

### Description

This is the original bug that was reported in core:  https://github.com/realm/realm-core/issues/6382

### Can you reproduce the bug?

Always

### Version

10.6.0

### What Atlas App Services are you using?

Local Database only

### Are you using encryption?

Yes

### Platform OS and version(s)

N/A

### Build environment

Android Studio version: ...
Android Build Tools version: ...
Gradle version: ...

**Comment by bmunkholm** [comment]
Closing as we assume this is resolved. If not, please create another issue with all details. Thanks!
