### ISSUE TITLE
Crash while removing objects in forEach block

### ISSUE THREAD

**Issue by Khudoyshukur** [realm/realm-java#7792]
PluginVersion: 10.13.0

I am getting crash here in production:
![image](https://user-images.githubusercontent.com/60431559/227523208-f443a3e0-439b-4e1d-9eb8-e5d97676dc19.png)

Here the code block:
![image](https://user-images.githubusercontent.com/60431559/227523761-113d9442-7490-4fa5-b74f-fb040e974324.png)

ExecureRealmTransaction has a mutex. So, no other transaction disturb current transaction.
![image](https://user-images.githubusercontent.com/60431559/227523139-df9be3c6-3db7-42f6-a601-4d643ce3897d.png)

I am guessing that the crash is coming from **line:32** because of **ConcurrentModification**.
What should I use in this case? **.deleteAllFromRealm()** ? Or should I **reverse-iterate**?

Similar issue: https://github.com/realm/realm-java/issues/2660

**Comment by clementetb** [comment]
I am unable to reproduce the issue. It might be have something to do on your code. Would it be possible to share a sample project that causes the issue?

On the other hand, I think that you could use:
- `executeTransactionAwait` instead of `executeRealmTransaction`
- `deleteAllFromRealm` instead of deleting one point at a time.

**Comment by Khudoyshukur** [comment]
@clementetb 
I myself also could not reproduce the crash locally. It is happening with few Samsung Android devices. 

1. `executeTransactionAwait`? Does it ensure synchonization? For example, one transaction is **in progress**. And the second transaction should wait.
2. I will use it.

**Comment by clementetb** [comment]
No need to ensure synchronization yourself. There can only be one write transaction active per Realm.

**Comment by Khudoyshukur** [comment]
@clementetb Thank you. I will take your recommendations and further monitor this crash
