### ISSUE TITLE
Hi @rzong...You can use `RealmConfiguration.Builder.directory()` and `RealmConfiguration.Builder.name()` to set a path to a Realm file.

### ISSUE THREAD

**Issue by Huazhiling** [realm/realm-java#7794]
Hi @rzong...You can use `RealmConfiguration.Builder.directory()` and `RealmConfiguration.Builder.name()` to set a path to a Realm file.

_Originally posted by @cmelchior in https://github.com/realm/realm-java/issues/7668#issuecomment-1094704938_
            

I have a problem with creating by this method，
```
Unrecoverable error. Invalid argument in /home/cc/repo/realm/release/realm/realm-library/src/main/cpp/io_realm_internal_SharedRealm.cpp line 217
```
version:3.1.1

**Comment by clementetb** [comment]
@Huazhiling We would need some context on what are you trying to do, could you please share the initialization code for your Realm? 

Are you using version Realm`3.1.1`, try to upgrade to the latest version.

**Comment by Huazhiling** [comment]
> @Huazhiling We would need some context on what are you trying to do, could you please share the initialization code for your Realm?
> 
> Are you using version Realm`3.1.1`, try to upgrade to the latest version.

```
Realm.init(this);
        // setting realm config
        RealmConfiguration config = new RealmConfiguration.Builder()
                .deleteRealmIfMigrationNeeded()
                .name("MISUMIRealm.realm")
                .schemaVersion(1)
                .migration(new MyMigration())
                .build();
        // save default config
        Realm.setDefaultConfiguration(config);
```
I get an error when calling
```
Realm.getDefaultInstance()
```
I can't upgrade to the latest version right now，
My current project is relatively old and cannot support androidx for the time being. The latest version requires kontlinx.flow and needs to be upgraded to androidx, which cannot be upgraded

**Comment by clementetb** [comment]
Version 10.13.1 does not require `kotlinx.flow`. It might require some changes though. 

The Realm Version 3.1.1 is 6 years old and since we have released many new features and bug fixes.

**Comment by Huazhiling** [comment]
> Version 10.13.1 does not require `kotlinx.flow`. It might require some changes though.
> 
> The Realm Version 3.1.1 is 6 years old and since we have released many new features and bug fixes.

Hi，Now this problem arises
```
java.lang.UnsupportedOperationException

The coroutines framework is missing from the classpath. Remember to add it as an implementation dependency. See https://github.com/Kotlin/kotlinx.coroutines#android for more details

 com.alibaba.fastjson.JSONException: write javaBean error
```
I need to parse the data returned by Realm into a string and return it, but when using FastJSON for parsing, an error occurred due to one of the returned values having a type of "flow", which is not compliant with FastJSON's parsing rules. This error did not occur in older versions.

**Comment by clementetb** [comment]
@Huazhiling I am glad that you were able to resolve the first issue. 

Now the issue is that you are trying to use coroutine-based Realm helper methods, but you can not provide the coroutines library. 

Avoid using such helper methods and you would be safe. I am afraid that if you like to use such methods you would need to migrate to use androidx.

**Comment by Huazhiling** [comment]
> @Huazhiling I am glad that you were able to resolve the first issue.
> 
> Now the issue is that you are trying to use coroutine-based Realm helper methods, but you can not provide the coroutines library.
> 
> Avoid using such helper methods and you would be safe. I am afraid that if you like to use such methods you would need to migrate to use androidx.

Okay, since upgrading is not possible for this old project and that method is necessary, I will stick with the previous version of Realm. Thank you for your help.

**Comment by clementetb** [comment]
Those methods are not available in the previous version of Realm, how isn't it an issue?

**Comment by Huazhiling** [comment]
> Those methods are not available in the previous version of Realm, how isn't it an issue?
I don't know which methods you mentioned, is it directory() or name()? This was available in the previous version. I took a look at the code of this version. There is no Flow related, only rx, and the new version adds Flow.

**Comment by Huazhiling** [comment]
> Those methods are not available in the previous version of Realm, how isn't it an issue?

I don't know which methods you mentioned, is it directory() or name()? This was available in the previous version. I took a look at the code of this version. There is no Flow related, only rx, and the new version adds Flow.

**Comment by rorbech** [comment]
Hi @Huazhiling. It is a bit hard to understand the issue here. Seems like the original question was about `directory` and `name`. If you have other issues (upgrading, other APIs, etc.), please open a new issue with the exact description:
- What you are trying to achieve and how,
- What you expected, and
- What you are actually see with full stack traces, erroneous return values

Please include code and log snippets to make intention and observations more clear.
