### ISSUE TITLE
transformer-api 10.14.0 increases lib size significantly

### ISSUE THREAD

**Issue by ahmedre** [realm/realm-java#7803]
### How frequently does the bug occur?

-- select --

### Description

unzipping the apk, I am seeing ~1.x mb increase on each of the .so files.

transformer-api 10.13.0:

```
-rw-r--r--@ 1 ahmedre  staff   6.9M ./lib/arm64-v8a/librealm-jni.so
-rw-r--r--@ 1 ahmedre  staff   7.7M ./lib/x86/librealm-jni.so
-rw-r--r--@ 1 ahmedre  staff   8.1M ./lib/x86_64/librealm-jni.so
-rw-r--r--@ 1 ahmedre  staff   4.6M ./lib/armeabi-v7a/librealm-jni.so
```

transformer-api 10.14.0:

```
-rw-r--r--@ 1 ahmedre  staff   8.3M ./lib/arm64-v8a/librealm-jni.so
-rw-r--r--@ 1 ahmedre  staff   9.0M ./lib/x86/librealm-jni.so
-rw-r--r--@ 1 ahmedre  staff   9.6M ./lib/x86_64/librealm-jni.so
-rw-r--r--@ 1 ahmedre  staff   5.6M ./lib/armeabi-v7a/librealm-jni.so
```

### Can you reproduce the bug?

Always

### Version

10.14.0-transform

### What Atlas App Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

AGP 8

### Build environment

Android Studio version: Unrelated
Android Build Tools version: 8.0.0
Gradle version: 8.1

**Comment by ahmedre** [comment]
This isn't related to AGP 8 since the same delta can be observed when AGP is at 7.4.2. I am guessing this size change is intentional, but wanted to raise is in case it's not.

**Comment by cmelchior** [comment]
This is caused by the upgrade of OpenSSL to 3.* which is unfortunately significantly larger than 1.*. So it is intentional, albeit unfortunate.

**Comment by ahmedre** [comment]
Thank you - closing this.
