### ISSUE TITLE
App crashed after implementing dexguard

### ISSUE THREAD

**Issue by souravsoftwareer** [realm/realm-java#7812]
[realm-core-11.7.0] Assertion failed: m_method_id != nullptr with (method_name, signature) =  ["willSendNotifications", "()V"]
<backtrace not supported on this platform>!!! IMPORTANT: Please report this at https://github.com/realm/realm-core/issues/new/choose
2023-05-02 14:44:02.666 20849-20849 libc 
A  Fatal signal 6 (SIGABRT), code -1 (SI_QUEUE) 
io.realm:realm-gradle-plugin:10.9.0
This happens when dex guard implemented

**Comment by clementetb** [comment]
Hi, the function you are having issues with is annotated with `@keep` so it should be guarded automatically. It might be that dexguard is not processing these annotations. 

You might find useful this comment where a user applied its own dexguard configuration to fix a similar issue.

https://github.com/realm/realm-java/issues/7514#issuecomment-871361571
