### ISSUE TITLE
java.lang.ClassCastException: com.google.gson.internal.LinkedTreeMap cannot be cast to io.realm.RealmModel

### ISSUE THREAD

**Issue by sharawanan** [realm/realm-java#7814]
### How frequently does the bug occur?

Always

### Description

**Using Retrofit 2.9.0 and AGP 8.0.1** 

`java.lang.ClassCastException: com.google.gson.internal.LinkedTreeMap cannot be cast to io.realm.RealmModel
	at io.realm.DefaultRealmModuleMediator.insertOrUpdate(SourceFile:7121)
	at io.realm.Realm.insertOrUpdate(SourceFile:1367)`

### Can you reproduce the bug?

Always

### Version

10.15.1

### What Atlas App Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

Android

### Build environment

Android Studio version: ...
Android Build Tools version: ...
Gradle version: ...

**Comment by clementetb** [comment]
From the exception, it seems you are trying to insert an instance that is not a `RealmModel` but a `LinkedTreeMap`. 

Could you check that you are deserializing to the correct object type?

**Comment by rorbech** [comment]
@sharawanan Can you elaborate a bit on:
- How you model looks like, and 
- How the statement "the same code works on Retrofit ..." relates to all this. Did it work with a previous version or realm? Or what does that refer to?

**Comment by rorbech** [comment]
@sharawanan There is nothing in the model definition that catches the eye. From the stacktrace it seems like you are invoking the `insertOrUpdate(Collection<? extends RealmModel>)`-variant of `insertOrUpdate` so I assume your `userRoleMenusList` is just a list of `UserRoleMenus`. In that case it looks like our plugin might not have been applied. 

Is this code in your `main` source set or is it test/integration test code or are there some specials about your configuration?
Also just to be completely explicit and help troubleshooting, what is the exact type of `userRoleMenusList`?

**Comment by rorbech** [comment]
It is a bit difficult to hunt without the ability to debug, but there are a couple of concerns:
- `userRoleMenusList` is a global variable updated in an async task. Could you try to pass the value `saveuserRoleMenu` as an argument, so that you are absolutely certain that it is the response of an immediate request that is passed. 
- The requests are mapped into a `UserRoleWrapper`, so it is still not possible to reason about what is actually going on

Could you debug and inspect that the `userRoleMenusList` is in fact a non-null `UserRoleMenus`-collection when you see the error?

**Comment by DearDhruv** [comment]
It is not a Realm issue. 

It is related to gson due to Type Erasure. 

I have the same issue with my simple custom class, I am keeping my `androidGradlePlugin 7.4.2` for now.

**Comment by rorbech** [comment]
@sharawanan Have you been able to trace down what the root of this was? If not please share more details or a minimal project that shows the issue for us to try to debug it.

**Comment by JacobCube** [comment]
Same issue here with AGP 8.0.2. The issue gets resolved when downgrading to 7.4.2 with no code change.

**Comment by JacobCube** [comment]
This seems to solve the issue. 
Thank you.
