### ISSUE TITLE
Changes after deleteRealmFile() not persisted when app is re-opened

### ISSUE THREAD

**Issue by T-Spoon** [realm/realm-java#782]
It appears that my changes are not being saved to disk once I've called `deleteRealmFile()` and then saved new data.

Heres the code:

        Realm realm = Realm.getInstance(getApplicationContext());
        realm.close();
        Realm.deleteRealmFile(getApplicationContext());
        realm = Realm.getInstance(getApplicationContext());
        realm.beginTransaction();
        User u = new User();
        u.setName("JimBob");
        realm.commitTransaction();

Everything appears to be saved correctly. I can query and receive data. But if I kill the app and re-open, there is no data.  Perhaps somehow the data thinks it's getting written to the old realm file?

**Comment by bmunkholm** [comment]
You are sure that's not because you still have the old deleteRealmFile() code :-)?
How do you ensure that's not executed?
Could you share a testcase or app that can reproduce this behavior?

**Comment by T-Spoon** [comment]
Heh, quite sure :)

Here's an example project - https://www.dropbox.com/s/6awalixryz7d5uy/RealmDeleteDbExample.zip?dl=0

The delete & re-populate is done in the click listener in the title.  So you can manually control it.

**Comment by bmunkholm** [comment]
You are deleting the file while still keeping the realm open.
Deleting the file is only safe when there are no references to the realm.
Let us know if the docs could be better (http://realm.io/docs/java/0.78.0/api/io/realm/Realm.html#deleteRealmFile(android.content.Context))?

**Comment by T-Spoon** [comment]
Updated to close Realm before delete, and not keep any instance references to realm: https://www.dropbox.com/s/na4dhe91d0nvyd0/RealmDeleteDbExample2.zip?dl=0

Am I missing something here?  How should I go about doing this, if what the updated example does isn't correct?

**Comment by T-Spoon** [comment]
@bmunkholm Any update on this? If the code in the second example is correct, then I think this should be re-opened.

**Comment by bmunkholm** [comment]
Hey @T-Spoon : Do absolutely feel free to reopen issues. I don't see the closed ones :-( I'll check it.

**Comment by T-Spoon** [comment]
@bmunkholm Not to worry.  I don't think I can re-open issues I didn't close myself though, and I didn't want to spam the issues section with duplicates.

Thanks for looking into it!

**Comment by bmunkholm** [comment]
@T-Spoon Just for the test - could you try to reopen when I now close it? We normally always ask people to reopen - but if that doesn't work it would be good to know :-)

**Comment by T-Spoon** [comment]
@bmunkholm Doesn't look like I can unfortunately. See here: http://stackoverflow.com/a/21333938/1639040

**Comment by bmunkholm** [comment]
Thanks! Then it's kinda pointless of me asking people to do that :-) Thanks!

**Comment by bmunkholm** [comment]
@T-Spoon : You still hold a reference to the open realm file in your onCreate().
Each getInstance() needs a corresponding close(). It's ref-counted, so only the last close() will actually close the file. We should document that better I can see.

**Comment by T-Spoon** [comment]
@bmunkholm Ah, I see.  I didn't realize that.  My bad.  I'll test it out when I get home tonight.

Thanks for looking into it!  I'll re-open if I notice the issue persists.
