### ISSUE TITLE
Wrong sync error codes

### ISSUE THREAD

**Issue by josias-milkinteractive** [realm/realm-java#7823]
### How frequently does the bug occur?

Always

### Description

Some realm sync errors are reported with error code UNKNOWN which previously had a specific error code.
For example permission denied error was logged like this in realm 10.13.1:
`PERMISSION_DENIED(realm::sync::ProtocolError:206): Permission denied (BIND, IDENT, QUERY, REFRESH)`

In realm 10.16.0 it looks like this: 
`UNKNOWN(unknown:1999): Permission denied (BIND, IDENT, QUERY, REFRESH)`

The same happens for the the bad progress error:
realm 10.13.1: 
`CLIENT_BAD_PROGRESS(realm::sync::ClientError:107): Bad progress information (DOWNLOAD)`

realm 10.16.10: 
`UNKNOWN(unknown:1999): Bad progress information (DOWNLOAD)`

This breaks the error handling in our app.

### Can you reproduce the bug?

Always

### Reproduction Steps

Open a realm with a SyncConfiguration and an error handler which logs the errors.

### Version

10.16.0

### What Atlas App Services are you using?

Atlas Device Sync

### Are you using encryption?

No

### Platform OS and version(s)

Android 11, 13

### Build environment

Android Studio version: Electric Eel | 2022.1.1 Patch 2
Android Build Tools version: 33.0.1
Gradle version: 7.5

**Comment by clementetb** [comment]
Thanks for the report, we are investigating the issue.

**Comment by cmelchior** [comment]
We can reproduce this and are working on a fix.
