### ISSUE TITLE
Android - Realm plugin version v6.0.2 is not found during build

### ISSUE THREAD

**Issue by atul-vts** [realm/realm-java#7826]
### How frequently does the bug occur?

Always

### Description

Hi team,

We're using Realm plugin version 6.0.2 and we're getting an error while running the build via Fastlane that this repository is not found, while it's working locally on Android Studio.

Error:

> * What went wrong:
A problem occurred configuring root project 's'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find io.realm:realm-gradle-plugin:6.0.2.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/io/realm/realm-gradle-plugin/6.0.2/realm-gradle-plugin-6.0.2.pom
       - https://repo.maven.apache.org/maven2/io/realm/realm-gradle-plugin/6.0.2/realm-gradle-plugin-6.0.2.pom
       - https://jcenter.bintray.com/io/realm/realm-gradle-plugin/6.0.2/realm-gradle-plugin-6.0.2.pom
     Required by:
         project :

### Stacktrace & log output

```shell
> * What went wrong:
A problem occurred configuring root project 's'.
> Could not resolve all artifacts for configuration ':classpath'.
   > Could not find io.realm:realm-gradle-plugin:6.0.2.
     Searched in the following locations:
       - https://dl.google.com/dl/android/maven2/io/realm/realm-gradle-plugin/6.0.2/realm-gradle-plugin-6.0.2.pom
       - https://repo.maven.apache.org/maven2/io/realm/realm-gradle-plugin/6.0.2/realm-gradle-plugin-6.0.2.pom
       - https://jcenter.bintray.com/io/realm/realm-gradle-plugin/6.0.2/realm-gradle-plugin-6.0.2.pom
     Required by:
         project :
```

### Can you reproduce the bug?

Always

### Reproduction Steps

Add fastlane to the project, and run the command to build the app via the fastlane command. It'll throw an error immediately.

### Version

6.0.2

### What Atlas App Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

Android OS

### Build environment

Android Studio version:  Android Studio Flamingo | 2022.2.1 Patch 2
Gradle Version: 7.0.4
Kotlin Version: 1.7.21
Realm Version: 6.0.2

**Comment by asrieltiago** [comment]
We're also facing the same issue by using Realm 5.1.0 version.

Seems that JCenter Bintray is down, and those versions are not available in MavenCentral().
https://plugins.gradle.org/plugin/com.gmail.jfkudg.appreciate-aliyun-mirror

**Comment by MatheusLima1** [comment]
Hey man, we are facing the same issue here, we have a realm version 5.10 and we are using fastlane as well. 
In this link https://status.gradle.com/ we can check that JCenter is now redirecting to Maven Central instead of serving artifacts.

**Comment by alexdpayne** [comment]
I'm using 6.1.1 same issue.

**Comment by mleung-code** [comment]
Same issue with 4.3.3

**Comment by rav-ctrl** [comment]
Same issue with 6.1.1

**Comment by alexdpayne** [comment]
Looks like it's back online again.

https://status.gradle.com/incidents/7x4wqd7zv715

**Comment by MatheusLima1** [comment]
oh, good to know

**Comment by atul-vts** [comment]
> Looks like it's back online again.
> 
> https://status.gradle.com/incidents/7x4wqd7zv715

It's working now!
