### ISSUE TITLE
Can I use realm-java to generate `.realm` files only on the Java backend? 

### ISSUE THREAD

**Issue by AAChartModel** [realm/realm-java#7836]
### Problem

Is it possible to achieve this without relying on Android?  
Because I want to generate a `.realm` file through the **Java server** and allow the mobile end to download the `.realm` file directly.

### How important is this improvement for you?

-- select --

### Feature would mainly be used with

-- select --

**Comment by rorbech** [comment]
Hi @AAChartModel. It is not possible to run Realm Java outside an Android environment. But realm files are the same across all SDKs so you could use any other SDK to generate the file. However, care should be taken to define the models completely identical if you use different SDKs on the server and mobile. 

Realm Kotlin (https://github.com/realm/realm-kotlin) has multi-platform support and runs in JVM desktop environments (along with Android and Darwin), so you could use that across your mobile and server implementation, to utilize the same code across environments. Or just from you server if you can't migrate the mobile SDK at the moment.
