### ISSUE TITLE
findAllSorted with link queries

### ISSUE THREAD

**Issue by tspecht** [realm/realm-java#784]
Will there be support for findAllSorted to be usable with link queries, e.g. access a field of a linked model inside the field name provided to findAllSorted?

**Comment by kneth** [comment]
It sounds like a good idea. It is not as trivial as it sounds, so it will take a while before we get to it but I'll add it to the list on proposed enhancements.

**Comment by beeender** [comment]
dup to #672 and will be implemented by #3834.
