### ISSUE TITLE
Replace Kapt to Ksp 

### ISSUE THREAD

**Issue by Kolyall** [realm/realm-java#7846]
When Kapt will be replaced to Ksp ?
https://github.com/realm/realm-java/blob/a5a0dd369d73252cee61315e0bd27f439d681af4/gradle-plugin/src/main/kotlin/io/realm/gradle/Realm.kt#L52

**Comment by rorbech** [comment]
Hi @Kolyall, thanks for the report. We already have an issue tracking the potential task of migrating to KSP. There are no immediate plans to do so though. You can monitor it https://github.com/realm/realm-java/issues/7310#issuecomment-1165289316 to track future updates.
