### ISSUE TITLE
Last two releases missing from Maven Central

### ISSUE THREAD

**Issue by Myvillithdar** [realm/realm-java#7852]
### How frequently does the bug occur?

Always

### Description

CHANGELOG.md shows that 10.16.2 and 10.17.0 were released last week, but it looks like the latest version available from Maven Central is 10.16.1.

### Can you reproduce the bug?

Always

### Version

10.16.2 and 10.17.0

### What Atlas App Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

https://central.sonatype.com/artifact/io.realm/realm-gradle-plugin/versions

### Build environment

Android Studio version: Giraffe | 2022.3.1 Patch 2
Android Build Tools version: 8.1.2
Gradle version: 8.3

**Comment by rorbech** [comment]
Hmm, that looks weird ... the publishing did succeed. Will investigate. Thanks for the report.

**Comment by clementetb** [comment]
Thanks for the report @Myvillithdar. It looks like the releases didn't go fully through. We have republished both versions.

Although they might not show in the web browser they are already available. Could you confirm you have access to them?

**Comment by Myvillithdar** [comment]
Yes, I'm able to access both versions now.  Thank you for the quick turnaround!
