### ISSUE TITLE
Newly Added Field in Realm Getting Null

### ISSUE THREAD

**Issue by rahul-kumawat-vts** [realm/realm-java#7857]
### How frequently does the bug occur?

Always

### Description

In my project i have a RealmObject() class, I have added a new field in that class and install the fresh application in my phone but i am getting null value of newly added fields from Database. Can you please let me know why this issue happen.

Realm Version Using - io.realm:realm-gradle-plugin:10.16.0

### Stacktrace & log output

```shell
No exception and error logs in logcat
```

### Can you reproduce the bug?

Always

### Reproduction Steps

1. Already create RealmObject Class
2. Add a New Field
3. Run the application in any new device
4. Getting null value from Realm database table.

### Version

10.16.0

### What Atlas App Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

Android OS -12

### Build environment

Android Studio version: Android Studio Flamingo | 2022.2.1 Patch 2
Android Build Tools version:  com.android.tools.build:gradle:7.4.2
Gradle version: gradle-7.5

**Comment by rorbech** [comment]
This sounds a bit like #7840 where incremental build was failing to trigger regeneration of all accessors correctly. Could you give it a try with the latest release?
