### ISSUE TITLE
Is there a reason RealmTransformerTask isn't cacheable?

### ISSUE THREAD

**Issue by oheyadam** [realm/realm-java#7858]
### Problem

`RealmTransformerTask` is on the critical path for us, but it's not cacheable according to our build scans. Is there a reason for that?

### Solution

Would it be possible to make this task cacheable, or is there a reason it's not?

### How important is this improvement for you?

Would be a major improvement

### Feature would mainly be used with

Local Database only

**Comment by rorbech** [comment]
What exactly is reported to be the issue? I have tried to enable configuration caching in a sample project and it does work. Maybe related to specific versions of Gradle, AGP and realm. 

Could you supply a reproducing project or try to fill in the information of the actual reported observation (stack trace, build/scan error, etc.) and the Gradle, AGP and Realm versions, etc. corresponding to the info requested in this form https://github.com/realm/realm-java/issues/new?assignees=&labels=T-Bug&projects=&template=bug.yml

**Comment by oheyadam** [comment]
Hey @rorbech, yea sorry my bad for not providing more information. Here's a screenshot from our build scan and you can see Gradle says this task doesn't have caching enabled. It's one of our longest running tasks as well. 

We do have configuration cache enabled, and that works as you described, but configuration cache is different from the build cache. To make a task build-cacheable, you annotate it with the `@Cacheable` [annotation](https://docs.gradle.org/current/javadoc/org/gradle/api/tasks/CacheableTask.html). More docs [here](https://docs.gradle.org/current/userguide/build_cache.html). Sorry if you're already aware of all of this, not trying to over-explain things--just thought I'd send links.

We're running Android Studio Giraffe v2022.3.1, patch 4, Gradle v8.4, AGP v8.1.4 and realm-gradle-plugin v10.16.1.

<img width="906" alt="SCR-20231122-jrks" src="https://github.com/realm/realm-java/assets/18615546/0639f8f1-03e0-40c6-9a34-4a88daf6354d">

**Comment by oheyadam** [comment]
Yep, absolutely. Thank you very much!
