### ISSUE TITLE
How to update a row in Realm db

### ISSUE THREAD

**Issue by somghosh** [realm/realm-java#786]
What is the method for updating an existing row in Realm? There were no clear code /instructions in the docs

My realm writing code is here, there should always be only one row in ACCOUNT_DATA_DB.
I find this row, and extract it as a variable and then modify the properties of that variable and commit.

Does this work, or should I be cleanly deleting the row and set it from scratch by creating a new variable again

Thanks

	Realm realm = Realm.getInstance(App.this, ACCOUNT_DATA_DB);
	RealmResults<AccountData> accountDataRes = realm.where(AccountData.class).findAll();

	realm.beginTransaction();       // start writing to database
	AccountData userData = accountDataRes.first();      //= last(), its the same, since 1 row only

	if(BuildConfig.DEBUG && !(accountDataRes.size() == 1))
		throw new RuntimeException();
	newMePageInfo.setDBRowFromPojo(userData, realm);        // writes newly fetch user info, feeds, points into account data db

	realm.commitTransaction();
	
## The writing function is here

	public void setDBRowFromPojo(AccountData x, Realm realm) {
	x.setTimeCreated(this.getTimeCreated());
	x.setFirstName(this.getFirstName());
	x.setLastName(this.getLastName());
	x.setLocationCity(this.getLocationCity());
	x.setAge(this.getAge());
	x.setGender(this.getGender());
	x.setImage(this.getImage());
	
}

**Comment by cmelchior** [comment]
Hi @somghosh 
When you have reference to an object, any changes are "updates" that will be reflected inside the Realm, so you got the right idea. Note that there is also a .findFirst() method that could simplify your code:

```
Realm realm = Realm.getInstance(App.this, ACCOUNT_DATA_DB);
AccountData userData = realm.where(AccountData.class).findFirst();

realm.beginTransaction();       // start writing to database
if(BuildConfig.DEBUG && userData != null)
    throw new RuntimeException();
newMePageInfo.setDBRowFromPojo(userData, realm);        // writes newly fetch user info, feeds, points into account data db
realm.commitTransaction();
```

**Comment by cmelchior** [comment]
@somghosh I assume the above answered your question. Please feel free to reopen if that is not the case.
