### ISSUE TITLE
Reduce SO source file size

### ISSUE THREAD

**Issue by AndrewChupin** [realm/realm-java#7867]
### Problem
I'm using Realm in Android app and I see that average size per CPU is about 3MB, is it possible to reduce it less than 1 mB?
Custom SQLite build takes about 300 KB for me.

![](https://github.com/realm/realm-java/assets/15245196/46d853f1-3cd1-42b4-a8f7-bf4c641f875f)

### How important is this improvement for you?
I would like to have it but have a workaround

### Feature would mainly be used with
Local Database only

**Comment by nirinchev** [comment]
We're continuously evaluating ways to reduce the file size - typically once or twice a year we'll do a binary analysis and investigate if there are opportunities for file size reduction. SQLite and Realm have inherently different features, so it wouldn't be an apples-to-apples comparison if we compare their file sizes directly as a lot of SQLite functionality is provided as extensions. Realm has adopted a "batteries included" approach, which has both benefits and drawbacks, but we believe it's the right choice. We don't have immediate plans to do a filesize  investigation and even when we do, it's highly unlikely that we'll be able to reduce the size to below 1 MB.
