### ISSUE TITLE
* What went wrong: Execution failed for task ':ERemittance:kaptDebugKotlin'. > A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptWithoutKotlincTask$KaptExecutionWorkAction    > java.lang.reflect.InvocationTargetException (no error message)

### ISSUE THREAD

**Issue by morarafrank** [realm/realm-java#7868]
### How frequently does the bug occur?

Always

### Description

Added new kotin standart library to one module: 
Here: implementation "org.jetbrains.kotlin:kotlin-stdlib:1.7.22"

### Stacktrace & log output

```shell
* What went wrong:
Execution failed for task ':ERemittance:kaptDebugKotlin'.
> A failure occurred while executing org.jetbrains.kotlin.gradle.internal.KaptWithoutKotlincTask$KaptExecutionWorkAction
   > java.lang.reflect.InvocationTargetException (no error message)
```

### Can you reproduce the bug?

-- select --

### Version

33

### What Atlas App Services are you using?

Both Atlas Device Sync and Atlas App Services

### Are you using encryption?

No

### Platform OS and version(s)

Windows OS

### Build environment

Android Studio version: ... HedgeHog 2023.1.1
Android Build Tools version: ... 7.2.1
Gradle version: ... 7.3.3

**Comment by nirinchev** [comment]
What version of the Realm Java SDK are you using? And can you reproduce this in an isolated project that we can use to diagnose the issue?
