### ISSUE TITLE
May I ask which example would be better for Android Java project reference?

### ISSUE THREAD

**Issue by mynameispp** [realm/realm-java#7874]
Dear experts，May I ask which example would be better for Android Java project reference?

**Comment by nirinchev** [comment]
If you're looking to use Realm in an Android application, our recommendation would be to use the [Realm Kotlin SDK - it adds many improvements on top of the Java SDK and is under more active development. You can find multiple samples using the Kotlin SDK in our [samples repo](https://github.com/realm/realm-kotlin-samples).
