### ISSUE TITLE
[realm-core-12.3.0] Assertion failed: false

### ISSUE THREAD

**Issue by jalen-ma** [realm/realm-java#7877]
#### SDK and version
SDK : java realm-core-12.3.0
Version: 12.3.0

#### Observations
i dont not the step, user crashes while using the app。

#### Crash log / stacktrace
backtrace:
    #00 pc 000000000007066c  /apex/com.android.runtime/lib64/bionic/libc.so (abort+160)
    realm/realm-core#1 pc 000000000066d55c  /data/app/com.demo.eh-9zyvbbrKmFJvAIcxvAHXjw==/lib/arm64/librealm-jni.so
    realm/realm-core#2 pc 000000000066d858  /data/app/com.demo.eh-9zyvbbrKmFJvAIcxvAHXjw==/lib/arm64/librealm-jni.so
    realm/realm-core#3 pc 000000000066d694  /data/app/com.demo.eh-9zyvbbrKmFJvAIcxvAHXjw==/lib/arm64/librealm-jni.so
    realm/realm-core#4 pc 00000000003c64b8  /data/app/com.demo.eh-9zyvbbrKmFJvAIcxvAHXjw==/lib/arm64/librealm-jni.so
    realm/realm-core#5 pc 00000000000d2578  /apex/com.android.runtime/lib64/bionic/libc.so (__cxa_finalize+212)
    realm/realm-core#6 pc 00000000000cdf60  /apex/com.android.runtime/lib64/bionic/libc.so (exit+24)
    realm/realm-core#7 pc 0000000000557828  /data/app/com.demo.eh-9zyvbbrKmFJvAIcxvAHXjw==/lib/arm64/libflutter.so
    realm/realm-core#8 pc 00000000005591b8  /data/app/com.demo.eh-9zyvbbrKmFJvAIcxvAHXjw==/lib/arm64/libflutter.so
    realm/realm-core#9 pc 000000000062da0c  /data/app/com.demo.eh-9zyvbbrKmFJvAIcxvAHXjw==/lib/arm64/libflutter.so
    realm/realm-core#10 pc 000000000062d864  /data/app/com.demo.eh-9zyvbbrKmFJvAIcxvAHXjw==/lib/arm64/libflutter.so
    realm/realm-core#11 pc 00000000000044fc  /data/app/com.demo.eh-9zyvbbrKmFJvAIcxvAHXjw==/lib/arm64/libapp.so (_kDartVmSnapshotInstructions+9468)

01-25 15:23:44.968 22446 22649 E REALM   : /tmp/realm-java/realm/realm-library/src/main/cpp/jni_util/jni_utils.cpp:54: [realm-core-12.3.0] Assertion failed: false
01-25 15:23:44.968 22446 22649 E REALM   : <backtrace not supported on this platform>!!! IMPORTANT: Please report this at https://github.com/realm/realm-core/issues/new/choose

#### Steps & Code to Reproduce
i dont not the step

**Comment by kneth** [comment]
@jalen-ma 

It is similar to https://github.com/realm/realm-java/issues/6987.

How often does it happen? Any particular operation which triggers it?
