### ISSUE TITLE
Realm.Init configuration take too long delay when move intent from 1st page into next page 

### ISSUE THREAD

**Issue by michaelsof47** [realm/realm-java#7881]
### How frequently does the bug occur?

Always

### Description

I was try to move into next page which in second page of activity. I was used Realm.Init to initialize of realm. But, it takes too long delay when move from 1st page into 2nd page. I'm also try Realm Init call from 1st Activity or Realm Init run inside of runOnUIThread(). but, it doesn't work well.

### Stacktrace & log output

```shell
2024-03-21 14:50:29.656  4240-4240  data_check  xxx.xxxx.xxx.xxx         D  first access realm init
2024-03-21 14:50:30.012  4240-4240  data_check  xxx.xxxx.xxx.xxx         D  add category of product
2024-03-21 14:50:30.559  4240-4240  data_check  xxx.xxxx.xxx.xxx         D  add product
```

### Can you reproduce the bug?

Always

### Reproduction Steps

1. Access First Page. 
2. Access Second Page After Page was positioned offline mode

### Version

10.15.1

### What Atlas App Services are you using?

Local Database only

### Are you using encryption?

No

### Platform OS and version(s)

One UI v.5.1, Android 13

### Build environment

Android Studio version:  2023.2.1 Patch 1
Android Build Tools version: 33.0.0
Gradle version: 8.0.0

**Comment by kneth** [comment]
It will be helpful if you can share a project which can reproduce it. In particular, we are interested in understand:

> Access Second Page After Page was positioned offline mode

Are you following https://www.mongodb.com/docs/atlas/device-sdks/sdk/java/sync/partition-based-sync/#std-label-java-open-a-synced-realm-while-online?
