### ISSUE TITLE
Custom machines ignore some cpu architectures

### ISSUE THREAD

**Issue by Huazhiling** [realm/realm-java#7884]
### Problem

I am running the realm database on a custom machine and the architecture is v8a, is there any way to not package other architectures so?

### How important is this improvement for you?

I would like to have it but have a workaround

### Feature would mainly be used with

Local Database only

**Comment by kneth** [comment]
[NDK abifilters](https://developer.android.com/ndk/guides/abis) should still work.

**Comment by Huazhiling** [comment]
@kneth thanks
