### ISSUE TITLE
A/libc﹕ Fatal signal 7 (SIGBUS) 

### ISSUE THREAD

**Issue by ousenko** [realm/realm-java#790]
That's an error I receive time after time. Any idea what could be the reason?

01-24 18:24:06.278    8724-8814/** E/UpdaterService﹕ realm successfull transaction
01-24 18:25:06.198    8724-8959/** A/libc﹕ Fatal signal 7 (SIGBUS) at 0x547ad78c (code=2)

**Comment by emanuelez** [comment]
Hello Andrew,
I'm afraid this is way too little information for us to be able to help you. Would you mind providing more details?
In the [README file](https://github.com/realm/realm-java/blob/master/README.md) we provide a template to help with that :smiley:

**Comment by ousenko** [comment]
It seems like I've tracked down the issue. I am (occasionally) starting 

`Realm.compactRealmFile(context)`

when there's still at least one Realm instance open. When I commented this line, the crash disappeared.

Unimportant Details:
I have set a limitation on my Activities and Fragments: 
- an abstract [RealmActivity](https://gist.github.com/ousenko/cc7ac155ea55bac2782c) which basically holds Realm instance and handles it's lifecycle (*see commented line for crash reason*)
- hosted [RealmFragment](https://gist.github.com/ousenko/77b7fc2a9811acd55fb0) may then access parent Activity's realm instance without  opening or closing it again

That's kind of performance optimisation in my Navigation Drawer pattern implementation.
And the error comes up when I am returning from DetailActivity to MasterActivity, because the file is attempted to be compacted in DetailActivity.onDestroy() while 1 realm instance is open at MasterActivity.

**P.S.** I would  appreciate any hint on how to have exactly one Realm instance per thread, for example, 1 instance for UI thread. Reference counting and mapping thread to realm instance?

**Comment by emanuelez** [comment]
Realm instances are already a thread singletons, meaning that if you can `Realm.getInstance(someContext)` twice (or more) in a thread, it will actually always return the same instance.

One question: why are you trying to compact the Realm file so often? Did you notice any size issues?

**Comment by ousenko** [comment]
Each time I start my application, I start update service. It downloads actual data from webserver and replaces all the previous data with it.

At first the data size is 1.5 mb, after a few updates it becomes 5.5mb, though total object count stays the same. I understand it's normal for realm file to grow in such case, but is there any limit on the fragmentation growth? 
**P.S.** I see the size is stabilised at 5.5mb in my case upon further calls.

**Comment by emanuelez** [comment]
That is correct and expected behavior. Right now Realm files will not shrink in size even if you delete all the data contained in it, but it will reuse that space efficiently when needed.
