### ISSUE TITLE
Getting children from a link query

### ISSUE THREAD

**Issue by mpost** [realm/realm-java#792]
I am facing a query which i can not fully implement. The idea is to query for a list of child objects that match a certain criteria. Imagine the following classes:

<pre lang="java">
class Person extends RealmObject {
  private List&lt;Shirt&gt; shirts;
}
class Shirt extends RealmObject {
  private int color;
}
</pre>

Now i want to get _a list of shirts from a certain person where the shirt color is green_ (<code>0xff00ff00</code>). I do know which person i am looking at.

How would i go about to implement such a query? My first attempt was to loop over the shirts myself, but in my app i repeat this check very often which leads to a lot of memory consumption and eventually to an <code>OutOfMemoryError</code>.

**Comment by emanuelez** [comment]
Hello Moritz,
what you are asking for here is what we call back-links. The Realm core actually implements this already, but it doesn't expose it in the query engine so bindings cannot use it yet.
That being said, right now, the only way to do the query you request is to add the inverse relationship in your model classes and manage it manually.

This is of course very cumbersome so we're thinking about providing some facility to let the user define the name of the inverse relationship, letting Realm do all the book-keeping.

**Comment by mpost** [comment]
Thanks for your answer i thought about the bidirectional mapping as well but though/hopped that there would be a better way. Looking forward to any build in support in the future.

**Comment by mpost** [comment]
Following up on the idea of the bidirectional mapping, would that be properly handled when doing to and from json conversion?

**Comment by emanuelez** [comment]
Not with the manual backlinking, but with the automatic one it would probably be possible. It depends on some design decisions we're gonna take, but backlinking ability will be a major contributing factor in such decision.

**Comment by mpost** [comment]
Ok, i am looking forward to that until than i'll work around the query problem.

**Comment by alexustinovsm** [comment]
Have you added back-links?

**Comment by cmelchior** [comment]
Not yet. You can follow the progress here: #607

**Comment by cmelchior** [comment]
Folding this into #607
