### ISSUE TITLE
Got TimeoutException 

### ISSUE THREAD

**Issue by ImGauravC** [realm/realm-java#801]
```java
java.util.concurrent.TimeoutException: io.realm.internal.Table.finalize() timed out after 10 seconds
       at io.realm.internal.Table.finalize(Table.java:134)
       at java.lang.Daemons$FinalizerDaemon.doFinalize(Daemons.java:187)
       at java.lang.Daemons$FinalizerDaemon.run(Daemons.java:170)
       at java.lang.Thread.run(Thread.java:841)

**Comment by cmelchior** [comment]
Hi @ImGauravC 
Realm currently uses finalisers to free native resources when possible. However Java finalisers are notoriously slow and unpredictable, which means that if you iterate over a lot of RealmObjects, the finaliser thread might not be able to keep up, resulting in either OOM or timeouts as the above.

If you have patterns like this in your code:

```
RealmResults all = realm.allObjects(Foo.class);
for (Foo obj : all) {
            sum += obj.getValue();
}
```
that you call very frequently (eg. as part of an animation), you will create lot of garbage objects in both Java and native code.

RealmResults has a lot of aggregate functions like ```sum()```, ```min()```, ```max()``` and ```avg()``` that helps avoid problems like this, but if you have any other use cases we would like to hear about them.

We have it on our roadmap to replace finalisers with a more robust concept, which will eliminate this problem, but for now you will most likely have to find these places in your code and try to see if they can be written in a more efficient way.

**Comment by cmelchior** [comment]
Hi @ImGauravC 
I assume your question got answered. Feel free to add additional info if that is not the case.
