### ISSUE TITLE
how to solve RealmMigrationNeededException?

### ISSUE THREAD

**Issue by nhduc296** [realm/realm-java#805]
Hi Realm dev team,

I got this exception after upgrade my schema, I found an example here

https://github.com/realm/realm-java/blob/master/examples/migrationExample/src/main/java/io/realm/examples/realmmigrationexample/MigrationExampleActivity.java

BUT: where are my realm file (***.realm) locate?

I add this line to onCreate, but it doesn't work.

Realm.deleteRealmFile(this);

I think we should add more information  about this problem in tutorial

**Comment by nhduc296** [comment]
I have no idea when I close intelliJ IDEA and open my project again. It's work.

But I recommend to add an advice add deleteRealmFile in to doccument
Realm.deleteRealmFile(this);

**Comment by cmelchior** [comment]
Hi @nhduc296 

Your Realm files are placed under ```/data/data/<packagename>/files```.

Calling ```Realm.deleteRealmFile(this)``` will not work if you have opened your Realm at that point. We are adding a check to this method that will warn you if not done correctly. See here: https://github.com/realm/realm-java/pull/787. It should be part of our next release.

**Comment by cmelchior** [comment]
Hi @nhduc296 
I assume your question got answered. Feel free to add additional info if that is not the case.

**Comment by nhduc296** [comment]
Hi @cmelchior 
Root cause of this issue is IntellJ IDEA doesn't get my latest source code when it compile.
