### ISSUE TITLE
Thorough migration explanation needed

### ISSUE THREAD

**Issue by Den-Rimus** [realm/realm-java#807]
We are almost at release state with our project now, and I'm worried about future database structure changes that we will definitely face.

I tried to do a simple thing: add a boolean field isSharedToInstagram to a Photo model (I really do need that fix now, though I can ignore migration and just tell everybody in team to re-install app for further developing-testing. But I want to try migration). I'm aware that current API is cumbersome and will be change, but no rocket science here - just adding a field so far.

So, in Application's onCreate I do

```java
try {
            Realm.getInstance(this);
        } catch (RealmMigrationNeededException e) {
            Log.i(TAG, e.getClass().getSimpleName() + " was raised");

            RioHelper.migrateRealm(this);
        }
```

RioHelper now needs to do something like `Realm.migrateRealmAtPath(path, new RioMigration());`, but trouble here is that I'm totally not getting that `path` obtaining mechanism that you show in [example](https://github.com/realm/realm-java/blob/master/examples/migrationExample/src/main/java/io/realm/examples/realmmigrationexample/MigrationExampleActivity.java) :

```java
copyBundledRealmFile(this.getResources().openRawResource(R.raw.default0), "default0");
```

I don't have anything in raw and I'm not getting why is "default0" provided as second parameter...

Can you give an example of Realm.migrateRealmAtPath for project, where we always obtain realm by Realm.getInstance(someContextObject) (I assume it will be named "default.realm" then - I see that from Realm source code) and we don't have a clue where the file is stored?

Also, I have another question - about db versioning.
Say we have an app 1.0, we install it to device1. Realm version there is 0. We release update 1.01 (add a field "age"). We update app on device1, we catch exception and make a migration. Realm version becomes 1.
We install updated app version 1.01 on device2. Realm version is 0.
We release update 1.02 (remove field "middleName").

On device1 after update to 1.02 everything goes fine - it performs only second migration - from db v.1 to db v.2. and removes field.
On device2 I'd say a trouble will occur: it already has field "age", but db version is 0 - it will try to update and create field "age" again, no?

Maybe I'm not getting something or missed some documentation about migration, but how can we specify db's version after clean app install on device, if we wan't it to be something other than "0"?

**Comment by cmelchior** [comment]
Hi @Den-Rimus 

The ```copyBundledRealmFile()``` just copies a already populated Realm file from the resource folders to the filesystem so it can be used. The 2nd parameter is the name of the Realm file.

The ```context``` parameter in ```Realm.getInstance(context)``` is used to call ```context.getFilesDir()``` which usually is ```/data/data/<packagename>/files/```. To migrate a "default.realm" file you would thus use the following:

```
Realm.migrateRealmAtPath(new File(context.getFilesDir(), "default.realm"), realmMigration);
```

The current migration API still needs a lot of work, so versioning is not supported very well atm. Right now the only way to set a version larger than zero is to use a Migration, so you would need to perform a empty migration on new installs that returns the version.

eg.
```
if (newInstall) {
    Realm.migrateRealmAtPath(new File(getFilesDir(), "default.realm"), new RealmMigration() {
        @Override
        public long execute(Realm realm, long version) {
            return 5; // latest version
        }
    });
}
```

**Comment by Den-Rimus** [comment]
Great!

Thanks for your time!
