### ISSUE TITLE
Automatic OR for equalTo and contains

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#809]
Instead of having to iterate over a query to manually OR together RealmQuery.equalTo() and RealmQuery.contains() if it has multiple matches, we could easily change the API to take multiple inputs and make the queries easier to make.

Eg. change API methods to:

```
RealmQuery.equalTo(String fieldName, String... values)
RealmQuery.contains(String fieldName, String... values)
```

Which would change queries like:

```
where(Foo.class).equalTo("field", "bar").or().equalTo("field", "baz").findAll()
```

to 

```
where(Foo.class).equalTo("field", "bar", "baz").findAll()
```

Related to #841

**Comment by emanuelez** [comment]
That would be confusing. What we need is `any()`, `all()`, `containsAny`, `containsAll`, etc. instead IMO.

**Comment by cmelchior** [comment]
Much better idea :)

**Comment by spl** [comment]
Here's a suggestion for a slightly different naming scheme that would be more consistent with `equalTo()`: `equalToAny()`, `equalToAll()`.

But does `all()`/`equalToAll()` make sense as a logical conjunction for one field? If values are different, then, by definition, the query would be empty.

**Comment by anggrayudi** [comment]
If we use MySQL syntax would be like this:
````mysql
SELECT * FROM table_name
WHERE field_name IN('John', 'Nicko', 'Ryan');
````

So when we use it in realm query:
````java
realm.where(People.class).matches(field_name, 'John', 'Nicko', 'Ryan').findAll();
````

I think `matches(String fieldName, String... values)` query is better than `equalTo(String fieldName, String... values)`.

**Comment by cmelchior** [comment]
`in()` was added in 1.2, so I'll close this issue.
