### ISSUE TITLE
Document using ANT with Realm

### ISSUE THREAD

**Issue by fairysword** [realm/realm-java#815]
I did not find documentation about this

**Comment by emanuelez** [comment]
Hello.
Do you mean from the command line and not from Eclipse?

**Comment by fairysword** [comment]
Yes

**Comment by fairysword** [comment]
Some documentation like this
https://github.com/excilys/androidannotations/wiki/Building-Project-Ant

**Comment by fairysword** [comment]
Also, there is some documentation about proguard?

**Comment by emanuelez** [comment]
As for proguard you can find some info here: https://groups.google.com/forum/#!msg/realm-java/umqKCc50JGU/gi7Bm3VCndIJ

Basically this is what you need:

```
-keep class io.realm.** { *; }
-dontwarn javax.**
-dontwarn io.realm.**
```

As for Ant, we haven't tried yet, but I would be surprised if it was much different from the instructions you linked. I will try to find some time to setup an Ant example project and document my findings.

**Comment by bmunkholm** [comment]
Not a priority.
