### ISSUE TITLE
Not getting data on background Thread

### ISSUE THREAD

**Issue by gpulido** [realm/realm-java#820]
I'm accessing a shared realm instance on all the "UI-thread methods".
I have a BaseActivity with
```java
Realm realm;
 @Override
    protected void onCreate(Bundle savedInstanceState) {
        super.onCreate(savedInstanceState);
        realm = Realm.getInstance(this);
}

  @Override
    protected void onDestroy() {
        super.onDestroy();
        realm.close();
    }
```
And a method to access the realm from child fragments:
```java
 public Realm getRealm()
 {
     return realm;
}
```
I have also a BaseFragment that have a method:
```java
 protected Realm getRealm()
 {
    return ((BaseActivity)getActivity()).getRealm();
 }
```
I can populate with base data and a access the data correctly from the ui-thread. 

However I have a fragment that extends BaseFragment, that I want to access the data on a background thread so as the documentation says, I create a new instance of Realm:
```java
 public void loadBackgroundData() {       
             for(Round round: getRealm().where(Round.class).findAll()) {
//            THIS HAS DATA
            }
          new Thread(new Runnable() {
            @Override
            for(Round round: Realm.getInstance(getActivity()).where(Round.class).findAll()) {
//             THIS DOESN'T HAVE DATA
            }
        }).start();
    }
```
(Round is a RealmObject)
What I'm missing here? Am I doing something wrong?
Thank you in advance.

**Comment by emanuelez** [comment]
Hello Gabriel,

you don't say anything about where your data is written from. The data won't be available to other threads until is it committed.

**Comment by gpulido** [comment]
Hello,
I have a MainActivity extends BaseActivity where it creates some data between a 
realm.beginTransaction();
realm.commitTransaction();

Those are executed on the OnCreate of the MainActivity (that is the entry point for the app)

**Comment by emanuelez** [comment]
That doesn't sound right... is there any way for you to share the failing code, even in a private way?

**Comment by gpulido** [comment]
Hello,
I have added the same mechanism to a "basefragment" so, instead of using the BaseActivity realm on the fragments, I use the realm created on the basefragment, and now when I use a specific new realm on the non-ui thread It works, so it was my problem (although I still don't know why the other way doesn't worked)

Now I'm having the problem of not being able to move "RealmObjects" from thread to thread (as it is already documented)
This force me to ask realm for each object any time I need it. I can refactor to pass an unique id instead of the RealmObject instance, and retrieve from realm the realmobject each time I need it, but if I now that the data doesn't change, it seems very inefficient, isn't it?
Also the absence of an automatic unique id makes this a little cumbersome. 
Are you going to release the version with the ids soon? (just to wait)

Thank you
Gabriel

**Comment by emanuelez** [comment]
Yes Gabriel, that is the correct way to do it and yes, primary keys are coming soon!
You can follow the progress here #565

**Comment by emanuelez** [comment]
Closing this. Please contact us in case you need more help!
