### ISSUE TITLE
Realm in different app versions

### ISSUE THREAD

**Issue by Bruno-Furtado** [realm/realm-java#831]
Hello,

My application has a silenty login at the application entry.
This login information is saved in the realm.

Everytime I create a new version of the application some users complain that they can no longer perform this login and the app closes.

I tried to find a solution looking for in the log but it was not possible.

It is possible that this error is occurring in the realm due to version change? 
(I'm not changing the database model).

**Comment by cmelchior** [comment]
As long as you are not changing your model classes, any updates you make to the app should not cause Realm to crash. If you change any of your model classes you should see a RealmMigrationNeededException in your logs.

Without any code or stacktrace it is hard to say what is going wrong, can you post the logic where you do the login?

**Comment by Bruno-Furtado** [comment]
@cmelchior,
It's hard to explain because the situation itself involves the application logic.

In short some users are having problems. 
They note that when entering the application it's a hung time and closes.

Have you ever seen a situation like this?
This same failure occurs on iOS and Android with some users.

**Comment by cmelchior** [comment]
Without any sort of stack trace, program code or reproducible test project I cannot give you any qualified answer, sorry. 

If your application hangs, it could be related to your doing write transactions on both the UI thread and in a background thread. Writes block each other, so if you have a long write in the background and do a write on the UI thread you can risk getting ANR errors.

**Comment by Bruno-Furtado** [comment]
@cmelchior,
Thanks and sorry for questions.
