### ISSUE TITLE
Drop Schema instead of migrating.

### ISSUE THREAD

**Issue by kenticus** [realm/realm-java#834]
In some Applications it is not necessary to migrate data from version to version. Since my data needs to be refreshed every time they open my Android app it would be a time saver if i could just drop my schema and let Realm generate a new DB when the versions change....instead of spending a lot of time updating models. (I have 80+ models that change somewhat frequently since we are in the early versions of our app)

**Comment by cmelchior** [comment]
You can, just use the method below before opening any Realm instance.
```
Realm.deleteRealmFile(getContext())
```

That will delete the database file and just whatever schema you have defined by you classfiles when you open the Realm.

**Comment by kenticus** [comment]
Sweet! Might I suggest then adding this to the "Migrations" section on the website docs?
You just saved me about 2-3 hours today :)

**Comment by cmelchior** [comment]
Yes, that would probably be a good idea. Thanks

**Comment by cmelchior** [comment]
I have updated the migration documentation with a note about this.

**Comment by kkmike999** [comment]
I just need To drop one table, but don't affect other tables. How to do?

**Comment by benmorrow** [comment]
I also need to drop one table. There seems to be [a way to do it in Java](https://github.com/realm/realm-java/issues/1382#issuecomment-205333334), but not in Swift. Is that correct?

**Comment by jaymoh** [comment]
@kkmike999  hi, did you find a solution?

**Comment by Zhuinden** [comment]
Just use a migration

**Comment by kkmike999** [comment]
@jaymoh i have not used realm for a while. i don't know whether Realm Developer solve it or not

**Comment by Zhuinden** [comment]
Just use a [Migration](https://github.com/realm/realm-java/blob/master/examples/migrationExample/src/main/java/io/realm/examples/realmmigrationexample/model/Migration.java)
