### ISSUE TITLE
Ghost row in Realm file after deletion

### ISSUE THREAD

**Issue by somghosh** [realm/realm-java#835]
I have the following code in the App.onCreate() - there was a version on Play Store and I put an upgraded version with a slightly different schema

The logcat is here:

	2	02-07 10:41:31.807 I/XXX (15633): Change of schema in account db - deleting and recreating ...
	13	02-07 10:41:31.887 I/XXX (15633): Change of schema in app db - deleting and recreating ...
	14	02-07 10:41:31.967 I/XXX (15633): 1 accountdata record found in db ...					===> not sure why 1 accountdata in db was found after deleting the file

So I can see that even when the Realm file is created again after deletion there is some kind of a ghost row with a null value.

## In App.onCreate():

    try {
        emAccountDataDb = Realm.getInstance(this, ACCOUNT_DATA_DB);
        // this might fail if we have changed the database schema during code change
    } catch (Exception e) {

        Log.i("XXX", "Change of schema in account db - deleting and recreating ...");
        // in which case delete the file and get stuff fresh
        Realm.deleteRealmFile(this, ACCOUNT_DATA_DB);
        emAccountDataDb = Realm.getInstance(this, ACCOUNT_DATA_DB);
    }

    try {
        emAppDataDb = Realm.getInstance(this, APP_DATA_DB);
        // this might fail if we have changed the database schema during code change
    } catch (Exception e) {

        Log.i("XXX", "Change of schema in app db - deleting and recreating ...");
        // in which case delete the file and get stuff fresh
        Realm.deleteRealmFile(this, APP_DATA_DB);
        emAppDataDb = Realm.getInstance(this, APP_DATA_DB);
    }

    //endregion

    //region check if an user is signed in and if so populate accountData variable with imp login info, and also identify in segmentIo

    RealmResults<AccountData> accountDataRes = emAccountDataDb.where(AccountData.class).findAll();
    long count = accountDataRes.size();
    if (count == 0) {
        Log.i("XXX", "No accountdata record found in db...");
        accountData = new AccountData();         // no account data in database
        authTokenString="";
    } else {
		//strangely the control comes here even after deleting and recreating the file
		
        Log.i("XXX", accountDataRes.size() + " accountdata record found in db ...");		// this line is printed in logcat
        accountData = accountDataRes.last();
        authTokenString = accountData.getToken();			// does a nullPointer crash on this line
        
    }

**Comment by somghosh** [comment]
My Realm file has just this one object - and it has stayed same between app version 1.1 and 1.2 - however when adb install -r app-release-12 is done with app-release-11 in the phone already, I see that there is a migration error being caused (as in the code above). Not sure why this 

	public class AccountData extends RealmObject{

	    private boolean isSomeoneSignedIn=false;          // if someone is signed in
	    private String email;                       // email of signed in user
	    private String password;                    // password of signed in user
	    private String token="";                       // authtoken of signed in user
	    private long id;                            // Django ID of the signed in user
	    private String facebookToken;               // fb token of signed in user
	    private boolean facebook;                   // if signed in user is signed in via fb
    
	    private String firstPage;

    
	    private Date timeCreated;
	    private String firstName;
	    private String lastName;
	    private String locationCity;
	    private Date age;
	    private String gender;
	    private String image;
    
	    // not making EarthmileBreakdown another additional table but making it flat in AccountData 
	    // as there is no additional benefit (there's no array)
	    private float totalEarthmiles = 0;
	    private float cycling = 0;
	    private float other = 0;
	    private long sumAllActivityPoints = 0;
	    private float walking = 0 ;
	    private float running = 0;
	    private float redeemableEarthmiles = 0;


	    }

**Comment by emanuelez** [comment]
Hello,

that is happening because you are deleting a Realm file while a Realm instance is still open.
We already added a check for that and from the next release Realm will throw an exception is this use-case.
To fix your problem you have to close the realm instance before deleting the Realm file.

**Comment by emanuelez** [comment]
Please contact us if you need more help!
