### ISSUE TITLE
Storing Login information in Realm file

### ISSUE THREAD

**Issue by somghosh** [realm/realm-java#836]
I created two realm files "accountdata.realm" and "appdata.realm" with the view that accountdata.realm would just store login information (1 model) , while appdata.realm stores all other info about the app (5 other models)

However, when I change certain models/tables which I was ONLY writing to appdata.realm, it seems to me that accountdata.realm also throws a RealmMigrationNeeded exception. On inspection of the accountdata.realm file using Realm Browser, i found that it has all the 6 (1+5) tables and not just 1 table 

Is there a way to achieve what I am trying to do - separation of accountdata and appdata, or should I go back to using Sharedprefs for accountdata/login info (I wanted to use consistently for everything as I love the way it works so far)

**Comment by cmelchior** [comment]
Hi @somghosh 
Currently all Realms use the same Schema even though you only put the data from one model class into it. You should be able to use the same migration code for both of them, but if you don't want to do this, then yes, putting it in SharedPreferences or similar is probably your best bet.

We do however plan for our next version of the migration API to handle such cases smoothly, ie. if any tables are empty, they should just upgrade to latest version without throwing exceptions.

**Comment by cmelchior** [comment]
I assume you got your question answered. Please feel free to add additional information if not.
