### ISSUE TITLE
equalToAny() / equalToAll() / In() — query for list membership

### ISSUE THREAD

**Issue by creativepsyco** [realm/realm-java#841]
How can I achieve a query like this in Realm? Is there a way to pass `RealmResults` as a parameter for the queries?

```sql
SELECT * FROM users WHERE id IN 
               (SELECT * FROM banned_user_ids);
```

**Comment by kneth** [comment]
First of all, you should be aware that Realm is not a relational database, and data modelling should often be done differently. The relationship concept (http://realm.io/docs/java/0.78.0/#relationships) is much closer to object-oriented programming than SQL ever will be.

But it is possible to do subqueries with Realm. A `RealmResults` has the method `where` just for that. It requires that it is the same class (from your query it looks like you have two different classes (`users` and `banned_user_ids`).

To do something similar, you can build up a query:

    RealmResults<banned_user_ids> ids = realm.allObjects(banned_user_ids.class);
    RealmQuery q = users.where();
    for (banned_user_ids id : ids) {
        q = q.equalsTo("id", id.id);
    }
    RealmResults<users> users = q.findAll();

Besides that, it might be easier to have a boolean field in your users class indicating that a user is be banned or not. If you have to capture more information about why or when the user was banned, you should use a one-to-one relationship to another class ("the reason object" we can call it) with that information. If the user isn't banned, simply set "the reason object" to `null`. For example:

    public class User {
        private long id;
        private boolean banned;
        private RealmObject<Reason> reason;
        // setters and getters
    }

    public class Reason {
        private Date when;
        // etc.
    }

Now your query becomes much simpler:

    RealmResults<User> users = realm.where(User.class).equalTo("banned", true).findAll();

and you can iterate easily:

    for (User user : users) {
        Log.d("BANNED", "User "+user.getId()+" was banned at "+user.getReason().getWhen());
    }

**Comment by creativepsyco** [comment]
Yes you are right in saying that data modelling should be done on a different approach. However, a DB schema whether it's implemented in SQLite or via Realm should be able to handle this type of query, as it appears very often. I am currently iterating over the `RealmResults` to add the necessary query parameters, but it would be quite useful if there was a reduction query support of the form:
```
RealmResults<banned_user_ids> ids = realm.allObjects(banned_user_ids.class);
RealmQuery q = users.where();
q.equalsTo("id",  ids.reduceToList("id"));
q.findAll();
```
This would reduce all ids from the `banned_user_ids` table into a list. The example is very simple but the relevance of such a query still exists and would reduce the number of `for` loops flying around in the code. Couchbase has some similar concepts `Grouping` and `Reduction` ([1][1]). Although these may be borrowed concepts from SQL-land, they still get pretty heavily used.

[1]: http://developer.couchbase.com/mobile/develop/guides/couchbase-lite/native-api/query/index.html

**Comment by kneth** [comment]
I agree that your `reduceToList` combined with `any` and/or `all` predicates can be useful in certain situations. Thanks for the suggestion.

**Comment by creativepsyco** [comment]
:+1: Sounds good.

**Comment by cmelchior** [comment]
It seems to me that `equalToAny()` and `in()` has the same semantics. `in()` is probably more familiar term coming from SQL, while `equalToAny()` is perhaps a bit more readable?

I am not sure I can find a good use case for `equalToAll()` as it would only work on Lists as far as I can tell, and then you get into questions whether ordering matters or not.

**Comment by creativepsyco** [comment]
I think `in()` is more favorable semantically for those coming from a SQL background. Or if you wanna go with the current convention, then `equalToXXXIn()` sounds better?

But then you have too many methods with the name starting with `equals..()`

**Comment by beeender** [comment]
+1 from http://stackoverflow.com/questions/35584661/realm-do-a-in-query-in-android

**Comment by mithrann** [comment]
+1

**Comment by iamaniba** [comment]
+1

**Comment by cmelchior** [comment]
As a v1 for this we should just focus on supporting `in()`.
It is debatable  if the input should be either a primitive array or a Collection. I am leaning towards `Collection` though, which is also what OrmLite uses. Could not find anything in GreenDao/Requery/SquiDB.

```
// in(String fieldName, Collection arguments)
realm.where(Person.class).in("name", Array.of("Foo", "Bar")).findAll();

// vs.

// in(String fieldName, String firstArg, String[] remaining Args)
realm.where(Person.class).in("name", "Foo", "Bar").findAll();
realm.where(Person.class).in("name", new String[] {"Foo", "Bar"}).findAll();
```

Since core doesn't have native support for it, this is just a helper method for doing `equalsTo()` in a loop, but will also allow us to optimise easily later.

**Comment by dalinaum** [comment]
Since `equalTo` methods are overloaded, I think `in` or `equalToAny` should be overloaded too. If we use choose `Collection`, we cannot use overloading.

`public RealmQuery<E> equalToAny(String fieldName, Collection<String> collection)` and `public RealmQuery<E> equalToAny(String fieldName, Collection<Byte> collection)` will clash. Since both method have same erasures.

So I am trying the third version.

```
realm.where(Person.class).in("name", new String[] {"Foo", "Bar"}).findAll();
```

**Comment by cmelchior** [comment]
Good point about `equalTo` also being overloaded. The SQLite API's also use primitive arrays, so there is that. Going with primitive arrays is fine with me.

**Comment by nevi-me** [comment]
@cmelchior I thought that Realm doesn't support primitive arrays, or am I missing something recent?

**Comment by dalinaum** [comment]
@nevi-me We've talked about parameters of `in`, not fields. :)

**Comment by nevi-me** [comment]
Thanks, I must have missed that part. I was having trouble with Realm when I came across the post. In the end it was a rookie error where I confused `listOf().add()` with `listOf().plus()` when creating my Realm model. I was querying a class, but didn't notice that I hadn't added any objects to it.

**Comment by cmelchior** [comment]
Added in Realm Java 1.2.0
