### ISSUE TITLE
ArrayIndexOutOfBoundsException: columnIndex > available columns

### ISSUE THREAD

**Issue by eboudrant** [realm/realm-java#852]
Crash unexplained, there was no schema change, no migration. Crash report say 

```
java.lang.ArrayIndexOutOfBoundsException: columnIndex > available columns.
at io.realm.internal.Row.nativeGetLong(Native Method)
at io.realm.internal.Row.getLong(Row.java:95)
at io.realm.AppInstalledRealmProxy.getVersionCode(AppInstalledRealmProxy.java:94)
```

Where versionCode is an int. I cannot reproduce it, it has been reported by an user.

Using Realm Android 0.78.0

**Comment by cmelchior** [comment]
Hi @eboudrant 
Without anything more I am afraid there is very little for us to go after.

- Have you seen the error multiple times?
- What devices / android version?
- Where in the app lifecycle does it happen? Startup? During something?

**Comment by zsavely** [comment]
Hi @cmelchior 
I am probably experiencing the same issue. I am using ver. 0.79.0.
```Stacktrace
FATAL EXCEPTION: main
java.lang.ArrayIndexOutOfBoundsException: rowIndex > available rows.
at io.realm.internal.LinkView.nativeRemove(Native Method)
at io.realm.internal.LinkView.remove(LinkView.java:67)
at io.realm.RealmList.remove(RealmList.java:189)
at com.sampleapp.MergedCardsListClick$1.onClick(MergedCardsListClick.java:64)
...
at dalvik.system.NativeStart.main(Native Method)
```
This issue happens when I try to delete the last element in `RealmList`. Here is my code:
```Java
for (int i = 0; i < parent.getChildren().size(); i++) {
	if (parent.getChildren().get(i).get_id() == object.get_id()) {
		mRealm.beginTransaction();
		parent.getChildren().remove(i); // Line that throws ArrayIndexOutOfBoundsException
		mRealm.commitTransaction();
		break;
	}
}
```
The strange thing is that when I try to delete any element but not last, it does not crash. But when I try to delete the last element (again, **any** element), it crashes.
So I changed the code a bit to make it work: (maybe somebody will find it helpful)
```Java
for (int i = 0; i < size; i++) {
	if (parent.getChildren().get(i).get_id() == sms.get_id()) {
		mRealm.beginTransaction();
		if (size != 1) {
			parent.getChildren().remove(i); // does not crash
		} else {
			parent.getChildren().clear(); // does not crash
		}
		mRealm.commitTransaction();
		break;
	}
}
```
My model:
```Java
package com.sampleapp;

import io.realm.RealmList;
import io.realm.RealmObject;
import io.realm.annotations.Index;
import io.realm.annotations.RealmClass;

@RealmClass
public class Parent extends RealmObject {
	private long _id;

	@Index
	private String originalText;
	private Parent parent;
	private RealmList<Parent> children;

	public long get_id() {
		return _id;
	}

	public void set_id(long _id) {
		this._id = _id;
	}

	public String getOriginalText() {
		return originalText;
	}

	public void setOriginalText(String originalText) {
		this.originalText = originalText;
	}

	public Parent getParent() {
		return parent;
	}

	public void setParent(Parent parent) {
		this.parent = parent;
	}

	public RealmList<Parent> getChildren() {
		return children;
	}

	public void setChildren(RealmList<Parent> children) {
		this.children = children;
	}
}
```
Summary: 
* It crashes every time. (I've seen it multiple times)
* It is reproducable.
* Experienced crashes on Android 4.1.2 (Samsung Galaxy S3), 4.4.4. (Sony Z3 Compact)
* Happens when a user taps on the button in order to delete the last child.

**Comment by eboudrant** [comment]
@cmelchior it happened in 2 scenarios : 
- during a delete in a broadcast receiver
- during a click in the activity

**Comment by cmelchior** [comment]
Hi @zsavely 
Thanks, but your issue is not the same. I think we already have a open bug report on it, but I will split it into another issue just to double check.

**Comment by cmelchior** [comment]
Hi @eboudrant 
We fixed some issues in 0.79 and 0.80 that could be connected to this. Are you still seeing this issue?

**Comment by eboudrant** [comment]
That's good news. I will try this new version but I won't be able to
release it because of #982
Thanks

On Wed, Apr 1, 2015 at 4:18 AM, Christian Melchior <notifications@github.com

**Comment by kneth** [comment]
@eboudrant Did updating Realm help?

**Comment by zhaozeyx** [comment]
The exception occurs while  I am migrating data
![image](https://cloud.githubusercontent.com/assets/4213414/7390281/0699db60-eea9-11e4-9e78-f136212c490b.png)
![image](https://cloud.githubusercontent.com/assets/4213414/7390285/131334ea-eea9-11e4-8bc0-141ae03f9046.png)
![image](https://cloud.githubusercontent.com/assets/4213414/7390290/166cb292-eea9-11e4-9a4c-639f521b0011.png)
![image](https://cloud.githubusercontent.com/assets/4213414/7390292/19b9df10-eea9-11e4-9cbe-18f9dafd661d.png)

**Comment by eboudrant** [comment]
@kneth until #982 is fixed I cannot update the realm and publish the app. I never had the issue since, I will re-open if I still have see it using 0.80.x. Thanks

**Comment by hohnamkung** [comment]
Hi Realm team.
I'm using Realm v0.87.4 and having this exception.

    Fatal Exception: java.lang.ArrayIndexOutOfBoundsException: columnIndex > available columns.
       at io.realm.internal.Table.nativeGetLong(Table.java)
       at io.realm.internal.Table.getLong(Table.java:645)
       at io.realm.BaseRealm.getVersion(BaseRealm.java:382)
       at io.realm.Realm.getVersion(Realm.java:108)
       at io.realm.Realm.createAndValidate(Realm.java:247)
       at io.realm.Realm.createInstance(Realm.java:231)
       at io.realm.RealmCache.createRealmOrGetFromCache(RealmCache.java:114)
       at io.realm.Realm.getInstance(Realm.java:197)
       at kr.co.vcnc.android.couple.feature.home.HomeFragment.onLazyLoadTab(HomeFragment.java:143)

This exception is happening only in Android 4.4 like issues #1795 
After we start to use independent Realm configuration to specific table(Same table in #1795), this crash is occurring.

![screen shot 2016-02-15 at 8 57 27 pm](https://cloud.githubusercontent.com/assets/1873136/13048075/bfa5007c-d426-11e5-9315-6931b0739fd7.png)
