### ISSUE TITLE
Android component: ReclyclerViewRealmAdapter

### ISSUE THREAD

**Issue by gpulido** [realm/realm-java#861]
Hello,
I'm trying to adapt the RealmBaseAdapter concept to a recyclerview.adapter extension using the same approach as the RealmBaseAdapter to autoupdate in case there is any change on the RealmResults attached list, however when I try to do:
```java
 if (automaticUpdate) {
            mRealmResults.getRealm().addChangeListener(new RealmChangeListener() {
                @Override
                public void onChange() {
                    notifyDataSetChanged();
                }
            });
        }
```
It obviously doesn't compile because the getRealm() is not public, so I can't access the realm that creates the RealmList. Is there any way to solve this problem?
Also I don't know if you are going to add your own implementation of recyclerview adapter.

**Comment by cmelchior** [comment]
Hi @gpulido 
We are continuously evaluating which Android framework classes we should extend with Realm support, and the RecyclerViewAdapter is probably a prime candidate as it is poised to replace ListViewAdapters in a lot of cases.

That said. The method you are trying to use is actually just package protected, so if you want to use your own implementation you can just put it in the io.realm package.

Just be warned, we might change any non-public methods/variabels without warning which could break your implementation.

**Comment by cmelchior** [comment]
An excellent blog post on creating your own RecyclerView.Adapter http://gradlewhy.ghost.io/realm-results-with-recyclerview/

**Comment by Zhuinden** [comment]
Hello! This seems to be working for me, I wrote it based on RealmBaseAdapter v0.81.1 - but I needed reflection to access the `getRealm()` method.

    public abstract class RealmRecyclerViewAdapter<T extends RealmObject, VH extends RecyclerView.ViewHolder>
            extends RecyclerView.Adapter<VH> {
        protected LayoutInflater inflater;
        protected RealmResults<T> realmResults;
        protected Context context;
    
        private final RealmChangeListener listener;
    
    
        private Realm getRealm(RealmResults<T> realmResults) {
            // "getRealm" is not accessible outside package io.realm
            Realm realm = null;
            try {
                Method method = RealmResults.class.getDeclaredMethod("getRealm");
                method.setAccessible(true);
                realm = (Realm)method.invoke(realmResults);
            } catch(NoSuchMethodException e) {
                e.printStackTrace();
            } catch(IllegalAccessException e) {
                e.printStackTrace();
            } catch(InvocationTargetException e) {
                e.printStackTrace();
            }
            return realm;
        }
    
        public RealmRecyclerViewAdapter(Context context, RealmResults<T> realmResults, boolean automaticUpdate) {
            if(context == null) {
                throw new IllegalArgumentException("Context cannot be null");
            }
            this.context = context;
            this.realmResults = realmResults;
            this.inflater = LayoutInflater.from(context);
            this.listener = (!automaticUpdate) ? null : new RealmChangeListener() {
                @Override
                public void onChange() {
                    notifyDataSetChanged();
                }
            };
    
            if(listener != null && realmResults != null) {
                getRealm(realmResults)
                        .addChangeListener(listener);
            }
        }
    
        @Override
        public long getItemId(int i) {
            // TODO: find better solution once we have unique IDs
            return i;
        }
    
        public T getItem(int i) {
            if(realmResults == null) {
                return null;
            }
            return realmResults.get(i);
        }
    
        public void updateRealmResults(RealmResults<T> queryResults) {
            if(listener != null) {
                // Making sure that Adapter is refreshed correctly if new RealmResults come from another Realm
                if(this.realmResults != null) {
                    getRealm(this.realmResults).removeChangeListener(listener);
                }
                if(queryResults != null) {
                    getRealm(queryResults).addChangeListener(listener);
                }
            }
    
            this.realmResults = queryResults;
            notifyDataSetChanged();
        }
    
        @Override
        public int getItemCount() {
            if(realmResults == null) {
                return 0;
            }
            return realmResults.size();
        }
    }

**Comment by SleeplessByte** [comment]
`#notifyDataSetChanged` will not queue animations and SHOULD not be used unless there are not other options. 

Instead, the data optimally is backed by a `RecyclerView.Adaper.SortedList` or use the `#notifyInserted`, `#notifyMoved` etc. otherwise.

**Comment by madhavajay** [comment]
Is this something that will be added to Realm soon? I would like to use this with https://github.com/TonicArtos/SuperSLiM

**Comment by kamilwlf** [comment]
When?

**Comment by slidenerd** [comment]
Read the answer http://stackoverflow.com/questions/28995380/best-practices-to-use-realm-with-a-recycler-view by PirateApp here... for Realm with RecyclerView

**Comment by thorbenprimke** [comment]
I have been working on a RecyclerView/Adapter with support for Realm and basic functionality like pull-to-refresh, empty state, load more and row animation. It also integrates with SuperSLiM and abstracts away the header creation. There is room for more functionality and better customization but would love to know if this is helpful/useful to anymore. https://github.com/thorbenprimke/realm-recyclerview

**Comment by slidenerd** [comment]
@thorbenprimke  i ll definitely take a look at this, just to clarify something beforehand, since RealmResults are live objects, you cannot call notifyXXX methods that perform animations and hence stuck with notifyDataSetChanged, any chance you worked around this limitation?

**Comment by thorbenprimke** [comment]
@slidenerd - Yes, to work around that I'm diffing the before (cached) and after item ids (uses primary key) and if there is only a single change group, I'm animating those rows. It's not ideal but until there are fine grained change notifications, this seems to work.

**Comment by slidenerd** [comment]
@thorbenprimke , I saw the 4 and I really appreciate the effort you have put into keeping the animations without calling notifyDataSetChanged() , if it isn't too much to ask, can you add a swipe to delete solution as well based on ItemTouchHelper https://developer.android.com/reference/android/support/v7/widget/helper/ItemTouchHelper.html that supports animations, thanks :+1:

**Comment by cmelchior** [comment]
We are splitting all Android specific components into their own repo. So this issue has been transferred to here: https://github.com/realm/realm-android-adapters/issues/7
