### ISSUE TITLE
Cannot load doubles from JSON

### ISSUE THREAD

**Issue by shvelo** [realm/realm-java#863]
When loading `double` values from JSON with `createAllFromJson`, they are always set to 0.0   
`String` and `int` values are loaded OK.  

Example JSON (UTF-8):
```json
[{"lat":41.68792900000596,"lon":44.818311000000534,"name":"ორთაჭალა - [1390]","id":1390}]
```
Realm model:
```java
// ClusterItem is from Google Maps utils
public class BusStop extends RealmObject implements ClusterItem {
    @PrimaryKey
    private int id;
    private String name;
    private double lat;
    private double lon;

    public BusStop() {}
    // Getters and setters here
}
```

Loading:
```java
InputStream is = getAssets().open("db.json");
realm.beginTransaction();
realm.createOrUpdateAllFromJson(BusStop.class, is);
realm.commitTransaction();
```

**Comment by cmelchior** [comment]
Hi @shvelo 
What does your JSON looks like?

**Comment by shvelo** [comment]
Here's the full JSON file: [shvelo/tbilisi-bus/assets/db.json](https://github.com/shvelo/tbilisi-bus/blob/master/assets/db.json)

**Comment by shvelo** [comment]
Sorry it was my fault. I wasn't using getters in getLocation.
