### ISSUE TITLE
copyToRealmOrUpdate() Throws PrimaryKey Constraint Exception When PrimaryKey Is Field In Non-PrimaryKey Class

### ISSUE THREAD

**Issue by thorbenprimke** [realm/realm-java#864]
copyToRealmOrUpdate() doesn't seem to pass the update flag through for objects that don't have a primaryKey and thus any fields within that object is only attempted to be copied. 

Example: https://github.com/thorbenprimke/realm-java/tree/nestedObjectCausesPrimaryKeyConflict
Example code: https://github.com/thorbenprimke/realm-java/blob/9f2992ef20e9b3241bac9a6e45f7fe034167c70f/examples/introExample/src/main/java/io/realm/examples/intro/IntroExampleActivity.java#L106

**Comment by thorbenprimke** [comment]
Forgot the stacktrace: https://gist.github.com/thorbenprimke/bc59000b0a336f7b1351

**Comment by cmelchior** [comment]
A fix has been merged and will be released as part of 0.79.1

**Comment by cmelchior** [comment]
0.79.1 has been released and should be in bintray now.
