### ISSUE TITLE
RxJava support

### ISSUE THREAD

**Issue by jenzz** [realm/realm-java#865]
I'm not sure if the Realm internals allow for RxJava support, but it would be nice to be able to do something like this:

```
// Get observable of all users
Realm.getInstance(context)
    .where(User.class)
    .findAll()
    .observable()
    .subscribe(users -> {
        // do stuff with users
    });

// Get observable of a single user
Realm.getInstance(context)
    .where(User.class)
    .findFirst()
    .observable()
    .subscribe(user -> {
        // do stuff with user
    });

// Get observable of users table count
Realm.getInstance(context)
    .where(User.class)
    .findAll()
    .size()
    .observable()
    .subscribe(count -> {
        // do stuff with count
    });
```

**Comment by kakkoyun** [comment]
+1

**Comment by cmelchior** [comment]
We definitely have RxJava on the radar, as it quite a cool framework. A first step for us is probably documenting what works and what doesn't when combining Realm and RxJava, but going forward adding some sort of support is not out of the question.

That said we are currently focusing on other features right now, so I cannot give you any timeframe just yet.

**Comment by DHuckaby** [comment]
+1

**Comment by cmelchior** [comment]
Some resources:
- https://github.com/ReactiveX/RxJava/wiki
- http://blog.danlew.net/2014/09/15/grokking-rxjava-part-1/
- https://www.youtube.com/watch?v=_t06LRX0DV0

**Comment by kboyarshinov** [comment]
+1

Internal RxJava support would be great. For now I'm using it with Realm by following several restrictions:  

- One observable for one transaction.
- Mapping Realm objects to non-Realm (e.g. AutoValue) when passing between observer/subscriber threads.

**Comment by cmelchior** [comment]
Hi @kboyarshinov 
Can you elaborate a bit on one observable pr. transaction?

I have been evaluating RxJava support as well, and the biggest blockers I can see so far is that we need fine-grained notifications to observe on queries and that it is not possible to move RealmObjects between threads which conflict with ```Observable.subscribeOn``` and ```Observerable.oberserveOn()```.

The second part is probably the biggest issue.

**Comment by kboyarshinov** [comment]
@cmelchior I implemented [`OnSubscribeRealm`](https://github.com/kboyarshinov/realm-rxjava-example/blob/master/app/src/main/java/com/kboyarshinov/realmrxjavaexample/rx/OnSubscribeRealm.java) function which controls creation and closing of Realm instance following `Observable` contract. And it defines custom function to manipulate data with that instance in a single transaction. 

One observable per transaction means every RealmObservable operates its own instance of `Realm` and executes used defined function with this instance in isolated transaction.

Also there is a [`RealmObservable`](https://github.com/kboyarshinov/realm-rxjava-example/blob/master/app/src/main/java/com/kboyarshinov/realmrxjavaexample/rx/RealmObservable.java) helper class - it simplifies usage of `OnSubscribe` function. Full example is also [available](https://github.com/kboyarshinov/realm-rxjava-example).

**Comment by bernhardpflug** [comment]
+1

**Comment by tomekpiotrowski** [comment]
+1

**Comment by Fi5t** [comment]
+1!

**Comment by colintheshots** [comment]
+1!!!

**Comment by allan1st** [comment]
+1

**Comment by wasabeef** [comment]
+1

**Comment by PavelSynek** [comment]
+1

**Comment by ewintory** [comment]
+1 too

**Comment by itrethan** [comment]
+1

**Comment by alliannas** [comment]
+1

**Comment by jonfry22** [comment]
+1

**Comment by grub-** [comment]
+1

**Comment by TheFinestArtist** [comment]
+1

**Comment by kkooff114** [comment]
+1

**Comment by cnevinc** [comment]
+1

**Comment by vova1vova** [comment]
+1

**Comment by vvictor10** [comment]
+1

**Comment by agonist** [comment]
+1

**Comment by NoahAndrews** [comment]
+1

**Comment by kalpesh-pagalguy** [comment]
+1

**Comment by maarek** [comment]
+1

**Comment by dmitry-mochalov** [comment]
+1

**Comment by dkpalmer** [comment]
+1

**Comment by festevezga** [comment]
+1

**Comment by fuwaneko** [comment]
+1

**Comment by lucamtudor** [comment]
+1

**Comment by TheRishka** [comment]
+1

**Comment by cnevinc** [comment]
+1

**Comment by dawidhyzy** [comment]
+1

**Comment by sharathp** [comment]
+1

**Comment by TheShapGuy** [comment]
I just hate +1's so,

It would be cool if Realm supported RxObservables  because it would allow `fluently` merging RealmObjets and API calls.

**Comment by DefiantCatgirl** [comment]
I don't particularly hate +1's so, well, +1. Mostly for the same reason @TheShapGuy mentioned.

**Comment by swsachini** [comment]
+1

**Comment by lpessoa** [comment]
+1

**Comment by rubixhacker** [comment]
+1

**Comment by cmelchior** [comment]
We have begun sketching out how Realm could support RxJava, please see https://github.com/realm/realm-java/pull/1651 for a design spec. Any feedback on direction and/or use cases we are missing will be much appreciated.

**Comment by alicheh** [comment]
+1

**Comment by cmelchior** [comment]
Initial RxJava support has been added in 0.87: https://realm.io/news/realm-java-0.87.0/
The remaining classes that needs to be exposed as Observables are tracked here #1955 and here #1956.

If you feel anything any other methods/classes are missing, please create a new issue for it.
