### ISSUE TITLE
Android 2.3: Could not find validateTable method in generated proxy class

### ISSUE THREAD

**Issue by shvelo** [realm/realm-java#870]
I've recently changed my app's minimum API level to 9 and when testing on Android 2.3 I always get this exception: 
```
java.lang.RuntimeException: Unable to create application com.tbilisi.bus.App: io.realm.exceptions.RealmException: Could not find the validateTable method in the generated io.realm.HistoryItemRealmProxy class: Annotation processor may not have been executed.
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:3413)
            at android.app.ActivityThread.access$2200(ActivityThread.java:124)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1012)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:130)
            at android.app.ActivityThread.main(ActivityThread.java:3821)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:507)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
            at dalvik.system.NativeStart.main(Native Method)
     Caused by: io.realm.exceptions.RealmException: Could not find the validateTable method in the generated io.realm.HistoryItemRealmProxy class: Annotation processor may not have been executed.
            at io.realm.Realm.initializeRealm(Realm.java:608)
            at io.realm.Realm.createAndValidate(Realm.java:523)
            at io.realm.Realm.create(Realm.java:480)
            at io.realm.Realm.getInstance(Realm.java:397)
            at io.realm.Realm.getInstance(Realm.java:359)
            at io.realm.Realm.getInstance(Realm.java:340)
            at com.tbilisi.bus.App.loadRealm(App.java:22)
            at com.tbilisi.bus.App.onCreate(App.java:18)
            at android.app.Instrumentation.callApplicationOnCreate(Instrumentation.java:969)
            at android.app.ActivityThread.handleBindApplication(ActivityThread.java:3410)
            at android.app.ActivityThread.access$2200(ActivityThread.java:124)
            at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1012)
            at android.os.Handler.dispatchMessage(Handler.java:99)
            at android.os.Looper.loop(Looper.java:130)
            at android.app.ActivityThread.main(ActivityThread.java:3821)
            at java.lang.reflect.Method.invokeNative(Native Method)
            at java.lang.reflect.Method.invoke(Method.java:507)
            at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:839)
            at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:597)
            at dalvik.system.NativeStart.main(Native Method)
```

All of my source is published at https://github.com/shvelo/tbilisi-bus  
I've tried adding `@RealmClass` to my models but it doesn't help at all.

**Comment by cmelchior** [comment]
Hi @shvelo 
I just checked your code out and ran it from Android Studio without any problems. Have you tried cleaning and/or reimporting the project again?

**Comment by shvelo** [comment]
I've tried deleting the build directory and building again, several times.
What Android version are you running it on?

**Comment by cmelchior** [comment]
Lollipop, but those classes are generated by the annotation processor so it should not be Android related, but perhaps more Java version related. What version of Java are you using?

**Comment by shvelo** [comment]
I'm using OpenJDK 8. 
The app works fine on my Jellybean device, but the crash only happens on Gingerbread.
Here's my build.gradle:
```gradle
buildscript {
    repositories {
        jcenter()
    }
    dependencies {
        classpath 'com.android.tools.build:gradle:1.0.+'
    }
}

repositories {
    jcenter()
}

task wrapper(type: Wrapper) {
    gradleVersion = '2.3'
}

apply plugin: 'com.android.application'

dependencies {
    compile fileTree(dir: 'libs', include: '*.jar')
    compile 'com.android.support:appcompat-v7:21.0.3'
    compile 'com.google.android.gms:play-services:6.5.87'
    compile 'com.google.maps.android:android-maps-utils:0.3+'
    compile 'io.realm:realm-android:0.79.0'
}

android {
    defaultConfig {
        versionCode 42
        versionName "4.2.0"
    }

    compileSdkVersion 21
    buildToolsVersion "21.1.2"

    lintOptions {
      abortOnError false
    }

    defaultConfig {
	   minSdkVersion 9
	   targetSdkVersion 21
    }

    buildTypes {
        release {
            debuggable false
            minifyEnabled true
            proguardFile file("proguard.cfg")
        }
    }

    signingConfigs {
        debug {
            storeFile file("debug.keystore")
        }
    }

    sourceSets {
        main {
            manifest.srcFile 'AndroidManifest.xml'
            java.srcDirs = ['src']
            resources.srcDirs = ['src']
            aidl.srcDirs = ['src']
            renderscript.srcDirs = ['src']
            res.srcDirs = ['res']
            assets.srcDirs = ['assets']
        }

        instrumentTest.setRoot('tests')

        debug.setRoot('build-types/debug')
        release.setRoot('build-types/release')
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_7
        targetCompatibility JavaVersion.VERSION_1_7
    }
}

apply from: 'signing.gradle'
```

**Comment by sliwakowski** [comment]
Same problem here, working great on Android 4.0+ but not for 2.3. I'm using @RealmClass annotation.

**Comment by cmelchior** [comment]
Hmm, you are correct there seem to be some issue with Gingerbread. Our proxy files and methods gets generated allright, but the code calling them cannot find them. Very odd.

**Comment by cmelchior** [comment]
It seems to be related to the bugs described here:
https://github.com/square/otto/issues/37
http://corner.squareup.com/2012/08/getting-to-the-bottom.html

It looks like it might be due to our proxy classes using unsupported API's (on 2.3.7) which then fail to initialise (they shouldn't). In this case our proxy classes are using JsonReader which isn't supported before API 11, but I will have to investigate further to be sure.

**Comment by shvelo** [comment]
Yeah I was getting a warning in Logcat that JsonReader was not found.

**Comment by cmelchior** [comment]
Yeah, but Dalvik should be able to handle that. It apparently doesn't do that very well on some versions of Android :(

**Comment by njovy** [comment]
Is there any hacky way to resolve this problem?

**Comment by cmelchior** [comment]
Hi @njovy 
The hacky approach would be to remove the populateUsingJsonStream() method from the proxy class as well as the ```import android.util.JsonReader;```

This bug will be fixed as part of our migration rewrite (#880), as we plan to change how the ProxyClasses are created.

**Comment by njovy** [comment]
@cmelchior  Thanks for the quick response! I will get rid of the method from proxy class and build realm until this issue is fixed.

**Comment by Sakirk** [comment]
@njovy are you successful with the hacky approach and can you please share how you achieved that.
Thanks.

**Comment by njovy** [comment]
@Sakirk The app uses createFromJson heavily to make a new realm object as our realm objects are returned from a server in json format so I didn't get rid of the method to resolve the issue yet. We have very few clients using gingerbread devices so we told them to upgrade their phones at the moment. I would include android.util.JsonReader class in realm and build a jar to fix this issue until #880 is fixed .

**Comment by gshockv** [comment]
I also have the same crash at my application on Gingerbread devices. I'm using 0.80.0 Realm version and it is crashes my app. I'm not using calls like createFromJson()

**Comment by njovy** [comment]
It looks like it will take more time until this issue is resolved. For those of you who are still waiting for this fix, I have forked the repo and replaced android.util.JsonReader with newly included android.support.v11.util.JsonReader(copy of codes from Android project). The repo is here https://github.com/njovy/realm-java. I ran realm:connectedCheck on Galaxy S running 2.3.6. You can build the project or simply use the jar file. Hope migration rewrite is done soon.

**Comment by jmachete** [comment]
The same crash here on 2.3. Please give we really need this bug fixed. Thanks

**Comment by cbotman** [comment]
We also have an app that needs to work on API 10, but in the meantime @njovy 's fix works, thanks. :+1:

**Comment by njovy** [comment]
I am glad that it helps :)
The repo will be updated until #938 is fixed. The realm team has made a lot of progress so I hope this issue is resolved soon.

**Comment by cmelchior** [comment]
Sorry for the wait. A fix should now have been merged to master.

**Comment by joaomachete** [comment]
Thats music to my ears...I will try it...Thanks @cmelchior

**Comment by njovy** [comment]
@cmelchior  Thank you for all your hard work!

**Comment by trolloks** [comment]
@cmelchior  Have you applied your fix to the latest SNAPSHOT?

**Comment by cmelchior** [comment]
Our buildserver has been acting up I'm afraid, so no It hasn't been deployed to our SNAPSHOT yet.

**Comment by trolloks** [comment]
Ahh okay, no worries. I luckily don't need the fix yet. Thanks for all your effort.

**Comment by stevyhacker** [comment]
I have the same issue on gingerbread on two of my applications, thanks @njovy for the fixed .jar it works. I was using 0.81.1 and still had the issue with android.util.JsonReader

**Comment by njovy** [comment]
@stevyhacker Please try to use 0.80.3 and see if the same error happens. The forked repo is deprecated  as it has been resolved. I haven't tried 0.81.1 yet but my app using 0.80.3 has no problem running on gingerbread devices.

**Comment by Zhuinden** [comment]
Don't forget that 0.82.0 is out, so you should see if that works or if there's a bug for the Realm people to fix (if you can).

**Comment by stevyhacker** [comment]
I tried 0.82.0 stable version and it's the same, the only thing that is working for me now is forked @njovy .jar file I tried building one myself with more recent realm version but I wasn't successfull. If you could update it, that would be great.

**Comment by stevyhacker** [comment]
I found the solution for my problem. I added the android.util.JsonReader and other 4 classes needed for it to work directly in my app source code.
