### ISSUE TITLE
Search doesn't work for Unicode characters

### ISSUE THREAD

**Issue by shvelo** [realm/realm-java#871]
My database contains data in Georgian, and when doing `contains` search on the field with Georgian characters, it always returns an empty set.

**Comment by kneth** [comment]
As I don't speak or write Georgian, can you provide a few sample strings I can try?

**Comment by shvelo** [comment]
OK, try some of these:  

მონაცემთა ბაზა  
მიწისქვეშა გადასასვლელი  
რუსთაველის გამზირი  
მთავარი ქუჩა  
სადგურის მოედანი  
ველოცირაპტორების ჯოგი  
პუტინი ყლეა

**Comment by kneth** [comment]
Thanks, I'll write an extra unit test. It is possible for you to sort them? Just in case I am going to test sorting too.

**Comment by shvelo** [comment]
Being too lazy, I've used Ruby to sort them

    ["ველოცირაპტორების ჯოგი", "მთავარი ქუჩა", "მიწისქვეშა გადასასვლელი", "მონაცემთა ბაზა", "პუტინი ყლეა", "რუსთაველის გამზირი", "სადგურის მოედანი"]

ველოცირაპტორების ჯოგი
მთავარი ქუჩა
მიწისქვეშა გადასასვლელი
მონაცემთა ბაზა
პუტინი ყლეა
რუსთაველის გამზირი
სადგურის მოედანი

**Comment by kneth** [comment]
I have created a unit test (see pull request #872), and I am not able to reproduce the issue.

**Comment by shvelo** [comment]
When I've changed my query from this:
```java
RealmResults<BusStop> results = realm.where(BusStop.class)
                    .contains("name", id)
                    .or().equalTo("id", Integer.parseInt(id))
                    .findAll();
```
to this:
```java
RealmResults<BusStop> results = realm.where(BusStop.class)
                    .contains("name", id)
                    .findAll();
```
It worked.

https://github.com/shvelo/tbilisi-bus/commit/6fa944c5693ee4b9e771b35eef615421e048c06d

**Comment by kneth** [comment]
I'll close the issue. You're welcome to reopen it if the issue comes up again.
