### ISSUE TITLE
@PrimaryKey usage

### ISSUE THREAD

**Issue by ousenko** [realm/realm-java#877]
Dear Realm developers, 

Could you shed a bit of light on this newly available feature? 
Any specific implications of annotating a field a @PrimaryKey, anything special to expect when using it?

**Comment by cmelchior** [comment]
Our JavaDoc should have most of the answers: http://realm.io/docs/java/0.79.0/api/io/realm/annotations/PrimaryKey.html

Is there anything in there that is unclear or could use a better description?

**Comment by ousenko** [comment]
Thank you, it seems like this javadoc was not attached to to realm.jar (0.79.0), that was the reason I came asking questions. 
Sorry for bothering :(
