### ISSUE TITLE
Document working with Parcelable RealmObjects 

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#878]
Having RealmObjects support the Parcelable interface as default would solve a lot of usecases sending RealmObjects around in Intents, which has been a fairly requested feature.

Even though RealmObjects contain no data, it should still be possible to serialize the data connection and reopen it again on the other side.

We need to figure out pros and cons of this approach and if we can add support for it. Preferable by letting RealmObject implement Parcelable. However there are some potential issues with standalone objects that needs to be considered.

Libraries to be for inspiration:
https://github.com/frankiesardo/auto-parcel
https://github.com/johncarl81/parceler

**Comment by spierce7** [comment]
This would be pretty nice.

**Comment by Tukajo** [comment]
Has any progress been made on this front?

**Comment by Saketme** [comment]
Passing parcelable objects around the app is something even I was doing, because re-fetching data from the SQLite database was expensive. However, with Realm, searching is super fast and I no longer require passing objects around. I feel that there's no need for this. Please correct if I'm wrong.

**Comment by cmelchior** [comment]
With #909 implemented it should be possible to do this, except the object will be copied into memory. We should document how best to work with this instead.

**Comment by cbush** [comment]
We are revamping the Realm docs. We're not ignoring this issue -- we've read through every one of them, and we'll be sure to address this as part of our updates. We're closing the GitHub issues and creating new JIRA tickets to track the work at a high level.

**Comment by ujwal-coditas** [comment]
Is there any update on this ?
