### ISSUE TITLE
How to skip needless migration

### ISSUE THREAD

**Issue by suzukihr** [realm/realm-java#886]
In your migration examples, all migration start with correct realm version. But when users install the app that is not first realm version, their migration start with 0. 

Is there a way that you recommend to set version?
Or, should I add conditions like below to skip needless migration?

```
// Migrate from version 0 to version 1
if (version == 0) {
    Table personTable = realm.getTable(Person.class);

    if (getIndexForProperty(personTable, "fullName") != -1) {
        version++;
    } else {
        ...
```

**Comment by cmelchior** [comment]
The current migration API is still pretty rough around the edges, so for now the current approach would to be to provide a no-op migration like this:

```
new SetVersionMigration implements RealmMigration {
  public long execute(Realm realm, long version) {
    return 42; // Return the version of the Schema
  }
}
```

This would set the version to 42.
But we are currently working on improving it :) https://github.com/realm/realm-java/pull/880

**Comment by suzukihr** [comment]
OK. Thank you very much :)
