### ISSUE TITLE
Realm.getInstance(getActivity()) throws RealmMigrationNeededException

### ISSUE THREAD

**Issue by dalgopower** [realm/realm-java#891]
Hi

Literally, my app throws RealmMigrationNeededException at the line of 'Realm realm = Realm.getInstance(getActivity());'
I haven't write and run that code until now so there shouldn't be any cache, any table, nor any db yet. However, Realm tells me that there is something old data I need to concern about.

So I call deleteRealmFile() to clear up and now the app does not throw that exception anymore.
(http://realm.io/docs/java/0.71.0/api/io/realm/Realm.html#deleteRealmFile(android.content.Context)

But I wonder..how that happened? How can one be sure that this exception will not be thrown again in the future even if DB file is fine and nothing is corrupted?

Can someone give a clue?

Thanks in advance

**Comment by cmelchior** [comment]
Hi @dalgopower 
I don't have any qualified answers for you. The scenario you describe should not be possible without a already existing database, perhaps your app's packagename match an old packagename that also had a Realm database.

Are you able to reproduce the behaviour?

**Comment by cmelchior** [comment]
Closing due to no response and we cannot reproduce the behaviour. Please feel free to reopen if you have additional information
