### ISSUE TITLE
Async queries + write  transactions

### ISSUE THREAD

**Issue by bmunkholm** [realm/realm-java#896]
Realm should offer a API akin to this, where queries are run on a background thread and then transferred afterwards.

```
realm.where(Foo.class).findAllAsync(new RealmQuery.Callback() {
  public void onSuccess(RealmResults<Foo> results) {
    // Use results
 }
});

realm.where(Foo.class).findFirstAsync(new RealmQuery.Callback() {
  public void onSuccess(Foo result) {
    // Use result
 }
});
```

Topics for discussion
- How to handle version differences between threads?
- Should we expose a error callback as well?
- How should we handle that the UI is no longer available (i.e. don't be AsyncTask)

**Comment by kneth** [comment]
Core issue: https://github.com/realm/realm-core/issues/725

**Comment by Ruxton** [comment]
+100!

**Comment by lucamtudor** [comment]
YES!

**Comment by kevincwuu** [comment]
please please implement this...

**Comment by nhachicha** [comment]
https://github.com/realm/realm-java/pull/1214
