### ISSUE TITLE
copyToRealmOrUpdate fails due to primary key on optional reference entity

### ISSUE THREAD

**Issue by vvictor10** [realm/realm-java#902]
The copyToRealmOrUpdate() fails in the following case. Car has list of Tires. And Tire has a reference to the Car it belongs to, however, not all tires are fitted to the car(as in the real world), so the Car reference in the Tire object has to be optional for me. And both of them have a primary key fields. So if I try to use the copyToRealmOrUpdate() to save a new Tire object without a car reference, it fails.

Is this expected, if so, why? If not, is it a bug?

I am trying to model an optional parent relationship from the child. And I would love to have a single method to save/update the Tire in my DAO class instead of having two - one for save-new and one for update.

Thanks for the tremendous support guys.

**Comment by emanuelez** [comment]
Hello again :)

In what way does it fail?
Could you write here your Car and Tire classes? You can omit the accessors for brevity.

**Comment by vvictor10** [comment]
@emanuelez Hello again, when trying to copy the classes for you, I realized the Tire RealmObject did not have the @PrimaryKey set on its id field. I set that and used the copyToRealmOrUpdate() and it works fine. Sorry for the false alarm.

Here are the classes, I was trying to save a Tire without a car reference.

public class RealmCar extends RealmObject{

    @PrimaryKey
    private String id;

    private String name;

    private String model;

    private RealmList<RealmTire> tires = new RealmList<RealmTire>();
}

public class RealmTire extends RealmObject{

    @PrimaryKey
    private String id;
    private String name;
    private RealmCar car;
}

**Comment by emanuelez** [comment]
Cool!

Just a note: would it make sense in your case to have a boolean field `isFitted` on the tire, instead of a link to the car? It would remove some data redundancy.

**Comment by vvictor10** [comment]
It might. But, if I want to find a Tire by Id or name and I dont know anything about the car in the query, how do I get the Car that the Tire belongs to?

**Comment by emanuelez** [comment]
```java
realm.where(Car.class).equalTo(tires.id, "42").findFirst();
```

**Comment by vvictor10** [comment]
So, this will give me the Car which has the tire with id 42. Correct?
Good thought, let me think about it and see if it makes sense to get rid of that redundant reference.

**Comment by emanuelez** [comment]
Correct. Happy coding! :)
