### ISSUE TITLE
Remove finalizers and use PhantomReference

### ISSUE THREAD

**Issue by emanuelez** [realm/realm-java#905]

**Comment by emanuelez** [comment]
This branch has an example project called MemoryLeak that crashes after about 30 seconds on GenyMotion. There is also a file with log output from a crash: https://github.com/realm/realm-java/tree/cm-memory-leak https://github.com/realm/realm-java/blob/cm-memory-leak/experimental/memoryleak/logoutput.txt

Docs on Phantom:
http://www.kdgregory.com/index.php?page=java.refobj
http://blog.kdgregory.com/2014/06/finalizers.html

**Kenneth** By examining a dump of the heap shows that a large number of objects are finalized by not reclaimed by the garbage collector. There seems to be no memory leak. The fact that finalizers are very slow in Java implies that the garbage collector cannot keep up and delete objects.
The test app creates objects in one thread and queries the realm in another. Putting in a sleep in the creating thread seems to help the garbage collector a bit. The app is using about 3 MB initially. As a small experiment, the sleep time has been varied and the memory (heap size) is monitored.

    sleep = 50 ms: 49 MB after 2 minutes
    sleep = 75 ms; 33 MB after 2 minutes
    sleep = 125 ms; 15 MB after 2 minutes
    sleep = 250 ms; 7 MB after 2 minutes

**Emanuele** Useful presentation: https://www.youtube.com/watch?v=KTC0g14ImPc

**Comment by timanglade** [comment]
We need to do more performance testing of Realm + of this branch and decide whether we merge this or not.
