### ISSUE TITLE
Investigate conversion of field access to getters and setters

### ISSUE THREAD

**Issue by emanuelez** [realm/realm-java#908]

**Comment by emanuelez** [comment]
Relevant links:

https://issues.jboss.org/browse/JASSIST-212?_sscc=t
https://github.com/stephanenicolas/morpheus
https://github.com/jakewharton/hugo

**Comment by emanuelez** [comment]
Investigation done and fruitful

**Comment by srikalyan** [comment]
What is the outcome of this investigation, We really want this feature and I am really interested in adding this feature so please guide/help me  in adding this feature.

**Comment by telenewbie** [comment]
how to deal with this problem ,i wanna to override methods like toString() or equals()??

**Comment by ubuntudroid** [comment]
@telenewbie At the moment the only way to handle this is to create a wrapper object.

**Comment by ericmaxwell2003** [comment]
I did that recently with one of my Realm objects, where "Lyric" is a RealmObject, it looked like this...   
        private Lyric addToStringMethod(Lyric lyric) {
        Lyric augmentedLyric = new Lyric(){
            @Override
            public String toString() {
                return getLyricText();
            }
        };
        augmentedLyric.setId(lyric.getId());
        augmentedLyric.setLyricText(lyric.getLyricText());
        return augmentedLyric;
    }

Would be nice if this restriction could be lifted...

**Comment by AlokBansal8** [comment]
I want to implement data validation interface with each of my model. We need this. Please bring it soon, its been more than a year now.

**Comment by grennis** [comment]
I followed the link here from the "restrictions" section in which the link was titled "[we are currently working on lifting these restrictions](https://realm.io/docs/java/latest/#objects)". However it seems this issue is closed with no further progress. Has this been abandoned? The inability to add helper methods, validation methods, etc., to an object is kind of a total deal breaker!

**Comment by AlokBansal8** [comment]
@grennis :+1:

**Comment by cmelchior** [comment]
@grennis This task was for exploring the possibilities for how to solve it. We did that and found a technical solution. At this point we are almost done implementing it. You can follow it here: #2196

**Comment by grennis** [comment]
OK, great. I think probably you might want to update the docs to point there instead. Thanks!
