### ISSUE TITLE
Support adding own methods to objects

### ISSUE THREAD

**Issue by emanuelez** [realm/realm-java#909]

**Comment by emanuelez** [comment]
See: https://groups.google.com/forum/#!searchin/realm-java/complex$20data$20types/realm-java/4XwofSl-iwU/30p8Y6JWt5EJ

**Comment by Queatz** [comment]
+1 for a modern db this should be possible.  I've been doing it by starting the method names with 'get' but not sure if that's going to cause unexpected results?  Seems to work, but full support would be nice to have.

**Comment by caroth92** [comment]
+1 my team is reconsidering the use of Realm for our app since we need custom logic in our getters & setters

**Comment by cmelchior** [comment]
For reference (Five +1's from #637 has been transfered here).

**Comment by yolapop** [comment]
+1 would like to be able to use `toString()` method which is used in custom adapter a lot.

**Comment by HitOdessit** [comment]
+1 for ability to override at least `toString()` and `equals()` in `RealmObject`

**Comment by nmoskalenko** [comment]
+1 must have feature

**Comment by AndreasBackx** [comment]
Any updates on this?

**Comment by Onejjy** [comment]
+1

For me, this feature is a must-have :/ Is it planned ?

**Comment by danpe** [comment]
+1 Can't override equals ??

**Comment by Queatz** [comment]
Right now how I work around this is by adding a getter for an ignored field

```java
@Ignore
String method;

public String getMethod();
```

Verrrrrry temporary :)

**Comment by emanuelez** [comment]
We are actively working on it and #1216 is part of the solution

**Comment by dommerq** [comment]
:+1: @emanuelez

**Comment by nolanamy** [comment]
:+1:

**Comment by iflatness** [comment]
I've discovered this can be implemented using the existing realm code by using default methods in an interface (which can be utilized using the [gradle-retrolambda](https://github.com/evant/gradle-retrolambda) plugin. For example a simplification of an interface of mine is:

```
public interface BaseModel {
    boolean isValid();
    void removeFromRealm();

    default String getUrlString() {
        return ModelType.get(this).toString() + "/" + getId();
    }

    String getId();
    void setId(String id);
}
```
By having my model classes implement BaseModel, I can use getUrlString without issue. This works due to the retrolambda plugin modifying code after the realm plugin. Like normal interfaces you can't define equals, toString, or hashCode, but this is a nice workaround until the folks at realm implement an official way. :)

**Comment by azizj1** [comment]
+1 I seriously can't use Realm until this is added. I would have to add another layer of model objects, and then use an object to object mapper, which defeats the purpose of Realm.

**Comment by emanuelez** [comment]
We are actively working on this :)

**Comment by AndreasBackx** [comment]
Any information on when this will be ready for production?

**Comment by emanuelez** [comment]
We can't promise a delivery date since we prioritize support first, then bug fixing, and finally the development of new features. Which means that the release date depends on the support load and the bugs to fix.

I know it might be unpleasant not being able to rely on a precise date, but focusing on support is really important to us.

**Comment by shawnwall** [comment]
+1

**Comment by hamen** [comment]
+1

**Comment by JJSarrasin** [comment]
+1

**Comment by lucho-yankov** [comment]
+1

**Comment by mmvicsonvictor** [comment]
+1

**Comment by jcarty** [comment]
+1

**Comment by josdejong** [comment]
Any news on this? 

It's quite a showstopper that Realm doesn't allow logic in getters/setters and doesn't allow custom methods (not even a `toString`). Like it is now, I have to write all logic regarding serialization of fields externally, which sort of defeats the purpose of the "object oriented" approach of Realm. 

Maybe [twig-persist](https://code.google.com/p/twig-persist/wiki/Quickstart) (for [Google App Engine](https://cloud.google.com/appengine/docs)) can serve as a source of inspiration here. The project is retired I think but had all these things right.

I'm really looking forward to these restrictions being resolved!

**Comment by olegflo** [comment]
+1, would be happy to hear some news. That's must have feature, we are all looking forward to have this released :)

**Comment by emanuelez** [comment]
Here are some news as requested.

This feature is actively being worked on:
 * #1216 
 * #1351

For these PRs to be merged we will need some major modifications to our build-system and to the way we distribute Realm. Both are currently being worked on.

**Comment by AndreasBackx** [comment]
@emanuelez Is there an ETA window? I'm just waiting for this feature before switching to Realm.

**Comment by dalinaum** [comment]
@AndreasBackx We unfortunately don't have any ETA at the moment though, sorry.

**Comment by cvoronin** [comment]
This is really a showstopper, when I can not add any domain logic to POJO, I don't need such a POJO at all.
I have a reach domain logic in my projects, so it is critical to me: validations, calculations, navigations etc.
I understand there are issues, however in ORMLite or in Hibernate (for "big" java) there is no such a problem. 

When we have no domain logic at all, we get the http://www.martinfowler.com/bliki/AnemicDomainModel.html

**Comment by emanuelez** [comment]
We're actively working on this and it's going to be ready for of the next releases.

#1585 is the first step towards it and it's almost ready to be merged. It's going throw the last stages of its review.
#1265 and #1351 Are coming next.

So as you can see all the code is basically ready. It just needs to go throw extensive reviews and testing.

**Comment by olegflo** [comment]
@emanuelez sounds as good news, thank you. When approximately btw is planed release with this?

**Comment by emanuelez** [comment]
That I cannot say. As you know we prioritise support and bug fixing over new features, which means that release dates depend on the support pressure we are under.

**Comment by jiahaoliuliu** [comment]
+1 on this. Actually it is quite hard to integrate with gson in Realm. The documentation refers us to create a customized class for JsonSerializer, which does exactly the same if we are not using Json. Thus, I want to add methods which parse the instance to json and create an instance from json inside of the class, so I can have them localized in the proper class.

**Comment by KingWu** [comment]
+1

**Comment by dareniott** [comment]
+1

**Comment by LivioGama** [comment]
+1 must have feature

**Comment by lourenci** [comment]
+1

**Comment by organillero** [comment]
+1

**Comment by aafa** [comment]
+1 long awaited feature

**Comment by edBaev** [comment]
+1

**Comment by alexzaitsev** [comment]
+1

**Comment by callmepeanut** [comment]
At least, equals and hashCode should be able to override.

**Comment by miguelmartin75** [comment]
:+1:

**Comment by borwoj** [comment]
+1 fingers crossed

**Comment by mateusgrb** [comment]
+1 Not being able to have your own methods is a dealbreaker in many situations. Must-have feature!

**Comment by hquezada** [comment]
+1

**Comment by philipgrafat** [comment]
+1 Also a must-have for me

**Comment by monossido** [comment]
+1
ATM I resolved with a static Utils class inside my RealmObject class

**Comment by muntasirsyed** [comment]
+1

Static Utils class inside RealmObject works as a workaround, however any use of fields (non-static) must of course be passed into the util methods as parameters.

**Comment by tayhalla** [comment]
+2

**Comment by Saketme** [comment]
You guys may want to stop replying with +1s. This feature is already under development and is expected to be released in the next update: https://github.com/realm/realm-java/pull/2196 :)

**Comment by AndreasBackx** [comment]
@Saketme I agree. There are 44 people watching this issue and every time a useless +1 comes up we get notification which defeats the purpose of watching issues too.

**Comment by mateusgrb** [comment]
I agree with @Saketme, but just in case anyone from Github is ever reading this, it seems to me that the amount of +1s commented indicates that a native button to +1 an issue(or something similar) would be welcome.

**Comment by Saketme** [comment]
@AndreasBackx @mateusgrb Totally. Developers have been requesting Github to fix this problem since long. GitLab has this feature where people can vote on issues so that the participants don't get notified for comments that don't contribute to the discussion.

Anyway, let's not discuss this here.

**Comment by mymvercher** [comment]
+1

**Comment by long-greg-c** [comment]
+1

**Comment by srmds** [comment]
:+1:

**Comment by drumcap** [comment]
+1

**Comment by scijoker** [comment]
+1

**Comment by luckyandyzhang** [comment]
+1

**Comment by toantran-ea** [comment]
This is important for case when we retrieved json object from API and mapping this object into Realm DB. 
Not having the ability to add extra fields/method to handle this will force us to clone 2 types of object. One for API response, and another for saving to Realm DB (extends RealmObject)  :cry:

**Comment by beeender** [comment]
@toantran-ea This has already been implemented in 0.88.x. Try the latest release?

**Comment by toantran-ea** [comment]
@beeender omg, should have update my Realm dependency first, thanks for pointing out, updating my legacy code now.

**Comment by peterbetos** [comment]
I can't see on the Javadoc page how we can add a custom method. Should I add an annotation for it to be ignored by realm?
https://realm.io/docs/java/0.79.0/api/io/realm/RealmObject.html

**Comment by dalinaum** [comment]
Hello @peterbetos You don't need to add an annotation for your custom method. Just making your custom method is enough.

**Comment by peterbetos** [comment]
Thanks, it worked by the way 👍
