### ISSUE TITLE
RealmQuery.contains() ignores caseSensitive flag

### ISSUE THREAD

**Issue by Ekzy** [realm/realm-java#912]
Hello!
My query is pretty simple:
```
realm.where(Region.class)
    .contains("title", query, false)
    .findAllSorted("title")
```
But result is the same no matter what flag I am using. I suppose that's because I store not english symbols in realm.

**Comment by bmunkholm** [comment]
Hi!
That could be. Please post the data you have and what you expect but don't get.
Thanks!

**Comment by Ekzy** [comment]
This prints 1 instead of 2:
```
List<Text> list = new ArrayList<>();
list.add(new Text("Москва"));
list.add(new Text("москва"));

Realm realm = Realm.getInstance(this);
realm.beginTransaction();
realm.clear(Text.class);
realm.copyToRealm(list);
realm.commitTransaction();

long count = realm.where(Text.class).contains("title", "мос", false).count();
Toast.makeText(this, String.valueOf(count), Toast.LENGTH_SHORT).show();
realm.close();
```
Text class:
```
public class Text extends RealmObject {
	private String title;

	public Text() {
	}
	public Text(String title) {
		this.title = title;
	}
	public String getTitle() {
		return title;
	}
	public void setTitle(String title) {
		this.title = title;
	}
}
```

**Comment by cmelchior** [comment]
Hi @Ekzy 
Sorry for the late reply. Realm currently doesn't support case insensitive searches for non-latin characters. You can read more under our Current limitations section here: http://realm.io/docs/java/0.79.0/#current-limitations.

**Comment by petersnoopy** [comment]
Is there a workaround to this problem to offer case insensitive search for european language especially swedish, norwegian and german?

**Comment by Ekzy** [comment]
@petersnoopy, I added a dublicate of the text field in lower case and do the search by this field.

**Comment by Saketme** [comment]
How difficult is it to support locales other than English?

**Comment by cmelchior** [comment]
Hi @Saketme It is unfortunately rather difficult, as it require us to use the system library ICU to do so. This library is rather large ~20 MB, so will be unfeasible for us to bundle with the Realm library itself. It is present on Android devices, but there is no guarantee in what version. We some ideas we want to investigate though, but any progress is tracked here: #1031

**Comment by Saketme** [comment]
Using Android's `Locale` class seems perfect :)
