### ISSUE TITLE
DOC: Update GSON documentation with TypeAdapter for primitive lists

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#915]
We should add a section to our GSON section about how to convert primitive lists to wrapper objects. It is possible to do seamlessly using a TypeAdapter. It is only a work-around until we add proper support, but the issue has been brought up a couple of times. 

See this: http://stackoverflow.com/questions/28733024/gson-deserialization-of-liststring-into-realmlistrealmstring

**Comment by Kml55** [comment]
I followed stackoverflow link but couldn't write read method of TypeAdapter correctly.

**Comment by Kml55** [comment]
I need help to deserialize big modal with a field list of ints.
 help http://stackoverflow.com/questions/29493101/gson-deserialization-for-realm-list-of-primitives
