### ISSUE TITLE
Query works wrong in RemoteViewsFactory

### ISSUE THREAD

**Issue by devholic** [realm/realm-java#919]
Hi,

I'm developing an application with AppWidget.
When I query in RemoteViewsFactory, I got unexpected results.
For example, result count must be 0, but I got 1.
At first, I thought that my query had a problem, but I checked query in normal Activity, it works well.

Using Realm Android 0.79.0

Thanks for the support.

**Comment by cmelchior** [comment]
Without any information on how to reproduce this we cannot give you any qualified help. See here for info on creating issues: https://github.com/realm/realm-java#filing-issues

**Comment by devholic** [comment]
After getting data from realm and closing realm solve this problem.
