### ISSUE TITLE
Fatal signal when trying to compact realm file

### ISSUE THREAD

**Issue by zsavely** [realm/realm-java#921]
This happened when I tried to compact my Realm file from a service, which has the option `android:process=":helper"` in the `AndroidManifest.xml`. The application was also running at that moment (in a normal process, with activity) and, yes, not all instances of Realm were closed. And unfortunately I didn't get Java exception. (my process `:helper` closed without any visible exceptions). So, I thought it might be helpful for you.
```Java
I/service(19575): onStartCommand
D/dalvikvm(19575): GC_CONCURRENT freed 260K, 9% free 12348K/13511K, paused 12ms+22ms, total 53ms
D/dalvikvm(19575): Trying to load lib /data/data/com.example/lib/libtightdb-jni.so 0x42b4c378
D/dalvikvm(19575): Added shared lib /data/data/com.example/lib/libtightdb-jni.so 0x42b4c378
A/libc(19575): Fatal signal 7 (SIGBUS) at 0x5d7be9cc (code=2), thread 19590 (Thread-19579)
```

In service I used:
```Java
try {
	Realm.compactRealmFile(this);
} catch (Exception e) {
	e.printStackTrace();
}
```

* Realm 0.79.0
* Samsung Galaxy S3
* Android 4.1.2

**Comment by cmelchior** [comment]
Hi @zsavely 
That option moves the service to another process. Currently we don't have multi-process support, but it is being worked on.

**Comment by cmelchior** [comment]
I just checked our documentation and apparently we forgot to document that limitation under our Limitations section for Java. I have added it now.
