### ISSUE TITLE
Realm.getInstance() with encryption key fails for second time

### ISSUE THREAD

**Issue by NirpE** [realm/realm-java#925]
Getting Realm instance with enrypted database causes exception. This seems to happening when I first uninstall and install application, then launch -> close -> open app. 

In real usage the error occurs always when I'm handling Realm instances between threads and opening new instances in those. I have debugged that the key is the same in each thread.

Using Realm with Android Studio:

<b> compile 'io.realm:realm-android:0.79.1' </b>

<code>
        byte[] testKey = "58d184c223a7fe6544c89586b6cb06d8843c24333f62a2ff74e78b1e07b550bb".getBytes();

        Realm.getInstance(this, "test", testKey); // This one ok
        Realm.getInstance(this, "test", testKey); // Line after throws exception

    Caused by: java.lang.IllegalStateException: Wrong key used to decrypt Realm.
            at io.realm.Realm.createAndValidate(Realm.java:508)
            at io.realm.Realm.create(Realm.java:480)
            at io.realm.Realm.getInstance(Realm.java:397)
</code>

**Comment by juliendn** [comment]
It seems to be already fixed by commit 6a8d16acd9c7b1012be0402963884c5f57de453d

**Comment by NirpE** [comment]
Closing as duplicate.
