### ISSUE TITLE
createAllFromJson with PrimaryKey

### ISSUE THREAD

**Issue by thorsten7** [realm/realm-java#930]
Hi,

I added a primary Key to my class. I use createAllFromJson. The expected result is a PrimaryKeyException while updating through createAllFromJson. I tried a while but did not find a working solution with createAllFromJson. Is there a best practice for "createOrUpdateAllFromJson"?

Thank you in advance,
Thorsten

**Comment by cmelchior** [comment]
I am not sure I understand your usecase. Why would you expect an exception when using createAllFromJson?

The difference between ```createAllFromJson()``` and ```createOrUpdateAllFromJson()``` is that the later does require a primary key to work, while the first will always create new copies even though primary keys are defined.

**Comment by thorsten7** [comment]
Okay thank you for your help. My problem is that I was blind while requesting createOrUpdateAllFromJson and not recognizing that there already is one. Sorry it's Friday ;-)
