### ISSUE TITLE
0.80 from jcentral

### ISSUE THREAD

**Issue by HPIWicket** [realm/realm-java#936]
Hey,

Is it possible to get the 0.80 version from jcentral or do I have to build the library myself? 

Regards
Richard

**Comment by cmelchior** [comment]
Our master is released as a SNAPSHOT version, so you can use that instead of building yourself. It uses a slightly different repository though:

```
    repositories {
        jcenter()
        maven {
            url 'http://oss.jfrog.org/artifactory/oss-snapshot-local'
        }
    }

    compile 'io.realm:realm-android:0.79.2-SNAPSHOT'
```
The version can be found here: https://github.com/realm/realm-java/blob/master/version.txt
Currently the latest is ```0.79.2-SNAPSHOT```

**Comment by HPIWicket** [comment]
Thanks for the reply, we will do that until 0.80 is out.
