### ISSUE TITLE
Doing long requests on UI Thread?

### ISSUE THREAD

**Issue by spierce7** [realm/realm-java#939]
I've been doing a lot of reading around realm recently, and it seems really cool. I'm planning testing it out on an existing project, so I'm planning the migration, and the threading model is tripping me up.

1. I can't pass any of the models between threads, which means I need to query data on the main thread. Doesn't this mean I'll be blocking the main thread then? Even assuming realm has amazing caching, on app load or whenever the first time the data is loaded it's going to have to load all that from disk and block the main thread, which is against the recommendations of both Android and iOS platforms. Am I missing something? Is there a supported way around this?

2. What if my views need thousands of model objects? Suddenly I've got lag in my UI with no way around it? Maybe there is an asynchronous API that i'm just not seeing?

3. It also seems like this threading model encourages writes on the main thread. If I have any data to save (especially large amounts), I've found it best practice to do this in a background thread so as not to create frame jank. If I have a screen where the user edits some data and then saves it, and then I immediately begin to transition to another screen where I need to load that same data that's been saved, I end up with a race condition. I'm given 2 options with realm it seems: 1. Block the user on the screen until the data finishes saving, or 2. Save the data on the main thread. Android makes AsyncTasks execute synchronously with one another on more recent versions of android to handle bugs like this. How should this be handled with realm? Is writing on the main thread not a big deal?

**Comment by cmelchior** [comment]
Hi @spierce7 

You are correct that currently we don't allow RealmObjects to be parsed between threads. Originally it was to avoid concurrency issues and is also one of the reasons Realm are as fast as it is. That said, those restrictions might have been to strict and we are currently exploring ways to make it easier to work with the Android framework in general.

A few bullet points to answer you questions:
- We are working on introducing async queries for queries that takes a long time. That will hopefully be ready soon.
- RealmResults are lazyloaded much like cursors, so eg. in a listview, only the items actually shown are loaded.
- Small writes on the UI thread should be OK.
- You can use standalone objects and Realm.copyToRealm() to create objects can be parsed between threads and saved later.
- Saving large amounts of data should still be done on a background thread, but such data are usually never created on the UI thread anyway.

**Comment by spierce7** [comment]
Are there benchmarks to show that writing on the UI thread is ok with realm?

Is there any timeline on the async queries? I've found some older issues where you guys reference them, and it sounds like something you hoped to get in several months ago.

I really appreciate the work you guys have done on realm, and it seems really cool. I'm really digging the api and the compile time code generation. Development could indeed drastically speed up. Everything seems very well thought out, except for the ability to offload saving and querying to a separate thread. I think that's something we need on mobile to create consistent, high quality mobile applications.

**Comment by cmelchior** [comment]
No benchmarks for that no. As that really depends on what and how many data you a writing.
The work on the core database for allowing this is almost done now, after which need need to expose the API. We don't have any time frame, except to say it is highest on our internal priority list to get this fixed once the core API's are in place.
