### ISSUE TITLE
java.lang.IllegalStateException: Mutable method call during read transaction.

### ISSUE THREAD

**Issue by Kaustubh-Deshmukh** [realm/realm-java#940]
```final Realm realm = Realm.getInstance(context);
    realm.beginTransaction();
    trip.removeFromRealm();
    realm.commitTransaction();```

I am getting IllegalStateException for trip.removeFromRealm();
I have annotated class with @RealmClass but no luck. Not able to get why I am facing this issue. Please help me.

**Comment by cmelchior** [comment]
Hi @Kaustubh-Deshmukh 
Where are you getting your trip object from?

**Comment by Kaustubh-Deshmukh** [comment]
```
final Realm realm = Realm.getInstance(context);
RealmQuery<CompletedRealmTrip> completedRealmTripRealmQuery
                            = realm.where(CompletedRealmTrip.class).equalTo("source", "test");
final RealmResults<CompletedRealmTrip> results = completedRealmTripRealmQuery.findAll();
for (int i = 0; i < results.size(); ++i) {
                        final CompletedRealmTrip trip = results.get(i);

                        // my code..
                        trip.removeFromRealm();
}
```
This is how I am getting trip class. Correct me if I am wrong.

**Comment by emanuelez** [comment]
I think that iterating backwards will solve your problem. See this github
issue: https://github.com/realm/realm-java/issues/789#issuecomment-71325591

for (int i = results.size(); i <= 0; i--) {
                        final CompletedRealmTrip trip = results.get(i);

                        // my code..
                        trip.removeFromRealm();
}



On Tue, Mar 10, 2015 at 1:57 PM, Kaustubh <notifications@github.com> wrote:

> final Realm realm = Realm.getInstance(context);
> RealmQuery<CompletedRealmTrip> completedRealmTripRealmQuery
>                             = realm.where(CompletedRealmTrip.class).equalTo("source", "test");
> final RealmResults<CompletedRealmTrip> results = completedRealmTripRealmQuery.findAll();
> for (int i = 0; i < results.size(); ++i) {
>                         final CompletedRealmTrip trip = results.get(i);
>
>                         // my code..
>                         trip.removeFromRealm();
> }
>
> This is how I am getting trip class. Correct me if I am wrong.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/realm/realm-java/issues/940#issuecomment-78047476>.
>



-- 
*Emanuele Zattin* (@emanuelez <https://twitter.com/emanuelez>)
SW Engineer & CI Specialist

**Comment by cmelchior** [comment]
Hi @Kaustubh-Deshmukh 
I assume the above fixed your issue. Please add additional information if that is not the case.
