### ISSUE TITLE
Where is the realm-annotations-processor-VERSION.jar  ???

### ISSUE THREAD

**Issue by sphairo** [realm/realm-java#943]
I downloaded the release package and I unzipped but not found realm-annotations ... .jar ???

http://realm.io/docs/java/0.70.1/

**Comment by emanuelez** [comment]
Hello,

please add more details in order for us to be able to help you.
You can see some guidelines on how to file issues here: https://github.com/realm/realm-java/blob/master/README.md#filing-issues

We moved away from having the annotation processor residing in another jar file so the documentation for version 0.70.1 do not apply anymore.

**Comment by cmelchior** [comment]
Hi @sphairo 
Those docs are from our initial release. Please see here for the latest info on how to to use Realm with either Android Studio or Eclipse: http://realm.io/docs/java/0.79.0 

Feel free to reopen if the additional information there doesn't work for you.
