### ISSUE TITLE
Error:Configuration with name 'default' not found. 

### ISSUE THREAD

**Issue by sphairo** [realm/realm-java#945]
this error after adding:

dependencies {
    apt fileTree(dir: 'libs', include: ['*.jar'])
    compile project(':realm')
}

My complete build.gradle is this:

buildscript {
    repositories {
        mavenCentral()
    }
    dependencies {
        classpath 'com.neenbedankt.gradle.plugins:android-apt:1.4'
    }
}

apply plugin: 'com.android.application'
apply plugin: 'com.neenbedankt.android-apt'

android {
    compileSdkVersion 21
    buildToolsVersion "21.1.2"

    defaultConfig {
        applicationId "mx.sphairo.realmtest"
        minSdkVersion 19
        targetSdkVersion 21
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}

dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:21.0.3'
    compile 'com.android.support:support-v4:21.0.3'

    apt fileTree(dir: 'libs', include: ['*.jar'])
    compile project(':realm')
}

**Comment by sphairo** [comment]
The solution for installation on Android Studio is:

Maven
Make sure your project uses jcenter as a dependency repository (default on latest version of the Android Gradle plugin)
Add compile 'io.realm:realm-android:0.79.0' to the dependencies of your project
In the Android Studio menu: Tools->Android->Sync Project with Gradle Files
Jar
Download the release package and unzip.
Create a new project with Android Studio
Copy the realm-VERSION.jar folder into app/libs
In the Android Studio menu: Tools->Android->Sync Project with Gradle Files

ProGuard
Realm generates a proxy class for each RealmObject at compile time. To ensure that these classes can be found after running an obufuscation and static analysis tool like ProGuard add the configuration below to your ProGuard configuration file.

-keepnames public class * extends io.realm.RealmObject
-keep class io.realm.** { *; }
-dontwarn javax.**
-dontwarn io.realm.**

**Comment by emanuelez** [comment]
Did you answer your own question or do you need more support?

**Comment by sphairo** [comment]
I answered my own question, I resolved my problem adding compile 'io.realm: realm-android: 0.79.0' to the dependencies of my project after added realm-VERSION.jar folder into app/libs finally on FILE proguard-rules.pro added:

-keepnames public class * extends io.realm.RealmObject
-keep class io.realm.** { *; }
-dontwarn javax.**
-dontwarn io.realm.**
