### ISSUE TITLE
RealmList commit problem

### ISSUE THREAD

**Issue by adelburekovic** [realm/realm-java#946]
Im joining two RealmLists of the same type from two different classes for the purpose of using both of them in RealmBaseAdapter:
 
<pre>
  <code>
RealmList<IncomeExpense> incomeExpenseList = month.getIncomeExpenseList();       

incomeExpenseList.addAll(companyInfo.getRecurringIncomeExpenseList());   

RealmResults<IncomeExpense> finalQuery = incomeExpenseList.where()
                    .equalTo("isIncome",false)
                    .findAll();
 
costsAdapter = new CostsAdapter(mActivity, R.id.costsList, finalQuery, true);

</code>
</pre>

The problem is that this join of both classes actualy is getting commited and i don't understand why, because as you can see i don't have <code>realm.beginTransaction()</code> and <code>realm.commitTransaction()</code> nowhere.

So my question is: 
- why is this happening? 
- and is there any better way for joining 2 lists and putting them in RealmBaseAdapter.

**Comment by emanuelez** [comment]
Where do `month` and `companyInfo` come from? Are they standalone objects or are they backed by Realm?

**Comment by adelburekovic** [comment]
Both Month and CompanyInfo are RealmObjects that include RealmList<IncomeExpense> objects.

**Comment by emanuelez** [comment]
What I mean is: do they come from a query, from `Realm.createObject()`, or were they instantiated with `new`?

**Comment by adelburekovic** [comment]
My bad. Here is the the rest of the code.

<pre>
<code>
RealmQuery<Year> query = realm.where(Year.class);
        query.equalTo("year", current_year);


        Year myYear = query.findFirst();

        if (myYear != null) {
            Month month = myYear.getMonths().where().equalTo("month", current_month).findFirst();
            RealmResults<IncomeExpense> incomeExpenses = month.getIncomeExpenseList()
                    .where()
                    .equalTo("isIncome", false).findAll();

            CompanyInfo companyInfo = realm.where(CompanyInfo.class).findFirst();

...
        
</code>
</pre>

**Comment by emanuelez** [comment]
To answer your first question I'll need some time to investigate.
For the second question my answer is that you should implement your own adapter getting inspired by the implementation of RealmBaseAdapter, just to accept two RealmResults instead of one.
Don't try to join the lists just ignoring generics. Realm relies on them heavily.

**Comment by emanuelez** [comment]
Did you manage to solve your issue?

**Comment by cmelchior** [comment]
Closing due to no response
