### ISSUE TITLE
Realm app crashes with io.realm.exceptions.RealmException: Could not find io.realm.RealmJsonImpl

### ISSUE THREAD

**Issue by CyberGriZzly** [realm/realm-java#947]
Hello,
I want to implement some list view with the elements from a realm DB and I set up the RealmAdapterExample project
When it gets to the line realm = Realm.getInstance(this); it crashes with

java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.realmadapterexample/com.example.realmadapterexample.AdapterExampleActivity}: io.realm.exceptions.RealmException: Could not find io.realm.RealmJsonImpl
...
Caused by: java.lang.ClassNotFoundException: Didn't find class "io.realm.RealmJsonImpl" on path: DexPathList[[zip file "/data/app/com.example.realmadapterexample-2/base.apk"],nativeLibraryDirectories=[/data/app/com.example.realmadapterexample-2/lib/x86, /vendor/lib, /system/lib]]
What did I do wrong?
Best regards and sorry for the inconvinience

**Comment by emanuelez** [comment]
It looks like the annotation processor is not running properly.
Do you have a complete log of the build?

**Comment by CyberGriZzly** [comment]
03-10 21:29:03.660: W/ActivityThread(2661): Application com.example.realmadapterexample is waiting for the debugger on port 8100...
03-10 21:29:03.660: I/System.out(2661): Sending WAIT chunk
03-10 21:29:03.857: I/art(2661): Debugger is active
03-10 21:29:03.864: I/System.out(2661): Debugger has connected
03-10 21:29:03.864: I/System.out(2661): waiting for debugger to settle...
03-10 21:29:04.148: I/System.out(2661): waiting for debugger to settle...
03-10 21:29:04.349: I/System.out(2661): waiting for debugger to settle...
03-10 21:29:04.553: I/System.out(2661): waiting for debugger to settle...
03-10 21:29:04.755: I/System.out(2661): waiting for debugger to settle...
03-10 21:29:04.989: I/System.out(2661): waiting for debugger to settle...
03-10 21:29:05.190: I/System.out(2661): waiting for debugger to settle...
03-10 21:29:05.399: I/System.out(2661): waiting for debugger to settle...
03-10 21:29:05.601: I/System.out(2661): waiting for debugger to settle...
03-10 21:29:05.801: I/System.out(2661): waiting for debugger to settle...
03-10 21:29:06.002: I/System.out(2661): waiting for debugger to settle...
03-10 21:29:06.202: I/System.out(2661): waiting for debugger to settle...
03-10 21:29:06.403: I/System.out(2661): debugger has settled (1342)
03-10 21:29:14.957: D/AndroidRuntime(2661): Shutting down VM
03-10 21:29:14.957: D/AndroidRuntime(2661): --------- beginning of crash
03-10 21:29:14.958: E/AndroidRuntime(2661): FATAL EXCEPTION: main
03-10 21:29:14.958: E/AndroidRuntime(2661): Process: com.example.realmadapterexample, PID: 2661
03-10 21:29:14.958: E/AndroidRuntime(2661): java.lang.RuntimeException: Unable to start activity ComponentInfo{com.example.realmadapterexample/com.example.realmadapterexample.AdapterExampleActivity}: io.realm.exceptions.RealmException: Could not find io.realm.RealmJsonImpl
03-10 21:29:14.958: E/AndroidRuntime(2661): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2298)
03-10 21:29:14.958: E/AndroidRuntime(2661): 	at android.app.ActivityThread.handleLaunchActivity(ActivityThread.java:2360)
03-10 21:29:14.958: E/AndroidRuntime(2661): 	at android.app.ActivityThread.access$800(ActivityThread.java:144)
03-10 21:29:14.958: E/AndroidRuntime(2661): 	at android.app.ActivityThread$H.handleMessage(ActivityThread.java:1278)
03-10 21:29:14.958: E/AndroidRuntime(2661): 	at android.os.Handler.dispatchMessage(Handler.java:102)
03-10 21:29:14.958: E/AndroidRuntime(2661): 	at android.os.Looper.loop(Looper.java:135)
03-10 21:29:14.958: E/AndroidRuntime(2661): 	at android.app.ActivityThread.main(ActivityThread.java:5221)
03-10 21:29:14.958: E/AndroidRuntime(2661): 	at java.lang.reflect.Method.invoke(Native Method)
03-10 21:29:14.958: E/AndroidRuntime(2661): 	at java.lang.reflect.Method.invoke(Method.java:372)
03-10 21:29:14.958: E/AndroidRuntime(2661): 	at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:899)
03-10 21:29:14.958: E/AndroidRuntime(2661): 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:694)
03-10 21:29:14.958: E/AndroidRuntime(2661): Caused by: io.realm.exceptions.RealmException: Could not find io.realm.RealmJsonImpl
03-10 21:29:14.958: E/AndroidRuntime(2661): 	at io.realm.Realm.getRealmJson(Realm.java:263)
03-10 21:29:14.958: E/AndroidRuntime(2661): 	at io.realm.Realm.<init>(Realm.java:161)
03-10 21:29:14.958: E/AndroidRuntime(2661): 	at io.realm.Realm.createAndValidate(Realm.java:516)
03-10 21:29:14.958: E/AndroidRuntime(2661): 	at io.realm.Realm.create(Realm.java:480)
03-10 21:29:14.958: E/AndroidRuntime(2661): 	at io.realm.Realm.getInstance(Realm.java:397)
03-10 21:29:14.958: E/AndroidRuntime(2661): 	at io.realm.Realm.getInstance(Realm.java:359)
03-10 21:29:14.958: E/AndroidRuntime(2661): 	at io.realm.Realm.getInstance(Realm.java:340)
03-10 21:29:14.958: E/AndroidRuntime(2661): 	at com.example.realmadapterexample.AdapterExampleActivity.onCreate(AdapterExampleActivity.java:45)
03-10 21:29:14.958: E/AndroidRuntime(2661): 	at android.app.Activity.performCreate(Activity.java:5933)
03-10 21:29:14.958: E/AndroidRuntime(2661): 	at android.app.Instrumentation.callActivityOnCreate(Instrumentation.java:1105)
03-10 21:29:14.958: E/AndroidRuntime(2661): 	at android.app.ActivityThread.performLaunchActivity(ActivityThread.java:2251)
03-10 21:29:14.958: E/AndroidRuntime(2661): 	... 10 more
03-10 21:29:14.958: E/AndroidRuntime(2661): Caused by: java.lang.ClassNotFoundException: io.realm.RealmJsonImpl
03-10 21:29:14.958: E/AndroidRuntime(2661): 	at java.lang.Class.classForName(Native Method)
03-10 21:29:14.958: E/AndroidRuntime(2661): 	at java.lang.Class.forName(Class.java:308)
03-10 21:29:14.958: E/AndroidRuntime(2661): 	at java.lang.Class.forName(Class.java:272)
03-10 21:29:14.958: E/AndroidRuntime(2661): 	at io.realm.Realm.getRealmJson(Realm.java:258)
03-10 21:29:14.958: E/AndroidRuntime(2661): 	... 20 more
03-10 21:29:14.958: E/AndroidRuntime(2661): Caused by: java.lang.ClassNotFoundException: Didn't find class "io.realm.RealmJsonImpl" on path: DexPathList[[zip file "/data/app/com.example.realmadapterexample-2/base.apk"],nativeLibraryDirectories=[/data/app/com.example.realmadapterexample-2/lib/x86, /vendor/lib, /system/lib]]
03-10 21:29:14.958: E/AndroidRuntime(2661): 	at dalvik.system.BaseDexClassLoader.findClass(BaseDexClassLoader.java:56)
03-10 21:29:14.958: E/AndroidRuntime(2661): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:511)
03-10 21:29:14.958: E/AndroidRuntime(2661): 	at java.lang.ClassLoader.loadClass(ClassLoader.java:469)
03-10 21:29:14.958: E/AndroidRuntime(2661): 	... 24 more
03-10 21:29:14.958: E/AndroidRuntime(2661): 	Suppressed: java.lang.ClassNotFoundException: io.realm.RealmJsonImpl
03-10 21:29:14.958: E/AndroidRuntime(2661): 		at java.lang.Class.classForName(Native Method)
03-10 21:29:14.958: E/AndroidRuntime(2661): 		at java.lang.BootClassLoader.findClass(ClassLoader.java:781)
03-10 21:29:14.958: E/AndroidRuntime(2661): 		at java.lang.BootClassLoader.loadClass(ClassLoader.java:841)
03-10 21:29:14.958: E/AndroidRuntime(2661): 		at java.lang.ClassLoader.loadClass(ClassLoader.java:504)
03-10 21:29:14.958: E/AndroidRuntime(2661): 		... 25 more
03-10 21:29:14.958: E/AndroidRuntime(2661): 	Caused by: java.lang.NoClassDefFoundError: Class not found using the boot class loader; no stack available

**Comment by emanuelez** [comment]
That a logcat, not a build log :)
I'm not sure if Eclipse allows to see the output of a build.
A better way might be to run the build from the command line as described here: http://codeseekah.com/2012/02/09/command-line-android-development-basics/

**Comment by CyberGriZzly** [comment]
hmmm I've put the annotation @RealmClass before the model class (that wasn't the case in the IntroExampleActivty) and it works.
You've said that the annotation processor is not running properly and I remembered point 6 - In order to trigger the annotation processor, you must add the annotation @RealmClass before every one of your RealmObject subclasses.

May I ask why in the intro project that was not needed and in this it is?

**Comment by emanuelez** [comment]
It only depends on the JDK version. JDK 6 does not honor the inheritance property, while JDK 7 and 8 work fine. I'm not sure about EJC.

**Comment by CyberGriZzly** [comment]
I haven't changed the JDK version (1.7.0_55) since I began to try realm. In the example sources there is no annotation, that is why I didn't put it. But in this case it was needed.
Thank you very much for your help and the promptness of you answers.

**Comment by cmush** [comment]
Hey, @emanuelez. I'm getting the same error (java.lang.NoClassDefFoundError:) when I run my realm app on android 2.3.3. Does this mean that Realm is incompatible with older versions of Android? Is a support library available?
