### ISSUE TITLE
Realm gets NullPointerException when I try to delete

### ISSUE THREAD

**Issue by ciromine** [realm/realm-java#951]
I have an Android app that shows a routes in a map, I receive the data from my own web services in JSON.

The "available" fields indicates if this routes is still active (true) or no (false). If the route is active is necessary create or uptade (if just exists) and works perfect.

Else "available" == false, it's time to delete.

```java
else
{
    synchronized(realm){
        final Ruta ruta = realm.where(Ruta.class)
                 .equalTo("id", json.getLong("id"))
                 .findFirst();
        if(ruta != null)
        {
            realm.beginTransaction();
            if(ruta.getCoordenadas().size() > 0)
                ruta.getCoordenadas().clear();
            ruta.removeFromRealm();
            realm.commitTransaction();
        }
    }
}

//If I create, update or delete I Save the last update Date of routes 
synchronized(realm){
    realm.beginTransaction();
    change.setCod(changeBdd);
    Log.e("changeBdd",changeBdd);
    realm.commitTransaction();
}
```

And this not work, if I do this for first time, REALM "delete" the route, but if I received the same Json for second time right now after delete. REALM find again the route, but when try to destroy crush the app.

```java
java.lang.RuntimeException: An error occured while executing doInBackground()
at android.os.AsyncTask$3.done(AsyncTask.java:300)
at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
at java.util.concurrent.FutureTask.run(FutureTask.java:242)
at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
at java.lang.Thread.run(Thread.java:841)
Caused by: java.lang.NullPointerException
at com.app.mapApp.ActivityPrincipal$CargaRutas.doInBackground(ActivityPrincipal.java:555)
at com.app.mapApp.ActivityPrincipal$CargaRutas.doInBackground(ActivityPrincipal.java:1)
at android.os.AsyncTask$2.call(AsyncTask.java:288)
at java.util.concurrent.FutureTask.run(FutureTask.java:237)
... 4 more
```

Plus all of this is inside of AsyncTask specifically in the method doInBackground

```java
rivate class CargaRutas extends AsyncTask<ItemRuta, ItemRuta, Boolean>{

    @Override
    protected Boolean doInBackground(ItemRuta... items) {
    .
    .
    .
    }
}
```

I use REALM 0.76.0 and Android 5.0

**Comment by cmelchior** [comment]
Hi @ciromine 
From your code it is not clear where the Nullpointer is happening. What is on line ActivityPrincipal.java:555?

**Comment by ciromine** [comment]
My apologies @cmelchior 

The line is:

```java
ruta.getCoordenadas().clear();
```

The problem is: REALM finds "again" the deleted route, but when try to destroy crush the app. Thanks!

**Comment by kneth** [comment]
Realm version 0.76.0 is pretty old. Can you upgrade to the latest and see if the problem persists?

**Comment by emanuelez** [comment]
Also, it's not needed to synchronize realm instances since they can only be used in one thread

**Comment by ciromine** [comment]
@kneth Ok I will try! and I comments you!.

@emanuelez Yes I know, but if I don't used synchronize the update methods, makes problems like the delete. :(

**Comment by emanuelez** [comment]
Can you please elaborate on what problem arise if you don't use synchronize?

**Comment by ciromine** [comment]
The problem is: The ruta (route) "update" his name (for example), but if you gets the name after update, REALM get the previous name.

Maybe is better make a video of this issue, but I will try update REALM and use the remove the synchronize. I will try to do that on the next week. Thanks!

**Comment by emanuelez** [comment]
Thank you @ciromine! Looking forward to an update so we can tackle this one down.

**Comment by ciromine** [comment]
Yes just give me four days and I will probe updating realm.

**Comment by ciromine** [comment]
Doesn't work I got the same problems (I removed the synchronize). I upload a example video: In this when I show a specific route and when updated his name many times, is necessary to update twice for get the change in the name.

[https://www.youtube.com/watch?v=9uz_m5V6xAk&feature=youtu.be](https://www.youtube.com/watch?v=9uz_m5V6xAk&feature=youtu.be)

And the delete method I got same issue, if I try to destroy the route, the route appears, but for the second time, the app crush, because REALM tried to destroy a deleted route.

The deleted issue not appear in the video. Regards!

**Comment by emanuelez** [comment]
Is it possible for you to share your code with us, even in a private way?

**Comment by ciromine** [comment]
Yes I have a github repository, maybe If you have an account I can give you access to view the code. Otherwise if you have another method tell me about it.

**Comment by kneth** [comment]
You could give access to either @cmelchior, @emanuelez or @kneth.

**Comment by ciromine** [comment]
To make more easy I share a dropbox folder with 3 files. After solved this issue I will delete the folder:

- Preview.java: Contains a clean code, with only 3 methods: OnCreate(), CargaRutas() [Where the issue appears] and CargaRutaMapa() [When I show the data from REALM in the map].
- REALM ERROR DIAGRAM.png: A Diagram to explain the all process. Plus the part inside the red square shows the "issue" in the diagram.
- ActivityInicial.java: Contains the all code of the Activity. Use only if you have more doubts after view the last 2 files.

I hope we can find the problem. Thanks a lot guys!

https://www.dropbox.com/sh/vnwt7xjps5j7l18/AAAkPfil6iD2G-Y4MwGNFXwva?dl=0

**Comment by ciromine** [comment]
someone could check my code? Regards!

**Comment by cmelchior** [comment]
Hi @ciromine 
We are all on vacation these days, but will take a look tomorrow. Thank you for the patience.

**Comment by cmelchior** [comment]
Hi @ciromine 
A few observations about your code. 

1) Your stack trace doesn't match the code you sent. Eg. the NullPointer happens here:

```
at com.app.mapApp.ActivityPrincipal$CargaRutas.doInBackground(ActivityPrincipal.java:555)
```
 but line 555 in the file you sent is:

```
if(ruta != null)
```

which can't create a NullPointerException. Has the code that created the NullPointer changed?


2) Are you sure your update problems are related to Realm. Looking at your code where you set the map pins, it isn't clear to me that you actually remove the old pins, which would cause the updated pins to render at the exact same position as the old ones, leaving it up to Google Maps to determine which pin is shown when you click the location.

**Comment by ciromine** [comment]
Hi @cmelchior thanks for your time. I aswer you questions:

1) Sorry for the confusion, the reason of this, is because I removed the Log methods. Actually in my code I have a lot of Logs for inspect the realm problem. And I deleted from the code, to make it less complicated to read.

2) Yes I was thinking that too, but that's not possible, because before use REALM I made the DB of the app in Sqlite and I never had this problem. Plus the update problem is irrelevant to me, but the delete problem is a really a headache, because crush the app.

On the other side, maybe is a specific problem with the speed of REALM and Google maps, I don't know if this is possible? Well if you have another idea to discover the problem? I need to fix that to update the app.

If you need another video or something, tell me please! I will try tonight with the syncronize again, maybe this solve the problem, regards.

**Comment by kneth** [comment]
@ciromine Did you have a chance to look at synchronize? And update to a recent version of Realm?

**Comment by ciromine** [comment]
Guys I update the REALM to the version 0.80.0 and I probe with synchronize. Plus I found an error from my code with the ID. But when delete a route and I received it again I got again a problem and the app crush, but the exception is different:

```java
java.lang.RuntimeException: An error occured while executing doInBackground()
	at android.os.AsyncTask$3.done(AsyncTask.java:300)
	at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:355)
	at java.util.concurrent.FutureTask.setException(FutureTask.java:222)
	at java.util.concurrent.FutureTask.run(FutureTask.java:242)
	at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:231)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1112)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:587)
	at java.lang.Thread.run(Thread.java:841)
Caused by: java.lang.IllegalStateException: Illegal State: Row/Object is no longer valid to operate on. Was it deleted?
	at io.realm.internal.Row.nativeGetLinkView(Native Method)
	at io.realm.internal.Row.getLinkList(Row.java:162)
	at io.realm.RutaRealmProxy.getCoordenadas(RutaRealmProxy.java:30)
	at com.app.ciclobike.ActivityPrincipal$CargaRutas.doInBackground(ActivityPrincipal.java:583)
	at com.app.ciclobike.ActivityPrincipal$CargaRutas.doInBackground(ActivityPrincipal.java:1)
	at android.os.AsyncTask$2.call(AsyncTask.java:288)
	at java.util.concurrent.FutureTask.run(FutureTask.java:237)
	... 4 more
```

The line of the problem is at the arrow:

```java
final Ruta ruta = realm.where(Ruta.class) .equalTo("id", json.getLong("id"))
				                                  .findFirst();
Log.e("ruta",ruta.getNombre()+"");
if(ruta != null)
{
    Log.e("else","eliminé!!!!");
    realm.beginTransaction();
    if(ruta.getCoordenadas().size() > 0) <-----------------------
    ruta.getCoordenadas().clear();
    ruta.removeFromRealm();
    realm.commitTransaction();
}
```

Aparenatly the reason is when the map load again REALM try to delete a deleted route. I probe with the synchronized(realm), but is the same. But maybe with this exception, someone have an idea :+1: . Maybe if I use RealmInstance it's works I think this sunday I have more time to probe again. IF any one have an idea please say it. Thanks guys.

**Comment by cmelchior** [comment]
Hi @ciromine 
You are probably getting that error because you are keeping a reference to ruta even though it has been deleted from another thread. If that can happen you can use:
```
boolean isAlive = ruta.isValid()
```

to check. That will return false either if the object is no longer in the Realm or the Realm has been closed.

**Comment by ciromine** [comment]
Guys I try this:

```
if(ruta.isValid())
{
    Log.e("else","eliminé!!!!");
    realm.beginTransaction();
    if(ruta.getCoordenadas().size() > 0)
    ruta.getCoordenadas().clear();
    ruta.removeFromRealm();
    realm.commitTransaction();
}
```

But I get the same crush and exception. My next step is change the logic for now, because I don't have more time to solve this issue. For now I will mark the routes with a boolean available = false. As I do in the server. After publish the next version of my app. I return to solve this, if anyone prefer close this issue for now, do it. Plus I have another problem with migrations, but this is another issue. Thanks guys and I hope this library will be convert in the best BD.

**Comment by cmelchior** [comment]
Hi @ciromine 
Ok, I will close this for now. But feel free to reopen it. If you have an issue with migrations, feel free to open a new issue so we can take a look at it.
