### ISSUE TITLE
compactRealmFile() doesn't cleanup properly

### ISSUE THREAD

**Issue by cmelchior** [realm/realm-java#953]
If ```Realm.compactRealmFile()``` fails for some reason, the temporary files created might not get deleted. This can leave rather large copies of unused Realm files on the disc.

**Comment by cmelchior** [comment]
Edit: Core has implemented its own compact method on ShareGroup. Use that instead.

**Comment by NielsMylle** [comment]
Any documentation on this?

**Comment by cmelchior** [comment]
There is the JavaDoc: http://realm.io/docs/java/0.80.0/api/io/realm/Realm.html#compactRealmFile-android.content.Context- ?

**Comment by Cilghal** [comment]
How do we use the compact method on ShareGroup?

**Comment by cmelchior** [comment]
You don't :)....SharedGroup is an concept used in the internal API's. From a user perspective you should be using:

```
Realm.compactRealmFile(context, "name");
```

This bug is about the current implementation of that API not cleaning up properly in some cases, but using it has not changed.
