### ISSUE TITLE
Feature Request: support IN-clause 

### ISSUE THREAD

**Issue by njovy** [realm/realm-java#957]
RealmQuery<E>	in(java.lang.String fieldName, java.util.Collection values)
RealmQuery<E>	in(java.lang.String fieldName, java.lang.Object[] values)
in comparison
I used IN clause with NSPredicate quite often in realm-cocoa and this feature should be implemented in realm java as well. It would be useful to have this method in RealmQuery. I am aware that IN clause can be implemented by building or and equalTo but if the method is provided by realm, it would save a few lines of code. Plus a performance can be optimized if it's possible.

**Comment by kneth** [comment]
@njovy Thanks for the suggestion. In #841 similar functionality is discussed.

**Comment by cmelchior** [comment]
Consolidating this feature request here https://github.com/realm/realm-java/issues/841 to avoid to many duplicates.
