### ISSUE TITLE
the data store in local is not always the same with data from server

### ISSUE THREAD

**Issue by machinezhou** [realm/realm-java#963]
hi ,
please help me.
In my recent projects the data store in local database is not always the same with data from server. 

My basemodel.class looks like this：

public class BaseModel{
  private static final String SUCCESS_CODE = "00";
  private static final String INVALID_COOKIE = "10";
  public static final String JSON_ROOT_NAME = "data";

  @SerializedName("statusCode")
  public String statusCode;
  @SerializedName("statusMsg")
  public String statusMsg;
}

then my listmodel.class looks like this:

public abstract class ListModel<T> extends BaseModel {
  @SerializedName(JSON_ROOT_NAME)
  public ArrayList<T> modelList;
}

with retrofit and gson it works fine, but if I want to store the modelList into database without status info, how can I do? For now I can get the List<T> , but realm requires "extends RealmObject", any idea?

**Comment by cmelchior** [comment]
Hi @machinezhou 
Currently Realm doesn't support subclassing (except from RealmObject), so your only choice is to move the fields from BaseMode to your ListModel.

However it is definitely something we want to support going forward, but there are a few hurdles in the core database we have to tackle first. You can follow progress on this here: https://github.com/realm/realm-java/issues/761

**Comment by machinezhou** [comment]
ok then, looking forward. Thanks for your effort.
2015年3月16日 上午4:41于 "Christian Melchior" <notifications@github.com>写道：
