### ISSUE TITLE
Dont work ProGuard

### ISSUE THREAD

**Issue by crysan** [realm/realm-java#965]
Hi!
Did not get automatically generate "Standard getters & setters generated by your IDE ...". When you run the Android Studio says error "No getter found".

My class:
@RealmClass
public class Authors extends RealmObject {

    @PrimaryKey
    private String name;
    private int age;
}

My app.gradle:
apply plugin: 'com.android.application'
android {
    compileSdkVersion 21
    buildToolsVersion "21.1.2"
    defaultConfig {
        applicationId "com.gorayalexander.samlibreaderpro"
        minSdkVersion 14
        targetSdkVersion 21
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled true
            proguardFile 'proguard-project.pro'
            proguardFile getDefaultProguardFile('proguard-android.txt')
        }
    }
}
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    compile 'com.android.support:appcompat-v7:21.0.3'
    compile 'io.realm:realm-android:0.80.0'
}

proguard-android.txt:
-keepnames public class * extends io.realm.RealmObject
-keep class io.realm.** { *; }
-dontwarn javax.**
-dontwarn io.realm.**

**Comment by cmelchior** [comment]
You need to generate getters and setters for all your private fields pr. the documentation: http://realm.io/docs/java/0.80.0/#models

In your case the model class should be: 

```
@RealmClass
public class Authors extends RealmObject {

@PrimaryKey
private String name;
private int age;

  public void setName(String name) {
    this.name = name;
  }

  public String getName() {
    return name;
  }

  public void setAge(int age) {
    this.age = age;
  }

  public int getAge() {
    return age;
  }
}
```

**Comment by crysan** [comment]
Thanks for the reply. However, you will allow me to create these procedures manually? They are not created automatically?

**Comment by cmelchior** [comment]
Yes, you have to create them manually. Realm does not do this for you. However both Eclipse and Android Studio has shortcuts for doing so very fast.

Ie. in Android Studio press CMD + N and select "Getter and Setter"

**Comment by crysan** [comment]
That'S Perfect! Thank you for the clarification!
