### ISSUE TITLE
Dead local variable generated in RealmProxy classes

### ISSUE THREAD

**Issue by kboyarshinov** [realm/realm-java#966]
Methods `populateUsingJsonObject` and `populateUsingJsonStream` in generated RealmProxy classes contain dead local variable `boolean standalone = obj.realm == null;` that never used further. Is it part of some old code that left unremoved or preparation for future features? Noticed that with FindBugs. 

Generation code:
https://github.com/realm/realm-java/blob/master/realm-annotations-processor/src/main/java/io/realm/processor/RealmProxyClassGenerator.java#L721

**Comment by cmelchior** [comment]
That code is generated as the boolean is needed if your modelclass contains either references to other RealmObjects or RealmLists, so in some cases it becomes dead code.

It is mostly a byproduct of Javawriter outputting statements in a streamlike fashion, so having conditional code blocks complicates the annotation processor quite a bit. That said it is probably something we should fix at some point, and we will probably revisit it when migrating to JavaPoet.

**Comment by kboyarshinov** [comment]
Ok, I see that. I'll ignore proxy classes for FindBugs processing.

+1 for JavaPoet migration.
