### ISSUE TITLE
How I can Parse and store a large JSON using RealM ?

### ISSUE THREAD

**Issue by ivanove** [realm/realm-java#968]
Hi, I had an issue I thought  from a while but i can't find a solution.

First, I used this link to create RealmList<MyString> to used in place of List<String> https://github.com/realm/realm-java/issues/575 

this is my error :Caused by: org.json.JSONExcept ion: Value fr at 0 of io.realm.exceptions.RealmException: Could not map Json at io.realm.Realm.createObjectFromJson(Realm.java:860) at com.example.volleyapp2.ImagesActivity$ImagesFragment.loadData(ImagesActivity.java:179) at com.example.volleyapp2.ImagesActivity$ImagesFragment$2.onResponse(ImagesActivity.java:133) at com.example.volleyapp2.ImagesActivity$ImagesFragment$2.onResponse(ImagesActivity.java:127) at com.android.volley.toolbox.JsonRequest.deliverResponse(JsonRequest.java:65) at com.android.volley.ExecutorDelivery$ResponseDeliveryRunnable.run(ExecutorDelivery.java:99) at android.os.Handler.handleCallback(Handler.java:615) at android.os.Handler.dispatchMessage(Handler.java:92) at android.os.Looper.loop(Looper.java:137) at android.app.ActivityThread.main(ActivityThread.java:4921) at java.lang.reflect.Method.invokeNative(Native Method) at java.lang.reflect.Method.invoke(Method.java:511) at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:1027) at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:794) at dalvik.system.NativeStart.main(Native Method) Caused by: org.json.JSONException: Value fr at 0 of type java.lang.String cannot be converted to JSONObject

 and this a part of my JSON where I think the problem : {"application": {"parameters": {"id":999,"account_id":41,"languages":["fr","en"],"url":"","title":"Le Cep","client

and my class model @PrimaryKey private int id; private String myString; public MyString() { } public MyString(int id, String myString) { this.id = id; this.myString = myString; } getter and setter 

so the  problem is my code or something in Realm ??

**Comment by cmelchior** [comment]
The problem is that your language array is an array of primitive strings which Realm doesn't support yet as pr #575. There are a few workarounds:

1) Change your JSON array to be an array of objects instead of strings
2) If you are using GSON you can create a custom deserializer. See here for more info http://stackoverflow.com/questions/28733024/gson-deserialization-of-liststring-into-realmlistrealmstring

**Comment by ivanove** [comment]
Hi, first thank's for your fast response, in the setter of my class model I add a function with split to avoid no words, it works.
