### ISSUE TITLE
Querying for objects using relationship criteria

### ISSUE THREAD

**Issue by mmvicsonvictor** [realm/realm-java#969]
I have Car and Tire realm entities. Classes below:

@RealmClass
public class RealmCar extends RealmObject {

    @PrimaryKey
    private String id;
    private String name;
    private String model;
    private RealmList<RealmTire> tires = new RealmList<RealmTire>();
...
}

@RealmClass
public class RealmTire extends RealmObject {

    @PrimaryKey
    private String id;
    private String name;
    private RealmCar car;
....
}

How do I query for all RealmTire objects which do not have a car reference?

I tried:

        RealmResults<RealmTire> attachedTires = realm.where(RealmTire.class).notEqualTo("car", null).findAll();

Doesn't compile as the notEqualTo clause specification is ambiguous.

Thanks.

**Comment by emanuelez** [comment]
You are looking for all the tires without a car reference so you should use `equalTo` instead of `notEqualTo`, isn't it?

**Comment by vvictor10** [comment]
You are correct. I was messing with this code a bit and when I copy/pasted it, it was not in its original form. But using equalTo() still does not compile though.

**Comment by emanuelez** [comment]
Thank you for the report. Right now there's no clean way to do what you need so we need to add support for query operations on RealmObjects

**Comment by cmelchior** [comment]
This feature is also being tracked here: https://github.com/realm/realm-java/issues/970
So closing this a duplicate.
