### ISSUE TITLE
ClassNotFoundException: io.realm.RealmJsonImpl - Creating FatJar

### ISSUE THREAD

**Issue by xbroak** [realm/realm-java#971]
Hello, I'm generating a jar file for eclipse users, this is a requirement and i cannot simply use maven etc...

I am generating the jar file and all of the class files seem to get included:

http://puu.sh/gDmHf/2338563847.png

As well as my main project files with contains my various realm objects.

Can't understand what's going on here, how do i bundle realm in a jar?

**Comment by cmelchior** [comment]
You are missing all the generated files from the annotation processor, ie. there should be a <ModelClassName>RealmProxy, RealmJsonImpl and ValidationList files as well.

If you are using Eclipse I think they are placed in the .eclipse directory.

**Comment by xbroak** [comment]
I am using Android studio :)

Any way to get gradle to include them?

**Comment by cmelchior** [comment]
Android Studio are placing the generated files in build/intermediates/classes/debug/io/realm, so you can copy them from there. 

But be aware that trying to make a library with RealmObjects to use by app code is currently not possible, which sounds like what you are trying to do.
