### ISSUE TITLE
RecyclerView.Adapter

### ISSUE THREAD

**Issue by crysan** [realm/realm-java#972]
When possible, there is support RecyclerView.Adapter?
Now you can only use http://gradlewhy.ghost.io/realm-results-with-recyclerview/

**Comment by cmelchior** [comment]
Right now Realm doesn't provide a RecyclerView.Adapter. It is definitely something that is on our radar, but that blogpost is an excellent startingpoint for creating your own.

**Comment by cmelchior** [comment]
Closing this as a duplicate as it is already tracked here: https://github.com/realm/realm-java/issues/861

**Comment by slidenerd** [comment]
@crysan read the answer by pirateapp for recyclerview adapter http://stackoverflow.com/questions/28995380/best-practices-to-use-realm-with-a-recycler-view

**Comment by crysan** [comment]
Good!

**Comment by scarings** [comment]
i dont know call contex to get position item for bundle data to other acctivity from adapter with this tutorial http://gradlewhy.ghost.io/realm-results-with-recyclerview/,
