### ISSUE TITLE
Iteration throughs RealmResults and changes elements problem

### ISSUE THREAD

**Issue by lirik16** [realm/realm-java#974]
Hi guys! 

I have a bug in the the process of changing the RealmResults elements. I execute the following line:

final RealmResults<RealmContact> result = realm.where(RealmContact.class).equalTo("sync", false).findAll();

I get the RealmResult objects and try to change its elements:
Version 1

realm.beginTransaction();
for (Contact contact : result) {
    contact.setSync(true);
}
realm.commitTransaction();

If I do it I get the ConcurrentModificationException. I tried to do the way shown below^
Version 2

realm.beginTransaction();
for (int i = 0, size = result.size(); i < size; ++i) {
    result.get(i).setSync(true);
}
realm.commitTransaction();

I get the ArrayIndexOutOfBoundsException. If I do it this way
Version 3

realm.beginTransaction();
for (int i = 0; i < result.size(); ++i) {
    result.get(i).setSync(true);
}
realm.commitTransaction();

The code finished without exception! When setSync(true) is executed the size of RealmResult decreases by one. So if the RealmResult contains 9 elements, and I use Version 3 it changes the value of just half of the elements. The changes occure before we call realm.commitTransaction() that's why we get ArrayIndexOutOfBoundsException and ConcurrentModificationException. 

That is a very strange behavior, and it looks like a bug. In that case in order to change the value of all RealmResult elements I have to use the following code 

realm.beginTransaction();
for (int i = 0; i < result.size(); ) {
    result.get(0).setSync(true);
}
realm.commitTransaction();

I used last (0.80.0) Realm version.

**Comment by cmelchior** [comment]
Yes, it is a known problem when iterating a result set that changes while you iterate, and one we hope to fix soon. You can follow progress on it here: https://github.com/realm/realm-java/issues/640

For your particular case there is workaround explained here: https://github.com/realm/realm-java/issues/789#issuecomment-71325591
