### ISSUE TITLE
Fatal signal 7 (SIGBUS)  again

### ISSUE THREAD

**Issue by ousenko** [realm/realm-java#977]
Hi everyone,
I receive

`A/libc﹕ Fatal signal 7 (SIGBUS) at 0x4d2b5090 (code=2)`

on my app's first launch (db is empty yet) on Lenovo A800 (armeabi-v7, I guess).
App works fine on x86 Genymotion device.

Package name for my app is pretty lengthy, something like: com.fffeeeggghhh.fffeeeggghhhii.
It seems like the crash happens in Realm.getInstance(), which is called upon app startup

**Comment by emanuelez** [comment]
Are you able to share your code (even in a private way) in order for us to try and replicate the issue?

**Comment by hiteshkamani** [comment]
Can any one find solution ? i found this crash when i replace .realm file and access data from it.

**Comment by Zhuinden** [comment]
You shouldn't replace a Realm file that is *open on any threads*.
