### ISSUE TITLE
Android Extendable List View with Realm?

### ISSUE THREAD

**Issue by CyberGriZzly** [realm/realm-java#978]
Hello,

I saw in the examples downloaded with the realm zip that it is possible to directly manipulate a realmresults object with a list view (RealmAdapters example).
My question is that it is possible to manipulate with a expandable list view?
I didn't see a RealmExpandableAdapter<?> or something like that .

**Comment by cmelchior** [comment]
Hi @CyberGriZzly 
Yes Realm currently doesn't provide a RealmExpandableAdapter, and I am not sure we are going to unless demand is really high as those adapters tend to be highly specialized. Also a RealmResults works just like a normal list, so you shouldn't have any trouble making your own. 

The only benefit of RealmBaseAdapter is that it automatically updates whenever something changes, and you you could probably add that functionality to your own ExpandableAdapter by duplicating the logic from https://github.com/realm/realm-java/blob/master/realm/src/main/java/io/realm/RealmBaseAdapter.java
