### ISSUE TITLE
encyption

### ISSUE THREAD

**Issue by idanbar134** [realm/realm-java#985]
Hello,
I have two Realms in my project, i want to encrypt them and to use only one key for both of them. i don't want to create each time the app starts an new key. i looked at your article and it didn't work for me.

i would be very happy for extra support.

Best regards,
Idan

**Comment by cmelchior** [comment]
Hi @idanbar134 
I assume you are talking about: https://github.com/realm/realm-java/blob/master/examples/encryptionExample/src/main/java/io/realm/examples/encryptionexample/EncryptionExampleActivity.java

You have to find a way to store your encryption key somewhere, and then load it when starting the app.
For it to be secure, the best options would probably be:

1) Save it on a server somewhere. It will require that you build an server + API for the app to download an encryption key when starting the app. I don't really have any references for this approach as it is highly dependant on your use case and requirements.

2) Saving it in the Android Keystore (from API 18). You can read more about that approach here: https://developer.android.com/training/articles/keystore.html

3) Manually saving it in SharedPreferences. A less secure approach is described here: http://stackoverflow.com/questions/785973/what-is-the-most-appropriate-way-to-store-user-settings-in-android-application/6393502#6393502

Saving user keys is not really something we can give copy-paste code on as it really depends a lot on the rest of you app architecture and how secure you want it to be.

**Comment by idanbar134** [comment]
Yes. Thank you for the great replay. Very helpful
