### ISSUE TITLE
Unspecified exception when getting Realm instance

### ISSUE THREAD

**Issue by josemando** [realm/realm-java#986]
We are experiencing some production problems on our Android app when we are trying to save the user login information on Realm.
We are currently using realm 0.77.0

Here is the code that is causing the exception:
```
private static final String CURRENT_REALM_VERSION = "realm01";
public static Realm getRealm(Context context) {
	Realm realm = null;
	try {
		// should throw as migration is required
		realm = Realm.getInstance(context, CURRENT_REALM_VERSION);
	} catch (RealmMigrationNeededException ex) {
		Realm.deleteRealmFile(context, CURRENT_REALM_VERSION);
		realm = Realm.getInstance(context, CURRENT_REALM_VERSION);
	}
	return realm;
}
```
And here is the exception:
```
java.lang.RuntimeException: Unspecified exception. Incompatible lock file in io_realm_internal_SharedGroup.cpp line 101
       at io.realm.internal.SharedGroup.createNativeWithImplicitTransactions(SharedGroup.java)
       at io.realm.internal.SharedGroup.<init>(SharedGroup.java:55)
       at io.realm.Realm.<init>(Realm.java:160)
       at io.realm.Realm.createAndValidate(Realm.java:435)
       at io.realm.Realm.create(Realm.java:414)
       at io.realm.Realm.getInstance(Realm.java:332)
       at io.realm.Realm.getInstance(Realm.java:294)
       at ****.RealmWrapper.getRealm(RealmWrapper.java:23)
```

**Comment by cmelchior** [comment]
Hi @josemando 
We have improved the lock file handling in the later versions of Realm, but it would be interesting to know a few details about your app:

- Is it reproducible?
- What Android device is it running on?

**Comment by josemando** [comment]
Hi @cmelchior 
Thanks for the reply, I'll update realm on my project to the latest version.
About your questions:

- I can't reproduce the problem on any of my devices, but I can monitor them happening on crashlytics: on the last 24 hours, this problem caused 134 crashes on 30 users.
- Some of the devices listed by crashlytics: Motorola XT1058, Samsung GT I9505, GT I9515L, GT N7100, Asus T00J

**Comment by cmelchior** [comment]
Interesting. This can also happen if two different versions of Realm access the same realm file. Are you by any chance sharing either the Realm between processes or between apps?

**Comment by josemando** [comment]
No, we are not sharing the Realm between processed nor apps. We use realm to save and load the current user information (id, login, token, etc) and that's it.

**Comment by emanuelez** [comment]
Hello @josemando. Did you manage to reproduce the issue with the latest version of Realm?

**Comment by josemando** [comment]
Hi @emanuelez, we are publishing today a new version of our app using the version Realm 0.80.0
I'll have more data for you by Monday.

**Comment by cmelchior** [comment]
Hi @josemando 
Are you still seeing this issue with your latest release?

**Comment by josemando** [comment]
Hi @cmelchior, I've just checked our Crashlytics data on our latest release and this problems happened 343 times in the last 7 days.
It has happened in these devices: Motorola XT1058 and XT920, ASUS T00J and Samsung GT N5110

**Comment by cmelchior** [comment]
Hi @josemando 
Sorry for the late reply. It is only a few devices, so I assume those crashes are only happening for very few users or am I mistaken about that? 

Also are you in able to share your codebase with us, as that would really help in assessing if you working with Realm in a way that could provoke this. It can be done privately through help@realm.io if you wish.

**Comment by cmelchior** [comment]
Closing due to no response. Please reopen if there is any new information
