### ISSUE TITLE
Create object with values aka. Optimized insert API

### ISSUE THREAD

**Issue by kneth** [realm/realm-java#987]
Creating a new object in a Realm is often done like:

    realm.beginTransaction();
    Person person = realm.createObject(Person.class);
    person.setName("Arthur");
    person.setAge(42);
    realm.commit();

It turns out that the calls to the setters are checking if the `person` object accessed from the correct thread (calling `Realm.checkIfValid())`. And this checking takes up 40-50 % of the time spend in the setters. Typically, creating object and setting the fields' values are always done together, and a simple method could be useful:

    realm.beginTransaction();
    Person person = realm.createObjectWithValues(Person.class, "Arthur", 42);
    realm.commit();

Besides a simpler API for creating objects with values, the method will also increase performance as only one call to `Realm.checkIfValue())` is done.

See also http://stackoverflow.com/questions/29214236/how-to-add-1-milion-items-in-realm-correctly/29216133#29216133

**Comment by cmelchior** [comment]
Merging this into #1684 as it is effectively the same thing
