### ISSUE TITLE
Feature Request: equalsToAny(String fieldName, ValueType... values)

### ISSUE THREAD

**Issue by RobertoArtiles** [realm/realm-java#990]
Hi guys,

Would be very convenient to have a such logical operator:
```Java
equalsToAny(String fieldName, ValueType... values)
```
Or just change equalsTo() to accept varargs.

**Comment by cmelchior** [comment]
Yup, it is something we want to add as well. It is already being tracked here https://github.com/realm/realm-java/issues/841 (Just renamed it for clarity, it was not easy to find). So closing this a duplicate.

**Comment by RobertoArtiles** [comment]
Nice! Good to know.
