### ISSUE TITLE
NPE in instrumentation test while querying RealmObject from main sourceSet

### ISSUE THREAD

**Issue by kboyarshinov** [realm/realm-java#998]
I finally reproduced issue that was submitted in [this SO question](http://stackoverflow.com/questions/28340757/realm-query-equalto-results-in-nullpointerexception).
Exception:

```
Caused by: java.lang.NullPointerException
at io.realm.RealmQuery.getColumnIndices(RealmQuery.java:158)
at io.realm.RealmQuery.equalTo(RealmQuery.java:199)
at io.realm.RealmQuery.equalTo(RealmQuery.java:184)
at com.kboyarshinov.realmtest.RealmObjectsTest$2.execute(RealmObjectsTest.java:43)
```

It happens only in instrumentation test while querying RealmObject like that:

```
realm.where(AppRealmObject.class).equalTo("field", "test").findFirst();
```

`AppRealmObject` is located in main sourceSet. Test is in androidTest sourceSet.
The same with any RealmObject within androidTest sourceSet works fine, e.g. `TestRealmObject`:

```
realm.where(TestRealmObject.class).equalTo("field", "test").findFirst();
```

`TestRealmObject` and `AppRealmObject` are internally identical:

```
@RealmClass
public class TestRealmObject extends RealmObject {
    private String field;

    public String getField() {
        return field;
    }

    public void setField(String field) {
        this.field = field;
    }
}
```

I guess this issue happens due tests are run as separated apk and it creates some file access problem.
Uploaded a reproducible example as zip: https://drive.google.com/file/d/0B4JhrcJuQTe_TktpR1dEWGd0ZkE/view?usp=sharing

Run tests with:

```
./gradlew connectedCheck
```

**Comment by emanuelez** [comment]
Hello @kboyarshinov ,
I tried the zip file you attached but no tests seem to be working there since you are using the new JUnit4 support, which, as far as I know, does not support native code. Can you please try again with normal JUnit3?

**Comment by kboyarshinov** [comment]
@emanuelez Tried. The same result with ActivityInstrumentationTestCase2 and JUnit3.
Sources: https://drive.google.com/file/d/0B4JhrcJuQTe_TVVMaU1adzVrNXM/view?usp=sharing

**Comment by cmelchior** [comment]
Hi @kboyarshinov 
There seems to be some problems with extending ActivityInstrumentationTestCase2. I am guessing it is because using that actually instruments the actual app instead of being part of it, making the Realm annotation processor not working correctly, eg. in your example. It can query TestRealmObject but not AppRealmObject.

Right now you are out of luck, and will have to fall back to extending AndroidTestCase. I have a feeling that our approach for adding support for library projects will also fix this problem, but it will have to be testet first.

**Comment by kboyarshinov** [comment]
@cmelchior Extending `AndroidTestCase` fails too. 
```
public class RealmObjectsTest extends AndroidTestCase {

    private Realm realm;

    @Override
    protected void setUp() throws Exception {
        super.setUp();
        realm = Realm.getInstance(getContext());
    }

    // tests...
}
```

I guess it is TestRunner problem because default [InstrumentationTestRunner](http://developer.android.com/reference/android/test/InstrumentationTestRunner.html) does instrument the app for running tests, all TestCase subclasses, including both `ActivityInstrumentationTestCase2` and `AndroidTestCase`.

**Comment by cmelchior** [comment]
This should be fixed by our library support: https://realm.io/docs/java/latest/#sharing-schemas
